### ISSUE TITLE
can we  increase no of block producers in eos? 

### ISSUE THREAD

**Issue by mark11226** [EOSIO/eos#10018]
HI all
i forked eosio, 
i want to increase bp from 21 to 70 ?
how can i achieve this ? 

Thank you :)

**Comment by heifner** [comment]
You don't need to fork eosio for that. eosio is configurable from 1 to 125 producers.
You just have to modify your system contract:
https://github.com/EOSIO/eosio.contracts/tree/master/contracts/eosio.system
Search for 21.

**Comment by mark11226** [comment]
> You don't need to fork eosio for that. eosio is configurable from 1 to 125 producers.
> You just have to modify your system contract:
> https://github.com/EOSIO/eosio.contracts/tree/master/contracts/eosio.system
> Search for 21.You don't need to fork eosio for that. eosio is configurable from 1 to 125 producers.
You just have to modify your system contract:
https://github.com/EOSIO/eosio.contracts/tree/master/contracts/eosio.system
Search for 21.

if change 21 to 125 ,  then we also need to set 15 to something or it ll automatically set it ?

**Comment by heifner** [comment]
> if change 21 to 125 , then we also need to set 15 to something or it ll automatically set it ?

You can change to any value from 1 to 125 including 70. Not sure what 15 you are asking about.
