### ISSUE TITLE
Docker: eoscpp scaffolding not found

### ISSUE THREAD

**Issue by facadev** [EOSIO/eos#1002]
After pulling the eos docker image, I ran the following command and it failed.
```
root@c03fd0722f54:~# eoscpp -n token
cp: cannot stat '/opt/eos/share/skeleton/.': No such file or directory
```

I checked the folder ("/opt/eos") and found there was only "bin", nothing else.

Also, when I tried to build .cpp into .wasm:
`/opt/eos/bin/eoscpp: line 36: /opt/wasm/bin/clang: No such file or directory`

Possibly a bug or something?

**Comment by avral** [comment]
same error

**Comment by andriantolie** [comment]
This issue is kinda outdated. But for the latest version of eosio, you will need to use eosio/eos-dev to be able to use eosiocpp.
```
docker pull eosio/eos-dev
docker run --rm --name eosio -d -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev  /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console"
alias eosiocpp='docker exec eosio eosiocpp'
```
And then `eosiocpp -n token` will work fine. :)
