### ISSUE TITLE
Failure when refund using My EOS Wallet ("code":500 + code":3050003)

### ISSUE THREAD

**Issue by Hejacke** [EOSIO/eos#10035]
{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: refund request not found","file":"wasm_interface.cpp","line_number":1075,"method":"eosio_assert"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":113,"method":"exec_one"}]}}

Can someone tell me what's going on?

**Comment by heifner** [comment]
I assume you were doing a refund action. 
https://github.com/EOSIO/eosio.contracts/blob/d7bc0a5cc8c0c2edd4dc61b0126517d0cb46fd94/contracts/eosio.system/src/delegate_bandwidth.cpp#L404

**Comment by Toprender** [comment]
I have the same problem. I have already waited 3 days to refund my EOS and I tried to do it manually by eostoolkit.io in the refund stake section but nothing happens. Now I have my EOS frozen and I do not know what to do.
This is my account if someone could check to help me "gy4temrtgene".
Thanks in advance

**Comment by nksanthosh** [comment]
@Toprender Looks like your issue has been resolved per what I can see here https://bloks.io/account/gy4temrtgene - if not please provide additional details by opening a new issue. Thank you.
