### ISSUE TITLE
EOS build failed on MAC OS High Sierra 10.13.2

### ISSUE THREAD

**Issue by fundurian** [EOSIO/eos#1004]
after many hours of building, it actually finish two part of (100%) and then finally it failed

-- Installing: /usr/local/wasm/lib/cmake/llvm/./GetSVN.cmake
-- Installing: /usr/local/wasm/lib/cmake/llvm/./HandleLLVMOptions.cmake
-- Installing: /usr/local/wasm/lib/cmake/llvm/./HandleLLVMStdlib.cmake
-- Installing: /usr/local/wasm/lib/cmake/llvm/./LLVMExternalProjectUtils.cmake
-- Installing: /usr/local/wasm/lib/cmake/llvm/./LLVMInstallSymlink.cmake
-- Installing: /usr/local/wasm/lib/cmake/llvm/./LLVMProcessSources.cmake
-- Installing: /usr/local/wasm/lib/cmake/llvm/./TableGen.cmake
-- Installing: /usr/local/wasm/lib/cmake/llvm/./VersionFromVCS.cmake
Password:
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.60.0

  Boost include path: /usr/local/include

  Detected version of Boost is too old.  Requested version was 1.64 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:68 (FIND_PACKAGE)

-- Using custom FindBoost.cmake
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   coroutine
-- Configuring Eos on OS X
-- BINARYEN_BIN not defined looking in PATH
-- BINARYEN_BIN => /usr/local/binaryen/bin
-- Using WASM clang => /usr/local/wasm/bin/clang
-- Using WASM llc => /usr/local/wasm/bin/llc
-- Using WASM llvm-link => /usr/local/wasm/bin/llvm-link
CMake Error at /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Secp256k1 (missing: Secp256k1_INCLUDE_DIR Secp256k1_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  libraries/fc/CMakeModules/FindSecp256k1.cmake:39 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  libraries/fc/CMakeLists.txt:19 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/phupang/steem/eos/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.

**Comment by acenode** [comment]
same error occurred

**Comment by roycms** [comment]
same error occurred  ?

**Comment by zhuliting** [comment]
@fundurian 
"Requested boost version was 1.64 (ornewer)."

**Comment by fundurian** [comment]
How do you upgrade your boost?

I tried brew install boost, then it say "boost is now version 1.66 but is not link" then i force link it, then when i try install it now saying boost version is 0.0.0, how do i fix this?

**Comment by amshb001** [comment]
@fundurian I met the same error when force link.  I delect all the older versions. and it is no use...

**Comment by pranksteess** [comment]
same error occurred

**Comment by RedaJa** [comment]
I have the same problem. Anyone have found the solution?

**Comment by acenode** [comment]
@RedaJa 
try manual installation.

**Comment by JohnnyHao** [comment]
I also have the same problem

**Comment by JohnnyHao** [comment]
Anyone has resolved this problem ?

**Comment by noprom** [comment]
Hi @fundurian, I also have the same problem, have you solved your problem now?

**Comment by RedaJa** [comment]
I succeed by installing the missing parts manually

**Comment by Olivierlu1** [comment]
@RedaJa you're solution didn't work. @noprom were you able to fix this problem?
