### ISSUE TITLE
EOSIO/eos Wiki - EOS Smart Contract eoscpp tool

### ISSUE THREAD

**Issue by apierp1** [EOSIO/eos#1006]
In order to get the eoscpp tool to work correctly, I had to copy the skeleton contract directory into /usr/local/share/  
This was in a freshly built ubuntu 17.04 VM environment (zesty). May be worth adding something like this step to the wiki:

In order for the eoscpp tool to work you will need to copy the skeleton contract into the /usr/local/share directory. This is done with the following commands:
cd /path_to_eos/contracts
cp -rf ./skeleton /usr/local/share

**Comment by nanonano7** [comment]
the required step should be to `sudo make install` in the build folder which puts everything in the right place.

**Comment by apierp1** [comment]
You sir are a life saver. Any material you recommend to cover that you think would help fill gaps like this?

**Comment by robe** [comment]
I had this same issue but on Mac OS. To remediate I had to symlink the skeleton directory to /usr/local/share.
