### ISSUE TITLE
enable-account-queries causes infinite loop

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#10080]
This has been observed on Telos, WAX, and EOS. Nodes with `enable-account-queries=true` went into 100% CPU usage and stopped responding on HTTP requests.

The triggering event is likely related to a high intensity of forks. Nodes in different parts of the world stopped working at the same block number. It also included internal nodes that are not exposed to public, but having the account queries enabled.

**Comment by matthewdarwin** [comment]
Should be fixed in 2.0.10.

**Comment by heifner** [comment]
Fixed by: https://github.com/EOSIO/eos/pull/10091

**Comment by cc32d9** [comment]
at Mar  2 12:41:04 UTC, EOS Mainnet nodes with account queries enabled went in an infinite loop again. It was a short period of empty blocks and heavy forks.

**Comment by cc32d9** [comment]
there weren't many forks, but it was a period of blocks that were almost empty

**Comment by sanaraufx** [comment]
Could you please share the version # of EOS when reproducing this issue?

**Comment by sanaraufx** [comment]
Per conversation with Kevin, this issue is now fixed and closed.
