### ISSUE TITLE
can not run eosd after building:unable to find genesis file

### ISSUE THREAD

**Issue by aboutyy** [EOSIO/eos#1008]
Detailed information are listed below:
818966ms            chain_plugin.cpp:126          plugin_initialize    ] initializing chain plugin
1818966ms            wasm_interface.cpp:757        get                  ] Runtime::init
1818966ms            http_plugin.cpp:138           plugin_initialize    ] host: 127.0.0.1 port: 8888 
1818966ms            http_plugin.cpp:141           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
1818966ms            net_plugin.cpp:2357           plugin_initialize    ] Initialize net plugin
1818966ms            net_plugin.cpp:2377           plugin_initialize    ] Setting net_plugin logging level to info
1818966ms            net_plugin.cpp:2402           plugin_initialize    ] host: 0.0.0.0 port: 9876 
1818966ms            net_plugin.cpp:2481           plugin_initialize    ] my node_id is 733d4d93ded55a69c2d5b1a09bf7493ee4917e33b1c03200cdb42d8f1bce5635
1818966ms            main.cpp:59                   main                 ] eosd version 233ba4e5
1818967ms            main.cpp:63                   main                 ] 10 assert_exception: Assert Exception
fc::exists( my->genesis_file ): unable to find genesis file '', check --genesis-json argument
    {"f":""}
      chain_plugin.cpp:228 plugin_startup

    {"my->genesis_file.generic_string()":""}
      chain_plugin.cpp:257 plugin_startup

**Comment by egmracer01** [comment]
I ran into this problem too. I fixed it by adding `genesis-json = {path-to-eos-folder}/eos/genesis.json` to the file: `{path-to-eos-folder}/eos/build/programs/eosd/data-dir/config.ini`. I run osx high sierra btw.

**Comment by aboutyy** [comment]
@egmracer01 thank you, problem solved.

**Comment by tcpinedo** [comment]
which one are you supposed to delete the first or second?

**Comment by EdwardJSantos** [comment]
@tcpinedo I believe you are suppose to delete the first one that is set to false. 
I am still having trouble though. The config.ini is referencing the correct genesis.json file, but I receive the following error

```
2535586ms            main.cpp:63                   main                 ] 10 assert_exception: Assert Exception
fc::exists( my->genesis_file ): unable to find genesis file '', check --genesis-json argument
    {"f":""}
      chain_plugin.cpp:228 plugin_startup

    {"my->genesis_file.generic_string()":""}
      chain_plugin.cpp:257 plugin_startup

```
