### ISSUE TITLE
Running a local node connected to the public testnet - BAD FILE DESCRIPTOR

### ISSUE THREAD

**Issue by comtechnet** [EOSIO/eos#1009]
Did a re-pull for the Mac 10.12.6 install and attempted the "connect to the public testnet and got this error.
3159191ms            chain_plugin.cpp:126          plugin_initialize    ] initializing chain plugin
3159192ms            chain_plugin.cpp:158          plugin_initialize    ] Replay requested: wiping database
3159192ms            wasm_interface.cpp:757        get                  ] Runtime::init
3159195ms            http_plugin.cpp:138           plugin_initialize    ] host: 127.0.0.1 port: 8888 
3159217ms            http_plugin.cpp:141           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
3159217ms            wallet_plugin.cpp:34          plugin_initialize    ] initializing wallet plugin
3159217ms            net_plugin.cpp:2357           plugin_initialize    ] Initialize net plugin
3159217ms            net_plugin.cpp:2377           plugin_initialize    ] Setting net_plugin logging level to info
3159217ms            net_plugin.cpp:2402           plugin_initialize    ] host: 0.0.0.0 port: 9877 
3159218ms            net_plugin.cpp:2481           plugin_initialize    ] my node_id is 7f461beb4eef40de7aa05a05cf8a3830270acf06fd367964941767406ce46cbe
3159218ms            main.cpp:59                   main                 ] eosd version 233ba4e5
3160252ms            block_log.cpp:92              open                 ] Opening block log at /Users/comtechnet/eos/build/scripts/testnet_np/blocks/blocks.log
3164465ms            chain_plugin.cpp:250          plugin_startup       ] starting chain in read/write mode
3164465ms            chain_plugin.cpp:255          plugin_startup       ] Blockchain started; head block is #0, genesis timestamp is 2017-12-04T01:00:00
3164466ms            http_plugin.cpp:153           plugin_startup       ] start processing http thread
3164490ms            http_plugin.cpp:210           plugin_startup       ] start listening for http requests
3164491ms            http_plugin.cpp:215           plugin_startup       ] http io service exit
3164491ms            chain_api_plugin.cpp:60       plugin_startup       ] starting chain_api_plugin
3164491ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/abi_bin_to_json
3164491ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/abi_json_to_bin
3164491ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_account
3164491ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_block
3164491ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_code
3164491ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_info
3164492ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_required_keys
3164492ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_table_rows
3164492ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_block
3164492ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_transaction
3164492ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_transactions
3164492ms            account_history_api_plugin.cpp:43 plugin_startup       ] starting account_history_api_plugin
3164492ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/account_history/get_controlled_accounts
3164493ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/account_history/get_key_accounts
3164493ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/account_history/get_transaction
3164493ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/account_history/get_transactions
3164493ms            wallet_api_plugin.cpp:69      plugin_startup       ] starting wallet_api_plugin
3164493ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/create
3164493ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/get_public_keys
3164494ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/import_key
3164494ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/list_keys
3164494ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/list_wallets
3164494ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/lock
3164494ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/lock_all
3164494ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/open
3164494ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/set_timeout
3164494ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/sign_transaction
3164494ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/unlock
3164494ms            net_plugin.cpp:2493           plugin_startup       ] starting listener, max clients is 25
3164533ms            net_plugin.cpp:567            connection           ] created connection to p2p-testnet1.eos.io:9876
3164533ms            net_plugin.cpp:1272           connect              ] host: p2p-testnet1.eos.io port: 9876 
3164790ms            net_plugin.cpp:1403           operator()           ] Error reading message from connection: Bad file descriptor

**Comment by comtechnet** [comment]
Latest pull fixed

**Comment by xu10000** [comment]
the same problem

**Comment by m13oas** [comment]
Same problem with connecting to testnet. download 1,3 M blocks and get this error.
