### ISSUE TITLE
DAWN-371 ⁃ account_history_plugin get accounts not returning account for key

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1010]
Calling:
$ programs/eosc/eosc ~~H testnet2.eos.io~~ p 80 get account shop1

returns:

{
  "account_name": "shop1",
  "eos_balance": "10.9999 EOS",
  "staked_balance": "0.0001 EOS",
  "unstaking_balance": "0.0000 EOS",
  "last_unstaking_time": "1969-12-31T23:59:59",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS7ZYeiRznTn3JobujogjAf3gQitfNcDrqm7n79Zwpehj2EoXLqu",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS8bxfgV9F3aH4oxeqvM2a1LbAa8k5Zw9nxUwBgU16dEFXDGbEFv",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}

but then calling:
programs/eosc/eosc ~~H testnet2.eos.io~~ p 80 get accounts EOS8bxfgV9F3aH4oxeqvM2a1LbAa8k5Zw9nxUwBgU16dEFXDGbEFv
or:
programs/eosc/eosc ~~H testnet2.eos.io~~ p 80 get accounts EOS7ZYeiRznTn3JobujogjAf3gQitfNcDrqm7n79Zwpehj2EoXLqu

doesn't return any account_names. (Repeating the command many times produces the same result, so it is not an issue of some nodes having the data and others not)

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Need to re-test

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

The issue still exists
bash-3.2$ programs/eosc/eosc H testnet2.eos.io p 80 get account shop1
{
  "account_name": "shop1",
  "eos_balance": "10.9999 EOS",
  "staked_balance": "0.0001 EOS",
  "unstaking_balance": "0.0000 EOS",
  "last_unstaking_time": "1969-12-31T23:59:59",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS7ZYeiRznTn3JobujogjAf3gQitfNcDrqm7n79Zwpehj2EoXLqu",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS8bxfgV9F3aH4oxeqvM2a1LbAa8k5Zw9nxUwBgU16dEFXDGbEFv",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}
bash-3.2$ programs/eosc/eosc H testnet2.eos.io p 80 get accounts EOS8bxfgV9F3aH4oxeqvM2a1LbAa8k5Zw9nxUwBgU16dEFXDGbEFv
{
  "account_names": []
}

**Comment by andriantolie** [comment]
Retested on latest code an everything looks good
