### ISSUE TITLE
error when push_transaction through RPC

### ISSUE THREAD

**Issue by gaoqiaizhanglan** [EOSIO/eos#1016]
"code":401,"message":"UnAuthorized","details":"signatures do not satisfy declared authorizations (3030002)\nTransaction declares authority '{\"account\":\"eosgm\",\"permission\":\"active\"}', but does not have signatures for it.

**Comment by gaoqiaizhanglan** [comment]
When use /v1/wallet/sign_transaction, I get the signatures 206112a1290038f7abb0ab677b7f3ac089417c5d748bf95a43c419f6efefcead6b239d98c475da0d2c4e224f18705d243080e76034d4463c52acee674cae9864ca . But when I push_transaction using this signature, it replies an error like that

**Comment by heifner** [comment]
This is not enough information to provide any kind of help. Please use telegram `EOS Developers` for support.
