### ISSUE TITLE
Readme.md does NOT match the initial doc?!

### ISSUE THREAD

**Issue by comtechnet** [EOSIO/eos#1019]
I noticed some unusual doc errors or inconsistency with the readme.md and the instructions 

For example ...

You should see the following response:

spawning child, programs/eosd/eosd --skip-transaction-signatures --data-dir tn_data_0
spawning child, programs/eosd/eosd --skip-transaction-signatures --data-dir tn_data_1
To confirm the nodes are running, run following eosc commands:

~/eos/build/programs/eosc
./eosc -p 8888 get info
./eosc -p 8889 get info
For each command you should get a json with blockchain information.

is WRONG!  ~/eos/build/programs/eosc  should be cd ~/eos/build/programs/eosc

But when I went to create the pull request - i noticed the readme.md is correct on my iMac

Why is this inconsistent?

**Comment by heifner** [comment]
Already fixed.

**Comment by comtechnet** [comment]
Kevin,

Here is a screenshot from 1 minute ago - IT IS NOT FIXED!

Dave
