### ISSUE TITLE
Eos build failed  on Mac os high Sierra 10.13.1

### ISSUE THREAD

**Issue by misiteye** [EOSIO/eos#1020]
CMake Error at plugins/db_plugin/CMakeLists.txt:21 (find_package):
  By not providing "Findlibbsoncxx.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "libbsoncxx", but CMake did not find one.

  Could not find a package configuration file provided by "libbsoncxx" with
  any of the following names:

    libbsoncxxConfig.cmake
    libbsoncxx-config.cmake

  Add the installation prefix of "libbsoncxx" to CMAKE_PREFIX_PATH or set
  "libbsoncxx_DIR" to a directory containing one of the above files.  If
  "libbsoncxx" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/Users/yepeilun/eos/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.

Anyboby can help me?

**Comment by jolestar** [comment]
see https://github.com/EOSIO/eos/blob/DAWN-2018-02-14/plugins/db_plugin/CMakeLists.txt#L36

# sudo apt-get install pkg-config libssl-dev libsasl2-dev
    # wget https://github.com/mongodb/mongo-c-driver/releases/download/1.8.0/mongo-c-driver-1.8.0.tar.gz
    # tar xzf mongo-c-driver-1.8.0.tar.gz
    # cd mongo-c-driver-1.8.0
    # ./configure --disable-automatic-init-and-cleanup --enable-static
    # make
    # sudo make install
    #
    # git clone https://github.com/mongodb/mongo-cxx-driver.git --branch releases/stable --depth 1
    # cd mongo-cxx-driver/build
    # cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
    # sudo make EP_mnmlstc_core
    # make
    # sudo make install
    #
    # sudo apt-get install mongodb

**Comment by Guy-Dvir** [comment]
Got the same problem - did the mongo-c driver and mongo-cxx driver installation manually also...
I can see the mentioned libraries in my /usr/local/lib, each (libbson, libmongocxx) has a folder with the configure files, but I can't seem to find a way to point cmake to them.. even when setting libbsoncxx_DIR to the path, it just wont find it using the find_library() command in the CMakeLists file inside plugins folder....

Any suggestions?

**Comment by WendySanarwanto** [comment]
I tried to build the `dawn-2.x` branch in my Ubuntu 16.04 LTS and got this problem as well. I use latest version of GCC (7.2), Clang version 5, and installed mongodb C library version 1.9.3.

**Comment by 1109993488** [comment]
brew install gcc

**Comment by kkurian** [comment]
See also: https://github.com/EOSIO/eos/issues/1661#issuecomment-373920747

**Comment by pacificcode** [comment]
For Mac OS 10.12 and higher. Proper installation of mongo-cxx-driver (libbsoncxx is included also make sure you have installed pkgconfig i.e. brew install pkgconfig)

cd ~
brew install --force pkgconfig
brew unlink pkgconfig && brew link --force pkgconfig
curl -LO https://github.com/mongodb/mongo-c-driver/releases/download/1.9.3/mongo-c-driver-1.9.3.tar.gz
tar xf mongo-c-driver-1.9.3.tar.gz
rm -f mongo-c-driver-1.9.3.tar.gz
cd mongo-c-driver-1.9.3
./configure --enable-ssl=darwin --disable-automatic-init-and-cleanup --prefix=/usr/local
make -j$( sysctl -in machdep.cpu.core_count )
sudo make install
cd ..
rm -rf mongo-c-driver-1.9.3

git clone https://github.com/mongodb/mongo-cxx-driver.git --branch releases/stable --depth 1
cd mongo-cxx-driver/build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
make -j$( sysctl -in machdep.cpu.core_count )
sudo make install
cd ..
rm -rf mongo-cxx-driver

**Comment by dreson4** [comment]
I have tried everything. keep getting this error. 
I have no idea whats wrong I can't get MongoDB driver to work.
I use macOS high sierra

`
checking if compiler needs -Werror to reject unknown flags... yes
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking whether pthreads work with -mthreads... no
checking for the pthreads library -lpthread... no
checking whether pthreads work with --thread-safe... no
checking whether pthreads work with -mt... no
checking for pthread-config... no
configure: error: libbson requires pthreads on non-Windows platforms.
configure: error: ./configure failed for src/libbson`

**Comment by pacificcode** [comment]
@dreson4 This thread is quite old and EOSIO has changed a great deal since this tread was last responded to. Im going to close this ticket but in the meantime I recommend removing your current clone of the EOSIO repo and starting fresh by running the commands below. If you still run into any issues please create a new ticket and copy and paste the entire output of the commands below into the new ticket. Thank you.

rm -rf /path/to/eos
git clone https://github.com/EOSIO/eos.git --recursive
git submodule update --init --recursive
./eosio_build.sh
