### ISSUE TITLE
request: Linux/Darwin packages and repository

### ISSUE THREAD

**Issue by str** [EOSIO/eos#1021]
Is it possible to get .deb packages instead of needing to build the project from src? It does take a lot of time to build it, and we all are doing the same process to generate the binaries.

**Comment by dearmark** [comment]
good idea , but ti is not realse . no version is stable .

**Comment by taintech** [comment]
Agree, I think it is overkill to build just to run eosd. It would be nice for joiners to adopt.
We could create Docker image and let people to run eos on any platform.

**Comment by asiniscalchi** [comment]
If you run cpack at the end of the build a Deb file is generated

**Comment by str** [comment]
@asiniscalchi  that would be something like:

```
 sudo cpack -G DEB -P eos -R 0.1-`date +%Y%m%d`
```

**Comment by asiniscalchi** [comment]
Just run cpack is already configured in master branch.
Eos-noos cpack patch is waiting merge.

**Comment by str** [comment]
Ohhh... I C, inside the `build` folder. Thank you!

**Comment by str** [comment]
I've just tested cpackage on DAWN-2018-05-16 and same error:

```udo dpkg -i packages/eos.io_4.0.0-1_amd64.deb 
[sudo] password for str: 
(Reading database ... 396368 files and directories currently installed.)
Preparing to unpack .../eos.io_4.0.0-1_amd64.deb ...
Unpacking eos.io (4.0.0) ...
dpkg: error processing archive packages/eos.io_4.0.0-1_amd64.deb (--install):
 unable to create '/usr/local/include/libc++/upstream/test/std/experimental/filesystem/Inputs/static_test_env/dir1/dir2/symlink_to_dir3/file5.dpkg-new' (while processing './usr/local/include/libc++/upstream/test/std/experimental/filesystem/Inputs/static_test_env/dir1/dir2/symlink_to_dir3/file5'): No such file or directory
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 packages/eos.io_4.0.0-1_amd64.deb


```

**Comment by pacificcode** [comment]
@str We are actively working on .deb, .rpm and .dmg packages.
Stay tuned.

**Comment by bitcoiners** [comment]
@pacificcode 
A snap package would be useful.
https://snapcraft.io/

**Comment by str** [comment]
It's still happening in 1.0.8

```
$ cpack 
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: EOSIO
CPack: - Install project: EOSIO
CPack: Create package
CPackDeb: - Generating dependency list
CPack: - package: /home/str/src/eos/build/packages/eos.io_1.0.8-1_amd64.deb generated.

$ sudo dpkg -i packages/eos.io_1.0.8-1_amd64.deb 
(Reading database ... 471225 files and directories currently installed.)
Preparing to unpack .../eos.io_1.0.8-1_amd64.deb ...
Unpacking eos.io (1.0.8) ...
dpkg: error processing archive packages/eos.io_1.0.8-1_amd64.deb (--install):
 unable to create '/usr/local/include/libc++/upstream/test/std/experimental/filesystem/Inputs/static_test_env/dir1/dir2/symlink_to_dir3/file5.dpkg-new' (while processing './usr/local/include/libc++/upstream/test/std/experimental/filesystem/Inputs/static_test_env/dir1/dir2/symlink_to_dir3/file5'): No such file or directory
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 packages/eos.io_1.0.8-1_amd64.deb
```

**Comment by str** [comment]
DEB PACKAGE is available for 1.4.1! Thank you.

Now we just need a repository.

**Comment by josephholsten** [comment]
I'm a big fan of packagecloud.

**Comment by str** [comment]
So, the deb package comes with `cleos, keosd, nodeos`. Should it also come with 
`eosiocpp`?

**Comment by brianjohnson5972** [comment]
eosiocpp is deprecated, so it is not included in the deb package.  cdt has its own deb package that you should use instead.

**Comment by brianjohnson5972** [comment]
There is a lot of baggage in the this old issue and a lot has changed.  Closing this issue.  Please open a new ticket if there are pieces that are still not covered (and not covered in one of the newer tickets covering similar requests).
