### ISSUE TITLE
Unable to unstake EOS due to CPU usage issues

### ISSUE THREAD

**Issue by jsprice87** [EOSIO/eos#10227]
I am unable to unstake any of my EOS due to the following error message:
"Error: billed CPU time (1418 us) is greater than the maximum billable CPU time for the transaction (4 us)"

Resources shows:
CPU Bandwidth
Used 1.53 ms / 0.23 ms

All other sources online have suggested this CPU usage goes up when you make transactions and regenerates over time. I have never made transactions. I got the EOS in the wallet, staked it, and left it. I have checked back for 4 days straight now and this number has not budged. This seems to be a bug.

Please help get this resolved so my assets aren't frozen.

**Comment by matthewdarwin** [comment]
This github is for raising issues about the EOSIO software, not the particulars of how to interact with any particular network (EOS).

EOS has rolled out the PowerUp model.  Discussion about this is happening here: https://t.me/eosresourcemodel for the last few months.

See also: https://eosauthority.com/power/statistics?network=eos
