### ISSUE TITLE
308004 308001 and how to got the cpu and net? 

### ISSUE THREAD

**Issue by 1971192997** [EOSIO/eos#10238]
we use eos to buy net and cpu but still 308004 308001

**Comment by 1971192997** [comment]
really do not what hppened

**Comment by 1971192997** [comment]
can u help to tell me  how to get cpu and net now?

**Comment by matthewdarwin** [comment]
This repo is for EOSIO software issues. You might get more help with EOS at https://t.me/EOSproject

**Comment by sanaraufx** [comment]
Are you having this issue with the latest version (2.0.12)?

**Comment by 1971192997** [comment]
@sanaraufx   powerup works on  2.0.12  ,   and thank u
