### ISSUE TITLE
PowerUp is broken for accounts without resources since 8th of April

### ISSUE THREAD

**Issue by unidwell** [EOSIO/eos#10239]
## Issue

Account without resources should PowerUp, but it can't anymore since **8th of April**. Does one have to have resources to call PowerUp? Does not make sense, looks like a bug.

## How to test it

Execute the following command with any v2.0.10 or v2.0.11 public node:

```
cleos -u <<NODE>> push action eosio powerup '{ "payer": "barasherfoob", "receiver": "barasherfoob", "days": 1, "cpu_frac": "348661516", "net_frac": "3000", "max_payment": "0.0050 EOS"}' -p barasherfoob@active
```

The account `barasherfoob` is an account without any EOS staked into CPU/NET resources.

## What is the result 

The response I get is this: `estimated CPU time (0 us) is not less than the maximum billable CPU time for the transaction (0 us)`

This worked until recently - before the **8th of April**. It looks like that since the **8th of April** the majority of nodes (>v2.0.10) rejects the PowerUp transactions when the account in question does not have enough resources. This is further confirmed since node v2.0.9 accepts the transaction, but it gets dropped later on by consensus.

## Possible reason

Might be connected to: [Consolidated Security Fixes in v2.0.10](https://github.com/EOSIO/eos/pull/10091)

## Related

Related issue (https://github.com/EOSIO/eos/issues/10238).

**Comment by YaroShkvorets** [comment]
Works for me. Have you tried different

**Comment by YaroShkvorets** [comment]
Works on https://eos.greymass.com
Doesn't work on https://eos.eosn.io

Looks like could be related to subjective billing patch https://github.com/EOSIO/eos/pull/10168 ?

**Comment by feri42** [comment]
> Works on https://eos.greymass.com

It does not work on Greymass any more. The transaction is accepted without an error, but then it is not included in the blockchain. Example:
```
cleos -u https://eos.greymass.com push action eosio powerup '{ "payer": "barasherfoob", "receiver": "barasherfoob", "days": 1, "cpu_frac": "348661516", "net_frac": "3000", "max_payment": "0.0050 EOS"}' -p barasherfoob@active 
executed transaction: 7580a86183cf1a0e99a5990972f5fd6d13b5ad7ceef8883ff9617766431526af  144 bytes  475 us
#         eosio <= eosio::powerup               {"payer":"barasherfoob","receiver":"barasherfoob","days":1,"net_frac":3000,"cpu_frac":348661516,"max...
#   eosio.token <= eosio.token::transfer        {"from":"barasherfoob","to":"eosio.rex","quantity":"0.0031 EOS","memo":"transfer from barasherfoob t...
#  eosio.reserv <= eosio.reserv::powupresult    {"fee":"0.0031 EOS","powup_net":286,"powup_cpu":133124586}
#  barasherfoob <= eosio.token::transfer        {"from":"barasherfoob","to":"eosio.rex","quantity":"0.0031 EOS","memo":"transfer from barasherfoob t...
#     eosio.rex <= eosio.token::transfer        {"from":"barasherfoob","to":"eosio.rex","quantity":"0.0031 EOS","memo":"transfer from barasherfoob t...
warning: transaction executed locally, but may not be confirmed by the network yet         ] 

```

**Comment by YaroShkvorets** [comment]
> > Works on https://eos.greymass.com
> 
> It does not work on Greymass any more. The transaction is accepted without an error, but then it is not included in the blockchain. Example:
> 

Might depend on the current producer. Try a few times. Definitely a bug though.

**Comment by feri42** [comment]
> Might depend on the current producer. Try a few times. Definitely a bug though.

we tried about 10 producers at least 50 attempts in total, likely more. The specific result depend only on the producer version. The only certainty is that it does not work anymore.

**Comment by heifner** [comment]
Thanks for the report. We are actively working this issue. In the meantime you can potentially use one of the power-up services to power-up your account so that you can then power-up yourself.

**Comment by 1971192997** [comment]
and this issue resolved now?

**Comment by feri42** [comment]
@heifner , It is not obvious to me from commits, but does 2.0.12 fix this issue?

**Comment by matthewdarwin** [comment]
Yes.

**Comment by heifner** [comment]
> @heifner , It is not obvious to me from commits, but does 2.0.12 fix this issue?

yes.

**Comment by CherryDT** [comment]
I have the same issue but it started happening only around a week ago.

I get "executed" as response but there is no TX on the blockchain. It even happens in Anchor wallet with its built-in powerup function.

**Comment by billy7944** [comment]
My EOS account fmssltdajh11 normally has CPU Used 72.9%, Net Used 0.6%, Ram remaining171.48kb, i can do a emergency power up for 24hrs from a free source & my account CPU drops to Used 2%, but i still cannot do any transactions on the EOS Blockchain, including trying to buy a bigger Power up of 1000EOS for 0.002 EOS, or try to do an exchange transaction PGL/EOS on Newdex. Please can someone advise.
