### ISSUE TITLE
EOS Token Swap from Trezor

### ISSUE THREAD

**Issue by fizzu777** [EOSIO/eos#10251]
Dear developers,

can you please support? I still have EOS ERC20 Token on my Trezor.

Obviously it is impossible to ectract the private keys in order to swap EOS to mainnet.

How can I solve this? Please help.

Thank you!

**Comment by sanaraufx** [comment]
The community has a tool for this, please use this link for further assistance.
[https://eosauthority.com/unregistered?network=eos]
