### ISSUE TITLE
Eosio.names did not refund my bid

### ISSUE THREAD

**Issue by lanhange** [EOSIO/eos#10257]
I bid ‘Start’ on April 8 for 83.0501. then was replaced for 100 by other bidder. But I have not received refund yet.

https://www.bloks.io/transaction/3cf2724104791b3c03a17a62f916d9cbdede28be421553f59269bce0e84efe59

**Comment by matthewdarwin** [comment]
This repo is for EOSIO software issues. You might get more help with EOS at https://t.me/EOSproject

**Comment by sanaraufx** [comment]
Thank you Matt. Closing this issue.
