### ISSUE TITLE
DAWN-401 ⁃ Refactor fc log appender's usage of boost ASIO

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1031]
7feac6b introduced a dependency between FC logging and ASIO and an initialization lifecycle phase for appenders which was necessary for GELF logging.

However, the lifecycle hook is left up to individual applications to micromanage per-appender as seen here:  https://github.com/EOSIO/eos/blob/7feac6b8b1e2ca37f8ecf6727610956a5ddad832/programs/eosd/main.cpp#L39-L40

and the explicit nature of the ASIO dependency resulted in a fragile forward declaration that ended up causing minor hiccups when upgrading boost from 1.65 to 1.66.

We need to refactor these features so that they are better and more cleanly supported:

- [ ] Legitimize the `initialize` lifecycle step and manage it through a single entry point triggered during an appropriate lifecycle hook in the applications (this may require app-base changes)
- [ ] create an internal-only header which defines `initialization_parameters` which has a member for the `io_service` and use a forward declaration of that type in place of boost io-service.  Only the code implementing the single entry point and the code implementing appenders needs to include the internal-only header.  The internal header should include the boost header directly instead of trying to manage a forward declaration to a foreign library.  No need to worry about draconian measures to prevent external files including this file.

**Comment by brianjohnson5972** [comment]
@wanderingbort  Do we want to keep this open?

**Comment by brianjohnson5972** [comment]
Changing released code for minor benefit is not desired, closing.
