### ISSUE TITLE
ok - i got the core eos down / need to move on to Dapps / need best practices

### ISSUE THREAD

**Issue by comtechnet** [EOSIO/eos#1035]
ok,

I'd like to move on to writing and testing some apps that send messages to the core eos contracts i'm creating.

I'd like to see some "best practices" on this kind / level of development.

I don't see anything in the wiki on the docs.

I saw there is some javascript ideas in GH

Any thoughts?

**Comment by bertolo1988** [comment]
Take a look: https://github.com/EOSIO/eos/tree/master/contracts
