### ISSUE TITLE
eosio_2.1.0-1-ubuntu-16.04_amd64.deb Not Found

### ISSUE THREAD

**Issue by melvjoshua** [EOSIO/eos#10394]
Hi,
I tried to download eosio_2.1.0-1-ubuntu-16.04_amd64.deb, but it returns 404 Not Found.
```
wget https://github.com/eosio/eos/releases/download/v2.1.0/eosio_2.1.0-1-ubuntu-16.04_amd64.deb
```

**Comment by nksanthosh** [comment]
As a workaround can you build from source? via instructions at https://developers.eos.io/manuals/eos/latest/install/build-from-source/shell-scripts/index. you need to checkout the tag v2.1.0 and then do a git submodule update --init --recursive to get the correct version of the build

**Comment by melvjoshua** [comment]
I can build it on another server. Thank you @nksanthosh
