### ISSUE TITLE
Will nodeos main process ever be multithreaded?

### ISSUE THREAD

**Issue by phorensic** [EOSIO/eos#10417]
I have tuned and tuned and tuned. It takes me 8+ hours to sync from the freshest snapshot I can get my hands on and 30min-1hr if I restart the server (less than 5 min down time). While the plugins are gloriously multithreaded, it seems to all pipe back in to the parent nodeos process and that becomes a bottleneck. Number of cores for syncing (and when live in production) obviously doesn't matter, so it's down to clock speed (and IPC?). I only have access to a Zen 2 AMD Epyc @ 3.3 GHz at the moment, so I am neutered. I have played with nearly all of the config options. I noticed increasing the fetch from 100 blocks to 500 actually decreases performance. It becomes bursty, but overall lower avg throughput. I have seen one config with 50 blocks per fetch, does that help? I am basically looking for the ultimate config ini for p2p syncing. I am not doing full history, yet, and cannot see that even being possible at this rate. When my server is behind the current head block I am only seeing 100-200 kibps, when I am fully synced it shoots up to 500 kibps. It seemed like the p2p nodes were just rate limiting me or saturated, but then it became clear it is probably my CPU.

I saw one comment on my deep dive through the issues that the main process will never be multithreaded, but I would like to know if that is true.

**Comment by spoonincode** [comment]
> I am basically looking for the ultimate config ini for p2p syncing

A few I would recommend:
* 2.0.x: make sure you're set to `wasm-runtime = eos-vm-jit`, this is default in 2.1.x
* use `eos-vm-oc-enable = true`, at least while syncing/catchup and maybe always depending on your node type
* if you've got 8+ cores set `eos-vm-oc-compile-threads =` to something greater than 1, like maybe 2 or 3. This setting has diminishing returns but if you have a lot of free cores dial it up higher.
* set `chain-state-db-size-mb = ` to something larger than the state of the chain you're following, but no more than 4GB of physical RAM, and make sure it's a multiple of 1024MB. I realize this is a tough number to dial in, and this will hopefully be improved in future versions.
* Reserve enough 1GB hugepages to match the setting you gave to `chain-state-db-size-mb`. This might be something like `echo -n 32 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages` but you'll need to confirm the kernel was able to reserve so much continuous memory by reading the value back. Set it on boot command line for highest success rate.
  * 2.0.x: set `database-hugepage-path =` to a 1GB hugetlbfs mount and then set `database-map-mode = locked`
  * 2.1.x: set `database-map-mode = heap` (no need for hugetlbfs any longer)
* Reduce the number of peers you're connected to. Particularly for syncing/catchup IMO it's better to be connected to a couple good peers vs. having 1 or 2 slow peers out of 10 connections.

> I saw one comment on my deep dive through the issues that the main process will never be multithreaded, but I would like to know if that is true.

2.1 is leaps and bounds faster than 1.0, and we haven't exhausted our list of potential performance improvements yet.

**Comment by phorensic** [comment]
Thank you so much. This was exactly the info I was looking for. I will try these settings and report back.

**Comment by phorensic** [comment]
Syncing like an absolute beast now! But also I upgraded to a Zen 3 @ 4.7 GHz. Only take minutes instead of hours. Thanks!
