### ISSUE TITLE
eosio_build_ubuntu.sh not detecting system correctly

### ISSUE THREAD

**Issue by jacojoubert12** [EOSIO/eos#10410]
eosio_build_ubuntu.sh gives the following output on an Ubuntu 18.04 system with 64GB memory installed:

```
./eosio_build_ubuntu.sh
OS name: 
OS Version: 
CPU cores: 
Physical Memory: G
Disk space total: G
Disk space available: G
 - You must be running 16.04.x or 18.04.x to install EOSIO.
```

**Comment by spoonincode** [comment]
You should just run `eosio_build.sh`, not `eosio_build_ubuntu.sh` -- `eosio_build_ubuntu.sh` will be run by `eosio_build.sh`

**Comment by jacojoubert12** [comment]
Ok, Thank you!
