### ISSUE TITLE
GE 

### ISSUE THREAD

**Issue by alphabetleev** [EOSIO/eos#10438]
GE，全称GE Network,是首个基于EOS链的去中心化金融协议，集保险、理财于一体的金融代币，采取最先进的持币收益机制。所有者可通过持有GE来获取EOS价值币，且在协议的未来发展中拥有决策权。![images.png](https://user-images.githubusercontent.com/77619267/122492647-bb979c80-d018-11eb-82b2-f0a4dd6c8c70.png)

Telegram: https://t.me/joinchat/xQtIWNlobpZmNzhl

**Comment by sanaraufx** [comment]
Thank you for the information. Please let us know if you encounter any EOSIO-related issues.
