### ISSUE TITLE
你们有没有点开来看过每天的commit

### ISSUE THREAD

**Issue by jinhefeng** [EOSIO/eos#1044]
虽然每天都有更新，但是都是一些小修改比如把 this.EOS 改成 EOS啊...在某几行之前加个回车啊什么的

**Comment by quan0012** [comment]
你这么一说还真是.....

**Comment by Louis778** [comment]
只是这几天吧？兄弟

--
Sincerely
Louis Luo
Cell Phone: 778-986-8827
Email: luosenzs@hotmail.com<mailto:luosenzs@hotmail.com>

在 2018年1月7日，上午7:41，Jin <notifications@github.com<mailto:notifications@github.com>> 写道：


虽然每天都有更新，但是都是一些小修改比如把 this.EOS 改成 EOS啊...在某几行之前加个回车啊什么的

**Comment by 344303947** [comment]
bytemaster  改了些代码，感觉其他人就是改一些 read.md

**Comment by yca2220206** [comment]
Please do not rub it, please speed up the project, to the good news, or investors want to despair @nathanhourt

**Comment by yca2220206** [comment]
这只能说明一个问题，目前3.0版本到了后期测试了，已经快稳定了。

**Comment by lai3d** [comment]
Please check the "eos-noon" branch also, not only the "master", BM has just commit huge amount of code. 

Showing  278 changed files  with 39,639 additions and 21 deletions.

大哥，你看下eos-noon分支啊，你看BM一次提交有多少代码！

**Comment by kuixiansheng** [comment]
这哥们是不是才了解git,不知道代码多分支多版本，master是项目最稳定的版本

**Comment by lai3d** [comment]
分支上开发好了，测试通过了，才合并到master上嘛，大公司基本是这个流程

**Comment by 344303947** [comment]
BM good~

**Comment by zw0** [comment]
issues 也不是这么用的
👎

**Comment by dreamlikey** [comment]
eos几十个分支

**Comment by leoloe326** [comment]
这样的讨论既打扰人又没什么价值，还是不要继续了吧。

**Comment by zw0** [comment]
@jinhefeng 把这个close掉吧

**Comment by yca2220206** [comment]
Our investors want to BM accelerate the development progress, give some good news , Otherwise eos ranking more and more by the post，This love of deep, hopeful, there is no mistake in itself

**Comment by windpls** [comment]
Opps! It's a very bad idea to complain here. Please close this issue and talk about the price on Telegram or elsewhere

**Comment by pmesnier** [comment]
Please note that github issues are intended to be used for reporting defects or submitting pull requests. 

For general questions about the development effort on the EOSIO core, visit https://eos.io or one of the many EOSIO related channels on telegram. 

Thank you.

**Comment by sunyoubo** [comment]
哈哈， 这是来搞笑的

**Comment by flyq** [comment]
新手，请问测试链上线了吗，多久上线？
我现在还在看solidity开发
