### ISSUE TITLE
Unable to decode transfer of asset action with cleos

### ISSUE THREAD

**Issue by RedCuckoo** [EOSIO/eos#10459]
When trying to decode transfer action from the hex, got from trace_api, I am unable to do so with
```
cleos convert unpack_action_data eosio.token transfer 00785e20fb5a1dc400785ea0c8879d8e0196d300000002000000
```
With the following output:
```
Error 3015013: Unpack data exception
Error Details:
Unable to unpack built-in type 'asset' while processing 'transfer.quantity'
read datastream of length 26 over by -1
error unpacking uint64_t
Error unpacking field m_value
error unpacking eosio::chain::symbol
Error unpacking field sym
error unpacking eosio::chain::asset
```
The hex was obtained from _trace_api/get_block_ endpoint.
It can't find quantity, because the actual data is _asset_ids_ field:
```
"data": {
    "from": "skippyt.ftw",
    "to": "luisjm5.ftw",
    "asset_ids": [
        "2199023309718"
    ],
    "memo":""
}
```
This info obtained from _chain/get_block_ endpoint.

The hex provided in this example is from block __#189039769__, transaction id __4825af582213461e67ca97165943866c41ded16eabb628793c98fe658562b910__ [this transaction on bloks.io](https://www.bloks.io/transaction/4825af582213461e67ca97165943866c41ded16eabb628793c98fe658562b910)

**Comment by praphael** [comment]
Hi RedCuckoo what is the output of `cleos version full`

**Comment by RedCuckoo** [comment]
Hi @praphael , the output is:
```
cleos version full
v2.1.0-26a4d285d0be1052d962149e431eb81500782991
```

**Comment by praphael** [comment]
@RedCuckoo It looks like the contract is `atomicassets`, yet you are using `eosio.token` in your attempt to unpack.   Have you tried using `atomicassets` in `cleos convert` ?

**Comment by RedCuckoo** [comment]
@praphael No, I haven't, now that I tried, it works as expected. Excuse me for bothering you, it was my fault using it with wrong parameters.

**Comment by praphael** [comment]
> @praphael No, I haven't, now that I tried, it works as expected. Excuse me for bothering you, it was my fault using it with wrong parameters.

No problem, happy to help!
