### ISSUE TITLE
DAWN-376 ⁃ migrate account_history_plugin to eos-noon branch

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1046]
(This ATC needs to be fixed once DAWN-466 has been merged)

ATC:
Can be run on local or public testnet (if public testnet, then node2 will need to be a local eosiod node that connects to the public testnet)
After each interaction using eosioc to communicate with the testnet, record the transaction_id that is returned.
Your eosioc will either connect with node1 or node2.  Steps #1 - #7 can be performed on either node. node1's config.ini file should not have any "filter_on_accounts = ..." lines.  node2's config.ini should have "filter_on_accounts = tester1" and "filter_on_accounts = tester11"
All corresponding private keys need to be imported into wallet for below used public keys.
1) create an account "tester1" (or choose your own name) with different owner and active public keys, using the existing "inita" account
2) create an account "tester2" (or choose your own name) with different owner and active public keys, using the existing "inita" account
3) create an account "tester11" (or choose your own name) with different owner and active key pair, using the existing "inita" account
4) create an account "tester21" (or choose your own name) with the same owner key pair used for "tester1” and the same active key pair used for "tester2”, using the existing "inita" account
5) transfer 100 EOS from "inita" to "tester1"
6) transfer 200 EOS from "inita" to "tester2"
7) transfer 100 EOS from "tester2" to "tester11"
8) run eosioc multiple times passing in ”get transaction " followed by the transaction_ids for #1-#7 above, and verify the returned transaction contains data consistent with the corresponding activity when connecting to node1, and should only return the transactions from #5 and #7 for node2
9) run eosioc passing in "get accounts ” followed by the owner public key for "tester1" and verify that an array with "tester1" and "tester21" is returned for node1, and nothing is returned for node2
10) run eosioc passing in "get accounts ” followed by the active public key for "tester1" and verify that an array with just "tester1" is returned for node1 and nothing for node2
11) run eosioc passing in "get accounts ” followed by the owner public key for "tester2" and verify that an array with just "tester2" is returned for node1 and nothing is returned for node2
12) run eosioc passing in "get accounts ” followed by the active public key for "tester2" and verify that an array with "tester2" and "tester21" is returned for node1 and nothing is returned for node2
13) run eosioc passing in "get accounts ” followed by the owner public key for "tester11" and verify that an array with just "tester11" is returned for node1 and nothing is returned for node2
14) run eosioc passing in "get accounts ” followed by the active public key for "tester11" and verify that an array with just "tester11" is returned for node1 and nothing is returned for node 2
15) run eosioc passing in "get servants " followed by "inita" and verify an array with "tester1" and "tester2" is returned for node1 and "tester1" for node2
16) run eosioc passing in "get servants " followed by "tester1" and verify nothing is returned for node1 and node2
17) run eosioc passing in "get servants " followed by "tester2" and verify nothing is returned for node1 and node2
18) run eosioc passing in "get servants " followed by "tester11" and verify nothing is returned for node1 and node2
19) run eosioc passing in "get servants " followed by "tester21" and verify nothing is returned for node1 and node2
20) run eosioc passing in "get transactions " followed by "inita” and verify that the transactions returned by #6, #5, #4, #3, #2, and #1 are returned in an array (in that order) for node1, and  only #5 for node2
21) run eosioc passing in "get transactions " followed by "tester1” and verify that the transactions returned by only #5 are returned in an array by node1 and node2
22) run eosioc passing in "get transactions " followed by "tester2” and verify that the transactions returned by #7 and #6 are returned in an array (in that order) for node1 and only #7 for node2
23) run eosioc passing in "get transactions " followed by "tester11” and verify that the transaction returned by only #7 are returned in an array for node1 and node2
24) run eosioc passing in "get transactions " followed by "tester21” and verify that an empty array is returned by node1 and node2
25) run eosioc passing in "get transactions " followed by "inita 1 2” (start at seq #1 and returns 2) and verify that the transactions returned by #5 and #4 are returned in an array (in that order) for node1 and an empty array for node2

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

[~bart.wyatt] [~kevin.heifner] I'm planning to just return the signed_transaction, and not worry about the outputs that used to be returned also for get_transaction.

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

Everything is ported over to eos-noon, but need to test with new launcher and eosioc merges, so that I can verify that everything is working.

**Comment by wanderingbort** [comment]
I'm going to close this as the ticket for initial work, if we add features we can do so in a new ticket
