### ISSUE TITLE
Command Error in https://github.com/EOSIO/eos/wiki/Command%20Reference (get transactions vs get transaction)

### ISSUE THREAD

**Issue by comtechnet** [EOSIO/eos#1052]
Another Doc ERROR - currently reads ...

Get transactions by account | $ eosc get transaction ${account} | View
-- | -- | --

should be 

$ eosc get transaction**s** ${account}

(note it should be plural!)

**Comment by PaulCalabrese** [comment]
Fixed. Thanks for pointing this out.
