### ISSUE TITLE
DAWN-456 ⁃ Add ability to reload logging configuration on the fly

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1057]
eosiod needs to be able to change logging levels without restarting.  Add the ability to reload the logging configuration on the fly.

#### Prerequisites
* A local test net with a single `eosiod` process on the test machine running the newest code

#### Side Effects
* Ordinarily expected log messages will not be present in the log

#### Procedure
1. With `eosiod` running, verify its `stderr.txt` is present and updating.
1. Edit `logging.json` for the running `eosiod`:

* In the `loggers` section, in the value for `"level"`, change `"info"` to `"warn"`

1. Send `SIGHUP` to `eosiod`:

* `pkill -HUP eosiod`

1. Verify "`Received HUP.  Reloading logging configuration.`" appears in `stderr.txt` and `Info` and below log messages no longer appear.  In particular "`Not producing block because it isn't my turn`" will stop appearing.
1. Edit `logging.json` for the running `eosiod`:

* In the `loggers` section, change `"warn"` to `"info"`

1. Send `SIGHUP` to `eosiod` as before.
1. Verify "`Not producing block because it isn't my turn`" appears in `stderr.txt` again.  No "Received HUP" message is expected, as it is logged with `Info` priority.
1. Edit `logging.json` for the running `eosiod`:

* In the `loggers` section, change `"debug"` to `"bogus"`

1. Send `SIGHUP` to `eosiod` as before.
1. Verify configuration file is rejected with `7 bad_cast_expection: Bad Cast` and `Expected 'all|debug|info|warn|error|off', but got 'bogus'` and logging continues as before.

**Comment by comtechnet** [comment]
./eosc get status needs to provide this level of detail - what test/live net am I connected to and what are my parms (servers and ports, etc.)

**Comment by jgiszczak** [comment]
@comtechnet You should post your comment as a separate ticket.  It sounds like a good idea that should be tracked.

**Comment by wanderingbort** [comment]
closed by #1058
