### ISSUE TITLE
Support wasm3 engine

### ISSUE THREAD

**Issue by jnordberg** [EOSIO/eos#10594]
[wasm3](https://github.com/wasm3/wasm3) is a performant WebAssembly engine that could improve the contract execution performance 

Benchmarks:

![image](https://user-images.githubusercontent.com/95886/128130717-baa97bee-5c64-4632-9a20-302776af5f92.png)
![image](https://user-images.githubusercontent.com/95886/128130765-be4890b7-4a05-4a36-a703-22c4d6121e80.png)

More benchmark data and methodology found here https://github.com/vwasm-staging/benchmarking

**Comment by spoonincode** [comment]
Those benchmarks seem to be using EOS VM interpreter. The interpreter is not really designed for maximum speed, but rather for other potential opportunities (such as a possible debugger), and also as a sort of "reference" runtime to compare against our other more advanced runtimes via our large unit test suite. nodeos, by default, does not use the interpreter to execute smart contracts.

The chance of EOSIO ever using something other then EOS VM is just about zero. We've made the decision that engineering and maintaining our own runtime is the best option for us. There are many reasons why. One example, in being a pioneer utilizing WebAssembly for smart contracts we managed to bake in some WASM spec violations around fringe corner cases in to the EOSIO consensus protocol. Other standard complaint WASM runtimes will likely balk at these violations meaning we'd need to maintain a fork of any such runtime _forever_.

Certainly our plan is to continue improving EOS VM JIT & EOS VM OC performance.

**Comment by jnordberg** [comment]
Could you point me to some reference on how to setup an executable that takes a wasm file and executes it using the JIT or OC methods (like bench_interp in the eos-vm tools)? I'm very interested in seeing how the benchmarks would look using those faster modes.

**Comment by spoonincode** [comment]
It should be fairly easy for EOS VM JIT -- just a different template specialization when constructing `eosio::vm::backend<>`. I can provide an example to help, but it may be a few days or a week, unless someone else jumps in.

EOS VM OC is more tricky, and there isn't really a reasonable approach besides bundling your test in to a contract and executing it that way.

**Comment by conr2d** [comment]
@jnordberg

You can refer to [this](https://github.com/conr2d/eos-vm/blob/7f933996/tools/jit.cpp) that I wrote.
It supports eos-vm with JIT mode and includes some WASI implementations to run benchmarks from other runtimes.

**Comment by spoonincode** [comment]
@conr2d nice work. Let us know what you discover @jnordberg

**Comment by jnordberg** [comment]
Thanks @conr2d, with that I was able to get the benchmark suite running with the jit backend 🎉 

Results

<img width="1052" alt="Screen Shot 2021-08-20 at 16 16 21 " src="https://user-images.githubusercontent.com/95886/130195290-b6637063-a8b5-4c2f-b730-66dabdfb91c4.png">

**Comment by jnordberg** [comment]
Looking at more heavy workloads

![bench2](https://user-images.githubusercontent.com/95886/130303707-8ff22b67-10da-43ed-9f22-b4a6a586ee7c.png)

**Comment by spoonincode** [comment]
Thanks for testing; Going to close this out, as there really isn't any action for us to take.
