### ISSUE TITLE
EOS transaction fee model

### ISSUE THREAD

**Issue by 0xfnzero** [EOSIO/eos#10599]
EOS registered account should be free, accounts can be random, transaction costs as the ETH use gas mode, gas can burn to deflation, I think this is the most perfect model, EOS is now way for a new user is a nightmare, this design is very bad, completely is to use technical thinking instead of thinking doing products, this is a very bad product

**Comment by aclark-b1** [comment]
Hi @wangwei123 thank you for the feedback.  EOSIO is extremely flexible and powerful, but we realize that introduces a great deal of complexity as well.  We have several training videos that are currently free, hopefully these will help.  
[https://training.eos.io/](https://training.eos.io/ )
