### ISSUE TITLE
v2.2.0-rc upgrading failed

### ISSUE THREAD

**Issue by issaxyz** [EOSIO/eos#10637]
we are upgrading from v2.0.12 to v2.2.0-rc (since 2.1.0 with bug of https://github.com/EOSIO/eos/issues/10435), but the upgrade failed, error log shows:

`APPBASE: Warning: The following configuration items in the config.ini file are redundantly set to
         their default value:
             contracts-console, access-control-allow-credentials, allowed-connection
         Explicit values will override future changes to application defaults. Consider commenting out or
         removing these items.
info  2021-08-19T03:37:07.778 nodeos    blockvault_client_plug:47     plugin_initialize    ] no block-vault-backend option is specified, skipping it
info  2021-08-19T03:37:07.778 nodeos    chain_plugin.cpp:717          plugin_initialize    ] initializing chain plugin
info  2021-08-19T03:37:07.779 nodeos    chain_plugin.cpp:537          operator()           ] Support for builtin protocol feature 'PREACTIVATE_FEATURE' (with digest of '0ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd') is enabled without activation restrictions
info  2021-08-19T03:37:07.779 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'ONLY_LINK_TO_EXISTING_PERMISSION' (with digest of '1a99a59d87e06e09ec5b028a9cbb7749b4a5ad8819004365d02dc4379a8b7241') is enabled with preactivation required
info  2021-08-19T03:37:07.779 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'FORWARD_SETCODE' (with digest of '2652f5f96006294109b3dd0bbde63693f55324af452b799ee137a81a905eed25') is enabled with preactivation required
info  2021-08-19T03:37:07.779 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'WTMSIG_BLOCK_SIGNATURES' (with digest of '299dcb6af692324b899b39f16d5a530a33062804e41f09dc97e9f156b4476707') is enabled with preactivation required
info  2021-08-19T03:37:07.779 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'REPLACE_DEFERRED' (with digest of 'ef43112c6543b88db2283a2e077278c315ae2c84719a8b25f25cc88565fbea99') is enabled with preactivation required
info  2021-08-19T03:37:07.779 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'NO_DUPLICATE_DEFERRED_ID' (with digest of '4a90c00d55454dc5b059055ca213579c6ea856967712a56017487886a4d4cc0f') is enabled with preactivation required
info  2021-08-19T03:37:07.779 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'RAM_RESTRICTIONS' (with digest of '4e7bf348da00a945489b2a681749eb56f5de00b900014e137ddae39f48f69d67') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'WEBAUTHN_KEY' (with digest of '4fca8bd82bbd181e714e283f83e1b45d95ca5af40fb89ad3977b653c448f78c2') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'BLOCKCHAIN_PARAMETERS' (with digest of '5443fcf88330c586bc0e5f3dee10e7f63c76c00249c87fe4fbf7f38c082006b4') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'DISALLOW_EMPTY_PRODUCER_SCHEDULE' (with digest of '68dcaa34c0517d19666e6b33add67351d8c5f69e999ca1e37931bc410a297428') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'RESOURCE_PAYER' (with digest of '808c49387292c34ccb3970e00b08a690b6b3370c1cbcec46d46c19d5dfafab03') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'KV_DATABASE' (with digest of '825ee6288fb1373eab1b5187ec2f04f6eacb39cb3a97f356a07c91622dd61d16') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'ONLY_BILL_FIRST_AUTHORIZER' (with digest of '8ba52fe7a3956c5cd3a656a3174b931d3bb2abb45578befc59f283ecd816a405') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'RESTRICT_ACTION_TO_SELF' (with digest of 'ad9e3d8f650687709fd68f4b90b41f7d825a365b02c23a636cef88ac2ac00c43') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'CONFIGURABLE_WASM_LIMITS' (with digest of 'bf61537fd21c61a60e542a5d66c3f6a78da0589336868307f94a82bccea84e88') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'ACTION_RETURN_VALUE' (with digest of 'c3a6138c5061cf291310887c0b5c71fcaffeab90d5deb50d3b9e687cead45071') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'SECURITY_GROUP' (with digest of 'ded2e25adcd78cbb94fa7f63a8f80a9af2b1a905e551a6e124e7d7829da1ea02') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'FIX_LINKAUTH_RESTRICTION' (with digest of 'e0fb64b1085cc5538970158d05a009c24e276fb94e1a0bf6a528b48fbc4ff526') is enabled with preactivation required
info  2021-08-19T03:37:07.780 nodeos    chain_plugin.cpp:524          operator()           ] Support for builtin protocol feature 'GET_SENDER' (with digest of 'f0af56d2c5a48d60a4a5b5c903edfb7db3a736a94ed589d0b797df33ff9d3e1d') is enabled with preactivation required
warn  2021-08-19T03:37:07.781 nodeos    chain_plugin.cpp:1297         plugin_initialize    ] 3110006 plugin_config_exception: Incorrect plugin configuration
Genesis state is necessary to initialize fresh blockchain state but genesis state could not be found in the blocks log. Please either load from snapshot or find a blocks log that starts from genesis.
    {}
    nodeos  chain_plugin.cpp:1129 plugin_initialize

error 2021-08-19T03:37:07.781 nodeos    main.cpp:163                  main                 ] 3110006 plugin_config_exception: Incorrect plugin configuration
Genesis state is necessary to initialize fresh blockchain state but genesis state could not be found in the blocks log. Please either load from snapshot or find a blocks log that starts from genesis.
    {}
    nodeos  chain_plugin.cpp:1129 plugin_initialize
rethrow
    {}
    nodeos  chain_plugin.cpp:1297 plugin_initialize`

start script:
`nodeos -d  --plugin eosio::chain_plugin 
 --plugin eosio::http_plugin 
 --plugin eosio::net_plugin 
 --plugin eosio::chain_api_plugin `

And the nodeos cannot downgrade to v2.0.12 any more, I thought this should be warned to node maintainer in release introduction.

**Comment by sanaraufx** [comment]
Please check out the Upgrading from previous versions of EOSIO section in the most recent release notes. We will take your suggestion into consideration for future releases. https://github.com/EOSIO/eos/releases/tag/v2.2.0-rc1
