### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by xloem** [EOSIO/eos#10638]
Is it presently possible to run eos on arm?

I tried building on aarch64/arm64 and encountered build errors due to wasm runtimes being used that were missing, due to lines like this only providing for x86_64: https://github.com/EOSIO/eos/blob/11d35f0f934402321853119d36caeb7022813743/CMakeLists.txt#L72

**Comment by spoonincode** [comment]
ARM8 has never been officially supported. Unofficially 2.0 was known to run and pass unit tests at one point (I haven't tried 2.0.12), but it will be limited to the slower wabt runtime so it will be tough to run a node on public networks. If you're looking for something like cleos support, it will work fine. Keep in mind 2.0 is just about end of life though.

Neither 2.1 nor 2.2 will work on ARM8 at all.

**Comment by xloem** [comment]
Thank you.  I have mostly arm systems; it's unfortunate.  It could be good to make this clear somewhere.
