### ISSUE TITLE
./build.sh file is missing EOSIO windows

### ISSUE THREAD

**Issue by apock666** [EOSIO/eos#10646]
hey guys i have recently installed EOSIO following the technique bellow:
https://steemit.com/eos/@tokenika/installing-and-running-eos-on-windows
but i can not find the build.sh. i have also tried going threw the ./scripts directory with no luck aswell using this code
./scripts/eosio_install.sh
which gives me this
 ":/mnt/c/Workspace/eos# ./scripts/eosio_install.sh
./scripts/eosio_install.sh: line 41: set: -i: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]"

I am up to step 5 as bellow: 

"Now you are ready to proceed with the actual compilation of the source code. This step can take several hours, depending on your computer's power, and will require you to intermittently confirm some actions and also to supply the sudo password.
cd ${EOSIO_INSTALL_DIR}
./build.sh ubuntu full
NOTE: As this process requires downloading a lot of files from various sources, it might fail. In this case just try running this step again."

**Comment by matthewdarwin** [comment]
This article is 4 years old.  Better to review latest information on developers.eos.io

https://developers.eos.io/manuals/eos/latest/install/build-from-source/index

**Comment by praphael** [comment]
Windows is not currently supported at the time.   You should be able to run through a  Linux VM such as VirtualBox.

**Comment by sanaraufx** [comment]
Closing this issue out. Please reopen if needed.
