### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#1069]
```
~/eos/Docker# docker build . -t eosio/eos
Sending build context to Docker daemon 16.38 kB
Step 1 : FROM ubuntu:16.04 as builder
Error parsing reference: "ubuntu:16.04 as builder" is not a valid repository/tag
```

**Comment by wanderingbort** [comment]
multi-stage builds are only available in docker `17.05` or higher.  What version of docker are you using?

**Comment by bitcoiners** [comment]
docker --version
Docker version 1.12.6, build 78d1802
will upgrade

**Comment by bitcoiners** [comment]
after upgrading to
Docker version 17.12.0-ce
build

**Comment by richardmax** [comment]
Hi EOSers (golly that doesnt look right!)
Docker build fails..... details below.

Docker Version: 17.12.0-ce-mac49 (21995) [ABOVE 17.05!]
Log:
Step 19/26 : COPY --from=builder /opt/eosio/bin /opt/eosio/bin
COPY failed: stat /var/lib/docker/overlay2/5f632b46e8ae8f05b134be25fe2600906c5330eb95b7260f467360781b6b8e9f/merged/opt/eosio/bin: no such file or directory
