### ISSUE TITLE
DAWN-470 ⁃ add lazy enforcement of account-scope-table key usage

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1072]
in eos-noon need to add back in the lazy enforcement of key usage per account-scope-table.  It will not enforce the abi table definition.

**Comment by wanderingbort** [comment]
here is the table where we are storing table id's.  We can add in observed type information in this table:

https://github.com/EOSIO/eos/blob/3f94e2a5742b55ed83dfe2a078b38f02f6bfb52a/libraries/chain/include/eosio/chain/contracts/contract_table_objects.hpp#L17-L42

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

[~bart.wyatt] Will this type restriction last forever?  Or would we reset it for a contract change?  (Or another reason?)  [~kevin.heifner] talked about there being an indication that could be put on the ABI that would say to not perform this check, do you know about this?

**Comment by blockone-syncclient** [comment]
➤ Bart Wyatt commented:

I think this type restriction lasts forever.  We don't have a real succinct plan for database upgrades on contract upgrades but I assume it involves reading the old tables, rewriting migrated data to new tables then abandoning/deleting the old tables. 

Also, nothing about ABI should be used for any hard validations.  the only reason the ABI is "on-chain" is because there is not a better repository for our client tools.  Ideally, one day there will be several chain-backed repositories for information about code (maybe source maps or debug symbols etc) but they cannot affect consensus.  They are purely informational.

**Comment by blockone-syncclient** [comment]
➤ Bart Wyatt commented:

I guess by forever, I mean as long as the table exists.  We may want to allow tables to be "garbage collected" if they are empty?  There are larger repercussions to something like that.

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

Could you pls add an ATC for it?

**Comment by heifner** [comment]
Resolved by #1244.

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

I am wondering how should I test this.

Can you pls add an ATC?

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

[~bart.wyatt] what is the status of the table interface?  Is the non-iterator interface going away?  If so, do we need to bother testing this?

**Comment by blockone-syncclient** [comment]
➤ Greg Lee commented:

From [~dan.larimer]:

There should be exactly one table per name regardless of type.  This needs to be enforced when creating a new table ID.

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

[~corey.lederer] [~greg.lee] [~kevin.heifner] This should be closed.  This task was started and then Dan added the table iterator interface.  I talked to [~anton.perkov] and the validation that could be enforced in the wasm code was much better than the limited validation that could be performed in a discrete c API call could perform.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

I will close if we agree that it is not an issue and we have a solution (as indicated by Anton's comments).

Everyone agree?

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

DAWN‌-367 removes this original change.  I think you should take silence as consent.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

[~bart.wyatt] [~brian.johnson] [~greg.lee] Is everyone ok with closing this ticket?

**Comment by blockone-syncclient** [comment]
➤ Greg Lee commented:

Get [~bart.wyatt]'s approval

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

Bart just responded in telegram that this should be closed-withdrawn.

**Comment by blockone-syncclient** [comment]
➤ Greg Lee commented:

Go ahead
