### ISSUE TITLE
./eosc get status needs to provide more detail - what test/live net am I connected to and what are my parms (servers and ports, etc.)

### ISSUE THREAD

**Issue by comtechnet** [EOSIO/eos#1073]
since ./eosd ties up a terminal window or runs in the background,

./eosc get status need to provide what "test net or live net" am I connected to at the time and what server and ports (resources) am I "using"

**Comment by jgiszczak** [comment]
`get info` now returns the chain_id.  `net peers` returns connected peers.  Operating system tools such as `netstat` can be used to discover simple listen port and connection information.
