### ISSUE TITLE
Unnable to get block data from snapshot

### ISSUE THREAD

**Issue by versionCollector** [EOSIO/eos#10746]
Hello, I'm running a  full node with `state_history_plugin`. I've synced it from snapshot that I got from https://snapshots-main.eossweden.org/ and now i can't get block data from snapshot with `/v1/cahin/get_block`.
Example:
`curl --location --request POST 'localhost:8888/v1/chain/get_block' --header 'Content-Type: application/json' --data-raw '{ "block_num_or_id": "180294714" }
{"code":400,"message":"Unknown Block","error":{"code":3100002,"name":"unknown_block_exception","what":"Unknown block","details":[{"message":"Could not find block: 180294714","file":"chain_plugin.cpp","line_number":2137,"method":"get_block"}]}}`
But if I'm requesting blocks that node synced I get a proper response. Can I somehow fix it?

**Comment by heifner** [comment]
The snapshot does not include the blocks, only the blockchain state. You would need to download a blocklog to be able to retrieve blocks.

**Comment by matthewdarwin** [comment]
There are some blocks to download here https://snapshots.eosamsterdam.net/

**Comment by versionCollector** [comment]
Thank you for fast response!
