### ISSUE TITLE
Nodeos folder non-existed after eosio installation with brew

### ISSUE THREAD

**Issue by sash20m** [EOSIO/eos#10805]
I am trying to install and run an EOS node on macos.

I installed eosio and eosio.cdt with brew.

I used 
```
brew tap eosio/eosio
brew install eosio
```
Everything went alright. But after installation the following folder was supposed to be created `/usr/local/eosio` which it did not.

Also, from what I know I should have a folder in my Application Support with the nodeos that was installed with eosio ( since  I want to edit the configuration file for nodeos ). However, I don't have the following folders.  
`/Users/[user]/Library/Library Support/eosio/nodeos`

In the same way I installed eosio.cdt
```
brew tap eosio/eosio.cdt
brew install eosio.cdt
```
And it has been installed successfully as well.

**Note that `nodeos --help` works, as well as `eosio-cpp --help` and `cleos --help`**

I am not sure if I am doing something wrong or the folders have been changed.

**Comment by sanaraufx** [comment]
Have you had previous installations of eosio on the system? If so, what versions?

**Comment by sash20m** [comment]
> Have you had previous installations of eosio on the system? If so, what versions?

Thanks for the response.

No. This is the first time installing eosio.

**Comment by sash20m** [comment]
I used `which nodeos` to find the path of the nodeos, which was in `/usr/local/bin` and then saw in the file details that the file was originated from `/usr/local/Cellar/eosio/2.1.0/bin` which is the location I was looking for. 
Also, the eosio folder has magically appeared in Library Support after I spun an eosio node with nodeos.
