### ISSUE TITLE
Typos in the wiki

### ISSUE THREAD

**Issue by EcutDavid** [EOSIO/eos#1086]
Hey, Find EOS recently and very excited about this project!

Just find some tiny issues in the wiki pages.

https://github.com/EOSIO/eos/wiki/Database%20Schema#3-transaction: 
"Account nmae of block producer" should be "Account name ..."

https://github.com/EOSIO/eos/wiki/Database: 
Nested Document is a data type, so I think it should keep the same, but now, there is one `Nested_Document`, one `Nested document` and one `Nested document`

The images on https://github.com/EOSIO/eos/wiki/Database%20API are broken on my side,
![image](https://user-images.githubusercontent.com/10692276/34912151-a0973cb2-f92d-11e7-9fbf-ffe13d64c1d4.png)

**Comment by EcutDavid** [comment]
On https://github.com/EOSIO/eos/wiki/Smart%20Contract#2-smart-contract-files
"To keep things simple we have created a tool called eoscpp which can be used to bootstrap a new contract. The eoscpp too will create the 3 smart contract files"
"The eoscpp too" seems need to be changed to "eoscpp tool"

https://github.com/EOSIO/eos/wiki/Smart%20Contract#23-wast
"Any program that wants to deploy to the EOS.IO blockchain must first compile into WASM format. " -> "wants to be deployed", "be compiled into"

https://github.com/EOSIO/eos/wiki/Smart%20Contract#3-checklist
"node_ip can be a private node's IP of you can connect to the public testnet using public nodes ip"
-> "private node's IP or you can"

**Comment by PaulCalabrese** [comment]
A lot of these tutorials has been rewritten. I did fix one of these problems that still existed.
