### ISSUE TITLE
QUESTION: Address-to-address message system

### ISSUE THREAD

**Issue by Dexaran** [EOSIO/eos#1088]
The ability to send human-readable text messages from one account owner to another without knowing their identities is very important for any blockchain-based system. For example if a user accidentally sent some funds to someone else's address but the user can not know who is the owner of this address. 

I have already worked on the address-to-address system on Ethereum earlier ([EIP802](https://github.com/ethereum/EIPs/issues/802), [announcement_38](https://github.com/EthereumCommonwealth/Roadmap/issues/38)).

It can be easily implemented using internal network facilities (smart-contracts) by analogy to naming system (ENS on Ethereum). It is obvious that the same service can be implemented in EOS as well and it is an essential part of the ecosystem. This is more a question of standardization: what contract will be considered "an official messaging core system".

The question is: are here any plans to establish a message system of EOS currently?

**Comment by brianjohnson5972** [comment]
There are no plans currently to establish an EOS message system as a system contract.
