### ISSUE TITLE
setcode contract issue

### ISSUE THREAD

**Issue by philsong** [EOSIO/eos#109]
We several guy meet the same issue in below, it seems scope is not right, how to resolve? or is it a bug?

➜  programs git:(master) vi data-dir/config.ini
➜  programs git:(master) ./eosc/eosc setcode inita ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi
10 assert_exception: Assert Exception
status_code == 200: Error
: 3030008 tx_missing_scope: missing required scope
Required scope currency not declared by transaction
    {"scope":"currency"}
    thread-1  message_handling_contexts.cpp:26 require_scope

    {}
    thread-1  wasm_interface.cpp:459 vm_onInit

    {}
    thread-1  wasm_interface.cpp:505 init

    {"context.msg":{"code":"eos","type":"setcode","data":"000000008040934b0000dc120061736d0100000001390a60037e7e7e017f60047e7e7f7f017f60017e0060057e7e7e7f7f017f60027f7f0060027f7f017f60027e7f0060017f0060000060027e7e0002760703656e7606617373657274000403656e76086c6f61645f693634000303656e760b726561644d657373616765000503656e760a72656d6f76655f693634000003656e760b7265717569726541757468000203656e760d726571756972654e6f74696365000203656e760973746f72655f6936340001030504060708090404017000000503010001077e05066d656d6f727902002a5f5a4e3863757272656e6379313273746f72654163636f756e744579524b4e535f374163636f756e74450007355f5a4e3863757272656e637932336170706c795f63757272656e63795f7472616e7366657245524b4e535f385472616e7366657245000804696e69740009056170706c79000a0abe0c043700024020012903084200510d0020004280808080a8d7bee3082001411010061a0f0b20004280808080a8d7bee308200129030010031a0bc50504017e027f047e017f4100410028020441206b2208360204200029030021052000290308100520051005200029030010042000290300210142002105423b2104411021034200210603400240024002400240024020054206560d0020032c00002202419f7f6a41ff017141194b0d01200241a0016a21020c020b420021072005420b580d020c030b200241ea016a41002002414f6a41ff01714105491b21020b2002ad42388642388721070b2007421f83200442ffffffff0f838621070b200341016a2103200542017c2105200720068421062004427b7c2204427a520d000b420021052008420037031820082006370310200142808080c887d7c8b21d4280808080a8d7bee308200841106a411010011a200041086a2903002101423b2104411021034200210603400240024002400240024020054206560d0020032c00002202419f7f6a41ff017141194b0d01200241a0016a21020c020b420021072005420b580d020c030b200241ea016a41002002414f6a41ff01714105491b21020b2002ad42388642388721070b2007421f83200442ffffffff0f838621070b200341016a2103200542017c21052007200684210

**Comment by skenan** [comment]
try ./eosc setcode currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi


Because in the small contracts, it's defined by currency, not inita.

**Comment by philsong** [comment]
![image](https://user-images.githubusercontent.com/1390304/28764428-c4b20eba-75f7-11e7-9ac5-4a1872de4092.png)

**Comment by philsong** [comment]
➜  programs git:(master) ./eosc/eosc create account inita currency EOS5MW14wMzpWhJ442i1fy2hiFAzTzMeNED7krepABcNKGVUs2XLU EOS7Buw6kLUy1fMz71gFbQ9mmv9EzjJ86DmkpLVmi9cjC5nj9j1YW
{
  "transaction_id": "1b9081cbc85b679983d8b0a0e51ef737b9b89400f8eb29caa5f6a0f14e1e78a6",
  "processed": {
    "refBlockNum": "8292",
    "refBlockPrefix": "3113964468",
    "expiration": "2017-07-31T06:13:49",
    "scope": [
      "eos",
      "inita"
    ],
    "signatures": [],
    "authorizations": [{
        "account": "inita",
        "permission": "active"
      }
    ],
    "messages": [{
        "code": "eos",
        "type": "newaccount",
        "data": "000000008040934b00000079b822651d0100000001023d550a1207c79aa6eb8bf48ae0c1fcb434d8212c7b58178c5d18840429caa4a70100000100000001032ef47d9508b1c9e7d8bb85b8d4fae9246ffee8c54cc563c39dfec1b0e270d9dd010000010000000001000000008040934b00000000149be8080100010000000000000008454f5300000000"
      }
    ],
    "output": [{
        "notify": [],
        "sync_transactions": [],
        "async_transactions": []
      }
    ]
  }
}
➜  programs git:(master) ./eosc/eosc setcode currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi
10 assert_exception: Assert Exception
status_code == 200: Error
: 3030003 tx_irrelevant_auth: irrelevant authority included
Transaction declared an authorization it did not need
    {}
    thread-1  chain_controller.cpp:676 process_transaction

**Comment by philsong** [comment]
@skenan

**Comment by clayop** [comment]
I have the same issue, which is highly suspiciously due to 67c9b8b.

**Comment by heifner** [comment]
set code of currency contract works. eosd_run_test.sh that is run with every build verifies set code of currency contract. Closing.
