### ISSUE TITLE
./eosc create account inita currency PUBLIC_KEY_1 PUBLIC_KEY_2 execution error

### ISSUE THREAD

**Issue by Dgtlinux** [EOSIO/eos#1090]
Running into this issue at the below step in the setup:
OSX Darwin.

./eosc create account inita currency PUBLIC_KEY_1 PUBLIC_KEY_2

Error:

2571028ms            main.cpp:1165                 main                 ] Failed with error: Assert Exception (10)
base58str.substr(0, prefix_len) == prefix:

**Comment by Dgtlinux** [comment]
anybody seen this before?

**Comment by cenkai88** [comment]
Did you use the PRIVATE KEY as PUBLIC KEY in the command? PUBLIC KEY should start with "EOS"

**Comment by Dgtlinux** [comment]
I did't use PRIVATE KEY as PUBLIC KEY,I use the PUBLIC KEY like this:
./eosc create account inita currency PUBLIC_KEY_1 PUBLIC_KEY_2

are you chinses?

**Comment by heifner** [comment]
Replace `PUBLIC_KEY_1` and `PUBLIC_KEY_2` with your public keys from `./eosc create key`.
Please use telegram `EOS Developers` for support.

**Comment by Dgtlinux** [comment]
Thank you,when I replace PUBLIC_KEY_1 and PUBLIC_KEY_2,I solved this problem.
