### ISSUE TITLE
call action error by sdk 

### ISSUE THREAD

**Issue by yekai1003** [EOSIO/eos#10912]
The following error occurred when I called actions using the SDK
 
> Internal` Service Error: eosio_assert_message assertion failure: assertion failure with message: datastream attempted to read past the end: pending console output:

But when I use cleos ,it work well.
Where should I start to solve the problem?

**Comment by praphael** [comment]
Are you referring to EOSJS SDK?  If so this would be the proper board https://github.com/EOSIO/eosjs/issues  
What actions are you calling?

**Comment by yekai1003** [comment]
> Are you referring to EOSJS SDK? If so this would be the proper board https://github.com/EOSIO/eosjs/issues What actions are you calling?

I'm use go sdk, the repo is github.com/eoscanada/eos-go, I tryed call add action, but get error.

**Comment by praphael** [comment]
> > Are you referring to EOSJS SDK? If so this would be the proper board https://github.com/EOSIO/eosjs/issues What actions are you calling?
> 
> I'm use go sdk, the repo is github.com/eoscanada/eos-go, I tryed call add action, but get error.

You will have to ask on that board.  Block.One/Bullish did not author and does not support eos-go.
