### ISSUE TITLE
Documentation on building eos from source via CMake ?

### ISSUE THREAD

**Issue by nyue** [EOSIO/eos#10916]
Hi,

  I have browse through the various markdown files but did not find instruction about building eos from source.

  Are they documented elsewhere ?

Cheers

**Comment by praphael** [comment]
If you are running a supported OS you can use our build scripts.  
https://github.com/EOSIO/eos/blob/master/scripts/eosio_build.sh

We also have Dockerfiles for the same sets of OS's https://github.com/EOSIO/eos/tree/master/.cicd/platforms

OS support depends on which branch you are using, but only Linux and Mac builds are supported
