### ISSUE TITLE
Trace_api 404 when querying blocks earlier than a certain block height 

### ISSUE THREAD

**Issue by camharris** [EOSIO/eos#10937]
When attempting to query blocks earlier than what seems like 216000000 the trace api returns a 404 error

```
curl  http://localhost/v1/trace_api/get_block --data '{"block_num":"100"}'
{"code":404,"message":"Block trace missing","error":{"code":0,"name":"","what":"","details":[]}}%
```
This worked previously, has something changed? 

Is this expected? I've noticed these blocks are able to be queried with the chain api but not the trace api. Running server version `v2.0.12-32a47e396a13b948263b1dc9762a6e2292a2c2ef`

**Comment by praphael** [comment]
Are you doing a replay on blocks before a certain time?  Trace API will not generate traces for transactions in blocks prior to it being activated, unless you do a replay.

**Comment by camharris** [comment]
Thanks for your response. I was not performing a replay on the blocks in question, as I was not originally aware of this.
