### ISSUE TITLE
[question] A unique ID known to both the message submitter and the smart contract apply()

### ISSUE THREAD

**Issue by bosschaert** [EOSIO/eos#1098]
Hi, this might be a bit of a n00b question, but I couldn't find this by looking at the documentation yet...

When I send a message to my eos smart contract I get a `transaction_id` back in the returned JSON. I assume that this ID is unique to my message. When my smart contract gets the `apply()` method called for my message I would like to obtain this unique transaction ID, so that I can put this as a key in the database for the result of the smart contract work. Is it possible to find out this transaction ID in the apply() method? Or of not, is there another way to automatically generate an ID that is given to the client when the message is sent and then obtained in the apply()?

Many thanks

**Comment by andriantolie** [comment]
transaction_id is actually just the sha256 digest of the transaction. If you want to get the transaction_id, you can first read the transaction and then just hash it, i.e.
```
char buffer[transaction_size()];
read_transaction(buffer, transaction_size());
checksum256 txid;
sha256(buffer, transaction_size(), &txid); 
printhex(&txid, sizeof(txid)/sizeof(uint8_t));
```
