### ISSUE TITLE
DAWN-480 ⁃ Extend ABI to support "singleton" table concept introduced in #1097

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1099]
# Singleton Table

It is efficient for the chain and more usable for the contract developers to have a table type that can store a lot of data types for which there will only ever be 1 entry.  However, right now our ABI expects the type of an entry in any given table to match all other entries in that table.  In this case, each entry would potentially have a different type.

## Suggested Solution

- extend the types available to the ABI definition to include a per-row/entry designator (maybe "varied")
- add an optional field on `table_def` that can contains a mapping of keys to types. 
  - this must at least allow for explicit key values
  - this mapping may allow for ranges/patterns etc

- we may want to include a convenient coercion from strings to i64 that operates like our `N()` utility macro/method

## Example

```
"tables": [{
   "name": "singleton",
   "type": "varied",
   "index_type": "i64",
   "key_names" : ["key"],
   "key_types" : ["name"],
   "varied_types": [
      { "key": "info",  "type": "info_type" },
      { "key": "stats",  "type": "stats_type" },
   ]
 }]
```

**Comment by brianjohnson5972** [comment]
The code has moved significantly from where it was at this point and if the community decides it wants a feature like this, it will likely be designed differently.  Closing.
