### ISSUE TITLE
DAWN-502 ⁃ Can't use any type other then uint64_t in eosio::token<uint64_t,N(currency)>

### ISSUE THREAD

**Issue by venediktov** [EOSIO/eos#1103]
Should it be  allowed using uint32_t and uint128_t and other unsigned values to represent token quantity ? 
Currently only uint64_t compiles .

If that's the case I can make a pull request to address the issue with following features

- Add type traits to smart contract library as a separate file contracts/eoslib/type_traits.hpp ( currently some type traits exist in contracts/eoslib/type.h)
- add static assertion in the body of template class 
- add SFINAE exclusion of constructor if type is not unsigned integral   
- don't allow implicit conversions of integral value in the ctor of eosio::token , same type but smaller length will be allowed though 
- change hardcoded asserts in contracts library 

```
template<typename NumberType, uint64_t currency = N(eos)>
struct token {
static_assert(eosio::is_unsigned<NumberType>::value, "NumberType can only be unsigned number");
.....
.....  
token() : quantity{} {}

template<typename T, typename = typename eosio::enable_if<eosio::is_unsigned<T>::value && !(sizeof(T)>sizeof(NumberType))>::type>
 explicit token( T v ):quantity(v){};


 //NumberType quantity = 0; //use default value initialization  in ctor 
NumberType quantity;
.....
```

A much stricter would be even better  but I think above proposal would suffice ?

```
template<typename T, typename = typename eosio::enable_if<eosio::is_unsigned<T>::value && eosio::is_same<T,NumberType>::type>
 explicit token( T v ):quantity(v){};
```

the proposed  change will require fixing  hardcoded asserts in multiple places as when we change token NumberType compiler will have  to automatically calculate size, see below  
```
-   static_assert( sizeof(bid) == 32+12, "unexpected padding" );
+   static_assert( sizeof(bid) == sizeof(order_id)+sizeof(price)+sizeof(eosio::tokens)+sizeof(time), "unexpected padding" );
```
Let me know what you think.

**Comment by wanderingbort** [comment]
related to #1071 

We should make sure we adopt the compile-time protections added here and, if not already present, some of the std c++ traits/etc that are implemented to facilitate better compile time type enforcement.
