### ISSUE TITLE
DAWN-475 ⁃ replaying blocks may randomly fail

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1104]
This is a corollary to the Most Hated Block fix, in that replaying previously logged blocks invokes the same process message functionality as what happens during a resync. I found a case where a user was trying to start his eosd with --replay and it would fail the process message duration validation on random blocks. It was not reproducible in that subsequent runs on the same host might not fail, or may fail on a block that passed earlier. While the nature of this issue suggests a larger runtime environmental issue, clearly a block that previously passed should not fail during a replay.

Also, it seems I mismatched 'dur" and "duration" in the enhanced log message I added when a process message validation legitimately fails. I suppose we need a too-long running contract as part of the test suite.

The fix for this issue is straightforward - add the new "irreversible" flag to the skip_flags set during a replay.

ATC for this issue is a little tough to characterize since the issue at hand is random. a too-long running contract isn't helpful for testing, since we need  a contract that was successful once, otherwise it won't be logged and thus not replayed.  Perhaps w need a contract that nominally runs for just under the time limit, then replay that on a heavily loaded host.

As for story points, the fix is easy, building a repeatable test case is going to be a bit harder.

**Comment by andriantolie** [comment]
With the refactored chain_controller, this issue looks to be obsolete
