### ISSUE TITLE
DAWN-476 ⁃ recovering state after a long pause.

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1105]
On Jan. 11, node 19, 10.160.12.240, fell out of sync. Turns out occasionally no p2p messages are processed for many seconds.  In some cases the delay was accompanied by a missed block. In most cases the missed block is recovered. In this case it looks like the node synced but was not able inform its peers that it was caught up. This then prevented the peers from sending new blocks to node 19.

The determination of duplicates is moved to issue DAWN-515

two issues to address are: 
1. Determine what happens to cause a long delay during message retrieval - as though no I/O callbacks are triggered. 
2. Determine why node 19 failed to update its peers upon completing the synchronization task.

While this happened on testnet 1, I'd like to use testnet 2 to investigate the issue

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

Testnets 1 and 2 are both running the DAWN-14-02-2018 tag of dawn-2.x. I believe this issue is no longer valid since the new tag substantially modifies how the p2p network synchronizes. Therefore I am closing this issue as obsolete.

**Comment by andriantolie** [comment]
As mentioned in the prev comment, this issue is obsolete. I'm closing this issue
