### ISSUE TITLE
No Signature under provided delay, permission and keys??

### ISSUE THREAD

**Issue by Jacquelinevv0693** [EOSIO/eos#11061]
Error
transaction declares authority '{"actor":"gemin....","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys ["EOS6wK74NhZ2CwLheYs.....","EOS7reqTZy8TKzK1jPEiyD......"], and a delay max limit of 3888000000 ms....

Please assist in resolving this. I have no idea what i have done

**Comment by praphael** [comment]
This question is probably best suited for the stack exchange https://eosio.stackexchange.com/

But to briefly explain, you don't have the private keys for the account  `gemin` in your wallet.  If you are using `cleos` with `keosd`, you can import keys with the command `cleos wallet import`

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)
