### ISSUE TITLE
DAWN-482 ⁃ Update our use of double types

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1107]
Matias brought up our use of double types:

btw, shouldn't we use 

boost::multiprecision::cpp_bin_float_50 instead of 
boost::multiprecision::cpp_dec_float_50 for the wasm_double ?

**Comment by elmato** [comment]
Ref #207

**Comment by elmato** [comment]
Ref #207

https://github.com/EOSIO/eos/issues/207

**Comment by blockone-syncclient** [comment]
➤ Bart Wyatt commented:

deprecated by DAWN-622

**Comment by taokayan** [comment]
test cases with ops including add/sub/mult/div/min/max/cmp/trunc/convert passed:

    Test case "wasm_tests/f32_tests" has passed with:
      4 assertions out of 4 passed

    Test case "wasm_tests/f64_tests" has passed with:
      4 assertions out of 4 passed

    Test case "wasm_tests/f32_f64_conversion_tests" has passed with:
      1 assertion out of 1 passed

    Test case "wasm_tests/f32_f64_overflow_tests" has passed with:
      48 assertions out of 48 passed
