### ISSUE TITLE
my local node can't produce block

### ISSUE THREAD

**Issue by darksford123x** [EOSIO/eos#11092]
i run this :
nodeos -e -p eosio \
--plugin eosio::producer_plugin \
--plugin eosio::producer_api_plugin \
--plugin eosio::chain_api_plugin \
--plugin eosio::http_plugin \
--plugin eosio::history_plugin \
--plugin eosio::history_api_plugin \
 --snapshot ~/waxdata/snapshots/snapshot.bin \
--data-dir ~/waxdata \
--chain-state-db-size-mb=1048576 \
--reversible-blocks-db-size-mb=1048576 

node will start and hanging on :
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:630          plugin_initialize    ] initializing chain plugin
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:461          operator()           ] Support for builtin protocol feature 'PREACTIVATE_FEATURE' (with digest of '0ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd') is enabled without activation restrictions
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'ONLY_LINK_TO_EXISTING_PERMISSION' (with digest of '1a99a59d87e06e09ec5b028a9cbb7749b4a5ad8819004365d02dc4379a8b7241') is enabled with preactivation required
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'FORWARD_SETCODE' (with digest of '2652f5f96006294109b3dd0bbde63693f55324af452b799ee137a81a905eed25') is enabled with preactivation required
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'WTMSIG_BLOCK_SIGNATURES' (with digest of '299dcb6af692324b899b39f16d5a530a33062804e41f09dc97e9f156b4476707') is enabled with preactivation required
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'REPLACE_DEFERRED' (with digest of 'ef43112c6543b88db2283a2e077278c315ae2c84719a8b25f25cc88565fbea99') is enabled with preactivation required
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'NO_DUPLICATE_DEFERRED_ID' (with digest of '4a90c00d55454dc5b059055ca213579c6ea856967712a56017487886a4d4cc0f') is enabled with preactivation required
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'RAM_RESTRICTIONS' (with digest of '4e7bf348da00a945489b2a681749eb56f5de00b900014e137ddae39f48f69d67') is enabled with preactivation required
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'WEBAUTHN_KEY' (with digest of '4fca8bd82bbd181e714e283f83e1b45d95ca5af40fb89ad3977b653c448f78c2') is enabled with preactivation required
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'DISALLOW_EMPTY_PRODUCER_SCHEDULE' (with digest of '68dcaa34c0517d19666e6b33add67351d8c5f69e999ca1e37931bc410a297428') is enabled with preactivation required
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'ONLY_BILL_FIRST_AUTHORIZER' (with digest of '8ba52fe7a3956c5cd3a656a3174b931d3bb2abb45578befc59f283ecd816a405') is enabled with preactivation required
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'RESTRICT_ACTION_TO_SELF' (with digest of 'ad9e3d8f650687709fd68f4b90b41f7d825a365b02c23a636cef88ac2ac00c43') is enabled with preactivation required
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'FIX_LINKAUTH_RESTRICTION' (with digest of 'e0fb64b1085cc5538970158d05a009c24e276fb94e1a0bf6a528b48fbc4ff526') is enabled with preactivation required
info  2022-05-22T05:05:51.696 nodeos    chain_plugin.cpp:448          operator()           ] Support for builtin protocol feature 'GET_SENDER' (with digest of 'f0af56d2c5a48d60a4a5b5c903edfb7db3a736a94ed589d0b797df33ff9d3e1d') is enabled with preactivation required
info  2022-05-22T05:05:52.106 nodeos    platform_timer_accurac:62     compute_and_print_ti ] Checktime timer accuracy: min:0us max:4us mean:1us stddev:0us
info  2022-05-22T05:05:52.106 nodeos    producer_plugin.cpp:937       plugin_initialize    ] Subjective CPU billing disabled
info  2022-05-22T05:05:52.106 nodeos    http_plugin.cpp:742           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
info  2022-05-22T05:05:52.106 nodeos    main.cpp:106                  main                 ] nodeos version v2.0.13 v2.0.13-c75fa31d119d9e026115f96c5e30a74475786b7c
info  2022-05-22T05:05:52.106 nodeos    main.cpp:107                  main                 ] nodeos using configuration file /home/wax-server/.local/share/eosio/nodeos/config/config.ini
info  2022-05-22T05:05:52.106 nodeos    main.cpp:108                  main                 ] nodeos data directory is /home/wax-server/waxdata
info  2022-05-22T05:05:52.106 nodeos    controller.cpp:541            startup              ] Starting initialization from snapshot, this may take a significant amount of time
info  2022-05-22T05:16:31.640 nodeos    controller.cpp:555            startup              ] database initialized with hash: a9fa5a8cfa18a2373d98aeec4d4c8ac029e766c14b9298c6635838c720e24835
info  2022-05-22T05:16:31.640 nodeos    controller.cpp:563            startup              ] Finished initialization from snapshot
info  2022-05-22T05:16:31.640 nodeos    chain_plugin.cpp:1171         plugin_startup       ] starting chain in read/write mode
info  2022-05-22T05:16:31.640 nodeos    chain_plugin.cpp:1179         plugin_startup       ] Blockchain started; head block is #183006892
info  2022-05-22T05:16:31.640 nodeos    producer_plugin.cpp:1017      plugin_startup       ] producer plugin:  plugin_startup() begin
info  2022-05-22T05:16:31.640 nodeos    producer_plugin.cpp:1042      plugin_startup       ] Launching block production for 1 producers at 2022-05-22T05:16:31.640.
info  2022-05-22T05:16:31.640 nodeos    producer_plugin.cpp:1053      plugin_startup       ] producer plugin:  plugin_startup() end
info  2022-05-22T05:16:31.640 nodeos    producer_api_plugin.cp:89     plugin_startup       ] starting producer_api_plugin
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/add_greylist_accounts
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/create_snapshot
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/get_account_ram_corrections
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/get_greylist
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/get_integrity_hash
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/get_runtime_options
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/get_scheduled_protocol_feature_activations
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/get_supported_protocol_features
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/get_whitelist_blacklist
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/pause
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/paused
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/remove_greylist_accounts
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/resume
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/schedule_protocol_feature_activations
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/set_whitelist_blacklist
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/producer/update_runtime_options
info  2022-05-22T05:16:31.640 nodeos    chain_api_plugin.cpp:105      plugin_startup       ] starting chain_api_plugin
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_info
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/abi_bin_to_json
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/abi_json_to_bin
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_abi
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_account
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_activated_protocol_features
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_block
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_block_header_state
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_code
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_code_hash
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_currency_balance
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_currency_stats
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_producer_schedule
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_producers
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_raw_abi
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_raw_code_and_abi
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_required_keys
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_scheduled_transactions
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_table_by_scope
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_table_rows
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/get_transaction_id
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/push_block
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/push_transaction
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/push_transactions
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/chain/send_transaction
info  2022-05-22T05:16:31.640 nodeos    history_api_plugin.cpp:34     plugin_startup       ] starting history_api_plugin
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/history/get_actions
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/history/get_controlled_accounts
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/history/get_key_accounts
info  2022-05-22T05:16:31.640 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/history/get_transaction
info  2022-05-22T05:16:31.640 nodeos    net_plugin.cpp:3489           plugin_startup       ] my node_id is 07ecb20e1fcb5ebfe137c15f695a48b32631f2016e9229d14bff4772b6dce90c
info  2022-05-22T05:16:31.640 nodeos    net_plugin.cpp:3545           plugin_startup       ] starting listener, max clients is 25
info  2022-05-22T05:16:31.641 nodeos    http_plugin.cpp:821           operator()           ] start listening for http requests
info  2022-05-22T05:16:31.641 nodeos    http_plugin.cpp:927           add_handler          ] add api url: /v1/node/get_supported_apis

^Cinfo  2022-05-22T05:26:50.061 nodeos    net_plugin.cpp:3591           plugin_shutdown      ] shutdown..
info  2022-05-22T05:26:50.061 nodeos    net_plugin.cpp:3608           plugin_shutdown      ] close 0 connections
info  2022-05-22T05:26:50.062 nodeos    net_plugin.cpp:3628           plugin_shutdown      ] exit shutdown
info  2022-05-22T05:26:50.792 nodeos    main.cpp:149                  main                 ] nodeos successfully exiting

how can i do to make my local node produce block?

**Comment by kingsnow-2008** [comment]
You can try to execute the program in the background。eg：
nodeos -e -p eosio
--plugin eosio::producer_plugin
--plugin eosio::producer_api_plugin
--plugin eosio::chain_api_plugin
--plugin eosio::http_plugin
--plugin eosio::history_plugin
--plugin eosio::history_api_plugin
--snapshot ~/waxdata/snapshots/snapshot.bin
--data-dir ~/waxdata
--chain-state-db-size-mb=1048576
--reversible-blocks-db-size-mb=1048576 >> "~/waxdata/nodeos.log" 2>&1 &。
You can view  logs in file ~/waxdata/nodeos.log
Hope this is useful to you。

**Comment by kingsnow-2008** [comment]
邮件已收到
