### ISSUE TITLE
Growing Team/Contact ?

### ISSUE THREAD

**Issue by KenoLeon** [EOSIO/eos#1120]
From Dan's steemit  update :

> This week we were pleased to add 8 new people to our team. We are constantly looking for more. If you are a talented developer or designer please contact us.

I haven't had any luck contacting you, I've tried a steemit comment, emailing eos@block.one and the telegram developers room.

What's the correct way, I am interested in the project and have been doing design, development and smart contract work (on Ethereum).

Thanks !

**Comment by heifner** [comment]
https://block.one/contact/
