### ISSUE TITLE
could not grow database file to requested size

### ISSUE THREAD

**Issue by standup75** [EOSIO/eos#1123]
Hi,

Trying to install the environment, and I get the following error:

```
function chainbase::database::database(const bfs::path &, chainbase::database::open_flags, uint64_t)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: could not grow database file to requested size.
```

I am running el capitan and the doc says Sierra, but doesn't explicitly exclude el capitan, so I thought I'd give it a spin. Is it the reason?

**Comment by standup75** [comment]
I confirm, finally migrated to Sierra, reinstalled eos and it works now

**Comment by firesWu** [comment]
I meet this problem because user don't have data directory permission.
