### ISSUE TITLE
Got 500 internal service error while walking through the intro

### ISSUE THREAD

**Issue by ethanyanjiali** [EOSIO/eos#1125]
So i got a 500 error when I come to this part:

> Run the create command where inita is the account authorizing the creation of the currency account and PUBLIC_KEY_1 and PUBLIC_KEY_2 are the values generated by the create key command

```
2593992ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"13 NSt3__18ios_base7failureE: ios_base::clear: unspecified iostream_category error\nrethrow ios_base::clear: unspecified iostream_category error: \n    {\"what\":\"ios_base::clear: unspecified iostream_category error\"}\n      block_log.cpp:50 check_index_read\nrethrow\n    {}\n      block_log.cpp:204 read_block_by_num"}
```

I've successfully built and ran the eosd btw, my machine is mac os

**Comment by heifner** [comment]
Can you restart your eosd with the resync option:  `./eosd --resync`

**Comment by ethanyanjiali** [comment]
still having same error. what does `unspecified iostream_category error` mean?

**Comment by ethanyanjiali** [comment]
it behaves like i've never started eosd. I also saw
`97295ms            http_plugin.cpp:219           plugin_startup       ] http: Underlying Transport Error`
and then
```
167001ms            chain_controller.cpp:1046     validate_block_heade ] head_block_time 2018-01-18T17:01:53, next_block 2018-01-18T17:02:47, block_interval 1
167001ms            chain_controller.cpp:1048     validate_block_heade ] Did not produce block within block_interval 1, took 54000ms)
```
when I run eosd
but everything else looks good, i can see new blocks generated from my local node

**Comment by heifner** [comment]
Please create a new issue for checking if port is occupied.
