### ISSUE TITLE
Is there a bug in merkle function in block.cpp?

### ISSUE THREAD

**Issue by daneric** [EOSIO/eos#1126]
```
digest_type merkle(vector<digest_type> ids) {
      while (ids.size() > 1) {
         if (ids.size() % 2)
            ids.push_back(ids.back());
         for (int i = 0; i < ids.size() / 2; ++i)
            ids[i/2] = digest_type::hash(std::make_pair(ids[i], ids[i+1]));
         ids.resize(ids.size() / 2);
      }

      return ids.front();
   }

```
I think the variable "i" in the for loop should be iterate by "i += 2" instead of "++i".
Am i right?
Best wishes for EOS great success!

**Comment by wanderingbort** [comment]
@daneric  you are right!  We actually found this bug a little bit ago when writing test cases for inter-blockchain communication.  Most of our development is focussed on Dawn 3.0 which lives (for now) in the eos-noon branch.  

If you'll notice [the new code](https://github.com/EOSIO/eos/blob/eos-noon/libraries/chain/merkle.cpp) has already adopted a fix for the bug you mentioned (allbeit in a different manner).  I would invite you to review that code and see if we have remaining issues.

Also note that our merkles are no longer "pure" in that we have the idea of canonical digests which self-describe whether they are the "left" or "right" concatenated.  [This](https://steemit.com/eos/@dan/inter-blockchain-communication-via-merkle-proofs-with-eos-io) has more information.

**Comment by daneric** [comment]
Thanks for reply and best wishes!

**Comment by sugalivijaychari** [comment]
what does ids.front() mean;
what exactly this function merkle is returning?

**Comment by heifner** [comment]
http://www.cplusplus.com/reference/vector/vector/front/
