### ISSUE TITLE
error launching local node connected to the public testnet

### ISSUE THREAD

**Issue by Dgtlinux** [EOSIO/eos#1127]
after "./start_npnode.sh" and "tail -F testnet_np/stderr.txt"
the output like this:

1153318ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/lock_all
1153318ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/open
1153318ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/set_timeout
1153318ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/sign_transaction
1153318ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/unlock
1153318ms            net_plugin.cpp:2515           plugin_startup       ] starting listener, max clients is 25
1153329ms            net_plugin.cpp:567            connection           ] created connection to p2p-testnet1.eos.io:9876
1153329ms            net_plugin.cpp:1284           connect              ] host: p2p-testnet1.eos.io port: 9876 
1154131ms            net_plugin.cpp:1628           handle_message       ] received a go away message, reason = duplicate
1154131ms            net_plugin.cpp:1417           operator()           ] Error reading message from p2p-testnet1.eos.io:9876: Bad file descriptor

what's wrong?

**Comment by gzhang** [comment]
change this line in testnet_np/config.ini file
p2p-server-address = <your real ip address>:9877

**Comment by Dgtlinux** [comment]
hi gzhang,i have changed like what you say,but it still failed.
when i "tail -F... " today,it worked successfully,
so i think it is related to the stat of network.
