### ISSUE TITLE
DAWN-465 ⁃ Provide to/from variant for transaction types

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1129]
* Provide to/from variant on chain controller for transaction types.
* Verify each transaction type can be converted to/from via templated method on chain controller via unittests.
* Update abi_serializer for missing transaction types
* Update abi_serializer for any other missing native types

ATC:

* chain_test should continue to run without error.

**Comment by heifner** [comment]
Yes, this has been completed.
