### ISSUE TITLE
DAWN-322 ⁃ Add wallet delete methods

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1134]
Currently, the only way to delete a wallet is to remove the wallet file. Also, there is no way to remove a single key from a wallet.

Add:

* ./eosc wallet delete -n name
  * Remove the wallet from the file system (should we prompt for confirmation?)
* ./eosc wallet remove key
  * Given a public or private key remove it from the wallet

**Comment by andriantolie** [comment]
Deleting wallet can be done by removing the relevant file, while removing key feature have been added to cleos. I'm closing this issue
