### ISSUE TITLE
DAWN-509 ⁃ Docker Images In Dockerhub

### ISSUE THREAD

**Issue by JamesDrummond** [EOSIO/eos#1135]
Can you please provide both builder [https://github.com/EOSIO/eos/blob/master/Docker/Dockerfile#L1-L79](https://github.com/EOSIO/eos/blob/master/Docker/Dockerfile#L1-L79) and final docker image [https://github.com/EOSIO/eos/blob/master/Docker/Dockerfile#L83-L97](https://github.com/EOSIO/eos/blob/master/Docker/Dockerfile#L83-L97)  on dockerhub? The builder would be nice to compile contracts with. I have generated both of these images manually but it would be nice for developers not to have to compile from source every update which takes a long time.

**Comment by JamesDrummond** [comment]
@heifner Consider creating a separate Dockerfile for https://github.com/EOSIO/eos/blob/master/Docker/Dockerfile#L1-L71 . Image name maybe `eosio/eos_base` . Then remove those lines 1-71 and add `FROM eosio/eos_base as builder` to the top of https://github.com/EOSIO/eos/blob/master/Docker/Dockerfile. This will save substantial time on your end and for others that may need to compile eos but not the dependencies.

**Comment by blockone-syncclient** [comment]
➤ Greg Lee commented:

Now that we have DockerHub access we need to get the proper files loaded there.  [~eric.iles] take liberty to do what you think is the right thing as far as what files need to be loaded into DH.

**Comment by ericiles** [comment]
This issue has been resolved by PR #1698
