### ISSUE TITLE
Docker build failing to sync with Testnet

### ISSUE THREAD

**Issue by RobPokorny** [EOSIO/eos#1141]
The containerised eosd repeatedly fails to sync with the Testnet when supplied with config.ini and genesis.json files from testnet_np build/scripts directory. Sync process begins, but fails as follows:

chain_controller.cpp:1003 apply_transaction
    {"next_block.block_num()":10599}
      chain_controller.cpp:650 _apply_block
3345495ms            net_plugin.cpp:1968           handle_message       ] accept_block threw a non-assert exception allotted processing time was exceeded (3030010)
 from 10.160.12.212:9876
3345495ms            net_plugin.cpp:1977           handle_message       ] block 10600, 0000296849ee9b4449f4c6022826e9cbf658bbe711569ff1848e1e76023d8fed not accepted from 10.160.12.212:9876
3345496ms            net_plugin.cpp:954            operator()           ] sent a go away message, closing connection to 10.160.12.212:9876
3345496ms            net_plugin.cpp:1417           operator()           ] Error reading message from p2p-testnet1.eos.io:9876: Operation canceled

Is there a fix / workaround? Non-containerised version syncs fine (once p2p-server-address is set).

**Comment by ericiles** [comment]
There have been significant changes made to all of our Docker related files. Due to the age of this issue, I am going to go ahead and close it out. Feel free to re-open if the issue persists.
