### ISSUE TITLE
Unable to start Docker container

### ISSUE THREAD

**Issue by snowsky** [EOSIO/eos#1143]
Got the below message when docker run:

```
Docker(master*)$ docker run --name eosd -p 8888:8888 -p 9876:9876 -t eosio/eos start_eosd.sh
/opt/eos/bin/start_eosd.sh: 22: exec: /opt/eos/bin/eosd: not found```

**Comment by GabrielNicolasAvellaneda** [comment]
@snowsky, please take a look if this solves your problem, it solved mine:
https://github.com/EOSIO/eos/pull/1184

**Comment by snowsky** [comment]
@GabrielNicolasAvellaneda It works for me. Thanks a lot.
