### ISSUE TITLE
Graphical EOS Wallet

### ISSUE THREAD

**Issue by asiniscalchi** [EOSIO/eos#1149]
I'd like to create multiplatform EOS Wallet (kind of Ethereum Mist) using Qt/QML/C++.
Do I need only the features of eosc executable ?
In that case what do you think if I extract a lib from eosc (with unit tests) and make eosc the command line frontend?

**Comment by brianjohnson5972** [comment]
Since the desire is for existing wallets to support EOS and since the EOS wallet is really just a tool to facilitate use until that happens, I don't think this will be pursued.

**Comment by brianjohnson5972** [comment]
Since the end goal is to have existing crypto wallets add support for EOS and not for EOS to maintain its own wallet (keosd is just there in the interim), it is not desired to pursue this.
