### ISSUE TITLE
DAWN-517 ⁃ ensure that eosiolib headers can be included in multiple compilation units

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1153]
contracts/eosiolib/memory.hpp currently can not be included in multiple compilation units in the same wasm, since each compilation unit will have its own eosio::memory_heap.  The current way of avoiding this internally was to control our implementation of the toolchain and forced only one compilation unit per wast, but we cannot prevent users from providing wast created by another toolchain.

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

One option is to drop memory.hpp and provide malloc, realloc, and free in the intrinsics in wasm_interface and drop sbrk (which we really don't want contract writers calling)

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

[~corey.lederer] is there a ticket to rename eoslib to eosiolib?

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

[~brian.johnson] What part of eoslib is not named eosiolib?

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

All of it isn't named eosiolib: https://github.com/EOSIO/eos/tree/eos-noon/contracts/eoslib

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

I looked at that at least 3 times and saw `eosiolib`.

**Comment by andriantolie** [comment]
I noticed this issue has been done by moving the implementation to eosiolib.cpp. I'm closing this issue
