### ISSUE TITLE
Allow parameters in init() of smart contracts

### ISSUE THREAD

**Issue by kesar** [EOSIO/eos#1159]
It would be very handy to let us pass parameters to the init() of smart contracts.

The idea would be to set those parameters using the command:

eosc set contract hello hello.wast hello.abi {params}

**Comment by wanderingbort** [comment]
We have an internal issue (which may need to be made external) to remove
`init` entirely in favor of contract define actions.

This gives us a single entry point at all times and plenty of flexibility.

**Comment by kesar** [comment]
Good point, another idea could be to use current_message as it is for the apply()

**Comment by heifner** [comment]
init() was removed.
