### ISSUE TITLE
DAWN-518 ⁃ Define Builtin Symbol type for Currencies

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1165]
eosio::asset is a struct that has to fields (amount, and symbol).  Symbol is a 64bit int that uses the first byte to indicate how many digits after the '.' should be used, the last 7 bytes are used as a null-terminated string.

Currently there is no way to use a symbol separate from an amount; however, in our abi_serializer it would be handy to indicate that a field represents a symbol.

This task is to separate out the symbol type and give it its own unique string representation of 
"SYMBOL,PRECISION" via overloading to/from variant.  

To be clear: asset should still convert to/from string like it does today.  Symbols will just be given their own representation.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

[~khaled.alhassanieh] is this PR#1201?
