### ISSUE TITLE
How many larimers an EOS equals？

### ISSUE THREAD

**Issue by wangweiX** [EOSIO/eos#1176]
I found something wrong with your eos glossary. How many larimers an EOS equals?
![image](https://user-images.githubusercontent.com/7995377/35251098-98dc23f0-0014-11e8-914c-f382f51ddef7.png)

**Comment by qiqipipioioi** [comment]
1/10000 or 0.001

**Comment by wangweiX** [comment]
The latest official wiki document has been corrected, 
1/10000 of an EOS (token) 0.0001 EOS.
