### ISSUE TITLE
eosd Failed with iostream error 

### ISSUE THREAD

**Issue by LonRock** [EOSIO/eos#1177]
Hello everyone, I encounter an eosd iostream error as below:
root@vico-H61M-S2P-B3:/usr/eos/build/programs/eosd# eosd
2356013ms            chain_plugin.cpp:126          plugin_initialize    ] initializing chain plugin
2356013ms            wasm_interface.cpp:757        get                  ] Runtime::init
2356014ms            producer_plugin.cpp:170       plugin_initialize    ] Public Key: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
2356014ms            wallet_plugin.cpp:34          plugin_initialize    ] initializing wallet plugin
2356014ms            http_plugin.cpp:138           plugin_initialize    ] host: 127.0.0.1 port: 8888 
2356014ms            http_plugin.cpp:141           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
2356014ms            net_plugin.cpp:2379           plugin_initialize    ] Initialize net plugin
2356014ms            net_plugin.cpp:2399           plugin_initialize    ] Setting net_plugin logging level to info
2356014ms            net_plugin.cpp:2424           plugin_initialize    ] host: 0.0.0.0 port: 9876 
2356015ms            net_plugin.cpp:2503           plugin_initialize    ] my node_id is fcacea1ded816a4798c84bb64320279d674a6695e27002e7d25113d40b0553ad
2356015ms            main.cpp:59                   main                 ] eosd version 2cc40a4e
2356016ms            block_log.cpp:92              open                 ] Opening block log at /usr/eos/build/programs/eosd/data-dir/blocks/blocks.log
2356016ms            block_log.cpp:120             open                 ] Log is nonempty
2356017ms            main.cpp:63                   main                 ] 13 St9exception: basic_ios::clear: iostream error
basic_ios::clear: iostream error: 
    {"my->genesis_file.generic_string()":"/usr/eos/build/genesis.json","what":"basic_ios::clear: iostream error"}
      chain_plugin.cpp:257 plugin_startup

Although I re-created data-dir folder and this problem doesn't happen, I wonder what cause this happening.   I have tried to create and deploy a hello contract but failed , maybe that is the reason?
The failed contract response is like this:
root@vico-H61M-S2P-B3:/usr/eos/build/hello# eosc create account inita currency EOS6VNsjksoG2TV5RrspQ5U4CwSbN9uHRXmkhEbdxGteAMbEKeeD1 EOS5mzg6DrTH9w1DH1vC3mX1XQvpTjcTC9vo9z7k6giEvdSd5Pzsa
2473507ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 401
: {"code":401,"message":"UnAuthorized","details":"signatures do not satisfy declared authorizations (3030002)\nTransaction declares authority '{\"account\":\"inita\",\"permission\":\"active\"}', but does not have signatures for it.\n"}

**Comment by rommzestz** [comment]
so , you can use it
./eosd --resync-blockchain
