### ISSUE TITLE
pushing message to exchange contract

### ISSUE THREAD

**Issue by jatinmehta420** [EOSIO/eos#1180]
![image](https://user-images.githubusercontent.com/22103300/35264102-6b1c1592-0041-11e8-857b-91dc575786fa.png)
This is the message that I have pushed to the exchange contract. I have created three accounts i.e. 1) Currency account, 2) Exchange account, 3) Tester account. I have deployed currency contract to currency account and exchange contract to exchange account. I am providing the data according to the exchange code and i am getting internal service error. Please tell me is there any mistake and to do it right way.

Thanks and Regards 
Jatin Mehta

**Comment by andriantolie** [comment]
The exchange contract has been heavily refactored last March. If you still have an issue uploading the new exchange contract, please create a new issue. I'm closing this issue as it's obsolete. Thanks!
