### ISSUE TITLE
not able to use eoscpp

### ISSUE THREAD

**Issue by jatinmehta420** [EOSIO/eos#1181]
For creating a skeleton of smart contract, I navigated to eos/build/tools. In that folder I used following command
$ eoscpp -n hello
and getting following error
command not found
and if i use following command
$ ./eoscpp -n hello
then it gives following output
cp: cannot stat '/usr/local/share/skeleton/.': No such file or directory

**Comment by jatinmehta420** [comment]
issue has been resolved by sudo make install in ~/eos/build directory

**Comment by xingstarx** [comment]
@jatinmehta420 hi, did you compile eos in ~/eos directory？ if I compile in ~/block-chain/eos，what did I do

**Comment by jatinmehta420** [comment]
@xingstarx Have you cloned the repository in the path you mentioned?

**Comment by xingstarx** [comment]
ok， I solve this problem

thanks

**Comment by rommzestz** [comment]
try

 cd /root/eos/build/tools
./eoscpp -n testapp
