### ISSUE TITLE
eosd unable to find genesis file

### ISSUE THREAD

**Issue by EdwardJSantos** [EOSIO/eos#1186]
When running eosd I receive the following
` 2298232ms            chain_plugin.cpp:126          plugin_initialize    ] initializing chain plugin
2298232ms            wasm_interface.cpp:757        get                  ] Runtime::init
2298233ms            http_plugin.cpp:138           plugin_initialize    ] host: 127.0.0.1 port: 8888 
2298233ms            http_plugin.cpp:141           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
2298233ms            net_plugin.cpp:2379           plugin_initialize    ] Initialize net plugin
2298233ms            net_plugin.cpp:2399           plugin_initialize    ] Setting net_plugin logging level to info
2298233ms            net_plugin.cpp:2424           plugin_initialize    ] host: 0.0.0.0 port: 9876 
2298233ms            net_plugin.cpp:2503           plugin_initialize    ] my node_id is 69f174591d53a4ab5e6fae1ce53d5d6cc0fae1b26d2677360a969ca29927fbcf
2298233ms            main.cpp:59                   main                 ] eosd version 22acff0c
2298234ms            main.cpp:63                   main                 ] 10 assert_exception: Assert Exception
fc::exists( my->genesis_file ): unable to find genesis file '', check --genesis-json argument
    {"f":""}
      chain_plugin.cpp:228 plugin_startup

    {"my->genesis_file.generic_string()":""}
      chain_plugin.cpp:257 plugin_startu`

I have followed the fix described in issue #1008, but that has not worked. 
Any help would be appreciated.

**Comment by BeBlockTech** [comment]
Hi Edward.

Which version of EOS are you running? If you updated to version 3 your plugins must be updated to eosio instead of eos.

If that doesn't help, can you also please have a look at your path before we dive deeper into this issue. 

Thanks.

**Comment by rijdz** [comment]
try this one instead
```
# Add Genesis File
genesis-json = ../../genesis.json
```

**Comment by michaelbpaulson** [comment]
The project comes with a base `genesis.json`.  The one being referred to is found in the root of the project [Genesis Location](https://github.com/EOSIO/eos/blob/master/genesis.json).  It also seems like you are walking through the project.  

1.  Genesis JSON
Make sure you update you `/path/to/eos/data-dir/config.ini` with the location of genesis block (mentioned above).

If you are going through [building EOS and running a node](https://github.com/EOSIO/eos#building-eos-and-running-a-node)
2.  Don't forget to copy the other fields
[Fields found here](https://github.com/EOSIO/eos#creating-and-launching-a-single-node-testnet)
