### ISSUE TITLE
Images in "Database API" wiki page is broken.

### ISSUE THREAD

**Issue by atjason** [EOSIO/eos#1189]
Hi, 
Please check the images in [Database API](https://github.com/EOSIO/eos/wiki/Database%20API) wiki page, which are broken. Thanks.

**Comment by leordev** [comment]
I was about to write it here but you were faster! 👍 

Guys let me know if you need help with it and docs... I'm not an expert but I'm developing stuff ;)

**Comment by atjason** [comment]
@leordev You're welcome. I just find this issue when reading the docs. As a developer, I also feel it's hard to write document. 😂

**Comment by andriantolie** [comment]
The above wiki is already outdated. I'm going to close this issue. Thanks! :)
