### ISSUE TITLE
docker run errror

### ISSUE THREAD

**Issue by crazybits** [EOSIO/eos#119]
> crazybit:Docker crazybit$ docker-compose -f docker-compose.yml up
Starting docker_eos_1 ...
Starting docker_eos_1 ... done
Attaching to docker_eos_1
eos_1  | cp: cannot create regular file '/opt/eos/bin/data-dir/config.ini': Permission denied
eos_1  | cp: cannot create regular file '/opt/eos/bin/data-dir/genesis.json': Permission denied

**Comment by baryon** [comment]
In mac,  try to change the permissions of data folder by `sudo chmod -R a+w /data/store`

**Comment by sivachaitanya** [comment]
What should I do if I'm on Windows ? I tried creating C:/data/eos and added the share permission, on executing docker-compose I run into ERROR: for eos  Cannot create container for service eos: Drive has not been shared ?

**Comment by gleehokie** [comment]
OBE due to Docker rework
