### ISSUE TITLE
DAWN-508 ⁃ Large txns are not always propagated

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1190]
I have two nodes -- a producer and a non-producer. I ask the non-producer to make a "large" (in this case, ~20KB) transaction. The non-producer node notifies the producer node of this transaction. The producer node then requests the transaction from the non-producer node. But, what ends up happening is that this request gets all the way to connection::txn_send() on the non-producer and is indeed added to txn_queue. But then txn_queue is never serviced because, I believe, no other txns are being sent by non-producer.

Seen on eos-noon Jan17 2018.

**Comment by blockone-syncclient** [comment]
➤ Matt Witherspoon commented:

In the mean time I've increased the threshold in net code so we can deploy currency contract w/o issues.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

[~phil.mesnier] can you look into this?

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

Yes. Matt and I have already discussed the issue. I believe Matt increased the threshold for directly sending transactions rather than just sending a notice message. This is a temporary workaround. The proper fix is to ensure that when a request for a large transaction is received, the actual transaction gets delivered.

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

I am taking this issue now. I believe the recently merged patch for issue 567 addresses this issue, but a test is necessary to verify.

**Comment by pmesnier** [comment]
Overtaken By Events
