### ISSUE TITLE
change a permission error

### ISSUE THREAD

**Issue by Lomect** [EOSIO/eos#1197]
### My account like this(I'm in the testnet):
<img width="570" alt="account" src="https://user-images.githubusercontent.com/20129391/35386827-5f127a34-0208-11e8-9ec5-a62261552ed8.png">
### My wallet has the owner key is like:
<img width="547" alt="wallet" src="https://user-images.githubusercontent.com/20129391/35386860-7e019006-0208-11e8-8439-bad8ab2c29fb.png">

### But when i change the active permission i found the error:
<img width="1437" alt="wx20180125-193939 2x" src="https://user-images.githubusercontent.com/20129391/35386889-9c4559da-0208-11e8-96b7-194bd142684a.png">

# Thanks

**Comment by readytopark** [comment]
Same thing here too. Whatever keys I tried to associate by using `cleos set account permission` command, the added key always becomes `EOS1111111111111111111111111111111114T1Anm` just like your screenshot.

**Comment by noprom** [comment]
Same problem here.

**Comment by mcgtts** [comment]
add `-p myaccount@owner`
```
cleos set account permission myaccount active EOS1111111111111111111111111111111114T1Anm owner -p myaccount@owner
```

**Comment by andriantolie** [comment]
Yes, -p myaccount@owner should solve the problem. I'm closing this issue
