### ISSUE TITLE
error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by DThink** [EOSIO/eos#1205]
ubuntu: 16.04 LTS

hello i've tried to build the last eos package but i receive this error

**error**: linker command failed with exit code 1 (use -v to see invocation)
libraries/chainbase/test/CMakeFiles/chainbase_test.dir/build.make:103: set di istruzioni per l'obiettivo "libraries/chainbase/test/chainbase_test" non riuscito
make[2]: *** [libraries/chainbase/test/chainbase_test] Errore 1
CMakeFiles/Makefile2:316: set di istruzioni per l'obiettivo "libraries/chainbase/test/CMakeFiles/chainbase_test.dir/all" non riuscito
make[1]: *** [libraries/chainbase/test/CMakeFiles/chainbase_test.dir/all] Errore 2
Makefile:160: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2

**Comment by heifner** [comment]
`git submodule update —init —recursive`
