### ISSUE TITLE
about eos ico

### ISSUE THREAD

**Issue by lisongjian** [EOSIO/eos#1210]
Hi, I just have a question about eos ico. Why i still can not see my eos in imtoken/metamask?
here is my transaction info
[etherscan](https://etherscan.io/tx/0x0ad2a9e9ac710b48e7f36fd8252ddba390ae2668a2a1a218dea782d3d0fd4497)

**Comment by lkebin** [comment]
https://etherscan.io/address/0x2277d5489fb8f45f5352c2b95d80f748374f2bc6#tokentxns

**Comment by heifner** [comment]
Issues here are for the EOSIO code base. Please direct your question to telegram https://t.me/EOSproject
