### ISSUE TITLE
DAWN-533 ⁃ rename remaining "eos" directories to "eosio"

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1215]
I found a handful of directories still named "eos" rather than the current term of art, "eosio"

./plugins/net_api_plugin/include/eos
./plugins/template_plugin/include/eos
./plugins/net_plugin/include/eos
./contracts/eos
./libraries/utilities/include/eos
./eos

#### Prerequisites
* None

#### Side effects
* None

#### Procedure
1. Verify no files or paths are named `eos` or `eosxxx` where `xxx` is some string, but rather `eosio` and `eosioxxx`, except for the top level checkout directory/repo name.

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

what about ./contracts/eoslib ?

**Comment by jgiszczak** [comment]
Completed.
