### ISSUE TITLE
DAWN-534 ⁃ Nodes are not forwarding transactions on to other nodes

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1216]
This is based on a situation Matt described in telegram. Here's my interpretation of that explanation:

Phil Mesnier, [Jan 24, 2018 at 10:57:23 PM]:
...Given the scenario of NP ~~> P1(A~~J) ~~> P2(k~~U), you said P1 "receivees" a transaction from NP. At this point, my assumption is this is a signed transaction, since thtas the only kind the p2p network passes. Second, that implies that it is signed by som account that exists on the np node. Third, this txn was generated as a result of some contract executed on node NP. Finally, I assume that the txn is validated by the chain controller on node NP since the only way for NP to send the txn in the first place is via the transaction_ready() call.

Anyway, moving on with the scenario, P1's handle_message(signed_transaction) is invoked causing tge fikkiwing events. The txn is added to P1's local txn cache (or the entry is updated), P1 notes that the txn came from the connection to NP, and finally passed to P1's chain controller. It does not forward the txn on to P2.

I assume that since NP's chain has already validated this txn, the call to P1's accept_transaction() which in turn calls transaction_ready(), won't modify the txn so that what gets passed to transactioon_ready() is the same signed transaction that was received by  in handle_message().

Question at this point is, is transaction_ready() always called as a result of a call to accept_transaction() with a valid signed transaction?

I think that this is a long winded way of saying that handle_message(signed transaction) should not call cache_txn(), rather allow send_all_txn() to do that.

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

This issue is replaced by DAWN-567.

**Comment by andriantolie** [comment]
As mentioned in prev comment, this issue is replaced. I'm closing the issue
