### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by JamesDrummond** [EOSIO/eos#1219]
See PR https://github.com/EOSIO/eos/pull/1218

**Comment by siddharthlatest** [comment]
I can confirm the issue exists.

**Comment by tusik** [comment]
That's work for me

**Comment by JamesDrummond** [comment]
Can someone from the EOSIO please review the PR? I can sign whatever agreement I need to issue my code to the base or have some issue it on my behalf.

**Comment by ericiles** [comment]
PR #1218 has been merged. This is now resolved.
