### ISSUE TITLE
apply() method of smart contract invoked 3 times for a single message

### ISSUE THREAD

**Issue by bosschaert** [EOSIO/eos#1220]
The [Tutorial](https://github.com/EOSIO/eos/wiki/Tutorials) states that the init() method of a smart contract gets invoked 3 times. I can live with that, however a super simple apply() method also gets excuted 3 times for a single message. E.g:

```
void apply( uint64_t code, uint64_t action ) {
        eosio::print( "apply()\n" );
	return;
}
```
Prints on the console for each single message:
```
apply()
apply()
apply()
```

I would really like a single message to be only processed once. Is that possible? Am I doing something wrong?

**Comment by LiorHalfon** [comment]
It's not wrong, The tutorial says that this should happen with **every** transaction.
You can see an example of this [here](https://github.com/EOSIO/eos/wiki/Tutorials#3-smart-contract-hello-world)

**Comment by bosschaert** [comment]
Hi @LiorHalfon, thanks for the response. 

Let's say my apply() method has a side effect, i.e. it stores something in the database or performs a eos transaction between two users. Will this side effect be applied 3 times as well?

**Comment by wanderingbort** [comment]
All effects on the database are rolled back between apply calls.  From the
point of view of the data directly accessible to your contract you can
assume at-most-once semantics.  That is to say, your contract code will
only take a delivery of an action once however, there is no hard guarantee
of delivery.

If you have an *external* system monitoring the chain via logs then you
will need to deal with multiple apply calls in a suitable way.
