### ISSUE TITLE
DAWN-536 ⁃ Large Block notifications break synchronization

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1222]
Matt discovered this situation. When a block producer has a block exceeding the "just send it" size, a notice message is sent and interested receivers have to request the block. but what can happen now is that while a large block is requested, a subsequent block can be produced which is pushed straight away. This new block ends up being received out of order and wackiness ensues.

In the short term we can get around this by always sending blocks regardless of size. 

A proper solution might be to cache "out of order" blocks while awaiting a requested block, or discard those blocks and fall back to a resync mode after receiving the requested block. 

A more exotic solution would be to build up a network node map that enables each node to be aware of which nodes are directly connected peers and thus be able to infer whether a message received from a given peer needs to be forwarded to any other peers.

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

This was a significant topic of discussion at Blacksburg yesterday. Dan set ne right, explaining the details I had missed previously. The key factors being 1) don't send a notice for a message you don't have and 2) do send a notice when you receive a big message.

Adding in a new "Big Message Manager" to coordinate the notification and requesting of big messages, whether those are blocks or transactions.

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

Given the turbulence hitting DAWN 3.0 with the advent of EOSIO-BIOS, I'm going to port my changes for this issue to Dawn 2.x. Then I think we will need to do a rollout to testnet 1. After I've verified it on testnet 2 of course.

**Comment by pmesnier** [comment]
before I make a PR I need to address the deep recursion problem discovered by the community testnet users.

**Comment by brianjohnson5972** [comment]
Are they actually related, or should they be separate PRs?

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

Fix is working on testnet 2 but I want to add a rewrite of the recursive function used to gather "reversible" blocks - if there are too many, they will blow the stack.

**Comment by pmesnier** [comment]
it's all part of synchronization and the program's failure to thrive, so yeah, they're related.
