### ISSUE TITLE
Dawn Alpha 3.0 for macos - SHOULD EOS Be a Root Folder?  Different from before?

### ISSUE THREAD

**Issue by comtechnet** [EOSIO/eos#1229]
EOS Team,

The doc is "emphasizing" that macos EOS should be installed in the "root" EOS folder.  Is this indeed your intent or this a typo or misunderstanding?  For this is a change from the previous install instructions and Brew now generates errors is part of the script when sudo ./build.sh darwin is run.

In my case - all previous macos installs were for my main user account /myuseraccount/eos
eosjs was installed here, etc. /myuseraccount/eosjs

PLEASE CLARIFY.

Also - you seem to be also emphasizing a change from EOS naming to EOSIO, yet the main folder remains EOS - small confusing issue.

**Comment by andriantolie** [comment]
The documentation has been modified a lot since Dawn 3.0, if you still see a similar issue with the new doc, please create new issue. I'm closing this issue. Thanks!
