### ISSUE TITLE
Dawn Alpha 3.0 for mongo_db_plugin not selected and will be omitted

### ISSUE THREAD

**Issue by Lomect** [EOSIO/eos#1231]
I build the Dawn Alpha 3.0 in ubuntu,the mongodb_plugin is not in the build and log : 
Using custom FindBoost.cmake
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   chrono
--   program_options
--   unit_test_framework
--   locale
-- Configuring AppBase on Linux
-- Using custom FindBoost.cmake
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   unit_test_framework
mongo_db_plugin not selected and will be omitted.
-- Git commit revision: 37312a4b
-- Git commit revision: 37312a4b
-- Git commit revision: 37312a4b

please give me a result for this question. Thanks

**Comment by jgiszczak** [comment]
This is expected output.  The mongo_db_plugin is optional, not required to run a testnet.  It can be enabled on the `cmake` command line with `-DBUILD_MONGO_DB_PLUGIN`.
