### ISSUE TITLE
Upload the "hello world" contract, there is an error

### ISSUE THREAD

**Issue by xuwei2014** [EOSIO/eos#1236]
Hi there,
I use the command "eoscpp -n hello" to create a contract.  And then upload the contract, there is an error like the following:

eosioc set contract hello hello.wast hello.abi
Reading WAST...
Assembling WASM...
766020ms thread-0   main.cpp:1209                 main                 ] Failed with error: Bad Cast (7)
Invalid cast from object_type to Array

Please help me to look at it.
Thanks.

**Comment by michaelbpaulson** [comment]
I am experiencing the same thing.  I get to the assembly part and boom.

**Comment by michaelbpaulson** [comment]
From the Telegram Channel:

1.  Produce the abi file
```
path/to/eoscpp -g hello.abi hello.hpp
```

2.  Then recompile the contract
```
/path/to/eoscpp -o hello.wast hello.cpp
```

3.  Set the contract 
eosioc set contract hello hello.wast hello.abi

**Comment by michaelbpaulson** [comment]
@xuwei2014 there also seems to be issues with the other contracts on master at this time (of commenting).  The recommended path, again, at this time, is to use dawn-2.x for dev.  

Things will change, but not so wild as to losing any learnings along the way.  Only the internal libs may change.  Like I see a big change in eoslib/token, but I am sure it will make more sense once dawn 3.0.x is in a better place.

**Comment by xuwei2014** [comment]
@michaelbpaulson thank you for you help. Your suggestion makes sense for me. I will use the recommended path:)
