### ISSUE TITLE
eosio 2.* source code

### ISSUE THREAD

**Issue by wanghuangang** [EOSIO/eos#1240]
Excuse me,where i can find the function called "front_primary_i128i128" source code?
for eg:
int32_t front_primary_i128i128( account_name scope, account_name code, table_name table, void* data, uint32_t len );
in path :"..\eos\contracts\eoslib\db.hpp"

**Comment by brianjohnson5972** [comment]
The implementation is provided in the eosd(2.x)/eosiod(3.x) when the contract is loaded to be able to run.  Functions that are declared in eoslib/*.h files are provided to the contract when it is loaded.

Also, please use the "EOS Developers" channel in Telegram for questions like these, github should only be used for problems that cannot be handled on "EOS Developers"

**Comment by wanghuangang** [comment]
Thanks ,I will download Telegram
