### ISSUE TITLE
DAWN-546 ⁃ add lazy enforcement of account-scope-table key usage unit tests

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1245]
Implemenation was added, but adding unit tests is a separate task, so higher priority tasks can move forward.  Put a place holder in wasm_test.cpp as test_table_key_validation.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

[~brian.johnson] Thoughts on Story point estimate?

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

I'm going to close-withdraw this since the lazy enforcement code is being stripped out.

**Comment by andriantolie** [comment]
As mentioned in prev comment. I'm closing this issue
