### ISSUE TITLE
EOS Database API Wiki Unknown Parameter in 32 remove_str

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eos#1247]
### [Remove_str is unclear](https://github.com/eosio/eos/wiki/Database%20API#remove_str) 
No `data` as parameter input
![image](https://user-images.githubusercontent.com/16319106/35576825-ef1f3d36-061a-11e8-970e-41fe59aa0ebf.png)

**Comment by dskvr** [comment]
This was clarified, closing now
