### ISSUE TITLE
master build error

### ISSUE THREAD

**Issue by jieniu** [EOSIO/eos#1250]
When I built the latest master code, I got this message

![image](https://user-images.githubusercontent.com/7031129/35616894-94008c38-06b1-11e8-8cb8-a94b419eeebf.png)

The command line is: 
```
$ git clone https://github.com/eosio/eos
$ git submodule update --init --recursive
$ ./build.sh darwin full
```

My env is macOS 10.13.2

**Comment by jgiszczak** [comment]
Be sure your brew-installed version of llvm is llvm@4.
