### ISSUE TITLE
MongoDB plugin: capped collections / tailable cursors?

### ISSUE THREAD

**Issue by liamcurry** [EOSIO/eos#1257]
I would like to listen for new items being added to MongoDB from EOS and push these updates to users in real-time. One way of doing this is with [tailable cursors](https://docs.mongodb.com/manual/core/tailable-cursors/), however this is only available on capped collections.

It seems there's no way to customize EOS's MongoDB collections to make them capped, and the collections appear to be wiped every time `eosiod` is started with `--replay-blockchain`. Is there any way around this?

**Comment by jgiszczak** [comment]
The mongo DB plugin does not support capped collections.  Pull requests are happily accepted.  Bear in mind that the mongo DB plugin may not survive long term.
