### ISSUE TITLE
Cannot find transactions of account

### ISSUE THREAD

**Issue by JamesDrummond** [EOSIO/eos#1264]
Using latest master I cannot find transactions for inita. Am I doing something wrong?

eosioc -p 8888 get info
{
  "server_version": "8d245066",
  "head_block_num": 9161,
  "last_irreversible_block_num": 9077,
  "head_block_id": "000023c94320e1314fa7e4d8761f497c11151a3400be7747ec84cb13190150e8",
  "head_block_time": "2018-02-01T02:39:14",
  "head_block_producer": "inito",
  "recent_slots": "1111111111111111111111111111111111111111111111111111111111111111",
  "participation_rate": "1.00000000000000000"
}

eosioc -p 8888 get transactions inita
2417287ms thread-0   main.cpp:1209                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 404
: {"code":404,"message":"Not Found","details":"Unknown Endpoint"}

**Comment by michaelbpaulson** [comment]
@JamesDrummond have you checked your plugins?

Here is the list of what I have found to be most helpful (part from telegram) (add to your path/to/data-dir/config.ini)

```
# Load the block producer plugin, so you can produce blocks
plugin = eosio::producer_plugin
# Wallet plugin
plugin = eosio::wallet_api_plugin
# As well as API and HTTP plugins
plugin = eosio::chain_api_plugin
plugin = eosio::http_plugin
plugin = eosio::account_history_plugin
plugin = eosio::account_history_api_plugin
```

If that helps please close ticket :)

**Comment by JamesDrummond** [comment]
@michaelbpaulson That was it :). Thanks man.
