### ISSUE TITLE
Documentation Request: scope

### ISSUE THREAD

**Issue by michaelbpaulson** [EOSIO/eos#1271]
I have been hacking on EOS for a week or so and I find scope to be confusing.  There does seem to be a lack of explanation of its purpose in its relation to account and permissions.  All of these learnings have been Dawn 2.x which may be irrelevant, and if so, please let me know.

Example, transfer funds:
```
eosc push message eos transfer '{"to": "rps", "from": "inita", "amount": 5000, "memo": "gimmie the gold"}' --scope rps,inita --permission inita@active
```

It seems weird that I have to specify the scope which happen to be the `to`/`from` accounts, and the permissions prove that `inita` has signed this request.  

Example in Databases
The C++ Wrappers use the following (from this [Wiki page](https://github.com/EOSIO/eos/wiki/Database%20API#2212-example)):
```
static bool table< scope, code, table, Record, PrimaryType, void >::get	(const PrimaryType &p, Record &r, uint64_t s=scope)
```

There are two mentions of `scope` one for the table specification and one for the third argument of `get`.  I have found examples of it in tic tac toe.

[Example of creating Games table](https://github.com/EOSIO/eos/blob/dawn-2.x/contracts/tic_tac_toe/tic_tac_toe.hpp#L126)
[Example of using get with scope](https://github.com/EOSIO/eos/blob/dawn-2.x/contracts/tic_tac_toe/tic_tac_toe.cpp#L96)

I would appreciate an explanation if anyone has one to give.  I assume other people are having troubles as well.

**Comment by jgiszczak** [comment]
Scope is now automatically determined internally, and has been renamed to more closely reflect its actual use.  You no longer have to provide it or any analog of it.  You'll need to study the new 3.0 release and it's accompanying documention which is due out soon.
