### ISSUE TITLE
Abort Trap 6 & Bus error 10 encountered in DAWN-2018-01-25-ALPHA 

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eos#1278]
## `Pure virtual function called !`
![image](https://user-images.githubusercontent.com/16319106/35728463-a03e06e2-0846-11e8-8310-4454b255ba45.png)
## `set_options `: invalid argument (Bus error 10)
![image](https://user-images.githubusercontent.com/16319106/35728484-ae2592b6-0846-11e8-8cf9-ca5df5128299.png)

**Comment by andriantolie** [comment]
The code has undergone a lot of change since 25 Jan. Please create new issue if you encounter a similar problem with the latest code. I'm closing this issue. Thanks!
