### ISSUE TITLE
Can't build Docker image on dawn-2.x branch

### ISSUE THREAD

**Issue by liamcurry** [EOSIO/eos#1289]
I'm unable to build the Docker image on the `dawn-2.x` branch.

The first issue is on this line: https://github.com/EOSIO/eos/blob/dawn-2.x/Docker/Dockerfile#L75

On that line `master` needs to be changed to `dawn-2.x` in order for Docker to build on the right branch.

Then, once that is changed the build gets a little farther, but now I'm seeing this failure:

![image](https://user-images.githubusercontent.com/77758/35759480-35bb13e6-0837-11e8-931a-1bda54eafc57.png)

Any ideas?

**Comment by liamcurry** [comment]
FYI I was able to fix this issue with the changes in PR #1184

**Comment by ericiles** [comment]
This should be resolved with PR #1547.
