### ISSUE TITLE
LibbsoncxxConfig.cmake errors when building WASM on Ubuntu

### ISSUE THREAD

**Issue by Babaloncryptolog** [EOSIO/eos#1290]
First of all, I would like to say I have found no file containing any Libbsoncxx related file on my computer and I have tried to setup/install all related Mongo. I personally built everything from source but this error will pop up regardless when trying to install the WASM dependency. 

***I would not be posting here If I could find a straight answer elsewhere and I'm not the only one struggling to figure this issue out so please help bring a solution to the table before closing this issue out prematurely. ***

CMake Error at plugins/db_plugin/CMakeLists.txt:21 (find_package):
  By not providing "Findlibbsoncxx.cmake" in CMAKE_MODULE_PATH this project <-- (Doesn't exist)
  has asked CMake to find a package configuration file provided by
  "libbsoncxx", but CMake did not find one.

  Could not find a package configuration file provided by "libbsoncxx" with
  any of the following names:

    libbsoncxxConfig.cmake <-- (Doesn't exist)
    libbsoncxx-config.cmake <-- (Doesn't exist)

  Add the installation prefix of "libbsoncxx" to CMAKE_PREFIX_PATH or set 
  "libbsoncxx_DIR" to a directory containing one of the above files.  If
  "libbsoncxx" provides a separate development package or SDK, be sure it has
  been installed. <-- (This Directory doesn't exist)

-- Configuring incomplete, errors occurred!
See also "/home/USER/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/USER/eos/build/CMakeFiles/CMakeError.log".

**Comment by flyq** [comment]
sadf

**Comment by Lonenso** [comment]
did u figure out how to solve it ?
