### ISSUE TITLE
Not binnary eosioc and eosiod found

### ISSUE THREAD

**Issue by Npizza** [EOSIO/eos#1291]
I have tried to set up the testnet and I follow the instructions 

`git clone https://github.com/eosio/eos --recursive

cd eos
./build.sh `ubuntu``

and all went good but i am trying found eosioc and eosiod to run it and it is not in the path `build/programs/eosiod` 

i only find CMakeFiles folder and config.hpp
Can you help me please?

**Comment by zshchou** [comment]
cd build
sudo make install
