### ISSUE TITLE
the first prducter now is eosio, and eosiod error!

### ISSUE THREAD

**Issue by zshchou** [EOSIO/eos#1296]
2617277ms thread-0   net_plugin.cpp:2559           plugin_startup       ] starting listener, max clients is 25
2617500ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
2618005ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
2618505ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio

**Comment by zshchou** [comment]
2616759ms thread-0   main.cpp:85                   main                 ] eosiod version 103c6901
2616761ms thread-0   block_log.cpp:92              open                 ] Opening block log at /Users/zsh/data_eos/blocks/blocks.log
2616762ms thread-0   chain_initializer.cpp:34      get_chain_start_prod ] result: {"version":0,"producers":[{"producer_name":"eosio","block_signing_key":"EOS1111111111111111111111111111111114T1Anm"}]} 
2616762ms thread-0   chain_initializer.cpp:34      get_chain_start_prod ] result: {"version":0,"producers":[{"producer_name":"eosio","block_signing_key":"EOS1111111111111111111111111111111114T1Anm"}]} 
2616762ms thread-0   chain_initializer.cpp:34      get_chain_start_prod ] result: {"version":0,"producers":[{"producer_name":"eosio","block_signing_key":"EOS1111111111111111111111111111111114T1Anm"}]} 
2616762ms thread-0   chain_controller.cpp:1075     operator()           ] starter.get_chain_start_producers(): {"version":0,"producers":[{"producer_name":"eosio","block_signing_key":"EOS1111111111111111111111111111111114T1Anm"}]} 
2617271ms thread-0   chain_controller.cpp:1106     operator()           ] applying genesis transaction

**Comment by heifner** [comment]
As of February 2018, master is under heavy development and is not suitable for experimentation.

**Comment by WildDylan** [comment]
producer-name = eosio
