### ISSUE TITLE
Error when creating currency account in README

### ISSUE THREAD

**Issue by sjkelleyjr** [EOSIO/eos#1298]
During the step: "Creating accounts for sample "currency" contract"

I'm running the following command:

`./eosioc create account inita currency PUBLIC_KEY_1 PUBLIC_KEY_2`

And getting the following error output:

```
729465ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 401
: {"code":401,"message":"UnAuthorized","details":"signatures do not satisfy declared authorizations (3030002)\nTransaction declares authority '{\"account\":\"inita\",\"permission\":\"active\"}', but does not have signatures for it.\n"}
```

I've already generated the two public keys using the steps described in the README:
```
cd ~/eos/build/programs/eosioc/
./eosioc create key # owner_key
./eosioc create key # active_key
```

and they are:
Public key: EOS6G7H8p2fKsqr2H2YoB9CTikAKh9sBgYmVV7138jGH37e7wD3qD
Public key: EOS5rwGKhMJqMzTokrdNvihThohr7EduLVhG3Rra1PvePJvvixgz3

so all together the command to create the currency account is:
```
./eosioc create account inita currency EOS6G7H8p2fKsqr2H2YoB9CTikAKh9sBgYmVV7138jGH37e7wD3qD EOS5rwGKhMJqMzTokrdNvihThohr7EduLVhG3Rra1PvePJvvixgz3
```

I've also imported the inita key using the step:
`./eosioc wallet import 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3`

Any thoughts?

**Comment by sjkelleyjr** [comment]
That was the problem, I've since switch to using a single node net and I'm getting the following error now instead:

```
2577076ms thread-0   main.cpp:985                  main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"10 assert_exception: Assert Exception\n(used_ubytes * dgpo.total_net_weight) <= (buo.net_weight * virtual_max_ubytes): authorizing account 'inita' has insufficient net bandwidth for this transaction\n    {\"n\":\"inita\",\"used_bytes\":\"348.00000000000000000\",\"user_net_weight\":0,\"virtual_max_bytes\":\"125829120.00000000000000000\",\"total_net_weight\":1}\n    thread-0  chain_controller.cpp:1597 update_usage\n\n    {\"trx\":{\"signatures\":[\"EOSKadLFWARYpowUgG5nQ4yYE9iXbq7hxVxTX9MzfBAY6RAkexgrdBmgBvVE6MxMQjjESKPcHve26muaCZ4uxLwjkwguFvcTt\"],\"compression\":\"none\",\"data\":\"5ef3dc580000000000000000010000000000ea305500409e9a2264b89a01000000000093dd7400000000a8ed32327c000000000093dd740000001e4d75af460100000000010003724af0ca707317d05647bfaf47c02376a78bb1da55522b5c41d09e9ee6ed25f40100010000000001000264c502370ce07cc2ae3e86194361aff637488dfdc908166a60809cb2715c5da401000100000001000000000093dd7400000000a8ed3232010000\"}}\n    thread-0  chain_controller.cpp:265 push_transaction"}
```

**Comment by algys** [comment]
I caught similar problem :(
`
1373487ms thread-0   main.cpp:985                  main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"10 assert_exception: Assert Exception\n(used_ubytes * dgpo.total_net_weight) <= (buo.net_weight * virtual_max_ubytes): authorizing account 'inita' has insufficient net bandwidth for this transaction\n    {\"n\":\"inita\",\"used_bytes\":\"348.00000000000000000\",\"user_net_weight\":0,\"virtual_max_bytes\":\"125829120.00000000000000000\",\"total_net_weight\":1}\n
`
I think that setup the 'user_net_weight' would solve this problem, but I don't know how to do it.

**Comment by heifner** [comment]
Did you see this is the `README.md`:

`As of February 2018, master is under heavy development and is not suitable for experimentation.`

**Comment by sjkelleyjr** [comment]
Yeah, I did, which is why I tried following the steps for the Dawn-2.x fork in the README, yielding the results in the original post.  If we want to deploy the currency contract what is the best way of doing that?

**Comment by AleksandrKh** [comment]
the same with Dawn-2:

```
./eosc create account inita currency EOS6HVayTMZzXf8VvYodJ6st1LLsRu5DeuWGmKRkgGHnNtwUEZ3wa EOS8fDSnDLLxw1tAsN4LwzfDZNybwe14mCMLnC6wsBrJdK6wn4HdD
1318708ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 401
: {"code":401,"message":"UnAuthorized","details":"signatures do not satisfy declared authorizations (3030002)\nTransaction declares authority '{\"account\":\"inita\",\"permission\":\"active\"}', but does not have signatures for it.\n"}
```

**Comment by sjkelleyjr** [comment]
For anyone else running into the same issue.  I checked out the commit prior to [1404de9](https://github.com/EOSIO/eos/commit/1404de957e280d975e3cd116d681c39c544d67d9) as @algys suggested and followed the steps for the master branch, this fixed the issue (note that I had to delete directories in the data-dir)

**Comment by jdavid82** [comment]
@sjkelleyjr I tried yesterday by deleting the whole repo, cloning and resetting to the commit prior to the one you mentioned (dawn-2.x of course). But now this time it fails to build
