### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by TaiChiBagua** [EOSIO/eos#1301]
I build in ubuntu and got the error when I execute make, what is wrong?

../Runtime/libRuntime.a(LLVMJIT.cpp.o):(.rodata._ZTIN7LLVMJIT12NullResolverE[_ZTIN7LLVMJIT12NullResolverE]+0x10): undefined reference to `typeinfo for llvm::JITSymbolResolver'
../Runtime/libRuntime.a(LLVMJIT.cpp.o):(.rodata._ZTIN7LLVMJIT17UnitMemoryManagerE[_ZTIN7LLVMJIT17UnitMemoryManagerE]+0x10): undefined reference to `typeinfo for llvm::RTDyldMemoryManager'
../Runtime/libRuntime.a(LLVMJIT.cpp.o):(.rodata._ZTIN4llvm18ObjectMemoryBufferE[_ZTIN4llvm18ObjectMemoryBufferE]+0x10): undefined reference to `typeinfo for llvm::MemoryBuffer'
../Runtime/libRuntime.a(LLVMJIT.cpp.o):(.rodata._ZTIN4llvm18MCJITMemoryManagerE[_ZTIN4llvm18MCJITMemoryManagerE]+0x10): undefined reference to `typeinfo for llvm::RuntimeDyld::MemoryManager'
../Runtime/libRuntime.a(LLVMJIT.cpp.o):(.rodata._ZTIN4llvm9ErrorInfoINS_9ErrorListENS_13ErrorInfoBaseEEE[_ZTIN4llvm9ErrorInfoINS_9ErrorListENS_13ErrorInfoBaseEEE]+0x10): undefined reference to `typeinfo for llvm::ErrorInfoBase'
../Runtime/libRuntime.a(LLVMJIT.cpp.o):(.rodata._ZTIN4llvm17raw_pwrite_streamE[_ZTIN4llvm17raw_pwrite_streamE]+0x10): undefined reference to `typeinfo for llvm::raw_ostream'
../Runtime/libRuntime.a(LLVMEmitIR.cpp.o):(.rodata._ZTIN4llvm10SelectInstE[_ZTIN4llvm10SelectInstE]+0x10): undefined reference to `typeinfo for llvm::Instruction'
../Runtime/libRuntime.a(LLVMEmitIR.cpp.o):(.rodata._ZTIN4llvm8FCmpInstE[_ZTIN4llvm8FCmpInstE]+0x10): undefined reference to `typeinfo for llvm::CmpInst'
collect2: error: ld returned 1 exit status
libraries/wasm-jit/Source/Programs/CMakeFiles/Test.dir/build.make:128: recipe for target 'libraries/wasm-jit/Source/Programs/Test' failed
make[2]: *** [libraries/wasm-jit/Source/Programs/Test] Error 1
CMakeFiles/Makefile2:1127: recipe for target 'libraries/wasm-jit/Source/Programs/CMakeFiles/Test.dir/all' failed
make[1]: *** [libraries/wasm-jit/Source/Programs/CMakeFiles/Test.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by myenglishmail** [comment]
the llvm's rtti
ran the command: llvm-config --has-rtti
if it shows NO, the rtti is closed, you need to open it

**Comment by warlish** [comment]
please how to open rtti, thanks a lot!

**Comment by bingfeng28** [comment]
@myenglishmail 
I got this error on ubuntu 16.04 too.
And ran this command: llvm-config --has-rtti
Output: YES
But build failed.
How can I fix this issue?
Thanks.

**Comment by pacificcode** [comment]
@bingfeng28 I need more information, can you run the following commands and paste the FULL output here?
llvm-config --has-rtti --version
gcc --version
cd /path/to/eos
rm -rf build/
git checkout master
git pull
git submodule update --init --recursive
./eosio_build.sh
