### ISSUE TITLE
./eosioc set contract currency  failed-----------------------------

### ISSUE THREAD

**Issue by myenglishmail** [EOSIO/eos#1312]
I followed the   
https://github.com/EOSIO/eos/
instruction to build the master version on ubuntu 16.10

and also follow the : Example "Currency" Contract Walkthrough 
but 1 issue as follow : 

**root@ubuntu:~/eosn/eos_clang/build/programs/eosioc# ./eosioc set contract currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi
Reading WAST...
Assembling WASM...
Publishing contract...
92623ms thread-0   main.cpp:1209                 main                 ] Failed with error: read_until: End of file (13)
read_until: End of file:** 

and the eosiod shows:

**initt generated block d530722e... #494 @ 2018-02-05T09:47:40.000 with 0 trxs
initt generated block d10c7927... #495 @ 2018-02-05T09:47:40.500 with 0 trxs
initt generated block 36026ddb... #496 @ 2018-02-05T09:47:41.000 with 0 trxs
initt generated block f826d469... #497 @ 2018-02-05T09:47:41.500 with 0 trxs
initu generated block b9c79205... #498 @ 2018-02-05T09:47:42.000 with 0 trxs
initu generated block 1224c2ec... #499 @ 2018-02-05T09:47:42.500 with 0 trxs
initu generated block 82073473... #500 @ 2018-02-05T09:47:43.000 with 0 trxs
initu generated block fe35a925... #501 @ 2018-02-05T09:47:43.500 with 0 trxs
initu generated block 5f699b23... #502 @ 2018-02-05T09:47:44.000 with 0 trxs
Segmentation fault (core dumped)**

I alse got the core dump file: (I donot know how to upload the coredump file, paste it )

Core was generated by `./eosiod'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f74d9ed0aee in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007f74d9ed0aee in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007f74d9ed0ed9 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000020a396b in llvm::DataLayout::operator=(llvm::DataLayout const&) ()
#3  0x00000000020a3835 in llvm::DataLayout::DataLayout(llvm::DataLayout const&) ()
#4  0x00000000020a0940 in llvm::TargetMachine::createDataLayout() const ()
#5  0x000000000209e0c9 in LLVMJIT::JITUnit::compile(llvm::Module*) ()
#6  0x000000000209e72e in LLVMJIT::instantiateModule(IR::Module const&, Runtime::ModuleInstance*) ()
#7  0x000000000208b913 in Runtime::instantiateModule(IR::Module const&, Runtime::ImportBindings&&) ()
#8  0x0000000001e54739 in eosio::chain::wasm_cache_impl::fetch_entry(fc::sha256 const&, char const*, unsigned long)::{lambda()#1}::operator()() const ()
#9  0x0000000001e5458e in auto eosio::chain::wasm_cache_impl::with_lock<eosio::chain::wasm_cache_impl::fetch_entry(fc::sha256 const&, char const*, unsigned long)::{lambda()#1}>(std::mutex&, eosio::chain::wasm_cache_impl::fetch_entry(fc::sha256 const&, char const*, unsigned long)::{lambda()#1}) ()
#10 0x0000000001e50feb in eosio::chain::wasm_cache_impl::fetch_entry(fc::sha256 const&, char const*, unsigned long) ()
#11 0x0000000001e4f22f in eosio::chain::wasm_cache::checkout(fc::sha256 const&, char const*, unsigned long) ()
#12 0x0000000001e8f280 in eosio::chain::wasm_cache::checkout_scoped(fc::sha256 const&, char const*, unsigned long) ()
#13 0x0000000001e88104 in eosio::chain::apply_context::exec_one() ()
#14 0x0000000001e8b2f8 in eosio::chain::apply_context::exec() ()
#15 0x0000000001b3669c in eosio::chain::chain_controller::__apply_transaction(eosio::chain::transaction_metadata&) ()
#16 0x0000000001b22a49 in eosio::chain::chain_controller::_apply_transaction(eosio::chain::transaction_metadata&) ()
#17 0x0000000001b21a9f in eosio::chain::chain_controller::_push_transaction(eosio::chain::transaction_metadata&) ()
#18 0x0000000001b21780 in eosio::chain::chain_controller::_push_transaction(eosio::chain::signed_transaction const&) ()
#19 0x0000000001b3e246 in eosio::chain::chain_controller::push_transaction(eosio::chain::signed_transaction const&, unsigned int)::$_1::operator()() const::{lambda()#1}::operator()() const ()
#20 0x0000000001b3e1e7 in chainbase::database::with_write_lock<eosio::chain::chain_controller::push_transaction(eosio::chain::signed_transaction const&, unsigned int)::$_1::operator()() const::{lambda()#1}> ()
#21 0x0000000001b3de8e in eosio::chain::chain_controller::push_transaction(eosio::chain::signed_transaction const&, unsigned int)::$_1::operator()() const ()
#22 0x0000000001b21672 in auto eosio::chain::chain_controller::with_skip_flags<eosio::chain::chain_controller::push_transaction(eosio::chain::signed_transaction const&, unsigned int)::$_1>(unsigned long, eosio::chain::chain_controller::push_transaction(eosio::chain::signed_transaction const&, unsigned int)::$_1&&) ()
#23 0x0000000001b20b0f in eosio::chain::chain_controller::push_transaction(eosio::chain::signed_transaction const&, unsigned int) ()
#24 0x000000000191a70d in eosio::chain_apis::read_write::push_transaction(fc::variant_object const&) ()
#25 0x00000000018efb35 in eosio::chain_api_plugin::plugin_startup()::$_11::operator()(std::__cxx11::basic_string<char, std::char_trai---Type <return> to continue, or q <return> to quit---q

[Uploading core…]()

**Is there any idea?  how to fix it ?**

**Comment by andriantolie** [comment]
currency contract is no longer available now. Please create a new issue if you still have problem uploading eosio.token contract instead. I'm closing this issue. Thanks!
