### ISSUE TITLE
Asserter Contract

### ISSUE THREAD

**Issue by JamesDrummond** [EOSIO/eos#1317]
How do I use the `provereset` function? I was able to figure out `procassert` is `eosioc push action asserter procassert '{"condition":"1","message":"test"}' --permission asserter@active`.

https://github.com/EOSIO/eos/blob/master/contracts/asserter/asserter.cpp#L33

**Comment by andriantolie** [comment]
provereset accepts no param, so `cleos push action asserter provereset '[]' -p asserter` will do
