### ISSUE TITLE
contracts/eoslib/db.hpp does not plumb scope

### ISSUE THREAD

**Issue by michaelbpaulson** [EOSIO/eos#1321]
`scope` is not plumbed through all the interfaces though the underlying `primary_index` lookups support this functionality.

[Front and Back missing scope](https://github.com/EOSIO/eos/blob/master/contracts/eosiolib/db.hpp#L629)

I have included a PR for the fix #1320 

------
I have only fixed it in dawn-2x but I can just as easily open this PR against master too.

**Comment by heifner** [comment]
Fixed via #1320
