### ISSUE TITLE
DAWN-573 ⁃ Add bootstrap command to eosioc

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1334]
# Bootstrapping a Chain from the command line

Before the `bios` branch was conceived our genesis block was implied by `genesis.json` and this was to be generated from the ERC-20 snapshot upon launch.   With the `bios` mentality, this needs to become an explicit block of transactions authorized by the system account after installing the base system contract.

This task is to add a `bootstrap` command to `eosioc` with at least one options that reads the output of the snapshot tools and produces all the accounts required including transitioning production to the 21 producers.

**Comment by jgiszczak** [comment]
OBE.  Mainnet has launched.  The snapshot was loaded via one-off script.
