### ISSUE TITLE
Not producing block because it isn't my turn, its eosio

### ISSUE THREAD

**Issue by zhangrm** [EOSIO/eos#1345]
please help:
167844ms thread-0   producer_plugin.cpp:167       plugin_startup       ] producer plugin:  plugin_startup() end
167844ms thread-0   http_plugin.cpp:156           plugin_startup       ] start processing http thread
167844ms thread-0   http_plugin.cpp:213           plugin_startup       ] start listening for http requests
167844ms thread-0   http_plugin.cpp:218           plugin_startup       ] http io service exit
167844ms thread-0   wallet_api_plugin.cpp:70      plugin_startup       ] starting wallet_api_plugin
167844ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/create
167844ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/get_public_keys
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/import_key
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/list_keys
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/list_wallets
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/lock
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/lock_all
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/open
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/set_timeout
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/sign_transaction
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/unlock
167845ms thread-0   chain_api_plugin.cpp:62       plugin_startup       ] starting chain_api_plugin
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/abi_bin_to_json
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/abi_json_to_bin
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_account
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_block
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_code
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_currency_balance
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_currency_stats
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_info
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_required_keys
167845ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_table_rows
167846ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/push_block
167846ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/push_transaction
167846ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/push_transactions
167846ms thread-0   net_plugin.cpp:2681           plugin_startup       ] starting listener, max clients is 25
168000ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
168500ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
169001ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
169500ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
170000ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
170500ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
171000ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
171500ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
172000ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
172500ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
173000ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio

**Comment by heifner** [comment]
master is not in a state at the moment to run a private testnet. Please see the README.md

**Comment by rommzestz** [comment]
just add eosio as producer on config.ini

**Comment by WildDylan** [comment]
producer-name = eosio
