### ISSUE TITLE
./eosioc create account inita currency public_key_1 public_key_2 error

### ISSUE THREAD

**Issue by tqqttq** [EOSIO/eos#1347]
chain_api_plugin.cpp:77       operator()           ] Exception encountered while processing chain.get_required_keys: {"code":13,"name":"St9exception","message":"unknown key","stack":[{"context":{"level":"warn","file":"chain_controller.cpp","line":1032,"method":"get_permission","hostname":"","thread_name":"thread-0","timestamp":"2018-02-09T07:57:55.703"},"format":"${what}: ","data":{"level":{"actor":"inita","permission":"active"},"what":"unknown key"}}]}

**Comment by ildr3him** [comment]
Same Error with me I think:

./eosioc create account inita cp42 EOS5ESsEC7hs2qPvjrgSaZTbnK1hpeKUrshLx4BrN1MUbWQSrfugK EOS8g1T9SeiA1p6EnuXX7ZEJrgauBb2TEzrYeC4wwfHR5dEp34Fa7 300798ms thread-0 main.cpp:1008 main ] Failed with error: Assert Exception (10) status_code == 200: Error code 500 : {"code":500,"message":"Internal Service Error","details":"13 St9exception: unknown key\nunknown key: \n {\"level\":{\"actor\":\"inita\",\"permission\":\"active\"},\"what\":\"unknown key\"}\n thread-0 chain_controller.cpp:1032 get_permission"}

and in the eosiod Terminal Window:
./eosioc create account inita cp42 EOS5ESsEC7hs2qPvjrgSaZTbnK1hpeKUrshLx4BrN1MUbWQSrfugK EOS8g1T9SeiA1p6EnuXX7ZEJrgauBb2TEzrYeC4wwfHR5dEp34Fa7 300798ms thread-0 main.cpp:1008 main ] Failed with error: Assert Exception (10) status_code == 200: Error code 500 : {"code":500,"message":"Internal Service Error","details":"13 St9exception: unknown key\nunknown key: \n {\"level\":{\"actor\":\"inita\",\"permission\":\"active\"},\"what\":\"unknown key\"}\n thread-0 chain_controller.cpp:1032 get_permission"}

Already tried running eosiod with --skip-transaction-signatures and --resync-blockchain both didn't change anything

**Comment by ildr3him** [comment]
Running with -s throws a completely new error:

```
thread-0   main.cpp:1008                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"13 St9exception: unknown key\nunknown key: \n    {\"trx\":{\"signatures\":[],\"compression\":\"none\",\"data\":\"5ef3dc580000000000000000010000000000ea305500409e9a2264b89a01000000008093dd7400000000a8ed32327c000000008093dd74000000000020484501000000000100022d50a9c51096ebe474cd771a3d2eb51d86e5759bf67c21662887e5fe33557d5b01000100000000010003f271d060d2073d6430daa6527952046e829c8be778d692293c2ac17be6d9e3e901000100000001000000008093dd7400000000a8ed3232010000\"},\"what\":\"unknown key\"}\n    thread-0  chain_controller.cpp:265 push_transaction"}

```

**Comment by hilbert25** [comment]
so how can I resolute this problem?

**Comment by heifner** [comment]
Unknown key indicates `inita` does not exist. If you are on master branch the only account currently is `eosio`.

**Comment by tqqttq** [comment]
use "./eosioc create account eosio currency public_key_1 public_key_2" is ok
