### ISSUE TITLE
build docker error in macos

### ISSUE THREAD

**Issue by qiushaoxi** [EOSIO/eos#1348]
Step 17/26 : RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install openssl && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 03519636d5d8
Step 18/26 : COPY --from=builder /usr/local/lib/* /usr/local/lib/
 ---> Using cache
 ---> 0f57636207db
Step 19/26 : COPY --from=builder /opt/eosio/bin /opt/eosio/bin
COPY failed: stat /var/lib/docker/overlay2/e0f4ffddfebda73326da19b057b76a3a7b59e4d7db0334f21974cc5b72cd227c/merged/opt/eosio/bin: no such file or directory

macOS 10.13.2 docker 17.12.0-ce

**Comment by ericiles** [comment]
PR #1218 resolves this issue.
