### ISSUE TITLE
DAWN-576 ⁃ Testing Fixtures

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1349]
Right now we have a parameter to the constructor of `tester` that determines whether we install the `test.system` contract as the system contract or not.  We may one day add more bootstrapping to this meaning that the state of the chain when entering a test case will be dirty.   This is only a problem when you need to do testing on _system contracts themselves_ or on producers that are not the first producers. 

We need easier support for multiple types of bootstrapped chains (including non-bootstrapped) as testing fixtures which means getting this out of the constructor parameter.

#### Idea 1 subclasses

make 2 types `tester` and `base_tester` where `base_tester` is === current `tester` (without a parameter for the constructor or the `push_genesis_block` method) and new `tester` is a thin child class that calls `push_genesis_block` in its constructor all the time (and implements that method).   That way we can have both available as fixtures for test cases.

#### Idea 2 templated composition

 we can have 1 class and a templated `push_genesis_block` functor then have `using tester = tester_impl<test_genesis_block>;` and `using base_tester = tester_imp<no_genesis_block>;` or something along that lines.

#### Idea 3 Dealer calls

The reality is the implementation doesn't really matter... so, solve this as best as you see fit where "you" is the person that eventually does this task and if "you" is "@wanderingbort" then "you" will probably do one of the two above 😄 

This is related to #1344

**Comment by heifner** [comment]
Merged.
