### ISSUE TITLE
DAWN-589 ⁃ Support new WAST standard

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1355]
## The problem

WebAssembly/spec#599 changes the way wast is printed out and we no longer accept properly formed output from `s2wasm` as a result.  This may be fixed in the WAVM upstream AndrewScheidecker/WAVM or it may not be.  If it is, we should come up to `master` in that repository.

**Comment by spoonincode** [comment]
Not fixed upstream; baked my own

**Comment by coreylederer** [comment]
Matt indicted this is complete.
