### ISSUE TITLE
How to include mongodb-plugin - or I just need to make eos-web-wallet work? (stable build)

### ISSUE THREAD

**Issue by nsgaga** [EOSIO/eos#1360]
Hi,
First, I'm running all this on the pre-Feb build, few weeks back, which is building and running fine (local testnet). I'm on Ubuntu (I have couple setups, 16 and 17, all local testnets, all that works fine, I'm running Eos/eosiod/eosioc, contracts for weeks now and all running fine)  
  
Short story, **I want to build and run eos-web-wallet**. For that to work I need to run Eosiod 
with db/mongodb plugin enabled.  

I've managed to build the Eos with that cmake flag (DBUILD_MONGO_DB_PLUGIN=true within build.sh under cmake).
That compiled eventually, it builds mongodb plugin lib and all (I have managed mongo-c, mongo-cxx driver etc., so all that went fine, so it seems).  

**However** when ran (eosiod) it shows:
`std::exception::what: unable to find plugin: eosio::mongo_db_plugin
`  

I've tried putting that lib/.o under the install/lib where all plugins are - but there seems to be more than that.  

I know mongodb may be phased out, but I just need some GUI wallet to run and customize.  
What is the way to do it?  
I'd appreciate any pointers, thanks.  
(I did put the same / similar question on the Telegram with no response it seems)

>>> Hi there, I'd need some pointers running eos-web-wallet on a local testnet. 
I merely want some test GUI for the contracts (and to customize it slightly). 
Is it possible, recommended to run that locally at all? Or just on public testnet
I've set it up, API service too (on :9000 and :3000), but my API service doesn't show anything on the /v1/auth/request-api-key endpoint.
I didn't set the mongodb (or db_plugin), hoping just API may work - is that the only issue here.
So as I see it:
compiling with DBUILD_MONGO_DB_PLUGIN=true (and setting up mongodb with all the libs manually),
adding db_plugin
...will that work, all I need.
Are there other wallets more recommended? This one looked fine for my needs, just that it works.
Any help is appreciated, thank you guys

**Comment by jordigoyanes** [comment]
I recently pulled and built from master and enabled the plugin eosio::mongo_db_plugin, it works.

**Comment by nsgaga** [comment]
@jordigoyanes thanks, my code is based on January/Feb build, good to hear and thanks for sharing!

**Comment by jordigoyanes** [comment]
Please close the issue :)
