### ISSUE TITLE
Faucet account establishes a account 

### ISSUE THREAD

**Issue by CooperLee123** [EOSIO/eos#1373]
./eosc create account test1234 cooper1234 EOS8V2LN3iSjvhqJqpjmz6Khi1C5rhUXt3Gs7RsbaCGeigfaP4VyK EOS6esMYR7R8f9iFi1DvdUcMW5psSfiTtkWndXyzVHxP27YRpXWDA
{
  "transaction_id": "513672c69f906f28789fc50c5379a4e0c8cd44b4d8c657a13e96ef3b27d27122",
  "processed": {
    "ref_block_num": 56428,
    "ref_block_prefix": 4166546178,
    "expiration": "2018-02-13T14:24:20",
    "scope": [
      "eos",
      "test1234"
is ok ,but
./eosc get account cooper1234
1481091ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"unknown key"}
question is that the faucet account test1234 establishes the cooper1234, it shows that is ok ,but why the "./eosc get account cooper1234 " shows wrong?

**Comment by yao23** [comment]
having issue when create account for sample "currency" contract:
```

./eosioc create account inita currency public_key_1 public_key_2
```
1655152ms thread-0   main.cpp:981                  main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","error":{"code":13,"name":"St9exception","message":"unknown key","details":"unknown key: ","stack_trace":[{"level":"warn","file":"chain_controller.cpp","line":1032,"method":"get_permission","hostname":"","thread_name":"thread-0","timestamp":"2018-03-01T18:27:35.150"}]}}

Request Path: localhost:8888/v1/chain/get_required_keys, Request Post Data: {"transaction":{"expiration":"2017-03-30T12:00:30","region":0,"ref_block_num":0,"ref_block_prefix":0,"packed_bandwidth_words":0,"context_free_cpu_bandwidth":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"inita","permission":"active"}],"data":"000000000093.....010000"}]},"available_keys":[]}


results when run ./eosioc get account currency:
```
{
  "account_name": "currency",
  "permissions": []
}
```
any solution?

**Comment by jgiszczak** [comment]
Master branch has no `inita` account on startup.  All instructions referring to `inita` apply only to the dawn-2.x branch and its tags.

Please use Telegram for tech support issues.  Github is for defects in code.

**Comment by yao23** [comment]
restart eosiod, open and unlock default wallet, then tried with root account `eosio` instead of inita and managed to create account successfully, thanks @jgiszczak
