### ISSUE TITLE
"sudo make install" has no make target  (ubuntu, dawn-2.x)

### ISSUE THREAD

**Issue by expaand** [EOSIO/eos#1376]
Not sure this is a documentation error or not, but in the README it says to run "sudo make install" after build in the top level eos directory. Doing this obtains the following:
`make: *** No rule to make target 'install'.  Stop.`

**Comment by IcculusC** [comment]
try `make install` it in `/build`

**Comment by rommzestz** [comment]
you can move to right folder and try again, or check correctly install

**Comment by yao23** [comment]
It works for me to `make install` in `build` directory
