### ISSUE TITLE
failed to compile on Fedora 27

### ISSUE THREAD

**Issue by PizzicatoWolf** [EOSIO/eos#1377]
I managed to compile binaryen and while the paths are indeed correct, I am still stuck. 

```
$ cmake -DBINARYEN_BIN=~/binaryen/bin -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib ..
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:69 (FIND_PACKAGE)


-- Configuring Eos on Linux
CMake Error at CMakeLists.txt:175 (message):
  No WASM compiler cound be found
```

**Comment by pacificcode** [comment]
Assuming you installed BOOST in your home directory
Try this.

echo "export BOOST_ROOT=~/boost_1_66_0” > .bash_profile

You will also need to follow the instructions on installing LLVM with WASM 
Support to complete the EOSIO installation.

**Comment by PizzicatoWolf** [comment]
I installed the one which I think is the right one through dnf. Clearly that's the wrong one then since I added the code you mentioned above (though it's ' not ") and it still printed the same error. Any documentation or further links to installing would be appreciated.

**Comment by pacificcode** [comment]
DNF would cause an issue when compiling  dependencies manually.
You can find full documentation for installation on Ubuntu or MacOS Darwin here:

https://github.com/EOSIO/eos/blob/master/README.md

We will have fully automated installation support for Fedora coming very soon.

**Comment by PizzicatoWolf** [comment]
I will have to wait for Fedora support before continuing then.
