### ISSUE TITLE
single-node testnet - Not producing block because it isn't my turn, its eosio

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#1378]
Running Dawn 2 and latest master
Log is showing

```
1046000ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
1046500ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
1047000ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio
1047500ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because it isn't my turn, its eosio


```

**Comment by NewETown** [comment]
Also seeing this as of a fresh pull/build this morning.

**Comment by AnsenYu** [comment]
see this: https://steemit.com/eos/@tokenika/installing-and-running-eos-on-windows

> At the time of my writing the master branch was in heavy development and should not be used for experimentation. Changing the branch with
>Git checkout dawn-2.x

**Comment by NewETown** [comment]
@AnsenYu that quote is very relevant in any non-release environment but it doesn't change that the master branch was working a few days ago. We're just here reporting the bug :)

**Comment by stephenie** [comment]
the same issue i met today .git checkout dawn-2.x but not find /eosio_build.sh. somebody else can help?

**Comment by NewETown** [comment]
@stephenie I believe 2.x still uses build.sh rather than eosio_build.sh

**Comment by bitcoiners** [comment]
getting same error on latest master pull.

**Comment by Vanderwald** [comment]
Same error as of today.

**Comment by bitcoiners** [comment]
Same error as of latest git pull today.

**Comment by geninsin** [comment]
In case anybody needs a "workaround",
add `producer-name = eosio` to the config.ini

**Comment by bitcoiners** [comment]
adding producer-name = eosio helped. Now this producer is the only one producing blocks.

**Comment by hellodudu** [comment]
same problem today.
tried changing to dawn-2.x.

**Comment by shuke0327** [comment]
thanks, @geninsin . it works for me.

and also, for executing the example smart contract described in the eos readme.md, one should use the account 'eosio', instead of 'inita', as the creator, for example:

you should use:
```
./eosioc create account eosio currency PUBLIC_KEY_1 PUBLIC_KEY_2

```

NOT the example code in EOS docs:

```
./eosioc create account inita currency PUBLIC_KEY_1 PUBLIC_KEY_2
```

**Comment by blockChainB** [comment]
add producer-name = eosio to the config.ini

  it works

**Comment by jordigoyanes** [comment]
After adding producer-name = eosio to the config.ini, I get this error:

`3376001ms thread-0   producer_plugin.cpp:250       block_production_loo ] Not producing block because I don't have the private key for EOS1111111111111111111111111111111114T1Anm`

how to fix this?

**Comment by jordigoyanes** [comment]
I fixed this building master all over again. I added producer-name = eosio and it works now.
