### ISSUE TITLE
DAWN-608 ⁃ add backward compatibility for successful rollout

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1381]
The synchronization of nodes changed a bit with respect to the fetching of blocks since the last irreversible block. This patch only affects a newer eosd catching up to an older one and not vice-versa since there won't ever be the need for an older node to catch up to a newer one. 

I'm also including some related odds and ends, a change to the tn_up.sh helper script to make it wait for a replay to complete before moving on. 

Finally, I am including a fix to a log message in the chain controller.

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

on second thought, community members may want to connect older local nodes to the upgraded testnet. Worst case we have to require a local upgrade to reconnect.

**Comment by pmesnier** [comment]
in fac my rebuilt  DAWN-2018-01-05 node syncs just fine from new test node.

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

This was only relevant during the roll out on testnet 1. Since that's done, this issue is done too.
