### ISSUE TITLE
DAWN-609 ⁃ Block Malleability Issue - Packed Transaction Size

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1386]
as a result of #1258 the block structure includes a vector of `packed_transaction` s.  The id's of these transactions were committed to in the headers, but the compression mode/details was _not_  

this becomes a malleability issue when a malicious actor creates a block with different compression mode/details because we are using that packed size to calculate resource usages.  This was meant to incentivize users to pack large transactions because they would be cheaper. 

The solution is to add a "commitment" to the billable size in the transaction itself.  Producers will validate that the on-wire transaction from the user were actually packed to that size. Then just include the unpacked transaction in the block.

This will relate to a future issue as well.  I will update that when I create this issue.

**Comment by andriantolie** [comment]
@wanderingbort is this issue still relevant?
