### ISSUE TITLE
No WASM compiler cound be found

### ISSUE THREAD

**Issue by greed4040** [EOSIO/eos#1393]
I'm trying to install EOS.IO by running `./eosio_build.sh` which is automated install. It fails at the very end when compiler says it has finished building everything.
Manual package installation described at _Building from source code_ section of  https://github.com/EOSIO/eos doesn't help either.

```
...
--   iostreams
-- Configuring Eos on Linux
CMake Error at CMakeLists.txt:175 (message):
  No WASM compiler cound be found


-- Configuring incomplete, errors occurred!
See also "/root/eos/build/CMakeFiles/CMakeOutput.log".
See also "/root/eos/build/CMakeFiles/CMakeError.log".

        >>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.
```

However it (WASM) had been sucessfuly compiled without any errors.

```
# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/root/binaryen/bin
# more /root/.bash_profile
export BINARYEN_ROOT=~/binaryen
export LLVM_DIR=~/wasm-compiler/lib/cmake/llvm
export WASM_LLVM_CONFIG=~/wasm-compiler/llvm/bin/llvm-config
export DBINARYEN_BIN=~/binaryen/bin
```
Is there a way I can check if WASM has been properly compiled and `./eosio_build.sh` actualy sees WASM?

**Comment by 4575759ww** [comment]
I met the same problem, have you fix it ?
