### ISSUE TITLE
Getting error while running ./eosd command

### ISSUE THREAD

**Issue by rupaliathashcode** [EOSIO/eos#1398]
i am getting error while running ./eosd command.

![eoserror](https://user-images.githubusercontent.com/36531568/36300644-1cb29ca6-1328-11e8-87f6-79b51abc94a7.PNG)
![eos2](https://user-images.githubusercontent.com/36531568/36300718-496dbc6c-1328-11e8-95e0-6cc13ae15d56.PNG)

**Comment by ShellRedia** [comment]
Well, I have the same problem. If anybody has a solution, notice me plz. : )
