### ISSUE TITLE
API Theory

### ISSUE THREAD

**Issue by nathanhourt** [EOSIO/eos#14]
Implement new API machinery. Progress for this has already begun (ref #12) but there's a lot of improvement to be done.

There are three plugin types involved in API exposure:
- The plugin that defines the APIs and provides `fc::api` handles for them (i.e. chain_plugin)
- A plugin to configure exposure and handle API permissions (i.e. chain_api_plugin)
- Plugins that expose APIs to the outside world (i.e. http_plugin)

For example, chain_plugin exposes a RO and RW APIs. They are exposed as publicly-accessible `fc::api` objects. chain_api_plugin gathers up these APIs and wires them up with http_plugin. chain_api_plugin implements any necessary permissions/authentication mechanisms, so chain_plugin simply implements the API without caring about permissions, chain_api_plugin implements the permissions and determines which APIs get exposed where, and API exposure plugins like http_plugin make the API accessible to the outside world without concerning themselves with permissions.

**Comment by bytemaster** [comment]
All APIs need to be documented throughly via doxygen in a manner that is easily accessible:

https://eosio.github.io/eos/group__eosiorpc.html

**Comment by heifner** [comment]
This issue has been complete for a long time. Although documentation could always be improved.
