### ISSUE TITLE
Documentation for Boost install wrong

### ISSUE THREAD

**Issue by rjg123456789** [EOSIO/eos#1404]
Not all 1.64 changed to 1.66

Install Boost 1.66:

cd ~
wget -c 'https://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_66_0.tar.bz2/download' -O boost_1.64.0.tar.bz2
tar xjf boost_1.66.0.tar.bz2

**Comment by heifner** [comment]
readme.md has been fixed. Thanks.
