### ISSUE TITLE
DAWN-615 ⁃ clean up intrinsic APIs that are pure functional

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1406]
Right now we have several purely functional APIs that are derived from `context_aware_api` which is wasted efforts when the API does not access anything on the `apply_context` or `wasm_context` we should create a thinner API for those and route any convenience API (like the crypto api) through that.

**Comment by andriantolie** [comment]
@wanderingbort is this already done?

**Comment by brianjohnson5972** [comment]
@wanderingbort There is a little waste, but it is just passing the context reference, right?  I would guess if we have not made this change by now that the negatives of making changes far outweigh the slight benefits.  Do you agree?

**Comment by brianjohnson5972** [comment]
The minor improvement is not worth the potential problems that refactoring this important interface could cause.  Closing.
