### ISSUE TITLE
./build.sh file is missing

### ISSUE THREAD

**Issue by rupaliathashcode** [EOSIO/eos#1411]
After cloning EOS repository. I move to eos folder and enter ./build.sh ubuntu command it display no such file or directory then i checked the list there is no ./build.sh file. how it is possible?. how can i get this file?. please reply.

Thanks in advance

**Comment by eosny** [comment]
I believe it moved to eosio_build.sh

**Comment by rupaliathashcode** [comment]
but i tried this command like ./eosio_build.sh ubuntu but does not work

**Comment by rupaliathashcode** [comment]
then how to run build command

**Comment by eosny** [comment]
I just ran:
git clone https://github.com/eosio/eos --recursive
cd eos
./eosio_build.sh ubuntu full

and got:
<a bunch of output>
ake[1]: Leaving directory '/home/deck/master/eos/build'
/usr/bin/cmake -E cmake_progress_start /home/deck/master/eos/build/CMakeFiles 0

        >>>>>>>>>>>>>>>>>>>> EOSIO has been successfully installed.

**Comment by ResponsiveWebApps** [comment]
so i tried
./build.sh

then
sudo make install

then got
make: *** No rule to make target `install'.  Stop.

what do i do now?

**Comment by DLzer** [comment]
Have you tried `./eosio_build.sh` ?

And by `sudo make install` are you saying that that you have already received the prompt 'EOSIO has been sucesfully installed?

**Comment by jchung00** [comment]
Did you do cd build ?

**Comment by coreycottrell** [comment]
./eosio_build.sh gives no such file or directory

**Comment by matthewdarwin** [comment]
./scripts/eosio_build.sh

**Comment by coreycottrell** [comment]
Expletive deleted!

Thanks man!!

**Comment by jemprince** [comment]
In my case it was the azure git repository converting lineendings from unix to windows
fixed with *.sh eol=lf in .gitattributes
