### ISSUE TITLE
CLI error when pushing actions to the tic.tac.toe contract

### ISSUE THREAD

**Issue by sjkelleyjr** [EOSIO/eos#1414]
I'm following the steps found in the [tic-tac-toe tutorial](https://github.com/EOSIO/eos/wiki/Tutorials#4-tic-tac-toe).  I've successfully compiled and deployed the contract, however when I try pushing any actions to the contract via the instructions given:

`./eosioc push message tic.tac.toe create '{"challenger":"inita", "host":"initb"}' -S initb -S tic.tac.toe -p initb@active`

I get the following output:

> ERROR: RequiredError: Subcommand required
> Create various items, on and off the blockchain
> Usage: ./eosioc create SUBCOMMAND
> 
> Subcommands:
>   key                         Create a new keypair and print the public and private keys
>   account                     Create a new account on the blockchain
>   producer                    Create a new producer on the blockchain

Any ideas?

**Comment by andriantolie** [comment]
The above command is already obsolete since the user doesn't need to specify the scope explicitly again. Please try with the latest code. If you encounter a similar problem with the latest code, please open a new issue. I'm closing this issue. Thanks!
