### ISSUE TITLE
EOS problems with the wallet

### ISSUE THREAD

**Issue by gruvchik** [EOSIO/eos#1418]
I transferred the coin - successfully !
TxHash: 0xe1665457d9df6d6b0b61a51156be227e5c2af435b4c5c4df0a0a633368a3f249
but credited to my wallet denied! and that's what they wrote back
Entering coins will be available after updating the source code of the wallet. Unfortunately, developers do not hurry to send updates

Therefore, in order to avoid losing users' funds, the network is not available.
If you have updated coin sources, send it to us and we will promptly fix the problem on the coin.
help me

**Comment by heifner** [comment]
Please use telegram for support.
