### ISSUE TITLE
[PROPOSAL] Horizontal scalability/Sharding

### ISSUE THREAD

**Issue by toonsevrin** [EOSIO/eos#142]
Though this topic is very vaguely touched in the whitepaper under 'Partial Evaluation of Blockchain State', eos should be designed to shard.

Here is the current progress on sharding within ethereum:
Ethereum has been writing some utils here: https://github.com/ethereum/sharding and there's documentation here: https://github.com/ethereum/wiki/wiki/Sharding-FAQ
Here's a proposal of how to shard ethereum: https://github.com/ethereum/EIPs/issues/53

We should start researching and writing documentation on possible sharding approaches for EOS.

**Comment by miohtama** [comment]
Today we can say, with hindsight, see that horizontal scalability has become the bottleneck for Ethereum. Also we can see that injecting sharding afterwards is not that trivial:

https://ethresear.ch/t/future-compatibility-for-sharding/386

Maybe giving this another thought, before it gets too late for EOS too?

**Comment by heifner** [comment]
Thanks for the proposal.
