### ISSUE TITLE
Contributing to the Wiki

### ISSUE THREAD

**Issue by sjkelleyjr** [EOSIO/eos#1420]
I've noticed a few small inconsistencies with the wiki and the code (namely the capitalization of the Move struct, as well as the incorrect name for the movement variable in the move struct both in the tic_tac_toe tutorial), I'd like to help by proposing a few small changes, what's the best way to go about this?

I'm also posting this in order to streamline the process for proposing changes to the wiki in the future so it doesn't end up as an issue instead, as I've seen a few documentation related issues coming up (https://github.com/EOSIO/eos/issues?utf8=%E2%9C%93&q=wiki)

**Comment by andriantolie** [comment]
The mentioned tic_tac_toe contract guide has moved to http://developers.eos.io/. You can make an account and then you can submit an edit suggestion, using the platform. Thanks for the contribution!
