### ISSUE TITLE
Error publishing (deploying) a contract to an account on public testnet. Why?

### ISSUE THREAD

**Issue by swdevMPaul** [EOSIO/eos#1425]
Hi,

I have launched a local node connected to the public testnet operated by block.one using the script:

./start_npnode.sh

When I command to deploy smart contract by:

root@paulm-Dev:/home/paulm/EOS/eos/build/contracts/testcontract1# eosc set contract ga testcontract1.wast testcontract1.abi

I get:

Reading WAST...
Assembling WASM...
Publishing contract...
1814446ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 401
: {"code":401,"message":"UnAuthorized","details":"signatures do not satisfy declared authorizations (3030002)\nTransaction declares authority '{\"account\":\"ga\",\"permission\":\"active\"}', but does not have signatures for it.\n"}

Why such error ? What is wrong and how to fix it ?

Kind Regards.

**Comment by andriantolie** [comment]
Ensure you have the private key of ga in your wallet
