### ISSUE TITLE
Getting(checking) account info after account created with faucet on Public Testnet.

### ISSUE THREAD

**Issue by swdevMPaul** [EOSIO/eos#1431]
Hi,

Does anyone know why after I have 

_Dear ,

Thank you for signing up for a developer account on the EOS.IO Testnet. Your account named

  swdevmpaul5

has been created and given an initial supply of test EOS tokens via our faucet facility._ 

I created wallet, imported keys, run the ./start_npnode.sh

And when I run:

root@paulm-Dev:/home/paulm/EOS/eos/build/contracts# eosc get account ga
{
  "account_name": "ga",
  "eos_balance": "100000000.0000 EOS",
  "staked_balance": "0.0000 EOS",
  "unstaking_balance": "0.0000 EOS",
  "last_unstaking_time": "1969-12-31T23:59:59",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS5cujNHGMYZZ2tgByyNEUaoPLFhZVmGXbZc9BLJeQkKZFqGYEiQ",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS5cujNHGMYZZ2tgByyNEUaoPLFhZVmGXbZc9BLJeQkKZFqGYEiQ",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}
root@paulm-Dev:/home/paulm/EOS/eos/build/contracts# eosc get code ga
code hash: 0000000000000000000000000000000000000000000000000000000000000000
root@paulm-Dev:/home/paulm/EOS/eos/build/contracts# eosc get code swdevmpaul5
Unknown accounts:
  - swdevmpaul5

Please check the account names and try again!

eosc get account swdevmpaul5

I get:

> 1586382ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
> status_code == 200: Error code 500
> : {"code":500,"message":"Internal Service Error","details":"unknown key"}
> 
> 

Why such error appears and how to fix it ?

Kind Regards.

**Comment by andriantolie** [comment]
The public testnet is not available anymore. I'm closing this issue as it's obsolete
