### ISSUE TITLE
How many smart contracts may be deployed(published) to one account ?

### ISSUE THREAD

**Issue by swdevMPaul** [EOSIO/eos#1432]
Hi,

1)
How many smart contracts may be deployed(published) to one account on local testnet ?

2)
How many smart contracts may be deployed(published) to one account on public testnet ?

Kind Regards.

**Comment by learnforpractice** [comment]
Hello there, one account one contract, as far as I know.

**Comment by swdevMPaul** [comment]
Thank you for your response learnforpractice. 

And I one needs to change(replace) a contract in an account, how to do so ?

**Comment by heifner** [comment]
Just set code again. Please use telegram for support.

**Comment by swdevMPaul** [comment]
What do you mean by set code again ? Do you mean to redeploy using eosc set contract ? Will it replace existing contract ?

**Comment by learnforpractice** [comment]
Yes, you are right, try it.
