### ISSUE TITLE
DAWN-618 ⁃ State Delta API

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1433]
# State Deltas

Many indexers will want to track changes certain rows in the chain database.  Currently, we emit information about actions etc in the transaction/block traces available to plugins but we do _not_ emit anything other than serial numbers for the changes to the chain database.  This means that indexers that want information about these state deltas must recreate them by locally reapplying the action logic.  Ideally, since any full node would have this information readily available the trace data would include a very simple set of data to facilitate this use case.

### Add transaction level state deltas
 - [ ] For each `code` `scope` `table` (as a tree hierarchy) create safe access to the previous and current value of any updated, created, or deleted row.
    * Created rows can omit/null the previous value
    * deleted rows can omit/null the current value
    * metadata updates should also be represented (such as changes in the bill-to-account)

 - [ ] Add support for ABI serializer, to encode/decode the state deltas present in the transaction_traces when going to/from variants

### Implementation notes

a lot of this data already exists in chainbase as part of the undo information.  If that data is stable for the lifetime of the transaction_trace object, these may be able to be `const` references to that data.  If that is the case, care should be taken to make sure the JSONification of the data structure properly explodes and "pretty prints" the row data when ABI information is present. 

## API Access

- [ ] The Mongo DB plugin should be extended to show state diffs per TX and per block

**Comment by brianjohnson5972** [comment]
This feature is being handled by this more current issue: #5789
