### ISSUE TITLE
DAWN-619 ⁃ Ricardian Contract Support for ABI Generator

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1435]
"soon" the standard ABI will allow for an optional [Ricardian Contract](https://en.wikipedia.org/wiki/Ricardian_contract) per action definition.  The ABI generator needs to be extended to support this in a convenient way.

## Suggested Implementation

using a tag in the vein of `@ref` in the ABI generator comments spec that can point to a file.  These files should be text files with the `.rc` extension which contain the markdown ricardian contract (or whatever format becomes the standard ABI format).

**Comment by brianjohnson5972** [comment]
ABI generator is no longer in this repo, OBE
