### ISSUE TITLE
DAWN-626 ⁃ System contract: voting

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1455]
1. producers should be able to vote on system parameters.
2. system contract should change set of active producers, if top 21 producers have changed

**Comment by taokayan** [comment]
Test suite "eosio_system_tests" has passed with:
    25 test cases out of 25 passed
    649 assertions out of 649 passed

    Test case "eosio_system_tests/stake_unstake" has passed with:
      25 assertions out of 25 passed

    Test case "eosio_system_tests/fail_without_auth" has passed with:
      4 assertions out of 4 passed

    Test case "eosio_system_tests/stake_negative" has passed with:
      7 assertions out of 7 passed

    Test case "eosio_system_tests/unstake_negative" has passed with:
      11 assertions out of 11 passed

    Test case "eosio_system_tests/unstake_more_than_at_stake" has passed with:
      17 assertions out of 17 passed

    Test case "eosio_system_tests/delegate_to_another_user" has passed with:
      39 assertions out of 39 passed

    Test case "eosio_system_tests/stake_unstake_separate" has passed with:
      45 assertions out of 45 passed

    Test case "eosio_system_tests/adding_stake_partial_unstake" has passed with:
      36 assertions out of 36 passed

    Test case "eosio_system_tests/producer_register_unregister" has passed with:
      27 assertions out of 27 passed

    Test case "eosio_system_tests/vote_for_producer" has passed with:
      52 assertions out of 52 passed

    Test case "eosio_system_tests/unregistered_producer_voting" has passed with:
      14 assertions out of 14 passed

    Test case "eosio_system_tests/more_than_30_producer_voting" has passed with:
      8 assertions out of 8 passed

    Test case "eosio_system_tests/vote_same_producer_30_times" has passed with:
      11 assertions out of 11 passed

    Test case "eosio_system_tests/producer_keep_votes" has passed with:
      29 assertions out of 29 passed

    Test case "eosio_system_tests/vote_for_two_producers" has passed with:
      22 assertions out of 22 passed

    Test case "eosio_system_tests/proxy_register_unregister_keeps_stake" has passed with:
      36 assertions out of 36 passed

    Test case "eosio_system_tests/proxy_stake_unstake_keeps_proxy_flag" has passed with:
      27 assertions out of 27 passed

    Test case "eosio_system_tests/proxy_actions_affect_producers" has passed with:
      47 assertions out of 47 passed

    Test case "eosio_system_tests/producer_pay" has passed with:
      20 assertions out of 20 passed

    Test case "eosio_system_tests/voters_actions_affect_proxy_and_producers" has passed with:
      66 assertions out of 66 passed

    Test case "eosio_system_tests/vote_both_proxy_and_producers" has passed with:
      12 assertions out of 12 passed

    Test case "eosio_system_tests/select_invalid_proxy" has passed with:
      6 assertions out of 6 passed

    Test case "eosio_system_tests/double_register_unregister_proxy_keeps_votes" has passed with:
      29 assertions out of 29 passed

    Test case "eosio_system_tests/proxy_cannot_use_another_proxy" has passed with:
      15 assertions out of 15 passed

    Test case "eosio_system_tests/elect_producers_and_parameters" has passed with:
      44 assertions out of 44 passed
