### ISSUE TITLE
can't find branch  DAWN-2018-02-14

### ISSUE THREAD

**Issue by stephenie** [EOSIO/eos#1460]
i want to git checkout DAWN-2018-02-14,but can't find this branch.I use dawn-2.x,but can not find eosio_build.sh

**Comment by watonyweng** [comment]
@stephenie Please you can browse [DAWN-2018-02-14](https://github.com/EOSIO/eos/tree/DAWN-2018-02-14)，and this is a tag for [dawn-2.x](https://github.com/EOSIO/eos/tree/dawn-2.x) branch.

**Comment by heifner** [comment]
On dawn 2.x branches the build script is `./build.sh darwin` or `./build.sh ubuntu`
