### ISSUE TITLE
sample contract fails

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#1461]
Following getting started instructions I get an error:
this is on dawn-2.x
```
:~/eos/build/programs/eosc# ./eosc create account inita currency EOS7DDzzuNkkrzGgYzQ7Yd8p1Y4ubPcUdbmVN5YL59bHkCBQaGxyN EOS7NgaFxU9CyiZR1vE6SUvft5Vd2xNZ51zD9Ggwsb1N9RvJPW86W
387995ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 401
: {"code":401,"message":"UnAuthorized","details":"signatures do not satisfy declared authorizations (3030002)\nTransaction declares authority '{\"account\":\"inita\",\"permission\":\"active\"}', but does not have signatures for it.\n"}



~/eos/build/programs/eosc# ./eosc wallet keys
[[
    "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
    "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
  ]
]
```

**Comment by pokerchain** [comment]
I met same problem, any one can help ?

**Comment by pokerchain** [comment]
Please create with account eosio, and must create wallet and import private key.

**Comment by AlanChen04** [comment]
@pokerchain Hello, 

`./eosc create account inita currency EOS7DDzzuNkkrzGgYzQ7Yd8p1Y4ubPcUdbmVN5YL59bHkCBQaGxyN EOS7NgaFxU9CyiZR1vE6SUvft5Vd2xNZ51zD9Ggwsb1N9RvJPW86W`

**inita** is the account authorizing the creation of the currency account.

Are you talking about an authorization account? Excuse me, is the account created on eos website?What is the link address?

Thank you.

**Comment by AlanChen04** [comment]
@bitcoiners I success, and look this #1726 , and go to `http://t1wallet.eos.io` to create an authorized account.
