### ISSUE TITLE
Openssl path in build.sh seems to be wrong.

### ISSUE THREAD

**Issue by gokulnath** [EOSIO/eos#1462]
Branch: dawn-2.x
OS: Ubuntu 17.10

In the build.sh openssl paths are set as below
```
OPENSSL_ROOT_DIR=/usr/local/opt/openssl
OPENSSL_LIBRARIES=/usr/local/opt/openssl/lib
```

These path's are non-existent in my system, any ideas?

Also, both of these are exported in scripts/install_dependencies.sh file, and are unused in that script.

**Comment by heifner** [comment]
Build script has been massively redone since this issue was created.
