### ISSUE TITLE
Implement tripple i64 key value object

### ISSUE THREAD

**Issue by elmato** [EOSIO/eos#147]
1. Create key64x64x64_value_object, add multindex container with the following indices

- (keya,keyb,keyc,id)
- (keyb,keyc,id)
- (keyc,id)

2. Implement db api functions for every index

- front
- back
- next
- previous
- load
- upper_bound
- lower_bound

3. Implement json-rpc api 
- get_table_rows_i64i64i64_primary
- get_table_rows_i64i64i64_secondary
- get_table_rows_i64i64i64_tertiary

**Comment by bytemaster** [comment]
This issue has been merged so closing it.
