### ISSUE TITLE
./eosio_build.sh not found in DAWN-2018-02-14 branch

### ISSUE THREAD

**Issue by Genysys** [EOSIO/eos#1471]
I have downloaded the `DAWN-2018-02-14` using this command: 

`git clone https://github.com/eosio/eos --recursive`

When I run git `checkout DAWN-2018-02-14`,  I  get the following output on the console:

> warning: unable to rmdir contracts/libc++/upstream: Directory not empty
> warning: unable to rmdir contracts/musl/upstream: Directory not empty
> M	libraries/appbase
> M	libraries/chainbase
> M	programs/snapshot
> Note: checking out 'DAWN-2018-02-14'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at bcb5bf75... Merge pull request #1382 from EOSIO/p2p-rollout-compat-d2x

Running the shell script to build it:

```
Pros-MacBook-Pro:eos Santi$ ./eosio_build.sh
-bash: ./eosio_build.sh: No such file or directory
```

Would appreciate pointers on this

**Comment by borg** [comment]
Build script named build in this commit
./build.sh target build | full

eg to run on mac
```
./build.sh darwin full
```
or without dependencies
```
./build.sh darwin build
```
there are likely other issues and you may want to use a prebuilt docker image
