### ISSUE TITLE
What are the differences between master and dawn-2x branches?

### ISSUE THREAD

**Issue by swdevMPaul** [EOSIO/eos#1472]
Hi,

Can anyone briefly let know(list) what are the key differences between master and dawn-2x eos branches ?

Is dawn-2x more reach in functionality, features ( more code )?

Kind Regards,

Paul.

**Comment by IsraelLaguan** [comment]
README says `master` don't support testnet anymore. So maybe the code to connect to testnet changed, and when i've tried to connect the blocks don't produce. Tried `--genesis-timestamp` but don't work. 

Also there are more than 1000 commits of difference, so a lot must have changed. I also want to know if `git checkout dawn-2x` make `./eosiod` work again, and other features in `dawn-2x`.
