### ISSUE TITLE
How to connect and get working EOS Community telegram group ?

### ISSUE THREAD

**Issue by swdevMPaul** [EOSIO/eos#1475]
Hi,

Would anyone who knows and uses telegram communicating with EOS Community explain how to setup EOS Community telegram on Ubuntu ?

I have tried before, but please see - no progress, can't connect to the EOS community groups on Telegram.
[https://app.box.com/s/ljjbv8lw0iee8pmrjx12hzpkyswo8qi5](url)
Please, this is very important, which version of telegram to install, how to find and connect to the EOS Community group(developers)?

Please explain.

Kind Regards.

**Comment by dali1986** [comment]
Install the latest version of telegram (really doesn't matter) and connect on your smartphone - then you can link a telegram account via a browser (firefox / chrome work fine on ubuntu) at web.telegram.com - The developers chat is here - https://t.me/joinchat/EgOVjkPktgfUS3kt14FStw

This isn't really a question for the EOS GitHub 

Telegram has a bunch of apis if that's your thing - https://core.telegram.org/
