### ISSUE TITLE
Now make new table with few rows ?

### ISSUE THREAD

**Issue by rommzestz** [EOSIO/eos#1476]
Good day!

I new on EOS, maybe you can help my how i can make table "test_table" with few rows as "row1" "row2" "row3"  and put , update , delete , found result for "row1"  ? 
Maybe sample script help my
Thanks you very much!

**Comment by ChristianDunst** [comment]
Hi rommzestz,
For information on how to use tables please have a look at the developers portal:
https://developers.eos.io/eosio-cpp/docs/multi-index-table-tutorial
