### ISSUE TITLE
http rpc problem 

### ISSUE THREAD

**Issue by kimziv** [EOSIO/eos#148]
i test the http rpc for eos

i found a problem, when i call :
 curl  http://localhost:8888/v1/chain/get_block -X POST -d '{"block_num_or_id":0000000445a9f27898383fd7de32835d5d6a978cc14ce40d9f327b5329de796b}'

the result is :

{
    "previous": "00000003cc4920ff315fa051f127d9440d04ddac4db4a2a49847afa325acbbbc",
    "timestamp": "2017-08-09T09:53:21",
    "transaction_merkle_root": "0000000000000000000000000000000000000000000000000000000000000000",
    "producer": "inite",
    "producer_changes": [],
    "producer_signature": "1f57d7d6bce258d395494ba1ed53ade1cb8a22081c46457c6d202c9ecb62bf019d76f716e4f2ef7efcc43cff8dea139462fcfd9c701b1d08e7c0da839cfc694db5",
    "cycles": [],
    "id": "00000004fcf7520182e828b438c7f44c80f07e2cafdc55fa00720c7f629f8ba7",
    "block_num": 4,
    "refBlockPrefix": 3022579842
}

ths  block_num_or_id param is 0000000445a9f27898383fd7de32835d5d6a978cc14ce40d9f327b5329de796b

but the result shows the id is 00000004fcf7520182e828b438c7f44c80f07e2cafdc55fa00720c7f629f8ba7

they are different, is this a bug?

**Comment by blackbeam** [comment]
I believe that `block_num_or_id` must be a string.

**Comment by kimziv** [comment]
I add  quote, the result is also the same to previous.

**Comment by nathanhourt** [comment]
Haha, interesting. It looks up the block ID you provide, and can't find it, so it looks it up as a block number instead. When it parses the ID as a number, it sees 00000004, followed by letters, so it ignores the letters and calls it a 4, and returns block number 4.

Seems like perhaps `boost::lexical_cast` isn't a good choice for the string-to-number conversion...
