### ISSUE TITLE
How EOS get data from outside world

### ISSUE THREAD

**Issue by lakerswq7** [EOSIO/eos#1483]
Some Dapps may have requirement to consume data from outside world
In Ethereum, solidity allow to log a event which can be catched by ethereum software.
Ethereum software will fetch the data through rest api or other way from outside world, and then inject the result back into contract through callback function.

I am just wondering if EOS have a same way to deal with it or use other manner.

Thanks

**Comment by bytemaster** [comment]
Smart contracts can only read data that is part of the transaction or stored in blockchain state. To pass external data into a contract it will need to be sent via an oracle. 


If you have an external application, such as a social media app, it can observe transactions and receive callbacks. You can either register a native plugin or you can poll eosiod.   Transactions can log data via print().

**Comment by arvoelke** [comment]
> If you have an external application, such as a social media app, it can observe transactions and receive callbacks. You can either register a native plugin or ...

How do we "receive callbacks" or "register a native plugin"? I've searched for both of these terms in this repo, the documentation repo, the wiki, Google, [asked eosio.stackexchange](https://eosio.stackexchange.com/questions/418/can-a-smart-contract-communicate-externally), but am struggling to locate the right information. Any links to examples or documentation are much appreciated!

> ... you can poll eosiod. 

To anyone you might have found this in the process of searching for the same question, `eosiod` is now `nodeos`.

**Comment by artjoma** [comment]
I think we should have something like that:
```
//return json
//@abi action-read
uint64_t calc (){
    return accountTbl.getValue() / 2;
}

//return serialized json object
//@abi action-read
config* getConfig(){
    config conf = configTbl.getConfig();
    return &conf;     
}
```
