### ISSUE TITLE
DAWN-637 ⁃ Need to remove the remaining code for lazy table key validation

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1489]
Need to remove the remaining code for lazy table key validation in contract_table_object.hpp (table_id_object::key_type).

ATC:
Run ctest and verify that all tests pass

**Comment by brianjohnson5972** [comment]
Is this being assigned to Andrianto to validate it?

**Comment by andriantolie** [comment]
I'm kinda confused with this ticket. I saw there are 3 PR referring to this ticket, will there any more in the future? Or is it ready for testing? If it's ready for testing, can we set the pipeline to be "In QA/ UAT" and add some ATC here? Thanks

**Comment by andriantolie** [comment]
ATC Passes
