### ISSUE TITLE
Failed with error 10 assert_exception: Assert Exception

### ISSUE THREAD

**Issue by rupaliathashcode** [EOSIO/eos#1494]
I am getting this error

3578973ms thread-0   main.cpp:1125                 main                 ] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error code 404
: {"code":404,"message":"Not Found","details":"Unknown Endpoint"}

    {"c":404,"msg":"{\"code\":404,\"message\":\"Not Found\",\"details\":\"Unknown Endpoint\"}"}
    thread-0  httpc.cpp:113 call

    {"server":"localhost","port":8888,"path":"/v1/chain/get_info","postdata":null}
    thread-0  httpc.cpp:117 call

while running command  "eosc create account inita name EOS8czYN9ExHv............................ EOS5pS7CbMHd5ru......................................."
I already unlock the account and import key in this account.

**Comment by pumatus** [comment]
@zhaokanghuiasd Do you solve this problem?? I also meet this one- -

**Comment by andriantolie** [comment]
You need to have `plugin = eosio::chain_api_plugin` in your `config.ini`
