### ISSUE TITLE
DAWN-645 ⁃ Can a non-producing or standby node be a failover block producer?

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1505]
(this ticket is based on comments and questions from the Block Producers call that Thomas managed on Feb 23, 2018)

See Page 35 on attached PDF. [^Block Producer Candidates Q&A #1 (23-Feb-2018).pdf] 

Can a secondary node be used as a failover node block producer that in the event of a block producer failure?  

Can we update the config.ini on the backup and restart or is there an automatic failover service we could write so the secondary/backup server simply takes over without intervention and is voted in as a block producer?

Could a secondary node be running in parallel, either as a non-producing node that keeps up to date with all blocks and all contracts states in RAM 

Another way of describing a solution:  Could there be a secondary server with the same username on two machines, effectively 2 block producers, one is "nulled" (on standby) until the primary dies.  If we currently start 2 block producers with the same username, it does not work.  How could that work?

There a many people concerned about the block producers and failover.

Eric (from the February 23rd BP call at 19:15 into the video) offered to go into more detail on this if possible.

┆Attachments: <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10147&#x2F;Block+Producer+Candidates+Q%26A+%231+%2823-Feb-2018%29.pdf">Block Producer Candidates Q&amp;A #1 (23-Feb-2018).pdf</a>

**Comment by andriantolie** [comment]
The answers can be found in the attached pdf
