### ISSUE TITLE
How to run EOS in multiple remote hosts?

### ISSUE THREAD

**Issue by haiboumich** [EOSIO/eos#1509]
Basically it works when I follow [Running multi-node local testnet](https://github.com/EOSIO/eos/tree/DAWN-2018-02-14#running-multi-node-local-testnet) to use command "./programs/launcher/launcher -p2 --skip-signature" and there would be two nodes running in my local machine.
But when I tried to do the same thing in another way [Running the launcher application](https://github.com/EOSIO/eos/wiki/Testnet%3A%20Local%20Multinode#running-the-launcher-application), I just typed in "programs/launcher/launcher -p2 -s mesh -o testnet.json" and did some modification like changing the hostname and rearranging the producers under each nodes(like inita~initk for testnet_00 and initl~initu for testnet_01), but when I rerun the command  "programs/launcher/launcher -p2" (btw is this the right way to rerun the launcher supplying the file?), it does not turns out as I expected like the producers are still arranged in the round-robin way, any idea?
After successfully setting up multiple nodes on a host, I would like to try to do EOS multi hosts set up, does anyone have experience on it? I would really appreciate it if anyone can give me some suggestion.

**Comment by IsraelLaguan** [comment]
I'm having same problems here, seems like is the change from DAWN 2.xx to 3.xx, could be that testnet is broken now? If someone can use multi-node please share how or with what branch, please

**Comment by jgiszczak** [comment]
If you want to manually edit launcher-generated config files, first use the `--launch none` option along with the other desired parameters like number of nodes, then edit the resulting config files in the 'staging' directory created by launcher.  To use the existing edited files, use the `--nogen` option.

See `programs/eosio-launcher/eosio-launcher --help` for all available options in Dawn 3, or `programs/launcher/launcher --help` in Dawn 2.  At present the two versions have identical capabilities.
