### ISSUE TITLE
error in getting started instructions

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#1518]
From instructions on https://github.com/EOSIO/eos#gettingstarted

```
For ease of contract development, one further step is required:

sudo make install

```
```
$ sudo make install
make: *** No rule to make target 'install'.  Stop.

```

**Comment by dstoyak** [comment]
I'm getting the same error :/

**Comment by bitcoiners** [comment]
I prefer to stay anonymous!I can verify that I am legitimate owner by logging in to my account which requires 2 way authorization and only legitimate owner can do.05.03.2018, 12:00, "Daniel Stoyak" <notifications@github.com>:I'm getting the same error :/

**Comment by shawinder** [comment]
you need to go inside `~/eos/build` and run the command there.

**Comment by rogerlzp** [comment]
this error just happened under eos/build
