### ISSUE TITLE
creating account fails 

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#1533]
Trying sample currency contract instructions on latest git master running on local single node test-net. 

```
 ./eosioc create account inita currency EOS6UTqYZbBjLfuaabBJaZ53m1pfVo7NWNNPoQxWXZdV29Lzte3AL EOS7J8gwqjyZirFUdbhhYZ8CQgMGBKVSoebpKJP6P9ycVCqHu3Wge 
2538674ms thread-0   main.cpp:941                  main                 ] Failed with error: unknown key (13)
unknown key: 
Request Path: localhost:8888/v1/chain/get_required_keys, Request Post Data: {"transaction":{"expiration":"2018-03-04T03:42:48","region":0,"ref_block_num":16785,"ref_block_prefix":2155080321,"packed_bandwidth_words":0,"context_free_cpu_bandwidth":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"inita","permission":"active"}],"data":"000000000093dd740000001e4d75af460100000000010002d0d68155059f9ba1369170f1d22801ed5e4115c387f61cc39e02283c38e0c3bc010001000000000100033d1401eeca5e065c81cbd38afde8662a351431181a210c43168deeffd3c8580301000100000001000000000093dd7400000000a8ed3232010000"}]},"available_keys":["EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"]}

```

**Comment by kaidiren** [comment]
use eosio instead of inita , have a try

**Comment by ibigbug** [comment]
using eosio worked, does that mean the doc need to be updated?

**Comment by grock999** [comment]
Hello.. switching from 'inita' to 'eosio' just worked for me also!

**Comment by kaidiren** [comment]
https://github.com/EOSIO/eos/blob/master/Docker/config.ini#L95

here you can see that the default producer-name is eosio.

**Comment by kaidiren** [comment]
https://github.com/EOSIO/eos/pull/1648

**Comment by grock999** [comment]
Thanks! Maybe I could have done this myself (?) but I'm new to the github
paradigm.

**Comment by ibigbug** [comment]
@grock999 yes you could though the [Pull Request](https://help.github.com/articles/about-pull-requests/) is for preventing others doing themselves again :D

**Comment by kaidiren** [comment]
hi,  this issue can be closed for https://github.com/EOSIO/eos/pull/1648 has been merged.
