### ISSUE TITLE
(Enhancement) Windows support

### ISSUE THREAD

**Issue by jjxtra** [EOSIO/eos#1535]
Is Windows going to be supported for the June release? I love Linux (and MAC) but also use Windows. There are hundreds of millions of Windows PCs on Earth, and it would be lovely to have EOS compile (or at least have pre-built binaries) for Windows (wallet, etc.).

**Comment by jerryhorak** [comment]
Interested as well given current momentum and need for greater adoption. As much as I love Docker...

**Comment by andriantolie** [comment]
There's currently no plan to support Windows
