### ISSUE TITLE
wrong amount of tokens after issue ( generic_currency.hpp )

### ISSUE THREAD

**Issue by kesar** [EOSIO/eos#1536]
<img width="524" alt="screen shot 2018-03-05 at 02 15 16" src="https://user-images.githubusercontent.com/1288106/36953453-2ac2503e-201b-11e8-910d-9ab283a20cbb.png">

eosioc push action currency issue '{"to":"twitter", "quantity": "1.0000 KSR"}' --permission currency@active

eosioc get currency balance currency twitter

[
  "138119.0404 KSR"
]

➜  twitter eosioc get table currency currency account
{
  "rows": [{
      "currency": 1381190404,
      "balance": 1381190404
    }
  ],
  "more": false
}
➜  twitter eosioc get table currency currency stat   
{
  "rows": [{
      "currency": 1381190404,
      "supply": 1381190404
    }
  ],
  "more": false
}

// code:

    typedef eosio::generic_currency< eosio::token<N(currency),S(4,KSR)> > contract;

**Comment by bytemaster** [comment]
This issue is a result of a change in how balances are stored, there is a fix that Arhag and I worked on that will be checked in later today.

**Comment by bytemaster** [comment]
https://github.com/EOSIO/eos/pull/1526
