### ISSUE TITLE
DAWN-654 ⁃ p2p sync can stall when one of the configured peers is unresponsive

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1542]
When I patched the community testnet it turns out that a couple of the named peers in their network were offline. This caused the synchronizing nodes to get a connection reset which triggers the sync manager class to reevaluate its status. however a bug in the re-evaluator function caused the node to forget where it was in the sync process. Compounding this, a timer that will restart the sync process can get reset by the receipt of unexpected messages such as a time or handshake message.

The solution is to ensure that a connection only triggers a reset in the synchronizer if it was the current source of catch-up blocks. Also the timer on the connection should only be reset when the desired message is received.

**Comment by heifner** [comment]
Moved to RC2 since this can be "fixed" by restarting the stalled node.

**Comment by pmesnier** [comment]
Fix was merged by Dan on March 7, a million years ago at this velocity. Since there is nothing new to review, I am closing this issue.
