### ISSUE TITLE
The ABI for the code on account "exchange" does not specify table "bids"

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#1552]
>Usage: ./eosioc get table [OPTIONS] scope contract table

```bash
./eosioc get table exchange exchange bids
The ABI for the code on account "exchange" does not specify table "bids".

Please check the account and table name, and verify that the account has the expected code using:
  eosioc get code exchange
```
I should have tables called: account, bids, asks

I just deployed a fixed version of exchange.abi: https://github.com/EOSIO/eos/pull/1551/commits/90c0d910eb8e959eebb1500a9a9a6506c7656d69 

Get table does not find any of the 3 tables.

**Comment by jeremi** [comment]
Get table is broken, it is not just for the exchange contract.
I reported it in #1742 and it has been added in the RC1 milestone.
