### ISSUE TITLE
generic_currency doesnt allow tokens without decimals

### ISSUE THREAD

**Issue by kesar** [EOSIO/eos#1554]
You can define a symbol like ``` S(0, GOLD) ``` but you can't query it:

➜  kesar-coin eosioc push action coin issue '{"to":"crowdsale", "quantity": "1000 GOLD"}' --permission coin@active
2117858ms thread-0   main.cpp:866                  operator()           ] Converting argument to binary...
2117914ms thread-0   main.cpp:941                  main                 ] Failed with error: Assert Exception (10)
dot_pos != string::npos: dot missing in asset from string

**Comment by elmato** [comment]
@kesar try using **"1000. GOLD"**. IIRC The dot is mandatory when converting from string

**Comment by jgiszczak** [comment]
Agreed, but closing in favor of #1616 .
