### ISSUE TITLE
Can't find LLVMConfig.cmake

### ISSUE THREAD

**Issue by sirkbitt** [EOSIO/eos#1564]
That issue's solution (https://github.com/EOSIO/eos/issues/43) doesn't work for me.
Here the error message:

CMake Error at libraries/wasm-jit/Source/Runtime/CMakeLists.txt:26 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 4.0) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

I don't understand.
Thanks.

**Comment by sirkbitt** [comment]
Solved. 
Thanks to @hh3755, view issue on this page: https://github.com/EOSIO/eos/issues/99.

**Comment by MNGanesan** [comment]
Hi ,

Am new to LLVM , I follow the LLVM getting started.
Downloaded latest source of LLVM (9.0) and try to build ..but am stuck , as my cmake/llvm installation did not have LLVMconfig.cmake

 could any one throw some light on it ?

**Comment by miraclegray** [comment]
Hi, @MNGanesan. Have you solved the problem? If you do, please share info about that.
