### ISSUE TITLE
why so much  physical memory ...

### ISSUE THREAD

**Issue by lisongjian** [EOSIO/eos#1573]
ARCHITECTURE Linux

	OS name: Ubuntu
	OS Version: 16.04
	CPU speed: 2394
MHz:
MHz:Mhz
	CPU cores: 4
	Physical Memory: 3847 Mgb
	Disk space total: 13G
	Disk space available: 18GG
	Your system must have 8 or more Gigabytes of physical memory installed.
	Exiting now.

**Comment by lisongjian** [comment]
is there any way to run it in other code ? like eth pyethapp

**Comment by dramlee** [comment]
I faced the same problem with you.
My solution is to run eos on public testnet.

**Comment by lisongjian** [comment]
how to do it? just start to learn

**Comment by spoonincode** [comment]
One reason is that we build the clang compiler during the build process. Some of those source files easily cause the compiler to eat over 1GB of RAM during the compilation. A `make -j4` or `make -j8` can easily cause 4GB+ of RAM usage.

**Comment by taty5556666** [comment]
You can try to edit the script in eos/scripts/eosio_build_ubuntu.sh
line 27  ' if ["${MEM_MEG}" -lt 7000] '  --> ' if ["${MEM_MEG}" -lt 4000] ' 
or kill line 30 ' exit 1 '
