### ISSUE TITLE
account name invalid char

### ISSUE THREAD

**Issue by zshchou** [EOSIO/eos#1580]
if account name contain 0,6,7,8,9, then create failure!

example: eosc create inita test106 EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV

2873113ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
to_string() == string(str): name not properly normalized

**Comment by elmato** [comment]
This is a expected behavior.
Valid characters for account names are ".12345abcdefghijklmnopqrstuvwxyz"
