### ISSUE TITLE
./eosd error: Address already in use

### ISSUE THREAD

**Issue by sirkbitt** [EOSIO/eos#1583]
I put here what appears to me after launching eos daemon:

./eosd
2704259ms            chain_plugin.cpp:126          plugin_initialize    ] initializing chain plugin
2704259ms            wasm_interface.cpp:757        get                  ] Runtime::init
2704260ms            producer_plugin.cpp:170       plugin_initialize    ] Public Key: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
2704260ms            wallet_plugin.cpp:34          plugin_initialize    ] initializing wallet plugin
2704260ms            http_plugin.cpp:138           plugin_initialize    ] host: 127.0.0.1 port: 8888 
2704261ms            http_plugin.cpp:141           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
2704261ms            net_plugin.cpp:2521           plugin_initialize    ] Initialize net plugin
2704261ms            net_plugin.cpp:2543           plugin_initialize    ] Setting net_plugin logging level to info
2704261ms            net_plugin.cpp:2571           plugin_initialize    ] host: 0.0.0.0 port: 9876 
2704262ms            net_plugin.cpp:2650           plugin_initialize    ] my node_id is 620c680246bb986be04301d7e5d15cc3f1c6301681ca94e87739648a346d4aff
2704262ms            main.cpp:59                   main                 ] eosd version 009828e9
2704266ms            block_log.cpp:92              open                 ] Opening block log at /Users/Sircs/eos_new/eos/build/programs/eosd/data-dir/blocks/blocks.log
2704268ms            chain_plugin.cpp:250          plugin_startup       ] starting chain in read/write mode
2704269ms            chain_plugin.cpp:255          plugin_startup       ] Blockchain started; head block is #0, genesis timestamp is 2017-03-30T12:00:00
2704269ms            producer_plugin.cpp:181       plugin_startup       ] producer plugin:  plugin_startup() begin
2704269ms            producer_plugin.cpp:186       plugin_startup       ] Launching block production for 21 producers.

*******************************
*                             *
*   ------ NEW CHAIN ------   *
*   -   Welcome to EOS!   -   *
*   -----------------------   *
*                             *
*******************************

Your genesis seems to have an old timestamp
Please consider using the --genesis-timestamp option to give your genesis a recent timestamp

2704269ms            producer_plugin.cpp:196       plugin_startup       ] producer plugin:  plugin_startup() end
2704270ms            http_plugin.cpp:153           plugin_startup       ] start processing http thread
2704270ms            http_plugin.cpp:210           plugin_startup       ] start listening for http requests
2704270ms            http_plugin.cpp:219           plugin_startup       ] http: Underlying Transport Error
2704270ms            wallet_api_plugin.cpp:69      plugin_startup       ] starting wallet_api_plugin
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/create
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/get_public_keys
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/import_key
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/list_keys
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/list_wallets
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/lock
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/lock_all
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/open
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/set_timeout
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/sign_transaction
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/unlock
2704271ms            chain_api_plugin.cpp:60       plugin_startup       ] starting chain_api_plugin
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/abi_bin_to_json
2704271ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/abi_json_to_bin
2704272ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_account
2704272ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_block
2704272ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_code
2704272ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_info
2704272ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_required_keys
2704272ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_table_rows
2704272ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_block
2704272ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_transaction
2704272ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_transactions
2704272ms            main.cpp:65                   main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
std::exception::what: bind: Address already in use

Thanks for any help.

P.S.: public testnet work well; this issue affects only local testnet (of course).

**Comment by kesar** [comment]
I think you had 2 instances running at the same time in the same port

**Comment by rommzestz** [comment]
you can fetch exist runing process - try found ./eosd eosd eosiod  and kill it
