### ISSUE TITLE
Unable to find softfloat library.  mac os

### ISSUE THREAD

**Issue by zhouyasong** [EOSIO/eos#1598]
-- Configuring Eos on OS X
-- Found WASM: /usr/local/wasm/bin/clang  
-- Using WASM clang => /usr/local/wasm/bin/clang
-- Using WASM llc => /usr/local/wasm/bin/llc
-- Using WASM llvm-link => /usr/local/wasm/bin/llvm-link
-- Looking for softfloat library
CMake Error at CMakeModules/softfloat.cmake:4 (message):
  Unable to find softfloat library
Call Stack (most recent call first):
  CMakeLists.txt:197 (include)

-- Configuring incomplete, errors occurred!

when I build eos/build and cmake, the errors occurred!

**Comment by rjg123456789** [comment]
Same error with Ubuntu build.

**Comment by brianjohnson5972** [comment]
Did you use eosio_build.sh?

**Comment by rjg123456789** [comment]
Thanks Brian, after trying that I get:

-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Could NOT find WASM (missing: WASM_CLANG WASM_LLC WASM_LLVM_LINK)
CMake Error at CMakeModules/wasm.cmake:8 (message):
  No WASM compiler cound be found (make sure WASM_ROOT is set)
Call Stack (most recent call first):
  CMakeLists.txt:193 (include)

:(

**Comment by bytemaster** [comment]
```   printf "\n\tChecking for SoftFloat\n"
   if [ ! -d /usr/local/berkeley-softfloat-3 ]; then
      # clone the library
		cd ${TEMP_DIR}
      mkdir softfloat
      cd softfloat
      git clone --depth 1 --single-branch --branch master https://github.com/ucb-bar/berkeley-softfloat-3.git
      cd berkeley-softfloat-3/build/Linux-x86_64-GCC
      make -j${CPU_CORE} SPECIALIZE_TYPE="8086-SSE" SOFTFLOAT_OPS="-DSOFTFLOAT_ROUND_EVEN -DINLINE_LEVEL=5 -DSOFTFLOAT_FAST_DIV32TO16 -DSOFTFLOAT_FAST_DIV64TO32"
      if [ $? -ne 0 ]; then
         printf "\tError compiling softfloat.\n"
         printf "\tExiting now.\n\n"
         exit;
      fi
      # no install target defined for this library
      sudo mkdir -p /usr/local/berkeley-softfloat-3
      sudo cp softfloat.a /usr/local/berkeley-softfloat-3/libsoftfloat.a
      sudo mv ${TEMP_DIR}/softfloat/berkeley-softfloat-3/source/include /usr/local/berkeley-softfloat-3/include
		sudo rm -rf ${TEMP_DIR}/softfloat
	else
		printf "\tsoftfloat found at /usr/local/berkeley-softfloat-3/\n"
   fi
```

**Comment by rjg123456789** [comment]
Thanks I added that into eosio_build.sh just before the build of eosio. Build went through will now start using.

**Comment by Lonenso** [comment]
Same error with ubuntu build, ubuntu 16.04LTS, and I followed documentation, and I got this. how come ?
