### ISSUE TITLE
eosd just stops after some time on WSL

### ISSUE THREAD

**Issue by MrToph** [EOSIO/eos#1613]
Hi,
I'm running `eosd` on `dawn-2` on Windows via Windows Subsystem for Linux Ubuntu installation, and after some time the block production just stops and it becomes unresponsive:

![powershell_2018-03-11_01-06-54](https://user-images.githubusercontent.com/3176721/37248092-b19a8a98-24c8-11e8-82c1-145fcb3d8152.png)

I have to kill it with `Ctrl + C`, and then it takes some minutes to get from the `exit shutdown` message to the `closing database` message.

**Comment by spoonincode** [comment]
Can you attach a debugger and see what the backtrace is when it becomes stuck?

You would do something like
```
lldb ./eosd -- --args --to --eosd
(lldb) run
# when eosd becomes unresponsive, ctrl-c
(lldb) bt
```

Then copy and paste the output from the `bt` command.

**Comment by MrToph** [comment]
It is actually still responsive. I think the problem is with WSL just not showing new messages in the bash after some time. I heard several people have the same problem with WSL

**Comment by w00tcoin** [comment]
I believe this is still a problem, i have experienced a similar issue and when i check the current block, the chain has not advanced but nodeos is active and responsive. did you find  a workaround or is it due to the limitations of the WSL cmd window?
