### ISSUE TITLE
DAWN-668 ⁃ Asset Symbol without "." (precision 0) should be supported

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1616]
Currently attempting to construct an asset::from_string("100 BTC") fails because it doesn't find "."

"100. BTC" should fail as '.' implies at least one digit of precision
"100 BTC" should be precision 0 and should succeed

**Comment by andriantolie** [comment]
ATC: Run tests/chain_tests for currency_tests/test_symbol and ensure everything pass

**Comment by taokayan** [comment]
Test case "currency_tests/test_symbol" has passed with:
      41 assertions out of 41 passed
