### ISSUE TITLE
getting internal server error while deploying contract in eos

### ISSUE THREAD

**Issue by rupaliathashcode** [EOSIO/eos#1620]
![image](https://user-images.githubusercontent.com/36531568/37272526-df2ffbe8-25fc-11e8-9b08-204703dea4f9.png)

**Comment by spoonincode** [comment]
It kind of looks like you're building a contract on master/3.0 (based on the presence of __cxa_atexit) but trying to deploy it on a 2.0 network (based on eosd vs eosiod). Do you think you might have mixed up versions of eos installed?
