### ISSUE TITLE
Docker: `FROM huangminghuang/eos_builder as builder` 

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#1622]
Is huangminghuang/eos_builder still supported?

In this container, I noticed SOFTFLOAT_ROOT was not set .. After I add this manually, I also see when I try to build that libboost_iostreams.a is missing.

**Comment by jcalfee** [comment]
https://github.com/EOSIO/eos/blob/master/Docker/Dockerfile#L76-L77

**Comment by jcalfee** [comment]
I like the idea of having a eos_builder .. I was accomplishing the same thing simply by copy and pasting those lines into my own eosrelease.Dockerfile.

In my container names though, I included the release.  So eos_builder/dawn3 for example..

**Comment by ericiles** [comment]
This has been resolved with PR #1698. The image is available as [eosio/builder.](https://hub.docker.com/r/eosio/builder/)
