### ISSUE TITLE
DAWN-667 ⁃ need hash of constitution reflected in each block and tx

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1626]
The current block structure doesn't have a place to record the "hash of the constitution" that's supposed to be present in each block and each Tx. Yet the presence of that hash is crucial. May need to alter the block structure.

See block structure here:
https://blockone.atlassian.net/wiki/spaces/ID/pages/46759938/Structure+of+a+Block+on+EOSIO

**Comment by thomasbcox** [comment]
This has been replaced by #2925
