### ISSUE TITLE
README.md  🔨🐞

### ISSUE THREAD

**Issue by wuyahuang** [EOSIO/eos#1636]
I'm installing ubuntu for the public testnet. 
I used:
git clone https://github.com/eosio/eos --recursive
git checkout DAWN-2018-02-14
./eosio_build.sh

but eosio_build.sh is no such file or directory.

**./build.sh ubuntu full**  help me out.

**Comment by spoonincode** [comment]
DAWN-2018-02-14 is a tag from the 2.0 branch. Use the build instructions on that branch as the difference from 2.0 to 3.0 was significant.

https://github.com/EOSIO/eos/blob/DAWN-2018-02-14/README.md

**Comment by mhedhliGVIT** [comment]
ReadMe.md on Master should still be updated to reference the DAWN 2.0 README.md, as the instructions reference the ./eosio_build.sh script which is no longer in the EOS root directory after checking out the dawn 2.0 branch.

For MacOS these are the instructions that worked for me.

> git clone https://github.com/eosio/eos --recursive
> git checkout DAWN-2018-02-14
> ~~./eosio_build.sh~~
> ./build.sh darwin full
