### ISSUE TITLE
eosio.system.hpp   -   != vs ==

### ISSUE THREAD

**Issue by joneric** [EOSIO/eos#1643]
Hi @arhag and @bytemaster  

I am curious why line 178 and line 194 both don't use "=="?

https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/eosio.system.hpp#L180

https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/eosio.system.hpp#L196

**Comment by andriantolie** [comment]
The eosio.system.hpp has undergone a lot of change since March that the line that this issue is referring to no longer trackable. I'm going to close this issue, if the similar case happens with the latest code, please open a new issue. Thanks!
