### ISSUE TITLE
DAWN-673 ⁃ Read/write multi_index should require code argument to constructor to be equivalent to the current receiver

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1644]
Calls to `store` in the C DB API do not need a `code` argument because it is assumed to be the current receiver (since the current receiver is not allowed to modify the database tables of other code). However, currently `multi_index` just makes the calls to `store` when it needs to without having ever checked that the `code` supplied to it during construction matches the current receiver. This means that currently a contract developer using `multi_index` with a `code` other than the current receiver (which has a legitimate use case when it is meant to be read-only) is allowed to call methods that modify database tables, but that would modify the tables in their code which is certainly not what was intended.

The correct behavior should be to allow the contract developer to instantiate a `multi_index` as read-only (in which case calls to methods such as `emplace`, `modify`, and `remove` would be compiler-time errors) or to instantiate a `multi_index` as read/write as it is now (in which case `multi_index` should check that the `code` passed into the constructor matches the current receiver, and throw a runtime error if it does not).

**Comment by arhag** [comment]
We have already merged in changes to do a runtime check to prevent `emplace`, `modify`, and `erase` from being called on a `multi_index` when its `_code` is different than the `current_receiver()`. 

This is a good safeguard from developer mistakes for now. But the better solution as the OP mentions, is to allow the `multi_index` to be instantiated in read-only mode, in which case the `current_receiver()` is always used as the code and access to `emplace`, `modify`, and `erase` is denied at compilation time.

This better solution will come when changes to automatically cache `multi_index` tables is implemented (see #2199). Users would still be allowed to instantiate `multi_index` directly (in which case they always avoid the cache and then the runtime checks protect the developers from accidentally calling `emplace`, `modify`, and `erase` when they shouldn't). However, the recommended way to use `multi_index` would be to use the static member `get` function to get a (possibly const) reference to a cache `multi_index` instance.
