### ISSUE TITLE
Checks for "voteproducer" action - eosio.system.hpp

### ISSUE THREAD

**Issue by joneric** [EOSIO/eos#1646]
Hi @bytemaster 

For the 'voteproducer' function:
https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/eosio.system.hpp#L342

Should there be explicit checks to make sure every listed producer or proxy has previously been registered and also that the voter has staked eos tokens in order to vote?

**Comment by andriantolie** [comment]
The line referred in this issue is no longer trackable since eosio.system has been refactored a lot since last March. I'm going to close this issue, if the similar issue still persists in the latest code, please open a new issue. Thanks!
