### ISSUE TITLE
Delegate vs Undelegate - eosio.system.hpp

### ISSUE THREAD

**Issue by joneric** [EOSIO/eos#1654]
Hi @bytemaster

With an existing account in the delegated bandwidth table, why doesn't the delegation of additional bandwidth add to the existing quantities?

https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/eosio.system.hpp#L184

With an existing account in the delegated bandwidth table, the undelegation of bandwidth subtracts from the existing quantities.

https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/eosio.system.hpp#L235

Could this lead to a loss of bandwidth?

**Comment by andriantolie** [comment]
The line referred in this issue is no longer trackable since eosio.system has been modified a lot since last time. I'm going to close this issue. If you see the similar issue with the latest code, please open a new issue with updated reference. Thanks!
