### ISSUE TITLE
Account History API lookup of accounts by public key

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#166]
Will track any account listed in the scope of a transaction that is signed by a specific public key (ignoring any transactions that don't include an account in the account scope filter).

**Comment by brianjohnson5972** [comment]
@bytemaster I just wanted to make sure you agree with my understanding of this feature.

**Comment by nathanhourt** [comment]
This doesn't sound right. I would expect a lookup of accounts by public key to maintain an index of public keys (found in authorities on accounts) to the accounts that posted them.

**Comment by brianjohnson5972** [comment]
So are you saying that the code will need to identify transactions with newaccount or updateauth messages  to identify the keys in each Authority?  And which accounts will each key be tied to?  The accounts in the authority (which we don't seem to be worried about setting yet)?

**Comment by brianjohnson5972** [comment]
(I am assuming that the requirements for this is that I will only be adding to blockchain processing only when this plugin is configured, i.e I shouldn't be affecting existing indices.  Also assuming that my hook into blockchain processing for this is still the chain_controller.applied_block signal.)

**Comment by nathanhourt** [comment]
One option would be to watch for `newaccount` and `updateauth` messages and to parse those; another option would be to observe the database directly and scan all updates to `permission_object`s. This latter approach used to be possible in Bitshares, but I'm not sure if chainbase supports it...

**Comment by brianjohnson5972** [comment]
Nathan and I discussed the option of providing a callback/signal in chainbase::generic_index to indicate when an object was added/modified/deleted for a specific type, but decided this was problematic with the undo logic for popping blocks and we decided that just identifying when messages for apply_eos_newaccount and apply_eos_updateauth are received.  @bytemaster please comment if you were wanting the callback/signal implemented now.

**Comment by brianjohnson5972** [comment]
Also, I'm going to assume that this interface won't make any distinction between "owner" and "active".

**Comment by nathanhourt** [comment]
No distinction between owner and active. Moreover, you should be getting keys from all authorities, not just the owner and active ones.

**Comment by brianjohnson5972** [comment]
newaccount => owner, active, recovery
updateauth => authority
