### ISSUE TITLE
Error building DAWN-2018-02-14 on macOS

### ISSUE THREAD

**Issue by ibigbug** [EOSIO/eos#1661]
1. the script mentioned in the doc `./eosio_build.sh` didn't exist under the tag
2. try using `build.sh darwin` or build manually, will finally failed at the step configure, the message is

```
-- Git commit revision: bcb5bf75
-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: EOS_LIBBSONCXX-NOTFOUND
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: EOS_LIBMONGOCXX-NOTFOUND
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.14") found components:  doxygen dot
-- Doxygen found.  Contract documentation will be generated.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EOS_LIBBSONCXX
    linked by target "db_plugin" in directory /Users/x/x/x/eos/plugins/db_plugin
EOS_LIBMONGOCXX
    linked by target "db_plugin" in directory /Users/x/x/x/eos/plugins/db_plugin
```

any ideas on how to build it successfully from macOS ? thanks

**Comment by ibigbug** [comment]
for those not familiar with cmake, appending:
```
-DEOS_LIBBSONCXX=/usr/local/lib/libbsoncxx.dylib -DEOS_LIBMONGOCXX=/usr/local/lib/libmongocxx.dylib
```

**Comment by arrui** [comment]
I have got the same problem,Could someone fix it ?

**Comment by hsx-ljg** [comment]
I have got the same problem on Ubuntu  branch DAWN-2018-02-14
-- Configuring AppBase on Linux
CMake Error at libraries/appbase/CMakeLists.txt:59 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "appbase".


-- Git commit revision: bcb5bf75
-- Git commit revision: bcb5bf75
-- Git commit revision: bcb5bf75
-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: /usr/local/lib/libbsoncxx.dylib
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: /usr/local/lib/libmongocxx.dylib
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Doxygen not found.  Contract documentation will not be generated.
-- Configuring incomplete, errors occurred!
See also "/home/liao/eos/build/CMakeFiles/CMakeOutput.log"

**Comment by ibigbug** [comment]
@arrui try adding there options to cmake

```
-DEOS_LIBBSONCXX=/usr/local/lib/libbsoncxx.dylib -DEOS_LIBMONGOCXX=/usr/local/lib/libmongocxx.dylib
```

**Comment by ibigbug** [comment]
@hsx-ljg it's not the same issue.

you are missing `DOXYGEN` instead of MONGO driver, please install doxygen and retry

**Comment by spoonincode** [comment]
>install TARGETS given no ARCHIVE DESTINATION for static library target

This error is due to you needing to update you git submodules
```
$ git submodule init
$ git submodule update
```

**Comment by arrui** [comment]
I've solved this error by change CMakeList.txt file.
This error is duplicate with this:
[https://github.com/EOSIO/eos/issues/1601](url)

**Comment by 1109993488** [comment]
brew install gcc
