### ISSUE TITLE
fatal error: 'exchange/exchange.hpp' file not found

### ISSUE THREAD

**Issue by rupaliathashcode** [EOSIO/eos#1662]
i am deploying the exchange contract on eos but it shows fatal error: fatal error: 'currcurrency.hpp' file not found". i don't even change the code.
![image](https://user-images.githubusercontent.com/36531568/37459350-c85ef6a8-286d-11e8-8ca6-ad414d7ea06d.png)

**Comment by andriantolie** [comment]
Contracts inside `contracts/` folder are not intended to be used with eosiocpp as they are compiled with cmake. The above error appears because you don't have currency/currency.hpp in your include folder.
