### ISSUE TITLE
Moving binaries from a build machine to a target environment

### ISSUE THREAD

**Issue by mtadeunet** [EOSIO/eos#1667]
Hi,
Everything builds and runs ok (dawn-2.x) if I'm running EOS on the same machine that it's built. Our methodology will be to run EOS and DAPPS on a target machine, different from the build machines. All these machines will be part of a CI environment. So we would install EOS in a dir, pick everything that is installed and deploy it in a target machine.
The problem I'm facing now, is that this is not possible, because eoscpp has hardcoded paths and it's a pain to 'sed' everything (and maintain these changes). Also the contract skeleton doesn't seem to be installed.
Any chance that eoscpp gets more flexible? Would help if it could detect if some env vars exist and override the existing paths(like eos install dir, wasm paths, etc), because they will be on different directories on the build and run environments.

**Comment by andriantolie** [comment]
The way the path of eosiocpp is determined in the latest version is more flexible. Once you build and install eos on your build machine, you should be able to compile your contract in the build machine. Once it's compiled you should be able to copy the compiled .wast and generated .abi to the target machine
