### ISSUE TITLE
eosiod does not exist after the build

### ISSUE THREAD

**Issue by Npizza** [EOSIO/eos#1676]
I was able to build successfully the environment and now i am trying to create and launch a single node testnet.In the tutorial it says that there is a eosiod binary file in the path 

> build/programs/eosiod 
but the only files that exist in that path are:
CMakeLists.txt
config.hpp.in
main.cpp

What should i do?

**Comment by 4575759ww** [comment]
it seems you open the path is eos/programs/eosiod, not in build category
