### ISSUE TITLE
clang: error: unable to execute command: Killed

### ISSUE THREAD

**Issue by XiaLiangYong** [EOSIO/eos#1677]
FAILED: /usr/bin/clang++   -I/eos/libraries/chain/include -Ilibraries/chain/include -I/eos/libraries/chain/../wasm-jit/Include -I/eos/libraries/chain/../../externals/binaryen/src -I/eos/libraries/utilities/include -I/eos/libraries/utilities/../wasm-jit/Include -I/eos/libraries/fc/include -I/usr/local/include -I/usr/include/openssl/include -I/eos/libraries/fc/vendor/websocketpp -I/eos/libraries/chainbase/include -I/eos/libraries/wasm-jit/Source/Runtime/../../../chain/include -I/eos/libraries/softfloat/source/include -I/eos/libraries/softfloat/source/8086-SSE -I/eos/libraries/softfloat/build/Linux-x86_64-GCC -Wall -Wno-invalid-partial-specialization -fcolor-diagnostics -O3 -DNDEBUG   -std=gnu++14 -MD -MT libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o -MF libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o.d -o libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o -c /eos/libraries/chain/wasm_interface.cpp
In file included from /eos/libraries/chain/wasm_interface.cpp:9:
In file included from /eos/libraries/chain/include/eosio/chain/wasm_interface_private.hpp:5:
/eos/libraries/chain/include/eosio/chain/webassembly/binaryen.hpp:85:8: warning: this is wrong [-W#warnings]
      #warning this is wrong
       ^
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0-1ubuntu1~16.04.2 (tags/RELEASE_400/rc1)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/wasm_interface-995cb4.cpp
clang: note: diagnostic msg: /tmp/wasm_interface-995cb4.sh
clang: note: diagnostic msg:

********************
/eos/libraries/chain/contracts/eosio_contract.cpp:127:8: warning: TODO: update setcode message to include the hash, then validate it in validate  [-W#warnings]
      #warning TODO: update setcode message to include the hash, then validate it in validate
       ^
/eos/libraries/chain/contracts/eosio_contract.cpp:42:13: warning: unused function 'modify_eosio_balance' [-Wunused-function]
static void modify_eosio_balance( apply_context& context, const account_name& account, share_type amt) {
            ^
2 warnings generated.
/eos/libraries/chain/chain_controller.cpp:1600:11: warning: TODO: restore bandwidth checks [-W#warnings]
         #warning TODO: restore bandwidth checks
          ^
1 warning generated.
ninja: build stopped: subcommand failed.

**Comment by jgiszczak** [comment]
That's usually an indication that your virtual machine has run out of RAM.  Either reduce the degree of parallelism in your build (-j2 or omit the -j argument entirely) or give the VM more RAM.

**Comment by njappboy** [comment]
@XiaLiangYong I know this is old but I have run into this type of build failure in the past as well.

In my experience, over 2GiB RAM is required to build.

If you are using a Docker environment check before you build otherwise `eosio/builder` will build but `eosio/eos` and `eosio/eos-dev` will likely fail.


```
$docker system info | grep 'Total Memory:'
Total Memory: 7.787GiB
```
