### ISSUE TITLE
The DAWN-2018-02-14 branch has no eosio_build.sh

### ISSUE THREAD

**Issue by 4xy** [EOSIO/eos#1692]
As you can see the building manual tells to checkout DAWN-2018-02-14 branch.

https://github.com/EOSIO/eos#clean-install-linux-amazon-centos-fedora-mint--ubuntu-for-the-public-testnet

Then it's told to `./eosio_build.sh`, but it's absent. There is only `build.sh`. That gives this:
 
> Usage: bash build.sh TARGET [full|build]
> 
> Targets: ubuntu darwin

I see no Amazon, CentOS, Fedora, Mint targets... I would like to use CentOS.

**Comment by adriancazan** [comment]
I can confirm this behaviour

**Comment by marinalexandru** [comment]
I can confirm this happens. But on master i see the ./eosio_build.sh. Unfortunately the master is not recomended to be built on the documentation.

**Comment by 4xy** [comment]
Exactly...

**Comment by 4xy** [comment]
This couldn't be build... And guys, why do you force to build LLVM? It's  already included in Ubuntu 16.04 "Server" distribution e.g. It takes hours to be built... 

"The EOS.IO Testnet has arrived" Is it joke?

**Comment by jgiszczak** [comment]
The LLVM included with Ubuntu 16.04 is not built with the necessary compile-time flags enabled.  Therefore you must build your own copy.

Testnet 2 is primarily for people who want to become familiar with running a node connected to a live testnet.  It is a snapshot in time, and therefore hasn't received any updates.  Support for Fedora, Mint, etc. is available for the newest versions of the source, but has not been backported to the old version, and will not be.

This is software under heavy development.  It is not suitable for end users at this time.  If you are demanding a friendly end user experience, you will have to wait until after the final release and establishment of a main net.

**Comment by 4xy** [comment]
Ok, I see the update of the manual, but anyway the header claiming **Amazon, Centos, Fedora, Mint** is still there regardless of the actual support of those...
