### ISSUE TITLE
Running eosiod doesn't create directory data-dir

### ISSUE THREAD

**Issue by Mac-m** [EOSIO/eos#1695]
Hi,
I'm trying to follow steps in "Creating and launching a single-node testnet" (https://github.com/EOSIO/eos#creating-and-launching-a-single-node-testnet)
but when I run eosiod, it doesn't create directory named data-dir.
Instead it's stuck at
500312ms thread-0   net_plugin.cpp:2752           plugin_startup       ] starting listener, max clients is 25
Am I missing anything? Where can I find config.ini ?
Thanks in advance,

**Comment by 4575759ww** [comment]
met the same issue

**Comment by 4575759ww** [comment]
./eosiod --config-dir data-dir/

**Comment by newship** [comment]
same on Ubuntu 16.04, it didn't create a directory named data-dir after I run eosiod.

**Comment by Mac-m** [comment]
Thanks @4575759ww  this worked and created data-dir directory and config.ini.
I modified config.ini according to the guide but when I run eosiod it's still stuck at 
226391ms thread-0   net_plugin.cpp:2752           plugin_startup       ] starting listener, max clients is 25

I'm sure 'm missing something simple but I'm not sure what.
Full message when I run eosiod:

226384ms thread-0   chain_plugin.cpp:93           plugin_initialize    ] initializing chain plugin
226385ms thread-0   http_plugin.cpp:141           plugin_initialize    ] host: 127.0.0.1 port: 8888
226385ms thread-0   http_plugin.cpp:144           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
226386ms thread-0   net_plugin.cpp:2614           plugin_initialize    ] Initialize net plugin
226386ms thread-0   net_plugin.cpp:2636           plugin_initialize    ] Setting net_plugin logging level to info
226387ms thread-0   net_plugin.cpp:2664           plugin_initialize    ] host: 0.0.0.0 port: 9876
226387ms thread-0   net_plugin.cpp:2740           plugin_initialize    ] my node_id is 8b11e382669100839d47869162f72278569be6c409eacdba0706dcd752d097d4
226388ms thread-0   main.cpp:110                  main                 ] eosiod version 37f763b8
226388ms thread-0   main.cpp:111                  main                 ] eosio root is /home/macm/eos/build
226389ms thread-0   chain_plugin.cpp:196          plugin_startup       ] starting chain in read/write mode
226390ms thread-0   chain_plugin.cpp:201          plugin_startup       ] Blockchain started; head block is #0, genesis timestamp is 2017-03-30T12:00:00.000
226390ms thread-0   http_plugin.cpp:156           plugin_startup       ] start processing http thread
226390ms thread-0   http_plugin.cpp:213           plugin_startup       ] start listening for http requests
226391ms thread-0   http_plugin.cpp:218           plugin_startup       ] http io service exit
226391ms thread-0   net_plugin.cpp:2752           plugin_startup       ] starting listener, max clients is 25

**Comment by jgiszczak** [comment]
Yes, a local node not connected to the testnet will only produce empty blocks, unless you start conducting transactions on it.  Its purpose is to enable testing of contracts you're developing.  You're now ready to start writing new contracts and trying them out.
