### ISSUE TITLE
can't find data-dir folder after running eosiod

### ISSUE THREAD

**Issue by rogeryu23** [EOSIO/eos#1696]
I am just following the documentation and run eosiod and then press ctrl+c
but there is not data-dir folder created under build/programs/eosiod folder

Any idea?

**Comment by grock999** [comment]
Don't have the exact path with me but since no one has answered yet I think
under 'etc/.../node_00'

**Comment by zshchou** [comment]
eosiod --enable-stale-production true --data-dir tn_data_00 --config-dir tn_data_00

**Comment by rogeryu23** [comment]
Thanks
