### ISSUE TITLE
DAWN-684 ⁃ Rename eosiod to nodeos and eosioc to cleos.

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1700]
Per Dan on 3/19/2018, rename eosiod and eosioc to nodeos and cleos, respectively.

EOSIOD becomes NODEOS
EOSIOC becomes CLEOS

Update:

* Application name
* Application build directories
* Associated scripts (example Phil's startup script)
* Log file names that the applications create
* Readme.md in GitHub
* Wiki pages
* Others?

**Comment by jgiszczak** [comment]
Completed.

**Comment by andriantolie** [comment]
Related PR is https://github.com/EOSIO/eos/pull/1702

**Comment by andriantolie** [comment]
Did a global check and verified that no more eosiod or eosioc used in the code. Removing "needs testing" label.
