### ISSUE TITLE
DAWN-686 ⁃ Pass receiver to `apply`

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1701]
# Description

The cases where a contract will handle an action without calling `current_receiver()` are few and far between.  Meanwhile, most account-independent contract code will need to call `current_receiver()` in order to determine if an incoming action is relevant to its code or not.  This presents boilerplate overhead that cannot be trimmed for actions that the contract is likely to ignore.   

# Proposal

instead of `void apply( name code_account, name action_name);` as the entry point to our contract environment we use `void apply( name receiver, name code_account, name action_name );` and remove the `name current_receiver();` intrinsic. 

# Rationale

The overhead of pushing another basic type onto the WebAssembly stack prior to the entry point call is minimal.  The overhead for intrinsics should also be small but is necessarily more than a simple push (as the intrinsic must push the final value to the stack at a minimum).  So, this should be a minor performance win.

Intrinsics represent consensus level APIs.   Adding and removing them is a hard-fork, so reducing their footprint has intrinsic (get it?) value 😏 

Additional basic type accessors are not as universal as `name current_receiver()` and we cannot pass in anything that would invalidate the semantics common to both `context_free_action` s and `action` s.  Therefore almost all other accessibly information does not qualify for this optimization.

**Comment by andriantolie** [comment]
Related PR is https://github.com/EOSIO/eos/pull/1743

**Comment by andriantolie** [comment]
ATC:
Add unit tests which:
- verify the "receiver" param in apply() matches for action that:
   - is directly sent to the contract
   - is received by another contract and forwarded as inline transaction

**Comment by andriantolie** [comment]
Just recheck the existing unit tests, and found out that the related unit tests already exists inside test_api/test_actions. Since running tests/chain_test passes, then ATC passes
