### ISSUE TITLE
~/eos/build/programs/eosio-launcher error to create multi-node in local testnet

### ISSUE THREAD

**Issue by chenlocus** [EOSIO/eos#1705]
The following is my trial on private testnet to run multi nodes, not public testnet. I want to try it later.

BTW,  to setup a node, it was warned that I need at least 8G memory. 

sudo git clone https://github.com/eosio/eos --recursive

```
cd eos
./eosio_build.sh
```

For ease of contract development, one further step is required, be aware, you need to go to build fold

```
cd build
sudo make install
```

Then I tried to run multi nodes in my local testnet:

```
cd ~/eos/build
cp ../genesis.json ./
./programs/eosio-launcher/eosio-launcher -p2 --skip-signature
```

I came across this error while running:
`/programs/eosio-launcher/eosio-launcher -p2 --skip-signature`

is not a valid path.
![](https://steemitimages.com/DQmY9F17kKVD6vupTA3pPUX1DiTNDt4AhQuC53pU4W2SxJn/image.png)

**Comment by andriantolie** [comment]
Hi, @chenlocus do you have a similar problem with the latest version (v1.0.7)?

**Comment by andriantolie** [comment]
I tried it v1.0.10 and it seems fine. If you still encounter this issue later on please reopen this issue
