### ISSUE TITLE
Limit account names to 12 chars rather than 13.

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1710]
This enables some bits to be used for scopes that cannot have conflicts with account names.

**Comment by andriantolie** [comment]
Related PR is #1774

**Comment by andriantolie** [comment]
ATC: 
add unit tests which test:
- No name should be longer than 12 characters
- If the creator is privileged, the newly created account name is allowed to have "eosio."prefix
- If the creator is not privileged, the newly created account name should not have "eosio." prefix

**Comment by andriantolie** [comment]
Test for the 3rd ATC fails, this is the unit test https://github.com/EOSIO/eos/blob/1710-QA/tests/chain_tests/auth_tests.cpp

**Comment by andriantolie** [comment]
PR https://github.com/EOSIO/eos/pull/1912 added to handle 3rd ATC
