### ISSUE TITLE
'stdint.h' file not found when running the example of smart contract “Hello World”

### ISSUE THREAD

**Issue by Duffyxx** [EOSIO/eos#1718]
I follow the tutorials to run the example of "Hellow World",when I run this command:

./eosiocpp -o hello.wast hello.cpp

get the error:

In file included from hello.cpp:5:
In file included from ./hello.hpp:5:
In file included from /usr/local/include/eosiolib/eosio.hpp:6:
In file included from /usr/local/include/eosiolib/types.hpp:6:
/usr/local/include/eosiolib/types.h:7:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.

My system is 10.13.1 (17B1003).
I have checked this file in clang and g++, stdint.h can be found, I don't know how to do with it.
Can somebody help me?
Thanks.

**Comment by Duffyxx** [comment]
I changed the file /usr/local/include/eosiolib/types.h
#include<stdint.h> to #include</usr/include/stdint.h>
is ok ,and get the error:
 'sys/cdefs.h' file not found
so, I have to change "sys/cdefs.h" to "/usr/include/sys/cdefs.h".
So, why eoscpp can't find files in /usr/include/?

**Comment by yanxi-me** [comment]
+1

**Comment by pokerchain** [comment]
+1

**Comment by pokerchain** [comment]
Solved. 
cd ~/eos/build
sudo make install
cd ~/eos/contract/currency
eosiocpp -o currency.wast currency.cpp

**Comment by mylesshie** [comment]
+1

**Comment by 623059008** [comment]
I don't make eos by myself. I think that's why this error happens.
So Is there any way to solve this without making eos?

**Comment by qs-lll** [comment]
+1

**Comment by sikeeoh** [comment]
+1

**Comment by shalakhin** [comment]
+1

**Comment by yekai1003** [comment]
+1

**Comment by lazaridiscom** [comment]
see #5133 for the case you hit on this error since 1.1.0
