### ISSUE TITLE
Error when trying to compile contract into .wast

### ISSUE THREAD

**Issue by jchung00** [EOSIO/eos#1722]
Similar to #1718 <img width="771" alt="screen shot 2018-03-21 at 6 24 34 pm" src="https://user-images.githubusercontent.com/19266519/37705062-bc111df0-2d35-11e8-87ca-09c6caad7e9e.png">

I followed the Smart Contract "Hello World" example on GitHub

**Comment by gleehokie** [comment]
Please check out the new smart contract tutorial on the GitHub Wiki https://github.com/EOSIO/eos/wiki/Tutorial-Getting-Started-With-Contracts

**Comment by itsmeprasanjit** [comment]
Followed the new tutorial but I am still getting this error 
eosiocpp -o hello.wast hello.cpp
In file included from hello.cpp:1:
In file included from /usr/local/include/eosiolib/eosio.hpp:6:
In file included from /usr/local/include/eosiolib/types.hpp:6:
/usr/local/include/eosiolib/types.h:7:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
1 error generated.

**Comment by mylesshie** [comment]
same error!

**Comment by luoxiaohui** [comment]
+1
