### ISSUE TITLE
last version build error(darwin & ubuntu)

### ISSUE THREAD

**Issue by zshchou** [EOSIO/eos#1723]
[ 83%] Built target fc
[ 84%] Building CXX object externals/binaryen/CMakeFiles/eosio-s2wasm.dir/src/wasm-emscripten.cpp.o
cd /Users/zshchou/blockchain/eos3/build/externals/binaryen && /usr/local/bin/clang++   -I/Users/zshchou/blockchain/eos3/externals/binaryen/src  -Wall -Wno-deprecated-declarations -std=c++11 -Wall -Werror -Wextra -Wno-unused-parameter -fno-omit-frame-pointer -fPIC -O2 -g -DNDEBUG -O2 -UNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk   -std=gnu++11 -o CMakeFiles/eosio-s2wasm.dir/src/wasm-emscripten.cpp.o -c /Users/zshchou/blockchain/eos3/externals/binaryen/src/wasm-emscripten.cpp
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f libraries/chainbase/test/CMakeFiles/chainbase_test.dir/build.make libraries/chainbase/test/CMakeFiles/chainbase_test.dir/depend
cd /Users/zshchou/blockchain/eos3/build && /usr/local/Cellar/cmake/3.10.3/bin/cmake -E cmake_depends "Unix Makefiles" /Users/zshchou/blockchain/eos3 /Users/zshchou/blockchain/eos3/libraries/chainbase/test /Users/zshchou/blockchain/eos3/build /Users/zshchou/blockchain/eos3/build/libraries/chainbase/test /Users/zshchou/blockchain/eos3/build/libraries/chainbase/test/CMakeFiles/chainbase_test.dir/DependInfo.cmake --color=
Dependee "/Users/zshchou/blockchain/eos3/build/libraries/chainbase/test/CMakeFiles/chainbase_test.dir/DependInfo.cmake" is newer than depender "/Users/zshchou/blockchain/eos3/build/libraries/chainbase/test/CMakeFiles/chainbase_test.dir/depend.internal".
Dependee "/Users/zshchou/blockchain/eos3/build/libraries/chainbase/test/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/zshchou/blockchain/eos3/build/libraries/chainbase/test/CMakeFiles/chainbase_test.dir/depend.internal".
Scanning dependencies of target chainbase_test
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f libraries/chainbase/test/CMakeFiles/chainbase_test.dir/build.make libraries/chainbase/test/CMakeFiles/chainbase_test.dir/build
[ 84%] Building CXX object libraries/chainbase/test/CMakeFiles/chainbase_test.dir/test.cpp.o
cd /Users/zshchou/blockchain/eos3/build/libraries/chainbase/test && /usr/local/bin/clang++   -I/Users/zshchou/blockchain/eos3/libraries/chainbase/include -I/usr/local/include  -std=c++11 -stdlib=libc++ -Wall -Wno-conversion -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk   -std=gnu++14 -o CMakeFiles/chainbase_test.dir/test.cpp.o -c /Users/zshchou/blockchain/eos3/libraries/chainbase/test/test.cpp
[ 84%] Building CXX object externals/binaryen/CMakeFiles/eosio-s2wasm.dir/src/wasm-linker.cpp.o
cd /Users/zshchou/blockchain/eos3/build/externals/binaryen && /usr/local/bin/clang++   -I/Users/zshchou/blockchain/eos3/externals/binaryen/src  -Wall -Wno-deprecated-declarations -std=c++11 -Wall -Werror -Wextra -Wno-unused-parameter -fno-omit-frame-pointer -fPIC -O2 -g -DNDEBUG -O2 -UNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk   -std=gnu++11 -o CMakeFiles/eosio-s2wasm.dir/src/wasm-linker.cpp.o -c /Users/zshchou/blockchain/eos3/externals/binaryen/src/wasm-linker.cpp
[ 84%] Linking CXX executable chainbase_test
cd /Users/zshchou/blockchain/eos3/build/libraries/chainbase/test && /usr/local/Cellar/cmake/3.10.3/bin/cmake -E cmake_link_script CMakeFiles/chainbase_test.dir/link.txt --verbose=0
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_filesystem-mt.a(operations.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_filesystem-mt.a(operations.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_filesystem-mt.a(unique_path.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_filesystem-mt.a(unique_path.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(test_tools.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(test_tools.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(unit_test_log.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(unit_test_log.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(test_tree.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(test_tree.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(unit_test_main.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(unit_test_main.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_filesystem-mt.a(path_traits.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_filesystem-mt.a(path_traits.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_filesystem-mt.a(path.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_filesystem-mt.a(path.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(execution_monitor.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(execution_monitor.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(debug.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(debug.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_system-mt.a(error_code.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_system-mt.a(error_code.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(unit_test_parameters.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(unit_test_parameters.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(results_reporter.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(results_reporter.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(progress_monitor.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(progress_monitor.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(unit_test_monitor.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(unit_test_monitor.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(test_framework_init_observer.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(test_framework_init_observer.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(decorator.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(decorator.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(results_collector.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(results_collector.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(xml_log_formatter.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(xml_log_formatter.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(junit_log_formatter.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(junit_log_formatter.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(compiler_log_formatter.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(compiler_log_formatter.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_filesystem-mt.a(codecvt_error_category.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_filesystem-mt.a(codecvt_error_category.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_filesystem-mt.a(utf8_codecvt_facet.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_filesystem-mt.a(utf8_codecvt_facet.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(xml_report_formatter.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(xml_report_formatter.o)) was built for newer OSX version (10.13) than being linked (8.0)
ld: warning: URGENT: building for iOS simulator, but linking in object file (/usr/local/lib/libboost_unit_test_framework-mt.a(plain_report_formatter.o)) built for OSX. Note: This will be an error in the future.
ld: warning: object file (/usr/local/lib/libboost_unit_test_framework-mt.a(plain_report_formatter.o)) was built for newer OSX version (10.13) than being linked (8.0)
Undefined symbols for architecture x86_64:
  "_opendir$INODE64", referenced from:
      boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*) in libboost_filesystem-mt.a(operations.o)
  "_readdir$INODE64", referenced from:
      boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*) in libboost_filesystem-mt.a(operations.o)
  "_readdir_r$INODE64", referenced from:
      boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*) in libboost_filesystem-mt.a(operations.o)
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libraries/chainbase/test/chainbase_test] Error 1
make[1]: *** [libraries/chainbase/test/CMakeFiles/chainbase_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 84%] Linking CXX executable bin/eosio-s2wasm
cd /Users/zshchou/blockchain/eos3/build/externals/binaryen && /usr/local/Cellar/cmake/3.10.3/bin/cmake -E cmake_link_script CMakeFiles/eosio-s2wasm.dir/link.txt --verbose=0
[ 84%] Built target eosio-s2wasm
make: *** [all] Error 2

**Comment by andriantolie** [comment]
`clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)`
Normally this happens because some of the files in the build folder are not owned by you. You can either chown them or use sudo to build eosio.
