### ISSUE TITLE
Sensitive content stored on blockchain

### ISSUE THREAD

**Issue by utilsites** [EOSIO/eos#1724]
About sensitive data stored on EOS blockchain, like child sensitive content. It can be a big problem, because it can't be removed, after being in an irreversible block.

**So who has full nodes is storing and distributing this sensitive content and can be liable to justice, it can be an argument to community/governments try to close every block producer and validator.**

I'm talking about storing an image bytes on an smart contract transaction input message, as the maximum size allow that (i think), can you confirm? A picture with 5KB is visible enough. Inspect every transaction input on fly seems not viable. Storing a hash pointing to IPFS should be no problem, because it can be removed in IPFS. In the blockchain is diferent, and I cannot find a solution to this, even if the community votes to remove the transaction, or create a blacklist, it can always exist a block explorer that allow to easily see this sensitive content, and it can be used to attack this project on public eyes! 
What do you think?

**Comment by bytemaster** [comment]
This issue applies to all blockchains.

**Comment by utilsites** [comment]
@bytemaster, I know that it applies to all blockcahins, but EOS is trying to be the BEST one!
This problem can be a big risk for all blockchain projects, maybe the community should start to find possible solutions.
- Maybe a simple filter check to don't allow images/videos bytes on transaction inputs?
- There is some way to remove or invalidate one transaction (by community consent) from an older block and reconstruct the hashs of the following blocks without breaking the inter blockchain communication and states? 
Thanks for you thoughts and availability.
