### ISSUE TITLE
DAWN-695 ⁃ Deferred transaction bugs

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eos#1735]
1. cancel_deferrerd is able to cancel transaction which will be created in the same action after the call to cancel_deferred
2. it's possible to create multiple transactions with the same sender_id
3. minor bug: print() doesn't work in deferred transactions (nothing appears in console)
4. apply_context::execute_deferred uses default_max_gen_trx_count instead of actual parameter

**Comment by gleehokie** [comment]
Fixed by PR #1883

**Comment by andriantolie** [comment]
Case 1 and 2 are verified by the existing api_tests/deferred_transaction_tests unit tests, while case 3 and 4 are verified by the additional unit test https://github.com/EOSIO/eos/pull/2173
