### ISSUE TITLE
 ../programs/eosd/eosd: No such file or directory

### ISSUE THREAD

**Issue by luoxianjiao** [EOSIO/eos#1739]
when run ./start_npnode.sh shell，show blow error in stderr.text
 ../programs/eosd/eosd: No such file or directory

**Comment by jgiszczak** [comment]
OBE.  This is effectively archaeology, at this point.  `eosd` has been renamed twice since then, `start_npnode.sh` no longer exists, and the boot process is entirely different.  See current tutorials in the wiki and the `tutorials` directory in the source for current practices.
