### ISSUE TITLE
EOS build for public testnet fails on Ubuntu 16.04 (AWS)

### ISSUE THREAD

**Issue by nksanthosh** [EOSIO/eos#1741]
git clone https://github.com/eosio/eos --recursive
cd eos
git checkout DAWN-2018-02-14
git submodule update --recursive
./build.sh

fails at:

![image](https://user-images.githubusercontent.com/8515898/37754680-e4c60bba-2de5-11e8-82d7-90ed5068e1df.png)

**Comment by bytemaster** [comment]
DAWN-2018-02-14 is no longer supported.

**Comment by nksanthosh** [comment]
Thx. Will instructions on https://github.com/EOSIO/eos#runanode be updated? 

How do we compile and run public testnet?
