### ISSUE TITLE
DAWN-693 ⁃ We are not currently validating: tapos, expiration, uniqueness for transactions

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1753]
ATC: demonstrable test cases that show proper rejection of bad tapos, expiration and uniqueness

**Comment by bytemaster** [comment]
We are checking for duplicate transactions.

**Comment by andriantolie** [comment]
Related PR is https://github.com/EOSIO/eos/pull/1865

**Comment by taokayan** [comment]
Is there any detail steps for QA testing?

**Comment by taokayan** [comment]
new unitest cases for validating ta_pos, and transaction expiration are added. Please see pull request https://github.com/EOSIO/eos/pull/2055
