### ISSUE TITLE
DAWN-620 ⁃ "on block" action for system contract

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1758]
At the close of every block the system contract should receive an action which contains header information of the block.  The purpose of this action is to trigger any per-block processing in the system contract.

This action should be implicit and not directly mentioned in the block structure (however, it can and should appear in the block trac)

This action should contribute to the action merkle for the block.

**Comment by bytemaster** [comment]
What branch has this code?

**Comment by zorba80** [comment]
It's in system-contract-voting-2.

**Comment by andriantolie** [comment]
ATC:
- Modified onblock handler inside eosio.system to print a statement
- Upload eosio.system contract to eosio
- Verify that the statement is printed every time a block is produced

**Comment by andriantolie** [comment]
ATC passes
