### ISSUE TITLE
DAWN-622 ⁃ Add soft float support

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1759]
Add support for floats and doubles for WASM via a software implementation of IEEE Std 754-2008 and add plumbing for redirecting floating point operations to their soft float counterparts.  This should cover all current backends.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

How is progress going on this ticket?

**Comment by bytemaster** [comment]
This has been merged to master.

**Comment by dhaneshvb** [comment]
test_softfloat_wasts passes
