### ISSUE TITLE
DAWN-649 ⁃ Set the permissions of eosio based on producers

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1763]
Set the permissions of eosio based on producers on testnet3

The root account is always where the system contract lives.  The rules for the system contract  basically requires the consensus of the producers to update/affect root actions like freezing accounts.  It stands to reason that this is what we used to call the "@producers" account.

And if we modify the root accounts authorities when the producers change then we have pretty much set it up "right"

**Comment by blockone-syncclient** [comment]
➤ Greg Lee commented:

From [~dan.larimer]:

@root can be separate from @producers when @producers are passive non-policy making role...

@root can set active=@producers to hand control over to producers

**Comment by blockone-syncclient** [comment]
➤ Bart Wyatt commented:

Our best interpretations of this WRT to what was previously known as "producer privileges" is as follows:

Producer Privileges -> Root Privileges 
@producers is an account with no inherent privileges, it is merely a figurehead account whose active authority is always "2/3+1 of the producers" 

A system contract may assign some of its privileges to @producers via WebAssembly by making a permission level which expects producers@active to be satisfied and then using that permission level to authorize certain WebAssembly methods.

We still need a reserved "producers" account, it should not be legal to update the authorities on this account directly so, it can be a "virtual" account if such an implementation is convenient.

**Comment by bytemaster** [comment]
The system contract can always perform inline updateauth messages to change the producers account permissions when ever it changes the producer schedule. No need to enforce this special mapping outside wasm.
