### ISSUE TITLE
DAWN-661 ⁃ stabilize testnets 2 & 3

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1764]
testnet blues. Yesterday I tried to bring up a dawn 3 based testnet using testnet 2. Because I was using the launcher, and it still has a number of configuration items with hardwired values, I shut down the dawn 2 nodes. I then followed Bart's recipe for launching the new network, with a few modifications. This failed. The failure seems to be related to the test.system's setprods action. With this action I watched the bios node switch from producing nodes to not producing, but none of the peers began producing.

So then I tried to restart the dawn 2 network for HK to be able to test and that action also failed. I had apparently failed to reset the EOSIO_HOME value in my working shell, so when I used the launcher to deploy the 21 appointed nodes, the config files ended up overwriting the dawn 2 files. Fortunately I had the original dawn 2 config files in a staging directory so I was able to restore those.

Next I found that all nodes started and were waiting for current blocks, but node 1 would not start producing. After more investigation I found that node 1's config file identified the producer as 'initb' rather than 'inita' as it should be. I have no idea how this change came to pass. Anyway, I fixed that and tried one more time to start node 1. This seemed to work but when it tried to produce a block it was hit by an unhandled assertion: chain_controller.cpp:1432: void eosio::chain::chain_controller::update_last_irreversible_block(): Assertion `block' failed.

Attempting to start other nodes with enable-stale-production = true and they all met the same fate.

So this is where I am with the testnet.

**Comment by bytemaster** [comment]
Duplicate #1768
