### ISSUE TITLE
DAWN-669 ⁃ augment the NIST crypto-primitives with ec25519

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1765]
We plan to support multiple curves - important to augment the NIST crypto-primitives with ec25519 (I believe this is in the 'fc' libs)

Goal is to free people from a sole dependency on older USG NIST curves and their (likely) NSA backdoors and offer them the option to use more secure modern alternatives.

We currently have code that supports SecP256k1 (bitcoin standard) and SecP256P1 (apple, android and windows). See the Readme file under the Apple Secure Enclave demo at programs/eosio-applesedemo/README.md .

This is expected to be modular and have low impact, but would likely be a forking change, according to Bart.

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner @arhag Is this still relevant or is it OBE?  I will assume OBE if I hear nothing.

**Comment by brianjohnson5972** [comment]
OBE (Overcome By Events)
