### ISSUE TITLE
DAWN-671 ⁃ Stricter Authority Checks

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1766]
There are a few pathological cases where we are not properly validating transactions and should be:

1. Now that CFAs exist all "normal" actions should require some sort of authorization.  This should be enforced and does not appear to be.
1. Enforcing the above will defeat the current "could be CFA" check.  That check should be changed to only respect the api usage.  In addition, this should be the **first** assertion checked so that any action that could be CFA is reported that way regardless of the other "normal" transaction rules. (see chain_controller __apply_transaction()).
1. We should enforce that the list of authorization is concise.  This should be done by collecting the authorizations actually needed during application (by tracking calls to `apply_context::require_authorization`) and verifying that the provided authorization exactly matches the used authorizations
1. We should enforce that all transactions have at least one valid "normal" action.  

ATC: demonstrable (and passing) unit test cases for all of the above.

**Comment by bytemaster** [comment]
All transactions require at least one authorization, but not actions require an authorization. The only reason to require an authorization on a transaction is to know who to bill for bandwidth.

**Comment by bytemaster** [comment]
Rather than enforcing authorizations to be concise, we could simply bill the user for computation based upon the number of authorizations specified.

**Comment by andriantolie** [comment]
ATC Passes.
api_tests/cf_action_tests has verified the ATC and it passes
