### ISSUE TITLE
DAWN-672 ⁃ Succinct error reports from ctest/jenkins

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1767]
The amount of console logging and spam produced during our current test runs makes it very hard if not impossible to correctly identify which tests are failing why.  

This task has authority to remove logging from tests, change logging methods in jenkins/ctest/tests and an other means necessary to make identifying failing tests simpler.  

For Jenkins specific ideas/changes please coordinate with [~eric.iles]

ATC: Output in failing Builds is reduced to a minimal set of information that will directly point reviewers/committers to the failing test cases that need to be addressed.

**Comment by blockone-syncclient** [comment]
➤ Bart Wyatt commented:

for example.  The log output for chain_test from https://jenkins.eos.io/blue/rest/organizations/jenkins/pipelines/eosio/branches/exchange/runs/11/nodes/66/steps/87/log/?start=0

could conceivably be condensed to something LIKE:

Test case "recovery_tests/test_recovery_multisig_owner" was aborted
    exception tx_missing_sigs expected but not raised
    tests/chain_tests/recovery_tests.cpp(69): last checkpoint

Test case "recovery_tests/test_recovery_owner" was aborted
    exception tx_missing_sigs expected but not raised
    tests/chain_tests/recovery_tests.cpp(102): last checkpoint

Test case "abi_tests/abigen_all_types" was aborted
    fatal error: 'boost/preprocessor/seq/for_each.hpp' file not found
    #include <boost/preprocessor/seq/for_each.hpp>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Assert Exception
    tests/tests/abi_tests.cpp(612): last checkpoint
This is just intended as an example, not intended to be prescriptive

**Comment by andriantolie** [comment]
Related PR is #1803
