### ISSUE TITLE
DAWN-678 ⁃ Prune/Remove/Cleanup/Never-Start Empty Cycles/Shards in blocks

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1769]
We are currently producing empty cycles and shards as an artifact of several calls to push_transaction.

We should fix the edge cases or implement a clean up process where by there are no empty shards and no empty cycles in blocks

This should be enforced by downstream validators (rejection blocks that are malformed due to empty regions,cycles,shards)

Previously we needed to accept empty blocks however, with DAWN-658 all blocks will contain the delivery of the on-block action to the system contract _at least_

ATC: every region/cycle/shard has something in it.  apply_block validates this, test cases manually create invalid blocks and they fail.

**Comment by bytemaster** [comment]
Delivery of block header is inferred and need to be included in the block. It also does not require a proof.

**Comment by andriantolie** [comment]
ATC Passes.
Added unit test to verify this (https://github.com/EOSIO/eos/pull/2052)
