### ISSUE TITLE
DAWN-681 ⁃ Segwit - Changing how block IDs are calculated 

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1771]
Segwit

Blockheaders should not include the hash of signature in the block ID.

**Comment by bytemaster** [comment]
From inspection of the code it appears this is complete.

**Comment by andriantolie** [comment]
I added a unit test to check if the block id is independent of producer_signature (it's in the end of file https://github.com/EOSIO/eos/blob/1771-QA/tests/chain_tests/block_tests.cpp) and it's failing

**Comment by heifner** [comment]
Thanks @andriantolie. I pulled your unittest with a fix into #2104 .

**Comment by andriantolie** [comment]
The related unit test is "block_tests/block_id_sig_independent" and it passes.
