### ISSUE TITLE
DAWN-685 ⁃ Pass processing off to the system contract for native actions

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1773]
All native actions that target the system contract should also be delivered implicitly to the eosio.system wasm code.

**Comment by bytemaster** [comment]
This enables rejection based on extra criteria as well as allows WASM to maintain extra state about accounts and permissions.

**Comment by wanderingbort** [comment]
This was closed by #1942

**Comment by andriantolie** [comment]
This is handled by https://github.com/EOSIO/eos/issues/1938, since #1938 passes, I'm going to put the label here
