### ISSUE TITLE
WASM API for Console Pretty Printing

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1780]
setwidth, precision, align left / right.

**Comment by spoonincode** [comment]
Is there a reason iostream can't be used for this?

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner @spoonincode Is this still a desire or can it be closed?

**Comment by wanderingbort** [comment]
There may be a desire for this however, it depends largely on a complete view of the developer tools we want to support.  Adding this as intrinsics in contracts puts burden on the CDT and the users to compile "proper" wasm for deployment where these intrinsics should not be available.  That usability concern means that we are complicating the development pipeline for something with an unquantified value proposition. 

For now we should close this and re-evaluate it in the space of the CDT OR in some higher-level conversation about developer tooling/workflow.
