### ISSUE TITLE
Update Currency standard to add a "type" field for the memo.

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1781]
the type can be used by the ABI to interpret the contents of the memo.

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner This appears to have been written against the old currency contract and not eosio.token, so is it OBE?  I will presume OBE if I don't hear anything.

**Comment by wanderingbort** [comment]
I think this needs to be preceded by a discussion of the use-cases it addresses and whether this is an appropriate solution to those use cases.   There are a number of deployed applications that are now stakeholders in this and have their own solutions.
