### ISSUE TITLE
~/eos/build/programs/eosio-launcher error to create multi-node in local testnet

### ISSUE THREAD

**Issue by chenlocus** [EOSIO/eos#1783]
#### Expected behavior
The following is my trial on private testnet to run multi nodes, not public testnet. I want to try it later.

BTW,  to setup a node, it was warned that I need at least 8G memory. 

sudo git clone https://github.com/eosio/eos --recursive

```
cd eos
./eosio_build.sh
```

For ease of contract development, one further step is required, be aware, you need to go to build fold

```
cd build
sudo make install
```

Then I tried to run multi nodes in my local testnet:

```
cd ~/eos/build
cp ../genesis.json ./
./programs/eosio-launcher/eosio-launcher -p2 --skip-signature
```
It is expected to create two nodes locally:

spawning child, programs/eosiod/eosiod --skip-transaction-signatures --data-dir tn_data_0
spawning child, programs/eosiod/eosiod --skip-transaction-signatures --data-dir tn_data_1

#### Actual behavior

However, I came across this error while running:
`/programs/eosio-launcher/eosio-launcher -p2 --skip-signature`

is not a valid path.
![](https://steemitimages.com/DQmY9F17kKVD6vupTA3pPUX1DiTNDt4AhQuC53pU4W2SxJn/image.png)

#### How to reproduce

With my process above, it is easy to reproduce this issue.

The tutorial I was following:

https://github.com/EOSIO/eos

You can search "Running multi-node local testnet’.

* Browser:  Chrome
* Operating system: Ubuntu 16.04 LTS

#### Recording Of The Bug
If the bug can be recorded on screen, please provide a short video or an animated GIF, otherwise delete this section.
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@chenlocus/eos-build-programs-eosio-launcher-error-to-create-multi-node-in-local-testnet">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by filipealonso** [comment]
From your screenshot it seems you are not running from the build/ folder but from the build/programs/eosio-launcher/ folder instead which is not necessary (eosio-launcher should be in PATH and therefore accessible anywhere) and might be causing the issue (since the launcher tries to reach the build/etc/eosio/node_00 folder created during make install).

**Comment by chenlocus** [comment]
Hi filipealonso, 

I can provide another screenshot that I ran from build/folder but not work.

![image](https://user-images.githubusercontent.com/15951769/37863685-52c7c910-2fb6-11e8-8e3d-1aac87a3ca2d.png)

**Comment by filipealonso** [comment]
Try just:
**cd ~/eos/build/
eosio-launcher -p2 --skip-signature**

**Comment by andriantolie** [comment]
Do you still encounter the issue with latest code?

**Comment by andriantolie** [comment]
Please try again with v1.1. I tried with v1.1. and I didn't encounter the above-mentioned issue. If you stlil encounter the problem please reopen this issue
