### ISSUE TITLE
[push_transaction error] '{"code":401,"message":"UnAuthorized","details":"signatures do not satisfy declared authorizations (3030002)\nTransaction declares authority '{\"account\":\"inita\",\"permission\":\"active\"}', but does not have signatures for it.\n\n"}

### ISSUE THREAD

**Issue by luoxianjiao** [EOSIO/eos#1787]
when i use "newaccount" method of eosjs ，it occur errors as title，my param is eos.newaccount({
  creator: 'inita',
  name: 'ylm',
  owner: initaPublic,
  active: initaPublic,
  recovery: 'inita',
  deposit: '1 EOS'
})

**Comment by filipealonso** [comment]
You need to import inita's keys to your wallet. Check config.ini for the private key and do:
_eosioc wallet import **&lt;key&gt;**_
(replace <key> with inita's private key)

**Comment by filipealonso** [comment]
You need to use inita's keys. Check config.ini for the key and follow the "Complete example" section here https://github.com/EOSIO/eosjs#contract
