### ISSUE TITLE
Simple Token example contract finalization

### ISSUE THREAD

**Issue by sergmetelin** [EOSIO/eos#1790]
A new example contract has been created - https://github.com/EOSIO/eos/blob/dispatch2/contracts/simple.token/simple.token.cpp, however, it is not documented currently. 

ACT:
- Tests are implemented and passing
- Contract is documented - description, example usage, code comments
- ABI is implemented
- README.md is implemented

**Comment by navcsdev** [comment]
@sergmetelin Now it had https://github.com/EOSIO/eos/blob/master/TUTORIAL.md 😄

**Comment by jgiszczak** [comment]
Simple.token is deprecated in favor of eosio.token.
