### ISSUE TITLE
Re-enable low participation check with appropriate block producer participation metric

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#1806]
See comment in PR #1805.

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner @arhag @jgiszczak  This sure seems like an idea that is no longer part of the plan.  If I don't hear from you I will presume it should be closed.

**Comment by brianjohnson5972** [comment]
The code has moved on from this point and it this is no longer part of the plan for the software.
