### ISSUE TITLE
Minimum hardware requirements to build the node from the scratch

### ISSUE THREAD

**Issue by sergmetelin** [EOSIO/eos#1807]
As mentioned here: https://steemit.com/dan/@prameshtyagi/eos-getting-started-document-need-to-be-updated-to-include-minimum-hardware-requirements we need to include minimum hardware requirements to build a node (from the scratch/docker). 

ACT:
- README.md is updated to reflect minimal hardware requirements for the build from the sources
- README.md is updated to reflect minimal hardware requirements for the Docker distribution

**Comment by jgiszczak** [comment]
Hardware requirements are now enforced by the build script and documented on the Developer Portal [here](https://developers.eos.io/eosio-nodeos/docs/install-nodeos).
