### ISSUE TITLE
Spin up mongodb for tests on Jenkins

### ISSUE THREAD

**Issue by heifner** [EOSIO/eos#1809]
Mac and Fedora do not auto start mongodb. 
Add a start of mongodb for mongo test in Jenkins.
`mongod -f /etc/mongod.conf`

**Comment by ericiles** [comment]
This has been resolved with PR #1810

**Comment by andriantolie** [comment]
ATC:
- Ensure you have mongodb installed
- Ensure you don't have any mongodb process running (execute `ps -aef | grep mongodb` and makes sure it's empty), if it doesn't, kill it first
- Run ./eosio_build.sh
- Check if you have mongodb process running by `ps -aef | grep mongodb`

**Comment by andriantolie** [comment]
ATC passes
