### ISSUE TITLE
mac os with build error

### ISSUE THREAD

**Issue by wengjunxiao** [EOSIO/eos#1812]
when I build the code use the commend with mac os bellow:

> git clone https://github.com/eosio/eos --recursive
> cd eos
> ./eosio_build.sh
> 
 I get the error bellow, do somebody know how to solve it ?

> 
> -- Configuring Eos on OS X
> -- binaryen building with -std=c++11
> -- binaryen building for platform x86-64
> -- binaryen building with -Wall
> -- binaryen building with -Werror
> -- binaryen building with -Wextra
> -- binaryen building with -Wno-unused-parameter
> -- binaryen building with -fno-omit-frame-pointer
> -- binaryen building with -fPIC
> -- binaryen building with -O2
> -- binaryen building with -UNDEBUG
> -- Could NOT find WASM (missing: WASM_CLANG)
> CMake Error at CMakeModules/wasm.cmake:8 (message):
>   No WASM compiler cound be found (make sure WASM_ROOT is set)
> Call Stack (most recent call first):
>   CMakeLists.txt:194 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/weng/eos/build/CMakeFiles/CMakeOutput.log".

**Comment by learnforpractice** [comment]
./eosio_build.sh darwin


That’s it

**Comment by ericiles** [comment]
I am unable to reproduce this on a clean install of MacOS High Sierra 10.13.3. Can you provide the full output of eosin_build.sh?

**Comment by wengjunxiao** [comment]
I have solved it by add the clang to my wasm directory, thank you

**Comment by learnforpractice** [comment]
I didn’t notice the script has been changed. That’s not the problem of “darwin”.

All things go will on macOS 10.13.3.

**Comment by nishant-birdeye** [comment]
> I have solved it by add the clang to my wasm directory, thank you

@wengjunxiao can you elaborate that ? I am having the same issue. Do I need to follow the steps here : https://clang.llvm.org/get_started.html ?
