### ISSUE TITLE
single-node testnet built from DAWN-2018-02-14 does not produce blocks

### ISSUE THREAD

**Issue by CharlesJu1** [EOSIO/eos#1818]
I was able to build DAWN-2018-02-14  on Ubuntu 17.10 and follow the instruction to setup the config.ini file with producers. When I run eosd, I got the following log message:
1330133ms            chain_api_plugin.cpp:60       plugin_startup       ] starting chain_api_plugin
1330133ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/abi_bin_to_json
1330134ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/abi_json_to_bin
1330134ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_account
1330134ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_block
1330134ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_code
1330134ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_info
1330134ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_required_keys
1330134ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_table_rows
1330134ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_block
1330135ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_transaction
1330135ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_transactions
1330135ms            net_plugin.cpp:2662           plugin_startup       ] starting listener, max clients is 25

However, I do not see the log messages related to producing blocks. 

Here is the related part of config.ini file.

genesis-json = /home/cju/eos-data/genesis.json
enable-stale-production = true
producer-name = inita
producer-name = initb
producer-name = initc
producer-name = initd
producer-name = inite
producer-name = initf
producer-name = initg
producer-name = inith
producer-name = initi
producer-name = initj
producer-name = initk
producer-name = initl
producer-name = initm
producer-name = initn
producer-name = inito
producer-name = initp
producer-name = initq
producer-name = initr
producer-name = inits
producer-name = initt
producer-name = initu

plugin = eosio::producer_plugin
plugin = eosio::wallet_api_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::http_plugin

Here are some output from eosc command:

cju@cju-VirtualBox:~/eos/build/programs/eosc$ ./eosc get info
{
  "server_version": "bcb5bf75",
  "head_block_num": 0,
  "last_irreversible_block_num": 0,
  "head_block_id": "0000000000000000000000000000000000000000000000000000000000000000",
  "head_block_time": "2018-03-20T12:00:00",
  "head_block_producer": "",
  "recent_slots": "1111111111111111111111111111111111111111111111111111111111111111",
  "participation_rate": "1.00000000000000000"
}

cju@cju-VirtualBox:~/eos/build/programs/eosc$ ./eosc wallet keys
[[
    "EOS654t1ESh4Ld1cDxA8drPaT2W1Q1EPQWcBtXvXNSHMu9TC7asjb",
    "5JXn2hnrUTqnL2SAfd5tky92VwSwhqfkcR2kYMdS2X6Ek7dd1mD"
  ],[
    "EOS6GfoPfJGpcMo6vBwZshERST19L5RPqVvzd7Eq41ArJEfridA6B",
    "5JpafRyWSoVcxDJRNh3expScyUFNx1yfDCGPKxzUVs4Jty4mtHB"
  ],[
    "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
    "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
  ]
]

cju@cju-VirtualBox:~/eos/build/programs/eosc$ ./eosc get account inita
2176624ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"unknown key"}

How to fix the "unknown key" error ?

Any other configuration needed for eosd to produce blocks?

**Comment by zhky04** [comment]
I have encounter this problem either, and i solve it by adding eosio as producer name to config.ini.
