### ISSUE TITLE
Complete Review of Permission System

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1821]
We need to be very careful with how actions are authorized or we might expose unintentional vulnerabilities is users execute actions on malicious contracts. We need a framework for evaluating what is and isn't a security issue.  

While we have many different permission levels, we should design security around the assumption that all actions are executed with "active" permission. 

## Example Bad Design 
```
badcontract::exec() with auth usera
   inline currency::transfer( usera, badcontract, allyourbase ) signed usera
```

## Example Good Design 
```
eosio::system updateauth currency::transfer to add goodcontract 
goodcontract::exec() with auth usera 
   inline currency::transfer( usera, goodcontract, allyourbase )  signed goodcontract
```

In this example the user specifically gave permission to good contract to transfer, when evaluating the inline action we evaluate it as if it was signed by goodcontact which is listed under usera::transfer authority and therefore permitted.

## Inline to Self 
There are many cases where we would like to inline to the same contract:
```
contract::exec()
    inline contract::otheraction()
```

Because otheraction is also on contract we can presume that contract has complete authority. This can be proven valid because the exec() method had complete write permission and could have accomplished the same thing by simply calling otheraction rather than generating an inline action. In this case contract chooses to generate an inline action so that external tools can pick it up and/or ensure certain invariants are maintained.

**Comment by jeremi** [comment]
There is no way to check an authorization for a specific permission. 

Would it be possible to expose `require_authorization(const account_name& account,
                                          const permission_name& permission)` in the contracts:
https://github.com/EOSIO/eos/blob/83f6ce54a78e60d91672f3cce5f6b0d5ba7bd18c/libraries/chain/apply_context.cpp#L128

As of now, only `require_authorization(const account_name& account)` is exposed:
https://github.com/EOSIO/eos/blob/511e2b819f610b26692972967d6310bbb7b21bab/libraries/chain/wasm_interface.cpp#L1510

**Comment by bytemaster** [comment]
@jeremi it is possible to read the entire action and all specified permission levels; however, permission levels are something the account manages, not the contract. A contract should not be telling the user what 'named permission levels' he/she should have.

**Comment by andriantolie** [comment]
Related PR is #1835

**Comment by gleehokie** [comment]
I added the "needs testing" label back onto this issue.  There are unit tests in PR #1835, verify they are complete, included in the running tests and functioning correctly.
