### ISSUE TITLE
after excute ./nodeos it will not create data-dir and no config.ini(press ctrl+c is not ok)

### ISSUE THREAD

**Issue by wrjicediamond** [EOSIO/eos#1822]
after excute ./nodeos it will not create data-dir and no config.ini(press ctrl+c is not ok)

**Comment by wrjicediamond** [comment]
it is execute in ubuntu 16.04

**Comment by okluoquan** [comment]
it is the same, execute in mac.

**Comment by wrjicediamond** [comment]
@okluoquan have you resolve this problem?

**Comment by yumenohosi** [comment]
./nodeos --config-dir data-dir/

**Comment by jgiszczak** [comment]
Default location is now `build/etc/eosio/node_00/config.ini` if run from the `build` directory.  If run from a Debian package, the default location is `/etc/eosio/node_00/config.ini`.  Default location for the chain and `nodeos` shared memory is `build/var/lib/eosio/node_00`.  You can specify a config location via `--config-dir` anywhere you like.

**Comment by renguzi** [comment]
yes.
it works on my environment:Google ECS,Centos 7
Does not work:
`[root@instance-2 nodeos]# pwd
/root/eos/build/programs/nodeos
[root@instance-2 nodeos]# ./nodeos 
651594ms thread-0   chain_plugin.cpp:96           plugin_initialize    ] initializing chain plugin
651594ms thread-0   http_plugin.cpp:141           plugin_initialize    ] host: 127.0.0.1 port: 8888 
651594ms thread-0   http_plugin.cpp:144           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
651594ms thread-0   net_plugin.cpp:2625           plugin_initialize    ] Initialize net plugin
651594ms thread-0   net_plugin.cpp:2647           plugin_initialize    ] Setting net_plugin logging level to info
651594ms thread-0   net_plugin.cpp:2675           plugin_initialize    ] host: 0.0.0.0 port: 9876 
651594ms thread-0   net_plugin.cpp:2751           plugin_initialize    ] my node_id is 98dccc526ba0d36f8303bd28a3ae4e015eeb5a490510ab71a7aa3bdfcbaf0b0b
651594ms thread-0   main.cpp:110                  main                 ] nodeos version 7ba3a8c3
651594ms thread-0   main.cpp:111                  main                 ] eosio root is /root/eos/build
651606ms thread-0   chain_plugin.cpp:205          plugin_startup       ] starting chain in read/write mode
651606ms thread-0   chain_plugin.cpp:210          plugin_startup       ] Blockchain started; head block is #0, genesis timestamp is 2017-03-30T12:00:00.000
651606ms thread-0   http_plugin.cpp:156           plugin_startup       ] start processing http thread
651606ms thread-0   http_plugin.cpp:213           plugin_startup       ] start listening for http requests
651606ms thread-0   http_plugin.cpp:218           plugin_startup       ] http io service exit
651606ms thread-0   net_plugin.cpp:2763           plugin_startup       ] starting listener, max clients is 25
651885ms thread-0   net_plugin.cpp:2777           plugin_shutdown      ] shutdown..
651885ms thread-0   net_plugin.cpp:2780           plugin_shutdown      ] close acceptor
651885ms thread-0   net_plugin.cpp:2783           plugin_shutdown      ] close 0 connections
651885ms thread-0   net_plugin.cpp:2791           plugin_shutdown      ] exit shutdown
[root@instance-2 nodeos]# ll
total 300596
drwxr-xr-x. 3 root root        85 Mar 29 05:49 CMakeFiles
-rw-r--r--. 1 root root      3640 Mar 29 03:26 cmake_install.cmake
-rw-r--r--. 1 root root       625 Mar 29 03:26 config.hpp
-rw-r--r--. 1 root root       269 Mar 29 03:26 CTestTestfile.cmake
-rw-r--r--. 1 root root      8495 Mar 29 03:26 Makefile
-rwxr-xr-x. 1 root root 307784472 Mar 29 06:12 nodeos
[root@instance-2 nodeos]# `

Work
`[root@instance-2 nodeos]# pwd
/root/eos/build/programs/nodeos
[root@instance-2 nodeos]# ./nodeos --config-dir data-dir/

799806ms thread-0   chain_plugin.cpp:96           plugin_initialize    ] initializing chain plugin
799807ms thread-0   http_plugin.cpp:141           plugin_initialize    ] host: 127.0.0.1 port: 8888 
799808ms thread-0   http_plugin.cpp:144           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
799808ms thread-0   net_plugin.cpp:2625           plugin_initialize    ] Initialize net plugin
799808ms thread-0   net_plugin.cpp:2647           plugin_initialize    ] Setting net_plugin logging level to info
799808ms thread-0   net_plugin.cpp:2675           plugin_initialize    ] host: 0.0.0.0 port: 9876 
799808ms thread-0   net_plugin.cpp:2751           plugin_initialize    ] my node_id is bb57b899ca02f72f9511ae82c8bb538796184f79a8b4eae97d8b1996c6664f17
799808ms thread-0   main.cpp:110                  main                 ] nodeos version 7ba3a8c3
799808ms thread-0   main.cpp:111                  main                 ] eosio root is /root/eos/build
799809ms thread-0   main.cpp:115                  main                 ] 10 assert_exception: Assert Exception
fc::exists( my->genesis_file ): unable to find genesis file '/root/eos/build/programs/nodeos/data-dir/genesis.json', check --genesis-json argument
    {"f":"/root/eos/build/programs/nodeos/data-dir/genesis.json"}
    thread-0  chain_plugin.cpp:182 plugin_startup

    {"my->genesis_file.generic_string()":"/root/eos/build/programs/nodeos/data-dir/genesis.json"}
    thread-0  chain_plugin.cpp:214 plugin_startup
[root@instance-2 nodeos]# 
[root@instance-2 nodeos]# ll
total 300596
drwxr-xr-x. 3 root root        85 Mar 29 05:49 CMakeFiles
-rw-r--r--. 1 root root      3640 Mar 29 03:26 cmake_install.cmake
-rw-r--r--. 1 root root       625 Mar 29 03:26 config.hpp
-rw-r--r--. 1 root root       269 Mar 29 03:26 CTestTestfile.cmake
drwxr-xr-x. 2 root root        24 Mar 29 08:13 data-dir
-rw-r--r--. 1 root root      8495 Mar 29 03:26 Makefile
-rwxr-xr-x. 1 root root 307784472 Mar 29 06:12 nodeos
[root@instance-2 nodeos]#`
