### ISSUE TITLE
Add unit tests for WASM memory OOB access

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#1824]
There is (somewhat surprisingly) no unit tests that check for accessing WASM memory that is out of bounds. While there are ample unit tests that do make sure the invoker wrapper guards OOB memory, we really need to add some WASM only unit tests.

**Comment by taokayan** [comment]
There's a memory wrapping bug which will probably crash the blockchain if triggered.
pull request #2311 created for the fix and adding unittest cases.

**Comment by spoonincode** [comment]
That's a really good find. But I'd also like to see us make sure that pure WASM memory load/stores are also caught correctly before closing this issue. (this can be done in C++ by dereferencing an OOB pointer and load/storing it)

**Comment by taokayan** [comment]
hi, I've committed another fix for the memory boundary check in the wasm case. also added unit test cases for load/store operations with different sizes.

This is my findings:
in the wasm-interpreter case: memory boundary checks for loads/stores are already performed in visitLoad() before calling the actual load() function:

`      Flow visitLoad(Load *curr) {
        NOTE_ENTER("Load");
        Flow flow = this->visit(curr->ptr);
        if (flow.breaking()) return flow;
        NOTE_EVAL1(flow);
        auto addr = instance.getFinalAddress(curr, flow.value);
        auto ret = instance.externalInterface->load(curr, addr);
        NOTE_EVAL1(addr);
        NOTE_EVAL1(ret);
        return ret;
      }

  template <class LS>
  Address getFinalAddress(LS* curr, Literal ptr) {
    auto trapIfGt = [this](uint64_t lhs, uint64_t rhs, const char* msg) {
      if (lhs > rhs) {
        std::stringstream ss;
        ss << msg << ": " << lhs << " > " << rhs;
        externalInterface->trap(ss.str().c_str());
      }
    };
    Address memorySizeBytes = memorySize * Memory::kPageSize;
    uint64_t addr = ptr.type == i32 ? ptr.geti32() : ptr.geti64();
    trapIfGt(curr->offset, memorySizeBytes, "offset > memory");
    trapIfGt(addr, memorySizeBytes - curr->offset, "final > memory");
    addr += curr->offset;
    trapIfGt(curr->bytes, memorySizeBytes, "bytes > memory");
    trapIfGt(addr, memorySizeBytes - curr->bytes, "highest > memory");
    return addr;
  }`

In the wasm-jit case, hardware interrupts are overwritten thus memory access violations are trapped (ref handleHardwareTrap in Runtime.cpp)

**Comment by taokayan** [comment]
It looks like the exception is already thrown in the wavm case, but we can't catch it even with "catch(...)". The malicious contract is:

```
void test_memory::test_outofbound_3()
{
    char *ptr = (char *)malloc(128);
    memset(ptr, 0xcc, 1048576); // heap memory out of bound
}
```

my memory out of bound check is:
```
template<typename T>
inline array_ptr<T> array_ptr_impl (running_instance_context& ctx, U32 ptr, size_t length)
{
   
   MemoryInstance* mem = ctx.memory;
   if (!mem) 
      Runtime::causeException(Exception::Cause::accessViolation);

   size_t mem_total = IR::numBytesPerPage * Runtime::getMemoryNumPages(mem);
   if (length > 1024) printf("array_ptr_impl %d %d mem %d sizeof(T) %d\n", ptr, (int)length, (int)mem_total, (int)sizeof(T));
   if (ptr >= mem_total || length > (mem_total - ptr) / sizeof(T))
   {
      printf("Time for access violation\n");
      Runtime::causeException(Exception::Cause::accessViolation);
   }
   return array_ptr<T>((T*)(getMemoryBaseAddress(mem) + ptr));
}

```

And I can see the output before it crash:
```
array_ptr_impl 3912 1048576 mem 65536 sizeof(T) 1
Time for access violation
unknown location:0: fatal error: in "api_tests/memory_tests": memory access violation at address: 0x2007fffff: non-existent physical address

```

**Comment by taokayan** [comment]
test passed:

    Test case "api_tests/memory_tests" has passed with:
      23 assertions out of 23 passed
