### ISSUE TITLE
eosiolib malloc() returning malaligned pointers

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#1825]
`std::max_align_t` is 16 in our contracts, so per spec malloc() should return pointers aligned to 16 bytes.

**Comment by andriantolie** [comment]
@spoonincode is this already done?

**Comment by spoonincode** [comment]
No, this was not done. I think it's probably a candidate when we move to clang6/7 because we need to optimize the malloc implementation there anyways.

**Comment by andriantolie** [comment]
Got it. Thanks for the confirmation!

**Comment by brianjohnson5972** [comment]
@spoonincode @larryk85 Is this still an issue with cdt, or can this be closed and marked OBE?

**Comment by brianjohnson5972** [comment]
@larryk85 is this still an issue with cdt?

**Comment by brianjohnson5972** [comment]
No longer pertinent to this repo, see CDT #[235](https://github.com/EOSIO/eosio.cdt/issues/235)
