### ISSUE TITLE
Reading sample "currency" contract balance returns empty rows

### ISSUE THREAD

**Issue by CharlesJu1** [EOSIO/eos#1827]
I built the master on Ubuntu 16.04. I was able to generate blocks, create currency account, create currency, issue currency, transfer currency  to eosio account. 

The issue is the account table in both eosio and currency has empty rows.

cju@ubuntu-16-04:~/eos-master/eos/build/programs/cleos$ ./cleos push action currency transfer '{"from":"currency","to":"eosio","quantity":"30.0000 CUR","memo":"my 2 transfer"}' --permission currency@active
3370617ms thread-0   main.cpp:935                  operator()           ] Converting argument to binary...
{
  "transaction_id": "efd7b38fdfdc5e55a28d011cc8c9051bfd607c190102351e754689e0ed59df46",
  "processed": {
    "status": "executed",
    "id": "efd7b38fdfdc5e55a28d011cc8c9051bfd607c190102351e754689e0ed59df46",
    "action_traces": [{
        "receiver": "currency",
        "act": {
          "account": "currency",
          "name": "transfer",
          "authorization": [{
              "actor": "currency",
              "permission": "active"
            }
          ],
          "data": {
            "from": "currency",
            "to": "eosio",
            "quantity": "30.0000 CUR",
            "memo": "my 2 transfer"
          },
          "hex_data": "0000001e4d75af460000000000ea3055e09304000000000004435552000000000d6d792032207472616e73666572"
        },
        "console": "transfer\n",
        "region_id": 0,
        "cycle_index": 0,
        "data_access": [{
            "type": "write",
            "code": "currency",
            "scope": "currency",
            "sequence": 3
          },{
            "type": "write",
            "code": "currency",
            "scope": "eosio",
            "sequence": 1
          },{
            "type": "read",
            "code": "currency",
            "scope": "........edeo3",
            "sequence": 2
          }
        ]
      },{
        "receiver": "eosio",
        "act": {
          "account": "currency",
          "name": "transfer",
          "authorization": [{
              "actor": "currency",
              "permission": "active"
            }
          ],
          "data": {
            "from": "currency",
            "to": "eosio",
            "quantity": "30.0000 CUR",
            "memo": "my 2 transfer"
          },
          "hex_data": "0000001e4d75af460000000000ea3055e09304000000000004435552000000000d6d792032207472616e73666572"
        },
        "console": "",
        "region_id": 0,
        "cycle_index": 0,
        "data_access": []
      }
    ],
    "deferred_transactions": []
  }
}

cju@ubuntu-16-04:~/eos-master/eos/build/programs/cleos$ ./cleos get table eosio currency account{
  "rows": [],
  "more": false
}

cju@ubuntu-16-04:~/eos-master/eos/build/programs/cleos$ ./cleos get table currency currency account
{
  "rows": [],
  "more": false
}

Why the rows are empty?

**Comment by jeremi** [comment]
It is a bug in the get table code.
It is reported in #1742.

**Comment by heifner** [comment]
Fixed by #1874. Closing.
