### ISSUE TITLE
ubuntu eos build error

### ISSUE THREAD

**Issue by shinjae1234** [EOSIO/eos#1833]
Hello.

The following error occurred during EOS processing :

-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: EOS_LIBBSONCXX-NOTFOUND
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: EOS_LIBMONGOCXX-NOTFOUND
-- Doxygen found.  Contract documentation will be generated.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EOS_LIBBSONCXX
    linked by target "db_plugin" in directory /home/shin/eos/plugins/db_plugin
EOS_LIBMONGOCXX
    linked by target "db_plugin" in directory /home/shin/eos/plugins/db_plugin

-- Configuring incomplete, errors occurred!
See also "/home/shin/eos/CMakeFiles/CMakeOutput.log".

Is there a good solution?

**Comment by bytemaster** [comment]
Builds on our nightly build of Ubuntu.

**Comment by ericiles** [comment]
I was able to reproduce on the DAWN-2018-02-14 tag. The issue is resolved on the dawn-2.x branch. I'd suggest using that instead of the DAWN-2018-02-14 tag.

**Comment by xu10000** [comment]
the same problem in DAWN-2018-02-14 tag:

-- Found Git: /usr/bin/git (found version "2.15.1") 
-- Git commit revision: bcb5bf75
-- Git commit revision: bcb5bf75
-- Found Intl: /usr/include  
-- Git commit revision: bcb5bf75
-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: EOS_LIBBSONCXX-NOTFOUND
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: EOS_LIBMONGOCXX-NOTFOUND
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- Doxygen found.  Contract documentation will be generated.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EOS_LIBBSONCXX
    linked by target "db_plugin" in directory /home/xzt/bk/eos/plugins/db_plugin
EOS_LIBMONGOCXX
    linked by target "db_plugin" in directory /home/xzt/bk/eos/plugins/db_plugin

I run ./build.sh ubuntu full, so confuse.
