### ISSUE TITLE
cleos push message not available

### ISSUE THREAD

**Issue by CharlesJu1** [EOSIO/eos#1836]
I compile the master code.  After I deployed the sample hello contract, I run the cleos push message command and got the following error:

cju@ubuntu-16-04:~/eos-master/eos/build/programs/cleos$ ./cleos push message currency hello '"abcd"' --scope currencyERROR: RequiredError: Subcommand required
Push arbitrary transactions to the blockchain
Usage: ./cleos push SUBCOMMAND

Subcommands:
  action                      Push a transaction with a single action
  transaction                 Push an arbitrary JSON transaction
  transactions                Push an array of arbitrary JSON transactions

What is the command to send message to a contract?

**Comment by jgiszczak** [comment]
`message` has been renamed `action`.  Documentation will be updated shortly.
