### ISSUE TITLE
After building, can't find start_npnode.sh

### ISSUE THREAD

**Issue by wengjunxiao** [EOSIO/eos#1838]
after building I can't find file "start_npnode.sh" in ~/eos/build/script
the files in the above folder are below, do sb know why?

> CMakeFiles          abi_is_json.py      eosio-tn_down.sh
> CTestTestfile.cmake cmake_install.cmake eosio-tn_roll.sh
> Makefile            eosio-tn_bounce.sh  eosio-tn_up.sh

**Comment by jgiszczak** [comment]
The `start_npnode.sh` script is only available in Dawn 2.x tags.  Follow only one section of instructions in the Readme.  Do not mix instructions for connecting with the public testnet with instructions for working with a local node.
