### ISSUE TITLE
Require checking alignment for all pointer and reference types through wasm interface.

### ISSUE THREAD

**Issue by larryk85** [EOSIO/eos#1840]
Ensure that all pointers passed to wasm interface from wasm side are properly aligned.

**Comment by andriantolie** [comment]
Can we have ATC for this?

**Comment by larryk85** [comment]
ATC: Given a program with pointers that are not aligned to the native alignment, then no errors will occur and only warnings should be seen to notify the user of the copy/slowpath.  The aligned_ref*/aligned_ptr* wasts should be testing this behavior.

**Comment by taokayan** [comment]
Looks like the related test cases are passed:

    Test case "wasm_tests/misaligned_tests" has passed with:
      7 assertions out of 7 passed
