### ISSUE TITLE
Remove tests/code for chain configuration median calculation

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1850]
Determining chain configuration from producer votes is now in the domain of the system contract.

As such we have a lot of unused code that causes maintenance hassles and should probably be removed:

plumbing:
https://github.com/EOSIO/eos/blob/1a8bfeca993024f9a7624fc94b05a8bb648fadee/libraries/chain/chain_config.cpp#L14-L41
https://github.com/EOSIO/eos/blob/1a8bfeca993024f9a7624fc94b05a8bb648fadee/libraries/chain/include/eosio/chain/chain_config.hpp#L39

tests: 
https://github.com/EOSIO/eos/blob/1a8bfeca993024f9a7624fc94b05a8bb648fadee/tests/tests/misc_tests.cpp#L48-L77

There is potentially more.

**Comment by andriantolie** [comment]
I did a global search and the method to determine median is not there anymore. I'm closing this issue
