### ISSUE TITLE
DAWN-511 ⁃ Improving Error Message in CLEOS (EOSC)

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1858]
When using eosc, often times the error message being thrown are not descriptive and helpful for the user to understand what's wrong.

Analysis has been done on various cases using eosc that results in an error https://docs.google.com/spreadsheets/d/1ccnjnDbImkLaEG4qjD6VdjTJjwd5RRZPaGBp04rRqII/edit#gid=83425241

Based on this analysis, we can categorize the errors into
1. Error that is being thrown by eosc itself
2. Error that is received from RPC API call

For each respective error, the following solution is proposed:

* Error that is being thrown by eosc itself
Catch error that is being thrown by eosc and display proper message
* Error that is received from RPC API call
a. In eosd, add more specific exception for each error thrown inside eosd that is treated as general exception
b. change the error response RPC API call from
```
{
  "code": 500,
  "message": "Internal Service Error",
  "details": "3110000 unknown_block_exception: unknown block\nCould not find block: 0\n    {\"block\":\"0\"}\n      chain_plugin.cpp:388 get_block"
}
```

to
```
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": "3110000",
    "message": "Could not find block: 0",
    "details": "chain_plugin.cpp:388 get_block"
  }
}
```

**Comment by andriantolie** [comment]
This is supposed to be parent class of DAWN-512 and DAWN-513. Since DAWN-512 is already closed and DAWN-513 now stands as a separate issue (not subtask), I'm going to merge this ticket with DAWN-513 (#1860).
