### ISSUE TITLE
DAWN-513 ⁃ Improving CLEOS Error Message: error that is received from RPC API Call

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1860]
More general explanation can be found inside the parent task's description (DAWN-511)

Make the error response thrown by RPC API call to be more consistent, currently there are 3 styles of them:
1. No error code => {"code": ..., "message": ..., "details": "...." }
2. Error code in front => {"code": ..., "message": ..., "details": "<errorCode> ...." }
3. Error code in the middle with bracket => {"code": ..., "message": ..., "details": ".... (<errorCode>) ...." }

Therefore, we plan to make the error response to be more consistent, to be in the following format:

```
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": "3110000",
    "message": "Could not find block: 0",
    "details": "chain_plugin.cpp:388 get_block"
  }
}
```

For that the following actions will be done:
1. Add missing error code 
2. Ensure unique error code for each type of exception
3. Ensure the wording of error makes sense
4. Group error code based on the type
5. Properly format the error code inside the respective xxx_api_plugon

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

[~andrianto.lie] can we please have story point estimation added to this?

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

Story point estimation added

**Comment by andriantolie** [comment]
**# Description for DAWN-511 is**

When using eosc, often times the error message being thrown are not descriptive and helpful for the user to understand what's wrong.

Analysis has been done on various cases using eosc that results in an error https://docs.google.com/spreadsheets/d/1ccnjnDbImkLaEG4qjD6VdjTJjwd5RRZPaGBp04rRqII/edit#gid=83425241

Based on this analysis, we can categorize the errors into
1. Error that is being thrown by eosc itself
2. Error that is received from RPC API call

For each respective error, the following solution is proposed:


* Error that is being thrown by eosc itself
Catch error that is being thrown by eosc and display proper message
* Error that is received from RPC API call
a. In eosd, add more specific exception for each error thrown inside eosd that is treated as general exception
b. change the error response RPC API call from
```
{
  "code": 500,
  "message": "Internal Service Error",
  "details": "3110000 unknown_block_exception: unknown block\nCould not find block: 0\n    {\"block\":\"0\"}\n      chain_plugin.cpp:388 get_block"
}
```


to
```
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": "3110000",
    "message": "Could not find block: 0",
    "details": "chain_plugin.cpp:388 get_block"
  }
}
```

**Comment by andriantolie** [comment]
ATC:
- Ensure that the error message returned by cleos is now following the new format, i.e.
![screen shot 2018-01-24 at 3 47 49 pm](https://user-images.githubusercontent.com/6541441/38046869-bedf0962-328e-11e8-853a-f5afb868b78d.png)

**Comment by andriantolie** [comment]
Yes, that's the right format for "push action". 
Previously, the old format just shows everything unorganized (dump of the errors) displayed in red color.

The new format is the error message displayed in three (optionally four) sections:
- Red - telling "what" is the error
- Green - giving advice on how to fix the error
- Yellow - give a more detailed explanation 
- White - show stack trace (only if -v option is used)
