### ISSUE TITLE
Support?

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eos#1863]
I realise that github issues are intended for reporting bugs or proposing improvements to the software and not as a form of support, however, I seem generally unable to join the Telegram group offered on the EOS website.  when I click the link Telegram pops up and offers me the chance to "Delete and exit" instead of joining the channel.  I joined the quite completely useless Facebook page to ask for help but none has been forthcoming

so I ask? where is the developer community? are you guys on IRC? Gitter? Slack?  where do I get to ask questions about EOS?

and is there someone that can fix my issue with Telegram?

finally, where is a good place to start in learning how to write a smart contract?  I've perused through the Doxygen documentation but find it terse and most unhelpful.  I don't want to run a node locally so most of the documentation on this repo is of no use (I will likely run in a Docker container) so what I'm interested in learning is how to compile/deploy a smart contract and a tutorial for the supported features of smart contracts.  a Hello World app would be nice.  I find no such thing anywhere

**Comment by bytemaster** [comment]
We are working on getting enough support for stack exchange, documentation will be a major part of our efforts the next couple of months.

**Comment by ekkis** [comment]
hei Dan.  what about the Telegram group? that's a place for devs to congregate no?  where do I ask questions?

**Comment by spartucus** [comment]
@ekkis [EOS Developers](https://t.me/joinchat/EaEnSUPktgfoI-XPfMYtcQ) Telegram

**Comment by ekkis** [comment]
@spartucus a million thanks.  I was able to join it.  excited to start finding my way around
