### ISSUE TITLE
Restore tests that were removed to get Jenkins builds working again

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#1868]
ATC

In a build that includes the mongodb, run the unit tests and ensure that nodeos_run_test-mongodb test is enabled and passes:
cd build
ctest

**Comment by gleehokie** [comment]
See commit 2a235da4ecb55cd2e36e49bb5584cad098fa6a1f

**Comment by PaulCalabrese** [comment]
The mongo test is still suffering intermittent failures. I have determined the cause of this and it is related to the design of the launcher/test and am discussing changes to fix this.

The basic problem is that the mongo options passed to the launcher (via --nodeos) are being passed to each node the launcher starts. In this test that means node_00 and node_bios are both starting the mongo plugin and race conditions between them can put the mongodb in a bad state and the test fails.

**Comment by PaulCalabrese** [comment]
ATC

In a build that includes the mongodb, run the unit tests and ensure that nodeos_run_test-mongodb test is enabled and passes:
cd build
ctest

**Comment by brianjohnson5972** [comment]
Verified that mongodb script is running and passing.  It is turned on for all jenkins build and passes.
