### ISSUE TITLE
Look into using Posit numbers to provide floating point operations

### ISSUE THREAD

**Issue by nathanhourt** [EOSIO/eos#187]
Posit is a new format for storing and manipulating reals in binary representation. It is gaining traction and seems likely to be supported by major hardware manufacturers as an upgrade to IEEE 754 floating point numbers in the future.

Information about posits:
https://www.youtube.com/watch?v=aP0Y1uAA-2Y
http://web.stanford.edu/class/ee380/Abstracts/170201-slides.pdf

**Comment by bytemaster** [comment]
Here is an implementation (missing addition) in c++
https://github.com/libcg/bfp

Here is the white paper about it:
http://www.johngustafson.net/pdfs/BeatingFloatingPoint.pdf

**Comment by jgiszczak** [comment]
OBE.  Now using Berkeley softfloat.
