### ISSUE TITLE
DAWN-394 ⁃ Port slow tests

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1870]

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

After discussed with Bart today, this unit test is obsolete. Let's make a PR to remove this file

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

PR Made https://github.com/EOSIO/eos/pull/1664

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

This task is now handled by  #1639

**Comment by taokayan** [comment]
I remember this is obsolete after discussed with Bart & Andri. Can we close this?

**Comment by coreylederer** [comment]
It does appear that #1639 obsoleted this
