### ISSUE TITLE
DAWN-393 ⁃ Port table abi test

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1871]

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

https://github.com/EOSIO/eos/pull/1664 PR made

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

This task is now handled by  #1639

**Comment by taokayan** [comment]
I think this is obsolete after discussing with Bart & Andri. Please see https://github.com/EOSIO/eos/pull/1664
