### ISSUE TITLE
DAWN-386 ⁃ port special tests

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1872]
https://github.com/EOSIO/eos/pull/1600

ATC:
Verify tests pass on all platforms

**Comment by taokayan** [comment]
hi I've made another commit for this. Please check https://github.com/EOSIO/eos/pull/1600 
This is what I got from my laptop:

build jiaendu$ ./tests/chain_test --report_level=detailed --run_test=special_account_tests
Random number generator seeded to 1522132582
Running 2 test cases...

Test module "Master Test Suite" has passed with:
  2 test cases out of 2 passed
  15 assertions out of 15 passed

  Test suite "special_account_tests" has passed with:
    2 test cases out of 2 passed
    15 assertions out of 15 passed

    Test case "special_account_tests/accounts_exists" has passed with:
      15 assertions out of 15 passed

    Test case "special_account_tests/producers_authority" has passed

**Comment by brianjohnson5972** [comment]
All tests passed on all build variants.
