### ISSUE TITLE
DAWN-387 ⁃ port wallet tests

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1873]
pull request link: https://github.com/EOSIO/eos/pull/1578/

Fix most of the tests cases in wallet tests except transfer related test cases, as the transfer of native contract not working at the moment.

**Comment by blockone-syncclient** [comment]
➤ Jiaen Du commented:

output:

Fredriks-MacBook-Pro:build jiaendu$ ./tests/chain_test --report_level=detailed --run_test=wallet_tests
Random number generator seeded to 1520416798
Running 2 test cases...
3598718ms thread-0   wallet.cpp:180                save_wallet_file     ] saving wallet to file test
3598719ms thread-0   wallet.cpp:180                save_wallet_file     ] saving wallet to file wallet_test.json
3598720ms thread-0   wallet.cpp:180                save_wallet_file     ] saving wallet to file ./test.wallet
3598720ms thread-0   wallet.cpp:180                save_wallet_file     ] saving wallet to file ./test.wallet
3598721ms thread-0   wallet.cpp:180                save_wallet_file     ] saving wallet to file ./test.wallet
3598721ms thread-0   wallet.cpp:180                save_wallet_file     ] saving wallet to file ./test2.wallet
3598722ms thread-0   wallet.cpp:180                save_wallet_file     ] saving wallet to file ./test2.wallet

Test module "Master Test Suite" has passed with:
  2 test cases out of 2 passed
  42 assertions out of 42 passed

  Test suite "wallet_tests" has passed with:
    2 test cases out of 2 passed
    42 assertions out of 42 passed

    Test case "wallet_tests/wallet_test" has passed with:
      13 assertions out of 13 passed

    Test case "wallet_tests/wallet_manager_test" has passed with:
      29 assertions out of 29 passed

**Comment by taokayan** [comment]
I've pushed another change to resolve the merge conflict. Please see https://github.com/EOSIO/eos/pull/1578

All the wallet test cases run successfully in my laptop:

  Test suite "wallet_tests" has passed with:
    2 test cases out of 2 passed
    42 assertions out of 42 passed

    Test case "wallet_tests/wallet_test" has passed with:
      13 assertions out of 13 passed

    Test case "wallet_tests/wallet_manager_test" has passed with:
      29 assertions out of 29 passed
