### ISSUE TITLE
docker run fails

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eos#1875]
in https://github.com/EOSIO/eos/blob/master/Docker/README.md there is an instruction that fails:

`docker run --name nodeos -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh arg1 arg2`

the error it generates is:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"nodeosd.sh\": executable file not found in $PATH": unknown.

arguably `arg1 arg2` are merely exemplary but without them it fails all the same since the script is not found

**Comment by ekkis** [comment]
not surprisingly, the `docker-compose up` fails in the same manner

**Comment by ekkis** [comment]
rather curiously, if I try to inspect the contents of the image:

`docker run --rm --name nodeos -t eosio/eos /bin/sh`

the command:

`# ls`

just hangs.  something else is going on here

**Comment by ekkis** [comment]
however, this shows the file isn't there:

`docker run --rm --name nodeos -t eosio/eos ls /opt/eosio/bin`
> cleos	  eosio-abigen	  eosio-s2wasm	eosiowd  start_nodeos.sh
> data-dir  eosio-launcher  eosiocpp	nodeos

**Comment by ekkis** [comment]
ah.  in comparing `start_nodeos.sh` with the `nodeosd.sh` found in the build directory, I see they're the same.  I don't understand how the file got renamed since the Dockerfile clearly doesn't rename it, but as a fix, we can just fix the documentation to use the correct file name

when I run:
`docker run --rm --name nodeos -t eosio/eos start_nodeos.sh`
I get something like:

> 328432ms thread-0   chain_plugin.cpp:93           plugin_initialize    ] initializing chain plugin
> 328432ms thread-0   http_plugin.cpp:141           plugin_initialize    ] host: 0.0.0.0 port: 8888 
> 328432ms thread-0   http_plugin.cpp:144           plugin_initialize    ] configured http to listen on 0.0.0.0:8888
> 328432ms thread-0   wallet_plugin.cpp:37          plugin_initialize    ] initializing wallet plugin
> 328432ms thread-0   wallet_api_plugin.cpp:112     plugin_initialize    ] 
> *************************************
> *                                   *
> *  --   Wallet NOT on localhost  -- *
> *  - Password and/or Private Keys - *
> *  - are transferred unencrypted. - *
> *                                   *
> *************************************

which seems much happier.  the `docker-compose.yml` will also need to be fixed

**Comment by ekkis** [comment]
the instructions also include:

```
alias cleos='docker-compose exec walletd /opt/eosio/bin/cleos -H nodeos'
cleos get info
```

but that fails too, with: 

> ERROR: No such service: walletd_1

sigh...  the `docker-compose.yml` contains the section:

```
  walletd:
    image: eosio/eos
    command: /opt/eosio/bin/eosiowd
    links:
      - nodeos
    volumes:
      - walletd-data-volume:/opt/eosio/bin/data-dir
```

so the `exec wallet` would run that section, creating a container named `walletd_1`, execute the binary `/opt/eosio/bin/cleos` (I verified it's there) passing it the parameters `-H nodeos`... but the container never gets started

any help would be appreciated

**Comment by ekkis** [comment]
this should fix it: github.com/EOSIO/eos/pull/1878 - I'll let someone else close it once the PR has been accepted

**Comment by peterwillcn** [comment]
1. docker rmi eosio/builder 
2. cd eos/Docker/builder && docker build . -t eosio/builder
3. cd eos/Docker && docker-compose up -d

**Comment by ekkis** [comment]
as you can see from this issue, I simply followed the instructions on the page: https://github.com/EOSIO/eos/blob/master/Docker/README.md and ran into the trouble I've described.  if the 3 steps you indicate are necessary for the README to work, then the document should be edited
