### ISSUE TITLE
DAWN-485 ⁃ Add an escrow contract

### ISSUE THREAD

**Issue by nathanhourt** [EOSIO/eos#188]
Write an escrow smart contract, similar to the one implemented in Steem:
https://steemit.com/sip/@dan/escrow-sip-steem-improvement-proposal
https://github.com/steemit/steem/issues/143

This issue may be best worked either after or in conjunction with #186

**Comment by brianjohnson5972** [comment]
This is very old, and if an escrow contract is desired it will be worked in the contracts repo.
