### ISSUE TITLE
Private Key has invalid prefix

### ISSUE THREAD

**Issue by okluoquan** [EOSIO/eos#1881]
command:
./cleos wallet import 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3

result:
1114848ms thread-0   main.cpp:1008                 main                 ]
Failed with error: unspecified (0)
Wallet not found: default
Request Path: localhost:8888/v1/wallet/import_key, Request Post Data: ["default","5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"]

can anyone help me !

**Comment by okluoquan** [comment]
I have  create default  Wallet  by running  ./cleos wallet create .

**Comment by Justin-ye** [comment]
I have the same bug as you.how to solve it ?

**Comment by wrjicediamond** [comment]
is the problem has been resolved?

**Comment by okluoquan** [comment]
has been resolved.
