### ISSUE TITLE
Link to mongocxx & bsoncxx statically

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#1882]
We ought to be linking to mongocxx and bsoncxx statically. We link to all other support libraries statically (boost, k1 lib, llvm/clang, binaryen, etc). Without linking to it statically prebuilt binaries will be just about pointless as users will have to download and install these libraries manually anyways.

**Comment by taokayan** [comment]
ok in version d6c36336cc8eeb5efa180e15a86780602578864e
Here's the output:

[ 96%] Building CXX object plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/mongo_db_plugin.cpp.o
[ 96%] Linking CXX static library libmongo_db_plugin.a
[ 96%] Built target mongo_db_plugin
[ 96%] Building CXX object programs/nodeos/CMakeFiles/nodeos.dir/main.cpp.o
[ 96%] Linking CXX executable nodeos
[ 96%] Built target nodeos
[ 96%] Building CXX object programs/cleos/CMakeFiles/cleos.dir/main.cpp.o
[ 96%] Building CXX object programs/cleos/CMakeFiles/cleos.dir/httpc.cpp.o
[ 96%] Building CXX object programs/cleos/CMakeFiles/cleos.dir/help_text.cpp.o
[ 96%] Linking CXX executable cleos
