### ISSUE TITLE
make test removes content created by eosio_build.sh

### ISSUE THREAD

**Issue by rbw3821** [EOSIO/eos#1886]
The eosio_build.sh script creates the directory etc/eosio/node_00 and copies genesis.json into it.  When make test is executed, it removes the node_00 directory.  When that directory is removed, nodeos with no parameters will no longer start correctly.  Further, if there was a nodeos running from the build directory at the time the tests are run, when the tests are finished, the running nodeos goes nuts.  Here is an example of the nodeos exception output at the time the 'make test' finishes.

eosio generated block 30912a0b... #280 @ 2018-03-27T15:23:36.000 with 0 trxs
eosio generated block d4bc747b... #281 @ 2018-03-27T15:23:36.500 with 0 trxs
eosio generated block 0f766635... #282 @ 2018-03-27T15:23:37.000 with 0 trxs
1417501ms thread-0   block_log.cpp:50              check_index_read     ] 13 NSt3__18ios_base7failureE: ios_base::clear: unspecified iostream_category error
rethrow ios_base::clear: unspecified iostream_category error: 
    {"what":"ios_base::clear: unspecified iostream_category error"}
    thread-0  block_log.cpp:50 check_index_read
1417501ms thread-0   block_log.cpp:204             read_block_by_num    ] 13 NSt3__18ios_base7failureE: ios_base::clear: unspecified iostream_category error
rethrow ios_base::clear: unspecified iostream_category error: 
    {"what":"ios_base::clear: unspecified iostream_category error"}
    thread-0  block_log.cpp:50 check_index_read
1417502ms thread-0   chain_controller.cpp:559      _generate_block      ] error while producing block
1417502ms thread-0   producer_plugin.cpp:218       block_production_loo ] Got exception while generating block:
13 NSt3__18ios_base7failureE: ios_base::clear: unspecified iostream_category error
rethrow ios_base::clear: unspecified iostream_category error: 
    {"what":"ios_base::clear: unspecified iostream_category error"}
    thread-0  block_log.cpp:50 check_index_read
rethrow
    {}
    thread-0  block_log.cpp:204 read_block_by_num

    {"trace.block":{"previous":"0000011a0f76663592d9be31a8d19ded8178d4b9d9c031895d5820311336bb32","timestamp":"2018-03-27T15:23:37.500","transaction_mroot":"5afa11566a1008761ee1212f7d6a29da757400121e9f223251eede76286c1fac","action_mroot":"ef4776a056e0a2b10eedfb162e0fb67852c356023d05f4af94c94b43a47c70a5","block_mroot":"4397184064e5ef2f2eda549ff160b4724e3d58e1795cc1fbe41a8b3ce3b8b862","producer":"eosio","schedule_version":0,"producer_signature":"EOSJxasgHwfuTBkUi6HrN9hiixqveTxy1W1JErUwDZcTQDnof75ZP6NDfJpeoSxqt2CsoU9iWGqEwK66sDXuk644Ynu4Fqh5E","regions":[{"region":0,"cycles_summary":[[{"read_locks":[],"write_locks":[],"transactions":[{"status":"executed","id":"5afa11566a1008761ee1212f7d6a29da757400121e9f223251eede76286c1fac"}]}],[{"read_locks":[],"write_locks":[],"transactions":[]}]]}],"input_transactions":[]}}
    thread-0  chain_controller.cpp:487 _finalize_block

    {"producer":"eosio"}
    thread-0  chain_controller.cpp:564 _generate_block

    {"when":"2018-03-27T15:23:37.500"}
    thread-0  chain_controller.cpp:501 generate_block
1417502ms thread-0   producer_plugin.cpp:259       block_production_loo ] exception producing block
1418003ms thread-0   chain_controller.cpp:946      validate_block_heade ] head_block_time 2018-03-27T15:23:37.000, next_block 2018-03-27T15:23:38.000, block_interval 500
1418003ms thread-0   chain_controller.cpp:948      validate_block_heade ] Did not produce block within block_interval 500ms, took 1000ms)
1418003ms thread-0   block_log.cpp:50              check_index_read     ] 13 NSt3__18ios_base7failureE: ios_base::clear: unspecified iostream_category error
rethrow ios_base::clear: unspecified iostream_category error: 
    {"what":"ios_base::clear: unspecified iostream_category error"}
    thread-0  block_log.cpp:50 check_index_read
1418003ms thread-0   block_log.cpp:204             read_block_by_num    ] 13 NSt3__18ios_base7failureE: ios_base::clear: unspecified iostream_category error
rethrow ios_base::clear: unspecified iostream_category error: 
    {"what":"ios_base::clear: unspecified iostream_category error"}
    thread-0  block_log.cpp:50 check_index_read

Acceptance Test Criteria:
"make test" does not remove the etc/eosio/node_00 folder.
Any running nodeos is unaffected by the "make test" completion.

**Comment by andriantolie** [comment]
ATC Passes.

Running `make test` doesn't remove the default config folder (which is now `/Users/andrianto/Library/Application Support/eosio` instead of `etc/eosio/node_00`). It also doesn't interfere nodeos that is running in the background.
