### ISSUE TITLE
Extend abi_generator to work with contracts like simple.token/eosio.bios/eosio.tokens

### ISSUE THREAD

**Issue by elmato** [EOSIO/eos#1891]

**Comment by andriantolie** [comment]
Hi @elmato I tried to verify this ticket by checking:
`eosiocpp -g generated.eosio.token.abi eosio.token.hpp`
and
`eosiocpp -g generated.eosio.bios.abi eosio.bios.hpp`
However the generated abi is empty, it looks like the following:
```
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-04-26T06:56:35",
  "types": [],
  "structs": [],
  "actions": [],
  "tables": [],
  "ricardian_clauses": []
}
```
Before I made a false positive judgement, can you verify if I'm missing something when testing this ticket? Thanks!

**Comment by andriantolie** [comment]
I also tried to put 
//@abi action
on top of each function inside eosio.bios but no success

**Comment by taokayan** [comment]
These are the steps to make it work:
1. go to build, run "sudo make install"
2. go to the contract source file folder(doesn't seems to work with different folders): 
for example: "cd /Users/jiaendu/workspaces/eos/contracts/dice"
3. run "eosiocpp -g 1.abi ../dice/dice.cpp"

the resulting 1.abi file will looks as follows:

```
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-04-27T08:29:41",
  "types": [],
  "structs": [{
      "name": "offer",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "owner",
          "type": "account_name"
        },{
          "name": "bet",
          "type": "asset"
        },{
          "name": "commitment",
          "type": "checksum256"
        },{
          "name": "gameid",
          "type": "uint64"
        }
      ]
    },{
...
```
