### ISSUE TITLE
When using eosiocpp -g to generate contract.abi, the ABI file data is empty.

### ISSUE THREAD

**Issue by OuterSpaceTears** [EOSIO/eos#1894]
hpp
`/**
 *  @file
 *  @copyright defined in eos/LICENSE.txt
 */
#include <eosiolib/eosio.hpp>

using namespace eosio;

class communicate_test {
    public:
        struct call {
            account_name caller;

            EOSLIB_SERIALIZE(call, (caller));
        };

        bool apply( account_name contract, action_name act) {
            switch (act) {
                case N(call):
                    on( unpack_action_data<call>() );
                    return true;
            }

            return false;
        }

        void on( const call& c) {
            print(c.caller);
            print("\n");
        }
};

`

abi
`{
  "types": [],
  "structs": [],
  "actions": [],
  "tables": []
}`

@heifner

**Comment by navcsdev** [comment]
@OuterSpaceTears I think you can try #2053 I was successful 😄

**Comment by oasis-eos** [comment]
Now it did not work for eos v1.0.1.

**Comment by yankunsam** [comment]
Have been fixed?

**Comment by dominic-healid** [comment]
I'm getting this issue as well, any solid solution for this? I noticed a lot of users have been experiencing this issue.
