### ISSUE TITLE
follow Helloworld demo, meet this question.

### ISSUE THREAD

**Issue by WildDylan** [EOSIO/eos#1896]
cleos set contract ${account} SmartTrading.wast SmartTrading.abi
Reading WAST...
Assembling WASM...
2030344ms thread-0   main.cpp:1008                 main                 ] Failed with error: Assert Exception (10)
!"error parsing wast": Error parsing WebAssembly text file:
:1:1: expected '('
{
^

**Comment by WildDylan** [comment]
How to know where is wrong

**Comment by gleehokie** [comment]
@WildDylan please clarify what document and section you are looking at.

**Comment by WildDylan** [comment]
uhmmmmmm, sorry, but the document was really really `A mess`...
Why not write 3 guides: 
1. master guide with contract, wallet ...
2. public testnet guide with contract, wallet ...
3. local testnet guide with contract, wallet ...
4. tools and commands difference between 1, 2, 3.

**Comment by strahe** [comment]
@WildDylan 看你是国人, 可以到我们[EOS中文社区](https://eosfans.io/)交流
