### ISSUE TITLE
cli issue

### ISSUE THREAD

**Issue by WildDylan** [EOSIO/eos#1900]
walleos: a lite-client
does `cleos` contain's full functions of `walleos`?

**Comment by gleehokie** [comment]
No.

`cleos` is the command line utility to interface to the blockchain daemon `nodes`.
We are in the middle of renaming `eosiowd` and jumped the gun on changing it to `walleos`.  Continue to use `eosiowd` for now.

**Comment by WildDylan** [comment]
@gleehokie But, when i build eos under dawn 2.x, do not find `walleos` under build folder. Can you provide a guide for MAC OSX, under branch dawn 3.x, with public testnet, with all of eos's cli tools ?

**Comment by gleehokie** [comment]
We're working on dawn-3.x documentation now.  Use `eosiowd` instead of `walleos`.

**Comment by gleehokie** [comment]
I just changed the mentions of `walleos` back to `eosiod` in the wiki.

**Comment by WildDylan** [comment]
Ok, thanks.
