### ISSUE TITLE
README content for building local testnet is incorrect

### ISSUE THREAD

**Issue by rbw3821** [EOSIO/eos#1903]
ATC - describe how to build and set up a local testnet, and update documentation to refer to dawn-2.x readme for using the public testnet.

**Comment by WildDylan** [comment]
yes, same questions. skip the local test, use 
`git checkout dawn-2.x` and use the public testnet. all things correct.
be carefully,  when you use smart contract hello word demo in wiki, you'll get some error. haha.

the document looks like nobody updated.

**Comment by andriantolie** [comment]
ATC Passes
