### ISSUE TITLE
explain some words

### ISSUE THREAD

**Issue by WildDylan** [EOSIO/eos#1904]
What's the `PK` `FK` ref id meaning

**Comment by bytemaster** [comment]
Where is "ref id" you refer to... file, line?

**Comment by WildDylan** [comment]
Thanks for your reply.

https://github.com/EOSIO/eos/wiki/Database%20Schema

WIKI: Database schema

**Comment by gleehokie** [comment]
PK = primary key
FK = foreign key

**Comment by WildDylan** [comment]
@gleehokie thanks, you solved many questions.
