### ISSUE TITLE
What's wrong with it and where to get the error detail information

### ISSUE THREAD

**Issue by WildDylan** [EOSIO/eos#1906]
cleos create account dwallet dylan.os EOS8WPzi8EgrgMUWc3DAECYwTKMb88t1LaiUR2P16PTHmiS7aFPyz EOS5k8Zx5TZV9ZXfPj5aKep1tuBe8nEWwxLGAUwhj9tKQLcCyMxdK
3410981ms thread-0   main.cpp:1008                 main                 ] Failed with error:  (140732912246896)

Request Path: localhost:8888/v1/chain/push_transaction, Request Post Data: {"signatures":[],"compression":"none","data":"2e6a855a00007016a5aeb962000000000000"}

**Comment by WildDylan** [comment]
When create contract, meet this error.

**Comment by gleehokie** [comment]
@WildDylan since you reference "cleos" I assume you are on the master branch, but the master branch is not compatible with testnet2.  See the README.md file that was updated today.

**Comment by WildDylan** [comment]
ok thanks, i will have a look.

**Comment by WildDylan** [comment]
@gleehokie MY BUILD BRANCH WAS DAWN 2.X.

**Comment by gleehokie** [comment]
@WildDylan are you sure?  dawn-2.x branch does not have a `cleos` executable in the programs directory, it is called `eosc` there on the dawn-2.x branch.

**Comment by WildDylan** [comment]
<img width="1085" alt="default" src="https://user-images.githubusercontent.com/2519544/38067975-413f9496-3341-11e8-9e59-0a4de7633647.png">

**Comment by WildDylan** [comment]
<img width="410" alt="default" src="https://user-images.githubusercontent.com/2519544/38068041-89fe9876-3341-11e8-9554-ca363ab04e5b.png">

**Comment by WildDylan** [comment]
<img width="389" alt="default" src="https://user-images.githubusercontent.com/2519544/38068057-9bbd5e12-3341-11e8-83ab-a4195d5d059d.png">

**Comment by WildDylan** [comment]
@gleehokie Please see this photos. ok, now, i want to use the latest readme.md to rebuild my eos under dawn-2.x, how to clean my enviroment. thanks for your reply.

**Comment by gleehokie** [comment]
@WildDylan did you build master (dawn-3.0) previously and do a `make install`?  If so that `cleos` executable is probably left over from that install.

**Comment by WildDylan** [comment]
yep `sudo make install`

**Comment by WildDylan** [comment]
ok, how to remove this, clean my enviroment. thanks, it's may my questions.
