### ISSUE TITLE
DAWN-498 ⁃ Producer Scheduling Delay of 1 Round

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#191]
I haven't reviewed the current implementation but we need to ensure the following properties of producer scheduling.

1. all changes to the "active set" of producers are signaled in the block headers
2. the signaled changes are verified when they are signaled
3. the change does not take effect until the signaled change is marked as irreversible 

These assumptions allow light verifying nodes to use the 2/3 acceptance of handoff to new producers.  Without requiring this delay a light nodes have no protection from rogue producers signaling a bogus active set change.

**Comment by nathanhourt** [comment]
Currently we calculate the next round on the last block of the prior one. Are you saying we should move that up and calculate it 1/3rd of the way through the prior round?

**Comment by thomasbcox** [comment]
cleaning up old assignments

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Kevin Heifner

3 months ago

Nathan:

Currently we calculate the next round on the last block of the prior one. Are you saying we should move that up and calculate it 1/3rd of the way through the prior round?

**Comment by blockone-syncclient** [comment]
➤ Bart Wyatt commented:

I am hijacking this issue to mean we need to write/verify tests that excercise and prove these things

**Comment by andriantolie** [comment]
This has been proved in producer_schedule_tests/producer_schedule_promotion_test. I'm closing this issue
