### ISSUE TITLE
Account details wrong

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eos#1916]
in this document: https://github.com/ekkis/eos#nextsteps the instruction goes:

`./cleos get account currency`

from which I expect something like:

```
{
  "account_name": "currency",
  "eos_balance": "0.0000 EOS",
  "staked_balance": "0.0001 EOS",
  "unstaking_balance": "0.0000 EOS",
  "last_unstaking_time": "2035-10-29T06:32:22",
...
```

but in my case, I get something totally different:

```
{
  "account_name": "currency",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS673P38w2wEtgDeJDhzkCzr9mfYhv6PaDWxruk7YUbANucJpYi6",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS673P38w2wEtgDeJDhzkCzr9mfYhv6PaDWxruk7YUbANucJpYi6",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}
```

which may explain the errors I get described here: https://github.com/EOSIO/eos/issues/1877.  incidentally, I notice that the keys for both 'owner' and 'active' are the same, which seems suspicious.  can anyone help?

**Comment by renguzi** [comment]
I have the same problem...

**Comment by Justin-ye** [comment]
I have the same problem.   the spec should. fix here!!!

**Comment by yanxi-me** [comment]
+1

**Comment by heifner** [comment]
Believe this has been fixed. Reopen if you still see problems.
