### ISSUE TITLE
Fork Database Light Client Validation

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1918]
1. fork database should function as a minimal viable light client and enforce that all non-primary branches are at the very least signed by the proper producer.

2. fork database should track BFT sigs on all blocks and should signal when a block has become irreversible by BFT standards.

3. the fork database should track the active producer set according to the block headers.

**Comment by andriantolie** [comment]
@bytemaster is this done?

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner I know that some of this is implemented.  Is this task complete, or are there pieces still left to implement?

**Comment by wanderingbort** [comment]
Some of it is complete, some of it is on hold, some of it will be part of a systemic refactor managed by @arhag 

This issue can be closed as no longer relevant
