### ISSUE TITLE
Error in handling implicit transactions

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#1919]
Causes the receiver of a singed block summary to abruptly close the connection and try again later.

**Comment by wanderingbort** [comment]
#1920 is an incomplete for the problem at hand.

Right now there is now way from a `block_summary` on a receiving node to know whether a given transaction ID that we don't have is 
 - an un-received transaction from users
 - a deferred transaction from a previous block
 - a deferred transaction that the block in question will generate and retire
 - an on-block action (though we could identify this via heuristic as a hack)

We don't really want to include this discriminating data in the block summary if we can avoid it.

To complicate matters, if the block in question would cause fork DB to swap to a different fork, the query-able state from `chain_controller` may be incorrect of incomplete WRT deferred transaction generation.

**Comment by pmesnier** [comment]
Since the PR #1920 provides a work-around, we can move this to a later RC.

**Comment by andriantolie** [comment]
Hi @pmesnier is this issue still relevant? Thanks

**Comment by pmesnier** [comment]
no, I don't believe it is.
