### ISSUE TITLE
How to inter-blockchain communicate in dawn 3.0?

### ISSUE THREAD

**Issue by OracleChain** [EOSIO/eos#1922]
we find that the struct "generated transaction" for inter-blockchain communication in dawn 2.0 was deleted in the newest version. thus the contract "proxy" failed in the new test net.

the new variable "region" in transaction_header is used to distinguish blockchain, how can we use it to inter-blockchain communicate?

**Comment by andriantolie** [comment]
dawn 3.0 is outdated by now and region is not available anymore. Please open a new issue if you have a similar question with version 1.0. Thanks!
