### ISSUE TITLE
run currency contract error

### ISSUE THREAD

**Issue by qiushaoxi** [EOSIO/eos#1927]
commit d25cf0ce9d4481d37284f6992e3040123e9ea953

error:
when i try to run currency contract.

cleos push action currency issue '{"to":"currency","quantity":"1000.0000 CUR","memo":""}' --permission currency@active
1557521ms thread-0   main.cpp:964                  operator()           ] Converting argument to binary...
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
condition: assertion failed: unable to find key
Request Path: localhost:8888/v1/chain/push_transaction
Request Post Data: {"signatures":["EOSK3e9LWS7DrEEzqxZgTMTyX5V5C1GQnzk6Y4Nv2nuVoG1NYcMq6H1yvnDYbdnzgpz4xibvaJe2f5YKrhsVS8t82azNa8q3g"],"compression":"none","data":"0379bc5a00000908c92eeb950000000000010000001e4d75af460000000000a53176010000001e4d75af4600000000a8ed3232190000001e4d75af468096980000000000044355520000000000"}

**Comment by okluoquan** [comment]
I have resolve it.

before ./cleos push action currency issue   run:

./cleos push action currency create '{"issuer":"currency", "maximum_supply": "1000000000.0000 CUR", "can_freeze": 1, "can_recall": 1, "can_whitelist": 1}' -p currency@active

**Comment by qiushaoxi** [comment]
before ./cleos push action currency issue run:

./cleos push action currency create '{"issuer":"currency", "maximum_supply": "1000000000.0000 CUR", "can_freeze": 1, "can_recall": 1, "can_whitelist": 1}' -p currency@active

**Comment by chenlian2015** [comment]
release number? 

bogon:currency cl$ cleos push action currency create '{"issuer":"currency", "maximum_supply": "1000000000.0000 CUR", "can_freeze": 1, "can_recall": 1, "can_whitelist": 1}' -p currency@active
2889631ms thread-0   main.cpp:964                  operator()           ] Converting argument to binary...
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
size > 0: 
Request Path: localhost:8888/v1/chain/push_transaction
Request Post Data: {"signatures":["EOSKhLaXiSfWTL3ZLBJ7kuFuEhj3U6eXHJgdtwtrDv5pMWQkHFupQJWoKxtkr3fgEc6UFQNJgPSkTWu4oaJuKCi6UykMg4ddz"],"compression":"none","data":"97b3bd5a00004316d4344a430000000000010000001e4d75af4600000000a86cd445010000001e4d75af4600000000a8ed323200"}
