### ISSUE TITLE
Issue of eosiocpp & exchange contract

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eos#1931]
# 1. eosiocpp -g
#### `eosiocpp -o exchange.wast exchange.cpp`
Prominent Issue: `#include_next <float.h>`
[Exchange Contract](https://github.com/EOSIO/eos/tree/master/contracts/exchange)
![image](https://user-images.githubusercontent.com/16319106/38078448-e476eaa6-336e-11e8-9a31-c3c63e3ae32a.png)
'float.h' file not found in libc++
![image](https://user-images.githubusercontent.com/16319106/38078281-56fdee0e-336e-11e8-8256-a217860b653b.png)

# 2. eosiocpp -o
line 74: realpath: command not found
![image](https://user-images.githubusercontent.com/16319106/38078589-647fa436-336f-11e8-8930-f3b2a062556a.png)
![image](https://user-images.githubusercontent.com/16319106/38078865-2e6bbac8-3370-11e8-94f0-63e3168b382a.png)

**Comment by andriantolie** [comment]
I believe contracts inside `contracts` folder is not compatible with eosiocpp, they are compiled using cmake. I'm closing this issue
