### ISSUE TITLE
Issue of eosiocpp -o & abi file

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eos#1933]
1. the structure of abi contains `types`, `structs`, `actions`, `tables`
in side the structs the `base: ""` seems redundant.
![image](https://user-images.githubusercontent.com/16319106/38081545-e2dc193e-3376-11e8-8727-4cd058bac6dd.png)

2. in order to create `action` object in abi file it require to specified `@abi action xx` in the hpp **`struct`** (refers to [EOS wiki](https://github.com/eosio/eos/wiki/Programs-&-Tools#eoscpp) ) this have two problems
2.1 all action must be in struct form, function cannot be generated to abi by eosiocpp
2.2 need to specify on every struct the same `@abi action`, which may be not efficient

Example of 2.1
![image](https://user-images.githubusercontent.com/16319106/38081794-781f3198-3377-11e8-940a-c59c40f008bf.png)

**Comment by elmato** [comment]
1. base just indicates who this type inherits from.
2. this PR #1663 will allow you to indicate `//@abi action` to an instance method, look at https://github.com/EOSIO/eos/blob/3c227b31f06cdbd436932f7a401ceba362033af3/contracts/dice/dice.cpp#L36-L40

**Comment by SheldonHH** [comment]
Great the #1663 has been merged into the master branch !
