### ISSUE TITLE
Error 3030020: Runtime Error Processing WASM

### ISSUE THREAD

**Issue by OuterSpaceTears** [EOSIO/eos#1935]
`feng@feng-B250-HD3P:~/workSpace/eos/build/programs/cleos$ ./cleos set contract currency ../../contracts/hello/hello.wast ../../contracts/hello/hello.abi 
Reading WAST...
Assembling WASM...
Publishing contract...
Error 3030020: Runtime Error Processing WASM
Error Details:
Smart contract's apply function not exported; non-existent; or wrong type
Request Path: localhost:8888/v1/chain/push_transaction
Request Post Data: {"signatures":["EOSKW7J7s6Ru5sDTu5Ze6ti5zfYuygduFL9NR6ArPrz12rAy1oz5QQV5cCuyjyt6ebLN2HxNHWnmn6z6E5vYqCTGkMVEg2t9T"],"compression":"zlib","data":"78da9d564d6fe35414bdcfcf763371d37ae8c7f423d379c9b4cc14a64c92769a16095423056634c32ca642a06edc367645d2240e490313a94ad8b0e177b08015122b90668158b162c5af40e23f709fed89dfb33c498417f6bbf79c7bdfb9c74f96bffbfdd509c0178b177ffdf603f04bf1efff143ec3fbd1d6f7bffc4170b1f169efe78f79fec77f4ba5bf97a2cc9f4b70d66d720ae99ba7da00af21199ed2e160087e381c60e82f785e1fbc5ea9c8408aeec783101afa10c13c19c0a9e2477ecfeba0e775d0f39ae7950152a85fa1fca4ad51b7f5f5b2736ed79c97c5d2817d516b3976bb536b9e75faa07070250676ddaad772384c39bc18c10def1bb773eef55a4e00cd4750f7caebb8003c6b46d95edb39bb7281c4faf4da6da94f28aff4685f96a70bf24660246f4668cb6141de8c208f43813c5590c7b3a13c2dd64790e7f7590aa0fdbd04f36ec958ccbb85111ab76e6e8408cecd8f92a2710b4256f66d2d406cc7eb9d37dc0475d904424ce28a4c89eb5c906141eca28c888a57e2902c5b478dadab16dc88822ea468763d0d041954bc1bb390a1746e5e55491bf04d112033af5259bde936bd4e5f8165fbc4fdeac5d362b1faa55bbdecf69af8028f8b36acddb14f9e3f72bd6ecd2b964239bef84a1faf174ffbb0be11317643463044a5e113b25b11e130248816079dfa707b7bc42b1545dec8e94ab0257237849ee5901b59eef3fac7051bee24f0221b231e9b30a607b9f1637a909f6a4c0fee4e39a687636e6e4e1c93d3b636274ec9696fef8e1ff2f9b17d78517be93af6a5db7ff2acbe5baa542a70af3476f0e4a2fb87d398915cbbfdc174062556e398ef1c4c34ed4da5ef1e4c34f24da50f6e8f33d7819dec181b1d786faad3e3c0c37bd398e3a0a0c2e4b3c369c5c96787d34ada59bbdde8c32eff62549b6dd84b7fabaf1bc080118b997b1563ce5f338551a69af3463a0c4d33425446cd59999891c33939bc298734eaaaca5d4126123954e450334c21b414f3067e1d830406e908450c7beb021d13aa39134fa4e209c3281365688105f715d5322ff3fabea2329da9873435da59b752757329a759804bb3ce199af19010b18ef22c65caeb3aca6b96b1820615c693a47d3e82324d2947e14e7c1f1ce3ad3ceef43803e897be4d53650a86b47359de59f3b38c468a35de473517722ad669619d6a3c4baedba69288b07831af062228d32211ffb3d9ad09cd96c132cd5506e60a9ed05546f0593057d1328a7be4346ca75432a01c51ecbb0390a78cf087fa4986e0a126f51c61c01f80e76258cf2b1998550c839f99cb9c66a065c603152cd5508f8ef0f7d4c283fed86d343cf6b9d76938ef334c3183ee7c88cf82a1a441f8ed855fab09bfbdb362e23fefee01f2"}
`

hello.abi
`{
  "types": [],
  "structs": [],
  "actions": [],
  "tables": []
}`

hello.hpp
`/**
 *  @file
 *  @copyright defined in eos/LICENSE.txt
 */
#include <hello.hpp>

/**
 *  The init() and apply() methods must have C calling convention so that the blockchain can lookup and
 *  call these methods.
 */
extern "C" {

    /// The apply method implements the dispatch of events to this contract
    void apply( uint64_t code, uint64_t action ) {
       eosio::print( "Hello World: ", eosio::name(code), "->", eosio::name(action), "\n" );
    }

} // extern "C"
`

hello.hpp
`/**
 *  @file
 *  @copyright defined in eos/LICENSE.txt
 */
#include <eosiolib/eosio.hpp>

`

**Comment by spoonincode** [comment]
There was a recent change is master, the `apply()` call now has different parameters:

`void apply( uint64_t receiver, uint64_t code, uint64_t action )`

You'll need to update your contract with that.
