### ISSUE TITLE
Serialization for deferred_transaction_request

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eos#1943]
In `libraries/chain/include/eosio/chain/contracts/abi_serializer.hpp`
```
template<typename Resolver, typename... Args>
      static void add( mutable_variant_object &mvo, const char* name, const fc::static_variant<Args...>& v, Resolver resolver )
      {
         //TODO: implement deserialization for static_variant
      }
```
There should be serialization code for either static_variant in general or for fc::static_variant<deferred_transaction, deferred_reference> which we use in apply_context.hpp.

**Comment by andriantolie** [comment]
@moskvanaft is this done?

**Comment by moskvanaft** [comment]
I see implementation in the code.
