### ISSUE TITLE
DAWN-674 ⁃ System contracts are described by Ricardian Contracts.

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1948]
Each call in the eosio.system contract needs to be described by a standalone Ricardian Contract with full legal language and with clear placeholders indicating where variables like ﹍**_from-party_**﹍ and ﹍**_to-party_**﹍ go.

**Some items that we have gathered about proxy voting:**

* There two types of proxies.  One is a general proxy.  A general proxy is written in such a way that it gives the proxy holder the right to vote as he or she sees fit on any business that may come up at a meeting.  A limited proxy includes on the proxy the business that is to be voted on and a place for the member to tell the proxy holder the way to vote on the business.  The proxy holder is legally required to cast the vote the way he has been designated by the member. (5)
* The proxy should include the name of the association, the word proxy under it, and a statement that ____________ is the person’s proxy for the meeting, and then a place for the member to sign and date the proxy.  If the proxy is a limited proxy it would also include any issues that are to be voted on at the meeting and a place for the member to check “yes” or “no” or a place to vote for any candidates being considered for office.   A proxy also may include when it expires. (5)
* In Riddicks Rules of Procedure, it states that “Proxy voting gives the power of attorney to a member to cast the votes for another legal vote holder.” (3)
* In a Guide for Voting, it states that “The word proxy has two meanings.  One meaning is the power of attorney given to another person to act in one’s stead.  The other meaning designates the person who holds the power of attorney.  In corporations it is used to allow those who can not attend meetings to send a proxy to vote for them.” (4)
* The most important rule is that the proxy permission must be in writing (1)
* The proxy form is clear and simple so that the intent of the owner is clear (1)
* When it comes to decision-making in your building, attending meetings in person is always best. But should the need arise, shareholders and unit owners are permitted to vote in board elections and other matters of corporate governance by proxy or absentee ballot. (2)
* Proxies are written statements by a shareholder or unit owner authorizing another person (the proxy holder) to vote his shares or common interests at a shareholders or special meeting. (2)
* Boards often rely upon the collection of proxies to fulfill the quorum requirement at the annual shareholders meeting or any special meetings. (2)
* It's a good idea to remind shareholders or unit owners in writing before the meeting to send in their proxies, if they will be unable to attend, so they can be counted toward the quorum. (2)
* The cardinal rules regarding issuance of a proxy are that the document must be in writing, and it must be dated and signed by the record owner or his attorney in fact. Unless indicated otherwise, the term of a proxy is 11 months from its issuance. If multiple proxies are issued by the same shareholder, the only valid one is that which was issued latest in time. (2)
* Proxies signed by any person other than the owner of record are invalid unless accompanied by documentary evidence such as a duly executed Power of Attorney, Letters Testamentary or Letters of Administration that this person is signing as attorney in fact. (2)
* If the record owner dies or is found incompetent after issuing of a proxy, the proxy is valid unless the association's secretary has been notified in writing prior to the meeting. (2)
* A shareholder or unit owner who changes his mind can issue a new proxy reflecting his revised preference. A proxy can also be revoked by written notice to the association's secretary. Or, a shareholder or unit owner can revoke the proxy by attending the meeting and casting a ballot that reflects the new preference. The ballot will supersede the previously issued proxy; however, merely attending the meeting, without actually casting a ballot, will not serve to revoke the proxy. (2)

* 

**Commonly Stated Problems:**

* There are two big problems [with proxy].  The first is that the members who don’t attend the meeting do not hear the discussion and may have marked their proxy based on misinformation or no information at all.  The second problem is that one person can collect many proxies, and if they are general proxies, can influence the outcome of the vote.  Members are basically giving their rights away to another to decide for them. (5)
* Shareholders and unit owners should be told how the proxy holders intend to vote, so that the issuance of proxies becomes a process of informed consent. (2)
* If the shareholder or unit owner whose proxy is being sought is not comfortable with one or more of the designated proxy holders, he may make the appropriate deletions (initializing the changes) or simply substitute his own designated proxy holder. (2)
* It's important to be aware that pre-dated proxy forms reflecting the day of the meeting or the day before the meeting are sometimes circulated. These proxies are illegal because they curtail the right to revoke a proxy before the meeting. (2)

In its simplest form, a Proxy Voting Authorization could be, but should be very clear as to dates and intent:

{Name of the company or association}
{Date of notice}
I, _______________________ (member), authorize ______________________ (person to represent my vote) to vote ___________________ (my selection on the matter of the vote), on my behalf (in proxy) on the subject of ______________________.
{Date proxy vote counted}
{Date proxy voting expires}

**References:**
(1) https://www.boardeffect.com/blog/board-meeting-proxy
(2) https://cooperator.com/article/voting-by-proxy/full
(3) Floyd M Riddick and Miriam H. Butcher, Riddick’s Rules of Procedure,Maryland: Madison books, page 155
(4) Joyce L. Stephens,  Guide for Voting,  Florida: Fredrick Publishers, 1993  page 51
(5) http://www.parli.com/newsletter/proxy-voting

**Other references:**
http://www.x12.org/forms/member-proxy-authorization-form
https://www.sec.gov/rules/final/ia-2106.htm
https://medium.com/legalthingsone/ricardian-contracts-legally-binding-agreements-on-the-blockchain-4c103f120707

**Comment by thomasbcox** [comment]
On hold pending completion of work on system contract.

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner I am presuming that most of this task has been incorporated and that the remaining uncovered portion is OBE.  If I don't hear from you I will presume that is the case.

**Comment by brianjohnson5972** [comment]
Some of this has been implemented and the rest is OBE (Overcome By Events).
