### ISSUE TITLE
Need Jenkins build that runs debug build

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#1949]
We need to be exercising asserts in at least one of the Jenkins builds.

**Comment by pacificcode** [comment]
Eric and I discussed the procedure below when building with Jenkins.
Does this get you what you are looking for brianjohnson5972?
in eosio_build.sh:
CMAKE_BUILD_TYPE=Release
if [  ! -z $EOS_BUILD_TYPE ]; then
    CMAKE_BUILD_TYPE=Debug
fi

**Comment by brianjohnson5972** [comment]
I think so. I think one Debug build would be fine, probably Ubuntu since it
has tended to have the most turned on tests.

**Comment by brianjohnson5972** [comment]
yes that works

**Comment by pacificcode** [comment]
This issue has been addressed in the build scripts by PR #1984.
