### ISSUE TITLE
Document our "varint" encoding.

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1950]
Previously, we exposed `signed_int` and `unsigned_int` as ABI types which were variable length encoded integers.   We are re-exposing these as part of #353 under the more conventional/descriptive names: `varint32` and `varuint32`.

However, the encoding of these is poorly documented. 

`varint32` is signed and uses [Zig-Zag encoding](https://developers.google.com/protocol-buffers/docs/encoding#signed-integers)

`varuint32` is unsigned and uses [VLQ or Base-128 encoding](https://en.wikipedia.org/wiki/Variable-length_quantity)

**Comment by SheldonHH** [comment]
VLQ is a universal code that uses an arbitrary number of binary octets (8-bits bytes) to represent an arbitrarily large integer.
