### ISSUE TITLE
DAWN-541 ⁃ Rearchitect eosiod into a minimum kernel

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1955]
Rearchitect `eosiod` to start with a 'root' account that can `set code` with contracts that bootstrap the EOS token and producer voting, and create producer accounts, then turn over control to those producer accounts.  Rate limiting remains in `eosiod` C++ code.

**Comment by andriantolie** [comment]
This is the current behaviour of eosio, so this ticket looks done. I'm closing this issue
