### ISSUE TITLE
DAWN-543 ⁃ DB API for String Key Table Interface inside db.h doesn't match the implementation inside wasm_interface.cpp

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1956]
DB API for String Key Table Interface inside db.h doesn't match the implementation inside wasm_interface.cpp, which cause unresolvable exception to be thrown. This includes:

* store_str
* update_str
* next_str
* previous_str
* lower_bound_str
* upper_bound_str
* remove_str
back_str and front_str still matches.

Furthermore, I notice the following lines of code in the implementation of db_api inside wasm_interface.cpp

```
      char* record_data =  ((char*)data) + sizeof(KeyArrayType);
      size_t record_len = data_len - sizeof(KeyArrayType);
```

Won't this cause problem for string key table? Since KeyArrayType of string key table is std::string[1] and sizeof(std::string[1]) will just return the size of the pointer to the data. If that's the case, I think we should make a JIRA ticket to make an implementation for string key table in wasm_interface.cpp.  Pardon me if I misunderstand things here.

**Comment by elmato** [comment]
That interface has been completely removed in favor of the multi_index API.
