### ISSUE TITLE
STAT-103 ⁃ Automated Doxygen Generation and Publishing

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#196]

**Comment by heifner** [comment]
Is this complete or does this issue include work to publish the doxygen to a public accessible location?

**Comment by jgiszczak** [comment]
So far as I know it's still desirable to publish the doxygen output somewhere.  I don't know where that should or could be.  Not my department.  Not entirely sure how, either.  I assume we want a controlled location, so something like Travis would have to have credentials stored somewhere, but I don't know anything about Travis.

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

Travis includes the ability to store data in encrypted form in the travis.yml file, so WordPress credentials could be stored securely for documentation publication purposes.

See https://docs.travis-ci.com/user/encryption-keys/

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

Per Dan and the discussion at the end of STAT Sprint 2, documentation destination is [eos.io/docs/](http://eos.io/docs/)

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

I was under the impression for STAT it was: https://eosio.github.io/eos/
Basically, undo what you did originally a few months back.

[~admin] Are we pushing to a wordpress site: eos.io/docs/
OR are we pushing to github pages: https://eosio.github.io/eos/

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

It was my understanding that was a temporary get-it-done-right-now solution to get the documentation back online, in answer to Dan's urgency, but that would not be the last place.  Instead, the github page would simply link (and maybe even automatically forward) to eos.io/docs/.

**Comment by blockone-syncclient** [comment]
➤ David Moss commented:

[~kevin.heifner] [~jonathan.giszczak] Github pages for now so we have them available. We will set up an eos.io/docs (or docs.eos.io) site when we get approval for the AWS account.

**Comment by blockone-syncclient** [comment]
➤ Thomas B. Cox commented:

We will push Doxygen and publish non-Doxygen documentation on a comprehensive Wordpress site. This is on hold pending AWS approval by Andrew.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

Assigned this back to Jonathan. I was thinking of a diff issue when I said Romeo was working this.

**Comment by blockone-syncclient** [comment]
➤ Thomas B. Cox commented:

Looks like Wordpress is out-of-scope for 04-Dec timeframe, so we'll 

  1. Generate the Doxygen
  2. Check the docs in
  3. make the Doxygen files available via a link

**Comment by blockone-syncclient** [comment]
➤ Thomas B. Cox commented:

Standard for Doxygen: 

  1. It's for low level API docs, 
  2. It's in GITIGNORE until time for a release; 
  3. It's added to a Git distro only when we release; 
  4. Users who want access to Doxygen output should go to the online copy we're constantly updating.

**Comment by heifner** [comment]
Generated Dawn 2.0 doxygen.
