### ISSUE TITLE
Sometimes producer_plugin crashes on exit

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#1961]
The timer in producer_plugin seems to be doing something that causes it to crash on exit sometimes. This is most noticeable when nodeos decides to exit on its own (like due to a bad config option or such).

**Comment by spoonincode** [comment]
https://github.com/EOSIO/appbase/pull/17

**Comment by andriantolie** [comment]
Can we have ATC for this?

**Comment by gleehokie** [comment]
@andriantolie 

ATC: verify that nodeos does not crash on exit after an error on startup.  Notes the cases described in the description for this issue and the linked issue.

**Comment by andriantolie** [comment]
ATC Passes.
Tested throwing an exception inside chain_plugin::plugin_startup by specifying invalid key inside genesis.json. Breakpoint inside appbase shutdown() is reached
