### ISSUE TITLE
Test that Producers can Update System Contract

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1962]
This test needs to verify that the entire system contract can be replaced via the eosio.msig contract.

Each producer should individually vote to approve it.

Do not use a simple system contract, use a "big" wasm.

**Comment by taokayan** [comment]
hi, I've created the test case in https://github.com/EOSIO/eos/pull/3100 . And I found that the authorisation link between eosio and eosio.prods need to be setup at the beginning in order to make it work:

```
   set_authority(N(eosio), "active", authority(1, 
      vector<key_weight>{{get_private_key("eosio", "active").get_public_key(), 1}}, 
      vector<permission_level_weight>{{{N(eosio.prods), config::active_name}, 1}}), "owner", 
      { { N(eosio), "active" } }, { get_private_key( N(eosio), "active" ) });
```

**Comment by gleehokie** [comment]
@moskvanaft I think you implemented a similar test case using the system contract, please reference it here.
