### ISSUE TITLE
Default Genesis 

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1963]
By default we should create genesis if one is not found in the config dir. The values for the default genesis should be available in config.ini.

The purpose of the genesis file is to make sure that all nodes start with the same config,  the config.ini can be useful to help create new blockchains without making users find, edit, copy, etc a genesis.json file.

**Comment by cppfuns** [comment]
How to create the default genesis.json, remember that DAWN 4.0 will automatically create under ~/.local/eosio/nodeos/config

**Comment by andriantolie** [comment]
`--extract-genesis-json` or `--print-genesis-json` in your nodeos to get your default genesis. The default genesis is now not written in a file by default

**Comment by cppfuns** [comment]
root@ip-172-31-25-86:~/.local/share/eosio/nodeos/config# nodeos --extract-genesis-json
547431ms thread-0   main.cpp:119                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_command_line_syntax> >
std::exception::what: the required argument for option '--extract-genesis-json' is missing

**Comment by jgiszczak** [comment]
Per the error message, you need to provide an argument to the `--extract-genesis-json` option.  The argument is a filename.  Use `--extract-genesis-json genesis.json`.
