### ISSUE TITLE
Change wallet daemon executable name from `eosiowd` to `keosd`

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#1968]
`keosd` is a play on words, it's a wallet daemon that stores EOS security keys.  We started with `keyeosd` but it was hard to pronounce (key-eos-dee) so we dropped the "ey" and ended up with `keosd` which phonetically has both "key" and "eos" in the word.  Yes, we're nerds.  🤓

**Comment by grock999** [comment]
lol

**Comment by spartucus** [comment]
@gleehokie And how to pronounce `keosd` ?

**Comment by gleehokie** [comment]
It is pronounced key-os-dee.

**Comment by andriantolie** [comment]
Did a global search, and verified that no more reference to eosiowd
