### ISSUE TITLE
Replace transaction_mroot with transaction_schedule_mroot

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#1972]
Right now the block header (which is signed by producers) does not commit to the transaction schedule defined in in the vector of `region_summary` (see field `region` in `signed_block_summary`). 

We may be indirectly committing to the schedule (at least partially) via the `action_mroot`, but there are potential malleability vulnerabilities involved with that approach which are hard to analyze. Furthermore, a light client cannot validate whether the transaction schedule of the `signed_block` was actually signed by the producer because it is not possible to validate `action_mroot` without actually apply the block (which requires state).

The most straightforward way for a producer to commit to a particular schedule is to commit to the digest of the vector of `region_summary` in the block header. Instead of including another digest into the block header, we can instead concatenate that digest with the `transaction_mroot`, take a hash of that, and put that resulting digest in the block header in place of the existing `transaction_mroot`. This way, we do not increase the size of the block header and still provide small proofs (only one extra digest needed in the proof) to anyone who wants to verify that a particular transaction was included in the `input_transactions` of some block.

So to recap, we would have the following digests in the `block_header`:

- `previous` remains the same. It is still the block id of the previous block in the blockchain.
- `block_mroot` remains the same. This is something that can be validated without database state, but the entire blockchain (or at least block ids) up to the block that one is validating is necessary.
- `action_mroot` remains the same. However, perhaps the data we currently commit to in the leaf nodes of the merkle tree may need to be modified if they do not allow us to prove all the things we care about proving; but that is a task for another issue). Validating `action_mroot` require applying the entire block and therefore requires the entire database state.
- `transaction_schedule_mroot` which is Hash(Hash(`regions`) || `transaction_mroot`). `transaction_mroot` is the root of the Merkle tree over `input_transactions`.

A light client validator with access to just the chain of `signed_block_header`s would be able to validate all fields of the head `signed_block_header` of the chain except for `transaction_schedule_mroot` and `action_mroot`. A validator with access to the entire blockchain would be able to validate (without actually applying any blocks nor having access to database state) all fields of the `signed_block_header` of the head block of the chain except for `action_mroot`.

**Comment by arhag** [comment]
There have been changes to the definition of `transaction_mroot` (or `transaction_schedule_mroot`) described at the top of this issue.

The objective of `transaction_mroot` (will not be renamed to `transaction_schedule_mroot` anymore) is still the same: 
* to commit to the set of input transactions included in the block;
* to commit to the particular schedule of transactions processed for the block (whether they are input transactions or deferred transaction);
* to commit to certain metadata about the processed transactions (that are not available in the actual data of the `transaction`s) which previously was just their status, but is now also the amount of CPU usage (`kcpu_usage`) and network bandwidth usage (`net_usage_words`) that was billed for processing the transaction;
* and finally, to do this in such a way that a node with access to the full blockchain would be able to validate the integrity of a new `signed_block` received from the network (in particular to know that all the data inside of `signed_block` was signed off by the producer key recovered from the signature in the `signed_block_header` in a way that cannot be meaningfully manipulated my a man-in-the-middle, and to be able to validate all fields in the `signed_block_header` except for `action_mroot` without having to actually apply the block and process all the transactions within.

The `transaction_mroot` is now a root of a Merkle tree over commitments for each region processed in the block ordered in ascending region id order. These commitments for each region are themselves roots of another Merkle tree (this indirection is to allow parallel computation of these region roots). A region root is the root of a Merkle tree over commitments of all the shards within that region ordered in a particular order (all commitments to shards in one cycle must come before the all commitments to shards in a later cycle within that region). These shard commitments are themselves roots of another Merkle tree (this indirection is to allow parallel computation of these shard roots). A shard root is the root of a Merkle tree over commitments of all transactions processed within that shard ordered in the order the transactions were processed in the shard. These transaction commitments are either the digest of the `transaction_receipt` concatenated with another digest of the `packed_transaction` associated with the processed transaction and included in the `input_transactions` field of the `signed_block` (if the transaction was an input transaction) or they are just the digest of the `transaction_receipt` (if the transaction was not an input transaction, which includes implicit transactions).

**Comment by andriantolie** [comment]
Can we have ATC for this?

**Comment by andriantolie** [comment]
Additional Unit Test for this ticket is added https://github.com/EOSIO/eos/pull/2271
