### ISSUE TITLE
Run All Chain Tests work on both Producer and Validator Nodes

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1973]
Just because a transaction sequence works on a "sole producer" node, does not mean that the resulting block will validate if pushed to another node. A recent example of this discovered that scopes on the shard failed checks after-the-fact that passed during generation.

We have a tester framework, this tester framework needs to create "two chains".  Every time a block is produced on the main chain, it needs to be copied and pushed to the second chain. The two chains should be identical.

Unit testers should not see this behavior as it should all be behind the scenes of the tester.

**Comment by gleehokie** [comment]
@andriantolie 

ATC: 

1) verify that both chains running properly and that blocks being produced on the main chain are pushed to the secondary chain
2) verify that blocks are accepted and are valid on the second chain
3) verify that the scopes on the shard (see description) are valid

**Comment by brianjohnson5972** [comment]
@gleehokie the ATC seems to be more what the code review should have verified.  This issue was for a unit test to perform those things, so not sure why we are testing things that the unit test should perform.

**Comment by gleehokie** [comment]
@brianjohnson5972 I struggled myself with an ATC for this one.  What I wrote essentially says "make sure it is doing what was intended", to verify the one problem case that was documented in the description no longer happens and to verify all of this happens correctly from a functional test point of view versus code review.  Tpfft.

**Comment by andriantolie** [comment]
This issue is already validated by validating_tester, which is the default tester when NON_VALIDATING_TEST macro is not specified. Since running chain_test with no NON_VALIDATING_TEST macro specified passes, the solution to this issue is verified to be working.
