### ISSUE TITLE
Unit Tests for simple.token contract 

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1976]
This is an example contract, we should verify that it works.

**Comment by WildDylan** [comment]
@bytemaster here are some questions, simple.token example was a class named `simpletoken`, without apply function. how to use ? can you explain me .

**Comment by wanderingbort** [comment]
Example contracts need to be curated and validated in the CDT repo or another more appropriate repo.  This issue will be migrated to that repo when that happens.
