### ISSUE TITLE
Build a resiliency testing network using tools like Chaos Monkey 

### ISSUE THREAD

**Issue by coreylederer** [EOSIO/eos#1978]
Imaging a service that uses a tool like Chaos Monkey (or similar) that every so often changes the block producer lineup for just a round or two, requiring standby producers to step up and be real producers for a few minutes. The idea is to routinely exercise the failover logic and the failover human practices.

**Comment by jgiszczak** [comment]
Jungle Testnet effectively does this as a matter of course.  Also #5545 added automated tests for the fork recovery code.

**Comment by brianjohnson5972** [comment]
Team at Blacksburg is pursuing their own testing strategy.
