### ISSUE TITLE
Trouble with large txns or large blocks propagating

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#1983]
I'm having trouble with either large txns or large blocks propagating in a single producer, single node network. Specifically the create_test_accounts operation of txn_test_gen_plugin fails to initialize the currency contract unless I go and set def_max_just_send in the net_plugin to a high number. Then it works every time.

Unsure the details yet.

**Comment by pmesnier** [comment]
Can you enumerate the steps necessary to induce the trouble?

**Comment by pmesnier** [comment]
I dialed down the max "just send it" size to 1, and everything still works.

**Comment by spoonincode** [comment]
I believe the problem in my tests is due to the large txns basically causing significant jumbling of txn ordering (which of course is completely allowed). Going to close for now.

**Comment by gleehokie** [comment]
@spoonincode no testing required, right?
