### ISSUE TITLE
bios producer should use well-known key

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#1985]
The launcher is generating new keypairs for each of the nodes as is necessary. However the genesis.json file carries with it the public key of the initial block producer. 

Secondary updates include adding the initialization of some currency for each of the init* producers and updates to the bounce script and its helper.

**Comment by PaulCalabrese** [comment]
I verified this functionality by using the launcher to start a network and checking that the bios node keys came from the genesis.json file each time I ran the launcher.

**Comment by andriantolie** [comment]
Verified by Paul, I'm going to update the label accordingly
