### ISSUE TITLE
`updateauth` doesn't check for uniqueness of keys

### ISSUE THREAD

**Issue by abourget** [EOSIO/eos#1993]
Despite what the comment says:

https://github.com/EOSIO/eos/blob/master/libraries/chain/include/eosio/chain/authority.hpp#L70-L91

**Comment by andriantolie** [comment]
The reference link in this issue is no longer relevant. I think the way authority is validated is already updated in the latest code. I'm closing this issue as it's no longer relevant, but if you find issue with the latest code, please open a new issue. Thanks!
