### ISSUE TITLE
Less strict authorization for canceling delayed transaction

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#1994]
Related to #1022.

Currently canceling a delayed transaction using the `canceldelay` action requires the active authority of some account which authorized at least one of the actions in the original transaction that was delayed.

We would like to be less strict on the authorization requirements of `canceldelay` so that it can be signed with a permission that is equal to or more powerful in the permission hierarchy than a required permission in some action in the original delayed transaction.

**Comment by taokayan** [comment]
Test case "delay_tests/canceldelay_test" has passed with:
      40 assertions out of 40 passed

    Test case "delay_tests/canceldelay_test2" has passed with:
      38 assertions out of 38 passed
