### ISSUE TITLE
This method (and this comparison) is suspect.

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1996]
https://github.com/EOSIO/eos/blob/e22ac305bb921ee973a7c01bdce13a6d9744a154/libraries/chain/include/eosio/chain/authority.hpp#L81

It is suppose to check that it is sorted, but it may fail if there is more than one key because the comparison might be backward.

**Comment by andriantolie** [comment]
This issue is tested by unit test misc_tests/authority_checker. Since the unit test passes, this issue is verified to be fixed.
