### ISSUE TITLE
Transaction Header should include upper limit on compute time

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1998]
Currently it includes the upper limit of the context free compute; however, this requires us to recompute the exact instruction count on replay and does not allow the transaction creator to prevent rogue contracts (such as notify on transfer) from consuming an unexpected CPU instruction count.

**Comment by wanderingbort** [comment]
If we don't charge the max at all times then we still have to compute the
exact instruction count on replay.

A max would provide some defense against expensive notifies/inlines.

**Comment by bytemaster** [comment]
We always charge the declared amount, we just assert the actual is less than declared.

**Comment by bytemaster** [comment]
Your use of std::forward<> is wrong, should be std::move()

**Comment by arhag** [comment]
I just noticed this issue. I posted a very similar one here: #1999.

**Comment by bytemaster** [comment]
Partial work on this in commit: 18009d1

**Comment by bytemaster** [comment]
Closing due to dupe #1999

**Comment by andriantolie** [comment]
Duplicate. Put the label here, so it's marked no need to be tested
