### ISSUE TITLE
Preferential billing for pruned data (and friendlier default network usage billing)

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2000]
Transaction headers include a field `net_usage_words` which is the number of 8-byte words to bill for network bandwidth (not counting the additional billing per read and write locks). Currently, there is no preferential rate for the data that can be pruned (signatures and context-free data). Similar to CPU billing, validation checks would require that the committed `net_usage_words` is greater than or equal to an effective calculated size which is `size(compressed unsigned transaction) + factor * (size(signatures) + size(compressed context-free data)` where the factor is a configurable chain parameter less than one.

(Question: Should the additional billing for read and write locks be added into the effective size so that the `net_usage_words` fields directly determines the total amount to bill for? How would that affect deferred transactions generated in contract code?)

Furthermore, similar to #1999, by default net usage would only be billed to the actor of the first authorization of the first context-aware action of the transaction (rather than all authorizing actors of the transaction as it is today). The default account to bill could be overridden with a special context-free action, but that is a task left for another issue.

**Comment by SheldonHH** [comment]
net_usage_words > size(cut) + factor * (size(sig)+size(c-cfd))

**Comment by wanderingbort** [comment]
We are going with transaction having an optionally declared "max"  in line with #1999

Preferential billing is still being debated.

**Comment by arhag** [comment]
The `max_net_usage_words` has already been implemented.

What remains is to implement preferential billing of the prunable data in a similar way that we already have preferential billing of the CPU bandwidth of context-free action.

**Comment by arhag** [comment]
Discount billing for prunable data is already in latest slim
