### ISSUE TITLE
Canceling a delayed transaction should use the transaction id rather than a sender_id

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2002]
Related to #1022.

When a transaction needs to be delayed, the system creates a generated transaction with the appropriate `delay_until` time set. Like all generated transactions, it needs a `sender` (which is an account) and `sender_id` (a `uint128_t` number). In the case of delayed transactions, the `sender` is always the system account. The `sender_id` can be anything as long as it is unique for each unique delayed transaction. 

Currently an auto-incrementing number is used as the `sender_id`. So a user who signs a transaction which is delayed does not automatically know what `sender_id` to use to refer to that transaction they just signed and broadcast. Currently, the `canceldelay` action requires the `sender_id` of the delayed transaction to cancel. So a user would be forced to trust a full node to map the transaction id which they know to the `sender_id`. And our block structure does not provide any way for such a node to prove to a user (who trusts the block producers) that the mapping was correct.

Instead, the `canceldelay` action should be modified to take a transaction id. The `generated_transaction_index` already has a `by_trx_id` index to allow the native action handler to find the appropriate `generated_transaction_object` from which it can get its `sender_id` to use with `apply_context::cancel_deferred`.

ATC:
Unit test verify that canceldelay action can cancel a delayed transaction using the transaction_id.  Verify that all tests pass on all platforms.

**Comment by brianjohnson5972** [comment]
All unit tests passed on all platforms
