### ISSUE TITLE
nodeos / cleos usability improvements

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#2008]
The user experience for developers attempting to setup and run a new node and then interact with it from the command line is very poor, we need to improve it.

- [x] JSON Dumps of Transactions are not acceptable
- [x] Console output from running transactions should be visible
- [x] Account history should be readable 
- [x] hex blobs of action data are not readable 
- [x] configuration files should not need to be edited by default
- [x] eosio dev key should be available to all wallets without import step
- [x] producer plugin should be enabled by default
- [ ] cleos should start keos as a background daemon if it is not currently running so that users don't need to think about this background process. - will be completed by #2094
- [x] permission command line flags need to make "@active" optional 

```
./nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::account_history_api_plugin
```

**Comment by bytemaster** [comment]
Default system contract does not set an ABI and it needs to, setting bios fixes it.

**Comment by zorba80** [comment]
One item is left:
_cleos should start keos as a background daemon if it is not currently running so that users don't need to think about this background process._
I will create a separate task for it.

**Comment by zorba80** [comment]
ATC for item
_eosio dev key should be available to all wallets without import step_

- Unit tests check that the default eosio key is imported when a wallet is created.
- Run nodeos without --eosio-key option, create a wallet, check that the wallet includes the key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
- Rerun nodeos with the wallet_api_plugin option --eosio-key passing a different key as an argument, create a new wallet and verify that the wallet includes the passed key.

**Comment by brianjohnson5972** [comment]
Performed tests with and without --eosio-key and tests passed.
