### ISSUE TITLE
Uploading sample "currency" contract to blockchain fails

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#2011]
Running latest git master.
Following getting started examples. 

```
 ./cleos set contract currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi
Reading WAST...
Assembling WASM...
447826ms thread-0   main.cpp:1186                 main                 ] Failed with error: Assert Exception (10)
!"error parsing wast": Error parsing WebAssembly text file:
:1:1: expected '('
{
^
```

**Comment by bytemaster** [comment]
It looks like your current working directory is not accurate and/or you are using outdated docs.  I recently changed the command line usage so you only have to specify the contract folder and it will automatically identify the .wast and .abi which should be named after their parent folder according to the convention.

See this file for a tutorial on how it works now... much simpler:
https://github.com/EOSIO/eos/blob/09affc02fcc30fe7f04150087d4411b786775045/TUTORIAL.md

**Comment by bitcoiners** [comment]
Thanks for the link, but these are instructions right from the latest readme file.
![image](https://user-images.githubusercontent.com/38520/38174928-ea5011fe-35fe-11e8-9ed5-8c44c2b09b38.png)
They should be updated to how it works now.

**Comment by bitcoiners** [comment]
This needs to be reopened.
I followed instructions from the Tutorial and got same errror.
```
$ ./cleos set contract eosio contracts/eosio.bios -p eosio
Reading WAST...
Assembling WASM...
25368ms thread-0   main.cpp:1186                 main                 ] Failed with error: Assert Exception (10)
!"error parsing wast": Error parsing WebAssembly text file:
:1:1: expected '('

^
```

**Comment by tbfleming** [comment]
I hit this also. This sentence needs fixing:

> This command assumes it is being executed from the root of the eosio source, but you could execute it from anywhere by specifying the full path to ${EOSIO_SOURCE}/contracts/eosio.bios

The .wast files are in the build tree: ${EOSIO_SOURCE}/**build**/contracts/eosio.bios

**Comment by manhvvhtth** [comment]
Thank to @tbfleming : `cleos set contract eosio build/contracts/eosio.bios -p eosio`
