### ISSUE TITLE
cleos wallet import  failed Wallet not found: default

### ISSUE THREAD

**Issue by Justin-ye** [EOSIO/eos#2023]
when I run below ,it comes out "Wallet not found: default"
$ ./cleos wallet import 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3

980465ms thread-0   main.cpp:1008                 main                 ] Failed with error: unspecified (0)
Wallet not found: default
Request Path: localhost:8888/v1/wallet/import_key, Request Post Data: ["default","5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"]

**Comment by WildDylan** [comment]
hey, use `./cleos wallet list`
if return []
and `./cleos wallet create`
and use `./cleos wallet unlock -n default`
enter `./cleos wallet create` command give your password

next import your keys and do another options.

**Comment by Lomect** [comment]
Your default wallet is not create or not open.
you can do ```cleos wallet open``` and then exec ```cleos wallet list```. then you can found the default wallet. if it not exist, you should create it.
