### ISSUE TITLE
go_away messages while connecting

### ISSUE THREAD

**Issue by taraldesai** [EOSIO/eos#2024]
Hi,

Getting go_away messages

3135663ms thread-0   net_plugin.cpp:1707           connect              ] Skipping connect due to go_away reason wrong version
3135663ms thread-0   net_plugin.cpp:1707           connect              ] Skipping connect due to go_away reason wrong version
3135663ms thread-0   net_plugin.cpp:1707           connect              ] Skipping connect due to go_away reason wrong version
3135792ms thread-0   net_plugin.cpp:838            send_handshake       ] Sending handshake generation 1 to 95.216.20.181:7015
3135802ms thread-0   net_plugin.cpp:1755           operator()           ] connection failed to ctestnet.eosio.se:6602: Connection refused
3135965ms thread-0   net_plugin.cpp:1755           operator()           ] connection failed to eosbrazil.com:9873: Connection refused

Here is my config.ini relevant setting

max-reversible-block-time = -1
max-pending-transaction-time = -1

http-server-address = 0.0.0.0:8888
p2p-listen-endpoint = 0.0.0.0:9876
p2p-server-address = localhost:9876
access-control-allow-origin = *

I changed p2p-server-address  with server address and with IP also, but no luck

**Comment by PaulCalabrese** [comment]
The net_plugin version code has been refactored since this issue and now uses a protocol version (instead of a git hash).  Closing this issue as no longer valid.
