### ISSUE TITLE
When build simple.token under master branch, meet some errors.

### ISSUE THREAD

**Issue by WildDylan** [EOSIO/eos#2026]
5 warnings generated.
/usr/local/wasm/bin/llvm-link: /var/folders/_x/6lrr9b5130g76pmfmf0k0_cc0000gn/T/tmp.PfVi2Ahs/built/eosnow_token.hpp:1:1: error: expected top-level entity
CPC�
/usr/local/wasm/bin/llvm-link: error loading file '/var/folders/_x/6lrr9b5130g76pmfmf0k0_cc0000gn/T/tmp.PfVi2Ahs/built/eosnow_token.hpp'

When execute `eosiocpp -o`

**Comment by dvalencia-sd** [comment]
@WildDylan did you solve this issue? I'm getting the same issue.

**Comment by WildDylan** [comment]
Hi, rebuild eos with master code was worked.

**Comment by akildemir** [comment]
Hi i am getting the same error, is not there any other solution other than rebuilding eos, because i cant do this right now. And if so, what does it mean "rebuilding with master code was worked"? Thanks

**Comment by WildDylan** [comment]
clean your eos and rebuild eos under master branch.

**Comment by akildemir** [comment]
Thanks i have resolved without doing it. I had written the file extension wrongly.
