### ISSUE TITLE
mac os 10.13.3, exec ./eosio_build.sh failed

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#2028]
![image](https://user-images.githubusercontent.com/11972366/38193636-8fc65b56-36a5-11e8-83e7-7a244bceacb1.png)
I just exec:
   # git clone https://github.com/eosio/eos --recursive
and exec:
  # cd eos
  # ./eosio_build.sh
then, error occured, what should I do next?

**Comment by pacificcode** [comment]
Can you run the following commands and paste the result here?
find /usr -name libintl* -print 2>/dev/null
brew list --versions gettext
brew list
Thank you.

**Comment by manhvvhtth** [comment]
I get the same error

```

**Comment by guaiguaihw** [comment]
@pacificcode 
![image](https://user-images.githubusercontent.com/11972366/38237506-f6ed2c42-3759-11e8-8266-2daa5798c541.png)

**Comment by guaiguaihw** [comment]
Here is the result，what should I do to figure out the problem??

**Comment by pacificcode** [comment]
It looks like home-brew did not symlink get text properly. run the following commands.

brew unlink gettext && brew link --force gettext 
find /usr -name libintl* -print 2>/dev/null

The output should now show:
/usr/local/include/libintl.h
/usr/local/lib/libintl.dylib
/usr/local/lib/libintl.8.dylib
/usr/local/lib/libintl.a
/usr/local/Cellar/gettext/0.19.8.1/include/libintl.h
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.dylib
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.8.dylib
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.a
/usr/local/Cellar/gettext/0.19.8.1/share/gettext/intl/libintl.rc

**Comment by manhvvhtth** [comment]
Thank @pacificcode. It worked.

**Comment by guaiguaihw** [comment]
I worked, Thanks a lot ! @pacificcode

**Comment by jacktang** [comment]
Hello, I failed build eos also, the console logging below:


```
>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOS.IO

-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.64.0

  Boost include path: /usr/local/include

  Detected version of Boost is too old.  Requested version was 1.66 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:88 (FIND_PACKAGE)


-- Configuring Eos on OS X
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using WASM clang => /usr/local/wasm/bin/clang
-- Using WASM llc => /usr/local/wasm/bin/llc
-- Using WASM llvm-link => /usr/local/wasm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Configuring fc to build on Unix/Apple
-- zlib found
-- bzip2 found
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   unit_test_framework
--   locale
-- Configuring ChainBase on OS X
-- Using custom FindBoost.cmake
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   program_options
--   unit_test_framework
--   locale
-- Configuring AppBase on OS X
-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: /usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-D_THREAD_SAFE
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: /usr/local/lib/libmongocxx-static.a;/usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-D_THREAD_SAFE;/usr/local/lib/libmongoc-static-1.0.a;/usr/local/lib/libbson-static-1.0.a;-D_THREAD_SAFE;-lsasl2;-framework Security;-framework CoreFoundation;-lz;-lresolv
-- Git commit revision: 9d1cf3f5
-- Git commit revision: 9d1cf3f5
-- Git commit revision: 9d1cf3f5
-- Configuring incomplete, errors occurred!
See also "/Users/jacktang/Code/eos/build/CMakeFiles/CMakeOutput.log".

	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.
```

[CMakeOutput.log](https://github.com/EOSIO/eos/files/1878667/CMakeOutput.log)

**Comment by wangshijun** [comment]
@pacificcode I encountered the same issue here, tried the solution above, but with no luck, are there any other possible reasons mac build will fail? thanks!

## 1. build script log

```
❯ ./eosio_build.sh

	Beginning build version: 1.2
	Wed  2 May 2018 09:09:58 UTC
	git head id: 0a04ff86a6b8ab97a76dce4c9846a9f5c7b0b274
	Current branch: * dawn-v3.0.0

	ARCHITECTURE: Darwin

	OS name: Darwin
	OS Version: 10.13.4
	CPU speed: 220.00Ghz
	CPU cores: 4
	Physical Memory: 16 Gbytes
	Disk space total: 233G
	Disk space available: 37G

	Checking XCode installation
	XCode installation found.

	Checking Ruby installation
	Ruby installation found.

	Checking Home Brew installation
	Home Brew installation found.

	Checking dependencies.
	Checking automake ... 		 automake found
	Checking Libtool ... 		 Libtool found
	Checking OpenSSL ... 		 OpenSSL found
	Checking llvm ... 		 llvm found
	Checking wget ... 		 wget found
	Checking CMake ... 		 CMake found
	Checking Boost ... 		 Boost found
	Checking GMP ... 		 GMP found
	Checking gettext ... 		 gettext found
	Checking MongoDB ... 		 MongoDB found
	Checking Doxygen ... 		 Doxygen found
	Checking Graphviz ... 		 Graphviz found
	Checking Python3 ... 		 Python3 found

	No required Home Brew dependencies to install.

	Checking MongoDB C++ driver installation.
	Mongo C++ driver found at /usr/local/lib/libmongocxx-static.a.

	Checking secp256k1-zkp installation.
	secp256k1 found at /usr/local/lib/

	Checking LLVM with WASM support.
	WASM found at /usr/local/wasm/bin/


>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOS.IO

-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
-- Configuring Eos on OS X
CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/FindThreads.cmake:223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  externals/binaryen/CMakeLists.txt:96 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/Users/wangshijun/Develop/blockchain/eos/build/CMakeFiles/CMakeOutput.log".
See also "/Users/wangshijun/Develop/blockchain/eos/build/CMakeFiles/CMakeError.log".

	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.
```

## 2. CMakeError.log

```
Determining if the include file pthread.h exists failed with the following output:
Change Dir: /Users/wangshijun/Develop/blockchain/eos/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_32239/fast"
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_32239.dir/build.make CMakeFiles/cmTC_32239.dir/build
Building C object CMakeFiles/cmTC_32239.dir/CheckIncludeFile.c.o
/usr/local/bin/clang     -o CMakeFiles/cmTC_32239.dir/CheckIncludeFile.c.o   -c /Users/wangshijun/Develop/blockchain/eos/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/Users/wangshijun/Develop/blockchain/eos/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: 'pthread.h' file not found
#include <pthread.h>
         ^~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_32239.dir/CheckIncludeFile.c.o] Error 1
make: *** [cmTC_32239/fast] Error 2
```

## 3. gettext seems proper symblinked

```
❯ find /usr -name libintl* -print 2>/dev/null
/usr/local/include/libintl.h
/usr/local/lib/libintl.dylib
/usr/local/lib/libintl.8.dylib
/usr/local/lib/libintl.a
/usr/local/Cellar/texi2html/5.0/share/texi2html/lib/libintl-perl
/usr/local/Cellar/gettext/0.19.8.1/include/libintl.h
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.dylib
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.8.dylib
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.a
/usr/local/Cellar/gettext/0.19.8.1/share/gettext/intl/libintl.rc
```

**Comment by pacificcode** [comment]
@wangshijun can you run:
find /usr -name pthread.h -print 2>/dev/null

**Comment by wangshijun** [comment]
@pacificcode appreciate your help!

```
❯ find /usr -name pthread.h -print 2>/dev/null
/usr/include/pthread/pthread.h
/usr/include/pthread.h
```

**Comment by pacificcode** [comment]
@wangshijun The header file cmake is looking for is clearly located @ 
/usr/include/pthread/pthread.h
/usr/include/pthread.h
- I would recommend checking your $PATH
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
- Reboot your computer and clear your parameter ram
https://support.apple.com/en-us/HT204063
I would also run the following:
cd /path/to/eos
rm -rf /path/to/eos/build
git pull
git submodule update --init --recursive
./eosio_build.sh

Capture the output of the script and if you run into any further issues send the output and your CMakeError.log.

**Comment by pacificcode** [comment]
@gavinwyf It looks like you have boost and llvm issues. Try running the following:
brew remove --force boost
brew remove --force llvm
cd /path/to/eos
rm -rf build/
git pull
git submodule update --init --recursive
./eosio_build.sh
Capture the output of the script and if you run into any further issues send the output and your CMakeError.log.

**Comment by hoopslb** [comment]
@pacificcode 
$ find /usr -name libintl* -print 2>/dev/null
/usr/local/Cellar/gettext/0.19.8.1/include/libintl.h
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.dylib
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.8.dylib
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.a
/usr/local/Cellar/gettext/0.19.8.1/share/gettext/intl/libintl.rc

$ brew list --versions gettext
gettext 0.19.8.1

$ brew list
argtable		curl			gmp			jsoncpp			libmicrohttpd		libyaml			openssl@1.1
autoconf		doxygen			go			lcov			libplist		libzip			pkg-config
automake		ethereum		gperftools		leveldb			libpng			llvm@4			python
berkeley-db		fontconfig		graphviz		libffi			libtasn1		makedepend		readline
boost			freetype		hiredis			libgpg-error		libtiff			miniupnpc		snappy
boost@1.60		gd			icu4c			libidn2			libtool			mongodb			sqlite
cmake			gdbm			ideviceinstaller	libimobiledevice	libunistring		ninja			usbmuxd
cocoapods		gettext			ios-deploy		libjson-rpc-cpp		libusb			node			webp
coreutils		git			jpeg			libksba			libxml2			openssl			wget

**Comment by pacificcode** [comment]
@hoopslb 
brew unlink gettext && brew link --force gettext

find /usr -name libintl* -print 2>/dev/null

Your output should be (and you should be good to go):
$ find /usr -name libintl* -print 2>/dev/null
/usr/local/include/musl/upstream/include/libintl.h
/usr/local/include/libintl.h
/usr/local/lib/libintl.dylib
/usr/local/lib/libintl.8.dylib
/usr/local/lib/libintl.a
/usr/local/Cellar/gettext/0.19.8.1/include/libintl.h
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.dylib
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.8.dylib
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.a
/usr/local/Cellar/gettext/0.19.8.1/share/gettext/intl/libintl.rc

**Comment by wangshijun** [comment]
@pacificcode now the build succeed! thank you so much! 👍
