### ISSUE TITLE
No producers configured! Please add producer IDs and private keys to configuration.

### ISSUE THREAD

**Issue by okluoquan** [EOSIO/eos#2030]
Yesterday is ok.
After checkouting the latest in the master ,today it tell me:

3035677ms thread-0   producer_plugin.cpp:175       plugin_startup       ] No producers configured! Please add producer IDs and private keys to configuration.

At the same time, the file--config.ini didn't create by auto.

**Comment by okluoquan** [comment]
I find it:
./nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::account_history_api_plugin

**Comment by sailei1** [comment]
how to config? I have   the  same problem

**Comment by okluoquan** [comment]
./nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::account_history_api_plugin

or

modify  /Users/xxx/Library/Application' 'Support/eosio/nodeos/config/config.ini

**Comment by djjaron** [comment]
I find that this only fixes the problem for a clean install and if you don't stop nodeos from running it causes error  https://github.com/EOSIO/eos/issues/2142.
