### ISSUE TITLE
Consolidated fixes for #1979 feedback

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2031]
#1979 had a few issues come up during on-site review that were logged in the now merged PR by @wanderingbort on behalf of @bytemaster.  This is an issue to resolve these issues:

- [x] ~~bill delayed transactions to the authorizer who imposed the highest delay, break ties with order of declaration~~ Removed Req in favor of billing the first declared on first action
- [x] remove ability to specify `0` as the payer for a deferred transaction.  Require an explicit sender including when the sender is the contract account
- [x] allow privileged sender to bill _anyone_ for a deferred transaction's storage
- [x] allow privileged contract to bill _anyone_ for a database row
- [x] bill storage of new accounts to the account that creates them
- [x] remove use of `sizeof` when calculating ram billing (as it is potentially platform/compiler specific)
- [x] ~~change spec to not double bill accounts which appear multiple times in a transaction~~ Removed Req in favor of billing the first declared on first action
- [x] clean up use of IN64_MAX as a cap on an int64_t
- [x] remove pre-check for account existing when sending a deferred, fail on billing instead

**Comment by wanderingbort** [comment]
Adding note here from @arhag : for future key/sig suites the size of the `public_key_type` may change and that will affect billing of authorities.  We should bill them based on ala carte serialized size and not a "union" of sizes which is the static variant size.

**Comment by wanderingbort** [comment]
- [ ] new requirement: all usage is billed just once to first declared actor.

**Comment by andriantolie** [comment]
- [x] remove ability to specify `0` as the payer for a deferred transaction.  Require an explicit sender including when the sender is the contract account **Verified**
- [x] allow privileged sender to bill _anyone_ for a deferred transaction's storage **Verified**
- [x] allow privileged contract to bill _anyone_ for a database row **Verified**
- [x] bill storage of new accounts to the account that creates them **Verified**
- [x] remove use of `sizeof` when calculating ram billing (as it is potentially platform/compiler specific) **Verified**
- [x] clean up use of IN64_MAX as a cap on an int64_t **Verified**
- [x] remove pre-check for account existing when sending a deferred, fail on billing instead **Verified**
