### ISSUE TITLE
eoscpp cant create a helloword project

### ISSUE THREAD

**Issue by Npizza** [EOSIO/eos#2040]
Hi I run the command : `eoscpp -n helloword` and I get this:

`cp: cannot stat '/home/travis/build/EOSIO/eos/build/install/share/skeleton/.': No such file or directory
`
What is going wrong?Shouldn't create a directory with an example contract?

**Comment by okluoquan** [comment]
use eosiocpp

**Comment by andriantolie** [comment]
If you install the latest code, `eosiocpp -n helloworld` should work fine
