### ISSUE TITLE
Defer assigning sender_id until _apply_cycle_trace

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eos#2041]
Current code uses DBAPI to get auto-incremented sender_id for delayed transactions (apply_context::get_next_sender_id). This creates contention on the singleton that contains previous sender_id between all threads in future parallel version of EOS (the code uses one table/row for all delayed transaction of all users).

Instead of that deferred transaction should be created with sender_id == 0 (in chain_controller::_push_transaction) and later _apply_cycle_trace should check if sender_id ==0 and use upper_bound to figure out next id.

**Comment by andriantolie** [comment]
@moskvanaft is this done?

**Comment by moskvanaft** [comment]
This is no longer relevant.
