### ISSUE TITLE
Fix cleos get currency balance

### ISSUE THREAD

**Issue by cj-oci** [EOSIO/eos#2043]
eosio.system was not adapted to handle the create action.  Needs to handle forwarding it in its apply method and also needs it added to its abi.

Original complaint:
Currently cleos get currency balance does not output anything
   programs/cleos/cleos get currency balance eosio eosio

**Comment by brianjohnson5972** [comment]
In testUtils.py in createInitAccounts, need to un-comment code that checks balance and need to add "create" action.
In eosio.system.hpp apply method should just call "eosio::currency(receiver).apply( code, act )" rather than using dispatch method for currency.  Also need to add create to abi.

**Comment by brianjohnson5972** [comment]
#2231 should take care of this issue
