### ISSUE TITLE
eos/tests/wasm_tests/dice_tests.cpp:5:10: fatal error: 'dice/dice.wast.hpp' file not found

### ISSUE THREAD

**Issue by lilianwen** [EOSIO/eos#2049]
when I do 
./eosio_build.sh 

this error occur:
eos/tests/wasm_tests/dice_tests.cpp:5:10: fatal error: 'dice/dice.wast.hpp' file not found

**Comment by andriantolie** [comment]
Please check the latest code. Thanks!
