### ISSUE TITLE
DAWN-328 ⁃ Automate Code Coverage Testing and Report Generation

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#206]
Steem and BTS did code coverage testing, but we need to automate this and have a server report the status. We should attempt to have maximum coverage in our tests.

Unit test coverage. Boost tests.

Do want these before launch, want public to understand that we are doing this.

Ability in a nightly build run report that runs and generates a code coverage report

Later: Integrations with monitoring / alerting systems

**Comment by thomasbcox** [comment]
Adding to 'track-in-jira' to ensure it's visible to the sprint teams there

**Comment by jgiszczak** [comment]
Test coverage report now available at https://coveralls.io/github/EOSIO/eos
