### ISSUE TITLE
wrong documedation at /wiki/Tutorials#1-accounts--wallets

### ISSUE THREAD

**Issue by Npizza** [EOSIO/eos#2060]
I was looking the tutorials in this section `https://github.com/EOSIO/eos/wiki/Tutorials#1-accounts--wallets`
and I found that this command does not work:
`$ cleos create account inita ${desired_account_name} ${public_key_1} ${public_key_2}
`
instead I had to replace inita with eosio
`$ cleos create account eosio ${desired_account_name} ${public_key_1} ${public_key_2}`

**Comment by rbw3821** [comment]
The wiki is being updated as part of the dawn 3.0 release.  The updated wiki will contain this fix.
