### ISSUE TITLE
cannot run the hello contract on the latest master branch build

### ISSUE THREAD

**Issue by brightermatter** [EOSIO/eos#2061]
running eosiocpp -o hello.wast hello.cpp in the /eos/build/contracts/hello folder generates 2 errors.  The build is the latest master branch. Nodeos is running and wallets and accounts are created.

eosiocpp -o hello.wast hello.cpp

In file included from hello.cpp:5:
In file included from ./hello.hpp:5:
In file included from /usr/local/include/eosiolib/eosio.hpp:7:
In file included from /usr/local/include/eosiolib/action.hpp:7:
In file included from /usr/local/include/eosiolib/datastream.hpp:9:
In file included from /home/osboxes/opt/boost_1_66_0/include/boost/container/flat_map.hpp:26:
In file included from /home/osboxes/opt/boost_1_66_0/include/boost/container/new_allocator.hpp:24:
/home/osboxes/opt/boost_1_66_0/include/boost/container/throw_exception.hpp:56:21: warning: address of array 'msg' will
      always evaluate to 'true' [-Wpointer-bool-conversion]
      BOOST_ASSERT(!msg);
                   ~^~~
/home/osboxes/opt/boost_1_66_0/include/boost/assert.hpp:60:36: note: expanded from macro 'BOOST_ASSERT'
# define BOOST_ASSERT(expr) assert(expr)
                                   ^~~~
/usr/local/include/musl/upstream/include/assert.h:8:28: note: expanded from macro 'assert'
#define assert(x) ((void)((x) || (__assert_fail(#x, __FILE__, __LINE__, __func__),0)))
                           ^
In file included from hello.cpp:5:
In file included from ./hello.hpp:5:
In file included from /usr/local/include/eosiolib/eosio.hpp:7:
In file included from /usr/local/include/eosiolib/action.hpp:7:
In file included from /usr/local/include/eosiolib/datastream.hpp:9:
In file included from /home/osboxes/opt/boost_1_66_0/include/boost/container/flat_map.hpp:26:
In file included from /home/osboxes/opt/boost_1_66_0/include/boost/container/new_allocator.hpp:24:
/home/osboxes/opt/boost_1_66_0/include/boost/container/throw_exception.hpp:64:25: warning: address of array 'msg' will
      always evaluate to 'true' [-Wpointer-bool-conversion]
      BOOST_ASSERT_MSG(!msg, str);
                       ~^~~
/home/osboxes/opt/boost_1_66_0/include/boost/assert.hpp:61:46: note: expanded from macro 'BOOST_ASSERT_MSG'
# define BOOST_ASSERT_MSG(expr, msg) assert((expr)&&(msg))
                                             ^~~~
/usr/local/include/musl/upstream/include/assert.h:8:28: note: expanded from macro 'assert'
#define assert(x) ((void)((x) || (__assert_fail(#x, __FILE__, __LINE__, __func__),0)))
                           ^
In file included from hello.cpp:5:
In file included from ./hello.hpp:5:
In file included from /usr/local/include/eosiolib/eosio.hpp:7:
In file included from /usr/local/include/eosiolib/action.hpp:7:
In file included from /usr/local/include/eosiolib/datastream.hpp:9:
In file included from /home/osboxes/opt/boost_1_66_0/include/boost/container/flat_map.hpp:26:
In file included from /home/osboxes/opt/boost_1_66_0/include/boost/container/new_allocator.hpp:24:
/home/osboxes/opt/boost_1_66_0/include/boost/container/throw_exception.hpp:72:25: warning: address of array 'msg' will
      always evaluate to 'true' [-Wpointer-bool-conversion]
      BOOST_ASSERT_MSG(!msg, str);
                       ~^~~
/home/osboxes/opt/boost_1_66_0/include/boost/assert.hpp:61:46: note: expanded from macro 'BOOST_ASSERT_MSG'
# define BOOST_ASSERT_MSG(expr, msg) assert((expr)&&(msg))
                                             ^~~~
/usr/local/include/musl/upstream/include/assert.h:8:28: note: expanded from macro 'assert'
#define assert(x) ((void)((x) || (__assert_fail(#x, __FILE__, __LINE__, __func__),0)))
                           ^
In file included from hello.cpp:5:
In file included from ./hello.hpp:5:
In file included from /usr/local/include/eosiolib/eosio.hpp:7:
In file included from /usr/local/include/eosiolib/action.hpp:7:
In file included from /usr/local/include/eosiolib/datastream.hpp:9:
In file included from /home/osboxes/opt/boost_1_66_0/include/boost/container/flat_map.hpp:26:
In file included from /home/osboxes/opt/boost_1_66_0/include/boost/container/new_allocator.hpp:24:
/home/osboxes/opt/boost_1_66_0/include/boost/container/throw_exception.hpp:80:25: warning: address of array 'msg' will
      always evaluate to 'true' [-Wpointer-bool-conversion]
      BOOST_ASSERT_MSG(!msg, str);
                       ~^~~
/home/osboxes/opt/boost_1_66_0/include/boost/assert.hpp:61:46: note: expanded from macro 'BOOST_ASSERT_MSG'
# define BOOST_ASSERT_MSG(expr, msg) assert((expr)&&(msg))
                                             ^~~~
/usr/local/include/musl/upstream/include/assert.h:8:28: note: expanded from macro 'assert'
#define assert(x) ((void)((x) || (__assert_fail(#x, __FILE__, __LINE__, __func__),0)))
                           ^
In file included from hello.cpp:5:
In file included from ./hello.hpp:5:
In file included from /usr/local/include/eosiolib/eosio.hpp:7:
In file included from /usr/local/include/eosiolib/action.hpp:7:
In file included from /usr/local/include/eosiolib/datastream.hpp:9:
In file included from /home/osboxes/opt/boost_1_66_0/include/boost/container/flat_map.hpp:26:
In file included from /home/osboxes/opt/boost_1_66_0/include/boost/container/new_allocator.hpp:24:
/home/osboxes/opt/boost_1_66_0/include/boost/container/throw_exception.hpp:88:25: warning: address of array 'msg' will
      always evaluate to 'true' [-Wpointer-bool-conversion]
      BOOST_ASSERT_MSG(!msg, str);
                       ~^~~
/home/osboxes/opt/boost_1_66_0/include/boost/assert.hpp:61:46: note: expanded from macro 'BOOST_ASSERT_MSG'
# define BOOST_ASSERT_MSG(expr, msg) assert((expr)&&(msg))
                                             ^~~~
/usr/local/include/musl/upstream/include/assert.h:8:28: note: expanded from macro 'assert'
#define assert(x) ((void)((x) || (__assert_fail(#x, __FILE__, __LINE__, __func__),0)))
                           ^
hello.cpp:19:38: error: no matching conversion for functional-style cast from 'uint64_t' (aka 'unsigned long long') to
      'eosio::name'
       eosio::print( "Selam Bist: ", eosio::name(code), "->", eosio::name(action), "\n" );
                                     ^~~~~~~~~~~~~~~~
/usr/local/include/eosiolib/types.hpp:75:11: note: candidate constructor (the implicit copy constructor) not viable: no
      known conversion from 'uint64_t' (aka 'unsigned long long') to 'const eosio::name' for 1st argument
   struct name {
          ^
/usr/local/include/eosiolib/types.hpp:75:11: note: candidate constructor (the implicit move constructor) not viable: no
      known conversion from 'uint64_t' (aka 'unsigned long long') to 'eosio::name' for 1st argument
/usr/local/include/eosiolib/types.hpp:75:11: note: candidate constructor (the implicit default constructor) not viable:
      requires 0 arguments, but 1 was provided
hello.cpp:19:63: error: no matching conversion for functional-style cast from 'uint64_t' (aka 'unsigned long long') to
      'eosio::name'
       eosio::print( "Selam Bist: ", eosio::name(code), "->", eosio::name(action), "\n" );
                                                              ^~~~~~~~~~~~~~~~~~
/usr/local/include/eosiolib/types.hpp:75:11: note: candidate constructor (the implicit copy constructor) not viable: no
      known conversion from 'uint64_t' (aka 'unsigned long long') to 'const eosio::name' for 1st argument
   struct name {
          ^
/usr/local/include/eosiolib/types.hpp:75:11: note: candidate constructor (the implicit move constructor) not viable: no
      known conversion from 'uint64_t' (aka 'unsigned long long') to 'eosio::name' for 1st argument
/usr/local/include/eosiolib/types.hpp:75:11: note: candidate constructor (the implicit default constructor) not viable:
      requires 0 arguments, but 1 was provided
5 warnings and 2 errors generated.

**Comment by yanxi-me** [comment]
+1

**Comment by MTGParley** [comment]
I have the same problem any ideas?

**Comment by yanxi-me** [comment]
resolved by changing the line

    void apply( uint64_t receiver, uint64_t code, uint64_t action ) {

to

    void apply( uint64_t receiver, eosio::name code, eosio::name action ) {

**Comment by masonbrothers** [comment]
I am having the same issue as well. It appears that this issue is similar to #2012. 

@yanxi-me I was able to compile with ```void apply( uint64_t receiver, eosio::name code, eosio::name action )``` too. I am a bit concerned that the WebAssembly virtual machine looks for a function with the prototype ```void apply( uint64_t receiver, uint64_t code, uint64_t action )```. I could be incorrect however as I am rather new to EOS development.

**Comment by masonbrothers** [comment]
I am looking inside of [types.hpp](https://github.com/EOSIO/eos/blob/master/contracts/eosiolib/types.hpp). I think ```struct name``` needs a constructor for ```uint64_t```.

**Comment by romainPellerin** [comment]
@masonbrothers your fix works for me, I was able to build dice smart contract using it.

**Comment by farhan19aug** [comment]
+1

**Comment by andriantolie** [comment]
@brightermatter Do you still encounter this problem on the latest code?

**Comment by andriantolie** [comment]
hello contract has been refactored to follow latest eosio framework, it should be fine now
