### ISSUE TITLE
Nodeos crashed when trying to run 'cleos get accounts xxxxxxxxx'

### ISSUE THREAD

**Issue by henryyyx** [EOSIO/eos#2066]
Below is the log message on the nodeos side.
1737632ms thread-0   producer_plugin.cpp:166       plugin_startup       ] Launching block production for 1 producers.
1737632ms thread-0   producer_plugin.cpp:176       plugin_startup       ] producer plugin:  plugin_startup() end
1738000ms thread-0   producer_plugin.cpp:241       block_production_loo ] Not producing block because production is disabled until we receive a recent block (se
e: --enable-stale-production)
1818633ms thread-0   chain_api_plugin.cpp:75       operator()           ] Exception encountered while processing chain.abi_json_to_bin: {"code":3010004,"name":"
contract_query_exception","message":"Contract Query Exception","stack":[{"context":{"level":"error","file":"chain_plugin.cpp","line":484,"method":"abi_json_to_b
in","hostname":"","thread_name":"thread-0","timestamp":"2018-04-03T15:30:18.625"},"format":"Contract can't be found ${contract}","data":{"contract":"user"}},{"c
ontext":{"level":"warn","file":"chain_plugin.cpp","line":496,"method":"abi_json_to_bin","hostname":"","thread_name":"thread-0","timestamp":"2018-04-03T15:30:18.
633"},"format":"","data":{"params.code":"user","params.action":"hi","params.args":["user"]}}]}
1904962ms thread-0   chain_api_plugin.cpp:77       operator()           ] Exception encountered while processing chain.get_required_keys: {"code":3010001,"name"
:"permission_query_exception","message":"Permission Query Exception","stack":[{"context":{"level":"warn","file":"chain_controller.cpp","line":1410,"method":"get
_permission","hostname":"","thread_name":"thread-0","timestamp":"2018-04-03T15:31:44.961"},"format":"Fail to retrieve permission: ${level} (${what})","data":{"l
evel":{"actor":"user","permission":"active"},"what":"unknown key"}}]}
1928571ms thread-0   chain_api_plugin.cpp:77       operator()           ] Exception encountered while processing chain.get_required_keys: {"code":3010001,"name"
:"permission_query_exception","message":"Permission Query Exception","stack":[{"context":{"level":"warn","file":"chain_controller.cpp","line":1410,"method":"get
_permission","hostname":"","thread_name":"thread-0","timestamp":"2018-04-03T15:32:08.571"},"format":"Fail to retrieve permission: ${level} (${what})","data":{"l
evel":{"actor":"user","permission":"active"},"what":"unknown key"}}]}
2074928ms thread-0   chain_api_plugin.cpp:77       operator()           ] Exception encountered while processing chain.get_required_keys: {"code":3010001,"name"
:"permission_query_exception","message":"Permission Query Exception","stack":[{"context":{"level":"warn","file":"chain_controller.cpp","line":1410,"method":"get
_permission","hostname":"","thread_name":"thread-0","timestamp":"2018-04-03T15:34:34.928"},"format":"Fail to retrieve permission: ${level} (${what})","data":{"l
evel":{"actor":"user","permission":"active"},"what":"unknown key"}}]}
nodeos: /vagrant/download/eos/libraries/chainbase/include/chainbase/chainbase.hpp:801: decltype ((chainbase::generic_index<MultiIndexType>*)(nullptr)->indicies(
).get<ByIndex>()) chainbase::database::get_index() const [with MultiIndexType = boost::multi_index::multi_index_container<eosio::public_key_history_object, boos
t::multi_index::indexed_by<boost::multi_index::ordered_unique<boost::multi_index::tag<eosio::by_id>, boost::multi_index::member<eosio::public_key_history_object
, chainbase::oid<eosio::public_key_history_object>, &eosio::public_key_history_object::id> >, boost::multi_index::ordered_unique<boost::multi_index::tag<eosio::
by_pub_key>, boost::multi_index::composite_key<eosio::public_key_history_object, boost::multi_index::member<eosio::public_key_history_object, fc::crypto::public
_key, &eosio::public_key_history_object::public_key>, boost::multi_index::member<eosio::public_key_history_object, chainbase::oid<eosio::public_key_history_obje
ct>, &eosio::public_key_history_object::id> > >, boost::multi_index::ordered_unique<boost::multi_index::tag<eosio::by_account_permission>, boost::multi_index::c
omposite_key<eosio::public_key_history_object, boost::multi_index::member<eosio::public_key_history_object, eosio::chain::name, &eosio::public_key_history_objec
t::name>, boost::multi_index::member<eosio::public_key_history_object, eosio::chain::name, &eosio::public_key_history_object::permission>, boost::multi_index::m
ember<eosio::public_key_history_object, chainbase::oid<eosio::public_key_history_object>, &eosio::public_key_history_object::id> > > >, boost::interprocess::all
ocator<eosio::public_key_history_object, boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family>, boo
st::interprocess::iset_index> > >; ByIndex = eosio::by_pub_key; decltype ((chainbase::generic_index<MultiIndexType>*)(nullptr)->indicies().get<ByIndex>()) = con
st boost::multi_index::detail::ordered_index<boost::multi_index::composite_key<eosio::public_key_history_object, boost::multi_index::member<eosio::public_key_hi
story_object, fc::crypto::public_key, &eosio::public_key_history_object::public_key>, boost::multi_index::member<eosio::public_key_history_object, chainbase::oi
d<eosio::public_key_history_object>, &eosio::public_key_history_object::id> >, std::less<boost::multi_index::composite_key_result<boost::multi_index::composite_
key<eosio::public_key_history_object, boost::multi_index::member<eosio::public_key_history_object, fc::crypto::public_key, &eosio::public_key_history_object::pu
blic_key>, boost::multi_index::member<eosio::public_key_history_object, chainbase::oid<eosio::public_key_history_object>, &eosio::public_key_history_object::id>
 > > >, boost::multi_index::detail::nth_layer<2, eosio::public_key_history_object, boost::multi_index::indexed_by<boost::multi_index::ordered_unique<boost::mult
i_index::tag<eosio::by_id>, boost::multi_index::member<eosio::public_key_history_object, chainbase::oid<eosio::public_key_history_object>, &eosio::public_key_hi
story_object::id> >, boost::multi_index::ordered_unique<boost::multi_index::tag<eosio::by_pub_key>, boost::multi_index::composite_key<eosio::public_key_history_
object, boost::multi_index::member<eosio::public_key_history_object, fc::crypto::public_key, &eosio::public_key_history_object::public_key>, boost::multi_index:
:member<eosio::public_key_history_object, chainbase::oid<eosio::public_key_history_object>, &eosio::public_key_history_object::id> > >, boost::multi_index::orde
red_unique<boost::multi_index::tag<eosio::by_account_permission>, boost::multi_index::composite_key<eosio::public_key_history_object, boost::multi_index::member
<eosio::public_key_history_object, eosio::chain::name, &eosio::public_key_history_object::name>, boost::multi_index::member<eosio::public_key_history_object, eo
sio::chain::name, &eosio::public_key_history_object::permission>, boost::multi_index::member<eosio::public_key_history_object, chainbase::oid<eosio::public_key_
history_object>, &eosio::public_key_history_object::id> > > >, boost::interprocess::allocator<eosio::public_key_history_object, boost::interprocess::segment_man
ager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family>, boost::interprocess::iset_index> > >, boost::mpl::v_item<eosio::by_pub_key,
boost::mpl::vector0<mpl_::na>, 0>, boost::multi_index::detail::ordered_unique_tag, boost::multi_index::detail::null_augment_policy>&]: Assertion `_index_map[ind
ex_type::value_type::type_id]' failed.
Aborted

Below are the steps running with cleos.

[root@lab tools]# cleos wallet keys
[[
    "EOS5bEWiid56525qXNPqojRaPeUMASFVbDVEWaG12v7hezT382YqW",
    "5JisUmRieQToexhWUP1exrx8XQSQbTg2gdeWN3teVJHRQkZ8eTx"
  ],[
    "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
    "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
  ],[
    "EOS6kr3HC2aTJsca7kDHS6JFZ8g71KrSxWshmZyzGLJAzM17wNrn8",
    "5HtP4QsvCHMspWqEeqtFV4hM6WaxS6Vhfz2EMHpitAr9A5zGbND"
  ]
]
[root@lab tools]# cleos get accounts EOS6kr3HC2aTJsca7kDHS6JFZ8g71KrSxWshmZyzGLJAzM17wNrn8
**2376805ms thread-0   main.cpp:1186                 main                 ] Failed with error: read_until: End of file (13)
read_until: End of file:**

## Nodeos failed to start up after the crash occurred.

[root@lab vagrant]# nodeos --config-dir ~/eosio-wallet  -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio:
:account_history_api_plugin
2446018ms thread-0   wallet_plugin.cpp:37          plugin_initialize    ] initializing wallet plugin
2446018ms thread-0   http_plugin.cpp:141           plugin_initialize    ] host: 0.0.0.0 port: 8888
2446018ms thread-0   http_plugin.cpp:144           plugin_initialize    ] configured http to listen on 0.0.0.0:8888
2446018ms thread-0   wallet_api_plugin.cpp:112     plugin_initialize    ]

2446018ms thread-0   chain_plugin.cpp:96           plugin_initialize    ] initializing chain plugin
2446018ms thread-0   net_plugin.cpp:2622           plugin_initialize    ] Initialize net plugin
2446018ms thread-0   net_plugin.cpp:2644           plugin_initialize    ] Setting net_plugin logging level to info
2446018ms thread-0   net_plugin.cpp:2672           plugin_initialize    ] host: 0.0.0.0 port: 9876
2446018ms thread-0   net_plugin.cpp:2748           plugin_initialize    ] my node_id is d41e0f566762595c265af3d8d738ac396f5da13be6d1ca3f1b9c1a9d64f420d5
2446019ms thread-0   main.cpp:90                   main                 ] nodeos version 638f5d72
2446019ms thread-0   main.cpp:91                   main                 ] eosio root is /root/.local/share
2446019ms thread-0   http_plugin.cpp:156           plugin_startup       ] start processing http thread
2446019ms thread-0   http_plugin.cpp:213           plugin_startup       ] start listening for http requests
2446019ms thread-0   http_plugin.cpp:218           plugin_startup       ] http io service exit
2446019ms thread-0   wallet_api_plugin.cpp:70      plugin_startup       ] starting wallet_api_plugin
2446019ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/create
2446019ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/get_public_keys
2446019ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/import_key
2446019ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/list_keys
2446019ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/list_wallets
2446019ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/lock
2446019ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/lock_all
2446019ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/open
2446019ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/set_timeout
2446019ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/sign_transaction
2446019ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/unlock
2446019ms thread-0   block_log.cpp:120             open                 ] Log is nonempty
2446019ms thread-0   block_log.cpp:128             open                 ] Index is nonempty

**Comment by henryyyx** [comment]
This issue occurred when running nodeos without the option '-e' like below.
nodeos  -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::account_history_api_plugin

**Comment by andriantolie** [comment]
@henryyyx Do you still encounter the problem with latest version of eosio?

**Comment by andriantolie** [comment]
To be able to use `cleos get accounts` you need to enable history_api_plugin instead of account_history_api_plugin. account_history_api_plugin is deprecated. Try it with `--plugin eosio::history_api_plugin`
