### ISSUE TITLE
Add a string field to the ABI that is arbitrary text

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2067]
The intent is to use this field to contain the human readable text version of the contract.  Think Ricardian contracts.

**Comment by PaulCalabrese** [comment]
I verified this functionality by doing the following:

1. Added a value for ricardian_contract to an action in an .abi file
2. Set the contract
3. Retrieved the abi using get code -a
4. Verified that the string was reported under the ricardian_contract field of the action
