### ISSUE TITLE
Datastream infinitely recurses on some fundamental types in eosiolib

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2069]
These specializations catch too much, as they will take _any_ type that is not specialized above and expect that it is a magic-reflectable type.  In the case of a type (exactly) like `int` this will mis-detect `int` as a struct with a single member of type `int` and recurse into itself:

https://github.com/EOSIO/eos/blob/24cfeca84800d7ac17ef99f0de45e1a1cbb80a8d/contracts/eosiolib/datastream.hpp#L619-L632

ATC: contracts using the `EOSIO_API` and `EOSIO_SERIALIZE` macros can operate on types like `int` without causing stack or memory exceptions

**Comment by taokayan** [comment]
Pull request https://github.com/EOSIO/eos/pull/2264 created to fix the pointer type cases (try to serialize pointer type using datastream will result in compile error). Add unit test cases.
