### ISSUE TITLE
Deterministic Floating Point API

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#207]
The actual precision of a cpp_dec_float is always slightly higher than the number of digits specified in the template parameter, actually how much higher is an implementation detail but is always at least 8 decimal digits.

This indicates that it may not be deterministic.

The documentation for cpp_bin_float_50 does not have such a disclaimer, that said we should verify that under the hood it only uses integer maths.

**Comment by elmato** [comment]
Upon further looking at the code and debuging, the cpp_bin_float uses only integer math to perform floating point arithmetic.

Ref 276b3f3c3212bd66b2cba10e7fe41f5287022f53

**Comment by elmato** [comment]
Closed by 276b3f3
