### ISSUE TITLE
cleos should be able to read JSON from file for any command which takes JSON

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eos#2077]
Currently `cleos push action` and `cleos push transactions` doesn't not allow to to provide JSON file. Maybe there are other places like that.

ATC:
Use push action and push transaction passing in both json strings and files with json and verify both behave as expected

**Comment by brianjohnson5972** [comment]
Currently, we can do:

programs/cleos/cleos push action -j currency transfer "$(cat test.json)" --permission currency@active

to pass in the contents of test.json

**Comment by PaulCalabrese** [comment]
ATC passed.
