### ISSUE TITLE
 Performance testing

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2078]
We want the following performance data to be available for each release:

1. Single threaded transactions per second.
2. With and without JITter.
3. With and without signature verification (since verification will be done in parallel in the future this gives us an idea of what will be achievable then)
4. Above measurements made in single node (no network) and multi-node (two nodes with network) configuration.

ATC:
A report similar to what was produced last time we ran these tests containing the test data and commentary. [We should link to the previous report.]

**Comment by SheldonHH** [comment]
Jitter has two difference meaning
1. variation in the delay of received packets. 
2. Javascript Interpreter: maybe emscripten of binaryen 
> #1452  0978f34561170d640e5d13af9c5ce7debfbcf2de all test pass interpreter / jitter
>  jitter is the deviation from true periodicity of a presumably periodic signal, often in relation to a reference clock signal. In clock recovery applications it is called timing jitter.
![image](https://user-images.githubusercontent.com/16319106/38296671-9eec4c5a-3824-11e8-969d-963dbb07f3d2.png)

**Comment by SheldonHH** [comment]
Refer to @wanderingbort  answer
JITter is one of two execution modules we have for Webassembly.
JITter is ** ahead of time compilation**  for WAVM
> [wasm-jit](https://github.com/EOSIO/eos/tree/master/libraries/wasm-jit)

**Comment by gleehokie** [comment]
@SheldonHH in this context I am referring to the just-in-time (JIT) WASM compiler vs. the WASM interpreter.

**Comment by bytemaster** [comment]
macbook, clang6, -O3, single node, no signature checking
WAVM: 8000 txn/sec
binaryen: 2700 txn/sec

Linux, Ryzen 1600X, clang6, -O3, two-nodes on same box with full signature checking, binaryen --- 1200txn/sec

**Comment by gleehokie** [comment]
Here is a link to the instructions for how to repeat the performance tests such as these: https://gist.github.com/spoonincode/fca5658326837b76fd744d39b2a25b4e
