### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by heipacker** [EOSIO/eos#2081]
2307303ms thread-0   net_plugin.cpp:1103           process_next_message ] e.to_detail_string(): 10 assert_exception: Assert Exception
w < count():
    {}
    thread-0  static_variant.hpp:344 set_which
Error unpacking field _storage
    {"field":"_storage"}
    thread-0  raw.hpp:327 operator()
error unpacking fc::crypto::signature
    {"type":"fc::crypto::signature"}
    thread-0  raw.hpp:568 unpack
Error unpacking field sig
    {"field":"sig"}
    thread-0  raw.hpp:327 operator()
error unpacking eosio::handshake_message
    {"type":"eosio::handshake_message"}
    thread-0  raw.hpp:568 unpack
2307303ms thread-0   net_plugin.cpp:1239           request_next_chunk   ] conn testnet.eosnation.io:9876 requesting range 1 to 1000
2307303ms thread-0   net_plugin.cpp:895            operator()           ] Error sending to peer testnet.eosnation.io:9876: Bad file descriptor

**Comment by wddxzz** [comment]
It s solved?

**Comment by xu10000** [comment]
the same problem

**Comment by xu10000** [comment]
any one can solved?

**Comment by xu10000** [comment]
Bad file descriptor
