### ISSUE TITLE
This error could be made clearer. Bad file name. 

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#2082]
☁  eos [master] cleos set contract eosio contracts/eosio.bios/ -p eosio
Reading WAST...
Assembling WASM...
3096374ms thread-0   main.cpp:1186                 main                 ] Failed with error: Assert Exception (10)
!"error parsing wast": Error parsing WebAssembly text file:
:1:1: expected '('

^

**Comment by nmsz97** [comment]
Bumped, common error.

**Comment by quocle108** [comment]
I have them same error.

$cleos set contract eosio.token ../contracts/eosio.token -p eosio.token
Reading WAST/WASM from ../contracts/eosio.token/eosio.token.wast...
Assembling WASM...
2677748ms thread-0   main.cpp:1763                 main                 ] Failed with error: Assert Exception (10)
!"error parsing wast": Error parsing WebAssembly text file:
:1:1: expected '('
{
^

**Comment by wanderingbort** [comment]
WAST support was deprecate and this error message now distinguishes between missing files and malformed WASM
