### ISSUE TITLE
db_store_i64 must needs "account_name payer" authority? but void db_update_i64(int32_t iterator, account_name payer, const void* data, uint32_t len); not need

### ISSUE THREAD

**Issue by chenlian2015** [EOSIO/eos#2086]
int32_t db_store_i64(account_name scope, table_name table, account_name payer, uint64_t id,  const void* data, uint32_t len);
this function must needs "account_name payer" authority?
but push action from one contract to another contract,how to add authority?
`trx.actions.emplace_back(vector<permission_level>{{N(mycontract), N(active)}}, transfercurrency);`
only mycontract can be set,other account name can not get authority,because private key not store on eos node??

but why`void db_update_i64(int32_t iterator, account_name payer, const void* data, uint32_t len);`,payer authority not needed?

**Comment by andriantolie** [comment]
For update, if there is no change in the total ram space, I believe the auth is not needed
