### ISSUE TITLE
Wrong documentation with "currency" contract?

### ISSUE THREAD

**Issue by Npizza** [EOSIO/eos#2091]
I am trying to run the currency contract in the main page `https://github.com/EOSIO/eos` 
I create a account with the command: `./cleos create account eosio currency PUBLIC_KEY_1 PUBLIC_KEY_2
`
It seems to work good but when I run the command `./cleos get account currency`
I get that:
`{
  "account_name": "currency",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS8cAbAbevzuh2pFn2n7uQd9ijPYJaNFYqveZ7DbtgcA4BjUqMJG",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS7WTGdq12tvrNG3NQq5qLVtz5vcj7548eRnZJtEN1isi17LyRpg",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}
`

In the documentation it says that I should take something like that:
`{
  "account_name": "currency",
  "eos_balance": "0.0000 EOS",
  "staked_balance": "0.0001 EOS",
  "unstaking_balance": "0.0000 EOS",
  "last_unstaking_time": "2035-10-29T06:32:22",
   ...
}`

Also I noticed that when I create a account I get in the nodeos this messege:
`561853ms thread-0   chain_api_plugin.cpp:79       operator()           ] Exception encountered while processing chain.push_transaction: {"code":3040000,"name":"action_validate_exception","message":"message validation exception","stack":[{"context":{"level":"error","file":"eosio_contract.cpp","line":62,"method":"apply_eosio_newaccount","hostname":"","thread_name":"thread-0","timestamp":"2018-04-04T09:09:21.850"},"format":"Cannot create account named ${name}, as that name is already taken","data":{"name":"currency"}},{"context":{"level":"warn","file":"eosio_contract.cpp","line":87,"method":"apply_eosio_newaccount","hostname":"","thread_name":"thread-0","timestamp":"2018-04-04T09:09:21.851"},"format":"","data":{"create":{"creator":"eosio","name":"currency","owner":{"threshold":1,"keys":[{"key":"EOS7WTGdq12tvrNG3NQq5qLVtz5vcj7548eRnZJtEN1isi17LyRpg","weight":1}],"accounts":[]},"active":{"threshold":1,"keys":[{"key":"EOS8cAbAbevzuh2pFn2n7uQd9ijPYJaNFYqveZ7DbtgcA4BjUqMJG","weight":1}],"accounts":[]},"recovery":{"threshold":1,"keys":[],"accounts":[{"permission":{"actor":"eosio","permission":"active"},"weight":1}]}}}},{"context":{"level":"warn","file":"apply_context.cpp","line":27,"method":"exec_one","hostname":"","thread_name":"thread-0","timestamp":"2018-04-04T09:09:21.852"},"format":"","data":{"_pending_console_output.str()":""}},{"context":{"level":"warn","file":"chain_controller.cpp","line":1662,"method":"__apply_transaction","hostname":"","thread_name":"thread-0","timestamp":"2018-04-04T09:09:21.853"},"format":"","data":{}},{"context":{"level":"warn","file":"chain_controller.cpp","line":1681,"method":"_apply_transaction","hostname":"","thread_name":"thread-0","timestamp":"2018-04-04T09:09:21.853"},"format":"","data":{}},{"context":{"level":"warn","file":"chain_controller.cpp","line":373,"method":"_push_transaction","hostname":"","thread_name":"thread-0","timestamp":"2018-04-04T09:09:21.853"},"format":"","data":{}},{"context":{"level":"warn","file":"chain_controller.cpp","line":311,"method":"_push_transaction","hostname":"","thread_name":"thread-0","timestamp":"2018-04-04T09:09:21.853"},"format":"","data":{}},{"context":{"level":"warn","file":"chain_controller.cpp","line":258,"method":"push_transaction","hostname":"","thread_name":"thread-0","timestamp":"2018-04-04T09:09:21.853"},"format":"","data":{}}]}
`

Is that normal?

**Comment by gleehokie** [comment]
OBE, closing since the currency contract has been removed
