### ISSUE TITLE
./eosio_build.sh exiting without installing on 4GB memory system

### ISSUE THREAD

**Issue by Npizza** [EOSIO/eos#2092]
I tried to reinstall eos but when  I run the ./eosio_build.sh I get that message:
`	Beginning build version: 1.2
	Wed Apr  4 09:50:15 UTC 2018
	git head id: cced245424e1aa7f9f301e55a8042e874115d98a
	Current branch: * master

	ARCHITECTURE: Linux

	OS name: Linux Mint
	OS Version: 18.2
	CPU speed: 1696
MHz:
MHz:Mhz
	CPU cores: 4
	Physical Memory: 3836 Mgb
	Disk install: /dev/sda2
	Disk space total: 211G
	Disk space available: 67G
	Your system must have 8 or more Gigabytes of physical memory installed.
	Exiting now.
`  

But the wierd thing is that I have space in my disk.Whatcan i do?

**Comment by strahe** [comment]
8G or more memory, not disk.

**Comment by Npizza** [comment]
Is it any way to install it without checking for the memory?I had installed it to a other laptop with more 8gb of ram and then changed hard drives to a other laptop with less than 8 gb ram and it worked.

**Comment by JFreegman** [comment]
It actually works if you have >= 4 gigs of ram. You can disable or modify this check on line 25 of eos/scripts/eosio_build_ubuntu.sh
