### ISSUE TITLE
Running chain_test from the repository directory leaves temp files around

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2093]
Running: 
```
<build directory>/tests/chain_test --log_level=error  -- --verbose
```
from the root of the repository leaves the following cruft:

```
$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	test
	wallet_test.json
```

These files should be cleaned up as part of the testing rig -or- more ideally put into a temporary directory.

**Comment by andriantolie** [comment]
I tried to run unittests from the repo and seems this issue is fixed
