### ISSUE TITLE
Complete testing of #1979

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2100]
There are a lot of unit tests already, but there are some more that need to be written.  Check with @wanderingbort to get the list of what should be done for unit and integration tests. #1979

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner I am thinking that this is complete or will not be implemented.  If I don't hear from you I will presume that is the case.

**Comment by brianjohnson5972** [comment]
The unit test coverage is sufficient.
