### ISSUE TITLE
Wrong path in TUTORIAL.md

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#2101]
The tutorial expects .wast files to live in the source tree, but they live in the build tree:

> The eosio.bios contract can be found in the contracts folder of yoru eosio source code. This command assumes it is being executed from the root of the eosio source, but you could execute it from anywhere by specifying the full path to ${EOSIO_SOURCE}/contracts/eosio.bios.
...
> ```cleos set contract eosio contracts/eosio.bios -p eosio```

On a fresh pull and build, the .wast lives under ${EOSIO_SOURCE}/**build**/contracts/eosio.bios

**Comment by Amthieu** [comment]
Same error later in the [Create Token Contract](https://github.com/EOSIO/eos/blob/09affc02fcc30fe7f04150087d4411b786775045/TUTORIAL.md#create-token-contract) section.

It should be noted that both corresponding files in the [wiki](https://github.com/EOSIO/eos/wiki) ([your error](https://github.com/EOSIO/eos/wiki/Tutorial-Getting-Started-With-Contracts#loading-the-bios-contract) and [mine](https://github.com/EOSIO/eos/wiki/Tutorial-eosio-token-Contract#eosiotoken-exchange-and-eosiomsig-contracts)) don't contain those errors. Updating the TUTORIAL.md file to match the current wiki files is all that's needed.

**Comment by andriantolie** [comment]
Checked in here https://github.com/EOSIO/eos/wiki/Tutorial-Getting-Started-With-Contracts#loading-the-bios-contract and it seems this issue is fixed
