### ISSUE TITLE
Generate Block and Push Block desync on CPU usage

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2105]
The root of the problem is that we are not propagating the number of signatures into the resource usage calculation during `transaction_trace chain_controller::push_transaction(const packed_transaction&);`

A fix is already in bound.

**Comment by taokayan** [comment]
Unitest case for max_cpu_usage was added. It also verify the synchronization between the producer chain and validator chain. see https://github.com/EOSIO/eos/pull/2172
