### ISSUE TITLE
wrong command at wiki/Local-Environment#351-execute-cleos-commands

### ISSUE THREAD

**Issue by slepher** [EOSIO/eos#2108]
location:
https://github.com/EOSIO/eos/wiki/Local-Environment#351-execute-cleos-commands

```diff
- $ alias cleos='docker-compose exec keosd /opt/eos/bin/cleos -H nodeos'
+ $ alias cleos='docker-compose exec keosd /opt/eosio/bin/cleos -H nodeosd'
```

**Comment by naveed949** [comment]
Thanks @slepher A day back `- $ alias cleos='docker-compose exec keosd /opt/eos/bin/cleos -H nodeos'` was working fine and today when I again run it gives me no such file 'cleos' when I replaced eos in path to eosio the error resolve but it seems cleos not connected to nodeos, So finally I changed nodeos to nodeosd and everything working good as day before. Don't why it happens in a day. Please anyone can explain.
Thaks in advance

**Comment by andriantolie** [comment]
Yes. It should be `alias cleos='docker-compose exec keosd /opt/eosio/bin/cleos -u http://nodeosd:8888 --wallet-url http://localhost:8900'` instead. For docker-compose, the markdown in https://github.com/EOSIO/eos/tree/master/Docker is already updated. I'm going to close this issue
