### ISSUE TITLE
eosd 'Segmentation fault' error on publishing the contract

### ISSUE THREAD

**Issue by MrXtar** [EOSIO/eos#211]
From this tutor: https://eosio.github.io/eos/group__eosc.html

After the creating currency account, i'm trying to publish the currency contract with command
`./eosc setcode currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi`

eosc output:
![image](https://user-images.githubusercontent.com/19951620/29516167-0403f48a-8678-11e7-98f7-a8cc0e4fb0f7.png)

eosd closing with error:
![image](https://user-images.githubusercontent.com/19951620/29516197-2bac13aa-8678-11e7-8624-3dfbecd36c18.png)

If I try to run eosd after that:
![image](https://user-images.githubusercontent.com/19951620/29518212-20bf5dd6-8681-11e7-9b8a-88c768f4ec23.png)

**Comment by nathanhourt** [comment]
I am unable to reproduce this issue on the master branch... Are you able to reproduce it with the latest code?

**Comment by MrXtar** [comment]
Hmm. `git clone https://github.com/eosio/eos --recursive` now and got this error again:

![image](https://user-images.githubusercontent.com/19951620/29610190-1ed08626-8802-11e7-8747-fc8f02a582f3.png)

**Comment by nathanhourt** [comment]
Hmm, I just saw errors a lot like this that began occurring after I switched branches until I started over with a fresh blockchain, which seems like database incompatibility between versions of the software. If you start over with a fresh blockchain, do you still get these errors?

**Comment by stevenzhang68** [comment]
I have the very same error. I also post issue #234 .

**Comment by MrXtar** [comment]
Recorded video with that problem: https://www.youtube.com/watch?v=l_7U_r9lgt0

Btw, I can give root access to my test server for experiments.

**Comment by MrXtar** [comment]
Uploaded eosd stderr output:
[eosd_err.txt](https://github.com/EOSIO/eos/files/1256713/eosd_err.txt)

**Comment by MrXtar** [comment]
gdb shows:

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff733136e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6

**Comment by MrXtar** [comment]
It seems that I used the wrong compiler
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
