### ISSUE TITLE
Remove references to testnet from docs

### ISSUE THREAD

**Issue by rbw3821** [EOSIO/eos#2115]
Since there will be no Testnet released for RC1.  Need to make sure following Wiki pages are updated accordingly.  We should pull out these section (for now).  The updated Wiki is following the planned readme.io document architecture, so these changes need to be aligned with that.

https://github.com/EOSIO/eos/wiki/Testnet%3A%20Public#web-wallet-end-users

https://github.com/EOSIO/eos/wiki/Testnet%3A%20Public#accounts-on-testnet

**Comment by andriantolie** [comment]
Checked the wiki and verified
