### ISSUE TITLE
Restore async capability in http_plugin once it is safe to do so

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#212]
For reference, the commit that disabled asynchronous processing is here:
https://github.com/EOSIO/eos/commit/f24e686cb5fe3411729702a66cec7c2fb2a79309

this was causing issues due to parts of the code not being thread-safe yet.

**Comment by andriantolie** [comment]
@wanderingbort I can't find http_thread and http_ios in the latest code. Is this issue still relevant?

**Comment by brianjohnson5972** [comment]
@wanderingbort , since this is so old, and the code has changed so many times over, I am closing this issue.
