### ISSUE TITLE
Error :  run ./nodeos

### ISSUE THREAD

**Issue by okluoquan** [EOSIO/eos#2122]
789545ms thread-0   main.cpp:95                   main                 ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: content of memory does not match data expected by executable
rethrow content of memory does not match data expected by executable: 
    {"my->genesis_file.generic_string()":"/Users/xxxxxx/Library/Application Support/eosio/nodeos/config/genesis.json","what":"content of memory does not match data expected by executable"}
    thread-0  chain_plugin.cpp:212 plugin_startup

**Comment by jgiszczak** [comment]
`rm -r ~/.local/share/eosio/nodeos/data/blocks/`.
`rm -r ~/.local/share/eosio/nodeos/data/shared_mem/`

The in-memory database maintained by the daemon is changing format multiple times per day right now, and is not expected to be compatible across unreleased versions.

**Comment by okluoquan** [comment]
thanks.it is ok.
