### ISSUE TITLE
Move the network diagram files out of the root repo directory

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2128]
There are some files released to the network topology diagrams (see df8e61912cb34ecb7b0b7d02ccd74e92eaecf43d), please move them into a logical location that is not in the root.

This can slide out of RC1 if need be, but I would like to clean the root repo directory up a bit.

**Comment by gleehokie** [comment]
We are not going to do this for RC1 since they are referenced by the wiki.

**Comment by andriantolie** [comment]
The images are not in root repo anymore. This is done
