### ISSUE TITLE
eos account has no authorities

### ISSUE THREAD

**Issue by nathanhourt** [EOSIO/eos#213]
Currently, the chain is initializing the eos account with no authorities. This violates the invariant that all accounts have at least an owner and active authority.

What should eos's authorities be?

This replaces #209, which is the error thrown when `lookup_minimum_permission` attempts to load eos's active authority.

**Comment by nathanhourt** [comment]
The above commit, which sets eos' auths to unsatisfiable, fixes the error in #209

**Comment by bytemaster** [comment]
This looks like a reasonable approach

**Comment by heifner** [comment]
@nathanhourt Looks like this was never merged.

**Comment by nathanhourt** [comment]
Yeah, I'd wondered what happened here. I remember fixing this, and I thought it got merged in, but it appears to have been lost somewhere along the way... One more try, then? https://github.com/EOSIO/eos/pull/471

**Comment by heifner** [comment]
Merged. Closing.
