### ISSUE TITLE
Update Smart Contract

### ISSUE THREAD

**Issue by navcsdev** [EOSIO/eos#2130]
On lastest code brand master, I use cmd to update contract 
`cleos set contract [OPTIONS] account contract-dir [wast-file] [abi-file]`
but when I only change the file `.abi` I get the error 
```
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
account.code_version != code_id: contract is already running this version of code
```
Can I only change the file `.abi` and update the smart contract ? 🙇

**Comment by pokerchain** [comment]
that means you have no change at this contract.

**Comment by navcsdev** [comment]
@pokerchain I change the `.abi` file but I can not update !

**Comment by blackwatertepes** [comment]
I'm having the same issue. I've update both the contract ABI, and the WAST, but the error code is telling me that the latest version is already running
`account.code_version != code_id: contract is already running this version of code`

The wiki/docs make no reference as to how to update already deployed contract, either.

**Comment by PaulCalabrese** [comment]
Currently, the code and abi are done in separate operations, but the abi
will not be set if the code is not set. If you only want to set an abi, all
you can do now is make a minor change to your contract (something that will
change the hash of the wast) and recompile. Your subsequent "set contract"
should update both.



Paul Calabrese

**Comment by blackwatertepes** [comment]
Thanks @PaulCalabrese for the info. However, in my case, the .wast has definitely changed. I'm using the tic tac toe example, and changed the namespace to 'tic', which produced a different .wast. After deploying the contract, and running `cleos get code tic`, i'm getting the same hash.

**Comment by blackwatertepes** [comment]
@PaulCalabrese How can get more information to debug this? Perhaps the deployed contract code, and not just the hash?

**Comment by PaulCalabrese** [comment]
This will retrieve the wast code currently in the contract:
cleos get code -c code.wast currency

**Comment by blackwatertepes** [comment]
Thanks @PaulCalabrese. Not sure what I did wrong. But all is well, now. Thanks for the tip.

**Comment by OuterSpaceTears** [comment]
mark
