### ISSUE TITLE
readme is out dated

### ISSUE THREAD

**Issue by realcom** [EOSIO/eos#2131]
get account currency showed diffrent result

current readme
{
  "account_name": "currency",
  "eos_balance": "0.0000 EOS",
  "staked_balance": "0.0001 EOS",
  "unstaking_balance": "0.0000 EOS",
  "last_unstaking_time": "2035-10-29T06:32:22",
   ...
}

but in latest version
```
{"account_name": "currency",
 "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6bhtfGKhuZ73Xfiyp3TR94cpTPXVGKssKTAH8Vjm6c82Gi4PRz",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6pUEEqY3G2JtZj26Bo3Yww4L1HbT7mbyib8fk8nm3bGCgFFyUE",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}
```

**Comment by max-block** [comment]
Yes, I still don't know how to get eos_balance for an account :)

**Comment by rbw3821** [comment]
The currency contract has been changed as of Dawn 3.0.  The more up-to-date example to use can be found in the wiki, https://github.com/EOSIO/eos/wiki/Tutorial-eosio-token-Contract 

If you still want to try to get the eos_balance for what you were doing above, the attached file provides some instructions that should help.  This was originally includes in the Local Environment section in the wiki, just after the section on Creating and Launching a Single Node Testnet.  It was removed in deference to the eosio.token example.  It looks like you've already done the first set of steps.  You might be able to just skip down through the file to the part where it says to create, then issue the currency, (~line #125) and resume from there.

[accounts_example.txt](https://github.com/EOSIO/eos/files/1912377/accounts_example.txt)
