### ISSUE TITLE
Make intrinsics that read data into a buffer consistent WRT undersized buffers

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2132]
# Description

We have several intrinsics that will push data into buffers supplied by WebAssembly.  When the buffer provided is not properly sized to hold the data requested we do one of three things:
 
 - Copy nothing and return the size needed to copy the full data
 - Copy up to the buffer size and return the size copied
 - Copy up to the buffer size and return the size needed to copy the full data

We should pick one and make all of our intrinsics comply.

A non exhaustive list of such intrinsics is:
 - [x] get_context_free_data
 - [x] get_blockchain_parameters_packed
 - [x] get_active_producers
 - [x] read_action_data
 - [x] db_get_i64
 - [x] read_transaction

**Comment by bytemaster** [comment]
A related issue is whether we want to support "streaming" reads or "random access" reads. 

This has huge implications for writing efficient contracts with minimal CPU and RAM usage.

**Comment by brianjohnson5972** [comment]
We would need to add an offset to start from if we wanted to support
streaming/random access.

I think copying over a maximum of the passed in bytes and returning the
actual copied bytes, with the special case of size == 0 returning the
required size is the "easiest" to explain.

**Comment by heifner** [comment]
Didn't find any more intrinsics than those listed that needed to be updated.
