### ISSUE TITLE
resolve: Host not found (authoritative)

### ISSUE THREAD

**Issue by barray888** [EOSIO/eos#2133]
~  cleos wallet list
Wallets:
717068ms thread-0   main.cpp:1186                 main                 ] Failed with error: resolve: Host not found (authoritative) (13)
resolve: Host not found (authoritative):

**Comment by barray888** [comment]
I  have switched WIFI connection and it works .
But i switched back , it still have error  "host not found"

**Comment by andriantolie** [comment]
@barray888 Do you still have similar issue with latest code?

**Comment by andriantolie** [comment]
Please reopen this issue if you still encounter the problem
