### ISSUE TITLE
centos 7 build error

### ISSUE THREAD

**Issue by xnfy520** [EOSIO/eos#2139]
[ 94%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/wasm_eosio_validation.cpp.o
In file included from /root/eos/libraries/chain/include/eosio/chain/wasm_interface_private.hpp:5:0,
                 from /root/eos/libraries/chain/wasm_interface.cpp:9:
/root/eos/libraries/chain/include/eosio/chain/webassembly/binaryen.hpp: In function ‘T eosio::chain::webassembly::binaryen::convert_literal_to_native(wasm::Literal&) [with T = float64_t]’:
/root/eos/libraries/chain/include/eosio/chain/webassembly/binaryen.hpp:202:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return reinterpret_cast<float64_t&>(val);
                                           ^
/root/eos/libraries/chain/include/eosio/chain/webassembly/binaryen.hpp:202:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/root/eos/libraries/chain/include/eosio/chain/webassembly/binaryen.hpp: In function ‘T eosio::chain::webassembly::binaryen::convert_literal_to_native(wasm::Literal&) [with T = float32_t]’:
/root/eos/libraries/chain/include/eosio/chain/webassembly/binaryen.hpp:208:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return reinterpret_cast<float32_t&>(val);
                                           ^
/root/eos/libraries/chain/include/eosio/chain/webassembly/binaryen.hpp:208:43: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
In file included from /root/eos/libraries/chain/include/eosio/chain/wasm_interface_private.hpp:7:0,
                 from /root/eos/libraries/chain/wasm_interface.cpp:9:
/root/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In static member function ‘static void eosio::chain::wasm_injections::injector_utils::build_type_slots(IR::Module&)’:
/root/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:37:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
          for ( int i=0; i < mod.types.size(); i++ ) {
                         ~~^~~~~~~~~~~~~~~~~~
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘float eosio::chain::softfloat_api::_eosio_f32_add(float, float)’:
/root/eos/libraries/chain/wasm_interface.cpp:207:47: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<float*>(&ret);
                                               ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘float eosio::chain::softfloat_api::_eosio_f32_sub(float, float)’:
/root/eos/libraries/chain/wasm_interface.cpp:211:47: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<float*>(&ret);
                                               ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘float eosio::chain::softfloat_api::_eosio_f32_div(float, float)’:
/root/eos/libraries/chain/wasm_interface.cpp:215:47: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<float*>(&ret);
                                               ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘float eosio::chain::softfloat_api::_eosio_f32_mul(float, float)’:
/root/eos/libraries/chain/wasm_interface.cpp:219:47: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<float*>(&ret);
                                               ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘float32_t eosio::chain::softfloat_api::to_softfloat32(float)’:
/root/eos/libraries/chain/wasm_interface.cpp:644:49: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<float32_t*>(&f);
                                                 ^
/root/eos/libraries/chain/wasm_interface.cpp:644:49: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘float64_t eosio::chain::softfloat_api::to_softfloat64(double)’:
/root/eos/libraries/chain/wasm_interface.cpp:647:49: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<float64_t*>(&d);
                                                 ^
/root/eos/libraries/chain/wasm_interface.cpp:647:49: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘float eosio::chain::softfloat_api::from_softfloat32(float32_t)’:
/root/eos/libraries/chain/wasm_interface.cpp:650:45: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<float*>(&f);
                                             ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘double eosio::chain::softfloat_api::from_softfloat64(float64_t)’:
/root/eos/libraries/chain/wasm_interface.cpp:653:46: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<double*>(&d);
                                              ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘double eosio::chain::compiler_builtins::__floatsidf(int32_t)’:
/root/eos/libraries/chain/wasm_interface.cpp:1265:48: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<double*>(&ret);
                                                ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘void eosio::chain::compiler_builtins::__extenddftf2(float128_t&, double)’:
/root/eos/libraries/chain/wasm_interface.cpp:1279:52: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          ret = f64_to_f128( float64_t{*(uint64_t*)&in} );
                                                    ^~
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘uint64_t eosio::chain::math_api::double_add(uint64_t, uint64_t)’:
/root/eos/libraries/chain/wasm_interface.cpp:1332:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          DOUBLE c = DOUBLE(*reinterpret_cast<double *>(&a))
                                                          ^
/root/eos/libraries/chain/wasm_interface.cpp:1333:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
                   + DOUBLE(*reinterpret_cast<double *>(&b));
                                                          ^
/root/eos/libraries/chain/wasm_interface.cpp:1335:51: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<uint64_t *>(&res);
                                                   ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘uint64_t eosio::chain::math_api::double_mult(uint64_t, uint64_t)’:
/root/eos/libraries/chain/wasm_interface.cpp:1340:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          DOUBLE c = DOUBLE(*reinterpret_cast<double *>(&a))
                                                          ^
/root/eos/libraries/chain/wasm_interface.cpp:1341:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
                   * DOUBLE(*reinterpret_cast<double *>(&b));
                                                          ^
/root/eos/libraries/chain/wasm_interface.cpp:1343:51: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<uint64_t *>(&res);
                                                   ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘uint64_t eosio::chain::math_api::double_div(uint64_t, uint64_t)’:
/root/eos/libraries/chain/wasm_interface.cpp:1348:64: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          DOUBLE divisor = DOUBLE(*reinterpret_cast<double *>(&b));
                                                                ^
/root/eos/libraries/chain/wasm_interface.cpp:1350:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          DOUBLE c = DOUBLE(*reinterpret_cast<double *>(&a)) / divisor;
                                                          ^
/root/eos/libraries/chain/wasm_interface.cpp:1352:51: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<uint64_t *>(&res);
                                                   ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘uint32_t eosio::chain::math_api::double_eq(uint64_t, uint64_t)’:
/root/eos/libraries/chain/wasm_interface.cpp:1357:54: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return DOUBLE(*reinterpret_cast<double *>(&a)) == DOUBLE(*reinterpret_cast<double *>(&b));
                                                      ^
/root/eos/libraries/chain/wasm_interface.cpp:1357:97: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return DOUBLE(*reinterpret_cast<double *>(&a)) == DOUBLE(*reinterpret_cast<double *>(&b));
                                                                                                 ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘uint32_t eosio::chain::math_api::double_lt(uint64_t, uint64_t)’:
/root/eos/libraries/chain/wasm_interface.cpp:1362:54: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return DOUBLE(*reinterpret_cast<double *>(&a)) < DOUBLE(*reinterpret_cast<double *>(&b));
                                                      ^
/root/eos/libraries/chain/wasm_interface.cpp:1362:96: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return DOUBLE(*reinterpret_cast<double *>(&a)) < DOUBLE(*reinterpret_cast<double *>(&b));
                                                                                                ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘uint32_t eosio::chain::math_api::double_gt(uint64_t, uint64_t)’:
/root/eos/libraries/chain/wasm_interface.cpp:1367:54: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return DOUBLE(*reinterpret_cast<double *>(&a)) > DOUBLE(*reinterpret_cast<double *>(&b));
                                                      ^
/root/eos/libraries/chain/wasm_interface.cpp:1367:96: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return DOUBLE(*reinterpret_cast<double *>(&a)) > DOUBLE(*reinterpret_cast<double *>(&b));
                                                                                                ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘uint64_t eosio::chain::math_api::double_to_i64(uint64_t)’:
/root/eos/libraries/chain/wasm_interface.cpp:1372:54: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return DOUBLE(*reinterpret_cast<double *>(&n)).convert_to<int64_t>();
                                                      ^
/root/eos/libraries/chain/wasm_interface.cpp: In member function ‘uint64_t eosio::chain::math_api::i64_to_double(int64_t)’:
/root/eos/libraries/chain/wasm_interface.cpp:1378:51: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
          return *reinterpret_cast<uint64_t *>(&res);
                                                   ^
In file included from /root/eos/libraries/chain/include/eosio/chain/wasm_interface_private.hpp:7:0,
                 from /root/eos/libraries/chain/wasm_interface.cpp:9:
/root/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)0; IR::ValueType ...Params = {(IR::ValueType)1}; int32_t = int]’:
/root/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:167:116:   required from here
/root/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:78:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for ( int i=0; i < module.exports.size(); i++ ) {
                            ~~^~~~~~~~~~~~~~~~~~~~~~~
/root/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)4; IR::ValueType ...Params = {(IR::ValueType)3}; int32_t = int]’:
/root/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:535:114:   required from here
/root/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:78:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/root/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)3; IR::ValueType ...Params = {(IR::ValueType)4}; int32_t = int]’:
/root/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:549:113:   required from here
/root/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:78:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
g++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [libraries/chain/CMakeFiles/eosio_chain.dir/build.make:207：libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o] 错误 4
make[2]: *** 正在等待未完成的任务....
make[1]: *** [CMakeFiles/Makefile2:1816：libraries/chain/CMakeFiles/eosio_chain.dir/all] 错误 2
make: *** [Makefile:163：all] 错误 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by pacificcode** [comment]
Well need a little information on your system and build tools to help out.
run the script ./eosio_build.sh
Paste all the install information when the script begins down to:
>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOS.IO

**Comment by xnfy520** [comment]
@pacificcode 

[root@izwz9gjb9m90kyr37781thz eos]# ./eosio_build.sh 

	Beginning build version: 1.2
	2018年 04月 05日 星期四 14:43:27 UTC
	git head id: 13a30de00856495ebf57c9c6075d50a019a659a6
	Current branch: * master

	ARCHITECTURE: Linux

	OS name: CentOS Linux
	OS Version: 7
	CPU speed: 2494Mhz
	CPU cores: 2
	Physical Memory: 3790 Mgb
	Disk install: /dev/vda1
	Disk space total: 39G
	Disk space available: 21G

	Checking Yum installation
	Yum installation found at /usr/bin/yum.

	Checking installation of Centos Software Collections Repository.

	Centos Software Collections Repository found.

	Enabling Centos devtoolset-7.

	Centos devtoolset-7 successfully enabled.

	Enabling Centos python3 installation.

	Centos python3 successfully enabled.

	Updating YUM repository.
已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
No packages marked for update

	YUM repository successfully updated.

	Checking YUM for installed dependencies.

	Package git  NOT  found.
	Package autoconf  NOT  found.
	Package automake  NOT  found.
	Package libtool  NOT  found.
	Package ocaml.x86_64  NOT  found.
	Package doxygen  NOT  found.
	Package libicu-devel.x86_64  NOT  found.
	Package bzip2-devel.x86_64  NOT  found.
	Package openssl-devel.x86_64  NOT  found.
	Package gmp-devel.x86_64  NOT  found.
	Package python-devel.x86_64  NOT  found.
	Package gettext-devel.x86_64  NOT  found.

	The following dependencies are required to install EOSIO.

	1. git
	2. autoconf
	3. automake
	4. libtool
	5. ocaml.x86_64
	6. doxygen
	7. libicu-devel.x86_64
	8. bzip2-devel.x86_64
	9. openssl-devel.x86_64
	10. gmp-devel.x86_64
	11. python-devel.x86_64
	12. gettext-devel.x86_64
	

	Do you wish to install these dependencies?
1) Yes
2) No
#? 1


	Installing dependencies

已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
软件包 git-1.8.3.1-12.el7_4.x86_64 已安装并且是最新版本
软件包 autoconf-2.69-11.el7.noarch 已安装并且是最新版本
软件包 automake-1.13.4-3.el7.noarch 已安装并且是最新版本
软件包 libtool-2.4.2-22.el7_3.x86_64 已安装并且是最新版本
软件包 ocaml-4.01.0-22.7.el7_2.x86_64 已安装并且是最新版本
软件包 1:doxygen-1.8.5-3.el7.x86_64 已安装并且是最新版本
软件包 libicu-devel-50.1.2-15.el7.x86_64 已安装并且是最新版本
软件包 bzip2-devel-1.0.6-13.el7.x86_64 已安装并且是最新版本
软件包 1:openssl-devel-1.0.2k-8.el7.x86_64 已安装并且是最新版本
软件包 1:gmp-devel-6.0.0-15.el7.x86_64 已安装并且是最新版本
软件包 python-devel-2.7.5-58.el7.x86_64 已安装并且是最新版本
软件包 gettext-devel-0.19.8.1-2.el7.x86_64 已安装并且是最新版本
无须任何处理

	YUM dependencies installed successfully.

	Checking for CMAKE.
	CMAKE found

	Checking for boost libraries
	Boost 1.66 found at /root/opt/boost_1_66_0

	Checking for MongoDB installation.
	MongoDB config found at /root/opt/mongodb/mongod.conf.

	Checking for MongoDB C++ driver.
	Mongo C++ driver found at /usr/local/lib/libmongocxx.so.

	Checking for secp256k1-zkp
	secp256k1 found

	Checking for binaryen
	Binaryen found at /root/opt/binaryen

	Checking for LLVM with WASM support.
	WASM found at /root/opt/wasm


>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOS.IO

-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
-- Configuring Eos on Linux
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using WASM clang => /root/opt/wasm/bin/clang
-- Using WASM llc => /root/opt/wasm/bin/llc
-- Using WASM llvm-link => /root/opt/wasm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Configuring fc to build on Unix/Apple
-- Setting up OpenSSL root and include vars to /usr/include/openssl, /usr/include/openssl/include
-- Found OpenSSL: /usr/lib64/libcrypto.so  
-- zlib found
-- bzip2 found
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   unit_test_framework
--   locale
-- Configuring ChainBase on Linux
-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   program_options
--   unit_test_framework
--   locale
-- Configuring AppBase on Linux
-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: /usr/local/lib/libbsoncxx.so
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: /usr/local/lib/libmongocxx.so;/usr/local/lib/libbsoncxx.so
-- Git commit revision: 13a30de0
-- Git commit revision: 13a30de0
-- Git commit revision: 13a30de0
-- Configuring done
WARNING: Target "chainbase_test" requests linking to directory "/usr/include/openssl".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /root/eos/build
[  0%] Building CXX object externals/binaryen/src/ast/CMakeFiles/ast.dir/ExpressionAnalyzer.cpp.o

....

[ 94%] Building CXX object

**Comment by pacificcode** [comment]
You have an old version of the repo.
I would recommend throwing out your current eos directory and start fresh (you may also want to build this as a non-root user as well).

git clone https://github.com/EOSIO/eos.git --recursive
cd eos/
git submodule update --init --recursive
./eosio_build.sh

**Comment by BestSilent** [comment]
@xnfy520  
you  problem solving？
I have the same problem.

**Comment by xnfy520** [comment]
@BestSilent
Follow this, Can run normally
https://github.com/EOSIO/eos/tree/dawn-v3.0.0#manualdepcentos 
Also need to install
`yum install gcc`
`yum install gcc-c++`

**Comment by pacificcode** [comment]
@BestSilent & @xnfy520 
The following will install a recent version of gcc and the autotools binaries.
sudo yum --enablerepo=extras install centos-release-scl
sudo yum update
sudo yum install -y devtoolset-7
scl enable devtoolset-7 bash
sudo yum install -y python33.x86_64
scl enable python33 bash
