### ISSUE TITLE
Producer Account Threshold is set wrong.

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#2141]
Bart Wyatt, [Apr 5, 2018 at 11:32:58 AM]:
...producers account properly lists the producer accounts BUT expects a threshold of 14

which cannot be achieved until you have at least 14 producers

**Comment by andriantolie** [comment]
The new formula (`((value * percentage) + eosio::chain::config::percent_100 - eosio::chain::config::percent_1)  / eosio::chain::config::percent_100`) works fine regardless the number of existing producers
