### ISSUE TITLE
could not gain write access to the shared memory file

### ISSUE THREAD

**Issue by sailei1** [EOSIO/eos#2142]
![image](https://user-images.githubusercontent.com/1625409/38375936-fd7e4bc8-3929-11e8-9f55-cd12481b412d.png)
how to config? 
how to fix?

**Comment by sailei1** [comment]
Last login: Thu Apr  5 23:51:10 on ttys001
/Users/zhangsailei/github/eos/build/programs/nodeos/nodeos ; exit;
sai:~ zhangsailei$ /Users/zhangsailei/github/eos/build/programs/nodeos/nodeos ; exit;
3215481ms thread-0   chain_plugin.cpp:96           plugin_initialize    ] initializing chain plugin
3215481ms thread-0   wallet_plugin.cpp:39          plugin_initialize    ] initializing wallet plugin
3215481ms thread-0   http_plugin.cpp:141           plugin_initialize    ] host: 127.0.0.1 port: 8888 
3215482ms thread-0   http_plugin.cpp:144           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
3215482ms thread-0   net_plugin.cpp:2622           plugin_initialize    ] Initialize net plugin
3215482ms thread-0   net_plugin.cpp:2644           plugin_initialize    ] Setting net_plugin logging level to info
3215482ms thread-0   net_plugin.cpp:2672           plugin_initialize    ] host: 0.0.0.0 port: 9876 
3215482ms thread-0   net_plugin.cpp:2748           plugin_initialize    ] my node_id is 4954871ce17deffbfd94d99e11c26cc6d2ceaf3d22a07600d118e98c525d1a43
3215482ms thread-0   main.cpp:90                   main                 ] nodeos version 4ec15c3a
3215483ms thread-0   main.cpp:91                   main                 ] eosio root is /Users/zhangsailei/Library/Application Support
3215483ms thread-0   chain_plugin.cpp:209          plugin_startup       ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: could not gain write access to the shared memory file
rethrow could not gain write access to the shared memory file: 
    {"my->genesis_file.generic_string()":"/Users/zhangsailei/Library/Application Support/eosio/nodeos/config/genesis.json","what":"could not gain write access to the shared memory file"}
    thread-0  chain_plugin.cpp:209 plugin_startup
3215483ms thread-0   chain_plugin.cpp:209          plugin_startup       ] my->genesis_file.generic_string(): /Users/zhangsailei/Library/Application Support/eosio/nodeos/config/genesis.json 
3215485ms thread-0   main.cpp:95                   main                 ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: could not gain write access to the shared memory file
rethrow could not gain write access to the shared memory file: 
    {"my->genesis_file.generic_string()":"/Users/zhangsailei/Library/Application Support/eosio/nodeos/config/genesis.json","what":"could not gain write access to the shared memory file"}
    thread-0  chain_plugin.cpp:209 plugin_startup
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by filmio** [comment]
Yep, getting the same error here after a clean build of 3.0.

**Comment by wessies** [comment]
I get exactly the same error. I think it has to do with this already given problem a while back (https://github.com/EOSIO/eos/issues/58). Question here is how rerun the first writer in order to start producing blocks again. ( I guess a simple solution is to delete all EOS files now and re-install the whole thing). However I think thats far from the optimal solution.

**Comment by Dhhhj** [comment]
I am having the same issue, its after I killed nodeos after its first run, permissions are correct on the file so I don't understand, has anyone fixed this?

**Comment by kenorb** [comment]
Make sure you're not running another `nodeos` process:

    # ps wuax | grep nodeos

If so, kill the previous one.

**Comment by Dhhhj** [comment]
thanks kenord i was using `top` to see if the nodeos process was running, and it wouldn't show any.

Is there an internal command to stop nodeos?

**Comment by jgiszczak** [comment]
There is no internal command to stop nodeos.  That's properly the domain of your operating system.  If you configure nodeos as a systemd service, you would use systemd start and stop commands.  If you configure nodeos as a FreeBSD rc.d service, you would use FreeBSD start and stop commands.  Process management is not a feature of EOS.IO.

`top` is not a good choice to see if processes are running.  It sorts by activity by default, and an idle nodeos process uses essentially no CPU time, so it falls into the noise of the rest of the system.
