### ISSUE TITLE
Add documentation about new database API to Wiki

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2159]
This will initially be sparse documentation (breadth not depth) on our new DB API, so we can get this into the public Wiki sooner rather than later. We will then continue to add to it over time. 

The documentation will cover both the new C DB API and the new C++ `multi_index` class that makes working with the EOS.IO DB system much easier and more convenient.

**Comment by stvenyin** [comment]
See.Boost C++ multi_index Class ,DB API
