### ISSUE TITLE
Create Account Fails on CLEOS

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#2160]
./cleos create account eosio dan EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
2468798ms thread-0   main.cpp:1158                 main                 ] Failed with error: Assert Exception (10)
itr != structs.end(): Unknown struct
Failed to serialize type

**Comment by bytemaster** [comment]
Setting the bios contract first will fix this.
The command succeeds, but then fails when attempting to pretty print.
We should probably catch ABI issues and dump the JSON if the pretty-print fails for some reason.

**Comment by larryk85** [comment]
This failed to fix the issue.  I have a fix that fixes this for all problems related to cleos before any system contract is set.

**Comment by andriantolie** [comment]
Creating account without setting the bios contract beforehand now succeeds.
