### ISSUE TITLE
./cleos create account --- Failed with error: Assert Exception

### ISSUE THREAD

**Issue by okluoquan** [EOSIO/eos#2170]
$ ./cleos create account eosio my EOS5gK3pEU9qkCbJm2x1JC9daqVuYzNThih11HiG7phdH47vqBDrq EOS6h5cchqPDbnspR29qMuTCzfUYXxR5NmTZ414PXGpdivFtGuirG
1429923ms thread-0   main.cpp:1158                 main                 ] Failed with error: Assert Exception (10)
itr != structs.end(): Unknown struct 
Failed to serialize type

**Comment by glemmaPaul** [comment]
I might be late on this, but this happened to me as well on a fresh install. For me setting the eosio.bios contract helped me out, as I forgot to do that before creating the accounts.

https://github.com/EOSIO/eos/wiki/Tutorial-Getting-Started-With-Contracts#loading-the-bios-contract

**Comment by farhan19aug** [comment]
@glemmaPaul  Thanks alot .. Work for me
