### ISSUE TITLE
Docker Build Fail

### ISSUE THREAD

**Issue by wanf425** [EOSIO/eos#2171]
when I run 

> docker build . -t eosio/eos

following error be reported

> Step 8/14 : COPY --from=builder /eos/Docker/config.ini /eos/genesis.json /
> COPY failed: stat /var/lib/docker/overlay2/e02215a633ddaf279e5571f5f2fc548d5b6fd77546e33e1adf8fbc689edc1cc2/merged/eos/genesis.json: no such file or directory

ATC:
Verify docker build does not fail.

**Comment by hxzqlh** [comment]
+1

**Comment by stvenyin** [comment]
Thanks！

**Comment by stvenyin** [comment]
docker images
docker stop coniter
docker rmi imageid
