### ISSUE TITLE
Add sub-modules to tar.gz release file

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2178]
The sub-modules are missing forcing the user to build them from source.  They should be included in the file.

**Comment by heifner** [comment]
Does not appear to be supported by Github: https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release

**Comment by gleehokie** [comment]
Should we be releasing the submodules as well and then providing instructions for the list of submodules that needs to be downloaded too?

**Comment by gleehokie** [comment]
After discussion we decided that we are not going to support this.  Everyone should use git to pull our source code.

**Comment by spoonincode** [comment]
Then we need to remove the download links.
