### ISSUE TITLE
cleos doesn't complain about locked wallet

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eos#2182]
````
cleos create account eosio eosio.msig EOS7vg7ZhTayydfca1kjhDNrDvQigcUdicA3d8FFhuQjAPtn3Hqui EOS7vg7ZhTayydfca1kjhDNrDvQigcUdicA3d8FFhuQjAPtn3Hqui
Error 3030002: signatures do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and you wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"eosio","permission":"active"}', but does not have signatures for it.
````
it failed because wallet was locked. So, it was not able to sign the transaction.
It should complain about locked wallet.

**Comment by andriantolie** [comment]
I just realize that with the latest update, all transactions need to have at least one signature, so I guess it should be fine

**Comment by andriantolie** [comment]
PR Added #2496

ATC:
1. Send tx with no available wallet and ensure it shows the following error
![screen shot 2018-04-19 at 11 34 03 am](https://user-images.githubusercontent.com/6541441/38970002-b331a85c-43c5-11e8-8ed1-6b2038e8e6de.png)
2. Send tx with no unlocked wallet and ensure it shows the following error
![screen shot 2018-04-19 at 11 33 58 am](https://user-images.githubusercontent.com/6541441/38970010-bf632682-43c5-11e8-95ae-6ea85ef426a9.png)
