### ISSUE TITLE
regproducer action use of "bytes" type is confusing

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#2184]
The eosio.system/regproducer action takes a producer name, a producer key, and a params bundle. However the producer key argument is of type "bytes" which appears to be a string of ascii encoded hexadecimal values. This differs from the eosio.bios contract's setprods action which uses the type "public_key" for the equivalent key value. The "public_key" value is consistent with keys as presented by the existing key manipulating and formatting tools such as the wallet and the default config file generator.

**Comment by andriantolie** [comment]
I see the abi of regproducer is already using public_key value. I'm closing this issue.
