### ISSUE TITLE
cleos get transaction can't retrieve transaction

### ISSUE THREAD

**Issue by kesar** [EOSIO/eos#2186]
Trying to retrieve a transactionId throws this error, current master, new nodeos with mongodb activated:

➜  eos-explorer git:(master) ✗ cleos get transaction b0f65186e3e840dadfd25fb17d4f3591e02c5d13d5ac70b15f0f9a2240e609e8
3502917ms thread-0   main.cpp:1158                 main                 ] Failed with error: unspecified (0)
Transaction with ID b0f65186e3e840dadfd25fb17d4f3591e02c5d13d5ac70b15f0f9a2240e609e8 was indexed as being in block ID 00001c99de91a28913c0fba03fa4f0431862160ae3694dc5683bdfc07fca75d6, but was not found in that block

apigen.js:114 api error => //localhost:8888/v1/account_history/get_transaction {"transaction_id":"b0f65186e3e840dadfd25fb17d4f3591e02c5d13d5ac70b15f0f9a2240e609e8"} Error: {"code":500,"message":"Internal Service Error","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"Transaction with ID b0f65186e3e840dadfd25fb17d4f3591e02c5d13d5ac70b15f0f9a2240e609e8 was indexed as being in block ID 00001c99de91a28913c0fba03fa4f0431862160ae3694dc5683bdfc07fca75d6, but was not found in that block","file":"account_history_plugin.cpp","line_number":142,"method":"find_transaction"}]}}

Screenshot from explorer where it shows that the transaction should belong to that block:

<img width="744" alt="screen shot 2018-04-06 at 18 00 49" src="https://user-images.githubusercontent.com/1288106/38431453-84fe5c60-39c4-11e8-8192-b1ec39023c0e.png">

**Comment by andriantolie** [comment]
@kesar Do you still encounter the same issue with the latest code? You should use history_api_plugin instead account_history_api_plugin now

**Comment by kesar** [comment]
@andriantolie I think its fixed now. 👍
