### ISSUE TITLE
Refactor net_plugin.cpp into multiple files

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#2190]
In order to improve maintainability, the monolithic net_plugin.cpp needs to be spread out across multiple source files. Furthermore, the megaclasses connection and net_plugin_impl should be decomposed into multiple classes that clarify the various roles filled by the current monoliths. 

I have a  workspace in which I've started this refactoring. I should be able to complete that work quickly.

**Comment by brianjohnson5972** [comment]
At this point, any refactoring of net plugin would have far higher risks that would outweigh the benefits of clarity in the code from refactoring.
