### ISSUE TITLE
Bandwidth double billing bug

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2193]
In dawn-v3.0.0, we are currently deduplicating authorizations at the `permission_level` which means that an account that is included in two different authorizations in the same transaction (e.g. `alice@permission1` and `alice@permission2`) would get billed twice.

https://github.com/EOSIO/eos/blob/dawn-v3.0.0/libraries/chain/chain_controller.cpp#L1285-L1296

Instead, each actor involved in authorizations of a transaction should only get billed exactly once for the CPU and network bandwidth of the transaction.

**Comment by taokayan** [comment]
pull request #2366 added for double billing test (same account with different permission names)
