### ISSUE TITLE
Problems with getting started documenation re: creating/listing wallet 

### ISSUE THREAD

**Issue by timogilvie** [EOSIO/eos#2194]
I ran into a few minor issues in the getting started documentation for Dawn3, 

1. I couldn't create or list wallets with just the plugin = eosio::wallet_plugin, as is described. 
I also needed plugin = eosio::wallet_api_plugin 
2. There's no mention that you need to import the private keys into your wallet before you can use them in the next step. Semi-intuitive, but probably worth mentioning. 
3. This line didn't work for me: 
./cleos set contract currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi
But worked when I used the contract-dir:
./cleos set contract currency ../../contracts/currency/
4. I couldn't issue currency until it was created (got: assertion failed: unable to find key). Turns out it was this issue: https://github.com/EOSIO/eos/issues/1725
Should add the following line to create before issuing:
cleos push action currency create '{"issuer":"currency", "maximum_supply": "1000000000.0000 CUR", "can_freeze": 1, "can_recall": 1, "can_whitelist": 1}' -p currency@active
5. The table name used is this command is wrong:
./cleos get table currency currency account
Should be accounts, not account
https://github.com/EOSIO/eos/issues/1742
6. Reading sample contract balances. The commands reference the wrong table again (account instead of account. Also transposes eosio and currency when querying accounts table for eosio balance. Should be:
./cleos get table currency eosio accounts
instead of:
./cleos get table eosio currency account

**Comment by rbw3821** [comment]
Fixes to these will be pushed to the wiki later this week as part of a broader set of wiki changes.
