### ISSUE TITLE
Test Security Delays

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#2195]
1. a great contract is published
2. people put money in, has an invest action.
3. the owner set huge delay for setcode to pass
4. community is reassured
5. rogue is tempted by the 750M accumulated
6. rogue deleteauth, unlinkauth then setcode with the invest method tweaked to transfer the funds to his account
7. .. profit ?!

The test:
1. unlink or relink of setcode to a new authority should have the delay of current setcode authority or active.
2. changing of the auth levels should require same permission level.

Unless owner or active has a delay on it, they can always instantly set permission levels. So for contract to be trusted it should:

1. Set permission levels with required delays on various actions
2. Set owner and active to NULL or something with an even longer delay.

**Comment by brianjohnson5972** [comment]
As these manual (or integration script tests) are performed, also update the [delay unit tests](https://github.com/EOSIO/eos/blob/master/tests/chain_tests/delay_tests.cpp).

**Comment by taokayan** [comment]
pull #2417 committed with extra test case to ensure min delay validation for updateauth, linkauth & unlinkauth
