### ISSUE TITLE
wallet/keosd requirements

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2197]
- [ ] keosd should be spawned automatically by cleos, an RPC password should be provided by a default configuration file that cleos generates and reuses every time it talks to keosd
- [ ] cleos should shutdown keosd when ever all wallets are locked and start it back up on "unlock"
- [x] keosd needs to default to a different HTTP port than nodeosd so we can run both without having to edit the config file of the other
- [ ] cleos should also default to match the situation where nodeosd and keosd are running at the same time on local host
- [ ] user should not have to specify any command line args to use cleos, keosd, and nodeosd in the default behavior
- [ ] consider the case where a browser plugin running on the same machine needs to access keosd

**Comment by brianjohnson5972** [comment]
Right now we start up cleos from the command line and it closes right away.
Will keosd be in a defined location, since we don't want to continue to pass in the port? (i.e. only one per host)

**Comment by wanderingbort** [comment]
We should take care with "consider the case where a browser plugin running
on the same machine needs to access keosd"

We have already proven to ourselves that a trivially constructed CSRF
attack can lock wallets.  It is not hard to imagine that keosd would be
vulnerable to [dns rebinding](https://bou.ke/blog/hacking-developers/) as
well.

**Comment by wanderingbort** [comment]
We should also be very clear that keosd is not safe for multi user
environments in it's current design.

Any unlocked wallet and it's keys are available to any un-authenticated
request.  It is essentially like a sysyrm global ssh-agent with no regard
for user permissions.

**Comment by brianjohnson5972** [comment]
The parts of this task that are still desired are already incorporated and the remainder are OBE or no longer desired.
