### ISSUE TITLE
appbase @ 024ec0d not properly linked in master

### ISSUE THREAD

**Issue by ryanRfox** [EOSIO/eos#22]
Unable to clone current master.

From commit f83884c668850af4dbd713f8f0785621f15305d3

 1 addition & 1 deletion libraries/appbase 
 Submodule appbase updated  from 028da3 to 024ec0 

However, https://github.com/eosio/appbase/tree/024ec0da9931700f25a89e8d80e02f555fe1310a is 404

**Comment by nathanhourt** [comment]
Reopen if not fixed by 9e15ffec18e6b5fcb875ccf70fd6e6ca6df5502d
