### ISSUE TITLE
Light validation on new blocks before adding to fork_db

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2204]
Right now we only check if a received block is linkable to an existing block in fork_db but do no other checks. If the network code also doesn't reject multiple blocks at the same block height from the same node, it opens itself up to an easy DOS attack.

Rather than relying only on the network code to protect against such attacks, we should do some light validation of the received blocks (particularly enough to check that it was correctly signed by an active producer from the perspective of that block) before including it into the fork_db.

**Comment by andriantolie** [comment]
ATC defined in PR #2488 pass
