### ISSUE TITLE
Add tic_tac_toe to build and add unit test

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#2214]
Need to ensure that tic_tac_toe continues to be correct in respect to our contract API so that the tutorial continues to be relevant.

ATC:
Follow the steps in tutorial and verify it functions according to documentation.

**Comment by PaulCalabrese** [comment]
I walked through and verified the tutorial. Minor edits to the tutorial were committed to the privatewiki repository. A problem found with cleos get table was addressed in issue #2350
