### ISSUE TITLE
Build error - libmongoc-static-1.0

### ISSUE THREAD

**Issue by marcinch18** [EOSIO/eos#2215]
Hi,

I was trying to build dwan-v3.0.0 but keep getting folloing error:

> -- Found bsoncxx headers: `/usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: /usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-lm;-pthread
CMake Error at /usr/local/lib/cmake/libmongocxx-static-3.2.0/libmongocxx-static-config.cmake:26 (find_package):
  Could not find a configuration file for package "libmongoc-static-1.0" that
  is compatible with requested version "1.9.2".

> The following configuration files were considered but not accepted:

> /usr/local/lib/cmake/libmongoc-static-1.0/libmongoc-static-1.0-config.cmake, version: 1.8.0

> Call Stack (most recent call first):
  plugins/mongo_db_plugin/CMakeLists.txt:36 (find_package)

> -- Configuring incomplete, errors occurred!
See also "/home/marcin/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/marcin/eos/build/CMakeFiles/CMakeError.log".

> CMAKE building EOSIO has exited with the above error.

Any idea how to fix it?

**Comment by winlin** [comment]
If you want to build dawn-v3.0.0, please follow cmds:
mkdir ~/opt
cd ~/opt
git clone https://github.com/EOSIO/eos --recursive
cd eos
./eosio_build.sh

WARNGING: please do not call as root, and if you have called as root, please do:
cd /tmp
sudo rm -rf mongo* boots*

please try again

**Comment by stradled** [comment]
Thanks for providing those steps @winlin 
When I ran :
`sudo rm -rf boost* mongodb* libmongocxx* mongo* secp256k1* llvm-mirror*`
I get : no matches found: boost*

I then tried to run cmds you mentioned to ~/opt, but the same problem occurred :

>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.

**Comment by pacificcode** [comment]
@stradled can your try this:
1. Remove your build directory
rm -rf path/to/eos/build
2. update your code
git pull
git submodule update --init --recursive
3. run the build script and paste all the output to your screen from the beginning of the script:
Beginning build version: 1.2
to the line indicating:
 >>>>>>>> ALL dependencies sucessfully found or installed . Installing EOS.IO

./eosio_build.sh

**Comment by winlin** [comment]
`
Issay(OracleChain), [Apr 11, 2018 at 4:01:45 PM]:
I meet the same issue, if you are on Ubuntu, just run  'sudo apt remove mongodb'

mongodb installed from apt version conflicts with the mannual build one
` 

hope help

**Comment by mxpaul** [comment]
I am facing this problem on fresh ubuntu-18.04 server, and the only solution for me was to comment out all mongo stuff in eosio_build.sh. EOS node does not use mongo by default now, so it's a sacrefice i am ready for.

This problem reproduced with dawn-4.1.0 and DAWN-2018-05-22 tags and is probably not ubuntu-specific as manually installing mongo-c-driver 1.9.2 does not solve it. It should be some flag combination to build EOS against mongo drivers.

**Comment by jchung00** [comment]
Commented out every exit statement related to mongo in /path/to/eos/scripts/eosio_build_ubuntu.sh and it worked
