### ISSUE TITLE
run eosio_build.sh error!

### ISSUE THREAD

**Issue by tianqb** [EOSIO/eos#2217]
In file included from /Users/tianqb/Documents/01.develop/05.study/05.blockchain/05.github/eos/contracts/musl/upstream/src/internal/floatscan.c:4:
/Users/tianqb/Documents/01.develop/05.study/05.blockchain/05.github/eos/contracts/libc++/upstream/include/float.h:69:15: fatal error: 'float.h' file not found
#include_next <float.h>
              ^~~~~~~~~
1 error generated.
make[2]: *** [contracts/musl/floatscan.c.bc] Error 1
make[1]: *** [contracts/musl/CMakeFiles/libc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 36%] Built target fc
make: *** [all] Error 2

**Comment by cheenid** [comment]
Download the missing libs such as 'musl' . Copy to the dir 'xx/eos/contracts/' .Then try again.

**Comment by heifner** [comment]
Reopen if you can reproduce.

**Comment by Dylan-Phoon** [comment]
Seem to be getting this error only when I try to do
```<#include <boost/multiprecision/cpp_int.hpp>```
and compile using eosiocpp
