### ISSUE TITLE
dawn-v3.0.0 create account error happens, but DAWN-2018-03-30-ALPHA will works well!

### ISSUE THREAD

**Issue by chenlian2015** [EOSIO/eos#2218]
today, compile HEAD detached at dawn-v3.0.0 i get error as follow below

run command:
`cleos create account eosio chenlian EOS8gb6EkQDry72Ugwwy6MUZCr7EQ4ytGAeRhu3knVsA3qSneWPEb EOS6BB3rfssiBdiBN2d14GQLswcM1KBmcKWEM8fiSmdLw6eKWP5et`

ger error
```
2639714ms thread-0   main.cpp:1158                 main                 ] Failed with error: Assert Exception (10)
itr != structs.end(): Unknown struct 
Failed to serialize type
```

how ever,DAWN-2018-03-30-ALPHA will works well!

**Comment by brightermatter** [comment]
+1

**Comment by red-butterfly** [comment]
you need to run the following command frist: 
cleos set contract eosio build/contracts/eosio.bios -p eosio
see：https://github.com/EOSIO/eos/wiki/Tutorial-Getting-Started-With-Contracts#load-the-bios-contract

**Comment by Akagi201** [comment]
@red-butterfly Thanks, solved my problem. This issue can be closed. @chenlian2015

**Comment by chenlian2015** [comment]
@heifner  thanks very much!
