### ISSUE TITLE
cleos get table returns empty rows for eosio.token contract accounts

### ISSUE THREAD

**Issue by brightermatter** [EOSIO/eos#2222]
Successfully deployed the eosio.token smart contract and transferred the currency between 2 accounts (tester, user). The overdrawn balance checks are triggered and the transactions run smoothly. However cleos get table returns empty rows for the accounts involved:

~/eos/build/contracts$ cleos get table eosio.token user account
{
  "rows": [],
  "more": false
}
   
~/eos/build/contracts$ cleos get table eosio.token tester account
{
  "rows": [],
  "more": false
}

The build is the latest master branch.

**Comment by red-butterfly** [comment]
I also get empty rows from eosio.token by table.
but if you want to get the balance of account, I think you can use "cleos get currency balance eosio.token account  symbol".

**Comment by pokerchain** [comment]
cleos get currency balance eosio.token account EOS
=> will return EMPTY

**Comment by brightermatter** [comment]
It works for me. You need need to replace the name of the account in the command i.e. :

cleos get currency balance eosio.token tester EOS

**Comment by elmato** [comment]
@brightermatter the table name is **accounts** (ABI file is wrong)

`cleos get table eosio.token user accounts`

This is being addressed in #2291
