### ISSUE TITLE
What IDE do you use to develop EOS? 

### ISSUE THREAD

**Issue by OuterSpaceTears** [EOSIO/eos#2230]
What IDE do you use to develop EOS,you can do breakpoint debugging?

**Comment by OuterSpaceTears** [comment]
@heifner

**Comment by chenlian2015** [comment]
qt creator

**Comment by OuterSpaceTears** [comment]
Qtcreator, but there are some functions that don't seem to jump in, so we have to interrupt before we can jump in. 
@chenlian2015

**Comment by pokerchain** [comment]
now i use Microsoft Code to view code.

**Comment by heifner** [comment]
Please use telegram for questions. I use CLion.

**Comment by stvenyin** [comment]
sourceinght4.0,gdb debug,what about you.

**Comment by OuterSpaceTears** [comment]
qt creator @stvenyin

**Comment by stvenyin** [comment]
@heifner ,i'm change Clion development debug.
thank you very much.
