### ISSUE TITLE
Pretty print

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2245]

**Comment by heifner** [comment]
As part of this work we need to clean up old `iostream` simulation in `print.hpp`. The `operator<<()` in namespace `eosio` defined in `print.hpp` interferes with `operator<<()`s defined in `datastream.hpp` which are also in namesapce `eosio`.

**Comment by brianjohnson5972** [comment]
Similar to #1780, it depends largely on a complete view of the developer tools we want to support.
