### ISSUE TITLE
API alignment issues

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2249]
There are known stability and crashing issues with the API currently.  @larryk85 please list them here.

**Comment by gleehokie** [comment]
Related to or duplicates #1840

**Comment by larryk85** [comment]
This issue is resolved by PR #2508, I am not sure how to link one PR to multiple issues.

**Comment by taokayan** [comment]
Test case "wasm_tests/misaligned_tests" has passed with:
      7 assertions out of 7 passed
