### ISSUE TITLE
keosd API to use a secure protocol (e.g. HTTPS)

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2253]

**Comment by DenisCarriere** [comment]
This would be a great feature to include in RC2, right now we've got 13+ Block Producers all hosting over HTTPS (mostly LetsEncrypt + Nginx).

https://scholar.eosnation.io

Unfortunately, using `cleos` doesn't seem to support `HTTPS` domains at the moment.

Feel free to use the following BP's to test HTTPS `cleos` connections:

```
cleos -p 443 --host scholarnet.eosnation.io get block 1
cleos -p 443 --host testnet.eosocal.io get block 1
cleos -p 8911 --host scholartestnet.cryptolions.io get block 1
cleos -p 443 --host testnet.meet.one get block 1
cleos -p 443 --host testnet.eoscannon.io get block 1
```

CC: @GMory @wuyahuang @luckybean
