### ISSUE TITLE
Add parameters for multi-sig contract actions to cleos

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2255]
In order to use the multisig contract currently the user must use cleos to send an action to the contract by building up the proper JSON string.  Add a “propose” option to cleos to make this simpler for users.  Any other actions in the multisig contract should have corresponding cleos options.

**Comment by moskvanaft** [comment]
Duplicate of #2163

**Comment by dhaneshvb** [comment]
Duplicates to https://github.com/EOSIO/eos/pull/2427
