### ISSUE TITLE
why the notify_code has to  process the same message?

### ISSUE THREAD

**Issue by OracleChain** [EOSIO/eos#226]
we notice that in process_message function in chain_controller.cpp, the same message is processed by the notify code. we can't understand it.

"
process_message(trx, notify_code, message, output.notify.back().output, &apply_ctx);
"

why the notify_code has to  process the same message?

**Comment by bytemaster** [comment]
The idea of notify is that code from other contracts get to process the same message.  Eg, an exchange can process the currency transfer for both deposit and withdraw.

**Comment by chenlian2015** [comment]
good idea!
