### ISSUE TITLE
where the EOS Token in new Version?

### ISSUE THREAD

**Issue by pokerchain** [EOSIO/eos#2263]
in dawn-2.x, there are EOS Tokens assigned to inita-initu, but new version, just one eosio user, and no EOS Tokens assigned. so how can I issue EOS Tokens to user eosio?

**Comment by red-butterfly** [comment]
you need to use smart contract eosio.token to init the EOS Tokens.

**Comment by pokerchain** [comment]
@HanFei, Yes, I see the eosio.token contract, so 3.0 will use smart contract to create EOS Tokens? I guess but not sure.

**Comment by pokerchain** [comment]
see: https://github.com/EOSIO/eos/issues/2286
closed
