### ISSUE TITLE
how to add permission of any account to deffered_transaction?now seems only can add  account permission of the contract  self

### ISSUE THREAD

**Issue by chenlian2015** [EOSIO/eos#2270]
contract name is ocaskans

void send_deferred_transaction() {

   using namespace eosio;
   auto trx = eosio::transaction();
   transfer as = unpack_action_data<transfer>();

   test_action_action<N(oct), N(transfer)> transfercurrency;
   eosio::print("....send_deferred_transaction....oct:", N(oct), ",transfer:", N(transfer));

   copy_data((char*)&as, sizeof(as), transfercurrency.data);

   trx.actions.emplace_back(vector<permission_level>{{N(ocaskans), N(active)}}, transfercurrency);
   trx.send( 0xffffffffffffffff, now()+2 );
}

**Comment by navcsdev** [comment]
@chenlian2015 I have a similar problem 😢

**Comment by chenlian2015** [comment]
@navcsdev 
The problem has been solved

**Comment by chenlian2015** [comment]
@navcsdev  
private key not on eos node,so it impossible to achieve,You can try other ways to solve this business scenario.

**Comment by navcsdev** [comment]
@chenlian2015 How did you solve it?

**Comment by andriantolie** [comment]
@navcsdev check the first comment here https://github.com/EOSIO/eos/issues/4326
