### ISSUE TITLE
eosio-launcher : problem during execution

### ISSUE THREAD

**Issue by maxb14** [EOSIO/eos#2273]
Hello, 

I wan't run 2 nodes with launcher. I execute the following command : 

`eosio-launcher --nogen -n 2 –p 2 –skip-signature`

And this is the response : 
```
launching bios
"/home/max/eos/Docker/eos/build/etc/eosio/node_bios/config.ini" exists. Use -f|--force to overwrite configuration
```

I don't wan't overwrite configuration files, this is why i use --nogen.

Can you help me please.

Thanks guys.

**Comment by maxb14** [comment]
Hello everyone ! 

Any ideas ?

Thanks.

**Comment by taokayan** [comment]
This issue is too old. Please try with the latest version. If issue still exists, please ask in eosio.stackexchange.com
