### ISSUE TITLE
Invalid genesis.json path should be an error

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2274]
# Description

Currently, if you have an invalid path as your `genesis-json` field inside `config.ini` `nodeos` will start up with some genesis data but, obviously not the intended data.

# Acceptance Test Criteria 

- [ ] Launching `nodeos` with a bogus path for the genesis file should hard error

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner I am thinking this is OBE.  If I don't hear from you I will presume that is the case.

**Comment by brianjohnson5972** [comment]
OBE (Overcome By Events)
