### ISSUE TITLE
Add ability to get active producer set using cleos

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2278]

**Comment by bytemaster** [comment]
There are 3 sets of producers which we must consider:

1. the active set that is currently producing blocks  (past, lame duck-schedule)
2. the new set that will become active once the block header that included them becomes irreversible (as exists in block_header_state) (schedule-elect )
3. the proposed set that will become "new" once the block that proposed it becomes irreversible (future (in the electoral college of producers after all votes tallied by state)
