### ISSUE TITLE
Producer pay testing, inactive producers  

### ISSUE THREAD

**Issue by zorba80** [EOSIO/eos#2279]
- [x] Write complete unit tests for per-block and standby producer pay.
- [x] Add a check to verify that there is a minimum total stake  before producer payment kicks in.
- [x] Add onblock authorization check. **CRITICAL**

**Comment by taokayan** [comment]
Pull request https://github.com/EOSIO/eos/pull/2950 created for fixing the test cases, and adding the onblock validation test case.
