### ISSUE TITLE
Producers Accounts with More Levels

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2281]
# Description

Right now, both producers@active and producers@owner are a 2/3+1 multisig of the active producers.  This is maintained by the chain code as the producer set moves.

This proposal would add multiple named permission levels which, due to the state of the producers may be equivalent but, ideally mean other things.

# Proposed changes

we create multiple levels with the same set of accounts but different thresholds

- [ ] @ owner become "unanimous" requiring 100% of the producers@owner
- [ ] @ active becomes "unanimous" requiring 100% of the producers@active
- [ ] @ twothirds would be 2/3rds of the producers@active (rounded up)
- [ ] @ half would be 1/2 of the producers@active (rounded up)
- [ ] @ onethird would be 1/3rd of the producers@active (rounded up) 
- [ ] @ one would be any producer @ active 

# Rationale

This would allow future contracts to afford different levels of requirements while still having the automatically managed set of producers fulfill the requirements.

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner I am thinking this is OBE.  If I don't hear from you I will presume that is the case.

**Comment by brianjohnson5972** [comment]
OBE (Overcome By Events)
