### ISSUE TITLE
Change prefix keys

### ISSUE THREAD

**Issue by narikatel** [EOSIO/eos#2282]
Good evening to shamans, the question is how to change the prefix for generating private and public keys?

```cpp
public_key.cpp
######
  constexpr auto prefix = config::public_key_base_prefix;
  FC_ASSERT(prefix_matches(prefix, base58str), "Public Key has invalid prefix: ${str}", ("str", base58str));

```
run
```nodeos```
error
```
3163693ms thread-0   main.cpp:95                   main                 ] 10 assert_exception: Assert Exception
prefix_matches(prefix, base58str): Public Key has invalid prefix: TES6KRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
    {"str":"TES6KRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"}
    thread-0  public_key.cpp:30 parse_base58
```
change made in this file

```hpp

public_key.hpp
#############
   namespace config {
      constexpr const char* public_key_base_prefix = "TES";
      constexpr const char* public_key_prefix[] = {
         "K1",
         "R1"
      };
   };
```

**Comment by andriantolie** [comment]
In the latest code, you will need to change
```
// inside public_key.hpp
// from
constexpr const char* public_key_legacy_prefix = "EOS";
// to
constexpr const char* public_key_legacy_prefix = "TES";
```

If you do this, you will need to modify the root CMakeList.txt
```
//from
set(EOSIO_ROOT_KEY "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV")
//to
set(EOSIO_ROOT_KEY "TES6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV")
```
And then it should be fine :)

**Comment by danirabbani90** [comment]
Hi @andriantolie  I have the same issue , i have changed the address prefix in both public_key.hpp and CmakeLists.txt file but the address is still coming up with prefix of EOS ? Please help

**Comment by danirabbani90** [comment]
Can someone even bother to reply please ?

**Comment by mark11226** [comment]
its not working 



// inside public_key.hpp
// from
constexpr const char* public_key_legacy_prefix = "EOS";
// to
constexpr const char* public_key_legacy_prefix = "TES";
If you do this, you will need to modify the root CMakeList.txt

//from
set(EOSIO_ROOT_KEY "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV")
//to
set(EOSIO_ROOT_KEY "TES6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV")
