### ISSUE TITLE
stricter authority validation

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2284]
Authority validation currently checks to see if the total weight (`total_weight`) over all keys and accounts in an authority is greater than or equal to the specified `threshold`. Besides an upper limit on the total number of keys/accounts in the authority, there is no other validation check. This means it is possible to provide an authority with no keys or accounts, which makes the authority unsatisfiable. 

To prevent users from accidentally running into this situation (which can actually easily happen using `cleos` if you give it a JSON without the appropriate field names), the authority validation should also check that `total_weight > 0`.

ATC:
Verify new unittest for this condition passes.

**Comment by taokayan** [comment]
pull request #2369 created for this
