### ISSUE TITLE
Error when add plugins at config.ini, but ok when add to command line options

### ISSUE THREAD

**Issue by pokerchain** [EOSIO/eos#2288]
Add these to config.ini:
plugin = chain_api_plugin 
plugin = account_history_plugin
plugin = account_history_api_plugin
When startup nodeos, will prompt error：
2302877ms thread-0   main.cpp:97                   main                 ] /home/hw/eos/libraries/appbase/application.cpp(270): Throw in function appbase::abstract_plugin &appbase::application::get_plugin(const string &) const
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: unable to find plugin: chain_api_plugin
But ok when startup node with:
nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::account_history_api_plugin

**Comment by spoonincode** [comment]
It's because you're not using `eosio::` in the config.ini

Try
```
plugin = eosio::chain_api_plugin
plugin = eosio::account_history_plugin
plugin = eosio::account_history_api_plugin
```

**Comment by pokerchain** [comment]
done, thanks, such stupid mistake.:(
