### ISSUE TITLE
Create tutorials for setting up and using eos components

### ISSUE THREAD

**Issue by thomasbcox** [EOSIO/eos#229]
This is the list of tutorials initially assigned to @dskvr . 

- [x] Tutorial for Block Producer: EOS Environment Setup
- [x] Tutorial for Block Producer: Network Setup
- [x] Tutorial for Block Producer: Produce Blocks
- [x] Tutorial for Smart Contract Developer: EOS Environment Setup
- [ ] Tutorial for User: Manage Permissions
- [x] Tutorial for User: Manage Wallet

Current thinking is to write these in Markdown and store in Github.

If any of these tutorials gets split out from the others, please create new Issues, one per owner or one per tutorial as you see fit and reference this Issue.

**Comment by dskvr** [comment]
I hit issues with Docker limitations and am rebuilding. Moving over to priority Issue for now.

**Comment by heifner** [comment]
Closing this meta issue as the "Tutorial for User: Manage Permissions" portion is now STAT-56, Github #640.
