### ISSUE TITLE
Token issuing bugs in eosio.token

### ISSUE THREAD

**Issue by JFreegman** [EOSIO/eos#2290]
The issue method doesn't enforce the number of decimals a token will have per the create method, and instead will issue unique tokens with the same token name for any given number decimals. For example:

> cleos push action eosio.token create '[ "eosio", "1000000000.0000 EOS", 0, 0, 0]' -p eosio.token 
> cleos push action eosio.token issue '[ "alice", "10 EOS", "memo" ]' -p eosio
> cleos push action eosio.token issue '[ "alice", "8.00 EOS", "memo" ]' -p eosio
> cleos get currency balance eosio.token alice
> 10 EOS
> 8.00 EOS

Now if we try to transfer all 18 or 18.00 EOS tokens to bob it will fail:

> cleos push action eosio.token transfer '[ "alice","bob","18 EOS","memo" ]' -p alice
> condition: assertion failed: overdrawn balance

But we can transfer 10 EOS tokens and 8.00 EOS tokens to bob separately:

>cleos push action eosio.token transfer '[ "alice","bob","10 EOS","memo" ]' -p alice
>cleos push action eosio.token transfer '[ "alice","bob","8.00 EOS","memo" ]' -p alice
>cleos get currency balance eosio.token bob
>10 EOS
>8.00 EOS

Also, the maximum supply set on token creation is never enforced and seems to be useless.

**Comment by elmato** [comment]
This is beign addressed in #2291
