### ISSUE TITLE
nodeos_run_test failed

### ISSUE THREAD

**Issue by amih** [EOSIO/eos#2292]
[nodeos_run_test.out.txt](https://github.com/EOSIO/eos/files/1894862/nodeos_run_test.out.txt)
I tried the dawn-v3.0.0 and later tried master, when I run the make test in the build folder, I get two failed tests:
The following tests FAILED:
	 26 - nodeos_run_test (Failed)
	 28 - nodeos_run_test-mongodb (Failed)

I then ran:
    tests/nodeos_run_test.py  -v --dump-error-detail >& nodeos_run_test.out.txt

Attached is the file from that command

**Comment by PaulCalabrese** [comment]
This is probably something environmental in your set up.  The first thing to try is to delete your eos/build directory, run eosio_build.sh again, and retest.

If you continue to see this problem, run the test again and check for nodeos startup problems: tests/nodeos_run_test.py --dont-kill -v
See if there are two copies of nodeos runing (ps -ef | grep nodeos)
Look in var/lib/node_bios/stderr.txt and var/lib/node_00/stderr.txt to see if there were any problems.

**Comment by amih** [comment]
I tried deleting the build directory abd running eosio_build.sh again, same failure.

Yes, there are two copies of nodeos, is that ok?

here is the output of the test with the --dont-kill and -v settings:

./tests/nodeos_run_test.py --dont-kill -v
BEGIN
TEST_OUTPUT: test_output_0.txt
SERVER: localhost
PORT: 8888
 cmd: programs/eosio-launcher/eosio-launcher -k 15
Traceback (most recent call last):
  File "./tests/nodeos_run_test.py", line 95, in <module>
    cluster.killall()
  File "/home/ami/dev/eos/tests/testUtils.py", line 1730, in killall
    if 0 != subprocess.call(cmd.split(), stdout=Utils.FNull):
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'programs/eosio-launcher/eosio-launcher': 'programs/eosio-launcher/eosio-launcher'

Also, I don't have a /var/lib/node_bios directory or /var/lib/node_00 directory at all.

**Comment by amih** [comment]
I just now did a git pull, deleted the build directory and rebuilt.
Now it passes the nodeos_run_test
Only one left is the nodeos_run_test-mongodb, I will close this issue as there is a separate issue 2103 for the mongodb test.

Thanks Paul!
