### ISSUE TITLE
Create tutorial for Make a Contract (as Developer) and Set Up your EOS Environment (as a User)

### ISSUE THREAD

**Issue by thomasbcox** [EOSIO/eos#230]
This is the list of tutorials initially assigned to @nathanhourt .

- [ ] Tutorial for Smart Contract Developer: Make a Contract (hello world)
- [ ] Tutorial for User: Set Up your EOS Environment

Current thinking is to write these in Markdown and store in Github.

If any of these tutorials gets split out from the others, please create new Issues, one per owner or one per tutorial as you see fit and reference this Issue.

**Comment by thomasbcox** [comment]
I feel this work has been substantially satisfied via #229 and the Readme.md file.

**Comment by myenglishmail** [comment]
where is the tutorial ?
could you give me a link pls?
