### ISSUE TITLE
Broken link in the wiki

### ISSUE THREAD

**Issue by blackwatertepes** [EOSIO/eos#2304]
On the wiki page: https://github.com/EOSIO/eos/wiki/Smart%20Contract

The link "Basics of EOSIO Smart Contract" anchors to: 
https://github.com/EOSIO/eos/wiki/Smart%20Contract#basics-of-eos-smart-contract

While the header is anchored to: https://github.com/EOSIO/eos/wiki/Smart%20Contract#basics-of-eosio-smart-contract

eos vs eosio!

**Comment by jgiszczak** [comment]
A major wiki update is in progress, currently scheduled for release on Thursday.  It includes a substantial rework of the smart contracts section.  Feel free to confirm the links in it when it's published and reopen this ticket if the problem persists.
