### ISSUE TITLE
Segmentation fault: 11 on single host, multi-node testnet

### ISSUE THREAD

**Issue by rbw3821** [EOSIO/eos#2305]
Here is my setup:  nodeos 1 is an observer.  nodeos 2 is the producer. cleos by default goes to nodeos 1.

First, I ran cleos:
cleos --wallet-port 8899 get accounts EOS7ijWCBmoXBi3CgtK7DJxentZZeTkeUnaSDvyro9dq7Sd1C3dC4
Error 3130003: Missing Account History API Plugin
Ensure that you have eosio::account_history_api_plugin added to your node's configuration!
Error Details:
Account History API plugin is not enabled

Second, I stopped nodeos 1, then restarted with the eosio::account_history_api_plugin added:
nodeos --enable-stale-production --producer-name eosio --plugin eosio::chain_api_plugin --plugin eosio::net_api_plugin --plugin eosio::account_history_api_plugin

Third, I re-ran:
cleos --wallet-port 8899 get accounts

Output from nodeos 1:
...
i url: /v1/net/status
2364588ms thread-0   account_history_api_plugin.cpp:45 plugin_startup       ] starting account_history_api_plugin
2364588ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/account_history/get_controlled_accounts
2364588ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/account_history/get_key_accounts
2364588ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/account_history/get_transaction
2364588ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/account_history/get_transactions
2364588ms thread-0   producer_plugin.cpp:161       plugin_startup       ] producer plugin:  plugin_startup() begin
2364588ms thread-0   producer_plugin.cpp:166       plugin_startup       ] Launching block production for 1 producers.
2364589ms thread-0   producer_plugin.cpp:176       plugin_startup       ] producer plugin:  plugin_startup() end
Segmentation fault: 11

I have not been able to replicate the problem.

**Comment by heifner** [comment]
account_history_plugin is no longer supported.
