### ISSUE TITLE
[Communication Smart Contract] Crate Action can not add more permission level

### ISSUE THREAD

**Issue by navcsdev** [EOSIO/eos#2309]
# How to create action in a contract then send it to another contract has required auth?

I have two smart contracts A and currency.
In smart contract A I create action and send to contract currency. 
### Way 1
```
vector<permission_level> perlvs;
permission_level A = permission_level{ N(A), N(active) };
permission_level issuer = permission_level{ N(currency), N(active) };
perlvs.push_back(A);
perlvs.push_back(issuer);
action act( perlvs, issue{ to, user_quantity, "Airdrop" } );
act.send();
```
I refer init function in `action.hpp` 
```
template<typename Action>
action( vector<permission_level>&& auth, const Action& value ) {
         account       = Action::get_account();
         name          = Action::get_name();
         authorization = move(auth);
         data          = pack(value);
}
```
But I get the error `error: no matching constructor for initialization of 'eosio::action'`

**Comment by navcsdev** [comment]
I tried changing the way the action was created:
```
action act( permission_level{ N(A), N(active) }, N(currency), N(issue), issue{ to, "10.0000 EOS", "Airdrop" } );
act.send();
```
But it get error `Missing authentication when run action issue in contract currency (require_auth( st.issuer );)`

**Comment by navcsdev** [comment]
I continue change permission to currency in smart contract A
```
action act( permission_level{ N(currency), N(active) }, N(currency), N(issue), issue{ to, "10.0000 EOS", "Airdrop" } );
act.send();
```
I got the error `Error 3030002: signatures do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and you wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"currency","permission":"active"}', but does not have signatures for it.`

**Comment by navcsdev** [comment]
I try another way
```
vector<permission_level> perlvs;
permission_level A = permission_level{ N(A), N(active) };
permission_level issuer = permission_level{ N(currency), N(active) };
perlvs.push_back(A);
perlvs.push_back(issuer);

action a;
a.account = N(currency);
a.name = N(issue);
a.authorization = move(perlvs);
a.data = pack(issue{ to, user_quantity, "Airdrop" });
a.send();
```
And it still error 😢

**Comment by henryyyx** [comment]
I got the same issue.

**Comment by andriantolie** [comment]
account A first need to authorize his A@active permission to your contract @eosio.code permission. Please take a look at the first comment of this https://github.com/EOSIO/eos/issues/4326

**Comment by lixiaodong** [comment]
but i have this error when compile...
