### ISSUE TITLE
eosio_build.sh llvm exists error

### ISSUE THREAD

**Issue by fabifrank** [EOSIO/eos#2312]
When running

`./eosio_build.sh `

I get the error:

```
mkdir: wasm-compiler: File exists
fatal: destination path 'llvm' already exists and is not an empty directory.
	Unable to clone llvm repo @ https://github.com/llvm-mirror/llvm.git.
	Exiting now.
```

Independent from whether llvm is inside the directory, already installed with brew, unlinked etc.

**Comment by fabifrank** [comment]
Fixed it by:

1. Edit `scripts/eosio_build_darwin.sh` to delete the llvm folder before git clone

2. When error `Found PythonInterp: /Users/skober/.pyenv/shims/python2.7 (found version "1.4")` appears edit  `scripts/eosio_build_darwin.sh`  to point to your python installation with the cmake option  `-DPYTHON_EXECUTABLE=/<path>/.pyenv/shims/python` in the relevant section (wasm on my side, which is the last section in the script).

3. On this error:
 ```
Failed to find Gettext libintl (missing: Intl_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindIntl.cmake:47 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  programs/cleos/CMakeLists.txt:29 (find_package)
```

Reinstall gettext: `brew reinstall gettext`
Relink: `brew unlink gettext && brew link gettext --force`

**Comment by sisardor** [comment]
You said `scripts/eosio_build_darwin.sh` and but didn't say what to do, what to edit? Explain little bit more?

**Comment by fabifrank** [comment]
@sisardor Updated the post. Does it help now?
And please add mention with `@` notation, otherwise I dont get a notification.

**Comment by pacificcode** [comment]
@fabifrank @sisardor on darwin remove the directory /tmp/wasm-compiler
rm -rf /tmp/wasm-compiler
And run the eosio_build.sh script again and you should be good to go.

**Comment by fabifrank** [comment]
@pacificcode Yeah that should work in case there's no other error in the build process. Which was not the case on my side.
