### ISSUE TITLE
publish contract error

### ISSUE THREAD

**Issue by chenlian2015** [EOSIO/eos#2314]
Reading WAST...
Assembling WASM...
Publishing contract...
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
!"unresolvable": env.strlen

**Comment by wanderingbort** [comment]
this means that you have built without the definition of `strlen` so, it is trying to import that from our runtime environment which does not provide it. 

This would imply that you included the headers from our libc implementation (musl) but not the compiled artifacts of that library.  

Can you give us more information about the contract and how you compiled it?

**Comment by brianjohnson5972** [comment]
This issue went silent many months ago.  If you are still having an issue, please create a new issue.
