### ISSUE TITLE
drawn_30,table now not support i64i64i64 primary key?

### ISSUE THREAD

**Issue by chenlian2015** [EOSIO/eos#2317]
bogon:oc_askanswer cl$ cleos get table ocaskans oct answer 
Error 3010003: Contract Table Query Exception
Most likely, the given table doesnt' exist in the blockchain.
Error Details:
Invalid table type i64i64i64

**Comment by salterok** [comment]
I had same error. Seems like eos trying to guess primary key size and in my case setting it to **i64i64i64** when i have first 3 fields of type `uint64_t`.   
A'm not sure if this the case but anyway i solved it by specifying primary key type like this:
```c++
// @abi table contract i64
struct contract {
    uint64_t id;
    ...
}
```

**Comment by andriantolie** [comment]
Yes, `// @abi table contract i64` will solve the problem. There's a problem with abigen previously, I think it should be fixed in the latest one.
