### ISSUE TITLE
Create tutorials for setting up and running benchmarks

### ISSUE THREAD

**Issue by thomasbcox** [EOSIO/eos#232]
This is the list of BENCHMARK tutorials initially assigned to @dskvr  . 

- [ ] Tutorial for Smart Contract Developer: Benchmark Setup
- [ ] Tutorial for Smart Contract Developer: Run Benchmark
- [ ] Tutorial for User: Benchmark Setup

Current thinking is to write these in Markdown and store in Github.

If any of these tutorials gets split out from the others, please create new Issues, one per owner or one per tutorial as you see fit and reference this Issue.

**Comment by thomasbcox** [comment]
Let's have the benchmark tutorial show the user:
1. How to invoke the benchmark once EOS is set up single node standalone
2. How to find the results of the benchmark
2.1. Total Time
2.2. Total Transactions
2.3. Number and Ratio of Successful vs Failed Transactions
2.4. Transactions per second
2.5. Successful transactions per second
3. Config of this benchmark run (# nodes, other init settings)

What else would someone want to see?

**Comment by thomasbcox** [comment]
In the case of EOS benchmarking we need to show
 1. how many transactions are included in a block
 2. average latency until being included in a block
 3. how quickly can the block be applied

**Comment by brianjohnson5972** [comment]
@bytemaster Is there benchmarking code (scripts/tests) in master?  All I could find was the captest code that Matt P. had worked on, on the tps-test and pushtrx-json branches. Since this is marked EOS Dawn 1.1 and Priority, I figured I should take it up, but wanted to make sure if this was the right code.

**Comment by brianjohnson5972** [comment]
Ok, missed that this was pulled into eosc.  I was perusing this because it was Dawn 1.1 and Priority, but  I am figuring this will be handled by the people focused on documentation.

**Comment by heifner** [comment]
Closing as this was moved to JIRA STAT-55, Github #639
