### ISSUE TITLE
p2p performance related fixes

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#2321]
1. not performance but dead code removal
2. forwarding transactions yields log spam.

ATC:
Using a multi-node test network, set the log level for p2p to debug: --log-level-net-plugin debug
observe that sending transactions less than 1500 bytes are just forwarded, no longer sent as notices.

**Comment by andriantolie** [comment]
Sending small transaction, such as "creating a new account" prints out
`sending whole txn to localhost:9878 - 351ec1d`
While sending relatively large transaction, such as "setting the contract", prints out
`sending notice to localhost:9878 - 351ec1d`

ATC passes.
