### ISSUE TITLE
Optimize Merkle root calculation

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2329]
Not to be confused with #9.

**Comment by gleehokie** [comment]
This means that we can make shorter proofs by not assuming a perfectly balanced tree.

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner I am thinking this is OBE.  If I don't hear from you I will presume that is the case.

**Comment by brianjohnson5972** [comment]
OBE (Overcome By Events)
