### ISSUE TITLE
Unable to find last irreversible block to write, hard fail

### ISSUE THREAD

**Issue by larryk85** [EOSIO/eos#2331]
Given a network of 4 or more producers are running and producer *n* is only connected through one connection.  When this connection is killed, and producer *n* is allowed to continue on his own fork for at least two rounds (it appears this is the case), then when reconnecting to another producer via cleos, syncing fails.  It syncs some blocks but fails before done with *unable to find last irreversible block to write*.

ATC:
After chain controller refactoring the unit test block_tests/last_irreversible_update_bug should fail as the assertion should not be thrown.
Verify that the new chain controller will pick the fork with the most recent irreversible block and that if these tie then pick the longest valid fork.

**Comment by larryk85** [comment]
This bug, should be resolved with Dan's chain controller refactoring.

**Comment by andriantolie** [comment]
@larryk85 Hi Bucky, the unit_test block_tests/last_irreversible_update_bug_test is not failing, is it supposed to be failing by the latest master?

**Comment by larryk85** [comment]
No those changes are not it master yet, Dan is still working on those.  So let's keep this is QA until those come in.  I don't think there is an issue for the refactoring, so I will just keep track of when those changes are merged and either message you or just ensure that the test fails.

**Comment by andriantolie** [comment]
Got it. Thanks!
