### ISSUE TITLE
Building dawn-v3.0.0 pre-release does not work on OSX, missing some externals/librairies

### ISSUE THREAD

**Issue by romainPellerin** [EOSIO/eos#2335]
Hi EOS team,

I just tried to build EOS dawn-v3.0.0 [pre-release](https://github.com/EOSIO/eos/commit/d9ad8eec49c59fb107f472de3952d29c9e73a023) from source code zip archive. Build process stopped since some externals and librairies files are missing from archive including the following:

/Users/rpellerin/EOS/eos-dawn-v3.0.0/externals/**binaryen** does not contain a CMakeLists.txt file. /Users/rpellerin/EOS/eos-dawn-v3.0.0/libraries/**softfloat**  does not contain a CMakeLists.txt file.
/Users/rpellerin/EOS/eos-dawn-v3.0.0/libraries/**chainbase** does not contain a CMakeLists.txt file.
/Users/rpellerin/EOS/eos-dawn-v3.0.0/libraries/**appbase** does not contain a CMakeLists.txt file.

FYI, I fixed that copying the externals and librairies from the git repo.
I also had to force brew link --force gettext.

**Comment by romainPellerin** [comment]
Finally build process failed on:
`[ 52%] Built target chainbase
make[2]: *** No rule to make target `../contracts/libc++/upstream/src/vector.cpp', needed by `contracts/libc++/vector.cpp.bc'.  Stop.
make[1]: *** [contracts/libc++/CMakeFiles/libc++.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 52%] Building LLVM bitcode eosiolib.cpp.bc
[ 52%] Built target appbase
In file included from /Users/rpellerin/EOS/eos-dawn-v3.0.0/contracts/eosiolib/eosiolib.cpp:1:
In file included from /Users/rpellerin/EOS/eos-dawn-v3.0.0/contracts/eosiolib/datastream.hpp:6:
In file included from /Users/rpellerin/EOS/eos-dawn-v3.0.0/contracts/eosiolib/system.h:6:
/Users/rpellerin/EOS/eos-dawn-v3.0.0/contracts/eosiolib/types.h:8:10: fatal error: 'wchar.h' file not found`

Going to switch to git repo in order to build project.

**Comment by spoonincode** [comment]
The tar balls are broken per issue #2178 you'll have to use git

**Comment by romainPellerin** [comment]
Built from git repo:

	EOS.IO has been successfully built. 0:32:16

	To verify your installation run the following commands:

	/usr/local/bin/mongod -f /usr/local/etc/mongod.conf &
	cd /Users/rpellerin/eos/build; make test

	For more information:
	EOS.IO website: https://eos.io
	EOS.IO Telegram channel @ https://t.me/EOSProject
	EOS.IO resources: https://eos.io/resources/
	EOS.IO wiki: https://github.com/EOSIO/eos/wiki
