### ISSUE TITLE
Updated readme to include System Requirements

### ISSUE THREAD

**Issue by alexhiggins732** [EOSIO/eos#2336]
It would be very helpful to put the system requirements, beyond supported OS, in the readme. 

After waiting clone the repo, which took sometime due to large download over a slow connection, the aotmatic build script failed because system did not have 8 GB of physical memory installed. After upgrading the memory build then again failed due to not have 20GB of available storage on the hard drive.

**Comment by rbw3821** [comment]
README has been updated to include system requirements.  Pending PR #2338 review and merge.

**Comment by rbw3821** [comment]
System requirements added to the "Building EOSIO" section of the wiki.  See https://github.com/EOSIO/eos/wiki/Local-Environment#2-building-eosio
