### ISSUE TITLE
contract setcode error and then blockchain locked

### ISSUE THREAD

**Issue by stevenzhang68** [EOSIO/eos#234]
When I run this cmd, there was a error.
zhangcongdembp:eosc zhangcong$ ./eosc setcode currency ../../../contracts/currency/currency.wast ../../../contracts/currency/currency.abi
13 N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_6system12system_errorEEEEE: read_until: End of file
read_until: End of file: 
    {"server":"localhost","port":8888,"path":"/v1/chain/push_transaction","postdata":{"refBlockNum":108,"refBlockPrefix":1027342416,"expiration":"2017-08-27T02:02:58","scope":["currency","eos"],"messages":[{"code":"eos","type":"setcode","authorization":[{"account":"currency","permission":"active"}],"data":"00000079b82265...756e74"}],"signatures":[]},"what":"read_until: End of file"}
    thread-0  httpc.cpp:117 call

and then, the blockchain sever is shutdown:

...
80249ms thread-0   eos_contract.cpp:200          apply_eos_setcode    ] set code: 2390
80249ms thread-0   wasm_interface.cpp:348        get                  ] Runtime::init
80251ms thread-0   wasm_interface.cpp:522        load                 ] LOADING CODE
Segmentation fault: 11

and then I start the eosd again, the blockchain was locked:

ZhangcongdeMacBook-Pro:eosd zhangcong$ ./eosd --skip-transaction-signatures
88174ms thread-0   chain_plugin.cpp:76           plugin_initialize    ] initializing chain plugin
88174ms thread-0   chain_plugin.cpp:114          plugin_initialize    ] Setting skip_transaction_signatures
88174ms thread-0   chain_plugin.cpp:123          plugin_initialize    ] Setting skip_transaction_signatures

**************************************
*                                    *
*   -- EOSD IGNORING SIGNATURES --   *
*   -         TEST MODE          -   *
*   ------------------------------   *
*                                    *
**************************************

88174ms thread-0   producer_plugin.cpp:133       plugin_initialize    ] Public Key: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
88174ms thread-0   http_plugin.cpp:109           plugin_initialize    ] host: 127.0.0.1 port: 8888 
88175ms thread-0   http_plugin.cpp:112           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
88175ms thread-0   net_plugin.cpp:773            plugin_initialize    ] Initialize net plugin
88175ms thread-0   net_plugin.cpp:779            plugin_initialize    ] host: 0.0.0.0 port: 9876 
88177ms thread-0   block_log.cpp:88              open                 ] Opening block log at /Users/zhangcong/EosProject/eos/build/programs/eosd/data-dir/blocks/blocks.log
88177ms thread-0   block_log.cpp:116             open                 ] Log is nonempty
88178ms thread-0   block_log.cpp:124             open                 ] Index is nonempty
Lock timeout, moving to lock 1

why?

**Comment by bytemaster** [comment]
It appears your data directory is corrupted, please delete everything in the data directory (except the config file) and start again.  Let me know if errors persist.

You can also try starting with --resync to get a fresh blockchain.

**Comment by stevenzhang68** [comment]
Thank you. Yesterday I have tried to remove data-dir and use --resync cmd and even rebuild project several times. It doesn't work.

**Comment by stevenzhang68** [comment]
@bytemaster I clone the newest code and build again, it's still error. I find #211 is same to me. I guess this error is not because of our build. 
By the way, the document at https://eosio.github.io/eos/group__eosc.html show the sample code "./eosc setcode currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi
", I think the path is wrong. We don't have .wast and .abi in the path "../../contracts/currency/", we need to change the path to "../../../contracts/currency/".

**Comment by MrXtar** [comment]
#211 is my issue. Recorded video with that problem: https://www.youtube.com/watch?v=l_7U_r9lgt0

Btw, I can give root access to my test server for experiments.

**Comment by MrXtar** [comment]
My issue is fixed. There was something wrong in system. Try reinstall like in this Docker: https://github.com/EOSIO/eos/blob/master/Docker/Dockerfile

**Comment by heifner** [comment]
Unable to reproduce. Are you still having issues?

**Comment by myenglishmail** [comment]
root@ubuntu:~/eosn/eos_clang/build/programs/eosioc# ./eosioc -v set contract currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi
Reading WAST...
Assembling WASM...
Publishing contract...
277523ms thread-0   main.cpp:1209                 main                 ] Failed with error: 13 St9exception: read_until: End of file
read_until: End of file: 
    {"server":"localhost","port":8888,"path":"/v1/chain/push_transaction","postdata":{"expiration":"2018-02-06T09:05:07","region":0,"ref_block_num":498,"ref_block_prefix":858062107,"actions":[{"account":"eosio","name":"setcode","authorization":[{"actor":"currency","permission":"active"}],"data":"0000001e4d75af46000087590061736d0100000001570f60017e0060027f7f0060037f7f7f017f60047e7e7f7f017f60017f017f60057e7e7e7f7f017f6000017f60027f7f017f60000060027e7e0060027e7e017f60017f0060047f7e7e7f0060047e7e7e7f0060037f7f7f0002b3010b03656e760b616374696f6e5f73697a65000603656e7606617373657274000103656e76086c6f61645f693634000503656e76066d656d637079000203656e76066d656d736574000203656e760b726561645f616374696f6e000703656e760c726571756972655f61757468000003656e7611726571756972655f726563697069656e74000003656e76047362726b000403656e760b73656e645f696e6c696e65000103656e760973746f72655f693634000303161508090a0b0b0b0b0c0c0d02010b07070704070e07010404017000000503010001073003066d656d6f72790200056170706c79000c1b5f474c4f42414c5f5f7375625f495f63757272656e63792e637070000b0af44015f202004100420037028c4041004200370294404100420037029c40410042003702a440410042003702ac40410041003602b440410041003602b840410041003602bc40410041003602c040410041003602c440410041003602c840410041003602cc40410041003602d040410041003602d440410041003602d840410041003602dc40410041003602e040410041003602e440410041003602e840410041003602ec40410041003602f040410041003602f440410041003602f840410041003602fc404100410036028041410041003602844141004100360288414100410036028c414100410036029041410041003602944141004100360298414100410036029c41410041003602a041410041003602a441410041003602a841410041003602ac41410041003602b041410041003602b441410041003602b841410041003602bc41410041003602c041410041003602c441410041003602c841410041003602cc41410041003602d041410041003602d4410b090020002001100d1a0b990201057f4100410028020441306b2206360204410021050240200042808080f0d1a9ddd7c600520d000240024002402001428080808080a0e998f600510d00200142808080b8d585cfe64d520d032006100e2006100f200641286a2d0000450d022006412c6a2802002205450d0220052005280200417f6a220436020020040d02200641246a2802002202450d0241002802cc4122044101480d02418cc00021052004410c6c418cc0006a21030340200541046a2802002204450d030240200441046a20024b0d00200420052802006a20024b0d030b2005410c6a22052003490d000c030b0b20061010200610110c010b2002417c6a2205200528020041ffffffff07713602000b410121050b4100200641306a36020420050b3301037f41004100280204220310002201410f6a4170716b22023602042002200110051a200020022001101d410020033602040ba80304017e017f027e027f4100410028020441306b22063602042000290300100620002903002101200029030810072001100720002903002101200642003703182006428486d59205370310200641206a428486d592052001200641106a10132006290328210320002903102104200041186a2202290300428486d592055141e0c1001001200320045a4180c4001001410141d0c20010012006428486d59205370320410141f0c20010012006200641206a410810031a2006200320047d370320410141f0c200100120064108722205200641206a410810031a20014280808080f2a9d3883220064110100a1a20002903082101200642003703182006428486d59205370310200641206a428486d592052001200641106a101320062903282104200029031021032002290300428486d592055141e0c1001001200320047c220420035a41a0c2001001410141d0c20010012006428486d59205370320410141f0c20010012006200641206a410810031a20062004370320410141f0c20010012005200641206a410810031a20014280808080f2a9d3883220064110100a1a4100200641306a3602040b8c0101047f41004100280204220410002201410f6a4170716b22023602042002200110051a200041106a220342848abd9a0537030020004200370308200141074b41f0c300100120002002410810031a2001417871220141084741f0c3001001200041086a200241086a410810031a200141104741f0c30010012003200241106a410810031a410020043602040bc30505027f017e017f017e017f4100410028020441d0006b220636020442808080f0d1a9ddd7c6001006200642003703482006428486d59205370340200641106a428486d5920542808080f0d1a9ddd7c600200641c0006a101220002903082103200041106a2202290300428486d592055141e0c1001001200320062903187c20035a41a0c20010012006200320062903187c370318410141d0c200100120062006290310370340410141f0c2001001200641206a200641c0006a410810031a20062006290318370340410141f0c2001001200641206a4108722204200641c0006a410810031a42808080f0d1a9ddd7c60042808080808080e4a646200641206a4110100a1a200642003703382006428486d59205370330200641c0006a428486d5920542808080f0d1a9ddd7c600200641306a101320062903482105200029030821032002290300428486d592055141e0c1001001200320057c220520035a41a0c2001001410141d0c20010012006428486d59205370340410141f0c2001001200641206a200641c0006a410810031a20062005370340410141f0c20010012004200641c0006a410810031a42808080f0d1a9ddd7c6004280808080f2a9d38832200641206a4110100a1a20002903082103200029030021052002290300428486d592055141e0c1001001200641003a0008200642003703002006410036020c42808080f0d1a9ddd7c6002005200320061014024020062d0008450d002006410c6a2802002200450d0020002000280200417f6a220236020020020d0020062802042204450d0041002802cc4122024101480d00418cc00021002002410c6c418cc0006a21010340200041046a2802002202450d0102400240200241046a20044b0d00200220002802006a20044b0d010b2000410c6a22002001490d010c020b0b2004417c6a2200200028020041ffffffff07713602000b4100200641d0006a3602040bba0201027f4100410028020441a0086b22053602042005200137030002400240200242808080f0d1a9ddd7c60042808080808080e4a646200541800810022204417f4c0d0020054200370388082005428486d5920537038008200441074b41f0c300100120054180086a2005410810031a200441787141084741f0c300100120054180086a41086a2005410872410810031a200041086a20052903880837030020002005290380083703000c010b410141d0c20010012005200329030037039808410141f0c200100120054180086a20054198086a410810031a2005200329030837039808410141f0c200100120054180086a41087220054198086a410810031a200242808080808080e4a64620054180086a4110100a1a200041086a2003290308370300200020032903003703000b4100200541a0086a3602040bba0201027f4100410028020441a0086b22053602042005200137030002400240200242808080f0d1a9ddd7c6004280808080f2a9d38832200541800810022204417f4c0d0020054200370388082005428486d5920537038008200441074b41f0c300100120054180086a2005410810031a200441787141084741f0c300100120054180086a41086a2005410872410810031a200041086a20052903880837030020002005290380083703000c010b410141d0c20010012005200329030037039808410141f0c200100120054180086a20054198086a410810031a2005200329030837039808410141f0c200100120054180086a41087220054198086a410810031a20024280808080f2a9d3883220054180086a4110100a1a200041086a2003290308370300200020032903003703000b4100200541a0086a3602040bbe0803077f047e017f410041002802044180016b220f3602044200210c423b210b4180c300210a4200210d034002400240024002400240200c4205560d00200a2c00002204419f7f6a41ff017141194b0d01200441a5016a21040c020b4200210e200c420b580d020c030b200441d0016a41002004414f6a41ff01714105491b21040b2004ad423886423887210e0b200e421f83200b42ffffffff0f8386210e0b200a41016a210a200c42017c210c200e200d84210d200b427b7c220b427a520d000b200f200d370340200f42808080f0d1a9ddd7c600370338410141e0c100100120032d0008210820032802002105200328020421040240200328020c220a450d00200a200a28020041016a3602000b200f41206a428486d59205370300200f41086a41246a2004360200200f41306a220320083a0000200f2001370310200f2000370308200f2002370318200f2005360228200f41346a200a3602000240200a450d00200a200a28020041016a3602000b200f41d8006a4101200f41386a10152105200f41c8006a41246a22094100360200200f4200370264200f42808080f0d1a9ddd7c600370348200f42808080b8d585cfe64d370350200f41f0006a200f41086a10162009200f280278360200200f200f290370370264024020032d0000450d00200f41346a2802002203450d0020032003280200417f6a220936020020090d00200f412c6a2802002206450d0041002802cc4122094101480d00418cc00021032009410c6c418cc0006a21070340200341046a2802002209450d0102400240200941046a20064b0d00200920032802006a20064b0d010b2003410c6a22032007490d010c020b0b2006417c6a2203200328020041ffffffff07713602000b0240200841ff0171450d00200a450d00200a200a280200417f6a220336020020030d002004450d0041002802cc4122034101480d00418cc000210a2003410c6c418cc0006a21080340200a41046a2802002203450d0102400240200341046a20044b0d002003200a2802006a20044b0d010b200a410c6a220a2008490d010c020b0b2004417c6a220a200a28020041ffffffff07713602000b200f41c8006a10170240200f2802642203450d0041002802cc4122044101480d00418cc000210a2004410c6c418cc0006a21080340200a41046a2802002204450d0102400240200441046a20034b0d002004200a2802006a20034b0d010b200a410c6a220a2008490d010c020b0b2003417c6a220a200a28020041ffffffff07713602000b200f41ec006a4100360200200f41e4006a4200370200024020052802002203450d0041002802cc4122044101480d00418cc000210a2004410c6c418cc0006a21080340200a41046a2802002204450d0102400240200441046a20034b0d002004200a2802006a20034b0d010b200a410c6a220a2008490d010c020b0b2003417c6a220a200a28020041ffffffff07713602000b4100200f4180016a3602040ba207010b7f20004100360208200042003702000240024002402001450d00410c2001410474101821070240200041046a2204280200450d004100210b4100210c03402007200b6a22082000280200200b6a2209290300370300200841086a200941086a290300370300200b41106a210b200c41016a220c2004280200490d000b0b024020002802002208450d0041002802cc41220c4101480d00418cc000210b200c410c6c418cc0006a21090340200b41046a280200220c450d0102400240200c41046a20084b0d00200c200b2802006a20084b0d010b200b410c6a220b2009490d010c020b0b2008417c6a220b200b28020041ffffffff07713602000b20002007360200200041086a220620013602002001450d014100210a0240200041046a220728020022082001220b470d004102210d0c030b4100210d0c020b4110210d0c010b4110210d0b037f024002400240024002400240024002400240024002400240024002400240024002400240024002400240024002400240024002400240024002400240200d0e11020304050607090a010b0c0d0e0f000810100b2009417c6a220b200b28020041ffffffff0771360200200728020021084108210d0c1d0b20002004360200200620033602004100210d0c1c0b200028020020084104746a220b2002290300370300200b41086a200241086a2903003703002007200728020041016a2208360200200a41016a220a2001460d0e4101210d0c1b0b20082006280200220b470d0f4102210d0c1a0b417f2108200b417f460d0d4103210d0c190b410c200b41016a2203410474101821042007280200450d0e4104210d0c180b4100210b4100210c4105210d0c170b2004200b6a22082000280200200b6a2209290300370300200841086a200941086a290300370300200b41106a210b200c41016a220c20072802002208490d0d0c0e0b410021084106210d0c150b20002802002209450d0d4107210d0c140b41002802cc41220c4101480d0d4109210d0c130b418cc000210b200c410c6c418cc0006a2105410a210d0c120b200b41046a280200220c450d0c410b210d0c110b200c41046a20094b0d0e410c210d0c100b200c200b2802006a20094b0d0e410d210d0c0f0b200b410c6a220b2005490d0a0c0b0b20000f0b4110210d0c0c0b4100210d0c0b0b4100210d0c0a0b410f210d0c090b4105210d0c080b4106210d0c070b4108210d0c060b4108210d0c050b4108210d0c040b410a210d0c030b4108210d0c020b410d210d0c010b410e210d0c000b0b820303057f017e017f4100410028020441106b220836020420004100360208200042003702004160200128022022036b21062003ad210703402006417f6a2106200742078822074200520d000b410020066b21024100210502402006450d00410c200210182105200041086a20023602002000200536020020052103200221040340200341003a0000200341016a21032004417f6a22040d000b0b200041046a200236020020082005360204200820053602002008200520066b36020820082001101c1a200141206a350200210720082802042106200841086a210503402007a721032008200742078822074200522204410774200341ff0071723a000f200528020020066b41004a41f0c200100120082802042008410f6a410110031a2008200828020441016a220636020420040d000b0240200141206a2802002203450d00200141246a2802002104200841086a28020020066b20034e41f0c200100120082802042004200310031a2008200828020420036a3602040b4100200841106a3602040ba80302017e057f4100410028020441206b2206360204200041146a280200220341047441106a21022003ad21010340200241016a2102200142078822014200520d000b200041206a280200220320026a21022003ad21010340200241016a2102200142078822014200520d000b024002402002450d00410c2002101822052103200221040340200341003a0000200341016a21032004417f6a22040d000c020b0b410021050b200620053602082006200520026a220336021020062000290300370318200241074a41f0c20010012005200641186a410810031a200620002903083703182003200541086a22046b41074a41f0c20010012004200641186a410810031a2006200541106a36020c200641086a200041106a10192000411c6a101a1a20052002100902402005450d0041002802cc4122034101480d00418cc00021022003410c6c418cc0006a21040340200241046a2802002203450d0102400240200341046a20054b0d00200320022802006a20054b0d010b2002410c6a22022004490d010c020b0b2005417c6a2202200228020041ffffffff07713602000b4100200641206a3602040bd804010c7f02402001450d00024020002802c041220d0d004110210d200041c0c1006a41103602000b200141086a200141046a41077122026b200120021b210202400240024020002802c441220a200d4f0d002000200a410c6c6a4180c0006a21010240200a0d0020004184c0006a220d2802000d0020014180c000360200200d2000360200200041004180c00010041a0b200241046a210a034002402001280208220d200a6a20012802004b0d002001280204200d6a220d200d28020041808080807871200272360200200141086a22012001280200200a6a360200200d200d28020041808080807872360200200d41046a22010d030b2000101b22010d000b0b41fcffffff0720026b2104200041c8c1006a210b200041c0c1006a210c20002802c8412203210d03402000200d410c6c6a22014188c0006a28020020014180c0006a2205280200464190c300100120014184c0006a280200220641046a210d0340200620052802006a2107200d417c6a2208280200220941ffffffff07712101024020094100480d000240200120024f0d000340200d20016a220a20074f0d01200a280200220a4100480d012001200a41ffffffff07716a41046a22012002490d000b0b20082001200220012002491b200941808080807871723602000240200120024d0d00200d20026a200420016a41ffffffff07713602000b200120024f0d040b200d20016a41046a220d2007490d000b41002101200b4100200b28020041016a220d200d200c280200461b220d360200200d2003470d000b0b20010f0b2008200828020041808080807872360200200d0f0b41000bc40203037f017e037f4100410028020441106b22083602042000280204210620013502042105200041086a2103200041046a210403402005a721072008200542078822054200522202410774200741ff0071723a0008200328020020066b41004a41f0c20010012004280200200841086a410110031a2004200428020041016a220636020020020d000b0240200141046a2802002204450d002001280200220720044104746a2103200041046a2104034020082007290300370308200041086a220228020020066b41074a41f0c20010012004280200200841086a410810031a2004200428020041086a22063602002008200741086a290300370308200228020020066b41074a41f0c20010012004280200200841086a410810031a2004200428020041086a2206360200200741106a22072003470d000b0b4100200841106a36020420000b860203047f017e027f4100410028020441106b22083602042000280204210720013502042106200041086a2104200041046a210503402006a721022008200642078822064200522203410774200241ff0071723a000f200428020020076b41004a41f0c200100120052802002008410f6a410110031a2005200528020041016a220736020020030d000b0240200141046a2802002203450d0020012802002105200041086a2104200041046a21020340200820052d00003a000e200428020020076b41004a41f0c200100120022802002008410e6a410110031a2002200228020041016a2207360200200541016a21052003417f6a22030d000b0b4100200841106a36020420000b870301077f200020002802c4412201410c6c6a22064180c0006a210702400240418080c000410010086b220241004c0d00200241808004200241808004491b22021008220320064184c0006a2802002204200728020022066a460d010240200620002001410c6c6a4188c0006a22052802002201460d00200420016a2204200428020041808080807871417c20016b20066a72360200200520072802003602002004200428020041ffffffff07713602000b200041c4c1006a2207200728020041016a220736020020002007410c6c6a22004184c0006a200336020020004180c0006a2200200236020020034100200210041a20000f0b02402007280200220320064188c0006a22042802002206460d0020002001410c6c6a4184c0006a28020020066a2202200228020041808080807871417c20066b20036a72360200200420072802003602002002200228020041ffffffff07713602000b2000200041c4c1006a220728020041016a22023602c0412007200236020041000f0b2007200620026a36020020070b870201027f4100410028020441106b220336020420032001290300370308200028020820002802046b41074a41f0c20010012000280204200341086a410810031a2000200028020441086a220236020420032001290308370308200028020820026b41074a41f0c20010012000280204200341086a410810031a2000200028020441086a220236020420032001290310370308200028020820026b41074a41f0c20010012000280204200341086a410810031a2000200028020441086a22023602042003200141186a290300370308200028020820026b41074a41f0c20010012000280204200341086a410810031a2000200028020441086a3602044100200341106a36020420000ba00203017f017e027f4100410028020441106b2206360204420021042000420037031020004200370320200041186a42848abd9a0537030041002105200041286a41003a00002000412c6a410036020020062001360204200620013602002006200120026a36020820062000101e1a20062802042102200641086a21030340200220032802004941b0c4001001200628020422022d000021012006200241016a2202360204200141ff0071200541ff0171220574ad2004842104200541076a210520014107760d000b200041206a2004a72201101f02402001450d00200041246a2802002105200641086a28020020062802046b20014f41f0c300100120052006280204200110031a2006200628020420016a3602040b4100200641106a3602040bd40101017f200028020820002802046b41074b41f0c300100120012000280204410810031a2000200028020441086a2202360204200028020820026b41074b41f0c3001001200141086a2000280204410810031a2000200028020441086a2202360204200028020820026b41074b41f0c3001001200141106a2000280204410810031a2000200028020441086a2202360204200028020820026b41074b41f0c3001001200141186a22012000280204410810031a2000200028020441086a3602042001290300428486d592055141c0c400100120000beb0301057f0240024002400240024002400240024002402001450d002000280200220420014d0d0120002001360200200028020420016a41003a00000f0b20002d0008450d072000410c6a2802002201450d0720012001280200417f6a22043602002004450d010c070b200420014f0d05410c2001101822022000280204200028020010031a20002d0008450d042000410c6a2802002204450d0420042004280200417f6a22033602002003450d010c040b20002802042202450d0541002802cc4122044101480d05418cc00021012004410c6c418cc0006a21030340200141046a2802002204450d060240200441046a20024b0d00200420012802006a20024b0d030b2001410c6a22012003490d000c060b0b200041046a2802002205450d0241002802cc4122034101480d02418cc00021042003410c6c418cc0006a21060340200441046a2802002203450d030240200341046a20054b0d00200320042802006a20054b0d030b2004410c6a22042006490d000c030b0b2002417c6a2201200128020041ffffffff07713602000c030b2005417c6a2204200428020041ffffffff07713602000b20002001360200200041046a2002360200200041086a41013a00002000410c6a41003602000b0f0b20004200370200200041086a41013a00002000410c6a41003602000b0bfb020b0041040b04603200000041e0c1000b3c617474656d707420746f20636f6e73747275637420746f6b656e2066726f6d206173736574207769746820646966666572656e742073796d626f6c000041a0c2000b26696e7465676572206f766572666c6f7720616464696e6720746f6b656e2062616c616e6365000041d0c2000b1b73696e676c65746f6e20746f6f2062696720746f2073746f7265000041f0c2000b06777269746500004180c3000b0761637469766500004190c3000b566d616c6c6f635f66726f6d5f6672656564207761732064657369676e656420746f206f6e6c792062652063616c6c6564206166746572205f686561702077617320636f6d706c6574656c7920616c6c6f6361746564000041f0c3000b057265616400004180c4000b2c696e746567657220756e646572666c6f77207375627472616374696e6720746f6b656e2062616c616e6365000041b0c4000b04676574000041c0c4000b16756e657870656374656420617373657420747970650000a312046e616d65200b616374696f6e5f73697a650006617373657274020000086c6f61645f693634050000000000066d656d63707903000000066d656d736574030000000b726561645f616374696f6e0200000c726571756972655f61757468010011726571756972655f726563697069656e740100047362726b01000b73656e645f696e6c696e650200000973746f72655f69363404000000001b5f474c4f42414c5f5f7375625f495f63757272656e63792e63707000056170706c79020130013181015f5a4e35656f73696f386469737061746368494e535f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c79313338313331393432384579454545454e53345f31337472616e736665725f6d656d6f454e53345f356973737565454a454545627979070130013101320133013401350136755f5a4e35656f73696f3133756e7061636b5f616374696f6e494e535f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c7931333831333139343238457945454531337472616e736665725f6d656d6f454545545f76040130013101320133615f5a4e35656f73696f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c79313338313331393432384579454545326f6e45524b4e53335f387472616e73666572450701300131013201330134013501366c5f5a4e35656f73696f3133756e7061636b5f616374696f6e494e535f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c79313338313331393432384579454545356973737565454545545f7605013001310132013301345e5f5a4e35656f73696f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c79313338313331393432384579454545326f6e45524b4e53335f35697373756545070130013101320133013401350136af015f5a4e35656f73696f377461626c653634494c7935303933343138363737363535353638333834454c793134323839323335353232333930383531353834454e535f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c79313338313331393432384579454545313463757272656e63795f7374617473454531336765745f6f725f637265617465457979524b53355f06013001310132013301340135a6015f5a4e35656f73696f377461626c653634494c7935303933343138363737363535353638333834454c7933363037373439373738373335313034303030454e535f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c79313338313331393432384579454545376163636f756e74454531336765745f6f725f637265617465457979524b53355f060130013101320133013401356f5f5a4e35656f73696f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c793133383133313934323845794545453135696e6c696e655f7472616e7366657245797953325f4e535f36737472696e6745100130013101320133013401350136013701380139023130023131023132023133023134023135315f5a4e35656f73696f36766563746f72494e535f31367065726d697373696f6e5f6c6576656c45454332456a524b53315f0e01300131013201330134013501360137013801390231300231310231320231337a5f5a4e35656f73696f347061636b494e535f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c7931333831333139343238457945454531337472616e736665725f6d656d6f4545454e535f36766563746f7249634545524b545f09013001310132013301340135013601370138185f5a4e4b35656f73696f36616374696f6e3473656e644576070130013101320133013401350136225f5a4e35656f73696f31346d656d6f72795f6d616e61676572366d616c6c6f63456d0e0130013101320133013401350136013701380139023130023131023132023133505f5a4e35656f73696f6c73494e535f31306461746173747265616d49506345454e535f31367065726d697373696f6e5f6c6576656c45454552545f53365f524b4e535f36766563746f724954305f4545090130013101320133013401350136013701383b5f5a4e35656f73696f6c73494e535f31306461746173747265616d495063454563454552545f53355f524b4e535f36766563746f724954305f4545090130013101320133013401350136013701382d5f5a4e35656f73696f31346d656d6f72795f6d616e6167657231366e6578745f6163746976655f68656170457608013001310132013301340135013601377b5f5a4e35656f73696f6c73494e535f31306461746173747265616d4950634545454552545f53355f524b4e535f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c79313338313331393432384579454545387472616e7366657245040130013101320133705f5a4e35656f73696f36756e7061636b494e535f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c7931333831333139343238457945454531337472616e736665725f6d656d6f454545545f504b636a0701300131013201330134013501367b5f5a4e35656f73696f7273494e535f31306461746173747265616d49504b634545454552545f53365f524e535f313667656e657269635f63757272656e6379494e535f35746f6b656e494c7935303933343138363737363535353638333834454c79313338313331393432384579454545387472616e736665724503013001310132195f5a4e35656f73696f36737472696e6736726573697a65456a070130013101320133013401350136"},{"account":"eosio","name":"setabi","authorization":[{"actor":"currency","permission":"active"}],"data":"0000001e4d75af46010c6163636f756e745f6e616d65046e616d6504087472616e7366657200040466726f6d0c6163636f756e745f6e616d6502746f0c6163636f756e745f6e616d65087175616e74697479056173736574046d656d6f06737472696e67056973737565000202746f0c6163636f756e745f6e616d65087175616e74697479056173736574076163636f756e7400020863757272656e63790675696e7436340762616c616e63650675696e7436340e63757272656e63795f737461747300020863757272656e63790675696e74363406737570706c790675696e74363402000000572d3ccdcd087472616e736665720000000000a5317605697373756502000000204f4d113203693634010863757272656e6379010675696e743634076163636f756e740000000000904dc603693634010863757272656e6379010675696e7436340e63757272656e63795f7374617473"}],"signatures":["EOSKjmAUor3gRDcQZjfywMRqyqs4aPGnLaS8NTn921fYbyMCabjavhYxYwAeqtzoYxNCMB3GTJ8txbG9P2dknnZPmJeSa5ctX"]},"what":"read_until: End of file"}
    thread-0  httpc.cpp:117 call

**Comment by myenglishmail** [comment]
@ @heifner 
hi, as below I pasted, the issue, any ideas ?

**Comment by heifner** [comment]
Old issue. Feel free to reopen if still having a problem.
