### ISSUE TITLE
Test #29, nodeos_run_test-mongodb fails

### ISSUE THREAD

**Issue by apimdavid** [EOSIO/eos#2340]
(Could be related to issue #2103)

After building from git repo at commit 96ee0325..., All tests except one appear to succeed.  On Ubuntu 17.10.

The following tests FAILED:
	 29 - nodeos_run_test-mongodb (Failed)
	 31 - distributed-transactions-remote-test (Failed)
Errors while running CTest
Makefile:119: recipe for target 'test' failed
make: *** [test] Error 8

Note: mongod is definitely running; I started it before running the tests, with: ~/opt/mongodb/bin/mongod -f ~/opt/mongodb/mongod.conf &

...and confirmed mongod is accepting connections on 127.0.0.1 port 27017.

After I run tests/nodeos_run_test.py --mongodb -v --dump-error-detail >& /tmp/mongo_test.out,
the file /tmp/mongo_test.out contains:

kill: (27556): No such process
kill: (27558): No such process
BEGIN
TEST_OUTPUT: test_output_0.txt
SERVER: localhost
PORT: 8888
 echo db.version() | mongo --host localhost --port 27017 EOStest
 =================================================================
== Errors see above ==
Shut down the cluster.
 cmd: programs/eosio-launcher/eosio-launcher -k 15
 cmd: pkill nodeos
Shut down the wallet.
 cmd: pkill keosd
Traceback (most recent call last):
  File "tests/nodeos_run_test.py", line 86, in <module>
    if enableMongo and not cluster.isMongodDbRunning():
  File "/home/ubuntu/eos/build/tests/testUtils.py", line 1902, in isMongodDbRunning
    ret,outs,errs=Node.stdinAndCheckOutput(cmd.split(), subcommand)
  File "/home/ubuntu/eos/build/tests/testUtils.py", line 197, in stdinAndCheckOutput
    popen=subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mongo': 'mongo'

**Comment by PaulCalabrese** [comment]
Is the mongo shell program in your executable path? Check with "which
mongo" or simply try to run it.
You may need to install an additional package for this or add a directory
to your path.

We will try to improve the error message for this failure.


Paul Calabrese

**Comment by apimdavid** [comment]
Thanks, Paul. I wrongly assumed the build would keep track of where it installed the mongo executables. All tests are now passing.  This may now be a simple documentation issue.

**Comment by AaronFaltesek** [comment]
I had to add mongo to my path 

` PATH=$PATH:~/opt/mongodb/bin/`

resolved test 29 error. Still getting this: 

`The following tests FAILED:
         32 - distributed-transactions-remote-test (Failed)
         33 - restart-scenarios-test_resync (Failed)`
