### ISSUE TITLE
Testnet faucet

### ISSUE THREAD

**Issue by thomsonimjd** [EOSIO/eos#2341]
Pleae let me know where can I get testnet coin for testiing purpose.  Please give  me the testnet faucet link and the testnet explorer link too.

**Comment by heifner** [comment]
As of right now there is no public testnet.

**Comment by thomsonimjd** [comment]
@heifner I have been developing a trading platfrom where I would like to add EOS coin as one of them , please let me know the developing part and tesing part too.
