### ISSUE TITLE
!!!! dawn-v3.0.0 Build failed on macOS

### ISSUE THREAD

**Issue by David007** [EOSIO/eos#2347]
[ 92%] Built target test_cypher_suites
[ 92%] Built target test_exchange
[ 92%] Built target http_plugin
[ 92%] Linking CXX executable eosio-applesedemo
ld: framework not found security
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [programs/eosio-applesedemo/eosio-applesedemo] Error 1
make[1]: *** [programs/eosio-applesedemo/CMakeFiles/eosio-applesedemo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 94%] Built target eosio_chain
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by David007** [comment]
macdeMacBook-Pro:bin mac$ ./clang++ -v
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by spoonincode** [comment]
Can you go in to your eos/build directory and
`make VERBOSE=1`
and either attach the log or copy/paste the part toward the end where it fails

**Comment by David007** [comment]
@spoonincode 

[ 97%] Linking CXX executable eosio-applesedemo
cd /Users/mac/EOS/eos3.0/eos-v3/eos/build/programs/eosio-applesedemo && /usr/local/Cellar/cmake/3.11.0/bin/cmake -E cmake_link_script CMakeFiles/eosio-applesedemo.dir/link.txt --verbose=1
/usr/bin/clang++   -Wall -Wno-deprecated-declarations -O3 -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names -framework security -framework corefoundation CMakeFiles/eosio-applesedemo.dir/main.cpp.o CMakeFiles/eosio-applesedemo.dir/r1_signature_compactor.cpp.o  -o eosio-applesedemo ../../libraries/fc/libfc.a -L/usr/local/lib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_date_time-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libboost_program_options-mt.a /usr/local/lib/libboost_signals-mt.a /usr/local/lib/libboost_serialization-mt.a /usr/local/lib/libboost_chrono-mt.a /usr/local/lib/libboost_unit_test_framework-mt.a /usr/local/lib/libboost_context-mt.a /usr/local/lib/libboost_locale-mt.a /usr/local/lib/libboost_iostreams-mt.a /usr/lib/libpthread.dylib /usr/local/opt/openssl/lib/libssl.a /usr/local/opt/openssl/lib/libcrypto.a /usr/lib/libz.dylib /usr/lib/libbz2.dylib /usr/local/lib/libsecp256k1.a /usr/local/lib/libgmp.a 
ld: framework not found security
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [programs/eosio-applesedemo/eosio-applesedemo] Error 1
make[1]: *** [programs/eosio-applesedemo/CMakeFiles/eosio-applesedemo.dir/all] Error 2
make: *** [all] Error 2

**Comment by spoonincode** [comment]
Did you use eosio_build.sh to build? Or some other mechanism? Is this a recently cloned repo or something somewhat old?

For some reason you're building with /usr/bin/clang++ which is the clang included with Xcode. But you should be building with /usr/local/bin/clang++ which is the clang installed as part of homebrew.

**Comment by learnforpractice** [comment]
For a better help, I think you can compile the source code with the following command:

./eosio_build.sh <applewebdata://6FAAE2B5-2818-43FD-BFC5-18B9CCD8B3E0/eosio_build.sh> >compile.log 2>&1

And then attach the result in compile.log to the github issue.

**Comment by David007** [comment]
@learnforpractice 


	Beginning build version: 1.2
	Sat Apr 14 03:28:11 UTC 2018
	git head id: 96ee0325cc925ff3e90f865ebc72b01341196e08
	Current branch: * (HEAD detached at dawn-v3.0.0)

	ARCHITECTURE: Darwin

	OS name: Darwin
	OS Version: 10.13.4
	CPU speed: 240.00Ghz
	CPU cores: 4
	Physical Memory: 16 Gbytes
	Disk space total: 233G
	Disk space available: 189G

	Checking XCode installation
	XCode installation found.

	Checking Ruby installation
	Ruby installation found.

	Checking Home Brew installation
	Home Brew installation found.

	Checking dependencies.
	Checking automake ... 		 automake found
	Checking Libtool ... 		 Libtool found
	Checking OpenSSL ... 		 OpenSSL found
	Checking llvm ... 		 llvm found
	Checking wget ... 		 wget found
	Checking CMake ... 		 CMake found
	Checking Boost ... 		 Boost found
	Checking GMP ... 		 GMP found
	Checking gettext ... 		 gettext found
	Checking MongoDB ... 		 MongoDB found
	Checking Doxygen ... 		 Doxygen found
	Checking Graphviz ... 		 Graphviz found
	Checking Python3 ... 		 Python3 found

	No required Home Brew dependencies to install.

	Checking MongoDB C++ driver installation.
	Mongo C++ driver found at /usr/local/lib/libmongocxx-static.a.

	Checking secp256k1-zkp installation.
	secp256k1 found at /usr/local/lib/

	Checking LLVM with WASM support.
	WASM found at /usr/local/wasm/bin/


>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOS.IO

-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
-- Configuring Eos on OS X
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using WASM clang => /usr/local/wasm/bin/clang
-- Using WASM llc => /usr/local/wasm/bin/llc
-- Using WASM llvm-link => /usr/local/wasm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Configuring fc to build on Unix/Apple
-- zlib found
-- bzip2 found
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   unit_test_framework
--   locale
-- Configuring ChainBase on OS X
-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   program_options
--   unit_test_framework
--   locale
-- Configuring AppBase on OS X
-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: /usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-D_THREAD_SAFE
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: /usr/local/lib/libmongocxx-static.a;/usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-D_THREAD_SAFE;/usr/local/lib/libmongoc-static-1.0.a;/usr/local/lib/libbson-static-1.0.a;-D_THREAD_SAFE;-lsasl2;-framework Security;-framework CoreFoundation;-lz;-lresolv
-- Git commit revision: d9ad8eec
-- Git commit revision: d9ad8eec
-- Git commit revision: d9ad8eec
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mac/EOS/eos3.0/eos-v3/eos/build
[  0%] Built target asmjs
[  1%] Built target ast
[  1%] Built target binaryen
[  1%] Built target wasm
[  1%] Built target cfg
[  1%] Built target emscripten-optimizer
[  2%] Built target support
[  5%] Built target passes
[  5%] Built target Platform
[ 29%] Built target softfloat
[ 29%] Built target chainbase
[ 31%] Built target libc++
[ 31%] Built target eosiolib
[ 31%] Built target appbase
[ 31%] contract...
[ 31%] Built target copy_skeleton_contract
[ 73%] Built target libc
[ 73%] Built target print_floats
[ 73%] Built target eosio-s2wasm
[ 74%] Built target Logging
[ 75%] Built target eosio.bios
[ 76%] Built target simple.token
[ 76%] Built target chainbase_test
[ 77%] Built target eosio.token
[ 77%] Built target appbase_example
[ 77%] Built target eosio.msig
[ 79%] Built target multi_index_test
[ 79%] Built target eosio.system
[ 79%] Built target identity
[ 79%] Built target currency
[ 80%] Built target identity_test
[ 80%] Built target stltest
[ 80%] Built target test.inline
[ 80%] Built target asserter
[ 80%] Built target infinite
[ 81%] Built target test_api
[ 81%] Built target proxy
[ 81%] Built target test_api_mem
[ 81%] Built target test_api_db
[ 82%] Built target test_api_multi_index
[ 83%] Built target noop
[ 84%] Built target dice
[ 84%] Built target IR
Scanning dependencies of target exchange
[ 84%] Building LLVM bitcode exchange.cpp.bc
[ 84%] Built target WASM
[ 84%] Generating exchange.abi.hpp
[ 85%] Built target Runtime
[ 86%] Built target WAST
[ 86%] Built target Emscripten
[ 86%] Built target Assemble
Scanning dependencies of target Disassemble
Scanning dependencies of target Test
[ 86%] Building CXX object libraries/wasm-jit/Source/Programs/CMakeFiles/Disassemble.dir/Disassemble.cpp.o
[ 86%] Building CXX object libraries/wasm-jit/Source/Programs/CMakeFiles/Test.dir/Test.cpp.o
[ 91%] Built target fc
[ 91%] Built target test_cypher_suites
Scanning dependencies of target wavm
[ 91%] Building CXX object libraries/wasm-jit/Source/Programs/CMakeFiles/wavm.dir/wavm.cpp.o
[ 91%] Linking CXX executable Disassemble
[ 91%] Built target Disassemble
Scanning dependencies of target eos_utilities
[ 91%] Linking CXX executable Test
[ 91%] Building CXX object libraries/utilities/CMakeFiles/eos_utilities.dir/key_conversion.cpp.o
/Users/mac/EOS/eos3.0/eos-v3/eos/contracts/exchange/exchange.cpp:115:34: warning: unused parameter 'fee' [-Wunused-parameter]
                 uint32_t        fee,
                                 ^
[ 91%] Built target Test
[ 92%] Linking CXX executable wavm
Scanning dependencies of target test_exchange
[ 92%] Building CXX object contracts/exchange/CMakeFiles/test_exchange.dir/test_exchange.cpp.o
[ 92%] Built target wavm
[ 92%] Building CXX object plugins/http_plugin/CMakeFiles/http_plugin.dir/http_plugin.cpp.o
1 warning generated.
[ 92%] Linking LLVM bitcode executable exchange.bc
[ 92%] Generating textual assembly exchange.s
/Users/mac/EOS/eos3.0/eos-v3/eos/contracts/exchange/test_exchange.cpp:347:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
/Users/mac/EOS/eos3.0/eos-v3/eos/contracts/exchange/test_exchange.cpp:361:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
/Users/mac/EOS/eos3.0/eos-v3/eos/contracts/exchange/test_exchange.cpp:368:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
/Users/mac/EOS/eos3.0/eos-v3/eos/contracts/exchange/test_exchange.cpp:376:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
[ 92%] Building CXX object libraries/utilities/CMakeFiles/eos_utilities.dir/string_escape.cpp.o
[ 92%] Generating WAST exchange.wast
[ 92%] Generating exchange.wast.hpp
[ 92%] Built target exchange
[ 92%] Building CXX object libraries/utilities/CMakeFiles/eos_utilities.dir/tempdir.cpp.o
[ 92%] Linking CXX executable eosio-applesedemo
ld: framework not found security
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [programs/eosio-applesedemo/eosio-applesedemo] Error 1
make[1]: *** [programs/eosio-applesedemo/CMakeFiles/eosio-applesedemo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 92%] Building CXX object libraries/utilities/CMakeFiles/eos_utilities.dir/words.cpp.o
4 warnings generated.
[ 92%] Linking CXX executable test_exchange
[ 92%] Built target test_exchange
[ 92%] Linking CXX static library libeos_utilities.a
[ 92%] Built target eos_utilities
/Users/mac/EOS/eos3.0/eos-v3/eos/plugins/http_plugin/http_plugin.cpp:182:66: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
                        handler_itr->second(resource, body, [con,this](int code, string body) {
                                                                 ^
1 warning generated.
[ 92%] Linking CXX static library libhttp_plugin.a
[ 92%] Built target http_plugin
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by learnforpractice** [comment]
Yeah, sounds like you are missing security framework which need by programs/eosio-applesedemo/CMakeLists.txt
For a quick fix, just comment out the following line in programs/CMakeLists.txt, as you probably would’t  play with eosio-applesedemo.

add_subdirectory( eosio-applesedemo )


Or try command 

softwareupdate --install —all

to update your OS X?

Also I think the eos team have a better solution.

**Comment by spoonincode** [comment]
It's not the first time we've seen this, but it's very rare. Not sure why the build is picking up that clang. Can you post the result of these two commands
`echo $PATH`

`which clang++`
