### ISSUE TITLE
get table array values not being returned

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#2350]
Specific example is tic_tac_toe tutorial, "get table" returns:

{
  "rows": [{
      "challenger": "player2",
      "host": "player1",
      "turn": "player2",
      "winner": "none",
      "board": []
    }
  ],
  "more": false
}

even though board is a uint8_t[9] and has values

**Comment by brianjohnson5972** [comment]
@wanderingbort                        
I think the issue is that in the abi the type is defined as "uint8_t[]" which maps to a vector<T> for pack/unpack, but in tic_tack_toe.hpp the parameter is:
uint8_t      board[9];
Which will NOT be mapped to operator<< with vector<T>, so the packing/unpacking don't match.

I think it is calling "DataStream& operator << ( DataStream& ds, const std::array<T,N>& v )" which is more efficient for packing/unpacking in contracts, but there is nothing on the abi that could handle this.

**Comment by brianjohnson5972** [comment]
Handling this by implementing operator<< for std::array and adding one for "T (&v)[N}" and using a similar implementation to std::vector<T> so that there is a size for abi serializer to use to size the vector that it will allocate to handle all of these types.

**Comment by andriantolie** [comment]
Played the tic_tac_toe contract and can verify for each step the board is printed properly by cleos get table command
