### ISSUE TITLE
Docker build error: CMake Error at plugins/mongo_db_plugin/CMakeLists.txt:22

### ISSUE THREAD

**Issue by jrosich** [EOSIO/eos#2352]
Following steps as stated here: https://github.com/EOSIO/eos/tree/master/Docker
Got the following error on docker build:

> -- Configuring AppBase on Linux
> CMake Error at plugins/mongo_db_plugin/CMakeLists.txt:22 (find_package):
>   By not providing "Findlibbsoncxx-static.cmake" in CMAKE_MODULE_PATH this
>   project has asked CMake to find a package configuration file provided by
>   "libbsoncxx-static", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "libbsoncxx-static"
>   with any of the following names:
> 
>     libbsoncxx-staticConfig.cmake
>     libbsoncxx-static-config.cmake
> 
>   Add the installation prefix of "libbsoncxx-static" to CMAKE_PREFIX_PATH or
>   set "libbsoncxx-static_DIR" to a directory containing one of the above
>   files.  If "libbsoncxx-static" provides a separate development package or
>   SDK, be sure it has been installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/tmp/build/CMakeFiles/CMakeOutput.log".
> See also "/tmp/build/CMakeFiles/CMakeError.log".
> The command '/bin/sh -c git clone -b master --depth 1 https://github.com/EOSIO/eos.git --recursive     && cd eos     && cmake -H. -B"/tmp/build" -GNinja -DCMAKE_BUILD_TYPE=Release -DWASM_ROOT=/opt/wasm -DCMAKE_CXX_COMPILER=clang++        -DCMAKE_C_COMPILER=clang -DCMAKE_INSTALL_PREFIX=/tmp/build  -DSecp256k1_ROOT_DIR=/usr/local -DBUILD_MONGO_DB_PLUGIN=true     && cmake --build /tmp/build --target install' returned a non-zero code: 1

**Comment by abejdaniels** [comment]
Running into the same issue using Docker build.

**Comment by Akagi201** [comment]
rebuild eos/builder docker image, and then build eos docker image, as it has some changes.

**Comment by ajose01** [comment]
Having the same issue. Can you explain a bit further what you mean by rebuilding eos/builder docker image?

I rmi'd both the EOS images and did a fresh git pull and docker build . and no go. Thanks.

**Comment by Akagi201** [comment]
```
cd Docker/builder
docker build -t eos/builder .
```

**Comment by ajose01** [comment]
Thanks for that. eos/builder successfully builds, but unfortunately that doesn't change the error when following up with eos docker image build.

**Comment by jrosich** [comment]
cd Docker/builder
docker build -t eos/builder .

Does not work on OSX: 

>  Errors were encountered while processing:
>  /var/cache/apt/archives/perl_5.22.1-9ubuntu0.2_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ajose01** [comment]
> Does not work on OSX:

MacOS High Sierra worked for eos/builder in my case...
```
Successfully built f7567c7c5cd6
Successfully tagged eos/builder:latest
```

eos image is what fails for me.

**Comment by jrosich** [comment]
I think I found the problem here: eosio/builder is 2 weeks old, so we have to build it locally. However, the right build has to be:

```
cd Docker/builder
docker build -t eosio/builder .
```
Notice "eosio/" instead of "eos/"

So, in order to compile Docker, follow this steps:

```
cd <whatever path to project>/eos/Docker/builder
docker build -t eosio/builder .
cd ..
docker build . -t eosio/eos
```

and everything should be fine.
Im compiling right now and its working so far. I will update as soon as Im finished.

**Comment by gonjay** [comment]
@Akagi201 What's the difference between esobuilder and eos?

**Comment by Akagi201** [comment]
@gonjay here https://github.com/EOSIO/eos/commit/148e742b34415b5ba7d5ce5f37cf19a9ee49744a

**Comment by ericiles** [comment]
I have updated eosio/builder on Docker Hub. This should resolve this issue.

**Comment by svenpohl** [comment]
Does exist a precompiled dockerimage? In my case (MacOS) the script abort with "returned a non-zero code: 137". Thanks.
