### ISSUE TITLE
Updating code on existing contract fails if only the ABI has changed

### ISSUE THREAD

**Issue by dallasjohnson** [EOSIO/eos#2358]
When updating a contract where the only effective change is a change to the ABI the uniqueness checking on the code appears to only consider the wast code changes.

## Steps to reproduce.
1. Create a cpp contract with a table annotation. `// @abi table`
2. Ensure it successfully is set via `cleos set code ...`
3. Change only the annotation in the cpp.
4. recompile and check that the table as been removed from the ABI.
5. Attempt to set the code again with `cleos set code ...` command.

## Result: 
`Error Details:
account.code_version != code_id: contract is already running this version of code`

## Expected result:
Since the ABI has changed and is part of the upload package to the code it should accept the code as a different contract.

**Comment by fan31415** [comment]
Same here.

**Comment by jafri** [comment]
@arhag do ABI changes still not invalidate version?

**Comment by andriantolie** [comment]
ABI and code are treated separately. If you just want to set the abi, please use `cleos set abi` instead.  :)
