### ISSUE TITLE
treat ABI as binary blob in setabi

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2359]
## The Concern

`setabi` is currently a native action that validates the provided ABI. 

We expect the ABI to change to adapt to the different ways contracts may wish to interpret the data of an action or the way data is stored in tables (or the way Ricardian contracts work). Also, new standards for an ABI may emerge that are better suited to the way data is handled by some contracts. 

With the current approach to `setabi`, updating the native action to support different versions of ABIs would be a hard-forking change. However, the chain/protocol does not care about the details of the ABI. All it needs is the raw data to store and to charge appropriately for the memory needed to store it. The clients (like cleos) are the ones that actually need to interpret the raw data as a valid ABI to use it to do things like represent a transaction in human-readable JSON.

## A Simple Fix

The obviously fix is to just avoid validating the ABI in the native action handler for `setabi`. So, the `setabi` action would continue to include the account name for which the ABI will be set and a vector of bytes containing the serialized ABI which should just be stored appropriately and not validated. As part of conforming to a standard, the vector of bytes might have an ABI type and version number stored in the beginning of the serialization to help clients easily figure out if and how they can interpret the serialized ABI; but this is again not a concern for the `setabi` action itself.

### Move to WASM System Contract
 
We should investigate whether it makes sense to actually remove `setabi` as a native action and instead provide it as part of the WASM system contract. After all, the chain/protocol really does not care about the contents of the ABI nor should it need access to it in any way. So it really does not make sense to have it as a native action. Also, by having it in the system contract, the action handler can be upgraded without a hard-fork. 

 The only complication with that approach is that if the raw ABI data is to continue to be stored in the `abi` field of the `account_object`, then a new `privileged_api` intrinsic would need to be added to allow the system contract to set that field.

### Remove `setabi` Altogether and Instead Create a Standard

Alternatively, the ABI could be stored as part of the contract's persistent state in a standard location that is unlikely to conflict with any other tables the contract would want to store. For example, the scope id 1 (which would never conflict with using either an `account_name` or `symbol_code` as a scope id) could be used to hold a special `metadata` table which would have a row with primary key `abi` that contains the raw serialized ABI data. 

With this alternative approach, neither a native `setabi` action nor a `setabi` action in the WASM system contract would be necessary. Instead, each contract could provide a `setabi` action that allows the appropriate authority to set the ABI for that contract in the appropriate location according to the standard. 

Another variation is for that contract's `setabi` action to get the serialized ABI data (which it again stores in the appropriate standard location without validation) from a referenced context-free `validateabi` action in the same transaction. The `validateabi` context-free action could be provided by some other contract that many contracts use to validate their ABIs.  With this approach, contract developers can continue to be assured, as they can today, that the transaction to set the ABI will not succeed unless the submitted ABI validates correctly.

Whichever approach is used to get the serialized ABI into the appropriate place in the contract's persistent state, standard-conforming tools would check to see if the appropriate row exists and if so would parse the serialized data to reconstruct the ABI for whatever purpose they need it for.

**Comment by bytemaster** [comment]
ABI cannot be binary blob as it implies Ricardian contracts under constitution which has legal effect.
