### ISSUE TITLE
Update name.cpp to match eosio_contract.cpp

### ISSUE THREAD

**Issue by jonericcook** [EOSIO/eos#2360]
`name.cpp` allows account names of length 13
https://github.com/EOSIO/eos/blob/master/libraries/chain/name.cpp#L11

`eosio_contract.cpp` allows account names of length 12
https://github.com/EOSIO/eos/blob/master/libraries/chain/contracts/eosio_contract.cpp#L55

@heifner for showing me where to find info about account names and bringing up this discrepancy.

**Comment by heifner** [comment]
This would provide a better error message for #2337.
`table_name` does take advantage of the 13th character. So in some cases we do want a type that works like `name` today. One solution would be to create a `name12` that restricts to 12 characters. Most types that are `name`s today would become typedefed to `name12` instead. `table_name` would be typedefed to name13.

**Comment by brianjohnson5972** [comment]
This issue was handled in other issues.
