### ISSUE TITLE
starting the second producer node failed when following the tutorial Testnet Single Host Multinode 

### ISSUE THREAD

**Issue by woshidama323** [EOSIO/eos#2362]
hi
    I want to start multiple nodes on one host (ubuntu) when following the new tutorial "Testnet Single Host Multiplenode"
but failed to start the second producer node and the console printed some errors like this below, 
the first node worked well. could you help to have a look about those errors  ?
thanks 
-------------------------------------------------------------------------------------------------------------------------------------------
3247266ms thread-0   net_plugin.cpp:1249           start_sync           ] Catching up with chain, our last req is 0, theirs is 12019 peer harry-ThinkPad-Edge-E535:9876 - 4c6868e
3247267ms thread-0   chain_controller.cpp:1402     validate_block_heade ] head_block_time 2018-03-01T12:00:00.000, next_block 2018-04-13T01:13:32.000, block_interval 500
3247267ms thread-0   chain_controller.cpp:1404     validate_block_heade ] Did not produce block within block_interval 500ms, took 3676412000ms)
3247269ms thread-0   chain_controller.cpp:254      _push_block          ] Failed to push new block:
10 assert_exception: Assert Exception
false: implicit transaction not found {"status":"executed","kcpu_usage":2,"net_usage_words":38,"id":"239e5bb0bea2312d918f3bd3e0f3b0fe9923484dea7928c05e85cb8341adc4ff"}
    {"trx":{"status":"executed","kcpu_usage":2,"net_usage_words":38,"id":"239e5bb0bea2312d918f3bd3e0f3b0fe9923484dea7928c05e85cb8341adc4ff"}}
    thread-0  chain_controller.cpp:897 operator()

    {"next_block.block_num()":1}
    thread-0  chain_controller.cpp:960 __apply_block
3247270ms thread-0   net_plugin.cpp:2321           handle_message       ] unable to accept block on assert exception Assert Exception (10)
false: implicit transaction not found {"status":"executed","kcpu_usage":2,"net_usage_words":38,"id":"239e5bb0bea2312d918f3bd3e0f3b0fe9923484dea7928c05e85cb8341adc4ff"}

 from harry-ThinkPad-Edge-E535:9876 - 4c6868e
3247270ms thread-0   net_plugin.cpp:1388           recv_block           ] second attempt to retrive block 1 failed
3247270ms thread-0   net_plugin.cpp:1201           request_next_chunk   ] Unable to continue syncing at this time
3247270ms thread-0   net_plugin.cpp:1855           operator()           ] Error reading message from 127.0.0.1:9876: Bad file descriptor
3277265ms thread-0   net_plugin.cpp:1723           connect              ] host: 127.0.0.1 port: 9876 
3277266ms thread-0   net_plugin.cpp:1249           start_sync           ] Catching up with chain, our last req is 0, theirs is 12079 peer harry-ThinkPad-Edge-E535:9876 - 4c6868e

**Comment by icodezjb** [comment]
in my case,  make your second block prodecuer's genesis.json as same as your  fisrt  block prodecuer's

**Comment by woshidama323** [comment]
ok, thanks for your help
