### ISSUE TITLE
Unknown stuct error when generating the abi

### ISSUE THREAD

**Issue by narcis2007** [EOSIO/eos#2371]
I wanted to interact with another smart contract from my smart contract so I copied the deposit function from the exchange contract and import the currency.hpp in mine but when I try to generate the abi I get this error:

985024ms thread-0   main.cpp:106                  main                 ] 10 assert_exception: Assert Exception
itr != structs.end(): Unknown struct asset
    {"type":"asset"}
    thread-0  abi_serializer.cpp:184 get_struct

    {"s":["extended_asset",{"name":"extended_asset","base":"asset","fields":[{"name":"contract","type":"account_name"}]}]}
    thread-0  abi_serializer.cpp:215 validate
985024ms thread-0   main.cpp:106                  main         

the compilation works fine

Do you know how can I solve this?

I see that it is hardcoded as a type here: https://github.com/EOSIO/eos/blob/master/libraries/chain/contracts/abi_serializer.cpp#L65

**Comment by leordev** [comment]
Same issue here. If I try to use `extended_asset` in my struct I receive the same error when I try to generate the `abi`. When using the simple `asset` type in my struct it works normally... So I guess it's something related to the `extended_asset` inheritance.

**Comment by andriantolie** [comment]
@narcis2007 Do you still encounter this problem with latest version?

**Comment by narcis2007** [comment]
@andriantolie got fixed now
