### ISSUE TITLE
dawn3: tilde not recognized as $HOME

### ISSUE THREAD

**Issue by robertkowalski** [EOSIO/eos#2373]
Hi folks, small issue.

When I use `nodeos --config-dir=~/eos/build/config` it **creates** a directory `~` instead of pointing to my home dir.

log output:

```
3353567ms thread-0   chain_plugin.cpp:178          plugin_startup       ]
 generating default genesis file /Users/robert/eos/build/config/~/eos/build/config/genesis.json
```

**Comment by spoonincode** [comment]
This works if you use a space instead of equals, for example
`nodeos -d ~/eos.data/node1 --config-dir ~/eos.data/node1 `
certainly works since that's what I always do. Trying to fully support `~` may be a slippery slope as we'll need to correctly handle that inside of config variables and such.
