### ISSUE TITLE
Build errors.  Installing / linking dependancies

### ISSUE THREAD

**Issue by coreylederer** [EOSIO/eos#2375]
Receiving the following error when running eosio_build.sh

Updating Home Brew.
Already up-to-date.
	Installing Dependencies.
Warning: graphviz 2.40.1 is already installed, it's just not linked
You can use brew link graphviz to link this version.
Warning: python 3.6.5 is already installed, it's just not linked
You can use brew link python to link this version.
Unlinking /usr/local/Cellar/graphviz/2.40.1... 0 symlinks removed
Unlinking /usr/local/Cellar/python/3.6.5... 0 symlinks removed
Linking /usr/local/Cellar/graphviz/2.40.1... 108 symlinks created
Linking /usr/local/Cellar/python/3.6.5... Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks
	Homebrew exited with the above errors.
	Exiting now.

Also saw this error in eosio_build.sh output this morning:

	Checking dependencies.
	Checking automake ... 		 automake found
	Checking Libtool ... 		 Libtool found
	Checking OpenSSL ... 		 OpenSSL found
	Checking llvm ... 		 llvm found
	Checking wget ... 		 wget found
	Checking CMake ... 		 CMake found
	Checking Boost ... 		 Boost found
	Checking GMP ... 		 GMP found
	Checking gettext ... 		 gettext found
	Checking MongoDB ... 		 MongoDB found
	Checking Doxygen ... 		 Doxygen found
	Checking Graphviz ... 		 Graphviz found
	Checking  ... /Users/macmini06/eos/scripts/eosio_build_darwin.sh: line 103: [: ==: unary operator expected
/Users/macmini06/eos/scripts/eosio_build_darwin.sh: line 109: [: =: unary operator expected

**Comment by coreylederer** [comment]
Issue resolved.  Local config problem.  Closing.

**Comment by andriantolie** [comment]
Since it's about local config problem, marked as "needs testing - pass". Also, I have no problem building it on my mac today.
