### ISSUE TITLE
EOSIO accounts should include a 3rd permission (named "action") after creation 

### ISSUE THREAD

**Issue by PunchPlump** [EOSIO/eos#2376]
At the moment EOSIO accounts are created with just an "owner" and an "active" key. I propose that accounts are created with also a 3rd key, which is for the "action" permission. 

The "action" key should be used to sign for actions which don't involve money (tokens), which in case of some contracts might always be the case. Requiring that all users of the EOSIO platform have an "action" permission means they don't have to unnecessarily expose their active key in these situations. An "action" key would make it possible for wallets to auto-sign actions which only require the "action" key (during a session or even permanently). It's also much less disastrous if someone's "action" key is compromised compared to when keys above that permission level are compromised. 

I believe this proposal would increase both security and usability greatly!

P.S.: This is my first time on Github and I felt my idea was important enough to share. I assumed it would have been implemented by now, but it still isn't, so I'll just let it be known. I don't know if it's appreciated that people who never contributed add issues, but I feel like this one would never be a waste of time since it's that important.

**Comment by PunchPlump** [comment]
Accidentally made a duplicate when I tried to add the issue to RC2 (sorry guys, new to Github). If anyone agrees to move this one to RC2 that would be appreciated.

Looking forward to any feedback regardless.

**Comment by learnforpractice** [comment]
I think we can give the owner key the ability to lock the contract on the account. That’s say before the contract is been lock on, owner key can updates it’s code freely, but when the contract is mature enough, owner key can just lock the code.That means even the owner key has been compromised, the code is still there, function as normal. I took this idea from the fuse bit in microcontroller. Developers can burn the fuse bit to keep their code safe in chips. Although I think multisig is still the best choice.

**Comment by andriantolie** [comment]
You can always make a new key that is derived from active by using `cleos set account permission`. And you can link that permission to any action you want by using `cleos set action permission`. :)

**Comment by brianjohnson5972** [comment]
At this stage of the released code, regardless of how good the idea was, this would be more drastic than a hard fork, since it would require changing every contract that is already deployed.  To garner the support that would be required to get a change like this accepted, I would suggest using the [EOS Developer telegram channel](https://t.me/joinchat/Esi1OkPktgcFeJ3Lmlcrqg)
