### ISSUE TITLE
file logger is disabled / fails to build

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#2377]
EOSIO supports console logging, gelf logging, and... uh.. I thought file logging. But the file logger is disabled and won't compile without some changes. Seems like people would want logs to go to a file.

**Comment by brianjohnson5972** [comment]
@spoonincode I think everyone is getting around this by just piping to a file.  Any objections to closing this?  If users want it, I think they will let us know.

**Comment by ank-everstake** [comment]
I searched a way to write log messages in json to a file, and find a workaround. You can use gelf type appender and point it to localhost. If you run [this](https://gist.github.com/ank-everstake/be91ba54a43e8dd68161c60ca9a66af1) kind of script you will be able to catch json and write all or part of log line to a file.
Run it like: ` python3 gelf_to_file.py`
It writes to stdout and to a file named as gelf-appender name (in logging json) which is passed in hostname field in log. Modify parsed fields and comment unused print statements. Nodeos uses zlib, gzip is left for history reasons.
Still it would be great to have json logging to a file more native.
