### ISSUE TITLE
Assertion `block' failed

### ISSUE THREAD

**Issue by 0x83043** [EOSIO/eos#238]
Hello!

I've got error message after a few (14-15) blocks generated in the single-node testnet. I confused about `/root/eos...` path, because it directory where i just built EOS, and after that execute `make install` and launch EOS under `eos` user with his home-directory.

```
eosd: /root/eos/libraries/chain/chain_controller.cpp:1263: void eos::chain::chain_controller::update_last_irreversible_block(): Assertion `block' failed.
Aborted
```

**Comment by bytemaster** [comment]
Can you reproduce this issue?

**Comment by 0x83043** [comment]
It's doesn't disappear. What additional information you need?

**Comment by heifner** [comment]
Unable to reproduce. Feel free to re-open if you have steps to reproduce.
