### ISSUE TITLE
needs more investigation -- unexpected txn expiry

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#2384]
This was seen on the internal test net today when the network was in a bad state and producers were minting empty blocks.

I execute this on my local node
```
./cleos create account eosio spoonz $PUBKEY $PUBKEY; \
 while true; do ./cleos get account spoonz; sleep 0.1; done
```
My local node sees the spoonz account but very quickly (less than 500ms) I no longer see the spoonz account.

Since cleos sets the expiration for 30 seconds, and no txns are being included in any blocks, the expected behavior was for my node to show the spoonz account for ~30 seconds, correct?

`./cleos get info` is incrementing the LIB and head block.

**Comment by brianjohnson5972** [comment]
@wanderingbort is this OBE?
