### ISSUE TITLE
Consider adding `int get_action_count(int type)` intrinsic function

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2386]
# Description

In #2356 it is outlined that dispatch ordering for inline context-free and regular actions when fetching them with `get_action(int, int, int, int)` .  The rationale is that you could then calculate the index for the actions you send as part of that action whereas without it you would not know if depth-first execution injected other actions' actions.

However, we have no convenient method for accessing the current count of context-free and regular actions sent inline.  We can see the explicit context-free and regular actions by reading the whole transaction (inconvenient but possible) however, this would not include those generated by actions using `send_inline*`

# Proposal

- add `int get_action_count(int type)` which is given the type of action (same as `get_action` ) and returns the current number of actions accessible by `get_action(...)`. 

# Acceptance Test Criteria

- [ ] test cases that prove an action can accurately determine the ordinal needed to read an inline context-free or regular action it creates, regardless of the remainder of exectution

**Comment by bytemaster** [comment]
We would like to simplify requirements for June to state that you can only read actions declared in the transaction, not generated actions.

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner I am thinking this is OBE.  If I don't hear from you I will presume that is the case.

**Comment by brianjohnson5972** [comment]
No longer part of the plan for C API
