### ISSUE TITLE
eosio/eos Docker image, eosiocpp  throws error 

### ISSUE THREAD

**Issue by karthik-ir** [EOSIO/eos#2387]
on creating hello.cpp and running 
` eosiocpp -o hello.wast hello.cpp ` 

I get error : `/opt/eosio/bin/eosiocpp: line 42: /opt/wasm/bin/clang: No such file or directory`

**Comment by grigio** [comment]
I confirm, I tried also the `eosio/builder` image but there are other problems #2320

**Comment by grigio** [comment]
dup #2480

**Comment by ericiles** [comment]
eosio/builder:latest now has all the required tools/libraries to compile contracts. I just tested using the hello contract. If you run into any other problems, please feel free to open additional issues.

**Comment by joaoritter** [comment]
hey @ericiles I'm still having trouble with this. I've got my docker containers set up and running. I've successfully created keys and accounts, and successfully completed the tutorial https://github.com/EOSIO/eos/wiki/Tutorial-eosio-token-Contract and am now working on https://github.com/EOSIO/eos/wiki/Tutorial-Hello-World-Contract.
I've set the following alias "alias eosiocpp='docker-compose exec keosd /opt/eosio/bin/eosiocpp'", but when I run "eosiocpp -o hello.wast hello.cpp", I get "clang-4.0: error: no such file or directory: 'hello.cpp'"
I am sure I'm running from the correct directory. I'm likely misunderstanding the docs, some clarification would be great!

Thank you

**Comment by luckyyang** [comment]
@joaoritter I commented here: https://github.com/EOSIO/eos/issues/4105#issuecomment-400929571

**Comment by vijaytabhatt** [comment]
@ericiles i get error eosiocpp not found
i am able to use nodeos and keosd

am i missing something?

**Comment by ericiles** [comment]
This has all changed since my comment on May 7th. You should now use the eosio/eos-dev:latest image. It contains all the required binaries and dependencies to work with smart contracts now.

**Comment by li3365** [comment]
I' m using the eosio/eos-dev:latest image. another error:
hello.cpp:1:10: fatal error: 'eosiolib/eosio.hpp' file not found

**Comment by vijaytabhatt** [comment]
@li3365  This is may be because there is not eosiolib folder from where you are running command
please search for eosiolib folder and then copy it to the folder from where you are running commands , if you can give me more details or screenshot i can help you

**Comment by lazaridiscom** [comment]
try the latest 1.2.0, this should fix your issues
