### ISSUE TITLE
Fix access control for context-aware vs context-free APIs

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2388]
Changes needed:

- `softfloat_api`  and `compiler_builtins` are currently not available to context-free actions when they should be.
- The exposed methods of `apply_context` are currently available to context-free actions when they should not be.
- `check_auth` should be moved from `context_free_transaction_api` (which is available to context-free actions) to `permission_api` (which is only available to context-aware actions). 
- Determine whether `now()` should be available to context-free actions. If not, then:
  * `now()` should be moved out of the `system_api` (which is available to both context-free and context-aware actions) to an API that is only available to context-aware actions.
  * We should figure out if `action_api::publication_time()` needs to be dealt with in a similar way. It wouldn't be a problem for a deferred transaction, but it may be for an immediately-executing input transaction.
- Determine whether `context_free_transaction_api::get_action` needs to be split into multiple functions: one that only gets actions in the original transaction and is available to both context-free and context-aware actions; and another one that can get all the actions in the current implicit transaction (including ones dispatched during execution of previously executed actions). Related to issues #2356 and #2386.

ATC:
- Unittests test all the api categories for access via context free actions.

**Comment by bytemaster** [comment]
Now should not be available to CFA (it could invalidate it randomly).

Publication time should not be available to CFA, the only reason for contract to know pub time is to enforce security delays, CFA are "self-certifying" and have no "auth requirements" and therefore no delay.
