### ISSUE TITLE
Create index with string key sorted alphabetically

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#239]
Ensure it works with get table rows and other APIs for tables.

**Comment by elmato** [comment]
#859aa75
The str index has been refactored to use shared_string instead of Name type.
Need more testing and to solve a problem with the wasm-vm that for some reason is not finding some intrinsic functions related to this index.

**Comment by elmato** [comment]
Pull request ready to review and merge EOSIO/eos#274
