### ISSUE TITLE
eosiocpp generating wast fails

### ISSUE THREAD

**Issue by cartmarsh** [EOSIO/eos#2393]
I get this error 
Domis-MacBook-Pro:~ domi$ eos/build/tools/eosiocpp -o testc.wast testc.cpp
In file included from testc.cpp:6:
In file included from /usr/local/include/eosiolib/db.h:8:
In file included from /usr/local/include/eosiolib/types.h:7:
/usr/local/include/stdint.h:18:10: fatal error: 'sys/_types/_int8_t.h' file not found
#include <sys/_types/_int8_t.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

but when i look in the default include paths I would find the file:
Domis-MacBook-Pro:_types domi$ pwd
/usr/local/sys/_types
Domis-MacBook-Pro:_types domi$ ls
_blkcnt_t.h		_fd_zero.h		_int16_t.h		_o_sync.h		_sigset_t.h		_u_int32_t.h
_blksize_t.h		_filesec_t.h		_int32_t.h		_off_t.h		_size_t.h		_u_int64_t.h
_caddr_t.h		_fsblkcnt_t.h		_int64_t.h		_offsetof.h		_socklen_t.h		_u_int8_t.h
_clock_t.h		_fsfilcnt_t.h		**_int8_t.h**		_os_inline.h		_ssize_t.h		_u_short.h
_ct_rune_t.h		_fsid_t.h		_intptr_t.h		_pid_t.h		_suseconds_t.h		_ucontext.h
_dev_t.h		_fsobj_id_t.h		_iovec_t.h		_posix_vdisable.h	_time_t.h		_ucontext64.h
_errno_t.h		_gid_t.h		_key_t.h		_ptrdiff_t.h		_timespec.h		_uid_t.h
_fd_clr.h		_guid_t.h		_mach_port_t.h		_rsize_t.h		_timeval.h		_uintptr_t.h
_fd_copy.h		_id_t.h			_mbstate_t.h		_rune_t.h		_timeval32.h		_useconds_t.h
_fd_def.h		_in_addr_t.h		_mode_t.h		_s_ifmt.h		_timeval64.h		_uuid_t.h
_fd_isset.h		_in_port_t.h		_nlink_t.h		_sa_family_t.h		_u_char.h		_va_list.h
_fd_set.h		_ino64_t.h		_null.h			_seek_set.h		_u_int.h		_wchar_t.h
_fd_setsize.h		_ino_t.h		_o_dsync.h		_sigaltstack.h		_u_int16_t.h		_wint_t.h

**Comment by nsjames** [comment]
Have you done `sudo make install` from the `build/` directory?

**Comment by cartmarsh** [comment]
yes I did. I guess it is a problem with my include path. I went on to use eosio on a virtual machine.

**Comment by luoxiaohui** [comment]
+1

**Comment by andriantolie** [comment]
Yes, I think it's very likely you didn't have /usr/local inside your include path.
