### ISSUE TITLE
missing Wast files

### ISSUE THREAD

**Issue by dunkan50** [EOSIO/eos#2395]
I am trying to build the **Testnet-Single-Host-Multinode**  and I am running to the following error...

```
1645753ms thread-0   main.cpp:1158        main                 ] Failed witherror: Assert Exception (10)
!wast.empty(): no wast file found build/contracts/eosio.bios/eosio.bios.wast
```
but the file in is present in the give directory.

**Comment by nsjames** [comment]
Yes, you will need to build it yourself using `eosiocpp -o eosio.bios.wast eosio.bios.cpp`.

If it throws an error on the eosiolib/eosio.hpp include remove the `eosiolib/` from the include in the cpp file.

**Comment by dunkan50** [comment]
hi, thank you for that...

it didn't throw an error at that point  ut 1st was the issue with the file directory,

```
clang-4.0: error: no such file or directory: 'eosio.bios.cpp'
clang-4.0: error: no input files

```
as handling that i am now having issues with the ```#include <eosio.bios/eosio.bios.hpp>``` in the **eosio.bios.cpp** file. the file is available I have tried a different system of referencing but nothing.

**Comment by mlawand** [comment]
@dunkan50 any update? have you been able to solve this issue?

**Comment by zmcNotafraid** [comment]
You need to run this command in ${EOSIO_SOURCE} directory, NOT IN "/build/program/cleos" directory.I solve it with this way. @dunkan50 @mlawand

**Comment by dunkan50** [comment]
@mlawand no yet been held up for some time,  but now I want to try the suggestion by @zmcNotafraid

**Comment by dunkan50** [comment]
@zmcNotafraid's method works but it doesn't make sense to me. How doe it work on the root directory?

```
cleos --wallet-port 8899 set contract eosio build/contracts/eosio.bios
```

it should be noted the above command is meant to be run the root directory.

@nsjames  @mlawand

**Comment by zmcNotafraid** [comment]
@dunkan50  You can read WIKI->Testnet Single Host Multinode->Start the Second Producer Node.
This command use to start additional nodes.

**Comment by stan14100** [comment]
@dunkan50  Can you tell me how you had handle these problems : 
clang-4.0: error: no such file or directory: 'eosio.bios.cpp'
clang-4.0: error: no input files
Thanks in advance

**Comment by eosbet-io** [comment]
Strange, my `eosio.bios.wast` file exists & I'm referencing it correctly using the full file path. However, `eosio.bios.cpp` does not exist, instead exist `eosio.bios.cpp.bc`

When I compile `eosiocpp -o eosio.bios.wast eosio.bios.cpp.bc` it gives some warnings but still seems to compile. The .wast file exists, and I can `cat` it fine.

I'm setting this up with Docker, maybe that's a problem?

**Comment by samkirton** [comment]
I'm also encountering this issue @eosbet-io, are you using a cleos alias referencing `docker-compose exec keosd`?
