### ISSUE TITLE
WASM injection damages wasm start function

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#2400]
Looks like the start function idx needs to be adjusted when we inject; otherwise wrong function is called (similar to the problems we had with `call_indirect`)

**Comment by spoonincode** [comment]
In binaryen runtime this actually seems to cause a hard crash 😳

**Comment by andriantolie** [comment]
Can we have ATC for this?

**Comment by larryk85** [comment]
ATC: Given a wast/wasm program with an explicitly defined start function, then injection no longer causes this to crash.  To force injection, either a block instruction is needed (checktime) or adding some f32/f64 instructions (softfloat).

**Comment by andriantolie** [comment]
Got it.
I noticed that wasm_tests/check_entry_behavior is already updated to include block instruction and it passes. So ATC passes
