### ISSUE TITLE
test chain generator

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#2404]
For at least issue #2390, we need a way to create chains of varying initial lengths. In some cases the chains need to be of a common source but we will need at least 3 source chains, two with the same genesis block but started by different bios producer instances, and another with a different genesis block. I'm not certain of the 3rd case.

Anyway, this variable length chain initializer could be built into nodeos as an extension to the hain controller, but I think it would be better as a separate utility, or maybe as a plugin module even.

Bonus idea - implement this as plugin, and allow it to accept source identifiers as some sort of URI format that could be local filesystem or network address, along with offset and count values, and now we have alternate synchronizer Dan mentioned the other day.  We could even throw in zlib based streaming compression. However integration with the existing p2p and chain controller code is left as an exercise for the reader.

**Comment by taokayan** [comment]
hey I've pushed a enhancement to txn_test_gen_plugin which allows you to create different initial lengths for different nodes, while maintaining the ability to sync with other nodes. Please see https://github.com/EOSIO/eos/pull/3151

config changes in config.ini:

# param startup-produce-blocks: number of extra blocks be built at initial stage, can be different on different nodes.
# param startup-sign-key: the key used to sign the extra initial blocks, or the bios private key, should be same on different nodes.
# txn_test_gen_plugin must be enabled.

startup-produce-blocks = 100
startup-sign-key = ["EOS8L8R3azSpkC2Go1Gj62qnq7EiWsGus8fMfrar7BqcxiFF8TpxR","5KFxAo6AHDzUPTtYjPet5FHQttC6VqmKpJ6cGbEj5sLsankoGuK"]
plugin = eosio::txn_test_gen_plugin

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner I am thinking this is OBE.  If I don't hear from you I will presume that is the case.

**Comment by brianjohnson5972** [comment]
No longer part of the plan.
