### ISSUE TITLE
eos Dawn3.0 install error

### ISSUE THREAD

**Issue by hljchz** [EOSIO/eos#2411]
Checking CMAKE installation.
	Installing CMAKE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7641k  100 7641k    0     0   494k      0  0:00:15  0:00:15 --:--:--  701k
ln: failed to create symbolic link ?.make/cmake-3.10.2?. File exists
---------------------------------------------
CMake 3.10.2, Copyright 2000-2017 Kitware, Inc. and Contributors
C compiler on this system is: cc  
---------------------------------------------
Error when bootstrapping CMake:
Cannot find a C++ compiler supporting C++11 on this system.
Please specify one using environment variable CXX.
See cmake_bootstrap.log for compilers attempted.
---------------------------------------------
Log of errors: /root/opt/cmake/Bootstrap.cmk/cmake_bootstrap.log
---------------------------------------------
	Error running bootstrap for CMAKE.
	Exiting now.

error log is below this,i was check the version of gcc is 4.8.I don't know what can i do.

**Comment by jgiszczak** [comment]
Please actually provide the error log, and describe your platform.

**Comment by andriantolie** [comment]
@hljchz Do you still have problem with latest version?

**Comment by halsaphi** [comment]
Out of date issue + no reply from reporter
