### ISSUE TITLE
Unable to run eosiocpp -o due to Boost error

### ISSUE THREAD

**Issue by tpmccallum** [EOSIO/eos#2415]
I am running the following command 
```
eosiocpp -o tp1/tp1.wasm tp1/tp1.cpp
```
and getting the following error
```
/usr/local/include/eosiolib/datastream.hpp:18:10: fatal error: 'boost/pfr.hpp' file not found
```
Background: All test on the installation have passed. In addition I have located the pfr.hpp file (using find) at /home/timothymccallum/eos_dawn_3/eos/externals/magic_get/include/boost/pfr.hpp

**Comment by tpmccallum** [comment]
Removed the /home/me/opt directory, re cloned the repo and re-ran the build.sh and I am now able to run the compiler without the boost error.

**Comment by Justin-ye** [comment]
how to re cloned?
