### ISSUE TITLE
When start node again under latest master branch

### ISSUE THREAD

**Issue by WildDylan** [EOSIO/eos#2418]
3179029ms thread-0   wallet_plugin.cpp:41          plugin_initialize    ] initializing wallet plugin
3179029ms thread-0   http_plugin.cpp:141           plugin_initialize    ] host: 127.0.0.1 port: 8888 
3179030ms thread-0   http_plugin.cpp:144           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
3179030ms thread-0   chain_plugin.cpp:99           plugin_initialize    ] initializing chain plugin
3179030ms thread-0   net_plugin.cpp:2631           plugin_initialize    ] Initialize net plugin
3179030ms thread-0   net_plugin.cpp:2647           plugin_initialize    ] Setting net_plugin logging level to info
3179030ms thread-0   net_plugin.cpp:2672           plugin_initialize    ] host: 0.0.0.0 port: 9876 
3179030ms thread-0   net_plugin.cpp:2748           plugin_initialize    ] my node_id is 83d3bd3076bc319b9665f6629ef19cf4e470c2aefa53cf4cadc565f9b3a03536
3179031ms thread-0   main.cpp:90                   main                 ] nodeos version 74a4c7a0
3179031ms thread-0   main.cpp:91                   main                 ] eosio root is /Users/root1/Library/Application Support
3179031ms thread-0   http_plugin.cpp:213           plugin_startup       ] start listening for http requests
3179031ms thread-0   wallet_api_plugin.cpp:70      plugin_startup       ] starting wallet_api_plugin
3179031ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/create
3179031ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/get_public_keys
3179031ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/import_key
3179031ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/list_keys
3179031ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/list_wallets
3179031ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/lock
3179031ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/lock_all
3179031ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/open
3179031ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/set_timeout
3179032ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/sign_transaction
3179032ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/unlock
3179032ms thread-0   block_log.cpp:120             open                 ] Log is nonempty
3179033ms thread-0   block_log.cpp:128             open                 ] Index is nonempty
3179058ms thread-0   chain_plugin.cpp:217          plugin_startup       ] 10 assert_exception: Assert Exception
head_block_num() == 0: last block ID does not match current chain state
    {"last_block->id":"00003db467309f318706127bab94cf42f31e9c857ef8704bff76da38dc949b14","head_block_num":15797}
    thread-0  chain_controller.cpp:1679 _spinup_fork_db
3179058ms thread-0   chain_plugin.cpp:217          plugin_startup       ] my->genesis_file.generic_string(): /Users/root1/Library/Application Support/eosio/nodeos/config/genesis.json 
3179060ms thread-0   main.cpp:95                   main                 ] 10 assert_exception: Assert Exception
head_block_num() == 0: last block ID does not match current chain state
    {"last_block->id":"00003db467309f318706127bab94cf42f31e9c857ef8704bff76da38dc949b14","head_block_num":15797}
    thread-0  chain_controller.cpp:1679 _spinup_fork_db
rethrow
    {"my->genesis_file.generic_string()":"/Users/root1/Library/Application Support/eosio/nodeos/config/genesis.json"}
    thread-0  chain_plugin.cpp:217 plugin_startup

**Comment by WildDylan** [comment]
how to resolve it .

**Comment by spoonincode** [comment]
> head_block_num() == 0: last block ID does not match current chain state

I've seen this when the DB is corrupted due to a crash or being improperly shutdown. May want to try with `--resync` to start anew.

**Comment by jgiszczak** [comment]
Shut down `nodeos` manually before shutting down the host OS.  Also avoid using `-9` in any kill command of `nodeos`.  `pkill nodeos` is normally sufficient and necessary for graceful shutdown.  The interrupt handler must be allowed to run to prevent corruption of the in-memory tables.
