### ISSUE TITLE
DAWN-495 ⁃ Design Chain to support Plugin writing without changing Chain library

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#242]
Need to be able to write plugins without making any modifications to the chain library when new plugins are added.  This actually referring to being able to add in-memory indices to the in-memory database, without having to edit eosio/chain/types.hpp's object_type enum.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

[~brian.johnson] is this fixed with Jonathan's CMake changes?

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

Jonathan's CMake change was to not have to edit eosiod's main.cpp to be able to add in a plugin (but still need to change the cmake entries for it), this has to do with the fact that we currently rely on an enum value to determine which index you are adding/retrieving/modifying.

**Comment by andriantolie** [comment]
@brianjohnson5972 is this issue still relevant?

**Comment by brianjohnson5972** [comment]
It is still relevant, if we want to be able to use the shared memory database to store data (like we did for history plugin).  But with the memory growth issues with history plugin, we may never want to bother to make any attempt to make it easier on a developer to do that.
@wanderingbort , any thoughts?

**Comment by brianjohnson5972** [comment]
Support for creating new tables in shared memory is not part of the plan.
