### ISSUE TITLE
logging SIGHUP doesn't reinitialize net_plugin's logger 

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#2432]
There are a couple of obvious ways to fix this:

* Make logging reinitaliztion be a plugin lifecycle action. When logging config is updated, call out to each plugin. This would give net_plugin an opportunity to get the new net_plugin_impl logger.
* Make net_plugin just get the net_plugin_impl logger on each log event. This is no worse than what `ilog()` etc already do (but with the 'default' logger in that case). One argument against this is that the net plugin hits its debug logger harder than the default logger is typically used.

I suppose another option is to drop HUP support.

**Comment by jgiszczak** [comment]
Completed.
