### ISSUE TITLE
nodeos fail to start in local testnet

### ISSUE THREAD

**Issue by Npizza** [EOSIO/eos#2436]
I followed the instractions from the local enviroment page and when run the:
`./nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::account_history_api_plugin 
`
I get this error:
`3124424ms thread-0   main.cpp:97                   main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
std::exception::what: bind: Address already in use
`

what I am doing wrong?

**Comment by jgiszczak** [comment]
`nodeos` is already running.  First `pkill nodeos` before launching another one with the same listen port number.

**Comment by Npizza** [comment]
Thank you.It worked

**Comment by CarGod** [comment]
Thank you @jgiszczak
