### ISSUE TITLE
Deleting permission should be possible with same authorization requirements as updating the permission

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2437]
Right now the requirements we have on `deleteauth` mean that if a minimum permission is not set for `deleteauth`, only active and owner permissions of an account can delete a permission from their permission tree.

But a permission can be modified with `updateauth` with an authorization that is satisfied just by that permission, which is more permissive than the current implementation of `deleteauth`. Since a permission can be modified to be unsatisfiable, it really does not make sense to be able to update a permission but not be allowed to delete it (assuming it has no children permission and there are no permission links to it).

So, the authorization requirements of `deleteauth` should be modified to be similar to that `updateauth` while accounting for the scenarios where they really should be different (such as the restrictions on `deleteauth` due to it having children permissions or a permission link to it).

**Comment by taokayan** [comment]
test cases for deleteauth added in https://github.com/EOSIO/eos/pull/2498
