### ISSUE TITLE
Disallow setting minimum permission for updateauth, deleteauth, linkauth, unlinkauth, and canceldelay native actions

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2438]
These 5 native actions are treated in a special way when it comes to check authorization. It does not make sense to set a minimum permission explicitly for these 5 native action since check authorization will compute a minimum permission that needs to be satisfied based on the contents of these actions and possibly the state of the permission tree for the relevant account.

Therefore, linkauth should not allow any user to set a minimum permission for any of these 5 actions.

ATC: pushing a linkauth action for some account that tries to map some minimum permission to any of these 5 native actions fails.

**Comment by taokayan** [comment]
add unit test cases (https://github.com/EOSIO/eos/pull/2468) and verified.

**Comment by piecesnbits** [comment]
with the current implementation it is not possible to prevent using these actions for certain permissions. for example bps claim their rewards with a special permission but if the key is compromised the acation can be unlinked. imo it is very useful to setup a permission (with certain linkauth) from which the private key can be published. there are many usecases for this.
