### ISSUE TITLE
On new block, report transactions in block/pending transactions

### ISSUE THREAD

**Issue by nathanhourt** [EOSIO/eos#244]
Update print statements when a new block is applied/created to list the number of transactions in the block and the number of transactions still pending, and also the total time required to apply the block

**Comment by nathanhourt** [comment]
Log: Block number, timestamp, producer, duration to apply, transaction count, pending transaction count

**Comment by MatthewPappas** [comment]
All done.

**Comment by nathanhourt** [comment]
@MatthewPappas Which commit(s)/preq resolves this issue?

**Comment by MatthewPappas** [comment]
branch log-244  it is ready for merging.
Tried command:
git log --first-parent log-244     
And the first few seem to be what you are looking for:
commit 593625fe159ca67ba1ad9b63bc3403f1e92459d2
commit fc4f01356dac603009ee49456ef999a3e8a8731a
commit 3ba5b73710788fdbf26619429a3c8d595a618780
commit 604bc62106c23fb0d322882297f008e144cfcf7f
commit 8abcadfac43cc778129d299acf7070ae550c2b6e
commit 0e9ddd847e61c6e59c8430a3ede38baf2f96755e
commit e63f82721d1b957f98988704be6333e373cc16b4

Put a couple items in and took them out.
Ultimatly just the change around _push_block function in chain_controller.cpp are going in.
I might have cleaned up windows line feed in the process, do let me know 
if by doing that I made anything difficult.

**Comment by MatthewPappas** [comment]
Ah, this is a nice command:
git diff master...log-244

**Comment by MatthewPappas** [comment]
Forgot to do tab -> space conversion on the source file. Next time.

**Comment by nathanhourt** [comment]
Ref #251

**Comment by MatthewPappas** [comment]
Yes
