### ISSUE TITLE
will EOS support brain key?

### ISSUE THREAD

**Issue by crazybits** [EOSIO/eos#2442]
as subject, will EOS support brain key? just like BTS,ETH, the private key could be generated from the random words of specified dictionary, seems currently, the private key is generated from random seed.

**Comment by halsaphi** [comment]
This is not directly built into the EOSIO platform, nor is it currently in our plans.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
