### ISSUE TITLE
cleos get transaction failed.

### ISSUE THREAD

**Issue by basakkang** [EOSIO/eos#2443]
when I called a transaction with transaction_id in block->regions->transactions, i failed with this.

1216318ms thread-0   main.cpp:1158                 main                 ] Failed with error: unspecified (0)
Transaction with ID f6004f07377922a3e50ec09f203799caf62204784b75660154dedc20d8681dc5 was indexed as being in block ID 00161f68353f72ec980c1b926601e1cf60d6a71805d0a54fea8edc92146e9280, but was not found in that block

**Comment by andriantolie** [comment]
@basakkang do you still have problem with the latest version of code?

**Comment by andriantolie** [comment]
Region does not exist anymore and the block structure has been simplified. Please ensure you have history_api_plugin enabled, replay the blockchain (only if the transaction is added before history_api_plugin is enabled) and try again. If you still encounter the issue, please reopen this
