### ISSUE TITLE
nodeos result in "unable to find last irreversible block to write" error

### ISSUE THREAD

**Issue by vicraft18** [EOSIO/eos#2449]
![eos_issue](https://user-images.githubusercontent.com/34088375/38861807-01501502-4266-11e8-9b66-2b77d5aeb541.png)
The error is throw by chain_controller.cpp line 1847
   // Write newly irreversible blocks to disk. First, get the number of the last block on disk...
   auto old_last_irreversible_block = _block_log.head();
   unsigned last_block_on_disk = 0;
   // If this is null, there are no blocks on disk, so the zero is correct
   if (old_last_irreversible_block)
      last_block_on_disk = old_last_irreversible_block->block_num();

   if (last_block_on_disk < new_last_irreversible_block_num) {
      for (auto block_to_write = last_block_on_disk + 1;
           block_to_write <= new_last_irreversible_block_num;
           ++block_to_write) {
         auto block = fetch_block_by_number(block_to_write);
         FC_ASSERT( block, "unable to find last irreversible block to write" );
         _block_log.append(*block);
         applied_irreversible_block(*block);
      }
   }

**Comment by DenisCarriere** [comment]
![image](https://user-images.githubusercontent.com/550895/38998965-b6ccffc2-43be-11e8-8b10-4cf21d0e234a.png)

Same issue using the `dawn-v3.0.0` tag

This issue seems to have been caused when an account executes the `setprods` function after the `eosio.system` has already been established (post-BIOS step).

**Comment by andriantolie** [comment]
@vicraft18 do you have the same problem with the latest version?

**Comment by andriantolie** [comment]
I checked this issue on v1.1, executing `setprods` after eosio.system is established doesn't reproducer this issue anymore. Since chain controller has been refactored a lot for v1.0.0, I guess this issue is already obsolete. Please reopen if you still see the same problem
