### ISSUE TITLE
Clearing/Resetting Local Blockchain

### ISSUE THREAD

**Issue by glemmaPaul** [EOSIO/eos#2451]
Hi all,

As most of us I'm new to programming with EOS and have done some improper actions on the wallet/accounts side and would like to redo my testing.

I've been looking through the documentation and was not able to find any info on how to reset or clear the blockchain that is run through `nodeos`. Tracing back in the logs I've found out most data is (Mac) `/Users/pauloostenrijk/Library/Application Support/eosio/nodeos/data`, by clearing this I do get the notion I've just created a new blockchain.

After that I try to import the `eosio` account, but it then notes that this is already included.

My question is if there is any instructions on completely clearing out the blockchain and their wallets/accounts? I'm definitely willing to create a PR to create these instructions on the Wiki/Documentation. It would be good to have these lined out, thoughts?

Thanks in advance!

**Comment by schabluk** [comment]
bump. I've deleted files from data/ and $user/eosio-wallet folder, but I can still query my keys.

**Comment by stanishev** [comment]
To be sure that you're looking at the correct wallets directory do: 

`cleos wallet open -n boguswalletname` 

and you should see an error that gives you the full path of where keosd tried to find that wallet file. 

Then delete that directory or whichever individual wallet file you want to get rid of.

No opinion re putting this in separate docs.

**Comment by andriantolie** [comment]
Yes, deleting the data folder or using `--delete` option should delete the blockchain. When you said importing`eosio` account, do you actually mean importing `eosio private key` to the wallet? You will need to delete your wallet too if you want to do it. Your wallet files should be found inside ~/eosio-wallet folder

**Comment by andriantolie** [comment]
Please let me know if the problem still persists!
