### ISSUE TITLE
Investigate implementation of begin in multi_index for fixed_key secondary key types

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2461]
`begin()` uses a `lower_bound` with the smallest possible value of the secondary key type. To get that lowest value, we are currently using `std::numeric_limits<secondary_key_type>::lowest()`. Specializations are defined for the arithmetic secondary key types that we support (`uint64_t`, `uint128_t`, `double`, `long double`), but this seems like it would be a problem for other supported non-arithmetic secondary key types such as `key256` (and later `key512`).

This current implementation is very likely buggy. We should verify that there is in fact a bug by trying to trigger it using a test that uses `begin()` on a `key256` secondary index. Whether or not there is a bug, a better implementation of getting the lowest value of our supported secondary key types is needed that doesn't rely on defining a specialization for `numeric_limits` on non-arithmetic types.

**Comment by arhag** [comment]
Actually, the current implementation was not buggy because apparently libc++ has a default implementation of `numeric_limits` that, if not specialized, will return the default constructor of the type when `lowest()` is called, which is exactly the behavior we desire. 

Nevertheless, relying on that behavior can potentially be buggy in the future. So, I will be changing `multi_index` to use a specific traits class `secondary_key_traits` that has a static member function `lowest()` which will give the the desired lowest value. The implementation will just use `lowest()` from `numeric_limits` for the arithmetic types, but for other types, such as `key256` and `key512`, a specialization will explicitly be provided which returns the appropriate value.

**Comment by andriantolie** [comment]
PR2494 that is connected to this issue is already merged. I'm closing this issue
