### ISSUE TITLE
unsuitable description in help file for command cleos 

### ISSUE THREAD

**Issue by woshidama323** [EOSIO/eos#2466]
hi,  
"contract TEXT               The contract that operates the currency"
This description confuse me, and i would use contract name rather than account name to get the currency balance. actually , the account name is right, am i right?

MacBook:eos easylend$ cleos get currency balance eosio.token whytest2
MacBook:eos easylend$ cleos get currency balance contracttest whytest2
75.0000 KAO
 
MacBook:eos easylend$ cleos get currency balance contracttest
ERROR: RequiredError: account
Retrieve the balance of an account for a given currency
Usage: cleos get currency balance contract account [symbol]

Positionals:
  contract TEXT               The **_contract_** that operates the currency
  account TEXT                The account to query balances for
  symbol TEXT                 The symbol for the currency if the contract operates multiple currencies

**Comment by andriantolie** [comment]
The contract referred above is referred to the account that hosts the eosio.token contract
