### ISSUE TITLE
The error about when accounts were created.

### ISSUE THREAD

**Issue by JEONG-JAE-HAN** [EOSIO/eos#2469]
Dear all.

Hello. I have encountered the critical error when I tried in order to create the new account.

The environment of my system is written as below.

1. Base of EOS system : dawn v3.0.0
2. The last adapted commit number : master (#2385)
(https://github.com/EOSIO/eos/commit/b847e32d222b6c3c1a05f45dd6c92d3f81f6c99e)
This commit is about account creating.

I have obey the rule in order to create a account as the guide in Github, however I have failed and I have got the mysterious log as below.

Plus log capture files are attached.

Could you please help me in order to create account?

Best regards.

JeongJae Han.

Log attached.
---------------------------------------------------------------------------------------------------------------
```
**shin@shin-home:~/eos/build/programs/cleos$ ./cleos create account eosio currency EOS7gMjsk6PM1bdk5DKFZrmeM1YnNhTPB9zJaV9grYXX2WT7ugjYW EOS625NRWueuWpxCctVEqXMzKEqwaoftxCX6FGA8sXdaaGnARcWo5**

executed transaction: 240d13184a284883c7efc7bcb119033f7543b7f3d68e5f17194985351d6cbcc3  352 bytes  102400 cycles
#eosio <= eosio::newaccount            {"creator":"eosio","name":"currency","owner":{"threshold":1,"keys":[{"key":"EOS7gMjsk6PM1bdk5DKFZrme...


shin@shin-home:~/eos/build/programs/cleos$ ./cleos get account currency
{
  "account_name": "currency",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS625NRWueuWpxCctVEqXMzKEqwaoftxCX6FGA8sXdaaGnARcWo5",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS7gMjsk6PM1bdk5DKFZrmeM1YnNhTPB9zJaV9grYXX2WT7ugjYW",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}

```
---------------------------------------------------------------------------------------------------------------

![screenshot from 2018-04-18 17-15-03](https://user-images.githubusercontent.com/25314532/38921328-75cd58a2-4330-11e8-8f4f-f2c4c20bf330.png)
![screenshot from 2018-04-18 17-15-21](https://user-images.githubusercontent.com/25314532/38921330-75fe218a-4330-11e8-9d1d-27a1c15a782a.png)

**Comment by JGShin** [comment]
same issue

**Comment by bonsoo-koo** [comment]
I have the same problem.

**Comment by sky9743** [comment]
Try again after set contract eosio.bios
