### ISSUE TITLE
Contract API action with no parameters fails.

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2474]
# Description

The EOSIOLib dispatcher does not properly handle api actions with no parameters.  It will fail trying call this:

https://github.com/EOSIO/eos/blob/5e47cbd0cabebf19d83a5d1746e1a3cb91c2b824/contracts/eosiolib/dispatcher.hpp#L47

because the serialized size is 0

Relayed from a legitimate bug report received through another channel:

```
I'm trying to see if there's a way to push action to a parameterless method.

// Contract 
class tester : public contract { 
public: 
using contract::contract; 
tester( name self ) : contract(self){} 
//@abi action 
void test(){ 
print("Test"); 
} 
}; 
EOSIO_ABI( tester, (test))

// From Generated Abi 
"types": [], 
"structs": [{ 
"name": "test", 
"base": "", 
"fields": [] 
} 
], 
"actions": [{ 
"name": "test", 
"type": "test", 
"ricardian_contract": "" 
} 
],

// Commands tried 
cleos push action tester tester '[]' -p eosio 
cleos push action tester tester '{}' -p eosio 
cleos push action tester tester '""' -p eosio

All three of those commands returns 
Error 3030000: transaction validation exception 
Ensure that your transaction satisfy the contract's constraint! 
Error Details: 
size > 0:
```

# Acceptance Test Criteria

- [x] test cases that prove a payloadless action properly executes in the EOSIO_ABI paradigm

**Comment by taokayan** [comment]
Test suite "payloadless_tests" has passed with:
    1 test case out of 1 passed
    2 assertions out of 2 passed

    Test case "payloadless_tests/test_doit" has passed with:
      2 assertions out of 2 passed
