### ISSUE TITLE
Testnet Single Host Multinode example problem

### ISSUE THREAD

**Issue by coinmini** [EOSIO/eos#2477]
node1 start successfully, 
when node2 start, it showed errors as follows 

$ cleos --wallet-port 8899  wallet create
Creating wallet: default
Save password to use in the future to unlock this wallet.
Without password imported keys will not be retrievable.
"PW5J9S2dqEukmpCBZg5Vb9WmAVYqwuJSop5785pQQXwkFRzd7fefo"

# bolin @ localhost in ~/documents/eos on git:master x [21:33:02]
$ cleos --wallet-port 8899 set contract eosio build/contracts/eosio.bios
Reading WAST/WASM from build/contracts/eosio.bios/eosio.bios.wast...
Assembling WASM...
Publishing contract...
executed transaction: 1d27ae4e1f109de4d6b28d893c4710d1aee86c783f58bea83a268118284fab9c  3280 bytes  2200576 cycles
#         eosio <= eosio::setcode               {"account":"eosio","vmtype":0,"vmversion":0,"code":"0061736d0100000001581060037f7e7f0060057f7e7e7e7e...
#         eosio <= eosio::setabi                {"account":"eosio","abi":{"types":[],"structs":[{"name":"set_account_limits","base":"","fields":[{"n...

# bolin @ localhost in ~/documents/eos on git:master x [21:35:07]
$ cleos create key
Private key: 5KUAwdbCnqMXyP4sm5WmAWhAiDxJmSCqrCevCxkRDx8sRFL9Ej5
Public key: EOS7FKRc287CUF5WDTGSKm9vu9XHK8THvJdB2B1VspmZbDhEdRUYB

# bolin @ localhost in ~/documents/eos on git:master x [21:35:58]
$ cleos --wallet-port 8899 wallet import 5JgbL2ZnoEAhTudReWH1RnMuQS6DBeLZt4ucV6t8aymVEuYg7sr

imported private key for: EOS6hMjoWRF2L8x9YpeqtUEcsDKAyxSuM1APicxgRU1E3oyV5sDEg

# bolin @ localhost in ~/documents/eos on git:master x [21:36:44]
$ cleos --wallet-port 8899 create account eosio inita EOS6hMjoWRF2L8x9YpeqtUEcsDKAyxSuM1APicxgRU1E3oyV5sDEg EOS6hMjoWRF2L8x9YpeqtUEcsDKAyxSuM1APicxgRU1E3oyV5sDEg

executed transaction: bce9cfab294910c66dcd1a8f49c86954f423667b6832b039040dea0133d6f674  352 bytes  102400 cycles
#         eosio <= eosio::newaccount            {"creator":"eosio","name":"inita","owner":{"threshold":1,"keys":[{"key":"EOS6hMjoWRF2L8x9YpeqtUEcsDK...

# bolin @ localhost in ~/documents/eos on git:master x [21:36:59]
$ nodeos --producer-name inita --plugin eosio::chain_api_plugin --plugin eosio::net_api_plugin --http-server-address 127.0.0.1:8889 --p2p-listen-endpoint 127.0.0.1:9877 --p2p-peer-address 127.0.0.1:9876 --config-dir node2 --data-dir node2 --private-key [\"EOS6hMjoWRF2L8x9YpeqtUEcsDKAyxSuM1APicxgRU1E3oyV5sDEg\",\"5JgbL2ZnoEAhTudReWH1RnMuQS6DBeLZt4ucV6t8aymVEuYg7sr\"]

2241119ms thread-0   chain_plugin.cpp:99           plugin_initialize    ] initializing chain plugin
2241119ms thread-0   http_plugin.cpp:141           plugin_initialize    ] host: 127.0.0.1 port: 8889
2241119ms thread-0   http_plugin.cpp:144           plugin_initialize    ] configured http to listen on 127.0.0.1:8889
2241119ms thread-0   net_plugin.cpp:2667           plugin_initialize    ] Initialize net plugin
2241119ms thread-0   net_plugin.cpp:2690           plugin_initialize    ] host: 127.0.0.1 port: 9877
2241119ms thread-0   net_plugin.cpp:2766           plugin_initialize    ] my node_id is 347c0ca3784f1c1a315a5e00b4e4a3743236f208123447660f9fc377db87bb35
2241120ms thread-0   main.cpp:90                   main                 ] nodeos version aeb52052
2241120ms thread-0   main.cpp:91                   main                 ] eosio root is /Users/bolin/Library/Application Support
2241120ms thread-0   block_log.cpp:120             open                 ] Log is nonempty
2241120ms thread-0   block_log.cpp:128             open                 ] Index is nonempty
2241136ms thread-0   chain_plugin.cpp:208          plugin_startup       ] starting chain in read/write mode
2241136ms thread-0   chain_plugin.cpp:213          plugin_startup       ] Blockchain started; head block is #757, genesis timestamp is 2018-03-01T12:00:00.000
2241137ms thread-0   http_plugin.cpp:213           plugin_startup       ] start listening for http requests
2241137ms thread-0   chain_api_plugin.cpp:62       plugin_startup       ] starting chain_api_plugin
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/abi_bin_to_json
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/abi_json_to_bin
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_account
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_block
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_code
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_currency_balance
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_currency_stats
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_info
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_required_keys
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_table_rows
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/push_block
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/push_transaction
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/push_transactions
2241137ms thread-0   net_plugin.cpp:2778           plugin_startup       ] starting listener, max clients is 25
2241137ms thread-0   net_plugin.cpp:621            connection           ] created connection to 127.0.0.1:9876
2241137ms thread-0   net_plugin.cpp:1738           connect              ] host: 127.0.0.1 port: 9876
2241137ms thread-0   net_api_plugin.cpp:69         plugin_startup       ] starting net_api_plugin
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/net/connect
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/net/connections
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/net/disconnect
2241137ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/net/status
2241137ms thread-0   producer_plugin.cpp:161       plugin_startup       ] producer plugin:  plugin_startup() begin
2241137ms thread-0   producer_plugin.cpp:166       plugin_startup       ] Launching block production for 1 producers.
2241137ms thread-0   producer_plugin.cpp:176       plugin_startup       ] producer plugin:  plugin_startup() end
2241138ms thread-0   net_plugin.cpp:2035           handle_message       ] Peer chain is forked
2241138ms thread-0   net_plugin.cpp:986            operator()           ] sent a go away message: chain is forked, closing connection to 127.0.0.1:9876
2241138ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from 127.0.0.1:9876: Operation canceled
2241503ms thread-0   producer_plugin.cpp:243       block_production_loo ] Not producing block because production is disabled until we receive a recent block (see: --enable-stale-production)
2271140ms thread-0   net_plugin.cpp:1738           connect              ] host: 127.0.0.1 port: 9876
2271141ms thread-0   net_plugin.cpp:2035           handle_message       ] Peer chain is forked
2271141ms thread-0   net_plugin.cpp:986            operator()           ] sent a go away message: chain is forked, closing connection to 127.0.0.1:9876
2271141ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from 127.0.0.1:9876: Operation canceled
2301138ms thread-0   net_plugin.cpp:1738           connect              ] host: 127.0.0.1 port: 9876
2301142ms thread-0   net_plugin.cpp:2035           handle_message       ] Peer chain is forked
2301142ms thread-0   net_plugin.cpp:986            operator()           ] sent a go away message: chain is forked, closing connection to 127.0.0.1:9876
2301142ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from 127.0.0.1:9876: Operation canceled
2331142ms thread-0   net_plugin.cpp:1738           connect              ] host: 127.0.0.1 port: 9876
2331145ms thread-0   net_plugin.cpp:2035           handle_message       ] Peer chain is forked
2331145ms thread-0   net_plugin.cpp:986            operator()           ] sent a go away message: chain is forked, closing connection to 127.0.0.1:9876
2331146ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from 127.0.0.1:9876: Operation canceled
2361146ms thread-0   net_plugin.cpp:1738           connect              ] host: 127.0.0.1 port: 9876
2361147ms thread-0   net_plugin.cpp:2035           handle_message       ] Peer chain is forked
2361147ms thread-0   net_plugin.cpp:986            operator()           ] sent a go away message: chain is forked, closing connection to 127.0.0.1:9876
2361147ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from 127.0.0.1:9876: Operation canceled

------------------------------------------------------------------------------------------------------
first node become as follows:

eosio generated block 5a6a6ca2... #506 @ 2018-04-18T13:38:18.500 with 0 trxs, lib: 505
eosio generated block f8509268... #507 @ 2018-04-18T13:38:19.000 with 0 trxs, lib: 506
eosio generated block eb82e7c8... #508 @ 2018-04-18T13:38:19.500 with 0 trxs, lib: 507
eosio generated block 335f4748... #509 @ 2018-04-18T13:38:20.000 with 0 trxs, lib: 508
eosio generated block e5150dd4... #510 @ 2018-04-18T13:38:20.500 with 0 trxs, lib: 509
eosio generated block 2932119a... #511 @ 2018-04-18T13:38:21.000 with 0 trxs, lib: 510
2301139ms thread-0   net_plugin.cpp:644            connection           ] accepted network connection
2301142ms thread-0   net_plugin.cpp:2053           handle_message       ] received a go away message from 127.0.0.1:9877 - 347c0ca, reason = chain is forked
2301142ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from connecting client: Bad file descriptor
eosio generated block 7e53f783... #512 @ 2018-04-18T13:38:21.500 with 0 trxs, lib: 511
eosio generated block b2e0e22b... #513 @ 2018-04-18T13:38:22.000 with 0 trxs, lib: 512
eosio generated block d81ce17b... #514 @ 2018-04-18T13:38:22.500 with 0 trxs, lib: 513
eosio generated block 77165a9d... #515 @ 2018-04-18T13:38:23.000 with 0 trxs, lib: 514
2303050ms thread-0   abi_serializer.hpp:349        extract              ] vo: {"signatures":["EOSKese58dTKfgV2FkSWYb9jusuu5pELY7oRnnRyDrooYSpLGQuYAh78CE2uAA1CqG4e78S3pnQvzEC1xvTPzUUcBseXjSuAK"],"compression":"none","packed_context_free_data":"","packed_trx":"6d4ad75a000002029995403000000000010000000000ea305500000038d15bb3c2010000000000ea305500000000a8ed32322f0100000001000000000093dd740002ee1e0301c0189aaa0eca06e0fe65b2f7a13de8b514fb87639e1c8fdc92359f7e"}
eosio generated block c76a56f6... #516 @ 2018-04-18T13:38:23.500 with 1 trxs, lib: 515
eosio generated block b0e292a0... #517 @ 2018-04-18T13:38:24.000 with 0 trxs, lib: 516
eosio generated block b3c641ee... #518 @ 2018-04-18T13:38:24.500 with 0 trxs, lib: 517
2305004ms thread-0   producer_plugin.cpp:252       block_production_loo ] Not producing block because I don't have the private key for EOS6hMjoWRF2L8x9YpeqtUEcsDKAyxSuM1APicxgRU1E3oyV5sDEg
2315470ms thread-0   net_plugin.cpp:650            ~connection          ] released connection from client
2331142ms thread-0   net_plugin.cpp:644            connection           ] accepted network connection
2331146ms thread-0   net_plugin.cpp:2053           handle_message       ] received a go away message from 127.0.0.1:9877 - 347c0ca, reason = chain is forked
2331146ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from connecting client: Bad file descriptor
2345472ms thread-0   net_plugin.cpp:650            ~connection          ] released connection from client
2301139ms thread-0   net_plugin.cpp:644            connection           ] accepted network connection
2301142ms thread-0   net_plugin.cpp:2053           handle_message       ] received a go away message from 127.0.0.1:9877 - 347c0ca, reason = chain is forked
2301142ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from connecting client: Bad file descriptor
eosio generated block 7e53f783... #512 @ 2018-04-18T13:38:21.500 with 0 trxs, lib: 511
eosio generated block b2e0e22b... #513 @ 2018-04-18T13:38:22.000 with 0 trxs, lib: 512
eosio generated block d81ce17b... #514 @ 2018-04-18T13:38:22.500 with 0 trxs, lib: 513
eosio generated block 77165a9d... #515 @ 2018-04-18T13:38:23.000 with 0 trxs, lib: 514
2303050ms thread-0   abi_serializer.hpp:349        extract              ] vo: {"signatures":["EOSKese58dTKfgV2FkSWYb9jusuu5pELY7oRnnRyDrooYSpLGQuYAh78CE2uAA1CqG42361147ms thread-0   net_plugin.cpp:644            connection           ] accepted network connectionad75a000
2361147ms thread-0   net_plugin.cpp:2053           handle_message       ] received a go away message from 127.0.0.1:9877 - 347c0ca, reason = chain is forked
2361147ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from connecting client: Bad file descriptor
2375476ms thread-0   net_plugin.cpp:650            ~connection          ] released connection from client
2391145ms thread-0   net_plugin.cpp:644            connection           ] accepted network connection
2391146ms thread-0   net_plugin.cpp:2053           handle_message       ] received a go away message from 127.0.0.1:9877 - 347c0ca, reason = chain is forked
2391146ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from connecting client: Bad file descriptor
2405477ms thread-0   net_plugin.cpp:650            ~connection          ] released connection from client
2421146ms thread-0   net_plugin.cpp:644            connection           ] accepted network connection
2421147ms thread-0   net_plugin.cpp:2053           handle_message       ] received a go away message from 127.0.0.1:9877 - 347c0ca, reason = chain is forked
2421147ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from connecting client: Bad file descriptor
2435477ms thread-0   net_plugin.cpp:650            ~connection          ] released connection from client
2451149ms thread-0   net_plugin.cpp:644            connection           ] accepted network connection
2451150ms thread-0   net_plugin.cpp:2053           handle_message       ] received a go away message from 127.0.0.1:9877 - 347c0ca, reason = chain is forked
2451150ms thread-0   net_plugin.cpp:1870           operator()           ] Error reading message from connecting client: Bad file descriptor
2465475ms thread-0   net_plugin.cpp:650            ~connection          ] released connection from client

**Comment by Duffyxx** [comment]
I have got the same problem , have you fixed it ?
