### ISSUE TITLE
set contract error detail is_type(t.second)!!

### ISSUE THREAD

**Issue by Lomect** [EOSIO/eos#2483]
i create a contract and it's error when i set it :
Reading WAST...
Assembling WASM...
Publishing contract...
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
is_type(t.second):

**Comment by elmato** [comment]
Can you post a link to the source code?

**Comment by Lomect** [comment]
i use the string type, and i think it's the error:
```
      private:
        // @abi table
         struct test {
            account_name    user_name;
            string         letter;         

            uint64_t primary_key() const { return user_name; }
         };
```

**Comment by elmato** [comment]
Please, link to the full source code including the ABI file.

**Comment by brianjohnson5972** [comment]
This issue has been silent for a while, so I am closing.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
