### ISSUE TITLE
Compiler-rt support for wasm

### ISSUE THREAD

**Issue by larryk85** [EOSIO/eos#2503]
The compiler-builtins interface was first created before libc was introduced, and some other limitations of the time disallowed us to easily use compiler-rt.  But, now that libc is included and most of the main hurdles of compilation, "linking" and other facets of utilizing compiler-rt have been resolved, we need to supplant compiler-builtins interface with this.

**Comment by arhag** [comment]
See comment [here](https://github.com/EOSIO/eos/issues/2487#issuecomment-429361960) for why I am closing this issue.
