### ISSUE TITLE
Make mongodb install/run optional to eosio_build.sh

### ISSUE THREAD

**Issue by heifner** [EOSIO/eos#2511]
`mongo_db_plugin` build and install of mongodb, mongo c/cpp drivers is part of the `eosio_build.sh` script. Since these are optional and many will have no need to install/build these components. Make their inclusion in the `eosio_build.sh` optional.

**Comment by trungtt1981** [comment]
@heifner 
See this https://github.com/EOSIO/eos/issues/3030

**Comment by heifner** [comment]
At this point would like to change the mongo_db_plugin into a filler based off the state_history_plugin at which time it will be in its own repo.
