### ISSUE TITLE
Manually Building EOSIO on centos 7 failed

### ISSUE THREAD

**Issue by gaoyuantan** [EOSIO/eos#2515]
I manual install the dependencies on centos 7 successfully. But it is failed when build EOS and I get the following error message.

`[kingnet@bctestnode3 build]$ cmake -DBINARYEN_BIN=/opt/tangy/eos.io/binaryen/bin -DWASM_ROOT=/opt/tangy/eos.io/wasm-compiler/llvm -DOPENSSL                                                                                                  _ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DBUILD_MONGO_DB_PLUGIN=true ..
-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
-- Configuring Eos on Linux
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using WASM clang => /opt/tangy/eos.io/wasm-compiler/llvm/bin/clang
-- Using WASM llc => /opt/tangy/eos.io/wasm-compiler/llvm/bin/llc
-- Using WASM llvm-link => /opt/tangy/eos.io/wasm-compiler/llvm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Configuring fc to build on Unix/Apple
-- zlib found
-- bzip2 found
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   unit_test_framework
--   locale
-- Configuring ChainBase on Linux
-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   program_options
--   unit_test_framework
--   locale
-- Configuring AppBase on Linux
**CMake Error at plugins/mongo_db_plugin/CMakeLists.txt:22 (find_package):
  By not providing "Findlibbsoncxx-static.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "libbsoncxx-static", but CMake did not find one.

  Could not find a package configuration file provided by "libbsoncxx-static"
  with any of the following names:

    libbsoncxx-staticConfig.cmake
    libbsoncxx-static-config.cmake

  Add the installation prefix of "libbsoncxx-static" to CMAKE_PREFIX_PATH or
  set "libbsoncxx-static_DIR" to a directory containing one of the above
  files.  If "libbsoncxx-static" provides a separate development package or
  SDK, be sure it has been installed.**

-- Configuring incomplete, errors occurred!
See also "/opt/tangy/eos.io/eos/build/CMakeFiles/CMakeOutput.log".
See also "/opt/tangy/eos.io/eos/build/CMakeFiles/CMakeError.log".
`
After that, I and libbsoncxx-static_DIR. But I get another error mesage.

`[kingnet@bctestnode3 build]$ cmake -DBINARYEN_BIN=/opt/tangy/eos.io/binaryen/bin -DWASM_ROOT=/opt/tangy/eos.io/wasm-compiler/llvm -DOPENSSL                                                                                                  _ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DBUILD_MONGO_DB_PLUGIN=true -Dlibbsoncxx-static_DIR=/opt/t                                                                                                  angy/eos.io/mongo-c-driver-1.9.3/mongo-cxx-driver/build/src/bsoncxx ..
-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
-- Configuring Eos on Linux
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using WASM clang => /opt/tangy/eos.io/wasm-compiler/llvm/bin/clang
-- Using WASM llc => /opt/tangy/eos.io/wasm-compiler/llvm/bin/llc
-- Using WASM llvm-link => /opt/tangy/eos.io/wasm-compiler/llvm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Configuring fc to build on Unix/Apple
-- zlib found
-- bzip2 found
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   unit_test_framework
--   locale
-- Configuring ChainBase on Linux
-- Using custom FindBoost.cmake
-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   program_options
--   unit_test_framework
--   locale
-- Configuring AppBase on Linux
**CMake Error at /opt/tangy/eos.io/mongo-c-driver-1.9.3/mongo-cxx-driver/build/src/bsoncxx/libbsoncxx-static-config.cmake:36 (message):
  File or directory
  /opt/tangy/eos.io/mongo-c-driver-1.9.3/mongo-cxx-driver/include/bsoncxx/v_noabi
  referenced by variable LIBBSONCXX_STATIC_INCLUDE_DIRS does not exist !
Call Stack (most recent call first):
  /opt/tangy/eos.io/mongo-c-driver-1.9.3/mongo-cxx-driver/build/src/bsoncxx/libbsoncxx-static-config.cmake:52 (set_and_check)
  plugins/mongo_db_plugin/CMakeLists.txt:22 (find_package)**

-- Configuring incomplete, errors occurred!
See also "/opt/tangy/eos.io/eos/build/CMakeFiles/CMakeOutput.log".
See also "/opt/tangy/eos.io/eos/build/CMakeFiles/CMakeError.log".
`

**Comment by YunZhuangCai** [comment]
check the openssl root path in the  eosio_build.sh file.

**Comment by gaoyuantan** [comment]
@YunZhuangCai 
I checked the openssl root path, and change  "-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl" to " -DOPENSSL _ROOT_DIR=/usr/include/openssl".
But it is also failed.

**Comment by YunZhuangCai** [comment]
Are you check the DOPENSSL_LIBRARIES path?  Delete the build contents and rebuild

**Comment by gaoyuantan** [comment]
@YunZhuangCai 
I checked the DOPENSSL_LIBRARIES. There is no DOPENSSL_LIBRARIES in eosio_build.sh. I have removed DOPENSSL_LIBRARIES from build command. But it it also failed.

I did not delete the build content. How to delete the build contents?

**Comment by gaoyuantan** [comment]
@YunZhuangCai 
I delete the build contents and rebuild again.  It is also failed.

**Comment by gaoyuantan** [comment]
god, I know the reason.
There should be a command "sudo make install" after the commands of "Install mongo-cxx-driver (release/stable):"

because mongo-cxx-driver is not installed if current operation.

**Comment by gaoyuantan** [comment]
Manual installation of the dependencies miss one command.
