### ISSUE TITLE
EOS RPC abi_json_to_bin get none return

### ISSUE THREAD

**Issue by YunZhuangCai** [EOSIO/eos#2516]
use the following command to serialize json to binary hex
curl  http://127.0.0.1:8888/v1/chain/abi_json_to_bin -X POST -d '{"code":"token", "action":"transfer", "fields":{"from":"user","to":"tester", "quantity":"1.0000EOS","memo":"m"}}'
 
but ,i get nothing,why?
{"binargs":"","required_scope":[],"required_auth":[]}

**Comment by YunZhuangCai** [comment]
i fix the probleom:
the right command is 
curl http://127.0.0.1:8888/v1/chain/abi_json_to_bin -X POST -d '{"code":"token", "action":"transfer", "args":{"from":"user","to":"tester", "quantity":"1.0000 EOS","memo":"m"}}'

**Comment by Cavan2477** [comment]
The value of the 'code' field in the command should be 'eosio.token'.
The value of the 'quantity' field should be fill in a blankspace.
