### ISSUE TITLE
Currency.cpp incomplete?

### ISSUE THREAD

**Issue by alexwagg** [EOSIO/eos#2518]
Hello,

Diving into some EOSIO contract writing as a long-time solidity developer. The file seems incomplete https://github.com/EOSIO/eos/blob/master/contracts/currency/currency.cpp , there are a lot more methods given in the .abi file, that don't seem implemented?

Also, this is supposed to be an EOS ERC20 token (whatever you want to call it) correct?

Cheers!
Alex

**Comment by nsjames** [comment]
Refer to the one in the `eosiolib`. You can see that it inherits from it.

**Comment by jgiszczak** [comment]
Currency is deprecated in favor of token.
