### ISSUE TITLE
Using uint8_t[] as the type of the board in the tic_tac_toe.abi - error: "is_type(field.type):"

### ISSUE THREAD

**Issue by LiorHalfon** [EOSIO/eos#2536]
Hi,
After finishing the TicTacToe tutorial, I started playing with the .abi and changed the board type from:
>{
          "name": "board",
          "type": "uint8[]"
        }

to:
>{
          "name": "board",
          "type": "uint8_t[]"
        }

So it will match the board type in the .hpp.
When i tried to deploy the contarct (after making a change in the .cpp to change the wast hash), I was getting this error: 
> ~/Documents/eos_dev/projects: cleos set contract tic.tac.toe ./tic_tac_toe/
Reading WAST/WASM from ./tic_tac_toe/tic_tac_toe.wast...
Assembling WASM...
Publishing contract...
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
is_type(field.type):
~/Documents/eos_dev/projects:

1) Why "uint8_t" is an invalid type for this array?
2) That error does not give the developer a lot of information about the issue.

Version: #2381

**Comment by tbfleming** [comment]
This doesn't answer your questions, but it may help. The list of basic types is at

https://github.com/EOSIO/eos/blob/15953cc1be7a4d4ff168d0235dbaba9464033b70/libraries/chain/contracts/abi_serializer.cpp#L56

**Comment by LiorHalfon** [comment]
Thank @tbfleming .
That can explain the error. uint8_t is not a supported type of .abi types.
After looking at abi_serializer.cpp code, I can see there is a validation for types:
`         FC_ASSERT(is_type(td.type), "invalid type", ("type",td.type));
`
But for some reason, it didn't catch uint8_t as an invalid type.
