### ISSUE TITLE
incorrect command

### ISSUE THREAD

**Issue by IamGabrielWu** [EOSIO/eos#2537]
Code here in wiki is using start_nodeos.sh but it doesn't exist.
`docker run --name nodeos -p 8888:8888 -p 9876:9876 -t eosio/eos start_nodeos.sh arg1 arg2`
Please change it to 
`docker run --name nodeos -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh arg1 arg2`

**Comment by gleehokie** [comment]
Fixed - thank you.
