### ISSUE TITLE
eosiocpp complie cpp into wast  error

### ISSUE THREAD

**Issue by loganwu** [EOSIO/eos#2538]
eosio/eos:20180420

when I compile debug.cpp with eosiocpp in eosio  running docker, I encounter with follow error.
eosiocpp  -o debug.wast debug.cpp 
/opt/eosio/bin/eosiocpp: line 42: /opt/wasm/bin/clang: No such file or directory

**Comment by 4575759ww** [comment]
me too

**Comment by grigio** [comment]
dup #2480

**Comment by ericiles** [comment]
This is due to the "eosio/eos" image not having all the required dependencies to compile the contract. You should now be able to pull down "eosio/builder:latest" and build your contracts inside of that container.
