### ISSUE TITLE
nodeos blocked after start

### ISSUE THREAD

**Issue by winlin** [EOSIO/eos#2545]
the start nodeos cmdline with just testnet:
`/usr/local/bin/nodeos --enable-stale-production false --data-dir /home/xxxxx/opt/data-dir --config-dir /home/xxxxx/opt/data-dir`

the log print:
`1257770ms thread-0   chain_plugin.cpp:99           plugin_initialize    ] initializing chain plugin
1257770ms thread-0   http_plugin.cpp:141           plugin_initialize    ] host: 0.0.0.0 port: 8888
1257770ms thread-0   http_plugin.cpp:144           plugin_initialize    ] configured http to listen on 0.0.0.0:8888
1257770ms thread-0   net_plugin.cpp:2622           plugin_initialize    ] Initialize net plugin
1257770ms thread-0   net_plugin.cpp:2644           plugin_initialize    ] Setting net_plugin logging level to info
1257770ms thread-0   net_plugin.cpp:2672           plugin_initialize    ] host: 0.0.0.0 port: 9876
1257770ms thread-0   net_plugin.cpp:2748           plugin_initialize    ] my node_id is b67eb9f9fdc802ff668bdd1ec1830fca162cdc251550caadff34f74097207a05
1257771ms thread-0   http_plugin.cpp:109           operator()           ] configured http with Access-Control-Allow-Origin: *
1257771ms thread-0   main.cpp:90                   main                 ] nodeos version d9ad8eec
1257771ms thread-0   main.cpp:91                   main                 ] eosio root is /home/xxxx/.local/share
1257771ms thread-0   block_log.cpp:120             open                 ] Log is nonempty
1257771ms thread-0   block_log.cpp:128             open                 ] Index is nonempty`

and the nodeos will block without response, I use gdb to get stack:
`(gdb) bt
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000564abb in bool boost::interprocess::ipcdetail::posix_condition::timed_wait<boost::interprocess::ipcdetail::internal_mutex_lock<boost::interprocess::scoped_lock<boost::interprocess::interprocess_mutex> > >(boost::interprocess::ipcdetail::internal_mutex_lock<boost::interprocess::scoped_lock<boost::interprocess::interprocess_mutex> >&, boost::posix_time::ptime const&) ()
#2  0x00000000008ecb6a in boost::interprocess::interprocess_sharable_mutex::timed_lock(boost::posix_time::ptime const&) ()
#3  0x00000000008ec05d in boost::unique_lock<boost::interprocess::interprocess_sharable_mutex>::timed_lock(boost::posix_time::ptime const&) ()
#4  0x00000000008930bd in eosio::chain::chain_controller::_spinup_db() ()
#5  0x0000000000892629 in eosio::chain::chain_controller::chain_controller(eosio::chain::chain_controller::controller_config const&) ()
#6  0x00000000005b50b7 in eosio::chain_plugin::plugin_startup() ()
#7  0x00000000005ca157 in appbase::plugin<eosio::chain_plugin>::startup() ()
#8  0x00000000004a7e19 in appbase::application::startup() ()
#9  0x000000000049d77a in main ()
(gdb)`

the reason maybe network access problem, in my city it very likely fail to connect other BPs .

**Comment by andriantolie** [comment]
Did you try to run a standalone node? Or did you try to connect to mainnet?

**Comment by brianjohnson5972** [comment]
This issue has been silent for a long time, so I am closing it.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
