### ISSUE TITLE
Issue in Wiki

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [EOSIO/eos#2547]
https://github.com/EOSIO/eos/wiki/Smart%20Contract#basics-of-eos-smart-contract

Inline. Inline is guaranteed to execute with the current transaction or unwind; no notification will be communicated regardless of success or failure. Inline operates **with the same scopes and authorities with the same scopes and authorities** the original transaction had.

**Comment by dskvr** [comment]
Fixed
