### ISSUE TITLE
"docker build . -t eosio/eos" failed

### ISSUE THREAD

**Issue by gunnergit** [EOSIO/eos#2557]
Cloning into 'test/emscripten'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/kripken/emscripten.git' into submodule path 'test/emscripten' failed
Failed to recurse into submodule path 'externals/binaryen'

**Comment by ericiles** [comment]
Looks like this was caused by some type of connectivity issue. I have just successfully built the docker image, so it appears this issue was temporary, and should be working fine now.
