### ISSUE TITLE
Docker/README.md says to build image but actually it can be directly get from "docker pull eosio/builder"

### ISSUE THREAD

**Issue by IamGabrielWu** [EOSIO/eos#2558]
Hello 
I know it's not significant but i'd like to mention.
In the section for eos docker setup, it says to build from source code.
I'd like to mention if you could please add it to your wiki, that user still can "docker pull eosio/builder" to get this image.
And in order to run it, user only needs to have a clone of the folder "Docker", instead of entire repository.

**Comment by andriantolie** [comment]
It's been updated in the README.md https://github.com/EOSIO/eos/tree/master/Docker#docker-hub. It's also available in developer portal
