### ISSUE TITLE
Create a project folder for shared header files

### ISSUE THREAD

**Issue by narauni** [EOSIO/eos#2560]
There is generic code that gets duplicated across different projects that should be extracted into a common shared folder. This is beneficial to prevent confusion on the side of developers and enhances code maintainability of the code.
Primary example is the string_to_name() function that currently exists in the eosio and chain namespaces (in chain/name.hpp and contracts/eosiolib/types.hpp files) that are functionally identical, and no reason to occur in two namespaces.

A new folder, "eosioinc" will be created under libraries folder that will serve as a container for such generic code. Developers are encouraged to place code that is to be shared across different projects into this folder. In general, the code should be housed in the top-level eosio namespace.

CMakeLists.txt files will be updated to expose the folder to the compiler include directories.

**Comment by brianjohnson5972** [comment]
This issue has been silent for some time, closing.  If this is still desired, it should be written against [CTD](https://github.com/EOSIO/eosio.cdt)
