### ISSUE TITLE
Use new dispatcher for identity contract

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eos#2562]

**Comment by taokayan** [comment]
Test suite "identity_tests" has passed with:
    8 test cases out of 8 passed
    253 assertions out of 253 passed

    Test case "identity_tests/identity_create" has passed with:
      24 assertions out of 24 passed

    Test case "identity_tests/certify_decertify" has passed with:
      52 assertions out of 52 passed

    Test case "identity_tests/trust_untrust" has passed with:
      10 assertions out of 10 passed

    Test case "identity_tests/certify_decertify_owner" has passed with:
      35 assertions out of 35 passed

    Test case "identity_tests/owner_certified_by_producer" has passed with:
      37 assertions out of 37 passed

    Test case "identity_tests/owner_certified_by_trusted_account" has passed with:
      37 assertions out of 37 passed

    Test case "identity_tests/owner_certification_becomes_trusted" has passed with:
      28 assertions out of 28 passed

    Test case "identity_tests/ownership_contradiction" has passed with:
      30 assertions out of 30 passed
