### ISSUE TITLE
When put .abi and .wasm file to contract, some wrong occurs!(Maybe .abi file format is wrong ,but why?)

### ISSUE THREAD

**Issue by lingyiliu016** [EOSIO/eos#2565]
cleos set contract debug /Users/changlingyi/eos/build/tools/debug/debug.wast /Users/changlingyi/eos/build/tools/debug/debug.abi 
Reading WAST...
Assembling WASM...
340819ms thread-0   main.cpp:1158                 main                 ] Failed with error: Assert Exception (10)
!"error parsing wast": Error parsing WebAssembly text file:
:1:1: expected '('
{
^

**Comment by jevinsu** [comment]
I meet the same problem, my abi file is same as in the document:
debug.abi
`
{
  "structs": [{
      "name": "foo",
      "base": "",
      "fields": {
        "from": "account_name",
        "to": "account_name",
        "amount": "uint64"
      }
    }
  ],
  "actions": [{
      "action_name": "foo",
      "type": "foo"
    }
  ]
}`

**Comment by lingyiliu016** [comment]
Can I have a look on your debug.hpp and debug.cpp files?

**Comment by lingyiliu016** [comment]
this is my debug.abi content
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-04-24T02:02:17",
  "types": [],
  "structs": [{
      "name": "foo",
      "base": "",
      "fields": [{
          "name": "from",
          "type": "account_name"
        },{
          "name": "to",
          "type": "account_name"
        },{
          "name": "amount",
          "type": "uint64"
        }
      ]
    }
  ],
  "actions": [{
      "name": "foo",
      "type": "foo",
      "ricardian_contract": ""
    }
  ],
  "tables": [],
  "clauses": []
}

**Comment by GankerBen** [comment]
Hi guys, I got the same errors, but I finally try it out, run the command like this:
./cleos set contract currency ../../contracts/currency
It mean that you just need pass the directory path, not .apiwast and .api, it is different from the tutorial, but it works.

**Comment by lingyiliu016** [comment]
when I commit deploy a contract on blockchain, "Error 3030002: signatures do not satisfy declared authorizations" occurs!

Details are as follows：
 cleos set contract debug /Users/changlingyi/eos/build/tools/debug/
Reading WAST...
Assembling WASM...
Publishing contract...
Error 3030002: signatures do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and you wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"debug","permission":"active"}', but does not have signatures for it.

I have checked that have the related private keys inside your wallet and you wallet is unlocked.
what should I do?give me some suggestion!

**Comment by GankerBen** [comment]
For now the branch is so unstable, so I suggest you wait for the master branch release.

**Comment by durongzheng** [comment]
two suggestion to resolve it:
1. create a new account to publish the contract, maybe you have publish one use eosio account.
2. remember import new key into your wallet, and add the option -p ***@active, alike that.
hope to useful.

**Comment by andriantolie** [comment]
Yes, the new command looks like this
`cleos set contract debug /Users/changlingyi/eos/build/tools/debug/`
instead of 
`cleos set contract debug /Users/changlingyi/eos/build/tools/debug/debug.wast /Users/changlingyi/eos/build/tools/debug/debug.abi`

For the next error, it's very likely that you didn't import debug's private key to your wallet (or you didn't unlock your wallet)

**Comment by liusong00621** [comment]
Thank you.It's error message. I have runing the contract，but I want to replace the contract. how to do 
account.code_version != code_id: contract is already running this version of code.
