### ISSUE TITLE
account without permissons

### ISSUE THREAD

**Issue by wuuzx** [EOSIO/eos#2566]
![image](https://user-images.githubusercontent.com/30622396/39164024-e9b90fa8-47af-11e8-8453-b91644fe477b.png)

Is this a bug? Or what operation leads to this?

**Comment by wuuzx** [comment]
![image](https://user-images.githubusercontent.com/30622396/39170846-89cc5666-47cf-11e8-8535-a173819f6d39.png)

Strange umm....

**Comment by andriantolie** [comment]
Could be a bug on the old version. In the latest version, `cleos get account` works differently and won't return empty permission. Reopen this issue if you still encounter something peculiar.
