### ISSUE TITLE
Can not get transactions

### ISSUE THREAD

**Issue by remonee** [EOSIO/eos#2567]
./cleos get transactions testa
842758ms thread-0   main.cpp:1435                 main                 ] Failed with error: Key Not Found (6)
Key data

How to solve this problem?

**Comment by remonee** [comment]
![image](https://user-images.githubusercontent.com/16790373/39170480-4ebfa36c-47ce-11e8-97ca-d24ac44cfad9.png)

**Comment by alexsharypin** [comment]
try 
cleos get transactions testa -j

**Comment by andriantolie** [comment]
This is solved by #2656. get_transactions is part of account_history_api_plugin which is now deprecated, it is replaced by history_api_plugin
