### ISSUE TITLE
Incorrect block producer key with testnet

### ISSUE THREAD

**Issue by yassersheikh** [EOSIO/eos#2571]
I'm using EOSIO Dawn 3.0 . For the single instance, setup looks fine (https://www.screencast.com/t/nsbYQWaCnp)

But when trying to connect with testnet getting following error. I have used this [config.ini](https://github.com/michaeljyeates/10mill/blob/master/config.ini) and [genesis.json](https://github.com/michaeljyeates/10mill/blob/master/genesis.json) file. 

https://www.screencast.com/t/oJ64Sdvh

Please help.
Thanks

**Comment by michaeljyeates** [comment]
Please ask in the community testnet group for help on this.  The testnet was not in a good way but should be better now
