### ISSUE TITLE
Block lock exception in stderr.txt

### ISSUE THREAD

**Issue by jchung00** [EOSIO/eos#2573]
Running a node on a testnet, and I get this "block lock exception" when looking at logs with tail -F stderr.txt. Node is still up and producing, but I saw this new exception so I thought it'd be best to post it here. It doesn't seem normal?
```console
1750087ms thread-0   chain_controller.cpp:2138     operator()           ] meta.id: 404417bf327d0fed3e8d5c9bd5a173b0a16c61f6e2fa7aa82fabe9fa37e0e7d3 
push block #2550733 from kangaroo 2018-04-24T08:29:10.000  0026ebcdd90e0ebff91d02b0ee37c1e862f07e64027c8c76e21dfe1c2f31946e lib: 2498106 success
1750594ms thread-0   chain_controller.cpp:2138     operator()           ] 3020003 block_lock_exception: shard locks in block are incorrect or mal-formed
read lock "eosio::eosio" required but not provided
    {"a":"eosio","s":"eosio"}
    thread-0  apply_context.cpp:193 require_read_lock

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:30 exec_one

    {}
    thread-0  chain_controller.cpp:2125 __apply_transaction
1750594ms thread-0   chain_controller.cpp:2138     operator()           ] meta.id: 8abea3c5f0b96a9b6ff1c978720f22ca55cce1bc40b6fedd53d1942e30fbd9e6 
push block #2550734 from kangaroo 2018-04-24T08:29:10.500  0026ebceb062ab2399e19b5d42eedf333fd68ef641b2d76b4988aacb6c218b59 lib: 2498106 success
1750602ms thread-0   net_plugin.cpp:2121           handle_message       ] Local network version: 1 Remote version: 0
```

**Comment by jchung00** [comment]
Running on new tag, DAWN-04-23-ALPHA by the way!

**Comment by basakkang** [comment]
I got similar one.

132668ms thread-0   chain_controller.cpp:2138     operator()           ] meta.id: 660ea4eb9e9761a3fea086007bad59f3e879d47f301507c7a71a3add7e6fe8d4
push block #2648656 from salamander 2018-04-25T10:00:59.000  00286a50989be4e7872580237d06cde0327de7aa24884abf26622fb68295df4f lib: 2529767 success
132669ms thread-0   chain_controller.cpp:2138     operator()           ] 3020003 block_lock_exception: shard locks in block are incorrect or mal-formed
read lock "eosio::eosio" required but not provided
    {"a":"eosio","s":"eosio"}
    thread-0  apply_context.cpp:193 require_read_lock

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:30 exec_one

    {}
    thread-0  chain_controller.cpp:2125 __apply_transaction

**Comment by DenisCarriere** [comment]
Message from @pmesnier (for those not on JungleTestnet's Telegram)

> Regarding all the messages “read lock… required but not provided” in the nodeos log file, these are recorded transactions that resulted in a hard_fail outcome. So even though the initial action failed, the transaction is valid.
