### ISSUE TITLE
Create Unit Test that will Start EOSD and verify it produces blocks

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#258]
Currently it is possible to break the code in a way that only shows up when attempting to start EOSD.   We need to automate this to make sure we don't break it.

**Comment by pmesnier** [comment]
I'll take this. A shell script uses the launcher can start a single node, then after say 10 seconds uses the launcher's kill function to terminate the node and finally use grep -c to ensure there are 2 or 3 block production comments in the logged output.

**Comment by jgiszczak** [comment]
Did tests/chain_test fail in this case?  It has several tests which create test chains and generate blocks, among other things.  You do need to run "ctest" in your build dir "tests" directory to run them.

**Comment by pmesnier** [comment]
I believe the various other tests load the components of interest directly. This need is specifically to run eosd. Look for a PR to be added shortly.

**Comment by brianjohnson5972** [comment]
Travis runs chain_test, slow_test, and api_test

**Comment by pmesnier** [comment]
Right. And as far as I can tell, none of them run eosd. Am I wrong?

**Comment by brianjohnson5972** [comment]
None of them do. I was just responding to the statement about needing to
run ctest. Just making it clear that is part of the automatic build.

**Comment by pmesnier** [comment]
new test merged.
