### ISSUE TITLE
Support block producer private key operations to be isolated in helper process

### ISSUE THREAD

**Issue by fproulx** [EOSIO/eos#2586]
Block producer should be able to isolate its private key in separate process / separate host to protect from exfiltration if node is compromised.

Most flexible and simple option would be to delegate private key signing operation to a helper process, which may optionally delegate to HSM or other system.

**Comment by ellipticasec** [comment]
That's essential for BPs to adequately protect their private key :+1:

**Comment by ellipticasec** [comment]
Yay thank you so much !
