### ISSUE TITLE
How to deploy a smart contract through RPC API？

### ISSUE THREAD

**Issue by xdleihui** [EOSIO/eos#2587]

**Comment by tbfleming** [comment]
This assumes your code is sucessfully pushing transactions via RPC.

Push ```setcode``` and ```setabi``` actions to ```eosio```.

```setcode``` needs:
* account
* vmtype: 0
* vmversion: 0
* code: .wasm (not .wast) format

```setabi``` needs:
* account
* abi

Fetch the abi from ```eosio``` to get the types for those fields.

**Comment by andriantolie** [comment]
Answered by @tbfleming
