### ISSUE TITLE
I got the error: cd: /Volumes/MAC: No such file or directory when exec eosio_build.sh

### ISSUE THREAD

**Issue by chengxulvtu** [EOSIO/eos#2591]
![2018-04-25 3 44 45](https://user-images.githubusercontent.com/949848/39232411-ce0334fa-489f-11e8-8efa-28c2cfb16c64.png)

My current workdir is "/Volumes/MAC DATA/eos"

**Comment by pacificcode** [comment]
@chengxulvtu The issue here is the space in your directory/volume name i.e. /Volumes/MAC DATA/eos
Ill have a PR in for this on Monday, in the meantime you can rename your volume i.e. /Volumes/MAC_DATA/eos or move your eos/ directory to a path that does not have a space in the name.

**Comment by chengxulvtu** [comment]
@pacificcode Thanks, I've rename my volume.
