### ISSUE TITLE
I can't run the blockchain after updating the newest version.

### ISSUE THREAD

**Issue by albertschr** [EOSIO/eos#2592]
I am a Mac OS user.
I ran the `git pull` yesterday, then there's an error when I input this command to run the blockchain system:
`./nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::account_history_api_plugin `
![error](https://user-images.githubusercontent.com/12784118/39248795-9c11aa5a-48cf-11e8-8fde-e83580328f29.jpeg)
I roll-backed my code to the old version, and the command is valid now, so I think the problem coming from the updating.:-)

**Comment by jgiszczak** [comment]
The newest version of the code attempts to reserve 32 GB of disk space for the shared memory file.  If you don't have sufficient disk space for a file that large and don't have a filesystem capable of creating sparse files, you'll need to add an additional command line parameter to specify a smaller size.  To get the previous behavior of 1 GB, use `--shared-memory-size-mb 1024`.  This option can be added to the config.ini file (as `shared-memory-size-mb = 1024`) if you'd like to persist it.
