### ISSUE TITLE
SLIM - execute cfa actions at time they are scheduled by contracts

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#2594]
The validity of a CFA does not depend upon blockchain state; therefore, it can be billed at the time it is scheduled and not dispatched at the time the scheduled transaction is executed.

Issues
- [ ] currently contracts don't deal with signed transactions and cannot pass CFD to code
- [ ] alternatively we could simply prohibit CFA created by scheduled transactions; however, we do support CFA for inline actions.  Therefore, I think it is reasonable to convert all scheduled cfa actions into inline cfa actions.

**Comment by wanderingbort** [comment]
As CFAs are not currently widely used and, changes to contract intrinsics for  CFA/D inclusion would require a hardfork, we are left with this being a speculative optimization with low priority.  I'm going to close this issue for now and it may re-open later if empirical data suggests that this is a worthwhile optimization OR the priority of CFD in deferred transactions is bumped up as a feature.

In the case of the latter, we need to engage in a full user-story for the feature.
