### ISSUE TITLE
Create the Arbitration Smart Contract

### ISSUE THREAD

**Issue by coreylederer** [EOSIO/eos#2597]
Create the Arbitration Smart Contract based on the workflow as defined in the link below:

https://docs.google.com/presentation/d/1hjgDKm8NO2E4FiCecVooN9N6ryjXbiGc7QmJlxmttVI/edit#slide=id.p

This will need to take into account:

1. Opening an arbitration case, including supporting documents, evidence, damages, priority, staking a bond on their claim
2. Arbitration forum reviewing the case
3. Arbitration forum assigning the case, assigning a bond / defence fund if the Claimant does not have the $ to provide in their own defence, Need to also track Claimants if they are abusing the defence fund
5. Validation of messages to the claimant and respondent
6. Ability for arbitrator to ask for clarification of additional supporting documents/data for the case
7. Ability to an arbitrator to make a ruling on a case
8. Ability for damages to be awarded

Claimants should also have a place in their account to place EOS into a performance bond, a separate place to set aside money to be frozen in case of an arbitration case against them

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner I am thinking that any task for Arbitration would be considerably different than these thoughts back in April and a new ticket should be created when this is actually thought through.  If I don't hear from you I will presume that is the case.

**Comment by brianjohnson5972** [comment]
The existing code and plans for arbitration have changed considerably since this issue was created.  Closing.
