### ISSUE TITLE
fc::variant deserialization fails for boost::multiprecision::number<T>

### ISSUE THREAD

**Issue by elmato** [EOSIO/eos#26]
**Ubuntu 16.04.2 LTS
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
boost 1.60.0**

```
UInt16 val16(150);
fc::variant v;
fc::to_variant(val16, v);

UInt16 tmp;
fc::from_variant(v, tmp);
BOOST_CHECK_EQUAL( val16, tmp );
```
The above test fails when using **decltype(n)**

```
template<typename T> void from_variant( const variant& v, boost::multiprecision::number<T>& n ) {
      n = decltype(n)(v.get_string());
}
```
Fixed using the type explicitly

```
template<typename T> void from_variant( const variant& v, boost::multiprecision::number<T>& n ) {
      n = boost::multiprecision::number<T>(v.get_string());
}
```
chain_controller::validate_tapos() fails because deserialization of refBlockNum and refBlockPrefix is wrong

**Comment by bytemaster** [comment]
That is a good catch, decltype(n) is probably resolving to boost::multiprecision::number<T>&, fix looks solid.
