### ISSUE TITLE
DAWN-493 ⁃ Advertise chain_id

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#260]
External clients need the chain ID to sign with.  Printing the chain ID when `eosd` starts has worked great in the past.

Additionally, it is a really going to be important to have something like `get_chain_info` so clients can call this and be sure they are talking to the correct chain..

**Comment by jcalfee** [comment]
@nathanhourt per our discussion .. you have some ideas about a handshake?

**Comment by jcalfee** [comment]
Well, I figured out how to get by for now.  I should have known .. lol

`chain_id: 0000000000000000000000000000000000000000000000000000000000000000`

**Comment by nathanhourt** [comment]
Yep, right now everything assumes chain_id is null

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Kevin Heifner

3 months ago

If not worked under STBT, will at least need to make it clear that chain_id should be null.

**Comment by jgiszczak** [comment]
Chain ID is now available in `get info` and is the SHA256 serialization of the genesis state.
