### ISSUE TITLE
ram is missing in eosio.system contract

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eos#2605]
For [contract eosio.system](https://github.com/EOSIO/eos/tree/master/contracts/eosio.system), there is stake of net, cpu and storage. It lacks of ram, specifically missing in [eosio.system.hpp](https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/eosio.system.hpp) and [voting.cpp](https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/voting.cpp)
```
 void delegatebw( const account_name from, const account_name receiver,
                          const asset stake_net_quantity, const asset stake_cpu_quantity,
                          const asset stake_storage_quantity );
```

**Comment by elmato** [comment]
**stake_storage_quantity** refers to how much tokens `from` is delegating to `recevier` for **ram** storage
