### ISSUE TITLE
Build fail on macOS 10.13.4 "Unable to find requested Boost libraries"

### ISSUE THREAD

**Issue by erlingrj** [EOSIO/eos#2610]
The build exits with the following error after almost finishing the installation. I have used brew to install Boost but it installs version 1.67 in a different location. The builder searchs in:
/usr/local/include while brew put it in:
/usr/local/Cellar/boost/1.67.0_1/ in this directory I find prompted libraries.

I am not that technical so I couldnt find where BOOST_ROOT and BOOST_LIBRARYDIR are to change them. Should I change them to the directory with boost 1.67?

> >>>>>>>> ALL dependencies sucessfully found or installed . Installing EOS.IO
> 
> -- Using custom FindBoost.cmake
> CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
>   Unable to find the requested Boost libraries.
> 
>   Boost version: 1.66.0
> 
>   Boost include path: /usr/local/include
> 
>   The following Boost libraries could not be found:
> 
>           boost_date_time
>           boost_filesystem
>           boost_system
>           boost_program_options
>           boost_signals
>           boost_serialization
>           boost_chrono
>           boost_unit_test_framework
>           boost_iostreams
> 
>   Some (but not all) of the required Boost libraries were found.  You may
>   need to install these additional Boost libraries.  Alternatively, set
>   BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
>   to the location of Boost.
>

**Comment by pacificcode** [comment]
@erlingrj run the following commands and you should be good to go.
(the eosio_build.sh script will install boost properly)
brew remove boost
cd /path/to/eos
rm -rf build/
git checkout master
git pull
git submodule update --init --recursive
./eosio_build.sh

**Comment by erlingrj** [comment]
Hi @pacificcode thanks for your quick reply. I ran all the commands but still get the same error regarding the boost libraries. 

This is the complete read out:

> 

> Beginning build version: 1.2
> 	Fri Apr 27 13:43:39 UTC 2018
> 	User: root
> 	git head id: 4e99117b16037c3c3873916848354fa6d3acb438
> 	Current branch: * master
> 
> 	ARCHITECTURE: Darwin
> 
> 	OS name: Darwin
> 	OS Version: 10.13.4
> 	CPU speed: 230.00Ghz
> 	CPU cores: 2
> 	Physical Memory: 8 Gbytes
> 	Disk space total: 79G
> 	Disk space available: 36G
> 
> 	Checking XCode installation
> 	XCode installation found.
> 
> 	Checking Ruby installation
> 	Ruby installation found.
> 
> 	Checking Home Brew installation
> 	Home Brew installation found.
> 
> 	Checking dependencies.
> 	Checking automake ... 		 automake found
> 	Checking Libtool ... 		 Libtool found
> 	Checking OpenSSL ... 		 OpenSSL found
> 	Checking llvm ... 		 llvm found
> 	Checking wget ... 		 wget found
> 	Checking CMake ... 		 CMake found
> 	Checking GMP ... 		 GMP found
> 	Checking gettext ... 		 gettext found
> 	Checking MongoDB ... 		 MongoDB found
> 	Checking Doxygen ... 		 Doxygen found
> 	Checking Graphviz ... 		 Graphviz found
> 	Checking LCOV ... 		 LCOV found
> 	Checking Python3 ... 		 Python3 found
> 
> 	No required Home Brew dependencies to install.
> 
> 	Checking boost library installation.
> 	Boost 1.66.0 found at /usr/local.
> 
> 	Checking MongoDB C++ driver installation.
> 	Mongo C++ driver found at /usr/local/lib/libmongocxx-static.a.
> 
> 	Checking secp256k1-zkp installation.
> 	secp256k1 found at /usr/local/lib/
> 
> 	Checking LLVM with WASM support.
> 	WASM found at /usr/local/wasm/bin/
> 
> 
> >>>>>>>> ALL dependencies sucessfully found or installed . Installing EOS.IO
> 
> -- The C compiler identification is Clang 4.0.1
> -- The CXX compiler identification is Clang 4.0.1
> -- Check for working C compiler: /usr/local/bin/clang
> -- Check for working C compiler: /usr/local/bin/clang -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/local/bin/clang++
> -- Check for working CXX compiler: /usr/local/bin/clang++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Using custom FindBoost.cmake
> CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
>   Unable to find the requested Boost libraries.
> 
>   Boost version: 1.66.0
> 
>   Boost include path: /usr/local/include
> 
>   The following Boost libraries could not be found:
> 
>           boost_date_time
>           boost_filesystem
>           boost_system
>           boost_program_options
>           boost_signals
>           boost_serialization
>           boost_chrono
>           boost_unit_test_framework
>           boost_iostreams
> 
>   Some (but not all) of the required Boost libraries were found.  You may
>   need to install these additional Boost libraries.  Alternatively, set
>   BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
>   to the location of Boost.
> Call Stack (most recent call first):
>   CMakeLists.txt:88 (FIND_PACKAGE)
> 
> 
> -- Configuring Eos on OS X
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - found
> -- Found Threads: TRUE  
> -- binaryen building with -std=c++11
> -- binaryen building for platform x86-64
> -- binaryen building with -Wall
> -- binaryen building with -Werror
> -- binaryen building with -Wextra
> -- binaryen building with -Wno-unused-parameter
> -- binaryen building with -fno-omit-frame-pointer
> -- binaryen building with -fPIC
> -- binaryen building with -O2
> -- binaryen building with -UNDEBUG
> -- Found WASM: /usr/local/wasm/bin/clang  
> -- Using WASM clang => /usr/local/wasm/bin/clang
> -- Using WASM llc => /usr/local/wasm/bin/llc
> -- Using WASM llvm-link => /usr/local/wasm/bin/llvm-link
> -- Found Secp256k1: /usr/local/lib/libsecp256k1.a
> -- Found GMP: /usr/local/lib/libgmp.a  
> -- Configuring fc to build on Unix/Apple
> -- Found OpenSSL: /usr/local/opt/openssl/lib/libcrypto.a (found version "1.0.2o") 
> -- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
> -- zlib found
> -- Found BZip2: /usr/lib/libbz2.dylib (found version "1.0.6") 
> -- Looking for BZ2_bzCompressInit
> -- Looking for BZ2_bzCompressInit - found
> -- bzip2 found
> -- Configuring SoftFloat
> -- Using custom FindBoost.cmake
> CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
>   Unable to find the requested Boost libraries.
> 
>   Boost version: 1.66.0
> 
>   Boost include path: /usr/local/include
> 
>   The following Boost libraries could not be found:
> 
>           boost_date_time
>           boost_filesystem
>           boost_system
>           boost_chrono
>           boost_unit_test_framework
> 
>   Some (but not all) of the required Boost libraries were found.  You may
>   need to install these additional Boost libraries.  Alternatively, set
>   BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
>   to the location of Boost.
> Call Stack (most recent call first):
>   libraries/chainbase/CMakeLists.txt:26 (FIND_PACKAGE)
> 
> 
> -- Configuring ChainBase on OS X
> -- Using custom FindBoost.cmake
> CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
>   Unable to find the requested Boost libraries.
> 
>   Boost version: 1.66.0
> 
>   Boost include path: /usr/local/include
> 
>   The following Boost libraries could not be found:
> 
>           boost_date_time
>           boost_filesystem
>           boost_system
>           boost_chrono
>           boost_program_options
>           boost_unit_test_framework
> 
>   Some (but not all) of the required Boost libraries were found.  You may
>   need to install these additional Boost libraries.  Alternatively, set
>   BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
>   to the location of Boost.
> Call Stack (most recent call first):
>   libraries/appbase/CMakeLists.txt:22 (find_package)
> 
> 
> -- Configuring AppBase on OS X
> -- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
> -- Found bsoncxx library: /usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-D_THREAD_SAFE
> -- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
> -- Found mongocxx library: /usr/local/lib/libmongocxx-static.a;/usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-D_THREAD_SAFE;/usr/local/lib/libmongoc-static-1.0.a;/usr/local/lib/libbson-static-1.0.a;-D_THREAD_SAFE;-lsasl2;-framework Security;-framework CoreFoundation;-lz;-lresolv
> -- Found Git: /usr/bin/git (found version "2.15.1 (Apple Git-101)") 
> -- Git commit revision: 4e99117b
> -- Git commit revision: 4e99117b
> CMake Error at /usr/local/Cellar/cmake/3.11.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Failed to find Gettext libintl (missing: Intl_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /usr/local/Cellar/cmake/3.11.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   /usr/local/Cellar/cmake/3.11.1/share/cmake/Modules/FindIntl.cmake:47 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   programs/cleos/CMakeLists.txt:29 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/erling/Projects/eos/build/CMakeFiles/CMakeOutput.log".
> 
> 	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.
>

**Comment by pacificcode** [comment]
@erlingrj Im not seeing the build script installing boost from source so Im guessing this is an issue from a previous install.
Try the following steps (do not skip any of these steps).
# remove boost and clear boost info from homebrew database
brew remove boost 
# remove boost header files
sudo rm -rf /usr/local/include/boost 
# remove boost libraries
sudo rm -rf /usr/local/lib/libboost* 
# run the build script and this will install boost from source
./eosio_build.sh

If you run into any further issue paste the output from eosio_build.sh here.

**Comment by pacificcode** [comment]
@erlingrj your getting closer. It would be best to compile boost manually. Here is how you would do this:
export BOOST_ROOT=/usr/local
cd /tmp
curl -LO https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2
tar xf boost_1_66_0.tar.bz2
rm -f boost_1_66_0.tar.bz2
cd boost_1_66_0/
./bootstrap.sh "--prefix=${BOOST_ROOT}"
./b2 install
cd /tmp
rm -rf /tmp/boost_1_66_0/

cd /path/to/eos
./eosio_build.sh

Let me know how things work out.

**Comment by erlingrj** [comment]
That did it. Thanks alot for your patience and help!!

Good weekend

**Comment by Panoplos** [comment]
For others finding this, I ran into a missing boost error and running `brew install boost` fixed it in my environment. Surprised this is not included in the Homebrew installation script in the EOSIO build step.

**Comment by tbfleming** [comment]
I’m starting to think that Apple makes machines which function differently from each other. When we try running the script on newly-purchased machines of the models that we happen to use, it works.
