### ISSUE TITLE
About key generate

### ISSUE THREAD

**Issue by WildDylan** [EOSIO/eos#2611]
Hello, some questions about generate public and private key like use command ' ./cleos creat key '.

some eosjs api can generate it ?
or rpc api can generate it?

hope ..

**Comment by andriantolie** [comment]
You can't use RPC API but you can use eosjs-ecc which is bundled inside eosjs.
Check these links
https://github.com/EOSIO/eosjs#related-libraries
https://github.com/EOSIO/eosjs-ecc#randomkey

Example
```
const Eos = require('eosjs');
const { ecc } = Eos.modules

ecc.randomKey().then(privateKey => {
  console.log('Private Key:\t', privateKey) // wif
  console.log('Public Key:\t', ecc.privateToPublic(privateKey)) // EOSkey...
  })
```
