### ISSUE TITLE
init start blocker producer create block while syncing and nodeos be hanging

### ISSUE THREAD

**Issue by winlin** [EOSIO/eos#2617]
`push block #10995 from joker 2018-04-06T12:19:36.000  00002af390f4b569f0fe4103f5465ba0dde3040969c661f9809548f1606a39e2 lib: 73 success
push block #10996 from joker 2018-04-06T12:19:36.500  00002af4f8f47f54607f8267cf937e029444c3cbed217da1c9adc47a1bc0724b lib: 73 success
push block #10997 from joker 2018-04-06T12:19:37.000  00002af53e07de915f0f904adfc600ef4a35737d5e6ce20b9f84865a90336d61 lib: 73 success
push block #10998 from joker 2018-04-06T12:19:37.500  00002af60c1b5054d93e6da3b462879231b06f49af193e63630b7d45bb2cb08d lib: 73 success
push block #10999 from joker 2018-04-06T12:19:38.000  00002af76eed0f601a10cb7ac266db42c21dd0f92c31277f4579db98b7d850fb lib: 73 success
push block #11000 from joker 2018-04-06T12:19:38.500  00002af871f378e71839e0d70cc622d120bd8b5947616c6c3214478be6150a70 lib: 73 success
216129ms thread-0   net_plugin.cpp:943            operator()           ] Error sending to peer eosgreen.uk.to:9875: Bad file descriptor
216129ms thread-0   net_plugin.cpp:1986           operator()           ] Error reading message from eosgreen.uk.to:9875: Bad file descriptor
216129ms thread-0   net_plugin.cpp:943            operator()           ] Error sending to peer eosgreen.uk.to:9875: Bad file descriptor
220563ms thread-0   net_plugin.cpp:1920           operator()           ] checking max client, visitors = 0 num clients 1
220563ms thread-0   net_plugin.cpp:680            connection           ] accepted network connection
225654ms thread-0   net_plugin.cpp:1854           connect              ] host: 159.89.197.162 port: 9877
225655ms thread-0   net_plugin.cpp:1854           connect              ] host: eosgreen.uk.to port: 9875
225655ms thread-0   net_plugin.cpp:1854           connect              ] host: test.eosys.io port: 9875
225655ms thread-0   net_plugin.cpp:1854           connect              ] host: 128.1.39.81 port: 9876
225655ms thread-0   net_plugin.cpp:1854           connect              ] host: ctestnet.eosio.se port: 62071
225655ms thread-0   net_plugin.cpp:1854           connect              ] host: 54.194.49.21 port: 9875
225655ms thread-0   net_plugin.cpp:686            ~connection          ] released connection from client
268888ms thread-0   fork_database.cpp:78          _push_block          ] Number of missed blocks: 3641377
elektra generated block 004d20cd... #11001 @ 2018-04-27T14:04:27.500 with 0 trxs, lib: 73
269002ms thread-0   fork_database.cpp:78          _push_block          ] Number of missed blocks: 2
elektra generated block ed74ee63... #11002 @ 2018-04-27T14:04:29.000 with 0 trxs, lib: 73
elektra generated block 1dc73710... #11003 @ 2018-04-27T14:04:29.500 with 0 trxs, lib: 73
elektra generated block 83c5d6e5... #11004 @ 2018-04-27T14:04:30.000 with 0 trxs, lib: 73
elektra generated block 7234f250... #11005 @ 2018-04-27T14:04:30.500 with 0 trxs, lib: 73
elektra generated block ec96c908... #11006 @ 2018-04-27T14:04:31.000 with 0 trxs, lib: 73
elektra generated block 387945cb... #11007 @ 2018-04-27T14:04:31.500 with 0 trxs, lib: 73
elektra generated block ce87c198... #11008 @ 2018-04-27T14:04:32.000 with 0 trxs, lib: 73`

init start a blocker producer, and the bp create block while syncing and then nodeos be hanging not print logs

**Comment by EOSBIXIN** [comment]
long time ago, I think the bug have fixed

**Comment by andriantolie** [comment]
Yeah. Please reopen if you still this issue
