### ISSUE TITLE
Ability to delete abi and code

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#2618]
The following would allow users to remove code and or abi:

Make the last parameter "optional" so a null value can be provided:
```js
// remove contract from the blockchain
eos.setcode('currency', 0, 0, null/*wasm*/)
eos.setabi('currency', null /*abi*/)
```

**Comment by xJonathanLEI** [comment]
With `eosjs`, the following code should do the trick:

    eos.setcode(account_name, 0, 0, new Uint8Array());

**Comment by hama** [comment]
how  to use cleos ?

**Comment by betdiceone** [comment]
> With `eosjs`, the following code should do the trick:
> 
> ```
> eos.setcode(account_name, 0, 0, new Uint8Array());
> ```

So how to remove abi?

**Comment by brianjohnson5972** [comment]
This was provided by #5442
