### ISSUE TITLE
Change build to build and install binaryen as pre-build step

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#262]
Change Travis to use a pre-built install of binaryen.

**Comment by brianjohnson5972** [comment]
@bytemaster Do we just want to do this in the Travis build or do we want to change our build as well?  Asking because Travis will not be building the exact same thing as we are.  It isn't a big issue if there is never a reason to make any changes to binaryen.  If there are then we will be dealing with updating and installing binaryen, but not being prompted to do it till we make the changes in the submodule and Travis fails.

**Comment by bytemaster** [comment]
We are not planning on making any changes to binaryen and thus want to remove it from our source tree entirely and reference pre-installed executable.  But that means our unit test environment will need to find the pre-built one.

I would say that this issue has the secondary task of removing the binaryen submodule from eos.

**Comment by brianjohnson5972** [comment]
Also, if we pre-build Boost for Travis, it will save us 2 minutes as well.

**Comment by brianjohnson5972** [comment]
So this task is to change the build steps to build and install binaryen, as part of WebAssembly instructions, remove binaryen submodule, and change cmake to use the install.  Along with this a pre-built binaryen needs to be added to the pre-built WebAssembly repo and Travis changed to pull down the pre-built files.
