### ISSUE TITLE
assert error barked about symbols but it was really precision

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#2623]
1.0000 DOS (too many decimals) caused this error:
**condition: assertion failed: comparison of assets with different symbols is not allowed**

1.00 DOS worked (2 decimals are correct)

```bash
cleos push action currency issue '{"to":"inita", "quantity": "1.0000 DOS", "memo": ""}' -p currency@active
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
condition: assertion failed: comparison of assets with different symbols is not allowed


cleos push action currency issue '{"to":"inita", "quantity": "1.00 DOS", "memo": ""}' -p currency@active
executed transaction: 84a5cc33c6fbd273196644bad0572e3982dcb3be6a8c1936e537e813f173fe97  248 bytes  122880 cycles
#      currency <= currency::issue              {"to":"inita","quantity":"1.00 DOS","memo":""}
>> issue
#      currency <= currency::transfer           {"from":"currency","to":"inita","quantity":"1.00 DOS","memo":""}
>> transfer
#         inita <= currency::transfer           {"from":"currency","to":"inita","quantity":"1.00 DOS","memo":""}
```

**Comment by elmato** [comment]
This is because the **symbol** of a token is the composition of a `symbol name` and a `precision`.
Maybe the message should specify that you are using the wrong precision.

**Comment by jcalfee** [comment]
Yea maybe, Non-hard forking change .. From the API's point of view there is only one symbol involved so "comparison" and "assets" could be looked at too..

**Comment by taokayan** [comment]
The precision is one of the information of an asset symbol. So "1.00 DOS" and "1.0000 DOS" are treated as different symbols. However, we'll improve the error message/docs in the future.

**Comment by jgiszczak** [comment]
With `--verbose-http-errors` enabled in nodeos, this now results in:
```
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: symbol precision mismatch
```
Without `--verbose-http-errors` enabled, it results in:
```
Error 3050003: eosio_assert_message assertion failure
```
