### ISSUE TITLE
Testing Upgrade Hooks Testing

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2630]
There are two intrensic apis:
```
activate_feature(name)
has_feature(name)
```

Has feature should only return true once the block that called activate_feature becomes irreversible.

Node should shutdown automatically if it attempts to switch to an irreversible block that it considers invalid.

**Comment by heifner** [comment]
We still need to test an actual hard fork on a live network.

**Comment by taokayan** [comment]
hi @heifner, I'm wondering do we also need to expose some API to get current version of the blockchain in the contract? Since a hard forked blockchain might support the same API but executes in a different way.

**Comment by heifner** [comment]
@taokayan Probably not at this time.
