### ISSUE TITLE
Crypto API tests

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2631]

**Comment by andriantolie** [comment]
Hi @gleehokie 

I saw that test_api/test_crypto unit test is working on `slim` branch and it has covered all the APIs defined in eosiolib/crypto.h. Can we have more explanation about what's missing here? Thanks!

**Comment by gleehokie** [comment]
@andriantolie please check the code coverage report to validate the crypto functions are being tested.

**Comment by andriantolie** [comment]
Okay

**Comment by andriantolie** [comment]
When I run it locally, 
even though `tests/chain_test --run_test=api_tests/crypto_tests --report_level=detailed -- --verbose --binaryen` passes, `tests/chain_test --run_test=api_tests/crypto_tests --report_level=detailed -- --verbose --binaryen` fails with `3030010 checktime_exceeded: allotted processing time was exceeded`. I'm going to put this ticket back to TODO first for further checking

**Comment by andriantolie** [comment]
Ah found it, it's actually now `unittests/unit_test` instead of `tests/chain_test`. Running it locally also produces the same result. I'm going to close this ticket

**Comment by wangyilin1987** [comment]
@andriantolie hi,  contracts/test_api.cpp  this test contract how to call?how it work?thank you

**Comment by wangyilin1987** [comment]
@andriantolie how make contracts/test_api work? i don't know how push action what to this contracts
