### ISSUE TITLE
Test updating a permission link

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2633]

**Comment by andriantolie** [comment]
Hi @gleehokie, can we have a more detailed description here?

If it is about testing updateauth/ linkauth, we already have some test cases inside unittests/auth_tests/update_auths and unittests/auth_tests/link_auths. They are a

I don't see any test case where auth is updated after it is linked, so I will add it. But if this is not what this ticket is originally intended for, more detail is really appreciated! Thanks

**Comment by brianjohnson5972** [comment]
The delayed tests do an updateauth for the active account, so there is an
updateauth that updates an existing permission.
