### ISSUE TITLE
remove apply_context::all_authorizations_used

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2637]

**Comment by brianjohnson5972** [comment]
@gleehokie This method isn't tested because it is no longer called.  I think it was replaced by the auth checker logic in authorization_manager::check_authorization.  We should change this to remove the method.

**Comment by dhaneshvb** [comment]
Both in slim and master repo, all_authorizations_used() is not being used. Hence no unit tests are written.

Marking this request for unit tests as closed

**Comment by brianjohnson5972** [comment]
@dhaneshvb  This ticket has been changed to be "remove apply_context::all_authorizations_used", so the task is now to remove the code.

**Comment by arhag** [comment]
@dhaneshvb Feel free to remove it. It didn't conflict with any of my work, but anyway my work on authorizations is already merged in at this point.

Also, while you are removing `apply_context::all_authorizations_used()`, you can also remove `apply_context::unused_authorizations()` and the `used_authorizations` field in `apply_context`. All of that is dead code.

**Comment by dhaneshvb** [comment]
@arhag , I am on it. Will submit the pull request in an hour with the updates, thank you
