### ISSUE TITLE
smart constract build error:  no member named 'rand' in namespace 'std'

### ISSUE THREAD

**Issue by jie123108** [EOSIO/eos#2643]
eos 3.0(master)  smart constract code: 
```
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>
#include <cstdlib>
#include <stdlib.h>

using namespace eosio;

class hello : public eosio::contract {
  public:
      using contract::contract;

      /// @abi action 
      void hi( account_name user ) {
        print(std::rand());
        print(rand());
         print( "Hello, ", name{user} );
      }
};

EOSIO_ABI( hello, (hi) )
```
build command:  **eosiocpp  -o test.wast hello.cpp**

build error: 
```
hello.cpp:14:20: error: no member named 'rand' in namespace 'std'
        print(std::rand());
              ~~~~~^
hello.cpp:15:15: error: use of undeclared identifier 'rand'
        print(rand());
              ^
```

who can help me?

**Comment by lhzw** [comment]
Met the same problem.

**Comment by learnforpractice** [comment]
There is no rand function in smart contract, it will break the consensus. Although you can simulate rand function with other method such as block hash, it also has known weak point as mining pool can cheat on it.

**Comment by jgiszczak** [comment]
`rand()` is not and will not be supported.  Contracts must execute and reexecute deterministically on each node as blocks are built and confirmed.  The `rand()` function's API and expected behavior are not compatible with this requirement.

**Comment by jie123108** [comment]
Thanks.

**Comment by cipherzzz** [comment]
How would I generate a random number then? Most app require some sort of random generation... Is there a snippet that anyone cares to share?
