### ISSUE TITLE
EOSIO_ABI support for external contract calls

### ISSUE THREAD

**Issue by kesar** [EOSIO/eos#2647]
If you need to catch, for example, a transfer of eosio.token, you need to tweak a bit how it works, and you can't auto-generate ABI. 

Example:

https://github.com/kesar/twitbot/blob/master/contracts/twitbot/twitbot.cpp#L72

Need to add another macro that allows for processing other code's actions and need to convert one of the existing complex examples to use it (like proxy.cpp).

**Comment by filipniziol** [comment]
Does it work as it is for you?
I do not get this proxy.cpp -> it has no class "proxy" but namespace? Does not look like a typical contract

**Comment by taokayan** [comment]
Please refer to INLINE_ACTION_SENDER in eosio.system.cpp for calling an action from other contracts.

**Comment by kesar** [comment]
@taokayan 

issue is when you are listening for an action from other contract.

**Comment by Dylan-Phoon** [comment]
Has this been solved yet?

**Comment by nahue086** [comment]
Any updates?

**Comment by brianjohnson5972** [comment]
Please try this out on [CDT](https://github.com/EOSIO/eosio.cdt) and if you still have an issue please write it up there.
