### ISSUE TITLE
get_block error with assert_exception.

### ISSUE THREAD

**Issue by basakkang** [EOSIO/eos#2653]
I got this messages during testing search by block_num. Is this mean # 62 block was missed?

`curl http://test.eosys.io:8887/v1/chain/get_block -X POST -d '{"block_num_or_id": 62}'
{"code":500,"message":"Internal Service Error","error":{"code":10,"name":"assert_exception","what":"Assert Exception","details":[{"message":"itr != structs.end(): Unknown struct ","file":"abi_serializer.cpp","line_number":185,"method":"get_struct"},{"message":"Failed to serialize type","file":"abi_serializer.hpp","line_number":439,"method":"to_variant"}]}}`

**Comment by taokayan** [comment]
Can you try with the latest version?

**Comment by andriantolie** [comment]
It seems it has a problem in deserializing the block. It could be because there's a change in the block structure that's not backward compatible at that day. Please reopen this issue if you still see it in the latest version
