### ISSUE TITLE
without "-j", it will report as the description.

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#2656]
root@eosio:~/data# cleos get transactions eosio
813330ms thread-0   main.cpp:1764                 main                 ] Failed with error: Key Not Found (6)
Key data

**Comment by Joelone** [comment]
Got the same error, here is more verbose output:

```
$ cleos -v get transactions user
3338195ms thread-0   main.cpp:1158                 main                 ] Failed with error: 6 key_not_found_exception: Key Not Found
Key data
    {"key":"data"}
    thread-0  variant_object.cpp:90 operator[]

```

**Comment by Joelone** [comment]
It is duplicated of #2567 
https://github.com/EOSIO/eos/issues/2567

**Comment by yankunsam** [comment]
Thanks
