### ISSUE TITLE
update Smart-Contract.md cpp code snippet to have proper closing parans

### ISSUE THREAD

**Issue by Alex1100** [EOSIO/eos#2663]
Check out the wiki on [my forked eos repo](https://github.com/Alex1100/eos/wiki/Smart%20Contract). Also, here is the proposed change to be included in the Smart-Contract.md wiki file.

Lines 195 - 215

```
**code filter**

In order to respond to a particular action, structure the `apply` function as follows. You may also construct a response to general actions by omitting the code filter.

```base
if (code == N(${contract_name})) {
    // your handler to respond to particular action
}
```

You can also define responses to respective actions in the code block.

**action filter**

To respond to a particular action, structure your `apply` function as follows. This is normally used in conjuction with the code filter.

```base
if (action == N(${action_name})) {
    //your handler to respond to a particular action
}
```

**Comment by taokayan** [comment]
the "apply" method is no longer explicitly needed in the contract. Please use macro EOSIO_ABI instead.
