### ISSUE TITLE
Keosd determines the home directory in non-compliant way

### ISSUE THREAD

**Issue by narauni** [EOSIO/eos#2666]
Keosd uses a locally coded function to determine the home directory, which subsequently is concatenated with string literals to determine its data-dir and config-dir.
The locally coded function reverses (in relation to the nodeos way) the steps in which the home directory is determined: i.e. first it attempts to get it from the user's "passwd" file, and if that fails from the $HOME environment variable, falling back on the current directory: "./".
nodes on the other hand calls fc::app_path(), which reverses the steps describe above, and is the preferred way to determine the "home" directory.

**Comment by spoonincode** [comment]
I think this is too risky to change now as it could possibly disturb current behavior for some users. Closing it as Won't Fix.
