### ISSUE TITLE
nodeos crashes processing transaction request

### ISSUE THREAD

**Issue by cj-oci** [EOSIO/eos#2667]
Requesting transaction before its finalized crashes nodeos. Requests for finalized transactions are safe.

Example:
  programs/cleos/cleos -v set contract -j eosio contracts/eosio.bios contracts/eosio.bios/eosio.bios.wast contracts/eosio.bios/eosio.bios.abi
  programs/cleos/cleos get transaction 2a914ff60d96a35b072e21fbcc46a4d98322ed4ceeae6ed14f21921b7850a940

Workaround: Wait for transaction to become finalized. On a single node this is achieved by waiting 1-2 seconds before transaction request.

**Comment by cj-oci** [comment]
run "tests/nodeos_run_test.py --only-bios -v --dont-kill"
"pgrep -a nodeos" will show only noeos_00 running, nodeos_bios has crashed.
[nodeos_run_test-pr2667.zip](https://github.com/EOSIO/eos/files/1962260/nodeos_run_test-pr2667.zip)

**Comment by heifner** [comment]
Resolved by #2680

**Comment by heifner** [comment]
Verified by @cj-oci
