### ISSUE TITLE
Action setprods causes nodeos crash

### ISSUE THREAD

**Issue by cj-oci** [EOSIO/eos#2670]
Command
programs/cleos/cleos push action -j eosio setprods {"schedule": [ { "producer_name": "initd", "block_signing_key": "EOS5cP2fcBxbydCNqm2KoPnHa8SGyKW7RqvHyQGhJhgQHT7e9z3qJ" } ] } --permission eosio@active

causes nodeos app crash with log message:

calling $21 resulted in (none.const ?) but the function type is 1
nodeos: ../libraries/chain/../../externals/binaryen/src/wasm-interpreter.h:804: wasm::Flow wasm::ModuleInstanceBase<std::map<wasm::Name, wasm::Literal, std::less<wasm::Name>, std::allocator<std::pair<const wasm::Name, wasm::Literal> > >, wasm::ModuleInstance>::callFunctionInternal(wasm::Name, LiteralList &)::RuntimeExpressionRunner::visitSetLocal(wasm::SetLocal *) [GlobalManager = std::map<wasm::Name, wasm::Literal, std::less<wasm::Name>, std::allocator<std::pair<const wasm::Name, wasm::Literal> > >, SubType = wasm::ModuleInstance]: Assertion `curr->isTee() ? flow.value.type == curr->type : true' failed.

**Comment by cj-oci** [comment]
Test attached. Run "tests/nodeos_run_test.py --only-bios -v --dont-kill"
Check log message for nodeos error detail.
[nodeos_run_test-pr2670.zip](https://github.com/EOSIO/eos/files/1962281/nodeos_run_test-pr2670.zip)

**Comment by cj-oci** [comment]
After May 1 morning sync this is no longer an issue, nodeos instance does not crash upon receiving setprods action.

**Comment by heifner** [comment]
Although this particular bug was fixed. Question now is how did this kill nodeos. @larryk85 will investigate.

**Comment by heifner** [comment]
In debug builds binaryren has asserts. So debug builds can cause nodeos to abort if an assert is tripped.
