### ISSUE TITLE
Docker fails to build

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eos#2672]
following the instructions on the Docker page, I've attempted to build an image but the build results in the following error:

> [516/1289] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/webassembly/binaryen.cpp.o
> The command '/bin/sh -c git clone -b master --depth 1 https://github.com/EOSIO/eos.git --recursive     && cd eos     && cmake -H. -B"/tmp/build" -GNinja -DCMAKE_BUILD_TYPE=Release -DWASM_ROOT=/opt/wasm -DCMAKE_CXX_COMPILER=clang++        -DCMAKE_C_COMPILER=clang -DCMAKE_INSTALL_PREFIX=/tmp/build  -DSecp256k1_ROOT_DIR=/usr/local -DBUILD_MONGO_DB_PLUGIN=true     && cmake --build /tmp/build --target install' returned a non-zero code: 137

I started from scratch by removing all existing images from docker, removing my previous EOS directory and cloning from github

it's broken.  ideas anyone?

p.s. running on OSX 10.11.6 and Docker 18.04.0-cd-rc2

p.p.s.  no, I can't built natively as EOS requires >= 10.13 and I'm not upgrading.  the newer versions break my access to TimeCapsule and I'm not dealing with that nightmare

**Comment by andriyha** [comment]
Docker -> Preferences -> Advanced -> Memory -> 8GB or above
than try again

**Comment by ekkis** [comment]
awesome!! that worked.  can we pleeease document this on the docker page?

**Comment by ericiles** [comment]
It is actually already documented in the README file in the docker directory. Glad you got this working,
