### ISSUE TITLE
eosc create account inita signature not added

### ISSUE THREAD

**Issue by toonsevrin** [EOSIO/eos#268]
`eosc create account inita tester <pubkey> <pubkey>` will only work with the `--skip-transaction-signatures` eosd flag. 

Apparently [this](https://github.com/EOSIO/eos/blob/master/programs/eosc/main.cpp#L135) signature is added too early.

**Comment by toonsevrin** [comment]
according to @heifner the signature override shall be removed with the cli wallet update

**Comment by heifner** [comment]
This will be fixed by #220, closing.

**Comment by 0x83043** [comment]
I can create account only with flag --skip-transaction-signatures. In another way (first key - new pair, second - public key inita, is it correct?):
```
3490242ms thread-0   main.cpp:135                  create_account       ] public key 02c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf
3490249ms thread-0   main.cpp:467                  main                 ] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error
: 3030002 tx_missing_sigs: signatures do not satisfy declared authorizations
Transaction declares authority '{"account":"inita","permission":"active"}', but does not have signatures for it.
    {"auth":{"account":"inita","permission":"active"}}
    thread-0  chain_controller.cpp:752 check_transaction_authorization
```

**Comment by asvirido** [comment]
I have this problem!

**Comment by asvirido** [comment]
2084154ms thread-0   main.cpp:768                  main                 ] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error
: 3030002 tx_missing_sigs: signatures do not satisfy declared authorizations
Transaction declares authority '{"account":"inita","permission":"active"}', but does not have signatures for it.
    {"auth":{"account":"inita","permission":"active"}}
    thread-0  chain_controller.cpp:749 get_required_keys

    {"msg":"3030002 tx_missing_sigs: signatures do not satisfy declared authorizations\nTransaction declares authority '{\"account\":\"inita\",\"permission\":\"active\"}', but does not have signatures for it.\n    {\"auth\":{\"account\":\"inita\",\"permission\":\"active\"}}\n    thread-0  chain_controller.cpp:749 get_required_keys"}
    thread-0  httpc.cpp:113 call

    {"server":"localhost","port":8888,"path":"/v1/chain/get_required_keys","postdata":{"transaction":{"refBlockNum":392,"refBlockPrefix":2240632363,"expiration":"2017-09-07T12:36:22","scope":["eos","inita"],"readscope":[],"messages":[{"code":"eos","type":"newaccount","authorization":[{"account":"inita","permission":"active"}],"data":"000000008040934b00000000c84267a101000000010200b35ad060d629717bd3dbec82731094dae9cd7e9980c39625ad58fa7f9b654b010000010000000103d2c4da204cffd357dcb09832cb2dff9d26d9bd66a28eee3e13e492d3094f3f6e010000010000000001000000008040934b00000000149be8080100010000000000000004454f5300000000"}],"signatures":[]},"available_keys":[]}}
    thread-0  httpc.cpp:117 call
