### ISSUE TITLE
Block production stops upon setprods action

### ISSUE THREAD

**Issue by cj-oci** [EOSIO/eos#2681]
Action "setprods" as shown below will halt block production. In attached example run "tests/nodeos_run_test.py --only-bios -v --dont-kill"

Log "var/lib/node_bios/stderr.txt" will show block production has stopped.

[https://app.zenhub.com/files/87335980/59d863ba-ad62-4a4b-80b7-500ad0df9294/download](https://app.zenhub.com/files/87335980/59d863ba-ad62-4a4b-80b7-500ad0df9294/download)

**Comment by heifner** [comment]
With only one node you can't change producer because there is no other producer to switch to.
