### ISSUE TITLE
Allow EOSC to accept alternate HTTP host/port

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#269]
I attached this comment to issue #203 but it seems to have been overlooked. It should be a separate issue anyway, Here's my original request:

'm looking for the most appropriate way to override the default host/port to which eosc sends the messages. I've thought of:
eosc --server host:port command ...,
eosc @host:port commmand ...
eosc command@host:port ....

in each case, an omitted host or port value is defaulted. In the case of streaming mode, I'd like this value to be changeable so that commands can be spread across many nodes. For that reason I'd prefer the second or third options listed above.

**Comment by brianjohnson5972** [comment]
my vote is --server host:port to have all command line tools have a typical
way of passing in command line args

**Comment by pmesnier** [comment]
Yeah, but eosc command line is already different from all other command lines.

**Comment by brianjohnson5972** [comment]
So far eosc has no configuration flags, these are all parameters related to
the command being processed ("create", "accounts", ...)

it is a very typical to see:

./<exe> [--some-flag value] [--another-flag value] command [first-param
[second-param ...]]

**Comment by pmesnier** [comment]
Right, but in a way you are reinforcing my point. I want the host:port to vary by command so that in a streaming mode, where commands are fed through stdin, successive commands can be sent to different nodes.

**Comment by heifner** [comment]
I also need to be able to specify the walletd endpoint.

**Comment by nathanhourt** [comment]
How is eosc command line different from other command lines? I designed it to be as typical as possible. Did I make a mistake? :P

The canonically correct way to add a server flag would be `--server host:port` and I think that's the best way to do it, just as @brianjohnson5972 described.

As to streaming mode... that's a much bigger can of worms, and I'm not convinced it makes sense to have eosc support it at all. The whole point of eosc in the first place was that we weren't going to reimplement the shell in it. This streaming mode is equivalent to writing a new shell, and is thus what eosc is supposed to not be. Eosc was designed to support that use case by using the shell to invoke it multiple times. If that's not fast enough, your use case is niche enough it may require its own utility.

And @heifner, it seems to me that all wallet-related logic should be in a `wallet` subcommand, no? That subcommand could have a walletd endpoint parameter. Would that work?

**Comment by heifner** [comment]
> And @heifner, it seems to me that all wallet-related logic should be in a wallet subcommand, no? That subcommand could have a walletd endpoint parameter. Would that work?

yes

**Comment by pmesnier** [comment]
Ok. If eosc is going to be restricted to issuing a single command then terminating, use of --server is fine and dandy. My motivation for creating the stream to begin with was to allow eosc to hold a connection open for a good long time in order to remove process startup/teardown + TCP socket connection and disconnection from the commanding overhead, but from what Dan found that most of the time is JSON related, my "optimization" is not particularly advantageous.  I think we found the HTTP plugin shuts down the connection anyway so even TCP connection is just part of every call's overhead.

So let's add --server host:port.

**Comment by wanderingbort** [comment]
it looks like @bytemaster  added `host` and `port` options for `eosc` in d16254c

it does not match the `--server` pattern but covers the needed functionality
