### ISSUE TITLE
stack limit error when push action

### ISSUE THREAD

**Issue by giniz** [EOSIO/eos#2697]
Hi,

I got this error when calling an action which performs multiindex.emplace() on a struct inheriting another struct
`Error 3030020: Runtime Error Processing WASM
Error Details:
stack limit
`
When removing inheritance and put all properties to child struct, it worked.

**Comment by giniz** [comment]
Nobody has seen this issue yet..?

**Comment by elmato** [comment]
@giniz Can you post a link to the source code?

**Comment by giniz** [comment]
hi @elmato,

My source looks like below:
```c++
struct order
{
    uint64_t id;
    account_name client;
    string order_time;
    string order_type;
    asset volume;
    asset price;
}
struct sellorder : order
{
}
struct buyorder : order
{
}
typedef eosio::multi_index<N(sellorder), sellorder> sellorders;

.....

sellorders selltable(_self, _self);
auto neworder = selltable.emplace(_self, [&](auto &a) {
	a.id = selltable.available_primary_key();
	a.client = client;
	a.order_time = order_time;
	a.order_type = order_type;
	a.volume = volume;
	a.price = price;
});
```

**Comment by lingyiliu016** [comment]
I have the same error,when I push an action at block link.
what should I do?
details as follows
 cleos push action child.acnt addtoken '{"id":"3","genes":"genes3","birthTime":"1514736000","cooldownEndTime":"1546272000","matronId":"100","sireId":"200","siringWithId":"50","cooldownIndex":"1","generation":"1","version":"1","_owner":"girl.account"}' -p child.acnt
Error 3030020: Runtime Error Processing WASM
Error Details:
stack limit

**Comment by lingyiliu016** [comment]
I have the same error,when I push an action at Blockchain.
what should I do?
details as follows
cleos push action child.acnt addtoken '{"id":"3","genes":"genes3","birthTime":"1514736000","cooldownEndTime":"1546272000","matronId":"100","sireId":"200","siringWithId":"50","cooldownIndex":"1","generation":"1","version":"1","_owner":"girl.account"}' -p child.acnt
Error 3030020: Runtime Error Processing WASM
Error Details:
stack limit

**Comment by ChristianDunst** [comment]
Problem with the serializer

**Comment by IvanYakimov** [comment]
Same here

**Comment by brianjohnson5972** [comment]
This issue has gone silent for a while, so closing. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for known bug reporting and features tracking, and Stack Exchange is the right place for any technical support discussions (and after discussing, if a bug is identified open a new issue). Thanks!
