### ISSUE TITLE
cannot create newaccount in eosjs (eosjs@eosjs@9.0.1)

### ISSUE THREAD

**Issue by yepp4you** [EOSIO/eos#2698]
http://localhost:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-05-02T02:26:42","region":0,"ref_block_num":7790,"ref_block_prefix":1418688422,"max_net_usage_words":0,"max_kcpu_usage":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000ea3055000000022103b89a010000000100022b0368a8fe1251def8a057f4b034874d4a0fba2b0b95993f1f008e94b8d11589010000010000000100022b0368a8fe1251def8a057f4b034874d4a0fba2b0b95993f1f008e94b8d115890100000100000000010000000000ea305500000000a8ed32320100"}]},"signatures":["EOSJyx6LxUqGE8ALGZ1xzaB2mMRn6eALYVjxTC3BfiGapna6GaNM7BGJ9k3N9v5XBYWJzn8V6Too5vxcQ6dn5wjiFVUphxt3d"]}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3120010,"name":"packed_transaction_type_exception","what":"Invalid packed transaction","details":[{"message":"Invalid packed transaction","file":"chain_plugin.cpp","line_number":432,"method":"push_transaction"},{"message":"pivot != std::string::npos: No delimiter in string, cannot determine type: EOSJyx6LxUqGE8ALGZ1xzaB2mMRn6eALYVjxTC3BfiGapna6GaNM7BGJ9k3N9v5XBYWJzn8V6Too5vxcQ6dn5wjiFVUphxt3d","file":"signature.cpp","line_number":20,"method":"parse_base58"},{"message":"Failed to deserialize variant","file":"abi_serializer.hpp","line_number":444,"method":"from_variant"}]}}

**Comment by BinaryFocus** [comment]
I'm seeing the same problem, I had a working web interface that created accounts and after upgrading the server I now get the same error.  I also updated eosjs lib on the client side and seeing the same thing. 

```
thread-0   abi_serializer.hpp:349        extract              ] vo: {"compression":"none","transaction":{"expiration":"2018-05-04T02:33:52","region":0,"ref_block_num":23473,"ref_block_prefix":884907158,"max_net_usage_words":0,"max_kcpu_usage":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000ea3055404a0857619db1ca0100000001000215bbc2361e334d9acb10f8fd6b5976ea040fd947377057699de227e972e37958010000010000000100028cfdbd5a25bd6d6ab3ea0eb13e4b43b771e13ac4b699d525def0d44f4440fdff0100000100000000010000000000ea305500000000a8ed32320100"}]},"signatures":["EOSKX1ULcfcUfAZ43F17xLhRHAT3JUsxgqa7KPv6eycA7qmCmZpC1aKy3ZM7eFgAxjDxUsb85iR51DH2X64gQfgPefdQ3RwgT"]} 

thread-0   chain_api_plugin.cpp:79       operator()           ] Exception encountered while processing chain.push_transaction: {"code":3120010,"name":"packed_transaction_type_exception","message":"Invalid packed transaction","stack":[{"context":{"level":"warn","file":"chain_plugin.cpp","line":432,"method":"push_transaction","hostname":"","thread_name":"thread-0","timestamp":"2018-05-04T02:32:53.176"},"format":"Invalid packed transaction","data":{}},{"context":{"level":"error","file":"signature.cpp","line":20,"method":"parse_base58","hostname":"","thread_name":"thread-0","timestamp":"2018-05-04T02:32:53.176"},"format":"pivot != std::string::npos: No delimiter in string, cannot determine type: ${str}","data":{"str":"EOSKX1ULcfcUfAZ43F17xLhRHAT3JUsxgqa7KPv6eycA7qmCmZpC1aKy3ZM7eFgAxjDxUsb85iR51DH2X64gQfgPefdQ3RwgT"}},{"context":{"level":"error","file":"abi_serializer.hpp","line":444,"method":"from_variant","hostname":"","thread_name":"thread-0","timestamp":"2018-05-04T02:32:53.176"},"format":"Failed to deserialize variant","data":{"variant":{"compression":"none","transaction":{"expiration":"2018-05-04T02:33:52","region":0,"ref_block_num":23473,"ref_block_prefix":884907158,"max_net_usage_words":0,"max_kcpu_usage":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000ea3055404a0857619db1ca0100000001000215bbc2361e334d9acb10f8fd6b5976ea040fd947377057699de227e972e37958010000010000000100028cfdbd5a25bd6d6ab3ea0eb13e4b43b771e13ac4b699d525def0d44f4440fdff0100000100000000010000000000ea305500000000a8ed32320100"}]},"signatures":["EOSKX1ULcfcUfAZ43F17xLhRHAT3JUsxgqa7KPv6eycA7qmCmZpC1aKy3ZM7eFgAxjDxUsb85iR51DH2X64gQfgPefdQ3RwgT"]}}}]}
```

**Comment by BinaryFocus** [comment]
It turns out that this https://github.com/EOSIO/eos/pull/2441 changed the signature format. 

I'm going to open an issue in eosjs to have them update to support this format. 

![20180504122652 000](https://user-images.githubusercontent.com/38670376/39639146-6fcd7d52-4f96-11e8-9390-8fde7247c63f.png)

**Comment by BinaryFocus** [comment]
Closing this issue as this is now open in eosjs

https://github.com/EOSIO/eosjs/issues/72

**Comment by BinaryFocus** [comment]
Never mind,  can't close the issue .. someone else will need to.
