### ISSUE TITLE
cleos programs missing max_transaction_delay variant

### ISSUE THREAD

**Issue by mrmsm** [EOSIO/eos#2706]
Hi :)

I'm tested regproducer with the cleos command.
During the test, we have confirmed that the max_transaction_delay variable is missing.
I solved this by adding "(max_transaction_delay, config :: default_max_trx_delay)" to the regproducer_variant in the programs/cleos/main.cpp # 380 line.
Please consider reflecting this code.

Thanks.

**Comment by taokayan** [comment]
This feature is only for the deferred action, and can be done by setting the expiration of action instead:
```
-x,--expiration             set the time in seconds before a transaction expires, defaults to 30s
```
