### ISSUE TITLE
Create the Arbitration Case Registry

### ISSUE THREAD

**Issue by coreylederer** [EOSIO/eos#2712]
We will need a place to record the details of Arbitration cases.  This will be the place where the Arbitration forum can look to see a listing os the Arbitration cases that are:

**Arbitration Case Status**
- Newly opened (not yet reviewed) - (new)
- In review by Arbitration Forum - (in-forum-review)
- Assigned to an arbitrator (active)
- Case has been arbitrated and remedies ruled upon (arbitrated)
- BP's have been instructed to award damages or not (bp-awarding-damages)
- Damages / awards have been transferred as instructed by Arbitrator (closed)

**This registry should have the following information available:**
- Arbitration case ID number
- Arbitrator, name, identity, preferred language
- Number of days both parties have to respond (10 days is default)
- Date accepted or rejected (and immediately closed)
  - If rejected, ruling on why it was rejected goes to both parties via email.
- Terms of Claim (what was submitted) so it is clear what the issue is.
- Claimed damages
- Bond total, in local currency of Claimant, placed for this claim, default 10% of damages in local currency of Claimant
- Bond total that Respondent has been asked to place for this claim.
- Fees provided during submittal
- Additional arbitration fees requested.
- Evidence of claim damages
- Estimate of losses
- Requested priority of claim
- Emergency injunctive relief requested
- Privacy / Confidentiality status of case
- Assigned Arbitrator (assigned by the Arbitration Forum)

It should allow the Arbitrator / Arbitration forum to query the data by**
- Case-ID-number (at a minimum)
- Arbitrator ID
- Claimant ID
- Respondent ID
- Priority of claim

I defer to the expertise of the team where / how this will be created.

**Comment by genghaibo** [comment]
yes

**Comment by taokayan** [comment]
Is this still open?

**Comment by brianjohnson5972** [comment]
Since this is several months old and arbitration is still being worked out, the requirements for an Arbitration Case Registry will be very different when this is actually pursued, so closing this issue and a new issue will be created when this finally moves forward.
