### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by mrzzcn** [EOSIO/eos#2715]
branch: commit f537bc50b21a7807ff0ee3af83d8f560ce09afa5 (HEAD -> master, origin/master, origin/HEAD)

```bash
The following tests FAILED:
	 27 - nodeos_run_test (Failed)
	 28 - nodeos_run_remote_test (Failed)
	 30 - nodeos_run_test-mongodb (Failed)
	 31 - distributed-transactions-test (Failed)
	 32 - distributed-transactions-remote-test (Failed)
	 33 - restart-scenarios-test_resync (Failed)
Errors while running CTest
make: *** [test] Error 8
```
Mac OS

**Comment by mrzzcn** [comment]
node version: v10.0.0

**Comment by pacificcode** [comment]
@mrzzcn Check that mongod is running and try again.
prep -x mongod

**Comment by mrzzcn** [comment]
@pacificcode yes, mongod was running, and there has been some connections between the tests running.
I just ignored those failed tests and keep `sudo make install `, I run through all the tutorials, and all work fine.

**But**, today, when I try again:
```
The following tests FAILED:
	 30 - nodeos_run_test-mongodb (Failed)
Errors while running CTest
make: *** [test] Error 8
```
there is only one failed test left, and still, the mongod is running.

**Comment by quocle108** [comment]
I tried on MACOS , and also have the same problem:

The following tests FAILED:
	 27 - nodeos_run_test (Failed)
	 28 - nodeos_run_remote_test (Failed)
	 30 - nodeos_run_test-mongodb (Failed)
	 31 - distributed-transactions-test (Failed)
	 32 - distributed-transactions-remote-test (Failed)
	 33 - restart-scenarios-test_resync (Failed)
Errors while running CTest
make: *** [test] Error 8

The test 25, 26 sometime works, but sometime it failed. don't know why.

@mrzzcn : how did you passed others test. I did **make install**, but the test also the same result

**Comment by quocle108** [comment]
When i tried cmd: tests/nodeos_run_test.py --mongodb -v --dump-error-detail >& mongo_test.log
There are something related memory space. But my lap have more than 50GB free memory.

i've attached a logfile

**Comment by mrzzcn** [comment]
@quocle108 I don't know, after `sudo make install` I just keep going with the turorials, today, when I run test again, it just passed. Only that one still failed. 
May be you could try git pull and build again.

**Comment by quocle108** [comment]
@mrzzcn Yes, i've tried git pull. it doesn't work.

By the way, i 've tried to look at logfile. there are something related mongodb and memory space

here is apart of logfile:

1264614ms thread-0   chain_plugin.cpp:225          plugin_startup       ] 13 N5boost12interprocess22interprocess_exceptionE: No space left on device
rethrow No space left on device: 
    {"my->genesis_file.generic_string()":"/Users/quocle/eos/build/etc/eosio/node_00/./genesis.json","what":"No space left on device"}

**Comment by pacificcode** [comment]
@mrzzcn can you run the following and paste the result here?
cd /path/to/eos
df -h .

**Comment by quocle108** [comment]
![screen shot 2018-05-05 at 9 31 06 am](https://user-images.githubusercontent.com/38057360/39658902-2a792f24-5047-11e8-8d19-2c60a155857a.png)

**Comment by pacificcode** [comment]
@quocle108 you are clearly running out of disk space. Clear up some space and you should be good to go.

**Comment by mrzzcn** [comment]
```bash
Filesystem     Size   Used  Avail Capacity iused               ifree %iused  Mounted on
/dev/disk1s1  233Gi  178Gi   45Gi    80% 5220639 9223372036849555168    0%   /
```

**Comment by fher98** [comment]
25/28 Test #25: unit_test_binaryen ..................   Passed   82.72 sec
      Start 26: unit_test_wavm
26/28 Test #26: unit_test_wavm ......................   Passed  354.31 sec
      Start 27: plugin_test
27/28 Test #27: plugin_test .........................   Passed    0.02 sec
      Start 28: distributed-transactions-test
28/28 Test #28: distributed-transactions-test .......***Failed   33.83 sec

96% tests passed, 1 tests failed out of 28

Total Test time (real) = 471.40 sec

The following tests FAILED:
	 28 - distributed-transactions-test (Failed)
Errors while running CTest
Makefile:61: recipe for target 'test' failed
make: *** [test] Error 8
[1]+  Exit 100      

Any help with #28

**Comment by macsilber** [comment]
I think the problem for mac osx users is the paths the these two files are for Linux; when you run tests/nodeos_run_test.py --mongodb -v --dump-error-detail >& mongo_test.log that is the output i get consistently.I also found it worked a few builds ago but then stopped and reverted back.

BEGIN
TEST_OUTPUT: test_output_0.txt
SERVER: localhost
PORT: 8888
 echo db.version() | mongo --host localhost --port 27017 EOStest
 MongoDb response: b'MongoDB shell version v3.6.4\nconnecting to: mongodb://localhost:27017/EOStest\nMongoDB server version: 3.6.4\n3.6.4\nbye\n'
 cmd: pkill -9 keosd
 cmd: programs/eosio-launcher/eosio-launcher -k 15
Test failed.
  =================================================================
  Contents of etc/eosio/node_bios/config.ini:
  File etc/eosio/node_bios/config.ini not found.
  =================================================================
  Contents of var/lib/node_bios/stderr.txt:
  File var/lib/node_bios/stderr.txt not found.
 =================================================================
== Errors see above ==

**Comment by geneidy** [comment]
Also running osx getting same error. 

`BEGIN
SERVER: localhost
PORT: 8888
 echo db.version() | mongo --host localhost --port 27017 EOStest
 MongoDb response: b'MongoDB shell version v3.6.5\nconnecting to: mongodb://localhost:27017/EOStest\nMongoDB server version: 3.6.5\n3.6.5\nbye\n'
 cmd: programs/eosio-launcher/eosio-launcher -k 9
 Test failed.
   =================================================================
   Contents of etc/eosio/node_bios/config.ini:
   File etc/eosio/node_bios/config.ini not found.
   =================================================================
   Contents of var/lib/node_bios/stderr.txt:
   File var/lib/node_bios/stderr.txt not found.
  =================================================================
 == Errors see above ==`

**Comment by geneidy** [comment]
posted but seeing I unassigned @pacificcode. Please excuse me.
