### ISSUE TITLE
Build EOS failed on MAC

### ISSUE THREAD

**Issue by a365344743s** [EOSIO/eos#2719]
Scanning dependencies of target eosio-applesedemo
[ 87%] Building CXX object plugins/http_plugin/CMakeFiles/http_plugin.dir/http_plugin.cpp.o
[ 87%] Building CXX object programs/eosio-applesedemo/CMakeFiles/eosio-applesedemo.dir/main.cpp.o
/Users/ws/Documents/workspace/git/eos/programs/eosio-applesedemo/main.cpp:37:13: warning: unused variable 'ret' [-Wunused-variable]
   OSStatus ret = SecItemCopyMatching(keyAttrDic, (CFTypeRef*)&attributes);
            ^
1 warning generated.
[ 87%] Building CXX object programs/eosio-applesedemo/CMakeFiles/eosio-applesedemo.dir/r1_signature_compactor.cpp.o
[ 87%] Linking CXX executable eosio-applesedemo
ld: framework not found security
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [programs/eosio-applesedemo/eosio-applesedemo] Error 1
make[1]: *** [programs/eosio-applesedemo/CMakeFiles/eosio-applesedemo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 87%] Linking CXX static library libhttp_plugin.a
[ 87%] Built target http_plugin
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by a365344743s** [comment]
On branch master

**Comment by a365344743s** [comment]
Maybe it's because my disk is case-sensitive.

Change "path-to-eos/programs/eosio-applesedemo/CMakeLists.txt"
"-framework security -framework corefoundation"
to
"-framework Security -framework CoreFoundation"
will resolve this problem.

**Comment by gleehokie** [comment]
@ericiles note this issue, perhaps we should configure our CI system for OSX/Darwin to use a case-sensitive file system so these issues are spotted automatically.
