### ISSUE TITLE
when restart nodeos，cleos wallet list shows no wallet?

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#2720]
I use the command below to start test network:
`nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::account_history_api_plugin`
And I create a wallet, use command:
`cleos wallet create -n test`
I could find my wallet, use command:
`cleos wallet list`
then I stop the test network, use ctrl+c.
when I restart the test network, use cleos wallet list, there is no wallet list? why??

**Comment by cluestudio** [comment]
I think you forgot to re-open the wallet with 'cleos wallet open -n test'

**Comment by BinaryFocus** [comment]
Yes, it's a bit confusing that command only shows you open wallets. Not all wallets that exist / have been created. One you open the wallet it'll show up in the list. Note that an open wallet still needs to be unlocked ... unless you see a * after then name of the wallet, it's not unlocked. 

```
./cleos wallet list
Wallets:
[
  "default *"
]
```

**Comment by guaiguaihw** [comment]
Thanks all, the problem has been solved.
