### ISSUE TITLE
Thre is no api to get a total row count for the multi_index table.

### ISSUE THREAD

**Issue by mj-raindays** [EOSIO/eos#2721]
There is no way to get a total row count for the 'multi_index table'?

**Comment by jafri** [comment]
Useful to have

**Comment by dvalencia-sd** [comment]
what is the best approach for this? Is there any solution for this?

**Comment by dominic-healid** [comment]
Is there available function for this now?

**Comment by eosbet-io** [comment]
Yes, this would a very nice improvement. There is no function for is @dominic-healid yet, just looked through the eosio source :(

**Comment by warrick-eosny** [comment]
+10 
This would be extremely helpful. Perhaps a switch like --count
cleos -u https://api.eosnewyork.io get table eosio eosio voters --count

**Comment by kasperfish** [comment]
also opened an issue for this and the guy who responded said it's implemented but I don't see any reference to this inside the linked issue. https://github.com/EOSIO/eos/issues/5543

**Comment by taokayan** [comment]
You can query the number of rows (value in field "count") using "get scope" now. But you can't do it inside a smart contract. Please refer to https://github.com/EOSIO/eos/pull/5486
