### ISSUE TITLE
build failed on macOS

### ISSUE THREAD

**Issue by hoopslb** [EOSIO/eos#2728]
Scanning dependencies of target cleos
[ 97%] Building CXX object programs/cleos/CMakeFiles/cleos.dir/main.cpp.o
[ 97%] Building CXX object tests/CMakeFiles/chain_test.dir/chain_tests/proof_tests.cpp.o
[ 98%] Building CXX object tests/CMakeFiles/chain_test.dir/chain_tests/recovery_tests.cpp.o
[ 98%] Building CXX object tests/CMakeFiles/chain_test.dir/api_tests/api_tests.cpp.o
[ 99%] Building CXX object programs/cleos/CMakeFiles/cleos.dir/httpc.cpp.o
[ 99%] Building CXX object programs/cleos/CMakeFiles/cleos.dir/help_text.cpp.o
[ 99%] Building CXX object tests/CMakeFiles/chain_test.dir/tests/abi_tests.cpp.o
[ 99%] Linking CXX executable cleos
Undefined symbols for architecture x86_64:
  "_libintl_bindtextdomain", referenced from:
      _main in main.cpp.o
  "_libintl_gettext", referenced from:
      eosio::client::localize::localized_with_variant(char const*, fc::variant_object const&) in main.cpp.o
      eosio::client::localize::localized_with_variant(char const*, fc::variant_object const&) in help_text.cpp.o
  "_libintl_setlocale", referenced from:
      _main in main.cpp.o
  "_libintl_textdomain", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [programs/cleos/cleos] Error 1
make[1]: *** [programs/cleos/CMakeFiles/cleos.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object tests/CMakeFiles/chain_test.dir/tests/database_tests.cpp.o
[ 99%] Building CXX object tests/CMakeFiles/chain_test.dir/tests/misc_tests.cpp.o
[ 99%] Building CXX object tests/CMakeFiles/chain_test.dir/wasm_tests/currency_tests.cpp.o
[ 99%] Building CXX object tests/CMakeFiles/chain_test.dir/wasm_tests/dice_tests.cpp.o
[ 99%] Building CXX object tests/CMakeFiles/chain_test.dir/wasm_tests/eosio.system_tests.cpp.o
[ 99%] Building CXX object tests/CMakeFiles/chain_test.dir/wasm_tests/eosio.token_tests.cpp.o
[ 99%] Building CXX object tests/CMakeFiles/chain_test.dir/wasm_tests/exchange_tests.cpp.o
[ 99%] Building CXX object tests/CMakeFiles/chain_test.dir/wasm_tests/identity_tests.cpp.o
[ 99%] Building CXX object tests/CMakeFiles/chain_test.dir/wasm_tests/multi_index_tests.cpp.o
[ 99%] Building CXX object tests/CMakeFiles/chain_test.dir/wasm_tests/multisig_tests.cpp.o
[100%] Building CXX object tests/CMakeFiles/chain_test.dir/wasm_tests/payloadless_tests.cpp.o
[100%] Building CXX object tests/CMakeFiles/chain_test.dir/wasm_tests/tic_tac_toe_tests.cpp.o
[100%] Building CXX object tests/CMakeFiles/chain_test.dir/wasm_tests/wasm_tests.cpp.o
[100%] Building CXX object tests/CMakeFiles/chain_test.dir/tests/special_accounts_tests.cpp.o
[100%] Building CXX object tests/CMakeFiles/chain_test.dir/tests/wallet_tests.cpp.o
[100%] Building CXX object tests/CMakeFiles/chain_test.dir/library_tests/chain/resource_limits_test.cpp.o
[100%] Building CXX object tests/CMakeFiles/chain_test.dir/common/main.cpp.o
[100%] Linking CXX executable chain_test
[100%] Built target chain_test
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by pacificcode** [comment]
@hoopslb This may be the solution:
https://github.com/EOSIO/eos/issues/2028

**Comment by hoopslb** [comment]
@pacificcode 
successfully built
I do this：
------------------------------
brew unlink gettext && brew link --force gettext
find /usr -name libintl* -print 2>/dev/null

**Comment by deju** [comment]
It is works ! :)
