### ISSUE TITLE
voteproducer Ricardian Contract needs to include additional clause forbidding automated re-voting

### ISSUE THREAD

**Issue by thomasbcox** [EOSIO/eos#2732]
the `voteproducer` action of the system contract needs, in its matching Ricardian contract, to forbid automatic re-voting (vs vote strength decay) 

We will have a function of the voting system that older votes will be less powerful than more recently cast votes; a voter can refresh their vote and bring them to full strength by manually and deliberately re-affirming them. 

It shall be a violation of the contract to use or allow to be used any automated system of refreshing a vote. All refreshes must be cast manually and intentionally by the voter.

**Comment by bytemaster** [comment]
We recognize that it is not possible to prove someone didn't automate the process, we merely wish to discourage the provable automatic voting via on-chain smart contracts.
