### ISSUE TITLE
voteproducer may need to collect a signature from the client software

### ISSUE THREAD

**Issue by thomasbcox** [EOSIO/eos#2733]
Attack vector on vote integrity: malicious actors can create faux or dishonest voting portals that seemingly collect a voter's intentions, but then rewrite the transaction to redirect some or all of the votes to the portal's preferred outcomes. 

Voters can protect themselves by inspecting the actual votes cast via another competing portal or block explorer.

The EOSIO voting system would benefit (I believe) by collecting some form of cryptographic signature (or other identifier) from the client software that is collecting and forwarding the `voteproducer` transaction, such that it is verifiable who did or did not collect and forward the vote.

**Comment by bytemaster** [comment]
not possible to do this as you end up trusting the software regardless.
