### ISSUE TITLE
eos transfer Error Error 3040002: Invalid Action Arguments 

### ISSUE THREAD

**Issue by chenfengqiannian** [EOSIO/eos#2751]
I've got 2 accounts, b and c.
Then I tried transfer some eos from b to c. But eosd returned an error as blow, anyone has ever met such error?
that is the command  
"cleos transfer b c 1000"

Error 3040002: Invalid Action Arguments
Ensure that your arguments follow the contract abi!
You can check the contract's abi by using 'cleos get code' command.
Error Details:
'{"from":"b","to":"c","quantity":"0.0001 EOS","memo":""}' is invalid args for action 'transfer' code 'eosio'
Invalid cast from object_type to string

that is b and c account
{
  "account_name": "b",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS8hdhrncnn1fKk21iHb7g9F8Q7MGa3VdfDiYEffqVeNVgo9iJ5K",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS8hdhrncnn1fKk21iHb7g9F8Q7MGa3VdfDiYEffqVeNVgo9iJ5K",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}

{
  "account_name": "c",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6BYMVG1UNaXqkAiR7KXiqzD1bMVHEcUMprqJwUfSByToPzhJkb",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6BYMVG1UNaXqkAiR7KXiqzD1bMVHEcUMprqJwUfSByToPzhJkb",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}

{
  "account_name": "c",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6BYMVG1UNaXqkAiR7KXiqzD1bMVHEcUMprqJwUfSByToPzhJkb",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6BYMVG1UNaXqkAiR7KXiqzD1bMVHEcUMprqJwUfSByToPzhJkb",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}

**Comment by gleehokie** [comment]
You must specify the full precision, try:

`cleos transfer b c 1000.0000`

depending on what version you are working with you may need to specify the symbol as well:

`cleos transfer b c 1000.0000 EOS`

**Comment by chenfengqiannian** [comment]
thanks for you help
i try you methods ，but it cant work also
that is err mssage

**cleos transfer b c "1000.0000"**

Error 3040002: Invalid Action Arguments
Ensure that your arguments follow the contract abi!
You can check the contract's abi by using 'cleos get code' command.
Error Details:
'{"from":"b","to":"c","quantity":"0.1000 EOS","memo":""}' is invalid args for action 'transfer' code 'eosio'
Invalid cast from object_type to string

and i also try **cleos transfer b c "1000.0000 EOS"**

Error 3040002: Invalid Action Arguments
Ensure that your arguments follow the contract abi!
You can check the contract's abi by using 'cleos get code' command.
Error Details:
'{"from":"b","to":"c","quantity":"0.1000 EOS","memo":""}' is invalid args for action 'transfer' code 'eosio'
Invalid cast from object_type to string

**Comment by quocle108** [comment]
@chenfengqiannian ,
I think there are something wrong from generated .abi file. Did you check .abi contract file
To query the contract use following code:
```
$ cleos get code -a contract.abi contract
$ cat contract.abi
```
