### ISSUE TITLE
Null content generated in abi file by eosiocpp for offical eosio.token  contract

### ISSUE THREAD

**Issue by michaekang** [EOSIO/eos#2752]
When I run "eosiocpp" command try to get abi file for offical eosio.token contract, the file content is NULL as the following steps:

```
kshdeMac-mini:eosio.token kangshuo$ eosiocpp -g eosio.token.abi eosio.token.cpp 
Generated eosio.token.abi ...
kshdeMac-mini:eosio.token kangshuo$ cat eosio.token.abi 
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-05-04T04:05:22",
  "types": [],
  "structs": [],
  "actions": [],
  "tables": [],
  "ricardian_clauses": []
}kshdeMac-mini:eosio.token kangshuo$ 
```

**Comment by michaekang** [comment]
If  I use hello testcase, I can use eosiocpp to generate the abi file. After some comparison, I found different way of "eosio namespace" declaration caused the abi generation problem. And I try to dig into the issue.

**Comment by giniz** [comment]
I think because that file missed _// @abi table_ and still used _bool_ type in structs.

**Comment by yekai1003** [comment]
You can use  “use namespace eosio;”  replace "namespace eosio {"  in hpp and cpp files.

**Comment by Phoenix117** [comment]
"//@abi table" and "//@abi action" are necessary.

**Comment by isha-padalia** [comment]
@yekai1003 is right,

replacing `namespace eosio {}` with `using namespace eosio;` will solve the issue.

also remove eosio:: from whole code.

**Comment by andriantolie** [comment]
This is fixed for latest eosio.token
