### ISSUE TITLE
Build failed on ubuntu 16.04

### ISSUE THREAD

**Issue by giniz** [EOSIO/eos#2753]
Hi @pacificcode 
From eos dir, I tried:
```shell
rm -rf build/
git pull
git submodule update --init --recursive
./eosio_build.sh
```
and got this error, with an empty build folder:
```
-- Found mongocxx library: /usr/local/lib/libmongocxx-static.a;/usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-lm;-pthread;/usr/local/lib/libmongoc-static-1.0.a;/usr/local/lib/libbson-static-1.0.a;-lm;-pthread;-lssl;-lcrypto;-lrt;-lz;-lresolv
-- Git commit revision: 19227c9b
-- Git commit revision: 19227c9b
-- Git commit revision: 19227c9b
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxxxxx/eos
make: *** No targets specified and no makefile found.  Stop.

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.
```
As I remember, the build was still success last week.

**Comment by pacificcode** [comment]
@giniz 
-- Build files have been written to: /home/xxxxxx/eos
that should have been /home/xxxxxx/eos/build
Can you remove the build directory, run the build script and capture the entire out put (beginning to end) and send it paste it here?
rm -rf build/
git pull
git submodule update --init --recursive
./eosio_build.sh

**Comment by giniz** [comment]
hi @pacificcode, I've just run those commands and here 's the log file
[eosio_build.sh.log](https://github.com/EOSIO/eos/files/1981958/eosio_build.sh.log)

**Comment by pacificcode** [comment]
@giniz Im not sure what to make of this. CMAKE should be writing its build files to your eos/build directory (which is why you were getting the error "make: *** No targets specified and no makefile found."). I would recommend removing you current clone of the EOS.IO repo and do a clean clone and 
try again.

**Comment by giniz** [comment]
thank @pacificcode , remove and re-clone do the job.
