### ISSUE TITLE
Update table struc return an error when trying to retrieve the table

### ISSUE THREAD

**Issue by baothy** [EOSIO/eos#2760]
After updating the table by adding a new string field and pushing it to the blockchain, the table cannot be retrieved.

Here is the error message:

$ cleos get table bao bao tasks
1324670ms thread-0   main.cpp:1763                 main                 ] Failed with error: Out of Range (8)
get datastream of length 28 over by 1

**Comment by taokayan** [comment]
Currently we don't support updating the struct on the fly. It will result in serialisation issue of the old data stream. However you can create another table instead. Please ask support@block.one for more details.

**Comment by ChristianDunst** [comment]
Whenever you update the structure of a table, you will need to delete the old table and create a new one in order to avoid inconsistencies.
