### ISSUE TITLE
Eliminate 3rd party tools from code coverage report

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2766]
The code coverage report currently covers all of the 3rd party tools that we use which adds noise visually to the reports that we have to sift out.  The code coverage report should focus on our code only. Eliminating the boost and wasm related directories alone would get us much of the way to our goal.  The directories that are important for us are libraries/chain and libraries/chainbase.  Once we have nodes fully running on slim we will pick up appbase, etc as well.

**Comment by heifner** [comment]
This is complete as can be seen in the latest code coverage report.
