### ISSUE TITLE
keosd usability improvements

### ISSUE THREAD

**Issue by heifner** [EOSIO/eos#2769]
- [x] wallet should indicate error if an attempt is made to unlock a locked wallet
- [x] wallet should auto lock after a default of 15 minutes

**Comment by spoonincode** [comment]
> wallet should auto lock after a default of 15 minutes

Kind of feel like this should be configurable (and default to 15 minutes)

**Comment by nsjames** [comment]
I agree with spoonincode. We added this functionality to Scatter and it proved immensly difficult to develop with until the ability to turn it off was added.

**Comment by nsjames** [comment]
Perfect
