### ISSUE TITLE
Create unit tests for uncovered areas of transaction.cpp

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2773]
Look at the code coverage report for transaction.cpp, note the uncovered code areas and add tests to cover those areas.

I suspect that _signed_transaction::sign_ and _template<size_t Limit> struct read_limiter_ are dead code and can be removed, but that needs to be verified.

**Comment by dhaneshvb** [comment]
>> I suspect that signed_transaction::sign and template<size_t Limit> struct read_limiter are dead code and can be removed, but that needs to be verified

Both these are referred by many parts of the code, especally the plug-ins like wallet, transaction tester plug in etc. Hence these functions need to be maintained

**Comment by dhaneshvb** [comment]
After going through the code, it seems all the major features of the transaction module is covered in various test cases

**Comment by taokayan** [comment]
Pull request https://github.com/EOSIO/eos/pull/3203 added.

**Comment by andriantolie** [comment]
#3203 is merged
