### ISSUE TITLE
Create unit tests for uncovered areas of fork_database.cpp

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2774]
Review the code coverage report for fork_database.cpp and create unit tests for the areas that are not currently covered.  The entire fork_database class needs to be covered.

**Comment by taokayan** [comment]
I've found a strange behaviour when adding my test case, please see #2835

**Comment by taokayan** [comment]
pull request #2872 created for fixing the confirmation in fork_database and adding unit test. Please review.
