### ISSUE TITLE
a suggestion about establish more strict correspondence between the public key and the account

### ISSUE THREAD

**Issue by durongzheng** [EOSIO/eos#2781]
Most blockchain applications, like bitcoin and ethernum, only need one public key when tagging the user address, so that the transfer can be completed. No matter in the exchange or in the wallet, enter the public key when you want to make a transaction.
And EOS introduces the account concept, the key pair is no longer the only sign that identifies the user, the account name is, the EOD transfer is from one account name to another account name. The account name is based on the base32 encoding, the number of the optional character set is 0-5, the lowercase letter of a-z, plus a ".", the length can not exceed 12. Although the number of combinations can be a lot, but it's more less than the number of public key addresses, and the possibility of repetition is too large. I reckon in the future, create account will often encounter the "account name has already existed" error. And it is not the same as the existing way of application of the existing purse, the transfer is not to copy the public key address, but to enter the name of the account, which is much different with other apps.
Let's imagine this scenario: for a new user of DAPP, he used to record only mnemonic words and keystore file, now he have to think about an unique account name.Recording is passive behavior while thinking is active behavior, and the two are very different.
Therefore, my suggestion is:
 1. establish a more strict correspondence between the account's owner permission and the public key, owner must own a new public key.
2. retain the public key as the user address identification mechanism, even if a public key has no account name, it can be used as a unique identification address to complete the transaction.

**Comment by learnforpractice** [comment]
Here is a reference wrote by BM

https://medium.com/@bytemaster/introducing-eosio-dawn-4-0-f738c552879 <https://medium.com/@bytemaster/introducing-eosio-dawn-4-0-f738c552879>
