### ISSUE TITLE
chain.get_block unknown_block_exception

### ISSUE THREAD

**Issue by solarzhong** [EOSIO/eos#2782]
Hello, I run a eos testnet with other 8 nodes.The testnet run 24 hours correctly.
But now I found the Irreversible Block Number is still the old number, but the Current Block Number still increase.

I found the log above.

1058863ms thread-0   chain_api_plugin.cpp:69       operator()           ] Exception encountered while processing chain.get_block: {"code":3110000,"name":"unknown_block_exception","message":"unknown block","stack":[{"context":{"level":"error","file":"chain_plugin.cpp","line":409,"method":"get_block","hostname":"","thread_name":"thread-0","timestamp":"2018-05-05T14:17:38.863"},"format":"Could not find block: ${block}","data":{"block":"198568"}}]}
1058878ms thread-0   chain_api_plugin.cpp:69       operator()           ] Exception encountered while processing chain.get_block: {"code":3110000,"name":"unknown_block_exception","message":"unknown block","stack":[{"context":{"level":"error","file":"chain_plugin.cpp","line":409,"method":"get_block","hostname":"","thread_name":"thread-0","timestamp":"2018-05-05T14:17:38.878"},"format":"Could not find block: ${block}","data":{"block":"198569"}}]}

How to fix it ?

**Comment by taokayan** [comment]
Please ask support@block.one

**Comment by andriantolie** [comment]
Do you still encounter the same issue on the latest code?

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
