### ISSUE TITLE
Error 3030000,transaction validation exception  at set contract

### ISSUE THREAD

**Issue by yekai1003** [EOSIO/eos#2783]
``` sh
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
!"unresolvable": env._ZN7mytoken8transferEyyN5eosio5assetENSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
``` 
How to find the specific cause of the error？

**Comment by tbfleming** [comment]
Unresolvable means your contract is missing a function. Paste the name (_ZN7mytoke...) into https://demangler.com/ to see what it is.

**Comment by lingyiliu016** [comment]
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
!"unresolvable": env.snprintf
when I paste the name (env.snprintf) into https://demangler.com/ 
this webpage display:
We didn't find any symbols to demangle in the input. Would you like to demangle something else?
env.snprintf

**Comment by taokayan** [comment]
Please use "print" api instead of snprintf. Ask support@block.one for more details.

**Comment by yekai1003** [comment]
Add option --contracts-console when run nodeos

**Comment by andriantolie** [comment]
Yes, you can't use snprintf. Please use eosio::print from the console API (eosiolib/print.hpp) instead

**Comment by mintzhao** [comment]
I have same issue. But Error is 3070000, but I'm not using print or snprintf at all.
I dont know why, drive me crazy.
whole error:

Publishing contract...
Error 3070000: WASM Exception
Error Details:
env.snprintf unresolveable
pending console output:
