### ISSUE TITLE
the Irreversible Block Number no longer increases

### ISSUE THREAD

**Issue by urbanvice** [EOSIO/eos#2784]
Hello, I run a eos testnet with other 8 nodes.The testnet run 24 hours correctly.
But now I found the Irreversible Block Number is still the old number, but the Current Block Number still increase. How can I fix this?
Here are the logs:
`3127490ms thread-0   chain_controller.cpp:176      push_block           ] push block #208722 from test1 2018-05-05T17:52:07.500  00032f52838e84dae1d2a6cc0ccfaa9f6c0caa853c566d14463859838a475b75 lib: 192727 success
3140028ms thread-0   fork_database.cpp:78          _push_block          ] Number of missed blocks: 24
3140028ms thread-0   chain_controller.cpp:1540     validate_block_heade ] head_block_time 2018-05-05T17:52:07.500, next_block 2018-05-05T17:52:20.000, block_interval 500
3140028ms thread-0   chain_controller.cpp:1542     validate_block_heade ] Did not produce block within block_interval 500ms, took 12500ms)
3140029ms thread-0   chain_controller.cpp:176      push_block           ] push block #208723 from test2 2018-05-05T17:52:20.000  00032f5397273a2581326c596229b75f4bcf54b5dcf96128d14ff5b8b38e6b5b lib: 192727 success
3140528ms thread-0   chain_controller.cpp:176      push_block           ] push block #208724 from test2 2018-05-05T17:52:20.500  00032f545bba33d084390a3d6a6f40f363171a58203311c6da283822db89928d lib: 192727 success
`

**Comment by urbanvice** [comment]
all 8 nodes are still producing blocks, current block number is increasing, but irreversible block number   no longer changes

**Comment by taokayan** [comment]
Please ask support@block.one

**Comment by andriantolie** [comment]
Is each node has one producer? Or is there a node with multiple producers? 
If you have 21 producers appointed in the blockchain, you will need 2/3 * 21 + 1 of it, which is 15 block producers producing before the irreversible block increases. Please try again with the new code and check how many producers are producing. If more than 2/3 * total producers are producing and you still see this issue please reopen this
