### ISSUE TITLE
Nodeos do not produce blocks

### ISSUE THREAD

**Issue by sidorovkirill** [EOSIO/eos#2785]
I builded nodeos as your been write in instructions. Also i set config file by guide. And after run i get following output

1833360ms thread-0   net_plugin.cpp:2797           plugin_initialize    ] Initialize net plugin
1833360ms thread-0   net_plugin.cpp:2818           plugin_initialize    ] host: 0.0.0.0 port: 9876
1833360ms thread-0   net_plugin.cpp:2890           plugin_initialize    ] my node_id is f91ae2cb2fff74bdd7c68014e42c3e3f3a4b21f80ffa4d16b38abfcedaaff33c
1833361ms thread-0   main.cpp:91                   main                 ] nodeos version c2869543
1833361ms thread-0   main.cpp:92                   main                 ] eosio root is /root/.local/share
1833391ms thread-0   chain_plugin.cpp:216          plugin_startup       ] starting chain in read/write mode
1833391ms thread-0   chain_plugin.cpp:221          plugin_startup       ] Blockchain started; head block is #0, genesis timestamp is 2018-03-01T12:00:00.000
1833391ms thread-0   producer_plugin.cpp:161       plugin_startup       ] producer plugin:  plugin_startup() begin
1833391ms thread-0   producer_plugin.cpp:166       plugin_startup       ] Launching block production for 1 producers.

*******************************
*                             *
*   ------ NEW CHAIN ------   *
*   -  Welcome to EOSIO!  -   *
*   -----------------------   *
*                             *
*******************************

Your genesis seems to have an old timestamp
Please consider using the --genesis-timestamp option to give your genesis a recent timestamp

1833391ms thread-0   producer_plugin.cpp:176       plugin_startup       ] producer plugin:  plugin_startup() end
1833391ms thread-0   http_plugin.cpp:285           plugin_startup       ] start listening for http requests
1833391ms thread-0   wallet_api_plugin.cpp:70      plugin_startup       ] starting wallet_api_plugin
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/create
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/get_public_keys
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/import_key
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/list_keys
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/list_wallets
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/lock
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/lock_all
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/open
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/set_timeout
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/sign_transaction
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/unlock
1833391ms thread-0   chain_api_plugin.cpp:62       plugin_startup       ] starting chain_api_plugin
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/abi_bin_to_json
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/abi_json_to_bin
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_account
1833391ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_block
1833392ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_code
1833392ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_currency_balance
1833392ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_currency_stats
1833392ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_info
1833392ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_required_keys
1833392ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_table_rows
1833392ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/push_block
1833392ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/push_transaction
1833392ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/push_transactions
1833392ms thread-0   net_plugin.cpp:2902           plugin_startup       ] starting listener, max clients is 25

But blocks do not produces at all. And nodeos behave yourself not like daemon. He blocked main process on server.  What i do wrong or what i don't do? Thanks!
System:
CentOS 7
kernel  2.6.32-042stab127.2

**Comment by bytemaster** [comment]
```
 ./nodeos -e --producer eosio --plugin eosio::producer_plugin
```

**Comment by sidorovkirill** [comment]
Oh, it's realy simply. Thanks!
