### ISSUE TITLE
/usr/local/include/eosiolib/types.h:7:10: fatal error: 'stdint.h' file not found on mac

### ISSUE THREAD

**Issue by itsmeprasanjit** [EOSIO/eos#2789]
`#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>
using namespace eosio;

class hello : public eosio::contract {
  public:
      using contract::contract;

      /// @abi action 
      void hi( account_name user ) {
         print( "Hello, ", name{user} );
      }
};

EOSIO_ABI( hello, (hi) )`

I have already run sudo make install in build
eosiocpp -o hello.wast hello.cpp
this gives me error of :
/usr/local/include/eosiolib/types.h:7:10: fatal error: 'stdint.h' file not found

**Comment by pacificcode** [comment]
@itsmeprasanjit 
find /usr -name stdint.h -print 2>/dev/null

**Comment by mylesshie** [comment]
do you solve this problem?

**Comment by Duffyxx** [comment]
I got the same problem when I use './eosiocpp -o hello.wast hello.cpp', then I change the command to 'eosiocpp -o hello.wast hello.cpp', success.

**Comment by qs-lll** [comment]
+1 same problem

**Comment by navcsdev** [comment]
+1 same problem

**Comment by sikeeoh** [comment]
+1 same problem

**Comment by CityOfStars** [comment]
I have a same issue and trying to solve it.
I found a `eosiolib` folder in `usr/local/include`, and I guess this is a default include path of `eosiocpp` the compiler. But my `stdint.h` file is in `usr/include` folder. I guess, `eosiocpp` can't see my default include path unlike cpp. 

In case of cpp, I can find the include path as `cpp -v` command, but `eosiocpp`  doesn't have it yet.(right?)
How can i change the default include path of `eosiocpp`?

**Comment by timwbodine** [comment]
This worked for me.  Just remember to change to backticks to quotes in the $EOSIO_INSTALL_DIR value.

**Comment by andriantolie** [comment]
@itsmeprasanjit do you still have this issue on latest version of eos? v1.1.0

**Comment by Di0niz** [comment]
This worked for me:

```bash
cd ~/eos/build
make install
```
and after that try to build smart contact.

**Comment by halsaphi** [comment]
Please try using the eosio.cdt 1.3.2

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
