### ISSUE TITLE
Test Network Checklist

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#279]
This issue is reserved for tracking the progress and release of the first public test network.  

#### Requirements Alpha Release:
1. CLI Wallet with Signature Generation . (UNDER DEV)
2. Relatively Accurate Snapshot of ERC20 token used as genesis (NEED VERIFICATION)
3. 5 independent nodes hosted in different AWS regions producing blocks of 4 producers per node
4. Enough stake voting for our top 20 producers that others cannot vote them out
5. 4 public seed nodes (which hide block producer nodes from public) 
6. 4 public API nodes with reverse proxy load balancing 
7. QA stress testing of this configuration prior to release (make sure P2P code works under stress)
8. Contract Publishing, Invocation, and State querying 
9. Installers (Cmake and linux packages)
10. QA on documentation 

### Not Implemented until Beta Release:
1. Merkle Hashing 
2. WASM C API is incomplete and may be expanded upon or revised
3. multi-threaded scheduler (using single threaded for now)
4. bandwidth rate limiting and storage limits
5. Native contracts associated with:
       a. constitution
       b. community benefit contracts
       c. upgrade consensus 
       d. hacked account recovery
       f. producer override of contracts

**Comment by heifner** [comment]
This has been broken down into individual issues. Closing this meta-task.
