### ISSUE TITLE
Update permission usage so get_permission_last_used API works properly

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2794]
In the transition from master to slim, controller left out `update_permission_usage`. This means that a `permission_usage_object` is never created in the current slim code and `postrecovery` just uses the account creation date as the last used time. Effectively the current state of the slim code would mean that after 30 days since the time an account was created, the only safeguard against lost password recovery is a 7 day delay.

The slim code should be fixed to track permission usage. Clearly, our unit tests on this are not very good, since recovery_tests are currently passing with the faulty code; so that needs to be improved as well. We should also just review the whole recovery mechanism altogether given all the changes we have recently made to deferred transactions, authorization checks and delays.

**Comment by bytemaster** [comment]
This test needs to be updated to validate that the new intrinsics get_permission_last_used() work properly and that we properly set the permission used timestamps.  

We removed the native 'postrecovery' messages in favor of WASM based implementations.

**Comment by gleehokie** [comment]
@arhag and @brianjohnson5972 please coordinate, I think you are both working on this

**Comment by brianjohnson5972** [comment]
If @arhag is working this, then please remove me and assign yourself.  @heifner pointed me to this since it wasn't marked as assigned.

**Comment by arhag** [comment]
PR #2893 fixes the issue of the last used time of permissions not being updated. With that fix and the `get_permission_last_used` intrinsic, contracts have enough tools to be able to implement account recovery. We still need to reimplement account recovery as a WASM contract and of course add proper tests for it, but that is a separate issue (#2894). So I am closing this one.
