### ISSUE TITLE
ERROR: Version mismatch: file ./docker-compose.yml specifies version 3.0

### ISSUE THREAD

**Issue by kenorb** [EOSIO/eos#2799]
Page: [Change default configuration](https://github.com/EOSIO/eos/wiki/Local-Environment#change-default-configuration)

Command: `docker-compose down`

> ERROR: Version mismatch: file ./docker-compose.yml specifies version 3.0 but extension file ./docker-compose.override.yml uses version 2.0

It's suggested to use `version: "2"`, but `docker-compose.yml` uses 3.0. The wiki page should be updated to use 3.0.

**Comment by ChristianDunst** [comment]
Thank you very much, we will look into this and update the documentation if needed
