### ISSUE TITLE
exchange-tutorial-python/README.md needs improvements

### ISSUE THREAD

**Issue by kenorb** [EOSIO/eos#2802]
Currently [`exchange-tutorial-python/README.md`](https://github.com/EOSIO/eos/blob/slim/programs/exchange-tutorial-python/README.md) got some formatting issues.

For example in section _Create account steps_ all commands are combined together which are referring to the specific points in the index. Or `cleos create key` is repeated twice, but instead should refer to the mentioned points. And `<private key from step 1>` and `<private key from step 2>` is not clear which steps it refers to.

**Comment by gleehokie** [comment]
@rbw3821 please address these comments when you move this tutorial into the wiki.

**Comment by jgiszczak** [comment]
OBE.  Obsolete tutorial removed.
