### ISSUE TITLE
transfer error

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#2806]
Error 3040002: Invalid Action Arguments
Ensure that your arguments follow the contract abi!
You can check the contract's abi by using 'cleos get code' command.
Error Details:
'{"from":"eosio","to":"eos.beijing","quantity":"10.0000 EOS","memo":"EOS"}' is invalid args for action 'transfer' code 'eosio'
Invalid cast from object_type to string

**Comment by imoonstal** [comment]
cleos push action YOUR_ACCOUNT transfer '["FROM_ACC","TO_ACC","0.1000 EOS",""]' -p YOUR_ACCOUNT

**Comment by yankunsam** [comment]
@imoonstal  "FROM_ACC"? The change on slim branch?

**Comment by imoonstal** [comment]
a account name.............

**Comment by imoonstal** [comment]
you must use contract named "eosio.system"

**Comment by taokayan** [comment]
Please use code name "eosio.token" instead of "eosio"
