### ISSUE TITLE
Fair Delegation Improvement Proposal

### ISSUE THREAD

**Issue by enriquejr99** [EOSIO/eos#2815]
### Introduction
It's logical that a BP which has great latency and RAM will receive more votes that some other BP with lower specs. However, in order to improve decentralisation, I suggest limiting this factor when reaching very high standard specs.

### Problem
Currently, if a node has better specs that some BP, the BP will be removed and replaced for that higher power node as it will not be able to get as many votes. This is fine, until we reach the "very fast" point, because this stage is enterprise level. At this stage, centralised entities are able to create large warehouses with supercomputers and become block producers immediately because they are much more powerful.

### Solution
What we can do is, if RAM > X, RAM = X. This doesn't mean we will be limiting the RAM of the node to X, it just means that we will pretend the RAM is X when calculating which node is better. So anyone with a powerful computer can compete with the enterprise level supercomputers.

For example, if a node has 0.5X RAM and some other node has X RAM, we will replace the 0.5X RAM node for the X RAM node by using votes. However, if another node comes in with some 4X RAM supercomputer, we will treat it as an X RAM node. So it will only be able to replace the current BP if the current BP misbehaves and it casts more votes than other X RAM nodes.

### Conclusion
I believe this is fair, as there's a point in which we really don't need higher specs. I truly don't think we need supercomputers working as BP for the network to work properly and this way we allow more nodes to compete for the BP position.

Note: In the example I used RAM, but it should be all specs which are currently considered when selecting a BP such as latency.

**Comment by gleehokie** [comment]
@enriquejr99 I think you misunderstand how BPs are selected, they are **not** picked by software based on their technical characteristics, the are voted on by the token holders for the chain.
