### ISSUE TITLE
p2p assemble a block based on previously shared transactions and summary info

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#282]
This is a TODO in the p2p net plugin code. Currently a complete block is shared when available. Ideally just a block summary will be shared and the peers should be able to reconstruct the block using known transactions and the "block summary." I'm not entirely sure what a block summary is, also are the signed transactions sufficient or are generated transactions necessary, in which case they need to be shared.

**Comment by nathanhourt** [comment]
I think it should not be necessary to share generated transactions. Full nodes will generate them in the course of processing the normal transactions, so there's no need to send them over the network.

**Comment by nathanhourt** [comment]
Perhaps block summary should be `block_header`?

**Comment by pmesnier** [comment]
This issue is really part of #291.

**Comment by pmesnier** [comment]
This is one of the TODO's identified as necessary for efficient p2p networking.

**Comment by pmesnier** [comment]
Part of the P2P protocol involves sharing SignedTransactions as they occur. However, signed blocks contain processed transactions containing MessageOutput lists. 

I'm not sure the best way to pass the message output content. Should I carry it in the summary along with the transaction ID? Or pass them separately? Ignore them? Generate them anew on the receiving nodes? Something else?

**Comment by nathanhourt** [comment]
Ignore them -- the P2P layer doesn't need to deal with trx outputs. Everything on the P2P network is capable of generating its own trx outputs.

**Comment by pmesnier** [comment]
Very well. That's the easiest solution.

**Comment by pmesnier** [comment]
Holding on this issue. I've got the implementation done but I need to finish last phases of initial syncing, which is fetching blocks above the last irreversible, and then retrieving any unblocked signed transactions so that when block summaries are received the block can be made whole.

**Comment by pmesnier** [comment]
PR #543 addresses this issue
