### ISSUE TITLE
Can't sign transactions with RPC

### ISSUE THREAD

**Issue by artyemk** [EOSIO/eos#2824]
I need to sign a transaction from python using RPC interface. It requires a signature of an account. So I do: 
`requests.post("http://localhost:8889/v1/wallet/sign_transaction", json=json.loads(data)).text` 

Where data looks like this(found this json params on github because RPC wiki seems to be outdated): 
`{
    "signatures": [""],
    "compression": "none",
    "context_free_data": [],
    "transaction": {
    "region": 0,
    "ref_block_num": "%s",
    "ref_block_prefix": "%s",
    "expiration": "%s",
    "max_net_usage_words": 0,
    "max_kcpu_usage": 0,
    "delay_sec": 0,
    "context_free_actions": [],
    "actions": [{
    "account": "user",
    "name": "summ",
    "authorization": [{
    "actor": "tester",
    "permission": "active"
    }],
    "data": "05000000000000000600000000000000"
    }]
    }
    }`

Block params comes from http://localhost:8888/v1/chain/get_info"
Output of this command is 403 HTTP error. I also tried to unlock my wallet with 
`s = '{"default":"PW5KFWYKqvt63d4iNvedfDEPVZL227D3RQ1zpVFzuUwhMAJmRAYyX"}'
requests.post("http://localhost:8889/v1/wallet/unlock", json=json.loads(s))` 
Same 403 error. What do I wrong?

**Comment by woshidama323** [comment]
hi, the issue has been corrected ? could you help to tell how to fix that ?
