### ISSUE TITLE
Error when deploy contract

### ISSUE THREAD

**Issue by quocle108** [EOSIO/eos#2838]
I tried to deploy contract follow [this link](https://github.com/EOSIO/eos/blob/09affc02fcc30fe7f04150087d4411b786775045/TUTORIAL.md) but there is a missing file. I also check project folder, there is no file eosio.token.wast. I builded on MacOS
`cleos set contract eosio.token contracts/eosio.token -p eosio.token`

> Reading WAST/WASM from contracts/eosio.token/eosio.token.wast...
> 2540777ms thread-0   main.cpp:1763                 main                 ] Failed with error: Assert Exception (10)
> !wast.empty(): no wast file found contracts/eosio.token/eosio.token.wast

**Comment by LucienLau** [comment]
I try it, but there's a error:
`$ eosiocpp -o contracts/eosio.token/eosio.token.wast contracts/eosio.token/eosio.token.cpp`
>contracts/eosio.token/eosio.token.cpp:6:10: fatal error: 'eosio.token/eosio.token.hpp' file not found
>#include <eosio.token/eosio.token.hpp>
>        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>1 error generated.

**Comment by quocle108** [comment]
@LucienLau : try use **#include <eosio.token.hpp>**

**Comment by LucienLau** [comment]
@quocle108 Thanks a lot and i solved it by this way.

**Comment by quoxoft** [comment]
@blockchain-expert 
You should generated to .wast first, and then deploy the contract.
Try below command to get .wast file

> eosiocpp -o contracts/eosio.token/eosio.token.wast contracts/eosio.token/eosio.token.cpp

**Comment by ItsLeeOwen** [comment]
Is anyone able to set custom contracts with eos running in a docker container?  I've built my .abi & .wast files in contracts/mycontract, and mounted the contracts dir without success.

```sh
cleos set contract myacct /opt/eosio/bin/data-dir/contracts/mycontract -p myacct
!wast.empty(): no wast file found /opt/eosio/bin/data-dir/contracts/mycontract.wast
```

**Comment by quocle108** [comment]
@ItsLeeOwen 
I also use Docker.
Have you try to build .wast file first?

**Comment by ItsLeeOwen** [comment]
@quocle108   yes they were built, my issue was that the docker-compose cleos alias was executing service "keosd" but I was only mounting my contracts directory to the "nodeosd" service.

**Comment by quocle108** [comment]
I’ve build a custom contract and there are no issues. Here is what i did:
1. Copy your contract to contracts folder
2. From docker folder: run below command
cleos set contract contractname ../contracts/your_contract -p contractname

**Comment by tanhuiya** [comment]
@ItsLeeOwen  @quocle108 
I have this problem too.
I have deployed a sample contract tic_toc_toa yesterday.
But now I can't deploy anymore contracts. issue me like below:

```
cleos set contract usertodo ../build/contracts/eosio.token -p usertodo
Reading WAST/WASM from ../build/contracts/eosio.token/eosio.token.wast...
2612538ms thread-0   main.cpp:2712                 main                 ] Failed with error: Assert Exception (10)
!wast.empty(): no wast file found ../build/contracts/eosio.token/eosio.token.wast
```

**Comment by quocle108** [comment]
@tanhuiya,

I also have the same issue. Sometime it works, sometime it doesn’t when try to deploy

**Comment by andriantolie** [comment]
Do you use docker? If you use docker, you need to specify the path RELATIVE to your docker container root folder.

**Comment by brianjohnson5972** [comment]
Since this issue has been silent for a while, it is being closed.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
