### ISSUE TITLE
abi_json_to_bin and abi_bin_to_json wrong way around

### ISSUE THREAD

**Issue by Fletch153** [EOSIO/eos#2851]
These endpoints seem to be the wrong way round. The json_to_bin requires the binary arguments and the bin_to_json requires the json arg map.

**Comment by heifner** [comment]
abi_json_to_bin takes json and return binary.
abi_bin_toJson takes binary and return json.

Not sure why you think it is reversed.

**Comment by Fletch153** [comment]
curl  http://127.0.0.1:8888/v1/chain/abi_bin_to_json -X POST -d '{"code":"currency", "action":"transfer", "binargs":"000000008093dd74000000000094dd74e803000000000000"}'

this returns the following error: "50800{"code":500,"message":"Internal Service Error","error":{"code":8,"name":"out_of_range_exception","what":"Out of Range","details":[{"message":"read datastream of length 24 over by 1","file":"datastream.cpp","line_number":6,"method":"throw_datastream_range_error"},{"message":"error unpacking uint64_t","file":"raw.hpp","line_number":601,"method":"unpack"},{"message":"Error unpacking field m_value","file":"raw.hpp","line_number":360,"method":"operator()"},{"message":"error unpacking eosio::chain::symbol","file":"raw.hpp","line_number":601,"method":"unpack"},{"message":"Error unpacking field sym","file":"raw.hpp","line_number":360,"method":"operator()"},{"message":"error unpacking eosio::chain::asset","file":"raw.hpp","line_number":601,"method":"unpack"}]}}
"

as "
curl  http://10.0.221.12:8888/v1/chain/abi_json_to_bin -X POST -d '{"code":"currency", "action":"transfer", "binargs":"000000008093dd74000000000094dd74e803000000000000"}'
" works fine, yet you're passing in a binary argument.

**Comment by heifner** [comment]
Define "works fine". What is returned?

**Comment by Fletch153** [comment]
My apologies, i was a bit to hasty to create an issue. It's working as expected.
