### ISSUE TITLE
Block digest validation in other languages

### ISSUE THREAD

**Issue by toonsevrin** [EOSIO/eos#2860]
Can this [block digest generation](https://github.com/EOSIO/eos/blob/master/libraries/chain/block.cpp#L14) be written in other languages then C(++)?

If so: Can a language-neutral format for the digest message be documented?

If not: This would be a very undesireable lock-in: EOS blocks will not be able to be validated on other blockchains like ethereum. Perhaps this hash function should be refined in a more language-neutral way.

**Comment by jgiszczak** [comment]
The block digest in EOS.IO is SHA256 as implemented by OpenSSL.  It is fully documented in FIPS PUB 180-2, published by the US NIST, and implemented in many languages.
