### ISSUE TITLE
delegatebw error

### ISSUE THREAD

**Issue by urbanvice** [EOSIO/eos#2862]
following is the abi for delegatebw:
![image](https://user-images.githubusercontent.com/24699417/39792593-f368a53e-5373-11e8-817c-832a0bd266ff.png)
but while I run the command，an error occurred
![image](https://user-images.githubusercontent.com/24699417/39792636-3d71fb1c-5374-11e8-9f39-7b0db9130a1e.png)

**Comment by bytemaster** [comment]
That code on master is deprecated.  Slim branch has updated abi.
