### ISSUE TITLE
fatal error: 'stdint.h' file not found

### ISSUE THREAD

**Issue by mylesshie** [EOSIO/eos#2870]
when I want get a wast file, give me an error
```
./eosiocpp -o currency.wast ./currency/currency.cpp
In file included from ./currency/currency.cpp:5:
In file included from ./currency/currency.hpp:5:
In file included from /usr/local/include/eosiolib/eosio.hpp:6:
In file included from /usr/local/include/eosiolib/types.hpp:6:
/usr/local/include/eosiolib/types.h:7:10: fatal error: 'stdint.h' file not found
#include <stdint.h>
         ^~~~~~~~~~
```

How can I solve it?  I have not find the answer in issues

**Comment by heifner** [comment]
currency.cpp no longer exists on the `slim` branch, soon to be master. Also this has been fixed on `slim`.

**Comment by mylesshie** [comment]
It's not the currency.cpp problem,I use this command
`eosiocpp -n ${contract}`
create the currency.cpp file, but when I want compile the wast file give me the error?

**Comment by heifner** [comment]
Did you try the `slim` branch?

**Comment by luoxiaohui** [comment]
+1
