### ISSUE TITLE
Is there a RPC API to find all transactions in a given block?

### ISSUE THREAD

**Issue by kristieguo** [EOSIO/eos#2873]
Hi, I am using API get_transactions to query all transactions for a given account:

I was wondering if there is a rpc api to find all transactions in a given block? Thanks.

**Comment by bytemaster** [comment]
Not currently, but the history plugin could be modified to support this.

**Comment by kristieguo** [comment]
@bytemaster OK thank you. I tried to use get_account(account_name) to query the balance for a given account, however the response I got is as below. "eos_balance", "staked_balance" and "unstaking_balance" no longer included in this API?

{  
   "account_name":"tester",
   "permissions":[  
      {  
         "perm_name":"active",
         "parent":"owner",
         "required_auth":{  
            "threshold":1,
            "keys":[  
               {  
                  "key":"EOS7icMoRSRVnQz1NoCuP5e8BKxTfnYDZXqF3kqLtb3UkidXD4R2v",
                  "weight":1
               }
            ],
            "accounts":[  

            ]
         }
      },
      {  
         "perm_name":"owner",
         "parent":"",
         "required_auth":{  
            "threshold":1,
            "keys":[  
               {  
                  "key":"EOS7icMoRSRVnQz1NoCuP5e8BKxTfnYDZXqF3kqLtb3UkidXD4R2v",
                  "weight":1
               }
            ],
            "accounts":[  

            ]
         }
      }
   ]
}
