### ISSUE TITLE
cleos get accounts gets error "Account History API plugin is not enabled"

### ISSUE THREAD

**Issue by cj-oci** [EOSIO/eos#2876]
"cleos get accounts" returns error "Error 3110003: Missing Account History API Plugin".

config.ini has history_plugin and history_api_plugin enabled. Attached test will reproduce issue
  tests/nodeos_run_test.py -v --only-bios --dont-kill

[https://app.zenhub.com/files/87335980/dbe4b2f1-f13d-4f36-bac7-a2230864ecee/download](https://app.zenhub.com/files/87335980/dbe4b2f1-f13d-4f36-bac7-a2230864ecee/download)

Launcher patch for adding history_plugin:
+++ b/programs/eosio-launcher/main.cpp
@@ -1009,6 +1009,7 @@ launcher_def::write_config_file (tn_node_def &node) {
     cfg << "plugin = eosio::mongo_db_plugin\n";
   }
   cfg << "plugin = eosio::chain_api_plugin\n"
+      << "plugin = eosio::history_plugin\n"
       << "plugin = eosio::history_api_plugin\n";
   cfg.close();
 }

**Comment by bytemaster** [comment]
Account History Plugin is the old and defunct plugin and has a distinct endpoint / different API from History Plugin.

**Comment by bytemaster** [comment]
The current history plugin does not currently generate or populate a key-cache to answer the question "what accounts are controlled by my keys".

**Comment by tbfleming** [comment]
Yes

**Comment by tbfleming** [comment]
Fixed in #3253
