### ISSUE TITLE
allow system contract to modify rate limiting inputs

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2877]
related to #2777 

# Description

The system contract should be able to set more parameters that tweak the resource rate limiting math.
A non-exhaustive list of these parameters:
 - [ ] the cpu_usage window size used to track accounts
 - [ ] the net_usage window size used to track accounts
 - [ ] the cpu_usage window size used to track block congestion
 - [ ] the rates of expansion and decay for the virtual block limits for cpu_usage
 - [ ] the net_usage window size used to track block congestion
 - [ ] the rates of expansion and decay for the virtual block limits for net_usage

Care should be taken to ensure that setting these values does not create numeric limit issues.

A non-exhaustive list of potential issues (that should be checked as part of ATC)
 - [ ] new cpu/net windows for accounts allows for an account to consume the block maximum cpu/net usage for the entire window without overflowing our higher precision tracking values `*_ex`
 - [ ] the rates of expansion and decay do not cause overflow in the processing of elastic virtual limits

**Comment by brianjohnson5972** [comment]
@wanderingbort Is this still a desired change?  If I don't get a response I will presume that it is not.

**Comment by brianjohnson5972** [comment]
No longer a desired change.
