### ISSUE TITLE
Rename "EOS" symbol in eosio.system to "SYS" 

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#2888]

**Comment by hokiecsgrad** [comment]
Tutorials need to be updated to account for the new token name.

**Comment by hokiecsgrad** [comment]
There has been some recent discussion to suggest that the token name should be "NOTEOS".

**Comment by gleehokie** [comment]
I confirmed with Dan today that we want the token to be called "SYS" instead of "EOS".

**Comment by macleanliu** [comment]
if the symbol change to sys, can cause scam make fake "EOS" token? If so, it can be dangerous。

**Comment by kesar** [comment]
> if the symbol change to sys, can cause scam make fake "EOS" token? If so, it can be dangerous。

No, its just for development.

**Comment by kaidiren** [comment]
this issue could be closed
