### ISSUE TITLE
Dockerfile does not have to clone repo

### ISSUE THREAD

**Issue by toonsevrin** [EOSIO/eos#289]
Right now the Dockerfile clones in the git repo through a RUN call. Replacing this with a COPY will not only marginally speed up the build, it will also enable proper caching of the build tools. I think right now the if you don't use --no-cache the build will just skip the whole building process due to RUNs being cached by Docker.

With this we will also be able to build different branches.

The dockerfile will be moved to the Dockerfile to the project root, because `COPY ../ <dest>` is otherwise out of the build context.

**Comment by toonsevrin** [comment]
I'll work on this, though @peterwillcn may have had a reason to use RUN clone instead of COPY.

**Comment by toonsevrin** [comment]
CI scripts may require to do a `git submodule update --init --recursive` to fetch recursively before building the docker image due to this.

**Comment by toonsevrin** [comment]
I have no idea how this build could fail.

**Comment by peterwillcn** [comment]
1.Using local code saves considerable time, but does't guarantee that your code stays up-to-date
2.Following the official master branch code takes a long time to download, depending on the network speed.

**Comment by peterwillcn** [comment]
> The dockerfile will be moved to the Dockerfile to the project root, because COPY ../ <dest> is otherwise out of the build context.

   **-f Docker/Dockerfile** Can solve your problems
 `docker build -t eosio/eos -f Docker/Dockerfile . `

So, dockerfile will be restored from the root directory to the docker directory.

**Comment by toonsevrin** [comment]
@peterwillcn You're completely right, I didn't think of this 👍
