### ISSUE TITLE
Update Billing to Microseconds

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#2898]
transaction_header::max_kcpu_usage =>  max_cpu_usage_ms 

Change the type from varint to uint8_t which allows us to express the range of 1 to 255ms max billing or unlimited (producer defined) billing.

**Comment by bytemaster** [comment]
This has mostly been implemented but needs some extensive review and improvement in corner cases.

**Comment by arhag** [comment]
This issue has been resolved by PR #2947. Further work on this topic is covered in issue #2960.
