### ISSUE TITLE
Error when build eosio.token 

### ISSUE THREAD

**Issue by LucienLau** [EOSIO/eos#2902]
I want to build eosio.token,and i build by this command:
`$ eosiocpp -o contracts/eosio.token/eosio.token.wast contracts/eosio.token/eosio.token.cpp`
but there's a error(eosio.token.hpp exist actually):
>contracts/eosio.token/eosio.token.cpp:6:10: fatal error: 'eosio.token/eosio.token.hpp' file not found
>#include <eosio.token/eosio.token.hpp>
>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>1 error generated.
Can someone help me with that?

**Comment by enriquejr99** [comment]
Change that line to:

`#include <eosio.token.hpp>`

**Comment by LucienLau** [comment]
Thank you very much,i build it successfully.

**Comment by KePeng1019** [comment]
i change to #include <eosio.token.hpp>, but still get error: src/eosio.token.cpp:5:10: fatal error: 'eosio.token.hpp' file not found
#include <eosio.token.hpp>

**Comment by zky001** [comment]
> i change to #include <eosio.token.hpp>, but still get error:
> 
> ```
>  src/eosio.token.cpp:5:10: fatal error: 'eosio.token.hpp' file not found
> #include <eosio.token.hpp>
> ```

'eosio.token.hpp' file not found,you can search this file in your file system.

**Comment by justinchou** [comment]
I solve this by move the file `include/eosio.token/eosio.token.hpp` to `src` folder and change the `#include <eosio.token/eosio.token.hpp>` to `#include "eosio.token.hpp"`

**Comment by unclewangshushu** [comment]
> I solve this by move the file `include/eosio.token/eosio.token.hpp` to `src` folder and change the `#include <eosio.token/eosio.token.hpp>` to `#include "eosio.token.hpp"`

It works, thank you
