### ISSUE TITLE
What is the database file size and how do i increase  / decrease it?

### ISSUE THREAD

**Issue by andrewfam** [EOSIO/eos#2909]
269178ms thread-0   chain_plugin.cpp:225          plugin_startup       ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: could not grow database file to requested size.
rethrow could not grow database file to requested size.:
    {"my->genesis_file.generic_string()":"/Users/andrewfam/Library/Application Support/eosio/nodeos/config/genesis.json","what":"could not grow database file to requested size."}
    thread-0  chain_plugin.cpp:225 plugin_startup
269178ms thread-0   chain_plugin.cpp:225          plugin_startup       ] my->genesis_file.generic_string(): /Users/andrewfam/Library/Application Support/eosio/nodeos/config/genesis.json
269179ms thread-0   main.cpp:96                   main                 ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: could not grow database file to requested size.
rethrow could not grow database file to requested size.:
    {"my->genesis_file.generic_string()":"/Users/andrewfam/Library/Application Support/eosio/nodeos/config/genesis.json","what":"could not grow database file to requested size."}
    thread-0  chain_plugin.cpp:225 plugin_startup

**Comment by jgiszczak** [comment]
Default backing store for the in-memory database is 32 GB.  Pass `--shared-memory-size-mb 1024` to reduce that to 1 GB, or select any size you prefer.  Be aware that the number of transactions you can process before your `nodeos` fails is limited by that allocation in the current implementation.
