### ISSUE TITLE
Api does not support random_shuffle?

### ISSUE THREAD

**Issue by xiangxn** [EOSIO/eos#2910]
Api does not support random_shuffle?

**Comment by jgiszczak** [comment]
No pseudo-random results with arbitrary seeds are allowed within contracts.  Contract execution must be deterministic, so it is repeatable by all verifying nodes.  Pseudo-randomness with pre-determined seeds is allowed.  See the `dice` contract for an example.

**Comment by xiangxn** [comment]
Random_shuffle can set seed
