### ISSUE TITLE
Is std::set not allowed in Smart Contract tables?

### ISSUE THREAD

**Issue by leordev** [EOSIO/eos#2912]
I have a table which has a list of `account_name` called `members`.

It was a `std::vector` but I changed to `std::set` so I don't need to handle duplication issues and also for an easy finder.

Here it is: https://github.com/leordev/eos-play/blob/d2aa51bb6406d1a02a8c892d392f72b155b2487f/mydao/mydao.cpp#L109

The problem is that after this change I receive this error on the compilation:
```
clang-4.0: error: unable to execute command: Illegal instruction: 4
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.1 (https://github.com/llvm-mirror/clang.git 3c8961bedc65c9a15cbe67a2ef385a0938f7cfef) (https://github.com/llvm-mirror/llvm.git c8fccc53ed66d505898f8850bcc690c977a7c9a7)
Target: wasm32
Thread model: posix
InstalledDir: /usr/local/wasm/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-4.0: note: diagnostic msg: /var/folders/fx/57r2j5ds4vb2ggsxrwbcbt3r0000gn/T/mydao-4491c5.cpp
clang-4.0: note: diagnostic msg: /var/folders/fx/57r2j5ds4vb2ggsxrwbcbt3r0000gn/T/mydao-4491c5.sh
clang-4.0: note: diagnostic msg: /var/folders/fx/57r2j5ds4vb2ggsxrwbcbt3r0000gn/T/mydao-4491c5.crash
clang-4.0: note: diagnostic msg:

********************
```

So my question is if I should never use sets for that and stick with vector and keep controlling the possible duplications.

The bug reports are huge like 600 lines, 23k lines... Not sure if you want me to paste it here.

**Comment by andriantolie** [comment]
I tried with the latest eosio (v1.1.0) and the compilation error is not there anymore. However, as far as I know only vector, struct, class, or a built-in type is supported by the abi_serializer
