### ISSUE TITLE
current RAM pricing model allows any user to make instant profit

### ISSUE THREAD

**Issue by taokayan** [EOSIO/eos#2914]
RAM price will exponentially increase as the supply goes down. This allow any user to make instant profit by repeating the following steps in one go:

1. buy x bytes of RAM at price p1
2. sell x bytes of RAM at price p2

since the RAM price is evaluated before the amount change, p2 will be always bigger than p1. A user can always make profit out of it.

"Changing the pricing evaluation formula at the selling time by increasing the supply by x first" still won't able to solve the issue, because the user can get rid of it by doing:

1. buy x bytes of RAM at price p1
2. sell x/2 bytes of RAM  at price p2
3. sell x/2 bytes of RAM at price p1

Possible workaround:
Divide the total number of RAM into n buckets, evaluate the price for each bucket. For buying/selling, iterate each relevant bucket and calculate the sum of the price of each bucket. But this will be too time consuming.

**Comment by taokayan** [comment]
Pull request https://github.com/EOSIO/eos/pull/2915 created for this. To reproduce the issue, please uncomment the following 2 lines:

   //BOOST_REQUIRE_EQUAL( success(), buyrambytes( "alice", "alice", 20000000 ) );
   //BOOST_REQUIRE_EQUAL( success(), sellram( "alice", 20000000 ) );

**Comment by bytemaster** [comment]
Added a unit test that would buy/sell a small amount of RAM and a large
    amount of RAM.  This test showed unexpected behavior due to attempting
    to sell over 2^32 RAM.  I updated the sellram action to enable selling
    more than 2^32 bytes at once.

    Test results show that for both large and small quantities, the user
    losses a small amount of tokens and does not profit.
