### ISSUE TITLE
cleos throws non fatal errors

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2919]
As of  bf0db378e every command I send to cleos seems to throw:

```
455622ms thread-0   main.cpp:2202                 main                 ] Failed with error: Key Not Found (6)
Key cpu_usage

```

This appears non-fatal as the side-effects of whatever command I issue seem to actually happen.

**Comment by wanderingbort** [comment]
seems this was introduced by c1aa803957f8a9098fab60af328da77fc0459e4b

**Comment by heifner** [comment]
Verified error not reported with #2920.
