### ISSUE TITLE
Using non-default wallet port causes cleos errors

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2928]
setting a --wallet-url to anything other than http://localhost:8888 throws a warning even though the wallet is successfully connected to.  I am not sure what would happen if it could have launched `keosd` but it didn't find it for me.

```
No wallet service listening on 127.0.0.1: 8888. Cannot automatically start keosd because keosd was not found.
```

for reference, my command line was:
```
cleos --url http://localhost:8000 --wallet-url http://localhost:8000
```

and there was an RPC/wallet daemon on port 8000 at the time (which is why it succeeded)

**Comment by narauni** [comment]
I would not stake many EOS tokens that the current solution solves the issue fully (i.e. that the specification of a non-default url would work), but it should solve the issue that "keosd was not found".
