### ISSUE TITLE
cleos get account not working

### ISSUE THREAD

**Issue by cj-oci** [EOSIO/eos#2934]
This does not fail immediately after account creation. However after some account transactions it starts failing. To reproduce use attached test:
  tests/nodeos_run_test.py -v --dont-kill

cleos get account initb
2471418ms thread-0   main.cpp:2222                 main                 ] Failed with error: Out of Range (8)
read datastream of length 18 over by -1
error unpacking uint64_t

This occurs in voter_info construction (chain_plugin.cpp:572)[https://app.zenhub.com/files/87335980/c713a5d4-be84-4090-9eaf-af682762a8ca/download](https://app.zenhub.com/files/87335980/c713a5d4-be84-4090-9eaf-af682762a8ca/download)

**Comment by moskvanaft** [comment]
@cj-oci , I tried to reproduce it. But it failed in other place (I don't know before or after the original place)
```
  Cluster bootstrap done.
  Parsing config file etc/eosio/node_bios/config.ini
   Found producer : eosio
  Parsing config file etc/eosio/node_00/config.ini
   Found producer : defproducera
   Found producer : defproducerb
   Found producer : defproducerc
   Found producer : defproducerd
   Found producer : defproducere
   Found producer : defproducerf
   Found producer : defproducerg
   Found producer : defproducerh
   Found producer : defproduceri
   Found producer : defproducerj
   Found producer : defproducerk
   Found producer : defproducerl
   Found producer : defproducerm
   Found producer : defproducern
   Found producer : defproducero
   Found producer : defproducerp
   Found producer : defproducerq
   Found producer : defproducerr
   Found producer : defproducers
   Found producer : defproducert
   Found producer : defproduceru
Test failed.
Traceback (most recent call last):
  File "./tests/nodeos_run_test.py", line 97, in <module>
    if cluster.launch(prodCount=prodCount, onlyBios=onlyBios, dontKill=dontKill) is False:
  File "/Users/antonperkov/eos/build/tests/testUtils.py", line 1313, in launch
    init1Keys=producerKeys["inita"]
KeyError: 'inita'
````

**Comment by cj-oci** [comment]
The attached test script isn't compatible with master. The users have been all renamed. The user inita has been renamed to defproducera which is the error you are running into. At this point the tests are broken, so I recommend shelving this issue until the tests can be re-enabled and I will revist this issue.

**Comment by cj-oci** [comment]
This is working now.

**Comment by NRajTheGeek** [comment]
Hi all i am also facing the issue that 

cleos get account inita

is not working, please help.
