### ISSUE TITLE
DAWN-499 ⁃ Include transaction_id in get_block

### ISSUE THREAD

**Issue by nanonano7** [EOSIO/eos#294]
Is it possible to include the transaction_ids in the get_block api call?
Don't know if that would have a negative impact but it could be quite useful to some.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Kevin Heifner

comment added in October 2017

We added this to the WebUI, but not in eosc. Should this issue just be closed, or is there a desire to add this to eosc?

**Comment by heifner** [comment]
transaction id now included in get block results.
