### ISSUE TITLE
"access-control-allow-methods" option is needed in config.ini

### ISSUE THREAD

**Issue by cluestudio** [EOSIO/eos#2945]
For the 'CORS', "access-control-allow-methods" field sould be included in http response.

int the 'config.ini' below field is included to config
```
access-control-allow-origin
access-control-allow-headers
access-control-allow-credentials
```

but there is no field for 'access-control-allow-methods'

**Comment by taokayan** [comment]
Can you elaborate what're the meanings of these parameters?

**Comment by cluestudio** [comment]
Sorry, it works without above things.
