### ISSUE TITLE
Chain forks after voting out and voting in a block producer - slim

### ISSUE THREAD

**Issue by notchxor** [EOSIO/eos#2946]
**Problem**
One block producer of 3 in a testnet forks.

**Context**
We are running a private testnet with 3 block producers, booting without problems , the producers synch and produce blocks with normality. 

**Steps to reproduce**
1- boot a private testnet with slim branch
2- Vote for 3 BPs
3- After some time with 3 BPs producing blocks we vote out one of them
4- we wait for the change to take effect
5- with only 2 bps producing and no missing blocks, vote in the same producer you vote out
5- The chain forks

**Comment by rngl4b** [comment]
A few more details to reproduce this issue:

- All nodes built at `8f2c4c6`
- The network runs stable as long as the three block producers are voted in.
- When one node is voted out it stays in sync, but instantly forks when voted in again.

**Comment by notchxor** [comment]
@yankunsam 
we use
```
cleos system voteproducer prods voter init1 init2 -p voter
```

**Comment by bytemaster** [comment]
in what way did it fork... 2 and 1, 3 separate ways?

**Comment by bytemaster** [comment]
What was the error reported when the blocks were rejected?

**Comment by notchxor** [comment]
We tried to reproduce the problem with the new master release (Latest commit 4f2931). And the problem seems to be fixed, The only  thing off was that  during the first cycle after the vote , one producer would produce 2 blocks instead of 12.
