### ISSUE TITLE
Unfair producer pay, depending on claim reward sequence

### ISSUE THREAD

**Issue by taokayan** [EOSIO/eos#2951]
The current producer pay model will result in an unfair situation as follows:

assume 21 producers have the same votes, producing for some days and they start to claim rewards in the same block in the following sequence:

prod A claims, prod B claims, prod C claims, ... 

Then A will get the biggest rewards, B will get the second biggest rewards, C will get less, and so on. The rewards are reducing per producer.

If we change the sequence to [C, B, A...], then C will get the biggest rewards.

Please refer to test case multiple_producer_pay_unfair in pull request https://github.com/EOSIO/eos/pull/2950

**Comment by arhag** [comment]
We are aware of this effect. There may be instances where things are a bit "unfair", but averaged out over the long term it shouldn't be too bad.

I am marking this as wontfix. PR #2950 has already been merged in, but we will be removing the multiple_producer_pay_unfair test case.
