### ISSUE TITLE
transferred eth to eos on shapeshift app iphone

### ISSUE THREAD

**Issue by davidvlas** [EOSIO/eos#2952]
so i transferred eth to eos on shapeshift iphone app and i didnt put a eos wallet address so im guessing it made me a wallet and idk where it went i wasnt able to access my eos can someone please help heres the link https://etherscan.io/token/0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0?a=0xb92f5937e000beed74d33ab8e0331d663703f9a2

**Comment by taokayan** [comment]
EOS ERC20 is already freeze.
