### ISSUE TITLE
How to get eos coin on testnet?

### ISSUE THREAD

**Issue by photon3108** [EOSIO/eos#2953]
I launched a local testnet of dawn 3 and followed these two docs to create eos token by smart contract (eosio.token). I can check the balance by `cleos get currency balance eosio.token user`.
[Getting Started with Contracts](https://github.com/EOSIO/eos/wiki/Tutorial-Getting-Started-With-Contracts)
[Eosio.token, Exchange, and Eosio.msig Contracts](https://github.com/EOSIO/eos/wiki/Tutorial-eosio-token-Contract)

But I guess eos coin in the native eos blockchain is not eos token from smart contract (eosio.token) just like eth coin and erc20 token, right?  After mainnet swap, all eos erc20 tokens will be turned to eos coins. How to get these eos coins on testnet? And how to check the balance of these? Thanks.

**Comment by enriquejr99** [comment]
In eos, eosio.token is the native "coin". Although it works just like any other regular token.

**Comment by lecht** [comment]
I'm also figuring on this problem, is there anyone who knows this issue?

**Comment by songjim** [comment]
i have this problem too, can any one can help?

**Comment by taokayan** [comment]
Do you still have issues for ```./cleos get currency balance username```?

**Comment by sergmetelin** [comment]
Due to no reply for a significant amount of time, we are closing this ticket. If you have further questions, please send us an email to developers@block.one
