### ISSUE TITLE
Inaccurate of eosc documentation

### ISSUE THREAD

**Issue by 0x83043** [EOSIO/eos#296]
1. It isn't clear where take information about activate public key in creation account process
2. `./eosc account tester` -> `./eosc get account tester`, for eos also
3. Probably one step was skipped in insufficient funds case
```
status_code == 200: Error
: 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt12out_of_rangeEEEE: unknown key
unknown key: 
    {"authorizer_account":"eos","code_account":"eos","type":"transfer","what":"unknown key"}
    thread-0  chain_controller.cpp:776 lookup_minimum_permission
```
4. unknown option `setcode` for eosc

I hope it's not entirely useless information :)

**Comment by thomasbcox** [comment]
This was resolved elsewhere. See latest version of this file.
