### ISSUE TITLE
Improvements to subjective billing

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#2960]
PR #2947 has resolved issue #2898. However, there is further work to do with subjective billing.

First we should review and test the whole thing carefully since it is a major change.

But there are also a lot of small things to do, such as:

- [x] Remove unneeded configuration parameters having to do with the old objective billing model.
- [x] Clean up all the checktime calls to not pass unnecessary `instruction_count` anymore.
- [x] Make min_transaction_cpu_usage_us a consensus configuration parameter.
- [ ] Add plumbing to allow produce plugin to set CPU leeway.
- [ ] Ensure the subjective and objective resource exhaustion exceptions are handled correctly by both validating nodes and producing nodes.
- [x] Do not bill for time needed to build WASM cache.

**Comment by larryk85** [comment]
Clean up all checktime calls satisfied by issue #2900 and pr #3051.

**Comment by bytemaster** [comment]
Some of these remaining check list items are probably best for future versions (1.1 or 1.2)
