### ISSUE TITLE
Irreversible Block Missing from Block Log and/or ForkDB on restart

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#2964]
after running a non-producing node connected to the testnet for a short period of time, then shutting down successfully.  Restarting the node crashes (the acute crash is tracked here #2963).  The root cause of this crash is that the Irreversible block as reported by `controller` is not fetchable from the `block_log` or the fork database

This ticket is to figure out why the block is not present.

EDIT: to add the fork database

**Comment by bytemaster** [comment]
The block log does not always get the last irreversible, it should check the fork db for the block if not in the log.

**Comment by wanderingbort** [comment]
In the crash created by #2963 the fork db is already checked:

https://github.com/EOSIO/eos/blob/84deb27f9107e5aca003c427f30b3fa2e43ee507/libraries/chain/controller.cpp#L1177-L1184

**Comment by wanderingbort** [comment]
I suppose I should update the title to represent the ambiguity though... on a restart the LIB should be in either the forkDB or the block log

**Comment by bytemaster** [comment]
Could this have been caused by fork db seralization bug that didn't serialize the state of "in current chain"?

**Comment by bytemaster** [comment]
closed issue due to inability to reproduce.

**Comment by wanderingbort** [comment]
At the very least, we should check the return of `read_block_by_num` and ensure that we don't dereference a `nullptr` .  `nullptr` is a valid return from that method and we are assuming that it won't return it here which is not great practice.

**Comment by wanderingbort** [comment]
nm, I missed the other issue for that....
