### ISSUE TITLE
The way to set the system contract changed on dawn-v4.0?

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#2972]
sam@sam-ThinkPad-E450:~/Public/Porridge$ python main.py setsystemcontract
Namespace(command='setsystemcontract')
setsystemcontract
Reading WAST/WASM from imagebios/contracts/eosio.system/eosio.system.wast...
Assembling WASM...
Publishing contract...
3102176ms thread-0   main.cpp:2316                 main                 ] Failed with error: Assert Exception (10)
condition: assertion failed: unable to find key

**Comment by Lomect** [comment]
I have the same Error!!!!

**Comment by Lomect** [comment]
Can you solve it ? @yankunsam

**Comment by elmato** [comment]
Do you have **eosio.token** contract deployed to the _eosio.token_ account?

**Comment by Lomect** [comment]
Must have the contract and account?

**Comment by elmato** [comment]
Yes

**Comment by Lomect** [comment]
I'll try it. Thanks.

**Comment by yankunsam** [comment]
Sorry @elmato . It works. I forget with "eosio.token" to the tokencontract contract.


sam@sam-ThinkPad-E450:~/Public/Porridge$ python main.py setsystemcontract
Namespace(command='setsystemcontract')
setsystemcontract
Reading WAST/WASM from imagebios/contracts/eosio.system/eosio.system.wast...
Assembling WASM...
Publishing contract...
executed transaction: 99b1341f202cf3d097f6b59c0acde3960cae1f654ad1b9981323da917d0f2069  40280 bytes  7517 us
#         eosio <= eosio::setcode               {"account":"eosio","vmtype":0,"vmversion":0,"code":"0061736d0100000001c1023060027f7e0060067f7e7e7f7f...
#         eosio <= eosio::setabi                {"account":"eosio","abi":{"types":[],"structs":[{"name":"buyrambytes","base":"","fields":[{"name":"p...
warning: transaction executed locally, but may not be confirmed by the network yet



Thanks.
