### ISSUE TITLE
Error 3030000: transaction validation exception when uploading hello contract

### ISSUE THREAD

**Issue by BinaryFocus** [EOSIO/eos#2974]
With a clean install of DAWN 4 I get the following error when I push the hello contract to a new test account. 

Note that I have not installed the system contract. If this is an error caused by lack of system contract please consider this issue a request to correct the response message. 

```
cleos --wallet-url http://wallet:5555 -u http://server:7777 set contract testuser5523 /tmp/build/contracts/hello -p testuser5523
Reading WAST/WASM from /tmp/build/contracts/hello/hello.wasm...
Using already assembled WASM...
Publishing contract...
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
!"unresolvable": env.current_time
```

**Comment by taokayan** [comment]
function current_time does not exist, please ensure your code satisfies the provided api functions
