### ISSUE TITLE
Get one account "actions" -DAWN-4.0

### ISSUE THREAD

**Issue by Frank-AFN** [EOSIO/eos#2981]
"cleos get actions account -j"

![image](https://user-images.githubusercontent.com/12408187/39957493-6d089732-5626-11e8-8f8b-01d25f4d8148.png)

I'm sure to have already added http_plugin in config.ini. Could you help to fix?

**Comment by bytemaster** [comment]
Did you add the eosio::history_plugin?

**Comment by eosio-sg** [comment]
Hi BM, I added history_plugin. The great news is I can use **cleos get account XXX -j**  for the account created by **system contract**. But still doesn't work for **cleos get actions xxx -j** with the same error. Thanks

**Comment by eosio-sg** [comment]
Hi BM,

1. I added the history_plugin. But still not work for the **cleos get actions xxx -j**.
2. There is another issue for command **cleos get account xxx -j** with the error shown below. Actually, It did work for a simple account but failed for the account created by the system account.
![image](https://user-images.githubusercontent.com/38582993/39963581-f622bec8-56a1-11e8-9f1d-439c355ee9ae.png)
3. The last issue is when I try to add account_history_plugin and account_history_api_plugin. I can not start the node in port 8888.
![image](https://user-images.githubusercontent.com/38582993/39963588-4043eedc-56a2-11e8-8a5e-5bbd465b38f1.png)

Thanks for your patient!

**Comment by eosio-sg** [comment]
I addition, the plugins I used.

plugin = eosio::chain_api_plugin
plugin = eosio::net_api_plugin
plugin = eosio::net_plugin
plugin = eosio::http_plugin
plugin = eosio::producer_plugin
plugin = eosio::history_plugin

Any plugin I left?

**Comment by eosio-sg** [comment]
Another issue I find, the wallet will **lock** if expired, I wish to set the config in **config.ini**. But doesn't work.

# Timeout for unlocked wallet in seconds (default 900 (15 minutes)). Wallets will automatically lock after specified number of seconds of inactivity. Activity is defined as any wallet command e.g. list-wallets. (eosio::wallet_plugin)
unlock-timeout = 900

**Comment by andriantolie** [comment]
To configure the unlocked wallet configuration for keosd, you need to modify the config.ini inside `~/eosio-wallet` instead. @eosio-sg do you still have similar problem with `cleos get actions` on v1.1.0?

**Comment by andriantolie** [comment]
We haven't received any feedback from you for some time. I assume the above suggestions works for you.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
