### ISSUE TITLE
I Regproducer a producer and vote to it but it's not product a block, Why?

### ISSUE THREAD

**Issue by Lomect** [EOSIO/eos#2982]
my producer like this : 
```
cleos -u http://xxxxxxxx:8888 system listproducers -j
{
  "rows": [{
      "owner": "eostest",
      "total_votes": "4034073698549328632610816.00000000000000000",
      "producer_key": "EOS8Ar1fUGtZxcJ8Rdkh3rc55Vqg3ariR6fdBV8zxz4WgTW3nT73L",
      "url": "http://xxxxxxxx:6789",
      "produced_blocks": 0,
      "last_claim_time": 0,
      "location": 0,
      "time_became_active": 0,
      "last_produced_block_time": 0
    }
  ],
  "more": false
}

```

**Comment by elmato** [comment]
With how much stake are you voting the producer?

**Comment by Lomect** [comment]
100000000.0000 EOS

**Comment by bytemaster** [comment]
You must have a total of 150M EOS before any producer can take over.

**Comment by wacxt** [comment]
Can you tell me how to regproducer,I have some trouble with it.

**Comment by cppfuns** [comment]
`root@surou-C-H110M-K-Pro:~/.local/share/eosio/nodeos/config# cleos -u http://127.0.0.1:8888 system listproducers -j
{
  "rows": [{
      "owner": "eos.cos",
      "total_votes": "3973562996478458817197113344.00000000000000000",
      "producer_key": "EOS61Aze1snGEZdzypSAxpU8VBjDzDirAnASKVEhUnVA3whdMc9Q",
      "url": "http://xx.xxx.xxx.xxx:8888",
      "produced_blocks": 0,
      "last_claim_time": 0,
      "location": 0,
      "time_became_active": 0,
      "last_produced_block_time": 0
    }
  ],
  "more": false
}
`
The number of eos.cos BP nodes exceeds 150M, but there is still no block
