### ISSUE TITLE
How to get table sorted by secondary index using cleos

### ISSUE THREAD

**Issue by sim31** [EOSIO/eos#2983]
`cleos get table` command has a `-k` option which supposed to do what I want. But it does not seem to work. I'm testing this with this contract: https://github.com/sim31/timeos

If I do ` cleos get table -k reverse timeos user timestamp` it returns rows in usual order by primary key. I can tell indexing itself in contract is working, because my `getts` action prints rows in the right (reverse) order according to index.

**Comment by FortisFortuna** [comment]
Please include this. It is needed for eosjs and pulling data remotely with the get_table_rows function.

**Comment by k26dr** [comment]
I'm having the same issue. Secondary index ranges don't work in cleos

**Comment by Eazy-C** [comment]
Ya, this is desperately needed for advanced querying. If there is another workaround for the time being, it would be helpful to be pointed to it.

**Comment by taokayan** [comment]
#4053

**Comment by taokayan** [comment]
#4053

**Comment by cluestudio** [comment]
![image](https://user-images.githubusercontent.com/22926212/41594322-0308fbe2-73fe-11e8-9b48-044c03f6e9ea.png)

"get all with secondary key" API is needed. A client may want to get all Bob's records.
For that, there is no other way to separate scope in this 1.0.x version. However, this method charges the user.

**Comment by taokayan** [comment]
you can set the "limit" parameter in get table. It won't charge the user because "get table" only read the content from one node.

**Comment by andriantolie** [comment]
Check this one https://github.com/EOSIO/eos/pull/4053, you can use `--index` and `--key-type` on v1.1.0 to achieve it
