### ISSUE TITLE
Disable ability to run exposed keosd/wallet without explicit configs

### ISSUE THREAD

**Issue by nsjames** [EOSIO/eos#2985]
We were talking about this on the Telegram channel. 
Wallets could easily be exposed to the world and end up harming developers who don't know any better in spite of warnings that they might or might not have read.

Making `keosd` fail to initialize with any host besides `localhost` or `127.0.0.1` should possibly be enforced and only circumvented by adding an `enable-insecure-wallet=true` to configs.

**Comment by tbfleming** [comment]
Same rule should apply when the wallet plugin is included in nodeos.

**Comment by tbfleming** [comment]
Downside: this will throw off docker.

**Comment by jgiszczak** [comment]
OBE.  Keosd now defaults to using Unix Domain sockets.  Enabling a TCP socket at all is now opt-in.  One layer of opt-in should be sufficient.  Wallet plugin has been entirely removed from nodeos.
