### ISSUE TITLE
DAWN 4 mac build failed

### ISSUE THREAD

**Issue by cluestudio** [EOSIO/eos#2988]
build failed with below message.
- osx 10.13.4
- xcode 9.3
- DAWN3 build was fine

[ 95%] Linking CXX executable unit_test
ld: can't write output file: unit_test for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [unittests/unit_test] Error 1
make[1]: *** [unittests/CMakeFiles/unit_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by pacificcode** [comment]
@cluestudio This looks like a permissions issue.
Can you run the following commands and put the complete output here?
cd /path/to/eos
rm -rf build/
git branch
git pull
git submodule update --init --recursive
./eosio_build.sh

**Comment by cluestudio** [comment]
It works!
Thanks
