### ISSUE TITLE
cleos wallet list always empty

### ISSUE THREAD

**Issue by scientistnik** [EOSIO/eos#2989]
I run all `https://github.com/EOSIO/eos/tree/master/Docker`
But when I create default wallet, I try import key: 
```
"/opt/eosio/bin/keosd" launched
Error 3120002: Nonexistent wallet
Public key should be encoded in base58 and starts with EOS prefix
Error Details:
Wallet not found: default
```
When I try watch wallet list:
```
"/opt/eosio/bin/keosd" launched
Wallets:
[]
```
After that `cleos wallet create` again:
```
"/opt/eosio/bin/keosd" launched
Error 3120001: Wallet already exists
Name should be less than 13 characters and only contains the following symbol .12345abcdefghijklmnopqrstuvwxyz
Error Details:
Wallet with name: 'default' already exists at /root/eosio-wallet/./default.wallet
```

**Comment by BinaryFocus** [comment]
I'm not 100% sure this will help but you may want to try this docker image and then read the page on wallets that I created. I'm not sure it'll solve your problem but it may give you a different perspective and hopefully help you. 

https://www.eosdocs.io/dappdevelopment/software/docker/
https://www.eosdocs.io/dappdevelopment/wallets/

**Comment by andriyha** [comment]
But with your alias I get error when try
`cleos set contract eosio /contracts/eosio.bios -p eosio`
i get
`Reading WAST/WASM from /contracts/eosio.bios/eosio.bios.wasm...
Using already assembled WASM...
Publishing contract...
Error 3110001: Missing Chain API Plugin
Error Details:
Chain API plugin is not enabled`

**Comment by itinance** [comment]
Same happens to me.

I follow all steps to build the docker container following the official docs, and also run cleos with the following alias:

`alias cleos='docker-compose exec keosd /opt/eosio/bin/cleos -u http://nodeosd:8888'`

This happens then: 

After creating a wallet

```
$ cleos wallet create
"/opt/eosio/bin/keosd" launched
Creating wallet: default
Save password to use in the future to unlock this wallet.
Without password imported keys will not be retrievable.
"PW5KdkDAnhZmChM*****************************"
```

it will be gone afterwards:

```
hagen at Hagens-MBP-4 in /data/workspace/eos/Docker on master
$ cleos wallet list
"/opt/eosio/bin/keosd" launched
Wallets:
[]

```

**Comment by andriyha** [comment]
With such alias everything is very wonderful
`alias cleos='docker-compose exec keosd /opt/eosio/bin/cleos -u http://nodeosd:8888 --wallet-url http://localhost:8888'`

**Comment by sergmetelin** [comment]
In 4.0 keosd is run automatically by cleos.
However, currently cleos doesn't seem to recognize nodeos running a wallet.

**Comment by itinance** [comment]
As stated in the [docs](https://www.eosdocs.io/dappdevelopment/wallets/#keosd):

> Something that can be a little confusing is that wallets that are not “open” are not listed when using the “list” command. Here’s an example:

**Comment by sergmetelin** [comment]
opening/unlocking the wallet doesn't fix it as well.

**Comment by gleehokie** [comment]
I tried to recreate this but was not able to.  Here's what I did:

1. Build from master (
2. Install (cd build && sudo make install)
3. Run nodeos (nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin)
4. Create wallet (cleos wallet create) and note the wallet password
5. List wallet (cleos wallet list)
6. Lock wallet (cleos wallet lock)
7. Unlock wallet (cleos wallet unlock --password xxxxxxxxx) where xxxxxxxxx is the wallet password

``` bash
glee-mbp:eosio-wallet greg$ cleos wallet create
"/usr/local/bin/keosd" launched
Creating wallet: default
Save password to use in the future to unlock this wallet.
Without password imported keys will not be retrievable.
"xxxxxxxxx"
glee-mbp:eosio-wallet greg$ cleos wallet lock
Locked: default
glee-mbp:eosio-wallet greg$ cleos wallet unlock --password xxxxxxxxx
Unlocked: default
glee-mbp:eosio-wallet greg$ cleos wallet list
Wallets:
[
  "default *"
]
glee-mbp:eosio-wallet greg$ cleos wallet lock
Locked: default
glee-mbp:eosio-wallet greg$ cleos wallet list
Wallets:
[
  "default"
]
glee-mbp:eosio-wallet greg$
```
Note that I built my executables, I did not do this using the Docker container.

**Comment by v1nc3ntlaw** [comment]
Stuck couple hours with same problem followed by https://github.com/EOSIO/eos/wiki/Local-Environment#start-both-nodeos-and-keosd-containers

I tried this one works well. https://github.com/EOSIO/eos/issues/2989#issuecomment-389158223

Thanks for save my day.

**Comment by gleehokie** [comment]
Related to #3105

**Comment by ericiles** [comment]
The [documentation](https://github.com/EOSIO/eos/blob/master/Docker/README.md#execute-cleos-commands) has been updated to reflect the solution to this issue.

**Comment by GodbayPlanet** [comment]
I had the same issue, I created a wallet and when I restart nodeos wallet list was empty. I resolve it with cleos wallet open. It appears that you first need to open wallet so you can use it.

**Comment by yhuag** [comment]
As @GodbayPlanet stated, you might need to open the wallet before seeing it.
`cleos wallet open`
And, you can view the wallet in the list:
`cleos wallet list`

Otherwise, since you cannot remove & rename any wallet on the eosio chain, you may want to create a new wallet with a new specific name:
`cleos wallet create --to-console -n THE_NAME_OF_WALLET`

When you finished using the wallet and want to store it somewhere (e.g. like your main key-pair) and may retrieve it back in the near future, you can transfer the ownership to the main key-pair:
`cleos set account permission ACCOUNT_NAME owner THE_MAIN_PUBLIC_KEY_THAT_STORES_YOUR_WALLETS -p ACCOUNT_NAME@owner`
