### ISSUE TITLE
All permission links to contract@eosio.code to be tapos-checked 

### ISSUE THREAD

**Issue by gpmn** [EOSIO/eos#3002]
As BM's suggestion, I rise a issue at here, thanks for any clarification.

1、Why does dice contract ask for user‘s active key?
     the user can not trust so many DApp before to use them in product. And to enable DApp to transfer any  cash in any amount from user's account is too dangerous and not acceptable in practice.

2、even dice app version 1.0.0 is secure enough, how to ensure version 1.0.1/1.1.0/1.2.0 .... is enough too? 
      think about this case : a user authorize dice app at version 1.0.0, then a bad guy change dice app and update it maliciously.
     a). how to let user just auth exactly current version's DApp and do not auth to the future version?
     b). how to disable contract be updated by other account? it seems anybody can update a DApp in private net.

**Comment by bytemaster** [comment]
The dice app should be modified so as not to require permission from user to transfer funds.

Future feature would be to allow delegation of  "contract@eosio.code" to refer to a particular code revision rather than "any code revision".

**Comment by bytemaster** [comment]
For version 1.0 we only need to identify a plan to add this feature in the future.

**Comment by bytemaster** [comment]
Created new issue for tracking DICE contract changes: #3003

**Comment by arhag** [comment]
> Future feature would be to allow delegation of "contract@eosio.code" to refer to a particular code revision rather than "any code revision".

> For version 1.0 we only need to identify a plan to add this feature in the future.

We can add this in a future hard fork without changing the serialization of the authorities or actions provided to the chain. The plan for this is documented in #3050.
