### ISSUE TITLE
error with using std::sting in contract

### ISSUE THREAD

**Issue by tsrman** [EOSIO/eos#3004]
I had strange problem while try use std::sting in DAWN-4. For example if I build sample "asserter" with eosio_build.sh "cleos set contract" work okay but if i build "asserter" with eosiocpp, i got error "Failed with error: Assert Exception (10) !"unresolvable": env.free" when try set contact

**Comment by tsrman** [comment]
look like it broken in this commit https://github.com/EOSIO/eos/commit/a521a68dd625e759145cfe3ab61548539f05b7ee#diff-fad3ebad54409ea86aa7b840c40a661d

**Comment by taokayan** [comment]
Can you share your smart contract code?

**Comment by spoonincode** [comment]
Closing due to CDT not having such linker grief. Please use eosio.cdt
