### ISSUE TITLE
[slim] defining extensions_type

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#3008]
I see two probably definitions for extenstions_type:

https://github.com/EOSIO/eos/blob/9be89106da1d6a1543eb19dd0f3b96a53e286088/contracts/eosiolib/types.hpp#L12

https://github.com/EOSIO/eos/blob/9be89106da1d6a1543eb19dd0f3b96a53e286088/libraries/chain/include/eosio/chain/types.hpp#L173-L177

Based on this comment and my guess at how this will serialize (simple concatenation), I think a struct like the one below should be added:

```json
  "extensions_type": {
    "base": "",
    "fields": {
      "type": "uint16",
      "data": "bytes"
    }
  }
```

**Comment by bytemaster** [comment]
They both serialize the same, eosiolib didn't have serialization defined for pair so I substituted tuple.  Pair is probably the official method.

**Comment by spartucus** [comment]
So `transaction_extensions` in `transaction` does not support yet?

> FC_ASSERT( trx.transaction_extensions.size() == 0, "we don't support any extensions yet" );
