### ISSUE TITLE
Does it support  UBUNTU 18.04 ?  

### ISSUE THREAD

**Issue by jidongg** [EOSIO/eos#3009]
Beginning build version: 1.2

	ARCHITECTURE: Linux

	Unsupported Linux Distribution. Exiting now.

Does it support  UBUNTU 18.04 ?

**Comment by robmcc1** [comment]
Ubuntu 16.04 (Ubuntu 16.10 recommended).

**Comment by jidongg** [comment]
Will upgrade in the future?

**Comment by hokiecsgrad** [comment]
Yes, already testing and will announce once it's available.
