### ISSUE TITLE
nodeos won't run properly, gives time error

### ISSUE THREAD

**Issue by flameheadsg** [EOSIO/eos#3011]
This is what I get in my console when I run nodeos, this is on an Ubuntu 16.04 VM:

sunny@sunny-VirtualBox:~$ nodeos
3488600ms thread-0   chain_plugin.cpp:125          plugin_initialize    ] initializing chain plugin
3488600ms thread-0   main.cpp:99                   main                 ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_9gregorian8bad_yearEEEEE: Year is out of valid range: 1400..10000
Year is out of valid range: 1400..10000: unable to convert ISO-formatted string to fc::time_point_sec
    {"what":"Year is out of valid range: 1400..10000"}
    thread-0  time.cpp:44 from_iso_string
unable to convert ISO-formatted string to fc::time_point
    {}
    thread-0  time.cpp:64 from_iso_string

I built EOS properly and did sudo make install in the /build folder. What else should I try?

**Comment by taokayan** [comment]
Did you run a newer version of nodeos with older version of block log file /shared_mem?

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
