### ISSUE TITLE
Node doesn't try to reconnect with the valid peer after it receives connection from other peer that has unlinkable "second" block (i.e. it doesn't link with the node's genesis block)

### ISSUE THREAD

**Issue by andriantolie** [EOSIO/eos#3017]
In this scenario, we have 3 nodes which are A1, A2, B. And they abide by the following rules:
- Node A1 and Node A2 share the same genesis
- Node B uses a different genesis (we can just modify the initial timestamp for this). So the genesis block of Node B has different id from A1 and A2
- Node A1 knows Node A2
- Node A2 knows Node B
- Node B knows Node A1
- Node A2 and Node B has enable-stale-production enabled, producer_plugin enabled, and the producer is eosio
- Node A1 has enable-stale-production disabled and producer_plugin disabled

And then we start the nodes in the following order: A1, B, A2. The reaction should be the following:
- Node A1 finds out that Node A2 is inactive and failed to connect with Node A2
- When Node B starts it tries to connect with Node A1. Node A1 will throw an exception `prior != by_id_idx.end(): unlinkable block`
- When Node A2 starts, it will try to connect to Node B, however, it will find out that B is forked so it rejects the connection with Node B
- **Normally**, after some time Node A1 will try to reconnect to A2 and be able to sync with A2. **However, this doesn't happen**

The above problem **only happens when Node A1 only have the genesis block** inside its chain. If Node A1 has another block on top of the genesis block, it will reject the connection with Node B and regard Node B as forked instead of throwing an exception. Then it will try to reconnect with Node A2 after some time

For convenience, I'm attaching the config and genesis for Node A1, A2, and B here
[3017-config-and-genesis.zip](https://github.com/EOSIO/eos/files/2032817/3017-config-and-genesis.zip)

Then they can be started by the following:
```
programs/nodeos/nodeos --data-dir data-dir-a1 --config-dir data-dir-a1 --resync
programs/nodeos/nodeos --data-dir data-dir-b --config-dir data-dir-b --resync
programs/nodeos/nodeos --data-dir data-dir-a2 --config-dir data-dir-a2 --resync
```

**Comment by pmesnier** [comment]
Thanks for that detailed write up. I assume that is against the master branch?

**Comment by andriantolie** [comment]
Yep

**Comment by andriantolie** [comment]
Awesome. Tested and verified!
