### ISSUE TITLE
fail to startup with error "database created by a different compiler, build, boost version, or operating system"

### ISSUE THREAD

**Issue by lihui1625** [EOSIO/eos#3020]
C02VF2LZHTD6:nodeos setup$ ./nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::account_history_api_plugin

1111249ms thread-0   wallet_plugin.cpp:41          plugin_initialize    ] initializing wallet plugin
1111250ms thread-0   http_plugin.cpp:247           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
1111250ms thread-0   chain_plugin.cpp:125          plugin_initialize    ] initializing chain plugin
_1111251ms thread-0   main.cpp:101                  main                 ] /Users/setup/GIT/EOS/eos/libraries/chainbase/src/chainbase.cpp(70): Throw in function chainbase::database::database(const bfs::path &, chainbase::database::open_flags, uint64_t)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: database created by a different compiler, build, boost version, or operating system_

**Comment by LucienLau** [comment]
Maybe you shuold try using history_api_plugin instead of account_history_api_plugin

**Comment by xianzhisheng** [comment]
#2975

**Comment by lihui1625** [comment]
it works if I use --resync-blockchain

I think it should update in document

**Comment by flylee2004** [comment]
@lihui1625  你好，我用了--resync-blockchain  提示what: unrecognised option '--resync-blockchain' 没有这个参数啊 是在nodeos后面加吗

**Comment by 723937936** [comment]
rm -rf ~/Library/Application\ Support/eosio/nodeos/data
it works again
