### ISSUE TITLE
nodeos report errors when  a new  bp join into private network

### ISSUE THREAD

**Issue by dipingxian2** [EOSIO/eos#3022]
42500ms thread-0   producer_plugin.cpp:569       block_production_loo ] Produced block 0000009328dad8f4... #147 @ 2018-05-14T07:14:02.500 signed by eosio [trxs: 0, lib: 147, confirmed: 0]
842560ms thread-0   net_plugin.cpp:703            connection           ] accepted network connection
842693ms thread-0   block_log.cpp:206             read_block_by_num    ] 13 NSt8ios_base7failureE: basic_ios::clear
rethrow basic_ios::clear:
    {"what":"basic_ios::clear"}
    thread-0  block_log.cpp:206 read_block_by_num
842693ms thread-0   net_plugin.cpp:1042           enqueue_sync_block   ] write loop exception
843000ms thread-0   block_log.cpp:177             append               ] 10 assert_exception: Assert Exception
my->index_stream.tellp() == sizeof(uint64_t) * (b->block_num() - 1): Append to index file occuring at wrong position.
    {"position":8,"expected":1168}
    thread-0  block_log.cpp:167 append
843000ms thread-0   producer_plugin.cpp:545       block_production_loo ] Got exception while generating block:
10 assert_exception: Assert Exception
my->index_stream.tellp() == sizeof(uint64_t) * (b->block_num() - 1): Append to index file occuring at wrong position.
    {"position":8,"expected":1168}
    thread-0  block_log.cpp:167 append
rethrow
    {}
    thread-0  block_log.cpp:177 append
843000ms thread-0   producer_plugin.cpp:591       block_production_loo ] exception producing block
843500ms thread-0   block_log.cpp:177             append               ] 10 assert_exception: Assert Exception
my->index_stream.tellp() == sizeof(uint64_t) * (b->block_num() - 1): Append to index file occuring at wrong position.
    {"position":8,"expected":1168}
    thread-0  block_log.cpp:167 append
843500ms thread-0   producer_plugin.cpp:545       block_production_loo ] Got exception while generating block:
10 assert_exception: Assert Exception
my->index_stream.tellp() == sizeof(uint64_t) * (b->block_num() - 1): Append to index file occuring at wrong position.
    {"position":8,"expected":1168}
    thread-0  block_log.cpp:167 append
rethrow
    {}
    thread-0  block_log.cpp:177 append

**Comment by taokayan** [comment]
Can you share your config and details steps?

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
