### ISSUE TITLE
dawn 4.0 can't start with error for unable to find plugin: eosio::account_history_plugin

### ISSUE THREAD

**Issue by shermanxie** [EOSIO/eos#3023]
download EOS dawn 4.0 source and build success,
use old JungleTestnet key,but can't start node
Error information :
  496523ms thread-0   chain_plugin.cpp:125          plugin_initialize    ] initializing chain plugin
2496544ms thread-0   http_plugin.cpp:247           plugin_initialize    ] configured http to listen on 0.0.0.0:8868
2496544ms thread-0   main.cpp:101                  main                 ] /home/eos-dawn-v4.0.0/eos/libraries/appbase/application.cpp(290): Throw in function appbase::abstract_plugin &appbase::application::get_plugin(const string &) const
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: unable to find plugin: eosio::account_history_plugin

**Comment by zformular** [comment]
replace with eosio::history_api_plugin

**Comment by jasonrdzhou** [comment]
history_api_plugin lead to "/v1/account_history/get_key_accounts"
