### ISSUE TITLE
When I resync block the error is find and resync is stop!!

### ISSUE THREAD

**Issue by Lomect** [EOSIO/eos#3029]
3589572ms thread-0   net_plugin.cpp:1175           process_next_message ] e.to_detail_string(): 8 out_of_range_exception: Out of Range
read datastream of length 0 over by 4
    {"method":"read","len":0,"over":4}
    thread-0  datastream.cpp:6 throw_datastream_range_error
error unpacking uint32_t
    {"type":"uint32_t"}
    thread-0  raw.hpp:602 unpack
Error unpacking field head_num
    {"field":"head_num"}
    thread-0  raw.hpp:361 operator()
error unpacking eosio::chain_size_message
    {"type":"eosio::chain_size_message"}
    thread-0  raw.hpp:602 unpack

**Comment by qiushaoxi** [comment]
how to resove?

**Comment by tianyalangzi** [comment]
I got similar error
