### ISSUE TITLE
[Error] Bancor Protocol

### ISSUE THREAD

**Issue by hyunwoongJi** [EOSIO/eos#3032]
According to Bancor Protocol, balance seems to be set as a wrong value

real_type C(c.balance.amount+in.amount); -> real_type C(c.balance.amount);

https://github.com/EOSIO/eos/blob/13952d4505d56442a769528bdf6094b52768b2cd/contracts/eosio.system/exchange_state.cpp#L7

Also, supply seems to be set as a wrong value.

real_type R(supply.amount - in.amount); -> real_type R(supply.amount);

https://github.com/EOSIO/eos/blob/13952d4505d56442a769528bdf6094b52768b2cd/contracts/eosio.system/exchange_state.cpp#L25

if connector weight was intended to be 50%, the number "1000.0" should be "1.0" (since c.weight = .5 in exchange_state.hpp)

https://github.com/EOSIO/eos/blob/13952d4505d56442a769528bdf6094b52768b2cd/contracts/eosio.system/exchange_state.cpp#L8

https://github.com/EOSIO/eos/blob/13952d4505d56442a769528bdf6094b52768b2cd/contracts/eosio.system/exchange_state.cpp#L27

**Comment by bytemaster** [comment]
Connector weight was not intended to be 50%, but .1%.

The Bancor Protocol math is wrong in their paper, absent the "+ in.amount" and "- in.amount" the protocol can be gamed.  Extensive tests have verified the math cannot be gamed and always sees error approaching 0 when higher precision numbers are used.

**Comment by hyunwoongJi** [comment]
@bytemaster 

Yes the Bancor Protocol math is wrong in their "white paper"

If you wanted to fix it, you had to fix the following line:

      real_type T = C * (std::pow( ONE + E/R, F) - ONE);
it should be as follows:
      real_type T = -1 * C * (std::pow( ONE - E/R, F) - ONE);

**Comment by sergioyuhjtman** [comment]
I am reviewing carefully Bancor papers. When saying that there is an error, please, refer clearly to what formula from what document you are talking about. So far I didn't find any errors in Meni Rosenfeld's article (though it could have been done simpler without integrating) nor in the two formulas in the last page of Bancor Whitepaper.

**Comment by hyunwoongJi** [comment]
@sergioyuhjtman 
I am sorry for unclearness. And the paper you have linked has no error. It was "white paper" https://storage.googleapis.com/website-bancor/2018/04/01ba8253-bancor_protocol_whitepaper_en.pdf (second equation of page 11) that I referred to. (Now I can see that whether the equation is wrong or not is depend on convention). The term "connected tokens paid out" in the LHS it self has negative sign therefore it should be multiplied by "-1". The same is true for the term "tokens destroyed" in the RHS. Thank you for reviewing this issue 👍

**Comment by sergioyuhjtman** [comment]
@hyunwoongJi Thanks. Please read also here https://eosio.stackexchange.com/questions/317/is-there-a-math-error-in-bancor-paper  to understand better what Dan Larimer has in mind. He is confused because he thinks that Rosenfeld's formulas are wrong. Since Dan's formulas make a difference in favor of the exchange, maybe this is good enough. But still I think it has to be reviewed carefully.

**Comment by hyunwoongJi** [comment]
@sergioyuhjtman Thank you for sharing. Now I can understand it. And thank you again for taking this issue carefully :)
