### ISSUE TITLE
Can not add custom struct type as a parameter to my function

### ISSUE THREAD

**Issue by basarrcan** [EOSIO/eos#3040]
```
public:
//@abi action
void addcustomer(account_name account, const contact newContact)
.
.
.
private:
//@abi table contact i64
struct contact
{
    uint64_t contactid;
    .
.
.
```

Here's the error:
 error: unknown type name 'contact'; did you mean 'contract'?
                     const contact newContact)
                           ^~~~~~~
                           contract

**Comment by tbfleming** [comment]
Move the struct definition to before its first use (C++ rule).
