### ISSUE TITLE
Docker image should be FROM alpine to reduce attack surface / minimize OS updates

### ISSUE THREAD

**Issue by ellipticasec** [EOSIO/eos#3042]
Right now `Dockerfile` is `FROM ubuntu:16.04` this is fairly large image (size to pull) and attack surface because of many packages.

https://github.com/EOSIO/eos/blob/dacc1b09d2c10cc3ca4cea7821c04ea2a47487fe/Docker/Dockerfile#L11

`alpine` as a base image has a much smaller attack surface and thus reduces the need for BP to frequently rebuild / restart their nodes for simple OS updates. not to mention that it's much leaner and speeds up start time from a fresh pull.

**Comment by ChristianDunst** [comment]
Thank you for your suggestion.

Note: BPs are not running the eosio code in docker images
