### ISSUE TITLE
Producer Policy Suggestion: Send last block early

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#3043]
# Description

In globally diverse test networks, the hand-off between two producers has the greatest risk for benign forking due to latency.  The result is that there can be a lot of single block forks when producer N + 1  must choose whether to wait for Producer N's last block or build from their second to last block.

# Proposal

A producer who maintains the chains operation as their best interest should voluntarily sign and send out their last block _early_ to allow it to reach the next producer in time for them to produce the first block of their round.

This policy should be implemented by the producer plugin and driven by command line

**Comment by taokayan** [comment]
Is that similar feature as #3683 ?

**Comment by taokayan** [comment]
hi, would you review https://github.com/EOSIO/eos/pull/4118?

**Comment by taokayan** [comment]
I think this ticket can be closed as #4118 has been merged
