### ISSUE TITLE
I update to dawn-v4.0.0 ,why can't run??

### ISSUE THREAD

**Issue by healthwallet** [EOSIO/eos#3066]
lwy1218deMac-mini:eos iinda$ ./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin
-bash: ./nodeos: No such file or directory
lwy1218deMac-mini:eos iinda$ cd build/programs/nodeos/
lwy1218deMac-mini:nodeos iinda$ ./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin
2386978ms thread-0   chain_plugin.cpp:125          plugin_initialize    ] initializing chain plugin
2387041ms thread-0   main.cpp:101                  main                 ] /Users/lwy1218/Downloads/eos/libraries/chainbase/src/chainbase.cpp(106): Throw in function chainbase::database::database(const bfs::path &, chainbase::database::open_flags, uint64_t)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: database dirty flag set (likely due to unclean shutdown) replay or resync required

my system is mac os,v3.0.0 is run ok.

**Comment by vjoke** [comment]
add '--replay-blockchain'

**Comment by healthwallet** [comment]
lwy1218deMac-mini:nodeos iinda$ nodeos --replay-blockchain
375256ms thread-0   chain_plugin.cpp:125          plugin_initialize    ] initializing chain plugin
375257ms thread-0   chain_plugin.cpp:162          plugin_initialize    ] Replay requested: wiping database
377901ms thread-0   http_plugin.cpp:247           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
377901ms thread-0   main.cpp:101                  main                 ] /Users/lwy1218/Downloads/eos/libraries/appbase/application.cpp(290): Throw in function appbase::abstract_plugin &appbase::application::get_plugin(const string &) const
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: unable to find plugin: eosio::account_history_api_plugin


4.0.0 no this eosio::account_history_api_plugin???

**Comment by heifner** [comment]
Use `eosio::history_api_pluging`

**Comment by rsivasundaram** [comment]
Please update the doc: https://github.com/EOSIO/eos/wiki/Local-Environment#advanced-steps to mention the change to eosio::history_api_plugin instead of eosio::account_history_api_plugin

**Comment by gleehokie** [comment]
Done

**Comment by AaronFaltesek** [comment]
Had this error: 
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: database dirty flag set (likely due to unclean shutdown) replay or resync required

adding --replay-blockchain solved it for me.

./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --replay-blockchain

**Comment by gleehokie** [comment]
Please update to Dawn-4.1 and repeat tests.
