### ISSUE TITLE
Why does refBlockPRefix of 0 work ?

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#307]
![image](https://user-images.githubusercontent.com/347290/29991441-cd736532-8f54-11e7-8c72-97ffb33e8fbf.png)

Is this a bug or intended behavior....

**Comment by heifner** [comment]
get_info from the first block:

./eosc get info
{
  "head_block_num": 0,
  "last_irreversible_block_num": 0,
  "head_block_id": "0000000000000000000000000000000000000000000000000000000000000000",
  "head_block_time": "2017-03-30T12:00:00",
  "head_block_producer": "",
  "recent_slots": "1111111111111111111111111111111111111111111111111111111111111111",
  "participation_rate": "1.00000000000000000"
}

Therefore, 0 refBlockNum and 0 refBlockPrefix work.

One question I have is how old should we allow refBlockNum/refBlockPrefix to be? Currently, it appears that as long as they are valid we don't care how old they are.  If we do add a timeout then 0/0 would be invalid after the timeout. Might also make sense to use a diff head_block_id to start.

**Comment by bytemaster** [comment]
They can be at most 64K blocks old.
