### ISSUE TITLE
Error：no member named 'get_channel' in 'appbase::application'

### ISSUE THREAD

**Issue by okluoquan** [EOSIO/eos#3072]
error:

eos/plugins/chain_plugin/chain_plugin.cpp:42:41: error: no member named 'get_channel' in 'appbase::application'
   :accepted_block_header_channel(app().get_channel<channels::accepted_block_header>())

when I run ./eosio_build.sh  on dawn 4.0.

Can anyone help me, thanks.

**Comment by spoonincode** [comment]
`git submodule update`
