### ISSUE TITLE
The number of BP nodes exceeds 150M, but there is still no block

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#3076]
root@surou-C-H110M-K-Pro:~/.local/share/eosio/nodeos/config# cleos -u http://127.0.0.1:8888 system listproducers -j
{
  "rows": [{
      "owner": "eos.cos",
      "total_votes": "3973562996478458817197113344.00000000000000000",
      "producer_key": "EOS61Aze1snGEZdzypSAxpU8VBjDzDirAnASKVEhUnVA3whdMc9Q",
      "url": "http://xx.xxx.xxx.xxx:8888",
      "produced_blocks": 0,
      "last_claim_time": 0,
      "location": 0,
      "time_became_active": 0,
      "last_produced_block_time": 0
    }
  ],
  "more": false
}

**Comment by jgiszczak** [comment]
Single node, single producer is a degenerate case that does not behave normally.  Add `--enable-stale-production` to the command line.  This argument is not required on any except a single test node or the bootstrap node of a new network.
