### ISSUE TITLE
DPOS BFT Double Confirmation

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3088]
To achieve true BFT guarantees requires a double confirmation from producers.  The discussion with Vitalik in issue https://github.com/EOSIO/eos/issues/2718 points out how our current improvement is incomplete.  

- [x] LIB does not advance until 2/3+1 producers implicitly agree on the LIB

No new information is required in block headers, as each block has an implied LIB already which we will now consider the the Proposed LIB (PLIB) which only becomes LIB after 2/3+1 agree on the PLIB.

Side effect is to increase latency on producer schedule changes.

BFT messages for real-time confirmation of blocks (outside of block headers) will require the double-confirmation same as all other BFT protocols. This will increase low-latency proofs to 30 to 37 signatures plus 21 bytes of signaling information.

**Comment by lyang36** [comment]
I have a question in the code. 
It currently reads: ````return blocknums[ (blocknums.size()-1) / 3 ];``` as the ```dpos_last_irreversible```. However, this does not imply "until 2/3+1 producers implicitly agree on the LIB". Do we need to check ```blocknums.size() > 2/3 * producers.size```?
