### ISSUE TITLE
Bill extra time to "set code" to recognize the fact that we will have to compile it at some point.

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3099]
We should in theory bill "extra time" on set code even though we don't hit the cache delay on set code. This extra time should be equal to the actual "cache time" or "max allowed transaction time" and the user must have enough CPU bandwidth to cover this billing.

**Comment by brianjohnson5972** [comment]
@wanderingbort @heifner I am thinking this is OBE (overcome by events).  If I don't hear from you I will presume that is the case.

**Comment by brianjohnson5972** [comment]
OBE (overcome by events)
