### ISSUE TITLE
Duplicate info about the producer_chain under `./eosd --help`

### ISSUE THREAD

**Issue by spicynoodle** [EOSIO/eos#310]
Duplicate `eos::producer_plugin` under `./eosd --help`

![](https://user-images.githubusercontent.com/16319106/30000229-4e34b51c-9096-11e7-96f3-562bd2a40204.png)

**Comment by pavybez** [comment]
This has been fixed. Please clone latest repository and let me know if still face the issue.

**Comment by wanderingbort** [comment]
@spicynoodle if you are still seeing this, we will reopen.
