### ISSUE TITLE
nodeosd exits unexceptly

### ISSUE THREAD

**Issue by rogerone-shen** [EOSIO/eos#3101]
Run `docker-compose -f docker-compose-dawn4.0.yaml up -d`, nodeos exits, and return following errors.

Attaching to docker_mongo_1, docker_nodeosd_1, docker_keosd_1
mongo_1    | 2018-05-16T03:28:23.778+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=mongo
keosd_1    | 1705081ms thread-0   wallet_plugin.cpp:41          plugin_initialize    ] initializing wallet plugin
keosd_1    | 1705081ms thread-0   http_plugin.cpp:247           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
nodeosd_1  | 1704504ms thread-0   main.cpp:101                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
nodeosd_1  | Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
nodeosd_1  | std::exception::what: unrecognised option '--mongodb-uri'
nodeosd_1  | 
mongo_1    | 2018-05-16T03:28:23.778+0000 I CONTROL  [initandlisten] db version v3.6.4
keosd_1    | 1705081ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/keosd/stop
keosd_1    | 1705081ms thread-0   http_plugin.cpp:285           plugin_startup       ] start listening for http requests
keosd_1    | 1705081ms thread-0   wallet_api_plugin.cpp:74      plugin_startup       ] starting wallet_api_plugin
keosd_1    | 1705081ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/create
keosd_1    | 1705081ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/create_key
keosd_1    | 1705081ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/get_public_keys
mongo_1    | 2018-05-16T03:28:23.778+0000 I CONTROL  [initandlisten] git version: d0181a711f7e7f39e60b5aeb1dc7097bf6ae5856
mongo_1    | 2018-05-16T03:28:23.779+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
mongo_1    | 2018-05-16T03:28:23.779+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1    | 2018-05-16T03:28:23.779+0000 I CONTROL  [initandlisten] modules: none
mongo_1    | 2018-05-16T03:28:23.780+0000 I CONTROL  [initandlisten] build environment:
mongo_1    | 2018-05-16T03:28:23.780+0000 I CONTROL  [initandlisten]     distmod: debian81
mongo_1    | 2018-05-16T03:28:23.780+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1    | 2018-05-16T03:28:23.780+0000 I CONTROL  [initandlisten]     target_arch: x86_64
keosd_1    | 1705082ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/import_key
keosd_1    | 1705082ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/list_keys
keosd_1    | 1705082ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/list_wallets
keosd_1    | 1705082ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/lock
keosd_1    | 1705082ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/lock_all
keosd_1    | 1705082ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/open
keosd_1    | 1705082ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/set_timeout
keosd_1    | 1705082ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/sign_transaction
mongo_1    | 2018-05-16T03:28:23.780+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
keosd_1    | 1705082ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/wallet/unlock
mongo_1    | 2018-05-16T03:28:23.780+0000 I STORAGE  [initandlisten] 
mongo_1    | 2018-05-16T03:28:23.781+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1    | 2018-05-16T03:28:23.781+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1    | 2018-05-16T03:28:23.781+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3474M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),cache_cursors=false,log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mongo_1    | 2018-05-16T03:28:24.447+0000 I STORAGE  [initandlisten] WiredTiger message [1526441304:447131][1:0x7f2fc2379a00], txn-recover: Set global recovery timestamp: 0
mongo_1    | 2018-05-16T03:28:24.476+0000 I CONTROL  [initandlisten] 
mongo_1    | 2018-05-16T03:28:24.477+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1    | 2018-05-16T03:28:24.477+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1    | 2018-05-16T03:28:24.477+0000 I CONTROL  [initandlisten] 
mongo_1    | 2018-05-16T03:28:24.478+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: a3e71aa2-5df0-4fe6-9e50-299281493566
mongo_1    | 2018-05-16T03:28:24.488+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.6
mongo_1    | 2018-05-16T03:28:24.494+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 513ee3bc-b6ca-4bdb-b6b6-59702fce2e30
mongo_1    | 2018-05-16T03:28:24.509+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1    | 2018-05-16T03:28:24.510+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
docker_nodeosd_1 exited with code 0

**Comment by grigio** [comment]
I think it's duplicate of #3018

**Comment by rogerone-shen** [comment]
It is. Thanks, i gonna close it.
