### ISSUE TITLE
cleos set contract eosio eosio.system, Failed 

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#3104]
`oot@iZ2zea5mjpcmz9m17k56daZ:/home/surou/Documents/github/eos/build/contracts# cleos set contract eosio eosio.system
Reading WAST/WASM from eosio.system/eosio.system.wasm...
Using already assembled WASM...
Publishing contract...
3096025ms thread-0   main.cpp:2316                 main                 ] Failed with error: Assert Exception (10)
!"unresolvable": env.send_deferred
`

**Comment by yepp4you** [comment]
I have the same problem.

**Comment by cppfuns** [comment]
Guess is a new issue caused by a new version modification

**Comment by cppfuns** [comment]
@elmato 
Why did you close this question and have it been resolved?
