### ISSUE TITLE
run "cleos wallet list", returns empty 

### ISSUE THREAD

**Issue by rogerone-shen** [EOSIO/eos#3105]
chenxuechengdeMacBook-Pro:Docker rogershen$ cleos wallet unlock -n default
"/opt/eosio/bin/keosd" launched
password: Unlocked: default
chenxuechengdeMacBook-Pro:Docker rogershen$ cleos wallet list
"/opt/eosio/bin/keosd" launched
Wallets:
[]

**Comment by cppfuns** [comment]
Have you already import some private key?

**Comment by rogerone-shen** [comment]
Yes, I have imported private key by run commad `cleos wallet import ${private_key_1}`

**Comment by cppfuns** [comment]
Are you operating under the same account? Whether create under root, and then operate under another account

**Comment by ericiles** [comment]
The [documentation](https://github.com/EOSIO/eos/blob/master/Docker/README.md#execute-cleos-commands) has been update to reflect the solution to this issue.
