### ISSUE TITLE
cleos system regproducer,      Error

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#3106]
The dawn-v4.0.0 branch is ok, but 
The following error occurred in the latest code running in the master branch.
----------------------------------------------------------
`root@surou-C-H110M-K-Pro:/home/surou/eos/build/contracts# cleos system regproducer eos.cos EOS61Aze1snGEZdzypSAxpU8VBjDzDirYAnASKVEhUnVA3whdMc9Q http://xx.XX.XX.XX:8888
Error 3050002: Invalid Action Arguments
Error Details:
'{"producer":"eos.cos","producer_key":"EOS61Aze1snGEZdzypSAxpU8VBjDzDirYAnASKVEhUnVA3whdMc9Q","url":"http://xxx.xx.xxx.xx:8888"}' is invalid args for action 'regproducer' code 'eosio'
Invalid cast from object_type to string`

**Comment by cppfuns** [comment]
`root@iZ2zea5mjpcmz9m17k56daZ:/home/surou/Documents/github/eos/build/contracts# cleos set contract eosio eosio.system -p eosio
Reading WAST/WASM from eosio.system/eosio.system.wasm...
Using already assembled WASM...
Publishing contract...
1730140ms thread-0   main.cpp:2316                 main                 ] Failed with error: Assert Exception (10)
!"unresolvable": env.send_deferred
`

**Comment by moskvanaft** [comment]
@cppfuns , it seems like `send_defrerred` function parameters in you contract doesn't match with what `nodeos` provides. I guess you need to rebuild the system contract with eosiolib (contracts/eosiolib) from the same revision as you `nodeos`.

**Comment by moskvanaft** [comment]
@cppfun , I am closing the ticket. Feel free to reopen if you still have problems.
