### ISSUE TITLE
execute ./eosio_build.sh

### ISSUE THREAD

**Issue by lilinkai** [EOSIO/eos#3108]
🍺  /usr/local/Cellar/boost/1.66.0: 13,101 files, 435.2MB
	Pinning boost libraries.
	Boost 1.66.0 successfully installed @ /usr/local.

	Checking MongoDB C++ driver installation.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   616    0   616    0     0    568      0 --:--:--  0:00:01 --:--:--   567
  0 7535k    0 34370    0     0     74      0 28:58:00  0:07:39 28:50:21     0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
mongo-c-driver-1.9.3/configure: (Empty error message)
tar: Error exit delayed from previous errors.
	Unable to unarchive file mongo-c-driver-1.9.3.tar.gz.
	Exiting now.

**Comment by pacificcode** [comment]
@lilinkai You have a network error and were unable to connect to and clone the github MongoDB C++ driver. Check your network settings or consult with your ISP.
