### ISSUE TITLE
Uncleared instruction under "Create accounts for your smart contracts" of readme.md

### ISSUE THREAD

**Issue by spicynoodle** [EOSIO/eos#311]
[#create-accounts-for-your-smart-contracts](https://github.com/eosio/eos#create-accounts-for-your-smart-contracts)
![](https://user-images.githubusercontent.com/16319106/30000245-c26bde74-9096-11e7-8dab-e7bfba8e263f.png)

**Comment by toonsevrin** [comment]
Weird, I don't see this: ![](https://i.gyazo.com/b95d100218a64b2413ca26d885165919.png)

**Comment by wanderingbort** [comment]
I also don't see the referenced text.  Closing for now.
