### ISSUE TITLE
boost libraries not found - build error on centos 7

### ISSUE THREAD

**Issue by barrage-ivan** [EOSIO/eos#3111]
Hello,

I was getting error while building from source: 

```
Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
Unable to find the requested Boost libraries.

Boost version: 1.66.0

Boost include path: /root/opt/boost_1_66_0/include

The following Boost libraries could not be found:

boost_system
boost_chrono

Some (but not all) of the required Boost libraries were found. You may
need to install these additional Boost libraries. Alternatively, set
BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
to the location of Boost.
Call Stack (most recent call first):
CMakeLists.txt:88 (FIND_PACKAGE)
```

I couldn't get it to work with few workarounds, so I decided to update the `scripts/eosio_build_centos.sh` to use the 1.67 version of boost library. After that my build succeeded. 

OS info:
```
CentOS Linux release 7.5.1804 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core) 
CentOS Linux release 7.5.1804 (Core)
```

**Comment by pacificcode** [comment]
@barrage-ivan EOS.IO is tested using boost 1.66. You may experience unexpected results using boost 1.67. It is recommended to compile EOS.IO as an unprivileged user i.e. not as root. If you run into any further installation issues please capture the complete output of the eosio_build.sh script and paste it here.

**Comment by barrage-ivan** [comment]
Yes, for the initial contact I've run it with root. You are right, I've run setup with unprivileged user, it went fine. Thanks!

**Comment by brightermatter** [comment]
Hi @pacificcode, what is the reason for compiling EOS.IO as an unprivileged user? can you elaborate on that, thx.

**Comment by lazaridiscom** [comment]
@brightermatter , my understanding is that generally, software should be installed as non-root, thus it can be run later as non-root, thus root-access accidents are avoided.
