### ISSUE TITLE
What's the symbol that makes one action unique?

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#3117]
When I use the command `cleos get actions <account_name> -j`,I got three actions which have different receivers, but belong to the same transfer.
I know that the three actions are for accounts who has contract、who is the from account and who is the to account.
Could I use the field `act_digest` to mark one transfer action, because I don't want to write down three repeated actions?

`{
  "actions": [{
      "global_action_seq": 6516,
      "account_action_seq": 1,
      "block_num": 6506,
      "block_time": "2018-05-15T03:43:15.000",
      "action_trace": {
        "receipt": {
          "receiver": "eosio.token",
          "act_digest": "cc3d56ed6ebe9f34a39a5e042c5d6c3a28131c5f60a708b8eaa6518b1a391540",
          "global_sequence": 6516,
          "recv_sequence": 4,
          "auth_sequence": [[
              "user",
              1
            ]
          ]
        },
        "act": {
          "account": "eosio.token",
          "name": "transfer",
          "authorization": [{
              "actor": "user",
              "permission": "active"
            }
          ],
          "data": {
            "from": "user",
            "to": "tester",
            "quantity": "2500.0000 EOS",
            "memo": "m"
          },
          "hex_data": "00000000007015d6000000005c95b1ca40787d010000000004454f5300000000016d"
        },
        "elapsed": 620,
        "cpu_usage": 0,
        "console": "transfer from user to tester 2500.0000 EOS\nuser balance: 17500.0000 EOS\ntester balance: 2500.0000 EOS\n",
        "total_cpu_usage": 0,
        "trx_id": "a4b4d3303c8034dd2298f87c8481a001e009871a16e3365a74703bf138dfdf47",
        "inline_traces": [{
            "receipt": {
              "receiver": "user",
              "act_digest": "cc3d56ed6ebe9f34a39a5e042c5d6c3a28131c5f60a708b8eaa6518b1a391540",
              "global_sequence": 6517,
              "recv_sequence": 2,
              "auth_sequence": [[
                  "user",
                  2
                ]
              ]
            },
            "act": {
              "account": "eosio.token",
              "name": "transfer",
              "authorization": [{
                  "actor": "user",
                  "permission": "active"
                }
              ],
              "data": {
                "from": "user",
                "to": "tester",
                "quantity": "2500.0000 EOS",
                "memo": "m"
              },
              "hex_data": "00000000007015d6000000005c95b1ca40787d010000000004454f5300000000016d"
            },
            "elapsed": 4,
            "cpu_usage": 0,
            "console": "",
            "total_cpu_usage": 0,
            "trx_id": "a4b4d3303c8034dd2298f87c8481a001e009871a16e3365a74703bf138dfdf47",
            "inline_traces": []
          },{
            "receipt": {
              "receiver": "tester",
              "act_digest": "cc3d56ed6ebe9f34a39a5e042c5d6c3a28131c5f60a708b8eaa6518b1a391540",
              "global_sequence": 6518,
              "recv_sequence": 1,
              "auth_sequence": [[
                  "user",
                  3
                ]
              ]
            },
            "act": {
              "account": "eosio.token",
              "name": "transfer",
              "authorization": [{
                  "actor": "user",
                  "permission": "active"
                }
              ],
              "data": {
                "from": "user",
                "to": "tester",
                "quantity": "2500.0000 EOS",
                "memo": "m"
              },
              "hex_data": "00000000007015d6000000005c95b1ca40787d010000000004454f5300000000016d"
            },
            "elapsed": 4,
            "cpu_usage": 0,
            "console": "",
            "total_cpu_usage": 0,
            "trx_id": "a4b4d3303c8034dd2298f87c8481a001e009871a16e3365a74703bf138dfdf47",
            "inline_traces": []
          }
        ]
      }
    },{
      "global_action_seq": 6517,
      "account_action_seq": 2,
      "block_num": 6506,
      "block_time": "2018-05-15T03:43:15.000",
      "action_trace": {
        "receipt": {
          "receiver": "user",
          "act_digest": "cc3d56ed6ebe9f34a39a5e042c5d6c3a28131c5f60a708b8eaa6518b1a391540",
          "global_sequence": 6517,
          "recv_sequence": 2,
          "auth_sequence": [[
              "user",
              2
            ]
          ]
        },
        "act": {
          "account": "eosio.token",
          "name": "transfer",
          "authorization": [{
              "actor": "user",
              "permission": "active"
            }
          ],
          "data": {
            "from": "user",
            "to": "tester",
            "quantity": "2500.0000 EOS",
            "memo": "m"
          },
          "hex_data": "00000000007015d6000000005c95b1ca40787d010000000004454f5300000000016d"
        },
        "elapsed": 4,
        "cpu_usage": 0,
        "console": "",
        "total_cpu_usage": 0,
        "trx_id": "a4b4d3303c8034dd2298f87c8481a001e009871a16e3365a74703bf138dfdf47",
        "inline_traces": []
      }
    },{
      "global_action_seq": 6518,
      "account_action_seq": 3,
      "block_num": 6506,
      "block_time": "2018-05-15T03:43:15.000",
      "action_trace": {
        "receipt": {
          "receiver": "tester",
          "act_digest": "cc3d56ed6ebe9f34a39a5e042c5d6c3a28131c5f60a708b8eaa6518b1a391540",
          "global_sequence": 6518,
          "recv_sequence": 1,
          "auth_sequence": [[
              "user",
              3
            ]
          ]
        },
        "act": {
          "account": "eosio.token",
          "name": "transfer",
          "authorization": [{
              "actor": "user",
              "permission": "active"
            }
          ],
          "data": {
            "from": "user",
            "to": "tester",
            "quantity": "2500.0000 EOS",
            "memo": "m"
          },
          "hex_data": "00000000007015d6000000005c95b1ca40787d010000000004454f5300000000016d"
        },
        "elapsed": 4,
        "cpu_usage": 0,
        "console": "",
        "total_cpu_usage": 0,
        "trx_id": "a4b4d3303c8034dd2298f87c8481a001e009871a16e3365a74703bf138dfdf47",
        "inline_traces": []
      }
    }
  ],
  "last_irreversible_block": 112987
}
`

**Comment by bytemaster** [comment]
Every contract that got executed is listed, if you only care about the "one true transfer" (the one that actually moved funds) then only focus on the action where the eosio.token is the receiver.
