### ISSUE TITLE
How can I get the struct fields from buffer get from db_get_i64?

### ISSUE THREAD

**Issue by Akagi201** [EOSIO/eos#3118]
for example.

The buffer code is as follows.

```
const auto buffer_size = context.db_get_i64(iter, nullptr, 0);
bytes value(buffer_size);
wlog("buffer_size: ${bs}", ("bs", buffer_size));


const auto written_size = context.db_get_i64(iter, value.data(), buffer_size);
assert(written_size == buffer_size);

wlog("data: ${data}", ("data", value));
```

And my buffer struct is.

```
struct contractstat {
    account_name contract;
    std:string code_id;
    std::string status;

    account_name primary_key() const {
      return contract;
    }
 };
```

**Comment by brianjohnson5972** [comment]
Where are you trying to use this code?  Your struct definition looks like you are writing contract code, but your code showing its use is calling context.db_get_i64(...) which looks like you are trying to make changes to the eosio source base.

**Comment by Akagi201** [comment]
@brianjohnson5972 I am writing the logic in the setcode phrase. in `libraries/chain/eosio_contract.cpp`

**Comment by brianjohnson5972** [comment]
Can you tell me what you are trying to accomplish?  Are you writing code that you are hoping to submit  to the EOSIO repo?  Making changes in this location without submitting them would give your node very different behavior from every other node in the blockchain network.

**Comment by Akagi201** [comment]
solved.
