### ISSUE TITLE
Change default vote-weight scale 

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3119]
Currently we use the equation:
```
weight = int64_t(now() / seconds_per_week) / 52.0
```

We should use:
```
weight = int64_t( (now()-block_timestamp_epoch)/seconds_per_week ) / 52.0
```

This will lower the magnitude of the vote weights.

**Comment by andriantolie** [comment]
PR #3199 added to adjust the voting weight
`double weight = int64_t( (now() - (block_timestamp::block_timestamp_epoch / 1000)) / (seconds_per_day * 7) )  / double( 52 ) `

now() is seconds, block_timestamp_epoch is milliseconds

**Comment by andriantolie** [comment]
ATC:
- ensure all unit tests inside eosio.system_tests still pass after the change

**Comment by andriantolie** [comment]
ATC passes
