### ISSUE TITLE
Dockerfile lost under https://github.com/EOSIO/eos/blob/master/Docker/Dockerfile

### ISSUE THREAD

**Issue by macleanliu** [EOSIO/eos#312]
Dockerfile lost under https://github.com/EOSIO/eos/blob/master/Docker/Dockerfile, 404 not found. Anyone can fix this ?

**Comment by toonsevrin** [comment]
This was moved to the root directory as #292 to fix the scope. Anyway it will be moved back to the Docker directory with #308, but you'll have to run the build from the root of the directory (this means you should do something like `docker build -f Docker/Dockerfile -t eosio/eos .`.

**Comment by macleanliu** [comment]
thank for your answer
