### ISSUE TITLE
Create validation tool for FC_REFLECT.

### ISSUE THREAD

**Issue by larryk85** [EOSIO/eos#3127]
Given the current system, we consistently have issues with fields not be reflected or reflected in the wrong order.  These bugs are hard to track down and waste a lot of time, we should have a tool that will compare what is reflected with what the structures actually are.

**Comment by bytemaster** [comment]
Steem had such a tool.  With respect to contracts we should be eating our own dog food and using abi generator.

**Comment by jgiszczak** [comment]
`tools/validate_reflection.py` is now included in the repository.
