### ISSUE TITLE
No head block in fork db, perhaps we need to replay

### ISSUE THREAD

**Issue by wddxzz** [EOSIO/eos#3152]
i want to join a testnet but meet some error.

964146ms thread-0   block_log.cpp:123             open                 ] my->head->block_num(): 1
964159ms thread-0   controller.cpp:1028           startup              ] No head block in fork db, perhaps we need to replay

964312ms thread-0   net_plugin.cpp:1185           process_next_message ] e.to_detail_string(): 8 out_of_range_exception: Out of Range
read datastream of length 1 over by 31
    {"method":"read","len":1,"over":31}
    thread-0  datastream.cpp:6 throw_datastream_range_error
error unpacking fc::sha256
    {"type":"fc::sha256"}
    thread-0  raw.hpp:602 unpack
Error unpacking field chain_id
    {"field":"chain_id"}
    thread-0  raw.hpp:361 operator()
error unpacking eosio::handshake_message
    {"type":"eosio::handshake_message"}
    thread-0  raw.hpp:602 unpack
964312ms thread-0   net_plugin.cpp:1312           request_next_chunk   ] Unable to continue syncing at this time

**Comment by SheldonHH** [comment]
same error for  DAWN-2018-05-16

**Comment by guaiguaihw** [comment]
same error+1

**Comment by chebaogong** [comment]
same error+1

who know how to solve it？

**Comment by djjaron** [comment]
same issue..

ends in error "db.revision(): 84 head->block_num: 84 blog.read_head()->block_num(): 83"

**Comment by BenAlthauser** [comment]
I am getting the same issue on Dawn 4.2.  To get nodeos running, I had to first empty the data dir at ~/.local/share/eosio/nodeos/data (delete "blocks" and "state" folders), then I ran - 

`nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::producer_plugin --plugin eosio::http_plugin --access-control-allow-origin=*`

It appears to be functioning, but I'd much rather be able to start nodeos with my config file.  The fact it errors out on a "nodeos" start command tells me that it's likely hitting an error in the config file as the command line arguments work.

**Comment by EfstaMits** [comment]
@BenAlthauser even if I do what you described it still closes with an error :

**Comment by EfstaMits** [comment]
@BenAlthauser even if I do what you described it still closes with an error :
448729ms thread-0   controller.cpp:261            ~controller_impl     ] db.revision(): 11 head->block_num: 11 blog.read_head()->block_num(): 10 

which means it is database error?  

has someone managed to fixed it? thanks

**Comment by falkon303** [comment]
@EfstaMits This will delete all the blocks, but you may want to try this - 
`nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::producer_plugin --plugin eosio::http_plugin --delete-all-blocks`
If that's not working, something else may be wrong.

**Comment by taokayan** [comment]
Looks like this is because of the data format version doesn't compatible with the version of nodeos. Can you try with the new version?

**Comment by GalaxyGaming72** [comment]
i'm fairly new to eos and i'm using docker to create a block producing node and i've encountered this same error after restarting the container, any ideas what i'm doing wrong?

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com

**Comment by mosjin** [comment]
I encountered same issue on CentOS7.6, is there any ideas please?

**Comment by mosjin** [comment]
I just gited clone the codes today.
