### ISSUE TITLE
push_transaction RPC API, Invalid packed transaction [error unpacking]

### ISSUE THREAD

**Issue by kristieguo** [EOSIO/eos#3159]
Hi, I am trying to create a transaction and broadcast it to local node. I use push_transaction(signed_transaction) api but I was getting the error below:

```
{  
   "code":500,
   "message":"Internal Service Error",
   "error":{  
      "code":3010010,
      "name":"packed_transaction_type_exception",
      "what":"Invalid packed transaction",
      "details":[  
         {  
            "message":"Missing signatures",
            "file":"abi_serializer.hpp",
            "line_number":393,
            "method":"extract"
         },
         {  
            "message":"Failed to deserialize variant",
            "file":"abi_serializer.hpp",
            "line_number":487,
            "method":"from_variant"
         },
         {  
            "message":"Invalid packed transaction",
            "file":"chain_plugin.cpp",
            "line_number":455,
            "method":"push_transaction"
         }
      ]
   }
}
```

The signed transaction I created is like below:

```
{  
   "actions":[  
      {  
         "account":"eosio.token",
         "name":"transfer",
         "authorization":[  
            {  
               "actor":"tester",
               "permission":"active"
            }
         ],
         "data":{  
            "from":"tester",
            "to":"kris",
            "quantity":"1 EOS"
         }
      }
   ],
   "signatures":[  
      "SIG_K1_KeH6wCsnUWRjrfGtqPpXFK4BJArfQ4FwuZARnpVyWkfgdrbrKMgH1msyvrvGyxABYj5UyNpMmipWhpyaruRaRFQbcuDBb4"
   ]
}
```

I am running node locally on dawn 4.0 version. I read the source code and I think I am giving the correct format of the signed transaction, wondering what the problem is. Thanks.

**Comment by bytemaster** [comment]
Likely due to quantity not being "1.0000 EOS" and/or missing "memo" in data section.

**Comment by kristieguo** [comment]
I added memo but the error still occurs. I don't think the problem is about the data section. The error message is "Missing signatures". The code below is how I get signature:

```
let signature = eosjs.modules.ecc.sign('signing tx', privateKey)
```

Should I convert the signed transaction json to hex? But if i use the abi_json_to_bin rpc api to convert the information of my transaction, signature is not included in the transfer params.

**Comment by spartucus** [comment]
The precision of `quantity` HAS TO BE 1 / 10000, here should be 1.0000 EOS, not 1 EOS.
Maybe [EOSDevHelper](https://github.com/OracleChain/EOSDevHelper) will help you.

**Comment by kristieguo** [comment]
ok, I use 1.0000 EOS and generate a hex of the transaction, and then put it as a packed_trx, I got the below error

```
{  
   "code":500,
   "message":"Internal Service Error",
   "error":{  
      "code":3010010,
      "name":"packed_transaction_type_exception",
      "what":"Invalid packed transaction",
      "details":[  
         {  
            "message":"Invalid packed transaction",
            "file":"chain_plugin.cpp",
            "line_number":455,
            "method":"push_transaction"
         },
         {  
            "message":"read datastream of length 41 over by 0",
            "file":"datastream.cpp",
            "line_number":6,
            "method":"throw_datastream_range_error"
         },
         {  
            "message":"error unpacking uint64_t",
            "file":"raw.hpp",
            "line_number":602,
            "method":"unpack"
         },
         {  
            "message":"Error unpacking field value",
            "file":"raw.hpp",
            "line_number":361,
            "method":"operator()"
         },
         {  
            "message":"error unpacking eosio::chain::name",
            "file":"raw.hpp",
            "line_number":602,
            "method":"unpack"
         },
         {  
            "message":"Error unpacking field name",
            "file":"raw.hpp",
            "line_number":361,
            "method":"operator()"
         },
         {  
            "message":"error unpacking eosio::chain::action",
            "file":"raw.hpp",
            "line_number":602,
            "method":"unpack"
         },
         {  
            "message":"Error unpacking field context_free_actions",
            "file":"raw.hpp",
            "line_number":361,
            "method":"operator()"
         },
         {  
            "message":"error unpacking eosio::chain::transaction",
            "file":"raw.hpp",
            "line_number":602,
            "method":"unpack"
         },
         {  
            "message":"error unpacking eosio::chain::transaction",
            "file":"raw.hpp",
            "line_number":646,
            "method":"unpack"
         }
      ]
   }
}
```

The way I do it is as below:

➜  ~ curl  http://127.0.0.1:8888/v1/chain/abi_json_to_bin -X POST -d '{"code":"eosio.token", "action":"transfer", "args":{"from":"tester", "to":"user", "quantity":"1.0000 EOS", "memo":"transfer"}}'

{"binargs":"000000005c95b1ca00000000007015d6102700000000000004454f5300000000087472616e73666572"}%                                                                                                           

➜  ~ curl  http://127.0.0.1:8888/v1/chain/push_transaction -X POST -d '{
               "signatures":[                "SIG_K1_KeH6wCsnUWRjrfGtqPpXFK4BJArfQ4FwuZARnpVyWkfgdrbrKMgH1msyvrvGyxABYj5UyNpMmipWhpyaruRaRFQbcuDBb4"
               ],
               "compression":"none",
               "packed_context_free_data":"",
               "packed_trx": "000000005c95b1ca00000000007015d6102700000000000004454f5300000000087472616e73666572"
            }'

**Comment by Dylan-Phoon** [comment]
+1 getting the same error

**Comment by yupasik** [comment]
+1

**Comment by jcalfee** [comment]
I think fc's unpack buffer is too small:
```json
         {  
            "message":"read datastream of length 41 over by 0",
            "file":"datastream.cpp",
            "line_number":6,
            "method":"throw_datastream_range_error"
         },
```
```c++
  // Stream adapter for use with the fc unpack functionality
  template <uint32_t buffer_len>
  class mb_datastream {
     public:
        mb_datastream( message_buffer<buffer_len>& m ) : mb(m) {}

        inline void skip( size_t s ) { mb.advance_read_ptr(s); }
        inline bool read( char* d, size_t s ) {
          if (mb.bytes_to_read() >= s) {
            mb.read(d, s);
            return true;
          }
          fc::detail::throw_datastream_range_error( "read", mb.bytes_to_read(), s - mb.bytes_to_read());
        }

        inline bool   get( unsigned char& c ) { return mb.read(&c, 1); }
        inline bool   get( char& c ) { return mb.read(&c, 1); }

      private:
        message_buffer<buffer_len>& mb;
  };
```
I'm getting this same error after deploying eosio.token then trying to read it back:
```bash
> api error => { message: 'read datastream of length 14 over by -12',
  file: 'datastream.cpp',
  line_number: 6,
  method: 'throw_datastream_range_error' } http://127.0.0.1:8888/v1/chain/get_code {"account_name":"inita"}
```

**Comment by WeijiaChe** [comment]
Got the same error when trying to read a contract 
```
api error => { message: 'read datastream of length 14 over by -12',
  file: 'datastream.cpp',
  line_number: 6,
  method: 'throw_datastream_range_error' } 
```
Any progress on this?

**Comment by guaiguaihw** [comment]
I have solve the problem, the struct of unbroadcast transaction has changed in dawn4.1/4.2
Like the struct below:
{
    "transaction": transaction struct,
   "signatures": xxxx,
   "compression": "none"
}
For example:
![image](https://user-images.githubusercontent.com/11972366/40602745-4bd2554a-628c-11e8-8781-9219d4296cb1.png)
@kristieguo

**Comment by taokayan** [comment]
Does this problem still exist?

**Comment by ismyhc** [comment]
Im still having this issue. Below is the format I'm using on push transaction. Is this correct?

```
{
  "compression": "none",
  "signatures": [
    "SIG_K1_K2C2qKLbwQ3vGjrYQp89fTNkqHmnbiWPPw6Gg2AxD35o8s3PPrzfFdG7v8v9VpojHFwykt2rZze1BFfP3QQdjppsyQzHsD"
  ],
  "transaction": {
    "ref_block_prefix": 2793985123,
    "net_usage_words": 0,
    "expiration": "2018-06-29T18:45:44.0000",
    "ref_block_num": 3300265,
    "delay_sec": 0,
    "context_free_actions": [
      
    ],
    "transaction_extensions": [
      
    ],
    "actions": [
      {
        "name": "transfer",
        "account": "eosio.token",
        "data": "10b0db269d43917990d45dd351042fe5010000000000000004535953000000000e746573742066726f6d206c796e78",
        "authorization": {
          "actor": "<username>",
          "permission": "active"
        }
      }
    ],
    "context_free_data": [
      
    ],
    "max_cpu_usage_ms": 0
  }
}
```

Always fails with:
```
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3010011,
    "name": "packed_transaction_type_exception",
    "what": "Invalid packed transaction",
    "details": [
      
    ]
  }
}
```

**Comment by ismyhc** [comment]
I was told I need to do a packed transaction if Im using signing offline and user the rpc interface. I think I've successfully packed the trx, but im still getting the same message. Its hard to tell by the error message. I guess its saying that the packed_trx is invalid? Is that the correct assumption?

```
{
  "packed_context_free_data" : [

  ],
  "compression" : "none",
  "signatures" : [
    "SIG_K1_Kida3zYdhCu2JcXzu7S27SgL89y4eJTbfEE6YQum4x2vzBfszbnzozByHxay5SBMHAoQ9f8569Mq1HexyYBboLm1e7uYAL"
  ],
  "packed_trx" : "1ce3365b00000b7320000032f763f0000000010a682343ea3055000572d3ccdcd110b0db269d4391790000a8ed32322f10b0db269d43917990d45dd35142fe5100000004454f530000e746573742066726f6d206c796e78100000000000000000000000000000000"
}
```

**Comment by destiny008** [comment]
@ismyhc where can i find the "packed_trx"?

**Comment by silvercondor** [comment]
I packed the tx via rpc call 'v1/chain/abi_json_to_bin' but still getting the same error 3010010. Full response below

<Response [500]>
{'code': 500, 'message': 'Internal Service Error', 'error': {'code': 3010010, 'name': 'packed_transaction_type_exception', 'what': 'Invalid packed transaction', 'details': [{'message': 'Invalid packed transaction', 'file': 'chain_plugin.cpp', 'line_number': 1457, 'method': 'push_transaction'}, {'message': 'read datastream of length 37 over by -4', 'file': 'datastream.cpp', 'line_number': 6, 'method': 'throw_datastream_range_error'}, {'message': 'error unpacking uint64_t', 'file': 'raw.hpp', 'line_number': 616, 'method': 'unpack'}, {'message': 'Error unpacking field value', 'file': 'raw.hpp', 'line_number': 368, 'method': 'operator()'}, {'message': 'error unpacking eosio::chain::name', 'file': 'raw.hpp', 'line_number': 616, 'method': 'unpack'}, {'message': 'Error unpacking field account', 'file': 'raw.hpp', 'line_number': 368, 'method': 'operator()'}, {'message': 'error unpacking eosio::chain::action', 'file': 'raw.hpp', 'line_number': 616, 'method': 'unpack'}, {'message': 'Error unpacking field context_free_actions', 'file': 'raw.hpp', 'line_number': 368, 'method': 'operator()'}, {'message': 'error unpacking eosio::chain::transaction', 'file': 'raw.hpp', 'line_number': 616, 'method': 'unpack'}, {'message': 'error unpacking eosio::chain::transaction', 'file': 'raw.hpp', 'line_number': 660, 'method':
'unpack'}]}}

**Comment by silvercondor** [comment]
resolved. 

> 
> 
> I packed the tx via rpc call 'v1/chain/abi_json_to_bin' but still getting the same error 3010010. Full response below
> 
> <Response [500]>
> {'code': 500, 'message': 'Internal Service Error', 'error': {'code': 3010010, 'name': 'packed_transaction_type_exception', 'what': 'Invalid packed transaction', 'details': [{'message': 'Invalid packed transaction', 'file': 'chain_plugin.cpp', 'line_number': 1457, 'method': 'push_transaction'}, {'message': 'read datastream of length 37 over by -4', 'file': 'datastream.cpp', 'line_number': 6, 'method': 'throw_datastream_range_error'}, {'message': 'error unpacking uint64_t', 'file': 'raw.hpp', 'line_number': 616, 'method': 'unpack'}, {'message': 'Error unpacking field value', 'file': 'raw.hpp', 'line_number': 368, 'method': 'operator()'}, {'message': 'error unpacking eosio::chain::name', 'file': 'raw.hpp', 'line_number': 616, 'method': 'unpack'}, {'message': 'Error unpacking field account', 'file': 'raw.hpp', 'line_number': 368, 'method': 'operator()'}, {'message': 'error unpacking eosio::chain::action', 'file': 'raw.hpp', 'line_number': 616, 'method': 'unpack'}, {'message': 'Error unpacking field context_free_actions', 'file': 'raw.hpp', 'line_number': 368, 'method': 'operator()'}, {'message': 'error unpacking eosio::chain::transaction', 'file': 'raw.hpp', 'line_number': 616, 'method': 'unpack'}, {'message': 'error unpacking eosio::chain::transaction', 'file': 'raw.hpp', 'line_number': 660, 'method':
> 'unpack'}]}}

Resolved. packed transction is not json_to_abi call but a separate action done on the local machine

**Comment by silvercondor** [comment]
> 
> 
> @silvercondor Could you give me more detail on packed transaction?How could we make those packed_trx with rpc?

from what I know, packing of transaction will not be supported via rpc and has to be done on local machine. You may use a library like eosjs/eosjs2 to pack your transaction or study the library for your own implementation

**Comment by choiceyou** [comment]
I have solved this problem.
I do a packed transaction using signing offline, my problem is on the local signature with 'EosByteWriter'. If you need help, you can ask me questions.

**Comment by RishalEP** [comment]
> I have solved this problem.
> I do a packed transaction using signing offline, my problem is on the local signature with 'EosByteWriter'. If you need help, you can ask me questions.

How can I create a packed transaction?

**Comment by silvercondor** [comment]
> 
> 
> > I have solved this problem.
> > I do a packed transaction using signing offline, my problem is on the local signature with 'EosByteWriter'. If you need help, you can ask me questions.
> 
> How can I create a packed transaction?

What language are you using?

**Comment by RishalEP** [comment]
> > > I have solved this problem.
> > > I do a packed transaction using signing offline, my problem is on the local signature with 'EosByteWriter'. If you need help, you can ask me questions.
> > 
> > 
> > How can I create a packed transaction?
> 
> What language are you using?

python

**Comment by brianjohnson5972** [comment]
Based on @choiceyou 's comment, it sounds like this can be closed.  If there is still a problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by Tanzim74** [comment]
need help kiddos
