### ISSUE TITLE
Online samples of eosc for contract has an issue, samples needs to be updated.

### ISSUE THREAD

**Issue by MatthewPappas** [EOSIO/eos#316]
I believe this:

eosc push message currency transfer '{"from":"currency","to":"tester","quantity":50}' -s currency -s tester -p active@currency

Should be this:

eosc push message currency transfer '{"from":"currency","to":"tester","amount":"50"}' -s currency -s tester -p active@currency

However when I run it I still run into another issue:
matthew@ubuntu2mp:/home/matthew/eos/build> eosc -p $EOSCUSEPORT push message currency transfer '{"from":"currency","to":"tester","amount":"50"}' -s currency -s tester -p active@currency
2251978ms thread-0   main.cpp:544                  operator()           ] Converting argument to binary...
2251979ms thread-0   main.cpp:600                  main                 ] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error
: 10 assert_exception: Assert Exception
account != nullptr: Account not found: active
    {"name":"active"}
    thread-0  chain_controller.cpp:978 require_account

    {"trx":{"refBlockNum":32,"refBlockPrefix":632100820,"expiration":"2017-09-03T19:39:10","scope":["currency","tester"],"readscope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"active","permission":"currency"},{"account":"active","permission":"currency"}],"data":"00000079b822651d00000000c84267a13200000000000000"}],"signatures":[]}}
    thread-0  chain_controller.cpp:263 push_transaction

    {"msg":"10 assert_exception: Assert Exception\naccount != nullptr: Account not found: active\n    {\"name\":\"active\"}\n    thread-0  chain_controller.cpp:978 require_account\n\n    {\"trx\":{\"refBlockNum\":32,\"refBlockPrefix\":632100820,\"expiration\":\"2017-09-03T19:39:10\",\"scope\":[\"currency\",\"tester\"],\"readscope\":[],\"messages\":[{\"code\":\"currency\",\"type\":\"transfer\",\"authorization\":[{\"account\":\"active\",\"permission\":\"currency\"},{\"account\":\"active\",\"permission\":\"currency\"}],\"data\":\"00000079b822651d00000000c84267a13200000000000000\"}],\"signatures\":[]}}\n    thread-0  chain_controller.cpp:263 push_transaction"}
    thread-0  httpc.cpp:113 call

    {"server":"localhost","port":8888,"path":"/v1/chain/push_transaction","postdata":{"refBlockNum":32,"refBlockPrefix":632100820,"expiration":"2017-09-03T19:39:10","scope":["currency","tester"],"readscope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"active","permission":"currency"},{"account":"active","permission":"currency"}],"data":"00000079b822651d00000000c84267a13200000000000000"}],"signatures":[]}}
    thread-0  httpc.cpp:117 call

**Comment by pavybez** [comment]
We found the same issue. it should be amount instead of quantity and secondly it should be currency@active instead of active@currency.

**Comment by sergmetelin** [comment]
@pavybez I think this is fixed now?
@bytemaster would it make more sense to do key@account, not account@key?

**Comment by pavybez** [comment]
Yes this is fixed now and merged. Documentation has been updated (I believe) to reflect that we need to use account@key.
