### ISSUE TITLE
cleos get servants gets error "Account History API plugin is not enabled"

### ISSUE THREAD

**Issue by cj-oci** [EOSIO/eos#3160]
"cleos get servants" returns error:

Ensure that you have eosio::history_api_plugin added to your node's configuration!
Error Details:
History API plugin is not enabled

To reproduce:
1.) Run cleos test:
             tests/nodeos_run_test.py -v --dont-kill
2.) run get servants command:
             programs/cleos/cleos --url http://localhost:8888  --wallet-url http://localhost:8899 get servants eosio

**Comment by tbfleming** [comment]
Fixed in #3253
