### ISSUE TITLE
cleos get currency stats isn't working

### ISSUE THREAD

**Issue by cj-oci** [EOSIO/eos#3163]
cleos get currency stats returns error:

Error 3060003: Contract Table Query Exception
Most likely, the given table doesn't' exist in the blockchain.
Error Details:
Table stat is not specified in the ABI

To reproduce:
1.) Run cleos test:
             tests/nodeos_run_test.py -v --dont-kill
2.) run get currency stats command:
             programs/cleos/cleos --url http://localhost:8888 --wallet-url http://localhost:8899 get currency stats currency1111 CUR

**Comment by tbfleming** [comment]
This works with master (a7d77526797b8a7747b4a074b1070fbbe3c24c7d):
```
$ programs/cleos/cleos --url http://localhost:8888 --wallet-url http://localhost:8899 get currency stats currency1111 CUR
{
  "CUR": {
    "supply": "100000.0000 CUR",
    "max_supply": "100000.0000 CUR",
    "issuer": "currency1111"
  }
}
```

**Comment by cj-oci** [comment]
Yes confirming it works now. Closing issue.
