### ISSUE TITLE
controller_impl::on_irreversible called multiple times with same block

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3172]
Occasionally on_irreversible is called multiple times with the same block which means the fork_db is signaling it multiple times. It seems to happen at the start of every chain and occasionally when switching forks. 

Under normal non-forking operation it doesn't seem to happen.

For now the handler simply suppresses it, but we should probably avoid signaling it multiple times to begin with.

**Comment by swatanabe-b1** [comment]
The code in question has been refactored significantly, and this issue is no longer relevant.  As of 9463efdfe2672e3058ac5701f01fbdd5525afada, controller_impl::on_irreversible no longer exists.
