### ISSUE TITLE
INLINE_ACTION_SENDER authentication error

### ISSUE THREAD

**Issue by basarrcan** [EOSIO/eos#3177]
```
 INLINE_ACTION_SENDER(eosio::token, transfer)( N(eosio.token), {owner,N(active)},
                                                       { owner, _self, quant, std::string("registry") } );
```

I use this in an action of my contract. When i try to push my action, it gives authentication error.

cleos push action mycontract action '["...... "owner"]' -p owner

Error to be exact:
```
Error 3050000: action exception
Error Details:
inline action's authorizations include a non-existent permission: {permission}

```

Note: I saw another issue on a similar subject but I couldn't get the solution.

**Comment by bytemaster** [comment]
Owner needs to give _self@eosio.code enough weight in the active authority for this to work.

**Comment by deba10106** [comment]
I'm getting this same error while running cleos push action currency create '{"issuer":"currency", "maximum_supply":"10000.0000 CUR", "can_freeze":"0", "can_recall":"0", "can_whitelist":"0"}' -p currency!!

In my case error 3050000: action exception

Unknown action create in contract currency.

**Comment by deba10106** [comment]
got the same after running cleos push action currency create '{"issuer":"currency", "maximum_supply":"10000.0000 CUR"}' -p currency!!
