### ISSUE TITLE
Efficient detection of '.' in names prohibited from eosio.system

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3187]
This should be performed with bitmath vs string operations.

**Comment by brianjohnson5972** [comment]
Once we reach steady-state (after all existing tokens imported and accounts created), won't newaccount processing be an insignificant percentage of the processing?

**Comment by taokayan** [comment]
Please ignore my pull request #3276

**Comment by taokayan** [comment]
Pull request https://github.com/EOSIO/eos/pull/3290 created for this. Please review.
