### ISSUE TITLE
I get an error on ./eosio_build.sh

### ISSUE THREAD

**Issue by lilinkai** [EOSIO/eos#3196]
Scanning dependencies of target net_api_plugin
[ 97%] Built target history_api_plugin
Undefined symbols for architecture x86_64:
  "_libintl_bindtextdomain", referenced from:
      _main in main.cpp.o
  "_libintl_gettext", referenced from:
      eosio::client::localize::localized_with_variant(char const*, fc::variant_object const&) in main.cpp.o
      eosio::client::localize::localized_with_variant(char const*, fc::variant_object const&) in help_text.cpp.o
  "_libintl_setlocale", referenced from:
      _main in main.cpp.o
  "_libintl_textdomain", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [programs/cleos/cleos] Error 1
make[1]: *** [programs/cleos/CMakeFiles/cleos.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Built target unit_test
[ 98%] Building CXX object plugins/net_api_plugin/CMakeFiles/net_api_plugin.dir/net_api_plugin.cpp.o
[ 98%] Linking CXX static library libnet_api_plugin.a
[ 98%] Built target net_api_plugin
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by jgiszczak** [comment]
See #2174.
