### ISSUE TITLE
Mac OS 10.13.3 build error "path mongo-cxx-driver already exists"

### ISSUE THREAD

**Issue by jivin** [EOSIO/eos#3197]
when I build Eos use the command with mac os bellow:

> git clone https://github.com/eosio/eos --recursive
> cd eos
> ./eosio_build.sh

I get below error, and do somebody know how to solve it ?

> libtool: install: /usr/bin/install -c .libs/libmongoc-1.0.0.dylib /usr/local/lib/libmongoc-1.0.0.dylib
> libtool: install: (cd /usr/local/lib && { ln -s -f libmongoc-1.0.0.dylib libmongoc-1.0.dylib || { rm -f libmongoc-1.0.dylib && ln -s libmongoc-1.0.0.dylib libmongoc-1.0.dylib; }; })
> libtool: install: /usr/bin/install -c .libs/libmongoc-1.0.lai /usr/local/lib/libmongoc-1.0.la
> libtool: install: /usr/bin/install -c .libs/libmongoc-1.0.a /usr/local/lib/libmongoc-1.0.a
> libtool: install: chmod 644 /usr/local/lib/libmongoc-1.0.a
> libtool: install: ranlib /usr/local/lib/libmongoc-1.0.a
> /Library/Developer/CommandLineTools/usr/bin/ranlib: file: /usr/local/lib/libmongoc-1.0.a(libmongoc_la-mongoc-linux-distro-scanner.o) has no symbols
>  build/autotools/install-sh -c -d '/usr/local/bin'
>   /bin/sh ./libtool   --mode=install /usr/bin/install -c mongoc-stat '/usr/local/bin'
> libtool: install: /usr/bin/install -c .libs/mongoc-stat /usr/local/bin/mongoc-stat
> /Library/Developer/CommandLineTools/usr/bin/make  install-exec-hook
> build/autotools/install-sh -c -d /usr/local/lib/cmake/libmongoc-1.0
> cp -f build/cmake/libmongoc-1.0-config.cmake /usr/local/lib/cmake/libmongoc-1.0
> cp -f build/cmake/libmongoc-1.0-config-version.cmake /usr/local/lib/cmake/libmongoc-1.0
> if [ ! -z "1" ]; then                                                                      \
> 	  rm -rf /usr/local/lib/cmake/libmongoc-static-1.0;                                                  \
> 	  build/autotools/install-sh -c -d /usr/local/lib/cmake/libmongoc-static-1.0;                                              \
> 	  cd /usr/local/lib;                                                                                 \
> 	  rm -f libmongoc-static-1.0.a;                                                                           \
> 	  ln -s libmongoc-1.0.a libmongoc-static-1.0.a;                                                         \
> 	  cp -f /tmp/mongo-c-driver-1.9.3/build/cmake/libmongoc-static-1.0-config.cmake cmake/libmongoc-static-1.0;         \
> 	  cp -f /tmp/mongo-c-driver-1.9.3/build/cmake/libmongoc-static-1.0-config-version.cmake cmake/libmongoc-static-1.0; \
> 	fi
>  build/autotools/install-sh -c -d '/usr/local/include/libmongoc-1.0'
>  /usr/bin/install -c -m 644 src/mongoc/mongoc-apm.h src/mongoc/mongoc-bulk-operation.h src/mongoc/mongoc-change-stream.h src/mongoc/mongoc-client.h src/mongoc/mongoc-client-pool.h src/mongoc/mongoc-collection.h src/mongoc/mongoc-cursor.h src/mongoc/mongoc-database.h src/mongoc/mongoc-error.h src/mongoc/mongoc-find-and-modify.h src/mongoc/mongoc-flags.h src/mongoc/mongoc-gridfs-file.h src/mongoc/mongoc-gridfs-file-list.h src/mongoc/mongoc-gridfs-file-page.h src/mongoc/mongoc-gridfs.h src/mongoc/mongoc.h src/mongoc/mongoc-handshake.h src/mongoc/mongoc-host-list.h src/mongoc/mongoc-index.h src/mongoc/mongoc-init.h src/mongoc/mongoc-iovec.h src/mongoc/mongoc-log.h src/mongoc/mongoc-macros.h src/mongoc/mongoc-matcher.h src/mongoc/mongoc-opcode.h src/mongoc/mongoc-rand.h src/mongoc/mongoc-read-concern.h src/mongoc/mongoc-read-prefs.h src/mongoc/mongoc-server-description.h src/mongoc/mongoc-client-session.h src/mongoc/mongoc-socket.h src/mongoc/mongoc-ssl.h src/mongoc/mongoc-stream-buffered.h src/mongoc/mongoc-stream-file.h src/mongoc/mongoc-stream-gridfs.h src/mongoc/mongoc-stream.h src/mongoc/mongoc-stream-socket.h src/mongoc/mongoc-stream-tls.h src/mongoc/mongoc-stream-tls-libressl.h src/mongoc/mongoc-stream-tls-openssl.h '/usr/local/include/libmongoc-1.0'
>  /usr/bin/install -c -m 644 src/mongoc/mongoc-stream-tls-secure-channel.h src/mongoc/mongoc-stream-tls-secure-transport.h src/mongoc/mongoc-topology-description.h src/mongoc/mongoc-uri.h src/mongoc/mongoc-version-functions.h src/mongoc/mongoc-version.h src/mongoc/mongoc-write-concern.h src/mongoc/utlist.h src/mongoc/op-delete.def src/mongoc/op-get-more.def src/mongoc/op-header.def src/mongoc/op-insert.def src/mongoc/op-kill-cursors.def src/mongoc/op-msg.def src/mongoc/op-query.def src/mongoc/op-reply.def src/mongoc/op-reply-header.def src/mongoc/op-update.def src/mongoc/op-compressed.def src/mongoc/mongoc-counters.defs src/mongoc/mongoc-config.h '/usr/local/include/libmongoc-1.0'
>  build/autotools/install-sh -c -d '/usr/local/share/doc/mongo-c-driver'
>  /usr/bin/install -c -m 644 COPYING NEWS README.rst THIRD_PARTY_NOTICES '/usr/local/share/doc/mongo-c-driver'
>  build/autotools/install-sh -c -d '/usr/local/lib/pkgconfig'
>  /usr/bin/install -c -m 644 ./src/libmongoc-1.0.pc ./src/libmongoc-ssl-1.0.pc ./src/libmongoc-static-1.0.pc '/usr/local/lib/pkgconfig'
> fatal: destination path 'mongo-cxx-driver' already exists and is not an empty directory.
> 	Unable to clone MongoDB C++ driver at this time.
> 	Exiting now.
>

**Comment by liukunyu** [comment]
i have the them problem,need help

**Comment by pacificcode** [comment]
@jivin @liukunyu try the following:

sudo rm -rf /tmp/mongo*

**Comment by jivin** [comment]
@pacificcode fixed, thanks

**Comment by trungtt1981** [comment]
@pacificcode 
Thanks so much for your hint.
I can overcome the build error `Unable to clone MongoDB C++ driver at this time`.
However, still comes up with a new error:

```
[ 67%] Linking CXX static library libmongocxx-static.a
[ 67%] Built target mongocxx
[ 69%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/result/bulk_write.cpp.o
[ 69%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/result/delete.cpp.o
[ 69%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/result/gridfs/upload.cpp.o
[ 70%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/result/insert_many.cpp.o
[ 70%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/result/insert_one.cpp.o
[ 70%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/result/replace_one.cpp.o
[ 71%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/result/update.cpp.o
[ 71%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/uri.cpp.o
[ 71%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/validation_criteria.cpp.o
[ 73%] Building CXX object src/mongocxx/CMakeFiles/mongocxx_mocked.dir/write_concern.cpp.o
[ 73%] Linking CXX static library libmongocxx-mocked.a
[ 73%] Built target mongocxx_mocked
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
	Error compiling MongoDB C++ driver.
	Exiting now.
```

Look forward to your response.
