### ISSUE TITLE
Implement Missing Permission Interface for EOSC

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#320]
```
eosc set account permission authority ${ACCOUNT} ${PERMISSION_NAME} ${AUTH} ?{PARENT_PERMISSION_NAME}
eosc set action permission ${ACCOUNT} ${CODE} ?{ACTION}  ${PERMISSION_NAME}
```

${AUTH} is a JSON blob containing an Authority structure.

if ${PERMISSION_NAME} is null then it should delete the link.
if ${PARENT_PERMISSION_NAME} is unspecified then it defaults to 'active'

**Comment by nathanhourt** [comment]
Dupe: https://github.com/EOSIO/eos/issues/185
