### ISSUE TITLE
How can I get my contract currency balance with c++ code?

### ISSUE THREAD

**Issue by yang24201** [EOSIO/eos#3201]
I want to get my contract currency balance within my contract code, but the `eosio::account::get (account_balance &acnt)` cann't use, so how can I do that?

**Comment by wsdfz** [comment]
Also need to get the other user's account balance.

It can get by "cleos get currency balance eosio.token XXX" by command. But do not find a way in contract.

**Comment by taokayan** [comment]
Please refer to the system contract eosio.token.cpp & eosio.token.hpp to get the currency balance table

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
