### ISSUE TITLE
Proposal: Basic contracts library for AssemblyScript

### ISSUE THREAD

**Issue by toonsevrin** [EOSIO/eos#3204]
__EDIT: You can join the discussion in the [telegram group](https://t.me/joinchat/GhN4MxBTQfA4HN_Cuk_aEA) and start contributing [here](https://github.com/eos-assemblyscript)!__

### Motivation
C++ is a barrier for the younger (or less experienced) under us. I think supporting a simpler language will enable a lot of these developers to start playing with eos as well.

### Description
[AssemblyScript](https://github.com/AssemblyScript/assemblyscript) allows the compilation of strictly typed TypeScript to WebAssembly with Binaryen. It's still in active development but I'm pretty sure the basic stuff is already in place.

I propose an AssemblyScript library containing the essential components from [eosiolib](https://github.com/EOSIO/eos/tree/master/contracts/eosiolib) to begin with and over time introduce better database support and all that.

Developing this minimal library should not be that difficult (especially compared to the benefits that come from it).

### Questions
The answers to the following problems are useful for supporting any language.

#### What parts of the eosiolib are essential?
__Serialization__
Stuff like action arguments have to be deserialized from a standard format to an internal representation (for example, a struct). The deserialization and serialization library should eventually cover all datatypes (structs, ints, strings, names..).

#### How is context related stuff done, like print.h?
All functions are imported from [a webassembly module](https://webassembly.org/docs/modules/#imports) called "env". These functions only support fixed size  parameters, so you have to pass memory pointers.

__Printing__
Uses the import `env.prints(pointer: i32): void`. The referenced string should be utf-8 encoded with null termination. There are also other functions for printing numbers..

__Entrypoint__
Every contract must export the `apply(receiver: u64, code: u64, action: u64): void` function.

To fetch the actual action data, you need to use a combination of the following imports:
- `env.action_data_size(): i32` fetches the byte length of the action data
- `env.read_action_data(msg: i32, len: i32) i32` stores len bytes of the action data to the msg pointer. Returns the number of bytes copied?
To serialize/deserialize the action data, see serialisation.

You can fetch the actual contract account through the `current_receiver(): u64` call. Comparing this to the apply receiver ensures that you're handling the right actions.

__Database__
The database functions which can be imported are listed [here](https://github.com/EOSIO/eos/blob/2f2c8c7e3811caca178a7553192c8fe59a22576d/contracts/eosiolib/db.h) or/and [here](https://github.com/EOSIO/eos/blob/cd0b147910af4e84dd079c934dbf9765dae75cd7/libraries/chain/wasm_interface.cpp).

__Time__
The import `current_time(): u64` returns the timestamp of the current block. (I'm uncertain about the freedom producers have in deviating from the real time when they set this timestamp)

__Inline transactions__
`send_inline(serialized_action: u32, size: u32): void` sends an inline action in the same context as the parent transaction. The serialized_action is a memory pointer to the start of the serialized action.

**Comment by SonicAgamemnon** [comment]
This is wonderful: Enabling even partial access for TypeScript developers opens up a significant market.

**Comment by toonsevrin** [comment]
I'm willing to implement this myself if there's a team member who can address questions when they come up.

**Comment by kesar** [comment]
@toonsevrin love this idea. I think it will be a great project to fund with the Worker Proposals as soon as they are available  👏

**Comment by toonsevrin** [comment]
Hi everyone! 

It took about 40 lines to write a working [Hello World](https://gist.github.com/toonsevrin/94734d39f7ee9441159ddcd7a844837a) contract in AssemblyScript!
 It could be written in 4 if the redundant stuff is extracted to a library.

Supporting AssemblyScript as a secondary language is thus very doable!

But, there were a couple of hickups:
- AssemblyScript strings are utf-16 encoded. This means that conversion was required to print them.
- The binary size was large (6000bytes compared to 3000 bytes for the c++ helloworld) and the execution was slow (3-6ms compared to 1ms in c++)
- The AssemblyScript standard library prints its errors to an env.abort function, which does not exist in the eos runtime. This means that this function has to be implemented manually after compilation (as there's no way to do it beforehand).

These issues make AssemblyScript a lot less attractive compared to c++ right now but, in my opinion, all of these issues can be solved by working together with the AssemblyScript team.

**Comment by learnforpractice** [comment]
Not bad, keep thinking different!

**Comment by toonsevrin** [comment]
_UPDATE_
The AssemblyScript team has jumped on the issues mentioned above, big thanks to them! Two of the issues are already resolved:
* Changing to a simpler memory allocator (one which does not deallocate memory) dropped the size to 4100 bytes and the execution time to 0.7ms!
* The env.abort issue is resolved (you can map it to an internal function with the compiler)

Up next: Database and inline contract call support

**Comment by metrue** [comment]
@toonsevrin 

This experiment is so cool, I just asked a related question in EOS channel few days ago,  and I got  response from @abourget .
```
The go toolchain is not ready and contracts would be over 9M, which wouldn't fit in a transaction. Too much runtime stuff, which makes C++ (and eventually Rust) a better fit.
```

not totally understand what he said, but I think technically we can do it I think.

**Comment by toonsevrin** [comment]
@metrue the way golang targets webassembly is very interesting, but it does create a heavy binary (1MB+). 

First of all: AssemblyScript does not have this problem, our test contract was under 1KB.

Secondly: golang may eventually split the binary up into two: One containing the runtime, the other one containing the actual program. That could make golang a viable language for contract development as well. I'd love to chat with @abourget about the feasability of this.

**Comment by toonsevrin** [comment]
@metrue that repo is not in use yet. I'll place a message here once it is.

**Comment by metrue** [comment]
@toonsevrin I see, how about this gist you list above https://gist.github.com/toonsevrin/94734d39f7ee9441159ddcd7a844837a, is it workable one? and how to get it up and run?

**Comment by toonsevrin** [comment]
Hi Metrue, here's a much simpler version of that contract: https://gist.github.com/toonsevrin/26498311ee024afbca0d890badf5f4f8

My apologies for the worst build instructions ever written ;)

**Comment by metrue** [comment]
@toonsevrin awesome, thanks.

**Comment by Hodles** [comment]
Absolutely support for higher level languages would greatly accelerate the adoption of EOS as a DAPP platform.  When the worker proposal system is in place, it's def something I will personally be voting for.

**Comment by ellipticasec** [comment]
That is very very exciting =)

**Comment by Hodles** [comment]
FYI, zilliqa block chain have proposed a smart contract specific language, which would also be a nice to have

https://arxiv.org/pdf/1801.00687.pdf

**Comment by MaxGraey** [comment]
AssemblyScript now support full set of operator overloading. So just imagine how looks like contracts will be:

```ts
@action
@onlyOwner
export function transfer(from: AccountName, to: AccountName, quantity: u64): void {
  Account.get(from) >> quantity >> Account.get(to);
}
```

More details of realization with some limitation (which resolve in future) you can find here:
https://webassembly.studio/?f=ohiz1qhiovg

**Comment by toonsevrin** [comment]
@MaxGraey that's awesome! Not sure if this would simplify things for developers though (because there's more syntax they have to learn).
