### ISSUE TITLE
Test multiple name auctions going in parallel

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3208]
- [x] verify that only the highest bid can close each day
- [x] verify that a new bid on highest bid postpones closing of the highest bid by 24 hours
- [ ] verify that no bids close if there isn't one
- [x] verify balances of bidders are properly billed and refunded when outbid 
- [x] verify suffix can create *.suffix accounts

**Comment by bytemaster** [comment]
See existing test at end of eosio_system_tests.cpp

**Comment by arhag** [comment]
Fixed by #3206
