### ISSUE TITLE
Account API for Smart Contract Developers

### ISSUE THREAD

**Issue by andriantolie** [EOSIO/eos#321]
There are currently 6 API categories in EOS Docs Roadmap for Smart Contract Developer's Reference, which are:
- Account API
- Console API
- Database API
- Math API
- Message API
- Token API

Referencing to current contract library code found inside contracts/eoslib directory, we can do the following mapping:
- Account API
- Console API -> print.h and print.hpp
- Database API -> db.h and db.hpp
- Math API -> math.h and math.hpp
- Message API -> message.h and message.hpp
- Token API -> token.hpp

However, I can't find any file that corresponds to Account API in contracts/eoslib. Does it mean that Account API have not been implemented yet by now? Or could it be that Account API doesn't exist and it just a line of error added to the list? Clarification on this case is really appreciated. Thanks!

**Comment by thomasbcox** [comment]
@bytemaster is there an answer to this?

**Comment by bytemaster** [comment]
Account API may not be implemented it would provide access to:
1. an account's permission tables
2. an account's balance (provided it is in scope)
3. other information available to native code 

I would say that the documentation at this point should simply describe the type of information that will be available and an "TODO" sign.

**Comment by heifner** [comment]
Closing as we moved this to STAT-49 Github Issue #638
