### ISSUE TITLE
abi_bin_to_json with bad data crashes nodeos

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#3219]
Reproduction for dawn-v4.0.0. I haven't tried to reproduce with 4.1 yet.

```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"code":"eosio.token","action":"issue","binargs":"ee6fff5a5c02c55b6304000000000100a6823403ea3055000000572d3ccdcd0100000000007015d600000000a8ed32322a00000000007015d6000000005c95b1ca102700000000000004454f53000000000968656c6c6f206d616e00"}' \
  http://localhost:8888/v1/chain/abi_bin_to_json
```

```
Floating point exception (core dumped)
```

~~I suspect the fault happens when converting double to string. May need to migrate serialization away from native floating point types to float*_t.~~ edit: token issue abi doesn't use floating point

Reported on the EOS Developers telegram:

![image](https://user-images.githubusercontent.com/418464/40263718-8c4f7dd2-5ae4-11e8-8f7c-fb6db1e82354.png)

![image](https://user-images.githubusercontent.com/418464/40263722-9bfb3c9e-5ae4-11e8-8483-dda1f5eeb807.png)

![image](https://user-images.githubusercontent.com/418464/40263726-a32fff7c-5ae4-11e8-87ce-a21393305be0.png)

**Comment by taokayan** [comment]
Looks like it's because the asset's precision is zero when asset::to_string() is invoked.
