### ISSUE TITLE
Dawn-v4.1.0 Error unpacking field producer_to_last_produced

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eos#3221]
This error occur while running `nodeos`
```
size.value*(sizeof(K)+sizeof(V)) < MAX_ARRAY_ALLOC_SIZE: 
    {}
    thread-0  flat.hpp:48 unpack
Error unpacking field producer_to_last_produced
    {"field":"producer_to_last_produced"}
    thread-0  raw.hpp:361 operator()
error unpacking eosio::chain::block_state
    {"type":"eosio::chain::block_state"}
    thread-0  raw.hpp:602 unpack
```

**Comment by SheldonHH** [comment]
solved by cleaning up data and shared_mem

**Comment by winlin** [comment]
we also suffer this problem dawn-v4.1.0

**Comment by winlin** [comment]
I just delete the shared_mem and get the follow error:

`{"log":"2504640ms thread-0   fork_database.cpp:220         remove               ] my-\u003eindex.size(): 59 \n","stream":"stderr","time":"2018-05-23T04:41:44.641006395Z"}
{"log":"2504640ms thread-0   controller.cpp:800            push_block           ] 13 St9exception: boost::interprocess::bad_alloc\n","stream":"stderr","time":"2018-05-23T04:41:44.641043691Z"}
{"log":"boost::interprocess::bad_alloc: \n","stream":"stderr","time":"2018-05-23T04:41:44.641048682Z"}
{"log":"    {\"what\":\"boost::interprocess::bad_alloc\"}\n","stream":"stderr","time":"2018-05-23T04:41:44.641051888Z"}
{"log":"    thread-0  controller.cpp:789 apply_block\n","stream":"stderr","time":"2018-05-23T04:41:44.641055508Z"}
{"log":"2504640ms thread-0   chain_plugin.cpp:262          plugin_startup       ] 13 St9exception: boost::interprocess::bad_alloc\n","stream":"stderr","time":"2018-05-23T04:41:44.641058732Z"}
{"log":"boost::interprocess::bad_alloc: \n","stream":"stderr","time":"2018-05-23T04:41:44.641062038Z"}
{"log":"    {\"what\":\"boost::interprocess::bad_alloc\"}\n","stream":"stderr","time":"2018-05-23T04:41:44.641065729Z"}
{"log":"    thread-0  controller.cpp:789 apply_block\n","stream":"stderr","time":"2018-05-23T04:41:44.641068794Z"}
{"log":"rethrow\n","stream":"stderr","time":"2018-05-23T04:41:44.64107174Z"}
{"log":"    {}\n","stream":"stderr","time":"2018-05-23T04:41:44.641074575Z"}
{"log":"    thread-0  controller.cpp:800 push_block\n","stream":"stderr","time":"2018-05-23T04:41:44.641077374Z"}
{"log":"2504640ms thread-0   chain_plugin.cpp:262          plugin_startup       ] my-\u003egenesis_file.generic_string(): /opt/eosio/bin/data-dir/genesis.json \n","stream":"stderr","time":"2018-05-23T04:41:44.64108029Z"}
{"log":"2504641ms thread-0   fork_database.cpp:94          close                ] states.size(): 59 \n","stream":"stderr","time":"2018-05-23T04:41:44.641967264Z"}
{"log":"2504641ms thread-0   controller.cpp:218            ~controller_impl     ] db.revision(): 200628 head-\u003eblock_num: 200628 blog.read_head()-\u003eblock_num(): 285446 \n","stream":"stderr","time":"2018-05-23T04:41:44.642048296Z"}
{"log":"2506280ms thread-0   main.cpp:99                   main                 ] 13 St9exception: boost::interprocess::bad_alloc\n","stream":"stderr","time":"2018-05-23T04:41:46.280570018Z"}
{"log":"boost::interprocess::bad_alloc: \n","stream":"stderr","time":"2018-05-23T04:41:46.280616161Z"}
{"log":"    {\"what\":\"boost::interprocess::bad_alloc\"}\n","stream":"stderr","time":"2018-05-23T04:41:46.280622169Z"}
{"log":"    thread-0  controller.cpp:789 apply_block\n","stream":"stderr","time":"2018-05-23T04:41:46.280625543Z"}
{"log":"rethrow\n","stream":"stderr","time":"2018-05-23T04:41:46.280628649Z"}
{"log":"    {}\n","stream":"stderr","time":"2018-05-23T04:41:46.280631482Z"}
{"log":"    thread-0  controller.cpp:800 push_block\n","stream":"stderr","time":"2018-05-23T04:41:46.28063439Z"}
{"log":"rethrow\n","stream":"stderr","time":"2018-05-23T04:41:46.280645695Z"}
{"log":"    {\"my-\u003egenesis_file.generic_string()\":\"/opt/eosio/bin/data-dir/genesis.json\"}\n","stream":"stderr","time":"2018-05-23T04:41:46.280670361Z"}
{"log":"    thread-0  chain_plugin.cpp:262 plugin_startup\n","stream":"stderr","time":"2018-05-23T04:41:46.280675043Z"}
`
