### ISSUE TITLE
hello demo ""

### ISSUE THREAD

**Issue by baizhiwen** [EOSIO/eos#3222]
localhost:hello uu$ cleos push action baizhiwen hi '{"user":"xiaohong"}' -p baizhiwen
executed transaction: 49f90143d5ff13ce86a9e0cd754eab2bd6a95641d0dccec6c7cad351b6c0c656  96 bytes  172 us
#     baizhiwen <= baizhiwen::hi                ""
warning: transaction executed locally, but may not be confirmed by the network yet

**Comment by taokayan** [comment]
This is expected.
