### ISSUE TITLE
Allow inject CORE_SYMBOL_NAME from environment variables

### ISSUE THREAD

**Issue by kesar** [EOSIO/eos#3225]
In order to avoid having a different CMakelists in community repo & block1, I will suggest to use environment for the CORE_SYMBOL_NAME.

That file will tends to change over the time, and we may need to solve potential merge conflicts.

**Comment by kesar** [comment]
we can anyhow run the script passing a param, so its not a big deal.

**Comment by matthewdarwin** [comment]
./eosio_build.sh -DCORE_SYMBOL_NAME=EOS

**Comment by Ray-cheng** [comment]
Now the newest EOS version change this argument to **-sXXX** format，ex: -sEOS.
