### ISSUE TITLE
bios-boot-tutorial fixes

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#3226]
From code review of #3212 (@heifner and @jafri)

![image](https://user-images.githubusercontent.com/418464/40270088-4eb1d940-5b55-11e8-8f68-d0a053ba58be.png)

**Comment by kaidiren** [comment]
https://github.com/EOSIO/eos/pull/3233

**Comment by tbfleming** [comment]
In-person discussion: issuer will remain eosio
