### ISSUE TITLE
abi generator emits type of account_name as uint64 instead of name

### ISSUE THREAD

**Issue by jeongkyu** [EOSIO/eos#3227]
I tried to build and run hello contract, but got the following error.
```
$ eosiocpp -n hello
$ cd hello
$ eosiocpp -o hello.wast hello.cpp
$ eosiocpp -g hello.abi hello.cpp
$ cleos create account eosio hello.code ...
$ cleos set contract hello.code ../hello -p hello.code
$ cleos push action hello.code hi '["user"]' -p user

Error 3050002: Invalid Action Arguments
Ensure that your arguments follow the contract abi!
You can check the contract's abi by using 'cleos get code' command.
Error Details:
'["user"]' is invalid args for action 'hi' code 'hello.code'. expected '[{"name":"user","type":"account_name"}]'
Couldn't parse uint64_t
```

The error seems to be caused by the incorrect type of account_name in hello.abi - abi generator used base type of account_name defined in eosiolib/types.h 

```
$ cat hello.abi
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-05-19T18:38:49",
  "version": "",
  "types": [{
      "new_type_name": "account_name",
      "type": "uint64"
    }
  ],
...
```
Once I changed the type into `name` and re-set the contract (after updating hello.wast), it worked as expected.

```
$ cleos push action hello.code hi '["user"]' -p user
executed transaction: c6a2e60e9044b023929b35eefd9b7a37925fe787513f7a0cc0dc76b5ab4c57d5  104 bytes  265 us
#    hello.code <= hello.code::hi               {"user":"user"}
>> Hello,  user
```

**Comment by ximinchao** [comment]
I encoutered same problem, and I found official contract's (eosio.token etc.) abi files start with:
"version": "eosio::abi/1.0",
  "types": [{
      "new_type_name": "account_name",
      "type": "name"
    }
  ],......
BUT if I use:
eosiocpp -g hello.abi hello.cpp
I got the same as @jeongkyu :
"____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-05-19T18:38:49",
  "version": "",
  "types": [{
      "new_type_name": "account_name",
      "type": "uint64"
    }
  ]
Is there some other way to generate abi file with version and correct name declear?

**Comment by ximinchao** [comment]
I encoutered same problem, and I found official contract's (eosio.token etc.) abi files start with:
`"version": "eosio::abi/1.0",
"types": [{
"new_type_name": "account_name",
"type": "name"
}
],......`
BUT if I use:
eosiocpp -g hello.abi hello.cpp
I got the same as @jeongkyu :
`"____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-05-19T18:38:49",
"version": "",
"types": [{
"new_type_name": "account_name",
"type": "uint64"
}
]`
Is there some other way to generate abi file with version and correct name declear?

**Comment by ximinchao** [comment]
I found another problem: if I just change the 
`"new_type_name": "account_name",
 "type": "uint64"`
to
`"new_type_name": "account_name",
 "type": "name"`
I will get a mistake when I try to get table (if the table contains account_name filed):
`cleos get table mycontract myscope mytable`

**Comment by lidancheng** [comment]
encoutered same problem when run the hello contract.
the eos version dawn 4.1.
