### ISSUE TITLE
get transaction from block

### ISSUE THREAD

**Issue by wangzehui123456** [EOSIO/eos#3228]
I want to find transaction from block. The id in transactions is not the actual transactionId, how get I found the transaction?
{
    "previous": "0000d2893079a485511d7b83cbd66b4d406b42d5f32a0f70edfa3b2189b79954",
    "timestamp": "2018-05-02T03:57:10.000",
    "transaction_mroot": "be6d4e2ee239352a2797e6185bd0419203483cf84dc744137db1e4d00397b832",
    "action_mroot": "6ea9af9d26a074e882309796641c43c4d7b2faad062088499621494ae3a7c065",
    "block_mroot": "65fbec2d94a398df5944b70b610b4824c39dbc977c85b3efedcb181f374354b8",
    "producer": "eosio",
    "schedule_version": 0,
    "new_producers": null,
    "producer_signature": "EOSK8ZkcdbnQo2b6H7wF4PqKFkMPD3rbMrBoa5aXhMX5RzTyLwz1QFvjcLYWGBRX9PQYXrvfNMvFhhbx7Z9yj6Bs43nvLN5zq",
    "regions": [
        {
            "region": 0,
            "cycles_summary": [
                [
                    {
                        "read_locks": [],
                        "write_locks": [],
                        "transactions": [
                            {
                                "status": "executed",
                                "kcpu_usage": 2,
                                "net_usage_words": 38,
                                "id": "11e1090bd02f6d253595b77d63cb550b40a4e0fd3a162ac55ef71197a1021bf8"
                            }
                        ]
                    }
                ]
            ]
        }
    ],
    "input_transactions": [],
    "id": "0000d28a758ee278d9aed4abec16bd1051e32385c6459ac2513854e36cf1007b",
    "block_num": 53898,
    "ref_block_prefix": 2882842329
}

**Comment by kesar** [comment]
I would recommend you to ask in https://eosio.stackexchange.com/ as this issues are more related to the code itself 👍

**Comment by jordigoyanes** [comment]
It's inside the "input_transactions" array, if it's emtpy then the block doesn't contain any transaction.

**Comment by wangzehui123456** [comment]
I'm running in dawn3.0 testnet. I'm confused with it.   If the block doesn't contain any transaction, where is the block the transaction contained? What's the mean of the ref_block_num in transaction?

**Comment by jordigoyanes** [comment]
I wonder too how do you know which block a transaction has been included in?

**Comment by taokayan** [comment]
0000d28a758ee278d9aed4abec16bd1051e32385c6459ac2513854e36cf1007b is the ref_block id

**Comment by andriantolie** [comment]
If you use history_api_plugin, you can use `cleos get transaction` and you will see the block num of where the transaction is included
