### ISSUE TITLE
keosd does not respect the --wallet-dir option

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#3229]
keosd does not respect the --wallet-dir option. Wallet files are always created in ~/eosio-wallet

test case:

```
docker run --rm --name keosd -v keosd-data-volume:/opt/eosio/bin/data-dir eosio/eos:dawn-v4.1.0 /opt/eosio/bin/keosd --wallet-dir=/opt/eosio/bin/data-dir

docker exec keosd cleos wallet create
"/opt/eosio/bin/keosd" launched
Creating wallet: default
Save password to use in the future to unlock this wallet.
Without password imported keys will not be retrievable.
"Password'
```

```
docker exec keosd ls -l /opt/eosio/bin/data-dir
[empty]
```

```
docker exec keosd ls -l /root/eosio-wallet
total 8
-rw-r--r-- 1 root root 1533 May 20 18:08 config.ini
-rw------- 1 root root  311 May 20 18:08 default.wallet
```

**Comment by kaidiren** [comment]
`docker run --rm --name keosd -v keosd-data-volume:/opt/eosio/bin/data-dir eosio/eos:dawn-v4.1.0 /opt/eosio/bin/keosd --wallet-dir=/opt/eosio/bin/data-dir --http-server-addres=127.0.0.1:8900`
  you should run command with `--http-server-addres=127.0.0.1:8900` as default


if you don't do this, when you run command `docker exec keosd cleos wallet create`

it will show you `"/opt/eosio/bin/keosd" launched`, here is a new instance of keosd with default data-dir

**Comment by noprom** [comment]
Hi, @masonbrothers , @kaidiren was right. You can use this docker-compose file to do this.
This PR [#3234](https://github.com/EOSIO/eos/pull/3234) will solve your problem.
