### ISSUE TITLE
Cannot run a contract eosc push message unless I comment out the following code

### ISSUE THREAD

**Issue by MatthewPappas** [EOSIO/eos#323]
#if 0
   // process_message recurses for each notified account, but we only want to run this check at the top level
   if (parent_context == nullptr && (_skip_flags & skip_authority_check) == false)
      EOS_ASSERT(apply_ctx.all_authorizations_used(), tx_irrelevant_auth,
                 "Message declared authorities it did not need: ${unused}",
                 ("unused", apply_ctx.unused_authorizations())("message", message));
#endif

**Comment by MatthewPappas** [comment]
Made a code change to make this work when --skip-transaction-signatures is set.
Making pull request for   make-contract-work-with-skipsig-323

**Comment by pavybez** [comment]
I think it is a bug in eosc/main.cpp instead of commenting that section.
