### ISSUE TITLE
CMake Error at libraries/wasm-jit/Source/Runtime/CMakeLists.txt:26 (find_package):

### ISSUE THREAD

**Issue by Kyeongrok** [EOSIO/eos#3230]
hello. I meet a error like below during run sh ./eosio_build.sh.

https://github.com/EOSIO/eos/issues/99 i found some issues at eos repository at git.

but i read some issues and replays but i cannot solve yet.

i use macOS High Sierra 10.13.4

i think why this problem has occured because llvm4.0 didn’t install.

i’m trying

brew install llvm-hs/llvm/llvm-4.0

but the build time too long i waited 10 minutes but not finished.

how can i solve this problem?

--------------------------------------------
CMake Error at libraries/wasm-jit/Source/Runtime/CMakeLists.txt:26 (find_package):
 Could not find a package configuration file provided by “LLVM” (requested
 version 4.0) with any of the following names:

LLVMConfig.cmake
 llvm-config.cmake

Add the installation prefix of “LLVM” to CMAKE_PREFIX_PATH or set
 “LLVM_DIR” to a directory containing one of the above files. If “LLVM”
 provides a separate development package or SDK, be sure it has been
 installed.

— Configuring incomplete, errors occurred!
See also “/Users/mattheu/git/eos/build/CMakeFiles/CMakeOutput.log”.

\> \> \> CMAKE building EOSIO has exited with the above error.

**Comment by marlonwilliams** [comment]
echo "export LLVM_DIR=/usr/local/Cellar/llvm/4.0.1/lib/cmake/llvm" >> ~/.zshrc
source ~/.zshrc

make sure path to llvm install is correct

**Comment by puravida365** [comment]
@marlonwilliams Thank you. The only thing that I had to do was make sure that the export path corresponded to mine. In my case it was:

export "LLVM_DIR=/usr/local/Cellar/llvm-4.0/4.0.1/lib/llvm-4.0/lib/cmake/llvm" >> ~/.zshrc
