### ISSUE TITLE
dawn-v4.1.0  After setting up the contract "eosio.bios" , cleos get account eosio get bug

### ISSUE THREAD

**Issue by bulangnisi** [EOSIO/eos#3235]
bogon:eos benj$ cleos set contracts eosio build/contracts/eosio.bios/ -p eosio

Reading WAST/WASM from build/contracts/eosio.bios/eosio.bios.wasm...

Using already assembled WASM...

Publishing contract...

executed transaction: 

86d802357ee73e69ba6b5147c88409db5d2459bd051d3eba0ee2692d70ccfe6c  3680 bytes  922 us
       eosio <= eosio::setcode               
"0000000000ea30550000c62e0061736d01000000015c1160037f7e7f0060057f7e7e7e7e0060047f7e7e7e0060027f7f006...
        eosio <= eosio::setabi                "0000000000ea3055050c6163636f756e745f6e616d65046e616d650f7065726d697373696f6e5f6e616d65046e616d650b6...

warning: transaction executed locally, but may not be confirmed by the network yet

bogon:eos benj$ cleos get account eosio

1750187ms thread-0   main.cpp:2316                 main                 ] Failed with error: Out of Range (8)
read datastream of length 5 over by -3
Error unpacking field version
error unpacking eosio::chain::abi_def

**Comment by zformular** [comment]
me too，i tried v4.1.0, DAWN-2018-05-22, master banch, all the same

**Comment by k26dr** [comment]
Solved this. You have to deploy the eosio.token contract and setup the eos account with a balance before deploying the eosio.system contract. Code can be found here:

https://github.com/EOSIO/eos/issues/3134

**Comment by bulangnisi** [comment]
@k26dr   thank
