### ISSUE TITLE
which database will EOSIO use?

### ISSUE THREAD

**Issue by red-butterfly** [EOSIO/eos#3236]
By June 1, There only have 10 days ， but the eosio didn't ensure that will use which database ?
The mongodb isn't update after issue the DAWN 4.0，and the push the sql_db_plugin. Use shared memory files? or use sqlite3?

**Comment by jgiszczak** [comment]
EOS.IO will launch with the shared memory database.  It is and always has been the sole database of record.  The mongodb and sql_db plugins are both available as export options to make the data available to dApps using traditional queries.  Those plugins are not and will not be used as the primary data store at launch.
