### ISSUE TITLE
After I downloaded the EOS code today,I can't even run the Hello World contract

### ISSUE THREAD

**Issue by Phoenix117** [EOSIO/eos#3237]
`root@bc154:/opt/eos/build# ./programs/cleos/cleos push action eosio hi ["eosio"] -p eosio
Error 3050002: Invalid Action Arguments
Ensure that your arguments follow the contract abi!
You can check the contract's abi by using 'cleos get code' command.

Error Details:
'["eosio"]' is invalid args for action 'hi' code 'eosio'. expected '[{"name":"user","type":"account_name"}]'
itr != structs.end(): Unknown struct account_name`

**Comment by enriquejr99** [comment]
`./programs/cleos/cleos push action eosio hi '[{"name":"eosio","type":"account_name"}]' -p eosio`

Let me know if it worked.

**Comment by Phoenix117** [comment]
@enriquejr99 It didn't work. The same error details.

**Comment by red-butterfly** [comment]
Yes, I have the same error.
After the Dawn 4.0, the action con't analyse the account_name;
In Dawn 4.0 ,the error is "Couldn't parse uint64_t", as i know

**Comment by andriyha** [comment]
You should change account_name to name.

**Comment by giniz** [comment]
recently there is a change in abi which needs to include below if containing account_name type:
"version": "eosio::abi/1.0",
   "types": [{
      "new_type_name": "account_name",
      "type": "name"
   }],

**Comment by Phoenix117** [comment]
@red-butterfly I don't have the same error when I use the Dawn 4.0.
Later I will try "name" type instead of "account_name" type. I will tell you the result.

**Comment by red-butterfly** [comment]
@andriyha @giniz  I know this method, but if you change the type to name ; When you use get table, you will find it doesn't work, or error

**Comment by Phoenix117** [comment]
@red-butterfly Dawn-v4.2.0 doesn't have these problem.I have tried.

**Comment by taokayan** [comment]
Can you try if the latest version works?

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
