### ISSUE TITLE
sign_transaction return transaction_id

### ISSUE THREAD

**Issue by yupasik** [EOSIO/eos#3238]
Hello! Is it possible to add transaction_id (hash) raw to the object returned by sign_transaction method?
It will be very usefull for exchanges who using two step sending transactions (create-broadcast)

**Comment by yupasik** [comment]
Or maybe it's better to implement API method *get_transaction_id* that return transaction_id from _signed transaction object_

All crypto currencies have the possibility to get transaction hash before broadcasting it to the network. I'm confused that EOS doesn't have it.

**Comment by andriantolie** [comment]
PR merged
