### ISSUE TITLE
History plugin: reduce memory usage

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#3244]
* Default behavior: don't track any actions
* Only track actions which match explicit filter rules. There will be no way to tell it to track all actions since that's susceptible to filling shared_mem
* Filter on receiver:action:actor. actor may be blank, but not receiver or action.
* eosio.token: limit memo to 256 bytes

**Comment by tbfleming** [comment]
Fixed in #3253

**Comment by libing125** [comment]
what are you talking about? how can i get actions now? please, thank u
