### ISSUE TITLE
latest master build error

### ISSUE THREAD

**Issue by brightermatter** [EOSIO/eos#3246]
/root/eos/libraries/chain/controller.cpp:127:34: error: cannot call member function ‘void eosio::chain::controller_impl::on_irreversible(const block_state_ptr&)’ without object
                                  on_irreversible(b);

Build seems passing but, building the latest master throws errors

**Comment by brightermatter** [comment]
Nop. I reverted back to the latest stable build. (Dawn 4.1 at that time)

**Comment by coosar** [comment]
same as your description, Clang 4.0 + vs code failed to build.

**Comment by taokayan** [comment]
can you try with the latest master?
