### ISSUE TITLE
Test name distribution/selling corner cases

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#3250]
During a white board session today we identified some corner cases that we want to test:

- [ ] Test that outbidding works properly
- [ ] Test that a higher bid on a different name causes the 24 hour time to reset
- [ ] Test that name selling process starts only two weeks after network unlock occurs (150M tokens vote)
- [ ] Test that the eosio., .eosio and .b1 names are reserved at start of the system contract

**Comment by brianjohnson5972** [comment]
@gleehokie Does this task cover automated testing, manual testing, or both?
