### ISSUE TITLE
Should we introduce prefix to types leaking from eosiolib/types.h to global namespace?

### ISSUE THREAD

**Issue by zokir** [EOSIO/eos#3258]
Noticed that following types are leaking into global namespace from eosiolib/types.h:

```
typedef uint64_t account_name;
typedef uint64_t permission_name;
typedef uint64_t token_name;                                                                                                             
typedef uint64_t table_name;                                                                                                             
..
etc.
```

Given that these names are pretty generic, should we introduce prefix like: `_eosio_c_` or something?
It will be much harder to collide with names llike `_eosio_c_account_name` than what we have now.

I can do the work, just want to know your opinion.

**Comment by brianjohnson5972** [comment]
This issue is no longer relevant in this repo.
