### ISSUE TITLE
eosc cannot push a transaction 

### ISSUE THREAD

**Issue by pavybez** [EOSIO/eos#326]
Currently, when we attempt to push a transaction it fails as below:

./eosc push message currency transfer '{"from":"currency","to":"tester","amount":50}' -s currency -s tester -p currency@active

status_code == 200: Error
: 3030003 tx_irrelevant_auth: irrelevant authority included
Message declared authorities it did not need: [{"account":"currency","permission":"active"}]
    {"unused":[{"account":"currency","permission":"active"}],"message":{"code":"currency","type":"transfer","authorization":[{"account":"currency","permission":"active"},{"account":"currency","permission":"active"}],"data":"00000079b822651d00000000c84267a13200000000000000"}}
    thread-0  chain_controller.cpp:926 process_message

**Comment by bytemaster** [comment]
This may be because the currency contract did not get properly set.
