### ISSUE TITLE
Replay temporarily leaks memory due to appbase channels queuing notices

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3260]
If I comment out the signals emited from controller it doesn't leak, if I leave them uncommented then memory can balloon up to 1GB with out all that many transactions. This memory includes transaction traces and other data.

Challenges:
1. some plugins need the signals (history plugin, db plugin, etc) to index state
2. other plugins don't want the signals (network plugin) 

The good news is that as soon as replay is done all the memory is freed.

**Comment by wanderingbort** [comment]
A quick survey suggests that appbase channels do not queue if there are no subscribers and we cannot find subscriptions that would be active during replay.  So, this may be a bug or the bloat may be in a layer between the controller signals and the appbase channels.

**Comment by bytemaster** [comment]
Moved to 1.1 because producers have ample ram and it eventually cleans up.
