### ISSUE TITLE
cleos create account eosio not passed

### ISSUE THREAD

**Issue by BlueDreamStar** [EOSIO/eos#3263]
Here is the code:
./cleos create account eosio test EOS7a53yaS61PpexVMccerh6zrTCu7yWaJLBijYLcBG2MA6aqW2x9 EOS8D9ydSeWpBbiFaMUC9WGYJFdzw2ovBDGWdjAtwtH2dqSSCisFA

And here is the output
2101881ms thread-0   main.cpp:2493                 main                 ] Failed with error: Parse Error (4)
Unexpected char '60' in ""

Could you help me address this bug, thank you very much!

**Comment by GiggleAll** [comment]
Excuse me, how did you solve this problem? I encountered the same problem.

**Comment by avral** [comment]
same error

**Comment by BlueDreamStar** [comment]
Sorry about the delay. 
I updated the system (macOS) to the latest version and then the bug was disappeared.

**Comment by dlutcat** [comment]
Did you solve this problem? @GiggleAll @avral 
I use CentOS 7.

**Comment by GiggleAll** [comment]
maybe centos lib have some problem or older,so you can try ubuntu 😀

Pat <notifications@github.com>于2018年6月27日 周三上午10:59写道：
