### ISSUE TITLE
when I set contract into blockchain ,"Error 3030000: transaction validation exception" occurs

### ISSUE THREAD

**Issue by lingyiliu016** [EOSIO/eos#3267]
cleos set contract child.acnt ~/eos/contracts/ERC721 -p child.acnt
Reading WAST...
Assembling WASM...
Publishing contract...
Error 3030000: transaction validation exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
!"unresolvable": env.snprintf
when I compile ERC721.wast and ERC721.abi, no error occurs. When I set contracts ,why error occured? How to solve the issue?

**Comment by taokayan** [comment]
Please use "print" instead

**Comment by mintzhao** [comment]
I have same issue. But Error is 3070000, but I'm not using print or snprintf at all.
I dont know why, drive me crazy.
whole error:
```
Publishing contract...
Error 3070000: WASM Exception
Error Details:
env.snprintf unresolveable
pending console output:
```

**Comment by jgiszczak** [comment]
@mintzhao You should post your code to [Stack Exchange](https://eosio.stackexchange.com/) for assistance in debugging your contract.

**Comment by mintzhao** [comment]
@jgiszczak  already solved, blame to to_string() function, thanks
