### ISSUE TITLE
update eos token contract wiki article

### ISSUE THREAD

**Issue by Velua** [EOSIO/eos#3272]
The wiki article https://github.com/EOSIO/eos/wiki/Tutorial-eosio-token-Contract references the old can_freeze, can_recall, can_whitelist parameters removed in #3103 
`cleos push action eosio.token create '[ "eosio", "1000000000.0000 EOS", 0, 0, 0]' -p eosio.token`

I'd put in a pull request but can't sus out how to do it for wiki pages.

**Comment by andriantolie** [comment]
The above wiki is already deprecated and replaced with the updated one in developers.eos.io
