### ISSUE TITLE
Unexpected mini forks on producer handoff; high block p2p latency

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#3280]
Under load in a test net there is an unexpectedly high rate of mini forks on producer handoff. When looking at logs this is initially no surprise -- since a block sent from producing node A to producer B took over 500ms to arrive it's no surprise that there is a mini fork.

But the connection between A and B is better than that. The RTT is ~350ms meaning that a block from A to B should only take about 175ms to arrive. Even a large ping (~3 times the size of blocks on this network!) is handled in a timely manner.
```
PING 35.200.146.141 (35.200.146.141) 15000(15028) bytes of data.
15008 bytes from 35.200.146.141: icmp_seq=1 ttl=76 time=355 ms
```

It seems reasonable that when producer A mints a block it should simply just broadcast to all its peers and not worry about the notice/request dance. Indeed there appears to be code in bcast_block that attempts this
https://github.com/EOSIO/eos/blob/ddd5ec05babf9a18d26b10f23ac81ad0e2f20e2d/plugins/net_plugin/net_plugin.cpp#L1575
But a look at the code a little closer..
https://github.com/EOSIO/eos/blob/ddd5ec05babf9a18d26b10f23ac81ad0e2f20e2d/plugins/net_plugin/net_plugin.cpp#L1594-L1607
Before 'just sending' the block it makes sure the other connection knows of the previous block, otherwise it'll send a notice.

That sounds reasonable but `blk_state` seems to be nearly ignored throughout the rest of the code. Constructs like this one that mark that a peer knows about a block aren't ever even used anywhere
https://github.com/EOSIO/eos/blob/ddd5ec05babf9a18d26b10f23ac81ad0e2f20e2d/plugins/net_plugin/net_plugin.cpp#L407-L414
I believe this blk_state index isn't being updated appropriately and this causes producer A to always do notice/request with producer B which simply takes too long since 355ms*1.5 is over 500ms.

**Comment by brianjohnson5972** [comment]
Resolved by #3393
