### ISSUE TITLE
Install on Centos7 - Unable to unarchive file /tmp/boost_1_66_0.tar.bz2

### ISSUE THREAD

**Issue by barrage-ivan** [EOSIO/eos#3294]
When you run `./eosio_build.sh` on clean centos 7,  I get error: `Unable to unarchive file /tmp/boost_1_66_0.tar.bz2.`.

Easy fix: `sudo yum install bzip2` and run `./eosio_build.sh` again.

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
