### ISSUE TITLE
Refactor control of "start_block" in light of discovered Node roles

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#3295]
# Description

During the operation of test networks and the refactor of the existing producer plugin triggered by #3161 there were several classes of network nodes identified, each of which has specific contracts with the network and users.   Note, nodes may fill multiple roles.

 - **Producer Node** : This node is an active producer on the network, it needs to learn transactions and blocks from the network and it needs to produce blocks.
    - this node should probably not burden itself with "relaying" blocks or transactions
    - this node should probably not burden itself with accepting direct RPC transactions
 - **Validating Node**:  This node learns blocks from the network and validates them
    - this node may be running an indexer that depends on blockchain state and provides a service for a dApp etc
 - **Relay/Firewall Node**: This is a specialization of a Validating Node.  In addition to learning blocks from the network, it may also learn transactions from the network.  
    - for each "valid" block or transaction this node learns about it will relay them to connected peers
    - this node does not need to "persist" any state of the transactions it learns as its role is not to serve as a queryable node
    - this node may have "looser" validation than a full validating node if it is more concerned with propagation delay
- **User RPC Node**: This is a node that is directly receiving transactions from users and attempting to forward those transactions to the network.
    - this node _does_ need to "persist" any state of the transactions it learns IF it is expected to represent that state on RPC reads/queries
    - this node may want to send a transaction _multiple times_ on the p2p network to give it a better chance at surviving to a producer (managing its own back-off so that it isn't labeled abusive).

This would present a minimum topology on a network (where no nodes are filling multiple roles) of:
```
[User RPC Node] <-> [zero or more Relay/Firewall Node(s)]  <-> [ Producer Node ]
                                ^        ^-> [Producer Node]
                                \-> [Producer Node] etc
```

We should work out the operation of the plugin(s) to reflect these differentiated use cases

**Comment by spartucus** [comment]
Awesome!
A silly question: what's the wallet's role? Is it `User RPC Node` or directly connected to `User RPC Node`?

**Comment by brianjohnson5972** [comment]
@wanderingbort Is this issue still relevant?  If I don't hear back from you I will presume that it is not.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
