### ISSUE TITLE
executing bash script from /tmp

### ISSUE THREAD

**Issue by barrage-ivan** [EOSIO/eos#3298]
https://github.com/EOSIO/eos/blob/f93d5ae6abbba18f110dabe707a67d5bc2eac9f2/eosio_build.sh#L55

Some installation templates by hardening does not allow executable files in `/tmp` folder. Maybe to consider using other dir for this.

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com

**Comment by andriantolie** [comment]
The implementation has changed in the latest version and variadic to $SOURCE_DIR
