### ISSUE TITLE
cleos get currency balance broken??

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3307]
root@eos-test-01:/opt/JungleTestnet# ./cleos.sh get currency balance eosio votertester1
Error 3060003: Contract Table Query Exception
Most likely, the given table doesnt' exist in the blockchain.
Error Details:
Table accounts is not specified in the ABI

This could happen if balance is 0 and therefore no table record?

**Comment by bytemaster** [comment]
> Hi,thank you very much,but this problem may by solve,the command is ./cleos.sh get currency balance eosio.token votertester1.thank you very much

**Comment by yy1098029419** [comment]
@bytemaster I have also encountered such a problem, and there is still a problem with following your tutorial.
