### ISSUE TITLE
No bid for name raised when creating new account with normal name without dot

### ISSUE THREAD

**Issue by LanfordCai** [EOSIO/eos#3315]
EOS version: DAWN-2018-05-22

Command:
```
cleos system newaccount ansnailsnail bnsnailsnail EOS7t6sziSL7gdTPBEJNEgo8qjQyFaNbiZR3ffjjM5fjuRbCnnLko EOS7t6sziSL7gdTPBEJNEgo8qjQyFaNbiZR3ffjjM5fjuRbCnnLko --stake-net "1.0000 EOS" --stake-cpu "1.0000 EOS" --buy-ram-bytes 3
```

Error:
```
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: no active bid for name
```

According to the [code](https://github.com/EOSIO/eos/blob/dd0cb785b8d138b2775bb485febca0ec67dc668c/contracts/eosio.system/eosio.system.cpp#L147), this error should not be raised because the new account name doesn't contain any dot.

**Comment by robrigo** [comment]
We're seeing this error as well trying to register a 12 character name for the EOS BIOS stage8 network.

**Comment by k26dr** [comment]
Seeing same error on jungle testnet
