### ISSUE TITLE
Error on Testnet Single Host Multinode 

### ISSUE THREAD

**Issue by jeaimetu** [EOSIO/eos#3316]
Hi.
Today I tried to follow "https://github.com/EOSIO/eos/wiki/Testnet-Single-Host-Multinode".

On following this tutorial, I encountered this error.

"root@ubuntu-s-4vcpu-8gb-nyc1-01:~/eos# cleos push action eosio setprods "{ \"schedule\": [{\"producer_name\": \"producernde1\",\"block_signing_key\": \"EOS5z9wT7qhvWEjqrUssnAmACUNz8Cq9hdUdsDMFNfwaxy8yqFUa7\"}]}" -p eosio@active
Error 3120003: Locked wallet
Ensure that your wallet is unlocked before using it!
Error Details:
You don't have any unlocked wallet!

This is the step for making second node to active.

So I used "cleos wallet open". But still same message occured to me.

Also there is only one wallet named "default".

Please check how to resolve this error.

BR, Teddy.

**Comment by rbw3821** [comment]
Recently, changes were made to start keosd automatically.  It's very possible that you have multiple keosd's running and the one your cleos is talking to is not the right one.  Try this to find out how many keosd's are running and what port they're listening to.
```
pgrep keosd | xargs printf " -p %d" | xargs lsof -Pani
```

**Comment by jeaimetu** [comment]
thanks. I used "ps -ef" and kill keosd. Even this causes "default" wallet remaining as a zombie. So "create wallet" does not work till I manually delete "default" file.

After then, everything work fine. 

Thanks.
