### ISSUE TITLE
404 - not found: /v1/account_history/get_transactions

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#3317]
`1829295ms thread-0   http_plugin.cpp:154           handle_http_request  ] 404 - not found: /v1/account_history/get_transactions`

Is this interface discarded? What is the new interface？

**Comment by spartucus** [comment]
`account_history` changed to `history`, `get_transactions` has been removed.
see [here](https://github.com/EOSIO/eos/blob/master/programs/cleos/httpc.hpp#L37).
