### ISSUE TITLE
Build fail on ubuntu 16.0.4 LTS

### ISSUE THREAD

**Issue by godspeedgld** [EOSIO/eos#3319]
Get an error is following , when start test-node
[
throw in function chainbase::database::database(const bfs::path &, chainbase::database::open_flags, uint64_t)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: database dirty flag set (likely due to unclean shutdown) replay or resync required
]

start commend line: 
 ./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin

I try to add --replay-blockchain.  the error still occur!
ubuntu is an instance in VMware, My operation is window 10

**Comment by godspeedgld** [comment]
I resolved it 
add  --resync-blockchain

**Comment by deba10106** [comment]
It didn't work for me

**Comment by specialtrevor** [comment]
--replay-blockchain doesn't do anything
--resync-blockchain is unrecognised option

Still getting: main.cpp:123                  main                 ] database dirty flag set (likely due to unclean shutdown): replay required

Any ideas?

**Comment by flexgames** [comment]
I had this issue with no data dir present but @specialtrevor's comment about specifying a different data dir with that parameter worked. I just added a data dir and it worked.

**Comment by godspeedgld** [comment]
@deba10106
 the flags  --resync-blockchnain has been removed in new dawn version

new flags is
--replay-blockchain --hard-replay-blockchain --delete-all-blocks

**Comment by yangqj** [comment]
nodeos --version is 2840751565
rm -rf ~/.local
it worked for me.

**Comment by raymondfx** [comment]
I am getting this

```
1187219ms thread-0   main.cpp:113                  main                 ] 10 assert_exception: Assert Exception
db.revision() >= head->block_num: fork database is inconsistent with shared memory
    {"db":0,"head":1}
    thread-0  controller.cpp:243 init

    {}
    thread-0  chain_plugin.cpp:454 plugin_startup
```
