### ISSUE TITLE
Can the ram of account be released(refund)?

### ISSUE THREAD

**Issue by hupengbuaa** [EOSIO/eos#3321]
We need to create so many accounts for users,  that would cost so much EOS. So can I sell those ram later? What would happen to those accounts? Will they be destroyed, reallocated to others, or still belongs to me?

**Comment by jafri** [comment]
Contracts should provide a way to release RAM, which can then be sold for EOS.

**Comment by hupengbuaa** [comment]
@jafri thx for answering. I may need more knowledge about the ram model.
