### ISSUE TITLE
When use get_account, always get error.

### ISSUE THREAD

**Issue by foreso-GitHub** [EOSIO/eos#3325]
I couldn't get the expected result when trying to execute the following command.

curl http://myHost:myPort/v1/chain/get_account -X POST -d '{"name":"inita"}' 

I am using Postman to execute post requests.

Steps:
1. create wallet 
curl http://localhost:8888/v1/wallet/create -X POST -d '"user1"'
The result is "PW5KRcvoeT6Kb1GGqAgQyDwJH21tzLgKXj5999cmTbBj47T7uCtBd".

2. import key
curl http://localhost:8888/v1/wallet/import_key -X POST -d '["user1","5KRcvoeT6Kb1GGqAgQyDwJH21tzLgKXj5999cmTbBj47T7uCtBd"]'
The result is "{}"

3. get account
curl http://localhost:8888/v1/chain/get_account -X POST -d '{"account_name":"user1"}' 
The result is:

{
    "code": 500,
    "message": "Internal Service Error",
    "error": {
        "code": 0,
        "name": "exception",
        "what": "unspecified",
        "details": [
            {
                "message": "unknown key",
                "file": "http_plugin.cpp",
                "line_number": 169,
                "method": "handle_http_request"
            }
        ]
    }
}

Is there any error in above steps?

**Comment by Crazy-Steven** [comment]
Wallet is not an account.

**Comment by okayplanet** [comment]
@Crazy-Steven No idea what you mean by that?  I am having the same problem, and the data passed is the account name such as ` '{"account_name":"b1"}'`

**Comment by okayplanet** [comment]
I resolved this problem by pulling and building from master.  It turns out that 1.0.1, and possibly 1.0.2 has this bug.  It seems to have been resolved though.

**Comment by newbdez33** [comment]
Still not work...

**Comment by Crazy-Steven** [comment]
Wallet name != Account name

**Comment by taokayan** [comment]
"user1" is your wallet name, not the account name. Please try "cleos create account ..." or "cleos system newaccount ..."

**Comment by ahamedbathru** [comment]
stdClass Object
(
    [code] => 500
    [message] => Internal Service Error
    [error] => stdClass Object
        (
            [code] => 0
            [name] => exception
            [what] => unspecified
            [details] => Array
                (
                )

        )

)

**Comment by Thomazella** [comment]
valid account names are 12 characters long, have no special characters, and use only number 1-5 incluse.
