### ISSUE TITLE
HTTP API Documentation for keosd.

### ISSUE THREAD

**Issue by kartik-koinex** [EOSIO/eos#3326]
Where can I find the HTTP API documentation for keosd?

**Comment by noprom** [comment]
You can find the API here: https://eosio.github.io/eos/group__eosiorpc.html#walletrpc
So this issue can be closed now.

**Comment by kartik-koinex** [comment]
@noprom Ah! Thanks a lot. but there are some apis missing like "create account", "get actions", etc

**Comment by noprom** [comment]
Hi @kartik-koinex , just wait for the update of the docs.

**Comment by sensay-nelson** [comment]
@noprom The link you provided 404's now.  https://eosio.github.io/eos/group__eosiorpc.html#walletrpc . 
Anyone know of any docs available?

**Comment by andriantolie** [comment]
This is the updated one for keosd https://developers.eos.io/keosd/v1.3.0/reference :)
