### ISSUE TITLE
Wallet API restricted to localhost

### ISSUE THREAD

**Issue by toonsevrin** [EOSIO/eos#333]
This is not fun for a dockerized environment, can this check be made ignorable?
https://github.com/EOSIO/eos/blob/master/plugins/wallet_api_plugin/wallet_api_plugin.cpp#L103

**Comment by heifner** [comment]
@bytemaster Do you want to remove the localhost restriction on eos-walletd?

**Comment by heifner** [comment]
@bytemaster Indicated that this restriction can be removed and replaced with a warning.

**Comment by heifner** [comment]
So I'm thinking the warning should be:
```c++
              "*************************************\n"
              "*                                   *\n"
              "*  --   Wallet NOT on localhost  -- *\n"
              "*  - Password and/or Private Keys - *\n"
              "*  - are transferred unencrypted. - *\n"
              "*                                   *\n"
              "*************************************\n");
```

Will put this small change in as a PR tomorrow morning.
