### ISSUE TITLE
bios-boot-tutorial doesn't work on master

### ISSUE THREAD

**Issue by sergmetelin** [EOSIO/eos#3332]
bios-boot-tutorial.py script doesn't work anymore, automatic bios boot doesn't work on master:5c3c9fd91822784d3b132aadcd0ae008120e56f6

<img width="673" alt="screen shot 2018-05-23 at 7 22 27 pm" src="https://user-images.githubusercontent.com/2141500/40443578-ae276b6c-5ebe-11e8-8b24-fd4168a66044.png">

**Comment by tbfleming** [comment]
What does this report? ```python3 --version```

**Comment by sergmetelin** [comment]
Fixed by upgrading Python to 3.6.4
