### ISSUE TITLE
walletd for docker

### ISSUE THREAD

**Issue by toonsevrin** [EOSIO/eos#334]
docker-compose should automatically setup a walletd instance.

**Comment by toonsevrin** [comment]
working on this over at https://github.com/toonsevrin/eos/tree/patch-4

**Comment by toonsevrin** [comment]
@peterwillcn

**Comment by heifner** [comment]
Is this still desired? Can we close this issue?

**Comment by noprom** [comment]
should be closed now.

**Comment by heifner** [comment]
Wallet added to docker a long time ago.
