### ISSUE TITLE
New User Creation Serialization Issue Dawn4.1

### ISSUE THREAD

**Issue by cs4026** [EOSIO/eos#3341]
When I create a new user using cleos, I get an "Unknown Struct Failed To Serialize Type" Error, however, the user account was still created.

<img width="1261" alt="screen shot 2018-05-23 at 5 02 05 pm" src="https://user-images.githubusercontent.com/16903949/40451849-fdf36292-5ead-11e8-9dd4-7a8a37bc13cb.png">

System: MacBook Pro (Retina, 13-inch, Early 2015), High Sierra.

EOS-Version: Dawn 4.1 - Fresh install 

Config File(Changed to .txt for submission): 
[config.txt](https://github.com/EOSIO/eos/files/2032918/config.txt).

Terminal Log:
[Terminal.txt](https://github.com/EOSIO/eos/files/2032928/Terminal.txt)
`[100%] Built target unit_test

	 _______  _______  _______ _________ _______
	(  ____ \(  ___  )(  ____ \\__   __/(  ___  )
	| (    \/| (   ) || (    \/   ) (   | (   ) |
	| (__    | |   | || (_____    | |   | |   | |
	|  __)   | |   | |(_____  )   | |   | |   | |
	| (      | |   | |      ) |   | |   | |   | |
	| (____/\| (___) |/\____) |___) (___| (___) |
	(_______/(_______)\_______)\_______/(_______)

	EOSIO has been successfully built. 00:26:30

	To verify your installation run the following commands:

	/usr/local/bin/mongod -f /usr/local/etc/mongod.conf &
	cd /Users/carlos/eos/build; make test

	For more information:
	EOSIO website: https://eos.io
	EOSIO Telegram channel @ https://t.me/EOSProject
	EOSIO resources: https://eos.io/resources/
	EOSIO wiki: https://github.com/EOSIO/eos/wiki

Xanadu:eos carlos$ vim ~/Library/Application\ Support/eosio/
Xanadu:eos carlos$ cd ~/Library/Application\ Support/eosio/
Xanadu:eosio carlos$ ls
Xanadu:eosio carlos$ eosio
-bash: eosio: command not found
Xanadu:eosio carlos$ ls
Xanadu:eosio carlos$ cd
Xanadu:~ carlos$ ls
--detach		22:22			Downloads		Public			docker			gitlab			t
--hostname		443:443			Justinmind		VirtualBox VMs		eos			gitlab.example.com	t.c
--name			80:80			Library			a.out			eos2			go			test
--publish		Applications		Movies			always			eosio-wallet		ipfs			test.txt
--restart		Desktop			Music			dev			eosjs-ui		run			testing
--volume		Documents		Pictures		dev-carlos		eosjs_setups		sudo			—recursive
Xanadu:~ carlos$ cd eos
Xanadu:eos carlos$ ls
CMakeLists.txt		HEADER			circle.yml		eos.doxygen.in		mesh.dot		ring.png		testnet.md
CMakeModules		Jenkinsfile		contracts		eosio_build.sh		mesh.png		scripts			testnet.template
Docker			LICENSE.txt		debian			externals		plugins			star.dot		tests
Doxyfile		README.md		docs			governance		programs		star.png		tools
EXCHANGE_README.md	build			eos-logo.png		libraries		ring.dot		testnet-diagrams.sh	unittests
Xanadu:eos carlos$ nodoes
-bash: nodoes: command not found
Xanadu:eos carlos$ nodeos
3109567ms thread-0   chain_plugin.cpp:99           plugin_initialize    ] initializing chain plugin
3109568ms thread-0   http_plugin.cpp:141           plugin_initialize    ] host: 127.0.0.1 port: 8888 
3109568ms thread-0   http_plugin.cpp:144           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
3109569ms thread-0   net_plugin.cpp:2628           plugin_initialize    ] Initialize net plugin
3109569ms thread-0   net_plugin.cpp:2644           plugin_initialize    ] Setting net_plugin logging level to info
3109569ms thread-0   net_plugin.cpp:2669           plugin_initialize    ] host: 0.0.0.0 port: 9876 
3109570ms thread-0   net_plugin.cpp:2745           plugin_initialize    ] my node_id is 760f5b67e160a7abc7edbbefc764ef3c34cf6f26fde27c34d120cb9e814ebb6f
3109571ms thread-0   main.cpp:90                   main                 ] nodeos version e578e56f
3109572ms thread-0   main.cpp:91                   main                 ] eosio root is /Users/carlos/Library/Application Support
3109572ms thread-0   chain_plugin.cpp:178          plugin_startup       ] 
 generating default genesis file /Users/carlos/Library/Application Support/eosio/nodeos/config/genesis.json
3109651ms thread-0   chain_plugin.cpp:208          plugin_startup       ] starting chain in read/write mode
3109651ms thread-0   chain_plugin.cpp:213          plugin_startup       ] Blockchain started; head block is #0, genesis timestamp is 2018-03-01T12:00:00.000
3109651ms thread-0   http_plugin.cpp:213           plugin_startup       ] start listening for http requests
3109653ms thread-0   net_plugin.cpp:2757           plugin_startup       ] starting listener, max clients is 25
3109654ms thread-0   producer_plugin.cpp:161       plugin_startup       ] producer plugin:  plugin_startup() begin
3109654ms thread-0   producer_plugin.cpp:175       plugin_startup       ] No producers configured! Please add producer IDs and private keys to configuration.
3109654ms thread-0   producer_plugin.cpp:176       plugin_startup       ] producer plugin:  plugin_startup() end
3111067ms thread-0   net_plugin.cpp:2771           plugin_shutdown      ] shutdown..
3111067ms thread-0   net_plugin.cpp:2774           plugin_shutdown      ] close acceptor
3111068ms thread-0   net_plugin.cpp:2777           plugin_shutdown      ] close 0 connections
3111068ms thread-0   net_plugin.cpp:2785           plugin_shutdown      ] exit shutdown
Xanadu:eos carlos$ cd ~/Library/Application\ Support/eosio/
Xanadu:eosio carlos$ ls
nodeos
Xanadu:eosio carlos$ cd nodeos/
Xanadu:nodeos carlos$ ls
config	data
Xanadu:nodeos carlos$ cd config/
Xanadu:config carlos$ ls
config.ini	genesis.json
Xanadu:config carlos$ vim config.ini 
Xanadu:config carlos$ vim config.ini 
Xanadu:config carlos$ vim config.ini 
Xanadu:config carlos$ cleos create account eosio first EOS89udP6VJi8AUodZNXr5VvHyRFLJngpdUX5UpWmZUZSCeFp3Mhb EOS89udP6VJi8AUodZNXr5VvHyRFLJngpdUX5UpWmZUZSCeFp3Mhb
Error 3030002: signatures do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and you wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"eosio","permission":"active"}', but does not have signatures for it.
Xanadu:config carlos$ cleos create account
ERROR: RequiredError: creator
Create a new account on the blockchain
Usage: cleos create account [OPTIONS] creator name OwnerKey ActiveKey

Positionals:
  creator TEXT                The name of the account creating the new account
  name TEXT                   The name of the new account
  OwnerKey TEXT               The owner public key for the new account
  ActiveKey TEXT              The active public key for the new account

Options:
  -x,--expiration             set the time in seconds before a transaction expires, defaults to 30s
  -f,--force-unique           force the transaction to be unique. this will consume extra bandwidth and remove any protections against accidently issuing the same transaction multiple times
  -s,--skip-sign              Specify if unlocked wallet keys should be used to sign transaction
  -j,--json                   print result as json
  -d,--dont-broadcast         don't broadcast transaction to the network (just print to stdout)
  -r,--ref-block TEXT         set the reference block num or block id used for TAPOS (Transaction as Proof-of-Stake)
  -p,--permission TEXT ...    An account and permission level to authorize, as in 'account@permission' (defaults to 'creator@active')
  --max-cpu-usage UINT        set an upper limit on the cpu usage budget, in instructions-retired, for the execution of the transaction (defaults to 0 which means no limit)
  --max-net-usage UINT        set an upper limit on the net usage budget, in bytes, for the transaction (defaults to 0 which means no limit)

Xanadu:config carlos$ cleos wallet
ERROR: RequiredError: Subcommand required
Interact with local wallet
Usage: cleos wallet SUBCOMMAND

Subcommands:
  create                      Create a new wallet locally
  open                        Open an existing wallet
  lock                        Lock wallet
  lock_all                    Lock all unlocked wallets
  unlock                      Unlock wallet
  import                      Import private key into wallet
  list                        List opened wallets, * = unlocked
  keys                        List of private keys from all unlocked wallets in wif format.
Xanadu:config carlos$ cleos wallet create
Creating wallet: default
Save password to use in the future to unlock this wallet.
Without password imported keys will not be retrievable.
"PW5HwTT6jta3Jt67RH1131hxg4Z7UvUbW4zFupABnEgoXXBxtpDYu"
Xanadu:config carlos$ cleos wallet unlock 
password: Unlocked: default
Xanadu:config carlos$ vim config.ini 
Xanadu:config carlos$ cleos create account eosio first EOS89udP6VJi8AUodZNXr5VvHyRFLJngpdUX5UpWmZUZSCeFp3Mhb EOS89udP6VJi8AUodZNXr5VvHyRFLJngpdUX5UpWmZUZSCeFp3Mhb
3358754ms thread-0   main.cpp:1181                 main                 ] Failed with error: Assert Exception (10)
itr != structs.end(): Unknown struct 
Failed to serialize type

Xanadu:config carlos$ cleos create account
ERROR: RequiredError: creator
Create a new account on the blockchain
Usage: cleos create account [OPTIONS] creator name OwnerKey ActiveKey

Positionals:
  creator TEXT                The name of the account creating the new account
  name TEXT                   The name of the new account
  OwnerKey TEXT               The owner public key for the new account
  ActiveKey TEXT              The active public key for the new account

Options:
  -x,--expiration             set the time in seconds before a transaction expires, defaults to 30s
  -f,--force-unique           force the transaction to be unique. this will consume extra bandwidth and remove any protections against accidently issuing the same transaction multiple times
  -s,--skip-sign              Specify if unlocked wallet keys should be used to sign transaction
  -j,--json                   print result as json
  -d,--dont-broadcast         don't broadcast transaction to the network (just print to stdout)
  -r,--ref-block TEXT         set the reference block num or block id used for TAPOS (Transaction as Proof-of-Stake)
  -p,--permission TEXT ...    An account and permission level to authorize, as in 'account@permission' (defaults to 'creator@active')
  --max-cpu-usage UINT        set an upper limit on the cpu usage budget, in instructions-retired, for the execution of the transaction (defaults to 0 which means no limit)
  --max-net-usage UINT        set an upper limit on the net usage budget, in bytes, for the transaction (defaults to 0 which means no limit)

Xanadu:config carlos$ cleos create account eosio first EOS89udP6VJi8AUodZNXr5VvHyRFLJngpdUX5UpWmZUZSCeFp3Mhb EOS89udP6VJi8AUodZNXr5VvHyRFLJngpdUX5UpWmZUZSCeFp3Mhb
Error 3040000: message validation exception
Error Details:
Cannot create account named first, as that name is already taken
Xanadu:config carlos$ cleos get accountfirst
ERROR: RequiredError: Subcommand required
Retrieve various items and information from the blockchain
Usage: cleos get SUBCOMMAND

Subcommands:
  info                        Get current blockchain information
  block                       Retrieve a full block from the blockchain
  account                     Retrieve an account from the blockchain
  code                        Retrieve the code and ABI for an account
  table                       Retrieve the contents of a database table
  currency                    Retrieve information related to standard currencies
  accounts                    Retrieve accounts associated with a public key
  servants                    Retrieve accounts which are servants of a given account 
  transaction                 Retrieve a transaction from the blockchain
  transactions                Retrieve all transactions with specific account name referenced in their scope
Xanadu:config carlos$ cleos get account first
{
  "account_name": "first",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS89udP6VJi8AUodZNXr5VvHyRFLJngpdUX5UpWmZUZSCeFp3Mhb",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS89udP6VJi8AUodZNXr5VvHyRFLJngpdUX5UpWmZUZSCeFp3Mhb",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}
`

**Comment by taokayan** [comment]
Can you try using the latest version?

**Comment by cs4026** [comment]
I'll close the issue since the error is no longer valid on 1.0.2.
