### ISSUE TITLE
Grace period for inactivating a recently voted in producer is too strict

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#3344]
`system_contract::update_elected_producers` only gives a 252 second grace period since the time a new producer was added into a new proposed producer schedule before considering them for inactivation due to no recent blocks produced.

This number was likely chosen prior to the latest DPOS changes that (on average) doubled the time between proposing a new producer schedule and making that schedule active. With those changes, and with a fully active set of 21 producers, a newly elected producer may be right on the edge of the grace period. This can frequently cause some newly elected producer to be disabled (zeroing out their block signing key) in a healthy network prior to them even producing their first block.

The easy fix is to just double this grace period to 504 seconds to match the doubling of the average time between proposed schedule to active schedule with the DPOS changes. However, this bug demonstrates that our current method of disabling inactive block producers is fragile. A better way of implementing it is likely possible and we should at least explore that for an updated version of the system contract after 1.0. But for the 1.0 milestone, it is likely sufficient to just double the grace period.

**Comment by bytemaster** [comment]
On steem & bitshares this grace period was closer to 1 day.   I think it is fair to allow 1 hour.
