### ISSUE TITLE
Error buliding Eos

### ISSUE THREAD

**Issue by hadramidah** [EOSIO/eos#3345]
Last login: Wed May 23 20:10:54 on ttys000
ELs-MacBook-Pro:~ elhadramidah$ cd eos
ELs-MacBook-Pro:eos elhadramidah$ ./eosio_build.sh

	Beginning build version: 1.2
	Wed May 23 20:51:48 UTC 2018
	User: elhadramidah
	git head id: 503e0c8e97e02d586f30fb36467e32673ce9ad9b
	Current branch: master

	ARCHITECTURE: Darwin

	OS name: Darwin
	OS Version: 10.13.4
	CPU speed: 220.00Ghz
	CPU cores: 4
	Physical Memory: 16 Gbytes
	Disk install: /dev/disk1s1
	Disk space total: 233G
	Disk space available: 71G

	Checking xcode-select installation
	xcode-select installation found @ 
	/usr/bin/xcode-select 

	Checking Ruby installation.
	Ruby installation found @ 
	/usr/bin/ruby 

	Checking Home Brew installation
	Homebrew must be installed to compile EOS.IO

	Do you wish to install Home Brew?
1) Yes
2) No
#? 1
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following existing directories will be made group writable:
/usr/local/bin
==> The following existing directories will have their owner set to elhadramidah:
/usr/local/bin
==> The following existing directories will have their group set to admin:
/usr/local/bin
==> The following new directories will be created:
/usr/local/Cellar
/usr/local/Homebrew
/usr/local/Frameworks
/usr/local/etc
/usr/local/include
/usr/local/lib
/usr/local/opt
/usr/local/sbin
/usr/local/share
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
/usr/local/var

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/bin
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin
==> /usr/bin/sudo /usr/sbin/chown elhadramidah /usr/local/bin
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /usr/sbin/chown elhadramidah /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var
==> /usr/bin/sudo /bin/mkdir -p /Users/elhadramidah/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/elhadramidah/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown elhadramidah /Users/elhadramidah/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/mkdir -p /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown elhadramidah /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Counting objects: 101229, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 101229 (delta 15), reused 12 (delta 5), pack-reused 101188
Receiving objects: 100% (101229/101229), 23.12 MiB | 186.00 KiB/s, done.
Resolving deltas: 100% (73666/73666), done.
From https://github.com/Homebrew/brew
 * [new branch]          master     -> origin/master
 * [new tag]             0.1        -> 0.1
 * [new tag]             0.2        -> 0.2
 * [new tag]             0.3        -> 0.3
 * [new tag]             0.4        -> 0.4
 * [new tag]             0.5        -> 0.5
 * [new tag]             0.6        -> 0.6
 * [new tag]             0.7        -> 0.7
 * [new tag]             0.7.1      -> 0.7.1
 * [new tag]             0.8        -> 0.8
 * [new tag]             0.8.1      -> 0.8.1
 * [new tag]             0.9        -> 0.9
 * [new tag]             0.9.1      -> 0.9.1
 * [new tag]             0.9.2      -> 0.9.2
 * [new tag]             0.9.3      -> 0.9.3
 * [new tag]             0.9.4      -> 0.9.4
 * [new tag]             0.9.5      -> 0.9.5
 * [new tag]             0.9.8      -> 0.9.8
 * [new tag]             0.9.9      -> 0.9.9
 * [new tag]             1.0.0      -> 1.0.0
 * [new tag]             1.0.1      -> 1.0.1
 * [new tag]             1.0.2      -> 1.0.2
 * [new tag]             1.0.3      -> 1.0.3
 * [new tag]             1.0.4      -> 1.0.4
 * [new tag]             1.0.5      -> 1.0.5
 * [new tag]             1.0.6      -> 1.0.6
 * [new tag]             1.0.7      -> 1.0.7
 * [new tag]             1.0.8      -> 1.0.8
 * [new tag]             1.0.9      -> 1.0.9
 * [new tag]             1.1.0      -> 1.1.0
 * [new tag]             1.1.1      -> 1.1.1
 * [new tag]             1.1.10     -> 1.1.10
 * [new tag]             1.1.11     -> 1.1.11
 * [new tag]             1.1.12     -> 1.1.12
 * [new tag]             1.1.13     -> 1.1.13
 * [new tag]             1.1.2      -> 1.1.2
 * [new tag]             1.1.3      -> 1.1.3
 * [new tag]             1.1.4      -> 1.1.4
 * [new tag]             1.1.5      -> 1.1.5
 * [new tag]             1.1.6      -> 1.1.6
 * [new tag]             1.1.7      -> 1.1.7
 * [new tag]             1.1.8      -> 1.1.8
 * [new tag]             1.1.9      -> 1.1.9
 * [new tag]             1.2.0      -> 1.2.0
 * [new tag]             1.2.1      -> 1.2.1
 * [new tag]             1.2.2      -> 1.2.2
 * [new tag]             1.2.3      -> 1.2.3
 * [new tag]             1.2.4      -> 1.2.4
 * [new tag]             1.2.5      -> 1.2.5
 * [new tag]             1.2.6      -> 1.2.6
 * [new tag]             1.3.0      -> 1.3.0
 * [new tag]             1.3.1      -> 1.3.1
 * [new tag]             1.3.2      -> 1.3.2
 * [new tag]             1.3.3      -> 1.3.3
 * [new tag]             1.3.4      -> 1.3.4
 * [new tag]             1.3.5      -> 1.3.5
 * [new tag]             1.3.6      -> 1.3.6
 * [new tag]             1.3.7      -> 1.3.7
 * [new tag]             1.3.8      -> 1.3.8
 * [new tag]             1.3.9      -> 1.3.9
 * [new tag]             1.4.0      -> 1.4.0
 * [new tag]             1.4.1      -> 1.4.1
 * [new tag]             1.4.2      -> 1.4.2
 * [new tag]             1.4.3      -> 1.4.3
 * [new tag]             1.5.0      -> 1.5.0
 * [new tag]             1.5.1      -> 1.5.1
 * [new tag]             1.5.10     -> 1.5.10
 * [new tag]             1.5.11     -> 1.5.11
 * [new tag]             1.5.12     -> 1.5.12
 * [new tag]             1.5.13     -> 1.5.13
 * [new tag]             1.5.14     -> 1.5.14
 * [new tag]             1.5.2      -> 1.5.2
 * [new tag]             1.5.3      -> 1.5.3
 * [new tag]             1.5.4      -> 1.5.4
 * [new tag]             1.5.5      -> 1.5.5
 * [new tag]             1.5.6      -> 1.5.6
 * [new tag]             1.5.7      -> 1.5.7
 * [new tag]             1.5.8      -> 1.5.8
 * [new tag]             1.5.9      -> 1.5.9
 * [new tag]             1.6.0      -> 1.6.0
 * [new tag]             1.6.1      -> 1.6.1
 * [new tag]             1.6.2      -> 1.6.2
 * [new tag]             1.6.3      -> 1.6.3
 * [new tag]             1.6.4      -> 1.6.4
HEAD is now at 24025a3ab Merge pull request #4202 from MikeMcQuaid/remove-some-integration-tests
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4763, done.
remote: Compressing objects: 100% (4540/4540), done.
remote: Total 4763 (delta 52), reused 1184 (delta 35), pack-reused 0
Receiving objects: 100% (4763/4763), 3.86 MiB | 162.00 KiB/s, done.
Resolving deltas: 100% (52/52), done.
Tapped 4551 formulae (4,804 files, 12MB)
==> Cleaning up /Library/Caches/Homebrew...
==> Migrating /Library/Caches/Homebrew to /Users/elhadramidah/Library/Caches/Hom
==> Deleting /Library/Caches/Homebrew...
Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics.html

==> Next steps:
- Run `brew help` to get started
- Further documentation: 
    https://docs.brew.sh
	Home Brew installation found @
	/usr/local/bin/brew

	Checking dependencies.
	Checking automake ... 		 automake NOT found.
	Checking Libtool ... 		 Libtool NOT found.
	Checking OpenSSL ... 		 OpenSSL NOT found.
	Checking llvm ... 		 llvm NOT found.
	Checking wget ... 		 wget NOT found.
	Checking CMake ... 		 CMake NOT found.
	Checking GMP ... 		 GMP NOT found.
	Checking gettext ... 		 gettext NOT found.
	Checking MongoDB ... 		 MongoDB NOT found.
	Checking Doxygen ... 		 Doxygen NOT found.
	Checking Graphviz ... 		 Graphviz NOT found.
	Checking LCOV ... 		 LCOV NOT found.
	Checking Python3 ... 		 python3 NOT found.

	The following dependencies are required to install EOSIO.

	1. automake\n\t2. Libtool\n\t3. OpenSSL\n\t4. llvm\n\t5. wget\n\t6. CMake\n\t7. GMP\n\t8. gettext\n\t9. MongoDB\n\t10. Doxygen\n\t11. Graphviz\n\t12. LCOV\n\t13. Python 3\n\t

Do you wish to install these packages?
1) Yes
2) No
#? 1
Password:
	Updating Home Brew.
Already up-to-date.
	Installing Dependencies.
==> Installing dependencies for automake: autoconf
==> Installing automake dependency: autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.high_sierra.b
==> Downloading from https://akamai.bintray.com/63/63957a3952b7af5496012b3819c99
######################################################################## 100.0%
==> Pouring autoconf-2.69.high_sierra.bottle.4.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/autoconf
==> Summary
🍺  /usr/local/Cellar/autoconf/2.69: 71 files, 3.0MB
==> Installing automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.16.1.high_sierra
==> Downloading from https://akamai.bintray.com/f9/f9d2f7f913917ce686bf8dab00fe5
######################################################################## 100.0%
==> Pouring automake-1.16.1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/automake/1.16.1: 131 files, 3MB
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6_1.high_sierra
==> Downloading from https://akamai.bintray.com/eb/ebb50367eb2336ee317841587e246
######################################################################## 100.0%
==> Pouring libtool-2.4.6_1.high_sierra.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6_1: 71 files, 3.7MB
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2o_1.high_sierr
==> Downloading from https://akamai.bintray.com/67/67a795f419adcc7f2cc9c204538f2
######################################################################## 100.0%
==> Pouring openssl-1.0.2o_1.high_sierra.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2o_1: 1,791 files, 12.3MB
==> Installing dependencies for llvm@4: libffi
==> Installing llvm@4 dependency: libffi
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.2.1.high_sierra.bo
######################################################################## 100.0%
==> Pouring libffi-3.2.1.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of libffi.

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/libffi/lib

==> Summary
🍺  /usr/local/Cellar/libffi/3.2.1: 16 files, 297.0KB
==> Installing llvm@4
==> Downloading https://homebrew.bintray.com/bottles/llvm@4-4.0.1.high_sierra.bo
==> Downloading from https://akamai.bintray.com/d0/d0bfdb67e52a97994cef179c3b865
######################################################################## 100.0%
==> Pouring llvm@4-4.0.1.high_sierra.bottle.tar.gz
==> Caveats
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm@4/lib -Wl,-rpath,/usr/local/opt/llvm@4/lib"

This formula is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/llvm@4/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/llvm@4/lib
    CPPFLAGS: -I/usr/local/opt/llvm@4/include

==> Summary
🍺  /usr/local/Cellar/llvm@4/4.0.1: 2,270 files, 1GB
==> Installing dependencies for wget: gettext, libunistring, libidn2
==> Installing wget dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.8.1.high_sierr
==> Downloading from https://akamai.bintray.com/99/99d2dbd4c9ebfe9bf2a64bd99f3a6
######################################################################## 100.0%
==> Pouring gettext-0.19.8.1.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD gettext library & some software gets confused if both are in the library path.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/gettext/lib
    CPPFLAGS: -I/usr/local/opt/gettext/include

==> Summary
🍺  /usr/local/Cellar/gettext/0.19.8.1: 1,935 files, 16.9MB
==> Installing wget dependency: libunistring
==> Downloading https://homebrew.bintray.com/bottles/libunistring-0.9.9.high_sie
==> Downloading from https://akamai.bintray.com/6c/6c072527173fa59aa703e5d4ccd4f
######################################################################## 100.0%
==> Pouring libunistring-0.9.9.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libunistring/0.9.9: 54 files, 4.4MB
==> Installing wget dependency: libidn2
==> Downloading https://homebrew.bintray.com/bottles/libidn2-2.0.5.high_sierra.b
==> Downloading from https://akamai.bintray.com/5a/5a772d41138cf7d83e338011ae9e6
######################################################################## 100.0%
==> Pouring libidn2-2.0.5.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libidn2/2.0.5: 68 files, 668.6KB
==> Installing wget
==> Downloading https://homebrew.bintray.com/bottles/wget-1.19.5.high_sierra.bot
==> Downloading from https://akamai.bintray.com/af/af8880a424be0cde4d2891b0027ae
######################################################################## 100.0%
==> Pouring wget-1.19.5.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/wget/1.19.5: 50 files, 3.7MB
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.11.2.high_sierra.bo
==> Downloading from https://akamai.bintray.com/8a/8a9b3ee8dc353de7231f972db6d02
######################################################################## 100.0%
==> Pouring cmake-3.11.2.high_sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.11.2: 2,363 files, 32.7MB
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.1.2_2.high_sierra.bot
==> Downloading from https://akamai.bintray.com/83/8372dcd88e36997d7aacaffb55570
######################################################################## 100.0%
==> Pouring gmp-6.1.2_2.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gmp/6.1.2_2: 18 files, 3.1MB
==> Installing dependencies for mongodb: gdbm, readline, sqlite, python@2
==> Installing mongodb dependency: gdbm
==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.14.1_1.high_sierra.b
######################################################################## 100.0%
==> Pouring gdbm-1.14.1_1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gdbm/1.14.1_1: 20 files, 555.7KB
==> Installing mongodb dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-7.0.3_1.high_sierr
==> Downloading from https://akamai.bintray.com/45/45322d69fba127fe9d5c8d1d2fe8b
######################################################################## 100.0%
==> Pouring readline-7.0.3_1.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only..

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/7.0.3_1: 46 files, 1.5MB
==> Installing mongodb dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.23.1.high_sierra.b
==> Downloading from https://akamai.bintray.com/0b/0b5f0e6d1096fbed10367e53c13c0
######################################################################## 100.0%
==> Pouring sqlite-3.23.1.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include

==> Summary
🍺  /usr/local/Cellar/sqlite/3.23.1: 11 files, 3MB
==> Installing mongodb dependency: python@2
==> Downloading https://homebrew.bintray.com/bottles/python@2-2.7.15.high_sierra
==> Downloading from https://akamai.bintray.com/f5/f557a6bed6223c3df7d5aef2941b0
######################################################################## 100.0%
==> Pouring python@2-2.7.15.high_sierra.bottle.tar.gz
==> /usr/local/Cellar/python@2/2.7.15/bin/python -s setup.py --no-user-cfg insta
==> /usr/local/Cellar/python@2/2.7.15/bin/python -s setup.py --no-user-cfg insta
==> /usr/local/Cellar/python@2/2.7.15/bin/python -s setup.py --no-user-cfg insta
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python@2/2.7.15: 4,669 files, 82.7MB
==> Installing mongodb
==> Downloading https://homebrew.bintray.com/bottles/mongodb-3.6.5.high_sierra.b
==> Downloading from https://akamai.bintray.com/1d/1da3328941f24fbc9a6c4b37862d0
######################################################################## 100.0%
==> Pouring mongodb-3.6.5.high_sierra.bottle.tar.gz
==> Caveats
To have launchd start mongodb now and restart at login:
  brew services start mongodb
Or, if you don't want/need a background service you can just run:
  mongod --config /usr/local/etc/mongod.conf
==> Summary
🍺  /usr/local/Cellar/mongodb/3.6.5: 19 files, 297.9MB
==> Downloading https://homebrew.bintray.com/bottles/doxygen-1.8.14.high_sierra.
==> Downloading from https://akamai.bintray.com/a2/a241e29223f4004e69c81be8e0147
######################################################################## 100.0%
==> Pouring doxygen-1.8.14.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/doxygen/1.8.14: 9 files, 12.8MB
==> Installing dependencies for graphviz: libpng, freetype, fontconfig, jpeg, libtiff, webp, gd
==> Installing graphviz dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.34.high_sierra.b
==> Downloading from https://akamai.bintray.com/d3/d38a64089526ecc1413acbc223738
######################################################################## 100.0%
==> Pouring libpng-1.6.34.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.34: 26 files, 1.2MB
==> Installing graphviz dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.9.1.high_sierra.
==> Downloading from https://akamai.bintray.com/44/444ef60a543aca6ca26223f46182c
######################################################################## 100.0%
==> Pouring freetype-2.9.1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.9.1: 60 files, 2.6MB
==> Installing graphviz dependency: fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.13.0.high_sier
==> Downloading from https://akamai.bintray.com/66/66ad096a51d6253be02b4d3df0299
######################################################################## 100.0%
==> Pouring fontconfig-2.13.0.high_sierra.bottle.tar.gz
==> Regenerating font cache, this may take a while
==> /usr/local/Cellar/fontconfig/2.13.0/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.13.0: 511 files, 3.2MB
==> Installing graphviz dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-9c.high_sierra.bottle.
==> Downloading from https://akamai.bintray.com/17/178200fd8aa50d5db22c5faa4ca40
######################################################################## 100.0%
==> Pouring jpeg-9c.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/jpeg/9c: 21 files, 724.5KB
==> Installing graphviz dependency: libtiff
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.9_3.high_sierra
==> Downloading from https://akamai.bintray.com/23/2338c777aad152907291b35f40f27
######################################################################## 100.0%
==> Pouring libtiff-4.0.9_3.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.0.9_3: 246 files, 3.5MB
==> Installing graphviz dependency: webp
==> Downloading https://homebrew.bintray.com/bottles/webp-1.0.0.high_sierra.bott
==> Downloading from https://akamai.bintray.com/d8/d84c923512187318d2538983b0c51
######################################################################## 100.0%
==> Pouring webp-1.0.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/webp/1.0.0: 38 files, 2MB
==> Installing graphviz dependency: gd
==> Downloading https://homebrew.bintray.com/bottles/gd-2.2.5.high_sierra.bottle
==> Downloading from https://akamai.bintray.com/ff/ff7aa2d452c6c05f8d41dee63bbd1
######################################################################## 100.0%
==> Pouring gd-2.2.5.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gd/2.2.5: 35 files, 1.1MB
==> Installing graphviz
==> Downloading https://homebrew.bintray.com/bottles/graphviz-2.40.1.high_sierra
==> Downloading from https://akamai.bintray.com/b5/b592ce51c2a929c3da82e96ec8565
######################################################################## 100.0%
==> Pouring graphviz-2.40.1.high_sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/graphviz/2.40.1: 500 files, 11.2MB
==> Downloading https://homebrew.bintray.com/bottles/lcov-1.13.high_sierra.bottl
######################################################################## 100.0%
==> Pouring lcov-1.13.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/lcov/1.13: 17 files, 543KB
==> Installing dependencies for python: xz
==> Installing python dependency: xz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.4.high_sierra.bottle
==> Downloading from https://akamai.bintray.com/e7/e7be50f4ee00e35887f3957263334
######################################################################## 100.0%
==> Pouring xz-5.2.4.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.4: 92 files, 1MB
==> Installing python
==> Downloading https://homebrew.bintray.com/bottles/python-3.6.5.high_sierra.bo
==> Downloading from https://akamai.bintray.com/7e/7e0fc1b078b51d9478ab08660d5df
######################################################################## 100.0%
==> Pouring python-3.6.5.high_sierra.bottle.1.tar.gz
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install
==> /usr/local/Cellar/python/3.6.5/bin/python3 -s setup.py --no-user-cfg install
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin

If you need Homebrew's Python 2.7 run
  brew install python@2

Pip, setuptools, and wheel have been installed. To update them run
  pip3 install --upgrade pip setuptools wheel

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.6/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python/3.6.5: 4,736 files, 99.2MB
Error: No such keg: /usr/local/Cellar/dep
Warning: Already linked: /usr/local/Cellar/automake/1.16.1
To relink: brew unlink automake && brew link automake
Warning: Already linked: /usr/local/Cellar/libtool/2.4.6_1
To relink: brew unlink libtool && brew link libtool
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
Linking /usr/local/Cellar/llvm@4/4.0.1... 2666 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/llvm@4/bin:$PATH"' >> ~/.bash_profile
Warning: Already linked: /usr/local/Cellar/wget/1.19.5
To relink: brew unlink wget && brew link wget
Warning: Already linked: /usr/local/Cellar/cmake/3.11.2
To relink: brew unlink cmake && brew link cmake
Warning: Already linked: /usr/local/Cellar/gmp/6.1.2_2
To relink: brew unlink gmp && brew link gmp
Linking /usr/local/Cellar/gettext/0.19.8.1... 197 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile
Warning: Already linked: /usr/local/Cellar/mongodb/3.6.5
To relink: brew unlink mongodb && brew link mongodb
Warning: Already linked: /usr/local/Cellar/doxygen/1.8.14
To relink: brew unlink doxygen && brew link doxygen
Warning: Already linked: /usr/local/Cellar/graphviz/2.40.1
To relink: brew unlink graphviz && brew link graphviz
Warning: Already linked: /usr/local/Cellar/lcov/1.13
To relink: brew unlink lcov && brew link lcov
Warning: Already linked: /usr/local/Cellar/python/3.6.5
To relink: brew unlink python && brew link python
	Homebrew exited with the above errors.
	Exiting now.

ELs-MacBook-Pro:eos elhadramidah$

**Comment by pacificcode** [comment]
@hadramidah Your clone of the EOSIO repo needs to be updated. Run the following command (capture the output of the script and if you run into any further issues paste the output here and Ill get you through it)

cd /path/to/eos
rm -rf build/
git pull
git submodule update --init --recursive
./eosio_build.sh

**Comment by hadramidah** [comment]
Thanks @pacificcode for the replay.
Eosio was successfully installed. Make test is underway.

**Comment by datacorder** [comment]
Same problem here with same configuration.
Same solution proposed solved the problem,
