### ISSUE TITLE
inconsistency in bad_alloc handling logic; also the handling logic is fragile

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#3348]
There is currently an inconsistency in how the `boost::interprocess::bad_alloc` exception handling logic works depending on if the originator of the `push_block` or `push_transaction` that caused the `bad_alloc` was the network plugin or the chain plugin. 

If the originator was the chain plugin, then it should gracefully exit nodeos and it may (see below) return the `BAD_ALLOC` error code. If the originator was the network plugin, then the exception will be logged and dropped, which means nodeos will continue likely to get another `bad_alloc` very soon after.

The reason I said it may return a `BAD_ALLOC` error code above is because the way we determine whether the exception was due to a bad allocation is fragile. 

There is an expectation that the `boost::interprocess::bad_alloc` exception will bubble up unmodified until it is caught by the catch block of either `read_write::push_block`, `read_write::push_transaction`, or `read_write::push_transactions` of chain_plugin. From there a `SIGUSR1` signal is raised which is handled by the lambda in `application::exec` of appbase, which cleanly shuts down and then throws a new `boost::interprocess::bad_alloc`. Then that exception should be caught by the appropriate catch block in the main.cpp file of nodeos. 

The bubbling of the second `boost::interprocess::bad_alloc` should be fine, but the original `boost::interprocess::bad_alloc` exception may be modified as it bubbles up the function call stack because of any of the various `FC_CAPTURE_AND_RETHROW` or similar macros that we liberally (and inconsistently) use throughout the code. That means in some cases (such as a bad_alloc due to creating an undo session in `controller::start_block`) the `boost::interprocess::bad_alloc` exception bubbles up undisturbed, but in other cases (such as while executing an input transaction) the `boost::interprocess::bad_alloc` gets modified into an `fc::exception` (or a derived type of `fc::exception`) before it reaches the appropriate catch blocks in chain_plugin.

We need to find a more robust solution for handling `bad_alloc` exceptions or any other exceptions that we want to special case so that they cause graceful exits with appropriate error codes (e.g. this might also be applicable to `fixed_reversible_db_exception` and the exceptions thrown because the shared memory file is dirty).

**Comment by jafri** [comment]
Example of bad_alloc handling in #3364

**Comment by arhag** [comment]
Resolved by #3564.
