### ISSUE TITLE
nodeos i can see producer_plugin only

### ISSUE THREAD

**Issue by Bo3o2S** [EOSIO/eos#3349]
![image](https://user-images.githubusercontent.com/14229134/40458505-44911620-5f37-11e8-8560-9cf626a761a6.png)

when start the nodeos i can see only producer_plugin, is it correct?

command i input is

**./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin** 

Please tell me, thanks

**Comment by heifner** [comment]
Yes, that looks fine.
