### ISSUE TITLE
why blocks.log open is messy code??What should I do with it?

### ISSUE THREAD

**Issue by healthwallet** [EOSIO/eos#3350]
tail -f ~/.local/share/eosio/nodeos/data/blocks/blocks.log

����xh8��'��ޗ����+���W Ω"�~�0U _�4�SR���Pn
                                          ��
;VE�{���: 1/{y�+L��U7�&Mg'�
                           Y}VeQ�A�N �'-��ő1E�0UB7��f-[ehJ6�M���D]����j�����4�a#ܿ���H�={�<�j7��BK�0U NGVg�rW{T2z��=X��Z���久������iyab�������<��H�ƴ��jN���Ƒ1E�0UB��Jc5&�/��Y5ː�:��@���{�(�xJH��f���+̷���~�j��0U 
B%���OHo�N������M��(����:#�+��78���Y-���.�g���:�D1��2���Ǒ1E�0UB���-N5��݋�w�iKg���Օ��:�N�
].�q���QZ���xh`����u����ڤ
                         �0U !�̬�R�����:T��ߌD���D����':��a��\@3�vި���[+��fRE���{j����ȑ1E�0U�@�Vn�يr�.8�?�vZ��0����$LT��
                                                                                                                      ��n�G�(y���)���Q�1��0U D�PT]��ı��M��`��}��h�+a��g|�V�[�hV���(qj
��CV��`La:o��Q����i�u���J��ǳe��oJ��*M��ɑ{�%� 3�Y(�-��ʑ1E�0UB
oX!N�6�ǌ#� �"�#��Dn
�>]@��$����Pa��0U,�2� !!j�*4t�&���TϪ��?��*_�Q�.9��̣�p�H�8OO;D����y�x�?�5��"
���ˑ1E�0UB
          u���`���
                  ��3�����:�qŦ"_i����
�Z���&ݡ�w��0UA1���"8U���A?4�YQR�>    ��p�~.�,��)X�	��l�ˠ��(as%����!���}�C!���̑1E�0UB
                                                                                        ���4��3+����i5,
                                                                                                        �4
                                                                                                          ���1�um����g˟�L�;�JҭNw��0U `FtS�/�rSak�}��U
                                                                                                                                                     ��n`�$���9�+R?{�"i��)ع����žL̫����V��d

**Comment by bytemaster** [comment]
This is the binary storage of block data.  It isn't a human readable log file.  Perhaps we should rename the file.
