### ISSUE TITLE
Better handling of shared memory dirty exception

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#3351]
In the main.cpp file of nodeos, the catch block for `std::runtime_error` handles the special case of the exceptions thrown by chainbase when opening a shared memory file with the dirty flag.

There are a few problems with the way this is being handled right now.

First, the code in main.cpp should return a unique error code signaling that the shared memory file is dirty rather than return `SUCCESS`.

Second, it would be better to use a unique exception type to designate this dirty status rather than abusing the message of an `std::runtime_error`.

Third, this exception is vulnerable to being captured and rethrown as an `fc::exception` similar to `boost::interprocess::bad_alloc` as described in #3348. If this happens, nodeos would exit with the wrong error code. So whatever solution is used to solve #3348 (perhaps whitelisting certain special exception types from `FC_CAPTURE_AND_RETHROW` and similar macros) should also be applied in this case.

**Comment by brianjohnson5972** [comment]
@arhag is the issue still relevant?

**Comment by arhag** [comment]
@brianjohnson5972:

Some of these points have already been addressed, like returning the proper error code due to dirty chainbase DBs.

We are still using `std::runtime_error` and so it is at risk of being captured and rethrown as an `fc::exception`. But we check to see if the error message of either `fc::exception` or `std::runtime_error` exception is "database dirty flag set" or "database metadata dirty flag set" to return the `DATABASE_DIRTY` error code, which is an ugly hack but it works I guess.

I think it is okay to close this issue and then we can hopefully address it more elegantly in the future either when we handle Chainbase read-only / read-write access (with guards) more appropriately, or when we audit our usage of exceptions throughout the whole code base.
