### ISSUE TITLE
Public key not found in unlocked wallets

### ISSUE THREAD

**Issue by Hipponensis** [EOSIO/eos#3355]
Request: http://127.0.0.1:8888/v1/wallet/sign_transaction

On dawn-v3.0.0 it has no issues, but on dawn-v4.0.0 and dawn-v4.1.0 the response is:

`{"code":500,"message":"Internal Service Error","error":{"code":3120004,"name":"wallet_missing_pub_key_exception","what":"Missing public key","details":[{"message":"Public key not found in unlocked wallets EOS74msw4XHLrS13Ng6c89NCQtWGb7N7MPsbBpRq1e5nmgidpCi19","file":"wallet_manager.cpp","line_number":209,"method":"sign_transaction"}]}}`

cleos wallet keys (the wallet is not locked and already import Private key):

```
[[
    "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
    "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
  ],[
    "EOS6zNSZ2c3DrkNr5r8X8pYfEXFYkoyv6Zw1eJeNhrPinbnc9ZCod",
    "5JHqLRYm4e542YUBwLbfga46vDu1qkqNSpQsTPYLTvZ5D1Ue6p4"
  ],[
    "EOS74msw4XHLrS13Ng6c89NCQtWGb7N7MPsbBpRq1e5nmgidpCi19",
    "5HpaGAU3bqGNmMSvv5iPn9Z5HcAxaEVmmSDyFouXetsNAYCStAt"
  ]
]
```

**Comment by guolin21** [comment]
Maybe you need to specify the wallet data location with parameter --wallet-dir

**Comment by noprom** [comment]
Hi @Hipponensis , same problem here.

**Comment by wangzehui123456** [comment]
I have met the same question, but it don't work even I have add the parameter --wallet-dir @guolin21

**Comment by wangzehui123456** [comment]
nodeos -e -p eosio --resync-blockchain --data-dir /Users/user/eosio-wallet --wallet-dir /Users/user/eosio-wallet --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::wallet_api_plugin

**Comment by guolin21** [comment]
Need unlock this wallet with rpc unlock api.

**Comment by heifner** [comment]
cleos now launches a keosd which is the one cleos then communicates with by default. So the wallet running in nodeos is not being used. I suspect using the wallet plugin in nodeos just doesn't work anymore.

**Comment by iFrankWu** [comment]
Yes, It is a daemon wallet was started  by keosd. just access http://localhost:8900/

**Comment by wangzehui123456** [comment]
when I unlock this wallet with rpc unlock api, it works very well.

**Comment by taokayan** [comment]
Did you connect to a different keosd server?

**Comment by andriantolie** [comment]
The `cleos wallet keys` very likely shows your wallet running on port 8900. So you need to call this instead `http://127.0.0.1:8900/v1/wallet/sign_transaction`
