### ISSUE TITLE
The get_transactions has been removed，What alternative interface do we have to obtain account history transaction records?

### ISSUE THREAD

**Issue by chenfengqiannian** [EOSIO/eos#3357]
from [#3317](https://github.com/EOSIO/eos/issues/3317) i see the get_transactions has been removed

What alternative interface do we have to obtain account history transaction records?

Or did I miss something?

**Comment by ismyhc** [comment]
Im very curious about this too. I've been searching all day. I can get transactions for an account through get_actions, but it only seems to be initiated actions and not receiving actions.

**Comment by bigbo1225** [comment]
Im very curious about this too. wait reply...

**Comment by andriantolie** [comment]
Use get_actions from history_api_plugin instead. account_history_api_plugin is deprecated
