### ISSUE TITLE
is i64i64i64 invalid table type?

### ISSUE THREAD

**Issue by OracleChain** [EOSIO/eos#3358]
doushadeMacBook-Pro:delphyforecast cl$ cleos -u http://127.0.0.1:8889/ --wallet-url http://127.0.0.1:8890/ get table -l 100 delphyfore delforeadm appeal
Error 3060003: Contract Table Query Exception
Error Details:
Invalid table type i64i64i64

**Comment by elmato** [comment]
@OracleChain, can you post a link to the source code (with the abi file included)?

**Comment by OracleChain** [comment]
/*
@abi table
*/
struct QueryResult{
    uint64_t idquery;

    uint8_t checked;
    uint64_t appealnum;
    std::string readvalue;
    std::string result;
    std::string unitrate;

    uint64_t created;
    uint64_t updated;

    uint64_t primary_key()const { return idquery; }

    EOSLIB_SERIALIZE(QueryResult, (idquery)(checked)(appealnum)(readvalue)(result)(unitrate)(created)(updated));
};

**Comment by FortisFortuna** [comment]
So what is the proper way to mark the abi to allow for secondary keys to be searched?

**Comment by bytemaster** [comment]
i64i64i64 table is not supported in latest eosio.
