### ISSUE TITLE
Producer Plugin runs into the future without limit...

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3359]
If you have a single producer responsible for all future blocks and you spam the blockchain, the producer will still fill blocks way into the future.

It should start rejecting transactions and apply back-pressure to the sender.

**Comment by bytemaster** [comment]
On a related issue, if a single transaction "overflows the block" simply because it is big and not because the block is almost full, it should be deferred until the next block and the current block should remain open.

**Comment by DouglasHorn** [comment]
How do we determine the line between the TX being too big or the block being too full? Should we designate a percentage threshold?
