### ISSUE TITLE
How can I get packed_trx?

### ISSUE THREAD

**Issue by bonsoo-koo** [EOSIO/eos#3361]
I knew packed_trx was needed for push_transaction.

How can I get packed_trx?

**Comment by ximinchao** [comment]
You can refer to eosjs, Fcbuffer will help you

**Comment by spartucus** [comment]
Maybe [EOSDevHelper](https://github.com/OracleChain/EOSDevHelper) will help you. Related code: [packed_trx](https://github.com/OracleChain/chainkit/blob/febe34e95d2ba022e58438ee215bc9a1619edeb4/chain/packedtransaction.cpp#L19).

**Comment by bonsoo-koo** [comment]
Is there a way to get " packed_trx " without installing other programs?
For example, REST API

**Comment by andriantolie** [comment]
You can use `cleos convert` command for this
