### ISSUE TITLE
get actions return null

### ISSUE THREAD

**Issue by bitcodernull** [EOSIO/eos#3362]
DAWN-2018-05-22

i want to get actions or transactions with accout, but i have gotten noting
i don't konw why?

i have set ` filter_on_accounts = jinmao3` in config.ini

`./cleos.sh get currency balance eosio.token jinmao3  EOS`
`2000.0000 EOS`

`./cleos.sh get actions jinmao3`
`seq  when                              contract::action => receiver      trx id...   args`

**Comment by vjoke** [comment]
solved #3244

**Comment by lcg635** [comment]
same problem

**Comment by nicholaspai** [comment]
same issue here, is there a fix to reset default behavior surpassing all actions?
