### ISSUE TITLE
A signature is required when a transaction is sent in the contract. How to solve it ?

### ISSUE THREAD

**Issue by AIYP1226** [EOSIO/eos#3363]
`           swop<N(dao),N(exchange)> actSwop ={from,stAst,"dao"};
            trx.actions.emplace_back(vector<permission_level>{{N(fund),N(active)}},actSwop);
            trx.delay_sec = 2;
            trx.send(0,N(fund));
            print("send defer\n");`

Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"fund","permission":"active"}', but does not have signatures for it under a provided delay of 2000 ms

**Comment by AIYP1226** [comment]
Do I need to import signature modules within the contract?  Is there any other way

**Comment by bytemaster** [comment]
Error message is misleading, "signatures" also means account delegated authority.
