### ISSUE TITLE
Edge Case: delegatebw and undelegatebw can cause account limbo (Error: 3080001) 

### ISSUE THREAD

**Issue by dskvr** [EOSIO/eos#3366]
## Summary
System contract allows account to unstake tokens if the account has a staking requirement, doesn't clear the bytes consumed, and then places the account in a limbo, where it will not have the bandwidth required to stake the account's tokens. Additionally, it prevents another account from delegating bandwidth as well. 

## Replicate
1. delegate bw: `cleos system delegatebw eosio testaccount "10 SYS" "10 SYS"`
2. stake bw: `cleos system delegatebw testaccount testaccount "10 SYS" "10 SYS"`
3. undelegate bw: `cleos system undelegatebw testaccount testaccount "10 SYS" "10 SYS"`
4. unstake bw: `cleos system undelegatebw eosio testaccount "10 SYS" "10 SYS"`
5. delegate bw: `cleos system delegatebw eosio testaccount "10 SYS" "10 SYS"`

**The last command throws:**

```
$ cleos system delegatebw eosio testaccount "10 SYS" "10 SYS"
1786650ms thread-0   main.cpp:1083                 operator()           ] act_payload: {"from":"eosio","receiver":"testaccount","stake_net_quantity":"10.0000 SYS","stake_cpu_quantity":"10.0000 SYS","transfer":false} 
1786651ms thread-0   main.cpp:419                  create_action        ] result: {"binargs":"0000000000ea30550000000d399ea6c1a0860100000000000453595300000000a086010000000000045359530000000000"} arg: {"code":"eosio","action":"delegatebw","args":{"from":"eosio","receiver":"testaccount","stake_net_quantity":"10.0000 SYS","stake_cpu_quantity":"10.0000 SYS","transfer":false}} 
Error 3080001: account using more than allotted RAM usage
Error Details:
account testaccount has insufficient ram; needs 3964 bytes has 0 bytes
```

Considering `delegatebw` is from a **priviledged** account to another account, why would it matter what the target account's RAM allocation is?  

If I try to buy ram manually: 
```
$ cleos system buyram testaccount testaccount "100 SYS" 
3271366ms thread-0   main.cpp:419                  create_action        ] result: {"binargs":"0000000d399ea6c10000000d399ea6c140420f00000000000453595300000000"} arg: {"code":"eosio","action":"buyram","args":{"payer":"testaccount","receiver":"testaccount","quant":"100.0000 SYS"}} 
Error 3081001: transaction reached the deadline set due to leeway on account CPU limits
Error Details:
the transaction was unable to complete by deadline, but it is possible it could have succeeded if it were allow to run to completion
```

**What the account looks like:**

```
$ cleos get account testaccount
privileged: false
permissions: 
     owner     1:    1 EOS5q1GZ13iHoDcYE8WSKn6jRe1LDcUpHFKqzLyUNuKUTV97pDheY
     active    1:    1 EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
     
memory: 
     quota:     6.553 Mb     used:     3.871 Kb   

net bandwidth: (averaged over 3 days)
     used:               485 bytes
     available:            0 bytes
     limit:                0 bytes

cpu bandwidth: (averaged over 3 days)
     used:             6.676 ms   
     available:            0 us   
     limit:                0 us   

producers:     <not voted>
```

The balance
```
$ cleos get currency balance eosio.token testaccount SYS
80.0000 SYS
```

Note: This account is registered as a producer.

```Producer      Producer key                                           Url                                                         Scaled votes
testaccount      EOS5q1GZ13iHoDcYE8WSKn6jRe1LDcUpHFKqzLyUNuKUTV97pDheY  https://testaccount.eos                                       1.0000
someaccount      EOS5q1GZ13iHoDcYE8WSKn6jRe1LDcUpHFKqzLyUNuKUTV97pDheY  https://someaccount.eos                                       0.0000
```

**Comment by moskvanaft** [comment]
It's kind of by design - user have to have RAM to run actions that write to DB. In this case someone should buy RAM for this user (`cleos buyram`).

**Comment by moskvanaft** [comment]
Actually it's really strange. I cannot explain what's going on here.
@dskvr , did you run any commands except those 4 ? (voting, buying/selling ram)

**Comment by moskvanaft** [comment]
> Note: This account is registered as a producer.

This can explain everything. Producer is eligible for paying for his data. His data changes when someone votes for him. When you delegate bandwidth to someone, his voting power changes. It may potentially affect producers. We have not foreseen that producer's RAM can affect voting/delegation. I need to know more details.
@dskvr, Who has voted for whom in this case?

**Comment by moskvanaft** [comment]
Now I can reproduce it.
My account has huge RAM quota and low usage:
```
$ cleos get account anton -j
{
  "account_name": "anton",
  "privileged": false,
  "last_code_update": "1970-01-01T00:00:00.000",
  "created": "2018-05-25T15:28:40.000",
  "ram_quota": "6218815765",
  ...
  "ram_usage": 4292,
```

And I get this error message:
```
Error 3080001: account using more than allotted RAM usage
Error Details:
account anton has insufficient ram; needs 3960 bytes has 0 bytes
```
which contradicts to account.

**Comment by moskvanaft** [comment]
fixed
