### ISSUE TITLE
dawn-v4.1.0,DAWN-2018-05-22,master banch failed set eosio.system contract,  Error 3050003

### ISSUE THREAD

**Issue by zformular** [EOSIO/eos#3368]
already set it after set eosio.token, create and issue eosio
![1527157505294](https://user-images.githubusercontent.com/1741302/40480016-d1e08784-5f7f-11e8-8ca5-f40f3e475e0a.jpg)

**Comment by cppfuns** [comment]
cd /eos/build/contracts
//部署eosio.token合约
cleos set contract eosio.token eosio.token
//创建代币 (BM将线上代码EOS 改成了SYS，之后上线后还是EOS)
cleos push action eosio.token create '["eosio","10000000000.0000 SYS",0,0,0]' -p eosio.token
//发布代币
cleos push action eosio.token issue '["eosio","10000000000.0000 SYS","issue"]' -p eosio
//部署eosio.system合约
cleos set contract eosio eosio.system -p eosio
//-----------------------------------------------
你需要修改你脚本里的EOS为SYS!!! 

我希望中文像英语一样强大，所以我用中文回复！
I hope Chinese is as strong as English, so I reply in Chinese.

**Comment by OuterSpaceTears** [comment]
I encountered the same problem when I was set contract eosio.

**Comment by taokayan** [comment]
Have you created the corresponding account?

**Comment by dixia** [comment]
closed as no reply
