### ISSUE TITLE
Nodeos shutdown on cleos create account

### ISSUE THREAD

**Issue by jafri** [EOSIO/eos#3369]
On a chain with eosio.token, eosio.token, eosio.msig and eosio.system deployed, running the following:

```
cleos create account eosio syedalijafri EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
```
leads to the printed error:
```
158686ms thread-0   main.cpp:2493                 main                 ] Failed with error: Bad Cast (7)
Invalid cast from type 'null_type' to Object
```
and nodeos shuts down with error
```
158685ms thread-0   net_plugin.cpp:2954           plugin_shutdown      ] shutdown..
158685ms thread-0   net_plugin.cpp:2957           plugin_shutdown      ] close acceptor
158685ms thread-0   net_plugin.cpp:2960           plugin_shutdown      ] close 0 connections
158685ms thread-0   net_plugin.cpp:2968           plugin_shutdown      ] exit shutdown
158686ms thread-0   fork_database.cpp:94          close                ] states.size(): 2 
158686ms thread-0   controller.cpp:261            ~controller_impl     ] db.revision(): 11 head->block_num: 11 blog.read_head()->block_num(): 10 
158714ms thread-0   main.cpp:101                  main                 ] bad alloc
```

**Comment by zformular** [comment]
which version? maybe you should try new one

**Comment by zformular** [comment]
@jafri  I run the same version, i can create account, do you deployed eosio.bios? maybe you should try in this order, it works for me.
1. set contract eosio ./contracts/eosio.bios -p eosio
2. create account eosio eosio.token pubkey pubkey
3. set contract eosio.token ./contracts/eosio.token -p eosio.token


there are some problem when i deploy eosio.system(Error 3050003: eosio_assert_message assertion failure), how do you get this worked?

**Comment by jafri** [comment]
The eosio.system is deployed using ```
cleos set contract eosio $EOS_BUILD_DIR/contracts/eosio.system -p eosio
```
The problem is creating accounts after eosio.system is deployed which is throwing error.

**Comment by heifner** [comment]
@jafri Please update and try latest. Your line number indicates you are running an older version.
