### ISSUE TITLE
Error 3040005: Expired Transaction when creating account

### ISSUE THREAD

**Issue by aniketdivekar** [EOSIO/eos#3370]
I'm following [this](https://github.com/EOSIO/eos/wiki/Tutorial-Getting-Started-With-Contracts) tutorial and when creating account I'm getting below error 

```
Error 3040005: Expired Transaction
Please increase the expiration time of your transaction!
Error Details:
transaction has expired, expiration is 2018-05-24T08:16:35 and pending block time is 2018-05-24T11:45:40.500
```
The only thing I did differently is instead of starting the node using command line directly, I used docker.
Any help would be much appreciated.

**Comment by aniketdivekar** [comment]
Getting below error when tying to execute below command:

Command:
`cleos transfer eosio.token myaccount "110.0000 EOS" memo`

Error: 
```
1946241ms thread-0   net_plugin.cpp:2423           handle_message       ] accept txn threw  3040005 expired_tx_exception: Expired Transaction
transaction has expired, expiration is 2018-05-27T17:09:53 and pending block time is 2018-05-27T17:27:20.000
    {"trx.expiration":"2018-05-27T17:09:53","pending_block_time":"2018-05-27T17:27:20.000"}
    thread-0  controller.cpp:1380 validate_expiration

    {"trx":{"expiration":"2018-05-27T17:09:53","ref_block_num":3054,"ref_block_prefix":1715752243,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio.token","name":"transfer","authorization":[{"actor":"eosio.token","permission":"active"}],"data":"00a6823403ea3055000000006405dd34e0c810000000000004454f5300000000046d656d6f"}],"transaction_extensions":[]}}
    thread-0  controller.cpp:1387 validate_expiration
```

**Comment by ctverceles** [comment]
were you able to find a solution to Error 3040005? im having the same issue using a docker image as well

**Comment by denis4net** [comment]
I have got the same issue when stale block production wasn't enabled for `nodeos`.
When I started `./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin`, issue was fixed.

Also, you can try to play with expiration `-x` argument.

**Comment by moskvanaft** [comment]
I am closing the ticket since solution was already provided in 2 last comments.
