### ISSUE TITLE
RPC API /v1/wallet/list_keys always shows the private keys.

### ISSUE THREAD

**Issue by noprom** [EOSIO/eos#3372]
I am using the EOS RPC API to develop some dapps, when I unlock my wallet using `/v1/wallet/unlock`, I can use `/v1/wallet/list_keys` to get all my keys, and these keys are exposed to the internet.
There may be some security problems.

How can I disable the `/v1/wallet/list_keys` RPC API?
Or can we add some params to restrict the API only to those who have their wallet password?
Maybe we can add params: `wallet_name` and `wallet_password` to this API.

**Comment by brianjohnson5972** [comment]
The wallet_plugin is not intended for use in a live environment, it is only intended for ease of testing.  A user should never send their private keys off of their devices because then they can no longer be assured they are safe.

**Comment by noprom** [comment]
Hi @brianjohnson5972 , thanks to the reply. What if I am building an EOS ios wallet? If the wallet_plugin can not be used, how can I do this?

**Comment by noprom** [comment]
Hi @brianjohnson5972 , is it possible that we can sign a transaction offline on the iOS device and then using RPC API to push the transaction to the blockchain?
