### ISSUE TITLE
 error: generating default genesis file failed when run "nodeos" 

### ISSUE THREAD

**Issue by Justin-ye** [EOSIO/eos#3373]
in the official wiki "Creating and Launching a Single Node Testnet"

JiQin-MacBook-Pro:nodeos $ nodeos 
1321454ms thread-0   chain_plugin.cpp:130          plugin_initialize    ] initializing chain plugin
1321454ms thread-0   chain_plugin.cpp:194          plugin_initialize    ] 
 generating default genesis file /path/to/eos/source/genesis.json
1321454ms thread-0   main.cpp:106                  main                 ] 11 eof_exception: End Of File
unexpected end of file
    {}
    thread-0  json.cpp:427 variant_from_stream

**Comment by larryk85** [comment]
@Justin-ye it appears as if you are using an older version based on the line number "chain_plugin.cpp:194 plugin_initialize".  Please retry with the latest changes.
