### ISSUE TITLE
currency::inline_transfer and INLINE_ACTION_SENDER return  returns error code 3090003 

### ISSUE THREAD

**Issue by wchh** [EOSIO/eos#3378]
in newest marster branch

in my contract invoke: 
currency::inline_transfer and INLINE_ACTION_SENDER  returns error code 3090003 :

cleos push action xpa.ex deposit '["wang.1", "100.0000 SYS", ""]' -p wang.1
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"wang.1","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms

**Comment by filipniziol** [comment]
How did you solve it?
I am getting a similar problem:
https://github.com/EOSIO/eos/issues/3847
