### ISSUE TITLE
Contract does not work after re-deploy

### ISSUE THREAD

**Issue by cluestudio** [EOSIO/eos#3397]
I changed the contract and rebuilt it. After that, I deployed the contact.
A message indicating successful completion has been printed.
```sh
$ url=http://121.168.149.101:8888/
$ cleos -u $url set contract ck.code ck -p ck.code
Reading WAST/WASM from ck/ck.wasm...
Using already assembled WASM...
Publishing contract...
executed transaction: d27b88f1ac2ad837a3a562f4960718dfcf329dd88978e97c7275d9360d0ec2d3  38088 bytes  12836 us
#         eosio <= eosio::setcode               {"account":"ck.code","vmtype":0,"vmversion":0,"code":"0061736d0100000001c5011f60027f7e0060037f7e7f00...
#         eosio <= eosio::setabi                {"account":"ck.code","abi":""}
warning: transaction executed locally, but may not be confirmed by the network yet
```

But then, no action works.
```sh
$ cleos -u $url push action ck.code signin '["ck.code"]' -p ck.code
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: read
```

Also, can not access the data which were saved before.
```sh
$ cleos -u $url get table ck.code ck.code player
Error 3060003: Contract Table Query Exception
Error Details:
Table player is not specified in the ABI
```

'player' table is specified in the abi
```
  "tables": [{
      "name": "player",
      "index_type": "i64",
      "key_names": [
        "owner"
      ],
      "key_types": [
        "name"
      ],
      "type": "player"
    },{
```

Contract modification / redistribution was 30 ~ 40 times. In the meantime, there was no problem.
I have tried to roll back the contract code, but it still does not work.

**Comment by bytemaster** [comment]
try latest master, and/or post the code / usage instructions.

**Comment by cluestudio** [comment]
Here is our source code.
https://github.com/bada-studio/ck_contract

Until 8277cd30593d469ca050d53a4ffc9a972f25095d, it was fine.
After that, I modified some codes, deployed contract and it brings kind of data crash.
The action just after the contract deployment was "rebirth".

I'll try the latest master.
And I backed it up the blocks.log file and blocks.index
If you need it, I can send you these files (but, kinda really big size)

**Comment by cluestudio** [comment]
Ah! 
Im' not sure, but the versions may be different between my test-net and local 'eoscpp' to build contract.
I use many machines during development. I'll try to deploy with another machine, it must be the same version with my test-net.

**Comment by cluestudio** [comment]
Sorry, it's my fault.
It was the version issue. 
It solved.
