### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#340]
`docker build -t eosio/eos -f Docker/Dockerfile .
...
Step 12 : RUN cd /tmp/eos/build && cmake -DWASM_LLVM_CONFIG=/opt/wasm/bin/llvm-config -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_INSTALL_PREFIX=/opt/eos ../   && make -j$(nproc) && make install && mv ../contracts /   && ln -s /opt/eos/bin/eos* /usr/local/bin   && rm -rf /tmp/eos*
 ---> Running in 0101d9acbb90
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using custom FindBoost.cmake
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
-- Using custom FindBoost.cmake
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   coroutine
-- Configuring Eos on Linux
-- BINARYEN_BIN not defined looking in PATH
-- BINARYEN_BIN => /usr/local
-- Using WASM clang => /opt/wasm/bin/clang
-- Using WASM llc => /opt/wasm/bin/llc
-- Using WASM llvm-link => /opt/wasm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.a  
-- Configuring fc to build on Unix/Apple
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.a (found version "1.0.2g") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- zlib found
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- bzip2 found
CMake Error at libraries/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    /tmp/eos/libraries/chainbase

  does not contain a CMakeLists.txt file.

-- egenesis: /tmp/eos/genesis.json
-- embed_genesis_args: -t/tmp/eos/libraries/egenesis/egenesis_brief.cpp.tmpl---/tmp/eos/build/libraries/egenesis/egenesis_brief.cpp-t/tmp/eos/libraries/egenesis/egenesis_full.cpp.tmpl---/tmp/eos/build/libraries/egenesis/egenesis_full.cpp--genesis-json/tmp/eos/genesis.json
CMake Error at libraries/CMakeLists.txt:9 (add_subdirectory):
  The source directory

    /tmp/eos/libraries/appbase

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/tmp/eos/build/CMakeFiles/CMakeOutput.log".
The command '/bin/sh -c cd /tmp/eos/build && cmake -DWASM_LLVM_CONFIG=/opt/wasm/bin/llvm-config -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_INSTALL_PREFIX=/opt/eos ../   && make -j$(nproc) && make install && mv ../contracts /   && ln -s /opt/eos/bin/eos* /usr/local/bin   && rm -rf /tmp/eos*' returned a non-zero code: 1
`

**Comment by toonsevrin** [comment]
#334 I'm working on it.

**Comment by toonsevrin** [comment]
Actually this is unrelated to the thing I'm working on, you have to fetch the modules:

To download all of the code, download Eos and a recursion or two of submodules. The easiest way to get all of this is to do a recursive clone:

git clone https://github.com/eosio/eos --recursive

If a repo is cloned without the --recursive flag, the submodules can be retrieved after the fact by running this command from within the repo:

git submodule update --init --recursive

**Comment by peterwillcn** [comment]
@bitcoiners  Any choice of a suitable instruction to run can solve your problem
```
git clone https://github.com/eosio/eos --recursive && \
cd eos  && docker build -t eosio/eos -f Docker/Dockerfile .
```
or 
```
cd eos && git checkout . && git fetch && git pull origin master && \
git submodule update --init --recursive && \
docker build -t eosio/eos -f Docker/Dockerfile .
```
