### ISSUE TITLE
how can get all of transactions of user

### ISSUE THREAD

**Issue by gaoyaxing24** [EOSIO/eos#3405]
I want to get all transactions of account.  i can get it when dawn3.0 use  `/v1/account_history/get_transactions`. bug dawn4.1 can't get it.
It's useless for me to plugin eosio::history_api_plugin.  and `/v1/history/get_transactions` or `/v1/account_history/get_controlled_accounts` all of useless.
always 404.
but at dawn3.0 it's all good.

how i can use old `/v1/account_history/*` RPC API if i upgrade to dawn4.1?

Server: Ubuntu 16.04

**Comment by andriantolie** [comment]
Use `get_actions` from the new `history_api_plugin` instead. `account_history_api_plugin` is deprecated. Furthermore, you will need to add the account that you want to track in your config.ini's `filter-on` parameter.

**Comment by MarcelBlockchain** [comment]
any way to get also all incoming transactions?
