### ISSUE TITLE
create account question

### ISSUE THREAD

**Issue by Liu-Bolun** [EOSIO/eos#3407]
When I use test Node A to produce blocks(producer:eosio)，and use another test Node B to synchronize blocks (but don’t form blocks), at this point when default wallet is open at Node B, I declare:

cleos -u http://B_IP:8888/ --wallet-url http://B_IP:8899/ create account eosio alafa4 EOS8hVSgyC3hGb5sPoJDfkQmvFfyjMR6PYvTUzvBpMMyhr296rG49 EOS7zUeBp2hiBarG3zhpFzwH3gr91qbpvkjmX8wmiHMjXtAbKRXnQ
It successfully generates account alafa4.

And then enter the same command:
cleos -u http://B_IP:8888/ --wallet-url http://B_IP:8899/ create account eosio alafa4 EOS8hVSgyC3hGb5sPoJDfkQmvFfyjMR6PYvTUzvBpMMyhr296rG49 EOS7zUeBp2hiBarG3zhpFzwH3gr91qbpvkjmX8wmiHMjXtAbKRXnQ

It will cause the automatic closure of NODEOS at Node B.

**Comment by andriantolie** [comment]
It's impossible to use wallet_plugin on nodeos anymore now. You will need to use keosd. As this is problem with outdated software, I'm going to close this issue. 

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
