### ISSUE TITLE
Why can't get transaction detail? 

### ISSUE THREAD

**Issue by zformular** [EOSIO/eos#3408]
i'm sure the transaction exists, but i can't get any details

![1527240800197](https://user-images.githubusercontent.com/1741302/40537527-bca1692a-6041-11e8-8071-782828701303.jpg)

**Comment by ripley** [comment]
@yankunsam 

When the db plugins are ready, mongo or sql, will they be capable of parsing block and save more detail in database?

**Comment by yankunsam** [comment]
Sorry, it is up to the core team. :)

**Comment by InfoHunter** [comment]
looks the same to #3244

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
