### ISSUE TITLE
Fails in make test

### ISSUE THREAD

**Issue by Catley94** [EOSIO/eos#3409]
Hey, I'm getting errors in the test with the latest pull:

29/32 Test #29: nodeos_run_test ........................***Failed    9.02 sec
      Start 30: nodeos_run_remote_test
30/32 Test #30: nodeos_run_remote_test .................***Failed   11.28 sec
      Start 31: distributed-transactions-test
31/32 Test #31: distributed-transactions-test ..........***Failed   26.28 sec
      Start 32: distributed-transactions-remote-test
32/32 Test #32: distributed-transactions-remote-test ...***Failed   25.56 sec

88% tests passed, 4 tests failed out of 32

Total Test time (real) = 1374.69 sec

The following tests FAILED:
         29 - nodeos_run_test (Failed)
         30 - nodeos_run_remote_test (Failed)
         31 - distributed-transactions-test (Failed)
         32 - distributed-transactions-remote-test (Failed)
Errors while running CTest
Makefile:61: recipe for target 'test' failed
make: *** [test] Error 8

[CMakeError.log](https://github.com/EOSIO/eos/files/2038877/CMakeError.log)

**Comment by Liu-Bolun** [comment]
before you test,you must Enter(default install):
(1)~/opt/mongodb/bin/mongod -f ~/opt/mongodb/mongod.conf &
(2)source /opt/rh/python33/enable
(3) export PATH=${HOME}/opt/mongodb/bin:$PATH
(4) cd eos/build
(5) make test

**Comment by taokayan** [comment]
We haven't received any update for this. Please try setting environment variable EOSIO_HOME to the build path and test it again. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
