### ISSUE TITLE
bios-boot-tutorial.py gets failed with error "Error 3120003: Locked wallet"

### ISSUE THREAD

**Issue by trungtt1981** [EOSIO/eos#3412]
From the tutorial of eosio bios boot sequence (https://github.com/EOSIO/eos/wiki/Tutorial-Bios-Boot-Sequence), I've tried running the script "bios-boot-tutorial.py". However, it gets failed with the following error:

test.py: cleos --wallet-url http://localhost:6666 --url http://localhost:8000 wallet import 5K463ynhZoCDDa4RDcr63cUwWLTnKqmdcoTKTHBjqoKfv4u5V7p
1877369ms thread-0   http_plugin.cpp:369           handle_exception     ] FC Exception encountered while processing wallet.import_key: 3120003 wallet_locked_exception: Locked wallet
Wallet is locked: default
    {"w":"default"}
    thread-0  wallet_manager.cpp:172 import_key
Error 3120003: Locked wallet
Ensure that your wallet is unlocked before using it!
Error Details:
Wallet is locked: default
test.py: exiting because of error

**Comment by matthewdarwin** [comment]
You need to unlock your wallet.
There should be * next to "default" if the wallet is unlocked.

**Comment by trungtt1981** [comment]
@matthewdarwin 
Thanks for your response.
But I think the Python script should have unlocked the created wallet automatically, right?

**Comment by matthewdarwin** [comment]
You are correct, the code says it removes the existing wallet, and then create one.  So it should be created as unlocked.

def startWallet():
    run('rm -rf ' + walletDir)
    run('mkdir -p ' + walletDir)
    background('keosd --http-server-address 127.0.0.1:6666 --wallet-dir ' + walletDir)
    time.sleep(.4)
    run(cleos + 'wallet create')

**Comment by trungtt1981** [comment]
@matthewdarwin 
I've tried disabling the start of "keosd" because I think it's not needed at all as the command "cleos wallet create" will auto start the "keosd". The result is that its works like charm

So, disable the line to make it work:
background('keosd --http-server-address 127.0.0.1:6666 --wallet-dir ' + walletDir)
