### ISSUE TITLE
buyram from eosio: no balance object found

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eos#3414]
Something regressed in system contract very recently. I had a script to setup accounts and buy/delegate to them. It was working.
Now it fails on
```
cleos system buyram eosio anton '100000.0000 SYS' -p eosi
assertion failure with message: no balance object found
```

**Comment by brianjohnson5972** [comment]
We could add this to the nodeos_run_test.py script. @cj_oci

**Comment by adeelnaqvi172** [comment]
![Screenshot from 2020-09-08 22-48-29](https://user-images.githubusercontent.com/53054023/92511027-2adc9680-f226-11ea-8e1b-a2940c6afcac.png)

@moskvanaft  i am facing this error please help
