### ISSUE TITLE
install eos-wallet-app-master err

### ISSUE THREAD

**Issue by zzwwzh** [EOSIO/eos#342]
Follow the README.md:
## Get started

* Install all dependencies via `yarn` (preferably) or `npm i`
* Start project via `npm start`

When i run `yarn` : 

yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "stylelint-config-standard@17.0.0" has unmet peer dependency "stylelint@^8.0.0".
warning "stylelint-config-recommended@1.0.0" has unmet peer dependency "stylelint@^8.0.0".
[4/4] Building fresh packages...
[-/2] ⠁ waiting...
[2/2] ⠁ node-sass
[-/2] ⠁ waiting...
[-/2] ⠁ waiting...
error /root/eos-wallet-app-master/node_modules/node-sass: Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/install.js
Directory: /root/eos-wallet-app-master/node_modules/node-sass
Output:
module.js:491
    throw err;
    ^

Error: Cannot find module 'asn1'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/eos-wallet-app-master/node_modules/sshpk/lib/formats/pem.js:9:12)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

ls -l:
total 660
drwxr-xr-x.   3 root root   4096 Aug 23 04:58 config
-rw-r--r--.   1 root root   4687 Aug 23 04:58 CONTRIBUTING.md
drwxr-xr-x. 949 root root  36864 Sep  5 17:50 node_modules
-rw-r--r--.   1 root root   2969 Aug 23 04:58 package.json
-rw-r--r--.   1 root root 362348 Aug 23 04:58 package-lock.json
drwxr-xr-x.   4 root root   4096 Aug 23 04:58 public
-rw-r--r--.   1 root root   1804 Aug 23 04:58 README.md
drwxr-xr-x.   2 root root   4096 Aug 23 04:58 scripts
drwxr-xr-x.  11 root root   4096 Aug 23 04:58 src
-rw-r--r--.   1 root root 234306 Aug 23 04:58 yarn.lock

I don't know how to fix it, need help please.

**Comment by zzwwzh** [comment]
and i run `npm start` : 
#npm start

> eosjs-ui@0.1.0 start /root/eos-wallet-app-master
> node scripts/start.js

Starting the development server...

Failed to compile.

./src/styles/index.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/root/eos-wallet-app-master/node_modules/node-sass/vendor'

**Comment by sergmetelin** [comment]
Is this an issue for this repo? https://github.com/EOSIO/eos-wallet-app

**Comment by zzwwzh** [comment]
@sergmetelin yes

**Comment by heifner** [comment]
Closing. Not relevant to this project.
