### ISSUE TITLE
Set initial producer "pause" via config or cli argument

### ISSUE THREAD

**Issue by aaroncox** [EOSIO/eos#3435]
```
POST /v1/producer/pause - pause production
POST /v1/producer/resume - resume from paused production
POST /v1/producer/paused - return true/false depending on whether the node is currently paused
```

These new controls are great - and while I believe they were added primarily for coordination in troubleshooting, it also may have uses for block producer failover scripts. 

Assuming the utility of these APIs for failover - it would be useful if a node could be started in a "paused" block-production state. This could be done with a command line argument (`--start-production-paused`?) or potentially a line in the `config.ini`.

This would allow you to run "hot spares" essentially, that start up in a paused state using the same signing key as the primary producing node. If the primary node fails/misses blocks, a script could trigger that:

- triggers `/v1/producer/pause` on the current primary to stop production (if it's even responding).
- triggers `/v1/producer/resume` on the hot spare to take over production.

A potentially non-MVP worthy addition; but this would remove the need for failover scripts submit excess `regproducer` txs in order to change keys and force a swap of nodes.

**Comment by matthewdarwin** [comment]
+100

**Comment by wanderingbort** [comment]
This should already be available with the "pause-on-startup" config or long
CLI option or the short CLI argument "-x"

**Comment by aaroncox** [comment]
That's fantastic, closing this issue since it's already available. I hadn't gotten around to the source yet - only reading the release notes.
