### ISSUE TITLE
set account permission error,help

### ISSUE THREAD

**Issue by fyy000** [EOSIO/eos#3436]
I change player's permission like this.
`
cleos set account permission player active '{"threshold":1,  "accounts":[{"permission":{"actor":"player","permission":"active"}, "weight":1}]}' owner -p player
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"player","permission":"active"}', but does not have signatures for it.
`
now it's this.
`
cleos get account player
privileged: false
permissions: 
     owner     1:    1 EOS6UeNf3xoagyEvT5k7qQehov5iCVvADScMBhuYkqSjNmsWeyQuA
        active     1:    1 player@eosio.code, 
memory: 
     quota:        -1 bytes  used:     3.037 Kb   

net bandwidth: (averaged over 3 days)
     used:                -1 bytes
     available:           -1 bytes
     limit:               -1 bytes

cpu bandwidth: (averaged over 3 days)
     used:                -1 us   
     available:           -1 us   
     limit:               -1 us
`
I want to revert it, but it's failed.
`
cleos set account permission player active '{"threshold":1, "keys":[{"key":"EOS6UeNf3xoagyEvT5k7qQehov5iCVvADScMBhuYkqSjNmsWeyQuA", "weight":1}], "accounts":[{"permission":{"actor":"player","permission":"active"}, "weight":1}]}' owner -p player
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"player","permission":"active"}', but does not have signatures for it.
`

I want to reset player's permission,how can I do it?

**Comment by bytemaster** [comment]
Use -p player@owner.
