### ISSUE TITLE
p2p-sync-on-new-node-improvements

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#344]
I found that when there are 2 or more active nodes, my naive synchronization requesting algorithm resulted in out-of-sequence blocks. As a solution, I have reworked the algorithm to more closely conform to the original model described in protocol.hpp. In this case a potentially large request is divided into smaller chunks. The chunk that follows the current head of the lagging chain passes incoming blocks directly to the chain. subsequent chunks are retrieved from other nodes and cached. At the point when syncing head reaches the end of the current chunk, a subsequent chunk is identified and any cached blocks are applied to the chain. This process is iterated until the lagging chain is caught up.

**Comment by bytemaster** [comment]
Sounds good... is there a pull request for review?

What happens when there is a timeout on one of the junks or a connection is dropped?

**Comment by pmesnier** [comment]
PR is coming, you can look at branch p2p-sync-improvment. (yeah its misspelled, sorry)

It should be possible to transfer chunk ownership in the case of a dead or hung supplier but I want to get this part working first. I just pushed to the branch, but Im not ready for a PR. Maye this evening.

**Comment by pmesnier** [comment]
closing, code is merged
