### ISSUE TITLE
"producer double-confirming known range" error when testing failover

### ISSUE THREAD

**Issue by jchung00** [EOSIO/eos#3442]
Tag: dawn-v4.2.0.
We have two nodes, same producer key and config, and one of them starts with production paused. They both run on the same machine.
Block producing node 1 start producing when the nodes start. Block producing node 2 syncs fine. We run `curl -sL http://127.0.0.1:<node-1-port>/v1/producer/pause` and `curl -sL http://127.0.0.1:<node-2-port>/v1/producer/resume`.
Block producing node 2 begins producing with no problems.
Then, we run `curl -sL http://127.0.0.1:<node-2-port>/v1/producer/pause` and `curl -sL http://127.0.0.1:<node-1-port>/v1/producer/resume`.
This causes the `producer double-confirming known range` assertion exception. We checked that this is where the assertion is defined in EOS.IO: https://github.com/EOSIO/eos/blob/3b70b5757a093f8a4db7be04734134ce65a8106a/libraries/chain/block_header_state.cpp#L158

We also noticed that block producing node 2 can't resync with the chain even when we run it with the `--hard-replay-blockchain` option.

**Comment by gleehokie** [comment]
Thanks for the report, I'll bring this to the devs attention.

**Comment by wanderingbort** [comment]
I will create a more specific issue for this and reference this issue in
it.

One of the concepts not ready for fail over is the watermark calculated by
the producer_plugin.  This watermark is used to determine how many blocks
to confirm with each produced block.

For the particular scenario you describe we can fix this by scanning
incoming blocks for producers who are also local producers.  That way your
backup node will have accurate watermarks

Inaccurate watermarks trick on node into double committing past blocks
which is a considered Byzantine failure and is why you cannot easily
recover

**Comment by noprom** [comment]
Look forward to the fix.

**Comment by abourget** [comment]
Also, I'm seeing that many nodes with the same keys loaded will all "counter-sign" all blocks. It doesn't fork or anything, and it's probably signing the same digest everywhere.. but I would have expected all signing to stop if you `pause` production.  Would that make sense ?

**Comment by EOSBIXIN** [comment]
when I test in 1.0.6 I suffer the same bug after call resume&pasue API in second time to switch master & slaver.

the error message:
on_incoming_block    ] 10 assert_exception: Assert Exception
nodeosd_1  | 2018-06-27T09:44:39.503449026Z prior != by_id_idx.end(): unlinkable block

**Comment by jchung00** [comment]
Any update on this issue?

**Comment by abourget** [comment]
Was it solved?
