### ISSUE TITLE
/usr/local/include/eosiolib/types.h:7:10: fatal error: 'stdint.h' file not found on Mac

### ISSUE THREAD

**Issue by sikeeoh** [EOSIO/eos#3447]
```
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>
using namespace eosio;
class hello : public eosio::contract {
public:
using contract::contract;

  void hi( account_name user ) {
     print( "Hello, ", name{user} );
  }
};

EOSIO_ABI( hello, (hi) )
```

I have already run sudo make install in build
eosiocpp -o hello.wast hello.cpp
Error : 
/usr/local/include/eosiolib/types.h:7:10: fatal error:
      'stdint.h' file not found

**Comment by zokir** [comment]
You probably tried to alias eosiocpp?  If you already ran `sudo make install`, just unset eosiocpp alias and rerun.

eosiocpp script looks for install directory(that later used to find includes) by looking at where eosiocpp script located.

**Comment by sikeeoh** [comment]
I solved it.
rebooted after sudo make install.
