### ISSUE TITLE
About set contract eosio.bios Error

### ISSUE THREAD

**Issue by lelence** [EOSIO/eos#3448]
eosio: dawn-v4.2.0,  
OS: macOs High Sierra 10.13.4

compile success, when I import contract eosio.bios, there is an error like this:

> \> cleos set contract eosio contracts/eosio.bios -p eosio
Reading WAST/WASM from ../../contracts/eosio.bios/eosio.bios.wasm...
Using already assembled WASM...
Publishing contract...
1754499ms thread-0   main.cpp:2552                 main                 ] Failed with error: Bad Cast (7)
Invalid cast from type 'string_type' to Object

**Comment by heifner** [comment]
Make sure you restart keosd
