### ISSUE TITLE
About mongo_db_plugin

### ISSUE THREAD

**Issue by Lomect** [EOSIO/eos#3450]
`mongo_db_plugin` is not work since dawn-v4.0.0, i want to know the plugin will be repaired or not?

**Comment by jafri** [comment]
It is not currently seeing active development. Follow the sql plugin instead, which will be updated in the upcoming week.

**Comment by noprom** [comment]
@jafri Is this confirmed by the official EOS team?

**Comment by chenfengqiannian** [comment]
What is your progress now？
One week has passed.

**Comment by red-butterfly** [comment]
Our company also have to use the db plugin.
mongodb or sqlite3 ? Which one is the EOS team will update??
@bytemaster

**Comment by heifner** [comment]
Plan on starting work on mongo plugin this week.

**Comment by noprom** [comment]
That's awesome!

**Comment by oviwankenobi** [comment]
it would've been nice to have an explanation on why was this closed: is the work on mongo plugin done? replaced by other plug in (sql plugin)? or?
thanks.
