### ISSUE TITLE
dice contract can't work

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#3454]
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"dice","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms

**Comment by vjoke** [comment]
you need to call the updateauth to grant eosio.code to your account. 
cleos set account permission your_account active '{"threshold": 1,"keys": [{"key": "YourPubKey","weight": 1}],"accounts": [{"permission":{"actor":"dice","permission":"eosio.code"},"weight":1}]}' owner -p your_account

**Comment by yankunsam** [comment]
Thanks. It works. But is it reasonable for "eosio.code" permission?

**Comment by vjoke** [comment]
This might be changed in the future, maybe in version 1.2

**Comment by heifner** [comment]
Closing this since dice is being removed by #6023
