### ISSUE TITLE
build fails -   Unable to find the requested Boost libraries.

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#3464]
After pulling latest git master build fails.

```
...
...updated 15709 targets...
	Boost 1.67.0 successfully installed @ /root/opt/boost_1_67_0.

	Checking MongoDB installation.
	MongoDB configuration found at /root/opt/mongodb/mongod.conf.

	Checking MongoDB C++ driver installation.
	Mongo C++ driver found at /usr/local/lib/libmongocxx-static.a.

	Checking secp256k1-zkp installation.
	secp256k1 found @ /usr/local/lib.

	Checking for LLVM with WASM support.
	WASM found at /root/opt/wasm/bin.


>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOSIO

>>>>>>>> CMAKE_BUILD_TYPE=Release
>>>>>>>> ENABLE_COVERAGE_TESTING=false
>>>>>>>> DOXYGEN=false

-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:665 (file):
  file STRINGS file "/root/opt/boost_1_66_0/include/boost/version.hpp" cannot
  be read.
Call Stack (most recent call first):
  CMakeLists.txt:88 (FIND_PACKAGE)


CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 0.0.0

  Boost include path: /root/opt/boost_1_66_0/include

  Detected version of Boost is too old.  Requested version was 1.67 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:88 (FIND_PACKAGE)


-- Configuring Eos on Linux
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using 'SYS' as CORE symbol name
-- Using 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV' as public key for eosio account
-- Using WASM clang => /root/opt/wasm/bin/clang
-- Using WASM llc => /root/opt/wasm/bin/llc
-- Using WASM llvm-link => /root/opt/wasm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Configuring fc to build on Unix/Apple
-- zlib found
-- Configuring Builtins
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:665 (file):
  file STRINGS file "/root/opt/boost_1_66_0/include/boost/version.hpp" cannot
  be read.
Call Stack (most recent call first):
  libraries/chainbase/CMakeLists.txt:26 (FIND_PACKAGE)


CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 0.0.0

  Boost include path: /root/opt/boost_1_66_0/include

  Detected version of Boost is too old.  Requested version was 1.57 (or
  newer).
Call Stack (most recent call first):
  libraries/chainbase/CMakeLists.txt:26 (FIND_PACKAGE)


-- Configuring ChainBase on Linux
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:665 (file):
  file STRINGS file "/root/opt/boost_1_66_0/include/boost/version.hpp" cannot
  be read.
Call Stack (most recent call first):
  libraries/appbase/CMakeLists.txt:22 (find_package)


CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 0.0.0

  Boost include path: /root/opt/boost_1_66_0/include

  Detected version of Boost is too old.  Requested version was 1.60 (or
  newer).
Call Stack (most recent call first):
  libraries/appbase/CMakeLists.txt:22 (find_package)


-- Configuring AppBase on Linux
-- Git commit revision: 07a67985
-- Git commit revision: 07a67985
-- Git commit revision: 07a67985
-- Configuring incomplete, errors occurred!
See also "/root/eos/build/CMakeFiles/CMakeOutput.log".
See also "/root/eos/build/CMakeFiles/CMakeError.log".

	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.

```

**Comment by spartucus** [comment]
seem issue. commit id: 07a6798584d053ed6061bd892879c6c886ba104e

**Comment by gleehokie** [comment]
@spartucus and @bitcoiners what platform are you compiling on?

**Comment by bitcoiners** [comment]
tried on Ubuntu 16.04 and 18.04

**Comment by spartucus** [comment]
Hi @gleehokie , Ubuntu 16.04 x64

**Comment by bt-cryptomancer** [comment]
Hi, I am also having this problem on Ubuntu 16.04.  It appears the eosio_build.sh script updated my Boost to 1.67.0 but the build expects version 1.66.0 and now that version no longer exists on my system.

**Comment by gleehokie** [comment]
@bitcoiners @spartucus @bt-cryptomancer both Ubuntu 16.04 and 18.04 are working on our CI system right now.  The CI Docker images start with Boost installed though.

If you want to get by this tonight I suggest you manually uninstall Boost and then reinstall Boost 1.67.  Let us know if you get by on that.

**Comment by jafri** [comment]
This is a problem with `Boost_INCLUDE_DIR` being outdated, which does not get updated when boost is upgraded. 

Running this *should* work:
```export Boost_INCLUDE_DIR="${HOME}/opt/boost_1_67_0"```

**Comment by bitcoiners** [comment]
@jafri I tried
```
 export BOOST_INCLUDE_DIR="${HOME}/opt/boost_1_67_0"
echo $BOOST_INCLUDE_DIR
/root/opt/boost_1_67_0

```
Problem did not go away.

**Comment by jafri** [comment]
@bitcoiners please try updated:

```
export Boost_INCLUDE_DIR="${HOME}/opt/boost_1_67_0/include"
```

**Comment by bitcoiners** [comment]
@jafri 
Tried.
No change.

**Comment by bt-cryptomancer** [comment]
I got it to work just now by explicitly setting BOOST_ROOT in CMakeLists.txt, like this:

set( BOOST_ROOT "/myhomedir/opt/boost_1_67_0" )

**Comment by spartucus** [comment]
@jafri export env way does not work, since it is already in `eosio_build.sh`.
> line 189: export BOOST_ROOT="${HOME}/opt/boost_1_67_0"

**Comment by jchung00** [comment]
One workaround is to `cd` into `~/opt` and removed the boost library there.
Re-compile using `./eosio_build.sh` and it should work.

**Comment by jon0008** [comment]
remove all file and all folders except .git in eos directory
git reset --hard HEAD
recompile

**Comment by jon0008** [comment]
remove all file and all folders except .git in eos directory
git reset --hard HEAD
recompile

**Comment by jon0008** [comment]
remove all file and all folders except .git in eos directory
git reset --hard HEAD
recompile

**Comment by jon0008** [comment]
remove all file and all folders except .git in eos directory
git reset --hard HEAD
recompile

**Comment by bitcoiners** [comment]
Deleting and cloning a new repo copy works. Problem gone.

**Comment by spartucus** [comment]
Yet it's not a proper solution.

**Comment by pacificcode** [comment]
@spartucus @bt-cryptomancer @bitcoiners @jon0008 @jcalfee @jafri it looks as though you have a old CMakeCache.txt file. Run the following commands.

cd /path/to/eos
rm -rf build/
git checkout master
git pull
git submodule update --init --recursive
./eosio_build.sh

Also, it is recommended when building EOS to do as as an unprivileged user i.e. /home/your_user_name

**Comment by jgiszczak** [comment]
The less brute force method is:

`cd /path/to/eos/build`
`rm CMakeCache.txt`
`rm -r CMakeFiles`
`cd ..`
`./eosio_build.sh`

Some IDEs provide this feature in a menu.  Qt Creator, for instance, provides the `Build | Clear CMake Configuration` menu option, which does the above steps for you.  CMake is aggressive about caching.  Sometimes it is necessary to smack it on the nose with a rolled up newspaper.

**Comment by Marwen-Bhj** [comment]
> I got it to work just now by explicitly setting BOOST_ROOT in CMakeLists.txt, like this:
> 
> set( BOOST_ROOT "/myhomedir/opt/boost_1_67_0" )

which CMakeLists.txt file are you talking about exactly
