### ISSUE TITLE
 How to confirm if a transaction is confirmed without history_api_plugin?

### ISSUE THREAD

**Issue by vjoke** [EOSIO/eos#3466]
I want to monitor all the transactions of my wallet, do I need to implement a custom service to handle these requirments? or am I missing anything already existed?

**Comment by njappboy** [comment]
Please review the [keosd](https://github.com/EOSIO/eos/wiki/Programs-&-Tools#keosd) api.

You should review the sample exchange implementation and also https://github.com/EOSIO/eos/blob/master/tutorials/exchange-tutorial-python/exchange_tutorial.py

**Comment by halsaphi** [comment]
Answered by njappboy, no further comments since 28 May.
