### ISSUE TITLE
run bios-boot-tutorial.py error: eosio_assert_message assertion failure

### ISSUE THREAD

**Issue by gunnergit** [EOSIO/eos#3468]
## error logs:

> bios-boot-tutorial.py: ../../build/programs/cleos/cleos --wallet-url http://localhost:6666 --url http://localhost:8000 system newaccount eosio --transfer producer1114 EOS69tWc1VS6aP2P1D8ryzTiakPAYbV3whbHeWUzfD8QWYuHKqQxk --stake-net "200.0000 SYS" --stake-cpu "200.0000 SYS"
315301ms thread-0   main.cpp:428                  create_action        ] result: {"binargs":"0000000000ea305540420857219de8ad00200000"} arg: {"code":"eosio","action":"buyrambytes","args":{"payer":"eosio","receiver":"producer1114","bytes":8192}}
315309ms thread-0   main.cpp:428                  create_action        ] result: {"binargs":"0000000000ea305540420857219de8ad80841e0000000000045359530000000080841e0000000000045359530000000001"} arg: {"code":"eosio","action":"delegatebw","args":{"from":"eosio","receiver":"producer1114","stake_net_quantity":"200.0000 SYS","stake_cpu_quantity":"200.0000 SYS","transfer":true}}
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: overdrawn balance
## Testnet

- EOSIO git version: 13076119

- Command line: 
`./bios-boot-tutorial.py -a`

**Comment by trungtt1981** [comment]
I've got the same issue.
The previous revision was not incurred by this issue.

**Comment by trungtt1981** [comment]
The error is about "overdrawn balance".
A possible work-around is to reduce the number of producers and users as follows:

> ./bios-boot-tutorial.py -all --producer-limit 10 --user-limit 10 --num-voters 5 --num-producers-vote 5

**Comment by taokayan** [comment]
Do you have enough balance to create the account? you should at least have around 401 EOS.

**Comment by halsaphi** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
