### ISSUE TITLE
DAWN4.2 get actions return null

### ISSUE THREAD

**Issue by vjoke** [EOSIO/eos#3469]
in DAWN4.1, with --filter-on *, I can get all the logs. 
but this doesn't work in DAWN4.2 any more. 

I also change the filter-on to some specific string, such as "myaccount:transfer:", but still returns null

**Comment by bezalel** [comment]
try below
**nodeos --hard-replay-blockchain --filter-on exchange:transfer:**

--filter-on receiver:action:actor 
Actor may be blank to include all. Receiver and Action may not be blank.

**Comment by vjoke** [comment]
Tried with no luck.   thanks

**Comment by photon3108** [comment]
I have the same question. Does anyone `get action` successfully on dawn 4.2?

**Comment by guaiguaihw** [comment]
+1, same problem

**Comment by chrisran** [comment]
config filter-on param to monitor one account, no longer monitors all accounts by default. 

-f [ --filter-on ] arg            Track actions which match 
                                        receiver:action:actor. Actor may be 
                                        blank to include all. Receiver and 
                                        Action may not be blank.

**Comment by kristieguo** [comment]
I use the following method to fix the problem: delete data folder, use the command below beginning from the first time you start nodeo, then set up everything from scratch (create account and publish contract etc.), then get actions should be fine

```
./nodeos --filter-on "*"
```

**Comment by orange1337** [comment]
I was trying this one **--filter-on receiver:action:actor** when starting nodeos,
 but still /get_actions - empty array.

**Comment by andriantolie** [comment]
--filter-on will only track actions that are executed after the arg is enabled. To track past actions, please replay your blockchain

**Comment by nicholaspai** [comment]
is there a way to by default track all actions for a given receiver? Or do we have to specify every action

something like --filter-on receiver:*

**Comment by jgiszczak** [comment]
@nicholaspai The syntax is `--filter-on receiver::` or `--filter-on receiver:0:0`.
