### ISSUE TITLE
When using 'delegatebw" to vote,terminal has a error

### ISSUE THREAD

**Issue by LeslieRan** [EOSIO/eos#3470]
When using 'delegatebw" to vote,terminal has a error:**account voter has insufficient ram; needs 3798 bytes has 0 bytes**
Thanking you for reading!

**Comment by moskvanaft** [comment]
Can you please provide more details?
What version are you running?
What `cleos get acount <name>` shows before and after you get this error?

**Comment by taokayan** [comment]
The account doesn't have enough RAM reserved. Please buy ram first.
