### ISSUE TITLE
Test failed on CentOS

### ISSUE THREAD

**Issue by pplam** [EOSIO/eos#3472]
For the latest code, successfully built both on MacOS & CentOS but some tests(`Test #29 ~ #32`) failed on CentOS. With the first failure logs as following:
~~~
29/32 Testing: nodeos_run_test
29/32 Test: nodeos_run_test
Command: "/home/imt/eos/build/tests/nodeos_run_test.py" "-v" "--dump-error-detail"
Directory: /home/imt/eos/build
"nodeos_run_test" start time: May 28 13:34 CST
Output:
----------------------------------------------------------
terminate called after throwing an instance of 'fc::eof_exception'
launching bios
spawning child, programs/nodeos/nodeos --max-transaction-time 5000 --filter-on *  --config-dir etc/eosio/node_bios --data-dir var/lib/node_bios
launching testnet_00
spawning child, programs/nodeos/nodeos --max-transaction-time 5000 --filter-on *  --config-dir etc/eosio/node_00 --data-dir var/lib/node_00
**********************************************************************
run 'bash bios_boot.sh' to kick off delegated block production
**********************************************************************
"/home/imt/eos/build/programs/keosd/keosd" launched
Failed to connect to nodeos at http://localhost:8888; is nodeos running?
BEGIN
TEST_OUTPUT: test_output_0.txt
SERVER: localhost
PORT: 8888
 cmd: pkill -9 keosd
 cmd: programs/eosio-launcher/eosio-launcher -k 15
 cmd: pkill -9 nodeos
Stand up cluster
 cmd: programs/eosio-launcher/eosio-launcher -p 1 -n 1 -s mesh -d 1 -f --nodeos --max-transaction-time 5000 --filter-on *
    cmd: pgrep -a nodeos
  pgrep output: "20688 programs/nodeos/nodeos --max-transaction-time 5000 --filter-on * --config-dir etc/eosio/node_bios --data-dir var/lib/node_bios
20689 programs/nodeos/nodeos --max-transaction-time 5000 --filter-on * --config-dir etc/eosio/node_00 --data-dir var/lib/node_00
"
  Node> Host: localhost, Port:8888
 Cluster viability smoke test. Validate every cluster node has block 1.
         cmd: programs/cleos/cleos --url http://localhost:8888  --wallet-url http://localhost:8899 get info
          ERROR: Expected JSON response
          RAW >
Test failed.
  =================================================================
  Contents of etc/eosio/node_bios/config.ini:
genesis-json = ./genesis.json
blocks-dir = blocks
readonly = 0
send-whole-blocks = true
http-server-address = '
p2p-listen-endpoint = 0.0.0.0:9776
p2p-server-address = localhost:9776
enable-stale-production = true
allowed-connection = any
required-participation = 33
private-key = ["EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"]
producer-name = eosio
plugin = eosio::producer_plugin
plugin = eosio::net_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::history_api_plugin
~~~
It seems that `cleos` cannot connect to `http://localhost:8888` with `http-server-address` configured to `127.0.0.1:8788`. Maybe use `0.0.0.0:8888` instead of `127.0.0.1:8888` can fix this.

**Comment by pacificcode** [comment]
@pplam Im unable to reproduce this error (see below). It might be a good idea to remove your build directory and start over.

cd /path/to/eos
rm -rf build/
git pull
git submodule update --init --recursive
./eosio_build.sh
cd /path/to/eos/build
source /opt/rh/python33/enable
make test

### result from running make test
32/32 Test #32: distributed-transactions-remote-test ...   Passed   67.42 sec

100% tests passed, 0 tests failed out of 32

Total Test time (real) = 1002.79 sec

	Beginning build version: 1.2
	Mon May 28 17:30:46 UTC 2018
	User: bhamilton
	git head id: 07a6798584d053ed6061bd892879c6c886ba104e
	Current branch: master

	ARCHITECTURE: Linux

	OS name: CentOS Linux
	OS Version: 7
	CPU speed: 2399Mhz
	CPU cores: 2
	Physical Memory: 7821 Mgb
	Disk install: /dev/xvda1
	Disk space total: 511G
	Disk space available: 506G

**Comment by pplam** [comment]
@pacificcode Thanks for your explanation! I've tried again and figured out that there is some problems with my `/etc/hosts`. After I point `127.0.0.1` to `localhost`, it works. But here comes another failure:
~~~
97% tests passed, 1 tests failed out of 32

Total Test time (real) = 614.86 sec

The following tests FAILED:
         27 - .(SEGFAULT)
Errors while running CTest
make: *** [test] Error 8
~~~
Could you please show me how can i just perform the test on the failed `unit_test_wavm `, by this way the maybe i can make the problem clear faster.

**Comment by pacificcode** [comment]
@pplam pull the latest code from master and you should be good to go.
