### ISSUE TITLE
Retrieve chain_id in contracts

### ISSUE THREAD

**Issue by jafri** [EOSIO/eos#3474]
Is there a way to retrieve the `chain_id` from an executing smart contract?

**Comment by spartucus** [comment]
emm, RPC API `get_info` retrieve `chain_id`.

**Comment by jafri** [comment]
You cannot do that from inside a contract

**Comment by taokayan** [comment]
use ```cleos get info``` to obtain chain id, you'll get something as follow
```
"chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906"
```

There's no way to get it from the smart contract.
