### ISSUE TITLE
"Claim" function in smart contract not working

### ISSUE THREAD

**Issue by coinsooth** [EOSIO/eos#3476]
HELP!!! I have contributed to the token sale countless times, and then claimed my EOS tokens through the contract execution on myetherwallet. Today, I have not been able to claim my tokens for period 345. Is anyone else having issues. I am not overly technically skilled. Please advise, as I am in a serious panic.

**Comment by njappboy** [comment]
Please ask on the eosio telegram channel [https://t.me/EOSproject](https://t.me/EOSproject)

**Comment by taokayan** [comment]
close this since EOS ERC20 is not valid anymore.
