### ISSUE TITLE
A problem about fork

### ISSUE THREAD

**Issue by LeslieRan** [EOSIO/eos#3478]
Due to network latency，the next block-producer begins to produce block before it recieved the block from  previous block-producer.
Will this situation lead to fork?

**Comment by njappboy** [comment]
This should help you understand DPoS+BFT. 
[EOS: Explanation of DPoS+BFT w/ Daniel Larimer - Part 1 of 2](https://www.youtube.com/watch?v=Xs1dyZFhIr4)

**Comment by LeslieRan** [comment]
@njappboy Thank you！

**Comment by taokayan** [comment]
It will create a temporary fork but eventually the longer chain prevails while the shorter chain will be discarded.
