### ISSUE TITLE
INLINE_ACTION_SENDER occurs "transaction declares authority '{"actor":"askera","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms"

### ISSUE THREAD

**Issue by OracleChain** [EOSIO/eos#3482]
void ocaskans::transferInline(const transfer &trs)
{
    require_auth(trs.from);
    INLINE_ACTION_SENDER(eosdactoken, transfer)(tokenContract, {trs.from,N(active)},
   { trs.from, trs.to, trs.quantity, std::string("") } );
}

get erros:
transaction declares authority '{"actor":"askera","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms

**Comment by njappboy** [comment]
@OracleChain are your `declared authorizations` satisfied?

**Comment by gravitt8460** [comment]
I have this same problem, and yes, I have satisfied the declared authorizations.

**Comment by OracleChain** [comment]
@njappboy 
cleos  -u http://127.0.0.1:8888/ --wallet-url http://127.0.0.1:8890/ push action ocaskans ask '{"id":"1", "from":"askera", "quantity":"2.0000 OCT","createtime":"0","endtime":"20000","optionanswerscnt":"3","asktitle":"what is you name","optionanswers":"{\"A\":\"成吉思汗\",\"B\":\"毛泽东\",\"C\":\"拿破仑\"}"}' -p askera

**Comment by Frank-AFN** [comment]
Hi, oracheChain,  any update on this problem?

**Comment by wenhuizhao** [comment]
If you use userA permission to call action in contract A, and in the action you use inline_action_sender to call action in contract B, the contract B does not receive  the userA permission. Instead it is use contractB's owner and permission "eosio.code" to call action in contractB. 
To allow contract B  to use userA's permission, you can configure userA's permission to allow contractB owner and permission eosio.code to have userA's active permission. 
```
cleos set account permission userA active '{"threshold":1, "keys":[{"key":"...", "weight":1}], "accounts": [{"permission":{"actor":"contractBuser","permission":"eosio.code"},"weight":1}]}' owner -p userA
```

**Comment by OracleChain** [comment]
thank you!
@wenhuizhao

**Comment by sart77** [comment]
I have the same problem, where I need to insert code,  and how it should to look form me, tanks.

Transaction failed - transaction declares authority '{"actor":"arturlupasku","permission":"owner"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys ["EOS6XX7h2Rut7MW4JiJcwh2H4S2y9BAue5cZsaG8Q7Xdjq3h3mHMt"], and a delay max limit of 3888000000 ms
If you resolve errors and still have issues with ledger,

Transaction failed - Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE

**Comment by sart77** [comment]
![Screenshot 2020-12-11 12 58 11](https://user-images.githubusercontent.com/35669143/101899574-b7487d80-3bb6-11eb-817f-d6f883432e0d.png)
