### ISSUE TITLE
Unknown action buyrambytes in contract eosio

### ISSUE THREAD

**Issue by OracleChain** [EOSIO/eos#3483]
cleos -u http://127.0.0.1:8888/ --wallet-url http://127.0.0.1:8890/   system newaccount eosio voter EOS8cMSi7eiGXC8oWcNfYFf83BRToBoKS4Dp46ERA6Hkb1cCwMn42  EOS8cMSi7eiGXC8oWcNfYFf83BRToBoKS4Dp46ERA6Hkb1cCwMn42  --stake-net '50.00 EOS' --stake-cpu '50.00 EOS'
Error 3050000: action exception
Error Details:
Unknown action buyrambytes in contract eosio

```
"actions": [{
      "name": "buyrambytes",
      "type": "buyrambytes",
      "ricardian_contract": ""
   },{
```

**Comment by moskvanaft** [comment]
It seems like you have not installed system contract. cleos commands starting with "system" work only if you have system contract installed (I just checked - it works with latest master).
Without system contract installed you should use `cleos create account`.

**Comment by wypsanity** [comment]
I have same exception.do you solve this?

**Comment by mbassan** [comment]
Same here.... This has been the hardest coin I have worked with by far. Nothing works as expected.
