### ISSUE TITLE
Cannot unlock or open wallet created and stored in custom location

### ISSUE THREAD

**Issue by trungtt1981** [EOSIO/eos#3486]
Currently, the command "cleos wallet unlock" doesn't support to unlock the wallet stored in custom location.
Indeed, when option "-n" allows to specify only the wallet name which is looked up only in the default wallet directory "$HOME/eosio-wallet".

Similarly for the command "cleos wallet open"

**Comment by jgiszczak** [comment]
Custom locations for wallet is a function of `keosd` and is provided by the `--wallet-dir` argument.  No other customization of location will be supported.
