### ISSUE TITLE
./bios-boot-tutorial.py --symbol does not work

### ISSUE THREAD

**Issue by trungtt1981** [EOSIO/eos#3490]
./bios-boot-tutorial.py --symbol does not work with the following error:

> bios-boot-tutorial.py: ../../build/programs/cleos/cleos --wallet-url http://localhost:6666 --url http://localhost:8000 set contract eosio ../../build/contracts/eosio.system/
> Reading WAST/WASM from ../../build/contracts/eosio.system/eosio.system.wasm...
> Using already assembled WASM...
> Publishing contract...
> Error 3050003: eosio_assert_message assertion failure
> Error Details:
> assertion failure with message: unable to find key
>

**Comment by trungtt1981** [comment]
@elmato 
This means that I will need to modify the EOS platform source code for the custom system currency?

**Comment by elmato** [comment]
You can specify the core symbol name when calling cmake using `-DCORE_SYMBOL_NAME=ABC`
Can you paste the full argument list you are using when calling `./bios-boot-tutorial.py`?

**Comment by gleehokie** [comment]
The symbol used when calling `./bios-boot-tutorial.py` needs to match the symbol that was specified when you built the EOSIO platform from source code.  This was done this way for code execution speed reasons.

As @elmato said above, you can specify the core symbol using -DCORE_SYMBOL_NAME when you build the platform.

Note, if you are using Docker images provided by Block.one at https://hub.docker.com/u/eosio/ the core symbol is "SYS".

**Comment by littlekfc** [comment]
@gleehokie If use eosio_build.sh to build the source code, which parameter we need to pass? I meet the 'unable to find key' issue when I set system contract.

**Comment by OuterSpaceTears** [comment]
./eosio_build.sh -DCORE_SYMBOL_NAME=EOS

	Invalid Option: -D
	Usage: ./eosio_build.sh [Build Option -o <Debug|Release|RelWithDebInfo|MinSizeRel>] [CodeCoverage -c ] [Doxygen -d]

**Comment by littlekfc** [comment]
Added a pull request to support passing DCORE_SYMBOL_NAME to make fille. #3586
