### ISSUE TITLE
Latest checkout is not producing blocks..

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#35]
After a new build, I wiped all but my `data-dir/config.ini` file which still contains `enable-stale-production = true` and the 11 `producer-id` entries per the README.

>No producers configured! Please add producer IDs and private keys to configuration.

The ini file has not changed..

**Comment by jcalfee** [comment]
```bash
egrep "(producer-id|private-key)" data-dir/config.ini 
producer-id = {"_id":0}
producer-id = {"_id":1}
producer-id = {"_id":2}
producer-id = {"_id":3}
producer-id = {"_id":4}
producer-id = {"_id":5}
producer-id = {"_id":6}
producer-id = {"_id":7}
producer-id = {"_id":8}
producer-id = {"_id":9}
producer-id = {"_id":10}
private-key = ["EOS6MRyAjQ...","5KQ..."]
```

**Comment by jcalfee** [comment]
And, being docker I could start up the previous version..  So, the prior version still works so it is really looking like some recent change.

**Comment by nathanhourt** [comment]
Ping @bytemaster

**Comment by nathanhourt** [comment]
Nvm bytemaster, I thought recent meant less than two weeks ago. xP

Yeah, this one's on my plate, it's in 55a8470929e0ea2ebda9c7cfb9ff45038b640391

**Comment by nathanhourt** [comment]
@jcalfee OK, rebuild, check the new README and update your config.ini. Everything should work, but I did change it to a full round of 21 producers, and they are now referenced by account name rather than ID. Does that fix it?

**Comment by educatedwarrior** [comment]
Hey @jcalfee I'm testing the build as well and would like to help.  Are you using the docker manifest from this repo, or you using your own?

**Comment by jcalfee** [comment]
@educatedwarrior yes, i'm using the docker from this repo
@nathanhourt it works

**Comment by jcalfee** [comment]
@educatedwarrior I use variations of these commands in the root eos folder:

```bash
# Update Docker
git pull
git submodule update --init
docker build -t eos0619 Docker

# Inneractive Shell
docker run -p 8888:8888 -v /home/jcalfee/eosio/eos/data-dir:/work/data-dir -i -t eos0619 bash

# In Docker
./eos/programs/eosd/eosd

# External Test
curl http://127.0.0.1:8888/v1/chain/get_info
echo '{"block_num_or_id": 2}' | curl http://127.0.0.1:8888/v1/chain/get_block -d @-
```
