### ISSUE TITLE
Add "region" field to transaction

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#350]
Regions are high-level groupings of contracts. A contract in one region cannot read data stored in other regions with the exception of the "basic account permissions" which all regions need to track for validation.  

The only way to communicate among regions is via async message passing.

**Comment by bytemaster** [comment]
Note the code for contracts is also shared across all regions.

Think of regions as a higher-level scope.

**Comment by brianjohnson5972** [comment]
Will regions have an affect on the Account History API?

**Comment by heifner** [comment]
Regions have been removed.
