### ISSUE TITLE
Following tutorial error

### ISSUE THREAD

**Issue by Catley94** [EOSIO/eos#3509]
So I installed EOS and there are no errors in the test, but when I run "./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin " as per the instructions in the wiki, I receive this error:
catley@CatleySurface:/mnt/c/Users/scp94/Projects/EOS/eos/build/programs/nodeos$ ./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin
3470853ms thread-0   chain_plugin.cpp:151          plugin_initialize    ] initializing chain plugin
3470856ms thread-0   main.cpp:113                  main                 ] 10 assert_exception: Assert Exception
version == block_log::supported_version: Unsupported version of block log. Block log version is 1146614400 while code supports version 1
    {"version":1146614400,"supported":1}
    thread-0  block_log.cpp:473 extract_genesis_state

Thanks,

**Comment by pventuzelo** [comment]
Add ` --delete-all-blocks` and it should work
