### ISSUE TITLE
It is not compiling on Ubuntu 14.04

### ISSUE THREAD

**Issue by batonio** [EOSIO/eos#351]
...due to a reason of absense std::make_unique  in default GCC 4.8
[make.txt](https://github.com/EOSIO/eos/files/1278990/make.txt)

**Comment by elmato** [comment]
Can you try the instructions for Ubuntu 16.04 and see if it works?

https://github.com/EOSIO/eos/blob/master/README.md

**Comment by batonio** [comment]
It work on two Ubuntu 16.04 machine and not work on another Ubuntu 14.04 machine

**Comment by batonio** [comment]
Full configure and make log:
[make_full.txt](https://github.com/EOSIO/eos/files/1279248/make_full.txt)

**Comment by bytemaster** [comment]
Ubuntu 14.04 is not supported, please use Ubuntu 16

**Comment by yashwanth2804** [comment]
for me Ubuntu 16/18 with amd notebook causing heating issue (known bug ) . is there a way around 
thanks

**Comment by heifner** [comment]
Can you use docker?

**Comment by yashwanth2804** [comment]
No planning to , Thanks .I hope i can use docker instead of dualbooting or vm ware.correct me if i am wrong 
thanks
