### ISSUE TITLE
on system/compiler/boost change detection, (hard) replay takes 3 tries

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#3516]
When the system/compiler/boost change detection is activated it takes 3 tries to recover.

```
$ programs/nodeos/nodeos -d ~/eos.data/f --config-dir ~/eos.data/f
3470986ms thread-0   chain_plugin.cpp:151          plugin_initialize    ] initializing chain plugin
3470987ms thread-0   main.cpp:119                  main                 ] /Users/spoon/eos-noon-net/libraries/chainbase/src/chainbase.cpp(70): Throw in function chainbase::database::database(const bfs::path &, chainbase::database::open_flags, uint64_t, bool)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: database created by a different compiler, build, boost version, or operating system
```
try 1:
```
$ programs/nodeos/nodeos -d ~/eos.data/f --config-dir ~/eos.data/f --hard-replay-blockchain
3512872ms thread-0   chain_plugin.cpp:151          plugin_initialize    ] initializing chain plugin
3512872ms thread-0   chain_plugin.cpp:233          plugin_initialize    ] Hard replay requested: deleting state database
3512873ms thread-0   block_log.cpp:324             repair_log           ] Recovering Block Log...
3512874ms thread-0   block_log.cpp:344             repair_log           ] Moved existing blocks directory to backup location: '/Users/spoon/eos.data/f/blocks-2018-05-28T21:58:32.873'
3512874ms thread-0   block_log.cpp:349             repair_log           ] Reconstructing '/Users/spoon/eos.data/f/blocks/blocks.log' from backed up block log
3512874ms thread-0   block_log.cpp:455             repair_log           ] Existing block log was undamaged. Recovered all irreversible blocks up to block number 1.
3512875ms thread-0   chain_plugin.cpp:431          recover_reversible_b ] Reconstructing '/Users/spoon/eos.data/f/blocks/reversible' from backed up reversible directory
3512875ms thread-0   main.cpp:119                  main                 ] /Users/spoon/eos-noon-net/libraries/chainbase/src/chainbase.cpp(70): Throw in function chainbase::database::database(const bfs::path &, chainbase::database::open_flags, uint64_t, bool)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: database created by a different compiler, build, boost version, or operating system
```
That doesn't look like anything actually happened, but try 2:
```
$ programs/nodeos/nodeos -d ~/eos.data/f --config-dir ~/eos.data/f --hard-replay-blockchain
3544493ms thread-0   chain_plugin.cpp:151          plugin_initialize    ] initializing chain plugin
3544493ms thread-0   chain_plugin.cpp:233          plugin_initialize    ] Hard replay requested: deleting state database
3544494ms thread-0   block_log.cpp:324             repair_log           ] Recovering Block Log...
3544494ms thread-0   block_log.cpp:344             repair_log           ] Moved existing blocks directory to backup location: '/Users/spoon/eos.data/f/blocks-2018-05-28T21:59:04.494'
3544494ms thread-0   block_log.cpp:349             repair_log           ] Reconstructing '/Users/spoon/eos.data/f/blocks/blocks.log' from backed up block log
3544494ms thread-0   block_log.cpp:455             repair_log           ] Existing block log was undamaged. Recovered all irreversible blocks up to block number 1.
3544495ms thread-0   main.cpp:133                  main                 ] boost::interprocess_exception::library_error
```
Well, that's different. Let's try a third time
```
$ programs/nodeos/nodeos -d ~/eos.data/f --config-dir ~/eos.data/f --hard-replay-blockchain
3565892ms thread-0   chain_plugin.cpp:151          plugin_initialize    ] initializing chain plugin
3565892ms thread-0   chain_plugin.cpp:233          plugin_initialize    ] Hard replay requested: deleting state database
3565892ms thread-0   block_log.cpp:324             repair_log           ] Recovering Block Log...
3565892ms thread-0   block_log.cpp:344             repair_log           ] Moved existing blocks directory to backup location: '/Users/spoon/eos.data/f/blocks-2018-05-28T21:59:25.892'
3565893ms thread-0   block_log.cpp:349             repair_log           ] Reconstructing '/Users/spoon/eos.data/f/blocks/blocks.log' from backed up block log
3565893ms thread-0   block_log.cpp:455             repair_log           ] Existing block log was undamaged. Recovered all irreversible blocks up to block number 1.
3565901ms thread-0   block_log.cpp:123             open                 ] Log is nonempty
3565901ms thread-0   block_log.cpp:136             open                 ] my->head->block_num(): 1 
3565901ms thread-0   block_log.cpp:159             open                 ] Index is empty
3565901ms thread-0   block_log.cpp:297             construct_index      ] Reconstructing Block Log Index...
3565921ms thread-0   http_plugin.cpp:281           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
```

Works on third try.

**Comment by firesWu** [comment]
same issue in v1.3.0

**Comment by villesundell** [comment]
Still happening with v1.7.3

**Comment by ndcgundlach** [comment]
Working on re-creating the issue, I start from a chainbase created by v1.7.  Running from the develop branch of v1.8+:

./nodeos  -c jungle-config.ini
...
info  2019-07-16T17:52:19.611 nodeos    chain_plugin.cpp:379          operator()           ] Support for builtin protocol feature 'GET_SENDER' (with digest of 'f0af56d2c5a48d60a4a5b5c903edfb7db3a736a94ed589d0b797df33ff9d3e1d') is enabled with preactivation required
warn  2019-07-16T17:52:19.621 nodeos    chain_plugin.cpp:943          plugin_initialize    ] 13 N5boost10wrapexceptISt13runtime_errorEE: chainbase database format not compatible with this version of chainbase.
rethrow chainbase database format not compatible with this version of chainbase.: 
    {"what":"chainbase database format not compatible with this version of chainbase."}
    nodeos  chain_plugin.cpp:943 plugin_initialize
error 2019-07-16T17:52:19.622 nodeos    main.cpp:116                  main                 ] 13 N5boost10wrapexceptISt13runtime_errorEE: chainbase database format not compatible with this version of chainbase.
rethrow chainbase database format not compatible with this version of chainbase.: 
    {"what":"chainbase database format not compatible with this version of chainbase."}
    nodeos  chain_plugin.cpp:943 plugin_initialize


Now try with --hard-replay option:

./nodeos  -c jungle-config.ini --hard-replay

...
info  2019-07-16T19:05:55.999 nodeos    chain_plugin.cpp:717          plugin_initialize    ] Hard replay requested: deleting state database
info  2019-07-16T19:05:56.002 nodeos    block_log.cpp:411             repair_log           ] Recovering Block Log...
info  2019-07-16T19:05:56.003 nodeos    block_log.cpp:431             repair_log           ] Moved existing blocks directory to backup location: '/home/developer/.local/share/eosio/nodeos/data/blocks-2019-07-16T19:05:56.002'
info  2019-07-16T19:05:56.003 nodeos    block_log.cpp:436             repair_log           ] Reconstructing '/home/developer/.local/share/eosio/nodeos/data/blocks/blocks.log' from backed up block log
info  2019-07-16T19:05:56.005 nodeos    block_log.cpp:567             repair_log           ] Existing block log was undamaged. Recovered all irreversible blocks up to block number 1.
info  2019-07-16T19:05:56.007 nodeos    chain_plugin.cpp:1063         recover_reversible_b ] Reconstructing '/home/developer/.local/share/eosio/nodeos/data/blocks/reversible' from backed up reversible directory
warn  2019-07-16T19:05:56.007 nodeos    chain_plugin.cpp:943          plugin_initialize    ] 13 N5boost10wrapexceptISt13runtime_errorEE: chainbase database format not compatible with this version of chainbase.
rethrow chainbase database format not compatible with this version of chainbase.: 
    {"what":"chainbase database format not compatible with this version of chainbase."}
    nodeos  chain_plugin.cpp:943 plugin_initialize
error 2019-07-16T19:05:56.007 nodeos    main.cpp:116                  main                 ] 13 N5boost10wrapexceptISt13runtime_errorEE: chainbase database format not compatible with this version of chainbase.
rethrow chainbase database format not compatible with this version of chainbase.: 
    {"what":"chainbase database format not compatible with this version of chainbase."}
    nodeos  chain_plugin.cpp:943 plugin_initialize

resulting data dir:

tree .

.
├── blocks
│   ├── blocks.log
│   └── reversible
├── blocks-2019-07-16T19:05:56.002
│   ├── blocks.index
│   ├── blocks.log
│   └── reversible
│       ├── shared_memory.bin
│       └── shared_memory.meta
├── snapshots
└── state



try again (note different error):

./nodeos  -c jungle-config.ini --hard-replay

...
info  2019-07-16T19:08:50.357 nodeos    chain_plugin.cpp:717          plugin_initialize    ] Hard replay requested: deleting state database
info  2019-07-16T19:08:50.357 nodeos    block_log.cpp:411             repair_log           ] Recovering Block Log...
info  2019-07-16T19:08:50.357 nodeos    block_log.cpp:431             repair_log           ] Moved existing blocks directory to backup location: '/home/developer/.local/share/eosio/nodeos/data/blocks-2019-07-16T19:08:50.357'
info  2019-07-16T19:08:50.357 nodeos    block_log.cpp:436             repair_log           ] Reconstructing '/home/developer/.local/share/eosio/nodeos/data/blocks/blocks.log' from backed up block log
info  2019-07-16T19:08:50.358 nodeos    block_log.cpp:567             repair_log           ] Existing block log was undamaged. Recovered all irreversible blocks up to block number 1.
info  2019-07-16T19:08:50.358 nodeos    chain_plugin.cpp:1063         recover_reversible_b ] Reconstructing '/home/developer/.local/share/eosio/nodeos/data/blocks/reversible' from backed up reversible directory
warn  2019-07-16T19:08:50.358 nodeos    chain_plugin.cpp:943          plugin_initialize    ] 13 N5boost10wrapexceptISt13runtime_errorEE: database file not found at /home/developer/.local/share/eosio/nodeos/data/blocks-2019-07-16T19:08:50.357/reversible/shared_memory.bin
rethrow database file not found at /home/developer/.local/share/eosio/nodeos/data/blocks-2019-07-16T19:08:50.357/reversible/shared_memory.bin: 
    {"what":"database file not found at /home/developer/.local/share/eosio/nodeos/data/blocks-2019-07-16T19:08:50.357/reversible/shared_memory.bin"}
    nodeos  chain_plugin.cpp:943 plugin_initialize
error 2019-07-16T19:08:50.358 nodeos    main.cpp:116                  main                 ] 13 N5boost10wrapexceptISt13runtime_errorEE: database file not found at /home/developer/.local/share/eosio/nodeos/data/blocks-2019-07-16T19:08:50.357/reversible/shared_memory.bin
rethrow database file not found at /home/developer/.local/share/eosio/nodeos/data/blocks-2019-07-16T19:08:50.357/reversible/shared_memory.bin: 
    {"what":"database file not found at /home/developer/.local/share/eosio/nodeos/data/blocks-2019-07-16T19:08:50.357/reversible/shared_memory.bin"}
    nodeos  chain_plugin.cpp:943 plugin_initialize

Data dir:
.
├── blocks
│   ├── blocks.log
│   └── reversible
├── blocks-2019-07-16T19:05:56.002
│   ├── blocks.index
│   ├── blocks.log
│   └── reversible
│       ├── shared_memory.bin
│       └── shared_memory.meta
├── blocks-2019-07-16T19:08:50.357
│   ├── blocks.log
│   └── reversible
├── snapshots
└── state

**Comment by spoonincode** [comment]
Closing this because #7678 has been merged
