### ISSUE TITLE
About History API plugin

### ISSUE THREAD

**Issue by jeaimetu** [EOSIO/eos#3523]
Hi,
I am trying to following https://github.com/EOSIO/eos/wiki/Tutorial-Comprehensive-Accounts-and-Wallets.
Everything went fine except this one.

root@ubuntu-s-4vcpu-8gb-nyc1-01:~# cleos get servants eosio
Error 3110003: Missing History API Plugin
Ensure that you have eosio::history_api_plugin added to your node's configuration!
Error Details:
History API plugin is not enabled

This is the result of "ps -ef" 
nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin

As you can see, I added "history_api_plugin".

After searching issues board. I also found "https://github.com/EOSIO/eos/pull/3253/commits" was merged into master branch. So I use "git fech" to refresh my local.

compiling and installing them, error message still show same result.

Can you give me a clarification? 

My purpose is "want to retrieve accounts list" as similar to "cleos wallet list".

BR, Teddy.

**Comment by alexwishes** [comment]
The same issue when I run this command: " cleos get accounts ******** ",
And I found "CHAIN_RO_CALL(get_key_accounts)" was comment in plugins/history_api_plugin/history_api_plugin.cpp. 
I think this function was removed in the latest code(or some previous version?)

Is there anybody can give an official answer?

**Comment by andriantolie** [comment]
I verified on version 1.1.0 and it works find, for both `get servants` and `get accounts`. Please try again and if the issue persists, reopen this issue.
