### ISSUE TITLE
Proposal ICO Contract

### ISSUE THREAD

**Issue by enriquejr99** [EOSIO/eos#3528]
We have many contracts already but I believe an ICO contract is very basic just like the token contract is and would help developers issue new tokens easily and securely.

If someone decides to self-assign this issue, I would suggest supporting the following:
- Whitelist
- Hardcap
- Contribution limits

**Comment by grigio** [comment]
I think good source references for ICO are https://github.com/OpenZeppelin/openzeppelin-solidity/tree/master/contracts/crowdsale and DAICO https://github.com/theabyssportal/DAICO-Smart-Contract

**Comment by edevil** [comment]
Is there any equivalent to OpenZeppelin in the EOS world? I've built several contracts in Ethereum and almost always based them on OZ's contracts, they are invaluable. A trusted source of audited building blocks for EOS contracts would help a lot.

**Comment by enriquejr99** [comment]
Have a look at this:
https://github.com/irespo/irespo/tree/master/irespo/irespoicoico

**Comment by dixia** [comment]
irrelevant to development of eos

feel free to find third-party resources for this kind of contract
