### ISSUE TITLE
cleos set contract fail

### ISSUE THREAD

**Issue by liyongpengCtrip** [EOSIO/eos#3532]
The latest version，when i running this command "_cleos set contract eosio build/contracts/eosio.bios_" ,I get a error like this:

[root@COMDEV0628 eos]# cleos set contract eosio build/contracts/eosio.bios
Reading WAST/WASM from build/contracts/eosio.bios/eosio.bios.wasm...
Using already assembled WASM...
Publishing contract...
2808368ms thread-0   main.cpp:2555                 main                 ] Failed with error: Assert Exception (10)
!"unresolvable": env.set_proposed_producers

Before running the command, I have deleted the build directory and run ./eosio_build.sh

**Comment by maxb14** [comment]
`cleos set contract eosio ${eos_path}/contracts/eosio.bios contracts/eosio.bios/eosio.bios.wast ${eos_path}/contracts/eosio.bios/eosio.bios.abi`

**Comment by moskvanaft** [comment]
@liyongpengCtrip it seems like version mismatch between the system contract and nodeos.
set_proposed_producers function was renamed from set_active_producers, your system contract uses set_proposed_producers while nodeos doesn't provide it
try recompiling everything from the same version of source code
