### ISSUE TITLE
Error 3110001: Missing Chain API Plugin

### ISSUE THREAD

**Issue by rainssong** [EOSIO/eos#3535]
when I run 
`
./cleos -u http://localhost:8899 create account eosio myaccount key1 key2
`
I got error :
```
Error 3110001: Missing Chain API Plugin
Ensure that you have eosio::chain_api_plugin added to your node's configuration!
Error Details:
Chain API plugin is not enabled
```

but I already set Chain API Plugin in ~/.local/share/eosio/nodeos/config/config.ini like this:
```
#Lad the testnet genesis state, which creates some initial block producers with the default key
genesis-json = genesis.json
# Enable production on a stale chain, since a single-node test chain is pretty much always stale
enable-stale-production = true
# Enable block production with the testnet producers
producer-name = eosio
# Load the block producer plugin, so you can produce blocks
plugin = eosio::producer_plugin
# Wallet plugin
plugin = eosio::wallet_api_plugin
# As well as API and HTTP plugins
plugin = eosio::chain_api_plugin
plugin = eosio::http_plugin
# This will be used by the validation step below, to view account history
plugin = eosio::history_api_plugin
```

and run nodeos like this:
`./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --resync-blockchain`

Why?

**Comment by maxb14** [comment]
If you use the config file, it's not necessary to write args on command.
Do you have the latest version of eosio ?
In your node config file, make sure that the adress is localhost:8899

**Comment by bluabaleno** [comment]
you do mean the 

# The local IP and port to listen for incoming http connections; set blank to disable. (eosio::http_plugin)
http-server-address = localhost:8899

yeah? 

I'm still getting the same error.

**Comment by ricktobacco** [comment]
Getting the same error as well.

**Comment by kidnuri** [comment]
Are you fix your problem?
I have been same error like you.
"Error 3110001: Missing Chain API Plugin"

**Comment by nikdale** [comment]
Same problem guys. And it's not the **port** (8899). :cry:

**Comment by BharatXBhalla** [comment]
nodeos \
  -e -p eosio \
  --plugin eosio::producer_plugin      \
  --plugin eosio::producer_api_plugin      \
  --plugin eosio::chain_api_plugin         \
  --plugin eosio::http_plugin          \
  --plugin eosio::history_plugin \
  --plugin eosio::history_api_plugin \
  --contracts-console   \
  --access-control-allow-origin='*' \
  --http-validate-host=false        \
  --verbose-http-errors             \
  --filter-on="*"



Try running this cmd on your local
