### ISSUE TITLE
Documentation: dapps shouldn't use serialization APIs

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#3544]
e.g. ```abi_json_to_bin```, ```abi_bin_to_json```

Potential attack:

* App uses serialization APIs to encode a transaction.
* API runs on a malicious server and encodes something different. e.g. send all user's tokens to attacker's account.
* App signs the encoded transaction. Since it doesn't know how to deserialize itself, it doesn't recognize the tampering.

**Comment by halsaphi** [comment]
moved to notion for review
