### ISSUE TITLE
Block log was not setup properly with genesis information.

### ISSUE THREAD

**Issue by Michael2008S** [EOSIO/eos#3545]
I get this error when I run  `./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin `.

```
➜  nodeos git:(master) ./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin
1875208ms thread-0   chain_plugin.cpp:151          plugin_initialize    ] initializing chain plugin
1875209ms thread-0   main.cpp:113                  main                 ] 10 assert_exception: Assert Exception
version > 0: Block log was not setup properly with genesis information.
    {}
    thread-0  block_log.cpp:470 extract_genesis_state
```

In this version:

```
commit 07a6798584d053ed6061bd892879c6c886ba104e
Merge: a609496 3588c5c
Author: Greg Lee <greg.lee@block.one>
Date:   Sun May 27 19:32:19 2018 -0400
```

**Comment by fulanto** [comment]
same here

**Comment by fulanto** [comment]
master is not stable, may be you should try released version

**Comment by fulanto** [comment]
well, I have tried dawn-v4.2.0, however, same error.

**Comment by jhtsing** [comment]
I have the same error.

**Comment by fulanto** [comment]
@wh2000292 Any idea about ubuntu ?

**Comment by maheshnama** [comment]
@wh2000292 Any idea about ubuntu ? In Ubuntu16.04  delete this  folder 
/root/.local/share/eosio/nodeos/data ,start this command it should work 
nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin

**Comment by stanishev** [comment]
clear this folder as in **remove** the data folder altogether. 

rm -rf ~/.local/share/eosio/nodeos/data

**Comment by cs4026** [comment]
Same issue on macOS, solved it by cd-ing into  ~/Library/Application Support/,
and running "rm -rf eosio". 

This deleted everything related to the chain. Running nodeos after this reset my eosio folder with a fresh config.ini. 

I updated the config.ini and ran "nodeos  --delete-all-blocks ", waited for it to clear pressed "ctrl-c" and ran nodeos again and it's working fine now.

**Comment by taokayan** [comment]
Please use the latest version and clean up the old block log and shared mem.

**Comment by andriantolie** [comment]
Yes, just use the latest version. I suspect there's a hardfork change at that time that is incompatible with your previous block log

**Comment by mosjin** [comment]
@stanishev works for me. thanks!

**Comment by vikas-sawant-rwaltz** [comment]
If you are using docker setup then run the nodeos without **--hard-replay-blockchain** at the start. It will work for you.

In my case I was trying docker nodeos setup with **--hard-replay-blockchain**, and when I removed it's start working.
