### ISSUE TITLE
Database Related App

### ISSUE THREAD

**Issue by gateway** [EOSIO/eos#3552]
I have been thinking of using EOS to create a system to collect various data that needs to be queried, I have read somewhere that EOS could be used to store such data and have a some sort of query language.  Is their any documentation o this or examples I could look at.. sorry this isn't an issue but more of a discussion point.  If there are other locations to post these types of questions let me know ..

cheers.

**Comment by pruhstal** [comment]
Look into IPFS 

https://github.com/EOSIO/Documentation/raw/master/EOS.IO%20Storage.pdf

**Comment by dixia** [comment]
hi@gateway please ask this kind of question in https://eosio.stackexchange.com
