### ISSUE TITLE
Core symbol name change does not get implemented

### ISSUE THREAD

**Issue by jchung00** [EOSIO/eos#3553]
Version: dawn-v4.2.0
OS: Ubuntu 18.04
We ran this in the source folder before building.
```console
ex -sc '16i|set( CORE_SYMBOL_NAME "EOS" )' -cx CMakeLists.txt
``` 
Then, we launched the network and then ran the following on the bios node:
```console
./cleos.sh push action eosio.token create '["eosio", "10000000000.0000 EOS"]' -p eosio.token
./cleos.sh push action eosio.token issue '["eosio",  "1000000000.0000 EOS", "init"]' -p eosio
```
However, the following command would cause an `assertion exception: unknown key`:
```console
./cleos.sh set contract eosio $CONTRACTS_FOLDER/eosio.system -x 1000 -p eosio
```
We tried this to see if it would solve the assertion exception:
```console
./cleos.sh push action eosio.token create '["eosio", "10000000000.0000 EOS"]' -p eosio.token
./cleos.sh push action eosio.token issue '["eosio",  "1000000000.0000 EOS", "init"]' -p eosio
./cleos.sh set contract eosio $CONTRACTS_FOLDER/eosio.system -x 1000 -p eosio
```
And the system contract was deployed.
Below is a screenshot of what we tried next, which leads us to believe that the core symbol name change hasn't really been implemented.
<img width="1440" alt="screen shot 2018-05-29 at 4 23 59 pm" src="https://user-images.githubusercontent.com/19266519/40675439-5ecc57ee-63aa-11e8-9939-93fe566ebce3.png">

**Comment by arhag** [comment]
After running that first command to change `SYS` to `EOS` please actually verify that the string has changed in CMakeLists.txt. If it has not, then that command is not working.

It should work if you manually change the "SYS" to "EOS" in CMakeLists.txt.

**Comment by jchung00** [comment]
@arhag Does this mean that we must change every reference to "SYS" in CMakeLists.txt to "EOS"? We did verify that CORE_SYMBOL_NAME ("EOS") was added to the file around line 16
