### ISSUE TITLE
System contract changes and testing

### ISSUE THREAD

**Issue by zorba80** [EOSIO/eos#3557]
- [x] Change by_vote producer_info index in order to avoid long loops in update_elected_producers.
- [x] Added a unit test to verify the effect of setram.
- [x] Added checks to test balances of eosio.ram, eosio.ramfee, eosio.names, eosio.saving, eosio.bpay, and eosio.vpay.
- [x] Cancel producer deactivation, add system contract action to deactivate a producer account.
- [x] Remove global state savings field as it is redundant now. 
- [x] Test eosio.stake account.
- [x] Check that number of producers hasn't decreased before updating producer schedule.

**Comment by arhag** [comment]
Resolved by PR #3559 and PR #3619.
