### ISSUE TITLE
Expired transaction time error

### ISSUE THREAD

**Issue by jchung00** [EOSIO/eos#3558]
Version: dawn-v.4.2.0
We started off by deploying the eosio.bios contract on the eosio account:
```console
./cleos.sh set contract eosio /home/ubuntu/eos/eosio.bios -p eosio
```
This worked without any errors.
Later, we deployed the system contract. We did have some problems with the `unknown key` assertion exception during the process as described in #3553 , but it still got deployed.
We deployed the eosio.bios contract onto the eosio account again, and then the system contract again. This worked running the same commands shown above.
And then we had to change some things again using the eosio.bios contract so we tried to deploy it again, and ran into the error below. This has persisted and we haven't been able to re-deploy the eosio.bios contract.
<img width="1147" alt="screen shot 2018-05-29 at 10 26 51 pm" src="https://user-images.githubusercontent.com/19266519/40675838-6fb7ee28-63ab-11e8-8157-537db5d5fe2d.png">

**Comment by brightermatter** [comment]
same error here, with dawn 4.2

**Comment by jchung00** [comment]
@brightermatter Those plugins were enabled, and producer-name was set to eosio.

**Comment by brightermatter** [comment]
After adding another consumer node, this error started popping up again on our producer node.

**Comment by douxin** [comment]
I have the same issue with 4.2, and these plugins were enabled, and produce name is eosio, not fix my problem

**Comment by moskvanaft** [comment]
Problem is that nodeos is not producing blocks. In this case head block is very old. `cleos` sets expiration time based on  head block time.
So, first make sure that you nodeos is producing blocks. It should be constantly printing something like
```
510005ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 00008ffc77f86047... #36860 @ 2018-06-05T20:08:30.000 signed by eosio [trxs: 0, lib: 36859, confirmed: 0]
510502ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 00008ffd7497ca46... #36861 @ 2018-06-05T20:08:30.500 signed by eosio [trxs: 0, lib: 36860, confirmed: 0]
```
If nodeos is not on your local machine try `cleos get info` and look for 
```
...
"head_block_time": "2018-06-05T20:10:52",
...
```
It should be very recent (not more than few seconds off from current time). And should be different each time you re-run `cleos get info`.

How to make your local nodeos to produce blocks when you start new blockchain (just an example, you may use different parameters):
```
nodeos  --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::producer_plugin --plugin eosio::history_api_plugin --contracts-console --delete-all-blocks --genesis-timestamp now -e
```
If you want to continure existing (valid!) chain - remove `--delete-all-blocks --genesis-timestamp now`

@jchung00 feel free to re-open if it didn't help

**Comment by trungtt1981** [comment]
@moskvanaft 
Please refer to my posted issue: 
I've also checked the `head_block_time` as you recommended. Although the `head_block_time` of my local nodeos is updated frequently, but I still encounter this kind of error.
Please help.
