### ISSUE TITLE
./cleos get currency balance eosio.token exchange1 EOS 

### ISSUE THREAD

**Issue by thinkSharp** [EOSIO/eos#3571]
could someone explain how to convert get balance into REST API Call?

http://137.117.56.253:8888/v1/chain/get_currency_balance
post request with {"contract":"eosio", "account": "exchange", "symbol":"EOS"}

I am getting following error message
{
    "code": 500,
    "message": "Internal Service Error",
    "error": {
        "code": 3060002,
        "name": "account_query_exception",
        "what": "Account Query Exception",
        "details": [
            {
                "message": "Fail to retrieve account for ",
                "file": "chain_plugin.cpp",
                "line_number": 462,
                "method": "get_abi"
            }
        ]
    }
}

**Comment by moskvanaft** [comment]
@thinkSharp your request should look like
```
{"account":"exchange","code":"eosio.token","symbol":"EOS"}
```
In the future release `cleos` will support `--print-request`, so you will be able to see what request is it doing ( #3849)

I am closing the ticket. Feel free to reopen if you still have the problem.
