### ISSUE TITLE
get keys by rest api error

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#3577]
With http_server_address 8888, it only return the first key pair.  sam@sam-machine:/media/sam/work/fork/Eoasis$ curl http://localhost:8888/v1/wallet/list_keys
[["EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"]]

sam@sam-machine:/media/sam/work/fork/Eoasis$ curl http://localhost:8900/v1/wallet/list_keys
[["EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"],["EOS6qnCLMm5d67JdP11EF31Kf4UUNr6ktUKBqPsDhSXADT1CHfNG2","5KZ2ytRsGMxRAycpFqFnkRF8mNfZTomQKnaXzh1FtbRPgbaTAF3"],["EOS6vizDzpZMxtt27WVVCUVYEFHXgaLhEfPuLQAXfpAJaf2oWAcwg","5JKesiwGnAWW6G4VVtobNbY1HCEBZeHeXRn6Dt3JC2ySn9MGib5"],["EOS7KKga2itCjyLAm6n4GHqujN4arBv3GQEWpZwQqSDWyNEj7iuxQ","5J4uBPibqwPppvdJKMWCdk1nKYgytxHpMckAzBzBtiNWYK4Y1Kb"]]

dawn-v4.2.0

**Comment by heifner** [comment]
You have two wallets running. One on 8888 and one on 8900. The one on 8888 has one key pair. The one on 8900 has 4 key pairs.

**Comment by sergmetelin** [comment]
Should the Private keys EVER be exposed via an RPC API?
