### ISSUE TITLE
cleos get table -k para is not effect ?? -L -U can effect.

### ISSUE THREAD

**Issue by healthwallet** [EOSIO/eos#3580]
eos version dawn-v4.2.0

➜  liondb git:(master) ✗ cleos get table liontable liontable accounteos -k 1
{
  "rows": [{
      "ID": 1,
      "loginID": "fsf",
      "loginName": "",
      "eosAcc": "",
      "memberType": 5,
      "cdate": 1527588850,
      "mdate": 1527588850
    },{
      "ID": 10,
      "loginID": "ac1",
      "loginName": "ac2",
      "eosAcc": "ac3",
      "memberType": 4,
      "cdate": 1527589190,
      "mdate": 1527589190
    }
  ],
  "more": false
}
➜  liondb git:(master) ✗ cleos get table liontable liontable accounteos -L1 -U2
{
  "rows": [{
      "ID": 1,
      "loginID": "fsf",
      "loginName": "",
      "eosAcc": "",
      "memberType": 5,
      "cdate": 1527588850,
      "mdate": 1527588850
    }
  ],
  "more": false
}

**Comment by andriantolie** [comment]
-k is deprecated for `cleos get table`, use `--index` and `--key-type` instead
