### ISSUE TITLE
can't figure out the relation between a producer and a node

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#3582]
I am confused even after I finish reading the tutorial. Therefore, I want to make sure the answer to the following questions.
(1) how many producers can one nodeos control?
(2) is nodeos the producer itself? 21 nodeos are chosed to produce blocks? Then what is purpose of -p argument of nodeos?
(3) can a nodeos control producers (users) created from other nodeos?

**Comment by jgiszczak** [comment]
A single node can be an arbitrary number of producers, including more than 21.
Nodeos is therefore not identified as "the" producer.  It is "some" producers, depending on how many are configured.  The `-p` argument informs a nodeos instance which producer(s) it is.
A nodeos instance can produce as a user that was created on other nodes, as long as it is synchronized to that chain, and is configured with `-p` or the equivalent `config.ini` setting, and frequently does so in testing scenarios.
A healthy mainnet is not expected to have multiple producers on the same nodeos instance.  On the contrary, there are efforts to support failover, so ultimately a healthy mainnet can expect to run 42 or more nodeos instances for 21 producers.
