### ISSUE TITLE
4.2.0 i can't get  actions

### ISSUE THREAD

**Issue by XieWeiZM** [EOSIO/eos#3583]
[btb@wallet-3 cleos]$ ./cleos transfer user tester "10 EOS" "a32"
executed transaction: 48e9df29d2f3132bac2b054e54322938e22f2bb5d650b35c1bdeaf1636ed8bb5  128 bytes  995 us
#   eosio.token <= eosio.token::transfer        {"from":"user","to":"tester","quantity":"10.0000 EOS","memo":"a32"}
#          user <= eosio.token::transfer        {"from":"user","to":"tester","quantity":"10.0000 EOS","memo":"a32"}
#        tester <= eosio.token::transfer        {"from":"user","to":"tester","quantity":"10.0000 EOS","memo":"a32"}
warning: transaction executed locally, but may not be confirmed by the network yet
[btb@wallet-3 cleos]$
[btb@wallet-3 cleos]$
[btb@wallet-3 cleos]$ ./cleos get actions user
#  seq  when                              contract::action => receiver      trx id...   args
================================================================================================================
[btb@wallet-3 cleos]$

**Comment by sss-CRS-sss** [comment]
Now, by default, a filter is for actions, this is necessary to save RAM BP. To see the actions, you need to restart the node with the -f option.
```
 -f [ --filter-on ] arg                Track actions which match
                                        receiver:action:actor. Actor may be
                                        blank to include all. Receiver and
                                        Action may not be blank
```

For example:
```./nodeos --plugin eosio::chain_api_plugin --producer-name eosio --config-dir c --data-dir d --delete -e --plugin eosio::history_api_plugin --filter-on "*"
```

**Comment by mlawand** [comment]
i have the same issue, even with the filter its not working i am getting the same error message

> warning: transaction executed locally, but may not be confirmed by the network yet

**Comment by spartucus** [comment]
> warning: transaction executed locally, but may not be confirmed by the network yet

@mlawand , this means success.

**Comment by mlawand** [comment]
@spartucus i am not getting any response when i push an action through cleos

**Comment by spartucus** [comment]
The response how to perform after an action is in your contract. In a some situations, there're no output prints.

**Comment by mlawand** [comment]
@spartucus i have included in my contract the print functionality to see an output, is there should always be an output. but it is not showing

**Comment by spartucus** [comment]
Hi @mlawand , you can start nodeos with the `--contracts-console` option to cause printed debug output to be sent to the console.

**Comment by taokayan** [comment]
Is this issue solved?
