### ISSUE TITLE
STD Exception encountered while processing chain.get_code: unknown key

### ISSUE THREAD

**Issue by lingyiliu016** [EOSIO/eos#3588]
when I run `node pingPong.js `, error occured! details are as followed!
api error => { message: 'unknown key',
  file: 'http_plugin.cpp',
  line_number: 371,
  method: 'handle_exception' } http://127.0.0.1:8888/v1/chain/get_code {"account_name":"child.acnt"}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"unknown key","file":"http_plugin.cpp","line_number":371,"method":"handle_exception"}]}}
    at /Users/changlingyi/node_modules/eosjs/node_modules/eosjs-api/lib/apigen.js:115:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) status: 500, statusText: 'Internal Server Error' }
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"unknown key","file":"http_plugin.cpp","line_number":371,"method":"handle_exception"}]}}
    at /Users/changlingyi/node_modules/eosjs/node_modules/eosjs-api/lib/apigen.js:115:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) status: 500, statusText: 'Internal Server Error' }
(node:80202) UnhandledPromiseRejectionWarning: Error: {"code":500,"message":"Internal Service Error","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"unknown key","file":"http_plugin.cpp","line_number":371,"method":"handle_exception"}]}}
    at /Users/changlingyi/node_modules/eosjs/node_modules/eosjs-api/lib/apigen.js:115:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:80202) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:80202) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
nodeos show `STD Exception encountered while processing chain.get_code: unknown key` in red color. 
Here is content of pingPong.js
let EOS = require('eosjs')

eos = EOS.Localnet({
        keyProvider:['5KQVzEFg4PbDNtCbdhbfgwfaqQYPNzhjna3ZCm5AzrFZCpeoccg','5KcHE3HF4zAecKWFxBiizG3KBPpkBxbbMDAn1HPeHQZecy69bZy'],
        httpEndpoint:'http://127.0.0.1:8888'
})

eos.contract('child.acnt').then((contract) => {
        contract.ping("child.acnt",{authorization:['child.acnt']}).then((res) => {
                console.log(res)
        })
})
I think the problem may be in keyProvider.but '5KQVzEFg4PbDNtCbdhbfgwfaqQYPNzhjna3ZCm5AzrFZCpeoccg','5KcHE3HF4zAecKWFxBiizG3KBPpkBxbbMDAn1HPeHQZecy69bZy' is owner_private_key and active_private_key of child.acnt.

**Comment by vicraft18** [comment]
i'm stuck with the same issue

**Comment by lingyiliu016** [comment]
edit ~/Library/Application Support/eosio/nodeos/config/config.ini，
cancel comment and add
# Specify the Access-Control-Allow-Origin to be returned on each request. (eosio::http_plugin)
 access-control-allow-origin = * 

# Specify the Access-Control-Allow-Headers to be returned on each request. (eosio::http_plugin)
 access-control-allow-headers = * 
，error may be different

**Comment by lingyiliu016** [comment]
edit ~/Library/Application Support/eosio/nodeos/config/config.ini，
cancel comment and add
`
Specify the Access-Control-Allow-Origin to be returned on each request. (eosio::http_plugin)

access-control-allow-origin = *

Specify the Access-Control-Allow-Headers to be returned on each request. (eosio::http_plugin)

access-control-allow-headers = *
`
，error may be different

**Comment by cipherzzz** [comment]
I'm stuck with this as well...

**Comment by taokayan** [comment]
Can you provide the detail steps to reproduce this issue. Normally "unknown key" is because the account is not found.

**Comment by hernanarber** [comment]
Hi:

Why is this Closed? I'm stuck with the Same Issue, tried doing what @lingyiliu016 says here: https://github.com/EOSIO/eos/issues/3588#issuecomment-393084126

But NO RESULT...

Can Anyone help me out?

**Comment by koeltp** [comment]
me too
