### ISSUE TITLE
3050003 error,attempt to add asset with different symbol

### ISSUE THREAD

**Issue by yekai1003** [EOSIO/eos#3590]
``` sh
ykdeMac-mini:eos yekai$ cleos push action dice deposit '[ "bob", "100.0000 EOS" ]' -p bob
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: attempt to add asset with different symbol
```

**Comment by maxb14** [comment]
`cleos push action dice deposit '[ "bob", "100.0000 SYS" ]' -p bob`

**Comment by yekai1003** [comment]
@maxb14 
why？What does "sys" stand for?

**Comment by maxb14** [comment]
https://cryptoslate.com/eosio-dawn-4-1-release-changes-core-token-name-from-eos-to-sys/

"In order to create this token we required the permission of the eosio.token contract because it "owns" the symbol namespace (e.g. "SYS"). Future versions of this contract may allow other parties to buy symbol names automatically. For this reason we must pass -p eosio.token to authorize this call."

**Comment by yekai1003** [comment]
@maxb14 thanks,by the way,what "eosio.code" stand for?

**Comment by maxb14** [comment]
eosio.code is a virtual permission

**Comment by yekai1003** [comment]
@maxb14 
Can not use function print()  for debug now?

**Comment by yekai1003** [comment]
``` cpp
 //@abi action
      void deposit( const account_name from, const asset& quantity ) {
         
         eosio_assert( quantity.is_valid(), "invalid quantity" );
         eosio_assert( quantity.amount > 0, "must deposit positive quantity" );
        print("deposit....");
         auto itr = accounts.find(from);
         if( itr == accounts.end() ) {
            itr = accounts.emplace(_self, [&](auto& acnt){
                //eosio_assert(itr->eos_balance.is_valid(),"invalid ")
                acnt.eos_balance = quantity;
                acnt.owner = from;
            });
         } 
         else {
            accounts.modify( itr, 0, [&]( auto& acnt ) {
                acnt.eos_balance += quantity;
            });
         }
         action(
            permission_level{ from, N(active) },
            N(eosio.token), N(transfer),
            std::make_tuple(from, _self, quantity, std::string(""))
         ).send();

         
      }
```
Maybe this code is right？

**Comment by moskvanaft** [comment]
@yekai1003 `print` is defined in namespace `eosio` (file contracts/eosiolib/print.hpp). Use `eosio::print(...)` or add `using namespace eosio;` before you call print.

`SYS` is a default name for system token. You can change it when you compile eos. On the mainnet it supposedly will be `EOS`.

**Comment by yekai1003** [comment]
If need to use print(),need to add params when start the nodeos.
