### ISSUE TITLE
P2P Network Question

### ISSUE THREAD

**Issue by alexwishes** [EOSIO/eos#3591]
What kind of P2P Network does EOS use?
I cannot find any information about this topic everywhere, please help~

**Comment by jgiszczak** [comment]
EOS.IO uses two different bespoke network protocols between full nodes, `net_plugin` and `bnet_plugin`.  These plugins may be used simultaneously, but can not be interconnected.  `net_plugin` messages are in `plugin/net_plugin/include/eosio/net_plugin/protocol.h`.  `bnet_plugin` messages are embedded in the source file, `bnet_plugin/bnet_plugin.cpp`.

**Comment by alexwishes** [comment]
Thanks @jgiszczak , it helps a lot
