### ISSUE TITLE
BNet strand error handling

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#3597]
We have several entry points in the `bnet_plugin` which have this construct:

https://github.com/EOSIO/eos/pull/3595/files/d3a77774a46547abf1cb231f1c0a8639a0cfcc05#diff-fba600af4c654e900ff8766887744c43R1084

While an error log is "nice" it seems to imply that this is inherently unsafe; if this message is in the log you have made concurrent access/modifications to some sort of state and the process is potentially in a bad state.  

We should address these errors in a different way so that this is either removable dead code (provably never happens), this is a halt-and-catch fire immediately, OR there is a "slow path" which produces safe behavior in the unlikely event that this would be triggered.

**Comment by heifner** [comment]
See discussion : https://github.com/EOSIO/eos/pull/3595#discussion_r191796370
