### ISSUE TITLE
BOOST_THROW_EXCEPTION

### ISSUE THREAD

**Issue by asvirido** [EOSIO/eos#360]
# The eosd run errors and exists. This is the output. MAC OS/Linux Ubuntu
```

3014624ms thread-0   main.cpp:35 main]
Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::multiple_occurrences> >
std::exception::what: option 'enable-stale-production' cannot be specified more than once

```

**Comment by vrudakov** [comment]
![image](https://user-images.githubusercontent.com/21339799/30127144-d98a4e6c-9346-11e7-9568-a8c9cf3e7e2c.png)
Have the same on macOS

**Comment by nanonano7** [comment]
I recreated the error by specifying `enable-stale-production = true` twice in the config.ini.
Try to check for duplicate entries.

**Comment by asvirido** [comment]
I had two lines

```
enable-stale-production = false
enable-stale-production = true
```
I delete first line and all ok

**Comment by asvirido** [comment]
чт, 7 сент. 2017 г. в 00:10, nanonano7 <notifications@github.com>:
