### ISSUE TITLE
sign_transaction error with curl 

### ISSUE THREAD

**Issue by thinkSharp** [EOSIO/eos#3601]
[{"ref_block_num":"180970","ref_block_prefix":"1613010314","expiration":"2018-05-30T14:22:22","scope":["exchange","user"],"read_scope":[],"messages":[{"code":"eosio.token","type":"transfer","authorization":[{"account":"exchange","permission":"active"}],"data":"0000008a4dd3505700000000007015d6a08601000000000004454f5300000000046d656d6f"}],"signatures":[]}, ["EOS6a8cdMF85ehutarLLYuC9rpTXtymZxQY35Qvh5qd9v38zewfZC"], ""]

{
    "code": 500,
    "message": "Internal Service Error",
    "error": {
        "code": 7,
        "name": "bad_cast_exception",
        "what": "Bad Cast",
        "details": [
            {
                "message": "Invalid cast from type 'string_type' to Object",
                "file": "variant.cpp",
                "line_number": 573,
                "method": "get_object"
            }
        ]
    }
}

**Comment by thinkSharp** [comment]
could someone please help?

**Comment by thinkSharp** [comment]
what am i doing wrong?

**Comment by taokayan** [comment]
Can you provide your commands and steps to reproduce this issue?

**Comment by andriantolie** [comment]
It's very likely that your action data doesn't match the abi

**Comment by minami-choi** [comment]
const object  =[{"ref_block_num":"180970","ref_block_prefix":"1613010314","expiration":"2018-05-30T14:22:22","scope":["exchange","user"],"read_scope":[],"messages":[{"code":"eosio.token","type":"transfer","authorization":[{"account":"exchange","permission":"active"}],"data":"0000008a4dd3505700000000007015d6a08601000000000004454f5300000000046d656d6f"}],"signatures":[]}, ["EOS6a8cdMF85ehutarLLYuC9rpTXtymZxQY35Qvh5qd9v38zewfZC"], ""]

I think you should do "JSON.stringfy(object)" 
The error message is "Invalid cast from type 'string_type' to Object"

**Comment by andriantolie** [comment]
We haven't got any reply from you since July. 

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issue is intended to be a place for bugs reporting and features track, and Stack Exchange will be the place for any technical support discussion. Thanks!
