### ISSUE TITLE
Verify bnet handles unusual Boost conditions

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#3612]
Unusual Boost conditions which crashed net_plugin:

* https://github.com/EOSIO/eos/commit/75bd470db1b6a844c60a6a3793b12c58d8ea7fbd
  * remote_endpoint() failed on a socket ("invalid endpoint"), even though is_open() returned true
* https://github.com/EOSIO/eos/commit/d327ed6461e08356008bd17fe9fcd0b450f39540
  * In async_connect callback, err was clear, but socket->set_option threw "Bad file descriptor"

**Comment by heifner** [comment]
I could not find that these two boost unusual conditions would cause any problems in bnet.
