### ISSUE TITLE
"Underlying Transport Error"

### ISSUE THREAD

**Issue by HassanAmad** [EOSIO/eos#3634]
I cloned the git repo onto a local machine. Followed the documentation instructions, but accidentally ran nodeos without the plugins, and realized my mistake so i shut the terminal session by simply closing the terminal window in Mac. When i went to go and try again, i tried adding the plugin options to nodeos like the documentation said, and it told me that some corruption flag was set. Not knowing what to do, i started to run nodeos with the delete-blocks flag, replay, hard-replay, etc. Nothing would work and i simply just got this message in return:
 

Message:

851416ms thread-0   chain_plugin.cpp:200          plugin_initialize    ] initializing chain plugin
851417ms thread-0   block_log.cpp:123             open                 ] Log is nonempty
851417ms thread-0   block_log.cpp:136             open                 ] my->head->block_num(): 1 
851417ms thread-0   block_log.cpp:142             open                 ] Index is nonempty
851440ms thread-0   http_plugin.cpp:285           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
851440ms thread-0   net_plugin.cpp:2814           plugin_initialize    ] Initialize net plugin
851440ms thread-0   net_plugin.cpp:2835           plugin_initialize    ] host: 0.0.0.0 port: 9876 
851440ms thread-0   net_plugin.cpp:2907           plugin_initialize    ] my node_id is 8599f31bdd2950039a3be93299ce1c8b2e6f5e299b65dfb5127332ff4d616824
851440ms thread-0   main.cpp:104                  main                 ] nodeos version ca03c3a7
851440ms thread-0   main.cpp:105                  main                 ] eosio root is /Users/hassan/Library/Application Support
851441ms thread-0   chain_plugin.cpp:406          plugin_startup       ] starting chain in read/write mode
851441ms thread-0   chain_plugin.cpp:411          plugin_startup       ] Blockchain started; head block is #1, genesis timestamp is 2018-03-02T12:00:00.000
851441ms thread-0   http_plugin.cpp:323           plugin_startup       ] start listening for http requests
851441ms thread-0   http_plugin.cpp:330           plugin_startup       ] http service failed to start: Underlying Transport Error
851441ms thread-0   fork_database.cpp:95          close                ] num_blocks_in_fork_db: 1 
851442ms thread-0   controller.cpp:261            ~controller_impl     ] db.revision(): 1 head->block_num: 1 blog.read_head()->block_num(): 1 
851446ms thread-0   main.cpp:133                  main                 ] Underlying Transport Error

Finally i gave up on that repo, and just checked out a fresh clone in a new repo, and followed the instructions verbatum this time, and I still got the "Underlying Transport Error" above.

**Comment by HassanAmad** [comment]
I did a build prior to this in a different repository on my machine, and i made a mistake of running nodeos without the plugins, and then I tried Ctrl-C'ng but it would not work so i simply shut the terminal session. When i went back to try again with the plugins, it gave me the same message.

The message you saw above was due to me completely deleting the corrupted repository, and remaking it, cloning the master from github, and trying the process again. The message above is where i followed the documentation instructions, but I got the same message as the first time i did it (where i actually made the mistake)

**Comment by lingyiliu016** [comment]
Same error occured When I set up eosio@dawn4.2

**Comment by lingyiliu016** [comment]
The error details are as follows:

<img width="986" alt="20180601113436" src="https://user-images.githubusercontent.com/27277897/40819922-24ecde6c-6590-11e8-95e2-ebc1324cccd1.png">
The reason of the error occured is that the command `make test` is running and not finished ,and I run  `./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin` at same time.
when I kill the `make test` , I run `./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin`  again, the  error disappear!

**Comment by heifner** [comment]
Transport error normally means the port is already taken.

**Comment by v-ken** [comment]
@heifner I've followed the instructions in the documentation (using Docker) and also get this error. Are you not going to help your developer community resolve issues besides just stating the cause of the issue?
