### ISSUE TITLE
Docker giving me a hard time with nodeos

### ISSUE THREAD

**Issue by HassanAmad** [EOSIO/eos#3637]
Docker nodeos crashed on me when i ran it the first time on a fresh git clone of master. I exited my bash session because it froze, now i go to run again, and it says:

eos hassan$ docker run --name nodeos -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh arg1 arg2

docker: Error response from daemon: Conflict. The container name "/nodeos" is already in use by container "b17d590d3844b4dfcd9e7caeed6dbe20ef84678b030b35ae01d6382333737d82". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

As you can see below there is no docker machines that seem to be running. So what is the deal?

eos hassan$ docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS

**Comment by ripley** [comment]
You once created a nodeos container.

'docker container ls -la' to find it, 'docker container rm xxx' to remove than rerun.

**Comment by HassanAmad** [comment]
When i restart the docker nodeos it gives me this error:

943002ms thread-0   producer_plugin.cpp:689       start_block          ] Not producing block because the irreversible block is too old [age:7755343s, max:1800s]

**Comment by ripley** [comment]
Never hit the issue myself, but someone did on telegram, he solved it by.

docker run —name nodeos -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh —max-irreversible-block-age 9999999

You can search in telegram, more help there. Actually I was a bit wondering why "Issues" of EOS is used as a  forum.

**Comment by harrywong** [comment]
You got this issue because the default genesis timestamp is too old, and latest updates have added some codes to check the age of irreversible.
You can also simply add this option: --genesis-timestamp=now to make the timestamp of genesis node to the time of now.

**Comment by HassanAmad** [comment]
Someone might want to put that in the documentation for newbies

**Comment by halsaphi** [comment]
Documentation request noted, closing issue.
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
