### ISSUE TITLE
 FC Exception encountered while processing chain.push_transaction:

### ISSUE THREAD

**Issue by lingyiliu016** [EOSIO/eos#3647]
here is my smart contract file: ping.cpp
<img width="433" alt="wx20180531-141958 2x" src="https://user-images.githubusercontent.com/27277897/40765078-c9ddecee-64dd-11e8-8b73-15f4579380e0.png">
here is my eosjs script pingpong.js
<img width="907" alt="wx20180531-142247 2x" src="https://user-images.githubusercontent.com/27277897/40765167-227d20cc-64de-11e8-97e5-b2a9d4d7024f.png">
when I run commend `node pingpong.js`
here is the process nodeos show information:
<img width="990" alt="wx20180531-142504 2x" src="https://user-images.githubusercontent.com/27277897/40765253-74ad509c-64de-11e8-85e4-e4dbbd1ec950.png">
here is the error 
<img width="983" alt="wx20180531-142630 2x" src="https://user-images.githubusercontent.com/27277897/40765334-ad9f57b0-64de-11e8-914e-e5ac9dfb3a36.png">
how should I do?

**Comment by FortisFortuna** [comment]
I get this error as well

**Comment by moskvanaft** [comment]
@lingyiliu016 , it seems like your JS code declares authorization of user 'child.acnt' but doesn't sign the transaction with the users' private key.
Since your contract doesn't require authorization (eosiolib function `require_auth`) you don't need to provide authorization.

**Comment by jcalfee** [comment]
This can happen if the chainId does not match.  There is a warning in the next eosjs release.  Provide the `cleos get info` chain_id here Eos.Localhost({chainId: 'hex'}) ..
