### ISSUE TITLE
eosc benchmark command does not output performance metrics.

### ISSUE THREAD

**Issue by pavybez** [EOSIO/eos#365]
I tried to run ./eosc benchmark setup 1000 and ./eosc benchmark transfer 10 10 but it only prints a statement that it has either setup accounts or done the random transfers. There is no information on the performance benchmark metrics. e.g. time taken.

**Comment by pavybez** [comment]
We need to show
 1. how many transactions are included in a block
 2. average latency until being included in a block
 3. how quickly can the block be applied
 4. TPS - transactions per second

**Comment by heifner** [comment]
benchmark is no longer a command of cleos
