### ISSUE TITLE
>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.

### ISSUE THREAD

**Issue by prayagk** [EOSIO/eos#3651]
./eosio_build.sh

	Beginning build version: 1.2
	Thu May 31 08:12:48 UTC 2018
	User: cybrosys
	git head id: d9df25ac1ad50ad4fd4880e70841863db31d9172
	Current branch: master

	ARCHITECTURE: Linux

	OS name: Ubuntu
	OS Version: 16.04
	CPU speed: 2534.338Mhz
	CPU cores: 2
	Physical Memory: 7856 Mgb
	Disk install: /dev/sda1
	Disk space total: 142G
	Disk space available: 64G

	Checking for installed dependencies.

	Package clang-4.0 found.
	Package lldb-4.0 found.
	Package libclang-4.0-dev found.
	Package cmake found.
	Package make found.
	Package automake found.
	Package libbz2-dev found.
	Package libssl-dev found.
	Package libgmp3-dev found.
	Package autotools-dev found.
	Package build-essential found.
	Package libicu-dev found.
	Package python2.7-dev found.
	Package python3-dev found.
	Package autoconf found.
	Package libtool found.
	Package curl found.
	Package zlib1g-dev found.
	Package doxygen found.
	Package graphviz found.

	No required dpkg dependencies to install.

	Checking boost library installation.
	Boost 1.67.0 found at /home/cybrosys/opt/boost_1_67_0.

	Checking MongoDB installation.
	MongoDB configuration found at /home/cybrosys/opt/mongodb/mongod.conf.

	Checking MongoDB C++ driver installation.
	Mongo C++ driver found at /usr/local/lib/libmongocxx-static.a.

	Checking secp256k1-zkp installation.
	secp256k1 found @ /usr/local/lib.

	Checking for LLVM with WASM support.
	WASM found at /home/cybrosys/opt/wasm/bin.

>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOSIO

>>>>>>>> CMAKE_BUILD_TYPE=Release
>>>>>>>> ENABLE_COVERAGE_TESTING=false
>>>>>>>> DOXYGEN=false

-- The CXX compiler identification is Clang 4.0.0
-- Check for working CXX compiler: /usr/bin/clang++-4.0
-- Check for working CXX compiler: /usr/bin/clang++-4.0 -- broken
CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCXXCompiler.cmake:54 (message):
  The C++ compiler "/usr/bin/clang++-4.0" is not able to compile a simple
  test program.

  It fails with the following output:

   Change Dir: /home/cybrosys/project/eos/eos/build/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_a0a89/fast"

  /usr/bin/make -f CMakeFiles/cmTC_a0a89.dir/build.make
  CMakeFiles/cmTC_a0a89.dir/build

  make[1]: Entering directory
  '/home/cybrosys/project/eos/eos/build/CMakeFiles/CMakeTmp'

  Building CXX object CMakeFiles/cmTC_a0a89.dir/testCXXCompiler.cxx.o

  /usr/bin/clang++-4.0 -o CMakeFiles/cmTC_a0a89.dir/testCXXCompiler.cxx.o -c
  /home/cybrosys/project/eos/eos/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx

  Linking CXX executable cmTC_a0a89

  /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a0a89.dir/link.txt
  --verbose=1

  /usr/bin/clang++-4.0 CMakeFiles/cmTC_a0a89.dir/testCXXCompiler.cxx.o -o
  cmTC_a0a89

  /usr/bin/ld: cannot find -lstdc++

  clang: error: linker command failed with exit code 1 (use -v to see
  invocation)

  CMakeFiles/cmTC_a0a89.dir/build.make:97: recipe for target 'cmTC_a0a89'
  failed

  make[1]: *** [cmTC_a0a89] Error 1

  make[1]: Leaving directory
  '/home/cybrosys/project/eos/eos/build/CMakeFiles/CMakeTmp'

  Makefile:126: recipe for target 'cmTC_a0a89/fast' failed

  make: *** [cmTC_a0a89/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

-- Configuring incomplete, errors occurred!
See also "/home/cybrosys/project/eos/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/cybrosys/project/eos/eos/build/CMakeFiles/CMakeError.log".

	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.

**Comment by pacificcode** [comment]
@prayagk can you run the following commands and paste the output here?
llvm-config-4.0 --has-rtti --version

**Comment by prayagk** [comment]
$ llvm-config-4.0 --has-rtti --version
YES
4.0.0

**Comment by pacificcode** [comment]
@prayagk its looks as though your installation of llvm/clang is not functioning as expected.i.e.
-- Check for working CXX compiler: /usr/bin/clang++-4.0 -- broken

 I would recommend removing clang and running the eosio_build.sh script again.

sudo apt-get purge clang-4.0
cd /path/to/eos
rm -rf build/
git checkout master
git pull
git submodule update --init --recursive
./eosio_build.sh

**Comment by prayagk** [comment]
@pacificcode  thank you. But this returns another error

dpkg: error processing package firefox (--configure):
 subprocess installed post-installation script returned error exit status 2
Setting up php7.0-cli (7.0.30-0ubuntu0.16.04.1) ...
No apport report written because MaxReports is reached already
                                                              update-alternatives: error: cannot stat file '/usr/bin/nodejs': Too many levels of symbolic links
dpkg: error processing package php7.0-cli (--configure):
 subprocess installed post-installation script returned error exit status 2
dpkg: dependency problems prevent configuration of libapache2-mod-php7.0:
 libapache2-mod-php7.0 depends on php7.0-cli; however:
  Package php7.0-cli is not configured yet.

dpkg: error processing package libapache2-mod-php7.0 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of php7.0:
 php7.0 depends on php7.0-fpm | libapache2-mod-php7.0 | php7.0-cgi; however:
  Package php7.0-fpm is not installed.
  Package libapache2-mod-php7.0 is not configured yet.
  Package php7.0-cgi is not installed.

dpkg: error processing package php7.0 (--configure):
 dependency problems - leaving unconfigured
Setting up clang-4.0 (1:4.0-1ubuntu1~16.04.2) ...
No apport report written because MaxReports is reached already
                                                              No apport report written because MaxReports is reached already
                                            No apport report written because MaxReports is reached already
                          Errors were encountered while processing:
 chromium-browser
 chromium-browser-l10n
 google-chrome-stable
 procps
 apport-gtk
 firefox
 php7.0-cli
 libapache2-mod-php7.0
 php7.0
E: Sub-process /usr/bin/dpkg returned an error code (1)

	DPKG dependency failed.

	Exiting now.

**Comment by pacificcode** [comment]
@prayagk Compiling EOSIO does not install any of packages reported in the errors you pasted above.
You may want to update your package manager prior to running the eosio_build.sh script.

**Comment by rvrichards** [comment]
clang-4.0 is required?? - this is the output from the eosio_build.sh script:
The following dependencies are required to install EOSIO.

	1. clang-4.0

**Comment by taokayan** [comment]
Can you try the latest source code?

**Comment by yikongzi** [comment]
I met the same error！

I find that the origin error caused by this line.
/usr/bin/clang-6.0  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_c8a30.dir/CheckFunctionExists.c.o  -o cmTC_c8a30 -lpthreads

Error is caused by this option: "-lpthreads"
The correct option should be:  "-lpthread"

But how to change the building scripts, and it generate correct command option "-lpthread"?  
I don't know.

**Comment by soseazi** [comment]
I fixed the above error:
make: *** [cmTC_a0a89/fast] Error 2

Solution for Ubuntu 16.04:
sudo apt-get install g++-5-multilib
sudo apt-get install libstdc++-8-dev

Problem:
Since I looked up the /eos/build/CMakeFiles/CMakeError.log, I could find out that while progressing CMake, it could not find lstdc++.
The above library provides the lstdc++ which solves the problem.

Please look up the error.log for your own problems. If it is not the same case, it won't  be the solution.

Thx

**Comment by rvrichards** [comment]
I'm on Mint 18, and get:
`E: Couldn't find any package by regex 'libstdc++-8-dev'`
