### ISSUE TITLE
dawn 4.2 RPC push_transaction error 3090003 unsatisfied_authorization

### ISSUE THREAD

**Issue by aiguo186** [EOSIO/eos#3652]
$ curl http://193.93.219.219:8888/v1/chain/push_transaction -X POST -d '{"compression":"none","signatures":["SIG_K1_JvmFjDnqLYXFGfiJc3CFsPVzjBdSL3o18sLZrmXx3fPCPJu3Lb9xW7jbehzd6jmXPWWZZ7vmNjN54kRiEJ4dF4rcw1W434"],"transaction":{"actions":[{"account":"unlimited111","authorization":[{"actor":"unlimited111","permission":"active"}],"data":"1042482a3be9e2d450c8482a3be9e2d4010000000000000000454f53000000000e676f20676f20676f20676f20676f","name":"transfer"}],"context_free_actions":[],"delay_sec":0,"expiration":"2018-05-31T08:50:21.000","max_kcpu_usage":0,"max_net_usage_words":0,"ref_block_num":63365,"ref_block_prefix":1967498922,"region":0}}'
----------
{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"unlimited111\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
-------

many people have this problem,how to solve it?

**Comment by vivekmarakana** [comment]
+1

**Comment by wchh** [comment]
may be signatures error, sign tx must with chain_id of get_info

**Comment by cppfuns** [comment]
I have had the same problem +1

**Comment by TAiS46** [comment]
+1

**Comment by vivekmarakana** [comment]
Putting the chain id while signing the transaction fixes this issue. 

You can get chain id from /v1/chain/get_info where you get `ref_block_num` and `ref_block_prefix`

`curl http://localhost:8888/v1/wallet/sign_transaction -X POST -d '[{"ref_block_num":21453,"ref_block_prefix":3165644999,"expiration":"2017-12-08T10:28:49","scope":["initb","initc"],"read_scope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"initb","permission":"active"}],"data":"000000008093dd74000000000094dd74e803000000000000"}],"signatures":[]}, ["EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"], "<INSERT_CHAIN_ID_HERE>"]'`

**Comment by cppfuns** [comment]
![image](https://user-images.githubusercontent.com/7980920/40817563-b2d659ac-6585-11e8-8b00-1802333de609.png)

`sendPing() {
    this.setState({ pingStatus: 'loading' })
    let eosClient = EOS.Localnet(EOS_CONFIG.clientConfig)
    
    eosClient.contract(EOS_CONFIG.contractName)
      .then((contract) => {
		console.log(EOS_CONFIG.contractName + '合约加载成功！')
        contract.hi(EOS_CONFIG.contractReceiver, { authorization: [EOS_CONFIG.contractReceiver] })
          .then((res) => { this.setState({ pingStatus: 'success' }) })
          .catch((err) => { this.setState({ pingStatus: 'fail' }); console.log(err) })
      })
  }
`
`{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"dapp.exec1\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}`

**Comment by aiguo186** [comment]
@wchh @vivekmarakana thx！it works！

**Comment by cppfuns** [comment]
@aiguo186 
Can you say how to solve it? I didn't understand.

**Comment by jinxinslim** [comment]
+1

**Comment by ItVen** [comment]
i have same error
[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"banker\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}', transaction 'db261a5b5173de40e12800000000014011c8d3d10a918e00809286a96cd44501000000005c05a73900000000a8ed323208000000005c05a73900'
write-api.js:692:23

**Comment by heifner** [comment]
@metaboy this is a very old closed issue. Please create a new issue with version, config, exact command line, and full logs.
