### ISSUE TITLE
unable to find key and permissions issue

### ISSUE THREAD

**Issue by duanfp** [EOSIO/eos#3653]
cleos set contract eosio ../../contracts/eosio.system/ -p eosio
**frist time**: Error 3080006: transaction took too long
Error Details:
deadline exceeded
**after first time**: Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: unable to find key

cleos set contract eosio.token build/contracts/eosio.token -p eosio.token
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"eosio.token","permission":"active"}', but does not have signatures for it.

**Comment by roycezjq** [comment]
maybe you should create an account named eosio.token before setting the contract

**Comment by duanfp** [comment]
already create the account, but still have no permissions.
i dont know why, could u give me some help?

**Comment by breadbread1984** [comment]
I meet the same problem, find any resolution then?

**Comment by jhexperiment** [comment]
I ran into the same problem after a `git pull` followed by a rebuild `eosio_build.sh`

I had to install the new binaries to my system 
https://github.com/EOSIO/eos/wiki/Local-Environment#install-the-executables

**Comment by breadbread1984** [comment]
i figured it out. you must create sys token before create any other tokens. sys is used for voting for producers. sys serves as eos token on mainnet. the name of system token is determined during compiling.

**Comment by moskvanaft** [comment]
`unable to find key` most likely means that you don't have either some required accounts or system token.
See https://github.com/EOSIO/eos/wiki/Tutorial-Bios-Boot-Sequence
parts "Create important system accounts", "Install the eosio.tokencontract", "Create and allocate the SYS currency" (system token is called SYS by default, on mainnet it probably will be EOS).

`transaction declares authority '{"actor":"eosio.token","permission":"active"}', but does not have signatures for it.` means that you either have not imported your key into your wallet or you have not unlocked the wallet (it automatically locks after long inactivity).

I am closing the ticket. Feel free to reopen if you still have the problem.
