### ISSUE TITLE
can't set contract to account eosio

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#3655]
I launch nodeos with self generated keypair and specify the keypair with --private-key. I believe this keypair is used for account eosio. I import the private key into wallet and set contract to this account. The cleos complains

> Error 3050003: eosio_assert_message assertion failure                                                              
Error Details:                                                                                                     
assertion failure with message: unable to find key

I check my wallet with command

```Shell
cleos wallet keys
```
and find the keypair of eosio I imported. Why can't I set contract to eosio account. Please help!

**Comment by moskvanaft** [comment]
It seems like you don't have either some required accounts or system token.
See https://github.com/EOSIO/eos/wiki/Tutorial-Bios-Boot-Sequence
parts "Create important system accounts", "Install the eosio.tokencontract", "Create and allocate the SYS currency" (system token is called SYS by default, on mainnet it probably will be EOS).

I am closing the ticket. Feel free to reopen if the documentation didn't help.
