### ISSUE TITLE
EOS Centos7 安装报错

### ISSUE THREAD

**Issue by FreeManNumOne** [EOSIO/eos#3656]
Centos 7 按照这个链接安装，一直安装有问题。现在有最新的安装教程吗？
http://blog.eosdata.io/index.php/2018/04/07/eos-dawn-30-an-zhuang-zhi-nan/

**Comment by FreeManNumOne** [comment]
启动的报错信息

# ./nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::account_history_api_plugin
1732647ms thread-0   wallet_plugin.cpp:41          plugin_initialize    ] initializing wallet plugin
1732652ms thread-0   http_plugin.cpp:264           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
1732653ms thread-0   chain_plugin.cpp:151          plugin_initialize    ] initializing chain plugin
1732656ms thread-0   main.cpp:113                  main                 ] 10 assert_exception: Assert Exception
version > 0: Block log was not setup properly with genesis information.
    {}
    thread-0  block_log.cpp:470 extract_genesis_state

**Comment by Liu-Bolun** [comment]
现在版本是4.2.........按照官方文档的启动方式，并结合这个来看https://github.com/EOSIO/eos/releases/tag/dawn-v4.2.0

**Comment by FreeManNumOne** [comment]
好的想问一下测试环境 安装是另外一个git 地址文档吗？

**Comment by Liu-Bolun** [comment]
https://github.com/EOSIO/eos/wiki/Local-Environment

**Comment by FreeManNumOne** [comment]
这个安装文件适用于测试环境的安装吗？

**Comment by FreeManNumOne** [comment]
这个安装文档适用于测试环境的安装吗？我这边想安装一套EOS的测试开发调试的环境。谢谢！

**Comment by FreeManNumOne** [comment]
我昨天按照这个文档安装，https://github.com/EOSIO/eos/wiki/Local-Environment ，那我的理解是现我安装的这个环境可以测试开发环境调试用了吗？

**Comment by FreeManNumOne** [comment]
curl '127.0.0.1:8888' 也返回了信息，那现这个环境可以连接外网，是否可以当作开发测试环境 进行调试。

**Comment by Liu-Bolun** [comment]
是的，首先你要确保安装成功，出现eosio成功的图样。

**Comment by Liu-Bolun** [comment]
外网要去更改config.ini,将 p2p-server-address = [外网ip]:8888，当然也可以另外一种方案，将http-server-address= [外网ip]:8888，但是测试环境本机不能直接访问，在cleos命令时要cleos -u http://[ip]:[端口]/ 命令

**Comment by Liu-Bolun** [comment]
我只做过centos的，记得执行安装，
cd build
sudo make install

**Comment by FreeManNumOne** [comment]
我看网上有一个测试环境，大家好多人在上面玩。方便加个QQ什么的吗？

**Comment by Liu-Bolun** [comment]
这个地方是对公众可见的，放置联系方式无异于要被信息轰炸，有问题直接提就好，我也只能挑着自己知道的说说，毕竟我也菜

**Comment by FreeManNumOne** [comment]
哈哈，行

**Comment by xiaotian044500** [comment]
sudo su -
