### ISSUE TITLE
do cleos  get account tokenpocke25 then throw bugs

### ISSUE THREAD

**Issue by heipacker** [EOSIO/eos#3659]
2739545ms thread-0   main.cpp:2552                 main                 ] Failed with error: Assert Exception (10)
a.get_symbol() == b.get_symbol(): 

version info:
root@iZrj9fjy4361prityhtkvcZ:/data-stage16# cleos -u 'http://127.0.0.1:8888' get info
{
  "server_version": "00c78697",
  "chain_id": "706a7ddd808de9fc2b8879904f3b392256c83104c1d544b38302cc07d9fca477",
  "head_block_num": 183276,
  "last_irreversible_block_num": 183275,
  "last_irreversible_block_id": "0002cbebaae193936df403e0bdaa464681c445b5b646a747e74e21860f9a9e76",
  "head_block_id": "0002cbec114e6f1be7413bf8f36360480d89a5a0df86f6eb4d82d3299e5679a5",
  "head_block_time": "2018-05-31T13:07:58",
  "head_block_producer": "eosio",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576
}

**Comment by taokayan** [comment]
Can you provide your detail command?

**Comment by dixia** [comment]
closed as no follow.

if this persists please file an issue again
