### ISSUE TITLE
Difference between cleos create account and cleos system newaccount

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eos#3672]
There are currently two ways to create account, what's the difference?
#### `cleos system newaccount creator name OwnerKey ActiveKey`

It seems that the `system newaccount` is have five extra Options.

```
 --stake-net TEXT            The amount of EOS delegated for net bandwidth
  --stake-cpu TEXT            The amount of EOS delegated for CPU bandwidth
  --buy-ram-bytes UINT        The amount of RAM bytes to purchase for the new account in kilobytes KiB, default is 8 KiB
  --buy-ram-EOS TEXT          The amount of RAM bytes to purchase for the new account in EOS
  --transfer                  Transfer voting power and right to unstake EOS to receiver
```

So is that redundant to keep `cleos create account`?

**Comment by tbfleming** [comment]
```cleos system``` commands are for when the system contract is installed. ```cleos create account``` shouldn't be used with the system contract.
