### ISSUE TITLE
Migrate http_plugin to boost beast

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#3678]
Right now we are using websocketpp (and an old version to boot) for our HTTP-RPC server.  

One of the most unfortunate side effects of this is that when handling http requests it will advertise HTTP/1.1 but does not support keep-alive.  We have made a small change so that it properly uses the `Connection: close` header (as the default value for that header is `keep-alive` in HTTP/1.1) to notify the peer that it will be closing the connection.  However, it would be a huge win for performance of cleos and the new out-of-process key signing if connections could persist longer. 

This would amortize the cost of TCP and TLS connections/handshaking down to almost nothing.

**Comment by brianjohnson5972** [comment]
@wanderingbort This looks like it is OBE (overcome by events), is it?  I will presume it is if I hear nothing.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!

**Comment by spoonincode** [comment]
This needs to be done, and I'm not sure if it's tracked anywhere else at the moment

**Comment by jeffreyssmith2nd** [comment]
This is tracked in Jira. I'll defer to @aclark-b1 but I would prefer we only track in one place and close this.

**Comment by spoonincode** [comment]
if it's in jira that's fine, I wasn't sure if it was or not
