### ISSUE TITLE
Producer configurable block lag compensation

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#3683]
# Description

Right now the "deadline" used to trigger sign/commit/send of a block on a producer is the block's timestamp.  However, in situations where the latency to the next producer/network is high OR if there is latency imposed by signature security (non local hardware module etc) it would be beneficial for the producers to set a value which will trigger sign/commit/send early.  This can compensate for signing and network lag when tolerances are tight. 

This should also be exposed through the API plugin so it can be adjusted at runtime.

**Comment by taokayan** [comment]
https://github.com/EOSIO/eos/pull/4118

**Comment by taokayan** [comment]
brief description:

This feature allows a producer to produce block sooner(negative number) or later(positive number), in terms of microseconds, in order to compensate the time different and network latencies between different producer nodes:

config/CLI parameters example:

```produce-time-offset-us = -5000``` This makes non-last block producing time to be scheduled 5ms earlier

```last-block-time-offset-us = -10000 ``` This makes last block producing time to be scheduled 10ms earlier.

to change at runtime, please use:
```
curl --data-binary '{"produce_time_offset_us":-3000}' http://localhost:8888/v1/producer/update_runtime_options
```
and
```
curl --data-binary '{"last_block_time_offset_us":-3000}' http://localhost:8888/v1/producer/update_runtime_options
```

**Comment by abourget** [comment]
I'm not sure I immediately get how we'd use that.
Would it be in reaction to network lag between our slot and the previous / next producers? (as in `Received block...latency=560ms`) so we'd adjust our offset to fit within our peers' lag window ? This changes quite dynamically though... and I've seen some producers drift linearly (lack of NTP sync)..
This seems a little wonky.. but I'm sure there's a better explanation :)

**Comment by wanderingbort** [comment]
If you find that your blocks are often microforked out of the chain because they arrive "late" from the point-of-view to the next producer, this allows you to ship some of the blocks off on the network early to try to compensate.  The idea is that a partial block in the chain is better than block out of tha chain.
