### ISSUE TITLE
Failed with error: 10 assert_exception: Assert Exception

### ISSUE THREAD

**Issue by asvirido** [EOSIO/eos#370]
# I have a problem with create account

```
3069107ms thread-0   main.cpp:768 main]
Failed with error: 10 assert_exception: Assert Exception
status_code == 200:
Error: 3030002 tx_missing_sigs: signatures do not satisfy declared authorizations
Transaction declares authority
'{"account":"inita","permission":"active"}', but does not have signatures for it.
{"auth":{"account":"inita","permission":"active"}}
thread-0  chain_controller.cpp:749 get_required_keys
```
Help please!

**Comment by nanonano7** [comment]
You need to import the private key for the inita account into your wallet.

**Comment by heifner** [comment]
See: https://github.com/EOSIO/eos#run-eos-walletd-and-importing-account-key

**Comment by asvirido** [comment]
Thank you very much!

**Comment by heifner** [comment]
Your welcome. Thanks for your interest in EOS.

**Comment by spicynoodle** [comment]
Also double check in the`eosd/data-dir/config.ini` you have append `plugin = eosio::wallet_plugin`

**Comment by rogeryu23** [comment]
@nanonano7 what are the steps to "You need to import the private key for the inita account into your wallet.
You also need to unlock the wallet before you do anything"

the doc only tells how to use existing one right?

**Comment by rupaliathashcode** [comment]
Hey i am getting same issue. i have unlocked the wallet and import the private key in the account @nanonano7 @heifner

**Comment by eliyahu-yhwh** [comment]
I FOUND IT!!!
eos/docker/config.ini

In my version / clone this file shows the producer to be "eosio" and a few lines down gives the Keys, the -j is for the json file:
1. ./cleos create account -j eosio wallet-name Public-Key-1 Public-Key-2
(you will get errors, but just continue on as shown)
2. ./cleos wallet import -n wallet-name eosio-private-key
(5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3)
3. ./cleos create account -j eosio wallet-name Public-Key-1 Public-Key-2

This should get you to the new account and a view of your json file...

**Comment by Sabrinsulthana** [comment]
Hi friends,
I found an error while setting a contract 
after creation of account 
Failed with error: Assert Exception (10)
