### ISSUE TITLE
Where to find the address and port of mainnet peers from the official announcement?

### ISSUE THREAD

**Issue by photon3108** [EOSIO/eos#3705]
After mainnet swap, I guess there are many peers, includes block producers (bp), to form mainnet. If I launch a non-bp fullnode, where to find the address (ip) and port of mainnet peers from the EOS official announcement?

**Comment by matthewdarwin** [comment]
Maybe this might help? https://steemit.com/eos/@eos-canada/eos-mainnet-launch-the-order-of-events

**Comment by gleehokie** [comment]
See https://eos.io/faq
