### ISSUE TITLE
[help] repositry EOSIO/genesis was gone,what happened?

### ISSUE THREAD

**Issue by YaleZheng** [EOSIO/eos#3709]
repositry EOSIO/genesis was gone,what happened?

at 2018/06/01, if u visit https://github.com/EOSIO/genesis ,github will show u "Page not found"

why delete this repositry?

and how can i get Eos Snapshot now?

**Comment by matthewdarwin** [comment]
https://github.com/EOS-distribution-collective/genesis/
  https://github.com/EOS-Mainnet/genesis/

**Comment by YaleZheng** [comment]
thks @matthewdarwin 

Did u know why move the repositry?

**Comment by xtay315** [comment]
what happened?

**Comment by gleehokie** [comment]
The community is responsible for the snapshot, so the repo was removed from this organization to prevent confusion.
