### ISSUE TITLE
Inconsistent results of  call "string_to_name" in "name.hpp" and "types.hpp"?

### ISSUE THREAD

**Issue by xiangxn** [EOSIO/eos#3710]
Inconsistent results of  call "string_to_name" in "name.hpp" and "types.hpp"?
Eosjs encodeName and their results are also inconsistent。

**Comment by moskvanaft** [comment]
@xiangxn , do you have any examples?

**Comment by xiangxn** [comment]
Because of the LE problem in JS, I have already processed.
