### ISSUE TITLE
Contract has no console output

### ISSUE THREAD

**Issue by mycamphortree** [EOSIO/eos#3713]
I use version 4.2. Follow the “https://github.com/EOSIO/eos/wiki/Tutorial-Hello-World-Contract” tutorial to operate a single node. I use  “nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --contracts-console true” started the node.
 But the output is:
cleos set contract hello2.code ./hello -p hello2.code
Reading WAST/WASM from ./hello/hello.wasm...
Using already assembled WASM...
Publishing contract...
executed transaction: 3c4610b13b2e6b6bfa78b99247393f810f8227cb3b1dc21c9724c4d1b0fa1234  1800 bytes  837 us
/#         eosio <= eosio::setcode               {"account":"hello2.code","vmtype":0,"vmversion":0,"code":"0061736d01000000013b0c60027f7e006000017e60...
/#         eosio <= eosio::setabi                {"account":"hello2.code","abi":"0e656f73696f3a3a6162692f312e30000102686900010475736572046e616d650100...
warning: transaction executed locally, but may not be confirmed by the network yet

I want to see ">> Hello, user" , what should I do?

**Comment by heifner** [comment]
Add `--contract-console` to nodeos.
