### ISSUE TITLE
eos account creation

### ISSUE THREAD

**Issue by Muhzn** [EOSIO/eos#3717]
i have installed eos....everything went normal , but after creating currency account...i cant able to set the path to currency...
cleos get account currency :its working
cleos get code  currency :its also working
but i cant set the path to currency

**Comment by sergmetelin** [comment]
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
