### ISSUE TITLE
contract not responds to any action after uploading to local node

### ISSUE THREAD

**Issue by alzozov** [EOSIO/eos#3720]
dawn 2.0 

this simple contract not responds to any action called to it, no output to console that smth is working there even with   --contracts-console  option for nodeos

![image](https://user-images.githubusercontent.com/741393/40824278-45dd0782-657c-11e8-8fe4-5b8237e600da.png)

```
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>

class membrana : public eosio::contract {
  public:
    membrana(account_name self)
      :eosio::contract(self),
      todos(_self, _self)
      {}

    // @abi action
    void create(account_name author, const uint32_t id, const std::string& description) {
      todos.emplace(author, [&](auto& new_todo) {
        new_todo.id  = id;
        new_todo.description = description;
        new_todo.completed = 0;
      });

      eosio::print("todo#", id, " created");
    }

    // @abi action
    void destroy(account_name author, const uint32_t id) {
      auto todo_lookup = todos.find(id);
      todos.erase(todo_lookup);

      eosio::print("todo#", id, " destroyed");
    }

    // @abi action
    void complete(account_name author, const uint32_t id) {
      auto todo_lookup = todos.find(id);
      eosio_assert(todo_lookup != todos.end(), "Todo does not exist");

      todos.modify(todo_lookup, author, [&](auto& modifiable_todo) {
        modifiable_todo.completed = 1;
      });

      eosio::print("todo#", id, " marked as complete");
    }

  private:
    // @abi table todos i64
    struct todo {
      uint64_t id;
      std::string description;
      uint64_t completed;

      uint64_t primary_key() const { return id; }
      EOSLIB_SERIALIZE(todo, (id)(description)(completed))
    };

    typedef eosio::multi_index<N(todos), todo> todo_table;
    todo_table todos;
};

EOSIO_ABI(membrana, (create)(complete)(destroy))


```

**Comment by alzozov** [comment]
i tried 
cleos push action membrana create '["dev", 1, "feed cat"]' -p dev
it is not working

here is how contract compiled and uploded

![image](https://user-images.githubusercontent.com/741393/40824973-ceac2cbc-657e-11e8-8ee6-e5de7c90d3aa.png)

**Comment by Velua** [comment]
Created a fresh account 
`cleos create account eosio newaccount EOS79TwoaKtEtMCCcBh7Jq8CJDyxAmiMwA5AckvWPARFGvQFTXL1c EOS79TwoaKtEtMCCcBh7Jq8CJDyxAmiMwA5AckvWPARFGvQFTXL1c`

Then deployed the contract
`cleos set contract mynewaccount /tmp/build/contracts/membrana/ -p mynewaccount`

Then pushed a create action over, 
`cleos push action newaccount create '["newaccount", 1, "feed cat"]'`

returned 
```executed transaction: 73fd77cc6bac63db11a8482b592ec4067f3c5191e42bf199f9eaa36d0b9c4091  120 bytes  5343 us
#    newaccount <= newaccount::create           {"author":"newaccount","id":1,"description":"feed cat"}
>> todo#1 created
warning: transaction executed locally, but may not be confirmed by the network yet
```

Looks good on this end.

**Comment by alzozov** [comment]
ok thanks, can you please share config.ini of nodeos ? 
and how you launch nodeos maybe something is wrong on my side

**Comment by alzozov** [comment]
John is it dawn 4.2 u are using?

**Comment by heifner** [comment]
You need to add `--contracts-console` to see print statements.

**Comment by alzozov** [comment]
It is not solved issue @heifner @Velua 

trying --contracts-console not works, reinstalling eosio not helps
the problem here is that in some reason contract that was published to to local blockchain node is not visible

so I publish contract cleos set contract developer ./hello -p developer

then cleos push action hello hi '["user"]' -p user

```
Error 3060004: Contract Query Exception
Most likely, the given contract doesnt' exist in the blockchain.
Error Details:
Contract can't be found hello

```

trying cleos get code -a hello.abi hello 

```
2809933ms thread-0   main.cpp:2584                 main                 ] Failed with error: unspecified (0)
unknown key
```

may it be it is some problem with keosd on my side ?

**Comment by yunjiali** [comment]
@alzozov Not sure if you have solved the problem. If you deploy the contract by `cleos set contract developer ./hello -p developer`, you need to replace the `hello` in the contract execution with `developer`. This is a bit confusing to me as the manual of cleos push action says `cleos push action [OPTIONS] contract action data`. Obviously, the `contract` should be `account` which deployed the smart contract.

**Comment by alzozov** [comment]
@yunjiali yes it worked, thx. 
Had you implemented sending eos coins from contract account (inside from contract) to other user ?

**Comment by yunjiali** [comment]
@alzozov Not yet. I am still new to EOS and trying to learn the basic concepts :)
