### ISSUE TITLE
get_table_rows_params ，Do you need to add a primary key to lookup？

### ISSUE THREAD

**Issue by OracleChain** [EOSIO/eos#3723]
struct get_table_rows_params {
      bool        json = false;
      name        code;
      string      scope;
      name        table;
//      string      table_type;
      string      table_key;
      string      lower_bound;
      string      upper_bound;
      uint32_t    limit = 10;
    };

**Comment by OracleChain** [comment]
@bytemaster

**Comment by taokayan** [comment]
primary key must be of type uint64_t, you only need to specify the lower bound and upper found for lookup
