### ISSUE TITLE
query actions is null,version dwan-v4.2.0

### ISSUE THREAD

**Issue by healthwallet** [EOSIO/eos#3726]
eos2@eos2-virtual-machine:~$ cleos push action liontoken transfer '["liontoken","eosio","10.000000 SNC",""]' -p liontoken
executed transaction: cb3370d0549fbeb1b6ecb021e0bd25d327f7c798aed2cd22024bfe25adf0d0c3  128 bytes  1705 us
#     liontoken <= liontoken::transfer          {"from":"liontoken","to":"eosio","quantity":"10.000000 SNC","memo":""}
#         eosio <= liontoken::transfer          {"from":"liontoken","to":"eosio","quantity":"10.000000 SNC","memo":""}
warning: transaction executed locally, but may not be confirmed by the network yet
eos2@eos2-virtual-machine:~$ cleos push action liontoken transfer '["liontoken","eosio","10.000000 SNC",""]' -p liontoken
executed transaction: a0908905adb5f142caccc120c269a6d56261a5ed2afa0fe2495cf7851a12bfb8  128 bytes  1181 us
#     liontoken <= liontoken::transfer          {"from":"liontoken","to":"eosio","quantity":"10.000000 SNC","memo":""}
#         eosio <= liontoken::transfer          {"from":"liontoken","to":"eosio","quantity":"10.000000 SNC","memo":""}
warning: transaction executed locally, but may not be confirmed by the network yet
eos2@eos2-virtual-machine:~$ cleos get actions liontoken
#  seq  when                              contract::action => receiver      trx id...   args
================================================================================================================

**# **there is no action show!!!!!!!!!****
eos2@eos2-virtual-machine:~$

**Comment by spartucus** [comment]
> We greatly reduced the memory usage of the history plugin by reducing the tracked actions to only those that match explicit filter rules. There is now no way to track all actions since that is susceptible to filling shared_mem.

Try start nodeos with `--filter-on "*"`.
