### ISSUE TITLE
system newaccount => to account does not exist

### ISSUE THREAD

**Issue by maxb14** [EOSIO/eos#3727]
Hello, the following command :

$> cloes system newaccount eosio testnet xxxxkey xxxxxkey —stake-net "100.00 SYS" —stake-cpu "100.00 SYS"

return this error:

—----------------
2162366ms thread-0   main.cpp:429                  create_action        ] result: {"binargs":"0000000000ea305500000020ab99b1ca00200000"} arg: {"code":"eosio","action":"buyrambytes","args":{"payer":"eosio","receiver":"testnet","bytes":8192}} 
2162374ms thread-0   main.cpp:429                  create_action        ] result: {"binargs":"0000000000ea305500000020ab99b1ca40420f0000000000045359530000000040420f0000000000045359530000000000"} arg: {"code":"eosio","action":"delegatebw","args":{"from":"eosio","receiver":"testnet","stake_net_quantity":"100.0000 SYS","stake_cpu_quantity":"100.0000 SYS","transfer":false}} 
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: to account does not exist
—----------------

This message is stupid, it is normal that the account does not exist since I want to create it

**Comment by zorba80** [comment]
Do you have eosio.ram, eosio.ramfee, and eosio.stake accounts created?

**Comment by liliyongleo** [comment]
if eosio.ram, eosio.ramfee, and eosio.stake are not created before enable eosio.system, how can we create these userids? or how to disable eosio.system contract first?

**Comment by evsward** [comment]
There's a work-around that you can set another contract except 'eosio.system' with eosio.  Then eosio's code has been changed.  After that, you can create eosio.* accounts.  Then you can set system contract with eosio and try to 'system newaccount' operation again, it should be work.

**Comment by andriantolie** [comment]
As @zorba80 said, you need to create the eosio.ram, eosio.ramfee, and eosio.stake accounts to create a new account after uploading the system contract. Otherwise, it will complain that the above accounts do not exist.
