### ISSUE TITLE
Upload sample contract doesn't work.

### ISSUE THREAD

**Issue by asvirido** [EOSIO/eos#373]
### Input
`./eosc set contract player ../../../contracts/currency/currency.wast ../../../contracts/currency/currency.abi`
### Output
`236602ms thread-0   main.cpp:768main]
Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error
: 3030002 tx_missing_sigs: signatures do not satisfy declared authorizations
Transaction declares authority '{"account":"player1","permission":"active"}',
but does not have signatures for it.
{"auth":{"account":"player1","permission":"active"}}
thread-0  chain_controller.cpp:749 get_required_keys`

### where is find tutorial about create smart contracts on eos?

**Comment by bycz6** [comment]
check this. Don't know if it help
https://github.com/EOSIO/eos/issues/311

**Comment by asvirido** [comment]
This does not work

**Comment by nanonano7** [comment]
Do you have your wallet unlocked and have all necessary private keys imported for the player account?

**Comment by asvirido** [comment]
Yes

**Comment by asvirido** [comment]
### INPUT WALLET CREATE
`./eosc wallet create`

### OUTPUT 
```
Creating wallet: default
Save password to use in the future to unlock this wallet.
Without password imported keys will not be retrievable.
"PW5Jw18LjR65ATRZAuGZfBDDCrifKimWXNXiFrxQZt9F9zKV3cA6j"
```

### INPUT WALLET IMPORT
`./eosc wallet import 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3`
### OUTPUT
`imported private key for: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV`
### INPUT CREATE KEY 
```
./eosc create key
./eosc create key
```
## OUTPUT
###Owner key
```
Private key: 5JrCcoukm93odyEcHxD9gbGJ5Qy7Q4KNK1RGtDCKExww6TdRK6x
Public key:  EOS65oyszGKvYfkLavKUD5WywJqQdqFa4wBLRA5MPND1muVHRVErh
```
###activity key
```
Private key: 5JeC2Uc7DK9ErNPkcESDRAzndUAuWPdGt96AULpgkD99Fnssmh4
Public key:  EOS7w6XGCvkLkw4CKW1rAwNMXK6a77JWyhYFMwBWT1QvwXv2inSsk
```
### INPUT
`./eosc create account inita currency EOS65oyszGKvYfkLavKUD5WywJqQdqFa4wBLRA5MPND1muVHRVErh EOS7w6XGCvkLkw4CKW1rAwNMXK6a77JWyhYFMwBWT1QvwXv2inSsk`
### iNPUT 
`./eosc set contract currency ../../../contracts/currency/currency.wast ../../../contracts/currency/currency.abi`
### OUTPUT
```
Reading WAST...
Assembling WASM...
Publishing contract...
3577570ms thread-0   main.cpp:768 main] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error 
```

**Comment by asvirido** [comment]
Before running, I delete files "blocks" "blockchain" "default.wallet" in data-dir
I run command in terminal
`./eosd --skip-transaction-signatures`
and start
`./eosc create wallet`
etc

**Comment by asvirido** [comment]
# Solution

` ./eosc wallet import PRIVAT_KEY_ACTIVITY`

### and after

`./eosc set contract currency ../../../contracts/currency/currency.wast ../../../contracts/currency/currency.abi
`

**Comment by Toormi** [comment]
File does not exist: ../../../contracts/currency/currency.wast
ERROR: ValidationError: wast-file=../../../contracts/currency/currency.wast

I got this message, where

**Comment by amodi01** [comment]
@nanonano7 : If I have to createand deploy a new Smart Contratc, then how can i Create a wast and abi file?

**Comment by nanonano7** [comment]
via eoscpp in tools. https://eosio.github.io/eos/md_contracts_eoslib_tutorial.html

**Comment by amodi01** [comment]
@nanonano7 Thanks alot for the help.

**Comment by heifner** [comment]
@amodi01 Please use Telegram `EOS Developers` for support.

**Comment by amolmaid** [comment]
Hi,
Does the name of an account should be same as of .abi file for setting the hash-code/contract ?
  I mean in above detailed comments from @liderako , instead of creating **currency** account if I use any other account name like **player** , will it work for following command ?
`./eosc set contract currency ../../../contracts/currency/currency.wast ../../../contracts/currency/currency.abi`

I am facing same issue, as I am trying to achieve --> transfer fund from _accountA_ to _accountB_ (the way it happens in usual wallets like Zebpay).
