### ISSUE TITLE
build error,help!!!!

### ISSUE THREAD

**Issue by hktk1001** [EOSIO/eos#3732]
/home/code/eos/libraries/chain/include/eosio/chain/apply_context.hpp:227:28:   required from ‘void eosio::chain::apply_context::generic_index<ObjectType, SecondaryKeyProxy, SecondaryKeyProxyConst>::update(int, eosio::chain::account_name, eosio::chain::apply_context::generic_index<ObjectType, SecondaryKeyProxy, SecondaryKeyProxyConst>::secondary_key_proxy_const_type) [with ObjectType = eosio::chain::secondary_index<float128_t, 12, eosio::chain::soft_long_double_less>::index_object; SecondaryKeyProxy = float128_t&; SecondaryKeyProxyConst = const float128_t&; eosio::chain::account_name = eosio::chain::name; eosio::chain::apply_context::generic_index<ObjectType, SecondaryKeyProxy, SecondaryKeyProxyConst>::secondary_key_proxy_const_type = const float128_t&]’
/home/code/eos/libraries/chain/wasm_interface.cpp:1265:7:   required from here
/home/code/eos/libraries/chain/include/eosio/chain/apply_context.hpp:65:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                FC_ASSERT( iterator < _iterator_to_object.size(), "iterator out of range" );
/home/code/eos/libraries/fc/include/fc/exception/exception.hpp:332:30: note: in definition of macro ‘FC_EXPAND_MACRO’
 #define FC_EXPAND_MACRO( x ) x
                              ^
/home/code/eos/libraries/fc/include/fc/exception/exception.hpp:339:11: note: in expansion of macro ‘UNLIKELY’
       if( UNLIKELY(!(TEST)) ) \
           ^~~~~~~~
/home/code/eos/libraries/chain/include/eosio/chain/apply_context.hpp:65:16: note: in expansion of macro ‘FC_ASSERT’
                FC_ASSERT( iterator < _iterator_to_object.size(), "iterator out of range" );
                ^
/home/code/eos/libraries/chain/include/eosio/chain/apply_context.hpp: In instantiation of ‘void eosio::chain::apply_context::iterator_cache<T>::remove(int) [with T = eosio::chain::secondary_index<float128_t, 12, eosio::chain::soft_long_double_less>::index_object]’:
/home/code/eos/libraries/chain/include/eosio/chain/apply_context.hpp:223:16:   required from ‘void eosio::chain::apply_context::generic_index<ObjectType, SecondaryKeyProxy, SecondaryKeyProxyConst>::remove(int) [with ObjectType = eosio::chain::secondary_index<float128_t, 12, eosio::chain::soft_long_double_less>::index_object; SecondaryKeyProxy = float128_t&; SecondaryKeyProxyConst = const float128_t&]’
/home/code/eos/libraries/chain/wasm_interface.cpp:1265:7:   required from here
/home/code/eos/libraries/chain/include/eosio/chain/apply_context.hpp:74:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                FC_ASSERT( iterator < _iterator_to_object.size(), "iterator out of range" );
/home/code/eos/libraries/fc/include/fc/exception/exception.hpp:332:30: note: in definition of macro ‘FC_EXPAND_MACRO’
 #define FC_EXPAND_MACRO( x ) x
                              ^
/home/code/eos/libraries/fc/include/fc/exception/exception.hpp:339:11: note: in expansion of macro ‘UNLIKELY’
       if( UNLIKELY(!(TEST)) ) \
           ^~~~~~~~
/home/code/eos/libraries/chain/include/eosio/chain/apply_context.hpp:74:16: note: in expansion of macro ‘FC_ASSERT’
                FC_ASSERT( iterator < _iterator_to_object.size(), "iterator out of range" );
                ^
virtual memory exhausted: Cannot allocate memory
make[2]: *** [libraries/chain/CMakeFiles/eosio_chain.dir/build.make:519: libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1873: libraries/chain/CMakeFiles/eosio_chain.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by pacificcode** [comment]
@hktk1001 Can you run the following commands and paste the FULL output here?

cd /path/to/eos
rm -rf build/
git checkout master
git pull
git submodule update --init --recursive
./eosio_build.sh

**Comment by w00tcoin** [comment]
I’m had a similar issue with cmake library. Tried the sub module update and now “destination path ‘mongo-cxx-driver’ already exists and is not empty. Do I just delete dir and re run ?

**Comment by w00tcoin** [comment]
Nm got it for now

**Comment by taokayan** [comment]
Is this issue solved?

**Comment by pacificcode** [comment]
@taokayan Closing this issue.
