### ISSUE TITLE
get_actions integer overflow allows to override account_name filter

### ISSUE THREAD

**Issue by mmcs85** [EOSIO/eos#3735]
Calling the get_actions api with the values accountName = "foo" AND
pos= 1, offset= 2147483646 OR
pos= 2147483646, offset = 1

results in a integer overflow in here:
https://github.com/EOSIO/eos/blob/7c2e6e76a02e5e01fb473edd29815c104464fc46/plugins/history_plugin/history_plugin.cpp#L349
end = (2147483646 + 1) + 1
end+1 is not checked for integer overflow so the resulted end_itr < start_itr

Now the side effect is that:
If the amount of stored actions is big to hit time_limit_exceeded_error then all the actions are returned without looking into the accountName criteria.
Else:
It doesnt crash nodeos but instead gives error "unknown key" wich is fine I guess.

**Comment by arhag** [comment]
Resolved by #3748.

**Comment by stvenyin** [comment]
know.
