### ISSUE TITLE
Incorrect type for last_producer_schedule_update in eosio.system.abi

### ISSUE THREAD

**Issue by andriantolie** [EOSIO/eos#3740]
last_producer_schedule_update is supposed to be blocktime_stamp_type instead of timepoint_sec

**Comment by arhag** [comment]
Resolved by #3744.

**Comment by stvenyin** [comment]
+ {“name”：“last_producer_schedule_update”，“type”：“ block_timestamp_type ”}，
block_timestamp_type  i see
