### ISSUE TITLE
eosc producer interface

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#375]
How does a normal user use eosc to see and vote for producers?

Commands needed via Dan (Actually Dan and I were putting this in at same time, see above)
- [x] eosc create producer username
- [x] eosc set producer approve user producername   -p user@active
- [x] eosc set producer unapprove user producername   -p user@active
- [x] eosc set proxy user proxyname -p user@active
- [x] default permission to user@active so not required every single time
- [x] setting proxy to 'null' will clear it
- [x] add interaction to eosd_run_test.sh integration test

**Comment by bytemaster** [comment]
I got side tracked on the data storage accounting problem, so have no progress or commits to report.

**Comment by heifner** [comment]
Phil mentioned you would like me to take a look at eosc producer interface which I believe is this issue. If you would rather me work on something else, just let me know.

**Comment by bytemaster** [comment]
```
Daniel Larimer, [Sep 11, 2017, 11:48 AM (9/11/17, 11:48:57 AM)]:
eosc set producer approve user producername   -p user@active
eosc set producer unapprove user producername   -p user@active
eosc set proxy user proxyname -p user@active

```

permission should default to user@active so they don't have to set it every single time

I'm assuming -p == the permision flag, it should match what ever is used for push transaction.

**Comment by heifner** [comment]
Commands needed via Dan
- [ ] eosc create producer username
- [ ] eosc producer approve producername
- [ ] eosc set producer approve user producername   -p user@active
- [ ] eosc set producer unapprove user producername   -p user@active
- [ ] eosc set proxy user proxyname -p user@active
- [ ] default permission to user@active so not required every single time

**Comment by heifner** [comment]
- About half done.
- Added task to add interaction to integration test.

**Comment by heifner** [comment]
- eos_contract apply_eos_setproxy is not implemented yet, so ./eosc set proxy can not be tested.

**Comment by heifner** [comment]
Merged via pull request $410
