### ISSUE TITLE
systemcontract will disappear after a successful deploying

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#3760]
<img width="1280" alt="screen shot 2018-06-02 at 5 41 40 pm" src="https://user-images.githubusercontent.com/16130147/40873089-730da76e-668c-11e8-9947-22383452687d.png">

I just wrap "cleos " "nodeos" by  python with a configure file

**Comment by moskvanaft** [comment]
@yankunsam what is in main.py ?
Does this script recompile system contract or what ?
Is it possible that main.py somehow changed eosio.system.wast ?

what version of EOS are you using ?

**Comment by yankunsam** [comment]
Here is my main.py .  https://github.com/yankunsam/Eoasis .   I use eos v1.0.0

**Comment by sergmetelin** [comment]
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
