### ISSUE TITLE
Assert Exeception on cleos get account

### ISSUE THREAD

**Issue by educatedwarrior** [EOSIO/eos#3769]
![image](https://user-images.githubusercontent.com/4054610/40881949-697c39de-66a2-11e8-994a-789144c3df64.png)

This command works with the -j option for JSON format with no errors.

**Comment by moskvanaft** [comment]
It seems like your `cleos` was compiled with different CORE_SYMBOL_NAME than the software it is connecting to (more specificaly, system contract installed on the chain).

**Comment by moskvanaft** [comment]
I am closing the ticket for now.
@educatedwarrior feel free to reopen if recompiling cleos with correct `CORE_SYMBOL_NAME` doesn't help.
