### ISSUE TITLE
why undelegatebw failed? tip "not enough has been staked for users to unstake" which i have

### ISSUE THREAD

**Issue by zformular** [EOSIO/eos#3771]
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/1741302/40882109-cec85ec2-670a-11e8-835c-2e4764a6e5c0.png">

**Comment by moskvanaft** [comment]
System contract doesn't allow you to unstake until the chain was activated. "Activated" means that accounts collectively owning 15% or more of total token supply voted for block producers.
See https://medium.com/@thomas.cox_39839/magic-15-unlocking-the-eosio-blockchain-91ec54f7b48d
