### ISSUE TITLE
p2p set option crash

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#3773]
41948ms thread-0   controller.cpp:896            maybe_switch_forks   ] successfully switched fork to new head 0001fec4ad550fe47fc189653e042aacc82400d0853a2bc0686d7bff509c0a3a
2045657ms thread-0   net_plugin.cpp:2433           operator()           ] accept txn threw  3080006 deadline_exception: transaction took too long
deadline exceeded
    {"now":"2018-06-01T14:34:05.656","deadline":"2018-06-01T14:34:05.651","start":"2018-06-01T14:34:05.576"}
    thread-0  transaction_context.cpp:288 checktime

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:60 exec_one
2045918ms thread-0   net_plugin.cpp:2080           operator()           ] Peer 35.177.169.60:9876 closed connection
2070127ms thread-0   net_plugin.cpp:1915           connect              ] host: 35.177.169.60 port: 9876 
2090385ms thread-0   net_plugin.cpp:2080           operator()           ] Peer 35.177.169.60:9876 closed connection
2106005ms thread-0   net_plugin.cpp:1915           connect              ] host: 35.177.169.60 port: 9876 
2121652ms thread-0   main.cpp:119                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
std::exception::what: set_option: Invalid argument

2121826ms thread-0   fork_database.cpp:93          close                ] num_blocks_in_fork_db: 457 
2122031ms thread-0   controller.cpp:261            ~controller_impl     ] db.revision(): 130894 head->block_num: 130894 blog.read_head()->block_num(): 130466 
Segmentation fault: 11

This is another case where an asio call was nade outside a try block and without an error code parameter.

I'm not sure how to write an ATC because I don't know how to induce the error.  It looks like the async connection handler can be called before the connection is ready

**Comment by fujiapple852** [comment]
I'm running on this branch now and am not longer receiving the above error
