### ISSUE TITLE
How to prevent re-deploy contract without consensus?

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#3775]
In my test network, I can easily re-deploy my contract by using command:
```
cleos set contract <account_name> <contract_dir> -p <account_name>
```
It seems that anyone who is the owner of  account can change the contract without permission of BP?
I doubt that how does a re-deploy contract proposal effictive by the main chain?

**Comment by moskvanaft** [comment]
You don't need any approvals to deploy a contract to your own account. You cannot deploy to others accounts or system accounts.
If you want to require more then one person to agree on deploying a contract, you can configure your permissions to require more than one signature, check out the documentation on permissions - https://github.com/EOSIO/eos/wiki/Accounts%20%26%20Permissions#multi-sig-account--custom-permissions

**Comment by brianjohnson5972** [comment]
@guaiguaihw you could also set the delay seconds for a permission that has a linkauth set for setcode, which would make it clear that there is a period of time that they will be able to analyze any new contract code before it actually goes into effect.
