### ISSUE TITLE
currency - get_supply - error

### ISSUE THREAD

**Issue by filipniziol** [EOSIO/eos#3781]
Inside the contract I run:

`currency(N(eosio.token)).get_supply(symbol_type(S(4, SYS)).name()); `

Cannot make it work:

> Error 3050003: eosio_assert_message assertion failure
> Error Details:
> assertion failure with message: unable to find key

**Comment by moskvanaft** [comment]
@filipniziol do you have token contract installed on to eosio.token account and SYS token created?

**Comment by filipniziol** [comment]
Yes. What started to work was replacing reference to currency.hpp => eosio.token.hpp and making get_supply and get_balance public not private
It seems not to work in that shape.
I have made pull request for this:
https://github.com/EOSIO/eos/pull/3832

**Comment by arhag** [comment]
Resolved by #3832.
