### ISSUE TITLE
Where to log issues

### ISSUE THREAD

**Issue by BinaryFocus** [EOSIO/eos#3787]
It is currently unclear if we should log issues here or over at https://github.com/EOS-Mainnet/eos .. can someone please provide direction.

**Comment by moskvanaft** [comment]
@BinaryFocus if you are reporting issues about the EOS software (not third-party tools, scripts, etc), you should do it here. This is the official EOS repository maintained by Block.one , EOS-Mainnet/eos is a fork created by someone else (I am not aware who and why created it).
