### ISSUE TITLE
Limitation of account history for token receiver of eosio.token transfer action

### ISSUE THREAD

**Issue by CharlesJu1** [EOSIO/eos#3789]
The filter-on option takes the form of receiver:action:actor, where actor can be left blank. The receiver part can not be left blank. 

For the eosio.token contract, with any given receiver, if I want to be able to check all the token transferred  to that receiver from all different actors, I could not do that with the current filter-on mechanism. 

Does it make sense to allow the receiver in the filter-on option to be blank as well? 

Note that a transfer action will trigger three action trace with eosio.token, user, tester as the receiver respectively.

```
easypayx@easypayxs-MacBook-Pro:~/eosio-commands $ cleos push action eosio.token transfer '[ "user", "tester", "25.0000 EOS", "m" ]' -p user
executed transaction: 00a9a3e1e109682496fe1c3730473f85be687cd2c362455c9ea72e2435993bbc  128 bytes  2177 us
#   eosio.token <= eosio.token::transfer        {"from":"user","to":"tester","quantity":"25.0000 EOS","memo":"m"}
#          user <= eosio.token::transfer        {"from":"user","to":"tester","quantity":"25.0000 EOS","memo":"m"}
#        tester <= eosio.token::transfer        {"from":"user","to":"tester","quantity":"25.0000 EOS","memo":"m"}
```

**Comment by tbfleming** [comment]
The history plugin keeps actions that match the filter in shared memory. If it allowed a blank receiver or action, then it would open up a ram-filling attack.

#3757 (merged) doesn't meet your needs?

**Comment by CharlesJu1** [comment]
#3757 solves half my problem. It allows me to retrieve all the transfer actions where an account is the sender. If given an account I want to see which other accounts does it receive token from, I could not do it. I noticed the current filter-on allows a "*", which will set the bypass_filter to true. 

For the ram-filling attack, if the contract name is also added to the filter-on option, that would help. That is, if the filter-on takes the following form:
`contract:action:actor:receiver`
and we require the contract name must be present while all others can be left blank. That would give a full node control on what to filter and not open up a ram-filling attack, right?

**Comment by tbfleming** [comment]
"*" is for testing purposes only.

Contracts ignore actions they don't understand. e.g. if someone sent large actions named `foo` to `eosio.token`, it would ignore them and the chain would consider them valid. If filter-on's action was empty, it'd store those actions.

**Comment by CharlesJu1** [comment]
I see. So a blank action still open up a ram-filling attack. Then what about we require contract and action must be specified, but actor and receiver can be  left blank?

**Comment by tbfleming** [comment]
`contract:action:actor:receiver` sounds good.

**Comment by tbfleming** [comment]
It will probably need to maintain backwards compatibility, so should handle both the 4-colon and 3-colon forms.

**Comment by CharlesJu1** [comment]
Got it.

**Comment by tbfleming** [comment]
The amount of map lookups it takes to do this got excessive, so I'm now leaning toward dropping backward compatibility. Maybe something like this: ```--filter-on contract:action:account```? contract and action would be required, account would be optional. If account is present it would match either actor or receiver.

**Comment by rbw3821** [comment]
I don't see how this is going to cut down on explosive memory growth over the long term. If you have a private contract, that would be one thing, but `eosio.token:transfer:` is going to be used heavily on the public blockchain so you're going to get everyone's transfers with that filter, and over the long term that's going to require huge amounts of memory.  I think this use case should be using a db plugin to store and query efficiently.

**Comment by CharlesJu1** [comment]
In our case, we will have a private contract that allows users to transfer some kind of asset among them and we would like to be able to show users their asset history coming in or out of their accounts. I would imagine many dapps will have this need. Thus we are looking for a way to be able to just track the related contract actions running on our own full node.
What is the difference between history plugin and a db plugin? Which existing plugin is a db plugin so I can take a look?

**Comment by rbw3821** [comment]
A db plugin mirrors content (transactions, etc.) to a db.  Your app then interacts with the db.  The history plugin with the `--filter-on` option puts matching actions into a multi-index map.  You can then use `cleos` to query the map.  Basically, with the history plugin, memory is your database, and it will eventually fill up.

As for available db plugins, this is basically an "exercise for the reader".  The mongo db plugin in the source code no longer works and is no longer maintained.  There is an sql db plugin in development by the community.  I've not tracked the status of that.  Perhaps you could participate in that or roll your own.

**Comment by CharlesJu1** [comment]
Got it. I also noticed from source code that history_plugin does not require mongo db plugin. Given the current --filter-on option can take the form of eosio.token:transfer:  which will also grow the memory continuously, is it ok to make a change as Todd suggested as a partial solution? For Dapp that needs frequent fast queries and not that many history to keep track, this memory database is a good fit. Once the db plugin is developed by the community, Dapp can have more choices.

**Comment by datnv-ibl** [comment]
This pull request is very useful. I merge it locally and save all the data to disk, not Ram. Thank you CharlesJu1.

**Comment by halsaphi** [comment]
Solved by tbfleming.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organised, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
