### ISSUE TITLE
Building and running a node on macOS - fatal error: 'currency/currency.wast.hpp' file not found

### ISSUE THREAD

**Issue by herman5** [EOSIO/eos#379]
On macOS 10.12.16, running `make -j4` in the `~/eos/build` directory (per the README guide) results in these errors around the 95% progress marker: `fatal error: 'test_api/test_api.wast.hpp' file not found` and `fatal error: 'currency/currency.wast.hpp' file not found`

**Comment by pavybez** [comment]
I just cloned repository and am able to successfully build it. Did you follow all the steps on readme?

**Comment by herman5** [comment]
I've followed the readme step for step 3 times now, every time building the dependencies from scratch as well as building LLVM and clang for WASM from scratch. Still getting the same error.

**Comment by mark0st** [comment]
I can see the same issue (macOS 10.12.6).

```
[ 81%] Linking CXX executable embed_genesis
ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in ___gmpn_divexact_1 from /usr/local/lib/libgmp.a(dive_1.o). To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
/Users/marko/devel/EOS/eos/tests/api_tests/api_tests.cpp:34:10: fatal error: 'test_api/test_api.wast.hpp'
      file not found
#include <test_api/test_api.wast.hpp>
         ^
[ 81%] Built target embed_genesis
1 error generated.
...

[ 83%] Building CXX object tests/CMakeFiles/slow_test.dir/common/database_fixture.cpp.o
/Users/marko/devel/EOS/eos/tests/slow_tests/slow_tests.cpp:47:10: fatal error: 'currency/currency.wast.hpp'
      file not found
#include <currency/currency.wast.hpp>
         ^
1 error generated.
```

File `currency.wast.hpp` is available in `build/contracts/currency`, and `test_api.wast.hpp` is available in `build/contracts/test_api` but looks like those locations aren't in include path.

**Comment by wanderingbort** [comment]
I have a related fix incoming.  see https://github.com/wanderingbort/eos/commit/09385a4c8fe9e0396ace8d5a5604003a73f71730

**Comment by brianjohnson5972** [comment]
Dylan,

The issue has been identified and we will let you know when it is committed
to master.

Brian

**Comment by wanderingbort** [comment]
to add notes, this only occurs if you do an out-of-band cmake build.  if you are building inline with the code base, it works just fine.
