### ISSUE TITLE
"EOSLIB_SERIALIZE" Can Construct "Out of Range"

### ISSUE THREAD

**Issue by xiangxn** [EOSIO/eos#3795]
If the order of "EOSLIB_SERIALIZE" is inconsistent with the definition of the structure, it may result in an abnormality in data writing, and it may cause an "out of range" error when reading the data.

I'm not sure if this might be an attack.
code : 
```
struct test {
    uint8_t a;
    vector<uint8_t> b;
    EOSLIB_SERIALIZE(test,(b)(a))
}
```

**Comment by tbfleming** [comment]
The order in EOSLIO_SERIALIZE, if used (it's optional), must match the order in the ABI. It's OK if it doesn't match the order in the struct.

**Comment by xiangxn** [comment]
will be data abnormal,  if it doesn't match the order in the struct.

**Comment by tbfleming** [comment]
It won't if the order in EOSLIB_SERIALIZE matches the order in the abi.
