### ISSUE TITLE
Running bios-boot-tutorial.py in tutorials/bios-boot-tutorial throws ERROR (options configuration file contains an invalid line)

### ISSUE THREAD

**Issue by coosar** [EOSIO/eos#3796]
../../build/programs/nodeos/nodeos    --max-irreversible-block-age 9999999    --contracts-console    --genesis-json /ho
me/stopro/workspace/eos4.0/tutorials/bios-boot-tutorial/genesis.json    --blocks-dir /home/stopro/workspace/eos4.0/tuto
rials/bios-boot-tutorial/nodes/01-producera/blocks    --config-dir /home/stopro/workspace/eos4.0/tutorials/bios-boot-tu
torial/nodes/01-producera    --data-dir /home/stopro/workspace/eos4.0/tutorials/bios-boot-tutorial/nodes/01-producera
  --chain-state-db-size-mb 1024    --http-server-address 127.0.0.1:8001    --p2p-listen-endpoint 127.0.0.1:9001    --ma
x-clients 13    --p2p-max-nodes-per-host 13    --enable-stale-production    --producer-name producera    --private-key
'["EOS8imf2TDq6FKtLZ8mvXPWcd6EF2rQwo8zKdLNzsbU9EiMSt9Lwz","5KLGj1HGRWbk5xNmoKfrcrQHXvcVJBPdAckoiJgFftXSJjLPp7b"]'    --
plugin eosio::http_plugin    --plugin eosio::chain_api_plugin    --plugin eosio::producer_plugin    --p2p-peer-address
localhost:9000

2850867ms thread-0   main.cpp:119                  main                 ] Throw location unknown (consider using BOOST_
THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program
_options::invalid_config_file_syntax> >
std::exception::what: the options configuration file contains an invalid line '(eosio::http_client_plugin)'
---
After dig source code of http_client_plugin, I found that the description of this plugin had an newline character '\n' at end. 
Source file is eos/plugins/http_client_plugin/http_client_plugin.cpp, with Line 17.

Coosar

**Comment by tbfleming** [comment]
This was fixed. Update to the latest tag and remove your nodes/ directory.
