### ISSUE TITLE
Debian

### ISSUE THREAD

**Issue by drandreaskrueger** [EOSIO/eos#3802]
Please support [Debian](https://www.cloudbalkan.com/most-popular-linux-distributions-from-2017/)

```
./eosio_build.sh 

	Beginning build version: 1.2
	Mon  4 Jun 15:13:36 UTC 2018
	git head id: 0961a56007d40fe6d897b7d726fe5005acf06162
	Current branch: master

	ARCHITECTURE: Linux

	Unsupported Linux Distribution. Exiting now.

uname -a
Linux ... 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
```

Thanks.

**Comment by pacificcode** [comment]
@drandreaskrueger Debian is not currently accounted for in our installation procedure. Other options would include Ubuntu or Linux Mint.

**Comment by drandreaskrueger** [comment]
Great way of treating this request /irony.

> Debian is not currently accounted for in our installation procedure.   

yes ... I noticed that. I did. Your script had told me that already.  

Odd project - a DAO-sized amount of Ether taken in, but not enough money to support more than Ubuntu? Sad. And not at all Linux approach. Debian is one of the main distros.


> @pacificcode closed this 17 hours ago

Just closing a valid issue is bad style IMHO. How would I now think it makes sense to even start [contributing](https://github.com/search?utf8=%E2%9C%93&q=issues+author%3Adrandreaskrueger&type=Issues) here ... if you are of that project-type that keeps on closing issues as quickly as possible, to just get them out of the way?

Possible alternative responses could have been:

- answering "... not currently accounted for", but leaving the issue open
- assigning a label "feature request"
- "... have a look at [stackexchange](https://eosio.stackexchange.com/), there might be others with the same question"
- "... not yet, sorry, but I know that John Smith is running Debian too, perhaps he can help. @ john?"
- " ... Ubuntu/Mint are based on Debian, so the differences cannot be big. If you find a solution please pull-request, and inform us here, thanks."
- "... thanks for the suggestion, I have added it to our list of milestones"
- just leaving it fricking open. I am sure you are not the only developer here, right?

A *closed issue* is now helping no one - apart from keeping your open issues count low. However, an *open issue* could become a possible gathering place for Debian devs helping each other to fix this (probably-simple-to-solve) shortcoming. 

my 2billion cents

**Comment by gotope** [comment]
@DanailMinchev 
 
I'm compiling on debian jessie, many error encountered.

**Comment by niclash** [comment]
We are compiling successfully on Debian Testing and managed to set it up to run on Debian Stretch (stable).

For the build changes, see github.com/eosgermany/eos. It is only the eosio_build.sh and the Ubuntu build in scripts/.
For production, need to allow libtinfo6 to be installed from Debian testing, by setting up /etc/apt/preferences. 

Could have been some additional things that slipped my mind right now.

I wouldn't count on getting it working on Jessie

**Comment by gotope** [comment]
@niclash  failed at 78% on Jessie(llvm 6), 
may be I need to upgrade to Stretch to go on.

**Comment by brdelphus** [comment]
Hi can I get the results of make test on debian stretch ? I'm having 6 failures I can't get rid off

**Comment by gituser** [comment]
@drandreaskrueger 
>About the Debian version: Due to its heavy focus on stability, and thus conservative versioning of packages, I don't think many cryptocurrency / blockchain developers can afford to still run Debian Jessie. Many of us will run Debian Stretch by now, it's been stable since last summer. So if you have found the way to install EOS to Debian Stretch, you're already the heros of the week.

No, Debian Jessie is a good choice and _MOST_ cryptocurrencies compile just fine on Debian Jessie.

Sure you can use Debian Stretch but it's newer and might contain more issues. If you have issues with building on Debian Jessie you can use Ubuntu Xenial 16.04 (though  not sure how long it will be supported).

**Comment by MikeC-BC** [comment]
still an absolute nightmare trying to build on Debian 9 Stretch

**Comment by matthewdarwin** [comment]
Until Debian is supported, it does work to compile Ubuntu 18.04 and run the binary on Debian 10.

**Comment by MikeC-BC** [comment]
The same applies to Ubuntu 16.04 and Debian 9.

**Comment by drandreaskrueger** [comment]
Thanks for continuing to fiddle with this.  EOS is not on the top of *my* list at the moment.  But keep me (i.e. this issue) in the loop.  Thanks.
