### ISSUE TITLE
how to get version by nodeos --version

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#3803]
my eos version is dwan-v4.2.0，
eos2@eos2-virtual-machine:~/eos$ nodeos --version
13076119
What is the relationship between dwan-v4.2.0 and 13076119？

How do I determine my version dwan-v4.2.0 through 13076119？？
thanks

**Comment by gleehokie** [comment]
Convert the version that is reported to hexadecimal.  That is the git commit hash.  13076119 is C78697 hex.  Add zeros to the left hand side until you have 8 digits.  Here is the associated commit link https://github.com/EOSIO/eos/commit/00C78697
