### ISSUE TITLE
extended_asset is using EOSLIB_SERIALIZE instead of EOSLIB_SERIALIZE_DERIVED

### ISSUE THREAD

**Issue by leordev** [EOSIO/eos#3804]
@tbfleming  asked me to create this issue.

I’m trying to adapt the issue action to use an extended_asset. the original issue action params body is: 
`{"to":"leo", "quantity": "100 TEST", "memo": "testing tokens"}`

changed to `extended_asset` and tried the below parameters:
`{"to":"leo", "quantity": {"amount": 100, "symbol": "TEST", "contract": "mytest"}, "memo": "testing tokens"}`

But the extended asset is empty, like a brand new one, if I print it, this is what I have: 
`0.0000 SYS@mytest` 

So the contract is working but I’m not being able to set the amount and symbol. Any ideas?

I tried also `"amount": "100 TEST"` and also `"asset": "100 TEST"`.. Nothing... Looks like I'm not being able to set the parent class (asset) attributes.

**Comment by bachvtuan** [comment]
Simple case should not occur in future. should add to test case as well.

**Comment by jcalfee** [comment]
Don't try this, it will not work: `"quantity": "100.0000 SYS@mytest"`

**Comment by gengghaibo** [comment]
How to create your own exchange

**Comment by jgiszczak** [comment]
OBE.  `extended_asset` is no longer a derived struct.
