### ISSUE TITLE
Producer Node wont produce blocks

### ISSUE THREAD

**Issue by ARoomWithABue** [EOSIO/eos#3809]
I’ve recently been attempting to make a private test net with in the servers in our office. I have a full node, and a watcher node that I want to become a BP node. I’ve performed the steps below with no errors, but the watcher node is still not producing blocks. 

Started full node
It’s properly configured to accept new connections
Setup BIOS sequence

Created BP account with staked ram/cpu/net
Transferred initial tokens
Registered account as producer
Verified with ```cleos system listproducers```
Started watcher/bp node
Voted for bp account

**Comment by gleehokie** [comment]
One of the producers needs to start production.  See the -e option.

**Comment by ARoomWithABue** [comment]
Why was this closed? This isn't a resolution to this issue. I already had enable-stall-production set to true on the producer node. Do you have any other suggestions on this issue?

**Comment by leoman70** [comment]
I have the same issue with version 1.4.3  follow the guide https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence only the node_bios is producing block
