### ISSUE TITLE
Why removed the get_transactions?

### ISSUE THREAD

**Issue by Hipponensis** [EOSIO/eos#3823]

**Comment by jgiszczak** [comment]
`get_transaction` is available if you load the `history_api_plugin`.  The `history_plugin` must be configured with a valid `filter-on` option to be enabled.  See Pull Request https://github.com/EOSIO/eos/pull/3821 for details of the current and future formats accepted by the option.

**Comment by Hipponensis** [comment]
get_transaction is not get_transactions

**Comment by spartucus** [comment]
`get_transactions` retrieves trxs from all tracked actions. It is no longger supported in EOS since Dawn4.2.

> We greatly reduced the memory usage of the history plugin by reducing the tracked actions to only those that match explicit filter rules. There is now no way to track all actions since that is susceptible to filling shared_mem.
