### ISSUE TITLE
fc enum_type operator> invalid

### ISSUE THREAD

**Issue by bilibiliChangKai** [EOSIO/eos#3826]

**Comment by bilibiliChangKai** [comment]
From eos/libraries/fc/include/fc/io/enum_type.hpp
26      bool       operator<( EnumType i ) const { return value < i; }
27      bool       operator>( EnumType i ) const { return value < i; }

Is this wrong?

**Comment by heifner** [comment]
Not currently used in EOS.IO.

**Comment by heifner** [comment]
https://github.com/EOSIO/fc/pull/1
