### ISSUE TITLE
Valgrind shows invalid read on message structure

### ISSUE THREAD

**Issue by pavybez** [EOSIO/eos#383]
I tried a quick test with Valgrind and it shows many invalid reads mostly on message structure:

==34131== **Invalid read of size 8**
==34131==    at 0x1AB651F: std::vector<char, std::allocator<char> >::~vector() (in /home/ubuntu/eos/build/programs/eosd/eosd)
==34131==    by 0x1AB4199: eos::types::Message::~Message() (in /home/ubuntu/eos/build/programs/eosd/eosd)
==34131==    by 0x1AD8997: void std::_Destroy<eos::types::Message>(eos::types::Message*) (in /home/ubuntu/eos/build/programs/eosd/eosd)
==34131==    by 0x1ACF469: void std::_Destroy_aux<false>::__destroy<eos::types::Message*>(eos::types::Message*, eos::types::Message*) (in /home/ubuntu/eos/build/programs/eosd/eosd)
==34131==    by 0x1AC5160: void std::_Destroy<eos::types::Message*>(eos::types::Message*, eos::types::Message*) (in /home/ubuntu/eos/build/programs/eosd/eosd)
==34131==    by 0x1ABCCE1: void std::_Destroy<eos::types::Message*, eos::types::Message>(eos::types::Message*, eos::types::Message*, std::allocator<eos::types::Message>&) (in /home/ubuntu/eos/build/programs/eosd/eosd)
==34131==    by 0x1AB67A0: std::vector<eos::types::Message, std::allocator<eos::types::Message> >::~vector() (in /home/ubuntu/eos/build/programs/eosd/eosd)
==34131==    by 0x1AB311D: eos::types::Transaction::~Transaction() (in /home/ubuntu/eos/build/programs/eosd/eosd)

**Comment by jgiszczak** [comment]
Can you be more specific?  I tried a few eosc commands against eosd under valgrind and got a clean bill of health.  No leaks, no invalid reads.  Presumably I didn't try specifically what you did.

**Comment by pavybez** [comment]
I tried today again and realized that these messages are only displayed when you bring down eosd.

**Comment by heifner** [comment]
Old valgrind messages.
