### ISSUE TITLE
can't interact with contract after uploading to local test node

### ISSUE THREAD

**Issue by alzozov** [EOSIO/eos#3831]
eosio 1.0.1

Executing  `cleos push action hello ping '{"author":"alezozov"}' -p alezozov`

getting :

```
Error 3060004: Contract Query Exception
Most likely, the given contract doesnt' exist in the blockchain.
Error Details:
Contract can't be found hello
```

log in nodeos:

```
667533ms thread-0   http_plugin.cpp:396           handle_exception     ] FC Exception encountered while processing chain.abi_json_to_bin: 3060004 contract_query_exception: Contract Query Exception
Contract can't be found hello
    {"contract":"hello"}
    thread-0  chain_plugin.cpp:943 abi_json_to_bin

    {"params.code":"hello","params.action":"ping","params.args":{"author":"alezozov"}}
    thread-0  chain_plugin.cpp:959 abi_json_to_bin

```
contract 

```
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>

class hello : public eosio::contract {
  public:
  
    hello(account_name self)
      :eosio::contract(self)
    {}
 
    /// @abi action
    void ping(account_name author) {
      
      eosio::print("pong");
      
    }
   
};

EOSIO_ABI(hello, (ping))
```

how I start nodeos :

`sudo nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console`

creating account

`alias cleos='cleos --wallet-url http://localhost:8888'`

`cleos wallet unlock --password PW5KFa4RaJhY7qC8uFDZtEsDREdQLMzQV162Yg6YrQyMooFkrtL76`

`cleos create account eosio alezozov EOS8YQzDjLvBKAuuaiaocNaonRpjYVyNjXGpm774ayeZasFwewsQw EOS8NbRFqpckjNDJjiikmYGaTiCDhLf3f43W5CjHTrDivxAR1K5Q9`

uploading contract 

`cleos set contract alezozov hello -p alezozov`

**Comment by moskvanaft** [comment]
@alzozov you need to send messages to the account where you installed the contract:
cleos push action **alezozov** ping '{"author":"alezozov"}' -p alezozov
