### ISSUE TITLE
how does producer node find genesis node

### ISSUE THREAD

**Issue by GeneSourceCode** [EOSIO/eos#3836]
I can't figure out how producer find genesis node in the case of "tutorial bios boot sequence". genesis node is launched without specifying its listening p2p port, so that producer can't specify genesis node's p2p address as peer address. How does producer make it? please give me some hints.

**Comment by rbw3821** [comment]
There is no auto-discovery mechanism.  Basically the producers, including the genesis node, must publish their address info (listening endpoint).  A node can then add that peer using the `--p2p-peer-address` command line option to `nodeos`, or can specify the property in its config.ini file.

**Comment by GeneSourceCode** [comment]
thx
