### ISSUE TITLE
last 6 tests failing

### ISSUE THREAD

**Issue by drandreaskrueger** [EOSIO/eos#3842]
Got myself an Ubuntu 18.04 VirtualBox now, because no [Debian support](https://github.com/EOSIO/eos/issues/3802) yet.

Compilation took several hours, but it went through. Very happy. Soon I can try your tutorials.

However, not all tests are passing with 52da8d5f3faad4b1530a774596cbc97acfba5d93:
```
28/34 Test #28: plugin_test ............................   Passed    0.08 sec
      Start 29: nodeos_run_test
29/34 Test #29: nodeos_run_test ........................***Failed   94.74 sec
      Start 30: nodeos_run_remote_test
30/34 Test #30: nodeos_run_remote_test .................***Failed   94.43 sec
      Start 31: distributed-transactions-test
31/34 Test #31: distributed-transactions-test ..........***Failed   97.53 sec
      Start 32: distributed-transactions-remote-test
32/34 Test #32: distributed-transactions-remote-test ...***Failed   98.28 sec
      Start 33: restart-scenarios-test_hard_replay
33/34 Test #33: restart-scenarios-test_hard_replay .....***Failed   98.09 sec
      Start 34: validate_dirty_db_test
34/34 Test #34: validate_dirty_db_test .................***Failed   95.08 sec

82% tests passed, 6 tests failed out of 34

Total Test time (real) = 1101.52 sec

The following tests FAILED:
	 29 - nodeos_run_test (Failed)
	 30 - nodeos_run_remote_test (Failed)
	 31 - distributed-transactions-test (Failed)
	 32 - distributed-transactions-remote-test (Failed)
	 33 - restart-scenarios-test_hard_replay (Failed)
	 34 - validate_dirty_db_test (Failed)
Errors while running CTest
Makefile:119: recipe for target 'test' failed
make: *** [test] Error 8

```

full log of `./eosio_build.sh`

```
	Beginning build version: 1.2
	Tue Jun  5 14:06:36 UTC 2018
	git head id: 52da8d5f3faad4b1530a774596cbc97acfba5d93
	Current branch: master

	ARCHITECTURE: Linux

	OS name: Ubuntu
	OS Version: 18.04
	CPU speed: 3192.000Mhz
	CPU cores: 3
	Physical Memory: 7096 Mgb
	Disk install: Code
	Disk space total: 219G
	Disk space available: 32G

	Checking for installed dependencies.

	Package clang-4.0 found.
	Package lldb-4.0 found.
	Package libclang-4.0-dev found.
	Package cmake found.
	Package make found.
	Package automake found.
	Package libbz2-dev found.
	Package libssl-dev found.
	Package libgmp3-dev found.
	Package autotools-dev found.
	Package build-essential found.
	Package libicu-dev found.
	Package python2.7-dev found.
	Package python3-dev found.
	Package autoconf found.
	Package libtool found.
	Package curl found.
	Package zlib1g-dev found.
	Package doxygen found.
	Package graphviz found.

	No required dpkg dependencies to install.

	Checking boost library installation.
	Boost found at /root/opt/boost.

	Checking MongoDB installation.
	MongoDB configuration found at /root/opt/mongodb/mongod.conf.

	Checking MongoDB C++ driver installation.
	Mongo C++ driver found at /usr/local/lib/libmongocxx-static.a.

	Checking secp256k1-zkp installation.
	secp256k1 found @ /usr/local/lib.

	Checking for LLVM with WASM support.
	WASM found at /root/opt/wasm/bin.


>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOSIO

>>>>>>>> CMAKE_BUILD_TYPE=Release
>>>>>>>> ENABLE_COVERAGE_TESTING=false
>>>>>>>> DOXYGEN=false

-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
-- Configuring EOSIO on Linux
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using 'SYS' as CORE symbol name
-- Using 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV' as public key for 'eosio' account
-- Using WASM clang => /root/opt/wasm/bin/clang
-- Using WASM llc => /root/opt/wasm/bin/llc
-- Using WASM llvm-link => /root/opt/wasm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Configuring fc to build on Unix/Apple
-- zlib found
-- Configuring Builtins
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   unit_test_framework
--   locale
-- Configuring ChainBase on Linux
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   program_options
--   unit_test_framework
--   locale
-- Configuring AppBase on Linux
-- Git commit revision: 52da8d5f
-- Git commit revision: 52da8d5f
-- Git commit revision: 52da8d5f
-- Configuring done
-- Generating done
-- Build files have been written to: /media/sf_Code/github/non-electron/EOSIO/eos/build
[  0%] Built target asmjs
[  0%] Built target ast
[  0%] Built target wasm
[  0%] Built target cfg
[  1%] Built target support
[  1%] Built target binaryen
[  1%] Built target emscripten-optimizer
[  2%] Built target builtins
[  5%] Built target passes
[  5%] Built target chainbase
[  6%] Built target Platform
[  6%] Built target appbase
[  8%] Built target libc++
[  8%] Built target eosiolib
[ 12%] Built target fc
[ 34%] Built target softfloat
[ 34%] contract...
[ 34%] Built target identity_common
[ 34%] Built target copy_skeleton_contract
[ 34%] Built target identity_interface
[ 34%] Built target test_exchange
[ 34%] Built target print_floats
[ 35%] Built target http_client_plugin
[ 74%] Built target libc
[ 74%] Built target eosio-s2wasm
[ 75%] Built target chainbase_test
[ 75%] Built target test_cypher_suites
[ 75%] Built target Logging
[ 75%] Built target appbase_example
[ 75%] Built target IR
[ 75%] Built target WASM
[ 75%] Built target Runtime
[ 75%] Built target Emscripten
[ 75%] Built target WAST
[ 75%] Built target Disassemble
[ 75%] Built target eosio-wast2wasm
[ 76%] Built target Test
[ 77%] Built target eosio.bios
[ 78%] Built target wavm
[ 78%] Built target eos_utilities
[ 79%] Built target simple.token
[ 79%] Built target eosio.token
[ 79%] Built target eosio.msig
[ 79%] Built target multi_index_test
[ 80%] Built target identity
[ 81%] Built target identity_test
[ 82%] Built target stltest
[ 83%] Built target exchange
[ 83%] Built target test.inline
[ 83%] Built target hello
[ 84%] Built target asserter
[ 84%] Built target infinite
[ 84%] Built target test_api_mem
[ 85%] Built target proxy
[ 86%] Built target test_api
[ 87%] Built target test_api_multi_index
[ 87%] Built target test_api_db
[ 87%] Built target test_ram_limit
[ 87%] Built target noop
[ 88%] Built target dice
[ 88%] Built target tic_tac_toe
[ 89%] Built target payloadless
[ 90%] Built target eosio.system
[ 92%] Built target eosio_chain
[ 93%] Built target abi_generator
[ 93%] Built target chain_plugin
[ 93%] Built target eosio_testing
[ 93%] Built target http_plugin
[ 93%] Built target wallet_plugin
[ 93%] Built target eosio-launcher
[ 94%] Built target eosio-abigen
[ 94%] Built target plugin_test
[ 94%] Built target bnet_plugin
[ 94%] Built target producer_plugin
[ 94%] Built target chain_api_plugin
[ 94%] Built target history_plugin
[ 95%] Built target wallet_api_plugin
[ 95%] Built target txn_test_gen_plugin
[ 95%] Built target db_size_api_plugin
[ 95%] Built target keosd
[ 95%] Built target cleos
[ 97%] Built target unit_test
[ 98%] Built target net_plugin
[ 98%] Built target producer_api_plugin
[100%] Built target history_api_plugin
[100%] Built target net_api_plugin
[100%] Built target nodeos


	 _______  _______  _______ _________ _______
	(  ____ \(  ___  )(  ____ \\__   __/(  ___  )
	| (    \/| (   ) || (    \/   ) (   | (   ) |
	| (__    | |   | || (_____    | |   | |   | |
	|  __)   | |   | |(_____  )   | |   | |   | |
	| (      | |   | |      ) |   | |   | |   | |
	| (____/\| (___) |/\____) |___) (___| (___) |
	(_______/(_______)\_______)\_______/(_______)

	EOSIO has been successfully built. 00:00:30

	To verify your installation run the following commands:

	export PATH=${HOME}/opt/mongodb/bin:$PATH
	/root/opt/mongodb/bin/mongod -f /root/opt/mongodb/mongod.conf &
	cd EOSIO/eos/build; make test

	For more information:
	EOSIO website: https://eos.io
	EOSIO Telegram channel @ https://t.me/EOSProject
	EOSIO resources: https://eos.io/resources/
	EOSIO wiki: https://github.com/EOSIO/eos/wiki

```

**Comment by zhaokanghuiasd** [comment]
I think that you use the server, am I right??

**Comment by drandreaskrueger** [comment]
> I think that you use the server, am I right??

not sure what you mean.

I did something along the lines of 

```
git clone ...
./eosio_build.sh
sudo make install

export PATH=${HOME}/opt/mongodb/bin:$PATH
/root/opt/mongodb/bin/mongod -f /root/opt/mongodb/mongod.conf &
cd EOSIO/eos/build; make test
```

does that help?

**Comment by drandreaskrueger** [comment]
> You might have copies of nodeos or keosd running in the background.  
> If so, you will need to kill these before running the tests.

yes perhaps.

Will have to wait until I am back in the office next week. Then I try again.

**Comment by gateway** [comment]
Im having something similar on mac, after 1.0 to 1.0.1 seems like validate_dirty_db_test is failing.. 

```
35/35 Test #35: validate_dirty_db_test .................***Failed    5.54 sec

97% tests passed, 1 tests failed out of 35

Total Test time (real) = 1203.05 sec

The following tests FAILED:
	 35 - validate_dirty_db_test (Failed)
Errors while running CTest
```
I did ./eosio_build.sh

everything compiled fine.

```
[100%] Built target keosd
[100%] Built target nodeos


	 _______  _______  _______ _________ _______
	(  ____ \(  ___  )(  ____ \\__   __/(  ___  )
	| (    \/| (   ) || (    \/   ) (   | (   ) |
	| (__    | |   | || (_____    | |   | |   | |
	|  __)   | |   | |(_____  )   | |   | |   | |
	| (      | |   | |      ) |   | |   | |   | |
	| (____/\| (___) |/\____) |___) (___| (___) |
	(_______/(_______)\_______)\_______/(_______)

	EOSIO has been successfully built. 00:00:24

	To verify your installation run the following commands:

	/usr/local/bin/mongod -f /usr/local/etc/mongod.conf &
	cd /Volumes/Data/EOS/eos/build; make test

	For more information:
	EOSIO website: https://eos.io
	EOSIO Telegram channel @ https://t.me/EOSProject
	EOSIO resources: https://eos.io/resources/
	EOSIO Stack Exchange: https://eosio.stackexchange.com
	EOSIO wiki: https://github.com/EOSIO/eos/wiki


```
ran 

```	/usr/local/bin/mongod -f /usr/local/etc/mongod.conf &
	cd /Volumes/Data/EOS/eos/build; make test```

failed on last test..

**Comment by drandreaskrueger** [comment]
> You might have copies of nodeos or keosd running in the background.  
> If so, you will need to kill these before running the tests.

Gotcha. Redone, like this:

```
sudo pkill nodeos; sudo pkill keosd

export PATH=${HOME}/opt/mongodb/bin:$PATH
/root/opt/mongodb/bin/mongod -f /root/opt/mongodb/mongod.conf &
cd build; make test
```

the result is the same though:

```

Running tests...
Test project /media/sf_Code/...../EOSIO/eos/build
      Start  1: test_cypher_suites
 1/34 Test  #1: test_cypher_suites .....................   Passed    0.07 sec
      Start  2: validate_simple.token_abi
 2/34 Test  #2: validate_simple.token_abi ..............   Passed    0.04 sec
      Start  3: validate_eosio.token_abi
 3/34 Test  #3: validate_eosio.token_abi ...............   Passed    0.04 sec
      Start  4: validate_eosio.msig_abi
 4/34 Test  #4: validate_eosio.msig_abi ................   Passed    0.04 sec
      Start  5: validate_multi_index_test_abi
 5/34 Test  #5: validate_multi_index_test_abi ..........   Passed    0.04 sec
      Start  6: validate_eosio.system_abi
 6/34 Test  #6: validate_eosio.system_abi ..............   Passed    0.04 sec
      Start  7: validate_identity_abi
 7/34 Test  #7: validate_identity_abi ..................   Passed    0.04 sec
      Start  8: validate_identity_test_abi
 8/34 Test  #8: validate_identity_test_abi .............   Passed    0.04 sec
      Start  9: validate_stltest_abi
 9/34 Test  #9: validate_stltest_abi ...................   Passed    0.04 sec
      Start 10: validate_exchange_abi
10/34 Test #10: validate_exchange_abi ..................   Passed    0.04 sec
      Start 11: validate_test.inline_abi
11/34 Test #11: validate_test.inline_abi ...............   Passed    0.04 sec
      Start 12: validate_hello_abi
12/34 Test #12: validate_hello_abi .....................   Passed    0.04 sec
      Start 13: validate_asserter_abi
13/34 Test #13: validate_asserter_abi ..................   Passed    0.04 sec
      Start 14: validate_infinite_abi
14/34 Test #14: validate_infinite_abi ..................   Passed    0.04 sec
      Start 15: validate_proxy_abi
15/34 Test #15: validate_proxy_abi .....................   Passed    0.04 sec
      Start 16: validate_test_api_abi
16/34 Test #16: validate_test_api_abi ..................   Passed    0.04 sec
      Start 17: validate_test_api_mem_abi
17/34 Test #17: validate_test_api_mem_abi ..............   Passed    0.04 sec
      Start 18: validate_test_api_db_abi
18/34 Test #18: validate_test_api_db_abi ...............   Passed    0.04 sec
      Start 19: validate_test_api_multi_index_abi
19/34 Test #19: validate_test_api_multi_index_abi ......   Passed    0.04 sec
      Start 20: validate_test_ram_limit_abi
20/34 Test #20: validate_test_ram_limit_abi ............   Passed    0.04 sec
      Start 21: validate_eosio.bios_abi
21/34 Test #21: validate_eosio.bios_abi ................   Passed    0.04 sec
      Start 22: validate_noop_abi
22/34 Test #22: validate_noop_abi ......................   Passed    0.04 sec
      Start 23: validate_dice_abi
23/34 Test #23: validate_dice_abi ......................   Passed    0.04 sec
      Start 24: validate_tic_tac_toe_abi
24/34 Test #24: validate_tic_tac_toe_abi ...............   Passed    0.04 sec
      Start 25: validate_payloadless_abi
25/34 Test #25: validate_payloadless_abi ...............   Passed    0.04 sec
      Start 26: unit_test_binaryen
26/34 Test #26: unit_test_binaryen .....................   Passed   99.18 sec
      Start 27: unit_test_wavm
27/34 Test #27: unit_test_wavm .........................   Passed  379.82 sec
      Start 28: plugin_test
28/34 Test #28: plugin_test ............................   Passed    0.09 sec
      Start 29: nodeos_run_test
29/34 Test #29: nodeos_run_test ........................***Failed   93.91 sec
      Start 30: nodeos_run_remote_test
30/34 Test #30: nodeos_run_remote_test .................***Failed   94.05 sec
      Start 31: distributed-transactions-test
31/34 Test #31: distributed-transactions-test ..........***Failed   97.27 sec
      Start 32: distributed-transactions-remote-test
32/34 Test #32: distributed-transactions-remote-test ...***Failed   97.82 sec
      Start 33: restart-scenarios-test_hard_replay
33/34 Test #33: restart-scenarios-test_hard_replay .....***Failed   97.44 sec
      Start 34: validate_dirty_db_test
34/34 Test #34: validate_dirty_db_test .................***Failed   94.04 sec

82% tests passed, 6 tests failed out of 34

Total Test time (real) = 1054.91 sec

The following tests FAILED:
	 29 - nodeos_run_test (Failed)
	 30 - nodeos_run_remote_test (Failed)
	 31 - distributed-transactions-test (Failed)
	 32 - distributed-transactions-remote-test (Failed)
	 33 - restart-scenarios-test_hard_replay (Failed)
	 34 - validate_dirty_db_test (Failed)
Errors while running CTest
Makefile:119: recipe for target 'test' failed
make: *** [test] Error 8
```

nope, sorry - the problem persists.

**Comment by drandreaskrueger** [comment]
### Tried again with newer commit.

Rebooted the Ubuntu VM, then rebuilt with newer code:

```
git pull
git submodule update --init --recursive

sudo apt update && sudo apt upgrade

./eosio_build.sh 
```

```
	Beginning build version: 1.2
	Mon Jun 11 09:02:11 UTC 2018
	User: root
	git head id: ade08c5d9775cac4ebfe2a3f8571dedf299be222
	Current branch: master

	...

```
then
```
cd build
sudo make install
```
then the test
```
export PATH=${HOME}/opt/mongodb/bin:$PATH
/root/opt/mongodb/bin/mongod -f /root/opt/mongodb/mongod.conf &
cd /media/sf_Code/github/non-electron/EOSIO/eos/build; make test
```

result now is 

```
make test
Running tests...
Test project /media/sf_Code/github/non-electron/EOSIO/eos/build
      Start  1: test_cypher_suites
 1/35 Test  #1: test_cypher_suites ...................   Passed    0.05 sec
      Start  2: validate_simple.token_abi
...
26/35 Test #26: unit_test_binaryen ...................   Passed  100.44 sec
      Start 27: unit_test_wavm
27/35 Test #27: unit_test_wavm .......................   Passed  389.38 sec
      Start 28: validate_deferred_test_abi
28/35 Test #28: validate_deferred_test_abi ...........   Passed    0.05 sec
      Start 29: plugin_test
29/35 Test #29: plugin_test ..........................   Passed    0.21 sec
      Start 30: nodeos_run_test
30/35 Test #30: nodeos_run_test ......................***Failed   94.98 sec
      Start 31: p2p_dawn515_test
31/35 Test #31: p2p_dawn515_test .....................   Passed    8.36 sec
      Start 32: distributed-transactions-test
32/35 Test #32: distributed-transactions-test ........***Failed  102.22 sec
      Start 33: restart-scenarios-test-resync
33/35 Test #33: restart-scenarios-test-resync ........***Failed   97.82 sec
      Start 34: restart-scenarios-test-hard_replay
34/35 Test #34: restart-scenarios-test-hard_replay ...***Failed   98.16 sec
      Start 35: validate_dirty_db_test
35/35 Test #35: validate_dirty_db_test ...............***Failed   94.85 sec

86% tests passed, 5 tests failed out of 35

Total Test time (real) = 987.78 sec

The following tests FAILED:
	 30 - nodeos_run_test (Failed)
	 32 - distributed-transactions-test (Failed)
	 33 - restart-scenarios-test-resync (Failed)
	 34 - restart-scenarios-test-hard_replay (Failed)
	 35 - validate_dirty_db_test (Failed)
Errors while running CTest
Makefile:119: recipe for target 'test' failed
make: *** [test] Error 8
```

so even with a new commit ... 5 tests are failing.

**Comment by lazaridiscom** [comment]
@drandreaskrueger , did you finally got it working?

If not, you may find a hint here:

https://github.com/EOSIO/eos/issues/4765#issuecomment-408574127

**Comment by lazaridiscom** [comment]
Similar test-failurers within https://github.com/EOSIO/eos/issues/4883#issuecomment-408137129 and #4758

**Comment by zillerium** [comment]
I get the same issue; was this resolved?
The following tests FAILED:
	 31 - nodeos_sanity_test (Failed)
	 32 - nodeos_run_test (Failed)
	 34 - nodeos_run_test-mongodb (Failed)
	 35 - distributed-transactions-test (Failed)
	 36 - restart-scenarios-test-resync (Failed)
	 37 - restart-scenarios-test-hard_replay (Failed)
	 38 - restart-scenarios-test-none (Failed)
	 39 - validate_dirty_db_test (Failed)
	 40 - nodeos_sanity_lr_test (Failed)
	 41 - nodeos_voting_lr_test (Failed)
Errors while running CTest
Makefile:119: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by Drug0j** [comment]
28/45 Test #28: unit_test_binaryen ...................***Failed   10.92 sec
      Start 29: unit_test_wavm
29/45 Test #29: unit_test_wavm .......................***Failed   10.91 sec
      Start 30: validate_deferred_test_abi
30/45 Test #30: validate_deferred_test_abi ...........   Passed    0.03 sec
      Start 31: plugin_test
31/45 Test #31: plugin_test ..........................***Failed    0.12 sec

**Comment by Drug0j** [comment]
yesterday's log file with errors was significantly larger, in particular, not the test of the node ended too unsuccessfully. I was able to create a wallet to import the key. but the node does not start, the log of its launch contains ./start.sh: line 22: ~/admin/eos/build/programs/nodeos/nodeos: No such file or d$

**Comment by Drug0j** [comment]
far test contains more errors
far test contains more errors

43/45 Test 43: nodeos_voting_lr_test ................***Failed   76.13 sec
      Start 44: bnet_nodeos_voting_lr_test
44/45 Test 44: bnet_nodeos_voting_lr_test ...........***Failed    0.35 sec

**Comment by Drug0j** [comment]
[footer.txt](https://github.com/EOSIO/eos/files/2336372/footer.txt)

**Comment by lazaridiscom** [comment]
try again with an update to latest:

```bash
# within your eos dir
git pull
git submodule update --init --recursive

sudo ./eosio_uninstall.sh
./eosio_build.sh 
sudo ./eosio_install.sh

cd build
make test
```

**Comment by Drug0j** [comment]
Total Test time (real) = 2039.24 sec

The following tests FAILED:
	 28 - unit_test_binaryen (Failed)
	 29 - unit_test_wavm (Failed)
	 31 - plugin_test (Failed)
	 32 - nodeos_sanity_test (Failed)
	 36 - nodeos_run_test-mongodb (Failed)
	 38 - restart-scenarios-test-resync (Failed)
	 39 - restart-scenarios-test-hard_replay (Failed)
	 45 - bnet_nodeos_voting_lr_test (Failed)
Errors while running CTest
Makefile:119: recipe for target 'test' failed
make: *** [test] Error 8
root@goeoslottery:~/eos/build# packet_write_wait: Connection to 1.1.1.1 port 22: Broken pipe

**Comment by Drug0j** [comment]
cd /path/to/eos
./eosio_build.sh
~/opt/mongodb/bin/mongod -f ~/opt/mongodb/mongod.conf &
cd build
make install
make test

**Comment by Drug0j** [comment]
28/46 Test #28: unit_test_binaryen ...................***Failed    9.41 sec
      Start 29: unit_test_wavm
29/46 Test #29: unit_test_wavm .......................***Failed    9.34 sec
      Start 30: validate_deferred_test_abi
30/46 Test #30: validate_deferred_test_abi ...........   Passed    0.03 sec
      Start 31: plugin_test
31/46 Test #31: plugin_test ..........................***Failed    0.11 sec
      Start 32: nodeos_sanity_test
32/46 Test #32: nodeos_sanity_test ...................   Passed    2.38 sec
      Start 33: nodeos_run_test
33/46 Test #33: nodeos_run_test ......................   Passed   62.33 sec
      Start 34: bnet_nodeos_run_test
34/46 Test #34: bnet_nodeos_run_test .................   Passed   62.62 sec
      Start 35: p2p_dawn515_test
35/46 Test #35: p2p_dawn515_test .....................   Passed    8.12 sec
      Start 36: nodeos_run_test-mongodb
36/46 Test #36: nodeos_run_test-mongodb ..............***Failed    0.29 sec
      Start 37: distributed-transactions-test
37/46 Test #37: distributed-transactions-test ........   Passed   74.55 sec
      Start 38: restart-scenarios-test-resync
38/46 Test #38: restart-scenarios-test-resync ........***Failed    0.51 sec
      Start 39: restart-scenarios-test-hard_replay

**Comment by Drug0j** [comment]
39/46 Test #39: restart-scenarios-test-hard_replay ...***Failed  192.94 sec
      Start 40: restart-scenarios-test-none
40/46 Test #40: restart-scenarios-test-none ..........***Failed    0.38 sec

**Comment by Drug0j** [comment]
Ubunt 18.04

**Comment by Drug0j** [comment]
ps -la
F S   UID   PID  PPID  C PRI  NI ADDR SZ WCHAN  TTY          TIME CMD
0 S     0 31740 16105  0  80   0 - 245670 futex_ pts/1   00:00:06 mongod
0 S     0 37459     1  0  80   0 -  9845 ep_pol pts/1    00:00:00 keosd
0 R     0 37462 16105  0  80   0 -  7220 -      pts/1    00:00:00 ps

**Comment by Drug0j** [comment]
f...k ................. /..... node!

**Comment by Drug0j** [comment]
we fix the error of the head unit, the solution  ./nodeos --delete-all-blocks --genesis-json genesis.json
2018-08-31T16:54:07.128 thread-0   chain_plugin.cpp:317          plugin_initialize    ] initializing chain plugin
2018-08-31T16:54:07.128 thread-0   chain_plugin.cpp:456          plugin_initialize    ] Deleting state database and blocks
2018-08-31T16:54:07.193 thread-0   chain_plugin.cpp:632          plugin_initialize    ] 3110006 plugin_config_exception: Incorrect plugin configuration
Specified genesis file '/root/eos/build/programs/nodeos/genesis.json' does not exist.
    {"genesis":"/root/eos/build/programs/nodeos/genesis.json"}
    thread-0  chain_plugin.cpp:532 plugin_initialize

**Comment by Drug0j** [comment]
F S   UID   PID  PPID  C PRI  NI ADDR SZ WCHAN  TTY          TIME CMD
4 -     0 16105 16007  0   -   - -  5921 -      pts/1    00:00:00 bash
4 S     0     -     -  0  80   0 -     - wait   -        00:00:00 -
0 -     0 31740 16105  0   -   - - 245944 -     pts/1    00:00:21 mongod
0 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - sigtim -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:01 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - hrtime -        00:00:01 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:14 -
1 S     0     -     -  0  80   0 -     - hrtime -        00:00:00 -
1 S     0     -     -  0  80   0 -     - hrtime -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - ep_pol -        00:00:00 -
1 S     0     -     -  0  80   0 -     - futex_ -        00:00:00 -
1 S     0     -     -  0  80   0 -     - ep_pol -        00:00:00 -
0 -     0 42705 16105  0   -   - -  7220 -      pts/1    00:00:00 ps
0 R     0     -     -  0  80   0 -     - -      -        00:00:00 -

**Comment by lazaridiscom** [comment]
@drandreaskrueger , latest versions should work better, see https://github.com/EOSIO/eos/issues/3842#issuecomment-417348636

**Comment by Drug0j** [comment]
eeeee .   F S   UID   PID  PPID  C PRI  NI ADDR SZ WCHAN  TTY          TIME CMD
4 S     0 16206 10271  0  80   0 - 376451 ep_pol pts/0   00:00:00 nodeos
0 R     0 16211 15458  0  80   0 -  7220 -      pts/1    00:00:00 ps
root@goeoslottery:~#

**Comment by Drug0j** [comment]
the best I

**Comment by lazaridiscom** [comment]
@taokayan , seems @Drug0j is a bit out of control...

**Comment by Drug0j** [comment]
did not understand you?
it all worked for me
F S UID PID PPID C PRI NI ADDR SZ WCHAN TTY TIME CMD
0 S 0 31398 1 0 80 0 - 9845 ep_pol pts / 1 00:00:00 keosd
4 S 0 34024 1 0 80 0 - 17030915 ep_pol pts / 1 00:00:06 nodeos
0 R 0 40480 31197 0 80 0 - 7220 - pts / 1 00:00:00 ps

thanks for the help ... :-P

**Comment by jgiszczak** [comment]
Addressed in #5525.

**Comment by Drug0j** [comment]
HI! decided to update, problem again
[1]+  Killed                  /root/opt/mongodb/bin/mongod -f /root/opt/mongodb/mongod.conf  (wd: ~/eos/build)
(wd now: ~/eos/build/programs/nodeos)
Killed
2018-09-11T22:10:06.669 thread-0   chain_plugin.cpp:317          plugin_initialize    ] initializing chain plugin
2018-09-11T22:10:06.679 thread-0   chain_plugin.cpp:556          plugin_initialize    ] Starting up fresh blockchain with default genesis state.
Killed

**Comment by jgiszczak** [comment]
@Drug0j Your kernel is killing the process because it is trying to lock a great deal of memory.  Update to v1.2.5, released yesterday.  It reverts the memory locking behavior, which should allow your node to continue running.

**Comment by Drug0j** [comment]
Hi my version 1.2.4

**Comment by Drug0j** [comment]
Here is the error that I now see quite often                  2018-09-13T19:25:25.613 thread-0   controller.cpp:688            push_scheduled_trans ] 3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
assertion failure with message: refund request not found
    {"s":"refund request not found"}
    thread-0  wasm_interface.cpp:930 eosio_assert
pending console output: 
    {"console":""}
    thread-0  apply_context.cpp:61 exec_one
