### ISSUE TITLE
has risk to be overflowed one byte

### ISSUE THREAD

**Issue by gpmn** [EOSIO/eos#3843]
https://github.com/EOSIO/eos/blob/8432531941da605cf542d3efc602dd40880279e8/libraries/chain/name.cpp#L11

'<= 13' should be changed to '< 13'

here may leak one byte in some other place if it is not taken properly.

the following log shows the different behavior. 

luckily apply_eosio_newaccount check out, but not every following process will be so lucky. so it's better to fix it, I suppose.

`
root@c492688bf98b:/# cleos create account eosio abc123451234512 EOS7mj34KXtiPf22n6XKXW9ArXpkKfcAP9zA4JgGofQWGcAFwTNRp
Error 3010001: Invalid name
Name should be less than 13 characters and only contains the following symbol .12345abcdefghijklmnopqrstuvwxyz
Error Details:
Name is longer than 13 characters (abc123451234512) 
root@c492688bf98b:/# cleos create account eosio abc1234512345 EOS7mj34KXtiPf22n6XKXW9ArXpkKfcAP9zA4JgGofQWGcAFwTNRp
Error 3050000: action exception
Error Details:
account names can only be 12 chars long
`

**Comment by arhag** [comment]
The `uint64_t` naming scheme we use allows up to 13 character names where the first 12 characters can be from the set `{'.', '1', '2', '3', '4', '5', 'a', ..., 'z'}` and the 13th character can be from the set `{'.', '1', '2', '3', '4', '5', 'a', ..., 'j'}`.

This naming scheme is used in many places in EOSIO: action names, scope names, table names, etc. Some names, like account names, have stricter restrictions. For example, as you noticed, the native action handler enforces a maximum limit of 12 characters on account names.

However, generally a `name` type (which the code you referenced handles) needs to be able to support the  13th character.

**Comment by gpmn** [comment]
got it!
thank you!
