### ISSUE TITLE
please add instructions how to read eosio.token balances

### ISSUE THREAD

**Issue by drandreaskrueger** [EOSIO/eos#3845]
Directly below this chapter ["Transfer Tokens to Account Tester"](https://github.com/EOSIO/eos/wiki/Tutorial-eosio-token-Contract#transfer-tokens-to-account-tester) 

it makes sense to explain how the **balances can be read** from the smart contract `eosio.token`. Either the balances of *all* token owners, or the balance of a *given account*, e.g. "user" or "tester"

Looking at the [contracts/eosio.token/eosio.token.abi](https://github.com/EOSIO/eos/blob/master/contracts/eosio.token/eosio.token.abi), I would assume it should look similar to this
```
cleos get table eosio.token "" accounts
```
but I cannot find the correct syntax, sorry. It comes back empty. What is the "scope" ?
```
{
  "rows": [],
  "more": false
}
```

Please add a hint into your https://github.com/EOSIO/eos/wiki/Tutorial-eosio-token-Contract

thanks.

**Comment by drandreaskrueger** [comment]
along the same thinking, when walking through your tutorial, there is nothing new happening in the chapters 

* Deploy Exchange Contract
* Deploy multisignature contract

because that are simply deploying two more contracts `build/contracts/exchange` and `build/contracts/eosio.msig` but then there are no examples given how to interact with those contracts.

so, what about for each giving a few more commands which demonstrate how to interact with those contracts?

**Comment by xianxun002** [comment]
code - the account name which has write permission
**scope** - an account where the data is stored
table - a name for the table that is being stored
record - a row in the table

**Comment by drandreaskrueger** [comment]
thx @xianxun002 

what is the exact command to read the token balance of an account?

like

     cleos push action eosio.token transfer '[ "user", "tester", "25.0000 SYS", "m" ]' -p user

is for transfer

**Comment by Velua** [comment]
Try something like this, questions like this can also be asked in the eosio stack exchange. 

`$ cleos get currency balance eosio.token mary
25.0000 EOS`

**Comment by drandreaskrueger** [comment]
yes, that's it

```
cleos get currency balance eosio.token tester
25.0000 SYS

cleos get currency balance eosio.token user
75.0000 SYS
```
thanks.


TODO: please add those commands to the instructions manual below this chapter here:

https://github.com/EOSIO/eos/wiki/Tutorial-eosio-token-Contract#transfer-tokens-to-account-tester

then: CanClose.

**Comment by taokayan** [comment]
cleos get currency balance eosio.token <accountName>

**Comment by drandreaskrueger** [comment]
Thanks @taokayan, or @Velua, or @xianxun002

PLEASE ADD THAT COMMAND [TO THE TUTORIAL HERE](https://github.com/EOSIO/eos/wiki/Tutorial-eosio-token-Contract#transfer-tokens-to-account-tester).

Thx
