### ISSUE TITLE
When I run smart contract , print doesn't work.

### ISSUE THREAD

**Issue by qq1032246642** [EOSIO/eos#3855]
`#include <eosiolib/eosio.hpp>
  
class debug : public eosio::contract {
  public:
      using contract::contract;

      // @abi action
      void debugfunc( account_name from, account_name to, uint64_t amount ) {
         auto header = "======== debugfunc ========";
         eosio::print( header, "\n" );
         eosio::print( "from = ", from, "  to = ", to, "  amount = ", amount, "\n" );
         eosio::print( "from = ", eosio::name{from}, "  to = ", eosio::name{to}, "  amount = ", amount, "\n" );
      }
};

EOSIO_ABI( debug, (debugfunc) )`

'wuyuans-MacBook-Pro:debug wuyuan$ cleos push action helleos debugfunc  '["tom","jerry",200]' -p helloman
executed transaction: dd64468125d587d7caf3c910b2cba1bffc1345f95f844fd2168cd512676698be  120 bytes  333 us
#       helleos <= helleos::debugfunc           {"from":"tom","to":"jerry","amount":200}
warning: transaction executed locally, but may not be confirmed by the network yet'

**Comment by AIYP1226** [comment]
The version before dawn-v4.10 can only be printed

**Comment by qq1032246642** [comment]
if i want print data， what should I do？

**Comment by andriantolie** [comment]
Try to set `contracts-console` in your config.ini to true

**Comment by qq1032246642** [comment]
It's work.  Thank you.
