### ISSUE TITLE
config.ini - account_history_api_plugin

### ISSUE THREAD

**Issue by ratwill** [EOSIO/eos#3860]
Default plugins within the config.ini file contains "account_history_api_plugin", and should be changed to "history_api_plugin" in order for nodeos to run properly when setting up local testnet

**Comment by heifner** [comment]
Where? I don't see this.

**Comment by taokayan** [comment]
Does this issue still exist?

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
