### ISSUE TITLE
Unstaking balance not changed after undelegatebw executed

### ISSUE THREAD

**Issue by LanfordCai** [EOSIO/eos#3863]
**Testnet**: Jungle
**EOS Ver**: 1.0.1

**Description**:

After undelegatebw executed, I checked the delegated bandwidth balance by "get account" and "system listbw", it did change. But in the voter_info part of "get account", the unstaking balance is always 0.0000 EOS, and deferred_trx_id is always 0. As I expected, after undelegatebw executed, I should see the field "unstaking" changed...

**Comment by moskvanaft** [comment]
@LanfordCai I assume found "unstaking" in JSON output (with `-j`).  The "unstaking" field in voter_info is not in use. It was used in the old version, but then we just forgot to remove it. It's always zero.

**Comment by moskvanaft** [comment]
same for deferred_trx_id - it's unused field

**Comment by LanfordCai** [comment]
@moskvanaft For current version, how can I get my unstaking balance?
