### ISSUE TITLE
Wrong Information in the Wiki - cleos wallet private_keys

### ISSUE THREAD

**Issue by HomoEfficio** [EOSIO/eos#3867]
https://github.com/EOSIO/eos/wiki/CLI%20Wallet#publicprivate-key-pairs

The command `cleos wallet private_keys` above does not exist.

So it should be removed from the Wiki page.

**Comment by spartucus** [comment]
Yes, it deos. `private_keys` is a protection from command line display of private keys.

see:
```
bob@VirtualBox:/home/bob/eosio-wallet$ cleos wallet keys
[
  "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"
]
bob@VirtualBox:/home/bob/eosio-wallet$ cleos wallet private_keys
password: [[
    "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
    "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
  ]
]
```

**Comment by spartucus** [comment]
the commit id i'm using is 379cb1a9e2a6557221d946eef4c5c83ddd156799.

**Comment by HomoEfficio** [comment]
Close this issue because It works in EOSIO 1.0.2.  Good Job!

![Imgur](https://i.imgur.com/Yg8txNf.png)
