### ISSUE TITLE
can't deploy on multiple machines following the official tutorial

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#3869]
I follow the intructions on tutorial bios boot sequence, but deploy producers on different machines. Everything goes smoothly until I call voteproducer from producer side. I get the following error

> Error 3050000: action exception                                                                                                                                       
Error Details:                                                                                                                                                        
Unknown action voteproducer in contract eosio

I am not sure whether it is caused by authority contraint or connection problem between producers and genesis. How can I deal with the problem or do i need to provide more information? Thx

**Comment by jgiszczak** [comment]
Closing in favor of #3871.
