### ISSUE TITLE
bnet plugin turn off node after get 320 blocks on V1.0.1

### ISSUE THREAD

**Issue by rommzestz** [EOSIO/eos#3872]
if i add bnet plugin , and after get 320 blocks - it node turn off and not response

0:02:57.500 signed by eosio [trxs: 0, lib: 317, conf: 0, latency: 2 ms]
178002ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block cefa2bcf453a5932... #319 @ 2018-06-06T10:02:58.000 signed by eosio [trxs: 0, lib: 318, conf: 0, latency: 2 ms]
178502ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 53b432ee626690d9... #320 @ 2018-06-06T10:02:58.500 signed by eosio [trxs: 0, lib: 319, conf: 0, latency: 2 ms]
179001ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block cc78c876f052391f... #321 @ 2018-06-06T10:02:59.000 signed by eosio [trxs: 0, lib: 320, conf: 0, latency: 2 ms]
179175ms thread-0   bnet_plugin.cpp:1166          on_reconnect_peers   ] attempt to connect to 000000:7272
179176ms thread-0   bnet_plugin.cpp:298           session              ] open session 16

**Comment by rommzestz** [comment]
it not fixed. 
every i get segmentation fail and node stopped

**Comment by taokayan** [comment]
Can you try with the latest version to see if this issue still happens?

**Comment by rommzestz** [comment]
Yes, lets my check it

**Comment by matthewdarwin** [comment]
I'm running bnet on multiple nodes on v1.1.0... seems to be working ok.

**Comment by lazaridiscom** [comment]
@rommzestz , if this works for you now, please close this issue.

**Comment by rommzestz** [comment]
Hi! Darwin, can you tell my default config with enabled bnet plugin?  Just
now and with 1.1.0v it stopped ......

**Comment by rommzestz** [comment]
i am get it log

 on_reconnect_peers   ] attempt to connect to *****:3777
1845979ms thread-0   bnet_plugin.cpp:349           session              ] open session 216
1845979ms thread-0   bnet_plugin.cpp:1260          on_reconnect_peers   ] attempt to connect to 190.2.133.25:7770
1845979ms thread-0   bnet_plugin.cpp:349           session              ] open session 217
1845979ms thread-3   bnet_plugin.cpp:860           on_fail              ] connect: Connection refused
1845979ms thread-3   bnet_plugin.cpp:1444          ~session             ] close session 216

**Comment by rommzestz** [comment]
yes..... few nodes stopped with enabled bnet plugin

**Comment by taokayan** [comment]
We haven't received any update for this. Please try to use p2p plugin instead. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
