### ISSUE TITLE
create account fail！

### ISSUE THREAD

**Issue by OuterSpaceTears** [EOSIO/eos#3874]
After updating to the latest version.
`
cleos create account eosio eosio.bpay EOS8kZRKTXpLozY182AtdvjZyEEwz96vvFvJttj7nbKc3N27s35wg EOS8kZRKTXpLozY182AtdvjZyEEwz96vvFvJttj7nbKc3N27s35wg
3381760ms thread-0   main.cpp:2584                 main                 ] Failed with error: Bad Cast (7)
Invalid cast from type 'string_type' to Object

`

**Comment by heifner** [comment]
Restart your keosd
