### ISSUE TITLE
cleos get transferaction  null

### ISSUE THREAD

**Issue by OuterSpaceTears** [EOSIO/eos#3875]
Change 1 to  transaction_id, and you won't get any trading information.
`cleos get transaction  1
{
  "id": "1000000000000000000000000000000000000000000000000000000000000000",
  "trx": null,
  "block_time": "2000-01-01T00:00:00.000",
  "block_num": 0,
  "last_irreversible_block": 2354,
  "traces": []
}
`

**Comment by wanderingbort** [comment]
closing this in favor of #3887 which provides the same error with more information.
