### ISSUE TITLE
511471ms thread-0   controller.cpp:261            ~controller_impl     ] db.revision(): 36 head->block_num: 36 blog.read_head()->block_num(): 35 

### ISSUE THREAD

**Issue by EfstaMits** [EOSIO/eos#3876]
after installing everything and trying to run the single node , when i run and then when i close the node i get these error, does anyone knows why?
![34691807_10216512881753853_3385903142422970368_n](https://user-images.githubusercontent.com/31578222/41037807-48d3acfc-698c-11e8-9429-07963378f628.png)
![34484116_10216512881673851_8840064253139353600_n](https://user-images.githubusercontent.com/31578222/41037813-4d5bf4aa-698c-11e8-9637-5e3c51e18311.png)

**Comment by wanderingbort** [comment]
These are spurious log messages left in from debugging efforts that we should remove.

**Comment by Drug0j** [comment]
log_guard_exception  ] Details: 3060101 database_guard_exception: Database usage is at unsafe levels
database free: 134217136, guard size: 134217728
    {"f":134217136,"g":134217728}
    thread-0  controller.cpp:1867 validate_db_available_size
2018-09-25T21:21:20.038 thread-0   net_plugin.cpp:3039
