### ISSUE TITLE
Race Condition - CWE362

### ISSUE THREAD

**Issue by teamwoot** [EOSIO/eos#3880]
Hi Team,

While analyzing the code for `filesystem.cpp` at Line 281 `https://github.com/EOSIO/eos/blob/master/libraries/fc/src/filesystem.cpp#L281`

i.e

`void chmod( const path& p, int perm )`

This accepts filename arguments. Use fchmod( ) instead.

Regards
Team w00t

**Comment by taokayan** [comment]
What's the actual benefit of changing chmod into fchmod? Doesn't the file need to be somehow opened using the file path anyway?

**Comment by brianjohnson5972** [comment]
Needed more information about this potential problem, but the issue has gone silent for several months.  Closing.
