### ISSUE TITLE
GetTransaction trx is null

### ISSUE THREAD

**Issue by igorls** [EOSIO/eos#3887]
After calling `cleos get transaction` on a valid hash (extracted from get block N), the output always give

```
"trx": null,
"block_time": "2000-01-01T00:00:00.000",
"block_num": 0,
````
`cleos version client = 1a27ee3a`
`nodeos = 438824506`

Plugins
```
plugin = eosio::chain_api_plugin
plugin = eosio::history_api_plugin
plugin = eosio::history_plugin
```

Same output is given using eosjs v14.1.0

**Comment by Duffyxx** [comment]
I get the same problem, and I can't get any print information after I push an action.

**Comment by OuterSpaceTears** [comment]
When I used another colleague's computer, there was no problem.

**Comment by cookedsteak** [comment]
I tried to restart nodeos with adding "--filter-on=*",  and it works.

**Comment by str** [comment]
OK, so the node needs to have the filter set to capture the information. Maybe nodeos should return

`trx: {error: "filter not set to capture this transaction"}`

Or something similar.
