### ISSUE TITLE
exchange_tutorial.py is out of date

### ISSUE THREAD

**Issue by rbw3821** [EOSIO/eos#3889]
It currently still uses "EOS" instead of "SYS" for the token name.  It also uses an account name ("exchange") that conflicts when tutorials are done in the flow implied in the documentation (i.e., one of the tutorials specifies to create an "exchange" account and load the "exchange" contract--this is not the same account as is intended for use with the exchange deposit withdraw tutorial and script, so the name in the tutorial was changed to "tokenxchange" to remove the conflict.  However, changing the account name breaks the script.

**Comment by brianjohnson5972** [comment]
It looks like exchange_tutorial.py was changed and this issue was not updated. Closing
