### ISSUE TITLE
connection related error messages need improvement

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#3890]
My nodeos log file is full of messages of the type:

2513445ms thread-0   net_plugin.cpp:1894           connect              ] Skipping connect due to go_away reason wrong chain
2483443ms thread-0   net_plugin.cpp:1894           connect              ] Skipping connect due to go_away reason duplicate

But it is not clear which host is on the wrong chain or duplicate?   Can you print the offending IP address as well?  It would make debugging a lot easier.

**Comment by jgiszczak** [comment]
Closing in favor of #3900.

**Comment by xu10000** [comment]
3355163ms thread-0   net_plugin.cpp:2279           handle_message       ] received a go away message from 47.96.104.71:9876, reason = wrong chain
3355163ms thread-0   net_plugin.cpp:2090           operator()           ] Error reading message from 47.96.104.71:9876: Bad file descriptor

**Comment by xu10000** [comment]
how to solve?

**Comment by matthewdarwin** [comment]
Check you have the same genesis.json with the other side.

**Comment by xu10000** [comment]
genesis.json is same.  I checkout it over many time.

**Comment by xu10000** [comment]
I git pull, the new  code solve the plobrem.
