### ISSUE TITLE
How to deploy a dedicated API endpoint?

### ISSUE THREAD

**Issue by hashware** [EOSIO/eos#3896]
the wiki doc says
nodeos

The core EOSIO daemon that can be configured with plugins to run a node. Example uses are block production, **## dedicated API endpoints**, and local development.

but i cant find any guides for it.
thanks.

**Comment by jgiszczak** [comment]
An API endpoint is merely a node with `http_plugin` and possibly `http_client_plugin` enabled, but not `producer_plugin` enabled.  That node is then connected to producer nodes or forwarding nodes eventually connected to producer nodes with `net_plugin` and/or `bnet_plugin`.  (Without a connection, direct or indirect, to producer nodes, there's no chain and an API endpoint doesn't do anything useful.)

**Comment by hashware** [comment]
I tried but failed
Would you please provide a step by step guide
Thank you

**Comment by hashware** [comment]
Does a "dedicated API endpoints" need NOT to download all the blockchain data?

**Comment by jgiszczak** [comment]
It's no longer possible to run nodeos without `producer_plugin` enabled.  Instead, the distinction is whether or not a producer has been configured on the node.  If there is no `producer-name =` and no `signature-provider =` configured, then the node is an API endpoint.

A dedicated API endpoint must still download the entire chain.  At present there is no implementation of a 'lite' node.

**Comment by sjhendriksz** [comment]
Hi jgiszczak. Did you manage to get your API endpoint set up?
I'm trying to do the same now, but there are hardly any resources out there on how to do it.

**Comment by jgiszczak** [comment]
@sjhendriksz To set up a mainnet API node, the instructions at the bottom of [this page](https://eosnode.tools/snapshots) tell you how to start from a snapshot.  You can then add peers from [this page](https://eosnodes.privex.io/).

Jungle Testnet has an automated script to set up an API node.

I'm sure the various other EOS.IO networks have similar resources available.
