### ISSUE TITLE
--replay-blockchain takes 100% CPU but restores nothing (should log where it is at in replaying the chain or other errors)

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#3899]
If I start up a new nodeos server and sync from the network, I get nice logging telling me where I am at.

424346ms thread-0   net_plugin.cpp:1548           recv_block           ]  got block 4032 from eosnation-nodeos-bp:9876 - 9506546
3424597ms thread-0   net_plugin.cpp:1548           recv_block           ]  got block 4033 from eosnation-nodeos-bp:9876 - 9506546
3424832ms thread-0   net_plugin.cpp:1548           recv_block           ]  got block 4034 from eosnation-nodeos-bp:9876 - 9506546

If I try to --replay-blockchain from the start there is no logging while the replay is going on.  nodeos is doing something because it takes 100% CPU, but we really need some progress indicators in the log so we know what block number we are on.

nodeos    | 2568841ms thread-0   net_plugin.cpp:2312           handle_message       ] got a notice_message from 192.168.200.2:9876
nodeos    | 2568841ms thread-0   net_plugin.cpp:2317           handle_message       ] this is a last irreversible notice with 399525 blocks
nodeos    | 2568841ms thread-0   net_plugin.cpp:2347           handle_message       ] this is a last irreversible notice with 399526 blocks
nodeos    | 2568841ms thread-0   net_plugin.cpp:1521           recv_notice          ] sync_manager got last irreversible block notice
nodeos    | 2568841ms thread-0   net_plugin.cpp:1285           sync_required        ] last req = 0, last recv = 395757 known = 399526 our head = 395757
nodeos    | 2568841ms thread-0   net_plugin.cpp:1255           set_state            ] old state in sync becoming lib catchup
nodeos    | 2568841ms thread-0   net_plugin.cpp:1405           start_sync           ] Catching up with chain, our last req is 0, theirs is 399526 peer 192.168.200.2:9876

**Comment by matthewdarwin** [comment]
Apparently backing up the data/* directory from one machine and restoring to another is not sufficient?  What else is needed?

Other people have mentioned replay should output some log entries.

**Comment by jgiszczak** [comment]
`--replay-blockchain` does produce progress status messages.  From my current log:

```3143319ms thread-0   controller.cpp:1141           startup              ] No head block in fork db, perhaps we need to replay
3143319ms thread-0   controller.cpp:307            initialize_fork_db   ]  Initializing new blockchain with genesis state                  
3143344ms thread-0   controller.cpp:199            init                 ] existing block log, attempting to replay 285583 blocks
       100 of 285583
       200 of 285583
       300 of 285583
       400 of 285583
       500 of 285583
       600 of 285583
       700 of 285583
       800 of 285583```
It continues in increments of 100 up to 285500, concluding with:
```    285400 of 285583
    285500 of 285583
3374060ms thread-0   controller.cpp:216            init                 ] 50536 reversible blocks replayed
3374061ms thread-0   controller.cpp:220            init                 ] replayed 336119 blocks in seconds, 0.68641280617876410 ms/block

3374061ms thread-0   chain_plugin.cpp:406          plugin_startup       ] starting chain in read/write mode
3374061ms thread-0   chain_plugin.cpp:411          plugin_startup       ] Blockchain started; head block is #336119, genesis timestamp is 2018-05-31T20:00:00.000```

(We're aware of the defect in the time reporting.)

Note that the line-endings of the incremental status messages utilize the naked carriage return trick, resulting in a single repeatedly overwritten updating line when displayed in a terminal, but peculiar results in many text editors or display tools when attempting to display a redirected log file.

Replay of a long chain can take a considerably long time, on the order of hours.

**Comment by matthewdarwin** [comment]
I'm using docker, just looking at logs on the console.

docker logs nodeos -f

**Comment by matthewdarwin** [comment]
So I would assume docker is one of those tools that cannot handle the "naked carriage return".  How about writing plain messages instead of trying to do something fancy that needs a terminal?

**Comment by taokayan** [comment]
Can you try with the latest version to see if this issue still happens?

**Comment by matthewdarwin** [comment]
Sure, I will re-test later today

**Comment by matthewdarwin** [comment]
nodeos version 1.0.6.  
Using the docker syslog driver, you get some logs.  Not pretty.  Very large gaps of time (9 minutes with no logs while all the big blocks at the start are replayed)

[log.txt](https://github.com/EOSIO/eos/files/2134992/log.txt)
In the attached file, log lines are truncated for readability

It would be much better to get rid of the fancy draw progress over top itself, and just ouput something every 30 seconds with where it's at.

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com
