### ISSUE TITLE
Error creating contract following instructions in Readme.md

### ISSUE THREAD

**Issue by mark0st** [EOSIO/eos#390]
The following step in Readme.md fails (newlines added for readability):

```
$ ./eosc set contract currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi
Reading WAST...
Assembling WASM...
Publishing contract...
2060686ms thread-0   main.cpp:768                  main                 ] 
Failed with error: 10 assert_exception: Assert Exception status_code == 200: Error
: 3030002 tx_missing_sigs: signatures do not satisfy declared authorizations
Transaction declares authority '{"account":"currency","permission":"active"}', 
but does not have signatures for it.
    {"auth":{"account":"currency","permission":"active"}}
    thread-0  chain_controller.cpp:749 get_required_keys
```

The error in server log:

```
2060681ms thread-0   chain_api_plugin.cpp:58       operator()           ] 
Exception encountered while processing chain.get_required_keys:
 {"code":3030002,"name":"tx_missing_sigs","message":"signatures do not satisfy declared authorizations",
"stack":[{"context":{"level":"error","file":"chain_controller.cpp","line":749,
"method":"get_required_keys","hostname":"",
"thread_name":"thread-0","timestamp":"2017-09-08T16:34:20"},
"format":"Transaction declares authority '${auth}', 
but does not have signatures for it.","data":{"auth":{"account":"currency","permission":"active"}}}]}
```

Previous steps were completed successfully and resulted in behaviour described in Readme.

**Comment by nanonano7** [comment]
Make sure you have setup a wallet that has the private key for the currency account imported and it is unlocked. Just import both keys active and owner to be sure.

**Comment by datienzalopez** [comment]
@mark0st as @nanonano7 said, you should import the private keys that you have used in the steps before to create the currency account.

./eosc wallet import _<private key>_

**Comment by mark0st** [comment]
Thanks, that solved the issue.
These instructions should be added to Readme, probably right before [Upload sample contract](https://github.com/EOSIO/eos/blob/master/README.md#upload-sample-contract).

**Comment by Toormi** [comment]
When I executed this instruction:

> ./eosc set contract player ../../../contracts/currency/currency.wast ../../../contracts/currency/currency.abi


I got this message:

> File does not exist: ../../../contracts/currency/currency.wast
> ERROR: ValidationError: wast-file=../../../contracts/currency/currency.wast

I search the whole project find there is no file named currency.wast
where is the file currency.wast?

**Comment by datienzalopez** [comment]
@Toormi I guess that you are going to the wrong path, just remove one **_../_**

The files should be in ~/eos/build/contracts/currency/

**Comment by Toormi** [comment]
@datienzalopez Thanks, I solved this issue.

I missed these instructions before I build EOS:
`echo "export WASM_LLVM_CONFIG=~/wasm-compiler/llvm/bin/llvm-config" >> ~/.bash_profile
echo "export LLVM_DIR=/usr/local/Cellar/llvm/4.0.1/lib/cmake/llvm" >> ~/.bash_profile
source ~/.bash_profile`

So after I build EOS, there is no 'contracts' directory at  ~/eos/build, and I support this directory is ~/eos/contracts, it's my mistake.

**Comment by wanderingbort** [comment]
Closing this issue, the original and tag-on issue seem fixed
