### ISSUE TITLE
why exec bios-boot-tutorial.py raise error ??? eos version dawn-v4.2.0

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#3907]
eos1@eos1-virtual-machine:~/eos/tutorials/bios-boot-tutorial$ ./bios-boot-tutorial.py  -a
  File "./bios-boot-tutorial.py", line 144
    factor = 1_000_000_000 / sum(dist)
                         ^
SyntaxError: invalid syntax

thanks!!

**Comment by jgiszczak** [comment]
This is Python 3.6 syntax.  Many distributions ship with Python 3.5.  There are discussions about removing the3.6-specific features, but that has not yet happened.  Until then, install Python 3.6 and edit the shebang line of the script to call it explicitly (if you prefer to not change your Python version in your OS preferences).
