### ISSUE TITLE
read / write transaction directly

### ISSUE THREAD

**Issue by Bo3o2S** [EOSIO/eos#3908]
hello, guys
i just wonder how can i read/write transaction directly. because nodeos use http_plugin and get or push transaction by http protocol. but i want to it directly.
can you recommend some solution about this problem?

**Comment by taokayan** [comment]
You can modify the plugin or create your own plugin and directly call push_transaction, but that will only push transaction into your local node. However, the communication between different nodes need to be done using TCP.
