### ISSUE TITLE
multi_index secondindex begin()，If there is no record, an error will occur

### ISSUE THREAD

**Issue by OracleChain** [EOSIO/eos#3909]
```
typedef multi_index<N(behsco), behsco,//behsco
   indexed_by< N(bysecondary), const_mem_fun<behsco, account_name, &behsco::get_secondary> >
> BehaviorScores;
void test(){
    BehaviorScores bs(_self, dataAdmin);
    auto secondary_index = bs.get_index<N(bysecondary)>();
    auto ite = secondary_index.begin();
}
```

**Comment by arhag** [comment]
What is the error?

What is supposed to happen if there are no records in the table is that `secondary_index.begin() == secondary_index.end()`.

**Comment by arhag** [comment]
I could not reproduce an error while investing the `begin()` method on secondary indices of `multi_index`. If you believe an error related to this still exists in the latest master, then please create a new issue with detailed steps and example contract code needed to reproduce it.
