### ISSUE TITLE
Layout of README.md confusing

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#392]
Someone was trying to build on Linux the other day and was following the steps shown in the read me file. He dutifully worked through the linux specific build environment setup steps until he reached the macos section and figured that was the end.

We should add some sort of preamble, or TOC at the top indicating all that is involved with building the EOS codebase, and perhaps a link preceding optional sections to skip over that section. Such as a link to the mac setup preceding the Linux instructions and a link to building a node preceding the macos setup instructions.

**Comment by wanderingbort** [comment]
There is a TOC passing through the PR process right now ( #382 ).  Care to ask your friend if that PR would be enough clarity.  If not we should probably suggest changes on top of that PR to better clarify.

**Comment by pmesnier** [comment]
Thanks. That TOC looks pretty good. I'll go ahead and "review" the PR and merge it, then we can add additional comments if necessary. I noticed another PR for the README was submitted this morning, #394.

**Comment by pmesnier** [comment]
OK. I found a typo and made a couple of other suggestions on the PR.

**Comment by pmesnier** [comment]
PR #382 addresses the points in this issue.
