### ISSUE TITLE
apigen doesn't work with https://github.com/EOSIO/eosio.token

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3929]
Areg reports that it seems to fail when header/source are separated.

**Comment by heifner** [comment]
#3970 provided actions for eosio.token. @elmato Could we also parse `multi_index` and auto-generate table definitions from the referenced tables?

**Comment by wanderingbort** [comment]
We have migrated over to the CDT which has a new model of ABI-Gen. Closing this as no longer relevant
