### ISSUE TITLE
Docker run should be "docker run --name nodeos -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh arg1 arg2 --genesis-timestamp=now" in the documentation

### ISSUE THREAD

**Issue by HassanAmad** [EOSIO/eos#3934]
The current documentation for setting up a local test node using docker does not actually work for individuals following the instructions. 

After having a few discussions with some of the community members, it was brought to my attention that this could be solved by replacing the current command:
`docker run --name nodeos -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh arg1 arg2`

with:
` docker run --name nodeos -p 8888:8888 -p 9876:9876 -t eosio/eos nodeosd.sh arg1 arg2 --genesis-timestamp=now`

Unfortunately I do not have permission to fix the wiki page where this is [located](https://github.com/EOSIO/eos/wiki/Local-Environment#3-docker)

Can someone with permission to edit the wiki add this so that newbs like me (who don't know this) can have an easier time building it in docker?

**Comment by dixia** [comment]
updated in developer portal. let us know if you find any other suggestions
