### ISSUE TITLE
eos exec  system contract error !! eos version dawn-v4.2.0

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#3937]
cleos set contract eosio eos/build/contracts/eosio.system -p eosio
Reading WAST/WASM from eos/build/contracts/eosio.system/eosio.system.wasm...
Using already assembled WASM...
Publishing contract...
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: unable to find key
eos3@eos3-virtual-machine:~$
thanks!!!!!

**Comment by moskvanaft** [comment]
You need to create some accounts before installing the system contract. See https://github.com/EOSIO/eos/wiki/Tutorial-Bios-Boot-Sequence "Create important system accounts"
