### ISSUE TITLE
How to test side chain feature locally?

### ISSUE THREAD

**Issue by futouyiba** [EOSIO/eos#3938]
How to create a side chain on my local environment?
Side chain is a very important feature of EOS, how can I test it locally?

**Comment by futouyiba** [comment]
When I think about it, this is more like a "question" instead of "issue". If anyone tell me how to transfer it into a "question", it's appreciated.

Of course, if anyone could directly answer this question, I will close this one immediately. 
Thanks.

**Comment by walnutown** [comment]
Had the same question here. Apparently, we can find nothing about sidechain in technical whitepaper
https://github.com/EOSIO/Documentation

**Comment by taokayan** [comment]
This question is too board. If you wish to discuss further, please post it in https://eosio.stackexchange.com
