### ISSUE TITLE
After deploying the contract eosio.system, is the cleos create account command unavailable?

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#3941]
eos1@eos1-virtual-machine:~$ cleos create account eosio liontoken EOS55UqxQmM1A7Hdfp9kAe9vgHbjJM9iXp7EpCH5sNQier9sAB5gP EOS55UqxQmM1A7Hdfp9kAe9vgHbjJM9iXp7EpCH5sNQier9sAB5gP
Error 3080001: account using more than allotted RAM usage
Error Details:
account liontoken has insufficient ram; needs 2996 bytes has 0 bytes
thanks!!!!!!!

**Comment by moskvanaft** [comment]
yes. after you installed system contract you need to use
`cleos system newaccount ...`
