### ISSUE TITLE
3050000 action_validate_exception: action exception

### ISSUE THREAD

**Issue by nining** [EOSIO/eos#3943]
I tried to start the node with the following command:
./nodeos  --genesis-json ./genesis.json
And I got this error:
230531ms thread-0   controller.cpp:1142           startup              ] No head block in fork db, perhaps we need to replay
230532ms thread-0   controller.cpp:307            initialize_fork_db   ]  Initializing new blockchain with genesis state                  
230567ms thread-0   fork_database.cpp:93          close                ] num_blocks_in_fork_db: 1 
230574ms thread-0   main.cpp:113                  main                 ] 3050000 action_validate_exception: action exception
max transaction cpu usage must be less than max block cpu usage
    {}
    thread-0  chain_config.cpp:24 validate
    {}
    thread-0  chain_plugin.cpp:417 plugin_startup

**Comment by arhag** [comment]
In your genesis.json file, the value for `max_transaction_cpu_usage` must be less than the value for `max_block_cpu_usage`. 

For other restrictions on genesis configuration values, see: https://github.com/EOSIO/eos/blob/v1.0.2/libraries/chain/chain_config.cpp#L12-L43
