### ISSUE TITLE
dice contract error

### ISSUE THREAD

**Issue by kael777** [EOSIO/eos#3944]
i follow the step of dice contract until the step of "Alice deposits 100 EOS into the dice contract"
and error 3090003 occur,i have import the private key to wallet and do every single step above,but it still not working for the permission problem,what is wrong here?

**Comment by boy-good** [comment]
> i follow the step of dice contract until the step of "Alice deposits 100 EOS into the dice contract"
> and error 3090003 occur,i have import the private key to wallet and do every single step above,but it still not working for the permission problem,what is wrong here?

me too. Are you solve the problem now?

**Comment by tbfleming** [comment]
The dice contract uses techniques for dealing with tokens which are no longer recommended and has other bugs. It’s scheduled for removal.

**Comment by tbfleming** [comment]
Closing this since dice is being removed by #6023

**Comment by boy-good** [comment]
> The dice contract uses techniques for dealing with tokens which are no longer recommended and has other bugs. It’s scheduled for removal.

ok,i update version to 1.4.0. Thank you very much.
