### ISSUE TITLE
Account Query Exception on get_currency_balance rpc call

### ISSUE THREAD

**Issue by LDS1** [EOSIO/eos#3946]
Makin chain request **get_currency_balance** with body:

> {"contract":"eosio.token","account":"test1","symbol":"SYS"}

**response** 

> "500 Internal Server Error: {\"code\":500,\"message\":\"Internal Service Error\",\"error\":{\"code\":3060002,\"name\":\"account_query_exception\",\"what\":\"Account Query Exception\",\"details\":[{\"message\":\"Fail to retrieve account for \",\"file\":\"chain_plugin.cpp\",\"line_number\":592,\"method\":\"get_abi\"}]}}"

**cleos get currency balance eosio.token test1 SYS** returns correct data.

**Comment by arhag** [comment]
I think you may be referring to outdated documentation, because the `contract` field has been renamed to `code`.

**Comment by kooogle** [comment]
I need to get the address of the eos wallet today. After going through google, many people have encountered this problem. My parameters are {:account=>"youraccount", :code=>"eosio.token", :symbol=>"EOS"}, it can work for me
