### ISSUE TITLE
cleos json parsing hangs

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eos#3955]
Bug in fc::json_relaxed used by cleos.

**Comment by arhag** [comment]
Resolved by #3957.

**Comment by tacc716** [comment]
Hey, Need little clarification that does this is the same bug exist in eosio.token contract ? I mean sending a contract in infinite loop by using \ slash ?

**Comment by moskvanaft** [comment]
@tacc716 there was no such bug in eosio.token contract. If you were "sending a contract in infinite loop by using \ slash" it never reached the contract (and even the node you were trying to send it to) because `cleos` hang.
