### ISSUE TITLE
p2p launcher updates

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#396]
The launcher will generate 2 explicit connections between some nodes, leading to duplicated message replication. Need to add a filter to ensure only one bidirectional connection between any two nodes, and that each node has at least one active connection defined. 

Also need to update the config.ini template to include new wallet plugins, and update the eosd command template to be correct WRT skipping signatures or any other parameters. 

Down the road... 
I would also like to separate the behaviors of launching and killing eosd processes into different executables, along with a 3rd executable that just emits a network configuration template file. All of these are behaviors of the launcher app today, selected by command line options. But I think that different exename would make it more clear.

Turn the launcher into a plugin that could be collocated with eosd or embedded into a standalone daemon to support the handling of RPC requests to manage the state of the eosd network nodes. See the "usability" section of issue #291

**Comment by heifner** [comment]
Moving over to issue #375 as I believe that is what Dan wants me to look at this morning. I did not do any work on this issue as I went for a long walk after putting it in work.

**Comment by heifner** [comment]
Getting started on this on 9/13. It is not scheduled for the 1.0 milestone.
- For star and mesh currently, two connections between nodes is possible
  - Need to filter the configuration generation so that duplicate connections are not specified
  - If a->b, then b->a is not needed as connections are bi-directional
- Also list of remotes should not go empty, one remote should be specified

**Comment by heifner** [comment]
- [ ] Add filter on configuration generation to prevent duplicate connections
- [ ] Update config.ini to include wallet plugin
- [ ] Update eosd to allow for command line args to be forwarded to it

**Comment by heifner** [comment]
Issue has been merged, closing.
