### ISSUE TITLE
DAWN-492 ⁃ Not producing block because node didn't wake up within 500ms of the slot time.

### ISSUE THREAD

**Issue by pavybez** [EOSIO/eos#397]
I started a single node with wall_api_plugin embedded and initiated some transactions using ./eosc benchmark transfer 600 600.

I see the following output in the log file. 

2994239ms thread-0   producer_plugin.cpp:210       block_production_loo ] initk generated block #202 @ 2017-09-11T06:49:54 with 0 trxs  0 pending
2998489ms thread-0   producer_plugin.cpp:229       block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
3000615ms thread-0   producer_plugin.cpp:229       block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
3002818ms thread-0   chain_controller.cpp:235      _push_block          ] inith #203 @2017-09-11T06:50:03  | 0 trx, 0 pending, exectime_ms=13

**Comment by pavybez** [comment]
Attached is the config.ini of the eosd.

[config.txt](https://github.com/EOSIO/eos/files/1291647/config.txt)

**Comment by bytemaster** [comment]
This is an indication that the single CPU is getting backlogged by a large blocking task that is not properly timebound... eg, block generation with a large pending set.

**Comment by wanderingbort** [comment]
We are planning to address this issue in the EOS Dawn 2.0 milestone as part of #301

**Comment by brianjohnson5972** [comment]
@bytemaster or @coreylederer  or @thomasbcox  This task is marked as EOS Dawn 1.1, but the above comment indicates that it will be addressed by another issue, that is marked as EOS Dawn 2.0.  Should this be closed and/or EOS Dawn 1.1 removed?

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Related to GH301 / DAWN‌-491

**Comment by heifner** [comment]
This will be worked under #301
