### ISSUE TITLE
why doesn't my single node testnet produce blocks

### ISSUE THREAD

**Issue by GeneSourceCode** [EOSIO/eos#3971]
I start my single node testnet with command 

```bash
/usr/local/bin/nodeos --enable-stale-production true --producer-name eosio --signature-provider=EOS6ttqSHFAtVoQgc6d9VPTCvAVU4sFCwdYHojbzjoTX6wV8fwLyW=KEY:5HwPk4pD1Tf1VGXW77rjE6AGLj9E7VUTzjgmgGRPoK886UEyS5y --http-server-address 0.0.0.0:8888 --p2p-listen-endpoint 0.0.0.0:9876 --p2p-server-address 127.0.0.1:9876 --agent-name eosio --p2p-max-nodes-per-host 1000 --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::http_plugin --plugin eosio::history_api_plugin --plugin eosio::net_plugin --plugin eosio::net_api_plugin --plugin eosio::bnet_plugin --plugin eosio::wallet_api_plugin --config-dir /root/.nodes/eosio --data-dir /root/.nodes/eosio --genesis-json /root/.nodes/eosio/genesis.json --delete-all-blocks
```

The test net is supposed to start producing blocks. But the output stops. The json file refered in the command is shown as follows

>{                                                                                                                                                                         "initial_timestamp": "2018-06-09T10:58:49",                                                                                                                           "initial_key": "EOS6ttqSHFAtVoQgc6d9VPTCvAVU4sFCwdYHojbzjoTX6wV8fwLyW",                                                                                               "initial_chain_id": "0000000000000000000000000000000000000000000000000000000000000000",                                                                               "initial_configuration": {                                                                                                                                                "max_block_net_usage": "1048576",                                                                                                                                     "target_block_net_usage_pct": "1000",                                                                                                                                 "max_transaction_net_usage": "524288",                                                                                                                                "base_per_transaction_net_usage": "12",                                                                                                                               "net_usage_leeway": "500",                                                                                                                                            "context_free_discount_net_usage_num": "20",                                                                                                                          "context_free_discount_net_usage_den": "100",                                                                                                                         "max_block_cpu_usage": "100000",                                                                                                                                      "target_block_cpu_usage_pct": "500",                                                                                                                                  "max_transaction_cpu_usage": "50000",                                                                                                                                 "min_transaction_cpu_usage": "100",                                                                                                                                   "max_transaction_lifetime": "3600",                                                                                                                                   "deferred_trx_expiration_window": "600",                                                                                                                              "max_transaction_delay": "3888000",                                                                                                                                   "max_inline_action_size": "4096",                                                                                                                                     "max_inline_action_depth": "4",                                                                                                                                       "max_authority_depth": "6",                                                                                                                                           "max_generated_transaction_count": "16"                                                                                                                           }                                                                                                                                                                 
}

what is the problem with my launching command?

**Comment by jgiszczak** [comment]
You need `--private-key "["EOS6ttqSHFAtVoQgc6d9VPTCvAVU4sFCwdYHojbzjoTX6wV8fwLyW","corresponding_private_key"] as well.  The genesis.json `initial_key` pair needs to be available so `eosio` can sign blocks.

**Comment by ntienbo** [comment]
push action eosio.token issue {"to":"eosio","quantity":"2000000000.0000 SYS","memo":"issue all system coin to eosio"} -p eosio
ERROR: ExtrasError: [quantity:2000000000.0000 SYS memo:issue all system coin to eosio]
Push a transaction with a single action
Usage: /home/eos-sources/eos/build/programs/cleos/cleos push action [OPTIONS] account action data

Positionals:
  account TEXT                The account providing the contract to execute (required)
  action TEXT                 A JSON string or filename defining the action to execute on the contract (required)
  data TEXT                   The arguments to the contract (required)

Options:
  -h,--help                   Print this help message and exit
  -x,--expiration             set the time in seconds before a transaction expires, defaults to 30s
  -f,--force-unique           force the transaction to be unique. this will consume extra bandwidth and
remove any protections against accidently issuing the same transaction multiple times
  -s,--skip-sign              Specify if unlocked wallet keys should be used to sign transaction
  -j,--json                   print result as json
  -d,--dont-broadcast         don't broadcast transaction to the network (just print to stdout)
  -r,--ref-block TEXT         set the reference block num or block id used for TAPOS (Transaction as Proof-of-Stake)
  -p,--permission TEXT ...    An account and permission level to authorize, as in 'account@permission'
  --max-cpu-usage-ms UINT     set an upper limit on the milliseconds of cpu usage budget, for the execution of the transaction (defaults to 0 which means no limit)
  --max-net-usage UINT        set an upper limit on the net usage budget, in bytes, for the transaction
(defaults to 0 which means no limit)
