### ISSUE TITLE
confused about the purpose of the scope for instantiating a multi_index

### ISSUE THREAD

**Issue by GeneSourceCode** [EOSIO/eos#3980]
I am confused about the purpose of scope which is the an argument of multi_index constructor. if the scope serves the same as its name suggests, the instantiated table should only contain records whose attribute used for index matches the scope value. But actually, the whole table is still accessible. So, what is the purpose for scope?

**Comment by tbfleming** [comment]
It's a multi_index constructor argument

**Comment by breadbread1984** [comment]
can the scope be any type of object?

**Comment by tbfleming** [comment]
the scope is a uint64_4

**Comment by GeneSourceCode** [comment]
thx
