### ISSUE TITLE
Create test for cleos get account

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#3984]
Smoke tests failed to detect a bug in get account which resulted in an error when system contract was loaded.

**Comment by cj-oci** [comment]
The nodeos_run_test.py does create and get account both before and after loading eosio.system contract. See attached test output. Contract eosio.system is loaded on line 201. Account testera11111 gets created on line 337. get account testera11111 is on line 376. Is there anything specific that should be validated in the get account response?

[nodeos_run_test-output.txt](https://github.com/EOSIO/eos/files/2091886/nodeos_run_test-output.txt)

**Comment by heifner** [comment]
What the test failed to catch was this: #3917

**Comment by heifner** [comment]
Looks like #3917 cleos should have returned 1 which I think Brian's new code which checks return code would catch.
