### ISSUE TITLE
whitelist_blacklist_tests.cpp:10:10: fatal error: 'deferred_test/deferred_test.wast.hpp' file not found

### ISSUE THREAD

**Issue by ljbb** [EOSIO/eos#3985]
There is an issue when building docker image, the detail information as below, could EOS support fix this issue? seems like the unit test cause the fatal error.

[1329/1345] Building CXX object unittests/CMakeFiles/unit_test.dir/whitelist_blacklist_tests.cpp.o
FAILED: unittests/CMakeFiles/unit_test.dir/whitelist_blacklist_tests.cpp.o 
/usr/bin/clang++   -Icontracts -I/eos/contracts -Iunittests/contracts -I/eos/unittests/contracts -I/eos/libraries/testing/include -Iunittests/tests/contracts -I/eos/unittests/wasm_tests -Iunittests/include -I/eos/libraries/chain/include -Ilibraries/chain/include -I/eos/libraries/chain/../wasm-jit/Include -I/eos/libraries/chain/../../externals/binaryen/src -I/eos/libraries/utilities/include -I/eos/libraries/utilities/../wasm-jit/Include -I/eos/libraries/fc/include -I/usr/local/include -I/usr/include/openssl/include -I/eos/libraries/fc/vendor/websocketpp -I/eos/libraries/chainbase/include -I/eos/libraries/wasm-jit/Source/Runtime/../../../chain/include -I/eos/libraries/softfloat/source/include -I/eos/libraries/softfloat/source/8086-SSE -I/eos/libraries/softfloat/build/Linux-x86_64-GCC -I/eos/libraries/builtins -I/eos/libraries/builtins../softfloat/source/include -Ilibraries/testing/include -I/eos/libraries/testing/../wasm-jit/Include -I/eos/libraries/abi_generator/include -I/usr/lib/llvm-4.0/include -Wall -Wno-invalid-partial-specialization -fcolor-diagnostics -O3 -DNDEBUG   -std=gnu++14 -MD -MT unittests/CMakeFiles/unit_test.dir/whitelist_blacklist_tests.cpp.o -MF unittests/CMakeFiles/unit_test.dir/whitelist_blacklist_tests.cpp.o.d -o unittests/CMakeFiles/unit_test.dir/whitelist_blacklist_tests.cpp.o -c /eos/unittests/whitelist_blacklist_tests.cpp
/eos/unittests/whitelist_blacklist_tests.cpp:10:10: fatal error: 'deferred_test/deferred_test.wast.hpp' file not found
#include <deferred_test/deferred_test.wast.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[1330/1345] Building CXX object unittests/CMakeFiles/unit_test.dir/tic_tac_toe_tests.cpp.o
[1331/1345] Building CXX object unittests/CMakeFiles/unit_test.dir/wasm_tests.cpp.o
ninja: build stopped: subcommand failed.
The command '/bin/sh -c git clone -b $branch https://github.com/EOSIO/eos.git --recursive     && cd eos && echo "$branch:$(git rev-parse HEAD)" > /etc/eosio-version     && cmake -H. -B"/tmp/build" -GNinja -DCMAKE_BUILD_TYPE=Release -DWASM_ROOT=/opt/wasm -DCMAKE_CXX_COMPILER=clang++        -DCMAKE_C_COMPILER=clang -DCMAKE_INSTALL_PREFIX=/tmp/build  -DSecp256k1_ROOT_DIR=/usr/local -DBUILD_MONGO_DB_PLUGIN=true -DCORE_SYMBOL_NAME=$symbol     && cmake --build /tmp/build --target install && rm /tmp/build/bin/eosiocpp' returned a non-zero code: 1

**Comment by ljbb** [comment]
This error is occurred on Dawn-4.0, Dawn-4.2, Eos-1.0.1 even EOS-1.0.2 as well, all versions are tried, still with the same issue.

**Comment by ljbb** [comment]
After checked the source code, there is no file "deferred_test.wast.hpp" under the folder unittests/contracts/deferred_test/, but the whitelist_blacklist_tests.cpp include the head file, cause this issue, hopping EOS team to update the unit test module ASAP.

**Comment by brianphobos** [comment]
I had the same issue building on Ubuntu 18.04 LTS

**Comment by samspk** [comment]
I have same issue during my 1st build on Ubunti 16.04 LTS Virtual Machine....


![image](https://user-images.githubusercontent.com/39917017/41196961-1aac396a-6c4e-11e8-8124-63271617d054.png)

**Comment by arhag** [comment]
Resolved by #3992.
