### ISSUE TITLE
bnet should expose a healthcheck path to allow for out-of-the-box load balancer integration

### ISSUE THREAD

**Issue by ellipticasec** [EOSIO/eos#3989]
Currently the bnet plugin expects the WebSocket handshake to be specified immediatly in the HTTP request headers of the initial request. This means that there is basically no way to get a HTTP 200 response for health check purposes. This is necessary for smooth integration with most load balancer setups that are doing healthcheck before letting traffic through (in most cases doing simple `GET /` expecting HTTP 200).

I am requesting that a special path (maybe `GET /ping` or `GET /healthz`) be added and return HTTP 200 if the WebSocket plumbing is ready for business.

This would be amazing so that we can use DDOS protection by flowing the bnet traffic through those.

**Steps to reproduce:**
```
$ curl -v http://127.0.0.1:4321 
> GET / HTTP/1.1
> Host: 127.0.0.1:4321
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Content-Length: 51
< Server: Boost.Beast/167
< 
* Connection #0 to host 127.0.0.1 left intact
The WebSocket handshake Connection field is missing
```

**Expected behavior:**
```
$ curl -v http://127.0.0.1:4321/healthz
> GET /healthz HTTP/1.1
> 
< HTTP/1.1 200 OK
< Server: Boost.Beast/167
< 
pong
```

**Comment by jgiszczak** [comment]
The bnet_plugin was deprecated in the v1.7.1 release and has now been removed.
