### ISSUE TITLE
Fatal Error: File Not Found! Building EOSIO on ubuntu 16.04.4 TLS Virtual Machine!

### ISSUE THREAD

**Issue by samspk** [EOSIO/eos#3994]
Hello

I have this error (see attached) during my 1st try to build EOSIO on ubuntu 16.04.4 TLS Virtual Machine! Can any one guide me? Wht Ihave this error?

![image](https://user-images.githubusercontent.com/39917017/41196964-483c7098-6c4e-11e8-8bd0-90beea3de0eb.png)

**Comment by brianphobos** [comment]
It looks like the fix to CMakeLists.txt  got merged 33 minutes ago.  I'm going to try to build it again.  Good luck to you as well!

**Comment by arhag** [comment]
Resolved by #3992.
