### ISSUE TITLE
Issue when Set the eosio.system contract

### ISSUE THREAD

**Issue by congnghebitcoin** [EOSIO/eos#3996]
There is an issue while using CLEOS to set eosio.system contract

> 1065003ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 0000a5b33af2f18d... #42419 @ 2018-06-10T08:17:45.000 signed by eosio [trxs: 0, lib: 42418, confirmed: 0]
1065504ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 0000a5b4f91714f9... #42420 @ 2018-06-10T08:17:45.500 signed by eosio [trxs: 0, lib: 42419, confirmed: 0]
1065675ms thread-0   wasm_interface.cpp:929        eosio_assert         ] message: unable to find key 
1065675ms thread-0   http_plugin.cpp:396           handle_exception     ] FC Exception encountered while processing chain.push_transaction: 3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
assertion failure with message: unable to find key
    {"s":"unable to find key"}
    thread-0  wasm_interface.cpp:930 eosio_assert
    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:60 exec_one
1066004ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 

> viettech88$ cleos --url http://localhost:8888 --wallet-url http://localhost:8899  set contract eosio contracts/eosio.system 
Reading WAST/WASM from contracts/eosio.system/eosio.system.wasm...
Using already assembled WASM...
Publishing contract...
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: unable to find key

I believe there is no problem with key

> viettech88$ cleos get account eosio
\privileged: true
permissions: 
     owner     1:    1 EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
        active     1:    1 EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
memory: 
     quota:        -1 bytes  used:     2.895 Kb   
net bandwidth: (averaged over 3 days)
     used:                -1 bytes
     available:           -1 bytes
     limit:               -1 bytes
cpu bandwidth: (averaged over 3 days)
     used:                -1 us   
     available:           -1 us   
     limit:               -1 us   

> viettech88s-MacBook-Pro:build viettech88$ cleos get account eosio.system
privileged: false
permissions: 
     owner     1:    1 EOS69R2Po2vWRkZQi9Erg3YdBYKxce9kU7hQh2AjvepziYgtKX8JM
        active     1:    1 EOS69R2Po2vWRkZQi9Erg3YdBYKxce9kU7hQh2AjvepziYgtKX8JM
memory: 
     quota:        -1 bytes  used:      2.66 Kb   
net bandwidth: (averaged over 3 days)
     used:                -1 bytes
     available:           -1 bytes
     limit:               -1 bytes
cpu bandwidth: (averaged over 3 days)
     used:                -1 us   
     available:           -1 us   
     limit:               -1 us

**Comment by congnghebitcoin** [comment]
oh I found that it missed native token SYS

**Comment by HeNanYuanWeitao** [comment]
how to solve this issue?

**Comment by shalomz** [comment]
The solution is to ensure you have created the native **SYS** token with something like `cleos push action eosio.token create '[ "eosio", "10000000000.0000 SYS" ]' -p eosio.token` then `cleos push action eosio.token issue '[ "eosio", "1000000000.0000 SYS", "memo" ]' -p eosio` then set the `system` contract with `cleos  set contract eosio path/to/eosio.system/contract`
