### ISSUE TITLE
Starting Single -nodeos Issue MacOS

### ISSUE THREAD

**Issue by raymondfx** [EOSIO/eos#3999]
When I run this command $ nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin 

I get this error, how can I fix it. Thanks

in eosio::history_api_plugin
2477787ms thread-0   chain_plugin.cpp:206          plugin_initialize    ] initializing chain plugin
2477798ms thread-0   block_log.cpp:123             open                 ] Log is nonempty
2477800ms thread-0   block_log.cpp:136             open                 ] my->head->block_num(): 1 
2477800ms thread-0   block_log.cpp:142             open                 ] Index is nonempty
2477830ms thread-0   http_plugin.cpp:285           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
2477831ms thread-0   net_plugin.cpp:2840           plugin_initialize    ] Initialize net plugin
2477832ms thread-0   net_plugin.cpp:2861           plugin_initialize    ] host: 0.0.0.0 port: 9876 
2477832ms thread-0   net_plugin.cpp:2933           plugin_initialize    ] my node_id is d7ce60aa741577f3615bfed66280f50df78de0849c81d05ecc86dee45330cc28
2477834ms thread-0   main.cpp:104                  main                 ] nodeos version ade08c5d
2477834ms thread-0   main.cpp:105                  main                 ] eosio root is /Users/dorris/Library/Application Support
2477836ms thread-0   chain_plugin.cpp:436          plugin_startup       ] starting chain in read/write mode
2477836ms thread-0   chain_plugin.cpp:441          plugin_startup       ] Blockchain started; head block is #1, genesis timestamp is 2018-06-01T12:00:00.000
2477837ms thread-0   http_plugin.cpp:323           plugin_startup       ] start listening for http requests
2477839ms thread-0   chain_api_plugin.cpp:75       plugin_startup       ] starting chain_api_plugin
2477840ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/abi_bin_to_json
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/abi_json_to_bin
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/get_abi
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/get_account
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/get_block
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/get_block_header_state
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/get_code
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/get_currency_balance
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/get_currency_stats
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/get_info
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/get_producers
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/get_required_keys
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/get_table_rows
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/push_block
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/push_transaction
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/chain/push_transactions
2477841ms thread-0   history_api_plugin.cpp:38     plugin_startup       ] starting history_api_plugin
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/history/get_actions
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/history/get_controlled_accounts
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/history/get_key_accounts
2477841ms thread-0   http_plugin.cpp:369           add_handler          ] add api url: /v1/history/get_transaction
2477844ms thread-0   fork_database.cpp:93          close                ] num_blocks_in_fork_db: 1 
2477845ms thread-0   controller.cpp:261            ~controller_impl     ] db.revision(): 1 head->block_num: 1 blog.read_head()->block_num(): 1 
2477855ms thread-0   main.cpp:119                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
std::exception::what: bind: Address already in use

**Comment by taokayan** [comment]
Looks like one of your port in config.ini is already occupied by other process. You can choose another port.

**Comment by andriantolie** [comment]
Yes, your port 8888 is already occupied by the other process, either kill that process or switch to another port
