### ISSUE TITLE
"Hello World" Contract MacOS

### ISSUE THREAD

**Issue by raymondfx** [EOSIO/eos#4000]
When I run this command  $ eosiocpp -o hello.wast hello.cpp

I get this error.

clang-4.0: error: no such file or directory: 'hello.cpp'
clang-4.0: error: no input fi

**Comment by friedger** [comment]
You should find help here: https://eosio.stackexchange.com

**Comment by raymondfx** [comment]
I managed to fix this problem.

**Comment by taokayan** [comment]
Is this issue solved?

**Comment by PillarDevelopment** [comment]
@raymondfx how do you complete this problem?

**Comment by jgiszczak** [comment]
Reported fixed by original poster.  Also OBE in any case.  `eosiocpp` is deprecated.  Users should be using `eosio-cpp` from https://github.com/EOSIO/eosio.cdt.
