### ISSUE TITLE
typo in wiki/Tutorial-Comprehensive-Accounts-and-Wallets

### ISSUE THREAD

**Issue by pjw4791** [EOSIO/eos#4004]
There is a typo in wiki/Tutorial-Comprehensive-Accounts-and-Wallets.

<img width="581" alt="2018-06-11 01 21 49" src="https://user-images.githubusercontent.com/6657429/41201967-0e57b63a-6d16-11e8-9f68-2694816bd2a5.png">
<img width="572" alt="2018-06-11 01 21 54" src="https://user-images.githubusercontent.com/6657429/41201968-14904c7e-6d16-11e8-9631-cfdf2aee05ea.png">
It should be "you will the two files"->"you will "SEE or HAVE" the two files".
Verb missing.

**Comment by dskvr** [comment]
Wiki will be deprecated, pending notice.
