### ISSUE TITLE
Where is the "mainnet" startup config files?

### ISSUE THREAD

**Issue by nining** [EOSIO/eos#4008]
The news said the "mainnet" was started.  Where is the startup config files?

**Comment by brandoncurtis** [comment]
There are some "unofficial" files linked here, but nothing official has been released yet.

https://eosio.stackexchange.com/questions/725/how-to-vote-using-cleos

If you fix the types in the plugin list like so:
```
plugin = eosio::producer_plugin 
plugin = eosio::wallet_api_plugin 
plugin = eosio::chain_api_plugin 
plugin = eosio::http_plugin
plugin = eosio::history_api_plugin
```

I was able to get it to run by following those instructions.

**Comment by jgiszczak** [comment]
https://github.com/EOS-Mainnet is one copy.
