### ISSUE TITLE
DAWN-489 ⁃ Missing scope and auth returned in eos::chain_apis::read_only::abi_json_to_bin_result

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#401]
Run
```shell
echo '{"code":"eos","action":"transfer",
"args":{"from":"inita","to":"initb","amount":1,"memo":""}}' |
curl http://127.0.0.1:8888/v1/chain/abi_json_to_bin -d @-
```
Current Output
```js
{"binargs":"000000008040934b000000000041934b010000000000000000",
"required_scope":[],"required_auth":[]}
```
Expecting
```js
{"binargs":"000000008040934b000000000041934b010000000000000000",
"required_scope":['inita', 'initb'],
"required_auth":[
    {account: 'inita', permission: 'active'}
]}
```
I believe that `required_auth` needs to be more complex than the above example.  It should probably have an outer array of **OR** authorities with an inner array of **AND** authorities.  So the following would say either `bob` or (`jan` and `mike`) may sign:
```js
required_auth: [
    [{account: 'bob', permission: 'active'}], // or..
    [{account: 'jan', permission: 'active'}, {account: 'mike', 'active'}]
]
```

**Comment by heifner** [comment]
@wanderingbort is this something you are working under #402 ?

**Comment by wanderingbort** [comment]
At the very least, I will be addressing the ability to auto-determine `required_scope` for the given end-point.  It is possible (perhaps likely) that mode of discovery for a transaction can also handle inferring the `required_auth`.

**Comment by wanderingbort** [comment]
please disregard the ref'd commits.  Classic off by one error 😄

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Connected to github issue \#402 / DAWN‌-490

Bart:

At the very least, I will be addressing the ability to auto-determine required_scope for the given end-point. It is possible (perhaps likely) that mode of discovery for a transaction can also handle inferring the required_auth.

**Comment by heifner** [comment]
These have been removed since they were not used/needed.
