### ISSUE TITLE
official mainnet sync settings

### ISSUE THREAD

**Issue by suahnkim** [EOSIO/eos#4014]
currently there is no official mainnet sync settings on this git. 
can someone update either the wiki(git) or the readme.md so people can start meshing with the mainnet? 

1. official genesis.json for the mainnet 
2. trusted urls/ips to bps 
3. trusted urls/ips to public nodes 

or
can someone clarify why this information isn't publicably available on git?

**Comment by jgiszczak** [comment]
Block.one is not launching the main net.  Github hosts the software.  It's up to the community to organize the mainnet launch.  Block.one is not endorsing any producer candidates, public nodes, or even snapshot results.  Links could be interpreted as endorsements.
