### ISSUE TITLE
Proposal roadmap for simpler EOS smart contract development.

### ISSUE THREAD

**Issue by iwasaki-kenta** [EOSIO/eos#4016]
Already saw some work on this, though I would like to bullet point down the main ways I see easiest at the current repository's state to make smart contract developments significantly easier on EOS.

1. Finalize separating a small, standalone smart contract SDK away from the main repository that won't require contract developers who utilize IDE's such as CLion to have to index all the source code within EOS for the sake of getting code auto-completion and other nice code analysis tidbits.

   The current methodology to developing smart contracts either requires sym-linking the `eosiolib` smart contract library to one's project (which requires indexing of the entire EOS monolithic repo.) or requires opening the entire EOS repo. on one's IDE.

   This allows for a development pattern where users leave an EOS block producer node running on Docker, and allows users to setup their smart contract development environment in a matter of a minute or two.

2. Provide reference `CMakeLists.txt` and a command to generate smart contract stub projects onto the `eosiocpp` CLI tool. Solely generating a hello-world contract does not help a developer much.

**Comment by jgiszczak** [comment]
The [Contract Development Toolkit](https://github.com/EOSIO/eosio.cdt) is now available.
