### ISSUE TITLE
how to write inline communication

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#4021]
I want to call action from another smart contract but don't know how to do it. I find a example in eosio.token whose issue action use SEND_INLINE_ACTION to call an action of the same contract.How do I call an action from a different contract?Thx

**Comment by iwasaki-kenta** [comment]
Provide the contract as the _name scope_ and specify a method from the contract's ABI to thereafter execute it. It's over in the docs here: https://developers.eos.io/eosio-cpp/reference#action-1

**Comment by breadbread1984** [comment]
thx i am learning it

**Comment by GeneSourceCode** [comment]
@iwasaki-kenta do i need to include the header file in the currenct directory if i want to compile a contract with inline action call to the other contract.
