### ISSUE TITLE
Pub not match private_key!Need Help!

### ISSUE THREAD

**Issue by Robwpy** [EOSIO/eos#4022]
I made a big mistake. I should use eth private_key to convert EOS Pub_key ,But use eth pub key convert to EOS pub key instead. The same private of hex ,but mainnet not match!!!

eth register is end , How could I do to fix this?
I really need help

**Comment by Robwpy** [comment]
@spartucus

**Comment by heifner** [comment]
This is not the proper place to seek help with this issue.

**Comment by spartucus** [comment]
Hi @Robwpy , sorry to hear that, i think you should ask help from [block.one](https://t.me/joinchat/EaEnSUPktgfoI-XPfMYtcQ).
