### ISSUE TITLE
reboot nodeos is very slow，why only one cpu core used？

### ISSUE THREAD

**Issue by zformular** [EOSIO/eos#4046]
![image](https://user-images.githubusercontent.com/1741302/41269604-a2e7083c-6e38-11e8-91c2-836367391b40.png)

**Comment by jgiszczak** [comment]
`nodeos` is not currently multithreaded, nor are there plans to thread it any time soon.

**Comment by farss** [comment]
but why? @jgiszczak

**Comment by jgiszczak** [comment]
@farss In the year since this issue was closed, nodeos has gotten several pieces of multithreading, especially in the networking code.  Network sync times have benefited.
