### ISSUE TITLE
Question for keosd and cleos

### ISSUE THREAD

**Issue by hellguard0** [EOSIO/eos#4047]
Hi guys, I was quite new to this EOS blockchain and was trying to follow the guide to setup the docker and the eos blockchain. I not sure if the guide was outdate or not. I was trying to run eosd but was nothing there in the folder i downloaded. so I try for keosd but it still showing error.

docker-compose exec keosd /opt/eosio/bin/cleos -u http://nodeosd:8888 --wallet-url http://l
ocalhost:8900 get info
Failed to connect to nodeos at http://nodeosd:8888; is nodeos running?

I was using Windows 10 Pro and is on Docker Linux container, using powershell admin to run the above code. I manage to create wallet and list the wallet from command. 

and for cleos command i totally cannot run even on powershell or on bash environment. Anyone can assist on this or providing a more update guide for this?

Currently i following guide for this, https://github.com/BlockchainTranslator/EOS/wiki/Local-Environment and this, https://developers.eos.io/eosio-nodeos/docs/keosd-overview

I was trying to setup the EOS blockchain and wanted to build a EOS blockchain based dApps for wallet function only.

**Comment by hellguard0** [comment]
docker-compose up is working already. I tried to check the nodeosd but it seems required to create the alias for nodeosd as i using Windows powershell. I am quite new to this. so nodeosd is a container run on kitematic?

**Comment by ashishchandr70** [comment]
Hi,

I am having an issue creating the alias for cleos using Windows Powershett:

The command in the documentation [documentation](https://developers.eos.io/eosio-nodeos/docs/docker-quickstart) is 

**alias cleos='docker exec -it eosio /opt/eosio/bin/cleos -u http://0.0.0.0:8888 --wallet-url http://0.0.0.0:8888'**

Using the Windows terminology, I changed the command to:

New-Alias -Name cleos" -Value 'docker exec -it eosio /opt/eosio/bin/cleos -u http://0.0.0.0:8888 --wallet-url http://0.0.0.0:8888'

The alias gets set successfully: 

PS C:\WINDOWS\system32> alias cleos

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           cleos -> docker exec -it eosio /opt/eosio/bin/c...

But, when I type **cleos**, this is what I get:

**PS C:\WINDOWS\system32> cleos**
cleos : The term 'docker exec -it eosio /opt/eosio/bin/cleos -u http://0.0.0.0:8888 --wallet-url http://0.0.0.0:8888'
is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name,
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ cleos
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (docker exec -it...://0.0.0.0:8888:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


When I just type the aliased command at the Windows Powershell prompt, it seems to be working fine. 

**PS C:\WINDOWS\system32> docker exec -it eosio /opt/eosio/bin/cleos -u http://0.0.0.0:8888 --wallet-url http://0.0.0.0:8888**
ERROR: RequiredError: Subcommand required
Command Line Interface to EOSIO Client
Usage: /opt/eosio/bin/cleos [OPTIONS] SUBCOMMAND

Options:
  -h,--help                   Print this help message and exit
  -u,--url TEXT=http://127.0.0.1:8888/
                              the http/https URL where nodeos is running
  --wallet-url TEXT=http://127.0.0.1:8900/
                              the http/https URL where keosd is running
  -r,--header                 pass specific HTTP header; repeat this option to pass multiple headers
  -n,--no-verify              don't verify peer certificate when using HTTPS
  -v,--verbose                output verbose actions on error
  --print-request             print HTTP request to STDERR
  --print-response            print HTTP response to STDERR

Subcommands:
  version                     Retrieve version information
  create                      Create various items, on and off the blockchain
  get                         Retrieve various items and information from the blockchain
  set                         Set or update blockchain state
  transfer                    Transfer EOS from account to account
  net                         Interact with local p2p network connections
  wallet                      Interact with local wallet
  sign                        Sign a transaction
  push                        Push arbitrary transactions to the blockchain
  multisig                    Multisig contract commands
  sudo                        Sudo contract commands
  system                      Send eosio.system contract action to the blockchain.
PS C:\WINDOWS\system32>

Appreciate any help.

Thank you
Ashish

**Comment by anykeyjunkie** [comment]
@ashishchandr70 if you use a powershell function instead of an alias, it worked on my machine:
`function cleos { docker exec -it nodeos /opt/eosio/bin/cleos --url http://127.0.0.1:8888 --wallet-url
 http://172.18.0.3:9876 $args}`

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com or developers@eos.io
