### ISSUE TITLE
Undelegatebw has the risk of losing eos token？is deffered transaction who Use a fixed id, may dismiss or replaced by others contract?

### ISSUE THREAD

**Issue by OracleChain** [EOSIO/eos#4048]
Undelegatebw, the system will send a refund system message. The message will be executed after 3 days. When the message is executed, eos will be sent to your account. But there is a risk that after 3 days, it may be because the message is not processed or it is lost. Your shottake eos is less, but your eos balance has not increased correspondingly. If you forget about this, you may accidentally lose your eos token. If you remember this, you will be able to undelegate again. Trigger this message and look forward to the next successful execution of this message

account "from" as transaction id, may be replaced by other contracts(Malicious)?
```
if ( need_deferred_trx ) {
            eosio::transaction out;
            out.actions.emplace_back( permission_level{ from, N(active) }, _self, N(refund), from );
            out.delay_sec = refund_delay;
            out.send( from, receiver, true );
         }
```

    * Deferred transactions will not be processed until a future block.  They
    * can therefore have no effect on the success of failure of their parent
    * transaction so long as they appear well formed.  If any other condition
    * causes the parent transaction to be marked as failing, then the deferred
    * transaction will never be processed.

**Comment by wanderingbort** [comment]
> replaced by other contracts(Malicious)?

Sender ID's for deferred transactions are all scoped/namespaced to the contract.  So, only the system contract can overwrite/modify this which is a feature as this code will overwrite in-flight refunds with updated values as you unstake more tokens.  No _other_ contract can interfere here.

> If you forget about this, you may accidentally lose your eos token.

You won't lose your tokens.  

If we assume the deferred transaction is dropped, then the automatic execution of the `refund` action will never happen.

This leaves the contract state where your account has an entry in the `refunds_tbl` with a `request_time` consistent such that at any time you as the user can post a `refund` action to trigger the delivery of the refunded tokens to your liquid balance. 

So, worst case scenario, the deferred transaction is dropped and you execute another undelegate call which resets the timer and causing a longer than expected delay for your tokens.

However, they are never lost.

**Comment by OracleChain** [comment]
Thank you!
