### ISSUE TITLE
contract print bug

### ISSUE THREAD

**Issue by urbanvice** [EOSIO/eos#4054]
I created a new contract with command
`eosiocpp -n hello`
following is the hello.cpp 
![image](https://user-images.githubusercontent.com/24699417/41287875-ce9fba8a-6e76-11e8-9daf-b1642bd34128.png)
after I deploy it, run command
`cleos push action inb hi '["tester"]' -p tester`
successfully, but print nothing, How to fix this？

**Comment by heifner** [comment]
Add `--contracts-console` to your nodeos.
