### ISSUE TITLE
push_transaction with type "bytes" fails unless action.data is hex

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#4055]
action.data as object
```bash
api error => { message: 'Failed to deserialize data for eosio:buyrambytes',
  file: 'abi_serializer.hpp',
  line_number: 417,
  method: 'extract' } http://127.0.0.1:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-06-12T15:43:49","ref_block_num":623,"ref_block_prefix":4050859248,"net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"eosio","permission":"active"}],"data":{"creator":"eosio","name":"myaccount","owner":{"threshold":1,"keys":[{"key":"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","weight":1}],"accounts":[],"waits":[]},"active":{"threshold":1,"keys":[{"key":"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","weight":1}],"accounts":[],"waits":[]}}},{"account":"eosio","name":"buyrambytes","authorization":[{"actor":"eosio","permission":"active"}],"data":{"payer":"eosio","receiver":"myaccount","bytes":8192}},{"account":"eosio","name":"delegatebw","authorization":[{"actor":"eosio","permission":"active"}],"data":{"from":"eosio","receiver":"myaccount","stake_net_quantity":"10.0000 SYS","stake_cpu_quantity":"10.0000 SYS","transfer":0}}],"transaction_extensions":[]},"signatures":["SIG_K1_Jy2oHSmkKyn7bXWzgGVjBJhSfYh8uJ1yvsfWj8muXLiWUup2C1dYUs3pzDvcESmicyetsDVaFNC64B9kyUFgm2R917kXgh"]}
```
action.data as hex
```bash
api > http://127.0.0.1:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-06-12T15:47:16","ref_block_num":25,"ref_block_prefix":1888660601,"net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000ea30550000c85353848c9701000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf0100000001000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf01000000"},{"account":"eosio","name":"buyrambytes","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000ea30550000c85353848c9700200000"},{"account":"eosio","name":"delegatebw","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000ea30550000c85353848c97a0860100000000000453595300000000a086010000000000045359530000000000"}],"transaction_extensions":[]},"signatures":["SIG_K1_KVKNDaxxu23CRGsLYCoj4humPrvJMRpN8FdqpMcH9FpoMAoozy7pPynKGD4rjc8nwSKysNNUvQgweP882tMwd9GXouoFyo"]}
api < { transaction_id: '588ac8e814f64ef886d2fe6418c4b4c4a6bbbe7dbc43f0edaa8378a1536d2c25',
  processed: 
   { id: '588ac8e814f64ef886d2fe6418c4b4c4a6bbbe7dbc43f0edaa8378a1536d2c25',
     receipt: { status: 'executed', cpu_usage_us: 293, net_usage_words: 42 },
     elapsed: 293,
     net_usage: 336,
     scheduled: false,
     action_traces: [ [Object], [Object], [Object] ],
     except: null } }
```

**Comment by halocq** [comment]
@jcalfee Please tell me how you make object to hex?

**Comment by jcalfee** [comment]
I just realized something.. I was testing this with eosio.bios deployed (not eosio.system) so this test must be invalid.  The buyrambytes does not exist until the system contract is deployed.  I think I need to add some RAM bits to the market to test this properly .. This is not your bug.

Although it would be better to report something along these lines:
```c++
Action eosio:buyrambytes does not exist
```

Back to your question.  The hex in action.data it is the serialized bytes just like what is stored on the blockchain..  Mostly you can use either JSON or HEX there and the back-end code will convert either to the same binary.  HEX is binary as-is and JSON must have all known FC_REFLECT types.

This is one way to create those bytes:
```jc
> require('eosjs)().fc.toBuffer('buyrambytes', {payer: 'eosio',receiver: 'myaccount',bytes: 8192}).toString('hex')
'0000000000ea30550000c85353848c9700200000'
```

It looks like you can use abi_json_to_bin to do this too.  Here is the API call docs:
```json
"abi_json_to_bin": {
    "brief": "Manually serialize json into binary hex.  The binayargs is usually stored in Action.data.",
    "params": {
      "code": "name",
      "action": "name",
      "args": "bytes"
    },
    "results": {
      "binargs": "bytes"
    }
  }
```
```js
> Buffer.from('{"payer":"eosio","receiver":"myaccount","bytes":8192}').toString('hex')
'7b227061796572223a22656f73696f222c227265636569766572223a226d796163636f756e74222c226279746573223a383139327d'
```
```bash
$ curl -X POST -d '{"code":"eosio","action":"buyrambytes","args":"7b227061796572223a22656f73696f222c227265636569766572223a226d796163636f756e74222c226279746573223a383139327d"}' http://localhost:8888/v1/chain/abi_json_to_bin
{"binargs":""}
```

**Comment by jcalfee** [comment]
This looks like a cool way to create the HEX data: https://github.com/EOSIO/abieos

I wonder if this will compile to wasm..

**Comment by halocq** [comment]
I see, thx

**Comment by halocq** [comment]
this is transaction
`transaction =     {
        actions =         (
                        {
                account = eosio;
                authorization =                 (
                                        {
                        actor = eosio;
                        permission = active;
                    }
                );
                data = 000000000000263d0000000000a0929b010000000100039c5cfda31d5d4cf4f04225ac7cffccce19216a80dd0d39cf52361a0cc957086a0100000001000000010003f3d3de7d6210d3ae204a276bb9ff9c5154968b3b2073906a7597307419cb5bfb01000000;
                name = newaccount;
            }
        );
        "context_free_actions" =         (
        );
        "context_free_data" =         (
        );
        "delay_sec" = 0;
        expiration = "2018-06-29T11:26:28";
        "max_kcpu_usage" = 0;
        "max_net_usage_words" = 0;
        "ref_block_num" = 54223;
        "ref_block_prefix" = 1045091400;
        signatures =         (
        );
    };`

and this is action.data
` {
    action = newaccount;
    args =     {
        active =         {
            accounts =             (
            );
            keys =             (
                                {
                    key = EOS8gcn9TJv8daUqCurjP5QfprFwUoxbL3LoXVLBMJtF2VibaygEY;
                    weight = 1;
                }
            );
            threshold = 1;
            waits =             (
            );
        };
        creator = eosio;
        name = nide;
        owner =         {
            accounts =             (
            );
            keys =             (
                                {
                    key = EOS826csYH9LxEt6FwmjaJL71jSioX4zEo5ktbXkXq5wbmqbossxc;
                    weight = 1;
                }
            );
            threshold = 1;
            waits =             (
            );
        };
    };
    code = eosio;
}`

**Comment by jcalfee** [comment]
probably unrelated

**Comment by taokayan** [comment]
We haven't received any update for this. I think the behaviour described in this ticket is by designed. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
