### ISSUE TITLE
eosio main-net After the synchronization is complete, an error is reported !!!version mainnet-1.0.2.2 

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#4073]
5852, conf: 0, latency: 1338 ms]
217532ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block ccd98d7b9bfd05b2... #475854 @ 2018-06-13T05:03:36.000 signed by genesisblock [trxs: 0, lib: 475853, conf: 0, latency: 1532 ms]
217535ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 7a3eba4e1a755edd... #475855 @ 2018-06-13T05:03:36.500 signed by genesisblock [trxs: 0, lib: 475854, conf: 0, latency: 1035 ms]
218231ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 563ab98123a0f45c... #475856 @ 2018-06-13T05:03:37.000 signed by genesisblock [trxs: 0, lib: 475855, conf: 0, latency: 1231 ms]
218238ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 566b7ae6fab1ff0f... #475857 @ 2018-06-13T05:03:37.500 signed by genesisblock [trxs: 1, lib: 475856, conf: 0, latency: 738 ms]
218585ms thread-0   net_plugin.cpp:1507           verify_catchup       ] got a catch_up notice while in in sync, fork head num = 475858 target LIB = 475857 next_expected = 475858
218932ms thread-0   controller.cpp:855            push_block           ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d346b36b4d991458db9c5f16721342d6645c58f95ad183019bf7e2d3be","previous":"000742d2da77811eea278e802d2b0de2a220349e64654baa78f0bdee0a3ccf70"}
    thread-0  fork_database.cpp:152 add
218933ms thread-0   producer_plugin.cpp:274       on_incoming_block    ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d346b36b4d991458db9c5f16721342d6645c58f95ad183019bf7e2d3be","previous":"000742d2da77811eea278e802d2b0de2a220349e64654baa78f0bdee0a3ccf70"}
    thread-0  fork_database.cpp:152 add
rethrow
    {}
    thread-0  controller.cpp:855 push_block
219213ms thread-0   controller.cpp:855            push_block           ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d42c45bd0fe20a8db72d2274ffa07e26ac7c01b0e8efa5995145cfe898","previous":"000742d346b36b4d991458db9c5f16721342d6645c58f95ad183019bf7e2d3be"}
    thread-0  fork_database.cpp:152 add
219214ms thread-0   producer_plugin.cpp:274       on_incoming_block    ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d42c45bd0fe20a8db72d2274ffa07e26ac7c01b0e8efa5995145cfe898","previous":"000742d346b36b4d991458db9c5f16721342d6645c58f95ad183019bf7e2d3be"}
    thread-0  fork_database.cpp:152 add
rethrow
    {}
    thread-0  controller.cpp:855 push_block
219713ms thread-0   controller.cpp:855            push_block           ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d55f251cd172e33755ab1fee9eb8b2c3e0c5c64c83e4b1f50963f652d4","previous":"000742d42c45bd0fe20a8db72d2274ffa07e26ac7c01b0e8efa5995145cfe898"}
    thread-0  fork_database.cpp:152 add
219714ms thread-0   producer_plugin.cpp:274       on_incoming_block    ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d55f251cd172e33755ab1fee9eb8b2c3e0c5c64c83e4b1f50963f652d4","previous":"000742d42c45bd0fe20a8db72d2274ffa07e26ac7c01b0e8efa5995145cfe898"}
    thread-0  fork_database.cpp:152 add
rethrow
    {}
    thread-0  controller.cpp:855 push_block
220213ms thread-0   controller.cpp:855            push_block           ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d67bb97a79cee6c719c56d97fbe16ac54fbec20208c76a8c5bbd94f10a","previous":"000742d55f251cd172e33755ab1fee9eb8b2c3e0c5c64c83e4b1f50963f652d4"}
    thread-0  fork_database.cpp:152 add
220214ms thread-0   producer_plugin.cpp:274       on_incoming_block    ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d67bb97a79cee6c719c56d97fbe16ac54fbec20208c76a8c5bbd94f10a","previous":"000742d55f251cd172e33755ab1fee9eb8b2c3e0c5c64c83e4b1f50963f652d4"}
    thread-0  fork_database.cpp:152 add
rethrow
    {}
    thread-0  controller.cpp:855 push_block
220713ms thread-0   controller.cpp:855            push_block           ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d73f33c078db133ca344c5c11eba925ceff7f10d85edacbfbb3759b3ac","previous":"000742d67bb97a79cee6c719c56d97fbe16ac54fbec20208c76a8c5bbd94f10a"}
    thread-0  fork_database.cpp:152 add
220713ms thread-0   producer_plugin.cpp:274       on_incoming_block    ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d73f33c078db133ca344c5c11eba925ceff7f10d85edacbfbb3759b3ac","previous":"000742d67bb97a79cee6c719c56d97fbe16ac54fbec20208c76a8c5bbd94f10a"}
    thread-0  fork_database.cpp:152 add
rethrow
    {}
    thread-0  controller.cpp:855 push_block
221213ms thread-0   controller.cpp:855            push_block           ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d8a884b339d7b9d5218915f5592b49830cfe5973e65d8bc5c6ccf72d6a","previous":"000742d73f33c078db133ca344c5c11eba925ceff7f10d85edacbfbb3759b3ac"}
    thread-0  fork_database.cpp:152 add
221214ms thread-0   producer_plugin.cpp:274       on_incoming_block    ] 10 assert_exception: Assert Exception
prior != by_id_idx.end(): unlinkable block
    {"id":"000742d8a884b339d7b9d5218915f5592b49830cfe5973e65d8bc5c6ccf72d6a","previous":"000742d73f33c078db133ca344c5c11eba925ceff7f10d85edacbfbb3759b3ac"}
    thread-0  fork_database.cpp:152 add
rethrow
    {}
    thread-0  controller.cpp:855 push_block

**Comment by datudou** [comment]
I met the same issue yesterday. I try restart  nodeosd with "--replay-blockchain". After waiting a long time (about twenty mins). It works again without these error logs. But I don't figure out the reason cause it.

**Comment by andrei-anisimov** [comment]
I have somewhat similar problem. After downloading all blocks, I began getting many new invalid blocks signed by 'genesisblock'.

**Comment by andriantolie** [comment]
It seems like you are connected to a block producer that is forking. Do you still have this issue?

**Comment by sivachaitanya** [comment]
yeah starting the nodeos with --replay-blockchain solved the problem for me. but didnt really understand how it solved the sync problem ?
