### ISSUE TITLE
[Darwin] Could not find a configuration file for package "libbson-static-1.0"

### ISSUE THREAD

**Issue by dimakomar** [EOSIO/eos#4080]
OS name: Darwin
	OS Version: 10.13.5
	CPU speed: 2.70Ghz
	CPU cores: 4
	Physical Memory: 16 Gbytes
	Disk install: /dev/disk1s1
	Disk space total: 465G
	Disk space available: 114G

CMake Error at src/bsoncxx/CMakeLists.txt:86 (find_package):
  Could not find a configuration file for package "libbson-static-1.0" that
  is compatible with requested version "1.10.0".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/libbson-static-1.0/libbson-static-1.0-config.cmake, version: 1.9.3

-- Configuring incomplete, errors occurred!
See also "/tmp/mongo-cxx-driver/build/CMakeFiles/CMakeOutput.log".
	Cmake has encountered the above errors building the MongoDB C++ driver.
	Exiting now.

Can't get over it for a couple of hours, any ideas ?

**Comment by FliGhTzZ** [comment]
Experiencing same issue as OP on Mac OS 10.13.4. This is the same issue as https://github.com/EOSIO/eos/issues/4062 . The fixes there didn't help me. Anyone have ideas?

**Comment by FliGhTzZ** [comment]
I experienced the same issue. Looks like the recent stable version of https://github.com/mongodb/mongo-cxx-driver.git needs 1.10.0 whereas v3.2 only needs 1.9.3, what we have.
So to fix, we change the references to https://github.com/mongodb/mongo-cxx-driver.git from recent/stable to recent/v3.2. i.e. change line 319 in eosio_build_darwin.sh to 
`if ! git clone https://github.com/mongodb/mongo-cxx-driver.git --branch releases/v3.2 --depth 1`

**Comment by lglove** [comment]
@FliGhTzZ it's good for me, thx

**Comment by d4vidadams** [comment]
Also had to remove /tmp/mongo-cxx-driver after changing that line in eosio_build_ubuntu.sh
