### ISSUE TITLE
how build down release package ??

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#4087]
eos-mainnet-1.0.2.2.tar.gz 
after Unpack.
cd eos-mainnet-1.0.2.2

 ./eosio_build.sh

	This build script only works with sources cloned from git
	Please clone a new eos directory with 'git clone https://github.com/EOSIO/eos --recursive'
	See the wiki for instructions: https://github.com/EOSIO/eos/wiki

Why not compile, if not use, what is the use of this release package?
thanks!!!!!!

**Comment by gleehokie** [comment]
GitHub generates these files on release automatically and it does not include the git submodules, so you can't build them without a lot of manual work.  If you want to use the `eosio_build.sh` script you must `git clone` with the `--recursive` option to get the submodules.

We leave the package for those that cannot use git and who still want to download the source code to read/review it.
