### ISSUE TITLE
DAWN-484 ⁃ Unify Memory api and other api tests

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#409]
This is an artifact of the review of #400 

Right now the memory contract API's tests are not integrated to the testing rig @elmato created.  For maintenance concerns we should probably unify that.

Additionally, there is an open question of whether the `/contracts/` directory should be for examples and "real" contracts only and if that is true, should we create a `/test/contracts/` tree for unit tests etc.

**Comment by andriantolie** [comment]
Looking at the #400 latest commit and the latest code, this task looks to be completed. I'm closing this issue
