### ISSUE TITLE
"Bad Cast" error on list_keys

### ISSUE THREAD

**Issue by egonson** [EOSIO/eos#4090]
list_keys throws an exception.

curl http://localhost:8888/v1/wallet/list_keys

{"code":500,"message":"Internal Service Error","error":{"code":7,"name":"bad_cast_exception","what":"Bad Cast","details":[{"message":"Invalid cast from object_type to Array","file":"variant.cpp","line_number":535,"method":"get_array"}]}}

used version: v1.0.2

**Comment by jgiszczak** [comment]
`list_keys` now requires an argument, which is your wallet password.

`curl --request POST --url http://localhost:8900/v1/wallet/list_keys --data '["default","PWxxxxxxxxxxxxx"]`
