### ISSUE TITLE
Error 3081001: transaction reached the deadline set due to leeway on account CPU limits

### ISSUE THREAD

**Issue by tti6o** [EOSIO/eos#4091]
I create a new account is always unsuccessful。
The error is as follows：

`root@ubuntu:/data/eosio/eosio-wallet# cleos system newaccount --stake-net '0.001 EOS' --stake-cpu '0.9 EOS' --buy-ram-kbytes 3 exchangenode bixudamocoin EOS4vsKVfuk8JZxNRGnnj6sPjWkxt6qa9pPjfBVxESqs1GfSRAv1S
2716864ms thread-0   main.cpp:430                  create_action        ] result: {"binargs":"a0129d8a4dd35057301d45549aa4bb3b000c0000"} arg: {"code":"eosio","action":"buyrambytes","args":{"payer":"exchangenode","receiver":"bixudamocoin","bytes":3072}} 
2717637ms thread-0   main.cpp:430                  create_action        ] result: {"binargs":"a0129d8a4dd35057301d45549aa4bb3b0a0000000000000004454f5300000000282300000000000004454f530000000000"} arg: {"code":"eosio","action":"delegatebw","args":{"from":"exchangenode","receiver":"bixudamocoin","stake_net_quantity":"0.0010 EOS","stake_cpu_quantity":"0.9000 EOS","transfer":false}} 
Error 3081001: transaction reached the deadline set due to leeway on account CPU limits
Error Details:
the transaction was unable to complete by deadline, but it is possible it could have succeeded if it were allowed to run to completion
`

cleos:
`alias cleos='docker exec -i keosd /opt/eosio/bin/cleos  --wallet-url http://127.0.0.1:8900  -u http://mainnet.eoswz.com:80/'
`

my balance:
`root@ubuntu:/data/eosio/eosio-wallet# cleos get currency balance eosio.token exchangenode
1.1000 EOS
`

Is it because the mortgage eos is not enough? 
Is there a way to know the current amount of mortgage required？

**Comment by lcgogo** [comment]
Have the same issue. The log of node is like:

`66906ms thread-0   net_plugin.cpp:2546           operator()           ] accept txn threw  3081001 leeway_deadline_exception: transaction reached the deadline set due to leeway on account CPU limits
the transaction was unable to complete by deadline, but it is possible it could have succeeded if it were allowed to run to completion
    {"now":"2018-06-22T12:01:06.906","deadline":"2018-06-22T12:01:06.686","start":"2018-06-22T12:01:06.651","billing_timer":254526}
    thread-0  transaction_context.cpp:301 checktime

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:62 exec_one`

**Comment by fundurian** [comment]
same error how to fix?

**Comment by andriantolie** [comment]
Yes, it's very likely that you have used all of your staked cpu quota. Stake more cpu for this or wait until your cpu usage decreases before you try again.

**Comment by MarkStair** [comment]
I'm not able to stake more cpu because I don't have enough cpu to run that command!
How do i get cpu and bandwidth from an account with none?

**Comment by andriantolie** [comment]
If you don't even have enough cpu to run that command, you can ask somebody to stake cpu for you. Or when the overall total cpu usage, you will be able to utilize the idle cpu usage.

**Comment by lBlankl** [comment]
@andriantolie How long will is the wait?

**Comment by andriantolie** [comment]
It really depends on the other transactions in the network.
