### ISSUE TITLE
mainnet get accounts error !!!version mainnet-1.0.2.2

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#4092]
cleos  get accounts EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
1380651ms thread-0   main.cpp:2659                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 404
: {"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"Unknown Endpoint","file":"http_plugin.cpp","line_number":203,"method":"handle_http_request"}]}}

my node is sync ok,other command is ok!
xteam@xteam-virtual-machine:~$ cleos system  listproducers
Producer      Producer key                                           Url                                                         Scaled votes
eosnewyorkio  EOS6GVX8eUqC1gN1293B3ivCNbifbr1BT6gzTFaQBXzWH9QNKVM4X  https://bp.eosnewyork.io                                    0.0332
eoscannonchn  EOS73cTi9V7PNg4ujW5QzoTfRSdhH44MPiUJkUV6m3oGwj7RX7kML  https://eoscannon.io                                        0.0324
eoscanadacom  EOS5HYV7rWeRxpZMCooe8YHRFQHKK7ncdmmUMTe3wCMaY2EvyVzUx  https://www.eoscanada.com                                   0.0317
eosauthority  EOS4va3CTmAcAAXsT26T3EBWqYHgQLshyxsozYRgxWm9tjmy17pVV  https://eosauthority.com                                    0.0286
eoshuobipool  EOS5XKswW26cR5VQeDGwgNb5aixv1AMcKkdDNrC59KzNSBfnH6TR7  http://eoshuobipool.com                                     0.0286
eosdacserver  EOS7aBPDACAn1SpJDjmaZHSEUgqfNWdUaNawVZhVuEWUx5aoepJf6  https://eosdac.io                                           0.0282
eosisgravity  EOS55HTTjoxVX1zVpW8pabxygBb1J3SEnG5D8D3y3KgrnSbLpELfE  http://eosgravity.com                                       0.0274
eoscafeblock  EOS7MAPWVuYcxNtc2n9e6WaEedEZd9thGVHn2Wpu2PoMhNiteTTqL  https://eoscafecalgary.com                                  0.0249
eosswedenorg  EOS7SGSBsWhSob6TEric6u3TGodcc1uXFcqSrquJ3Etuqcbb3VnNY  https://eossweden.se                                        0.0244
eosyskoreabp  EOS7TjKVBkBcSmjsXF4jJfZ1QU9RqVHuBkkcHNJoEcHGR79CoLf2f  http://eosys.io                                             0.0241
eosbeijingbp  EOS5dGpcEhwB4VEhhXEcqtZs9EQj5HeetuXDnsAGVHMXHAFdMjbdj  http://www.eosbeijing.one                                   0.0238
eoseouldotio  EOS6SSA4gYCSZ3q9NWpxGsYDv5MWjSwKseyq25RRZexwj8EM6YHDa  https://portal.eoseoul.io                                   0.0233
eosiomeetone  EOS5gS4ZtanRS2Jx4vpjAQaVNci3v65iZiGCgMr9DNwu67x2pt8Qd  https://meet.one                                            0.0227
eosliquideos  EOS4v1n2j5kXbCum8LLEc8zQLpeLK9rKVFmsUgLCWgMDN38P6PcrW  http://vote.liquideos.com/                                  0.0225
eos42freedom  EOS4tw7vH62TcVtMgm2tjXzn9hTuHEBbGPUK2eos42ssY7ip4LTzu  https://www.eos42.io                                        0.0222
eosstorebest  EOS8FrjiXUDAFc8pSQkFejk1zRxyALnqPbYdJsqhAwKMya3tY7TaU  http://www.eos.store                                        0.0217
bitfinexeos1  EOS6sgKjHUFtY1XxxQaMDwfxBac6nDBibVzZHb8LFMVmvSjcCdDhE  https://www.bitfinex.com                                    0.0216
eosasia11111  EOS76gG6ATpqfVf5KrVjh3f4JAa4EKzAwWabTucNQ4Xv2TmVAj9bN  https://www.eosasia.one                                     0.0207
helloeoscnbp  EOS79cHpaEittzgJWgj79tdRhgzLEWy8wXmmQ3fL7kkDjmYYiGNet  https://www.helloeos.com.cn                                 0.0202
eosnationftw  EOS8PkNNBYU1xnbcjBUNm1mT6N68QiGvCDgPT97rqurLBEjDanSXK  https://bp.eosnation.io                                     0.0198
sheos21sheos  EOS5nUybopuNRPp4Lgpt3BCxT3j2Zw3BftJha8gLbJFvMQBMC3ToL  https://sheos.org                                           0.0194
eoslaomaocom  EOS8QgURqo875qu3a8vgZ58qBeu2cTehe9zAWRfpdCXAQipicu1Fi  https://eoslaomao.com                                       0.0192
cypherglasss  EOS5rTrUiqvgu7YCVyKCeQ1QXA7Uo94FZhq7zKcNPqbrCP5u5fQXo  http://cypherglass.com                                      0.0189
argentinaeos  EOS7jq4FHrFrtCXxpRQ39dBeDMa5AjM4VaRbqBECkSa5aZnizJzrx  https://www.eosargentina.io                                 0.0182
eosnodeonebp  EOS6xcmB3LnUwcjFu55hKFQwX8EHWWerwbHyAs3VpaJmbBFp4bmDs  http://www.eosnodeone.io                                    0.0181
eosflytomars  EOS6Agpfp38bTyRjJDmB4Qb1EpQSq7wnEAsALXgXE7KFSzKjokkFD  http://www.bitmars.one                                      0.0173
eosriobrazil  EOS7RioGoHQnhv2fJEiciP9Q7J8JgfJYFcyofVkmCqMop8Q1PzgqP  https://eosrio.io                                           0.0170
libertyblock  EOS5jDCYph3hctKED9tHbe9L77q8JZToeuMnefMDdyfPkrb89FzSt  http://libertyblock.io                                      0.0170
tokenika4eos  EOS8Src8Nd3EoJpewmPzSDjZP8A3iLuHky4itLqWwuCjPNdCztrVL  https://tokenika.io/                                        0.0154
teamgreymass  EOS4xurP5oZk4WvMUp9neKkw94DJ2iq48GtMD5Dff3GKe6krh2ctR  https://greymass.com                                        0.0152
eosbixinboot  EOS7QC1XfAtkYeLjbHQjcDWVqUsxuSJ3YRhNyG93VAv2u3uHopGVp  http://en.eosbixin.com                                      0.0124
zbeosbp11111  EOS7rhgVPWWyfMqjSbNdndtCK8Gkza3xnDbUupsPLMZ6gjfQ4nX81  http://www.zbeos.com                                        0.0119
eossv12eossv  EOS7fv6nadePJBdCiWyR2Ldz5YWyzJGMBkEo47zUSWFttduQhHHaa  https://eossiliconvalley.io                                 0.0118
eoswenzhoubp  EOS5SQjv1G8uaxqkXh6Z5nWbKqumhGj91NMq7qkYuvT9YS45QcZsA  http://eoswz.com                                            0.0106
cryptolions1  EOS5yHaUBwhpwFftNjADdVwBpCVybLPg5P3z7HpTbDGjUfpqwWSSf  http://CryptoLions.io                                       0.0106
eosphereiobp  EOS5FYRrG3ThNU56d3uZ8d4bo4MsN5Fig9WPY3xYSpH3RqPhpoH3A  https://www.eosphere.io                                     0.0105
oraclegogogo  EOS67BuVBFqC9wWw8NaDg7JZ3FseSg55Rvwh6NJQUehBhmEsHfmLh  https://oraclechain.io                                      0.0104
hkeoshkeosbp  EOS8SXELcUbgtBTmi7of9CJTUc6eGPw68G8ph7nLD7wpHkEosEShs  https://www.hkeos.com                                       0.0087
eosnairobike  EOS54UAELQVaMrc1y98W7KsfLbBchvsQg7FCEYpoiQLi5y1Gvyqcy  www.eosnairobi.io                                           0.0085
eosdublinwow  EOS5bjub7pm8H9WLMYW5ETSwfFKrEJpVWwiwK5knvGAqLVUjEpLxx  https://eosdublin.com                                       0.0084
eosunion1111  EOS5YrPTWCKNHHLuntq13Q9X6M2CFCNGb21GqrcjUexqBBjxpCG7H  http://eosunion.io/                                         0.0077
eosamsterdam  EOS8HDwgQnKMHAxzva9eyHsPeETv23JSQ6RRzQjJLvCsZ6b1ySgQo  https://eosamsterdam.net                                    0.0076
eostribeprod  EOS6J5d6rwHJYPZnuv7KRrf5cekTf3atRTjMgbU1YMKuNnrgGvEdE  https://eostribe.io                                         0.0073
eosonoeosono  EOS5AHfFwaJxjMPkrufw4aCTFvJJUVgpwqwvghhYrFahik7oxaXah  https://ono.chat                                            0.0071
unlimitedeos  EOS8jjSeSmwX4kxMbpo8G4uibMnhf52QrGi4f9N7Zd3jY6oYVt9g6  http://www.unlimitedeos.com/bp.json                         0.0070
jrrcryptoeos  EOS7JR4vL3P2qgPwfMagZDqAtRLjB38qQCe6xw87gefVV73x85bsw                                                              0.0069
jedaaaaaaaaa  EOS5XP49jx9eJNQZjqvP7pfKNaAe5JmyAbPZMdsiqD61QQEExqUYe  http://www.eosjapan.org                                     0.0067
aus1genereos  EOS57ZyzVjoEG2bvzmYmmeiH8YnYtRudxNKxppx17q7Hg29F8tW4t  http://www.genereos.io                                      0.0061
bitspacenode  EOS7HvfCTxaL4DwokbZRsbrXXQafzE6wcG38azf6WefKGHBqsE3Ad  https://eos.bitspace.no                                     0.0059
bp2bp2bp2bp2  EOS64imhc1mStfLdkK6Po3juwwyiiSD9RsevSoSWx8vBqP3opUx2L  https://bp2.io                                              0.0056
-L acroeos12345 for more

thanks !!!!!!!!

**Comment by samvel12** [comment]
Hi, did you get this issue resolved? I am experiencing the same problem

**Comment by shishi614** [comment]
Others have similar themes

**Comment by shishi614** [comment]
add two plugin
plugin = eosio::http_plugin
plugin = eosio::history_plugin
