### ISSUE TITLE
3100002 : unknown_block_exception

### ISSUE THREAD

**Issue by ItVen** [EOSIO/eos#4093]
when I use curl --request POST \
  --url http://127.0.0.1:8888/v1/chain/get_block_header_state \
  --data '{"block_num_or_id":"1"}'
it return 500 
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3100002,
    "name": "unknown_block_exception",
    "what": "unknown block",
    "details": [
      {
        "message": "Could not find reversible block: 1",
        "file": "chain_plugin.cpp",
        "line_number": 846,
        "method": "get_block_header_state"
      }
    ]
  }
}

the nodeos logs is 
1719060ms thread-0   http_plugin.cpp:396           handle_exception     ] FC Exception encountered while processing chain.get_block_header_state: 3100002 unknown_block_exception: unknown block
Could not find reversible block: 1
    {"block":"1"}
    thread-0  chain_plugin.cpp:846 get_block_header_state

**Comment by ItVen** [comment]
cleos get block --header-state 1
Error 3100002: unknown block
Error Details:
Could not find reversible block: 1

cleos get block 1
{
  "timestamp": "2018-06-01T12:00:00.000",
  "producer": "",
  "confirmed": 1,
  "previous": "0000000000000000000000000000000000000000000000000000000000000000",
  "transaction_mroot": "0000000000000000000000000000000000000000000000000000000000000000",
  "action_mroot": "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f",
  "schedule_version": 0,
  "new_producers": null,
  "header_extensions": [],
  "producer_signature": "SIG_K1_111111111111111111111111111111111111111111111111111111111111111116uk5ne",
  "transactions": [],
  "block_extensions": [],
  "id": "00000001bcf2f448225d099685f14da76803028926af04d2607eafcf609c265c",
  "block_num": 1,
  "ref_block_prefix": 2517196066
}

**Comment by ItVen** [comment]
unknown_block_exception How can I do

**Comment by andriantolie** [comment]
You can only use --header-state argument for a block that is not yet irreversible. :)
