### ISSUE TITLE
Http API params error

### ISSUE THREAD

**Issue by m13oas** [EOSIO/eos#4097]
Http API reference at [dev site](https://developers.eos.io/eosio-nodeos/reference) said that wallet create_key should invoked with Json Object. This is bug, because create_key working with Json array.
For example:
 --data '["foo", "K1"]' instead --data '{"name":"foo","key_type":"R1"}'

Please, fix it.

**Comment by rbw3821** [comment]
Confirmed the documentation should list the array of parameters instead of the json object.

**Comment by rbw3821** [comment]
Change has been made and will appear in the published update of the reference.
