### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Vurdalacky** [EOSIO/eos#4098]
New instance ubuntu 18.04

$git clone https://github.com/EOSIO/eos.git
$cd eos/
$git checkout tags/v1.0.3
$git submodule update --init --recursive
$./eosio_build.sh 
...
make[3]: Leaving directory '/tmp/mongo-c-driver-1.9.3'
 /bin/mkdir -p '/usr/local/include/libmongoc-1.0'
 /usr/bin/install -c -m 644 src/mongoc/mongoc-apm.h src/mongoc/mongoc-bulk-operation.h src/mongoc/mongoc-change-stream.h src/mongoc/mongoc-client.h src/mongoc/mongoc-client-pool.h src/mongoc/mongoc-collection.h src/mongoc/mongoc-cursor.h src/mongoc/mongoc-database.h src/mongoc/mongoc-error.h src/mongoc/mongoc-find-and-modify.h src/mongoc/mongoc-flags.h src/mongoc/mongoc-gridfs-file.h src/mongoc/mongoc-gridfs-file-list.h src/mongoc/mongoc-gridfs-file-page.h src/mongoc/mongoc-gridfs.h src/mongoc/mongoc.h src/mongoc/mongoc-handshake.h src/mongoc/mongoc-host-list.h src/mongoc/mongoc-index.h src/mongoc/mongoc-init.h src/mongoc/mongoc-iovec.h src/mongoc/mongoc-log.h src/mongoc/mongoc-macros.h src/mongoc/mongoc-matcher.h src/mongoc/mongoc-opcode.h src/mongoc/mongoc-rand.h src/mongoc/mongoc-read-concern.h src/mongoc/mongoc-read-prefs.h src/mongoc/mongoc-server-description.h src/mongoc/mongoc-client-session.h src/mongoc/mongoc-socket.h src/mongoc/mongoc-ssl.h src/mongoc/mongoc-stream-buffered.h src/mongoc/mongoc-stream-file.h src/mongoc/mongoc-stream-gridfs.h src/mongoc/mongoc-stream.h src/mongoc/mongoc-stream-socket.h src/mongoc/mongoc-stream-tls.h src/mongoc/mongoc-stream-tls-libressl.h src/mongoc/mongoc-stream-tls-openssl.h '/usr/local/include/libmongoc-1.0'
 /usr/bin/install -c -m 644 src/mongoc/mongoc-stream-tls-secure-channel.h src/mongoc/mongoc-stream-tls-secure-transport.h src/mongoc/mongoc-topology-description.h src/mongoc/mongoc-uri.h src/mongoc/mongoc-version-functions.h src/mongoc/mongoc-version.h src/mongoc/mongoc-write-concern.h src/mongoc/utlist.h src/mongoc/op-delete.def src/mongoc/op-get-more.def src/mongoc/op-header.def src/mongoc/op-insert.def src/mongoc/op-kill-cursors.def src/mongoc/op-msg.def src/mongoc/op-query.def src/mongoc/op-reply.def src/mongoc/op-reply-header.def src/mongoc/op-update.def src/mongoc/op-compressed.def src/mongoc/mongoc-counters.defs src/mongoc/mongoc-config.h '/usr/local/include/libmongoc-1.0'
 /bin/mkdir -p '/usr/local/share/doc/mongo-c-driver'
 /usr/bin/install -c -m 644 COPYING NEWS README.rst THIRD_PARTY_NOTICES '/usr/local/share/doc/mongo-c-driver'
 /bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 ./src/libmongoc-1.0.pc ./src/libmongoc-ssl-1.0.pc ./src/libmongoc-static-1.0.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory '/tmp/mongo-c-driver-1.9.3'
make[1]: Leaving directory '/tmp/mongo-c-driver-1.9.3'
Cloning into 'mongo-cxx-driver'...
remote: Counting objects: 714, done.
remote: Compressing objects: 100% (628/628), done.
remote: Total 714 (delta 250), reused 254 (delta 70), pack-reused 0
Receiving objects: 100% (714/714), 1.24 MiB | 3.29 MiB/s, done.
Resolving deltas: 100% (250/250), done.
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Auto-configuring bsoncxx to use MNMLSTC for polyfills since C++17 is inactive
CMake Error at src/bsoncxx/CMakeLists.txt:86 (find_package):
  Could not find a configuration file for package "libbson-static-1.0" that
  is compatible with requested version "1.10.0".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/libbson-static-1.0/libbson-static-1.0-config.cmake, version: 1.9.3

-- Configuring incomplete, errors occurred!
See also "/tmp/mongo-cxx-driver/build/CMakeFiles/CMakeOutput.log".
	Cmake has encountered the above errors building the MongoDB C++ driver.

	Exiting now.

**Comment by SoYouDie** [comment]
The same as https://github.com/EOSIO/eos/issues/4062. Here is answer

**Comment by jgiszczak** [comment]
Closing in favor of #4602.
