### ISSUE TITLE
Error 3040007

### ISSUE THREAD

**Issue by xu10000** [EOSIO/eos#4113]
![z](https://user-images.githubusercontent.com/22340978/41446673-77616eda-7083-11e8-9c03-fbe0b19c6096.png)
I can delegate, vote, regproducer.  but can not transfer EOS,  why?   in the begining, I am transfer it.

**Comment by xu10000** [comment]
anybody can help me?

**Comment by andriantolie** [comment]
Seems like you have a problem with the TAPOS. Is your latest irreversible block somehow larger than head_block_num-2^16?

**Comment by andriantolie** [comment]
We haven't received any follow up from this. 
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
