### ISSUE TITLE
bug: dropping unexpired tx

### ISSUE THREAD

**Issue by zhaoguojie2010** [EOSIO/eos#4116]
https://github.com/EOSIO/eos/blob/24b98627ff4f6c0aaba74795ae1321fef68ff9be/plugins/producer_plugin/producer_plugin.cpp#L841

I think the if condition should be `if (trx->packed_trx.expiration() <= pbs->header.timestamp.to_time_point())`

**Comment by andriantolie** [comment]
This is already fixed with commit 45be28aa

**Comment by zhaoguojie2010** [comment]
Is it true you guys don't pay for bug reports?

**Comment by ChristianDunst** [comment]
Bug bounties are being handled via the official "eosio Bug Bounty Program". Please go here to read about eligibility and rules: https://hackerone.com/eosio
