### ISSUE TITLE
How to transfer the eos in the refund to the balance?in cleos

### ISSUE THREAD

**Issue by isifidio** [EOSIO/eos#4119]
up

**Comment by oasis-eos** [comment]
it may be automatically back to the balance when stake time is expired

**Comment by isifidio** [comment]
If must have call refund function, then what is the cleos command?

**Comment by oasis-eos** [comment]
according to the code,refund is a deferred transaction 

`            eosio::transaction out;
            out.actions.emplace_back( permission_level{ from, N(active) }, _self, N(refund), from );
            out.delay_sec = refund_delay;
            out.send( from, receiver, true );
`

**Comment by jgiszczak** [comment]
It is automatic.  The deferred transaction executes a `transfer` inline action when it is triggered at the end of its deferral period.

**Comment by yanxi-me** [comment]
@jgiszczak My eos is still in Refund after 72 hours, do you know why?

**Comment by marketstack** [comment]
did anyone figure out the cleos command for refund? 

judging by the following in ./cleos get account <account_name> i don't think its automatic, i think you have to explicitly call eosio::refund

**Comment by marketstack** [comment]
this did it

./cleos push action eosio refund '{"owner": "youraccountname"}' -p youraccountname

**Comment by yanxi-me** [comment]
@marketstack it works, thanks!

**Comment by ChenLi0830** [comment]
Hi @marketstack thank you for sharing that!

**Comment by mrzzcn** [comment]
`./cleos -u https://node1.eoscannon.io push action eosio refund '{"owner": "youraccountname"}' -p youraccountname`  full command

**Comment by samkirton** [comment]
Did this post conclude that refunds are not automatic? Or that refunds have to be triggered manually in some circumstances?

**Comment by jgiszczak** [comment]
Refunds are nominally automatic but the deferred transaction may expire before being successfully incorporated into a block.  At that point a manual refund must be invoked, as described.
