### ISSUE TITLE
The exchange contract don't have withdraw action

### ISSUE THREAD

**Issue by littlekfc** [EOSIO/eos#4120]
I saw the exchange contract don't have withdraw action but there is a withdraw function here. Is it a bug?

**Comment by jgiszczak** [comment]
The exchange contract provides deposit and withdraw action dispatching via the `EOSIO_API` macro.  See line 221.

**Comment by jgiszczak** [comment]
`eosiocpp` has some defects with regards to ABI generation.  You may need to write an ABI signature for `withdraw` by hand, at least for now.
