### ISSUE TITLE
cleos get account test1100  unknown key

### ISSUE THREAD

**Issue by qq5254232** [EOSIO/eos#4122]
root@fengqun:/opt/eos_src# cleos get account test1100
924358ms thread-0   main.cpp:2659                 main                 ] Failed with error: unspecified (0)
unknown key

**Comment by jgiszczak** [comment]
The specified account does not exist on the chain queried.  Query the correct chain, or query for an account that exists.

**Comment by qq5254232** [comment]
@jgiszczak  Please help me，Wallet account has been created

root@fengqun:/opt/eos_src# cleos wallet list
Wallets:
[
  "beidukeji",
  "fengqun",
  "test",
  "test110",
  "test111",
  "test66"
]
root@fengqun:/opt/eos_src# 

root@fengqun:/opt/eos_src# cleos get account fengqun
2248820ms thread-0   main.cpp:2659                 main                 ] Failed with error: unspecified (0)
unknown key

root@fengqun:/opt/eos_src# cleos get account beidukeji
2258518ms thread-0   main.cpp:2659                 main                 ] Failed with error: unspecified (0)
unknown key

**Comment by sugalivijaychari** [comment]
I am also getting the same issue.
My contract account name is battlegame.
I have set my contract.
"user" is the account i have created and also imported the private key with respective public key.
After i do the below command:(i am getting issue)
cleos push action cardgame login '["user"]' -p user@active
error 2019-07-20T19:28:16.254 thread-0  main.cpp:3896                 main                 ] Failed with error: unspecified (0)
unknown key (eosio::chain::name): cardgame

**Comment by conr2d** [comment]
@sugalivijaychari You said that contract name is `battlegame`, but why did you send transaction to `cardgame`?
