### ISSUE TITLE
Error on bios contract deploy

### ISSUE THREAD

**Issue by IvanYakimov** [EOSIO/eos#4125]
Please help me solve the problem.

I recently updated eosio to v1.0.3 and got an error while deploying bios contract. I had no such problems neither with version v1.0.2 nor with v1.0.1.
I followed the "[getting started](https://github.com/EOSIO/eos/wiki/Tutorial-Getting-Started-With-Contracts)" manual and got stuck on the line below:
`cleos set contract eosio build/contracts/eosio.bios -p eosio`.
with error:
`Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.`
Note, that I have imported the private keys and unlocked the wallet.

P.S. I don't know if it could help you, but I also struggled with creating a wallet:
`cleos wallet create`
but solved it (thanks to https://github.com/EOSIO/eos/issues/3879) by explicitly passing the port number to keosd:
`keosd --http-server-address localhost:8900`

**Comment by jgiszczak** [comment]
Include the wallet url on your cleos command line as well.

`cleos --wallet-url localhost:8900 set contract eosio build/contracts/eosio.bios -p eosio`

If your keosd has been running a while, you may need to unlock your wallet before you can sign your transaction.  Check with

`cleos --wallet-url localhost:8900 wallet list keys`

Results should be similar to:

```
Wallets:
[ 
  "default *"
]
[ 
  "EOS5vL6EKe4wAFZ9M4GArfQbpaa563YcEHB93GxrirT4UTT5YbjtA",
  "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
]
```
If the result is empty `[]`, you need to unlock.

**Comment by IvanYakimov** [comment]
Thanks, but I have already tried it earlier and unfortunately it didn't help. Moreover, the same issue remains in version v1.0.5.
``` bash
 cleos --wallet-url http://localhost:8900 wallet list keys
Wallets:
[
  "default *"
]
[
  "EOS68qW7HnQYhMtvy58Jx2jdeoHyc8quymYU7tA4xLWQAgpiQM4vW"
]
```
And I still get the error:
``` bash
cleos --wallet-url http://localhost:8900 set contract eosio ${EOSIO_SOURCE}/build/contracts/eosio.bios -p eosio
Reading WAST/WASM from /home/src/eos//build/contracts/eosio.bios/eosio.bios.wasm...
Using already assembled WASM...
Publishing contract...
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
```
Please, tell me what should I do? Or how can I provide more of useful information to help solving the problem?
