### ISSUE TITLE
Build on Ubuntu 17.04 (amd64) breaking.

### ISSUE THREAD

**Issue by siginfo** [EOSIO/eos#413]
I was trying to build eos on ubuntu 17.04 (amd64) and followed the instructions mentioned in the [README.md](https://github.com/EOSIO/eos/blob/master/README.md). 

# EOS environment
## gcc/g++ version
```note
siginfo@ubuntu:~$ gcc --version && g++ --version
gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

siginfo@ubuntu:~$ 
```
I exported following variables from bashrc, namely
## environment variables
```bash
export BOOST_ROOT=~/opt/boost_1_64_0
export BINARYEN_ROOT=~/code/binaryen
export WASM_LLVM_CONFIG=~/code/wasm-compiler/llvm/bin/llvm-config
export LLVM_DIR=~/code/wasm-compiler/llvm/lib/cmake/llvm
```
The build failure logs are located in this [gist](https://gist.github.com/siginfo/a04185df418199424f1e975a1667478b)

Am I missing something?

**Comment by gguoss** [comment]
My system is also ubuntu17.04, but compiled in ubuntu16.04, OK

**Comment by gguoss** [comment]
![fafa](https://user-images.githubusercontent.com/9285062/30382912-ff02f752-98d2-11e7-9cb4-f3af645e615c.png)
To see your problem, I changed to ubuntu17.04, compile through.

**Comment by elmato** [comment]
Your cmake log indicates that g++ is being used for compiling.

> ...
> -- The C compiler identification is GNU 6.3.0
> -- The CXX compiler identification is GNU 6.3.0
> ...

Set clang-4 as your preferred compiler before running cmake

> export CC=clang-4.0
> export CXX=clang++-4.0
> 

or use the build.sh script as indicated in the README.md

> git clone https://github.com/eosio/eos --recursive
> cd eos
> ./build.sh ubuntu # For ubuntu

**Comment by siginfo** [comment]
@elmato I tried build.sh on ubuntu 17.04 - still failing at the same stage. Attaching my run of script's build.txt (zipped) here [build.txt.zip](https://github.com/EOSIO/eos/files/1303056/build.txt.zip)

```bash
script ~/build.txt
```
Also, added a small fix to build.sh here [fix](https://github.com/siginfo/eos/commit/181580b5570966a089543cfb4dc21191f3ad74c0)

**Comment by siginfo** [comment]
@elmato @bytemaster please re-open this issue as there seems to be a genuine issue here. It seems that wasm's llvm is not compiled with cmake's -DLLVM_ENABLE_RTTI=ON option both on Linux and macOS.

I have added a fix [here](https://github.com/siginfo/eos/commit/6b1e1a56563a3a1874572c2d6765396be418f001).

Once this issue reopens - I will initiate a pull request for the same.

**Comment by elmato** [comment]
@siginfo I have successfully built the project using the current build.sh as it is now.
 The llvm toolchain that needs to have RTTI=ON is the one used to build **eosd** (because of wasm-jit).

The Ubuntu packages from https://apt.llvm.org have rtti enabled (those are the ones installed by _install_dependecies.sh_).

You can check that using llvm-config --has-rtti

```#bash
> ➜  build git:(master) ✗ llvm-config-4.0 --has-rtti                     
> YES
> ➜  build git:(master) ✗ ~/wasm-compiler/llvm/bin/llvm-config --has-rtti
> NO
> 
```

**Comment by siginfo** [comment]
@elmato are you sure that https://github.com/llvm-mirror/llvm.git and https://github.com/llvm-mirror/clang.git (because that is what is referenced in scripts/install_dependencies.sh) has the RTTI CMAKE switch 'ON'?

I tried it on my macOS - same issue with linking errors. But then when I added RTTI switch back - the build on macOS went fine.

I am now trying to build a new ubuntu-amd64-16.10 virtual machine to see if something I am not doing correctly.

**Comment by minimizeTrustLess** [comment]
hi @elmato, @siginfo, how long does it take to build? i have been doing it for a while now. More than 3hrs
scary that it might break soon. I did a fresh build on a newely installed ubuntu...maybe has a huge dependency?
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
latest log from build-----
[ 44%] Building CXX object lib/Target/CMakeFiles/LLVMTarget.dir/TargetLoweringObjectFile.cpp.o

**Comment by siginfo** [comment]
@minimizeTrustLess it took around 1:30 hrs before it failed on my machine (same as your setup). Check the build logs  [here](https://github.com/EOSIO/eos/files/1303056/build.txt.zip).
Please let us know about the build status on your machine. I tried on my another machine which is a macOS - but it failed around the same stage as on ubuntu.
I added a fix [here](https://github.com/siginfo/eos/commit/6b1e1a56563a3a1874572c2d6765396be418f001) which fixes my macOS build.
I am starting a fresh build on Linux 17.04...

**Comment by minimizeTrustLess** [comment]
@siginfo thanks for the comment, Failed as i had suspected.i left it running all the time lol, thought my laptop is 8 years old...i did not do a std output or std err...not sure if this build shell script actually writes log to something....i got tired and let my laptop run all night. woke up to see the below
i will give one more try soon. First look at screen failure looks like a linking issue.

make[2]: *** [contracts/test_api/test_api.wast] Error 127
CMakeFiles/Makefile2:338: recipe for target 'contracts/test_api/CMakeFiles/test_api.dir/all' failed
make[1]: *** [contracts/test_api/CMakeFiles/test_api.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

i see below too... not sure when this shows up in the test....
make[1]: *** [contracts/proxy/CMakeFiles/proxy.dir/all] Error 2
[  8%] Building LLVM bitcode test_math.cpp.bc
[  8%] Building LLVM bitcode test_message.cpp.bc
[  9%] Building LLVM bitcode test_print.cpp.bc
[  9%] Building LLVM bitcode test_transaction.cpp.bc
[  9%] Linking LLVM bitcode test_api.bc
[ 10%] Generating textual assembly test_api.s
[ 10%] Generating WAST test_api.wast

**Comment by siginfo** [comment]
@elmato @minimizeTrustLess I was successfully able to build on my fresh ubuntu (amd64) 17.04 machine via build.sh. I guess my clang on ubuntu was stale which was missing rtti support.

**Comment by minimizeTrustLess** [comment]
@siginfo i am trying a new one in a brand new fast laptop.

**Comment by siginfo** [comment]
@minimizeTrustLess @elmato build on my fresh macOS Sierra (10.12.6) went well with `build.sh darwin`

**Comment by minimizeTrustLess** [comment]
@siginfo it failed like this....
-- Configuring ChainBase on Linux
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/minizime/Desktop/decentralized/eos/libraries/appbase/Boost_INCLUDE_DIR
   used as include directory in directory /home/minizime/Desktop/decentralized/eos/libraries/appbase
/home/minizime/Desktop/decentralized/eos/libraries/chainbase/Boost_INCLUDE_DIR
   used as include directory in directory /home/minizime/Desktop/decentralized/eos/libraries/chainbase
/home/minizime/Desktop/decentralized/eos/libraries/fc/Boost_INCLUDE_DIR
   used as include directory in directory /home/minizime/Desktop/decentralized/eos/libraries/fc

-- Configuring incomplete, errors occurred!
See also "/home/minizime/Desktop/decentralized/eos/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.

**Comment by siginfo** [comment]
@minimizeTrustLess do this:
```bash
$ script ~/build.txt
$ ./build.sh ubuntu
$ exit
```
send the gist of the ~/build.txt file

note: don't forget to pull submodules

**Comment by minimizeTrustLess** [comment]
@siginfo doing a fresh pull and all over again....staring now :)
```
git clone https://github.com/eosio/eos --recursive
cd eos
script ~/build.txt
./build.sh ubuntu
exit
```

**Comment by minimizeTrustLess** [comment]
@siginfo @elmato looks like it finally built? if so great :D 
 98%] Building CXX object programs/eosc/CMakeFiles/eosc.dir/main.cpp.o
[ 99%] Linking CXX static library libaccount_history_api_plugin.a
[ 99%] Built target account_history_api_plugin
Scanning dependencies of target eosd
[100%] Building CXX object programs/eosd/CMakeFiles/eosd.dir/main.cpp.o
[100%] Linking CXX executable eosc
[100%] Built target eosc
[100%] Linking CXX executable eosd
[100%] Built target eosd

**Comment by minimizeTrustLess** [comment]
@siginfo @elmato Awesome sauce.. I was able to build finally. Now time for experimenting with true decentralization...
Could you please help me with getting following answered for my research, so I can get my hands dirty on this new platform?
1) Where is developer Wiki/confluence? 
2) What is the entry point to get started using this platform? API reference. Demo?
Thanks

**Comment by SheldonHH** [comment]
DLLVM_ENABLE_RTTI=1
