### ISSUE TITLE
how to deploy contract by annother account

### ISSUE THREAD

**Issue by wangzehui123456** [EOSIO/eos#4134]
Hi, I want to deploy contracts in account 'testa' with permission account 'testb'
first I authorize account 'testb'  with the activer permission of account 'testa'

cleos set account permission testa active '{"threshold" : 1, "keys" : [{"key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV", "weight": 1}], "accounts" : [{"permission":{"actor":"testb","permission":"active"},"weight":1}]}' owner 

then 
cleos set contract testa data_contract/ -p testb
error:
Ensure that you have the related authority inside your transaction!;
If you are currently using 'cleos push action' command, try to add the relevant authority using -p option.
Error Details:
missing authority of testa

**Comment by andriantolie** [comment]
What you need to do is
`cleos set contract testa data_contract/ -p testa` instead of `-p testb` here. Since you have authorized testb@active for testa@active, the wallet will find out that testa can be satisfied with testb and then sign the transaction with testb private key in the end.
