### ISSUE TITLE
Remove cleos unlock-timeout feature

### ISSUE THREAD

**Issue by heifner** [EOSIO/eos#4136]
`cleos wallet unlock` has a --unlock-timeout option but this option only does something if the wallet is not already running. If you do anything else first, like say `cleos wallet open` this is silently ignored.

Remove this option until it can be supported via rpc interface on keosd.  This could possibly confuse users into thinking their wallet will be locked quickly when it will not be.

**Comment by arhag** [comment]
Resolved by #4139.
