### ISSUE TITLE
cleos can not transfer tokens except the "eos" token 

### ISSUE THREAD

**Issue by oasis-eos** [EOSIO/eos#4137]
I modified the main.cpp of cleos and it works

diff --git a/programs/cleos/main.cpp b/programs/cleos/main.cpp
index eea34b50f..57c441f05 100644
--- a/programs/cleos/main.cpp
+++ b/programs/cleos/main.cpp
@@ -2021,7 +2021,7 @@ int main( int argc, char** argv ) {
          tx_force_unique = false;
       }
 
-      send_actions({create_transfer(con,sender, recipient, to_asset(amount), memo)});
+      send_actions({create_transfer(con,sender, recipient, to_asset(con,amount), memo)});
    });
 
    // Net subcommand

**Comment by jgiszczak** [comment]
cleos supports transfer of any token via `push action`, e.g.

`cleos push action <your_token_account> transfer '["from_user", "to_user", "25.0000 XYZ", "Memo text" ]' -p from_user`
