### ISSUE TITLE
How to send eos coins from inside of contract to other account ?

### ISSUE THREAD

**Issue by alzozov** [EOSIO/eos#4138]

**Comment by jgiszczak** [comment]
See https://github.com/EOSIO/eos/blob/master/contracts/eosiolib/currency.hpp for the implementation of `inline_transfer` and https://github.com/EOSIO/eos/blob/master/contracts/exchange/exchange.cpp in `deposit()` and `withdraw()` for samples of invoking it.

**Comment by alzozov** [comment]
thanks

**Comment by alzozov** [comment]
@jgiszczak 
and how to use eos.token transfare method and token or is it the same as currency.hpp ?

**Comment by jgiszczak** [comment]
I'm sure it's similar if not identical to the old currency.hpp.
