### ISSUE TITLE
Transactions not making it into blocks when faced with production gaps.

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#4145]
#4060 corrected a false-positive result from the get_transaction RPC which, in turn, allowed our smoke tests to _actually detect_ dropped transactions for the first time.   In addition, there is a non-deterministic set of conditions that can occur in our smoke tests which drops transactions on a local low-latency network.  This coincides with an unintentional gap in production in the smoke tests. 

logs from CI machine (located here for those with access: https://buildkite.com/EOSIO/eosio/builds/2167 ) indicated that between block 222 and 223 there was an unintentional 7.5 second gap that also corresponds with the loss of a transaction and failure of the test.

The transaction in question (ce112f38db6...) is received by `node_02`, validated and propagated to all nodes ~800ms after `node_02` produced block 222.   after the gap, `node_00` produces 223 with 0 transactions.  However, logs indicate that it had received, validated and applied the transaction in question 5.5s prior to producing that block.

This implies that `node_00` received the transaction successfully applied the transaction to its local speculative block.  Later it would abort this block, which should move the transaction in to the "unapplied transactions" inside the controller AND then start its production block.  The producer plugin should attempt to stuff any unapplied transactions into the new block but obviously something in this chain of custody has dropped the ball.

this issue is for
- [x] identifying the cause of the dropped transactions
- [ ] fix it
- [ ] if possible author unit tests to protect against regression

@cj-oci will address making the smoke tests deterministic in #4144

**Comment by wanderingbort** [comment]
this line seems to be the culprit:
https://github.com/EOSIO/eos/blob/a6c3e9c98655bddc6aaf9c73947b828f4e76b2bf/plugins/producer_plugin/producer_plugin.cpp#L841

it would essentially defeat any attempt to promote transactions received while speculating on a block into the production block.

This has a reduced impact that it would imply at first because the transaction would still propagate on the network and if it was received by any producer _while that producer was constructing a block_ it would not be dropped.  This made our weak points, producer hand-offs where a transaction could hit the producer A after it made its last block and producer B right before it got A's last block AND any time the network had a down producer.

**Comment by Crypto-Ferret** [comment]
Any chance you could explain this in a idiots guide kind of way please?
