### ISSUE TITLE
keosd-provider-timeout=5 default is quite aggressive

### ISSUE THREAD

**Issue by abourget** [EOSIO/eos#4151]
I've seen some missed blocks using the OOB signing process. Both for production blocks and "counter-signatures". Error looks like this upon production:

```
1853505ms thread-0   producer_plugin.cpp:1006      maybe_produce_block  ] 10 assert_exception: Assert Exception
!ec: Failed to read response: Connection timed out
    {"message":"Connection timed out"}
    thread-0  http_client.cpp:300 post_sync
```

And like this upon counter-signature:

```
2650583ms thread-0   controller.cpp:150            emit                 ] 10 assert_exception: Assert Exception
!ec: Failed to read response: Connection timed out
    {"message":"Connection timed out"}
    thread-0  http_client.cpp:300 post_sync
```

Some signatures take a lot more than 5ms.  This doesn't seem to interrupt the in-process signing mechanism, but it does truncate and drop the block if the OOB signing process takes too long.

Some blocks might loop through multiple sigs to find a "canonical" signature.. and I've seen the process take up to 15ms on my laptop (using https://github.com/eoscanada/eos-blocksigner ).

I'm going through `http_client.cpp` and am unsure how it considers connection keep-alives. If it were to drop the TCP connection between each signature, that'd add to latency. I'll try to check deeper if this is the case.

I don't have `debug` logging enabled in production, so can't easily tell the perceived time from `nodeos`.. I'll see what I can get.

If all of this adds to the latency, and is an important security measure, then https://github.com/EOSIO/eos/issues/3683 becomes all the more important.

**Comment by taokayan** [comment]
We haven't received any update for this. This timeout parameter is configurable. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
