### ISSUE TITLE
Error while compiling with eosiocpp###     fatal error: 'fstream' file not found

### ISSUE THREAD

**Issue by blockchain-expert** [EOSIO/eos#4152]
While compiling a contract using eosiocpp tool, following error found. I'm using latest docker images.
fatal error: 'fstream' file not found
#include<fstream>
        ^~~~~~~~~
1 error generated.

**Comment by jgiszczak** [comment]
`fstream` is not supported and will not ever be supported.  Reading and writing to files in a node filesystem is nondeterministic across nodes.
