### ISSUE TITLE
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations

### ISSUE THREAD

**Issue by quocle108** [EOSIO/eos#4154]
Hi all,
I just updated the last version, and got this issues when i tried to create an account as below.
Anyone have this issues?

```
$ cleos create account eosio eosio.token EOS7m4Q5HRiLPK8a1q3pX1DMLd8VehTdRfuabv9f3FoX6wG51bAjU
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
```

The wallet already imported a private key and  unlocked.
```
$ cleos wallet keys
[
  "EOS7m4Q5HRiLPK8a1q3pX1DMLd8VehTdRfuabv9f3FoX6wG51bAjU"
]

$ cleos wallet unlock --password PW5Jw5iTrqs8u1eMDY7EzU7ujkrmDQmxc6yKg1W67TtxaAn5cz21S
Unlocked: default
```

**Comment by spartucus** [comment]
The key of `eosio` is not imported into wallet.
I think the right key of eosio is `EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV`.

**Comment by sunphy** [comment]
Same error occurs. 
How could I import the public key of `eosio`? I think only private key could be imported by command `cleos wallet import ` @spartucus

**Comment by heifner** [comment]
**ONLY USE FOR TESTING**

eosio public key: `EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV`
eosio private key: `5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3`

**ONLY USE FOR TESTING**

**Comment by sunphy** [comment]
Yes,it works.Thanks a lot @heifner

**Comment by duvalCC** [comment]
<img width="1191" alt="eos" src="https://user-images.githubusercontent.com/21072525/41819870-d443b008-77fa-11e8-8250-e82660af35ca.png">

I have imported the public key of  eosio  .But it do not work for me . Who can help...

**Comment by duvalCC** [comment]
@HeDeHeng  我是连接了主网创建账号的，这个eosio只能用于测试网络？

**Comment by quocle108** [comment]
@nikodean1 
You just import eosio account to your wallet. This account already created

**Comment by gartox** [comment]
Works for me

**Comment by AlgernonMXF** [comment]
@duvalCC 我遇到了和你截图中同样的问题，想问一下你是怎么解决的呢

**Comment by JonieH** [comment]
same  error

**Comment by rosselpha** [comment]
still didn't work now I'm getting the previous err I was getting 

`cleos create account eosio koood EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV EOS6BX6eQH2JwKoMwh57wi1p76sr3CkqHNDBzjGCYWnMn4M3GH7fq
1401172ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)
` 
yes i im runing nodeos with `--http-validate-host=false`

**Comment by nikodean1** [comment]
Check if the account was created anyway. Something similar happened to me

**Comment by rosselpha** [comment]
it worked I just needed to restart nodeos

**Comment by bluabaleno** [comment]
I couldn't import the producer key AND I can't sign push eosio.bios contract despite having already set up the default wallet.

**Comment by bluabaleno** [comment]
I'm having trouble setting the bios contract on my producing test node. 
Apparently the default wallet is suppose to contain the producer key but I can't sign with it. Can't import it again either :(

**Comment by jgiszczak** [comment]
@bluabaleno The default wallet no longer contains any key when first created.  Even the default key must be imported manually.  The documentation has been updated to reflect this change.

**Comment by neo-thematrix** [comment]
nodeos is running for a day or more and receiving blocks from July....not sure if that is causing this.

Received same error message rusted@rusty:~/eos$ cleos create account eosio eosio.token EOS6N2sbMRCT7tcrpyi1m9DeNca9qrZPt1WUPgtVbMq7jSjTi8L44
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked. 

Wallet was unlocked and confirmed unlock.  Did restart nodeos once as well and rechecked wallet lock.
![screenshot from 2018-08-27 22-08-04](https://user-images.githubusercontent.com/7365837/44700547-e0c15780-aa46-11e8-8dbc-506ce98ef8a8.png)

**Comment by VtpVlan-oo7** [comment]
@heifner 

 i am using these both

eosio public key: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
eosio private key: 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3

and write on terminal as such-

cleos create account eosio intersteller EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV

but still didn't got any reply from terminal before 10 min please share the proper cli for creating new account just because of that i am stuck with that before 2wk

**Comment by VtpVlan-oo7** [comment]
@gartox 
i am using the  same as you suggest but its not in working-
firstly i imported private key by using command-

cleos wallet  import --private-key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 -n asdf imported private key for: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV

and after using that my terminal gone to be stuck , i didn't got any response--

 cleos create account eosio intersteller EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV

**Comment by jgiszczak** [comment]
@neo-thematrix You can not create accounts using the default key on a node being synchronized with mainnet.  The eosio account on mainnet was not created with the default key and it's disabled now in any case since mainnet went live with voted producers.  All of the instructions for creating accounts with the default key are for private test networks only.

**Comment by jgiszczak** [comment]
@VtpVlan-oo7 The command line you are using is correct.  Be sure your local `nodeos` instance is running, not stopped, is producing blocks, and is standalone.

**Comment by neo-thematrix** [comment]
@jgiszczak okay I think I am following you.  So I do have all the keys in a separate account name.  So I changed to `````
$ cleos push action eosio.token create '[ "pollen", "21000000.0000 POLLEN" ]' -p eosio.token
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
```
"pollen" as you can see was unlocked prior to the command.  I feel I am close, but obviously missing a few steps?
![screenshot from 2018-08-29 10-13-44](https://user-images.githubusercontent.com/7365837/44800669-39dad980-ab74-11e8-82e4-68276b9607c7.png)

**Comment by jgiszczak** [comment]
@neo-thematrix You also do not have authority to issue transactions on behalf of the eosio.token account, as you don't have its private key either.  If you wish to use the eosio.token contract, you may set it on your own account, and use it to create and issue your own token.  Note you will have to pay the RAM costs for storing the contract and its tables.

There may at some point be a way to use the system token contract for custom tokens, but I'm not aware of consensus emerging around any of the proposals.  Very likely it will be an entirely new contract, or even family of contracts, not named eosio.token at all.

**Comment by abhi3700** [comment]
@VtpVlan-oo7 
I am facing the same problem as well.

Steps followed:
- `nodeos` running on a separate terminal.
- wallet is unlocked
- list keys using `cleos wallet keys`. It gives output as:
```
[
  "EOS5auLgLhM3uYWaDEeESKUMfqYsnNcUj2G9xSDuLbmEj4PGfBupL",
  "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
  "EOS6aD1hj7hcqktskyMtFKLti62MSaQV4vgb1GMES5cvLmj8s8Jip"
]
```
- create account for uploading a contract using 
   `cleos create account eosio dev111111111 EOS5auLgLhM3uYWaDEeESKUMfqYsnNcUj2G9xSDuLbmEj4PGfBupL EOS6aD1hj7hcqktskyMtFKLti62MSaQV4vgb1GMES5cvLmj8s8Jip`

**Issue**: It is returning nothing. I did wait for long.

Anyone with the solution, please?

Happy coding :)
@abhi3700

**Comment by VtpVlan-oo7** [comment]
@abhi3700 

 **for account creation Block genration must be needed

use the below command and the owner key which you have to use should be of nodeos's config.ini signature-provider key like that-

signature-provider = EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3


$ cleos create account eosio intersteller EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV 

executed transaction: bb0df6ba191b895ed50b4060a59d0474535707a70e5d89a18a1ab63f4919a784  200 bytes  297 us
#         eosio <= eosio::newaccount            {"creator":"eosio","name":"intersteller","owner":{"threshold":1,"keys":[{"key":"EOS6MRyAjQq8ud7hVNYc...
warning: transaction executed locally, but may not be confirmed by the network yet    ]

**Comment by damianjnc** [comment]
I got that error while creating an account, anyone knows whats wrong?:
```
~$ cleos create account creator damian2 name damian11 OwnerKey EOS6BvXtPVJeH9HVvv2LfFM7X4fNFZYEhgQgWSrD1JfWcUHSeq5aq
ERROR: ExtrasError: [OwnerKey EOS6BvXtPVJeH9HVvv2LfFM7X4fNFZYEhgQgWSrD1JfWcUHSeq5aq]
Create an account, buy ram, stake for bandwidth for the account
Usage: cleos create account [OPTIONS] creator name OwnerKey [ActiveKey]

Positionals:
  creator TEXT                The name of the account creating the new account (required)
  name TEXT                   The name of the new account (required)
  OwnerKey TEXT               The owner public key for the new account (required)
  ActiveKey TEXT              The active public key for the new account

Options:
  -h,--help                   Print this help message and exit
  -x,--expiration             set the time in seconds before a transaction expires, defaults to 30s
  -f,--force-unique           force the transaction to be unique. this will consume extra bandwidth and remove any protections against accidently issuing the same transaction multiple times
  -s,--skip-sign              Specify if unlocked wallet keys should be used to sign transaction
  -j,--json                   print result as json
  -d,--dont-broadcast         don't broadcast transaction to the network (just print to stdout)
  --return-packed             used in conjunction with --dont-broadcast to get the packed transaction
  -r,--ref-block TEXT         set the reference block num or block id used for TAPOS (Transaction as Proof-of-Stake)
  -p,--permission TEXT ...    An account and permission level to authorize, as in 'account@permission'
  --max-cpu-usage-ms UINT     set an upper limit on the milliseconds of cpu usage budget, for the execution of the transaction (defaults to 0 which means no limit)
  --max-net-usage UINT        set an upper limit on the net usage budget, in bytes, for the transaction (defaults to 0 which means no limit)

```

**Comment by navneetboghani** [comment]
same issue i got

**Comment by DjangoPeng** [comment]
@navneetboghani Have u solved the issue? 
If so, please share the solution.

**Comment by kissm** [comment]
The wallet imports the system account private key and loads the BIOS contract。
1、 cleos wallet import -n name --private-key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 
2、cleos set contract eosio build/contracts/eosio.bios -p eosio

**Comment by Mojicode** [comment]
I know how to solve this issue, you must import eosio's pub&pri key to your wallet first :
1.input "cleos wallet import -n yourwalletname"
2.input eosio's private key.
then you can use cleos create account eosio yourAccount pubkey1 pubkey2.
