### ISSUE TITLE
Main Page of Doxygen Needs to be more robust introduction

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#416]
![image](https://user-images.githubusercontent.com/347290/30382415-07048a08-986d-11e7-997c-4bf4d790955e.png)

Content defined here:

contracts/eoslib/mainpage.md

**Comment by dskvr** [comment]
Wrote the outline and pushed to `docs-416` moving to another issue before I call it a night.

**Comment by dskvr** [comment]
Crowdsale related documentation cannot exist unless it is behind a purchase agreement.

**Comment by dskvr** [comment]
Collecting the last bits and pieces on this, opened pull request for review.
