### ISSUE TITLE
can not create account use cleos command

### ISSUE THREAD

**Issue by tvrc4m** [EOSIO/eos#4163]
i have create local wallet address and import two private key.
and run this command 
cleos  -u http://mainnet.genereos.io create account eosio eosio.token EOS74bPXbwdz7Any4me8Zwwrs5SVxeSmLYmW35n9e4jKWiFgBHrqk EOS8LPedxtcz5KzDT8oUZMgyptQh9v3jXxQzqsGCfcZdbSdPgyzAJ
it returns
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.

but the wallent is unlock status and has two keys inside.

so have a  solution ?

**Comment by spartucus** [comment]
No, that's not the right way. `cleos create account CREATOR NEW_ACCOUNT OWNER_KEY AVTICE_KEY -p CREATOR` is TESTING only.
The right way to create account on main net is `cleos -u http://mainnet.genereos.io CREATOR NEW_ACCOUNT OWNER_KEY ACTIVE_KEY --staked-net "0.0001 EOS" --stake-cpu "0.0001 EOS" --buy-ram "0.0439 EOS" -p CREATOR`

**Comment by tvrc4m** [comment]
and then return the error.
cleos --wallet-url http://localhost:8900/ -u http://mainnet.genereos.io/ creator eostonystark EOS74bPXbwdz7Any4me8Zwwrs5SVxeSmLYmW35n9e4jKWiFgBHrqk EOS8LPedxtcz5KzDT8oUZMgyptQh9v3jXxQzqsGCfcZdbSdPgyzAJ --staked-net "0 EOS" --stake-cpu "0 EOS" --buy-ram "0 EOS" -p creator
the error message
Host and port options (-H, --wallet-host, etc.) have been replaced with -u/--url and --wallet-url
Use for example -u http://localhost:8888 or --url https://example.invalid/

**Comment by heifner** [comment]
Try with `cleos -v` ... to see better error message. You are not allowed to specify `0 EOS`.

**Comment by tvrc4m** [comment]
the wallet and public key save on the local host.
now can not query on the main net.
how to transfer eos to this wallet ?

**Comment by dmorris99** [comment]
Also unable to create a/c on mainnet. Proper examples and docs are very needed.

**Comment by jgiszczak** [comment]
There is no account named `creator` on the mainnet, and even if there was, you would need its private key to be able to execute that command.  Accounts can only be created from existing accounts.  There is no mechanism whatsoever to simply inject a new account into the system after it's up and running.  If you did not register ICO tokens before mainnet launch, you do not have and can not create an account.

Presumably an account creation service with arise, but I'm not aware of any at present.

**Comment by wooparadog** [comment]
> Presumably an account creation service with arise, but I'm not aware of any at present.

https://medium.com/coinmonks/create-your-own-eos-account-easily-using-the-non-service-fee-dapp-signupeoseos-b15c5347f2fc

There is one such service now, worth a try.
