### ISSUE TITLE
1.0.5 do not feed back assertion details, can not solve problems!

### ISSUE THREAD

**Issue by gpmn** [EOSIO/eos#4167]
e.g. what wrong with it???
---------------------
RESPONSE:
---------------------
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3050003,
    "name": "eosio_assert_message_exception",
    "what": "eosio_assert_message assertion failure",
    "details": []
  }
}
---------------------
Error 3050003: eosio_assert_message assertion failure

**Comment by noprom** [comment]
Can you show more details about this issue so that we can reproduce.

**Comment by gpmn** [comment]
I suppose I have a problem in my contract which owned by fifagambling, but no detail feedback, I have no idea what's wrong.

----------------------------------------------------------------------------------

`root@59ad54cc9e4a:/# cleos transfer testgambling guytiobzguge "0.01 EOS" "memo"
cleos transfer testgambling guytiobzguge "0.01 EOS" "memo"
executed transaction: 3822b29bef7ce6e4aaf26d163142a66b099b8b3ce1319f8dce54f12ed4d743d0  136 bytes  1148 us
#   eosio.token <= eosio.token::transfer        {"from":"testgambling","to":"guytiobzguge","quantity":"0.0100 EOS","memo":"memo"}
#  testgambling <= eosio.token::transfer        {"from":"testgambling","to":"guytiobzguge","quantity":"0.0100 EOS","memo":"memo"}
#  guytiobzguge <= eosio.token::transfer        {"from":"testgambling","to":"guytiobzguge","quantity":"0.0100 EOS","memo":"memo"}
warning: transaction executed locally, but may not be confirmed by the network yet
root@59ad54cc9e4a:/# cleos --print-response transfer testgambling guytiobzguge "0.01 EOS" "memo"
cleos --print-response transfer testgambling guytiobzguge "0.01 EOS" "memo"
RESPONSE:
---------------------
{
  "EOS": {
    "supply": "1000334947.8475 EOS",
    "max_supply": "10000000000.0000 EOS",
    "issuer": "eosio"
  }
}
---------------------
RESPONSE:
---------------------
{
  "binargs": "c0a68b471a96b1caa09866ff5097bd66640000000000000004454f5300000000046d656d6f"
}
---------------------
RESPONSE:
---------------------
{
  "server_version": "db031363",
  "chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
  "head_block_num": 1121388,
  "last_irreversible_block_num": 1121057,
  "last_irreversible_block_id": "00111b218b181c41660ae8eabc498372e569056627309d1220373fc01ffb4e95",
  "head_block_id": "00111c6ccee7453565e3534ccde803de616ace3b29a301b7843362244958d505",
  "head_block_time": "2018-06-17T03:34:57.000",
  "head_block_producer": "bitfinexeos1",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576
}
---------------------
RESPONSE:
---------------------
[
  "EOS5Tpvfbrimu7KFKzWowAzzEHxg696M89DjCf54v8StdnQtBxFkV",
  "EOS63VmZSUzjwu83B9CD5eJF1Le6GdViCPj9ro3UZLG4jLCZvi9Dp",
  "EOS6yGaoPaniXqiTK3cG9tigenCVWD9WXGqk9XGxnfoPjWCnEDoua",
  "EOS7CVFrSUz9A23M8SSx99hVrnJf66H8mbpBUN3XTn88wpJs9Ji7f",
  "EOS7iAKvifRc5AfaetwZUUPWJyNVvuqT7ehFG4e5m5PSNndGwMz5g"
]
---------------------
RESPONSE:
---------------------
{
  "required_keys": [
    "EOS7CVFrSUz9A23M8SSx99hVrnJf66H8mbpBUN3XTn88wpJs9Ji7f"
  ]
}
---------------------
RESPONSE:
---------------------
{
  "expiration": "2018-06-17T03:35:27",
  "ref_block_num": 6945,
  "ref_block_prefix": 3941075558,
  "max_net_usage_words": 0,
  "max_cpu_usage_ms": 0,
  "delay_sec": 0,
  "context_free_actions": [],
  "actions": [{
      "account": "eosio.token",
      "name": "transfer",
      "authorization": [{
          "actor": "testgambling",
          "permission": "active"
        }
      ],
      "data": "c0a68b471a96b1caa09866ff5097bd66640000000000000004454f5300000000046d656d6f"
    }
  ],
  "transaction_extensions": [],
  "signatures": [
    "SIG_K1_KZWg8pE3WbSvnvGurxxLe3DQjpRjgqV6CjUkj9SBNyCrqG4mZ2XJMqwWK2S6RpxtG5UDJjittMW91kHU5WNL7qf9QUxvj4"
  ],
  "context_free_data": []
}
---------------------
RESPONSE:
---------------------
{
  "transaction_id": "a158ffa556b91edddc72586e8c588ad25d30e7366d2bee7af285adccc313600b",
  "processed": {
    "id": "a158ffa556b91edddc72586e8c588ad25d30e7366d2bee7af285adccc313600b",
    "receipt": {
      "status": "executed",
      "cpu_usage_us": 1003,
      "net_usage_words": 17
    },
    "elapsed": 1003,
    "net_usage": 136,
    "scheduled": false,
    "action_traces": [{
        "receipt": {
          "receiver": "eosio.token",
          "act_digest": "455716fc67aed4be91591ab86fc72831fa5699233c4a489d943b2c5d38fedecd",
          "global_sequence": 3998025,
          "recv_sequence": 717927,
          "auth_sequence": [[
              "testgambling",
              18
            ]
          ],
          "code_sequence": 1,
          "abi_sequence": 1
        },
        "act": {
          "account": "eosio.token",
          "name": "transfer",
          "authorization": [{
              "actor": "testgambling",
              "permission": "active"
            }
          ],
          "data": {
            "from": "testgambling",
            "to": "guytiobzguge",
            "quantity": "0.0100 EOS",
            "memo": "memo"
          },
          "hex_data": "c0a68b471a96b1caa09866ff5097bd66640000000000000004454f5300000000046d656d6f"
        },
        "elapsed": 632,
        "cpu_usage": 0,
        "console": "",
        "total_cpu_usage": 0,
        "trx_id": "a158ffa556b91edddc72586e8c588ad25d30e7366d2bee7af285adccc313600b",
        "inline_traces": [{
            "receipt": {
              "receiver": "testgambling",
              "act_digest": "455716fc67aed4be91591ab86fc72831fa5699233c4a489d943b2c5d38fedecd",
              "global_sequence": 3998026,
              "recv_sequence": 8,
              "auth_sequence": [[
                  "testgambling",
                  19
                ]
              ],
              "code_sequence": 1,
              "abi_sequence": 1
            },
            "act": {
              "account": "eosio.token",
              "name": "transfer",
              "authorization": [{
                  "actor": "testgambling",
                  "permission": "active"
                }
              ],
              "data": {
                "from": "testgambling",
                "to": "guytiobzguge",
                "quantity": "0.0100 EOS",
                "memo": "memo"
              },
              "hex_data": "c0a68b471a96b1caa09866ff5097bd66640000000000000004454f5300000000046d656d6f"
            },
            "elapsed": 7,
            "cpu_usage": 0,
            "console": "",
            "total_cpu_usage": 0,
            "trx_id": "a158ffa556b91edddc72586e8c588ad25d30e7366d2bee7af285adccc313600b",
            "inline_traces": []
          },{
            "receipt": {
              "receiver": "guytiobzguge",
              "act_digest": "455716fc67aed4be91591ab86fc72831fa5699233c4a489d943b2c5d38fedecd",
              "global_sequence": 3998027,
              "recv_sequence": 31,
              "auth_sequence": [[
                  "testgambling",
                  20
                ]
              ],
              "code_sequence": 1,
              "abi_sequence": 1
            },
            "act": {
              "account": "eosio.token",
              "name": "transfer",
              "authorization": [{
                  "actor": "testgambling",
                  "permission": "active"
                }
              ],
              "data": {
                "from": "testgambling",
                "to": "guytiobzguge",
                "quantity": "0.0100 EOS",
                "memo": "memo"
              },
              "hex_data": "c0a68b471a96b1caa09866ff5097bd66640000000000000004454f5300000000046d656d6f"
            },
            "elapsed": 11,
            "cpu_usage": 0,
            "console": "",
            "total_cpu_usage": 0,
            "trx_id": "a158ffa556b91edddc72586e8c588ad25d30e7366d2bee7af285adccc313600b",
            "inline_traces": []
          }
        ]
      }
    ],
    "except": null
  }
}
---------------------
executed transaction: a158ffa556b91edddc72586e8c588ad25d30e7366d2bee7af285adccc313600b  136 bytes  1003 us
#   eosio.token <= eosio.token::transfer        {"from":"testgambling","to":"guytiobzguge","quantity":"0.0100 EOS","memo":"memo"}
#  testgambling <= eosio.token::transfer        {"from":"testgambling","to":"guytiobzguge","quantity":"0.0100 EOS","memo":"memo"}
#  guytiobzguge <= eosio.token::transfer        {"from":"testgambling","to":"guytiobzguge","quantity":"0.0100 EOS","memo":"memo"}
warning: transaction executed locally, but may not be confirmed by the network yet
root@59ad54cc9e4a:/# cleos --print-response transfer testgambling fifagambling "0.01 EOS" "memo"
cleos --print-response transfer testgambling fifagambling "0.01 EOS" "memo"
RESPONSE:
---------------------
{
  "EOS": {
    "supply": "1000334947.8475 EOS",
    "max_supply": "10000000000.0000 EOS",
    "issuer": "eosio"
  }
}
---------------------
RESPONSE:
---------------------
{
  "binargs": "c0a68b471a96b1cac0a68b471a66965b640000000000000004454f5300000000046d656d6f"
}
---------------------
RESPONSE:
---------------------
{
  "server_version": "db031363",
  "chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
  "head_block_num": 1121415,
  "last_irreversible_block_num": 1121081,
  "last_irreversible_block_id": "00111b3925060a6a03a7620e0c27d21c501a0b9eec51f402608dcbd421c68f97",
  "head_block_id": "00111c8777af0a5eda0d9ee8ee7d017b68240bff8ffabdccce1643a6e07e76ae",
  "head_block_time": "2018-06-17T03:35:10.500",
  "head_block_producer": "eos42freedom",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576
}
---------------------
RESPONSE:
---------------------
[
  "EOS5Tpvfbrimu7KFKzWowAzzEHxg696M89DjCf54v8StdnQtBxFkV",
  "EOS63VmZSUzjwu83B9CD5eJF1Le6GdViCPj9ro3UZLG4jLCZvi9Dp",
  "EOS6yGaoPaniXqiTK3cG9tigenCVWD9WXGqk9XGxnfoPjWCnEDoua",
  "EOS7CVFrSUz9A23M8SSx99hVrnJf66H8mbpBUN3XTn88wpJs9Ji7f",
  "EOS7iAKvifRc5AfaetwZUUPWJyNVvuqT7ehFG4e5m5PSNndGwMz5g"
]
---------------------
RESPONSE:
---------------------
{
  "required_keys": [
    "EOS7CVFrSUz9A23M8SSx99hVrnJf66H8mbpBUN3XTn88wpJs9Ji7f"
  ]
}
---------------------
RESPONSE:
---------------------
{
  "expiration": "2018-06-17T03:35:40",
  "ref_block_num": 6969,
  "ref_block_prefix": 241346307,
  "max_net_usage_words": 0,
  "max_cpu_usage_ms": 0,
  "delay_sec": 0,
  "context_free_actions": [],
  "actions": [{
      "account": "eosio.token",
      "name": "transfer",
      "authorization": [{
          "actor": "testgambling",
          "permission": "active"
        }
      ],
      "data": "c0a68b471a96b1cac0a68b471a66965b640000000000000004454f5300000000046d656d6f"
    }
  ],
  "transaction_extensions": [],
  "signatures": [
    "SIG_K1_Jx9ok6f28SJGate1bK63j1TV8AnNWAgaHKJCxVy9mtyxcgpcYnRzo5BzvVALVijT2YZoYnknnwung4At6iv7Ck8mLyje3w"
  ],
  "context_free_data": []
}
---------------------
RESPONSE:
---------------------
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 3050003,
    "name": "eosio_assert_message_exception",
    "what": "eosio_assert_message assertion failure",
    "details": []
  }
}
---------------------
Error 3050003: eosio_assert_message assertion failure
root@59ad54cc9e4a:/# 

root@59ad54cc9e4a:/# 

root@59ad54cc9e4a:/# 

root@59ad54cc9e4a:/# 

root@59ad54cc9e4a:/# cleos transfer testgambling fifagambling "0.01 EOS" "memo"
cleos transfer testgambling fifagambling "0.01 EOS" "memo"
Error 3050003: eosio_assert_message assertion failure
root@59ad54cc9e4a:/# alias 
alias 
alias cleos='/usr/local/bin/cleos  --wallet-url http://127.0.0.1:8900  -u http://mainnet.eoscalgary.io'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
root@59ad54cc9e4a:/# `

**Comment by nsjames** [comment]
We are seeing this as we across the board with different system methods.

So far i've seen this with `buyrambytes`, `newaccount`, and `bidname`. 
It seems to happen when an assertion is hit ( such as not enough EOS to buy ram ) but swallows the assertion and outputs the `FC_DECLARE_DERIVED_EXCEPTION`

https://github.com/EOSIO/eos/blob/master/libraries/chain/include/eosio/chain/exceptions.hpp#L172

**Comment by wsdfz** [comment]
Yes, after mainnet upgrade to v1.0.5, I cannot see the message of eosio_assert any more.

It only shows: 
Error 3050003: eosio_assert_message assertion failure

**Comment by wangyilin1987** [comment]
Yes, after mainnet upgrade to v1.0.5, I cannot see the message of eosio_assert any more.

It only shows:
Error 3050003: eosio_assert_message assertion failure

me too. how to deal this issue?

**Comment by jgiszczak** [comment]
Use `--verbose-http-errors` to get more detail about the problem.  A change in 1.0.4 was too aggressive in eliminating error information.  The change will be revisited in a future release.

**Comment by andriantolie** [comment]
This issue should be solved with the above mentioned `--verbose-http-errors`. I'm closing this issue.

**Comment by calfzhou** [comment]
`--verbose-http-errors` doesn't work now, will cause an error:
```
ERROR: ExtrasError: [--verbose-http-errors]
```

using `--verbose` but still no detail message returned.

**Comment by jgiszczak** [comment]
@calfzhou Your build is substantially out of date if that argument is unrecognized.  Update to v1.3.1 and try again.

**Comment by calfzhou** [comment]
thanks @jgiszczak . Now it works!
