### ISSUE TITLE
Why did main network synchronization fail in a while？？version 1.0.5

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#4168]
52337ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/sign_digest
52337ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/sign_transaction
52337ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/unlock
52337ms thread-0   history_api_plugin.cpp:38     plugin_startup       ] starting history_api_plugin
52337ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_actions
52337ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_controlled_accounts
52337ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_key_accounts
52337ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_transaction
52337ms thread-0   producer_plugin.cpp:577       plugin_startup       ] producer plugin:  plugin_startup() begin
52338ms thread-0   producer_plugin.cpp:604       plugin_startup       ] producer plugin:  plugin_startup() end
106896ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block ddc03486114e6a1c... #1000 @ 2018-06-09T12:06:33.000 signed by eosio [trxs: 1, lib: 999, conf: 0, latency: 651313896 ms]
158204ms thread-0   net_plugin.cpp:1055           operator()           ] Error sending to peer bp.eosbeijing.one:8080: Operation canceled
158204ms thread-0   net_plugin.cpp:2187           operator()           ] Error reading message from bp.eosbeijing.one:8080: Bad file descriptor
172413ms thread-0   net_plugin.cpp:1969           connect              ] host: bp.eosbeijing.one port: 8080
182464ms thread-0   net_plugin.cpp:2011           operator()           ] connection failed to node1.liquideos.com:9876: Connection timed out
182526ms thread-0   net_plugin.cpp:1055           operator()           ] Error sending to peer node1.liquideos.com:9876: Broken pipe
198690ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 206e680a75958c81... #2000 @ 2018-06-09T12:14:53.000 signed by eosio [trxs: 1, lib: 1999, conf: 0, latency: 650905690 ms]
202512ms thread-0   net_plugin.cpp:1969           connect              ] host: node1.liquideos.com port: 9876
280127ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 3755ae4c7e9c5751... #3000 @ 2018-06-09T12:23:13.500 signed by eosio [trxs: 1, lib: 2999, conf: 0, latency: 650486627 ms]
331983ms thread-0   net_plugin.cpp:2011           operator()           ] connection failed to node1.liquideos.com:9876: Connection timed out
352812ms thread-0   net_plugin.cpp:1969           connect              ] host: node1.liquideos.com port: 9876
362943ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block b7540f01a5ff33f0... #4000 @ 2018-06-09T12:31:34.500 signed by eosio [trxs: 0, lib: 3999, conf: 0, latency: 650068443 ms]
terminate called after throwing an instance of 'boost::interprocess::bad_alloc'
  what():  boost::interprocess::bad_alloc

thanks

**Comment by w00tcoin** [comment]
I’m having the very same issues

**Comment by fundurian** [comment]
Help I am also having this issue, it fail at the block #4000

**Comment by tbfleming** [comment]
> so i added the line --filter-on = * on my config file

Don't do that. * is for automated tests only. It can't handle the main net.

**Comment by tbfleming** [comment]
If you need to track all transactions, then you need one of the database plugins which are under development. The history plugin can't handle that load on the mainnet.

**Comment by Nadejde** [comment]
How do the big block producers do it then? The apis they expose seem to have full action history for all accounts?

**Comment by shishi614** [comment]
`If you need to track all transactions, then you need one of the database plugins which are under development. The history plugin can't handle that load on the mainnet.`
how to config ???thanks

**Comment by Nadejde** [comment]
@shishi614 this is what i did:

Went into ~/.local/share/eosio/nodeos/config/config.ini and changed chain-state-db-size-mb = 40240.

I gave it 40gb of memory because I can but it seems that it's total overkill:) I've been monitoring the process and it does not go over 4g. 

I've been resyncing my node. Up to block 800000 and no issues so far.

**Comment by kein-S** [comment]
same issue
