### ISSUE TITLE
kleosd error

### ISSUE THREAD

**Issue by raymondfx** [EOSIO/eos#4170]
When I `Pkill Keosd `and change the http-server-address property to:
`http-server-address = 127.0.0.1:8899`

I get this error when I try to unlock wallet with is command `cleos --wallet-url=http://localhost:8899 wallet unlock`

 error

```
cleos --wallet-url=http://localhost:8899 wallet unlock
password: Error 3120002: Nonexistent wallet
Are you sure you typed the wallet name correctly?
```
keosd logs
```
3294706ms thread-0   http_plugin.cpp:405           handle_exception     ] FC Exception encountered while processing wallet.unlock
3294706ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 3120002 wallet_nonexistent_exception: Nonexistent wallet
Unable to open file: /Users/..../eosio-wallet/./default.wallet
    {"f":"/Users/.../eosio-wallet/./default.wallet"}
    thread-0  wallet_manager.cpp:86 open
```
```

**Comment by andriantolie** [comment]
Do you have this file `/Users/..../eosio-wallet/./default.wallet`? If not, you will need to create the wallet first

**Comment by programerone** [comment]
1. Make sure wallet is unlocked.

$ cleos wallet list

Wallets:
[
 "walletNameHere *"
]

The "*" means the wallet is unlocked

2. Make sure to create key and attach it to a wallet. Like so.

$ cleos create key
Private key: 5Jmsawgsp1tQ3GD6JyGCwy1dcvqKZgX6ugMVMdjirx85iv5VyPR
Public key: EOS7ijWCBmoXBi3CgtK7DJxentZZeTkeUnaSDvyro9dq7Sd1C3dC4

Then we import this key into your wallet:

$ cleos wallet import -n walletNameHere 5Jmsawgsp1tQ3GD6JyGCwy1dcvqKZgX6ugMVMdjirx85iv5VyPR
imported private key for: EOS7ijWCBmoXBi3CgtK7DJxentZZeTkeUnaSDvyro9dq7Sd1C3dC4

Hope that works.

**Comment by raymondfx** [comment]
Thanks managed to fix this problem.

**Comment by ProxToken** [comment]
./cleos --wallet-url=http://localhost:8899 wallet unlock -n yourwalletname
hope this help
