### ISSUE TITLE
Expired transaction on contract deployment

### ISSUE THREAD

**Issue by trungtt1981** [EOSIO/eos#4172]
I try to deploy contract to a remote testnet via a local nodeos.
It's quite ok to deploy the contract for the first time.
However, after that, it's no longer possible to deploy any other contract.
The error is as below:

```
Reading WAST/WASM from ./debug/debug.wasm...
Using already assembled WASM...
Publishing contract...
Error 3040005: Expired Transaction
Please increase the expiration time of your transaction!
Error Details:
expired transaction 9af2bdd6e18ccfc636d7970f741b292c917e9c3ede37ffaa4230721d5b8f2f95
```

My build revision of nodeos:
`master branch at commit a97a49a0dd4f5051dc7de1de4bc654fedf49cadf`

**Comment by trungtt1981** [comment]
I've found out a work-around.
Simply set the `max-transaction-time` to a higher value than default (e.g. 30000 ms) in `config.ini``

**Comment by andriantolie** [comment]
See the help for uploading contracts ("cleos set contract -h") and use the expiration parameter to change the expiration time.
