### ISSUE TITLE
token create

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#4174]
Error 3050000: action exception. The same operatin is okay for 1.0.2.  the abi file not changes, but why   
throw this exception?

**Comment by dvalencia-sd** [comment]
Any follow up on this? I'm having the same issue. 

In my case I just created new smart contract with different name but same code for eosio.token

**Comment by yankunsam** [comment]
By cleos, it is hard code for "eosio.token" account. So you should by HTTP API to communicate with your token.

**Comment by dixia** [comment]
closed as no follow up. let us know if this persists
