### ISSUE TITLE
keosd running on wrong port?

### ISSUE THREAD

**Issue by scolobey** [EOSIO/eos#4176]
Running through the 'getting started' stuff located here:
https://github.com/EOSIO/eos/wiki/Tutorial-Getting-Started-With-Contracts

When running:
`cleos wallet create`
I got this error:
'Failed to connect to keosd at http://localhost:8900/; is keosd running?'

I found that the config.ini located in my ~/eosio-wallet directory showed this.
http-server-address = 127.0.0.1:8888

Seems that the out-of-the-box setup is configured to run keosd at localhost:8888 while cleos is configured to look for it at localhost:8900.

Changing 'http-server-address' variable to 127.0.0.1:8900 seems to solve the problem. 

Curently, line #240 in this file:
eos/plugins/http_plugin/http_plugin.cpp
sets the default http-server-address to 127.0.0.1:8888
Can this be safely changed to 127.0.0.1:8900 ?

Alternatively, maybe I just need to run keosd manually before creating a wallet? But I thought starting nodeos was supposed to launch keosd.

**Comment by jgiszczak** [comment]
Manually running keosd is the current recommendation.  Running cleos starts keosd, not nodeos, unless keosd is running on the port cleos expects, in which case it does not launch another one.

**Comment by taokayan** [comment]
Is this solved?

**Comment by welbon** [comment]
It's not work. I was modified localhost:8900 in config.ini, but still got same error.
I was followed from this guidance - https://github.com/EOSIO/eos/wiki/Local-Environment#3-docker
It is work well when I running "docker-compose up", but following "cleos wallet list" got error.

**Comment by halsaphi** [comment]
This is a configuration option, please refer to latest documentation at developer.eos.io.
