### ISSUE TITLE
transactions would be run three times?

### ISSUE THREAD

**Issue by vaneyli** [EOSIO/eos#4179]
Two node A and B.
1: A get Transaction c   run the action and update the mutil-index database
2: B get Transaction c from A. and run the action and update the mutil-index database.
3: A create Block d which include the Transaction c. 
4: B get Block d, and run the Transaction c  again, and update the mutil-index database.

A run action one time  and B run action two times.  how to keep the same result of the database?

**Comment by jgiszczak** [comment]
Transactions run at least once on every single producer, so on a full network, a transaction will typically execute at least 22 times, and it could be as many as 60+ times.  This is entirely normal, and the system rolls back automatically before reexecuting.
