### ISSUE TITLE
Block stuck at 1027597 even after multiple restart

### ISSUE THREAD

**Issue by fundurian** [EOSIO/eos#4183]
Help, why when i do "cleos get info" my block stuck at 1027597
{
 "server_version": "843ed645",
  "chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
  "head_block_num": 1027926,
  "last_irreversible_block_num": 1027597,
  "last_irreversible_block_id": "000fae0db900b8a66d37f106a834b6405c3314df0f887f50bd52c457c2dd63ff",
  "head_block_id": "000faf56bcd290aa3f7300cb130fcf7243b4f1fd475bc3fd6708e609bc6b3f05",
  "head_block_time": "2018-06-16T09:56:38",
  "head_block_producer": "cypherglasss",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576
}

even when i restart the node, it download from block 0 it stop at 1027597

**Comment by SoYouDie** [comment]
Have the same issue but stucked on 1027597

**Comment by fundurian** [comment]
I solved it by reinstalling everything from version 1.0.5

https://github.com/EOS-Mainnet/eos/tree/mainnet-1.0.5
