### ISSUE TITLE
Cant use boost string inside contract

### ISSUE THREAD

**Issue by leordev** [EOSIO/eos#4184]
When I import boost string with:

`#include <boost/algorithm/string.hpp>`

and try to use the trim method:

`boost::algorithm::trim(pet_name);`

The code compiles fine but if I try to deploy this contract I receive this error:

```
cleos set contract monstereosio ../pet
Reading WAST/WASM from ../pet/pet.wasm...
Using already assembled WASM...
Publishing contract...
1469232ms thread-0   main.cpp:2659                 main                 ] Failed with error: Assert Exception (10)
!"unresolvable": env.calloc
```

Should I assume boost string functions is not supported in contracts?

**Comment by jgiszczak** [comment]
For the time being boost string functions are not supported, nor are any other libraries that make use of calloc.  This may change eventually, but at present there are no plans to implement calloc.
