### ISSUE TITLE
Cannot find "boost/container/flat_set.hp"

### ISSUE THREAD

**Issue by yimapo** [EOSIO/eos#4185]
After updating to the tip of the master branch, the compiler couldn't find file 'boost/container/flat_set.hpp' when compiling the "simple.token" contract. The error didn't happen in the old version.
---------------- Error message ----------------------
eosiocpp -g simple.token.abi simple.token.cpp
In file included from /home/sanwa/cxp/eos/contracts/simple.token/simple.token.cpp:1:
In file included from /usr/local/include/eosiolib/eosio.hpp:7:
In file included from /usr/local/include/eosiolib/action.hpp:7:
/usr/local/include/eosiolib/datastream.hpp:9:10: fatal error: 'boost/container/flat_set.hpp' file not found
#include <boost/container/flat_set.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by yimapo** [comment]
Never mind. I forgot to run "sudo make install". The issue is fixed after running the command.

**Comment by amih** [comment]
I experience the same problem. In what folder did you run "sudo make install"?
In the git cloned folder for eos I just ran ./eosio_build.sh

Oh, never mind, I found I need to run:

    sudo ./eosio_install.sh
