### ISSUE TITLE
Table interface is empty in the abi file for contract "simple.token"

### ISSUE THREAD

**Issue by yimapo** [EOSIO/eos#4186]
I generated abi file for contract "simple.token" using command "eosiocpp -g simple.token.abi simple.token.cpp". But the interface for tables is empty (e.g., "tables": [],)in the abi file as follows. This issue is not limited to contract "simple.token". I can't generate table interfaces in the abi file for any contracts.
------------- simple.token.abi file -----------------------
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-06-18T11:44:26",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "transfer",
      "base": "",
      "fields": [{
          "name": "from",
          "type": "name"
        },{
          "name": "to",
          "type": "name"
        },{
          "name": "quantity",
          "type": "uint64"
        }
      ]
    },{
      "name": "issue",
      "base": "",
      "fields": [{
          "name": "to",
          "type": "name"
        },{
          "name": "quantity",
          "type": "uint64"
        }
      ]
    }
  ],
  "actions": [{
      "name": "transfer",
      "type": "transfer",
      "ricardian_contract": ""
    },{
      "name": "issue",
      "type": "issue",
      "ricardian_contract": ""
    }
  ],
  "tables": [],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": []
}
~

**Comment by elmato** [comment]
which version of eosiocpp are you using?

**Comment by yimapo** [comment]
I just updated to the latest version of master branch as of 6/17/2018.

**Comment by yimapo** [comment]
I found some of the abi files are checked into the repository. If these files are derived from the source code, why should they be checked into the repository?

**Comment by elmato** [comment]
Add this comment above the type. A new version of the abi_generator is coming that will parse tables without the need for the comment. 
```c++
      //@abi table accounts
      struct account {
         account_name owner;
         uint64_t     balance;

         uint64_t primary_key()const { return owner; }
      };
```
