### ISSUE TITLE
How to unstake the tokens?

### ISSUE THREAD

**Issue by filipniziol** [EOSIO/eos#4188]
I have an account and I see that 5 tokens are staked:
http://eosflare.io/account/ha4tkmjxgyge
Why are they staked and how to unstake them?

**Comment by Velua** [comment]
This question is related to the EOS main net and not the EOSIO software, please engage the EOSIO Stack Exchange.

**Comment by jgiszczak** [comment]
All tokens were staked at launch while producer voting was underway.  To unstake, use:
`./cleos system undelegatebw [from] [receiver] [unstake_net_quantity] [unstake_cpu_quantity]`.  All arguments are required.
