### ISSUE TITLE
EOSIO compile under Arch

### ISSUE THREAD

**Issue by Jzarecta** [EOSIO/eos#4189]
I am getting ``` Unsupported Linux Distribution. Exiting now. ```

When trying to compile under arch linux. Any help regarding this?

**Comment by pacificcode** [comment]
@Jzarecta EOSIO is not currently set up to build on Arch Linux. We will be adding more distributions in the future however.

**Comment by Jzarecta** [comment]
What is stoping it from running on Arch?

**Comment by pacificcode** [comment]
@Jzarecta Yes, we do have Docker code and documents @ https://github.com/EOSIO/eos/tree/master/Docker.
You can also check the Docker/ directory of your clone of the EOSIO repo.

**Comment by Jzarecta** [comment]
@pacificcode any hold up why eosio arch? any way to get some output?

**Comment by jgiszczak** [comment]
@Jzarecta There are no plans to expand the currently supported list of Linux distributions.  Arch users can manually install the required dependencies and run the build.

Anyone wishing to add Arch support to the build scripts is welcome to do so.  Community pull requests will be reviewed.
