### ISSUE TITLE
Obtain irreversible data from smart contracts

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#4191]
Some way to obtain irreversible data from a smart contract is needed (via get_table_rows perhaps).  I understand this is being worked-on, please provide updates when available..  Thank you..

Related: **local node state and unconfirmed data** https://github.com/EOSIO/eosjs/issues/192

**Comment by taokayan** [comment]
You can get the last irreversiable block number then try to retrieve the blocks up to that number. However, in the current version there's no way to retrieve the state(table) up to the last irreversiable block.

**Comment by chuang39** [comment]
@taokayan 
>> You can get the last irreversiable block number
Just curious in the contract, any way we can get last irreversible block number? Thanks!

**Comment by jgiszczak** [comment]
@chuang39 Last irreversible block number is part of the output of `cleos get info` and the corresponding RPC API.  e.g.
```json
{
  "server_version": "08819aae",
  "chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
  "head_block_num": 16959169,
  "last_irreversible_block_num": 16958840,
  "last_irreversible_block_id": "0102c578fb36074565304933c5ffd50ff42b3bd1739e66cb1b5280f67c7773b9",
  "head_block_id": "0102c6c1cd804fb6b48700f2ea4ddc10077e2ac35651b4f60b79fe7ecac70795",
  "head_block_time": "2018-09-17T22:16:26.000",
  "head_block_producer": "libertyblock",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 198685,
  "block_net_limit": 1048352,
  "server_version_string": "v1.2.5"
}
```

**Comment by HashDApp** [comment]
> @chuang39 Last irreversible block number is part of the output of `cleos get info` and the corresponding RPC API. e.g.
> 
> ```json
> {
>   "server_version": "08819aae",
>   "chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
>   "head_block_num": 16959169,
>   "last_irreversible_block_num": 16958840,
>   "last_irreversible_block_id": "0102c578fb36074565304933c5ffd50ff42b3bd1739e66cb1b5280f67c7773b9",
>   "head_block_id": "0102c6c1cd804fb6b48700f2ea4ddc10077e2ac35651b4f60b79fe7ecac70795",
>   "head_block_time": "2018-09-17T22:16:26.000",
>   "head_block_producer": "libertyblock",
>   "virtual_block_cpu_limit": 200000000,
>   "virtual_block_net_limit": 1048576000,
>   "block_cpu_limit": 198685,
>   "block_net_limit": 1048352,
>   "server_version_string": "v1.2.5"
> }
> ```

any updates?

need to retreive last_irreversible_block_id in smart contracts

**Comment by tbfleming** [comment]
If nodeos exposed last irreversible to contracts then it could break consensus. Even though last irreversible moves forwards and never backwards, nodes are not aware of the most irreversible advancing at the same time.

**Comment by tbfleming** [comment]
Not currently
