### ISSUE TITLE
abigen uses struct name instead of table name

### ISSUE THREAD

**Issue by athei** [EOSIO/eos#4197]
I was following the somewhat outdated tic-tac-toe example and tried to generate the ABI for it instead of doing it manually.

I have a game struct declared with the table annotation and a typedef for the table:
```
// @abi table
struct game { ... }
typedef eosio::multi_index<N(games), game> games;
```

What is happening now is that abigen uses `game` instead of `games` for the table name. It just takes the name of the struct. The code still works but you can't query the table with cleos.

Is there some other way to annotate it or must the struct name match the table name for it to work?

**Comment by taokayan** [comment]
The tic-tac-toe contract is out of date and we're going to fix it.

**Comment by andriantolie** [comment]
Use `// @abi table games` instead. We have also updated tic-tac-toe so it supports eosiocpp, waiting for it to be merged https://github.com/EOSIO/eos/pull/4130 :)

**Comment by athei** [comment]
Sweet. I had I really hard time understanding how to generate ABI. We need some documents explaining the annotations.

**Comment by andriantolie** [comment]
Documentation on how to use abigen is on the timeline, you will be able to find it on the developer portals once it's finished. :)
I'm going to close this issue then.
