### ISSUE TITLE
cleos get table secondary key indexing

### ISSUE THREAD

**Issue by basarrcan** [EOSIO/eos#4206]
Hello, 
I'm just trying to use -k option to use my secondary key indexing with cleos get table, but no matter what parameter I put after -k it always returns the same exact result. Is there any additional parameter do I need to use, or any example that shows using secondary key index?

**Comment by melnx** [comment]
the secondary index doesn't get included in the abi file, seems like there needs to be an additional comment above the struct in the header file for the secondary index similar to 
//@abi table accounts i64

**Comment by taokayan** [comment]
ref #3695

**Comment by eoline7** [comment]
same question

**Comment by heifner** [comment]
Resolved by #4053
