### ISSUE TITLE
haven't received the eos in Unstaked after  72 hours (undelegate)

### ISSUE THREAD

**Issue by yanxi-me** [EOSIO/eos#4207]
I undelegated at 2018-06-15T15:18:56, now it's after 72 hours, but still haven't received the eos in unstaked.

$ cleosm get account gu3dsnjtgage -j

```
...
"core_liquid_balance": "3.2898 EOS",
...
"refund_request": {
    "owner": "gu3dsnjtgage",
    "request_time": "2018-06-15T15:18:56",
    "net_amount": "5049.7999 EOS",
    "cpu_amount": "5049.1069 EOS"
  },
...
```

How can I move the refund eos to unstaked?

**Comment by heipacker** [comment]
cleos -u 'http://localhost:8883' get account he2dgnygenes -j

EOS balances: 
     liquid:            3.0000 EOS
     staked:            2.4287 EOS
     unstaking:         0.0000 EOS
     total:             5.4287 EOS

  "refund_request": {
    "owner": "he2dgnygenes",
    "request_time": "2018-06-14T21:50:54",
    "net_amount": "30345.5000 EOS",
    "cpu_amount": "30345.5000 EOS"
  },

**Comment by yanxi-me** [comment]
done after: `./cleos push action eosio refund '{"owner": "youraccountname"}' -p youraccountname`
