### ISSUE TITLE
Docker Images eosio/eos-dev:v1.0.5 and eosio/eos-dev:latest are missing dev tools

### ISSUE THREAD

**Issue by tmuskal** [EOSIO/eos#4208]
https://hub.docker.com/r/eosio/eos-dev/tags/

latest & v1.0.5 are significantly smaller and don't contain eosiocpp anymore.

**Comment by MerouaneBen** [comment]
I'm facing the same issue every time I get this error:  **_eosiocpp: command not found_** , I think something wrong happened when building the latest & v1.0.5 images.

**Comment by bachvtuan** [comment]
It is no longer in folder /opt/eosio/bin. Need someone explain where it is going ?

**Comment by MerouaneBen** [comment]
@bachvtuan it doesn't exist in the versions 1.0.5 and latest. you can use v1.0.4 until they fix the image on the docker hub, or you can build it yourself from the repo.

**Comment by tmuskal** [comment]
seems to fixed 3 hours ago.

**Comment by KennyLiu25775** [comment]
the problem still exists :(  . it still cannot read eosiocpp command :( 
![image](https://user-images.githubusercontent.com/11808716/42342492-176f47e0-804b-11e8-97d5-e93df8f1231a.png)

anyone could help me?
