### ISSUE TITLE
P2P sync failing

### ISSUE THREAD

**Issue by heifner** [EOSIO/eos#421]
This issue is related to #291 stability.

Current sync of producer nodes is not working. Steps to reproduce:
- programs/launcher/launcher -p5 -s mesh --skip-signature
  - -s star, -s ring also exhibit same issue
- programs/eosc/eosc --port 8888 get block 1
- programs/eosc/eosc --port 8889 get block 1
- programs/eosc/eosc --port 8890 get block 1
- programs/eosc/eosc --port 8891 get block 1
- programs/eosc/eosc --port 8892 get block 1
  - The blocks returned do not agree.
  - Also the following is in tn_data_*/stderr.txt
```
426004ms thread-0   net_plugin.cpp:820            handle_message       ] unable to accept block #3 syncing
426004ms thread-0   fork_database.cpp:65          push_block           ] Pushing block to fork database that failed to link: 00000003dcb43dac9f0083ea66e8f62ca0eaf0b6141894412ee3557c4b7a6a18, 3
426004ms thread-0   fork_database.cpp:66          push_block           ] Head: 2, 000000020f5b636cd1777ce3453373501ce6bbccd158725470d91ca855821dde
```
- Large amounts of memory were consumed by the eosd

**Comment by heifner** [comment]
Created a simple test and handed it over to Phil who is actively working this issue with #406. It is much more stable in branch p2p-txn-handling-393, but still can be made to fail via dropped connections.

**Comment by pmesnier** [comment]
I've created a new branch off of "staging" to carry on my work sorting out the p2p networking functionality. This issue relates back to #291 and the working branch is p2p-sync-slow-peers.

**Comment by pmesnier** [comment]
Since I'm not actually working this issue directly, I'm removing the in progress label for now

**Comment by pmesnier** [comment]
I'm pretty sure this is failing simply because the last bit of sync code isn't in place yet. This is the part involving fetching the blocks post irreversible.

**Comment by pmesnier** [comment]
Solution added with PR #543

**Comment by pmesnier** [comment]
PR #543 addresses this issue
