### ISSUE TITLE
Error while creating account create account

### ISSUE THREAD

**Issue by blockchain-expert** [EOSIO/eos#4210]
When I try to create an account, following error shows.
```
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
```
My wallet is unlocked and it has the required keys. Why this happens?

**Comment by rameshb444** [comment]
Same issue here. Did anyone solved this issue?

**Comment by wangjun5** [comment]
Same issue here. Did anyone solved this issue?

**Comment by jgiszczak** [comment]
Show your command line.

**Comment by wangjun5** [comment]
cleos create account eosio xx.test.1 EOS6CAbXRBtAwVqySZqZ1Jgwtwj1mNxFh3iQXAdE9vobKGBYrLyjS EOS72CPirpyB7PD98oLjw2e4RS9E5a9jwrDt3giPqv98UkrA5nk8H

**Comment by wangjun5** [comment]
nodeos:
nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin
create account:
cleos create account eosio wj.test.1 EOS6CAbXRBtAwVqySZqZ1Jgwtwj1mNxFh3iQXAdE9vobKGBYrLyjS EOS72CPirpyB7PD98oLjw2e4RS9E5a9jwrDt3giPqv98UkrA5nk8H
error:
3090003

**Comment by wangjun5** [comment]
nodeos:
nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin
create account:
cleos create account eosio xx.test.1 EOS6CAbXRBtAwVqySZqZ1Jgwtwj1mNxFh3iQXAdE9vobKGBYrLyjS EOS72CPirpyB7PD98oLjw2e4RS9E5a9jwrDt3giPqv98UkrA5nk8H
error:
3090003

**Comment by IvanYakimov** [comment]
If you are using your private testnet than try this:
First, open `config.ini` - the configuration file of the nodeos, you may find it here: `/root/.local/share/eosio/nodeos/config`.
Here you will find something like this:
```signature-provider = EOS${PUBLIC_KEY}=KEY:${PRIVATE_KEY}```
Copy the ${PRIVATE_KEY} into a clipboard.
Now, unlock your wallet:
`cleos wallet unlock` (you will have to enter a password you have got after creating a default wallet)
And, finally, import the ${PRIVATE_KEY} into your wallet:
`cleos wallet import ${PRIVATE_KEY}`
Now you can sign transactions with eosio permissions.

**Comment by rameshb444** [comment]
Thank you @IvanYakimov. Now, it's working..!!

**Comment by grabastart** [comment]
@IvanYakimov 
your advice seems useful. previously i got all sort of errors while creating a simple, new account on local test node.  now, it seems an improvement, no error generated, however, the 
cleos create account eosio mynewaccount EOS6MRyA...publickey simply hanged there, no response,
it's been about 3 minutes already, what could be the problem?
thanks.

**Comment by IvanYakimov** [comment]
@grabastart Sorry, but unfortunately I cannot answer your question as I don't have enough expertise in eos myself. You can try to leave a question on the [https://eosio.stackexchange.com/](https://eosio.stackexchange.com/) forum.
