### ISSUE TITLE
Incorrect  block format？

### ISSUE THREAD

**Issue by a791540852** [EOSIO/eos#4211]
{
    "timestamp": "2018-06-17T17:41:13.000",
    "producer": "bitfinexeos1",
    "confirmed": 0,
    "previous": "0012a8f6ddc64c7e4ae364c1cbaa127c72c7c7c7d1d72e5e51da74fdc578e678",
    "transaction_mroot": "ceba9b6d5ea5f24f5cacab06d0f04d44e14e0e14bc07b064c9cc73e509b12de5",
    "action_mroot": "9b1ca09a0ef7834a06b6ece2557a8cf28690db70d5d5d2e31f6e04ddc6c2bfa4",
    "schedule_version": 15,
    "new_producers": null,
    "header_extensions": [],
    "producer_signature": "SIG_K1_KjUpDyR2Y9XHY7n15ThD9S7HXpDCkR91wqfqNRpzP2Yb73SV1Fy3w9Jrg2BP3Djjzxo5kzVTASDTbEGKC2Ca4WE6Xagb6f",
    "transactions": [
        {
            "status": "executed",
            "cpu_usage_us": 1597,
            "net_usage_words": 0,
            "trx": "7b69b1e053d4edc6b3b7632283f1eca5e160845314b2ae6f298f47c196a14864"
        },
        {
            "status": "executed",
            "cpu_usage_us": 455,
            "net_usage_words": 17,
            "trx": {
                "id": "b9aa1520faba4fc32b86823cbb9a43ccc6df073cd0e4415247c5c356549f6419",
                "signatures": [
                    "SIG_K1_K4teDVDYyaj9aiUT9enrV5q26ftC7CQSnzZ2CB8voHbHJU3A9LVPN4bG5ofkqJBAc1ghWM3CjmALEdk5YmZGgiU8zwWH6J"
                ],
                "compression": "none",
                "packed_context_free_data": "",
                "context_free_data": [],
                "packed_trx": "95a0265bb0a7bcaa291d0000000001a09861f648958566000000000080694a01a09864fa489abe6600000000a8ed323225243230303030303020454f5320626964206163636f756e742067753274656d62716761676500",
                "transaction": {
                    "expiration": "2018-06-17T17:55:33",
                    "ref_block_num": 42928,
                    "ref_block_prefix": 489269948,
                    "max_net_usage_words": 0,
                    "max_cpu_usage_ms": 0,
                    "delay_sec": 0,
                    "context_free_actions": [],
                    "actions": [
                        {
                            "account": "gu2tembqgage",
                            "name": "ddos",
                            "authorization": [
                                {
                                    "actor": "guzdombugmge",
                                    "permission": "active"
                                }
                            ],
                            "data": {
                                "memo": "2000000 EOS bid account gu2tembqgage"
                            },
                            "hex_data": "243230303030303020454f5320626964206163636f756e742067753274656d627167616765"
                        }
                    ],
                    "transaction_extensions": []
                }
            }
        }
    ],
    "block_extensions": [],
    "id": "0012a8f72001df70171f1c4d68e5f9617d52c4c830cf30a4cd06e9ea76cee0a7",
    "block_num": 1222903,
    "ref_block_prefix": 1293688599
}

block height:
1222903
1223716
1223823
1223824
1223913
1224253
1224264
1224468

**Comment by heifner** [comment]
What is the question or issue here?
