### ISSUE TITLE
undelegatebw is ok,but the refund didn't

### ISSUE THREAD

**Issue by oasis-eos** [EOSIO/eos#4212]
I do a undelegatebw 3 days ago(15/6),but refund didn't happen,need i explicitly to claim the refund or anything else is wrong?

**Comment by marketstack** [comment]
after the 3 days of undelegatebw, you must explicitly push refund action

./cleos push action eosio refund '{"owner": "youraccountname"}' -p youraccountname

**Comment by oasis-eos** [comment]
it is ok,thanks!
