### ISSUE TITLE
unexpected behavior in `cleos get table --limit`

### ISSUE THREAD

**Issue by kkurian** [EOSIO/eos#4223]
Using: v1.0.1

Given a contract with a table containing between 200 and 300 rows.

`cleos get table` without a `--limit` returns a consistent result:

```
<<< cleos get table mycontract myscope mytable
>>> (rows: 8)
<<< cleos get table mycontract myscope mytable
>>> (rows: 8)
<<< cleos get table mycontract myscope mytable
>>> (rows: 8)
```

However, when `--limit` is present the following unexpected (to me, at least) behaviors exist:

1. `--limit 0` appears to imply no limit at all.

2. `--limit n` (except for `--limit 0`) appears to be a sort of upper limit but cleos does not provide a best effort to reach that limit.

```
<<< cleos get table --limit 0 mycontract myscope mytable
>>> (rows: 153)
<<< cleos get table --limit 1 mycontract myscope mytable
>>> (rows: 1)
<<< cleos get table --limit 2 mycontract myscope mytable
>>> (rows: 2)
<<< cleos get table --limit 3 mycontract myscope mytable
>>> (rows: 3)
<<< cleos get table --limit 4 mycontract myscope mytable
>>> (rows: 4)
<<< cleos get table --limit 5 mycontract myscope mytable
>>> (rows: 5)
<<< cleos get table --limit 6 mycontract myscope mytable
>>> (rows: 5)
<<< cleos get table --limit 7 mycontract myscope mytable
>>> (rows: 6)
<<< cleos get table --limit 8 mycontract myscope mytable
>>> (rows: 7)
<<< cleos get table --limit 9 mycontract myscope mytable
>>> (rows: 7)
<<< cleos get table --limit 10 mycontract myscope mytable
>>> (rows: 8)
<<< cleos get table --limit 11 mycontract myscope mytable
>>> (rows: 8)
<<< cleos get table --limit 12 mycontract myscope mytable
>>> (rows: 9)
```

With respect to best effort, notice that without `--limit` cleos consistently returns 8 rows. But starting at `limit 6` it returns fewer rows than requested and it isn't until `limit 10` that it returns 8 rows.

This is completely non-intuitive: Without a limit we consistently get 8 rows but with limits of 8 and 9 we get 7 rows.

Also, note that the behavior is nondeterministic. Just one set of runs with `limit` is provided above. Other sets of runs with `limit` will exhibit similar but not identical behavior.

Perhaps all of this is correct behavior? If it is then IMHO it needs to be prominently documented at least at `cleos get table --help`.

**Comment by andriantolie** [comment]
If you don't specify the limit, it will get as many rows as it can in 10 ms
