### ISSUE TITLE
Better checks in multi_index methods that take a reference to an object

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#4228]
`multi_index` methods that take a reference to an object that is supposed to be maintained by the `multi_index` instance (e.g. `modify`, `erase`, `iterator_to`) have some runtime checks to make sure the object is actually managed by the `multi_index` instance.

The problem is that this check is not super robust. There are rare conditions in which the check can fail and undefined behavior ensues. This is only a problem if a contract developer misuses these methods by, for example, passing in a reference to a stack-allocated copy of the object. However, as discussed in #4226, it is too common for developers to accidentally do this.

A more robust check is possible at the cost of performance. The methods could scan the internal vector of `unique_ptr`s to the managed objects and see if any of them match the reference address that was passed in. Since the size of this vector should be small for most contracts, this shouldn't be too bad. Still it is obviously not ideal.

Because the overloads of the potentially problematic methods in `multi_index` that take a reference will be deprecated (see #4226), and the overloads that take a `const_iterator` (by the way, an overload of `iterator_to` that takes `const_iterator` should be added) are safe which means they can avoid this expensive check, it makes sense to implement this more robust check on those methods that take a reference.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
