### ISSUE TITLE
cleos set contract and create account error Unexpected char '60' in “”

### ISSUE THREAD

**Issue by timhang** [EOSIO/eos#4229]
Two weeks ago I tried to use cleos subcommands and everything worked fine. I could set contract to the accounts I created using my own smart contract code. Now whenever I tried set contract or create account, it kept giving this error. I tried changing the config files and rebuilding eos but the program still doesn't seem to work. What can I do here?

p.s. I already read #3782 , only wallet list works but nothing else.

<img width="487" alt="screen shot 2018-06-19 at 4 43 15 pm" src="https://user-images.githubusercontent.com/31256307/41631073-74273dbe-73e7-11e8-9230-b9d6586b3aa7.png">
<img width="452" alt="screen shot 2018-06-19 at 4 43 35 pm" src="https://user-images.githubusercontent.com/31256307/41631074-743eef4a-73e7-11e8-84c4-3e8afb8a7114.png">

**Comment by microingens** [comment]
Same problem here with char '70'
_Failed with error: Parse Error (4)
Unexpected char '70' in "Found."_

**Comment by andriantolie** [comment]
Can you try to kill your keosd and try again?

**Comment by timhang** [comment]
I rebuilt cleos and keosd and killed existing programs on local network then reran nodeos on 8888 and keosd on 8900 and everything seems to work fine now. Also, does the print function from eosio namespace not print to console anymore?

**Comment by andriantolie** [comment]
Great. To enable it you need to set `contracts-console = true` in your config.ini. :)
