### ISSUE TITLE
Unable to issue token to myself

### ISSUE THREAD

**Issue by fundurian** [EOSIO/eos#4233]
Hello, so below is the step i do

1. cleos set contract cdexaccount1 /root/eos/build/contracts/eosio.token -p cdexaccount1

2. cleos push action cdexaccount1 create ‘[“cdexaccount1”,”500000000.00 CDX”]’ -p cdexaccount1 

3. cleos push action cdexaccount1 issue '[ “fundurian112”, “100.00 CDX”, "memo" ]' -p cdexaccount1

then i get error message as below when i do the number3, number1 and number 2 run successfully

the error message is 
Error 3050003: eosio_assert_message assertion failure

**Comment by dskvr** [comment]
`cdexaccount1@active`

**Comment by jgiszczak** [comment]
Try `-p eosio` instead of `-p cdexaccount1` in your third command.  Issuing actually requires three transactions, and fairly sweeping permissions.

**Comment by fundurian** [comment]
no, i cannot use -p eosio as i dont have permission

Do not the above 3 step running fine prior to v1.0.5

**Comment by arhag** [comment]
I could not reproduce this (unless the account you are issuing to does not exist).

To get more information about what the actual error message is, please rerun the nodeos instance you are connecting to with `--verbose-http-errors` (a change in v1.0.4 was too aggressive in squelching debugging output over HTTP which should be made a little more verbose by default in a future release) and try running step 3 again. Then please post the actual error message here.

**Comment by fundurian** [comment]
Hello arhag I want to ask is this the correct way to issue token? 

1. If i issue my own token using my own account+smart contract, the token only exist on my own smart contract and all transaction is not visible on other people block explorer such as eospark.com

2. or all token should be issued by official EOSIO.token account only? If this is the case, we dont have authority to use EOSIO.token account to issue our token for ourself?

**Comment by andriantolie** [comment]
@fundurian Any further hint you can share with the --verbose-http-errors option?

**Comment by fundurian** [comment]
I figured out the issue, it is due to I created the token with 0 decimal point, so when I issue the token i need to put 0 decimal point instead of 2 decimal point

**Comment by fundurian** [comment]
Yes, solved
