### ISSUE TITLE
EOS Token still keep in Refund status over 3 days 

### ISSUE THREAD

**Issue by RickyShiJs** [EOSIO/eos#4234]
Account: gm3tcnzyhege
Step: 
1. Did Refund action on 2018-06-16T08:09:55
```
cleos get table eosio gm3tcnzyhege refunds
{
  "rows": [{
      "owner": "gm3tcnzyhege",
      "request_time": "2018-06-16T08:09:55",
      "net_amount": "14018.4350 EOS",
      "cpu_amount": "14018.1489 EOS"
    }
  ],
  "more": false
}
```
Result:
The token is still in Refund status

![image](https://user-images.githubusercontent.com/7312454/41639897-54a04142-7492-11e8-9da2-ac6807b1c641.png)

**Comment by Eason-Github** [comment]
try
`cleos push action eosio refund '["gm3tcnzyhege"]' -p  gm3tcnzyhege`

**Comment by Eason-Github** [comment]
看这个图，你的 ram （memory）不多了，最好先 买点 ram，防止影响之后的操作

**Comment by jgiszczak** [comment]
Deferred transactions have been erroneously expiring, so manual refund claims have been necessary.  This is expected to be fixed in an upcoming release.
