### ISSUE TITLE
when will a static member of contract class be initialized?

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#4237]
Can I add a static member into a contract class? If yes, when will the static member be initialized? will it be initialized every time an action is called?

**Comment by breadbread1984** [comment]
I find that I can't add a static member to a contract class. If I add one the compiling is OK but Ican't set the contract to the blockchain. The cleos gives the following error message.

>Reading WAST/WASM from test/test.wasm...
Using already assembled WASM...                                                                             Publishing contract...
1858674ms thread-0   main.cpp:2712                 main                 ] Failed with error: Assert Exception (10) 

My code is given below. The contract can be upload successfully if you comment the ERROR macro variable. Why static object is not allowed in contract object.

```c++
#ifndef TEST_HPP
#define TEST_HPP

#include <eosiolib/asset.hpp>
#include <eosiolib/eosio.hpp>

#define ERROR

using namespace std;
using namespace eosio;

class test {
	string str;
public:
	test():str("hello the world!") {}
	string operator()(){return str;}
};

class Test : public contract {
public:
#ifdef ERROR
	static test t;
#endif
	Test(account_name _self): contract(_self){}
	void func();
};

#endif
```

```c++
#include "test.hpp"

#ifdef ERROR
test Test::t = test();
#endif

void Test::func() {
}

EOSIO_ABI(Test,(func))
```

**Comment by CharlesJu1** [comment]
A contract is a WASM module that is stored on blockchain. It will be loaded into memory and initialized and run by an interpreter when an action is issued to the contract. The initialized wasm module is cached in the memory, which means it is not guaranteed to be in the memory all the time. In this context, the meaning of a static field is not well defined. I guess that is why it is not supported. As an alternative, use contract table to store the static value.

**Comment by breadbread1984** [comment]
OK thx
