### ISSUE TITLE
how to uninstall EOS

### ISSUE THREAD

**Issue by sundevilyang** [EOSIO/eos#4238]
Hello There, 

I try to build EOSIO, but failed because of the following picture
![image](https://user-images.githubusercontent.com/1499214/41651683-b9f0f458-74b3-11e8-8a8b-fcbaff8b14cc.png)

and it occupied my hard disc space aout 8 GB .

Can someone tell me where to remove EOSIO ?

thx

**Comment by pacificcode** [comment]
rm -rf /path/to/eos
