### ISSUE TITLE
updted the smart contract table size, query it by get_table_rows api,return failed.

### ISSUE THREAD

**Issue by woo-fight** [EOSIO/eos#4240]
when i change my contract  table:lotterygame : uint8_t => uint16_t,just like:
```
  ///@abi table lotterygame i64
  struct lotterygame : public basegame {
    uint16_t current_index; //===========it was uint8_t  before
    uint16_t max_palyer; //=============it was uint8_t  before
    asset prize_pool; 

    EOSLIB_SERIALIZE(lotterygame, (g_id)(randseed)(end)(date)(current_index)(
                                      max_palyer)(prize_pool));
  };
```
then i snd a table request 
```
POST /v1/chain/get_table_rows HTTP/1.1
Host: 10.0.2.97:8989
Content-Type: application/javascript
Cache-Control: no-cache
Postman-Token: e98f8987-1be1-a206-47b1-d737a5e45335

{
	"scope":"frank1111111", 
	"code":"frank1111111", 
	"table":"lotterygame", 
	"json": true, 
	"lower_bound":"", 
	"upper_bound":-1, 
	"limit":1
}
```
```
respone
{
    "code": 500,
    "message": "Internal Service Error",
    "error": {
        "code": 8,
        "name": "out_of_range_exception",
        "what": "Out of Range",
        "details": []
    }
}
```
and return an error,in my producter node log:
```
1957625ms thread-0   http_plugin.cpp:405           handle_exception     ] FC Exception encountered while processing chain.get_table_rows
1957625ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 8 out_of_range_exception: Out of Range
read datastream of length 39 over by -4
    {"method":"read","len":39,"over":-4}
    thread-0  datastream.cpp:6 throw_datastream_range_error
error unpacking uint64_t
    {"type":"uint64_t"}
    thread-0  raw.hpp:616 unpack
Error unpacking field m_value
    {"field":"m_value"}
    thread-0  raw.hpp:368 operator()
error unpacking eosio::chain::symbol
    {"type":"eosio::chain::symbol"}
    thread-0  raw.hpp:616 unpack
Error unpacking field sym
    {"field":"sym"}
    thread-0  raw.hpp:368 operator()
error unpacking eosio::chain::asset
    {"type":"eosio::chain::asset"}
    thread-0  raw.hpp:616 unpack
```
any dieas? thank you
vertion info
![image](https://user-images.githubusercontent.com/21164253/41659253-57036930-74cb-11e8-806c-ca44636efb75.png)

**Comment by heifner** [comment]
Did you update your *.abi file?

**Comment by woo-fight** [comment]
yep, i run ``` eosioapp -g xxx.abi xxx.cpp```before deploy the contract

**Comment by heifner** [comment]
Did you already have data in the table? With the old layout?

**Comment by woo-fight** [comment]
yes,  the table data already exist in blockchain before i update the table struct

**Comment by heifner** [comment]
Then that is the problem. It is trying to serialize the old data out with the new abi and is failing.

**Comment by heifner** [comment]
If you need to keep the old data then create a new table and copy the rows over.

**Comment by woo-fight** [comment]
you mean i must rename the table name or deploy the contract with new account？

**Comment by heifner** [comment]
Revert the contract back to uint8_t so you can again interact with the table. Then if you want to preserve the data in the table. Create a new table with the new schema and copy the rows from the old table to the new. You can delete from the old table as you go or delete them all from the old table when done. At that point you can update your contract by removing the old table struct.

**Comment by msj121** [comment]
@heifner Is there an easy way to delete all data using cleos, or do you have to delete each row as it is searched?

**Comment by msj121** [comment]
Okay, Thank you. Was running into this error before and started a new blockchain, good to know that erasing the data will solve it.
