### ISSUE TITLE
`/opt/eosio` not created

### ISSUE THREAD

**Issue by paul-mesnilgrente** [EOSIO/eos#4241]
Hi everyone,

I am having trouble to start working with `eos` because of the docker file. If I follow the [docker quickstart](https://developers.eos.io/eosio-nodeos/docs/docker-quickstart), I just have to pull `eosio/eos-dev`, run it, and the folder `/opt/eosio` should be created. I say this because the paragraph after the run says to create this alias: `alias cleos='docker exec eosio /opt/eosio/bin/cleos --wallet-url http://localhost:8888'`.
But this alias can't work with me because I don't have any folder `/opt/eosio`.

Do you have an idea?

**OS:** Ubuntu 18.04
**Docker:** 18.03.1-ce

**Comment by bachvtuan** [comment]
This folder is created inside docker 18.03.1-ce not on your OS 18.04.

**Comment by paul-mesnilgrente** [comment]
Ok I think I don't get everything about docker yet. How do I enter into this system? Because when I run the alias, the file is not found anyway.

**Comment by bachvtuan** [comment]
your alias look good. what response when you run cleos ?

**Comment by paul-mesnilgrente** [comment]
Ok I understood the problem, it is much easier to solve now that I know that Docker has its own file hierarchy. Btw, how can I explore it?

The problem was that my alias was defined my current user, but docker needs `sudo` to run. When I was running the command with sudo, the alias was not found. I was sure to have tested it without the alias and typing the direct command, but apparently no.

My next move I think will to make docker work for the normal user. Thank you very much :)

**Comment by bachvtuan** [comment]
Great if I helped you.

```
docker container exec -it eosio bash
```
That command will give you logged in into docker  and /opt/eosio should be here :)
