### ISSUE TITLE
Unable to sell RAM in one account and distribute proceeds to another

### ISSUE THREAD

**Issue by andrei-anisimov** [EOSIO/eos#4262]
I own 2 accounts: `someaccount1` and `someaccount2`. I'd like to sell RAM in `someaccount2` and distribute proceeds into `someaccount1`. I follow the docs and use `-p` argument to modify the authorization, because I assume that setting authorization to `someaccount2` instructs the system to sell RAM in `someaccount2` account. The command looks like this: 
`cleos system sellram -p 'someaccount2@active' -d someaccount1 4096`

However, the generated transaction JSON still has `someaccount1` under authorization
```
...
  "context_free_actions": [],
  "actions": [{
      "account": "eosio",
      "name": "sellram",
      "authorization": [{
          "actor": "someaccount1",
          "permission": "active"
        }
      ],
      "data": "202952d89cdc98530010000000000000"
    }
  ],
  "transaction_extensions": [],
...
```

**Comment by andrei-anisimov** [comment]
Yes, I understand that I can manually do this. Looks like this is still a bug though, because `-p` should be able to set the authority and it doesn't.

**Comment by andriantolie** [comment]
This is fixed in https://github.com/EOSIO/eos/issues/6113
