### ISSUE TITLE
Error 3040005: Expired Transaction (Please increase the expiration time of your transaction!)

### ISSUE THREAD

**Issue by ddzyan** [EOSIO/eos#4265]
eos version:v1.0.5
os:centos 7

![image](https://user-images.githubusercontent.com/9130123/41705498-b6e21b08-756b-11e8-82a5-3acc6171fa93.png)

![image](https://user-images.githubusercontent.com/9130123/41705533-cffbbd60-756b-11e8-9b39-dff5c536d1a0.png)

**Comment by ddzyan** [comment]
"Max-transaction-time = 30000" has been set in config.ini.

**Comment by andriantolie** [comment]
Is anybody producing in your chain?

**Comment by andriantolie** [comment]
Is everything fine?

**Comment by ismyhc** [comment]
Im having a similar issue, although the error message isnt giving quite as much advice. Im setting the expiration about 24 hours from head_block_time.

```
{
  "packed_context_free_data" : "",
  "compression" : "none",
  "signatures" : [
    "SIG_K1_K1iX2jDHsi1eXy1nKHwBXadxBCF5V9nw2hcKtPtiDrSeuTBoPwdD6qwrP9hWw6V76cxUAWzqtGwvqsQmKdsDjoZAGsPqN4"
  ],
  "packed_trx" : "0000000000000000000000000000000043a6375b0000275c14caae32000010a682343ea3055000572d3ccdcd110b0db269d4391790000a8ed32322f10b0db269d43917990d45dd35142fe5100000002454f530000e746573742066726f6d206c796e78000000000000000000000000000000000"
}
```

```
{
  "code": 400,
  "message": "Bad Request",
  "error": {
    "code": 3040005,
    "name": "expired_tx_exception",
    "what": "Expired Transaction",
    "details": [
      
    ]
  }
}
```

**Comment by andriantolie** [comment]
Hi @ismyhc, which version that you use? Also, what is your current head block time? Has your local node catched up with the mainnet?
