### ISSUE TITLE
start  keosd --http-server-address=localhost:8899 error

### ISSUE THREAD

**Issue by qq5254232** [EOSIO/eos#4267]
root@eostest:~/eosio-wallet# keosd --http-server-address=localhost:8899
2637618ms thread-0   main.cpp:52                   main                 ] /opt/eos_src/libraries/appbase/application.cpp(304): Throw in function appbase::abstract_plugin &appbase::application::get_plugin(const string &) const
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: unable to find plugin: eosio::chain_api_plugin

**Comment by cppfuns** [comment]
检查下 config.ini 中 有没有添加  plugin = eosio::chain_api_plugin

**Comment by qq5254232** [comment]
root@:~# keosd --http-server-address=127.0.0.1:8889
2759258ms thread-0   main.cpp:52                   main                 ] /opt/eos_src/libraries/appbase/application.cpp(304): Throw in function appbase::abstract_plugin &appbase::application::get_plugin(const string &) const
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: unable to find plugin: eosio::chain_api_plugin

  root:~# tail -10 /data/eos/eos_wallet/config.ini 
# plugin =
plugin = eosio::chain_api_plugin
plugin = eosio::history_api_plugin
plugin = eosio::producer_plugin
plugin = eosio::wallet_api_plugin
plugin = eosio::http_plugin
plugin = eosio::wallet_plugin
plugin = eosio::history_plugin
plugin = eosio::http_client_plugin
plugin = eosio::http_plugin 
root@:~#

**Comment by cppfuns** [comment]
The default config.ini for Linux OS loading should be
`~/.local/share/eosio/nodeos/config/config.ini`

--------------------------------
Welcome to browse https://www.bcskill.com ,May help you with some common questions

**Comment by jgiszczak** [comment]
The only plugins compiled into keosd are `wallet_api_plugin`, `wallet_plugin`, and `http_plugin`, all of which are hardcoded to be initialized at startup.  Keosd can not use the same config.ini as nodeos, and ordinarily does not need a config.ini at all.
