### ISSUE TITLE
High "latency" in "Received block"

### ISSUE THREAD

**Issue by trungtt1981** [EOSIO/eos#4269]
My built version of nodeos (master branch): `a97a49a0dd4f5051dc7de1de4bc654fedf49cadf`

I've run the script `${EOS_INSTALL_DIR}/tutorials/bios-boot-tutorial/script_bios_boot.sh` to deploy a testnet on some virtual server.
After that, I start a local nodeos that gets connected to this remote testnet. 
Everything works fine.
However, after a long while, the local nodeos seems to be running in a situation that the `latency` value in `Received block` is very high. Consequently, all transactions that go via this local nodes are expired.

```
0|script_c | 2449775ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block fb6ac5f36e2513c9... #8000 @ 2018-06-19T05:31:19.000 signed by producer111d [trxs: 0, lib: 7865, conf: 0, latency: 198570775 ms]
0|script_c | 2460079ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 6e46f9724a80e6e5... #9000 @ 2018-06-19T05:39:39.000 signed by producer111g [trxs: 0, lib: 8861, conf: 0, latency: 198081079 ms]
0|script_c | 2470377ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 640c594a3d7690b9... #10000 @ 2018-06-19T05:47:59.000 signed by producer111j [trxs: 0, lib: 9857, conf: 0, latency: 197591377 ms]
0|script_c | 2481194ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block aefb8281daa941cf... #11000 @ 2018-06-19T05:56:19.000 signed by producer111d [trxs: 0, lib: 10865, conf: 0, latency: 197102194 ms]
0|script_c | 2491786ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 49b7d5cb2d435ce9... #12000 @ 2018-06-19T06:04:39.000 signed by producer111g [trxs: 0, lib: 11861, conf: 0, latency: 196612787 ms]
0|script_c | 2505076ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 88971c698b567def... #13000 @ 2018-06-19T06:12:59.000 signed by producer111j [trxs: 0, lib: 12857, conf: 0, latency: 196126077 ms]
```

This kind of situation will be resolved only if I stop the currently-running testnet and re-run the script `${EOS_INSTALL_DIR}/tutorials/bios-boot-tutorial/script_bios_boot.sh`

I guess that the root cause is because the local nodeos is downloading a huge amount of produced blocks.

**Comment by heifner** [comment]
The latency reported is from the time the block was created, not network latency.

**Comment by keeplearning77** [comment]
Sometimes negative value is observed for latency. Could this be due to the clock on the producer being ahead than the the receiver node?

info  2019-04-24T14:54:23.467 thread-0  producer_plugin.cpp:345       on_incoming_block    ] Received block c0bfc5dd5160ef18... #54664349 @ 2019-04-24T14:54:23.500 signed by eossv12eossv [trxs: 18, lib: 54664013, conf: 0, latency: -32 ms]

**Comment by heifner** [comment]
Producers can configure a block to be released ahead of its scheduled time which will show as a negative latency.
