### ISSUE TITLE
Cleos Command Does Not Exist

### ISSUE THREAD

**Issue by fonsolo** [EOSIO/eos#4271]
While following the instructions on [https://developers.eos.io/eosio-nodeos/docs/docker-quickstart](url) I managed to set up Docker and finish all steps up to the "Cleos" section. Once I tried to complete the "Cleos" section, I ran into an issue when I attempted to run the command **$ cleos --help**. After attempting to run the command, I received an error message stating that the command does not exist. 

Has anyone else had this issue? I would really appreciate any help I could get regarding this, as I am bran new to Linux. Thanks ahead of time!

**Comment by cppfuns** [comment]
cd eos_source_dir/build
sudo make install
------------------------------------------------------------
Welcome to browse https://www.bcskill.com，May help you with some common questions

**Comment by fonsolo** [comment]
Wonderful, thank you very much! This should prove to be extremely valuable to me. Have a wonderful day/night!

**Comment by rajkumarpatoliya** [comment]
done everything still stays the problem...

**Comment by cppfuns** [comment]
> done everything still stays the problem...
try
sudo ./eosio_install.sh
------------------------------------------------------------
Welcome to browse https://www.bcskill.com ,May help you with some common questions

**Comment by rajkumarpatoliya** [comment]
Thank you.
