### ISSUE TITLE
Selling RAM must abide the market price for ram trading to succeed

### ISSUE THREAD

**Issue by dmore** [EOSIO/eos#4275]
After browsing the code, looks to me buyram and sellram methods are currently of different pricing strategy. Whereas the buyram contract uses the bancor algorithm, code comment says selling ram is sold at the purchase price?. Is that a reference to the original purchase price it was last bought at? or is it the market price of ram kb at the time of the sale? the latter being what I expect.

``  
    *  While buying ram uses the current market price according to the bancor-algorithm, selling ram only
    *  refunds the purchase price to the account. In this way there is no profit to be made through buying
    *  and selling ram.
    */
   void system_contract::sellram( account_name account, int64_t bytes ) {
      require_auth( account );
      eosio_assert( bytes > 0, "cannot sell negative byte" );

      user_resources_table  userres( _self, account );
      auto res_itr = userres.find( account );
      eosio_assert( res_itr != userres.end(), "no resource row" );
      eosio_assert( res_itr->ram_bytes >= bytes, "insufficient quota" );

      asset tokens_out;
      auto itr = _rammarket.find(S(4,RAMCORE));
      _rammarket.modify( itr, 0, [&]( auto& es ) {
          /// the cast to int64_t of bytes is safe because we certify bytes is <= quota which is limited by prior purchases
          tokens_out = es.convert( asset(bytes,S(0,RAM)), CORE_SYMBOL);
      });

      _gstate.total_ram_bytes_reserved -= static_cast<decltype(_gstate.total_ram_bytes_reserved)>(bytes); // bytes > 0 is asserted above
      _gstate.total_ram_stake          -= tokens_out.amount;

      //// this shouldn't happen, but just in case it does we should prevent it
      eosio_assert( _gstate.total_ram_stake >= 0, "error, attempt to unstake more tokens than previously staked" );

      userres.modify( res_itr, account, [&]( auto& res ) {
          res.ram_bytes -= bytes;
      });
      set_resource_limits( res_itr->owner, res_itr->ram_bytes, res_itr->net_weight.amount, res_itr->cpu_weight.amount );

      INLINE_ACTION_SENDER(eosio::token, transfer)( N(eosio.token), {N(eosio.ram),N(active)},
                                                       { N(eosio.ram), account, asset(tokens_out), std::string("sell ram") } );
      auto fee = tokens_out.amount / 200;
      if( fee > 0 ) {
         INLINE_ACTION_SENDER(eosio::token, transfer)( N(eosio.token), {account,N(active)},
            { account, N(eosio.ramfee), asset(fee), std::string("sell ram fee") } );
      }
   }
``

**Comment by arhag** [comment]
That comment is old and does not reflect what the code actually does now. The comment has been updated in PR #4293.

**Comment by dmore** [comment]
I can confirm the functionality works as I expected. Apologies and best regards.
