### ISSUE TITLE
Unable to connect to keosd, if keosd is running please kill the process and try again.

### ISSUE THREAD

**Issue by KennyLiu25775** [EOSIO/eos#4276]
Hey guys so when i try to create a wallet from cleos it always says

`
"/usr/local/bin/keosd" launched
Unable to connect to keosd, if keosd is running please kill the process and try again."` 

I tried to kill keosd by using `pkill keosd` but its not working, i even tried to re-download the code and re-installed it, the problem still persists. Appreciate it if anyone could help me

**Comment by asshidhak** [comment]
same:  
Unable to connect to keosd, if keosd is running please kill the process and try again.

**Comment by cppfuns** [comment]
https://www.bcskill.com/index.php/archives/105.html

**Comment by KennyLiu25775** [comment]
thank you very much, the code was very useful, problem solved
