### ISSUE TITLE
reading multi_index container in scope of another user requires authority

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#4279]
I implement an action which creates a multi_index with receiver as the code and another account as the scope. Calling this action with receiver's authority fails with error message

>Error 3090004: missing required authority                                                                                                                             Ensure that you have the related authority inside your transaction!;                                                                                                  If you are currently using 'cleos push action' command, try to add the relevant authority using -p option.

I doesn't use require_auth in the action. Why does the action ask for authority of another account?

**Comment by breadbread1984** [comment]
@andriantolie thx for replying. I already solved the problem.

**Comment by andriantolie** [comment]
Great
