### ISSUE TITLE
Testnet?

### ISSUE THREAD

**Issue by ChrisCates** [EOSIO/eos#4280]
Curious when the EOS team will have their official testnet up...

I noticed a group called CryptoLions took the liberty of starting one, but this is not maintained by the EOS team.

**Comment by matthewdarwin** [comment]
Not sure why you think EOSIO (BlockOne) needs to run an official test net.  It's up to the community to do this.

**Comment by jgiszczak** [comment]
Block.one has decided to forego creation of any new public testnets, specifically because the community has stepped up and filled the need several times over.
