### ISSUE TITLE
nodeosd and keosd are separated?

### ISSUE THREAD

**Issue by ChrisCates** [EOSIO/eos#4281]
I'm pretty confused why these two daemons are separate from each other.
The chain API can't interact with the wallet API...

I noticed that this daemon used to be all one binary originally...

Was there a particular reason to separate them instead of using flags when running the daemon?

**Comment by jgiszczak** [comment]
The chain API has no reason to interact with the wallet API, and shouldn't.  The only reason the wallet_plugin was ever linked into nodeos was testing purposes.  The wallet is to hold keys and sign things.  Nothing more.  The chain is given transactions to process.  The chain should not be meddling with private keys.

The distinction will become much more evident as keosd evolves to support hardware wallets.  In hardware wallets, keys are completely inaccessible outside of the device.

**Comment by ChrisCates** [comment]
@jgiszczak that's pretty reasonable.
I only brought this up because of the design decisions in the old docker image.

Please make sure to remove the redundant docker image on the master branch and verbosely specify the new docker image!
