### ISSUE TITLE
How to develop multiple contracts communicate with each other?

### ISSUE THREAD

**Issue by lingyiliu016** [EOSIO/eos#4283]
When I intend to develop a contract that trade goods on market ,I found that I have to develop a contract communicated with eosio.token contract, because customers trade goods with token. it means that the contract must call transfer that is a member function of eosio.token contract.
     I have developed three seperated contracts, each contract is very simple.because they are all test case.  currency contract represents the eosio.token contract.
     I have develop currency contracts and goods contracts,and deployed on blockchain, everything is ok!
     but I don't know how to use market contract to call currency contracts and goods contracts.
     specific as follow:
     Here is the three contract structure
<img width="201" alt="1" src="https://user-images.githubusercontent.com/27277897/41767446-3239d91e-763c-11e8-9bef-41e1a4d5573b.png">
     Here is currency contract(currency.hpp and currency.cpp)
<img width="567" alt="currency hpp" src="https://user-images.githubusercontent.com/27277897/41767663-e0978786-763c-11e8-9428-452ae690d019.png">
<img width="614" alt="currency cpp" src="https://user-images.githubusercontent.com/27277897/41767678-e7ab1c18-763c-11e8-9343-c48bf780a2a1.png">
     Here is goods contract(goods.hpp and goods.cpp)
<img width="742" alt="goods hpp" src="https://user-images.githubusercontent.com/27277897/41767744-04b3c63e-763d-11e8-879f-8e85598ee42f.png">
<img width="707" alt="20180622181315" src="https://user-images.githubusercontent.com/27277897/41771498-f4328b64-7647-11e8-9258-5630d4ef9775.png">
    Here is market contract(market.hpp and market.cpp)
<img width="786" alt="market hpp" src="https://user-images.githubusercontent.com/27277897/41768060-d345f8e6-763d-11e8-80ee-092039debd4d.png">
<img width="779" alt="market cpp" src="https://user-images.githubusercontent.com/27277897/41768073-da6c148e-763d-11e8-83e8-a07951793233.png">

**Comment by lingyiliu016** [comment]
I don't know how to write market.hpp and market.cpp .Here is a example ,but doesn't work!
anyone help me? give me some suggetions ,please! 
Thakn you very much!

**Comment by lingyiliu016** [comment]
I have seen on the eos official website that multiple contracts can interact with each other.
Here is the screenshot.
<img width="777" alt="20180622170942" src="https://user-images.githubusercontent.com/27277897/41768548-14f1cc88-763f-11e8-9304-5af90fc4eb4e.png">
But the website doesn't give a example,so I don't know write it!

**Comment by lingyiliu016** [comment]
I think the content of market.cpp is probably like this:
<img width="811" alt="20180622180641" src="https://user-images.githubusercontent.com/27277897/41771242-0a18d8e4-7647-11e8-92a9-be541aa7a97c.png">
Maybe I'm  one step closer to he correct answer, but there are still many error!

**Comment by abhi3700** [comment]
Please make a tutorial on this, if possible.

And post it on utopian community over STEEM Blockchain. This is for getting reward for contribution. 

It will be really helpful for the EOS developer community.
