### ISSUE TITLE
Invalid padding yields a confusing error

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#4284]
The error below is this: `"quantity":"1.200 SYS"`

It should have been this: `"quantity":"1.2000 SYS"`

But the error message did not reflect that:  Internal Service Error

SYS is an asset in the eosio.token contract..

>api < error 	 undefined http://127.0.0.1:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-06-22T12:42:25","ref_block_num":5181,"ref_block_prefix":660326027,"net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio.token","name":"transfer","authorization":[{"actor":"inita","permission":"active"}],"data":{"from":"inita","to":"initb","quantity":"1.200 SYS","memo":""}}],"transaction_extensions":[]},"signatures":["SIG_K1_KcrUXMPebMuwafL1PaXHwWaobQE6pBt2T19BgdE47NxdEa9ZwTBjHdcqBEkwoFGiUYCXk6gr5nukG7Kqig2wnE2mNU3m3x"]}

>{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[]}}
    at /home/jcalfee/eosjs/eosjs/node_modules/eosjs-api/lib/apigen.js:95:23
    at process._tickCallback (internal/process/next_tick.js:68:7) status: 500, statusText: 'Internal Server Error' }
[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[]}}', transaction 'b1ee2c5b3d148bc65b27000000000100a6823403ea3055000000572d3ccdcd01000000000093dd7400000000a8ed323221000000000093dd74000000008093dd74b00400000000000003535953000000000000'

```

**Comment by andriantolie** [comment]
If you take a look at the `error.code`, it is 3050003 which is eosio_assert_message_exception, however, the `error.details` is empty now. This is because in the latest version the error message is suppressed if you start nodeos with --verbose-http-errors option, you can see a more descriptive error message. :)

**Comment by ismyhc** [comment]
@jcalfee @andriantolie is there somewhere that documents the exact requirements for quantity when doing push_transaction ? This bit me today until I found this git issue. I wasnt sending up exactly 4 decimal places. Once I changed that, it worked fine.. :)

**Comment by jcalfee** [comment]
I believe it is a case-by-case basis so you'll have to code it if you know for sure and it can't change or you'll have to let the user provide the correct digits.  It is at least error proof so I don't know that is it risky, just manual.  

I believe it is an awkward thing to fix now, it was not handled in the transaction bytes in the beginning and now it is hard to change ;-o .. This is just my opinion though, I'm not a first hand coder in eos I just look at the code.
