### ISSUE TITLE
How to delete the account's public key

### ISSUE THREAD

**Issue by heiduya** [EOSIO/eos#4287]
My account AAA has two public keys like this:
Account name : AAA
Owner EOSXXXXXXXXXa 
Active EOSXXXXXXXXXa
Owner EOSXXXXXXXXXb  
Active EOSXXXXXXXXXb
How to delete the account's public key EOSXXXXXXXXXa,and keep the EOSXXXXXXXXXb
Positionals:authority TEXT - [delete] NULL, [create/update] public key, JSON string, or filename defining the authority
_cleos set account authority_ ???
I looked up the developer documentation, but didn't see how to do it,maybe my question is stupid,I really need help.

**Comment by heiduya** [comment]
anybody can help me ?

**Comment by cppfuns** [comment]
https://www.bcskill.com/index.php/archives/51.html

**Comment by andriantolie** [comment]
I assume your account looks like this now (when you call `cleos get account AAA`)
```
permissions:
     owner     1:    1 EOSXXXXXXXXXa, 1 EOSXXXXXXXXXb
        active     1:    1 EOSXXXXXXXXXa, 1 EOSXXXXXXXXXb
```

In that case, you can just use `cleos set account permission`.
The following command is used to update active:
```
cleos set account permission AAA active EOSXXXXXXXXXb owner -p AAA@owner
```
The following command is used to update owner:
```
cleos set account permission AAA owner EOSXXXXXXXXXb -p AAA@owner
```
