### ISSUE TITLE
Can't create account on local testnet

### ISSUE THREAD

**Issue by syncro2017** [EOSIO/eos#4289]
Im trying to follow the tutorial from here: https://developers.eos.io/eosio-nodeos/docs/learn-about-wallets-keys-and-accounts-with-cleos however im getting error when i try to create the account

I build EOSIO from github today, latest and greatest

Environment:

I have nodeos running: nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin 

I have keosd running on the default port 8900

Wallet is unlocked and keys imported:

devel@devel-VM:[~]: cleos --wallet-url=http://localhost:8900 wallet list
Wallets:
[
  "default *"
]

devel@devel-VM:[~]: cleos --wallet-url=http://localhost:8900 wallet keys
[
  "EOS5XXhUDzMCCTdmWjfLGNvCvfoaHBd5v9Z3cK5yLbQyWn4kvsjfV",
  "EOS5xKKqQ1yqbJdUeCyrwwHuZwGdLQWGuWiigBwyKcQnaywn8ejdo"
]

Here is the eosio key from nodeos config.ini:

signature-provider = EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3

When i run create account, i get this:

devel@devel-VM:[~]: cleos --wallet-url=http://localhost:8888 create account eosio testaccount12 EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV EOS5XXhUDzMCCTdmWjfLGNvCvfoaHBd5v9Z3cK5yLbQyWn4kvsjfV
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.

Any help would be really appriciated

**Comment by syncro2017** [comment]
I just discovered (i hope im right) that the eosio key has to be imported into the wallet as well??
well i did import it and now got another error trying to create account

`2111500ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 00002981ead30e05... #10625 @ 2018-06-22T20:35:11.500 signed by eosio [trxs: 0, lib: 10624, confirmed: 0]
2112000ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 00002982ee6129e4... #10626 @ 2018-06-22T20:35:12.000 signed by eosio [trxs: 0, lib: 10625, confirmed: 0]
2112501ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 00002983da6ecb6d... #10627 @ 2018-06-22T20:35:12.500 signed by eosio [trxs: 0, lib: 10626, confirmed: 0]
2113000ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 00002984bda98ae8... #10628 @ 2018-06-22T20:35:13.000 signed by eosio [trxs: 0, lib: 10627, confirmed: 0]
2113455ms thread-0   http_plugin.cpp:405           handle_exception     ] FC Exception encountered while processing chain.push_transaction
2113455ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 3090003 unsatisfied_authorization: provided keys, permissions, and delays do not satisfy declared authorizations
transaction declares authority '{"actor":"eosio","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys ["EOS76LS62CaFQunU7X4qh4DMFn5xrLriNShubfZihwv2WmD9Aad9u"]
    {"auth":{"actor":"eosio","permission":"active"},"provided_delay":0,"provided_permissions":[],"provided_keys":["EOS76LS62CaFQunU7X4qh4DMFn5xrLriNShubfZihwv2WmD9Aad9u"],"delay_max_limit_ms":3888000000}
    thread-0  authorization_manager.cpp:409 check_authorization
2113501ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 000029854219113e... #10629 @ 2018-06-22T20:35:13.500 signed by eosio [trxs: 0, lib: 10628, confirmed: 0]
`

**Comment by KennyLiu25775** [comment]
hey man, I got exact same problem with you:
appreciate it if anyone could help us :)

![image](https://user-images.githubusercontent.com/11808716/41800184-4a365348-7629-11e8-8d79-bc8022a064c5.png)

**Comment by kofwang** [comment]
+1

**Comment by daithi-coombes** [comment]
+1 have same issue here.

Following same instructions instructions as op: https://developers.eos.io/eosio-nodeos/docs/learn-about-wallets-keys-and-accounts-with-cleos

I'm getting from within `docker` container, using latest image `eosio/eos` here: https://github.com/daithi-coombes/docker-eos/blob/master/docker-compose.yml

Once up (as per instructions) I ssh into container and start `keosd` with non default port `keosd --http-server-address=localhost:8899` (`nodeos` is running at this stage). Then check wallet is opened and has keys
```
cleos --wallet-url=http://localhost:8899 wallet list
cleos --wallet-url=http://localhost:8899 wallet list keys
```
Is unlocked, and has keys using the above. I then try creating account:
```
cleos --wallet-url=http://localhost:8899 create account eosio myaccount ${public_key_1} ${public_key_2}
```
Have same result
```
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
```

Same result with docker image `eosio/eos-dev`.

**Comment by daithi-coombes** [comment]
Think I have it, well just created my first account.

All commands on `cleos` from creating default wallet, importing keys - and `import eosio genesis key` to relevant wallet must be done with `keosd --wallet-url=http://localhost:8899`, or whatever custom port.

(will update readme on my test repo: https://github.com/daithi-coombes/docker-eos)

**Comment by orchi** [comment]
Same issue and the above suggestion did not work. 

cleos --wallet-url=http://localhost:8899 create account eosio myaccount EOS5Ss4crxKboKx5bN4VGBYhZKmc3spVHjVmeFznzCLWFHcEZXAJt EOS7AjnQmXNmoDqDqLsWSrW4cxENHTUSN9FonYEtsrPPdCEtiu4FQ
Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.

**Comment by chadrickm** [comment]
same issue mentioned here: https://eosio.stackexchange.com/questions/1107/cleos-create-account-error-failed-with-error-assert-exception-10-prefix-matc

**Comment by chadrickm** [comment]
@daithi-coombes it looks like your documentation is setting the eosio key as the active key on the default wallet. I'll try the same thing and see if I can get it to work on local testnet.

**Comment by KennyLiu25775** [comment]
Thank you so much man @daithi-coombes the problem solved!

**Comment by andriantolie** [comment]
Is everything alright here?

**Comment by andriantolie** [comment]
How did you start your keosd?

**Comment by syncro2017** [comment]
in order for keosd to run on port 8899 i have to start it like this:

keosd --http-server-address=localhost:8899

is i just run keosd it would default to port 8900

Do i need to pass the path to the config file to it?

**Comment by andriantolie** [comment]
You can pass the config dir `keosd --config-dir ~/eosio-wallet` to make it explicit, but you shouldn't need to do it if your config file is inside ~/eosio-wallet

Are you sure, you put the right parameter name in your ~/eosio-wallet/config.ini?
which is `http-server-address = 127.0.0.1:8899` and run `keosd` without any argument?

**Comment by syncro2017** [comment]
this is wierd, i just tried it again and it seems to work as expected reading form ~/eosio-wallet/config.ini without the need to pass any argument to keosd.
I think its all good now, will test more to make sure and report

**Comment by serganus** [comment]
I have this same issue.

# Recreate this error

## (A) Get the latest eosio-dev, start the docker image and go into the image

```
docker pull eosio/eos-dev

sudo docker run --rm --name eosio -p 8888:8888 -p 9876:9876 -v /Users/gautamanand/Library/Github/serganus/ReliefChain-smartcontracts:/tmp/work -v /Users/gautamanand/Library/Github/serganus/dataEOS:/mnt/dev/data -v /Users/gautamanand/Library/Github/serganus/dataEOS:/mnt/dev/config eosio/eos-dev /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console"

docker exec -it eosio /bin/bash
cd /tmp/work

```

# (B) Create a wallet and unlock it

```
cleos wallet create
cleos wallet unlock --password "PW5HyRv1mxYV3XQYNPaYJyRtQKp5dactf3KzYWUs6aagahopScufc"

```

# (C) Check if the eosio account exists
```
cleos get account eosio
```

# (D) Creatign eosio.token account
```
# Onwer
cleos create key
Private key: 5HsE7QJXpM6pDdwBshszMQ88Qx2zA5qx5AJwRS1ts47vaG1hyCL
Public key: EOS71NjMU5cn8GpGZfaFGYHyUmmkrdrQUtbZ1RgLStw6Fdzg9gF2v

# Active
cleos create key
Private key: 5KR8cSn9227qVhZv5Ve2RD1W5aiWKLTprsxJb7qBceygpddDrNi
Public key: EOS68n41qFudrHH1DjbXCiiQQEKbW1TX9gcMMyUDg7a4Y8T1J25fj

cleos wallet import 5HsE7QJXpM6pDdwBshszMQ88Qx2zA5qx5AJwRS1ts47vaG1hyCL
cleos wallet import 5KR8cSn9227qVhZv5Ve2RD1W5aiWKLTprsxJb7qBceygpddDrNi

cleos create account eosio eosio.token EOS71NjMU5cn8GpGZfaFGYHyUmmkrdrQUtbZ1RgLStw6Fdzg9gF2v EOS68n41qFudrHH1DjbXCiiQQEKbW1TX9gcMMyUDg7a4Y8T1J25fj -p eosio

cleos get account eosio.token

cleos push action eosio updateauth "{\"account\":\"eosio.token\",\"permission\":\"active\",\"parent\":\"owner\",\"auth\":{\"keys\":[{\"key\":\"EOS71NjMU5cn8GpGZfaFGYHyUmmkrdrQUtbZ1RgLStw6Fdzg9gF2v\", \"weight\":1}],\"threshold\":1,\"accounts\":[{\"permission\":{\"actor\":\"eosio\",\"permission\":\"eosio.code\"},\"weight\":1}],\"waits\":[]}}" -p eosio.token
```
# (F) Output

<img width="701" alt="screen shot 2018-06-30 at 1 13 42 am" src="https://user-images.githubusercontent.com/12946435/42105419-e05cfe6a-7c02-11e8-8809-969aea18b0ab.png">

**Comment by PaulCalabrese** [comment]
You will need to import the private key for the eosio account to create
accounts like this.  This key is no longer loaded by default.
You can find this key in your config.ini. It is probably using the default
key for a local testnet:

cleos wallet import 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
cleos create account ...

Paul Calabrese

**Comment by serganus** [comment]
@PaulCalabrese Thanks. Solved!
