### ISSUE TITLE
Account have sufficient balance, but can't buy ram or delegatebw cpu

### ISSUE THREAD

**Issue by itleaks** [EOSIO/eos#4297]
Currently, many accounts created by 3rd party have no ram and cpu resource. So "buy ram" action will fail due to lack cpu bandwidth, also "delegatebw cpu" action will fail due to lack ram resource even though the account has sufficient balance. Then, these accounts can't do anything due to lack ram or cpu resource. 
    So, I propose to add a subcommand for cleos to pack  "buy ram" action and "delegatebw cpu" action in one transaction to fix above issue. However, in this case, system only allows 3000us  cpu bandwidth(leeway) to execute one transaction ,  while the two actions usually  cost 4000+ us. So system will throw below exception .
       "Error 3081001: transaction reached the deadline set due to leeway on account CPU limits"
  Therefore, EOS should make default leeway value large enough(may 6000us)  to execute "buy ram" action and "delegatebw cpu" action in one transaction.

**Comment by itleaks** [comment]
<img width="666" alt="931fabab-f290-4f94-bd3f-56f9049a057b" src="https://user-images.githubusercontent.com/7782367/41805670-69bf437e-76e1-11e8-9fe0-91a8a3fe080c.png">
<img width="1066" alt="1cb21964-c3b8-496a-8aec-9a70620312b9" src="https://user-images.githubusercontent.com/7782367/41805681-861e5ad2-76e1-11e8-881c-b1da0abe20cb.png">
<img width="1059" alt="4ac224b7-eb80-4343-a646-ce951c0b74fa" src="https://user-images.githubusercontent.com/7782367/41805706-c99fea32-76e1-11e8-9563-b0f2a5937ef9.png">
<img width="769" alt="1ef1726c-c5af-4925-aaaa-bcaefeee2024" src="https://user-images.githubusercontent.com/7782367/41805708-cdd28588-76e1-11e8-967b-c50dbdf3393c.png">

**Comment by noprom** [comment]
Hi @itleaks , try to let another account buyram for `testtest1233`

**Comment by itleaks** [comment]
@noprom Thanks, your suggestion is one solution to solve this problem. But it's not easy to find another account currently. And I think eos should provide this basic ability.

**Comment by boriskozak** [comment]
Yeah this is a big issue.   These accounts are effectively stuck and can't do anything.  Really poor design choice to not let accounts delegate bandwidth to themselves, because there is not enough bandwidth available to perform the actions.

**Comment by taokayan** [comment]
I think it's better to enhance cleos to support "delegatebw" with "buyram" in one transaction.

**Comment by taokayan** [comment]
Please follow the pull request https://github.com/EOSIO/eos/pull/4635

**Comment by spartucus** [comment]
What if the account doesn't have enough cpu and net for now? how to save itself?

**Comment by taokayan** [comment]
The workable solution is to execute "delegatebw" and "buyram" inside a single transaction, this is implemented in #4635 as enhancement. For now you need to ask somebody to stake net/cpu for you.

**Comment by taokayan** [comment]
This should be fin even if you don't have stakes for cpu/net, as final validation will use the new cpu/net stake values.

**Comment by spartucus** [comment]
Got it, thanks for reply.

**Comment by taokayan** [comment]
This is fixed. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
