### ISSUE TITLE
BP claimrewards vpay bug

### ISSUE THREAD

**Issue by abitmore** [EOSIO/eos#4300]
This is re-post of comments in #3014 in order to gain more attraction.

@abourget commented here: https://github.com/EOSIO/eos/issues/3014#issuecomment-397741614

>Imagine this scenario:
>1. Lets assume 3 BPs for simplicity.
>2. Each 3 BP have 33% vote weight, during 4 days (within vote decay boundaries - Saturday 0:00:00 UTC)
>3. They each produce the same number of blocks during that period.
>4. The inflation goes to the respective accounts and is ready to be claimed.
>5. On day 4, BP1 raises to 50% of votes. It claimrewards, the vpay is adjusted according to the current vote weight, he gets his pay accordingly.
>6. A few minutes later, BP2 raises to 50% of votes, BP1 gets back to some lower position. It claimrewards, the vpay is adjusted to the current vote weight. He now takes the rest of the 50% of the vpay.
>7. A few minutes later, BP3 wants to claimrewards. The vpay pot is empty, no matter how much % of votes he has..

@zorba80 commented here: https://github.com/EOSIO/eos/issues/3014#issuecomment-397759983

>A producer gets their share of vpay at the claim time :
>
>1. When BP1 claimrewards, inflation amount is issued and a fraction of that goes to vpay. Assume vpay is now 500.0000 EOS. BP1 gets 250.0000 EOS out of that. vpay is now 250.0000 EOS.
>
>2. BP2 claimrewards shortly after that, inflation is negligible. Their share is 50% of the current vpay, they get 125.0000 EOS. vpay pot is now 125.0000 EOS.
>
>3. BP2 claimrewards, they get their share of the remaining 125.0000 EOS.
>
>If a producer's share of vpay is less that 100 tokens, they get zero.

**Comment by andriantolie** [comment]
Thanks for the post, this issue is noted and I believe we have fix candidate.
