### ISSUE TITLE
Error 3090004: missing required authority

### ISSUE THREAD

**Issue by lingyiliu016** [EOSIO/eos#4302]
I developed a smart contract, deployed it on blockchain, and when I push action .error occured!
command line:
`cleos push action market.acnt trade '["11","11","5.5000 EOS","gs.acnt","cly.acnt","我要买"]' -p cly.acnt -p gs.acnt`
Error message throwed from cleos. 
<img width="1150" alt="20180623174429" src="https://user-images.githubusercontent.com/27277897/41808235-24a5c480-770d-11e8-9a30-bace77233be2.png">
Error message throwed from nodeos
<img width="1171" alt="20180623174548" src="https://user-images.githubusercontent.com/27277897/41808326-4928885a-770e-11e8-9ca2-f8d9341222db.png">
I haved added` -p cly.acnt ` to the command line, but cleos still reported error that miss require authory. I think that  the error may be caused by my smart contract,.But I don't know how to solve it by modifying the contract!
help me ,please!
thank you, very much!

**Comment by lingyiliu016** [comment]
Here is part of my smart contract.
<img width="906" alt="20180623175520" src="https://user-images.githubusercontent.com/27277897/41808349-9e197054-770e-11e8-8cc6-9554d7abdd50.png">
The first box is the name of the action, the second box is the program that invokes other contract actions,This is my focus of suspicion. but I don't know how to modify it.

**Comment by cppfuns** [comment]
你可以先试试把 trade 内的代码都注释掉，只打印出 输入的信息。

**Comment by andriantolie** [comment]
You are making an inline action on behalf of other users inside your smart contract, so the seller and buyer need to authorize your smart contract first before you can do it.

In the above case the seller is "gs.acnt" and the buyer is "cly.acnt", so "gs.acnt" need to do the following:
```
cleos set account permission gs.acnt active '{"keys":[{"key":"PUT_gs.acnt_ACTIVE_PERMISSION_KEY_HERE", "weight":1}], "threshold": 1, "accounts":[{"permission":{"actor":"market.acnt","permission":"eosio.code"},"weight":1}], "waits":[] }' owner -p gs.acnt
```
While "cly.acnt" needs to do the following:
```
```
cleos set account permission cly.acnt active '{"keys":[{"key":"PUT_cly.acnt_ACTIVE_PERMISSION_KEY_HERE", "weight":1}], "threshold": 1, "accounts":[{"permission":{"actor":"market.acnt","permission":"eosio.code"},"weight":1}], "waits":[] }' owner -p cly.acnt
```
```

**Comment by lingyiliu016** [comment]
Your answer is almost correct, but is wrong.Your answer is the solution to the problem that "transaction declares authority , but does not have signature for it under a private delay of 0 ms".
finally I found the reason. the cause of problem is that exchange action need seller and buyer signature, but program deliver seller signature.
