### ISSUE TITLE
esoc output message incomplete for unauthorized transactions

### ISSUE THREAD

**Issue by pavybez** [EOSIO/eos#431]
When you execute command 

./eosc push message hello transfer '{"from":"initb","to":"inita","amount":50}' --scope hello

The expected output should be:

  1881603ms thread-0   main.cpp:797                  operator()           ] Converting argument to binary...
548  1881630ms thread-0   main.cpp:851                  main                 ] Failed with error: 10 assert_exception: Assert Exception
549  status_code == 200: Error
550  : 3030001 tx_missing_auth: missing required authority
551  Transaction is missing required authorization from initb
552      {"acct":"initb"}
553          thread-0  message_handling_contexts.cpp:19 require_authorization

But the actual output is non descriptive and is as follows:

3078965ms thread-0   main.cpp:841                  operator()           ] Converting argument to binary...
An error occurred while submitting the transaction for this command!

**Comment by wanderingbort** [comment]
This was changed with my pretty printing of errors.  That one is not handled yet.  I will add it.  Until then you can use the new `-v` or `--verbose` flag to `eosc` to restore the old messges:

eg: `./eosc -v push message hello transfer '{"from":"initb","to":"inita","amount":50}' --scope hello`
