### ISSUE TITLE
can do Cross chain transaction ？

### ISSUE THREAD

**Issue by xtuyaowu** [EOSIO/eos#4314]
is eos can do Cross chain transaction? for example ,transaction eth,bitcoin on eos chain,
thanks！！

**Comment by jgiszczak** [comment]
EOS.IO can do cross chain transactions if the other chain is capable of validating EOS.IO merkle proofs.  In theory a contract in Ethereum might be capable.  Bitcoin can not.

See [this paper](https://steemit.com/eos/@dan/inter-blockchain-communication-via-merkle-proofs-with-eos-io) for details.
