### ISSUE TITLE
When patching nodeos binaries the version number needs to change

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#4315]
Last week the nodeos software version 1.0.5 was patched due to some issue.  This was discussed between the top 21 BPs and B1.   However, during that process the version number was not changed (as reported in "get info").  It is hard to confirm which nodes have applied the patch and which ones not.

Suggest that all future patches modify the version number in some way. (eg 1.0.5.1)

**Comment by matthewdarwin** [comment]
I'm trying to report on what versions people have.  Current situation is difficult. https://validate.eosnation.io/report-versions.txt

**Comment by njappboy** [comment]
@matthewdarwin current situation only allows commit hash resolution. 

My current environment is running the latest docker hub `eosio/eos` image and `v1/chain/get_info` api properly returns the `server_version`

```json 
{
   "server_version": "79651199",
   ...
}
```
i.e. v1.0.6 tag [commit hash 79651199](https://github.com/EOSIO/eos/commit/79651199)
i.e. v1.0.5 tag [commit hash c9b7a247](https://github.com/EOSIO/eos/commit/c9b7a247)
i.e. v1.0.5 (c9b7a247 parent) plus BP constitution [commit hash db031363](https://github.com/EOSIO/eos/commit/db031363)

**Comment by jgiszczak** [comment]
Provided with #5005 released in v1.2.0.

**Comment by matthewdarwin** [comment]
I know the current situation allows a commit hash.  I am suggesting this way of doing things is insufficient and an additional manually updated field should be available.  The field is only updated when a patch is created.  so then "git apply patchfilename ..." will update it.
