### ISSUE TITLE
about bp node

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#4317]
Apply to be a bp node. What are the officially recommended memory, bandwidth, and network requirements?And the hard drive, thank you

**Comment by testcode77** [comment]
EOSeoul Spec

● Type : Cloud(AWS)
● Location : Seoul AWS region
● Machine : m4.2xlarge instance
● Number : 1
● Memory : 32GB
● CPU : vCPU 8 Core
● Storage : SSD 300GB
● Network
○ uplink capacity : 1G High Shared Network
○ VM interface bandwidth : 1G High Shared Network
● Monthly Bill : USD $457

**Comment by testcode77** [comment]
live service.

● Location : Seoul AWS region
● Machine : m5.12xlarge (up to x1.32xlarge)
● Number : 1
● Memory : 192GB (up to 2TB)
● CPU : vCPU 48 Cores (up to 128 Cores)
● Storage : SSD 2TB * 2EA(NVME) + EBS 16TB (Provisioned IOPS 20000)
● Network : 10 Gbps (up to 25 Gbps)
● Monthly Bill : USD $2,800 (up to $19,361)
● Type : Cloud(AWS)

**Comment by jgiszczak** [comment]
Thanks to EOSeoul for sharing detailed technical specifications.

Block producer candidates should join the block producer Telegram channel and use whatever other venues that channel recommends.  This forum is for managing defects in the software itself.
