### ISSUE TITLE
"elapsed" is varying in time

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#4319]
I noticed this while testing my watchdog script https://github.com/cc32d9/eosaccwatch 

I'm pulling last 20 transactions for an account every 5 minutes, and sending an alert if anything has changed. But in the recent few hours, it appears that "elapsed" field is varying:
```
         "console" : "",
          "cpu_usage" : 0,
-         "elapsed" : 8,
+         "elapsed" : 5,
          "inline_traces" : [],
          "receipt" : {
             "abi_sequence" : 1,
@@ -76,7 +76,7 @@
          },
          "console" : "",
          "cpu_usage" : 0,
-         "elapsed" : 231,
+         "elapsed" : 229,
          "inline_traces" : [],
          "receipt" : {
             "abi_sequence" : 5,
@@ -131,7 +131,7 @@
          },
          "console" : "",
          "cpu_usage" : 0,
-         "elapsed" : 231,
+         "elapsed" : 219,
          "inline_traces" : [],
          "receipt" : {
             "abi_sequence" : 5,
```

Isn't it a value that is already part of transaction data in the block? It should be invariable in this case.

**Comment by andriantolie** [comment]
Is it always varying every 5 minutes? Or does it just vary on the second time you query it?

**Comment by cc32d9** [comment]
it was stable for about a day, and then varied several times during 3 hours.

**Comment by taokayan** [comment]
This depends on BP's machines and it is subjective. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
