### ISSUE TITLE
permission weight is reset to zero after 65535

### ISSUE THREAD

**Issue by PayGateV5** [EOSIO/eos#4320]
I think this will cause privilege escalation problem

[script I run]
cleos set account permission eospaycontrl active '{"threshold":65536,"keys":[],"accounts":[{"permission":{"actor":"eospay1admin","permission":"active"},"weight":65537},{"permission":{"actor":"eospay2admin","permission":"active"},"weight":65536},{"permission":{"actor":"eospay3admin","permission":"active"},"weight":65535}],"waits":[]}' owner -p eospaycontrl@active

[expected result]
assertion error

or

cleos get account eospaycontrl
permissions: 
     owner     1:    1 EOS5izi76yQFZ4ae8TMhCRYhcyUNdfGB87Xj1q3RXG22BZuKfUHZc
        active 65536:    65535 eospay1admin@active, 65536 eospay2admin@active, 65537 eospay3admin@active, 
memory: 
     quota:     127.4 KiB    used:     2.971 KiB  

[actual result]
cleos get account eospaycontrl
permissions: 
     owner     1:    1 EOS5izi76yQFZ4ae8TMhCRYhcyUNdfGB87Xj1q3RXG22BZuKfUHZc
        active 65536:    65535 eospay1admin@active, 0 eospay2admin@active, 1 eospay3admin@active, f

——————-

max weight of permission is 1 ~ 2^16 : 1 ~ 65536
when the weight is 65536, it became 0

big impact on multisig account control

**Comment by swatanabe-b1** [comment]
This cannot cause privilege escalation, because it can only reduce the weights.  The threshold is 32 bits, so wrap-around for it is a lot less likely.

**Comment by PayGateV5** [comment]
technically no privilege escalation.
but in real world, I can be used for fraud which will cause privilege escalation.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
