### ISSUE TITLE
cleos "-c,--contract TEXT" option is ignored

### ISSUE THREAD

**Issue by oviwankenobi** [EOSIO/eos#4322]
hi, I used the eosio.token contract and created my own eosairdroper.token contract, pretty much using the same code, I have installed it to account eosairdroper;

I managed to create MYT token and then issue MYT token to eosairdroper account, and other accounts as well; so far so good.

but I fail to transfer MYT token from one account the another, I get bellow error message althouth I am setting the contract that manages MYT token:

eos@eosro1:~/testnet0$ cleos transfer -c eosairdroper.token sourceaccount destaccount "10.0000 MYT" "first MYT transfer"

2679346ms thread-0   main.cpp:2712                 main                 ] Failed with error: unspecified (0)
Symbol MYT is not supported by token contract eosio.token

I have tried also **-c eosairdroper** instead of **-c eosairdroper.token**, still same result
eos@eosro1:~/testnet0$ cleos transfer -c eosairdroper sourceaccount destaccount "10.0000 MYT" "first MYT transfer"

can you pls advise what am I doing wrong?
thank you

**Comment by oviwankenobi** [comment]
this command worked fine

cleos push action eosairdroper transfer '[ "sourceaccount", "destinationaccount", "1000.0000 MYT", "transfer test" ]' -p sourceaccount

**Comment by heifner** [comment]
Resolved by #4931
