### ISSUE TITLE
max supply in eosio token contract

### ISSUE THREAD

**Issue by featheryus** [EOSIO/eos#4325]
I have a question about the max_supply when create token SYS. for example, we give 1 billion to the max supply.
when the supply reach to the max supply, how to issue more for rewards of producer.
It will assert failure as "quantity exceeds available supply"
As I know, EOS issue 5% more token every year.
Thanks.

**Comment by dacom-dark-sun** [comment]
Same question. What is predicted behavior?

**Comment by dacom-dark-sun** [comment]
Just test it and have answer: 
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: quantity exceeds available supply

Question is, how to burn tokens, or this is not available?

**Comment by ChristianDunst** [comment]
The current system contract "eosio.token" cannot change the max supply and it cannot burn tokens.
If you need.

You can either inherit from the system contract and add the missing functionality or write your own contract in order to achieve the functionality that you desire.
