### ISSUE TITLE
what is the right way to do inline transferring?

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#4326]
I want to transfer money from contract account to other's account. what is the right way to do it? I found inline action sender always cause error message. 

>Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations                                                                         
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.

I know that sign for my contract can't pass authority check of transfer action. How to do it properly?

**Comment by andriantolie** [comment]
You need to authorize your contract's eosio.code permission to your contract's active permission, e.g.
```
cleos set account permission dice active '{"threshold": 1, "keys":[{"key":"DICE_ACCOUNT_ACTIVE_KEY", "weight":1}], "accounts":[{"permission":{"actor":"dice","permission":"eosio.code"},"weight":1}], "waits":[] }' owner -p dice
```

**Comment by breadbread1984** [comment]
is eosio.code a customized authority beside owner and active? where does it defined?

**Comment by andriantolie** [comment]
It's a special keyword. You can find the definition in https://github.com/EOSIO/eos/blob/master/libraries/chain/include/eosio/chain/config.hpp and it's being used by the authority checker.

**Comment by breadbread1984** [comment]
ok thx

**Comment by breadbread1984** [comment]
@andriantolie I tried your method on a very simple contract but still can't transfer successfully. I paste my code FYI.

test.hpp
```c++
#ifndef TEST_HPP
#define TEST_HPP

#include <eosiolib/asset.hpp>
#include <eosiolib/eosio.hpp>

using namespace eosio;

class test: public contract {
public:
    //@abi action
    test(account_name _self): contract(_self) {}
    void func();
};
#endif
```
test.cpp

```c++
#include "test.hpp"

void test::func() {
    require_auth(_self);
    action(
        permission_level {_self,N(active)},
        N(eosio.token),N(transfer),
        std::make_tuple(_self,N(eosio.token),asset(1,N(SYS)),"")
    ).send();
}

EOSIO_ABI(test,(func))
```

**Comment by andriantolie** [comment]
What's the error that you got?

Also, I notice that you use a custom asset that's different from the system asset, i.e., `asset(1,N(SYS))` instead of `asset(4,N(SYS))` (system token has 4 precision). Is this intentional?

**Comment by breadbread1984** [comment]
I don't know the right way to initialize an asset object. what shall I do to make a 1.0000 SYS asset?

**Comment by breadbread1984** [comment]
I paste the error message above.

**Comment by andriantolie** [comment]
Ah sorry, I misread the constructor. It's actually `explicit asset( int64_t a = 0, symbol_type s = CORE_SYMBOL )`

So, if you want to construct 1.0000 SYS asset, you define it as `asset(10000, symbol_type(S(4, SYS))` or you can neglect the second parameter since it will default to CORE_SYMBOL (i.e. `asset(10000)` is enough)

**Comment by andriantolie** [comment]
You will need to start your nodeos with `--verbose-http-errors` option to make your error message more meaningful :)

**Comment by breadbread1984** [comment]
ok i will try it

**Comment by breadbread1984** [comment]
@andriantolie the error message is 

>Error 3050003: eosio_assert_message assertion failure                                                                                                                 Error Details:                                                                                                                                                        assertion failure with message: read

**Comment by andriantolie** [comment]
Hmm, did you try with the updated asset I mentioned before?

**Comment by breadbread1984** [comment]
yeah, buy I actually debug with a token with four alphabets. is the one you provided Ok?

**Comment by andriantolie** [comment]
You can just modify the precision and symbol name inside S(4, SYS) to your token precision and symbol name

**Comment by breadbread1984** [comment]
finally, it works. I get some typos in my code. thx

**Comment by breakstring** [comment]
I'm also blocked during the permission set up.
Your account name and contract name are both "test"? Will you please share your last authority commands? Thank you.

**Comment by breadbread1984** [comment]
you need to use your test's public key to replace mine in the command.

**Comment by breakstring** [comment]
Yes, I'm using my test account(betbetbetbet) public key, and also rebuild my contract to rename it as same name.....looks the permission already added (found the betbetbetbet@eosio.code in active section by cleos get account betbetbetbet, you can find this account in jungle test network). 
But still got the "Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations" error.......Maybe I should setup a nodeos to debug it :(
