### ISSUE TITLE
How can I trigger a smart contract action when recieved a token transfer

### ISSUE THREAD

**Issue by breakstring** [EOSIO/eos#4328]
I have an account which have a smart contract.
Any way to trigger an action in the smart contract once this account received a token transfer?

**Comment by andriantolie** [comment]
Inside the contract apply function, you need to filter condition where code is eosio.token and action is transfer. You won't be able to use EOSIO_ABI in this case as you use your own custom apply function.

**Comment by breakstring** [comment]
Thank you, find a solution at https://eosio.stackexchange.com/questions/421/how-to-do-something-when-your-contract-is-an-action-notification-recipient-like
