### ISSUE TITLE
How to keep the order of the trx

### ISSUE THREAD

**Issue by vaneyli** [EOSIO/eos#4329]
Two questions:
1:    how to keep the order of the trx.   When trx1 must run before trx2。 
2:    how to avoid the infinite loop in the wasm?  the vm would detect it?

thanks.

**Comment by jgiszczak** [comment]
Outside of a contract, the only way to ensure transaction ordering is to issue the first, poll the chain until the transaction is executed, then issue the second, bearing in mind that the first may expire before executing and require reissuance, possibly multiple times before success.

The chain does terminate infinite loops.  CPU stake gets exhausted quickly in that case, so developers have incentive to avoid writing them.

**Comment by vaneyli** [comment]
@jgiszczak  I found the total cpu is calculated just after the end of the trx.   If the trx never ends, where to calculate the cpu.     Is there  a timer?  or  each step of database operation in contract would call the cpu caculation?  I can't find the code.  thanks.

**Comment by jgiszczak** [comment]
The transaction code is injected with calls to a `checktime()` function which throws an exception if the various time limits are exceeded at the time of the call.  See [transaction_context](https://github.com/EOSIO/eos/blob/90fefdd12a4797e47890910f11dd7b60f1435ed4/libraries/chain/transaction_context.cpp#L283) and [wasm_binary_injection](https://github.com/EOSIO/eos/blob/90fefdd12a4797e47890910f11dd7b60f1435ed4/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp#L780) for details.
