### ISSUE TITLE
The tutorial/vios-boot-tutorial can't be used with the latest eosio

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#4330]
I just updated eosio. I launched a testnet with

> python3 bios-boot-tutorial.py -a --user-limit 10 --producer-limit 4 --num-producers-vote 2

It works fine before. Now it stuck at creating 9/14 account. Please update bios-boot-tutorial.py. I debug my contract with this helpful tool. I find another tool called eosio-launcher. Is it a testnet lauching tool  as well? Where can I find a tutorial on how to use it?

**Comment by jgiszczak** [comment]
bios-boot-tutorial.py was last updated 21 Aug 2018, correcting the previous deficiencies.  If there are new problems, please file a new issue.
