### ISSUE TITLE
Why I have got this "failed to connect to nodeos at xxxxxxxxx;is nodeos running? "  frequently

### ISSUE THREAD

**Issue by JadeGhost** [EOSIO/eos#4331]
I was using the docker command line to connect the mainnet。but I have got this error shown in below!
failed to connect to nodeos at xxxxxxxxx;is nodeos running?
Its seems like net unstable ,sometimes connection is good to use! but sometime it has been disconnected!
Anyone got this as well?
![error](https://user-images.githubusercontent.com/39815686/41903417-6ccef756-7968-11e8-999a-cd83c398637a.png)

**Comment by jgiszczak** [comment]
Try using another node.

Accessibility of mainnet nodes is outside the control of block.one.  This forum is for issues in the software itself.

**Comment by KennyLiu25775** [comment]
@JadeGhost  hey were you able to solve the issue?
