### ISSUE TITLE
about get_block 

### ISSUE THREAD

**Issue by LeeGG** [EOSIO/eos#4333]
when i use cURL get_block 
![image](https://user-images.githubusercontent.com/22726673/41907228-c9f03954-7972-11e8-8809-58ee0abd27e7.png)
response format:
![image](https://user-images.githubusercontent.com/22726673/41907263-eb4afef4-7972-11e8-92e6-1400fc1360ea.png)
what is the problem

**Comment by LeeGG** [comment]
![image](https://user-images.githubusercontent.com/22726673/41907423-62b4b39a-7973-11e8-9d74-13e5a98fb74e.png)
local eenviroment 
 block out  looks like no problem

**Comment by jgiszczak** [comment]
You must specify a block ID in a properly formatted JSON block and pass it to cURL with the `-d` or `--data` argument. See https://eosio.github.io/eos/group__eosiorpc.html#v1chaingetblock for example usage.  Note that not all documentation on that page may be up to date.  I have verified only `get_block`.
