### ISSUE TITLE
Warning for eosiocpp missing contract

### ISSUE THREAD

**Issue by kesar** [EOSIO/eos#4334]
eosiocpp -g aegis.abi aegis.cpp

878702ms thread-0   abi_generator.hpp:68          ricardian_contracts  ] Warning, no ricardian clauses found for 

         ricardian_contracts() = default;
         ricardian_contracts( const string& context, const string& contract, const vector<string>& actions ) {
            ifstream clauses_file( context+"/"+contract+"_rc.md");
            if ( !clauses_file.good() )
               wlog("Warning, no ricardian clauses found for ${con}\n", ("con", contract));

**Comment by akildemir** [comment]
how did you solve the issue? I am getting the same error

**Comment by halsaphi** [comment]
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
Smart contracts should now be built using eosio.cdt.
