### ISSUE TITLE
Prefix architecture for launch separate network

### ISSUE THREAD

**Issue by dacom-dark-sun** [EOSIO/eos#4335]
Hello crypto-gods ;)
If we launch separate public network for project, we are need to change key-prefix. If we simple replace EOS to another prefix, test are failed. Question is about compatibility, what better way for launch separate network - we need fix the tests, or we need to wait next release, where this opportunity will implemented? 

By this reference [https://github.com/EOSIO/eos/issues/2146](url) i see that some changes will about it, but what design is planning for launch easily compatible separate public network? Should we just change prefix and fix tests, or this way is wrong for the future time?

**Comment by jgiszczak** [comment]
Fixing the tests to match the change is appropriate.  At present there are no plans to make changes to facilitate launching compatible separate public networks.
