### ISSUE TITLE
Cannot NULL permission

### ISSUE THREAD

**Issue by ankh2054** [EOSIO/eos#4336]
Trying to NULL a permission attached to an account and getting action exception.

```
./cleos.sh get account eos42freedom
permissions: 
     owner     1:    1 EOS8QoCJ5TcopvKTVW5trtRKeynK5KCdTJiwwcFfdn8FVWxrfnhnN
        active     1:    1 EOS5rgA6SenKsWJysTRwS6nek8uHbT7PjsDMY76sZkHEW74Htnc5p
           claim     1:    1 EOS8WLaXgcZdctUr8DAErtgp5g9qp6PZQxDRHybUer4L4U9m6BCMt
```

```
./cleos.sh set account permission eos42freedom claim NULL
Error 3050000: action exception
```

**Comment by andriantolie** [comment]
Can you start your nodeos with --verbose-http-errors option and paste the result of running the above command here?

**Comment by ankh2054** [comment]
```
./cleos.sh set action permission eos42freedom eosio claimrewards NULL 
executed transaction: f07ad3c329ddef7269142768a35e53656cf28682d7c6b23db83e4fc17596407a  120 bytes  1142 us
#         eosio <= eosio::unlinkauth            {"account":"eos42freedom","code":"eosio","type":"claimrewards"}
warning: transaction executed locally, but may not be confirmed by the network yet
```

**I double checked the authority link was  unlinked.**
```
./cleos.sh set action permission eos42freedom eosio claimrewards NULL 
Error 3040000: transaction exception
Ensure that your transaction satisfy the contract's constraint!
Error Details:
cannot unlink non-existent permission link of account 'eos42freedom' for actions matching 'eosio::claimrewards'
```
```
./cleos.sh set account permission eos42freedom claim NULL
Error 3050000: action exception
Error Details:
Cannot delete a linked authority. Unlink the authority first
```

**Comment by EOSBeijing** [comment]
We once had the same issue. I checked your transaction, you once set linked to a wrong action:

72d4e5d604f529c8ef188e6f1904dc0f03c356d912051f648daadc908bacc2f1
account: eos42freedom, code: eosio, type: claimrewar, requirement: claim

Once we unlined the wrong action, we could delete the permission.

But we have a new problem now. We cannot claim rewards when we set a new permission and I don't know why.

**Comment by ankh2054** [comment]
thanks very useful :). Many people are having the same issue & some it does work, but still uses the active permission.

**Comment by EOSBeijing** [comment]
@ankh2054 Will you create the claim permission again? If so, please let me know if you can claim rewards by that permission successfully. Thank you.

**Comment by ankh2054** [comment]
I’ve tried again but still not working for me, always uses the active permission. Not sure why.

**Comment by eosauthority** [comment]
cleos push action eosio claimrewards '{"owner":"BP-ACCOUNT"}' -p BP-ACCOUNT@claimer

this works and the claimer permission is able to claim correctly. #4379
