### ISSUE TITLE
6 tests failed

### ISSUE THREAD

**Issue by JustinZal** [EOSIO/eos#4342]
Hello, I have completed full installation,  but 6 tests still aren't passing. Is it critical? Will I be able to functionally work with EOS, interact with blockchain and deploy smart contracts? What can I do to fix these errors?

`The following tests FAILED:
	 30 - nodeos_run_test (Failed)
	 32 - distributed-transactions-test (Failed)
	 33 - restart-scenarios-test-resync (Failed)
	 34 - restart-scenarios-test-hard_replay (Failed)
	 35 - restart-scenarios-test-none (Failed)
	 36 - validate_dirty_db_test (Failed)
Errors while running CTest
make: *** [test] Error 8`

OS: macOS High Sierra V 10.13.5

**Comment by lazaridiscom** [comment]
@JustinZal , have you solved this? Just update to 1.1.3, and you should be fine.

**Comment by JustinZal** [comment]
Yes, I have resolved it. Thanks for the answer
