### ISSUE TITLE
Generating helper functions that serialize/deserialize types in ABI spec

### ISSUE THREAD

**Issue by kkurian** [EOSIO/eos#4347]
According to the [soon-to-be-deprecated documentation](https://github.com/EOSIO/eos/wiki/Programs-&-Tools#eosiocpp),  "eosiocpp can also be used to generate helper functions that serialize/deserialize the types defined in the ABI spec."

The example provided is:
```
➜ eosiocpp -g abi.json -gs types.hpp
Generated abi.json ...
Generated types.gen.hpp ...
```

However, as of v1.0.7 eosiocpp does not recognize the `-gs` option. v1.0.1 did not recognize it either.

The new [developer portal](https://developers.eos.io/) makes no mention of this option that I can find, and does not appear to discuss generation of these helper functions.

Was this feature ever supported? Will it be? Where is it now?

**Comment by andriantolie** [comment]
I don't think we need the `.gen.hpp` file generated with `-gs` option anymore, our eosiolib/datastream.hpp and eosiolib/serialize.hpp has been updated to support most of the serialization/ deserialization need.
