### ISSUE TITLE
I need to transfer token in a smart contract so which permission should I need?

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#4348]
transaction declares authority '{"actor":"user1","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [{"actor":"fifa","permission":"eosio.code"}], and provided keys []
    {"auth":{"actor":"user1","permission":"active"},"provided_delay":0,"provided_permissions":[{"actor":"fifa","permission":"eosio.code"}],"provided_keys":[],"delay_max_limit_ms":3888000000}
    thread-0  authorization_manager.cpp:409 check_authorization

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:62 exec_one

Here is my operate: 

cleos --wallet-url "http://127.0.0.1:8888" push action fifa newteam ./team1.json -p user1

**Comment by andriantolie** [comment]
Can you share your action handler for newteam?

**Comment by yankunsam** [comment]
// @abi action newteam
  void newteam(const account_name owner,const account_name banker,uint64_t scoresum,asset cost,const asset& stake,const uint8_t gameid,const std::vector<uint32_t> players) {
    require_auth(owner);

    auto gameitr = gamelists.find(gameid);
    eosio_assert(gameitr != gamelists.end(),"unknown gameid");
    auto teamer = teams.emplace(_self,[&](auto& new_team){
      new_team.id = teams.available_primary_key();
      //new_team.id = 1;
      new_team.owner = owner;
      new_team.banker = banker;
      new_team.players = players;
      new_team.cost = cost;
      new_team.stake= stake;
      new_team.gameid = gameid;
      new_team.scoresum = scoresum;
    });

    action(
      permission_level{ owner, N(active) },
      N(eosio.token), N(transfer),
      std::make_tuple(owner,banker,stake,std::string(""))
    ).send();
  }

@andriantolie

**Comment by yankunsam** [comment]
@EugeneChung  Can you give me more details information?  which account to be privileged for the above code? "user1"?

**Comment by andriantolie** [comment]
You shouldn't need to set your contract to be privileged. In fact, only eosio, eosio.token, and eosio.msig should have privileged account status. 

For the above, user1 needs to authorize fifa@eosio.code to act on behalf of him. So user1 needs to execute the following command:
`cleos set account permission user1 active '{"threshold": 1, "keys":[{"key":"USER1_PUBLIC_ACTIVE_KEY", "weight":1}], "accounts":[{"permission":{"actor":"fifa","permission":"eosio.code"},"weight":1}], "waits":[] }' owner -p user1`

**Comment by EugeneChung** [comment]
So provided_permission : {{receiver, config::eosio_code_name}} means it. Thanks.

**Comment by andriantolie** [comment]
Yep

**Comment by yankunsam** [comment]
@andriantolie  @EugeneChung  It works. Thanks
