### ISSUE TITLE
Failed to connect to nodeos at http://nodeosd:8888; is nodeos running?

### ISSUE THREAD

**Issue by jaybkim1** [EOSIO/eos#4352]
I carefully followed the instructions from [Developers EOSIO](https://developers.eos.io/eosio-nodeos/docs/overview-1).

I successfully pulled the image from the repository `docker pull eosio/eos-dev` and started the eosio node.

$ sudo docker run --rm --name eosio -d -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev  /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console"

I went to the next steps accordingly until `Creating an Account` part on `Comprehensive Guide to Accounts & Wallets`

I had no problem restarting **keosd** and unlocked my default wallet using the command lines below.

$ pkill keosd
$ keosd --http-server-address-localhost:8899
$ cleos --wallet-url=http://localhost:889 wallet unlock

![screen shot 2018-06-27 at 11 18 45 am](https://user-images.githubusercontent.com/20435620/41950197-df51a638-79ff-11e8-9f4f-0942d704d889.png)

Then, I started **nodeos** by opening a new terminal window. 
$ nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin

Now, I could see the blocks are producing like an attached image below.

![screen shot 2018-06-27 at 11 48 57 am](https://user-images.githubusercontent.com/20435620/41950233-1a88531e-7a00-11e8-8c48-0c9623c220b0.png)

**Here comes an error while creating an account.**

$ cleos --wallet-url=http://localhost:8899 create account eosio testaccount ${public_key_1} ${public_key_2}

I entered the public keys for ${public_key_1} and ${public_key_2} that I generated from $ cleos create keys.

> Failed to connect to nodeos at http://nodeosd:8888; is nodeos running?

Anyone facing this problem? 

Any suggestions will be grateful!

**Comment by andriantolie** [comment]
It seems to me that you have the argument `-u http://nodeosd:8888` passed to your cleos. I guess it's inside your alias definition. If you are following the developer portal https://developers.eos.io/eosio-nodeos/docs/docker-quickstart, you won't need to have the `-u` argument inside your cleos alias

**Comment by jaybkim1** [comment]
@andriantolie 

Thank you for your feedback.

But, I feel a bit confused by what you meant by the `-u` argument. 

Are you referring to this below alias command from the developer portal?

`alias cleos='docker exec eosio /opt/eosio/bin/cleos --wallet-url http://localhost:8888'`

**Comment by andriantolie** [comment]
The fact that you got this error `Failed to connect to nodeos at http://nodeosd:8888; is nodeos running?` must be because your cleos alias is something like this
`alias cleos='docker-compose exec xxx /opt/eosio/bin/cleos -u http://nodeosd:8888 xxx'  instead of the above alias you mentioned. I guess you follow the docker-compose guide previously to set the alias, and mixed it up with the guide from developer portal website.

Try to call 
```
type cleos
```
to see your cleos alias definition

Just replace the old alias with the one you mentioned above and it should be fine :)

**Comment by andriantolie** [comment]
We haven't received any follow up from this. I recommend you to try with the latest version. 
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
