### ISSUE TITLE
When does EOS support multi thread?

### ISSUE THREAD

**Issue by xiliangMa** [EOSIO/eos#4357]
https://steemit.com/en/@eoseoul/bmt-eosio-tps-results-by-eoseoul 

Dawn 3.0 test results were only within 2000 of TPS. 
 
When does EOS support multi thread? 

Under the same conditions, how much can we raise when we open multi thread?

20000tps？

**Comment by xiliangMa** [comment]
No one cares about this problem?

**Comment by jgiszczak** [comment]
There are no plans to multithread `nodeos` in the near future.  At some point signature validation within a block may be multithreaded, but there is no timeline for this feature, if it happens at all.

The current plan is to achieve higher transaction rates via horizontal scaling using inter-blockchain communication (IBC).  See [this post](https://steemit.com/eos/@dan/inter-blockchain-communication-via-merkle-proofs-with-eos-io) for a design discussion.  Note that the final version may or may not adhere closely to that whitepaper.

**Comment by gleehokie** [comment]
A note for people who are reading this now, considerable multithreading has been added to EOSIO over the past few releases and will continue to be added where appropriate.  See the release notes.

**Comment by farhan-troon** [comment]
Multithreading is now being support for three main plugins i.e net_plugin, http_plugin and chain_plugin. Check the prospective config options to set the thread number.
