### ISSUE TITLE
Stop Mining Empty Blocks in Private Chain

### ISSUE THREAD

**Issue by mamidi1211** [EOSIO/eos#4358]
Is there any way to stop mining empty blocks in private chain

**Comment by andriantolie** [comment]
Why would you want to stop mining empty blocks? If you do that, your chain will be stale

**Comment by mamidi1211** [comment]
Producing empty blocks may increase the data size. Also it may increase the computation time of the transactions. 
Am i right ?

**Comment by jgiszczak** [comment]
Producing empty blocks does increase the size of the block log on disk.  However empty blocks are extremely small compared to the capacity of modern disks.  A desktop PC generating empty blocks is likely to experience a hardware failure before filling a 2TB disk with empty blocks.

Transaction computation time is totally unaffected by the size of the block chain.

**Comment by mamidi1211** [comment]
Thanks @jgiszczak . 
Is there any way to stop producing empty blocks. ?

**Comment by jgiszczak** [comment]
If you load `producer_api_plugin` in your nodeos config.ini, it makes available the URL `/v1/producer/pause`, which you may access via curl or similar tools.  `cleos` does not provide support for that API.  To resume, use the URL `/vi/producer/resume`.

**Comment by mamidi1211** [comment]
Thanks. It worked.

**Comment by yashvadhvani** [comment]
I know this issue is closed but can you give me more detailed explanation Please
