### ISSUE TITLE
synchronization is slow ?

### ISSUE THREAD

**Issue by yangyang9966** [EOSIO/eos#4359]
synchronization is slow ,120 blocks/min.Any idea? thanks！

**Comment by jgiszczak** [comment]
Synchronization speed varies dramatically depending on how many transactions are in a block.  The earliest parts of the chain include loading the genesis snapshot into the chain, producing a very large number of transactions per block.  Other parts of the chain can be synchronized much more quickly, as blocks are far smaller.  Benchmarking shows that signature verification is a significant burden on the synchronization time.  Possibilities are being considered to improve that, but the block per minute rate will always vary considerably depending on activity.
