### ISSUE TITLE
how can i get account balance info when developing smart contract

### ISSUE THREAD

**Issue by waterhkzhong** [EOSIO/eos#4360]
hi , how can i get account balance info when developing smart contract. I can't find any account api in EOSIOLIB

**Comment by andriantolie** [comment]
It's inside eosio.token accounts table

**Comment by waterhkzhong** [comment]
@andriantolie thanks, so i should send an action to eosio.token contract in order to get the balance? How can i get the return value after sended an action?

**Comment by andriantolie** [comment]
Nope, you don't need to send an action to eosio.token. The data is stored in the table of eosio.tokens, so you can just query it using multi index table.
Example:
```
#include "fill_the_path_to_eosio.token.hpp_here"
...
        eosio::token t(N(eosio.token));
        const auto sym_name = eosio::symbol_type(S(4,SYS)).name();
        const auto my_balance = t.get_balance(N(myaccount), sym_name );
        eosio::print("My balance is ", my_balance);
...
```

**Comment by waterhkzhong** [comment]
@andriantolie thanks.  : )

**Comment by raphaelgodro** [comment]
How can we do it using the new CDT compiler?

**Comment by FortisFortuna** [comment]
I found this to be helpful
https://github.com/EOSIO/eos/issues/3954#issuecomment-573394063
