### ISSUE TITLE
Can't see system account from producer nodes

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#4363]
I create testnet following the tutorial given on the wiki of eosio's github. I create 4 producer nodes (hosting at port 8001-8004). when I check out account info through cleos -u http://localhost:8001 get account eosio. I can see eosio account successfully. However, I can't see info of other system account eosio.* from producer nodes. I checked the connectivity through cleos -u http://localhost:8001 net peers. All 4 producers connect with genesis node well. what could be the problem?

**Comment by taokayan** [comment]
We haven't received any update for this. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
