### ISSUE TITLE
msig  contract  error

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#4364]
2214171ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 3090003 unsatisfied_authorization: provided keys, permissions, and delays do not satisfy declared authorizations
transaction declares authority '{"actor":"mymultisig11","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [{"actor":"eosio.msig","permission":"eosio.code"}], and provided keys []
    {"auth":{"actor":"mymultisig11","permission":"active"},"provided_delay":0,"provided_permissions":[{"actor":"eosio.msig","permission":"eosio.code"}],"provided_keys":[],"delay_max_limit_ms":3888000000}
    thread-0  authorization_manager.cpp:409 check_authorization

    {"fc::to_hex(data, data_len)":"27b3345b000000000000000000000100a6823403ea3055000000572d3ccdcd01100273d8e5a8a59700000000a8ed32323c100273d8e5a8a597104208e1aa99afa990d003000000000004535953000000001b50617920706172746e6572313131313120736f6d65206d6f6e657900"}
    thread-0  wasm_interface.cpp:1326 send_deferred

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:62 exec_one

The same reason to   https://github.com/EOSIO/eos/issues/4348 ?

**Comment by yankunsam** [comment]
Fixed.  All the signature account should hava "eosio.msig@eosio.code" permission now.

**Comment by ndcgundlach** [comment]
Indicated fixed by opener
