### ISSUE TITLE
Support a Read-Only operational mode for nodeos

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#4372]
During the review of #4291 it became clear that supporting `push_transaction` on a node that wanted to maintain a consistent read state would be more expensive than supporting `push_transaction` with the current default speculative mode of operation/reads.   As a result, it is prudent to offer a configuration option which puts an API into "read only" mode. 

This mode of operations will:
- not accept HTTP api requests for any variant of `push_transaction`
- not act as a relay for P2P transactions in either `net_plugin` or `bnet_plugin`
- never have a pending block state
- not support production of new blocks

Generally speaking, this node should be a read-only replica of the best chain state it is aware of and nothing more.  This would support either the "head" or "LIB" read-modes from #4196 but should consider "speculative" mode to be an invalid configuration.

**Comment by heifner** [comment]
Resolved by #5198
