### ISSUE TITLE
nodeos was killed. but restart takes too long time.

### ISSUE THREAD

**Issue by egonson** [EOSIO/eos#4376]
1. Why is nodeos killed so frequently?
2. Every time nodeos died, --replay-blockchain option should have been used.
Like bitcoin, is it impossible that only last few blocks needs to be replayed?
In case of steem, replaying is hell. EOS too in the future?
3. Sometimes, even --replay-blockchain option does not works. --hard-replay-blockchain is too.
then, I should have deleted all block data and restart from the very beginning.
It take too long time.
Is there something like checkpoint?

**Comment by jgiszczak** [comment]
If nodeos is shut down cleanly, it can be relaunched with no arguments at all (besides `--config-dir` or `--data-dir` if those were used) and it will resume where it left off.  If nodeos is not shutting down cleanly on your system, you are running up against a hardware limitation or your OS is misconfigured.  Nodeos is a stable, long-running process.  I myself have run it for weeks at a time without incident.

`--hard-replay` is a checkpoint type system, which will replay as much of the block log as is good, then switch to synchronization after it can no longer continue reading from the old log.  Replay time is limited by your hardware.
