### ISSUE TITLE
eos v1.0 cannot Build Multiple host multiple nodes？

### ISSUE THREAD

**Issue by LeeGG** [EOSIO/eos#4377]
developers docs only ‘Local Multi-Node Testnet‘

**Comment by jgiszczak** [comment]
You may have followed a stale link.  The current documentation for a local multi-node testnet is available at https://github.com/EOSIO/eos/wiki/Testnet-Single-Host-Multinode
You may also use `tutorials/bios-boot-tutorial/bios-boot-tutorial.py` in the repository to achieve the same result in an automated fashion.  See the accompanying README file for the briefest of introductions.  Use the `--help` argument for more detailed documentation of the command line.
