### ISSUE TITLE
Byzantine  is already in the codebase?

### ISSUE THREAD

**Issue by vaneyli** [EOSIO/eos#4380]
The whitepaper said : “Byzantine Fault Tolerance is added to traditional DPOS by allowing all producers to sign all blocks so long as no producer signs two blocks with the same timestamp or the same block height. Once 15 producers have signed a block the block is deemed irreversible. Any byzantine producer would have to generate cryptographic evidence of their treason by signing two blocks with the same timestamp or blockheight. Under this model a irreversible consensus should be reachable within 1 second.“
 
I would like to know whether is already realized in the latest code?   uint16_t                         confirmed = 1;  ??  thanks.

**Comment by jgiszczak** [comment]
Yes, this has been implemented.  See [#3088](https://github.com/EOSIO/eos/issues/3088) for details.
