### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by tamdinh** [EOSIO/eos#4381]
I've tried to build eos from source code and I get the error message below :
.......
[ 83%] Generating dice.abi.hpp [ 84%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/elliptic_secp256k1.cpp.o In file included from /Users/Tam/Projects/BlockChain/eos/libraries/fc/src/crypto/elliptic_impl_priv.cpp:5: /Users/Tam/Projects/BlockChain/eos/libraries/fc/src/crypto/_elliptic_impl_priv.hpp:11:7: error: unknown type name 'secp256k1_context_t'; did you mean 'secp256k1_context'? const secp256k1_context_t* _get_context(); ^~~~~~~~~~~~~~~~~~~ secp256k1_context /usr/local/include/secp256k1.h:43:41: note: 'secp256k1_context' declared here typedef struct secp256k1_context_struct secp256k1_context; ^ /Users/Tam/Projects/BlockChain/eos/libraries/fc/src/crypto/elliptic_impl_priv.cpp:52:5: error: unknown type name 'rivate_key'; did you mean 'private_key'? rivate_key private_key::regenerate( const fc::sha256& secret ) ^~~~~~~~~~ private_key /Users/Tam/Projects/BlockChain/eos/libraries/fc/include/fc/crypto/elliptic.hpp:93:11: note: 'private_key' declared here class private_key
........
I have tried build and install secp256k1 from bitcoin-core but it did not work. I wonder which version of secp256k1 is using. Does anybody have an idea?

**Comment by yankunsam** [comment]
On  Mac?  which tag for eos?

**Comment by yankunsam** [comment]
Delete the "build"  directory and rebuild by eosio_build.sh is good choice.

**Comment by tamdinh** [comment]
I have deleted the "build" directory and the error is still there.

**Comment by yankunsam** [comment]
How about checkout to v1.0.6. It works for me.

**Comment by tamdinh** [comment]
I have checked but it still does not work. I have built on another Mac Computer, it worked. So maybe my laptop environment have some problems, I think.

**Comment by tamdinh** [comment]
I follow https://www.jianshu.com/p/f26ee4cf1d4a and problem has been solved.
```
git clone https://github.com/cryptonomex/secp256k1-zkp.git
cd secp256k1-zkp
./autogen.sh
./configure
make
sudo make install
```

**Comment by onigirisan** [comment]
@tamdinh Many thanks, you saved my life.
