### ISSUE TITLE
push action eosio setprods。Invalid Action Arguments

### ISSUE THREAD

**Issue by LeeGG** [EOSIO/eos#4383]
eos v1.0.7
when i setup Local Multi-Node Testnet
i want inita registered as a producer with the bios node  like developers docs
![image](https://user-images.githubusercontent.com/22726673/42013639-d13c33f2-7ad0-11e8-8201-25ab1d0e3ea6.png)
paste out：
`[eoser@bigdata-08 cleos]$ ./cleos --wallet-url http://localhost:8899 push action eosio setprods "{ \"version\": 1, \"producers\": [{\"producer_name\": \"inita\",\"block_signing_key\": \"EOS7EyCgo1hvQymAdgy7yEacUCP26D75W278Q8bpQo64SbLBzX1wi\"}]}" -bpQo64SbLBzX1wi\"}]}" -p eosio@active
Error 3050002: Invalid Action Arguments
Ensure that your arguments follow the contract abi!
You can check the contract's abi by using 'cleos get code' command.`

**Comment by yankunsam** [comment]
You should check the eosio.bios.abi in <eos_source_code>/build/contract/eosio.bios/

**Comment by LeeGG** [comment]
@yankunsam  im not good at c.  
please have a look . 
this is . eosio.bios.abi   setprods
`{
      "name": "set_producers",
      "base": "",
      "fields": [
        {"name":"schedule",   "type":"producer_key[]"}
      ]
    }`
so  I should change json？or abi？
and how to change

**Comment by yankunsam** [comment]
```cat setprods.json

{
    "schedule": [
        {
             "producer_name": "xxx",
             "block_signing_key": "xxx"  
       },
      {
         "producer_name": "xxx",
         "block_signing_key": "xxx"  
      }
    ]

}
```

A json file is a better way.

**Comment by LeeGG** [comment]
@yankunsam   thanks! it works .   mua
