### ISSUE TITLE
Possible memory leak of net_plugin

### ISSUE THREAD

**Issue by EugeneChung** [EOSIO/eos#4388]
> plugins/net_plugin/net_plugin.cpp

    class dispatch_manager {
      vector<block_request> req_blks;
    }

    void dispatch_manager::recv_notice () {
        ...
        if (!b) {
            req_blks.push_back( {blkid, generated} );
        }
    )

I can't find any erase or clear call for dispatch_manager::req_blks vector of net_plugin.

**Comment by vjoke** [comment]
for (auto ref = req_trx.begin(); ref != req_trx.end(); ++ref) {
         if (*ref == id) {
            req_trx.erase(ref);
            break;
         }
      }

**Comment by taokayan** [comment]
This is a small bug. Since the number of blocks are relatively less (64 million blocks per year) and only consume 64M x 40 bytes = 2.5GB memory per year at the worst case. We'll fix it in the future.

**Comment by EugeneChung** [comment]
Found that it's fixed by https://github.com/EOSIO/eos/pull/4847/commits/78aa3d1bde73f19db8275297fd9053bea0d0c7c6
