### ISSUE TITLE
how to get total supply of ram? how to get the price of ram?

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#4393]
As we all know, some explorer has already monitor the price of ram.
I wonder that how to get the price of ram and the total aviliable amount of ram？

**Comment by Atidium** [comment]
Use https://www.eosrp.io

**Comment by guaiguaihw** [comment]
search ram total balance：
`cleos get table eosio eosio rammarket`
ram price / KB：
`quote.balance/base.balance`

**Comment by cppfuns** [comment]
https://www.bcskill.com/index.php/archives/353.html
