### ISSUE TITLE
registered as a producer

### ISSUE THREAD

**Issue by LeeGG** [EOSIO/eos#4396]
i want initb registered as a producer with the bios node like developers docs
when i execute：
`cleos --wallet-url http://localhost:8899 push action eosio setprods "{ \"version\": 1, \"schedule\": [{\"producer_name\":\"initb\",\"block_signing_key\":\"EOS7EyCgo1hvQymAdgy7yEacUCP26D75W278Q8bpQo64SbLBzX1wi\"}]}" -p eosio@active`
error：
![image](https://user-images.githubusercontent.com/22726673/42030366-29b90742-7b05-11e8-8cc1-e80fd0156ef8.png)

The strange thing is that I performed successfully once before

**Comment by jgiszczak** [comment]
Once you have loaded the eosio.system contract, setprods is no longer available.  You need to either use the voting mechanisms to elect initb, or reload the eosio.bios contract on the eosio account.  Note that if you dropped privileges for the eosio account, you would need to replace the eosio.system contract with eosio.bios via the producer voting mechanism.
