### ISSUE TITLE
cleos wallet import should support secure entry

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#4401]
# Description

`cleos wallet import` expects secret information on the command line.  This can mean that secret data is stored in logs and history files on the system in plaintext.   cleos should support a means of import that respects the sensitive nature of this data similar to the options we provide for password entry where the command line argument is optional and if not present uses terminal entry.

- [ ] private key data options for `cleos wallet import` should be optional
- [ ] terminal entry should not echo the data to the screen

**Comment by andriantolie** [comment]
This is merged
