### ISSUE TITLE
build eos failed on centos7

### ISSUE THREAD

**Issue by fry325** [EOSIO/eos#4405]
I use centos virtual machine on windows 10.

    `[root@localhost eos]# ./eosio_build.sh
    
        Beginning build version: 1.2
        2018年 06月 29日 星期五 00:28:16 UTC
        User: root
        git head id: 90fefdd12a4797e47890910f11dd7b60f1435ed4
        Current branch: HEAD
    
        ARCHITECTURE: Linux
    
        OS name: CentOS Linux
        OS Version: 7
        CPU speed: 2601Mhz
        CPU cores: 2
        Physical Memory: 3773 Mgb
        Disk install: /dev/sda3
        Disk space total: 47G
        Disk space available: 42G
    
        Checking Yum installation
        Yum installation found at /usr/bin/yum.
    
        Checking installation of Centos Software Collections Repository.
        Centos Software Collections Repository found.
    
    
        Enabling Centos devtoolset-7.
        Centos devtoolset-7 successfully enabled.
    
    
        Updating YUM repository.
    
    已加载插件：fastestmirror, langpacks
    Loading mirror speeds from cached hostfile
     * base: mirrors.aliyun.com
     * extras: mirrors.aliyun.com
     * updates: mirrors.aliyun.com
    正在解决依赖关系
    --> 正在检查事务
    ---> 软件包 kernel.x86_64.0.3.10.0-862.3.3.el7 将被 安装
    ---> 软件包 kernel-tools.x86_64.0.3.10.0-862.3.2.el7 将被 升级
    ---> 软件包 kernel-tools.x86_64.0.3.10.0-862.3.3.el7 将被 更新
    ---> 软件包 kernel-tools-libs.x86_64.0.3.10.0-862.3.2.el7 将被 升级
    ---> 软件包 kernel-tools-libs.x86_64.0.3.10.0-862.3.3.el7 将被 更新
    ---> 软件包 python-perf.x86_64.0.3.10.0-862.3.2.el7 将被 升级
    ---> 软件包 python-perf.x86_64.0.3.10.0-862.3.3.el7 将被 更新
    --> 解决依赖关系完成
    
    依赖关系解决
    
    =========================================================================================================
     Package                      架构              版本                            源                  大小
    =========================================================================================================
    正在安装:
     kernel                       x86_64            3.10.0-862.3.3.el7              updates             46 M
    正在更新:
     kernel-tools                 x86_64            3.10.0-862.3.3.el7              updates            6.2 M
     kernel-tools-libs            x86_64            3.10.0-862.3.3.el7              updates            6.2 M
     python-perf                  x86_64            3.10.0-862.3.3.el7              updates            6.2 M
    
    事务概要
    =========================================================================================================
    安装  1 软件包
    升级  3 软件包
    
    总计：65 M
    Downloading packages:
    Running transaction check
    Running transaction test
    
        YUM update failed.
    
        Exiting now.
    `

I check the file on eos/scripts/eosio_build_centos.sh, it says:

	 if ! sudo "${YUM}" -y update 2>/dev/null
                then
                printf "\\n\\tYUM update failed.\\n"
                printf "\\n\\tExiting now.\\n\\n"
                exit 1;

I'm a new guy on Linux, can anyone help me?
能说中文最好啦

**Comment by cppfuns** [comment]
加个梯子试试

**Comment by zhousi666** [comment]
我刚刚试了一下，也提示“YUM update failed”，然后发现是 “sudo "${YUM}" -y update”这里报的错。
你可以把这句话打印出来然后，手动在centos7 上执行 看是少了什么，自己安装就好了。
我的问题是“-bash sudo : command not found”，已经通过“yum -y install  sudo” 处理。

**Comment by taokayan** [comment]
We haven't received any update for this. Looks like this is already solved. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
