### ISSUE TITLE
Can I save the shared_memory.bin file to snapshot like checkpoint?

### ISSUE THREAD

**Issue by egonson** [EOSIO/eos#4406]
I found replay-blockchain takes too long time.
So I want to replay blocks from some snapshot rather than beginning.
Is this possible?
If the shared memory file is not consistent with current block data,
is the shared memory file useless at all?

In addition, can I extend the shared_memory file while nodeos is running?
Thanks.

**Comment by jgiszczak** [comment]
shared_memory.bin is a persistent copy of the memory database used by the node.  It is reread on startup with no arguments, and loaded into memory.  True snapshot functionality is in development.  See #4254.

If a shared memory file is not consistent with the block log, it is currently useless, and must be rebuilt from scratch.

Shared_memory can be resized by shutting down nodeos gracefully, changing the `chain-state-db-size-mb` config.ini setting to a larger number, and starting nodeos without any replay option.  If sufficient disk space is available, the file will grow to the new size.  Shared_memory can not be resized while nodeos is running.
