### ISSUE TITLE
Readme.md TOC and link issues

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#441]
Under Resources, Telegram link is https://eos.io/chat, which isn't working

**Comment by thomasbcox** [comment]
Link is probably okay, it's the destination / target that seems broken. 

Expanding this issue to include TOC problems in the Readme.md file.

**Comment by thomasbcox** [comment]
Current plan with @dskvr is to change the link to point directly to the Telegram channel.
