### ISSUE TITLE
The action of contract called by eosio.msig failed!(missing required authority)

### ISSUE THREAD

**Issue by lingyiliu016** [EOSIO/eos#4412]
I explain the background of the problem first.
This is content of the smart contrat follow.
![521530243874_ pic_hd](https://user-images.githubusercontent.com/27277897/42083656-1b2718b8-7bbe-11e8-8d6c-7c99d84b2b56.jpg)
I can call the action by multi-signature synchronously 
`cleos push action child.acnt execute '["boy.acnt","girl.acnt"]' -p boy.acnt -p girl.acnt`
![531530243954_ pic_hd](https://user-images.githubusercontent.com/27277897/42083797-77310696-7bbe-11e8-8739-8d08f68b8004.jpg)
I deploy the eosio.msig contract on blockchain.
The following is a record of the execution eosio.msig process.
firstly, I execute `cleos multisig propose` successfully!
`cleos multisig propose girl.acnt '[{"actor":"girl.acnt","permission":"active"}]' '[{"actor":"girl.acnt","permission":"active"}]' child.acnt execute '{"name1":"boy.acnt","name2":"girl.acnt"}' boy.acnt 100 -p boy.acnt`
<img width="1116" alt="20180629170938" src="https://user-images.githubusercontent.com/27277897/42084070-42e98678-7bbf-11e8-9ae1-807d6e42d1f5.png">
Secondly, I get the information successfully
`cleos multisig review boy.acnt girl.acnt`
<img width="1112" alt="20180629171147" src="https://user-images.githubusercontent.com/27277897/42084166-87f6ca64-7bbf-11e8-9e0e-1ac21c310651.png">
Thirdly I execute `cleos multisig approve` successfully!
`cleos multisig approve boy.acnt girl.acnt '{"actor":"girl.acnt","permission":"active"}'  -p girl.acnt`
<img width="1108" alt="20180629171334" src="https://user-images.githubusercontent.com/27277897/42084273-c6994abc-7bbf-11e8-998b-c6ba2d72708d.png">
Lastly I execute `cleos multisig exec` successfully,too!
`cleos multisig exec boy.acnt girl.acnt girl.acnt -p girl.acnt`
<img width="927" alt="20180629171535" src="https://user-images.githubusercontent.com/27277897/42084412-1c13268e-7bc0-11e8-974c-b65077ef11a6.png">
Although I executed  `cleos multisig exec` successfully, the action(execute) of contract (mulasynsig) called failed!  nodeos client throws this error.details as follow:
<img width="1112" alt="20180629172056" src="https://user-images.githubusercontent.com/27277897/42084665-da24a86e-7bc0-11e8-8960-96fa25c1289f.png">
The reason for this error is missing authority of boy.acnt, but Why?
I don't konw how to solve this issue!
give me some suggestion ,please!Thank you very much!

**Comment by andriantolie** [comment]
Take a look at your command here.
`cleos multisig propose girl.acnt '[{"actor":"girl.acnt","permission":"active"}]' '[{"actor":"girl.acnt","permission":"active"}]' child.acnt execute '{"name1":"boy.acnt","name2":"girl.acnt"}' boy.acnt 100 -p boy.acnt`

Notice that you don't specify boy.acnt for the transaction permission and requested permission here, it's the reason for the above error. Even though you made a proposal as boy.acnt, it doesn't implicitly mean that boy.acnt gives permission to the proposal that he proposed. He needs to declare it explicitly
