### ISSUE TITLE
Can not find eosio account for local dev

### ISSUE THREAD

**Issue by luckyyang** [EOSIO/eos#4413]
I run eos with docker, after I import the private key of eosio I can not see the eosio account:
![image](https://user-images.githubusercontent.com/1963646/42087219-18c3aa64-7bc8-11e8-928b-6a47b8443b81.png)

**Comment by jgiszczak** [comment]
`cleos get accounts` only works if history_plugin was enabled prior to the transactions that create the account.  If in a multinode network, this can be achieved by replaying and resynching with another node.  If a single node testnet, either create a new account or start over.

**Comment by luckyyang** [comment]
I changed the command inside `Docker/nodeosd.sh`:
from:
`exec /opt/eosio/bin/nodeos  $CONFIG_DIR "$@"`
to:
`exec /opt/eosio/bin/nodeos --delete-all-blocks $CONFIG_DIR "$@"`

Then added `eosio::history_plugin` into `config.ini`:
`plugin = eosio::history_plugin`

Then run `docker-compose up -d` again and it works.
