### ISSUE TITLE
Build failed on OSX High Sierra 10.13.5

### ISSUE THREAD

**Issue by serganus** [EOSIO/eos#4418]
# Commands
```
git clone https://github.com/eosio/eos --recursive
./eosio_build.sh
```

# Logs

```
./eosio_build.sh

	Beginning build version: 1.2
	Fri Jun 29 17:43:56 UTC 2018
	User: gautamanand
	git head id:XXXXXXX
	Current branch: master

	ARCHITECTURE: Darwin

	OS name: Darwin
	OS Version: 10.13.5
	CPU speed: 2.90Ghz
	CPU cores: 4
	Physical Memory: 16 Gbytes
	Disk install: /dev/disk1s1
	Disk space total: 1863G
	Disk space available: 1034G

	Checking xcode-select installation
	xcode-select installation found @ 
	/usr/bin/xcode-select 

	Checking Ruby installation.
	Ruby installation found @ 
	/usr/bin/ruby 

	Checking Home Brew installation
	Home Brew installation found @
	/usr/local/bin/brew

	Checking dependencies.
	Checking automake ... 		 automake found
	Checking Libtool ... 		 Libtool found
	Checking OpenSSL ... 		 OpenSSL found
	Checking llvm ... 		 llvm found
	Checking wget ... 		 wget found
	Checking CMake ... 		 CMake found
	Checking GMP ... 		 GMP found
	Checking gettext ... 		 gettext found
	Checking MongoDB ... 		 MongoDB found
	Checking Doxygen ... 		 Doxygen found
	Checking Graphviz ... 		 Graphviz found
	Checking LCOV ... 		 LCOV found
	Checking Python3 ... 		 Python3 found

	No required Home Brew dependencies to install.

	Checking boost library installation.
	Boost 1.67.0 found at /usr/local.

	Checking MongoDB C++ driver installation.
	Mongo C++ driver found at /usr/local/lib/libmongocxx-static.a.

	Checking secp256k1-zkp installation.
	secp256k1 found at /usr/local/lib/.

	Checking LLVM with WASM support.
	WASM found at /usr/local/wasm/bin/.


>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOSIO

>>>>>>>> CMAKE_BUILD_TYPE=Release
>>>>>>>> ENABLE_COVERAGE_TESTING=false
>>>>>>>> DOXYGEN=false

-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
-- Configuring EOSIO on OS X
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using 'SYS' as CORE symbol name
-- Using 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV' as public key for 'eosio' account
-- Using WASM clang => /usr/local/wasm/bin/clang
-- Using WASM llc => /usr/local/wasm/bin/llc
-- Using WASM llvm-link => /usr/local/wasm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Configuring fc to build on Unix/Apple
-- zlib found
-- Configuring Builtins
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   unit_test_framework
--   locale
-- Configuring ChainBase on OS X
CMake Error at libraries/wasm-jit/Source/Runtime/CMakeLists.txt:26 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 4.0) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/Users/gautamanand/Library/dapps/eos/build/CMakeFiles/CMakeOutput.log".

	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.
```

**Comment by jgiszczak** [comment]
Try:

`export LLVM_DIR=/usr/local/wasm/lib/cmake/llvm; ./eosio_build.sh`

EOS.IO requires a special build of LLVM, which the build script downloads, builds, and installs for you, but if you have a brew-installed version of LLVM, it takes precedence and conceals the version the EOS.IO build requires.  We often recommend removing the other compiler entirely, but I'd like you to try giving CMake an environment that will help it find the right version.

**Comment by pacificcode** [comment]
@serganus Or you can try the following:

brew remove --force llvm
brew install llvm@4
brew unlink llvm@4 && brew link --force llvm@4

**Comment by serganus** [comment]
@jgiszczak This didn't work!

@pacificcode This also didn't work.

Same error!

**Comment by pacificcode** [comment]
@serganus run the following and paste the full output of each command here:
llvm-config --has-rtti --version
which clang | xargs ls -lah
clang --version
ls -lah /usr/local/Cellar

**Comment by LittleXiaosi** [comment]
I had the same problem @pacificcode  

all the log is here 

yansideMacBook-Pro-2:eos yansi$ llvm-config --has-rtti --version
YES
4.0.1
yansideMacBook-Pro-2:eos yansi$ which clang | xargs ls -lah
lrwxr-xr-x  1 yansi  admin    32B  6 30 14:36 /usr/local/bin/clang -> ../Cellar/llvm@4/4.0.1/bin/clang
yansideMacBook-Pro-2:eos yansi$ clang --version
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /usr/local/bin
yansideMacBook-Pro-2:eos yansi$ ls -lah /usr/local/Cellar
total 0
drwxr-xr-x  37 yansi  admin   1.2K  6 30 13:44 .
drwxr-xr-x  25 root   wheel   800B  6 30 14:11 ..
drwxr-xr-x   3 yansi  admin    96B  6 27  2015 android-sdk
drwxr-xr-x   3 yansi  admin    96B  6 27  2015 ant
drwxr-xr-x   3 yansi  admin    96B  6 30 13:27 autoconf
drwxr-xr-x   3 yansi  admin    96B  6 30 13:27 automake
drwxr-xr-x   3 yansi  admin    96B  6 30 13:44 boost
drwxr-xr-x   3 yansi  admin    96B  6 30 13:31 cmake
drwxr-xr-x   3 yansi  admin    96B  6 30 13:32 doxygen
drwxr-xr-x   3 yansi  admin    96B  6 30 13:33 fontconfig
drwxr-xr-x   3 yansi  admin    96B  6 30 13:33 freetype
drwxr-xr-x   3 yansi  admin    96B  6 30 13:33 gd
drwxr-xr-x   3 yansi  admin    96B  6 30 13:31 gdbm
drwxr-xr-x   3 yansi  admin    96B  6 30 13:25 gettext
drwxr-xr-x   3 yansi  admin    96B  6 30 13:31 gmp
drwxr-xr-x   3 yansi  admin    96B  6 30 13:33 graphviz
drwxr-xr-x   3 yansi  admin    96B  6 30 13:33 jpeg
drwxr-xr-x   3 yansi  admin    96B  6 30 13:33 lcov
drwxr-xr-x   3 yansi  admin    96B  6 30 13:27 libffi
drwxr-xr-x   3 yansi  admin    96B  6 30 13:25 libidn2
drwxr-xr-x   3 yansi  admin    96B  6 30 13:33 libpng
drwxr-xr-x   3 yansi  admin    96B  6 30 13:33 libtiff
drwxr-xr-x   3 yansi  admin    96B  6 30 13:27 libtool
drwxr-xr-x   3 yansi  admin    96B  6 30 13:25 libunistring
drwxr-xr-x   3 yansi  admin    96B  6 30 13:30 llvm@4
drwxr-xr-x   3 yansi  admin    96B  6 30 13:32 mongodb
drwxr-xr-x   3 yansi  admin    96B  2 25  2016 nvm
drwxr-xr-x   3 yansi  admin    96B  6 30 13:25 openssl
drwxr-xr-x   3 yansi  admin    96B  2 25  2016 pkg-config
drwxr-xr-x   3 yansi  admin    96B  6 30 13:34 python
drwxr-xr-x   3 yansi  admin    96B  6 30 13:43 python@2
drwxr-xr-x   3 yansi  admin    96B  6 30 13:31 readline
drwxr-xr-x   3 yansi  admin    96B  5 21  2015 sdl2
drwxr-xr-x   3 yansi  admin    96B  6 30 13:31 sqlite
drwxr-xr-x   3 yansi  admin    96B  6 30 13:33 webp
drwxr-xr-x   3 yansi  admin    96B  6 30 13:25 wget
drwxr-xr-x   3 yansi  admin    96B  6 30 13:33 xz

**Comment by halsaphi** [comment]
Hi can you try using the latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
