### ISSUE TITLE
eosd does not serve http api requests on Linux

### ISSUE THREAD

**Issue by Netherdrake** [EOSIO/eos#442]
**Issue:**
```
~/G/E/e/c/p/eosd % curl http://127.0.0.1:8888/v1/chain/get_info
curl: (7) Failed to connect to 127.0.0.1 port 8888: Connection timed out
~/G/E/e/c/p/eosd % 
```

**Commit:**
abf65ff77d3a4cdaef9044a60b0f3cbe2d1eb7e6

**`eosd` output:**
https://gist.github.com/Netherdrake/ce04cbbf3ae000aba19ba3f141179aa5

**Potential issue:**
`ufw` is enabled, however this _shouldn't_ matter because we're using localhost.

**Comment by pavybez** [comment]
Please follow the instructions in readme or on github page. You need to modify the config.ini found in data-dir folder and add a few plugins (one of them being http-plugin). Let me know if that does not solve the issue.

**Comment by Netherdrake** [comment]
If you check the eosd output in the issue post, you can see that the plugin is initialized properly and the API endpoints are setup.

**Comment by heifner** [comment]
My guess is ufw is interfering, what is the output of `sudo ufw status`?

Also in one terminal run `nc -l 127.0.0.1 8888` and then in another terminal run `nc -zv 127.0.0.1 8888`. You should see something like `Connection to 127.0.0.1 8888 port [tcp/*] succeeded!`

You can, of course, run `man nc` to find help on nc.

**Comment by heifner** [comment]
@Netherdrake are you still having issues? Or can we close this issue?

**Comment by heifner** [comment]
Unable to duplicate. No response from the reporter for 5 days. Closing.

**Comment by JFreegman** [comment]
I'm having the same issue. Config is setup per the readme, wireshark shows the TCP packet is successfully sent but ignored, and disabling ufw doesn't help. The `nc` commands @heifner mentioned above indicated no issue.

error:

>3347466ms            main.cpp:1195                 main                 ] Failed with error: connect: Connection timed out (13)
>connect: Connection timed out:

eosd output on startup:

> ./eosd
712616ms            chain_plugin.cpp:126          plugin_initialize    ] initializing chain plugin
712616ms            wasm_interface.cpp:757        get                  ] Runtime::init
712617ms            producer_plugin.cpp:170       plugin_initialize    ] Public Key: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
712617ms            wallet_plugin.cpp:34          plugin_initialize    ] initializing wallet plugin
712617ms            http_plugin.cpp:138           plugin_initialize    ] host: 127.0.0.1 port: 8888 
712617ms            http_plugin.cpp:141           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
712617ms            net_plugin.cpp:2521           plugin_initialize    ] Initialize net plugin
712617ms            net_plugin.cpp:2543           plugin_initialize    ] Setting net_plugin logging level to info
712617ms            net_plugin.cpp:2571           plugin_initialize    ] host: 0.0.0.0 port: 9876 
712636ms            net_plugin.cpp:2650           plugin_initialize    ] my node_id is c8fef60ffb93285a84cd36653f61a81abc181303c1b7f9f04bccb2792ed9c2a4
712637ms            main.cpp:59                   main                 ] eosd version bcb5bf75
712641ms            block_log.cpp:92              open                 ] Opening block log at /home/jfreegman/eos/build/programs/eosd/data-dir/blocks/blocks.log
712641ms            block_log.cpp:120             open                 ] Log is nonempty
712642ms            block_log.cpp:128             open                 ] Index is nonempty
712649ms            chain_plugin.cpp:250          plugin_startup       ] starting chain in read/write mode
712649ms            chain_plugin.cpp:255          plugin_startup       ] Blockchain started; head block is #2783, genesis timestamp is 2017-03-30T12:00:00
712649ms            producer_plugin.cpp:181       plugin_startup       ] producer plugin:  plugin_startup() begin
712649ms            producer_plugin.cpp:186       plugin_startup       ] Launching block production for 21 producers.
712649ms            producer_plugin.cpp:196       plugin_startup       ] producer plugin:  plugin_startup() end
712649ms            http_plugin.cpp:153           plugin_startup       ] start processing http thread
712649ms            http_plugin.cpp:210           plugin_startup       ] start listening for http requests
712649ms            http_plugin.cpp:215           plugin_startup       ] http io service exit
712649ms            wallet_api_plugin.cpp:69      plugin_startup       ] starting wallet_api_plugin
712649ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/create
712649ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/get_public_keys
712649ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/import_key
712649ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/list_keys
712649ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/list_wallets
712649ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/lock
712649ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/lock_all
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/open
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/set_timeout
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/sign_transaction
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/unlock
712650ms            chain_api_plugin.cpp:60       plugin_startup       ] starting chain_api_plugin
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/abi_bin_to_json
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/abi_json_to_bin
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_account
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_block
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_code
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_info
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_required_keys
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/get_table_rows
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_block
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_transaction
712650ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/chain/push_transactions
712650ms            net_plugin.cpp:2662           plugin_startup       ] starting listener, max clients is 25
