### ISSUE TITLE
Can't read eosiocpp command

### ISSUE THREAD

**Issue by KennyLiu25775** [EOSIO/eos#4423]
hey guys i dont know if anyone of you guys have the same issue like me. So i installed EOS using docker, and i dont know why it just cannot read eosiocpp command. It always says `eosiocpp: command not found`...
![image](https://user-images.githubusercontent.com/11808716/42113879-d2e3a614-7ba1-11e8-84c8-3a4faf7e09ec.png)
appreciate it if anyone can helo me

**Comment by a627938936** [comment]
my error message is same to u
