### ISSUE TITLE
Throw event in transfer could lead to increasing balance twice

### ISSUE THREAD

**Issue by 7flash** [EOSIO/eos#4426]
https://github.com/EOSIO/eos/blob/90fefdd12a4797e47890910f11dd7b60f1435ed4/contracts/exchange/exchange.cpp#L14

**Comment by 7flash** [comment]
When user call method `deposit` tokens will be transferred and his balance will be increased in this method. But then his balance will be increased again in the line 202.

**Comment by taokayan** [comment]
The exchange contract is depreciated. Please use the latest version of EOS. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
