### ISSUE TITLE
cleos system buyram kbytes

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eos#4427]
cleos system buyram takes token amount as a parameter.
It should also allow user to specify exact number of kbytes (instead of token amount).

**Comment by andriantolie** [comment]
PR Merged

**Comment by wangzhixue2333** [comment]
[root@VM_16_7_centos deposit]# cleos system newaccount eosio test1 xxxxx xxxxx --stake-net "1000.0000 EOS" --stake-cpu "1000.0000 EOS" --buy-ram-kbytes "12800 KiB"
error 2019-04-16T09:47:59.839 thread-0  main.cpp:3449                 main                 ] Failed with error: Assert Exception (10)
!action_type.empty(): Unknown action buyrambytes in contract eosio


please help me
