### ISSUE TITLE
How does EOS prevent execution of infinite loops?

### ISSUE THREAD

**Issue by alice-bob-dlfs** [EOSIO/eos#4428]
I guess it's implemented somewhere for running WASM bytecodes, but couldn't find the exact code sections.

**Comment by heifner** [comment]
There are checktime calls that verify execution does not exceed limits.

**Comment by alice-bob-dlfs** [comment]
@heifner Does EOS currently run the bytecodes with JIT?  If so, when does the `checktime` get called?  I'm assuming during the execution of the native code, we have to somehow implement pre-emption?

**Comment by jgiszczak** [comment]
`checktime()` is called within the contract.  Contracts are modified by injection.  See [this comment](https://github.com/EOSIO/eos/issues/4329#issuecomment-400829845) for code references.
