### ISSUE TITLE
transaction declares authority '{"actor":"gushi","permission":"active"}', but does not have signatures for it.

### ISSUE THREAD

**Issue by lingyiliu016** [EOSIO/eos#4432]
when I execute the following command
`cleos set account permission gushi active '{"threshold":1,"keys":[{"key":"EOS7nLRAheR7tYMiTiCA2ry2vW2Yh4LKoMUsxiE6YcxSCh2nS8tq4","weight":1}],"accounts":[{"permission":{"actor":"market.acnt","permission":"eosio.code"},"weight":1}]}' owner -p gushi`
error occured!
details as follow:
<img width="1115" alt="20180630140815" src="https://user-images.githubusercontent.com/27277897/42122097-17368dc2-7c6f-11e8-9592-eee2f5a3e511.png">
what's the matter?
help me ,please! 
thank you very much!

**Comment by trungtt1981** [comment]
Just need to import the correspondent private key of the public key into your local wallet. Then, it should work fine.

**Comment by lingyiliu016** [comment]
firstly, the wallet including gushi is unlocked and have the private keys!
<img width="771" alt="20180630141216" src="https://user-images.githubusercontent.com/27277897/42122131-9cf2cafc-7c6f-11e8-8ff1-0783f30a1aef.png">
Secondly, Here is the gushi account information
<img width="997" alt="20180630141340" src="https://user-images.githubusercontent.com/27277897/42122143-d244090a-7c6f-11e8-923c-62d02af4d4a9.png">

**Comment by lingyiliu016** [comment]
@trungtt1981  I have  import the correspondent private key of the public key into your local wallet,but wrong still.above is information of my account

**Comment by lingyiliu016** [comment]
Now I want to authorize gushi to eosio and eosio.msig.
here is my command!
`cleos set account permission gushi active '{"threshold":2,"keys":[{"key":"EOS7nLRAheR7tYMiTiCA2ry2vW2Yh4LKoMUsxiE6YcxSCh2nS8tq4","weight":2}],"accounts":[{"permission":{"actor":"eosio","permission":"eosio.code"},"weight":1},{"permission":{"actor":"eosio.msig","permission":"eosio.code"},"weight":1}]}' owner -p gushi`
but wrong is still occur!
<img width="1115" alt="20180630142019" src="https://user-images.githubusercontent.com/27277897/42122205-cdbee250-7c70-11e8-9dab-e9069967de32.png">
firstly, I think my command maybe wrong! tell me the right way!
secondly, give some suggestion about how to solve this problem.

**Comment by lingyiliu016** [comment]
solution:
`cleos set account permission gushi active '{"threshold":1,"keys":[{"key":"EOS7nLRAheR7tYMiTiCA2ry2vW2Yh4LKoMUsxiE6YcxSCh2nS8tq4","weight":1}],"accounts":[{"permission":{"actor":"eosio","permission":"eosio.code"},"weight":1}]}' owner -p gushi@owner`
Very good! it works!

**Comment by andriantolie** [comment]
I'm closing this issue as the user has solved his problem

**Comment by surraajjjjj** [comment]
while transfering ecoin from my telos tribe wallet app it is showing transaction declares authority '{"actor":surraajjjjj1","permission":"active"}',but does not have signatures on it. please help.

**Comment by dannykansas** [comment]
Same issue. Incredible how complicated EOS managed to make things, even just to experiment with!
