### ISSUE TITLE
add 3 accounts to permission and fail

### ISSUE THREAD

**Issue by NeverLandFly** [EOSIO/eos#4433]
Hi, i'm trying to create an multisig account, when i add 2 accounts to the json, it works fine, 

cleos set account permission escrow active '{"threshold":2,"keys":[],"accounts":[{"permission":{"actor":"bob","permission":"active"},"weight":1},{"permission":{"actor":"joe","permission":"active"},"weight":1}],"waits":[]}' owner -p escrow@owner

but fails when the third added:
cleos set account permission escrow active '{"threshold":2,"keys":[],"accounts":[{"permission":{"actor":"bob","permission":"active"},"weight":1},{"permission":{"actor":"joe","permission":"active"},"weight":1},{"permission":{"actor":"dave","permission":"active"},"weight":1}],"waits":[]}' owner -p escrow@owner

Error Details:
Authority failed validation! ensure that keys, accounts, and waits are sorted and that the threshold is valid and satisfiable!

**Comment by davidfrothin** [comment]
You need to sort the three actors alphabetically.
try > bob, dave, joe
and it will work

**Comment by davidfrothin** [comment]
You need to sort the three actors alphabetically.
try > bob, dave, joe
and it will work

**Comment by NeverLandFly** [comment]
@davidfrothin  It did work!
Thanks!

**Comment by dawnFromDark** [comment]
> You need to sort the three actors alphabetically.
> try > bob, dave, joe
> and it will work

thanks for your help,this issue makes me crazy!

**Comment by kriskoin** [comment]
Thanks for post this soluccion !!!

**Comment by cppfuns** [comment]
This is a bug? 
@larryk85 @johndebord
