### ISSUE TITLE
Token contract not enforcing unique symbol names (Multiple EOS tokens on chain)

### ISSUE THREAD

**Issue by blahbax** [EOSIO/eos#4434]
There are currently multiple EOS, BTC and EOSDAC tokens on chain. Token contract does not appear to be enforcing unique tickers, even for the network token.

https://eosmonitor.io/coins?page=1

(Third button on the right gets you next page).

Here's a tx with someone creating some EOS https://eospark.com/MainNet/tx/89a0085987fdb407c628303aa091334c6f28a1c48efe4b0e6e0e4d3bacd0b40e

Would appreciate ownership of our ticker as finder's fee for this bug.

**Comment by tbfleming** [comment]
Each account which runs eosio.token forms a separate namespace. EOS@eosio.token is different from EOS@blah. Some monitors aren't aware of this.

**Comment by blahbax** [comment]
That is inviting a whole bunch of trouble. Ticker namespace should be unique and independent from account namespace.

**Comment by venediktov** [comment]
@blahbax , @tbfleming looks like EOS is no different from ethereum in that regard. Same ERC20 code can belong to many different ethereum public addresses.  Therefore  @blahbax I don't see any issue with that . If it works for Ethereum it should work for EOS.

**Comment by blahbax** [comment]
@tbfleming @venediktov lol https://cryptodaily.co.uk/2018/09/1-billion-fake-eos-tokens-used-to-steal-58k-from-decentralised-exchange/

Fair enough this largely boils down to the exchange and not the eosio code, but door was left wide open.

**Comment by venediktov** [comment]
Hi @blahbax , you can create as many tokens with the same name on Ethereum too.

- On Ethereum It's not the name of a symbol that matters but address of ERC20 contract hosting the symbol . 
- On EOS it's not the name of a symbol but the account name that owns token contract hosting the symbol. 

Here is explanation how ethereum works with tokens

https://ethereum.stackexchange.com/questions/24725/are-erc20-token-names-unique

It's **Newdex** problem not EOS ,  **Newdex** needs to run same validation as it would do for ethereum tokens. 


quote from your article 
> the gaping security holes left by token exchange developers too negligent to even program a smart contract to protect users.”

**Comment by emptypockts** [comment]
Hi What is the benefit of allowing duplicate banes and tickers? I just don’t see the value of doing that

**Comment by tbfleming** [comment]
Contract A can't limit what Contract B does when they're controlled by separate parties
