### ISSUE TITLE
bidname didn't refund correctly

### ISSUE THREAD

**Issue by luckybean** [EOSIO/eos#4435]
Bidname: com

Bid timeline:
1. Account <b>tokeneconomy</b> bid on "com" with 490 EOS at 2018-06-28 15:52:45, tx is: f16069bcff6385157e8b637227af8eb50456e1b34fcabf43bab87292ee77f275

2. Account <b>gi3dmnjugqge</b> bid on "com" with 500 EOS at 2018-06-30 08:18:59, tx is: ca49a9b41316c2ba2bf8e79418bfb5389663f1a2f203992e97b7e14be5d1c7d3
This transaction was successful but it `should be failed` because the price 500 EOS is less than 110% of former bid price 490 EOS.
Two actions of this transaction are the same, `which are also wrong`.

3. Account <b>starteosiobp</b> bid on "com" with 550 EOS at 2018-06-30 16:28:46, tx is: 5d95ef88e7c5d3df033605273476b7e581fa48843f4e6915296fc7c9bfa78265
In this transaction, an action will refund bid on "com" to <b>tokeneconomy</b> with 490 EOS. Now the 500 EOS of <b>gi3dmnjugqge</b> is missing.

<br/>
<b>In general, there are two problems:</b>
<br/>1. The above step2 should not be passed.
<br/>2. The 500 EOS of <b>gi3dmnjugqge</b> is missing.

**Comment by jchung00** [comment]
Also, if gi3dmnjugqge's bid went through, tokeneconomy should have been refunded after step 2.

**Comment by alienzin** [comment]
step2 is not real 'bidname' transaction.
Account **gi3dmnjugqge** just transferred 500 EOS to eosio.names with memo "bid name com".

To bid a name, you should call action "bidname" of "eosio.system" contract.

So there's nothing wrong in above 3 transactions.

**Comment by luckybean** [comment]
@alienzin make sense, thank you.
btw, can the account get the 500 EOS back from eosio.names ?
