### ISSUE TITLE
Error 3050003 still no fix

### ISSUE THREAD

**Issue by wsdfz** [EOSIO/eos#4436]
After mainnet upgrade to v1.0.5, I cannot see the message of eosio_assert any more.

It only shows:
Error 3050003: eosio_assert_message assertion failure

Now it still do not fix in mainnet. For the errors appear in the contracts in mainnet, developers can not debug it and fix.

I think it blocks the development of dapps and should fix ASAP.

**Comment by wanderingbort** [comment]
You should not be debugging a contract sending requests to a mainnet node.

The two acceptable modes of debugging are to run a local node where you
will see the contract messages in your log OR to find an RPC node
explicitly configured to act as a debug RPC node.  In particular you want a
node that sets "verbose-http-errors" to true.

**Comment by jgiszczak** [comment]
The developer can run a mainnet RPC node with `verbose-http-errors = true` in config.ini and provide users HTTPS access to that node.

**Comment by wsdfz** [comment]
It lets the dapp develop must create , maintain and sync a eos node before he can create a dapp.

It costs a lot.
