### ISSUE TITLE
Error 3050003: eosio_assert_message assertion failure instead "already claimed rewards within past day" when claimrewards

### ISSUE THREAD

**Issue by dionisin** [EOSIO/eos#4437]
Tested in Jungletestnet and mainnet v1.0.7

When execute action for claim rewards before 24 hours from last claimed

>cleos system claimrewards mosquitometa -p mosquitometa
1916519ms thread-0   main.cpp:429 create_action] result: {"binargs":"60b292343b6d3195"} arg: {"code":"eosio","action":"claimrewards","args":{"owner":"mosquitometa"}} 
**Error 3050003: eosio_assert_message assertion failure**

The error should be "already claimed rewards within past day" 

_eos/contracts/eosio.system/producer_pay.cpp_
eosio_assert( ct - prod.last_claim_time > useconds_per_day, "**already claimed rewards within past day**" );

**Comment by andriantolie** [comment]
Yes, "already claimed rewards within past day" is the detailed message of the above error which is suppressed by default now. If you want to see the detailed error message, use `--verbose-http-errors` arg when starting your nodeos and you will be able to see it :)
