### ISSUE TITLE
When I run nodeos there was a exception with a messge (reversible block database is inconsistent with fork database, replay blockchain)

### ISSUE THREAD

**Issue by jongyoungcha** [EOSIO/eos#4439]
Hi recently, I'm studing eos plaform, 

But after build with new eos revision, Its start to show a follow message.

"reversible block database is inconsistent with fork database, replay blockchain"

If I infer the exception, It occured when load the blocks in the local muchien......  

![image](https://user-images.githubusercontent.com/7163653/42130976-e3611f04-7d30-11e8-859f-f54a5a861518.png)

please give me a solution..... thanks

**Comment by jgiszczak** [comment]
Try `--hard-replay-blockchain`.  Be sure you have enough free disk space for a complete copy of the chain, as it will be moved out of the way and a new version created from as much of the old as is possible.

**Comment by jongyoungcha** [comment]
I already add --hard-replay-blockchain option.
I have deleted my all blocks with --delete-all-blocks, The issue has disappeared.

**Comment by brandedux** [comment]
Any recent suggestions on best practice to solve this without delete-all-blocks... there are several threads on this topic with zero solutions.
