### ISSUE TITLE
EOS RAM market improvement(s)

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#4440]
Currently there are quite a few issues associated with RAM market, from hoarding and speculation driving cost of operating on EOS blockchain up to having BPs act as central bankers collectively deciding on supply of a precious resource with all the potential for abuse.
One of the possible ways to improve RAM market is to make RAM price algorithmically tied to actual usage ratio (used/total) of RAM rather than remainder of unpurchased supply as is now.
This will likely reduce incentive to hoard and speculate with RAM, driving cost of running a DAapp on EOS down and increasing blockchain usage.
Other ideas for RAM market improvements are welcome.

**Comment by hashware** [comment]
What about charge a fixed fee on newaccount creation, take 0.1 EOS for 4KB consideration.

**Comment by bitcoiners** [comment]
@CharlesJu1 Yes, hoarding should be made constly to remove incentive to hoard beyond need.

**Comment by thbourlove** [comment]
Agree to improve the EOS RAM market, but "actual usage ratio (used/total) of RAM" is easy to fake by store some rubbish in my own contract.

**Comment by jgiszczak** [comment]
Closing as this is more a political issue than a software issue, and as thbourlove points out, there is no way to distinguish legitimate usage from hoarded usage.
