### ISSUE TITLE
get deferred transaction id when undelegatebw?

### ISSUE THREAD

**Issue by hupengbuaa** [EOSIO/eos#4443]
I need know when the `undelegatebw` actually refund EOS to my account, could I get the deferred trx id when performing undelegatebw action?

**Comment by hama** [comment]
same issue

**Comment by brianjohnson5972** [comment]
You could use the get_table_rows chain_api call with table=="refunds"_n, scope=="<from account name>", table_key="<from account name>" to check the value before you issue the undelegatebw and then you will know that the undelegatebw has been executed.  If there isn't a current refund being processed then there will be no table entry for the from account.
