### ISSUE TITLE
 resource limit in eos  v1.0.7？

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#4444]
I had a private network build on eos v1.0.1,there is no limit in account limit ,because I have seen every account's resource is -1.
But there is limit on v1.0.7,how to avoid it?

**Comment by jgiszczak** [comment]
When starting a private network, after setting the eosio.bios contract, use `setalimits` to set RAM limit and CPU and network capacity weights to INT64_MAX for an account. INT64_MAX is 9223372036854775807.  If you have already progressed your private network to eosio.system, you will need to transfer large amounts (> 100000000) of your system token to the accounts you wish to "unlimit" and stake those tokens.
