### ISSUE TITLE
How to authorize one account to another account in the contract and change the authorization?

### ISSUE THREAD

**Issue by AIYP1226** [EOSIO/eos#4447]
How is eosio.prods licensed to 21 bp?

**Comment by blockchain-expert** [comment]
its through voting....from the other members

**Comment by jgiszczak** [comment]
A description of the mechanics of voting may be found in the [documentation](https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence).  There are many high level descriptions available on the web, including videos.
