### ISSUE TITLE
Potential memory in binaryen submodule

### ISSUE THREAD

**Issue by sbrella-andy** [EOSIO/eos#4450]
Our code analyzer has found a potential memory in binaryen submodule

In Line#119 in src/passes/LegalizeJSInterface.cpp, a memory is allocated as follows:

    auto* legal = new Function();

https://github.com/EOSIO/binaryen/blob/e13b8b74d210b882f19252dc11dc3df73294ae13/src/passes/LegalizeJSInterface.cpp#L119

There is only one place in the function that stores the value "legal" into a container in line#163 as follows

    if (!module->getFunctionOrNull(legal->name)) {
      module->addFunction(legal);
    } 

https://github.com/EOSIO/binaryen/blob/e13b8b74d210b882f19252dc11dc3df73294ae13/src/passes/LegalizeJSInterface.cpp#L162

And then, we lose track of the variable "legal", meaning that given that we cannot find the function in the module, a memory of **sizeof(Function)** bytes may leak.

**Comment by jgiszczak** [comment]
As nodeos no longer accepts WAST files for a contract, this does not happen in a persistent process.  We encourage you to report the problem to the upstream maintainers of binaryen.
