### ISSUE TITLE
request_next_chunk   ] Unable to continue syncing at this time (eos version 1.0.7)

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#4456]
while i ctrl+c break off nodeos,but restart arrise error as follow:

xteam@xteam-virtual-machine:~/eos$ nodeos
1732705ms thread-0   chain_plugin.cpp:209          plugin_initialize    ] initializing chain plugin
1732709ms thread-0   block_log.cpp:123             open                 ] Log is nonempty
1732709ms thread-0   block_log.cpp:141             open                 ] Index is nonempty
1732811ms thread-0   http_plugin.cpp:290           plugin_initialize    ] configured http to listen on 0.0.0.0:8888
1732811ms thread-0   net_plugin.cpp:2948           plugin_initialize    ] Initialize net plugin
1732811ms thread-0   net_plugin.cpp:2972           plugin_initialize    ] host: 0.0.0.0 port: 9876
1732811ms thread-0   net_plugin.cpp:3044           plugin_initialize    ] my node_id is e316b8eb1ceac13434b85edf44c1b5f35d20d4d5b6d9bf81d883d3a0fdab5e9c
1732811ms thread-0   net_api_plugin.cpp:95         plugin_initialize    ]
**********SECURITY WARNING**********
*                                  *
* --         Net API            -- *
* - EXPOSED to the LOCAL NETWORK - *
* - USE ONLY ON SECURE NETWORKS! - *
*                                  *
************************************

1732811ms thread-0   wallet_plugin.cpp:39          plugin_initialize    ] initializing wallet plugin
1732811ms thread-0   wallet_api_plugin.cpp:122     plugin_initialize    ]
********!!!SECURITY ERROR!!!********
*                                  *
* --       Wallet API           -- *
* - EXPOSED to the LOCAL NETWORK - *
* -  HTTP RPC is NOT encrypted   - *
* - Password and/or Private Keys - *
* - are at HIGH risk of exposure - *
*                                  *
************************************

1732811ms thread-0   history_plugin.cpp:275        plugin_initialize    ] --filter-on * enabled. This can fill shared_mem, causing nodeos to stop.
1732812ms thread-0   main.cpp:104                  main                 ] nodeos version b195012b
1732812ms thread-0   main.cpp:105                  main                 ] eosio root is /home/xteam/.local/share
1732812ms thread-0   chain_plugin.cpp:450          plugin_startup       ] starting chain in read/write mode
1732812ms thread-0   chain_plugin.cpp:455          plugin_startup       ] Blockchain started; head block is #2922937, genesis timestamp is 2018-06-08T08:08:08.888
1732812ms thread-0   http_plugin.cpp:331           plugin_startup       ] start listening for http requests
1732812ms thread-0   chain_api_plugin.cpp:75       plugin_startup       ] starting chain_api_plugin
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/abi_bin_to_json
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/abi_json_to_bin
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_abi
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_account
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_block
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_block_header_state
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_code
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_currency_balance
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_currency_stats
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_info
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_producers
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_required_keys
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_table_rows
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/push_block
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/push_transaction
1732812ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/push_transactions
1732812ms thread-0   net_plugin.cpp:3056           plugin_startup       ] starting listener, max clients is 25
1732813ms thread-0   net_plugin.cpp:749            connection           ] created connection to 119.254.15.39:9876
1732813ms thread-0   net_plugin.cpp:1970           connect              ] host: 119.254.15.39 port: 9876
1732813ms thread-0   net_plugin.cpp:749            connection           ] created connection to 119.254.15.40:9876
1732813ms thread-0   net_plugin.cpp:1970           connect              ] host: 119.254.15.40 port: 9876
1732813ms thread-0   net_plugin.cpp:749            connection           ] created connection to p2p.prod.eosgravity.com:80
1732813ms thread-0   net_plugin.cpp:1970           connect              ] host: p2p.prod.eosgravity.com port: 80
1732813ms thread-0   net_plugin.cpp:749            connection           ] created connection to peer1.mainnet.eos.store:80
1732813ms thread-0   net_plugin.cpp:1970           connect              ] host: peer1.mainnet.eos.store port: 80
1732813ms thread-0   net_plugin.cpp:749            connection           ] created connection to peer2.mainnet.eos.store:80
1732813ms thread-0   net_plugin.cpp:1970           connect              ] host: peer2.mainnet.eos.store port: 80
1732813ms thread-0   net_plugin.cpp:749            connection           ] created connection to bp.cryptolions.io:9876
1732813ms thread-0   net_plugin.cpp:1970           connect              ] host: bp.cryptolions.io port: 9876
1732813ms thread-0   net_plugin.cpp:749            connection           ] created connection to p2p.meet.one:9876
1732813ms thread-0   net_plugin.cpp:1970           connect              ] host: p2p.meet.one port: 9876
1732813ms thread-0   net_plugin.cpp:749            connection           ] created connection to publicnode.cypherglass.com:9876
1732813ms thread-0   net_plugin.cpp:1970           connect              ] host: publicnode.cypherglass.com port: 9876
1732813ms thread-0   net_api_plugin.cpp:63         plugin_startup       ] starting net_api_plugin
1732813ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/net/connect
1732813ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/net/connections
1732813ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/net/disconnect
1732813ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/net/status
1732813ms thread-0   wallet_api_plugin.cpp:73      plugin_startup       ] starting wallet_api_plugin
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/create
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/create_key
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/get_public_keys
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/import_key
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/list_keys
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/list_wallets
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/lock
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/lock_all
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/open
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/remove_key
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/set_timeout
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/sign_digest
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/sign_transaction
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/wallet/unlock
1732814ms thread-0   history_api_plugin.cpp:38     plugin_startup       ] starting history_api_plugin
1732814ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_actions
1732815ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_controlled_accounts
1732815ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_key_accounts
1732815ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_transaction
1732815ms thread-0   producer_plugin.cpp:577       plugin_startup       ] producer plugin:  plugin_startup() begin
1733018ms thread-0   producer_plugin.cpp:604       plugin_startup       ] producer plugin:  plugin_startup() end
1733112ms thread-0   net_plugin.cpp:2190           operator()           ] Peer p2p.prod.eosgravity.com:80 closed connection
1733263ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from 119.254.15.39:9876: Bad file descriptor
1733438ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from 119.254.15.40:9876: Bad file descriptor
1733629ms thread-0   net_plugin.cpp:1410           request_next_chunk   ] Unable to continue syncing at this time
1733629ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from peer1.mainnet.eos.store:80: Bad file descriptor
1735189ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from publicnode.cypherglass.com:9876: Bad file descriptor
1735277ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from bp.cryptolions.io:9876: Bad file descriptor
1748770ms thread-0   net_plugin.cpp:1410           request_next_chunk   ] Unable to continue syncing at this time
1748770ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from p2p.meet.one:9876: Bad file descriptor

**Comment by jgiszczak** [comment]
You have eight peers configured.  Five of them closed their connections.  Did the other three also close their connections?  If not, leave the node running to allow synchronization to be retried.  It can take some time to sort out which node will be used to resynch.
