### ISSUE TITLE
How to speed up full node synchronization??

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#4459]
I have not finished the data synchronization of the main network for several days. What is a good way to speed up the synchronization??

61232ms thread-0   net_plugin.cpp:2012           operator()           ] connection failed to peer2.mainnet.eos.store:80: Connection timed out
768774ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block fc21d565d8d859aa... #3073000 @ 2018-06-28T11:05:11.000 signed by eoscanadacom [trxs: 2, lib: 3072665, conf: 0, latency: 400057774 ms]
781240ms thread-0   net_plugin.cpp:1970           connect              ] host: peer2.mainnet.eos.store port: 80
877159ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block edc3d9c760104249... #3074000 @ 2018-06-28T11:13:31.000 signed by eoscanadacom [trxs: 1, lib: 3073673, conf: 0, latency: 399666159 ms]
910676ms thread-0   net_plugin.cpp:2012           operator()           ] connection failed to peer2.mainnet.eos.store:80: Connection timed out
931583ms thread-0   net_plugin.cpp:1970           connect              ] host: peer2.mainnet.eos.store port: 80
976434ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 7cba52e29c4f3a59... #3075000 @ 2018-06-28T11:21:51.000 signed by eoscafeblock [trxs: 0, lib: 3074669, conf: 0, latency: 399265434 ms]
1047797ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 0510983041e73f2f... #3076000 @ 2018-06-28T11:30:11.000 signed by eosbeijingbp [trxs: 2, lib: 3075665, conf: 0, latency: 398836797 ms]

**Comment by lcgogo** [comment]
change the p2p peers config in config.ini and restart nodeos.

**Comment by halsaphi** [comment]
Closed as old issue, though please ensure you use the latest version of code.
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
