### ISSUE TITLE
build error on ubuntu : Error compiling MongoDB C driver

### ISSUE THREAD

**Issue by tqknight1984** [EOSIO/eos#4460]
环境：
uname -r
4.15.0-23-generic

执行./eosio_build.sh  未通过：

`  -t, --touch                 touch 目标而不是重新创建它们。
  --trace                     打印跟踪信息。
  -v, --version               打印 make 的版本号并退出。
  -w, --print-directory       打印当前目录。
  --no-print-directory        关闭 -w，即使 -w 默认开启。
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              将 FILE 当做最新。
  --warn-undefined-variables  当引用未定义变量的时候发出警告。

该程序为 x86_64-pc-linux-gnu 编译
报告错误到 <bug-make@gnu.org>
        Error compiling MongoDB C driver.

        Exiting now.
`

然后下载了 新版Mongo-c-driver 1.1.0：
`$ wget https://github.com/mongodb/mongo-c-driver/releases/download/1.11.0/mongo-c-driver-1.11.0.tar.gz
$ tar xzf mongo-c-driver-1.11.0.tar.gz
$ cd mongo-c-driver-1.11.0
$ mkdir cmake-build
$ cd cmake-build
$ cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF ..

$ make
$ sudo make install`

编译通过后，重新./eosio_build.sh，但 还是报错：
`报告错误到 <bug-make@gnu.org>
        Error compiling MongoDB C driver.

        Exiting now.`

**Comment by vsiryxm** [comment]
踩过这个坑，见我的文章：https://www.jianshu.com/p/13c7bddacfd9

**Comment by tqknight1984** [comment]
@vsiryxm 
多谢，已发现是脚本（scripts/eosio_build_ubuntu.sh）这一行问题：
CPU_CORE=$( lscpu | grep "^CPU(s)" | tr -s ' ' | cut -d\  -f2 || cut -d' ' -f2 )
解决：
也是写死 CPU_CORE=8

**Comment by unknownfix** [comment]
@vsiryxm @tqknight1984 CPU_CORE=1, CPU_CORE=2, CPU_CORE=8 etc not work for me, still same MongoDB error... I have digitalOcean 1cpu

**Comment by andriantolie** [comment]
Is this problem solved?

**Comment by halsaphi** [comment]
Closed as old issue,  this was fixed.
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
