### ISSUE TITLE
mongo_db_plugin.cpp compile error

### ISSUE THREAD

**Issue by Junxin-Huo** [EOSIO/eos#4461]
I open the mongo_db_plugin to compile in [https://github.com/EOSIO/eos/blob/master/plugins/mongo_db_plugin/CMakeLists.txt](url). Like:

#add_subdirectory(faucet_testnet_plugin)
add_subdirectory(mongo_db_plugin)
#add_subdirectory(sql_db_plugin)

But it can't compile right. Will mongo_db_plugin be used in the future? And When?

**Comment by jgiszczak** [comment]
Bringing the mongo_db_plugin up to date is in work.  See PR #4304.
