### ISSUE TITLE
Problems with wallet list

### ISSUE THREAD

**Issue by m13oas** [EOSIO/eos#4467]
When I run cleos wallet list, I get list of my wallets, but when I run list_wallets via RPC request, I get an empty array. run keosd an http server localhost:8900. Is there bug, or problems with configurations??
See a keosd processes, there is only one process.

**Comment by andriantolie** [comment]
Hi @m13oas, how do you query your keosd? Both RPC request and cleos should return the same result since cleos is using RPC request internally.

The result of `curl http:/localhost:8900/v1/wallet/list_wallets` and `cleos wallet list` should be the same.

**Comment by andriantolie** [comment]
`cleos wallet list` without any argument defaults to http://localhost:8900 to find the wallet so the above commands are not equivalent! Try curl-ing to localhost 8900 instead :)

**Comment by andriantolie** [comment]
We haven't received any follow up from this. 
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
