### ISSUE TITLE
Is it possible to create more token?

### ISSUE THREAD

**Issue by coderKM** [EOSIO/eos#4469]
I created token with a symbol as SYS, and am trying to create some more tokens with same symbol.
However, I am getting an **assertion failure with message : token with symbol already exists.**
Is there any way that I can create more tokens with same symbol or update the token amount?

**Comment by jgiszczak** [comment]
In the current `eosio.token` contract, the maximum supply of a token may not be modified after it is created.  Other token contracts may be different.
