### ISSUE TITLE
why i can't set account permission to eosio.ccode ?

### ISSUE THREAD

**Issue by stev1988** [EOSIO/eos#4479]
i can set account permission to eosio.code, but it is failed to set account to eosio.ccode,why?
right:
cleos  set account permission user1 active '{"threshold": 1,"keys": [{"key": "EOS7nnGJ7Ra911dwR1rQFw2MD2M8RkRPzUBtYb3qBmuYfaxbkUWmd","weight": 1}],"accounts": [{"permission":{"actor":"ico","permission":"eosio.code"},"weight":1}]}' owner -p user1

fail:
cleos  set account permission user1 active '{"threshold": 1,"keys": [{"key": "EOS7nnGJ7Ra911dwR1rQFw2MD2M8RkRPzUBtYb3qBmuYfaxbkUWmd","weight": 1}],"accounts": [{"permission":{"actor":"ico","permission":"eosio.ccode"},"weight":1}]}' owner -p user1

fail reason:
1590893ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 3050000 action_validate_exception: action exception
permission '{"actor":"ico","permission":"eosio.ccode"}' does not exist
    {"perm":{"actor":"ico","permission":"eosio.ccode"}}
    thread-0  eosio_contract.cpp:56 validate_authority_precondition

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:62 exec_one

Does any guy know the reason?

**Comment by andriantolie** [comment]
It's because support for eosio.ccode not implemented yet. It's still a proposal for now
