### ISSUE TITLE
Taking snapshot of EOS accounts

### ISSUE THREAD

**Issue by CharlesJu1** [EOSIO/eos#4480]
Is there a built in support to get snapshot of EOS accounts? I could not find related info. Given the EOS account balance changes continuously, how about adding the following support?
1. Add the api similar to v1/producer/pause to stop a full node from accepting new incoming blocks at a certain time point or a block number. This will keep the state of a full node kind of freeze. 
2. Add a snapshot plugin to page the EOS account via an api.

**Comment by jgiszczak** [comment]
Snapshot supported was added in v1.4.1.  The producer_api_plugin provides the `/vi/producer/pause` API.
