### ISSUE TITLE
In contract, eosio.token get_balance with new user, should return 0, but throw error

### ISSUE THREAD

**Issue by 86chenjie** [EOSIO/eos#4481]
```
    eosio::token t(N(eosio.token));
    const auto sym_name = eosio::symbol_type(S(4,TTT)).name(); // int
    const auto balance = t.get_balance(user, sym_name );
```

balance should be 0, but error throwed:
```
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: unable to find key
```

```
asset token::get_balance( account_name owner, symbol_name sym )const
   {
      accounts accountstable( _self, owner );
      const auto& ac = accountstable.get( sym );
      return ac.balance;
   }
```

probably this line is the root cause.
```
const auto& ac = accountstable.get( sym );
```

**Comment by jgiszczak** [comment]
The thrown error is correct.  An account which has never participated in a particular token does not have a zero balance.  It has no participation.  The states are distinct.

**Comment by 86chenjie** [comment]
@jgiszczak  thanks for your response. But in contract, i need a way to check the account's token balance.
If throw error, how should i handle this ?

**Comment by qiushaoxi** [comment]
> Rather than use `get()`, which includes an `assert()`, use `find()` and test the result against `accountstable.cend()`. If it's `cend()`, the account has no participation in the given token.

accountstable.cend() or accountstable.end() ？
