### ISSUE TITLE
boost::interprocess::bad_alloc

### ISSUE THREAD

**Issue by crazybits** [EOSIO/eos#4484]
the following error would be encountered after set `filter-on = *` and enable `history_plugin` on config.ini

```
terminate called after throwing an instance of 'boost::interprocess::bad_alloc'
  what():  boost::interprocess::bad_alloc
```

**Comment by vjoke** [comment]
the shared memory mapped file is full due to filter-on = *.  Basically, this option is only for testing, and cannot be set to * in production env.
