### ISSUE TITLE
Unable to transfer token using node eosjs 

### ISSUE THREAD

**Issue by rameshb444** [EOSIO/eos#4487]
Hi,

I am trying to transfer token using node and eosjs, but getting below errors
**message: 'action\'s code account \'eosio.token\' does not exist**
< error      { message: 'action\'s code account \'eosio.token\' does not exist',
  file: 'controller.cpp',
  line_number: 1486,
  method: 'validate_referenced_accounts' } http://127.0.0.1:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-07-04T07:50:59","ref_b ock_num":10513,"ref_block_prefix":2239072832,"net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio.token","name": transfer","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000c85353848c970040c85353848c97a086010000000000045359530000000000"}],"transaction_extensions :[]},"signatures":["SIG_K1_JzPeH9uE3bhfTNb1QQf8sNzvvm6Pkc8rqEX2EHCMh1DwmdUZGbD1j6Y73drwLm3nzaU99oBzkN1cJ2tybcCJGY7wKqRYXp"]}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3040000,"name":"transaction_exception","what":"transaction exception","details":[{"message":"acti n's code account 'eosio.token' does not exist","file":"controller.cpp","line_number":1486,"method":"validate_referenced_accounts"}]}}
    at /home/eos/node/eos-api/node_modules/eosjs-api/lib/apigen.js:95:23

**Below is my nodejs code :** 

Eos = require('eosjs');
// Connect to a testnet or mainnet
eos = Eos(httpEndpoint, chainId, '5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3');
eos = Eos({"keyProvider" : "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"});
options = {
  authorization: 'eosio@active',
  broadcast: true,
  sign: true
}
eos.transfer('myaccount', 'myaccount1', '10.0000 SYS', '', options);

**But I can transfer tokens using cleos from terminal.**

./cleos --wallet-url http://localhost:8899 push action myaccount issue '["myaccount1", "100.0000 SYS", "memo" ]' -p eosio
executed transaction: f6754433845024b533158ded0d99b54f8ac75dc61bcd75b845f5e41849ad9c77  128 bytes  1965 us
 

Please let me know if I am doing anything wrong. Thanks.

**Comment by andriantolie** [comment]
Have you created eosio.token account and deployed the contract?

**Comment by rameshb444** [comment]
Hi andriantolie,

Thanks for your reply. 

Actually I have created account with different name "myaccount" and deployed contract with this account only.  
And I can transfer using cleos in terminal from below command.

./cleos --wallet-url http://localhost:8899 push action myaccount issue '["myaccount1", "100.0000 SYS", "memo" ]' -p eosio

But when I try to transfer this token from node and eosjs, it is showing 'eosio.token' does not exist. 

**So as per your suggestion, again I created eosio.token account and deployed contract with this account.
Now I can transfer from both terminal and also from node eosjs.**

Also I have one more doubt :  

As per the doc If I want to deploy contract, I need to read wasm , abi files and after that I need to setcode, setabi and deploy contract.


var binaryen = require('binaryen')
eos = Eos({keyProvider, binaryen})
wasm = fs.readFileSync('/home/eos/eos/contracts/hello/hello.wasm')
abi = fs.readFileSync('/home/eos/eos/contracts/hello/hello.abi')
 
// Publish contract to the blockchain
eos.setcode('ram', 0, 0, wasm) // @returns {Promise}
eos.setabi('ram', JSON.parse(abi)) // @returns {Promise}

eos.contract('ram').then(myaccount => {
	//myaccount.myaction
	console.log(myaccount);
});



**Is there any way to deploy contract directly from node eosjs instead of creating wasm and abi files from terminal?** 

Currently I am creating wasm and abi files from terminal from below commands.
**eosiocpp -o hello.wast hello.cpp
eosiocpp -g hello.abi hello.cpp**
**Can I create wasm and abi files directly from node eosjs?** 

Please let me know the correct way of deploying using node eosjs. Thanks

**Comment by andriantolie** [comment]
Which eosjs version that you used?

**Comment by rameshb444** [comment]
"eosjs version": "15.0.3"

**Comment by tricaricom** [comment]
Why does an eosio.token account have to exist?  I am having the same exact problem.

**Comment by songjim** [comment]
I am having the same exact problem. somebody can help ?

**Comment by halsaphi** [comment]
Closed as refers to old version of code.
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
