### ISSUE TITLE
Can I check current usage of shared memory file?

### ISSUE THREAD

**Issue by egonson** [EOSIO/eos#4488]
I found that if shared memory file were full, nodeos was killed.

Can I check current used amount of it?

Currently I set 40G size for that.

**Comment by roman-tik** [comment]
+1

**Comment by vjoke** [comment]
run your eos node with --plugin eosio::db_size_api_plugin, which will provide a url /v1/db_size/get, then you can get the detailed usage about the state db.

**Comment by egonson** [comment]
That's exactly what I wanted. I close this issue.
