### ISSUE TITLE
chain DB difference with another Peers

### ISSUE THREAD

**Issue by hsejin314** [EOSIO/eos#4491]
file : eos/plugins/chain_plugin/chain_plugin.cpp

In the line of 1034, some of Peers' DB has '0' value in value.size()
so that can not get in the below line

**Comment by andriantolie** [comment]
I just marked this down for reference before the code changes. The above file referred is referring to the latest commit in master as today: https://github.com/EOSIO/eos/blob/af02ebba5d5797b6dcc2f06befcfc584b07dc75f/plugins/chain_plugin/chain_plugin.cpp

**Comment by hsejin314** [comment]
It could be chain plugin problem, but more serious is chain DB is not perfectly match with serveral Peers
