### ISSUE TITLE
trust  problem in  exchange contract

### ISSUE THREAD

**Issue by AIYP1226** [EOSIO/eos#4493]
if someone deposits  his token in account of exchange,  and the holder of exchange  move all tokens away,
so how do we trust the holder of exchange ?

**Comment by oneroot001** [comment]
I also have this consern. When I test transfer token to the exchange contract, the owner can control the token as his will.Is there a mechanism like erc-20 that only the user can withdraw his token in the contract??

**Comment by halsaphi** [comment]
Closed as refers to old version of code. exchange contract has been deprecated.
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
