### ISSUE TITLE
push trouble

### ISSUE THREAD

**Issue by liyanhrxy** [EOSIO/eos#4498]
when push transaction Like Tthis :
`eos --print-request  push transaction '{"expiration": "2018-07-05T04:13:48.000","ref_block_num": 336909,"ref_block_prefix": 1176409106,"max_net_usage_words": 0,"max_cpu_usage_ms": 0,"delay_sec": 0,"context_free_actions": [],"actions": [{"account": "eosio.token","name": "transfer","authorization": [{"actor": "liyan","permission": "active"}],"data": "000000008069bc8b00a6823403ea3055400d0300000000000453595300000000056c6979616e"}],"transaction_extensions": [],"signatures": [],"context_free_data": []},["EOS8XsZF723pBgy1PWQyzzDY85qu5f5j4YfDeVf4pf87XnUWphjHa"],"cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f"'`
I got this: It is sure that the wallet is unlocked 
`Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"liyan","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys []`

**Comment by andriantolie** [comment]
`eos --print-request` => what is this tool you used to push the transaction? is that an alias of something else?

**Comment by liyanhrxy** [comment]
`eos` is a alias of `cleos`!
