### ISSUE TITLE
bid name bug,how can user get refund?

### ISSUE THREAD

**Issue by szdbetter** [EOSIO/eos#4499]
Account **gi3dmnjugqge** wants to bid name com, but he used transfer(instead of bid name) command to send EOS to system account: eosio.names ,
tx is:ca49a9b41316c2ba2bf8e79418bfb5389663f1a2f203992e97b7e14be5d1c7d3;
Now how the user get his 500 EOS back? That's almost his everything. 
Please advise how to fix #it, thanks
@jeremi @dbrock @guanqun @jmarca @andelf

**Comment by andriantolie** [comment]
eosio.names is owned by eosio@active, so as far as I know only a transaction signed by 2/3+1 producers will be able to take the eos out.

**Comment by szdbetter** [comment]
So how to opearte?like  claim it to ECAF ? could you please offer more information/

**Comment by ChristianDunst** [comment]
Hi szdbetter,
eosio github is for technical issues only. 
I suggest you try to get some help in the official EOS channel on telegram, which can be found here:
https://t.me/EOSproject
