### ISSUE TITLE
improve token parsing for users

### ISSUE THREAD

**Issue by robertkowalski** [EOSIO/eos#4500]
Hello folks,

thanks for eos and congrats to the launch!

I have a request which could make my life and the life of other users happier. 

A transaction with a token contains these fields in `action_trace.act.data`:

```
          "data": {
            "from": "scott",
            "to": "tokenxchange",
            "quantity": "1.0000 SYS",
            "memo": "12345"
          },
```

When a receiver wants to programatically verify incoming transfers, they have to parse the `quantity` field, `1.0000 SYS`. 

If they accept multiple tokens, they would write a regex to parse the quantity and token. This is very error prone, e.g., `/SYS$/` would also verify accept `ESYS`.

My suggestion is to add another field, e.g. `token` which contains the token without the quantity. In my example it would be `"token": "SYS"`.

Maybe that is not possible, another idea is to provide some parsing functionality in the RPCs. I see a lot of tickets regarding token transfer problems in the issue tracker, so I think this is an issue more users face.

Here is the full example TX for reference:

```
{
  "actions": [{
      "global_action_seq": 2132,
      "account_action_seq": 2,
      "block_num": 2099,
      "block_time": "2018-06-03T15:29:33.000",
      "action_trace": {
        "receipt": {
          "receiver": "tokenxchange",
          "act_digest": "3a49a62f23db41c4ed8a8fa52509a04056c8afdcb15de7544a430b2cadfbaf68",
          "global_sequence": 2132,
          "recv_sequence": 3,
          "auth_sequence": [[
              "scott",
              9
            ]
          ],
          "code_sequence": 1,
          "abi_sequence": 1
        },
        "act": {
          "account": "eosio.token",
          "name": "transfer",
          "authorization": [{
              "actor": "scott",
              "permission": "active"
            }
          ],
          "data": {
            "from": "scott",
            "to": "tokenxchange",
            "quantity": "1.0000 SYS",
            "memo": "12345"
          },
          "hex_data": "00000000809c29c2a0d8340df5a920cd10270000000000000453595300000000053132333435"
        },
        "elapsed": 2,
        "cpu_usage": 0,
        "console": "",
        "total_cpu_usage": 0,
        "trx_id": "05fd45b61df815a4cdeb768e732adb292500b2399517fc9c98b6e6b136d7a4d1",
        "inline_traces": []
      }
    }
  ],
  "last_irreversible_block": 2543
}
```

**Comment by jgiszczak** [comment]
Use a better regex, such as `/[ ]SYS$/`

**Comment by robertkowalski** [comment]
thank you for your time and response.

thats not the point of my issue, but that its easy to use the wrong regex in general for users.

**Comment by tbfleming** [comment]
Here's the trade-off:
* `"1.0000 SYS"` is more readable and easier to type than the alternative
* `{"symbol":"SYS", "precision":4, "value":"10000"}` is deceptively easier to parse. I say deceptively because the same developers who would mess up a regexp are likely to make the 56-bit precision mistake when dealing with assets in JSON and in JS.

We're doubling-down on the first option. Some types slipped through the cracks (e.g. `extended_asset` and `extended_symbol`) and ended up with the longer syntax. We're going to move those to the short form.
