### ISSUE TITLE
"Loading the Bios Contract" failed

### ISSUE THREAD

**Issue by grabastart** [EOSIO/eos#4509]
@bytemaster could you take a look at the following issue?
Summary:
eosio was built successfully on my windows 10 running ubuntu (windows subsystem for linux) last night.
out of 36 tests, other than p2p_dawn515_test failed,
restart-scenario-test-resync failed,
restart-scenario-test-hard_replay failed,
and restart-scenario-test-none failed
all others Passed. 

Initial trying of eosio:
(a) running a single node of blockchain in background
nodeos -x eosio (with two plugin of "chain" and "history")
Outcome:
ps indicates nodeos running among two other processes.

(b) trying out wallet
# create wallet
cleos wallet create
Outcome: success
proceeded with creating private and public key pairs
Outcome: success (verified with subcommand of keys)
ensuring and confirming this default wallet is unlocked

(c) attmpted to "Loading the Bios Contract"
my current path is "eos/build" already.
/{path}/cleos set contract eosio ./contracts/eosio.bios -p eosio
Result:
It generated errors, see attached file.

![failure-in-loading-the-bios-contract](https://user-images.githubusercontent.com/2821724/42335498-9806b9b2-804e-11e8-8120-a8d2d174cc17.png)

Thanks in advance.

**Comment by jgiszczak** [comment]
Follow the first half of the error message.  Your wallet is unlocked but is missing the required key.

**Comment by grabastart** [comment]
@jgiszczak but the default wallet has two pairs of public and private keys as indicated by the command of
cleos wallet private_keys 
(and if this subcommand is named "bothkeys" it would be more appropriate because it returns the key pairs instead of just priviate key(s)).
  
Could eleos be confused by the two pairs of keys?  Or?

Thanks.

**Comment by grabastart** [comment]
@jgiszczak, ok, thanks, since there are multiple genesis.json files laying around under eosio installation, where is this genesis.json file you mentioned located on my eosio installation folder?

**Comment by jgiszczak** [comment]
If you launched nodeos without specifying a data directory or a genesis file, it wrote one to `~/.local/share/eosio/nodeos/config`.  The matching private key for that default public key is `5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3`.  Be sure never to use that key for any mainnet account.

**Comment by grabastart** [comment]
Are you saying simply launching nodeos without any parameters, that is, 
./{path4nodeos}/nodeos
then, load bios contract as in
/{path}/cleos set contract eosio ./contracts/eosio.bios -p eosio
would work?

Thanks.

**Comment by jgiszczak** [comment]
Yes, an account is required.  The account you should load `eosio.bios` into is `eosio`.

**Comment by grabastart** [comment]
@jgiszczak 
I stepped back from loading the Bios Contract.
Right now I want to create a new local account first.  However, the following command failed
./cleos create account eosio dli EOS5....{restOfPubKey}
error message:
"No available wallet" but the default wallet has been created and key generated and private key has been imported and the wallet is open and unlock.

How to fix it?

Thanks in advance.

**Comment by grabastart** [comment]
@jgiszczak 
for creating a new account, 
./cleos create account eosio dli EOS5....{restOfPubKey}
producing errors.
But when I added -v switch for cleos it now added the following error:  
transaction declares authority '{"actor":"eosio","permission":"active"}', but does not have signatures for it.

and I then searched for this string, @bytemaster  indicated the following on May 14 on a fix but in his code he also included a key and I'm not sure which file,  

another person posted:
from
[{"permission":{"actor":"eosio","permission":"active"},"weight":1}]
to
[{"permission":{"actor":"eosio","permission":"eosio.code"},"weight":1}]

what command and options to run to make the above change?

**Comment by grabastart** [comment]
@jgiszczak 
this private key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 for
default public key EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
has now been imported into wallet.
+ "cleos wallet list" now includes the eosio public key of EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV as well.
+ nodeos started with -e -p Options in the background and it seems producing blocks.
+ wallet is open and unlock.

But, both
cleos create account eosio mynewaccount {mynewpublickey}
hangs (no response even after two minutes)
cleos set contract eosio ./contracts/eosio.bios -p eosio
also hangs  (no response even after three minutes)

What caused this problem and how to resolve it?

Thanks.

**Comment by jgiszczak** [comment]
Make sure you know which ports keosd and nodeos are running on and specify their URLs in the cleos command line, e.g. `cleos -u http://127.0.0.1:88xx --wallet-url http://127.0.0.1:8900` where '88xx' is the port on which nodeos is running.  If you manually launched keosd at any point, it will not be running on the port cleos expects to find it, and so you will need to specify the full URL to access it.

**Comment by jgiszczak** [comment]
`sudo netstat -tlp` or more verbosely `sudo netstat --tcp --listening --program`.

You need the public key of `eosio` to be in the wallet, not the key of the account you are attempting to create.  It's `eosio` that will be signing the account creation transaction.

**Comment by grabastart** [comment]
the public key and its corresponding private key for eosio has been imported into wallet, see the following screen shot, 
https://user-images.githubusercontent.com/2821724/42550935-a1406994-84a2-11e8-865b-fd3e4cbe21cc.png

I've also tried
cleos -u http://127.0.0.1:8888 --wallet-url http://127.0.0.1:8899 create account eosio myaccount {eosiopublickey} also failed.

Something exceedingly weird seems happening here.
