### ISSUE TITLE
"eosiocpp" command not found: installed via docker

### ISSUE THREAD

**Issue by KennyLiu25775** [EOSIO/eos#4510]
Hey guys I installed EOS using docker and the program won't recognize eosiocpp command and it keeps saying `eosiocpp: command not found.` Appreciate it if anyone could help me!!
![image](https://user-images.githubusercontent.com/11808716/42341786-1c02e0de-8049-11e8-8a4d-bbfa6c0969b7.png)

**Comment by eosbet-io** [comment]
Hello, that's because the standard `eosio/eos:latest` does not contain eosiocpp to make the images more lightweight. You need to do this:

```
cd Docker/dev
docker build -t eosio/eos-dev .
```

This should install eosiocpp via Docker :)

**Comment by KennyLiu25775** [comment]
thank you !!! :)

**Comment by ekkis** [comment]
@eosbet-io and I would run the command how? from the docker_nodeosd_1 container? I see a new docker image created `eosio/eos-dev` but there's nothing in the `docker-compose.yml` that kicks that off.  how would I use it then, to deploy a contract?

**Comment by ekkis** [comment]
I got it to work and figured out a whole workflow for Docker.  documented it here: https://medium.com/@ekkis/eos-development-on-docker-3f4eb9b680ec

**Comment by mariam-crissi** [comment]
I am also facing the issue.But I have it from the source.How can I resolve the issue in this case?

**Comment by ekkis** [comment]
if you have the source, you just need to build it.  this thread is concerned with Docker deployments though so you may do better asking elsewhere

**Comment by KennyLiu25775** [comment]
@ekkis hey Ekkis, did you also have the empty abi table issue when you use eosiocpp after docker build EOS? The eosiocpp command always generate an empty table in abi file just like this 
![image](https://user-images.githubusercontent.com/11808716/43538214-3ceb6270-9576-11e8-978f-da32c9b8767f.png)
I tried to add the //@abi table but it still does not work...

**Comment by huainanhaoyuelengqianshan** [comment]
> Hello, that's because the standard `eosio/eos:latest` does not contain eosiocpp to make the images more lightweight. You need to do this:
> 
> ```
> cd Docker/dev
> docker build -t eosio/eos-dev .
> ```
> This should install eosiocpp via Docker :)

I can't understand "cd Docker/dev". Could you give me an example? Thank you.
