### ISSUE TITLE
Ensure that you have eosio::chain_api_plugin added to your node's configuration!

### ISSUE THREAD

**Issue by hyqsfaf** [EOSIO/eos#4514]
cleos --wallet-url http://127.0.0.1:1234 create account  ...

prompt：
Error 3110001: Missing Chain API Plugin
Ensure that you have eosio::chain_api_plugin added to your node's configuration!
Error Details:
Chain API plugin is not enabled

**Comment by andriantolie** [comment]
Check your nodeos config.ini, do you have `plugin = eosio::chain_api_plugin`?

**Comment by hyqsfaf** [comment]
I configured

**Comment by andriantolie** [comment]
Does it load when you start your nodeos? 
If it loads, you will see the following line at the beginning of your nodeos log
```
...
3276134ms thread-0   chain_api_plugin.cpp:75       plugin_startup       ] starting chain_api_plugin
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/abi_bin_to_json
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/abi_json_to_bin
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_abi
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_account
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_block
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_block_header_state
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_code
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_currency_balance
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_currency_stats
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_info
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_producers
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_required_keys
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_table_rows
3276134ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/push_block
3276176ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/push_transaction
3276176ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/push_transactions
...
```

**Comment by hyqsfaf** [comment]
yes   is Running。

$ ./cleos create account eosio sean EOS69ZZXxm8ZrrjB3J93LT9Wgu4nWRbpVuo7qspk393SDsNaSSYfW EOS8SvNZAW7pwzQjGkeG6e46mwiczMP9kkrCifASqGM8qkVqnu8QR
Error 3110001: Missing Chain API Plugin
Ensure that you have eosio::chain_api_plugin added to your node's configuration!
Error Details:
Chain API plugin is not enabled
mac:cleos kcmac$ ./cleos wallet list

**Comment by andriantolie** [comment]
In localhost:8888?

**Comment by hyqsfaf** [comment]
no is http://127.0.0.1:1234.  
8888  

nodeos  Can not run

**Comment by andriantolie** [comment]
I see so you have your wallet and nodeos running on the same port? Coz I see you put http://127.0.0.1:1234 as your --wallet-url param

If you started your nodeos in http://127.0.0.1:1234, then you will also need to pass that url to cleos
`cleos -u http://127.0.0.1:1234 --wallet-url http://127.0.0.1:1234 `

**Comment by hyqsfaf** [comment]
mac:cleos kcmac$ cleos wallet keys
[
  "EOS65eJhviCwF2t4dRRExJxVoiKaqjH2Fk3TdvgzVQYyxTmyVyixs",
  "EOS7EFUN5QuQwRR9xiXFUA5VgrtDxG59KE7FZmftBDYFkv5WzcdBb",
  "EOS83raguWAMFtzyR67oGy6p3vKF7MDhzAaKWZxLuY5Pkf2KmUcs5"
]
mac:cleos kcmac$ cleos create account eosio currency EOS7EFUN5QuQwRR9xiXFUA5VgrtDxG59KE7FZmftBDYFkv5WzcdBb EOS83raguWAMFtzyR67oGy6p3vKF7MDhzAaKWZxLuY5Pkf2KmUcs5


Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
mac:cleos kcmac$

**Comment by andriantolie** [comment]
And what is your eosio active key? Please share `cleos get account eosio`

**Comment by hyqsfaf** [comment]
mac:cleos kcmac$ cleos get account eosio -j
{
  "account_name": "eosio",
  "head_block_num": 10393,
  "head_block_time": "2018-07-06T08:02:40.000",
  "privileged": true,
  "last_code_update": "1970-01-01T00:00:00.000",
  "created": "2018-06-01T12:00:00.000",
  "ram_quota": -1,
  "net_weight": -1,
  "cpu_weight": -1,
  "net_limit": {
    "used": -1,
    "available": -1,
    "max": -1
  },
  "cpu_limit": {
    "used": -1,
    "available": -1,
    "max": -1
  },
  "ram_usage": 2724,
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
            "weight": 1
          }
        ],
        "accounts": [],
        "waits": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
            "weight": 1
          }
        ],
        "accounts": [],
        "waits": []
      }
    }
  ],
  "total_resources": null,
  "self_delegated_bandwidth": null,
  "refund_request": null,
  "voter_info": null
}

**Comment by andriantolie** [comment]
You need to import the private key of EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV then

**Comment by hyqsfaf** [comment]
Unable to import

mac:cleos kcmac$ cleos wallet import EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
Error 3010003: Invalid private key
Private key should be encoded in base58 WIF
Error Details:
Invalid private key: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV

**Comment by jgiszczak** [comment]
Contains multiple common questions, all answered.
