### ISSUE TITLE
RAM price calculation does not match the formula in the Bancor Protocol paper

### ISSUE THREAD

**Issue by CharlesJu1** [EOSIO/eos#4515]
Here is the formula in the [Bancor Protocol white paper](https://storage.googleapis.com/website-bancor/2018/04/01ba8253-bancor_protocol_whitepaper_en.pdf)

<img width="1255" alt="screen shot 2018-07-06 at 1 09 42 pm" src="https://user-images.githubusercontent.com/1816882/42360906-28273682-811e-11e8-99b6-995f4f35d4e6.png">

In the formula, the balance and supply are the current value before the buy and sell action.

Here is the code from exchange_state.cpp.
```
asset exchange_state::convert_to_exchange( connector& c, asset in ) {

      real_type R(supply.amount);
      real_type C(c.balance.amount+in.amount);
                                   ^^^^^^^^^^^^ This amount should not be added. 
      real_type F(c.weight/1000.0);
      real_type T(in.amount);
      real_type ONE(1.0);

      real_type E = -R * (ONE - std::pow( ONE + T / C, F) );
      //print( "E: ", E, "\n");
      int64_t issued = int64_t(E);

      supply.amount += issued;
      c.balance.amount += in.amount;

      return asset( issued, supply.symbol );
   }

   asset exchange_state::convert_from_exchange( connector& c, asset in ) {
      eosio_assert( in.symbol== supply.symbol, "unexpected asset symbol input" );

      real_type R(supply.amount - in.amount);
                                  ^^^^^^^^^^^^ This amount should not be subtracted. 
      real_type C(c.balance.amount);
      real_type F(1000.0/c.weight);
      real_type E(in.amount);
      real_type ONE(1.0);


     // potentially more accurate: 
     // The functions std::expm1 and std::log1p are useful for financial calculations, for example, 
     // when calculating small daily interest rates: (1+x)n
     // -1 can be expressed as std::expm1(n * std::log1p(x)). 
     // real_type T = C * std::expm1( F * std::log1p(E/R) );
      
      real_type T = C * (std::pow( ONE + E/R, F) - ONE);
      //print( "T: ", T, "\n");
      int64_t out = int64_t(T);

      supply.amount -= in.amount;
      c.balance.amount -= out;

      return asset( out, c.balance.symbol );
   }

```
It seems the C in convert_to_exchange is not set according to the formula in the paper. The same for the R in convert_to_exchange.

Another question is about the setting of CW. Weight is set to 0.5. Why it is divided by 1000 again? 
`F(c.weight/1000.0);`

**Comment by vjoke** [comment]
you can refer to #3032

**Comment by taokayan** [comment]
This is by design. The "in.amount" term is used to calculate the price at the worst case point, in such way that you can't make any profit by buying ram and selling immediately. For example, when you buy ram, the price you need to pay is the price after you buy not the price before you buy. When you sell ram, the price you get is the price after the ram is sold.

**Comment by CharlesJu1** [comment]
If there is only one user buying a big chunk of RAM and selling it afterward, then the user's token balance should be the same as before except for the 1% ram fee. However, what you described sounds like make the user buy high and sell low, which will reduce the user's token balance.

**Comment by taokayan** [comment]
I agree that in the current model if you buyram in small chunks, you'll end up having slightly more RAM. However, according to the formula, the different won't be that much unless you are buying with really big amount, for example, using 1 million EOS to buy RAM.
