### ISSUE TITLE
Error 3090004: missing required authority

### ISSUE THREAD

**Issue by jasoncodingnow** [EOSIO/eos#4522]
so, I followed the steps here: https://developers.eos.io/eosio-cpp/docs/token-tutorial
after I created my account `hello.code`, I deployed `eosio.token` contract:
`cleos --wallet-url=http://localhost:8899 set contract hello.code build/contracts/eosio.token -p hello.code`

then I tried `cleos --wallet-url=http://localhost:8899 push action hello.code create '[ "eosio", "1000000000.0000 SYS"]' -p hello.code`, **everything worked well**. 

After about an hour, I unlocked my wallet, then try `cleos --wallet-url=http://localhost:8899 push action hello.code issue '[ "user", "100.0000 SYS", "memo" ]' -p hello.code`, 

but it shows this:

`Error 3090004: missing required authority
Ensure that you have the related authority inside your transaction!;
If you are currently using 'cleos push action' command, try to add the relevant authority using -p option.`

checked my wallet did unlock. So how to fix this?

**Comment by jgiszczak** [comment]
The instructions to create the 'user' account are on [this](https://developers.eos.io/eosio-cpp/docs/introduction-to-smart-contracts) page.  The token instructions will be updated with a reference to them, for people not running the tutorials in order.
