### ISSUE TITLE
[Feature] return buyram result with ram_bytes info

### ISSUE THREAD

**Issue by hupengbuaa** [EOSIO/eos#4524]
I think it's necessary to return `ram_bytes` info when calling `buyram` action.

**Comment by andriantolie** [comment]
Hi @hupengbuaa, eos architecture does not allow anything to be returned by an action. You can note the amount that you have before you bought, and compared it with the amount you have after you bought it to get the amount of RAM you successfully bought

**Comment by hama** [comment]
but we can't know the RAM history

**Comment by hupengbuaa** [comment]
@andriantolie  `buyrambytes`  and `sellram` return the info of eos transfer to `eosio.ram` and `eosio.ramfee`, which is very helpful. I do need the info of `bytes` return by `buyram`.

**Comment by andriantolie** [comment]
It's because eos transfer to `eosio.ram` is an inline action, therefore it has the payload of how much eos is being transferred inside the action.
