### ISSUE TITLE
Deploy Eosio.msig Contract error

### ISSUE THREAD

**Issue by onepiecelyk** [EOSIO/eos#4529]
when i ```Deploy Eosio.msig Contract```
back 
```

Error 3090003: provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
```
after  i use  
```
cleos wallet import 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
```
then back 
```main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)```
what shoud i do ? 
thanks

**Comment by andriantolie** [comment]
What is the private key of your eosio.msig account?
