### ISSUE TITLE
Permissions abuse by contract update

### ISSUE THREAD

**Issue by Sindbag** [EOSIO/eos#4531]
Hey guys, I have been thinking about permissions for token manipulations for external contract given by user (calling updateauth, for example).

But, due to ease of contract change, the contract code could be replaced with fraudulent functionality, so the given permission could be used to transfer money to the thief.

Is there a way to prevent or track this?

Seems like a bug or misbehaviour for me.

**Comment by jgiszczak** [comment]
See #6168.
