### ISSUE TITLE
It consumes 31 times more RAM than I expected.

### ISSUE THREAD

**Issue by cluestudio** [EOSIO/eos#4532]
### Background
sizeof(material) is just 8 bytes.
but it spent 248 bytes of ram.

```cpp
//@abi table material i64
struct material {
    uint16_t id = 0;
    uint16_t code = 0;
    uint32_t saleid = 0;

    uint64_t primary_key() const {
        return id;
    }

    uint64_t by_saleid() const {
        return saleid;
    }

    EOSLIB_SERIALIZE(
            material,
            (id)
            (code)
            (saleid)
    )
};

typedef eosio::multi_index< N(material), material,
    indexed_by< N(saleid), const_mem_fun<material, uint64_t, &material::by_saleid> >
> material_table;

```

### It is not reasonable to consume more RAM than the size of the table.
The developer can not control the usage except the table size. In addition, developers can not predict how much RAM will be consumed.

As a result of the test, it seems that about 110 bytes are consumed every time the secondary index is added. Every table must have at least one primary key, so at least 110 bytes per row is consumed.

As you know, RAM costs are huge. The specifications for ram consumption are very important to dApp developers, but we do not know how they are charged.

### How we can reduce ram usage?
EOS emphasizes reduce the use of RAM, but it's basically a lot consumed, it's impossible to use less. The only way to use less RAM is to reduce the row. This approach will hinder the development of various dApp.

**Comment by cluestudio** [comment]
As a result of the test, it seems that about 110 bytes are consumed every time the secondary index is added. Every table must have at least one primary key, so at least 110 bytes per row is consumed.

**Comment by tbfleming** [comment]
Here's how it's calculated:
* If the combination of code/scope/table doesn't already exist, then create it and bill `config::billable_size_v<table_id_object>` (112 bytes). i.e. there's a penalty for using multiple scopes.
* Bill `config::billable_size_v<key_value_object>` for the row's overhead (indexing): 112 bytes.
* Bill for the size of the row's data (8 bytes).
* Plus 8 bytes from somewhere. I must have missed something scanning through the database code.

Total = 240

**Comment by tbfleming** [comment]
@sergmetelin this should probably go into the documentation

**Comment by cluestudio** [comment]
(112 bytes * count of indexes) added to every row. 
It means every row is charged 0.1K at least. 
And also every additional secondary index is charged 0.1K more.

I just want to write only 8 bytes.
I think it is not reasonable.

**Comment by tbfleming** [comment]
A lot of apps store vectors of small objects in a single row. That reduces cost per object.

**Comment by taokayan** [comment]
```If a new account (name A) is created, the first account (name B) which transfer EOS to A, will cost much ram.``` This is correct.

```Is it the same problem, B help A to create table, that cost B ram```  This depends on the contract implementation. RAM can be billed by the contract owner or the account who executes the contract.

**Comment by cluestudio** [comment]
I did not expect the "rows in row" style to be possible. It works. 
Some features are likely to be replaced by this feature.
Thanks.
