### ISSUE TITLE
updateauth action from contract

### ISSUE THREAD

**Issue by Pdsmithjp** [EOSIO/eos#4533]
I am unable to generate an authorization from a JSON, so that a contract can send an updateauth  action. Building an authorization requires eosio::chain::public_key_type, which i can't include as eosiocpp wont compile 'float.h'. Any way around this?

**Comment by andriantolie** [comment]
You should include public_key_type defined in contracts/eosiolib/types.h and it doesn't require float.h

**Comment by Pdsmithjp** [comment]
There is no public_key_type defined in types.h. Only public_key struct. The chain version links to fc::crypto::public_key which has methods for converting a base58 key string to public_key type (data[34])

**Comment by andriantolie** [comment]
Anything inside libraries/chain contains dependencies that might not be supported by Web Assembly. I don't think it's safe to include those files.

If you pass the public key to your user-generated action (not the inline action), the abi serializer will automatically convert your public key string to public key type (and I guess this is what usually most of the people do).
