### ISSUE TITLE
Problem in creating account and loading eosio.bios contract

### ISSUE THREAD

**Issue by grabastart** [EOSIO/eos#4538]
Hi,

Here's the details.

my OS: windows 10 running Ubuntu 16.04 via Windows Subsystem for Linux

eosio info:
{
  "server_version": "90fefdd1",
  "chain_id": "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f",
  "head_block_num": 6763,
  "last_irreversible_block_num": 6762,
  "last_irreversible_block_id": "00001a6ac485dc05fd5f136d55f95cee2fec5a7afab5d341b56af39fabe5c5c7",
  "head_block_id": "00001a6b5f67b6f37b0ca68549d113ce9c605c5e97137882a2781a34123a5deb",
  "head_block_time": "2018-07-08T13:47:56.000",
  "head_block_producer": "eosio",
  "virtual_block_cpu_limit": 173024443,
  "virtual_block_net_limit": 908999456,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576
}

here's how nodeos was started with -e -p Options and with three plugins of wallet, chain and history and it runs in the background.

wallet and keys:
a new key was generated and imported into wallet
The private key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 for
default public key EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
has also been imported into wallet.
"cleos wallet list" now includes the eosio public key of EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV as well.

additional info about wallet and keys:
previously, I've created keys and imported them but they failed to create a new account, thus, I renamed default.wallet and newly created wallets.  see below for the files ~/eosio-wallet folder,
config.ini
defaultOLD2.walletOLD2
defaultOLD.walletOLD
default.wallet
perwinkle.wallet
wallet2OLD.wallet2OLD
Their permission for the user is rw none for group and all.

and wallet is open and unlock.

But, both
cleos create account eosio mynewaccount {mynewpublickey}
hangs (no response even after two minutes)
cleos set contract eosio ./contracts/eosio.bios -p eosio
also hangs (no response even after three minutes)

What caused this problem and how to resolve it?

Thanks in advance.

**Comment by cravis87** [comment]
First of all there should be two keys, owner and active, you need those both to create account.

Follow this,
https://infinitexlabs.com/first-steps-in-eos-blockchain-development/

**Comment by andriantolie** [comment]
Is your nodeos producing block?

**Comment by wm84** [comment]
@andriantolie  yes it seems to be producing blocks.  @cravis87 according to cleos man page, the active key is optional.

**Comment by grabastart** [comment]
yes, all these basic functionality including get block {blockNumber} works and yes, nodeos runs on localhost:8888 while I've changed the default wallet url from the same port of 8888 to 8899.
and the account creation process even check account name if it contains numbers it would complain about bad format but what really puzzle me is that such ESSENTIAL function of being able to create an account failed.  
Another thing is, the nodeos frequently complained about inconsistent blocks, so, I had to frequently either run --hard-replay-blockchain or --delete-all-blocks and the second option is not really practical in any production environment.

**Comment by taokayan** [comment]
What's the exact command you used and what's the exact output you saw?

**Comment by grabastart** [comment]
@taokayan see the following screen shot:
![cleos-create-account-hangs](https://user-images.githubusercontent.com/2821724/42550935-a1406994-84a2-11e8-865b-fd3e4cbe21cc.png)

**Comment by taokayan** [comment]
are you using native Linux OS? and are you running nodeos and producing blocks already?

**Comment by grabastart** [comment]
@taokayan 
my OS: windows 10 running Ubuntu 16.04 via Windows Subsystem for Linux (see my op above).
the `ps` command indicated nodeos was running and yes it's producing blocks ( `cleos get block #` would return a particular block info ).

With 4 billion funding, I hope EOSIO can really allocate some serious resources to make its blockchain platform reliable for major OSs.

**Comment by halsaphi** [comment]
Closed as refers to old version of code. Block.one is working hard to resolve all issues as they occur.
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
