### ISSUE TITLE
Unable to build on OSX

### ISSUE THREAD

**Issue by atteeela** [EOSIO/eos#454]
As per https://github.com/EOSIO/eos/releases instructions

$ bash build.sh darwin

>>> ARCHITECTURE "darwin"
build.sh: line 81: cmake: command not found
make: *** No targets specified and no makefile found.  Stop.

**Comment by pavybez** [comment]
There is a short coming in the build.sh in root eos folder. I am making a fix. In the mean time you could edit build.sh and set INSTALL_DEPS=1.

**Comment by thomasbcox** [comment]
I believe is was fixed by #455 ?

**Comment by pavybez** [comment]
Yes.
