### ISSUE TITLE
import eosio private keys error

### ISSUE THREAD

**Issue by onepiecelyk** [EOSIO/eos#4546]
hi guys,
when i write ```cleos wallet import 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3```
back 
```
12318ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)

```
Why is this? pls！

**Comment by tyGavinZJU** [comment]
i met the same problem as yours, when i do 

> cleos wallet import 5KX1ViES7RVkU76nt43BHNPTVydSj7d8ktegdgC8b8HCNDRBsXu

is there some problem when import some certain private keys?

**Comment by andriantolie** [comment]
Can you please try again with your keosd started with `--verbose-http-errors`? Let's gather more evidence first before we jump to premature conclusion. Thanks!

**Comment by tyGavinZJU** [comment]
I removed all the keys in my wallet, the problem solved. So i guess the problem may be importing the same private key twice. And then I try to import the same key twice, the same error occurs.

**Comment by whitmanc** [comment]
Problem was the keys were already imported for me

**Comment by andriantolie** [comment]
Yes, normally the error message is duplicate public key imported. The next release will have a better concise error message when `--verbose-http-errors` is not enabled!

@onepiecelyk have you figured out your problem?

**Comment by onepiecelyk** [comment]
@andriantolie yes ，The problem is solved ，thank you
