### ISSUE TITLE
Error 3050003: eosio_assert_message assertion failure, eat assert errors in a contrast

### ISSUE THREAD

**Issue by wsdfz** [EOSIO/eos#4547]
Is it by design?

It causes it is hard to debug in mainnet.

When a dapp owner want to know what's wrong with the dapp, the user who find the bug only can give him this assert failure message.

I prefer the old way that can print actual assert messages.

**Comment by andriantolie** [comment]
The old way is still there, you just need to start your nodeos with `--verbose-http-errors` argument. :)

**Comment by KennyLiu25775** [comment]
@andriantolie  Hi could you be little more specific on how to use the --verbose-http-errors command you were talking about? i am using the jungle testnet and it is not allowing me to debug it:
![image](https://user-images.githubusercontent.com/11808716/42729186-fdf8ec6c-8784-11e8-91ea-2d29ab0ba3a0.png)

**Comment by bitcoiners** [comment]
I get the same error and even with --verbose-http-errors the message is unclear.
cleos push action eosio claimrewards eosiodetroit -p eosiodetroit@claims
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: read
pending console output:
