### ISSUE TITLE
cleos wallet unlock does not allow to input password in prompt

### ISSUE THREAD

**Issue by Mourdraug** [EOSIO/eos#4548]
Whenever I'm trying to unlock wallet it instantly passes password prompt and returns:
```
$ cleos wallet unlock
password: Error 3120005: Invalid wallet password
Are you sure you are using the right password?
```
Which forces me to use --password option, which is obviously a security issue.

**Comment by andriantolie** [comment]
This shouldn't happen. cleos wallet unlock will give you chance to input your password. Is this just happened to you recently?

**Comment by Mourdraug** [comment]
I actually never used cleos and keosd before, only scatter. I'm going through Eosio developer guide and I'm working on provided docker image, I guess that either docker or alias to cleos might be the cause here.

**Comment by andriantolie** [comment]
Ah so that cleos, is the one from docker image?

Then I guess you just miss `-i` argument in your `docker exec`, `-i` means enable interactive interaction with docker

**Comment by Mourdraug** [comment]
Ah, that works, thanks. I'd say `-i` agument should be included in docker quickstart (https://developers.eos.io/eosio-nodeos/docs/docker-quickstart) in that case.

**Comment by andriantolie** [comment]
Good idea. I will submit an edit suggestion on developers.eos.io. 
Even better, `-it` instead of just `-i` will allow you to type the password without causing it to be visible
