### ISSUE TITLE
!wast.empty(): no wast file found

### ISSUE THREAD

**Issue by KennyLiu25775** [EOSIO/eos#4558]
Hey guys so  i installed EOS using docker and when i try  to deploy the contract to the jungle testnet it keeps saying the error: `Reading WAST/WASM from contracts/vcctoken/vcctoken.wast...
403635ms thread-0   main.cpp:2712                 main                 ] Failed with error: Assert Exception (10)
!wast.empty(): no wast file found contracts/vcctoken/vcctoken.wast`

![image](https://user-images.githubusercontent.com/11808716/42479632-ab80e5f6-838e-11e8-914b-568aad03db4e.png)

appreciate it if anyone could help me! Thanks

**Comment by compjotr** [comment]
Does this help you? https://github.com/EOSIO/eos/issues/4598#issuecomment-404442721

**Comment by KennyLiu25775** [comment]
thank you @compjotr  that was helpful
