### ISSUE TITLE
mongo_db_plugin unable to capture all accounts and transactions

### ISSUE THREAD

**Issue by elnoxvie** [EOSIO/eos#4561]
Sorry if i opened an unnecessary issue. There aren't much information about the mongo_db_plugin so i am opening an issue here to get some help.
so i was testing the latest Gh#3030 enable mongodb on release 1.1. 
I am under an impression that it is supposed to track all the accounts & transactions. However, after finishing the installation and running the nodeos, all i see from the actions, transactions are all that are related to eosio account only. 

so I was wondering if this is what the mongo_db_plugin supposed to be? or there are some configuration that i have missed. 

Thanks.

**Comment by dhaneshvb** [comment]
Did you add the mongodb_plugin into the config?

**Comment by heifner** [comment]
The mongo_db_plugin currently creates the following collections:

**accounts**
- This only keep track of contract ABI set on an account. Used internally by the mongo_db_plugin to convert hex data of action data into json for storage into mongo. Without the ABI all the action data would be in hex form and more difficult for end users to decode/query.

**actions**
- All actions

**block_states**
- All block_states

**blocks**
- All blocks
-- Marked with irreversible = true when irreversible

**transaction_traces**
- All transaction traces

**transactions**
- All transactions
-- Marked with irreversible = true when irreversible

**Comment by elnoxvie** [comment]
@heifner Glad to have your reply. Is it possible to capture all accounts and transactions using mongo_db_plugin? 
I don't see any data other than the eosio related after synching for an hour. Not sure what is the issue.

**Comment by heifner** [comment]
All accounts and all transactions are included. Currently, there is no filter capability.

**Comment by elnoxvie** [comment]
@heifner thanks. It seems like the issue is due to genesis and peers list not responding. It's working now.
