### ISSUE TITLE
how to connect EOS mainnet?

### ISSUE THREAD

**Issue by vaneyli** [EOSIO/eos#4563]
How to connect EOS mainnet?  Is there a IP list of main nodes?
I found the EOS New York  in the https://eosmeta.io/bpinfo/eosnewyorkio .   

May I use the real IP of https://bp.eosnewyork.io to connect mainnet?

**Comment by andriantolie** [comment]
You can connect to any node that is connected to the mainnet as long as you know the IP address.
For eosnewyorkio that you mentioned above, you can see their api node url in their website (right hand corner -> transparency -> bp.json)

**Comment by andriantolie** [comment]
http://bp.eosnewyork.io/bp.json for convenience
