### ISSUE TITLE
Is that true nodeos process can only consume single CPU? 

### ISSUE THREAD

**Issue by liliyongleo** [EOSIO/eos#4568]
Is that true "nodeos" process can only consume single CPU?  
When we do the performance benchmark, we saw that the CPU% for the "nodeos" process is up to 100%. 

  If that is ture, there is no need to assign more CPU to the Super Node?   Any performance tips regarding cpu utilization? Thanks.

**Comment by heifner** [comment]
Correct. nodeos is currently single threaded.

**Comment by kaidiren** [comment]
when multiple threads?
