### ISSUE TITLE
push_transaction error

### ISSUE THREAD

**Issue by XieWeiZM** [EOSIO/eos#4569]
FC Exception encountered while processing chain.push_transaction: 3090003 unsatisfied_authorization: provided keys, permissions, and delays do not satisfy declared authorizations
transaction declares authority '{"actor":"btbtest2","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms
    {"auth":{"actor":"btbtest2","permission":"active"},"provided_delay":0,"delay_max_limit_ms":3888000000}
    thread-0  authorization_manager.cpp:405 check_authorization

**Comment by taokayan** [comment]
You need to import the private key of btbtest2@active into your wallet before pushing the transaction.
