### ISSUE TITLE
Docker/README error

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#457]
/data/store/eos/contracts/exchange# docker exec docker_eos_1 eosc contract exchange contracts/exchange/exchange.wast contracts/exchange/exchange.abi
ERROR: RequiredError: Subcommand required
Command Line Interface to Eos Daemon
Usage: eosc [OPTIONS] SUBCOMMAND

Options:
  -h,--help                   Print this help message and exit
  -H,--host TEXT=localhost    the host where eosd is running
  -p,--port UINT=8888         the port where eosd is running
  --wallet-host TEXT=localhost
                              the host where eos-walletd is running
  --wallet-port UINT=8888     the port where eos-walletd is running
  -v,--verbose                output verbose messages on error

Subcommands:
  create                      Create various items, on and off the blockchain
  get                         Retrieve various items and information from the blockchain
  set                         Set or update blockchain state
  transfer                    Transfer EOS from account to account
  wallet                      Interact with local wallet
  benchmark                   Configure and execute benchmarks
  push                        Push arbitrary transactions to the blockchain

**Comment by dskvr** [comment]
The correct command is `docker exec docker_eos_1 eosc set contract exchange contracts/exchange/exchange.wast contracts/exchange/exchange.abi`, however, unless you already have the compiled wasm this wouldn't work anyways. Please see issue #460

**Comment by tlightsky** [comment]
use the Dockerfile from:https://github.com/EOSIO/eos/pull/482,
then there are the wast files,
but got Segmentation fault when run:
`eosc set contract exchange contracts/exchange/exchange.wast contracts/exchange/exchange.abi`

details:
```
root@f93c8c447b5c:/opt/eos/bin/data-dir# eosc set contract exchange contracts/exchange/exchange.wast contracts/exchange/exchange.abi
Reading WAST...
Assembling WASM...
Publishing contract...
Segmentation fault (core dumped)
```
