### ISSUE TITLE
billed CPU time (ХХХ us) is greater than the maximum billable CPU time for the transaction (ХХХ us)

### ISSUE THREAD

**Issue by bizlevel** [EOSIO/eos#4572]
I got latest 1.0.8 version and this strange in logs:
```
Jul 10 13:53:11 eos eos[13830]: 3191559ms thread-0   net_plugin.cpp:2547           operator()           ] accept txn threw  3080004 tx_cpu_usage_exceeded: transaction exceeded the current CPU usage limit imposed on the transaction
Jul 10 13:53:11 eos eos[13830]: billed CPU time (3632 us) is greater than the maximum billable CPU time for the transaction (3088 us)
Jul 10 13:53:11 eos eos[13830]:     {"billed":3632,"billable":3088}
Jul 10 13:53:11 eos eos[13830]:     thread-0  transaction_context.cpp:350 validate_cpu_usage_to_bill
Jul 10 13:53:11 eos eos[13830]: 3191567ms thread-0   producer_plugin.cpp:294       on_incoming_block    ] Received block 01625b6b88fc55d9... #5159781 @ 2018-07-10T13:53:11.500 signed by libertyblock [trxs: 1, lib: 5159445, conf: 0, latency: 67 ms]
Jul 10 13:53:11 eos eos[13830]: 3191576ms thread-0   net_plugin.cpp:2547           operator()           ] accept txn threw  3081001 leeway_deadline_exception: transaction reached the deadline set due to leeway on account CPU limits
Jul 10 13:53:11 eos eos[13830]: the transaction was unable to complete by deadline, but it is possible it could have succeeded if it were allowed to run to completion
Jul 10 13:53:11 eos eos[13830]:     {"now":"2018-07-10T13:53:11.575","deadline":"2018-07-10T13:53:11.575","start":"2018-07-10T13:53:11.569","billing_timer":6089}
Jul 10 13:53:11 eos eos[13830]:     thread-0  transaction_context.cpp:301 checktime
Jul 10 13:53:11 eos eos[13830]:     {"_pending_console_output.str()":""}
Jul 10 13:53:11 eos eos[13830]:     thread-0  apply_context.cpp:62 exec_one

```

What i must change in config file to eliminate this ?
Thanks.

**Comment by taokayan** [comment]
you probably need to stake more EOS for CPU resource or push your transaction to a faster node.

**Comment by spartucus** [comment]
Hi @taokayan , by "push your transaction to a faster node." you mean push same trx to different node cost different CPU resource?

**Comment by taokayan** [comment]
Yes. depends on the machine CPU performance your transaction might results in different cpu usage.

**Comment by liukunyu** [comment]
'push same trx to different node cost different CPU resource'?then how to apply_block with this transaction in different node ?

**Comment by tomarvijay25** [comment]
I am getting the same at the time of transferring my EOS from ledger nano to one exchange. Can someone please explain in detail what exactly needs to be done to rectify this error? My EOS are stuck, please help me to transfer my EOS.

**Comment by SavostinVladimir** [comment]
Hi! I've got the same error. And does it mean if I stake for example 3.0 EOS for some account I need to wait 72 hours to be able do new transactions?? I just staked 3 EOS but my bandwidth was decreased from 18.95 msec to 6.8 msec.

**Comment by taokayan** [comment]
No you don't need to wait 72 hours. You can still push your transaction if the network become idle. Also your CPU usage will gradually reduce over time. So you can keep trying from time to time.

**Comment by SavostinVladimir** [comment]
thank you!
![screenshot from 2019-01-31 13-54-41](https://user-images.githubusercontent.com/27097483/52039842-cfcdc280-255f-11e9-9d52-8279e4dfddfc.png)
if you see on this screenshot now I have 3 EOS staking for CPU and my bandwidht is 19 ms... but when there was  0.0 EOS staking for CPU my bandwidth was almost the same. It was ~18.9 ms. Does it mean that I staked 3 EOS for so tiny CPU bandwidth??

**Comment by taokayan** [comment]
the cpu usage/limit from some public explorer is the usage/limit evaluated at the last time you made a transaction. It does not reflect to how much you can use at any time in the future. So, try to make your transaction, if it succeed, you should see the updated usage/limit.

**Comment by rvit34** [comment]
Currently I have the same error as @SavostinVladimir 
I think my account have enough CPU account to make a transaction
![eos_account_resources](https://user-images.githubusercontent.com/20579813/72930196-d529ab80-3d74-11ea-956e-93262155ac70.png)

But anyaway I got an error:
`
{
  "code": 400,
  "message": "Bad Request",
  "error": {
    "code": 3080004,
    "name": "tx_cpu_usage_exceeded",
    "what": "Transaction exceeded the current CPU usage limit imposed on the transaction",
    "details": [
      {
    "message": "billed CPU time (362 us) is greater than the maximum billable CPU time for the transaction (13 us)",
    "file": "transaction_context.cpp",
    "line_number": 553,
    "method": "validate_cpu_usage_to_bill"
      }
    ]
  }
}
`
How to fix it? Stake more CPU? I've already staked 20EOS (almost a half of my initial balance). It's good enough, isn't it?

**Comment by Dangermouse1234** [comment]
I found THE SOLUTION for this CPU time error !!

Download the latest Anchor wallet: https://github.com/greymass/anchor/releases

In Resources: buy CPU pressing the 'Rent via PowerUp (1day)'

You will be fine. ALL YOUR TRANSACTIONS WILL GO THROUGH !!
