### ISSUE TITLE
The block height for same transactions on different nodes are different ! 

### ISSUE THREAD

**Issue by bizlevel** [EOSIO/eos#4576]
I have own latest 1.0.8 node, And when i run:
**root@eos:~# curl -s -d '{"id":"17a1bfae5f2e7ba1303ca34ff5a057182c1ade1513ac894f9178f163d349196f"}' --request POST --url http://127.0.0.1:8888/v1/history/get_transaction | jq '.'**

I got:
```
{
  "id": "17a2a357ecdc45064712f512cce073310c1920f2f1ea1879e5470f4ceac1d329",
  "trx": null,
  "block_time": "2018-07-10T14:09:42.500",
  "block_num": 5161763,
  "last_irreversible_block": 5180448,
  "traces": []
}
```

On the first look all the fine. But if i check answer with other explorer, i got HUGE BUG!
block_num - IS WRONG!

Check it - https://eosmonitor.io/txn/17a1bfae5f2e7ba1303ca34ff5a057182c1ade1513ac894f9178f163d349196f
Or check it - https://eostracker.io/transactions/17a1bfae5f2e7ba1303ca34ff5a057182c1ade1513ac894f9178f163d349196f
Same result, but not with my node.

HOW IT CAN BE?

![1](https://user-images.githubusercontent.com/12154217/42524992-c3591904-847a-11e8-83f3-6e552ebec876.PNG)

![2](https://user-images.githubusercontent.com/12154217/42524993-c378edd8-847a-11e8-9e44-0c37160bc975.PNG)

**Comment by FaysalM** [comment]
Is anyone planning to reply? Seems like a pretty major issue (if legit).

**Comment by FaysalM** [comment]
@bizlevel you may want to try this:
https://github.com/EOSIO/eos/issues/3887

**Comment by bizlevel** [comment]
@FaysalM No, https://github.com/EOSIO/eos/issues/3887 it is different and my ticket also it is there https://github.com/EOSIO/eos/issues/4570
It is Other case.

**Comment by heifner** [comment]
It looks like the transaction was not found, notice the "trx : null" in which case it returns the current block_num. We realize this is confusing and has been enhanced in the upcoming 1.1 release.

**Comment by bizlevel** [comment]
Ok, we will wait for it, because PAYTOMAT can't start without it!

**Comment by jgiszczak** [comment]
Now returns code 500 with error name `tx_not_found` when an invalid or unknown transaction ID is requested.
