### ISSUE TITLE
eosio-applesedemo : failed to generate asymmetric keypair

### ISSUE THREAD

**Issue by hwnahm** [EOSIO/eos#4579]
$ applesedemo.app/Contents/MacOS/applesedemo --create-se-touch-only
Failed
Error Domain=NSOSStatusErrorDomain Code=-34018 "failed to generate asymmetric keypair" UserInfo={NSDescription=failed to generate asymmetric keypair}
$

**Comment by hwnahm** [comment]
I made some mistakes on apple AppID generation.
It's solved.

**Comment by unclewangshushu** [comment]
> I made some mistakes on apple AppID generation.
> It's solved.

Does it require a paid Apple developer ID?
