### ISSUE TITLE
nodeos crash: terminate called after throwing an instance of 'boost::interprocess::bad_alloc'

### ISSUE THREAD

**Issue by IvanYakimov** [EOSIO/eos#4584]
I got a crytical error (ended up with a process abort) while synchronizing my local nodeos instance with the mainnet.
I followed instructions from here: https://eosio.stackexchange.com/questions/725/how-to-vote-using-cleos/726#726 and set up my local nodeos respectively.

So, my local nodeos instance mainly got synchronized (roughly saying about 4K blocks maybe) and then suddenly crashed.

The crash log is below:

```
346857ms thread-0   controller.cpp:217            init                 ] 2890 reversible blocks replayed
346857ms thread-0   controller.cpp:221            init                 ] replayed 4423099 blocks in seconds, 0.91038242010861614 ms/block

346857ms thread-0   chain_plugin.cpp:450          plugin_startup       ] starting chain in read/write mode
346857ms thread-0   chain_plugin.cpp:455          plugin_startup       ] Blockchain started; head block is #4423099, genesis timestamp is 2018-06-08T08:08:08.888
346857ms thread-0   chain_api_plugin.cpp:75       plugin_startup       ] starting chain_api_plugin
346857ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/abi_bin_to_json
...
346857ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/push_transactions
346857ms thread-0   history_api_plugin.cpp:38     plugin_startup       ] starting history_api_plugin
346857ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_actions
...
346857ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_transaction
346857ms thread-0   net_plugin.cpp:3056           plugin_startup       ] starting listener, max clients is 25
346857ms thread-0   net_plugin.cpp:749            connection           ] created connection to 106.10.42.238:9876
346857ms thread-0   net_plugin.cpp:1970           connect              ] host: 106.10.42.238 port: 9876
...
346858ms thread-0   net_plugin.cpp:749            connection           ] created connection to node1.eosnewyork.io:6987
346858ms thread-0   net_plugin.cpp:1970           connect              ] host: node1.eosnewyork.io port: 6987
346858ms thread-0   net_plugin.cpp:749            connection           ] created connection to node2.blockeos.io:9987
346858ms thread-0   net_plugin.cpp:1970           connect              ] host: node2.blockeos.io port: 9987
346858ms thread-0   net_plugin.cpp:749            connection           ] created connection to node2.eosnewyork.io:6987
346858ms thread-0   net_plugin.cpp:1970           connect              ] host: node2.eosnewyork.io port: 6987
...
346860ms thread-0   net_plugin.cpp:749            connection           ] created connection to seed2.greymass.com:9876
346860ms thread-0   net_plugin.cpp:1970           connect              ] host: seed2.greymass.com port: 9876
346860ms thread-0   producer_plugin.cpp:580       plugin_startup       ] producer plugin:  plugin_startup() begin
346952ms thread-0   producer_plugin.cpp:607       plugin_startup       ] producer plugin:  plugin_startup() end
347169ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from 159.65.214.150:9876: Connection reset by peer
347329ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from 123.59.116.52:49876: Connection reset by peer
347397ms thread-0   net_plugin.cpp:2190           operator()           ] Peer 807534da.eosnodeone.io:19872 closed connection
347458ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from api-full1.eoseoul.io:9876: Connection reset by peer
347476ms thread-0   net_plugin.cpp:2190           operator()           ] Peer api.eosuk.io:12000 closed connection
...
354562ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from mars.fnp2p.eosbixin.com:443: Bad file descriptor
354671ms thread-0   net_plugin.cpp:2190           operator()           ] Peer node1.eosamericas.com:9876 closed connection
354916ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from node1.eoscannon.io:59876: Connection reset by peer
355160ms thread-0   net_plugin.cpp:2190           operator()           ] Peer node2.blockeos.io:9987 closed connection
terminate called after throwing an instance of 'boost::interprocess::bad_alloc'
  what():  boost::interprocess::bad_alloc
Aborted (core dumped)

```

https://github.com/EOSIO/eos/blob/ef654aa34c135e2023ca76871ddbcb07a91a1990/plugins/net_plugin/net_plugin.cpp#L2190

Note: before the crash happened I had been launching nodeos several times and last time I launched it with `--hard-replay-blockhain` option enabled

**Comment by andriantolie** [comment]
Very likely your local nodeos is running out of shared memory size for the chain state. This could happen if the RAM usage is already more than the allocated default size which is 1024 MB

Update the `chain-state-db-size-mb =` parameter inside your config.ini to a higher value, say 4096 (4GB) and try to restart your nodeos :)

**Comment by ddzyan** [comment]
I set up  chain-state-db-size-mb = 8192,That is still the case.

**Comment by nanmu42** [comment]
Me too, for many times.

And the memory usage is only at 3 GB.

**Comment by andriantolie** [comment]
If you are using history plugin and filter all transactions, your memory usage will increase significantly and you will need a higher amount. Furthermore, if you are syncing with the mainnet, you will also need the amount to be at least equal to the current total ram usage in the mainnet

**Comment by nanmu42** [comment]
Yes, I am syncing the mainnet.

> if you are syncing with the mainnet, you will also need the amount to be at least equal to the current total ram usage in the mainnet

However, I do not understand why I need so much memory, the memory usage is always at 2~3 GB.

I am considering there is some bug in `nodeos`.

**Comment by Drug0j** [comment]
./nodeos --config=/root/usr/local/eosio/bin/config.ini --replay-blockchain --genesis-json genesis.json
2018-09-25T08:39:55.905 thread-0   chain_plugin.cpp:329          plugin_initialize    ] initializing chain plugin
2018-09-25T08:39:55.905 thread-0   chain_plugin.cpp:496          plugin_initialize    ] Replay requested: deleting state database
2018-09-25T08:39:55.905 thread-0   chain_plugin.cpp:646          plugin_initialize    ] 4 parse_error_exception: Parse Error
Expected '"' but read '?'
    {"char":"?"}
    thread-0  json.cpp:100 stringFromStream
while parsing token ''
    {"token":""}
    thread-0  json.cpp:123 stringFromStream
Error parsing object
    {}
    thread-0  json.cpp:218 objectFromStream

**Comment by Drug0j** [comment]
./nodeos --config=/root/usr/local/eosio/bin/config.ini --delete-all-blocks --genesis-json genesis.json
2018-09-25T08:41:50.829 thread-0   chain_plugin.cpp:329          plugin_initialize    ] initializing chain plugin
2018-09-25T08:41:50.829 thread-0   chain_plugin.cpp:470          plugin_initialize    ] Deleting state database and blocks
2018-09-25T08:41:50.829 thread-0   chain_plugin.cpp:646          plugin_initialize    ] 4 parse_error_exception: Parse Error
Expected '"' but read '?'
    {"char":"?"}
    thread-0  json.cpp:100 stringFromStream
while parsing token ''
    {"token":""}
    thread-0  json.cpp:123 stringFromStream
Error parsing object
    {}
    thread-0  json.cpp:218 objectFromStream
Failed to initialize

**Comment by Drug0j** [comment]
I use this genesis,  
{
  « initial_timestamp » : « 2018-06-08T08: 08: 08.888 » ,
  « initial_key » : « EOS7EarnUhcyYqmdnPon8rm7mBCTnBoot6o7fE2WzjvEX2TdggbL3 » ,
  " initial_configuration " : {
    " max_block_net_usage " : 1048576 ,
    « target_block_net_usage_pct » : 1000 ,
    " max_transaction_net_usage " : 524288 ,
    " base_per_transaction_net_usage " : 12 ,
    « net_usage_leeway » : 500 ,
    " context_free_discount_net_usage_num " : 20 ,
    " context_free_discount_net_usage_den " : 100 ,
    " max_block_cpu_usage " : 200000 ,
    " target_block_cpu_usage_pct " : 1000 ,
    « max_transaction_cpu_usage » : 150000 ,
    « min_transaction_cpu_usage » : 100 ,
    « max_transaction_lifetime » : 3600 ,
    « deferred_trx_expiration_window » : 600 ,
    " max_transaction_delay " : 3888000 ,
    " max_inline_action_size " : 4096 ,
    " max_inline_action_depth " : 4 ,
    " max_authority_depth " : 6
  }
}
but when I insert into the created file .JSON in the folder, it becomes so ....
{
     initial_timestamp    :    2018-06-08T08: 08: 08.888    ,
     initial_key    :    EOS7EarnUhcyYqmdnPon8rm7mBCTnBoot6o7fE2WzjvEX2TdggbL3    ,
  " initial_configuration " : {
    " max_block_net_usage " : 1048576 ,
       target_block_net_usage_pct    : 1000 ,
    " max_transaction_net_usage " : 524288 ,
    " base_per_transaction_net_usage " : 12 ,
       net_usage_leeway    : 500 ,
    " context_free_discount_net_usage_num " : 20 ,
    " context_free_discount_net_usage_den " : 100 ,
    " max_block_cpu_usage " : 200000 ,
    " target_block_cpu_usage_pct " : 1000 ,
       max_transaction_cpu_usage    : 150000 ,
       min_transaction_cpu_usage    : 100 ,
       max_transaction_lifetime    : 3600 ,
       deferred_trx_expiration_window    : 600 ,
    " max_transaction_delay " : 3888000 ,
    " max_inline_action_size " : 4096 ,
    " max_inline_action_depth " : 4 ,
    " max_authority_depth " : 6
  }
}


 tell me the problem is yes? how to preserve the original appearance?

**Comment by Drug0j** [comment]
Problem in « Yes?

**Comment by Drug0j** [comment]
!!!!!!!!YES !!!!!!! dowaland https://github.com/CryptoLions/EOS-MainNet/tree/2c69bcb7654b99454926e86d09845346c469f751    .json go ./nodeos -- config
