### ISSUE TITLE
EOS.io Website

### ISSUE THREAD

**Issue by nanonano7** [EOSIO/eos#459]
On the website its website it says 

> CURRENT PERIOD 80/351

Which indicates that we are in the 80th period out of 351.But we are currently in the 81st period out of 351 with the index of 80.

**Comment by dskvr** [comment]
This is correct. We're using a 0 based index for periods. It's Period 0, not Period 1.

**Comment by bytemaster** [comment]
I have reported this to the web team, this is issue is not relevant to this repo.
