### ISSUE TITLE
eosio.token::transfer - cannot decrement end iterator when the table is empty

### ISSUE THREAD

**Issue by MrToph** [EOSIO/eos#4596]
Hi,

I encountered a weird bug.
Now after some time, all valid eos transfers suddenly don't work anymore.
I'm testing this on a local testnet.

I get this error:

```
Exception Details: 3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
assertion failure with message: cannot decrement end iterator when the table is empty
    {"s":"cannot decrement end iterator when the table is empty"}
    thread-0  wasm_interface.cpp:930 eosio_assert
```

Every valid eosio.token transfer causes this error.
If I try to transfer to myself I still get the correct assertion error that I cannot transfer to myself.

```
cleos push action eosio.token transfer '[ "eosio", "kingofeos", "50.0001 SYS", "memo" ]' -p eosio
```

Is my local node broken somehow? I couldn't find any decrement statements in the eosio.token contract

**Comment by MrToph** [comment]
I figured it out.

If anyone ever encounters this error, this was what it caused it in my case:
These two contracts that I tested it with both had smart contracts that listened for transfers to them and send and inline_transfer back, basically ping ponging each other with transfers all the time.

**Comment by nirdesh27** [comment]
Yes i also encouter this issue while easing value form a table. I don't know what the hack is goind on...('' '')
