### ISSUE TITLE
eos smart contract dosen't update

### ISSUE THREAD

**Issue by compjotr** [EOSIO/eos#4598]
Hi guys! I'm creating a simple game by following the tic tac toe tutorial. But when recompiling the .wast and the .abi file, the cleos set contract doesn't recognize the changes made. Even when creating a new account, the new code is not recognized.
![image](https://user-images.githubusercontent.com/8794897/42579219-1843e478-8528-11e8-946a-347f896c4494.png)
I have tried the other posts, but not found a solution. Any help is greatly appreciated.

**Comment by andriantolie** [comment]
Hi @compjotr, what's the change that you have made to the code before and after? If you make a change that will be skipped by the compiler (for example, declare an unused variable), it will result in the same code.

**Comment by compjotr** [comment]
@andriantolie i have made real changes. Added a function that is also added to the abi file, but the compiled contract dosen't see it. Also print statements, to all functions to see if they are running.

**Comment by andriantolie** [comment]
That's strange. How do you compile the contract and how do you set the contract?

**Comment by compjotr** [comment]
➜  rock_paper_scissors git:(master) ✗ eosiocpp -o rock_paper_scissors.wast rock_paper_scissors.cpp
➜  rock_paper_scissors git:(master) ✗ eosiocpp -g rock_paper_scissors.abi rock_paper_scissors.cpp
987970ms thread-0   abi_generator.hpp:68          ricardian_contracts  ] Warning, no ricardian clauses found for rock_paper_scissors

987970ms thread-0   abi_generator.hpp:75          ricardian_contracts  ] Warning, no ricardian contract found for create

987970ms thread-0   abi_generator.hpp:75          ricardian_contracts  ] Warning, no ricardian contract found for restart

987970ms thread-0   abi_generator.hpp:75          ricardian_contracts  ] Warning, no ricardian contract found for close

987970ms thread-0   abi_generator.hpp:75          ricardian_contracts  ] Warning, no ricardian contract found for move

987970ms thread-0   abi_generator.hpp:75          ricardian_contracts  ] Warning, no ricardian contract found for hi

Generated rock_paper_scissors.abi ...
➜  rock_paper_scissors git:(master) ✗ cleos set contract letsplay rock_paper_scissors             
Reading WAST/WASM from rock_paper_scissors/rock_paper_scissors.wast...
Assembling WASM...
Publishing contract...
991663ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)

Error for localnet : 
991662ms thread-0   http_plugin.cpp:405           handle_exception     ] FC Exception encountered while processing chain.push_transaction
991662ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 10 assert_exception: Assert Exception
account.code_version != code_id: contract is already running this version of code
    {}
    thread-0  eosio_contract.cpp:151 apply_eosio_setcode

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:62 exec_one

**Comment by andriantolie** [comment]
```
rock_paper_scissors git:(master) ✗ eosiocpp -o rock_paper_scissors.wast rock_paper_scissors.cpp
rock_paper_scissors git:(master) ✗ cleos set contract letsplay rock_paper_scissors
```
You did the above commands from the same folder? In that case, the one that is uploaded is not the one that you just generated, but instead is the one inside .../rock_paper_scissors/rock_paper_scissors/rock_paper_scissors.wast

**Comment by compjotr** [comment]
Nice, cleaned up and run like you suggested, but same issue i'm afraid. I copied the function from the hello world contract, and try to run it, but the compiled code is not changed.

**Comment by compjotr** [comment]
Still, the functions doesn't print the print statements to the terminal, any idea why?

**Comment by andriantolie** [comment]
Set contract-console = true in your config.ini and restart your nodeos

**Comment by compjotr** [comment]
Thanks dude. saved me a lot of time and trouble. Have a good day!
