### ISSUE TITLE
get_block api request returning 500 service error

### ISSUE THREAD

**Issue by shakhruz** [EOSIO/eos#4600]
Since yesterday (July 10) all nodes started responding with 500 service error when I request block info for specific blocks, for example 447, 2167 and many more others. Before I only had a problem with a couple of blocks in the entire blockchain.

here is the full response:
``
{
"code": 500,
"message": "Internal Service Error",
"error": {
"code": 10,
"name": "assert_exception",
"what": "Assert Exception",
"details": [
{
"message": "fc::time_point::now() < deadline: serialization time limit 15000us exceeded",
"file": "abi_serializer.hpp",
"line_number": 288,
"method": "add"
},
{
"message": "Failed to serialize type",
"file": "abi_serializer.hpp",
"line_number": 600,
"method": "to_variant"
}
]
}
}
``

**Comment by heifner** [comment]
The default `--abi-serializer-max-time-ms` of 15 is too small to de-serialize larger blocks on the particular machine responding to your block info request. The nodeos processing your requests can increase the allowed serialization time by passing a larger value to '--abi-serializer-max-time-ms`.
