### ISSUE TITLE
cleos wallet error

### ISSUE THREAD

**Issue by HomoEfficio** [EOSIO/eos#4603]
`cleos wallet` does not seem to work.

![12-07-2018-07-38-14](https://user-images.githubusercontent.com/17228983/42602912-8b0dd878-85a6-11e8-99c4-f0b0162483db.png)

**Comment by billylindeman** [comment]
was having the same issue this might point you in the right direction 
https://github.com/EOSIO/eos/pull/4599/files 
https://github.com/EOSIO/eos/pull/4580

if you're just doing local dev adding `http-validate-host = false` to your config.ini fixes it

**Comment by HomoEfficio** [comment]
@jgiszczak That's not the point. It happens even in a single keosd.
