### ISSUE TITLE
multi-index .modify() errors when primary_key() is 0 or 1

### ISSUE THREAD

**Issue by billylindeman** [EOSIO/eos#4605]
I have a struct using a `uint64_t id` as the primary key. Records are created in an action and upon initialization setting ` available_primary_key()` as the id.  I'll end up with records starting at 0, which I can access with .find() but when i call .modify on the iterator i end up with an error.

```        // Check if game already exists
        matches_index matches(_self, _self);
        auto itr = matches.find(match);

        eosio_assert(itr != matches.end(), "match not found");
        eosio_assert(itr->state == match_state::PENDING, "this match has already been accepted!");
        eosio_assert(itr->challenger == N(none), "this match has already been accepted!");

        print("found match: ", itr->id, " setting challenger to ", challenger);
        
        matches.modify(itr, _self, [&]( auto& m ) {
            m.challenger = challenger;
            m.state = match_state::ACCEPTED;
        });
```

```nodeosd_1  | 828966ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 10 assert_exception: Assert Exception
nodeosd_1  | iterator != -1: invalid iterator
nodeosd_1  |     {}
nodeosd_1  |     thread-0  apply_context.hpp:63 get
nodeosd_1  |
nodeosd_1  |     {"_pending_console_output.str()":"finding match: 0 found match: 0 setting challenger to 14605619288908759040"}
nodeosd_1  |     thread-0  apply_context.cpp:62 exec_one
```

When I try to accept match 0 or 1 this function fails with the above error but works fine with id >= 2

**Comment by andriantolie** [comment]
What is the value of the variable `match` above? Also, what's the struct of your match and what's the currently available data inside your table? I can't see anything strange by just looking at the above snippet, further information will help.

**Comment by billylindeman** [comment]
not exactly sure what was wrong but i wiped my nodeos and tested it from a fresh net and it works now.
