### ISSUE TITLE
build eos failed on centos7

### ISSUE THREAD

**Issue by ddzyan** [EOSIO/eos#4606]
`[admin@default eos]$ sudo ./eosio_build.sh 

	Beginning build version: 1.2
	Thu Jul 12 06:33:42 UTC 2018
	User: root
	git head id: f947a6daa6fac1891bd5bb5b2c88a08025c6e740
	Current branch: HEAD

	ARCHITECTURE: Linux

	OS name: CentOS Linux
	OS Version: 7
	CPU speed: 2397Mhz
	CPU cores: 4
	Physical Memory: 16048 Mgb
	Disk install: /dev/mapper/rootvg-root
	Disk space total: 62G
	Disk space available: 57G

	Checking Yum installation
	Yum installation found at /bin/yum.

	Checking installation of Centos Software Collections Repository.
	Centos Software Collections Repository found.

	Enabling Centos devtoolset-7.

	Unable to enable Centos devtoolset-7 at this time.

	Exiting now`

**Comment by ddzyan** [comment]
Is already installed
`sudo yum -y --enablerepo=extras install centos-release-scl

  sudo yum install -y devtoolset-7

  sudo yum install -y python33.x86_64`

**Comment by jgiszczak** [comment]
Does `scl enable devtoolset-7` also produce a non-zero return code when the toolset is already enabled?
