### ISSUE TITLE
multi_index vs flat_map

### ISSUE THREAD

**Issue by mamidi1211** [EOSIO/eos#4611]
what is the difference between multi_index and flat_map. 
Also, is there any documentation or tutorial where we can find these kind of definitions. ?

**Comment by dhaneshvb** [comment]
flatmap is a sorted vector. It is kept on contiguous memory and supports one key
multi_index container can have multiple indices associated with it and queryable based on it.

**Comment by jgiszczak** [comment]
flat_map is documented [here](https://www.boost.org/doc/libs/1_67_0/doc/html/boost/container/flat_map.html).  It's part of boost.  multi_index has doxygen documentation, which you can generate from the source code yourself.  The pregenerated version available [here](https://eosio.github.io/eos/classeosio_1_1multi__index.html) is currently out of date, but might be a little helpful.
