### ISSUE TITLE
Occuered "wallet_missing_pub_key_exception" when signing transaction by RPC

### ISSUE THREAD

**Issue by vincentwang0736** [EOSIO/eos#4616]
I want to make a interface for creating account.
But when I am on the step of sign, I got this exception after I called "'/v1/wallet/sign_transaction'"

> {"code":500,"message":"Internal Service Error","error":{"code":3120004,"name":"wallet_missing_pub_key_exception","what":"Missing public key","details":[]}}

I have unlocked wallet by RPC former.
By the way,I imported privatekey by cmd:cleos. is it anything wrong?

anyone can help me? thanks a lot!

**Comment by jgiszczak** [comment]
You need to call `/vi/chain/get_required_keys` to get the required public key needed for signing your transaction.  To see the full sequence, use cleos to create an account with the `--print-request --print-response` arguments.
