### ISSUE TITLE
error happen when I use custom permission

### ISSUE THREAD

**Issue by zhengzhejun** [EOSIO/eos#4617]
I create account called test and create new permission called "publish".
`
cleost get account test
permissions:
owner     1:    1 EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV

active     1:    1 EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV

publish     1:    1 EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV`

And I set contract in "test" account, code like below

`
class Test : public eosio::contract {
    public:
    explicit Test(action_name self) : contract(self) {};

    //@abi action
    void test() {}
};
EOSIO_ABI(Test,(test))
`

when I push action with "publish" permission, there happend error saying like below.

`
cleost push action test test '' -p test@publish

Error 3090005: irrelevant authority included
Please remove the unnecessary authority from your action!
Error Details:
action declares irrelevant authority '{"actor":"test","permission":"publish"}'; minimum authority is {"actor":"test","permission":"active"}
`

I wonder why need the "active" permission when the function "test" does noting.

**Comment by vjoke** [comment]
I think it's hardcoded by cleos. maybe you can hack the source code

**Comment by andriantolie** [comment]
Even though your action is not doing anything, for every transaction, we need to have at least one signer to bill the net and cpu. 

And unless you link the action with `publish` auth, the minimum required authority is active. To allow you to use test@publish for test action, you need to link the auth first `cleos set action permission tset test test publish`
