### ISSUE TITLE
CMake Error at libraries/CMakeLists.txt:10 (add_subdirectory):

### ISSUE THREAD

**Issue by dteos** [EOSIO/eos#4620]
Hi, I'm getting the following error when building on Ubuntu  18.04

I ran:

cd /path/to/eos
rm -rf build/
git pull
git submodule update --init --recursive
./eosio_build.sh

And get:

CMake Error at libraries/CMakeLists.txt:10 (add_subdirectory):
  The source directory

    /home/darrin/eos/libraries/abi_generator

  does not contain a CMakeLists.txt file.

-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Git commit revision: ef654aa3
-- Git commit revision: ef654aa3
-- Found Intl: /usr/include  
-- Git commit revision: ef654aa3
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
-- Configuring incomplete, errors occurred!
See also "/home/darrin/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/darrin/eos/build/CMakeFiles/CMakeError.log".

	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.

Thanks

**Comment by jgiszczak** [comment]
Something has gone badly wrong with your git pull.  `libraries/abi_generator` does have a CMakeLists.txt and is not a submodule.  Make sure you're on `master` or a release tag.  If that doesn't help, our advice in these circumstances is usually to make sure you don't have any of your code in the source tree and simply erase `/path/to/eos` and start over.  If you'd prefer a less scorched earth recovery, consult available git help.

**Comment by dteos** [comment]
A fresh clone fixed the problem. Thank you.
