### ISSUE TITLE
query record base on key

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#4622]
Is there a way to query record base on key?

**Comment by andriantolie** [comment]
Can you please elaborate your question?

Do you mean querying a smart contract table from within a smart contract? Or do mean you querying a smart contract table from outside?

**Comment by csquan** [comment]
querying a smart contract table from within a smart contract?now,only I know to query the whole table content,but I want to query record base on key or some other terms.

**Comment by csquan** [comment]
I want to query a smart contract table within a smart contract.
now,only I know to query the whole table content,but I want to query record base on key or some other terms.

**Comment by andriantolie** [comment]
If you want to query record based on the primary key, you can just use the `get` or `find` function of the multi_index.

If you want to query record based on the other field, you will need to index that field as the secondary key first, get the secondary index table, and you can use the `get` or `find` function of the multi_index on that secondary index table.

Example
```
#include <eosiolib/eosio.hpp>
using namespace eosio;
using namespace std;
class addressbook: contract {
  struct address {
     uint64_t account_name;
     string first_name;
     string last_name;
     string street;
     string city;
     string state;
     uint32_t zip = 0;
     uint64_t primary_key() const { return account_name; }
     uint64_t by_zip() const { return zip; }
     EOSLIB_SERIALIZE( address, (account_name)(first_name)(last_name)(street)(city)(state)(zip) )
  };
  public:
    addressbook(account_name self):contract(self) {}
    typedef eosio::multi_index< N(address), address, indexed_by< N(zip), const_mem_fun<address, uint64_t, &address::by_zip> > address_index;
    void myaction() {
      address_index addresses(_self, _self); 
      addresses.emplace(payer, [&](auto& address) {
        address.account_name = N(dan);
        address.first_name = "Daniel";
        address.last_name = "Larimer";
        address.street = "1 EOS Way";
        address.city = "Blacksburg";
        address.state = "VA";
        address.zip = 93446;
      });
      auto primary_key_itr = addresses.find(N(dan));
      eosio_assert(primary_key_itr->account_name == N(dan), "Incorrect Record ");
      auto zip_index = addresses.get_index<N(zip)>();
      auto secondary_key_itr = zip_index.find(93446);
      eosio_assert(secondary_key_itr->account_name == N(dan), "Incorrect Record ");
    }
}
EOSIO_ABI( addressbook, (myaction) )
```
