### ISSUE TITLE
Can I get contract's original c++ codes from chain?

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#4628]
Is it possible to get contract's original code from chain? 
Sometimes, we need to audit contracts. Is the only way to audit contracts is to ask for their original code, and compare the hash with the on chain hash?

**Comment by evsward** [comment]
i do wonder if could

**Comment by jgiszczak** [comment]
At present, no, there is no way to retrieve the original source code of a contract.  We are aware of this shortcoming and considering possible mechanisms to address it.

**Comment by guaiguaihw** [comment]
@jgiszczak I am looking forward to your improvement, It's very important for the exchange. If you can add it to the support  plan  I will be very appciate.
