### ISSUE TITLE
How to veritfy a contract on the mainnet is exactly follows the source code the author open sourced on github?

### ISSUE THREAD

**Issue by hashware** [EOSIO/eos#4629]
I use get abi and get code to retrive a contract from the mainnet,
and i found the source code the author announced open sourced on github
how to verify the contract and source code's implementation is identical?

**Comment by vjoke** [comment]
+1

**Comment by andriantolie** [comment]
If you compile the source code and hash it using hash256, the hash should be the same as the one you get with `cleos get code`
