### ISSUE TITLE
A ERROR appeared when loading eosio.bios

### ISSUE THREAD

**Issue by Danilo0120** [EOSIO/eos#4633]
I have no idea what's up with this:

~/eos$ cleos set contract eosio ./build/contracts/eosio.bios -p eosio
Reading WAST/WASM from ./build/contracts/eosio.bios/eosio.bios.wasm...
Using already assembled WASM...
Publishing contract...
1419308ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)
response_content_length >= 0: Invalid content-length response

**Comment by Danilo0120** [comment]
I will appreciate it if this error is resolved

**Comment by jgiszczak** [comment]
Add `http-validate-host = false` to your nodeos config.ini.  The latest version tightened up host validation considerably.  This is good for production nodes, but it does require attention in local testnets.

**Comment by Danilo0120** [comment]
@jgiszczak    follow your guide,but it still have problem:


~/eos/build/programs/cleos$ cleos set contract eosio ../../contracts/eosio.bios -p eosio
Reading WAST/WASM from ../../contracts/eosio.bios/eosio.bios.wasm...
Using already assembled WASM...
Publishing contract...
2272648ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)

**Comment by msj121** [comment]
I just got the same error.  I cleared all blocks on my nodeos startup just now (--delete-all-blocks), It had published a contract today, recently changed the table definition, but changed back and no help. I also changed the ipaddress and port I listen on, but changed back and didn't help.

> Reading WAST/WASM from ./validator.wast...
> Assembling WASM...
> Publishing contract...
> 438324ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)
> response_content_length >= 0: Invalid content-length response

**Comment by Danilo0120** [comment]
@msj121  follow his guide and have a try again?

**Comment by msj121** [comment]
@Danilo0120 Oh, I already had that set to false and still had errors. Will update my post.

**Comment by Danilo0120** [comment]
@msj121  I am searching a way to resolve this error

**Comment by jackiesun8** [comment]
change the  ~/.local/share/eosio/nodeos/config/config.ini http-server-address = 127.0.0.1:8888
 to http-server-address = localhost:8888 Solved my problem

**Comment by rafael81** [comment]
@jackiesun8 I resolved this issue. thanks

**Comment by nb312** [comment]
I have another problem when I run ``` cleos set contract eosio build/contracts/eosio.bios -p eosio@active ```
```
Using already assembled WASM...
Publishing contract...
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
```
