### ISSUE TITLE
why the nodeos was killed when get chain info?

### ISSUE THREAD

**Issue by woo-fight** [EOSIO/eos#4634]
![image](https://user-images.githubusercontent.com/21164253/42681540-9453886e-86ba-11e8-9391-dcf1132b5c77.png)
why the nodeos was killed when get chain info?

**Comment by woo-fight** [comment]
![image](https://user-images.githubusercontent.com/21164253/42682720-f2851ae4-86bd-11e8-847b-6018c1ceff6b.png)
and then i  run  `/home/eos-sources/eos/build/programs/nodeos/nodeos --data-dir /opt/EOSmainNet --config-dir /opt/EOSmainNet`

**Comment by woo-fight** [comment]
![image](https://user-images.githubusercontent.com/21164253/42683213-4661ddcc-86bf-11e8-8263-229b476cff9a.png)
![image](https://user-images.githubusercontent.com/21164253/42683563-387a1d04-86c0-11e8-86c9-8378268fb3d2.png)

when i run `dmesg`, it‘s  OOM , is there any idea without Increase physical memory

**Comment by jgiszczak** [comment]
`nodeos` can not run on a machine with 2 GB of RAM, especially not when connected to mainnet.

**Comment by jgiszczak** [comment]
That will work, but is not the minimum.  CPU core count and RAM minimums are proportional, as the build script attempts a parallel build if multiple cores are available.  Generally speaking, the machine needs 2 GB of RAM per core, so a 4 core machine should have at least 8 GB of RAM.  8 GB of RAM is required for a development environment with `nodeos` running.  Mainnet synchronization effectively requires 64 GB now (actually 80% of 64 GB, but no machine will be configured with 52 GB of RAM).  20 GB of available disk space is required to build.  An SSD is not required for a development machine, but is required to be a successful producer on a major network.  Mainnet synchronization requires 85 GB of free disk space before building.
