### ISSUE TITLE
Sane HTTP API  error responses

### ISSUE THREAD

**Issue by vovapi** [EOSIO/eos#4642]
At every error API returns HTTP 500 with body:
```json
{
  "code": 500,
  "message": "Internal Service Error",
  "error": {
    "code": 0,
    "name": "exception",
    "what": "unspecified",
    "details": [
      
    ]
  }
}
```
It would be nice to have some info on what went wrong in response.

**Comment by jgiszczak** [comment]
Run nodeos with `--verbose-http-errors true` or add it to your config.ini.
