### ISSUE TITLE
why  error where i executing  sh ./eosio_build.sh ??

### ISSUE THREAD

**Issue by lancesf** [EOSIO/eos#4643]
my os : centos7

why  error where i executing  sh ./eosio_build.sh ??
The following errors occurred :

**Comment by lancesf** [comment]
and eos check yum install dependency is error, my computer have git.. these software, eos say not found ....
eos is so troublesome and don't friendly!

**Comment by taokayan** [comment]
try to run ```./eosio_build.sh``` only to see what happens.

**Comment by lancesf** [comment]
@taokayan  have not changed at all, I've tried it several times... dependency is  not found ,and error

**Comment by 401825317** [comment]
@taokayan 
where are eosio_build.sh ?

**Comment by jgiszczak** [comment]
Unresponsive for 148 days.
