### ISSUE TITLE
Issue creating an account

### ISSUE THREAD

**Issue by leopangchan** [EOSIO/eos#4650]
I've been following this guide (https://developers.eos.io/eosio-nodeos/docs/learn-about-wallets-keys-and-accounts-with-cleos) to create an account onto the blockchain. I have created wallets, imported keys and unlocked them. However, I've got this error when I tried to create an account onto the blockchain.
![image](https://user-images.githubusercontent.com/16515271/42715352-72a9cdae-86ab-11e8-9020-65c48ffc8225.png)

I've tried too look for a solution on the internet. Some suggested this issue might be caused by cleos and keosd are not communicating on the same port. So, I used this command to force keosd to listen on `127.0.0.1:8900`. 
![image](https://user-images.githubusercontent.com/16515271/42715388-a4b50a5c-86ab-11e8-9298-fb6fa278e3da.png)

To run nodeos, I used this command: 
![image](https://user-images.githubusercontent.com/16515271/42715398-b722783c-86ab-11e8-822a-d8e808a15afb.png)

And, I used this command, which connects to the wallet via `127.0.0.1:8900`, to create an account :

> cleos --wallet-url=http://127.0.0.1:8900 create account -j eosio name OwnerPubKey ActivePubKey

However, telling the command to listen to `127.0.0.1:8900` didn't fix my issue. Please help!! I appreciate it so much!!

Note:
Also, I've added `http-validate-host = false` to my `~/eos-wallet/config.ini`, which is suggested in #4594. It didn't solve my issue either.

**Comment by jgiszczak** [comment]
You'll also need to add `--http-validate-host=false` to your nodeos command line.

**Comment by leopangchan** [comment]
@jgiszczak I've also tried that. I'm sorry I didn't mention in the description. Also, I'm not sure why allowing any host would fix the issue since I'm using my localhost anyways. I'm still new to network knowledge and EOS. Please help me.

**Comment by jgiszczak** [comment]
Host matching when it was first implemented required absolute precision up until the 1.10 release.  Such precision that `localhost:8888` did not match `127.0.0.1:8888` and the connection would be rejected.

Try adding `--verbose-http-errors` to your nodeos command line to see if you can get more details.

**Comment by leopangchan** [comment]
@jgiszczak I run the nodeos by using ./nodeos -e -p eosio --verbose-http-errors --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin
However, it didn't give me more detail.

**Comment by jgiszczak** [comment]
I don't see `--http-validate-host=false` in your command line.

**Comment by leopangchan** [comment]
My bad. I thought I need to add `--http-validate-host=false` in config.ini. It seems to fix the error, but I got a different error right now. 
<img width="785" alt="screen shot 2018-07-13 at 5 11 34 pm" src="https://user-images.githubusercontent.com/16515271/42718670-d2609930-86bf-11e8-9f0e-6284faad5dc0.png">

I've attempted to create new keys and a wallet to which the keys are imported, but I didn't fix it. Here is the command I used to create an account.
`cleos --wallet-url=http://127.0.0.1:8900 create account -j eosio name OwnerPubKey ActivePubKey`

**Comment by HomoEfficio** [comment]
In v1.0.10, I still got error even after I added `--http-validate-host=false` to the `nodeos` like below.

![14-07-2018-05-17-32](https://user-images.githubusercontent.com/17228983/42722611-cd01f446-8789-11e8-8d37-5f4c1af505d1.png)

**Comment by leopangchan** [comment]
@yang24201 You might try to add the flag in the command. The following works for me.
`./nodeos -e -p eosio --verbose-http-errors --http-validate-host=false --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin`

**Comment by andriantolie** [comment]
`cleos create account` also contacts your wallet (keosd) for signature. Try to start your keosd with `--http-validate-host=false` too (or you can also modify your keosd's config.ini which is located in your `~/eosio-wallet` by adding `http-validate-host=false`, no dash dash here)

**Comment by andriantolie** [comment]
@leopangchan do you have eosio private key in your keosd?

**Comment by leopangchan** [comment]
@andriantolie Yes, I've imported two pairs of public/private keys to my wallets. I do have a confusion here. Since I've created multiple wallets, which wallet does the command for creating account use? 

However, I've tried to import keys to all wallets, and unlock them, before I created an account. It still didn't work.

**Comment by leopangchan** [comment]
@andriantolie Hi, here are the outputs:
![image](https://user-images.githubusercontent.com/16515271/42769773-0fa31614-88d8-11e8-9737-a6158c8afa27.png)

**Comment by andriantolie** [comment]
Yes, looking from above, you haven't imported private key for eosio yet. Try to import it first.
`cleos wallet import 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3`

**Comment by leopangchan** [comment]
@andriantolie I've imported the private key to a wallet by using the following command. 
`cleos wallet import 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 -n mywallet`. However, I've found this #2749 saying that the eosio's private key is automatically imported. Could you please clarify this?

**Comment by jgiszczak** [comment]
#2749 is obsolete.  Having the test key automatically added to all wallets led to people confusing it with their own keys and setting the wrong keys on their mainnet accounts, which led to account hijacking.  No longer automatically adding keys helps prevent that problem.
