### ISSUE TITLE
"CODE AS LAW" Impeachment code and Compliance Contract Validation Code

### ISSUE THREAD

**Issue by controllinghand** [EOSIO/eos#4651]
# Code as Law
## Impeachment code and Compliance Contract Validation Code
All BPs sign a regproducer ricardian contract found here: https://github.com/EOS-Mainnet/governance/blob/master/eosio.system/eosio.system-regproducer-rc.md

Currently there is no automated way to validate that said BP is in compliance with the ricardian contract they signed.  Also, there is no automated way to enforce removal if they break the contract.

I propose that code should be written to reduce the need for human intervention.

1) Compliance Validation: code that will be put into the chain to validate the regproducer ricardian contract.  Things like validating that BP has a website, have an ownership disclouser, don't miss block production and any other items found in the regproducer contract.  Anything that can't be programed will be handled by human intervention until which time technology is improved to do so.

2) Impeachment code:  This code will remove a BP from the block producers list.  This code could be called from the Compliance Validation code above if it finds a BPs has fallen out of compliance.  Said BP will need to fix the violation and re-apply and re-sign a new regproducer ricardian contract and have to pass the Compliance Validation in order to be placed back on the BP ballot list.

In the interim, BPs can use the impeachment code if evidence shows any BP have violated the regproducer ricardian contract by majority vote.

The overall goal, is to take the decision process out of the BPs hands and the overall EOS community hands.  Both the Compliance Validation and the Impeachment Code should be reviewed and vote on by the community with majority vote before implementation.

**Comment by controllinghand** [comment]
https://drive.google.com/file/d/1vwwcfEDoxYQUyXF4czuLQ7rbFPo1wE25/view?usp=sharing

![image](https://user-images.githubusercontent.com/31561227/42718995-290aa70e-86c4-11e8-8780-cfacce795f29.png)

some thoughts on what can be coded and what can't

**Comment by wanderingbort** [comment]
This is not the appropriate place to discuss this issue.  This repo is for the reference EOSIO blockchain implementation.  I do not want to suggest the "correct" repository for discussions of governance as there are several communities and several chains based on EOSIO.  However, the repo where you referenced the ricardian contract *may* be an appropriate place for your specific concerns.  The maintainers of that repo will have to decide for themselves.  

If there is a request for a *reference* implementation of a specific type contract that can be made in the [eosio.contracts repo](https://github.com/EOSIO/eosio.contracts) and it will be triaged appropriately by that team.   **However**, I stress that neither repo are the appropriate place do discuss the governance of any active or hypothetical chain based on the EOSIO software.

**Comment by controllinghand** [comment]
I'm disappointed that we have to look for other ways to provide governance.  I was under the impression that EOS has a governance aspect to the software?
