### ISSUE TITLE
Cannot sell ram - is it possible that the actual RAM consumption is higher than shown?

### ISSUE THREAD

**Issue by filipniziol** [EOSIO/eos#4653]
Check irespooracle contract:
https://eosflare.io/account/irespooracle

**- 154 KB shown as used**
**- 210 KB available**

**- 171 KB .wast file size on local disk**
**- 200 KB size of all 5 files on local disk**

Check the contracts:
https://github.com/irespo/irespo/tree/master/irespo/irespooracle

**I could not sell RAM.**

Is it possible that the RAM calculation is wrong and the total size is higher?

**Comment by andriantolie** [comment]
How much ram are you trying to sell? You need to ensure you have an adequate amount of RAM after you sell the ram

And also have you cleared the data that you stored previously? I saw your git history, you have other tables in the past

**Comment by taokayan** [comment]
This is duplicated issue. Please refer to https://github.com/EOSIO/eos/issues/4517
