### ISSUE TITLE
eosio 1.0.10, http-server-address = 0.0.0.0:8888 not working!

### ISSUE THREAD

**Issue by newbieh4cker** [EOSIO/eos#4654]
few days a go, I issued 0.0.0.0 problem.
https://github.com/EOSIO/eos/issues/4607

updated eosio to 1.0.10, but still 0.0.0.0 doesn't work

**Comment by wanderingbort** [comment]
Are there any other things about your deployment that may be relevant?

what OS are you on, is "my_public_ip" actually bound to the box or is it NAT'd/Load balanced through something before it hits your endpoint?

**Comment by wanderingbort** [comment]
Barring a bug, the checks should allow the `Host: ` header (you can see this with `curl -v` to be the actual IP you connect to.  It would help to have the output of `curl -v`

**Comment by newbieh4cker** [comment]
@wanderingbort 
setting "http-validate-host=false" solved problem.
But, I don't think it is safe or stable way to solve.
