### ISSUE TITLE
Build validation mongo issues

### ISSUE THREAD

**Issue by joaoritter** [EOSIO/eos#4656]
Following the tutorial at https://developers.eos.io/eosio-nodeos/docs/build-validation

![image](https://user-images.githubusercontent.com/5597861/42728070-df0e97c0-8766-11e8-8214-d51c141fad90.png)

`build test ` gets stuck on job 27/37

**Comment by lazaridiscom** [comment]
> gets stuck on job 27/37

@joaoritter , initially it looked like 27 stucks on my side, too. But finally it just takes 4000 times longer than the earlier tests...

```shell
26/41 Test #26: validate_payloadless_abi .............   Passed    0.09 sec
      Start 27: unit_test_binaryen
27/41 Test #27: unit_test_binaryen ...................   Passed  390.64 sec
      Start 28: unit_test_wavm
```

now, test 28 still not finished, possibly it takes even longer than test 27.

Issue: tests should provide more progress feedback

**Comment by lazaridiscom** [comment]
related: #4833

**Comment by heifner** [comment]
@lazaridiscom There are various options for progress feedback. See: https://cmake.org/cmake/help/latest/manual/ctest.1.html

**Comment by halsaphi** [comment]
Closed as refers to old version of code.
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
