### ISSUE TITLE
Not able to debug: Error 3050003: eosio_assert_message assertion failure

### ISSUE THREAD

**Issue by KennyLiu25775** [EOSIO/eos#4657]
Hey guys i dont know why the program won't print the exact bug message just like what was written in the smart contract...:
what was in the the eosio.token contract:
![image](https://user-images.githubusercontent.com/11808716/42729224-6d8df0e0-8785-11e8-80aa-8e2f4b77afbc.png)
the error message that i got:
![image](https://user-images.githubusercontent.com/11808716/42729230-81855ec6-8785-11e8-8cb7-d7885fb6224a.png)

**Comment by jgiszczak** [comment]
Add `verbose-http-errors = true` to the nodeos config.ini to get full text of assertion failures.  Pruning of error messages in default mode is known to be overaggressive.  There is a plan to restore some detail to the default verbosity level.

**Comment by boy-good** [comment]
i also has this error. Are you solve this problem?

**Comment by yuanbi** [comment]
i also has this error. Are you solve this problem?
