### ISSUE TITLE
get no result when run curl http://localhost:8888/v1/chain/get_info

### ISSUE THREAD

**Issue by past2017** [EOSIO/eos#4658]
I install eosio by https://developers.eos.io/eosio-nodeos/docs/docker-quickstart
docker
step 1:
```
1. docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

step 2 
`docker pull eosio/eos-dev`
step 3
`docker run --rm --name eosio -d -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev  /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console"`
step 4. docker logs --tail 5 eosio
```
2776000ms thread-0   producer_plugin.cpp:1087      produce_block        ] Produced block 0000eb8e345760be... #60302 @ 2018-07-15T00:46:16.000 signed by eosio [trxs: 0, lib: 60301, confirmed: 0]
2776500ms thread-0   producer_plugin.cpp:1087      produce_block        ] Produced block 0000eb8f667e1a37... #60303 @ 2018-07-15T00:46:16.500 signed by eosio [trxs: 0, lib: 60302, confirmed: 0]
2777000ms thread-0   producer_plugin.cpp:1087      produce_block        ] Produced block 0000eb90713f73dc... #60304 @ 2018-07-15T00:46:17.000 signed by eosio [trxs: 0, lib: 60303, confirmed: 0]
2777500ms thread-0   producer_plugin.cpp:1087      produce_block        ] Produced block 0000eb91d20d51b1... #60305 @ 2018-07-15T00:46:17.500 signed by eosio [trxs: 0, lib: 60304, confirmed: 0]
2778000ms thread-0   producer_plugin.cpp:1087      produce_block        ] Produced block 0000eb92edcce82a... #60306 @ 2018-07-15T00:46:18.000 signed by eosio [trxs: 0, lib: 60305, confirmed: 0]
```

step 5: docker ps and netstan
![image](https://user-images.githubusercontent.com/25541244/42729486-997a1a08-880c-11e8-8b6b-984f92698faa.png)

step 6:
curl http://localhost:8888/v1/chain/get_info
```
eos@bkex-real-wallet-usdt-3:~/image/eos/Docker$ curl http://localhost:8888/v1/chain/get_info
eos@bkex-real-wallet-usdt-3:~/image/eos/Docker$ 
eos@bkex-real-wallet-usdt-3:~/image/eos/Docker$
```
it looks step 1~step 4 run well, but run step 5, i get nothing
Please help me, thank you very much

**Comment by wanderingbort** [comment]
Please try curl with http://127.0.0.1:8888 or whitelist the use of the
localhost by adding it as an alias with `--http-alias=localhost:8888` on
the docker run command line for nodeos

**Comment by past2017** [comment]
it looks --http-validate-host=false  should be set

**Comment by lijameshao** [comment]
try
curl http://0.0.0.0:8888/v1/chain/get_info

**Comment by lcgogo** [comment]
--http-validate-host=false is work for me.

**Comment by CoderMudy** [comment]
where should i set http-validate-host=false

**Comment by CoderMudy** [comment]
oh i know
