### ISSUE TITLE
Invalid Reference Block Transaction's reference block did not match

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#4659]
We start a program to sync our accounts' transactions, but meet some errors from the noodes. 
It seems that the transacations did not belong to the main network, but It should not happen because our transactions are always send to the main network. 
I wonder in what circumstances that would happend??? The details of errors are below:

```
2366835ms thread-0   net_plugin.cpp:2547           operator()           ] accept txn threw  3040007 invalid_ref_block_exception: Invalid Reference Block
Transaction's reference block did not match. Is this transaction from a different fork?
    {"tapos_summary":{"block_id":"00588a114f3146c2dae54a1926812a7b7e8d5915ea4ffc917dac847cdd3e977e"}}
    thread-0  controller.cpp:1544 validate_tapos

    {}
    thread-0  controller.cpp:1545 validate_tapos
2366840ms thread-0   net_plugin.cpp:2547           operator()           ] accept txn threw  3040007 invalid_ref_block_exception: Invalid Reference Block
Transaction's reference block did not match. Is this transaction from a different fork?
    {"tapos_summary":{"block_id":"00588a139fbcfbb7650ad718a8e72ffc97d304721744c56cf2e3518cb510782f"}}
    thread-0  controller.cpp:1544 validate_tapos

    {}
    thread-0  controller.cpp:1545 validate_tapos
2366840ms thread-0   net_plugin.cpp:2547           operator()           ] accept txn threw  3040007 invalid_ref_block_exception: Invalid Reference Block
Transaction's reference block did not match. Is this transaction from a different fork?
    {"tapos_summary":{"block_id":"00588a114f3146c2dae54a1926812a7b7e8d5915ea4ffc917dac847cdd3e977e"}}
    thread-0  controller.cpp:1544 validate_tapos

    {}
    thread-0  controller.cpp:1545 validate_tapos
```

**Comment by andriantolie** [comment]
What action that you did to produce the above error messages? Normally the above error message appears when you are referring a block at a fork.

**Comment by guaiguaihw** [comment]
The actions are transfer. @andriantolie

**Comment by andriantolie** [comment]
Are you sending the transaction to the same node where you get your reference block from?

**Comment by guaiguaihw** [comment]
@andriantolie We use A node to send transaction, use B node to get actions. Each node are connected to main network. We use http api to get and send transaction, not cleos. Is It possible that we don't use the same node that cause the error? But two nodes all sync the main network, It can not fork orther chain.

**Comment by andriantolie** [comment]
Are both nodes head block on par? Or if they differ, how large is the gap?

Which block did you use as reference block? Try to use the last irreversible block between two nodes as the reference block to ensure that the ref block exists in both nodes. And also, you can't refer to a block older than MAX(uint16_t) from head block since ref_block_num is an uint16_t type

**Comment by guaiguaihw** [comment]
ok, we will pay more attention to what you have mentioned, thanks a lot @andriantolie

**Comment by csquan** [comment]
I have seen log
“maybe_switch_forks   ] switching forks from ...” ,then error log"Transaction's reference block did not match. Is this transaction from a different fork?" show,what happened?

**Comment by csquan** [comment]
why fork?none got this?

**Comment by taokayan** [comment]
Soft fork is a normal situation on EOS blockchain. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.

**Comment by hama** [comment]
Same issue

**Comment by lixiaodong** [comment]
same issue!
