### ISSUE TITLE
cleos wallet create and Failed with error: Assert Exception (10) response_content_length >= 0: Invalid content-length response

### ISSUE THREAD

**Issue by okayplanet** [EOSIO/eos#4664]
I just updated to 3c6134c68fa4d52df58955bc1a1475f7adbf3cfa, and removed ~/.local/share/eosio for a fresh go.

I executed `./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin`

Then tried `cleos wallet create` and was met with some errors.  Any ideas?

```
okayplanet@okaybox:~/dev/eos/eos/build/programs/cleos$ ./cleos wallet create
755308ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)
response_content_length >= 0: Invalid content-length response

okayplanet@okaybox:~/dev/eos/eos/build/programs/cleos$ ./cleos wallet create -n hmmmmmmm
761519ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)
response_content_length >= 0: Invalid content-length response
```

**Comment by okayplanet** [comment]
I got it working by referencing issues #4637 and #4594.  But I had to change the config.ini in the ~/.eosio-wallet folder, which actually didn't exist for me.

**Comment by andriantolie** [comment]
It should be `~/eosio-wallet` instead of `~/.eosio-wallet`.

**Comment by rosselpha** [comment]
where can I find ~/eosio-wallet

**Comment by sunyoubo** [comment]
I am working like this: $ cleos --wallet-url http://127.0.0.1:8888 wallet create
