### ISSUE TITLE
Full node follows p2p endpoint of bp node so slow!

### ISSUE THREAD

**Issue by ridewindx** [EOSIO/eos#4668]
I got public p2p endpoint list from https://eosnodes.privex.io/?config=1, and paste them into my config.ini.
But a few days ago, I found the syncing speed is so slow like a turtle. Averagely 0.5s per block.
My cloud servers are on Google Cloud and Aliyun, located in Taiwan and Shenzhen, China.
So when can I catch up with the latest block? Never?

![_20180716113135](https://user-images.githubusercontent.com/1844879/42742256-0bd01974-88ec-11e8-8c24-cf30908b0e01.png)

Please tell me how to optimize the syncing speed. Like build private vpn connection with some bp node?

**Comment by nanmu42** [comment]
Encountered the same situation:

* running in docker
* `p2p-peer-address` from https://eosnodes.privex.io/?config=1
* sync is so slow that node is not able to catch up with main stream

**Comment by jgiszczak** [comment]
Bare metal is preferred.  Run on the highest clock frequency CPUs you can find.  `nodeos` is single-threaded, so large core counts are a detriment, not a help.  Bare metal on a base clock of 4.2 GHz Kaby Lake will certainly be able to keep up.  Base clock of 2.6 GHz may not be fast enough.

**Comment by liviu-** [comment]
Try increasing `sync-fetch-span` in the `config.ini` for `nodeos`

**Comment by redpolarbear** [comment]
We are using the bare metal as the server machine.

- CPU: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
- Memory: 184G
- SSD
- running in the docker

but the problem for us is that some times the sync speed is very fast, but some times it's very slow.
it doesn't look like that the hardware is holding down the speed. 

`received signed_block : #5952230 block age in secs = 144900`
`received signed_block : #5952233 block age in secs = 144901`
`received signed_block : #5952235 block age in secs = 144902`

the num of the block is increasing, but the `age in secs` is increasing as well, which means the speed is slow and can't keep up the main net.

Is it related to the p2p network?

**Comment by jgiszczak** [comment]
It's the network.  Mainnet is seeing a block with 200 transactions in it every 12 blocks for at least the past several hours.  Possibly many hours.  This is resulting in considerably longer processing time than normal for slower CPUs.  Non-producing nodes will need to be much closer in specification to producer nodes to handle the load until it abates.  (It appears to be artificial load, rather than organic demand.)  A lower specification non-producing node should eventually catch up once the transaction rate drops again.  Judging by the duration, someone with a _lot_ of staked EOS is inducing the load.

**Comment by redpolarbear** [comment]
Thanks, @jgiszczak for your quick response. 

It's really slow to sync back to the main net. just as you said, especially when the blocks contained many tranxs. Do we have any method to tune the configuration to speed up? e.g. disable some plugins? change the stack size?

any advice is appreciated.

**Comment by ridewindx** [comment]
@jgiszczak Thanks for your reply. If BPs' non-producing full nodes do not have so high-performance hardware to supply public endpoint api service, is it their irresponsibility? After my testing, my cloud server can sync and process any many incoming transactions, and the only bottleneck is the incoming speed of net packets from the mainnet.

@redpolarbear No other tuning methods. Just wait for the syncing until latest enough. My nodeos have catched up with the mainnet head.

**Comment by matthewdarwin** [comment]
I have noticed this problem on a machine with 2.4GHz CPU... if you try to sync from scratch, nodeos takes way too much CPU and cannot keep up with all the big blocks we have right now.    I also tried to restore from 1 hour old backup, it can still not catch up.  (Restore from 5 minute old backup is fine).   It appears that when nodeos is current, then it uses much less CPU and can keep up with blocks fine.

Why does nodeos take so much CPU when processing older blocks?
(My tests have been running for several days now)

**Comment by jgiszczak** [comment]
There is no configuration tuning that will help, but...
[Good news everyone!](http://gifimage.net/wp-content/uploads/2017/11/good-news-everyone-gif-4.gif)
EOS.IO v1.1 has a change that disables speculative execution while synching, which substantially reduces the CPU time required to process irreversible blocks incoming over the network.  We're estimating as much as a factor of 10 speedup.  This should allow low spec CPUs to catch up to mainnet much more readily.  Look for the v1.1 release later today.

**Comment by matthewdarwin** [comment]
Sounds excellent!

**Comment by lcgogo** [comment]
@jgiszczak  I have not find the 1.1 docker image in docker hub. When will it upload to docker hub? Now the latest one is v1.0.10.
Tag Name    Compressed Size     Last Updated
latest           83 MB                       5 days ago
v1.0.10         83 MB                       5 days ago

**Comment by jgiszczak** [comment]
The 1.1 Docker image was uploaded 2 hours ago.  Your patience is appreciated.
