### ISSUE TITLE
eosiosystem::authority cannot be serialized to eosio::chain::authority

### ISSUE THREAD

**Issue by alienzin** [EOSIO/eos#4669]
I'm trying to create new account in my contract.

If I define the same authority structure as eosio::chain::authority, there's no problem for newaccount.
(which has vector<wait_weight> waits rather than delay_sec)

    struct wait_weight {
        uint32_t wait_sec;
        weight_type weight;
    };
    struct authority {
        uint32_t threshold;
        vector<eosiosystem::key_weight> keys;
        vector<eosiosystem::permission_level_weight> accounts;
        vector<wait_weight> waits;
    };

    eosiosystem::key_weight keyweight = { .key = pubkey,  .weight = 1 };
    authority               ownerkey  = { .threshold = 1, .keys = { keyweight }, .accounts = {}, .waits = {} };
    authority               activekey = { .threshold = 1, .keys = { keyweight }, .accounts = {}, .waits = {} };

    action(
        permission_level{ _self, N(active) },
        N(eosio), N(newaccount),
        make_tuple(_self, new_account_name, ownerkey, activekey)
    ).send();

But if I try to use eosiosystm::authority like following, I get errors.
(which has delay_sec rather than waits)

    eosiosystem::key_weight keyweight = { .key = pubkey,  .weight = 1 };
    eosiosystem::authority  ownerkey  = eosiosystem::authority { .threshold = 1, .delay_sec = 0, .keys = { keyweight }, .accounts = {} };
    eosiosystem::authority  activekey = eosiosystem::authority { .threshold = 1, .delay_sec = 0, .keys = { keyweight }, .accounts = {} };

    action(
        permission_level{ _self, N(active) },
        N(eosio), N(newaccount),
        make_tuple(_self, new_account_name, ownerkey, activekey)
    ).send();

console error
> 2419603ms thread-0   http_plugin.cpp:468           handle_exception     ] FC Exception encountered while processing chain.push_transaction
2419603ms thread-0   http_plugin.cpp:469           handle_exception     ] Exception Details: 10 assert_exception: Assert Exception
w < count():
    {}
    thread-0  static_variant.hpp:339 set_which
Error unpacking field _storage
    {"field":"_storage"}
    thread-0  raw.hpp:368 operator()
error unpacking fc::crypto::public_key
    {"type":"fc::crypto::public_key"}
    thread-0  raw.hpp:616 unpack
Error unpacking field key
    {"field":"key"}
    thread-0  raw.hpp:368 operator()
error unpacking eosio::chain::key_weight
    {"type":"eosio::chain::key_weight"}
    thread-0  raw.hpp:616 unpack
Error unpacking field keys
    {"field":"keys"}
    thread-0  raw.hpp:368 operator()
error unpacking eosio::chain::authority
    {"type":"eosio::chain::authority"}
    thread-0  raw.hpp:616 unpack
Error unpacking field active
    {"field":"active"}
    thread-0  raw.hpp:368 operator()
error unpacking eosio::chain::newaccount
    {"type":"eosio::chain::newaccount"}
    thread-0  raw.hpp:616 unpack
error unpacking eosio::chain::newaccount
    {"type":"eosio::chain::newaccount"}
    thread-0  raw.hpp:660 unpack
    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:62 exec_one

I referred to #4438 so I'm trying to use latest authority structure.
Is there any good way to use eosiosystem::authority ?

**Comment by andriantolie** [comment]
Which eos version are you using? Is it v1.0.10?

**Comment by alienzin** [comment]
yes. i'm using eos v1.0.10

**Comment by tbfleming** [comment]
It's a bug. Concise description is now in #4684.

**Comment by alienzin** [comment]
@tbfleming Thanks.

**Comment by saltbo** [comment]
Hello,  how to defined keyweight by eosio.cdt?

I use the public_key from crypto.hpp replace  eosiosystem::key_weight,

But, I got a error public_key.

```
    struct permission_level_weight {
        permission_level permission;
        uint16_t weight;
    };

    struct wait_weight {
        uint32_t wait_sec;
        uint16_t weight;
    };

    struct key_weight {
        public_key key;
        uint16_t weight;
    };

    struct authority {
        uint32_t threshold = 0;
        vector<key_weight> keys;
        vector<permission_level_weight> accounts;
        vector<wait_weight> waits;
    };

    std::array<char, 33> data;
    std::copy(pubkey.begin(), pubkey.end(), data.data());
    print(data.data());

    key_weight keyweight = {.key = public_key{.type = 0, .data = data}, .weight = 1};
    authority owner = {.threshold = 1, .keys = {keyweight}, .accounts = {}, .waits = {}};
    authority active = {.threshold = 1, .keys = {keyweight}, .accounts = {}, .waits = {}};
```

My public_key is `EOS7WGdLRwPeR7AgEwp5AfcEMhxCz8tXtsD1iLgbYpPzqehkaUusW`
but it be set to `EOS3KjJRdcon8KoinC8oaeewKC7Dw7xrRpPvNtj49EhJABq4m5dNoi`
