### ISSUE TITLE
incoming message length unexpected (1347703880)

### ISSUE THREAD

**Issue by stev1988** [EOSIO/eos#4670]
sending to peer eosapi.blockmatrix.network:13546: Broken pipe
2666840ms thread-0   net_plugin.cpp:2160           operator()           ] incoming message length unexpected (1347703880)
2674265ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from p2p.one.eosdublin.io:9876: Connection reset by peer
2695396ms thread-0   net_plugin.cpp:1970           connect              ] host: eosapi.blockmatrix.network port: 13546 
2695396ms thread-0   net_plugin.cpp:1970           connect              ] host: pub1.eostheworld.io port: 9876 
2695396ms thread-0   net_plugin.cpp:1970           connect              ] host: fn001.eossv.org port: 443 
2695396ms thread-0   net_plugin.cpp:1970           connect              ] host: p2p.one.eosdublin.io port: 9876 
2695396ms thread-0   net_plugin.cpp:1970           connect              ] host: eos.nodepacific.com port: 9876 
2695396ms thread-0   net_plugin.cpp:1970           connect              ] host: mainnet.genereos.io port: 80 
2698127ms thread-0   net_plugin.cpp:2190           operator()           ] Peer eos.nodepacific.com:9876 closed connection
2698127ms thread-0   net_plugin.cpp:2190           operator()           ] Peer fn001.eossv.org:443 closed connection
2698127ms thread-0   net_plugin.cpp:2190           operator()           ] Peer pub1.eostheworld.io:9876 closed connection
2698127ms thread-0   net_plugin.cpp:2190           operator()           ] Peer eosapi.blockmatrix.network:13546 closed connection
2698128ms thread-0   net_plugin.cpp:2160           operator()           ] incoming message length unexpected (1347703880)

**Comment by jgiszczak** [comment]
Peers in the various seed lists are frequently out of date.  Nodes may be down or inaccessible.  Nodes may also have reached their connection limits.  If you have `net_api_plugin` initialized in config.ini, you may remove non-responsive peers using cleos without restarting, e.g. `cleos net disconnect p2p.one.eosdublin.io:9876`.  Note you will also have to remove them from config.ini, or the endpoint will be re-added the next time nodeos restarts.

**Comment by jgiszczak** [comment]
Perhaps v1.0.8 was successful when you last launched it.  Availability of nodes changes from day to day, and is not guaranteed to be the same by the time another release is available.  The errors are benign as long as at least one connection succeeds.  It's just noise in the log.  If you'd prefer not to see the errors, add `net_api_plugin` so you can eliminate them, or remove nonresponsive nodes from config.ini.
