### ISSUE TITLE
How to use cleos to create a delayed transaction and cancel the transaction.

### ISSUE THREAD

**Issue by mycamphortree** [EOSIO/eos#4672]
hi ，
    How to use cleos to create a delayed transaction and cancel the transaction？Can you provide a simple example?

**Comment by andriantolie** [comment]
There is no option to set the transaction delay using cleos. However, you can use `cleos push transaction` to achieve this. You will need to first pack the action and sign the transaction manually beforehand. For the structure of transaction JSON, you can refer to signed_transaction inside `libraries/chain/include/eosio/chain/transaction.hpp`. And to make it a delayed transaction, you need to set the delay_sec in the transaction header larger than 0. After that, you can cancel it by using `cleos system canceldelay`.
