### ISSUE TITLE
EOSIO_ABI

### ISSUE THREAD

**Issue by compjotr** [EOSIO/eos#4673]
Why does the tic tutorial have EOSIO_ABI at the bottom, but not on the final github code?
I'm gettting errors when having the EOSIO_ABI at the bottom of the c++ file. 
error: a namespace name is not allowed.

**Comment by jgiszczak** [comment]
EOSIO_ABI must be truly at the very bottom of the file, outside of all namespaces.  In particular, it must come after the end of the `eosio` namespace which contracts are in.  The macro contains an `extern "C" {}` directive.
