### ISSUE TITLE
I would like to create an EOS account and facing errors. Please help me out. 

### ISSUE THREAD

**Issue by doubleconnect1** [EOSIO/eos#4674]
Is my command line right? 

daeyeonjo@daeyeonjo-All-Series:~/eos/contracts$ cleos --url http://node2.liquideos.com:8888 system newaccount --stake-net 30 --stake-cpu 30 --buy-ram 10 g44tiojygige nowcoincount EOS838q5ocmCU1tfHJYyaRmd2jPXHaD5Dr6fcDc6JYYdUBh9obzLc EOS838q5ocmCU1tfHJYyaRmd2jPXHaD5Dr6fcDc6JYYdUBh9obzLc

2029616ms thread-0   asset.cpp:79                  from_string          ] 3010012 asset_type_exception: Invalid asset
Asset's amount and symbol should be separated with space
    {}
    thread-0  asset.cpp:42 from_string
2029616ms thread-0   asset.cpp:79                  from_string          ] from: 10
Error 3010012: Invalid asset
Error Details:
Asset's amount and symbol should be separated with space
rethrow

-----------------------------------------------------------------------------------------------------------------------------------------
I checked other discussion about this issue, tried the following and got another error.   

daeyeonjo@daeyeonjo-All-Series:~/eos/contracts$ cleos --url http://node2.liquideos.com:8888 system newaccount --stake-net '30.0000 EOS' --stake-cpu '30.0000 EOS'--buy-ram '10.0000 EOS' g44tiojygige nowcoincount EOS838q5ocmCU1tfHJYyaRmd2jPXHaD5Dr6fcDc6JYYdUBh9obzLc EOS838q5ocmCU1tfHJYyaRmd2jPXHaD5Dr6fcDc6JYYdUBh9obzLc
ERROR: ExtrasError: [EOS838q5ocmCU1tfHJYyaRmd2jPXHaD5Dr6fcDc6JYYdUBh9obzLc]
Create an account, buy ram, stake for bandwidth for the account
Usage: cleos system newaccount [OPTIONS] creator name OwnerKey [ActiveKey]

Positionals:
  creator TEXT                The name of the account creating the new account (required)
  name TEXT                   The name of the new account (required)
  OwnerKey TEXT               The owner public key for the new account (required)
  ActiveKey TEXT              The active public key for the new account

Options:

**Comment by doubleconnect1** [comment]
I tried another command line and got the following error.
Error 3050003: eosio_assert_message assertion failure
Any idea to solve this matter?

daeyeonjo@daeyeonjo-All-Series:~/eos/contracts$ cleos --url http://node2.liquideos.com:8888 system newaccount --stake-net '30.0000 EOS' --stake-cpu '30.0000 EOS' --buy-ram-kbytes 8  g44tiojygige nowcoincount EOS838q5ocmCU1tfHJYyaRmd2jPXHaD5Dr6fcDc6JYYdUBh9obzLc EOS838q5ocmCU1tfHJYyaRmd2jPXHaD5Dr6fcDc6JYYdUBh9obzLc

260959ms thread-0   main.cpp:429                  create_action        ] result: {"binargs":"a09863fe5197096190a7a6683a8a389d00200000"} arg: {"code":"eosio","action":"buyrambytes","args":{"payer":"g44tiojygige","receiver":"nowcoincount","bytes":8192}}
262428ms thread-0   main.cpp:429                  create_action        ] result: {"binargs":"a09863fe5197096190a7a6683a8a389de09304000000000004454f5300000000e09304000000000004454f530000000000"} arg: {"code":"eosio","action":"delegatebw","args":{"from":"g44tiojygige","receiver":"nowcoincount","stake_net_quantity":"30.0000 EOS","stake_cpu_quantity":"30.0000 EOS","transfer":false}}

Error 3050003: eosio_assert_message assertion failure

**Comment by jgiszczak** [comment]
The g44tiojygige account only has 41.5705 EOS available.  You're trying to stake 60 EOS.  Free up some of the 335 EOS staked or buy more EOS.

**Comment by doubleconnect1** [comment]
Thank you very much for your comment.
