### ISSUE TITLE
contracts/eosio.system/native.hpp has incorrect definitions

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#4684]
The `authority` struct is incorrect. This header should be checked for other incorrect definitions.

This caused #4669

**Comment by andresberrios** [comment]
That `authority` struct has `delay_sec`, which from https://github.com/EOSIO/eos/issues/4438 I understood is the new format. I haven't been able to use this one nor handmade ones to match the `waits` field in libraries/chain. I'm trying to do an inline action to `updateauth` with no success. I don't understand what is the new format of the `authority` struct and what is the old.

**Comment by andresberrios** [comment]
I've explained better and given an update here: https://github.com/EOS-Mainnet/eos/issues/61

I would fix this myself and send PR but I'm lost. The way in which the action data is unpacked seems to be the same for `apply_eosio_updateauth` and `apply_eosio_newaccount`, so I don't understand what could be going wrong.

Should I create a separate issue for this? As it seems unrelated to the actual format of either `waits` or `delay_sec` in the authority struct.

**Comment by heifner** [comment]
Fixed by: https://github.com/EOSIO/eosio.contracts/pull/90
