### ISSUE TITLE
cleos can't get my account.  

### ISSUE THREAD

**Issue by doubleconnect1** [EOSIO/eos#4685]
I created an account as follows and immediately asked cleos to get the newly created account and got 
the following error:

daeyeonjo@daeyeonjo-All-Series:~/eos/contracts$ cleos --url http://node2.liquideos.com:8888 get account nowcoincount
3202740ms thread-0   main.cpp:2712                 main                 ] Failed with error: Assert Exception (10)
response_content_length >= 0: Invalid content-length response

[account creation command]

daeyeonjo@daeyeonjo-All-Series:~/eos$ cleos --url http://node2.liquideos.com:8888 system newaccount --stake-net '10.0000 EOS' --stake-cpu '10.0000 EOS' --buy-ram-kbytes 8  g44tiojygige nowcoincount EOS838q5ocmCU1tfHJYyaRmd2jPXHaD5Dr6fcDc6JYYdUBh9obzLc EOS838q5ocmCU1tfHJYyaRmd2jPXHaD5Dr6fcDc6JYYdUBh9obzLc

[account creation result]

1020677ms thread-0   main.cpp:429                  create_action        ] result: {"binargs":"a09863fe5197096190a7a6683a8a389d00200000"} arg: {"code":"eosio","action":"buyrambytes","args":{"payer":"g44tiojygige","receiver":"nowcoincount","bytes":8192}}
1022144ms thread-0   main.cpp:429                  create_action        ] result: {"binargs":"a09863fe5197096190a7a6683a8a389da08601000000000004454f5300000000a08601000000000004454f530000000000"} arg: {"code":"eosio","action":"delegatebw","args":{"from":"g44tiojygige","receiver":"nowcoincount","stake_net_quantity":"10.0000 EOS","stake_cpu_quantity":"10.0000 EOS","transfer":false}}
executed transaction: 0c60724d1b76ea5ab82f0bf14dfc15a04da7f707cba86b7fc8d60452a85c132e  336 bytes  6340 us
#         eosio <= eosio::newaccount            {"creator":"g44tiojygige","name":"nowcoincount","owner":{"threshold":1,"keys":[{"key":"EOS838q5ocmCU...
#         eosio <= eosio::buyrambytes           {"payer":"g44tiojygige","receiver":"nowcoincount","bytes":8192}
#   eosio.token <= eosio.token::transfer        {"from":"g44tiojygige","to":"eosio.ram","quantity":"2.7955 EOS","memo":"buy ram"}
#  g44tiojygige <= eosio.token::transfer        {"from":"g44tiojygige","to":"eosio.ram","quantity":"2.7955 EOS","memo":"buy ram"}
#     eosio.ram <= eosio.token::transfer        {"from":"g44tiojygige","to":"eosio.ram","quantity":"2.7955 EOS","memo":"buy ram"}
#   eosio.token <= eosio.token::transfer        {"from":"g44tiojygige","to":"eosio.ramfee","quantity":"0.0141 EOS","memo":"ram fee"}
#  g44tiojygige <= eosio.token::transfer        {"from":"g44tiojygige","to":"eosio.ramfee","quantity":"0.0141 EOS","memo":"ram fee"}
#  eosio.ramfee <= eosio.token::transfer        {"from":"g44tiojygige","to":"eosio.ramfee","quantity":"0.0141 EOS","memo":"ram fee"}
#         eosio <= eosio::delegatebw            {"from":"g44tiojygige","receiver":"nowcoincount","stake_net_quantity":"10.0000 EOS","stake_cpu_quant...
#   eosio.token <= eosio.token::transfer        {"from":"g44tiojygige","to":"eosio.stake","quantity":"20.0000 EOS","memo":"stake bandwidth"}
#  g44tiojygige <= eosio.token::transfer        {"from":"g44tiojygige","to":"eosio.stake","quantity":"20.0000 EOS","memo":"stake bandwidth"}
#   eosio.stake <= eosio.token::transfer        {"from":"g44tiojygige","to":"eosio.stake","quantity":"20.0000 EOS","memo":"stake bandwidth"}
warning: transaction executed locally, but may not be confirmed by the network yet

**Comment by andriantolie** [comment]
Your account is indeed created https://eospark.com/MainNet/account/nowcoincount

Try again with v1.0.10, it should work.
