### ISSUE TITLE
how to change owner permissions?

### ISSUE THREAD

**Issue by wangyilin1987** [EOSIO/eos#4686]
hi,i want to change account's owner permissions to other private keys,i try this,but get a error:
cleos set account permission teswangyilin owner '{"threshold":1,"keys":  [{"key": "EOS7fcmyJExx1N72z49QDJqLBfATNzgAJ6aTcgpZAwPbyTnemmYkt","weight": 1}] ,"accounts":[]}' owner -p teswangyilin@owner
error log:
1953216ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 3050000 action_validate_exception: action exception
Cannot set an authority as its own parent
    {}
    thread-0  eosio_contract.cpp:214 apply_eosio_updateauth

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:62 exec_one

and,i try this, is success, but this is give owner permissions to other,is not i want,
cleos set account permission teswangyilin owner '{"threshold":1,"keys":[],"accounts":[{"permission":{"actor":"eoswangyilin","permission":"active"},"weight":1}],"waits":[]}' -p teswangyilin@owner

How do I get what I want?thank you

**Comment by andriantolie** [comment]
Don't put owner again as your permission's parent. Owner permission should not have any parent, i.e.
```
cleos set account permission teswangyilin owner '{"threshold":1,"keys": [{"key": "EOS7fcmyJExx1N72z49QDJqLBfATNzgAJ6aTcgpZAwPbyTnemmYkt","weight": 1}] ,"accounts":[]}'  -p teswangyilin@owner
```

**Comment by wangyilin1987** [comment]
@andriantolie thank you!
