### ISSUE TITLE
Failure to create account

### ISSUE THREAD

**Issue by grabastart** [EOSIO/eos#4687]
OS:
Ubuntu 18.04 vm over virtualbox.
Docker:
Version 17.x

nodeos running 
(confirmed by curl --url http://127.0.0.1:8888/v1/chain/get_info )

keosd running
(confirmed by "ps")

private key for eosio has been imported into wallet
two newly created private keys have also been imported wallet 
wallet is unlocked
(see screen shot below)

PROBLEM:
cleos create account eosio mynewaccount {mypublicOwnerKey} {mypublicActiveKey}
resulted in error
(see screen shot for err msg)
cleos get block # also resulted in same error and possibly other cleos command(s) would result in error as well.

hope eosio core devs can dig into it to see if it's eosio issue or ubuntu 18.4 issue or compatibility issue with docker or... most importantly how to solve it.

![importedkeysetc-from 2018-07-16 22-24-43](https://user-images.githubusercontent.com/2821724/42794995-cdacd010-894f-11e8-9559-42fa1dbb5d68.png)

**Comment by taokayan** [comment]
did you add ```--http-validate-host=false``` to your nodeos? You can use ```ps waux | grep eos``` to check

**Comment by jgiszczak** [comment]
Add `--http-validate-host=false` to both the nodeos and keosd command lines.  Note that the 1.1 release revises `cleos` to match the default listen host and port for nodeos and keosd, which should also alleviate this problem.

**Comment by grabastart** [comment]
"which should also alleviate this problem.", 
but new account is still unable to be created (same error msg), a very basic function for any software.  why did you @jgiszczak close it when the bug / problem has not been resolved?
