### ISSUE TITLE
Hello World smart contract isn't working.

### ISSUE THREAD

**Issue by newbieh4cker** [EOSIO/eos#4689]
my environment is -> eosio latest version(v.1.1.0 I think) on Ubuntu 16.04.

Currently, I'm following eosio smart contract tutorials
https://developers.eos.io/eosio-cpp/docs/hello-world

But thing is, after everything done(compile to wast/abi and set contract to account), here is result of cleos push action.

root@eos-full:\~/study# cleos push action hello.code hi '["user"]' -p user
executed transaction: 86e8190b16f77eaa3df27df22e2c7cae52c1a6ba4c730984835772cfb47c4cf2  104 bytes  435 us
\#     hello.code <= hello.code::hi               {"user":"user"}
warning: transaction executed locally, but may not be confirmed by the network yet
root@eos-full:~/study#

Q1. What Can I do for "warning: transaction~~~" message?

Q2. Why I'm not getting smart contract return message(in this case, 'Hello, user')

**Comment by andriantolie** [comment]
Looking at the response of your cleos command, I see nothing wrong. Your action is executed successfully. 

Q1. What Can I do for "warning: transaction~~~" message?
> Nothing, it's just a warning that tells you it might not be confirmed by the network yet until somebody includes that transaction in the block (which most likely will be success if you are running an isolated local node)

Q2. Why I'm not getting smart contract return message(in this case, 'Hello, user')
> Very likely you didn't start your nodeos with `--contracts-console` argument. The console is suppressed by default.

**Comment by PhillipHamnett** [comment]
I'm still new to this myself, so someone can feel free to correct me if I'm wrong:

A1. You are running a single node, transactions can't be confirmed unless you have 15 BPs confirm it.
A2. You have to run nodeos with --contracts-console to get debug output

**Comment by newbieh4cker** [comment]
@andriantolie 
since which eosio verison did I have to pass "--contracts-console" as an argument?

**Comment by andriantolie** [comment]
Hmm, it's been quite some time. Can't remember exactly the time, but I have been using it since last May
