### ISSUE TITLE
eosd -> Segmentation fault: 11  on Mac OS Sierra 10.12.6

### ISSUE THREAD

**Issue by eluzgin** [EOSIO/eos#469]
Successfully built EOS project. 
Then ran built eosd binary - got Segmentation fault: 11 error 
No config created.

**Comment by eluzgin** [comment]
Switched to Ubuntu 16, built without any errors and ran single node.

**Comment by staticinstance** [comment]
I'm getting the same issue on Mac OS Sierra 10.12.6, I'll look into switching to Ubuntu 16.  However, it would be interesting to know the solution to this.

**Comment by staticinstance** [comment]
Up and running with Ubuntu

**Comment by pavybez** [comment]
How are you running eosd? I tried and am unable to reproduce issue.

**Comment by staticinstance** [comment]
./eosd

**Comment by pavybez** [comment]
Can you delete the data-dir folder and try again?

**Comment by staticinstance** [comment]
I managed to get it to run on Mac OS Sierra 10.12.6  
I updated xcode and updated the config.ini and pointed genesis-json to the genesis.json file in the build directory

**Comment by pavybez** [comment]
Great. I will close the issue then and reopen if you encounter it again.
