### ISSUE TITLE
eosiocpp not working with Hello World tutorial on Ubuntu 18.04

### ISSUE THREAD

**Issue by PhillipHamnett** [EOSIO/eos#4690]
After successfully installing eos on Ubuntu 18.04 (using the `eosio_build.sh` script, and then running `sudo make install` in the build directory), the tutorial would not compile.

Steps to reproduce:

1. `eosiocpp -n hello`
2. `cd hello`
3. `eosiocpp -o hello.wast hello.cpp`

Output:

1. Creates the hello world skeleton (ok)
2. Go into folder (ok)
3. Complains that it can not find <eosiolib/eosio.hpp>

I tried making a symbolic link to the eosiolib folder in my `hello` directory, the got rid of the error and replaced it with a new error (inttypes.h could not be found).

I then tried installing Ubuntu 16.04, following the exact steps outlined above. This worked fine.

**Comment by newbieh4cker** [comment]
eosiocpp -o hello.wast hello.cpp
eosiocpp -g hello.abi hello.cpp

not 'wasm'

**Comment by PhillipHamnett** [comment]
Oops, typo in my PR.
Edited it now

**Comment by Pdsmithjp** [comment]
Did this get resolved? The install instructions says 18.04 is compatible. I am having similar issues.

**Comment by lazaridiscom** [comment]
similar: #5015

**Comment by dev1644** [comment]
I also have this issue , tried re-installing and other things too , but it didn't work.

**Comment by halsaphi** [comment]
Please refer to eosio.cdt
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
