### ISSUE TITLE
how do I view the new permission list

### ISSUE THREAD

**Issue by wangyilin1987** [EOSIO/eos#4691]
i try this:
 `cleos set account permission eoswangyilin view '{"threshold":1,"keys":  [{"key": "EOS5SL61GpNqMUJmhrPE3ueq7XG41MujPieMEhaDDCT5F2L4fhyny","weight": 1}] ,"accounts":[]}' `

and how to see the  permissions 'view' contains?  i can't found how to see list.

**Comment by andriantolie** [comment]
If the above command run successfully, you will see your new permission inside `cleos get account eoswangyilin`

**Comment by wangyilin1987** [comment]
@andriantolie sorry,i lose put this:`cleos set action permission eoswangyilin eosio.token transfer view`
i want see view had how many action's permission?

and `cleos get account eoswangyilin`  only know eoswangyilin has a view permission,but don't know what action can call.

**Comment by andriantolie** [comment]
Ah, if that's what you mean, I believe there's no API to retrieve the list of linked actions. I think it will be a useful feature though.

Not exactly the proper way to get it though, but in the current code, I'm aware that if you are trying to delete the permission, it will complain and say which action is currently linked

**Comment by n13** [comment]
> Ah, if that's what you mean, I believe there's no API to retrieve the list of linked actions. I think it will be a useful feature though.
> 
> Not exactly the proper way to get it though, but in the current code, I'm aware that if you are trying to delete the permission, it will complain and say which action is currently linked

Great trick with deleting permission - I needed to verify that the linkauth is set correctly
