### ISSUE TITLE
response_content_length >= 0: Invalid content-length response

### ISSUE THREAD

**Issue by tvrc4m** [EOSIO/eos#4692]
eosio build version
Build version: 3c6134c6
when i run the command as follow
cleos --print-request --print-response wallet list
output error
<img width="994" alt="screen shot 2018-07-17 at 3 24 46 pm" src="https://user-images.githubusercontent.com/2194937/42802512-ca33cce6-89d5-11e8-943d-4e975f997128.png">

Wallets:
REQUEST:
---------------------
POST /v1/wallet/list_wallets HTTP/1.0
Host: localhost:8900
content-length: 0
Accept: */*
Connection: close

---------------------
1258132ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)
response_content_length >= 0: Invalid content-length response
![Uploading Screen Shot 2018-07-17 at 3.24.46 PM.png…]()

**Comment by andriantolie** [comment]
Try to kill your keosd and starts again

**Comment by andriantolie** [comment]
If thing is still not working, you might want to start your keosd with `--http-validate-host=false` arg
