### ISSUE TITLE
How to write unit tests for smart contracts

### ISSUE THREAD

**Issue by sajjadpoores** [EOSIO/eos#4696]
Hi
I'm trying to figure it out how to write unit tests for my smart contracts. There are no official or non-official documents about it. I even havn't figured it out how to compile cpp files inside eos/unittests directory. even if I manage to run those files their code doesn't seem understandable.

I need you to help me having at least a general understanding of what I should do in order to write unit tests for my smart contracts.
thanks.

**Comment by andriantolie** [comment]
When you run ./eosio_build.sh, all cpp files inside eos/unittests are compiled as build/unitests/unit_test which is an executable of boost test. This means that you can pass boost test run time parameter to build/unitests/unit_test

You might want to check eosio.system_tests.cpp/ eosio.token_tests.cpp/ tic_tac_toe_tests.cpp / other unit test file inside eos/unittests as reference for this.

In general, for the unit test, you will want to create your own test chain (you can simply use tester object as convenience), compile your contract into wast, upload it to your test chain, and then interact with it

**Comment by halsaphi** [comment]
Closed as refers to old version of code.
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
