### ISSUE TITLE
CMAKE building EOSIO has exited with the above error

### ISSUE THREAD

**Issue by wypsanity** [EOSIO/eos#4697]
CMake Error at CMakeLists.txt:207 (add_subdirectory):
 add_subdirectory given source "unittests" which is not an existing
  directory.

CMake Error at CMakeLists.txt:208 (add_subdirectory):
  add_subdirectory given source "tests" which is not an existing directory.

-- Configuring incomplete, errors occurred!
See also "/home/eos/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/eos/eos/build/CMakeFiles/CMakeError.log".

        >>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above erro
r.

CMakeOutput.log:

Determining if the include file pthread.h exists passed with the following outpu
t:
Change Dir: /home/eos/eos/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_f8116/fast"
/usr/bin/make -f CMakeFiles/cmTC_f8116.dir/build.make CMakeFiles/cmTC_f8116.dir/
build
make[1]: Entering directory '/home/eos/eos/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_f8116.dir/CheckIncludeFile.c.o
/usr/bin/clang-4.0     -o CMakeFiles/cmTC_f8116.dir/CheckIncludeFile.c.o   -c /h
ome/eos/eos/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
Linking C executable cmTC_f8116
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f8116.dir/link.txt --verbose
=1
/usr/bin/clang-4.0       CMakeFiles/cmTC_f8116.dir/CheckIncludeFile.c.o  -o cmTC
_f8116 -rdynamic
make[1]: Leaving directory '/home/eos/eos/build/CMakeFiles/CMakeTmp'

CMakeError.log

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/eos/eos/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_991a1/fast"
/usr/bin/make -f CMakeFiles/cmTC_991a1.dir/build.make CMakeFiles/cmTC_991a1.dir/
build
make[1]: Entering directory '/home/eos/eos/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_991a1.dir/CheckSymbolExists.c.o
/usr/bin/clang-4.0     -o CMakeFiles/cmTC_991a1.dir/CheckSymbolExists.c.o   -c /
home/eos/eos/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_991a1
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_991a1.dir/link.txt --verbose
=1
/usr/bin/clang-4.0       CMakeFiles/cmTC_991a1.dir/CheckSymbolExists.c.o  -o cmT
C_991a1 -rdynamic
CMakeFiles/cmTC_991a1.dir/CheckSymbolExists.c.o: In function `main':
/home/eos/eos/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:(.text+0x19): undefi
ned reference to `pthread_create'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/cmTC_991a1.dir/build.make:97: recipe for target 'cmTC_991a1' failed
make[1]: *** [cmTC_991a1] Error 1
make[1]: Leaving directory '/home/eos/eos/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_991a1/fast' failed
make: *** [cmTC_991a1/fast] Error 2

File /home/eos/eos/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Error compiling eos in ubuntu, please help me.
I used the following command:
git clone https://github.com/EOSIO/eos --recursive.
./eosio_build.sh

**Comment by wypsanity** [comment]
I used the following command:
git clone https://github.com/EOSIO/eos --recursive.
./eosio_build.sh

**Comment by jgiszczak** [comment]
Your `git clone` or `git submodule update --init --recursive` failed part way through.  Remove the `eos` directory and try again.  Be sure both git operations complete successfully before attempting to build.
