### ISSUE TITLE
any plan about bancor contract

### ISSUE THREAD

**Issue by wilkey10** [EOSIO/eos#4698]
![image](https://user-images.githubusercontent.com/41328855/42813930-2785556c-89f5-11e8-94ef-1bf3681e926f.png)
Is there any plan about bancor contract? Of course not ram.

**Comment by halsaphi** [comment]
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
