### ISSUE TITLE
contract using regex

### ISSUE THREAD

**Issue by williamleecn** [EOSIO/eos#4699]
include \<regex\> to use regex, deploy contract occur error

```
3541826ms thread-0   http_plugin.cpp:405           handle_exception     ] FC Exception encountered while processing chain.push_transaction
3541827ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 10 assert_exception: Assert Exception
!"unresolvable": env.calloc
    {"module":"env","export":"calloc"}
    thread-0  wasm_interface.hpp:41 resolve

    {"mod_name":"env","export_name":"calloc"}
    thread-0  wasm_interface.hpp:43 resolve

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:62 exec_one

```

**Comment by jgiszczak** [comment]
The regex header is not usable in contracts.  Another regex library which does not use `calloc` may be usable.

**Comment by trmaphi** [comment]
@jgiszczak What's regex library do you recommend in smart contracts?

**Comment by heifner** [comment]
Would not recommend any regex library in a smart contract. Format your actions so regex is not required in contracts. Provide data to contracts that does not require that complex of processing.
