### ISSUE TITLE
Name bid does not work in mainnet

### ISSUE THREAD

**Issue by wsdfz** [EOSIO/eos#4700]
>cleos system bidnameinfo io
bidname:                                io
highest bidder:               starteosiobp
highest bid:                     900880000
last bid time:     2018-07-12T09:58:57.000

The highest bid "io" does not bid successfully after 5 days passed.

**Comment by taokayan** [comment]
This is because everyday only one name with the globally highest bid will be closed. I guess other names have higher bids than io.

**Comment by andresberrios** [comment]
@taokayan not necessarily, please check the pull request I've just submitted: https://github.com/EOSIO/eos/pull/4849
