### ISSUE TITLE
sudo make install error

### ISSUE THREAD

**Issue by ddzyan** [EOSIO/eos#4708]
eosio version:v.1.0.10
os:centos 7

`[admin@iz8vb5skar3xe57rl6fmn2z build]$ sudo make install
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
-- Configuring EOSIO on Linux
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using 'SYS' as CORE symbol name
-- Using 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV' as public key for 'eosio' account
-- Using WASM clang => /home/admin/opt/wasm/bin/clang
-- Using WASM llc => /home/admin/opt/wasm/bin/llc
-- Using WASM llvm-link => /home/admin/opt/wasm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Configuring fc to build on Unix/Apple
-- zlib found
-- Configuring Builtins
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   unit_test_framework
--   locale
-- Configuring ChainBase on Linux
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   program_options
--   unit_test_framework
--   locale
-- Configuring AppBase on Linux
CMake Error at contracts/CMakeLists.txt:22 (add_subdirectory):
  add_subdirectory given source "hello" which is not an existing directory.

-- Git commit revision: 3c6134c6
-- Git commit revision: 3c6134c6
-- Git commit revision: 3c6134c6
-- Configuring incomplete, errors occurred!
See also "/data/home/admin/eos-private/eos/build/CMakeFiles/CMakeOutput.log".
See also "/data/home/admin/eos-private/eos/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1`

what should I do?

**Comment by jgiszczak** [comment]
`sudo make install` should not have triggered a CMake rebuild.  Run `eosio_build.sh` from the EOS.IO root directory first and let the build complete before attempting to install.
