### ISSUE TITLE
Docker image for developers

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eos#4713]
it's great that it's separate, to keep the running version light, and the README indicates how to build it, but says nothing of how to use it.  I've looked at the Dockerfile and it doesn't create a container.

how do I use this image to run `eosiocpp`?  I want to deploy the `eosio.token` that comes with EOS but the directory contains no `.wast` or `.abi` so I need to figure out how to build them

**Comment by ericiles** [comment]
You can run the docker container interactively with a mounted volume `docker run -it -v <path/on/your/machine>:/compiled-contracts eosio/eos-dev:latest`. While at the bash prompt within the container, you can follow the [documentation](https://developers.eos.io/eosio-cpp/docs/hello-world) for working with smart contracts. 

Once you have your contracts compiled, you can then copy the wast/abi files to /compiled-contracts and it will now be on your local machine in the directory you specified in the docker command above.

I will work on updating the README to better explain this process.

**Comment by ekkis** [comment]
thanks for the quick reply.  I will give that a try.  I hope we can develop a workflow for developers who prefer Docker that facilitates working locally

**Comment by ekkis** [comment]
@ericiles, I've worked out a whole workflow for using Docker.  documented here: https://medium.com/@ekkis/eos-development-on-docker-3f4eb9b680ec -- please feel free to comment or take whatever may be of value from it
