### ISSUE TITLE
what can eosio.msig do?

### ISSUE THREAD

**Issue by wangyilin1987** [EOSIO/eos#4720]
from eosio.msig/readme.md's example, I don't see anything that helps me understand eosio.msig functions,  because it just same as 
`cleos push action eosio.token issue '[ "tester", "1000.0000 EOS", "memo" ]' -p treasury`.
I want to do like this with eosio.msig,and how?:
`cleos set account permission ticwangyilin multransfer '{"threshold":2,"keys":  [{"key": "EOS5heeQWpUjVRJCETabxJzgCimBDwruRU83Bzq5nSnsHrTBFSSuq","weight": 1}] ,"accounts":[{"permission":{"actor":"wangyuanyuan","permission":"mulyuan"},"weight":1}]}' active -p ticwangyilin`
`cleos set action permission ticwangyilin eosio.token transfer multransfer `
and keys to accounts 'wangyuanyuan@mulyuan' and 'EOS.........' imported into local wallet, the wallet is unlocked, and that wangyuanyuan@mulyuan can do transfer

**Comment by wangyilin1987** [comment]
or eosio.msig  has no connection to account's permission(about threshold),it just can check contract's require_auth() Async?

**Comment by evsward** [comment]
you can check this article: https://www.cnblogs.com/Evsward/p/msig.html

**Comment by wangyilin1987** [comment]
@evsward thank you!
另外，在这里用中文描述问题会得到回应吗:)

**Comment by evsward** [comment]
如果有人看到的话，会回应你的，不过一般来讲比较冷门的问题需要英文来问 @wangyilin1987
