### ISSUE TITLE
Application does not have a valid signature; Secure Enclave support disabled

### ISSUE THREAD

**Issue by tvrc4m** [EOSIO/eos#4722]
![image](https://user-images.githubusercontent.com/2194937/42873658-1c21a94c-8ab2-11e8-9d2f-0f8d045c51fd.png)
![image](https://user-images.githubusercontent.com/2194937/42873750-5946e382-8ab2-11e8-90f3-c556b95d6309.png)

who know?

**Comment by taokayan** [comment]
syntax changed for the new version, please add ```--private-key``` before your private key
