### ISSUE TITLE
cleos wallet is broken in a docker container (v1.0.10)

### ISSUE THREAD

**Issue by sztwiorok** [EOSIO/eos#4724]
I can use any ```cleos wallet``` subcommand in your latest docker image ```eos-dev:v1.0.10```

all the time I get Assert Exception (10), please see the example below
```
cleos wallet create
"/opt/eosio/bin/keosd" launched
3331351ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)
response_content_length >= 0: Invalid content-length response
```

**Comment by lcgogo** [comment]
Meet the same issue. I use followed docker image.
eosio/eos            v1.0.10              e2e8372d00e0        5 days ago          247MB

$ cleos version client
Build version: 3c6134c6

$ cleos get info
1798702ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)
response_content_length >= 0: Invalid content-length response

**Comment by AlexFanY** [comment]
Same here.

$ cleos get info
2577035ms thread-0 main.cpp:2756 main ] Failed with error: Assert Exception (10)
response_content_length >= 0: Invalid content-length response

I tried to get into the container,
`docker exec -it <keosd_containerId> bash `
install vim and add `http-validate-host = false` to ~/eos-wallet/config.ini

Then I exit and restart keosd, but keosd can no longer be started again.

**Comment by jgiszczak** [comment]
Adding `http-validate-host = false` in the keosd config.ini is the correct solution for v1.0.10.  `keosd` must then be killed and restarted to use the new setting.

Alternatively, waiting for the v1.1.0 Docker image, or building one, might be preferred.  v1.1 addresses that error by fixing the mismatch between the default listen host for nodeos and the default URL for cleos.

**Comment by sztwiorok** [comment]
when will v1.1.0 be released?

**Comment by jgiszczak** [comment]
v1.1 has been released.
