### ISSUE TITLE
Datatable Query

### ISSUE THREAD

**Issue by nishakant001** [EOSIO/eos#4727]
Hi,
I am writing a contract register user into Blockchain. 
for that i have created a table users which holds the details of it.
But i have a query.
1. Can we create **dynamic** table through code as an when new user is registered i.e When user1 is registered, I should be able to create user1 table, user2 table ..... usern as and when new users are added. ?
2. Or how can we maintain **table relationship** i.e suppose I would want to store more then 1 Address of user1 (Using foreign key relation ship).?
3. What is the **limit of tables** that can be created in the smart contract. or EOS database?
4. what is the **limit of records** that can be inserted into the table.? 

thanks in advance.

**Comment by andriantolie** [comment]
1. Yes
2. You can store the primary key of another record inside your record to work as the foreign key if you would like. But it's your responsibility to maintain the constraint.
3. As much as the payer's available RAM
4. As much as the payer's available RAM

**Comment by nishakant001** [comment]
Hi Thanks for your update.

1. But could you please send me some link or Sample code showing how table can be created dynamically?

**Comment by andriantolie** [comment]
Check eosio.token.cpp token::create function, every time a new currency is created, we create a new table under the scope of the currency symbol. Whenever a new data is inserted into an empty table definition, a new table will be created.
