### ISSUE TITLE
in v1.1.0:get transaction error: please contact the RPC server administrator for

### ISSUE THREAD

**Issue by stev1988** [EOSIO/eos#4728]
cleos -u http://127.0.0.1:5001 get transaction 1583af626874441a15df59fa1f0284e72bf6aaa8f1ba75455e0eec9207e700e8
Error 3200006: invalid http request
Error Details:
The server has rejected the request as invalid!
Please verify this url is valid: http://127.0.0.1:5001/v1/history/get_transaction
If the condition persists, please contact the RPC server administrator for 127.0.0.1!

but get info is success.

**Comment by jgiszczak** [comment]
`/v1/history/get_transaction` is part of the history_plugin, and requires initializing the `history_plugin` and `history_api_plugin`.  It is independent of the plugin that provides `get_info`.  If you wish to retrieve transactions already on the chain after initializing history_plugin, you'll need to `--replay-blockchain` to populate the plugin's database.

**Comment by stev1988** [comment]
my config.ini has added the history_api_plugin and history_plugin,like this:
plugin = eosio::http_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::producer_plugin
plugin = eosio::history_plugin
plugin = eosio::history_api_plugin
plugin = eosio::mongo_db_plugin 

and the same error when i added --replay-blockchain ,why the command is sucessful in v1.0.10 but failed in v1.1.0?

**Comment by egonson** [comment]
same to me. what's the matter?

**Comment by cppfuns** [comment]
@jgiszczak 
The problem should not be here, I have appeared here too.

**Comment by cppfuns** [comment]
Read this article, maybe solve your problem.
https://www.bcskill.com/index.php/archives/356.html
