### ISSUE TITLE
Cannot find commands like cleos and eosiocpp in latest release v1.1.0

### ISSUE THREAD

**Issue by yashbhavsar007** [EOSIO/eos#4729]
i have added the path to my bashrc file...after that cleos and eosiocpp is running but eosiocpp cannot include hpp files from eosiolib it shows error "fatal error: 'eosiolib/asset.hpp' file not found".

**Comment by mmcs85** [comment]
After compiling the new version did you do: make install
?

**Comment by timtide** [comment]
have made install. It's useless

**Comment by yashbhavsar007** [comment]
@niufj  it's ok for cleos but what about eosiocpp i have also given path of it but it cannot able to include hpp  files like " eosiolib/asset.hpp " and my contract is in the folder eos/contract and that hpp file is also present in eosiolib folder still not able to include the hpp files.

**Comment by yashbhavsar007** [comment]
@timtide  agree after making install i am facing this issues

**Comment by johnworthley** [comment]
For cleos just run $ /usr/local/eosio/bin/cleos and it should work. I ran it now on v1.1.0

**Comment by shaqk** [comment]
Binaries are no longer under "/usr/local/eosio/bin/", presumably to avoid name conflicts.
To add the eosio bin folder to your PATH (This is TEMPORARY and only valid for the current terminal session)

`export PATH=$PATH:/usr/local/eosio/bin/`

To make the PATH change PERMANENT you can add it to your ~/.profile 

`echo 'PATH=$PATH:/usr/local/eosio/bin/' >> ~/.profile`

**Comment by andriantolie** [comment]
@shaqk is right here, binaries are installed in /usr/local/eosio/bin instead of /usr/local/bin now, and the include path is /usr/local/eosio/include. If you are still using the eos binaries inside /usr/local/bin, please use the one inside /usr/local/eosio/bin instead

**Comment by yashbhavsar007** [comment]
@shaqk Thank you for helping.....It works for me.

**Comment by bluabaleno** [comment]
I have added the path to my .profile and it is still not working.

export PATH=$PATH:/usr/local/eosio/bin/

works fine for the session, but once I exit it the commands no longer work. I have checked my .profile and the path is there.

**Comment by lazaridiscom** [comment]
@bluabaleno , from the https://github.com/EOSIO/eos/issues/4729#issuecomment-406448595 above:

> To make the PATH change PERMANENT you can add it to your ~/.profile

```bash
echo 'PATH=$PATH:/usr/local/eosio/bin/' >> ~/.profile
```

and possibly you need to reload the profile via ` . ~/.profile`

**Comment by r12543** [comment]
But still unable to include files like asset.hpp and eosio.hpp. How to set the new include path?

**Comment by hsejin314** [comment]
what if that I haven't 'make install'?

**Comment by jgiszczak** [comment]
@hsejin314 Then simply specify some part of the path to the program you are trying to run.  If your working directory is `eos/build`, you may type `programs/cleos/cleos` and it will run.
