### ISSUE TITLE
Use `set -e` instead of manual error handling in build scripts

### ISSUE THREAD

**Issue by pbrkr** [EOSIO/eos#4736]
The build scripts currently rely on manual error handling which is itself prone to errors. Instead, `set -e` should be used to ensure that bash exits immediately on any error in the build process. This will make the build scripts much easier to follow as they no longer need to have an if statement for every command that is executed and there is no risk of missing any errors.

**Comment by spoonincode** [comment]
As of 1.8 the scripts do indeed start with a `set -eo pipefail`, closing this
