### ISSUE TITLE
Wallet list is empty even though wallet is create successfully [version 1.1.0]

### ISSUE THREAD

**Issue by jin-beyond** [EOSIO/eos#4738]
I added this alias and create the "default" wallet successfully 
`alias cleos='docker exec -it eosio /opt/eosio/bin/cleos -u http://0.0.0.0:8888'`
but `cleos wallet list` showed empty list. 
Then I tried creating the "default" again, it replied that the wallet had been created.

Then I modified the alias by replacing `-u http://0.0.0.0:8888` with `---wallet-url http://localhost:8888`, Surprisingly, I can create the "default" wallet again, and the `cleos wallet list` showed `default` wallet.

Any idea?

**Comment by andriantolie** [comment]
If you don't specify `--wallet-url`, the default wallet url will be http://localhost:8900. 
If `cleos wallet list` is empty but you have indeed created the wallet, you can just open the wallet using `cleos wallet open`, you will see your wallet later on

**Comment by spoonincode** [comment]
Closing this. Has to do with docker and an ancient version... no reason keeping it open.
