### ISSUE TITLE
having error creating accounts in eosio using cli--cleos in ubuntu 18.04

### ISSUE THREAD

**Issue by rosselpha** [EOSIO/eos#4744]
`cleos create account eosio myaccount 

`EOS6BX6eQH2JwKoMwh57wi1p76sr3CkqHNDBzjGCYWnMn4M3GH7fq EOS6BX6eQH2JwKoMwh57wi1p76sr3CkqHNDBzjGCYWnMn4M3GH7fq`

`418832ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)`
`response_content_length >= 0: Invalid content-length response`
`

that is the command I run i don't understand what it means I'm new to eos and ubuntu

**Comment by jin-beyond** [comment]
which version are u using?

**Comment by taokayan** [comment]
Please start nodeos with ```--http-validate-host=false```
