### ISSUE TITLE
nodeos crashes - Exception Details: 3010008 block_id_type_exception: Invalid block ID

### ISSUE THREAD

**Issue by warrick-eosny** [EOSIO/eos#4745]
I am able to spin up a fresh instance of a server and consistently crash it when calling a simple hello world contract. 

I've put debug files here: 
https://vsolution.box.com/s/5gzvmcj237j64xaet1tn6ic7yh82apa5

1. Server output
2. There is a windows fiddler trace showing the exact http requests. 

If you don't have a windows box to view the fiddler trace. Here's some screenshots showing the raw HTTP requests. 

![snap001](https://user-images.githubusercontent.com/40346010/42920223-9ae9a58c-8ae3-11e8-975f-e45435dcefe3.png)
![snap002](https://user-images.githubusercontent.com/40346010/42920235-a29c76ec-8ae3-11e8-8b93-7d413a1e1ef2.png)
![snap003](https://user-images.githubusercontent.com/40346010/42920268-be65dd32-8ae3-11e8-814b-98858fad0aeb.png)

This can be reproduced by going to this URL: http://pennstation.eosdocs.io/ and clicking the 1st button on the page repeatedly. 

http://pennstation.eosdocs.io:7001/v1/chain/get_info
```
{"server_version":"75635168","chain_id":"cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f","head_block_num":73,"last_irreversible_block_num":59,"last_irreversible_block_id":"0000003bd342916b0ec1f06bf766195c3585460e9647fff9a2afbdffb85a0c1b","head_block_id":"00000049591e08a5b9b377ad692a2570938e592aa1a0cbda667b3aaa8a55c81e","head_block_time":"2018-07-19T03:43:00.500","head_block_producer":"bp1","virtual_block_cpu_limit":214903,"virtual_block_net_limit":1126859,"block_cpu_limit":199900,"block_net_limit":1048576}
```

This is a small debug environment running as a Docker image in case that makes a difference.

**Comment by gittempo** [comment]
@warrick-eosny please give me step by step tutorial to install and download blockchain

**Comment by warrick-eosny** [comment]
unable to reproduce this again.
