### ISSUE TITLE
what's the rule to generate a action id

### ISSUE THREAD

**Issue by sunrye** [EOSIO/eos#4746]
I query a transaction with block id 5580084 and tx id d3decdb21d20e627cab1087a6c579fbb112a063f17099f431e39e288f4e2a7ae through RPC, I find there is one action
`actions": [
                        {
                            "account": "eosio",
                            "name": "sellram",
                            "authorization": [
                                {
                                    "actor": "g44tqnrwgege",
                                    "permission": "active"
                                }
                            ],
                            "data": {
                                "account": "g44tqnrwgege",
                                "bytes": 320000
                            },
                            "hex_data": "a09862fc4e9b096100e2040000000000"
                        }
                    ],`
It's a sellram type action, but I am surprised that there is no specific eos amount shown here.
When I query this tx in https://eosmonitor.io/txns/d3decdb21d20e627cab1087a6c579fbb112a063f17099f431e39e288f4e2a7ae/actions/5b47f0ffc6f90767ce42c90c I find this transaction has 2 related actions，as follows

5b47f0ffc6f90767ce42c90e | eosio.ram | active | transfer | 111.1977 EOS (eosio.token)
5b47f0ffc6f90767ce42c90f | g44tqnrwgege | active | transfer | 0.5560 EOS (eosio.token)

My questions are:1. what's action id rule.2. how can I get the related action as the eosmonitor.io do.

**Comment by taokayan** [comment]
there's no action id concept, as actions can't be separated outside of any transactions. You need to query the transaction by transaction id.
