### ISSUE TITLE
Unable to connect to HTTP/RPC API

### ISSUE THREAD

**Issue by bharry29** [EOSIO/eos#4747]
Hello Team,

I am trying to connect to HTTP/RPC API and do basic queries like get accounts, get balance in my UI and I am always getting a 404 error.

Here is the error:

{"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"Unknown Endpoint","file":"http_plugin.cpp","line_number":203,"method":"handle_http_request"}]}}

I have configured nodeos to work on port 8888 and cleos on 8889 and I have followed multiple resources to get it right but I cannot do so.

Any help would be appreciated.

I have attached the config files of nodeos and cleos.

[Config files.zip](https://github.com/EOSIO/eos/files/2208269/Config.files.zip)

**Comment by yashbhavsar007** [comment]
@bharry29  attach plugins in config file for http which is "plugin = eosio::http_plugin" and try it.

**Comment by bharry29** [comment]
@yashbhavsar007 I have tried that but I cannot do that. I have enabled the plugin through nodeos too. 
The command is "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console"

**Comment by taokayan** [comment]
please add --http-validate-host=false to your nodeos then retry

**Comment by bharry29** [comment]
@taokayan I have tried it but nothing works.

**Comment by jgiszczak** [comment]
You said you configured cleos on port 8889.  Presumably you meant keosd, since cleos does not have a listen port.

A curl command that matches the command line you gave for nodeos is:
`curl http://127.0.0.1:8888/v1/chain/get_info`.

**Comment by bharry29** [comment]
Only curl http://127.0.0.1:8888/v1/chain/get_info works showing me results and rest of them fail giving me a 404 error. Any directions to look into now?

**Comment by yashbhavsar007** [comment]
Run nodeos and keosd on same port and then try.

**Comment by bharry29** [comment]
@yashbhavsar007 I am getting this error for keosd: 
2018-07-20T07:14:11.739 thread-0   http_plugin.cpp:408           plugin_startup       ] http service failed to start: Address already in use
2018-07-20T07:14:11.739 thread-0   main.cpp:54                   main                 ] Address already in use

**Comment by yashbhavsar007** [comment]
I have attached my config file please check it it is for version 1.1.0 
[config.ini.zip](https://github.com/EOSIO/eos/files/2212902/config.ini.zip)

**Comment by jgiszczak** [comment]
Running multiple services on the same IP and port does not work without kernel-level chicanery no one does if they can avoid it.  Revert to the ports you had before.

If `/vi/chain/get_info` is working, the rest of the `chain` API will also be available.  The only other endpoints which do not require parameters are `/v1/chain/get_producers` and `/v1/chain/get_producer_schedule`.  All others require additional `curl` parameters.  Unfortunately the [documentation](https://developers.eos.io/eosio-nodeos/reference) is currently bad.  This is being fixed. 
 Until the documentation is fixed, the best way to discover what arguments are required is to use `cleos --print-request` for the equivalent `cleos` command.

Here's a complete sample matching your nodeos configuration for retrieving a block using curl:
`curl --request POST http://127.0.0.1:8888/v1/chain/get_info --data '{"block_num_or_id": "16"}'`

**Comment by dominic-healid** [comment]
Please help..

I can access /chain/get_info and other routes but not the routes for wallet like /wallet/get_public_keys 

I can access chain api using the port 8888, for wallet I have tried 8900 or 8888 but no luck.

Any thoughts?

**Comment by dominic-healid** [comment]
@taokayan no sir, just on testnet. Did I miss any commands that I need to run to be able to make the wallet api routes accessible?

**Comment by dominic-healid** [comment]
In terminal I'm using cleos and when I'm trying to call the  /wallet/get_public_keys I'm using RESTClient of firefox.

**Comment by yashbhavsar007** [comment]
@dominic-healid  This happens because they have removed wallet rpc from nodeos in latest updates but you can still interact with your wallet from your keosd port and to making this /wallet/get_public_keys call you need to unlock your default wallet first.

**Comment by dominic-healid** [comment]
@yashbhavsar007 thanks for the response. is the 8900 default port for keosd? Sorry, I'm very new with EOS and haven't explored deeper of it. I actually tried 8900 and I'm getting 404 not found but I haven't tried unlocking the wallet first, about to do it now.

**Comment by yashbhavsar007** [comment]
@dominic-healid  may be by default port is 8888.

**Comment by ghassett** [comment]
I am having a similar problem.  Calls to the `chain` API succeed, calls to the `wallet` API fail.  I am running `keosd` on a unix socket.  Example of `CURL` to `chain` API that succeeds:

Example of `CURL` to `wallet` API that 404's:

```
$ curl --request POST  --unix-socket ~/eosio-wallet/keosd.sock  http:/v1/wallet/list_wallets   --header 'content-type: application/x-www-form-urlencoded; charset=UTF-8'

{"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[]}}

**Comment by sneha6patel** [comment]
Hello I am also new to EOS and want to o connect to HTTP/RPC API but when i'm using wallet rpc api to create wallet using python. It's getting 404 errors.

Here is my python code..............................

import requests
headers = {
'Cache-Control': 'no-cache',
'Content-Type' : 'application/json',
'charset' : 'UTF-8'
}
data = '"Wallet-1"'

response = requests.post("http://localhost:8900/v1/wallet/create", data=data)

print(response.json())

And the errors are.....................................................................

{'message': 'Not Found', 'error': {'details': [{'message': 'Unknown Endpoint', 'line_number': 298, 'method': 'handle_http_request', 'file': 'http_plugin.cpp'}], 'what': 'unspecified', 'name': 'exception', 'code': 0}, 'code': 404}

**Comment by yashbhavsar007** [comment]
Is your keosd running on 8900 ? @sneha6patel

**Comment by sneha6patel** [comment]
yes, actually My nodes running on 8888 so then i tried 8900 for keosd but it gets error..I've also tried to run on 8888 but still it gets errors

**Comment by yashbhavsar007** [comment]
have you checked using cleos ?
@sneha6patel

**Comment by sneha6patel** [comment]
yes, it's running

**Comment by yashbhavsar007** [comment]
@sneha6patel have you tried using curl like this **curl -X POST   http://127.0.0.1:8900/v1/wallet/create   -H 'Cache-Control: no-cache'   -H 'Content-Type: application/json'  -d '"mywallet"'**

**Comment by sneha6patel** [comment]
No it's getting errors

{"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"Unknown Endpoint","file":"http_plugin.cpp","line_number":298,"method":"handle_http_request"}]}}

**Comment by yashbhavsar007** [comment]
Have you checked config.ini of eosio-wallet ? What is value for http-server-address ? @sneha6patel

**Comment by sneha6patel** [comment]
Yes It has 127.0.0.1:8900

**Comment by sneha6patel** [comment]
I've also again changed to 127.0.0.1:8888 for both keosd and nodes also in python code. Still it get errors..

**Comment by sneha6patel** [comment]
[config.ini.zip](https://github.com/EOSIO/eos/files/2859624/config.ini.zip)
this file is for Eosio-wallet.

**Comment by yashbhavsar007** [comment]
Have you seen this type of logs during startup of nodes/keosd ?
![screenshot 2019-02-13 at 2 57 57 pm](https://user-images.githubusercontent.com/26292780/52701309-f1876a80-2f9f-11e9-98f5-f502db4be52c.png)

**Comment by sneha6patel** [comment]
I've solved my problem..The thing is i changed the port in config file but it didn't take it therefore my friend just type manually on cmd and my code runs.

And also thnak you

**Comment by yashbhavsar007** [comment]
Great to hear that @sneha6patel 
Your need to restart nodeos with new changes and in keosd sometime it takes to restart system also as i had the problem in older versions.

**Comment by sneha6patel** [comment]
Okay

**Comment by sneha6patel** [comment]
How do i create EOS account through RPC api using python and html page as we are deploying web application on EOS

**Comment by yashbhavsar007** [comment]
@sneha6patel This may be out of this github issue you can reach me by mail or telegram will help you out!

**Comment by sneha6patel** [comment]
Ok then I'' msg you via gmail account.
