### ISSUE TITLE
Loading the Bios Contract ERROR

### ISSUE THREAD

**Issue by JonieH** [EOSIO/eos#4748]
virtual-machine:~/eos$ cleos set contract eos build/contracts/eosio.bios -p eosio@active
Reading WAST/WASM from build/contracts/eosio.bios/eosio.bios.wasm...
Using already assembled WASM...
Publishing contract...
2488106ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)
response_content_length >= 0: Invalid content-length response

**Comment by taokayan** [comment]
please add ``` --http-validate-host=false``` to your nodeos then retry

**Comment by manishatGit** [comment]
@taokayan Its a real issue. Got the same error. adding --http-validate-host=false doesn't work.
