### ISSUE TITLE
multi index data cannot find in get table rows

### ISSUE THREAD

**Issue by Hitmanv** [EOSIO/eos#4751]
but I can read it from contract
i'm using the local test net
i deployed the contract
```shell
cleos set contract hitman contract_path c.wast c.abi  -p hitman@active
```
and the query
```shell
cleos get table hitman hitman table_name
```
or in eosjs
```javascript
eos.getTableRows({ code: "hitman", scope: "hitman",  json: true, table: table_name })
```

the contract code looks like this
```cpp
#include <eosiolib/eosio.hpp>

using namespace eosio;

class hello : public eosio::contract {
  /// @abi table tests
  struct t {
    uint64_t id;
    auto primary_key() const { return id; }
    EOSLIB_SERIALIZE(t, (id))
  };
  typedef multi_index<N(t), t> tests;

  public:
      using contract::contract;
      /// @abi action 
      void hi( account_name user ) {
        tests t_table(_self, _self);
        t_table.emplace(_self, [&](auto &r){
          r.id = 1;
        });
      }

      /// @abi action
      void get() {
        tests t_table(_self, _self);
        auto itr = t_table.begin();
        // it's ok here
        print(itr->id);
      }
};

EOSIO_ABI( hello, (hi)(get) )

```

**Comment by taokayan** [comment]
Depending on your source code and actual usage, a table will only be created when it's being used.

**Comment by mmcs85** [comment]
Not totaly sure but shouldn't this line:
typedef multi_index<N(t), t> tests;

Change to:
typedef multi_index<**N(tests)**, t> tests;

**Comment by taokayan** [comment]
we recommend to be ```typedef multi_index<N(t), t> tests;```. In this case your table name is ```t```.

**Comment by Hitmanv** [comment]
that's it. thank you all!

**Comment by SheharyarCh** [comment]
it is returning value that we stored in hi method manually.
How to retrieve complete record by giving an id or name?

**Comment by SheharyarCh** [comment]
I have used this code to store the data(name and marks) in the table, now i want to retrieve that data in the form of record. how can i get that?

void addmarks(account_name examiner, account_name student, uint64_t marks)
    {
        auto toitr = _accounts.find(student);
        if(toitr == _accounts.end())
        {
            _accounts.emplace(examiner, [&](auto& st)
            {
                st.name = student;
                st.obtainedmarks = marks;
            });
        }
        else
        {
            _accounts.modify(toitr,0,[&](auto& st)
            {
                st.obtainedmarks += marks;
                eosio_assert(st.obtainedmarks >= marks, "Marks Assigned");
            });
        } 
    }

**Comment by SheharyarCh** [comment]
I have used this code to store the data(name and marks) in the table, now i want to retrieve that data in the form of record. how can i get that?
--------------------------------------------------------------------------------------------------------------
void addmarks(account_name examiner, account_name student, uint64_t marks)
    {
        auto toitr = _accounts.find(student);
        if(toitr == _accounts.end())
        {
            _accounts.emplace(examiner, [&](auto& st)
            {
                st.name = student;
                st.obtainedmarks = marks;
            });
        }
        else
        {
            _accounts.modify(toitr,0,[&](auto& st)
            {
                st.obtainedmarks += marks;
                eosio_assert(st.obtainedmarks >= marks, "Marks Assigned");
            });
        } 
    }  
--------------------------------------------------------------------------------------------------------------
kindly help me to solve it?

**Comment by Hitmanv** [comment]
@SheharyarCh did you mean the index or primary key?
you could use get/find(primary_key) or use the get_index method
[reference](https://developers.eos.io/eosio-cpp/reference#get_index)
