### ISSUE TITLE
import private keys error~!someone help me~!

### ISSUE THREAD

**Issue by zhengyi345** [EOSIO/eos#4753]
cleos wallet import 5JXmv5N4hTgDc6NVS6J8CNT1JxDKab7M6iEyFbPewTrGkUxhuuZ -n alec_wallet
ERROR: ExtrasError: [5JXmv5N4hTgDc6NVS6J8CNT1JxDKab7M6iEyFbPewTrGkUxhuuZ]
Import private key into wallet
Usage: cleos wallet import [OPTIONS]

Options:
  -n,--name TEXT              The name of the wallet to import key into
  --private-key TEXT          Private key in WIF format to import

**Comment by leos97** [comment]
cleos wallet import --private-key 5JXmv5N4hTgDc6NVS6J8CNT1JxDKab7M6iEyFbPewTrGkUxhuuZ -n alec_wallet

**Comment by zhengyi345** [comment]
@leos97 Thank you, but there is still a problem, tips：
cleos wallet import --private-key 5JXmv5N4hTgDc6NVS6J8CNT1JxDKab7M6iEyFbPewTrGkUxhuuZ -n alec_wallet
No wallet service listening on 127.0.0.1:8900. Cannot automatically start keosd because keosd was not found.
Failed to connect to keosd at http://127.0.0.1:8900/; is keosd running?

**Comment by jgiszczak** [comment]
It seems you are running a copy of `cleos` that is neither installed nor in the build hierarchy.  As such, you will need to run keosd manually.  To get it running in a way compatible with the documentation and cleos defaults, use:
`keosd --config-dir ~/eos-wallet --wallet-dir ~/eos-wallet --http-server-address 127.0.0.1:8900 --http-alias localhost:8900 > ~/eos-wallet/stdout.log 2> ~/eos-wallet/stderr.log &`

You may of course choose any directory or directories you like.  Just be aware that any documentation referring to wallet directories will require you to substitute your own to work.  You may choose any listen port you like, and specify it on the cleos command line with `--wallet-url`.

You will need to run `cleos wallet create -n alec_wallet` before executing the import.
