### ISSUE TITLE
Plugin and Nodeos test failed.

### ISSUE THREAD

**Issue by bluabaleno** [EOSIO/eos#4758]
30 - plugin_test (Failed)
         31 - nodeos_sanity_test (Failed)
         32 - nodeos_run_test (Failed)
         34 - nodeos_run_test-mongodb (Failed)
         35 - distributed-transactions-test (Failed)
         36 - restart-scenarios-test-resync (Failed)
         37 - restart-scenarios-test-hard_replay (Failed)
         38 - restart-scenarios-test-none (Failed)
         39 - validate_dirty_db_test (Failed)
         40 - nodeos_sanity_lr_test (Failed)
         41 - nodeos_voting_lr_test (Failed)

running Ubuntu as Windows Linux Subsystem with EOS.IO 1.10.0 build.

**Comment by jgiszczak** [comment]
Windows Linux Subsystem is not supported.  If you wish to discover why those tests are failing and submit pull requests that correct the problem on Windows, we will evaluate them for possible merging.

**Comment by lazaridiscom** [comment]
possibly related: #3842

**Comment by lazaridiscom** [comment]
> Windows Linux Subsystem is not supported.

As things stand, the problem with the test-failures is not related to WSL
