### ISSUE TITLE
multiple index

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#4759]
static_assert failed "name provided is not the name of any secondary index within multi_index"

**Comment by heifner** [comment]
Please provide more information.

**Comment by yankunsam** [comment]
➜  bind git:(75635168e) ✗ eosiocpp -o bind.wast bind.cpp
In file included from bind.cpp:1:
In file included from ./bind.hpp:1:
In file included from /usr/local/include/eosiolib/eosio.hpp:9:
/usr/local/include/eosiolib/multi_index.hpp:622:10: error: static_assert failed "name provided is not the name of any secondary index within multi_index"
         static_assert( res != hana::nothing, "name provided is not the name of any secondary index within multi_index" );
         ^              ~~~~~~~~~~~~~~~~~~~~
bind.cpp:6:31: note: in instantiation of function template specialization 'eosio::multi_index<3617210386705953280, actinfolist, eosio::indexed_by<12044502819693133824,
      boost::multi_index::const_mem_fun<actinfolist, unsigned long long, &actinfolist::get_owner> > >::get_index<4587419431193280512>' requested here
  auto actinfo = actinfolists.get_index<N(byowner)>();
                              ^
In file included from bind.cpp:1:
In file included from ./bind.hpp:1:
In file included from /usr/local/include/eosiolib/eosio.hpp:9:
In file included from /usr/local/include/eosiolib/multi_index.hpp:9:
In file included from /usr/local/include/boost/hana.hpp:59:
In file included from /usr/local/include/boost/hana/adapt_adt.hpp:15:
In file included from /usr/local/include/boost/hana/detail/struct_macros.hpp:28:
In file included from /usr/local/include/boost/hana/string.hpp:41:
/usr/local/include/boost/hana/optional.hpp:102:9: error: static_assert failed "hana::optional::value() requires a non-empty optional"
        static_assert(detail::wrong<dummy...>{},
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/eosiolib/multi_index.hpp:624:54: note: in instantiation of function template specialization 'boost::hana::optional<>::value<>' requested here
         return typename decltype(+hana::at_c<0>(res.value()))::type(this);
                                                     ^
bind.cpp:6:31: note: in instantiation of function template specialization 'eosio::multi_index<3617210386705953280, actinfolist, eosio::indexed_by<12044502819693133824,
      boost::multi_index::const_mem_fun<actinfolist, unsigned long long, &actinfolist::get_owner> > >::get_index<4587419431193280512>' requested here
  auto actinfo = actinfolists.get_index<N(byowner)>();
                              ^
In file included from bind.cpp:1:
In file included from ./bind.hpp:1:
In file included from /usr/local/include/eosiolib/eosio.hpp:9:
/usr/local/include/eosiolib/multi_index.hpp:624:36: error: no matching function for call to 'at_c'
         return typename decltype(+hana::at_c<0>(res.value()))::type(this);
                                   ^~~~~~~~~~~~~
bind.cpp:6:31: note: in instantiation of function template specialization 'eosio::multi_index<3617210386705953280, actinfolist, eosio::indexed_by<12044502819693133824,
      boost::multi_index::const_mem_fun<actinfolist, unsigned long long, &actinfolist::get_owner> > >::get_index<4587419431193280512>' requested here
  auto actinfo = actinfolists.get_index<N(byowner)>();
                              ^
/usr/local/include/boost/hana/at.hpp:52:30: note: candidate template ignored: substitution failure [with n = 0, Xs = void]: cannot form a reference to 'void'
    constexpr decltype(auto) at_c(Xs&& xs) {
                             ^      ~~
/usr/local/include/boost/hana/basic_tuple.hpp:211:30: note: candidate template ignored: could not match 'basic_tuple<type-parameter-0-1...>' against 'void'
    constexpr decltype(auto) at_c(basic_tuple<Xs...> const& xs) {
                             ^
/usr/local/include/boost/hana/basic_tuple.hpp:216:30: note: candidate template ignored: could not match 'basic_tuple<type-parameter-0-1...>' against 'void'
    constexpr decltype(auto) at_c(basic_tuple<Xs...>& xs) {
                             ^
/usr/local/include/boost/hana/basic_tuple.hpp:221:30: note: candidate template ignored: could not match 'basic_tuple<type-parameter-0-1...>' against 'void'
    constexpr decltype(auto) at_c(basic_tuple<Xs...>&& xs) {
                             ^
/usr/local/include/boost/hana/tuple.hpp:273:30: note: candidate template ignored: could not match 'tuple<type-parameter-0-1...>' against 'void'
    constexpr decltype(auto) at_c(tuple<Xs...> const& xs) {
                             ^
/usr/local/include/boost/hana/tuple.hpp:278:30: note: candidate template ignored: could not match 'tuple<type-parameter-0-1...>' against 'void'

**Comment by yankunsam** [comment]
Here is my demo code.
```
#include <eosiolib/eosio.hpp>
#include <eosiolib/asset.hpp>
#include <eosiolib/action.hpp>
#include <eosiolib/public_key.hpp>
#include <eosiolib/types.hpp>
#include <iterator>
#include <set>

using namespace eosio;
using namespace std;

// @abi table actinfolist i64
struct actinfolist {
  uint32_t id;
  uint64_t owner;
  // define as a set:
  //set <account_name> servant;
  vector<account_name> servant;
  bool audit;

  uint32_t primary_key() const { return id; }
  uint64_t get_owner() const { return owner; }

  EOSLIB_SERIALIZE(actinfolist,(id)(owner)(servant)(audit));
};

typedef eosio::multi_index<N(actinfolist),actinfolist,indexed_by<N(owner),const_mem_fun<actinfolist,uint64_t,&actinfolist::get_owner>>> actinfolist_index;

class bindactinfo: public contract {
public:
  bindactinfo(account_name self): contract(self),actinfolists(_self,_self) {}
  void actupdate(account_name servant,bool audit);
  void transupdate(string transaction_id);
  actinfolist_index actinfolists;


private:

};
EOSIO_ABI(bindactinfo, (actupdate)(transupdate))


```

**Comment by yankunsam** [comment]
Sorry for the wrong name.
