### ISSUE TITLE
fatal error: 'eosiolib/eosio.hpp' file not found

### ISSUE THREAD

**Issue by MessyComposer** [EOSIO/eos#4760]
I've been trying to get the development environment working for the past three days but keep getting this error when generating wast and abi for my code using eosiocpp
`fatal error: 'eosiolib/eosio.hpp' file not found #include <eosiolib/eosio.hpp>`

I've tried all the solutions I could find, including modifying eosiocpp, sudo make install, etc.
I have also tried using master branch, v1.0.5, v1.0.9 and v1.1.0

I'm completely stuck, what to do now?

**Comment by andriantolie** [comment]
Try v1.1.0, build it and install it (./eosio_build.sh && cd build && sudo make install). You will see that your eosiocpp will be installed inside `/usr/local/eosio/bin` and your eosiolib will be installed inside `/usr/local/eosio/include`. This way, if you are compiling using /usr/local/eosio/bin/eosiocpp, your eosiocpp should be able to detect files inside `/usr/local/eosio/include` as it is already added to your include path by eosiocpp. Make sure you revert all the change you have made to eosiocpp previously to prevent unintended side effect. Let me know if you still encounter the problem.

**Comment by MessyComposer** [comment]
Same thing happens, don't just frantically close the issue.

I can get it kind of working by modifying eosiocpp but then I get errors about missing boost library files.

EOS 1.1.0 is scuffed.

**Comment by andriantolie** [comment]
Hmm, that's strange I don't think eosiocpp boost include directory got changed recently. Normally, the above solution works fine for v1.1.0. What modification did you do?

**Comment by williamleecn** [comment]
must build and **make install**  the eos

**Comment by cppfuns** [comment]
I don't understand why the file path before the modification is placed separately. Is the directory clear? For newcomers who are not familiar with ubuntu, this will be annoying.
Can you give a solution? ?

`Revision: f4ffc26a1e393f33a1542f45f1b1ea388f416ad5
Author: Bucky Kittinger <larrykittinger@gmail.com>
Date: 7/11/2018 1:28:13 AM
Message:
change default to /usr/local/eosio

----
Modified: eosio_build.sh`

**Comment by cppfuns** [comment]
https://www.bcskill.com/index.php/archives/304.html

**Comment by MessyComposer** [comment]
I managed to get it working by making a fresh install of ubuntu.


After close inspection, it seems that build script dependency installation didn't take into account which version of boost I had, and skipped it, leading into missing files.

eosiocpp still doesn't work as expected, but with minor path tinkering I got it working.
