### ISSUE TITLE
rebuild v1.1.0, make test has failed

### ISSUE THREAD

**Issue by Elliottssu** [EOSIO/eos#4764]
When update to v1.1.0, I am rebuild the code, but it failed:
```
The following tests FAILED:
	 32 - nodeos_run_test (Failed)
	 36 - restart-scenarios-test-resync (Failed)
	 38 - restart-scenarios-test-none (Failed)
	 39 - validate_dirty_db_test (Failed)
	 41 - nodeos_voting_lr_test (Failed)
Errors while running CTest
make: *** [test] Error 8
```
what's the matter with it, did i clean the old file  not thorough?

**Comment by NorseGaud** [comment]
Same here. MAC OSX 10.13.6

`90% tests passed, 4 tests failed out of 41

Label Time Summary:
long_running_tests    =   2.53 sec*proc (2 tests)

Total Test time (real) = 979.92 sec

The following tests FAILED:
	 32 - nodeos_run_test (Failed)
	 36 - restart-scenarios-test-resync (Failed)
	 38 - restart-scenarios-test-none (Failed)
	 41 - nodeos_voting_lr_test (Failed)
Errors while running CTest
make: *** [test] Error 8`

**Comment by lazaridiscom** [comment]
@Elliottssu , @NorseGaud have you solved this? Just update to 1.1.3, and you should be fine.

**Comment by NorseGaud** [comment]
I'll try today. Thanks for the follow up.

**Comment by NorseGaud** [comment]
More failures now haha

<pre>
88% tests passed, 5 tests failed out of 41
Label Time Summary:
long_running_tests    = 1262.58 sec*proc (2 tests)
Total Test time (real) = 2233.56 sec
The following tests FAILED:
	 32 - nodeos_run_test (Failed)
	 36 - restart-scenarios-test-resync (Failed)
	 37 - restart-scenarios-test-hard_replay (Failed)
	 39 - validate_dirty_db_test (Failed)
	 40 - nodeos_sanity_lr_test (Failed)
Errors while running CTest
make: *** [test] Error 8</pre>

**Comment by lazaridiscom** [comment]
1.1.4 is now out. My last test with 1.1.3 worked fine on ubuntu 18.04 (except some rare failures of the last test).

You could try a super-fresh install (fetch latest code to another dir).

**Comment by NorseGaud** [comment]
Yep, I tried both versions.
