### ISSUE TITLE
a

### ISSUE THREAD

**Issue by ghost** [EOSIO/eos#4765]

**Comment by DexHunter** [comment]
I met the following error (also on ubuntu 1804)

```
76% tests passed, 10 tests failed out of 41

Label Time Summary:
long_running_tests    =   7.54 sec*proc (2 tests)

Total Test time (real) = 607.87 sec

The following tests FAILED:
	 31 - nodeos_sanity_test (Failed)
	 32 - nodeos_run_test (Failed)
	 34 - nodeos_run_test-mongodb (Failed)
	 35 - distributed-transactions-test (Failed)
	 36 - restart-scenarios-test-resync (Failed)
	 37 - restart-scenarios-test-hard_replay (Failed)
	 38 - restart-scenarios-test-none (Failed)
	 39 - validate_dirty_db_test (Failed)
	 40 - nodeos_sanity_lr_test (Failed)
	 41 - nodeos_voting_lr_test (Failed)
Errors while running CTest
Makefile:119: recipe for target 'test' failed
make: *** [test] Error 8

```

**Comment by lazaridiscom** [comment]
Similar problems here. Related Issue #4833

**Comment by DexHunter** [comment]
@lazaridiscom Any solutions yet?

**Comment by lazaridiscom** [comment]
@DexHunter , I avoid "plumbing around" (trial&error) to find solutions, so I filed #4833 and await at this point feedback from the team.

--

@heifner & Team: Entry-Barrier-Issues like this should be processed with highest priority. If a developer evaluates e.g. ETH and EOS in parallel, he will most possibly choose the system with the least entry barriers.

**Comment by heifner** [comment]
You can run with `ctest --output-on-failure` to see failure output. You can look at `ctest --help` for other options including how to run individual tests.

**Comment by lazaridiscom** [comment]
@DexHunter , check with

* `sudo ctest --output-on-failure -R nodeos_sanity_test`

on my side i get:

```bash
31/41 Test #31: nodeos_sanity_test ...................***Failed    0.61 sec
 is not a valid path
 is not a valid path
 is not a valid path
 BEGIN
 UTC time: 2018-07-24 22:46:18.220263
 EOS Client version: 75635168
 Processor: x86_64
 OS name: Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-16.04-xenial
SERVER: localhost
PORT: 8888
 cmd: pkill -9 keosd
 cmd: programs/eosio-launcher/eosio-launcher -k 9
 cmd: pkill -9 nodeos
Stand up cluster
  Checking if port 8888 is available.
  Checking if port 8889 is available.
 cmd: programs/eosio-launcher/eosio-launcher -p 1 -n 1 -s mesh -d 1 -i 2018-07-24T22:46:18.323 -f --p2p-plugin net --nodeos --max-transaction-time 5000 --abi-serializer-max-time-ms 5000 --filter-on * --p2p-max-nodes-per-host 1 --contracts-console
 ERROR: Launcher failed to launch.
 FAILURE - launcher
 ERROR: Failed to stand up eos cluster.
 Test failed.
   =================================================================
   Contents of etc/eosio/node_bios/config.ini:
   File etc/eosio/node_bios/config.ini not found.
   =================================================================
   Contents of var/lib/node_bios/stderr.txt:
   File var/lib/node_bios/stderr.txt not found.
  =================================================================
 == Errors see above ==
 Shut down the cluster.
  cmd: programs/eosio-launcher/eosio-launcher -k 9
  cmd: pkill -9 nodeos
 Shut down the wallet.
  cmd: pkill -9 keosd
```

**Comment by lazaridiscom** [comment]
Those paths seem to cause trouble elsewhere too (note: regression is mentioned there) : https://github.com/EOSIO/eos/issues/2715#issuecomment-391762686

**Comment by DexHunter** [comment]
@lazaridiscom I got basically the same error
```
Test project /home/dex/github/eos/build
    Start 31: nodeos_sanity_test
1/1 Test #31: nodeos_sanity_test ...............***Failed    0.18 sec
 is not a valid path
 is not a valid path
 is not a valid path
 BEGIN
 UTC time: 2018-07-27 16:16:54.727825
 EOS Client version: 40a20769
 Processor: x86_64
 OS name: Linux-4.15.0-23-generic-x86_64-with-Ubuntu-18.04-bionic
SERVER: localhost
PORT: 8888
 cmd: pkill -9 keosd
 cmd: programs/eosio-launcher/eosio-launcher -k 9
 cmd: pkill -9 nodeos
Stand up cluster
  Checking if port 8888 is available.
  Checking if port 8889 is available.
 cmd: programs/eosio-launcher/eosio-launcher -p 1 -n 1 -s mesh -d 1 -i 2018-07-27T16:16:54.752 -f --p2p-plugin net --nodeos --max-transaction-time 5000 --abi-serializer-max-time-ms 5000 --filter-on * --p2p-max-nodes-per-host 1 --contracts-console
 ERROR: Launcher failed to launch.
 FAILURE - launcher
 ERROR: Failed to stand up eos cluster.
 Test failed.
   =================================================================
   Contents of etc/eosio/node_bios/config.ini:
   File etc/eosio/node_bios/config.ini not found.
   =================================================================
   Contents of var/lib/node_bios/stderr.txt:
   File var/lib/node_bios/stderr.txt not found.
  =================================================================
 == Errors see above ==
 Shut down the cluster.
  cmd: programs/eosio-launcher/eosio-launcher -k 9
  cmd: pkill -9 nodeos
 Shut down the wallet.
  cmd: pkill -9 keosd


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.19 sec

The following tests FAILED:
	 31 - nodeos_sanity_test (Failed)
Errors while running CTest
```

**Comment by DexHunter** [comment]
I think the error is caused by missing files
```
    =================================================================
    Contents of etc/eosio/node_bios/config.ini:
    File etc/eosio/node_bios/config.ini not found.
    =================================================================
    Contents of var/lib/node_bios/stderr.txt:
    File var/lib/node_bios/stderr.txt not found.
   =================================================================
```
But I do not know how should I generate those files? Any ideas?

**Comment by lazaridiscom** [comment]
@DexHunter I thought this initially, too, but it could be just a bad written general message-template.

Strangely, the developers keep silence around all this, its like they want newcomers to struggle with a fresh build. This is totally irritating...

What you could do now (I'll do it in a few hours, too) is:

* locate the locations of the error-logs and look for hints
* try an older version (but this can introduce new problems, due to different versions of dependencies)

I understand that you are on a real ubuntu machine (e.g. not WSL or Virtualbox), so at least this way I know that its not a WSL (Windows Subsystem for Linux) thing.

**Comment by heifner** [comment]
It is not that we wish newcomers to struggle. We have limited resources and this type of thing can really drain those resources. We are actively working on making the tests more resilient.

**Comment by heifner** [comment]
I imagine the sudo is suspect. That might be interfering with file creation/deletion and paths.

**Comment by lazaridiscom** [comment]
@heifner , I understand your struggle. Just help me to help you (i will later provide an update for your documentation, to make things easier for others).

Are there any "hidden" error-log locations I should look at (to spot why the eosio-launcher fails? )

And: I'm assuming that the location-errors are of secondary nature, so they can be ignored for now. Am I assuming right? (I mean those here:

```
    =================================================================
    Contents of etc/eosio/node_bios/config.ini:
    File etc/eosio/node_bios/config.ini not found.
    =================================================================
    Contents of var/lib/node_bios/stderr.txt:
    File var/lib/node_bios/stderr.txt not found.
   =================================================================
```

**Comment by lazaridiscom** [comment]
# Workaround

@nicoodie , @DexHunter 

* cd into your eosio source directory (where `eosio_build.sh` resides)
* `touch validate.sh`
* `sudo chmod 755 validate.sh`

copy the following content into `validate.sh`

```bash
#!/bin/bash
##########################################################################
# Workaround for issue https://github.com/EOSIO/eos/issues/4765
#
cd build;
ctest --output-on-failure -R nodeos_sanity_test
cd ..
```

and then run

`sudo ./validate.sh`

works on my side, on the `develop` branch (but should work on master, too).

You can then remove the `-R nodeos_sanity_test` part, to run the full tests.

**Comment by lazaridiscom** [comment]
@heifner , to clarify, it's not a `sudo` thing, but most possibly a `relative path` thing.

**Comment by lazaridiscom** [comment]
@nicoodie , @DexHunter 

I managed to get quite far with this (above workaround not needed anymore) :

* ubuntu 18.04

```bash
sudo apt update
sudo apt upgrade
#fetch latest master code
./eosio_build.sh
#start mongodb as mentioned
cd build
ctest --output-on-failure
```

**Comment by lazaridiscom** [comment]
@nicoodie , @DexHunter have you solved this? Just update to 1.1.3, and you should be fine.

**Comment by taokayan** [comment]
is not a valid path => please set EOSIO_HOME to your build path.

**Comment by jgiszczak** [comment]
Abandoned and erased by original poster, and likely OBE.
