### ISSUE TITLE
rpc /v1/history/get_transaction return error,but others works wall.

### ISSUE THREAD

**Issue by whiteblackbee** [EOSIO/eos#4766]
v1.1.0
any other cleos cmd works wall,but "/v1/history/get_transaction"
and i start the nodeos with ```--http-validate-host false```
![image](https://user-images.githubusercontent.com/21164253/42994223-0b6498b4-8c40-11e8-9c37-33ce7bb97c8c.png)

**Comment by jgiszczak** [comment]
The `get_transaction` API is only available if history_plugin has been enabled on the node.  Note that history plugin is deprecated, but the replacement is not yet complete.  It may be used on smaller networks successfully.
