### ISSUE TITLE
The cleos prompts that the private key is wrong when vote on the command line

### ISSUE THREAD

**Issue by yqzzj** [EOSIO/eos#4767]
The cleos prompts that the private key is wrong when I vote on the command line on local eosio test net.

root@eosnew:~# cleos system voteproducer prods voter zhangzhijiao producers accountnum11
2018-07-20T08:26:09.289 thread-0   main.cpp:438                  create_action        ] result: {"binargs":"0000000080ab32dd0000000000000000031082d4334f4d11320000c057219de8ad408d7bae7d364dfb"} arg: {"code":"eosio","action":"voteproducer","args":{"voter":"voter","proxy":"","producers":["accountnum11","producers","zhangzhijiao"]}} 
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked

root@eosnew:~# cleos get account zhangzhijiao
permissions: 
     owner     1:    1 EOS6Wz6kqpd2UidU1G8netofPZCdv16TQpFwSQs6pj8FXqGmnqBTy
        active     1:    1 EOS6Wz6kqpd2UidU1G8netofPZCdv16TQpFwSQs6pj8FXqGmnqBTy
memory: 
     quota:     6.512 MiB    used:      3.49 KiB  

net bandwidth: 
     staked:  400000000.0000 SYS           (total stake delegated from account to self)
     delegated:  100000.0000 SYS           (total staked delegated to account from others)
     used:               145 bytes
     available:        164.6 TiB  
     limit:            164.6 TiB  

cpu bandwidth:
     staked:  400000000.0000 SYS           (total stake delegated from account to self)
     delegated:  100000.0000 SYS           (total staked delegated to account from others)
     used:             5.484 ms   
     available:         4794 hr   
     limit:             4794 hr   

SYS balances: 
     liquid:     98799910.0000 SYS
     staked:    800000000.0000 SYS
     unstaking:         0.0000 SYS
     total:     898799910.0000 SYS

producers:     <not voted>

root@eosnew:~# cleos wallet private_keys --password PW5KhFbzTwYBBifzqEHvDLUG9kc77cpRXRKXdXLcGmpswf673hYEU
[[
    "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
    "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
  ],[
    "EOS6Wz6kqpd2UidU1G8netofPZCdv16TQpFwSQs6pj8FXqGmnqBTy",
    "5K6rkE3UmNp3WfSSHjaG8Hep1MQgYiaxGMbBb9bT4XyuT8hTiGL"
  ],[
    "EOS6m5LewS8WVyfs2KVRqxyMkVJ247BwSRQtnQnUr1TX1opGYdkRF",
    "5J6efF8K4sDAz27T6yo74rg5xCMZCQqPdZPWQ7hToe2quvhtc3w"
  ]
]

root@eosnew:~# cleos system listproducers
Producer      Producer key                                           Url                                                         Scaled votes
accountnum11  EOS6Wz6kqpd2UidU1G8netofPZCdv16TQpFwSQs6pj8FXqGmnqBTy  https://accountnum11.com/EOS6Wz6kqpd2UidU1G8netofPZCdv16TQp 0.0000
accountnum12  EOS6Wz6kqpd2UidU1G8netofPZCdv16TQpFwSQs6pj8FXqGmnqBTy  https://accountnum12.com/EOS6Wz6kqpd2UidU1G8netofPZCdv16TQp 0.0000

The wallet is already unlocked and I can transfer from zhangzhijiao.
root@eosnew:~# cleos transfer zhangzhijiao accountnum11 "1 SYS"
executed transaction: 38f0721712e644677343bcb4cf6d37f18ad2662e281c1273f9b8d7fe9041e179  128 bytes  413 us
#   eosio.token <= eosio.token::transfer        {"from":"zhangzhijiao","to":"accountnum11","quantity":"1.0000 SYS","memo":""}
#  zhangzhijiao <= eosio.token::transfer        {"from":"zhangzhijiao","to":"accountnum11","quantity":"1.0000 SYS","memo":""}
#  accountnum11 <= eosio.token::transfer        {"from":"zhangzhijiao","to":"accountnum11","quantity":"1.0000 SYS","memo":""}
warning: transaction executed locally, but may not be confirmed by the network yet    ] 
root@eosnew:~# cleos system voteproducer prods voter zhangzhijiao producers accountnum11
2018-07-20T08:49:21.001 thread-0   main.cpp:438                  create_action        ] result: {"binargs":"0000000080ab32dd0000000000000000031082d4334f4d11320000c057219de8ad408d7bae7d364dfb"} arg: {"code":"eosio","action":"voteproducer","args":{"voter":"voter","proxy":"","producers":["accountnum11","producers","zhangzhijiao"]}} 
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.

Why the command line show the error about private key?

**Comment by ChaselChen3** [comment]
I don't know if it's a new version of the problem.

**Comment by jgiszczak** [comment]
Try:
`cleos system voteproducer prods zhangzhijiao accountnum11`
or
`cleos system voteproducer prods zhangzhijiao accountnum11 accountnum12`
The command you used was attempting to vote as user `voter`, which doesn't exist, and so its keys can't be found.

`cleos` help text for non-option arguments is meant to be substituted rather than appended.
