### ISSUE TITLE
Is there a feature like Ether's payable in the EOS contract?

### ISSUE THREAD

**Issue by sycnanana** [EOSIO/eos#4769]
Is there a feature like Ether's payable in the EOS contract? How  can I get EOS transfer info outside of the contract?

**Comment by jgiszczak** [comment]
There is no equivalent to the `payable` function tag in Solidity.  If you wish to handle transfers, you should write a `transfer()` method in your contract and register it along with your other actions in `EOSIO_DISPATCH( yourcontract, (transfer) )`.

Outside of contracts, EOS transfer information is retrieved from a database or mongodb instance populated by a nodeos running eosio_sql_plugin or mongo_db_plugin, respectively.  You may also create a process which listens to state_history_plugin.
