### ISSUE TITLE
Docker does not have wallet embedded

### ISSUE THREAD

**Issue by pavybez** [EOSIO/eos#477]
Users trying docker cannot use eos because there is no wallet if these instructions are followed:

https://github.com/EOSIO/eos/tree/master/Docker

The solution is to modify the config.ini to include wallet_api_plugin and change the http-server-port to 127.0.0.1 from 0.0.0.0 in config.ini.

**Comment by pavybez** [comment]
The solution is to modify the config.ini to include wallet_api_plugin and change the http-server-port to 127.0.0.1 from 0.0.0.0 in config.ini.

**Comment by andriantolie** [comment]
This pull request should fix this issue https://github.com/EOSIO/eos/pull/465
