### ISSUE TITLE
nodeos command not found

### ISSUE THREAD

**Issue by mlawand** [EOSIO/eos#4771]
i have updated today my eosio to version 1.1 and these are the steps that i have took.
- git pull
-  ./eosio_build.sh
-   cd build
-   sudo make install

Everything completed successfully. After this when i try to run EOS locally i get this error

    bash: nodeos: command not found

i looked around for solution but i am not able to fix it. I have run the test and it's failing on

Test #32: nodeos_run_test ......................***Failed    0.25 sec
Test #36: restart-scenarios-test-resync ........***Failed    0.33 sec
Test #37: restart-scenarios-test-hard_replay ...***Failed    0.36 sec
Test #39: validate_dirty_db_test ...............***Failed    0.24 sec
Test #40: nodeos_sanity_lr_test ................***Failed    0.31 sec

**Comment by jgiszczak** [comment]
Binaries are installed to `/usr/local/eosio/bin` in the 1.1 release.  You'll need to add that path to your PATH environment variable.  This is not expected to continue in future releases.

To see why your tests are failing, in your `build` directory, run `ctest --output-on-failure`.

**Comment by gunnarpope** [comment]
Spot on @jgiszczak ! This worked for me:
```
$ export PATH=$PATH:/usr/local/eosio/bin
```
