### ISSUE TITLE
nodeos got stuck after lots of error information

### ISSUE THREAD

**Issue by vjoke** [EOSIO/eos#4775]
We have found a weird problem which froze the nodeos. 
Version: 1.0.8
Before nodeos got stuck, a lot of error information is printed:
![image](https://user-images.githubusercontent.com/7498344/43029934-78cae5ca-8cbd-11e8-9620-9df6aeefff50.png)

![image](https://user-images.githubusercontent.com/7498344/43029947-8e588320-8cbd-11e8-9e09-d4dc34cbf918.png)
And we checked the calling stack:
![image](https://user-images.githubusercontent.com/7498344/43029898-38650e3e-8cbd-11e8-85d5-c436f64aee55.png)

Is there any solution for this problem? @taokayan

**Comment by taokayan** [comment]
Can you shared the steps to reproduce this issue? What transactions/actions did you make?

**Comment by jgiszczak** [comment]
Unresponsive for 153 days, refers to a version of the software more than 6 releases ago.  Insufficient data to make any sort of determination of what the problem might be.
