### ISSUE TITLE
The primary network data cannot be synchronized.

### ISSUE THREAD

**Issue by hyqsfaf** [EOSIO/eos#4777]
2018-07-21T01:01:49.356 thread-0   chain_plugin.cpp:859          log_guard_exception  ] Details: 3060101 database_guard_exception: Database usage is at unsafe levels
database free: 134211040, guard size: 134217728
    {"f":134211040,"g":134217728}
    thread-0  controller.cpp:1623 validate_db_available_size

**Comment by FricWang** [comment]
did you solve this problem ?

**Comment by tqknight1984** [comment]
did you solve this problem ?

**Comment by jooner** [comment]
I was facing the same issue. I'm running my node in a docker container and I was able to resolve this error by going to my config.ini file and increased the `chain-state-db-size-mb`, which is the maximum size of the shared_memory database for storing the state. Remember to configure it to be less than your machine's memory. Hope this helps!
