### ISSUE TITLE
How can i set permission owner with eosio.code

### ISSUE THREAD

**Issue by reluo** [EOSIO/eos#4779]
i can set active permission success and cmd like this.

>  cleos set account permission auth1user active '{"threshold": 1,"keys": [{"key": "EOS5WDrQEdP3CdKYAbF5pi9YKqYCt4UbLNum3yLWb7PF24U3AUHY7","weight": 1}],"accounts": [{"permission":{"actor":"updateauth","permission":"eosio.code"},"weight":1}]}' owner -p auth1user@owner

but when i try to set owner permission and cmd like following

> cleos set account permission auth1user owner '{"threshold": 1,"keys": [{"key": "EOS5WDrQEdP3CdKYAbF5pi9YKqYCt4UbLNum3yLWb7PF24U3AUHY7","weight": 1}],"accounts": [{"permission":{"actor":"updateauth","permission":"eosio.code"},"weight":1}]}' owner -p auth1user@owner

nodes will send error 
> Cannot set an authority as its own parent
    {}
    thread-0  eosio_contract.cpp:214 apply_eosio_updateauth
pending console output:
    {"console":""}
    thread-0  apply_context.cpp:61 exec_one
2018-07-21T03:31:55.005 thread-0   producer_plugin.cpp:1194      produce_block        ] Produced block 00020aa9ef59513c... #133801 @ 2018-07-21T03:31:55.000 signed by eosio [trxs: 0, lib: 133800, confirmed: 0]

how can i do when i want add eosio.code to owner ?

**Comment by reluo** [comment]
i have solve it ,my error lol！

**Comment by rommzestz** [comment]
so, just need 

cleos set account permission testuser active '{"threshold": 1,"keys": [{"key": "EOS6eyYpTygR9NfVefhMjv92zvE2DiX1MdfdrdbEGR","weight": 1}],"accounts": [{"permission":{"actor":"mycontract","permission":"eosio.code"},"weight":1}]}' owner -p testuser @owner
