### ISSUE TITLE
Problems that can be modified by smart contracts 

### ISSUE THREAD

**Issue by williamleecn** [EOSIO/eos#4786]
the smart contract  , I think adding an option that can't be modified,Like f3d, if  can modify it, there will be less  to trust

**Comment by liviu-** [comment]
Yeah, the fact that any token can spontaneously add a `destroy()` or `freeze()` method is worrying. It'd be nice if there was a way to opt-out of mutability and deploy an immutable contract.

**Comment by cppfuns** [comment]
Yes, this problem is very serious for contractual fairness. It is recommended that EOS should be resolved with the highest priority.

**Comment by quocle108** [comment]
It is better if we have 2 mode for the contract. And the user should be know which contract can be modified which cannot.

**Comment by swatanabe-b1** [comment]
The permissions of a contract can be adjusted to make it harder or impossible to modify.
