### ISSUE TITLE
multi-host multi-node testnet tutorial

### ISSUE THREAD

**Issue by dksuper** [EOSIO/eos#4797]
Hi, I have a question, where can I get **multi-host multi-node testnet tutorial**?
,because in [local-multi-node-testnet](https://developers.eos.io/eosio-nodeos/docs/local-multi-node-testnet),have mention **In a later tutorial we will explore how to use more advanced tools to run a multi-host, multi-node testnet**,but i can't find it!

**Comment by ricktobacco** [comment]
Hasn't been posted yet maybe, also waiting for it!

**Comment by dksuper** [comment]
Is there have any tutorial of multi-host, multi-node publish?

**Comment by halsaphi** [comment]
We will raise an internal issue to update the documentation to include a local multi node testnet tutorila, else we will remove this comment. If you feel this tutorial would be useful please contact developers@block.one.
