### ISSUE TITLE
eos version 1.1.0,wallet create Error 3200006?

### ISSUE THREAD

**Issue by Midcc** [EOSIO/eos#4800]
../../build/programs/cleos/cleos --wallet-url http://localhost:5555 --url http://localhost:6000 wallet create
Error 3200006: invalid http request
Error Details:
The server has rejected the request as invalid!
Please verify this url is valid: http://localhost:5555/v1/wallet/create
If the condition persists, please contact the RPC server administrator for localhost!
bios-boot-tutorial.py: exiting because of error

**Comment by Midcc** [comment]
Well, I can replace localhost with 127.0.0.1, but I don't know why this is the problem?

**Comment by andriantolie** [comment]
There is a http host validation in version 1.1.0 which checks whether your request host header matches with your server address or not. I suspect that you configure your nodeos's http-server-address to 127.0.0.1:5555 and your keosd's http-server-address to 127.0.0.1:6000. Another solution is to set http-alias to your nodeos and keosd, i.e. `http-alias=localhost:5555` and `http-alias=localhost:6000` respectively.

**Comment by Midcc** [comment]
Oh, understand, thank you.
