### ISSUE TITLE
how to install the latest eos?

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#4801]
I find the latest eos downloaded from this repo doesnt provide a way to install all tools properly. before, I can get nodeos, cleos, keosd and eosiocpp after I execute make install under build directory. now I have to manually link the tools to somewhere the bash can find. but eosiocpp still can't work properly. it can't find STL headers. how am i supposed to install the latest eos?

**Comment by KennyLiu25775** [comment]
hey @breadbread1984 I also had the same issue where the eosiocpp command does not work at all, just wondering if you have solved the problem? thanks

**Comment by breadbread1984** [comment]
@KennyLiu25775 the latest 1.1 version move all installed files into /usr/local/eosio . you need to add /usr/local/eosio/bin to environmental variable PATH and add /usr/local/eosio/lib to environmental variable LD_LIBRARY_PATH to make bash understand where the binaries is.

**Comment by KennyLiu25775** [comment]
@breadbread1984 hey man sorry i am little dizzy now haha, could you explain little more on this, I am pretty new to EOS dev and C++, hope you can help me, appreciate it

**Comment by breadbread1984** [comment]
you can find all tools you need under directory /usr/local/eosio/bin .

**Comment by KennyLiu25775** [comment]
oh ok thanks buddy, appreciate it

**Comment by breadbread1984** [comment]
no problem

**Comment by KennyLiu25775** [comment]
hey buddy I am so sorry, but would you mind explaining how to "add /usr/local/eosio/bin to environmental variable PATH and add /usr/local/eosio/lib to environmental variable LD_LIBRARY_PATH"? i am not very familiar  with  shell command... :(

**Comment by lazaridiscom** [comment]
@KennyLiu25775 , should be this here:

```bash
export PATH=/usr/local/eosio/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/eosio/lib:$LD_LIBRARY_PATH
```

If you're new to all this, you may find it easier to go with docker based installation:

https://developers.eos.io/eosio-nodeos/docs/docker-quickstart
