### ISSUE TITLE
can't get transaction

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#4802]
I am using the latest eosio. I add history_api_plugin and history_plugin when I launch nodeos, but when I get transaction I get the following error

> Error 3200006: invalid http request                                                                                                                                   
Error Details:                                                                                                                                                        
The server has rejected the request as invalid!                                                                                                                       
Please verify this url is valid: http://192.168.1.100:8000/v1/history/get_transaction                                                                                 
If the condition persists, please contact the RPC server administrator for 192.168.1.100!

the error didn't appearred before. How can i deal with the problem? thx

**Comment by andriantolie** [comment]
Can you share your command that you call for get transaction? And also the command that you used to start nodeos

**Comment by breadbread1984** [comment]
@andriantolie I restart my nodeos. the problem goes away. still thx for replying.

**Comment by banshee** [comment]
(Adding information because I had the same issue and got here from a google search)

I get the error when I connect to localhost, but not when I connect to 127.0.0.1:

```
root@nodeosd:/# cleos -u http://127.0.0.1:8888/ get info
{
  "server_version": "75635168",
  "chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
  "head_block_num": 142835,
  "last_irreversible_block_num": 142834,
  "last_irreversible_block_id": "00022df2e1a6c33ff341272d34fcf5850412469ff4216ca109090ee51d8409fd",
  "head_block_id": "00022df3c60a1b40b347669360e2c9c30e58eaa91848fbb652151e9a2a71be0a",
  "head_block_time": "2018-06-11T06:48:26.500",
  "head_block_producer": "genesisblock",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 200000,
  "block_net_limit": 1048576
}
root@nodeosd:/# cleos -u http://localhost:8888/ get info
Error 3200006: invalid http request
Error Details:
The server has rejected the request as invalid!
Please verify this url is valid: http://localhost:8888/v1/chain/get_info
If the condition persists, please contact the RPC server administrator for localhost!
root@nodeosd:/# host localhost
localhost has address 127.0.0.1
localhost has IPv6 address ::1
root@nodeosd:/# 

```

**Comment by andriantolie** [comment]
@banshee This is because of the http host header validation introduced in v1.1.0. It will check whether your host header matches your nodeos' http-server-address or not. For the above situation, it's very likely that you have configured your nodeos http-server-address parameter to 127.0.0.1:8888 (if you haven't done so, this is the default value), that's why it rejects localhost:8888. If you want it to also work with localhost:8888, use the http-alias param, set it to`http-alias=localhost:8888`

**Comment by yqzzj** [comment]
I got the same issue.
start nodeos:
nohup nodeos --enable-stale-production --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --producer-name accountnum11 --private-key '[ "EOS6Wz6kqpd2UidU1G8netofPZCdv16TQpFwSQs6pj8FXqGmnqBTy","5K6rkE3UmNp3WfSSHjaG8Hep1MQgYiaxGMbBb9bT4XyuT8hTiGL" ]' --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::http_plugin --plugin eosio::history_api_plugin --p2p-peer-address 192.168.52.132:9876 --hard-replay-blockchain --replay-blockchain &

root@eosnew:~# cleos get info
{
  "server_version": "75635168",
  "chain_id": "7982c6fd7ccf06d43fe3a7d2e6a585cc172e90a21360331a2746598956ffb082",
  "head_block_num": 46523,
  "last_irreversible_block_num": 46522,
  "last_irreversible_block_id": "0000b5bad950a22846343827e07e66691502cfedf35c7b5b4ace432f9dbdc921",
  "head_block_id": "0000b5bbcf084d33032ece2c9a72972c9defad6d9155204a26219cbfd494fdde",
  "head_block_time": "2018-07-24T10:15:42.500",
  "head_block_producer": "eosio",
  "virtual_block_cpu_limit": 100000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 99900,
  "block_net_limit": 1048576
}
root@eosnew:~# cleos get transaction 16cbdd50d9d9a2e14c69477125e01a3afdc02b41982ee3385536af2af0c9d62b
Error 3200006: invalid http request
Error Details:
The server has rejected the request as invalid!
Please verify this url is valid: http://127.0.0.1:8888/v1/history/get_transaction
If the condition persists, please contact the RPC server administrator for 127.0.0.1!

**Comment by sivachaitanya** [comment]
how did you resolve this ?
