### ISSUE TITLE
RPC   sign_transaction

### ISSUE THREAD

**Issue by hyqsfaf** [EOSIO/eos#4803]
Use the https://api.eosnewyork.io node. Call the rpc operation of the main network involving the wallet, such as sign_transaction. How to deal with

https://api.eosnewyork.io/v1/wallet/sign_transaction
return
  {
   "message": "PARSE_ERROR",
   "code": 400
}

My own node synchronization is too slow to catch up with the main network

**Comment by andriantolie** [comment]
What's your payload? Seems something is wrong with your payload

**Comment by hyqsfaf** [comment]
If I don't sync the main network node. Whether you can complete the transaction using https://api.eosnewyork.io.

The RPC about the wallet seems to have not been accessed.



[
  {
    "ref_block_num": 7321961,
    "ref_block_prefix": 2281634421,
    "expiration": "2018-07-23T09:38:05.000",
    "scope": [
      "#######",
      "#######"
    ],
    "read_scope": [],
    "actions": [
      {
        "account": "@@@@@",
        "name": "transfer",
        "authorization": [
          {
            "actor": "#######",
            "permission": "active"
          }
        ],
        "data": "30209d4637e48c8620209d4637e48c86e8030001111110000446544300000000057366737373"
      }
    ],
    "signatures": []
  },
  [
    "EOS8FDdchw68CrrdWCmxxxxxxxxxxxxxx"
  ],
  ""
]

**Comment by andriantolie** [comment]
I just realize you are calling the wallet API remotely, you should only call the wallet API to a local endpoint.
