### ISSUE TITLE
Failed to connect to nodeos at http://127.0.0.1:8888/; is nodeos running?  --But -- the port is not occupied, and nodeos is not running.端口没有占用,nodeos 也没在运行。

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#4804]
1、
![image](https://user-images.githubusercontent.com/11773000/43064876-bba79b14-8e92-11e8-827a-1d1a2f82ea0f.png)
sec@ll-B85M-DS3H-A:~/rgh/eos_719/eos/build/programs/cleos$ ./cleos set contract eosio /home/sec/rgh/eos_719/eos/build/contracts/eosio.bios -p eosio@active
Reading WAST/WASM from /home/sec/rgh/eos_719/eos/build/contracts/eosio.bios/eosio.bios.wasm...
Using already assembled WASM...
Publishing contract...
Failed to connect to nodeos at http://127.0.0.1:8888/; is nodeos running?
2、
![image](https://user-images.githubusercontent.com/11773000/43064918-d8bf9f6c-8e92-11e8-89d7-d387c6ca2d19.png)
sec@ll-B85M-DS3H-A:~/rgh/eos_719/eos/build/programs/cleos$ ./cleos create account eosio user  EOS7eanXtt1fx9sThAtg1pohi4bVVfHu2XanYaMjtxhtC65CV2S6q
Failed to connect to nodeos at http://127.0.0.1:8888/; is nodeos running?

3、但是--端口没有占用,nodeos 也没在运行。But -- the port is not occupied, and nodeos is not running.

**Comment by andriantolie** [comment]
If the port is not occupied and nodeos is not running, then you need to start nodeos first before you execute the above cleos command

**Comment by amActiveHello** [comment]
Okay thank you. Previously only considered the port occupancy error.

**Comment by amActiveHello** [comment]
Okay thank you. Previously only considered the port occupancy error.
