### ISSUE TITLE
Docker quickstart 

### ISSUE THREAD

**Issue by sztwiorok** [EOSIO/eos#4805]
there was a documentation about how to use eosio-dev docker image
https://eosio-nodeos.readme.io/docs/docker-quickstart

I can't find it in the current documentation's table of contents. Is it deprecated?

thanks in advance

**Comment by lazaridiscom** [comment]
its there:

https://developers.eos.io/eosio-nodeos/docs/docker-quickstart

and another one, reachable from the left-side menu:

https://developers.eos.io/eosio-nodeos/docs/docker

(as a sidenote: the design of https://eosio-nodeos.readme.io/docs looks much better, possibly some css was not transferred correctly to https://developers.eos.io).

**Comment by andriantolie** [comment]
Yep, developers.eos.io is our current official documentation
