### ISSUE TITLE
subscribe channel not working

### ISSUE THREAD

**Issue by zhangqwesc** [EOSIO/eos#4806]
I tried to write a plugin that tried to print something when accepting a new block, but it seems like this doesn't work. 
this is my code:
```
void test_plugin::plugin_startup() {
    ilog( "starting test_plugin" ); //this is working correctly
    app().get_channel<channels::accepted_block>().subscribe([this](block_state_ptr s) {
        ilog( "accepted block!!!!!" ); //this will never print, although the block is increasing.
    });
}
```
can someone help me?

**Comment by taokayan** [comment]
I guess you have a single node running that will only produce block rather than accepting block.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
