### ISSUE TITLE
different cpu time usage on different machine?

### ISSUE THREAD

**Issue by tjchern** [EOSIO/eos#4808]
When I refer to the eos code, I have a question: in cpu limit, cpu usage just base on system clock, so a transaction run on different machine, will consume different cpu time, so maybe a tansaction will be pushed to block on a faster cpu machine, but can't be pushed to block on a slower cpu machine because of time usage exceed. So how to resolve this problem in eos?
thank you

**Comment by vjoke** [comment]
This is by design. since eos use subjective billing instead of objective billing.

**Comment by andriantolie** [comment]
Guess this ticket is already answered by #4572. I'm closing this issue

**Comment by tjchern** [comment]
Thank you
