### ISSUE TITLE
chain/push_transaction   failure

### ISSUE THREAD

**Issue by hyqsfaf** [EOSIO/eos#4810]
2018-07-23T11:20:26.261 thread-0   http_plugin.cpp:476           handle_exception     ] Exception Details: 3090003 unsatisfied_authorization: Provided keys, permissions, and delays do not satisfy declared authorizations
transaction declares authority '{"actor":"kuaichuanok2","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys ["EOS5Xd8tV91C9NhkaihmtPX1EQf9xnX8kBj3nEqScoHCBXMBmZNFZ"]
    {"auth":{"actor":"kuaichuanok2","permission":"active"},"provided_delay":0,"provided_permissions":[],"provided_keys":["EOS5Xd8tV91C9NhkaihmtPX1EQf9xnX8kBj3nEqScoHCBXMBmZNFZ"],"delay_max_limit_ms":3888000000}
    thread-0  authorization_manager.cpp:411 check_authorization

I don't have the private key of EOS5Xd8tV91C9NhkaihmtPX1EQf9xnX8kBj3nEqScoHCBXMBmZNFZ

**Comment by jgiszczak** [comment]
If you do not have the matching private key for the public key in question, you can not sign transactions with that key.

**Comment by readygo586** [comment]
@hyqsfaf, Did you find the exact reason for such problem? I met similar problem  listed in https://github.com/EOSIO/eos/issues/5774
