### ISSUE TITLE
cleos push action not returning output

### ISSUE THREAD

**Issue by mlawand** [EOSIO/eos#4811]
I have published a very simple smart contract to my local network and i am testing it if its working, everything was pushed correctly. 
i am using this hello world example as reference 

> https://medium.com/coinmonks/printing-hello-world-with-eos-smart-contract-50fbe873d1b4

when i try to push an action like this `cleos push action scuser hi '["user1"]' -p scuser`

i dont get an output of the function i get this 
`executed transaction: 6a7a7c4f0cfd72f14a3bfe618a765e0b4a11e31b197cc401a57f4439a9b7d442  104 bytes  276 us
  scuser <= scuser::hi                   {"user":"user1"}
warning: transaction executed locally, but may not be confirmed by the network yet    ] `

any idea on how to solve this?

**Comment by jgiszczak** [comment]
`cleos` does not receive a copy of output from `print()`.  To see `print()` output, add `--contracts-console` to the `nodeos` command line.  Your output will be in the `nodeos` log.

**Comment by mlawand** [comment]
@jgiszczak where is the nodeos log?

**Comment by jgiszczak** [comment]
That depends on how you ran `nodeos`.  It does not write to file natively, so if you didn't include redirection to a file in your command line when you launched `nodeos`, it's simply in the console window where you started it.  If you did include redirection, it will be in that file.

**Comment by huelite** [comment]
For anyone being held up by this i found a work around. If you use 
`cleos push transaction json_file_containing_transaction.json`
instead of **_cleos push action ..._** then you get lots of information on the transaction displayed in the console including your prints.
