### ISSUE TITLE
[PRODUCT] Concise Naming of Things

### ISSUE THREAD

**Issue by lazaridiscom** [EOSIO/eos#4814]
The eosιο executables were recently renamed.

## Previous Naming

* `eosiod`
* `eosioc`
* `eosiowd`

## New/Current Naming
* `Nodeos` -  I do not read "eos", but some other words. "Node os" -> Node OS (I associate this with node.js)
* `Cleos` - I read the word fluent, so "eos" disappears (e.g.: I do not read: "cl eos" but Cle OS)
* `Keosd` - sounds a bit like "kerberos"

Essentially, #1700 and #1968 introduced a **regression on product-level** 

**Weaknesses**

* those names are not "eos"-centric (especially "Nodeos" kills the "eos" brand)
* those names are not self-describing

## Suggested Naming

Product/System: `eos`

Subsystems add a suffix to `eos` (`node`, `blockchain`, `wallet`)
 

* nodeos / eosiod
  * `eosnode` (eos node)
  * eosbc (eos blockchain)
* cleos / eosioc
  * `eos` (the most simple/concise term, for the most used exec)
* eoskey / eosiowd
  * eosks (eos keystore)
  * eoskey
  * `eoswallet`

One could argue (or proof) that "deamons" must have a "d" at the end.

My personal favorites would be:

* `eosnode`, `eoswallet` and finally `eos` for the main cli

Edit (after another mental pass) :

* `eosd`, `eos`, `eoskeyd`

**Comment by jgiszczak** [comment]
Thank you for your feedback.  We are not planning on any further renaming at this time.

**Comment by lazaridiscom** [comment]
@jgiszczak , you should really not close issues that fast.

This issue is tagged "PRODUCT", and thus it affects `Product Management` (and thus C-level, in the business sense).

This issue here affects a **major** **defect** in the eosio system. 

I don't know the rationales which led to the renaming - but there is a quite clear indication that there are no rationales at all:

from #1968
> keosd is a play on words, it's a wallet daemon that stores EOS security keys. We started with keyeosd but it was hard to pronounce (key-eos-dee) so we dropped the "ey" and ended up with keosd which phonetically has both "key" and "eos" in the word. Yes, we're nerds. 🤓

Naming things is not a **Game of Nerdiness**.

Its a matter of **Professionalism** or (if you prefer) **Gentleness**.

Provide concise naming, which does not confuse the users, especially the newcomers.

As i cannot reopen the issue myself, I ask you to reopen it, thus the Product Manager can take a look.

At the very minimum, the Product Manager should look at this:

# nodeos - a node.js based operationg-system

vs

# eosd - the EOS daemon

**Comment by jgiszczak** [comment]
As it happens, I am the author of the patch that introduced the current names.  The names were suggested by Dan Larimer.  Clarity of verbal communications was obviously a priority.  Nor was that change recent.  The current names were introduced March 19th.  Since then, all reference documentation, tutorials, presentations, even online videos produced by block.one employees and third parties all refer to those names.

We are not planning on any further renaming at this time.

**Comment by dskvr** [comment]
@lazaridiscom Most would probably agree that the ideal naming of the components were as you have suggested, myself included. However, there a caveat you're overlooking. 

**eos** is a blockchain network launched by the community. 
**eosio** is a blockchain _platform_ developed by block.one

The standardized route would then imply the "correct" naming to be as follows
1. eosio or eosioc
2. eosiod
3. eosiokeyd

However, this is less easy to type, it's inefficient. It is also rather difficult to verbally communicate, for example, in video tutorials. At-a-glance recognition that "eosiod" is "eosiod" and not "eosioc" is more difficult with this naming scheme. 

The actual names used today were the result of a brainstorm session to farm solutions to the naming scheme, really intended to get the conversation started. To my surprise these names were integrated into the platform shortly there-after. 

Many devs alias their EOSIO installation to their preferences similar to patterns you have standardizations you have shown above.

**Comment by lazaridiscom** [comment]
@dskvr , I understand your elaborations, but the eos/eosio distinction is a "light detail", as shrinking "eosio" to "eos" does not result in any confusion. 

In contrast, the violated main requirements are "heavy details" :

## Requirements

1. Name is not taken elsewhere (this prime-requirement should be indisputable)
2. Name follows branding rules
1. [...]
1. easy verbal communication (e.g. video tutorials)

Verbal communication is not a top priority requirement (there are others).

## Candidates

* nodeos
  *  fails requirement 1.), as its already taken by https://node-os.com/
  * fails requirement 2.), as it reminds "node" (node.js)


> The actual names used today were the result of a brainstorm session to farm solutions to the naming scheme, really intended to get the conversation started. To my surprise these names were integrated into the platform shortly there-after.

Obviously someone was to fast (similar to @jgiszczak  and others within this repo closing issues very fast, making this repo a personal playground, and not an open resource - but this is another **governance** issue).

All this is an indication for a weak governance, for missing procedures. Thus, the main action would be here:

## Rename-Procedure

https://forums.eosgo.io/discussion/1768/nodeos-naming-things-is-not-a-game-of-nerdiness

## Live-Rename-Procedure

**nodeos** is live, and this is the minimum name which should be renamed. A possible procedure would be

* find the new names using the Rename-Procedure
* provide new names as aliases
* start to use new names everywhere
* drop original names after e.g. 6 months

Technical barriers should be solvable.

## The Naming Things Hell

I personally live always this hell, moving from one name to another. But when its a system like eos, you really have to follow some standard-procedures for renaming, which **must** involve community, avoiding this way accidents like this with `nodeos`.
