### ISSUE TITLE
EOS nodes Problems | EOS节点问题

### ISSUE THREAD

**Issue by williamleecn** [EOSIO/eos#4815]
1.Can you list some nodes on the site to allow developers to synchronize data quickly? 
2.Can the Official  set up some nodes? The synchronization is now very slow and many nodes are unable to connect
3.Could you provide me with funding for me to set up some nodes? 

I come from China, China now has a lot of EOS users and developers, I hope to help this vast group, and also facilitate the development of myself .

QQ:260914013

**Comment by cppfuns** [comment]
https://www.bcskill.com/index.php/archives/92.html
There are three ways to get the available p2p-peer-address

**Comment by jgiszczak** [comment]
Block.one does not sponsor or endorse any specific blockchain running with EOS.IO software.

A list of public nodes on what is commonly called 'mainnet' is available [here](https://eosnodes.privex.io/).  If many of those node are inaccessible, you are encouraged to create a curated list of nodes which are accessible within China.
