### ISSUE TITLE
action 'eosio::setcode' is on the action blacklist

### ISSUE THREAD

**Issue by xnfy520** [EOSIO/eos#4821]
Error 3130005: Action to execute is on the blacklist
Error Details:
action 'eosio::setcode' is on the action blacklist
pending console output:

in mainnet

Why is this?

**Comment by chuang39** [comment]
The issue here. Any idea?

**Comment by thbourlove** [comment]
Same issue here.

**Comment by yanxi-me** [comment]
I get the same error.

**Comment by chriszhao1988** [comment]
Same issue

**Comment by yanxi-me** [comment]
Where is the news? I can't found this on eos.io @matthewdarwin

**Comment by thbourlove** [comment]
how to check the status of block list?

**Comment by RonLino** [comment]
I have got this error since yesterday.
Some news?
are thre some workaround to deploy a contract?

**Comment by matthewdarwin** [comment]
According to discussion I see in telegram, the blacklist is proposed to be removed by end-of-day (US time) July 25.

**Comment by gulbinas** [comment]
![image](https://user-images.githubusercontent.com/3935101/43235280-cb5890d4-9088-11e8-9db9-3c9ff7f41020.png)

**Comment by abourget** [comment]
A bunch of producers removed the blacklist now

**Comment by chriszhao1988** [comment]
Already working properly

**Comment by jgiszczak** [comment]
@thbourlove An API has been created to retrieve the contents of the blacklist and whitelist.  It will be available in version 1.2. See #4853.

`set code` is generally available on mainnet again.
