### ISSUE TITLE
meet error when setting contract

### ISSUE THREAD

**Issue by breadbread1984** [EOSIO/eos#4825]
I compile my contract successfully, but can't upload to account. the error message is 

> Reading WAST/WASM from GeneMelee/GeneMelee.wasm...                                                                                                                    
Using already assembled WASM...                                                                                                                                       
Publishing contract...                                                                                                                                                
Error 3070002: Runtime Error Processing WASM

the detail of the error messge from the log is 

> 2018-07-24T07:16:44.637 thread-0   http_plugin.cpp:476           handle_exception     ] Exception Details: 3070002 wasm_execution_error: Runtime Error Processing WASM
Nested depth exceeded                                                                                                                                                     
    {}                                                                                                                                                                    
    thread-0  wasm_eosio_validation.hpp:116 accept                                                                                                                    
pending console output:                                                                                                                                                   
    {"console":""}                                                                                                                                                        
    thread-0  apply_context.cpp:61 exec_one

what is the meaning of this error and how can I locate the problem? thx.

**Comment by issayTseng** [comment]
in wasm_eosio_validation.hpp, it restrict the nested depth within 1024. so checking the loop/if/else depths would solve the problem I guess~

**Comment by breadbread1984** [comment]
got it, thx!

**Comment by crazybits** [comment]
```
Error 3070002: Runtime Error Processing WASM
Error Details:
Nested depth exceeded
pending console output:
```

my contract is fine before,  above error encountered when re-compile and set contract recently, is this feature added recently? @issaxyz
