### ISSUE TITLE
use jsoncpp in  contract failed and how to change the wasm.cmake

### ISSUE THREAD

**Issue by sulier2684** [EOSIO/eos#4827]
in contract api is generated, but it falied 

code:
Json::Reader reader;

The error is

 Failed with error: Assert Exception (10)
!"unresolvable": env.ZN4Json5Value6appendERKS0

someone use change the arg “WASM_COMMAND” from wasm.cmake,but i have append “-ljson” ,return failed, who test add jsoncpp successed,please tell me the detail,thanks

**Comment by jgiszczak** [comment]
Consider using a header-only [JSON library](https://github.com/nlohmann/json). Adding `-ljson` will not work.  If you're using a json library that requires object files, you must add the source files of the library to your contract.  The entire library must be compiled to WASM.
