### ISSUE TITLE
Docker RPC doesn't work.

### ISSUE THREAD

**Issue by liderako** [EOSIO/eos#4829]
I use this tutorial [docker-quickstart](https://developers.eos.io/eosio-nodeos/docs/docker-quickstart)

`http://localhost:8888/v1/chain/get_info` and `curl http://localhost:8888/v1/chain/get_info` doesn't work.

`cleos get info` working

How to fix it? I use docker.

**Comment by vjoke** [comment]
add option --http-validate-host false

**Comment by liderako** [comment]
docker run --rm --name eosio -d -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev  /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console `--http-validate-host=false`"

--http-validate-host equal false

[docker-quickstart](https://developers.eos.io/eosio-nodeos/docs/docker-quickstart)
<img width="680" alt="screen shot 2018-07-24 at 4 17 33 pm" src="https://user-images.githubusercontent.com/25816656/43140756-1d7a16a8-8f5d-11e8-922b-661d54a136bf.png">

**Comment by andriantolie** [comment]
With --http-validate-host equal to false the above command should work fine. Which version of eos are you using? Can you use the latest docker v1.1.1 and make sure you are using exactly the above command? I tested it with the above command and everything works fine

**Comment by liderako** [comment]
Docker latest version. Returned error.

<img width="1139" alt="screen shot 2018-07-25 at 11 47 41 am" src="https://user-images.githubusercontent.com/25816656/43190057-c40f83ce-9000-11e8-8917-c66da7ce1f7d.png">

after this command 

> docker run --name eosio -d -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false"

**Comment by liderako** [comment]
@guomingyi I did try yesterday, but it command too doesn't work

**Comment by andriantolie** [comment]
Your database is dirty. Very likely because of a non-graceful shutdown previously (you might need to give more timeout to your `docker stop`).
Try to replay it and fix irreversible blocks by adding the following args `--replay --fix-reversible-blocks`

**Comment by liderako** [comment]
@andriantolie Thanks, I fixed it.

But `curl http://0.0.0.0:8888/v1/chain/get_info` still doesn't work

**Comment by andriantolie** [comment]
Hmm... Is your nodeos running fine? (check`docker logs -f eosio`) And also if you ssh to your docker container and call the above command, what did you get?

**Comment by liderako** [comment]
@andriantolie 
`docker logs -f eosio` 
<img width="1445" alt="screen shot 2018-07-25 at 12 15 52 pm" src="https://user-images.githubusercontent.com/25816656/43191842-b1422716-9004-11e8-8ae6-732dac9ca3af.png">


#### cleos command

<img width="984" alt="screen shot 2018-07-25 at 12 18 25 pm" src="https://user-images.githubusercontent.com/25816656/43191909-d7bc827e-9004-11e8-95a5-7209011a122e.png">

**Comment by Naberator** [comment]
Hi @liderako , I am dealing with the same issue. did you find any leads to a solution?

**Comment by liderako** [comment]
hi @Naberator, I didn't find solution(

**Comment by Naberator** [comment]
Hi @liderako , I changed a few things in docker-compose.yml and it worked. 
    expose:
      - "8888"
was set to 8899 for some reason.

Good luck!

**Comment by Frankonly** [comment]
Hi @Naberator , how did you change the docker-compose.yml?

**Comment by Frankonly** [comment]
Use "docker exec -it eosio bash" and try curl in the container. Maybe port 8888 has been use by other software.

**Comment by Stathismi** [comment]
have you found a solution to that? 

I have the same issue, i have tried to run nodeos in another port, i have tried to run it with --http-validate-host false, as this is the default on the documentation here : https://developers.eos.io/eosio-nodeos/docs/docker-quickstart#section-check-nodeos-endpoints

cleos get info  : WORKS
BUT 
curl http://localhost:8888/v1/chain/get_info : DOESN'T WORK

**Comment by liderako** [comment]
Has solved a problem so.
```
curl http://$(docker-machine ip default):7777/v1/chain/get_info
```
