### ISSUE TITLE
Cannot run nodeos in the background.

### ISSUE THREAD

**Issue by bluabaleno** [EOSIO/eos#4831]
I used `nodeos &`. Nodeos starts up just fine and produces blocks, but I cannot type in any commands, not even Ctrl+C stops nodeos.

Running EOSIO 1.10.0

Update: commands do work, but the block produced msgs keep interrupting.

**Comment by heifner** [comment]
I recommend you read up on standard Linux background jobs. You might start with this:

https://unix.stackexchange.com/questions/74520/can-i-redirect-output-to-a-log-file-and-background-a-process-at-the-same-time

**Comment by lazaridiscom** [comment]
@bluabaleno , if you're too lazy to lookup for a solution, just open a 2nd terminal window.
