### ISSUE TITLE
Calling Cleos from Anywhere

### ISSUE THREAD

**Issue by raymondfx** [EOSIO/eos#4841]
I would like to call Cleos from anywhere, how do I go about it?
Anybody...

**Comment by jgiszczak** [comment]
After `sudo make install` in your build directory, you'll need to modify your environment to use cleos from anywhere.

`export PATH=$PATH:/usr/local/eosio/bin/`

To make the PATH change permanent you can add it to your ~/.profile

`echo 'PATH=$PATH:/usr/local/eosio/bin/' >> ~/.profile`

Note that this will no longer be required in a future release, as the install path will be changing back to `/usr/local/bin` and the previous behavior will apply, where `cleos` was available by default on installation on most Linux distributions.

**Comment by raymondfx** [comment]
Thanks it worked.
