### ISSUE TITLE
Updateauth Owner Permission 

### ISSUE THREAD

**Issue by StarryJapanNight** [EOSIO/eos#4852]
It is possible to change the owner/active permission key of an account to another account name (not key). For example:

Account: user1
Permissions:
Owner: user2@owner
Active: user1@active KEY

It is also possible to change the user1 owner permission to:

Account: user1
Permissions:
Owner: user1@owner
Active: user1@active KEY

Who now owns this account? user1 has the active key but is now unable to authorize an updateauth to change the owner key?!

**Comment by andriantolie** [comment]
This is desirable, for example:
Case 1: take a look at `eosio`, its permission is passed to `eosio.prods`
Case 2: you want to lock the account, so nobody can update the contract
