### ISSUE TITLE
code: 3050003, name: "eosio_assert_message_exception"

### ISSUE THREAD

**Issue by SpadeRoy** [EOSIO/eos#4858]
when i push transaction to node by http rpc, return the error:

`{"error": "http://10.140.0.12:8888/v1/chain/push_transaction: status code=500, body={\"code\":500,\"message\":\"Internal Service Error\",\"error\":{\"code\":3050003,\"name\":\"eosio_assert_message_exception\",\"what\":\"eosio_assert_message assertion failure\",\"details\":[]}}"}`

why?

**Comment by andriantolie** [comment]
We haven't received any follow up from this. 
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
