### ISSUE TITLE
v1.1.1 build error.

### ISSUE THREAD

**Issue by greatyaqi** [EOSIO/eos#4860]
/mnt/app/blockchain/eos/libraries/chain/webassembly/wavm.cpp:130:4:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)3; IR::ValueType ...Params = {(IR::ValueType)3}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:489:69:   required from ‘static void eosio::chain::wasm_injections::f32_unop_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 145]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f32_unop_injector<145>}]’
/mnt/app/blockchain/eos/libraries/chain/webassembly/wavm.cpp:130:4:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)1; IR::ValueType ...Params = {(IR::ValueType)4, (IR::ValueType)4}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:544:85:   required from ‘static void eosio::chain::wasm_injections::f64_relop_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 102]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f64_relop_injector<102>}]’
/mnt/app/blockchain/eos/libraries/chain/webassembly/wavm.cpp:130:4:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)1; IR::ValueType ...Params = {(IR::ValueType)3, (IR::ValueType)3}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:503:85:   required from ‘static void eosio::chain::wasm_injections::f32_relop_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 96]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f32_relop_injector<96>}]’
/mnt/app/blockchain/eos/libraries/chain/webassembly/wavm.cpp:130:4:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
In file included from /mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_interface_private.hpp:7:0,
                 from /mnt/app/blockchain/eos/libraries/chain/wasm_interface.cpp:10:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)2; IR::ValueType ...Params = {(IR::ValueType)4}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:597:69:   required from ‘static void eosio::chain::wasm_injections::f64_trunc_i64_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 177]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f64_trunc_i64_injector<177>}]’
/mnt/app/blockchain/eos/libraries/chain/wasm_interface.cpp:1921:3:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for ( int i=0; i < module.exports.size(); i++ ) {
                            ~~^~~~~~~~~~~~~~~~~~~~~~~
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)2; IR::ValueType ...Params = {(IR::ValueType)3}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:571:69:   required from ‘static void eosio::chain::wasm_injections::f32_trunc_i64_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 175]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f32_trunc_i64_injector<175>}]’
/mnt/app/blockchain/eos/libraries/chain/wasm_interface.cpp:1921:3:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)1; IR::ValueType ...Params = {(IR::ValueType)4}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:584:69:   required from ‘static void eosio::chain::wasm_injections::f64_trunc_i32_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 171]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f64_trunc_i32_injector<171>}]’
/mnt/app/blockchain/eos/libraries/chain/wasm_interface.cpp:1921:3:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)1; IR::ValueType ...Params = {(IR::ValueType)3}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:558:69:   required from ‘static void eosio::chain::wasm_injections::f32_trunc_i32_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 169]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f32_trunc_i32_injector<169>}]’
/mnt/app/blockchain/eos/libraries/chain/wasm_interface.cpp:1921:3:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)4; IR::ValueType ...Params = {(IR::ValueType)4, (IR::ValueType)4}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:516:85:   required from ‘static void eosio::chain::wasm_injections::f64_binop_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 166]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f64_binop_injector<166>}]’
/mnt/app/blockchain/eos/libraries/chain/wasm_interface.cpp:1921:3:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)4; IR::ValueType ...Params = {(IR::ValueType)4}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:530:69:   required from ‘static void eosio::chain::wasm_injections::f64_unop_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 159]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f64_unop_injector<159>}]’
/mnt/app/blockchain/eos/libraries/chain/wasm_interface.cpp:1921:3:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)3; IR::ValueType ...Params = {(IR::ValueType)3, (IR::ValueType)3}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:475:85:   required from ‘static void eosio::chain::wasm_injections::f32_binop_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 152]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f32_binop_injector<152>}]’
/mnt/app/blockchain/eos/libraries/chain/wasm_interface.cpp:1921:3:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)3; IR::ValueType ...Params = {(IR::ValueType)3}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:489:69:   required from ‘static void eosio::chain::wasm_injections::f32_unop_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 145]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f32_unop_injector<145>}]’
/mnt/app/blockchain/eos/libraries/chain/wasm_interface.cpp:1921:3:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)1; IR::ValueType ...Params = {(IR::ValueType)4, (IR::ValueType)4}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:544:85:   required from ‘static void eosio::chain::wasm_injections::f64_relop_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 102]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f64_relop_injector<102>}]’
/mnt/app/blockchain/eos/libraries/chain/wasm_interface.cpp:1921:3:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp: In instantiation of ‘static void eosio::chain::wasm_injections::injector_utils::add_import(IR::Module&, const char*, int32_t&) [with IR::ResultType Result = (IR::ResultType)1; IR::ValueType ...Params = {(IR::ValueType)3, (IR::ValueType)3}; int32_t = int]’:
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:503:85:   required from ‘static void eosio::chain::wasm_injections::f32_relop_injector<Opcode>::accept(eosio::chain::wasm_ops::instr*, eosio::chain::wasm_ops::visitor_arg&) [with short unsigned int Opcode = 96]’
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_binary_ops.hpp:566:7:   required from ‘void eosio::chain::wasm_ops::instr_base<Mutators>::visit(eosio::chain::wasm_ops::visitor_arg&&) [with Mutators = {eosio::chain::wasm_injections::f32_relop_injector<96>}]’
/mnt/app/blockchain/eos/libraries/chain/wasm_interface.cpp:1921:3:   required from here
/mnt/app/blockchain/eos/libraries/chain/include/eosio/chain/wasm_eosio_injection.hpp:81:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
make[1]: *** [CMakeFiles/Makefile2:1873: libraries/chain/CMakeFiles/eosio_chain.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

I have deleted the source code again,run eos_build.sh,still have this problem,CentOS 7.4

**Comment by Ampakinetic** [comment]
I get a similar error, also v1.1.1, and with 4 CPUs and 16Gb RAM:

`
/root/opt/boost/include/boost/test/tools/old/impl.hpp: In instantiation of âboost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl(const Left&, const Right&) [with Left = long unsigned int; Right = int]â:
/root/opt/boost/include/boost/test/tools/old/impl.hpp:130:26:   required from âboost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl_frwd::call_impl(const Left&, const Right&, mpl_::false_) const [with Left = long unsigned int; Right = int; mpl_::false_ = mpl_::bool_<false>]â
/root/opt/boost/include/boost/test/tools/old/impl.hpp:145:56:   required from âboost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl_frwd::operator()(const Left&, const Right&) const [with Left = long unsigned int; Right = int]â
/root/opt/boost/include/boost/test/tools/old/impl.hpp:92:1:   required from âbool boost::test_tools::tt_detail::check_frwd(Pred, const boost::unit_test::lazy_ostream&, boost::unit_test::const_string, std::size_t, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, const Arg0&, const char*, const Arg1&, const char*) [with Pred = boost::test_tools::tt_detail::equal_impl_frwd; Arg0 = long unsigned int; Arg1 = int; boost::unit_test::const_string = boost::unit_test::basic_cstring<const char>; std::size_t = long unsigned int]â
/root/eos/unittests/wasm_tests.cpp:101:7:   required from here
/root/opt/boost/include/boost/test/tools/old/impl.hpp:107:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     return left == right;
            ~~~~~^~~~~~~~
[ 98%] Building CXX object programs/cleos/CMakeFiles/cleos.dir/help_text.cpp.o
[ 98%] Linking CXX executable cleos
[ 98%] Built target cleos
[ 98%] Linking CXX executable unit_test
[ 98%] Built target unit_test
make: *** [Makefile:163: all] Error 2

        >>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.
`

**Comment by jgiszczak** [comment]
Neither pasted snippet contains the actual error that caused the builds to fail.  Compiling Boost unfortunately produces many (presumably) benign warnings about signed/unsigned mismatches which conceal the real error.  Please find an actual compiler error in your build logs and paste that.

**Comment by Ampakinetic** [comment]
Ok I think I got the root error this time:

```
In file included from /root/opt/boost/include/boost/test/test_tools.hpp:46:0,
                 from /root/opt/boost/include/boost/test/unit_test.hpp:18,
                 from /root/eos/tests/wallet_tests.cpp:11:
/root/opt/boost/include/boost/test/tools/old/impl.hpp: In instantiation of âboost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl(const Left&, const Right&) [with Left = int; Right = long unsigned int]â:
/root/opt/boost/include/boost/test/tools/old/impl.hpp:130:26:   required from âboost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl_frwd::call_impl(const Left&, const Right&, mpl_::false_) const [with Left = int; Right = long unsigned int; mpl_::false_ = mpl_::bool_<false>]â
/root/opt/boost/include/boost/test/tools/old/impl.hpp:145:56:   required from âboost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl_frwd::operator()(const Left&, const Right&) const [with Left = int; Right = long unsigned int]â
/root/opt/boost/include/boost/test/tools/old/impl.hpp:92:1:   required from âbool boost::test_tools::tt_detail::check_frwd(Pred, const boost::unit_test::lazy_ostream&, boost::unit_test::const_string, std::size_t, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, const Arg0&, const char*, const Arg1&, const char*) [with Pred = boost::test_tools::tt_detail::equal_impl_frwd; Arg0 = int; Arg1 = long unsigned int; boost::unit_test::const_string = boost::unit_test::basic_cstring<const char>; std::size_t = long unsigned int]â
/root/eos/tests/wallet_tests.cpp:38:4:   required from here
/root/opt/boost/include/boost/test/tools/old/impl.hpp:107:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     return left == right;
            ~~~~~^~~~~~~~
/root/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp: In member function âvoid eosio::mongo_db_plugin_impl::_process_accepted_transaction(const transaction_metadata_ptr&)â:
/root/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:759:31: error: âclass mongocxx::v_noabi::bulk_writeâ has no member named âexecuteâ
             if( !bulk_actions.execute() ) {
                               ^~~~~~~
/root/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp: In member function âvoid eosio::mongo_db_plugin_impl::_process_irreversible_block(const block_state_ptr&)â:
/root/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:960:20: error: âclass mongocxx::v_noabi::bulk_writeâ has no member named âexecuteâ
          if( !bulk.execute()) {
                    ^~~~~~~
/root/eos/plugins/net_plugin/net_plugin.cpp: In member function âvoid eosio::connection::blk_send_branch()â:
/root/eos/plugins/net_plugin/net_plugin.cpp:869:16: warning: variable âlib_numâ set but not used [-Wunused-but-set-variable]
       uint32_t lib_num;
                ^~~~~~~
make[2]: *** [plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/build.make:63: plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/mongo_db_plugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6020: plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:163: all] Error 2
```

**Comment by MessyComposer** [comment]
I'm getting the following error:
```
   File or directory /usr/local/include/libmongoc-1.0 referenced by variable MONGOC_INCLUDE_DIRS does not exist!
```
So basically the build script is skipping mongoDB C driver installation

**Comment by matthewdarwin** [comment]
Maybe check https://github.com/EOSIO/eos/issues/4714

solution: docker pull eosio/builder:latest

**Comment by Ampakinetic** [comment]
Thanks, I saw that but I'm not using docker, this is straight from a source build.

**Comment by greatyaqi** [comment]
I failed to compile for the first time, and then I did not delete the build folder. The second compile succeeded.I don't know why the compilation was successful.

**Comment by Ampakinetic** [comment]
Still the same after another build and without deleting the build folder (I'm using the build script BTW).

**Comment by greatyaqi** [comment]
@Ampakinetic   Upload the compilation log so that the problem can be described more clearly

**Comment by Ampakinetic** [comment]
Any further ideas on what I can try to resolve this please?

**Comment by jgiszczak** [comment]
The mongocxx version found at `/usr/local/lib64/libmongocxx-static.a` is not the required version.  The build script attempts to download and build the required version automatically.  It examines your installed version first.  There appears to be a bug in that code.  Assuming you're in Ubuntu, edit `eos/scripts/eosio_build_ubuntu.sh` and change line 292 from `if [ "${maj}" -gt 3 ]; then` to `if [ "${maj}" -lt 3 ]; then`.  Then run `eosio_build.sh` again.  If it starts compiling libmongocxx for you, we'll know, and that apparent defect will need to be fixed.

**Comment by Ampakinetic** [comment]
Thank you very much!  I was using Centos 7, so I edited the centos script instead.  The first time I ran it, I made the change as you'd suggested, but that didn't seem to make a difference.  Then I commented out the conditional statements to make sure the driver was going to be installed no matter what.  This fixed the build error and now I'm up and running and syncing properly :)
