### ISSUE TITLE
mainnet peer connect closed connection

### ISSUE THREAD

**Issue by seoMyeongseok** [EOSIO/eos#4861]
I did the following work.

api verification: http://api.eosnewyork.io/v1/chain/get_info
Check bp: http://bp.eosnewyork.io/bp.json
Check p2p_endpoint: "p2p_endpoint": "node1.eosnewyork.io:6987"

Modify config.ini
# eosnewyorkio: BR, primary
p2p-peer-address = node1.eosnewyork.io:6987

$ nodeos --data-dir $ DIRECTORY --config-dir $ DATE
nodeos started.

The same error occurs.

onnection
2538981ms thread-0   net_plugin.cpp:2190           operator()           ] Peer mainnet-eos.wancloud.cloud:55576 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer peer2.eosthu.com:8080 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer mainnet.eoseco.com:10010 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer peering2.mainnet.eosasia.one:80 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer p2p.meet.one:9876 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer node1.eosamericas.com:9876 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer p2p.mainnet.eospace.io:88 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer p2p.eosdetroit.io:3018 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer eos.staked.us:9870 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer node.eosmeso.io:9876 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer m.eosvibes.io:9876 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer eos-seed-de.privex.io:9876 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer api.eosuk.io:12000 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer p2p.eosio.cr:1976 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer mainnet.eosarabia.org:3571 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer eu1.eosdac.io:49876 closed connection
2538982ms thread-0   net_plugin.cpp:2190           operator()           ] Peer node1.eosnewyork.io:6987 closed connection
2540450ms thread-0   net_plugin.cpp:2190           operator()           ] Peer eosbp.buildteam.io:8532 closed connection
2541100ms thread-0   net_plugin.cpp:2190           operator()           ] Peer fullnode.eoslaomao.com:443 closed connectio

**Comment by jgiszczak** [comment]
Public seed peers on mainnet frequently reach their simultaneous connection limit and no longer accept new connections.  Peers which consistently close connections should be removed from your `config.ini`.
