### ISSUE TITLE
Deleting Accounts

### ISSUE THREAD

**Issue by raymondfx** [EOSIO/eos#4862]
Hello, Is there away of deleting accounts, I have a a few accounts I would want to remove from my localhost 

```
cleos get accounts EOS7ijWCBmoXBi3CgtK7DJxentZZeTkeUnaSDvyro9dq7Sd1C3dC4
{
  "account_names": [
    "eosio.msig",
    "eosio.token",
    "exchange",
    "hello1",
    "hello1.code",
    "tester",
    "user"
  ]
```
}

**Comment by WendySanarwanto** [comment]
@raymondfx Hey , why you closed it ? I was about asking same question here. Is there any way to delete an account ?

**Comment by tbfleming** [comment]
There isn’t.

**Comment by raymondfx** [comment]
Hey @WendySanarwanto  I closed it because in Blockchain the records are permanent and irreversible

**Comment by WendySanarwanto** [comment]
That makes sense. Is there anyway to disable an account such make it to be inactive and inaccessible ? Many thanks in advance.

**Comment by jgiszczak** [comment]
@WendySanarwanto You can nullify an account's keys.  This makes the account provably inactive and inaccessible.  The account stays inactive unless and until a privileged account intervenes to reestablish keys, which is also visible.  Use these commands to disable an account:
```bash
$ cleos push action <account_name> updateauth '{"account": "<account_name>", "permission": "owner", "parent": "", "auth": {"threshold": 1, "keys": [], "waits": [], "accounts": [{"weight": 1, "permission": {"actor": "<account_name>", "permission": "active"}}]}}' -p <account_name>@owner
$ cleos push action <account_name> updateauth '{"account": "<account_name>", "permission": "active", "parent": "owner", "auth": {"threshold": 1, "keys": [], "waits": [], "accounts": [{"weight": 1, "permission": {"actor": "<account_name>", "permission": "active"}}]}}' -p <account_name>@active
```
This works by setting "keys" to `[]`.  An account with no keys can't validate the signature for any transaction.

**Comment by WendySanarwanto** [comment]
@jgiszczak Thank you for your reply, mate. This is very helpful to my case 👍
