### ISSUE TITLE
Error code list requirement

### ISSUE THREAD

**Issue by Errance** [EOSIO/eos#4863]
Could we have a list like a "error code document"?

Cuz the API document is not complete there are so many missed part.....

**Comment by jgiszczak** [comment]
Documentation updates are ongoing.  Until then, the list of error codes that can be generated by the chain can be found in the [source code](https://github.com/EOSIO/eos/blob/40a207695bd55d654ff5ee0f60232704865e7d65/libraries/chain/include/eosio/chain/exceptions.hpp#L71).
