### ISSUE TITLE
Cannot cancel large multisig proposal

### ISSUE THREAD

**Issue by k26dr** [EOSIO/eos#4869]
I have a large multisig proposal here which consumes 140KB of RAM:

https://eosflare.io/tx/76e48cc8ce944a540b4a0af8b7fa35fa2be118f3c469ca1fa39c3be60739abc7

I'm trying to cancel it, but I can't because the transaction is taking too long. My command and errors are below:

```
cleos multisig cancel libertyblock 1dot1dotzero libertyblock

Error 3080006: Transaction took too long
Error Details:
deadline exceeded
pending console output: 
```

I figure if it can get created within the deadline it should be able to be deleted within the deadline. Any reason it can't?

**Comment by k26dr** [comment]
I have tried against a couple other API nodes as well just in case my node was being slow, but no luck

**Comment by taokayan** [comment]
If you're one of the producers, you can try to maximize your CPU frequency then push it on your own node.

**Comment by taokayan** [comment]
Closed this as no further reply. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
