### ISSUE TITLE
Tic-Tac-Toe Smart Contract---in the move action Generate an error  "Error 3015014: Pack data exception"

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#4873]
![image](https://user-images.githubusercontent.com/11773000/43240130-98e91e7c-90c7-11e8-8819-c1d02f6725a8.png)
the tic_tac_toe.cpp has no error, but only move have "Error 3015014: Pack data exception"

**Comment by amActiveHello** [comment]
There  is because that the row and column parameters  are  not corresponding
![image](https://user-images.githubusercontent.com/11773000/43244200-796a73d8-90dc-11e8-865f-b247e91109c3.png)

**Comment by andriantolie** [comment]
Thanks for the input!
Seems like the Play section in https://developers.eos.io/eosio-cpp/docs/tic-tac-toe-tutorial was still following tic-tac-toe v1.0. The documentation is updated now.
