### ISSUE TITLE
question about -- undelegatebw

### ISSUE THREAD

**Issue by jooyyy** [EOSIO/eos#4874]
To undelegate the resource which is delegated by self is normal, but when i want to undelegate the resource which i got from another account, i get failed. At same time, the payer who delegate resource to other account can not get back EOS either.

**Comment by andriantolie** [comment]
When you delegate the bandwidth, do you use `--transfer` option?

**Comment by andriantolie** [comment]
We haven't received any follow up from this. 
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
