### ISSUE TITLE
Cannot query any txs of an account by using /v1/history/get_actions

### ISSUE THREAD

**Issue by ppLorins** [EOSIO/eos#4876]
Hi all : 
       I'm new to eos . 
       I followed the steps indicated from [here](https://developers.eos.io/eosio-nodeos/docs/overview-1) , and successfully running the container . But when using  [the querying API](https://developers.eos.io/eosio-nodeos/reference#get_actions-1) for history txs of some certain accounts , I cannot get anything:
  
   request url:  `https://api.eosio.cr/v1/history/get_actions `
   request method: POST
   request body : 
```json
{"account_name":"eosio","pos":1,"offset":2} 
```

  response :  
```json
{"actions":[],"last_irreversible_block":7820506}
```

  I've tried several accounts , none of them can be retrived for actions , I can hardly believe that they are all empty.
 And the reason why I was using https://api.eosio.cr as the endpoint is my own nodeos service seemed couldn't get finished downloading the entire blocks from EOS network in the next few days :  By now, there are approximately 7.8M blocks and my container only finished downloading 328K out of them ,which already cost more than 24 hours.

 So , what's the right way to query history txs of an account , by using Nodeos ?
 Thanks a lot.

**Comment by andriantolie** [comment]
It's the right way, however, in order for you to be able to query the actions, the node that you contacted need to you has `filter-on=` enabled in his config.ini so you can query the actions related to that filter.

Looking for the above situation, it's very likely that the node hosted in https://api.eosio.cr doesn't have `filter-on=` enabled in its config.ini. So either you can ask the node host to enable it or you set up your own local node that enables the filter.

**Comment by ppLorins** [comment]
@andriantolie  I found the explaination in my nodeos's `config.ini` file:
> Track actions which match receiver:action:actor. Actor may be blank to include all. Receiver and Action may not be blank. (eosio::history_plugin)

Seems that the third-party service don't have a reason to provide a querying serive for your account .
One have to download the whole block chains of EOS to do this . Then another problem comes : **How to accelerate the downloading speed** ? My container only donwloaded 42225 blocks in 6 hours , then I need 48 days to finish that , that's impractical. My bandwidth is over 10MB/s , that's obviously not the cause. I doubt it's the application's problem .

  Can you give some suggestions ? What I want to do is just query my account's history txs . 
  Thanks a lot.

**Comment by andriantolie** [comment]
Did you try with version larger than v1.1? v1.1. introduces faster syncing https://github.com/EOSIO/eos/releases/tag/v1.1.0 so it should be much faster to sync. 

You could also try to sync with another node. It could also be that the node that you are syncing with has low bandwidth or too busy with other tasks.

**Comment by shalomz** [comment]
You can achieve that by running `nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --filter-on="*"`.

**Comment by ppLorins** [comment]
@shalomz  Got. Thanks.

**Comment by yqzzj** [comment]
@andriantolie     The log show: --filter-on * enabled. This can fill shared_mem, causing nodeos to stop.
And my nodeos was stop at 3470123 block.
My server is 8 kernel, 16 g ram.
Do I need to improve the configuration?

**Comment by andriantolie** [comment]
You need to increase your shared memory size. The default value in your config.ini won't be enough for the mainnet
`chain-state-db-size-mb = 1024`

Remember that there are 100million trx in the mainnet now and you are trying to index all of them, so you need to have enough space for the transactions

Please also be aware also that when you set the chain-state-db-size higher than your maximum memory, it will affect the performance

**Comment by spartucus** [comment]
In my env, if the `chain-state-db-size-md` higher than valid memory, when nodeos start, it exit with `process killed` message. 

And be aware, you should not set `chain-state-db-size-md` just as big as valid memory, if your memory run out, nodeos crash with dirty flag.  That said, if you have 16G memory, you could set 10240 for safety. 

see https://github.com/EOSIO/eos/pull/4666#issuecomment-406995867

**Comment by yqzzj** [comment]
My config.ini:
chain-state-db-size-mb = 8192
And free info:
root@eos:/var/lib/docker/volumes/nodeos-data-volume/_data# free
              total        used        free      shared  buff/cache   available
Mem:       16431804      177384      456492        3540    15797928    15657900

Is there a configuration problem?
@andriantolie  Thanks.

**Comment by andriantolie** [comment]
Hmm, considering you are using `filter-on=*` the above chain-state-db-size-mb seems low. There are 100 million trxs in the blockchain. Assuming a transaction is 500 bytes (the actual size should be higher and varies), it will cost you around 50 GB to index 100 million trxs. Not counting the fact that chain-state-db-size-mb is also used for the contract table (I don't know know how much is the actual usage of RAM now but it can as big as the amount of bought RAM). If you don't have that much memory and you just want to index the transaction, I think you can use the mongo db plugin which indexes the transaction in your mongo db instead.

**Comment by yqzzj** [comment]
@andriantolie I start nodeos with "--delete-all-blocks --mongodb-wipe --mongodb-uri mongodb://mongo:27017/EOS" and not using filter-on in docker.
Now the block synchronization is very slow and when I use "cleos get transaction xxxx", the command line returns:
Error 3040011: The transaction can not be found
Is this normal？

**Comment by jgiszczak** [comment]
The failure of `get transaction` is expected.  cleos can no longer retrieve transactions from nodeos using that API since you're no longer using the history plugin.  Instead, you should be querying mongodb.

We're still looking in to why block synchronization is so slow.

**Comment by villesundell** [comment]
I am/was encountering the same issue, for me it helped to set: "mongodb-queue-size = 4096" in my config.ini. I will continue experimenting, and will report back here :slightly_smiling_face:

**Comment by villesundell** [comment]
Update: It took about 4 days to sync with 1.1 nodeos and mongo. Eventually it got synced, and played well with the mainnet. For some reason the sync speed eventually increased a lot

**Comment by MarcelBlockchain** [comment]
Probably because of the bnet plugin using websockets
