### ISSUE TITLE
wast/wasm files are generated differently between eosio-s2wasm and eosiocpp

### ISSUE THREAD

**Issue by alienzin** [EOSIO/eos#4877]
#### Background
I'm developing contracts on MacOS and want to publish `contract code hash` when releasing contract source code on github.

For example, if I want to build `hello` contract, there are 2 ways.

### Using build script
<pre>
cd build/contracts/hello
make hello
cleos set contract hello.code ../hello
cleos get code hello.code
</pre>
Then I get code hash as following.
`code hash: e20f3bb294373b642a311d64e3193252526f80a8f0bf568038d8342403f535f1`

### Using eosiocpp
<pre>
cd contracts/hello
eosiocpp -o hello.wast hello.cpp
cleos set contract hello.code ../hello
cleos get code hello.code
</pre>
Now I get code hash as following.
`code hash: 1d0070ffc528f1268ad1f6c5ba998245811318bdcfd8827432d56e24c69a476c`

Those hello.wast and hello.wasm are generated differently so the code hashes are different.

Are there any possibilities that eosiocpp generates same wast/wasm files as those from build script?

**Comment by halsaphi** [comment]
Please refer to latest eosio.cdt, code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
