### ISSUE TITLE
multisig propose  that requires eosio authority,which was executed successfully but did not take effect!

### ISSUE THREAD

**Issue by wangyilin1987** [EOSIO/eos#4878]
`cleos get account eosio.prods`
`active     3:    1 bitfinexeos1@active, 1 gzb.eosadmin@active, 1 wyl.eosadmin@active, 1 xzt.eosadmin@active`

i try this,all executed successfully,but eosio did not receive the 0.5 transfer, why, and this is right way to use eosio permissions?or how use eosio  permissions?
`cleos multisig propose test '[{"actor": "gzb.eosadmin", "permission": "active"},{"actor": "wyl.eosadmin", "permission": "active"},{"actor": "xzt.eosadmin", "permission": "active"}]' '[{"actor": "eosio.prods", "permission": "active"}]' eosio.token transfer '{"from":"eosio","to":"eoswangyilin","quantity":"0.5000 EOS","memo":"test eosio pow"}' wyl.eosadmin`
`cleos multisig approve wyl.eosadmin test '{"actor": "gzb.eosadmin", "permission": "active"}' -p gzb.eosadmin@active`
`cleos multisig approve wyl.eosadmin test '{"actor": "wyl.eosadmin", "permission": "active"}' -p wyl.eosadmin@active`
`cleos multisig approve wyl.eosadmin test '{"actor": "xzt.eosadmin", "permission": "active"}' -p xzt.eosadmin@active`
`cleos multisig exec wyl.eosadmin test wyl.eosadmin -p wyl.eosadmin`

**Comment by andriantolie** [comment]
It should be like this:
```
cleos multisig propose test '[{"actor": "gzb.eosadmin", "permission": "active"},{"actor": "wyl.eosadmin", "permission": "active"},{"actor": "xzt.eosadmin", "permission": "active"}]' '[{"actor": "eosio", "permission": "active"}]' eosio.token transfer '{"from":"eosio","to":"eoswangyilin","quantity":"0.5000 EOS","memo":"test eosio pow"}' wyl.eosadmin
```
Don't use eosio.prods@active as the tx_permission because the transfer operation is supposed to be satisfied by eosio@active (which when translated later on can be satisfied by eosio.prods@active and then translated again later on can be satisfied by the producers' active key)
