### ISSUE TITLE
Integer literal is too large to be represented in any integer type

### ISSUE THREAD

**Issue by skostic9242** [EOSIO/eos#4879]
Hi,

lt seems that I can not save 128bit integers (actually compile fails with error from title). Even if I save small number in db in uint128_t field, and I copy saved value (for example 0xffa11f4b000000000000000000000000) and I try to assign it with uint128_t tmp = 0xffa11f4b000000000000000000000000 it doesn't compile. Any ideas? 

Thanks in advance

**Comment by taokayan** [comment]
uint128_t field = 0xffa11f4b;
field <<= 96;
