### ISSUE TITLE
eosio_build.sh  ERROR

### ISSUE THREAD

**Issue by liderako** [EOSIO/eos#4880]
run last version eos

`$ sh eosio_build.sh`

#### Return
```sh
$ eosio_build.sh: 33: eosio_build.sh: Bad substitution
$ eosio_build.sh: 43: eosio_build.sh: Syntax error: "(" unexpected
```

**Comment by liderako** [comment]
maybe, need use to command bash ` bash eosio_build.sh` or `./eosio_build.sh`. I'll check now.

**Comment by liderako** [comment]
@mariam-crissi yep, need use to command bash  `eosio_build.sh` or `./eosio_build.sh`

**Comment by mariam-crissi** [comment]
@liderako  I have got another issue while setting up.

                    	Beginning build version: 1.2
	                Fri Jul 27 07:19:02 UTC 2018
	                User: maria
	                 git head id: 75635168e743c3e65bb6345a1eaedd905581e6b0
	                 Current branch: master

	                    ARCHITECTURE: Linux
                           ./eosio_build.sh: line 219: /home/maria/Documents/EOS: No such file or directory

	                   Error occurred while trying to remove old installation!
