### ISSUE TITLE
different cpu time usage on different machine

### ISSUE THREAD

**Issue by liukunyu** [EOSIO/eos#4882]
'push same trx to different node cost different CPU resource'

then how to apply_block with this transaction in different node ? maybe it will lead to hard branching?

the cpu usag of my EOS account updated by which node cpu calculation?

**Comment by andriantolie** [comment]
Your final cpu usage will be determined by the producer who produces the block where your transaction is included in.

**Comment by jgiszczak** [comment]
Hard forking is prevented by producing nodes being comparable in CPU capacities and by allowing a small amount of overrun when verifying blocks vs initially creating blocks.
