### ISSUE TITLE
[PROJECT] Missing Team-Overview

### ISSUE THREAD

**Issue by lazaridiscom** [EOSIO/eos#4888]
Where can I find a team-overview?

I am mainly interested to identify the role of  `jgiszczak`, in order to prepare a formal complaint because of an unjustified locking of a critical issue (#4814) which had an ongoing discussion of community members.

**Comment by yunhui0501** [comment]
申诉

**Comment by ChristianDunst** [comment]
We have taken the necessary steps internally and thank you for bringing this to our attention

Thank you for your continued interest in eosio and your valuable feedback.

**Comment by lazaridiscom** [comment]
@ChristianDunst , the thing is that you close issues too fast (see #4839), even this issue here was closed too fast, because the Team-Overview is still missing.

Don't you agree that a Team-Overview must be provided, for transparency reasons?
