### ISSUE TITLE
why add config-dir data-dir/ when run ./nodeos

### ISSUE THREAD

**Issue by wypsanity** [EOSIO/eos#4889]
192769ms thread-0   chain_plugin.cpp:209          plugin_initialize    ] initializing chain plugin
192783ms thread-0   block_log.cpp:123             open                 ] Log is nonempty
192783ms thread-0   block_log.cpp:141             open                 ] Index is nonempty
192793ms thread-0   http_plugin.cpp:343           plugin_initialize    ] configured http to listen on 127.0.0.1:
8888
192793ms thread-0   net_plugin.cpp:2948           plugin_initialize    ] Initialize net plugin
192793ms thread-0   net_plugin.cpp:2972           plugin_initialize    ] host: 0.0.0.0 port: 9876
192793ms thread-0   net_plugin.cpp:3044           plugin_initialize    ] my node_id is 8fb87f9b17942d5fdc899fb06
d128fd7b74dbcf7b00dd0ed8f34ccf552aa9ede
192793ms thread-0   main.cpp:104                  main                 ] nodeos version 3c6134c6
192793ms thread-0   main.cpp:105                  main                 ] eosio root is /root/.local/share
192793ms thread-0   chain_plugin.cpp:450          plugin_startup       ] starting chain in read/write mode
192793ms thread-0   chain_plugin.cpp:455          plugin_startup       ] Blockchain started; head block is #7257
0, genesis timestamp is 2018-06-01T12:00:00.000
192793ms thread-0   http_plugin.cpp:394           plugin_startup       ] start listening for http requests
192794ms thread-0   net_plugin.cpp:3056           plugin_startup       ] starting listener, max clients is 25
192794ms thread-0   producer_plugin.cpp:580       plugin_startup       ] producer plugin:  plugin_startup() begi
n
192798ms thread-0   producer_plugin.cpp:607       plugin_startup       ] producer plugin:  plugin_startup() end

sir,This is not add --config-dir data-dir,If i add --config-dir data-dir,The chain will come out block。why?How do I need to configure it?

**Comment by jgiszczak** [comment]
The `--config-dir` contains the `config.ini` file for the process and the genesis.json file for the chain.  If you move those two files to the defined data directory, `nodeos` will operate exactly the same as it did when the config-dir was different from the data-dir.  If you define `--config-dir` as your data directory without moving those files, `nodeos` will generate new, default versions of both files, which may not match your original files.  If the the independent config-dir version of genesis.json does not match the default genesis.json, loading the blocks from the existing data-dir will fail.

**Comment by wypsanity** [comment]
thanks very much.The default dir is ~/.local...
