### ISSUE TITLE
eosio.token - Why is it possible that the table of an account is empty even it has a positive balance?

### ISSUE THREAD

**Issue by mochunhei** [EOSIO/eos#4893]
I came across a strange account that has a positive EOS balance, but the "accounts" table is empty (This account is not mine, it is just a random account I came across):
![image](https://user-images.githubusercontent.com/19904072/43301131-da2f733a-9195-11e8-99c7-579fcc609cfa.png)

Why is it possible that the table of an account is empty even it has a positive balance?

Note:
- I used the same commands for another account, and the result is normal:
![image](https://user-images.githubusercontent.com/19904072/43301211-46bfa7fe-9196-11e8-8f6c-d865afaa67fb.png)
- I tried to use eosjs to getTableRows() for the account (111111111121), and the returned value is still empty.
- I added the account (111111111121) to greymass, and it can show the balance correctly.

**Comment by alienzin** [comment]
cleos recognizes `scope` as uint64 of base32 encoded string if the `scope` contains numeric characters only.

So you can get accounts table of account ("111111111121") in following way.
<pre>
cleos -u https://nodes.get-scatter.com get table eosio.token 595056260442244112 accounts
</pre>

Likewise, following 2 commands are same.
<pre>
cleos -u https://nodes.get-scatter.com get table eosio.token bitfinexeos1 accounts
cleos -u https://nodes.get-scatter.com get table eosio.token 4301702136998473744 accounts
</pre>

#### Suggestion to block.one
It seems that cleos needs to be enhanced to distinguish uint64 of base32 encoded string and original string using double quotation marks ("")
e.g. to get accounts table of account ("111111111121"),
<pre>
cleos get table eosio.token "111111111121" accounts
</pre>

**Comment by heifner** [comment]
You can query like this:
`./cleos --url https://api.eosnewyork.io:443 get table eosio.token " 111111111121" accounts`

We added a `--key-type` for index perhaps we should add a `--scope-type`

**Comment by heifner** [comment]
Note that "trick" works for any account, for example:
`./cleos --url https://api.eosnewyork.io:443 get table eosio.token " bitfinexeos1" accounts`
also works.

**Comment by alienzin** [comment]
@heifner `--scope-type` would be good.
