### ISSUE TITLE
cleos get actions pos offset----cleos get actions tokenxchange 1 0

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#4894]
![image](https://user-images.githubusercontent.com/11773000/43303759-df35ecac-91a3-11e8-936b-91e52b2664f2.png)
in the  tutorial when 
![image](https://user-images.githubusercontent.com/11773000/43303802-0c42bcca-91a4-11e8-8b68-b1e94c5e41a1.png)
while result is
![image](https://user-images.githubusercontent.com/11773000/43303828-2b7072ea-91a4-11e8-953d-9e346fafd529.png)

**Comment by dixia** [comment]
hi @amActiveHello please check our developer portal for the tutorials on EOSIO. it is a bit unclear which tutorial you are referring
