### ISSUE TITLE
when execute “cleos push transaction”，generate an "Error 3200006: invalid http request"error 

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#4897]
![image](https://user-images.githubusercontent.com/11773000/43311530-4f8f13f2-91bd-11e8-9a49-2c5dfad04640.png)
when execute “cleos push transaction”，generate an "Error 3200006: invalid http request"error

**Comment by jgiszczak** [comment]
Judging by the name of the json file you're trying to use, you're trying to upload a contract to the chain.  Use `cleos --print-request set code <account> <contract-dir>` to see the format of the JSON required to do so.  The contents of the file you are using is substantially incomplete.
