### ISSUE TITLE
when i run "cleos --url http://localhost:8888 get info" ,occures Error 3200006: invalid http request，but when i "ping localhost" ,it's ok . Also when i excute "cleos --url http://127.0.0.1:8888 get info"",it is ok.

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#4899]
1、when i run "cleos --url http://localhost:8888 get info" ,occures Error 3200006: invalid http request
![image](https://user-images.githubusercontent.com/11773000/43317359-19d80252-91cf-11e8-8ed0-2bfe3a777727.png)
2、but when i "ping localhost" ,it's ok .
![image](https://user-images.githubusercontent.com/11773000/43317379-2d7f97fc-91cf-11e8-84f8-24a397dc1baa.png)
3、when i execute "ping localhost",it's ok.
![image](https://user-images.githubusercontent.com/11773000/43317431-552940f0-91cf-11e8-80b3-11cd2ceb467b.png)

**Comment by alienzin** [comment]
Check if http-validate-host = 0 (or false) in config.ini

**Comment by amActiveHello** [comment]
now, then i modify "http-validate-host = 0" ,it's ok.thank you.
