### ISSUE TITLE
nodeos failing to initialize: 

### ISSUE THREAD

**Issue by christola** [EOSIO/eos#4902]
2018-07-27T17:57:27.014 thread-0   chain_plugin.cpp:271          plugin_initialize    ] initializing chain plugin
2018-07-27T17:57:27.078 thread-0   chain_plugin.cpp:580          plugin_initialize    ] 13 St13runtime_error: database dirty flag set
rethrow database dirty flag set:
    {"what":"database dirty flag set"}
    thread-0  chain_plugin.cpp:580 plugin_initialize

**Comment by christola** [comment]
any help? trying to create account. anytime i try to run nodeos thats what i get

**Comment by christola** [comment]
plugins are added to config.ini

**Comment by jgiszczak** [comment]
For a local testnet, simply add `--delete-all-blocks` to your `nodeos` command line, once.  Be sure to shut down `nodeos` gracefully to avoid this problem.  If you're using Docker, that requires adding a longer shutdown timer to the Docker container.  The default of 10 seconds is typically not long enough.  Outside of Docker, be sure to terminate `nodeos` only with Ctrl-C in the controlling terminal, kill -15, or kill -2.
