### ISSUE TITLE
Fix getTransaction

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#4903]
In most cases the transaction has made it into a block and been processed by the history plugin before the python script calls getTransaction on the node, but it can fail sometimes, particularly when transaction is sent to one node and then getTransaction called on another node.
Need to add a flag to make a second pass if the first attempt to retrieve the transaction fails.

**Comment by andriantolie** [comment]
PR #4905 is merged, I'm closing this issue
