### ISSUE TITLE
cleos system newaccount error!

### ISSUE THREAD

**Issue by wypsanity** [EOSIO/eos#4909]
./cleos system newaccount --stake-net "0.0000 SYS" --s
take-cpu "0.0000 SYS" --buy-ram-kbytes 8 eosio xiaoxiaopeng EOS7kVxD5WaUo6TfB7g3oziyh3ttSwuMxqWQpZCLyh2eS7Y5kCYuf E
OS6NRhuH1BH3zaTrnsA4vMo59z7yWyVYKksxgbLYR5h2cGmgrB83
Error 3050000: action exception

nodeos console:
3441965ms thread-0   http_plugin.cpp:468           handle_exception     ] FC Exception encountered while process
ing chain.abi_json_to_bin
3441965ms thread-0   http_plugin.cpp:469           handle_exception     ] Exception Details: 3050000 action_vali
date_exception: action exception
Unknown action buyrambytes in contract eosio
    {"action":"buyrambytes","contract":"eosio"}
    thread-0  chain_plugin.cpp:1109 abi_json_to_bin

    {"params.code":"eosio","params.action":"buyrambytes","params.args":{"payer":"eosio","receiver":"xiaoxiaopeng","bytes":8192}}
    thread-0  chain_plugin.cpp:1119 abi_json_to_bin

i'm loaded eosio.system contract in this Local test.but throw this error.I am confused,please help me.sir.

**Comment by wypsanity** [comment]
cleos get code eosio.system
code hash: 2967cf8a34175f80d72d0cb4301740a1875700d615a60bcd3a78da270d0e2d9d

**Comment by andriantolie** [comment]
Can you share your `cleos get abi eosio` here. Seems to me like you haven't uploaded the eosio.system contract to eosio account properly

**Comment by wypsanity** [comment]
cleos system newaccount eosio --transfer xiaoxiaopeng EOS7kVxD5WaUo6TfB7g3oziyh3ttSwuMxqWQpZCLyh2eS7Y5kCYuf  EOS6NRhuH1BH3zaTrnsA4vMo59z7yWyVYKksxgbLYR5h2cGmgrB83 --
stake-net "000.0000 SYS" --stake-cpu "000.0000 SYS" --buy-ram-kbytes 8
983901ms thread-0   main.cpp:429                  create_action        ] result: {"binargs":"0000000000ea3055c0a
6aad4b84e8deb00200000"} arg: {"code":"eosio","action":"buyrambytes","args":{"payer":"eosio","receiver":"xiaoxiao
peng","bytes":8192}}
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: must purchase a positive amount

The nodeos
983911ms thread-0   wasm_interface.cpp:929        eosio_assert         ] message: must purchase a positive amoun
t
983912ms thread-0   http_plugin.cpp:468           handle_exception     ] FC Exception encountered while processi
ng chain.push_transaction
983912ms thread-0   http_plugin.cpp:469           handle_exception     ] Exception Details: 3050003 eosio_assert
_message_exception: eosio_assert_message assertion failure
assertion failure with message: must purchase a positive amount
    {"s":"must purchase a positive amount"}
    thread-0  wasm_interface.cpp:930 eosio_assert

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:62 exec_one

**Comment by andriantolie** [comment]
So I guess the original problem of this issue has been solved and you encountered a new problem that you post in the comment section?

**Comment by wypsanity** [comment]
I have posted the latest one. I saw that you have a response, so I am here to ask.

**Comment by wypsanity** [comment]
https://github.com/EOSIO/eos/issues/4928 @andriantolie    This is my new post comment, please take a look.
