### ISSUE TITLE
chain_controller::validate_tapos failed when sending transactions.

### ISSUE THREAD

**Issue by learnforpractice** [EOSIO/eos#491]
1401228ms thread-0   chain_controller.cpp:398      _generate_block      ] The transaction was {"refBlockNum":2827,"refBlockPrefix":971425546,"expiration":"2017-09-25T02:24:58","scope":["currency","inita"],"readscope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"currency","permission":"active"}],"data":"00000079b822651d000000008040934b8203000000000000"}],"signatures":["1f408d018fd5afc1cc7c00aec52d950df281ebfce75d8ee59b4f43ec4e68de5fce1b2aa23b2209660f100b79c503d5f8d8b914f00d543e469b748d17e45ff2b99b"]}
1401229ms thread-0   chain_controller.cpp:395      _generate_block      ] Transaction was not processed while generating block due to {"code":3030000,"name":"transaction_exception","message":"transaction validation exception","stack":[{"context":{"level":"error","file":"chain_controller.cpp","line":870,"method":"validate_tapos","hostname":"","thread_name":"thread-0","timestamp":"2017-09-25T02:23:21"},"format":"Transaction's reference block did not match. Is this transaction from a different fork?","data":{"tapos_summary":{"block_id":"0000000000000000000000000000000000000000000000000000000000000000"}}},{"context":{"level":"warn","file":"chain_controller.hpp","line":319,"method":"validate_transaction","hostname":"","thread_name":"thread-0","timestamp":"2017-09-25T02:23:21"},"format":"","data":{"trx":{"refBlockNum":2827,"refBlockPrefix":971425546,"expiration":"2017-09-25T02:24:58","scope":["currency","inita"],"readscope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"currency","permission":"active"}],"data":"00000079b822651d000000008040934b8303000000000000"}],"signatures":["1f5d99e7d08895e73ae3f26a43c6d6f8fdce1b7ce22498cb71c2097bd6383cf9334e479d0b32249abc972cfc7bd22edffd36922c0ece6bfaa148ad71fc586ad440"]}}},{"context":{"level":"warn","file":"chain_controller.cpp","line":979,"method":"apply_transaction","hostname":"","thread_name":"thread-0","timestamp":"2017-09-25T02:23:21"},"format":"","data":{"trx":{"refBlockNum":2827,"refBlockPrefix":971425546,"expiration":"2017-09-25T02:24:58","scope":["currency","inita"],"readscope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"currency","permission":"active"}],"data":"00000079b822651d000000008040934b8303000000000000"}],"signatures":["1f5d99e7d08895e73ae3f26a43c6d6f8fdce1b7ce22498cb71c2097bd6383cf9334e479d0b32249abc972cfc7bd22edffd36922c0ece6bfaa148ad71fc586ad440"]}}}]}

**Comment by learnforpractice** [comment]
I have looked into the code. Sounds  like it was caused by the following two objects do not update in the same time .
dynamic_global_property_object
block_summary_object

Something wrong with block producer?

**Comment by learnforpractice** [comment]
first threw a duplicate transaction exception in validate_uniqueness and then validate_tapos threw a exception too.

1242011ms thread-0   chain_controller.cpp:395      _generate_block      ] Transaction was not processed while generating block due to {"code":3030011,"name":"tx_duplicate","message":"duplicate transaction","stack":[{"context":{"level":"error","file":"chain_controller.cpp","line":839,"method":"validate_uniqueness","hostname":"","thread_name":"thread-0","timestamp":"2017-09-25T09:20:42"},"format":"Transaction is not unique","data":{}},{"context":{"level":"warn","file":"chain_controller.hpp","line":319,"method":"validate_transaction","hostname":"","thread_name":"thread-0","timestamp":"2017-09-25T09:20:42"},"format":"","data":{"trx":{"refBlockNum":7039,"refBlockPrefix":3767977222,"expiration":"2017-09-25T09:22:16","scope":["currency","inita"],"readscope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"currency","permission":"active"}],"data":"00000079b822651d000000008040934b9602000000000000"}],"signatures":["1f0e0b63aeafa47b2573704b3b62a07e3dc32c01de6cfd1be0b779a8a66ce4054113571098724dcfb23848d61300e7c4d14ce2c56822af6963e72476de34e5baf6"]}}},{"context":{"level":"warn","file":"chain_controller.cpp","line":997,"method":"apply_transaction","hostname":"","thread_name":"thread-0","timestamp":"2017-09-25T09:20:42"},"format":"","data":{"trx":{"refBlockNum":7039,"refBlockPrefix":3767977222,"expiration":"2017-09-25T09:22:16","scope":["currency","inita"],"readscope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"currency","permission":"active"}],"data":"00000079b822651d000000008040934b9602000000000000"}],"signatures":["1f0e0b63aeafa47b2573704b3b62a07e3dc32c01de6cfd1be0b779a8a66ce4054113571098724dcfb23848d61300e7c4d14ce2c56822af6963e72476de34e5baf6"]}}}]}
1242012ms thread-0   chain_controller.cpp:398      _generate_block      ] The transaction was {"refBlockNum":7039,"refBlockPrefix":3767977222,"expiration":"2017-09-25T09:22:16","scope":["currency","inita"],"readscope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"currency","permission":"active"}],"data":"00000079b822651d000000008040934b9602000000000000"}],"signatures":["1f0e0b63aeafa47b2573704b3b62a07e3dc32c01de6cfd1be0b779a8a66ce4054113571098724dcfb23848d61300e7c4d14ce2c56822af6963e72476de34e5baf6"]}
1242013ms thread-0   chain_controller.cpp:881      validate_tapos       ] trx.refBlockNum 7040: block_id._hash[0]: 0 trx.refBlockPrefix: 2874117022 block_id._hash[1]: 0
1242013ms thread-0   chain_controller.cpp:395      _generate_block      ] Transaction was not processed while generating block due to {"code":3030000,"name":"transaction_exception","message":"transaction validation exception","stack":[{"context":{"level":"error","file":"chain_controller.cpp","line":888,"method":"validate_tapos","hostname":"","thread_name":"thread-0","timestamp":"2017-09-25T09:20:42"},"format":"Transaction's reference block did not match. Is this transaction from a different fork?","data":{"tapos_summary":{"block_id":"0000000000000000000000000000000000000000000000000000000000000000"}}},{"context":{"level":"warn","file":"chain_controller.hpp","line":319,"method":"validate_transaction","hostname":"","thread_name":"thread-0","timestamp":"2017-09-25T09:20:42"},"format":"","data":{"trx":{"refBlockNum":7040,"refBlockPrefix":2874117022,"expiration":"2017-09-25T09:22:19","scope":["currency","inita"],"readscope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"currency","permission":"active"}],"data":"00000079b822651d000000008040934b9802000000000000"}],"signatures":["1f2b0c5ec4f9baa37201bcac02cfdf6b8084a2844c4a99e507155ebef7fcaca1c31da8aafddc2776a4edb01a5fa48cc0e1a8b4272ad9c6d70e0f70fcfaa81d76c2"]}}},{"context":{"level":"warn","file":"chain_controller.cpp","line":997,"method":"apply_transaction","hostname":"","thread_name":"thread-0","timestamp":"2017-09-25T09:20:42"},"format":"","data":{"trx":{"refBlockNum":7040,"refBlockPrefix":2874117022,"expiration":"2017-09-25T09:22:19","scope":["currency","inita"],"readscope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"currency","permission":"active"}],"data":"00000079b822651d000000008040934b9802000000000000"}],"signatures":["1f2b0c5ec4f9baa37201bcac02cfdf6b8084a2844c4a99e507155ebef7fcaca1c31da8aafddc2776a4edb01a5fa48cc0e1a8b4272ad9c6d70e0f70fcfaa81d76c2"]}}}]}
1242013ms thread-0   chain_controller.cpp:398      _generate_block      ] The transaction was {"refBlockNum":7040,"refBlockPrefix":2874117022,"expiration":"2017-09-25T09:22:19","scope":["currency","inita"],"readscope":[],"messages":[{"code":"currency","type":"transfer","authorization":[{"account":"currency","permission":"active"}],"data":"00000079b822651d000000008040934b9802000000000000"}],"signatures":["1f2b0c5ec4f9baa37201bcac02cfdf6b8084a2844c4a99e507155ebef7fcaca1c31da8aafddc2776a4edb01a5fa48cc0e1a8b4272ad9c6d70e0f70fcfaa81d76c2"]}

**Comment by learnforpractice** [comment]
close it since everybody are at hard work and it's it is not easy to reproduce I can't solve this problem alone. I will post the same issue again if it still there after a few month.

**Comment by lixiaodong** [comment]
i have the same problem and i posted it.
