### ISSUE TITLE
Can't publish my smart-contract on localnet.

### ISSUE THREAD

**Issue by dev1644** [EOSIO/eos#4910]
Hi There, Today I created a basic smart-contract on local Net and then I compiled it and generates its abi. Then I tried to publish contract using "Set contract " command I got this error.
 ``
```
870444ms thread-0   http_plugin.cpp:405           handle_exception     ] FC Exception encountered while processing chain.push_transaction
870444ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 10 assert_exception: Assert Exception
!"unresolvable": `env._ZN4user5helloEy`
    {"module":"env","export":"_ZN4user5helloEy"}
    thread-0  wasm_interface.hpp:41 resolve

    {"mod_name":"env","export_name":"_ZN4user5helloEy"}
    thread-0  wasm_interface.hpp:43 resolve

    {"_pending_console_output.str()":""}
    thread-0  apply_context.cpp:62 exec_one

```
I also tried to publish contract from different accounts , but the same error was thrown.

**Comment by andriantolie** [comment]
Do you import a library outside eos/contracts/ folder in your contract?

**Comment by dev1644** [comment]
Don't know this error was pretty strange and it was showing on most of the contracts.
But today, when I tried to publish contract again , it got published without any errors.
As for now I am closing this issue.
Thanks for the support.
