### ISSUE TITLE
Building EOS

### ISSUE THREAD

**Issue by Khokavim** [EOSIO/eos#4911]
When I run : 
sh ./eosio_build.sh darwin

I get...
-- Configuring ChainBase on OS X
CMake Error at libraries/wasm-jit/Source/Runtime/CMakeLists.txt:26 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 4.0) with any of the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/users/mishael/Desktop/eos/eos/build/CMakeFiles/CMakeOutput.log".

	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.

How do I resolve this issue?

**Comment by lazaridiscom** [comment]
Here is a concrete solution:

https://github.com/EOSIO/eos/issues/43#issuecomment-407052366

More solutions within:

https://github.com/EOSIO/eos/search?q=LLVM+mac&unscoped_q=LLVM+mac&type=Issues

**Comment by lazaridiscom** [comment]
related: #4911

**Comment by lazaridiscom** [comment]
@Khokavim , did you finally solve this? (If yes, please close the issue)

**Comment by taokayan** [comment]
Closed since we have received any feedback. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
