### ISSUE TITLE
ABI generation fails with templated struct

### ISSUE THREAD

**Issue by devgg** [EOSIO/eos#4913]
I am trying to define a struct that can hold values of different types. When I use the templated version it the abi generation gives an error: `false: types can only be: vector, struct, class or a built-in type. ((anonymous)) {"type":"(anonymous)"} `.

Is this intended behaviour?

```cpp
  // this works
  struct field {
    std::string value;
  };
```
```cpp
  // this does not
  template <typename T>
  struct field {
    T value;
  };
```
```cpp
  /**
   * @abi table profile i64
   */
  struct profile {
    account_name account;
    field<std::string> first_name;
    auto primary_key() const { return account; }
    EOSLIB_SERIALIZE(profile, (account)(first_name))
  };

  typedef eosio::multi_index<N(profile), profile> profiles_idx;
```

**Comment by heifner** [comment]
ABI generation has been greatly improved and moved to the `eosio.cdt` repo.
