### ISSUE TITLE
get block 8108755 returns error "The type defined in the ABI is invalid"

### ISSUE THREAD

**Issue by systemzax** [EOSIO/eos#4915]
Block num : 8108755

Tested and reproduced against multiple nodes running version 1.1.0 and 1.1.1

Same issue when calling through cleos and through http plugin. 

```
cleos get block 8108755
Error 3015004: The type defined in the ABI is invalid
Error Details:
Failed to serialize type
```

**Comment by systemzax** [comment]
Same issue for the following blocks:
8108960
8109228
8109296
8109491

**Comment by tianyangj** [comment]
I am also getting this via eosjs connecting eosnewyork endpoint.

api < error      { message: '',
  file: 'abi_serializer.cpp',
  line_number: 235,
  method: 'validate' } https://api.eosnewyork.io/v1/chain/get_block {"block_num_or_id":8108960}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3015004,"name":"invalid_type_inside_abi","what":"The type defined in the ABI is invalid","details":[{"message":"","file":"abi_serializer.cpp","line_number":235,"method":"validate"},{"message":"","file":"abi_serializer.cpp","line_number":236,"method":"validate"},{"message":"Failed to serialize type","file":"abi_serializer.hpp","line_number":596,"method":"to_variant"}]}}

**Comment by heifner** [comment]
Can you try again:

./cleos --url https://api.eosnewyork.io get block 8108960

Worked for me.

**Comment by tianyangj** [comment]
Yes, these blocks are working for me, thanks!

**Comment by heifner** [comment]
@systemzax Is it working for you now?

**Comment by heifner** [comment]
Feel free to reopen if you are still experiencing an issue.

**Comment by systemzax** [comment]
Confirmed, working now. Thanks!

**Comment by mawenpeng** [comment]
Still get same issues with EOS v1.2.2. Any clues? @heifner 
Thanks.

`[root@bc-nodes ~]# cleos --url https://api.eosnewyork.io get block 13990004
Error 3015004: The type defined in the ABI is invalid
Error Details:
Failed to serialize type
[root@bc-nodes ~]# cleos --url https://api.eosnewyork.io get block 13990026
Error 3015004: The type defined in the ABI is invalid
Error Details:
Failed to serialize type
[root@bc-nodes ~]# cleos -u http://127.0.0.1:8888 get block 13990004
Error 3015004: The type defined in the ABI is invalid
[root@bc-nodes ~]# cleos -u http://127.0.0.1:8888 get block 13990026
Error 3015004: The type defined in the ABI is invalid`
