### ISSUE TITLE
Build Error - Ubuntu 18.04 - Boost Library Issue

### ISSUE THREAD

**Issue by brianphobos** [EOSIO/eos#4916]
**I ran into this Boost libraries error trying to run the build script on Ubuntu 18.04.  After I ran into it I tried. sudo apt-get install libboost-all-dev

That didn't solve the issue.   Should it be looking in /home/brian/opt/boost/lib instead of /home/brian/opt/boost/include?   They seem to be in the lib directory?**  
==============================================================
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: /home/brian/opt/boost/include

  The following Boost libraries could not be found:

          boost_system
          boost_chrono

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  libraries/chainbase/CMakeLists.txt:26 (FIND_PACKAGE)

-- Configuring ChainBase on Linux
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: /home/brian/opt/boost/include

  The following Boost libraries could not be found:

          boost_system
          boost_chrono

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  libraries/appbase/CMakeLists.txt:22 (find_package)

-- Configuring AppBase on Linux
-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: /usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-lgcc;-lgcc_s;-lc;-lgcc;-lgcc_s;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: /usr/local/lib/libmongocxx-static.a;/usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-lgcc;-lgcc_s;-lc;-lgcc;-lgcc_s;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread;/usr/local/lib/libmongoc-static-1.0.a;/usr/local/lib/libbson-static-1.0.a;-lgcc;-lgcc_s;-lc;-lgcc;-lgcc_s;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;rt;/usr/lib/x86_64-linux-gnu/libz.so;resolv
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Git commit revision: 40a20769
-- Git commit revision: 40a20769
-- Found Intl: /usr/include  
-- Git commit revision: 40a20769
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
-- Configuring incomplete, errors occurred!
See also "/home/brian/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/brian/eos/build/CMakeFiles/CMakeError.log".

	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.
![boost-libs](https://user-images.githubusercontent.com/40128659/43361646-466ac22c-9289-11e8-82b4-86a8e70dbc8d.png)

**Comment by lazaridiscom** [comment]
Possibly this helps: https://github.com/EOSIO/eos/issues/3406#issuecomment-392050991

**Comment by brianphobos** [comment]
@lazaridiscom You are a life saver!  That was what it was!  Thank you so much.

**Comment by lazaridiscom** [comment]
Glad to be of help.

For the case that you run into problems during the build-validation, please take a look at #4765 and #3842.

**Comment by brianphobos** [comment]
@lazaridiscom 
The only one that failed was the very last one and I couldn't really figure out why based on the other stuff.  I have tried to run it 3 times and it has failed all 3 times.   

Key already in wallet
    {}
    thread-0  wallet.cpp:160 import_key
 == Errors see above ==
 Shut down the cluster.
 Shut down the wallet.
  Killing wallet manager process 4033


0% tests passed, 1 tests failed out of 1

Label Time Summary:
long_running_tests    = 1207.16 sec*proc (1 test)

Total Test time (real) = 1212.11 sec

The following tests FAILED:
	 41 - nodeos_voting_lr_test (Failed)
Errors while running CTest

**Comment by lazaridiscom** [comment]
The good news is: I'm exactly at the same point now, with the voting_lr_test failing (but a bit exhausted, so will continue most possibly tomorrow). its possibly just a tiny detail.

Are you on a native ubuntu 18.04 installation (e.g. no Virtualization etc.) ?

**Comment by brianphobos** [comment]
@lazaridiscom 
Yeah on this setup It is native on one of my laptops.  
The weird thing is on my desktop I have almost the same setup running in Virtual box and all the tests passed.   So I'm not sure what the issue is.

**Comment by lazaridiscom** [comment]
Your desktop is running windows? The virtual ubuntu is which version and 32 or 64 bit?

Me on windows btw., using WSL ubuntu 18.04 - just now, some other tests failed on a rerun.

Most possibly its a matter of some dirt (data from previous runs not cleaned up, remaining processes etc.).

Will continue this after sleep...

**Comment by brianphobos** [comment]
No, The desktop is running OpenSuSE and then has Ubuntu 18.04 64bit in VirtualBox.

**Comment by brianphobos** [comment]
@lazaridiscom and luck getting that last test to pass?   I never figured it out and just moved on but then I realized that there are all these path issues for some reason that I didn't run into on previous builds.  

brian@ThinkPad:~/eos$ build/tools/eosiocpp -o hello.wast hello.cpp
hello.cpp:1:10: fatal error: 'eosiolib/eosio.hpp' file not found
#include <eosiolib/eosio.hpp>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

==============================

If I try to manually fix the path then another error pops up.  It is like a whack-a-mole situation.  

I tried sudo make install in the /eos/build/ directory but that didn't solve it.   Are you running into the same issue on your build?

**Comment by lazaridiscom** [comment]
nope, I'm assuming something with timeouts.

Tests and builds have quite a low priority in this project, its really mysterious. Other teams deal with upcoming build/test failures like crazy-gone dobermans...

No idea about the other error you mention. At this point, as the main issue (boost) is solved, you should close this issue here, and open other dedicated issues

**Comment by lazaridiscom** [comment]
take a look at this, re paths etc: https://github.com/EOSIO/eos/issues/4883#issuecomment-408205732

**Comment by brianphobos** [comment]
This is kind of funny but I saw that last night when I was real tired trying to figure everything out and I tried that command.  

export PATH=$PATH;/usr/local/eosio/bin

But it didn't work because there is a typo.  Instead of a semi colon ;  it should have been a colon : 

So it should be 

export PATH=$PATH:/usr/local/eosio/bin

I didn't catch that last night but that fixed my issue with the path situation!   

There was no typo in the part where he was showing it being written to .profile.   

echo 'PATH=$PATH:/usr/local/eosio/bin/' >> ~/.profile
source ~/.profile
