### ISSUE TITLE
lldb debug can't read var value (ubuntu),how to deal?? I compile  eosio with ./eosio_build.sh -o Debug

### ISSUE THREAD

**Issue by suannilian** [EOSIO/eos#4917]
2018-07-29T00:53:52.118 thread-0   http_plugin.cpp:447           add_handler          ] add api url: /v1/wallet/sign_transaction
2018-07-29T00:53:52.118 thread-0   http_plugin.cpp:447           add_handler          ] add api url: /v1/wallet/unlock
Process 2337 stopped
* thread #1, name = 'keosd', stop reason = breakpoint 1.1
    frame #0: keosd`eosio::wallet::wallet_manager::create(this=0x0000000000dfdbb0, name="\x18\xb8���) at wallet_manager.cpp:61
   58
   59  	   auto wallet_filename = dir / (name + file_ext);
   60  	//FC_ASSERT( !" wallet is already!" );
-> 61  	   if (fc::exists(wallet_filename)) {
   62  	      EOS_THROW(chain::wallet_exist_exception, "Wallet with name: '${n}' already exists at ${path}", ("n", name)("path",fc::path(wallet_filename)));
   63  	   }
   64
(lldb) po wallet_filename
error: keosd :: Class '_Vector_impl' has a base class 'std::_Vector_base<char, std::allocator<char> >::_Tp_alloc_type' which does not have a complete definition.
error: keosd :: Try compiling the source file with -fno-limit-debug-info.

(lldb)

**Comment by lazaridiscom** [comment]
Have you tried what the error-msg suggests?

`Try compiling the source file with -fno-limit-debug-info`

**Comment by andriantolie** [comment]
Have you restarted your keosd after you compile it with Debug option?

**Comment by andriantolie** [comment]
We haven't received any follow up from this. 
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
