### ISSUE TITLE
Extend message API to read variable length strings.

### ISSUE THREAD

**Issue by pavybez** [EOSIO/eos#492]
At the moment, eos::currentMessage<T> only supports reading structures with fixed length types. This should be extended to support reading structures with String types now that we support Strings in ABI and database.

**Comment by pavybez** [comment]
For example, the "String" is prefixed with length followed by data. But it is not easy to tell how many bytes represent length field. We should have utilities to unpack these.

**Comment by heifner** [comment]
variable length `string`s are supported in actions now.
