### ISSUE TITLE
v1/wallet/create issue

### ISSUE THREAD

**Issue by gittempo** [EOSIO/eos#4921]
Why do i get this error while creating wallet with http api

`curl --request POST \
  --url http://127.0.0.1:8888/v1/wallet/create`

> {
    "code": 500,
    "message": "Internal Service Error",
    "error": {
        "code": 4,
        "name": "parse_error_exception",
        "what": "Parse Error",
        "details": [
            {
                "message": "Unexpected char '119' in \"wwwwwallet21\"",
                "file": "json.cpp",
                "line_number": 437,
                "method": "variant_from_stream"
            },
            {
                "message": "",
                "file": "json.cpp",
                "line_number": 460,
                "method": "from_string"
            }
        ]
    }
}

**Comment by yashvadhvani** [comment]
Please tell us the full rpc call format so we can pass the data

**Comment by yashvadhvani** [comment]
Try this out @gittempo 

`
curl -X POST   http://127.0.0.1:9999/v1/wallet/create   -H 'Cache-Control: no-cache'   -H 'Content-Type: application/json'  -d '"mywallet"'
`
