### ISSUE TITLE
wasm contain from_iso_string of time_point display "unresolvable"

### ISSUE THREAD

**Issue by NeverLandFly** [EOSIO/eos#4922]
I'm trying to send a time string as input of an action. And I used from_iso_string in "eosiolib/time.hpp".
The compile succeded. But faild on the setting contract step. The error message is:

Exception Details: 3070000 wasm_exception: WASM Exception
env._ZN5eosio10time_point15from_iso_stringERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE unresolveable
    {"module":"env","export":"_ZN5eosio10time_point15from_iso_stringERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE"}

My code is:
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>
#include <eosiolib/time.hpp>
#include <string>

using namespace eosio;

class try_time : public eosio::contract{
    public:
        try_time(account_name self): eosio::contract(self){}

        ///@abi action
        void show(const std::string& time_str)
        {
            const time_point& current_time = time_point::from_iso_string(time_str);
            print(current_time.elapsed._count);
        }
};
EOSIO_ABI(try_time, (show))

**Comment by NeverLandFly** [comment]
Well acutally i cant find the implementation of from_iso_string in the repository.

**Comment by tbfleming** [comment]
`eosio::time_point` is a modified version of `fc::time_point`. The declaration for `from_iso_string` was accidentally left in and should be removed.

**Comment by NeverLandFly** [comment]
And which function shall I use to translate a string into a time_point struct? I tried fc::time_point and  it generated an compile error:
/usr/local/eosio/include/libc++/upstream/include/float.h:69:15: fatal error: 
      'float.h' file not found
#include_next <float.h>

**Comment by NeverLandFly** [comment]
OK I get that. Thanks.

**Comment by spartucus** [comment]
`from_iso_string` still left in `eosio::time_point` in both `eos` and `eosio.wasmsdk` reop.

**Comment by heifner** [comment]
@spartucus Can you please create an issue in eosio.wasmske repo if you have not already. Thanks.
