### ISSUE TITLE
Functions treated as duplicates only if prefix are the same.

### ISSUE THREAD

**Issue by rsivasundaram** [EOSIO/eos#4926]
Hi, I am developing a smart contract and noticed that two functions with the same prefix are treated as duplicates and returns an error:
```error: duplicate case value '14024952939320644976'```

As an example, 'select' and 'selectAuth' would get treated as the same function since 'select' matches for both.

I am not sure if this was the intended behavior, but it seems that it would be better to check against the entire name.

**Comment by taokayan** [comment]
this is because only lower case characters ('a'-'z') and numbers from 1 to 5 are allowed in a function name.

**Comment by rsivasundaram** [comment]
I have other functions written in camelcase that are still compiling. Will it only print that error on run-time?

**Comment by taokayan** [comment]
For consistency, please ensure all function names have lowercase letters and numbers from 1-5 only. Variables names don't have this limitation.
