### ISSUE TITLE
Extend db C++ API to define tables with string keys.

### ISSUE THREAD

**Issue by pavybez** [EOSIO/eos#493]
We now support storage of Strings as keys in database. But db API lacks utilities to define tables using strings as primary and secondary indices.

**Comment by pavybez** [comment]
Pull request https://github.com/EOSIO/eos/pull/501 in review.

**Comment by brianjohnson5972** [comment]
This was against the old table designe and it looks like this was initially completed  but not marked as complete.   Current string as secondary index deficiency is addressed in #2402
