### ISSUE TITLE
what does chain-state-db-size-mb mean?max size is mem size?

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#4937]
In config.ini,there is opt chain-state-db-size-mb,which max size is mem size,so if my pc's men is 8G,and chain-state-db-size-mb max size is 8G,when the state dir is above 8G ,what happened?Is there anyway to break this up limit of state dir?

**Comment by liliyongleo** [comment]
Would enable mongodb-plugin will help to reduce chain-state-db-size?

**Comment by taokayan** [comment]
chain-state-db-size-mb is the max size of the shared_memory database for storing the state. It should be configured to be less than machine memory. Configuring large size might result in memory swap and performance reduction.

**Comment by csquan** [comment]
As you say,what happened if chain-state-db-size-mb increase more than machine memory?eos crush?or not crush,but can not store new data?

**Comment by taokayan** [comment]
it will possibly causes memory swap and serious performance reduction.

**Comment by csquan** [comment]
if it happens,eos can not store data and work normally.
if set chain-state-db-size-mb less than mem size(8G),some day it increase above limit,it crush.
it is bug or there is some way to reslove it?

**Comment by jgiszczak** [comment]
For the time being, the solution is to run nodeos on a machine with more memory.  This solves the problem for quite a long time, as AMD EPYC systems are available today that can accommodate 4TB of RAM.

Note that on some platforms, with some kernel settings, nodeos will crash if the chain state exceeds available physical RAM.  It attempts to lock memory, and if that operation fails, some platforms will terminate the process.

**Comment by csquan** [comment]
As you say,if my pc's mem is low ,someday eos must be crush.
So ,that is a serious  bug in eos?

**Comment by tbfleming** [comment]
That’s not a bug, it’s just the way certain OSes with certain kernel options handle memory overconsumption. nodeos can’t change OS behavior.

**Comment by csquan** [comment]
But actually,most people's mem is about 8G,when state_db size increase above it ,eos must crush,it can not work normally at all.

**Comment by tbfleming** [comment]
Nodes handling large chains need to run on high-ram dedicated servers, not typical PCs. This is not unusual; servers exist to run jobs that PCs are poor at.

**Comment by liliyongleo** [comment]
this means that the EOS cannot support large data volume applicaiton???.... since in the end, the state_db will reach the limit......   is there any plan to swap to another DB engine? like put some data onto mongodb instead??     I agree that this is actually serious problem.... as a lot of application requires much more space than 1TB, or 4TB.

**Comment by evsward** [comment]
But even though the high-ram server, we still face the crush result once the ram used up.  Is there a solution like state data persistence in hard disk storage?

**Comment by tbfleming** [comment]
Common causes for ram exceeding 64 GB:

* Abusing filter-on. * is not intended for production use. See the Mongo plugin for an alternative.
* Storing data that contracts don’t need in rows. See demux for an alternative. See also the Mongo plugin.

Key point to remember: data can be stored in action data without causing nodeos to consume ram, as long as that data isn’t stored in rows or included by the history plugin. Both mongo and demux can safely index large data stored this way.

**Comment by sinhyeok-cp** [comment]
The history_plugin + "filter-on: *" option causes memory full problem.
Consider mongo_db_plugin + mongo db + api server.

**Comment by masterayman** [comment]
Pity it seems still not solved yet in 2022!
