### ISSUE TITLE
A serious bug in EOS, our team crashed

### ISSUE THREAD

**Issue by eosonic** [EOSIO/eos#4939]
Hi, Daniel, we are a development team from China, EOS sonic. We encountered a biggest BUG in EOS, and I'm going to describe this process.

Just last week, our team got a $1 million strategic investment, in order to support our development based on EOS CPU rent dapp, we invite finance experts to help us design the financial model of current savings, we are very hard to get the cpubank's initial capital injection, but, just this morning, we found that the Daniel will launch the CPU rent mode.This immediately brought our project to the brink of bankruptcy, as if we were the Netscape Communications Corporation, we were developing Netscape, blockone was Microsoft, you developed IE.

We understand that Daniel is a very good programmer who can develop any dapp, does that mean "please everyone get out, block will write any code, develop any dapp, we don't need any other developers"?

Is Daniel developing an EOS game?are you developing an EOS mail system?are you developing IM?Please tell us what Daniel is going to develop instead of going bankrupt overnight when we are happy.so in our opinion, this is the biggest bug of EOS.

WHY?such DAPP why not go to other developers, like [http://www.minnowbooster.com/](http://www.minnowbooster.com/).Daniel: give the developers a chance. EOS should not be a one-man arena.

**Blockone and Daniel are strong, but strong people should discipline themselves, shouldn't they?**

**Comment by lazaridiscom** [comment]
> but, just this morning, we found that the Daniel will launch the CPU rent mode.

Can you please provide a link to more information? 

> This immediately brought our project to the brink of bankruptcy


How?

(me asking out of curiosity here, as your issue seems not to affect a code-bug, but organizational flaw. If so, it would be better to find another place to discuss this.)

**Comment by lazaridiscom** [comment]
ok, i see now your problem:

> our team got a $1 million strategic investment, in order to support our development based on EOS CPU rent dapp

My comment here is:

whenever you start some development, you must do some research. Here, you should have assessed 

* how possible is it that EOS will provide EOS CPU Rent itself (kind of core-functionality)

The game is still not over for you. Your can listen better to user/market needs, and provide a better CPU rent system than block.one itself.

**Comment by eosonic** [comment]
Daniel in the telegraph group：will create market to buy and seel right to receive 30 day delegation,and he will develop the CPU rent model

we means,if Daniel is going to do a lot of "work that belongs to other developers,",so why are we developing in EOSIO?

THIS IS A SERIOUS GOVERNANCE BUG!

**Comment by eosonic** [comment]
Netscape is going to beat Microsoft?I feel desperate.

This should not be a war, because CPU leasing is not profitable.

**Comment by lazaridiscom** [comment]
See my comment above (we wrote in parallel i guess). 

> THIS IS A SERIOUS GOVERNANCE BUG!

what can i say. try to raise it here:

https://forums.eosgo.io/categories/eos-governance-economics-philosophy

Although I insist:

> whenever you start some development, you must do some research. Here, you should have assessed

   >  how possible is it that EOS will provide EOS CPU Rent itself (kind of core-functionality)

**Comment by eosonic** [comment]
Thank you for your answer. We still suggest that blockone and Daniel should be disciplined. He should not do everything. :(

**Comment by eosonic** [comment]
[https://chintai-eos.io/ one DApp for  EOS  resource rent](https://chintai-eos.io/)

Q:WILL BLOCK.ONE BE DEVELOPING A TOKEN LEASING PLATFORM? IF NOT, WHY?
A:The core mission of Block.One at this point in time will be to ensure the EOS software is ready for launch. They have confirmed they will not be developing a fully operational token leasing dApp upon launch of the platform in June.

what a pity,chintai also died.

**Comment by PhillipHamnett** [comment]
Chintai is **not**  dead. We plan to release our MVP in August.

**Comment by lazaridiscom** [comment]
> We still suggest that blockone and Daniel should be disciplined

Discipline starts by ourselves. In your case, I suggest:

* Provide an abstract
* Provide facts(!) and your arguments
* Provide a concrete (EOS governance) enhancement proposal
* Find the relevant media to publish
* Post as a person (not as an nickname "eosonic" wihtout any reference)

It looks to me that you could post this on this resource:

https://www.reddit.com/r/eos/

with a title like that:

[GOVERNANCE] Block.one Must Disclose the DApps it will Develop Itself

An example for an Abstract:

In order to keep EOS attractive for an high amount of developers, businesses (...)
(here you give your concrete example, list verifiable facts)

What should change (example) : 

The suggestion is that Block.one discloses which DApps it will produce itself(...)

-

[I'm not sure if an Enhancement Proposal Procedure exists. But in general, you can go the above described way. Note that you can close this issue by yourself if you want to go the reddit way. ]

**Comment by eosonic** [comment]
Thank you for the advice, thank you to everyone, and we will stick to it.

**Comment by ChristianDunst** [comment]
I would like to emphasize that the EOSIO blockchain is run by the community. It is the communities decision if and wether to include features and bug fixes developed by block.one, as such it is a community decision to include features written by Dan's team or the community or wether to include them at all.

**Comment by lazaridiscom** [comment]
@ChristianDunst , community-decision or not, the OP has valid points. The transparency of the EOS project is a small desastar, this repo here feels like wild-west.

See #4839 and #4888 (not only that there is not team-overview, and absolute MUST for transparency reasons, but a team-member closes the issue whilst joking).

So, "Community-Run" is at this point a theory.
