### ISSUE TITLE
Getting Unexpected value of a Boolean variable in multi index Table.

### ISSUE THREAD

**Issue by AkantYadav** [EOSIO/eos#4940]
Hi,There 
While creating a smart contract today, I have encounter a peculiar bug i.e.  I create a Multi Index Table, and initialize three Boolean variables in it and did initialize them to false. When  I run get table command the table was printed but one of the three Boolean variable had the weird garbage value instead of 0.
I am here posting the struct that I have created in my Smart Contract.
 
`  /// @abi table chal12 i64
     struct challenges
     {
         account_name to;
         account_name from;
         uint64_t noofdays;
         asset balance;
         uint64_t id=0;
         bool accepted = false;
         bool completed = false;
         bool decline = false;
         time cgt=now();
         time taccept;
        
         uint64_t primary_key() const {return id;}

         EOSLIB_SERIALIZE(challenges,(to)(from)(noofdays)(balance)(id)(accepted)(completed)(cgt)(taccept)(decline))

     };

     typedef eosio::multi_index<N(chal12), challenges> challenge_table;`

When running command get table I got the following output -:

`{
  "rows": [{
      "to": "amar1",
      "from": "test1",
      "noofdays": 5,
      "balance": "20.0000 EOS",
      "id": 0,
      "accepted": 0,
      "completed": 0,
      "decline": 244,
      "cgt": 5988348,
      "taccept": 0
    },{
      "to": "amar1",
      "from": "test1",
      "noofdays": 5,
      "balance": "20.0000 EOS",
      "id": 1,
      "accepted": 0,
      "completed": 0,
      "decline": 51,
      "cgt": 5988349,
      "taccept": 16777216
    }
  ],
  "more": false
}`

**Comment by taokayan** [comment]
Would you try to use uint8_t instead? It consumes same amount of memory.

**Comment by yashbhavsar007** [comment]
It returns 0 because eos takes 0 as false and 1 as true.

**Comment by yashbhavsar007** [comment]
You got this error because you have to arrange it in EOSLIB_SERIALIZE as you have arranged in struct 
The correct order will be 
     **EOSLIB_SERIALIZE(challenges,(to)(from)(noofdays)(balance)(id)(accepted)(completed)(decline)(cgt)(taccept))**
Try this...

**Comment by AkantYadav** [comment]
Thanks for the support , issue is solved now. Closing this.

**Comment by dapixcasey** [comment]
What was the fix? @ghost
