### ISSUE TITLE
process cleos system newaccount in batch slow

### ISSUE THREAD

**Issue by woniuxu** [EOSIO/eos#4944]
Hi all,
I have four shell script running in parallel, each executes cleos system newaccount in batch like:

>for name in $names
do
cleos system newaccount eosio --transfer $name pub_key --stake-net "1 SYS" --stake-cpu "1 SYS" --buy-ram "1 SYS"
done
>
And my testnet consists of two BP node and my eosio version is tag/1.0.7.
The number of trxs per second is about 50.

>1681502ms thread-0 producer_plugin.cpp:1073 produce_block ] Produced block 0012df26417917e2... #1236774 @ 2018-07-31T12:28:01.500 signed by accountnum11 [trxs: 23, lib: 1236758, confirmed: 0]
1682002ms thread-0 producer_plugin.cpp:1073 produce_block ] Produced block 0012df2749aa8d8d... #1236775 @ 2018-07-31T12:28:02.000 signed by accountnum11 [trxs: 26, lib: 1236758, confirmed: 0]
1682502ms thread-0 producer_plugin.cpp:1073 produce_block ] Produced block 0012df283fbf7fdb... #1236776 @ 2018-07-31T12:28:02.500 signed by accountnum11 [trxs: 24, lib: 1236758, confirmed: 0]
1683002ms thread-0 producer_plugin.cpp:1073 produce_block ] Produced block 0012df29fe7ce1c5... #1236777 @ 2018-07-31T12:28:03.000 signed by accountnum11 [trxs: 25, lib: 1236758, confirmed: 0]
1683501ms thread-0 producer_plugin.cpp:1073 produce_block ] Produced block 0012df2a028077b6... #1236778 @ 2018-07-31T12:28:03.500 signed by accountnum11 [trxs: 25, lib: 1236758, confirmed: 0]
1684002ms thread-0 producer_plugin.cpp:1073 produce_block ] Produced block 0012df2bd0542d27... #1236779 @ 2018-07-31T12:28:04.000 signed by accountnum11 [trxs: 22, lib: 1236758, confirmed: 0]
1684501ms thread-0 producer_plugin.cpp:1073 produce_block ] Produced block 0012df2c2232cb2e... #1236780 @ 2018-07-31T12:28:04.500 signed by accountnum11 [trxs: 25, lib: 1236758, confirmed: 0]
1685001ms thread-0 producer_plugin.cpp:1073 produce_block ] Produced block 0012df2dcfa089d7... #1236781 @ 2018-07-31T12:28:05.000 signed by accountnum11 [trxs: 24, lib: 1236758, confirmed: 0]
>
So, I'm curious why the number of trxs per second is so low.
Two points I can guess are:

cleos system newaccount action is complicated that it actually involves several sub-action?
Though my four scripts are running in parallel, but they all send http request to the same nodeos, and the http API performance of nodeos is relatively poor?

Am I right or are there any other reasons? Thanks.

**Comment by heifner** [comment]
Yes and yes. There is http actions with keosd,  http actions to get current block reference, http actions to convert json to binary, etc. Also as you json parsing and abi parsing. It would take a number of api nodes interacting via cleos to get anywhere capacity on your producer. cleos is in no way optimized for this kind of use.
