### ISSUE TITLE
The wast file exists and is correct, but when run "cleos set code "prompt is not found

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#4954]
![image](https://user-images.githubusercontent.com/11773000/43497827-b959e8ae-9576-11e8-8757-a6b5e813004f.png)
2、
![image](https://user-images.githubusercontent.com/11773000/43497849-c6e270ea-9576-11e8-876c-3f1ed1bb9ec5.png)

**Comment by jgiszczak** [comment]
In more recent releases, the command that takes just the parent directory name is `set contract`.  `cleos set code` now expects the full path to the WAST file itself.  The command you want is:

`cleos --print-request set contract eosio ./hello`

If there is documentation that says `set code` accepts the parent path, it needs to change.  Please paste a link.
