### ISSUE TITLE
chain-state-db-size-mb = 8192，this means that the EOS cannot support large data volume applicaiton???

### ISSUE THREAD

**Issue by liliyongleo** [EOSIO/eos#4955]
this means that the EOS cannot support large data volume applicaiton???.... since in the end, the state_db will reach the limit...... is there any plan to swap to another DB engine? e.g. put some data onto mongodb instead?? I think that this is actually very serious problem.... as a lot of application requires much more space than 8GB, 1TB, or 4TB.

As far as I know, some of the history data are also stored in state DB.

**Comment by liliyongleo** [comment]
our dapp had already reached 8GB limit... we tried to increase RAM for the nodeos, but eventually it will fill up again.

**Comment by taokayan** [comment]
```chain-state-db-size-mb``` is a configurable parameter for the size of the shared_memory. The actual limit is around 66GB in the mainnet as of now and it grows with a speed of 1KB/block. EOS can support arbitrary size of memory up to the machine limit. However since the RAM resource is limited, dapp developers need to buy RAM before they can use it. The alternative way is to store data in block logs (or memo, context free actions, etc) which doesn't consume RAM.

**Comment by csquan** [comment]
we had build a private network ,not use  mainnet ,and mem is 8G.

**Comment by csquan** [comment]
does mongodb can help solving this problem?can anyone point out.that confuse me a lot.

**Comment by liliyongleo** [comment]
taokayan, what do you mean by "The alternative way is to store data in block logs (or memo, context free actions, etc) which doesn't consume RAM.",    how can I store data in block logs instead of "state"...   
As far as I know, there are two storage tiers in blockchain, one is "state" database, the other is "block" database, or "log" database.

**Comment by evsward** [comment]
memo, context free actions, etc

**Comment by csquan** [comment]
/root/.local/share/eosio/nodeos/data/block/block.log is where to store data in disk,but how  to store date in it but not in state?

**Comment by liliyongleo** [comment]
any update, please?

**Comment by taokayan** [comment]
I guess the original question is already answered.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
