### ISSUE TITLE
Get Producers API endpoint returns inconsistent results 

### ISSUE THREAD

**Issue by fschoell** [EOSIO/eos#4956]
Problem: The `/v1/chain/get_producers` API endpoint returns inconsistent results and the number of producers returned varies greatly. 

How to reproduce (using EOS New York as example): 

API Call: `POST https://api.eosnewyork.io/v1/chain/get_producers`

Using the following parameters (set the limit to a high value to get all producers):
```
{
	"json": true,
	"limit": 500
}
```

**Result:** Try it out a couple of times and the number of producers the API returns will vary. I actually had responses varying between 65 and 95 KB.

**Comment by heifner** [comment]
get_producers has a max execute time of 10ms. It will return as many producers as it can gather in that time limit. 

```
   struct get_producers_result {
      vector<fc::variant> rows; ///< one row per item, either encoded as hex string or JSON object
      double              total_producer_vote_weight;
      string              more; ///< fill lower_bound with this value to fetch more rows
   };
```

Check `more` value to see if additional producers can be retrieved.
