### ISSUE TITLE
After starting nodes Disk IO too busy

### ISSUE THREAD

**Issue by ddzyan** [EOSIO/eos#4957]
After starting nodes, IO utilization is not super high. What causes this?
Is there a solution?

**Comment by jgiszczak** [comment]
In what scenario?  If synching to mainnet, I/O utilization will be very high until your node achieves full synchronization, after which it can still be quite high if mainnet is very busy.

**Comment by ddzyan** [comment]
Can I reduce IO by modifying the configuration information?

**Comment by jgiszczak** [comment]
There may be OS-level configuration tweaks.  There are no native `nodeos` configuration options to change the disc I/O behavior.  Wait until synchronization is complete before judging the steady state I/O.  The synchronization burden is unavoidably high&mdash;there is simply a lot of data to process and persist.
