### ISSUE TITLE
Why does EOS stay in the refund section sometimes and other times it refund automatically?

### ISSUE THREAD

**Issue by xwartz** [EOSIO/eos#4961]
I am trying to figure out if there is any reason for this. 
When I unstake EOS, it shows up on the refund section in a block explorer. 
Sometimes, the refund goes automatically to unstaked section and sometimes it just stays in the refund section even after 3 days. 
Is this completely random or is there some reason for this?

**Comment by jgiszczak** [comment]
The transfer from the refund section to the unstaked section is a deferred transaction.  As with all transactions, it is subject to expiration.  If the network is particularly busy at the time the deferral is triggered, it may expire before being incorporated into a block.

**Comment by comfyowl** [comment]
@jgiszczak I currently have this issue. 
Is there a workaround for this issue, since my tokens are associated with my Ledger Nano S account which cannot call the claim manually function?
Is there any improvement planned for this issue? A lot of other users have it.

**Comment by jgiszczak** [comment]
@comfyowl I know of no reason why an account making use of a Ledger Nano S could not initiate a manual claim.  The Nano S should sign that transaction just as it does any other.  It's just a transfer, albeit from a system account.

**Comment by comfyowl** [comment]
Thanks for the reply. This feature was added in the EOS Ledger Nano S app version 1.1
You can now manually claim your stuck EOS.
