### ISSUE TITLE
Where is the genesis inside the docker?

### ISSUE THREAD

**Issue by wypsanity** [EOSIO/eos#4962]
docker pull eosio/eos-dev
docker run --rm --name eosio -d -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev  /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false"

Where is the file of gengesis.json?

**Comment by jgiszczak** [comment]
There will be no genesis.json file in the scenario outlined here.  It will use defaults for all genesis values.  If you wish to use an existing genesis.json file, put it in `/mnt/dev/config` and specify its name to the `--genesis-json` option.  To get a copy of the default genesis.json, after running your docker command, run `docker exec -it eosio /opt/eosio/nodeos -d /mnt/dev/data --config-dir /mnt/dev/config --extract-genesis-json /mnt/dev/config/genesis.json`.
