### ISSUE TITLE
Who modified “bft_irreversible_blocknum”?

### ISSUE THREAD

**Issue by mycamphortree** [EOSIO/eos#4965]
When viewing the relevant code of BFT-DPOS, the slot function corresponding to the signal "signal<void(const chain::producer_confirmation&)> confirmed_block;" was not found.

Anyway, I am wondering when the parameter "bft_irreversible_blocknum" changed.
Please tell me which function called "controller::push_confirmation( const header_confirmation& c )"

**Comment by andriantolie** [comment]
Updating bft_irreversible_blocknum is the responsible of fork_database

**Comment by mycamphortree** [comment]
hi
   The function "push_confirmation()" is defined in controller.hpp. This function is the only entry I found that can change "bft_irreversible_blocknum" because it calls fork_db.add(), and its comment is "Call this method when a producer confirmation" Is received, this might update".
   I tried to find the entire code and didn't find a place to call the "push_confirmation()" function.
   Is the current version not using the BTF consensus?

**Comment by heifner** [comment]
The current version is not using BFT consensus.

**Comment by raymondnuaa** [comment]
In my understanding, current EOS runs the implied BFT not the realtime BFT. That is to say the block is confirmed implicitly as others produce new block base on previous ones.  Realtime BFT needs explicit confirmation which should be sent by push_confirmation. But it is not called anywhere. 

@heifner , do you know is there any plan to support the realtime BFT? Thanks!

**Comment by ziranliu** [comment]
> The current version is not using BFT consensus.

So how long is the block confirmation time now? If BFT consensus is not in use, that time to irreversibility is at least 45 seconds since it needs 15 BPs to produce blocks base on that. Is this right?

**Comment by clockworkgr** [comment]
> > The current version is not using BFT consensus.
> 
> So how long is the block confirmation time now? If BFT consensus is not in use, that time to irreversibility is at least 45 seconds since it needs 15 BPs to produce blocks base on that. Is this right?

I am not sure how EOS orders BPs but it should be at least 2/3 +1 (15) BPs confirming and at most 4/3 +1 (29) confirming.

Assuming 12 consecutive blocks at 0.5s per BP = 6s , Anywhere between 90 seconds and 174 seconds

**Comment by ziranliu** [comment]
@clockworkgr Yes, you're right. I remember it wrong. One BP keeps producing for 6s, not 3s.

What puzzles me is that if it takes 90 seconds to confirm a block, why does many cryptocurrency exchange like Huobi only need one block to admit people's EOS deposit? Without BFT, the risk of reversing a block which only one block is based on is big.
