### ISSUE TITLE
MongoDB Plugin accounts Collection Missing Smart Contract Created Accounts

### ISSUE THREAD

**Issue by deckb** [EOSIO/eos#4968]
It appears that the mongoDB plugin is missing accounts that have been created by a smart contract. For example the account [accountcreat](https://bloks.io/account/accountcreat) has a [contract](https://github.com/angelol/smart_account_creator/blob/master/smart_account_creator.cpp) that on line 80 calls `INLINE_ACTION_SENDER` for `newaccount`. Any of the accounts seen on a block explorer for [accountcreat](https://bloks.io/account/accountcreat) do not appear to show up.

**Comment by heifner** [comment]
Can you provide an example account that was created?

**Comment by deckb** [comment]
4will4meltoo

**Comment by heifner** [comment]
https://gist.github.com/heifner/f9eb752772d2b178ca7e0f0d4c1b66ac

**Comment by heifner** [comment]
If you have your own plugin you can parse `transaction_trace` for `inline_traces` actions. I'm going to give some thought to how best add this to the mongo_db_plugin.

**Comment by deckb** [comment]
That doesn't appear to be showing the accounts collection though. What fails to return is:

`db.accounts.find({"name":"4will4meltoo"})`

**Comment by heifner** [comment]
Correct. Not in accounts collection because the mongo_db_plugin currently does not parse inline actions for populating `db.accounts`

**Comment by deckb** [comment]
Oh I see. Thanks.

**Comment by heifner** [comment]
Example with #5066 

```
> db.action_traces.find({"act.data.name":"4will4meltoo"}).pretty()
{
	"_id" : ObjectId("5b694ba5f9a2f32ce1cbfb65"),
	"receipt" : {
		"receiver" : "eosio",
		"act_digest" : "2f4f333fb968a0bd320beb669d145333d9f5ae235f21c65a6e61117bded39152",
		"global_sequence" : 57693692,
		"recv_sequence" : 9002644,
		"auth_sequence" : [
			[
				"accountcreat",
				8075
			]
		],
		"code_sequence" : 7,
		"abi_sequence" : 8
	},
	"act" : {
		"account" : "eosio",
		"name" : "newaccount",
		"authorization" : [
			{
				"actor" : "accountcreat",
				"permission" : "active"
			}
		],
		"data" : {
			"creator" : "accountcreat",
			"name" : "4will4meltoo",
			"owner" : {
				"threshold" : 1,
				"keys" : [
					{
						"key" : "EOS6yFSrLnDaxYeTmMuPAxw5h8UQoyAbn8BnuTpZp3y5H4aPxxwDT",
						"weight" : 1
					}
				],
				"accounts" : [ ],
				"waits" : [ ]
			},
			"active" : {
				"threshold" : 1,
				"keys" : [
					{
						"key" : "EOS6yFSrLnDaxYeTmMuPAxw5h8UQoyAbn8BnuTpZp3y5H4aPxxwDT",
						"weight" : 1
					}
				],
				"accounts" : [ ],
				"waits" : [ ]
			}
		},
		"hex_data" : "908dba284f4d113240698e4a92181d270100000001000312336b5f342d1db7fc3635d095e7218a424545086c58102a6540ba260cea0390010000000100000001000312336b5f342d1db7fc3635d095e7218a424545086c58102a6540ba260cea039001000000"
	},
	"elapsed" : 1605,
	"cpu_usage" : 0,
	"console" : "",
	"total_cpu_usage" : 0,
	"trx_id" : "658cb0756990ff5debbe32c1ee31310dd695236f1ffd18f31e0b04e8708fa41c",
	"createdAt" : ISODate("2018-08-07T07:35:01.994Z")
}
```
