### ISSUE TITLE
eosiolib/eosio.hpp file not found

### ISSUE THREAD

**Issue by Nanofortress** [EOSIO/eos#4974]
I get this error when following the hello world tutorial at https://developers.eos.io/eosio-cpp/docs/hello-world when I tried to do: _eosiocpp -o hello.wast hello.cpp_. The system I am using is Ubuntu 16.04.5 LTS, and the eosio I am using the the most recent 1.1.1.

I have tried deleting /build and rebuilding with _./eosio_build.sh_, as well as call sudo make install in the /build folder afterwards, but they do not fix this error.

The following is the error I got:
_$ eosiocpp -o hello.wast hello.cpp
hello.cpp:1:10: fatal error: 'eosiolib/eosio.hpp' file not found
#include <eosiolib/eosio.hpp>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated._

**Comment by Nanofortress** [comment]
Someone has already opened this issue

**Comment by williamleecn** [comment]
modify eosiocpp

set "EOSIO_INSTALL_DIR" to "/usr/local/eosio"
