### ISSUE TITLE
Hello world tutorial not working for Ubuntu 16.04.5

### ISSUE THREAD

**Issue by Nanofortress** [EOSIO/eos#4975]
I get this error when following the hello world tutorial at https://developers.eos.io/eosio-cpp/docs/hello-world when I tried to do: _eosiocpp -o hello.wast hello.cpp_. The system I am using is Ubuntu 16.04.5 LTS, and the eosio I am using the the most recent 1.1.1.

I have tried deleting /build and rebuilding with _./eosio_build.sh_, as well as calling _sudo make install_ in the _/build_ folder afterwards, but they do not fix this error. I have tried every fix online and they do not work, I think this is a issue only with the newest version. I have also saw one person mentioned he has the same problem with Ubuntu 18.

The following is the error I got:
_$ eosiocpp -o hello.wast hello.cpp
hello.cpp:1:10: fatal error: 'eosiolib/eosio.hpp' file not found
#include <eosiolib/eosio.hpp>
^~~~~~~~~~~~~~~~~~~~
1 error generated._

Any thought is appreciated, thanks!

**Comment by Nanofortress** [comment]
I found an interesting fix online by user jchung00, on this post https://github.com/EOSIO/eos/issues/2265. 

So here is what I did. 
First I got a older version of the eosio with command: _git clone -b v1.0.10 https://github.com/EOSIO/eos --recursive_

Afterwards I tried all the sudo make install... and all that regular stuff but it still doesn't work.
Then I tried the fix on the post I mentioned above, which is to do:
_$sudo su
$make install
$sudo <username>_
 
Everything works like magic afterwards! I have no idea how.

Additionally the new eosio v1.1.1 which I had in another folder works as well.

Again this is not a permanent fix, any explanation is appreciated, thanks!

**Comment by Nanofortress** [comment]
Update again, the issue seems to be a environment permission issue. To simply running eosiocpp commands with root user won't result an error.

**Comment by Nanofortress** [comment]
Update again. I am not sure if this is an environment problem. For example, logging in as userA (not my real username) in Ubuntu and run _eosiocpp -o hello.wast hello.cpp_ will have the error, but if I do _sudo su userA_ (basically changing to myself) and run _eosiocpp -o hello.wast hello.cpp_ I will not get any error.

**Comment by Nanofortress** [comment]
Update, again. Doing _sudo su userA_ will solve the problem above but a new problem arises, when using cleos to create a new account it will give the following error:
_"/usr/local/bin/keosd" launched
Unable to connect to keosd, if keosd is running please kill the process and try again._

This shouldn't be happening as cleos should have no problem starting keosd, and I have no previous keosd running.

**Comment by andriantolie** [comment]
First of all, things to note here that starting from v1.1.0, eosio binaries and libraries are installed inside /usr/local/eosio instead of /usr/local now. If you are also installing v1.0.10 at the same machine, you will actually have two binaries and libraries, one inside /usr/local/eosio and one inside /usr/local.

I advise you to just stick to the latest version which is v1.1.1, `sudo ./eosio_build.sh` (this will also clean the old installation and then `cd build && sudo make install` to install it. Once you are done, export /usr/local/eosio to your PATH (export PATH=/usr/local/eosio/bin:$PATH). 
Once you have done it, your cleos/ keosd/ nodeos should be using the one from /usr/local/eosio

**Comment by lazaridiscom** [comment]
> I advise you to just stick to the latest version which is v1.1.1, sudo ./eosio_build.sh

@andriantolie , are you sure with the `sudo` here? I remember to had problems when using sudo for the build. Additionally, the manuals do not say to use `sudo` for the build step (just for the install step).

**Comment by andriantolie** [comment]
Normally you won't need `sudo`, and it's better not to use sudo when it's not needed. However, for this case, seems like he has installed the old version of eos in the same machine. If he wants to clean the old version, he will need to call it with sudo. For details check scripts/clean_old_install.sh :)

**Comment by Nanofortress** [comment]
Thanks for all the comments! I will start debugging this first thing tomorrow. 
I just want to say that I am not trying to uninstalling the old version, I am simply trying to make the tutorial work. I think this problem is caused by permissions configurations. As when I do  $ eosiocpp -o hello.wast hello.cpp, the scrip doesn't seem to be able to find the the files. It can only find the files after I did Sudo su userA. This which will cause an unexpected behavior with the eosiocpp create account function. Where it cannot start keosd on its own.

**Comment by lazaridiscom** [comment]
I remember that building with sudo created some stuff with root permissions, so later some actions needed again sudo (don't remember exactly what this was). Building again without sudo cleaned up the situation.

possibly a safer way would be:

```bash
sudo ./scripts/clean_old_install.sh
./eosio_build.sh
```

**Comment by dixia** [comment]
closed as solved
