### ISSUE TITLE
How do I know how much RAM I need to deploy a contract?

### ISSUE THREAD

**Issue by RonLino** [EOSIO/eos#4979]
Before sending a transaction to create a contract how could I determine how much RAM I need?

At the moment, when I send the transaction the system throw an exception because I don’t have enough RAM, in the exception I can see the RAM needed: ‘...has insufficient ram; needs 39574 bytes...’, but I would like to know this data beforehand.

Thanks!

**Comment by taokayan** [comment]
The memory you need is roughly the size of your compiled wasm file.

**Comment by RonLino** [comment]
Thanks taokayan, but the size of the wasm file is a lot different from the RAM that exception tells me.

To avoid other issues, the contract that I'm trying to deploy in mainnet is the "Hello contract" delivered with EOS code. The size of Hello.wasm is 3042 bytes, and the exception returns 'account XXXX has insufficient ram; needs 40055 bytes ...'

I have deployed the contract on testnet and the spent RAM was nearly 40000 bytes.

Then, How could I know this data beforehand?

**Comment by heifner** [comment]
```
const static uint32_t   setcode_ram_bytes_multiplier       = 10;     ///< multiplier on contract size to account for multiple copies and cached compilation
```
```
   int64_t new_size  = code_size * config::setcode_ram_bytes_multiplier;
```

Also the abi takes up some room, but there is no multiplier on abi size and it is stored as packed bytes, so its impacts is small.

So roughly 10 * wasm size + packed abi size.
