### ISSUE TITLE
Can a smart contract action access the transactionId?

### ISSUE THREAD

**Issue by b-flightly** [EOSIO/eos#4980]
Is it possible to find out the transactionId from within an action?  

I know I can access the block_num and a few other details using the tapos function but I did not find similar for transactionId.

**Comment by b-flightly** [comment]
Note: I did find the following in contracts/test_api/test_transaction.h that seems to work:

`void test_transaction::test_read_transaction() {
   using namespace eosio;
   checksum256 h;
   auto size = transaction_size();
   char buf[size];
   uint32_t read = read_transaction( buf, size );
   eosio_assert( size == read, "read_transaction failed");
   sha256(buf, read, &h);
   printhex( &h, sizeof(h) );
}`

I tested with an action and the printed string _seems_ to work for "cleos get transaction ...".  

I didnt know if there was another (better) way.

**Comment by taokayan** [comment]
This is not available for now. However, we'll treat it as a future enhancement.

**Comment by kingdom998** [comment]
> Note: I did find the following in contracts/test_api/test_transaction.h that seems to work:
> 
> ```
> void test_transaction::test_read_transaction() {
>    using namespace eosio;
>    checksum256 h;
>    auto size = transaction_size();
>    char buf[size];
>    uint32_t read = read_transaction( buf, size );
>    eosio_assert( size == read, "read_transaction failed");
>    sha256(buf, read, &h);
>    printhex( &h, sizeof(h) );
> }
> ```
> I tested with an action and the printed string _seems_ to work for `cleos get transaction ...`.
> 
> I didnt know if there was another (better) way.

Have you solve this problem, I also want to get transaction id offline.

**Comment by brianjohnson5972** [comment]
Created #6289 to address this
