### ISSUE TITLE
[TEST] Unify CI Tests with Local Tests

### ISSUE THREAD

**Issue by lazaridiscom** [EOSIO/eos#4984]
The auto-build via `./eosio_build.sh` suggests at its end to use `make test', which starts a cascade of tests.

The github ci ~uses a different set of tests~ launches the test in a different manner via `buildkite` (and possibly uses not the identical set of tests).

## Problem

Having different tests / launch-methods within CI and for a manual local build can introduce consistency problems (see #4927) and additional (redundant) maintenance effort.

## Solution / Goal

Unify the test-system, thus a manual local test uses the same script/tests that the github-ci-tests.

## Barriers

Achieving the above goal will most possibly introduce the necessity to rework the overall test-system.

## Similar Issues

Build-System Unification:
#4923 - Unify Docker Build-Scripts

**Comment by jgiszczak** [comment]
Users generally speaking do not have `buildkite` available on their local system.  Without it, the test systems can not be unified.  The `buildkite` configuration contains optimizations for testing in a cluster that likely aren't even relevant to most end users.  However, at its root, `buildkite` runs `ctest`, which is what `make test` runs.  Fundamentally, the tests are already unified, at the point where it's possible and it matters.

**Comment by lazaridiscom** [comment]
Once more you close an issue far too fast (#4839).

Reading your comment, It really seem that you place `buildkite` (a tool) above your users.

## Reality

* The current test-system implementation has deep flaws (and even defects)
* The team around eos ignores those flaws and defects (at the users cost, e.g. time and effort)
* The current test-system needs to be unified, in order to avoid situations like #4972.
* It matters that the test-system is near 100% identical (locally / repo)
* It is possibly to achieve near-100% unification
* It is possible to drop buildkite, if it does not allow near-100% unification

If you really think that...

>  "Fundamentally, the tests are already unified, at the point where it's possible and it matters."

then you should reassess very quickly "what is possible" and "what matters".

**Comment by NorseGaud** [comment]
What’s the current status on this?

**Comment by lazaridiscom** [comment]
This issue was closed, and thus "off-radar" of the team (which has a tendency to close issues a bit to early).
