### ISSUE TITLE
stripping dead, unlinked code

### ISSUE THREAD

**Issue by elwyos** [EOSIO/eos#4987]
When running eosiocpp on hello.cpp, if I add a function like:

```
int whatevs(){
   int x = 433242;
   return x;
}
```
It doesn't actually strip the function away, adding a few bytes.

Is there a way to strip dead code on hello.cpp? This makes it impossible to use a standard library of sorts - because I'd have to comment out individual functions or add an #ifdef before every function in the library and enabling them with #define if I want to use them

**Comment by taokayan** [comment]
This is not a something unexpected. In the C/C++ perspective, it's very difficult to tell if a function is not being used, as a function can be referenced and called in an external way. like:
```
extern void func(); // this expects func is defined somewhere else
```
This will only make the wast file a little bit larger, but it won't make you impossible to use the standard sort function. Actually, you can find ```std::sort``` is already used in the system contract ```voting.cpp```.
