### ISSUE TITLE
Error 3090003: When use the RPC interface to push_transaction

### ISSUE THREAD

**Issue by BlackWhiteBlock** [EOSIO/eos#4988]
I build a test environment to test the RPC interface, but I met the issue when I test the transfer function.
I run a nodeos on Ubuntu,and use the curl on a windows PC.

I have created  account "user1" and "user2"; and import there keys into the default wallet.
I 
Here is my process:
1.curl http://192.168.181.168:8888/v1/chain/abi_json_to_bin -d  
{
	"code": "eosio.token",
	"action": "transfer",
	"args": {
		"from": "user1",
		"to": "user2",
		"quantity": "200.0000 SYS",
		"memo": "user1 to user2 200 SYS"
	}
}
result:
{"binargs":"00000000807015d600000000007115d680841e0000000000045252560000000016757365723120746f2075736572322032303020525256"}

2.curl http://192.168.181.168:8888/v1/chain/get_info
result:
{
    "server_version": "40a20769", 
    "chain_id": "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f", 
    "head_block_num": 74002, 
    "last_irreversible_block_num": 74001, 
    "last_irreversible_block_id": "00012111923a992b2e67c6a0b60bb1b1b33fab2d191a34606761cdefdc273d7d", 
    "head_block_id": "0001211272ddd7a694c05498e90954415c1e19e03a16def9496fa280b3b18cac", 
    "head_block_time": "2018-08-02T06:49:32.000", 
    "head_block_producer": "eosio", 
    "virtual_block_cpu_limit": 200000000, 
    "virtual_block_net_limit": 1048576000, 
    "block_cpu_limit": 199900, 
    "block_net_limit": 1048576
}

3.curl http://192.168.181.168:8888/v1/chain/get_block -d "{\"block_num_or_id\":74002}"
result:
{
    "timestamp": "2018-08-02T06:49:32.000", 
    "producer": "eosio", 
    "confirmed": 0, 
    "previous": "00012111923a992b2e67c6a0b60bb1b1b33fab2d191a34606761cdefdc273d7d", 
    "transaction_mroot": "0000000000000000000000000000000000000000000000000000000000000000", 
    "action_mroot": "82a169f9307a1cd0b7b1b7dbd232337e83f4254e60cf96a1f7262fe7100dc966", 
    "schedule_version": 0, 
    "new_producers": null, 
    "header_extensions": [ ], 
    "producer_signature": "SIG_K1_KZ4vGHJiirC5spMqwUR3PGiaXZv8fE3rZC6VzJ8h2SSQc9EcKH7wskqwiKXMzBvTktGceS3R1x6WbiBkkGNnBD4qsQjjDQ", 
    "transactions": [ ], 
    "block_extensions": [ ], 
    "id": "0001211272ddd7a694c05498e90954415c1e19e03a16def9496fa280b3b18cac", 
    "block_num": 74002, 
    "ref_block_prefix": 2555691156
}

4.curl http://192.168.181.168:8888/v1/wallet/unlock -d "[\"default\", \"PW5JiSGXxpoRLYgHr3jWfVXrSbdcZL38jRWFy9Zv28R142tJrkTW1\"]"
result:
{}

5.curl http://192.168.181.168:8888/v1/chain/get_required_keys -d
{
	"transaction": {
		"ref_block_num": "74002",
		"ref_block_prefix": "2555691156",
		"expiration": "2018-08-02T07:20:32.000",
		"scope": ["user1", "user2"],
		"actions": [{
			"account": "eosio.token",
			"name": "transfer",
			"recipients": ["user1", "user2"],
			"authorization": [{
				"actor": "user1",
				"permission": "active"
			}],
			"data": "00000000807015d600000000007115d680841e0000000000045252560000000016757365723120746f2075736572322032303020525256"
		}],
		"signatures": [],
		"authorizations": []
	},
	"available_keys": ["EOS8bLquC3ByN51tDsDzTpX4Rt3GawTnd75XPpKMpDeB2fFYfbGjS", "EOS7N3i3EbYHxekd4zPnzzPee4PPw2wWBbJ6jsLAJVcZhDdwJw1Dy", "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"]
}
result:
{"required_keys":["EOS8bLquC3ByN51tDsDzTpX4Rt3GawTnd75XPpKMpDeB2fFYfbGjS"]}

6.curl http://192.168.181.168:8888/v1/wallet/sign_transaction -d
[{
		"ref_block_num": "74002",
		"ref_block_prefix": "2555691156",
		"expiration": "2018-08-02T07:20:32.000",
		"scope": ["user1", "user2"],
		"read_scope": [],
		"message": [{
			"account": "eosio.token",
			"name": "transfer",
			"authorization": [{
				"actor": "user1",
				"permission": "active"
			}],
			"data": "00000000807015d600000000007115d680841e0000000000045252560000000016757365723120746f2075736572322032303020525256"
		}],
		"signatures": []
	},
	["EOS8bLquC3ByN51tDsDzTpX4Rt3GawTnd75XPpKMpDeB2fFYfbGjS"], ""
]
result:
{
    "expiration": "2018-08-02T07:20:32", 
    "ref_block_num": 8466, 
    "ref_block_prefix": 2555691156, 
    "max_net_usage_words": 0, 
    "max_cpu_usage_ms": 0, 
    "delay_sec": 0, 
    "context_free_actions": [ ], 
    "actions": [ ], 
    "transaction_extensions": [ ], 
    "signatures": [
        "SIG_K1_K1AhigUcKkw9iQrPfdLd6iXJz3iRVTWVcTzcSQhQkrkqNa3b81vBUMjg7ZgmqGuxokjG2dQ8dSd3quXimWTRDRBVRFvw5T"
    ], 
    "context_free_data": [ ]
}

7.curl http://192.168.181.168:8888/v1/chain/push_transaction -d
{
	"compression": "none",
	"transaction": {
		"expiration": "2018-08-02T07:20:32",
		"ref_block_num": 8466,
		"ref_block_prefix": 2555691156,
		"max_net_usage_words": 0,
		"max_cpu_usage_ms": 0,
		"delay_sec": 0,
		"context_free_actions": [],
		"actions": [{
			"account": "eosio.token",
			"name": "transfer",
			"authorization": [{
				"actor": "user1",
				"permission": "active"
			}],
			"data": "00000000807015d600000000007115d680841e0000000000045252560000000016757365723120746f2075736572322032303020525256"
		}],
		"transaction_extensions": []
	},
	"signatures": ["SIG_K1_K1AhigUcKkw9iQrPfdLd6iXJz3iRVTWVcTzcSQhQkrkqNa3b81vBUMjg7ZgmqGuxokjG2dQ8dSd3quXimWTRDRBVRFvw5T"],
	"context_free_data": []
}
ERROR result:
{
	"code": 500,
	"message": "Internal Service Error",
	"error": {
		"code": 3090003,
		"name": "unsatisfied_authorization",
		"what": "Provided keys, permissions, and delays do not satisfy declared authorizations",
		"details": [{
			"message": "transaction declares authority '{\"actor\":\"user1\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys [\"EOS5tRvgFrEEKMZqWtVN5qZER5b9xcFebj5abxLDBDiJ7fGXGdv6k\"]",
			"file": "authorization_manager.cpp",
			"line_number": 411,
			"method": "check_authorization"
		}]
	}
}

**Any one know how to reslove this issue?**

**Comment by BlackWhiteBlock** [comment]
Here is the info about the user1:

cleos --wallet-url  http://192.168.181.168:9999 --url http://192.168.181.168:8888 get account user1
permissions: 
     owner     1:    1 EOS8bLquC3ByN51tDsDzTpX4Rt3GawTnd75XPpKMpDeB2fFYfbGjS
        active     1:    1 EOS8bLquC3ByN51tDsDzTpX4Rt3GawTnd75XPpKMpDeB2fFYfbGjS1 user1@eosio.code, 
memory: 
     quota:     191.6 MiB    used:     3.521 KiB  

net bandwidth: 
     staked:  100000000.0000 SYS           (total stake delegated from account to self)
     delegated:       0.0000 SYS           (total staked delegated to account from others)
     used:               446 bytes
     available:        9.155 TiB  
     limit:            9.155 TiB  

cpu bandwidth:
     staked:  100000000.0000 SYS           (total stake delegated from account to self)
     delegated:       0.0000 SYS           (total staked delegated to account from others)
     used:             1.079 ms   
     available:        533.3 hr   
     limit:            533.3 hr   

SYS balances: 
     liquid:        49990.0000 SYS
     staked:    200000000.0000 SYS
     unstaking:         0.0000 SYS
     total:     200049990.0000 SYS

producers:     <not voted>

**Comment by lyf199800** [comment]
bro,have you make it?I have the same problem now
