### ISSUE TITLE
Tables is empty in abi file generated by eosiocpp -g 

### ISSUE THREAD

**Issue by yiran-ever** [EOSIO/eos#4990]
When using eosiocpp -g to generate an abi file, the "tables" field is empty. 
version: mainnet-1.1.1
eg. eosiocpp -g eosio.token.abi eosio.token.cpp

**Comment by sangemi** [comment]
Same issue. I read the issue ttps://github.com/EOSIO/eos/issues/4186 .
And i added //@and comment
```
         //@abi table accounts
         struct account {
            asset    balance;

            uint64_t primary_key()const { return balance.symbol.name(); }
         };
```
But other error occur when I run eosiocpp -g 
```
abi_generation_exception: Unable to generate abi
false: Unable to guess index type
```

**Comment by KennyLiu25775** [comment]
![image](https://user-images.githubusercontent.com/11808716/43614460-6b519bfa-9668-11e8-95fa-b75634fac67f.png)
I tried to add the comment like above as I learned from others, but it still does not work, the tables were created but the `cleos get currency balance` still does not work

**Comment by yiran-ever** [comment]
@quocle108 It doesn't work with user-defined contract either,  eosio.token is just an example.

**Comment by yiran-ever** [comment]
I've found that the name of the struct MUST be less then 13 characters (excludes "_"), then add the @abi macro. 
Note that the table name in the @abi macro should be the same with the one in typedef.

**Comment by quocle108** [comment]
@yiran-ever I know that. what i what to get all table. Example i can get a list producers
`$ cleos -u https://nodes.get-scatter.com:443 get table eosio eosio producers 
{
  "rows": [{
      "owner": "123singapore",
      "total_votes": "7036095537958997.00000000000000000",
      "producer_key": "EOS71UbkZzuz55WNBpsEVQzkXrZAJ2XyLoQiEcS9WKwbYambhFxWb",
      "is_active": 1,
      "url": "http://eos.vote",
      "unpaid_blocks": 0,
      "last_claim_time": "1529459862000000",
      "location": 0
    },{
      "owner": "1eosbattles1",
      "total_votes": "329144938830.10693359375000000",
      "producer_key": "EOS1111111111111111111111111111111114T1Anm",
      "is_active": 0,
      "url": "http://eosbattles.com",
      "unpaid_blocks": 0,
      "last_claim_time": 0,
      "location": 643
    },{
      "owner": "1eostheworld",
      "total_votes": "7513528312168187.00000000000000000",
      "producer_key": "EOS7DtVzfmr1c5ACb7usAwyn4f39V7urk6kBWswUWCtg3H8H6CFAr",
      "is_active": 1,
      "url": "https://eostheworld.io",
      "unpaid_blocks": 0,
      "last_claim_time": 0,
      "location": 630
    },{
      "owner": "1teamcanada1",
      "total_votes": "286438200222.54486083984375000",
      "producer_key": "EOS7gBHpJMaWo8uzcXRfBAhN9yLfVTLTbH4L2xA64B5HNMnZpVuKJ",
      "is_active": 1,
      "url": "http://can-play.ca",
      "unpaid_blocks": 0,
      "last_claim_time": "1532021698000000",
      "location": 1
    },{
      "owner": "accproxsomes",
      "total_votes": "119904814521.01521301269531250",
      "producer_key": "EOS5CW54ph1oYAuQiHu3ReVKGucYZtyn5kJgsu3QAVh5FWQJ9PUga",
      "is_active": 1,
      "url": "Malta",
      "unpaid_blocks": 0,
      "last_claim_time": 0,
      "location": 0
    },{
      "owner": "acroeos12345",
      "total_votes": "76289877450180800.00000000000000000",
      "producer_key": "EOS56PyKoHXwyRkwDzr2uNhgDRioPoq5TwdN8Pm2hQGko7jrup2W5",
      "is_active": 1,
      "url": "http://www.acroeos.one",
      "unpaid_blocks": 0,
      "last_claim_time": "1533257496000000",
      "location": 410
    },{
      "owner": "activeeoscom",
      "total_votes": "359055188662674.00000000000000000",
      "producer_key": "EOS788SrVzZ3mJt3WUZkmYadjFJCisJGhZRTp85EznxEaqsARN26w",
      "is_active": 1,
      "url": "https://www.activeeos.com",
      "unpaid_blocks": 0,
      "last_claim_time": 0,
      "location": 840
    },{
      "owner": "alohaeosprod",
      "total_votes": "38962441764476592.00000000000000000",
      "producer_key": "EOS53pfXfxZ4tH3EGccdnGvBZVJsrcSf2nbCKiLLMphgaii9XxxhM",
      "is_active": 1,
      "url": "https://www.alohaeos.com",
      "unpaid_blocks": 0,
      "last_claim_time": "1533240902500000",
      "location": 840
    },{
      "owner": "argentinaeos",
      "total_votes": "219918491792858464.00000000000000000",
      "producer_key": "EOS7jq4FHrFrtCXxpRQ39dBeDMa5AjM4VaRbqBECkSa5aZnizJzrx",
      "is_active": 1,
      "url": "https://www.eosargentina.io",
      "unpaid_blocks": 5563,
      "last_claim_time": "1533225506500000",
      "location": 32
    },{
      "owner": "atticlabeosb",
      "total_votes": "117928183811468400.00000000000000000",
      "producer_key": "EOS7LqudX6Ac4woGwTF9CvQKwrJhg3H7p3pScDoXj1Ws82mMZFQqf",
      "is_active": 1,
      "url": "https://atticlab.net",
      "unpaid_blocks": 0,
      "last_claim_time": "1533287702500000",
      "location": 804
    }
  ],
  "more": true
}
`

**Comment by KennyLiu25775** [comment]
@yiran-ever hi Li Cheng, so i tried to keep the table name in the @abi the same with the one in typedef, but still unable to get the currency balance :(

here is how i changed my hpp file:
![image](https://user-images.githubusercontent.com/11808716/43666909-ac849e20-972a-11e8-97af-f44903f1ef11.png)

here is how the new generated abi table looks like: 
![image](https://user-images.githubusercontent.com/11808716/43666919-ba0a2984-972a-11e8-99f0-6dab79093b4b.png)

this is what the eosio.token default abi looks like(how should my abi table supposed to look like):
![image](https://user-images.githubusercontent.com/11808716/43666928-c66b052c-972a-11e8-8a58-2aacf560c3c8.png)

And here is the result:   :(
![image](https://user-images.githubusercontent.com/11808716/43667090-591990b4-972b-11e8-8b0f-4cfc2fed74db.png)

**Comment by yiran-ever** [comment]
@KennyLiu25775  don't know how you deployed your contract. I tried `cleos --url http://dev.cryptolions.io:38888 get abi vcctoken`, but got errors.
``

**Comment by KennyLiu25775** [comment]
@yiran-ever Hi , so did your code work? Would you mind posting a picture of how you add the @abi comment? thanks!

**Comment by yiran-ever** [comment]
as follows
`         /// @abi table accounts i64
         struct account {
            asset    balance;
            string  memo;

            uint64_t primary_key()const { return balance.symbol.name(); }
         };

         /// @abi table stat i64
         struct statt {
            asset          supply;
            asset          max_supply;
            account_name   issuer;
            string  memo;

            uint64_t primary_key()const { return supply.symbol.name(); }
         };

         typedef eosio::multi_index<N(accounts), account> accounts;
         typedef eosio::multi_index<N(stat), statt> stats;`

**Comment by yiran-ever** [comment]
`         /// @abi table accounts i64
         struct account {
            asset    balance;
            string  memo;

            uint64_t primary_key()const { return balance.symbol.name(); }
         };

         /// @abi table stat i64
         struct statt {
            asset          supply;
            asset          max_supply;
            account_name   issuer;
            string  memo;

            uint64_t primary_key()const { return supply.symbol.name(); }
         };

         typedef eosio::multi_index<N(accounts), account> accounts;
         typedef eosio::multi_index<N(stat), statt> stats;`

**Comment by yiran-ever** [comment]
![1](https://user-images.githubusercontent.com/10877876/43672170-362ce33e-97db-11e8-98c0-e2f57bd8d591.jpg)

**Comment by KennyLiu25775** [comment]
I did exactly what you did with your hpp file, but i still got error :( :(
![image](https://user-images.githubusercontent.com/11808716/43672307-265ebef8-9760-11e8-8f87-a472f65a3bf5.png)

------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/11808716/43672311-3bdae61c-9760-11e8-9f91-19fd7a7a4995.png)

**Comment by yiran-ever** [comment]
`cleos -u http://dev.cryptolions.io:38888 get abi vcctoken` still not working. Maybe you can post a picture of how you deployed the contract?

**Comment by KennyLiu25775** [comment]
Yeah sure, here was how I deployed the contract, I think i did it correctly?
![image](https://user-images.githubusercontent.com/11808716/43673171-c96db9e8-9772-11e8-8178-05789c8a2a4b.png)

**Comment by yiran-ever** [comment]
So you've made a wrong usage of the "get balance" method.
`Usage: cleos get currency balance contract account [symbol]`
the "contract" should be the account name which you deployed your contract, here is "vcchaintest3", not "vcctoken".
try `cleos -u http://dev.cryptolions.io:38888 get currency balance vcchaintest3 vcchaintest3 BBQ`

**Comment by KennyLiu25775** [comment]
@yiran-ever Thank you so much my friend. My mistake haha, problem solved!

**Comment by KennyLiu25775** [comment]
But I do think the command description is little misleading, I dont know if it is just for me but it specifically asked for the name of the contract. In this case, maybe it  should say "the account name which you deployed your contract"?
![image](https://user-images.githubusercontent.com/11808716/43678611-52921b3a-97cb-11e8-84c8-ff3a8fd2bfbd.png)
