### ISSUE TITLE
Peer addresses for mainnet

### ISSUE THREAD

**Issue by vimalbera92** [EOSIO/eos#4992]
Can anyone please let me know, from where I can find peer list to sync my mainnet node of EOS? I've tried to add peers from list available on https://eosnodes.privex.io/ but it's not working. I'm not able to sync up the nodes.

**Comment by heifner** [comment]
That list should work. What errors do you get?

**Comment by vimalbera92** [comment]
I was getting error "Bad file descriptor" which is resolved when I pass genesis.json file as a parameter.

This issue can be closed. 

Thank you,
Vimal
