### ISSUE TITLE
about txn_test_gen_plugin question

### ISSUE THREAD

**Issue by wangyilin1987** [EOSIO/eos#4994]
i run `curl --data-binary '["eosio", "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"]' http://127.0.0.1:8888/v1/txn_test_gen/create_test_accounts`
and have error:
`2018-08-02T03:37:54.325 thread-0   net_plugin.cpp:2517           operator()           ] accept txn threw  3040000 transaction_exception: Transaction exception
action's authorizing actor 'txn.test.t' does not exist
    {"account":"txn.test.t"}
    thread-0  controller.cpp:1590 validate_referenced_accounts`
I guess it's because of the parallel processing of create account transactions  and set code transactions

and i try let create_test_accounts function's "create some test accounts" and "set txn.test.t contract to hotio.token & initialize it"  on one's own,and success.
like:
`static uint64_t flag = 1;`
`if(flag == 1)
{
//create some test accounts
flag=2;
}
else if(flag == 2)
{
//set txn.test.t contract to hotio.token & initialize it
}
`
so,is i use txn_test_gen_plugin wrong way, or this is issues?

**Comment by taokayan** [comment]
This plugin is only for performance testing only. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
