### ISSUE TITLE
how to use " asset::from_string "

### ISSUE THREAD

**Issue by hama** [EOSIO/eos#4995]
i found there was a action `asset::from_string`  in eos/libraries/chain/asset.cpp , but not in eos/contracts/eosiolib/asset.hpp, you know, we cannot include any chain files in contract, so how can use this function?

**Comment by taokayan** [comment]
As this function is used in the core rather than in the contract, you can't directly include or use it. However you can copy the implementation into your contract source code if you really need it.

**Comment by hama** [comment]
i have tried, but there was an error:
fatal error: 'float.h' file not found
