### ISSUE TITLE
Intermittent issue with production get transaction

### ISSUE THREAD

**Issue by pete001** [EOSIO/eos#4996]
Yesterday (2018-08-01) we saw a period of load spikes across several BP RPC API nodes. Here is the load spike from our cluster: 

<img width="786" alt="screen shot 2018-08-02 at 11 27 24" src="https://user-images.githubusercontent.com/410428/43578577-12ec1e2a-9647-11e8-9e3d-a9bab001c2fd.png">

During this time, the `nodeos` process was pegged to 100% on the individual core. 

It was around this time that block 8,888,888 was generated. We have noticed that many RPC API nodes have no transaction history for this period. For example, all these dont work: 

```
cleos -u https://eos.greymass.com get transaction e53f2af98bf4e4902ad9056000afcfd37a4268ec75e01769840a395771ccffd1

cleos -u https://api1.eosasia.one get transaction e53f2af98bf4e4902ad9056000afcfd37a4268ec75e01769840a395771ccffd1

cleos -u https://eosapi.blockmatrix.network get transaction e53f2af98bf4e4902ad9056000afcfd37a4268ec75e01769840a395771ccffd1

cleos -u https://api.eossweden.se get transaction e53f2af98bf4e4902ad9056000afcfd37a4268ec75e01769840a395771ccffd1

cleos -u https://api.eosrio.io get transaction e53f2af98bf4e4902ad9056000afcfd37a4268ec75e01769840a395771ccffd1
```

However, it does exist on some nodes:

```
cleos -u https://eu.eosdac.io get transaction e53f2af98bf4e4902ad9056000afcfd37a4268ec75e01769840a395771ccffd1

cleos -u https://api.eosnewyork.io e53f2af98bf4e4902ad9056000afcfd37a4268ec75e01769840a395771ccffd1
```

Do you have any details on what could have caused this? Would be good to understand as we want to ensure that a consistent experience is delivered to all the dApps/explorers/etc currently using our API nodes.

**Comment by tbfleming** [comment]
If a dapp depends on `filter-on` settings, then it should be running its own node. I expect the number of BPs using `filter-on:*` to fall to 0 over time.

**Comment by pete001** [comment]
Yeah makes sense, thanks for following up on this one 👍
