### ISSUE TITLE
[PROJECT] Provide a Team-Overview with Roles

### ISSUE THREAD

**Issue by lazaridiscom** [EOSIO/eos#5003]
For the sake of transparency, a team-overview should be provided, thus the main roles are immediately visible.

| github id | role | name |
| - | - | - |
| @heifner | | |
| @bytemaster | | |
| @ChristianDunst |  | |
| @jgiszczak | | |
| @sergmetelin | | | 
| @taokayan |||
| ... | | |

https://github.com/EOSIO/eos/graphs/contributors

**Comment by tbfleming** [comment]
| github id | role | name |
| - | - | - |
| @tbfleming | closer of issues | |
