### ISSUE TITLE
code == N(debug) what meaning, Which API does it call?

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5006]
![image](https://user-images.githubusercontent.com/11773000/43622487-eedca41e-970e-11e8-9f75-162232ccd731.png)
1、code == N(debug) ，Which API does it call? I don't understand  N（debug）this method.

**Comment by taokayan** [comment]
this is to check if the value of ```action``` equals to base32 encoded value of ```debug```. So when you push an action using cleos, the account name and action name will be encoded from string to uint64_t using base32 encoding.
