### ISSUE TITLE
One more producer, chain synchronization error

### ISSUE THREAD

**Issue by wypsanity** [EOSIO/eos#5007]
I have eosio and a account producer,I want them to synchronize the production block, a producer in the eosio_test directory, his configuration is p2p-listen-endpoint = 127.0.0.1:9875, p2p-peer-address = 127.0.0.1:9876.eosio configuration is p2p- Listen-endpoint = 127.0.0.1:9876,p2p-peer-address = 127.0.0.1:9875.
run ./nodes and nodeos --genesis-json ~/eosio_test/xiaoxiaopeng/genesis.json --block-dir ~/eosio_test/xiaoxiaopeng/blocks --config-dir ~/eosio_test/xiaoxiaopeng/ --data-dir ~/eosio_test/xiaoxiaopeng/ --http-server-address 127.0.0.1:8889 --p2p-listen-endpoint 127.0.0.1:9875 --enable-stale-production --producer-name xiaoxiaopeng --private-key  '["EOS7kVxD5WaUo6TfB7g3oziyh3ttSwuMxqWQpZCLyh2eS7Y5kCYuf","5KQRmR64GmVKotNG62dBX7cpTBxnzjoui3ffo3zDvEQ6mt3Hjik" ]' --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::http_plugin --plugin eosio::history_api_plugin --p2p-peer-address 127.0.0.1:9876 command.
The following error:
```
1)No head block in fork db, perhaps we need to replay
2)915817ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from 127.0.0.1:9876: Bad file descriptor
928457ms thread-0   net_plugin.cpp:773            connection           ] accepted network connection
928457ms thread-0   net_plugin.cpp:2315           handle_message       ] Peer on a different chain. Closing connection
928458ms thread-0   net_plugin.cpp:1148           operator()           ] sent a go away message: wrong chain, closing connection to connecting client
928458ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from connecting client: Operation canceled
```

**Comment by taokayan** [comment]
I guess that producer might be on a different fork.

**Comment by jgiszczak** [comment]
You must provide ` --genesis-json ~/eosio_test/xiaoxiaopeng/genesis.json` to both nodes.  The first node without the argument will generate a default `genesis.json` when it is launched, and at the very least, its timestamp will not match that of the provided genesis file.  There may be other differences as well, which is not allowed.  The genesis files must match.
