### ISSUE TITLE
get actions accountA does only get records which send by accountA,but no records receive by accountA?

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5008]
get actions accountA does only get records which send by accountA,but no records receive by accountA?
my filter-on =eosio.token:transfer:
anyone could help?

**Comment by csquan** [comment]
does anyone could help?

**Comment by csquan** [comment]
that a serious problem,and now i can not get all history

**Comment by csquan** [comment]
none answer this?

**Comment by csquan** [comment]
filter-on =eosio.token:transfer:* can not start nodes, filter-on =eosio.token:transfer:A could filter receiver of A,but there is no possible to list all receiver.how solve this?

**Comment by jgiszczak** [comment]
To clarify, the syntax to filter all transfers to eosio.token is `filter-on =eosio.token:transfer:`.

The wildcard `*` is special-cased only for the stand-alone case.  The equivalent wildcard for action or actor is to leave the field blank.  That is, to log all actors for a given action, there must be a trailing colon with no following text, as in the example above.  To log all account activity, there must be two trailing colons: `filter-on = eosio.token::`.  To log all actions between two a receiver and an actor, leave the action blank: `filter-on =eosio.token::accounta`.

The `filter-out` option uses the same syntax.
