### ISSUE TITLE
How to know a transaction is put on chain and irreversible?

### ISSUE THREAD

**Issue by CharlesJu1** [EOSIO/eos#5010]
I setup a local testate with 2 block producing nodes and 2 full nodes. I then shut down the two block producing nodes. I issued an transaction with nodejs to one of the full node and get back the trx id. I then do a Cleos get transaction on the fullnode that I issued the transaction and get the following:

```
{
  "id": "604fb67f0e66089806d0c0a49930e0dbd023197bfb0b7227415c48fb2539ff66",
  "trx": {
    "receipt": {
      "status": "executed",
      "cpu_usage_us": 1609,
      "net_usage_words": 13,
      "trx": [
        1,{
          "signatures": [
            "SIG_K1_Kgu3fQcpZTtDZa1ZESMz5PrKGXZHYc8C6cTgfpDZH6TidgQf3UPLniK8ziLLyNJKSFDCN6s4fPEDG6zrgGc5G9hPvSxJGR"
          ],
          "compression": "none",
          "packed_context_free_data": "",
          "packed_trx": "19df635bf30bbf5f5a5e00000000010000b80a6b8095a4000000004c3799c30100000000007015d600000000a8ed32320800000000807015d600"
        }
      ]
    },
    "trx": {
      "expiration": "2018-08-03T04:50:33",
      "ref_block_num": 3059,
      "ref_block_prefix": 1582981055,
      "max_net_usage_words": 0,
      "max_cpu_usage_ms": 0,
      "delay_sec": 0,
      "context_free_actions": [],
      "actions": [{
          "account": "omes.user",
          "name": "signin",
          "authorization": [{
              "actor": "user",
              "permission": "active"
            }
          ],
          "data": {
            "user": "user1"
          },
          "hex_data": "00000000807015d6"
        }
      ],
      "transaction_extensions": [],
      "signatures": [
        "SIG_K1_Kgu3fQcpZTtDZa1ZESMz5PrKGXZHYc8C6cTgfpDZH6TidgQf3UPLniK8ziLLyNJKSFDCN6s4fPEDG6zrgGc5G9hPvSxJGR"
      ],
      "context_free_data": []
    }
  },
  "block_time": "2018-08-03T04:49:34.000",
  "block_num": 3080,
  "last_irreversible_block": 3059,
  "traces": [{
      "receipt": {
        "receiver": "omes.user",
        "act_digest": "5a9e2f1841328d8ddfcc8132ec8aa7bfeb52b6751fa5528c7584f9a486c5b922",
        "global_sequence": 3166,
        "recv_sequence": 7,
        "auth_sequence": [[
            "user",
            8
          ]
        ],
        "code_sequence": 1,
        "abi_sequence": 1
      },
      "act": {
        "account": "omes.user",
        "name": "signin",
        "authorization": [{
            "actor": "user",
            "permission": "active"
          }
        ],
        "data": {
          "user": "user1"
        },
        "hex_data": "00000000807015d6"
      },
      "elapsed": 815,
      "cpu_usage": 0,
      "console": "",
      "total_cpu_usage": 0,
      "trx_id": "604fb67f0e66089806d0c0a49930e0dbd023197bfb0b7227415c48fb2539ff66",
      "inline_traces": []
    }
  ]
}
```

It looks the transaction is executed on the fullnode and put in a block with num 3080.  
Given the fullnode is not producing blocks, why the transaction is put in a block? What conclusion can I draw for sure from the output  `"block_num": 3080`?  Also the same info is available on the other fullnode. So the block is broadcasted to the other fullnode. 

Given the above behavior, a followup question is when I call the contract action, how do I know that the transaction is put on the chain and not reversible?

**Comment by jgiszczak** [comment]
All nodes perform speculative execution of transactions (unless they're synching and haven't caught up).  A node that has become isolated from all producing nodes has no way to know that there are (or should be) newer blocks it has not seen, so if it was previously synchronized, it will continue to speculate until it reconnects and discovers it is behind.

When `last_irreversible_block > block_num`, you can be sure the transaction has been incorporated into the chain and is not reversible.

**Comment by CharlesJu1** [comment]
What is the purpose of a fullnode putting the transaction into a local block (block number 3080 in my example)? In a normal operating network, the fullnode will broadcast the block 3080 to the network and the block producer will take out the transaction out of the block and put it into a different block generated by the block producer? Is this how it works?

**Comment by heifner** [comment]
The purpose is speculative verification. Don't want to relay a bad transaction.
