### ISSUE TITLE
getting table row with secondary key?

### ISSUE THREAD

**Issue by elwyos** [EOSIO/eos#5011]
According to https://developers.eos.io/eosio-nodeos/reference#get_table_rows there are ways to find certain rows if you have the primary key (by using lower/upper bound), but is it possible to find the data through the secondary/tertiary key?

I imagine the multi_index indexers does generate an index in the actual table?

**Comment by yiran-ever** [comment]
Yea, you can getting table rows with a secondary key.
eg. search the producers by votes
`cleos get table --index 2 --key-type float64 eosio eosio producers`

**Comment by elwyos** [comment]
Ah, so it is possible to do it using cleos. However, what's the parameters if you want to do it using the REST api? Could it be that it's just missing documentation?

**Comment by jgiszczak** [comment]
The JSON data for the above request via the HTTP API is:
```
{
  "json": true,
  "code": "eosio",
  "scope": "eosio",
  "table": "producers",
  "table_key": "",
  "lower_bound": "",
  "upper_bound": "",
  "limit": 10,
  "key_type": "float64",
  "index_position": "2"
} 
```
If it can be done in `cleos`, you can find out the JSON required by adding the `--print-request` command line option.  The lack of these parameters (and all others) in the HTTP API documentation is a known defect.
