### ISSUE TITLE
no matching conversion for functional-style cast from 'const account_name'

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5012]
![image](https://user-images.githubusercontent.com/11773000/43626290-cd32fdbc-9723-11e8-81cc-78cb5c92dbff.png)
when i deploy it ：
![image](https://user-images.githubusercontent.com/11773000/43626351-167243d4-9724-11e8-8b0f-5a32d6ac0bdb.png)

**Comment by brianjohnson5972** [comment]
Using eosio::name{from} will make the error go away
