### ISSUE TITLE
no member named 'current_message' in namespace 'eosio'

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5013]
the complete debug.cpp  is as follows：
![image](https://user-images.githubusercontent.com/11773000/43626447-6cb65456-9724-11e8-8ce6-1e64aabae086.png)
eosio::current_message is 
![image](https://user-images.githubusercontent.com/11773000/43626469-86308492-9724-11e8-9ffe-c94bf7f96ea3.png)
it runs error
![image](https://user-images.githubusercontent.com/11773000/43626512-b02da4be-9724-11e8-88c4-3d0401c2d52c.png)

**Comment by jgiszczak** [comment]
The documentation is indeed obsolete.  Use `unpack_action_data<debug::foo>()` instead.  The documentation will be updated.
