### ISSUE TITLE
make install do not copy eosiolib 

### ISSUE THREAD

**Issue by oneroot001** [EOSIO/eos#5015]
in the eosio version after realase 1.1,it seems that do not copy contract libralies to the system lib by execute the command "make install"?

**Comment by oneroot001** [comment]
Yeah, eosiocpp will fail now.How to solve this? Do you remember the previous version that set the library?

**Comment by Pdsmithjp** [comment]
I haven't upgraded for a while. I just did a clean ubuntu 18.04 install and then installed EOS 1.1.2 as per the instructions. Which folder needs to be moved, and to where?

**Comment by lazaridiscom** [comment]
the, as suggested here https://github.com/EOSIO/eos/issues/4801#issuecomment-409416727, possibly you need still to export some stuff:

```bash
export PATH=/usr/local/eosio/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/eosio/lib:$LD_LIBRARY_PATH
```

if this does not work, try a reinstall:

```bash
sudo ./scripts/clean_old_install.sh
./eosio_build.sh
sudo make install
```

then export the above mention PATH/LD_LIBRARY_PATH

**Comment by Pdsmithjp** [comment]
That didn't work for me. As stated above, I have a fresh network already.

**Comment by larryk85** [comment]
The new workflow moving forward is to use [eosio.wasmsdk](https://github.com/EOSIO/eosio.wasmsdk).  This has the new compiler (toolchain), eosiolib and standard libs.

**Comment by lazaridiscom** [comment]
@larryk85 , shouldn't this be mentioned in both, the changelog and the developer-documentation?

**Comment by Pdsmithjp** [comment]
Is the eosio.wasmsdk in addition to or in place of the standard eos git? It is a very large and slow install. I am trying to figure out how to compile with it.

**Comment by lazaridiscom** [comment]
My understanding is that its additional.

**Comment by dev1644** [comment]
I am also getting this problem , and I have tried  all of the solutions before.

**Comment by Pdsmithjp** [comment]
Check my fix here. 

https://github.com/EOSIO/eosio.wasmsdk/issues/30

**Comment by oneroot001** [comment]
@Pdsmithjp it works.but when I compile "exchange" contract, it failed with errors:
./exchange.hpp:5:10: fatal error: 'exchange/market_state.hpp' file not found
#include <exchange/market_state.hpp>

**Comment by Pdsmithjp** [comment]
You need to install eosio.contracts from github. Build them using ./build.sh. Then add /eosio.contracts/build/contracts folder to your path - not the /eos/contracts or /eos/build/contracts.

**Comment by oneroot001** [comment]
then how to generate abi use eosio-cpp? @Pdsmithjp

**Comment by Pdsmithjp** [comment]
You can't! Take the old one from eosiocpp and modify it as necessary. I believe they are working on it.

**Comment by dabdevelop** [comment]
Install the eos sdk here:

https://github.com/EOSIO/eosio.wasmsdk

**Comment by dabdevelop** [comment]
Install the eos sdk here:

https://github.com/EOSIO/eosio.wasmsdk

**Comment by dabdevelop** [comment]
Install the eos sdk here:

https://github.com/EOSIO/eosio.wasmsdk

**Comment by lazaridiscom** [comment]
@MrToph , @Pdsmithjp , @oneroot001 and others:

please try this: #5133

**Comment by lazaridiscom** [comment]
try the latest 1.2.0, this should fix your issues (please close this issue if it works for you).

**Comment by halsaphi** [comment]
Please refer to latest eosio.cdt, code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
