### ISSUE TITLE
Cannot get Table: userres, delband, refunds from  System contract

### ISSUE THREAD

**Issue by quocle108** [EOSIO/eos#5016]
There are some tables in system contract cannot get by command:
Any helps, Thanks

```
$ cleos -u https://nodes.get-scatter.com:443 get table eosio eosio userres
{
  "rows": [],
  "more": false
}
```

**Comment by yiran-ever** [comment]
Usage: cleos get table [OPTIONS] contract scope table
The scope should be your account, not eosio

**Comment by quocle108** [comment]
@yiran-ever I know that. what i want to get all table. Example i can get a list producers

$ cleos -u https://nodes.get-scatter.com:443 get table eosio eosio producers
{
"rows": [{
"owner": "123singapore",
"total_votes": "7036095537958997.00000000000000000",
"producer_key": "EOS71UbkZzuz55WNBpsEVQzkXrZAJ2XyLoQiEcS9WKwbYambhFxWb",
"is_active": 1,
"url": "http://eos.vote",
"unpaid_blocks": 0,
"last_claim_time": "1529459862000000",
"location": 0
},{
"owner": "1eosbattles1",
"total_votes": "329144938830.10693359375000000",
"producer_key": "EOS1111111111111111111111111111111114T1Anm",
"is_active": 0,
"url": "http://eosbattles.com",
"unpaid_blocks": 0,
"last_claim_time": 0,
"location": 643
},{
"owner": "1eostheworld",
"total_votes": "7513528312168187.00000000000000000",
"producer_key": "EOS7DtVzfmr1c5ACb7usAwyn4f39V7urk6kBWswUWCtg3H8H6CFAr",
"is_active": 1,
"url": "https://eostheworld.io",
"unpaid_blocks": 0,
"last_claim_time": 0,
"location": 630
},{
"owner": "1teamcanada1",
"total_votes": "286438200222.54486083984375000",
"producer_key": "EOS7gBHpJMaWo8uzcXRfBAhN9yLfVTLTbH4L2xA64B5HNMnZpVuKJ",
"is_active": 1,
"url": "http://can-play.ca",
"unpaid_blocks": 0,
"last_claim_time": "1532021698000000",
"location": 1
}
"more": true
}

**Comment by yiran-ever** [comment]
Don't known what's your problem.
"producers" is a system table, doesn't belong to any user, so the scope is "eosio", a sytem account. 
But userres, delband and refunds are tables belong to a certain user, so the scope should be the user account. 
eg.`cleos -u https://nodes.get-scatter.com:443 get table eosio starteosiobp userres`

**Comment by quocle108** [comment]
Ok. I  understood what you mean.
I've check system contract again...

`user_resources_table   totals_tbl( _self, receiver ); //  only for receiver can get`

`producers_table _producers(_self,_self); //  for contract account`
