### ISSUE TITLE
Not able to create account

### ISSUE THREAD

**Issue by vimalbera92** [EOSIO/eos#5021]
I'm running non-producing nodeos and it's syncing completely fine. But now I'm not able to create account using below command.

`cleos system newaccount -x 10 --stake-net "0.1 EOS" --stake-cpu "0.1 EOS" --buy-ram-kbytes 8 --transfer creator_account_name new_account_name EOS_PUB_KEY EOS_PUB_KEY`

Using above command I'm getting below output and command line stuck there but transaction not pushed on node.

`2018-08-03T09:30:00.058 thread-0   main.cpp:438                  create_action        ] result: {"binargs":"a09853f64f983d61808d8a48a169a63b00200000"} arg: {"code":"eosio","action":"buyrambytes","args":{"payer":"creator_account_name","receiver":"new_account_name","bytes":8192}}
2018-08-03T09:30:02.500 thread-0   main.cpp:438                  create_action        ] result: {"binargs":"a09863f64f953d61808d8a48a169a63b640000000000000004454f5300000000640000000000000004454f530000000001"} arg: {"code":"eosio","action":"delegatebw","args":{"from":"creator_account_name","receiver":"new_account_name","stake_net_quantity":"0.100 EOS","stake_cpu_quantity":"0.100 EOS","transfer":true}}`

Please note that -
1. I'm using proper name instead of creator_account_name and new_account_name.
2. My node is not yet synced totally.
3. I'm running non-producing node.

Is there anything I'm missing? Please help.

Thank you,
Vimal

**Comment by jgiszczak** [comment]
Mainnet is relatively busy.  Your transaction is likely expiring before it has a chance to be incorporated into a block.  You're using `-x 10` which is substantially lower than the default expiration time.  Either omit `-x 10`, for the default expiration, or use `-x ##` with some number greater than 10 seconds and try again.

**Comment by tomasbulva** [comment]
I'm having the same issue. I've tried with -x 100 -x 1000 -x 3600 no matter what I try it's just stuck. Have you @vimalbera92 ever figure out what the issue was? 

my command: `cleos system newaccount -x 100 --stake-net "0.1000 EOS" --stake-cpu "0.1000 EOS" --buy-ram-kbytes 8 --transfer creator_account_name new_account_name new_account_pub_key new_account_pub_key`

**Comment by vimalbera92** [comment]
Nop @tomasbulva. I couldn't get around it. I tried everything I could but with no success. Please let me know if you find something.

**Comment by odarboe** [comment]
@tomasbulva  can you try increasing the amount of EOS you are staking to 1 EOS each to be given much CPU time and Network bandwidth for the transaction to pass through. Also verify the syntax documentation. I don't think --transfer is needed as far as I know.
