### ISSUE TITLE
Wrong naming requirements described for IndexName in comment

### ISSUE THREAD

**Issue by filipealonso** [EOSIO/eos#5022]
https://github.com/EOSIO/eos/blob/7412253f2e921d37e0e2a7a95065da19938366db/contracts/eosiolib/multi_index.hpp#L125

If the EOSIO naming requirements is the same for _account_name_ as it is for _IndexName_ (EOSIO base32 encoded 64-bit integer), then

> the first twelve from the lowercase characters a-z, digits 0-5, and ".", and if there is a 13th character, it is restricted to lowercase characters a-p and ".".

shouldn't read instead

> the first twelve from the lowercase characters a-z, **digits 1-5**, and ".", and if there is a 13th character, it is restricted to lowercase **characters a-o** and ".".

? or even

> the first twelve from the lowercase characters a-z **and digits 0-5** and if there is a 13th character, it is restricted to lowercase **characters a-p**.

?

- **The first twelve characters use 5 bits each** (which means there's no space for 0)
`a-z (26 chars) + 1-5 (5 digits)+ "." (1 char) = 32 possible chars in total (= 2^5 bits)`
- **The 13th character uses 4 bits** (which means there's no space for "p")
`a-o (15 chars) + "." (1 char) = 16 possible chars in total (= 2^4 bits)`

So it shouldn't consider "." and 0 or "p" and "." as two different characters, because in the end they both convert to 0 as well as any other character outside the range, which can be misleading.

`aaaa22.2bbbbp = aaaa2202bbbb.` but whoever reads the comment might think otherwise.

**Comment by taokayan** [comment]
Closed as we have received any feedback. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
