### ISSUE TITLE
The table operation is not allowed

### ISSUE THREAD

**Issue by williamleecn** [EOSIO/eos#5025]
multi_index emplace pay ram by user
```
        table mytable(_self, _self);

        auto ite = mytable.begin();

        while (ite != table.end()) {
            mytable.erase(ite);
            ite++;
        }

```
but erase by the contract occur this error:
Exception Details: 3160005 table_operation_not_permitted: The table operation is not allowed
dereference of deleted object

**Comment by jgiszczak** [comment]
`multi_index` iterators are instantly invalidated when used in an erase operation, but unlike STL containers, `erase()` returns the next element.  Try:

```
while(ite != table.end()) {
    ite = mytable.erase(ite);
}
```
