### ISSUE TITLE
Create command

### ISSUE THREAD

**Issue by gittempo** [EOSIO/eos#5027]
Anyone can write a complete sample sequence for creating a working wallet and get EOS deposit address using cleos?

is it correct sequence to create working wallet / account

cleos create key

Result

Private key: 5KCkcSxYKZfh5Cr8CCunS2PiUKzNZLhtfBjudaUnad3PDargFQo
Public key: EOS5uHeBsURAT6bBXNtvwKtWaiDSDJSdSmc96rHVws5M1qqVCkAm6

Now where im supposed to use Public command in `cleos create account` command?

Wallet

if i use this command

`cleos wallet create -n temp-wallet`

output comes likes

```
Creating wallet: default
Save password to use in the future to unlock this wallet.
Without password imported keys will not be retrievable.
"PW5JD9cw9YY288AXPvnbwUk5JK4Cy6YyZ83wzHcshu8F2akU9rRWE"

```
Now where and how i can get my deposit address?

**Comment by jgiszczak** [comment]
EOS.IO accounts are distinct from keys.  A mainnet account should have at least two independent keys, and can have an indefinite number more assigned to specific permissions, as the user wishes.

The two main keys are the owner key and the active key.  The owner key may be thought of as a recovery key.  It's intended to be kept offline in cold storage and used only to change the active key in the event it is compromised, or simply if the user wishes.  The active key is the key used to sign transactions submitted to the chain.  It is correlated with an address, but not tightly tied to one, as account keys can be changed.

In EOS.IO, your account is your address.  Accounts must be created by other accounts.  There are now services to create mainnet accounts, for a small fee.

Do **not**, under any circumstances, create a mainnet account using the key you pasted into this issue.  There are bots harvesting the web for keys and attempting transactions on the main chain using them.  You may use that key on a test net if you wish, but it is useless for securing anything public.

**Comment by jgiszczak** [comment]
The owner key is more properly called a key pair.  It is a public key (on the chain) and your private key, in secure storage.  The active key is similarly a key pair, with the public key on the chain, registered as part of creating your account, and your private key, on your local hard drive.
