### ISSUE TITLE
malloc: *** malloc_zone_unregister()  On OSX 10.12 

### ISSUE THREAD

**Issue by hawkit** [EOSIO/eos#503]
After build EOS on MacOS Sierra (OSX 10.12.6),   then enter "./eosd" in the terminal,  it show following failed message: 

> eosd(32053,0x7fffb3a1e3c0) malloc: *** malloc_zone_unregister() failed for 0x7fffb3a14000

but eosd still starts to work and  produces blocks 

>330006ms thread-0   producer_plugin.cpp:233       block_production_loo ] initn generated block #386 @ 2017-09-26T07:05:30 with 0 trxs  0 pending
333005ms thread-0   chain_controller.cpp:235      _push_block          ] initt #387 @2017-09-26T07:05:33  | 0 trx, 0 pending, exectime_ms=0
333005ms thread-0   producer_plugin.cpp:233       block_production_loo ] initt generated block #387 @ 2017-09-26T07:05:33 with 0 trxs  0 pending
336002ms thread-0   chain_controller.cpp:235      _push_block          ] initp #388 @2017-09-26T07:05:36  | 0 trx, 0 pending, exectime_ms=0

When I  enter "./launcher -p2 --skip-signature" in the terminal to run multi-node local testnet,  I get following result: 
>launcher(32466,0x7fffb3a1e3c0) malloc: *** malloc_zone_unregister() failed for 0x7fffb3a14000
adding hostname 192.168.1.15
adding hostname 192
found interface 127.0.0.1
found interface 192.168.1.15
spawning child, programs/eosd/eosd --skip-transaction-signatures  --data-dir tn_data_0
[1]    32466 illegal hardware instruction  ./launcher -p2 --skip-signature

After googling for a while, I have found some useful information about this issue. 

>Zone allocator registration code failing on OSX 10.12
https://github.com/jemalloc/jemalloc/issues/420

" illegal hardware instruction" error may be caused by malloc in  libmalloc in OSX 10.12. 

So are there anyone here have encountered this issue,  or any solution?

Thanks!

**Comment by heifner** [comment]
Very old issue. No longer see this issue.
