### ISSUE TITLE
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations (**I already tried to set permissions via eosio.code :(

### ISSUE THREAD

**Issue by erikajung** [EOSIO/eos#5032]
I've been stuck on this error for days trying to use a transfer generated from EOSIO_ABI_EX (I did the comment/uncomment hack with a EOSIO_ABI to be able to generate .abi and it's been calling the methods at least)

When I do the transfer though it fires this error (normal transfers from user1 to user2 are fine, but transfers to the contract fail due to this permissions error): 
`Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"testcontract","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [{"actor":"testcontract","permission":"eosio.code"}], and provided keys []
`

I fired up a transaction -d -j and this is what I got:

> {
>   "expiration": "2018-08-04T02:01:38",
>   "ref_block_num": 2919,
>   "ref_block_prefix": 3929369957,
>   "max_net_usage_words": 0,
>   "max_cpu_usage_ms": 0,
>   "delay_sec": 0,
>   "context_free_actions": [],
>   "actions": [{
>       "account": "eosio.token",
>       "name": "transfer",
>       "authorization": [{
>           "actor": "user1",
>           "permission": "active"
>         }
>       ],
>       "data": "00000000807015d620294af152aea46120a10700000000000453595300000000047265642d"
>     }
>   ],
>   "transaction_extensions": [],
>   "signatures": [
>     "SIG_K1_K36HR7di1jzViZr7VH9GUsxoBbXsdmsprZ9uRHm2JtdYBjoPj6QrLecXb11MrvH7VRJHHgDJYcAKZRz9EshzSSEfW22Pjj"
>   ],
>   "context_free_data": []
> }

I attempted this solution that others have posted, with all of my public keys just to be sure:  `cleos set account permission user1 active '{"threshold":1, "keys":[{"key":"EOS8jY5J5VCHUbG2xF5TRACBfRv7cLcNGQ1WcPq8x33XaDT2xhhUx", "weight":1}], "accounts": [{"permission":{"actor":"testcontract","permission":"eosio.code"},"weight":1}]}' owner -p user1
`

Then I tried again setting permission of testcontract active to testcontract eosio.code, and that gave this new error:
`cleos push action eosio.token transfer '{"from":"user1", "to":"testcontract", "quantity":"2.0000 SYS", "memo":""}' -p user1

Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: unable to find key
pending console output: 

`

**Comment by taokayan** [comment]
```assertion failure with message: unable to find key``` possibly refer to token not created, or user not found..., etc. However, the permission check seems already passed. Have you created the token SYS?

**Comment by erikajung** [comment]
Got it, you were right! Lost track of all my cleos commands. Thanks!

**Comment by hippo-dalaoshe** [comment]
I meet the same probolem, how to solve it?
