### ISSUE TITLE
[BUILD] boost_system and boost_chrono missing

### ISSUE THREAD

**Issue by lazaridiscom** [EOSIO/eos#5034]
## Problem

Occasionally, users report that the build fails due to the missing:

```
boost_system
boost_chrono
````

This happened 

* a few months ago on CentOS (#3111), 
* nowadays again on ubuntu (#4916).
* just now on my laptop (VirtualBox ubuntu 18.04 on Win10 Pro)

## Workaround

The suggested workaround here https://github.com/EOSIO/eos/issues/3406#issuecomment-392050991 is to delete the `opt/boost` and the build folder, and to update the clone of the repo.

For me, this simple step did it:

```bash
#within eos dir
rm -rf ../opt/boost*
./eosio_build.sh
```

This indicates that there is 
* a sporadic failure, possibly due to download timeouts or similar.
* something that happens on the first build attempt (e.g. a path is set or similar), which lets the 2nd build attempt work fine.

## Solution Path

* Research the problem (ideally on a slower laptop)
  * is the 1st attempt always failing?
* Verify the downloads 
* Fix the build-scripts, so this problem does not occur again

A quick-fix could be possibly to repeat the fetch-phase

**Comment by taokayan** [comment]
Which boost version are you using? 1.67 is recommended.

**Comment by lazaridiscom** [comment]
@taokayan , this is more about the automatically installed version 1.67 (2 users, including me). Although the problem happened at least once in an older eosio version, which installed 1.66.
