### ISSUE TITLE
EOSIOCPP - Unable to compile with 1.1.2/1.1.3 on fresh install.

### ISSUE THREAD

**Issue by Pdsmithjp** [EOSIO/eos#5039]
I have spent the last two days trying to resolve an issue that is present with recent versions of EOSIO that was not present before.

On fresh installs of Ubuntu 16.04/18.04/18.10 (VBOX)

Installed 1.1.3 following the official guide.

1) git clone https://github.com/EOSIO/eos --recursive

2) cd eos
./eosio_build.sh

3) cd build
sudo make install

No build errors occurred. I manually added the following path to my .profile and resourced it. This was not necessary in earlier versions of EOSIO.

/usr/local/eosio/bin

On trying to compile eosio.token from /eos/contracts/eosio.token, I receive the following error

eosiolib/asset.hpp not found 

I tried adding /eos/contracts to my path but no joy. Clearly undocumented changes have been made. It is vital the official documentation is updated when this happens. It wastes lots of developer time and goodwill. 

# @ #5015

**Comment by lazaridiscom** [comment]
And most possibly, #5040 is related.

**Comment by Pdsmithjp** [comment]
I resolved this by installing eosio.wasmsdk and eosio.contracts. Note there is (another) bug in the build script for eosio.wasmsdk, and it does not install the required boost 1.67. You need to do this manually.

**Comment by Pdsmithjp** [comment]
On the upside, once you manage to eosio.wasmsdk installed and working you might see significant reductions in your wast file size. My file size went from 34K->17K. This is a huge saving in ram costs, and worth the effort.

**Comment by lazaridiscom** [comment]
@Pdsmithjp , see #5133 for a workaround/fix

(you can close the issue if you think its adequately fixed for you)

**Comment by lazaridiscom** [comment]
try the latest 1.2.0, this should fix your issues (please close this issue if it works for you).
