### ISSUE TITLE
No "eosio.token.hpp" after installation

### ISSUE THREAD

**Issue by yiran-ever** [EOSIO/eos#5045]
Some user-define contracts used the currency::transfer action in the past, since now  currency contract is deprecated in favor of eosio.token, should the new header file be installed into system directory or we need to defined an action struct manually?

**Comment by taokayan** [comment]
Please refer to the latest version of eosio.contracts. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
