### ISSUE TITLE
Undelegatebw on local development node.

### ISSUE THREAD

**Issue by Pdsmithjp** [EOSIO/eos#5047]
I am unable to undelegatebw on my development node due to 15% of voters not voting. Is this there a simple workaround for this?

**Comment by Pdsmithjp** [comment]
I have tried setting a regproducer and then voting 20% of all issued tokens, but still receive this error when trying to undelegatebw.

**Comment by taokayan** [comment]
Can you place your exact what happened on your node?

**Comment by Pdsmithjp** [comment]
In the end I modified producer_pay.cpp line 8 to zero! Recompiled the system contract. Problem solved

**Comment by jgiszczak** [comment]
For future reference, the not-editing-the-source-code solution is to issue enough tokens such that voting 15% exceeds the 150 million token limit on line 8.  To emulate mainnet, testnets should create and issue 1 billion tokens.
