### ISSUE TITLE
Confusing inline traces, repetitive action data

### ISSUE THREAD

**Issue by Jeiwan** [EOSIO/eos#5048]
I noticed that inline traces contain identical action data and it's not clear how many times the action was actually executed. Could you clarify this moment please?

Here's an example (many unrelated fields were omitted):

```json
{
   "receipt":{
      "receiver":"eosio.token",
      "global_sequence":6727890
   },
   "act":{
      "authorization":[
         {
            "actor":"eosio",
            "permission":"active"
         }
      ],
      "account":"eosio.token",
      "name":"transfer",
      "data":{
         "from":"eosio",
         "to":"eosio.saving",
         "quantity":"354.2156 EOS",
         "memo":"unallocated inflation"
      }
   },
   "inline_traces":[
      {
         "receipt":{
            "receiver":"eosio",
            "global_sequence":6727891
         },
         "act":{
            "authorization":[
               {
                  "actor":"eosio",
                  "permission":"active"
               }
            ],
            "account":"eosio.token",
            "name":"transfer",
            "data":{
               "from":"eosio",
               "to":"eosio.saving",
               "quantity":"354.2156 EOS",
               "memo":"unallocated inflation"
            }
         },
         "inline_traces":[

         ]
      },
      {
         "receipt":{
            "receiver":"eosio.saving",
            "global_sequence":6727892
         },
         "act":{
            "account":"eosio.token",
            "name":"transfer",
            "authorization":[
               {
                  "actor":"eosio",
                  "permission":"active"
               }
            ],
            "data":{
               "from":"eosio",
               "to":"eosio.saving",
               "quantity":"354.2156 EOS",
               "memo":"unallocated inflation"
            }
         },
         "inline_traces":[

         ]
      }
   ]
}
```
(transaction id: 1f9b26807a4772af2e249d3f4e879221b958e031ac3b4f3fe74d0e063c8af5d8)

The root trace and the inline traces contain absolutely identical action data: they all transfer 354.2156 EOS tokens from `eosio` to `eosio.saving`. But how many times these tokens were actually transferred? And how to find the action that actually transferred the tokens?

All these actions have different `receipt.receiver` field values, and, only in the root action, it matches `act.account`. Does it mean that this is the action that actually transferred the tokens? What about action data in inline traces? Does it always duplicate the data of the root action or it's possible that it reflects what the inline action actually did?

What does it mean when `receipt.receiver` and `act.account` fields don't match?

**Comment by tbfleming** [comment]
There are 3 actions:
* The original: sent to `eosio.token` (receiver in the 1st)
* A carbon copy sent to `from`  (receiver in the 2nd)
* A carbon copy sent to `to` (receiver in the 3rd)

`eosio.token` sends carbon copies (`require_recipient` function) to `from` and `to` so they can be notified of the transfer.

**Comment by Jeiwan** [comment]
@tbfleming Thanks!
What's the correct way to identify carbon copies? Is it possible that `receipt.receiver` and `act.account` don't match in original actions? I'm looking for a proper way to separate copies from original actions.

**Comment by tbfleming** [comment]
receiver and account will always match in the original.

**Comment by Jeiwan** [comment]
@tbfleming Thanks.
