### ISSUE TITLE
High latency when high trx

### ISSUE THREAD

**Issue by DebugFuture** [EOSIO/eos#5049]
I saw high latency when trx is high in one of my test full node.  Not sure if it's related to the disk iops limitation.

os: Ubuntu 16.04
nodeos version: mainnet-1.1.1
memory: 32GB
disk: aws ssd gp2 200GB (so the iops limitation is 3 * 200 = 600 according to aws)

latency and trx num from nodeos log:
<img width="644" alt="2018-08-05 22 38 40" src="https://user-images.githubusercontent.com/8135834/43686963-9568fc4a-9900-11e8-9561-5e1ad572c626.png">

<img width="306" alt="2018-08-05 22 40 09" src="https://user-images.githubusercontent.com/8135834/43686964-98448ee8-9900-11e8-919b-3426313b10d3.png">

<img width="313" alt="2018-08-05 22 39 58" src="https://user-images.githubusercontent.com/8135834/43686965-9a635830-9900-11e8-8765-ce47bf009429.png">

**Comment by tbfleming** [comment]
I believe you're right about the cause. You can probably solve it using an AWS instance that has local SSD storage.

**Comment by taokayan** [comment]
I guess this is more related to the hardware limitation. ```iowait``` means the cpu is idle, but waiting for the io to complete. You can try to test it on your local machine or a different instance with more IOPS.

**Comment by DebugFuture** [comment]
I'm expanding the IOPS limitation to check again. By the way, may I ask what's the limit of IOPS should I have to avoid this problem? Is there a recommendation?

**Comment by DebugFuture** [comment]
I increased the IOPS limitation to 1500. The iowait is down to about 0.5%. But the latency is still high when trxs is high. The latency is the same as before.

**Comment by DebugFuture** [comment]
I changed to local ssd with great iops and can still see high latency when trxs is high. I think it may because the data transferred is large. Is it by design?

**Comment by DebugFuture** [comment]
![wechatimg113](https://user-images.githubusercontent.com/8135834/44832157-46d2f800-ac5c-11e8-9100-e478f38e72cf.jpeg)

This is a full node which is directly connected to our producer node. The latency is high when trx is high. It will cause forks and missing blocks sometimes.

The disk io is not a problem because both of them are local SSD. The network is also not a problem because they are located in the same zone. 

For CPU, I tried both 2.3 GHz and 4GHz, didn't solve the problem.

**Comment by taokayan** [comment]
Please test with the latest version. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
