### ISSUE TITLE
constant value of config::billable_size<table_id_object> is inconsistent with comment

### ISSUE THREAD

**Issue by smlu** [EOSIO/eos#5050]
https://github.com/EOSIO/eos/blob/9be89106da1d6a1543eb19dd0f3b96a53e286088/libraries/chain/include/eosio/chain/contract_table_objects.hpp#L167

I'm not sure if this is a bug or not but it's confusing to understand what the correct constant field size should be since the comment says it's 36 bytes and the actual size is 44 bytes.

**Comment by taokayan** [comment]
Please trust the source code as it's already being used.

**Comment by smlu** [comment]
Ok, so 44 bytes is the correct size and the comment should be updated than?

**Comment by taokayan** [comment]
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
