### ISSUE TITLE
Runtime Error Processing WASM

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5052]
1、debug.cpp is:
![image](https://user-images.githubusercontent.com/11773000/43693483-b2dc73b4-9960-11e8-92d8-b1ec32ce8c16.png)
2、debg.hpp
![image](https://user-images.githubusercontent.com/11773000/43693506-d57c8bc0-9960-11e8-85e2-90ba0e40a5f8.png)
3、but console is 
![image](https://user-images.githubusercontent.com/11773000/43693524-f8f8de00-9960-11e8-81c6-6ea52c054bd1.png)
4、log is
![image](https://user-images.githubusercontent.com/11773000/43693536-06aab3c0-9961-11e8-8720-f4fa35d1ae40.png)
5、in /usr/local/eosio/include/eosiolib/contracts.dox illustrate 
![image](https://user-images.githubusercontent.com/11773000/43694652-fd75ee7c-9966-11e8-86c7-46136ee743b8.png)
5、whent i modify to 
![image](https://user-images.githubusercontent.com/11773000/43695033-c330dd6a-9968-11e8-90e4-514233d56552.png)
it produce  the same error

**Comment by taokayan** [comment]
you need to compile your cpp into wast using eosiocpp first.

**Comment by amActiveHello** [comment]
I aready  have compiled use eosiocpp:
`eosiocpp -o debug.wast debug.cpp
eosiocpp -g  debug.abi  debug.cpp
`

**Comment by amActiveHello** [comment]
1、when use 
`cleos set code account wastFileFullPath`
`cleos set abi account abiFileFullPath`
set code still have the same error:
![image](https://user-images.githubusercontent.com/11773000/43768029-ff00f126-9a68-11e8-93d7-89cfdd3b4b17.png)
2、log error still is:
![image](https://user-images.githubusercontent.com/11773000/43768073-169ab178-9a69-11e8-93cd-73998c2bceec.png)
3、debug.cpp
![image](https://user-images.githubusercontent.com/11773000/43768112-289ed214-9a69-11e8-9902-856f83d02ae3.png)
4、debug.hpp
![image](https://user-images.githubusercontent.com/11773000/43768135-38126a44-9a69-11e8-8ebc-6fdea7986ffd.png)

**Comment by taokayan** [comment]
Your function signature is not correct, please refer to the MARCO:
```
#define EOSIO_ABI( TYPE, MEMBERS ) \
extern "C" { \
   void apply( uint64_t receiver, uint64_t code, uint64_t action ) { \
      auto self = receiver; \
      if( action == N(onerror)) { \
         /* onerror is only valid if it is for the "eosio" code account and authorized by "eosio"'s "active permission */ \
         eosio_assert(code == N(eosio), "onerror action's are only valid from the \"eosio\" system account"); \
      } \
      if( code == self || action == N(onerror) ) { \
         TYPE thiscontract( self ); \
         switch( action ) { \
            EOSIO_API( TYPE, MEMBERS ) \
         } \
         /* does not allow destructor of thiscontract to run: eosio_exit(0); */ \
      } \
   } \
} \
```

**Comment by amActiveHello** [comment]
now ,when i modify debug.cpp , set code && set abi are ok,
but generated another error , although i use `-p debug`:
Error 3050000: Action validate exception
![image](https://user-images.githubusercontent.com/11773000/43769778-28726144-9a6d-11e8-80dc-b3576fe393cc.png)
