### ISSUE TITLE
docker_nodeosd_1 exited with code 137

### ISSUE THREAD

**Issue by yqzzj** [EOSIO/eos#5054]
I started nodeos v1.1.2 in docker:
root@eos:~/eos/Docker# docker-compose up  -d

![image](https://user-images.githubusercontent.com/19380198/43697298-c96daf70-9975-11e8-8d4c-432cf46481f5.png)

I don't know why nodeos stoped...
And when I restart,  the commond line returns:
![image](https://user-images.githubusercontent.com/19380198/43697337-12a99168-9976-11e8-8ebb-7fe39a662210.png)

**Comment by samkirton** [comment]
I'm encountering this error on every first attempt of `docker-compose up`, all subsequent calls run successfully.

**Comment by villesundell** [comment]
Same here, when I re-start the docker-compose, it works like it should :)

**Comment by danazkari** [comment]
Having the same issue, although it's not fixing no matter how many times I restart the docker-compose.

**Comment by samkirton** [comment]
@danazkari run docker-compose with `--delete-all-blocks` flag on `nodeosd`, then `docker-compose stop`, `docker-compose down`, `docker-compose up` will fix it.

**Comment by danazkari** [comment]
I think it solved it, thanks! At least now is running smoothly 👍
