### ISSUE TITLE
How to import old account into keosd?

### ISSUE THREAD

**Issue by cliff-ck** [EOSIO/eos#5056]
Hi all:
I've a eos account now,but i can't import it into my wallet,the step is:

`cleos wallet create -n MY_ACCOUNT_NAME`

`cleos wallet import PRIVATE_KEY`

when i run the command:

`cleos set contract MY_ACCOUNT_NAME contracts/hello -p MY_ACCOUNT_NAME`

I get a error:

`Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"cliffgueslog","permission":"active"}', but does not have signatures for it.
`

Is there some step i lost?I'm sure my wallet is unlocked and i can see the PUBLIC_KEY in wallet.

**Comment by jgiszczak** [comment]
What does `cleos wallet keys` say?  It should be something similar to:
```json
[
  "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"
]
```

**Comment by taokayan** [comment]
```cleos wallet create -n MY_ACCOUNT_NAME``` this is not your account name but your wallet name.

**Comment by cliff-ck** [comment]
Thks,I put the key into the wrong wallet....
