### ISSUE TITLE
producers produce blocks

### ISSUE THREAD

**Issue by wypsanity** [EOSIO/eos#5058]
How can I let producers produce blocks? In a single-section environment, two producers were registered and voted.On nodeos, it has always been a eosio production block. how can a producer produce a block instead of an eosio block.Sir.

**Comment by jgiszczak** [comment]
You need to meet the threshold requirements for voting.  In particular, you need to vote 15% of the tokens you issued.

**Comment by wypsanity** [comment]
Producer      Producer key                                           Url
                 Scaled votes
Producer      Producer key                                           Url
                 Scaled votes
xiaoxiaopeng  EOS7kVxD5WaUo6TfB7g3oziyh3ttSwuMxqWQpZCLyh2eS7Y5kCYuf  https://accountnum11.com/EOS7kVxD5WaUo6TfB7
g3oziyh3ttSwuMxq 1.0000
xiaoxiaoxiao  EOS7JPYeHA7mf2uMnVVFZHgX7SXEj15fihiCJHMb1AAVkapuaoBy4  https://accountnum22.com/EOS7JPYeHA7mf2uMnV
VFZHgX7SXEj15fih 0.0000
@jgiszczak sir,i have voted 15% of the tokens to xiaoxiaopeng,but But still eosio production.Can I configure p2p net? How can I do it well?

**Comment by wypsanity** [comment]
Eosio window:
9045 @ 2018-08-07T09:49:21.500 signed by eosio [trxs: 0, lib: 239044, confirmed: 0]
2962000ms thread-0   producer_plugin.cpp:1087      produce_block        ] Produced block 0003a5c685445320... #23
9046 @ 2018-08-07T09:49:22.000 signed by eosio [trxs: 0, lib: 239045, confirmed: 0]
2962500ms thread-0   producer_plugin.cpp:1087      produce_block        ] Produced block 0003a5c7776e521a... #23
9047 @ 2018-08-07T09:49:22.500 signed by eosio [trxs: 0, lib: 239046, confirmed: 0]
another window:
9045 @ 2018-08-07T09:49:21.500 signed by eosio [trxs: 0, lib: 239044, conf: 0, latency: 2 ms]
2962002ms thread-0   producer_plugin.cpp:294       on_incoming_block    ] Received block 85445320b59f68a5... #23
9046 @ 2018-08-07T09:49:22.000 signed by eosio [trxs: 0, lib: 239045, conf: 0, latency: 2 ms]
2962502ms thread-0   producer_plugin.cpp:294       on_incoming_block    ] Received block 776e521aa7f35281... #23
9047 @ 2018-08-07T09:49:22.500 signed by eosio [trxs: 0, lib: 239046, conf: 0, latency: 2 ms]

**Comment by jgiszczak** [comment]
It is not necessary to vote in 21 producers.  Any number of producers can be voted in.  I've run testnets with four producers voted in.

Note that you must vote at least 150 million of your issued system tokens.  There is an absolute count requirement as well as the percentage total requirement.

**Comment by raymondnuaa** [comment]
@wypsanity 
Suppose you can check the python file in tutorials/bios-boot-tutorial which will start more than one nodeos with different configuration/data directories. I've been used this for muti-nodes test env.
