### ISSUE TITLE
filter-out 

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5062]

**Comment by csquan** [comment]
filter-out can not work..
my config file is 
filter-on =*
filter-out =eosio:onblock:
and filter-out does not work,because I  can still get actions eosio which result in onblock records.

**Comment by ScottSallinen** [comment]
filter-out was a pull request and is not in a release yet. Did you pull the changes first?

**Comment by yankunsam** [comment]
"--mongodb-filter-out arg" works.

**Comment by jgiszczak** [comment]
`filter-out=` in the history plugin now works.
