### ISSUE TITLE
get actions result?

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5063]
when i run cmd get actions A 0 2410(the max no is 2410,first run get actions A -1 -1 and result is max no 2410),only get 800+ records,what's wrong?

**Comment by csquan** [comment]
can anyone could help？just want to get the whole actions of account.

**Comment by taokayan** [comment]
There's a time limit to the request.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
