### ISSUE TITLE
Not getting the transaction information

### ISSUE THREAD

**Issue by yashvadhvani** [EOSIO/eos#5065]
Hi,
I am performing cleos get transaction <trx_id> but i am not able to print the transaction information and i have attached history_plugin and history_api_plugin Please help me out
Thank You

**Comment by grigio** [comment]
Yeah history call seems broken https://github.com/EOSIO/eosjs/issues/287

**Comment by andriantolie** [comment]
You need to have `filter-on=` in your nodeos' config.ini
