### ISSUE TITLE
WASM SDK should probably add -fno-threadsafe-statics (__cxa_guard_acquire undefined)

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#5074]
-fno-threadsafe-statics

/usr/local/eosio.wasmsdk/bin/wasm-ld: error: CMakeFiles/eosio.system.wasm.dir/src/eosio.system.cpp.o: undefined symbol: __cxa_guard_acquire
/usr/local/eosio.wasmsdk/bin/wasm-ld: error: CMakeFiles/eosio.system.wasm.dir/src/eosio.system.cpp.o: undefined symbol: __cxa_guard_release

**Comment by larryk85** [comment]
This is already in v1.1.0.  You might need to git submodule update --recursive.
