### ISSUE TITLE
mongodb full sync delayed

### ISSUE THREAD

**Issue by elnoxvie** [EOSIO/eos#5075]
Hi All, I have been using mongodb plugin for nodeos 1.1 and running it for several weeks. It doesn't seem to catch up to the latest block after running it for so long. At this time of writing, the block reached is at 6.5 M. Current block is at 9M + .. so i was wondering if the reason was the machine that were used is too slow or they are other issues? 

Machine specs: 
n1-standard-1 (1 vCPU, 3.75 GB memory)

Hope someone knowledgable in this area could enlighten me on this.  

Thanks.

**Comment by taokayan** [comment]
you should have a machine of at least 16GB+ memory or even more.

**Comment by elnoxvie** [comment]
@heifner @taokayan Thanks both for the information. I appreciated all the help.
