### ISSUE TITLE
Recover public key in contract

### ISSUE THREAD

**Issue by eosbet-io** [EOSIO/eos#5076]
Say we have an arbitrary EOS public key: `EOS8F5PUWEA8tVHYLwueZQ6wrsxwJLvog5D2KAy9g7bdTU7iY9qDU`

How to get this into type `public_key` which is a char[34]? Seems like we must use this type with the built-in function `assert_recover_key` or it fails.

Say we have an arbitrary EOS signature: `SIG_K1_KhHP1KdoRPw3izzovoTG4fnREiswPAGXhkq1WBz97CZ1ZEiukjuz9iooGc9jjGTKsz427BJQLrS3V1i1TR2Qq2ErTPMD7F`

How do we get this into type `signature` which is a uint8_t[66]? We also need to use this specific type with the `recover_key` function.

This is really unclear and with zero documentation.

**Comment by eosbet-io** [comment]
See https://github.com/EOSIO/eos/blob/master/contracts/eosiolib/types.h for the underlying types to `public_key` and `signature`.

**Comment by CooperGoldchrest** [comment]
void test::foo(const checksum256 digest, const signature sig, const eosio::public_key pub) {
    public_key pub2;
    pub2.data[0] = char(pub.type.value);
    memcpy(&pub2.data[1], pub.data.data(), 33);
    assert_recover_key(&digest, (const char*)&sig, sizeof(signature), (const char*)&pub2, sizeof(public_key));
}

**Comment by miguelmota** [comment]
This worked for me

```c++
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>
#include <eosiolib/crypto.h>
using namespace eosio;

class ec: public eosio::contract {
  public:
      using contract::contract;

  ///@abi action
  void ecverify(std::string data, const signature &sig, const public_key &pk)
  {
    checksum256 digest;
    sha256(&data[0], data.size(), &digest);

    assert_recover_key(&digest, (const char *)&sig, sizeof(sig), (const char *)&pk, sizeof(pk));
    print("VALID");
  }
};

EOSIO_ABI( ec, (ecverify) )
``

**Comment by smlu** [comment]
If you're using eosio.cdt v1.3.x, those types were renamed to `capi_public_key` and `capi_signature`. You can check `types.h` header file to get the correct name of those types.

**Comment by kindex** [comment]
> This worked for me
> 
> ```c++
> #include <eosiolib/eosio.hpp>
> #include <eosiolib/print.hpp>
> #include <eosiolib/crypto.h>
> using namespace eosio;
> 
> class ec: public eosio::contract {
>   public:
>       using contract::contract;
> 
>   ///@abi action
>   void ecverify(std::string data, const signature &sig, const public_key &pk)
>   {
>     checksum256 digest;
>     sha256(&data[0], data.size(), &digest);
> 
>     assert_recover_key(&digest, (const char *)&sig, sizeof(sig), (const char *)&pk, sizeof(pk));
>     print("VALID");
>   }
> };
> 
> EOSIO_ABI( ec, (ecverify) )
> ```

I can't compile this code. I got error
`error: no matching function for call to 'assert_recover_key'
crypto.h:236:6: note: candidate function not viable: requires 5 arguments, but 6 were provided
void assert_recover_key( const checksum256* digest, const char* sig, size_t siglen, const char* pub, size_t publen );`

**Comment by chrisli30** [comment]
Guys, how do I generate a signature and pass in as the second parameter? I'm using 
cleos sign -k {private_key} -c {chain_id} '{"seed":"b573137b8db841e11363e8f485c96665dbaab7ea3fcc1e4f8f8314c823d4c087"}' to generate a signature for function

[[eosio::action]] void resolvebet(const uint64_t bet_id, capi_signature sig) {
......
    assert_recover_key(&activebets_itr->seed, (const char *)&sig, sizeof(sig), (const char *)&rand_signing_key, sizeof(rand_signing_key));
......

in which &activebets_itr->seed and rand_signing_key are known by me. Should I sign the whole transaction or an object?

Please help ...
