### ISSUE TITLE
 ./eosio_build.sh :: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile . how to deal with that problem ?

### ISSUE THREAD

**Issue by VtpVlan-oo7** [EOSIO/eos#5078]
Checking MongoDB installation.
	MongoDB configuration found at /root/opt/mongodb/mongod.conf.

	Checking MongoDB C++ driver installation.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    232      0 --:--:--  0:00:02 --:--:--   232
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile:

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
	Unable to download MongoDB C driver at this time.
	Exiting now.

**Comment by jgiszczak** [comment]
Your operating system root certificates are out of date.  Follow your OS-specific instructions for updating them.

In Ubuntu: `sudo apt install ca-certificates`.  Your OS may be different.
