### ISSUE TITLE
Not producing block because node appears to be on a minority fork with only 0% producer participation

### ISSUE THREAD

**Issue by learnforpractice** [EOSIO/eos#508]
eosd keep printing warning message:
1721004ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because node appears to be on a minority fork with only 0% producer participation
1728000ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because node appears to be on a minority fork with only 0% producer participation
1729005ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because node appears to be on a minority fork with only 0% producer participation
1730000ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because node appears to be on a minority fork with only 0% producer participation
1731000ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because node appears to be on a minority fork with only 0% producer participation
1732001ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because node appears to be on a minority fork with only 0% producer participation
1733003ms thread-0   producer_plugin.cpp:227       block_production_loo ] Not producing block because node appears to be on a minority fork with only 0% producer participation

You can reproduce this warning with the data in attach file.
Please close this issue if it's normal.

[tn_data_1 copy.zip](https://github.com/EOSIO/eos/files/1336515/tn_data_1.copy.zip)

**Comment by heifner** [comment]
Use `./eosd --enable-stale-production`.
