### ISSUE TITLE
'get_unapplied_transaction' call is consuming a huge amount of CPU

### ISSUE THREAD

**Issue by datudou** [EOSIO/eos#5081]
# Description
   Something strange happened on one of our full nodes. CPU is fully occupied by nodeos.  The top command output screenshot is here:
<img width="1123" alt="htop" src="https://user-images.githubusercontent.com/1549854/43759663-e6f2fe3e-9a5a-11e8-8062-872cd1e8e66b.png">
     And I use perf command to see what is consuming cpu time. I see the output above: 
<img width="798" alt="perf" src="https://user-images.githubusercontent.com/1549854/43757615-48fd2dea-9a54-11e8-85d5-76b2792e6ba6.png">
      Seems like that 'get_unapplied_transaction' call is consuming a huge amount of CPU, dose it means too many unapplied transactions will let  cpu run out? If it does, could we have more explanation with more details?
# Environment
- nodeos version:  2272778459
- Operation system: ubuntu 16.04 
- Deployed using docker container
- fully synchronized and still syncing
- Did you try to restart the node?: No

#  Nodeos logs 
<img width="1680" alt="log" src="https://user-images.githubusercontent.com/1549854/43757859-3b81f2bc-9a55-11e8-8d3d-4b62456ae85c.png">
You can see high network latency here, but still syncing.

# Steps to Reproduce
Doesn't know how to reproduce this.

**Comment by wanderingbort** [comment]
For `unapplied_transactions` to be very large you would need to have observed a fork of some sort, which appeared to be the best fork for some time, was then abandoned and contained transactions that were not reflected on the new best fork. 
-OR-
You are running a heavily used RPC node but something about your p2p connections is not relaying your users transactions
-OR- 
this is the normal amount of `unapplied_transaction` for a node on the p2p network and your CPU may be underprovisioned

Without more details it will be hard to know.

What is the docker host running on?  
VM/raw?
CPU speeds?
RAM allocation?
Disk/SSD?

If there was a prolonged fork that built a backlog of unapplied transactions that would be something we can look at and fix independently, a full log would be helpful.

**Comment by datudou** [comment]
@wanderingbort  Thx for your explanation, here are some supplements.
# More Environment Detail
* VM/raw? :  Google Cloud  Compute Engine
* CPU speeds?:  Intel(R) Xeon(R) CPU @ 2.60GHz
* RAM allocation?: 14GB
* Disk/SSD?: Google Standard persistent disk

BTW, It's not a heavily used RPC node, just a full node to use sync data. Which log do you need?  Is it a nodeos console log?

**Comment by datudou** [comment]
The console log is too big now even I have compressed it. But I find there is 14512 times mini fork during 2018-07-26  to  2018-08-09.

**Comment by datudou** [comment]
I think this issue could be closed. Cause it fixed on v1.1.5.
