### ISSUE TITLE
a plugin for querying more RAM action details

### ISSUE THREAD

**Issue by d13o** [EOSIO/eos#5083]
For the reason that RAM amount delta is not included in ram action(buyram, buyrambytes, sellram), the price of RAM trading can not be fetched and calculated from blockchain directly. To record the RAM amount delta for every RAM-related action, a table should be used to record every account's RAM balance, and then compare the balance before and after the action to calculate the delta. 

In order to resolve this problem, a plugin for querying RAM action details has been developed for enumivo([website](http://enumivo.org), [forum](https://enumivo.com)). Here is the repo of the [plugin](https://github.com/d13o/enumivo/tree/enutick/plugins/ram_plugin)

By including this plugin in config.ini and after blocks replaying, the RAM action details can be fetched from HTTP API http://HOST_ADDRESS:PORT/v1/ram/get_actions by POST method.
![image](https://user-images.githubusercontent.com/39394431/43764086-09e9aff6-9a5f-11e8-82ef-abb5008d2ec0.png)

I think the plugin might be also useful for EOS, so if there are demands here, I will make a PR to the project.

**Comment by jgiszczak** [comment]
Work is in progress to accommodate linking plugins from external repositories into `nodeos` via configuration settings.  See #5026.  A pull request may not be necessary, but if one is made, we will evaluate it as a candidate for inclusion in the base code.

**Comment by d13o** [comment]
Cool, building external plugin via config is a excellent idea. For the reason that I've add new object type in types.hpp, It maybe not be suitable to build from external repository. It's awesome if the plugin can be reviewed and evaluated by EOSIO even further included in the base code. What's more is that it is used for ENU RAM exchange enutick.com in backend.

**Comment by d13o** [comment]
I have ported Bancor algorithm from system contract to ram_plugin, it's used to evaluate ENU/RAM exchange rate before the real transaction actually involved. The evaluation can be fetched via HTTP API /v1/ram/evaluate by providing input asset amount and symbol.
<img width="908" alt="evaluate_enu" src="https://user-images.githubusercontent.com/39394431/44184897-ced8de00-a143-11e8-896c-aba47d66bff1.png">
<img width="908" alt="evaluate_ram" src="https://user-images.githubusercontent.com/39394431/44184900-d5675580-a143-11e8-94c0-808ff9a444dd.png">

**Comment by jgiszczak** [comment]
External plugins now easily integrated into the build via PRs #5026 and #5539.
