### ISSUE TITLE
Update nodeosd.sh to better handle the genesis parameters

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#5089]
When running `nodeos` for the first time on a non-test chain, you must to pass in the `--genesis-json` or one of its alternates to define the genesis information for the chain.  However, subsequent runs of `nodeos` treat this as a bad option if the chain has already been initialized.  

This presents a usability issue for docker where containers are created once with command line options and then stop/start'd liberally as you cannot provide a set of command line options that both bootstrap a chain and support stop/start.  

We could put extra logic into the nodeosd.sh script that serves as the entry point for docker that detects the presence of block data and either strips `--genesis-*` options if data exists or creates the appropriate `--genesis-*` option based on other input if data does not exist.

The goal is to have a single set of parameters that works to bootstrap into new chain, stop the node, restart the node, upgrade the node, etc.

**Comment by jgiszczak** [comment]
Nodeos now accepts a redundant `--genesis-json` argument, as long as the provided genesis file matches the on disk genesis data in the block log.
