### ISSUE TITLE
What does the "set contract" function do?

### ISSUE THREAD

**Issue by notsag-dev** [EOSIO/eos#5093]
I'm running into a problem when deploying multiple contracts. To start I created a contract that defines a multi index table. Doing that I was able to compile it, generate wast, wasm and abi files and deploy it. Additionally, insertions in the table and recovery of information from it were working fine.

In opposition to that, when I tried to build and deploy more than one contract I wasn't able to get, for example, the table rows for a table without setting the contract (again) that defines that table. This is what I'm doing:
```
 declare -a contracts=("contract1" ... "contractn")
 for contract in "${contracts[@]}"
 do
   eosiocpp -o ${contract}.wast ${contract}.cpp && \
   eosiocpp -g ${contract}.abi ${contract}.cpp && \
   cleos set contract $USERNAME . ${contract}.wast ${contract}.abi
 done
```
Maybe I'm missing the point of the **set contract** function. I thought that setting the contract was equivalent to deploying it to the blockchain for future usage, and apparently that is true, but at the same time it has to be set again each time it needs to be used. Is that correct?

Thank you.

**Comment by notsag-dev** [comment]
But what happens if you need to have a big system running on the blockchain, or worst, multiple systems under the same account? Do you have to include all the code that will be running on the blockchain

**Comment by notsag-dev** [comment]
But what happens if you need to have a big system running on the blockchain, or worst, multiple systems under the same account? Do you have to include all the code into the same contract?

**Comment by tbfleming** [comment]
Create an account for each contract.

**Comment by taokayan** [comment]
It depends on how you design your system. If a system can be split into several pieces with zero or very minimum inter-communications, you can create different accounts for different pieces. However if your system is too big, you would need to consider more on the RAM/CPU/network resources on EOS platform as they are more likely to become the real bottlenecks.

**Comment by tbfleming** [comment]
A contract can send actions to any other contract. It can also read any other contract's tables.
