### ISSUE TITLE
Cross-compiling to Webassembly

### ISSUE THREAD

**Issue by ernestopskins** [EOSIO/eos#5095]
Some days ago I asked for help to use OpenSSL inside a contract ([link to the post](https://github.com/EOSIO/eos/issues/5028)). One of the options was to cross-compile OpenSSL to WebAssemble using [eosio.wasmsdk](https://github.com/EOSIO/eosio.wasmsdk), which is the approach I think is convenient in my case.
The question today is about setting up the config file in order to compile WebAssembly. I've been reading several articles and manuals and all of them point to _--build_ and _--host_ options when running the _config_ script. Since I'm running on a Linux x64, it is clear for me what should I put on _--build_ parameter: _x86_64-pc-linux-gnu_. My question is about _--host_ parameter, because I do not see a _WebAssemble_ option.
So far I have:
./configure --build=x86_64-pc-linux-gnu --host=<?>

What should I use for _--host_?
Should I set CC variable pointing to eosio-cpp?

**Comment by jgiszczak** [comment]
`eosiocpp` is a script that includes the necessary arguments to clang, llvm-link, llc, eosio-s2wasm and eosio-wast2wasm to produce the required WASM format.  If you prefer a script, you may edit a copy of eosiocpp to suit your needs.

Alternatively, you can create directories in `contracts` for your contract and the OpenSSL source, and CMakeLists.txt files to build them.  See `contracts/eosio.system/CMakeLists.txt` and `contracts/eosio.token/CMakeLists.txt` for samples.
