### ISSUE TITLE
eosio/eos-dev:v1.1.4 lack of include files, so it can't used to compile contract source files.

### ISSUE THREAD

**Issue by vchengsong** [EOSIO/eos#5105]
In docker image eosio/eos-dev:v1.1.4, /opt/eosio/include contain bellow folders and files.
root@56aa36cbfc4c:/opt/eosio/include# ll
total 36
drwxr-xr-x  8 root root 4096 Aug  3 21:53 ./
drwxr-xr-x  1 root root 4096 Aug  3 21:53 ../
drwxr-xr-x  2 root root 4096 Aug  3 21:53 appbase/
drwxr-xr-x  2 root root 4096 Aug  3 21:53 chainbase/
drwxr-xr-x  4 root root 4096 Aug  3 21:53 eosio/
-rw-r--r--  1 root root  120 Aug  3 21:47 eosio.version.hpp
drwxr-xr-x 12 root root 4096 Aug  3 21:53 fc/
drwxr-xr-x  2 root root 4096 Aug  3 21:53 softfloat/
drwxr-xr-x 10 root root 4096 Aug  3 21:53 wasm-jit/

but in docker image eosio/eos-dev:v1.1.1, /opt/eosio/include contain bellow folders and files.
root@faff4cbcfe88:/opt/eosio/include# ll
total 44
drwxr-xr-x 11 root root 4096 Jul 24 23:28 ./
drwxr-xr-x  1 root root 4096 Jul 24 23:28 ../
drwxr-xr-x  2 root root 4096 Jul 24 23:28 appbase/
drwxr-xr-x  3 root root 4096 Jul 24 23:28 boost/
drwxr-xr-x  2 root root 4096 Jul 24 23:28 chainbase/
drwxr-xr-x  6 root root 4096 Jul 24 23:28 eosio/
drwxr-xr-x  2 root root 4096 Jul 24 23:28 eosio.system/
drwxr-xr-x  2 root root 4096 Jul 24 23:28 eosiolib/
drwxr-xr-x 12 root root 4096 Jul 24 23:28 fc/
drwxr-xr-x  3 root root 4096 Jul 24 23:28 libc++/
drwxr-xr-x  3 root root 4096 Jul 24 23:28 musl/

now, v1.1.4 can't used to compile contract files.

**Comment by lazaridiscom** [comment]
related: #5040

**Comment by helperShang** [comment]
same issues

**Comment by lazaridiscom** [comment]
try the workaround/fix within #5133

**Comment by lazaridiscom** [comment]
try the latest 1.2.0, this should fix your issues (please close this issue if it works for you).

**Comment by taokayan** [comment]
Please test with the latest version with cdt.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
