### ISSUE TITLE
How to delete a contract corresponding to the account

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5108]
![image](https://user-images.githubusercontent.com/11773000/43824888-d34ddfe0-9b25-11e8-9585-adcbae7faa2a.png)
now, i want to  delete a contract corresponding to the account,what should I do？

**Comment by taokayan** [comment]
There's no way to delete the contract. However you can upload a smaller one to get some RAM back.

**Comment by heifner** [comment]
You can also push a `setcode` transaction with an empty `setcode.code`.

**Comment by amActiveHello** [comment]
ok, this is a good solution,thank you。

**Comment by taokayan** [comment]
thanks @heifner for your answer

**Comment by heifner** [comment]
At one point I thought we had the ability to do that by passing 'null' to cleos set code.
