### ISSUE TITLE
Produce blocks only if transaction is there

### ISSUE THREAD

**Issue by yashvadhvani** [EOSIO/eos#5110]
Is there any way to produce block only if transaction is there ?

**Comment by taokayan** [comment]
Every block at least have one implicit ```onblock``` transaction which is required to process some system level events (like set producer, name bidding settlement,... etc). Also block header serves as confirmations of all the previous blocks produced by all producers. Any producer failed to generate a block has negative impact to the network confirmation time and thus the corresponding producer will get less reward.

**Comment by yashvadhvani** [comment]
But what if i want to produce only if there is a smart contract transaction. https://ethereum.stackexchange.com/questions/3151/how-to-make-miner-to-mine-only-when-there-are-pending-transactions
Like we can do this in ethereum

**Comment by jgiszczak** [comment]
There is no support in EOSIO for generating a block only when a contract transaction is submitted, and no plans to create such a feature.

You are welcome to customize the source for your own needs.
