### ISSUE TITLE
eosiocpp : command not found

### ISSUE THREAD

**Issue by vectar31** [EOSIO/eos#5111]
I used the eosio_build.sh and everything works fine except that the script probably hasn't installed eosiocpp or the path hasn't been set. There are no clear instructions. Should I setup eosiocpp separately. If so, how can I go about that?

**Comment by lazaridiscom** [comment]
see #5040

**Comment by taokayan** [comment]
It should be in ```<yourEOSFolder>/build/tools```. Are you able to find it?

**Comment by lazaridiscom** [comment]
You may need to add a path, see instructions within #5126 

(as a sidenote, you can locate eosiocpp with the command `locate eosiocpp`)

**Comment by andriantolie** [comment]
eosiocpp is deprecated, please refer to eosio.cdt. 

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by youngqqcn** [comment]
I installed eos by   deb package , It dot not contain 'eosiocpp' or 'eosio-cpp' . In lastest eos  please  use [eosio.cdt](https://github.com/EOSIO/eosio.cdt).  I use v1.4.1. It's ok.    If you are run in Virtaul Machine please change the cpu's core more than 2.(It's important to avoid eosio-cpp compile never over issue)
