### ISSUE TITLE
Error on ./iosio_build.sh

### ISSUE THREAD

**Issue by rkalyan445** [EOSIO/eos#5112]
[ 71%] contract...
[ 71%] Built target copy_skeleton_contract
[ 71%] Built target identity_common
[ 72%] Built target identity_interface
[ 72%] Built target print_floats
[ 72%] Built target eosio-s2wasm
make[2]: *** No rule to make target '/usr/local/opt/openssl/lib', needed by 'libraries/chainbase/test/chainbase_test'.  Stop.
CMakeFiles/Makefile2:949: recipe for target 'libraries/chainbase/test/CMakeFiles/chainbase_test.dir/all' failed
make[1]: *** [libraries/chainbase/test/CMakeFiles/chainbase_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 77%] Built target fc
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

        >>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by taokayan** [comment]
looks like some 3rd party libraries (openssl) are missing. You can try to install it first.

**Comment by taokayan** [comment]
Please try the latest version.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
