### ISSUE TITLE
How to configure keosd config.ini to allow connections from private network?

### ISSUE THREAD

**Issue by filipniziol** [EOSIO/eos#5114]
I have a keosd running on http://127.0.0.1:8900
What I want to enable calls from the private network.
The server running keosd has within the network an ip address 10.0.0.4.
How to configure wallet config.ini file? 
What are the plugins needed?

**Comment by jgiszczak** [comment]
In `~/eosio-wallet/config.ini` change `http-server-address` to `http-server-address = 0.0.0.0:8900` and run `keosd` without the `--http-server-address` command line argument.

Note this configuration is strongly discouraged.  You must be very certain of your firewall configuration to prevent misuse.  In particular, `keosd` will sign transactions using any key it knows upon any request that can reach it, which means transfer transactions could be signed without your knowledge.

**Comment by filipniziol** [comment]
Sure! I have the keosd on the ubuntu server with all ports closed apart from 22 and private network with an access granted to our web app that is the only user of keosd.

**Comment by filipniziol** [comment]
Thank you for the answer!
