### ISSUE TITLE
How to create a transaction signature using c#? What is the algorithm?

### ISSUE THREAD

**Issue by filipniziol** [EOSIO/eos#5115]
I would like to sign a transaction directly within ASP.NET application and then simply send it as a call to http api.
What is the algorithm that I should use to build c# signer?

**Comment by jgiszczak** [comment]
R1 key signing is done via OpenSSL, specifically

```C++
int ECDSA_sign(
  int type,
  const unsigned char *dgst,
  int dgstlen,
  unsigned char *sig,
  unsigned int *siglen, EC_KEY *eckey);
```
in `openssl/ecdsa.h` from the system installation.

K1 key signing is done via
```C++
int secp256k1_ecdsa_sign_compact(
  const secp256k1_context_t* ctx,
  const unsigned char *msg32,
  unsigned char *sig64,
  const unsigned char *seckey,
  secp256k1_nonce_function_t noncefp,
  const void *ndata,
  int *recid
);
```
in `secp256k1.h` from the Cryptonomex branch of the secp256k1 library called secp256k1-zkp, found [here](https://github.com/cryptonomex/secp256k1-zkp.git) and automatically installed as a dependency during the build process.
