### ISSUE TITLE
faucet_testnet_plugin can NOT pass build after enable it

### ISSUE THREAD

**Issue by raymondnuaa** [EOSIO/eos#5118]
As there is a create_account API in faucet plugin, then I tried to enable the plugin.
But found the code of this plugin is outdated.  The change needed is as following. 
The question is that do we still need to keep this faucet plugin? 
If yes, I‘d like to create a pull request to merge the change. Thanks! 

chain::chain_id_type chainid;
auto& plugin = _app.get_plugin<chain_plugin>();
plugin.get_chain_id(chainid);
controller& cc = plugin.chain();
---------change to the following---->
chain_id_type chainid = app().get_plugin<chain_plugin>().get_chain_id();
chain::controller& cc = app().get_plugin<chain_plugin>().chain();

cc.push_transaction( std::make_shared<transaction_metadata>(trx) );
---------change to the following---->
cc.push_transaction( std::make_shared<transaction_metadata>(trx), fc::time_point::maximum());

**Comment by halsaphi** [comment]
Closed as refers to old version of code.
Please refer to latest code and documentation:
https://github.com/EOSIO
https://developers.eos.io/
If problem persists with latest version please raise new issue.
