### ISSUE TITLE
Just-in-time Transaction Scheduling / Async Push Transaction

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#512]
In a multi-threaded environment chain::push_transaction cannot be synchronous, it the transaction will have to be scheduled then dispatched to the proper thread and then finally accepted or rejected. 

Our unit tests still benefit from having a synchronous push_transaction, so this task is to define a new method called async_push_transaction(). Because things are ASYNC we cannot use the STACK for managing the transaction lifetime, therefore we should move to a shared ptr model.

This method should take a functor that is called with success or any errors.

- [ ] Build a block as transactions are pushed
- [ ] don't apply a transaction 3x on producing node, only apply it 1x
- [ ] refactor transaction scheduling to handle read-only scopes and just-in-time scheduling
- [ ] if a transaction is postponed to next cycle, it the next cycle should start no later than 100 ms

**Comment by bytemaster** [comment]
As part of this task I am reviewing our high level design processing incoming transactions.  I have mostly focused on the interface specification at this time.  Nothing to commit just yet.

**Comment by bytemaster** [comment]
I'm going to put this task on hold until a refactor of chainbase to support proper scoping of tables.

**Comment by bytemaster** [comment]
https://github.com/EOSIO/eos/issues/525 will be implemented first, then get back to this.

**Comment by andriantolie** [comment]
@bytemaster is this still issue completed?

**Comment by brianjohnson5972** [comment]
Any plans of making push_transaction be synchronous have been dropped, so this issue is OBE
