### ISSUE TITLE
chain-state-db-size-mb not read from config file 

### ISSUE THREAD

**Issue by warrick-eosny** [EOSIO/eos#5120]
It seems that the "chain-state-db-size-mb" option is not read from the config.ini file. 

If you supply it on the commandline it takes effect, however setting it in the config does nothing. 

Yes, I have made sure that the formatting is correct and yes I have ensured that the server is in fact loading the config.ini file that I believe it is. 

Version = 1.1.1

This is currently a very painful lesson to learn after waiting hours for chain to replay as you get a message which states "please increase the value set for "chain-state-db-size-mb" and restart the process!" ..which one tends to do in the config file ... then find that the replay fails again .. 

It would also be great if the plugin logged the settings in use so that one could see the value of the settings (default or not) that are being used at the time of execution.

**Comment by warrick-eosny** [comment]
I also realize that something doesn't make sense here as one would imagine others have run into this. I am trying to build a fresh box a reproduce this at the moment.

**Comment by heifner** [comment]
You have `--config-dir=/oes` instead of `--config-dir=/eos`

**Comment by warrick-eosny** [comment]
Sorry .. I need to check on my dyslexia ... ugg ... I guess it would be nice if the the config-dir didn't exist an exception was thrown.

**Comment by jgiszczak** [comment]
`nodeos` needs to run out of the box, so if the config-dir is missing, it will create it, along with a copy of its default config.

To ensure config-dir exists, specify `-c` or `--config` and a filename other than `config.ini`.  If you use a non-default config file name, a missing config file will trigger an error message and exit.
