### ISSUE TITLE
nodeos crash when setting chain-state-db-size-mb bigger than RAM

### ISSUE THREAD

**Issue by newbieh4cker** [EOSIO/eos#5121]
I'm trying to sync block from mainnet(which is running full node).
Here is env.
- using Google Cloud Platform
- OS : Ubuntu 16.04 LTS
- number of CPU : 4
- RAM : 16 GB
- SSD : 500 GB ( free space is about 400GB )
- eosio version : cloned master commit from repo.

I heard that to run full node on mainnet, I need to set chain-state-db-size at least 64GB. But in 'config.ini' file, if I set "chain-state-db-size" bigger that actual server RAM (16GB = 16384MB) and start nodeos, it crash after 3-4 seconds.

one of my friends told me he set the chain-sate-db-size as 100GB on server with 32GB RAM, and his nodeos works fine.

What could be wrong

**Comment by taokayan** [comment]
Please test with the latest version. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.

**Comment by csquan** [comment]
I want to know if set  chain-sate-db-size bigger that actual server RAM,there any influence?

for example,speed and performance

**Comment by jgiszczak** [comment]
@csquan There was one release which attempted to lock the amount of RAM required to fulfill the chain-state-db-size setting.  It was reverted in a subsequent release.  Performance can and will decline if the chain state actually requires more RAM than is present in the system.  It will swap at the very least, and may crash if swap is not available.  To test this behavior, enable history_plugin with `filter-on="*"` and sync with main net.  It will eventually use more RAM than is available on all but the very best provisioned systems.
