### ISSUE TITLE
have connection error

### ISSUE THREAD

**Issue by wypsanity** [EOSIO/eos#5123]
the nodeos:
2076544ms thread-0   net_plugin.cpp:1148           operator()           ] sent a go away message: duplicate, clo
sing connection to 127.0.0.1:9877
2076544ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from 127.0.0.1:9
877: Bad file descriptor
the cleos: 
2076544ms thread-0   net_plugin.cpp:2188           operator()           ] Error reading message from connecting
client: Bad file descriptor

Excuse me，What is the reason？

**Comment by jgiszczak** [comment]
When configuring a multinode local testnet, be sure you have only one copy of `p2p-peer-address =` for each remote node.  Duplicate entries will result in multiple connections and the reported error messages.

If you have some sort of virtual hosting set up which results in multiple nodes with the same hostname and same port number, or the same apparent IP and port number, distinguish them by explicitly setting unique `p2p-server-address = ` entries for each node.
