### ISSUE TITLE
push_transaction rpc error

### ISSUE THREAD

**Issue by egonson** [EOSIO/eos#5124]
I called http://127.0.0.1:8888/v1/wallet/push_transaction -d '
{
"packed_trx":"62fc6b5b68e9a0166717000000000100a6823403ea3055000000572d3ccdcd0190ddb91466772...",
"packed_context_free_data":[],
"compression":"none",
"signatures":["SIG_K1_JxDAMo...","SIG_K1_K7LUVZ..."]
}
'
(the account has multisig)

But I met the error
http://127.0.0.1:8888/v1/wallet/push_transaction: {"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[]}}

packed_trx is right.
I compared it with cleos's packed trx.

What's the problem?

**Comment by andriantolie** [comment]
It should be http://127.0.0.1:8888/v1/chain/push_transaction instead of http://127.0.0.1:8888/v1/wallet/push_transaction
