### ISSUE TITLE
Where get location id? (help needed)

### ISSUE THREAD

**Issue by plazav** [EOSIO/eos#5128]
To specify producer location there are some id numbers used. 
The question is where to get those id's?
Have tried to use https://api1.eosdublin.io/v1/chain/get_table_rows with body 
`{"json":true,"code":"eosio","scope":"eosio","table":"locations","table_key":"","limit":500}`
but table with this name is missing. May be there is some way to see all tables list?

**Comment by wuyahuang** [comment]
try `cleos get table eosio eosio producers`

**Comment by jgiszczak** [comment]
You may simply use `cleos --print-response system listproducers`, which gives you the detailed producer information as JSON, immediately followed by the human readable form.  Note that the full registered producers list is long enough that the response is automatically limited in length to 50 entries at a time.

**Comment by plazav** [comment]
Thank you for answers, but not any of those queries could give me complete list of location id's and location names.
