### ISSUE TITLE
Name bidding has wrong logic

### ISSUE THREAD

**Issue by oranke** [EOSIO/eos#5140]
`producer_pay.cpp` sets highest `high_bid` info to negative every minute. 
But it refers `highbid` index of `bidnams` table and it always returns negative value to the top most. 
So even if other bidding times are old enough, they can't reach their turn until top most bidder create new account.

---

 1. See `onblock` function in `producer_pay.cpp` . It select highest bid info using `highbid` index.
 1. See `name_bid` structure in `eosio.system.hpp`. It has `highbid` index and it returns negative value of `high_bid`. So If there are negative value in table, `onblock` function always get that info.
 1. See `bidname` function in `eosio.system.cpp`. It checks `high_bid` value is negative.
 1. If top most negative bidder don't make it's account, the others never get chance to be negative

---

* My `cleos` try to get highest bidders in mainnet
```bash
$ cleos get table eosio eosio namebids -l 5 --index 2 --key-type i64
{
"rows": [{
  "newname": "app",
  "high_bidder": "f2poolshenyu",
  "high_bid": -275000001,
  "last_bid_time": "1533287763000000"
},{
  "newname": "ex",
  "high_bidder": "gm3denbwguge",
  "high_bid": 26660000,
  "last_bid_time": "1533739098000000"
},{
  "newname": "pra",
  "high_bidder": "g44dqnygenes",
  "high_bid": 22000001,
  "last_bid_time": "1533530080000000"
},{
  "newname": "games",
  "high_bidder": "loveshaoxing",
  "high_bid": 20190000,
  "last_bid_time": "1533437030000000"
},{
  "newname": "dex",
  "high_bidder": "gezdmnbtg4ge",
  "high_bid": 17000000,
  "last_bid_time": "1532905015500000"
}
],
"more": true
}
```

 * Fifth `dex`'s bidnameinfo
```bash
$ cleos system bidnameinfo dex
bidname:                               dex
highest bidder:               gezdmnbtg4ge
highest bid:                      17000000
last bid time:     2018-07-29T22:56:55.500
```

 * I checked this info in `UTC 2018-08-09T23:52:00.000`. 
 `dex` still has positive value and it can't be a new account.

**Comment by wuyahuang** [comment]
Yes, only 1 and just 1 bidname will be create per day.

**Comment by taokayan** [comment]
This is the current behavior. You need to wait for f2poolshenyu to create the name app before any other name can be closed.

**Comment by oranke** [comment]
Thank's for your reply @taokayan 
Hmm... Interesting. It really seems like bug. 

Where can I found code about your comment? 
Is there a official document?

The eosio system contract checks `bidnames` table every minute. 
So... What do you think the reason is?


I just found some links. 
https://github.com/EOSIO/eosio.contracts/releases/tag/v1.1.1
https://github.com/EOSIO/eos/pull/4849
https://github.com/EOSIO/eosio.contracts/issues/21

There's many peoples who have same question about `name auction blocking`.

Oh... Some fix already prepared. 
https://github.com/EOSIO/eosio.contracts/blob/master/eosio.system/src/producer_pay.cpp

**Comment by oranke** [comment]
I always thanks you contributors. 
But I want you do not close issues carelessly. 
Have a good day.

**Comment by tiboong** [comment]
@taokayan do you think this is normal? any other name bidders have to wait blankly until 'f2poolshenyu' create the name 'app'?
