### ISSUE TITLE
chain_plugin uses two types of function call for incoming::methods::transaction_async

### ISSUE THREAD

**Issue by raymondnuaa** [EOSIO/eos#5142]
In chain_plugin.cpp, it defines the member variable:

incoming::methods::transaction_async::method_type& incoming_transaction_async_method;

and it is initialized in construction function:

incoming_transaction_async_method(app().get_method<incoming::methods::transaction_async>());

Then it is used in the following function:

void chain_plugin::accept_transaction(const chain::packed_transaction& trx, next_function<chain::transaction_trace_ptr> next) {
   my->incoming_transaction_async_method(std::make_shared<packed_transaction>(trx), false, std::forward<decltype(next)>(next));
}

But in function:

void read_write::push_transaction(const read_write::push_transaction_params& params, next_function<read_write::push_transaction_results> next) {}

still uses:

app().get_method<incoming::methods::transaction_async>()(pretty_input, true, [this, next](const fc::static_variant<fc::exception_ptr, transaction_trace_ptr>& result) -> void{....
 
It is better to change to use 
 my->incoming_transaction_async_method
to make things be consistent.

**Comment by taokayan** [comment]
This is not really an issue as they're actually doing the same thing, just like some people use "unsigned int" while other people use "uint32_t".
