### ISSUE TITLE
Transaction broadcast to full node, but can not confirm by Bp？

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#5143]
Recently, we meet the errors like that our transaction has been successfully broadcasted to network through our full node, and get transaction hash back, but finally the transaction was not on chain.
Here is the transaction below, which was broadcast successfully but finally not  onchain:
`{
      "compression": "none", 
      "packed_context_free_data": "", 
      "packed_trx": "79ce635b60cf08701d1700000000010000000000ea30557015d289deaa32dd019074e55f1ff59fdc00000000a8ed323281029074e55f1ff59fdc00000000000000001e90e8ad982ad368341030555d4db7b23ba0129d0a998ab33b80a93a3aa2e94c4380a932c85d933145301d3ff560aaa84990a689b42a76955490d534ee986b3055104208c1386c3055a096c1d154753055301b9a744e833055104208411d8d3055c0299f2e1e9d3055405da6296aaa3055d07234aa21d43055e0b3dbe632ec30558055a2d325253155401dbc946735315580a9a24e21533155208471d3487a315590b13aead28c3155a0a5d30deb96315590e8adeab89b315570d5d6144db3315580683c581db73155508f34332bb73155508f622646b73155500f756ad2abaac6406fc5544d671aca1042a80753954de300", 
       "signatures":["SIG_K1_KafVxoBAfnWTJXdo2mFFgpQbQXNcNnbBKvUnJmBXxPjZ9Y3xn8YWA5XJFQ5kHVb4A8ttYbsrHLBppENfsrVfcEAixkRSi5"], 
      "tx_id": "a3a8fd10dc58b65472d85476770ac5e7eeca657ac9681708cfe9fedbf509a7a6"
  }`

The error occurs frequently, expecially  during cpu peak time, we wonder if the bps lost our transactions or missed the blocks？？

**Comment by taokayan** [comment]
The BP may not include your transaction to their new generated block if their block is already full. Also every block is reversible before confirmed by 2/3 of all the producers.

**Comment by brianjohnson5972** [comment]
If this happens during peak times, it may be because your transaction isn't getting into a block before it expires.
