### ISSUE TITLE
How eosio estimate the cost of CPU and NETWORK for one operation?

### ISSUE THREAD

**Issue by yyh1102** [EOSIO/eos#5146]
I have two questions about the cost estimation of CPU and NETWORK in eosio.

1. How eosio estimate the cost of CPU and NETWORK bandwidth when send an action?

2. Is the resource of CPU and NETWORK that an account holds through delegation used for every action or  for one transaction(including several actions)? 

Hope someone can give a answer. Thanks very much!

**Comment by taokayan** [comment]
CPU: depends on the actually time it takes on the corresponding producer node. It can be from 1us up to 30ms.
NETWORK: size of packed transaction plus some overhead (typically around 128 bytes for a transfer)

**Comment by yyh1102** [comment]
Maybe this issue should not be closed. So only if an action executed can we know the actual executing time, and should the producer node drop the result of this execution, and said CPU exceed limit?

**Comment by taokayan** [comment]
> Maybe this issue should not be closed. So only if an action executed can we know the actual executing time, and should the producer node drop the result of this execution, and said CPU exceed limit?

the executing time is only finalised when a transaction has been put into a block. BP will drop the result if a txn exceeds the max billable cpu time, in the case the txn will not be included in the block.

**Comment by yyh1102** [comment]
That means, when we delegate some EOS in CPU time, EOSIO will check the previous execution time of txns from this account, and determine whether we have enough CPU resource or not to execute this txn? 

My question is that how EOSIO determines whether we have enough CPU resource delegated by EOS to execute a transaction?

**Comment by jgiszczak** [comment]
Correct, the system checks how much previous execution time has been used for the account.  If the remaining allotment is too small for the transaction it has just attempted, it rejects it.  The calculation is [here](https://github.com/EOSIO/eos/blob/0f6695cb8d31e3d2f318d1720e9d9ad23e1ce80d/libraries/chain/resource_limits.cpp#L94).  Network limits are calculated in the same function.

**Comment by yyh1102** [comment]
Thank you! @jgiszczak
