### ISSUE TITLE
Where do eos uses mongodb and what is stored where? what is shared_memory ? BP's have extra storage fields ? Solve my confusion

### ISSUE THREAD

**Issue by yashvadhvani** [EOSIO/eos#5150]

**Comment by jgiszczak** [comment]
Account information, contract code, and contract data are stored in RAM, which uses boost shared memory for automated back up to disc.

Mongodb is an entirely optional storage choice, available for the purpose of enabling queries of system data in an interface familiar to many developers.  It also allows rapid searching of the chain using indexes not available by default in chain nodes.

A SQL db plugin is in development which is optional just as the Mongo plugin is.  It will allow use of any SQL database supported by libsoci, for the same reasons as the Mongo plugin.
