### ISSUE TITLE
nodeos signature-provider fails for KEOSD provider-type

### ISSUE THREAD

**Issue by jplanc** [EOSIO/eos#5151]
From config.ini:
```
signature-provider = EOS5hCncQzo7TJqcv3Xjwwf3PvuEoCW6RrU5zcXzYv8kJnRUoLd3n=KEOSD:http://127.0.0.1:8900
```

After confirming that cleos can successfully access that key from keosd at that url, running nodeos v1.1.4 results in:
```
2018-08-10T13:57:55.862 thread-0   producer_plugin.cpp:677       plugin_startup       ] producer plugin:  plugin_startup() end
2018-08-10T13:57:56.000 thread-0   producer_plugin.cpp:1183      maybe_produce_block  ] 11 eof_exception: End Of File
unexpected end of file
    {}
    thread-0  json.cpp:434 variant_from_stream

    {"str":""}
    thread-0  json.cpp:460 from_string
```

**Comment by spoonincode** [comment]
You need to use the full URL, so
`signature-provider = EOS5hCncQzo7TJqcv3Xjwwf3PvuEoCW6RrU5zcXzYv8kJnRUoLd3n=KEOSD:http://127.0.0.1:8900/v1/wallet/sign_digest`

**Comment by jplanc** [comment]
This was fixed by https://github.com/EOSIO/fc/commit/dd7e8e231e3486efc655fdd40de1356b6c67b00e
