### ISSUE TITLE
Using Table.

### ISSUE THREAD

**Issue by asvirido** [EOSIO/eos#516]
# I have two contracts.

First - `player` -( this is contract, creates table and init variable "name" and win = 0.

Second contract -`mydice`- must change variables in table accounts which contain variables.

The contract player can change itself. But contract number two  can not change table in accounts.

**Comment by asvirido** [comment]
[smart_contracts.tar.gz](https://github.com/EOSIO/eos/files/1341227/smart_contracts.tar.gz)

**Comment by asvirido** [comment]
https://github.com/asvirido/eos-contracts

**Comment by asvirido** [comment]
https://github.com/asvirido/eos-contracts

**Comment by learnforpractice** [comment]
I think your problem was caused by the following code in Win method:
requireNotice( name );
requireAuth( name );


Remove the above code and have another try, that shall work.


mydice.cpp

  void  Gameplay(const mydice::Game& game) {
player::Win(game.one);
}

Player.hpp
  void    Win( AccountName name ) {
    requireNotice( name );
    requireAuth( name );
      
    auto var = getAccount( name );
      
    var.win += 1;
    player::Store( var );
  //  player::Update( var );
  }

**Comment by learnforpractice** [comment]
Also you need to call requireAuth in apply

> 

   void apply(uint64_t code, uint64_t action)  {
      if ( code == N( mydice ) )
        if ( action == N( game ) ) {
> 
> 	requireAuth( N(mydice) );

          mydice::Gameplay( currentMessage< mydice::Game >() );
        }
    }

**Comment by asvirido** [comment]
@learnforpractice 
I delete code in player.hpp 
```
    requireNotice( name );
    requireAuth( name );
```
And add code in mydice.cpp 
` requireAuth( N(mydice) ); `

It did not help(

**Comment by learnforpractice** [comment]
Hmm, then you should provide more information.
Tell me the commands you ran and the output you got on the eosd.

**Comment by asvirido** [comment]
@learnforpractice 
Commands and output on eosc. 
[log.txt](https://github.com/EOSIO/eos/files/1362934/log.txt)

**Comment by asvirido** [comment]
player variable had to be changed to 1.

**Comment by asvirido** [comment]
@learnforpractice 
 mind if, i use one wallet and one pair keys?

**Comment by learnforpractice** [comment]
add
    account.name = owner;
to getAccount, account will not be changed if load_i64 failed, and in constructor you set name to current code:
        Account() {
            name = currentCode();
            win = 0;
        }
That’s the reason why win is always 0.

  inline    Account getAccount( AccountName owner ) {
    Account   account;
    account.name = owner;
    Accounts::get(owner, currentCode(), N( account ), &account, sizeof(account) );
    return ( account );
  }

Also you need to modify your mydice.abi:
{
  "types": [{
      "newTypeName": "AccountName",
      "type": "Name"
    }
  ],
  "structs": [{
  "name": "players",
    "fields": {
        "one": "AccountName"
        "two": "AccountName"
    }
  },{
  "name": "void"
  },
  {
  "name": "account",
    "fields": {
        "name": "AccountName"
        "win": "UInt64"
    }
  }
  ],
  "actions": [{
    "action": "game", "type": "players"
    },{
    "action": "load", "type": "void"
    }
  ]
  "tables": [{
      "table": "account",
      "type": "account",
      "indextype": "i64"
    }
  ]
}

And you need to change your command from:

./eosc get table player player account

to

./eosc get table player mydice account




Hope that can solve your problem.

**Comment by asvirido** [comment]
Now mydice once changes the value in the table and does not want to anymore=)
But already thanks.

**Comment by learnforpractice** [comment]
I can’t quite understand what you said, but I have tested it and It works on my side.

**Comment by asvirido** [comment]
Could you try to run it more than once?

**Comment by asvirido** [comment]
The "win" variable need to become greater then 1

**Comment by learnforpractice** [comment]
Yes,it increased by one after push the message.

**Comment by asvirido** [comment]
I found an error.  
I use   `Accounts::get(owner, owner, N( account ), &account, sizeof(account) );`
but need
`Accounts::get(owner, currentCode(), N( account ), &account, sizeof(account) );`.
Thanks

**Comment by learnforpractice** [comment]
Good to hear that.
