### ISSUE TITLE
Why 21 producers why not 50? 

### ISSUE THREAD

**Issue by yashvadhvani** [EOSIO/eos#5167]
# Why does eos has 21 producers why not more or less please answer.
## what are producers actually and if i am running a private node on my machine. Is there any need of producers? if yes tell me how can i make some account a producer? Thank you.

**Comment by heifner** [comment]
Please take a look at: https://developers.eos.io
Or ask your question on: https://eosio.stackexchange.com/
GitHub issues are for issues, not q/a.
