### ISSUE TITLE
Create Account on mainnet

### ISSUE THREAD

**Issue by gittempo** [EOSIO/eos#5168]
I have setup a EOS node on ubuntu server.

Now while creating account i have seen, this command has to be used

`cleos -u http://IP-HERE:8888 system newaccount --stake-net "0.1000 EOS" --stake-cpu "0.1000 EOS" --buy-ram-kbytes 8 eosio myDesiredAccountName Public key Public key`

my question is, Here account system is creating newaccount. So this system account must have some EOS balance to pay money that is written into the above command?

This system command could be on any exchange or wallet out side of my node?

Im stucked here because im not able to create my account.

One more question, if i create account successfully then where in EOS blockchain network / explorer i can check if account actually exists into the blockchain?

**Comment by odarboe** [comment]
@gittempo you can use https://zeos.co/ to check whether a name is available.
The verify whether you account is created type the new name of the account to any eos block explorer search function. e.g.
![image](https://user-images.githubusercontent.com/1871493/44000335-31181758-9e1e-11e8-9bf6-0915e87b294d.png)

**Comment by gittempo** [comment]
Wowww thanks for nice working links.

Can you write some words regarding this command in my question?

`cleos -u http://IP-HERE:8888 system newaccount --stake-net "0.1000 EOS" --stake-cpu "0.1000 EOS" --buy-ram-kbytes 8 eosio myDesiredAccountName Public key Public key`

**Comment by gittempo** [comment]
If i create an account from [https://zeos.co](url) for example testtesttest is account name

then while using this command, i should use test account and its public key as owner? and then we are done with main net? BTW what main net URL should be used for this purpose?

`cleos -u http://IP-HERE:8888 system newaccount --stake-net "0.1000 EOS" --stake-cpu "0.1000 EOS" --buy-ram-kbytes 8 testtesttest myDesiredAccountName TestTestTestPublicKey Public key`

**Comment by odarboe** [comment]
I think you can use this command to test if your node is connected to mainnet. Since we are running a p2p network.
`cleos --url http://mainnet.eoscalgary.io:80 `

**Comment by gittempo** [comment]
i will try and update here :-)

**Comment by dixia** [comment]
closed as no follow up. for this kind of question eosio stack exchange is a better place

**Comment by kulakovao** [comment]
The most useful link in this thread. 
https://mywish.io/eos-token
Quick account creation.
