### ISSUE TITLE
Occured error when set contract eosio.token

### ISSUE THREAD

**Issue by vincentwang0736** [EOSIO/eos#5173]
When I try to set contract eosio.token,I got these error:

> Reading WAST/WASM from ../../contracts/eisio.token/eisio.token.wast...
> 1421434ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)
> !wast.empty(): no wast file found ../../contracts/eisio.token/eisio.token.wast

Then I found this topic:
https://github.com/EOSIO/eos/issues/2838
It seems like that I can use this command to solve my problem:
eosiocpp -o contracts/eosio.token/eosio.token.wast contracts/eosio.token/eosio.token.cpp
But I didn't found the file:eosio.token.cpp, I only found eosio.token.cpp.bc

So anyone can help me or give me some advice? Thanks a lot!

**Comment by taokayan** [comment]
if you run "eosio_build.sh" the wast file will be automatically built into <EOSdir>/build/contracts/eosio.token/eosio.token.wast
eosiocpp is not required for this.

**Comment by taokayan** [comment]
Closed as no updates.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
