### ISSUE TITLE
why the transfer need ram

### ISSUE THREAD

**Issue by williamleecn** [EOSIO/eos#5176]
simple transfer to account(not contract) need 4k RAM??

```
    {"account":"xxxx","needs":4214,"available":4050}
    thread-0  resource_limits.cpp:184 verify_account_ram_usage
```

**Comment by taokayan** [comment]
The transfer action needs RAM only when the receiver doesn't have any EOS. In this case the balance row is created and the corresponding RAM is billed by the transferrer.

**Comment by wuyahuang** [comment]
If you try to transfer EOS or any other currency to someone, and he did't have it before, then the currency contract need to create a new record to table for him. and yes, you will need to pay for the RAM, because the table of contract are store in the RAM.
