### ISSUE TITLE
Switch from testnet to mainnet

### ISSUE THREAD

**Issue by gittempo** [EOSIO/eos#5177]
Anyone point me to a document that explains clearly. How to switch from testnet to mainnet and how to check if my node is running on testnet and mainnet

**Comment by williamleecn** [comment]
run cleos get info
check chain_id was aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906

**Comment by gittempo** [comment]
i get his response chain_id is different

> 
{
  "server_version": "40a20769",
  "chain_id": "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f",
  "head_block_num": 2538894,
  "last_irreversible_block_num": 2538893,
  "last_irreversible_block_id": "0026bd8d6f1f8e8f7ea47f11502d488d2a0a86a04c8bd89d0503bc11fc77e33b",
  "head_block_id": "0026bd8e4fb6af2f7e914de0464ee2e06733ffb50487337d46e5deb7985deea0",
  "head_block_time": "2018-08-12T13:15:26.500",
  "head_block_producer": "eosio",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576
}

**Comment by taokayan** [comment]
This is what I got from mainnet using  ```./cleos -u https://eu1.eosdac.io:443 get info```
{
  "server_version": "2d3bb003",
  "chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
  "head_block_num": 10841760,
  "last_irreversible_block_num": 10841428,
  "last_irreversible_block_id": "00a56d54dc95ac21360b7114cc6f515e2122f59123c18987184d8cf95a2e8062",
  "head_block_id": "00a56ea014e38ab89fa5bf3793e86021cfe5a8539eeb7141b285e0683dff162c",
  "head_block_time": "2018-08-13T01:51:58.500",
  "head_block_producer": "eosswedenorg",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576
}

**Comment by gittempo** [comment]
@taokayan with your command it means, We are connected to main net via this URL https://eu1.eosdac.io:443 and this is not our own node. Its third party node?

**Comment by halsaphi** [comment]
Will raise this as required update to documentation.
