### ISSUE TITLE
Error when compile smart contract from skeleton

### ISSUE THREAD

**Issue by rjkz808** [EOSIO/eos#5180]
So, i run:
```
$ eosiocpp -n hello
created hello from skeleton
$ cd hello
$ eosiocpp -o hello.wast hello.cpp
hello.cpp:1:10: fatal error: 'eosiolib/eosio.hpp' file not found
#include <eosiolib/eosio.hpp>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```
I've build EOS from it sources (1.1.4), and I run it on the Ubuntu 16.04 subsystem on Windows 10
Can anyone help?

**Comment by taokayan** [comment]
Please test with cdt.  If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
