### ISSUE TITLE
current name bidding procedure is normal? or not?

### ISSUE THREAD

**Issue by tiboong** [EOSIO/eos#5181]
at that closed issue #5140 , oranke said the current name bidding procedure has critical problem.

```$ cleos get table eosio eosio namebids -l 5 --index 2 --key-type i64
{
"rows": [{
  "newname": "app",
  "high_bidder": "f2poolshenyu",
  "high_bid": -275000001,
  "last_bid_time": "1533287763000000"
},{
  "newname": "ex",
  "high_bidder": "gm3denbwguge",
  "high_bid": 26660000,
  "last_bid_time": "1533739098000000"
},{
  "newname": "pra",
  "high_bidder": "g44dqnygenes",
  "high_bid": 22000001,
  "last_bid_time": "1533530080000000"
},{
  "newname": "games",
  "high_bidder": "loveshaoxing",
  "high_bid": 20190000,
  "last_bid_time": "1533437030000000"
},{
  "newname": "dex",
  "high_bidder": "gezdmnbtg4ge",
  "high_bid": 17000000,
  "last_bid_time": "1532905015500000"
}
],
"more": true
} 
```

as the bidding closed, the bidder 'f2poolshenyu' ready to get the name 'app' but he(or she) didn't create the name. so others have to wait endlessly until 'f2poolshenyu' creating the name 'app'.

@taokayan said 'This is the current behavior....' and he closed that issue #5140

but I want to hear what other guys talk about this issue.

**Comment by wanderingbort** [comment]
The releases of that contract are tracked in the [contracts repo](https://github.com/EOSIO/eosio.contracts/) .  A [fix for this issue](https://github.com/EOSIO/eosio.contracts/releases/tag/v1.1.1) has been release for 19 days.  If you are participating in a EOSIO based blockchain that has not adopted the fix, then you should submit an issue to whomever operates that chain.
