### ISSUE TITLE
eosio produce block end

### ISSUE THREAD

**Issue by wypsanity** [EOSIO/eos#5182]
2098548ms thread-0   http_plugin.cpp:440           add_handler          ] add api url: /v1/wallet/sign_transacti
on
2098548ms thread-0   http_plugin.cpp:440           add_handler          ] add api url: /v1/wallet/unlock
2098548ms thread-0   producer_plugin.cpp:580       plugin_startup       ] producer plugin:  plugin_startup() beg
in
2098548ms thread-0   producer_plugin.cpp:595       plugin_startup       ] Launching block production for 1 produ
cers at 2018-08-13T00:34:58.548.
2098664ms thread-0   producer_plugin.cpp:607       plugin_startup       ] producer plugin:  plugin_startup() end

**Comment by wypsanity** [comment]
My scene is as follows:
I have a eosio node,it is my first node.At the beginning, only the eosio block was produced. Now I use the other two nodes to connect to the eosio node, and after voting to become the producer, then one node produces the block. When the two nodes are not connected, my eosio node cannot produce blocks, resulting in Unable to access. In order to prevent this, I hope that when the other two nodes are not connected, my eosio node can produce blocks, what do I need to do?Sir.

**Comment by taokayan** [comment]
Have you enabled ```enable-stale-production = true``` in your config? by default it's set to false.

**Comment by wypsanity** [comment]
I have added enable-stale-production = true

**Comment by taokayan** [comment]
Ok. I guess you also need to add 
```producer-name = eosio``` and
```signature-provider = EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3```

**Comment by wypsanity** [comment]
enable-stale-production = true
producer-name = eosio
signature-provider = EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
I have added all three，sir
 @ 2018-08-13T02:01:03.500 signed by initb [trxs: 0, lib: 8710, conf: 0, latency: 3 ms]
64003ms thread-0   producer_plugin.cpp:294       on_incoming_block    ] Received block 605bc7bce769180b... #8712
 @ 2018-08-13T02:01:04.000 signed by initb [trxs: 0, lib: 8711, conf: 0, latency: 3 ms]
64507ms thread-0   producer_plugin.cpp:294       on_incoming_block    ] Received block ce607342639e3093... #8713
 @ 2018-08-13T02:01:04.500 signed by initb [trxs: 0, lib: 8712, conf: 0, latency: 7 ms]
64930ms thread-0   net_plugin.cpp:2190           operator()           ] Peer 127.0.0.1:9877 - c19abf2 closed con
nection
79773ms thread-0   net_plugin.cpp:1970           connect              ] host: 127.0.0.1 port: 9877
79773ms thread-0   net_plugin.cpp:2012           operator()           ] connection failed to 127.0.0.1:9877: Con
nection refused
109773ms thread-0   net_plugin.cpp:1970           connect              ] host: 127.0.0.1 port: 9877
109774ms thread-0   net_plugin.cpp:2012           operator()           ] connection failed to 127.0.0.1:9877: Co
nnection refused

**Comment by wypsanity** [comment]
bnet-endpoint = 0.0.0.0:4321
bnet-follow-irreversible = 0
bnet-no-trx = false
bnet-peer-log-format = ["${_name}" ${_ip}:${_port}]
blocks-dir = "blocks"
chain-state-db-size-mb = 1024
reversible-blocks-db-size-mb = 340
contracts-console = true
filter-on = *
https-client-validate-peers = 1
http-server-address = 127.0.0.1:8888
access-control-allow-origin = *
access-control-allow-credentials = false
max-body-size = 1048576
verbose-http-errors = true
http-validate-host = false
p2p-listen-endpoint = 127.0.0.1:9876
p2p-peer-address = 127.0.0.1:9877
p2p-max-nodes-per-host = 10
agent-name = "EOS Test Agent"
allowed-connection = any
max-clients = 25
connection-cleanup-period = 30
network-version-match = 0
sync-fetch-span = 100
max-implicit-request = 1500
use-socket-read-watermark = 0
peer-log-format = ["${_name}" ${_ip}:${_port}]
enable-stale-production = true
pause-on-startup = false
max-transaction-time = 3000
max-irreversible-block-age = -1
producer-name = eosio
signature-provider = EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
keosd-provider-timeout = 50
txn-reference-block-lag = 0
wallet-dir = "."
unlock-timeout = 9000
plugin = eosio::chain_api_plugin
plugin = eosio::net_api_plugin
plugin = eosio::wallet_api_plugin
plugin = eosio::chain_plugin
plugin = eosio::history_plugin
plugin = eosio::history_api_plugin
plugin = eosio::http_plugin
plugin = eosio::net_plugin
plugin = eosio::producer_plugin
plugin = eosio::wallet_plugin
Sir,this is my all config.

**Comment by wuyahuang** [comment]
Just FYI. 
[https://github.com/meet-one/Testnet/blob/master/how-to-set-up-testnet.md](how-to-set-up-testnet)
