### ISSUE TITLE
Using eosio_build.sh Script Compilation failed.

### ISSUE THREAD

**Issue by 401825317** [EOSIO/eos#5183]
os:centos 7
![image](https://user-images.githubusercontent.com/19526136/44010027-752812e4-9ee2-11e8-8c9c-5863fa6f9055.png)
Help, thank you.

**Comment by 401825317** [comment]
I deleted RM -rf /root/opt/cmake/cmake-3.10.2.
Try compiling again
![image](https://user-images.githubusercontent.com/19526136/44010126-1bcb0ff2-9ee3-11e8-8a78-c75373268d4f.png)

**Comment by 401825317** [comment]
![image](https://user-images.githubusercontent.com/19526136/44010218-bfb9716c-9ee3-11e8-827d-b7ff5c9533cc.png)

**Comment by lazaridiscom** [comment]
See the message:

> Your system must have 7 or more Gigabytes of physical memory installed. Exiting now.

Just get a machine with 8GB and you should be fine.

**Comment by 401825317** [comment]
Thank you. I have removed this judgement in script files, not for this reason.
