### ISSUE TITLE
signing transactions without eosjs/eosjs-ecc (in c++)

### ISSUE THREAD

**Issue by elwyos** [EOSIO/eos#5188]
How does one derive the signature that clients (like eosjs) use to sign transactions? I tried the following:

```sig = secp256k1(privateKey, sha256(chain_id + packed_transaction + sha256(contextFreeData)))```

but the sig output I see in the json has the prefix SIG_K1 and even without that, it's longer than the base58 encoded version of what I outputted. Not only that, the results are different.

Would be keen to hear if anyone knows the secret sauce

**Comment by taokayan** [comment]
The signatures can vary due the to nature of ecc algorithm. Please ask in eosio.stackexchange.com if you have further questions.

**Comment by lucgerrits** [comment]
@elwyos Did you asked the question on stackexchange ? I can't find a related question to this one on there.
PS: I'm also trying to send transactions using only C++ .
