### ISSUE TITLE
eosio_build issue

### ISSUE THREAD

**Issue by xiaoxiaoleo** [EOSIO/eos#5189]
root@test-1:~/eos# ./eosio_build.sh  
	Beginning build version: 1.2
	Mon Aug 13 08:28:43 UTC 2018
	User: root
	git head id: 4f4e5c225afa4d4e82cb8283074d8311a0178887
	Current branch: master

	ARCHITECTURE: Linux

	OS name: Ubuntu
	OS Version: 16.04
	CPU speed: 2494.224Mhz
	CPU cores: 2
	Physical Memory: 7983 Mgb
	Disk install: /dev/vda1
	Disk space total: 39G
	Disk space available: 20G

	Checking for installed dependencies.

	Package clang-4.0 found.
	Package lldb-4.0 found.
	Package libclang-4.0-dev found.
	Package cmake found.
	Package make found.
	Package automake found.
	Package libbz2-dev found.
	Package libssl-dev found.
	Package libgmp3-dev found.
	Package autotools-dev found.
	Package build-essential found.
	Package libicu-dev found.
	Package python2.7-dev found.
	Package python3-dev found.
	Package autoconf found.
	Package libtool found.
	Package curl found.
	Package zlib1g-dev found.
	Package doxygen found.
	Package graphviz found.

	No required dpkg dependencies to install.

	Checking boost library installation.
	Boost found at /root/opt/boost.

	Checking MongoDB installation.
	MongoDB configuration found at /root/opt/mongodb/mongod.conf.

	Checking MongoDB C++ driver installation.
	Mongo C++ driver found at /usr/local/lib/libmongocxx-static.a.

	Checking secp256k1-zkp installation.
	secp256k1 found @ /usr/local/lib.

	Checking for LLVM with WASM support.
	WASM found at /root/opt/wasm/bin.

>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOSIO

>>>>>>>> CMAKE_BUILD_TYPE=Release
>>>>>>>> ENABLE_COVERAGE_TESTING=false
>>>>>>>> DOXYGEN=false

-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
-- Configuring EOSIO on Linux
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using 'SYS' as CORE symbol name
-- Using 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV' as public key for 'eosio' account
-- Using WASM clang => /root/opt/wasm/bin/clang
-- Using WASM llc => /root/opt/wasm/bin/llc
-- Using WASM llvm-link => /root/opt/wasm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Configuring fc to build on Unix/Apple
-- zlib found
-- Configuring Builtins
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   unit_test_framework
--   locale
-- Configuring ChainBase on Linux
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   program_options
--   unit_test_framework
--   locale
-- Configuring AppBase on Linux
-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: /usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-lc;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: /usr/local/lib/libmongocxx-static.a;/usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-lc;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread;/usr/local/lib/libmongoc-static-1.0.a;/usr/local/lib/libbson-static-1.0.a;-lc;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;rt;/usr/lib/x86_64-linux-gnu/libz.so;resolv
-- Git commit revision: 4f4e5c22
-- Git commit revision: 4f4e5c22
-- Git commit revision: 4f4e5c22
-- Configuring done
-- Generating done
-- Build files have been written to: /root/eos/build
[  1%] Built target binaryen
[  1%] Built target wasm
[  1%] Built target ast
[  1%] Built target asmjs
[  2%] Built target cfg
[  5%] Built target passes
[  6%] Built target support
[  6%] Built target emscripten-optimizer
[  6%] Built target builtins
[ 29%] Built target softfloat
[ 29%] Built target chainbase
[ 29%] Built target Platform
[ 30%] Built target appbase
[ 32%] Built target libc++
[ 32%] Built target eosiolib
[ 70%] Built target libc
[ 71%] contract...
[ 71%] Built target copy_skeleton_contract
[ 71%] Built target identity_common
[ 72%] Built target identity_interface
[ 72%] Built target print_floats
[ 72%] Built target eosio-s2wasm
[ 72%] Built target chainbase_test
[ 72%] Built target Logging
[ 72%] Built target appbase_example
[ 72%] Built target IR
[ 73%] Built target Runtime
[ 75%] Built target WASM
[ 75%] Built target Emscripten
[ 75%] Built target WAST
[ 76%] Built target wavm
[ 76%] Built target Test
[ 76%] Built target Disassemble
[ 76%] Built target eosio-wast2wasm
[ 80%] Built target fc
[ 80%] Generating textual assembly eosio.bios.s
/root/opt/wasm/bin/llc: : error: unable to get target for 'wasm32', see --version and --triple.
contracts/eosio.bios/CMakeFiles/eosio.bios.dir/build.make:82: recipe for target 'contracts/eosio.bios/eosio.bios.s' failed
make[2]: *** [contracts/eosio.bios/eosio.bios.s] Error 1
CMakeFiles/Makefile2:4372: recipe for target 'contracts/eosio.bios/CMakeFiles/eosio.bios.dir/all' failed
make[1]: *** [contracts/eosio.bios/CMakeFiles/eosio.bios.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 80%] Generating textual assembly simple.token.s
/root/opt/wasm/bin/llc: : error: unable to get target for 'wasm32', see --version and --triple.
contracts/simple.token/CMakeFiles/simple.token.dir/build.make:82: recipe for target 'contracts/simple.token/simple.token.s' failed
make[2]: *** [contracts/simple.token/simple.token.s] Error 1
CMakeFiles/Makefile2:2411: recipe for target 'contracts/simple.token/CMakeFiles/simple.token.dir/all' failed
make[1]: *** [contracts/simple.token/CMakeFiles/simple.token.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by lazaridiscom** [comment]
sometimes it helps to simply rerun the script. if it fails again, try to 

```bash
sudo apt update
sudo apt upgrade
rm -rf build
./eosio_build.sh
```

If available to you, you can try additionally on ubuntu 18.04

**Comment by lazaridiscom** [comment]
try the latest 1.2.0 (please close this issue if it works for you).

**Comment by xiaoxiaoleo** [comment]
I rebuild llvm, it's works then.
