### ISSUE TITLE
Implement string class

### ISSUE THREAD

**Issue by andriantolie** [EOSIO/eos#519]
Implement string class that covers the following:
1. A constructor that remembers ownership of memory
2. If memory is owned that it is reference counted
3. Index operator

**Comment by bytemaster** [comment]
The vast majority of use cases will involve:

1. reading a packed record or message 
2. unpacking the record or message

99% of the time the string will be a sub-part of a buffer previously allocated.

This means the string class should have a pointer to the base memory segment, an offset, and a size.

The base memory segment can be reference counted.

Copying a string should just increment the count on the base memory segment
Destroying a string should decrement the count on the base memory segment

Copying data / strings will quickly consume our limited memory.

**Comment by andriantolie** [comment]
I made a pull request for this. It will be great if you can have some time to take a look on this. Thanks!  https://github.com/EOSIO/eos/pull/536
