### ISSUE TITLE
Error 3081001: Transaction reached the deadline set due to leeway on account CPU limits

### ISSUE THREAD

**Issue by gittempo** [EOSIO/eos#5195]
While creating new account, Im getting this error

I got many links on internet for same issue but none of them provides solution.

Anyone can resolve this issue?

**Comment by odarboe** [comment]
@gittempo check whether you have stacked your tokens. Stacking the tokens will give you more CPU time and NET bandwith. I think this error occurs if your account does not have enough CPU time allocated to execute the specified transaction.

**Comment by gittempo** [comment]
@odarboe thanks for your reply.

How can i stack my tokens? What is the process?

this is my account information

`EOS Unstaked：3.5295 EOS
EOS Staked：0.02 EOS
EOS Value：18.25 USD



3.37 KiB/3.98 KiB Memory



0.00 us/258.00 us
CPU
Staked: 0.01 EOS
Unstaked: 0 EOS



0.00 bytes/6.66 KiB

Net
Staked: 0.01 EOS
Unstaked: 0 EOS

`

**Comment by odarboe** [comment]
@gittempo which platform have you so far? 
I like https://eostoolkit.io/  but first you have to install "[scatter](https://www.youtube.com/watch?v=6770ySYX_8Y)" on your browser. 

or use [Greymass ](https://www.reddit.com/r/eos/comments/8vh1wf/how_to_stake_eos_token/)which is a hot wallet.

**Comment by gittempo** [comment]
I have installed Greymass on my windows computer and im connected to my account and wallet is open.
What should i do now to stack? So i be able to create accounts on main net

Scatter is confusing thing

**Comment by odarboe** [comment]
Right. Check this out. https://www.youtube.com/watch?v=A2Dkw1qh0YM

**Comment by gittempo** [comment]
Thanks for the good video.
So i just have to buy CPU and Bandwidth to be able to create accounts?
How much EOS i should spend in CPU and Bandwidth to be able to create new accounts?

**Comment by gittempo** [comment]
@odarboe i bought 1 EOS's CPU and 1 EOS's Bandwidth and i was able to create account :-) thanks a lot for your help

**Comment by odarboe** [comment]
@gittempo  I was traveling back home. I don't think you had to buy . You already had 3 EOS in your account. You could have added 1 EOS for CPU and 1 EOS for NET and you will be left with 1 extra unstaked. But its still fine since you got it working. :) Great!
