### ISSUE TITLE
Transaction failed on bp node due to 'unstable cpu price'

### ISSUE THREAD

**Issue by cluestudio** [EOSIO/eos#5207]
Mainnet CPU resource is very unstable. 
(Because of “WE LOVE BM” by "blocktwitter" and "chaintwitter" accounts.)
"cpu_limit.max" value changes rapidly. 

When I pushed traction to some node, that node approved my transaction. But when my transaction moved to the bp node, it could fail, if the 'cpu_limit.max' was reduced at that time. 

And it happens too much now on MainNet. Currently, even though the first node has approved a transaction, the client cannot be sure of success or failure. 

This behavior looks like **fork issue** which occurs between the first node and bp node who has the turn to produce.

I think at least when the first node approved a transaction, then bp node should not check the CPU available time.

**Comment by taokayan** [comment]
This is by design, because any seed node can be malicious, and anyone can run a seed node and accept all his own transactions. Therefore, it's a responsibility for the BP node to verify again.
