### ISSUE TITLE
How to get the return value from the contract

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#5209]
Suppose the contract code is as follows

`
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>
using namespace eosio;
class hello : public eosio::contract {
  public:
      using contract::contract;

      /// @abi action 
      int add( account_name user ,int a, int b) {
         require_auth( user );
         return a+ b;
      }
};
EOSIO_ABI( hello, (add) )
`

**Comment by yashbhavsar007** [comment]
as per my knowledge eos cannot support **return**

**Comment by cppfuns** [comment]
@yashbhavsar007 
I am just giving an example, the effect that is similar to the most desired is this.

**Comment by yashbhavsar007** [comment]
@cppfuns I thought you were not aware about this..because you are at the same time asking about how to return value?...still not understand you have a question or you are giving suggestion ?

**Comment by cppfuns** [comment]
@wuyahuang  
What I have learned so far is that there is a need to exist a database, but there should be data redundancy problems. I hope that there is a better way. Thank you.

**Comment by cppfuns** [comment]
@yashbhavsar007
 I’m sorry, I’m lazy, I’ve written the question shortly in the title, and it’s really unfriendly to the way I ask questions.

**Comment by cppfuns** [comment]
https://www.bcskill.com/index.php/archives/969.html
