### ISSUE TITLE
Error 3120008: Key already exists

### ISSUE THREAD

**Issue by isTg** [EOSIO/eos#5211]
GuangdeMacBook-Pro:cleos tg$ ./cleos wallet import --private-key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
Error 3120008: Key already exists

**Comment by yashbhavsar007** [comment]
You got this because public key related to this private key is exist in your wallet...please check it using 
**cleos wallet keys**
it gives you list of public keys which already exists in your wallet.

**Comment by isTg** [comment]
@yashbhavsar007 thanks
