### ISSUE TITLE
3080004 tx_cpu_usage_exceeded: Transaction exceeded the current CPU usage limit imposed on the transaction

### ISSUE THREAD

**Issue by yashbhavsar007** [EOSIO/eos#5212]
I got this error on local noedeos can anyone know how to increase cpu limit on local nodeos ?

**Comment by odarboe** [comment]
Check this out #5195 You have to stake you token to CPU and NET.

**Comment by yashbhavsar007** [comment]
i am getting this error when performing transaction related to contract and i'm on local nodeos...still i need to stake token?

**Comment by odarboe** [comment]
@yashbhavsar007 I think you need to stake your tokens to use the CPU and NET. Staking gives you more cpu time and network bandwidth to perform transaction. 
I might be wrong but I look at the staking of tokens a replacement of transaction fees to use the network.

**Comment by yashbhavsar007** [comment]
@odarboe  thanks for reply i will try it...

**Comment by taokayan** [comment]
Due to the same code/logic applied on the EOS block chain, you need to stake for CPU & NET regardless of local node or mainnet.

**Comment by jacktang** [comment]
When I sync with mainnet, I get the same issue
```
2018-09-25T07:00:55.041 thread-0   controller.cpp:688            push_scheduled_trans ] 3080004 tx_cpu_usage_exceeded: Transaction exceeded the current CPU usage limit imposed on the transaction
billed CPU time (11027 us) is greater than the maximum billable CPU time for the transaction (8752 us)
    {"billed":11027,"billable":8752}
    thread-0  transaction_context.cpp:374 validate_cpu_usage_to_bill
```

My question is which accout should I need to stake CPU? @taokayan 
Thanks!

**Comment by odarboe** [comment]
You should create a new account. Buy eos and send it to this new account. Install and use eos-voter to stake your cpu and net. Make sure you have enough CPU staked (may be) at least 1 eos to avoid this error.

**Comment by jacktang** [comment]
@odarboe you mean the producer account?
