### ISSUE TITLE
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations

### ISSUE THREAD

**Issue by isTg** [EOSIO/eos#5215]
GuangdeMacBook-Pro:cleos tg$ ./cleos  -u http://api.main.alohaeos.com:80/ set contract eosio ../../../build/contracts/eosio.bios/ -p default

Reading WAST/WASM from ../../../build/contracts/eosio.bios/eosio.bios.wasm...
Using already assembled WASM...
Publishing contract...
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"default","permission":"active"}', but does not have signatures for it.

**Comment by wuyahuang** [comment]
Actually, you can't set a contract to eosio, because eosio has been resign to Top 21 BP.
You need to create a new account to deploy your contract, Take a look at here. 
https://developers.eos.io/eosio-cpp/docs/hello-world

**Comment by isTg** [comment]
@wuyahuang thanks very much
