### ISSUE TITLE
EOS integration with scatter

### ISSUE THREAD

**Issue by VtpVlan-oo7** [EOSIO/eos#5219]
how to do scatter wallet  integrate EOSIO , can anyone help ??

**Comment by odarboe** [comment]
@VtpVlan-oo7 Check this out https://steemit.com/eos/@ajose01/eos-and-scatter-part-1 if you want to integrate it at the web level using javascript.

**Comment by jgiszczak** [comment]
See the 'Signature Provider' section of the Readme.md at https://github.com/GetScatter/ScatterWebExtension

You will need [eosjs](https://github.com/EOSIO/eosjs) or [web3](https://github.com/ethereum/web3.js/) as well.
