### ISSUE TITLE
Can't run ./eosd

### ISSUE THREAD

**Issue by ioleksiu** [EOSIO/eos#523]
![image](https://user-images.githubusercontent.com/7544213/31015380-81d258f6-a528-11e7-9bae-7a655542a2a4.png)

**Comment by ioleksiu** [comment]
./eosd used to work
config.ini seems to be fine
enable-stale-production = true

**Comment by guanqun** [comment]
do you have the genesis.json put at the right place?

**Comment by ioleksiu** [comment]
@guanqun 
The problem was in trying to run ./eosd after after being suspended(ctrl + z).
But daemon was still running.
Fixed that by using fg command.
The problem is over. Thank your for feedback.

**Comment by jatinmehta420** [comment]
@ioleksiu I'm facing same issue sir, please help me out with the fg command syntax!

**Comment by rupaliathashcode** [comment]
hey @ioleksiu i want to know about your error. Is your error fixed?

**Comment by jatinmehta420** [comment]
@rupaliathashcode try with ./eosd --resync

**Comment by rupaliathashcode** [comment]
Thank you so much sir @jatinmehta420
