### ISSUE TITLE
eosio_assert write error message to console

### ISSUE THREAD

**Issue by Thomas55777** [EOSIO/eos#5240]
I wrote a contract with the following code:

```
    void printerr()
    {
        eosio_assert(1 == 2, "One is not equal to two.");
    }
```

If I push the action using cleos I do not receive the error message only a generic assert failed:
`Error 3050003: eosio_assert_message assertion failure`

I can see the error message from nodeos if I use --contracts-console.  Is there any way to see the error message using cleos or eosjs?

Thank you

**Comment by RuBAN-GT** [comment]
Did you find the answer? It will be useful for testing.

**Comment by RuBAN-GT** [comment]
https://github.com/EOSIO/eos/issues/4547 contain the answer: You need to use `--verbose-http-errors` for nodeos.
