### ISSUE TITLE
mongodb-filter-out issues on EOS docker v1.2.0 [help]

### ISSUE THREAD

**Issue by elnoxvie** [EOSIO/eos#5244]
**Issues**
I am trying to use a new filter options in mongodb plugin. However, this doesn't seem to work unfortunately. I am using docker EOS version v1.2.0. 

**Steps to produce:** 
Add the following entries to **config.ini**
mongodb-filter-out = eosio:onblock:

**Expected Result:** 
   eosio:onblock will no longer be shown in the mongodb transactions

Appreciated if anyone could help on this.

**Comment by chengevo** [comment]
`mongodb-filter-on` and `mongodb-filtr-out` only applies for `transaction_traces` and `action_traces` so far, which means will still populates `transactions` collection with entire transaction data in the blockchain.  You can find more info regarding current MongoDB plugin in this PR #5066 .
