### ISSUE TITLE
docker restart eosio-dev error

### ISSUE THREAD

**Issue by helperShang** [EOSIO/eos#5245]
```
13 St13runtime_error: database dirty flag s   │
│   et                                                                                                                                    │
│   rethrow database dirty flag set:                                                                                                      │
│       {"what":"database dirty flag set"}
```

**Comment by mauhcs** [comment]
I have the same issue

I ran this command:

docker run --rm --name eosio -d -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev  /bin/bash -c "nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false"

**Comment by taokayan** [comment]
try to add --delete

**Comment by jgiszczak** [comment]
The long form of the flag is `--delete-all-blocks` which does exactly as it says: it restarts your chain from scratch.  If you're using docker, change your docker shutdown time limit to 60 seconds.  The default limit is too short to allow a graceful shutdown, which corrupts the database.  Also be sure to shut down your nodeos docker before restarting your machine, again to prevent an abrupt shutdown that corrupts the database.    If you're not using docker, be sure to terminate nodeos only with `kill -2` or `kill -15`.  Never use `kill -9`.  `kill` with no signal argument defaults to a signal that is handled gracefully.
