### ISSUE TITLE
When importing a key pair into the wallet, the wallet is unlocked, but programe show the wallet is still not unlocked

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5250]
When importing a key pair into the wallet, the wallet is unlocked, but programe show the wallet is still not unlocked
![image](https://user-images.githubusercontent.com/11773000/44143609-ed87139a-a0b6-11e8-8bbf-8172fe7b072f.png)

**Comment by wanderingbort** [comment]
`--wallet-url` parameter needs to be part of the wallet unlock command.  It is likely that you have two versions of `keosd` running at this point: one listening to `8900` (the default) and one on `8899` your explicit setting in `cleos wallet import`.  I would suggest cleaning up the running keosd processes before proceeding.  Afterwards make sure you pass in the same `--wallet-url` to all cleos commands

**Comment by amActiveHello** [comment]
I only kept one keosd process, but I still get an error：
![image](https://user-images.githubusercontent.com/11773000/44184276-29bd0600-a141-11e8-9247-12f79af32ea3.png)
