### ISSUE TITLE
The docker-quickstart is broken (on https://developers.eos.io)

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#5252]
It works in v1.1.5 but not in v1.2.0 (latest as of now)...  The 1.2 container does not have the wallet_plugin or the wallet_api_plugin.

https://developers.eos.io/eosio-nodeos/docs/docker-quickstart

# steps to re-produce

The container does not start (check with `docker ps`) so this comment returns nothing:
```bash
docker logs --tail 10 eosio
```

To see the error, I replaced the docker run `-d` (daemon) with `-it` (interactive) then run just `bash` without the `-c` command.  Then ran the `-c` command in the interactive container:

```bash
$ docker run --rm --name eosio -ti -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev /bin/bash

root@2eacc395f349:/# nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false
2018-08-15T12:54:24.728 thread-0   main.cpp:131                  main                 ] /eos/libraries/appbase/application.cpp(309): Throw in function appbase::abstract_plugin &appbase::application::get_plugin(const string &) const
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: unable to find plugin: eosio::wallet_api_plugin
```

**Comment by heifner** [comment]
`wallet_plugin` and `wallet_api_plugin` is no longer supported in nodeos. Is there a reason you can't run keosd?

**Comment by wanderingbort** [comment]
@ericiles 

It looks like these are the paths that are searched for includes:
```
                                   -I /opt/eosio/contracts \
                                   -I /eos/contracts \
                                   -I /eos/contracts/libc++/upstream/include \
                                   -I /eos/contracts/musl/upstream/include \
                                   -I /eos/externals/magic_get/include \
                                   -I ${EOSIO_INSTALL_DIR}/include \
                                   -I${EOSIO_INSTALL_DIR}/include/libc++/upstream/include \
                                   -I${EOSIO_INSTALL_DIR}/include/musl/upstream/include \
                                   -I${BOOST_INCLUDE_DIR} \
```
the `/eos/` path comes from the build environment
the `EOSIO_INSTALL_DIR` is implied to be the directory of the eosiocpp script.   

@jcalfee please try to limit issues to a single problem, this issue is now tracking 2 issues: 
 - [ ] 1.2.0 does not support running the wallet plugin in nodeos anymore
 - [ ] 1.1.5/1.1.2 eosiocpp has bad search paths.

**Comment by jcalfee** [comment]
@heifner 
> Is there a reason you can't run keosd?
No reason.  Using keosd is fine.

**Comment by jurosh** [comment]
Also confused by current quickstart. Where to find `keosd` docker image ? :disappointed:

**Comment by dixia** [comment]
hi @jcalfee please check the latest page on developer portal. it got quite a lot update and should fix this issue. in case it is not, feel free to let us know via hotjar.
