### ISSUE TITLE
docker build   Fails

### ISSUE THREAD

**Issue by jmarca** [EOSIO/eos#526]
Docker build errors out trying to delete the eos files.  Following the README in the Docker directory to "build eos image," I cloned the code and then ran 

```
docker build -t eosio/eos -f Docker/Dockerfile .
```

The build failed with a slew of errors complaining about not being able to delete things.

The bad command is here:

https://github.com/EOSIO/eos/blob/3a34f3e8115a0e68dfd2cbd36683967362d73986/Docker/Dockerfile#L68

I'm new to Docker, but I've narrowed it down to the COPY command on lines above.  It seems the git clone stuff was axed in favor of copying the repo in directly.  However, as far as I can tell (again, I'm new to Docker), you can't use "rm" to remove files copied into the image with COPY.  I tried a few things, including the all-powerful `find /tmp/eos/* -delete`, which gave a more interesting error message but still failed. (The errors say things like "find: '/tmp/eos/.git/refs/tags': No such file or directory")

Reading the Docker docs, I can't find any mention anywhere of how to delete files that have been COPYied in.  Perhaps it is not considered *necessary* to remove these files?

Building with the `rm -rf` command deleted, the build works.  

Logging into the docker image with 

```
docker exec -i -t docker_eos_1 /bin/bash
```

I see that the /tmp/eos stuff is definitely there in the running image, but rm -rf and find . -type f -delete *still* won't delete the files.

Suggested fix is to delete the line https://github.com/EOSIO/eos/blob/3a34f3e8115a0e68dfd2cbd36683967362d73986/Docker/Dockerfile#L68 as well as the "\" on line 67.

In addition, I'd strongly suggest putting in a good [.dockerignore](https://docs.docker.com/engine/reference/commandline/build/#use-a-dockerignore-file) file so that the `.git` stuff is excluded. 

Alternately, comment out the COPY stuff and uncomment the git clone stuff, but maybe using the options 

* `--depth 1` 
* `--shallow-submodules`

(Note that the version of git in the Docker file does not support the --shallow-submodules option, so you would also have to upgrade that at the start of the Docker file)

**Comment by heifner** [comment]
Old issue. Docker has changed much since this was written.
