### ISSUE TITLE
I  have several genesis.json file , how can i sure which file dose nodes 's config file(~/.local/share/eosio/nodeos/config) seeds 。

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5269]
I  have several genesis.json file , how can i sure which file dose nodes 's config file(~/.local/share/eosio/nodeos/config) seeds 。
![image](https://user-images.githubusercontent.com/11773000/44182088-ef02a000-a137-11e8-8708-a6e91d9e0543.png)

**Comment by jgiszczak** [comment]
The current version of nodeos does not accept a genesis file in the config file at all.  If one is not specified on the command line, it uses the default internal genesis settings.  If you run `nodeos` without a `--genesis-json` argument, none of the files in your screenshot will be used.
