### ISSUE TITLE
v1.2.1: Is there some change for plugin configuration?

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#5270]
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: unable to find plugin: eosio::wallet_plugin

**Comment by heifner** [comment]
See release notes: https://github.com/EOSIO/eos/releases/tag/v1.2.0
wallet_plugin is no longer allowed in nodeos. Run a keosd instead.

**Comment by yankunsam** [comment]
So for my private network. I need create a wallet and import the eosio's privatekey and then run the nodeos? If this, How does nodeos knows the keosd's url and port? Thanks!

**Comment by heifner** [comment]
See `./cleos --help` keosd url and port can be specified on the command line. Or you can run keosd on cleos's expected default port for it: `./keosd --data-dir data --http-server-address 127.0.0.1:8900`
