### ISSUE TITLE
How to restart EOS private chain? (when all BPs are lost)

### ISSUE THREAD

**Issue by lpx1988** [EOSIO/eos#5273]
I created an EOS private chain with 3 BPs, which in turn generated blocks. Due to unexpected reasons, all three BPs have stopped running. Is there any way to restart this EOS private chain? (Keep all block data that has been generated)

**Comment by jgiszczak** [comment]
Yes.  On one of the BP nodes, while retaining data and config-dir flags, start with the `-e` flag.  It may be necessary to start specifically the node running the producer which is supposed to take the current slot.  The shotgun approach is to start every node with the addition of `-e`, then restart them one by one without it once the network is synched again.

If the unexpected reasons resulted in unclean shutdowns, also include `--replay-blockchain`.  Depending on the length of your chain, this may take some time.  If `--replay-blockchain` fails, use `--hard-replay-blockchain`.  This will make move your old block log out of the way and attempt to build a new one using the old one as a starting point.  Be aware you'll need the disk space to store 6 copies of your chain for this to work.

There is a defect where stubborn producers will not take their turns as expected, even with `-e`.  We've seen this work itself out simply by waiting 15-20 minutes.  Investigations into a permanent fix are ongoing.

**Comment by lpx1988** [comment]
Thank  you @jgiszczak

**Comment by SaketN** [comment]
@lpx1988 Do you have any blog where you have explained the private chain creation process step by step? If not please mail me on [saketnalegaonkar@gmail.com](mailto:saketnalegaonkar@gmail.com)
