### ISSUE TITLE
When I specify --walet-url for cleos, execute "set set contract", indicating that the wallet is not unlocked, but only one keosd is running.

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5274]
1、When I specify --walet-url for cleos, execute "set set contract", indicating that the wallet is not unlocked, but only one keosd is running.
![image](https://user-images.githubusercontent.com/11773000/44196745-5c7df300-a16f-11e8-8aed-6487cbe9fcb5.png)
2、keosd process:
![image](https://user-images.githubusercontent.com/11773000/44197236-b16e3900-a170-11e8-8993-630091da369c.png)

**Comment by yashbhavsar007** [comment]
@amActiveHello still not able to set contract after unlocking wallet ?

**Comment by amActiveHello** [comment]
yes, it is.

**Comment by jgiszczak** [comment]
Try `ps aux | grep keosd`.  Without the `a` flag, ps won't show you processes created in another terminal.  Until you get a clean start without an `Address already in use` complaint, there is definitely another process using port 8900, and it's probably another `keosd`.
