### ISSUE TITLE
Mongodb plugin mongodb-block-state option

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [EOSIO/eos#5276]
using version 1.2 

```
cleos get info
..."server_version": "4da680bd" ....
````
set 
```
mongodb-block-state = false
mongodb-store-act-via-txtraces = false
```
restarted nodeos.
i still see number of documents in block_states and transaction_traces increasing.
why?

@ScottSallinen, @heifner

**Comment by ScottSallinen** [comment]
It sounds like you're using an old build (possibly Greymass's old production branch). In the latest version of the code, the configuration option names are different. Check out `nodeos --help`, as you probably want these:

``` 
--mongodb-store-blocks arg (=1)       Enables storing blocks in mongodb.
--mongodb-store-block-states arg (=1) Enables storing block state in 
--mongodb-store-transactions arg (=1) Enables storing transactions in mongodb.
--mongodb-store-transaction-traces arg (=1)  Enables storing transaction mongodb.
--mongodb-store-action-traces arg (=1) Enables storing action traces in mongodb.
```

**Comment by heifner** [comment]
Thanks @ScottSallinen

**Comment by Vasiliy-Bondarenko** [comment]
@ScottSallinen i took options from your post https://github.com/EOSIO/eos/pull/5043 :)
anyway - thanks for help.

another question - i would prefer a bit other data structure. how can i go about it?
what i need is transactions with some extra data from the blocks like block.producers, block.timestamp, etc.
and the same staff with actions possibly.
how can i do it?
