### ISSUE TITLE
3190002 fail to append block to the block log

### ISSUE THREAD

**Issue by eoline7** [EOSIO/eos#5278]
> 2018-08-16T08:24:35.066 thread-0   producer_plugin.cpp:1205      produce_block        ] Produced block 00000002557c4e04... #2 @ 2018-08-16T08:24:35.000 signed by eosio [trxs: 0, lib: 0, confirmed: 0]

> 2018-08-16T08:24:35.502 thread-0   producer_plugin.cpp:1205      produce_block        ] Produced block 0000000338048557... #3 @ 2018-08-16T08:24:35.500 signed by eosio [trxs: 0, lib: 2, confirmed: 0]

> 2018-08-16T08:24:36.015 thread-0   block_log.cpp:196             append               ] 3190002 block_log_append_fail: fail to append block to the block log
> Append to index file occuring at wrong position.
>     {"position":0,"expected":8}
>     thread-0  block_log.cpp:184 append

> 2018-08-16T08:24:36.035 thread-0   producer_plugin.cpp:1154      maybe_produce_block  ] 3190002 block_log_append_fail: fail to append block to the block log
> Append to index file occuring at wrong position.
>     {"position":0,"expected":8}
>     thread-0  block_log.cpp:184 append
> rethrow
>     {}
>     thread-0  block_log.cpp:196 append

> 2018-08-16T08:24:36.514 thread-0   block_log.cpp:196             append               ] 3190002 block_log_append_fail: fail to append block to the block log
> Append to index file occuring at wrong position.
>     {"position":0,"expected":8}
>     thread-0  block_log.cpp:184 append

> 2018-08-16T08:24:36.529 thread-0   producer_plugin.cpp:1154      maybe_produce_block  ] 3190002 block_log_append_fail: fail to append block to the block log
> Append to index file occuring at wrong position.
>     {"position":0,"expected":8}
>     thread-0  block_log.cpp:184 append
> rethrow
>     {}
>     thread-0  block_log.cpp:196 append

......(repeating)

What's wrong? Anybody who knows this, thinks.

**Comment by jgiszczak** [comment]
It looks like you have a very old block log with only a single block in it.  The format of the block log changed several times before the 1.0 release.  Add `--delete-all-blocks` once to your `nodeos` command line to start with a fresh chain in the release format.  If you restart `nodeos` after that first time, you should omit the `--delete-all-blocks` flag to retain your new chain.
