### ISSUE TITLE
INLINE_ACTION_SENDER cause multi_index table modification failed

### ISSUE THREAD

**Issue by Simbafa** [EOSIO/eos#5282]
The test is based on version 1.1.4.
Failed test case:
   1). 4 multi_index table operations, such as modify/emplace
   2). INLINE_ACTION_SENDER for eosio.token transfer action
   3). modify multi_index table data (**the modification is NOT applied**)
Succeed test case:
   1). 4 multi_index table operations, such as modify/emplace
   2). modify multi_index table data (**the modification is applied**)
   3). INLINE_ACTION_SENDER for eosio.token transfer action

For the test cases, the transaction is succeed.
Is there a request that INLINE_ACTION_SENDER operation MUST be the latest action?

**Comment by taokayan** [comment]
all inline actions are executed at the end of the original action, regardless of where you put it in.

**Comment by Simbafa** [comment]
I'm very sorry. I made a mistake.
The modification is applied.
But the data is modified by another auto-service call.
