### ISSUE TITLE
[HELP] cannot find actions in mongodb!

### ISSUE THREAD

**Issue by axaysingh** [EOSIO/eos#5283]
i had update to the v1.2.1 and everything is set but i had notice that in mongodb **actions** collection(table) is missing and other two new tables where added.

```
> use EOS
switched to db EOS
> show tables
account_controls
accounts
action_traces
block_states
blocks
pub_keys
transaction_traces
transactions
```
is something i am missing or doing wrong! any help :)

**Comment by heifner** [comment]
See #5066
