### ISSUE TITLE
How to connect with mainnet ?

### ISSUE THREAD

**Issue by yashbhavsar007** [EOSIO/eos#5284]
I have following questions:-
1) How to connect with mainnet? i want to deploy my contract over mainnet i don't have any eos account?
    I have seen so many videos to connect with mainnet but no one shows how to get an account on  
    mainnet to deploy smart contract. 
2) What changes are needed to done in config.ini file of nodeos ?

**Comment by odarboe** [comment]
@yashbhavsar007 You need to create an account. To connect to mainnet you need to find p2p-peers that are iand add them to your config.ini file. 
Run this to get a list of the BPs and add them to your config.ini file.
cleos -u http://api.eosnewyork.io  system  listproducers

**Comment by yashbhavsar007** [comment]
@odarboe how to create account ?

**Comment by lalitCodezeos** [comment]
@odarboe `cleos -u http://api.eosnewyork.io system listproducers` not working

**Comment by swang-b1** [comment]
> @odarboe `cleos -u http://api.eosnewyork.io system listproducers` not working

try this one:

cleos -u http://mainnet.eosamsterdam.net system listproducers
