### ISSUE TITLE
[1.2.1] ABI generation with "core_symbol.hpp"

### ISSUE THREAD

**Issue by Lucklyric** [EOSIO/eos#5285]
`eosiocpp -g XXXX.abi XXXX.hpp ` results `fatal error: 'eosiolib/core_symbol.hpp' file not found`.

Because` eosio.wasmsdk ` does not support abi-generation yet, if you also got above issue, there is one trick I am using seems to be working for me.

1. build and install `eosio.wasmsdk` 
2. Add `-I${EOSIO_WASMSDK_INSTALL_DIR}/include/` in function `generate_abi ` in file [https://github.com/Lucklyric/eos/blob/master/tools/eosiocpp.in](url)

You an define and check your `EOSIO_WASMSDK_INSTALL_DIR` at the beginning.

**Comment by 86chenjie** [comment]
can you write more detail?i'm struggling to deploy contracts with v1.2.1.

**Comment by Lucklyric** [comment]
@86chenjie @Dylan-Phoon 
I just did a test:
1. Remove `eosio.wasmsdk `include path (in may case it is "/usr/local/eosio.wasmsdk/include") from `generate_abi`
2. ` ./eosio_build.sh` then sudo `./eosio_install.sh`
3. `eosiocpp -g`  got error. 
4. Add includ path back 
5. ` ./eosio_build.sh` then sudo `./eosio_install.sh`
6. `eosiocpp -g`  back to work. 

You can check the file diff here [commit](https://github.com/Lucklyric/eos/commit/41cf36ad651f318c8c0a9c51bb4cc1592d81996f#diff-fad3ebad54409ea86aa7b840c40a661d)

Don't forget to rebuild and reinstall the eos after the modification. 
Hope it will help.

**Comment by acoutts** [comment]
@Lucklyric thank you!! Worked like a charm for me.

MacBook Pro (Retina, 13-inch, Mid 2014)
macOS High Sierra 10.13.6 (17G65)

**Comment by nirdesh365** [comment]
I am using ubuntu 16.04 and don't find any eosio.wasmsdk file in my system , what should i  do ?

**Comment by Lucklyric** [comment]
@nirdesh365 , you have to clone it from a separate repository at [eosio.wasmsdk](https://github.com/EOSIO/eosio.wasmsdk). Follow its readme to build and install it then you can try the above method.  Good luck.
