### ISSUE TITLE
 "cleos push action eosio setprods  "{ \"schedule\": [{\\"}]}""" ，set eosio as a producer_name?

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5288]
when i run : cleos --wallet-url http://localhost:8899 push action eosio setprods "{ \"schedule\": [{\"producer_name\": \"inita\",\"block_signing_key\": \"EOS6hMjoWRF2L8x9YpeqtUEcsDKAyxSuM1APicxgRU1E3oyV5sDEg\"}]}" -p eosio@active,can eosio as a memeber of producer_name ?

**Comment by jgiszczak** [comment]
Yes, you can retain `eosio` as a producer if you wish.  Using your key and the tutorial key:

`cleos --wallet-url http://localhost:8899 push action eosio setprods "{"schedule": [{"producer_name": "inita", "block_signing_key":"EOS6hMjoWRF2L8x9YpeqtUEcsDKAyxSuM1APicxgRU1E3oyV5sDEg"},{"producer_name":"eosio", "block_signing_key":"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"}]}" -p eosio@active`

The object with producer_name and block_signing_key may be repeated up to 21 times for 21 different accounts.
