### ISSUE TITLE
cleos wallet create , error

### ISSUE THREAD

**Issue by nunettine** [EOSIO/eos#5289]
![2018-08-16 22 10 45](https://user-images.githubusercontent.com/39987149/44219364-c968ab80-a1b6-11e8-9718-6c7feaa6d216.PNG)

i see this error first, 

how can i solve this problem?

**Comment by jgiszczak** [comment]
Follow the instructions given.

`cleos wallet create --to-console`

will give you the output required to continue the tutorial.  The documentation will be updated.
