### ISSUE TITLE
Consistency between MongoDB and history plugin's filter-on option

### ISSUE THREAD

**Issue by chengevo** [EOSIO/eos#5292]
I've observed that MongoDB and history plugins `filter-on` options behave differently.

Assume a simple toke transfer scenario that I want to filter on an action that triggered by account `alice`, that calls `transfer` action on contract deployed on account `eosio.token`, which results transfer some token to `bob`.

If I configured history plugin as below:

```
filter-on=alice:transfer:
filter-on=bob:transfer:
```

I can observe this transaction from either `alice` or `bob`’s perspective:

```
cleos get actions alice
cleos get actions bob
```

however, I won’t achieve the same result if have MongoDB plugin configured the same way:

```
mongodb-filter-on=alice:transfer:
mongodb-filter-on=bob:transfer:
```

But according to the doc, `filter-on` and `mongodb-filter-on` should result the same output:

> `filter-on` option
> 
> Track actions which match `receiver:action:actor`. Actor may be blank to include all. Action and Actor both blank allows all from Recieiver. Receiver may not be blank.
> 
> `mongodb-filter-on` option
> 
> Track actions which match `receiver:action:actor`.  Actor may be blank to include all. Receiver and Action may not be blank. Default is * include everything.

## Reason
The reason resulting this conflict is, history plugin and MongoDB plugin use different fields in an action trace to do filtering.

History plugin construct `receiver:action:actor` as below:

```cpp
filter_on.find({ act.receipt.receiver, act.act.name, a.actor } )
```

and this is what happened in MongoDB plugin. Here, `act.account` actually means the account that have contract deployed.

```cpp
filter_on.find( {act.account, act.name, a.actor} )
```

So, in the token transfer example above, if we configure MongoDB plugin with the option `mongodb-filter-on=alice:transfer:`, what we actually mean is I want to monitor `transfer` action triggered by anyone on the account `alice`.

**Comment by heifner** [comment]
We normally close when PR is merged.

**Comment by chengevo** [comment]
Sorry, it's my bad. I'll know the drill next time. :)

**Comment by jgiszczak** [comment]
Merged.
