### ISSUE TITLE
How to detect a contract account in the contract.

### ISSUE THREAD

**Issue by dabdevelop** [EOSIO/eos#5296]
I want to exclude all contract account to use my contract. How can I detect the account deployed contract in my contract?

**Comment by dabdevelop** [comment]
@taokayan @sergmetelin @heifner

**Comment by jgiszczak** [comment]
The first parameter of your contract's `void apply()` function is `uint64_t receiver`, which is the name of the account to which the contract has been deployed.  If you are using the `EOSIO_ABI` macro, you will need to remove it and create your own implementation of the `apply()` function.  See the macro definition at the bottom of [dispatcher.hpp](https://github.com/EOSIO/eos/blob/bf28f8bbf9ee753966c95c586906e82d72f9dfac/contracts/eosiolib/dispatcher.hpp#L121) for details.  If you include all of the macro, you may use `if(self == N(accountname))` to test if the account named 'accountname' matches the account on which the contract is deployed.

**Comment by chuang39** [comment]
@dabdevelop curious if you got a solution or not. Can you share the idea? Thanks!

@jgiszczak I don't understand your suggestion. The original question was trying to prevent any user with a contract deployed to that user to use my contract.

**Comment by jgiszczak** [comment]
@chuang39 If the condition I quote is violated `(self == N(accountname))`, reject the action in your contract, or do nothing.  Or conversely, all contract actions would be within that conditional, and so only work if the contract is running within the context of the account named "accountname".

**Comment by chuang39** [comment]
@jgiszczak sorry for late response. Thanks for your reply first.

For (self == N(accountname)), self would be the name of my contract name. Assume I deploy my contract at localtest1234, self/receiver would be localtest123. What account name I should use? If a user called user12345678 (with a deployed contract) pushes a action, how your solution could catch it?

**Comment by taokayan** [comment]
This is a contract entry point:
```
void apply( uint64_t receiver, uint64_t code, uint64_t action )
```
receiver: the account that own the current code (self)
code: if triggering code (if code == receiver, it's in main action, otherwise it's in the notification)

Unless specified in some parameters, there's no way to know which use who push the action. Also an action can be signed by multiple accounts.

**Comment by jgiszczak** [comment]
Ultimately, you can not prevent someone else from using your code.  The suggestion I have made only prevents casual reuse.

```c++
if(self == N(localtest1234))
{
    function_normally();
}
```
That test will fail on account `localtest12345678`, so a deployment to that account would do nothing.  However, your code is always retrievable from the chain, as it is public information, and it can be converted from WASM to WAST format, edited to remove that check, and reconverted to WASM and uploaded.  You can not prevent this.

There are _no_ secrets on the chain.

**Comment by chuang39** [comment]
@jgiszczak get your point. Thanks for your explanation!
