### ISSUE TITLE
MacOS compilation error

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [EOSIO/eos#5302]
Can't compile v1.2.* on MacOS with error:
MacOS: 10.13.6 (17G65)

```
Beginning build version: 1.2
	Fri Aug 17 13:10:44 UTC 2018
	User: info
	git head id: bf28f8bbf9ee753966c95c586906e82d72f9dfac
	Current branch: HEAD

	ARCHITECTURE: Darwin

	OS name: Darwin
	OS Version: 10.13.6
	CPU speed: 3.69Ghz
	CPU cores: 6
	Physical Memory: 16 Gbytes
	Disk install: /dev/disk1s1
	Disk space total: 465G
	Disk space available: 410G

	Checking xcode-select installation
	xcode-select installation found @
	/usr/bin/xcode-select

	Checking Ruby installation.
	Ruby installation found @
	/usr/bin/ruby

	Checking Home Brew installation
	Home Brew installation found @
	/usr/local/bin/brew

	Checking dependencies.
	Checking automake ... 		 automake found
	Checking Libtool ... 		 Libtool found
	Checking OpenSSL ... 		 OpenSSL found
	Checking llvm ... 		 llvm found
	Checking wget ... 		 wget found
	Checking CMake ... 		 CMake found
	Checking GMP ... 		 GMP found
	Checking gettext ... 		 gettext found
	Checking MongoDB ... 		 MongoDB found
	Checking Doxygen ... 		 Doxygen found
	Checking Graphviz ... 		 Graphviz found
	Checking LCOV ... 		 LCOV found
	Checking Python3 ... 		 Python3 found

	No required Home Brew dependencies to install.

	Checking boost library installation.
	Boost 1.67.0 found at /usr/local.

	Checking MongoDB C++ driver installation.
	Mongo C++ driver found at /usr/local/lib/libmongocxx-static.a.

	Checking secp256k1-zkp installation.
	secp256k1 found at /usr/local/lib/.

	Checking LLVM with WASM support.
	WASM found at /usr/local/wasm/bin/.


>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOSIO

>>>>>>>> CMAKE_BUILD_TYPE=Release
>>>>>>>> ENABLE_COVERAGE_TESTING=false
>>>>>>>> DOXYGEN=false

-- The C compiler identification is Clang 4.0.1
-- The CXX compiler identification is Clang 4.0.1
-- Check for working C compiler: /usr/local/bin/clang
-- Check for working C compiler: /usr/local/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/clang++
-- Check for working CXX compiler: /usr/local/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
-- Configuring EOSIO on OS X
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using 'SYS' as CORE symbol name
-- Using 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV' as public key for 'eosio' account
-- Found WASM: /usr/local/wasm/bin/clang
-- Using WASM clang => /usr/local/wasm/bin/clang
-- Using WASM llc => /usr/local/wasm/bin/llc
-- Using WASM llvm-link => /usr/local/wasm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Found GMP: /usr/local/lib/libgmp.a
-- Configuring fc to build on Unix/Apple
-- Found OpenSSL: /usr/local/opt/openssl/lib/libcrypto.a (found version "1.0.2o")
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11")
-- zlib found
-- Configuring Builtins
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   unit_test_framework
--   locale
-- Configuring ChainBase on OS X
-- Using custom FindBoost.cmake
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   filesystem
--   system
--   chrono
--   program_options
--   unit_test_framework
--   locale
-- Configuring AppBase on OS X
-- Found Git: /usr/bin/git (found version "2.15.2 (Apple Git-101.1)")
-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: /usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;/usr/lib/libm.dylib
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: /usr/local/lib/libmongocxx-static.a;/usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;/usr/lib/libm.dylib;/usr/local/lib/libmongoc-static-1.0.a;/usr/local/lib/libbson-static-1.0.a;/usr/lib/libm.dylib;/usr/lib/libsasl2.dylib;-framework CoreFoundation;-framework Security;/usr/lib/libz.dylib;resolv
-- Git commit revision: bf28f8bb
-- Git commit revision: bf28f8bb
-- Found Intl: /usr/local/include
-- Git commit revision: bf28f8bb
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.14") found components:  doxygen dot
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
cocoa_framework
    linked by target "wallet_plugin" in directory /Users/info/_sites/eos/plugins/wallet_plugin
corefoundation_framework
    linked by target "wallet_plugin" in directory /Users/info/_sites/eos/plugins/wallet_plugin
localauthentication_framework
    linked by target "wallet_plugin" in directory /Users/info/_sites/eos/plugins/wallet_plugin
security_framework
    linked by target "wallet_plugin" in directory /Users/info/_sites/eos/plugins/wallet_plugin

-- Configuring incomplete, errors occurred!
See also "/Users/info/_sites/eos/build/CMakeFiles/CMakeOutput.log".

	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.
```

**Comment by Vasiliy-Bondarenko** [comment]
xcode-select can be found.
xcode installed
all frameworks can be found here: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/
i've even tried to add this path to $PATH

but build script still failing.

**Comment by lazaridiscom** [comment]
@jgiszczak , this seems related to https://github.com/EOSIO/eos/pull/4244#commitcomment-30068178

@Vasiliy-Bondarenko , just a guess: can you try to cleanup everything (rm -rf build, tmp files etc.) or to go for a fresh clone/build?

**Comment by Vasiliy-Bondarenko** [comment]
`rm -rf build` - done.
tmp files - did not find any.
it is a fresh clone/build. i did not build it on this machine before.
same result.

**Comment by NorseGaud** [comment]
Are you manually installing or using the .sh script? Our configs are identical according to your output. Here are my brew versions if that helps
<pre>
 norsegaud@norsegaudnet  ~  ll /Users/norsegaud/Library/Caches/Homebrew                                                                                                                                                                               1 ↵  2012  17:09:14
total 1388568
drwxr-xr-x  4 norsegaud  staff   128B Jun 11 22:26 Cask
-rw-r--r--  1 norsegaud  staff   871K Sep 14  2017 autoconf-2.69.high_sierra.bottle.4.tar.gz
-rw-r--r--  1 norsegaud  staff   943K Mar 11 19:32 automake-1.16.1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff    87M Apr 18 11:30 boost-1.67.0_1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff    12M Jul 17 11:56 cmake-3.12.0.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff    75K Sep 18  2017 cpptest-1.1.2.high_sierra.bottle.1.tar.gz
-rw-r--r--  1 norsegaud  staff   4.0M Dec 28  2017 doxygen-1.8.14.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   1.2M May  3 06:33 fontconfig-2.13.0.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   877K May  2 07:45 freetype-2.9.1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   290K Sep 15  2017 gd-2.2.5.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   190K Jun 28 06:54 gdbm-1.16.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   7.8M Sep 14  2017 gettext-0.19.8.1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   1.0M Mar 19 14:02 gmp-6.1.2_2.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   6.9M Sep 15  2017 graphviz-2.40.1.high_sierra.bottle.1.tar.gz
-rw-r--r--  1 norsegaud  staff    25M Jun 21 22:15 icu4c-62.1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   298K Feb 26 04:11 jpeg-9c.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   144K Sep 23  2017 lcov-1.13.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff    97K Sep 14  2017 libffi-3.2.1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   217K May 18 06:25 libidn2-2.0.5.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   445K Jul 25 08:20 libpng-1.6.35.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   1.0M Jul  2 03:33 libtiff-4.0.9_4.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   1.0M Sep 14  2017 libtool-2.4.6_1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   1.4M May 25 13:21 libunistring-0.9.10.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   100K Sep 14  2017 libyaml-0.1.7.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   204K Jul 31 07:46 linkage.db
-rw-r--r--  1 norsegaud  staff   319M Sep 17  2017 llvm@4-4.0.1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   5.7M Mar 27 09:07 media-info-18.03.1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff    85M Jun 28 12:21 mongodb-4.0.0.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff    16M Jul  4 23:08 node-10.6.0.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   3.7M Mar 28 07:30 openssl-1.0.2o_1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   3.7M Jun 17 04:02 openssl-1.0.2o_2.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   236K Sep 14  2017 pkg-config-0.29.2.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff    11M Mar  2 08:14 postgresql-10.3.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff    22M Jul 23 18:22 python-3.7.0.high_sierra.bottle.1.tar.gz
-rw-r--r--  1 norsegaud  staff    18M Jul 23 18:22 python@2-2.7.15_1.high_sierra.bottle.1.tar.gz
-rw-r--r--  1 norsegaud  staff   495K Sep 14  2017 readline-7.0.3_1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   494K Jul  5 12:21 readline-7.0.5.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   8.0M Mar 28 20:54 ruby-2.5.1.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   1.7M Jun  4 21:17 sqlite-3.24.0.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff    94K Dec 19  2017 telnet-54.50.1.high_sierra.bottle.1.tar.gz
-rw-r--r--  1 norsegaud  staff    75K Feb  7  2018 uriparser-0.8.5.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   835K Apr 21 03:04 webp-1.0.0.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   1.3M May  6 23:52 wget-1.19.5.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   373K May  1 07:07 xz-5.2.4.high_sierra.bottle.tar.gz
-rw-r--r--  1 norsegaud  staff   923K May 23 17:02 yarn-1.7.0.tar.gz</pre>

**Comment by NorseGaud** [comment]
Are you using eosio_build.sh and then the install.sh?

I’m almost 100% certain this is a problem with something you have installed separate from EOS and it’s requirements. Create a new user account on your Mac and try the build/install from scratch

**Comment by lazaridiscom** [comment]
latest versions include an `eosio_install.sh` script, so you go with:

```bash
./eosio_build.sh
sudo ./eosio_install.sh
```

**Comment by Vasiliy-Bondarenko** [comment]
@NorseGaud created new user, same story. what kind of requirements are you talking about except the one, that script installs itself? is there some list i need to go through?
i'm just doing 
```
git clone https://github.com/EOSIO/eos --recursive
cd eos
./eosio_build.sh
```
am i missing something? 

@lazaridiscom i don't have problems installing, i can't compile.

**Comment by lazaridiscom** [comment]
@Vasiliy-Bondarenko , my last comment complemented @NorseGaud "build/install" comment.

**Comment by jgiszczak** [comment]
@lazaridiscom Of course the comment on #4244 seems related&mdash;it's the same person with the same problem report.

For once, Homebrew is not at fault.  There is something wrong with the XCode and framework installation.  CMake's `find_library()` function is used by the wallet plugin to determine the linking flags required for its build.  Check permissions, check that the specific required frameworks really are present, check the filesystem for corruption.  If none of those things help, file a problem report with CMake.  The `find_library()` function works on any normal, healthy system.

Failing all of that, VirtualBox with a Linux installation has been reported to work by another Mac user with a permanently sick system.

**Comment by lazaridiscom** [comment]
@jgiszczak 
> Of course the comment on #4244 seems related—it's the same person with the same problem report.

Yes, an its standard-procedure to interlink related issues/PR's (which I've done by mentioning the PR).

> Failing all of that, VirtualBox with a Linux installation has been reported to work by another Mac user with a permanently sick system.

This does not solve this issue.

This issue should stay open, until the team has find a way to help this user, and to avoid similar incidents in the future. Actions would be:

* Issue: provide a MAC-OS sanity-check
* Issue: integrate a sanity-check within the MAC-OS build-scripts

**Comment by jgiszczak** [comment]
@lazaridiscom Mac OS X and XCode technical support is provided by Apple Corporation.  This forum is for EOS.IO software problems.  CMake's functions constitute a sanity check.  If CMake fails to locate XCode frameworks, the problem lies with the system, not the EOS.IO software.  Systems damaged or deviant enough to prevent CMake from functioning are not supported.  The issue is closed.

**Comment by aaroncox** [comment]
Ran into the same problem, but since I've run into this before with a case-sensitive file system, I figured it'd be a simple enough fix. Pull request with the solution has been submitted to `develop`.

**Comment by lazaridiscom** [comment]
@jgiszczak 

> [...] The issue is closed.

You (and the project-lead) should really urgently revise your attitude and policies. 

@aaroncox 

Great!

Related: https://github.com/EOSIO/eos/issues/2719#issuecomment-386611988

**Comment by Vasiliy-Bondarenko** [comment]
@aaroncox thanx man. 
obviously it was no issues with my system, apple, xcode or cmake :)

**Comment by jgiszczak** [comment]
@Vasiliy-Bondarenko Oh it's definitely an issue with Apple.  They pulled the same crap Microsoft did with a case-preserving but case-insensitive filesystem, which is a travesty in a filesystem that in every other respect appears POSIX compliant.

**Comment by lazaridiscom** [comment]
@Vasiliy-Bondarenko , we, the simple users, must do our best to keep things around EOS evolving.

Thank you for filing this issue and for your patience.

**Comment by Vasiliy-Bondarenko** [comment]
@jgiszczak :))) yep, you are right, apple did a lot of nonsense staff, especially in the last two years :)

@lazaridiscom appreciate it. looks like you know how the team is doing software testing - can you elaborate a little how do you test for performance bottlenecks? our team is going to investigate hardware optimisation for different kind of nodes. thanks.

**Comment by lazaridiscom** [comment]
@Vasiliy-Bondarenko , could swear I answered you already - but my comment is gone... anyway, again:

>  looks like you know how the team is doing software testing

I'm just processing/evaluating the build/install/test system in an abstract manner, in the role of a simple user (or: contract developer).

> can you elaborate a little how do you test for performance bottlenecks

I would go the usual way:

* Specify Requirements
* Select a Standard-Tool (Profiler)

> our team is going to investigate hardware optimisation for different kind of nodes

Sounds like a challenging task. Such functionality could be standardized and included into an EOS SDK.
