### ISSUE TITLE
eosio.token account

### ISSUE THREAD

**Issue by oshek14** [EOSIO/eos#5308]
Hello guys, before deploying contract, we create account to deploy it to:  `cleos create account eosio eosio.token PUB_KEY PUB_KEY` . the name of the account is "eosio.token". So there is my question? How can I create account with this name? I know that account with this name already exists. Isn't account name unique? I know that something specific is going on, but I can't understand well. Can someone explain me?

**Comment by jgiszczak** [comment]
The tutorials are for a private testnet, which needs an eosio.token account to operate properly.  Contracts can be deployed to any account with the RAM purchased sufficient to hold the contract, one contract per account.  See the [Hello World Contract](https://developers.eos.io/eosio-cpp/docs/hello-world) tutorial for an example of a different account name being used.

Note that even that tutorial is geared for a private testnet&mdash;account names with dots in them are reserved for the bidding process on mainnet.  If and when the `.code` suffix is successfully bid on mainnet, the tutorial name `hello.code` would be purchased from the owner of that suffix.

To get an account on mainnet, if you didn't buy and register EOS during the ICO, you must purchase one from one of the available services.  The account names that may be bought without auction must be exactly 12 characters long and consist of the digits 0-5 and the letters a-z.  (This restriction is a side effect of the fact that every account 'name' in EOS is actually a base32-encoded 64 bit integer.)  Once you have your new account, you may deploy your contract to it using cleos.
