### ISSUE TITLE
How to implment a contract that transfer EOS from contract account to invoker account?

### ISSUE THREAD

**Issue by yukozh** [EOSIO/eos#5309]

**Comment by xJonathanLEI** [comment]
Define a struct for the transfer action:

    struct transfer_args
    {
        account_name from;
        account_name to;
        asset quantity;
        string memo;
    };

In one of your action handler, send the token:

    void mycontract::myhandler(account_name recepient) {

        require_auth(recepient);

        action(permission_level{_self, N(active)},
               N(eosio.token), N(transfer),
               transfer_args{
                   _self,
                   recepient,
                   asset(amount, S(4, EOS)),
                   "Sent from the contract!"}
         ).send();
    }

**Comment by boy-good** [comment]
@xJonathanLEI  I use this function but show the error :
"assertion failure with message: attempt to add asset with different symbol"
Can you help me?Thanks very much.

**Comment by andriantolie** [comment]
The original issue has been answered by @taokayan, I'm closing this issue.

@boy-good check if you are adding assets with the same symbol. If you are testing locally, your symbol is very likely to be S(4, SYS)

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
