### ISSUE TITLE
[v1.2.1] 'make test' failing for Mac OS 

### ISSUE THREAD

**Issue by NorseGaud** [EOSIO/eos#5318]
<pre>
70% tests passed, 14 tests failed out of 46

Label Time Summary:
long_running_tests    = 324.23 sec*proc (5 tests)

Total Test time (real) = 1515.75 sec

The following tests FAILED:
	 32 - nodeos_sanity_test (Failed)
	 33 - nodeos_run_test (Failed)
	 34 - bnet_nodeos_run_test (Failed)
	 36 - nodeos_run_test-mongodb (Failed)
	 37 - distributed-transactions-test (Failed)
	 38 - restart-scenarios-test-resync (Failed)
	 39 - restart-scenarios-test-hard_replay (Failed)
	 40 - restart-scenarios-test-none (Failed)
	 41 - validate_dirty_db_test (Failed)
	 42 - nodeos_sanity_lr_test (Failed)
	 43 - bnet_nodeos_sanity_lr_test (Failed)
	 44 - nodeos_voting_lr_test (Failed)
	 45 - bnet_nodeos_voting_lr_test (Failed)
	 46 - nodeos_under_min_avail_ram_lr_test (Failed)
</pre>

Used build and install scripts. Should I be concerned? What sort of quality control is done when a new version is released to ensure these are tested to be working on every distro?

**Comment by lazaridiscom** [comment]
related #4927 

Possibly you need to kill existent processes first (`pkill -9 nodeos`, same for keosd,) 

instead of of `make test`, use `ctest --output-on-failure` to get some feedback on the errors.

**Comment by lazaridiscom** [comment]
> What sort of quality control is done when a new version is released to ensure these are tested to be working on every distro?

see #4984 for some answers.

**Comment by NorseGaud** [comment]
While I hate that the tests aren't working, even if I run it multiple times, the code does run, so I'm ok with it for now. I'd love to see more assurance of code stability through tests in future releases. It's not unreasonable to expect 100% passing tests in all environments the code is said to run in.
