### ISSUE TITLE
split blocks.log

### ISSUE THREAD

**Issue by williamleecn** [EOSIO/eos#5322]
blocks.log文件增长太快了,我觉得把它应该分割成多个文件

 blocks.log files are growing too fast.I think it should be split into multiple files

**Comment by taokayan** [comment]
Theoretically it should be able to store in even a single file, as the max block size is around 1MB and around 60M blocks/year, which would be 60TB/year at maximum. So having a RAID 0 config for 4 14TB harddisks can allow you to store the whole log for years. What's your harddisk size and your current blocks.log size?

**Comment by williamleecn** [comment]
我是超节点,我用的是云服务器,只有120G,虽然可以增加到500G,但是这费用也挺贵.
除了分割,我还在想能不能删掉一些旧的

I'm not a BP,I used a cloud server, only 120G, although it can increase to 500G, but it's expensive. 

In addition to division, I still want to be able to delete some of the old 

-rw-r--r-- 1 root root  93M Aug 20 13:14 blocks.index
-rw-r--r-- 1 root root  35G Aug 20 13:14 blocks.log

**Comment by jgiszczak** [comment]
The bitcoin blockchain is ~173 GB this year.  The EOS.IO blockchain is considerably more capable, hosting accounts, contracts, and user data as well as transactions.  The EOS.IO chain size is not out of line with other chains, especially given the transaction rate it is capable of processing.  If you wish to run a full node, you are expected to provision accordingly.  Full nodes are required to be able to transmit a complete copy of the chain to any connecting node.  Therefore, full nodes must maintain a complete copy of the chain.

The feature you are requesting may be suitable for a so-called 'lite' node.  At present there is no implementation of a 'lite' node.
