### ISSUE TITLE
is genesis.json file a must, when trying to connect to EOS mainnet?

### ISSUE THREAD

**Issue by liliyongleo** [EOSIO/eos#5324]
we have to specify genesis.json file, when trying to connect to EOS mainnet, is that a must?

What really concerns me, is that, is genesis.json compatibled forthwards when we try to upgrade EOS to a new version in future.

**Comment by y001j** [comment]
No, you don't need to modify genesis.json, if only wnat to connect mainnet. 
use argument -u and one of mainnet node addresses:    **`cleos -u http://mainnet.....   get info`**

**Comment by qimiaoguo** [comment]
When your first start your node, you must specify genesis.json, when your restart, you don't need any more

**Comment by taokayan** [comment]
genesis.json is needed only when you start nodeos with an empty block log. further upgrades will not change the genesis.json file.
