### ISSUE TITLE
Why is min_activated_stake a fixed value of 150'000'000'0000 instead of 15%?

### ISSUE THREAD

**Issue by lpx1988** [EOSIO/eos#5326]
Why is min_activated_stake a fixed value of 150'000'000'0000 instead of 15%? In order to limit the system token SYS circulation is 1 billion?（.../constracts/eosio.system/producer_pay.cpp ）

**Comment by taokayan** [comment]
This is hardcoded value and it was only used to activate the blockchain. It would basically equal to 15% of the overall circulation at the time it was activated. It will be no longer used after activation.

**Comment by lpx1988** [comment]
If the initial token (SYS) is less than or much larger than this value（150'000'000'0000）, will it cause the system to fail to activate properly?@taokayan

**Comment by jgiszczak** [comment]
If the token supply is less than that value, yes, the system will fail to activate properly.  If the token supply is much larger, it will not affect activation.

**Comment by lpx1988** [comment]
Thank you ！@jgiszczak
