### ISSUE TITLE
[HELP] Cannot able to connect with testnet

### ISSUE THREAD

**Issue by yashbhavsar007** [EOSIO/eos#5329]
I tried running start.sh but nodeos doesnot started after that i tried start_wallet.sh it shows
./Wallet/start_wallet.sh: line 17: /home/eos/build/programs/keosd/keosd: No such file or directory
where i have available all the files at the same path.
Here i am also attaching my config file please correct me if is there any problems in config.ini
[config.ini.zip](https://github.com/EOSIO/eos/files/2301369/config.ini.zip)

**Comment by jgiszczak** [comment]
What start.sh script are you using?  The current repository has no such script.

**Comment by yashbhavsar007** [comment]
Here is my start.sh script @jgiszczak 
`NODEOSBINDIR="/home/eos/build/programs/nodeos"
DATADIR="/opt/JungleTestnet"

$DATADIR/stop.sh
echo -e "Starting Nodeos \n";

ulimit -n 65535
ulimit -s 64000


$NODEOSBINDIR/nodeos --data-dir $DATADIR --config-dir $DATADIR "$@" > $DATADIR/stdout.txt 2> $DATADIR/stderr.txt &  echo $! > $DATADIR/nodeos.pid`

**Comment by jgiszczak** [comment]
That looks like a perfectly serviceable start script.  What does your start_wallet.sh script look like?

**Comment by yashbhavsar007** [comment]
@jgiszczak  here i am attaching my all testnet scripts and genesis.json file.
[Testnet Scripts.zip](https://github.com/EOSIO/eos/files/2308898/Testnet.Scripts.zip)

**Comment by yashbhavsar007** [comment]
here is i met with error when i tried run start_wallet.sh have a look at this also @jgiszczak 
![testnet_issue](https://user-images.githubusercontent.com/26292780/44443670-98450c80-a5f6-11e8-89e7-7264ad16421d.png)

**Comment by jgiszczak** [comment]
Your start_wallet.sh script contains `$NODEOSBINDIR/keosd/keosd` but your start.sh script contains `NODEOSBINDIR/nodeos`, but you said you "had all files available at the same path".  Remove the `keosd` subdirectory in start_wallet.sh and the `keosd` binary will be found.  `$NODEOSBINDIR/keosd`

**Comment by Aniket-Engg** [comment]
@yashbhavsar007  Change data directory in `start.sh` like this `DATADIR="/opt/JungleTestnet/EOS-Jungle-Testnet"`  and same in `./Wallet/start_wallet.sh` along with the actual path of keosd.

**Comment by yashbhavsar007** [comment]
@Aniket-Engg  I have changed name of folder after cloning from EOS-Jungle-Testnet to JungleTestnet so i don't need to change path and thanks for response but this issue is resolved now.
