### ISSUE TITLE
Permission design question

### ISSUE THREAD

**Issue by elmato** [EOSIO/eos#533]
_(the eosc examples uses the last parameter as the permission level to authorize)_

Suppose that we have the following permission structure over account1

***owner<--active<--newperm***

by doing

```./eosc set account permission account1 newperm EOSxxxxxUxF active active```

Then we set "newperm" as the minimum permission to call updateauth over account1 using eosc.

```./eosc set action permission account1 eos updateauth newperm active```

**It is the expected behavior to allow us to change the "active" authorities (or any other parent permission authority) by just satisfying the "newperm" permission?**

```./eosc set account permission account1 active EOSxxxxxMuE owner newperm```

**Comment by andriantolie** [comment]
In the latest code, this is not allowed anymore. I'm closing this issue
