### ISSUE TITLE
eosiocpp: command not found

### ISSUE THREAD

**Issue by isTg** [EOSIO/eos#5333]
GuangdeMacBook-Pro:hello tg$ ls
CMakeLists.txt	hello.abi	hello.cpp	hello.hi_rc.md	hello_rc.md
GuangdeMacBook-Pro:hello tg$ eosiocpp -o hello.api hello.cpp
-bash: eosiocpp: command not found

**Comment by yashbhavsar007** [comment]
see this #4729

**Comment by lazaridiscom** [comment]
@isTg , with the latest (1.2.1), you simply run `./eosio_install.sh`. It installs the binaries and places symlinks to the standard-bin paths.
