### ISSUE TITLE
tx can only be found when giving block_num_hint

### ISSUE THREAD

**Issue by dfguo** [EOSIO/eos#5334]
tx `50fe99fcd24d9c025bf808329ef29b01e9c7783d7e770c3d497b72c9749cbd40` contains a `eosio.token:transfer` action. When queried through cleos/block explorer, it can only be found when given block_num_hint 10534685.

Cleos:

```cleos -u https://api1.eosasia.one get transaction fae47848324887bf4400816bb68e8be4f6607e3f6a13ca72af3de5199563fc71``` can't find tx

```cleos -u https://api1.eosasia.one get transaction fae47848324887bf4400816bb68e8be4f6607e3f6a13ca72af3de5199563fc71 -b 11139462``` tx can be found

See in explorer:

https://www.myeoskit.com/#/tx/50fe99fcd24d9c025bf808329ef29b01e9c7783d7e770c3d497b72c9749cbd40?block=10534685
https://www.myeoskit.com/#/tx/50fe99fcd24d9c025bf808329ef29b01e9c7783d7e770c3d497b72c9749cbd40

**Comment by jgiszczak** [comment]
The history plugin attempts to find the transaction in its index.  If it's not in the index, it will use the block number to exhaustively search the block for the transaction.  Without the block number hint, it does not try to search the entire chain.

To get all transactions into the index, replay your blockchain with the history plugin enabled.  Note this will take considerably more RAM than normal, as the indexes are built in the same RAM database as chain state.

**Comment by jgiszczak** [comment]
You will need to replay your blockchain to index all previous transactions.  This history plugin indexes transactions as it sees them incorporated into the chain.  It does not retroactively search the chain after it is enabled.

**Comment by dfguo** [comment]
@jgiszczak I know. We have filter-on enabled since the beginning. It's definitely an issue because I have tried to query the tx on all available API endpoints that have history plugin on with no avail.

**Comment by winlin** [comment]
@jgiszczak we have same issue, and we have replay the blockchain and enable filter-on=* always

**Comment by guaiguaihw** [comment]
+1，we enable filter-on=* and history plugin since the beginning too.

**Comment by dfguo** [comment]
@heifner sorry, i think i pasted the wrong cleos command. I have edited it. The tx doesn't include blocktwitter and still can't be found without providing block hint:

```cleos -u https://api1.eosasia.one get transaction 50fe99fcd24d9c025bf808329ef29b01e9c7783d7e770c3d497b72c9749cbd40```

```cleos -u https://api1.eosasia.one get transaction 50fe99fcd24d9c025bf808329ef29b01e9c7783d7e770c3d497b72c9749cbd40 -b 10534685```

**Comment by heifner** [comment]
Can you reproduce this on a local nodeos?
