### ISSUE TITLE
Nodeos has crashed after hard replay

### ISSUE THREAD

**Issue by ValeryDubrava** [EOSIO/eos#5336]
I've get corrupted state after killing the nodes and launched it in hard replay mode.
After a while I faced with [this error](https://gist.github.com/ValeryDubrava/0d1cb5e9278322c34524c62c095df58b) in the log and state was corrupted again!

Nodeos version is: 1330535458
OS: Centos7 (Linux eos 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by jgiszczak** [comment]
block_subscription_plugin.cpp appears to be a network-enabled plugin.  Check it for uncaught exceptions.  If it has problems, you'll need to file issues with it.  It is not part of the EOS.IO software maintained in this repository.
