### ISSUE TITLE
when i run cleos in one host use diffirent port,does it need to wallet import  --private-key twice ?ALso, create account twice？

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5338]
when i run cleos in one host use diffirent port:
```
cleos --wallet-url http://127.0.0.1:8900 --url http://127.0.0.1:8888  create account EOS8Znrtgwt8TfpmbVpTKvA2oB8Nqey625CLN8bCN3TEbgx86Dsvr
cleos --wallet-url http://127.0.0.1:8901 --url http://127.0.0.1:8889  create account EOS8Znrtgwt8TfpmbVpTKvA2oB8Nqey625CLN8bCN3TEbgx86Dsvr
```
```
cleos --wallet-url http://127.0.0.1:8900 --url http://127.0.0.1:8888  wallet import --private-key
5K463ynhZoCDDa4RDcr63cUwWLTnKqmdcoTKTHBjqoKfv4u5V7p
cleos --wallet-url http://127.0.0.1:8900 --url http://127.0.0.1:8888  wallet import --private-key
5K463ynhZoCDDa4RDcr63cUwWLTnKqmdcoTKTHBjqoKfv4u5V7p
```
does it need to import  --private-key twice ?

**Comment by jgiszczak** [comment]
If you are running more than one keosd with independent data directories, then yes, you must import private keys twice if you expect them to be available on all of your keosd instances.  Running more than one keosd with the same data directory is strongly discouraged.  You are likely to encounter unexpected results, including crashes.  It is ordinarily unnecessary to run more than one keosd when using the HTTP-enabled version.

If you are running multiple instances of `nodeos`, it is only necessary to run `create account` on the nodes if they are independent.  If the nodes are connected and synched, it is only necessary to run `create account` once.  If you are able to run `create account` on multiple nodes without error, that is an indication that your nodes are not synchronized.  If you intended them to be synchronized, you have an error in your network configuration.
