### ISSUE TITLE
Retrieving synced blocks from blocks.log

### ISSUE THREAD

**Issue by jooner** [EOSIO/eos#5340]
Problem:
I've synced up my local nodeos (running in a docker container) to the Mainnet and would like to inspect the actual data that's on each block/transaction/action. One way to do this would be through rpc calls, but doing this for millions of blocks is very slow (even with pool/async etc).

Question:
Is it possible to work directly with the `blocks.log` file that's written during the syncing process? By blocks.log I'm referring to the 30GB+ file that lives in `/root/.local/share/eosio/nodeos/data/`. If so, how should I read (wrt encoding and file handling) the `.log` file if I'm working in python?

Any pointers would be greatly appreciated. Thanks!

**Comment by jgiszczak** [comment]
It's always possible to interpret the blocks.log file, but it would be considerably difficult to do so in Python.  You would have to replicate the entirety of fc library variants for the fundamental types, then create Python struct interpretations of every block-related class, including packed transactions and blocks themselves.

It would be considerably easier to enable the mongo_db_plugin, replay your chain, and query your mongodb.

If you're really determined to read the file yourself, start with `eos/libraries/chain/block_log.cpp` and work your way through the `append()` method and everything it invokes to serialize a block.
