### ISSUE TITLE
push_transaction RPC API usage example and questions

### ISSUE THREAD

**Issue by baegjae** [EOSIO/eos#5341]
The `push_transaction` RPC API call requires some queries and conversions.
This example has been tested with eos version 1.2.1 and works fine.
I hope this example helps you to use the push_transaction API.

```
#!/bin/sh

# Example of push_transaction
# Tested with eos version 1.2.1
# below script are same as
# cleos push action eosio.token transfer '{"from":"applecookies","to":"blueberryjam","quantity":"1.0000 EOS","memo":"memo"}' -p applecookies@active
CODE="eosio.token"
ACTION="transfer"
ARGS='{"from":"applecookies","to":"blueberryjam","quantity":"1.0000 EOS","memo":"memo"}'
ACTOR="applecookies"
PUBLIC_KEY="EOS7Cg2SPDJDdAFZWkyx8s3U7CQq5RiWhj7M2Xkc9qRxSVYwU2jHQ" # ACTOR's

# edit this for your environment
CHAIN="curl --request POST --url http://127.0.0.1:8888/v1/chain"
WALLET="curl --request POST --url http://127.0.0.1:8900/v1/wallet"
CLEOS="./build/programs/cleos/cleos -u http://192.168.10.81:8888 --wallet-url=http://127.0.0.1:8900"

# 1. Get required information (chain_id, block_num, block_prefix, expiration)
GET_INFO=`$CHAIN/get_info`
CHAIN_ID=`echo $GET_INFO | jq '.chain_id'`
BLOCK_NUM=`echo $GET_INFO | jq '.last_irreversible_block_num'`
GET_BLOCK=`$CHAIN/get_block --data '{"block_num_or_id":'$BLOCK_NUM'}'`
BLOCK_PREFIX=`echo $GET_BLOCK | jq '.ref_block_prefix'`
TIMESTAMP=`echo $GET_BLOCK | jq '.timestamp'`
EXPIRATION=`jq -n ''$TIMESTAMP' | strptime("%Y-%m-%dT%H:%M:%S%Z") | mktime | . + 30 | todate | sub("Z"; .before)'`
echo "chain_id: $CHAIN_ID"
echo "block_num: $BLOCK_NUM"
echo "block_prefix: $BLOCK_PREFIX"
echo "expiration: $EXPIRATION"

# 2. Convert arguments: json -> binary
BINARGS=`$CHAIN/abi_json_to_bin --data '{"args":'"$ARGS"',"code":"'$CODE'","action":"'$ACTION'"}' | jq '.binargs'`
echo "binargs: $BINARGS"

# 3. Sign the transaction
TX='{"actions":[{"account":"'$CODE'","name":"'$ACTION'","authorization":[{"actor":"'$ACTOR'","permission":"active"}],"data":'$BINARGS'}],"signatures":[],"expiration":'$EXPIRATION',"ref_block_num":"'$BLOCK_NUM'","ref_block_prefix":"'$BLOCK_PREFIX'"}'
echo "TX: $TX"
SIGNED_TX=`$WALLET/sign_transaction --data '['$TX', ["'$PUBLIC_KEY'"], '$CHAIN_ID']'`
echo "SIGNED_TX: $SIGNED_TX"

# 4. Pack the signed_transaction
PACKED_TX=`$CLEOS convert pack_transaction ''$SIGNED_TX''`
echo "PACKED_TX: $PACKED_TX"

# 5. Call push transaction using packed transaction
echo "\n-- Results of push_transaction --"
$CHAIN/push_transaction --data ''"$PACKED_TX"''
echo ""
```

And the questions are as follows.

Question 1.
In the code, the push_transaction RPC API can only be executed when `packed transaction` is used as data. (# 5 in example)
However, `signed transaction` is used as data in the document.
This confusion needs to be corrected.
https://developers.eos.io/eosio-nodeos/reference#push_transaction

Question 2.
In my search, `cleos` is the only way to pack transactions. (# 4 in the example)
Is there another way to pack transactions?
If not, what is your plan for this feature? (RPC API or other tool?)
I think, if `cleos` is already installed, we do not need to use a complicated RPC API.

**Comment by wanglei-sky** [comment]
# 4 in the example
Is this step necessary?
The RPC interface does not provide this method. What should I do?

**Comment by jgiszczak** [comment]
Answer 1: The documentation clearly states that the `push_transaction` RPC API expects a packed transaction.

![image](https://user-images.githubusercontent.com/15825116/45185815-160d3880-b1f1-11e8-91d9-15aee99857df.png)

Answer 2: There are third party implementations that replicate the packing functionality of `cleos`.  I believe one of them is in Javascript.  At present there are no plans to provide an RPC API to pack transactions.

**Comment by baegjae** [comment]
@wanglei-sky Yes it is necessary. Refer jgiszczak's answer 2.
@jgiszczak 
Answer1 -> The document has been corrected. Thank you.
Answer2 -> I also think that pack transaction should be run on the client side. Thank you for clarifying.

**Comment by lucgerrits** [comment]
The question #2 about pack transaction should indeed be detailed. I'm trying to build & send transactions in C++ and it is strange that there isn't a lot of information about this step (only the eosjs code to help a little...).

**Comment by apond308** [comment]
Has there been any progress on this? I would also like to use the RPC API and not rely on cleos to interact with my contract. It seems like there is really only documentation for eosjs (javascripts API) instead of the RPC chain API.
