### ISSUE TITLE
Hou to use cleos command specified --wallet-dir ?

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5342]
The file for this wallet is named default.wallet. By default, keosd stores wallets in the ~/eosio-wallet folder. The location of the wallet data folder can be specified on the command line using the --wallet-dir argument.
so, Hou to use cleos command specified --wallet-dir ?

**Comment by jgiszczak** [comment]
Cleos does not load files from the wallet-dir itself.  It communicates only with keosd, which manages wallet files.  Use `--wallet-url` to specify the hostname/IP and port for keosd.
