### ISSUE TITLE
eosiocpp output error

### ISSUE THREAD

**Issue by isTg** [EOSIO/eos#5347]
GuangdeMacBook-Pro:bin tg$ ./eosiocpp -o output.wast /Users/tg/Downloads/eos/contracts/hello/hello.cpp
/Users/tg/Downloads/eos/contracts/hello/hello.cpp:1:10: fatal error:
      'eosiolib/eosio.hpp' file not found
#include <eosiolib/eosio.hpp>
         ^~~~~~~~~~~~~~~

**Comment by lazaridiscom** [comment]
run `sudo ./eosio_install.sh` first

**Comment by isTg** [comment]
@lazaridiscom Tried

**Comment by lazaridiscom** [comment]
@isTg Great

**Comment by jgiszczak** [comment]
Also update to the 1.2.1 release.

**Comment by taokayan** [comment]
Is this issue solved?

**Comment by isTg** [comment]
Tried other ways
