### ISSUE TITLE
Error 3160009: No wast file found

### ISSUE THREAD

**Issue by li3365** [EOSIO/eos#5349]
I use latest eosio/eos-dev docker images ,and jungletestnet http://jungle.cryptolions.io:18888 
with helloworld contract,meet following errors:

cleos set contract helocode1234 ./helo -p helocode1234@active
Reading WASM from ./helo/helo.wasm...
Error 3160009: No wast file found
Error Details:
no wasm file found ./helo/helo.wasm

but these files do exist:
ls ./helo/
helo.abi	helo.cpp	helo.wasm	helo.wast

why?

**Comment by li3365** [comment]
That issue is under mac book air.now I use docker image under  ubuntu ,It worked .strange.

**Comment by jgiszczak** [comment]
Be sure to update your docker images.  Older versions did have problems locating contract files.

**Comment by Panoplos** [comment]
Having the same issue... This should not be closed for 1.2.5 branch.

**Comment by rohanagarwal94** [comment]
@jgiszczak please reopen this issue.

**Comment by rohanagarwal94** [comment]
tg://join?invite=Esi1OkPktgcFeJ3Lmlcrqg. Join this, and see the chat history to get the solution.

**Comment by jgiszczak** [comment]
See [this post](https://github.com/EOSIO/eos/issues/5091#issuecomment-411826939) for how to use the `docker volume` command to set up a mapping between the docker and host filesystems.  It's one of several possible options for making the jump between the two.  The documentation is being updated.  Its explanations for working with the docker environment are definitely inadequate.

Note the eosio.cdt toolchain no longer generates .wast files at all.  If you wish a wast file, you'll need to run the converter on the wasm file yourself.

**Comment by itamarro** [comment]
To anyone encountering this with the latest version, try to use an absolute path instead (e.g. /bla/bla, not ./bla/bla).
