### ISSUE TITLE
clion build hello error

### ISSUE THREAD

**Issue by isTg** [EOSIO/eos#5351]
7:04 PM	Error running hello: File not found: /Users/tg/Downloads/eos/cmake-build-debug/contracts/hello/hello.tmp

**Comment by isTg** [comment]
@lazaridiscom I still don't understand,How should it be configured?

**Comment by lazaridiscom** [comment]
> How should it be configured?

I have no idea.

Just use the command-line-tools directly, like:

```bash
cd <your eos dir>
./eosio_build.sh
```

or use the docker-based tools (much simpler, no build etc. neccessary)

For further help, please use https://eosio.stackexchange.com/.

This issue-tracker here is mostly about bugs.

**Comment by jgiszczak** [comment]
Clion is effectively not supported.  My post is the extent of support.  Anyone not using the build scripts is expected to know what they are doing and solve their own problems.
