### ISSUE TITLE
"transfer" transaction "actions[0].action_trace.receipt.receiver == "tokenxchange" no longer exist?

### ISSUE THREAD

**Issue by kristieguo** [EOSIO/eos#5352]
Hi, in the account actions I query from block producers, I realized the "action_trace.receipt.receiver" in "transfer" transactions is no longer the actual sender or receiver of the transaction, instead the receiver became the contract name, such as "eosio.token". For exchanges, should we remove this logic (actions[0].action_trace.receipt.receiver == "tokenxchange) for accepting deposits?

**Comment by taokayan** [comment]
normally receiver = contract owner (the account who has the executing contract)

**Comment by taokayan** [comment]
closed as no reply. Please ask in eosio.stackexchange.com if you have further questions.
