### ISSUE TITLE
cleos create key --file or --to-console

### ISSUE THREAD

**Issue by yoo3740** [EOSIO/eos#5353]
I rebuild v1.2.0 and `cleos create key` command is not the same as before. 
The output is 

> ERROR: Either indicate a file using "--file" or pass "--to-console"

so I attatched `--to-console` , and it succeeded.
but  when I attatch `--file` it print out same error.

what's the difference? and why does not the second work?

**Comment by jgiszczak** [comment]
`--file` expects a filename argument before it will work.  It was added so that private keys could be written directly to disk, without ever being visible on screen.
