### ISSUE TITLE
Error: No wasm file found

### ISSUE THREAD

**Issue by akildemir** [EOSIO/eos#5357]
Hi all

I have run into that problem  which when i try to upload my contract into my local eosio testnet, although there is both wasm file and wast file and abi file the eosiocpp says no wasm file found.. 

I am working on mac os sierra what could be the problem?

Note: i had deleted some developers tools files for  when i was trying to remove them and it did not work. And developer tools were still working.
 Can this be the problem? If so, what can i do to repair them? Thanks!

**Comment by taokayan** [comment]
please try ```cleos set code accountName wastFileFullPath```

**Comment by akildemir** [comment]
@taokayan i tried with full path too but it still did not work but the good news is i asked same question on the telegram either and one guy said u should only use path to contract folder cuz what i was using was path to contract folder and then path to wasm file and then path to abi file. So eventually i solved the problem. It was probably about the version cuz i was doing it like what i told 1 month ago or something. Thanks anyway man
