### ISSUE TITLE
Unlinkable block

### ISSUE THREAD

**Issue by williamleecn** [EOSIO/eos#5363]
```
2018-08-22T04:25:32.647 thread-0   producer_plugin.cpp:309       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00bd1da28feb56b0d31c56383e230767315d10ec5f4dc0a9a328395596e8438b","previous":"00bd1da1591315791655cbf100df9ffd89064172219efb654e93b20875dc9128"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1036 push_block
```

running more than 10 days, but yesterday occur this error and sync stop

**Comment by vjoke** [comment]
which version? from the commit info, versions with 1.1.4 had resolved this issue.

**Comment by williamleecn** [comment]
newest ,v1.2.1

**Comment by wanderingbort** [comment]
@williamleecn Unlinkable block errors are a symptom of a problem, not the root problem.  In the log that had unlinkable block errors there should be a single error that precedes the unlinkable block errors.  That error will be the one we can use to identify the real issue at hand.  Do you still have the logs before this error?

**Comment by AllenYaoya** [comment]
i met the same error, it said '3030001 unlinkable_block_exception: Unlinkable block...'.

and i get another error ahead of it, see below:

'''
2018-08-23T12:21:28.811 thread-0   controller.cpp:1012  apply_block  ] e.to_    detail_string(): 3030000 block_validate_exception: Block exception
receipt does not match
    {"producer_receipt":{"status":"soft_fail","cpu_usage_us":4248,"net_usage_words":0,"trx":[0,"6929422a066f4c59a0427c330e66eb8d31890778f706f045651c8cc386a3a2b8"]},"validator_receipt":{"status":"executed","cpu_usage_us":4248,"net_usage_words":6,"trx":[0,"6929422a066f4c59a0427c330e66eb8d31890778f706f045651c8cc386a3a2b8"]}}
    thread-0  controller.cpp:989 apply_block 
2018-08-23T12:21:28.832 thread-0   controller.cpp:1036           push_block           ] 3030000 block_validate_exception: Block exception
receipt does not match
    {"producer_receipt":{"status":"soft_fail","cpu_usage_us":4248,"net_usage_words":0,"trx":[0,"6929422a066f4c59a0427c330e66eb8d31890778f706f045651c8cc386a3a2b8"]},"validator_receipt":{"status":"executed","cpu_usage_us":4248,"net_usage_words":6,"trx":[0,"6929422a066f4c59a0427c330e66eb8d31890778f706f045651c8cc386a3a2b8"]}}
    thread-0  controller.cpp:989 apply_block

    {}
    thread-0  controller.cpp:1016 apply_block
2018-08-23T12:21:28.832 thread-0   producer_plugin.cpp:309       on_incoming_block    ] 3030000 block_validate_exception: Block exception
receipt does not match
    {"producer_receipt":{"status":"soft_fail","cpu_usage_us":4248,"net_usage_words":0,"trx":[0,"6929422a066f4c59a0427c330e66eb8d31890778f706f045651c8cc386a3a2b8"]},"validator_receipt":{"status":"executed","cpu_usage_us":4248,"net_usage_words":6,"trx":[0,"6929422a066f4c59a0427c330e66eb8d31890778f706f045651c8cc386a3a2b8"]}}
    thread-0  controller.cpp:989 apply_block

    {}
    thread-0  controller.cpp:1016 apply_block
rethrow
    {}
    thread-0  controller.cpp:1036 push_block
'''

seems i have a bad block? is it the root cause of it??

**Comment by AllenYaoya** [comment]
refer to another issue #4884 ,this might due to i mixed used bnet_plugin and net_plugin. it might lead some blocks crashed.
i know bnet_plugin is a newer one. and it can only connect with those who also activate it. my question is bnet_plugin and net_plugin, which one is more recommended? Could i activate both of them at the same time? thanks

**Comment by heifner** [comment]
- net_plugin is the currently recommended p2p plugin.
- We have a theory on why bnet_plugin could cause the `unlinkable_block_exception`. However, we have not proven the theory.
- You can run both plugins at the same time.

**Comment by NorseGaud** [comment]
Using the newest release myself (1.2.2).
I'm running the following:
`cleos create account eosio testuser EOS6bHhxtKotwybaPwJufXtFiYumL3DGcitv2xvZ5s3Kpyz57qwH7 EOS6tARBHmwLNaep4bhWXnjLWbt9FEKRfAzuAE3KAs7MU1bTeV2YL`
and see
```executed transaction: f5a0ea909dc5277ce86a0697a9e2e0b2e6b8295afa6865ca3ba736a4fea838cb  200 bytes  454 us
#         eosio <= eosio::newaccount            {"creator":"eosio","name":"testuser","owner":{"threshold":1,"keys":[{"key":"EOS6bHhxtKotwybaPwJufXtF...
warning: transaction executed locally, but may not be confirmed by the network yet    ]```
Then, on my producer node, I see:
<pre>
2018-08-24T02:34:06.003 thread-0   producer_plugin.cpp:1302      produce_block        ] Produced block 000000571cc4cdaa... #87 @ 2018-08-24T02:34:06.000 signed by eosio [trxs: 1, lib: 86, confirmed: 0]
2018-08-24T02:34:06.004 thread-0   producer_plugin.cpp:330       on_incoming_block    ] Received block 4e4676d9ccd7ba95... #87 @ 2018-08-24T02:34:06.000 signed by eosio [trxs: 1, lib: 86, conf: 0, latency: 4 ms]
2018-08-24T02:34:06.503 thread-0   producer_plugin.cpp:1302      produce_block        ] Produced block 0000005802c3ba27... #88 @ 2018-08-24T02:34:06.500 signed by eosio [trxs: 0, lib: 87, confirmed: 0]
2018-08-24T02:34:06.504 thread-0   producer_plugin.cpp:330       on_incoming_block    ] Received block 3dea12e4f9304170... #88 @ 2018-08-24T02:34:06.500 signed by eosio [trxs: 0, lib: 87, conf: 0, latency: 4 ms]
2018-08-24T02:34:07.003 thread-0   producer_plugin.cpp:1302      produce_block        ] Produced block 000000595cdf3fe6... #89 @ 2018-08-24T02:34:07.000 signed by eosio [trxs: 0, lib: 88, confirmed: 0]
2018-08-24T02:34:07.004 thread-0   controller.cpp:1036           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"0000005968704d958f27fa382f88bb6faa7fcc8277d2a669ae349579d7b75222","previous":"000000583dea12e4f9304170deab2266a7cb137e19512c493cc06d02da4cf9e4"}
    thread-0  fork_database.cpp:151 add
2018-08-24T02:34:07.004 thread-0   producer_plugin.cpp:309       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"0000005968704d958f27fa382f88bb6faa7fcc8277d2a669ae349579d7b75222","previous":"000000583dea12e4f9304170deab2266a7cb137e19512c493cc06d02da4cf9e4"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1036 push_block</pre>

It will repeat the Unlinkable block after that until I do --delete-all-blocks on the producer node.

**Comment by cc32d9** [comment]
I had a crash last night with a fresh v1.2.2. 
Config.ini:
```
p2p-peer-address = seed2.greymass.com:9876
p2p-peer-address = node869-mainnet.eosauthority.com:9393
p2p-peer-address = br.eosrio.io:9876
p2p-peer-address = p2p.libertyblock.io:9800
p2p-peer-address = mainnet.libertyblock.io:9800
p2p-peer-address = peering.mainnet.eoscanada.com:9876
p2p-peer-address = p2p.eossweden.se:9876

plugin = eosio::bnet_plugin
bnet-endpoint = 0.0.0.0:4321
bnet-threads = 4
bnet-connect = nodebnet-mainnet.eosauthority.com:19393
bnet-connect = p2p.eosio.cr:20747
bnet-connect = node.eosflare.io:5222
```
nodeos console log attached. bnet reports a bad block at 2018-08-23T23:10:45.080 received from greymass, and then p2p plugin reports all connections being rejected (which should not be the case, the network did not have interruptions). Then nodeos crashed 
```
*** Error in `/usr/local/eosio/bin/nodeos': double free or corruption (fasttop): 0x00007f7d140e4d90 ***
```

[nodeos_1.2.2.crash.log](https://github.com/EOSIO/eos/files/2318005/nodeos_1.2.2.crash.log)

**Comment by cc32d9** [comment]
Also once I commented out p2p peers and left only bnet peers, nodeos complained constantly about unlinkable blocks, and was not advancing anywhere. Then I commented out all bnet statements and activated only p2p statements, and nodeos continued processing the blockchain as expected.

Looks like something is fundamentally broken in bnet plugin.

**Comment by heifner** [comment]
@cc32d9 How easily can you reproduce this? Would you be willing to test a patch?

**Comment by cc32d9** [comment]
@heifner quite easily over the weekend. The server runs already two nodeos instances in LXC containers over ZFS clones, so making a new test instance is a no-brainer.

**Comment by cc32d9** [comment]
with all p2p peers removed, and only bnet peers remaining, nodeos is still struggling with unlinkable blocks. Last irreversible block is not increasing:

```
2018-08-26T15:16:49.586 thread-0   producer_plugin.cpp:309       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cda890301be3e0af710107da117e9fe9f9c3301f7645e5a6a26371f21081","previous":"00c8cda7793a3acca1d537031130538733d2284d83f47d64a4f3214b9f8ff494"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1036 push_block
2018-08-26T15:16:50.018 thread-0   controller.cpp:1036           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865","previous":"00c8cda890301be3e0af710107da117e9fe9f9c3301f7645e5a6a26371f21081"}
    thread-0  fork_database.cpp:151 add
2018-08-26T15:16:50.018 thread-0   producer_plugin.cpp:309       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865","previous":"00c8cda890301be3e0af710107da117e9fe9f9c3301f7645e5a6a26371f21081"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1036 push_block
2018-08-26T15:16:50.078 thread-0   controller.cpp:1036           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865","previous":"00c8cda890301be3e0af710107da117e9fe9f9c3301f7645e5a6a26371f21081"}
    thread-0  fork_database.cpp:151 add
2018-08-26T15:16:50.078 thread-0   producer_plugin.cpp:309       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865","previous":"00c8cda890301be3e0af710107da117e9fe9f9c3301f7645e5a6a26371f21081"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1036 push_block
2018-08-26T15:16:50.096 thread-0   controller.cpp:1036           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865","previous":"00c8cda890301be3e0af710107da117e9fe9f9c3301f7645e5a6a26371f21081"}
    thread-0  fork_database.cpp:151 add
2018-08-26T15:16:50.096 thread-0   producer_plugin.cpp:309       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865","previous":"00c8cda890301be3e0af710107da117e9fe9f9c3301f7645e5a6a26371f21081"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1036 push_block
2018-08-26T15:16:50.514 thread-0   controller.cpp:1036           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cdaa45cda7316d03b78be6162b72239a1ea559686a874f80f073b83f1454","previous":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865"}
    thread-0  fork_database.cpp:151 add
2018-08-26T15:16:50.514 thread-0   producer_plugin.cpp:309       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cdaa45cda7316d03b78be6162b72239a1ea559686a874f80f073b83f1454","previous":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1036 push_block
2018-08-26T15:16:50.576 thread-0   controller.cpp:1036           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cdaa45cda7316d03b78be6162b72239a1ea559686a874f80f073b83f1454","previous":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865"}
    thread-0  fork_database.cpp:151 add
2018-08-26T15:16:50.576 thread-0   producer_plugin.cpp:309       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cdaa45cda7316d03b78be6162b72239a1ea559686a874f80f073b83f1454","previous":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1036 push_block
2018-08-26T15:16:50.602 thread-0   controller.cpp:1036           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cdaa45cda7316d03b78be6162b72239a1ea559686a874f80f073b83f1454","previous":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865"}
    thread-0  fork_database.cpp:151 add
2018-08-26T15:16:50.602 thread-0   producer_plugin.cpp:309       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"00c8cdaa45cda7316d03b78be6162b72239a1ea559686a874f80f073b83f1454","previous":"00c8cda983af84c521412c1437cf03a05f0e5463bd918829b7d29f1905410865"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1036 push_block

```

**Comment by cc32d9** [comment]
with one p2p peer enabled, it still keeps complaining about unlinkable blocks, but the head of the chain is moving forward.

**Comment by cc32d9** [comment]
at least it doesn't segfault after re-syncing with mainnet

**Comment by cc32d9** [comment]
when re-syncing finished, it can start with bnet peers only without complaints. But last_irreversible_block_num is increasing slower that real-time blocks.

**Comment by heifner** [comment]
@cc32d9 Let me see if I follow correctly. When you are in state of unlinkable blocks, installing new code does not get you out of that state. However, using new code, if you start over all is well?

**Comment by cc32d9** [comment]
@heifner , 
_When you are in state of unlinkable blocks, installing new code does not get you out of that state_ -- correct.

_using new code, if you start over all is well_ -- not exactly. From the same unlinkable state, I enabled a  p2p peer, and it re-synched, and then it could run without the p2p peer,

**Comment by cc32d9** [comment]
`net_plugin`. I added a legacy p2p peer, and the node got in-sync after a while.

**Comment by heifner** [comment]
@cc32d9 How long did you let `bnet_plugin` attempt to get you out of unlinkable blocks? How many threads are you running on `bnet_plugin`? How many `bnet-connect` entries?

**Comment by cc32d9** [comment]
@heifner a couple of minutes. i can re-do it for longer period if needed. My config is above: 4 threads and 3 bnet peers.

**Comment by heifner** [comment]
@cc32d9 Thanks. Forgot the config was above, oops. If you could test again and give it say 30 minutes, I would appreciate it.

**Comment by cc32d9** [comment]
it's running for about 30 minutes already, with the same errors. It keeps running, and I will check tomorrow again.

**Comment by heifner** [comment]
@cc32d9 Can you share your log output?

**Comment by datnv-ibl** [comment]
I got this issue last night: unlinkable_block_exception, node stop and got dirty database when start again.
Full log from startup to crash: 
https://drive.google.com/file/d/1pW6BiT8CUTfx14UqzAoc3f033D-cLguy/view?usp=sharing

**Comment by heifner** [comment]
@datnv-ibl What version of the eos.io?

**Comment by datnv-ibl** [comment]
It's v1.1.3

**Comment by TPixie** [comment]
I got the same issue. Running "eosio/eos-dev:latest" docker image, which contains nodoes v1.2.3, on Ubuntu 16.04 LTS. I'm using net_plugin, but no bnet.

**Comment by helperShang** [comment]
It's v1.2.5

**Comment by taokayan** [comment]
Please try using latest version with p2p plugin. Please ask in eosio.stackexchange.com if you have further questions.

**Comment by jgiszczak** [comment]
@rameshb444 The underlying issue is not resolved.  There is a workaround.  `bnet_plugin` is still unreliable.  Do not use `bnet-connect =` in your config.ini.  Use only `p2p-peer-address =` to connect peers.
