### ISSUE TITLE
How to upgrade the system (eos) of BP nodes?

### ISSUE THREAD

**Issue by lpx1988** [EOSIO/eos#5365]
When upgrading the BP system in the private chain, after the normal "make install", after the normal “make install”, try to use the original config.ini file to start nodeos, but it cannot start normally. **What is the standard upgrade process for BP in the main network?**

**Comment by jgiszczak** [comment]
The standard upgrade procedure is to read the [release notes](https://github.com/EOSIO/eos/releases) for each release and modify `config.ini` files accordingly.  The `Removal Notices` sections are the most necessary sections to review when upgrading `nodeos`, as newly unrecognized options will prevent `nodeos` from starting, but the full notes should be reviewed for relevant changes.

**Comment by lpx1988** [comment]
Thank you. @jgiszczak
