### ISSUE TITLE
Possible to add an artificial delay into block production?

### ISSUE THREAD

**Issue by GavinPacini** [EOSIO/eos#5367]
Hi all,

I am wondering if it is possible to configure my local dev node to delay block production? This would really help me with some testing.

Thanks!

**Comment by jgiszczak** [comment]
You may edit `eos/libraries/chain/include/eosio/chain/config.hpp`, change `const static int      block_interval_ms = 500;` (line 42 in most branches) to a larger number, and recompile.  Of course synching two nodes with different values for that constant would cause Bad Things to happen, so don't do that.  With a single node, or multiple nodes from that binary, you may choose any value you like.
