### ISSUE TITLE
when i set contract it's no reply,reading  wasm files

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5369]
1、![image](https://user-images.githubusercontent.com/11773000/44460429-9c494c80-a63f-11e8-9d13-dcff8094befa.png)
2、here is eosio.token folder:
![image](https://user-images.githubusercontent.com/11773000/44460488-d74b8000-a63f-11e8-8f44-10945dc1b317.png)

**Comment by jgiszczak** [comment]
What's the corresponding log output from `nodeos`?

**Comment by taokayan** [comment]
closed as no reply. Please ask in eosio.stackexchange.com if you have further questions.
