### ISSUE TITLE
Add result validation for slow_test and api_test

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#537]
All (or at least most) tests in slow_test and api_test can pass without contracts actually doing anything (like all memory_test tests passed when WASM import list exceeded 10,000 bytes. (Only tests that expect an exception to be thrown failed)  So the current tests just verify that an exception isn't thrown by push_transaction and then verifies that blocks were created.

**Comment by heifner** [comment]
This is too general of an issue. Many tests have been added and updated. There is always room for improvement.
