### ISSUE TITLE
[TEST] nodeos_voting_lr_test, sporadic failure

### ISSUE THREAD

**Issue by lazaridiscom** [EOSIO/eos#5372]
## Problem
`nodeos_voting_lr_test` fails sporadically (around 1 of 5 times), see #5036 (issue was closed too fast)

## Reproduction

run the test 20 times

`ctest --output-on-failure -R nodeos_voting_lr_test --repeat-until-fail 20`

**Comment by taokayan** [comment]
I guess some results of integration tests that are related to producer/voting/contracts might vary due to machine CPU and timing. However we'll look into that in the future.

**Comment by lazaridiscom** [comment]
I could bet that tao-issue-ripper-kayan has not looked into this...
