### ISSUE TITLE
[HELP]  Need advise on creation of account 

### ISSUE THREAD

**Issue by yashbhavsar007** [EOSIO/eos#5373]
I am working on ICO based on eosio so what actually i need to do is i want to make a system in which all users come to signup and system generate  a key pair for them and give them key and registered account.
So,My questions are as below
1) Can we create an account(i will call it as master account)which is having ram and gives all the user 
    their ram,cpu and net is this possible?
2) Is there any way that if user do transaction from their key and ram,cpu and net can be used of master 
    account?
3) Is there any other way that may be more feasible for ico ?

I know that if we give users to handle their own account then it will make trouble for them to handle all the account resource. **Suggestions are admired!**

**Comment by lazaridiscom** [comment]
Hi there. A better media for such requests would be https://eosio.stackexchange.com/

**Comment by taokayan** [comment]
I think No. 1 is ok by creating a new account and stake cpu/net for the new created account.
No.2 is indirectly ok by staking cpu/net for the new created account
No.3 is too broad, but what kind of feasible is subjective.

**Comment by taokayan** [comment]
closed as no reply. Please ask in eosio.stackexchange.com if you have further questions.
