### ISSUE TITLE
Why core_symbol.hpp was deleted?

### ISSUE THREAD

**Issue by JeanoLee** [EOSIO/eos#5374]
Hi Guys.

Now I'm developing token contract for dapp project.
My token code is based on eosio.token contract code.

but token contract wasn't compiled when I updated EOS version 1.2.1.
eos compiler couldn't find <contracts/core_symbol.hpp>

So. I traced commits, 

0ec841b77650e0b0ae43ebbf33b84b4a30fb3dcb

https://github.com/EOSIO/eos/pull/4844/commits/0ec841b77650e0b0ae43ebbf33b84b4a30fb3dcb

this commit has deleted <contracts/core_symbol.hpp> file.

Why It was deleted???

@larryk85

**Comment by larryk85** [comment]
core_symbol.hpp is a generated file, the one that was deleted in the source directory was there to clean up the directory, eosiocpp already adds the include directory of the generated core_symbol.hpp.  You should not have been including that specific version of core_symbol.hpp as it was configured with the default symbol name.  In addition, eosiocpp has been flagged as deprecated and will be removed in the next release, so, I would suggest using eosio.wasmsdk for future development.
