### ISSUE TITLE
Dead lock of my account

### ISSUE THREAD

**Issue by cuizx** [EOSIO/eos#5387]
hi,  my  account has 10 EOS, but no resouces. So I cannot buy ram or stake for cpu and bandwidth. Actually ,I almost can do nothing. Is there any solution?   In reality, i cannot find any other account to do this instead.

**Comment by taokayan** [comment]
Please run ```./cleos system delegatebw``` with ```--buyram```. This allows you to delegate CPU, NET and buyram in one transaction. You may need to run it multiple times until one of the producer accept your transaction.
