### ISSUE TITLE
database dirty flag set (likely due to unclean shutdown): replay required #4742

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5393]
--hard-replay or --replay-blockchain does not work,how to solve this..?

**Comment by csquan** [comment]
when use --replay options,it delete state ,use --hard-replay,it rescontruct,but all this does not make use.is this a bug?

**Comment by csquan** [comment]
refer to https://github.com/EOSIO/eos/issues/4742,how to sove this?

**Comment by taokayan** [comment]
Please refer to #4742

**Comment by csquan** [comment]
all opts does not work,I have try many ways.

From: DU Jiaen
Date: 2018-08-24 10:29
To: EOSIO/eos
CC: csquan; Author
Subject: Re: [EOSIO/eos] database dirty flag set (likely due to unclean shutdown): replay required #4742 (#5393)
Please refer to #4742

**Comment by csquan** [comment]
does not work...........................
