### ISSUE TITLE
Question about DPoS-irreversibility

### ISSUE THREAD

**Issue by lyang36** [EOSIO/eos#5400]
Hi, in the closed issue #3088 ,  it is stated that "LIB does not advance until 2/3+1 producers implicitly agree on the LIB". However,  in the current code, it reads: ```return blocknums[ (blocknums.size()-1) / 3 ];``` as the ```dpos_last_irreversible```. However, this does not imply "until 2/3+1 producers implicitly agree on the LIB". Do we need to check ```blocknums.size() >= producers.size``` or change the ```dpos_last_irreversible``` to a point ```lib``` with ```(blocknums.size() - lib) > 2/3*producers.size```?

**Comment by taokayan** [comment]
This is an improved consensus algorithm combining DPOS & BFT. Under this implementation, a transaction need to wait about 320-340 blocks until it become irreversible.

**Comment by lyang36** [comment]
Hi @taokayan I understand it is an improved consensus algorithm. However, the code does not imply "until 2/3+1 producers implicitly agree on the LIB".  And my concern is not addressed.  
I think the correct implementation of the algorithm should be changing ```dpos_last_irreversible``` to be 
```dpos_last_irreversible = max(0, blocknums.size() - 2/3*producers.size)```

**Comment by taokayan** [comment]
This change is the result of applying BFT which assume there can be up to 1/3 of malicious producers.

**Comment by lyang36** [comment]
@taokayan The problem is that in the current implementation line 28 of block_header_state.cpp, 
```return blocknums[ (blocknums.size()-1) / 3 ];``` assumes much more than that. 

For instance, if the ```blocknums.size < 1/3 producers.size```, then ```blocknums[ (blocknums.size()-1) / 3 ]```means less than 1/9 producers confirm. 

Indeed this case is rare (for instance the network splits), but it is still possible a ```proposed-irb``` become irb whereas less than 2/3 producers confirming it.

**Comment by lyang36** [comment]
Suppose we have 4 producers, A, B, C, D. 
Consider the following extreme case: suppose for now blocknums = [A, B, C, D] and then the network splits and only A, B are presented in the network. Then by the code, blocknums of A, B, C, D will all become irb without the confirmations from C and D.

**Comment by lyang36** [comment]
@heifner of course. 
hmm.
Does it mean the few blocks after the genesis block do not have double 2/3 confirmations before they become irb?
At the beginning of the chain, the map ```producer_to_last_implied_irb``` do not even record all the producers. 
Indeed that part of the chain is produced by the anonymous producers and cannot be changed anyway.

**Comment by lyang36** [comment]
Also, it seems like ```producer_to_last_implied_irb``` will keep growing? For each new producer_schedule version, it increases by at least 1? Will this become a problem?

**Comment by heifner** [comment]
It is cleared in `maybe_promote_pending`

**Comment by lyang36** [comment]
Okay, got it. I've checked that part. It answers my question. Thanks.
