### ISSUE TITLE
wallet always empty

### ISSUE THREAD

**Issue by ldupisani** [EOSIO/eos#5405]
Same as this issue:

https://github.com/EOSIO/eos/issues/2989

But none of the solutions presented worked for me:

Following this tutorial:

https://eosio-nodeos.readme.io/docs/docker-quickstart

adding: --wallet-url http://localhost:8888

to the alias also didn't work either

I just ended up getting:

Error 3110002: Missing Wallet API Plugin
Ensure that you have eosio::wallet_api_plugin added to your node's configuration!
Otherwise specify your wallet location with --wallet-url argument!
Error Details:
Wallet is not available

Also, opening and unlocking wallets didn't make any difference.

I was hoping it was the list function, but trying to write keys to unlocked wallets also failed.

**Comment by k5trismegistus** [comment]
I managed to work.

First, use v1.1.5 image
```
> docker pull eosio/eos-dev:v1.1.5
```

and run contaier with this (specify plugin eosio::wallet_api_plugin and eosio::wallet_plugin)
```
docker run --rm --name eosio -it -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev:v1.1.5  /bin/bash -c "nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin  -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false"
```

then, create alias as this
```
alias cleos='docker exec -it eosio /opt/eosio/bin/cleos -u http://localhost:8888 --wallet-url http://localhost:8888'
```

Now, `cleos wallet list` returns created wallet!

```
> cleos wallet list
Wallets:
[
  "default *"
]
```

```

**Comment by zachalam** [comment]
I am fairly certain that either:
a) something is wrong with the 'alias' for `cleos` provided in the documentation (available here: https://developers.eos.io/eosio-nodeos/docs/docker-quickstart). 
b) keosd should not be "re-launching" before each cleos command.

Here is the  alias provided in the quickstart, and it's results:
```
alias cleos='docker exec -it eosio /opt/eosio/bin/cleos -u http://localhost:8888'
```
```
root@eos:~# cleos wallet create
"/opt/eosio/bin/keosd" launched
Error 3120001: Wallet already exists
Try to use different wallet name.
```
```
root@eos:~# cleos wallet list
"/opt/eosio/bin/keosd" launched
Wallets:
[]
```

For those in need of a temporary solution, you can SSH into the running docker container and access the wallet list completely fine using cleos.
```
docker exec -it eosio /bin/bash
```
```
root@436f779f7d52:/# cleos wallet list
Wallets:
[
  "default *"
]
```
If anyone has a solution for the docker quickstart, please share!

**Comment by sensay-nelson** [comment]
I have found with a fresh start of kleosd, the wallet needs to be "opened" before it will be listed as available for unlock. 
```
$ cleos wallet list
Wallets:
[]

$ cleos wallet open
Opened: default

$ cleos wallet list
Wallets:
[
  "default"
]
```

**Comment by andriantolie** [comment]
The document has changed a lot since this issue is posted. Please take a look at the newest document https://developers.eos.io/eosio-nodeos/docs/docker-quickstart
