### ISSUE TITLE
i push deferred action with eosjs，aciton return success，but the deferred action execute fail，call eosio onerror

### ISSUE THREAD

**Issue by jimoful** [EOSIO/eos#5406]
i deploy my contract in test net, it work well.when i deploy it in main net,it just return error as my title description

**Comment by taokayan** [comment]
deferred transaction is not guaranteed to be success. As a result, it might fail in subjective or objective way, or never get a chance to be executed. Furthermore, it depends on various situations including the cpu/net resource usages, timing,... etc. However, setting a longer expiration time may results in higher chance that the corresponding deferred transaction get executed.

**Comment by jimoful** [comment]
but i have try set expiration time as 6min and have 10 EOS net/cpu, it steel don't work!!
