### ISSUE TITLE
ubutun 18 make test What is the reason for failure?

### ISSUE THREAD

**Issue by flyskyfloow** [EOSIO/eos#5407]
The following tests FAILED:
         38 - restart-scenarios-test-resync (Failed)
         40 - restart-scenarios-test-none (Failed)
         45 - bnet_nodeos_voting_lr_test (Failed)
Errors while running CTest
Makefile:119: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by taokayan** [comment]
The test results of these tests might be subject to machine CPU power, RAM usage, harddisk performance. Would you try to run it several times to see if you can get any positive result?

**Comment by taokayan** [comment]
closed as no reply. Please ask in eosio.stackexchange.com if you have further questions.
