### ISSUE TITLE
How do I restore reserved RAM for creating account?

### ISSUE THREAD

**Issue by manh-vv** [EOSIO/eos#5409]
>  The account creator must reserve the RAM required to store the new account until the new account stakes tokens to reserve its own RAM [white paper](https://github.com/EOSIO/Documentation/blob/master/TechnicalWhitePaper.md#accounts)

Does that mean I have to ask account owner to stake tokens to reserver RAM so I can get back my reserve RAM?

**Comment by taokayan** [comment]
There's no way to delete an account at the moment. The ram spent on the new account will be billed by the creator.
