### ISSUE TITLE
get actions return empty when use mongo_db_plugin

### ISSUE THREAD

**Issue by hippokylejan** [EOSIO/eos#5410]
eosio/eos:v1.2.2

using mongo_db_plugin to process historical data, the configuration is as below.
plugin = eosio::chain_api_plugin
plugin = eosio::mongo_db_plugin
plugin = eosio::history_plugin
plugin = eosio::history_api_plugin

mongodb-uri = mongodb://mongodb_eos:27017/EOS
mongodb-queue-size = 1024
mongodb-filter-on = *

It returns empty when using cleos to get actions of account, while the account exists caused I can get correct response when calling get account api.

**Comment by chengevo** [comment]
`cleos` tool read data from `history_plugin`, not `mongodb_plugin`, thus you should add an `filter-on` option:

```
filter-on = *
```

**Comment by heifner** [comment]
`cleos` does not currently provide an interface for reading from a mongo db populated via mongo_db_plugin. Use other publicly available tools for extracting mongodb data.
