### ISSUE TITLE
 'eosiolib/core_symbol.hpp' file not found

### ISSUE THREAD

**Issue by chuang39** [EOSIO/eos#5419]
When I compile my code for abi , I got the following error. However, if I compile the code with v1.1.0, the compilation is fine. Any suggestion?

$ eosiocpp -o testapp.wast testapp.cpp ---No error
$eosiocpp -g testapp.abi testapp.cpp
In file included from ~/myapp/eos/contracts/testapp/testapp.cpp:1:
In file included from ~/myapp/eos/contracts/testapp/testapp.hpp:14:
In file included from ~/myapp/eos/contracts/eosiolib/asset.hpp:5:
~/myapp/eos/contracts/eosiolib/symbol.hpp:2:10: fatal error: 'eosiolib/core_symbol.hpp' file not found
#include <eosiolib/core_symbol.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Error while processing ~/myapp/eos/contracts/testapp/testapp.cpp.

**Comment by guojinggit** [comment]
same problem to me,help.

**Comment by chuang39** [comment]
@srmcatee1110 That workaround worked. Thanks! Btw, I think community should fix this asap. It is broken for a while.

**Comment by chuang39** [comment]
Btw, just curious if I would like to contribute some patch, which branch should I submit to? Is there a process on doing that?

**Comment by lazaridiscom** [comment]
@chuang39 , against `release/1.2.x`

But as to my knowledge, the *.in files are used during the build/install process, so you possibly should await a comment of some core-dev.

To ensure its a bug: this sequence should clone/build/install all relevant files:

```bash
git clone https://github.com/EOSIO/eos.git --recursive
cd eos
./eosio_build.sh
sudo ./eosio_install.sh
```

**Comment by chuang39** [comment]
Lazaridis, Thanks for response. Yep, I think I followed that process. Should be easy to repro.

**Comment by lazaridiscom** [comment]
I can confirm your bug, by adding an `#include <eosiolib/symbol.hpp>` to the `hello.cpp` demo.

related: #5285 #5297 

# Problem

Summary: `core_symbol.hpp` is generated based on `core_symbol.hpp.in`. It does not find its way to an include-path

## Workaround

copy the generated file into a location where its found by eosiocpp

```bash
cd eos
cp build/libraries/chain/include/eosio/chain/core_symbol.hpp contracts/eosiolib/
```

**Comment by lazaridiscom** [comment]
see a comment: 

https://github.com/EOSIO/eos/pull/5401/files/5b114ad976d20e6827bb2a5ad17ef945c5db5cc9

**Comment by xJonathanLEI** [comment]
@lazaridiscom See my reply ;)

https://github.com/EOSIO/eos/pull/5401/files/5b114ad976d20e6827bb2a5ad17ef945c5db5cc9#r212826380

**Comment by taokayan** [comment]
Please test with cdt. Please ask in eosio.stackexchange.com if you have further questions.
