### ISSUE TITLE
3030000 block_validate_exception: Block exception receipt does not match

### ISSUE THREAD

**Issue by AllenYaoya** [EOSIO/eos#5420]
when i resynchronize JungleTestNet block data, i met below error when i resync to block:1310498. i have tried several times, delete existing data and rerun the code, but this error occurs every time when it comes to block:1310498. 

i have commented out **bnet_plugin**, and use **net_plugin**. Also, just use one **p2p-peer-address = jungle.cryptolions.io:19876**.

seems i have a bad block? but how does this happen? Could anyone help figuring this out? Thanks so much!

```
2018-08-25T07:47:42.834 thread-0   controller.cpp:1012           apply_block          ] e.to_detail_string(): 3030000 block_validate_exception: Block exception
receipt does not match

 {"producer_receipt":{"status":"soft_fail","cpu_usage_us":4248,"net_usage_words":0,"trx":[0,"6929422a066f4c59a0427c330e66eb8d31890778f706f045651c8cc386a3a2b8"]},"validator_receipt":{"status":"executed","cpu_usage_us":4248,"net_usage_words":6,"trx":[0,"6929422a066f4c59a0427c330e66eb8d31890778f706f045651c8cc386a3a2b8"]}}
```

**Comment by AllenYaoya** [comment]
sorry, i may issue this in EOS-Jungle-Testnet.

**Comment by imlaochen** [comment]
i occured the same problem. and how did you fix it?

**Comment by jgiszczak** [comment]
See the Jungle Testnet Telegram channel pinned message for instructions regarding how to successfully sync.
