### ISSUE TITLE
Use "eosiocpp" library problem

### ISSUE THREAD

**Issue by 414054375** [EOSIO/eos#5421]
I want to compile .cpp file to .wast/.abi file without communicating with eosio full node server. Can I use "eosiocpp" library seperately?  

Or there are other more convenient ways?

Need Help!!!

**Comment by 414054375** [comment]
@xJonathanLEI  I know it doesn't connect with the mainnet, but compiling file still needs to clone the whole project and do the instruction "eosiocpp". Is there any other way to compile the .cpp file more convenient?

**Comment by xJonathanLEI** [comment]
In that case, you may set up your own cloud compilation service. Then you can install eos once and compile everywhere ;)

**Comment by jgiszczak** [comment]
The [EOS.IO wasmsdk project](https://github.com/EOSIO/eosio.wasmsdk) is intended to provide a stand-alone way of compiling contracts, without requiring a build of the main project.  It is not yet complete, but it should mostly work.  You may try it out, and build your process around it, as it will be the supported path in the future.  The `eosiocpp` tool is currently deprecated and will be removed entirely once wasmsdk and its documentation are ready.
