### ISSUE TITLE
New EOS Mainnet account with no creator logged

### ISSUE THREAD

**Issue by Soleone** [EOSIO/eos#5424]
### Background

There's a service called [signupeoseos](https://medium.com/@cc32d9/a-new-way-to-create-eos-accounts-signupeoseos-dapp-39cdb1cebd21) that let's you transfer EOS with a memo from e.g. an exchange to create a new EOS acccount.

### Problem

It seems like through that service every new account created ends up with a blank "creator":

![image](https://user-images.githubusercontent.com/2923/44623470-496cd080-a89d-11e8-89df-32ed84f7383a.png)

### Expected

I would expect every new EOS account to be able to point back to its creator account that called the `newaccount` action on the `eosio` account.

### More info

* Account with smart contract: https://bloks.io/account/signupeoseos
* New user account with no creator: https://bloks.io/account/rvrkingfishr

### Additional Thoughts

* Is this because the `newaccount` action was maybe called as an inline action? (i am not sure if that is the case, haven't looked at the signupeoseos smart contract yet)
* Is this more of an underlying eosio issue or just an issue with those block explorers? Is it expected that sometimes the account creator would have to be looked up differently?

**Comment by tbfleming** [comment]
Accounts don’t point back to their creator accounts in nodeos. Some network monitors track that; how they track it and how they display it is up to them.

**Comment by heifner** [comment]
```
> db.action_traces.find({"act.data.name":"rvrkingfishr"}).pretty()
{
	"_id" : ObjectId("5b7e684df9a2f323e8f4c683"),
	"receipt" : {
		"receiver" : "eosio",
		"act_digest" : "338734fbb673704730bde6454d13b15510a0787d9da25138168c88ccae8e1a90",
		"global_sequence" : 36771423,
		"recv_sequence" : 8485218,
		"auth_sequence" : [
			[
				"signupeoseos",
				1328
			]
		],
		"code_sequence" : 7,
		"abi_sequence" : 8
	},
	"act" : {
		"account" : "eosio",
		"name" : "newaccount",
		"authorization" : [
			{
				"actor" : "signupeoseos",
				"permission" : "active"
			}
		],
		"data" : {
			"creator" : "signupeoseos",
			"name" : "rvrkingfishr",
			"owner" : {
				"threshold" : 1,
				"keys" : [
					{
						"key" : "EOS6zxEBtJJwJ31tDcyM2Np4bcYw6jrBeFHW6vFi4XEmvbf4DQfqR",
						"weight" : 1
					}
				],
				"accounts" : [ ],
				"waits" : [ ]
			},
			"active" : {
				"threshold" : 1,
				"keys" : [
					{
						"key" : "EOS6zxEBtJJwJ31tDcyM2Np4bcYw6jrBeFHW6vFi4XEmvbf4DQfqR",
						"weight" : 1
					}
				],
				"accounts" : [ ],
				"waits" : [ ]
			}
		},
		"hex_data" : "80a9c254553d99c3701b768b4d07efbe0100000001000316116a3c6ba368b08600e9cbe2ce905b894f450ed890e95cd0449c2efd96ff74010000000100000001000316116a3c6ba368b08600e9cbe2ce905b894f450ed890e95cd0449c2efd96ff7401000000"
	},
	"elapsed" : 365,
	"cpu_usage" : 0,
	"console" : "",
	"total_cpu_usage" : 0,
	"trx_id" : "5b3d73945f9b3c57d5fff84cf22aea8802e6d9cc9fc14e6686ceb7f7103bc242",
	"block_num" : 6461822,
	"block_time" : "2018-07-18T04:52:36.000",
	"producer_block_id" : "0062997e48ab12b6cb0eec976aa91b7f2660dfd461c10a1dc26b49f8a5c1fabe",
	"account_ram_delta" : [
		[
			"rvrkingfishr",
			2996
		]
	],
	"trx_status" : "executed",
	"createdAt" : ISODate("2018-08-23T07:54:53.650Z")
}
```

**Comment by tbfleming** [comment]
^ a reason for monitors to switch to the mongodb plugin
