### ISSUE TITLE
how to get JSON data of eosflare.io??

### ISSUE THREAD

**Issue by flygonsam** [EOSIO/eos#5426]
I want to use my eos account infomation on my own app(such as total balance, actions info(id, time, type, info...just like eosflare.io). But I cant find api for it.
Help me pleaaaaaaaaaaaaaaaaaaaaase!!

**Comment by xJonathanLEI** [comment]
eosflare.io is a blockchain browser, not a public node. You need a public node to get JSON data. eosflare.io might have public nodes but I'm not aware of any.

You may try this one out:
https://api.helloeos.com.cn

    $ cleos -u https://api.helloeos.com.cn get info

**Comment by flygonsam** [comment]
Thank you so much.....
