### ISSUE TITLE
Create Currency Not Working

### ISSUE THREAD

**Issue by srmcatee1110** [EOSIO/eos#5427]
I have the following script which establishes a node and then compiles eosio.token.  I attempt to create a currency.  However, nothing is there.

Please note this is all on my own private node and I am using 1.1.6.

#setup node
docker run --rm --name eosio -d -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev:v1.1.6  /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false"
alias cleos='docker exec -it eosio /opt/eosio/bin/cleos -u http://0.0.0.0:8888 --wallet-url http://0.0.0.0:8888'

#copy code to contracts
docker exec eosio bash -c 'cd /eos/contracts/eosio.token && eosiocpp -o eosio.token.wast eosio.token.cpp'

# I am using 1.1.6.  I had to go to /eos/contracts/eosiolib and change core_symbol.hpp.in to core_symbol.hpp
docker exec eosio bash -c 'cd /eos/contracts && eosiocpp -g eosio.token/eosio.token.abi eosio.token/eosio.token.cpp'

#create and open wallets - keys should be in them
#if you have a prior wallet copy it to /tmp/eosio/data as sudo
cleos wallet open -n bob

#Unlock nesha wallet - this will be the private key for your wallet
cleos wallet unlock -n bob

#create account with wallet keys
cleos create account eosio bob <ownerkey> <activekey>

#set eosio.token contract to account.
cleos set contract bob /eos/contracts/eosio.token -p bob@active

# create tokens.
cleos push action bob create '{"issuer":"bob","maximum_supply":"1000000.00 JCK"}' -p bob

#issue tokens
cleos  push action bob issue '{"to":"bob","quantity":"1000.00 JCK", "memo":"airdrop"}' -p bob

#up to this point I have had no errors
#check balance
cleos get table eosio.token bob accounts
#k this does not work.  Says account is not on block chain....

Should I have a table at this point?

**Comment by xJonathanLEI** [comment]
This is not a create currency issue. It's a known `eosiocpp` bug.

See this issue: #5419 
See this PR fixing this problem: #5401 

They should merge the PR **ASAP**, or more people are gonna complain about it. Meanwhile, you may add a new line to the 115th line at `tools/eosiocpp.in` :

    -extra-arg=-I@CMAKE_BINARY_DIR@/contracts \

And then run install again. Your `eosiocpp` should now work.

**Comment by srmcatee1110** [comment]
Thanks for quick reply.  I will give this a try.

**Comment by jgiszczak** [comment]
Use `cleos get table bob bob accounts`.  The `get table` help text is misleading.  The first argument is the account on which the contract was deployed, not the contract name.  The text is being corrected in #5448.

**Comment by srmcatee1110** [comment]
Figured it out.  Please close.
