### ISSUE TITLE
Docker 1.2.3 Does not start

### ISSUE THREAD

**Issue by srmcatee1110** [EOSIO/eos#5428]
When starting the latest in the docker hub it does not start.  docker ps gives an empty list.

Here is the command I execute after downloading the repository.
docker run --rm --name eosio -d -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev  /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false"

**Comment by cthacker** [comment]
I believe the issue is that nodeos no longer has the wallet plugin

**Comment by odarboe** [comment]
To: @srmcatee1110 
 @cthacker is right remove `--plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin`  when starting nodeos.

**Comment by srmcatee1110** [comment]
That worked.  Thank you.

**Comment by srmcatee1110** [comment]
K.  Without the plugin.  How do I specify wallet locations?

**Comment by jgiszczak** [comment]
`keosd` manages the wallet files.  It accepts the `--wallet-dir` argument to specify that location.  It's specified as `/opt/eosio/bin/data-dir` in the Docker compose file.
