### ISSUE TITLE
How to clear data in multi_index Database if i want to drop an token contracts and release RAM?

### ISSUE THREAD

**Issue by yyh1102** [EOSIO/eos#5431]
In the current version, i only find the way to release RAM an contract occupied is to set a new and smaller contract with the same account. But i cannot release the RAM in the multi_index Database and the data is still there!  

How to release these RAM in multi_index Database ?

**Comment by yyh1102** [comment]
@xJonathanLEI Thx for replying. Are there any plans in EOSIO to support this feature in the future?

**Comment by xJonathanLEI** [comment]
Check this out #5380 

Note that even if this gets implemented it would result in a hard fork. So a long way to go.

**Comment by taokayan** [comment]
You need to make an action to delete several rows each time.

**Comment by yyh1102** [comment]
@xJonathanLEI @taokayan Thank you both！

**Comment by yhc166188** [comment]
> You need to make an action to delete several rows each time.

I wonder which command this should use?
