### ISSUE TITLE
where can I find my eos config.ini file ?

### ISSUE THREAD

**Issue by zhousi666** [EOSIO/eos#5436]
系统配置：
	- 操作系统版本: centos 7
	- 可用内存: 8GB 以上
	- 可用磁盘: 20G 以上

this is my install process:

```
    yum install -y centos-release-scl 
    yum install -y devtoolset-7	
    yum install -y python33.x86_64
    yum install -y gcc gcc-c++ make patch cmake automake autoconf libtool ocaml doxygen graphviz-devel libicu-devel bzip2-devel gmp-devel python-devel gettext-devel sudo git

    cd /root	
    git clone https://github.com/EOSIO/eos --recursive	
    cd eos/	
    git submodule update --init --recursive

    ./eosio_build.sh

    cd build
    make install
```
where I can find my eos config.ini file ?  Or I generate it by myself . Can  help me ?

**Comment by xJonathanLEI** [comment]
~/.local/share/eosio/nodeos/config/config.ini

**Comment by jgiszczak** [comment]
After installation, you must run `nodeos` at least once to generate the `config.ini` file in the location described by @xJonathanLEI.  You may run `nodeos` with no command line arguments, shut it down with Ctrl-C, then edit the newly created file and relaunch `nodeos`.
