### ISSUE TITLE
"invalid symbol name" when push contract action

### ISSUE THREAD

**Issue by spartucus** [EOSIO/eos#5440]
Env: Ubuntu 16.04 x64, eos - v1.2.2 local single testnet.
I have this contract with action like:
```
// contract.hpp
...
// @abi action
void regorc(name oracle, name method, asset price, asset stake)
```

```
// contract.cpp
void contract::regorc(name oracle, name method, asset price, asset stake)
{
    print("regorc enter");
    ...
    print("regorc leave");
}
```

```
// contract.abi
{
      "name": "regorc",
      "base": "",
      "fields": [{
          "name": "oracle",
          "type": "name"
        },{
          "name": "method",
          "type": "name"
        },{
          "name": "price",
          "type": "asset"
        },{
          "name": "stake",
          "type": "asset"
        }
      ]
    }
```

and I have `SYS` token, and transfer SYS is fine.

so call this action:
```
cleos push action contract1234 regorc '["namenamename", "mmm", "1.0000 SYS", "1.0000 SYS"]' -p contract1234
```
it returns with error like:
![image](https://user-images.githubusercontent.com/6071887/44649733-4a297200-aa17-11e8-9e78-c9a7a58ff357.png)

It's never get the chance to call into `regorc`, because no `regorc enter` log prints.

Any ideas?

**Comment by spartucus** [comment]
Hi @xJonathanLEI , are you using v1.2.2 ? What's your CORE_SYMBOL? Is it default `SYS`?

**Comment by xJonathanLEI** [comment]
Yes I'm using v1.2.2, and my `CORE_SYMBOL` is `SYS`. The core symbol should not matter as the error thrown was from a call to `is_valid()` of the symbol, which simply performs checks on format, not the token existence.

**Comment by spartucus** [comment]
You are right, I'm using your demo, and it works. So I think there's something wrong with my code. Thanks for help. :)
