### ISSUE TITLE
Non-executables under /opt/eosio/bin

### ISSUE THREAD

**Issue by NorseGaud** [EOSIO/eos#5449]
Investigation of the eosio/eos docker image shows the following layer:
ebd41e1366c449ea1df65b1132fc73b2c2e345e2e0ca35f21cc4b501e1027812
Within it, nodeos.sh. However, inside of that, there is reference to "/opt/eosio/bin/data-dir". A bin directory should not contain anything but executables.

With that understanding, this is a request to move "data-dir" back into /opt/eosio. I'm unsure how to modify the images on docker, so if someone knows how, please let me know and I will do it. Otherwise, can the devs suggest the best course of action to get this modified within all executables and images?

**Comment by NorseGaud** [comment]
Looks more widespread. It's in a lot of the configs, etc. This would be a big overhaul, but I believe it's something necessary for software maturity.

**Comment by lazaridiscom** [comment]
I guess an `opt/eosio/var/data-dir` would do it

**Comment by NorseGaud** [comment]
Thanks @lazaridiscom, I wasn't aware they solidified the issue template so I've been avoiding it for now. It's good to lead the way with that stuff, so I'll start doing it.

Var works too! http://www.linfo.org/var.html

**Comment by taokayan** [comment]
closed as it is already solved. Please ask in eosio.stackexchange.com if you have further questions.
