### ISSUE TITLE
eosio.system contract failure

### ISSUE THREAD

**Issue by younggege** [EOSIO/eos#5453]
when I set contract eosio.system ,it comes errors as flow:
`2018-08-28T03:24:17.740 thread-0   wasm_interface.cpp:929        eosio_assert         ] message: unable to find key 
2018-08-28T03:24:17.741 thread-0   http_plugin.cpp:475           handle_exception     ] FC Exception encountered while processing chain.push_transaction
2018-08-28T03:24:17.741 thread-0   http_plugin.cpp:476           handle_exception     ] Exception Details: 3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
assertion failure with message: unable to find key
    {"s":"unable to find key"}
    thread-0  wasm_interface.cpp:930 eosio_assert
pending console output: 
    {"console":""}
    thread-0  apply_context.cpp:61 exec_one
`

**Comment by firesWu** [comment]
change `CORE_SYMBOL_NAME = "SYS"` to  `CORE_SYMBOL_NAME = "EOS"`  in eosio_build.sh  and rebuild.

**Comment by xJonathanLEI** [comment]
@firesWu There's no need to manually modify the `eosio_build.sh` file. Use the argument instead:

    $ sudo ./eosio_build.sh -s EOS

That said, I believe the problem of OP is not with the core symbol itself, but rather that he didn't properly initialize the chain by **creating system accounts**, **deploying token contract** and **creating the core symbol token**.

Check this out: #3134

https://github.com/EOSIO/eos/issues/3134#issuecomment-392688982

This might be what the OP is looking for.

**Comment by taokayan** [comment]
agree, please checkout #3134
