### ISSUE TITLE
CPU and NET won't reset if used > max after 3 days

### ISSUE THREAD

**Issue by datnv-ibl** [EOSIO/eos#5454]
I have to wait until the cpu price go down and make a transaction to reset the cpu & net used after 3 days.
This should be changed: 
1. Auto reset after 3 days
or
2. Transactions should be process and the cpu & net will reset after 3 days even if used > max

```
    "cpu_limit": {
        "used": 15514,
        "available": 0,
        "max": 14276
    }
```

**Comment by jgiszczak** [comment]
CPU used is calculated using an exponential moving average with a window size of 24 hours (in milliseconds) divided by the block interval, which is 500 ms.  There is no process in the system that recalculates the usage on some scheduled interval.  Instead it is calculated the next time you submit a transaction.  Try submitting a new transaction and see what the values are.

**Comment by taokayan** [comment]
The usage values will be refreshed if you push a transaction on that account. It will not be automatically recalculated.

**Comment by jsprice87** [comment]
@taokayan, how are we supposed to "push a transaction" if the transactions fail due to "Insufficient CPU"?
