### ISSUE TITLE
pass by value of wallet_plugin/wallet_api.hpp

### ISSUE THREAD

**Issue by EugeneChung** [EOSIO/eos#5455]
Is there any specific reason to use pass by value for the parameters of all wallet_api methods?

https://github.com/EOSIO/eos/blob/master/plugins/wallet_plugin/include/eosio/wallet_plugin/wallet_api.hpp

**Comment by jgiszczak** [comment]
I'm not aware of any particular reason pass by value is used in that API.  It isn't used in other APIs.  Odds are it was because the arguments are generally trivial in size and all of the methods are performance-insensitive.

**Comment by EugeneChung** [comment]
If DApp uses keosd to sign its transaction, try_sign_digest could be performance-insensitive.
