### ISSUE TITLE
Is there a http api for set account permission?

### ISSUE THREAD

**Issue by zxf969175364** [EOSIO/eos#5458]
I need to distinguish permissions based on roles and find that eos itself contains permission controls. So if there is a http api of `close set account permission`, you don't need to control it inside the contract.

**Comment by xJonathanLEI** [comment]
Setting account permission is not done via a standalone API call, but rather a function action invoke.

The relevant action is the `updateauth` action from the `eosio` contract.

**Comment by taokayan** [comment]
Please use ```updateauth``` instead.
