### ISSUE TITLE
On output, use new key format for K1 keys

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#5467]
* Switch all tools, libraries, api endpoints, etc. to output the new key format (`PUB_K1_xxx`)
* Compatibility: all tools, libraries, api endpoints, etc. need to support the legacy format (`EOSxxx`)
* Tools, libraries, api endpoints, etc. will *not* support custom prefixes for the legacy format. Instead, users may use conversion tools.

**Comment by marlonwilliams** [comment]
Useless request. Good for technical reasons, but it's too late - the current method is simpler and those with existing EOSxxx keys won't bother going through the hassle of replacing their keys.

Most tools use eosjs and eosjs-ecc - both libraries have been updated to support dynamic prefixes: https://github.com/EOSIO/eosjs-ecc/pull/30 and https://github.com/EOSIO/eosjs/pull/314

Total waste of developer time.

**Comment by marlonwilliams** [comment]
For clarity - "useless" from a user perspective. Totally useful for technical reasons and future development.

**Comment by jgiszczak** [comment]
Users will get switched to the new format automatically.  The moment you import an old format key into a wallet, then request the list of keys, it will print the new format of the same key in response.  We'll have to provide a flag to retrieve the key(s) in the old format, but it will not be the default.

Both formats of the key are purely human readable packaging of the same binary key material anyway.  As more sophisticated wallets are constructed, including support for hardware wallets, people will spend less and less time reading their keys themselves, allowing the software to do what software is good at.  (How many people read the certificates their HTTPS connection uses?)

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
