### ISSUE TITLE
build error, no member named version_string

### ISSUE THREAD

**Issue by newbieh4cker** [EOSIO/eos#5471]
![image](https://user-images.githubusercontent.com/23703741/44770021-8dafe780-aba1-11e8-82f9-2646cc5c396b.png)

How can I fix that error?

**Comment by taokayan** [comment]
which branch did you use? would you try release/1.1 or release/1.2.x?

**Comment by spoonincode** [comment]
did you update submodules?

**Comment by jgiszczak** [comment]
`git submodule update --init --recursive` in the `eos` directory.

**Comment by gongyimingdao** [comment]
me too
