### ISSUE TITLE
eosiocpp runs good, but where is eosio.hpp file?

### ISSUE THREAD

**Issue by newbieh4cker** [EOSIO/eos#5472]
![image](https://user-images.githubusercontent.com/23703741/44771912-5c3a1a80-aba7-11e8-9642-fb488f269a2f.png)

eosiocpp compile executes perfect. but I can not find eosio.hpp file.

**Comment by taokayan** [comment]
did you run eosio_install.sh?

**Comment by taokayan** [comment]
should be in /usr/local/eosio/include/eosiolib/

**Comment by damianoazzolini** [comment]
`eosio.hpp` file is in `/eos/contracts/eosiolib`

**Comment by lazaridiscom** [comment]
fetch the latest version (1.2.3 i think), there were some relevant fixes.

**Comment by newbieh4cker** [comment]
@lazaridiscom  using latest commit.
@taokayan yes, eosio.hpp is in there(/usr/local/eosio/include/eosiolib), but 'locate eosio.hpp' command doesn't return that dir

**Comment by newbieh4cker** [comment]
@lazaridiscom  using latest version.
@damianoazzolini  yes, but as far as I know, that is not the directory eosiocpp looking for.
@taokayan  nah, it's not there

![image](https://user-images.githubusercontent.com/23703741/44822925-740daf00-ac38-11e8-9adf-413a4657a4c2.png)

**Comment by lazaridiscom** [comment]
So your problem is that eosiocpp finds eosio.hpp, but you are not able to locate it on a file-system?

You should better ask such stuff on: https://eosio.stackexchange.com/

**Comment by newbieh4cker** [comment]
@lazaridiscom  yes, that's the problem. I'll ask on stackexchange, thanks

**Comment by lazaridiscom** [comment]
follow-up: https://eosio.stackexchange.com/questions/2178/cant-find-eosio-hpp-on-file-system

(@newbieh4cker , you can close the issue now)
