### ISSUE TITLE
mongo_db_plugin :mongo fc exception, add action traces, line 773, 3015010 abi_serialization_deadline_exception: ABI serialization time has exceeded the deadline

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#5475]
Failed to serialize type
    {"object":{"receipt":{"receiver":"eosio","act_digest":"aba24f324251bf11dd574e8e33f30f3e19951b4391401f4b1ad6a65d3e711ee9","global_sequence":3147618,"recv_sequence":1727300,"auth_sequence":[["eosio",2985153]],"code_sequence":4,"abi_sequence":5},"act":{"account":"eosio","name":"onblock","authorization":[{"actor":"eosio","permission":"active"}],"data":"de88674500118d073baca66200000008075bff037618217882c42c20561a80ec8d8683c067b3e60828d8dae0dd7448155e32f250accb873c5a45ac37ffbbc56f2e6c1416b48810e9328fdd732f8012f817edfda597dfe7e22437b2cf565bf14ca4e9d69fa50741ef21be64f2e979010000000000"},"elapsed":318,"cpu_usage":0,"console":"","total_cpu_usage":0,"trx_id":"e8904c3dcb38bf8a2e126c822a56379d385214eb17f61337eebc4f06ab11d474"}}
    thread-1  abi_serializer.hpp:599 to_variant
2018-08-29T14:10:41.618 thread-1   mongo_db_plugin.cpp:463       handle_mongo_excepti ] mongo fc exception, add action traces, line 773, 3015010 abi_serialization_deadline_exception: ABI serialization time has exceeded the deadline
serialization time limit 5000000us exceeded
    {"t":5000000}
    thread-1  abi_serializer.hpp:192 add

**Comment by cppfuns** [comment]
I queried this question
https://github.com/EOSIO/eos/commit/ff4874e5220af6052d3f285f6d919bc90fcbcdba
Need to adjust XX to 1*1000*1000, 1 second?

**Comment by heifner** [comment]
Looks like you have it set to 5x1000x1000, 5 seconds which was not enough time to serialize the action trace. My guess would be that your machine was very busy at that point in time OR it is a slow machine. For nodeos running mongo_db_plugin I would recommend running with:
 `read-mode = read-only`
and if you trust your peer:
 `validation-mode = light`
as that will help the load a bit.

In `read-only` mode you will then just be processing transactions in blocks, so I would increase `abi-serializer-max-time-ms` to something huge like 999915000.

**Comment by cppfuns** [comment]
It should be because I am using offline packets to import data directly
https://eosnode.tools/blocks
My machine configuration should be OK, and it may be that MongoDB does three-part sharding, and the main CPU and RAM consumption is still in the mongo process.
I did not find the read-mode and validation-mode mentioned in the config and mongo-db-plugin plugin source.
