### ISSUE TITLE
Ethereum event logs equivalent for EOS

### ISSUE THREAD

**Issue by oshek14** [EOSIO/eos#5485]
One of the solutions for saving quite a lot data in Ethereum Smart contracts is to log data by emitting event, which saves our gas. Is EOS quite similar? Does it provide us with the very same opportunity like Ethereum logging to save our RAM? if yes.. how many µs of CPU bandwidth this simple log function (without any additional functionality) will take? Will it take any RAM?

**Comment by xJonathanLEI** [comment]
There's currently **NO** Ethereum LOG equivalent in EOS. The closest thing AFAIK would be demux:

https://github.com/EOSIO/demux-js

**Comment by andriantolie** [comment]
Answered by @xJonathanLEI. I'm closing this issue
