### ISSUE TITLE
Where can I find the source code of the eosio-contract(about setcode and setabi)?

### ISSUE THREAD

**Issue by lpx1988** [EOSIO/eos#5489]

**Comment by jgiszczak** [comment]
For any other contract besides the system contracts, it is up to the author(s) of the contract to make the code available.  You may use `cleos get code` to retrieve the WASM code being executed on the chain and convert it to WAST, which is human readable, if not easy to understand.

**Comment by lpx1988** [comment]
Thank  you. @xJonathanLEI @jgiszczak
