### ISSUE TITLE
Any way to get the signature of current transaction inside the smart contract?

### ISSUE THREAD

**Issue by shwuhk** [EOSIO/eos#5491]
I would like to get the transaction signature that the smart contract is executing, which looks like "SIG_K1_......". Thanks.

**Comment by tbfleming** [comment]
The `read_transaction` function can get the entire transaction in serialized form. You can deserialize it and pull out any information. You'll have to create equivalents to chain's transaction-related structures to do the deserialization.

**Comment by shwuhk** [comment]
That seems very complicated. Is there any other way? I just need the signature....

**Comment by tbfleming** [comment]
There’s not. It’s complicated because it’s a rare need.

**Comment by shwuhk** [comment]
Understood. Thanks for your help. I would try the other approach then.

**Comment by siliconswampio** [comment]
@ohJohanZ guess not
