### ISSUE TITLE
mongo password?

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5493]
mongo in eos have no password in default.
I add user and password in mongo,does any change to  config.ini?
if there no chane in config.ini,does eos can still write date to mongo?

**Comment by heifner** [comment]
Should work. I have not tested it.
https://docs.mongodb.com/manual/reference/connection-string/
Note the user/password can be specified as part of the uri.

**Comment by taokayan** [comment]
@csquan has this issue been solved?

**Comment by csquan** [comment]
I had solved,thanks a lot.
