### ISSUE TITLE
How to get contract B's code hash in contract A?

### ISSUE THREAD

**Issue by HashDApp** [EOSIO/eos#5494]
contract A will interface with contract B
when contract B changed source, and published a new contract
How to discover this event in contract A?
Is check contract B's code hash in each interface a solution?
or  Is there a better solution?
thanks

**Comment by taokayan** [comment]
There's no way to get the code hash inside the contract. However you can use cleos to get it offchain.

**Comment by HashDApp** [comment]
will it be supported in the future?
