### ISSUE TITLE
when  to modify the table value, id 0 is well. But others failed with below logs

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#5498]
missing authority of ............1
    {"account":"............1"}
    thread-0  apply_context.cpp:131 require_authorization
pending console output: Hello actiupdateThe expected activity found
    {"console":"Hello actiupdateThe expected activity found"}
    thread-0  apply_context.cpp:61 exec_one

**Comment by yankunsam** [comment]
After change to 0, it works. But what 0 means  in modify?

```
activitylists.modify(item, 0, [&](auto& new_activity)
```

**Comment by taokayan** [comment]
0 means the payer of RAM doesn't change.
