### ISSUE TITLE
Issues regarding history_plugin and wallet_plugin

### ISSUE THREAD

**Issue by yashvadhvani** [EOSIO/eos#5499]
how to get transaction information via RPC call as the history_plugin is deprecated?
how to unlock wallet via RPC call as the wallet_plugin is also deprecated?
I am working in an application where i want rpc calls for both please give a detailed information.

**Comment by taokayan** [comment]
you can use mongo db plugin.

**Comment by xJonathanLEI** [comment]
Use [keosd](https://developers.eos.io/eosio-nodeos/docs/keosd-overview) instead.

**Comment by yashvadhvani** [comment]
Is it safe to use rpc calls and communicate with keosd?

**Comment by xJonathanLEI** [comment]
That’s the whole point of separating keosd

**Comment by yashvadhvani** [comment]
Ok that's great
