### ISSUE TITLE
synchronized backwardness problem

### ISSUE THREAD

**Issue by quarksgluons** [EOSIO/eos#5500]
My synchronizing node data has behind the main network.Restarting and updating the P2P node is invalid.  
Now the synchronization has stopped adn the height is 13823825. My P2P nodes' source:

```
https://validate.eosnation.io/reports/endpoints.txt
http://eosnetworkmonitor.io/
```
what need I do with it and how to fix it?

**Comment by jgiszczak** [comment]
For mainnet, you may also try P2P nodes from:
```
https://eosnodes.privex.io/
```

**Comment by quarksgluons** [comment]
I tried, but it didn't work.

**Comment by jgiszczak** [comment]
You'll need to ask for help on Stack Exchange or Telegram.  This forum is for issues with the software itself.  Internet routing problems are out of scope.

**Comment by quarksgluons** [comment]
I'm think this is a software problem, not a simple routing problem.
Why does btc or stellar do not have this unstable synchronization problem In the same network environment?

**Comment by jgiszczak** [comment]
BTC at least has a very swarm-based synchronization system.  EOS.IO has not yet adopted such a system.  It may be that it will at some point in the future.  For now, achieving synchronization requires significant manual configuration.

**Comment by quarksgluons** [comment]
It is a problem that There is no  one or more nodes dedicated to synchronizing data and those P2P nodes are too unstable.

I've found that nodeos process don't usually have a high percentage of memory, except that when unlinkable blocks or other disconnected problems occur, the percentage of memory usage increases dramatically. Then there's a high probability that the system will kill it.
