### ISSUE TITLE
add an official Block Producer Voting Record

### ISSUE THREAD

**Issue by stubborn-me** [EOSIO/eos#5511]
### My Problem

I've finally decided to stake my tokens and I'm wondering which BPs to vote for. I know there have been some disagreements between BPs in the past on some important issues, but I can't see who supported which agenda.

For example which BPs supported the gradual increase of RAM, and who didn't? I've heard that some BPs were against it because they were themselves involved in RAM speculation and I definitely want to avoid voting for them.
Or who is for burning the Worker's Proposal Fund and who is against?

I want to choose BPs whose past work is closest to my principles, but the information is not readily available, and if I have to go dig through forums and telegram chats then I'll put off voting yet again, or even worse vote for the wrong BPs.

### Proposed Solution

Right there in the voting screen in my GUI wallet there should be a link called "Block Producer Voting Record" or something similar.

I need this link to provide me with a few pieces of information:

1. A list of all the BP proposals in the past.
2. For each BP proposal who was for, who was against, and who was neutral. For example who supported the gradual increase of RAM and who didn't.
3. For a selected BP a list of all the historic proposals while he was active and how he voted on each one.

On the protocol level here's what happens:

- Any active BP can submit a transaction with a new proposal, for example "Let's start increasing the RAM at a rate of 1KB per block".

- There's a deadline for the voting period and each BP can vote for, against, neutral, or not vote (which is also neutral but his non-engagement should be perceived negatively by the community)

- Each BP can also add a comment with his vote explaining himself why he voted a certain way. Later when I as a voter review the voting history of a BP I might still give him slack for voting against my principles if his comment is persuasive enough.

**Comment by taokayan** [comment]
It looks like you want to get transactions of BP accounts with certain criteria. I think you can go for some common public EOS explorer or syn with the mainnet.

**Comment by stubborn-me** [comment]
> It looks like you want to get transactions of BP accounts with certain criteria.

The transactions that the BPs will submit to vote on these issues will be a permanent and public record of the agendas they supported or opposed in the past. They'll be cryptographically signed and hence non-repudiable.

> I think you can go for some common public EOS explorer or syn with the mainnet.

And that is exactly the problem I've got. If I have to go dig through EOS explorers or forums or telegram chats then I and 99% of other voters won't bother to do it.

The information needs to be readily available right there at the voting screen of my GUI voting tool.

This is an enhancement of the user experience that is badly needed.

**Comment by stubborn-me** [comment]
> Your "GUI voting tool" can easily implement what you're requesting. You should probably open an issue there.

That misses the point.

Think about it this way: Right now there are various websites that show the voting record for any congressman or senator. But none of those websites participated in the establishing of a voting record protocol for the congress or the senate. They only present the information to me in a nice tabular format. Likewise the GUI wallets cannot impose a new decision making procedure onto the BPs.

What I'm suggesting is formalizing the decision making process of the BPs and imposing a new protocol for recording all of their interventions in the management of the network.

Later I as a voter need this record so I can evaluate the quality of each BP.

**Comment by jgiszczak** [comment]
While this may be a useful and valuable discussion to have, it is a question for the governance of the various chains.  The software provides the tools required to implement such a system.  It's up to the producers and users of the public chains to decide to use those tools.  I suggest posting your idea to the venues used by the users and producers of the chain you are interested in.

This forum is for the maintenance, development, and help with the software itself.  It is not used for governance of any particular EOS.IO-based chain.
