### ISSUE TITLE
cleos create account not working on local node

### ISSUE THREAD

**Issue by abhi3700** [EOSIO/eos#5514]
I am facing a problem related to creating account on local node.

**Steps followed:**
- `nodeos` running on a separate terminal.
- wallet is unlocked
- list keys using `cleos wallet keys`. It gives output as:
```
[
  "EOS5auLgLhM3uYWaDEeESKUMfqYsnNcUj2G9xSDuLbmEj4PGfBupL",
  "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
  "EOS6aD1hj7hcqktskyMtFKLti62MSaQV4vgb1GMES5cvLmj8s8Jip"
]
```
- create account for uploading a contract using 
   `cleos create account eosio dev111111111 EOS5auLgLhM3uYWaDEeESKUMfqYsnNcUj2G9xSDuLbmEj4PGfBupL EOS6aD1hj7hcqktskyMtFKLti62MSaQV4vgb1GMES5cvLmj8s8Jip`

**Issue**: It is returning nothing. I did wait for long.

Anyone with the solution, please?

Happy coding :)
@abhi3700

**Comment by taokayan** [comment]
have you imported the private key of eosio? also if you already uploaded the eosio.system contract, you need to use "cleos system newaccount" instead.

**Comment by NorseGaud** [comment]
Are you 100% sure it returns nothing? No errors, no pending notifications with a tracking id? And nothing on your node’s logs? Also, Can you add ‘-u http://localhost/addressofnodeos:port’ to the cleos command?

**Comment by abhi3700** [comment]
@NorseGaud 
- Yes! It returns nothing.
- [nodeos](https://github.com/abhi3700/My_Learning_EOS/blob/master/Images/nodeos_block_production_local_node.png) (also added --contracts-console) , [cleos get info](https://github.com/abhi3700/My_Learning_EOS/blob/master/Images/cleos_get_info.png) , [cleos get account eosio](https://github.com/abhi3700/My_Learning_EOS/blob/master/Images/cleos_get_account_eosio.png) are working perfectly.
- The problems I face is during [cleos create account ......](https://github.com/abhi3700/My_Learning_EOS/blob/master/Images/cleos_create_account.png) , [cleos set contract eosio .../eosio.bios](https://github.com/abhi3700/My_Learning_EOS/blob/master/Images/cleos_set_bios_contract.png).
- Also, tried using `cleos -u http://127.0.0.1:8888/ set contract eosio ....`. But still no response.

**Comment by jgiszczak** [comment]
Try your `create account` command with `--print-request --print-response`.  Let's see how far through the process `cleos` gets.

**Comment by abhi3700** [comment]
None of the above solutions are working.
So, instead I am using the API wrapper using eosjs (Javascript), eosfactory (Python) for showing the output.

Thanks!..

**Comment by ambrish-dev** [comment]
I am also getting the same problem . no output is showing when trying to create account by command line .
./cleos create account -j eosio tester EOS4toFS3YXEQCkuuw1aqDLrtHim86Gz9u3hBdcBw5KNPZcursVHq EOS7d9A3uLe6As66jzN8j44TXJUqJSK3bFjjEEqR4oTvNAB3iM9SA

**Comment by NorseGaud** [comment]
Interesting, I'm curious what your environment is like locally @ambrish-dev. Do you use bash, or something like zshrc? Have you tried this with a default shell environment, removing anything third party that might conflict?

**Comment by ambrish-dev** [comment]
> 
> 
> Interesting, I'm curious what your environment is like locally @ambrish-dev. Do you use bash, or something like zshrc? Have you tried this with a default shell environment, removing anything third party that might conflict?

I have installed EOS mainnet on amazon server and after installed it . I am executing this command on putty.
