### ISSUE TITLE
How to get an account's meta data in contract?

### ISSUE THREAD

**Issue by HashDApp** [EOSIO/eos#5515]
How to get an account's meta data in contract?
like created time, owner key, active keys, balance, etc.

**Comment by taokayan** [comment]
You can get the balance by reading the balance table. However I don't think you can get others.

**Comment by xJonathanLEI** [comment]
In addition, you can also get information about an account's resource stake from the `userres` table and delegated tokens from the `delband` table.

That's pretty much all you can read about an account from within a contract.

**Comment by HashDApp** [comment]
> In addition, you can also get information about an account's resource stake from the `userres` table and delegated tokens from the `delband` table.
> 
> That's pretty much all you can read about an account from within a contract.

Would you please provide some sample code to get userres and delband table?
Thank you

**Comment by taokayan** [comment]
I guess you can use the same way from the system contract to retrieve the information from the multi_index table. Please ask in eosio.stackexchange.com if you have further questions.
