### ISSUE TITLE
[BUG] uint64_t << 64 remains unchanged

### ISSUE THREAD

**Issue by xJonathanLEI** [EOSIO/eos#5516]
# Problem

In a contract, when you left shift an `uin64_t` by more than 64 bits, you get an effective shift of `bits_shift` % `64`.

For example:

    uint64_t max = 0xFFFFFFFFFFFFFFFFULLL;
    max = max << 64; // max is still 0xFFFFFFFFFFFFFFFFULL

# Expected Behavior

The value should become `0` when the bits shifted is greater than 64.

**Comment by taokayan** [comment]
This is not a bug, as this behaviour is undefined:
https://en.cppreference.com/w/cpp/language/operator_arithmetic#Bitwise_shift_operators
