### ISSUE TITLE
Non-producing node can not retrieve producers

### ISSUE THREAD

**Issue by jgiszczak** [EOSIO/eos#552]
In a P2P network, a node configured without any producers of its own is unable to retrieve information about producers.

**Comment by jgiszczak** [comment]
Non-producing node appears to be creating appropriate accounts on initial startup, in a debugger.

**Comment by jgiszczak** [comment]
Completed.

**Comment by jgiszczak** [comment]
Producer information is retrievable on a non-producing node.

**Comment by codemaster101** [comment]
@jgiszczak  how is one supposed to create a non producing node and connect it to a producing node. creation of a non producing node seems unclear to me

**Comment by jgiszczak** [comment]
@codemaster101 Simply omit any `producer-name=` and `private-key=`/`signature-provider=` configuration options from the node you want to not produce.  If it has no configured producer names, it will not attempt to produce.

If you still questions, please post in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
