### ISSUE TITLE
How to remove(delete / replace) a table's all data

### ISSUE THREAD

**Issue by HeDeHeng** [EOSIO/eos#5521]
Hi,

Does anyone know which command to execute in order to delete previously table data

**Comment by xJonathanLEI** [comment]
Check out https://github.com/EOSIO/eos/issues/5431#issuecomment-416089051

**Comment by taokayan** [comment]
You need to make an action to delete one or several rows each time until the whole table is deleted.

**Comment by yhc166188** [comment]
> You need to make an action to delete one or several rows each time until the whole table is deleted.

I wonder which command this should use?
