### ISSUE TITLE
How to create an account with less ram

### ISSUE THREAD

**Issue by yhc166188** [EOSIO/eos#5522]
I only create accounts, not buy ram and CPU, net

**Comment by xJonathanLEI** [comment]
The RAM is not for anything else but storing your account information. The minimum RAM needed for an account (as of `v1.2.3`) is:

    2996 bytes

It's possible to buy only 2996 bytes of RAM when creating the new account, but that would pretty much render your account useless.

As for CPU and NET, you can opt to not stake or delegate any EOS. However, that way your newly created account won't be able to make any transaction.

So please just follow the sane way of account creation.

**Comment by taokayan** [comment]
The actually RAM usage for an account is roughly 1KB just after creation. So it's indeed possible to reduce the RAM charge from 3KB to 1KB or even less. However, since the RAM is charged in the core during account creation, it might need a hardfork or something.
```
void apply_eosio_newaccount(apply_context& context) {
   ...
   int64_t ram_delta = config::overhead_per_account_ram_bytes;  // <- this is 2KB
   ram_delta += 2*config::billable_size_v<permission_object>;
   ram_delta += owner_permission.auth.get_billable_size();
   ram_delta += active_permission.auth.get_billable_size();

   context.trx_context.add_ram_usage(create.name, ram_delta);
```

**Comment by yhc166188** [comment]
What can I do to reduce the amount of ram I need to create an account? Later, buyram, CPU and net are raising the memory.

**Comment by taokayan** [comment]
I guess you can't do anything to reduce the RAM required unless you're one of the producer.

**Comment by yhc166188** [comment]
I just want to modify the eos source code? I sent you an E-mail. Could you give me some help?

**Comment by jgiszczak** [comment]
Modifying your own copy of the code does nothing to change the RAM requirements of the public nets, and in fact makes your node incompatible with them.

If you want to change the RAM requirements for your own private chain you may attempt to do so, but you may find that the data required to create a useful account has a minimum size which is not very different from the current size.  See the method quoted by @taokayan in `libraries/chain/eosio_contract.cpp` for details.
