### ISSUE TITLE
MultiNode with multiple producers (different accounts are used for producing) - one is paused

### ISSUE THREAD

**Issue by mamidi1211** [EOSIO/eos#5526]
Our Scenario 1: node1 paused, node2 is producing blocks. When a transaction is done on node1 it is not getting mined/validated and unable to get the data from table. 

Scenario 2: node1 paused, node2 is producing blocks. When a transaction is done on node2, sometimes the transaction is not mined/validated and unable to get the data from table.

How to solve this ? 
Am I missing something to configure ?

**Comment by jgiszczak** [comment]
Have you verified that the two nodes are properly synchronized with each other?  When both are producing, do they produce blocks with sequence numbers correctly following the other producer?  If Node1 produces block numbers 300-311, Node2 should then produce block numbers 312-323.

The node which is not producing a series should be logging something similar to:
```
1624700ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block b3e11edbd04099d2... #103000 @ 2018-06-01T10:40:23.500 signed by jgiszczak [trxs: 0, lib: 102664, conf: 0, latency: 1158401200 ms]
```

**Comment by mamidi1211** [comment]
Yes. Everything is good. They are producing with sequence numbers. 
one will be receiving while the other is producing.

**Comment by taokayan** [comment]
Please provide more logs, exceptions, ... etc. You transactions might be roll back or not included in the next block.

**Comment by mamidi1211** [comment]
when we check the transaction_id using API **v1/history/get_transactions**, in the result we are getting value for key "txn" as null. 

**Please find the example : 
I/P for API :**
{
	"id":"8c3e151828899c83116e1883c4a3e75f99b4a2c02e27dcc48ce64530560972c8",
	"json":true
}

**O/P :**
{
    "id": "8c3e4c83296dee0272dabb03b81e186c13d6a039fdfda20b4dd050c7d53d1d05",
    "trx": null,
    "block_time": "2018-08-29T14:08:43.500",
    "block_num": 25140,
    "last_irreversible_block": 102285,
    "traces": []
}

**Comment by jgiszczak** [comment]
Be sure the history plugin filter options are set in a way that will capture the transaction you are looking for.  The `--filter-on` option should include the account name and/or action name of the transaction, and the `--filter-out` option must not be excluding it.

**Comment by mamidi1211** [comment]
--filter-on=* was there. Also, we have observed this **"sometimes the transaction is not mined/validated"** not for every transaction.

**Comment by jgiszczak** [comment]
Transactions submitted via `cleos` default to an expiration time of 30 seconds.  Try increasing `--expiration` to something more than 30 seconds, or submit transactions more slowly so your node has time to process them all.

A network with a designated producer not actually producing is considered degraded.  Ordinarily such a producer should unregister, or should be voted out.

**Comment by taokayan** [comment]
closed as no reply. Please ask in eosio.stackexchange.com if you have further questions.
