### ISSUE TITLE
Different account actions results from two nodes of version 1.2.3

### ISSUE THREAD

**Issue by kristieguo** [EOSIO/eos#5527]
I queried account actions from two eos mainnet nodes with the same version 1.2.3, but the results turned out to be different. P.S: I queried at the same time, and there is no new account actions coming in. See screenshots below for reference.

<img width="738" alt="screen shot 2018-09-04 at 6 54 39 pm" src="https://user-images.githubusercontent.com/20232539/45027746-e0434500-b074-11e8-8ec0-fba6474653e2.png">
<img width="1067" alt="screen shot 2018-09-04 at 6 54 51 pm" src="https://user-images.githubusercontent.com/20232539/45027771-ecc79d80-b074-11e8-87ae-632ea2c03cf2.png">
<img width="723" alt="screen shot 2018-09-04 at 6 55 29 pm" src="https://user-images.githubusercontent.com/20232539/45027780-f4874200-b074-11e8-921b-12f43ee3ad1a.png">
<img width="1075" alt="screen shot 2018-09-04 at 6 55 19 pm" src="https://user-images.githubusercontent.com/20232539/45027789-fb15b980-b074-11e8-8a89-bfd67ab527fd.png">

**Comment by jgiszczak** [comment]
For very active accounts, you will need to use the `pos` and `offset` arguments for `get actions` to get consistent results.  Try:
`./cleos -u http://13.250.7.18:8888 get actions cybexeospool 100 20`
