### ISSUE TITLE
get_table_rows with secondary key

### ISSUE THREAD

**Issue by mamidi1211** [EOSIO/eos#5528]
using get_table_rows http api how can we filter/ query using secondary primary key ?

**Comment by maoueh** [comment]
```
curl -X POST https://kylin.eoscanada.com/v1/chain/get_table_rows -d '{"json":true,"code":"cancancan345","scope":"cancancan345","table":"vote", "index_position":2,"key_type":"i128","lower_bound":"0x0000000000000000D0F2A472A8EB6A57","upper_bound":"0xFFFFFFFFFFFFFFFFD0F2A472A8EB6A57"}'
```
If you omit the both `lower_bound` and `upper_bound`, results are sorted according to the secondary index key.

See https://github.com/eoscanada/eosio.forum/blob/master/include/forum.hpp#L110 for the secondary indexes definitions.

So, the answer is yes. This issue should closed IMO.

**Comment by maoueh** [comment]
Also note that if your secondary index type is name, you can use a name as the key instead of an hex string, something like: `"lower_bound":"abc","upper_bound":"def"`.

Also, for complex keys, you must an HEX string in little endian format.

**Comment by taokayan** [comment]
see #3695
