### ISSUE TITLE
how to remove producer from producerlist？

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5531]
I have build a private network which have 5 BP,when I stop a BP,for example:A,I can see other BP‘s log ,when  wait for A produce block,because A have been stoped,it wait 6 seconds,and in this 6 seconds,no blocks was produced,how to avoid this ?

**Comment by csquan** [comment]
in this 6 seconds,no block was produced,so any tx will accepted but not write in block,and account balance refer to above tx have no change,this is a risk.

**Comment by wuyahuang** [comment]
Unregister an existing producer
Usage: cleos system unregprod  account

Positionals:
  account TEXT                The account to unregister as a producer (required)

**Comment by csquan** [comment]
I have run undelegatebw ，voteproducer ，unregprod cmd ,and scaled of A has down to 0 in producedlist,but there still wait 6 seconds,and no block was produced in this 6 seconds.

**Comment by taokayan** [comment]
There's no way to reduce the number of producers. In your case there's no way to remove producers since the number of producers is less than 21. However you can vote another 16 new producers so that would be 5+16=21 producers then A will run out of the top 21 producer list.
