### ISSUE TITLE
Missing Documentation | JSON response for transfer & others

### ISSUE THREAD

**Issue by NorseGaud** [EOSIO/eos#5532]
## Problem

Unable to find documentation or comments on total_cpu_usage, cpu_usage_us, cpu_usage, net_usage, net_usage_words, etc.

I am looking at the JSON output from a `cleos transfer` execution. Some of them are empty too.

## Request

I would like to see a documentation page OR comments in the code indicating what each value is for and if it's bytes, bits, etc. 

I see some of them defined in https://github.com/EOSIO/eos/blob/4da680bdfe1f68a11edb332252e015f4f533c443/libraries/chain/include/eosio/chain/trace.hpp, but can't really understand that yet so I'm not sure.

## JSON

<pre>{
  "transaction_id": "fa1410330444add50a1baa64769ba65614d29246d78212726f484e76099626e9",
  "processed": {
    "id": "fa1410330444add50a1baa64769ba65614d29246d78212726f484e76099626e9",
    "receipt": {
      "status": "executed",
      "cpu_usage_us": 1035,
      "net_usage_words": 22
    },
    "elapsed": 1035,
    "net_usage": 176,
    "scheduled": false,
    "action_traces": [
      {
        "receipt": {
          "receiver": "eosio.token",
          "act_digest": "82f618679a3be195883fb6fb2f96fd18de4450d1000784c710201ac862d1fda9",
          "global_sequence": 31016491,
          "recv_sequence": 1611663,
          "auth_sequence": [
            [
              "XXXXXXsju1",
              30
            ]
          ],
          "code_sequence": 2,
          "abi_sequence": 2
        },
        "act": {
          "account": "eosio.token",
          "name": "transfer",
          "authorization": [
            {
              "actor": "XXXXXXsju1",
              "permission": "active"
            }
          ],
          "data": {
            "from": "XXXXsju1",
            "to": "XXXXXXsju2",
            "quantity": "1.0000 EOS",
            "memo": "XXXXXXXX 1536109951000: ACCOUNT_ONE -> ACCOUNT_TWO"
          },
          "hex_data": "10f4c3c8dd8ca99220f4c3c8dd8ca992102700000000000004454f5300000000334d454f53545249435320313533363130393935313030303a204143434f554e545f4f4e45202d3e204143434f554e545f54574f"
        },
        "elapsed": 707,
        "cpu_usage": 0,
        "console": "",
        "total_cpu_usage": 0,
        "trx_id": "fa1410330444add50a1baa64769ba65614d29246d78212726f484e76099626e9",
        "inline_traces": [
          {
            "receipt": {
              "receiver": "XXXXXXsju1",
              "act_digest": "82f618679a3be195883fb6fb2f96fd18de4450d1000784c710201ac862d1fda9",
              "global_sequence": 31016492,
              "recv_sequence": 12,
              "auth_sequence": [
                [
                  "meostricsju1",
                  31
                ]
              ],
              "code_sequence": 2,
              "abi_sequence": 2
            },
            "act": {
              "account": "eosio.token",
              "name": "transfer",
              "authorization": [
                {
                  "actor": "XXXXXXsju1",
                  "permission": "active"
                }
              ],
              "data": {
                "from": "XXXXsju1",
                "to": "XXXXXXsju2",
                "quantity": "1.0000 EOS",
                "memo": "XXXXXX 1536109951000: ACCOUNT_ONE -> ACCOUNT_TWO"
              },
              "hex_data": "10f4c3c8dd8ca99220f4c3c8dd8ca992102700000000000004454f5300000000334d454f53545249435320313533363130393935313030303a204143434f554e545f4f4e45202d3e204143434f554e545f54574f"
            },
            "elapsed": 6,
            "cpu_usage": 0,
            "console": "",
            "total_cpu_usage": 0,
            "trx_id": "fa1410330444add50a1baa64769ba65614d29246d78212726f484e76099626e9",
            "inline_traces": [

            ]
          },
          {
            "receipt": {
              "receiver": "XXXXXju2",
              "act_digest": "82f618679a3be195883fb6fb2f96fd18de4450d1000784c710201ac862d1fda9",
              "global_sequence": 31016493,
              "recv_sequence": 12,
              "auth_sequence": [
                [
                  "meostricsju1",
                  32
                ]
              ],
              "code_sequence": 2,
              "abi_sequence": 2
            },
            "act": {
              "account": "eosio.token",
              "name": "transfer",
              "authorization": [
                {
                  "actor": "XXXXXsju1",
                  "permission": "active"
                }
              ],
              "data": {
                "from": "XXXXXXsju1",
                "to": "XXXXXsju2",
                "quantity": "1.0000 EOS",
                "memo": "XXXXXXXXX 1536109951000: ACCOUNT_ONE -> ACCOUNT_TWO"
              },
              "hex_data": "10f4c3c8dd8ca99220f4c3c8dd8ca992102700000000000004454f5300000000334d454f53545249435320313533363130393935313030303a204143434f554e545f4f4e45202d3e204143434f554e545f54574f"
            },
            "elapsed": 10,
            "cpu_usage": 0,
            "console": "",
            "total_cpu_usage": 0,
            "trx_id": "fa1410330444add50a1baa64769ba65614d29246d78212726f484e76099626e9",
            "inline_traces": [

            ]
          }
        ]
      }
    ],
    "except": null
  }
}
</pre>

**Comment by taokayan** [comment]
From the code you can figure out cpu usage is measured in terms of us, while net usage is measured in terms of bytes.

**Comment by NorseGaud** [comment]
@taokayan What about the other values like total_cpu_usage being 0 ?
