### ISSUE TITLE
mongo_db_plugin :ABI serialization time has exceeded the deadline

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5536]
I have set  serialization time to something huge like 999915000 as heifner said to avoid "ABI serialization time has exceeded the deadline",and what does options "read-mode = read-only" mean?And,in fact,my eos node is sync data and write data into mongo very slowly,why?

**Comment by taokayan** [comment]
Are you using SSD or harddisk? Normally SSD is required. And what's your CPU & RAM config?

**Comment by heifner** [comment]
Also choosing not to store all collections and filtering out some transactions will help.

**Comment by taokayan** [comment]
closed as no reply. Please ask in eosio.stackexchange.com if you have further questions.
