### ISSUE TITLE
I cannot compile success on my Mac

### ISSUE THREAD

**Issue by yangguanglu** [EOSIO/eos#5540]
I cloned master to compile, but errors happened at last.

[ 74%] Generating eosio.token.abi.hpp
[ 74%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/rand.cpp.o
In file included from /Users/cary/Projects/eos/libraries/fc/src/crypto/elliptic_impl_priv.cpp:5:
/Users/cary/Projects/eos/libraries/fc/src/crypto/_elliptic_impl_priv.hpp:11:7: error: unknown type name 'secp256k1_context_t'; did you mean
      'secp256k1_context'?
const secp256k1_context_t* _get_context();
      ^~~~~~~~~~~~~~~~~~~
      secp256k1_context
/usr/local/include/secp256k1.h:43:41: note: 'secp256k1_context' declared here
typedef struct secp256k1_context_struct secp256k1_context;
                                        ^
/Users/cary/Projects/eos/libraries/fc/src/crypto/elliptic_impl_priv.cpp:75:19: error: no matching function for call to
      'secp256k1_ec_pubkey_create'
       FC_ASSERT( secp256k1_ec_pubkey_create( detail::_get_context(), (unsigned char*) pub.begin(), (int*) &pk_len, (unsigned char*) my->_...
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/cary/Projects/eos/libraries/fc/include/fc/exception/exception.hpp:339:22: note: expanded from macro 'FC_ASSERT'
      if( UNLIKELY(!(TEST)) ) \
                     ^~~~
/Users/cary/Projects/eos/libraries/fc/include/fc/exception/exception.hpp:323:52: note: expanded from macro 'UNLIKELY'
    #define UNLIKELY(x)  __builtin_expect((long)!!(x), 0L)
                                                   ^
/Users/cary/Projects/eos/libraries/fc/include/fc/exception/exception.hpp:332:30: note: expanded from macro 'FC_EXPAND_MACRO'
#define FC_EXPAND_MACRO( x ) x
                             ^
/usr/local/include/secp256k1.h:482:48: note: candidate function not viable: requires 3 arguments, but 5 were provided
SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ec_pubkey_create(
                                               ^
/Users/cary/Projects/eos/libraries/fc/src/crypto/elliptic_impl_priv.cpp:85:89: error: too few arguments to function call, expected 6, have 5
        return secp256k1_nonce_function_default( nonce32, msg32, key32, *extra, nullptr );
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                         ^
/Users/cary/Projects/eos/libraries/fc/src/crypto/elliptic_impl_priv.cpp:96:24: error: use of undeclared identifier 'secp256k1_ecdsa_sign_compact'
            FC_ASSERT( secp256k1_ecdsa_sign_compact( detail::_get_context(), (unsigned char*) digest.data(), (unsigned char*) result.begin...

**Comment by jgiszczak** [comment]
You must use the version of the secp256k1 library installed by the build script, specifically the one at `https://github.com/cryptonomex/secp256k1-zkp.git`.  Other versions of that library will not work.  That library must also successfully build _and_ install.  The EOS.IO build detects it in the installed location.

If you are really determined not to install that library in the normal location, you may pass `-DSecp256k1_ROOT_DIR` with the path to an alternate location on your CMake command line.  The variables `Secp256k1_INCLUDE_DIR` and `Secp256k1_LIBRARY` are also available for even finer-grained control.  If you have both the required version and an alternative version of the secp256k1 library installed, you may need to use those variables to specify the correct version.

**Comment by yangguanglu** [comment]
thanks
