### ISSUE TITLE
Dose bp reject the tx, if fullnode set disable-ram-billing-notify-checks = true, and broadcast it？ 

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#5551]
If bp node is updated to version 1.2.3, and they all  set `disable-ram-billing-notify-checks = false`, that means they will not package transactions which will pay for extra rams to another account.
But if we want to pay for extra rams for another account, and we set our fullnode `disable-ram-billing-notify-checks = true`, then broadcast a transaction by it. Dose the transaction will be packaged by bp, even if it will  cost  extra rams of account which triggered the contract?
@bytemaster

**Comment by jgiszczak** [comment]
If and when all block producers transition to `disable-ram-billing-notify-checks = false`, any transaction which triggers a contract to attempt to bill more RAM in a notification handler will fail and will never be incorporated into the blockchain, regardless of the setting on your local node.

Previous transactions already incorporated into an irreversible block will always be accepted.  New transactions would be denied.
