### ISSUE TITLE
I connect the Jungle testnet ,start the nodeos problems,cannot find my account

### ISSUE THREAD

**Issue by StupidStudentInSchool** [EOSIO/eos#5552]
**question 1**
2018-09-06T02:37:03.360 thread-0 net_plugin.cpp:2133 operator() ] Error reading message from dev.cryptolions.io:19876: Bad file descriptor
2018-09-06T02:37:04.078 thread-0 net_plugin.cpp:1366 request_next_chunk ] Unable to continue syncing at this time
2018-09-06T02:37:04.079 thread-0 net_plugin.cpp:2133 operator() ] Error reading message from dev.cryptolions.io:39876: Bad file descriptor

**question 2**
2018-09-06T02:44:36.975 thread-0   controller.cpp:1036           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001402870646eae521ff7a831543624a43a71000e99b875bb9d82c366336becc","previous":"00140286d7d09289da4ea725e9564439fb8fa4640b4eab8bdf6c160674721feb"}
    thread-0  fork_database.cpp:151 add
2018-09-06T02:44:36.975 thread-0   producer_plugin.cpp:309       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001402870646eae521ff7a831543624a43a71000e99b875bb9d82c366336becc","previous":"00140286d7d09289da4ea725e9564439fb8fa4640b4eab8bdf6c160674721feb"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1036 push_block

**my config.ini**
i change the p2p-server-addrass,producer-name,signature-provide; 

**question 3**
user@ubuntu:~/.local/share/eosio/nodeos/config$ cleos get account linlibinioes
2018-09-06T02:48:32.548 thread-0   main.cpp:3007                 main                 ] Failed with error: unspecified (0)
unknown key

**Comment by quarksgluons** [comment]
question1 and question 2
What is the content of your genesis.json file? It maybe that your genesis.json is different from Jungle testnet.

You kan set you testnet follow this link.
https://github.com/CryptoLions/EOS-Jungle-Testnet

The Jungle Testnet explore:
http://dev.cryptolions.io/#home

question3
I can't find your account that names linlibinioes on Jungle Testnet.

**Comment by StupidStudentInSchool** [comment]
sorry linlibinieos ，，

according to [https://github.com/CryptoLions/EOS-Jungle-Testnet](url) ，I download the genesis.json and config.ini 。

I just change signature-provider、producer-name、p2p-server-address and p2p-peer-address

p2p-peer-address is coming from [https://github.com/CryptoLions/EOS-Jungle-Testnet](url) P2P

I know question3 ，block is not all  download yet

**Comment by jgiszczak** [comment]
Jungle Testnet suffered an odd corner case in one of their blocks.  The only way to synch with it is to start from release/1.1.0, synch to head node, then upgrade.  Unless and until they discard their old, broken blockchain, this problem will persist.
From their Telegram channel pinned message:

> ❗️🛠 If you are Not synced, you need to downgrade to v1.1.0 sync node and upgrade:
> 1. stop node.
> 2. downgrade to v1.1.0
> 3. remove blocks/reverrsible folder. 
> 4. disable bnet /mongo plugin
> 5. update peers in config
> 6.  ./start.sh --replay
> 7. Upgrade to v1.2.4

As for question one, `dev.cryptolions.io:19876` frequently exceeds it connection limit count.  Remove peers that generate errors until you find some with available connection slots.

**Comment by StupidStudentInSchool** [comment]
nodeos -v , my nodeos version is v1.2.2 .

I do not how to downgrade to v1.1.0 and Upgrade to 1.2.4.

as your 3 step say，remove blocks and download complete nodeos data according [https://s3-ap-northeast-1.amazonaws.com/data.eos/index.html](url) . then replay old blocks. Is that right?

**Comment by StupidStudentInSchool** [comment]
@jgiszczak

**Comment by jgiszczak** [comment]
You downgrade using `git checkout release/1.1` and recompiling.

Downloading a block log is certainly an option.  However, that's a mainnet block log, not Jungle testnet.  The Jungle testnet block log is only a little over 3 GB.  If mainnet is what you want, by all means download that block log.  You'll need different peers from the one you specified though.  If you actually want Jungle testnet, you'll be downloading some other block log.

**Comment by StupidStudentInSchool** [comment]
@jgiszczak thank you ~

**Comment by panjiang** [comment]
What an annoying problem. EOS is fucking me.
