### ISSUE TITLE
why my transactions can't be included in a block?

### ISSUE THREAD

**Issue by bixf** [EOSIO/eos#5553]
i build a single node testnet. my producer is generating blocks normally, but my transactions  can't be included in a block. everytime  i check the transaction with "cleos get transaction txid"
i get the same result:
{
  "id": "b1fb6f62e627f1686f1a9daa49d44d6c3563d2239285ebe1b1917569f4df66b2",
  "trx": null,
  "block_time": "2000-01-01T00:00:00.000",
  "block_num": 0,
  "last_irreversible_block": 5604,
  "traces": []
}
how can i solve this?

**Comment by taokayan** [comment]
any logs from nodeos?

**Comment by bixf** [comment]
i found when i send that transaction,the next block contains 1 tx, but that block was confirmed by zero. after that i get that block ,it has empty tx list. is zero confirmed it is the reason? is that means i need 21 producers to solve this?

**Comment by evsward** [comment]
Have you loaded history_api_plugin?
