### ISSUE TITLE
Unexpected behavior when cancel a delay transaction using active/owner permission

### ISSUE THREAD

**Issue by jiangweifeng** [EOSIO/eos#5555]
Expected Behavior: 
the active/owner should be able to cancel the delayed transaction. 

Repro steps:

0. Originally, the account has two different keys for active and owner, one for each. 

1. permission settings as follows: 

account: aaa123aaa123

active '{
    "threshold": 2, 
    "keys": [
        {"key": "EOSXXXXXXXXXXXXXXXXXXXXXXXXXX", "weight": 1},
        {"key":"PUB_R1_XXXXXXXXXXXXXXXXXXXXXXXX", "weight":1}], 
    "accounts": [], 
    "waits": [{"wait_sec": 120, "weight": 1}] }'

owner just one key: EOSYYYYYYYYYYYYYYYYYYYYYY

`
./cleos -u https://eos.greymass.com set account permission aaa123aaa123 active '{
    "threshold": 2, 
    "keys": [
        {"key": "EOSXXXXXXXXXXXXXXXXXXXXXXXXXX", "weight": 1},
        {"key":"PUB_R1_XXXXXXXXXXXXXXXXXXXXXXXX", "weight":1}], 
    "accounts": [], 
    "waits": [{"wait_sec": 120, "weight": 1}] }' -p aaa123aaa123@owner
`

2. remove one active key from the wallet

`
./cleos wallet remove_key PUB_R1_XXXXXXXXXXXXXXXXXXXXXXXX
`

3. send a transaction
file send1eos.json:
{
    "delay_sec": 600,
    "actions": [{
        "account": "eosio.token",
        "name": "transfer",
        "authorization": [{
            "actor": "aaa123aaa123",
            "permission": "active"
        }],
        "data": {
            "from": "aaa123aaa123",
            "to": "bbb123bbb123",
            "quantity": "1.0000 EOS",
            "memo": ""
        }
    }]
}
`
./cleos -u https://eos.greymass.com push transaction ./send1eos.json 
`

4. try to cancel above transaction using different auth. 

- using owner permission to cancel the transaction, 
`
./cleos -u https://eos.greymass.com system canceldelay aaa123aaa123 owner 12345txtxtxtxtxttxxtnoxxxxxxxxxxxxxxxxxxxxx
`
Error 3050000: Action validate exception
Error Details:
canceling_auth in canceldelay action was not found as authorization in the original delayed transaction

- using active permission to cancel the transaction (one key)
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"aaa123aaa123","permission":"active"}', but does not have signatures for it.

`
./cleos -u https://eos.greymass.com system canceldelay aaa123aaa123 active 12345txtxtxtxtxttxxtnoxxxxxxxxxxxxxxxxxxxxx
`

- Add the other active key back to wallet and using active permission to cancel the transaction (two active keys included in the wallet)
Error 3090002: Irrelevant signature included
Please remove the unnecessary signature from your transaction!
Error Details:
transaction bears irrelevant signatures from these keys: ["PUB_R1_XXXXXXXXXXXXXXXXXXXXXXXX"]

Workaround: 
Change the active permission to one key, and using active permission to cancel the delay transaction. (tried using owner permission, failed). 

Possible user solution:
Consider this issue when set permission. Include keys' weight >= permission threshold in order to be able to cancel the delayed transaction.

**Comment by jiangweifeng** [comment]
There is another way to work around this. Set keys with higher weight in active permission, and use active permission to cancel the transaction.

**Comment by taokayan** [comment]
Has this issue solved? Please ask in eosio.stackexchange.com if you have further questions.
