### ISSUE TITLE
Do commit transactions have to be packaged?

### ISSUE THREAD

**Issue by wanglei-sky** [EOSIO/eos#5556]
I tried #5341 but in the fourth step
I can't use RPC API calls
Use push_transaction directly to report the error below

2018-09-06T10:42:35.220 thread-0   http_plugin.cpp:473           handle_exception     ] Exception Details: 3010010 packed_transaction_type_exception: Invalid packed transaction
Invalid packed transaction
    {}
    thread-0  chain_plugin.cpp:1398 push_transaction
Invalid cast from object_type to string
    {"type":"object_type"}
    thread-0  variant.cpp:476 as_string
Failed to deserialize variant
    {"variant":{"packed_trx":"","packed_context_free_data":"","compression":"none","signatures":[{"ref_block_prefix":2135967292,"max_cpu_usage_ms":0,"context_free_actions":[],"expiration":"2018-07-25T16:43:47","max_net_usage_words":0,"delay_sec":0,"ref_block_num":60993,"actions":[{"authorization":[{"actor":"icoinbaytest","permission":"active"}],"data":"90b1cade9ce9287290b1cade9ce92872102700000000000004454f5300000000087472616e73666572","name":"transfer","account":"eosio.token"}],"signatures":["SIG_K1_KXkhPuxYdWzn21MwwfhSRPKPmp2T4PbksMsPZjwHQ8ZSJcSyHDhFNRC1HEptzRS6zD29a7iJQ5nsmz524X3qcWhJVhgeCH"],"transaction_extensions":[],"context_free_data":[]}]}}
    thread-0  abi_serializer.hpp:604 from_variant

PS :I feel like EOS is the hardest thing I've ever connected to,Providing apis is too difficult

**Comment by jgiszczak** [comment]
Yes, transactions are only accepted in packed format.  There is now support in `cleos` to pack a JSON format transaction for you, returning the packed form.  There are third party libraries that can do it.  And one of the APIs can do it.  See `cleos convert` for help.
