### ISSUE TITLE
nodeos high CPU usage

### ISSUE THREAD

**Issue by chengevo** [EOSIO/eos#5565]
The nodeos node(non-producing node) constantly consumes 100% CPU, transactions send to that node are very likely to fail.

The system calls looks as follow:

![image](https://user-images.githubusercontent.com/1447307/45202571-fc7cf700-b2ab-11e8-958b-7de93e2e288d.png)

After restart nodeos, CPU usage drops to 10% to 20%,

![image](https://user-images.githubusercontent.com/1447307/45202682-58e01680-b2ac-11e8-865f-6905a289a3d1.png)

**Comment by taokayan** [comment]
what's your CPU model and what's your machine config?

**Comment by chengevo** [comment]
The machine I used:
- CPU: 3.2 GH Intel Xeon E5-2667 v4（Broadwell)
- memory: 32 G

By saying "machine config", are you referring to how I configed the nodeos?

**Comment by shwuhk** [comment]
Actually, we got the same situation. We host the nodeos on Google cloud platform and the process CPU usage is always 100%. Is there anything we can tweak to help?

**Comment by chengevo** [comment]
I ruled out following possible reasons:

- nodeos version
- peer connections
- HTTP request traffic
- chain state size

and finally it seems the problem was caused by malfunctioned hardware: after migrating to a new machine, CPU usage steadily maintains at 5% to 10%.
