### ISSUE TITLE
Error 3160009: No wast file found

### ISSUE THREAD

**Issue by StupidStudentInSchool** [EOSIO/eos#5566]
`user@ubuntu:~/eos/build/contracts/eosio.token$ ls
CMakeFiles           eosio.token.abi      eosio.token.cpp.bc  eosio.token.wast
cmake_install.cmake  eosio.token.abi.hpp  eosio.token.s       eosio.token.wast.hpp
CTestTestfile.cmake  eosio.token.bc       eosio.token.wasm    Makefile
user@ubuntu:~/eos/build/contracts/eosio.token$ cleos -u http://jungle.cryptolions.io:18888 set contract linlibinieos eosio.token
Reading WASM from eosio.token/eosio.token.wasm...
Error 3160009: No wast file found
Error Details:
no wasm file found eosio.token/eosio.token.wasm
user@ubuntu:~/eos/build/contracts/eosio.token$ `

why No wast file found?

**Comment by rohanagarwal94** [comment]
@StupidStudentInSchool did you manage to solve this?

**Comment by judeebene** [comment]
have you try manually @rohanagarwal94  using https://github.com/EOSIO/eosio.cdt
eosio-wasm2wast  test.wasm -o test.wast

**Comment by rohanagarwal94** [comment]
I tried to upload the contract through `cleos set contract hello.code ../hello -p hello.code@active` but it didn't find the wast file. Whereas the wasm file is there in the folder.

**Comment by StupidStudentInSchool** [comment]
@rohanagarwal94  Create a hello directory，Enter the directory，touch hello.cpp file , then eosiocpp this file. It will create wasm and wast .abi .Return to previous directory. upload

**Comment by miguelmota** [comment]
Alright figured it out. The problem is that `cleos` was actually an alias to a docker container. So of course the path is not found.

```bash
alias cleos='docker exec -it eosio /opt/eosio/bin/cleos'
```

It works if you deploy from within the container

```bash
docker exec -it eosio bash
```

```
root@dbfc4a4d2c0f:/# cd hello

root@dbfc4a4d2c0f:/# ls -1
hello.cpp

root@dbfc4a4d2c0f:/hello# eosiocpp -o hello.wasm hello.cpp

root@dbfc4a4d2c0f:/hello# eosiocpp -g hello.abi hello.cpp

root@dbfc4a4d2c0f:/hello# ls -1
hello.abi
hello.cpp
hello.wasm

root@dbfc4a4d2c0f:/hello# cd ..

root@dbfc4a4d2c0f:/# cleos -u http://api.kylin.alohaeos.com set contract helloworld54 hello/ -p helloworld54@active
Reading WASM from hello/hello.wasm...
Publishing contract...
executed transaction: 0179a18622035f2c26149cef5cce7b7d6a640338ab621b6753435363576307d4  1800 bytes  439 us
#         eosio <= eosio::setcode               {"account":"helloworld54","vmtype":0,"vmversion":0,"code":"0061736d01000000013b0c60027f7e006000017e6...
#         eosio <= eosio::setabi                {"account":"helloworld54","abi":"0e656f73696f3a3a6162692f312e30000102686900010475736572046e616d65010...
warn  2018-10-28T21:37:45.193 thread-0  main.cpp:482                  print_result      warning: transaction executed locally, but may not be confirmed by the network yet

root@dbfc4a4d2c0f:/hello# cleos -u http://api.kylin.alohaeos.com push action helloworld54 hi '["bob"]' -p helloworld54@active
executed transaction: c6645daf43f7253e190b6fcab1d5db77b3d5aadf749e5ee36cb7d8a7fe8de027  104 bytes  176 us
#  helloworld54 <= helloworld54::hi             {"user":"bob"}
warn  2018-10-28T21:59:18.515 thread-0  main.cpp:482                  print_result       warning: transaction executed locally, but may not be confirmed by the network yet
```

Success!

**Comment by shikhars371** [comment]
@miguelmota when i try to run eosiocpp -o hello.wasm hello.cpp this command in docker bash
its showing me error eosiocpp command not found, can you please help me out in this?

**Comment by StupidStudentInSchool** [comment]
@shikhars371 Add commands to environment variables

**Comment by shikhars371** [comment]
how to do that?

**Comment by serganus** [comment]
I moved the code to eosio.cdt, but still same error. Any suggestions?

**Comment by Enockkipkoech** [comment]
I encountered similar error : Error 3160009: No wasm file found Error Details: no wasm file found

**Solution:**
When starting docker container image using the command below, make sure you have full-colon(:) before project folder i.e  **$(pwd):/your_project_directory**

This allows you to move around your project folders and access files.

 `docker run -it --name waxdev -v $(pwd):/project_directory waxteam/dev bash`
