### ISSUE TITLE
How to get transaction id inside smart contract?

### ISSUE THREAD

**Issue by god2g** [EOSIO/eos#5569]
it is possible to get transaction id inside smart contract? i know there is a api called read_transaction(char * buffer,size_t size), but it seems not contain transaction id inside.Anyone knows? Thanks

**Comment by jgiszczak** [comment]
No, and yes.  The raw transaction data does not contain the ID, but the ID is a calculated value.  Your contract can recalculate it.  See #4980.

**Comment by brianjohnson5972** [comment]
Created #6289 to address this
