### ISSUE TITLE
The full board condition in tic-tac-toe contract example seems wrong

### ISSUE THREAD

**Issue by MarekStocki** [EOSIO/eos#5570]
Isn't the term inverted? Shouldn't the line rather be:
is_board_full &= !is_empty_cell(board[i]);
(with the ! negation)
https://github.com/EOSIO/eos/blob/cc9decff9428b261900a5b89ddf3f51d2c39321a/contracts/tic_tac_toe/tic_tac_toe.cpp#L54

**Comment by conr2d** [comment]
Yes, you're right. It's surprising that this error is found now. It has been since 15th, June.

**Comment by taokayan** [comment]
Thanks for your fix.

**Comment by arhag** [comment]
Resolved by #5572.
