### ISSUE TITLE
Some questions about RAM.

### ISSUE THREAD

**Issue by littleboy0k** [EOSIO/eos#5575]
When the EOS mainnet launched, each genesis crowdsale participant was awarded 4 kb of RAM. Is my assumption correct?

If so, then who had all the other RAM? Which account had the RAM? Was it a system contract? Or, was it given to genesis account holders proportionally to their EOS holding?

When new RAM is added (EOS RAM increased from 64 GB to 70+ GB), where does the RAM go to?

**Comment by NorseGaud** [comment]
Might be a better question for https://eosio.stackexchange.com/

**Comment by taokayan** [comment]
All genesis accounts were created by system account eosio that has no limit on RAM. Each of them has 8KB RAM which is free of charge.
Initially all RAM are kept in the system until they are bought(reserved) by some accounts. New RAM are added to the system pool.
