### ISSUE TITLE
Irreversible block height stop growing

### ISSUE THREAD

**Issue by HeZero** [EOSIO/eos#5577]
I have a test network,  for some reason,  some BP stop running. when I restarted them, the irreversible block height stop growing but the block height still growing ,this means my network is in an unavailable state, how should I solve this problem?

**Comment by gameosdotme** [comment]
The jungle test net has some problem. All push does not take effect.

**Comment by taokayan** [comment]
irreversible block number grows only if there're more than 2/3 of producers who are actually producing. You need fix those problematic BPs if this happens.
