### ISSUE TITLE
execute "./bulid.sh ubuntu full" but error

### ISSUE THREAD

**Issue by sionnow0** [EOSIO/eos#558]
./build.sh ubuntu full

…………

-- Installing: /root/opt/wasm/lib/cmake/llvm/./HandleLLVMOptions.cmake
-- Installing: /root/opt/wasm/lib/cmake/llvm/./LLVMInstallSymlink.cmake
-- Installing: /root/opt/wasm/lib/cmake/llvm/./TableGen.cmake
-- Installing: /root/opt/wasm/lib/cmake/llvm/./CheckCompilerVersion.cmake
-- Installing: /root/opt/wasm/lib/cmake/llvm/./HandleLLVMStdlib.cmake
-- Installing: /root/opt/wasm/lib/cmake/llvm/./CheckLinkerFlag.cmake
-- Installing: /root/opt/wasm/lib/cmake/llvm/./CrossCompile.cmake
-- Installing: /root/opt/wasm/lib/cmake/llvm/./GetSVN.cmake
-- Installing: /root/opt/wasm/lib/cmake/llvm/./AddLLVM.cmake
-- Installing: /root/opt/wasm/lib/cmake/llvm/./AddOCaml.cmake
-- Installing: /root/opt/wasm/lib/cmake/llvm/./LLVMExternalProjectUtils.cmake
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
The CMAKE_CXX_COMPILER:

clang++-4.0
is not a full path and was not found in the PATH.

Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/eos_new/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/eos_new/eos/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found. Stop.

============================
Ubuntu 14.04.5 LTS
gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
clang -v
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-unknown-linux-gnu
cmake --version
cmake version 3.9.0

can you help me ?

**Comment by lilymoana** [comment]
you can install clang++-4.0

**Comment by PaulCalabrese** [comment]
The build script has been rewritten since this issue. Closing.
