### ISSUE TITLE
eosiocpp generate eosio.token abi, and the field 'tables' is empty

### ISSUE THREAD

**Issue by yyh1102** [EOSIO/eos#5584]
At `master` branch, i use `eosiocpp` to generate `eosio.token.abi` from the original `eosio.token.cpp`. And the field 'table' is empty, which was originally two tables at previous version. 

![image](https://user-images.githubusercontent.com/10328169/45261592-3deedd00-b439-11e8-92c7-a329a8ec7f69.png)

**Comment by firesWu** [comment]
Did you add comment `//@abi table` above struct.

**Comment by yyh1102** [comment]
@firesWu Yeah, that's the problem. So the `eosio.token.hpp` also lost the `//@abi table` comment. Thanks for your help!

**Comment by firesWu** [comment]
@yyh1102  if you use eosiocpp -g to generate abi, you should add comment. but you can manually add table in ABI.

**Comment by yyh1102** [comment]
@firesWu Thanks!

**Comment by taokayan** [comment]
actually eosio.token abi is written manually rather than generate by eosiocpp. eosiocpp is a tool but users can also write their own abi files manually.
