### ISSUE TITLE
Got Error 3050000 after pushing action

### ISSUE THREAD

**Issue by ioleksiuk** [EOSIO/eos#5585]
Got Error 3050000 after pushing action to addressbook contract

cleos push action adr add '{"account":"alice","first_name":"alice","last_name":"in wonderland","street":"white rabbit lane","city":"wonderland","state":"wonderland","zip":"98109"}' -p alice@active
[Smart contract code](https://github.com/sjkelleyjr/Learning-Blockchain-with-EOSIO/tree/master/smart_contracts/addressbook)
![image](https://user-images.githubusercontent.com/42911468/45266784-3515ff80-b469-11e8-8edf-4ef0a17063eb.png)

**Comment by taokayan** [comment]
Looks like it's a type mismatch. In your abi file the type of "zip" is uint32_t but you put a string from your command line.

```
      "fields": [{
          "name": "account",
          "type": "name"
        },{
          "name": "first_name",
          "type": "string"
        },{
          "name": "last_name",
          "type": "string"
        },{
          "name": "street",
          "type": "string"
        },{
          "name": "city",
          "type": "string"
        },{
          "name": "state",
          "type": "string"
        },{
          "name": "zip",
          "type": "uint32"
        }
      ]
```

**Comment by ioleksiuk** [comment]
The problem was in calling another contract which is not deployed yet.  
![image](https://user-images.githubusercontent.com/42911468/45289386-b3b87e80-b4f5-11e8-828e-70baa4536465.png)
Thank you all 😉
