### ISSUE TITLE
cleos get transaction <txhash A>, but the result is  the content of txhash B?

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#5589]
![image](https://user-images.githubusercontent.com/11972366/45285291-6d731780-b515-11e8-9c2b-8d3304aa38b9.png)
Our fullnode is connected to mainnet.  Why could this happen ?

**Comment by arhag** [comment]
Resolved by #5723.

**Comment by taokayan** [comment]
Thanks @arhag
