### ISSUE TITLE
eosc: --skip-sign shouldn't need a private key

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#559]
I was just looking for the transaction syntax.  I'll import the key as a work-around, however this does look like a bug:

```
./programs/eosc/eosc transfer --skip-sign inita initb 1 ''
An error occurred while submitting the transaction for this command!

The transaction requires permissions that could not be authorized by the wallet.
Missing authrizations:
  - inita@active

Please make sure the proper keys are imported into an unlocked wallet and try again!
```

**Comment by jcalfee** [comment]
Sorry if this was fixed.. My build is a little behind.

**Comment by jcalfee** [comment]
latest build.. same behaviour

**Comment by heifner** [comment]
Is `eosd` running with `--skip-transaction-signatures` ?

**Comment by jcalfee** [comment]
no

**Comment by jcalfee** [comment]
I know why.. it skipped the signature but tried to broadcast anyways.. Of course it is missing the authority.

**Comment by heifner** [comment]
When testing without signatures both `eosc` and `eosd` must indicate no signatures.

**Comment by jcalfee** [comment]
Why does eosd need to skip signatures though?  That is unfortunate, what about the case where the transaction json is needed for cold-storage signing.  In production most users will not have a eosd that will skip signatures.

**Comment by heifner** [comment]
In production NO users will have a eosd that skips signatures. Signatures are required for non-test eosd. eosc does not currently support creating json for cold-storage signing.
