### ISSUE TITLE
Is the EOS Name Bidding Operational? 

### ISSUE THREAD

**Issue by odarboe** [EOSIO/eos#5590]
I want to know whether there is something blocking the issuance of premium names currently in the bidding process? It has been two weeks since the last bid on the highest name and still the name has not been awarded to the winner.

Is there any plan to amend the process to speed up the bidding process? Awarding one name a day compared to the vast list of names will take a very long time.

**Comment by jgiszczak** [comment]
The eosio.system contract bug preventing issuance of premium names was fixed and released on July 24th as version 1.1.1, available [here](https://github.com/EOSIO/eosio.contracts/releases).  To my knowledge, mainnet still has not deployed the updated system contract, so premium names are still stalled.  Lobby the block producers to update the system contract.
