### ISSUE TITLE
how can I get actions of one account from mongodb like run v1/history/get_actions from history plugin

### ISSUE THREAD

**Issue by past2017** [EOSIO/eos#5591]
how can I get actions of one account from mongodb like run v1/history/get_actions from history plugin
I try serveral tables but cannot get according result i want
Please tell me what is the command I run on mongodb to  get actions history of definite account
thank you very much
```
> show tables
account_controls
accounts
action_traces
block_states
blocks
pub_keys
transaction_traces
transactions
```

**Comment by evsward** [comment]
You can try to use "mongodb-filter-on".  The value should match "receiver:action:actor".

**Comment by halsaphi** [comment]
Answered by @evsward, and no additional queries, please refer to eosio.stackexchange.com for questions relating to mongodb, or try mongodb forums.
