### ISSUE TITLE
TUTORIAL: BIOS Boot Sequence - ERROR: Either --buy-ram or --buy-ram-kbytes with non-zero value is required

### ISSUE THREAD

**Issue by ashishchandr70** [EOSIO/eos#5598]
Hi,

The following command, part of the BIOS Boot Sequence tutorial on Developers Portal (https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence) [Step 10a] fails with the error

**cleos system newaccount eosio --transfer accountnum55 EOS6zYkkuKpVT3eApAPNXocaaAnnepWMxtHon54ETjREtewuEGaF1 --stake-net "100000.0000 SYS" --stake-cpu "100000.0000 SYS"**

**ERROR: Either --buy-ram or --buy-ram-kbytes with non-zero value is required**

Does this cleos command need a --buy-ram argument as well?

I am running on a Windows 10 laptop, using Ubuntu (details below)

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

Account eosio details are:

achandra@DESKTOP-5VFKFIM:~/eos$ cleos get account eosio
privileged: true
permissions:
     owner     1:    1 EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
        active     1:    1 EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
memory:
     quota:       unlimited  used:     1.116 MiB

net bandwidth:
     used:               unlimited
     available:          unlimited
     limit:              unlimited

cpu bandwidth:
     used:               unlimited
     available:          unlimited
     limit:              unlimited

SYS balances:
     liquid:    1000000000.0000 SYS
     staked:            0.0000 SYS
     unstaking:         0.0000 SYS
     total:     1000000000.0000 SYS

**Comment by ashishchandr70** [comment]
Add a --buy-ram-kbytes 8192 to get around the error, along with the rest of the cleos command. I don't know if this is the intended command or the command in tutorial should work as is. 

Please provide clarification and/or update the tutorial text.

**Comment by jgiszczak** [comment]
The `system newaccount` command was indeed missing an argument which is no longer optional.  Documentation update in progress.
