### ISSUE TITLE
cleos push action how transfer parameters symbol_type?

### ISSUE THREAD

**Issue by wangyilin1987** [EOSIO/eos#5614]
have   a interface in abi file:
`void buy(symbol_typesymbol);`      

`cleos push action test buy '["4,EOS"]' `

that have error!and how put this parameter in put action?

**Comment by jgiszczak** [comment]
Try defining the type as `symbol_name` rather than `symbol_type`.

**Comment by wangyilin1987** [comment]
@jgiszczak and how put data in `cleos push action `? thank you

**Comment by wangyilin1987** [comment]
i use that solve this problem:
```
void buy(string symbol)
{
    uint64_t symboltmp = ::eosio::string_to_symbol(4,symbol.c_str());
}
```
