### ISSUE TITLE
Following docker quickstart error

### ISSUE THREAD

**Issue by golangdaddy** [EOSIO/eos#5615]
OSX HighSierra

I just downloaded and built the system, but then switched to the docker quickstart method (following all instructions until after aliasing cleos). Cleos command works, but when I try and do anything with is I get the following error.

Alexs-MacBook-Pro:build alexbreadman$ cleos wallet create
Error 3200004: fail to resolve host
Error Details:
Error resolving "[keosd_ip]:${url}" : Host not found (authoritative)

**Comment by zscole** [comment]
I created a functional and minimal Docker image that consists of a static binary, so there are no external dependencies and it works right out of the box. You can find it on [Docker Hub](
https://hub.docker.com/r/whiteblock/eosio/) or just run `docker pull whiteblock/eosio` to get started. If you decide to check it out, let me know what you think or if you have any issues! I just pushed it yesterday. Good luck! 😄

**Comment by golangdaddy** [comment]
Thanks will do!

**Comment by jgiszczak** [comment]
You need to modify your `cleos` alias.  The instructions were to find the IP address your Docker environment assigned for `keosd` and substitute it in the alias.  In the example, `[keosd_ip]` would be `172.18.0.3`.  You need to find what your IP is by executing the `docker network inspect eosdev` command in the instructions and inspecting the results.

The documentation will be updated for better clarity.

**Comment by golangdaddy** [comment]
Super
