### ISSUE TITLE
p2p transaction generator plugin

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#562]
In order to test the p2p infrastructure under the greatest load, I would like a plugin that generates transactions in a configurable way. My idea is that this plugin will behave more-or-less like the http plugin except that it will synthesize transaction data rather than accept it from an external source. 

I also expect a multinode testnet to support multiple nodes with this plugin. I assume that the plugin will read a config file, probably json. The launcher app can be enhanced to compose appropriate sets of config files. Configuration items include such details as a range of accounts to produce, contract[s] to load, execution frequency, etc. Finally the plugin should periodically report metrics as appropriate.

As I complete the remaining details of the p2p, I think this will give a more flexible and robust means of driving load tests.

**Comment by heifner** [comment]
Closing as this is now #762
