### ISSUE TITLE
exchange tokens by transfer does not work

### ISSUE THREAD

**Issue by wsdfz** [EOSIO/eos#5623]
In my old contract, when someone transfer token to contract, contract will transfer back another token to exchange within tokens. But now it can not work with error:

Error 3100006: Subjective exception thrown during block production
Error Details:
Cannot charge RAM to other accounts during notify.

Maybe it is related to new RAM rules: https://github.com/EOSIO/eos/pull/5451

But it will error too when the account already have both tokens. In this case, no new RAM is needed.

Question:
1, Is these any way to exchange tokens by transfer after this change?

2, If not, what is the common new way ?

And when I tested in my local machine, all transfers are working fine. Is there any settings to open it in config.ini ?

I tried to add: 
  disable-ram-billing-notify-checks = false

It still works.

**Comment by taokayan** [comment]
In the new versions it's not allow to charge the user RAM in the notification code by default, this is by design and will stop hacker from stealing user's RAM. Contract owners are advised to change their contract so that the RAM is billed by the contract owner in their notification code.

**Comment by wsdfz** [comment]
Ignore it. 
It is only because one of the modify operation in contract code.
