### ISSUE TITLE
Nodeos running but no json file in http://localhost:8888/v1/chain/get_info

### ISSUE THREAD

**Issue by arcynosure** [EOSIO/eos#5625]
I have build the files and ran install script and then when i start nodeos it starts producing blocks normally but when i go to http://localhost:8888/v1/chain/get_info there is no json file!

**Comment by taokayan** [comment]
did you start nodeos with ```--http-validate-host=false```?

**Comment by jgiszczak** [comment]
Was an error reported?

**Comment by arcynosure** [comment]
No
