### ISSUE TITLE
Smart Contract API: get sender of the current message

### ISSUE THREAD

**Issue by andriantolie** [EOSIO/eos#563]
When trying to write sample contract, I often stumble upon on the case where I need this capability, it will be great if we have one.

**Comment by nanonano7** [comment]
would including the senders name in the data field be a solution?

**Comment by andriantolie** [comment]
Yes, that's what I'm currently doing. But I find it to be tedious to add the sender name for every action that exists in the contract.

**Comment by learnforpractice** [comment]
You can specify the sender in ABI struct.
That’s the work who created the smart contract should do. :)
