### ISSUE TITLE
warning: transaction executed locally, but may not be confirmed by the network yet   

### ISSUE THREAD

**Issue by AlwaysFurther** [EOSIO/eos#5630]
Hello,

I am new to EOS and I have been having a problem whenever executing a transaction ( creating account, pushing smart contract...)

Thank you in advance for taking the time to answer my question.

I am running a  nodeos and a keosd docker

> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
3da536ed028f        eosio/eos           "/bin/bash -c 'keosd…"   About an hour ago   Up About an hour    0.0.0.0:9876->9876/tcp   keosd
9fe24a9d5cf6        eosio/eos           "/bin/bash -c 'nodeo…"   About an hour ago   Up About an hour    0.0.0.0:8888->8888/tcp   nodeos

I use the following cleos alias:

`alias cleos='docker exec -i keosd /opt/eosio/bin/cleos --url http://nodeos:8888 --wallet-url http://127.0.0.1:9876'`

Now when I for instance want to create a account I run:

`cleos create account eosio corry EOS5tMLLzov5C3tpPTZu18xx4S1vDmsHtXqhmwXotj7EcxP7AUYP7 EOS5tMLLzov5C3tpPTZu18xx4S1vDmsHtXqhmwXotj7EcxP7AUYP7`

and I get the following message:

`executed transaction: 83a40a4cc06fbfcc447b3c851b0cd8fb2849b414697b58383458ee96eae952eb  200 bytes  624 us
warning: transaction executed locally, but may not be confirmed by the network yet    ] `

Do you know why my transaction is not sent to nodeos ?

Thank you !

**Comment by jgiszczak** [comment]
The warning is normal and expected.

Your transaction was sent to nodeos.  The warning is a reminder that receipt of your transaction by nodeos does not guarantee that it will be executed and incorporated into a block.  If the node receiving it is very busy, or if you set a very short expiration time, it may expire before it has a chance to be processed.  There are various other factors that also may result in your transaction not being confirmed.

In your particular case, with a private test network, odds are very high that your transactions will be executed.  There's just no guarantee.

**Comment by AlwaysFurther** [comment]
Hi jgiszczak,

Thank you for the quick response.
