### ISSUE TITLE
Bad error message

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#5633]
"inline action recursion depth reached" in apply_context.cpp, it should be "max inline action depth per transaction reached"

**Comment by brianjohnson5972** [comment]
See confusion reported in #5632

**Comment by johnworthley** [comment]
What is this error mean? I cannot understand why I am receiving this error after a simple inline action transfer call `[[eosio::action]]
void exchange::transfer(name from, name to, asset quantity, string memo)
{

    eosio_assert(quantity.symbol == EOS_SYMBOL, "must pay with EOS token"); 
   
    uint64_t EOS_AMOUNT = 1.0000;

  
    name eosio_name = "cooperbaxter"_n;
    asset amount = asset(10000, EOS_SYMBOL);
    if (quantity.symbol == EOS_SYMBOL)
    {
    action (
            permission_level{get_self(), "active"_n},
            "eosio.token"_n,
            "transfer"_n,
            std::make_tuple (
                from = _self, to = eosio_name, quantity = amount, memo = "Test"
            )
        ).send();
    }
}`
