### ISSUE TITLE
nodeos_run_test-mongodb ..............***Failed

### ISSUE THREAD

**Issue by DTanniks** [EOSIO/eos#5637]
Hi,I met the same problem in #2013, but it did not solve my problem.When I 'make test' it failed nodeos_run_test - directing a...* * * Failed...I'm sure I got mongodb and mongo-cxx-driver installed,
![clipboard](https://user-images.githubusercontent.com/41659229/45464808-d7bdcf00-b744-11e8-9e17-fba34336f436.png)
![board](https://user-images.githubusercontent.com/41659229/45464839-fb811500-b744-11e8-8936-90c64bf72439.png)
This is my mongo test.out:
![clip](https://user-images.githubusercontent.com/41659229/45464868-21a6b500-b745-11e8-86cb-cc7f5c9e99c7.png)
The problem seems to be that my mongodb is not running, but I don't know what to do about it,Thank you very much!

**Comment by DTanniks** [comment]
Oh...is #2103.Sorry

**Comment by taokayan** [comment]
Did you install mongo db?

**Comment by jgiszczak** [comment]
The [documentation](https://developers.eos.io/eosio-nodeos/docs/build-validation) includes instructions for how to launch MongoDB for the tests.

**Comment by DTanniks** [comment]
> 该[文档](https://developers.eos.io/eosio-nodeos/docs/build-validation)包含有关如何为测试启动MongoDB的说明。
I think I did follow the steps, I couldn't activate my mongod, I wonder why?
![image](https://user-images.githubusercontent.com/41659229/45533985-1d08fc00-b82c-11e8-9ce1-819accd9bb03.png)
