### ISSUE TITLE
get_table_rows API returns empty for data type array

### ISSUE THREAD

**Issue by andriantolie** [EOSIO/eos#564]
I'm trying to write a smart contract, and I have the following struct
```
  struct Game {
    Game() {};
    Game(AccountName challenger, AccountName host):challenger(challenger), host(host), turn(host), winner(N(none)) {
      // Initialize board
      for(int i = 0; i < 9; i++) {
        board[i] = N(-);
      }
    };
    AccountName   challenger; // use challenger as the key
    AccountName   host;
    AccountName   turn; // host/ challenger
    AccountName   winner; // none/ draw/ host/ challenger
    uint64_t      board[9]; // use 1d array since 2d array is not yet supported
  };
```

And the following data in the .abi 
```
{
  "types": [{
      "newTypeName": "AccountName",
      "type": "Name"
    }
  ],
  "structs": [{
      "name": "game",
      "base": "",
      "fields": {
        "challenger": "AccountName",
        "host": "AccountName",
        "turn": "AccountName",
        "winner": "AccountName",
        "board": "UInt64[]"
      }
    }],
  "tables": [{
        "table": "game",
        "type": "game",
        "indextype": "i64",
        "keynames" : ["challenger"],
        "keytypes" : ["AccountName"]
      }
  ]
}
```

After constructing the Game object, I try to retrieve the data through `eosc get table`, however I got empty array instead of array of '-' as the following:
```
{
  "rows": [{
      "challenger": "inita",
      "host": "initb",
      "turn": "initb",
      "winner": "",
      "board": []
    }
  ],
  "more": false
}
```

Anybody, has ever face the same issue?

**Comment by nanonano7** [comment]
I think you need to specify the board length like this in your struct.
board_len = 9;

**Comment by learnforpractice** [comment]
There must be something wrong. Show me the code of how you store Game struct on db,  so maybe I can help.

**Comment by andriantolie** [comment]
@nanonano7 Oh yeah, the trick works! I need to specify the board_len before board inside the struct but not inside the abi. This needs to be documented somewhere... Thanks!
@learnforpractice The problem is already solved, thanks for the support :) I'm trying to make a tic-tac-toe game on top of eos blockchain https://github.com/andriantolie/tic_tac_toe. If you have some time to spend, comments are really welcomed :)

**Comment by learnforpractice** [comment]
Well, if if the size of board >= 128, the length bytes is 2, so it will still be a problem.

See code in libraries/fc/include/fc/io/raw.hpp

    template<typename Stream> inline void pack( Stream& s, const unsigned_int& v ) {
      uint64_t val = v.value;
      do {
        uint8_t b = uint8_t(val) & 0x7f;
        val >>= 7;
        b |= ((val > 0) << 7);
        s.write((char*)&b,1);//.put(b);
      }while( val );
    }

template<typename Stream> inline void unpack( Stream& s, signed_int& vi ) {
      uint32_t v = 0; char b = 0; int by = 0;
      do {
        s.get(b);
        v |= uint32_t(uint8_t(b) & 0x7f) << by;
        by += 7;
      } while( uint8_t(b) & 0x80 );
      vi.value = ((v>>1) ^ (v>>31)) + (v&0x01);
      vi.value = v&0x01 ? vi.value : -vi.value;
      vi.value = -vi.value;
    }

    // std::vector<char>
    template<typename Stream> inline void pack( Stream& s, const std::vector<char>& value ) {
      fc::raw::pack( s, unsigned_int((uint32_t)value.size()) );
      if( value.size() )
        s.write( &value.front(), (uint32_t)value.size() );
    }
    template<typename Stream> inline void unpack( Stream& s, std::vector<char>& value ) {
      unsigned_int size; fc::raw::unpack( s, size );
      FC_ASSERT( size.value < MAX_ARRAY_ALLOC_SIZE );
      value.resize(size.value);
      if( value.size() )
        s.read( value.data(), value.size() );
    }


So if length>=128, you have to unpack the length bytes manually.

I think the eos team should think about add this function to the eoslib.

**Comment by learnforpractice** [comment]
There is a error in the previous post, the length is unsigned, not signed,so the unpack method is as below:

    template<typename Stream> inline void unpack( Stream& s, unsigned_int& vi ) {
      uint64_t v = 0; char b = 0; uint8_t by = 0;
      do {
          s.get(b);
          v |= uint32_t(uint8_t(b) & 0x7f) << by;
          by += 7;
      } while( uint8_t(b) & 0x80 );
      vi.value = static_cast<uint32_t>(v);
    }

**Comment by andriantolie** [comment]
Yes, you are right, it will cause problem when length >=128. Let's open another issue to increase visibility
