### ISSUE TITLE
Returning WAST from get_code is no longer supported

### ISSUE THREAD

**Issue by hama** [EOSIO/eos#5640]
When i use get code 
`cleos -u http://api.eosnewyork.io get code xxxxxxxxxxxx`
it return error now, which method shoud i use now?
`Error 3100008: Feature is currently unsupported
Error Details:
Returning WAST from get_code is no longer supported`

**Comment by swapnibble** [comment]
The only method you can use is "Pull and rebuild" :)

**Comment by firesWu** [comment]
what is your version？

```
cleos -u http://api.eosnewyork.io get code  eosio
code hash: b721d706e5ea6dbdfd6fc601bbc3e52adca5c83138e3326290451ef888707b6d
```

**Comment by taokayan** [comment]
This feature is remove due to security reason.

**Comment by hama** [comment]
> This feature is remove due to security reason.

So how can i get  code? no way any more?

**Comment by tbfleming** [comment]
To clarify: get code still works, but now retrieves wasm instead of wast. To function correctly your cleos version must match the api node’s version because of the changes.

**Comment by hama** [comment]
> To clarify: get code still works, but now retrieves wasm instead of wast. To function correctly your cleos version must match the api node’s version because of the changes.

Got it, thank you!
