### ISSUE TITLE
FC Exception encountered while processing chain.abi_json_to_bin

### ISSUE THREAD

**Issue by VtpVlan-oo7** [EOSIO/eos#5641]
curl --request POST \
  --url http://127.0.0.1:8888/v1/chain/abi_json_to_bin \
  --data '{"code":"eosio.token","action":"transfer","args":"{\"from\":\"intereoseos1\",\"to\":\"intersteller\":1}"}'

//  after requesting  abi_json_to_bin we got this error 

 Exception Details: 3050000 action_validate_exception: Action validate exception
Unknown action transfer in contract eosio
    {"action":"transfer","contract":"eosio"}
    thread-0  chain_plugin.cpp:1634 abi_json_to_bin
code: eosio, action: transfer, args: 
    {"code":"eosio","action":"transfer","args":""}
    thread-0  chain_plugin.cpp:1645 abi_json_to_bin

**Comment by taokayan** [comment]
The correct syntax is
```
curl --request POST --url http://127.0.0.1:8888/v1/chain/abi_json_to_bin --data '{"code":"eosio.token","action":"transfer","args":{"from":"intereoseos1","to":"intersteller","memo":"hihi","quantity":"1.0000 EOS"}}'
```

**Comment by VtpVlan-oo7** [comment]
@taokayan  thanks we got it !!
