### ISSUE TITLE
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations Ensure that you have the related private keys inside your wallet and your wallet is unlocked

### ISSUE THREAD

**Issue by arcynosure** [EOSIO/eos#5642]
I have created the wallet generated the keys imported the pvt keys started nodeos and then when i try to execute the bios contract this happens:

ananthan@ananthan-VirtualBox:~/Downloads/eos$ cleos set contract eosio build/contracts/eosio.bios -p eosio@active
Reading WASM from build/contracts/eosio.bios/eosio.bios.wasm...
Publishing contract...
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.

Please help i have ensured that the wallet is unlocked my wallet name is pappan

**Comment by arcynosure** [comment]
u mean the keys generated by running cleos create key
i imported that pvt key

**Comment by AlwaysFurther** [comment]
no I mean to use the eosio account you need to import the private key from it. Just run the command i gave you and try again it should work !

**Comment by arcynosure** [comment]
it shows nonexistent wallet so should i specify the wallet like cleos wallet import --private-key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 -n pappan   ??

**Comment by arcynosure** [comment]
thank u it worked cud u specify where u got this pvt key !

**Comment by AlwaysFurther** [comment]
No problem glad to help !

you can find it here: [https://developers.eos.io/eosio-cpp/docs/introduction-to-smart-contracts](url)

**Comment by AlwaysFurther** [comment]
Copy paste the link. clicking it doesn't work^^

**Comment by taokayan** [comment]
have you import the private key of eosio?

**Comment by niutaifan** [comment]
![image](https://user-images.githubusercontent.com/22468286/45614298-a83bf900-ba9b-11e8-84ea-85fd5173fab7.png)
The same mistake
