### ISSUE TITLE
something wrong with my transaction

### ISSUE THREAD

**Issue by bixf** [EOSIO/eos#5646]
hi! i use the http rpc to send transaction to local node. in the documentation https://developers.eos.io/eosio-nodeos/v1.2.0/reference ,it seems i need to use sign_transaction to have the signed transaction first ,but this method is deprecated in v1.2.0. i got the signed transaction,and this transaction can be sent to node. but when i get this transaction from chain,its  actions part is like this:
```
"actions": [{
          "account":` "eoscrctest12",
          "name": "transfer",
          "authorization": [{
              "actor": "eoscrctest12",
              "permission": "active"
            }
          ],
           "data": "2042c62aa38b30550000000084ab32dd102700000000000004535953000000000f746869732069732061207465737421"
        }
      ]
```
and the receive account's balance did not changed.  how can i solve this?

**Comment by firesWu** [comment]
you should use push_transaction after using sign_transaction.

**Comment by bixf** [comment]
> you should use push_transaction after using sign_transaction.

i have done that ,and the transaction has been contained in a block ,but when i get it from the chain, i get the abnormal output like above. normal tx like this:
```
"actions": [
        {
          "account": "eosio.token",
          "name": "transfer",
          "authorization": [
            {
              "actor": "marekvrba111",
              "permission": "active"
            }
          ],
          "data": {
            "from": "marekvrba111",
            "to": "eosbetdice11",
            "quantity": "40.0000 EOS",
            "memo": "90-marekvrba555-"
          },
          "hex_data": "104230e76ea8ae911082422e65753055801a06000000000004454f53000000001039302d6d6172656b767262613535352d"
        }
      ]
```

**Comment by firesWu** [comment]
It seem nodeos can't get your abi, so it have not unpack data.

**Comment by bixf** [comment]
@firesWu  how can i fix this,do i need to add some config or what?  i am new to this,can u explain it a little more?

**Comment by taokayan** [comment]
looks like the corresponding abi of eoscrctest12 is missing.

**Comment by andriantolie** [comment]
We haven't received any follow up from this. 
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
