### ISSUE TITLE
print("\n") seems some wrong.when comes one print("\n"),the latter doesn't work.

### ISSUE THREAD

**Issue by cophey** [EOSIO/eos#5647]
```
void testbr(){
        print("test1\n");
        print("test2\n");
}
```
When call the contranct action,it only print test1.

**Comment by taokayan** [comment]
can you provide the output?

**Comment by damianoazzolini** [comment]
I've reproduced the same situation. I've an action called `test` structured in this way:

```	
void test(account_name user) {
		print("print1\n");
		print("print2\n");
		print( "Hello, ", name{user} );
	}
```
I've created an account `test` and called the action `cleos push action test test '["a"]' -p test`. In the console with `cleos` i see 
```
executed transaction: a5851c60516db247a9e73c64348db847875f05cbcca8ceb765443fc5f008ca2a  104 bytes  4284 us
#          test <= test::test                   {"user":"a"}
>> print1
warning: transaction executed locally, but may not be confirmed by the network yet    ]
```
so only the first print is printed. BTW, if a look at the console with `nodeos` running, i see all the data printed (i've the flag `--contracts-console` set in `nodeos`):
```
2018-09-14T08:35:10.960 thread-0   apply_context.cpp:28          print_debug          ]
[(test,test)->test]: CONSOLE OUTPUT BEGIN =====================
print1
print2
Hello, a
[(test,test)->test]: CONSOLE OUTPUT END   =====================
```

**Comment by heifner** [comment]
cleos only prints the first line. Add `--verbose` to your cleos for more output.

**Comment by damianoazzolini** [comment]
Even if i modify the command in `cleos --verbose  push action test test '["a"]' -p test` the output is still the same. I think because the verbose flag works only if there is an error, as written in the helper: `-v,--verbose                output verbose actions on error`

**Comment by heifner** [comment]
Yep, forgot that. Use `-json` to get full output.

**Comment by heifner** [comment]
Correct. cleos only prints the first line. We could add an option I suppose to print all lines. But at some point it is better to just output json and let the use format as desired.

**Comment by godmar** [comment]
An odd decision, especially given how many hours you steal from new developers who wonder whether their smart contract has the desired effect - or any effect at all.

I will note that [EOS's own documentation](https://developers.eos.io/eosio-cpp/v1.1.0/docs/debugging) recommends: _The main method used to debug smart contract is Caveman Debugging, where we utilize the printing functionality to inspect the value of a variable and check the flow of the contract. Printing in smart contract can be done through the Print API (C and C++). The C++ API is the wrapper for C API, so most often we will just use the C++ API._

**Comment by godmar** [comment]
For the benefit of any readers who may stumble on this issue, here's how I was able to work around this:

```
cleos push action -j ..... > output.json
jq -r '.processed.action_traces[].console' output.json 
```
using the [jq](https://stedolan.github.io/jq/) utility.
