### ISSUE TITLE
The type defined in the ABI is invalid

### ISSUE THREAD

**Issue by ddzyan** [EOSIO/eos#5648]
eosio:v1.2.3
os:centos 7 

![image](https://user-images.githubusercontent.com/9130123/45484412-951ce680-b786-11e8-8a8d-3eecdafabaea.png)

```bash
$./cleos.sh get block 16134281

Error 3015004: The type defined in the ABI is invalid
Error Details:
Failed to serialize type
```

**Comment by ddzyan** [comment]
Can only upgrade the version and resume synchronization?

**Comment by ddzyan** [comment]
Can only upgrade the version and start synchronizing the block again?

**Comment by NM1024** [comment]
maybe only upgrade

**Comment by firesWu** [comment]
#5548

**Comment by taokayan** [comment]
please refer to #5548 or #5523
