### ISSUE TITLE
docs: "eosc push message" json examples missing memo field

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#565]
The examples throw this error:
```bash
./eosc push message eos transfer '{"from":"inita","to":"initb","amount":50}'
1125153ms thread-0   main.cpp:1033                 operator()           ] Converting argument to binary...
1125163ms thread-0   main.cpp:1100                 main                 ] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error
: 10 assert_exception: Assert Exception
!"missing field in variant object": Missing 'memo' in variant object
```

**Comment by learnforpractice** [comment]
Change it to

./eosc push message eos transfer '{"from":"inita","to":"initb","amount":50,"memo":"hello"}' --scope inita,initb --permission inita@active

The doc is out of sync.

**Comment by learnforpractice** [comment]
Change it to./eosc push message eos transfer '{"from":"inita","to":"initb","amount":50,"memo":"hello"}' --scope inita,initb --permission inita@activeThe doc is out of sync.On 14 Oct 2017, at 3:23 AM, James Calfee <notifications@github.com> wrote:./eosc push message eos transfer '{"from":"inita","to":"initb","amount":50}'

**Comment by jcalfee** [comment]
Thanks ..I'll submit a pr soon..

**Comment by jcalfee** [comment]
I'm sorry, I got this twisted up.. My example is wrong eos needs a memo, but the example documentation uses the "currency" contract which does not have a memo.
