### ISSUE TITLE
Loosen the rules for binary extensions in abi_serializer

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#5657]
`abi_serializer`'s `variant_to_binary` has data integrity rules on binary extensions which are more strict than necessary. These should be loosened. The ideal rule is this: if an extended field is left out, no data may follow in the binary.

**Comment by arhag** [comment]
Actually `abi_serializer` as currently implemented correctly follows the new restrictions on binary extensions described in #5600.
