### ISSUE TITLE
Get eosio.msig contract table "approvals2" failed

### ISSUE THREAD

**Issue by young-mu** [EOSIO/eos#5659]
I used the **cleos** tool (built from the latest code `08819aae0fb22aaa0d91c95990370278bea5243f` of [eos](https://github.com/eosio/eos) master branch ) to get tables of eosio.msig contract (built from the latest code `6ca72e709faba179726a20571929a9eeaea47d08` of [eosio.contracts](https://github.com/eosio/eosio.contracts) master branch )

I can get the right result from table `proposal`, but failed for table `approvals2`.

1. get table `proposal`

```shell
> cleos get table eosio.msig test2 proposal
{
  "rows": [{
      "proposal_name": "test",
      "packed_transaction": "daa19c5b0000000000000000000001000000008090b1ca00000000a86c52d501000000008090b1ca00000000a8ed32321484610f00000000000b6d617468656d617469637300"
    }
  ],
  "more": false
}
```

2. get table `approvals`

```shell
> cleos get table eosio.msig test2 approvals2
2018-09-14T06:55:38.276 thread-0   main.cpp:3010                 main                 ] Failed with error: Out of Range (8)
```

The error logs from nodeos are below:

```shell
2018-09-14T06:55:38.004 thread-0   producer_plugin.cpp:1302      produce_block        ] Produced block 0001067b8c28f265... #67195 @ 2018-09-14T06:55:38.000 signed by eosio [trxs: 0, lib: 67194, confirmed: 0]
2018-09-14T06:55:38.276 thread-0   http_plugin.cpp:473           handle_exception     ] FC Exception encountered while processing chain.get_table_rows
2018-09-14T06:55:38.276 thread-0   http_plugin.cpp:474           handle_exception     ] Exception Details: 8 out_of_range_exception: Out of Range
read datastream of length 35 over by 0
    {"method":"read","len":35,"over":0}
    thread-0  datastream.cpp:6 throw_datastream_range_error
error unpacking uint64_t
    {"type":"uint64_t"}
    thread-0  raw.hpp:616 unpack
Error unpacking field value
    {"field":"value"}
    thread-0  raw.hpp:368 operator()
error unpacking eosio::chain::name
    {"type":"eosio::chain::name"}
    thread-0  raw.hpp:616 unpack
2018-09-14T06:55:38.504 thread-0   producer_plugin.cpp:1302      produce_block        ] Produced block 0001067cf2a61171... #67196 @ 2018-09-14T06:55:38.500 signed by eosio [trxs: 0, lib: 67195, confirmed: 0]
```

**Comment by firesWu** [comment]
Is table structure consistent with data?

**Comment by taokayan** [comment]
Can you provide your command of making the proposal?

**Comment by young-mu** [comment]
The command is 

```shell
cleos multisig propose test '[{"actor": "test2", "permission": "owner"}]' '[{"actor": "test1", "permission": "active"}]' test1 update '{"number": 1008004, "new_major": "mathematics"}' -p test2@active
```

- test1 is the owner of my customized contract
- test2 is the proposer

---

The permission of test1

```shell
➜  cleos get account test1
permissions:
     owner     1:    1 EOS7G6FMvusCAXyVBZyac1WuBMCuSDu5GcRv4kkPCspRcbyY6vAib
        active     1:    1 test2@owner,
memory:
     quota:       unlimited  used:       175 KiB

net bandwidth:
     used:               unlimited
     available:          unlimited
     limit:              unlimited

cpu bandwidth:
     used:               unlimited
     available:          unlimited
     limit:              unlimited
```

---

I propose, approve and exec the proposal successfully. But the only problem is that I cannot get the value of table `approvals2`, which is defined from [here](https://github.com/EOSIO/eosio.contracts/blob/master/eosio.msig/include/eosio.msig/eosio.msig.hpp#L52) and used from [here](https://github.com/EOSIO/eosio.contracts/blob/master/eosio.msig/src/eosio.msig.cpp#L60)

**Comment by young-mu** [comment]
> Is table structure consistent with data?

Honestly, I cannot quite get your words. Can you explain it more detailedly?

**Comment by arhag** [comment]
@young-mu: 

This is due to an inconsistency in the ABI for the eosio.msig contract. The `approvals_info` struct is missing the `version` field. 

Thank you for reporting this issue. I have opened a new issue in the eosio.contracts repo (EOSIO/eosio.contracts#75) for this bug and you can track its progress there if interested. I will be closing this issue since the bug affects eosio.contracts and not the code in eos repository.

This will be fixed in a future patch release of eosio.contracts, but if you want to get it work now all that needs to be done is to modify the `approvals_info` struct in the eosio.msig.abi file to read:
```
    {
      "name": "approvals_info",
      "base": "",
      "fields": [
        {"name": "version", "type": "uint8"},
        {"name": "proposal_name", "type": "name"},
        {"name": "requested_approvals", "type": "approval[]"},
        {"name": "provided_approvals",  "type": "approval[]"}
      ]
    }
```

**Comment by young-mu** [comment]
@arhag 

Thanks very much for your quick reply and fix. I have pulled the latest code of release/1.3.x branch, it works.

---

But in your fix, why you modify the ABI file directly?

In my mind, the ABI file is generated by scanning the contract source code. (like `eosiocpp -g xxx.abi xxx.cpp`)

**Comment by jgiszczak** [comment]
@young-mu Most of the block.one supported system contracts have hand-written ABI files.  The generator is not used.
