### ISSUE TITLE
Broadcast will be failed if multisigned tx has unused signature？？

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#5661]
In this case, if one transaction can be approved by threshold 3, which is controlled by three accounts named A/B/C.  A's threshold is 2, B is 1, C is 1.
If  one transaction is signed by A、B、C，one signature is unused. then broadcast will be failed.
errors is below:
![image](https://user-images.githubusercontent.com/11972366/45537481-eedce980-b836-11e8-9882-48752ad34414.png)
I check the code, find the problem is that parameter `allow_unused_keys` is set to false.
![image](https://user-images.githubusercontent.com/11972366/45537548-1d5ac480-b837-11e8-804f-ede8924e9f51.png)
https://github.com/EOSIO/eos/blob/75635168e743c3e65bb6345a1eaedd905581e6b0/libraries/chain/authorization_manager.cpp，row 324、row 415.
I think it's not reasonable to set this param to false. Can we fix it with configure, which we can configure it in the transaction parameter?

**Comment by taokayan** [comment]
what's your permission level in your transaction? or can you provide the command you used to push the transaction?

**Comment by andriantolie** [comment]
It's by design that you're not allowed to add unused authorization. You can't configure this parameter.
