### ISSUE TITLE
How to accelerate the mainnet synchronization？

### ISSUE THREAD

**Issue by helperShang** [EOSIO/eos#5662]
How to accelerate the mainnet synchronization？ Synchronization is too slow

**Comment by taokayan** [comment]
There're some ways to deal with it.
- use a faster and newer CPU (3+ GHz)
- use a faster network
- disable "void transaction_context::checktime()" if you're not a producing node.

**Comment by maoueh** [comment]
@taokayan Can you give more insights about `disable "void transaction_context::checktime()" if you're not a producing node.` tip?

Is this tied to a configuration option? Or should we edit the code of `nodeos` ourself?

**Comment by maoueh** [comment]
@jgiszczak Any idea about the `disable "void transaction_context::checktime()" if you're not a producing node` thing?

**Comment by jgiszczak** [comment]
I strongly discourage disabling `checktime()`.  @taokayan suggested he was going to remove that particular line of advice on Friday.  I'm not sure why he hasn't.

**Comment by taokayan** [comment]
sorry I just updated my comment. Please don't disable checktime().
