### ISSUE TITLE
get_block can produce invalid JSON

### ISSUE THREAD

**Issue by jamespic** [EOSIO/eos#5666]
If transactions contain unexpected data, such as binary data in their memo, then the `chain/get_block` API can return invalid JSON, that does not decode as UTF-8.

You can reproduce this issue with:
```
curl -X POST http://127.0.0.1:8888/v1/chain/get_block --data '{"block_num_or_id":"16184203"}'
```
The response contains the byte sequence e593 in the memo for transaction 562e3ad347fc79acefdc8e88ef22d0094a816fd96265fdf505b78c8f28af9a0f, that does not decode as UTF-8.

**Comment by taokayan** [comment]
This is about character encoding, and it is the issue of the transaction itself, not really the issue of the blockchain.
"memo" field, or any string field in EOS, is actually an instance of type "std::string", which means that it supports arbitrary formats as long as it can be fit into std::string.

I agree that any JSON string need to be in UTF-8 format, but there's no way to convert any binary stream of unknown format to the correct UTF-8 format. Here's some examples or counter-examples:

binary stream \x41\x42\x43 is English charaters "ABC"

binary stream \xE9\x99\x90, if the source format is "UTF-8", then it's character "限". In this case if we write "\xE9\x99\x90" into the terminal, the terminal should display "限" if it is aware of UFT-8 string.

binary stream \xE9\x99\x90, if the source format is "extended ascii", then it should be converted into \xC3\xA9\xC2\x99\xC2\x90, as any ascii character ranging from 128 to 255 has 2-byte width in UFT-8 representation.

binary stream \xB0\xA1, if the source format is "GBK" , then it is character "一", then it is \xE4\xB8\x80 in UTF-8, there's no easy formula to convert GBK to UTF-8 except to lookup from the table. \xB0\xA1 is invalid in UTF-8 format.

Maybe I am going to far here, but the fundamental thing is that, there's no way to convert from std::string to UTF-8 string without knowing the source encoding format.
