### ISSUE TITLE
mongo_db_plugin ->  how to filter special account blockchain data?

### ISSUE THREAD

**Issue by zhongjixiuxing** [EOSIO/eos#5669]
question : how to filter special account blockchain data? I'm try use mongodb-filter-on option, mongodb-filter-on option value is "anxinganxin1:transfer:", but this option don't work. 
anybody here, what are you do filter special account blockchain data?

**Comment by heifner** [comment]
What do you mean it doesn't work. It filters action_trace and transaction_trace data.

**Comment by zhongjixiuxing** [comment]
@heifner yes, you are right! I misunderstood... thank of you reply
