### ISSUE TITLE
ubuntu 16.10 build error.

### ISSUE THREAD

**Issue by lilymoana** [EOSIO/eos#567]
>>> ARCHITECTURE "ubuntu"
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /home/lily/opt/wasm/bin/clang-4.0
-- Check for working C compiler: /home/lily/opt/wasm/bin/clang-4.0 -- broken
CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/home/lily/opt/wasm/bin/clang-4.0" is not able to compile a
  simple test program.

  It fails with the following output:

   Change Dir: /home/lily/work/c++/eos/build/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_b6f56/fast"

  /usr/bin/make -f CMakeFiles/cmTC_b6f56.dir/build.make
  CMakeFiles/cmTC_b6f56.dir/build

  make[1]: Entering directory
  '/home/lily/work/c++/eos/build/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_b6f56.dir/testCCompiler.c.o

  /home/lily/opt/wasm/bin/clang-4.0 -o
  CMakeFiles/cmTC_b6f56.dir/testCCompiler.c.o -c
  /home/lily/work/c++/eos/build/CMakeFiles/CMakeTmp/testCCompiler.c

  error: unable to create target: 'No available targets are compatible with
  this triple.'

  1 error generated.

  CMakeFiles/cmTC_b6f56.dir/build.make:65: recipe for target
  'CMakeFiles/cmTC_b6f56.dir/testCCompiler.c.o' failed

  make[1]: *** [CMakeFiles/cmTC_b6f56.dir/testCCompiler.c.o] Error 1

  make[1]: Leaving directory
  '/home/lily/work/c++/eos/build/CMakeFiles/CMakeTmp'

  Makefile:126: recipe for target 'cmTC_b6f56/fast' failed

  make: *** [cmTC_b6f56/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "/home/lily/work/c++/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/lily/work/c++/eos/build/CMakeFiles/CMakeError.log".
make: *** 没有指明目标并且找不到 makefile。 停止。

**Comment by heifner** [comment]
Over a month old. Closing.
