### ISSUE TITLE
(install WASM Compiler) -bash: /usr/local/bin/cmake: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by Nost78** [EOSIO/eos#568]
Hi,
entering: cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/opt/wasm -DLLVM_TARGETS_TO_BUILD= \-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly -DCMAKE_BUILD_TYPE=Release ../
as per instructions found in  "h***s://steemit.com/eoskorea/@clayop/eos-build-guide-on-ubunbu" returns  "-bash: /usr/local/bin/cmake: cannot execute binary file: Exec format error"
I'm new to this, all help appreciated :)

**Comment by heifner** [comment]
Over a month old. Closing.
