### ISSUE TITLE
There are still references to `net_usage_words`

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos#5682]
References like this should instead me `max_net_usage_words` correct?

https://github.com/EOSIO/eos/blob/master/contracts/eosiolib/transaction.hpp#L34

**Comment by tbfleming** [comment]
Related to #4684, but a different header. All chain-related definitions in eosio-contracts and the cdt need to be checked. The contracts/ dir in the eos repo is deprecated, so may not get fixed.

**Comment by heifner** [comment]
Moved to eosio.contracts repo and fixed.
