### ISSUE TITLE
getTableRows return incorrect data while delay  the getTableRows call return correct data

### ISSUE THREAD

**Issue by micahli** [EOSIO/eos#5683]
I use eosjs and scatter to call transfer to a contract, the contract will update a Table after the transfer, then i will call getTableRows to get that data.
The code in client side is like below:
transferEOS() {
 this.getEos().transfer(this.eosAccount.name, DEST, betVal.toFixed(4) + ' EOS', "memo", auth).then((rst)=>{
            if (rst) {
                this.getEos().getTableRows({"json": true, "table_key": 'owner', "code": DEST, 
                                        "scope": DEST, "table": 'tableName',
                                        "lower_bound": encodedName.toString(), "upper_bound": encodedName.plus(1).toString()}).then(
                data => {
                console.log(data.rows[0]);
                ...
            })
        });
}

the problem is that the returned data.rows[0] is not consistent with what i get from cleos cmd "cleos -u https://api.cypherglass.com gettable myaccountname myaccountname tablename"
but when i add some delay in the promise of transfer like below, the result is correct then.

transferEOS() {
 this.getEos().transfer(this.eosAccount.name, DEST, betVal.toFixed(4) + ' EOS', "memo", auth).then((rst)=>{
            if (rst) {
                setTimeOut(function() {
                    this.getEos().getTableRows(...).then(
                    data => {
                    console.log(data.rows[0]);
                    ...
                }, 2000);                     
            })
        });
}
when i change the delay time to 1000 ms, sometimes the result is correct, sometimes is not.
Anyone can tell me what's wrong with my code. Thanks!

Below is part of the contract code:

struct st_table1 {
        name owner;
        uint32_t value1;
        uint32_t value2;
        uint32_t value3;
        uint32_t value4;
        uint32_t value5;
        string string_val1;
        string string_val2;
	uint64_t primary_key() const { return owner; }
        EOSLIB_SERIALIZE(st_pools, (owner)(value1)(value2)(value3)(value4)(string_val1)(string_val2))
}

// check if user exists or not. If user doesn’t exist, create one.
auto itr_user1 = table1.find(user);
if (itr_user1 == table1.end()) {
    itr_user1 = table1.emplace(_self, [&](auto &p){
        p.owner = name{user};
        p.value1 = 0;
        p.value2 = 0;
        p.value3 = 0;
        p.value4 = 0;
        p.value5 = 0;

    });
}

// Get user values
arr[0] = get_value(0);
arr[1] = get_value(1);
arr[2] = get_value(2);
arr[3] = get_value(3);
arr[4] = get_value(4);

// Get receipt record
string record;
uint32_t arr[5];
Record = get_receipt_record(user);

// update table for the user with the values and record above
table1.modify(itr_user1, _self, [&](auto &p){
    p.value1 = arr[0];
    p.value2 = arr[1];
    p.value3 = arr[2];
    p.value4 = arr[3];
    p.value5 = arr[4];
    p.string_val = record;
});

**Comment by taokayan** [comment]
This is more about irreversible time of a block. If you're transferring money, you should wait for the block become irreversible(around 300 blocks + transaction expire time) before issuing the query. Any irreversible block or states can be roll back if a soft fork happens.

**Comment by micahli** [comment]
Thank you very much!  @taokayan
