### ISSUE TITLE
node sync takes long on high-end machine

### ISSUE THREAD

**Issue by negedzuregal** [EOSIO/eos#5687]
Hi, we've been integrating EOS at [blox.io](https://blox.io) for our users. Been struggling getting the nodes up and running. Especially finding good peers.

We've been running our main node on an aws machine that has 128G ram, its been syncing for more than a week and it will probably take another week (maybe a bit less). 
Its kind of worrying that it should take that long on such a powerful machine. In a few months it will be very hard to catch up for new nodes.

Are we doing something wrong or is it just that heavy?

down is our config file. We do run the node with traces and mongo plugin for history fetching.

#chain_plugin
chain-state-db-size-mb = 65536
contracts-console = false
validation-mode = light

#http_plugin - off port listen
http-server-address =

#Logs
log-level-net-plugin = warn

#net_plugin
p2p-listen-endpoint = 0.0.0.0:9876
p2p-server-address = eos.bloxcenter.com:9876
allowed-connection = any
max-clients = 1024
p2p-max-nodes-per-host = 248
sync-fetch-span = 1024
max-implicit-request = 15000
abi-serializer-max-time-ms = 600000

#bnet_plugin
bnet-endpoint = 0.0.0.0:4321
bnet-threads = 24

#Plugins
plugin = eosio::chain_plugin
plugin = eosio::net_plugin
plugin = eosio::bnet_plugin
plugin = eosio::mongo_db_plugin

mongodb-store-blocks = true
mongodb-store-block-states = false
mongodb-store-transactions = true
mongodb-store-transaction-traces = false
mongodb-store-action-traces = false
mongodb-abi-cache-size = 2048
mongodb-wipe = false
mongodb-block-start = 0
mongodb-queue-size = 2048

# Include all Receivers and Actions
filter-on = 

#Other Pub BP nodes
p2p-peer-address = 106.10.42.238:9876
p2p-peer-address = 178.49.174.48:9876
p2p-peer-address = 185.253.188.1:19876
p2p-peer-address = 807534da.eosnodeone.io:19872
p2p-peer-address = api-full1.eoseoul.io:9876
p2p-peer-address = api-full2.eoseoul.io:9876
p2p-peer-address = api.eosuk.io:12000
p2p-peer-address = boot.eostitan.com:9876
p2p-peer-address = bp.antpool.com:443
p2p-peer-address = bp.cryptolions.io:9876
p2p-peer-address = bp.eosbeijing.one:8080
p2p-peer-address = bp.eosmedi.com:9877
p2p-peer-address = bp.libertyblock.io:9800
p2p-peer-address = br.eosrio.io:9876
p2p-peer-address = eos-seed-de.privex.io:9876
p2p-peer-address = eos.nodepacific.com:9876
p2p-peer-address = eos.staked.us:9870
p2p-peer-address = eosapi.blockmatrix.network:13546
p2p-peer-address = eosboot.chainrift.com:9876
p2p-peer-address = eosbp.buildteam.io:8532
p2p-peer-address = eosnode.fi:9888
p2p-peer-address = eu-west-nl.eosamsterdam.net:9876
p2p-peer-address = eu1.eosdac.io:49876
p2p-peer-address = fn001.eossv.org:443
p2p-peer-address = fullnode.eoslaomao.com:443
p2p-peer-address = m.eosvibes.io:9876
p2p-peer-address = mainnet-eos.wancloud.cloud:55576
p2p-peer-address = mainnet.eosarabia.org:3571
p2p-peer-address = mainnet.eoscalgary.io:5222
p2p-peer-address = mainnet.eosoasis.io:9876
p2p-peer-address = mainnet.eospay.host:19876
p2p-peer-address = mars.fnp2p.eosbixin.com:443
p2p-peer-address = node.eosflare.io:1883
p2p-peer-address = node.eosio.lt:9878
p2p-peer-address = node.eosmeso.io:9876
p2p-peer-address = node1.eoscannon.io:59876
p2p-peer-address = node1.eosnewyork.io:6987
p2p-peer-address = node2.eosnewyork.io:6987
p2p-peer-address = p.jeda.one:3322
p2p-peer-address = p2p.eos.bitspace.no:9876
p2p-peer-address = p2p.eosdetroit.io:3018
p2p-peer-address = p2p.eosio.cr:1976
p2p-peer-address = p2p.eosio.cr:5418
p2p-peer-address = p2p.genereos.io:9876
p2p-peer-address = p2p.mainnet.eosgermany.online:9876
p2p-peer-address = p2p.mainnet.eospace.io:88
p2p-peer-address = p2p.meet.one:9876
p2p-peer-address = p2p.one.eosdublin.io:9876
p2p-peer-address = p2p.two.eosdublin.io:9876
p2p-peer-address = p2p.unlimitedeos.com:15555
p2p-peer-address = peer.eosio.sg:9876
p2p-peer-address = peer.eosjrr.io:9876
p2p-peer-address = peer.eosn.io:9876
p2p-peer-address = peer.main.alohaeos.com:9876
p2p-peer-address = peer1.mainnet.eos.store:80
p2p-peer-address = peer1.mainnet.helloeos.com.cn:80
p2p-peer-address = peer2.eosthu.com:8080
p2p-peer-address = peering.mainnet.eoscanada.com:9876
p2p-peer-address = peering1.mainnet.eosasia.one:80
p2p-peer-address = peering2.mainnet.eosasia.one:80
p2p-peer-address = pub0.eosys.io:6637
p2p-peer-address = pub1.eostheworld.io:9876
p2p-peer-address = pub1.eosys.io:6637
p2p-peer-address = publicnode.cypherglass.com:9876
p2p-peer-address = seed1.greymass.com:9876
p2p-peer-address = seed2.greymass.com:9876

**Comment by taokayan** [comment]
Is your CPU 100% on one core? I think try to limit your p2p connection to 1-2 would help to improve your sync up speed. Normally it take couple of days to finish.

**Comment by negedzuregal** [comment]
@taokayan we've limited to 4 the number of peers to see the effect. it was 1024. 
No change as of now but will keep updating.

**Comment by sensay-nelson** [comment]
I was able to sync a node in a day by using https://eosnode.tools automation & tools, but that was without the mongo plugin.  It seems to be slowing down somewhere around 5-6MM blocks with the mongo_db_plugin installed.  Always afraid to stop and start it though, as that could instantly kill a days worth of syncing :(

**Comment by negedzuregal** [comment]
@sensay-nelson did u run with filter on? 

filter-on = *

**Comment by negedzuregal** [comment]
with filter off it does seem faster.. not 24H but around 3 days.
But than historical data is not available.

**Comment by nelsonenzo** [comment]
@negedzuregal Yes, it had filter-on = *, but this was around block 14MM and the data was much smaller + was not running mongo. The mongo plugin is taking minutes per 1000 block to update in the database and seems to basically be a blocking factor.

**Comment by taokayan** [comment]
I guess the 1000 iops of your SSD is a blocking factor. You can try it with a faster SSD (10k ops) for example. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
