### ISSUE TITLE
Where there are two documents in transaction_traces?

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#5692]
<img width="1280" alt="screen shot 2018-09-17 at 2 48 13 pm" src="https://user-images.githubusercontent.com/16130147/45609061-d5cb7700-ba88-11e8-8934-1bc71fd67652.png">

**Comment by TamirTian** [comment]
You can see #5667

**Comment by TamirTian** [comment]
A transaction includes one or more actions

**Comment by taokayan** [comment]
The first column is different in the last letter. What's the name of the first column?

**Comment by taokayan** [comment]
This might because of a soft fork that result in the same transaction executed more than one time. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
