### ISSUE TITLE
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations

### ISSUE THREAD

**Issue by niutaifan** [EOSIO/eos#5693]
![image](https://user-images.githubusercontent.com/22468286/45614654-cf46fa80-ba9c-11e8-87e6-a6058d4e8320.png)

**Comment by jgiszczak** [comment]
On which network are you attempting to execute `cleos set contract`?

**Comment by niutaifan** [comment]
> 您试图在哪个网络上执行`cleos set contract`？
I have been tested locally, ready to deploy the main network formal environment, and combine with my project.

**Comment by niutaifan** [comment]
![Uploading image.png…]()

**Comment by niutaifan** [comment]
![image](https://user-images.githubusercontent.com/22468286/45658454-84bb9180-bb21-11e8-937d-bc288957957f.png)

**Comment by taokayan** [comment]
You can't set the contract for system account ```eosio``` in mainnet

**Comment by niutaifan** [comment]
Thank you. I think I'm confused.

**Comment by andriantolie** [comment]
`eosio.bios` contract is used to bootstrap the network. The mainnet has been bootstrapped so you don't need to do the above thing anymore and you won't be allowed to do so.
