### ISSUE TITLE
Boost libraries could not be found:boost_system、boost_chrono、boost_program_options、boost_unit_test_framework、boost_locale

### ISSUE THREAD

**Issue by byterminator** [EOSIO/eos#5700]
eostest@ubuntu:~/eos$ ./eosio_build.sh

	Beginning build version: 1.2
	Mon Sep 17 18:50:24 UTC 2018
	User: eostest
	git head id: 08819aae0fb22aaa0d91c95990370278bea5243f
	Current branch: master

	ARCHITECTURE: Linux

	OS name: Ubuntu
	OS Version: 18.04
	CPU speed: 2494.370Mhz
	CPU cores: 2
	Physical Memory: 2978 Mgb
	Disk install: /dev/sda1
	Disk space total: 26G
	Disk space available: 12G
	Your system must have 7 or more Gigabytes of physical memory installed.
	Exiting now.
	You must have at least 20GB of available storage to install EOSIO.
	Exiting now.

	Checking for installed dependencies.

	Package clang-4.0 found.
	Package lldb-4.0 found.
	Package libclang-4.0-dev found.
	Package cmake found.
	Package make found.
	Package automake found.
	Package libbz2-dev found.
	Package libssl-dev found.
	Package libgmp3-dev found.
	Package autotools-dev found.
	Package build-essential found.
	Package libicu-dev found.
	Package python2.7-dev found.
	Package python3-dev found.
	Package autoconf found.
	Package libtool found.
	Package curl found.
	Package zlib1g-dev found.
	Package doxygen found.
	Package graphviz found.

	No required dpkg dependencies to install.

	Checking boost library installation.
	Boost found at /home/eostest/opt/boost.

	Checking MongoDB installation.
	MongoDB configuration found at /home/eostest/opt/mongodb/mongod.conf.

	Checking MongoDB C++ driver installation.
	Mongo C++ driver found at /usr/local/lib/libmongocxx-static.a.

	Checking secp256k1-zkp installation.
	secp256k1 found @ /usr/local/lib.

	Checking for LLVM with WASM support.
	WASM found at /home/eostest/opt/wasm/bin.

>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOSIO

>>>>>>>> CMAKE_BUILD_TYPE=Release
>>>>>>>> ENABLE_COVERAGE_TESTING=false
>>>>>>>> DOXYGEN=false

-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: /home/eostest/opt/boost/include

  The following Boost libraries could not be found:

          **boost_system
          boost_program_options
          boost_signals
          boost_serialization
          boost_chrono
          boost_unit_test_framework
          boost_locale**

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:98 (FIND_PACKAGE)

-- Configuring EOSIO on Linux
-- binaryen building with -std=c++11
-- binaryen building for platform x86-64
-- binaryen building with -Wall
-- binaryen building with -Werror
-- binaryen building with -Wextra
-- binaryen building with -Wno-unused-parameter
-- binaryen building with -fno-omit-frame-pointer
-- binaryen building with -fPIC
-- binaryen building with -O2
-- binaryen building with -UNDEBUG
-- Using 'SYS' as CORE symbol name
-- Using 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV' as public key for 'eosio' account
-- Using WASM clang => /home/eostest/opt/wasm/bin/clang
-- Using WASM llc => /home/eostest/opt/wasm/bin/llc
-- Using WASM llvm-link => /home/eostest/opt/wasm/bin/llvm-link
-- Found Secp256k1: /usr/local/lib/libsecp256k1.a
-- Configuring fc to build on Unix/Apple
-- zlib found
-- Configuring Builtins
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: /home/eostest/opt/boost/include

  The following Boost libraries could not be found:

          boost_system
          boost_chrono
          boost_unit_test_framework
          boost_locale

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  libraries/chainbase/CMakeLists.txt:26 (FIND_PACKAGE)

-- Configuring ChainBase on Linux
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: /home/eostest/opt/boost/include

  The following Boost libraries could not be found:

          boost_system
          boost_chrono
          boost_program_options
          boost_unit_test_framework
          boost_locale

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  libraries/appbase/CMakeLists.txt:22 (find_package)

-- Configuring AppBase on Linux
-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: /usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-lgcc;-lgcc_s;-lc;-lgcc;-lgcc_s;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: /usr/local/lib/libmongocxx-static.a;/usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-lgcc;-lgcc_s;-lc;-lgcc;-lgcc_s;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread;/usr/local/lib/libmongoc-static-1.0.a;/usr/local/lib/libbson-static-1.0.a;-lgcc;-lgcc_s;-lc;-lgcc;-lgcc_s;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;rt;/usr/lib/x86_64-linux-gnu/libz.so;resolv
-- Git commit revision: 08819aae
-- Git commit revision: 08819aae
-- Git commit revision: 08819aae
-- Configuring incomplete, errors occurred!
See also "/home/eostest/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/eostest/eos/build/CMakeFiles/CMakeError.log".

	>>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.

**Comment by jgiszczak** [comment]
The build script attempts to build boost for you.  It appears your build of boost failed.
`rm -r /home/eostest/opt/boost` and rerun the build script.

**Comment by byterminator** [comment]
> The build script attempts to build boost for you. It appears your build of boost failed.
> `rm -r /home/eostest/opt/boost` and rerun the build script.

Thans bro,its ok,good！
