### ISSUE TITLE
I use the EOS Cleaner block data to start my server.  And it has the error. How can I change it?

### ISSUE THREAD

**Issue by zhousi666** [EOSIO/eos#5706]
I use the EOS Cleaner block data to start my server.  And it has the error. How can I change it?

data source : 
https://www.tuoluocaijing.cn/article/detail-5895.html
![image](https://user-images.githubusercontent.com/29378230/45661131-c272e700-bb2e-11e8-88b9-40de579f7e4a.png)
https://s3-ap-northeast-1.amazonaws.com/data.eos/index.html
![image](https://user-images.githubusercontent.com/29378230/45661158-d3bbf380-bb2e-11e8-87d0-52fa658f455d.png)

···
root@2f58dc37cb0d:~# nodeos --data-dir /root/data --config  /root/config/config.ini
2018-09-18T02:12:04.436 thread-0   http_plugin.cpp:344           plugin_initialize    ] configured http to listen on 0.0.0.0:8888
2018-09-18T02:12:04.436 thread-0   chain_plugin.cpp:317          plugin_initialize    ] initializing chain plugin
database created by a different compiler, build, boost version, or operating system
Environment differences (host vs database):
 Compiler Version: 
                   342e322e3120436f6d70617469626c6520436c616e6720342e302e312028746167732f52454c454153455f3430312f66696e616c2900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 "4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final) "
                   vs
                   342e322e3120436f6d70617469626c6520436c616e6720342e302e302028746167732f52454c454153455f3430302f726331290000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 "4.2.1 Compatible Clang 4.0.0 (tags/RELEASE_400/rc1) "
 Debug: 0 vs 0
 Apple: 0 vs 0
 Windows: 0 vs 0
 Boost Version: 106700 vs 106700
2018-09-18T02:12:04.496 thread-0   chain_plugin.cpp:632          plugin_initialize    ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: database created by a different compiler, build, boost version, or operating system
rethrow database created by a different compiler, build, boost version, or operating system: 
    {"what":"database created by a different compiler, build, boost version, or operating system"}
    thread-0  chain_plugin.cpp:632 plugin_initialize
2018-09-18T02:12:04.496 thread-0   main.cpp:125                  main                 ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: database created by a different compiler, build, boost version, or operating system
rethrow database created by a different compiler, build, boost version, or operating system: 
    {"what":"database created by a different compiler, build, boost version, or operating system"}
    thread-0  chain_plugin.cpp:632 plugin_initialize
···

**Comment by taokayan** [comment]
Looks like you have different version of Clang which make the database incompatible. It is recommend to sync with the mainnet instead of downloading a database from somewhere.

**Comment by jgiszczak** [comment]
You may launch nodeos with the addition of `--replay-blockchain`.  State can only be used if all aspects of the build environment are identical.  The block log can still be used when the compiler differs, so replay from the downloaded block log to recreate state.  Use that option only once unless replay is interrupted or fails.  After successful replay, remove the option from the command line.

**Comment by vlyl** [comment]
> I use the EOS Cleaner block data to start my server. And it has the error. How can I change it?
> 
> data source :
> https://www.tuoluocaijing.cn/article/detail-5895.html
> ![image](https://user-images.githubusercontent.com/29378230/45661131-c272e700-bb2e-11e8-88b9-40de579f7e4a.png)
> https://s3-ap-northeast-1.amazonaws.com/data.eos/index.html
> ![image](https://user-images.githubusercontent.com/29378230/45661158-d3bbf380-bb2e-11e8-87d0-52fa658f455d.png)
> 
> ···
> root@2f58dc37cb0d:~# nodeos --data-dir /root/data --config /root/config/config.ini
> 2018-09-18T02:12:04.436 thread-0 http_plugin.cpp:344 plugin_initialize ] configured http to listen on 0.0.0.0:8888
> 2018-09-18T02:12:04.436 thread-0 chain_plugin.cpp:317 plugin_initialize ] initializing chain plugin
> database created by a different compiler, build, boost version, or operating system
> Environment differences (host vs database):
> Compiler Version:
> 342e322e3120436f6d70617469626c6520436c616e6720342e302e312028746167732f52454c454153455f3430312f66696e616c2900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 "4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final) "
> vs
> 342e322e3120436f6d70617469626c6520436c616e6720342e302e302028746167732f52454c454153455f3430302f726331290000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 "4.2.1 Compatible Clang 4.0.0 (tags/RELEASE_400/rc1) "
> Debug: 0 vs 0
> Apple: 0 vs 0
> Windows: 0 vs 0
> Boost Version: 106700 vs 106700
> 2018-09-18T02:12:04.496 thread-0 chain_plugin.cpp:632 plugin_initialize ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: database created by a different compiler, build, boost version, or operating system
> rethrow database created by a different compiler, build, boost version, or operating system:
> {"what":"database created by a different compiler, build, boost version, or operating system"}
> thread-0 chain_plugin.cpp:632 plugin_initialize
> 2018-09-18T02:12:04.496 thread-0 main.cpp:125 main ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: database created by a different compiler, build, boost version, or operating system
> rethrow database created by a different compiler, build, boost version, or operating system:
> {"what":"database created by a different compiler, build, boost version, or operating system"}
> thread-0 chain_plugin.cpp:632 plugin_initialize
> ···

I known how to solve this problem, but, unfortunately, I cann't open download page anymore

**Comment by freddieee** [comment]
> > I use the EOS Cleaner block data to start my server. And it has the error. How can I change it?
> > data source :
> > https://www.tuoluocaijing.cn/article/detail-5895.html
> > ![image](https://user-images.githubusercontent.com/29378230/45661131-c272e700-bb2e-11e8-88b9-40de579f7e4a.png)
> > https://s3-ap-northeast-1.amazonaws.com/data.eos/index.html
> > ![image](https://user-images.githubusercontent.com/29378230/45661158-d3bbf380-bb2e-11e8-87d0-52fa658f455d.png)
> > ···
> > root@2f58dc37cb0d:~# nodeos --data-dir /root/data --config /root/config/config.ini
> > 2018-09-18T02:12:04.436 thread-0 http_plugin.cpp:344 plugin_initialize ] configured http to listen on 0.0.0.0:8888
> > 2018-09-18T02:12:04.436 thread-0 chain_plugin.cpp:317 plugin_initialize ] initializing chain plugin
> > database created by a different compiler, build, boost version, or operating system
> > Environment differences (host vs database):
> > Compiler Version:
> > 342e322e3120436f6d70617469626c6520436c616e6720342e302e312028746167732f52454c454153455f3430312f66696e616c2900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 "4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final) "
> > vs
> > 342e322e3120436f6d70617469626c6520436c616e6720342e302e302028746167732f52454c454153455f3430302f726331290000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 "4.2.1 Compatible Clang 4.0.0 (tags/RELEASE_400/rc1) "
> > Debug: 0 vs 0
> > Apple: 0 vs 0
> > Windows: 0 vs 0
> > Boost Version: 106700 vs 106700
> > 2018-09-18T02:12:04.496 thread-0 chain_plugin.cpp:632 plugin_initialize ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: database created by a different compiler, build, boost version, or operating system
> > rethrow database created by a different compiler, build, boost version, or operating system:
> > {"what":"database created by a different compiler, build, boost version, or operating system"}
> > thread-0 chain_plugin.cpp:632 plugin_initialize
> > 2018-09-18T02:12:04.496 thread-0 main.cpp:125 main ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: database created by a different compiler, build, boost version, or operating system
> > rethrow database created by a different compiler, build, boost version, or operating system:
> > {"what":"database created by a different compiler, build, boost version, or operating system"}
> > thread-0 chain_plugin.cpp:632 plugin_initialize
> > ···
> 
> I known how to solve this problem, but, unfortunately, I cann't open download page anymore

@vlyl Hi dude, I also encountered this issue, would u mind sharing your solution?

**Comment by vlyl** [comment]
> > > I use the EOS Cleaner block data to start my server. And it has the error. How can I change it?
> > > data source :
> > > https://www.tuoluocaijing.cn/article/detail-5895.html
> > > ![image](https://user-images.githubusercontent.com/29378230/45661131-c272e700-bb2e-11e8-88b9-40de579f7e4a.png)
> > > https://s3-ap-northeast-1.amazonaws.com/data.eos/index.html
> > > ![image](https://user-images.githubusercontent.com/29378230/45661158-d3bbf380-bb2e-11e8-87d0-52fa658f455d.png)
> > > ···
> > > root@2f58dc37cb0d:~# nodeos --data-dir /root/data --config /root/config/config.ini
> > > 2018-09-18T02:12:04.436 thread-0 http_plugin.cpp:344 plugin_initialize ] configured http to listen on 0.0.0.0:8888
> > > 2018-09-18T02:12:04.436 thread-0 chain_plugin.cpp:317 plugin_initialize ] initializing chain plugin
> > > database created by a different compiler, build, boost version, or operating system
> > > Environment differences (host vs database):
> > > Compiler Version:
> > > 342e322e3120436f6d70617469626c6520436c616e6720342e302e312028746167732f52454c454153455f3430312f66696e616c2900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 "4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final) "
> > > vs
> > > 342e322e3120436f6d70617469626c6520436c616e6720342e302e302028746167732f52454c454153455f3430302f726331290000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 "4.2.1 Compatible Clang 4.0.0 (tags/RELEASE_400/rc1) "
> > > Debug: 0 vs 0
> > > Apple: 0 vs 0
> > > Windows: 0 vs 0
> > > Boost Version: 106700 vs 106700
> > > 2018-09-18T02:12:04.496 thread-0 chain_plugin.cpp:632 plugin_initialize ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: database created by a different compiler, build, boost version, or operating system
> > > rethrow database created by a different compiler, build, boost version, or operating system:
> > > {"what":"database created by a different compiler, build, boost version, or operating system"}
> > > thread-0 chain_plugin.cpp:632 plugin_initialize
> > > 2018-09-18T02:12:04.496 thread-0 main.cpp:125 main ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE: database created by a different compiler, build, boost version, or operating system
> > > rethrow database created by a different compiler, build, boost version, or operating system:
> > > {"what":"database created by a different compiler, build, boost version, or operating system"}
> > > thread-0 chain_plugin.cpp:632 plugin_initialize
> > > ···
> > 
> > 
> > I known how to solve this problem, but, unfortunately, I cann't open download page anymore
> 
> @vlyl Hi dude, I also encountered this issue, would u mind sharing your solution?

Sorry, I forgot the details but change the version of compiler or some configuration file works. 

This bucket can't access for a long time, can you still use it now?
