### ISSUE TITLE
NOOB Main Network Dockerfile

### ISSUE THREAD

**Issue by ChrisCates** [EOSIO/eos#5708]
I created a NOOB (new out of box) Dockerfile for the EOS Mainnet. This syncs with the latest blocks from https://eosnode.tools and runs with a hard replay.

It would also be useful if everyone had access to such a thing, so that they can simply run an EOS Mainnet RPC node with ease with a Dockerfile instead of having to configure downloading the blocks themselves.

Here's the `Dockerfile` I created:

```docker
FROM eosio/eos
USER root

RUN apt-get update
RUN apt-get install curl -y

RUN curl https://eosnode.tools/api/blocks?os=Ubuntu+18.04&limit=1 -o /opt/eosio/bin/blocks.tar.gz
RUN curl https://raw.githubusercontent.com/CryptoLions/EOS-MainNet/master/genesis.json -o /opt/eosio/bin/genesis.json
RUN curl https://raw.githubusercontent.com/CryptoLions/EOS-MainNet/master/config.ini -o /opt/eosio/bin/config.ini

WORKDIR /opt/eosio/bin
RUN tar xvzf blocks.tar.gz

EXPOSE 9876
EXPOSE 8888
CMD ["/bin/bash", "-c", "nodeos --data-dir=/opt/eosio/bin --hard-replay"]
```

**Feedback would be greatly appreciated!**

**Comment by taokayan** [comment]
Thanks for your contribution to EOS!

**Comment by ChrisCates** [comment]
@taokayan, in terms of distribution. 

There should probably be a folder called `Docker/mainnet`.
In that folder it can container a `Dockerfile` and `docker-compose.yml` file.

Also, it would probably be in the best interest of eosio to publish this `Dockerfile` as something like `eosio/eos-mainnet`. Something like that.

Also, there should be documentation specifying they can deploy with this dockerfile.
I'd think this is pretty important to have in the `README.md` file.

What do you think?

**Comment by jgiszczak** [comment]
Block.one does not endorse any particular instantiation of the EOS.IO software.  You might file your suggestion with the [mainnet repo](https://github.com/EOS-Mainnet) instead.
