### ISSUE TITLE
p2p sync pending transactions

### ISSUE THREAD

**Issue by pmesnier** [EOSIO/eos#571]
moving this over from #550. This also relates to super-isssue #291.

I believe I have a solution to the problem of effectively sending 1000s of pending transactions to a newly started producer node. I assume that a non-producing node has no need to cache pending transactions apart fromm possibly being able to forward transacitions on to other producer nodes.

The solution is it add a second queue on the connection object that would be filled with previously packed transactions. Then bundles of transactions are sent out at a lower priority than the notification and request messages.

The pending txn queue can be popluated with all cached packed transactions, or with all except those in a list, or only with those in the list.

Testing is proceeding.

**Comment by pmesnier** [comment]
This enhancement includes 2 extensions to the p2p protocol - I added a new message, "go_away" to convey that a compliant peer should not try to reconnect after an active connection closure. This allows for redundant remote connections in the node's config to facilitate quick reconnection after peer restart without worrying about duplication of messages.

Second, I extended the data passed with the notify and request messages, adding a "mode" for distinguishing between normal or catch-up modes, and an explicit indication that either the block or the transaction list is not supplied, rather than being supplied but empty. In catch-up mode, an empty id list in the request means send all pending blocks or transactions, whereas a nonempty list with a catchup-up messages indicates which block or transactions to not send, think of "send all except these"

**Comment by pmesnier** [comment]
still in progress. Most recent push includes all the pieces necessary (IMO) to sort out initial sync once and for all. Still a little buggy in terms of determining which participant should do what, but I've got 10 hours of train time today to sort that all out.

**Comment by pmesnier** [comment]
This issue morphed into something larger, bringing in block sync topics, and the use of summaries. Also addressed is issue #429. All of these topics are related and in many cases influenced by the same functions, so I feel this commingling of issues is warranted.

**Comment by heifner** [comment]
Replaced by #644
