### ISSUE TITLE
How to get Action information when Trx is a string.it is no information？

### ISSUE THREAD

**Issue by JDalready** [EOSIO/eos#5711]
{
    "timestamp": "2018-09-18T05:29:00.000",
    "producer": "eosio",
    "confirmed": 0,
    "previous": "00027b940a181bfc8507533098e58868b1504d92509bd79006c10a57b1c770dd",
    "transaction_mroot": "3e4151a1e4c39cee0675244e0ad032d5b29bdc679fa5e13788fab493ae198fac",
    "action_mroot": "c9b7adef5348cdc8c7d73d53e8e6ec4c6444eaa83c20ed1034fe3c7fd8f77f18",
    "schedule_version": 0,
    "new_producers": null,
    "header_extensions": [],
    "producer_signature": "SIG_K1_KiKwFsaQvcr82ySo2KkiMMHjbRnMqhaEGuaQZ6dUkg4qbShLwNHQYmc5h9Wk7B1SWVuLiMDKP16eXqwvVUsBtc9APMmPJF",
    "transactions": [
        {
            "status": "executed",
            "cpu_usage_us": 3705,
            "net_usage_words": 6,
            "trx": "647cd18d0bb53272675bce7403c70ef9c7ee60cf18e55a4214838dc13abebe53"
        }
    ],
    "block_extensions": [],
    "id": "00027b95a8a8a9a6d8524693e1f0f9a1853254653587fa6b82087b351ce944ae",
    "block_num": 162709,
    "ref_block_prefix": 2470859480
}

Action information how to get ?

**Comment by taokayan** [comment]
looks like 647cd18d0bb53272675bce7403c70ef9c7ee60cf18e55a4214838dc13abebe53 is your txn id. You can use ```cleos get block 162709``` to retrieve all txns inside that block.

**Comment by JDalready** [comment]
it is my get block 162709 to information ,but the trx hasn't other information .
Ordinary trx has action, but this is just a string.

"trx": { "id": "c68b4890b464d6da418b6fb6b5d99ec7e27189c3c62ec9c4e68929ecb1ef6536", "signatures": [ "SIG_K1_K8ytR9hjDeWp8rRrM51f3jiqQQpgdJNAoitvFiGP4fYHCACBEEoyvmTLNgETEdPJeFHbjmenP5yAmwis5erU56ixnfrzj7" ], "compression": "none", "packed_context_free_data": "", "context_free_data": [], "packed_trx": "eaed7c5b2f2ca14893eb00000000011082422e6575305500405647ed48b1ba0140a7c3066575305500000000489aa6b94abdfb000000000000002009d4875dcda2218f9c50fc983e0743a86d43329212ffaea7c6d173d94c35ec422a80597ce8fb7b78f1eb906e1e6e17b38a57ba8b0ee533eef7bccf101923412c00", "transaction": { "expiration": "2018-08-22T05:00:26", "ref_block_num": 11311, "ref_block_prefix": 3952298145, "max_net_usage_words": 0, "max_cpu_usage_ms": 0, "delay_sec": 0, "context_free_actions": [], "actions": [{ "account": "eosbetdice11", "name": "resolvebet", "authorization": [{ "actor": "eosbetcasino", "permission": "random" } ], "data": { "bet_id": 64445, "sig": "SIG_K1_KW2uhvjDgCA2pfiE3cKzTbV6dGraBrCttPyPhehtbDVjtCUvF36PugoEkcLFode9LHrHi41vRC9HCFjgomWWC3XqcS3nQR" }, "hex_data": "bdfb000000000000002009d4875dcda2218f9c50fc983e0743a86d43329212ffaea7c6d173d94c35ec422a80597ce8fb7b78f1eb906e1e6e17b38a57ba8b0ee533eef7bccf101923412c" } ], "transaction_extensions": [] }

**Comment by JDalready** [comment]
@sergmetelin @taokayan

**Comment by taokayan** [comment]
This is likely because the trx is a deferred trx. Please ask in eosio.stackexchange.com if you have further questions.
