### ISSUE TITLE
How can I get code hash from contract ABI or WAST files?

### ISSUE THREAD

**Issue by young-mu** [EOSIO/eos#5712]
The `cleos` provides `get code` subcommand to get code hash of contract under certain account. 

```shell
> cleos get code <account>
```

This can work on the premise that the contract is deployed into chain. 

Now I want to get code hash from contract ABI and WAST files, in order to know if the contract is the version deployed into chain.

**Comment by taokayan** [comment]
The simplest way is to get the wasm file and abi from the blockchain to verify if they're what you expect. If you really want to get the code hash from the wasm file, you need to do exactly the same as function apply_eosio_setcode in eosio_contract.cpp:
```
     code_id = fc::sha256::hash( act.code.data(), (uint32_t)act.code.size() );
```

**Comment by young-mu** [comment]
@taokayan 

Got it. Thanks!
