### ISSUE TITLE
Empty value for account_name

### ISSUE THREAD

**Issue by artjoma** [EOSIO/eos#5724]
Hey, what is empty value for variable type account_name? 0 ? May be exists something like const EMPTY_ACCOUNT?

**Comment by jgiszczak** [comment]
In the C++ code, an account name is an integer under the hood.  Zero is considered empty.  See `account_name proxy` in `eosio.system.hpp`, for example.

**Comment by artjoma** [comment]
json representation of empty account_name is 
```
"field": "...aui...1qsg"  
```

**Comment by artjoma** [comment]
All is fine, I found bug in the contract.
