### ISSUE TITLE
Can't deploy contract from outside of nodeos container

### ISSUE THREAD

**Issue by AlwaysFurther** [EOSIO/eos#5726]
Hello,

I am running a docker for nodeos and a docker for keosd

When I am inside the nodeos container, I manage to deploy a contract. The problem is that to do so I have to import my wallet to nodeos because it cannot find the one that I put on keosd. For me this is a problem because then I have to unlock my wallet on nodeos which doesn't seem too secure because if other people are connected to this node they can see my password.

So I want to deploy the contract from the client side (in my bash outside the docker container) but I get the following error:

`Reading WASM from hello2/hello2.wasm...
Error 3160009: No wast file found
Error Details:
no wasm file found hello2/hello2.wasm
`

The wasm file is present in the hello2 folder

Thank you for your help

**Comment by taokayan** [comment]
This seems to be a file path issue. what's your corresponding cleos command? Can you try using the absolute path?

**Comment by AlwaysFurther** [comment]
hi @taokayan ,
Thanks for the answer,
I use cleos like this 

```
alias cleos='docker exec -i keosd /opt/eosio/bin/cleos --url http://nodeos:8888 --wallet-url http://127.0.0.1:9876'
```

**Comment by dixia** [comment]
Hi @AlwaysFurther what important here is the absolute path to the contract file. Not the command line of cleos.

**Comment by dixia** [comment]
btw for this kind of question, it is better to go to EOSIO stack exchange https://eosio.stackexchange.com/

**Comment by jgiszczak** [comment]
Rather than using `docker start eosio`, use a custom command line as outlined [here](https://developers.eos.io/eosio-home/docs/getting-the-software#section-step-2-boot-node-and-wallet).  Be sure to substitute your actual path for `CONTRACTS_DIR`.
