### ISSUE TITLE
When can I consider a transfer is confirmed?

### ISSUE THREAD

**Issue by shwuhk** [EOSIO/eos#5729]
I am going to send out products to user when they pay me EOS.
I got a service monitor the blockchain transaction. Can I send the product to the user once I see the transaction in the blockchain? Or I should only send the product if the transaction in the block become irreversible(but this got around 2.5minutes delay)? Thanks.

**Comment by jgiszczak** [comment]
Irreversibility is transfer confirmation.  Up until that point the transaction may be reversed, after which you have no money for the product.

**Comment by shwuhk** [comment]
@jgiszczak Is the possibility of reversing a transaction high if the transaction is included in a block?
