### ISSUE TITLE
Multisig Permissions Question

### ISSUE THREAD

**Issue by srmcatee1110** [EOSIO/eos#5736]
I have a question about multisig and permissions

Owner:  Can change or grant anything on an account
Active: Can publish smart contract to account and call the contract.  Can also approve multisig proposals.

Custom Permission:  If I create a custom permission.  Can it do approve of multisig's?  Or does it only allow set action permissions to actions on the smart contract?

What I am trying to do is have an account that can approve a proposed transaction but have no other authority against the account.

Thanks in advance for any insight.

**Comment by taokayan** [comment]
The permission level used to approve a multisig proposal is defined in the proposal itself. It might not be account@active or account@owner.

More precisely, multisig is basically used for signing a transaction by different accounts, in such a way that the combination of signatures can satisfy the authorization defined by the real actions inside the proposal. For example:

- action1 in contract1 requires authorization of contract1@action1, and contract1@action1 require both user1@action1 and user2@action1.
- user1 proposes a multisig with requested permission level of user1@action1 & user2@action1. And the transaction inside the multisig proposal contains action1 of contract1 with authorization of contract1@action1.
- user1 approve by using the private key of user1@action1 to sign.
- user2 approve by using the private key of user2@action1 to sign.

- now either user1 and user2 can execute the proposal, which actually execute action1 in contract1.

**Comment by srmcatee1110** [comment]
Thank you.  Couple of questions.  What gives an account the permission to propose a transaction against another account?  Do they have to be active on the account they are proposing to?  Trying to make sure who can propose and sign a proposal cannot change the contract.

Would this code example work?

`cleos set account permission sigacct1 permaction1 '{"threshold":2,"keys":[],"accounts":[{"permission":{"actor":"acct1","permission":"active"},"weight":1},{"permission":{"actor":"acct2","permission":"active"},"weight":1}],"waits":[]}' owner -p sigacct1@owner

cleos multisig propose prop1 '[{"actor": "acct1", "permission": "permaction1"},{"actor": "acct2", "permission": "permaction1"}]' '[{"actor": "sigacct1", "permission": "active"}]' sigacct1  contractact1 '{"acct1":"acct1", "acct2":"acct2"}' -p acct2@active
`

**Comment by srmcatee1110** [comment]
I answered my own question.  Any permission below active cannot change or load a new smart contract.
