### ISSUE TITLE
Docker build for 1.2.5 fails

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#5738]
after doing  "docker pull eosio/builder:latest"
I can no longer build eosio 1.2.5

What builder version do I need to pull to get a builder to compile 1.2.5?

The docker build process for eosio 1.2.5 goes like this (using latest):

-- The C compiler identification is Clang 4.0.1
-- The CXX compiler identification is Clang 4.0.1
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Secp256k1 (missing: Secp256k1_INCLUDE_DIR Secp256k1_LIBRARY)                                                                                                                                       
Call Stack (most recent call first):                                                                                                                                                                                
  /usr/local/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)                                                                                                               
  libraries/fc/CMakeModules/FindSecp256k1.cmake:39 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)                                                                                                                              
  CMakeLists.txt:77 (find_package)

**Comment by ajose01** [comment]
I am having the same issue on 1.2.5

**Comment by matthewdarwin** [comment]
If the official docker image cannot be fixed, can the Dockerfile that was used be provided and we can build our own docker image?

**Comment by jgiszczak** [comment]
The Dockerfile is in the repository, under the `Docker` directory.

**Comment by andriantolie** [comment]
Please try with the latest version of eosio builder. And as @jgiszczak said, the Dockerfile is inside the Docker folder in the repository. 

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
