### ISSUE TITLE
RAM Question

### ISSUE THREAD

**Issue by bixf** [EOSIO/eos#5739]
hi, i did some trxs on the mainnet, from what i seen, sender always need to pay some ram for each trx. and only sometime, the ram was released. then, i monitored some other accounts on the mainnet. just after they sent the trx, i checked these accounts and found that their ram remained. in my own case ,how did this ram release happened? and is there some operation can be take to keep the ram be available ,like all the time?

**Comment by taokayan** [comment]
The RAM payer is deteremined in the code of the corresponding contract. Normal transfer operations will not cause extra RAM usage unless you need to pay RAM for your storage of your token balance for the first time. More precisely, if one contract want to store some data into the multi_index table, the contract owner can let himself or the user to pay the RAM. The RAM will be released if the contract remove the data or replace with a smaller data from the original table.

There's no clear way to limit your RAM usage when you push a transaction, as extra RAM usage is expected at some time, just like you need to allocate some RAM to store your crypto pets, or play a bet game, etc.

**Comment by bixf** [comment]
ok, thx
