### ISSUE TITLE
How about the development schedule of the project?

### ISSUE THREAD

**Issue by neove** [EOSIO/eos#574]
i am a big fan of EOS , i want to know about how the project develops now

**Comment by strahe** [comment]
+1

**Comment by dskvr** [comment]
This is not a development issue, please visit the telegram.

**Comment by neove** [comment]
@strahe 中国朋友么？ 你怎么看EOS

**Comment by malei** [comment]
哈哈哈 中文好啦

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.8.75&pv=10.12.2&source=email_footer_2]
On Thu, Oct 19, 2017 at 9:25, neo <notifications@github.com> wrote:
@strahe [https://github.com/strahe] 中国朋友么？ 你怎么看EOS

**Comment by strahe** [comment]
@neove tg群链接, 需要番强

**Comment by neove** [comment]
@strahe 翻墙了   打不开，不知道咋回事

**Comment by neove** [comment]
估计也就到明年看看有啥利好和进展了

**Comment by philsong** [comment]
我正在「区块链金融」和朋友们讨论有趣的话题，你一起来吧？
https://t.xiaomiquan.com/nqZfmQv
