### ISSUE TITLE
Building latest version of EOSIO code results in build-error, on Linux Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by WendySanarwanto** [EOSIO/eos#5756]
### Steps to replicate:

1. Update `eosio/eos` local repository (either on `master` or `release` branches, does not matter), through running `git pull` command.
2. Move into `eosio/eos` local directory on command terminal through using `cd` command (e.g. `cd ~/github/eosio/`).
3. Remove `build` directory by invoking `rm -rf build` command.
4. Run `./eosio_build.sh` command to build the `eosio`.

### Actual outcome:
When the build's progress is at 98%, the build process is ended as error, as shown in this following screenshot:
![image](https://user-images.githubusercontent.com/18456618/45787701-30dbb480-bca9-11e8-88c8-95d377778aa2.png)

### Machine environment:

- OS: latest updated Linux Ubuntu 18.04.1 LTS
![image](https://user-images.githubusercontent.com/18456618/45787752-61bbe980-bca9-11e8-80a6-b32e43aa0982.png)
![image](https://user-images.githubusercontent.com/18456618/45787898-21a93680-bcaa-11e8-9757-d95fe6afc07f.png)

- Spec: CPU i5, RAM 16 GB, SSD

### Steps to resolve the issue:

- Run ` ` command to wipe out all `libmongoc` files from prior version's build(s).
- Re-run EOSIO build command (e.g. `~/github/eos/eosio_build.sh`). Confirm that the build error does not happen anymore.

**Comment by jgiszczak** [comment]
Depending on the age of your last build, you may need to remove some or all of the dependencies that were downloaded and compiled in `~/opt`.  You may also need to force a rebuild of the Mongo interface library by removing the previous one: `rm /usr/local/lib/libmongocxx-static.a`.

**Comment by WendySanarwanto** [comment]
Hello @jgiszczak. I followed your idea by deleting every `libmongoc*` inside `/usr/local/lib/` by invoking `sudo rm -rf /usr/local/lib/libmongoc*` command then re-run `./eosio_build.sh` build command. The build process is ended as success. Thank you, I am going to close this ticket. 
Cheers.
