### ISSUE TITLE
What is the require port running node?

### ISSUE THREAD

**Issue by mademin** [EOSIO/eos#5761]
Hello, I was running EOS node in my private server. So I will open the port.

What is the require port?

**Comment by firesWu** [comment]
Did you mean http api and p2p port?  you can configure it in `config.ini`

**Comment by taokayan** [comment]
Depends on your usage. You don't need to open any listening port if you just want to sync-up or use it locally. However you might need to open the port specified by ```http-server-address``` if you want remote clients connect to nodeos.

**Comment by mademin** [comment]
I want to my node is trust node. block sync and push trnasaction. so I was opened http port and p2p port. that's all?
