### ISSUE TITLE
Reduce strictness of git describe failure

### ISSUE THREAD

**Issue by EugeneChung** [EOSIO/eos#5766]
‘’’
Scanning dependencies of target appbase_version
fatal: Not a git repository: fatal: Not a git repository: /var/lib/buildkite-agent/builds/.../.git/modules/libraries/fc/modules/secp256k1/upstream
fatal: 'git status --porcelain' failed in submodule libraries/fc
CMake Error at version.cmake:11 (message):
  git describe failed
‘’’

I’m also using buildkite and docker to build my chain product. After updating fc module which includes secp256k1 as external, I am getting the error above. With a terminal, git describe —tags —dirty is working well.

At first, I think it’s too strict to make it as build failure for preparing version information.
So I made a PR, https://github.com/EOSIO/appbase/pull/35, to reduce strictness of git describe failure. Please consider my PR to reflect.

**Comment by spoonincode** [comment]
I believe the reason you're getting that error is because you're using an old version of git that is buggy with recursive submodules. Specifically, it stores an absolute path to the submodule instead of a relative one. This causes problems as buildkite moves the cloned directory to different locations.

**Comment by EugeneChung** [comment]
git on the agent machine (git used by buildkite-agent) is the latest version of Ubuntu 16.04.
$ git --version
git version 2.7.4

Another git is in the docker container, eosio/ci:ubuntu. I guess it's 2.7.4, too.

**Comment by EugeneChung** [comment]
I upgraded git to 2.19.0 and it passed. Thanks.
