### ISSUE TITLE
While replaying, nodeos tries to remove state/ and blocks/ directory, even if it's a block device.

### ISSUE THREAD

**Issue by perduta** [EOSIO/eos#5767]
In Tokenika, we use high-performance ZFS datasets that are mounted in place of `state/` and `blocks/` directories. ZFS provides high IOPS possibilities and great snapshots, and we would like to use it with our EOSIO infrastructure nodes. EOS node has generally no problems with that running run-time, and snapshots make state backups easy and damn fast.
Unfortunately when executing `--replay` or `--hard-replay` nodeos attempts to remove/move whole dictionaries, instead of removing content of those which fails with our setup because you can't simply remove ZFS dataset (mounted in Linux like block device) with simple `rm -rf`.

Failure on removing `state/` directory:
```
nodeos@api1:/pool/nodeos$ /pool/nodeos/nodeos --data-dir /pool/nodeos/ --config-dir /pool/nodeos/ --replay                                                       
2018-09-20T11:37:21.718 thread-0   chain_plugin.cpp:317          plugin_initialize    ] initializing chain plugin
2018-09-20T11:37:21.719 thread-0   chain_plugin.cpp:482          plugin_initialize    ] Replay requested: deleting state database                    
2018-09-20T11:37:21.719 thread-0   chain_plugin.cpp:632          plugin_initialize    ] 13 N5boost10filesystem16filesystem_errorE: boost::filesystem::remove: Device or resource busy: "/pool/nodeos/state"
rethrow boost::filesystem::remove: Device or resource busy: "/pool/nodeos/state": 
    {"what":"boost::filesystem::remove: Device or resource busy: \"/pool/nodeos/state\""}
    thread-0  chain_plugin.cpp:632 plugin_initialize                                                           
2018-09-20T11:37:21.719 thread-0   main.cpp:125                  main                 ] 13 N5boost10filesystem16filesystem_errorE: boost::filesystem::remove: Device or resource busy: "/pool/nodeos/state"
rethrow boost::filesystem::remove: Device or resource busy: "/pool/nodeos/state":                                                     
    {"what":"boost::filesystem::remove: Device or resource busy: \"/pool/nodeos/state\""}
```
Failure on moving `blocks/` directory:
```
nodeos@api1:/pool/nodeos$ /pool/nodeos/nodeos --data-dir /pool/nodeos/ --config-dir /pool/nodeos/ --hard-replay
2018-09-20T11:40:18.556 thread-0   chain_plugin.cpp:317          plugin_initialize    ] initializing chain plugin                                                                                          
2018-09-20T11:40:18.556 thread-0   chain_plugin.cpp:462          plugin_initialize    ] Hard replay requested: deleting state database
2018-09-20T11:40:18.735 thread-0   block_log.cpp:325             repair_log           ] Recovering Block Log...
2018-09-20T11:40:18.738 thread-0   chain_plugin.cpp:632          plugin_initialize    ] 0 exception: unspecified
Rename from /pool/nodeos/blocks to /pool/nodeos/blocks-2018-09-20T11:40:18.735 failed because boost::filesystem::remove: Device or resource busy: "/pool/nodeos/blocks"
    {"srcfile":"/pool/nodeos/blocks","dstfile":"/pool/nodeos/blocks-2018-09-20T11:40:18.735","reason":"boost::filesystem::remove: Device or resource busy: \"/pool/nodeos/blocks\""}
    thread-0  filesystem.cpp:314 rename                                                                
2018-09-20T11:40:18.738 thread-0   main.cpp:125                  main                 ] 0 exception: unspecified
Rename from /pool/nodeos/blocks to /pool/nodeos/blocks-2018-09-20T11:40:18.735 failed because boost::filesystem::remove: Device or resource busy: "/pool/nodeos/blocks"
    {"srcfile":"/pool/nodeos/blocks","dstfile":"/pool/nodeos/blocks-2018-09-20T11:40:18.735","reason":"boost::filesystem::remove: Device or resource busy: \"/pool/nodeos/blocks\""}
    thread-0  filesystem.cpp:314 rename
rethrow
    {}
    thread-0  chain_plugin.cpp:632 plugin_initialize
```

**Proposed solution:**
Change `--replay` and `--hard-replay` behavior to remove/move content of directory instead of whole directory.

**Comment by jgiszczak** [comment]
This feature is available in release v1.3.0 for the state directory.  To solve the problem with the block directory, you should be mounting the `data/` directory as your dataset, rather than the `blocks/` directory.  (This also allows normal manipulation of the `state/` directory.)  That way subdirectories can behave normally, and your block log and state can be automatically kept in sync.

**Comment by perduta** [comment]
Thank you, I somehow missed that's solved in `v1.3.0`. Closing.

**Comment by cc32d9** [comment]
> This feature is available in release v1.3.0 for the state directory. To solve the problem with the block directory, you should be mounting the `data/` directory as your dataset, rather than the `blocks/` directory. (This also allows normal manipulation of the `state/` directory.) That way subdirectories can behave normally, and your block log and state can be automatically kept in sync.

no, totally wrong. Blocks are written linearly and they can reside on HDD easily. State is accessed totally randomly in small 4kb chunks, so it has to reside on SDD, or even a RAID array of SSD. They must not be forced to be on the same partition.

**Comment by cc32d9** [comment]
@perduta please reopen the issue if you have the permission.

**Comment by perduta** [comment]
Reopening to enable further discussion on this topic.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
