### ISSUE TITLE
nodeos Failed to initialize

### ISSUE THREAD

**Issue by dwucsm** [EOSIO/eos#5771]
~$ nodeos
2018-09-20T16:23:32.064 thread-0   chain_plugin.cpp:317          plugin_initialize    ] initializing chain plugin
2018-09-20T16:23:32.064 thread-0   chain_plugin.cpp:632          plugin_initialize    ] 3190000 block_log_exception: Block log exception
Block log was not setup properly with genesis information.
    {}
    thread-0  block_log.cpp:475 extract_genesis_state
Failed to initialize

My computer crashed and restarted, I can't launch nodeos, how can i do ?

**Comment by jgiszczak** [comment]
Assuming nodeos was previously working, you will need to include the correct `--data-dir` argument to `nodeos` so that it can find the block log it was using.  Follow the instructions you were using to start nodeos back up.

**Comment by MikeC-BC** [comment]
getting the same issue when on initialization with a `snapshot`.  Why was this issue closed?

**Comment by jgiszczak** [comment]
@MikeC-BC The referenced error message has been gone since October 2018.  There have been many improvements and many releases since then, including substantial work on better snapshot support in the October release.  You should upgrade to a much more recent release to successfully load snapshots together with a block log.

**Comment by mosjin** [comment]
I just "rm -rf ~/.local/share/eosio/nodeos/data/*" and used [the method in 4742](https://github.com/EOSIO/eos/issues/4742)  to let my EOS works.

> nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::http_plugin --plugin eosio::history_plugin --plugin eosio::history_api_plugin --access-control-allow-origin='*' --contracts-console --http-validate-host=false
