### ISSUE TITLE
Error 3090003, unsatisfied_authorization happens in push transaction

### ISSUE THREAD

**Issue by readygo586** [EOSIO/eos#5772]
When I try to use rpc to transfer currency, 3090003 happens. please refer the attachment for detail info.
 

{"code": 500, "message": "Internal Service Error", "error": {"code": 3090003, "name": "unsatisfied_authorization", "what": "Provided keys, permissions, and delays do not satisfy declared authorizations", "details": [{"message": "transaction declares authority \"{"actor":"testaccount1","permission":"active"}\", but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys ["EOS7gGChmszuw8FvzjbZ9t4HMXdKZfNG2rNywEzHZNyAPTsTEEX6v"]", "file": "authorization_manager.cpp", "line_number": 411, "method": "check_authorization"}]}}

[Error 390003, unsatisfied_authorization happens in push transaction.docx](https://github.com/EOSIO/eos/files/2402446/Error.390003.unsatisfied_authorization.happens.in.push.transaction.docx)

**Comment by readygo586** [comment]
testaccount1 info is listed below.
![image](https://user-images.githubusercontent.com/41469645/45838553-8e710f00-bd44-11e8-8b22-f00a159a17b2.png)

**Comment by jgiszczak** [comment]
Use the `--print-request` argument to a `cleos transfer` command to see the format you must use for the transaction you are submitting.  You may also wish to explore [eosjs](https://github.com/EOSIO/eosjs) or [eosjs2](https://github.com/EOSIO/eosjs2).

Note I do not read .docx attachments.  If you wish to paste a large amount of JSON in a readable format, Github supports the following markup:

> \```json
> { "your JSON data here" }
> \```

**Comment by readygo586** [comment]
@jgiszczak, Please read the attachment,  I think the import thing is not the json format.

**Comment by chrisli30** [comment]
Have you been able to fix it? This error is so annoying. cleos wallet private_keys shows that the keys are sitting there in wallet and used to sign the transaction, but somehow the contract is not able to verify the signature?
