### ISSUE TITLE
nodeos --constacts-console  database dirty flag set

### ISSUE THREAD

**Issue by lzqjfly** [EOSIO/eos#5778]
I run the contract,but i did not see any output from nodes.   So i restart `nodeos` with the `--contracts-console`

`$ nodeos --contracts-console`

2018-09-21T03:42:32.620 thread-0   chain_plugin.cpp:329          plugin_initialize    ] initializing chain plugin
2018-09-21T03:42:32.680 thread-0   chain_plugin.cpp:646          plugin_initialize    ] 13 St13runtime_error: database dirty flag set
rethrow database dirty flag set: 
    {"what":"database dirty flag set"}
    thread-0  chain_plugin.cpp:646 plugin_initialize
Failed to initialize

**Comment by lzqjfly** [comment]
I start the blockchain like :
` $ nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --contracts-console `
I can set the out logs

**Comment by yaanhyy** [comment]
--hard-replay will take too long time, eos has 23million blocks now.

**Comment by andriantolie** [comment]
As said by @heifner and @taokayan, it seems that your nodeos was killed forcefully before. Just start nodeos with `--hard-replay` option
