### ISSUE TITLE
action_traces is inside already confirmed?If not, how can I know that the transaction has been confirmed?

### ISSUE THREAD

**Issue by JDalready** [EOSIO/eos#5781]
I found that some unconfirmed transactions are also in the monogdb database.

**Comment by taokayan** [comment]
Whether a transaction is confirmed nor not depends on whether the block containing that transaction become irreversible. Normally around 330 block time are required to make a block become irreversible. Also if a block is rolled back, transactions in the block are likely applied again in other blocks. Setting a short expiration time in the transaction can make it completely fails earlier.

**Comment by taokayan** [comment]
closed as no reply. Please ask in eosio.stackexchange.com if you have further questions.
