### ISSUE TITLE
cleos: allow users to buy bytes

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#5783]
`cleos system create` supports `--buy-ram` (tokens) and `--buy-ram-kbytes`, but not `--buy-ram-bytes`.

`cleos system delegatebw` supports `--buyram`, but not the bytes or kbytes form.

`cleos system buyram` supports `--buy-ram` (tokens) and `--buy-ram-kbytes`, but not `--buy-ram-bytes`. 

If a user wants to buy ram and specify the number of bytes this is not currently possible since the `--buy-ram-kbytes` option take *KB* instead of bytes.

Please add a "--buy-ram-bytes" option to all three cleos commands.

**Comment by conr2d** [comment]
What do you think of the case that user set two options `--buy-ram-bytes` and `--buy-ram-kbytes` at the same time? Can we consider that user tries buying the summation of them, or should we trigger assert not to use both of them?

**Comment by tbfleming** [comment]
assert

**Comment by arhag** [comment]
Resolved by #5852.
