### ISSUE TITLE
cleos get transaction does not work unless provide block hint

### ISSUE THREAD

**Issue by shwuhk** [EOSIO/eos#5785]
Is it a bug or my config is wrong? cleos get transaction does not work even I give a valid transaction id. It only works if I provide the block hint. The error message is 
```
Error 3040011: The transaction can not be found
Error Details:
Transaction 2994e22aff0efba6fd9fa0001fc454116677c74b97c5252b6e100fa7bce6c4f8 not found in history and no block hint was given
```

**Comment by jgiszczak** [comment]
Upgrade nodeos to v1.3.0.  If you're querying a remote node, you'll need to find one that has upgraded.  A defect in transaction ID matching was fixed with PR #5723, included in that release.  Replay is not required after the upgrade, as the stored data was adequate and its format did not change.

**Comment by shwuhk** [comment]
@jgiszczak I don't have any experience in upgrading nodeos. Is it as simple as running ./eosio_build.sh and then ./eosio_install.sh? Anything more need to be done?

**Comment by jgiszczak** [comment]
For best results:
```sh
eos $ ./eosio_uninstall.sh
eos $ git pull
eos $ git submodule update --init --recursive
eos $ ./eosio_build.sh
eos $ ./eosio_install.sh
```

**Comment by shwuhk** [comment]
@jgiszczak I follow your step and tried to reinstall but it seems did not work. Can you please help? Thanks.
```
root@eosnode-template-2-c8mw:~# cleos -u http://127.0.0.1 get transaction 2994e22aff0efba6fd9fa0001fc454116677c74b97c5252b6e100fa7bce6c4f8 
Error 3040011: The transaction can not be found
Error Details:
Transaction 2994e22aff0efba6fd9fa0001fc454116677c74b97c5252b6e100fa7bce6c4f8 not found in history and no block hint was given
root@eosnode-template-2-c8mw:~# cleos -u http://127.0.0.1 get info^C
root@eosnode-template-2-c8mw:~# cleos version client
Build version: 0f6695cb
root@eosnode-template-2-c8mw:~# 
```

**Comment by jgiszczak** [comment]
I don't see the results of `get info` from nodeos.  It's the server side that needs the upgrade, not the client.
