### ISSUE TITLE
Verify user's signature in contract

### ISSUE THREAD

**Issue by oneroot001** [EOSIO/eos#5788]
User A has signed a message `msg` with signature `sig`.How can the third party verify this message in a contract? The verify method contract should be like this: 
```
void verify_user_sig(account_name user,string msg,string sig,public_key pubkey);
```

Because we can know `user`,`msg,sig` and user's `pubkey` ,we can recover the public key in contract.But the problem is how can we know that the `pubkey`submitted is the user's public key ?

**So the question is:**
How to get the account name of a public key in contract?

**Comment by taokayan** [comment]
see wasm interface API assert_recover_key & recover_key in wasm_interface.cpp

**Comment by superjyy** [comment]
A similar question, how to get the signature of a transaction in contract?

**Comment by taokayan** [comment]
You can only get the permission level from the action data in side your smart contract. For example "account1@active", which implicitly give you the idea that signature of account1 is provided. However, I don't think you can get the exact signature in hex in your smart contract. Please ask in eosio.stackexchange.com if you have further questions.
