### ISSUE TITLE
How to iterate all token holders

### ISSUE THREAD

**Issue by chuang39** [EOSIO/eos#5794]
For the contract like contracts/eosio.token, account is sharded and recorded by using user's name as scope. If I would like to find all holders for the token, how to iterate through accounts or how to iterate difference scopes? Thanks a lot!

Link for the contract eosio.token.
https://github.com/EOSIO/eos/tree/master/contracts/eosio.token

**Comment by csquan** [comment]
how?same problem?

**Comment by firesWu** [comment]
you can refer to this PR. #5486

**Comment by taokayan** [comment]
Yes, please upgrade to the latest version first. you can use "cleos get scope" with lower bound to iterator all possible scope inside a contract. Please quote the account name with a space as prefix, like: ```./cleos get scope eosio.token -L " 555555555555"```

**Comment by taokayan** [comment]
solved in https://github.com/EOSIO/eos/pull/5486

**Comment by mschoenebeck** [comment]
in the current version of eosio (2.1.0-1) `cleos get scope` is not available anymore. How to get all scopes/shards of a table?
