### ISSUE TITLE
get transaction error

### ISSUE THREAD

**Issue by ququzone** [EOSIO/eos#5795]
get transaction error on release v1.3.0

get transaction 776c609bd63d008a2336879cbca872f3b39896c564d70ab0d9cb10b0cb1af1c6 error: Error: {"code":500,"message":"Internal Service Error","error":{"code":10,"name":"assert_exception","what":"Assert Exception","details":[{"message":"(b & ~1) == 0: ","file":"raw.hpp","line_number":339,"method":"unpack"},{"message":"Error unpacking field context_free","file":"raw.hpp","line_number":368,"method":"operator()"},{"message":"error unpacking eosio::chain::action_trace","file":"raw.hpp","line_number":616,"method":"unpack"}]}}

**Comment by ququzone** [comment]
this problem maybe because not delete old blocks.

**Comment by CyrilCermak** [comment]
I am experiencing the same issue, one day everything worked perfectly fine and it has been circa 5 days since I am getting the 500 code from the blockchain.

**Comment by pete001** [comment]
Yep, seeing a bunch of these. Can be easily tripped with: 

```
curl https://eosapi.blockmatrix.network/v1/chain/get_account -X POST -d '{"account_name":"3gvhudgfjhge"}'
```

**Comment by pete001** [comment]
Also, for two nodes that are both running full history `filter-on = *` they are returning differently: 

This works: 

```
curl -siX POST https://api.eoslaomao.com/v1/history/get_transaction -d '{"id":"2955edda8577b6b0494ec83301d3a82d370c2e6aee839ff3829176a471dc3e46"}'
```

The same query on another node with full history, doesnt: 

```
curl -siX POST https://api.eossweden.se/v1/history/get_transaction -d '{"id":"2955edda8577b6b0494ec83301d3a82d370c2e6aee839ff3829176a471dc3e46"}'
```

**Comment by jgiszczak** [comment]
First, the account "3gvhudgfjhge" does not exist on the specified node, which is not the same error as the initial filing.  Second, eoslaomao no longer returns any history results.  Third, the history plugin had a defect where it could include failed deferred transactions in its history without correctly distinguishing them.  See #6220.  Fourth, to answer the original question, transaction retrieval could fail when an ABI had changed but an older transaction is being retrieved.  Try a newer version of the software, which will return the serialized version of the data in that case.

Finally, history plugin is deprecated.  The `get transaction` feature depends on it, and may no longer be available anywhere at some point.  Users needing to search transaction history should make arrangements to transition to other queryable systems, such as mongo.
