### ISSUE TITLE
could not gain write access to the shared memory file

### ISSUE THREAD

**Issue by 0x83043** [EOSIO/eos#58]
Hi! I've caught the error  wich related with rights i think. But i can't understand how to solve. Please help!

```
graphene@d657759b57d5:/eos$ eosd --config=./data-dir/config.ini
1540149ms thread-0   chain_plugin.cpp:60           plugin_initialize    ] initializing chain plugin
1540149ms thread-0   net_plugin.cpp:514            plugin_initialize    ] Initialize net plugin
1540149ms thread-0   net_plugin.cpp:520            plugin_initialize    ] configured net to listen on 127.0.0.1:9876
1540150ms thread-0   main.cpp:29                   main                 ] /eos/libraries/chainbase/src/chainbase.cpp(102): Throw in function chainbase::database::database(const bfs::path &, chainbase::database::open_flags, uint64_t)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: could not gain write access to the shared memory file
```

**Comment by pmesnier** [comment]
Hi,
Please run the following commands and report the results:
ls -l ./data-dir
ls -l ./data-dir/blockchain      \#or whatever you may have set the name to
umask
id

Then maybe we can figure out what the problem is

**Comment by 0x83043** [comment]
```
graphene@162f8d36c4a6:/eos$ ls -l ./data-dir
total 12
drwxrwxr-x 2 graphene graphene 4096 Jun 29 18:26 blockchain
drwxrwxr-x 2 graphene graphene 4096 Jun 29 18:59 blocks
-rw-rw-r-- 1 graphene graphene 2413 Jul  1 09:03 config.ini
graphene@162f8d36c4a6:/eos$ ls -l ./data-dir/blockchain
total 5196
-rw-r--r-- 1 graphene graphene 8589934592 Jul  1 09:03 shared_memory.bin
-rw-r--r-- 1 graphene graphene       2896 Jul  1 09:03 shared_memory.meta
graphene@162f8d36c4a6:/eos$ umask
0002
graphene@162f8d36c4a6:/eos$ id
uid=1000(graphene) gid=1000(graphene) groups=1000(graphene),27(sudo)
```

**Comment by pmesnier** [comment]
Oh, you're trying to open a second writer on the same file!
The distributed testnet capability is not yet ready, but when it is, you will need to provide a separate data directory for each eosd instance. There'll be other config settings to modify too.

For the time being, just run a single eosd instance.

Now, if you are only running a single instance of eosd then we will have to dig into the arcana of shared memory and file locks to see how to recover. Did your previous run of eosd get abruptly terminated by say kill -9 or some unhandled signal like a segv?

**Comment by 0x83043** [comment]
Oh, thanks! It still working after ^Z. I killed eosd, and started - it's ok. But next one:
`Not producing block because I don't have the private key for EOS6MRyA....`
How i can take valid kyes pair? It isn't take pair wich i try reg throw https://eos.io/distribution (i didn't send eth, may be in next windows).

**Comment by pmesnier** [comment]
OK, I don't have a full picture here. What are you trying to do?  Are you modifying anything?

what do you mean it is still working after a ^Z? ^Z sends a sigstop to the process, which should leave it in the process table, with all resources held, just waiting to be continued. Then you use either the fg or bg command to continue the process either foregrounded or backgrounded. Is that what you mean?

Regarding the keys, the supplied genesis.json file has defaulted keypairs that should just work. Maybe you need to refresh your local git workspace.

**Comment by 0x83043** [comment]
I was misled line after ^Z:
`[1]+  Stopped                 eosd --data-dir=/eos/data-dir/ --genesis-json=/eos/genesis.json`
I realized my mistake, thanks a lot!

I know about genesis.json with init nodes, but one pair need be listed  in config.ini. I have taken values from --help option - it's work. Do I need registrade personal pair?
