### ISSUE TITLE
reduce number of BP 

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5803]
how to reduce number of BP when all bp is produce block in turn?

**Comment by csquan** [comment]
the number of 21 is in default,I have chage to 5 and my number 0f BP is 5 ,now I want to reduce to 2 ,how to do this?

**Comment by jgiszczak** [comment]
Use `cleos system unregprod` to unregister the producer accounts you no longer want producing, then redistribute votes so that the remaining producer accounts have enough to continue the network.

**Comment by csquan** [comment]
yes,as you say,I had done this,but there is still a time gap when should produce block by which node have stop.

**Comment by jgiszczak** [comment]
Enough nodes need to be producing when unregprod happens for the new schedule to take affect.  If you started by shutting off nodes, your LIB has stopped advancing and will not continue until you restart some producers to take the missing slots long enough to advance the LIB until the new schedule is incorporated into the chain.  If you no longer have the private keys for those accounts, your chain is unrecoverable.
