### ISSUE TITLE
mongo config

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5804]
I have set 
mongodb-filter-on = *
mongodb-filter-out = eosio:onblock: in my config.ini ,but I can still get onblock data in mongdb,why does this happened?

**Comment by csquan** [comment]
none？

**Comment by csquan** [comment]
my eos version is 1.2.5,can anyone answer this?

**Comment by csquan** [comment]
still none？

**Comment by jgiszczak** [comment]
If you wish to filter out all onblock actions, you may upgrade to 1.3.0 and use `mongodb-filter-out = :onblock:`.  Note that filters only apply to `action_traces`.
