### ISSUE TITLE
mongo_db_plugin needs to respect transaction status in irreversible blocks

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#5806]
In `_process_irreversible_block()`, the plugin does not look up the transaction status in each transaction receipt. As a result, there's no indication if a transaction fails at BP signing.

Example: block 8972110, the first two transactions have status `hard_fail`, but previously they were delivered and processed by `_process_applied_transaction()`, so they look like totally valid transfers (except that global action sequence is the same number for both).

So, `_process_irreversible_block()` should update existing documents and mark the status or delete failed documents.

See also:  https://github.com/cc32d9/eos_zmq_plugin/commit/d9ad18d9dbcf9678f1155f14c4dedc99a1c71d32

**Comment by heifner** [comment]
You should not have this problem if you run with `read-mode = read-only`

**Comment by cc32d9** [comment]
I don't think it would help. At the moment I'm synchronizing a node with my ZMQ plugin. It does the verification on `trace->producer_block_id.valid()` like in Mongo plugin, and this machine has one p2p peer to a nearby node, and I never pushed transactions to it.

At the moment it's still re-syncing , and it's at `2018-09-19 13:14:23`, and it delivered 1224 transactions which were then marked as failed in subsequent irreversible blocks. 

The same thing happens if I re-play the blockchain from a local blocks archive.

the node is not configured with read-only mode. I can add it now and see if the number of such transactions increases.

**Comment by cc32d9** [comment]
ah, sorry, I just read the full description of read-only mode. If it only delivers irreversible blocks, then it definitely solves the issue. Probably the mongodb plugin should check if this option is enabled?

**Comment by heifner** [comment]
`read-only` does NOT only deliver irreversible blocks. It delivers signed blocks (before they become irreversible). 

If you run any mode except `read-only` then you speculative execute (and deliver to plugin) p2p transactions. Even if you don't send any transactions directly to the node.

If you check `trace->producer_block_id.valid()` then you should not process any speculative transaction traces. You are seeing this with the `trace->producer_block_id.valid()` ?

**Comment by cc32d9** [comment]
yes, I'm seeing this with 
```
    void on_applied_transaction( const transaction_trace_ptr& trace )
    {
      // see a long comment in mongo_db_plugin.cpp for applied_transaction()
      if( !trace->producer_block_id.valid() ) {
        return;
      }
```

also I see it in replay-blockchain mode

**Comment by heifner** [comment]
What is the value of your `producer_block_id` for those in block_num 8972110?

**Comment by cc32d9** [comment]
```
eosio@eosnode:~$ cleos get block 8972110 | head -30
{
  "timestamp": "2018-08-01T23:42:52.000",
  "producer": "eoscanadacom",
  "confirmed": 0,
  "previous": "0088e74dea0a4e4e8883ad54bcc0e44908d24ec465c17ef79e7109e25d78a70d",
  "transaction_mroot": "13a1b4957c7d8d09d4df285a585882f54bf79265e2c55449c402424ac2595dfe",
  "action_mroot": "90acc8ba680042dcb29fab82e6e286b1af7d9df26f1ea4331d03cedbb57cf442",
  "schedule_version": 255,
  "new_producers": null,
  "header_extensions": [],
  "producer_signature": "SIG_K1_K8zSiHw6fjZBJ7WaZK71CC4QQAWViqLnwxfLaxEFNoBy6hfE34QvZEA6cN7FowfQDFFPKxEZhsAV2n4nCnSCPkKWrtCNWt",
  "transactions": [{
      "status": "hard_fail",
      "cpu_usage_us": 0,
      "net_usage_words": 0,
      "trx": "4e5d4fcef0f7a5cc00350b107e4a9387541a0e0335179dac06870ac274302152"
    },{
      "status": "hard_fail",
      "cpu_usage_us": 0,
      "net_usage_words": 0,
      "trx": "f2720351ddee5e9734368643b14d8e81faf99e3dcf5f9df8e08dd7e303cbdfd5"
    },{
      "status": "executed",
      "cpu_usage_us": 534,
      "net_usage_words": 13,
      "trx": {
        "id": "18f7f2de67e8e0f099a06ca30ff0e2e9e0b288d9209e3ba5f1438fb7b5b2d147",
        "signatures": [
          "SIG_K1_Ki6iWfHD19ZmrFkLfyJATrPchGEP8EAJiUiyGjh1B8zaDCrGyVvu2Q8iCCRv16yEUNEcKXvvQNwNi7kdJB6QQ2y52hjWJK"
        ],
```
in "previous" I see the block ID from your pastebin. And as you see, the transactions are marked as failed, and your mongodb has them as happening. This is exactly what I described

**Comment by heifner** [comment]
The pastebin I show has them all as:
  "trx_status" : "hard_fail"

**Comment by cc32d9** [comment]
yes, but it still has `"global_sequence" : 144602772,` and that violates a unique index, because this global sequence belong to a different transaction that was executed successfully.

**Comment by heifner** [comment]
global_sequence should not be a unique index. You can get duplicates for hard_fail as we see here. [producer_block_id, trx_id, receipt.global_sequence] would be unique assuming producer_block_id is valid if you really want an index which includes global_requence.
