### ISSUE TITLE
Java RPC create token error

### ISSUE THREAD

**Issue by eggoa** [EOSIO/eos#5807]
Hi, all

I use commond create token is ok, but use java rpc error, the parameter is issuer and maximum_supply ?
I have signed with private key, and other actions are ok.
Why that?  thx

Error:
Exception Details: 3090003 unsatisfied_authorization: Provided keys, permissions, and delays do not satisfy declared authorizations
transaction declares authority '{"actor":"tokener","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], and provided keys ["EOS7Ln9tQDUKjbvktvkuWgJt5mQNyCwVKyXwf1QcKtmAFZLG6feqz"]
    {"auth":{"actor":"tokener","permission":"active"},"provided_delay":0,"provided_permissions":[],"provided_keys":["EOS7Ln9tQDUKjbvktvkuWgJt5mQNyCwVKyXwf1QcKtmAFZLG6feqz"],"delay_max_limit_ms":3888000000}
    thread-0  authorization_manager.cpp:411 check_authorization

**Comment by jgiszczak** [comment]
What is the JSON of the transaction generated by your Java code?

**Comment by eggoa** [comment]
@jgiszczak

**Comment by eggoa** [comment]
@jgiszczak 

How do you use eos rpc ?
