### ISSUE TITLE
multi_index::get and multi_index::find in the multi_index::modify

### ISSUE THREAD

**Issue by dwucsm** [EOSIO/eos#5810]
why?

`#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>
using namespace eosio;

class hello : public eosio::contract {
  public:
      hello(account_name self): eosio::contract(self), dl(_self, _self) {}
      //using contract::contract;

      //@abi action 
      void hi(account_name user) {
         print("Hello, ", name{user}, " ");
      }

      //@abi action
      void in(uint32_t dat) {
         dl.emplace(_self, [&](auto& obj) {
            obj.id = dl.available_primary_key();
            obj.value = dat;
         });
      }

      //@abi action
      void add1(uint32_t id) {
         auto it = dl.get(id);
         dl.modify(it, 0, [&](auto& obj) {
            obj.value += 1;
         });
      }

      //@abi action
      void add2(uint32_t id) {
         auto it = dl.find(id);
         dl.modify(it, 0, [&](auto& obj) {
            obj.value += 1;
         });
      }

      //@abi table mydata i64
      struct mydata {
         uint32_t id;
         uint32_t value;

         uint32_t primary_key() const { return id; }
         EOSLIB_SERIALIZE(mydata, (id)(value))
      };

      typedef eosio::multi_index<N(mydata), mydata> mydata_index;
      mydata_index dl;
};

EOSIO_ABI( hello, (hi)(in)(add1)(add2)) `

cleos push action myacnt in '["5"]' -p myacnt@active
cleos get table myacnt myacnt mydata
cleos push action myacnt add1 '["0"]' -p myacnt@active  ×
cleos push action myacnt add2 '["0"]' -p myacnt@active  √

add1 assertion failure

**Comment by firesWu** [comment]
```
void add1(uint32_t id) {
     const auto& it = dl.get(id);
     dl.modify(it, 0, [&](auto& obj) {
        obj.value += 1;
     });
  }
```

**Comment by jgiszczak** [comment]
For help debugging your contracts, post to [https://eosio.stackexchange.com/](https://eosio.stackexchange.com/).  This issue tracker is for the core code.
