### ISSUE TITLE
possibility to use filter-on with *:transfer:

### ISSUE THREAD

**Issue by ajose01** [EOSIO/eos#5812]
For devs running wallet type dApps where user account history across multiple tokens is important, running a node with the mongo plugin is important.

However the amount of data / time / space it takes to sync a full node is growing... see #5797 .

Would it be possible to implement a filter that allows a wildcard receiver? Something like:

`filter-on: *:transfer:`

This would limit the amount of data a node needs to write to the db for transfer history, which is what most wallet type dApps are after.

**Comment by jgiszczak** [comment]
The Mongo plugin has provided this feature since 1.3.0.  See PR #5670 for details.

The syntax is `filter-on = :transfer:` or `filter-on = 0:transfer:0`.

**Comment by sensay-nelson** [comment]
This is an excellent question @ajose01, thank you for asking it.  For the life of me I can not find a simple list of filters with even a light dictionary of what is behind each filter.  This is very helpful.
