### ISSUE TITLE
Three days after I undelegatebw, why can't tokens be redeemed automatically? I also need to make a manual refund action

### ISSUE THREAD

**Issue by yhc166188** [EOSIO/eos#5815]
after the 3 days of undelegatebw,I needn't explicitly push refund action,Token is automatically sent to my account.How do I want this scenario to be implemented

**Comment by yhc166188** [comment]
> you can send an deferred_transaction in you contract.
> 
> ```
> eosio::transaction out;
> out.actions.emplace_back( permission_level{ account, N(active) }, _self, N(action_name)
>     , std::make_tuple(arg1,arg2) );
> out.delay_sec = delay_sec;
> out.send(sender_id, _self, false);
> ```

I tried it and it still doesn't work.why?

**Comment by firesWu** [comment]
Can you post your code?

**Comment by yhc166188** [comment]
> Can you post your code?

I use the latest eos code,You can have a look

**Comment by yhc166188** [comment]
> 也许缺乏资源，所以退款行动执行失败。
> deferred_transaction（三天后退款执行）在执行时消耗cpu和net，所以你应该保证足够的资源。

I can make sure that I have enough resources, and I can do the manual refund action

**Comment by yhc166188** [comment]
Is it all the hand-operated refund action

**Comment by taokayan** [comment]
Did you do another undelegatebw in the middle?

**Comment by jgiszczak** [comment]
The automatically generated deferred transaction generated by an `undelegatebw` instruction frequently fails on mainnet.  It could be that it would be more reliable with a longer expiration time, but this would require all mainnet producers to vote in a new system contract.  Unless and until that happens, use the manual refund workaround.
