### ISSUE TITLE
there are two items find by one trx_id in action_traces

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eos#5817]
![screen shot 2018-09-26 at 12 15 29 pm 2](https://user-images.githubusercontent.com/16130147/46057020-1496b680-c186-11e8-8fd1-755cf965d9c8.png)

**Comment by taokayan** [comment]
Looks like I've seen this before. What's the full name of your first column?

**Comment by taokayan** [comment]
This is likely because of the same transaction is executed again after switching forks. Please ask in eosio.stackexchange.com if you have further questions.
