### ISSUE TITLE
get_actions  error in version  v1.3.0

### ISSUE THREAD

**Issue by liyanhrxy** [EOSIO/eos#5818]
when I call the rpc method`get_actions` ,it returns me an error  in version v1.3.0  which  all going well in version v1.2.5. Is it a bug ??? ,  Tell me what's going wrong , Please ???

**Comment by SpadeRoy** [comment]
what's error

**Comment by liyanhrxy** [comment]
`2018-09-25T10:14:26.566 thread-0   history_plugin.cpp:371        get_actions          ] params: {"account_name":"xxxxxx","pos":1,"offset":2}
2018-09-25T10:14:26.566 thread-0   history_plugin.cpp:383        get_actions          ] pos: 1
2018-09-25T10:14:26.566 thread-0   history_plugin.cpp:407        get_actions          ] start: 1 end: 3
2018-09-25T10:14:26.566 thread-0   http_plugin.cpp:580           handle_exception     ] FC Exception encountered while processing history.get_actions
2018-09-25T10:14:26.566 thread-0   http_plugin.cpp:581           handle_exception     ] Exception Details: 10 assert_exception: Assert Exception
(b & ~1) == 0:
    {}
    thread-0  raw.hpp:339 unpack
Error unpacking field context_free
    {"field":"context_free"}
    thread-0  raw.hpp:368 operator()
error unpacking eosio::chain::action_trace
    {"type":"eosio::chain::action_trace"}
    thread-0  raw.hpp:616 unpack`

**Comment by taokayan** [comment]
hi @heifner , looks like the new field ```context_free``` in ```struct base_action_trace``` has broken the old data in de-serialization. would you help?

**Comment by taokayan** [comment]
```--hard-reply``` will solve this issue.

**Comment by liyanhrxy** [comment]
> `--hard-reply` will solve this issue.

Even if this  solve this issue ,but the efficiency is too low .It will take me some days to fish this.  Comparing with  reloading  the blocks data, it has no any superiority. Is there another way ??

**Comment by pete001** [comment]
Seeing this across many nodes too. Might need to think about informing the wider BP community about this, as its affecting quite a few apps, especially those that rely on history.

**Comment by quarksgluons** [comment]
Same error, too.

**Comment by hmilymb** [comment]
same error too

**Comment by liyanhrxy** [comment]
> same error too ,how to fixed

--hard-reply  will solve this issue

**Comment by pete001** [comment]
I can now confirm that a full `--hard-replay` from version 1.3.0+ fixes this.
