### ISSUE TITLE
I want to do reward distribution of block producers each day

### ISSUE THREAD

**Issue by yashvadhvani** [EOSIO/eos#5821]
this is an issue I want to have reward distribution every day is it possible?

**Comment by jgiszczak** [comment]
The system contract included in the `eos` repository allows `claim rewards` every 24 hours.  In `producer_pay.cpp`:
```C++
eosio_assert( ct - prod.last_claim_time > useconds_per_day, "already claimed rewards within past day" );
```
If current time minus last claim time (in microseconds) is greater than the number of microseconds in a day, claim processing will proceed.  If you want reward distribution more frequently, modify that file, recompile your system contract, and upload it to your chain.
