### ISSUE TITLE
Error 3160005: The table operation is not allowed

### ISSUE THREAD

**Issue by Midcc** [EOSIO/eos#5822]
After adding a new field to my table, I delete the old data, retype the contract, get the index again, and traverse the index, and an error is reported：
Error 3160005: The table operation is not allowed

 http_plugin.cpp:473           handle_exception     ] Exception Details: 3160005 table_operation_not_permitted: The table operation is not allowed
dereference of end iterator
    {}
    thread-0  apply_context.hpp:64 get
pending console output: 
    {"console":""}
    thread-0  apply_context.cpp:61 exec_one

**Comment by Midcc** [comment]
Does deleting all items mean deleting all data?

**Comment by Midcc** [comment]
Does deleting all items mean deleting all data?

**Comment by Midcc** [comment]
Does deleting all items mean deleting all data?
Previous action: roll back the old version, delete the data, install the new struct, and the index fetch will report an error

**Comment by taokayan** [comment]
The correct steps is to roll back to your old structure, and then delete all your data, and then apply your new structure, and then insert your new data. Please ask in eosio.stackexchange.com if you have further questions.
