### ISSUE TITLE
why fork?

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5836]
my log show
"2018-09-26T16:23:42.038 thread-0   controller.cpp:1064           maybe_switch_forks   ] switching forks from 00034610b904b3a7a67520c6bf09a2186d69a374199f68c66ec2da5de8eaa68f (block number 214544) to 00034610d1bc50ddfa34731605211041079d17706f10be0ede8920a3495abcbb (block number 214544)"
how does this happened?

**Comment by jgiszczak** [comment]
In a network functioning normally switching forks is typically induced by network delays around the time the current producer is changing.  The current producer is late in transmitting the last block of its series and the next producer has already produced the same block number.  This results in two different blocks arriving from the network with head block IDs that conflict.  This typically results in the late block being dropped and the other block being incorporated into the chain.

**Comment by jgiszczak** [comment]
Transaction failures are unrelated to forks.
