### ISSUE TITLE
Transaction's reference block did not match. Is this transaction from a different fork?

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#5837]
when I push tx,I got log
"Transaction's reference block did not match. Is this transaction from a different fork?"

**Comment by firesWu** [comment]
Did you set correct block_num and block_prefix?

**Comment by csquan** [comment]
how set?my client just get_info of eos and set block_num and block_prefix.

**Comment by firesWu** [comment]
you should get block_num and block_prefix from blockchain which you want to push trx.  
you can through `get_block` check block_num and block_prefix.

**Comment by jgiszczak** [comment]
Calling `get_info` is not sufficient.  You must incorporate the results you received from `get_info` into the transaction you are composing.

If you are using eosjs, there are Github issues describing this process.
