### ISSUE TITLE
v1.3.0-dirty ?

### ISSUE THREAD

**Issue by AllenYaoya** [EOSIO/eos#5840]
Hi
 I manually downloaded and compiled the source code.  But when i done it, i get the nodeos with version : v1.3.0-dirty.  I just follow the official instrument.
```
git clone https://github.com/EOSIO/eos --recursive

cd eos
./eosio_build.sh

./eosio_install.sh
```
could someone help me to figure out why this happen?

thanks,

**Comment by spoonincode** [comment]
What does a `git status` show?

**Comment by taokayan** [comment]
can you try to checkout branch ```release/1.3.x```?

**Comment by AllenYaoya** [comment]
hi 

i work on the aws, and cat /etc/os-release shows below,
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
But the auto-build script need the NAME="Amazon Linux AMI" to run. So i manually revised the eos/eosio_build.sh and eos/scripts/eosio_build_amazon.sh to make the script run for NAME = "Amazon Linux". 

Seems due to the difference exists in the git status. Then i get a dirty version after compiling. So in my case, what should i do to make the auto-build script run successful?

thanks!

**Comment by AllenYaoya** [comment]
> What does a `git status` show?
hi,
i manually revised a couple of build scripts. git diff shows the difference.

**Comment by spoonincode** [comment]
Yes, if you edit any files that git is aware of the build will be marked dirty.

**Comment by spoonincode** [comment]
Amazon Linux 2 added to build script; closing
