### ISSUE TITLE
How can I save nodeos running log in local use option -l?

### ISSUE THREAD

**Issue by yaanhyy** [EOSIO/eos#5846]
I can not find enough info to config nodeos to save running log in local file not only in stdout.

**Comment by spoonincode** [comment]
There is no built in ability to log to a file -- this functionality is disabled and broken (#2377). You will just have to redirect the output via your shell (`/nodeos &> log.txt`), or use journalctl if nodeos is launched by systemd. Going to go ahead and close this one as file logging being broken is already captured in #2377
