### ISSUE TITLE
Very less throughput

### ISSUE THREAD

**Issue by sivachaitanya** [EOSIO/eos#5847]
I have setup a 3 node private EOS network where 2 are running on Azure (8vCPU, 16GB ram) and 1 on my machine (8CPU, 32 GB ram), the smart contract is simple multi index which stores the values sent to in the table and I am using the following script to send txns - 

#!/bin/bash

for (( c=1; c<=10000; c++ ))
do  
   uname=`gpw 1 8`
   #cleos create account eosio $uname EOS7Riw4uGqGy8BqT2GRLvCmiEKjvD8yMXQ6c4HoPAFXYRpT6PPsC EOS6e7BkZwtrVMGjyRyJWPnpyrQmhzHChZkRgdjaCePDGLV8SCBVm
    cleos push action testr push '["'$uname'","testr","460900,1436, NA , NA ,12/1/2014 0:33:00,12/1/2014 0:36:00,47,47,0,0,12/30/1899 0:00:00"]' -p testr
done

Although the txns are submitted locally on the azure vm, I can on an average per block roughly 3-8 txns are added which very less throughput. How can I tune the performance to pack more txns in the block ?

**Comment by spoonincode** [comment]
Using cleos in a loop like that is very inefficient. It has a non trivial start up cost and it will perform a few operations on each invocation that could have just been cached once. You might have to write your own RPC client to obtain high performance. You might also consider using multiple scripts running simultaneously instead of a single script doing 1 to 10000.

**Comment by taokayan** [comment]
you may also need to run a validating node to save the serialization time.

**Comment by sivachaitanya** [comment]
@spoonincode @taokayan  I am running 3 full nodes, can you let me know how to run a validating node ?

**Comment by sivachaitanya** [comment]
@sergmetelin @spoonincode @taokayan As suggested I have created the cleos calls in the EOSJS but there is no improvement in the performance, actually it went bad where the throughput was 10 txns/sec, - 

var fs = require('fs')
    , es = require('event-stream');
let Eos = require('eosjs')
var lineNr = 0;
const util = require('util')

const config = {
    expireInSeconds: 60,
    broadcast: true,
    debug: false,
    sign: true,
    // mainNet bp endpoint
    httpEndpoint: 'http://127.0.0.1:8888',
    // mainNet chainId
    chainId: 'cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f',
    keyProvider: ['5JZntapnrfnBLR9Qj7BWGRwKKgdWdQHxxXVCddt63Awu59mxNmz']
};
var lineNr = 0;
var uname;
const eos = Eos(config);
eos.contract('testr').then((contract) => {

    var s = fs.createReadStream('D11.txt')
        .pipe(es.split())
        .pipe(es.mapSync(function (line) {

            // pause the readstream
            s.pause();
            uname = makeid(7);
            contract.push(uname, "testr", line.toString(), { authorization: ['testr'] }).then((res) => {
                console.log('-----Executed transaction id (locally) - ' + res.transaction_id + ', File 1 index -' + lineNr + ' -----')
                lineNr = lineNr + 1;
                s.resume();
            }).catch('error', function (er) {
                console.log('****Error during transaction execution - ' + util.inspect(er))
            })

            // resume the readstream, possibly from a callback
            
        })
            .on('error', function (err) {
                console.log('Error while reading file.', err);
            })
            .on('end', function () {
                console.log('Read entire file.')
            })
        );

})

function makeid(l) {
    var text = "";
    var char_list = "abcdefghijklmnopqrstuvwxyz1235";
    for (var i = 0; i < l; i++) {
        text += char_list.charAt(Math.floor(Math.random() * char_list.length));
    }
    return text;
}

**Comment by sivachaitanya** [comment]
@spoonincode @taokayan  I was able to achieve around 400 TPS with a single node running on my local machine (8CPU, 32 GB RAM, Ubuntu 16.04) when I spin up 50 threads in the JMeter, but if I connect the remaining 2 nodes on the Azure then the perofrmance comes down to nearly 150-200 TPS. Do you have any hacks to change the underlying cleos code to observe 1000 TPS  like in this (https://gist.github.com/spoonincode/fca5658326837b76fd744d39b2a25b4e) post ?

**Comment by sivachaitanya** [comment]
@spoonincode  Also I found out that if I submit the transactions to local node the throughput is 200 TPS but if I submit it to a remote BP node on the azure machine then it comes down to 10-20 TPS ?

**Comment by spoonincode** [comment]
>@spoonincode Also I found out that if I submit the transactions to local node the throughput is 200 TPS but if I submit it to a remote BP node on the azure machine then it comes down to 10-20 TPS ?

When you perform an action with cleos it makes at least 3 HTTP calls in a ping-pong manner. This means even if you have something like a 10ms RTT from cleos to the HTTP endpoint you're going to burn over 30ms of overhead for a single action.

**Comment by sivachaitanya** [comment]
@spoonincode  As you can see from the above javascript code, I am using it to send transactions (remote or local BP node) the TPS fell to 10-20 TPS atleast the with cleos I am able to achieve 150-200 TPS while submitting to local BP node. Can you suggest which is the best approach I should follow to achieve the throughput you have achieved in this video (https://gist.github.com/spoonincode/fca5658326837b76fd744d39b2a25b4e)?

**Comment by taokayan** [comment]
A better approach is to run a local node connecting to the mainnet. Then you can spawn multiple thread to push transactions into your local node.

**Comment by sivachaitanya** [comment]
@taokayan I was following the same approach, I am submitting the transactions to the local node which are connected to 2 Azure nodes. But here I am trying with a private testnet of EOS instead of connecting to public mainnet.

**Comment by taokayan** [comment]
You can investigate which part is your bottleneck. But I guess the latency will be too big from your server to Azure. For example, if your round trip latency is 200ms, you won't be able to send even 1 transaction per second per thread due to TCP & HTTP overhead.

**Comment by sivachaitanya** [comment]
@taokayan  in the nodeos logs the latency for block shows as 178-200 ms, where block latency between 2 azure nodes is 20-30 ms ?

**Comment by spoonincode** [comment]
@sivachaitanya you may need to describe your environment in better detail again. It's not clear any more what nodes are where and where you are pushing transactions from.

**Comment by sivachaitanya** [comment]
@spoonincode  - Matt, I am using 3 node setup. 2 nodes are on Azure (8vCPU,16GB RAM) and 1 local machine (8CPU,32GB RAM). I started the genesis node on Azure to which another Azure node and my local machine connects. I am using the following commands to start the nodes - 

Genesis node on Azure - nohup nodeos --enable-stale-production -p eosio -l logging.json  --plugin eosio::chain_api_plugin --plugin eosio::net_api_plugin --p2p-listen-endpoint  10.0.18.4:9876 &

Node2 on Azure - nohup nodeos -l logging.json --plugin eosio::chain_api_plugin --plugin eosio::net_api_plugin --p2p-listen-endpoint 10.0.19.4:9876 --p2p-peer-address <Genesis node public ip address>:9876 &

Node3 on Azure - nohup nodeos -l logging.json   --plugin eosio::chain_api_plugin --plugin eosio::net_api_plugin --plugin eosio::history_api_plugin --p2p-listen-endpoint  0.0.0.0:9876 --p2p-peer-address <Genesis node public ip address>:9876 &

and then I have create a key pair and associated it with an account called testr. I have set my test contract which is having multiindex table to store values which are pushed from cleos.  I am pushing transactions using JMeter to local node which is node3 using the following cleos command -

#! /bin/bash
uname=`gpw 1 8`
cleos push action testr push '["'$uname'","testr","4601,1436, NA , NA ,12/1/2014 0:33:00,12/1/2014 0:36:00,47,47,0,0,12/30/1899 0:00:00"]' -p testr

I have setup 100 threads on JMeter which uses the above script to send transactions to the local node, for which I am getting around 220-250TPS. If I submit the transactions to genesis node or node 2 then the TPS drops to 10-20. I have tried using the EOSJS as suggested in the earlier comments in post but even with that its 10-20 TPS.

**Comment by sivachaitanya** [comment]
![eosjs_100threads](https://user-images.githubusercontent.com/6172334/46515918-57dade80-c884-11e8-9aee-4aa1383f068d.png)

The above is the JMeter screenshot for 100 threads sendign transactions using eosjs which is giving 8 TPS throughput. Also out of 2449 samples send from JMeter only 1440 of them appears to have been inserted in the blockchain ?

**Comment by sivachaitanya** [comment]
@spoonincode  I tried the same test described in benchmarking with the 3 node network setup and observed that 500-600 TPS on average as shown in the below image, Can you please help me achieve the same TPS it would be great, like if you can share how the tx generator plugin is sending transaction or point me to documentation where is it implemented, I will try to use the same functionality to send transactions - 

![benchmarking_test](https://user-images.githubusercontent.com/6172334/46516682-b4d89380-c888-11e8-8517-2262ed0cb3f9.png)

**Comment by jgiszczak** [comment]
Very high transaction throughput from a single node is achieved by using a plugin linked directly into `nodeos`, which avoids the (ridiculous) expense of JSON marshalling and unmarshalling as well as eliminating all network overhead.  Usage of the public-facing interfaces and APIs will never achieve similar throughput through a single node.

To achieve a very high transaction rate using the available APIs, you'll need to run a cluster of connected `nodeos` processes.  Submit your transactions to each of 5 or 6 local `nodeos` processes and you will be able to achieve the desired transaction rate.  Of course you will need to parallelize transaction submission to avoid duplicates.

To achieve a very high transaction rate using a single node, write a custom plugin that can read the transaction data in some machine-friendly format and compose your transactions directly in C++.  You may imitate the `txn_test_gen_plugin` to get started.
