### ISSUE TITLE
Eos balance

### ISSUE THREAD

**Issue by liderako** [EOSIO/eos#585]
Whether it is possible through smart contracts to send еос_balance. If so, then how?
How to make transfer between two accounts without calling "./eosc transfer one_account_name two_account_name? What сlass or functions should I use? Could you tell me?

**Comment by jgiszczak** [comment]
Smart contracts can invoke transfers of any token on the chain.  See for example the `exchange` contract included in the source, which may be deployed according to this documentation: https://github.com/EOSIO/eos/wiki/Tutorial-eosio-token-Contract
