### ISSUE TITLE
compile error in eos-dev docker

### ISSUE THREAD

**Issue by jacktang** [EOSIO/eos#5850]
Hello, my contract is compile well out of docker container. And I try to deploy in eos-dev container, and failed:

```
$ docker exec -it eosio /bin/bash -c 'eosiocpp -o xxx.contracts/xxx.wast xxx.contracts/xxx.cpp && eosiocpp -g xxx.contracts/xxx.abi xxx.contracts/xxx.cpp'
xxx.contracts/xxx.cpp:7:10: fatal error: 'eosio.token/eosio.token.hpp' file not found
#include <eosio.token/eosio.token.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
error Command failed with exit code 1.
```

How can I fix the head file include error? Thanks

**Comment by taokayan** [comment]
I think ```eosio.token/eosio.token.hpp``` is not in the default include path. You can copy eosio.token/eosio.token.hpp into your source code folder and then use ```#include "eosio.token.hpp"``` in your cpp file.

**Comment by jgiszczak** [comment]
Consider transitioning to eosio.cdt, which is available as pre-built binary packages.  `eosiocpp` is deprecated and will be removed in a future release.  Otherwise you may follow Kayan's advice, or add the eosio.token include path to the command line with `-I`.
