### ISSUE TITLE
Get transaction detail in smart contract

### ISSUE THREAD

**Issue by KunkaYU** [EOSIO/eos#5856]
Hello,I am building a dapp.  Inside the contract I get a trxid(parameter) from user. I want to see the detail of this transaction. How can I do that ?

**Comment by jgiszczak** [comment]
There is no API to retrieve transaction details directly from the chain in a smart contract.  Only state modified by transactions can be retrieved.  If a transaction makes no state changes, nothing of it can be retrieved within a contract.
