### ISSUE TITLE
Create Account through RPC API

### ISSUE THREAD

**Issue by srmcatee1110** [EOSIO/eos#5861]
I understand cleos simplifies quite a bit.  After learning cleos I am now trying to rewrite my script in Python and call the RPC API and create an account against my private EOS network.

What smart contract creates accounts?  I've looked at eosio.system and do not see the action that would create an account.  Which smart contract handles account creation?

**Comment by tbfleming** [comment]
nodeos handles some actions to the eosio account and the system contract handles others. Use cleos -j to see the set of actions needed to create an account.

**Comment by wuyahuang** [comment]
try to add `http-validate-host = false` to config.ini

**Comment by wuyahuang** [comment]
https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/eosio.system.cpp#L146

**Comment by srmcatee1110** [comment]
@tbfleming the cleos -j just returns the resulting json.  I want to know what the json payload into the transaction is.  And what transaction.

**Comment by srmcatee1110** [comment]
@wuyahuang Line 146 is called after the account is created to enforce resource limits.  Or is this the code that enters the account into the account table?  I am still not how to form the json for this call..

**Comment by conr2d** [comment]
This can help you. `signupeoseos` is a contract which creates an account by transferring necessary EOS and information. (Information is given by `memo` in the format of "account_name-public_key")
https://github.com/Dappub/signupeoseos/blob/b9a0c656148f5dbde0667d0286a5de1d6c7a1b6f/signupeoseos.cpp#L83

**Comment by srmcatee1110** [comment]
Hey Everyone.  Thank you for the great responses.  However not sure it is answerming my question.  I'm trying to call the web service from python and create an account.  For example:

`url = "http://172.17.0.2:8888/v1/chain/"
surl="push_transaction"
payload="{\"body\":\"xxxx\"}"
response = requests.request("POST", url + surl, data=payload)
print(response.text)`

What do I put in the body for xxxx?
Would it be this--

`{creator: 'existingaccount', name: 'newaccountName', owner: pubkey, active: pubkey}`

**Comment by tbfleming** [comment]
`push_transaction` needs a packed (binary) and signed transaction. Those are both major topic areas. See `eosjs2` sources for an example of how to do it.

**Comment by srmcatee1110** [comment]
Thanks.

I think will do the trick.
