### ISSUE TITLE
How to enumerate scopes in a table

### ISSUE THREAD

**Issue by yukozh** [EOSIO/eos#5870]
How to enumerate scopes in a table? I want to enumerate the token holders, I want to do something like enumerating the currency table scopes to know who holds my token.

**Comment by codereba** [comment]
abi file can help.maybe.

**Comment by yukozh** [comment]
@codereba No, it won't. abi only show you tables, not scopes.

**Comment by taokayan** [comment]
Please refer to https://github.com/EOSIO/eos/pull/5486
