### ISSUE TITLE
make test filling up /tmp

### ISSUE THREAD

**Issue by NorseGaud** [EOSIO/eos#5876]
Hello, I'm still learning (slowly), and can't figure out how to change the tmp storage location for `make test`I've got a really locked down /tmp directory for security reasons and want to be able to use a different location. Any suggestions?

**Comment by taokayan** [comment]
What's the size of your storage?

**Comment by jgiszczak** [comment]
The tests managed by ctest can be run elsewhere by running `TMPDIR=/some/place/executable ctest` in your `eos/build` directory.  The python-driven tests don't attempt to execute anything from /tmp.

**Comment by NorseGaud** [comment]
Hmm, interesting. I tried setting TMPDIR before running it. I'll try it again tonight and keep ya posted. Thanks!

**Comment by NorseGaud** [comment]
It's working now. Not sure what happened. Thanks!
