### ISSUE TITLE
 How to monitor new block in real time

### ISSUE THREAD

**Issue by eggoa** [EOSIO/eos#5879]
Hi all,

I want to monitor the latest blocks or action information in real time.

How to this？

**Comment by taokayan** [comment]
You can do this by writing a new plugin or modifying some existing plugin (mongo_plugin, history_plugin for example). Make sure you're connecting to the accepted_block signal of the chain:
```
         my->accepted_block_connection.emplace( chain.accepted_block.connect( [&]( const chain::block_state_ptr& bs ) {
            my->accepted_block( bs );
         } ));
```

**Comment by eggoa** [comment]
Okay, thank you.
