### ISSUE TITLE
How to setup mainnet account 

### ISSUE THREAD

**Issue by GeekPrasad** [EOSIO/eos#5883]
I am using docker for EOSIO and able to create tokens using testnet but now I want to setup mainnet.
Any idea or steps to setup EOS mainnet?

Thanks in advance.

**Comment by tmclane** [comment]
One way to do it: 
http://zeos.co/en/home

Or

https://eos-account-creator.com/

**Comment by tmclane** [comment]
Or someone with an account can create them as well.

**Comment by GeekPrasad** [comment]
> Or someone with an account can create them as well.
Thanks tmclane!!
How to do this? I have account details.

**Comment by tmclane** [comment]
https://medium.com/@cc32d9/creating-a-new-eos-eosio-account-f88201dc1a

**Comment by tmclane** [comment]
Another one I found: https://namevault.co

I can't vouch for any of these except that I used the zeos.co myself.

**Comment by tmclane** [comment]
Actually getting a local node talking to mainnet: https://hackernoon.com/getting-started-on-eos-mainnet-in-10-minutes-bf61dd9ec787

**Comment by taokayan** [comment]
You need to ask someone or some service provider to help you create EOS account on mainnet. There's no way to create EOS account without the help of an existing EOS account.

**Comment by GeekPrasad** [comment]
ok Thanks

**Comment by GeekPrasad** [comment]
I created by using following command:
cleos --wallet-url "nodeos container" -u "mainnet link" wallet list
