### ISSUE TITLE
what is the return type of find in multi_index class

### ISSUE THREAD

**Issue by god2g** [EOSIO/eos#5884]
I know i can use auto to receive the return type of find method, but i want to define a member variable to receive the result of find. Which type of the member variable i should use?

**Comment by jgiszczak** [comment]
It's different for every index you define.  The base type is `multi_index::index::const_iterator`, but the template arguments will differ.  `auto` was invented for a reason.  If you're foolishly determined to get the real type, try:
```C++
#include <typeinfo>

...
auto i = your_multi_index.find(something);
print(typeid(i).name());
```
where the lines after `...` are appropriately inserted into your contract where your_multi_index can be found in scope.  You'll need to enable contracts-console in nodeos to see the result.
