### ISSUE TITLE
Eosio v1.3.1 test fails.

### ISSUE THREAD

**Issue by enumivo** [EOSIO/eos#5891]
The last test nodeos_under_min_avail_ram_lr_test fails.

**Comment by enumivo** [comment]
The nodes die because of this:
Database has reached an unsafe level of usage, shutting down to avoid corrupting the database.

**Comment by Alteryy** [comment]
Same error here, but I ctl+z, then make install, I have problems when starting up

```
nodeos -d /root/eosdata
2018-10-05T12:28:29.276 thread-0   main.cpp:136                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option 'required-participation'
```

**Comment by jgiszczak** [comment]
Try again with the v1.4.2 release.  Various enhancements have been made to the long running tests to improve their reliability.  If they fail again, you may simply attempt running them again.  The long running tests are time sensitive, which can lead to spurious failures on a busy machine.

**Comment by jgiszczak** [comment]
Closed as no further reply. If you still have the same problem please ask https://eosio.stackexchange.com/.
