### ISSUE TITLE
advice to reduce cpu usage?

### ISSUE THREAD

**Issue by god2g** [EOSIO/eos#5894]
is there a guide that tells that?

**Comment by spoonincode** [comment]
What CPU usage are you referring to? Billed CPU usage from a contract action?

**Comment by god2g** [comment]
> What CPU usage are you referring to? Billed CPU usage from a contract action?

Yes, that's what i mean

**Comment by yashbhavsar007** [comment]
You should post these type of questions on [eosio.stackexchange.com](url)

**Comment by jgiszczak** [comment]
I tend to agree with @yashbhavsar007.  This is an open-ended question with complex answers much more suitable for StackExchange.  The documentation team has been made aware of it, and perhaps some document will be included to address questions such as this.  Until then, StackExchange is your best bet.

**Comment by god2g** [comment]
ok，thanks
