### ISSUE TITLE
Docker instructions fail

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#590]
```
docker exec docker_eos_1 eosc get info
{
  "head_block_num": 212,
  "last_irreversible_block_num": 198,
  "head_block_id": "000000d4ec0eb4c683b6b5582eff82f45a97edc6ae6a72cdd63bd2790b931c43",
  "head_block_time": "2017-10-25T15:22:27",
  "head_block_producer": "inits",
  "recent_slots": "1111111111111111111111111111111111111111111111111111111111111111",
  "participation_rate": "1.00000000000000000"
}
```

Upload sample exchange contract

> docker exec docker_eos_1 eosc set contract exchange contracts/exchange/exchange.wast contracts/exchange/exchange.abi
Reading WAST...
Assembling WASM...
Publishing contract...
1061444ms thread-0   main.cpp:1101                 main                 ] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error
: Unknown Endpoint

    {"msg":"Unknown Endpoint"}
    thread-0  httpc.cpp:113 call

    {"server":"localhost","port":8888,"path":"/v1/wallet/get_public_keys","postdata":null}
    thread-0  httpc.cpp:117 call

**Comment by northeastsquare** [comment]
I also met this
