### ISSUE TITLE
permissioned data access

### ISSUE THREAD

**Issue by yashvadhvani** [EOSIO/eos#5900]
Is it possible to have permissioned data access? Suppose I am having a multi_index table and whoever adds data to that table only can access the data because I am having a table storage and one account named "myaccount" has added an entry but everyone else can access that data by doing cleos get table? Is there any way to change this or any other way to achieve permissioned data access?

**Comment by conr2d** [comment]
`cleos get table` doesn't check any permission to be executed. You may hide table abi from contract (cleos get table will not work) and add `read` action for permissioned access. (It would consume resources for reading data from table)

**Comment by yashvadhvani** [comment]
how exactly i can do this

**Comment by conr2d** [comment]
I've tested my method, but found that regardless of removing table abi, other contract can access table data with proper `code`, `scope`, `tablename`. Sorry for wrong information. In that case, permissioned access may not be possible. (Other contract can access by code anytime)

**Comment by conr2d** [comment]
You can't forbid people from reading your data. By removing ABI, `cleos get table` will not work, but others can deploy his own contract which have table with code, scope, tablename corresponding to yours and read table by code. Refer to the next.
https://eosio.stackexchange.com/questions/2149/can-we-add-the-permission-to-access-the-table

**Comment by yashvadhvani** [comment]
how to perform read operation without a table as you mentioned before i have done this with update add and delete

**Comment by conr2d** [comment]
There's a misunderstanding. Table is necessary, but not by exposing table abi (omitting /// @abi table blahblah),  you can disable cleos get table, but cleos only. People still can access your data by code.

**Comment by yashvadhvani** [comment]
Ok Thank you sir @conr2d

**Comment by heifner** [comment]
As pointed out, all data in tables are public.
