### ISSUE TITLE
Can I code ML code inside EOS ?

### ISSUE THREAD

**Issue by sivachaitanya** [EOSIO/eos#591]
I have a text extraction ML app working in Python. I am thinking if I could replicate the same functionality to code a smart contract  in EOS such that other smart contracts could be able to talk to ML smart contract and get the data ?

**Comment by learnforpractice** [comment]
Maybe you are looking for this:
https://github.com/learnforpractice/pyeos <https://github.com/learnforpractice/pyeos>

There is DL example in the following link:

https://github.com/learnforpractice/pyeos/tree/master/programs/pyeos/contracts/mnist <https://github.com/learnforpractice/pyeos/tree/master/programs/pyeos/contracts/mnist>


Also you should know all of this are at a very early stage.

Let me know if you need additional help.

**Comment by sivachaitanya** [comment]
Thank you @learnforpractice  that is exactly what I'm looking for, Definitely will let you know if I encounter issue :)

**Comment by timothytlewis** [comment]
This is a very exciting thread. Thank you, both.
