### ISSUE TITLE
v1.3.1 unable to start after update

### ISSUE THREAD

**Issue by Alteryy** [EOSIO/eos#5911]
# nodeos -d /root/eosdata
2018-10-05T12:28:29.276 thread-0   main.cpp:136                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option 'required-participation'
------------------------
I checked the information that there are write parameters in the config.ini file that cannot be used.
 I want to know which parameters are not available.
`nodeos -v output is v1.3.1-dirty` what does dirty mean?
Here is my config.ini:

```
# network topology, use "star" "mesh" or give a filename for custom
shape = star

# select a p2p plugin to use (either net or bnet). Defaults to net.
p2p-plugin = net

# set the path to genesis.json
genesis = "./genesis.json"

# nodeos does not require transaction signatures.
skip-signature = false

# forward nodeos command line argument(s) to each instance of nodeos, enclose arg(s) in quotes
# nodeos = 

# forward nodeos command line argument(s) (using "--specific-nodeos" flag) to this specific instance of nodeos. This parameter can be entered multiple times and requires a paired "--specific-nodeos" flag
# specific-num = 

# forward nodeos command line argument(s) to its paired specific instance of nodeos(using "--specific-num"), enclose arg(s) in quotes
# specific-nodeos = 

# seconds delay before starting each node after the first
delay = 0

# After deploying the nodes and generating a boot script, invoke it.
boot = false

# launch nodes without writing new config files
nogen = false

# a file containing mapping specific nodes to hosts. Used to enhance the custom shape argument
host-map = ""

# a file containing ip addresses and names of individual servers to deploy as producers or non-producers 
servers = ""

# specifies how many nodeos instances will run on a single host. Use 0 to indicate all on one.
per-host = 0

# network name prefix used in GELF logging source
network-name = testnet_

# enable gelf logging appender in logging configuration file
enable-gelf-logging = 1

# hostname:port or ip:port of GELF endpoint
gelf-endpoint = 10.160.11.21:12201

# the startup script template
template = testnet.template

# the generated startup script name
script = bios_boot.sh
```
------------------------

**Comment by jgiszczak** [comment]
That's your eosio-launcher config file, which is not used by nodeos.  You'll need to find the config.ini file being used by nodeos and remove the obsolete `required-participation` option.  The software will inform you of any other obsolete options.  There is no comprehensive list.

`v1.3.1-dirty` means some file in your build directory has been modified prior to the build.  This applies to any file known to git, including documentation, tests, and contracts, not just source code of nodeos itself.
