### ISSUE TITLE
Compiling different programs independently

### ISSUE THREAD

**Issue by damianoazzolini** [EOSIO/eos#5912]
Hi. I want to make some changes to `cleos`. I modify only the `main.cpp` file in the folder `/programs/cleos/` and then how can i compile it without recompiling all eos? I've tried using `g++` and include all the directories with `-I` but it is an endless job and i don't think is the smartest way to do it. Is there a better way? I have find nothing in the reference, so it will be also cool to have a brief explanation on how to contribute also to `nodeos` for example.

**Comment by jgiszczak** [comment]
Just run `make` or `make -j8` in your `build` directory.  CMake generates Makefiles which do dependency checking.  If you have modified only `programs/cleos/main.cpp`, only `cleos` will be rebuilt.

A slightly safer way of accomplishing the same thing which will also detect some changes to the build environment is `cmake --build . --target all`.  Append `-- -j8` if you wish to run a parallel build.

(Change 8 to the number of CPU cores you have available.  Some people prefer 1.5X the number of available CPU cores available.  See [the Internet](https://www.google.com/search?q=parallel+builds+make) for discussion.)
