### ISSUE TITLE
Feature Request: get table (and RPC equivalent) needs an exact key value lookup

### ISSUE THREAD

**Issue by znebby** [EOSIO/eos#5917]
Here's the problem: I want to be able to select on a particular key value, rather than within certain bounds.

I can't use bounds for this, because while the lower bound is inclusive, the upper bound is exclusive. If I'm searching on an integer index, that's not a big issue, I'll just set the upper bound to be 1 higher than the lower bound.

But, if I'm searching on an account_name index, it gets really messy. To do it properly, I would need to figure out what is exactly one greater than the account_name string I want.

To solve this, get table needs either a field to do an exact lookup, or a way to make the upper bound inclusive.

**Comment by conr2d** [comment]
`--limit (-l)` option will limit the number of rows to be shown. You can add `--limit 1` to get exact row that you want to find.

**Comment by taokayan** [comment]
You can make your upper bound like this:
- if lower bound has exactly 12 characters, append "1" at the end. for example "abcdabcdabcd" will become "abcdabcdabcd1"
- if lower bound has less than 12 characters, append one or multiple "." to make it 12 bytes long, then append "1" at the end. For example "com" will become "com.........1"
I guess this logic can make your query much easier.

**Comment by znebby** [comment]
Okay, a simple rule like that would work. Can you explain the logic of the less than 12 character example? Why the dots?

**Comment by conr2d** [comment]
account_name is encoded into 64bit integer by BASE32 encoding. dot `.` is encoded into 0. Each chunk of 5 bits is translated into a character, and name shorter than 12 character should have a series of `.` to fill remaining bits.

**Comment by taokayan** [comment]
all account names will be left-aligned. "." is encoded into zero.
