### ISSUE TITLE
cleos Push data with one of the field with spaces but works with underscore

### ISSUE THREAD

**Issue by swapnachippagi** [EOSIO/eos#5927]
When am trying to push data as content field("tweet":"sss  ddd") including spaces,it shows following error

`"push action exec blog createpost {"timestamp":1532704423,"author":bobnew1,"tweet":"sss ddd"} -p bobnew1@active " "  [31mError 3120007: Already unlocked [0m ERROR: ExtrasError: [ddd"}] Push a transaction with a single action Usage: /opt/eosio/bin/cleos push action [OPTIONS] account action data Positionals: account TEXT The account providing the contract to execute (required) action TEXT A JSON string or filename defining the action to execute on the contract (required) data TEXT The arguments to the contract (required) Options: -h,--help Print this help message and exit -x,--expiration set the time in seconds before a transaction expires, defaults to 30s -f,--force-unique force the transaction to be unique. this will consume extra bandwidth and remove any protections against accidently issuing the same transaction multiple times -s,--skip-sign Specify if unlocked wallet keys should be used to sign transaction -j,--json print result as json -d,--dont-broadcast don't broadcast transaction to the network (just print to stdout) --return-packed used in conjunction with --dont-broadcast to get the packed transaction -r,--ref-block TEXT set the reference block num or block id used for TAPOS (Transaction as Proof-of-Stake) -p,--permission TEXT ... An account and permission level to authorize, as in 'account@permission' --max-cpu-usage-ms UINT set an upper limit on the milliseconds of cpu usage budget, for the execution of the transaction (defaults to 0 which means no limit) --max-net-usage UINT set an upper limit on the net usage budget, in bytes, for the transaction (defaults to 0 which means no limit) " "null"`

**Comment by conr2d** [comment]
You should wrap arguments with single quotation marks:
```
push action ACCOUNT ACTION '{ ... }' -p ACCOUNT@active
                           ^       ^
```
Moreover, `account` and `action` only can be placed between `push action` and arguments. In your command `exec blog createpost`, there are three words before args list.

**Comment by taokayan** [comment]
can you provide screen shot instead?

**Comment by Danilo0120** [comment]
@conr2d    @taokayan   here is a problem:

./cleos push action metadataset create '{3, "Eva Gu", "China"}' -p metadataset
Error 3010005: Invalid action
Ensure that your action JSON follows the contract's abi!
Error Details:
Fail to parse action JSON data='{3, "Eva Gu", "China"}'
Expected ':' after key "3"
Error parsing object

**Comment by Danilo0120** [comment]
abi file is:

{
    "____comment": "This file was generated with eosio-abigen. DO NOT EDIT Tue Oct 16 22:36:57 2018",
    "version": "eosio::abi/1.0",
    "structs": [
        {
            "name": "create",
            "base": "",
            "fields": [
                {
                    "name": "unique_id",
                    "type": "uint64"
                },
                {
                    "name": "name",
                    "type": "string"
                },
                {
                    "name": "address",
                    "type": "string"
                }
            ]
        },
        {
            "name": "db_table",
            "base": "",
            "fields": [
                {
                    "name": "id",
                    "type": "uint64"
                },
                {
                    "name": "name",
                    "type": "string"
                },
                {
                    "name": "address",
                    "type": "string"
                },
                {
                    "name": "date_created",
                    "type": "time"
                }
            ]
        },
        {
            "name": "erase",
            "base": "",
            "fields": [
                {
                    "name": "unique_id",
                    "type": "uint64"
                }
            ]
        },
        {
            "name": "get",
            "base": "",
            "fields": [
                {
                    "name": "unique_id",
                    "type": "uint64"
                }
            ]
        },
        {
            "name": "update",
            "base": "",
            "fields": [
                {
                    "name": "unique_id",
                    "type": "uint64"
                },
                {
                    "name": "name",
                    "type": "string"
                },
                {
                    "name": "address",
                    "type": "string"
                }
            ]
        }
    ],
    "types": [],
    "actions": [
        {
            "name": "create",
            "type": "create",
            "ricardian_contract": ""
        },
        {
            "name": "erase",
            "type": "erase",
            "ricardian_contract": ""
        },
        {
            "name": "get",
            "type": "get",
            "ricardian_contract": ""
        },
        {
            "name": "update",
            "type": "update",
            "ricardian_contract": ""
        }
    ],
    "tables": [
        {
            "name": "mltidxdb",
            "type": "db_table",
            "index_type": "i64",
            "key_names": [],
            "key_types": []
        }
    ],
    "ricardian_clauses": [],
    "abi_extensions": []
}

**Comment by Danilo0120** [comment]
here is my code:

#include <string>
#include <eosiolib/eosio.hpp>

using namespace eosio;
using namespace std;

class mltidxdemo : public eosio::contract {

    using contract::contract;

    private:
    // @abi table mltidxdb i64    
    struct [[eosio::table]] db_table {
        uint64_t id;        
        string name;         
        string address;     
        time date_created;    

        uint64_t primary_key() const { return id; }
        EOSLIB_SERIALIZE(db_table, (id)(name)(address)(date_created))
    };

    typedef eosio::multi_index<N(mltidxdb), db_table> db_multi_index; 
    db_multi_index my_database; 

    public:
    mltidxdemo(account_name self) : contract(self),
                                    my_database(_self, _self) {}

    [[eosio::action]]
    void create(const uint64_t unique_id, std::string name = "", std::string address = "") {
     
        auto my_database_itr = my_database.find(unique_id);
        eosio_assert(my_database_itr == my_database.end(), " ID already exists, use 'set' to update info "); 

        print(" ID doesn't exist ");
        print(" Creating new Row for ID ");

        my_database.emplace(_self, [&](auto& my_row) {
            my_row.id = unique_id;
            my_row.name = name;
            my_row.address = address;
            my_row.date_created = now();
        });

        print(" Database set ");
        return;
    }

    [[eosio::action]]
    void get(const uint64_t unique_id) {
       
        auto my_database_itr = my_database.find(unique_id);
        if (my_database_itr == my_database.end()) {
            print(" ID doesn't exist ");
        }

        if (my_database_itr->id == unique_id) {
            print(" Here is your info ");
            print(" ID: ", my_database_itr->id);
            print(" Name: ", my_database_itr->name.c_str());
            print(" Address: ", my_database_itr->address.c_str());
            print(" Date Created: ", my_database_itr->date_created);
        }
    }

    [[eosio::action]]
    void update(const uint64_t unique_id, std::string name = "", std::string address = "") {
        
        auto my_database_itr = my_database.find(unique_id);

        eosio_assert(my_database_itr != my_database.end(), "That ID doesn't exist");

        my_database.modify(my_database_itr, _self, [&](auto& db_to_update) { 
            db_to_update.name = name;
            db_to_update.address = address;
        });

        print(" ID: ", unique_id, " updated ");
    }

    [[eosio::action]]
    void erase(const uint64_t unique_id) {
       
        auto my_database_itr = my_database.find(unique_id);
        if (my_database_itr == my_database.end()) {
            print(" ID doesn't exist ");
        }

        if (my_database_itr->id == unique_id) {
            print(" Deleting your info ");
            my_database.erase(my_database_itr);
        }
    }
};

EOSIO_ABI(mltidxdemo, (create)(get)(update)(erase))

**Comment by Danilo0120** [comment]
@jgiszczak

**Comment by andriantolie** [comment]
@Danilo0120 
`cleos push action metadataset create '{3, "Eva Gu", "China"}' -p metadataset` is indeed an invalid JSON. If you do not want to pass the argument name, you should use square bracket instead of curly bracket, i.e.  '[3, "Eva Gu", "China"]'

@swapnachippagi you miss the single quote there and if you are using shell script to forward arguments as @csares said, don't forget the double quote
