### ISSUE TITLE
Packing and Signing a transaction

### ISSUE THREAD

**Issue by srmcatee1110** [EOSIO/eos#5929]
Is there any examples on packing a transaction?  I'm attempting to sign a transaction and I know it passes the data parameter as part of the call.  Not sure how the data parameter is populated or "packed".

Thanks,>

**Comment by jgiszczak** [comment]
This question is perhaps better asked at [Stack Exchange](eosio.stackexchange.com), especially if you want a diversity of languages.  I believe [eosjs](https://github.com/EOSIO/eosjs) and [eosjs2](https://github.com/EOSIO/eosjs2) both do their own transaction packing if you'd like Javascript samples.
