### ISSUE TITLE
Is it possible to query custom tables using the mongodb plugin?

### ISSUE THREAD

**Issue by notsag-dev** [EOSIO/eos#5930]
Hi all. I'm working on a system running on top of EOS that creates few tables on the blockchain through our contracts. The thing is that when we need to run "complex" queries (and sometimes not complex at all) we just can't do it with eosjs because the API is quite limited.

Taking that into consideration, we are thinking about using the mongodb plugin for EOS, but checking the documentation I'm not getting if we can get information from custom tables that we created or just from the collections that are listed there (accounts, action_traces, etc). At the same time, I wanted to ask those who are using the plugin what's your opinion about it so far, can you trust it for a production environment or it's kind of experimental?

Thank you.

**Comment by heifner** [comment]
The `mongo_db_plugin` tracks `action_trace`, `transaction_trace`, `block`, and `block_state` as well as some limited account information. It does not currently track user tables.

You might want to look at the new https://github.com/EOSIO/eos/tree/state-history-plugin/plugins/state_history_plugin which is not yet released.

**Comment by Onotoko** [comment]
Hi, 
Could mongo_db_plugin track user tables now?
