### ISSUE TITLE
wrong chain

### ISSUE THREAD

**Issue by CRChen** [EOSIO/eos#5931]
hi, i have a mainnet node, which version is 1.2.5. yesterday,it wad shutdown by itself, or maybe i started it when it was still running. when i started it again, this info is on eos.log
`2018-10-09T01:55:59.336 thread-0   net_plugin.cpp:2324           handle_message       ] received a go away message from peering.mainnet.eoscanada.com:9876, reason = wrong chain
2018-10-09T01:55:59.336 thread-0   net_plugin.cpp:2133           operator()           ] Error reading message from peering.mainnet.eoscanada.com:9876: Bad file descriptor`
this node had been initialized, and before this it was running normal.
thx

**Comment by CRChen** [comment]
this is my genesis.json. and it hasn't been modified.
`{
"initial_timestamp": "2018-06-08T08:08:08.888",
"initial_key": "EOS7EarnUhcyYqmdnPon8rm7mBCTnBoot6o7fE2WzjvEX2TdggbL3",
"initial_configuration": {
    "max_block_net_usage": 1048576,
    "target_block_net_usage_pct": 1000,
    "max_transaction_net_usage": 524288,
    "base_per_transaction_net_usage": 12,
    "net_usage_leeway": 500,
    "context_free_discount_net_usage_num": 20,
    "context_free_discount_net_usage_den": 100,
    "max_block_cpu_usage": 200000,
    "target_block_cpu_usage_pct": 1000,
    "max_transaction_cpu_usage": 150000,
    "min_transaction_cpu_usage": 100,
    "max_transaction_lifetime": 3600,
    "deferred_trx_expiration_window": 600,
    "max_transaction_delay": 3888000,
    "max_inline_action_size": 4096,
    "max_inline_action_depth": 4,
    "max_authority_depth": 6
  }
}
`
i have tried several peers. some are wrong chain, some others are connection reset by peer, others are invalid peers.

**Comment by jgiszczak** [comment]
That is the correct genesis file, but reconnecting to mainnet after you were already synced does not require it.  Instead, be sure your `--data-dir` points to the same location where your node was previously syncing.

Judging by the timestamp in the error message, your restarted `nodeos` tried to start a new chain, rather than continue the existing log.
