### ISSUE TITLE
CPU usage bug.  

### ISSUE THREAD

**Issue by ganjingcun** [EOSIO/eos#5934]
https://eosflare.io/account/itehappydice

Last action is 3 day ago, buy cpu usage is still 11 sec, It doesn't look like it's going to recover.

**Comment by taokayan** [comment]
This is not a bug. actual CPU usage will only be refresh when you'll push another transaction. You can assume the cpu usage is zero at this moment.

**Comment by ganjingcun** [comment]
Thank you !  You are right.
