### ISSUE TITLE
Transaction ID offline calculation

### ISSUE THREAD

**Issue by PhilippDolgolev** [EOSIO/eos#5935]
Hi!

I need transaction ID before pushing transaction to network. I found some Java implemetation of signing transactions offline, but as I can see, transaction ID is not equal signed hash. How I can calculate it? Which fields of transaction and in wich order I should pack before calculation?

**Comment by taokayan** [comment]
transaction id is the hash of the transaction content itself, and it will not be affected by the signature. However, the signature will use the combined information from chain_id, transaction content and content free data as digest, then be signed by the private key. Therefore, transaction ID will never equal to signature. All of these can be found in transaction.cpp.

**Comment by PhilippDolgolev** [comment]
I understand that signature never equal transaction ID, I want completely understand how exactly transaction ID generated

For example, tx: https://tools.cryptokylin.io/#/tx/88aa28ba94c529aa075fa41f1ff7822703b7271b754be0f3c0253cfd973f4d48

Chain ID: 5fff1dae8dc8e2fc4d5b23b2c7665c97f9e9d8edf2b6485a86ba311c25639191
Transactiond content (aka packed_trx): f736bf5b7213e0d1fae1000000000100a6823403ea3055000000572d3ccdcd0190a7a608998c554e00000000a8ed32322590a7a608998c554e90a7a6089996e934102700000000000004454f5300000000047465737400

Neiter SHA256 of ChainID + packed_trx, neither SHA256 of packed_trx not equals Transaction ID
(for example I use this online hash generator: https://passwordsgenerator.net/sha256-hash-generator/)

**Comment by jgiszczak** [comment]
The transaction ID is the sha256 of the transaction structure in memory.  See the code [here](https://github.com/EOSIO/eos/blob/1e9ca55cc35b003c81ff4da780fb3cb869a16607/libraries/chain/transaction.cpp#L66).

**Comment by APshenkin** [comment]
Confirmed with this sha256 calculator

https://www.fileformat.info/tool/hash.htm?hex=f736bf5b7213e0d1fae1000000000100a6823403ea3055000000572d3ccdcd0190a7a608998c554e00000000a8ed32322590a7a608998c554e90a7a6089996e934102700000000000004454f5300000000047465737400

sha256 is 88aa28ba94c529aa075fa41f1ff7822703b7271b754be0f3c0253cfd973f4d48

**Comment by hchaor** [comment]
How can I get packed_trx by offline signature?

**Comment by MohammadBaniasad** [comment]
so anyone managed to create the txId offline?

**Comment by heifner** [comment]
https://developers.eos.io/manuals/eos/v2.1/cleos/command-reference/get/transaction_id
