### ISSUE TITLE
Who signed the transaction?

### ISSUE THREAD

**Issue by Simbafa** [EOSIO/eos#5937]
In contract code, I want to know who signed the transaction.
Is there such a function?

**Comment by jgiszczak** [comment]
Yes.  Actions carry with them a vector of permissions.  Each permission corresponds to a signature, and there will be no signatures without a permission, as transactions with extraneous signatures are rejected.
Use `get_action()` to retrieve transaction actions and process the vector of `permission_level`s named `authorization` in each `action`.

From `eosiolib/transaction.hpp`:
```C++
/**
    * Retrieve the indicated action from the active transaction.
    * @param type - 0 for context free action, 1 for action
    * @param index - the index of the requested action
    * @return the indicated action
    */
   inline action get_action( uint32_t type, uint32_t index );
```
And see `eosiolib/action.hpp` for the definitions of `struct action` and `struct permission_level`.
