### ISSUE TITLE
How long does it takes to confirm a block?

### ISSUE THREAD

**Issue by ziranliu** [EOSIO/eos#5946]
According to https://github.com/EOSIO/eos/issues/4965#issuecomment-410049124 , EOS doesn't use BFT consensus. So in my understanding, it should be at least 2/3 +1 (15) BPs confirming, around 90 seconds, in pure DPoS consensus of EOS. Is that right?

**Comment by taokayan** [comment]
It's combination of DPOS and BFT. In normal situation it takes around 330 block time (165 seconds) to make a block become irreversible. (please check https://eosnetworkmonitor.io/)

**Comment by ziranliu** [comment]
@taokayan Thx for your explanation! But I'm still puzzled. I see from https://eosnetworkmonitor.io/ that the difference of current block height and irreversible block height is around 330. But in theory, 2/3+1 (15)BPs confirming could make a block irreversible, hence the max difference of current block height and irreversible block height should be 180. Why it's around 330 in reality?

**Comment by taokayan** [comment]
the actually implementation use DPOS + BFT which result in around 320-330 block time delay.  Pure DPOS will only result in around 180 block time.

**Comment by ziranliu** [comment]
@taokayan If the BFT you use increases the confirmation time,  what's the benefit of it? And is the BFT you use same with EOS white-paper mentioned?
And by the way, I see many cryptocurrency exchanges like Huobi and Binance credit EOS deposits to a client’s account after only one confirmation. Do you know why they can do like this?

Sorry for so many questions bothering you!

**Comment by taokayan** [comment]
The basic idea can be found from https://medium.com/eosio/dpos-bft-pipelined-byzantine-fault-tolerance-8a0634a270ba
