### ISSUE TITLE
missing authority of "xxx"

### ISSUE THREAD

**Issue by Simbafa** [EOSIO/eos#5947]
In contract code, authority is required as:
require_auth(N(xxx));

But I want other accounts (e.g. aaaa, bbbb) also can authorize the transation.
So I updated the xxx account permission as:
xxx:
    active 1:    1 EOS....... 1 aaaa@active 1 bbbb@active

When:
cleos push action mycontract myaction 'action contents' -p aaaa
missing authority error occured.

**Comment by Simbafa** [comment]
Thank you very much for your suggestion.
Do you mean use multisig propose, review, approve etc. steps?
It‘s inconvenient.

Is there another way to do this?

**Comment by taokayan** [comment]
I guess you need to use multisig for this. The multisig can be proposed by either aaaa or bbbb, then approved by both aaaa & bbbb, and then be executed by either aaaa or bbbb

**Comment by firesWu** [comment]
Although you updated the xxx account permission, but this action still need use `-p xxx`.
if your wallet has `aaaa@active` key or `bbbb@active` key, `cleos push action mycontract myaction 'action contents' -p xxx` will exec successfuly
