### ISSUE TITLE
cleos set action permission - should fail if invalid action is specified 

### ISSUE THREAD

**Issue by kasi-git** [EOSIO/eos#5954]
For example: cleos set action permission acc1 acc2 action1 new_permission -p acc1

executed transaction: 22446c6a56c3bba0d0da49065cb05b104baaa0941b561e10810460e40c056cdf  128 bytes  369 us
#         eosio <= eosio::linkauth              "000000000020103200000000002010320080082d6b63d5ed000050db65648ec6"

Above should fail when the action1 doesn't exist on the contract acc2 abi but its simply going through to create the linkauth even though action1 doesn't exists on acc2 contract at all.

**Comment by brianjohnson5972** [comment]
eosio::linkauth code only verifies that the account, code, and permission are valid, EOSIO does not  cache the action entry points provided by the contract WASM for the actions it supports.  Also, it doesn't even require the code account actually have contract code set.  This allows for the permissions and links to be in place before the code account has put their code in place, thus allowing the security to be in place before the contract can be misused.

**Comment by kasi-git** [comment]
Ok, got it. Thanks for clarifying, closing.
