### ISSUE TITLE
Is it possible to get other contract's table in smart contract?

### ISSUE THREAD

**Issue by KunkaYU** [EOSIO/eos#5961]
contract A define a multi-indexed table , is there any way i can get it in contract B?

**Comment by taokayan** [comment]
yes, as long as you define exact the same struct. then in the constructor you need to specifies the name the other contract to replace "_self". for example ```table t(_self, scope)``` will be ```table t(other_contract, scope)```. Please also note that you can only read the data but not modify the data.
