### ISSUE TITLE
Error 3070000: WASM Exception

### ISSUE THREAD

**Issue by JaniceSayang** [EOSIO/eos#5962]
I compile my contract successfully, but can't upload to account. the error message is:
Error 3070000: WASM Exception
Error Details:
env._ZN2fc6to_hexEPKcm unresolveable
pending console output:
maybe i tried to transfer hash to string

**Comment by maldiohead** [comment]
can you show your contract  here or send to me privately ?

**Comment by taokayan** [comment]
Can you provide your minimal code that can reproduce your issue?

**Comment by JaniceSayang** [comment]
> can you show your contract here or send to me privately ?



> Can you provide your minimal code that can reproduce your issue?

 std::string txHash = fc::to_hex((const char*)(&hash), sizeof(hash)); 

as you see,i try to use fc::to_hash to transfer hash to string

**Comment by JaniceSayang** [comment]
and the type of hash is "transaction_id_type"

**Comment by jgiszczak** [comment]
The functions in the fc library are not accessible to contracts.  The fc library is not compiled to WASM unless you do so yourself, and that's not recommended.  You may copy the contents of `fc::to_hex(const char* d, uint32_t s)` into your contract code and use that.  It's not necessary to preserve the `fc` namespace when you copy the function.
