### ISSUE TITLE
Can't find config.ini file after running nodeos

### ISSUE THREAD

**Issue by JamesZH29** [EOSIO/eos#5965]
OS name: Darwin
Version: macOS High Sierra 10.13.4

I've run nodeos for several time local single node with `./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin`

But can't find the config.ini file at `~/Library/Application Support/eosio/nodeos/config`

There is no `eosio` file in `~/Library/Application Support`

So where I can find the config.ini file? Thanks

Last run and shut down as following

> jamess-mbp-2:nodeos James$ ./nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin
> 2018-10-11T18:03:17.368 thread-0   chain_plugin.cpp:329          plugin_initialize    ] initializing chain plugin
> 2018-10-11T18:03:17.370 thread-0   block_log.cpp:124             open                 ] Log is nonempty
> 2018-10-11T18:03:17.371 thread-0   block_log.cpp:142             open                 ] Index is nonempty
> 2018-10-11T18:03:17.390 thread-0   http_plugin.cpp:422           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
> 2018-10-11T18:03:17.390 thread-0   net_plugin.cpp:2910           plugin_initialize    ] Initialize net plugin
> 2018-10-11T18:03:17.390 thread-0   net_plugin.cpp:2936           plugin_initialize    ] host: 0.0.0.0 port: 9876 
> 2018-10-11T18:03:17.390 thread-0   net_plugin.cpp:3007           plugin_initialize    ] my node_id is d5db6844db9ffbf7a5dc1a69e0329e93cec01a3e4cd38b21c6f7aa9b36a7bd60
> 2018-10-11T18:03:17.391 thread-0   main.cpp:110                  main                 ] nodeos version v1.3.1-dirty
> 2018-10-11T18:03:17.391 thread-0   main.cpp:111                  main                 ] eosio root is /Users/James/Library/Application Support
> 2018-10-11T18:03:17.391 thread-0   chain_plugin.cpp:664          plugin_startup       ] starting chain in read/write mode
> 2018-10-11T18:03:17.391 thread-0   chain_plugin.cpp:668          plugin_startup       ] Blockchain started; head block is #47476, genesis timestamp is 2018-06-01T12:00:00.000
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:486           plugin_startup       ] start listening for http requests
> 2018-10-11T18:03:17.391 thread-0   chain_api_plugin.cpp:77       plugin_startup       ] starting chain_api_plugin
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/abi_bin_to_json
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/abi_json_to_bin
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_abi
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_account
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_block
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_block_header_state
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_code
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_code_hash
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_currency_balance
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_currency_stats
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_info
> 2018-10-11T18:03:17.391 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_producer_schedule
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_producers
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_raw_abi
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_raw_code_and_abi
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_required_keys
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_scheduled_transactions
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_table_by_scope
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_table_rows
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/get_transaction_id
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/push_block
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/push_transaction
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/chain/push_transactions
> 2018-10-11T18:03:17.392 thread-0   history_api_plugin.cpp:38     plugin_startup       ] starting history_api_plugin
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/history/get_actions
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/history/get_controlled_accounts
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/history/get_key_accounts
> 2018-10-11T18:03:17.392 thread-0   http_plugin.cpp:554           add_handler          ] add api url: /v1/history/get_transaction
> 2018-10-11T18:03:17.392 thread-0   net_plugin.cpp:3026           plugin_startup       ] starting listener, max clients is 25
> 2018-10-11T18:03:17.392 thread-0   producer_plugin.cpp:692       plugin_startup       ] producer plugin:  plugin_startup() begin
> 2018-10-11T18:03:17.392 thread-0   producer_plugin.cpp:714       plugin_startup       ] Launching block production for 1 producers at 2018-10-11T18:03:17.392.
> 2018-10-11T18:03:17.395 thread-0   producer_plugin.cpp:726       plugin_startup       ] producer plugin:  plugin_startup() end
> 2018-10-11T18:03:17.503 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b9759078ff13... #47477 @ 2018-10-11T18:03:17.500 signed by eosio [trxs: 0, lib: 47476, confirmed: 0]
> 2018-10-11T18:03:18.002 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b976b77d7d10... #47478 @ 2018-10-11T18:03:18.000 signed by eosio [trxs: 0, lib: 47477, confirmed: 0]
> 2018-10-11T18:03:18.503 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b97760af16f1... #47479 @ 2018-10-11T18:03:18.500 signed by eosio [trxs: 0, lib: 47478, confirmed: 0]
> 2018-10-11T18:03:19.004 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b978013451f7... #47480 @ 2018-10-11T18:03:19.000 signed by eosio [trxs: 0, lib: 47479, confirmed: 0]
> 2018-10-11T18:03:19.503 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b9792384a6b5... #47481 @ 2018-10-11T18:03:19.500 signed by eosio [trxs: 0, lib: 47480, confirmed: 0]
> 2018-10-11T18:03:20.003 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b97a6e704ab8... #47482 @ 2018-10-11T18:03:20.000 signed by eosio [trxs: 0, lib: 47481, confirmed: 0]
> 2018-10-11T18:03:20.504 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b97bb57000ce... #47483 @ 2018-10-11T18:03:20.500 signed by eosio [trxs: 0, lib: 47482, confirmed: 0]
> 2018-10-11T18:03:21.005 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b97c1e299f45... #47484 @ 2018-10-11T18:03:21.000 signed by eosio [trxs: 0, lib: 47483, confirmed: 0]
> 2018-10-11T18:03:21.503 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b97d77be2050... #47485 @ 2018-10-11T18:03:21.500 signed by eosio [trxs: 0, lib: 47484, confirmed: 0]
> 2018-10-11T18:03:22.003 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b97edf044a45... #47486 @ 2018-10-11T18:03:22.000 signed by eosio [trxs: 0, lib: 47485, confirmed: 0]
> 2018-10-11T18:03:22.503 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b97f8df49e43... #47487 @ 2018-10-11T18:03:22.500 signed by eosio [trxs: 0, lib: 47486, confirmed: 0]
> 2018-10-11T18:03:23.005 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b9802aa1e38e... #47488 @ 2018-10-11T18:03:23.000 signed by eosio [trxs: 0, lib: 47487, confirmed: 0]
> 2018-10-11T18:03:23.502 thread-0   producer_plugin.cpp:1419      produce_block        ] Produced block 0000b9814a1b2c8b... #47489 @ 2018-10-11T18:03:23.500 signed by eosio [trxs: 0, lib: 47488, confirmed: 0]
> ^C2018-10-11T18:03:23.820 thread-0   net_plugin.cpp:3058           plugin_shutdown      ] shutdown..
> 2018-10-11T18:03:23.820 thread-0   net_plugin.cpp:3061           plugin_shutdown      ] close acceptor
> 2018-10-11T18:03:23.820 thread-0   net_plugin.cpp:3064           plugin_shutdown      ] close 0 connections
> 2018-10-11T18:03:23.820 thread-0   net_plugin.cpp:3072           plugin_shutdown      ] exit shutdown
>

**Comment by jgiszczak** [comment]
The log message is pretty definitive:
`2018-10-11T18:03:17.391 thread-0 main.cpp:111 main ] eosio root is /Users/James/Library/Application Support`
On MacOS, the default data-dir (and you haven't overridden yours in the given commandline) is that path with `eosio/nodeos/config` appended.

I suggest running a filesystem integrity check.  If the config.ini really isn't visible to `ls` at `/Users/James/Library/Application Support/eosio/nodeos/config/config.ini` but nodeos still launches, I suspect filesystem corruption.

**Comment by JamesZH29** [comment]
Found it, thanks! @jgiszczak
