### ISSUE TITLE
Vulnerability?

### ISSUE THREAD

**Issue by liderako** [EOSIO/eos#5966]
I have a smart contract where there is a deposit and a withdrawal. When Alice made a deposit, I can call the command on behalf of the contract `cleos transfer eosio.token contract bob "5.0000 EOS"`  and withdraw the money of alice to the bob account.

**This functional makes it possible to abuse the rights of the owner of the contract.**

How can this be limited?

**Comment by jgiszczak** [comment]
You do not have the private key of the `eosio.token` contract so you can not sign that transaction.  Therefore it will be rejected and no funds will transfer.

Also, your command line is invalid.  `cleos transfer` accepts four arguments, but yours will not parse, as the amount is the third argument and your command line has it as the fourth.

**Comment by liderako** [comment]
I don’t understand. I sign a transaction with my account and not eosio.token. And command valid
