### ISSUE TITLE
[mongo-db-plugin]  why deserialize data in transaction_traces failed？

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#5972]
In my test node, I have successfully executed inline action refund, after undelegatebw cpu and net. However, when I switched on mongo-db-plugin to write data in, find that the data in transaction_traces did not deserialize yet.
![image](https://user-images.githubusercontent.com/11972366/46847660-1021fd00-ce18-11e8-9a88-d9a383002849.png)
I am sure that refund action has been executed successfully：
![image](https://user-images.githubusercontent.com/11972366/46847693-3c3d7e00-ce18-11e8-96b0-68fd6366aadc.png)
Not match the conditions which would cause the failure of deserialization：
![image](https://user-images.githubusercontent.com/11972366/46847903-5deb3500-ce19-11e8-820d-5a3d7c1b05ab.png)
Here is my config.ini:
```
mongodb-queue-size = 1024
mongodb-abi-cache-size = 40960
mongodb-wipe = false
mongodb-block-start = 0
mongodb-uri = mongodb://root:123456@127.0.0.1:27017/EOS
mongodb-store-blocks = 1
mongodb-store-block-states = 1
mongodb-store-transactions = 1
mongodb-store-transaction-traces = 1
mongodb-store-action-traces = 1
# mongodb-filter-on =
# mongodb-filter-out =
plugin = eosio::mongo_db_plugin
```

**Comment by taokayan** [comment]
You need to enable the mongo_db plugin at the beginning of sync-up (from empty database), otherwise the some abi definitions will not be captured by mongo-db which results in serialization failure.

**Comment by guaiguaihw** [comment]
I am sure I enabled the mongo_db plugin at the beginning of sync-up (from empty database)，refund action is a system action，I think mongo-db-plugin should guarantee the deserialization. There may be something wrong with the plugin.

**Comment by heifner** [comment]
What value do you have for:
`abi-serializer-max-time-ms` ?

**Comment by guaiguaihw** [comment]
I find the reason, it because the table `accounts` in mongodb  did not have account `eosio`, I did not sync data since the beginning. I insert `eosio` infos into `accounts` from other mongodb which sync the whole data, and fix it
