### ISSUE TITLE
Lack of generator for ABI files - redundant work needed

### ISSUE THREAD

**Issue by hliberacki** [EOSIO/eos#5974]
Not sure if in the right place, but ....

I have been getting to know EOS for the last few days, and it struck me that ABI files needs to be manually created.

I have been working in multiply projects where those actions were just generated, Interface (ABI/JSON) from Cpp source code, or Cpp code from Interface (ABI/JSON). 

It would be fun for me to implement it, yet I'd like to know whether community/implementers would like to see that coming to life, or whether is there any rational why it's that way?

If agreed that it's needed then let me know which route is preferred, Interface leading to skeleton cpp source or Code leading to skeleton Interface.  In my opinion 1st is better, yet I am open for suggestions.

**Comment by taokayan** [comment]
You can use "abi-gen" tools to generate abi file from source code.

**Comment by hliberacki** [comment]
@taokayan ok then I did not see that. Sorry for dumb question and thanks for the answer.
