### ISSUE TITLE
can not create token maximum_supply

### ISSUE THREAD

**Issue by navneetboghani** [EOSIO/eos#5977]
i fire this command
cleos push action jas create '["eosio","1000000000.0000 EOS",0,0,0]' -p jas

below erorr display

2018-10-12T14:28:53.416 thread-0   main.cpp:3091                 main                 ] Failed with error: Assert Exception (10)
!action_type.empty(): Unknown action create in contract jas

**Comment by jgiszczak** [comment]
Did you run `cleos set contract contracts/eosio.token` first?

**Comment by navneetboghani** [comment]
i fire this command
cleos set contract eosio.token eosio.token -p eosio.token

below erorr display
no wasm file found eosio.token/eosio.token.wasm

this file all  redy  created 
root@home:/eos/contracts/eosio.token# ls
CMakeLists.txt   eosio.token.cpp  eosio.token.wasm
eosio.token.abi  eosio.token.hpp  eosio.token.wast

**Comment by taokayan** [comment]
Please use ```cleos set code YOUR_ACCOUNT WASM_FILE_FULL_PATH``` and ```cleos set abi YOUR_ACCOUNT ABI_FILE_FULL_PATH``` and try to issue again

**Comment by satishkumarj** [comment]
I tried following statement, still getting same error

cleos set code YOUR_ACCOUNT WASM_FILE_FULL_PATH
cleos set abi YOUR_ACCOUNT ABI_FILE_FULL_PATH

2018-10-15T03:12:06.089 thread-0   main.cpp:3091                 main                 ] Failed with error: Assert Exception (10)
!action_type.empty(): Unknown action create in contract eosio.token

**Comment by brianjohnson5972** [comment]
@satishkumarj In you original response you put that you executed:

> cleos set contract eosio.token eosio.token -p eosio.token

That is is how you would setup the eosio.token contract wasm (indicated by the second eosio.token written on that command line) for the eosio.token account (indicated by the first eosio.token written on that command line).
You are indicating that you get the error for the following command:

> cleos push action jas create '["eosio","1000000000.0000 EOS",0,0,0]' -p jas

Which is trying to call the "create" action for the jas contract.  To be able to do that, you should run:

> cleos set contract jas eosio.token -p jas

Which will setup the eosio.token contract wasm for the jas account

**Comment by satishkumarj** [comment]
I was able to create the token, when I set the wasm and abi separately from the build/contracts/eosio.token folder, previously I copied the token contract into another location and I was building the token contract with eosio-cpp and set the contract. no all good I was able to create the token issue token. thanks

**Comment by brianjohnson5972** [comment]
This sounds like you got things working.
