### ISSUE TITLE
no member named 'version_string' in 'appbase::application'

### ISSUE THREAD

**Issue by duvalCC** [EOSIO/eos#5994]
Build eosid failed because of the error below

[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/abi_serializer.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/asset.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/webassembly/wavm.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/webassembly/binaryen.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/webassembly/wabt.cpp.o
[ 92%] Linking CXX static library libeosio_chain.a
[ 92%] Built target eosio_chain
Scanning dependencies of target abi_generator
Scanning dependencies of target eosio_testing
[ 92%] Building CXX object libraries/abi_generator/CMakeFiles/abi_generator.dir/abi_generator.cpp.o
[ 92%] Building CXX object libraries/testing/CMakeFiles/eosio_testing.dir/tester.cpp.o
[ 92%] Linking CXX static library libabi_generator.a
[ 92%] Built target abi_generator
[ 93%] Building CXX object libraries/testing/CMakeFiles/eosio_testing.dir/tester_network.cpp.o
Scanning dependencies of target chain_plugin
[ 93%] Building CXX object plugins/chain_plugin/CMakeFiles/chain_plugin.dir/chain_plugin.cpp.o
/Users/duval/blockchain/eos/plugins/chain_plugin/chain_plugin.cpp:970:13: error: no member named 'version_string' in 'appbase::application'
      app().version_string(),
      ~~~~~ ^
[ 93%] Linking CXX static library libeosio_testing.a
[ 93%] Built target eosio_testing
Scanning dependencies of target http_client_plugin
[ 94%] Building CXX object plugins/http_client_plugin/CMakeFiles/http_client_plugin.dir/http_client_plugin.cpp.o
1 error generated.
make[2]: *** [plugins/chain_plugin/CMakeFiles/chain_plugin.dir/chain_plugin.cpp.o] Error 1
make[1]: *** [plugins/chain_plugin/CMakeFiles/chain_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 94%] Linking CXX static library libhttp_client_plugin.a
[ 94%] Built target http_client_plugin
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

➜  eos git:(v1.3.2) ✗ git status
On branch v1.3.2
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   externals/binaryen
	modified:   libraries/appbase
	modified:   libraries/chainbase
	modified:   libraries/fc
	modified:   libraries/softfloat

➜  eos git:(v1.3.2) ✗

**Comment by duvalCC** [comment]
my rebo was on tag v1.3.2

**Comment by conr2d** [comment]
I don't have this error. How did you checkout tag v1.3.2? My command:
```
$ git checkout tags/v1.3.2 -b v1.3.2
```
Or, are you sure to run `git submodule update --init --recursive` before build?

**Comment by taokayan** [comment]
Please checkout release/1.3.x and retry.

**Comment by jgiszczak** [comment]
This is a symptom of an out of sync submodule.  As conr2d said, use `git submodule update --init --recursive` to solve it.
