### ISSUE TITLE
code":3040008,"name":"tx_duplicate

### ISSUE THREAD

**Issue by helperShang** [EOSIO/eos#5995]
status code=409, body={"code":409,"message":"Conflict","error":{"code":3040008,"name":"tx_duplicate","what":"Duplicate transaction","details":[{"message":"duplicate transaction b3c6b3fc57ecbc739b258a641783eae190f5657c5353864f47bdf5b937e1192a","file":"producer_plugin.cpp","line_number":383,"method":"on_incoming_transaction_async"}]}}

**Comment by taokayan** [comment]
are you pushing the same transaction multiple times?

**Comment by helperShang** [comment]
yes ,transfer 0.0001 to one account 3 times per second

**Comment by helperShang** [comment]
how to solve this problem？

**Comment by taokayan** [comment]
The simplest way is to use different memo

**Comment by cassade** [comment]
Is it possible that after getting tx_duplicate error transaction is included into the one of subsequent blocks, before expiration?

**Comment by jgiszczak** [comment]
No, duplicate transactions are never included.  Once a transaction is determined to be a duplicate, an exception is raised and propagated, interrupting processing.
