### ISSUE TITLE
INLINE_ACTION_SENDER ERROR

### ISSUE THREAD

**Issue by gamesir2** [EOSIO/eos#5996]
HI ! i maked inline action on my contract's code.
* code:
```
#include "eosio.token.hpp"

name account = "testaccount"_n;
asset quantity = asset(10000, symbol(symbol_code("EOS"),4));

 INLINE_ACTION_SENDER(token, transfer)(
         "eosio.token"_n, { {_self, "active"_n}},
         { _self, account, quantity, "Withdraw"});
```
* error
```
Error 3050003: eosio_assert_message assertion failure
```
My contract account had join 'mycontract@eosio.code' action permission, and the balance is insufficient.
Current eosio-cpp version 1.3.0

**Comment by taokayan** [comment]
I guess it should be ```INLINE_ACTION_SENDER(eosio.token, transfer)``` instead of ```INLINE_ACTION_SENDER(token, transfer)```
