### ISSUE TITLE
why set contract again error. Parse Error(4)...

### ISSUE THREAD

**Issue by boy-good** [EOSIO/eos#5997]
Failed with error: Parse Error (4) Unexpected char '40' in ""

![image](https://user-images.githubusercontent.com/39320533/46928090-620e9100-d06b-11e8-9483-7286f9258d74.png)

**Comment by taokayan** [comment]
what tools are you using for compiling? can you share your minimal code to reproduce this issue?

**Comment by boy-good** [comment]
> what tools are you using for compiling? can you share your minimal code to reproduce this issue?

hello. I use docker to run eos-dev. Show my contract code right?

**Comment by boy-good** [comment]
> what tools are you using for compiling? can you share your minimal code to reproduce this issue?

"eosiocpp -n test" the contract ,now reproduce this issue
![image](https://user-images.githubusercontent.com/39320533/46934032-ede2e600-d088-11e8-9f38-321b1f1618b2.png)
![image](https://user-images.githubusercontent.com/39320533/46934039-f509f400-d088-11e8-8f84-c5f87eaa2c44.png)

**Comment by taokayan** [comment]
you need to change from test.wast to test.wasm, otherwise your wasm will not be related to your source code.

**Comment by boy-good** [comment]
> you need to change from test.wast to test.wasm, otherwise your wasm will not be related to your source code.

This is how i to create and set contract 
![image](https://user-images.githubusercontent.com/39320533/46940007-4c649000-d09a-11e8-831a-9f7a8014e616.png)
 and this is my contract dict
![image](https://user-images.githubusercontent.com/39320533/46940082-6c944f00-d09a-11e8-89ee-29be0bd9f882.png)

**Comment by boy-good** [comment]
> you need to change from test.wast to test.wasm, otherwise your wasm will not be related to your source code.

I'm so sorry.When i compile abi ,the options -g write -o cause this error.
