### ISSUE TITLE
New keosd process is created even though there is an existing keosd process (develop branch)

### ISSUE THREAD

**Issue by andriantolie** [EOSIO/eos#5998]
I was investigating issue #4064, where `cleos wallet create` fails if "eosio-wallet" directory doesn't exist and keosd is already running.

This issue still persists in the master branch but has disappeared in the develop branch. 

However, I noticce the following thing in develop branch:
1. I call `cleos wallet create`, a keosd process is spawned
2. I delete the "~/eosio-wallet" folder
3. I call `cleos wallet create` again, another keosd process is spawned. So I have two keosd processes now running, which I think should be prevented since I already have a keosd process running?

Although it's not harmful or critical, I think it will be tidier if it can be cleaned up.

**Comment by conr2d** [comment]
If there is an executed `keosd` process, 8900 port may be occupied (common configuration). In this case, another `keosd` fails to be executed.

**Comment by andriantolie** [comment]
Correct. That's why this issue doesn't happen in the master branch as it is still using TCP port. However, the develop branch seems to have moved the keosd communication to unix socket instead and the unix socket file is located inside "eosio-wallet" folder.

**Comment by jgiszczak** [comment]
Since all file locks in Linux are advisory locks, a perfect solution that avoids all possible race conditions is not possible.    That said, `keosd` now monitors its lock file and terminates if it's manually removed, preventing most instances of abandoned `keosd` instances happening as a result of user experimentation.
