### ISSUE TITLE
STAT-101 ⁃ Testnet Sprint One - Transfer fails because of transaction expiration timeout

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#600]
Transfer from inita to initb fails sometimes due to the low limit on transaction expiration time.

Steps to reproduce:

1. start a local eosd-walletd
2. Import relevant keys
3. Transfer 1000 eos from inita to initb

Output:
MacBook01:build pravin$ programs/eosc/eosc --host 10.160.12.152 --port 8889 --wallet-port 8899 transfer inita initb 1000
An error occurred while submitting the transaction for this command!

**Comment by heifner** [comment]
reopened by jira, closing.

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

Please see related: https://blockone.atlassian.net/browse/STAT-128
