### ISSUE TITLE
Write irreversible block delay in mongodb for 24 minutes

### ISSUE THREAD

**Issue by czm7805077** [EOSIO/eos#6000]
We initiated a transaction to query the transaction in hisory_plugin and will soon be able to get the transaction irreversible, but after checking the transaction in mongodb for 24 minutes, why is this?

**Comment by czm7805077** [comment]
This happens only in multiple nodes, everything is normal for a single node.

**Comment by taokayan** [comment]
What's your hardware config?

**Comment by heifner** [comment]
What are your config.ini options?

**Comment by csquan** [comment]
it is nothing of confiig.because before this error happened,tx is work normally.

**Comment by jgiszczak** [comment]
It may still be the config, despite it not changing.  Mongodb behavior may change as the amount of stored data becomes very large.  If the problem has been solved, please close this issue.

**Comment by jgiszczak** [comment]
Improvements have been made to mongodb support when mongodb is configured to run in a cluster.  The modifications are available in [v1.6.0-rc1](https://github.com/EOSIO/eos/releases/tag/v1.6.0-rc1).

**Comment by heifner** [comment]
It is possible you are seeing this: https://github.com/EOSIO/eos/issues/6409#issuecomment-442866447

**Comment by heifner** [comment]
No answer from the reporter, closing.
