### ISSUE TITLE
Provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority  but does not have signatures for it under a provided delay of 0 ms

### ISSUE THREAD

**Issue by satishkumarj** [EOSIO/eos#6010]
push_transaction: `{  
   "code":500,
   "message":"Internal Service Error",
   "error":{  
      "code":3090003,
      "name":"unsatisfied_authorization",
      "what":"Provided keys, permissions, and delays do not satisfy declared authorizations",
      "details":[  
         {  
            "message":"transaction declares authority '{\"actor\":\"user1\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [\"EOS69hiYv5Haijk5QLk6RtGn4z5TLrUQQZRhPmWfXHAdnAsvrx8Bb\"], and a delay max limit of 3888000000 ms",
            "file":"authorization_manager.cpp",
            "line_number":413,
            "method":"check_authorization"
         }
      ]
   }
}`

I am getting above response from when I am Using RPC, my main question is EOS69hiYv5Haijk5QLk6RtGn4z5TLrUQQZRhPmWfXHAdnAsvrx8Bb key not in my wallet or not created any where, I am not sure where it is coming from, I checked my local wallet it have 2 private keys and corresponding public keys.

I also noticed the key in the above response keeps changing every time I run
 
I am following following sequence and using the response values to send the next request 
1) abi_json_to_bin
2) get_info
3) get_public_keys
4) get_block
5) get_required_keys
6) sign_transaction
7) push_transaction -- failing here

any help would be greatly appreciated .

Thanks!

**Comment by firesWu** [comment]
Check whether sign_transaction's  data and push_transaction's data are the same. any change must be re-sign.

**Comment by taokayan** [comment]
are you using version 1.3 and later versions? There was a push transaction bug on the signed transaction in the old versions.

**Comment by satishkumarj** [comment]
> are you using version 1.3 and later versions? There was a push transaction bug on the signed transaction in the old versions.

v1.3.0-dirty, I am not sure what dirty means

**Comment by satishkumarj** [comment]
> Check whether sign_transaction's data and push_transaction's data are the same. any change must be re-sign.

I guess even the expiration should be same right ? I will verify and update the what I found. Thanks!

**Comment by satishkumarj** [comment]
I found the that RPC pack transaction and cleos pack transaction are slightly different 

can you please suggest what might have caused this, it is expiration conversion

cleos
`**30f7c**55b63bd513dd8270000000001e02f652a1b04e861000000006483523201e02f652a1b04e86100000000a8ed32322ae02f652a1b04e8610c52657374617572616e7473310c52657374617572616e74733107656e676c69736800`
rpc
`**b5fac**55bf5c3d060ebab0000000001e02f652a1b04e861000000006483523201e02f652a1b04e86100000000a8ed32322ae02f652a1b04e8610c52657374617572616e7473310c52657374617572616e74733107656e676c69736800`

**Comment by satishkumarj** [comment]
Thank you for helping me figure out I was able to fix the issue, I was adding 60 more seconds to the expiry date after I get the signed transaction which is not matching with original, I fixed that and I was able to push transaction.

Thank you!

**Comment by satishkumarj** [comment]
Thank you for helping me figure out I was able to fix the issue, I was adding 60 more seconds to the expiry date after I get the signed transaction which is not matching with original, I fixed that and I was able to push transaction.

Thank you!

**Comment by SpadeRoy** [comment]
using version 1.3.
I have same error:
```json
{"transferData": {"transaction_id":"b93834b26e88e8d68135acef2ea3c65f67bef3625968f98bbdc7f7bf5c462982","broadcast":false,"transaction":{"compression":"none","transaction":{"expiration":"2018-10-17T07:04:22","ref_block_num":10274,"ref_block_prefix":77198628,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosblackteam","name":"transfer","authorization":[{"actor":"greatsouthex","permission":"active"}],"data":"d055cb9ae26cd465a0f655b8ab9635c5003fab010000000004424c41434b000006726566756e64"}],"transaction_extensions":[]},"signatures":["SIG_K1_KUqsdH8P2yiR5KLydR9KDArSRwQfYrLj8j4nX7Viad9VWwgdfWKueFzSPM3HTuKrBjZpT763aBx3BQeg9vq5HTmpXf9Xq7"]}}, "error": "http://172.16.1.15:8888/v1/chain/push_transaction: status code=500, body={\"code\":500,\"message\":\"Internal Service Error\",\"error\":{\"code\":3090003,\"name\":\"unsatisfied_authorization\",\"what\":\"Provided keys, permissions, and delays do not satisfy declared authorizations\",\"details\":[{\"message\":\"transaction declares authority '{\\\"actor\\\":\\\"greatsouthex\\\",\\\"permission\\\":\\\"active\\\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [\\\"EOS6nmJnjqFV9KT3vFnkutAG93omqFDg9bbSq3jbaHiaAa7Ei669j\\\"], and a delay max limit of 3888000000 ms\",\"file\":\"authorization_manager.cpp\",\"line_number\":413,\"method\":\"check_authorization\"}]}}"} 
```

but, other account transfer is success, why ? 
please help @satishkumarj @taokayan  @firesWu

**Comment by satishkumarj** [comment]
Please pack the transaction using cleos and compare the the packed transaction from rpc, if both are not same then, there might be issue in rpc packing transaction, it was the case with my issue @SpadeRoy

**Comment by SpadeRoy** [comment]
> Please pack the transaction using cleos and compare the the packed transaction from rpc, if both are not same then, there might be issue in rpc packing transaction, it was the case with my issue @SpadeRoy

let me try
