### ISSUE TITLE
Theoretically there is the possibility of overflow.

### ISSUE THREAD

**Issue by hellowuzekai** [EOSIO/eos#6011]
In the file the file `/eos/libraries/chain/include/eosio/chain/wasm_interface_private.hpp `, theoretically there is the possibility of overflow in line 46 of the function `parse_initial_memory`.
Look at the code:

```
const U32 base_offset = data_segment.baseOffset.i32;
const Uptr memory_size = (module.memories.defs[0].type.size.min << IR::numBytesPerPageLog2);
if(base_offset >= memory_size || base_offset + data_segment.data.size() > memory_size)
```

the `memory_size` is less than 0x2100000，and the same as `base_offset`. If we construct a data_segment.data is more than `0xffffffff - base_offset` In 32-bit machine, it will cause a overflow.
In fact the data is more than 4Gb. So it just exists in theory. But I think the code should like below:

```
if(base_offset >= memory_size || uint64_t(base_offset) + data_segment.data.size() > memory_size)
```
THX :)

**Comment by taokayan** [comment]
This is not true, "32bit uint + 64bit uint" will result in 64bit uint. This is a sample program:
```
#include <stdio.h>
#include <iostream>
int main(int argc, char **argv) {
  uint32_t a = 10;
  uint64_t b = 0xffffffff;
  std::cout << (a + b);
  return 0;
}
```
output: 4294967305

**Comment by hellowuzekai** [comment]
the vector::size will return a `size_type` typed number, so in 32-bit machine the  data_segment.data.size() will return a uint32 number.

**Comment by taokayan** [comment]
eosio couldn't be compiled as 32-bit binary anyway.
