### ISSUE TITLE
I push the dice contract show error 3090003...

### ISSUE THREAD

**Issue by boy-good** [EOSIO/eos#6013]
Exception Details: 3090003 unsatisfied_authorization: Provided keys, permissions, and delays do not satisfy declared authorizations
transaction declares authority '{"actor":"alice","permission":"active"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [{"actor":"demo","permission":"eosio.code"}], provided keys [], and a delay max limit of 3888000000 ms
    {"auth":{"actor":"alice","permission":"active"},"provided_delay":0,"provided_permissions":[{"actor":"demo","permission":"eosio.code"}],"provided_keys":[],"delay_max_limit_ms":3888000000}
    thread-0  authorization_manager.cpp:413 check_authorization
pending console output:
    {"console":""}

like this.

**Comment by quocle108** [comment]
You should set eosio.code permission for your contract
Use following commands:

`cleos set account permission contract_account active '{"threshold": 1,"keys": [{"key": "publickey","weight": 1}],"accounts": [{"permission":{"actor":"contract_account","permission":"eosio.code"},"weight":1}]}' owner -p contract_account
`

**Comment by boy-good** [comment]
> You should set eosio.code permission for your contract
> Use following commands:
> 
> `cleos set account permission contract_account active '{"threshold": 1,"keys": [{"key": "publickey","weight": 1}],"accounts": [{"permission":{"actor":"contract_account","permission":"eosio.code"},"weight":1}]}' owner -p contract_account`

Thank you very much!
but now a new error show:

 Exception Details: 3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
assertion failure with message: attempt to add asset with different symbol
    {"s":"attempt to add asset with different symbol"}
    thread-0  wasm_interface.cpp:930 eosio_assert
pending console output:
    {"console":""}

**Comment by quocle108** [comment]
It seem the quantity incorrect symbol name. 
Could you provide your command action?

**Comment by boy-good** [comment]
> It seem the quantity incorrect symbol name.
> Could you provide your command action?

cleos push action demo deposit '[ "alice", "10.0000 EOS" ]' -p alice

**Comment by kstvigilante** [comment]
local nodeos doesnt support EOS use SYS instead if you havent created SYS then create and issue it first using eosio.token contract

**Comment by heifner** [comment]
Closing this since dice is being removed by #6023
