### ISSUE TITLE
How to delete table data from the contract account

### ISSUE THREAD

**Issue by yhc166188** [EOSIO/eos#6018]
After I clear out the contract, the table data under this contract still exists, and also occupies RAM, I do not know with what command delete table data

**Comment by kstvigilante** [comment]
void deletedata(){

    require_auth(_self);
    <table_name> st(_self, _self);
    auto itr = st.begin();
    while(itr != st.end()){
        itr = st.erase(itr);
    }
}

**Comment by jgiszczak** [comment]
There is no generic command to remove contract data.  As kstvigilante describes, you must create a contract with a delete action, then invoke the action.

If your table is so large that deleting it all at once would exceed the CPU usage limitations of a transaction, you'll need to add a counter to the above code and remove rows in batches.  This may also be necessary if you don't have many tokens staked for CPU usage.

**Comment by yhc166188** [comment]
> There is no generic command to remove contract data. As kstvigilante describes, you must create a contract with a delete action, then invoke the action.
> 
> If your table is so large that deleting it all at once would exceed the CPU usage limitations of a transaction, you'll need to add a counter to the above code and remove rows in batches. This may also be necessary if you don't have many tokens staked for CPU usage.

Can we write a general command to delete a table?

**Comment by yhc166188** [comment]
> void deletedata(){
> 
> ```
> require_auth(_self);
> <table_name> st(_self, _self);
> auto itr = st.begin();
> while(itr != st.end()){
>     itr = st.erase(itr);
> }
> ```
> }
> after this
> cleos push action <contract_name> deletedata [ ] -p <contract_name>

What should I do if I want to delete the table data of other contracts in the system contract?

**Comment by jgiszczak** [comment]
Generally speaking, you shouldn't be trying to.  On public nets, you have no option to customize the system contract.

On a private network, the only difference to kstvigilante's code would be in the declaration of the table, which would substitute an arbitrary account name for the first `_self` argument.  This could conceivably be an argument to the contract action.
