### ISSUE TITLE
Redirect Tokens [SUPPORT]

### ISSUE THREAD

**Issue by dacom-dark-sun** [EOSIO/eos#6020]
I have a dispatcher in the contract to intercept the transfer action from the eosio.token contract, after which the event is processed, and at the end, it is necessary to redirect the tokens to another account. Redirect of tokens falls out with an error - not enough balance. Those. It seems that at the time of sending the redirect, eosio considers the balance not received. Is there any way to get around this problem, or is the redirect impossible?

Schema of one action: 
- Receive tokens on contract_a
- Do things on contract_a
- Transfer received tokens from contract_a to contract_b

**Comment by jgiszczak** [comment]
Correct, the balance has not been finalized.  You could generate a deferred transaction, though you will need to keep an accounting of what balances should be transferred where in an internal table in the event the deferred transaction fails.  You'll need a contract action to retry.
