### ISSUE TITLE
eosio.token contract, why creator should be contract owner

### ISSUE THREAD

**Issue by quocle108** [EOSIO/eos#6030]
As i've read eosio.token contract, only contract owner can create token then issue it to issuer.
**require_auth( _self );**
Why don't allow issuer can create token ? it allow everyone use existing eosio.token contract without push new one.

Thanks

**Comment by jgiszczak** [comment]
At present there is effectively no interest from block producers of EOS.IO-based networks in enabling arbitrary token issuance using the eosio.token account.  You may campaign among them to fund such development if you wish.
