### ISSUE TITLE
http_plugin and a unix socket

### ISSUE THREAD

**Issue by deckb** [EOSIO/eos#6038]
I noticed the other day that there was an option in the http plugin to use an unix socket however when I tried to set that config option I got an error message stating it was unrecognized. 

`std::exception::what: unrecognised option 'unix-socket-path'`

Looking at the code it seems that if the default is not set then the option is not added. 

https://github.com/EOSIO/eos/blob/2232802dee4be1a3f6ca436edad64af3c45d7029/plugins/http_plugin/http_plugin.cpp#L351

I guess the question is whether this is supposed to work and if not will it be supported in the future?

**Comment by jgiszczak** [comment]
The http_plugin's unix socket support is in use by keosd as a more secure option for communicating with it.  There are no plans to enable that support in nodeos.
