### ISSUE TITLE
An error occurs when linking unit_test in my contract

### ISSUE THREAD

**Issue by yepp4you** [EOSIO/eos#6039]
os : macOS mojave
eosio.cdt v1.3.2
eosio v1.4.0

https://github.com/EOSIO/eos/blob/2232802dee4be1a3f6ca436edad64af3c45d7029/libraries/chain/webassembly/wavm.cpp#L134

[100%] Linking CXX executable unit_test
Undefined symbols for architecture x86_64:
  "Platform::immediately_exit()", referenced from:
      eosio::chain::webassembly::wavm::wavm_runtime::immediately_exit_currently_running_module() in libeosio_chain.a(wavm.cpp.o)
ld: symbol(s) not found for architecture x86_64

**Comment by jgiszczak** [comment]
macOS?

**Comment by yepp4you** [comment]
yes macOS

**Comment by jgiszczak** [comment]
This is frequently fixed automatically simply by running the build script a second time.  If that doesn't work, removing the `build` directory and then rerunning the script has also been reported to be successful.

**Comment by yepp4you** [comment]
I tried clearing the build folder of all the folders (eos, eosio.cdt, my project) and testing, but the same problem occurred, so I commented out the following code on eos, built it and then did a unit_test on my project.
