### ISSUE TITLE
How can I access to nodeos from other device?

### ISSUE THREAD

**Issue by djKooks** [EOSIO/eos#6046]
Hello
I just success testing smart contract 'Hello world', and now want to send same event as`cleos push action hello ...` from smartphone. Is there some way(http API, or else...) to do it like this, or is there a document about this?

Thanks.

**Comment by wuyahuang** [comment]
```
cleos -u https://mainnet.meet.one get info
```

**Comment by andriantolie** [comment]
You can use eosjs (https://github.com/EOSIO/eosjs)

**Comment by djKooks** [comment]
@andriantolie yeah...but because I'm finding a way to do in Android, so cannot use it.

**Comment by djKooks** [comment]
I found RPC API guide [here](https://developers.eos.io/eosio-nodeos/reference). Is `push_transaction` same as `cleos push action...`?

**Comment by jgiszczak** [comment]
Yes, using the `push_transaction` endpoint is fundamentally what happens at the end of `cleos push action`.  You do have to perform all of the steps `cleos` was performing for you to compose the transaction JSON you are pushing, including serializing and signing.

You may certainly use eosjs2 on Android.  Build a web page using it and visit it using a browser running in Android.  You may also use frameworks like PhoneGap to write your Android app using HTML5 and Javascript, which can include a copy of eosjs2 natively within the application, no download from the webserver required.
