### ISSUE TITLE
about pending_block 

### ISSUE THREAD

**Issue by zfuke164345** [EOSIO/eos#6061]
when a transaction coming  in proudcer_plugin on_incoming_transaction_async
if exec a transaction  need a pending_block ,and if  pending_block create in apply_block  and that time a transaction coming ,that case will broken  apply_block

**Comment by andriantolie** [comment]
Hi @zfuke164345, can you please elaborate more on the control flow that leads to the above conclusion? That will be helpful. Thanks!

**Comment by zfuke164345** [comment]
1.use requst v1/chain_plugin/push_transaction -> chain::plugin::read_write::push_transaction ->producer_plugin->incoming::methods::transaction_async  in this  function code
if have pending_block  then will  call chain::push_transaction  to exec this transaction
 chain::push_transaction will push transaction in pending_block 

2.and when a new block coming  if all right will last call control::apply_block this function will create pending_block to exec new block  transactions


if 1 and 2 done at the same time  ，1 will use 2 created pending_block  , in apply_block 
 EOS_ASSERT( pending->_pending_block_state->block->transactions.size() == num_pending_receipts+1,
                        block_validate_exception, "expected receipt was not added",
                        ("block", *b)("expected_receipt", receipt)
                      );

will fail ?

**Comment by zfuke164345** [comment]
@andriantolie

**Comment by jgiszczak** [comment]
`nodeos` is not multithreaded.  1 and 2 can not happen "at the same time".  They will always happen sequentially and the sequence ensures that there is always a pending block available for push_transaction.  The `_async` in method names indicate methods which fundamentally use polling with timeouts to interact with the network, not threads.  There are no threads except the main thread.

**Comment by zfuke164345** [comment]
@jgiszczak  thank you!!!
