### ISSUE TITLE
1.4.1 error

### ISSUE THREAD

**Issue by helperShang** [EOSIO/eos#6062]
unlinkable block                                                                                                                                                 │
│       {"id":"0151eb973621444bce304e9389ab240dab9134b471802b0c9df2a559a09b47bf","previous":"0151eb96ce6fca8e89f6a7be703ba1ce4ef10675b84cac9697693a5d10009931"}      │
│       thread-0  fork_database.cpp:151 add                                                                                                                          │
│   rethrow                                                                                                                                                          │
│       {}                                                                                                                                                           │
│       thread-0  controller.cpp:1251 push_block                                                                                                                     │
│   warn  2018-10-19T06:12:01.967 thread-0  controller.cpp:1251           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block                │
│   unlinkable block                                                                                                                                                 │
│       {"id":"0151eb98ca145b8993deb9415c2ce68f91f20db7407a31e10915b0f8d1f3daec","previous":"0151eb973621444bce304e9389ab240dab9134b471802b0c9df2a559a09b47bf"}      │
│       thread-0  fork_database.cpp:151 add                                                                                                                          │
│   error 2018-10-19T06:12:01.967 thread-0  producer_plugin.cpp:316       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block                │
│   unlinkable block                                                                                                                                                 │
│       {"id":"0151eb98ca145b8993deb9415c2ce68f91f20db7407a31e10915b0f8d1f3daec","previous":"0151eb973621444bce304e9389ab240dab9134b471802b0c9df2a559a09b47bf"}      │
│       thread-0  fork_database.cpp:151 add                                                                                                                          │
│   rethrow                                                                                                                                                          │
│       {}                                                                                                                                                           │
│       thread-0  controller.cpp:1251 push_block                                                                                                                     │
│   warn  2018-10-19T06:12:01.967 thread-0  controller.cpp:1251           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block                │
│   unlinkable block                                                                                                                                                 │
│       {"id":"0151eb99facfdcac90270c6ffa218eec0dc27fcc20b0203e1f4de0500d2e39ad","previous":"0151eb98ca145b8993deb9415c2ce68f91f20db7407a31e10915b0f8d1f3daec"}      │
│       thread-0  fork_database.cpp:151 add                                                                                                                          │
│   error 2018-10-19T06:12:01.967 thread-0  producer_plugin.cpp:316       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block                │
│   unlinkable block                                                                                                                                                 │
│       {"id":"0151eb99facfdcac90270c6ffa218eec0dc27fcc20b0203e1f4de0500d2e39ad","previous":"0151eb98ca145b8993deb9415c2ce68f91f20db7407a31e10915b0f8d1f3daec"}      │
│       thread-0  fork_database.cpp:151 add                                                                                                                          │
│   rethrow                                                                                                                                                          │
│       {}

**Comment by andriantolie** [comment]
Hi @helperShang, to investigate further on this issue, can you provide more detail? Such as:
1. Is it your private net / testnet/ mainnet?
2. Is this the first time your node syncing with another node? Or has this node synced with another node under the old version previously then this issue appears after you upgrade the node?
3. Do your node and the node you are syncing with share the same genesis?
Thanks.

**Comment by helperShang** [comment]
mainnet use bnet

**Comment by jgiszczak** [comment]
`bnet_plugin` remains unreliable.  Use `net_plugin` to sync with mainnet.
