### ISSUE TITLE
bidnameinfo returning bidname even though it doesn't exist

### ISSUE THREAD

**Issue by NorseGaud** [EOSIO/eos#6067]
<pre>cleos -uhttp://api.eosnewyork.io system bidnameinfo notcreated
bidname:                              note
highest bidder:               chaoxiaojuan
highest bid:                            12
last bid time:     2018-06-21T02:32:34.500</pre>

This can be replicated using anything that doesn't exist in the bidname system. It looks to be matching the first few characters:

<pre>cleos -uhttp://api.eosnewyork.io system bidnameinfo t3st
bidname:                                t4
highest bidder:               eoszzzeoszzz
highest bid:                             1
last bid time:     2018-06-29T16:09:29.000</pre>

I believe it should return "No bidname record found" (cleos/main.cpp):
<pre>         if ( result.rows.empty() ) {
            std::cout << "No bidname record found" << std::endl;
            return;
         }</pre>

**Comment by conr2d** [comment]
@brianjohnson5972 
Can you review #6070 ? That will solve more issues like this.

**Comment by taokayan** [comment]
Looks like this issue is solved:)
