### ISSUE TITLE
Why are failed transactions not included in the blockchain?

### ISSUE THREAD

**Issue by liviu-** [EOSIO/eos#6069]
Other smart contract platforms include failed transactions on chain in order to tax the sender for the resources consumed. In EOSIO, it seems like failed transactions are discarded and incur no costs, so a user may spam a node with failing transaction at no cost aside from electricity.

Why is the design as such?

**Comment by taokayan** [comment]
test

**Comment by ChristianDunst** [comment]
test

**Comment by ChristianDunst** [comment]
test
