### ISSUE TITLE
Binary builds for mac OS X failing on some machines

### ISSUE THREAD

**Issue by larryk85** [EOSIO/eos#6073]
Binary builds for mac OS X are failing on some machines with `illegal instruction 4`.  This is caused by the build script doing a `brew link --force llvm@4`.  This clobbers the system's `libc++.dylib` and links against llvm's.  A fix for this will be available in the next patch release (v1.4.2).

**Comment by kesar** [comment]
Linked https://github.com/EOSIO/eos/issues/6084

**Comment by larryk85** [comment]
Resolved in v1.4.2 by PR #6100
