### ISSUE TITLE
how to find scheduled deferred transaction of the account ?

### ISSUE THREAD

**Issue by hama** [EOSIO/eos#6074]
is there any way that we can find all scheduled deferred transactions of one account ?

**Comment by taokayan** [comment]
I guess there's no way to find those by account at this moment, as one transaction can be signed by multiple accounts.

**Comment by hama** [comment]
thanks,  so, if i bought an account, the owner can schedule a deferred transaction to change the key back. buy an account is not safe now.

**Comment by StarryJapanNight** [comment]
https://github.com/EOSIO/eosio.contracts/issues/53#issue-353297274

**Comment by jgiszczak** [comment]
Resolution of this issue requires a hard fork.  Changes to the code will be tracked as #6118.
