### ISSUE TITLE
is this command unsecured?

### ISSUE THREAD

**Issue by zottirik** [EOSIO/eos#6078]
Hi,
Is this command unsecured?
./cleos --url https://eos.greymass.com transfer from to "3 EOS" "memo"

My private key is secure still?

**Comment by conr2d** [comment]
What's the point of worrying? That command doesn't send any info directly related to your private key. It just signs transaction with key, but the private key cannot be inferred from signed transaction.

**Comment by jgiszczak** [comment]
`cleos` never receives or transmits the private key, and in fact the `cleos` process never touches the private key.  Signatures are created by `keosd`.
