### ISSUE TITLE
transfer action invoke in my contract can not work .

### ISSUE THREAD

**Issue by beykery** [EOSIO/eos#6081]
my contract contains : 
 
 action(permission_level{_this_contract, N(active)}, N(eosio.token),
           N(transfer), std::make_tuple(_this_contract, account, quantity,
                                        std::string("for free .")))
            .send();

but it dos'nt work now , two days ago it worked well .  why ?

**Comment by zhaoguo20002** [comment]
the same error as you @beykery

**Comment by beykery** [comment]
sorry , my fault .

**Comment by beykery** [comment]
怎么加权限？@hama

**Comment by beykery** [comment]
已解决
需要添加eosio.code权限
@hama 
多谢。
