### ISSUE TITLE
brew install --universal

### ISSUE THREAD

**Issue by kesar** [EOSIO/eos#6083]
➜  ~ brew install eosio --universal
==> Installing eosio from eosio/eosio
==> Downloading https://github.com/eosio/eos/archive/v1.4.1.tar.gz
==> Downloading from https://codeload.github.com/EOSIO/eos/tar.gz/v1.4.1
######################################################################## 100.0%
Warning: Cannot verify integrity of c8bfb8991f211c5dd2056f9d6137135bcf8b802f4e155df673c6a42ead027616--eos-1.4.1.tar.gz
A checksum was not provided for this resource
For your reference the SHA256 is: d855ea3369c6bd0715b2d144b3ae74f9fb0d68df6ddcafadcfb092fb1b5fed39
Error: An exception occurred within a child process:
  RuntimeError: Error, only supporting binary packages at this time

**Comment by larryk85** [comment]
What version of OSX are you using?

**Comment by kesar** [comment]
➜ ~ brew config
HOMEBREW_VERSION: 1.7.7-111-g8b3228a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8b3228ad8a68468e0511ba7116e51ba75393eba4
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f3c308ab51044d4a663bffbdd813af25543a633c
Core tap last commit: 8 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_172
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0

High Sierra

**Comment by larryk85** [comment]
Do you have problems if you don't use the `--universal` option?  Correct me if I am wrong, but `--universal` is for fat binaries, and we only support 64-bit Intel.

**Comment by kesar** [comment]
without --universal get installed, but got this error: https://github.com/EOSIO/eos/issues/6084
