### ISSUE TITLE
nodeos fails after brew install ( illegal hardware instruction )

### ISSUE THREAD

**Issue by kesar** [EOSIO/eos#6084]
➜  ~ brew doctor
Your system is ready to brew.

➜  ~ brew config
HOMEBREW_VERSION: 1.7.7-111-g8b3228a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8b3228ad8a68468e0511ba7116e51ba75393eba4
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f3c308ab51044d4a663bffbdd813af25543a633c
Core tap last commit: 8 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_172
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0

➜  ~ brew tap eosio/eosio    
==> Tapping eosio/eosio
Cloning into '/usr/local/Homebrew/Library/Taps/eosio/homebrew-eosio'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Tapped 1 formula (31 files, 26.7KB).
➜  ~ brew install eosio    
==> Installing eosio from eosio/eosio
==> Downloading https://github.com/eosio/eos/releases/download/v1.4.1/eosio-1.4.1.high_sierra.bottle.tar.gz
Already downloaded: /Users/kesar/Library/Caches/Homebrew/downloads/5671336acd5a13d10a5d54468748c4a0a4366d08e6f4581d26e3c1dc45bb9520--eosio-1.4.1.high_sierra.bottle.tar.gz
==> Pouring eosio-1.4.1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/eosio/1.4.1: 14 files, 61.9MB
➜  ~ nodeos  
[1]    21165 illegal hardware instruction  nodeos

(cleos works fine)

**Comment by taokayan** [comment]
Interesting, what's your CPU model?

**Comment by jgiszczak** [comment]
Have you tried with a more recent release?  There have been fixes to homebrew support.

**Comment by jgiszczak** [comment]
Closing as unresponsive after 21 days.

**Comment by JohnnyZhao** [comment]
OSX Mojava, same issue
