### ISSUE TITLE
智能合约中能否使用  regex

### ISSUE THREAD

**Issue by senhanxiao** [EOSIO/eos#6085]
#include< regex >
regex_match  
编译通过，但是部署时提示如下错误 

Exception Details: 3070000 wasm_exception: WASM Exception
env.__ctype_get_mb_cur_max unresolveable
    {"module":"env","export":"__ctype_get_mb_cur_max"}
    thread-0  wasm_interface.hpp:42 resolve

    {"mod_name":"env","export_name":"__ctype_get_mb_cur_max"}
    thread-0  wasm_interface.hpp:44 resolve
pending console output: 
    {"console":""}
    thread-0  apply_context.cpp:61 exec_one

**Comment by jgiszczak** [comment]
Try prefixing your eosio-cpp command line with `export LC_ALL="C";`.  If you are still using eosiocpp, you should switch to eosio-cpp, from https://github.com/EOSIO/eosio.cdt.

**Comment by jgiszczak** [comment]
Per EOSIO/eosio.cdt#125, regex in smart contracts is not supported and not recommended because of its dependency on `std::locale`.
