### ISSUE TITLE
Try to create a new account, command doesn't work

### ISSUE THREAD

**Issue by JamesZH29** [EOSIO/eos#6086]
`cleos --url http://node2.liquideos.com:8888 system newaccount --stake-net '0.1 EOS' --stake-cpu '0.1 EOS' --buy-ram-kbytes 4 asdfghj12345 asdfghj55555 EOS7Divrf81apTrzXTxwocYCM8LvhLDqfpsF36pgTQtbpAKZV6hnZ EOS7Divrf81apTrzXTxwocYCM8LvhLDqfpsF36pgTQtbpAKZV6hnZ`

> ERROR: ExtrasError: [EOS7Divrf81apTrzXTxwocYCM8LvhLDqfpsF36pgTQtbpAKZV6hnZ EOS7Divrf81apTrzXTxwocYCM8LvhLDqfpsF36pgTQtbpAKZV6hnZ]

I have created and tried several keys, doesn't solve the problem. Is something wrong in the command I typed in?

**Comment by damianoazzolini** [comment]
Look at the issue #4565

**Comment by jgiszczak** [comment]
The issue linked by damianoazzolini contains the solution to your problem.  To stake 0.1 EOS you must specify `"0.1000 EOS"`.
