### ISSUE TITLE
【mongo-db-plugin】transaction_traces is null ?

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#6088]
we enabled mongo-db-plugin, and we just need the transaction_traces table, so we disabled another four tables:
```
mongodb-store-blocks = false
mongodb-store-block-states = false
mongodb-store-transactions = false
mongodb-store-action-traces = false
```
but, we find that if we disabled action-traces, the table of transaction_traces is null. why?

**Comment by guaiguaihw** [comment]
![image](https://user-images.githubusercontent.com/11972366/47281681-c9e64e00-d60e-11e8-9e95-7c923f2230ef.png)
when I read codes, find that if action_traces disabled, transaction_traces won't be insert. I wonder it's reasonable or you should remind us in  docs.

**Comment by littleLj** [comment]
我开了全部的collections , 还是没有数据。 1。3  还是好的。

**Comment by guaiguaihw** [comment]
> 我开了全部的collections , 还是没有数据。 1。3 还是好的。

你的节点是什么版本？config.ini发出来哇

**Comment by littleLj** [comment]
> > 我开了全部的collections , 还是没有数据。 1。3 还是好的。
> 
> 你的节点是什么版本？config.ini发出来哇

I test again , it worked.   data is writed to mongo.    
found the write_atraces  is false  by debug .
I  add  two functions to  parse action trace,  not use the  add_action_traces  and fixed the bug.
