### ISSUE TITLE
Merkle Tree over Blocks that change Active Producers

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#609]
We have currently specified a merkle tree over all block headers. A sequental validation of block headers will enable someone to trivially verify the handoff of old producers to new producers assuming 2/3 of the producers are honest.  This handoff is only necessary when the active set of producers changes.

Light validating nodes need to verify that a transaction was generated and validated by 2/3 of the active set.  They do not care about all blocks, instead they care about the active set of producers at any given time and whether that set has confirmed a block.

Since the active set might change at a much lower frequency (a couple times per day would be a lot) then number of blocks one must track is much lower.

Given knowledge of the active set at time T combined with 2/3 signatures on block a block at that time + merkle proof of existence within that block you can prove a transactions status.

With 21 producers we would need 14 signatures, plus a much shorter merkle proof over contents of a single block.

**Comment by FinleySmile** [comment]
EOS Dawn 3.0 no in process ?

**Comment by gleehokie** [comment]
Replaced by #1671 (PR #1672), closing per conversation with @bytemaster and @wanderingbort.
