### ISSUE TITLE
How to freeze an account

### ISSUE THREAD

**Issue by wangzehui123456** [EOSIO/eos#6093]
when i use eos to set up private network, how can me freeze an account like eos?

**Comment by jgiszczak** [comment]
To disable an account, set the keys of the account to null, as described in the [documentation](https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence#section-step-12-resign-eosio-).

From the documentation:
```bash
$ cleos push action eosio updateauth '{"account": "eosio", "permission": "owner", "parent": "", "auth": {"threshold": 1, "keys": [], "waits": [], "accounts": [{"weight": 1, "permission": {"actor": "eosio.prods", "permission": "active"}}]}}' -p eosio@owner
$ cleos push action eosio updateauth '{"account": "eosio", "permission": "active", "parent": "owner", "auth": {"threshold": 1, "keys": [], "waits": [], "accounts": [{"weight": 1, "permission": {"actor": "eosio.prods", "permission": "active"}}]}}' -p eosio@active
```

**Comment by wangzehui123456** [comment]
I want to using eosio permission to freezing other common account, like BP nodes

**Comment by wangzehui123456** [comment]
像报道里面的一样作为超级节点冻结其他账户和恢复其他账户 应该怎么办

**Comment by jgiszczak** [comment]
The same procedure applies to any account.  Just change the account name in the command to the desired account.
