### ISSUE TITLE
calculateNextRound error

### ISSUE THREAD

**Issue by Toormi** [EOSIO/eos#610]
In file "eos\libraries\native_contract\producer_objects.cpp"
I found in this line:

boost::for_each(LapCompleters, StartNewLap);

The size of LapCompleters was 21, but StartNewLap only ran once.

Finnally, I found the problem.

LapCompleters is a rang of AllProducersByFinishTime, and AllProducersByFinishTime is an index of the multi index container ProducerVotesMultiIndex. 

The problem is that while it walking throgh LapCompleters, at the same time StartNewLap modify the container. It will lead to an error after modify the container if you continue accessing the container with LapCompleters.

**Comment by jgiszczak** [comment]
Obsolete.  This code no longer exists in a form I can recognize.  Producer voting was completely reimplemented as a system contract.
