### ISSUE TITLE
Unspecified error after hard replay

### ISSUE THREAD

**Issue by djKooks** [EOSIO/eos#6106]
Hello
I just run `--replay-blockchain` cause dirty flag has been shown.
```
...
2018-10-23T01:53:33.950 thread-0   chain_plugin.cpp:649          plugin_initialize    ] 13 St13runtime_error: database dirty flag set
rethrow database dirty flag set:
    {"what":"database dirty flag set"}
    thread-0  chain_plugin.cpp:649 plugin_initialize
2018-10-23T01:53:33.951 thread-0   main.cpp:123                  main                 ] database dirty flag set (likely due to unclean shutdown): replay required
...
```

But after replay, `push` action returns exception, which works well just before.
```
2018-10-23T01:58:15.117 thread-0   http_plugin.cpp:587           handle_exception     ] STD Exception encountered while processing chain.get_abi
2018-10-23T01:58:15.117 thread-0   http_plugin.cpp:588           handle_exception     ] Exception Details: unknown key (eosio::chain::name): hello
```

Do I have to do something with this?

Thanks.

**Comment by andriantolie** [comment]
`Unknown key` error message usually appears when the blockchain is not able to find the required object inside chainbase. The above error seems like it is trying to find the abi of an account called `hello` and it can't find that account inside chainbase.

I think what you can pay attention in this case:
1. When you push the action, has the replay finished successfully? If it's still in the middle of replay and you haven't replayed up to the block where `hello` account is created, then you just need to wait until it finishes replaying.

**Comment by djKooks** [comment]
@andriantolie well, I replayed by `--replay-blockchain`, but still dirty flag appears so used `--hard-replay-blockchain`, and nodeos worked successfully. Is there a way to check replay finished successfully?

More, I used EOSIO 1.3.2 version.

Thanks.

**Comment by andriantolie** [comment]
It should be written in the log if it has finished replaying. At least you will see, your node continues to produce or append block from other producers.

Can you try `cleos get account hello`? Can it find that account? What the action you are pushing is actually trying to do btw?

**Comment by jgiszczak** [comment]
Closed as no further reply. Original question appears to be answered.
