### ISSUE TITLE
How to get block info (e.g. block hash code) in smart contract?

### ISSUE THREAD

**Issue by wangyilin1987** [EOSIO/eos#6109]
I can't find any interface to get block hash code in smart contract.

**Comment by andriantolie** [comment]
Hi @wangyilin1987, you can get the block info of a block through chain_api_plugin (i.e. `cleos get block`) outside the smart contract, but it's not possible to get it inside the smart contract as it's not exposed.

**Comment by varshakhandre14** [comment]
What is the solution for this?
