### ISSUE TITLE
Mongo data is getting bigger and bigger.

### ISSUE THREAD

**Issue by TamirTian** [EOSIO/eos#6114]
### How to solve this question of big data ?
It's 1440 GB in my db and increase by 40G per day.

other: I want to connect the Kafka to the EOS, any guys have suggestions?

**Comment by eosdex** [comment]
Here is the [plugin](https://github.com/meitu/eos/tree/master/plugins/pubsub_plugin) for kafka

**Comment by jgiszczak** [comment]
`mongo_db_plugin` supports filters.  See the documentation for `mongodb-filter-out =`.

Beyond that, EOS.IO mainnet is a world wide public network with a block rate of 0.5 seconds and a transaction rate that's averaging over 20 transactions per block.  This has resulted in 394511360 transactions and 14355993 blocks to date, and both will only grow.  You should expect large amounts of data for such a network.
