### ISSUE TITLE
reading data from multiindex is limited ?

### ISSUE THREAD

**Issue by sivachaitanya** [EOSIO/eos#6120]
I have written 10000 rows of data to a multiindex table and using cleos to fetch all the rows from it using - "time cleos get table testa testa ttab -l 10000", but all I can see is that it was able to read only 4097 rows and shows up more=true, can you please advice how can I retrieve all 10K rows in this case ? and why the results are always limited to 4096/4097 rows even though in the command I clearly passed limit as 10000 ?

**Comment by brianjohnson5972** [comment]
nodeos limits the time that the query is run to prevent too much resources being devoted to servicing read queries, and preventing it from processing incoming blocks. To get all the rows you need to create another query requesting the rows that you didn't receive when the returned query indicates there are more rows that were not returned.
