### ISSUE TITLE
mongo plugin

### ISSUE THREAD

**Issue by littleLj** [EOSIO/eos#6124]
when I apply the mongo plugin ,  the  nodes  always  crash.    there  are logs.

**info  2018-10-24T07:12:00.733 thread-0  chain_plugin.cpp:585          plugin_initialize    ] Using genesis state provided in '/home/lj/genesis.json'
warn  2018-10-24T07:12:00.733 thread-0  chain_plugin.cpp:592          plugin_initialize    ] Starting up fresh blockchain with provided genesis state.
info  2018-10-24T07:12:00.772 thread-0  net_plugin.cpp:2901           plugin_initialize    ] Initialize net plugin
info  2018-10-24T07:12:00.772 thread-0  net_plugin.cpp:2927           plugin_initialize    ] host: 0.0.0.0 port: 9876 
info  2018-10-24T07:12:00.772 thread-0  net_plugin.cpp:2998           plugin_initialize    ] my node_id is f823f0427be44d1409528cdcd060ba2e2bddd7eb4ef8dc3025fb7e058f620f75
info  2018-10-24T07:12:00.772 thread-0  mongo_db_plugin.cpp:1504      plugin_initialize    ] initializing mongo_db_plugin
info  2018-10-24T07:12:00.772 thread-0  mongo_db_plugin.cpp:1587      plugin_initialize    ] connecting to mongodb://127.0.0.1:27017/EOS
Press <RETURN> to close this window...**

I use the mongo  last version mongo  c++ drive . 
when i compile  codes ,  there has a  warning 

**/home/lj/eos1.4.1/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:1385:20: warning: 'count' is deprecated [-Wdeprecated-declarations]
      if( accounts.count( make_document()) == 0 ) {
                   ^
/usr/local/include/mongocxx/v_noabi/mongocxx/collection.hpp:429:38: note: 'count' has been explicitly marked deprecated here
    MONGOCXX_DEPRECATED std::int64_t count(bsoncxx::document::view_or_value filter,
                                     ^
1 warning generated.**

**Comment by littleLj** [comment]
the count  function deprecated .
if( accounts.count(make_document()) == 0

**Comment by taokayan** [comment]
Can you provide your config? It would be nice if you can provide core dump info as well.

**Comment by littleLj** [comment]
sorry , I don't save the core dump .   the log is  only show a signal .
first , i install the EOS  . then  I want to study mongo c++ drive , I  install the mongo c++ drive according to the http://mongocxx.org/mongocxx-v3/installation/  。 after  few days , I update the EOS code and to complie failed .

I  uninstall the mongo drive , and use the build script to build ,  it is ok 。  maybe the reason  is the count function  has been deprecated.   I  install   mongo c++ according to  http://mongocxx.org/mongocxx-v3/installation/    
mongo version is 3.4.1.
