### ISSUE TITLE
Error 3010014: Invalid symbol

### ISSUE THREAD

**Issue by Petelin** [EOSIO/eos#6125]
```
Error 3010014: Invalid symbol
Error Details:
Symbol NOTEXIST is not supported by token contract eosio.token
```
i am learn eosio.token and i cannot see any check in the code to make sure it only transfer TOKEN that he issued, so i try to use eosio.token to transfer some unknow token. but it do get an error.  Invalid symbol.  where did this  come from?

**Comment by jgiszczak** [comment]
Transfer of an unrecognized symbol managed by eosio.token will fail [here](https://github.com/EOSIO/eosio.contracts/blob/1b8574172ca61f725545b14b5edddc174e4d0ce0/eosio.token/src/eosio.token.cpp#L97), generating an exception.  Tokens not issued by a particular instantiation of eosio.token will not be present in that table.

**Comment by cppfuns** [comment]
https://www.bcskill.com/index.php/archives/615.html
