### ISSUE TITLE
Connect to main net

### ISSUE THREAD

**Issue by SavostinVladimir** [EOSIO/eos#6128]
Hi
I installed nodeos through command 
`sudo apt install ./eosio-1.4.1.ubuntu-18.04-x86_64.deb 
`
then I tried to run nodeos with genesis.json:
`nodeos --genesis-json  genesis.json
`
my genesis.json file consist the mainnet cofiguration:
`{
"initial_timestamp": "2018-06-08T08:08:08.888",
"initial_key": "EOS7EarnUhcyYqmdnPon8rm7mBCTnBoot6o7fE2WzjvEX2TdggbL3",
"initial_configuration": {
"max_block_net_usage": 1048576,
"target_block_net_usage_pct": 1000,
"max_transaction_net_usage": 524288,
"base_per_transaction_net_usage": 12,
"net_usage_leeway": 500,
"context_free_discount_net_usage_num": 20,
"context_free_discount_net_usage_den": 100,
"max_block_cpu_usage": 200000,
"target_block_cpu_usage_pct": 1000,
"max_transaction_cpu_usage": 150000,
"min_transaction_cpu_usage": 100,
"max_transaction_lifetime": 3600,
"deferred_trx_expiration_window": 600,
"max_transaction_delay": 3888000,
"max_inline_action_size": 4096,
"max_inline_action_depth": 4,
"max_authority_depth": 6
}
}
`

and I have this log:

vs@vs-pc:~$ nodeos --genesis-json  genesis.json
info  2018-10-24T10:32:08.695 thread-0  chain_plugin.cpp:333          plugin_initialize    ] initializing chain plugin
info  2018-10-24T10:32:08.696 thread-0  chain_plugin.cpp:585          plugin_initialize    ] Using genesis state provided in '/home/vs/genesis.json'
warn  2018-10-24T10:32:08.696 thread-0  chain_plugin.cpp:592          plugin_initialize    ] Starting up fresh blockchain with provided genesis state.
info  2018-10-24T10:32:08.726 thread-0  http_plugin.cpp:422           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
info  2018-10-24T10:32:08.726 thread-0  net_plugin.cpp:2901           plugin_initialize    ] Initialize net plugin
info  2018-10-24T10:32:08.726 thread-0  net_plugin.cpp:2927           plugin_initialize    ] host: 0.0.0.0 port: 9876 
info  2018-10-24T10:32:08.726 thread-0  net_plugin.cpp:2998           plugin_initialize    ] my node_id is 69b8f5a61d7348a0ec482e46f64b7ed0102b43bf96985103edea493df62250d7
info  2018-10-24T10:32:08.726 thread-0  main.cpp:110                  main                 ] nodeos version v1.4.1
info  2018-10-24T10:32:08.727 thread-0  main.cpp:111                  main                 ] eosio root is /home/vs/.local/share
error 2018-10-24T10:32:08.727 thread-0  controller.cpp:1593           startup              ] No head block in fork db, perhaps we need to replay
warn  2018-10-24T10:32:08.727 thread-0  controller.cpp:571            initialize_fork_db   ]  Initializing new blockchain with genesis state                  
info  2018-10-24T10:32:08.754 thread-0  controller.cpp:389            init                 ] database initialized with hash: f5021b331a160d3f9c1bc720e600029614a8f2714becb694f0ea5d0c490945f3
info  2018-10-24T10:32:08.761 thread-0  chain_plugin.cpp:707          plugin_startup       ] starting chain in read/write mode
info  2018-10-24T10:32:08.761 thread-0  chain_plugin.cpp:711          plugin_startup       ] Blockchain started; head block is #1, genesis timestamp is 2018-06-08T08:08:08.888
info  2018-10-24T10:32:08.761 thread-0  http_plugin.cpp:486           plugin_startup       ] start listening for http requests
info  2018-10-24T10:32:08.761 thread-0  net_plugin.cpp:3017           plugin_startup       ] starting listener, max clients is 25
info  2018-10-24T10:32:08.761 thread-0  producer_plugin.cpp:714       plugin_startup       ] producer plugin:  plugin_startup() begin
info  2018-10-24T10:32:08.761 thread-0  producer_plugin.cpp:748       plugin_startup       ] producer plugin:  plugin_startup() end

after this I try `nodeos --genesis-json  genesis.json` again and get:

vs@vs-pc:~$ nodeos --genesis-json  genesis.json
info  2018-10-24T10:38:08.086 thread-0  chain_plugin.cpp:333          plugin_initialize    ] initializing chain plugin
warn  2018-10-24T10:38:08.086 thread-0  chain_plugin.cpp:684          plugin_initialize    ] 3110006 plugin_config_exception: Incorrect plugin configuration
Genesis state can only be set on a fresh blockchain.
    {}
    thread-0  chain_plugin.cpp:571 plugin_initialize
Failed to initialize

so then I change the `.local/share/eosio/config/config.ini` and add there plugins and peers:

plugin = eosio::producer_plugin
plugin = eosio::chain_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::history_plugin
plugin = eosio::history_api_plugin
plugin = eosio::net_plugin
plugin = eosio::net_api_plugin 

p2p-peer-address = 106.10.42.238:9876
p2p-peer-address = 178.49.174.48:9876
p2p-peer-address = 185.253.188.1:19876
p2p-peer-address = 807534da.eosnodeone.io:19872
p2p-peer-address = api-full1.eoseoul.io:9876
p2p-peer-address = api-full2.eoseoul.io:9876
p2p-peer-address = api.eosuk.io:12000

and I try again:

but it returns errors:
`warn  2018-10-24T10:20:02.865 thread-0  controller.cpp:1251           push_block           ] 3190000 block_log_exception: Block log exception
block log has no blocks and is appending the wrong first block.  Expected ${expecgted}, but received: 1
    {"expected":0,"actual":1}
    thread-0  controller.cpp:248 on_irreversible
error 2018-10-24T10:20:02.865 thread-0  producer_plugin.cpp:316       on_incoming_block    ] 3190000 block_log_exception: Block log exception
block log has no blocks and is appending the wrong first block.  Expected ${expecgted}, but received: 1
    {"expected":0,"actual":1}
    thread-0  controller.cpp:248 on_irreversible
rethrow
    {}
    thread-0  controller.cpp:1251 push_block
`

**Comment by jgiszczak** [comment]
With your new configuration, rerun as `nodeos --delete-all-blocks --genesis-json genesis.json`.  You should let it run long enough to begin syncing (it will log receipt of new blocks), then terminate `nodeos` gracefully with Ctrl-C and run it again with no arguments.  It will resume syncing where it left off.  Those two arguments must be used only once, and are no longer required after the initial startup and creation of a new chain.

**Comment by SavostinVladimir** [comment]
Thank you!
