### ISSUE TITLE
Conecctions to local node not work

### ISSUE THREAD

**Issue by SavostinVladimir** [EOSIO/eos#6129]
I run the local nodeos connected to mainnet with such config.ini:

chain-state-db-size-mb = 12288
#get-transactions-time-limit = 3
blocks-dir = "blocks"
http-server-address = 0.0.0.0:8888
p2p-listen-endpoint = 0.0.0.0:9856
p2p-server-address = :9856
allowed-connection = any
#log-level-net-plugin = info
max-clients = 100
connection-cleanup-period = 30
network-version-match = 0
sync-fetch-span = 2000
enable-stale-production = false
#required-participation = 33
plugin = eosio::chain_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::history_plugin
plugin = eosio::history_api_plugin
filter-on = *
plugin = eosio::db_size_api_plugin
p2p-peer-address = 106.10.42.238:9876
p2p-peer-address = 178.49.174.48:9876
p2p-peer-address = 185.253.188.1:19876
p2p-peer-address = 807534da.eosnodeone.io:19872
p2p-peer-address = api-full1.eoseoul.io:9876
p2p-peer-address = api-full2.eoseoul.io:9876
p2p-peer-address = api.eosuk.io:12000
p2p-peer-address = boot.eostitan.com:9876
p2p-peer-address = bp.antpool.com:443

but then I try to send request to http://localhost:9856/v1/chain/get_info
I get the such log:

warn  2018-10-24T13:26:26.767 thread-0  net_plugin.cpp:732            connection           ] accepted network connection
error 2018-10-24T13:26:26.776 thread-0  net_plugin.cpp:2112           operator()           ] incoming message length unexpected (542393671), from 127.0.0.1:37508

**Comment by SavostinVladimir** [comment]
But then I use `cleos get info` it works ok!!

**Comment by jgiszczak** [comment]
`curl` must address port 8888 in your configuration, not port 9856.  The P2P protocol is not HTTP and can not be interpreted by `curl`.  Try `curl http://localhost:8888/v1/chain/get_info`

**Comment by SavostinVladimir** [comment]
It's strange! the` curl http://localhost:8888/v1/chain/get_info` is not working, but the `curl http://127.0.0.1:8888/v1/chain/get_info` is ok!!
