### ISSUE TITLE
How to upgrade eos to latest version

### ISSUE THREAD

**Issue by zyzsyncloss** [EOSIO/eos#6134]
from 1.1 to 1.4.1, don't want to uninstall old one

**Comment by yashbhavsar007** [comment]
Here is code to update eos without removing old one
```
cd ../eos
git pull
git checkout v1.4.1 
git submodule update --init --recursive
./eosio_build.sh
cd build
sudo make install
```

**Comment by taokayan** [comment]
please send us an email to developers@block.one or ask in https://eosio.stackexchange.com/
