### ISSUE TITLE
about _persistent_transactions and  _pending_incoming_transactions

### ISSUE THREAD

**Issue by zfuke164345** [EOSIO/eos#6137]
if a user request a transction  and in on_incoming_transaction_async   transction  exec once then push in
_persistent_transactions  ,and on  start_block  function ,event when not producting , _persistent_transactions  also exec.why exec multi times?

**Comment by jgiszczak** [comment]
The network speculatively executes the transactions it receives in an attempt to provide the most current view of contract state possible.  When a transaction is incorporated into a block, speculative execution is rolled back and it is re-executed to be certain it will have the same results on all nodes.

This can result in local node state changing for outside queries, then changing back if a transaction was locally executed speculatively, then expired before being incorporated into a block.
