### ISSUE TITLE
why my local listener node receiving below message ?

### ISSUE THREAD

**Issue by 26rahulsingh** [EOSIO/eos#6143]
by eosio [trxs: 0, lib: 115871, conf: 0, latency: -5513 ms]
2325486ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block d32f2caf7e98d48d... #115873 @ 2018-10-25T06:38:51.500 signed by eosio [trxs: 0, lib: 115872, conf: 0, latency: -6013 ms]
2325487ms thread-0   net_plugin.cpp:2599           handle_message       ] unable to accept block on assert exception Assert Exception (10)
block->timestamp < (fc::time_point::now() + fc::seconds(7)): received a block from the future, ignoring it
 from jetmetrix:9876 - ede0488
2325487ms thread-0   net_plugin.cpp:2187           operator()           ] Error reading message from 10.64.112.137:9876: Bad file descriptor

**Comment by 26rahulsingh** [comment]
On My Producer Node log
-----------------------------------

6:44:45.000 signed by eosio [trxs: 0, lib: 116579, confirmed: 0]
info  2018-10-25T06:44:45.500 thread-0  producer_plugin.cpp:1490      produce_block        ] Produced block 0001c765e90c8fba... #116581 @ 2018-10-25T06:44:45.500 signed by eosio [trxs: 0, lib: 116580, confirmed: 0]
info  2018-10-25T06:44:46.001 thread-0  producer_plugin.cpp:1490      produce_block        ] Produced block 0001c7666e23ef55... #116582 @ 2018-10-25T06:44:46.000 signed by eosio [trxs: 0, lib: 116581, confirmed: 0]
warn  2018-10-25T06:44:46.112 thread-0  net_plugin.cpp:732            connection           ] accepted network connection
error 2018-10-25T06:44:46.151 thread-0  net_plugin.cpp:2140           operator()           ] Error reading message from fuse1:9876 - 79937f6: Connection reset by peer

**Comment by 26rahulsingh** [comment]
And On listener Node log
----------------------------------

6:58:27.000 signed by eosio [trxs: 0, lib: 117966, conf: 0, latency: -3318 ms]
info  2018-10-25T06:58:23.682 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 4bf1d1c743d6024d... #117968 @ 2018-10-25T06:58:27.500 signed by eosio [trxs: 0, lib: 117967, conf: 0, latency: -3817 ms]
info  2018-10-25T06:58:23.683 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 587535f1cf380b13... #117969 @ 2018-10-25T06:58:28.000 signed by eosio [trxs: 0, lib: 117968, conf: 0, latency: -4316 ms]
info  2018-10-25T06:58:23.684 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 3d97a279d77f1a74... #117970 @ 2018-10-25T06:58:28.500 signed by eosio [trxs: 0, lib: 117969, conf: 0, latency: -4815 ms]
info  2018-10-25T06:58:23.685 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block a177a2e31e05cc6a... #117971 @ 2018-10-25T06:58:29.000 signed by eosio [trxs: 0, lib: 117970, conf: 0, latency: -5314 ms]
info  2018-10-25T06:58:23.685 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 6839862c02bd6ae8... #117972 @ 2018-10-25T06:58:29.500 signed by eosio [trxs: 0, lib: 117971, conf: 0, latency: -5814 ms]
info  2018-10-25T06:58:23.686 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block bac5b2e82889f46f... #117973 @ 2018-10-25T06:58:30.000 signed by eosio [trxs: 0, lib: 117972, conf: 0, latency: -6313 ms]
error 2018-10-25T06:58:23.686 thread-0  net_plugin.cpp:2549           handle_message       ] block_validate_exception accept block #117974 syncing from 10.64.12.137:9877 - ce9e166
error 2018-10-25T06:58:23.687 thread-0  net_plugin.cpp:2140           operator()           ] Error reading message from 10.64.11.137:9876: Bad file descriptor

**Comment by jgiszczak** [comment]
You must be certain the clocks on each of your nodes are properly synchronized.  Configure and run a timekeeping service such as NTP.

**Comment by KunkaYU** [comment]
got the same question..
