### ISSUE TITLE
how to call another contract ?

### ISSUE THREAD

**Issue by sivachaitanya** [EOSIO/eos#6146]
I have 2 contracts - contract 1 and contract 2, from contract 1 I want to call function B of contract 2, can you provide a working example of how can I read storage of contract B as well as how can I write to storage of contract B from contract A ?

**Comment by brianjohnson5972** [comment]
If by "call function B of contract 2" you mean send an action to contract 2, you need to construct an eosio::action (https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/action.hpp) with the account name for contract 2 and send it.  If you mean call a function defined in another WASM file, the answer is you cannot.  You can compile multiple files into the same WASM code and then you would just call function B or contract 2 the same way you would in regular C++ code.

**Comment by jgiszczak** [comment]
To read storage of Contract B from Contract A, instantiate the multi_index with the account name and scope of Contract A, rather than `_self` as shown in the documentation.

Contract B can not ever write to the storage of Contract A.  Storage of other accounts is always read only.
