### ISSUE TITLE
19 test failed out of 50 

### ISSUE THREAD

**Issue by JingyuQian** [EOSIO/eos#6155]
I'm new to EOS. I followed the instructions and installed EOSIO from raw. Some tests were failed when I **make test**.

**OS:** Ubuntu 16.04 LTS
**EOS version:** 1.4.1

62% tests passed, 19 tests failed out of 50

Label Time Summary:
long_running_tests         =  25.95 sec (7 tests)
nonparallelizable_tests    =  67.99 sec (13 tests)

Total Test time (real) = 563.98 sec

The following tests FAILED:
	 31 - nodeos_sanity_test (Failed)
	 32 - nodeos_sanity_bnet_test (Failed)
	 33 - nodeos_run_test (Failed)
	 34 - nodeos_run_bnet_test (Failed)
	 36 - nodeos_run_test-mongodb (Failed)
	 37 - distributed-transactions-test (Failed)
	 38 - distributed-transactions-bnet-test (Failed)
	 39 - restart-scenarios-test-resync (Failed)
	 40 - restart-scenarios-test-hard_replay (Failed)
	 41 - restart-scenarios-test-none (Failed)
	 42 - validate_dirty_db_test (Failed)
	 43 - launcher_test (Failed)
	 44 - nodeos_sanity_lr_test (Failed)
	 45 - nodeos_sanity_bnet_lr_test (Failed)
	 46 - nodeos_run_check_lr_test (Failed)
	 47 - nodeos_forked_chain_lr_test (Failed)
	 48 - nodeos_voting_lr_test (Failed)
	 49 - nodeos_voting_bnet_lr_test (Failed)
	 50 - nodeos_under_min_avail_ram_lr_test (Failed)
Errors while running CTest

Also went to look possible solutions and similar issues but with no result. 
Appreciate the help.

**Comment by brianjohnson5972** [comment]
Please run again with:
```
ctest --output-on-failure  -R nodeos_sanity_test
```
and save it to a file and attach it here.

**Comment by JingyuQian** [comment]
[https://drive.google.com/file/d/1K8_AFufKnPwDO1M6NHu8o6TF6gM4F6nv/view?usp=sharing](https://drive.google.com/file/d/1K8_AFufKnPwDO1M6NHu8o6TF6gM4F6nv/view?usp=sharing)
@brianjohnson5972 Here's the command output

**Comment by brianjohnson5972** [comment]
Looks like the nodeos instances are running but the script isn't finding them using pgrep, but not sure why.  Please run:
```
tests/nodeos_run_test.py -v --sanity-test --clean-run --dump-error-detail --leave-running --keep-logs
```

from your build directory and save the output and then when it completes, run (if you are running macos):
```
pgrep -fl nodeos
```

or for all other platforms run:
```
pgrep -a nodeos
```
and post the output for both here.

**Comment by JingyuQian** [comment]
@brianjohnson5972 [https://drive.google.com/file/d/1_JLQe4kbqgROpHmqbWe_8svRWGh2ZBxA/view?usp=sharing](https://drive.google.com/file/d/1_JLQe4kbqgROpHmqbWe_8svRWGh2ZBxA/view?usp=sharing) This is the output for the first command.

For the **pgrep** command, the output is the following:

4617 programs/nodeos/nodeos --max-transaction-time -1 --abi-serializer-max-time-ms 990000 --filter-on * --p2p-max-nodes-per-host 1 --contracts-console --config-dir etc/eosio/node_bios --data-dir var/lib/node_bios --genesis-json etc/eosio/node_bios/genesis.json --genesis-timestamp 2018-10-29T20:26:55.748
4618 programs/nodeos/nodeos --max-transaction-time -1 --abi-serializer-max-time-ms 990000 --filter-on * --p2p-max-nodes-per-host 1 --contracts-console --config-dir etc/eosio/node_00 --data-dir var/lib/node_00 --genesis-json etc/eosio/node_00/genesis.json --genesis-timestamp 2018-10-29T20:26:55.748

**Comment by JingyuQian** [comment]
Hi, after I ran the commands I saw the output was **Debian**.

I wonder if this has anything to do with the Anaconda python I previously installed? Cause if I switch to system default python, the output is **('Ubuntu', '16.04', 'xenial')**.

If I uninstall Anaconda, and ran again:
`tests/nodeos_run_test.py -v --sanity-test --clean-run --dump-error-detail --leave-running --keep-logs`
It gives out sth like this:
********
$ tests/nodeos_run_test.py -v --sanity-test --clean-run --dump-error-detail --leave-running --keep-logs
 BEGIN
 UTC time: 2018-10-29 21:44:21.394096
 EOS Client version: f9a3d023
 Processor: x86_64
 OS name: Linux-4.15.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
SERVER: localhost
PORT: 8888
 cmd: programs/eosio-launcher/eosio-launcher -k 9
 cmd: pkill -9 nodeos
Stand up cluster
  Checking if port 8888 is available.
  Checking if port 8889 is available.
 cmd: programs/eosio-launcher/eosio-launcher -p 1 -n 1 -d 1 -i 2018-10-29T21:44:21.433 -f --p2p-plugin net --nodeos --max-transaction-time -1 --abi-serializer-max-time-ms 990000 --filter-on * --p2p-max-nodes-per-host 1 --contracts-console --max-block-cpu-usage 160000000 --max-transaction-cpu-usage 150000000 --shape mesh
launching bios
spawning child, programs/nodeos/nodeos --max-transaction-time -1 --abi-serializer-max-time-ms 990000 --filter-on * --p2p-max-nodes-per-host 1 --contracts-console  --config-dir etc/eosio/node_bios --data-dir var/lib/node_bios --genesis-json etc/eosio/node_bios/genesis.json --genesis-timestamp 2018-10-29T21:44:21.433
launching testnet_00
spawning child, programs/nodeos/nodeos --max-transaction-time -1 --abi-serializer-max-time-ms 990000 --filter-on * --p2p-max-nodes-per-host 1 --contracts-console  --config-dir etc/eosio/node_00 --data-dir var/lib/node_00 --genesis-json etc/eosio/node_00/genesis.json --genesis-timestamp 2018-10-29T21:44:21.433

run 'bash bios_boot.sh' to kick off delegated block production

cmd: pgrep -a nodeos
ERROR: call of "pgrep -a nodeos" failed. 
cmd: sleep 3 seconds, remaining time: 89 seconds
********
and **pgrep -a nodeos** gives me nothing.

I was never able to get the tests to pass. I installed the fresh OS days ago, so there are only some development tools inside the system.

**Comment by brianjohnson5972** [comment]
@JingyuQian This looks like an issue that you need to resolve on your machine.  Once you get your python version cleaned up, if you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by JingyuQian** [comment]
@brianjohnson5972 After I reinstalled Ubuntu I passed all the tests. Thanks for the help!
