### ISSUE TITLE
where can i get eosio.bios.wasm when i use "apt install xx.deb"?

### ISSUE THREAD

**Issue by Mojicode** [EOSIO/eos#6159]
I install eosio by using "apt install ./eosio-1.4.1.ubuntu-16.04-x86_64.deb",but I can't find eosio.bios.wasm and other base contract.

**Comment by jgiszczak** [comment]
Get the contracts from the eosio.contracts repository [here](https://github.com/EOSIO/eosio.contracts).  Compile them with the EOS.IO Contract Development Toolkit, available as a pre-built package [here](https://github.com/EOSIO/eosio.cdt/releases).
