### ISSUE TITLE
How to get ram price in eos contract

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#6162]
Used in eosiocpp
```
asset zion_contract::buyrambytes(uint32_t bytes) {
  eosiosystem::rammarket market(N(eosio), N(eosio));
  auto itr = market.find(S(4, RAMCORE));
  eosio_assert(itr != market.end(), "RAMCORE market not found");
  auto tmp = *itr;
  return tmp.convert(asset(bytes, S(0, RAM)), CORE_SYMBOL);
}
```
How to get it in eosio-cpp? I want to calculate in the contract how much ram can be purchased by the current eos.

**Comment by jgiszczak** [comment]
You may gain access to the rammarket using the same typedef used by the system contract, found [here](https://github.com/EOSIO/eosio.contracts/blob/1b8574172ca61f725545b14b5edddc174e4d0ce0/eosio.system/include/eosio.system/exchange_state.hpp#L38): `typedef eosio::multi_index< "rammarket"_n, exchange_state > rammarket;`.

If you wish to continue using `#include <eosio.system/exchange_state.hpp>`, you'll need to provide `eosio-cpp` with a `-I eosio.contracts/eosio.system/include` argument to your copy of the eosio.contracts repository, prefixing my sample path with whatever is appropriate for your environment.
