### ISSUE TITLE
Please Fix Poor "Getting Started" Tutorial

### ISSUE THREAD

**Issue by hackingbeauty** [EOSIO/eos#6166]
Hello,

I've been following the "Getting Started" tutorial on developers.eos.io and it's bad.  There are errors, the right context is not provided, and it's been frustrating other developers (not just myself).

One example error is this command:

```docker pull eosio/eos::v1.4.0```

There is an extra colon in that command.  The correct command that worked for me is this:

```docker pull eosio/eos:v1.4.0```

Can the EOS team please verify that the Getting Started tutorial actually works?  It's wasting a lot of dev time and we're getting frustrated.

Thanks!

**Comment by kesar** [comment]
Documentation is based on https://readme.io/ . You can also contribute to fix those issues adding suggestions there 👍 

<img width="679" alt="screenshot 2018-10-27 at 14 10 00" src="https://user-images.githubusercontent.com/1288106/47603867-08ef1780-d9f2-11e8-91fe-0af9e8770b28.png">

**Comment by andriantolie** [comment]
Thanks for the feedback. Just checked the developers.eos.io, and seems like the developer relation team has incorporated the change.
