### ISSUE TITLE
 if block action already completed, the table in RPC node is also completed at the same time? is there any latency?

### ISSUE THREAD

**Issue by whiteblackbee** [EOSIO/eos#6169]
we have a question that if block action already completed, the table in RPC node is also completed at the same time? is there any latency?
x. action change 1=>2, the table we read is already =2?

**Comment by wanderingbort** [comment]
The consistency of reading tables in RPC is at the block level or transaction level depending on the mode of operation.  In either case if the RPC indicates that the block of transaction is valid/applied then it's side effects, including mutating table data should be present.  

Some operators will provide RPC access load balanced between several nodes.  In this case, read consistency may appear less strong if requests are serviced by different actual nodes and the operators have not taken care to provide it through sticky sessions or some other device.
