### ISSUE TITLE
what is the difference at _n and N(),INLINE_ACTION_SENDER and action.send()

### ISSUE THREAD

**Issue by wangyilin1987** [EOSIO/eos#6172]
1.`N(active) <-> "active"_n <-> "active"_n.value`
2.`INLINE_ACTION_SENDER(eosio::token, issue)( N(eosio.token), {{N(eosio),N(active)}},
                                                    {N(eosio), asset(new_tokens), std::string("issue tokens for producer pay and savings")} );
                                                    
 action(
            permission_level{ itr->base.contract, N(active) },
            itr->base.contract, N(transfer),
            std::make_tuple(itr->base.contract, t.from, token_out, t.memo)
    ).send();`

what is the difference ,there is do same thing?no documentation was found.

**Comment by andriantolie** [comment]
1. N(active) and "active"_n.value is the same, it converts `string` into base32 string representation of unsigned 64-bit integer. However, the former is deprecated now and the latter is the new standard in the latest eosio.cdt. "active"_n is a little bit different, it is converting `string` into a `name` object.

2. In the end, both of them results in the same thing. INLINE_ACTION_SENDER, however, will create a tuple that is based on the arguments of the contract function that you pass. While std::make_tuple will implicitly determine the type of the tuple.
