### ISSUE TITLE
Can't to create new account

### ISSUE THREAD

**Issue by SavostinVladimir** [EOSIO/eos#6175]
I have imported private key, and my default wallet is unlocked, but when I try to create a new account I get error:
![screenshot from 2018-10-29 16-30-34](https://user-images.githubusercontent.com/27097483/47644317-00384600-db98-11e8-92d9-70da4833acd9.png)

**Comment by SavostinVladimir** [comment]
![screenshot from 2018-10-29 16-50-06](https://user-images.githubusercontent.com/27097483/47645312-d46a8f80-db9a-11e8-8aa9-c70e34680e0a.png)
and what was happened when I tried to create a hello account for my first smart contract

**Comment by SavostinVladimir** [comment]
I've just created account, but not in mainnet...
if i run
`nodeos --data-dir . --config-dir . -e --producer eosio`
it is start new blocjchain and it is able to create a new accounts... but how can I do it on mainnet???

**Comment by yashbhavsar007** [comment]
@SavostinVladimir  have you imported private keys of eosio account ? if not then must do it.

**Comment by jgiszczak** [comment]
Use an account creation service to get an account on mainnet.  New accounts are always created by existing accounts and you don't control any existing account, so you can not create an account on mainnet.  Once you use a service to get and fund an account, you may use it to create further new accounts yourself.
