### ISSUE TITLE
'unable to find key' when I call push transaction use RPC

### ISSUE THREAD

**Issue by xxxxll** [EOSIO/eos#6176]
1. **abi_json_to_bin**
`curl --request POST --data '{"code":"eosio.token", "action":"transfer", "args":{"from":"alice","to":"bob","quantity":"1.0000 EOS","memo":"memo"}}' --url http://127.0.0.1:7777/v1/chain/abi_json_to_bin`
get the 'binargs'
2. **get_info**
`curl  --request   --url http://127.0.0.1:7777/v1/chain/get_info`
get the 'head_block_num'
3. **get_block**
`curl  --request  POST --data '{"block_num_or_id":${head_block_num}}'  --url http://127.0.0.1:7777/v1/chain/get_block`
get the 'timestamp' 'block_num' and 'ref_block_prefix'
4. **unlock**
`curl  --request  POST --data '["default", "${wallet_password}"]'  --url http://0.0.0.0:5555/v1/wallet/unlock`
unlock the wallet
5. **require_keys**
`curl  --request  POST --data '{"available_keys":["EOS6C3iqHU1h85rir88sWRcbvdbLvTcuHrhQmejyZpyfXvQzDub49","EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"],"transaction":{"actions":[{"account":"eosio.token","authorization":[{"actor":"alice","permission":"active"}],"data":"00000000001aa36a0000000000000e3d102700000000000004454f53000000001163726561746564206279206e6f70726f6d","name":"transfer"}],"context_free_actions":[],"context_free_data":[],"delay_sec":0,"expiration":"2018-10-27T10:57:53.500","max_kcpu_usage":0,"max_net_usage_words":0,"ref_block_num":2055,"ref_block_prefix":3089521551,"signatures":[]}}'  --url http://127.0.0.1:7777/v1/chain/get_required_keys`
get the public key of alice   'EOS6C3iqHU1h85rir88sWRcbvdbLvTcuHrhQmejyZpyfXvQzDub49'
6. **sign the transaction**
`curl  --request  POST --data '[{"ref_block_num":20010,"ref_block_prefix":525334628,"expiration":"2018-10-29T06:41:08.000","actions":[{"account":"eosio.token","name":"transfer","authorization":[{"actor":"alice", "permission": "active"}],"data":"0000000000855c340000000000000e3d102700000000000004454f53000000001163726561746564206279206e6f70726f6d"}],"signatures":[]},["EOS6C3iqHU1h85rir88sWRcbvdbLvTcuHrhQmejyZpyfXvQzDub49"],"cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f"]'  --url http://0.0.0.0:5555/v1/wallet/sign_transaction`
get the signatures
7. **send transaction**
`curl  --request  POST --data '{"compression":"none","transaction":{"expiration":"2018-10-29T06:41:08.000","ref_block_num":20010,"ref_block_prefix":525334628,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio.token","name":"transfer","authorization":[{"actor":"alice","permission":"active"}],"data":"0000000000855c340000000000000e3d102700000000000004454f53000000001163726561746564206279206e6f70726f6d"}],"transaction_extensions":[]},"signatures":["SIG_K1_Kj4NctkNMMjVN2WNqLFdh8iS45sefm16kKVfYUvuNAYwb92MLz7Pgf3rtdaonuJbTb5PS9DTum7V1NQJfhjg3okA7VXGge"]}'  --url http://127.0.0.1:7777/v1/chain/push_transaction `

and this is the error:
```
error 2018-10-29T10:04:18.667 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: unable to find key
error 2018-10-29T10:04:18.668 thread-0  http_plugin.cpp:580           handle_exception     ] FC Exception encountered while processing chain.push_transaction
debug 2018-10-29T10:04:18.668 thread-0  http_plugin.cpp:581           handle_exception     ] Exception Details: 3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
assertion failure with message: unable to find key
    {"s":"unable to find key"}
    thread-0  wasm_interface.cpp:934 eosio_assert
pending console output:
    {"console":""}
    thread-0  apply_context.cpp:72 exec_one
```

and this is the public key of alice:

```
> cleos get account alice
permissions:
     owner     1:    1 EOS6C3iqHU1h85rir88sWRcbvdbLvTcuHrhQmejyZpyfXvQzDub49
     active     1:    1 EOS6C3iqHU1h85rir88sWRcbvdbLvTcuHrhQmejyZpyfXvQzDub49
```

**Comment by jgiszczak** [comment]
The key in question is the entry in a table, not an encryption key.

Going by the account names you are using, you are attempting this transfer on a private testnet.  Be sure you have completed bootstrapping your testnet, including installing the `eosio.token` contract, and creating and issuing an EOS token.  If you did not customize your core symbol during the build to EOS, create and issue the SYS token and revise your test transaction to transfer `"1.0000 SYS"` instead of `"1.0000 EOS"`.

**Comment by xxxxll** [comment]
> The key in question is the entry in a table, not an encryption key.
> 
> Going by the account names you are using, you are attempting this transfer on a private testnet. Be sure you have completed bootstrapping your testnet, including installing the `eosio.token` contract, and creating and issuing an EOS token. If you did not customize your core symbol during the build to EOS, create and issue the SYS token and revise your test transaction to transfer `"1.0000 SYS"` instead of `"1.0000 EOS"`.

@jgiszczak Thanks. the key is should be `"1.0000 SYS"` not  `"1.0000 EOS"`.
