### ISSUE TITLE
"Error 3090005: Irrelevant authority included" for @random authority

### ISSUE THREAD

**Issue by reedteam** [EOSIO/eos#6180]
I got an error "Error 3090005: Irrelevant authority included Please remove the unnecessary authority from your action!" when the command `cleos push action eosbetdice11 resolvebet <...> -p eosbetcasino@random` is executed. The @random authority is already included in the code: https://gitlab.com/EOSBetCasino/eosbetdice_public/blob/master/EOSBetDice.cpp#L207.

Why is the @random authority irrelevant?

Here is the summary of account `eosbetcasino`:
```
permissions: 
 owner     1:    1 EOS5hKKeeY1w89SZgAyZgFGZjTNcC9PwHHQjBgX2geCDungtF3wQu
    active     1:    1 EOS5hKKeeY1w89SZgAyZgFGZjTNcC9PwHHQjBgX2geCDungtF3wQu
    random     1:    1 EOS5hKKeeY1w89SZgAyZgFGZjTNcC9PwHHQjBgX2geCDungtF3wQu
memory: 
 quota:       unlimited  used:      2.99 KiB  
```

**Comment by andriantolie** [comment]
I suspect that you haven't linked your `random` authority with the `resolvebet` action of `eosbetdice11` in this case. When you set up a new authority, it's not authorized to satisfy any action until it is linked. To do so, try this command
`cleos set action permission eosbetcasino eosbetdice11 resolvebet random`

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
