### ISSUE TITLE
get CORE_SYMBOL in contract

### ISSUE THREAD

**Issue by young-mu** [EOSIO/eos#6182]
We know that the default `CORE_SYMBOL` is `SYS` and we can designate customized `CORE_SYMBOL` like `ABC` by shell environment for our own EOS test net. 

For contract developing, we also have this demand to get the real CORE_SYMBOL for certain EOS net. However, I found the CORE_SYMBOL is always `SYS` for any EOS net. 

I also found the header file is located in `build/contracts/eosiolib/core_symbol.hpp` under EOS project directory. The contents are below.

```
/** @file
 *    @copyright defined in eos/LICENSE.txt
 *
 * \warning This file is machine generated. DO NOT EDIT.  See core_symbol.hpp.in for changes.
 */

#define CORE_SYMBOL S(4,SYS)
```

**Comment by andriantolie** [comment]
The eosiolib development now has moved to https://github.com/EOSIO/eosio.cdt. You can assume the files inside contracts/ folder of EOSIO/eos is outdated.

With the release of latest eosio.cdt, eosiolib/core_symbol.hpp is removed and it's the responsibility of the contract owner to specify the symbol (check this out https://github.com/EOSIO/eosio.cdt)
