### ISSUE TITLE
Asset's amount and symbol should be separated with space

### ISSUE THREAD

**Issue by tvrc4m** [EOSIO/eos#6183]
![image](https://user-images.githubusercontent.com/2194937/47708711-9b4d2080-dc69-11e8-81c5-b175b2392113.png)

**Comment by boy-good** [comment]
it's right.

**Comment by tvrc4m** [comment]
> it's right.

the amount and symbol has the space.

**Comment by boy-good** [comment]
@tvrc4m 你这个句命令是自己敲的还是复制黏贴的

**Comment by tvrc4m** [comment]
自己敲的
cl push action eosio.token create '["eosio","100000000.0000 EOS"]'

**Comment by boy-good** [comment]
@tvrc4m 把精度去掉试试 我是直接 100 EOS，没有报错

**Comment by tvrc4m** [comment]
> @tvrc4m 把精度去掉试试 我是直接 100 EOS，没有报错

不行，发币必须带小位数

**Comment by taokayan** [comment]
is your ```cl``` command an alias to ```cleos```? try to directly call "cleos". Please ask in eosio.stackexchange.com if you have further questions.

**Comment by tvrc4m** [comment]
> is your `cl` command an alias to `cleos`? try to directly call "cleos". Please ask in eosio.stackexchange.com if you have further questions.

just like this.
alias cl='docker-compose  -f /data/docker-compose/eos/docker-compose.yml exec keosd /opt/eosio/bin/cleos -u http://nodeosd:8888 --wallet-url http://localhost:8900'

before it's ok.suddenly it's to bad.

**Comment by jgiszczak** [comment]
The recommended cleos alias for use with docker is `alias cleos='docker exec -it eosio /opt/eosio/bin/cleos --url http://127.0.0.1:7777 --wallet-url http://127.0.0.1:5555'` after starting up the EOS.IO docker image with 
```bash
docker run --name eosio \
  --publish 7777:7777 \
  --publish 127.0.0.1:5555:5555 \
  --volume CONTRACTS_DIR:CONTRACTS_DIR \
  --detach \
  eosio/eos:v1.4.2 \
  /bin/bash -c \
  "keosd --http-server-address=0.0.0.0:5555 & exec nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:7777 --access-control-allow-origin=* --contracts-console --http-validate-host=false --filter-on='*'"
```
substituting appropriate path names for `CONTRACTS_DIR`.  See the [documentation](https://developers.eos.io/eosio-home/docs/getting-the-software#section-step-4-aliasing-cleos) for details.  Consult the docker documentation for how to adapt the above steps to `docker-compose`.
