### ISSUE TITLE
3050003!!ERRPR:assertion failure with message: attempt to add asset with different symbol

### ISSUE THREAD

**Issue by boy-good** [EOSIO/eos#6184]
![image](https://user-images.githubusercontent.com/39320533/47709498-53c79400-dc6b-11e8-8831-1f39dd3bb47f.png)

How to reslove this error?Please help me.Thanks very much

**Comment by boy-good** [comment]
{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: attempt to add asset with different symbol","file":"wasm_interface.cpp","line_number":934,"method":"eosio_assert"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":72,"method":"exec_one"}]}}

**Comment by wanderingbort** [comment]
do you have the source code for the contract deployed on `eosdevtest11` ? that assert is triggered when you try to add to separated tokens together.  For instance "1.0000 EOS" + "1.0000 SYS".  It is likely that something about the contract operations is violating this restriction.

**Comment by boy-good** [comment]
@wanderingbort  this is my source code
![image](https://user-images.githubusercontent.com/39320533/47759113-0ee24280-dce9-11e8-9e29-1ede1be0c80a.png)
I want to use eosio.token to transfer in my contract. How to do best?

**Comment by jgiszczak** [comment]
Be sure your `eos_balance` member of the account record was initialized with the correct symbol type.

If you still have the problem and wish to discuss further, please post it in [https://eosio.stackexchange.com](https://eosio.stackexchange.com).  To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right
place for any technical support discussions. Thanks!
