### ISSUE TITLE
v1.4.1 has broken unit test.

### ISSUE THREAD

**Issue by VasiliyKuznetsov** [EOSIO/eos#6186]
Hello!

```
% git checkout master
% ./eosio_build.sh
% build/unittests/unit_test -t wasm_tests/weighted_cpu_limit_tests
```

    3080004 tx_cpu_usage_exceeded: Transaction exceeded the current CPU usage limit imposed on the transaction billed CPU time (474 us) is greater than the maximum billable CPU time for the transaction (0 us)
        {"billed":474,"billable":0}
        thread-0  transaction_context.cpp:520 validate_cpu_usage_to_bill transaction_header: {"expiration":"2020-01-01T00:00:13","ref_block_num":15,"ref_block_prefix":132319163,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0}, billed_cpu_time_us: 0
        {"header":{"expiration":"2020-01-01T00:00:13","ref_block_num":15,"ref_block_prefix":132319163,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0},"billed":0}
        thread-0  tester.cpp:354 push_transaction rethrow
        {}
        thread-0  wasm_tests.cpp:651 test_method

    eos/unittests/main.cpp(15): fatal error: in "wasm_tests/weighted_cpu_limit_tests": Caught Unexpected Exception

What is wrong and what can i do for resolve this issue?

Thank you!

**Comment by wanderingbort** [comment]
That unit test has been broken since the introduction of leeway cpu.  the set of official tests can be accessed using `ctest` instead of directly accessing the `unit_test` binary after a build.
