### ISSUE TITLE
Declaring a static variable in a contract causes WASM exception when setting the compiled contract

### ISSUE THREAD

**Issue by jchung00** [EOSIO/eos#6188]
Can you not declare static variables in the class?

**Comment by spoonincode** [comment]
We really need to see at least the exception that you're getting and preferably a code sample

**Comment by jchung00** [comment]
This is a piece of code that I believe would cause the same problem. The only exception I got was "`WASM exception`" when setting the compiled contract.
```
namespace hello{
  class foo : public eosio::foo {
    public:
     /* constructor */
     //@abi action
      void hello();
    private:
    static uint32_t x;
    void incrX(){
      x++;
    }
  };
  /* Define constructor */
  void hello(){
    incrX();
  }
};

**Comment by taokayan** [comment]
I don't think static member is supported in EOS. Please ask in eosio.stackexchange.com if you have further questions.

**Comment by spoonincode** [comment]
No response in months, closing
