### ISSUE TITLE
eos --hard-replay is so slow

### ISSUE THREAD

**Issue by bitcodernull** [EOSIO/eos#6190]
if i don't save old eos chain data, how can i speed up the replay

it is so slowly now.

**Comment by jgiszczak** [comment]
The major EOS.IO-based networks generally provide a block log downloadable from some service using traditional protocols.  This can be faster than live syncing.

If you still have the problem and wish to discuss further, please post it in [https://eosio.stackexchange.com](https://eosio.stackexchange.com). To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by matthewdarwin** [comment]
If you're on mainnet, make sure you have lots of RAM (256GB at least), or something near RAM (optane)
