### ISSUE TITLE
Duplicate transactions in mongodb

### ISSUE THREAD

**Issue by littleLj** [EOSIO/eos#6192]
I replay the transactions to mongo ,  duplicate transactions  is in mongo when the block height  reaches to 23 000 000 .
transaction id  d52a670d4127f986f6f81b356b6c72dd6381db312df96ad247d078974e9cae30.
13c12310f349bba82b3b3d9c128aa961be4e68ec3aa9934a8745eaada0c28392.
and the transaction content is  strange.

**Comment by littleLj** [comment]
d5b8ca35b806855f51769baab1024b0e6fdae3d65fe0b1394e34d432937222c4   
this transaction trace is so odd.

**Comment by firesWu** [comment]
Did you set `read-mode = read-only `in `config.ini` ?

**Comment by raymondnuaa** [comment]
The duplicate transaction is not related with block height. Actually the mongodb is written twice:
1) transaction is collected by CLI push or received from network broadcast
2) when producing block

**Comment by littleLj** [comment]
> Did you set `read-mode = read-only `in `config.ini` ?

read-mode = speculative .

**Comment by littleLj** [comment]
`# Database read mode ("speculative", "head", or "read-only").
# In "speculative" mode database contains changes done up to the head block plus changes made by transactions not yet included to the blockchain.
# In "head" mode database contains changes done up to the current head block.
# In "read-only" mode database contains incoming block changes but no speculative transaction processing.
#  (eosio::chain_plugin)
read-mode = speculative

# Chain validation mode ("full" or "light").
# In "full" mode all incoming blocks will be fully validated.
# In "light" mode all incoming blocks headers will be fully validated; transactions in those validated blocks will be trusted
#  (eosio::chain_plugin)
validation-mode = full
`

**Comment by firesWu** [comment]
> > Did you set `read-mode = read-only `in `config.ini` ?
> 
> read-mode = speculative .
> validation-mode = full.

if you have not set `read-mode = read-only`,  `accepted_transaction` and `applied_transaction` will emit twice, so that it has duplicate data.

**Comment by littleLj** [comment]
> > > Did you set `read-mode = read-only `in `config.ini` ?
> > 
> > 
> > read-mode = speculative .
> > validation-mode = full.
> 
> if you have not set `read-mode = read-only`, `accepted_transaction` and `applied_transaction` will emit twice, so that it has duplicate data.

just few  transactions  emit  twice .
