### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by colinkim** [EOSIO/eos#6193]
I made success compile by ./eosio_build.sh but I forgot it . I made configured manually build enviroment. after that I realized was wrong and tried compile by ./eosio_build.sh.
but I rand  ./eosio_build.sh fail build and following error occurred 

/Users/kimcy/dev/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:25:10: fatal error: [ 94%] Linking CXX static library libchain_plugin.a
[ 94%] Built target chain_plugin
[ 94%] Building CXX object unittests/CMakeFiles/unit_test.dir/block_timestamp_tests.cpp.o
[ 94%] Linking CXX executable eosio-blocklog
[ 94%] Built target eosio-blocklog
[ 94%] Building CXX object unittests/CMakeFiles/unit_test.dir/bootseq_tests.cpp.o
Scanning dependencies of target wallet_api_plugin
[ 94%] Building CXX object plugins/wallet_api_plugin/CMakeFiles/wallet_api_plugin.dir/wallet_api_plugin.cpp.o
Scanning dependencies of target txn_test_gen_plugin
[ 94%] Building CXX object plugins/txn_test_gen_plugin/CMakeFiles/txn_test_gen_plugin.dir/txn_test_gen_plugin.cpp.o
Scanning dependencies of target db_size_api_plugin
[ 94%] Building CXX object plugins/db_size_api_plugin/CMakeFiles/db_size_api_plugin.dir/db_size_api_plugin.cpp.o
Scanning dependencies of target mongo_db_plugin
[ 94%] Building CXX object plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/mongo_db_plugin.cpp.o
/Users/kimcy/dev/eos/plugins/mongo_db_plugin/mongo_db_plugin.cpp:25:10: fatal error: 'bsoncxx/builder/basic/kvp.hpp' file
      not found
#include <bsoncxx/builder/basic/kvp.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/mongo_db_plugin.cpp.o] Error 1
make[1]: *** [plugins/mongo_db_plugin/CMakeFiles/mongo_db_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

I want to compile  ./eosio_build.sh but I do not know how to fix it.

**Comment by jgiszczak** [comment]
You will need to uninstall/reinstall/repair the mongo-cxx-driver library installation, which is installed via a CMake installation script.  You will need to search for how to do this, as such support is out of scope here.

To keep things organized, Github issues are intended for bugs reporting and features tracking, and [Stack Exchange](https://eosio.stackexchange.com) is the right place for any technical support discussions. Thanks!

**Comment by gituser** [comment]
For those who are getting similar error and don't want to use stock `eosio_build.sh` because it requires root privileges and massively uses sudo all over and messing up your /usr/local directory.

1. Install boost into `BOOST_DIR` defined in the config file
2. Install required dependencies into `DEPS_DIR`
3. Note this build script replaces `SYS` name of the native token with `EOS` name

```bash
#!/bin/bash
VER=$(git describe --tags)
CORE_SYMBOL_NAME=EOS #default is SYS
CMAKE_BUILD_TYPE=Release

# update git submodules
git submodule update --init --recursive

export DEPS_DIR=/home/build/eos/deps
export BOOST_ROOT=/home/build/boost/installed
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/home/build/eos/deps/lib/pkgconfig

C_COMPILER=clang-4.0
CXX_COMPILER=clang++-4.0

# cleanup old build directory
rm -rf build

mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=$DEPS_DIR -DCMAKE_CXX_COMPILER="${CXX_COMPILER}" -DCMAKE_C_COMPILER="${C_COMPILER}" -D Secp256k1_INCLUDE_DIR=$DEPS_DIR/include -D Secp256k1_LIBRARY=$DEPS_DIR/lib/libsecp256k1.a -D Secp256k1_ROOT_DIR=$DEPS_DIR -D CORE_SYMBOL_NAME="${CORE_SYMBOL_NAME}" -D CMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" -DBUILD_MONGO_DB_PLUGIN=true ..

if [ "$?" != 0 ]; then
   echo "[-] EOS cmake failed!"
   exit 1
fi

make -j8

if [ "$?" == 0 ]; then
   cd ..
   mkdir ../$VER
   find build/programs -type f -executable -exec cp -prv {} ../$VER/ \;
   rm -rf ../current
   ln -sf $VER ../current
else
   echo "[-] EOS build failed!"
fi
```
