### ISSUE TITLE
last irreversible block num doesn't change when one of three producers died

### ISSUE THREAD

**Issue by tekpig** [EOSIO/eos#6194]
I do a test in our private network. Three nodes are running and they're all set as producers by the function set producers in the system contract bios.
When I stop one node, the other two alive nodes are still producing blocks, but last irreversible block number doesn't grow.
I dug into the codes and found that because "block_header_state::calc_dpos_last_irreversible()" always return same result.
We only have 3 nodes, 2 nodes are alive, the blocks can get 2/3 agreement theoretically. Why does the irreversible block number not grow?

**Comment by tekpig** [comment]
I have found the root cause.

**Comment by brianjohnson5972** [comment]
(In case someone finds this and wants the answer)
It needs to have 2/3 + 1 producers to reach consensus, so with 3 producers you can only have consensus with all 3 producers.  If you had 4 producers you would need 3 ... for 21 you need 15.

**Comment by anlebcoder** [comment]
Hi:

When BP died(<2/3), the irreversible height did not increase for a period of time. For example, stop for 10 minutes

Ten minutes later, we revived BP（>2/3） and the irreversible height began to grow.

You'll find that we're here(`on_applied_irreversible_block`) to find that the irreversible heights are about 10 minutes slower to receive messages.


```
 my->irreversible_block_connection.emplace(
               chain.irreversible_block.connect( [&]( const chain::block_state_ptr& bs ) {
                  my->applied_irreversible_block( bs );
               } ));
```
