### ISSUE TITLE
[mongo_db_plugin] Synchronization to the Mongo database, how to choose the key, do you have any relevant document reference?

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#6198]
Synchronization to the Mongo database, how to choose the key, do you have any relevant document reference? I currently find that the data on the EOS chain is stored in a library with two ready-made plug-ins, MySQL and Mongo, and MySQL has many private versions. I don't know how to choose, which is better.

**Comment by jgiszczak** [comment]
The choice of database plugin to use is a matter of personal preference.

To keep things organized, Github issues are intended for bugs reporting and features tracking.  If you would like to start a community discussion regarding the pros and cons of the various database plugins, [Stack Exchange](https://eosio.stackexchange.com) is the right place to begin. Thanks!
