### ISSUE TITLE
{"msg":"unknown key"} on trying to deploy the currency contract 

### ISSUE THREAD

**Issue by sivachaitanya** [EOSIO/eos#620]
I was following the steps described in - https://github.com/EOSIO/eos#smartcontractexample
Everything happening smoothly until I ran "./eosc set contract currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi" which throwed me unknown key error. I tried running eosd with --resync-blockchain and --skip-transaction-signatures switches but facing the same result, Can somebody help me debug the issue ?

Log - 

root@cea64a3655d3:/home/eos/build/programs/eosc# ./eosc set contract currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi
Reading WAST...
Assembling WASM...
Publishing contract...
413166ms thread-0   main.cpp:1101                 main                 ] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error
: unknown key

    {"msg":"unknown key"}
    thread-0  httpc.cpp:113 call

    {"server":"localhost","port":8888,"path":"/v1/chain/get_required_keys","postdata":{"transaction":{"refBlockNum":0,"refBlockPrefix":0,"expiration":"2017-03-30T12:00:01","scope":["currency","eos"],"readscope":[],"messages":[{"code":"eos","type":"setcode","authorization":[{"account":"currency","permission":"active"}],"data":"0000001e4d75af460000d8120061736d0100000001390a60037e7e7f017f60047e7e7f7f017f60017e0060057e7e7e7f7f017f60027f7f0060027f7f017f60027e7f0060017f0060000060027e7e0002760703656e7606617373657274000403656e76086c6f61645f693634000303656e760b726561644d657373616765000503656e760a72656d6f76655f693634000003656e760b7265717569726541757468000203656e760d726571756972654e6f74696365000203656e760973746f72655f6936340001030504060708090404017000000503010001077e05066d656d6f727902002a5f5a4e3863757272656e6379313273746f72654163636f756e744579524b4e535f374163636f756e74450007355f5a4e3863757272656e637932336170706c795f63757272656e63795f7472616e7366657245524b4e535f385472616e7366657245000804696e69740009056170706c79000a0aba0c043400024020012903084200510d0020004280808080f2a9d388322001411010061a0f0b20004280808080f2a9d38832200110031a0bc40504017e027f047e017f4100410028020441206b2208360204200029030021052000290308100520051005200029030010042000290300210142002105423b2104411021034200210603400240024002400240024020054206560d0020032c00002202419f7f6a41ff017141194b0d01200241a5016a21020c020b420021072005420b580d020c030b200241d0016a41002002414f6a41ff01714105491b21020b2002ad42388642388721070b2007421f83200442ffffffff0f838621070b200341016a2103200542017c2105200720068421062004427b7c2204427a520d000b420021052008420037031820082006370310200142808080f0d1a9ddd7c6004280808080f2a9d38832200841106a411010011a200041086a2903002101423b2104411021034200210603400240024002400240024020054206560d0020032c00002202419f7f6a41ff017141194b0d01200241a5016a21020c020b420021072005420b580d020c030b200241d0016a41002002414f6a41ff01714105491b21020b2002ad42388642388721070b2007421f83200442ffffffff0f838621070b200341016a2103200542017c2105200720068421062004427b7c2204427a520d000b2008200637030020084200370308200142808080f0d1a9ddd7c6004280808080f2a9d388322008411010011a200841186a220329030020002903105a4120100020032003290300200029031022057d370300200520082903087c20055a41d00010002008200829030820002903107c370308200029030021050240024020032903004200510d0020054280808080f2a9d38832200841106a411010061a0c010b20054280808080f2a9d38832200841106a10031a0b200041086a290300210502400240200841086a2903004200510d0020054280808080f2a9d388322008411010061a0c010b20054280808080f2a9d38832200810031a0b4100200841206a3602040b970303027f057e017f4100410028020441106b220736020442002103423b210241800121014200210403400240024002400240024020034207560d0020012c00002200419f7f6a41ff017141194b0d01200041a5016a21000c020b420021052003420b580d020c030b200041d0016a41002000414f6a41ff01714105491b21000b2000ad42388642388721050b2005421f83200242ffffffff0f838621050b200141016a2101200342017c2103200520048421042002427b7c2202427a520d000b42002103423b2102411021014200210603400240024002400240024020034206560d0020012c00002200419f7f6a41ff017141194b0d01200041a5016a21000c020b420021052003420b580d020c030b200041d0016a41002000414f6a41ff01714105491b21000b2000ad42388642388721050b2005421f83200242ffffffff0f838621050b200141016a2101200342017c2103200520068421062002427b7c2202427a520d000b2007428094ebdc033703082007200637030020044280808080f2a9d388322007411010061a4100200741106a3602040ba30303027f047e017f4100410028020441206b220836020442002105423b210441800121034200210603400240024002400240024020054207560d0020032c00002202419f7f6a41ff017141194b0d01200241a5016a21020c020b420021072005420b580d020c030b200241d0016a41002002414f6a41ff01714105491b21020b2002ad42388642388721070b2007421f83200442ffffffff0f838621070b200341016a2103200542017c2105200720068421062004427b7c2204427a520d000b024020062000520d0042002105423b210441900121034200210603400240024002400240024020054207560d0020032c00002202419f7f6a41ff017141194b0d01200241a5016a21020c020b420021072005420b580d020c030b200241d0016a41002002414f6a41ff01714105491b21020b2002ad42388642388721070b2007421f83200442ffffffff0f838621070b200341016a2103200542017c2105200720068421062004427b7c2204427a520d000b20062001520d0020084200370318200841086a4118100241174b41a0011000200841086a10080b4100200841206a3602040b0bb601070041040b04c04000000041100b086163636f756e74000041200b2c696e746567657220756e646572666c6f77207375627472616374696e6720746f6b656e2062616c616e6365000041d0000b26696e7465676572206f766572666c6f7720616464696e6720746f6b656e2062616c616e636500004180010b0963757272656e637900004190010b097472616e73666572000041a0010b1e6d6573736167652073686f72746572207468616e20657870656374656400009202046e616d650b06617373657274020000086c6f61645f6936340500000000000b726561644d6573736167650200000a72656d6f76655f693634030000000b726571756972654175746801000d726571756972654e6f7469636501000973746f72655f69363404000000002a5f5a4e3863757272656e6379313273746f72654163636f756e744579524b4e535f374163636f756e74450201300131355f5a4e3863757272656e637932336170706c795f63757272656e63795f7472616e7366657245524b4e535f385472616e73666572450901300131013201330134013501360137013804696e69740801300131013201330134013501360137056170706c7909013001310132013301340135013601370138010b4163636f756e744e616d65044e616d6502087472616e7366657200030466726f6d0b4163636f756e744e616d6502746f0b4163636f756e744e616d6506616d6f756e740655496e743634076163636f756e740002076163636f756e74044e616d650762616c616e63650655496e74363401000000572d3ccdcd087472616e7366657201000000204f4d11320369363401076163636f756e7401044e616d65076163636f756e74"}],"signatures":[]},"available_keys":["EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","EOS6Pfe32emhC2L2MrbLa1W354uudz7DyoBBR7kjVBzGuZhfANsYr","EOS7XXJgTWe9dx124sxDiAEFS6KzBNgSfBeQ1HxnCzCMwxqEtFqws"]}}
    thread-0  httpc.cpp:117 call

**Comment by heifner** [comment]
You closed this issue, I assume you figured out that you needed to pass `-s` to `./eosc set contract` if running `eosd` with `-skip-transaction-signatures`.

**Comment by sivachaitanya** [comment]
yeah if we are using no sign in eosd we have to do the same in eosc too :)
