### ISSUE TITLE
what is the replacement of i64i64i64 in abi file

### ISSUE THREAD

**Issue by giniz** [EOSIO/eos#6201]
Hi,

Am trying to use the identity contract but got problem with the **certs** table due to deprecated i64i64i64 type in ABI file. However I cannot find any document mentioning the new type to replace

```
"tables": [{
      "name": "certs",
      "type": "certrow",
      "index_type": "i64i64i64",
      "key_names" : [
        "property",
        "trusted",
        "certifier"
      ],
      " key_types": [
        "uint64",
        "uint64",
        "uint64"
      ]
    }
```

**Comment by taokayan** [comment]
```i64i64i64``` is no longer used as index type in abi file. All primary indexes of tables are of type i64.  Please test with cdt and the latest version of eos. If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com.
