### ISSUE TITLE
Wallet's RPC connection to test network error, and cleos can succeed.

### ISSUE THREAD

**Issue by SoftProgramLX** [EOSIO/eos#6202]
$ curl --request POST   --url http://jungle.cryptolions.io:38888/v1/wallet/list_wallets  
{"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"Unknown Endpoint","file":"http_plugin.cpp","line_number":298,"method":"handle_http_request"}]}}

$ cleos -u http://jungle.cryptolions.io:38888 wallet list
Wallets:
[]

How do I do it?

**Comment by jgiszczak** [comment]
The wallet URL is independent of the node URL on the cleos command line.  Specify it with `--wallet-url http://jungle.cryptolions.io:38888`.  Your command was retrieving your local wallet list.

To verify cleos is doing what you expect, use the `--print-request` argument.  For the above query, you will see:
```bash
$ cleos --wallet-url http://jungle.cryptolions.io:38888 --print-request wallet list
Wallets:
REQUEST:
---------------------
POST /v1/wallet/list_wallets HTTP/1.0
Host: jungle.cryptolions.io:38888
content-length: 0
Accept: */*
Connection: close


---------------------
Error 3110002: Missing Wallet API Plugin
Ensure that you have eosio::wallet_api_plugin added to your node's configuration!
Otherwise specify your wallet location with --wallet-url argument!
Error Details:
Wallet is not available
```
Which is exactly as it should be.  Public nodes should not ever be running wallets.

If you still have the problem and wish to discuss further, please post it in [https://eosio.stackexchange.com](https://eosio.stackexchange.com). To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
