### ISSUE TITLE
whitelists for synchronization nodes

### ISSUE THREAD

**Issue by quarksgluons** [EOSIO/eos#6206]
Two synchronization nodes add whitelists to each other. How do you do this?

**Comment by quarksgluons** [comment]
Why support? I think there is someting misunderstanding.
I mean how to make two nodes in the LAN add whitelists to each other,to stay connected for quick sync.

**Comment by jgiszczak** [comment]
To guarantee two nodes can always connect to each other (hardware and OS conditions permitting), in config.ini set `allowed-connection = specified`, add a `peer-private-key =` setting, one for each node, then add the corresponding `peer-key =` setting to the opposite node.  For example:

Node A:
```ini
allowed-connection = specified
peer-private-key = ["EOS6qM2oNVX6oS4MsxWpeZKyP1AnT39TuBY5rwF6TptW6YRa3Pxgn","5Jjr5RvPJBn9dxudSdnxGHRkzas7HQRTYhFutR3utadnFajBq1n"]
peer-key = EOS7MFAuuZ2P4ZsE94EiDmZcXiiBge8yVYTBAGdCQfBeZatfdFuLR
```
Node B:
```ini
allowed-connection = specified
peer-private-key = ["EOS7MFAuuZ2P4ZsE94EiDmZcXiiBge8yVYTBAGdCQfBeZatfdFuLR","5K8maRv8zRQQQ75yfXieYuq69fW9EkuCWoY24EdZNWoBmoNURKm"]
peer-key = EOS6qM2oNVX6oS4MsxWpeZKyP1AnT39TuBY5rwF6TptW6YRa3Pxgn
```
The keys in this example are a valid key pair, so they may be copied and pasted directly for testing purposes.  Obviously they should not be used in any production system, as they have been compromised by being pasted here.

As configured, this is a closed network of nodes.  To allow any other node to sync, you'll need to configure a third node:

Node C:
```ini
allowed-connection = any
peer-private-key = ["EOS5agxw7TnxknBuEkexTkC2uW56qTen7C6DB97tRjUh876Cb7ADY","5JawfDErJHG7VoeEjzypwSbADWm1hBRN3g7nBPj8ihbwFNuWnQd"]
```
And add `peer-key = EOS5agxw7TnxknBuEkexTkC2uW56qTen7C6DB97tRjUh876Cb7ADY` to at least one of Node A or Node B.  Node C allows public syncing, while maintaining its guaranteed connection(s) to Node A or B.

This does not enable any sort of "quick" sync.  It simply assures that Nodes A and B will never have exhausted their `max-clients =` settings.  It does validate the peers to one another, proving to Node A that it is only Node B connecting and vice versa.  It does not prevent tampering with the subsequent datastream between the nodes.  It is my understanding that this mechanism is not frequently used.  Instead the peer connection is configured to run over some sort of pre-established encrypted connection such as a VPN or SSH tunnel.  In that case, standard system administration procedures apply.

If you still have question and wish to discuss further, please post it in [https://eosio.stackexchange.com](https://eosio.stackexchange.com). To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
