### ISSUE TITLE
Change nodeos --genesis-json option behavior

### ISSUE THREAD

**Issue by larryk85** [EOSIO/eos#6209]
Change the behavior of `nodeos --genesis-json` and `genesis-timestamp` option to check if blocks.log exists and only fail if the genesis of the blocks.log does not match the supplied genesis.json or timestamp.  This would allow for scripts or users to run the same command without having two distinct commands for the setup and initial run and subsequent runs.

**Comment by arhag** [comment]
Resolved by #6212.
