### ISSUE TITLE
/v1/get_account 500 error, unspecified exception

### ISSUE THREAD

**Issue by j4ys0n** [EOSIO/eos#6213]
Hello,

I'm seeing that some accounts throw a 500 error from the `get_account` endpoint.

on my local: 
`curl -X POST -H "Content-Type: application/json" http://127.0.0.1:8888/v1/get_account -d '{"account_name": "ethsidechain"}'`
results in:
`{"code":500,"message":"Internal Service Error","error":{"code":0,"name":"exception","what":"unspecified","details":[]}}`

while, using the url from the eostracker.io explorer, it works.

`curl -X POST -H "Content-Type: application/json" https://eos.greymass.com/v1/chain/get_account -d '{"account_name": "ethsidechain"}'`

`{"account_name":"ethsidechain","head_block_num":24731621,"head_block_time":"2018-11-01T22:36:00.000","privileged":false,"last_code_update":"2018-10-22T14:58:08.000","created":"2018-07-17T03:38:11.500","core_liquid_balance":"0.0035 EOS","ram_quota":269977,"net_weight":106000,"cpu_weight":1070000,"net_limit":{"used":129,"available":7254875,"max":7255004},"cpu_limit":{"used":1037,"available":703518,"max":704555},"ram_usage":267451,"permissions":[{"perm_name":"active","parent":"owner","required_auth":{"threshold":1,"keys":[{"key":"EOS68PG99c2u83SuS5DkWuEp7yKbPQDEJ4qzNbqQdKTVwwfuznYtp","weight":1}],"accounts":[{"permission":{"actor":"ethsidechain","permission":"eosio.code"},"weight":1}],"waits":[]}},{"perm_name":"owner","parent":"","required_auth":{"threshold":1,"keys":[{"key":"EOS68PG99c2u83SuS5DkWuEp7yKbPQDEJ4qzNbqQdKTVwwfuznYtp","weight":1}],"accounts":[],"waits":[]}}],"total_resources":{"owner":"ethsidechain","net_weight":"10.6000 EOS","cpu_weight":"107.0000 EOS","ram_bytes":268577},"self_delegated_bandwidth":{"from":"ethsidechain","to":"ethsidechain","net_weight":"10.1000 EOS","cpu_weight":"106.0000 EOS"},"refund_request":null,"voter_info":{"owner":"ethsidechain","proxy":"","producers":[],"staked":1176500,"last_vote_weight":"0.00000000000000000","proxied_vote_weight":"0.00000000000000000","is_proxy":0}}`

any insight into fixing this would be fantastic.

thank you!

**Comment by jgiszczak** [comment]
Assuming the node on 127.0.0.1 that you are querying is syncing with mainnet, your sync probably is not yet complete.  Compare get_info on your node vs greymass and see.

If your local node is not syncing with mainnet, there's no reason for that account to exist, so the error would be correct.

**Comment by jgiszczak** [comment]
If the node is run with `verbose-http-errors` turned on, it can provide more detail in errors.

Yes, you should be able to see how close to synced you are.  As I said, use `/v1/chain/get_info` to see what head block the local node has.
