### ISSUE TITLE
how to get block_prefix by block_num or block id

### ISSUE THREAD

**Issue by hama** [EOSIO/eos#6223]
I found this code in "chain/transaction.cpp"
`void transaction_header::set_reference_block( const block_id_type& reference_block ) {
   ref_block_num    = fc::endian_reverse_u32(reference_block._hash[0]);
   ref_block_prefix = reference_block._hash[1];
}`

but how to get block_prefix by block_num or block id  using cleos or in contracts.

**Comment by taokayan** [comment]
You can refer to /eos/programs/cleos/main.cpp:
```
auto info = get_info(); 
...
block_id_type ref_block_id = info.last_irreversible_block_id;
...
trx.set_reference_block(ref_block_id);
```
Please ask in eosio.stackexchange.com if you have further questions.
