### ISSUE TITLE
Transactions initially included in forked blocks are lost forever -- could lead to unexplained failure of deferred tx to execute

### ISSUE THREAD

**Issue by acoutts** [EOSIO/eos#6228]
Last night I observed 6 cases where a transaction was initially included in a block, and then that block was immediately replaced with a new version of the same block number but lacking the original transaction.

Node information:
- nodeos v1.4.1
- full validation
- read-only mode
- non-producing node

Below I've printed relevant action traces as they are detected from the `applied_transaction` signal in the chain plugin, and also from the `accepted_block` signal. I was investigating how transactions are included into blocks and wanted to see if in a fork situation the applied_transaction signal would happen again. It appears it does not and the transaction is actually just lost.

In this case, block `25070852` was received twice. The first time it was received it included transaction `f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934`. This transaction was not included the second time this block was received and if you try to look up this transaction today in cleos it doesn't exist, because it appears it was never written into an irreversible block.

```
Error 3040011: The transaction can not be found
Error Details:
Transaction f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934 not found in history and no block hint was given
```

Nodeos log:

```
. . .
info  2018-11-03T21:48:30.304 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 96377791e7bdadf0... #25070850 @ 2018-11-03T21:48:28.500 signed by bitfinexeos1 [trxs: 30, lib: 25070516, conf: 0, latency: 1804 ms]
info  2018-11-03T21:48:30.433 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 112e6b741757820e... #25070851 @ 2018-11-03T21:48:29.000 signed by bitfinexeos1 [trxs: 34, lib: 25070516, conf: 0, latency: 1433 ms]
info  2018-11-03T21:48:30.555 thread-0  watcher_plugin.cpp:162        on_action_trace      ] [on_action_trace] [f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934] Added trace to queue: prepare | To: chintailease | From: co4lvm1ilgoa | Data: {"memo":"co4lvm1ilgoa|1|10|0.009|28|1.0000|byntr29c6n"}
info  2018-11-03T21:48:30.555 thread-0  watcher_plugin.cpp:162        on_action_trace      ] [on_action_trace] [f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934] Added trace to queue: transfer | To: eosio.token | From: co4lvm1ilgoa | Data: {"from":"co4lvm1ilgoa","to":"chintailease","quantity":"0.0900 EOS","memo":"co4lvm1ilgoa|1|10|0.009|28|1.0000|byntr29c6n"}
info  2018-11-03T21:48:30.555 thread-0  watcher_plugin.cpp:162        on_action_trace      ] [on_action_trace] [f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934] Added trace to queue: activate | To: chintailease | From: co4lvm1ilgoa | Data: {"memo":"co4lvm1ilgoa|1|10|0.009|28|1.0000|byntr29c6n"}
info  2018-11-03T21:48:30.556 thread-0  watcher_plugin.cpp:162        on_action_trace      ] [on_action_trace] [f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934] Added trace to queue: delegatebw | To: eosio | From: chintailease | Data: {"from":"chintailease","receiver":"co4lvm1ilgoa","stake_net_quantity":"0.0000 EOS","stake_cpu_quantity":"10.0000 EOS","transfer":0}
info  2018-11-03T21:48:30.556 thread-0  watcher_plugin.cpp:162        on_action_trace      ] [on_action_trace] [f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934] Added trace to queue: transfer | To: eosio.token | From: chintailease | Data: {"from":"chintailease","to":"eosio.stake","quantity":"10.0000 EOS","memo":"stake bandwidth"}
info  2018-11-03T21:48:30.556 thread-0  watcher_plugin.cpp:162        on_action_trace      ] [on_action_trace] [f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934] Added trace to queue: transfer | To: eosio.token | From: chintailease | Data: {"from":"chintailease","to":"eosio.stake","quantity":"10.0000 EOS","memo":"stake bandwidth"}
info  2018-11-03T21:48:30.556 thread-0  watcher_plugin.cpp:162        on_action_trace      ] [on_action_trace] [f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934] Added trace to queue: transfer | To: eosio.token | From: chintailease | Data: {"from":"chintailease","to":"eosio.stake","quantity":"10.0000 EOS","memo":"stake bandwidth"}
info  2018-11-03T21:48:30.556 thread-0  watcher_plugin.cpp:162        on_action_trace      ] [on_action_trace] [f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934] Added trace to queue: extensions | To: chintailease | From: chintailease | Data: {"scheduled_execution_time":1543700909,"transaction_retry_count":0,"stake_id":1140202861,"lease_id":3230853922,"stake_fulfilled":1,"memo":"delegatebw"}
info  2018-11-03T21:48:30.556 thread-0  watcher_plugin.cpp:162        on_action_trace      ] [on_action_trace] [f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934] Added trace to queue: transfer | To: eosio.token | From: chintailease | Data: {"from":"chintailease","to":"guantianying","quantity":"0.0899 EOS","memo":"Lend order (1140202861) fulfilled by borrow order (3230853922), paying interest from Chintai."}
info  2018-11-03T21:48:30.556 thread-0  watcher_plugin.cpp:162        on_action_trace      ] [on_action_trace] [f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934] Added trace to queue: transfer | To: eosio.token | From: chintailease | Data: {"from":"chintailease","to":"guantianying","quantity":"0.0899 EOS","memo":"Lend order (1140202861) fulfilled by borrow order (3230853922), paying interest from Chintai."}
info  2018-11-03T21:48:30.556 thread-0  watcher_plugin.cpp:162        on_action_trace      ] [on_action_trace] [f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934] Added trace to queue: transfer | To: eosio.token | From: chintailease | Data: {"from":"chintailease","to":"guantianying","quantity":"0.0899 EOS","memo":"Lend order (1140202861) fulfilled by borrow order (3230853922), paying interest from Chintai."}
info  2018-11-03T21:48:30.595 thread-0  watcher_plugin.cpp:274        on_accepted_block    ] [on_accepted_block] block_num: 25070852
info  2018-11-03T21:48:30.595 thread-0  watcher_plugin.cpp:275        on_accepted_block    ] [on_accepted_block] Matched TX in accepted block: f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934
info  2018-11-03T21:48:30.596 thread-0  watcher_plugin.cpp:281        on_accepted_block    ] [on_accepted_block] Action queue size after removing item: 0
info  2018-11-03T21:48:30.597 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block de5d4eed4ffc786d... #25070852 @ 2018-11-03T21:48:29.500 signed by bitfinexeos1 [trxs: 33, lib: 25070516, conf: 0, latency: 1097 ms]
info  2018-11-03T21:48:30.670 thread-0  controller.cpp:1278           maybe_switch_forks   ] switching forks from 017e8d04de5d4eed4ffc786d2684818d9f8f0aa32b3896c5e98a631f1b6ea1be (block number 25070852) to 017e8d046b3f84feb3e8dd55f726cc44f316a0ddd20fcbffd979ac09448736be (block number 25070852)
info  2018-11-03T21:48:31.101 thread-0  controller.cpp:1323           maybe_switch_forks   ] successfully switched fork to new head 017e8d046b3f84feb3e8dd55f726cc44f316a0ddd20fcbffd979ac09448736be
info  2018-11-03T21:48:31.101 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 6b3f84feb3e8dd55... #25070852 @ 2018-11-03T21:48:30.000 signed by cochainworld [trxs: 48, lib: 25070528, conf: 239, latency: 1101 ms]
info  2018-11-03T21:48:31.165 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 964915a8b867615c... #25070853 @ 2018-11-03T21:48:30.500 signed by cochainworld [trxs: 9, lib: 25070528, conf: 0, latency: 665 ms]
info  2018-11-03T21:48:31.446 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block f8fef8b95bb1dc01... #25070854 @ 2018-11-03T21:48:31.000 signed by cochainworld [trxs: 36, lib: 25070528, conf: 0, latency: 446 ms]
info  2018-11-03T21:48:31.960 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block da499d1e99804609... #25070855 @ 2018-11-03T21:48:31.500 signed by cochainworld [trxs: 29, lib: 25070528, conf: 0, latency: 460 ms]
info  2018-11-03T21:48:32.279 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 9cca39236a5fa1d6... #25070856 @ 2018-11-03T21:48:32.000 signed by cochainworld [trxs: 22, lib: 25070528, conf: 0, latency: 279 ms]
info  2018-11-03T21:48:32.875 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block a24ce33e94f32c63... #25070857 @ 2018-11-03T21:48:32.500 signed by cochainworld [trxs: 14, lib: 25070528, conf: 0, latency: 375 ms]
info  2018-11-03T21:48:33.479 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 71708c24b97b3bc0... #25070858 @ 2018-11-03T21:48:33.000 signed by cochainworld [trxs: 23, lib: 25070528, conf: 0, latency: 479 ms]
. . .
```

It appears that if a transaction is included in a block that is later reproduced due to a fork, the transaction(s) in the original block are dropped for good.

This would mean if a deferred transaction executes at the exact block of a fork like this, then the deferred tx may execute on the other chain and then be lost- appearing to have never executed on the main chain.

This poses a challenge to contract developers relying on deferred transactions as it appears there is no way to guarantee their execution.

Here is the plugin used to print the messages above:
https://github.com/acoutts/chintai-zeromq-watcher-plugin/blob/master/watcher_plugin/watcher_plugin.cpp

**Comment by arhag** [comment]
> In this case, block `25070852` was received twice. The first time it was received it included transaction `f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934`. This transaction was not included the second time this block was received and if you try to look up this transaction today in cleos it doesn't exist, because it appears it was never written into an irreversible block.

Was that transaction a deferred transaction or a regular non-delayed input transaction? And what was the `status` of that transaction included in the orphaned block?

If it was a deferred transaction with a status of `hard_fail` it could explain this behavior because that nodeos instance would indiscriminately blacklist the deferred transaction due to its failure and never attempt to execute that deferred transaction again for the rest of that nodeos process lifetime. Normally this would not be a problem unless a fork orphans the block that included that retired deferred transaction.

I will have to look more carefully into it, but if it is as I expect, I would indeed consider that a bug. Though, I'm still not sure if it actually covers your particular issue yet until I can get more information about that status. The solution may be to only blacklist in producer_plugin if the failure is subjective as defined in `controller.cpp`.

> It appears that if a transaction is included in a block that is later reproduced due to a fork, the transaction(s) in the original block are dropped for good.

An input transaction included in an orphaned branch can migrate over to another branch unless TaPoS prevents it. 

> This poses a challenge to contract developers relying on deferred transactions as it appears there is no way to guarantee their execution.

Even if this is a bug (as I suspect it might be) and is fixed, there would still be no guarantee that a deferred transaction will execute.

There are no guarantees that a deferred transaction will ever execute just like there is no guarantee that an input transaction will even be included in a block. In fact two of the reasons I can identify for the lack of a guarantee (even if the transaction would have no objective failures if executed with enough time given) are the same for both deferred and input transactions:

1. Subjective CPU billing.
2. Other subjective failures such as the blacklists.

However, there is another important reason for why there can be no guarantee that deferred transactions will execute which is specific to deferred transactions. The lack of the guarantee (and the addition of the `expired` status) was needed to prevent a potential attack vector (see issue https://github.com/EOSIO/eos/issues/2071).

**Comment by acoutts** [comment]
In this case the transaction I highlighted was a regular non-delayed transaction. The contract then performed an inline delegatebw and transfer action.

- `prepare`, `transfer`, and `activate` are bundled as 3 actions in a single transaction submitted to the Chintai contract.
- The 8 actions below `activate` starting with `delegatebw` are all inline actions of the same transaction. 

I highlighted deferred tx as I assume they would be susceptible just the same upon the moment of execution if the block that includes their execution is "lost" like in the 6 cases I observed yesterday.

The status of this transaction must have been executed or it would have been filtered out by the logic here in my plugin and I'd have never seen the action traces printed as they did: 
```c++
      void on_applied_tx(const transaction_trace_ptr& trace) {
        if (trace->receipt) {
          // Ignore failed deferred tx that may still send an applied_transaction signal
          if( trace->receipt->status != transaction_receipt_header::executed ) {
            return;
          }
. . .
```

**Comment by arhag** [comment]
@acoutts:

Okay, so if it is a non-delayed input transaction, then it likely means that the second time it tried to execute in the new branch it failed. If it was because of an objective reason, it would be because new transactions executed in the repeated block that preceding the retried transaction changed the state in such a way that caused the retried transaction to fail. More likely, it is because of a subjective failure such as CPU exhaustion.

Your plugin would not see the second failed attempt since it filters out all transactions that do not have an `executed` status.

**Comment by tbfleming** [comment]
> If it was a cpu exhaustion for example how could it execute the first time?

https://www.alohaeos.com/tools/benchmarks

**Comment by taokayan** [comment]
> Ah that could be the case. If it was a cpu exhaustion for example how could it execute the first time?

Even you have the same hardware, the cpu billing will unlikely be the same if a transaction is executed for the second time. Also if a transaction access multi_index table, or any api related to block time/block number, it might results in a different logic, (e.g. pseudo random number generation).

To ensure a transaction is really included, you can first get the block number by the transaction id, ensure the block number is less than or equal to the last irreversible block number, then retrieve the whole block to confirm the transaction is really there.

Please ask in eosio.stackexchange.com if you have further questions.

**Comment by abourget** [comment]
For ref: https://eosq.app/tx/f7a4ec11327a5a86740e8ef19b1d497e0c64b92e37035fd6e2936a930e50b934 shows the flow and deferred trx created.
