### ISSUE TITLE
`vector<bool>` singleton causes problems

### ISSUE THREAD

**Issue by jchung00** [EOSIO/eos#6241]
Here's some sample code:
```
/*header file*/
...
struct map_state{
  vector<bool> map;
  EOSLIB_SERIALIZE(map_state, (map));
}

typedef eosio::singleton< (N(m), map_state > map_singleton;
...

private:
  map_singleton _map;
...
```
```
/*cpp*/
/*Same namespace*/
/*constructor implemented*/
void contract_name::foo(){
  ...
  auto mstate = _map.get()
  ...
}
```
Causes the following error:
<img width="1311" alt="screen shot 2018-11-05 at 3 16 20 pm" src="https://user-images.githubusercontent.com/19266519/48024139-cf16c300-e10d-11e8-8010-a4046ad20ab3.png">

It seems like this can be fixed when you use `vector<uint8_t>` instead, but this uses more memory... Not completely sure why using `vector<bool>` doesn't work.

**Comment by taokayan** [comment]
I guess you need to use ```vector<uint8_t>``` at this moment because the type supported in the abi can only be ```bytes[]``` or ```int8[]```, which means that the underlying data can not be compressed. If you have further questions, please ask https://eosio.stackexchange.com/
