### ISSUE TITLE
Will Eos provide a random number generator for contracts?

### ISSUE THREAD

**Issue by NeverLandFly** [EOSIO/eos#6245]
Current methods used by developers seems to be complicate and vulnerable.
For instantce, several gambling games has reported their losses caused by hacker predicting the game results.

**Comment by taokayan** [comment]
There no real random in EOS blockchain. As every block must execute exactly the same in each node, random number in the smart contract is predictable. However you may generate random number off- chain. Please ask https://eosio.stackexchange.com/ if you have further questions.

**Comment by ranchersland** [comment]
> EOS blok zincirinde gerçek bir rastgelelik yoktur. Her bloğun her düğümde tam olarak aynı şekilde çalışması gerektiğinden, akıllı sözleşmedeki rastgele sayı tahmin edilebilir. Ancak zincir dışı rasgele sayı üretebilirsiniz. Başka sorularınız varsa lütfen [https://eosio.stackexchange.com/ adresine sorun.](https://eosio.stackexchange.com/)

How can I safely include an externally generated number in a smart contract? (i.e. how can I put those numbers inside secretly by preventing users from transacting on bloks.io?)
