### ISSUE TITLE
Question about not broadcasting confirmation once the receiver has confirmed the block successfully

### ISSUE THREAD

**Issue by tekpig** [EOSIO/eos#6246]
Now in the main net, when a transaction is packaged, it means that the current node confirms it, and it needs at least 2/3 of the 21 super nodes to confirm. In addition, two rounds of confirmation are required.

Therefore, the difference between the current block height and the irreversible block height, up to a maximum of 336( 2 * (2/3) * 21 * 12 = 336 ).

Why not broadcast confirmation to make a block become irreversible faster?

**Comment by tekpig** [comment]
In plugins/producer_plugin/producer_plugin.cpp, when accepted_block_connection receives block, on_block function will be called. 

In on_block function, 
         std::set_intersection( _producers.begin(), _producers.end(),
                                active_producers.begin(), active_producers.end(),
                                boost::make_function_output_iterator( [&]( const chain::account_name& producer )
         {
            if( producer != bsp->header.producer ) {
               auto itr = std::find_if( active_producer_to_signing_key.begin(), active_producer_to_signing_key.end(),
                                        [&](const producer_key& k){ return k.producer_name == producer; } );
               if( itr != active_producer_to_signing_key.end() ) {
                  auto private_key_itr = _signature_providers.find( itr->block_signing_key );
                  if( private_key_itr != _signature_providers.end() ) {
                     auto d = bsp->sig_digest();
                     auto sig = private_key_itr->second( d );
                     _last_signed_block_time = bsp->header.timestamp;
                     _last_signed_block_num  = bsp->block_num;

   //                  ilog( "${n} confirmed", ("n",name(producer)) );
                     _self->confirmed_block( { bsp->id, d, producer, sig } );
                  }
               }
            }
         } ) );

What's the purpose of the above codes?

**Comment by taokayan** [comment]
I think this is by design. the confirmation message has to be in-sync among all BPs in order to keep last irreversible block number in sync. A confirmation of block N is implicitly done by producing block N+1 after block N. You might argue that there maybe better ways to do that, but all of these changes require hard forks. If you have further questions, please ask in https://eosio.stackexchange.com/
