### ISSUE TITLE
billed CPU time (xxxx) is greater than the maximum billable CPU time for the transaction (xxxx)

### ISSUE THREAD

**Issue by tomarvijay25** [EOSIO/eos#6248]
I am getting this issue at the time of transferring my EOS from Ledger Nano S using Fairy wallet to one exchange. Somewhere I read that I will have to put some EOS on stake to rectify this error but it wasn't clear to me. Can someone please explain in detail how can I rectify this error. Please refer attached screenshot for detailed error.
![capture](https://user-images.githubusercontent.com/44813656/48080172-15a21580-e213-11e8-86af-41589fb541d2.JPG)

**Comment by eosbillbusiness** [comment]
Your account cpu must be staked with at least 3 eos。

**Comment by szwork2013** [comment]
Your account cpu must be staked with at least 3 eos。

**Comment by taokayan** [comment]
Compare to paying "gas" in Ethereum, you need to stake some of your EOS for CPU resource in order to make transactions. However, you can get your staked EOS back, so transfering in EOS is free of charge. If you have further questions, please ask in https://eosio.stackexchange.com/.

**Comment by tomarvijay25** [comment]
Thanks szwork2013 and taokayan.
I still have some query regarding the process and raised it in eosio forum as suggested by taokayan.
Here is the link "https://eosio.stackexchange.com/questions/3058/issue-in-transferring-eos-from-ledger-nano-to-exchange"
Thanks
