### ISSUE TITLE
STAT-124 ⁃ Template arguments Standards Update

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#625]
Update all Template arguments:  Should be CamelCase
(per https://blockone.atlassian.net/wiki/spaces/ID/pages/10518529/Coding+Standards)

https://blockone.atlassian.net/wiki/spaces/ID/pages/7864359/Testing+Process+Overview

ATC:

* Visually inspect the code for non-CamelCase Template arguments.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

Worked as part of STAT-123. There were a few of these that needed to be updated.

**Comment by heifner** [comment]
Verified by QA.
