### ISSUE TITLE
STAT-122 ⁃ C API Coding Standard Update

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#626]
Update the C API to the current Coding Standard 

https://blockone.atlassian.net/wiki/spaces/ID/pages/10518529/Coding+Standards

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

This part of updating api was worked under STAT-108:
  https://github.com/EOSIO/eos/pull/622

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

Note that Structs used by the C api will be updated via STAT-123.

**Comment by heifner** [comment]
Resolved by #627 and #622
