### ISSUE TITLE
Will "/v1/history/get_actions" be deprecated ? 

### ISSUE THREAD

**Issue by newyangyang** [EOSIO/eos#6260]
I'm currently on v1.4.1, and started my nodeos with command:

> nodeos --http-server-address 0.0.0.0:8888 --data-dir ~/eos/data --config-dir ~/eos/config --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::net_api_plugin --filter-on xxx:transfer: 

I've noticed that in EOSIO v1.4.3 Release, `(#6220) Failed Deferred Transactions Were in History Plugin Results` is fixed, and states that `history_plugin was DEPRECATED in version 1.2.0 `, implying future removal of this plugin.

I rely on api `/v1/history/get_actions` to get the actions of interest, so I wanna know:  Is this api part of `history_plugin` and affected by the #6220 bug ? If so, will this api removed in the future ?  Or is there an equivalent api can do its job ?

**Comment by jgiszczak** [comment]
All APIs with the prefix `/vi/history/` are indeed deprecated, and yes, the results you were retrieving using it were affected by #6220.  You should replay to be assured of clean results from that API.

You may expect the API to be removed in some future release.  Efforts to replace it are ongoing.  The Jungle Testnet is testing a version of the mongo plugin that can provide the history plugin APIs.  That may or may not be the solution that is eventually adopted into the base repository.

**Comment by newyangyang** [comment]
@jgiszczak Thank you for replying. 
The release note said `This does not affect the state of the chain`.
I only use the api `/v1/history/get_actions` to see EOS coins people sent to  me , I don't submit anything. 
In this case,  do I still need to replay ?
