### ISSUE TITLE
Will extra storage support contract data?

### ISSUE THREAD

**Issue by masonhunk** [EOSIO/eos#6261]
Hi,

The chainbase-multiindex db have some limitations, for example it has limited storage, it does not support String as key, and it support only 128 bit integer as key/index...So I want to know something about extra storage. I refer to mongodb-plugin but mongodb does not aim at storage extension per https://github.com/EOSIO/eos/issues/5150...

I have some questions here.

1  Do EOS have any plan to set extra storage for contract data? 

2 How will EOS handle storage scalability? As far as I know, the chainbase storage is limited to machine, for example, if the system has 1 super node, the storage is X; The network has at most 21X storage space..

**Comment by jgiszczak** [comment]
There are no plans to replace or extend storage of contract state to anything other than RAM.

Chainbase storage is indeed limited to the RAM available to producer nodes, which currently maxes out at 4 TB for supported platforms.  This limit does not multiply by the number of producer nodes&mdash;all producer nodes mirror one another.

Contracts need to be designed with these constraints in mind.
