### ISSUE TITLE
cleos get transaction failed

### ISSUE THREAD

**Issue by prettyCoders** [EOSIO/eos#6263]
cleos get transaction 690878b888dd70c339df268ae68019c097b1d4ded649a50c9b5723f734d84837
Error 3040011: The transaction can not be found

my plugin:
plugin = eosio::chain_api_plugin

plugin = eosio::history_api_plugin

plugin = eosio::chain_plugin

plugin = eosio::history_plugin

plugin = eosio::net_plugin

plugin = eosio::net_api_plugin

**Comment by prettyCoders** [comment]
Build version: 1e9ca55c

**Comment by damianoazzolini** [comment]
What is the full command? This transaction exists in the mainnet...

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/48178060-cfec6680-e352-11e8-9f36-0c0e737081b8.png)
@damianoazzolini

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/48178096-f9a58d80-e352-11e8-87cf-1bdd2e04bf7f.png)

**Comment by damianoazzolini** [comment]
Do you run a complete node syncronized with the mainnet? If not, this mean that you run a local testnet and you don't have that transaction in it

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/48187200-51ed8700-e375-11e8-855c-54ebb2d6a4ee.png)

![image](https://user-images.githubusercontent.com/36216120/48187226-60d43980-e375-11e8-8434-fe894b02148a.png)
It`s mainnet

**Comment by bookcool** [comment]
add -b option the block num of this transaction

**Comment by prettyCoders** [comment]
It`s work Thanks!Can i get all transactions about my account?

**Comment by jgiszczak** [comment]
No.  The current APIs do not provide all transactions in a single query.  To get all transactions that reference your account in authorization or receiver, use `cleos get actions`.  This will not include transactions that involved your account in other ways.

If you still have questions, please post in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
