### ISSUE TITLE
Using "get table {contract} EOS {table name}" got warning "missing comma in symbol"

### ISSUE THREAD

**Issue by Lucklyric** [EOSIO/eos#6274]
After upgrading to eosio.cdt v1.3.x, table scope for symbol is defined as `sym.conde().raw() a` in official `eosio.token` contract. 
Using` eosio.token` contract as an example, if I use `cleos get table eosio.token 4,EOS stat`, I can not get any results. When I use  `cleos get table eosio.token EOS stat`, I can get stats information as expected, but there will be warining on nodeos - "Invalid symbol, missing comma in symbol {} symbol.hpp from_string ".

**Comment by vchengsong** [comment]
got the same error. 

# command
$cleos get table eosio.token EOS stat

# nodeos log
2018-11-10T16:54:58.971 thread-0   symbol.hpp:84                 from_string          ] 3010014 symbol_type_exception: Invalid symbol
missing comma in symbol
    {}
    thread-0  symbol.hpp:78 from_string
2018-11-10T16:54:58.971 thread-0   symbol.hpp:84                 from_string          ] from: EOS

**Comment by arhag** [comment]
Resolved by #6342.
