### ISSUE TITLE
solution: i have the same question, use the command not works,please help me,thank you very much!

### ISSUE THREAD

**Issue by heshaofeng1991** [EOSIO/eos#6275]
`cleos set account permission gushi active '{"threshold":1,"keys":[{"key":"EOS7nLRAheR7tYMiTiCA2ry2vW2Yh4LKoMUsxiE6YcxSCh2nS8tq4","weight":1}],"accounts":[{"permission":{"actor":"eosio","permission":"eosio.code"},"weight":1}]}' owner -p gushi@owner`
Very good! it works!

_Originally posted by @lingyiliu016 in https://github.com/EOSIO/eos/issues/4432#issuecomment-401523179_

**Comment by heshaofeng1991** [comment]
cleos set account permission yucheng22222 owner '{"threshold":1,"keys":[{"key":"EOS5MiseD8XwNUb5QkSUMjgn1kacQZ4GhicR5Rp89xiXk1tcEsMk3","weight":1}],"accounts":[{"permission":{"actor":"eosio","permission":"e
osio.code"},"weight":1}]}' owner -p yucheng22222@owner

**Comment by heshaofeng1991** [comment]
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"yucheng22222","permission":"owner"}', but does not have signatures for it.

**Comment by firesWu** [comment]
Did your wallet have owner key?

**Comment by jgiszczak** [comment]
You must have the current owner key for the `yucheng22222` account in an unlocked wallet accessible to cleos.

If you still have problems and wish to discuss further, please post in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by heshaofeng1991** [comment]
tks, i solve the question!

**Comment by heshaofeng1991** [comment]
I will adopt your opinion. post in https://eosio.stackexchange.com.
