### ISSUE TITLE
Difference between the head block and the irreversible block

### ISSUE THREAD

**Issue by ttamna** [EOSIO/eos#6281]
Hello?
I have a question.
In technical white paper contains the following information.

"""In addition to DPOS, EOS.IO adds asynchronous Byzantine Fault Tolerance (aBFT) for faster achievement of irreversibility. The aBFT algorithm provides 100% confirmation of irreversibility within 1 second."""

But when i query block information, I can get following~

root@e7429669bd7d:~# /opt/eosio/bin/cleos -u https://rpc.eosys.io get info
{
  "server_version": "99d94446",
  "chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
  "head_block_num": 25993655,
  "last_irreversible_block_num": 25993331,
  "last_irreversible_block_id": "018ca073707d59cf928cf6a1726a87c3d23a521f622e535cfd80ef885216450f",
  "head_block_id": "018ca1b7683d813db0acec91915ad844c4350e79edb5fbe63ae08e7f246dc864",
  "head_block_time": "2018-11-09T06:39:09.000",
  "head_block_producer": "eosdacserver",
  "virtual_block_cpu_limit": 21627979,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 155586,
  "block_net_limit": 1044088,
  "server_version_string": "mainnet-1.4.1"
}

There is quite a difference between the head block and the irreversible block (about one round)
It seems that the current head block becomes irreversible block by another round,
Then, is not the irreversible settling time not one second but 126 seconds?

**Comment by jgiszczak** [comment]
Correct, irreversible settling time is a full round.  BFT is not yet implemented.  #6154
