### ISSUE TITLE
should faild if the permission is not created when linkauth,but now it success. 

### ISSUE THREAD

**Issue by bluepeople1** [EOSIO/eos#6290]
void apply_eosio_linkauth(apply_context& context) {
//   context.require_write_lock( config::eosio_auth_scope );

   auto requirement = context.act.data_as<linkauth>();
   try {
      EOS_ASSERT(!requirement.requirement.empty(), action_validate_exception, "Required permission cannot be empty");

      context.require_authorization(requirement.account); // only here to mark the single authority on this action as used

      auto& db = context.db;
      const auto *account = db.find<account_object, by_name>(requirement.account);
      EOS_ASSERT(account != nullptr, account_query_exception,
                 "Failed to retrieve account: ${account}", ("account", requirement.account)); // Redundant?
      const auto *code = db.find<account_object, by_name>(requirement.code);
      EOS_ASSERT(code != nullptr, account_query_exception,
                 "Failed to retrieve code for account: ${account}", ("account", requirement.code));
      if( requirement.requirement != config::eosio_any_name ) {
         **const auto *permission = db.find<permission_object, by_name>(requirement.requirement);**
         EOS_ASSERT(permission != nullptr, permission_query_exception,
                    "Failed to retrieve permission: ${permission}", ("permission", requirement.requirement));
      }

this cause linkauth permission success when the requirement permission exists but the permission is not created by the account.

**Comment by arhag** [comment]
The objective fix to this bug is tracked in #6333. This issue is left to track a subjective mitigation that rejects `eosio::linkauth` if it links to a non-existing permission.

**Comment by arhag** [comment]
There is no real need for a subjective mitigation since this isn't a security issue and the proper fix has been implemented as part of the protocol feature introduced in #6831.
