### ISSUE TITLE
Multi-index key name not meet constraints

### ISSUE THREAD

**Issue by codename-art** [EOSIO/eos#6291]
https://github.com/EOSIO/eos/blob/11c25394b6dd05cc3c97f0b7471a84f3d7cfbca3/contracts/eosio.msig/eosio.msig.abi#L140
Is it allowed to have multi-index key name that not meet base32 constraints?

**Comment by arhag** [comment]
The `key_names` and `key_types` fields of the ABI do not do anything and are remnants of an old ABI spec that unfortunately were not pruned prior to 1.0 release. They should be ignored (and preferably left empty).

**Comment by arhag** [comment]
Also, most of the contracts in contracts folder of the eos repository are old and not maintained. Check out the [eosio.contract](https://github.com/EOSIO/eosio.contracts/) repository for the most recent versions of the eosio.bios, eosio.system, eosio.msig, eosio.token, and eosio.wrap (formerly known as eosio.sudo) contracts.
