### ISSUE TITLE
Why I'm getting unlinkable block exception after few days. EOSIO v1.4.2

### ISSUE THREAD

**Issue by 26rahulsingh** [EOSIO/eos#6294]
thread-0  controller.cpp:1251 push_block
warn  2018-11-12T05:58:41.503 thread-0  controller.cpp:1251           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc651d0d30517bf748f0d52e5eeb87b217e4a0a4f19a7150ee699898f72c","previous":"001efc647bbfc312bf95c3e6fb39a32388513f216ee93e5b59c6ced5491dbeac"}
    thread-0  fork_database.cpp:151 add
error 2018-11-12T05:58:41.503 thread-0  producer_plugin.cpp:316       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc651d0d30517bf748f0d52e5eeb87b217e4a0a4f19a7150ee699898f72c","previous":"001efc647bbfc312bf95c3e6fb39a32388513f216ee93e5b59c6ced5491dbeac"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1251 push_block
warn  2018-11-12T05:58:42.003 thread-0  controller.cpp:1251           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc66287cf525dfbd183ef0d134d2fe361c2790959ce3f679b5efec5e30a1","previous":"001efc651d0d30517bf748f0d52e5eeb87b217e4a0a4f19a7150ee699898f72c"}
    thread-0  fork_database.cpp:151 add
error 2018-11-12T05:58:42.003 thread-0  producer_plugin.cpp:316       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc66287cf525dfbd183ef0d134d2fe361c2790959ce3f679b5efec5e30a1","previous":"001efc651d0d30517bf748f0d52e5eeb87b217e4a0a4f19a7150ee699898f72c"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1251 push_block
warn  2018-11-12T05:58:42.503 thread-0  controller.cpp:1251           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc6758da9febc092121c659fd5469c8542d67f025fc71b45623e555ef6e8","previous":"001efc66287cf525dfbd183ef0d134d2fe361c2790959ce3f679b5efec5e30a1"}
    thread-0  fork_database.cpp:151 add
error 2018-11-12T05:58:42.503 thread-0  producer_plugin.cpp:316       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc6758da9febc092121c659fd5469c8542d67f025fc71b45623e555ef6e8","previous":"001efc66287cf525dfbd183ef0d134d2fe361c2790959ce3f679b5efec5e30a1"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1251 push_block
warn  2018-11-12T05:58:43.003 thread-0  controller.cpp:1251           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc689b2ec54dab1ce03240188d95de7cca331e04fa9991aeaf806ce8c08d","previous":"001efc6758da9febc092121c659fd5469c8542d67f025fc71b45623e555ef6e8"}
    thread-0  fork_database.cpp:151 add
error 2018-11-12T05:58:43.003 thread-0  producer_plugin.cpp:316       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc689b2ec54dab1ce03240188d95de7cca331e04fa9991aeaf806ce8c08d","previous":"001efc6758da9febc092121c659fd5469c8542d67f025fc71b45623e555ef6e8"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1251 push_block
warn  2018-11-12T05:58:43.503 thread-0  controller.cpp:1251           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc6927b593d9d53b7ab95412c092e829eb8ebd05a553afc2fa4b56a1981d","previous":"001efc689b2ec54dab1ce03240188d95de7cca331e04fa9991aeaf806ce8c08d"}
    thread-0  fork_database.cpp:151 add
error 2018-11-12T05:58:43.503 thread-0  producer_plugin.cpp:316       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc6927b593d9d53b7ab95412c092e829eb8ebd05a553afc2fa4b56a1981d","previous":"001efc689b2ec54dab1ce03240188d95de7cca331e04fa9991aeaf806ce8c08d"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1251 push_block
warn  2018-11-12T05:58:44.003 thread-0  controller.cpp:1251           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc6ace306794b5131381b7a024e3515475357747540d99e867b9de723b47","previous":"001efc6927b593d9d53b7ab95412c092e829eb8ebd05a553afc2fa4b56a1981d"}
    thread-0  fork_database.cpp:151 add
error 2018-11-12T05:58:44.003 thread-0  producer_plugin.cpp:316       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc6ace306794b5131381b7a024e3515475357747540d99e867b9de723b47","previous":"001efc6927b593d9d53b7ab95412c092e829eb8ebd05a553afc2fa4b56a1981d"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}
    thread-0  controller.cpp:1251 push_block
warn  2018-11-12T05:58:44.503 thread-0  controller.cpp:1251           push_block           ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc6b3b5119921c976ac92c8f9d924fea054a9b06d3da9f76cc8ccdd40ddd","previous":"001efc6ace306794b5131381b7a024e3515475357747540d99e867b9de723b47"}
    thread-0  fork_database.cpp:151 add
error 2018-11-12T05:58:44.503 thread-0  producer_plugin.cpp:316       on_incoming_block    ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block
    {"id":"001efc6b3b5119921c976ac92c8f9d924fea054a9b06d3da9f76cc8ccdd40ddd","previous":"001efc6ace306794b5131381b7a024e3515475357747540d99e867b9de723b47"}
    thread-0  fork_database.cpp:151 add
rethrow
    {}

**Comment by imlaochen** [comment]
same problem with v1.4.2.

downgrade to v1.1.0， it works. 
but i don't know why.

**Comment by jgiszczak** [comment]
Which network plugin are each of you using in 1.4.2?  You should be using net_plugin, by configuring `p2p-peer-address =`.  You should not be using bnet_plugin, and should remove any instance of `bnet-connect =`, as bnet_plugin is unreliable and prone to corrupting blocks, resulting in unlinkable exceptions.

**Comment by taokayan** [comment]
Closed as no further reply. If you still have the same problem please ask https://eosio.stackexchange.com/

**Comment by quanhuynhUmb** [comment]
> same problem with v1.4.2.
> 
> downgrade to v1.1.0， it works.
> but i don't know why.

How can downgrade to v1.1.0? Please help me step by step.
Thank you very much.
I stuck this problem  many day (T__T)
