### ISSUE TITLE
How to get action detail data

### ISSUE THREAD

**Issue by eggoa** [EOSIO/eos#6300]
uint32_t read_action_data (void *msg, uint32_t len)

How can I use rpc to read above function data ?  Is it have action resources used deail data ?

Thank you!

**Comment by jgiszczak** [comment]
`read_action_data()` only retrieves the action data for the current action within contract code.  It is not accessible via RPC, and is not interesting or useful as an RPC call.  It does not include resource usage information.

If you have further questions of this nature, please post them to https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
