### ISSUE TITLE
what is meaning of "rror 3160009: No wast file found"

### ISSUE THREAD

**Issue by dwarf-han** [EOSIO/eos#6303]
I'm new for EOSIO and trying to follow tutorial this

https://developers.eos.io/eosio-home/docs/your-first-contract

but I got this error

Error 3160009: No wast file found
Error Details:
no wasm file found ./hello/hello.wasm

here is my history and it was worked with ubuntu 16.04

root@han:~/contracts/hello# cleos set contract hello ./hello -p hello@active
Reading WASM from ./hello/hello.wasm...
Error 3160009: No wast file found
Error Details:
no wasm file found ./hello/hello.wasm
root@han:~/contracts/hello# pwd
/root/contracts/hello
root@han:~/contracts/hello# ls
hello.abi  hello.cpp  hello.wasm
root@han:~/contracts/hello# 

root@han:~/contracts/hello# 
root@han:~/contracts/hello# docker ps

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                              NAMES
916bd7b0721e        eosio/eos:v1.4.2    "/bin/bash -c 'keosd…"   23 hours ago        Up 29 minutes       127.0.0.1:5555->5555/tcp, 0.0.0.0:7777->7777/tcp   eosio

**Comment by jgiszczak** [comment]
You needed to substitute your contracts directory for the ` --volume CONTRACTS_DIR:CONTRACTS_DIR \` argument to `docker run` to map your local filesystem to the docker container.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
