### ISSUE TITLE
Need a function to check if it is a contract account

### ISSUE THREAD

**Issue by jin10086** [EOSIO/eos#6305]
So I can refuse the contract attack

**Comment by jin10086** [comment]
Now basically all the random numbers are broken, which are all implemented by the contract account.
If I can in smart contract check if it is a contract account  , I can reject the request.

**Comment by evsward** [comment]
- RPC请求get_account -> last_code_update.  如果最后code修改时间不是genesis_timestamp，那这个账户就是合约账户。  
- 或者使用cleos get code {account_name}，查看某账户的code值，如果不是0则证明该账户是合约账户。

**Comment by jin10086** [comment]
@evsward  谢谢回复，外部的话，我当然可以拿到...
我想要的是 在合约内 判断...

**Comment by evsward** [comment]
没有文档，兄弟，需要自己尝试调用一下，你可以参考read_only::get_code源码。在合约中通过状态库查询到账户的信息，然后判断返回对象的code.size()是否不为空，是的话则证明是合约账户。

**Comment by jin10086** [comment]
好的，谢谢啦.我尝试一下，然后成功的话，把代码贴出来，方便后面的兄弟...

**Comment by flyq** [comment]
我也尝试了。
参考：
https://github.com/EOSIO/eos/blob/master/plugins/chain_plugin/chain_plugin.cpp#L1578

```cpp
        const auto& d = db.db();
        const auto& accnt  = d.get<account_object,by_name>( params.account_name );        
    
        if(accnt.code.size()) {
          print("Msg from a account with contract, you may be a hacker.", name{user});
        } else {
          print("Msg from a account without contract, you are a good man.", name{user});
        }
```
   
但是因为引入了```eosio/chain/*```里面的头文件，编译不通过

**Comment by evsward** [comment]
因为合约的执行是与区块链分隔开的，因此合约不能直接使用节点的环境变量。所以你要尝试在合约中自己构建db对象，请参考

https://github.com/EOSIO/eos/blob/master/libraries/chain/controller.cpp#L173

**Comment by taokayan** [comment]
> Now basically all the random numbers are broken, which are all implemented by the contract account.
> If I can in smart contract check if it is a contract account , I can reject the request.

This is unlikely to solve your fundamental problem, as a hacker can run a modified local node not to broadcast his transactions that will potentially lose the games.

**Comment by fingera** [comment]
Even if send_defered twice, BP can still control HASH, but maybe safe for small amounts.

**Comment by jin10086** [comment]
Someone helped create a contract database.
Although not so smart, it is currently available.

https://github.com/ProChain/ProRatingEOS

**Comment by jgiszczak** [comment]
Closing, as the thread has played itself out and the requested feature does not solve any problem.

**Comment by superpdm** [comment]
> 因为合约的执行是与区块链分隔开的，因此合约不能直接使用节点的环境变量。所以你要尝试在合约中自己构建db对象，请参考
> 
> https://github.com/EOSIO/eos/blob/master/libraries/chain/controller.cpp#L173
 你真的在合约里面构建过db对象吗？应该是不太可能的啊
