### ISSUE TITLE
Compatible Clang 4.0.X is conflict

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#6310]
when I rn nodeos, ,logs show as:
Compiler Version: 
                   342e322e3120436f6d70617469626c6520436c616e6720342e302e302028746167732f52454c454153455f3430302f726331290000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 "4.2.1 Compatible Clang 4.0.0 (tags/RELEASE_400/rc1) "
                   vs
                   342e322e3120436f6d70617469626c6520436c616e6720342e302e312028746167732f52454c454153455f3430312f66696e616c2900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 "4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final) "

but I have checked clang version,both was 4.0.0,is was not changed,why?

**Comment by evsward** [comment]
**find the difference:**
- Clang 4.0.0 (tags/RELEASE_400/rc1)   
- Clang 4.0.1 (tags/RELEASE_401/final)

**Comment by jgiszczak** [comment]
While those two compiler versions may actually generate 100% compatible shared memory layouts in RAM, the nodeos code is extremely conservative and makes no assumptions that this is true.  There are no guarantees that even micro version changes do generate compatible layouts, so a replay is still required.

It is very easy for a system to have more than one compiler installed.  You will need to examine the build scripts, and possibly modify them to print which compiler they locate to verify precisely which installation is being used.  It may not be what you find by default in the path at a shell prompt.
