### ISSUE TITLE
Getting error "Unknown type name 'uint256_t'; did you mean 'uint16_t'?"

### ISSUE THREAD

**Issue by ericc2833** [EOSIO/eos#6312]
I want to use uint256_t in my EOS smart contract but I am getting following error

unknown type name 'uint256_t'; did you mean 'uint16_t'?

Do I need to add any additional headers or something? I have tried using compiling the code using both eosio.cdt and eosiocpp.

**Comment by jgiszczak** [comment]
uint256_t is not a standard type, and so is not provided.  You may create your own or use one of the various publicly available libraries.

**Comment by dominic-healid** [comment]
@jgiszczak but why it is being mentioned in the documentation?

```
You can have up to 16 additional indexes and the field types can be uint64_t, uint128_t, uint256_t, double or long double
```
