### ISSUE TITLE
ERROR. At compilation smart contracts

### ISSUE THREAD

**Issue by asvirido** [EOSIO/eos#632]
I updated to the latest version. And now, code produces an error.
```
 #include <eoslib / eos.hpp>
```
Ordinary contracts are working: currency, infinity etc. Not working only my contacts.
I'm git cloned last version. And `./build.sh ubuntu`
Next. I'm changed last line in your build script `./build.sh` from `make -j4` to `sudo make install` And run but that's doesn't work

### Error
```
 /home/asvirido/EOS/contracts/message/message.hpp:13:10: fatal error: 'eoslib/eos.hpp' file not found
```

**Comment by heifner** [comment]
Spaces are not allowed in an include:
```
 #include <eoslib/eos.hpp>
```
Don't see how that could have ever worked.

**Comment by asvirido** [comment]
Sorry, I don't understand. Which spaces?

**Comment by heifner** [comment]
Should be:

```
 #include <eoslib/eos.hpp>
```
Not:
```
 #include <eoslib / eos.hpp>
```

**Comment by asvirido** [comment]
This is a mistake in the issue. In code `#include <eoslib/eos.hpp>`

**Comment by brianjohnson5972** [comment]
If you updated to the latest version, I would expect many compile issues in
any changed smart contracts, since the functions and methods were changed
last week to be all lower case with "_" between words.

**Comment by asvirido** [comment]
Yes, I know it, but error at the compilation stage, does not find eos.hpp.

**Comment by asvirido** [comment]
### Solution
```
add_wast_target has been changed, don't pass in the SOURCE_FILES, it has been changed
to only compile the file <target>.cpp.
If you have more than one cpp file to compile, then include the subsequent cpp files in <target>.cpp
```

**Comment by popov-a-e** [comment]
I have the same issue compiling skeleton from samples:
eoscpp -o skeleton.wast skeleton.cpp
-emit-llvm -O3 --std=c++14 --target=wasm32 -ffreestanding -nostdlib -fno-threadsafe-statics -fno-rtti -fno-exceptions -I /usr/local/include -I . -c skeleton.cpp -o /tmp/tmp.pQXbzwmTpU/built/skeleton.cpp
In file included from skeleton.cpp:5:
./skeleton.hpp:5:10: fatal error: 'eoslib/eos.hpp' file not found
#include <eoslib/eos.hpp>
         ^~~~~~~~~~~~~~~~
1 error generated.
Using Docker on Ubuntu 16.04.

**Comment by heifner** [comment]
This is not the same issue. Please create a new issue with step by step instructions to reproduce. Including how you are running eoscpp. When you pulled from master. Are you in the Docker container or external? Do you have a docker compose override file?
