### ISSUE TITLE
Use std::nounitbuf for blocks.log

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#6328]
`libraries/chain/block_log.cpp` is opening `blocks.log` and `blocks.index` with default `unitbuf` set, so on each writing, there are two write operations on the filesystem: first the header, then  the body. This causes extra I/O load on the underlying physical media.

It makes sense to use std::nounitbuf flag for the blocks log, so that the write operations are combined. As of now, the flush() call at the end of writing has no effect because of the unitbuf flag set.

The write operations are seen very well with `strace` Linux command:

```
strace -p PID 2>&1 | grep write
```

**Comment by cc32d9** [comment]
also probably you don't need to call flush() and let the standard library handle the buffering efficiently. This will improve the I/O load a lot.

**Comment by acoutts** [comment]
Here is strace for the `state_history_plugin`, as it appears it might be doing the same: https://gist.github.com/acoutts/40a61918a2ac7d239e0474a179d4448a

handles 10-13 are the state history files:
```
nodeos     1665  1672           ubuntu    6uW     REG              259,1        2896    6656005 /home/ubuntu/opt/data/state/shared_memory.meta
nodeos     1665  1672           ubuntu    7uW     REG              259,1        2896    6656009 /home/ubuntu/opt/data/blocks/reversible/shared_memory.meta
nodeos     1665  1672           ubuntu    8w      REG              259,1 54679642212    6656010 /home/ubuntu/opt/data/blocks/blocks.log
nodeos     1665  1672           ubuntu    9w      REG              259,1   143007136    6656012 /home/ubuntu/opt/data/blocks/blocks.index
nodeos     1665  1672           ubuntu   10u      REG              259,1 29181443729    6656014 /home/ubuntu/opt/data/state-history/trace_history.log
nodeos     1665  1672           ubuntu   11u      REG              259,1   143030232    6656015 /home/ubuntu/opt/data/state-history/trace_history.index
nodeos     1665  1672           ubuntu   12u      REG              259,1 15036721509    6656016 /home/ubuntu/opt/data/state-history/chain_state_history.log
nodeos     1665  1672           ubuntu   13u      REG              259,1   143030232    6656017 /home/ubuntu/opt/data/state-history/chain_state_history.index
```

**Comment by jgiszczak** [comment]
@cc32d9 The string `unitbuf` occurs nowhere in the chain library, and the default for iostreams for that flag is off.  I suggest storing your blocks log on a filesystem that support `noatime` and trying that.  I suspect one of the writes will go away.

**Comment by cc32d9** [comment]
@jgiszczak this has nothing to do with noatime, which is actually set on my server. `strace` shows the write operations that the program is making for particular fiilehandles, and `lsof` shows the file handle numbers and how they are associated with files.

`strace` shows that blocks.log is written with two write() operations per block: first goes 8-byte length, then goes the content.

**Comment by jgiszczak** [comment]
@cc32d9 The fact remains that the `unitbuf` flag is not being set on the block log stream, or any other stream.  If there are two writes happening, that is the buffered behavior in your standard library.  Only `std::cerr` and `std::wcerr` have `unitbuf` set by default.  No other stream, including `std::cout` and all `fstream`s, have the flag set by default.

You might try adding `my->block_stream << std::nounitbuf;` to `void block_log::open(const fc::path& data_dir)` in `block_log.cpp` after the stream is opened, in case your standard library has nonstandard behavior.

**Comment by cc32d9** [comment]
@jgiszczak this is a totally standard build on Ubuntu 18.04, just built from EOSIO sources. And it's showing the same picture on multiple servers. I will try to tweak the code later today.

**Comment by jgiszczak** [comment]
@cc32d9 What were the results of an explicit `nounitbuf` flag set?

**Comment by sanaraufx** [comment]
We no longer use iostream for blocklog.
