### ISSUE TITLE
Build issue on Ubuntu 18.10

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#6337]
llvm 4 build fails on Ubuntu 18.10. This patch fixes it: https://bugzilla.redhat.com/attachment.cgi?id=1389687&action=diff

**Comment by spoonincode** [comment]
We no longer need to build llvm4 on ubuntu 18.10 -- we don't need to build a wasm toolchain and the llvm library for wavm come can come from a system provided packaged. "just doing cmake" should work on 18.10. Going to go ahead and close.
