### ISSUE TITLE
delete all data in smart contract when re-deploy?

### ISSUE THREAD

**Issue by newbieh4cker** [EOSIO/eos#6338]
is there anyway to delete all data in smart contract table, when re-deploying(cause of code modification) it??

**Comment by helperShang** [comment]
```
cleos set contract account -c
```

**Comment by conr2d** [comment]
> ```
> cleos set contract account -c
> ```

@helperShang's command is for clearing contract from account, but not clearing table. There's no convenient way to clear table yet.

**Comment by taokayan** [comment]
One of the possible ways is to make an action to delete one or more rows, and then execute it multiple times until all rows are removed. 

If you have further questions please ask https://eosio.stackexchange.com/
