### ISSUE TITLE
Which docker images should I use for dev??

### ISSUE THREAD

**Issue by newbieh4cker** [EOSIO/eos#6339]
![image](https://user-images.githubusercontent.com/23703741/48681025-312df880-ebe3-11e8-9a0b-ad2d58eb8d3e.png)

looks like eos-dev is going to be deprecatred. Which images should I use?

**Comment by conr2d** [comment]
`eos-dev` is right one for contract development. You can use prebuilt image from [here](https://github.com/EOSIO/eosio.cdt/releases) or create docker image with Dockerfile by yourself.

**Comment by GMory** [comment]
Any news on what will take it's place or what alternative approach we should take after June 19, 2019?

**Comment by gleehokie** [comment]
We're moving away from Docker images in favor of the pre-built binaries.  See https://github.com/EOSIO/eos/releases/latest and https://github.com/EOSIO/eosio.cdt/releases/latest.
