### ISSUE TITLE
cleos set contract error message & usage info not update?

### ISSUE THREAD

**Issue by dixia** [EOSIO/eos#6343]
If you point cleos to a wrong path which beginner does a lot, you will get error messages which does not hint the correct path for them and sometimes confusing.

For example, if you have a folder at path:

/Users/dixia/code/onboarding/inline_action/addressbook

and use the following command:

cleos set contract addressbook ./addressbook addressbook.wasm addressbook.abi

Error 3160009: No wast file found
Error Details:
no wasm file found ./addressbook/addressbook.wasm

Firstly. why it is saying wast file is not found? I thought a wast file is not required or at least user does not have generate themselves?

Also it does not show the absolute path which the cleos is trying to read the contract from. That is difficult for beginner/new adopter to troubleshooting their problems if they use a wrong path or somehow in case of docker the path is not point to correct mapping folder.
 
Moreover, the usage of cleos set contract actually does not say the contract-dir has to be an absolute path. 

contract-dir TEXT           The path containing the .wasm and .abi

It can do the job & good developers can figure it out. But this will consume new developers quite some time. Can we add support for relative path or update the usage?

**Comment by conr2d** [comment]
The name of exception `wast_file_not_found` is changed to `wasm_file_not_found`, but not merged to `master` yet. (#6048)

**Comment by jgiszczak** [comment]
The name of the exception has been corrected and is correct beginning with the v1.5.0 release.  The path in the error message now prints the canonical path, making debugging erroneous relative paths easier.  This is also available beginning with the v1.5.0 release.
