### ISSUE TITLE
3080004：Transaction exceeded the current CPU usage limit imposed on the transaction

### ISSUE THREAD

**Issue by ddzyan** [EOSIO/eos#6347]
"server_version_string": "v1.4.1-dirty"
"network":MainNet
```js
err message: {"code":500,"message":"Internal Service Error","error":{"code":3080004,"name":"tx_cpu_usage_exceeded","what":"Transaction exceeded the current CPU usage limit imposed on the transaction","details":[{"message":"billed CPU time (17175 us) is greater than the maximum billable CPU time for the transaction (16812 us)","file":"transaction_context.cpp","line_number":520,"method":"validate_cpu_usage_to_bill"}]}}
err stack: Error: {"code":500,"message":"Internal Service Error","error":{"code":3080004,"name":"tx_cpu_usage_exceeded","what":"Transaction exceeded the current CPU usage limit imposed on the transaction","details":[{"message":"billed CPU time (17175 us) is greater than the maximum billable CPU time for the transaction (16812 us)","file":"transaction_context.cpp","line_number":520,"method":"validate_cpu_usage_to_bill"}]}}
    at /data/home/admin/wallet/eos-funds/node_modules/eosjs-api/lib/apigen.js:112:23
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

```
![image](https://user-images.githubusercontent.com/9130123/48721310-9c67e100-ec5c-11e8-94df-3c100a72f3af.png)

My CPU resources are very abundant. Why is this problem?

**Comment by jgiszczak** [comment]
Your available CPU bandwidth is less than 14 milliseconds.  Your transaction is attempting to use 17 milliseconds of CPU time.  Your CPU resources are anything but abundant.  Execute a simpler transaction or stake more CPU bandwidth.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
