### ISSUE TITLE
Can I send data to another contract??

### ISSUE THREAD

**Issue by newbieh4cker** [EOSIO/eos#6352]
https://developers.eos.io/eosio-home/docs/sending-an-inline-transaction-to-external-contract
In above tutorial, I see addressbook send string to abcount. I'm trying to make people multi_index table in abcounter (duplicate of people table in addressbook).

I think I can get specificed data, with this. 'auto userData = addresses.find(user.value);'
But I'm stuck with how to send data 'userData' to abcounter contract.

This is code I'm working on to send data,

void send_data(name user, ??? orig_data) {
    action copier = action(
      permission_level{get_self(),"active"_n},
      "abcounter"_n,
      "upsert2"_n,
      make_tuple(user, orig_data)
    );
    copier.send();

But I'm not sure which datatype I need to use to pass userData(as orig_data)

**Comment by jgiszczak** [comment]
Dereference the iterator you retrieved with `addresses.find()`.  Your type will be `const person& orig_data`.

For contract authoring help, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for coding help discussions. Thanks!
