### ISSUE TITLE
replay is very slow after 5,000,000 

### ISSUE THREAD

**Issue by llmin** [EOSIO/eos#6354]
We deploy a full node of EOS,  and we meet he problem of repaly is very slow after about 5,000,000 block.  cpu usage is under 5%.  mem usage is about 85%,  we use aws ec2 with 4vcpu and 16G memeory.   EOS version 1.4.3

log:
error 2018-11-20T05:21:23.162 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found
debug 2018-11-20T05:21:23.162 thread-0  controller.cpp:893            push_scheduled_trans ] 3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
assertion failure with message: refund request not found
    {"s":"refund request not found"}
    thread-0  wasm_interface.cpp:934 eosio_assert
pending console output:
    {"console":""}
    thread-0  apply_context.cpp:72 exec_one

**Comment by jgiszczak** [comment]
There are already numerous threads discussing the hardware requirements for running a node synced with mainnet, both here and on Stack Exchange as well as elsewhere on the web.  When your CPU usage is low, your instance needs higher IOPS to persistent storage.  See #5797 for one of the longer discussions.  Search the web for others.
