### ISSUE TITLE
global_sequence stored in mongodb should be int64

### ISSUE THREAD

**Issue by kaidiren** [EOSIO/eos#6368]
global_sequence from eos source code:
![image](https://user-images.githubusercontent.com/2025174/48847173-dc090700-eddb-11e8-936b-057280c4062c.png)

global_sequence from mongdb:
![image](https://user-images.githubusercontent.com/2025174/48847124-c267bf80-eddb-11e8-8891-ab004f70aa35.png)

it's a bug in mongo_db_plugin

**Comment by heifner** [comment]
The mongo_db_plugin converts action_trace which includes action_receipt to json for storage in mongodb. It appears that mongo has decided to store the global_sequence and recv_sequence as i32. Presumably, it will store them as i64 if the json number is too larger for i32.

**Comment by kaidiren** [comment]
ok, thanks

**Comment by FasihAmco** [comment]
The global_sequence has now even greater than the i64 and it is saved as a string in mongodb. Any solution to deal with this? How to store it as a long long integer or i128 in the mongodb ?

**Comment by heifner** [comment]
We are just taking defaults for mongo.
