### ISSUE TITLE
replay is doing, while it has a error like this message: refund request not found ,i wonder it is an effort for this replay?

### ISSUE THREAD

**Issue by hmlinux** [EOSIO/eos#6376]
### When I download this package ,and i have config this mainnet in the config.ini,I  do this two steps 
1.start
./start.sh --genesis-json genesis.json --hard-replay --wasm-runtime wabt

2.second start
./start.sh
nodeos --data-dir /data/seele/data/eosnode --config-dir /data/seele/data/eosnode
when it id doing replay, it is showing this message  in the screen, My system is ubuntu 16.04 ,
why ? what should i do to handle this error???

error 2018-11-22T10:24:26.721 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:24:29.185 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:24:30.333 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:24:31.933 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:24:33.882 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:24:36.220 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:24:37.630 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: symbol precision mismatch 
error 2018-11-22T10:24:41.312 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:24:47.632 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:24:47.966 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:24:55.889 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: symbol precision mismatch 
error 2018-11-22T10:24:55.961 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: symbol precision mismatch 
error 2018-11-22T10:24:56.136 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: symbol precision mismatch 
error 2018-11-22T10:24:59.858 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:25:00.459 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:25:04.115 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: refund request not found 
error 2018-11-22T10:25:04.403 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: symbol precision mismatch 
   5093900 of 26509107

is have someone countering this?

**Comment by taokayan** [comment]
This will happen when a deferred transaction executes but objectively fails. And it is a normal behavior.
