### ISSUE TITLE
STAT-49 ⁃ Account API for Smart Contract Developers #321

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#638]
Github issue [#321](https://github.com/EOSIO/eos/issues/321)

Account API would provide access to:

1. an account's permission tables
1. an account's balance (provided it is in scope)
1. other information available to native code

basing current requirements off of what chain_plugin.cpp get_account returns.

will add account.h with:
bool account_balance_get(void* ptr, uint32_t len)

account.hpp will have:
struct PACKED( account_balance ) { uint32_t account;...} // see ***balance_object

with namespace (account) methods for:
bool get(account_balance& b);           // populate b based on search with b.account

Acceptance Test Criteria:
1)Setup contract similar to test_account::test_balance validating each parameter in the returned account_balance or eosio::print if logs can be retrieved
2) setup an account
3) transfer funds to the account
4) stake and unstake funds
5) send a transaction with message for the contract
6) verify transaction is successful or logs have desired content

┆Attachments: <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10048&#x2F;Screen+Shot+2017-11-22+at+12.53.36+PM.png">Screen Shot 2017-11-22 at 12.53.36 PM.png</a>

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

* Account permissions are out of scope for STAT.
  * Account balance can be provided
  * Do we have any ideas what else would be useful?

[~admin] For STAT, I suggest we story point this for account balance. We can always create new issues for additional account data needed.

**Comment by blockone-syncclient** [comment]
➤ David Moss commented:

[~kevin.heifner] Agreed on story points for account balance.

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

[~admin][~thomas.cox]
We can story point this, but we need [~dan.larimer] to tell us what the (wasm_interface instrinsic) function declaration is, since this will affect contracts that will likely move to multi-threaded EOS.

**Comment by blockone-syncclient** [comment]
➤ David Moss commented:

[~brian.johnson] Okay, ask Dan in the private developers Telegram chat about the function declaration. He may not be available to respond until Monday, 10/23/2017.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

[~admin] You indicated that you would check with Dan.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

[~dan.larimer] Do you have an interface in mind for account balance? 
I noticed today [#585](https://github.com/EOSIO/eos/issues/585), someone is already asking for it.

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

SUGGESTED INTERFACE

Balance:
i64 account_balance(i64)   - pass in account name and return ShareType balance

Permissions:
in account.hpp:
struct Permission {  // everything in permission_object except id
      i64       owner;
      id_type parent;    // not sure what we want here, should it just be the parent account name
      i64       name;
      u64      auth;
}

in wasm_interface:
i64 account_permission(i64,i64,i32,i32)  -- pass in AccountName and PermissionName, and pointer to Permission (to populate) with size (for validation, could skip) and returns size if populated (or 1) and 0 if not
?? - do we need a function that returns all permissions for a given account name or all permissions with a given parent?  If so, do we want to use a pointer to an array of Permission objects, or what other suggestions?  If just look up by account name (not parent) could write into an pointer to array of i64 with PermissionNames

in account.hpp:
struct StakedBalance {
   i64 ownerName;
   i64 stakedBalance;
   i64 unstakingBalance;
   i32 lastUnstakingTime;
}

in wasm_interface:
i64 account_staked(i64,i32,i32)  -- pass in OwnerName, and pointer to StakedBalance (to populate) with size (for validation, could skip) and returns size if populated (or 1) and 0 if not

for more "other information available to native code", I need some clarification.  I think the already listed functions are the most important.

[~admin] [~dan.larimer] need input if this meets requirements

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

[~dan.larimer] 

  * Is the suggested API good for the suggested data?
  * Is the API complete or do we need more?

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

11/1/2017 Meeting with Dan.

Would like an api that follows how table access is provided. So account info would be pulled from an account table. This should be possible from any contract that provides account scope.

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

Need [~dan.larimer] and [~kevin.heifner] to review added API design

**Comment by blockone-syncclient** [comment]
➤ Christian Dunst commented:

This has been reviewed by Kevin. !Screen Shot 2017-11-22 at 12.53.36 PM.png|thumbnail!

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

Tested using a test contract.
Here is the result
Fetching account balance for inita

Account=8421048506461978624
        Balance amount=9993162095
        Balance symbol=1397703940
        Staked balance=0
        Staked balance symbol=1397703940
        Unstaking balance amount=0
        Unstaking balance symbol=1397703940
        Last unstaking time=4294967295918002

Here is the code snippet
void apply_malicious_account()
    {
        eosio::print("Fetching account balance for inita\n");
        eosio::account::account_balance b;

b.account = N(inita);
        eosio::account::get(b);
        eosio::print("\n\tAccount=", b.account);
        eosio::print("\n\tBalance amount=", (uint64_t) b.eos_balance.amount);
        eosio::print("\n\tBalance symbol=",b.eos_balance.symbol);
        eosio::print("\n\tStaked balance=", (uint64_t) b.staked_balance.amount);
        eosio::print("\n\tStaked balance symbol=", b.staked_balance.symbol);
        eosio::print("\n\tUnstaking balance amount=", (uint64_t) b.unstaking_balance.amount);
        eosio::print("\n\tUnstaking balance symbol=", b.unstaking_balance.symbol);
        eosio::print("\n\tLast unstaking time=", b.last_unstaking_time);
    }

**Comment by heifner** [comment]
Verified by QA.
