### ISSUE TITLE
Is it possible to call “updateauth” to change account keys from within a smart contract?

### ISSUE THREAD

**Issue by VtpVlan-oo7** [EOSIO/eos#6386]
I am trying to write a smart contract that changes the keys of an account (not itself). The transaction will be of course be authorized by the account for which the keys are changing.
I feel like it should look something like this: 
action(N(eosio), 
        N(updateauth), 
        N(eosbayitem), 
        fc::mutable_variant_object()
       ("account", "myaccount")
       ("permission", "owner")
       ("parent", "")
       ("auth",  authority("EOS8djkstZzKVY7BsWkT3CMQjngXMSgtoM2g3VAS65wZw1JLC4fML", 1)).send();

**Comment by taokayan** [comment]
Closed as no further reply. If you want to discuss further, please ask in https://eosio.stackexchange.com/
