### ISSUE TITLE
refund_request has expired but the core_liquid_balance is not updated.

### ISSUE THREAD

**Issue by Viterbo** [EOSIO/eos#6387]
my account name is gqydoobuhege and I have requested a refund of a previous stake for other accounts (also mine). If you get account info you will find the refund_request present with a request_time a week ago. I was expected to have those 114.0000 EOS already in my core_liquid_balance.

**how can I make effective the refund?**
Thanks

```
$ curl --data '{"account_name":"gqydoobuhege"}' 'https://api.eosio.cr/v1/chain/get_account'
{
    ...
    "refund_request": {
        "cpu_amount": "57.0000 EOS",
        "net_amount": "57.0000 EOS",
        "owner": "gqydoobuhege",
        "request_time": "2018-11-18T18:09:53"
    },
    ...
}
```
![refund_issue](https://user-images.githubusercontent.com/4420760/48972622-e52cea80-f00c-11e8-8abf-ae27cb01fc92.jpg)

**Comment by jgiszczak** [comment]
See #4119.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
