### ISSUE TITLE
mongodb full sync is being delayed

### ISSUE THREAD

**Issue by newbieh4cker** [EOSIO/eos#6389]
![image](https://user-images.githubusercontent.com/23703741/48987715-a0b46280-f164-11e8-927e-4cab466bba73.png)

left side is instance(using google cloud platform) running nodeos, with below spec.
 > n1-standard-8 (vCPU #8, RAM 30GB, SSD 1TB)
 > using back-up block from https://eosnode.tools/blocks
 > mongodb-queue-size = 4096
 > mongodb-api-cache-size = 10240
 > filter-on = *  / trying to make block explorer, so I need filter-on as *

right side is instance running docker, with below spec.
 > n1-highmeme-4 (vCPU #4, RAM 26GB, HDD 1TB)

Currently my nodeos+mongodb is syncing 7516120 blocks (about 25% of mainnet).
I think after about 500000 blocks, sync speed isn't catching mainnet's block generartion speed(1 sec = 2 blocks).

Is it normal??

**Comment by matthewdarwin** [comment]
You probably need more like 1TB RAM to get mainnet to sync to mongo at a reasonable speed.  You will certainly need larger than 1TB of disk space.   The database is growing very quickly.

**Comment by newbieh4cker** [comment]
@matthewdarwin  but as you can see, none of instances using more than allocated RAM

**Comment by matthewdarwin** [comment]
Disk cache.  You need very fast writes to disk.

**Comment by matthewdarwin** [comment]
I used to run, but stopped running mongo db 1 month ago because it got way too big.

**Comment by jgiszczak** [comment]
A `filter-on = *` mongo node needs extremely high IOPS.  You benefit from running two GCP instances: one for nodeos and one for mongodb.  They both use quite a lot of IOPS.  Barring that, read Google's [performance tuning](https://cloud.google.com/compute/docs/disks/performance) page and heed the advice about SSD IOPS scaling with the number of vCPUs.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions.  There are already some performance tuning threads. Thanks!
