### ISSUE TITLE
is there any way to avoid hard-replay when upgrade from 1.2.4 to 1.4.1?

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#6391]
is there any way to avoid hard-replay when upgrade from 1.2.4 to 1.4.1?

**Comment by jgiszczak** [comment]
If you are not running history plugin, you can upgrade to v1.4.1 or v1.4.4 without replay.  If you are running history plugin and wish an accurate representation of deferred transactions, `--replay-blockchain` is required.
