### ISSUE TITLE
Where is new account?

### ISSUE THREAD

**Issue by Onotoko** [EOSIO/eos#6392]
Hi guys,
I create 1.000.000 accounts on my computer(1GB RAM , 512 GB SSD) but EOS still run? Why?
Because I read on google, an account has 4KB RAM so if I create 1mil accounts that need ~ 4GB RAM. Please kindly let me know why? Thanks!

**Comment by conr2d** [comment]
RAM in eosio doesn't mean your physical memory. Your account data are stored under `data` directory created by `nodeos`.

**Comment by Onotoko** [comment]
Hi @conr2d , thank you for your comment. So It be synced to file?Right? But when I set 'max_ram_size' = 2GB, EOS is error? it is not clear if EOS create account if it store on disk

**Comment by conr2d** [comment]
Do you mean `max_ram_size` in `eosio.system` contract? Decreasing ram size is not allowed. Elaborate on your error.

**Comment by Onotoko** [comment]
Yes, because when I test it with million accounts, I must increase max_ram_size. 
And If I am not enough RAM, then new account when be wrote on disk, is it true?

**Comment by conr2d** [comment]
No, RAM is not memory. **RAM** in eosio means the storage (like DB) where persistent data is saved. 
https://github.com/EOSIO/eosio.contracts/blob/master/eosio.system/include/eosio.system/eosio.system.hpp#L55
The default max_ram_size is 64GiB, but this doesn't mean the server where you execute node should have 64GiB physical memory. Internally, eosio uses [ChainBase](https://github.com/eosio/chainbase) to store data, and RAM indicates this internal storage where global state are saved.

**Comment by conr2d** [comment]
If you require any further information, you can ask a question in [https://eosio.stackexchange.com](https://eosio.stackexchange.com/). Github issues is for reporting issues (such as bugs or enhancement suggestions) about EOSIO software.

**Comment by jgiszczak** [comment]
`nodeos` uses disk as backing storage for its RAM store of contract state, which includes accounts.  It uses memory-mapped I/O, and so can tolerate inadequate physical RAM to store all of the data, at the cost of a performance hit.

If you wish to induce a memory full error, you will need to `--delete` your current chain and change `max-ram-size` then attempt to recreate all of your test accounts on a new chain.  As conr2d says, you can not decrease max ram available to a chain.
