### ISSUE TITLE
Why don't we stop unix_server from listening in shutdown stage as well?

### ISSUE THREAD

**Issue by evsward** [EOSIO/eos#6393]
https://github.com/EOSIO/eos/blob/59626f1e6361df3b715e926ee13a9a8e84d177af/plugins/http_plugin/http_plugin.cpp#L550
add
```

      if(my->unix_server.is_listening())
         my->unix_server.stop_listening();
```

**Comment by jgiszczak** [comment]
Which should also unlink the socket file.  Pull requests gratefully accepted.  Please branch from the `develop` branch.

**Comment by spoonincode** [comment]
>We should also unlink the socket file

Already does that

**Comment by spoonincode** [comment]
https://github.com/EOSIO/eos/blob/59626f1e6361df3b715e926ee13a9a8e84d177af/plugins/http_plugin/include/eosio/http_plugin/local_endpoint.hpp#L205

**Comment by spoonincode** [comment]
oh and here too, so it looks like `stop_listenting()` should remove it
https://github.com/EOSIO/eos/blob/59626f1e6361df3b715e926ee13a9a8e84d177af/plugins/http_plugin/include/eosio/http_plugin/local_endpoint.hpp#L435

**Comment by evsward** [comment]
I think the destructor is not enough.  The shutdown stage need explicit call.

**Comment by spoonincode** [comment]
Fix merged
