### ISSUE TITLE
How does EOS count the historical balance of the account?

### ISSUE THREAD

**Issue by basketballCzm** [EOSIO/eos#6394]
I want to count the historical balance of an account, but I don't know how to process the data (data synced from the main chain and data returned by the RPC interface). I am very grateful for your message.

**Comment by jgiszczak** [comment]
The chain data on disk is not trivially accessible.  It is the ledger you are trying to see.  For a more accessible version of the same data, sync a node with either `mongo_db_plugin` or the third party `eosio_sql_plugin` enabled.  You may then use Mongo queries or SQL queries, respectively, to retrieve all transactions for an account, allowing you to see the full ledger.

If you have further question, please post it https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
