### ISSUE TITLE
multi_index::rbegin, rend, begin, and end all return const iterators

### ISSUE THREAD

**Issue by PhillipHamnett** [EOSIO/eos#6395]
They should return non-const iterators.

**Comment by conr2d** [comment]
Why do you think of that? You can access data by iterator with `*()` operator, but it doesn't mean you can modify table data with iterator directly. `eosio::multi_index` allow user to modify table data only when const iterator is passed as the first argument of `modify()`.

**Comment by jgiszczak** [comment]
conr2d is correct.  Only `modify()` is allowed to change rows.  As you can see reading the method, modifying a row is nontrivial.  To maintain the integrity of the indices, `modify()` must do a lot of work.

For consistency with typical usage of STL containers, you may use `cbegin()` etc. in your code, which are provided as well.  The `multi_index` impersonation of STL containers is imperfect, but many STL algorithms will still work.  The `multi_index` `const_iterator` is a bidirectional iterator, and carries that STL tag.  For algorithms which write, you just have to carefully construct predicates to use `modify()`.
