### ISSUE TITLE
EOS TDD development

### ISSUE THREAD

**Issue by pserg1** [EOSIO/eos#6405]
What is the best way to write contracts in a TDD style? The EOS source repo has unit tests which seem to be focused around testing the platform but my question is focused at the next level up (based on the assumption that the platform is tested and working).

**Comment by jgiszczak** [comment]
https://github.com/EOSIO/eosio.contracts/blob/master/tests/eosio.system_tests.cpp along with https://github.com/EOSIO/eosio.contracts/blob/master/tests/eosio.system_tester.hpp is an example of tests of the eosio.system contract in the eosio.contracts repository.  The patterns embodied in those source files can be imitated to test your own contracts.
