### ISSUE TITLE
apt eosio version is still 1.4.3

### ISSUE THREAD

**Issue by shwuhk** [EOSIO/eos#6406]
When will it be updated? Thanks.

**Comment by jgiszczak** [comment]
The Ubuntu builds of 1.4.4 are available [here](https://github.com/EOSIO/eos/releases/download/v1.4.4/eosio_1.4.4-1-ubuntu-16.04_amd64.deb) and [here](https://github.com/EOSIO/eos/releases/download/v1.4.4/eosio_1.4.4-1-ubuntu-18.04_amd64.deb) for Ubuntu 16.04 and 18.04 respectively.
