### ISSUE TITLE
No head block in fork db, perhaps we need to replay

### ISSUE THREAD

**Issue by snipper15** [EOSIO/eos#6408]
First , I have remove /.local/share/eosio/nodeos/data's data, and when I start a nodeos, I received some error,but I don't know what's wrong.
./nodeos -e -p eosio  --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --logconf ./log/nodeos.log
info  2018-11-28T14:57:49.071 thread-0  chain_plugin.cpp:333          plugin_initialize    ] initializing chain plugin
warn  2018-11-28T14:57:49.071 thread-0  chain_plugin.cpp:605          plugin_initialize    ] Starting up fresh blockchain with default genesis state.
info  2018-11-28T14:57:49.078 thread-0  http_plugin.cpp:422           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
info  2018-11-28T14:57:49.078 thread-0  net_plugin.cpp:2901           plugin_initialize    ] Initialize net plugin
info  2018-11-28T14:57:49.078 thread-0  net_plugin.cpp:2927           plugin_initialize    ] host: 0.0.0.0 port: 9876 
info  2018-11-28T14:57:49.078 thread-0  net_plugin.cpp:2998           plugin_initialize    ] my node_id is 6cedfbb904501c585d526c451d86fecf49501c29e6fa181b50d3985c65c2e925
info  2018-11-28T14:57:49.079 thread-0  main.cpp:110                  main                 ] nodeos version v1.4.4
info  2018-11-28T14:57:49.079 thread-0  main.cpp:111                  main                 ] eosio root is /home/ubuntu/.local/share
info  2018-11-28T14:57:49.079 thread-0  main.cpp:112                  main                 ] nodeos using configuration file /home/ubuntu/.local/share/eosio/nodeos/config/config.ini
info  2018-11-28T14:57:49.079 thread-0  main.cpp:113                  main                 ] nodeos data directory is /home/ubuntu/.local/share/eosio/nodeos/data
error 2018-11-28T14:57:49.079 thread-0  controller.cpp:1596           startup              ] No head block in fork db, perhaps we need to replay
warn  2018-11-28T14:57:49.079 thread-0  controller.cpp:574            initialize_fork_db   ]  Initializing new blockchain with genesis state                  
info  2018-11-28T14:57:49.131 thread-0  chain_plugin.cpp:707          plugin_startup       ] starting chain in read/write mode
info  2018-11-28T14:57:49.131 thread-0  chain_plugin.cpp:711          plugin_startup       ] Blockchain started; head block is #1, genesis timestamp is 2018-06-01T12:00:00.000
info  2018-11-28T14:57:49.131 thread-0  http_plugin.cpp:486           plugin_startup       ] start listening for http requests
error 2018-11-28T14:57:49.131 thread-0  http_plugin.cpp:493           plugin_startup       ] http service failed to start: Address already in use
error 2018-11-28T14:57:49.152 thread-0  main.cpp:152                  main                 ] Address already in use

**Comment by jgiszczak** [comment]
Some process is already using port 8888.  It may be another instance of nodeos already running or you may be running a proxy service on your machine.  Either shut it down, reconfigure it, or reconfigure nodeos to use a different port.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
