### ISSUE TITLE
When close keosd , all wallets which created before , would removed . I don't know why. thank you

### ISSUE THREAD

**Issue by snipper15** [EOSIO/eos#6413]
When close keosd , all wallets which created before , would removed . I don't know why. thank you

**Comment by snipper15** [comment]
sorry, I means when I  using the command : cleos wallet list to list all the wallets, list is empty.

**Comment by jgiszczak** [comment]
Is it launching with different data-dirs?  Try running it with a specific `--data-dir` argument twice in a row.

**Comment by spoonincode** [comment]
Closing due to lack of response from reporter
