### ISSUE TITLE
the balance is not equal when  use rpc get balance currency from two nodes 

### ISSUE THREAD

**Issue by yaanhyy** [EOSIO/eos#6414]
We push one  transaction  to The node 172.18.11.38:8888,  the transaction contain one action(yyloveuu1314 transfer 1 ZKS token to another account)， then node return trx_id.But the transaction is not recorded  in chain. the transaction failed . But when we use  the rpc(get balance currency) to query token balance, the node(172.18.11.38:8888)  subtract   1 ZKS from account yyloveuu1314. We use  the same rpc to query token balance from other node (https://api1.eosasia.one), the result is 29 ZKS. not subtract the amount from the failed transaction.
Is  there a bug in  eosio?  
```
C02WT5SXG8WN:cleos hongyuanyang$ ./cleos  -u http://172.18.11.38:8888    get currency balance zkstokensr4u yyloveuu1314 ZKS
28 ZKS
C02WT5SXG8WN:cleos hongyuanyang$ ./cleos  -u https://api1.eosasia.one    get currency balance zkstokensr4u yyloveuu1314 ZKS
29 ZKS

```

**Comment by jgiszczak** [comment]
Transactions are executed immediately on the receiving node, in anticipation of being successfully incorporated into the chain.  If the transaction ultimately fails and is not incorporated, the receiving node rolls back the transaction.  This can take some time.  Run your balance queries again and you will see they agree once more.

If you still have questions, please post them on https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
