### ISSUE TITLE
how to steal asset decimal？

### ISSUE THREAD

**Issue by boy-good** [EOSIO/eos#6418]
when i hava two asset like:
asset a = 5.0000 Token
asset b = 3.0000 Token
now i want to a/b , but result = 1
how to steal to 1.6667

I try to do it

double q = a.amount;
double w = b.amount;
double c = q / w;

error:
"error":{"code":3070002,"name":"wasm_execution_error","what":"Runtime Error Processing WASM","details":[{"message":"wabt execution failure (out of bounds memory access)"

**Comment by andriantolie** [comment]
Hi @boy-good,

I tried your above code, i.e.
```
        asset a(5, symbol("TOKEN", 4));
        asset b(3, symbol("TOKEN", 4));
        double c = double(a.amount)/ double(b.amount);
        eosio::print("c is ", c, "\n");
```
And I have no problem in getting the ratio of a and b as 1.666666666666667e+00

Could the "out of bond memory access" error that you encountered be caused by another part of your smart contract?
