### ISSUE TITLE
The wallet API configuration nginx agent returns 400

### ISSUE THREAD

**Issue by jiangzongyao** [EOSIO/eos#6423]
The wallet API configuration nginx agent returns 400？I'm having a headache！

**Comment by jgiszczak** [comment]
Be sure your use of the API works without nginx first, then configure nginx.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
