### ISSUE TITLE
STAT-40 ⁃ p2p perf send a notice of large blocks/txns

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#643]
(replaces github issue #408)

Phil:

Relates to #291. There is already a notice message, but it isn't being used in the manner described in #291. What I have is a notice message that is only used for transactions and then all recipients immediately turn around and request the contents right away. I'm not entirely sure of the benefit with blocks, since they have to be shared anyway

sMarking for M2. There is more discussion required to decide if this issue needs more work or is satisfied by the current code.

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

Hi Josh,

You are correct about the notice/request logic needing some love. It seems that it takes me some time after Dan explains an idea in his head before I get it right in mine. :-) 

The principal behind sending a notice of a large block or transaction is that a peer may hav several connections and therefore it may have received the block/txn from some other source thereby not needing to ask again. We hit on 3*MTU (which I'm currently estimating as 1300 bytes)  as a max size under which it makes sense to just send the payload.

My workspace code currently iterates throguh the list of transactions in a notice and will request only the ones it doesn't know about. Same with the blocks.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

From [~phil.mesnier] on github:

I think this issue is settled. There is a "just send it" max payload size value of 3 times my guess of the default MTU size, 1300 bytes. 3x because that is the minimum bandwidth cost of notify / request / deliver.

A new ticket should be opened if more work is needed.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

Closed in github

**Comment by coreylederer** [comment]
Sync'd the issue back to JIRA and closing.
