### ISSUE TITLE
old history plugin and new mongodb plugin bug?

### ISSUE THREAD

**Issue by piecesnbits** [EOSIO/eos#6434]
I think I found a bug in both plugins. While aggregating balances from transfer actions on our tokencontract "eosdactokens" I found trx_ids in the action that don't match the data.

mongodb (cryptolions api)
http://history.cryptolions.io/v1/history/get_actions/eosdactokens?skip=536000&limit=1000&sort=1
view raw json and search for: 452.0872 EOSDAC
![image](https://user-images.githubusercontent.com/44613132/49483180-80eeff80-f832-11e8-91d9-a1c3dd3e2e3c.png)

old history api (see explorer transactions)
https://explorer.eosdac.io/transfers
search for: 452.0872
![image](https://user-images.githubusercontent.com/44613132/49483235-b98ed900-f832-11e8-9ae3-b48bdc9089e0.png)
check the txids to compare the above data

https://www.bloks.io/transaction/ee63cd731c0e4c71e37d56019cf39ba710bdb272b35aee23918ef73551aa5b0b

https://www.bloks.io/transaction/b24dc83dba02b148b4ac9515270a31207d49b3533f4b141a43fd04c

according to the action data trxid "b24dc83dba02b148b..." should be an EOSDAC transfer but when getting the trx it seems that it is an eosio.token (eos) transfer. This in both mongodb plugin and old history plugin (eosdac explorer runs on the old history plugin).

**Comment by taokayan** [comment]
This is not a bug. If you look into the "traces" tab in https://www.bloks.io/transaction/b24dc83dba02b148b4ac9515270a31207d49b3533f4b141a43fd04c

The main action is actually EOS token transfer, and then the notification handler of account eosdaqooooo4 makes some inline actions to transfer EOSDAC to some other accounts. 

If you want to discuss further, please ask in https://eosio.stackexchange.com

**Comment by piecesnbits** [comment]
sorry i posted the wrong example. please recheck this. Why the trx_id is different and receiver sequence number is the same?
![image](https://user-images.githubusercontent.com/44613132/49518615-58511f00-f89f-11e8-8b99-9d7eff2dbb90.png)

http://history.cryptolions.io/v1/history/get_actions/eosdactokens?skip=535000&limit=1000&sort=1 a212cd7c0789b22ae6db34402b8e174ca9a8519e1db4baee35a9bf372fdaec09 60574d23fa461270a932f98f4786279bdf4428f79ca1cc6964e627d15cb772d8

**Comment by heifner** [comment]
block_id 01c2bffe3dcd8324fd1394f35b91fb349750c3fdf7d06cc94765c4b81834452d, block_num 29540350 is on a fork that didn't make it into the chain
block_id 01c2bffeb22f9205f6425c92b96c5d8acd0602bcbd6f87fcce90913974f47cb1, block_num 29540350 is irreversible and made it into the chain

https://eostracker.io/blocks/29540350

You are seeing transactions from a forked block that never reached irreversibly.

**Comment by piecesnbits** [comment]
Thank you for clarification! What would be best practice to detect the action is in a forked or non-forked block based on the data received. It would be handy that the plugin itself would detect this.

**Comment by tbfleming** [comment]
There is a way to detect forks in mongodb, but I'm not familiar with it. The alpha release of the state history plugin is out; you could try it with fill-postgresql.

**Comment by heifner** [comment]
The mongo plugin will mark a block_state as irreversible. However, there is no indication until irreversible.

**Comment by flux627** [comment]
If you set the `--mongodb-update-via-block-num` flag, then the plugin will overwrite forked blocks instead of keeping them around.
