### ISSUE TITLE
why not improve the eosio build script?

### ISSUE THREAD

**Issue by woshidama323** [EOSIO/eos#6438]
when compiling the eosio by using eosio_build.sh, we found the erorr below
Checking LLVM with WASM support installation...
	Installing LLVM with WASM...
	!! Unable to create directory /tmp/llvm-compiler !!

Actually ,It's a long journey for building eosio, and then an error happen with such problem
I mean why not remove the /tmp/llvm-compiler first and then create a new one so that the journey would go on ?

**Comment by matthewdarwin** [comment]
Well it really should make a unique temporary directory name instead.

**Comment by taokayan** [comment]
Have you tried "sudo ./eosio_build.sh"?

**Comment by woshidama323** [comment]
Actually , it's ok for me . I just need to remove the /tmp/llvm-compiler and run it again . I mean, maybe we can improve this script. just remove the tmp/llvm-compiler and then continue the step. I don't think it will cause anything

**Comment by luoyhang003** [comment]
sudo ?
