### ISSUE TITLE
when nodeos  sync from main-net,  throw with  much errors 

### ISSUE THREAD

**Issue by vpants** [EOSIO/eos#6440]
Version:
  OS: Ubuntu:16.04
  Nodeos: 1.4.1
  Runtime:Docker-18.06.00

Opeartor:
  blocks recover from snapshot

Errors :
error 2018-12-06T08:14:33.494 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: Player didn't hit or double down 
error 2018-12-06T08:14:33.498 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: Player didn't hit or double down 
error 2018-12-06T08:14:33.514 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: Player didn't hit or double down 
error 2018-12-06T08:14:33.537 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: Payout amount mismatch 
error 2018-12-06T08:14:33.550 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: Player didn't hit or double down 
error 2018-12-06T08:14:33.618 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: Player didn't hit or double down 
error 2018-12-06T08:14:36.990 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: Player didn't hit or double down
error 2018-12-06T08:15:10.992 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: Game not found 
error 2018-12-06T08:15:13.340 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: bet not found
error 2018-12-06T08:15:17.590 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: you have a pending game. please wait. 
error 2018-12-06T08:15:18.329 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: you have a pending game. please wait.
error 2018-12-06T08:45:12.191 thread-0  wasm_interface.cpp:933        eosio_assert         ] message: Hand bet amount mismatch

**Comment by taokayan** [comment]
This is not an issue. However we will make it configurable to suppress those assertion message in the smart contracts.

**Comment by spoonincode** [comment]
these are no longer shown by default, closing
