### ISSUE TITLE
when use contracts/eosin.token to issue token, can not query each account's balance.  

### ISSUE THREAD

**Issue by readygo586** [EOSIO/eos#6441]
After parsing the eosin.token.abi, I found there are  no _accounts and stats_ tables, which are different from https://github.com/EOSIO/eos/tree/master/contracts/eosio.token/eosio.token.abi. 
Is there any missing when I generate the abi file?  
![image](https://user-images.githubusercontent.com/41469645/49590499-04316200-f9a7-11e8-86ea-7556dc996a5e.png)

**Comment by jgiszczak** [comment]
Which tool did you use to generate the abi file?  You may need to use the most recent release of [eosio.cdt](https://github.com/EOSIO/eosio.cdt).

**Comment by readygo586** [comment]
I update to the latest eos1.5.0 and cdt 1.4.1, and follow the instructions in https://developers.eos.io/eosio-home/docs/your-first-contract to create a contracts/nyhello/myhello.cpp.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/41469645/49640322-4363bf80-fa48-11e8-9621-45565c708b22.png">

The   myhello.abi is **EMPTY**,  looks like bleow.
 <img width="592" alt="image" src="https://user-images.githubusercontent.com/41469645/49638904-8c197980-fa44-11e8-8929-4f1aa389f9a2.png">

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/41469645/49638878-7a37d680-fa44-11e8-8fa2-07c00a665271.png">

if I change the class name from _hello_ to _myhello_, then it can generate a valid .abi file, may some improvement are necessary.

**Comment by taokayan** [comment]
try ```CONTRACT myhello : public eosio::contract {```

If you still need help and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
