### ISSUE TITLE
Error in starting up `nodeos`

### ISSUE THREAD

**Issue by pskanade** [EOSIO/eos#6443]
Getting error when trying to startup nodeos. I followed all the steps from getting started guide and at [Step 1.2](https://developers.eos.io/eosio-home/docs/getting-the-software#section-step-1-2-start-nodeos)

Following is the command and its output that I got -
```
  % nodeos -e -p eosio \                                                                                                                                                              !6633
--plugin eosio::producer_plugin \
--plugin eosio::chain_api_plugin \
--plugin eosio::http_plugin \
-d /Users/pskanade/projects/eos/contracts/eosio/data \
--config-dir /Users/pskanade/projects/eos/contracts/eosio/config \
--access-control-allow-origin=* \
--contracts-console \
--http-validate-host=false \
—filter-on=‘*’ >> nodeos.log 2>&1 &
[2] 17551
zsh: no matches found: --access-control-allow-origin=*
[2]  + 17551 exit 1     nodeos -e -p eosio --plugin eosio::producer_plugin --plugin  --plugin  -d
```

I am using macbook air with mojave. Please help !

**Comment by spoonincode** [comment]
Try changing the above to

```
nodeos -e -p eosio \
--plugin eosio::producer_plugin \
--plugin eosio::chain_api_plugin \
--plugin eosio::http_plugin \
-d /Users/pskanade/projects/eos/contracts/eosio/data \
--config-dir /Users/pskanade/projects/eos/contracts/eosio/config \
'--access-control-allow-origin=*' \
--contracts-console \
--http-validate-host=false \
'--filter-on=*' >> nodeos.log 2>&1 &
```

**Comment by pskanade** [comment]
Thanks, it worked !! :)

**Comment by pskanade** [comment]
This might sound silly, but why changing these options to quoted string is required?

**Comment by spoonincode** [comment]
The shell is going to expand the '*' character to all files in the directory. Just like when you do a `ls *` for example. So you need to tell the shell not to expand it and treat it literally. I will try to get the docs updated.

**Comment by spoonincode** [comment]
docs fixed

**Comment by coreycottrell** [comment]
using ubuntu in a VM (windows 10 pro)  same spot but im getting 

corey@corey-VirtualBox:~$ nodeos -e -p eosio \
> --plugin eosio::producer_plugin \
> --plugin eosio::chain_api_plugin \
> --plugin eosio::http_plugin \
> --plugin eosio::history_plugin \
> --plugin eosio::history_api_plugin \
> --access-control-allow-origin='*' \
> --contracts-console \
> --http-validate-host=false \
> --verbose-http-errors >> nodeos.log 2>&1 &
[1] 31557
corey@corey-VirtualBox:~$ tail -f nodeos.log

Command 'nodeos' not found, did you mean:

  command 'nodejs' from deb nodejs
  command 'nodefs' from deb noweb

Try: sudo apt install <deb name>

tried the above fix and no joy

**Comment by jgiszczak** [comment]
@coreycottrell The easiest way for you to install nodeos is to download the appropriate .deb file from the 
[releases page](https://github.com/EOSIO/eos/releases) for your version of Ubuntu and use `dpkg -i <deb-file>`.  There is currently no apt repository available.  If you receive errors about missing dependencies after installing the eosio package, also run `sudo apt-get -f install` which will fetch and install any missing packages needed.

If you still have the problem and wish to discuss it further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by coreycottrell** [comment]
Perfect thank you so much
