### ISSUE TITLE
Can't install on Debian 8.0

### ISSUE THREAD

**Issue by ChrysmOre** [EOSIO/eos#6447]
Following the basic instructions the eosio_1.5.0-1-ubuntu-18.04_amd64.deb fails when trying to run apt install. It can't seem to find the package at all. Error:

.
.
.E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'mysql-utilities-commercial' was not found
E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'fish-common' was not found
E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'fish-dbg' was not found
E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'slack-desktop' was not found
E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'libudev0' was not found
E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'libgcrypt11' was not found
E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'libcurl4' was not found
E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'sublime-text' was not found
E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'sublime-merge' was not found
E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'mysql-connector-java' was not found
E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'atom' was not found
E: Release 'eosio_1.5.0-1-ubuntu-18.04_amd64.deb' for 'discord' was not found
.
.
.

etc (pages and pages of the above)

**Comment by jgiszczak** [comment]
Debian 8 is not supported.  Debian 9 is supported by compiling from source only.  Pre-built Debian binaries are not available.  The instructions mention the word Debian, but are referring to the supported Debian derivatives Ubuntu and Mint.

You'll need to run `./eosio_build.sh` to compile on Debian.
