### ISSUE TITLE
What is the sender_id in transaction?

### ISSUE THREAD

**Issue by quocle108** [EOSIO/eos#6449]
What is the sender_id? why the data_type is uint128_t? 
I thought it should be account name

eos/contracts/eosiolib/transaction.hpp
```
   class transaction : public transaction_header {
   public:
      transaction(time_point_sec exp = time_point_sec(now() + 60)) : transaction_header( exp ) {}

      void send(const uint128_t& sender_id, account_name payer, bool replace_existing = false) const {
         auto serialize = pack(*this);
         send_deferred(sender_id, payer, serialize.data(), serialize.size(), replace_existing);
      }
...
}
```

**Comment by taokayan** [comment]
sender_id should be the id of the deferred transaction. 

If you still need help and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
