### ISSUE TITLE
Error 3050003: eosio_assert_message assertion failure - unclear error message

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#6452]
Getting unclear error message, running with --verbose-http-errors
```
cleos push action eosio claimrewards eosiodetroit -p eosiodetroit@claims
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: read
pending console output:
```

**Comment by taokayan** [comment]
Please start nodeos with  --contracts-console

If you still need help and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by bitcoiners** [comment]
I restarted with  --contracts-console. The only message I see:
Error 3050003: eosio_assert_message assertion failure

**Comment by dixia** [comment]
@bitcoiners could add --verbose-http-errors as well. That might make print out more info

**Comment by bitcoiners** [comment]
> @bitcoiners could add --verbose-http-errors as well. That might make print out more info

As mentioned in original post nodeos is running with --verbose-http-errors, still no useful message is printed out.

**Comment by gaboesquivel** [comment]
This can also happen if change the structure of your table without erasing the previous content see https://github.com/clockknock/eos-contract-example/tree/master/02-erase-table

**Comment by theblockstalk** [comment]
@gaboesquivel we experienced this error several times over the weekend, even after clearing the data tables that had changed structure. the only solution we found was to create a new account.

**Comment by abourget** [comment]
This solved it for me: https://github.com/EOSIO/eos/issues/4394
