### ISSUE TITLE
Latest docker image 'eos-dev' does not  have `eosiocpp`

### ISSUE THREAD

**Issue by pskanade** [EOSIO/eos#6453]
I followed the [quickstart link](https://developers.eos.io/eosio-nodeos/docs/docker-quickstart) with one change - I pulled the latest image.
Here is what the results look like when I checked for `eosiocpp` in the container -
```
➜  with_docker $ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZEeosio/eos-dev       latest              0174ae6fe90a        3 days ago          3.19GB
hello-world         latest              4ab4c602aa5e        3 months ago        1.84kB➜  with_docker docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
d222c5fad1be        eosio/eos-dev       "/bin/bash -c 'nodeo…"   57 seconds ago      Up 56 seconds       0.0.0.0:8888->8888/tcp   nodeos
➜  with_docker $ docker exec -it nodeos bash
root@d222c5fad1be:/# ls /opt/eosio/bin/
cleos  eosio-blocklog  eosio-launcher  eosio-s2wasm  eosio-wast2wasm  keosd  nodeos  nodeosd.sh
```

It seems that the latest version of `eos-dev` image does not have `eosiocpp`

**Comment by taokayan** [comment]
eosiocpp is deprecated and removed from the latest version of docker. Please use eosio-cpp (cdt) instead. 

If you still need help and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
