### ISSUE TITLE
who pay the defer transaction's cpu?

### ISSUE THREAD

**Issue by 2557171839** [EOSIO/eos#6454]
i know the defer transaction can choose the ram payer,but how to choose the cpu payer?

**Comment by taokayan** [comment]
I guess it is paid by the contract owner.

If you still need help and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
