### ISSUE TITLE
Make multi_index accessible via offset / offset dereference operator ([])

### ISSUE THREAD

**Issue by cmadh** [EOSIO/eos#6455]
In some cases where the sender of a transaction or the contract itself exactly knows the index of an entry in a Multi-Index it seems not to be clever to use iterators in times where CPU is rare and expensive.

I know, the C-API contains functions for direct access but with more complex structures a cast from void* to struct can be very awkward or even impossible.

Best, Corvin

**Comment by taokayan** [comment]
The multi_index table uses a tree structure to order its data, which implicitly imply that any lookup needs logarithmic time. I don't think you are able to make it faster than O(logN).

**Comment by jgiszczak** [comment]
`db_get_i64()` accepts an iterator and retrieves an entire table row that has already been located.  In the C API, the function that locates a row is `db_find_i64()`.  It performs the logarithmic lookup.  There is no way to bypass that lookup.
