### ISSUE TITLE
Cannot get inline action history

### ISSUE THREAD

**Issue by quocle108** [EOSIO/eos#6456]
I've tried get inline actions from cleos/demux/RPC API but i couldn't
then I've checked mongodb storage, it's there. So there any ways to get it directly from blockchain except from mogodb

**Comment by jgiszczak** [comment]
The only way to get data _directly_ from the block chain is to build a tool to walk the block log on disc and extract information from it.  But I don't suppose that's what you meant.

State history plugin has been released as Alpha status in v1.5.0.  You probably shouldn't be spending money based on what it says, but you can start building software around it and testing to see if it meets your needs.  It is the supported successor to history_plugin.  Until it is ready, mongo_db_plugin is your best production choice.
