### ISSUE TITLE
Malformed private key pair

### ISSUE THREAD

**Issue by NathanKim91** [EOSIO/eos#6461]
When I am trying to configure ["Local Multi-Node Testnet"](https://developers.eos.io/eosio-nodeos/docs/local-multi-node-testnet) there is some problem.

---

$ nodeos --producer-name inita --plugin eosio::chain_api_plugin --plugin eosio::net_api_plugin --http-server-address 127.0.0.1:8899 --p2p-listen-endpoint 127.0.0.1:9877 --p2p-peer-address 127.0.0.1:9876 --config-dir node2 --data-dir node2 --private-key [\"EOS6RxxLBrMG6bCBtC8VSXYiepD6zwFsa***************\", \"5KVTMsHfMgggLxyuLsxAFyjecHc8JrxSh3b**************\"]
info  2018-12-11T02:21:09.230 thread-0  chain_plugin.cpp:333          plugin_initialize    ] initializing chain plugin
warn  2018-12-11T02:21:09.230 thread-0  chain_plugin.cpp:605          plugin_initialize    ] Starting up fresh blockchain with default genesis state.
info  2018-12-11T02:21:09.232 thread-0  http_plugin.cpp:422           plugin_initialize    ] configured http to listen on 127.0.0.1:8899
info  2018-12-11T02:21:09.232 thread-0  net_plugin.cpp:2901           plugin_initialize    ] Initialize net plugin
info  2018-12-11T02:21:09.232 thread-0  net_plugin.cpp:2927           plugin_initialize    ] host: 127.0.0.1 port: 9877 
info  2018-12-11T02:21:09.232 thread-0  net_plugin.cpp:2998           plugin_initialize    ] my node_id is 7e0807136aa5d5ff598da41cc5edd81dcb6eab107e1e9244d57bcfc73384c6c7
error 2018-12-11T02:21:09.234 thread-0  producer_plugin.cpp:612       plugin_initialize    ] Malformed private key pair
error 2018-12-11T02:21:09.234 thread-0  producer_plugin.cpp:612       plugin_initialize    ] Malformed private key pair
info  2018-12-11T02:21:09.235 thread-0  main.cpp:110                  main                 ] nodeos version v1.4.4
info  2018-12-11T02:21:09.235 thread-0  main.cpp:111                  main                 ] eosio root is /Users/nate/Library/Application Support
info  2018-12-11T02:21:09.235 thread-0  main.cpp:112                  main                 ] nodeos using configuration file /Users/nate/Dev/eos_/eos/build/node2/config.ini
info  2018-12-11T02:21:09.235 thread-0  main.cpp:113                  main                 ] nodeos data directory is /Users/nate/Dev/eos_/eos/build/node2
error 2018-12-11T02:21:09.235 thread-0  controller.cpp:1596           startup              ] No head block in fork db, perhaps we need to replay
warn  2018-12-11T02:21:09.235 thread-0  controller.cpp:574            initialize_fork_db   ]  Initializing new blockchain with genesis state                  
info  2018-12-11T02:21:09.262 thread-0  chain_plugin.cpp:707          plugin_startup       ] starting chain in read/write mode
info  2018-12-11T02:21:09.262 thread-0  chain_plugin.cpp:711          plugin_startup       ] Blockchain started; head block is #1, genesis timestamp is 2018-06-01T12:00:00.000
info  2018-12-11T02:21:09.262 thread-0  http_plugin.cpp:486           plugin_startup       ] start listening for http requests
error 2018-12-11T02:21:09.263 thread-0  http_plugin.cpp:493           plugin_startup       ] http service failed to start: Address already in use
error 2018-12-11T02:21:09.269 thread-0  main.cpp:152                  main                 ] Address already in use

---

it says there is malformed private key pair.
However I followed the step what is written.
Please let me know what is the problem.
Thanks.

**Comment by matthewdarwin** [comment]
probably you want single quotes around the key so the shell doesn't mess that up. as in:

-private-key '["EOS6RxxLBrMG6bCBtC8VSXYiepD6zwFsa***************", "5KVTMsHfMgggLxyuLsxAFyjecHc8JrxSh3b**************"]'

**Comment by NathanKim91** [comment]
@matthewdarwin thanks, i found the problem. A space between the key pair was making trouble.

However, I still have following problem.

---

$ nodeos --producer-name inita --plugin eosio::chain_api_plugin --plugin eosio::net_api_plugin --http-server-address 127.0.0.1:8899 --p2p-listen-endpoint 127.0.0.1:9877 --p2p-peer-address 127.0.0.1:9876 --config-dir node2 --data-dir node2 --private-key [\"EOS6RxxLBrMG6bCBtC8VSXYiepD6zwFsaUNMBf3DjbC8xorBoqyHj\",\"5KVTMsHfMgggLxyuLsxAFyjecHc8JrxSh3bNaWtgjonbiD94iTv\"]
info  2018-12-11T05:32:25.859 thread-0  chain_plugin.cpp:333          plugin_initialize    ] initializing chain plugin
info  2018-12-11T05:32:25.867 thread-0  block_log.cpp:134             open                 ] Log is nonempty
info  2018-12-11T05:32:25.867 thread-0  block_log.cpp:161             open                 ] Index is nonempty
info  2018-12-11T05:32:25.869 thread-0  http_plugin.cpp:422           plugin_initialize    ] configured http to listen on 127.0.0.1:8899
info  2018-12-11T05:32:25.869 thread-0  net_plugin.cpp:2901           plugin_initialize    ] Initialize net plugin
info  2018-12-11T05:32:25.869 thread-0  net_plugin.cpp:2927           plugin_initialize    ] host: 127.0.0.1 port: 9877 
info  2018-12-11T05:32:25.869 thread-0  net_plugin.cpp:2998           plugin_initialize    ] my node_id is f1ec6194129ca44a74e04a717e129957f534bc51235dd3751b97ea22fc662e1f
warn  2018-12-11T05:32:25.869 thread-0  producer_plugin.cpp:610       plugin_initialize    ] "private-key" is DEPRECATED, use "signature-provider=EOS6RxxLBrMG6bCBtC8VSXYiepD6zwFsaUNMBf3DjbC8xorBoqyHj=KEY:***************************************************"
info  2018-12-11T05:32:25.869 thread-0  main.cpp:110                  main                 ] nodeos version v1.4.4
info  2018-12-11T05:32:25.869 thread-0  main.cpp:111                  main                 ] eosio root is /Users/nate/Library/Application Support
info  2018-12-11T05:32:25.870 thread-0  main.cpp:112                  main                 ] nodeos using configuration file /Users/nate/Dev/eos_/eos/build/node2/config.ini
info  2018-12-11T05:32:25.870 thread-0  main.cpp:113                  main                 ] nodeos data directory is /Users/nate/Dev/eos_/eos/build/node2
info  2018-12-11T05:32:25.870 thread-0  chain_plugin.cpp:707          plugin_startup       ] starting chain in read/write mode
info  2018-12-11T05:32:25.870 thread-0  chain_plugin.cpp:711          plugin_startup       ] Blockchain started; head block is #1, genesis timestamp is 2018-06-01T12:00:00.000
info  2018-12-11T05:32:25.870 thread-0  http_plugin.cpp:486           plugin_startup       ] start listening for http requests
error 2018-12-11T05:32:25.870 thread-0  http_plugin.cpp:493           plugin_startup       ] http service failed to start: Address already in use
error 2018-12-11T05:32:25.873 thread-0  main.cpp:152                  main                 ] Address already in use

---

It says the address already in use.
I am running the keosd now.
What's wrong in here?

**Comment by NathanKim91** [comment]
Oh i found what a problem is.
It was needed to exit the keosd.
