### ISSUE TITLE
use eosio-cpp -I include -o eosio.token.wasm src/eosio.token.cpp --abigen cannot create .abl file

### ISSUE THREAD

**Issue by Lynette-xin** [EOSIO/eos#6468]
use eosio-cpp -I include -o eosio.token.wasm src/eosio.token.cpp --abigen cannot create .abl file
and i switch to "eosio-abigen hello.cpp --output=hello.abi",it can not help also

**Comment by jgiszczak** [comment]
`eosio.token.cpp` in this repository has a hand-written ABI that can not be reproduced with `eosio-cpp`.  The version in the [contracts repository](https://github.com/EOSIO/eosio.contracts) should be compatible with the eosio.cdt tools.

To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. You should first post the problem, with direct text copies of your command line and the resulting error messages, at https://eosio.stackexchange.com. Thanks!
