### ISSUE TITLE
unbelievable  !!!! get table eosio eosio namebids --key-type i64 --index 2 -r -l 1  

### ISSUE THREAD

**Issue by lsf1001** [EOSIO/eos#6473]
![image](https://user-images.githubusercontent.com/40747755/49935531-36454580-ff0c-11e8-9897-bcd9b67b4176.png)

What it means here is that if the bid price is negative it means that the account name has been bid for, whereas the negative number shown here is kind of unbelievable, and the negative number is the opposite of the bid amount

**Comment by jgiszczak** [comment]
This is working as intended.  Try `cleos -u https://api.eosnewyork.io system bidnameinfo -j me` to see the raw info.  The highest bid is actually a negative number in the table.  This is used as a marker by the system contract when an auction has closed but the name is unclaimed.

When the holder of the `ujkuiihddt5q` account exercises their right to create the `me` account, the bid will be deleted from the `namebids` table.  All negative bids in the table are closed auctions with unclaimed names.
