### ISSUE TITLE
Strange transaction

### ISSUE THREAD

**Issue by borovik96** [EOSIO/eos#6474]
I have the transaction with next id: `2d17b1b2e85840315ad9a004c9982eba6c31ae21b5561d78c38c16717fb96d2c`

In one explorer it has status `delayed` [eospark](https://eospark.com/tx/2d17b1b2e85840315ad9a004c9982eba6c31ae21b5561d78c38c16717fb96d2c), at the same time another explorer says it is `executed` [blocks.io](https://bloks.io/transaction/2d17b1b2e85840315ad9a004c9982eba6c31ae21b5561d78c38c16717fb96d2c)

Which one explorer I can trust and how I can have 100% confidence that money was transferred?

Also what means `delayed` status and where can I find information about transaction statuses?

Will appreciate any help.

**Comment by heifner** [comment]
It was executed:
https://gist.github.com/heifner/af84debe60c69cb4b4c4e427db75c735
And is irreversible:
https://gist.github.com/heifner/a2a2a10f479baa9949410e87f44234c0

Here is the input transaction:
https://gist.github.com/heifner/7cf7c149ca48ce3056b96dbada361a1d

Note the delay_sec of 5. This means it was set to execute 5 seconds after submitting.

100% confidence would come from running your own validation node.
