### ISSUE TITLE
Bios-Boot-Sequence, nodes not producing blocks

### ISSUE THREAD

**Issue by itxlieni** [EOSIO/eos#6475]
Dear community

I try to setup a multinode test net with its own test currency.
I followed the boot-sequence-tutorial from eosio.
The Problem is that my nodes except the genesis node don’t produce blocks.

First i changed the SYS Currency in the CMakeLists.txt
I also changed it in also in /eos/eos/libraries/fc/include/fc/crypto/public_key.hpp, this way I am able to create keys with my test currency symbol CCT, i created a new key and modified the default eosio root key in CMakeLists.txt.

Genesis nodes is up and running (producing blocks)
I deployed the bios, system, token and msig contracts.
I created the CCT token (1’000’000’000 and issued 100’000’000 of it to eosio account).
Then I created the accounts for the other 5 producers, sent them some token, and stacked for these users.
After I registered them as producers ($ cleos system regproducer ccbp2 PUBKEY URL)
I started all the other nodes with:
$ nodeos --genesis-json /home/ubuntu/.local/share/eosio/nodeos/config/genesis.json
I can see that the other 5 nodes are connected to each other and receive the blocks (on_incomong_block)
Then I voted with each account for them self ($ cleos system voteproducer prods ccbp2 ccbp2)
ubuntu@ccbp1:~$ cleos system listproducers
Producer      Producer key     Url          Scaled votes
ccbp11        CCT6Q....     ....                0.1429
ccbp12        CCT8E...     .....                 0.1429
ccbp13        CCT5F.....     .....             0.1429
ccbp5         CCT6e.....     ......               0.1429
ccbp4         CCT8U......     .....                0.1429
ccbp2         CCT7B.....     ....                  0.1429
ccbp3         CCT6e......     ......                 0.1429

but still, the only node is producing blocks is the genesis node, do I missed something?
Here a config of one of the servers.

bnet-endpoint = 0.0.0.0:4321
bnet-follow-irreversible = 0
bnet-no-trx = false
bnet-peer-log-format = ["${_name}" ${_ip}:${_port}]

blocks-dir = "blocks"
abi-serializer-max-time-ms = 15000
chain-state-db-size-mb = 1024
chain-state-db-guard-size-mb = 128
reversible-blocks-db-size-mb = 340
reversible-blocks-db-guard-size-mb = 2
chain-threads = 2
contracts-console = false

read-mode = speculative
validation-mode = full
disable-ram-billing-notify-checks = false
https-client-validate-peers = 1

http-server-address = 127.0.0.1:8888
access-control-allow-credentials = false

max-body-size = 1048576
verbose-http-errors = false
http-validate-host = 1
max-login-requests = 1000000
max-login-timeout = 60

p2p-listen-endpoint = xxx.localip.xxx:9876
p2p-server-address = xxx.xxx.xxx.1

#public ips
p2p-peer-address = xxx.xxx.xxx.2:9876
p2p-peer-address = xxx.xxx.xxx.3:9876
p2p-peer-address = xxx.xxx.xxx.4:9876
p2p-peer-address = xxx.xxx.xxx.4:9876
p2p-peer-address = xxx.xxx.xxx.5:9876
p2p-peer-address = xxx.xxx.xxx.6:9876

p2p-max-nodes-per-host = 1
agent-name = "ccbp12"
allowed-connection = any
max-clients = 25
connection-cleanup-period = 30
max-cleanup-time-msec = 10
network-version-match = 0

sync-fetch-span = 100
max-implicit-request = 1500
use-socket-read-watermark = 0
peer-log-format = ["${_name}" ${_ip}:${_port}]

enable-stale-production = true
pause-on-startup = false
max-transaction-time = 30
max-irreversible-block-age = -1

producer-name = ccbp13
#(DEPRECATED - Use signature-provider instead) Tuple of [public key, WIF private key] (may specify multiple times) (eosio::producer_plugin)
#private-key = 
signature-provider = CCT5F....=KEY:....
#each nodes has his own Key pair

keosd-provider-timeout = 5
produce-time-offset-us = 0
last-block-time-offset-us = 0
incoming-defer-ratio = 1
snapshots-dir = "snapshots"
state-history-dir = "state-history"
trace-history = false
chain-state-history = false

state-history-endpoint = 0.0.0.0:8080
txn-reference-block-lag = 0

plugin = eosio::producer_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::http_plugin
#plugin = eosio::history_api_plugin
plugin = eosio::bnet_plugin
plugin = eosio::net_api_plugin

**Comment by jgiszczak** [comment]
You need to vote a minimum of of 150000000 tokens before the system is activated.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
