### ISSUE TITLE
when Publishing contract , happened Serialization Error Processing WASM error

### ISSUE THREAD

**Issue by snipper15** [EOSIO/eos#6477]
version:
Publishing contract...
Error 3070003: Serialization Error Processing WASM
Error Details:
mutable globals cannot be imported: globalImport.type.isMutable
pending console output:

**Comment by spoonincode** [comment]
Was this .wasm built with eosio.cdt or something else? What version of eosio.cdt?

Can you attach the .wasm file to this issue?

**Comment by spoonincode** [comment]
okay thanks, but you're going to at least need to attach the .wasm file here for investigation

**Comment by spoonincode** [comment]
Do you think you may have used `-c` when invoking eosio-cpp?

**Comment by WendySanarwanto** [comment]
This issue still happened, when I followed tutorials in here: https://developers.eos.io/eosio-home/docs/token-contract. Could you please re-open this ? See this screenshot:

![image](https://user-images.githubusercontent.com/18456618/53605956-072d9e80-3bf4-11e9-923e-11715773b2fb.png)

#### Environments:
1. OS: Ubuntu 18.04.2 LTS
2. EOSIO version 1.6.1
3. EOS.cdt version 1.4.1

**Comment by spoonincode** [comment]
Please show command line used to compile contract and any output from compiling contract.

**Comment by WendySanarwanto** [comment]
Hello @spoonincode ,

This is the command that I invoked for compiling the `eosio.token` contract (as suggested in this [link](https://developers.eos.io/eosio-home/docs/token-contract)):

![image](https://user-images.githubusercontent.com/18456618/53676963-3b808800-3ce4-11e9-9377-f271efe30fc9.png)

As shown in the screenshot, there's `` error message returned. Do you think this is the cause of `Error 3070003: Serialization Error Processing WASM` when deploying the contract ?

**Comment by WendySanarwanto** [comment]
I have tried to update the latest version of [eosio.contracts](https://github.com/EOSIO/eosio.contracts) and my [eos.cdt](https://github.com/EOSIO/eosio.cdt) to version `1.5.0`, then recompile & deploy the `eosio.token` contract, but it's still failing with same error. 

![image](https://user-images.githubusercontent.com/18456618/53677440-e4ca7c80-3cea-11e9-92b9-3f726b52a876.png)

**Comment by spoonincode** [comment]
@WendySanarwanto I would recommend trying to resolve the eosio-cpp error first, potentially by putting an issue over in https://github.com/EOSIO/eosio.cdt/, as that's almost certainly your problem.

The `mutable globals cannot be imported: globalImport.type.isMutable` error is typically because an "intermediate" wasm object file is being used vs. a final "linked" wasm module. It's possible your eosio.token.wasm is an intermediate file and not the final linked output. I think newer eosio-cpp improves the way this is handled so that intermediate files have a .o extension and thus aren't easily as confused. But, I don't know if that fix was 1.5 or 1.6 of eosio.cdt

**Comment by WendySanarwanto** [comment]
Hello @spoonincode, thanks for your kind response. I'd like to inform you that I got the issue resolved through doing these following actions:

* Get rid my current eosio installation and reinstall the latest stable version of [eosio](https://github.com/eosio/eos/releases/download/v1.6.2/eosio_1.6.2-1-ubuntu-18.04_amd64.deb)

* Git clone the [eosio.cdt](https://github.com/EOSIO/eosio.cdt) repository, checkout `release/1.6.x` branch and build the source (run `./build.sh` command inside the repo's directory). Confirm that the build is succeded then run `sudo ./install.sh` command.

* Try use the brand new `eosio-cpp` & `cleos` commands for compiling and deploying a smartcontract's `abi` and `wasm` files. Confirm that compile and deploy processes are succeded

![image](https://user-images.githubusercontent.com/18456618/53696012-98bc2c80-3dfd-11e9-9383-1583c135ca0b.png)

Hope this information would be useful to anyone who would bump to this issue in future.
