### ISSUE TITLE
3090003 nodejs push_transaction.How to get 'packed_trx'?

### ISSUE THREAD

**Issue by zpc10** [EOSIO/eos#6487]
How to pack transaction without cleos?
So the new API only accepts a packed_trx but there is no RPC call to pack a signed transaction.
How can it be done on system without cleos installed? Is there any implementation in pure NodeJS ?

**Comment by jgiszczak** [comment]
See https://github.com/EOSIO/eosjs or https://github.com/EOSIO/eosjs2 for implementations.
