### ISSUE TITLE
Using read_only API in chain_plugin with multi-threading read causes some iostream error in Docker

### ISSUE THREAD

**Issue by necokeine** [EOSIO/eos#6488]
I found the read_only API in chain_plugin isn't so good to use in multi-threading read. I guess it caused by the delayed disk flush.
Is there any plan to refactor the [block_log](https://github.com/EOSIO/eos/blob/master/libraries/chain/include/eosio/chain/block_log.hpp) to something like mmap implement? I think it will be helpful in exposing fixed blocks data for analysis purpose.

**Comment by heifner** [comment]
What do you mean by multithreaded read?

**Comment by necokeine** [comment]
I created several read_only API objects to read out all blocks in blocks.log file, and it caused some problems. BTW I am reading from a nodeos which is sync data from network.

**Comment by taokayan** [comment]
I don't think it necessary to use multi-threading to read block_log as the bottle neck is on the harddisk/SSD. Making the block_log into memory mapped file is also not a feasible idea because the block_log can grow into couple terabytes easily.

**Comment by necokeine** [comment]
Loading the block.log file with Mmap wouldn't cost memory as the total size of this file. In my opinion, it may be reproduced during multiple get_block API call, and it may pollute the data and need additional hard replay.

**Comment by taokayan** [comment]
You can use multi-threading to read block_log as long as you add a mutex to block_log to synchronize all read/write operations, as the original design of block_log is single threaded.

**Comment by necokeine** [comment]
I think I got it, it was my fault to use it in with multi-threading situation, please close this issue freely.
