### ISSUE TITLE
keosd setting path --wallet-dir is invalid

### ISSUE THREAD

**Issue by matrixpool** [EOSIO/eos#6491]
version: v1.5.0
keosd execute script:
keosd --data-dir /eos/wallet --config-dir /eos/wallet

I use cleos to create a wallet，but found some question.
1、use cleos wallet create --to-console create default.wallet, but default.wallet is in ~/eosio-wallet
2、cleos -u http://127.0.0.1:8888/ wallet create --to-console, Why the communication channel is unix socket, but not http?
3、curl --request POST \
  --url http://127.0.0.1:8888/v1/wallet/create \
  --header 'content-type: application/x-www-form-urlencoded; charset=UTF-8'
 response error:
{"code":500,"message":"Internal Service Error","error":{"code":7,"name":"bad_cast_exception","what":"Bad Cast","details":[]}}

keosd config.ini
```
#The filename (relative to data-dir) to create a unix socket for HTTP RPC; set blank to disable. (eosio::http_plugin)
unix-socket-path = keosd.sock

#The local IP and port to listen for incoming http connections; leave blank to disable. (eosio::http_plugin)
http-server-address = 127.0.0.1:8888 

#The local IP and port to listen for incoming https connections; leave blank to disable. (eosio::http_plugin)
# https-server-address = 

#Filename with the certificate chain to present on https connections. PEM format. Required for https. (eosio::http_plugin)
# https-certificate-chain-file = 

#Filename with https private key in PEM format. Required for https (eosio::http_plugin)
# https-private-key-file = 

#Specify the Access-Control-Allow-Origin to be returned on each request. (eosio::http_plugin)
# access-control-allow-origin = 

#Specify the Access-Control-Allow-Headers to be returned on each request. (eosio::http_plugin)
# access-control-allow-headers = 

#Specify the Access-Control-Max-Age to be returned on each request. (eosio::http_plugin)
# access-control-max-age = 

#Specify if Access-Control-Allow-Credentials: true should be returned on each request. (eosio::http_plugin)
access-control-allow-credentials = false

#The maximum body size in bytes allowed for incoming RPC requests (eosio::http_plugin)
max-body-size = 1048576

#Append the error log to HTTP responses (eosio::http_plugin)
verbose-http-errors = false

#If set to false, then any incoming "Host" header is considered valid (eosio::http_plugin)
http-validate-host = 1

#Additionaly acceptable values for the "Host" header of incoming HTTP requests, can be specified multiple times.  Includes http/s_server_address by default. (eosio::http_plugin)
# http-alias = 

#The path of the wallet files (absolute path or relative to application data dir) (eosio::wallet_plugin)
plugin = eosio::wallet_plugin
wallet-dir = "/eos/wallet"

#Timeout for unlocked wallet in seconds (default 900 (15 minutes)). Wallets will automatically lock after specified number of seconds of inactivity. Activity is defined as any wallet command e.g. list-wallets. (eosio::wallet_plugin)
unlock-timeout = 900

#Override default URL of http://localhost:12345 for connecting to yubihsm-connector (eosio::wallet_plugin)
# yubihsm-url = 

#Enables YubiHSM support using given Authkey (eosio::wallet_plugin)
# yubihsm-authkey = 

#Plugin(s) to enable, may be specified multiple times
plugin = eosio::http_plugin 
```

**Comment by jgiszczak** [comment]
The `--config-dir` and `--wallet-dir` arguments accept what you write.  You wrote `/eos/wallet`, which is an absolute path.  It expects an `eos` directory at the root of your filesystem.

1. The `--to-console` argument means "echo the wallet password to the console".  It does not mean create a wallet to console.  Creating a wallet always creates a file.
2. The tutorials still use http over TCP sockets to make it easy for Docker users.  While it is possible to use a Unix socket into Docker, it requires setup which is not included in the tutorials.
3. The `wallet/create` API requires an argument.  Run cleos with `--print-request` to see the required argument format.

If you still have problems and wish to discuss further, please post in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
