### ISSUE TITLE
ubuntu18.04 build failed on v1.5.1

### ISSUE THREAD

**Issue by gyl19930522** [EOSIO/eos#6492]
While I am building eos under ubuntu18.04, it failed at linking CXX executable nodeos, as following:

[100%] Linking CXX executable nodeos
/usr/local/lib/libmongoc-static-1.0.a(mongoc-crypto-openssl.c.o)：在函数‘EVP_MD_CTX_new’中：
mongoc-crypto-openssl.c:(.text+0x50): `EVP_MD_CTX_new'被多次定义
/usr/lib/x86_64-linux-gnu/libcrypto.a(digest.o):(.text+0xb0)：第一次在此定义
/usr/local/lib/libmongoc-static-1.0.a(mongoc-crypto-openssl.c.o)：在函数‘EVP_MD_CTX_free’中：
mongoc-crypto-openssl.c:(.text+0x60): `EVP_MD_CTX_free'被多次定义
/usr/lib/x86_64-linux-gnu/libcrypto.a(digest.o):(.text+0xd0)：第一次在此定义
/usr/local/lib/libmongoc-static-1.0.a(mongoc-openssl.c.o)：在函数‘_mongoc_openssl_init’中：
mongoc-openssl.c:(.text+0x19b)：对‘SSL_library_init’未定义的引用
mongoc-openssl.c:(.text+0x1a0)：对‘SSL_load_error_strings’未定义的引用
mongoc-openssl.c:(.text+0x1aa)：对‘OPENSSL_add_all_algorithms_noconf’未定义的引用
mongoc-openssl.c:(.text+0x1af)：对‘CRYPTO_num_locks’未定义的引用
mongoc-openssl.c:(.text+0x1f1)：对‘CRYPTO_num_locks’未定义的引用
mongoc-openssl.c:(.text+0x1fa)：对‘CRYPTO_get_locking_callback’未定义的引用
mongoc-openssl.c:(.text+0x204)：对‘SSLv23_method’未定义的引用
mongoc-openssl.c:(.text+0x22c)：对‘CRYPTO_set_locking_callback’未定义的引用
mongoc-openssl.c:(.text+0x236)：对‘CRYPTO_set_id_callback’未定义的引用
/usr/local/lib/libmongoc-static-1.0.a(mongoc-openssl.c.o)：在函数‘_mongoc_openssl_cleanup’中：
mongoc-openssl.c:(.text+0x267)：对‘CRYPTO_get_locking_callback’未定义的引用
mongoc-openssl.c:(.text+0x274)：对‘CRYPTO_get_id_callback’未定义的引用
mongoc-openssl.c:(.text+0x2a7)：对‘CRYPTO_num_locks’未定义的引用
mongoc-openssl.c:(.text+0x2c4)：对‘CRYPTO_set_locking_callback’未定义的引用
mongoc-openssl.c:(.text+0x2cd)：对‘CRYPTO_set_id_callback’未定义的引用
/usr/local/lib/libmongoc-static-1.0.a(mongoc-openssl.c.o)：在函数‘_mongoc_openssl_check_cert’中：
mongoc-openssl.c:(.text+0x3b6)：对‘sk_num’未定义的引用
mongoc-openssl.c:(.text+0x3f3)：对‘sk_value’未定义的引用
/usr/local/lib/libmongoc-static-1.0.a(mongoc-openssl.c.o)：在函数‘_mongoc_openssl_ctx_new’中：
mongoc-openssl.c:(.text+0x6c3)：对‘SSLv23_method’未定义的引用
/usr/local/lib/libmongoc-static-1.0.a(mongoc-crypto-openssl.c.o)：在函数‘EVP_MD_CTX_free’中：
mongoc-crypto-openssl.c:(.text+0x65)：对‘EVP_MD_CTX_cleanup’未定义的引用
/usr/local/lib/libmongoc-static-1.0.a(mongoc-crypto-openssl.c.o)：在函数‘mongoc_crypto_openssl_sha1’中：
mongoc-crypto-openssl.c:(.text+0xbd)：对‘EVP_MD_CTX_cleanup’未定义的引用
clang: error: linker command failed with exit code 1 (use -v to see invocation)
programs/nodeos/CMakeFiles/nodeos.dir/build.make:206: recipe for target 'programs/nodeos/nodeos' failed
make[2]: *** [programs/nodeos/nodeos] Error 1
CMakeFiles/Makefile2:6167: recipe for target 'programs/nodeos/CMakeFiles/nodeos.dir/all' failed
make[1]: *** [programs/nodeos/CMakeFiles/nodeos.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[100%] Linking CXX executable cleos
[100%] Built target cleos
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

Could anyone know how to resolve it, thanks!

**Comment by jgiszczak** [comment]
It looks like you have an older build of libmongoc.  If you remove `/usr/local/lib/libmongoc*`, the build script will rebuild it for you.
