### ISSUE TITLE
some questions about cdt inline action

### ISSUE THREAD

**Issue by anlgit** [EOSIO/eos#6493]
newest version of eos,inline action changed alot. But system contract example eosio.token,not  export the interface like this:  "using transfer_action = action_wrapper<"transfer"_n, &monster::transfer>" ,I hope u can change this quickly!

**Comment by jgiszczak** [comment]
See the [eosio.contract](https://github.com/EOSIO/eosio.contracts) repository for the current version of the eosio.token contract.  The version in this repository is out of date, used only by automated tests.

**Comment by anlgit** [comment]
I got it. But I hope u can add one line code like "using transfer_action = action_wrapper<"transfer"_n, &token ::transfer>" in function "transfer" . when contract need use inline action to transfer some eos to others.I can use it like 
"token::transfer_action aaa(inline_code, {_self, "active"_n});
aaa.send(from,to,money,data);" .
Or i only to use it like " 
action(
        {_self, N(active)},
        N(eosio.token), N(transfer),
        std::make_tuple(_self, from, aquantity, std::string("send winner chip SLOT"))
    ).send(); "
that's so sad!

**Comment by anlgit** [comment]
OR we can use SEND_INLINE_ACTION?
