### ISSUE TITLE
STAT-144 ⁃ eosd sync failure in some cases

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#651]
The problem is manifest when a multinode testnet is started manually. This induces a delay wherein one instance of eosd will create blocks the best it can, but  not advancing the last irreversible block. Then sometime later a new eosd is started, which should add more producers and should also synchronize with the existing producers, but this sometimes doesn't happen.

The actual problem is a corner case where the last irreversible block number is 0. In this case, the chain controller throws an exception when you try to get the block id for block number 0. In the p2p code, this exception is caught, but it caused another block id request to be skipped, leading to the observed failure. 

A second problem is that the handshake handling code was skipping the update notice if the peer's reported head block had an id value of all 0.

**Comment by heifner** [comment]
Resolved by #652.

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

How do we test this tomorrow? Is there an ACT?
