### ISSUE TITLE
error: no matching member function for call to 'erase'

### ISSUE THREAD

**Issue by yinchonging** [EOSIO/eos#6512]
auto by_secondary_index = _table.get_index<"bysecondaryid"_n>();
    auto it_l = by_secondary_index.lower_bound(secondaryid);
    auto it_u = by_secondary_index.upper_bound(secondaryid);
    
    while(it_l != it_u)
    {
        it_l = _table.erase( it_l );  
        //it_l++;
    }
Errors in compile "error: no matching member function for call to 'erase'"

    auto by_secondary_index = _table.get_index<"bysecondaryid"_n>();
    auto it_l = by_secondary_index.lower_bound(secondaryid);
    auto it_u = by_secondary_index.upper_bound(secondaryid);
    
    while(it_l != it_u)
    {
        _table.erase( *it_l );   
        it_l++;
    }

Error in execution "The table operation is not allowed "

How to fix? thinks!

**Comment by kaidiren** [comment]
```
while (true) {
    auto idx = bets.get_index<N(bygameid)>();
    auto bet_itr = idx.find(game.id);
    if (bet_itr == idx.end()) {
        break;
    }
    idx.erase(bet_itr);
}
```

do it like this

**Comment by yinchonging** [comment]
@kaidiren Thanks for your reply.  what if lower_bound is used？
Is this a bug?

**Comment by jgiszczak** [comment]
Rather than trying to increment the iterator yourself, write `it_l = _table.erase(it_l);`.  The erase method that accepts an iterator returns the incremented iterator, ensuring your own iterator remains valid.

**Comment by yinchonging** [comment]
> Rather than trying to increment the iterator yourself, write `it_l = _table.erase(it_l);`. The erase method that accepts an iterator returns the incremented iterator, ensuring your own iterator remains valid.

"The table operation is not allowed ", why?

**Comment by yinchonging** [comment]
> ```
> while (true) {
>     auto idx = bets.get_index<N(bygameid)>();
>     auto bet_itr = idx.find(game.id);
>     if (bet_itr == idx.end()) {
>         break;
>     }
>     idx.erase(bet_itr);
> }
> ```
> do it like this

EOSIO.CDT Version : 1.4.1  "error: no matching member function for call to 'erase'"
