### ISSUE TITLE
cleos create account 0 Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations

### ISSUE THREAD

**Issue by eladelrom** [EOSIO/eos#6513]
I cloned origin/release/1.5.1, created the default wallet, created two keypairs and imported the private keys to the default wallet.  Additionally, the wallet is unlocked (as you can see from the screenshot) and I am running "nodeos" in a separate Terminal using this command;

> nodeos -e -p eosio --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin

Yet I am still getting the 3090003 error:
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.

![image](https://user-images.githubusercontent.com/139483/50281650-de9d6180-0458-11e9-9e97-74cd84ffc475.png)

I see there was a ticket open https://github.com/EOSIO/eos/issues/4154, but I don't see a resolution and it was closed on Oct 26 without a being resolved. This issue is needs to be resolved any collaborators aware of where this stand?

**Comment by kaidiren** [comment]
if you don't know how to run it correctly, you can use this https://github.com/kaidiren/local-eos-testnet

**Comment by jgiszczak** [comment]
Everything you needed was in #4154, which was resolved.  Import the key for the eosio account.  You do not need the keys of a newly created account to be imported at all until you are using the new account.  The creator account is the one that must have a key in the wallet, so it can sign the create transaction.
