### ISSUE TITLE
1.6.0-rc1 can not start up

### ISSUE THREAD

**Issue by dawnFromDark** [EOSIO/eos#6515]
root@ubuntu:/home/time/code/eos# nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /home/time/block --config-dir /home/time/block/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false 

error 2018-12-21T02:31:11.666 thread-0  main.cpp:135                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option 'max-implicit-request'

root@ubuntu:/home/time/code/eos# git branch
* (HEAD detached at v1.6.0-rc1)
  master
  v1.5.1
root@ubuntu:/home/time/code/eos# git checkout v1.5.1
warning: refname 'v1.5.1' is ambiguous.

i checkout the 1.6.0-rc1 ,built successfully, however ,it can not star up again! the os
 Linux ubuntu 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
beofre i upgrade to1.6.0-rc1 , my branch is 1.5.1, so guys, please fix it ,ok?

**Comment by dawnFromDark** [comment]
and i rollback to 1.5.1，all the function is good, it proves that 1.5.1 upgraded to 1.6.0-rc1 may got fatal error,right?

**Comment by heifner** [comment]
Remove `max-implicit-request` from your config.ini.

**Comment by dawnFromDark** [comment]
> ax-implicit-request

ok, i removed it ,and re-compile it, and i will show the result later，thank you for your help.

**Comment by dawnFromDark** [comment]
> Remove `max-implicit-request` from your config.ini.

ok, my issue was solved, thanks again.
