### ISSUE TITLE
 Issue with get_balance in eosio.token

### ISSUE THREAD

**Issue by pserg1** [EOSIO/eos#6517]
https://github.com/EOSIO/eos/blob/master/contracts/eosio.token/eosio.token.hpp

If user doesn't have any tokens on his balance, the get_balance method drops with weird exception.

Please either:

1. Let us define our own exception

or

2. Return 0

**Comment by conr2d** [comment]
`eosio::token::get_balance()` is not the only way to get balance. You can write your own accessor to token balance.

**Comment by heifner** [comment]
Note `eosio.token` has moved to https://github.com/EOSIO/eosio.contracts all issues related to it should be discussed there. The contracts in this repo are only for testing.
