### ISSUE TITLE
history_plugin has a serious bug

### ISSUE THREAD

**Issue by singpenguin** [EOSIO/eos#6519]
Hi, 
I'm use version 1.5.2，but i found a serious problem.
eg: block 189，has one transaction ff7b77246a26da7c807facdc92bcebe257ff2e0b2b4ef0100cf4e109ecdf7344 .
if i use: cleos get transaction ff7b77246a26da7c807facdc92bcebe257ff2e0b2b4ef0100cf4e109ecdf7344

it return too large data. The "traces" array contains a lot of redundant data.
eg: [{"receiver":1,"inline_traces": [{"receiver": 2, "inline_traces": [{"receiver": 3}]}]}, {"receiver": 2, "inline_traces": [{"receiver": 3}]}, {"receiver": 3}]

The data of "inline_traces" will be copied in the outermost layer. thanks.

**Comment by taokayan** [comment]
Can you provide more details? for example: how to reproduce? Also can you show us a complete transaction retrieved from cleos?

**Comment by singpenguin** [comment]
cleos get transaction ff7b77246a26da7c807facdc92bcebe257ff2e0b2b4ef0100cf4e109ecdf7344

The file is too big, I put it in the attachment. The second layer of inline_traces will be copied to the first layer.

[result.txt](https://github.com/EOSIO/eos/files/2706490/result.txt)

This is my nodeos info:
{
  "server_version": "d3424096",
  "chain_id": "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906",
  "head_block_num": 3659100,
  "last_irreversible_block_num": 3658767,
  "last_irreversible_block_id": "0037d40f650914261d1a4ae36324410bbd02d2bea8d3c9d50a222a0eb737b7e8",
  "head_block_id": "0037d55c3e9374e26464dbd3858d4979cb5c287aca7a3ff1c093cac27ff903e5",
  "head_block_time": "2018-07-01T20:35:47.000",
  "head_block_producer": "eos42freedom",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 200000,
  "block_net_limit": 1048576,
  "server_version_string": "v1.5.2"
}

**Comment by taokayan** [comment]
See https://bloks.io/transaction/ff7b77246a26da7c807facdc92bcebe257ff2e0b2b4ef0100cf4e109ecdf7344

This is account creation of "eosio" which indirectly triggers multiple actions (buy ram, ram fee, transfers, delegatebw). As a result, multiple action traces & inline action traces are created accordingly. Therefore this is not a bug.

**Comment by singpenguin** [comment]
https://bloks.io/transaction/ff7b77246a26da7c807facdc92bcebe257ff2e0b2b4ef0100cf4e109ecdf7344

This looks like the right result. The file I uploaded contains the wrong result. I will try another version.
Thanks.
