### ISSUE TITLE
Using cleos to read table with i128 bit secondary index

### ISSUE THREAD

**Issue by okayplanet** [EOSIO/eos#6522]
(I am using nodeos v1.4.3)

I have a table with a secondary index of type uint128_t.  

My understanding is that I should be able to use the following to get an entry:
`cleos get table mycontract mycontract mytable --key-type i128 --index 2 -L 269426230777718110912747792682672604624`

But I get this error when trying to run the above command:
`error 2018-12-24T04:59:48.999 thread-0  main.cpp:3151                 main                 ] Failed with error: Assert Exception (10)
s.size() == 2 + 2 * sizeof(temp) && s.find("0x") == 0: Failure in converting hex data into a uint128_t
Could not convert lower_bound string '269426230777718110912747792682672604624' to key type.`

Despite 269426230777718110912747792682672604624 being a valid uint128_t key, there is still some issue with the conversion.

**Comment by maoueh** [comment]
Your `uint128_t` input must be in hexadecimal format using little endian format. Something like that:

```
eosc get table eosforumrcpp eosforumrcpp vote --index 2 --key-type i128 --lower-bound 0x0000000000000000b0b13278fd8d73fa --upper-bound 0xffffffffffffffffb0b13278fd8d73fa
```

You'll need to convert your big number to hexadecimal.

**Comment by okayplanet** [comment]
Perfect! Thanks.
