### ISSUE TITLE
Please advise how can I create Multi-Host Private Blockchain Network. 

### ISSUE THREAD

**Issue by chanwitkepha** [EOSIO/eos#6524]
Because I would like to deploy Private Blockchain like Diagram below. But Document have only method for setup Multi-Node on Single Host
https://developers.eos.io/eosio-nodeos/docs/local-multi-node-testnet

Moreover I tried to understand this Document but I'm not sure that's the right solution for build node on multiple servers or not. When I look at method for create genesis.json files. It seem not clear about EOS_PUB_DEV_KEY that Should I use Public Key from another server or not? (Example : use Public Key of Server 2 in genesis.json file on Server 1).

https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence

Please advise solution or guideline for me, Thank you very much.

![1545647432845](https://user-images.githubusercontent.com/45688421/50397346-5bef0c00-07a2-11e9-84fc-6624ba55456b.jpg)

**Comment by yashbhavsar007** [comment]
This is not an issue related to code you should have to ask this type of questions over https://eosio.stackexchange.com and close this issue.
--

**Comment by jgiszczak** [comment]
The documentation at https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence is more explicit about how to construct a network of multiple producer nodes.  To generalize the instructions to multiple VMs, simply substitute appropriate IPs and ports for the `p2p-peer-address` parameters of each remote node as required for your network.  The genesis.json file must be identical on all nodes that will be synchronized.

For an automated deployment tool, use `eosio-launcher`.  From your `build` directory, run `programs/eosio-launcher/eosio-launcher --help` for documentation.  Use `--launch none` to generate config files without starting a network.  Experiment with various values of `--nodes` and `--pnodes` and `--shape` to see how config files change depending on the numbers of producing and non-producing nodes and the generated topology.

If you still have questions and wish to discuss further, please post in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by chanwitkepha** [comment]
Dear jgiszczak. Thank you very much for your advise about eosio-launcher and community in stackexchange.
