### ISSUE TITLE
how to pull contract data very very quickly？？

### ISSUE THREAD

**Issue by boy-good** [EOSIO/eos#6527]
how to pull contract data quickly。like eosbet.io

**Comment by jgiszczak** [comment]
I am not familiar with the details of how eosbet.io functions.

Generally speaking, to retrieve contract data as quickly as possible, you need to run your own node synced with the net you are interested in and use one of the external database plugins.  You may also wish to use a custom plugin for data access.

If you still have questions and wish to discuss further, please post in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
