### ISSUE TITLE
bad_cast_exception on v1/wallet/create_key

### ISSUE THREAD

**Issue by ashishchandr70** [EOSIO/eos#6532]
nodeos version: 1.5.2
Ubuntu: 16.04 running as WSL
keosd running on port 8900

$ **curl --request POST   --url http://127.0.0.1:8900/v1/wallet/create_key --header 'content-type: application/x-www-form-urlencoded; charset=UTF-8'**
error 2018-12-27T18:56:56.883 thread-0  http_plugin.cpp:580           handle_exception     ] FC Exception encountered while processing wallet.create_key{"code":500,"message":"Internal Service Error","error":{"code":7,"name":"bad_cast_exception","what":"Bad Cast","details":[]}}
debug 2018-12-27T18:56:56.885 thread-0  http_plugin.cpp:581           handle_exception     ] Exception Details: 7 bad_cast_exception: Bad Cast
Invalid cast from object_type to Array
    {"type":"object_type"}
    thread-0  variant.cpp:535 get_array

The documentation at https://developers.eos.io/keosd/v1.3.0/reference#create_key does not mention a parm.

Also, does v1/wallet/create_key work to create a key in a specific wallet, or does it work like 'cleos create key' to just generate a key pair? If it creates a key in a specific wallet, that means it should need the wallet name as a parm. Tried that as well (after unlocking the wallet):

$  **curl --request POST   --url http://127.0.0.1:8900/v1/wallet/create_key --header 'content-type: application/x-www-form-urlencoded; charset=UTF-8' --data '["default"]'**
error 2018-12-27T19:04:22.816 thread-0  http_plugin.cpp:587           handle_exception     ] STD Exception encountered while processing wallet.create_key{"code":500,"message":"Internal Service Error","error":{"code":0,"name":"exception","what":"unspecified","details":[]}}
debug 2018-12-27T19:04:22.818 thread-0  http_plugin.cpp:588           handle_exception     ] Exception Details: vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)

**Comment by jgiszczak** [comment]
The web API reference has unfortunately never been completely correct, since it omits all parameters for all APIs that require them.  `/vi/wallet/create_key` does require two arguments, which are the wallet name and either `K1` or `R1` (wrapped in appropriate JSON) to specify the key type to create.

Try:
```bash
curl --request POST --url http://127.0.0.1:8900/v1/wallet/create_key --data '["default", "K1"]'
```

**Comment by ashishchandr70** [comment]
It worked. Thank you. Someone should update the doc as well.
