### ISSUE TITLE
Build Validation test "Start 35: distributed-transactions-test" hangs on WSL

### ISSUE THREAD

**Issue by realuser** [EOSIO/eos#6537]
I'm using Ubuntu 18.04.1 LTS on Windows 10 Pro 64-bit via the WSL (Windows Subsystem for Linux).   Using the [EOSIO autobuild script](https://developers.eos.io/eosio-nodeos/docs/autobuild-script) it built without issue.

`git clone https://github.com/EOSIO/eos --recursive`
`cd eos`
`./eosio_build.sh`

I have not yet run the below command to install it, instead waiting to validate the build first (not sure if that matters)
`sudo ./eosio_install.sh`

Running the [build validation ](https://developers.eos.io/eosio-nodeos/docs/build-validation), the first 34 tests all ran and passed, however the 35th test appears to hang indefinitely (I left it running overnight)

`Start 35: distributed-transactions-test`

After cancelling that, I have ran the test separately via
`ctest --output-on-failure -R distributed-transactions-test`

But the test doesn't seem to fail but rather just hang.

Any idea why this is happening or how I can further troubleshoot it?

**Comment by taokayan** [comment]
Can you run the same test with ```--debug``` to see more information?

**Comment by realuser** [comment]
I ran it again individually and it worked. 

```
$ ctest --output-on-failure -R 'distributed-transactions-test'

Test project /home/username/eos/build
    Start 35: distributed-transactions-test
1/1 Test #35: distributed-transactions-test ....   Passed  239.85 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
nonparallelizable_tests    = 239.85 sec*proc (1 test)

Total Test time (real) = 239.92 sec

```
There three things I did in the interim that possibly could have had an impact:
1.  It's possible I didn't correctly set `EOSIO_HOME`.  I may have just copied the following line from [build validation](https://developers.eos.io/eosio-nodeos/docs/build-validation) rather than setting it to my actual path:
`export EOSIO_HOME=/repo/eos/build/`
However I don't recall what I did and I don't have the command history for it.  What I vaguely remember doing is maybe copying the suggested export statement from the end of the autobuild script.

2. I did decide to run `sudo ./eosio_install.sh` in case that would have any impact on the issue. From the instructions it's not clear to me if this is necessary before testing or not.

3. rebooted.

There are some other failing/hanging tests now (e.g. 48 - nodeos_voting_bnet_lr_test (Failed)).  I could close this issue and open new ones as necessary or continue in this thread.

**Comment by realuser** [comment]
Unless there is some cumulative effect from running the tests in sequence (via `make test`) rather than running them individually (via `ctest`)

**Comment by jgiszczak** [comment]
There is not supposed to be any cumulative effect of running the tests in sequence.  All of the tests are intended to be independent.  Any side effects should be found and eliminated.

Some of the tests are indeed still fragile.  This is usually timing related, rather than environmentally related.  We have made efforts to eliminate timing problems as well, but we know we haven't achieved complete success.  If you have a system with repeatedly bad timings, the failure logs would be helpful.  Please run with the `--output-on-failure` argument to ctest.

**Comment by jgiszczak** [comment]
Personally identifiable information in the test output is limited to the pathnames commands are run from, which may include your home directory which may match your username on the system.

The duplicate key errors are expected.  The bad file descriptors are not.  It looks like Microsoft's attempt to emulate the Berkeley TCP stack continues to be a miserable failure.

Windows is not supported.  You may be able to use `cleos`, but it's at your own risk up to and including possible loss of keys.  Running nodeos is not advised.
