### ISSUE TITLE
How to paging a multi-condition query?

### ISSUE THREAD

**Issue by yinchonging** [EOSIO/eos#6540]
```
{
  "rows": [{
      "id": 0,
      "content": "D/v3uwPVXWQ5yRyM5hYnKw==",
      "secondary_id": 0
    },{
      "id": 1,
      "content": "YjVF4FcpWyJlkfSEVYGEUA==",
      "secondary_id": 0
    },{
      "id": 3,
      "content": "I7YVWM2W/31s4erxzOZP/A==",
      "secondary_id": 1
    },{
      "id": 4,
      "content": "if07NTGLIsgaVC/fcEtUew==",
      "secondary_id": 1
    },{
      "id": 10000,
      "content": "AgOMAyRkx+ninQ+8TxeXOA==",
      "secondary_id": 0
    },{
      "id": 10001,
      "content": "AgOMAyRkx+ninQ+8TxeXOA==",
      "secondary_id": 1
    }
    //......
  ]
}
```

I want to use secondary index  to query data with ID 10001.
How to implement with the cleos command?

```
./cleos get table account scope table \
--index 2 \               //Index number, 2 == secondary_id
--key-type i64 \
-L 1 \                    //secondary_id == 1
-U 1 \                    //secondary_id == 1
--limit 1 \
--???                     //id == 10001
```
Thanks for any reply.

**Comment by taokayan** [comment]
looks like the "id" field is the primary index. You can simply do this by querying the primary index.

**Comment by yinchonging** [comment]
@taokayan  I mean, I want to query secondary_id == 1 and id == 10001 of this data, how to query with the cleos command?

**Comment by taokayan** [comment]
Multiple key indexing is not yet supported in eosio. However, you can query by one key first then do a manual filtering.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
