### ISSUE TITLE
Replacing a deferred transaction is temporarily disabled.

### ISSUE THREAD

**Issue by boy-good** [EOSIO/eos#6541]
![image](https://user-images.githubusercontent.com/39320533/50590917-df59dd00-0ec7-11e9-8bfc-2653c4c9001d.png)

how to deal with this problem?not allow to replace?

**Comment by wanderingbort** [comment]
The first parameter to `send_deferred` is a contract controlled ID that represents the transaction at an internal level: https://github.com/EOSIO/eos/blob/d34240966309739914c4c2ae85c4c51bde5e8c12/contracts/eosiolib/transaction.h#L56

if that ID is already in use and you try to replace the deferred transaction you get this issue.

To prevent it, call `cancel_deferred` using that ID before calling `send_deferred`.  This is safe to do even if no transaction with that ID is currently scheduled:

https://github.com/EOSIO/eos/blob/d34240966309739914c4c2ae85c4c51bde5e8c12/contracts/eosiolib/transaction.h#L77
