### ISSUE TITLE
Payment notification

### ISSUE THREAD

**Issue by rockandruby** [EOSIO/eos#6556]
How do u implement in EOS payment notification(like walletnotify for bitcoin)? I mean I need a mechanism that will inform my system that a payment was recieved by my wallet/account whatever and then proceed with some actions.

**Comment by jgiszczak** [comment]
State history plugin will be the supported method for achieving what you want.  It is currently in Alpha release, so it's available to start building software against, but the documentation is incomplete and the API is not guaranteed stable.  It has its own TCP socket which defaults to port 8080.  Use the `state-history-endpoint` setting to change it.  See the ABI in the source for the message format.  You'll need to process blocks yourself.  Send a `get_blocks_request_v0` with an `end_block_num` in the future.  This acts as a subscription.

If you would prefer a more granular notification, you'll need to implement a custom plugin, possibly extending state history.

**Comment by rockandruby** [comment]
@jgiszczak I use junggle testnet and I found some servers that possibly work with that plugin. So what's the endpoint of get_blocks_request_v0? I mean /v1/history/get_blocks_request_v0 doesn't work, so what's the correct one?

**Comment by jgiszczak** [comment]
State history plugin does not provide an HTTP API.  It speaks a packed binary protocol, described by the ABI file in the source.  There may be an API plugin as well eventually, but there currently is not.

**Comment by rockandruby** [comment]
@jgiszczak and what about rpc get_actions? For sample, junggle tesnet has history node and I fetch my hisotry via get_actions when connected to that node

**Comment by jgiszczak** [comment]
So far there is no comparable interface to get_actions.
