### ISSUE TITLE
how to catch defer onerror

### ISSUE THREAD

**Issue by boy-good** [EOSIO/eos#6562]
![image](https://user-images.githubusercontent.com/39320533/50735191-ada58680-11e5-11e9-8394-3cb07d2f2709.png)
defer action maybe onerror how to catch in contract?

**Comment by spartucus** [comment]
same here, maybe a `missing authority of ${account}` error?

**Comment by boy-good** [comment]
@spartucus i found the error maked by contract eosio_assert. the eosx.io can see the error. I want to know how to catch it in contract , like in "apply" function?

**Comment by hama** [comment]
you should use onerror.
https://github.com/EOSIO/eos/blob/ea08cfd3d1a82b634a9e84f971d99708af516c0d/unittests/contracts/deferred_test/deferred_test.cpp#L47

**Comment by taokayan** [comment]
You need to implement the "onerror" action

**Comment by boy-good** [comment]
@taokayan @hama only support to print error? Can operate table in  "apply_onerror" function like "deferred_test.cpp"?

**Comment by vtsurka** [comment]
Also interesting how get which assert in deferred transaction trigger onerror situation.

**Comment by jgiszczak** [comment]
@boy-good There are no restrictions on what can be done in `apply_onerror()`.  See 
https://github.com/EOSIO/eos/blob/ea08cfd3d1a82b634a9e84f971d99708af516c0d/contracts/proxy/proxy.cpp#L71
for another example.  Note that injudicious code could result in permanent loops, so care must be taken.

@vtsurka The above reference shows an example of retrieving the sent transaction in `apply_onerror()`.
