### ISSUE TITLE
NOON-145 ⁃ eosd should detect network desync/sync and log status changes

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#657]
Because block time and the per round producer schedule is always known, eosd can explicitly detect network desynchronization and resynchronization.  It should do so and log appropriately.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

Moved this back todo, Jonathan is going to work on STAT-167 now as it is a higher priority.

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

My original purpose for creating this feature was to allow explicit monitoring of node synchronization from logs.  Today on testnet1 I built a monitor based on the unlinkable_block_exception, which addresses the majority of the feature.

It may not be necessary to change code for this.  I will evaluate other use cases.

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

Did not find any other use case.

**Comment by heifner** [comment]
Closed in JIRA.
