### ISSUE TITLE
Can get zero timestamp that today in contract?

### ISSUE THREAD

**Issue by boy-good** [EOSIO/eos#6584]
how to get zero timestamp?

**Comment by jgiszczak** [comment]
I'm not sure what you're asking.  A timestamp can have a value of zero, which is the beginning of its epoch.

**Comment by taokayan** [comment]
Is your question translated from Chinese? Please can you provide your question in your native language?

**Comment by boy-good** [comment]
在合约中可以获取到当天指定时间的时间戳吗 比如获取当天凌晨零点的时间戳

**Comment by boy-good** [comment]
@taokayan @jgiszczak

**Comment by taokayan** [comment]
If you want to get the beginning of the day of the current time, you can use ```time_point_sec(now() / 86400 * 86400)```

**Comment by boy-good** [comment]
> If you want to get the beginning of the day of the current time, you can use `time_point_sec(now() / 86400 * 86400)`

![image](https://user-images.githubusercontent.com/39320533/51105924-562a9a80-1825-11e9-8124-61cd3b1bd435.png)

return data not an uint64_t type，how to translate to uint64_t right? Thanks very much.

**Comment by jgiszczak** [comment]
Instead of using `now()`, you may use `current_time() / 1000000` which is a `uint64_t`, while performing the same operation that `now()` does.  Alternatively you may cast `now()` to `uint64_t`.
