### ISSUE TITLE
Nodeos command is throwing an exception.

### ISSUE THREAD

**Issue by Shujat696** [EOSIO/eos#6595]
After successfully building eos, I'm trying to launch a single node testnet. I used this command:
nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --contracts-console . 
But, I'm getting this error message: error 2019-01-14T17:56:22.175 thread-0  main.cpp:135                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option 'signature-cpu-billable-pct'
I'm following tutorials from this site: [https://infinitexlabs.com/first-steps-in-eos-blockchain-development/](url)

**Comment by jgiszczak** [comment]
What version of nodeos are you running?  Find out with `nodeos --version`.  It needs to be at least v1.6.0-rc1 to accept that option.  If an older version is being found in your path, you'll need to remove it.  You should also remove older versions of keosd, eosio-launcher, and cleos if they're present in `/usr/local/bin`.  You may use `eosio_install.sh` to install, which will add symbolic links, run the cleanup script, and run `make install` for you.  If you'd prefer to just clean up, you may run `scripts/clean_old_install.sh` to automatically remove old versions.

The newly installed version should be in `/usr/local/eosio`.
