### ISSUE TITLE
cleos push tranaction failed, maybe expired transaction would forbidden new transaction ?

### ISSUE THREAD

**Issue by guaiguaihw** [EOSIO/eos#6603]
In my private chain, one transaction is expired, tx_id: `374708fff7719dd5979ec875d56cd2286f6d3cf7ec317a3b25632aab28ec37bb`
when I push new transaction, there always be error: 
![image](https://user-images.githubusercontent.com/11972366/51157672-f206e580-18bb-11e9-9458-882b95dc2baf.png)
But text2 contains new transaction, which tx_id: `d796e1e83a44fd21784e2ddc8a875afbfa57f61f49dc44744cd5e2f7b697c2d7`
![image](https://user-images.githubusercontent.com/11972366/51157686-0945d300-18bc-11e9-8cd2-2fed61a95b4d.png)
The node's error:  
![image](https://user-images.githubusercontent.com/11972366/51157722-31353680-18bc-11e9-9951-a1dc4bb91a22.png)
I wonder there maybe something wrong with `cleos push tranaction`？

**Comment by jgiszczak** [comment]
You need to regenerate your packed_trx after updating your original transaction.  It contains an expiration time.  If that time is in the past, `push transaction` will always fail.  The expiration time must be in the future.
