### ISSUE TITLE
Feature request: Add way to transfer RAM payer of table

### ISSUE THREAD

**Issue by znebby** [EOSIO/eos#6604]
Currently only rows can change payer, but not tables.

**Comment by taokayan** [comment]
One possible way is to remove all the rows from a table and insert those rows back. Otherwise a hard-fork might be required to have this new feature.

**Comment by znebby** [comment]
But if each user is paying for their own row, you wouldn't be able to keep them as the payers when you add them back.

**Comment by aclark-b1** [comment]
Is this still an issue for you?  If so, please reopen this ticket and provide a bit more context on your use case.
