### ISSUE TITLE
Bug?: cleos get scope table counts do not make sense

### ISSUE THREAD

**Issue by znebby** [EOSIO/eos#6605]
using eosio 1.5: cleos -u https://eos.greymass.com get scope infiniverse1

Among other results includes:

      "code": "infiniverse1",
      "scope": "infiniverse1",
      "table": "land",
      "payer": "gu3dinjtgage",
      "count": 19708
    },{
      "code": "infiniverse1",
      "scope": "infiniverse1",
      "table": "land........1",
      "payer": "gu3dinjtgage",
      "count": 9854
    },{
      "code": "infiniverse1",
      "scope": "infiniverse1",
      "table": "land........2",
      "payer": "gu3dinjtgage",
      "count": 9854

I understand land1 and land2 are the secondary index tables, but why is the count in the main land table double?

When I iterate through the table land using the get table API, there are in fact 9854 rows, not 19708.

**Comment by taokayan** [comment]
From ```apply_context.cpp``` I found that the ```count``` was incremented more than one time if a table has secondary key. This behaviour is confusing user, however if the counter decremented in the same way it was incremented, it will not results in any actual bug/issue. I guess the documentation need to be updated to reflect this actual behaviour.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
