### ISSUE TITLE
Re-deploy token contract

### ISSUE THREAD

**Issue by dchan1288** [EOSIO/eos#6606]
Hi 
I have deploy my eosio.token contract to the main chain, I had create, issue token with that account, however I accidentally used this same account to deploy other contract which results the 
cleos get currecy balance command not working, however I redeploy the eosio.token contract again then the command does work.
The problem is that on eosflare it shown the balance when first deploy, however after the mistake and re-deploy eosflare.io never shown the balance again but as I say cleos get balance does work so why is that ?
Can anybody help

**Comment by jgiszczak** [comment]
You would have to ask the authors of the eosflare.io website.  It is not maintained here.
