### ISSUE TITLE
The mongodb is required for CMake in the eos/plugin/dbplugin/ and eos/tests/, however, it has not been specified in the documentation

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eos#661]
It will lead to failure of CMake it MongoDB is not installed

![](https://user-images.githubusercontent.com/16319106/32650864-44040230-c63a-11e7-95d5-ef73968c99e3.png)
It doesnot been specified EOS Application Stack, the Application Stack specify use IPFS to store
![image](https://user-images.githubusercontent.com/16319106/32650906-7c6b2932-c63a-11e7-8490-eb353b5f2b7b.png)

For example, for the CMakeList.txt under plugin/db_plugin/CMakeList, and tests/CMakeList.
It the installation of MongoDB should be specified in build.sh and documentations.
![image](https://user-images.githubusercontent.com/16319106/32651281-9b2cf520-c63b-11e7-8296-82a3c1d89c9c.png)

**Comment by heifner** [comment]
mongodb is not required. You do get a warning if not setup but eos still builds. Most people will not be interested in setting up the mongodb and can safely ignore the warning.

**Comment by myyan** [comment]
@heifner hi , can you explain detail  what's the function of mongo ?   i my opinion , data should stored on the blockchain ,  if  i missed something ？

**Comment by jgiszczak** [comment]
@myyan MongoDB was provided as a mirror of the in-memory database, making the same data available in a classically queryable form.  The plugin is currently inoperable and stale and is slated to be updated.
