### ISSUE TITLE
[Mainnet][Synchronization] Slow at block 7.000.000

### ISSUE THREAD

**Issue by tranchiendang** [EOSIO/eos#6616]
Hi,
I started to sync with mainnet, at first, sync was very fast, but from block 7.000.000, the sync process is very slow now. I try to add more peers as well as increase disk I/O but can not overcome.
Do you have any suggestion to speed up.

./start.sh --delete-all-blocks --genesis-json genesis.json

**Comment by matthewdarwin** [comment]
Make sure you have a very fast CPU (eg Intel i9-9900K CPU @ 3.60GHz is excellent)
Make sure you have 16 GB RAM.
Make sure you are using SSD hard disk or NVME drive.
Make sure your CPU usage is 100%.  If not, it means your network is too slow.

After all that, it will take around 1 week.

Alternate solutions: 
Use a snapshot if you don't need all the history.
Get a backup from someone.

This question is really better for https://eosio.stackexchange.com/

**Comment by tranchiendang** [comment]
@matthewdarwin Thank for your suggestion. 
Let me upgrade the hardware and see the progress first.
Will back later.
Thank you.

**Comment by tranchiendang** [comment]
Hi @matthewdarwin 
After continuing sync, the sync get stuck at block 7116229. It stayed there for 2 days.
Could you please give me any suggestion?

**Comment by taokayan** [comment]
How about your CPU/RAM/harddisk/network usage at the time of stuck? Can you find out which is the bottleneck?

**Comment by tranchiendang** [comment]
Hi @taokayan ,

![image](https://user-images.githubusercontent.com/3632621/51380792-17f2eb00-1b45-11e9-9410-60c23083268f.png)
![image](https://user-images.githubusercontent.com/3632621/51380818-29d48e00-1b45-11e9-929c-ed7ba0abf45d.png)

everything is fine.

**Comment by matthewdarwin** [comment]
What do the logs say?  Are you connected to any peers?

**Comment by tranchiendang** [comment]
hi @matthewdarwin 
this is some peer nodes that in established:
![image](https://user-images.githubusercontent.com/3632621/51509698-b5436d00-1e2c-11e9-918f-c0a8fa463158.png)

and this is the logs:
![image](https://user-images.githubusercontent.com/3632621/51509737-e02dc100-1e2c-11e9-9dbd-c65bc23822f8.png)

**Comment by matthewdarwin** [comment]
Any errors before that?
Did you try restarting nodeos?

**Comment by tranchiendang** [comment]
Hi,
I dont see any errors before. Did not try restarting. should i need?

**Comment by matthewdarwin** [comment]
Yes, please restart. sometimes nodeos gets stuck for no apparent reason.

**Comment by tranchiendang** [comment]
Hi, 
Ok, let me do it. will back later.
Thank you for your time.

**Comment by jgiszczak** [comment]
Looking at your peer list, you are not successfully establishing a connection to any peer anymore.  You need to remove inaccessible peers from your list and add some new ones.  You may have had a responsive peer and have lost your connection when someone else occupied the last available connection.
