### ISSUE TITLE
cleos set account permission with JSON authority gave me an "Error 3010001: Invalid name" in eosio v1.5.0

### ISSUE THREAD

**Issue by Viterbo** [EOSIO/eos#6617]
I was following [this solution](https://eosio.stackexchange.com/a/1711/2452) I found on stack exchange to communicate two contracts with eachother but one of the commands gave me an error.

**command:**

    $ cleos set account permission sender active '{"threshold": 1,"keys": [{"key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","weight": 1}],"accounts": [{"permission":{"actor":"sender","permission":"eosio.code"},"weight":1}]}' owner -p sender

**error:**

    Error 3010001: Invalid name
    Name should be less than 13 characters and only contains the following symbol .12345abcdefghijklmnopqrstuvwxyz
    Error Details:
    Name not properly normalized (name: 1,keys:, normalized: 1.keys) 

the account *sender* is already created and has the contract code loaded. I also checked the JSON sintax and it's fine. 

**net info:**

```
$ cleos get info
{
  "server_version": "ea08cfd3",
  "chain_id": "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f",
  "head_block_num": 162410,
  "last_irreversible_block_num": 162409,
  "last_irreversible_block_id": "00027a6957b66200ca9b6c2d1a198464e25026597d424cdac7608c8a574f92f4",
  "head_block_id": "00027a6a1e13a76a0ceffa5030d002a4114eaf1d7616a209ecc22def2cc5d137",
  "head_block_time": "2019-01-16T04:20:03.500",
  "head_block_producer": "eosio",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576,
  "server_version_string": "v1.5.0"
}
```

**Comment by conr2d** [comment]
It seems that your command lose `"` sign during execution. JSON parser recognizes ... '{"threshold": `1,"keys"`: [{ ... as '{"threshold": `1,keys`: [{ ...
Have you passed your arguments through shell script?

**Comment by Viterbo** [comment]
I found the problem !!
I was using the same Public Key from the example instead of using my own public key.
I changed it and worked with no problems.
sorry for the inconvenience and thanks for answering so fast.
