### ISSUE TITLE
 Change class styles

### ISSUE THREAD

**Issue by asvirido** [EOSIO/eos#662]
In c++, class is usually written like this "Transaction"  not a "transaction" etc. Why did you change class name styles? And, variables is usually written like this "nameTable" not a "name_table".
Example
[class **string**](https://github.com/EOSIO/eos/blob/master/contracts/eoslib/string.hpp) 
[class **transaction**](https://github.com/EOSIO/eos/blob/master/contracts/eoslib/transaction.hpp)

**Comment by heifner** [comment]
Define usually. All the C++ standard and Boost classes, for example, are lowercase.
