### ISSUE TITLE
Synchronization speed is really slow

### ISSUE THREAD

**Issue by Coding-Jewelry** [EOSIO/eos#6623]
Hi.
I've just installed EOS node on my Ubuntu VPS.  
Also I did some configuration according to the guide, and started nodeos by running "nodeos -e -p eosio".
The problem seems the speed of block synchronization.   It saves only 2 blocks per second.

My VPS circumstance is
CPUs: 16 vcpus
RAM:  64GB
Disk:   1.2TB

So that, I think that this environment is fully sufficient for the node.

Can you please let me know how I can speed up synchronization?
Maybe is there any extra configuration I should do?    I am not entirely sure about it because I am a newbie on EOS.

Thanks.

**Comment by jgiszczak** [comment]
The given command line is not syncing.  It is generating new blocks locally in a stand alone node.  In that mode it's a local sandbox for contract development purposes.  To sync with mainnet, you may follow the instructions [here](https://eosio.stackexchange.com/questions/725/how-to-vote-using-cleos/726#726), steps 2-7.  To sync with another network, you would need to get peer addresses from the network in question and use those.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by Coding-Jewelry** [comment]
Thanks for letting me know, @jgiszczak 
I will try to follow the guidance and let you know if I have any question.
