### ISSUE TITLE
Cannot create a new account

### ISSUE THREAD

**Issue by Coding-Jewelry** [EOSIO/eos#6628]
Hi.
I've just installed EOS node on my Ubuntu VPS, and it seems be working well.   Sync speed is pretty fast also.
For your information, I ran nodeos like:
"nodeos --genesis-json eos_data/config/genesis.json  --config-dir eos_data/config/ --data-dir eos_data/data/"

I've also created a new wallet, two key pairs and imported them to the wallet.  Then I've imported the key pair for eosio account as well.
So when I execute "cleos -u http://127.0.0.1:5801 wallet keys", then all of the 3 public keys are displaying.
[
  "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
  "EOS7YnvWfj************************************************************",
  "EOS7uBeu8*************************************************************"
]

Then, I've unlocked the wallet.
So I thought that it's sufficient that I can create a new account.

Unfortunately, when I tried 
"cleos -u http://127.0.0.1:5801 create account eosio NEW_ACCOUNT owner_public_key active_public_key"
then it displays an error like

Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"eosio","permission":"active"}', but does not have signatures for it.

I am not sure what's wrong and how I can fix this problem.
Please give me any hint to overcome it.

Thanks.

**Comment by jgiszczak** [comment]
If you are syncing to mainnet, the eosio account is disabled, and in any case it did not have a known key when it was bootstrapped.  The eosio account on a new network is effectively root access, so public networks do not publish that key.

On mainnet and other public networks, you can not create an account unless you already have an account.  There are public services who will use their account to create accounts for you using public keys you provide.  After the ICO ended and the snapshot of the data on the Ethereum network was created, there is no other way to get an account.

When using public account creation services, be very careful not to send public keys for any well known tutorial key pair, such as `EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV`.  Use only keys you have created yourself.  Helpful services blacklist the well known keys, but there's no guarantee everyone is helpful.

**Comment by Coding-Jewelry** [comment]
Hello @jgiszczak , thank you for letting me know.
One more thing - is there any representative public service that can create accounts for me by using keys I created myself?

**Comment by jgiszczak** [comment]
Block.one does not endorse any particular public chain, or recommend services on any particular public chain.  You might ask on [Stack Exchange](https://eosio.stackexchange.com).

**Comment by Coding-Jewelry** [comment]
I had already posted a related one on StackExchange, but I have not got any solution yet.
Here it is: https://eosio.stackexchange.com/questions/3732/cannot-create-a-new-account/3737

Everything seems correct, but still got the same error.
Error Details:
transaction declares authority '{"actor":"eosio","permission":"active"}', but does not have signatures for it.

It means that the following eosio key pair is not correct?
EOSIO public key: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
EOSIO private key: 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3

**Comment by jgiszczak** [comment]
That is the default key pair for a local sandbox testnet.  No public network uses that key pair.

You do not have any key pair that will let you create an account if your node is syncing to any public network.  You may only create accounts on a local private network.  On a local private network that key will work.  It has no other use.

**Comment by Coding-Jewelry** [comment]
Okay, thank you for letting me know.
What I want is to create accounts on public network.  So what is the easiest way to create account on public network?
