### ISSUE TITLE
./eosio_build error

### ISSUE THREAD

**Issue by merwin9** [EOSIO/eos#6629]
$ git clone https://github.com/pacificcode/eos.git --recursive
$ cd eos
$ git submodule update --init --recursive
$ ./eosio_build.sh

Beginning build version: 1.2
2019년 01월 17일 목 오전 8:54:34
User: intc9
git head id: 61e1768692e5fa6ecfffc296952476d69bda9d6e
Current branch: master

    ARCHITECTURE: MINGW64_NT-10.0
./eosio_build.sh: line 213: : No such file or directory

ALL dependencies sucessfully found or installed . Installing EOSIO

CMAKE_BUILD_TYPE=Release
ENABLE_COVERAGE_TESTING=false
DOXYGEN=false

./eosio_build.sh: line 238: : command not found

    >>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error.
what problem..?

**Comment by jgiszczak** [comment]
You're cloning a forked version of the EOS.IO repository, not this one.  You should be cloning from `https://github.com/EOSIO/eos.git`.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
