### ISSUE TITLE
sync always need to restart.

### ISSUE THREAD

**Issue by firesWu** [EOSIO/eos#6641]
when i sync in mainnet, nodeos always stop sync because p2p connection time out, but I restart nodeos wil fix this problem and start sync. but I always need to restart in few days.

**Comment by taokayan** [comment]
Did you try other nodes?

**Comment by firesWu** [comment]
I have three node,  version 1.3.0 , 1.5.3, 1.6.0. This is happen to all of them.

**Comment by heifner** [comment]
Can you share your config.ini, also can you provide log that shows the p2p connection timeout.

**Comment by spoonincode** [comment]
No response to support ticket in months, closing
