### ISSUE TITLE
how to use RPC api push transaction with ref_block_num?

### ISSUE THREAD

**Issue by lixiaodong** [EOSIO/eos#6642]
Transaction A and B

i want to use ref_block_num to protect the transaction 

if A is rollback ,B is rollback too.

i just need to know ,how to use it within RPC api?

**Comment by taokayan** [comment]
you can specify ```--ref-block```, type ```./cleos push transaction``` for more details.

**Comment by jgiszczak** [comment]
The reference block number helps prevent a submitted transaction being lost on an abandoned fork but it provides no guarantees that the second transaction submitted will be incorporated into a block if the first is and rejected if it is not.

To achieve what you desire, submit a single transaction with multiple actions.  A submitted transaction is exactly analogous to a `BEGIN TRANSACTION`/`COMMIT TRANSACTION` pair in SQL.  Actions within it are analogous to statements between the `BEGIN` and `COMMIT`.
