### ISSUE TITLE
Error 3090003 on cleos set account

### ISSUE THREAD

**Issue by joksi01** [EOSIO/eos#6646]
Hello, after I did everything in the tutorial, I was trying to setup the command: 
`cleos set contract hello /home/jovana/contracts/hello -p hello@active`

The output I get is: 
```Failed to get existing code hash, continue without duplicate check...
Reading WASM from /home/jovana/contracts/hello/hello.wasm...
Publishing contract...
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.```

**Comment by nikdale** [comment]
+1 :disappointed:

**Comment by conr2d** [comment]
Have you created `hello` account? That error message is also shown in the case of account non-existence.

**Comment by joksi01** [comment]
I've done that already. Wallet unlocked, has keys, account created, still that error.

**Comment by jgiszczak** [comment]
Can you provide a link to the tutorial you are following?

**Comment by jgiszczak** [comment]
And the output of `./cleos wallet keys`?

**Comment by joksi01** [comment]
```[
  "EOS66v6nn3qZr6CMgdukzSMKFGWpZX4pPeaXNcqL7AvXmvjaJzx1e",
  "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
  "EOS7NRVnMp6PCpdid8sqnLsJBd3sJN6f8qqWBcKWEBGgdeMoCFSZk"
]

**Comment by jgiszczak** [comment]
You'll note none of those keys match the owner and active key for the `hello` account.  Add the private key corresponding to `EOS8QntPwDBNKDZ3ryL8iqM5ojmrxJSVAy1xoUQxeC6vtzqyRHfMe` to your wallet and you'll be able to conduct transactions on the `hello` account.

**Comment by joksi01** [comment]
Where can I find private key for `EOS8QntPwDBNKDZ3ryL8iqM5ojmrxJSVAy1xoUQxeC6vtzqyRHfMe` ?

**Comment by heifner** [comment]
When you created the key for your hello account it created the private key along with your public key.

https://developers.eos.io/eosio-home/docs/wallets#section-step-1-create-a-wallet
https://developers.eos.io/eosio-home/docs/wallets#section-step-4-import-keys-into-your-wallet

If you used `cleos create key --to-console` then the private key was echoed to the console. If you used `--file` then the private key was put in the provided file.
