### ISSUE TITLE
How to create the snapshot in JSON format?

### ISSUE THREAD

**Issue by ChenJiaoZhu** [EOSIO/eos#6649]
I know snapshots can be triggered at runtime using the RPC available through the `producer_api_plugin` with

`curl http://127.0.0.1:8888/v1/producer/create_snapshot`

but it is binary format, so how to create with JSON format or how can I transfer .bin to .json? Thanks for helping.

details refer to: https://github.com/EOSIO/eos/pull/5956

**Comment by matthewdarwin** [comment]
What are you trying to do with the snapshot file that you want it in JSON format?  The snapshot is meant to be used only by nodeos so it doesn't need to sync all the blocks from scratch.

**Comment by ChenJiaoZhu** [comment]
> What are you trying to do with the snapshot file that you want it in JSON format? The snapshot is meant to be used only by nodeos so it doesn't need to sync all the blocks from scratch.

I want to get the snapshot of the blockchain account state included keys, balance and so on, without mongo plunging, are there any other methods?
