### ISSUE TITLE
Build error happened in libcrypto.a (threads_pthread.o)， How to fix it?

### ISSUE THREAD

**Issue by laravel1112** [EOSIO/eos#6650]
When I use "git clone https://github.com/eosio/eos --recursive", and then run "./eosio_build.sh". everythings look ok until meet the following errors.

What should I do to fix such problems?

[ 91%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/resource_limits.cpp.o
[ 91%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/chain_config.cpp.o
**[ 91%] Linking CXX executable test_cypher_suites
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':
(.text+0x16): undefined reference to `pthread_atfork'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/build.make:113: recipe for target 'libraries/fc/test/crypto/test_cypher_suites' failed
make[2]: *** [libraries/fc/test/crypto/test_cypher_suites] Error 1
CMakeFiles/Makefile2:783: recipe for target 'libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all' failed
make[1]: *** [libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....**
[ 91%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/chain_id_type.cpp.o
[ 91%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/genesis_state.cpp.o
[ 91%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/genesis_state_root_key.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/wast_to_wasm.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/wasm_eosio_validation.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/wasm_eosio_injection.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/apply_context.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/abi_serializer.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/asset.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/snapshot.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/webassembly/wavm.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/webassembly/wabt.cpp.o
[ 92%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/transaction_metadata.cpp.o
[ 92%] Linking CXX static library libeosio_chain.a
[ 92%] Built target eosio_chain
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

        >>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

I'm using Ubuntu 16.04.
I already tried to remove, clone the fresh repo and retried `./eosio_build.sh` several times but no luck.
I researched all other issues and no case seems to be match.

**Comment by taokayan** [comment]
what's your OS version?

**Comment by laravel1112** [comment]
Ubuntu 16.04

**Comment by jgiszczak** [comment]
What's the result of `dpkg -l | grep pthread`?  You should have `libpthread-stubs0-dev` installed.

**Comment by jgiszczak** [comment]
What's the result of `dpkg -S /usr/lib/x86_64-linux-gnu/libcrypto.a`?  If it's `libssl-dev:amd64:`, what's the output of `dpkg -l | grep libssl-dev`?

**Comment by laravel1112** [comment]
The result of `dpkg -S /usr/lib/x86_64-linux-gnu/libcrypto.a` is `libssl-dev:amd64: /usr/lib/x86_64-linux-gnu/libcrypto.a`.

The output of `dpkg -l | grep libssl-dev` is 
> ii  libssl-dev:amd64                 1.1.1a-2+ubuntu16.04.1+deb.sury.org+1         amd64        Secure Sockets Layer toolkit - development files

**Comment by jgiszczak** [comment]
That's very much unexpected and is probably the problem.  It should be
```
ii  libssl-dev:amd64                           1.0.2g-1ubuntu4.14                           amd64        Secure Sockets Layer toolkit - development files
```
I don't know how you got 1.1.1a on Ubuntu 16.  Are you sure you're still running Ubuntu 16?

**Comment by laravel1112** [comment]
yes, It's Ubuntu 16 as it is in the result.
But the weird thing is that, it says ubuntu 16.04.1 in the output of `dpkg -l | grep libssl-dev`.
But when I access to the server via putty, it says like this.

> Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-141-generic x86_64)

As you can see, the versions are bit different, one is 16.04.1 and another is 16.04.5.
I hope this can be a hint for you.

**Comment by hbquan93** [comment]
I meet same problem above. May I help you??? 
-------------------------------------------------
Scanning dependencies of target test_cypher_suites
[  9%] Building CXX object libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/test_cypher_suites.cpp.o
[  9%] Linking CXX executable test_cypher_suites
libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/build.make:113: recipe for target 'libraries/fc/test/crypto/test_cypher_suites' failed
CMakeFiles/Makefile2:783: recipe for target 'libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all' failed
Makefile:138: recipe for target 'all' failed

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

-----------------------------
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libraries/fc/test/crypto/test_cypher_suites] Error 1
make[1]: *** [libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all] Error 2
make: *** [all] Error 2

**Comment by hbquan93** [comment]
Who can help me??? Thank you very much
-----
Maybe I failed cause fc libraries....

[  8%] Built target fc
Scanning dependencies of target test_cypher_suites
[  9%] Building CXX object libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/test_cypher_suites.cpp.o
[  9%] Linking CXX executable test_cypher_suites
CMakeFiles/test_cypher_suites.dir/test_cypher_suites.cpp.o: In function `cypher_suites::test_k1::test_method()':
/home/quanbh/aWork/eos/libraries/fc/test/crypto/test_cypher_suites.cpp:(.text+0xb76): undefined reference to `fc::crypto::private_key::private_key(std::string const&)'
/home/quanbh/aWork/eos/libraries/fc/test/crypto/test_cypher_suites.cpp:(.text+0xc6f): undefined reference to `fc::crypto::private_key::operator std::string() const'
/home/quanbh/aWork/eos/libraries/fc/test/crypto/test_cypher_suites.cpp:(.text+0xda7): undefined reference to `fc::crypto::public_key::operator std::string() const'
/home/quanbh/aWork/eos/libraries/fc/test/crypto/test_cypher_suites.cpp:(.text+0x10f4): undefined reference to `fc::logger::get(std::string const&)'
/home/quanbh/aWork/eos/libraries/fc/test/crypto/test_cypher_suites.cpp:(.text+0x1151): undefined reference to `fc::logger::get(std::string const&)'
/home/quanbh/aWork/eos/libraries/fc/test/crypto/test_cypher_suites.cpp:(.text+0x11ba): undefined reference to `fc::exception::to_detail_string(fc::log_level) const'

**Comment by jgiszczak** [comment]
@hbquan93 Try `git submodule update --init --recursive` at the top level of your `eos` checkout and rebuild.

**Comment by crazybits** [comment]
same issue here on ubuntu 18 , but osx is fine

**Comment by crazybits** [comment]
@all fyi, add `--pthread` options while compiling could fix the issue

**Comment by i-love-to-code** [comment]
You can downgrade OpenSSL to the expected version on that machine as follows: 

`sudo apt-get purge -y libssl1.0.0 libssl-dev`
 `sudo apt-get install -y libssl1.0.0=1.0.2g-1ubuntu4.15 libssl-dev=1.0.2g-1ubuntu4.15`

**Comment by heifner** [comment]
Old issue, closing.

**Comment by penglipeng666** [comment]
same issue here on ubuntu 18 , but 16.0.4 is fine
