### ISSUE TITLE
智能合约是否可以引用外面的c++库？

### ISSUE THREAD

**Issue by lifu568** [EOSIO/eos#6652]
智能合约是否可以引用外面的c++库？

**Comment by jgiszczak** [comment]
Libraries that can successfully be built into your smart contract are unusual.  Not all of the standard libraries are available to smart contracts.  Libraries that expect to use the missing parts of the standard C and C++ libraries will not compile.    Many popular external C++ libraries are also very large.  The RAM expense of using them in your smart contract may be too high.

That said, you may use any external library that you can compile and link into your contract with eosio-cpp.
