### ISSUE TITLE
unsigned underflow

### ISSUE THREAD

**Issue by garytone** [EOSIO/eos#6658]
https://github.com/EOSIO/eos/blob/3fddb727b8f3615917707281dfd3dd3cc5d3d66d/plugins/producer_plugin/producer_plugin.cpp#L999

In line 1007, if minimum_slot_producer_index is greater than producer_index, the value of producer_distance will be very large, resulting in a large value of next_block_slot in line 1017, will it affect subsequent production?

**Comment by garytone** [comment]
Code reference is not comprehensive

**Comment by taokayan** [comment]
There's a already a unsigned overflow check at line 1008:
```
      // check for unsigned underflow
      if (producer_distance > producer_index) {
         producer_distance += active_schedule.size();
      }
```

**Comment by taokayan** [comment]
basically you'll see minimum_slot_producer_index is strictly less than active_schedule.size(). Therefore ```producer_distance += active_schedule.size()``` will overflow ```producer_distance``` back to the expected number. Let's consider another example:

unsigned int a = 4;
unsigned int b = a - 5; // <---- after this b will be underflow to INT_MAX
unsigned int c = b + 7; // <---- after this c will be overflow back to 6, which is same as 4 - 5 + 7
 
or generally speaking, 4 - 5 + 7 is always equivalent to 4 + 7 - 5 no matter signed or unsigned integer is used to represent the intermediate values.

**Comment by garytone** [comment]
thank you, I know now
