### ISSUE TITLE
s2wasm is not included in /usr/local folder

### ISSUE THREAD

**Issue by spicynoodle** [EOSIO/eos#666]
Under /eos root folder, after successfully executing `CMake .` to create Makefile, the running `make` command incur errors below 
/bin/sh: /usr/local/s2wasm: No such file or directory
![image](https://user-images.githubusercontent.com/16319106/32688986-e8ca5d1a-c715-11e7-864a-43276ac8d1f6.png)

**Comment by spicynoodle** [comment]
This problem will be solved by 
```
mkdir -p ~/eos/build && cd ~/eos/build
cmake -DBINARYEN_BIN=~/binaryen/bin -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib ..
make -j4
```

**Comment by spicynoodle** [comment]
I have solved this problem, but I still donnot understand what is the root cause of problem, and what's the role s2wasm played in EOS?

**Comment by heifner** [comment]
It is part of the process of generating WebAssembly from a contract.
