### ISSUE TITLE
how to shut down resource consumtion in transaction?

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#6663]
how to shut down resource consumtion in transaction?

I have build a private eos network,and is there a way  to shut down  resource consumtion in transaction?

**Comment by csquan** [comment]
I had set set_resource_limits(newact,-1,-1,-1) in function newaccount of system contract ,can it solve problem?

**Comment by jgiszczak** [comment]
In a private network, if you want to minimize resource usage of nodes, you may pause production until you need to conduct transactions.  Enable `eosio::producer_api_plugin` in your config file to gain access to the `v1/producer/pause` and `v1/producer/resume` APIs.

**Comment by csquan** [comment]
@jgiszczak,I understand what you said.but it only  minimize resource usage of nodes,and to do this ,I must  enable eosio::producer_api_plugin in config file to gain access to the v1/producer/pause and v1/producer/resume APIs.
Before I issue this,I had set set_resource_limits(newact,-1,-1,-1) in function newaccount of system contract after I reserach the code of eos,and it does look like there is no resource limit in  transaction.
But when I do stress testing of transaction with one account,after about one hour,there is  prompt of resource exhaust and can not do any transaction.so this way can not solve my problem.
That is why I issue this problem.

**Comment by taokayan** [comment]
What's your value of ```--chain-state-db-size-mb``` in your config? Have you set it to a relative large number?

**Comment by csquan** [comment]
yes,I had set it to 64G.

**Comment by taokayan** [comment]
What does your error message look like? Is it related to one account or related to the whole blockchain?

**Comment by csquan** [comment]
I have forget exactly error message ,but I do rember it is related to one account,because after changed to another account,it can continue do transaction again.

**Comment by jgiszczak** [comment]
Now I understand.

On a private network, the easiest way to disable resource checking for an account is to make it privileged.
```bash
cleos push action eosio setpriv '["youraccount", 1]' -p eosio@active
```
where `"youraccount"` is the name of the account to be privileged.  That allows youraccount completely unrestricted ability to execute transactions on your nodes.

If you wish to maintain some restrictions, simply stake more of your system token for network and CPU bandwidth.  This is the only solution possible on public networks.

**Comment by csquan** [comment]
@jgiszczak,thank you for your answer.
