### ISSUE TITLE
Is server_version_string of nodeos v1.5.4 wrong?

### ISSUE THREAD

**Issue by newyangyang** [EOSIO/eos#6664]
I just update my nodeos version to v1.5.4 (with ubuntu deb file). 
chain/get_info returns `"server_version":"a09083c8"` and `"server_version_string":"v1.5.0-rc2-21-ga09083c"`. The server_version is in accordance with the git commit id,  but server_version_string is either wrong or misleading, since we already have a v1.5.0-rc2 release.

**Comment by conr2d** [comment]
Well, server_version_string follows git tag, so if the last commit-id is same to that of released version, it might be a mistake. (Just not tagged correctly)

**Comment by matthewdarwin** [comment]
The same thing happened on the v1.6.0 release, which was subsequently updated to fix this issue.
