### ISSUE TITLE
Compiling test contract freezes

### ISSUE THREAD

**Issue by batrlatom** [EOSIO/eos#6670]
Hi, I have installed eos according to your documentation and everything works fine.
Until I want to compile your test code from hello contract.

System: Ubuntu 18.04, 64bit version, running as a VM somewhere in the datacenter.
eosio-cpp version 1.4.1 ... it gives out the output bellow
eosio-cpp version 1.5.0 .... total freeze, created files
-rw-rw-r-- 1 recall recall  1271 Jan 26 22:19 hello.wasm
-rwxrwxr-x 1 recall recall 10810 Jan 26 22:19 hello.wasm.tmpcebd77a

```
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>

using namespace eosio;

class hello : public contract {
  public:
      using contract::contract;

      [[eosio::action]]
      void hi( name user ) {
         print( "Hello, ", user);
      }
};

EOSIO_DISPATCH( hello, (hi))
```

I am using `eosio-cpp -o hello.wasm hello.cpp --abigen` to compile the code, but the compilation code crashes.

Output is:

clang version 7.0.0 (https://github.com/eosio/clang.git 3e38ccb3dacee8c53ed6d3d5a59d1f6d4f0c96cf) (https://github.com/eosio/llvm 9d682f7ebbdc50c2ad620f46d04d2aa94523f8f3)
Target: wasm32
Thread model: single
InstalledDir: /usr/opt/eosio.cdt/1.4.1/bin
 "/usr/opt/eosio.cdt/1.4.1/bin/clang-7" -cc1 -triple wasm32 -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello.cpp -mrelocation-model static -mthread-model single -masm-verbose -mconstructor-aliases -ffreestanding -fuse-init-array -target-cpu generic -fvisibility hidden -dwarf-column-info -debugger-tuning=gdb -momit-leaf-frame-pointer -v -coverage-notes-file /home/recall/eostest/contracts/hello/hello.gcno -resource-dir /usr/opt/eosio.cdt/1.4.1/lib/clang/7.0.0 -D BOOST_DISABLE_ASSERTS -D BOOST_EXCEPTION_DISABLE -I /usr/opt/eosio.cdt/1.4.1/bin/../include/libcxx -I /usr/opt/eosio.cdt/1.4.1/bin/../include/libc -I /usr/opt/eosio.cdt/1.4.1/bin/../include -isysroot /usr/opt/eosio.cdt/1.4.1/bin/../ -internal-isystem /usr/opt/eosio.cdt/1.4.1/bin/..//include/c++/v1 -internal-isystem /usr/opt/eosio.cdt/1.4.1/bin/..//include -O3 --std=c++17 -fdeprecated-macro -fdebug-compilation-dir /home/recall/eostest/contracts/hello -ferror-limit 19 -fmessage-length 80 -fno-builtin -fno-rtti -fno-threadsafe-statics -fobjc-runtime=gnustep -fno-common -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -load /usr/opt/eosio.cdt/1.4.1/bin/eosio_plugin.so -load /usr/opt/eosio.cdt/1.4.1/bin/LLVMEosioApply.so -mllvm -use-cfl-aa-in-codegen=both -o hello.wasm -x c++ hello.cpp
clang -cc1 version 7.0.0 based upon LLVM 7.0.0svn default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/usr/opt/eosio.cdt/1.4.1/bin/..//include/c++/v1"
ignoring nonexistent directory "/usr/opt/eosio.cdt/1.4.1/bin/..//usr/local/include"
ignoring nonexistent directory "/usr/opt/eosio.cdt/1.4.1/lib/clang/7.0.0/include"
ignoring nonexistent directory "/usr/opt/eosio.cdt/1.4.1/bin/..//usr/include"
ignoring duplicate directory "/usr/opt/eosio.cdt/1.4.1/bin/../include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /usr/opt/eosio.cdt/1.4.1/bin/../include/libcxx
 /usr/opt/eosio.cdt/1.4.1/bin/../include/libc
 /usr/opt/eosio.cdt/1.4.1/bin/../include
End of search list.

**Comment by taokayan** [comment]
What's your available RAM in your VM? It's better to be 8GB or more.

**Comment by jgiszczak** [comment]
Yes, you may compile a contract and then run it on such a machine.  That machine can not participate in any major public network, for lack of RAM and an SSD.  You may run a private network node though.

To successfully compile a contract, you need a second core.  This issue is being tracked in EOSIO/eosio.cdt#288.
