### ISSUE TITLE
Sync with the mainnet doesn't work

### ISSUE THREAD

**Issue by 4ban** [EOSIO/eos#6671]
Hello, I'm trying to set up the EOS node but for every p2p-peer-addresses I got errors such as Connection refused, Connection reset by peer or closed connection. 

It worked a week ago, but now I can't sync my node with the mainnet.

What could be the reason and how can it be fixed?

EOS server version 1.6.0

**Comment by matthewdarwin** [comment]
The endpoints listed here are checked every 30 minutes for connectivity.
https://validate.eosnation.io/mainnet/reports/config.html

**Comment by 4ban** [comment]
I know, and for all of them, I'm getting the same errors.

**Comment by matthewdarwin** [comment]
Do you have the correct genesis configuration?   Any specific errors in the log?

**Comment by 4ban** [comment]
The part of the log and genesis are on gist.
I didn't notice any specific errors. It just trying to connect to the peers in the loop.

https://gist.github.com/4ban/26008f50495453abdbdb6f611e7013a6

**Comment by matthewdarwin** [comment]
You are somehow not passing the correct genesis to nodeos. The log line should read:
```
Blockchain started; head block is #1, genesis timestamp is 2018-06-08T08:08:08.888
```
(yours has a different timestamp)

**Comment by 4ban** [comment]
Interesting.

Well, I've changed start script to be sure that genesis is in use: `nodeos --data-dir $DATADIR --config-dir $CONFIGDIR --delete-all-blocks --genesis-json genesis.json --hard-replay-blockchain`

https://gist.github.com/4ban/335b486a6ab690c6464f8fe556fc8868
Line 6 is weird. Seems like the `--hard-replay-blockchain` didn't fix anything. The **data folder was deleted** before start.

Do you have any idea what it could be and how to fix that?

But, despite of the peers errors still there (Connection refused, Connection reset by peer, Bad file descriptor or closed connection), it finally connected to somebody and started to download the blockchain. 

Is it possible that peers rejected me because of different timezones? I think that I'm connected to the peers in my timezone (Montreal, Canada) (I've changed the timezone also on my machine while investigated the genesis incorrect timestamp). I mean that if somebody will meet the same issue, the problem could be in timezones.

Only these peers left in my config:
```
p2p-peer-address = bp.antpool.com:443
p2p-peer-address = fullnode.eoslaomao.com:443
p2p-peer-address = mars.fnp2p.eosbixin.com:443
p2p-peer-address = p2p.eos.bitspace.no:9876
p2p-peer-address = p2p.genereos.io:9876
p2p-peer-address = peer.eosn.io:9876
p2p-peer-address = peer.main.alohaeos.com:9876
p2p-peer-address = peering.mainnet.eoscanada.com:9876 # Montreal, Canada
p2p-peer-address = publicnode.cypherglass.com:9876
```

Thanks, you helped a lot. Its working now.

**Comment by matthewdarwin** [comment]
When I want tro recover from a crash, I always use 2 parameters together: --hard-replay --replay-blockchain.  This means to replay the existing blockchain.  It doesn't mean to start from scratch using the genesis. When I want to restart from scratch, I delete data dir.

Time zone is irrelevant.

BTW, peer.eosn.io:9876 is in Toronto.  It should let you connect.

**Comment by 4ban** [comment]
> Time zone is irrelevant.

Then I can't understand what was the cause of my issue.

Thank you for the help.

**Comment by lambda2003** [comment]
@4ban I seems having the same issue. Could you help me?? How did you fix the issue??
