### ISSUE TITLE
improve performance of boost::multi_index on large data sets then port to nodeos

### ISSUE THREAD

**Issue by snstrand** [EOSIO/eos#6676]
The time performance of boost::multi_index container degrades dramatically when the data set is too large to fit in L3 cache which is commonly the case for nodeos. Boost:multi_index container is not tuned to specifically maximize out-of-cache performance. After many experiments I have settled on a new data structure which uses an AVL height balanced tree with interior nodes consisting of a key and two child pointers and leaf nodes that consist of two vectors (about 300 long) one holding keys (in sorted order for binary search) and the other holding data or pointers to data. This data structure can hold about 50% more keys than boost:multi_index before the runtime for FIND and/or INSERT operations starts to be dominated by cache misses. Nodeos would benefit from use of this data structure but porting it to nodeos is more delicate than a blind drop-in replacement. I am currently learning the nodeos code base as a prelude to doing this port.

**Comment by taokayan** [comment]
I guess the L3 cache might not be that beneficial when the data size has become significantly larger than the cache size. Assume the following configuration:

CPU: Intel® Xeon® Platinum 8180 with cache: 38.5 MB L3
mult_index table size on a blockchain: around 10 GB, in which 10%(1GB) data are hot (need to be access/modified frequently at random).

Before improvement:
Cache hit rate = 38.5MB / 1GB = 3.85 %
Cache miss rate = 96.15 %
L3 latency: 20ns
Main memory latency: 100ns
average latency: ~96.8ns

After improvement:
cache hit rate: ~7%
cache miss rate: ~93%
average latency: ~94.4ns

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
