### ISSUE TITLE
nodeos crashes due to empty data/blocks/reversible dir

### ISSUE THREAD

**Issue by ramtej** [EOSIO/eos#6682]
Hello, 

Scenario description: 

```
1) nodeos 1.5.3 or 1.6.x
2) --plugin eosio::chain_api_plugin
3) a empty data/blocks/reversible directory is created
4) start nodeos
5) boost::interprocess_exception::library_error exception is generated
```

> info  2019-01-29T15:49:51.495 thread-0  block_log.cpp:522             repair_log           ] Existing block log was undamaged. Recovered all irreversible blocks up to block number 1000.
> warn  2019-01-29T15:49:51.495 thread-0  chain_plugin.cpp:707          plugin_initialize    ] 13 N5boost12interprocess22interprocess_exceptionE: boost::interprocess_exception::library_error
> rethrow boost::interprocess_exception::library_error: 
>     {"what":"boost::interprocess_exception::library_error"}
>     thread-0  chain_plugin.cpp:707 plugin_initialize
> error 2019-01-29T15:49:51.495 thread-0  main.cpp:129                  main                 ] 13 N5boost12interprocess22interprocess_exceptionE: boost::interprocess_exception::library_error
> rethrow boost::interprocess_exception::library_error: 
>     {"what":"boost::interprocess_exception::library_error"}
>     thread-0  chain_plugin.cpp:707 plugin_initialize

Testcase: 

https://github.com/eosgermany/nodeos_devops_tests/blob/6f578acf71389cf947dfc46a61efb417f672a501/unit/tests/test_10-nodeos-crashes-when-empty-reversible-dir-is-available.sh#L42

Best Regards, 
jj

**Comment by ndcgundlach** [comment]
Unable to reproduce in 1.8.
