### ISSUE TITLE
contract error

### ISSUE THREAD

**Issue by boy-good** [EOSIO/eos#6688]
{"code":500,"message":"Internal Service Error","error":{"code":13,"name":"N5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE","what":"could not insert object, most likely a uniqueness constraint was violated","details":[]}}

**Comment by taokayan** [comment]
Is the exception thrown inside the contract? Looks like it tries to insert the data with same id.

**Comment by stefanzarembinski** [comment]
I cannot even try to comment your problem without knowing the context of the error message.

**Comment by spoonincode** [comment]
No response from submitter in months, closing
