### ISSUE TITLE
eosio brew tap repo link typo ?

### ISSUE THREAD

**Issue by gravitt8460** [EOSIO/eos#6692]
When trying to install eosio using brew, it is fails with “fatal: repository https://github.com/esoio/homebrew-eosio not found”.  It looks like the github account “eosio” is misspelled. Is there a way to install it via brew or does something need to be changed in the build?

**Comment by larryk85** [comment]
This seems like an issue with your tap.  Can you run `brew untap esoio/eosio`? and then `brew tap eosio/eosio` and see if that resolves your issue.

**Comment by spoonincode** [comment]
No response to support ticket in over 2 months, closing
