### ISSUE TITLE
EOS v 1.5 suddenly stop 

### ISSUE THREAD

**Issue by sicute** [EOSIO/eos#6719]
i have 3 EOS node with  version 1.5  in aws and sudden they are stop and  make dirty database againt .
any solustion for that.
How about if i upgrade to 1.6 will be solved that problem without make dirty database againt.

**Comment by matthewdarwin** [comment]
Suggest to take regular backups and then restore from backup.
Alternately if you don't need history, you can start from a snapshot instead.  EOS Mainnet snapshots can be found here: https://eosnode.tools/snapshots

**Comment by sicute** [comment]
i need history data so i restore from backup and catchup sync

**Comment by jgiszczak** [comment]
What was in the logs when nodeos stopped?

**Comment by sicute** [comment]
here i have 3  instance in aws , there always  stuck and make dirty database 
, here last log : 
`error 2019-02-25T10:01:54.909 thread-0  net_plugin.cpp:1903           operator()           ] connection failed to publicapi-mainnet.sheleaders.one:6789: Connection refused
info  2019-02-25T10:01:58.872 thread-0  net_plugin.cpp:2115           operator()           ] Peer eosdapp.oneeos.org:9000 closed connection
info  2019-02-25T10:01:58.944 thread-0  net_plugin.cpp:2115           operator()           ] Peer fn001.eossv.org:443 closed connection
info  2019-02-25T10:01:59.177 thread-0  net_plugin.cpp:2115           operator()           ] Peer p2p.eoseoul.io:9876 closed connection
error 2019-02-25T10:02:01.564 thread-0  net_plugin.cpp:1903           operator()           ] connection failed to api4.eosmetal.io:19877: Connection refused
error 2019-02-25T10:02:01.877 thread-0  net_plugin.cpp:1903           operator()           ] connection failed to p2p.mainnet.eos.eosgermany.online:9876: Connection refused
info  2019-02-25T10:02:03.727 thread-0  net_plugin.cpp:2115           operator()           ] Peer seed2.eos42.io:9876 closed connection
error 2019-02-25T10:02:03.951 thread-0  net_plugin.cpp:1903           operator()           ] connection failed to peer-mainnet.eospacex.com:88: Connection refused
error 2019-02-25T10:02:04.599 thread-0  net_plugin.cpp:1903           operator()           ] connection failed to node1.bp.eosindex.io:9876: Connection refused
error 2019-02-25T10:02:06.728 thread-0  net_plugin.cpp:1903           operator()           ] connection failed to p2p.eosio.cr:5418: Connection refused`

and here log another 
`info  2019-02-25T21:04:40.652 thread-0  net_plugin.cpp:2142           operator()           ] Peer eos.genesis-mining.com:19876 closed connection
error 2019-02-25T21:04:40.670 thread-0  net_plugin.cpp:1963           operator()           ] connection failed to api.eos.wiki:39876: Connection refused
error 2019-02-25T21:04:40.981 thread-0  net_plugin.cpp:1963           operator()           ] connection failed to peer.eosfengwo.com:8080: Connection refused
error 2019-02-25T21:04:41.058 thread-0  net_plugin.cpp:1963           operator()           ] connection failed to node.eoswing.io:8769: Connection reset by peer
info  2019-02-25T21:04:41.269 thread-0  net_plugin.cpp:2142           operator()           ] Peer node1.eoscannon.io:59876 closed connection
info  2019-02-25T21:04:41.289 thread-0  net_plugin.cpp:2142           operator()           ] Peer p2p-mainnet.eosgravity.com:8001 closed connection`
also every day i must stop and start eos other wise the block import will be slowdown .

**Comment by spoonincode** [comment]
Are you still having issues on 1.6, 1.7 or 1.8?

**Comment by sicute** [comment]
already fix and problem no show at version 1.7.4  
i close it
