### ISSUE TITLE
bug hello.cpp Name

### ISSUE THREAD

**Issue by gaoqiaizhanglan** [EOSIO/eos#672]
当使用eoscpp -n hello对hello.cpp进行创建时，语句 eosio::print( "Hello World: ", eosio::Name(code), "->", eosio::Name(action), "\n" )与Namespace不符，应将其改为 eosio::print( "Hello World: ", eosio::name(code), "->", eosio::name(action), "\n" );方能正确编译

**Comment by asvirido** [comment]
Please, write in English)

**Comment by gaoqiaizhanglan** [comment]
In  hello.cpp created by " eoscpp -n hello" , word 'Name' in sentence  eosio::print( "Hello World: ", eosio::Name(code), "->", eosio::Name(action), "\n" ) is incompatible with the namespace. It should be changed to eosio::print( "Hello World: ", eosio::name(code), "->", eosio::name(action), "\n" );

**Comment by asvirido** [comment]
There did not change the name of the function `eosio::Name` in command `eoscpp -n hello`?

**Comment by gaoqiaizhanglan** [comment]
Maybe, I remenmbered when I checked the type.hpp it said that the function was 'name' , but in hello.cpp it was 'Name'.

**Comment by asvirido** [comment]
yes, it's error in smart-contract.

**Comment by gaoqiaizhanglan** [comment]
ok

**Comment by asvirido** [comment]
I reported an error)
