### ISSUE TITLE
./eosc get servants inita

### ISSUE THREAD

**Issue by gaoqiaizhanglan** [EOSIO/eos#673]
$ ./eosc get servants inita
1273547ms thread-0   main.cpp:1110                 main                 ] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error code 404
: {"code":404,"message":"Not Found","details":"Unknown Endpoint"}

    {"c":404,"msg":"{\"code\":404,\"message\":\"Not Found\",\"details\":\"Unknown Endpoint\"}"}
    thread-0  httpc.cpp:113 call

    {"server":"localhost","port":8888,"path":"/v1/account_history/get_controlled_accounts","postdata":{"controlling_account":"inita"}}
    thread-0  httpc.cpp:117 call

**Comment by heifner** [comment]
This account history plugin is needed for this.
```
plugin = eosio::account_history_plugin
plugin = eosio::account_history_api_plugin
```

**Comment by gaoqiaizhanglan** [comment]
Thanks, I'll try it later.
