### ISSUE TITLE
Unable to connect to  Wallet RPC API

### ISSUE THREAD

**Issue by sneha6patel** [EOSIO/eos#6730]
Hello I am also new to EOS and want to o connect to HTTP/RPC API but when i'm using wallet rpc api to create wallet using python. It's getting 404 errors.

Here is my python code..............................

import requests
headers = {
'Cache-Control': 'no-cache',
'Content-Type' : 'application/json',
'charset' : 'UTF-8'
}
data = '"Wallet-1"'

response = requests.post("http://localhost:8900/v1/wallet/create", data=data)

print(response.json())

And the errors are.....................................................................

{'message': 'Not Found', 'error': {'details': [{'message': 'Unknown Endpoint', 'line_number': 298, 'method': 'handle_http_request', 'file': 'http_plugin.cpp'}], 'what': 'unspecified', 'name': 'exception', 'code': 0}, 'code': 404}

**Comment by jgiszczak** [comment]
Nodeos does not run the wallet plugins.  Keosd is the wallet daemon.  It uses a Unix socket in `~/eosio-wallet` by default.  Executing `cleos wallet list` will launch it for you.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
