### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridiscom** [EOSIO/eos#6734]

**Comment by matthewdarwin** [comment]
You might try starting with https://www.eosdocs.io

**Comment by lazaridiscom** [comment]
@matthewdarwin , this looks quite thorough, yet it seems to not contain what I'm asking for (e.g. a collection of end-user getting started).

What I would need is an overview of wallets (open source), and of DApps (ideally very simple, and with open source). Doing the research is quite an effort, and so, at least some basic starting pointers should be given by the main EOS website.

**Comment by lazaridiscom** [comment]
I found this here:

https://www.reddit.com/r/eos/comments/9y54yp/eos_getting_started_helpful_links/

which has some end-user tools listed.
