### ISSUE TITLE
what size of RAM  does an account need? 

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#6740]
I had  a solution which use mongo to store transaction data and does not use history plugin,chainbase of eos still store state data,when the size of chainbase overweight the limit which write in config.ini,eos will crush.my  business scenario is simple ,just transfer XXX. 
so my question is ,what size of RAM  does an account need? I must  estimate how many accounts does eos can hold.

**Comment by jgiszczak** [comment]
EOS.IO accounts are created with a total used and reserved space of approximately 3 kibibytes each.  There is a hardcoded minimum of 2048 bytes (2 KiB).  See discussion in #5522.

**Comment by csquan** [comment]
@jgiszczak,as you mean,each account 's state data store in chainbase use max 5kb at most. So if writen 5G in config.ini ,then eos can hold 1000,000 accounts. Am i said right?
