### ISSUE TITLE
how many accounts eos can hold?

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#6751]
@jgiszczak,as you mean(refer to 6740),each account 's state data store in chainbase use max 5kb at most. So if writen 5G in config.ini ,then eos can hold 1000,000 accounts. Am i said right?

**Comment by jgiszczak** [comment]
The ultimate account capacity of EOS.IO depends on the hardware the producer nodes are running.  If all producers are running on dual EPYC machines with maximum configurable RAM, EOS.IO can accommodate ~1.4 billion (~1.4 × 10<sup>9</sup>) accounts, assuming no other contract state.  If you wish to reserve 5 KiB per account, on the above hardware EOS.IO can accommodate ~850 million (~850 × 10<sup>6</sup>) accounts.
