### ISSUE TITLE
nodeos  version 1.6 crash dump in Ubuntu 16.04

### ISSUE THREAD

**Issue by sicute** [EOSIO/eos#6752]
i check node was get late block sync and i check  top there was apport high usage and check there was error nodeos .
here log i got : 
`cat /var/crash/_usr_opt_eosio_1.6.1_bin_nodeos.1001.crash
ProblemType: Crash
Architecture: amd64
CrashCounter: 1
Date: Fri Feb 15 07:12:30 2019
DistroRelease: Ubuntu 16.04
ExecutablePath: /usr/opt/eosio/1.6.1/bin/nodeos
ExecutableTimestamp: 1549552448
ProcCmdline: /usr/bin//nodeos --data-dir /mnt/eos/eosio//data --config-dir /mnt/eos/eosio//config --disable-replay-opts
ProcCwd: /home/ubuntu
ProcEnviron:
 SHELL=/bin/bash
 TERM=xterm-256color
 PATH=(custom, user)
 LANG=en_US.UTF-8
 LC_CTYPE=en_US.UTF-8"
 XDG_RUNTIME_DIR=<set>
ProcMaps:
 00400000-02bb9000 r-xp 00000000 103:02 537927                            /usr/opt/eosio/1.6.1/bin/nodeos
 02db8000-02ed0000 r--p 027b8000 103:02 537927                            /usr/opt/eosio/1.6.1/bin/nodeos
 02ed0000-02f2c000 rw-p 028d0000 103:02 537927                            /usr/opt/eosio/1.6.1/bin/nodeos
 02f2c000-02f5a000 rw-p 00000000 00:00 0
 04767000-37faf2000 rw-p 00000000 00:00 0                                 [heap]
 7f968c000000-7f968f177000 rw-p 00000000 00:00 0
 7f968f177000-7f9690000000 ---p 00000000 00:00 0
 7f9694000000-7f969416c000 rw-p 00000000 00:00 0
 7f969416c000-7f9698000000 ---p 00000000 00:00 0
 7f9698000000-7f969b10b000 rw-p 00000000 00:00 0
 7f969b10b000-7f969c000000 ---p 00000000 00:00 0
 7f969c000000-7f969c165000 rw-p 00000000 00:00 0
 7f969c165000-7f96a0000000 ---p 00000000 00:00 0
 7f96a0000000-7f96a0169000 rw-p 00000000 00:00 0
 7f96a0169000-7f96a4000000 ---p 00000000 00:00 0
 7f96a4000000-7f96a4171000 rw-p 00000000 00:00 0
 7f96a4171000-7f96a8000000 ---p 00000000 00:00 0
 7f96a8000000-7f96a8170000 rw-p 00000000 00:00 0
 7f96a8170000-7f96ac000000 ---p 00000000 00:00 0
 7f96ac000000-7f96ac165000 rw-p 00000000 00:00 0
 7f96ac165000-7f96b0000000 ---p 00000000 00:00 0
 7f96b0000000-7f96b0188000 rw-p 00000000 00:00 0
 7f96b0188000-7f96b4000000 ---p 00000000 00:00 0
 7f96b4000000-7f96b4176000 rw-p 00000000 00:00 0
 7f96b4176000-7f96b8000000 ---p 00000000 00:00 0
 7f96c8000000-7f96c8021000 rw-p 00000000 00:00 0
 7f96c8021000-7f96cc000000 ---p 00000000 00:00 0
 7f96d4000000-7f96d4021000 rw-p 00000000 00:00 0
 7f96d4021000-7f96d8000000 ---p 00000000 00:00 0
 7f96d9a11000-7f96d9a16000 r-xp 00000000 103:02 1990                      /lib/x86_64-linux-gnu/libnss_dns-2.23.so
 7f96d9a16000-7f96d9c16000 ---p 00005000 103:02 1990                      /lib/x86_64-linux-gnu/libnss_dns-2.23.so
 7f96d9c16000-7f96d9c17000 r--p 00005000 103:02 1990                      /lib/x86_64-linux-gnu/libnss_dns-2.23.so
 7f96d9c17000-7f96d9c18000 rw-p 00006000 103:02 1990                      /lib/x86_64-linux-gnu/libnss_dns-2.23.so
 7f96d9c18000-7f96d9c23000 r-xp 00000000 103:02 1993                      /lib/x86_64-linux-gnu/libnss_files-2.23.so
 7f96d9c23000-7f96d9e22000 ---p 0000b000 103:02 1993                      /lib/x86_64-linux-gnu/libnss_files-2.23.so
 7f96d9e22000-7f96d9e23000 r--p 0000a000 103:02 1993                      /lib/x86_64-linux-gnu/libnss_files-2.23.so
 7f96d9e23000-7f96d9e24000 rw-p 0000b000 103:02 1993                      /lib/x86_64-linux-gnu/libnss_files-2.23.so
 7f96d9e24000-7f96d9e2a000 rw-p 00000000 00:00 0
 7f96ddcab000-7f96ddcac000 ---p 00000000 00:00 0
 7f96ddcac000-7f96e1b2c000 rw-p 00000000 00:00 0
 7fe71e036000-7fe71e04c000 r-xp 00000000 103:02 1975                      /lib/x86_64-linux-gnu/libgcc_s.so.1
 7fe71e04c000-7fe71e24b000 ---p 00016000 103:02 1975                      /lib/x86_64-linux-gnu/libgcc_s.so.1
 7fe71e24b000-7fe71e24c000 rw-p 00015000 103:02 1975                      /lib/x86_64-linux-gnu/libgcc_s.so.1
 7fe71e24c000-7fe71e3be000 r-xp 00000000 103:02 76                        /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
 7fe71e3be000-7fe71e5be000 ---p 00172000 103:02 76                        /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
 7fe71e5be000-7fe71e5c8000 r--p 00172000 103:02 76                        /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
 7fe71e5c8000-7fe71e5ca000 rw-p 0017c000 103:02 76                        /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
 7fe71e5ca000-7fe71e5ce000 rw-p 00000000 00:00 0
 7fe71e5ce000-7fe71e5e5000 r-xp 00000000 103:02 1984                      /lib/x86_64-linux-gnu/libresolv-2.23.so
 7fe71e5e5000-7fe71e7e5000 ---p 00017000 103:02 1984                      /lib/x86_64-linux-gnu/libresolv-2.23.so
 7fe71e7e5000-7fe71e7e6000 r--p 00017000 103:02 1984                      /lib/x86_64-linux-gnu/libresolv-2.23.so
 7fe71e7e6000-7fe71e7e7000 rw-p 00018000 103:02 1984                      /lib/x86_64-linux-gnu/libresolv-2.23.so
 7fe71e7e7000-7fe71e7e9000 rw-p 00000000 00:00 0
 7fe71e7e9000-7fe71ea04000 r-xp 00000000 103:02 6198                      /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
 7fe71ea04000-7fe71ec03000 ---p 0021b000 103:02 6198                      /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
 7fe71ec03000-7fe71ec1f000 r--p 0021a000 103:02 6198                      /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
 7fe71ec1f000-7fe71ec2b000 rw-p 00236000 103:02 6198                      /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
 7fe71ec2b000-7fe71ec2e000 rw-p 00000000 00:00 0
 7fe71ec2e000-7fe71ec8c000 r-xp 00000000 103:02 6133                      /lib/x86_64-linux-gnu/libssl.so.1.0.0
 7fe71ec8c000-7fe71ee8c000 ---p 0005e000 103:02 6133                      /lib/x86_64-linux-gnu/libssl.so.1.0.0
 7fe71ee8c000-7fe71ee90000 r--p 0005e000 103:02 6133                      /lib/x86_64-linux-gnu/libssl.so.1.0.0
 7fe71ee90000-7fe71ee97000 rw-p 00062000 103:02 6133                      /lib/x86_64-linux-gnu/libssl.so.1.0.0
 7fe71ee97000-7fe71ee9e000 r-xp 00000000 103:02 1998                      /lib/x86_64-linux-gnu/librt-2.23.so
 7fe71ee9e000-7fe71f09d000 ---p 00007000 103:02 1998                      /lib/x86_64-linux-gnu/librt-2.23.so
 7fe71f09d000-7fe71f09e000 r--p 00006000 103:02 1998                      /lib/x86_64-linux-gnu/librt-2.23.so
 7fe71f09e000-7fe71f09f000 rw-p 00007000 103:02 1998                      /lib/x86_64-linux-gnu/librt-2.23.so
 7fe71f09f000-7fe71f25f000 r-xp 00000000 103:02 1980                      /lib/x86_64-linux-gnu/libc-2.23.so
 7fe71f25f000-7fe71f45f000 ---p 001c0000 103:02 1980                      /lib/x86_64-linux-gnu/libc-2.23.so
 7fe71f45f000-7fe71f463000 r--p 001c0000 103:02 1980                      /lib/x86_64-linux-gnu/libc-2.23.so
 7fe71f463000-7fe71f465000 rw-p 001c4000 103:02 1980                      /lib/x86_64-linux-gnu/libc-2.23.so
 7fe71f465000-7fe71f469000 rw-p 00000000 00:00 0
 7fe71f469000-7fe71f571000 r-xp 00000000 103:02 1976                      /lib/x86_64-linux-gnu/libm-2.23.so
 7fe71f571000-7fe71f770000 ---p 00108000 103:02 1976                      /lib/x86_64-linux-gnu/libm-2.23.so
 7fe71f770000-7fe71f771000 r--p 00107000 103:02 1976                      /lib/x86_64-linux-gnu/libm-2.23.so
 7fe71f771000-7fe71f772000 rw-p 00108000 103:02 1976                      /lib/x86_64-linux-gnu/libm-2.23.so
 7fe71f772000-7fe71f78b000 r-xp 00000000 103:02 2129                      /lib/x86_64-linux-gnu/libz.so.1.2.8
 7fe71f78b000-7fe71f98a000 ---p 00019000 103:02 2129                      /lib/x86_64-linux-gnu/libz.so.1.2.8
 7fe71f98a000-7fe71f98b000 r--p 00018000 103:02 2129                      /lib/x86_64-linux-gnu/libz.so.1.2.8
 7fe71f98b000-7fe71f98c000 rw-p 00019000 103:02 2129                      /lib/x86_64-linux-gnu/libz.so.1.2.8
 7fe71f98c000-7fe71f9b1000 r-xp 00000000 103:02 2136                      /lib/x86_64-linux-gnu/libtinfo.so.5.9
 7fe71f9b1000-7fe71fbb0000 ---p 00025000 103:02 2136                      /lib/x86_64-linux-gnu/libtinfo.so.5.9
 7fe71fbb0000-7fe71fbb4000 r--p 00024000 103:02 2136                      /lib/x86_64-linux-gnu/libtinfo.so.5.9
 7fe71fbb4000-7fe71fbb5000 rw-p 00028000 103:02 2136                      /lib/x86_64-linux-gnu/libtinfo.so.5.9
 7fe71fbb5000-7fe71fbcd000 r-xp 00000000 103:02 1979                      /lib/x86_64-linux-gnu/libpthread-2.23.so
 7fe71fbcd000-7fe71fdcc000 ---p 00018000 103:02 1979                      /lib/x86_64-linux-gnu/libpthread-2.23.so
 7fe71fdcc000-7fe71fdcd000 r--p 00017000 103:02 1979                      /lib/x86_64-linux-gnu/libpthread-2.23.so
 7fe71fdcd000-7fe71fdce000 rw-p 00018000 103:02 1979                      /lib/x86_64-linux-gnu/libpthread-2.23.so
 7fe71fdce000-7fe71fdd2000 rw-p 00000000 00:00 0
 7fe71fdd2000-7fe71fdd5000 r-xp 00000000 103:02 1982                      /lib/x86_64-linux-gnu/libdl-2.23.so
 7fe71fdd5000-7fe71ffd4000 ---p 00003000 103:02 1982                      /lib/x86_64-linux-gnu/libdl-2.23.so
 7fe71ffd4000-7fe71ffd5000 r--p 00002000 103:02 1982                      /lib/x86_64-linux-gnu/libdl-2.23.so
 7fe71ffd5000-7fe71ffd6000 rw-p 00003000 103:02 1982                      /lib/x86_64-linux-gnu/libdl-2.23.so
 7fe71ffd6000-7fe71fffc000 r-xp 00000000 103:02 1978                      /lib/x86_64-linux-gnu/ld-2.23.so
 7fe7200e9000-7fe7201f4000 rw-p 00000000 00:00 0
 7fe7201f9000-7fe7201fb000 rw-s 00000000 00:14 3                          /dev/shm/mongoc-21133 (deleted)
 7fe7201fb000-7fe7201fc000 r--p 00025000 103:02 1978                      /lib/x86_64-linux-gnu/ld-2.23.so
 7fe7201fc000-7fe7201fd000 rw-p 00026000 103:02 1978                      /lib/x86_64-linux-gnu/ld-2.23.so
 7fe7201fd000-7fe7201fe000 rw-p 00000000 00:00 0
 7ffeebf39000-7ffeebf73000 rw-p 00000000 00:00 0                          [stack]
 7ffeebfd8000-7ffeebfdb000 r--p 00000000 00:00 0                          [vvar]
 7ffeebfdb000-7ffeebfdd000 r-xp 00000000 00:00 0                          [vdso]
 ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
ProcStatus:
 Name:	nodeos
 State:	S (sleeping)
 Tgid:	21133
 Ngid:	0
 Pid:	21133
 PPid:	1
 TracerPid:	0
 Uid:	1001	1001	1001	1001
 Gid:	1001	1001	1001	1001
 FDSize:	64
 Groups:	1001
 NStgid:	21133
 NSpid:	21133
 NSpgid:	21128
 NSsid:	20986
 VmPeak:	352422552 kB
 VmSize:	15532628 kB
 VmLck:	       0 kB
 VmPin:	       0 kB
 VmHWM:	15388364 kB
 VmRSS:	14713196 kB
 VmData:	15453576 kB
 VmStk:	     232 kB
 VmExe:	   40676 kB
 VmLib:	    7640 kB
 VmPTE:	   28940 kB
 VmPMD:	      72 kB
 VmSwap:	       0 kB
 HugetlbPages:	       0 kB
 Threads:	2
 SigQ:	0/63121
 SigPnd:	0000000000000000
 ShdPnd:	0000000000000000
 SigBlk:	0000000000000000
 SigIgn:	0000000000000004
 SigCgt:	0000000180007000
 CapInh:	0000000000000000
 CapPrm:	0000000000000000
 CapEff:	0000000000000000
 CapBnd:	0000003fffffffff
 CapAmb:	0000000000000000
 Seccomp:	0
 Speculation_Store_Bypass:	vulnerable
 Cpus_allowed:	3
 Cpus_allowed_list:	0-1
 Mems_allowed:	00000000,00000001
 Mems_allowed_list:	0
 voluntary_ctxt_switches:	59629413
 nonvoluntary_ctxt_switches:	1066644
Signal: 11
Uname: Linux 4.4.0-1075-aws x86_64
UserGroups:
_LogindSession: 632 `

**Comment by spoonincode** [comment]
Unfortunately we need a little more data to investigate a crash -- ideally you would get a coredump on a crash and be able to open this coredump in gdb/lldb and get a backtrace of where the crash occurred. Have you seen this problem any more since your original report?

**Comment by spoonincode** [comment]
No response, closing
