### ISSUE TITLE
Error: boost: "cxx11" is not a recognized standard

### ISSUE THREAD

**Issue by Marcos2015** [EOSIO/eos#6760]
eos git:(master) ✗ ./eosio_build.sh

	Beginning build version: 1.2
	2019年 2月17日 星期日 23时06分11秒 UTC
	User: zhaofeng
	git head id: 1a14e9cd635410af29415c61be3a14d9764cf133
	Current branch: master

	ARCHITECTURE: Darwin

	OS name: Darwin
	OS Version: 10.14.3
	CPU speed: 2.30Ghz
	CPU cores: 4
	Physical Memory: 16 Gbytes
	Disk install: /dev/disk1s1
	Disk space total: 465G
	Disk space available: 213G

	Checking xcode-select installation
	xcode-select installation found @
	/usr/bin/xcode-select

	Checking Ruby installation.
	Ruby installation found @
	/usr/local/bin/ruby

	Checking Home Brew installation
	Home Brew installation found @
	/usr/local/bin/brew

	Checking dependencies.
	Checking automake ... 		 automake found
	Checking Libtool ... 		 Libtool found
	Checking OpenSSL ... 		 OpenSSL found
	Checking llvm ... 		 llvm found
	Checking wget ... 		 wget found
	Checking CMake ... 		 CMake found
	Checking GMP ... 		 GMP found
	Checking gettext ... 		 gettext found
	Checking MongoDB ... 		 MongoDB found
	Checking Doxygen ... 		 Doxygen found
	Checking Graphviz ... 		 Graphviz found
	Checking LCOV ... 		 LCOV found
	Checking Python3 ... 		 Python3 found

	No required Home Brew dependencies to install.

	Checking boost library installation.
	Installing boost libraries.
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).

######################################################################## 100.0%
Error: boost: "cxx11" is not a recognized standard
	Unable to install boost 1.67 libraries at this time. 0
	Exiting now.

**Comment by spoonincode** [comment]
fixed via #6721 
will be in next release
