### ISSUE TITLE
what exactly size of  maximum configurable  RAM and account store state?

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#6761]
refer to 6571,what exactly size of  maximum configurable  RAM does dual EPYC machines? I am  not very familiar with that.what  exactly size of  an account store state info.

**Comment by jgiszczak** [comment]
The maximum configurable RAM of dual EPYC machines is 4 TiB.  See previous responses for minimum account size.

If you still have questions and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
