### ISSUE TITLE
keosd and nodeos can not start up after updating from 1.5.0 to 1.6.1 under ubuntu 18.04

### ISSUE THREAD

**Issue by gyl19930522** [EOSIO/eos#6764]
As following, after I updating  eos from 1.5.0 to 1.6.1, cleos and keosd could not operate on. I have checked all the config.ini but can not find "max-implicit-request" to delete. Furthermore, chain_api_plugin has been added in config.ini in "eosio-wallet" while still gives an error. Thanks!

gyl@lone:~$ nodeos
<3>error 2019-02-18T12:23:51.259 thread-0  main.cpp:135                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option 'max-implicit-request'

gyl@lone:~$ keosd
<3>error 2019-02-18T12:24:10.974 thread-0  main.cpp:58                   main                 ] /home/gyl/eos/libraries/appbase/application.cpp(327): Throw in function appbase::abstract_plugin &appbase::application::get_plugin(const string &) const
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: unable to find plugin: eosio::chain_api_plugin

**Comment by heifner** [comment]
Remove `max-implicit-request` from you config.ini

**Comment by gyl19930522** [comment]
> Remove `max-implicit-request` from your config.ini

but I can't find the config.ini under /local/eosio/share/

**Comment by gyl19930522** [comment]
> Remove `max-implicit-request` from your config.ini
thank you! but how to solve keosd failed on starting?

**Comment by gyl19930522** [comment]
> Remove `max-implicit-request` from your config.ini

**Comment by jgiszczak** [comment]
Remove `plugin=eosio::chain_api_plugin` from `eosio-wallet/config.ini`.  `keosd` does not support any chain plugins since it is the wallet server, not the chain server.
