### ISSUE TITLE
dirty database if taking a snapshot and kill nodeos at the same time

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#6774]
I have not 100% reproduced this issue, but it appears that if you ask nodeos to take a snapshot via http://127.0.0.1:8888/v1/producer/create_snapshot and then you kill nodeos without waiting for the snapshot process to finish, then you get the dirty database flag.

**Comment by matthewdarwin** [comment]
BTW, it helps to have really slow disk I/O to reproduce this problem.

**Comment by matthewdarwin** [comment]
And you can issue multiple http://127.0.0.1:8888/v1/producer/create_snapshot in a parallel... it seems to run them one after the other (as soon as one finishes, it runs again).

**Comment by spoonincode** [comment]
Do you think it's possible you sent SIGTERM/Ctrl-C more than once to nodeos (while you were waiting for the snapshot to complete)?

**Comment by matthewdarwin** [comment]
Perhaps... I don't have debug logging turned on in docker, so I am not sure what signals it sent and when.  I am happy to not investigate this pending solution to the double signal fix.

It takes 4 minutes to take the snapshot on this slow machine.

**Comment by gituser** [comment]
Why you've closed the issue?

>And you can issue multiple http://127.0.0.1:8888/v1/producer/create_snapshot in a parallel... it seems to run them one after the other (as soon as one finishes, it runs again).

This is a bug too and should be filled as a separate issue imo.
