### ISSUE TITLE
Error: Package: eosio-1.5.0-1.x86_64 (/eosio-1.5.0-1.el7.x86_64) Requires: mongodb-server

### ISSUE THREAD

**Issue by Marcos2015** [EOSIO/eos#6788]
[Thomas@Thomas Desktop]$ systemctl status mongod.service
● mongod.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/usr/lib/systemd/system/mongod.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-02-20 23:38:41 HKT; 6min ago
     Docs: https://docs.mongodb.org/manual
  Process: 4786 ExecStart=/usr/bin/mongod $OPTIONS (code=exited, status=0/SUCCESS)
  Process: 4780 ExecStartPre=/usr/bin/chmod 0755 /var/run/mongodb (code=exited, status=0/SUCCESS)
  Process: 4768 ExecStartPre=/usr/bin/chown mongod:mongod /var/run/mongodb (code=exited, status=0/SUCCESS)
  Process: 4762 ExecStartPre=/usr/bin/mkdir -p /var/run/mongodb (code=exited, status=0/SUCCESS)
 Main PID: 4841 (mongod)
    Tasks: 20
   CGroup: /system.slice/mongod.service
           └─4841 /usr/bin/mongod -f /etc/mongod.conf

Feb 20 23:38:38 Thomas systemd[1]: Starting High-performance, schema-free d.....
Feb 20 23:38:39 Thomas mongod[4786]: about to fork child process, waiting u...s.
Feb 20 23:38:39 Thomas mongod[4786]: forked process: 4841
Feb 20 23:38:41 Thomas systemd[1]: Started High-performance, schema-free do...e.
Hint: Some lines were ellipsized, use -l to show in full.

[Thomas@Thomas Desktop]$ sudo yum -y install eosio-1.5.0-1.el7.x86_64.rpm 
[sudo] password for Thomas: 
Loaded plugins: fastestmirror, langpacks
Examining eosio-1.5.0-1.el7.x86_64.rpm: eosio-1.5.0-1.x86_64
Marking eosio-1.5.0-1.el7.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package eosio.x86_64 0:1.5.0-1 will be installed
--> Processing Dependency: bzip2-devel for package: eosio-1.5.0-1.x86_64
Loading mirror speeds from cached hostfile
 * base: mirrors.cn99.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.163.com
--> Processing Dependency: gmp-devel for package: eosio-1.5.0-1.x86_64
--> Processing Dependency: mongodb for package: eosio-1.5.0-1.x86_64
--> Processing Dependency: mongodb-server for package: eosio-1.5.0-1.x86_64
--> Processing Dependency: openssl-devel for package: eosio-1.5.0-1.x86_64
--> Running transaction check
---> Package bzip2-devel.x86_64 0:1.0.6-13.el7 will be installed
---> Package eosio.x86_64 0:1.5.0-1 will be installed
--> Processing Dependency: mongodb for package: eosio-1.5.0-1.x86_64
--> Processing Dependency: mongodb-server for package: eosio-1.5.0-1.x86_64
---> Package gmp-devel.x86_64 1:6.0.0-15.el7 will be installed
---> Package openssl-devel.x86_64 1:1.0.2k-16.el7 will be installed
--> Processing Dependency: zlib-devel(x86-64) for package: 1:openssl-devel-1.0.2k-16.el7.x86_64
--> Processing Dependency: krb5-devel(x86-64) for package: 1:openssl-devel-1.0.2k-16.el7.x86_64
--> Running transaction check
---> Package eosio.x86_64 0:1.5.0-1 will be installed
--> Processing Dependency: mongodb for package: eosio-1.5.0-1.x86_64
--> Processing Dependency: mongodb-server for package: eosio-1.5.0-1.x86_64
---> Package krb5-devel.x86_64 0:1.15.1-37.el7_6 will be installed
--> Processing Dependency: libverto-devel for package: krb5-devel-1.15.1-37.el7_6.x86_64
--> Processing Dependency: libselinux-devel for package: krb5-devel-1.15.1-37.el7_6.x86_64
--> Processing Dependency: libcom_err-devel for package: krb5-devel-1.15.1-37.el7_6.x86_64
--> Processing Dependency: keyutils-libs-devel for package: krb5-devel-1.15.1-37.el7_6.x86_64
---> Package zlib-devel.x86_64 0:1.2.7-18.el7 will be installed
--> Running transaction check
---> Package eosio.x86_64 0:1.5.0-1 will be installed
--> Processing Dependency: mongodb for package: eosio-1.5.0-1.x86_64
--> Processing Dependency: mongodb-server for package: eosio-1.5.0-1.x86_64
---> Package keyutils-libs-devel.x86_64 0:1.5.8-3.el7 will be installed
---> Package libcom_err-devel.x86_64 0:1.42.9-13.el7 will be installed
---> Package libselinux-devel.x86_64 0:2.5-14.1.el7 will be installed
--> Processing Dependency: libsepol-devel(x86-64) >= 2.5-10 for package: libselinux-devel-2.5-14.1.el7.x86_64
--> Processing Dependency: pkgconfig(libsepol) for package: libselinux-devel-2.5-14.1.el7.x86_64
--> Processing Dependency: pkgconfig(libpcre) for package: libselinux-devel-2.5-14.1.el7.x86_64
---> Package libverto-devel.x86_64 0:0.2.5-4.el7 will be installed
--> Running transaction check
---> Package eosio.x86_64 0:1.5.0-1 will be installed
--> Processing Dependency: mongodb for package: eosio-1.5.0-1.x86_64
--> Processing Dependency: mongodb-server for package: eosio-1.5.0-1.x86_64
---> Package libsepol-devel.x86_64 0:2.5-10.el7 will be installed
---> Package pcre-devel.x86_64 0:8.32-17.el7 will be installed
--> Finished Dependency Resolution
Error: Package: eosio-1.5.0-1.x86_64 (/eosio-1.5.0-1.el7.x86_64)
           Requires: mongodb-server
Error: Package: eosio-1.5.0-1.x86_64 (/eosio-1.5.0-1.el7.x86_64)
           Requires: mongodb
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

When install eos, at CentOS 7 , I had install MongoDB and running normal, but still display not found Mongdb-server and Mongodb;how to solve this problem ?

**Comment by KrzysztofHajdamowicz** [comment]
rpm -ivh --nodeps ;)
I can say that out-of-the-box nodeos works without mongo

**Comment by Marcos2015** [comment]
> rpm -ivh --nodeps ;)
> I can say that out-of-the-box nodeos works without mongo

what is rpm -ivh --nodeps ? 

[Thomas@Thomas Desktop]$ rpm -ivh --nodeps
rpm: no packages given for install

It said no packages.

**Comment by KrzysztofHajdamowicz** [comment]
`rpm -ivh --nodeps eosio-1.5.0-1.el7.x86_64.rpm`
Just rpm states above :)

Also, looks like dependency on mongodb and mongodb-server are broken. Official mongodb community packages are named differently: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/

**Comment by Marcos2015** [comment]
> `rpm -ivh --nodeps eosio-1.5.0-1.el7.x86_64.rpm`
> Just rpm states above :)
> 
> Also, looks like dependency on mongodb and mongodb-server are broken. Official mongodb community packages are named differently: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/

I  had done about you given advice for Mongodb,but still happened the same problem.

**Comment by KrzysztofHajdamowicz** [comment]
> > `rpm -ivh --nodeps eosio-1.5.0-1.el7.x86_64.rpm`
> > Just rpm states above :)
> > Also, looks like dependency on mongodb and mongodb-server are broken. Official mongodb community packages are named differently: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/
> 
> I had done about you given advice for Mongodb,but still happened the same problem.

Can you provide any logs?

**Comment by Marcos2015** [comment]
> > > `rpm -ivh --nodeps eosio-1.5.0-1.el7.x86_64.rpm`
> > > Just rpm states above :)
> > > Also, looks like dependency on mongodb and mongodb-server are broken. Official mongodb community packages are named differently: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/
> > 
> > 
> > I had done about you given advice for Mongodb,but still happened the same problem.
> 
> Can you provide any logs?

➜  Desktop sudo yum -y install eosio-1.6.2-1.el7.x86_64.rpm
Loaded plugins: fastestmirror, langpacks
Examining eosio-1.6.2-1.el7.x86_64.rpm: eosio-1.6.2-1.x86_64
Marking eosio-1.6.2-1.el7.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package eosio.x86_64 0:1.6.2-1 will be installed
--> Processing Dependency: bzip2-devel for package: eosio-1.6.2-1.x86_64
Loading mirror speeds from cached hostfile
 * base: mirrors.shu.edu.cn
 * extras: mirrors.163.com
 * updates: mirrors.shu.edu.cn
--> Processing Dependency: gmp-devel for package: eosio-1.6.2-1.x86_64
--> Processing Dependency: libstdc++-devel for package: eosio-1.6.2-1.x86_64
--> Processing Dependency: mongodb for package: eosio-1.6.2-1.x86_64
--> Processing Dependency: mongodb-server for package: eosio-1.6.2-1.x86_64
--> Processing Dependency: openssl-devel for package: eosio-1.6.2-1.x86_64
--> Running transaction check
---> Package bzip2-devel.x86_64 0:1.0.6-13.el7 will be installed
---> Package eosio.x86_64 0:1.6.2-1 will be installed
--> Processing Dependency: mongodb for package: eosio-1.6.2-1.x86_64
--> Processing Dependency: mongodb-server for package: eosio-1.6.2-1.x86_64
---> Package gmp-devel.x86_64 1:6.0.0-15.el7 will be installed
---> Package libstdc++-devel.x86_64 0:4.8.5-36.el7 will be installed
---> Package openssl-devel.x86_64 1:1.0.2k-16.el7 will be installed
--> Processing Dependency: zlib-devel(x86-64) for package: 1:openssl-devel-1.0.2k-16.el7.x86_64
--> Processing Dependency: krb5-devel(x86-64) for package: 1:openssl-devel-1.0.2k-16.el7.x86_64
--> Running transaction check
---> Package eosio.x86_64 0:1.6.2-1 will be installed
--> Processing Dependency: mongodb for package: eosio-1.6.2-1.x86_64
--> Processing Dependency: mongodb-server for package: eosio-1.6.2-1.x86_64
---> Package krb5-devel.x86_64 0:1.15.1-37.el7_6 will be installed
--> Processing Dependency: libverto-devel for package: krb5-devel-1.15.1-37.el7_6.x86_64
--> Processing Dependency: libselinux-devel for package: krb5-devel-1.15.1-37.el7_6.x86_64
--> Processing Dependency: libcom_err-devel for package: krb5-devel-1.15.1-37.el7_6.x86_64
--> Processing Dependency: keyutils-libs-devel for package: krb5-devel-1.15.1-37.el7_6.x86_64
---> Package zlib-devel.x86_64 0:1.2.7-18.el7 will be installed
--> Running transaction check
---> Package eosio.x86_64 0:1.6.2-1 will be installed
--> Processing Dependency: mongodb for package: eosio-1.6.2-1.x86_64
--> Processing Dependency: mongodb-server for package: eosio-1.6.2-1.x86_64
---> Package keyutils-libs-devel.x86_64 0:1.5.8-3.el7 will be installed
---> Package libcom_err-devel.x86_64 0:1.42.9-13.el7 will be installed
---> Package libselinux-devel.x86_64 0:2.5-14.1.el7 will be installed
--> Processing Dependency: libsepol-devel(x86-64) >= 2.5-10 for package: libselinux-devel-2.5-14.1.el7.x86_64
--> Processing Dependency: pkgconfig(libsepol) for package: libselinux-devel-2.5-14.1.el7.x86_64
--> Processing Dependency: pkgconfig(libpcre) for package: libselinux-devel-2.5-14.1.el7.x86_64
---> Package libverto-devel.x86_64 0:0.2.5-4.el7 will be installed
--> Running transaction check
---> Package eosio.x86_64 0:1.6.2-1 will be installed
--> Processing Dependency: mongodb for package: eosio-1.6.2-1.x86_64
--> Processing Dependency: mongodb-server for package: eosio-1.6.2-1.x86_64
---> Package libsepol-devel.x86_64 0:2.5-10.el7 will be installed
---> Package pcre-devel.x86_64 0:8.32-17.el7 will be installed
--> Finished Dependency Resolution
Error: Package: eosio-1.6.2-1.x86_64 (/eosio-1.6.2-1.el7.x86_64)
           Requires: mongodb
Error: Package: eosio-1.6.2-1.x86_64 (/eosio-1.6.2-1.el7.x86_64)
           Requires: mongodb-server
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
➜  Desktop

**Comment by KrzysztofHajdamowicz** [comment]
You did not run things like said above.
Try to run: `rpm -ivh eosio-1.6.2-1.el7.x86_64.rpm --nodeps`

**Comment by jgiszczak** [comment]
The 1.70 Release Candidate has had the mongodb requirement removed from at least some of the RPMs.  You might try that.

**Comment by spoonincode** [comment]
Yep this is fixed in 1.7.0, so closing
