### ISSUE TITLE
STAT-161 ⁃ Skeleton abi has old action member variable

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#679]
The "action" member variable should now be called "action_name"

**Comment by heifner** [comment]
Resolved by #678

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

Did the following steps:

MacBook01:test pravin$ git branch
* (HEAD detached at STAT-2017-11-14)
  blk_ts
  block_timestamp
  build_script
  masterMacBook01:build pravin$ make installMacBook01:contracts pravin$ eoscpp -n test
created test from skeletonI don't see action_name?

    /// The apply method implements the dispatch of events to this contract
    void apply( uint64_t code, uint64_t action ) {
       eosio::print( "Hello World: ", eosio::name(code), "->", eosio::name(action), "\n" );
    }

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

Take a look at skeleton.abi 

  "actions": [{
      "action": "transfer",
      "type": "transfer"
    }
  ],has changed into

  "actions": [{
      "action_name": "transfer",
      "type": "transfer"
    }
  ],That's the change needed for this STAT-161
