### ISSUE TITLE
I am  getting  no output  when trying to create account by command line

### ISSUE THREAD

**Issue by ambrish-dev** [EOSIO/eos#6795]
I am  getting  no output  when trying to create account by command line .
./cleos create account -j eosio tester EOS4toFS3YXEQCkuuw1aqDLrtHim86Gz9u3hBdcBw5KNPZcursVHq EOS7d9A3uLe6As66jzN8j44TXJUqJSK3bFjjEEqR4oTvNAB3iM9SA.

Please help

**Comment by heifner** [comment]
Does `./cleos get info` generate any output?

**Comment by ambrish-dev** [comment]
> 
> 
> Does `./cleos get info` generate any output?

yes

**Comment by ambrish-dev** [comment]
When I try to publish contract  by using below command . it is just showing "publishing contract...".
./cleos set contract eosio ../contracts/eosio.bios/ -p eosio@active

**Comment by heifner** [comment]
What is your environment? bash? linux version? compiled yourself? version of cleos? version of nodeos?

**Comment by jgiszczak** [comment]
What are the results of two consecutive invocations of `./cleos get info`?

**Comment by spoonincode** [comment]
No response in over 50 days, closing
