### ISSUE TITLE
centos 7 mainnet fullnode disk read overload

### ISSUE THREAD

**Issue by colinlabs** [EOSIO/eos#6796]
```
OS: CentOS 7
kerner: 3.10.0-693.2.2.el7.x86_64
eos version: v1.6.0
DISK IOPS: 20000+
```

![image](https://user-images.githubusercontent.com/10361796/53146066-ca531d80-35dd-11e9-8357-d8864b6255b9.png)

**Comment by spoonincode** [comment]
That much read overhead typically means you're short on physical RAM. How much do you have?

**Comment by jgiszczak** [comment]
It may mean sync is not yet complete as well.  Check your LIB height with `cleos get info` and compare to one of the mainnet nodes.

**Comment by colinlabs** [comment]
solved with [stackexchange](https://eosio.stackexchange.com/questions/3981/centos-7-mainnet-fullnode-disk-read-overload/4008#4008)

**Comment by gituser** [comment]
I had similar issue.
The issue here is:
If you did specify `chain-state-db-size-mb` lower than the actual state size (e.g. `chain-state-db-size-mb =1024) (e.g. right now state is 4.6Gb), so the state doesn't fit in the memory, nodeos will be continually reading from disk and be very very slow.

This is definitely needs fixing.

**Comment by spoonincode** [comment]
>If you did specify chain-state-db-size-mb lower than the actual state size (e.g. `chain-state-db-size-mb =1024) (e.g. right now state is 4.6Gb), so the state doesn't fit in the memory, nodeos will be continually reading from disk and be very very slow.

That's not how it works: if `chain-state-db-size-mb` is set less than the needed size nodeos will exit. Be aware that `chain-state-db-size-mb` is unable to shrink the database -- if you launch nodeos `chain-state-db-size-mb = 4096` once, and then launch it `chain-state-db-size-mb = 1024`, the state DB will continue to be 4GB

**Comment by gituser** [comment]
@spoonincode well you can try it yourself if you don't believe me.

It's very easy to reproduce.

**Comment by spoonincode** [comment]
>well you can try it yourself if you don't believe me.

it's impossible to load a snapshot or replay or sync to "mainnet" with `chain-state-db-size-mb =1024` because nodeos will exit once DB memory approaches 1024-128=896MB
