### ISSUE TITLE
contract how to deal action？When two action was built in one block

### ISSUE THREAD

**Issue by boy-good** [EOSIO/eos#6810]
My contract action was called twice, just packed in the same block. At this time, the contract database appears to use a self-increasing id but not the same transaction hash, even the last hash in the two transactions?

![image](https://user-images.githubusercontent.com/39320533/53215507-eca37480-368b-11e9-8ecc-40b5e2f30930.png)

The auto-increment id of this transaction is “14767”, but the transaction hash corresponding to this id when my server pulls the contract data is “3a038ebfd11e110a86225ddb389ff438c9f099a03927f06dd20c59230bdf396d”, and the hash of this id becomes “32c7e68bde38ad4dfb91daaf5b3fba5f472ae65e484e9b7588e1e42becec2c30” when the contract is requested again.

This happens in the **Jungle** network.The transactions like:
https://jungle.eosq.app/block/00e6072c48636064462f030a53126e90f64973103b8444b9681be7c311a9ec5c

**Comment by jgiszczak** [comment]
The id of a transaction is the hash of the transaction data.  Naturally two different transactions with different participating accounts will have different hashes, and hence different ids.  This is true regardless of the ordering of the transactions and regardless of the blocks in which the transactions are included.

To prevent inadvertent duplicates, transactions are required to be unique.  Two transactions with the same amounts, participants, and memos are required to have different expirations or reference blocks to ensure uniqueness and hopefully intent.
