### ISSUE TITLE
How to filter  transactions data for one special account with mongodb_filter_plugin ?

### ISSUE THREAD

**Issue by FrankWong1213** [EOSIO/eos#6811]
I want to save the transactions to mongodb  which their transfer target is one special account, but found no way.Help!

**Comment by jgiszczak** [comment]
`mongo_db_plugin` supports a `mongodb-filter-on = ` setting, which is the same format as history plugin's filter-on setting.  To filter to one account, use `mongodb-filter-on = youraccount::`.  Note the two trailing colons, which indicate all actions, all actors.
