### ISSUE TITLE
account schema inconsistent for 'net_limit' attribute

### ISSUE THREAD

**Issue by fzxu** [EOSIO/eos#6820]
using the JSON API `/v1/chain/get_account` to get the account info.

e.g. for account `eosio.stake`, it looks like:

```
"net_limit": {
        "used": 289,
        "available": 13927873,
        "max": 13928162
    },
```
Please note, both `available` and `max` are numbers. But if I get the account info for `heztanrqgene`, it will return:

```
"net_limit": {
        "used": 133847,
        "available": "8344411498",
        "max": "8344545345"
    },
```

The `available` and `max` are string this time...

**Comment by jgiszczak** [comment]
This behavior is to cater to a Javascript limitation.  Javascript can not represent integers greater than 53 bits as numbers.  EOS.IO represents integers larger than 32 bits as strings as a convenient and predictable cutoff.
