### ISSUE TITLE
STAT-156 ⁃ Transaction object has non shared vector object

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#683]
Issue: When node is restarted without clearing state then in certain circumstances it crashes because it tries to access an invalid pointer from previous session from the shared memory segment.

Analysis:
Refer to the class generated_transaction_object, which has:
GeneratedTransaction          trx;
Which has ProcessedGeneratedTransaction.
The ProcessedGeneratedTransaction class has;
 vector<MessageOutput> output;

Since generated_transaction_object is supposed to be in shared memory, maintaining a vector as part of this data structure is error prone as it is pointing to the heap memory which is out of scope of shared memory. Restarting the node can cause unexpected behavior.

As a quick solution, GeneratedTransaction will be removed from all the references and wont be supported in STAT release.

Long term solution is, to change the vector into shared_vector and ensure that entire hierachy of GeneratedTransaction has no reference to non-shared-memory references.

ATC

The testing described in STAT-153 should be sufficient for this issue.

Note: The solution of removing GeneratedTransactions was achieved by effectively disabling the transaction_send() function in the C API (transaction::send() in C++). Calling either of these from a contract will now result in an assert exception. Because the proxy contract uses this API, its use will also result in these exceptions.

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

Did the following:
1. Did a few currency transactions
2. Restarted node1 eosd without resync options
3. Made a transfer from node 2 and checked the balance from node 1
The balances are different
eosd logs in node 1:
2856001ms thread-0 chain_controller.cpp:208 pushblock ] inita #37619 @2017-11-24T03:47:36 | 0 trx, 0 pending, exectime_ms=0
2856002ms thread-0 producer_plugin.cpp:244 block_production_loo ] inita generated block #37619 @ 2017-11-24T03:47:36 with 0 trxs 0 pending
2856003ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37994
2856004ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37994
2856004ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37994
2856005ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37994
2856994ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37995
2856995ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37995
2857993ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37996
2857993ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37996
2857993ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37996
2857993ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37996
2858995ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37997
2858995ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37997
2858996ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37997
2860000ms thread-0 net_plugin.cpp:1723 handle_message ] got a block while syncing but no sync_receiving set #37998
Proof of failure:
bash-3.2$ check_p2p
transfer 10k inita->initb from 10.160.13.241
transfer completed
10.160.13.241
participation rate 0.96875000000000000
inita balance 999995.9750
initb balance 1000004.0250
10.160.11.221
participation rate 0.04687500000000000
inita balance 999997.9800
initb balance 1000002.0200
Fail

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Kevin - Can you review this?  Is it actually in progress or corrected by another fix?

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

This has been fixed. But really can't be QA'ed until Paul fixes STAT-188.

**Comment by heifner** [comment]
Verified fixed by QA.
