### ISSUE TITLE
EOS Token Swap- Can I still make it?

### ISSUE THREAD

**Issue by orielpe** [EOSIO/eos#6838]
Hi,
Sorry if this super irrelevant topic here.
I found out I still have some ERC20 EOS tokens in my wallet.
Can I still make the swap or it is basically gone?

Thanks

**Comment by jgiszczak** [comment]
If you registered, you can easily claim your EOS tokens on any network using a proper snapshot at the time of the end of the token sale.  If you didn't register, you can still generate an EOS key using a transaction signed with your Ethereum key.  The various networks provide instructions which you can find via search.  For the current mainnet, I suggest EOS Authority and their fallback mechanism.
