### ISSUE TITLE
Can't get the internal state of function after the function run?

### ISSUE THREAD

**Issue by flyq** [EOSIO/eos#6849]
all the function in contract is `void` function, but I have some problem:    

This is some code in a function. I want to get the `_id` after the function run. any suggestion? thx
```Cpp
    auto _id = _shares.available_primary_key();
    _shares.emplace(_self, [&](auto &s) {
        s.id = _id;
        s.reader = from;
        s.quota = in.amount * sign->fission_factor / 1000;
    });
```

if I get the json of  `shares`'s table and find the max id immediately after someone run the function, it will get wrong id if many people run the function at one time.

**Comment by jgiszczak** [comment]
To get the data you need, you would need to include some sort of externally generated transaction ID that you provide, which you can later correlate with chain data.  Order of execution of transactions is unknown to you, even if it is deterministic internally, and your transaction may not ever execute at all.  It may expire before it's incorporated into a block.  You don't know at the time you submit it.

So if you need to track state changes within your contract to specific transactions, and the system generated transaction ID is insufficient for your purposes, you must provide tracking data yourself.  That tracking data is available in the transaction receipt, which you can read from the output of the various state tracking plugins.  If your transaction is executed and incorporated into a block, a transaction receipt will be available to confirm it.  Ordinarily you only need to track the system generated transaction ID which is in the response of push transaction.
