### ISSUE TITLE
STAT-158 ⁃ The node crashes when run the test script

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#686]
When executes the script eosd_run_test.sh, the eosd crashes.
The script is attached herewith
 [^eosd_run_test.sh] 

ATC:

* Run attached script. eosd does not crash.

┆Attachments: <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10011&#x2F;eosd_run_test.sh">eosd_run_test.sh</a>

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

Integrated the attached script with the one it was based on in tests.

Now tests/eosd_run_test.sh takes arguments. If given localhost for --host then it will use the launcher to launch an eosd for the test, otherwise it will skip that step.

usage: eosd_run_test.sh --host=host_name --port=port --output=test_output_0.txt
  If --host==localhost then this script also launches an eosd for the test.
  Example: eosd_run_test_sh --host=localhost --port=8888 --output=test_output_0.txt

**Comment by brianjohnson5972** [comment]
Does it have defaults, so I can just call  tests/eosd_run_test.sh and it
still run?

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

The script echos usage if no arguments are specified.

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

Pravin Bezwada, [Nov 15, 2017 at 9:28:28 AM]:
./tests/eosd_run_test.sh --host=10.160.11.161 --port=8889 --output /tmp/test1.log

throws following error:

658346ms thread-0   main.cpp:1117                 main                 ] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"unknown key"}

{"c":500,"msg":"{\"code\":500,\"message\":\"Internal Service Error\",\"details\":\"unknown key\"}"}
    thread-0  httpc.cpp:113 call

{"server":"10.160.11.161","port":8889,"path":"/v1/chain/get_required_keys","postdata":{"transaction":{"ref_block_num":11228,"ref_block_prefix":627052842,"expiration":"2017-11-15T14:28:06","scope":["currency","testera"],"read_scope":[],"messages":[{"code":"eos","type":"transfer","authorization":[{"account":"testera","permission":"active"}],"data":"000000c05c95b1ca0000001e4d75af46cfe10e00000000001274657374207472616e7366657220612d3e62"}],"signatures":[]},"available_keys":["EOS59C8WeGcyVep3YD5HNbtLs2pD6wkYSLvd1jRwLQRBtVvsUg1B2","EOS6LVvnuGn36BjUK7YM1WSm4Mi4mAY5mpURnYwCkVMXW83QUUhFe","EOS79GhUyhLzNDEf3KteRAJBbfKKtMndZsY3pBuRuG3sTQowKdQMs"]}}
    thread-0  httpc.cpp:117 call
FAILURE - eosc transfer returned error code 1

I am on:

MacBook01:build pravin$ git branch

  * (HEAD detached at STAT-2017-11-14)
blk_ts
block_timestamp
build_script
master

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

Pravin Bezwada, [Nov 15, 2017 at 9:28:28 AM]:
./tests/eosd_run_test.sh --host=10.160.11.161 --port=8889 --output /tmp/test1.log

throws following error:

658346ms thread-0   main.cpp:1117                 main                 ] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"unknown key"}

{"c":500,"msg":"{\"code\":500,\"message\":\"Internal Service Error\",\"details\":\"unknown key\"}"}
    thread-0  httpc.cpp:113 call

{"server":"10.160.11.161","port":8889,"path":"/v1/chain/get_required_keys","postdata":{"transaction":{"ref_block_num":11228,"ref_block_prefix":627052842,"expiration":"2017-11-15T14:28:06","scope":["currency","testera"],"read_scope":[],"messages":[{"code":"eos","type":"transfer","authorization":[{"account":"testera","permission":"active"}],"data":"000000c05c95b1ca0000001e4d75af46cfe10e00000000001274657374207472616e7366657220612d3e62"}],"signatures":[]},"available_keys":["EOS59C8WeGcyVep3YD5HNbtLs2pD6wkYSLvd1jRwLQRBtVvsUg1B2","EOS6LVvnuGn36BjUK7YM1WSm4Mi4mAY5mpURnYwCkVMXW83QUUhFe","EOS79GhUyhLzNDEf3KteRAJBbfKKtMndZsY3pBuRuG3sTQowKdQMs"]}}
    thread-0  httpc.cpp:117 call
FAILURE - eosc transfer returned error code 1

I am on:

MacBook01:build pravin$ git branch

  * (HEAD detached at STAT-2017-11-14)
blk_ts
block_timestamp
build_script
master

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

This is a config issue. Things work when the configuration is in the right conditions.
