### ISSUE TITLE
ExtrasError while creating currency in docker eos

### ISSUE THREAD

**Issue by vgagaleski** [EOSIO/eos#6861]
I am trying to create a currency with the following command:
>docker exec -it nodeos /opt/eosio/bin/cleos --url http://127.0.0.1:8888 --wallet-url http://172.18.0.3:9876 push action eosio.token create '[ "eosio", "1000000000.0000 TOK"]' -p eosio.token

and I always get this error:

ERROR: ExtrasError: [eosio, 1000000000.0000 TOK]']
Push a transaction with a single action
Usage: /opt/eosio/bin/cleos push action [OPTIONS] account action data

Positionals:
  account TEXT                The account providing the contract to execute (required)
  action TEXT                 A JSON string or filename defining the action to execute on the contract (required)
  data TEXT                   The arguments to the contract (required)

Options:
  -h,--help                   Print this help message and exit
  -x,--expiration             set the time in seconds before a transaction expires, defaults to 30s
  -f,--force-unique           force the transaction to be unique. this will consume extra bandwidth and remove any protections against accidently issuing the same transaction multiple times
  -s,--skip-sign              Specify if unlocked wallet keys should be used to sign transaction
  -j,--json                   print result as json
  -d,--dont-broadcast         don't broadcast transaction to the network (just print to stdout)
  --return-packed             used in conjunction with --dont-broadcast to get the packed transaction
  -r,--ref-block TEXT         set the reference block num or block id used for TAPOS (Transaction as Proof-of-Stake)
  -p,--permission TEXT ...    An account and permission level to authorize, as in 'account@permission'
  --max-cpu-usage-ms UINT     set an upper limit on the milliseconds of cpu usage budget, for the execution of the transaction (defaults to 0 which means no limit)
  --max-net-usage UINT        set an upper limit on the net usage budget, in bytes, for the transaction (defaults to 0 which means no limit)
  --delay-sec UINT            set the delay_sec seconds, defaults to 0s

I tried different approaches but I am not getting what is the core problem.

Before executing push action the set was executed succesfully
>docker exec -it nodeos /opt/eosio/bin/cleos --url http://127.0.0.1:8888 --wallet-url http://172.18.0.3:9876 set contract eosio.token contracts/eosio.token -p eosio.token
Reading WASM from /opt/eosio/contracts/eosio.token/eosio.token.wasm...
Publishing contract...
executed transaction: 031b9256a0ac4436b6a600e69bb6f29b9babf011abaa99e46c33d1caab4b97d3  8104 bytes  811 us
         eosio <= eosio::setcode               {"account":"eosio.token","vmtype":0,"vmversion":0,"code":"0061736d01000000017e1560037f7e7f0060057f7e...
         eosio <= eosio::setabi                {"account":"eosio.token","abi":"0e656f73696f3a3a6162692f312e30010c6163636f756e745f6e616d65046e616d65...
warning: transaction executed locally, but may not be confirmed by the network yet  

>docker exec -it nodeos /opt/eosio/bin/cleos --url http://127.0.0.1:8888 --wallet-url http://172.18.0.3:9876 version client
Build version: 3186ddba

Also: 
>docker exec -it nodeos /opt/eosio/bin/cleos --url http://127.0.0.1:8888 --wallet-url http://172.18.0.3:9876 get table eosio.token eosio.token accounts
{
  "rows": [],
  "more": false
}

**Comment by andriantolie** [comment]
@vgagaleski I can't reproduce your issue with the command that mentioned above. From the error message, seems to me it's a syntax error. The above syntax error could happen if you typed `[ '"eosio", "1000000000.0000 TOK"]'` instead of `'[ "eosio", "1000000000.0000 TOK"]'`

**Comment by vgagaleski** [comment]
Well I am using the same command as the one written above and the first thing that I checked was the syntax because the error string ExtrasError: [eosio, 1000000000.0000 TOK]'] <- looks very strange, maybe there is some wrong parsing ? If you ask me, the error string should end only with ], not with ]']. I am new with EOS and don't know how to debug further... any suggestions?

**Comment by andriantolie** [comment]
Did you type the whole command (`docker exec -it nodeos /opt/eosio/bin/cleos --url http://127.0.0.1:8888 --wallet-url http://172.18.0.3:9876 push action eosio.token create '[ "eosio", "1000000000.0000 TOK"]' -p eosio.token`) directly in the command line?

Or do you actually pass some part of it to other function? For example, if actually `docker exec -it nodeos /opt/eosio/bin/cleos --url http://127.0.0.1:8888 --wallet-url http://172.18.0.3:9876 $@` is a bash script? 

The fact that it complains [eosio, 1000000000.0000 TOK]'] means that your `'[` and `"eosio", "1000000000.0000 TOK"]'` is treated as separate parameter

**Comment by andriantolie** [comment]
> ExtrasError: [eosio, 1000000000.0000 TOK]'] <- looks very strange, maybe there is some wrong parsing ? If you ask me, the error string should end only with ]?

Btw, regarding this, you can ignore the outer square bracket, it actually just complains about `eosio, 1000000000.0000 TOK]'`

**Comment by vgagaleski** [comment]
I am using the whole command directly in the command line on Windows 10, I wasn't able to assign alias as written in the tutorial.

**Comment by andriantolie** [comment]
I see. It might be the behavior of Windows terminal. since I don't encounter this problem on my Mac terminal. The problem seems to me that the arguments are treated separately. Since spaces are not important inside the single quote there, how about if you just remove the space? i.e. `'["eosio", "1000000000.0000 TOK"]'` instead of '[ "eosio", "1000000000.0000 TOK"]'

If it still doesn't work, you might want to try -c mentioned in https://docs.docker.com/engine/reference/commandline/exec/

**Comment by vgagaleski** [comment]
`docker exec -it nodeos /opt/eosio/bin/cleos --url http://127.0.0.1:8888 --wallet-url http://172.18.0.3:9876 push action eosio.token create '["eosio", "1000000000.0000 TOK"]' -p eosio.token` 
*without space, results in: 

ERROR: ExtrasError: [1000000000.0000 TOK]']
Push a transaction with a single action
Usage: /opt/eosio/bin/cleos push action [OPTIONS] account action data

Positionals:
  account TEXT                The account providing the contract to execute (required)
  action TEXT                 A JSON string or filename defining the action to execute on the contract (required)
  data TEXT                   The arguments to the contract (required)

Options:
  -h,--help                   Print this help message and exit
  -x,--expiration             set the time in seconds before a transaction expires, defaults to 30s
  -f,--force-unique           force the transaction to be unique. this will consume extra bandwidth and remove any protections against accidently issuing the same transaction multiple times
  -s,--skip-sign              Specify if unlocked wallet keys should be used to sign transaction
  -j,--json                   print result as json
  -d,--dont-broadcast         don't broadcast transaction to the network (just print to stdout)
  --return-packed             used in conjunction with --dont-broadcast to get the packed transaction
  -r,--ref-block TEXT         set the reference block num or block id used for TAPOS (Transaction as Proof-of-Stake)
  -p,--permission TEXT ...    An account and permission level to authorize, as in 'account@permission'
  --max-cpu-usage-ms UINT     set an upper limit on the milliseconds of cpu usage budget, for the execution of the transaction (defaults to 0 which means no limit)
  --max-net-usage UINT        set an upper limit on the net usage budget, in bytes, for the transaction (defaults to 0 which means no limit)
  --delay-sec UINT            set the delay_sec seconds, defaults to 0s

I tried different combinations with the -c but it is not helping, should I start all over again ?

**Comment by jgiszczak** [comment]
Windows is unsupported.

See [How Command Line Parameters Are Parsed](http://daviddeley.com/autohotkey/parameters/parameters.htm) and [A Better Way To Understand Quoting and Escaping of Windows Command Line Arguments](http://www.windowsinspired.com/understanding-the-command-line-string-and-arguments-received-by-a-windows-program/) and bear in mind that all of this advice is dependent on how the docker executable parses the command line it receives from the shell.

Odds are you will need to replace the outer single quotes with double quotes and escape the interior quotes, but I haven't tested it.

**Comment by danielleiszen** [comment]
If anyone else faces the same problem. On Windows Powershell the following command works.

`cleos push action eosio.token create '[ \"eosio\",\"1000000000.000 EOS\" ]' -p eosio.token`

So the single quotes remain and the double quotes should be escaped
