### ISSUE TITLE
why should we set the max peers of one node to 25?

### ISSUE THREAD

**Issue by qiushui777** [EOSIO/eos#6866]
Hi, everyone.
I read the source code and realized that eos set the max peers that one node can connect is 25. Why should we set this value? Do we really need this limit? Because if one attacker wants to connect as many as connections to one node and send lots of garbage traffic, he needs to consume his resource as well. So can anyone explain why should we set this limit here?

**Comment by jgiszczak** [comment]
Because one attacker may have access to many machines, including machines not actually owned by the attacker.  DDoS botnets exist and require multiple layers of mitigation for high value targets.  A configurable connection limit within the software is one of those layers.
