### ISSUE TITLE
unnecessary checks on cleos system newaccount ?

### ISSUE THREAD

**Issue by gaboesquivel** [EOSIO/eos#6873]
Hi

Today stumbled upon this problem:

On an private chain with no resource market. 

`cleos system newaccount` keeps throwing at me `ERROR: One of --buy-ram, --buy-ram-kbytes or --buy-ram-bytes should have non-zero value` on Build version: d4ffb4eb.

on the other hand EOSJS 20 beta 3 works nicely for

```
 actions: [{
    account: 'eosio',
    name: 'newaccount',
    authorization: [{
      actor: 'myoldaccount',
      permission: 'active',
    }],
    data: {
      creator: 'myoldaccount',
      name: 'mynewaccount',
      owner: {
        threshold: 1,
        keys: [{
          key: 'PUB_R1_6FPFZqw5ahYrR9jD96yDbbDNTdKtNqRbze6oTDLntrsANgQKZu',
          weight: 1
        }],
        accounts: [],
        waits: []
      },
      active: {
        threshold: 1,
        keys: [{
          key: 'PUB_R1_6FPFZqw5ahYrR9jD96yDbbDNTdKtNqRbze6oTDLntrsANgQKZu',
          weight: 1
        }],
        accounts: [],
        waits: []
      },
    },
  }]
```

**Comment by arhag** [comment]
> On an private chain with no resource market.

In that case use `cleos create account` rather than `cleos system newaccount`.

**Comment by yashbhavsar007** [comment]
Have you deployed system contracts and other contracts on your private network as per https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence ?

**Comment by gaboesquivel** [comment]
Thank, I'm aware of `cleos create account` and the boot sequence. 

It just seems to me very counterintuitive to me to have `cleos system newaccount` requiring those flags.

**Comment by gaboesquivel** [comment]
What I was suggesting is that perhaps the `simple` flag could be explicit. 
https://github.com/EOSIO/eos/blob/master/programs/cleos/main.cpp#L993

Now I'm realizing that `cleos system` has a very specific scope.

<img width="828" alt="create_account" src="https://user-images.githubusercontent.com/391270/53884633-adf1b080-3fe1-11e9-943f-a5f01221be4b.png">
