### ISSUE TITLE
Faked transactions in block.

### ISSUE THREAD

**Issue by wilkey10** [EOSIO/eos#6874]
If the transactions in block are faked or captured maliciously, it cannot be noticed until verify the mkroot in header after _apply_block_ . That is right?

**Comment by jgiszczak** [comment]
Bad transactions are detected during `apply_block`.  Each [call](https://github.com/EOSIO/eos/blob/c8f260783dee923ff6a33e1ba130d1a065237312/libraries/chain/controller.cpp#L1215) to `push_transaction()` validates authorizations and other starting conditions and determines if a transaction should succeed or fail.  A bad block produced and propagated anywhere on the network will be detected and [rejected](https://github.com/EOSIO/eos/blob/c8f260783dee923ff6a33e1ba130d1a065237312/libraries/chain/controller.cpp#L1226) at that point.
