### ISSUE TITLE
v1.7.0-rc1 build failed

### ISSUE THREAD

**Issue by stev1988** [EOSIO/eos#6877]
On ubuntu16.04, I build failed in the eos/scripts direction,how to build sucess on v1.7.0-rc1?

root1@root1-Default-string:~/work/eos-v1.7.0-rc1/eos/scripts$ ./eosio_build.sh 

Beginning build version: 2.1
2019年 03月 06日 星期三 12:12:01 UTC
User: root
Current branch: HEAD

ARCHITECTURE: Linux

OS name: Ubuntu
OS Version: 16.04
CPU speed: 3393.198Mhz
CPU cores: 16
Physical Memory: 7979 Mgb
Disk install: /dev/sda2
Disk space total: 211G
Disk space available: 51G
Do you wish to update repositories with apt-get update? (y/n) y
命中:1 http://mirrors.aliyun.com/ubuntu xenial InRelease
忽略:2 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                    
命中:3 https://dl.google.com/linux/chrome/deb stable Release                                                          
忽略:5 https://repo.fdzh.org/chrome/deb stable InRelease                                     
命中:6 http://linux.teamviewer.com/deb stable InRelease                                                                
命中:7 https://repo.fdzh.org/chrome/deb stable Release                                                                                            
命中:9 http://linux.teamviewer.com/deb preview InRelease                                                                                          
忽略:10 http://www.scootersoftware.com bcompare4 InRelease                                                             
忽略:11 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0 InRelease
忽略:12 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 InRelease
命中:13 http://www.scootersoftware.com bcompare4 Release         
忽略:15 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 InRelease
忽略:16 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0 Release
获取:17 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 Release [3,457 B]
忽略:18 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 Packages
命中:19 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 Release
忽略:21 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse i386 Packages
忽略:22 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse all Packages
获取:23 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 Release.gpg [801 B]
错误:23 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 Release.gpg
  下列签名无效： KEYEXPIRED 1544811256
忽略:24 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh_CN
忽略:25 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh
忽略:26 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-en
命中:27 http://packages.microsoft.com/repos/vscode stable InRelease                
忽略:28 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 DEP-11 Metadata                                                                                                         
命中:29 http://archive.ubuntukylin.com:10006/ubuntukylin xenial InRelease                                                                                                                                  
忽略:30 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse DEP-11 64x64 Icons                                                                                                            
忽略:18 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 Packages                                                                                                                
获取:31 http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial InRelease [17.5 kB]                                                                                                                       
忽略:21 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse i386 Packages                                                                                                                 
忽略:22 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse all Packages                                                                                                                  
忽略:24 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh_CN                                                                                                             
命中:32 http://ppa.launchpad.net/samoilov-lex/aftl-stable/ubuntu xenial InRelease                                                                                                                          
忽略:25 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh                                                                                                                
命中:33 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial InRelease                                                                                                                           
忽略:26 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-en                                                                                                                
忽略:28 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 DEP-11 Metadata                                                                                                         
命中:34 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease                                                                                                                                  
忽略:30 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse DEP-11 64x64 Icons                                                                                                            
获取:35 http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial/main amd64 Packages [6,348 B]                                                                                                             
忽略:18 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 Packages                                                                                                                
忽略:21 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse i386 Packages                                                                                                                 
获取:36 http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial/main i386 Packages [6,348 B]                                                                                                              
忽略:22 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse all Packages                                                                                                                  
忽略:24 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh_CN                                                                                                             
忽略:25 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh                                                                                                                
忽略:26 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-en                                                                                                                
忽略:28 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 DEP-11 Metadata                                                                                                         
忽略:30 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse DEP-11 64x64 Icons                                                                                                            
忽略:18 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 Packages                                                                                                                
忽略:21 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse i386 Packages                                                                                                                 
忽略:22 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse all Packages                                                                                                                  
忽略:24 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh_CN                                                                                                             
忽略:25 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh                                                                                                                
忽略:26 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-en                                                                                                                
忽略:28 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 DEP-11 Metadata                                                                                                         
忽略:30 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse DEP-11 64x64 Icons                                                                                                            
忽略:18 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 Packages                                                                                                                
忽略:21 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse i386 Packages                                                                                                                 
忽略:22 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse all Packages                                                                                                                  
忽略:24 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh_CN                                                                                                             
忽略:25 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh                                                                                                                
忽略:26 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-en                                                                                                                
忽略:28 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 DEP-11 Metadata                                                                                                         
忽略:30 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse DEP-11 64x64 Icons                                                                                                            
错误:18 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 Packages                                                                                                                
  404  Not Found
忽略:21 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse i386 Packages                                                                                                                 
忽略:22 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse all Packages                                                                                                                  
忽略:24 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh_CN
忽略:25 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-zh
忽略:26 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse Translation-en
忽略:28 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse amd64 DEP-11 Metadata
忽略:30 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.0/multiverse DEP-11 64x64 Icons
忽略:37 http://mirrors.aliyun.com/ubuntu xenial-updates InRelease
忽略:38 http://mirrors.aliyun.com/ubuntu xenial-backports InRelease
忽略:39 http://mirrors.aliyun.com/ubuntu xenial-security InRelease
0% [正在等待报头]

**Comment by jgiszczak** [comment]
The build script attempts to install all required dependencies for you.  Many of these dependencies are available as packages from the platform's own repositories.  In order to build successfully, you must have access to your platform's repositories.  It looks like your build is stalling while attempting to access the Ubuntu mirror you have selected.  Select a different mirror and try again.

If your Internet access is too unreliable to retrieve dependency packages, you may open the shell scripts and read them to determine what dependencies the build requires, which you may then acquire and install some other way.  After manually installing dependencies, you may then answer `n` to the question asking to update repositories and the build will proceed.

If you still have the problem and wish to discuss it further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
