### ISSUE TITLE
STAT-162 ⁃ Create test script for existing contract

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#688]
This will be a bash script, where the following things will be done for each contract inside the contracts folder:

* Compile the contracts
* Create account for each contract
* Upload the contract
* Send message to the contract
* Get the table content and check if it is correct

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

Andrianto is going back today and won't be able to finish it by Thursday. I assigned it to myself.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Moving to finished, this was moved to closed-withdrawn by mistake.

**Comment by heifner** [comment]
Closing to match JIRA.
