### ISSUE TITLE
enhance eosio-blocklog utility

### ISSUE THREAD

**Issue by snstrand** [EOSIO/eos#6884]
Nodeos take about 90 minutes to create blocks.index from blocks.log. I have a free standing utility that can do it in about 120 seconds. Nodeos also takes about 90 minutes to truncate blocks.log at a given block number. My utility can do that in less than one second. This functionality should be added to the existing eosio-blocklog utility which currently converts blocks.log to JSON.

**Comment by gituser** [comment]
@snstrand Can you share your utility?

Thanks!

**Comment by brianjohnson5972** [comment]
These features were added to the eosio-blocklog utility.
