### ISSUE TITLE
opinion about eosio-s2wasm crashes inherited from s2wasm

### ISSUE THREAD

**Issue by HongxuChen** [EOSIO/eos#6900]
I noticed that several crashes can be reproduced in eosio-s2wasm, which comes from [binaryen/s2wasm](https://github.com/WebAssembly/binaryen/issues?utf8=%E2%9C%93&q=is%3Aissue+s2wasm+). But since binaryen is going to [deprecate s2wasm in favor of o2wasm](https://github.com/WebAssembly/binaryen/issues/1509#issuecomment-382479554), I'm wondering what EOS plan on these bugs.
Would you please explain a bit?

**Comment by jgiszczak** [comment]
Binaryen is no longer used and has been removed entirely from the 1.7.0 release candidate.

**Comment by HongxuChen** [comment]
@jgiszczak  Okay, got it. Thanks.
