### ISSUE TITLE
eosio_build.sh not working on fedora 29 because no upstream llvm4 package

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#6907]
The eosio_build.sh script wants to install `llvm4.0` and friends but those packages are not provided on fedora 29 (and probably won't be on future fedora releases). We should revert to building llvm4 manually on fedora now.

**Comment by NorseGaud** [comment]
I attempted this and I couldn't get it compiled from source either. I forwarded the internal email about it.

**Comment by spoonincode** [comment]
I haven't tried but we probably need at least these two patches:
https://aur.archlinux.org/cgit/aur.git/plain/PR37486-Fix-lli-fails-to-build-with-gcc-8.patch
https://aur.archlinux.org/cgit/aur.git/plain/D47281-Use-pre-computed-size-of-struct-ustat.patch

**Comment by spoonincode** [comment]
Closing because we're dropping Fedora support from build scripts
