### ISSUE TITLE
/v1/chain/sign_transaction  block time fast to result "message": "PARSE_ERROR",

### ISSUE THREAD

**Issue by cancerts** [EOSIO/eos#6908]
1. https://api.eosnewyork.io/v1/chain/get_info
2.https://api.eosnewyork.io/v1/chain/get_block  with the block num
3.https://api.eosnewyork.io/v1/chain/sign_transaction
4.https://api.eosnewyork.io/v1/chain/push_transaction
but the Block time is two fast ,when ii get my result ,like the 
"ref_block_num": 46739256,
  "ref_block_prefix": 2668208063,
and with the network delay 
when i go to the step push_transaction 
then the ref_block_num has changed
how solve this problem ？
等待大家的回复。

**Comment by heifner** [comment]
The ref_block_num only needs to be a recent block. What error are you getting?

**Comment by cancerts** [comment]
> The ref_block_num only needs to be a recent block. What error are you getting?

{
    "message": "PARSE_ERROR",
    "code": 400
}
when https://api.eosnewyork.io/v1/chain/sign_transaction
[{
        "ref_block_num": 46804085,
        "ref_block_prefix": 2151216492,
        "expiration": "2019-03-10T02:45:58.000",
        "actions": [{
            "account": "eosio.token",
            "name": "transfer",
            "authorization": [{
                "actor": "myacount",
                "permission": "active"
            }],
            "data": "abi_json_to_bin"
        }],
        "signatures": []
    },
    ["my eos public key"], "aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906"
]
this is my paras

**Comment by heifner** [comment]
Are you using cleos?

**Comment by cancerts** [comment]
> Are you using cleos?

no ,i use the open api  https://api.eosnewyork.io/v1/chain/sign_transaction
now i have understand my problem ,i should  http://127.0.0.1:8888/v1/chain/sign_transaction,
but i have not a local node wallet ,can any other ways to get the signatures without using the local wallet node just code

**Comment by taokayan** [comment]
I guess ref_block_num is lower 16 bit integer of the recent block number (ranged from 0 to 65535)

**Comment by quarksgluons** [comment]
@cancerts

**Comment by spoonincode** [comment]
No response to support ticket in months, closing
