### ISSUE TITLE
Replay slow down around block number 32M running against Mainnet data

### ISSUE THREAD

**Issue by nksanthosh** [EOSIO/eos#6909]
Nodeos replay with Mainnet data slows down as shown in the attached graph

1) Restart nodeos @ 32-33 million blocks:

Safely restarting nodeos while replay is between 32 & 33 million blocks seems to optimize total replay time, across all 3 tests.  Later than this means the replay stalls significantly, earlier and a second restart is needed or replay may stall prior to completion.

2) Restart nodeos after replay completes:

Post-replay sync performance (catch up with blocks generated after replay start) begins around 500-1000 blocks per minute.  A 2nd restart during this sync increases performance by a factor of about 5 (again, consistent across all 3 tests), and decreases total sync time from ~24 hours to ~4-5 hours.

**Comment by nksanthosh** [comment]
![replayissues](https://user-images.githubusercontent.com/8515898/54076280-e8747b00-4277-11e9-9fd4-2a849ecff022.png)

**Comment by wanderingbort** [comment]
@nksanthosh @dconry Please specify the configuration and hardware used to derive this graph so that future readers of this issue can properly understand.  

My assumption is that this graph looks very different with `wabt` as a web assembly back-end even if it is slower in an absolute sense.

**Comment by dconry** [comment]
@wanderingbort @nksanthosh Here are some hardware/runtime details for tests above, numbered left to right in graph:

Test 1 (aws m4.4xlarge: 8x2.5GHz CPU/64GB RAM): *--replay --wasm-runtime wavm* on nodeos 1.6.0rc2
Test 2 (aws m4.4xlarge: 8x2.5GHz/64GB): *--replay --wasm-runtime wavm --disable-replay-opts --trace-history --chain-state-history --plugin eosio::state_history_plugin* on nodeos 1.6.1
Test 3 (aws z1d.6xlarge: 12x3.4-4.0Ghz/192GB): *--replay --wasm-runtime wavm* on nodeos 1.6.1

Also, tests 1 & 2 were allowed to process slowly for several days before a nodeos restart unstalled them.  Test 3 was restarted promptly (prior to stall) in attempt to avoid stall period.  This (plus faster CPU freq) contributed to the faster completion seen in graph for Test 3.

Please let me know if further details would be useful...

**Comment by matthewdarwin** [comment]
Might be related to https://github.com/EOSIO/eos/issues/6533?

**Comment by dconry** [comment]
@taokayan We do have memory statistics for each system over these intervals.  I'll look into extracting the raw data from the monitoring system's API & representing it here.

**Comment by dconry** [comment]
Here are summary graphs of RAM usage... files are named to match the items/lines in graph above.  Nodeos process is 90%+ of the usage for all three.  I'm not sure the raw data is as useful, but it is also available upon request.

First two graphs had monitoring enabled mid-run, so the first few hours are missing.  I'm relatively certain the overall shape of the increase was consistent with the existing data.

<img width="453" alt="nohistory" src="https://user-images.githubusercontent.com/12399145/54631937-5d536c00-4a53-11e9-8d13-3aa2b42d46de.png">

<img width="457" alt="statehistory" src="https://user-images.githubusercontent.com/12399145/54631946-63494d00-4a53-11e9-82f6-318a23649382.png">

<img width="454" alt="newhardware" src="https://user-images.githubusercontent.com/12399145/54631953-66443d80-4a53-11e9-95fe-628f2d225dfe.png">

One takeaway... the slowness problem seems more intense starting around 55-60G of RAM, even on the 3rd test where the machine has (significantly) more than 64G available, and chain-state-db-size-mb was also changed to be higher (see env doc for details).

**Comment by cyberluke** [comment]
Same problem here and also here: https://eosio.stackexchange.com/questions/4149/node-cant-sync-with-the-mainnet

**Comment by spoonincode** [comment]
mostly fixed by #7047
