### ISSUE TITLE
cleos command to set an account to "immutable"

### ISSUE THREAD

**Issue by fcecin** [EOSIO/eos#6912]
It would be great if cleos had a simple command like

cleos set account permission immutable

or something like that, which would be a macro to whatever the best practice is to set an account to immutable permissions, instead of this:

https://eosio.stackexchange.com/questions/4069/how-do-i-set-my-smart-contract-account-to-immutable/4074#4074

**Comment by heifner** [comment]
I think the "best practice" is to never set a contract permissions immutable.
