### ISSUE TITLE
A transaction with 10000000000000.0000 EOS? Should be a BUG?

### ISSUE THREAD

**Issue by egops** [EOSIO/eos#6916]
We have receive a transaction with a large amount of EOS, is this a bug? can anyone figure it out ?
https://eospark.com/tx/2ce995c3bbda6ef401c89c2a4d90eda3adf27a3c9d18a76ebd170048db346169

**Comment by rahilzebpay** [comment]
https://eosflare.io/tx/2ce995c3bbda6ef401c89c2a4d90eda3adf27a3c9d18a76ebd170048db346169

**Comment by rahilzebpay** [comment]
Looks like it failed. 
But I'm looking to understand how it went through in the first place. It was irreversible first (mined in a block).

**Comment by jafri** [comment]
https://bloks.io/transaction/2ce995c3bbda6ef401c89c2a4d90eda3adf27a3c9d18a76ebd170048db346169

This link shows it correctly as a hard_fail

**Comment by taokayan** [comment]
this is a hard_failed transaction.

**Comment by heifner** [comment]
@egops 
https://developers.eos.io/eosio-nodeos/docs/how-to-monitor-state
Of the 5 transaction states only `executed` means the transaction succeeded and has run. Also note the additional information in that link:

> A transaction may be executed, but only when the block containing the transaction is irreversible can you be sure that the operation is final and complete. A block is irreversible if the block number is less than the block number of the last irreversible block (LIB). The last irreversible block (LIB) is the most recent block which has been acknowledged by 2/3 of the block producers.

I would recommend using a block explorer that shows you transaction trace results or safest yet is to run your own tracking using the state history plugin or mongo db plugin.
