### ISSUE TITLE
How to build a macos homebrew bottle like eos?

### ISSUE THREAD

**Issue by pursonchen** [EOSIO/eos#6918]
Can anyone tell me that how can I use Homebrew in MacOS to compile the forked eosio tarball from GitHub to brew bottle package? In other words how to make the bottle package by the formula and store it onto the GitHub or other VPS?

**Comment by NorseGaud** [comment]
https://docs.brew.sh/Bottles

> Bottles are created using the Brew Test Bot. This happens mostly when people submit pull requests to Homebrew and the bottle do block is updated by maintainers when they brew pull --bottle the contents of a pull request. For the Homebrew organisations’ taps they are uploaded to and downloaded from Bintray.

**Comment by pursonchen** [comment]
I removed the bottle section and set the right URL to the tar file, then I run  `brew test-bot --auto-ci my-project-name`  It came error. My formula is like below:
```
class Eos < Formula
  desc " "
  homepage " "
  url " "
  revision 0

  depends_on :arch =>  :intel
  depends_on "gettext"
  depends_on "gmp"
  depends_on :macos => :high_sierra
  depends_on "openssl"

  def install
    raise "Error, only supporting binary packages at this time"
  end
end
```
Would you please give me more advice?

**Comment by pursonchen** [comment]
Does the URL for the eosio binary file that matches the architect?

**Comment by NorseGaud** [comment]
@pursonchen, this is support better suited for homebrew. They should have any issues tracker on their GitHub.

**Comment by pursonchen** [comment]
thank you
