### ISSUE TITLE
eosio_build.sh a bit aggresive on Python homebrew dependencies check

### ISSUE THREAD

**Issue by maoueh** [EOSIO/eos#6932]
### Specs

OS: Mac OS X

#### Problem

It seems the `eosio_build.sh` is a bit aggresive on checking exact version of Python. For example, brew current version for Python3 is `3.7.2_2` while the `scripts/eosio_build_darwin_deps` file ask for `3.7.2_1`. So even after the installation, the deps check still fails.

The problem is similar for Python2 latest installed version is `2.7.16` while scripts requires `2.7.15_2` (and I had `2.7.15_1` installed before upgrade).

```
$ ls /usr/local/Cellar/python/
3.7.2_2

$ ls /usr/local/Cellar/python@2/
2.7.16
```

I temporarily removed them from the deps file to continue compilation. Not sure what is the best way to check that a given version range is installed for those however.

**Comment by NorseGaud** [comment]
@spoonincode I was able to fix this in 
https://github.com/EOSIO/eos/pull/6852
Is it possible it was reverted somehow?

**Comment by NorseGaud** [comment]
@maoueh, we'll have this fixed in the next minor release. For now, you can update the dep file to match the one in the PR I linked to in my last comment. Apologies for the inconvenience.
