### ISSUE TITLE
How can we connect the nodeos with our project?

### ISSUE THREAD

**Issue by hasnat98044** [EOSIO/eos#6937]
how can we change the host for nodeos? For example my nodeos is running on the azure server and now I want to connect it to my project. How can I do that. I have already given the default host and port that 127.0.0.1:8888. how to do this.

**Comment by jgiszczak** [comment]
You will need to change that localhost IP address to an externally routed IP address for your Azure node, assuming the process you wish to use to access it is not running on the same machine.

If you still have the problem and wish to discuss it further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
