### ISSUE TITLE
Cannot assign requested address 

### ISSUE THREAD

**Issue by hasnat98044** [EOSIO/eos#6938]
I have the changes the nodeos host and it saying that cannot assign requested address. what to do.

**Comment by jgiszczak** [comment]
You can run only one nodeos per IP/port pair on the same machine.  If a node is already running, you must either use a different port for the second node, or shut down the other node.

If you still have the problem and wish to discuss it further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
