### ISSUE TITLE
Unable to make 2nd transaction after 1st

### ISSUE THREAD

**Issue by shubham-shinde** [EOSIO/eos#6939]
Failed with error: could not insert object, most likely a uniqueness constraint was violated (13)
could not insert object, most likely a uniqueness constraint was violated: pending console output:

**Comment by jgiszczak** [comment]
If you're using cleos to submit the second transaction, you just have to wait a few seconds between submissions.  Cleos will automatically select a different block reference number, which will result in a new unique transaction.  You can not submit two identical transactions.  If you are composing your own transaction, you must change something and sign a new transaction, even if you do want the same affect to happen twice.
