### ISSUE TITLE
Docker build fails on tag v1.7.0

### ISSUE THREAD

**Issue by datudou** [EOSIO/eos#6944]
# Can't build docker image on tag v1.7.0 , the error shows in the below image
![photo_2019-03-15 12 36 40](https://user-images.githubusercontent.com/1549854/54406942-6ecd0900-471f-11e9-8402-932ecdbce2d7.jpeg)

* OS: Ubuntu 16.04
* Tag: v1.7.0 
* Docker version:  18.09.3

Think should update the Dockerfile in the eosio/Docker/builder

**Comment by lcgogo** [comment]
eos dockerhub has no update now. the latest version in docker hub is 1.6.0-rc4

**Comment by NorseGaud** [comment]
We have deprecated our support for Docker (see docker hub page) and suggest the use of our packages instead.

**Comment by datudou** [comment]
@NorseGaud Got it.

**Comment by mh-x** [comment]
@NorseGaud is there any particular reason why docker is no longer supported? It's much more convenient by using docker instead of package

**Comment by mauhcs** [comment]
I had the same problem.
Adding the following options to the Dockerfile (before the `git clone` line)solves the problem:


    RUN apt-get update -y; apt-get dist-upgrade -y
    RUN apt-get install -y apt-utils
    RUN apt-get install -y libcurl4-openssl-dev
    RUN apt-get install -y libusb-1.0-0-dev

**Comment by lanmower** [comment]
Is this intentional so that people can not easily build eosio?

**Comment by NorseGaud** [comment]
> It would be good to see continued support for a build process in the future, to promote transparency.

Improvements are being made in each release for the build and install scripts. We will continue to support those indefinitely.
