### ISSUE TITLE
how can i  create a raw transaction with my privatekey in js ?

### ISSUE THREAD

**Issue by cancerts** [EOSIO/eos#6945]
first 
==================

i need a raw signed transaction ,but i don,t want own my local node

then 
==================

i broadcast it used open api 
how should i do ?

**Comment by jgiszczak** [comment]
There are various Javascript libraries publicly available that are capable of doing local signing.  Depending on how you use it, the [eosjs](https://github.com/EOSIO/eosjs) library will sign for you automatically, simply as a side effect of composing your transaction.

If you still have questions and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
