### ISSUE TITLE
WASM serialization calls std::vector::resize(SIZE_MAX)  which always leads to crash

### ISSUE THREAD

**Issue by zhangbo-miuNEST** [EOSIO/eos#6946]
file: libraries/wasm-jit/Source/WASM/WASMSerialization.cpp
line: 384

OutputStream::capacity() always returns SIZE_MAX, so std::vector::resize(SIZE_MAX) always leads to crash. Please comment it out. Thanks.

	void serialize(OutputStream& stream,UserSection& userSection)
	{
             userSection.data.resize( sectionStream.capacity() ? sectionStream.capacity() : 1 );
	}

The latest WAVM source code has commented it out, but EOS doesn't synchronize with it.
https://github.com/EOSIO/eos/blob/master/libraries/wasm-jit/Source/WASM/WASMSerialization.cpp

**Comment by taokayan** [comment]
which version of EOS did you find to have this bug?

**Comment by zhangbo-miuNEST** [comment]
just the latest version of EOS,  master branch.

**Comment by taokayan** [comment]
Hmm.. it indeed looks like a bug

**Comment by spoonincode** [comment]
> This serialize() function is for saving compiled WASM bytecode to disk file, which is seldom used.

Is it used anywhere in EOSIO? There are a many parts of WAVM that are not used in EOSIO and at least on first glance I'm not seeing where this is used. If it is possible to encounter this crash with nodeos or cleos I would encourage you to file details at
https://hackerone.com/eosio
because it would likely be eligible for the bug bounty problem.

**Comment by zhangbo-miuNEST** [comment]
It is used by the assembly utility "eosio-wast2wasm" to save compiled WASM bytecode to file.
Mybe it's obsolete due to the standalone EOS contract sdk?

**Comment by spoonincode** [comment]
Okay that is true, I had forgot about eosio-wast2wasm since its purpose has been entirely superseded by eosio.cdt. I will see about removing this tool from future releases.

**Comment by spoonincode** [comment]
Tool removed from 1.7.1 & 1.8 thanks
