### ISSUE TITLE
cannot find -lmongo_db_plugin

### ISSUE THREAD

**Issue by TachyonRSA** [EOSIO/eos#6948]
I am trying to run `./eosio_build.sh ubuntu full` on my Ubuntu linux sub system in Windows but I keep getting the following:

> [ 96%] Built target test_control_api_plugin
> [100%] Built target unit_test
> [100%] Linking CXX executable nodeos
> /usr/bin/ld: cannot find -lmongo_db_plugin
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> programs/nodeos/CMakeFiles/nodeos.dir/build.make:190: recipe for target 'programs/nodeos/nodeos' failed
> make[2]: *** [programs/nodeos/nodeos] Error 1
> CMakeFiles/Makefile2:3528: recipe for target 'programs/nodeos/CMakeFiles/nodeos.dir/all' failed
> make[1]: *** [programs/nodeos/CMakeFiles/nodeos.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2

Anyone know whats causing this?

**Comment by NorseGaud** [comment]
Which branch are you working from? The build scripts are now under scripts/eosio_build.sh. You should run it from the root directory too with `./scripts/eosio_build.sh`.

Lastly, the build script supports a few arguments, but `ubuntu` and `full` are unknown. Are you using a tutorial somewhere that indicates the use of them?

**Comment by TachyonRSA** [comment]
Finally got it working. Now all I am looking for is the folder where eos is actually installed? I used `sudo apt install ./eosio_1.7.0-1-ubuntu-18.04_amd64.deb` - do you know where it possibly installs on Ubuntu?

**Comment by jgiszczak** [comment]
You may always use `dpkg -L <packagename>` to see what files a package installs, including their full paths.  In this case, use `dpkg -L eosio`.

If you still have questions and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
