### ISSUE TITLE
New build script creates too many directories at home

### ISSUE THREAD

**Issue by conr2d** [EOSIO/eos#6957]
When building with `develop` branch, new build script creates too many directories such as `src`, `opt`, `var`, `etc`, `bin` and `data`. The paths are hard-coded with `$HOME`, so it's inconvenient to change them. If all they are necessary, it would be better that all directories are included under single directory like `$HOME/eosio`.

**Comment by NorseGaud** [comment]
We’re looking into potentially doing the folder isolation per our major versions, but for now the isolation (as much as possible) into $HOME is to prepare for future non-root installation.

**Comment by conr2d** [comment]
I

**Comment by NorseGaud** [comment]
Totally understand. We want folks to move to using our OS specific packages instead of the build scripts (they are mostly used for our CI/CD automated build/testing). Regardless, I believe you’ll soon see more flexibility and organization in the build scripts to meet your needs.

**Comment by sgehrman** [comment]
I'm also really annoyed that building clutters up my home directory.  Build also failed.  gzip: stdin: not in gzip format.  Did building have any other side effects like this?  If I build with sudo does that work differently?

**Comment by jgiszczak** [comment]
@sgehrman Building with `sudo` makes it worse.  All the same directories and files are created, but now they're owned by `root`.

**Comment by NorseGaud** [comment]
The next version of the build scripts will take care of this and several other community concerns.
