### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by got3nks** [EOSIO/eos#6959]
`docker build -t eosio/eos:v1.7.0 --build-arg branch=v1.7.0 .`

While compiling libraries/yubihsm

```
-- Checking for one of the modules 'libcurl'
CMake Error at /usr/local/share/cmake-3.9/Modules/FindPkgConfig.cmake:640 (message):
  None of the required 'libcurl' found
Call Stack (most recent call first):
  libraries/yubihsm/CMakeLists.txt:163 (pkg_search_module)


-- Checking for one of the modules 'libusb-1.0'
CMake Error at /usr/local/share/cmake-3.9/Modules/FindPkgConfig.cmake:640 (message):
  None of the required 'libusb-1.0' found
Call Stack (most recent call first):
  libraries/yubihsm/CMakeLists.txt:164 (pkg_search_module)
```

Already installed:

```
apt-get install libusb-1.0-0-dev libusb-1.0-0
apt-get install libcurl4-openssl-dev
```

But same error. Any suggestions?

**Comment by datudou** [comment]
Update the Dockerfile under eosio/Docker/builder.

**Comment by fsword** [comment]
> Update the Dockerfile under eosio/Docker/builder.

Why the official image doesnt work? Is there difference ?

**Comment by NorseGaud** [comment]
@fsword, the images are deprecated and set to be removed in June. We suggest using our OS specific packages instead.

**Comment by fsword** [comment]
> @fsword, the images are deprecated and set to be removed in June. We suggest using our OS specific packages instead.

So the docker folder will removed in the future ? If not, when we should use docker instead of packages ?

**Comment by NorseGaud** [comment]
@fsword, eventually, yes. Our readme currently only suggests using packages.

**Comment by fsword** [comment]
got it

**Comment by fsword** [comment]
> @fsword, eventually, yes. Our readme currently only suggests using packages.

got it

**Comment by got3nks** [comment]
That's what I did:

```
docker rmi eosio/builder
rm -Rf eos
git clone https://github.com/EOSIO/eos.git --recursive  --depth 1
cd eos/Docker/builder/
docker build . -t eosio/builder
cd ..
docker build -t eosio/eos:v1.7.0 --build-arg branch=v1.7.0 .
```

but it's still not working:

```
CMake Error at /usr/local/share/cmake-3.9/Modules/FindPkgConfig.cmake:640 (message):
  None of the required 'libcurl' found
Call Stack (most recent call first):
  libraries/yubihsm/CMakeLists.txt:163 (pkg_search_module)


-- Checking for one of the modules 'libusb-1.0'
CMake Error at /usr/local/share/cmake-3.9/Modules/FindPkgConfig.cmake:640 (message):
  None of the required 'libusb-1.0' found
Call Stack (most recent call first):
  libraries/yubihsm/CMakeLists.txt:164 (pkg_search_module)


CMake Error at libraries/yubihsm/lib/CMakeLists.txt:99 (if):
  if given arguments:

    "VERSION_LESS" "1.0.16"

  Unknown arguments specified
```

**Comment by sushenghua** [comment]
**create Dockerfile with the following content:**

FROM ubuntu:18.04

RUN apt-get update -y \
    && apt-get install -y wget libcurl4-openssl-dev libusb-1.0-0-dev libcurl3-gnutls libicu60 \
    && mkdir -p /opt/source \
    && wget -O  /opt/source/eosio_ubuntu_18.04_amd64.deb https://github.com/eosio/eos/releases/download/v1.7.3/eosio_1.7.3-1-ubuntu-18.04_amd64.deb \
    && dpkg -i /opt/source/eosio_ubuntu_18.04_amd64.deb \
    && mkdir -p /opt/eosio/bin \
    && ln -s /usr/bin/cleos  /opt/eosio/bin/cleos \
    && ln -s /usr/bin/keosd  /opt/eosio/bin/keosd \
    && ln -s /usr/bin/nodeos /opt/eosio/bin/nodeos

ENV PATH /opt/eosio/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


**then run:**
docker build . -t eosio/eos
