### ISSUE TITLE
STAT-169 ⁃ Test script with non-producing node

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#696]
Create a script to verify that a non-producing node will forward transactions on to a producing node.

Integrate into travis build.

ATC:

* tests/run_tests.sh is run on every build.

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

Verified the following
estnet@ip-10-160-12-222:~/STAT/build/tests$ pwd
/home/testnet/STAT/build/tests
testnet@ip-10-160-12-222:~/STAT/build/tests$ ls -ltr run_tests.sh 
rwxrxr-x 1 testnet testnet 355 Nov 22 00:34 run_tests.sh
testnet@ip-10-160-12-222:~/STAT/build/tests$

**Comment by heifner** [comment]
Verified by QA.
