### ISSUE TITLE
How to get a transaction details from block.log file

### ISSUE THREAD

**Issue by hashware** [EOSIO/eos#6966]
I downloaded a block.log file from https://eosnode.tools/blocks
and use tool eosio-blocklog to retrive a block like
**eosio-blocklog --blocks-dir ./blocks/ --first 18245594 --last 18245594**

then get a transaction like this
  **...
"transactions": [{
      "status": "executed",
      "cpu_usage_us": 2075,
      "net_usage_words": 0,
      "trx": "c7d30a65952ba816dbf9eaa38c4bc58ee844593b6e716c7b98459524fca961fd"
    },{
...**

how to get trx c7d30a65952ba816dbf9eaa38c4bc58ee844593b6e716c7b98459524fca961fd details from block.log file without history plugin?

Thanks.

**Comment by jgiszczak** [comment]
To decode transaction details you need the contract ABI for the contract in use.

Using only the block log, you would need to find the last time the contract and ABI were set on the account in question, retrieve the ABI from the transaction which set them, and decode the transaction data by correlating the action named in the transaction with the ABI.

Using live data in addition to the block log, you may retrieve the ABI for the account from a node of the chain in question using the API that exists for the purpose.

If no ABI has been set, there is no simple way to decode the transaction data.  You would have to reverse engineer it.

**Comment by hashware** [comment]
first step
How to find out the hex_data of trx c7d30a65952ba816dbf9eaa38c4bc58ee844593b6e716c7b98459524fca961fd in block.log file?
@jgiszczak 
Thanks
