### ISSUE TITLE
STAT-172 ⁃ sync vs new block production

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#697]
continuation of STAT-155. Improved solution, allow the launcher to set the enable stale production flag via the command line when starting a new testnet but rely on the default value when [re]starting a node to catch up.

Also updating testnet.md and net_plugin option definitions to improve readability.

ATC: 
1. Use the launcher to start a new testnet with > 1 producer node. 
Observe that blocks are being produced on all nodes.
2. Let the system run for several hours then shut down one node and restart it with --resync-blockchain. 
Observe that the restarted node successfully synchronizes and begins producing blocks.

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

Pls add an ATC for it

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

NO ATC. Moving back to In progress.

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

Added ATC to description. Please advise if insufficient,

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

No change to functional code, just added ATC to description

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

Failed test:

1846011ms thread-0   net_plugin.cpp:1727           handle_message       ] expected block 3561 but got 40820 ihnotinh got now
1846031ms thread-0   net_plugin.cpp:1021           operator()           ] post cache: unable to accept block on assert exception Assert Exception
1851004ms thread-0   net_plugin.cpp:1723           handle_message       ] got a block while syncing but no sync_receiving set #40453
1851005ms thread-0   net_plugin.cpp:1241           operator()           ] Error reading message from connection: End of file
1851005ms thread-0   net_plugin.cpp:1241           operator()           ] Error reading message from connection: End of file
1851006ms thread-0   net_plugin.cpp:1241           operator()           ] Error reading message from connection: End of file

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

please retest on the 11-25 testnet

**Comment by heifner** [comment]
Passed QA.
