### ISSUE TITLE
producer logs   message: to account does not exist

### ISSUE THREAD

**Issue by Midcc** [EOSIO/eos#6970]
2019-03-20T07:11:32.508 thread-0   wasm_interface.cpp:929        eosio_assert           ] message: to account does not exist
2019-03-20T07:11:33.003 thread-0   wasm_interface.cpp:929        eosio_assert           ] message: to account does not exist
2019-03-20T07:11:33.003 thread-0   producer_plugin.cpp:330       on_incoming_block    ] Received block 69ea29ccb42bd9d2... #325516 @ 2019-03-20T07:11:33.000 signed by producer111a [
 
but system listproducers 
Producer      Producer key                                              Url                                                         Scaled votes
producer111a  EOS8imf2TDq6FKtLZ8mvXPWcd6EF2rQwo8zKdLNzsbU9EiMSt9Lwz     https://producer111a.com/EOS8imf2TDq6FKtLZ8mvXPWcd6EF2rQwo8 0.3333
producer111b  EOS7Ef4kuyTbXbtSPP5Bgethvo6pbitpuEz2RMWhXb8LXxEgcR7MC     https://producer111b.com/EOS7Ef4kuyTbXbtSPP5Bgethvo6pbitpuE 0.3333
producer111c  EOS5n442Qz4yVc4LbdPCDnxNSseAiUCrNjRxAfPhUvM8tWS5svid6     https://producer111c.com/EOS5n442Qz4yVc4LbdPCDnxNSseAiUCrNj 0.3333

three producers is are started，but only producer111a Produced block,please why?

**Comment by jgiszczak** [comment]
Check that `signature-provider`s are configured for each of producer111b and producer111c with key pairs that match the registered public keys shown above.  They may be configured on the same node as producer111a or their own nodes or any combination.  Also be sure the same node has a matching `producer-name` entry for each producer registered.

If you still have the problem and wish to discuss it further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
