### ISSUE TITLE
./scripts/eosio_build ERROR

### ISSUE THREAD

**Issue by Azure-kyLIN** [EOSIO/eos#6991]
Deadly appreciate any help here, I have tried all I can but still fail, 
OS: Ubuntu 18.04
All follow the automated build script, ( maybe I have to manually build?

The error is like below
`CMake Warning at plugins/mongo_db_plugin/CMakeLists.txt:3 (find_package):
  By not providing "Findlibmongoc-1.0.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "libmongoc-1.0", but CMake did not find one.

  Could not find a package configuration file provided by "libmongoc-1.0"
  (requested version 1.8) with any of the following names:

    libmongoc-1.0Config.cmake
    libmongoc-1.0-config.cmake

  Add the installation prefix of "libmongoc-1.0" to CMAKE_PREFIX_PATH or set
  "libmongoc-1.0_DIR" to a directory containing one of the above files.  If
  "libmongoc-1.0" provides a separate development package or SDK, be sure it
  has been installed.

Could NOT find MongoDB. mongo_db_plugin with MongoDB support will not be included.

usr/bin/ld: cannot find -lmongo_db_plugin
clang: error: linker command failed with exit code 1 (use -v to see invocation)
programs/nodeos/CMakeFiles/nodeos.dir/build.make:190: recipe for target 'programs/nodeos/nodeos' failed
make[2]: *** [programs/nodeos/nodeos] Error 1
CMakeFiles/Makefile2:3528: recipe for target 'programs/nodeos/CMakeFiles/nodeos.dir/all' failed`

However, I install those dependencies and ensure they are intact, damm, what should I do?
How can I find this mongo-plug

**Comment by jgiszczak** [comment]
Since you're getting far enough that CMake is running, if you don't intend to use mongodb the quick and dirty fix is to disable it.  On line 284 of `scripts/eosio_build.sh`, change `-DBUILD_MONGO_DB_PLUGIN=true` to `-DBUILD_MONGO_DB_PLUGIN=false`.

If you do intend to use mongodb, you'll need to diagnose the problem.  The build script does attempt to build and install the mongo interface libraries.  Verify `~/src/mongo-c-driver-1.13.0` is present and its contents look reasonable.  It should contain five directories and eight files at the top level.  Next, verify it was built and installed correctly.  Verify `~/lib` exists and contains `libmongoc-static-1.0.a` and `libmongoc-1.-0.so.0.0.0`.  Also verify `~lib/pkgconfig` exists and contains `libmongoc-1.0.pc`, `libmongoc-static-1.0.pc` and `libmongoc-ssl-1.0.pc`.  If any of those files in `~lib` are missing, the libmongoc build failed.

If the libmongoc build failed, you'll need to find out why and paste the errors here.  Assuming the source directory is present and looks intact, `cd ~/src/mongo-c-driver-1.13.0/cmake-build` and run `make`.

**Comment by Azure-kyLIN** [comment]
So grateful for your help, I follow your instructions and those files you mentioned are already there, safe and sound;
After `cd ~/src/mongo-c-driver-1.13.0/cmake-build` and run `make`
Then I retry compilation but received another mistake  about openssl (This one related to my own system problem and I will try to fix it myself)

BTW, Today I try installing eos in MACOS system, but facing werid problem too;
I don't know if this is the bug or my computer's error?

All about gmp.h

> In file included from /Users/formal1n/eos/libraries/fc/secp256k1/upstream/src/secp256k1.c:12:
In file included from /Users/formal1n/eos/libraries/fc/secp256k1/upstream/src/num_impl.h:14:
In file included from /Users/formal1n/eos/libraries/fc/secp256k1/upstream/src/num.h:17:
/Users/formal1n/eos/libraries/fc/secp256k1/upstream/src/num_gmp.h:10:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^~~~~~~
[ 53%] Built target softfloat
1 error generated.
make[2]: *** [libraries/fc/secp256k1/CMakeFiles/secp256k1.dir/upstream/src/secp256k1.c.o] Error 1
make[1]: *** [libraries/fc/secp256k1/CMakeFiles/secp256k1.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 53%] Built target chainbase

I install gmp using homebrew sucessfully while the cmake cannot find my gmp,

> Checking dependencies...
- cmake found
- automake found
- Libtool found
- OpenSSL found
- wget found
- GMP found
- llvm found
- python NOT found.
- python@2 NOT found.
- doxygen found
- graphviz found
- libusb found
- pkgconfig found

You can see that the dependencies got the gmp... Don't know if other users face this problem

**Comment by jgiszczak** [comment]
Brew doesn't always set up the requisite symbolic links to actually make use of what it installs properly.  If you know you're only using GMP for building EOS.IO, you can fix it with:
`brew unlink gmp`
`brew link --force gmp`
This will remove any stale links, then create new ones.  In the past we included those steps in the build automation but it is considered intrusive, especially when we did it for our specific version of the llvm compiler, so we dropped it.

**Comment by Azure-kyLIN** [comment]
Thanks! It did work.
Now all my projects are done with `eosio` and `eosio.cdt`. However, the compilation of `eos.contracts` is still weird. 
I know maybe this is out of your working range but they are many guys are struggling with the same issues
> https://github.com/EOSIO/eosio.contracts/issues/141
> https://github.com/EOSIO/eosio.contracts/issues/163
> https://github.com/EOSIO/eosio.contracts/issues/180

I tried to adjust the CMakeLists but failed, no idea if you @jgiszczak  have any solutions out. It will be so grateful for you to share your help, really appreciate it.😄
I will close this issue and wait for above issuses answers😢
