### ISSUE TITLE
Xcode v10.0.1 causes build failures with Boost 1.67/8/9

### ISSUE THREAD

**Issue by larryk85** [EOSIO/eos#6996]
The latest release of Xcode 10.2 (clang version 10.0.1) introduces breaking changes that causes EOS to fail to build.  This will affect anyone who starts fresh build with the build script and anyone who updates their Xcode version on their own.  The fix to this issue is to bump the version of Boost to v1.69 and apply a patch to this before building.  We will also have to check the compiler version and not use Boost v1.69 and stay at v1.67 if the version of clang installed is 10.0.0 or lower for branches release/1.6.x and release/1.7.x, develop will not require this check.

**Comment by NorseGaud** [comment]
I can try and get this working in the build scripts. Do you have the patch url?

**Comment by spoonincode** [comment]
I already fixed the xcode 10.2 problems with #6953, we should backport that to 1.6 & 1.7 if need be

**Comment by NorseGaud** [comment]
Thanks @spoonincode
