### ISSUE TITLE
STAT-175 ⁃ Launcher configuration optimization

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#701]
Brian A. and I have worked though some testnet configuration details and decided on some updates. 

The db_plugin cannot be generally applied. But where applied, it needs to be accompanied by a producer plugin. To address this, I'm adding a field to the tesnet.json file indicating that a node should get the db_plugin.

Next, add a new launcher option to start up without overwriting config files. It is currently possible to deploy configuration files without actually starting eosd instances.

Finally, I'm adding a second deployment config file that gives a list of hosts that map to the node ids in the generated testnet.json file. This allows the remote configuration template to remain just that - a template.

**Comment by heifner** [comment]
Resolved by #750

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

1, 2, 3 pass
