### ISSUE TITLE
webauthn key & signature type

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#7012]
Finish adding webauthn key & signatures to eosio. There are still some unresolved questions (now solved; answers in bold) that came out of the prototype:

* where/how/if credential ID is stored - **will not be stored as part of consensus; public storage discouraged regardless**
* JSON parsing vs not parsing - **We need to parse JSON, the "tricks" we discussed internally will not work due to item 4 on this list**
* Compression of JSON or not - **No**
* Validation of HTTPS origin in signature or not (a public key would have an origin it is scoped to) - **Yes we need to validate this**
* Validation of user presence and/or user verification in signature (a public key would state some minimum level of verification requirement) - **Doing this and maintaining the "symmetry" of recovered keys to the public keys in the authority is unwieldy, but it's probably useful to have this ability so will do it**

Ideally all of these are answered before commencing work on the production implementation.

**Comment by jafri** [comment]
If credential ID is not stored as part of consensus or public storage, how will credentials be synced between nodes?

**Comment by spoonincode** [comment]
>If credential ID is not stored as part of consensus or public storage, how will credentials be synced between nodes?

The public key that a credential ID references is part of consensus. It will be a `PUB_WA_...` thing. But the storage of the credential ID that is required to sign via the private key associated with that public key is left outside the scope of consensus.

**Comment by nksanthosh** [comment]
EOSJS related changes will be tracked in https://github.com/EOSIO/eosjs/issues/537

**Comment by spoonincode** [comment]
#7421
