### ISSUE TITLE
state_history_plugin full resync

### ISSUE THREAD

**Issue by ksemaev** [EOSIO/eos#7053]
Guys, is there a way to make state_history_plugin create it's db from 0 on current chain. Thing is - it only starts adding history from the moment it was applied, so to have full history - I have to create empty node, and start filling chain from 0.
Maybe there is an option, or util, that can make it work with currently present chain on disk and fill history db from it?

**Comment by jgiszczak** [comment]
To get full history of a current chain, use the `--replay-blockchain` argument when launching nodeos.  It will move your existing block log out of the way and replay it into a new copy of the chain.  This allows state_history_plugin to build history from the beginning of the chain.  You should also use `--delete-state-history` at the same time to be sure it starts in sync.

You do need to have enough storage space for two complete copies of the chain, which in the case of an older chain can be a substantial storage requirement, so plan ahead before starting a replay.
