### ISSUE TITLE
error when using launcher

### ISSUE THREAD

**Issue by gaoqiaizhanglan** [EOSIO/eos#706]
./launcher -s ring --skip-signature

spawning child, programs/eosd/eosd  --data-dir tn_data_0

terminate called after throwing an instance of 'boost::process::process_error'
  what():  execve failed: No such file or directory

**Comment by heifner** [comment]
launcher currently setup to run only from eos root: `programs/launcher/launcher -s ring --skip-signature`

**Comment by gaoqiaizhanglan** [comment]
ok thanks
