### ISSUE TITLE
Build issue w/mongo download on ubuntu 18.10

### ISSUE THREAD

**Issue by dconry** [EOSIO/eos#7066]
Noticed when building to support wasm-api dev environments: MongoDB has ceased providing downloads for non-LTS Ubuntu releases.  This causes the build script to fail on Ubuntu 18.10.

Changing the build script to download the 18.04 version from Mongo seems to be a valid workaround on 18.10.  Switching to use the OS-provided Mongo packages might also work.

If determined that 18.10 is not supported, this issue can be summarily closed.

**Comment by matthewdarwin** [comment]
As someone who never uses mongo plugin, ideally there would be an option to not even bother doing the download or compile steps at all.

**Comment by spoonincode** [comment]
Build scripts no longer allow the use of anything other than 16.04 or 18.04 for now
