### ISSUE TITLE
Assertion exception during index reconstruction leads to crash

### ISSUE THREAD

**Issue by dconry** [EOSIO/eos#7067]
Ran into this issue on 1.7.1 during replay from a recent block log.  During initial block **index** reconstruction, nodeos crashes with an assertion exception on block 49448627 (dated 3/25 ~ 0606UTC).

Initial test was run with "--replay --wasm-backend wavm" flags.  I also tried fresh replay with wabt backend, same result.  Finally, I tried a hard replay, same result.

Attaching relevant nodeos error log snippets for both soft replay & hard replay results.  Hard replay log has a bit more detail including exact block num.  I also have the full logs for these runs, if desired.

[softreplay_crash.txt](https://github.com/EOSIO/eos/files/3045174/softreplay_crash.txt)
[hardreplay_crash.txt](https://github.com/EOSIO/eos/files/3045176/hardreplay_crash.txt)

Add'tl details: I can reproduce this issue also with release 1.6.1.  Tests were all run on latest Ubuntu 18.04.  Nodeos was installed from binary packages.

**Comment by taokayan** [comment]
It's likely that your block log file is corrupted at block 49448627. Try to use --hard-replay-blockchain with --truncate-at-block, or download the most updated block log.

**Comment by xebb82** [comment]
I got the same error on two different machines while trying to sync up my state history (with blocks copied from another machine that's working). I've tested with the same result on: 1.5.3, 1.6.3, 1.6.4, 1.7.0 and 1.7.1.
I'm closing in on this magical block on a third machine as we speak (with state history enabled).

I started my nodeos process using a snapshot from 2019-03-10, which was the closest earlier snapshot I had (49448627 timestamp: 2019-03-25T10:06:17.500).
The machine without state-history enabled passed it nicely and is currently at:
2019-04-08T09:03:23.730 thread-0  controller.cpp:313            replay               ] 51478000 of 51702269

While my third with state-history is currently at: 492810000.
Will report back with results.

**Comment by dconry** [comment]
> It's likely that your block log file is corrupted at block 49448627. Try to use --hard-replay-blockchain with --truncate-at-block, or download the most updated block log.

This is certainly possible, though I tried two different block logs with verified checksums, both failing on the same block.  Truncating the log before 49448627 does allow index reconstruction to complete & replay to continue.

**Comment by spoonincode** [comment]
I can't reproduce on my local block log

**Comment by spoonincode** [comment]
@dconry can you provide the exact length of the troublesome block log and its SHA256? Curious to see if mine matches through that range

**Comment by dconry** [comment]
@spoonincode I do still have both blocks logs that were tested earlier, both are from EOS node tools site.  Here are verified md5 sums of the (compressed) logs:

blocks_2019-03-29-07-02.tar.gz   3ddde743b3be53dbe64bb682ba882561
blocks_2019-04-03-07-02.tar.gz   cc59e396b2db9969fe5af0d4efa2d77d

I can certainly also provide uncompressed log file sizes & sha256 checksums for these.  I will look into how to determine ending block num.

Just to stress, this crash is happening during block index construction (prior to replay), as node tools does not supply an index file.  Since both logs above were pulled from the same source, some common corruption at the source is of course possible.

**Comment by spoonincode** [comment]
>this crash is happening during block index construction (prior to replay)

Yep, understand. But my block log (synced myself) does not have any problems reconstructing the index.

I just need the length and sha256 of the uncompressed block.log to compare to mine. I will sha256 mine up to the last byte yours has.

**Comment by dconry** [comment]
Here is size/checksum of one log, from 3/29/2019 0702:

$ stat blocks.log
File: blocks.log
Size: 243404660132    Blocks: 475399736  IO Block: 4096   regular file

$ sha256sum blocks.log
d6151ac9dc4af7ddff3d9d72328bdadb328fa1c2fb6b72df181ce27466594c58  blocks.log

Working on the 2nd log now.

**Comment by spoonincode** [comment]
```
$ ls -l blocks.log.don
-rw-r--r-- 1 spoon spoon 243404660132 Apr 15 10:52 blocks.log.don
$ sha256sum blocks.log.don
affaac85a089e9a8c7be66998a4dba585f8b818447604ce6da94b41d231e99b8  blocks.log.don
```

So our two block logs are different. That's a good indicator one of ours is corrupted; and since yours won't index, I'd say it's probably yours 🙂

**Comment by dconry** [comment]
Yes, I'd say that points to corruption in the logs I used.

I was able to bypass this crash last week by replaying from a log truncated prior to 49448626.  This replayed back to current without error.  I just removed the block index & initiated another replay on that log, it also did *not* crash on index construction.

**Comment by dconry** [comment]
We are convinced this was due to blocks log corruption from the common source (EOS Node Tools).  Subsequent attempts with later logs from other sources, as well as with using further synced logs from the original source, resulted in no such issue.  Closing pending reoccurrence.
