### ISSUE TITLE
push transaction error  memo length range 6-10

### ISSUE THREAD

**Issue by quarksgluons** [EOSIO/eos#7082]
eos 1.6.0

2019-04-05T09:30:59.063  ---  2019-04-06T01:01:09.614 
The node log has been reporting this error for about 16 hours during this time. I can't the error definition in the  source code. What is the reason for this error?

I saw other people in the issue raised this question, but later did not investigate the reasons for the in-depth investigation.

https://github.com/EOSIO/eos/issues/6726

```
error 2019-04-06T00:59:51.410 thread-0  http_plugin.cpp:585           handle_exception     ] FC Exception encountered while processing chain.push_transaction
debug 2019-04-06T00:59:51.410 thread-0  http_plugin.cpp:586           handle_exception     ] Exception Details: 3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
assertion failure with message: memo length range 6-10!
    {"s":"memo length range 6-10!"}
    thread-0  wasm_interface.cpp:917 eosio_assert
pending console output:
    {"console":""}
    thread-0  apply_context.cpp:72 exec_one
```

**Comment by taokayan** [comment]
again this error is likely thrown at the contract of some account. It's better to contact the contract owner/developer to find out the solution.

**Comment by quarksgluons** [comment]
I checked the receiving account and found that he really has a contract.
thanks！
