### ISSUE TITLE
Using available_primary_key() as table scope

### ISSUE THREAD

**Issue by jasonbert** [EOSIO/eos#7087]
I've written a full explanation of this on the [eosio stack exchange](https://eosio.stackexchange.com/questions/4212/why-does-using-available-primary-key-as-scope-for-a-table-result-in-this-behav), but here's the tl;dr :).

When using the incremental `available_primary_key()` as a way of scoping data, the data returned by `get scope <account> -t <table name>` doesn't seem right. The `scope` property is returning values of `""` for ID 0 and `"............1"` for any ID above 0, where the number is always equal to the ID.

My assumption for this behaviour is because `scope` is normally used with an account name, however you pass through a `uint64_t` to the scope and not a `name` object. I think the return data for `scope` should better handle `uint64_t` values that don't translate to a valid EOS account.

A secondary point, although unrelated to scope, is the fact the `count` property always seems to return a value double the actual number of rows in the scope.

```
{
  "rows": [{
      "code": "gre1111111p1",
      "scope": "",
      "table": "rwdsacts",
      "payer": "gre1111111p1",
      "count": 2
    },{
      "code": "gre1111111p1",
      "scope": "............1",
      "table": "rwdsacts",
      "payer": "gre1111111p1",
      "count": 2
    },{
      "code": "gre1111111p1",
      "scope": "............2",
      "table": "rwdsacts",
      "payer": "gre1111111p1",
      "count": 4
    }
  ],
  "more": ""
}
```

**Comment by tbfleming** [comment]
All uint64_t values are also valid names. They're valid account names if the 4 LSBs are 0.

Changing scope's type in the /v1/... api will break existing clients.

**Comment by eostb** [comment]
verry good

**Comment by jasonbert** [comment]
@tbfleming appreciate breaking changes are not wise, although there have been plenty so far ;), and I'm not advocating one. 

As it stands, the process of using a raw uint64_t as a scope is incomplete and you would have to do conversions.

1. List table scopes -> returns `name` type
2. Convert `name` scope to `uint64_t` <-- this step shouldn't be required
3. Call action `addrow(uint64_t scope, ...)`

I think it would be useful to have an additional property which returns the raw uint64_t of the scope, this would avoid the breaking change.

**Comment by jasonbert** [comment]
Forgot to also check again regarding the `count`, any reason it shows `rows*2` instead of the actual row count?

**Comment by taokayan** [comment]
the 2x count number is likely because of the usage of secondary index.

**Comment by jasonbert** [comment]
@taokayan the table in question actually has a primary and two secondary indexes. The count should surely not be impacted by the number of indexes on a table, that skews the actual row count then.

**Comment by jgiszczak** [comment]
@jasonbert Correct, it shouldn't.  The count is affected by the presence of any secondary index.  This is being tracked in issue #6605.  At present you can only account for the fact that all rows are double counted when a table has a secondary index.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
