### ISSUE TITLE
[windows,docker,beginner]some troubles when building eos by docker in windows

### ISSUE THREAD

**Issue by ChesleyCN** [EOSIO/eos#710]
emmm,,,it's just a little of trouble while building docker. I hope that can be joined into the user manual.

i use docker in windows(10). the first time, I follow the document (https://github.com/EOSIO/eos/tree/master/Docker)
HOWEVER,some errors happened.

1.Port conflict
2.“can not find such file” when doing “docker compose”

SOLUTION：
0.docker rm [container ID]
1.docker rmi [image ID]
2.edit “eos/Docker/Dockerfile” 
    `EXPOSE 19876 8888`
3.edit “eos/Docker/docker-compose.yml”
    `ports:
    - "8888:8888"
    - "19876:19876"`
4.change volum in default "docker-compose.yml":
    `volumes:
    - /d/eos/eos/data/store/eos:/opt/eos/bin/data-dir`
5.Build a path “D:/eos/eos/data/store/eos”
6.re-build docker image following the document:
    docker build -t eosio/eos -f Docker/Dockerfile .

**Comment by heifner** [comment]
We have update Docker and have addressed all of these issues I believe. Can you please try again.
