### ISSUE TITLE
How to define the struct key_weight by eosio.cdt's libraries?

### ISSUE THREAD

**Issue by saltbo** [EOSIO/eos#7106]
Hello,  how to defined keyweight by eosio.cdt?

I use the public_key from crypto.hpp replace  eosiosystem::key_weight,

But, I got a error public_key.

```
    struct permission_level_weight {
        permission_level permission;
        uint16_t weight;
    };

    struct wait_weight {
        uint32_t wait_sec;
        uint16_t weight;
    };

    struct key_weight {
        public_key key;
        uint16_t weight;
    };

    struct authority {
        uint32_t threshold = 0;
        vector<key_weight> keys;
        vector<permission_level_weight> accounts;
        vector<wait_weight> waits;
    };

    std::array<char, 33> data;
    std::copy(pubkey.begin(), pubkey.end(), data.data());
    print(data.data());

    key_weight keyweight = {.key = public_key{.type = 0, .data = data}, .weight = 1};
    authority owner = {.threshold = 1, .keys = {keyweight}, .accounts = {}, .waits = {}};
    authority active = {.threshold = 1, .keys = {keyweight}, .accounts = {}, .waits = {}};

    
    action create_account = action(permission_level(get_self(), "active"_n), "eosio"_n, "newaccount"_n, std::make_tuple(_self, newname, owner, active));
    create_account.send();
```

My public_key is `EOS7WGdLRwPeR7AgEwp5AfcEMhxCz8tXtsD1iLgbYpPzqehkaUusW`
but it be set to `EOS3KjJRdcon8KoinC8oaeewKC7Dw7xrRpPvNtj49EhJABq4m5dNoi`

**Comment by saltbo** [comment]
I try to use eosio's libraries -- #include <fc/crypto/public_key.hpp>

but，I got error: "iostreams currently clash with eosio::datastream"

**Comment by anyshy** [comment]
> https://eosio.stackexchange.com/questions/3304/how-to-transfer-token-and-do-some-action-inlineor-how-to-parse-string-to-signat

`  struct key_weight
  {
    capi_public_key key;
    uint16_t weight;
  };
  ACTION create(string strpubk, name newname)
  {
    key_weight keyweight = {.key = str_to_pub(strpubk), .weight = 1};
    authority owner = {.threshold = 1, .keys = {keyweight}, .accounts = {}, .waits = {}};
    authority active = {.threshold = 1, .keys = {keyweight}, .accounts = {}, .waits = {}};

    action create_account = action(permission_level(get_self(), "active"_n), "eosio"_n, "newaccount"_n, std::make_tuple(_self, newname, owner, active));
    create_account.send();
  }`

**Comment by saltbo** [comment]
thanks @anyshy
