### ISSUE TITLE
Upgrade to 1.7 - import wallets and accounts

### ISSUE THREAD

**Issue by nicram-cf** [EOSIO/eos#7110]
I try to upgrade to newest version from v1.3.
On production we have generated accounts. How to import them to newest version, what steps are to upgrade procedure?

**Comment by jgiszczak** [comment]
Wallet format has not changed, so you may simply run keosd v1.7 with the same parameters you've been using and cleos will be able to unlock and use your existing wallets without change.

To upgrade nodeos, after shutting down v1.3, run v1.7 with the `--replay-blockchain` argument.  This will preserve the accounts you created in your chain, along with all other state.  Depending on how long you've been running your v1.3 chain, it could take many hours to complete the replay, during which time most chain functions are not available, so plan for some downtime.
