### ISSUE TITLE
Warning encountered while re-runing eosd after creating Account 

### ISSUE THREAD

**Issue by spicynoodle** [EOSIO/eos#712]
![image](https://user-images.githubusercontent.com/16319106/32892419-1f9a1fa2-cb11-11e7-92e4-47b1c5b5c7f3.png)

**Comment by heifner** [comment]
This is just informing you that if your wallet is not on the localhost then you are transferring your private keys across the network. If you are just testing, then no big deal. But be careful with your private keys tied to important public keys.
