### ISSUE TITLE
inline action's authorizing actor eosio.ram does not exist

### ISSUE THREAD

**Issue by freeFeatrue** [EOSIO/eos#7121]
I'm running local testnet; I want to create new account !
`
~/work$  cleos system newaccount  \
--stake-net "1000.0000 EOS"  \
--stake-cpu "1000.0000 EOS"  \
--transfer \
--buy-ram "50 EOS" \
eosio  \
wolftest1111  \
EOS6EUKo6HVXjmtbQyAw6HhAixhvv7UvyqDM8gNedyh47bPd38fLa  \
EOS6EUKo6HVXjmtbQyAw6HhAixhvv7UvyqDM8gNedyh47bPd38fLa

Error 3050000: Action validate exception
Error Details:
inline action's authorizing actor eosio.ram does not exist
pending console output: 
`
Is my command line right?  Any insight into this?

**Comment by conr2d** [comment]
https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence

Have you followed this tutorial first? Not only launching nodeos, but more jobs (deploying system contract, creating default accounts like eosio.ram, eosio.ramfee, eosio.stake etc.) are required to mimic mainnet environment.

If you still have question, you can post it on https://eosio.stackexchange.com. Here issues are for bug report or feature request.

**Comment by freeFeatrue** [comment]
I forgot create the system accounts !!! 
thanks for your reply!
