### ISSUE TITLE
eosio 1.7.1 after sudo ./eosio_install.sh ，cannot use   nodeos  command anywhere 

### ISSUE THREAD

**Issue by lsf1001** [EOSIO/eos#7124]
when i buid the eosio 1.7.1 ，after sudo ./eosio_install.sh ，cannot  use nodeos  command anywhere 
 
My solution is   
sudo cp /build/programs/nodeos/nodeos  /usr/local/bin 

I hope to be able to fix this bug 
QQQ

**Comment by lsf1001** [comment]
@jgiszczak  @heifner @arhag

**Comment by spoonincode** [comment]
The 1.7.x eosio_install.sh script installs the binaries to ~/opt/eosio/bin/

Did you look to see if you have nodeos there?

**Comment by NorseGaud** [comment]
The install script also indicates the location where it was installed. Ensure this is in your path:
https://github.com/EOSIO/eos/blob/265b60db3132f28e084b5e3644d80a8607b6863f/scripts/eosio_install.sh#L80
