### ISSUE TITLE
Working build process.

### ISSUE THREAD

**Issue by lanmower** [EOSIO/eos#7154]
We're unable to get the software to build using Ubuntu 18.04

The manual build instructions do not work, and produces various errors that are all seemingly impassable.

Since docker support is getting dropped, a working build process should be publicized.

**Comment by jgiszczak** [comment]
If you don't need a custom build, the `.deb` packages are strongly recommended.

Can you be more specific about the build errors you encountered?

**Comment by NorseGaud** [comment]
I am curious what issues you are experiencing. Our CI/CD pipelines run various builds to ensure that the build scripts function with 18.04. If it does not work, it could be that local changes are conflicting with the scripts (like ENV variables, etc).

**Comment by spoonincode** [comment]
No response to support ticket in two months, closing
