### ISSUE TITLE
Running nodeos on second machine, connection refused when trying to curl it

### ISSUE THREAD

**Issue by sgehrman** [EOSIO/eos#7166]
My main machine is Debian, so I had to set up a second machine on Ubuntu to compile and run nodeos, but i can't access it.  No firewall, should work. (clean install of 18.04)

$ curl http://192.168.1.242:8888/v1/chain/get_info
curl: (7) Failed to connect to 192.168.1.242 port 8888: Connection refused

why connection refused?

What I did...

start nodeos:

steve@EOSOS:~$ nodeos -e -p eosio \
> --plugin eosio::producer_plugin \
> --plugin eosio::chain_api_plugin \
> --plugin eosio::http_plugin \
> --plugin eosio::history_plugin \
> --plugin eosio::history_api_plugin \
> --access-control-allow-origin='*' \
> --contracts-console \
> --http-validate-host=false \
> --verbose-http-errors >> nodeos.log 2>&1 &

works when on that machine:

steve@EOSOS:~$ curl http://localhost:8888/v1/chain/get_info

{"server_version":"265b60db","chain_id":"cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f","head_block_num":20,"last_irreversible_block_num":19,"last_irreversible_block_id":"00000013d844e8e4e095cc85e5c36df6c0c9d3837f063f201dc0a161879f5c5a","head_block_id":"0000001492f6e856a085bae97b9fc63bad4cbb5fc6c3b7a813cadf4bce87e4c0","head_block_time":"2019-04-19T05:45:43.500","head_block_producer":"eosio","virtual_block_cpu_limit":203830,"virtual_block_net_limit":1068689,"block_cpu_limit":199900,"block_net_limit":1048576,"server_version_string":"v1.7.1-9-g265b60db3"}

exit ssh:

steve@EOSOS:~$ exit
Connection to 192.168.1.242 closed.

on main dev box:

$ curl http://192.168.1.242:8888/v1/chain/get_info
curl: (7) Failed to connect to 192.168.1.242 port 8888: Connection refused

I have apache running on that machine too and curl on  port:80 works just fine

Sorry if this is a noob question, just started EOS dev.

-steve

**Comment by Jeiwan** [comment]
Try to add `--http-server-address=0.0.0.0:8888` to the nodeos starting command.

**Comment by sgehrman** [comment]
That worked!! Thanks man.

-steve
