### ISSUE TITLE
STAT-81 ⁃ Database Limiting

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#717]
Will track bytes for a code account as rows are stored, updated, and removed.  Each row's bytes will be calculated by the byte size of the passed in data plus a configured size ("row-overhead-db-limit-bytes") to account for scope, code, table, and key storage.  If we are not applying a received block, if the configured max storage ("per-code-account-max-storage-db-limit-mbytes") is exceeded, an exception will be thrown.

Acceptance Testing:

* Write a contract that creates rows (store_*),  modifies rows (store_* and update_*), and deletes rows (remove_*) at varying amounts
* Set the "per-code-account-max-storage-db-limit-mbytes" to 1 (MB).("row-overhead-db-limit-bytes" is defaulted to 32)
* Each rows storage is determined by "row-overhead-db-limit-bytes" plus the number of bytes needed for the key and value (rounded to the next 8 byte boundary)
* Verify that a limit can be reached and:

1. creates are rejected
1. modifies with larger new data are rejected
1. modifies with smaller new data are accepted
1. deletes are always accepted
1. creates or modifies in subsequent init are rejected

* if testing with multiple nodes, after limit is reached, and blocks have been propogated, on a different node verify that:

1. creates are rejected
1. modifies with larger new data are rejected
1. modifies with smaller new data are accepted
1. deletes are always accepted

┆Attachments: <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10068&#x2F;dblimiting.abi">dblimiting.abi</a> | <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10069&#x2F;dblimiting.cpp">dblimiting.cpp</a> | <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10070&#x2F;dblimiting.gen.gpp">dblimiting.gen.gpp</a> | <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10072&#x2F;dblimiting.gen.hpp">dblimiting.gen.hpp</a> | <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10071&#x2F;dblimiting.hpp">dblimiting.hpp</a> | <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10073&#x2F;Screen+Shot+2017-11-29+at+4.01.24+PM.png">Screen Shot 2017-11-29 at 4.01.24 PM.png</a>

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

[~admin] At the very least we need max table usage size by contract enforced. Assuming delta rate limit is handled by time limit. Do you have any additional requirements?

**Comment by blockone-syncclient** [comment]
➤ David Moss commented:

[~kevin.heifner] Those are the current requirements. Let's get them implemented, then when we stand up the Testnet, we can write spamming scripts to see if this is adequate.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

https://github.com/EOSIO/eos/issues/353

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

Tests are in place, going to rebase to master and submit pull request.

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

I am not sure how to test this. Needs more information and detailed steps.

What I understood:

1. Create a smart contract that inserts data and if size of data exceeds a limit, it should reject.

Then I have questions:

1. If a db operation is rejected, how do I know how much of limit is available?

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

There is currently no way to retrieve that information from the eosd.  To know exactly how much memory is available, you will need to calculate the size of your rows (using the row calculation added to the ATC) and determine what the remainder is when you have approached the 1MB limit.

**Comment by bytemaster** [comment]
Ideally storage usage is not something that a contract can query, it is a limit set for "abuse purposes" but in theory we could change the rate limiting/billing algorithms in the future and it would be a shame to have to enforce all the old rules / calculations for ever.

Rate limits can only ever fail a transaction and they can never be tested or "branched upon".

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

test contract looks good

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

I implemented attached contract and after pushing the contract to eosd, I use the attached script to send multiple messages to eosd. I think it exceeds 5 MB but don't see any errors reported.

Attached are following:

1. smart contract implementation.
2. script to send messages in a loop.
3. picture of block and blockchain folder in data-dir of eosd.

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

[~pravin.bezwada] Since there is an automated test that verifies that the limit is reached, can we get the contract changed to print the: key, size of key string (which is passed into store_xx or update_xx, or remove_xx), and size of value buffer  (which is passed into store_xx or update_xx)
so that the calculation can be verified. Also, if you can keep going to see if a limit can be reached (as long as testing doesn't take too long)
The other option is if you could analyze my automated test and see if you can identify why that calculation works out right and your contract doesn't (or if my code incorrectly determines the limit being reached).

**Comment by heifner** [comment]
Verified.
