### ISSUE TITLE
I just did my first EOSIO upgrade with a software package, but found that the version did upgrade and the directory structure didn't change, which I didn't think was very good

### ISSUE THREAD

**Issue by lsf1001** [EOSIO/eos#7178]
I just did my first EOSIO upgrade with a software package, but found that the version did upgrade and the directory structure didn't change, which I didn't think was very good

**Comment by lsf1001** [comment]
@jgiszczak @heifner @arhag

**Comment by NorseGaud** [comment]
Can you clarify exactly what you mean by "the directory structure didn't change"?

**Comment by NorseGaud** [comment]
I'm going to close this due to inactivity. Feel free to reply and we'll re-open
