### ISSUE TITLE
How to write the unit tests using eosio.cdt 1.6.1 or latest?

### ISSUE THREAD

**Issue by farhan-troon** [EOSIO/eos#7182]
Hi, 
I'm trying to figure out how to write unit test using new eosio.cdt and I have already seen the tests in eosio.contracts repository but all tests are old which uses the eosio/chain/* libraries and some boost libraries which are removed from eosio.cdt 1.6.1.

I need your help finding a solution to write unit tests that compatible with eosio.cdt.
Thanks.

**Comment by Jeiwan** [comment]
@farhan-troon Did you find a solution?

**Comment by farhan-troon** [comment]
Yeah, eosio.contracts using old tests but you can new test in eosio.cdt example hello contract which work perfectly fine for me with using cmake.
https://github.com/EOSIO/eosio.cdt/tree/master/examples/hello

**Comment by Jeiwan** [comment]
@farhan-troon awesome! Thanks.
