### ISSUE TITLE
Unable to cancel delayed transaction.

### ISSUE THREAD

**Issue by ashishchandr70** [EOSIO/eos#7186]
Hi,

Network: mainnet

Original Transaction ID that creates the deferred transaction: 18bc3743bd52c3d4609ce39cd36bcdfd5d53f4053ce64a84b596afd5003f16d5

Deferred Action's Transaction ID: **ea5ec618c47f28e0fe3f099d60bac7f13a82b01a7e98fab8cc77878c8385f53f**

https://eosq.app/tx/ea5ec618c47f28e0fe3f099d60bac7f13a82b01a7e98fab8cc77878c8385f53f

`cleos --url https://api.eosnewyork.io system canceldelay eosrex.io active ea5ec618c47f28e0fe3f099d60bac7f13a82b01a7e98fab8cc77878c8385f53f`

`Error 3040011: The transaction can not be found
Error Details:
cannot cancel trx_id=ea5ec618c47f28e0fe3f099d60bac7f13a82b01a7e98fab8cc77878c8385f53f, there is no deferred transaction with that transaction id`

Thank you,
Ashish

**Comment by tbfleming** [comment]
It's a contract-generated deferred transaction. Only the contract which generated it can cancel it.

**Comment by ashishchandr70** [comment]
Thanks for your comment.
