### ISSUE TITLE
MAKE installing EOSIO has exited with the above error

### ISSUE THREAD

**Issue by VtpVlan-oo7** [EOSIO/eos#7190]
sudo ./scripts/eosio_build.sh -s EOS

Beginning build version: 2.1
Wed Apr 24 00:42:30 UTC 2019
User: root
Current branch: HEAD

ARCHITECTURE: Linux

OS name: Ubuntu
OS Version: 16.04
CPU speed: 2400.076Mhz
CPU cores: 4
Physical Memory: 16046 Mgb
Disk install: /dev/xvda1
Disk space total: 310G
Disk space available: 301G
Do you wish to update repositories with apt-get update? (y/n) y
Hit:1 http://ap-northeast-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ap-northeast-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease      
Hit:3 http://ap-northeast-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                    
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]                                                              
Hit:5 http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu xenial InRelease                  
Hit:6 http://ppa.launchpad.net/jonathonf/gcc-7.1/ubuntu xenial InRelease                                       
Fetched 109 kB in 1s (70.7 kB/s)                                                    
Reading package lists... Done
 - APT update complete.

Checking for installed dependencies...
 - Package git found.
 - Package llvm-4.0 found.
 - Package clang-4.0 found.
 - Package libclang-4.0-dev found.
 - Package make found.
 - Package automake found.
 - Package libbz2-dev found.
 - Package libssl-dev found.
 - Package doxygen found.
 - Package graphviz found.
 - Package libgmp3-dev found.
 - Package autotools-dev found.
 - Package build-essential found.
 - Package libicu-dev found.
 - Package python2.7 found.
 - Package python2.7-dev found.
 - Package python3 found.
 - Package python3-dev found.
 - Package autoconf found.
 - Package libtool found.
 - Package curl found.
 - Package zlib1g-dev found.
 - Package sudo found.
 - Package ruby found.
 - Package libusb-1.0-0-dev found.
 - Package libcurl4-gnutls-dev found.
 - Package pkg-config found.
 - No required APT dependencies to install.
Checking CMAKE installation...
 - CMAKE found @ /usr/bin/cmake.

Checking Boost library (1_67_0) installation...
 - Boost library found with correct version @ /home/ubuntu/src/boost_1_67_0 (Symlinked to /home/ubuntu/opt/boost).

Checking MongoDB installation...
 - MongoDB found with correct version @ /home/ubuntu/opt/mongodb-3.6.3 (Symlinked to /home/ubuntu/opt/mongodb).
Checking MongoDB C driver installation...
 - MongoDB C driver found with correct version @ /home/ubuntu/src/mongo-c-driver-1.13.0.
Checking MongoDB C++ driver installation...
 - MongoDB C++ driver found with correct version @ /home/ubuntu/src/mongo-cxx-driver-r3.4.0.

Checking LLVM 4 support...
 - LLVM found @ /home/ubuntu/opt/llvm.

========================================================================
======================= Starting EOSIO Build =======================
## ENABLE_COVERAGE_TESTING=false
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.67 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:105 (FIND_PACKAGE)

-- Configuring EOSIO on Linux
-- Using 'EOS' as CORE symbol name
-- Using 'EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV' as public key for 'eosio' account
-- Configuring fc to build on Unix/Apple
-- zlib found
-- Configuring Builtins
-- Configuring SoftFloat
-- Using custom FindBoost.cmake
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   system
--   chrono
--   unit_test_framework
-- Configuring ChainBase on Linux
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.60 (or
  newer).
Call Stack (most recent call first):
  libraries/appbase/CMakeLists.txt:20 (find_package)

-- Configuring AppBase on Linux
-- Using prebuilt re2c lexer
-- Starting yubihsm configuration...
Install targets
Libraries /home/ubuntu/opt/eosio/lib
Includes /home/ubuntu/opt/eosio/include
Binaries /home/ubuntu/opt/eosio/bin
Manuals /home/ubuntu/opt/eosio/share/man
Pkg-config /home/ubuntu/opt/eosio/share/pkgconfig
not win32
-- yubihsm configuration complete
-- Found bsoncxx headers: /usr/local/include/bsoncxx/v_noabi
-- Found bsoncxx library: /usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-lc;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread
-- Found mongocxx headers: /usr/local/include/mongocxx/v_noabi;/usr/local/include/bsoncxx/v_noabi
-- Found mongocxx library: /usr/local/lib/libmongocxx-static.a;/usr/local/lib/libbsoncxx-static.a;/usr/local/lib/libbson-static-1.0.a;-lc;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread;/usr/local/lib/libmongoc-static-1.0.a;/usr/local/lib/libbson-static-1.0.a;-lc;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;rt;/usr/lib/x86_64-linux-gnu/libz.so;resolv
-- Git commit revision: 38d8c2b9
-- Git commit revision: 38d8c2b9
-- Git commit revision: 38d8c2b9
-- Not building contracts in directory `eos/unittests/test-contracts/`
-- Configuring incomplete, errors occurred!
See also "/home/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/eos/build/CMakeFiles/CMakeError.log".

ubuntu@ip-172-26-11-104:/home/eos$ sudo ./scripts/eosio_install.sh
make: *** No rule to make target 'install'.  Stop.

MAKE installing EOSIO has exited with the above error.

what should i do to resolve such this error..................!!!

**Comment by taokayan** [comment]
you need to have boost version 1.67

**Comment by VtpVlan-oo7** [comment]
@taokayan i have boost version 1.67 but still i'm facing same issue.

**Comment by jgiszczak** [comment]
If you're not using boost 1.58 for anything else, the easiest fix for this problem is to uninstall the boost development packages for 1.58.  Use `sudeo apt remove '^libboost.*1\.58.*-dev'`.

**Comment by VtpVlan-oo7** [comment]
@jgiszczak sir, but now i'm facing this issue-

-- Starting yubihsm configuration...
Install targets
Libraries /home/ubuntu/opt/eosio/lib
Includes /home/ubuntu/opt/eosio/include
Binaries /home/ubuntu/opt/eosio/bin
Manuals /home/ubuntu/opt/eosio/share/man
Pkg-config /home/ubuntu/opt/eosio/share/pkgconfig
not win32
-- Looking for memset_s
-- Looking for memset_s - not found
-- Looking for explicit_bzero
-- Looking for explicit_bzero - not found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'libcrypto'
-- Checking for one of the modules 'libcurl'
-- Checking for one of the modules 'libusb-1.0'
-- yubihsm configuration complete
-- Found bsoncxx headers: /home/ubuntu/include/bsoncxx/v_noabi
-- Found bsoncxx library: /home/ubuntu/lib/libbsoncxx-static.a;/home/ubuntu/lib/libbson-static-1.0.a;-lc;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread
-- Found mongocxx headers: /home/ubuntu/include/mongocxx/v_noabi;/home/ubuntu/include/bsoncxx/v_noabi
-- Found mongocxx library: /home/ubuntu/lib/libmongocxx-static.a;/home/ubuntu/lib/libbsoncxx-static.a;/home/ubuntu/lib/libbson-static-1.0.a;-lc;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread;/home/ubuntu/lib/libmongoc-static-1.0.a;/home/ubuntu/lib/libbson-static-1.0.a;-lc;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libm.so;-pthread;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;rt;/usr/lib/x86_64-linux-gnu/libz.so;resolv
-- Git commit revision: 448287d5
-- Git commit revision: 448287d5
-- Found Intl: /usr/include  
-- Git commit revision: 448287d5
-- Not building contracts in directory `eos/unittests/test-contracts/`
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/EOSIO/eos/libraries/appbase/Boost_INCLUDE_DIR
   used as include directory in directory /home/EOSIO/eos/libraries/appbase
/home/EOSIO/eos/libraries/chainbase/Boost_INCLUDE_DIR
   used as include directory in directory /home/EOSIO/eos/libraries/chainbase
/home/EOSIO/eos/libraries/fc/Boost_INCLUDE_DIR
   used as include directory in directory /home/EOSIO/eos/libraries/fc

-- Configuring incomplete, errors occurred!
See also "/home/EOSIO/eos/build/CMakeFiles/CMakeOutput.log".
See also "/home/EOSIO/eos/build/CMakeFiles/CMakeError.log".

**Comment by heifner** [comment]
What version of eosio are you trying to build?

**Comment by VtpVlan-oo7** [comment]
@heifner  i am using mainnet-1.6.0

**Comment by spoonincode** [comment]
Have you tried building 1.8? Is the issue resolved?

**Comment by spoonincode** [comment]
No response from submitter in nearly a month. Closing this as report was against 1.6. If problems persist on 1.8 please file a new report.
