### ISSUE TITLE
Invalid Options in Config File error without printing which config file was being loaded

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#7231]
I was attempting to follow tutorials with an old config file and wasn't able to track down which config file nodeos thought it was loading.  This will make a very poor experience for any new developer with a bad config file and not knowing where to look.

> nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::http_plugin --plugin eosio::history_plugin --plugin eosio::history_api_plugin --access-control-allow-origin='*' --contracts-console --http-validate-host=false --verbose-http-errors  --config-dir configs/
error 2019-04-27T20:00:37.318 thread-0  main.cpp:127                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option 'invalid-option'

**Comment by andriantolie** [comment]
I've opened PR https://github.com/EOSIO/appbase/pull/68 for this

**Comment by spoonincode** [comment]
This has been merged in; closing
