### ISSUE TITLE
Can't start eosd after reboot

### ISSUE THREAD

**Issue by gluneau** [EOSIO/eos#726]
The two must relevant pieces of information in the seems to be 
``` 
Log is nonempty
13 NSt8ios_base7failureB5cxx11E: basic_ios::clear: iostream error
```

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510941631/lvbszvechctdrvdfmjcv.png)

The error seems similar to [EOS Issue #523](https://github.com/EOSIO/eos/issues/523) but since the process is not running, it's different.

Also does seem similar to this steem issue: [Steem Issue #589](https://github.com/steemit/steem/issues/589)
That was resolved by flushing the log. [Steem commit](https://github.com/steemit/steem/commit/419efced5d916c56de15f1907a8292a2fdf7260d)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@helo/can-t-start-eosd-after-reboot">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by spicynoodle** [comment]
Specify the correct url to genesis.json

**Comment by 89851258537** [comment]
I have same problem and I have correct path to genesis.json 
{"my->genesis_file.generic_string()":"/home/saa/eos/genesis.json","what":"basic_ios::clear: iostream error"}

**Comment by AuZhoomLee** [comment]
I have the same problem , and  it latest 3 days ,I couldn't find way to solve, Have you solve it yet?
And here's my error info:

2625208ms thread-0   main.cpp:115                  main                 ] 13 NSt8ios_base7failureB5cxx11E: basic_ios::clear: iostream error
basic_ios::clear: iostream error: error unpacking fc::sha256
    {"type":"fc::sha256","what":"basic_ios::clear: iostream error"}
    thread-0  raw.hpp:568 unpack
Error unpacking field previous
    {"field":"previous"}
    thread-0  raw.hpp:327 operator()
error unpacking eosio::chain::signed_block
    {"type":"eosio::chain::signed_block"}
    thread-0  raw.hpp:568 unpack

    {"my->genesis_file.generic_string()":"/home/aupieceslanden/project/eos/build/etc/eosio/node_00/genesis.json"}
    thread-0  chain_plugin.cpp:214 plugin_startup

**Comment by AuZhoomLee** [comment]
I find a way to solve it in #758, Mr. heifner give an effective command to run it again normally:
Please try to run `./eosd --resync !`
But refer to latest eosio version ,I recommend you change your `config.ini` (build/etc/eosio/node_00/),and run` ./nodeos` (/build/programs/nodeos/) or `./nodeos --resync `
