### ISSUE TITLE
build script on clean install has compiler detection error

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#7260]
When running the build script with no options on a fresh Ubuntu 18.04 install it builds the clang8 compiler. That is not expected without the -P option. The reason for this is due to a couple errors in the build script and ordering of detection.

The script has a couple logic defects that should probably be fixed like so:
```diff
--- a/scripts/eosio_build.sh
+++ b/scripts/eosio_build.sh
@@ -253,8 +253,8 @@ if [ $PIN_COMPILER ]; then
    BUILD_CLANG8=true
    CPP_COMP=${OPT_LOCATION}/clang8/bin/clang++
    CC_COMP=${OPT_LOCATION}/clang8/bin/clang
-elif $NO_CPP17; then
-   if [ $NONINTERACTIVE -eq 0 ]; then
+elif [ $NO_CPP17 ]; then
+   if [ $NONINTERACTIVE -eq 1 ]; then
       BUILD_CLANG8=true
       CPP_COMP=${OPT_LOCATION}/clang8/bin/clang++
       CC_COMP=${OPT_LOCATION}/clang8/bin/clang
```

But this doesn't fix the underlying problem: this compiler check happens before a compiler is possibly installed by the eosio_build_ubuntu.sh (or other platform) script. So by making this change above it will prompt users to install pinned compiler when a platform compiler would pass muster any other time.

But there's more: the eosio_build_ubuntu.sh script will end up installing gcc still. This means the next time the user runs the script with no options (as they probably would, since that's what they did the first time), the script will try doing a non-pinned build. And of course that won't work -- giving bizarre errors -- because you'd need to give a -f to switch between pinned vs nonpinned.

**Comment by spoonincode** [comment]
This error also seems to prevent eosio_build.sh from working on 16.04 when no arguments are passed

**Comment by NorseGaud** [comment]
I noticed the same with my tests in #7263... Strange... I'm collecting failure logs for each distro so we can swarm on what's causing it.

**Comment by spoonincode** [comment]
#7263 still has the faulty if statement I documented in this defect, that's why it too has problems

**Comment by NorseGaud** [comment]
There is a bit of a chicken and egg problem here. You can't compile cmake without clang/gcc-c++ installed, so you can't compile clang8. That's why the user is prompted that their version will not work and -y will answer yes to installing our clang8.

My script handles this by warning the user they've already installed eosio before they can proceed. Unless they just downloaded a newer version, there shouldn't be a reason someone would run it twice. Also, I'm using a new path structure with the version pulled from the CMakeLists file.

**Comment by NorseGaud** [comment]
@spoonincode Still an issue?

**Comment by spoonincode** [comment]
nah I think we should close this one
