### ISSUE TITLE
build script boost detection inconsistent and causes grief via not finding boost

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#7262]
Some users have experienced problems where despite the build script insisting that boost 1.67 has been built boost is either still not found by cmake or an old version is found. #7190 appears to be textbook case of this -- the script reports 1.67 is there yet cmake finds 1.58. I've also entertained more than one user on telegram having this issue.

The reason seems to be due to inconsistent usage of BOOST_ROOT and BOOST_LINK_LOCATION in the scripts. On a clean system with 1.7 the scripts work, but there must be cases maybe due to an upgrade from an old version where things get out of whack.

Here we can see how these two variables are defined:
https://github.com/EOSIO/eos/blob/448287d520f5f8c282139ecc60f227c218d42e82/scripts/eosio_build.sh#L46-L47
https://github.com/EOSIO/eos/blob/448287d520f5f8c282139ecc60f227c218d42e82/scripts/eosio_build.sh#L70-L71

The build script when deciding on if to build boost looks at (effectively) BOOST_LINK_LOCATION:
https://github.com/EOSIO/eos/blob/448287d520f5f8c282139ecc60f227c218d42e82/scripts/eosio_build_ubuntu.sh#L158-L159

However, it's BOOST_ROOT -- which is `$HOME/${SRC_LOCATION}/boost_${BOOST_VERSION}` which cmake will look at (via inspecting the environment variable BOOST_ROOT).

Thus, it is possible (and clearly happening in the wild) for someone to have boost in ~/opt/boost causing the script's check to pass, but not have boost in ~/src/boost_... causing cmake to not find it.

**Comment by NorseGaud** [comment]
@heifner We can change `$HOME/opt/boost` to use $BOOST_ROOT in the ubuntu script (and other scripts) to get 1.8.x fixed

**Comment by NorseGaud** [comment]
It looks as if 1.8.x is already using $BOOST_ROOT instead of $HOME/opt/boost. In the new build scripts under 7263, I've got it using BOOST_ROOT as well.

**Comment by taokayan** [comment]
I found this may be a solution:
in file ```eos/libraries/fc/CMakeModules/FindBoost.cmake```, apply this diff:

```
diff --git a/CMakeModules/FindBoost.cmake b/CMakeModules/FindBoost.cmake
index 4c37f5f..5d54484 100644
--- a/CMakeModules/FindBoost.cmake
+++ b/CMakeModules/FindBoost.cmake

@@ -458,6 +459,7 @@ else()
   # The user has not requested an exact version.  Among known
   # versions, find those that are acceptable to the user request.
   set(_Boost_KNOWN_VERSIONS ${Boost_ADDITIONAL_VERSIONS}
+    "1.67.0" "1.67" "1.57.0" "1.57"
     "1.56.0" "1.56" "1.55.0" "1.55" "1.54.0" "1.54"
     "1.53.0" "1.53" "1.52.0" "1.52" "1.51.0" "1.51"
     "1.50.0" "1.50" "1.49.0" "1.49" "1.48.0" "1.48" "1.47.0" "1.47" "1.46.1"
@@ -599,6 +601,7 @@ if(NOT Boost_INCLUDE_DIR)
       C:/boost/include
       C:/boost
       /sw/local/include
+      $ENV{HOME}/src
       )
   endif()
```

**Comment by spoonincode** [comment]
I'm going to close this. 1.8 changes the scripts so much it probably isn't affected (or if it is, in a completely different way)
