### ISSUE TITLE
fatal error in rex contract action!!! 

### ISSUE THREAD

**Issue by dawnFromDark** [EOSIO/eos#7292]
when i did not have any rex in my rex bucket,i did this action mvtosavings the result is following:

![image](https://user-images.githubusercontent.com/44474000/57276613-b98e5000-70d4-11e9-8085-0157e4725223.png)
and form that, all the rex action got error,even i did buy rex action! this was the memory access error!
![image](https://user-images.githubusercontent.com/44474000/57276624-c14df480-70d4-11e9-8c1d-d9c2d7e01e55.png)
i think you guys need to do something to solve this ,right?

**Comment by dawnFromDark** [comment]
does anybody here to solve this?????
i clean all the data from my server and the problem still exist,may you solve this?????

**Comment by dawnFromDark** [comment]
this is a critical problem ,right????

**Comment by taokayan** [comment]
Would you share your bootstrap steps to reproduce this issue?

**Comment by dawnFromDark** [comment]
i changed the server time to test this,firstly, i buyrex  and the quantity was "3000.0000 EOS", then i changed the timepoint to ten days later,then i bought rex again and the amount was "400.0000 EOS",and the next step was like the picture i showed,some one thought that i deployed the error system contract, but the system contract i deployed was this:https://github.com/EOSIO/eosio.contracts
and i test all process on nodeos version 1.6.5,no mistake happend on my server. therefore some mistake happend must happend on nodeos,because my nodeos that got error was version 1.7.3??
Then,i used the https://github.com/EOSIO/eosio.contracts system contract master branch,and cleaned all the data,the error did not  happend again.

i guess may be my system contract version was too old to math nodeos ?
