### ISSUE TITLE
build scripts will attempt to use outdated/unusable system cmake

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#7302]
The build scripts will prefer using the system provided cmake if one is found. But this preference happens even if the system provided cmake is too old to build eosio. For example installing the system provided 2.8 cmake on centos7 before running the build script will cause the build to error out part way through.

This is particularly quirky for users who have upgraded from pre-1.7 on 16.04 as the build scripts up through 1.6 still installed the system cmake!

**Comment by taokayan** [comment]
I can build eos release/1.8 using the following steps in a fresh ubuntu 16:

- manually download and install cmake 3.15:
```
wget https://github.com/Kitware/CMake/releases/download/v3.15.0-rc3/cmake-3.15.0-rc3.tar.gz
tar zxvf cmake-3.15.0-rc3.tar.gz 
cd cmake-3.15.0-rc3/
./configure
cmake
sudo make install
```

- download and install clang8 manually:
```
wget http://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
```

- make softlink of ```clang``` & ```clang++``` to the download clang binaries
- redirect ```g++``` & ```gcc``` to ```clang++``` & ```clang``` (important!)

in eos folder, run:
```
./scripts/eosio_build.sh
```

**Comment by an-ivannikov** [comment]
in  CMakeLists.txt add `cmake_policy(SET CMP0074 NEW)`

**Comment by an-ivannikov** [comment]
I think it's because of (-c Enable Code Coverage). 
I removed this option (-c) and the assembly continued successfully

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
