### ISSUE TITLE
userres table abi interface error with pure number acccount

### ISSUE THREAD

**Issue by HBrightShow** [EOSIO/eos#7314]
Our eos account was created with '1-5' and 'a-z'. So i created two account  123451234512 and plainuser111, next i used  following command to find my resource:
cleos  -u http://47.92.123.209:9008 get table eosio plainuser111 userres
cleos  -u http://47.92.123.209:9008 get table eosio 123451234512 userres

i can get resource information with plainuser111 ,but the other one 's resource information is empty. So is any different with two kinds of account,or it's a issue?   

of course, the information of userres table with 123451234512 is right, i can get it from my own contract

**Comment by jgiszczak** [comment]
This is a quirk of how data types are converted on the cleos command line and the fact that EOS.IO account names are fundamentally 64 bit integers, so cleos supports specifying them numerically.  To specify a name that's all digits, use `cleos -u http://47.92.123.209:9008 get table eosio " 123451234512" userres`.
