### ISSUE TITLE
STAT-180 ⁃ Launch a parallel testnet with 1 second per block

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#733]
As per Dan,

We need a new testnet configured with 1 sec per block and run it upto a million blocks.

ATC:

* Run eosd and watch output to see that a new block is produced once a second.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

* Default block interval changed to 1 sec.
    * Use ./eosd --resync --block-interval-seconds 3 to run with previous default.

  * Block interval made configurable via a command line or config.ini option to chain_plugin.

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

The eosd instance, without specifying the blok-interval-seconds generates block every second
68009ms thread-0   chain_controller.cpp:208      pushblock          ] initj #1116 @2017-11-22T09:02:48  | 0 trx, 0 pending, exectime_ms=1
168009ms thread-0   producer_plugin.cpp:244       block_production_loo ] initj generated block #1116 @ 2017-11-22T09:02:48 with 0 trxs  0 pending
169004ms thread-0   chain_controller.cpp:208      pushblock          ] inith #1117 @2017-11-22T09:02:49  | 0 trx, 0 pending, exectime_ms=0
169004ms thread-0   producer_plugin.cpp:244       block_production_loo ] inith generated block #1117 @ 2017-11-22T09:02:49 with 0 trxs  0 pending
170002ms thread-0   chain_controller.cpp:208      pushblock          ] initm #1118 @2017-11-22T09:02:50  | 0 trx, 0 pending, exectime_ms=0
170002ms thread-0   producer_plugin.cpp:244       block_production_loo ] initm generated block #1118 @ 2017-11-22T09:02:50 with 0 trxs  0 pending
1

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

Looks good as context switching among nodes happen every second. Blocks are being generated by the same node on every 21 seconds
397001ms thread-0   producer_plugin.cpp:244       block_production_loo ] initi generated block #2952 @ 2017-11-23T09:06:37 with 0 trxs  0 pending
409002ms thread-0   chain_controller.cpp:208      pushblock          ] initk #2953 @2017-11-23T09:06:49  | 0 trx, 0 pending, exectime_ms=0
411714ms thread-0   net_plugin.cpp:1132           connect              ] host: ip-10-160-12-231 port: 9876 
411716ms thread-0   net_plugin.cpp:1168           operator()           ] connection failed to ip-10-160-12-231:9876: Connection refused
414001ms thread-0   chain_controller.cpp:208      pushblock          ] initj #2954 @2017-11-23T09:06:54  | 0 trx, 0 pending, exectime_ms=0
418001ms thread-0   chain_controller.cpp:208      pushblock          ] initi #2955 @2017-11-23T09:06:58  | 0 trx, 0 pending, exectime_ms=0
418001ms thread-0   producer_plugin.cpp:244       block_production_loo ] initi generated block #2955 @ 2017-11-23T09:06:58 with 0 trxs  0 pending
430002ms thread-0   chain_controller.cpp:208      pushblock          ] initk #2956 @2017-11-23T09:07:10  | 0 trx, 0 pending, exectime_ms=0
435001ms thread-0   chain_controller.cpp:208      pushblock          ] initj #2957 @2017-11-23T09:07:15  | 0 trx, 0 pending, exectime_ms=0
439001ms thread-0   chain_controller.cpp:208      pushblock          ] initi #2958 @2017-11-23T09:07:19  | 0 trx, 0 pending, exectime_ms=0
439001ms thread-0   producer_plugin.cpp:244       block_production_loo ] initi generated block #2958 @ 2017-11-23T09:07:19 with 0 trxs  0 pending

**Comment by heifner** [comment]
Verified by QA.
