### ISSUE TITLE
I found an incomprehensible key error case.

### ISSUE THREAD

**Issue by kimhyukdong** [EOSIO/eos#7349]
I'm not good at English. Please understand.
I made Web wallet by eosjs(16.0.9), eosio(1.6.3) on Ubuntu 18.04.  
It is a structure to trade tokens using the Web.

but, I found an incomprehensible key error case.
Despite the difference in the ending digit of the private key,  A Token transfer to the other user.

For example, If my private key number is "....................bZV5K9SqseNwxMSa**4**",  "....................bZV5K9SqseNwxMSa**1**" is also transmitted.

This error only occurs in ending digit of private key.

It only happens to a few users.

Fortunately, Cleos is not found in that case

Thanks your advise.

**Comment by johndebord** [comment]
Could you please provide a step-by-step process to reproduce this error?
I'm unable to determine exactly what you are trying to explain without any context.

**Comment by jgiszczak** [comment]
The last 4 bytes of an EOS private key expressed in binary are the first 4 bytes of the ripemd160 hash of the key material.  Expressed in base58, this is the last 6 characters.  If the code you are using to sign transactions does not validate the key checksum, errors in the last few bytes of the key will be ignored.  Errors in the key checksum do not affect the integrity of the resulting signatures.  It does mean that if the key itself is corrupted that will go undetected until a signature validation is attempted, which will fail.
