### ISSUE TITLE
ensure state chainbase is dirty if exiting due to error that leaves state in inconsistent state

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#7361]
Some exceptions can cause nodeos to shut down but leave the state chainbase in an inconsistent state. Other ones, like a `database_guard_exception`, will cause nodeos to shutdown in a consistent state.

A new function should be added to chainbase to put it into a mode where it expects to shutdown in a dirty way. When in this mode, certain database operations (like commit or creating a session) are free to abort since the developers should not be doing such operations when chainbase is put into this mode. But the main purpose of this mode is to not reset the dirty flag to false in the destructor of chainbase.

When an exception that will shutdown nodeos leaving the state chainbase in a consistent mode  is encountered, the new function should not be called because it is desirable for the state chainbase to not be dirty after shutdown. However, if other exceptions are encountered which will shutdown nodeos and likely leave it in an inconsistent mode, then the new function should be called.

For example in `controller_impl::replay`, we should catch all exceptions (other than `database_guard_exception`) in the code that replays irreversible blocks, then call the function to force the state chainbase to stay dirty, and then rethrow the exception. This will properly handle the situation during replay of irreversible blocks where an unexpected exception can cause nodeos to shutdown leaving the state chainbase in an inconsistent state.

**Comment by ndcgundlach** [comment]
This may be a dup.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
