### ISSUE TITLE
EOS mainnet replay speed too slow after syncing about 20M blocks

### ISSUE THREAD

**Issue by hamza-kakar** [EOSIO/eos#7375]
while replay the nodeos sync speed was fast in start but after about syncing 20M blocks the speed is very very slow.

> mongoDb and history plugins are enabled.

nodeos is not utilizing above 1500 iops while the server iops limit is above 20k.

server specs:

- CPU: Intel Xeon 3.2Ghz * 8.
- RAM: 32GB
- SSD: 1TB
- IOPS: ~20000

server `iostats`:

![image](https://user-images.githubusercontent.com/24855220/57902764-43cc7600-7884-11e9-8ba7-54d9efbf3f92.png)

> any suggestions on how i can boost the replay.?

**Comment by matthewdarwin** [comment]
The blocks after 20 are much larger than the ones before.   To get the fastest replay speed, you need the fastest available CPU core for a single thread performance.  O/S and/or BIOS settings tuning may also help.

This is probably not the place to discuss tuning as there is no issue per se.

**Comment by spoonincode** [comment]
As Matthew says the first 20MM are simply easier to process than post 20MM. I don't believe there is anything actionable here so closing this.
