### ISSUE TITLE
Port db_modes_test to Python test framework

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#7386]
The db_modes_test has been very unstable on Mac. This is likely because it takes a much longer time to start up nodeos on Mac and the db_modes_test.sh script just waits for a few seconds before proceeding forward with the assumption that it has started up.

We would like to make the test more robust by actually polling (with reasonable timeouts) for signals that nodeos has actually successfully started up. For example, by enabling the `eosio::chain_api_plugin` and polling `get_info` until the testing script gets back a successful response.

Building it support for this into the existing bash script will require recreating code that is already in place in the Python testing framework. So instead, we would like to port over that test to the Python testing framework and making it more robust in the process.

Note that using `eosio::chain_api_plugin` as a mechanism to make the `db_modes_test` more robust will make it non-parallelizable (at least until the Python testing framework is updated to force usage of different port numbers to avoid conflicts) and so the ported over test should have the `nonparallelizable_tests` label.

**Comment by heifner** [comment]
Resolved by #7390
