### ISSUE TITLE
While trying to submit action from the browser received error many times "Failed To Fetch"

### ISSUE THREAD

**Issue by atulatul** [EOSIO/eos#7388]
I tried to use the dist-web js to create a web app and when I tried to submit the action using api.transact I receive various error messages.
Sometimes it works well but most of the time I receive exceptions "failed to fetch" and could not retireve abi.
While rpc_get_table_rows always works fine.

**Comment by andriantolie** [comment]
This question is better posted in https://github.com/EOSIO/eosjs/issues

**Comment by andriantolie** [comment]
I try to reproduce your issue. The only time I will see "failed to fetch" is when my nodeos doesn't have cors enabled. You can configure the cors by using the --access-control-allow-origin option on nodeos. Once I configure it properly, I don't have any problem using the api.transaction of eosjs dist-web.

I'm going to close this issue as this is not related to eos core software, but more to the eosjs. If you still encounter the problem I would suggest you to post it in https://eosio.stackexchange.com. Or if you think it is an issue in the eosjs software itself, please post it in  https://github.com/EOSIO/eosjs/issues. Thanks.

**Comment by atulatul** [comment]
> I try to reproduce your issue. The only time I will see "failed to fetch" is when my nodeos doesn't have cors enabled. You can configure the cors by using the --access-control-allow-origin option on nodeos. Once I configure it properly, I don't have any problem using the api.transaction of eosjs dist-web.
> 
> I'm going to close this issue as this is not related to eos core software, but more to the eosjs. If you still encounter the problem I would suggest you to post it in https://eosio.stackexchange.com. Or if you think it is an issue in the eosjs software itself, please post it in https://github.com/EOSIO/eosjs/issues. Thanks.


Many thanks for your verification. Although I have also the cors enabled in my setup for nodeos but still many times I see failed to Fetch error only sometimes actions work well.
Can you please provide your way you added the cors enabled for nodeos.

**Comment by andriantolie** [comment]
For my local setup, I just use the wildcard `nodeos --access-control-allow-origin "*"` for convenience (only for development, not advised for production).

And also, you might want to check if you are querying http://localhost:8888 or http://127.0.0.1:8888  using eosjs. You should use the latter to pass the http-validate-host check on nodeos (unless you use --http-validate-host false option on nodeos which will disable the validation, but this option is also not advised for production)
