### ISSUE TITLE
Some questions about deferred transaction

### ISSUE THREAD

**Issue by hadg** [EOSIO/eos#7393]
1. Is it possible to judge whether a transaction is a deferred transaction based on the transaction id?
2. Can I know from the transaction id whether the transaction created a deferred transaction and get the deferred transaction ID it created?
3. If a transaction is a deferred transaction, can I get the transaction that created the transaction?

I looked at the rpc documentation of eos, but I didn't find an interface to solve the above problem. Only one interface can get the list of unexecuted deferred transactions. Is there a way to solve the above problem? The method may not be limited to the rpc protocol.

**Comment by andriantolie** [comment]
1. The way transaction id is generated is by taking the sha256 of the transaction. So theoretically, you won't be able to differentiate the transaction with the transaction id alone.
2. Similar to no 1
3. I don't think there's a link between a deferred transaction with the generation transaction in the transaction/ trace/ chain state. If a consensus upgrade happens in the future, you might be able to see the generating transaction id by checking the generated transaction context of the deferred transaction https://github.com/EOSIO/eos/issues/6115
