### ISSUE TITLE
Empty account list

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eos#7395]
if I run `cleos get accounts $PK` I get the Json below:

>{
>  "account_names": []
>}

so there are no accounts.  good.  now I want to create one:

`cleos create account eosio $ACCT $PK $PK`

which results in:

> Error 3050001: Account name already exists
> Error Details:
> Cannot create account named ********, as that name is already taken
> pending console output: 

clearly the `get accounts` is broken.  incidentally, my wallet is open and unlocked and I'm running the stable v1.7.3 on OSX

**Comment by ekkis** [comment]
to reproduce the issue, grab the script https://gist.github.com/ekkis/e2220ed8447196bb2fd87bd9b5a993fc and run it without parameters

it expects an ACCT environment variable for the user account it needs to create and you may want to edit the second line where it specifies where logs, data and config directories will go

the idea is the script is *idem potent* so run it a second time and it should work just as well.  to start from scratch I'll often do `./run stop; rm ~/eosio-wallet; ./run`

**Comment by ekkis** [comment]
one other thing: please note that though `cleos get accounts $PK` comes back empty, `cleos get account $ACCT` actually returns the account, the most telling piece of evidence that cleos is broken

**Comment by ekkis** [comment]
in continuing to test, I'm also getting these errors from `get account`:

> error 2019-05-24T06:36:49.909 thread-0  main.cpp:3899                 main                 ] Failed with error: unspecified (0)
> unknown key (boost::tuples::tuple<bool, eosio::chain::name, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>): (0 user2)

**Comment by shabbir-bblab** [comment]
> in continuing to test, I'm also getting these errors from `get account`:
> 
> > error 2019-05-24T06:36:49.909 thread-0  main.cpp:3899                 main                 ] Failed with error: unspecified (0)
> > unknown key (boost::tuples::tuple<bool, eosio::chain::name, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>): (0 user2)

I'm also getting same error when querying get_account from curl or browser but if do this from cleos it gives result.
Kindly provide a solution .

**Comment by jgiszczak** [comment]
> one other thing: please note that though `cleos get accounts $PK` comes back empty, `cleos get account $ACCT` actually returns the account, the most telling piece of evidence that cleos is broken

`cleos` is not broken.  The `get accounts` API depends on history_plugin.  If history_plugin is not enabled, or was not enabled at the time the key in question was used, it will return no results.  `get account` does not depend on history_plugin.

To see exactly which APIs cleos is using, add `--print-request` to the command line.  Here is an example:
```bash
$ cleos --print-request get accounts EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
REQUEST:
---------------------
POST /v1/history/get_key_accounts HTTP/1.0
Host: localhost:8888
content-length: 75
Accept: */*
Connection: close

{
  "public_key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"
}
```
Note the URL starts with `/v1/history`.  Everything with that URL prefix is deprecated and very few nodes on major EOS networks enable it anymore.  It was unable to scale appropriately.

Here is what `get account` does:
```bash
$ cleos --print-request get account eosio
REQUEST:
---------------------
POST /v1/chain/get_account HTTP/1.0
Host: localhost:8888
content-length: 29
Accept: */*
Connection: close

{
  "account_name": "eosio"
}
```
Note the `/v1/chain` prefix on the API.  This query requires chain_api_plugin to be enabled, which is ordinarily readily available.

You should use `get account` and should not use `get accounts` at all.  Its availability is rapidly approaching zero on all but trivial testnets.

**Comment by jgiszczak** [comment]
> > in continuing to test, I'm also getting these errors from `get account`:
> > > error 2019-05-24T06:36:49.909 thread-0  main.cpp:3899                 main                 ] Failed with error: unspecified (0)
> > > unknown key (boost::tuples::tuple<bool, eosio::chain::name, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>): (0 user2)
> 
> I'm also getting same error when querying get_account from curl or browser but if do this from cleos it gives result.
> Kindly provide a solution .

That is the response you will get when `user2` does not exist.  It is the expected error, though admittedly not very readable or user-friendly.  Both curl and cleos will fail to fetch any information about a nonexistent account.  If cleos is succeeding but curl is failing, check your curl syntax.  The equivalent of the `cleos get account eosio` command above is:
```bash
$ curl localhost:8888/v1/chain/get_account -d '{"account_name":"eosio"}'
```

**Comment by ekkis** [comment]
if `get accounts` is deprecated, then what is the recommended way to get a list of accounts? alternatively, how can I determine if an account exists so that if it doesn't, I can create it?

**Comment by jgiszczak** [comment]
`get_account`, no 's', is supported.  That tells you if an account exists or not.  If the account doesn't exist, you'll get the rather horrible error mentioned by shabbir-bblab that you also saw.

**Comment by ekkis** [comment]
good enough thanks.  I can do `2> /dev/null; echo $?`

**Comment by tbfleming** [comment]
I'd stay away from shell vodoo like that one. There are many errors; you need to distinguish between account not found and the others, such as failure to connect.

**Comment by ekkis** [comment]
what do you recommend for automation then?

**Comment by tbfleming** [comment]
A language such as JS or Python which knows how to talk to http APIs.

**Comment by ekkis** [comment]
ok.  makes sense.  I should just switch since I'm doing all this stuff in Js/Mocha for tests anyway
