### ISSUE TITLE
cleos -j missing from multiple commands

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#7397]

**Comment by arhag** [comment]
We can divide the cleos sub-commands into: 1) those that are not expected to output a JSON to console; 2) those that always write their output in JSON format; 3) those that should provide the user with an option (via the `-j` flag) to write the output in JSON format.

Within the third category, I have only identified `get currency balance` as the sub-command that doesn't provide a `-j` flag when it should.

**Comment by tbfleming** [comment]
A common case is to combine -d and -j to see what cleos would send across the network. Especially useful for people to see how to use apis and system contract actions.

**Comment by andriantolie** [comment]
PR is merged. I'm closing this issue
