### ISSUE TITLE
Supported version must be between 2 and 2 inclusive

### ISSUE THREAD

**Issue by huachao0326** [EOSIO/eos#7398]
wget https://github.com/EOSIO/eos/releases/download/v1.8.0-rc2/eosio-1.8.0-rc2.el7.x86_64.rpm
sudo yum install eosio-1.8.0-rc2.el7.x86_64.rpm
nodeos --genesis-json genesis.json
nodeos --delete-all-blocks --snapshot snapshots/snapshot-038fbd95fc268eec34ea53b1903935fa871d95934754988119e4a39204e86
bdc.bin
error 2019-05-24T03:34:54.609 nodeos    main.cpp:120                  main                 ] 3240001 snapshot_validation_exce
ption: Snapshot Validation Exception
Unsupported version of chain snapshot: 1. Supported version must be between 2 and 2 inclusive.
    {"version":1,"min":2,"max":2}
    nodeos  chain_snapshot.hpp:31 validate

    {}
    nodeos  chain_plugin.cpp:989 plugin_startup

**Comment by matthewdarwin** [comment]
It looks to me like you're using a snapshot from version 1.7 or earlier.  These are not compatible with 1.8

**Comment by spoonincode** [comment]
Matthew is correct -- snapshots pre-1.8 cannot be loaded in 1.8. The wording for this error is a little wonky but for 2.0.0 this will be "between 2 and 3" so not worth changing the wording at this point either.

**Comment by zsq978663747** [comment]
why the snapshot doesn't compatible with 1.8?have any other ideal to solve this?

**Comment by matthewdarwin** [comment]
Please review the 1.8 release candidate release notes.

You should get  a snapshot created on version 1.8.

**Comment by bing-deng** [comment]
eos1.8 snapshots download from https://snapshots.eossweden.org/
