### ISSUE TITLE
1.8+ performance regression on 18.04 when using build script's default options

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#7402]
Pre-1.8 the build script on 18.04 used clang 4.0 as the compiler. 1.8+ uses gcc 7. gcc seems to really struggle with wabt and this causes a serious performance regression for users who use the default build script options.

I measured a popular benchmarking contract on a 9600k with a core forced to C0 (4.6Ghz). The execution time was:

compiler | execution time
------------ | -------------
clang 8 | 1.2ms
gcc 8 | 1.7ms
gcc 7 | 1.8ms
clang 6 | 1.2ms

We need to seriously consider using the system's clang compiler instead of gcc. For ubuntu 18.04 this means clang6, for amz2 this means clang7, and for rhel7 clones this may possibly mean clang5 (there are new versions of clang available from RH but the centos software collections have not surpassed 5.0).

Obviously users who use the pinned build script option are not affected since they get clang8.

**Comment by NorseGaud** [comment]
I've added a nice little warning/prompt for this in bats changes.
