### ISSUE TITLE
cleos should only attempt to start keosd when the sub-command requires access to keosd

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#7406]
If a cleos sub-command does not require access to keosd, e.g. `cleos sign`, it should not attempt to start keosd.

**Comment by andriantolie** [comment]
With the modification for #7407, `cleos sign` might need to use keosd.

I checked the list of cleos commands, which are:
- version - x
- create - `key` subcommand require keosd
- convert - x
- get - x
- set - require keosd
- transfer - require keosd
- net - x
- wallet - require keosd
- sign - require keosd after modification for #7407
- push - require keosd
- multisig - except for `review` subcommand, the others require keosd
- wrap - require keosd
- system - except for `listproducers`, `listbw`, `bidnameinfo` subcommand, the others require keosd

The existing codebase has prevented keosd from starting except for `convert` and `multisig review`, I've opened PR #7432 for this

**Comment by heifner** [comment]
Resolved by #7432
