### ISSUE TITLE
cleos sign should allow signing with keosd

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#7407]
The `cleos sign` command currently provides two ways to sign a transaction:
1. Pass in the private key directly as a command-line argument with the `-k` option.
2. Avoid the `-k` option in which case cleos will prompt the user the enter in the private key (it won't be visible in the terminal).

It should be possible to pass in the public key (corresponding to the private key to sign with) as a command line option which would trigger cleos to request the corresponding private key from keosd.

**Comment by andriantolie** [comment]
PR #7430 is created for this

**Comment by heifner** [comment]
Resolved by #7430
