### ISSUE TITLE
cleos option to direct generated transaction output to a file

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#7408]
Many cleos actions generate transactions and/or retrieve transaction traces. These are currently output to the standard output potentially along with other messages for the user. A script that may only be interested in getting the transaction (or transaction trace) alone needs a reliable way to get the data relevant to it. So cleos should provide an option to instead output the transaction data to a file specified through the command line option.

In addition, with such an option available cleos has more freedom to output helpful error messages to the standard output to convey whether the requested operation was successful. For example, `cleos sign` with this output option provided could output a message informing the user that the transaction was successfully signed and the signed transaction was output to the specified path.

**Comment by heifner** [comment]
Resolved by #7425
