### ISSUE TITLE
Problem installing deb libicu60 unavailable

### ISSUE THREAD

**Issue by str** [EOSIO/eos#7415]
I tried to install the EOSIO v1.8.0-rc2  / eosio_1.8.0-rc2-ubuntu-18.04_amd64.deb and got the following dependencies missing:
- libicu60 unavailable
- libtinfo5 unsatisfied

When installing I got:

```
dpkg: dependency problems prevent configuration of eosio:
 eosio depends on libicu60; however:
  Package libicu60 is not installed.
 eosio depends on libtinfo5; however:
  Package libtinfo5 is not installed.

dpkg: error processing package eosio (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 eosio

```

I'm using Ubuntu 19.04

**Comment by spoonincode** [comment]
At the current time we're only supporting the LTS releases 16.04 and 18.04 with binaries
