### ISSUE TITLE
I NEED HELP!!! Why do I get an error assertion message "invalid tokenin operation" when I sell ram?

### ISSUE THREAD

**Issue by ashuralyk** [EOSIO/eos#7429]
the command operation is "**cleos -u https://geo.eosasia.one system sellram aaasportsnba 1024**"
but the response is odd:
**Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: invalid tokenin operation
pending console output:** 

my other accounts on the mainnet and jungle testnet are fine, but the problem is only happened on this "aaasportsnba" account, so weird.

ps: this account is not mine, and I only have its active permission, and this account's owner permission is not same as its active permission. I'm not sure if this affect its sellram operation.

![image](https://user-images.githubusercontent.com/3871265/58522973-305eca80-81f5-11e9-9e25-9f4bbcf8e1e5.png)
![image](https://user-images.githubusercontent.com/3871265/58523010-53897a00-81f5-11e9-86d9-401c12fc3c3c.png)

**Comment by andriantolie** [comment]
Hi @ashuralyk, I checked the eosio.system contracts in the mainnet and it doesn't have the above error message that you shared. eosio's sellram action is going to trigger inline action to eosio.token transfer, and eosio.token transfer is going to notify both the sender and recipient of the transfer. I checked aaasportsnba account in the mainnet and it has a contract deployed to it, so I suspect that the above error message is being emitted by aaasportsnba smart contract which reacts to the eosio.token transfer action.

By the way, owner permission and active permission is advisable not to be the same for security. This shouldn't affect the sellram operation.
