### ISSUE TITLE
STAT-188 ⁃ Restart of eosd with transactions in reversible blocks causes problems

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#743]
When restarting eosd without --resync-blockchain or --replay-blockchain, eosd will fail to get back in sync because it is trying to create transaction_history_object objects that already exist. This will result in exceptions in the log of "could not insert object, most likely a uniqueness constraint was violated".

This only happens if the transactions are in the reversible portion of the blockchain when the process is killed.

ATC

This is probably best tested on a local network.
Bring up a multi-node network.
Perform some activities on the network.
Kill on of the nodes (kill <pid>)
Restart the killed node without either of --resync-blockchain or --replay-blockchain.
Verify that the nodes come back into sync
Verify that things are functional by performing more activities.

**Comment by heifner** [comment]
Verified by QA.
