### ISSUE TITLE
Enhance error message for cleos command which can either interpret the JSON string itself or as path to the JSON file

### ISSUE THREAD

**Issue by andriantolie** [EOSIO/eos#7435]
When cleos receives a string that can be interpretted either as a JSON string itself or a path to a file containing the JSON, cleos gives unhelpful error messages to indicate which was the case.

**Comment by andriantolie** [comment]
For example (transfer.json contains a transaction with missing bracket and transfer.jso doesn't exist)

cleos push transaction transfer.jso
error 2019-05-30T08:35:06.951 thread-0  main.cpp:3449                 main                 ] Failed with error: Bad Cast (7)
Invalid cast from type 'string_type' to Object
Failed to deserialize variant

cleos push transaction transfer.json
error 2019-05-30T08:38:53.822 thread-0  main.cpp:3449                 main                 ] Failed with error: Bad Cast (7)
Invalid cast from type 'string_type' to Object
Failed to deserialize variant

**Comment by tbfleming** [comment]
Better: make the selection between json and filename explicit. cleos shouldn’t guess argument types.

**Comment by andriantolie** [comment]
Good idea

**Comment by andriantolie** [comment]
@tbfleming

I was thinking of making the selection explicit by adding -f option to explicitly say that the passed parameter is a filename, otherwise, it's a JSON string.

But after some thought, if we go this way, I think this might break the existing scripts/ tools that are currently being used by the EOSIO developers which have the assumption that the command works with either filename/ JSON string. For backward compatibility, perhaps it's better to keep the behavior the same

**Comment by andriantolie** [comment]
Done with #7442
