### ISSUE TITLE
Will CRDT be helpful to EOS?

### ISSUE THREAD

**Issue by coolspeed** [EOSIO/eos#745]
CRDT is quite a new technology (theory) in Distributed Computing realm. It's born in 2011!

> In distributed computing, a **conflict-free replicated data type (CRDT)** is a data structure which can be replicated across multiple computers in a network, where the replicas can be updated independently and concurrently without coordination between the replicas, and where it is always mathematically possible to resolve inconsistencies which might result.
> 
> The CRDT concept was formally defined in 2011 by Marc Shapiro, Nuno Preguiça, Carlos Baquero and Marek Zawirski. Development was initially motivated by collaborative text editing and mobile computing. CRDTs have also been used in online chat systems, online gambling, and in the SoundCloud audio distribution platform. The NoSQL distributed databases Redis and Riak have CRDT data types.

https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type

I think it can be helpful in addition to domain oriented sharding.

Of course, it's priority is obviously lower than the domain (per DApp) sharding. But if it comes into our vision, we will have more options. And it will help us make a plan for a longer future.

**Comment by wanderingbort** [comment]
Never say never, but in the context of a deterministic block-chain I don't see CRDTs becoming something we use at the chain level.  

CRDTs are a way of restoring consistency on a fine grain in a system with an AP system.  After all, if there was no way to get an inconsistent result (Strong C) then there wouldn't be a need for a CRDT.   

If we only look at irreversibile blocks in EOS.IO, what we actually have is a CA system.   In the event of a network partition, the system is still consistent and available, but it may not be able to "proceed" (if you are in the partition with less than 2/3 + 1 producers).  Pedantically, if you are partitioned from everyone and have no local copy we are not actually "available" but, assuming your local machine has any irreversible block chain data its available and consistent.   In that system, everything is made consistent at the chain level, that is after all the point of the chain, to build consensus over state of the chain.

Maybe, we could classify the part of the chain which is still reversible as a "CRDT" itself, after all its a data type that resolves conflicts in a distributed way once a network partition clears up. 

This has been fun, but I think I'm going to close the issue.  For theoretical discussions I encourage you to reach out to us on telegram: https://t.me/joinchat/EgOVjkPktgfUS3kt14FStw
