### ISSUE TITLE
How can I set up testnet to use the CLI Wallet API?

### ISSUE THREAD

**Issue by joluan** [EOSIO/eos#7471]
I am in this section of https://docs.decent.ch/Testnets/index.html?fbclid=IwAR2hBlKpbw6jU6Ep3OowJs1uhorpY8sq9fHqNiHiUDo4B2j9dyOwsW3iIQg

but I don't know how to Synchronize the Public Testnet Locally
I dont know how to coneect the files from my local pc to the git hub 
/home/my-testnet-folder.

could you explain me from the begining how to connect and where to find those folders /home/my-testnet-folder. are there from my c: root ?

**Comment by jgiszczak** [comment]
Windows is not supported.  I see no sign that DCore has additional Windows support unique to them, either.  You need to use Linux or macOS.

If you still have problems and wish to discuss them further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by joluan** [comment]
thanks for your reply  jgiszczak , but actually is not for using EOS.IO Beta, I just want to install DCore DECent in my windows system to be able to use the API of CLI wallet and can edit the interface of https://testnet-wallet.dcore.io/ 
any suggestion, how to setp up my testnet to be able to edit the GUI
