### ISSUE TITLE
test_cypher_suites ubuntu 18.04 build failure due to lack of pthread linkage

### ISSUE THREAD

**Issue by NorseGaud** [EOSIO/eos#7490]
https://buildkite.com/EOSIO/eosio-base-images/builds/213#59c398c5-7a92-4000-bf87-6e0727ec499f

```
[ 91%] [32mBuilding CXX object libraries/chain/CMakeFiles/eosio_chain.dir/chain_id_type.cpp.o[0m

/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':

(.text+0x16): undefined reference to `pthread_atfork'

clang: [0;1;31merror: [0mlinker command failed with exit code 1 (use -v to see invocation)[0m

libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/build.make:113: recipe for target 'libraries/fc/test/crypto/test_cypher_suites' failed

make[2]: *** [libraries/fc/test/crypto/test_cypher_suites] Error 1

CMakeFiles/Makefile2:783: recipe for target 'libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all' failed

make[1]: *** [libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all] Error 2
```

**Comment by NorseGaud** [comment]
I'm also getting this on 1.6.x: 

```
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':
(.text+0x16): undefined reference to `pthread_atfork'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/build.make:113: recipe for target 'libraries/fc/test/crypto/test_cypher_suites' failed
make[2]: *** [libraries/fc/test/crypto/test_cypher_suites] Error 1
make[2]: Leaving directory '/root/eos/build'
CMakeFiles/Makefile2:783: recipe for target 'libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all' failed
make[1]: *** [libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by n8d** [comment]
Same issue here on a fresh Ubuntu 18.04 system.

**Comment by dconry** [comment]
Ran into this today also.  I think this may be tied to openssl 1.1.0 -> 1.1.1 on Ubuntu 18, along with location of pthread_atfork() def...  there are add'tl details in the following external issue:

https://github.com/nanomsg/nng/issues/956

**Comment by meenxio** [comment]
just add --pthread options while compiling the sub-project

**Comment by taokayan** [comment]
I can build it by making the following change to eos/libraries/fc/CMakeLists.txt:
```
~/eos1.6/eos/libraries/fc$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8056cf0..efb09db 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -157,7 +157,7 @@ IF(APPLE)
   find_library(security_framework Security)
   find_library(corefoundation_framework CoreFoundation)
 ENDIF()
-target_link_libraries( fc PUBLIC ${LINK_USR_LOCAL_LIB} ${Boost_LIBRARIES} ${OPENSSL_LIBRARIES} ${ZLIB_LIBRARIES} ${PLATFORM_SPECIFIC_LIBS} ${RPCRT4} ${CMAKE_DL_LIBS} ${rt_library} ${readline_libraries} ${ECC_LIB} ${security_framework} ${corefoundation_framework} )
+target_link_libraries( fc PUBLIC ${LINK_USR_LOCAL_LIB} ${Boost_LIBRARIES} ${OPENSSL_LIBRARIES} ${ZLIB_LIBRARIES} ${PLATFORM_SPECIFIC_LIBS} ${RPCRT4} ${CMAKE_DL_LIBS} ${rt_library} ${readline_libraries} ${ECC_LIB} ${security_framework} ${corefoundation_framework} pthread )
 
 
 SET(OPENSSL_CONF_TARGET )
```

**Comment by zer0blockchain** [comment]
> I can build it by making the following change to eos/libraries/fc/CMakeLists.txt:
> 
> ```
> ~/eos1.6/eos/libraries/fc$ git diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index 8056cf0..efb09db 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -157,7 +157,7 @@ IF(APPLE)
>    find_library(security_framework Security)
>    find_library(corefoundation_framework CoreFoundation)
>  ENDIF()
> -target_link_libraries( fc PUBLIC ${LINK_USR_LOCAL_LIB} ${Boost_LIBRARIES} ${OPENSSL_LIBRARIES} ${ZLIB_LIBRARIES} ${PLATFORM_SPECIFIC_LIBS} ${RPCRT4} ${CMAKE_DL_LIBS} ${rt_library} ${readline_libraries} ${ECC_LIB} ${security_framework} ${corefoundation_framework} )
> +target_link_libraries( fc PUBLIC ${LINK_USR_LOCAL_LIB} ${Boost_LIBRARIES} ${OPENSSL_LIBRARIES} ${ZLIB_LIBRARIES} ${PLATFORM_SPECIFIC_LIBS} ${RPCRT4} ${CMAKE_DL_LIBS} ${rt_library} ${readline_libraries} ${ECC_LIB} ${security_framework} ${corefoundation_framework} pthread )
>  
>  
>  SET(OPENSSL_CONF_TARGET )
> ```

This worked for me. I made the change and created a patch using `git diff` and apply it using a `patch` cmd.

EOSIO v1.6.0
EOSIO.CDT v1.6.0

```
git clone --recursive https://github.com/eosio/eos --branch v1.6.0 --single-branch
git clone --recursive https://github.com/eosio/eosio.cdt --branch v1.6.0 --single-branch
```

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
