### ISSUE TITLE
cleos get contract assert exception message

### ISSUE THREAD

**Issue by danX-4q** [EOSIO/eos#7491]
in my contract, use eosio_assert exception with message xxxx.
when i use cleos push action ... raise the exception, but console only show `Error 3050003: eosio_assert_message assertion failure`, which is without message xxxx.
as the result, my dapp can't give correct message to its user.

**Comment by andriantolie** [comment]
Hi @danX-4q, if you want to see the whole error message, you will need to start your nodeos with `verbose-http-errors` set to true. You can either set it up in your config.ini or pass it as cli argument when starting nodeos.

**Comment by andriantolie** [comment]
@danX-4q how's it going?

**Comment by danX-4q** [comment]
@andriantolie 
it's ok!
thanks.
