### ISSUE TITLE
can't run eos on docker

### ISSUE THREAD

**Issue by jimmywhylove** [EOSIO/eos#7511]
Docker version 18.09.2, build 6247962

when I run "docker build . -t eosio/eos",it show error:"Sending build context to Docker daemon  29.18kB
Step 1/16 : FROM eosio/builder as builder
pull access denied for eosio/builder, repository does not exist or may require 'docker login'"

I have already login!

**Comment by tbfleming** [comment]
Docker images were deprecated in 2018 then removed in 2019. We recommend the binary releases instead.
