### ISSUE TITLE
Build failed Ubuntu 18.04.2 LTS (Windows 10)

### ISSUE THREAD

**Issue by younhajo88** [EOSIO/eos#7524]
How do I fix the problem?

Build failed Ubuntu 18.04.2 LTS

![fail](https://user-images.githubusercontent.com/39249723/59890697-1340a480-940d-11e9-8d71-0435e77706f8.png)

**Comment by spoonincode** [comment]
Can you try the `develop` branch? I believe this issue is fixed there and I want to be sure before potentially backporting the fix.

**Comment by NorseGaud** [comment]
Develop looks to have the issue https://buildkite.com/EOSIO/eosio-base-images/builds/272

**Comment by taokayan** [comment]
Please see https://github.com/EOSIO/eos/issues/7490

**Comment by spoonincode** [comment]
> Develop looks to have the issue https://buildkite.com/EOSIO/eosio-base-images/builds/272

I don't see anything in that build related to this issue?

**Comment by NorseGaud** [comment]
Sorry, posted to the wrong issue; ignore me

**Comment by spoonincode** [comment]
closing as dupe of #7490
