### ISSUE TITLE
EOS build problem on Mac that may be related to Clang

### ISSUE THREAD

**Issue by aaron-fu-block-one** [EOSIO/eos#7526]
Encountered a problem when trying to to build EOS on macOS Mojave (version 10.14.5).

The EOS version was the latest develop branch with commit `405dce4b71f6ff26ec1bc6069a8fb6bba814b835`.

**Problem**

I started with running `~/eos/scripts/eosio_build.sh` and confirmed to build at `~/eosio/1.9/`.

The script terminated prematurely. The last line shown on the screen was

```
 - HomeBrew installation found @ /usr/local/bin/brew
```

With the help of `echo`, I managed to narrow down the problem -- the script stopped at `function ensure-compiler()` in `~/eos/scripts/helpers/eosio.sh`.

The exact line at which the script stopped was

```bash
COMPILER_TYPE=$( eval $READLINK_COMMAND $(which $CXX) )
```

**Workaround**

Later I acquired a copy of the pre-built binaries of LLVM 8.0.0 from the official website. Then I moved the unzipped clang+llvm folder (renamed to `clang8`) to `/usr/local/`, and made a symbolic link from `~/eosio/1.9/opt/clang8` to it.

After this step, the building process seemed to be normal: It downloaded Boost, and started to compile, and ended reporting `EOSIO has been successfully built`.

**Comment by NorseGaud** [comment]
This was fixed in 
https://github.com/EOSIO/eos/pull/7525
https://github.com/EOSIO/eos/pull/7528

**Comment by NorseGaud** [comment]
Whoops, didn't mean to close. Please let me know if the new changes resolved it for you.

**Comment by aaron-fu-block-one** [comment]
Yes. It is fixed.

Previously the `eosio_build.sh` script stopped after printing

```
- HomeBrew installation found @ /usr/local/bin/brew
```

Now the script continues to print

```
[Ensuring HomeBrew dependencies]
 - cmake found!
 - graphviz found!
 - libtool found!
 - automake found!
 - wget found!
 - gmp found!
 - llvm@4 found!
 - pkgconfig found!
 - python found!
 - python@2 found!
 - doxygen found!
 - libusb found!
 - openssl found!
 - No required package dependencies to install.

[Ensuring LLVM 4 support]
 - LLVM successfully linked from /usr/local/opt/llvm@4 to /Users/aaron.fu/eosio/1.9/opt/llvm
[Ensuring Boost 1.70.0 library installation]
 - Boost library found with correct version @ /Users/aaron.fu/eosio/1.9/src/boost_1_70_0


========================================================================
======================= Starting EOSIO Build ===========================
...
```

Thanks!
