### ISSUE TITLE
wrong build files location

### ISSUE THREAD

**Issue by taokayan** [EOSIO/eos#7527]
in branch release/1.8.x, cmake version 3.14.1, macOS Mojave, eosio_build.sh writes Build files into eos folder instead of eos/build, causing the next step "make all" to stop:

```
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jiaendu/workspaces/eos
make: *** No targets specified and no makefile found.  Stop.
```

But in a fresh ubuntu 18.04, it works correctly:
```
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/eos/build
/home/ubuntu/eosio/1.8/bin/cmake -S/home/ubuntu/eos -B/home/ubuntu/eos/build --check-build-system CMakeFiles/Makefile.cmake 0
/home/ubuntu/eosio/1.8/bin/cmake -E cmake_progress_start /home/ubuntu/eos/build/CMakeFiles /home/ubuntu/eos/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/ubuntu/eos/build'
...
```

**Comment by taokayan** [comment]
I found out that this can be solved by removing "CMakeCache.txt"

**Comment by NorseGaud** [comment]
We actually had this issue in the CICD too; We have to forcefully remove it or start with a clean container to get around it. I believe it's been an issue for quite a while.

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
