### ISSUE TITLE
Synchronization can't keep up and send transaction not return with 1.74

### ISSUE THREAD

**Issue by quarksgluons** [EOSIO/eos#7534]
The 1.74 version of the node often has the following two problems:

### 1. Synchronization can't keep up

It is about 100-300 blocks behind. When it is late, it will stop synchronizing whenever it is about to catch up. When it is behind more than 100 blocks, it will resume synchronization.

### 2. It is not possible to broadcast a transaction at a node. This occurs less frequently.

When the synchronization keeps up, send a transaction with this node does not return a result in a long time.

This problem has not occurred in the previous version 1.60 for several months, but it has appeared frequently after the update to 1.74.

**Comment by matthewdarwin** [comment]
Re #1.  Probably you need better hardware.

**Comment by heifner** [comment]
1.7.x is no longer supported. Many fixes for syncing have been added in recent versions of 1.8.x and 2.0.x.
