### ISSUE TITLE
get_supported_apis should return itself in the list of supported APIs

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#7542]
`get_supported_apis` should return itself in the list of supported APIs.  It is missing from the list

test case: curl http://localhost:8888/v1/node/get_supported_apis 
(this is tested on 1.8.0-rc2)

Related: https://github.com/EOSIO/eos/issues/7536

**Comment by aaron-fu-block-one** [comment]
Since I have worked on the related issue #7536 I would like to investigate this issue. Hopefully, the investigation will also yield something useful towards solving issue #7543.

**Comment by aaron-fu-block-one** [comment]
Hi @matthewdarwin. Having looked at the source for what `get_supported_apis` returned, I found the original author explicitly excluded `get_supported_apis` itself from the list.

https://github.com/EOSIO/eos/blob/67a3249b31bd2583c0fef3ab6736dae278625405/plugins/http_plugin/http_plugin.cpp#L718-L721

I believe the author has some good reason behind it. After all, the reason for having such a function is to know what (other) APIs are supported. Thus, it might be redundant to include itself recursively, which might add to the burden of the network. At any rate, it is self-evident that `get_supported_apis` is supported, so along as the call is successful.

Therefore, I guess maybe it is better for us to leave the code as it is now.
