### ISSUE TITLE
list of apis in get_supported_apis should be configurable

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#7543]
In some cases a public block producer candidate might want to enable an API for internal use but not make that API available publicly.  For example, the 'net' plugin might be of use for controlling the node, but a BP would not want the public to use that.    However, the `get_supported_apis` would say the net plugin is available, even though it is blocked by an intermediate proxy server the BP might be running (eg HAProxy or nginx or whatever).

If the list of supported apis is configurable, the BP can enable which ones should be shown, and then they should adjust their proxy configuration to match what is configured in nodeos.

Or even better nodeos exposes 2 different HTTP sockets and you can configure which APIs are published on which sockets. (internal HTTP server vs public HTTP server)

Related: https://github.com/EOSIO/eos/issues/7542 https://github.com/EOSIO/eos/issues/7536 https://github.com/EOSIO/eos/issues/4292

**Comment by aaron-fu-block-one** [comment]
Since I have worked on the related issue #7536 I would like to investigate this issue. I think step one should be taking a look at what we could do for issue #7542, which also has something to do with `get_supported_apis`. From that point, I believe it would be easier to solve this issue.

**Comment by b1aafulei** [comment]
Hi @matthewdarwin.

`get_supported_apis` returns a concatenated string `result` read from `url_handlers`. Even if we manually changed the `result` by removing certain API names from it, users can still have access to them.

For example, say we removed `/v1/chain/push_transactions` from the `result` string, users can still access it by calling

```c++
curl http://localhost:8888/v1/chain/push_transactions
```

This, while it may convey a message to the users that calling `push_transactions` is discouraged, cannot ban them from doing so (by just configuring the `get_supported_apis` function). Furthermore, this may lead to an inconsistency: it appears there is no support for `push_transactions`, but there is as a matter of fact.

Thus, in my humble opinion, it might be better for us to leave the code as it is.

**Comment by matthewdarwin** [comment]
Hello, this is correct that people can still access the URL.... However, any public API would realistically have a load balancer or some sort in front of their nodeos which would be configured to allow certain URLs only.

Hence my suggestion to allow certain URLs to be published on certain ports, and then nodeos can know quite clearly what is available and get_supported_apis can return the correct thing automatically.

**Comment by b1aafulei** [comment]
Hello @matthewdarwin. Thank you for the reply. Personally I think the feature you proposed might be better provided at the infrastructure level, namely to provide a tailor-made `get_supported_apis` endpoint that a router redirects traffic flow to.

```
 --------------
|    router    | --- (custom) `get_supported_apis` endpoint
 --------------
 |      |     |
 |      |     |
url1  url2   url3
```

Doing so, instead of configuring the `get_supported_apis` in nodoes, will maintain consistency. It is your router that switches on and off the APIs, and thus it should also be your router that provides sort of an instruction guide to the public what APIs that they may use.
