### ISSUE TITLE
Unable to deserialize action with empty data

### ISSUE THREAD

**Issue by acoutts** [EOSIO/eos#7546]
ABI snippet for action in question:
```json
{
  "name": "processpool",
  "base": "",
  "fields": []
}
```

When called in practice:
```c++
trx.actions.emplace_back(eosio::permission_level {_self, N(active) }, _self, N(processpool), std::string(""));
```

I'm writing a plugin that should handle actions for this case, but `binary_to_variant()` is failing with an unpack data exception:
```
warn  2019-06-27T21:59:09.501 thread-0  controller.cpp:234            emit                 ] 3015013 unpack_exception: Unpack data exception
Unable to unpack 'processpool' from stream
    {"p":"processpool"}
    thread-0  abi_serializer.cpp:376 _binary_to_variant
```

Here is the raw action:
```
{"account":"chintailease","name":"processpool","authorization":[{"actor":"chintailease","permission":"active"}],"data":"00"}
```

There's a comment on line 375 of `abi_serializer.cpp` which explains exactly the issue I'm having:
```
      // QUESTION: Is this assert actually desired? It disallows unpacking empty structs from datastream.
      EOS_ASSERT( mvo.size() > 0, unpack_exception, "Unable to unpack '${p}' from stream", ("p", ctx.get_path_string()) );
```

Is there a safe way to deserialize action data and handle a case where the data is empty?

**Comment by aclark-b1** [comment]
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!
