### ISSUE TITLE
Cannot Send EOS to Binance from Scatter/EOS Authority

### ISSUE THREAD

**Issue by Batman0323** [EOSIO/eos#7557]
Hi guys -

Firstly THANK YOU in advance for your help. I am moderately computer literate however the troubleshooting I have done on my own is WAY above my paygrade.  

Here is what is going on.

1. On June 14th I was able to send 10 EOS without issue from my Authority Account connected via Scatter.

2.  The same day I undelegated and unstaked as much of my balance as I could (leaving .5 and .1 respectively)  

3. Currently I have 83 EOS that I am trying to send to Binance and I keep running into this error:

Transaction failed "{\"code\":500,\"message\":\"Internal Service Error\",\"error\":{\"code\":3090003,\"name\":\"unsatisfied_authorization\",\"what\":\"Provided keys, permissions, and delays do not satisfy declared authorizations\",\"details\":[{\"message\":\"transaction declares authority '{\\\"actor\\\":\\\"g42tgmzqgege\\\",\\\"permission\\\":\\\"active\\\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [\\\"EOS6ZkN4MtezD6QayV7YLuYVRrx5kwoVZ7AfsbTc87HoQP8w1zsWx\\\"], and a delay max limit of 3888000000 ms\",\"file\":\"authorization_manager.cpp\",\"line_number\":520,\"method\":\"check_authorization\"}]}}"

4. I have endeavored to do my own research but all this change Ms Cleo to this and then this command line using xyz is massively confusing.

5.  I am running Scatter 11.0 

Anyone know how to make this work?

**Comment by NorseGaud** [comment]
Have you posted an issue with Scatter on their GitHub?

**Comment by gleehokie** [comment]
@Batman0323 you are using the wrong keys, see https://bloks.io/account/g42tgmzqgege#keys for the keys that are assigned to the g42tgmzqgege account.

If you are using Scatter please refer your questions to Scatter on Telegram (https://t.me/Scatter) or GitHub.
