### ISSUE TITLE
./eosio_uninstall.sh: line 5: ./scripts/helpers/eosio.sh: No such file or directory

### ISSUE THREAD

**Issue by acoutts** [EOSIO/eos#7569]
On `tags/v1.8.0`, this is the output of running `eosio_uninstall.sh` from within the scripts folder. Works if you execute it from the parent root folder though. Looks like a hardcoded relative path to the scripts folder is the issue.

**Comment by arhag** [comment]
Similar to #7564.

**Comment by acoutts** [comment]
Same thing for the install script as well.

**Comment by dawnFromDark** [comment]
me too,i did not find this script in the branch

**Comment by NorseGaud** [comment]
Please run from the root directory for now until the next release
