### ISSUE TITLE
STAT-189 ⁃ eosc benchmark is broken due to signatures and transaction timeouts

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#757]
eosc benchmark stopped working since last testnet because of signatures in transactions and timeouts in transactions.

ATC:

1. eosc benchmark setup 10 <owner key> <active key>
2. eosc benchmark transfer 10 1000

Check that the transfer is successful.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

This is still in peer review. Moving.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

Please try again with 11/27.2017 testnet.

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

Followed these steps:
remote_eosc benchmark setup 10 EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
<Succsess, created all the accounts>

remote_eosc benchmark transfer 10 1000
<First 10 transactions were successfully completed, then got the following error>

Generating random 1000 transfers among 10
706053ms thread-0   main.cpp:1125                 main                 ] Failed with error: 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_6system12system_errorEEEEE: read_until: Connection reset by peer
read_until: Connection reset by peer: 
    {"server":"10.160.11.221","port":8888,"path":"/v1/chain/get_required_keys","postdata":{"transaction":{"ref_block_num":2734,"ref_block_prefix":884653761,"expiration":"2017-11-28T03:11:54","scope":["benchmark...1","benchmark...c"],"read_scope":[],"messages":[{"code":"eos","type":"transfer","authorization":[{"account":"benchmark...1","permission":"active"}],"data":"010080d7c886a63a080080d7c886a63a010000000000000024323031372d31312d32385430333a31313a34342031353131383338373034383933323231"}],"signatures":[]},"available_keys":["EOS4ws1tX5Jjbm4PfeqMHaNpDEdtSqs7AMbumb9U7hAsNkuYeMKvJ","EOS5P7qu6tQjKWsKqFGT9Xj29EYkahCUxPQhnBJyERu4fqyadyGZX","EOS5UKhhDri3mxroHhpGfDuXMRP359YFUyQcKYdqmYuLWxfoewgZr","EOS5jk1RbC8prdDc3yvWnVJF7MFibLrYMVsLTtXTDXrnZ4wf8WH5K","EOS61EgwkgTfdVngrQpXCbczMzjEfxRy5pBLFRtdfrw4Cj6YsNPUX","EOS699kChKPbJPqrrhyMwjBdRVREowzdoN23YNvP4YXZ815RbfC7a","EOS6KKi7NjX1Wb7KkAKBytEU2xhyyrDF2c4F8dTtCnYQUaE2epEtF","EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","EOS6QTPXRswTALmK6bsCoyVEdsLK384ys57RzMSjnUN7uQbpmqv5o","EOS6TY6hjTeL1Px8tMf3m4iCQX89MXKA5Gnq3iV6Hxu3JTXbKSBKY","EOS6VUPau1krKJCUrwvCJCwRzh9ojhtZ1FSVzcbxNYoQc56E8rbMF","EOS6XH3qFT9dXfxcfbCH26HMfK9DTnTZyiFLxg8LfPJtWAEnF7NDr","EOS6cio7gLERhjqoD5GfqK7Cgv3HduLnhcdA9pAxvPzqJgj2CDV3M","EOS6eGhHofm2znZK5rrxCvEW4gaDD62PodV1TUC48FjY3U2yuZh16","EOS6ijCPrSARDsCq7q6avjsn1VimmRmj4FxfQAC2aKCFv5qg6DDmr","EOS6mgx1uouW8AsRg2vnPUosCvgH74nridSKhDj3oV3D96BkPuvcN","EOS6peNYDDpH7eHBs3u3gzDzBPEbYHYFoLeMbt8m8yyCvydS1oVVR","EOS6rsQyHVZrqr5cWFZGWeL7MAtgVcD6G8DmfcoQYLHbTBSKa4mij","EOS6sck1N6sTqGRURYJYNnAjpz8PUhjSwX3NjRyXjDXZbZazUqGJ5","EOS6vScLZnvFzxsYhd8QehYBGzmFdu4oBrfFu5Q9i6r45DHv6F65S","EOS75dTX9MwRB5QN6bUTwMNt5i8iYszesSEQrvyby272RCKE13pVg","EOS75qrbSvsLdxwfiTRjFKc6y2qjvpD6feoBABebqwa3UMgxjzTT5","EOS7GcwGGhP4334XR5sLGR78wX52wu8wfnz1NEx7h4bAZn7H6DVje","EOS7L9ber2srpHfr2TomvRg41kK1bFa7jYkoWtQpQ6JfvNPhYMkXa","EOS7SbNDjHpLxH4PhyqUoxdqNW22TvJS1m6moSy2zBNvVSHM3sjgV","EOS7U2LtvbsYChp3P8UCYRNoLwxBDV3LA3iyjHKEnu96DauoWvxDW","EOS7Y4GpaD6sgWcHtpMvmgBh6WUANZ5FX7dAEqJZtLtcrCbrneMVK","EOS7cbA3eB9aCsPymzrMFYMqTuE5agqvdXdXt4XuZA5sVrjz2zTR7","EOS7eBgsKPxwbiNenxFggW7k64f9rFjJUXw5VMnrAGX54UY7XTwXD","EOS7uCq4F7r73nk4efyxAAfNEUwwrjPCkssCVPjF7HsoKYYmMEqGG","EOS7vTXfPzmandq1WjM1zG8UBCjJNSZPT8TwP8a7zqKkKWofGGLqj","EOS8ANhnYgS1quCoJWZkuRkyafGuTYTwHP37mw1DoroTvK7sMovYH","EOS8LMoJmADDVRr8LRsj6L1m17z4fjEZgrxm1UGJ6KdX4MLdYtn9L","EOS8LMs1CknEjzVnE5cJBoUP47wuJF5gevs7ueyFAdrRmP7H65GiN","EOS8UoFezU4xZFnkV62amso7JxwqxepA65w1MiEQ1ty2iBRCtj855","EOS8VkVLMhTAJ3SYbvcDjMRdBbqJK2UkM7pgnRCaeiLCJ2kxr5UZj","EOS8YJVXSAWoGZXjU3jXVc3bm74ZaeuTNixSZ77HZd5Xje24k1DCT","EOS8b4iFQ7Ba7FdC7SdnoHhtjMZJnrW4KD5JRMhWHZu24p1fpaEef","EOS8bHDVcTyNAmCzKR7uYyReaT5ABUSnTqXeDDGTanXEKaaLzv9hv","EOS8gaUmF1gxh8TY24MTB3Aad6zogQkdNnwVxdHDNW782W6teUbDQ","EOS8mGc2JECaDcQJoKZof1PvVYBHRC3St4CQyLzTysUYKWGHYQPHs"]},"what":"read_until: Connection reset by peer"}
    thread-0  httpc.cpp:117 call
bash-3.2$

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

Marking this issue as closed as the scope of the test is limited to eosc benchmark command
But the real problem of benchmark transfer requests are not being executed still exists and separate jira for it

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

The reported issue still exists
processed": {
      "error": "3030000 transaction_exception: transaction validation exception\nTransaction is expired\n    {\"now\":\"2017-11-29T03:22:48\",\"trx.exp\":\"2017-11-29T03:18:28\"}\n    thread-0  chain_controller.cpp:809 validate_expiration\n\n    {\"trx\":{\"ref_block_num\":3490,\"ref_block_prefix\":3586235344,\"expiration\":\"2017-11-29T03:18:28\",\"scope\":[\"benchmark...b\",\"benchmark...c\"],\"read_scope\":[],\"messages\":[{\"code\":\"eos\",\"type\":\"transfer\",\"authorization\":[{\"account\":\"benchmark...c\",\"permission\":\"active\"}],\"data\":\"080080d7c886a63a070080d7c886a63a010000000000000024323031372d31312d32395430333a32323a34352031353131393235373635343335303230\"}]}}\n    thread-0  chain_controller.cpp:810 validate_expiration\n\n    {\"trx\":{\"ref_block_num\":3490,\"ref_block_prefix\":3586235344,\"expiration\":\"2017-11-29T03:18:28\",\"scope\":[\"benchmark...b\",\"benchmark...c\"],\"read_scope\":[],\"messages\":[{\"code\":\"eos\",\"type\":\"transfer\",\"authorization\":[{\"account\":\"benchmark...c\",\"permission\":\"active\"}],\"data\":\"080080d7c886a63a070080d7c886a63a010000000000000024323031372d31312d32395430333a32323a34352031353131393235373635343335303230\"}],\"signatures\":[\"1f2e4c83d639e973a9b4e60fd82bc39e1108b98985425480eee3a93b0e220970d9057127bffd41c9940afa7dc22723180c7bed59b3a4cc5e46b605430e52ad3db7\"]}}\n    thread-0  chain_controller.hpp:357 validate_transaction\n\n    {\"trx\":{\"ref_block_num\":3490,\"ref_block_prefix\":3586235344,\"expiration\":\"2017-11-29T03:18:28\",\"scope\":[\"benchmark...b\",\"benchmark...c\"],\"read_scope\":[],\"messages\":[{\"code\":\"eos\",\"type\":\"transfer\",\"authorization\":[{\"account\":\"benchmark...c\",\"permission\":\"active\"}],\"data\":\"080080d7c886a63a070080d7c886a63a010000000000000024323031372d31312d32395430333a32323a34352031353131393235373635343335303230\"}],\"signatures\":[\"1f2e4c83d639e973a9b4e60fd82bc39e1108b98985425480eee3a93b0e220970d9057127bffd41c9940afa7dc22723180c7bed59b3a4cc5e46b605430e52ad3db7\"]}}\n    thread-0  chain_controller.cpp:983 apply_transaction\n\n    {\"trx\":{\"ref_block_num\":3490,\"ref_block_prefix\":3586235344,\"expiration\":\"2017-11-29T03:18:28\",\"scope\":[\"benchmark...b\",\"benchmark...c\"],\"read_scope\":[],\"messages\":[{\"code\":\"eos\",\"type\":\"transfer\",\"authorization\":[{\"account\":\"benchmark...c\",\"permission\":\"active\"}],\"data\":\"080080d7c886a63a070080d7c886a63a010000000000000024323031372d31312d32395430333a32323a34352031353131393235373635343335303230\"}],\"signatures\":[\"1f2e4c83d639e973a9b4e60fd82bc39e1108b98985425480eee3a93b0e220970d9057127bffd41c9940afa7dc22723180c7bed59b3a4cc5e46b605430e52ad3db7\"]}}\n    thread-0  chain_controller.cpp:236 push_transaction"

**Comment by blockone-syncclient** [comment]
➤ Bezwada Satyapravin commented:

[~dhanesh.balakrishnan] How can I reproduce this issue?

**Comment by heifner** [comment]
Verified by QA, closing.

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Moving to finished, this was moved to closed-withdrawn by mistake.
