### ISSUE TITLE
nodeos can not sync block from 1.7.4

### ISSUE THREAD

**Issue by dawnFromDark** [EOSIO/eos#7570]
i can not upgrde my block data from nodeos 1.7.4 to 1.8,the eorror is following:

warn  2019-07-01T02:26:05.872 nodeos    chain_plugin.cpp:958          plugin_initialize    ] 13 N5boost10wrapexceptISt13runtime_errorEE: chainbase database format not compatible with this version of chainbase.
rethrow chainbase database format not compatible with this version of chainbase.: 
    {"what":"chainbase database format not compatible with this version of chainbase."}
    nodeos  chain_plugin.cpp:958 plugin_initialize
error 2019-07-01T02:26:05.872 nodeos    main.cpp:114                  main                 ] 13 N5boost10wrapexceptISt13runtime_errorEE: chainbase database format not compatible with this version of chainbase.
rethrow chainbase database format not compatible with this version of chainbase.: 
    {"what":"chainbase database format not compatible with this version of chainbase."}
    nodeos  chain_plugin.cpp:958 plugin_initialize

it seems that data incompatibility,may you solve this ?

**Comment by dawnFromDark** [comment]
and your eosio_insall.sh have fatal error,you can check it ! The relative path got critical error, you guys did not test this , right?????


![image](https://user-images.githubusercontent.com/44474000/60407009-6a076480-9beb-11e9-92d3-7a8885815f98.png)

**Comment by matthewdarwin** [comment]
Please read the release notes on how to solve the compatibility issue https://github.com/EOSIO/eos/releases/tag/v1.8.0

**Comment by matthewdarwin** [comment]
See https://github.com/EOSIO/eos/issues/7564 re the issue about eosio_install.sh.

**Comment by NorseGaud** [comment]
Please execute scripts from the repo root until this is fixed in the next patch release: `./scripts/eosio_install.sh`
