### ISSUE TITLE
eos 1.8.0 build failed with clang error

### ISSUE THREAD

**Issue by wsdfz** [EOSIO/eos#7577]
In my macbook, I built eos 1.8.0 with the following error. Any suggestion ?

======================= Starting EOSIO Build ===========================
Re-run cmake no build system arguments
-- The C compiler identification is Clang 4.0.1
-- The CXX compiler identification is Clang 4.0.1
-- Check for working C compiler: /usr/local/opt/llvm@4/bin/clang
-- Check for working C compiler: /usr/local/opt/llvm@4/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/opt/llvm@4/bin/clang++
-- Check for working CXX compiler: /usr/local/opt/llvm@4/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:57 (message):
  Clang version must be at least 5.0!

-- Configuring incomplete, errors occurred!

**Comment by NorseGaud** [comment]
You need to uninstall the old EOS installation which is using /usr/local/opt/llvm@4/bin/clang++ (which is no longer a version we support).

**Comment by wsdfz** [comment]
I run scripts/eosio_uninstall.sh and uninstall llvm@4 in brew as the following:

...
Do you wish to uninstall and unlink all brew installed llvm@4 versions? (y/n) y
Uninstalling llvm@4... (4,452 files, 2.0GB)
Removing: /Users/dacheng/Library/Caches/Homebrew/llvm@4--4.0.1_1.mojave.bottle.1.tar.gz... (626.4MB)
...

But when I run ./eosio_build.sh again, it want to install llvm@4 again. Like the following:

...

[Ensuring xcode-select installation]
 - xcode-select installation found @ /usr/bin/xcode-select
[Ensuring Ruby installation]
 - Ruby installation found @ /usr/local/bin/ruby
[Ensuring HomeBrew installation]
 - HomeBrew installation found @ /usr/local/bin/brew

[Ensuring HomeBrew dependencies]
 - cmake found!
 - graphviz found!
 - libtool found!
 - automake found!
 - wget found!
 - gmp found!
 **- llvm@4 NOT found.**
 - pkgconfig found!
 - python found!
 - python@2 found!
 - doxygen found!
 - libusb found!
 - openssl found!

Do you wish to install missing dependencies? (y/n)  

What should I do to let it install a newer version of llvm ?

**Comment by NorseGaud** [comment]
/usr/local/opt/llvm@4/bin looks to be in your PATH env; make sure to clean up your .bashrc/profile files for any older PATHs

**Comment by wsdfz** [comment]
Yes. I uses the macbook to build eosio 1.7.4 . 

I found it checks dependence in file: scripts/eosio_build_darwin_deps and there is a llvm@4 .

https://github.com/EOSIO/eos/blob/master/scripts/eosio_build_darwin_deps

cmake,/usr/local/bin/cmake
graphviz,/usr/local/opt/graphviz
libtool,/usr/local/bin/glibtool
automake,/usr/local/bin/automake
wget,/usr/local/bin/wget
gmp,/usr/local/opt/gmp/include/gmpxx.h
llvm@4,/usr/local/opt/llvm@4
pkgconfig,/usr/local/bin/pkg-config
python,/usr/local/opt/python3
python@2,/usr/local/opt/python2
doxygen,/usr/local/bin/doxygen
libusb,/usr/local/lib/libusb-1.0.0.dylib
openssl,/usr/local/opt/openssl/lib/libssl.a

And in https://github.com/EOSIO/eos/blob/release/1.8.x/scripts/helpers/eosio.sh
There is a "Ensuring LLVM 4 support".

I tried to change to LLVM 8. And failed with following error:

...
CMake Error at libraries/wasm-jit/Source/Runtime/CMakeLists.txt:26 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "4.0".

  The following configuration files were considered but not accepted:

    /usr/local/opt/llvm@8/lib/cmake/llvm/LLVMConfig.cmake, version: 8.0.0
    /usr/local/opt/llvm@8/lib/cmake/llvm/llvm-config.cmake, version: unknown



-- Configuring incomplete, errors occurred!

**Comment by NorseGaud** [comment]
You need to use the llvm@4. Did you find why llvm@4’s clang is being loaded by checking the PATH env?

**Comment by wsdfz** [comment]
After install both llvm@4 and llvm@8, eos 1.8 is built successfully.
