### ISSUE TITLE
can't run ./eosd!

### ISSUE THREAD

**Issue by jatinmehta420** [EOSIO/eos#758]
I gave command to run eosd and everything was going good but then in the middle I got an server error and when I again connected my server and gave command to run the eosd. It gave following error:
1933263ms thread-0   main.cpp:39                   main                 ] 13 NSt8ios_base7failureB5cxx11E: basic_ios::clear: iostream error
basic_ios::clear: iostream error:
    {"my->genesis_file.generic_string()":"/home/ubuntu/eos/build/genesis.json","what":"basic_ios::clear: iostream error"}
    thread-0  chain_plugin.cpp:236 plugin_startup
![capture4](https://user-images.githubusercontent.com/22103300/33129712-e4a58792-cfb6-11e7-8148-b5c90a497fbc.PNG)

**Comment by heifner** [comment]
Not much to go on here. What the server error you mentioned? Is /home/ubuntu/eos/build/genesis.json a valid json file?

**Comment by jatinmehta420** [comment]
My server error was "Connection Reset" and yes it is a valid path to genesis.json file!

**Comment by heifner** [comment]
Please try with `./eosd --resync`

**Comment by jatinmehta420** [comment]
Ill try it sir Thank you :)

**Comment by jatinmehta420** [comment]
That worked sir Thanks a lot!

**Comment by heifner** [comment]
Glad to hear it, closing this issue.

**Comment by DavidFnck** [comment]
@heifner Hi，I guess `./eosd --resync` is the way to reload the config.ini file.

But in Docker, I use `docker-compose -f docker-compose.yml up` to start the eosd and the wallet, and how can I use `./eosd --resync` to reload the file? Thanks.
