### ISSUE TITLE
The dependency target "XXX/example_project/src/../ricardian/example_project.contracts.md of target "example_project" does not exist

### ISSUE THREAD

**Issue by FarhanQureshi19** [EOSIO/eos#7596]
nodeos -v: `v1.8.0`
eosio-cpp -v:  ``` clang version 7.0.0 (https://github.com/eosio/clang.git 6b886302a11a8419b76e469794ff9d0c531a4b4b) (https://github.com/eosio/llvm a41b8e7653258a4f1a5911ef28c95672efce051e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/opt/eosio.cdt/1.6.1/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64 ```

using commands:
```
eosio-init -path=XXX -project=example-project
cd XXX/build
cmake ..
```

output:

> -- The C compiler identification is GNU 7.3.0
> -- The CXX compiler identification is GNU 7.3.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Setting up Eosio Wasm Toolchain 1.6.1 at /usr
> CMake Warning (dev) in CMakeLists.txt:
>   No cmake_minimum_required command is present.  A line of code such as
>     cmake_minimum_required(VERSION 3.10)
>   should be added at the top of the file.  The version specified may be lower
>   if you wish to support older CMake versions for this project.  For more
>   information run "cmake --help-policy CMP0000".
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /XXX/example_project/build

`make`

Output:

> Scanning dependencies of target example_project_project
> [ 11%] Creating directories for 'example_project_project'
> [ 22%] No download step for 'example_project_project'
> [ 33%] No patch step for 'example_project_project'
> [ 44%] No update step for 'example_project_project'
> [ 55%] Performing configure step for 'example_project_project'
> -- Setting up Eosio Wasm Toolchain 1.6.1 at /usr
> -- Setting up Eosio Wasm Toolchain 1.6.1 at /usr
> -- The C compiler identification is Clang 7.0.0
> -- The CXX compiler identification is Clang 7.0.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - failed
> -- Detecting C compile features
> -- Detecting C compile features - failed
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - failed
> -- Detecting CXX compile features
> -- Detecting CXX compile features - failed
> CMake Warning (dev) in CMakeLists.txt:
>   No cmake_minimum_required command is present.  A line of code such as
>     cmake_minimum_required(VERSION 3.10)
>   should be added at the top of the file.  The version specified may be lower
>   if you wish to support older CMake versions for this project.  For more
>   information run "cmake --help-policy CMP0000".
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Configuring done
> CMake Warning (dev) at /usr/opt/eosio.cdt/1.6.1/lib/cmake/eosio.cdt/EosioCDTMacros.cmake:12 (add_dependencies):
>   Policy CMP0046 is not set: Error on non-existent dependency in
>   add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
>   Use the cmake_policy command to set the policy and suppress this warning.

```
>   The dependency target
>   "/XXX/example_project/src/../ricardian/example_project.contracts.md"
>   of target "example_project" does not exist.
> Call Stack (most recent call first):
>   CMakeLists.txt:8 (target_ricardian_directory)
```

> This warning is for project developers.  Use -Wno-dev to suppress it.
> -- Generating done
> -- Build files have been written to: /XXX/example_project/build/example_project

**Comment by ndcgundlach** [comment]
Not clear what the issue is here.  It has been open more than six months.  If this is an ongoing issue, please document with more detail.
