### ISSUE TITLE
brew install eosio

### ISSUE THREAD

**Issue by ytuaeb** [EOSIO/eos#7604]
macOS: 10.13.6-x86_64

$ brew install eosio
==> Installing eosio from eosio/eosio
==> Downloading https://github.com/eosio/eos/archive/v1.8.0.tar.gz
==> Downloading from https://codeload.github.com/EOSIO/eos/tar.gz/v1.8.0
######################################################################## 100.0%
Warning: Cannot verify integrity of fcc4996828aa5cc0c832f7604b1fc6850923e428475e8f6709959f66bec12ef9--eos-1.8.0.tar.gz
A checksum was not provided for this resource
For your reference the SHA-256 is: 173122c922bd13bb837620bd27d25755efec294dd54a050fc1838e8546b640f7
Error: An exception occurred within a child process:
  RuntimeError: Error, only supporting binary packages at this time

**Comment by spoonincode** [comment]
eosio only supports 10.14 now. That's probably the reason for your error but I have no way of testing 10.13 at the moment

**Comment by spoonincode** [comment]
the bottle has been updated to report a more intelligent error when not running 10.14+, closing issue as resolved

**Comment by acalleja42** [comment]
macOS Catalina: 10.15.6

➜  ~ brew install eosio
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 5 formulae.

==> Installing eosio from eosio/eosio
==> Downloading https://github.com/eosio/eos/archive/v2.0.7.tar.gz
Already downloaded: /Users/amaurycalleja/Library/Caches/Homebrew/downloads/835fef79b625d321e2f7b609c9e8f03822dcda89317b439a8a5c8835fbc244f6--eos-2.0.7.tar.gz
Warning: Cannot verify integrity of 835fef79b625d321e2f7b609c9e8f03822dcda89317b439a8a5c8835fbc244f6--eos-2.0.7.tar.gz
A checksum was not provided for this resource.
For your reference the SHA-256 is: 9a9ecd36242d620e0165766f41f5f942ff6d1a9edc12dac418a0ebcaf2dc4d8a
Error: An exception occurred within a child process:
  RuntimeError: Error, only supporting binary packages at this time
