### ISSUE TITLE
Eos 1.8.0 fails to install on clean ubuntu18.04

### ISSUE THREAD

**Issue by ksemaev** [EOSIO/eos#7605]
Hi guys! I get the released package from https://github.com/EOSIO/eos/releases/download/v1.8.0/eosio_1.8.0-1-ubuntu-18.04_amd64.deb and try installing it on clean (or updated) ubuntu18.04 and receive

>  eosio : Depends: libicu60 but it is not installable
>          Depends: libusb-1.0-0 but it is not installable
>          Depends: libcurl3-gnutls but it is not installable

There're some playing arround with fixing dependencies, but is there a smooth way of installing it from packages you provide? Maybe there's readme on prerequisites that I missed?
Please advice!

**Comment by ksemaev** [comment]
Not sure why, but running `apt-get update`twice before installing that package fixed the issue for me

**Comment by jgiszczak** [comment]
The "proper" solution is to install from a repository/PPA.  Block.one is working to establish a PPA so apt/apt-get can be used to install from packages, enabling automated dependency handling which dpkg does not provide.

Standard procedure to install missing dependencies of a dpkg installed package is to run `apt-get install -f`.

Standard procedure to install missing dependencies of an rpm installed package is to reinstall with `yum --nogpgcheck localinstall packagename.arch.rpm`.
