### ISSUE TITLE
eos-node version 1.8.0 startup instructions

### ISSUE THREAD

**Issue by ksemaev** [EOSIO/eos#7606]
There's a very poor doc portal on https://developers.eos.io/eosio-nodeos which basically get's me no information. What are the recommended settings to start and syncup the non-productive node (https://developers.eos.io/eosio-nodeos/docs/environment-non-producing-node ) ?

All I get now from logs is node connected to peers, but not receiving blocks. 
Should I get some special peers for 1.8.0? Currently I use `wget  -O p2p.ini https://eosnodes.privex.io/?config=1` to get peers, but maybe there's some new list?

Any advice on startup oprions is appreciated

**Comment by ksemaev** [comment]
Config file is:

>     #Chain plugin settings
>     chain-state-db-size-mb = 8192
>     reversible-blocks-db-size-mb = 2048
>     read-mode = read-only
>     validation-mode = light
>     wasm-runtime = wabt
> 
>     #Http plugin settings
>     access-control-allow-origin = *
>     http-validate-host = false
>     verbose-http-errors = true
>     http-server-address = 0.0.0.0:8888
>     filter-on = *
> 
>     #Net plugin settings
>     agent-name = Exodus Dev Agent
>     sync-fetch-span = 200
>     p2p-max-nodes-per-host = 4
>     max-clients = 100
>     p2p-server-address = 0.0.0.0:9876
> 
>     # State history plugin settings
>     state-history-endpoint = 0.0.0.0:8080
>     trace-history = true
>     chain-state-history = true
> 
>     #Plugins
>     plugin = eosio::chain_plugin
>     plugin = eosio::state_history_plugin
>     plugin = eosio::chain_api_plugin
>     plugin = eosio::history_api_plugin
>     plugin = eosio::http_plugin
>     plugin = eosio::net_api_plugin
> 
>     #peers
>     p2p-peer-address = 18.234.6.119:80
>     p2p-peer-address = 185.253.188.1:19876
>     p2p-peer-address = api-full1.eoseoul.io:9876
>     p2p-peer-address = api-full2.eoseoul.io:9876
>     p2p-peer-address = boot.eostitan.com:9876
>     p2p-peer-address = bp.antpool.com:443
>     p2p-peer-address = bp.cryptolions.io:9876
>     p2p-peer-address = bp.eosbeijing.one:8080
>     p2p-peer-address = bp.libertyblock.io:9800
>     p2p-peer-address = br.eosrio.io:9876
>     p2p-peer-address = eos-seed-de.privex.io:9876
>     p2p-peer-address = eu1.eosdac.io:49876
>     p2p-peer-address = fullnode.eoslaomao.com:443
>     p2p-peer-address = mainnet.eoscalgary.io:5222
>     p2p-peer-address = mainnet.eospay.host:19876
>     p2p-peer-address = mars.fnp2p.eosbixin.com:443
>     p2p-peer-address = node.eosflare.io:1883
>     p2p-peer-address = node1.eoscannon.io:59876
>     p2p-peer-address = node1.eosnewyork.io:6987
>     p2p-peer-address = node2.eosnewyork.io:6987
>     p2p-peer-address = p.jeda.one:3322
>     p2p-peer-address = p2p.eosdetroit.io:3018
>     p2p-peer-address = p2p.genereos.io:9876
>     p2p-peer-address = p2p.meet.one:9876
>     p2p-peer-address = p2p.one.eosdublin.io:9876
>     p2p-peer-address = p2p.two.eosdublin.io:9876
>     p2p-peer-address = peer.eosn.io:9876
>     p2p-peer-address = peer.main.alohaeos.com:9876
>     p2p-peer-address = peer1.mainnet.helloeos.com.cn:80
>     p2p-peer-address = peer2.mainnet.helloeos.com.cn:80
>     p2p-peer-address = peering.mainnet.eoscanada.com:9876
>     p2p-peer-address = pub0.eosys.io:6637
>     p2p-peer-address = pub1.eosys.io:6637
>     p2p-peer-address = publicnode.cypherglass.com:9876
>     p2p-peer-address = seed1.greymass.com:9876
>     p2p-peer-address = seed2.greymass.com:9876
> 

And startup string I use is `/usr/bin/nodeos --config-dir /home/eos/config --data-dir /home/eos/mainnet --disable-replay-opts`

**Comment by conr2d** [comment]
If you want nodeos to sync with mainnet, you should provide `genesis.json` during first setup. `--genesis-json PATH_TO_GENESIS_JSON` option is used for this.
https://github.com/CryptoLions/EOS-MainNet/blob/master/genesis.json
