### ISSUE TITLE
Don't remove released assets please

### ISSUE THREAD

**Issue by ksemaev** [EOSIO/eos#7636]
Hi guys! I had this pipe working for several days: `wget -q https://github.com/EOSIO/eos/releases/download/v$VERSION/eosio_$VERSION-1-ubuntu-18.04_amd64.deb` 

And now it's broken because you removed `.deb` releases from `1.8.0` version. Can you please not do it next time, or even put back the ones you removed?
Currently there's only source code present in assets for this version.

**Comment by heifner** [comment]
See 1.8.1 release notes:
https://github.com/EOSIO/eos/releases/tag/v1.8.1

The 1.8.0 packages were removed because everyone needs to run 1.8.1 instead of 1.8.0.

**Comment by taokayan** [comment]
please use the latest version (1.8.1)
