### ISSUE TITLE
EOS Ubuntu18 同步快照的时候报错

### ISSUE THREAD

**Issue by wanggang931111** [EOSIO/eos#7637]
EOS同步快照快的时候报错，安装流程按官网源码编译来的，初始化创始快没问题，就是到了同步快照的时候报错了，有大佬知道吗？几天了，各种问各种试，还是不行。说版本必须在2和2之间包括2
![073a6d18f59fb0b6b8fc2dc999738fe](https://user-images.githubusercontent.com/51226924/61042078-14f6fa00-a406-11e9-8bb1-cb6e9fdf1e8f.png)

**Comment by taokayan** [comment]
The snapshot is created in version 1.7 or older versions, which is not compatible with version 1.8 or later versions. To solve this, you can:

- do hard-replay with version 1.8 (recommended, but might take weeks), or
- use eosio version 1.7, and wait for the compatible snapshot version in the future.

**Comment by wanggang931111** [comment]
1.7版本的  去哪里找

**Comment by taokayan** [comment]
https://github.com/EOSIO/eos/tree/v1.7.4

**Comment by wanggang931111** [comment]
> https://github.com/EOSIO/eos/tree/v1.7.4

1.7.4的也可以吗？

**Comment by wanggang931111** [comment]
> https://github.com/EOSIO/eos/tree/v1.7.4

是要1.7以下的才可以快照同步， 还是1.8以下的，大佬

**Comment by taokayan** [comment]
yes. 1.7.4 is ok

**Comment by wanggang931111** [comment]
> 是。1.7.4没关系
硬重播 大佬 你说的1.8版本的硬重播 ，是不是 就是同步所有快？

**Comment by wanggang931111** [comment]
> 是。1.7.4没关系
大佬，还是这个错。 急死人， 要上线了
![image](https://user-images.githubusercontent.com/51226924/61098843-f5f27980-a492-11e9-95d9-bf64e0fdf09a.png)

**Comment by taokayan** [comment]
are you sure you're running version 1.7.4? Please check with ```nodeos --version```

**Comment by wanggang931111** [comment]
> are you sure you're running version 1.7.4? Please check with `nodeos --version`

大佬，我里面有一个1.8的版本的，再下个1.7.4的会冲突吗？ 为什么我编译1.7.4老是编译不通过

**Comment by taokayan** [comment]
you can have different versions of nodeos. you can download the pre-build version.

**Comment by wanggang931111** [comment]
> > 你确定你运行的是1.7.4版本吗？请检查`nodeos --version`
> 
> 大佬，我里面有一个1.8的版本的，再下个1.7.4的会冲突吗？为什么我编译1.7.4老是编译不通过
我重新重置了系统，我再试下，我用的1.5.2的版本的， 也是一样的吧？还在编译中，脑壳痛，搞了2天了。

**Comment by wanggang931111** [comment]
> 您可以拥有不同版本的nodeos。您可以下载预构建版本。

我重置了liunx系统，我用源码部署的，应该没问题吧。 部署的1.5.2版本的。现在还在编译中，
git clone https://github.com/EOSIO/eos  -b v1.5.2 --recursive 命令是这样不？

**Comment by lcgogo** [comment]
You can try http://snapshots.eossweden.org/ which is 1.8 snapshot

**Comment by spoonincode** [comment]
Going to close this, there doesn't seem to really be anything actionable. Portable snapshots made with 1.8+ will only work on 1.8+. Portable snapshots made pre-1.8 will only work on pre-1.8.

**Comment by bbboyjan** [comment]
你的节点的EOS版本和快照不一致。
