### ISSUE TITLE
[SUPPORT] Where I can find the nodeos code ? 

### ISSUE THREAD

**Issue by bakasura980** [EOSIO/eos#7638]

**Comment by heifner** [comment]
https://github.com/EOSIO/eos/tree/master/programs/nodeos

**Comment by bakasura980** [comment]
Thank you for your answer!
Unfortunately I can not find the nodeos core logic in the provided link. Could you reopen the issue, please

**Comment by heifner** [comment]
What exactly are you looking for? `main.cpp` is there and you can follow include files from there.

**Comment by bakasura980** [comment]
I suppose that the implementation is in this include - `appbase/application.hpp`, where I can find it or I need to pull the repo on my PC ?

**Comment by heifner** [comment]
`git submodule update --init --recursive`

Most of the core logic is in:
https://github.com/EOSIO/eos/tree/master/libraries/chain

**Comment by bakasura980** [comment]
Thank you for your support !
