### ISSUE TITLE
nodeos not returning code of '2' when database is dirty

### ISSUE THREAD

**Issue by spoonincode** [EOSIO/eos#7658]
There is code in nodeos that intends to have nodeos exit with a code of 2 when the database is dirty. It does this by looking at the text in the exception that would typically be fired from chainbase, specifically pinnable_mapped_file

However, appbase swallows exceptions from plugin init and simply returns false from `initialize<>()` causing nodeos to exit with a -1 instead.

This is almost certainly a regression from some point in time; though it's not immediately clear to me if it's worth fixing this behavior or not?

**Comment by ndcgundlach** [comment]
Fixed and merged into develop.
