### ISSUE TITLE
Path error in cleos set code/abi

### ISSUE THREAD

**Issue by b1aafulei** [EOSIO/eos#7659]
In the latest `develop` branch with `cleos version full` returning

```
v1.9.0-develop-e549a6ce52c4cd15b36dec98f30c9913b451da5a
```

there seems to be a bug with `cleos set code` and `cleos set abi` when they try to parse the full path of the wasm/abi file.

**Example**

Say I have `~/contracts/eosio.contracts/eosio.token/eosio.token.wasm`.

When I run `cleos set code eosio ~/contracts/eosio.contracts/eosio.token/eosio.token.wasm` I will receive an error saying

```
Reading WASM from /Users/aaron.fu/Users/aaron.fu/contracts/eosio.contracts/
eosio.token/eosio.token.wasm...
Error 3160009: No wasm file found
Error Details:
no wasm file found /Users/aaron.fu/Users/aaron.fu/contracts/eosio.contracts/
eosio.token/eosio.token.wasm
```

Note the duplicated `/Users/aaron.fu/Users/aaron.fu/` in the path.

Same problem for `cleos set abi`, but not for `cleos set contract`, which works fine.

**Usage**

For your reference, the usage for `cleos set code` is

```
Usage: cleos set code [OPTIONS] account [code-file]
```

where `[code-file]` is the `fullpath containing the contract WASM`.

Likewise, the usage for `cleos set abi` is

```
Usage: cleos set abi [OPTIONS] account [abi-file]
```

where `[abi-file]` is the `fullpath containing the contract ABI`.

---

I would like to investigate this issue.

**Comment by heifner** [comment]
Fix merged to develop.
