### ISSUE TITLE
8888 get_info showing wrong version

### ISSUE THREAD

**Issue by NorseGaud** [EOSIO/eos#7669]
`echo $(curl -s http://localhost:8888/v1/chain/get_info) | jq` shows me `"server_version_string": "v1.8.0-rc2-142-g78a4697f3",` when the CMakeLists.txt shows 1.8.1 develop

**Comment by taokayan** [comment]
I found out that string is valued from the output of ```git describe --tags --dirty```. Maybe we need to add a tag of v1.8.1 ?

**Comment by jgiszczak** [comment]
This has been corrected in the current binaries.
