### ISSUE TITLE
Did EOSIO work well on Ubuntu 19.04?

### ISSUE THREAD

**Issue by ashuralyk** [EOSIO/eos#7670]
I want to modify the script file to allow EOSIO building program to be running successfully on my Ubuntu 19.04, but I have no idea what problems I could encounter while its running.

**Comment by spoonincode** [comment]
No reason to think it would have problems. The only "difficulty" that you'll have compiling for 19.04 is that ubuntu doesn't provide an LLVM 4 package for 19.04.

**Comment by spoonincode** [comment]
Closing, no actionable item
