### ISSUE TITLE
help: unable to replay in nodeos 1.8.1 

### ISSUE THREAD

**Issue by elnoxvie** [EOSIO/eos#7679]
Hi all, i am doing a replay with state_history_plugin enable in nodeos v1.8.1. 
The block.log was downloaded from https://eosnode.tools/blocks and blocks_2019-07-23-07-03.tar.gz

However, when i tried to replay, i hit some issues. The screenshot of the logs show as per attached. 

the command i used to do a replay: 
./nodeos --disable-replay-opts --replay-blockchain

The config.ini file 
> agent-name = "DSP"
> p2p-server-address = addr:8888
> http-server-address = 0.0.0.0:8888
> p2p-listen-endpoint = 0.0.0.0:9876
> blocks-dir = "blocks"
> abi-serializer-max-time-ms = 3000
> max-transaction-time = 150000
> wasm-runtime = wabt
> reversible-blocks-db-size-mb = 1024
> contracts-console = true
> p2p-max-nodes-per-host = 1
> allowed-connection = any
> max-clients = 100
> network-version-match = 1 
> sync-fetch-span = 500
> connection-cleanup-period = 30
> http-validate-host = false
> access-control-allow-origin = *
> access-control-allow-headers = *
> access-control-allow-credentials = false
> verbose-http-errors = true
> http-threads=8
> net-threads=8
> read-mode = head
> trace-history-debug-mode = true
> trace-history = true
> plugin = eosio::producer_plugin
> plugin = eosio::chain_plugin
> plugin = eosio::chain_api_plugin
> plugin = eosio::net_plugin
> plugin = eosio::state_history_plugin
> state-history-endpoint = 0.0.0.0:8887
> 

![image](https://user-images.githubusercontent.com/200763/61873292-2f59c900-af18-11e9-836c-7baaa3d1e5eb.png)

Appreciate any inputs on this. Thanks.

**Comment by jgiszczak** [comment]
Can you show the beginning of the log?

**Comment by elnoxvie** [comment]
hi there, here is the beginning of the log. Thanks. 

![image](https://user-images.githubusercontent.com/200763/61919651-2ce38780-af89-11e9-94a7-00df610c79a2.png)

**Comment by jgiszczak** [comment]
And the section after the log index reconstruction completes?

**Comment by elnoxvie** [comment]
> And the section after the log index reconstruction completes?

It never get completed i think. It stops at the first screenshot i show you. This is error is from the physical server. However, on Google Compute engine, this works fine strangely. Both are on ubuntu 18.04

**Comment by i-love-to-code** [comment]
I just hit the exact same error at the exact same block.

**Comment by heifner** [comment]
@elnoxvie & @i-love-to-code Any update? Did you try a different block and newer version of eosio?

**Comment by heifner** [comment]
No reply, closing.
