### ISSUE TITLE
can't run get transaction command!

### ISSUE THREAD

**Issue by jatinmehta420** [EOSIO/eos#768]
Whenever I run ./eosc get transactions inita. Im getting following error:
![capture5](https://user-images.githubusercontent.com/22103300/33164565-63ad5220-d059-11e7-8eb1-a439273c8602.PNG)
2842616ms thread-0   main.cpp:1101                 main                 ] Failed with error: 10
assert_exception: Assert Exception
status_code == 200: Error code 404
: {"code":404,"message":"Not Found","details":"Unknown Endpoint"}
 {"c":404,"msg":"{\"code\":404,\"message\":\"Not Found\",\"details\":\"Unknown Endpoint\"}"}
thread-0  httpc.cpp:113 call
 {"server":"localhost","port":8888,"path":"/v1/account_history/get_transactions","postdata":
{"account_name":"inita"}}
 thread-0  httpc.cpp:117 call

**Comment by heifner** [comment]
Make sure you have the following plugins in your config.ini.
```
plugin = eosio::account_history_plugin
plugin = eosio::account_history_api_plugin
```

**Comment by jatinmehta420** [comment]
I'm still getting that error sir even after editing my config.ini file! @heifner

**Comment by heifner** [comment]
Does `./eosc get info` work?

**Comment by jatinmehta420** [comment]
Yes sir it's working and giving information about head block number and head block id! @heifner

**Comment by heifner** [comment]
You restarted your eosd after editing the config.ini in the data-dir? What error do you get now?

**Comment by jatinmehta420** [comment]
Sir im getting the same error while executing that transaction command!

**Comment by heifner** [comment]
That error is pretty specific. Are you sure you edited the config.ini file in use? Can you repaste the error? You can try adding something like `plugin = junk` to your config.ini file. Then restart with `./eosd --resync` if you get an error about `.. unable to fine plugin: junk` then you know it is the correct config.ini.

**Comment by jatinmehta420** [comment]
That error has been solved sir! Thanks for your help :)
