### ISSUE TITLE
Review copyright headers in files

### ISSUE THREAD

**Issue by b1bart** [EOSIO/eos#7684]
We have inconsistent (from naive observation) inclusion of 

```
/**
 *  @file
 *  @copyright defined in eos/LICENSE
 */
```

at the top of `.cpp` and `.hpp` files.  @nksanthosh, please advise as to what expectations are regarding this notice so that this issue can make a pass at enforcing it across the repo.

**Comment by nksanthosh** [comment]
We can remove these copyright headers from the .cpp and .hpp files. 

The requirement is that the LICENSE file should always be visible with the appropriate license for that repo within the root folder. e.g. https://github.com/EOSIO/eos/blob/master/LICENSE

**Comment by b1bart** [comment]
re-opening until the repo has been cleaned (at least in develop) for the next release

**Comment by b1bart** [comment]
Resolved by #7757
