### ISSUE TITLE
mongo_db_plugin doesn't store genesis block

### ISSUE THREAD

**Issue by conr2d** [EOSIO/eos#7687]
mongo_db_plugin handles `accepted_block` and `applied_irreversible_block` events, and for genesis block, both events aren't emitted, so mongoDB doesn't store genesis block.

When MongoActionReader in demux-eos tries reading blocks from the beginning, because of missing block 1, its process is aborted. To keep consistency, (NodeosActionReader can read block 1 from history_api_plugin), mongoDB needs to store genesis block.

I found that block_state_ptr for genesis block isn't stored in fork_database, so `controller::fetch_block_state_by_[id/number]` don't work in this case. (signed_block_ptr for block 1 is stored in block_log, so it can be retrieved by `controller::fetch_block_by_number`)

I think that mongo_db_plugin needs to store genesis block in its `plugin_startup` step, and there are some possibilities to get genesis block_state_ptr.

1. Fresh started blockchain case, `controller::head_block_state()` will return genesis block_state_ptr.
2. Not fresh blockchain case, I could't find where to get genesis block_state_ptr, so extract build genesis block_state_ptr process from `controller_impl::initialize_blockchain_state()` and name it `controller::genesis_block_state()`. mongo_db_plugin calls it to retrieve genesis block_state_ptr. The one thing I concerned that block_state_ptr, returned by this method, isn't marked validated, because `fork_database::reset()` marks validated as true during `controller_impl::init()`.

Or, please give me any suggestion to solve this issue. Thank you.

**Comment by heifner** [comment]
See comment on #7690
