### ISSUE TITLE
unrecognised option 'contracts-console'

### ISSUE THREAD

**Issue by bts-webber** [EOSIO/eos#7693]
When I run keosd ,this exception is throwing.

error 2019-07-29T01:38:32.572 thread-0  main.cpp:57                   main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::wrapexcept<boost::program_options::unknown_option>
std::exception::what: unrecognised option 'contracts-console'

**Comment by heifner** [comment]
`keosd` `config.ini` contains `contracts-console` which not a supported option for `keosd`. This option should be removed from your `keosd` `config.ini`. You may be pointing your `keosd` at your `nodeos` `config.ini`.

**Comment by jgiszczak** [comment]
If you still have the problem and wish to discuss it further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
