### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by jafri** [EOSIO/eos#7698]
https://github.com/EOSIO/eos/blob/1418543149b7caf8fc69a23621e3db7f3c6d18ad/libraries/chain/authorization_manager.cpp#L301

The strings here don't actually get interpolated

**Comment by heifner** [comment]
Do you have an example log message?

**Comment by jafri** [comment]
This is returned as an error from nodeos, with the exact string quoted. I assume things like ${auth} are to be replaced by the actual auth in question?

**Comment by ndcgundlach** [comment]
Open for six months and never any example of problem.
