### ISSUE TITLE
error version

### ISSUE THREAD

**Issue by prettyCoders** [EOSIO/eos#7704]
![image](https://user-images.githubusercontent.com/36216120/62113608-79abc300-b2e7-11e9-8a17-6ee58b1c1f43.png)

**Comment by jgiszczak** [comment]
The snapshot format changed with the recent releases.  Older snapshots can not be loaded in it.  Use a snapshot in the new format.

If you still have the problem and wish to discuss it further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
