### ISSUE TITLE
1.8.1 hard replay crashed throw bad_alloc 

### ISSUE THREAD

**Issue by DebugFuture** [EOSIO/eos#7705]
nodeos version: 1.8.1
system: 4 core 32 GB

chain-state-db-size-mb = 30000
reversible-blocks-db-size-mb = 2048

plugins: 
plugin = eosio::chain_api_plugin 

eos        | info  2019-07-30T12:29:26.787 nodeos    block_log.cpp:477             repair_log           ] Recovered block 11424000
eos        | info  2019-07-30T12:29:26.795 nodeos    block_log.cpp:477             repair_log           ] Recovered block 11425000
eos        | info  2019-07-30T12:29:26.802 nodeos    block_log.cpp:477             repair_log           ] Recovered block 11426000
eos        | info  2019-07-30T12:29:26.809 nodeos    block_log.cpp:477             repair_log           ] Recovered block 11427000
eos        | info  2019-07-30T12:29:26.817 nodeos    block_log.cpp:477             repair_log           ] Recovered block 11428000
eos        | warn  2019-07-30T12:29:26.835 nodeos    chain_plugin.cpp:958          plugin_initialize    ] 13 St9bad_alloc: std::bad_alloc
eos        | rethrow std::bad_alloc:
eos        |     {"what":"std::bad_alloc"}
eos        |     nodeos  chain_plugin.cpp:958 plugin_initialize
eos        | error 2019-07-30T12:29:26.835 nodeos    main.cpp:114                  main                 ] 13 St9bad_alloc: std::bad_alloc
eos        | rethrow std::bad_alloc:
eos        |     {"what":"std::bad_alloc"}
eos        |     nodeos  chain_plugin.cpp:958 plugin_initialize
eos exited with code 254

**Comment by heifner** [comment]
This should be fixed in 1.8.2 by #7743
