### ISSUE TITLE
I have updated to eos v1.8.1, when activating ONLY_LINK_TO_EXISTING_PERMISSION, got error

### ISSUE THREAD

**Issue by zhopen** [EOSIO/eos#7708]
I activate feature ONLY_LINK_TO_EXISTING_PERMISSION '1a99a59d87e06e09ec5b028a9cbb7749b4a5ad8819004365d02dc4379a8b7241', but return error below. 
Anyone tell me why.
```
[root@eoschain2.zhongxind eoschain2]$curl -X POST http://127.0.0.1:8888/v1/producer/schedule_protocol_feature_activations -d '{"protocol_features_to_activate": ["1a99a59d87e06e09ec5b028a9cbb7749b4a5ad8819004365d02dc4379a8b7241"]}'  |python -m json.tool
{
    "code": 500,
    "error": {
        "code": 3250000,
        "details": [
            {
                "file": "producer_plugin.cpp",
                "line_number": 1114,
                "message": "protocol feature requires preactivation: 1a99a59d87e06e09ec5b028a9cbb7749b4a5ad8819004365d02dc4379a8b7241",
                "method": "schedule_protocol_feature_activations"
            }
        ],
        "name": "protocol_feature_exception",
        "what": "Protocol feature exception"
    },
    "message": "Internal Service Error"
}
```

**Comment by arhag** [comment]
All protocol features other than `PREACTIVATE_FEATURE` require pre-activation which means they cannot be activated using the `schedule_protocol_feature_activations` endpoint. Instead the `eosio::activate` action must be used.

See the [upgrade guide](https://developers.eos.io/eosio-nodeos/docs/consensus-protocol-upgrade-process) for details (particularly the last sentence under the ["Upgrade process for all EOSIO networks" section](https://developers.eos.io/eosio-nodeos/docs/consensus-protocol-upgrade-process#section-upgrade-process-for-all-eosio-networks-including-test-networks-)). Or if you are just starting up a new local test chain, [this guide](https://github.com/EOSIO/eos/issues/7180) will probably be more helpful (you do not need to activate all the protocol features if you do not want to).
