### ISSUE TITLE
1.8.1 Error on Replay St9exception: vector

### ISSUE THREAD

**Issue by ek1977** [EOSIO/eos#7709]
I am trying to replay from scratch using 1.8.1 and the state-history plugin.  I am getting the same error at the same block each time I try.  The error is:

`error 2019-07-31T02:09:14.807 nodeos    controller.cpp:1761           apply_block          ] e.to_detail_string(): 13 St9exception: vector
vector:
    {"trace":{"id":"794d446dd4ce2f08bf8b2065f24d7e250248e8f88e1ceea4f21addc5de0f5eee","block_num":7829351,"block_time":"2018-07-26T06:56:31.000","producer_block_id":"00777767318eeea111b96f2796bbe701f7871d9c2cbfba0d6f1fcdbae0e9cc13","elapsed":55,"net_usage":104,"scheduled":false,"action_traces":[{"action_ordinal":1,"creator_action_ordinal":0,"closest_unnotified_ancestor_action_ordinal":0,"receipt":{"receiver":"blocktwitter","act_digest":"53e4a9911ac44c82ae11d5e1dcb188a1fce6aa6de69bd5bd4d0db1fabc10d39f","global_sequence":96817037,"recv_sequence":73494323,"auth_sequence":[["chaintwitter",39066502]],"code_sequence":1,"abi_sequence":1},"receiver":"blocktwitter","act":{"account":"blocktwitter","name":"tweet","authorization":[{"actor":"chaintwitter","permission":"active"}],"data":"0a5745204c4f564520424d"},"context_free":false,"elapsed":34,"console":"","trx_id":"794d446dd4ce2f08bf8b2065f24d7e250248e8f88e1ceea4f21addc5de0f5eee","block_num":7829351,"block_time":"2018-07-26T06:56:31.000","producer_block_id":"00777767318eeea111b96f2796bbe701f7871d9c2cbfba0d6f1fcdbae0e9cc13","account_ram_deltas":[]}],"failed_dtrx_trace":null},"what":"vector"}
    nodeos  controller.cpp:1365 push_transaction`

**Comment by ndcgundlach** [comment]
This has been open for six months.  If this is still an issue, please provide updated info.
