### ISSUE TITLE
Script to make new plugin does not work properly on Mac

### ISSUE THREAD

**Issue by b1aafulei** [EOSIO/eos#7711]
The script `plugins/eosio-make_new_plugin.sh` does not work properly on Mac.

For example, running

```bash
./eosio-make_new_plugin.sh foo_plugin
```
will generate
```
...
Renaming in files...
sed: 1: "foo_plugin/CMakeLists.txt": invalid command code f
sed: 1: "foo_plugin/include/eosi ...": invalid command code f
sed: 1: "foo_plugin/foo_plugin.cpp": invalid command code f
...
```

while running

```bash
./eosio-make_new_plugin.sh bar_plugin
```

will generate

```
...
Renaming in files...
sed: 1: "bar_plugin/CMakeLists.txt": undefined label 'ar_plugin/CMakeLists.txt'
sed: 1: "bar_plugin/include/eosi ...": undefined label 
        'ar_plugin/include/eosio/bar_plugin/bar_plugin.hpp'
sed: 1: "bar_plugin/bar_plugin.cpp": undefined label 'ar_plugin/bar_plugin.cpp'
...
```

As a result, the text substitution in files failed -- the original text `template_plugin` is not properly changed to `foo_plugin` in either `foo_plugin.cpp` or `foo_plugin.hpp`.

The problem occurs with the line in the script

```bash
find $pluginName -type f -exec sed -i "s/template_plugin/$pluginName/g" {} \;
```

Note that the BSD version of `sed -i` on Mac differs slightly differs from the GNU version of `sed -i` on Linux. To do in-place editing with no backup, you can run with `sed -i` on Linux, but must use `sed -i ''` on Mac.

A small but smart change is desired so as to make the script work properly on both platforms in spite of `sed -i` differences.

For reference see this [answer](https://unix.stackexchange.com/a/92907/363762) at Unix & Linux Exchange.

**Comment by heifner** [comment]
Fixed by #7720
