### ISSUE TITLE
STAT-210 ⁃ Doxygen Issue: Database C API > Single String Index Table

### ISSUE THREAD

**Issue by erichim** [EOSIO/eos#772]
Some of the function documentations seems outdated e.g. load_str. Please help on checking. Thanks.

Link: https://eosio.github.io/eos/group__dbstr.html#ga7684765e32e6b3ab806dbd4e8366320b

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

[~matias.romeo] We assigned you this task of updating the doxygen. If you will not be able to get to this week, please let us know. Thanks.
