### ISSUE TITLE
Missing build/tests/multiversion_paths.conf

### ISSUE THREAD

**Issue by randyhrockypoint** [EOSIO/eos#7722]
Case 68 for the standard test set is failing due to the missing file at build/tests/multiversion_paths.conf.

Has anyone run the full test set recently? 

test 68
      Start 68: nodeos_multiple_version_protocol_feature_mv_test

68: Test command: /home/randy/src/eos-0802/eos/build/tests/nodeos_multiple_version_protocol_feature_test.py "-v" "--clean-run" "--dump-error-detail" "--alternate-version-labels-file" "/home/randy/src/eos-0802/eos/build/tests/multiversion_paths.conf"
68: Test timeout computed to be: 1500
68: unable to kill fc::exception=11 eof_exception: End Of File
68: unexpected end of file
68:     {}
68:     eosio-launcher  json.cpp:434 variant_from_stream
68: unable to kill fc::exception=11 eof_exception: End Of File
68: unexpected end of file
68:     {}
68:     eosio-launcher  json.cpp:434 variant_from_stream
68: unable to kill fc::exception=11 eof_exception: End Of File
68: unexpected end of file
68:     {}
68:     eosio-launcher  json.cpp:434 variant_from_stream
68: unable to kill fc::exception=11 eof_exception: End Of File
68: unexpected end of file
68:     {}
68:     eosio-launcher  json.cpp:434 variant_from_stream
68:  BEGIN
68:  UTC time: 2019-08-04 00:54:14.258478
68:  EOS Client version: 14185431
68:  Processor: x86_64
68:  OS name: Linux-4.15.0-51-generic-x86_64-with-Ubuntu-18.04-bionic
68:  cmd: programs/eosio-launcher/eosio-launcher -k 9
68:  cmd: pkill -9 nodeos
68: Alternate Version Labels File is /home/randy/src/eos-0802/eos/build/tests/multiversion_paths.conf
68:  Test failed.
68:  =================================================================
68:     cmd: pgrep -a nodeos
68:  pgrep output:
68: 24121 nodeos
68: 
68:    =================================================================
68:    Contents of etc/eosio/node_bios/config.ini:
68:    File etc/eosio/node_bios/config.ini not found.
68: Traceback (most recent call last):
68:   File "/home/randy/src/eos-0802/eos/build/tests/nodeos_multiple_version_protocol_feature_test.py", line 86, in <module>
68:     assert exists(alternateVersionLabelsFile), "Alternate version labels file does not exist"
68: AssertionError: Alternate version labels file does not exist
68: 
68: During handling of the above exception, another exception occurred:
68: 
68: Traceback (most recent call last):
68:   File "/home/randy/src/eos-0802/eos/build/tests/nodeos_multiple_version_protocol_feature_test.py", line 192, in <module>
68:     TestHelper.shutdown(cluster, walletMgr, testSuccessful, killEosInstances, killWallet, keepLogs, killAll, dumpErrorDetails)
68:   File "/home/randy/src/eos-0802/eos/build/tests/TestHelper.py", line 156, in shutdown
68:     cluster.dumpErrorDetails()
68:   File "/home/randy/src/eos-0802/eos/build/tests/Cluster.py", line 1427, in dumpErrorDetails
68:     fileNames=Cluster.__findFiles(path)
68:   File "/home/randy/src/eos-0802/eos/build/tests/Cluster.py", line 1414, in __findFiles
68:     it=os.scandir(path)
68: FileNotFoundError: [Errno 2] No such file or directory: 'var/lib/node_bios'
68/68 Test #68: nodeos_multiple_version_protocol_feature_mv_test ...***Failed    0.20 sec

**Comment by arhag** [comment]
Our CICD system automatically generates the multiversion_paths.conf file after bringing in the build directory of previous build of v1.7.0 of EOSIO. So, that particular test will not be able to successfully run if you only build one version of EOSIO from source and then run the test.

If you would like to run the test manually, you need to first built v1.7.0 of EOSIO and then manually create the multiversion_paths.conf file, place it in the tests directory, and the contents should be:
```
170=/path/to/1.7.0/build/directory
```

Actually, I think you should be able to get away with just placing the v1.7.0 nodeos binary in a `programs/nodeos/` subdirectory within the path included in the multiversion_paths.conf file.

**Comment by randyhrockypoint** [comment]
Got it. Will check it out. Might be good to add this to the error message output of this test... 

Thanks
Randy
