### ISSUE TITLE
Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)

### ISSUE THREAD

**Issue by jatinmehta420** [EOSIO/eos#773]
I ran a command to generate currency.wast file but getting an error. 
Following is the command:
$ cmake -DBINARYEN_BIN=~/binaryen/bin -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib ..
Following is the error that i have encountered:
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Doxygen not found.  Contract documentation will not be generated.
![capture6](https://user-images.githubusercontent.com/22103300/33204216-dc478596-d128-11e7-9ac2-63bacf48fb16.PNG)

**Comment by heifner** [comment]
Doxygen is only needed if you wish to generate the doxygen documentation. It is not needed to generate currency.wast.

**Comment by 139Vaibhav** [comment]
How to solve it in windows?
