### ISSUE TITLE
Can't build deb package

### ISSUE THREAD

**Issue by tuchinsky** [EOSIO/eos#7731]
I successfully build eosio using **scripts/eosio_build.sh**. But **scripts/generate_deb.sh** causes error:

```
root@build:~/eos/scripts# ./generate_deb.sh 
Package: 
Version: -1
Section: devel
Priority: optional
Depends: libc6, libgcc1, libssl1.1, libicu60, libstdc++6, libtinfo5, zlib1g, libusb-1.0-0, libcurl3-gnutls
Architecture: amd64
Homepage: 
Maintainer: 
Description: 
cp: cannot stat '/licenses/eosio/*': No such file or directory
```

My steps:
1) git clone https://github.com/EOSIO/eos.git
2) cd eos
3) git checkout v1.8.1
4) git submodule update --init --recursive
5) cd scripts
6) ./eosio_build.sh
7) generate_deb.sh

How do I build deb package?

**Comment by jalbiero** [comment]
@tuchinsky That's not the correct way to generate a .deb package. Do the following:

1. Build the blockchain code (your steps 1-6)
2. Go to **build/packages** directory
3. Execute the following:
```
$ chmod +x generate_package.sh 
$ ./generate_package.sh deb
```

**Comment by tuchinsky** [comment]
@jalbiero after step 6 (eosio_buid.sh) I do not have a file **generate_package.sh**, only file with **.in** extension:

```
# pwd
/root/eos/scripts
# ls -lah|grep generate_package.sh
-rw-r--r--  1 root root  852 Aug 15 11:18 generate_package.sh.in
```

**Comment by jalbiero** [comment]
You forgot the step 2 of my post: Go to **build/packages** directory (deduced from your latest post, go to **/root/eos/build/packages**). CMake templates files (*.in) results are part of the build, so a version without .in extension will be located inside _build_ directory tree.

**Comment by tuchinsky** [comment]
@jalbiero thanks!
