### ISSUE TITLE
How to debug eos/nodeos with vscode

### ISSUE THREAD

**Issue by yiyanwannian** [EOSIO/eos#7733]
I can not find any useful vscode debug documents

**Comment by heifner** [comment]
@spoonincode answered on dev telegram which is a better place to get help instead of opening an issue.

**Comment by yiyanwannian** [comment]
I can debug my eosio on WSL with vscode now, and this is my launch.json file:
//" --hard-replay-blockchain"
//"miDebuggerPath": "/usr/bin/lldb-mi-6.0"
{
    "version": "0.2.0",
    "configurations": [
       { 
          "name": "debug (attach)",
          "type": "cppdbg",
          "request": "attach",
          "program": "${workspaceFolder}/build/programs/nodeos/nodeos",
          "processId": "${command:pickProcess}",
          "MIMode": "gdb",
       },
       {
          "name": "debug (launch)",
          "type": "cppdbg",
          "request": "launch",
          "program": "${workspaceFolder}/build/programs/nodeos/nodeos",
          "args": [
            "-e", 
            "-p", 
            "eosio", 
            "--plugin",
            "eosio::producer_plugin", 
            "--plugin", 
            "eosio::chain_api_plugin", 
            "--plugin",
            "eosio::http_plugin", 
            "--plugin",
            "eosio::db_size_api_plugin",
            "--access-control-allow-origin='*'", 
            "--contracts-console", 
            "--http-validate-host=false", 
            "--verbose-http-errors", 
            "--hard-replay-blockchain",
         ],
          "stopAtEntry": false,
          "cwd": "${workspaceFolder}",
          "environment": [],
          "externalConsole": false,
          "MIMode": "gdb",
       }
    ]
 }


you can download and rename to launch.json
