### ISSUE TITLE
Getting "symbol precision mismatch" while sending some EOS tokens

### ISSUE THREAD

**Issue by rafaelekol** [EOSIO/eos#7740]
I am trying to send EOS token "EOSDT"(eosdtsttoken) but getting this error:

`Internal Service Error - Code: 3050003 - What 3050003 - detail: assertion failure with message: symbol precision mismatch - pending console output:  - ` 

Sending parameters are:
```
{
    "from": "fromaccount",
    "to": "toaccount",
    "quantity": "0.1234 EOSDT",
    "memo" : ""
    }
```

Other tokens like MEETONE, PGL, NDX are sending without error.

**Comment by spoonincode** [comment]
The EOSIO project doesn't have anything to do with EOSDT so we can't really say for sure. However it looks like they crated their token with a precision of 9 which I believe means (at least with the eosio.token contract) you must provide 9 digits of precision even when it would otherwise not matter. If you change the quantity to "0.123400000 EOSDT" does it work?

**Comment by rafaelekol** [comment]
You are right. The problem was precision point. I tried to search for this token precision point information, but couldn't find. Where can I check EOS tokens(EOSDT, Everipedia, Newdex, etc) precision points?

**Comment by spoonincode** [comment]
That question is probably better asked some place like https://eosio.stackexchange.com/

**Comment by rafaelekol** [comment]
There is no answer for my question
https://eosio.stackexchange.com/questions/4786/where-i-can-get-eos-tokens-number-precision-information
Any help here?

**Comment by spoonincode** [comment]
If the token is based off the eosio.token contract, you could get the `stat` table and see what the precision is there. For example, for EOS
```
$ cleos get table eosio.token EOS stat
{
  "rows": [{
      "supply": "1024177197.2358 EOS",
      "max_supply": "10000000000.0000 EOS",
      "issuer": "eosio"
    }
  ],
  "more": false
}
```
For EOSDT
```
$ programs/cleos/cleos get table eosdtsttoken EOSDT stat
{
  "rows": [{
      "supply": "5562623.798696016 EOSDT",
      "max_supply": "70000000.000000000 EOSDT",
      "issuer": "eosdtcntract"
    }
  ],
  "more": false
}
```

**Comment by rafaelekol** [comment]
Thank you very much

**Comment by alvinoktavbitcoin** [comment]
Hi rafa, so can we send eosdt, I send eosdt using 9 decimals but still error
