### ISSUE TITLE
nodeos 1.8 got stale when the first p2p peer went down

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#7749]
I took down one of my nodes for upgrade, and all other (1.8.0 and 1.8.1) nodes which had it as the first line in p2p list have stalled and did not advance the head any more. After restarting nodeos, they picked up from the rest of p2p list and went further.

It seems to be similar to what EOS Wiki observed last week with their production nodes, and some other users reported about nodes being stuck after network connectivity problems.

**Comment by cc32d9** [comment]
the node was stopped gracefully, which means its peers received a normal TCP connection closing.

**Comment by cc32d9** [comment]
logging.json is set for error level only, so the logs did not have anything for that event.

**Comment by heifner** [comment]
Appears to be fixed by #7750.
