### ISSUE TITLE
Build script for ubuntu does not build all dependencies

### ISSUE THREAD

**Issue by Rapso** [EOSIO/eos#775]
I build eos using `./build.sh ubuntu ` but it turns out that wasm file for currency contract is missing because no wasm compiler has been found. I have to install wasm compiler manualy. I dont know if it is by script design but manually installing of wasm compiler is not mentioned in the Setting up a build/development environment section

**Comment by heifner** [comment]
The build script should have built wasm for you. See `../script/install_dependencies.sh` which is called by `./build.sh ubuntu`.

**Comment by jatinmehta420** [comment]
In case if you want to install wasm compiler dependency manually, try with this:
mkdir  ~/wasm-compiler
cd ~/wasm-compiler
git clone --depth 1 --single-branch --branch release_40 https://github.com/llvm-mirror/llvm.git
cd llvm/tools
git clone --depth 1 --single-branch --branch release_40 https://github.com/llvm-mirror/clang.git
cd ..
mkdir build
cd build
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=.. -DLLVM_TARGETS_TO_BUILD= -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly -DCMAKE_BUILD_TYPE=Release ../
make -j4 install
I was facing same issue and that helped me!

**Comment by heifner** [comment]
If you can provide any insight into why `./build.sh ubuntu` did not install wasm compiler. Please let us know.

**Comment by jatinmehta420** [comment]
I dont know sir but that worked for me anyway! @heifner 
If you @Rapso  want to publish a currency contract in the currency account then try with this:
./eosc set contract currency ../../contracts/currency/currency.wast ../../contracts/currency/currency.abi
because ./build has already built currency .wast and currency.abi files for you.
