### ISSUE TITLE
the nodeos exit with no exception when using the eosio::mongo_db_plugin

### ISSUE THREAD

**Issue by ling2yt** [EOSIO/eos#7755]
first i use the docker image eosio/eos-dev:v1.6.0-rc1 to start nodeos network without mongo_db_plugin. 
then i want to change the memory db to mongo_db because of the big data that i turn on history_api_plugin and filter-on=*.
but the nodeos exit with no error message when i set --hard-replay-blockchain to replay the transactions into mongodb with the nodeos data folder.
the log is as follows:

> info  2019-08-13T05:19:53.485 thread-1  mongo_db_plugin.cpp:953       _process_accepted_bl ] block_num: 23000
info  2019-08-13T05:19:54.253 thread-1  mongo_db_plugin.cpp:482       consume_blocks       ] process_accepted_block,       time per: 847, size: 1143, time: 969254
info  2019-08-13T05:19:55.961 thread-1  mongo_db_plugin.cpp:495       consume_blocks       ] process_irreversible_block,   time per: 747, size: 2285, time: 1708060
info  2019-08-13T05:19:56.561 thread-1  mongo_db_plugin.cpp:457       consume_blocks       ] process_applied_transaction,  time per: 524, size: 1142, time: 599536
info  2019-08-13T05:19:57.021 thread-1  mongo_db_plugin.cpp:953       _process_accepted_bl ] block_num: 24000
info  2019-08-13T05:19:57.867 thread-1  mongo_db_plugin.cpp:953       _process_accepted_bl ] block_num: 25000
info  2019-08-13T05:19:57.916 thread-1  mongo_db_plugin.cpp:482       consume_blocks       ] process_accepted_block,       time per: 845, size: 1142, time: 965209
info  2019-08-13T05:19:59.632 thread-1  mongo_db_plugin.cpp:495       consume_blocks       ] process_irreversible_block,   time per: 751, size: 2284, time: 1716309
info  2019-08-13T05:20:00.248 thread-1  mongo_db_plugin.cpp:457       consume_blocks       ] process_applied_transaction,  time per: 539, size: 1141, time: 615802
info  2019-08-13T05:20:01.457 thread-1  mongo_db_plugin.cpp:953       _process_accepted_bl ] block_num: 26000
info  2019-08-13T05:20:01.627 thread-1  mongo_db_plugin.cpp:482       consume_blocks       ] process_accepted_block,       time per: 864, size: 1141, time: 986327
     27300 of 31368
info  2019-08-13T05:20:02.094 thread-0  controller.cpp:319            replay               ] 27298 blocks replayed
info  2019-08-13T05:20:02.094 thread-0  controller.cpp:332            replay               ] 0 reversible blocks replayed
info  2019-08-13T05:20:02.095 thread-0  controller.cpp:336            replay               ] replayed 27298 blocks in 83 seconds, 3.06608150780276922 ms/block
info  2019-08-13T05:20:02.095 thread-0  chain_plugin.cpp:731          plugin_startup       ] starting chain in read/write mode
info  2019-08-13T05:20:02.095 thread-0  chain_plugin.cpp:735          plugin_startup       ] Blockchain started; head block is #27300, genesis timestamp is 2018-06-01T12:00:00.000
info  2019-08-13T05:20:02.125 thread-0  mongo_db_plugin.cpp:1349      ~mongo_db_plugin_imp ] mongo_db_plugin shutdown in process please be patient this can take a few minutes
info  2019-08-13T05:20:03.370 thread-1  mongo_db_plugin.cpp:495       consume_blocks       ] process_irreversible_block,   time per: 763, size: 2283, time: 1743645
info  2019-08-13T05:20:03.370 thread-1  mongo_db_plugin.cpp:443       consume_blocks       ] draining queue, size: 5506
info  2019-08-13T05:20:03.953 thread-1  mongo_db_plugin.cpp:457       consume_blocks       ] process_applied_transaction,  time per: 528, size: 1101, time: 582165
info  2019-08-13T05:20:04.992 thread-1  mongo_db_plugin.cpp:953       _process_accepted_bl ] block_num: 27000
info  2019-08-13T05:20:05.235 thread-1  mongo_db_plugin.cpp:482       consume_blocks       ] process_accepted_block,       time per: 837, size: 1101, time: 922587
info  2019-08-13T05:20:06.919 thread-1  mongo_db_plugin.cpp:495       consume_blocks       ] process_irreversible_block,   time per: 764, size: 2203, time: 1683655
info  2019-08-13T05:20:06.919 thread-1  mongo_db_plugin.cpp:443       consume_blocks       ] draining queue, size: 0
info  2019-08-13T05:20:06.919 thread-1  mongo_db_plugin.cpp:505       consume_blocks       ] mongo_db_plugin consume thread shutdown gracefully

i start the nodeos with the common genesis conf and the cmd is like :

> nodeos -e $PRODUCER\
    --plugin eosio::producer_plugin \
    --plugin eosio::chain_api_plugin \
    --plugin eosio::history_api_plugin \
    --plugin eosio::http_plugin \
    --plugin eosio::mongo_db_plugin \
    -d $DATA_PATH \
    --config-dir $CONFIG_PATH \
    --http-server-address=$HTTP_SERVER_ADDRESS \
    --p2p-peer-address my-nodeos:9876 \
    --chain-state-db-size-mb=71680 \
    --mongodb-wipe \
    --signature-provider=$SIGNATURE_PROVIDER \
    --access-control-allow-origin=* \
    --contracts-console \
    --mongodb-uri=mongodb://127.0.0.1:27017/icbceos \
    --http-validate-host=false \
    --verbose-http-errors \
    --mongodb-filter-on=* \
    --mongodb-queue-size=2048 \
    --abi-serializer-max-time-ms=500000 \
    --hard-replay-blockchain

**Comment by spoonincode** [comment]
> v1.6.0-rc1

This is very old. Do you see the problem on 1.8?

**Comment by ling2yt** [comment]
Because i want to run it in docker, but the 1.8 version don't support docker any more.
Is the 1.6 have the problem for sure?
Can I run the the 1.8 with the 1.6 data without any changed?
And why the 1.8 doesn't support docker any more?
