### ISSUE TITLE
C-file for state history plugin

### ISSUE THREAD

**Issue by vtsurka** [EOSIO/eos#7759]
@tbfleming What do you think about switch to new C-File https://github.com/EOSIO/fc/pull/107 in state history plugin? Maybe add this to backlog?

**Comment by heifner** [comment]
Thanks @vtsurka for the idea. Our testing showed very little improvement, but we merged it anyway.

**Comment by vtsurka** [comment]
@heifner thank for your great work) I think its more important to have same interface for work with files.
