### ISSUE TITLE
Run validate_reflection.py on repo

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#7762]
Need to run:
./tools/validate_reflection.py plugins/ programs/ libraries/ --recurse --extension "cpp" --extension "hpp" -e
and fix all errors that are identified.

Already analysed errors:

struct additional_block_signatures_extension : fc::reflect_init {
Most likely it is that the regex didn't account for only having one word between ":" and "{"

class console_appender final : ...
Most likely it is that the regex didn't account for "final"

This needs to be completed before #7761 can be merged.

**Comment by heifner** [comment]
Fixed in #8409
