### ISSUE TITLE
net_plugin unexpected message length error message not useful

### ISSUE THREAD

**Issue by jgiszczak** [EOSIO/eos#7766]
When net_plugin logs an unexpected message length error, it logs the IP and port of the peer the unrecognized message came from, even when the peer is listed by name in the peer list.  Net API plugin only accepts exact matches for `net disconnect`.  It would be much more useful if net_plugin would log the peer list entry rather than the resolved IP.

**Comment by heifner** [comment]
Fix is in `v1.8.5`
