### ISSUE TITLE
Try to transfer, the memo is '火幣', get the error

### ISSUE THREAD

**Issue by lystrosaurus** [EOSIO/eos#7768]
`{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: all characters must be numbers!","file":"wasm_interface.cpp","line_number":924,"method":"eosio_assert"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":72,"method":"exec_one"}]}}`

`{"args":{"quantity":"0.1022 EOS","memo":"火幣","from":"bittrexacct1","to":"huobideposit"},"code":"eosio.token","action":"transfer"}`

**Comment by spoonincode** [comment]
the assert "all characters must be numbers!" comes from the huobideposit contract. You will have to contact the author of that contract for support, we have no idea how it works
