### ISSUE TITLE
STAT-200 ⁃ deployment optimizations

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#777]
on net_plugin, increased the limit on client connections and made it configurable. also change the behavior of initial connections so that if it has never connected to a peer, keep trying asap to connect to at least one, then back off for retrying others. 

on launcher, give it a list of host IPs for it to use for remote configuration. Second, format the aliases to use leading 0's as necessary so that these names string-sort as expected. Third, increase the number of connections used in the star configuration and allow the mesh configuration to specify redundant connections to insure as quick a connection as possible.

**Comment by pmesnier** [comment]
all features implemented and merged via #779

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

Pass.
All nodes show 21 for the given shell command in a stable testnet network.
