### ISSUE TITLE
Hello, I'm doing 

### ISSUE THREAD

**Issue by lsg1213** [EOSIO/eos#7771]

**Comment by lsg1213** [comment]
![image](https://user-images.githubusercontent.com/42692200/63208565-92521080-c110-11e9-9203-eb1e0cbec5e4.png)

It doesn't work, all of contract code is same with https://developers.eos.io/eosio-home/docs/your-first-contract

**Comment by spoonincode** [comment]
Is it stuck? Do you only have 1 CPU core?

**Comment by lsg1213** [comment]
> Is it stuck? Do you only have 1 CPU core?

Yes I gave the 1 core to virtual box.

**Comment by spoonincode** [comment]
That's a known problem with eosio.cdt -- it needs at least two cores otherwise it gets stuck. Add another core to your virtual box.
