### ISSUE TITLE
[Feature Request] Account notification on modification of resources

### ISSUE THREAD

**Issue by jafri** [EOSIO/eos#7781]
When a contract uses or releases your RAM, it should have the account as a receiver of the TX.

Without this, users may see tokens or other items be added/removed from their accounts without proper notifications as a receiver.

Perhaps a similar thing should be applied to CPU/NET?

**Comment by aclark-b1** [comment]
Unfortunately this would be very difficult, if not impossible, to enforce at the protocol layer.
