### ISSUE TITLE
currency push sample command fails on testnode

### ISSUE THREAD

**Issue by eluzgin** [EOSIO/eos#780]
Update documentation for the EOS sample commands. I went over all of them and found the following one failing:
./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":50}' --scope currency,inita
1795434ms thread-0   main.cpp:1058                 operator()           ] Converting argument to binary...
1795550ms thread-0   main.cpp:1125                 main                 ] Failed with error: 10 assert_exception: Assert Exception
status_code == 200: Error code 400
: {"code":400,"message":"Bad Request","details":"missing required authority (3030001)\nTransaction is missing required authorization from currency\n\n\n\n\n\n\n"}

    {"c":400,"msg":"{\"code\":400,\"message\":\"Bad Request\",\"details\":\"missing required authority (3030001)\\nTransaction is missing required authorization from currency\\n\\n\\n\\n\\n\\n\\n\"}"}
    thread-0  httpc.cpp:113 call

    {"server":"localhost","port":8888,"path":"/v1/chain/push_transaction","postdata":{"ref_block_num":1003,"ref_block_prefix":3960810133,"expiration":"2017-11-25T15:30:25","scope":["currency","inita"],"read_scope":[],"messages":[{"code":"currency","type":"transfer","authorization":[],"data":"0000001e4d75af46000000000093dd743200000000000000"}],"signatures":[]}}
    thread-0  httpc.cpp:117 call

**Comment by heifner** [comment]
`./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":50}' --scope currency,inita --permission currency@active`

You are missing the `--permission currency@active`
