### ISSUE TITLE
STAT-201 ⁃ Add configuration options for new depth limit and block time.

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#782]
Add configuration for pending transaction queue depth limit, currently hardcoded to 1000.
Add configuration for generating block time limit, currently hardcoded to 200ms.

Acceptance Test Criteria:
local test (to avoid affecting configuration for testnet and possibly loosing a nights work):

1. set configuration parameter "pending-txn-depth-limit" to 20 (or something low to make testing easier, may need lower number for faster machines, or possibly slower for real slow machines)
1. start up 1 node with 21 producers and one node with no producers
1. send more than 10 (or whatever number you chose) transactions and observe that transactions indicate they were rejected
1. set configuration parameter "gen-block-time-limit-msec" to 10ms (trying to set this low enough to verify that transactions get pushed back to be sent in another block) and set "pending-txn-depth-limit" to 1000 (or remove it and use default)
1. start up of 1 node with 21 producers and one node with no producers both from a clean start (delete blockchain)
1. wait for normal block production to occur
1. send 1000 transactions and verify that the at least some transactions reported in a different block (you can use "./eosc transaction <transaction id> and verify first transaction reports one block number and the last reports a different block number)

testnet (this change does nothing to the stability of the testnet, so if the similar test resulted in problems last night it will depend on what other changes have happened):

1. standard testnet configuration ("pending-txn-depth-limit" set to 1000 or not set, if config param is set to something else, then substitute that number for 1000 below
1. send over 1000 transactions to one node and verify that only 1000 are accepted and the remainder are rejected

**Comment by blockone-syncclient** [comment]
➤ Dhanesh Valappil commented:

Rejects when pending txns breaches 1000 (the default limit)

**Comment by heifner** [comment]
Resolved by #781
