### ISSUE TITLE
nodeos 1.8.2 takes too much bandwith at times

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#7829]
Upgrade nodeos and all connected peers to 1.8.2 on EOS Mainnet.  Sometimes get very high network bandwidth usage.  Restarting nodeos clears the problem.

Example "iftop" output:

![image](https://user-images.githubusercontent.com/26171839/63949724-d3b7b980-ca48-11e9-8d0b-9bb5af250c4e.png)

detailed logging starts at 14:27
[log.txt.gz](https://github.com/EOSIO/eos/files/3556095/log.txt.gz)

**Comment by matthewdarwin** [comment]
Log is from "mainnet-peer8".
Mainnet-public9 has 125 p2p connections to the general public.

**Comment by matthewdarwin** [comment]
![image](https://user-images.githubusercontent.com/26171839/63951185-4c1f7a00-ca4b-11e9-99e7-9b33b171826e.png)

Now connection to mainnet-public8 is also having the same issue. (It also has 125 p2p connections to the general public)

**Comment by matthewdarwin** [comment]
Bandwidth usage is more-or-less back to normal now without me restarting any of the 3 nodeos servers involved.  Oops spoke too son... public7 now is high bandwidth.

**Comment by heifner** [comment]
Fixed in 1.8.3. Thanks @matthewdarwin for reporting and testing early versions of 1.8.3.
