### ISSUE TITLE
cant run eosc commands on Server using my IP address!

### ISSUE THREAD

**Issue by jatinmehta420** [EOSIO/eos#783]
I have configured my RPC interface with "http-server-endpoint" and Chain_API plugin in the config.ini file.
Whenever I run eosc commands on localhost, Im able to get relevant output. But when I use IP address of my cloud server, I get following error:
Failed to connect to eosd at localhost:8888; is eosd running?
![capture8](https://user-images.githubusercontent.com/22103300/33238406-0c388832-d2b3-11e7-94a0-89d02f175729.PNG)

Although my eosd was running. When I ran my eosd after editing config.ini file, I got following output:
![capture7](https://user-images.githubusercontent.com/22103300/33238339-c1e12e2a-d2b1-11e7-9951-5f4e87089aae.PNG)
Blocks were still producing and my eosd was running.

**Comment by jatinmehta420** [comment]
Yes sir I have

**Comment by jatinmehta420** [comment]
@heifner Sir Im in trouble please help me with this!

**Comment by heifner** [comment]
If your eosd is not running on localhost then you have to pass host and port to eosc. See eosc help for host and port options.

**Comment by jatinmehta420** [comment]
Sir I have provided that too but eosc is not accessing eosd on that ip address and port

**Comment by jatinmehta420** [comment]
Sir my eosd is running perfectly on provided IP address and all the plugins are successfully loaded but still eosc is not able to access eosd on my IP address although I've provide host and port in the eosc commands! @heifner

**Comment by nanonano7** [comment]
can you access the api via browser?

**Comment by jatinmehta420** [comment]
no sir i cant

**Comment by nanonano7** [comment]
well then its not eosc. can you provide your eosd config?

**Comment by Gagan0436** [comment]
@nanonano7 Hi I'm having the same issue after I changed http-server-endpoint with myHost:myPort. eosd config has http_plugin:
![image](https://user-images.githubusercontent.com/29055755/33654985-d2d26850-da97-11e7-87f5-0e9bf5d95f3c.png)
Although i can access API via browser to get chain-info with following url
http://myHost:myPort/v1/chain/get_info
![image](https://user-images.githubusercontent.com/29055755/33655722-e34fa844-da99-11e7-8c49-7ceda8a893e5.png)
But can't access any other info related to wallet-list, account-info, etc. 
Also i faced the same error as @jatinmehta420 faced.
![image](https://user-images.githubusercontent.com/29055755/33655608-873b1124-da99-11e7-89aa-2eb107690a29.png)
Please help!

**Comment by heifner** [comment]
Please use telegram `EOS Developers` or `EOS.IO Testnet Developers` for support.

If `myPort != 8888` then you will need to specify port on the command line to `eosc`.
