### ISSUE TITLE
unable to find plugin: eosio::wallet_api_plugin

### ISSUE THREAD

**Issue by limchienhoo** [EOSIO/eos#7833]
A new developer of EOSIO，hope some help!

programming environment：
win10-pro+ubuntu18.04LTS+eosio_1.8.1

**sudo apt install ./eosio_1.8.1-1-ubuntu-18.04_amd64.deb
cleos --help
nodeos --help
keosd --help**
All above was certained  to be correct.
when I went to run eosio，it ecurred error like follow:

lim@PC-201908291114:/home$ **nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::chain_api_plugin --plugin eosio::account_history_api_plugin**

error 2019-08-30T10:35:12.304 nodeos    main.cpp:120                  main                 ] /home/cicd/eos/libraries/appbase/application.cpp(435): Throw in function appbase::abstract_plugin &appbase::application::get_plugin(const std::__1::string &) const
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: **unable to find plugin: eosio::wallet_api_plugin**

**Comment by heifner** [comment]
`wallet_api_plugin` is no longer supported as part of `nodeos`. Use `keosd` instead. 
https://developers.eos.io/keosd/docs

**Comment by limchienhoo** [comment]
so how can i run nodeos?

**Comment by heifner** [comment]
https://developers.eos.io/eosio-nodeos/docs/running-nodeos
