### ISSUE TITLE
Docs Update Required - When setting up a contract

### ISSUE THREAD

**Issue by idancali** [EOSIO/eos#784]
We need to add a reminder in the main guide to let the developer know that they need to unlock their wallet after restarting their `eosd` node.

**Comment by rbw3821** [comment]
Public wiki to be updated this week and will include a note on this in the CLI Wallets section.  Note that this is an issue related to restarting your wallet manager, which could be either nodeos or keosd.

**Comment by idancali** [comment]
great, thanks for the update @rbw3821
