### ISSUE TITLE
transaction failed multiple times after setting contract

### ISSUE THREAD

**Issue by fufesou** [EOSIO/eos#7840]
eos version v1.6.2, centos 7。
steps
1. set contract
2. push action

transaction is likely to executed by nodeos, but failed to sync to other nodes. As flowing pic shows.
![image](https://user-images.githubusercontent.com/13586388/64183906-2f48d380-ce9d-11e9-8052-82560b0cd6a3.png)

The block_num in the results changes every time I call get transaction.(0.5 sec later)
![image](https://user-images.githubusercontent.com/13586388/64184066-746d0580-ce9d-11e9-8962-76342fd9441e.png)

No results could be returned when I call get transaction on the other nodes on the same chain.

It seems the transaction tried and failed many times.
The transaction may be executed every "on_incoming_block" was triggered.

Only the first "push action" failed many times, while the second works correctly.
And this is not always happened, but seemed to be frequently on my machines.

**Comment by heifner** [comment]
v1.6.2 is an old unsupported version. Please upgrade to the latest and try again. Also you can enable `producer_plugin` `transaction_tracing` logging at `debug` level to see the results of your transaction execution. 

https://github.com/EOSIO/eos/blob/develop/programs/nodeos/logging.json

**Comment by fufesou** [comment]
> v1.6.2 is an old unsupported version. Please upgrade to the latest and try again. Also you can enable `producer_plugin` `transaction_tracing` logging at `debug` level to see the results of your transaction execution.
> 
> https://github.com/EOSIO/eos/blob/develop/programs/nodeos/logging.json

Thank you for your suggestion.
But v1.6.2 is the production version in our products. I may not upgrade to the latest easily.
I have enabled the debug level to trace the transaction execution, but fail to find out the reason. I should try that for 2 more days.

**Comment by heifner** [comment]
v1.6.2 has known security issues addressed in later patch releases of 1.6.x. I recommend you do not use it in a production environment. At the very least you should upgrade to v1.6.6, but even that version has known security issues.

**Comment by fufesou** [comment]
> v1.6.2 has known security issues addressed in later patch releases of 1.6.x. I recommend you do not use it in a production environment. At the very least you should upgrade to v1.6.6, but even that version has known security issues.

Thank you for reminding.
