### ISSUE TITLE
Blank bid names being allowed

### ISSUE THREAD

**Issue by eosauthority** [EOSIO/eos#7857]
https://eosauthority.com/transaction/dc1b7f62c1b953057fb0c052ae7509ae38cc1ec8c3704e942dc8675b91b0db49?network=eos

It looks like the new name being bid of can be blank.
{
  "bidder": "guydgnjygige",
  "newname": "",
  "bid": "0.3000 EOS"
}

This was in June 2018. This is probably fixed now.

Other examples are
https://eosauthority.com/transaction/1999e80bc696e8a3745333406d971a4e50c67e36b62f0164e9734ba472682575
https://eosauthority.com/transaction/34912ce84dc72c4ea51e95a780f4afb8a86be52f5a5a4513aa9511637a3b7033
https://eosauthority.com/transaction/52b2a68d83fbbe747dd071a4098358e4f6e7e34fe2df88a14639331f9d90f1ab

**Comment by UMU618** [comment]
Yes, it's fixed.

https://github.com/EOSIO/eosio.contracts/blob/a4b7aee49543907fdb512f38e6d0467bbe232d67/contracts/eosio.system/src/name_bidding.cpp#L15
