### ISSUE TITLE
Why compile Error?

### ISSUE THREAD

**Issue by kenneth** [EOSIO/eos#787]
eos/plugins/chain_plugin/chain_plugin.cpp:319:40: error: no member named 'version_int' in 'appbase::application'
      itoh(static_cast<uint32_t>(app().version_int())),
                                 ~~~~~ ^
[ 79%] Building CXX object libraries/egenesis/CMakeFiles/embed_genesis.dir/embed_genesis.cpp.o
1 error generated.

**Comment by heifner** [comment]
git submodule update
