### ISSUE TITLE
Error 3070000: WASM Exception

### ISSUE THREAD

**Issue by johnchenyan** [EOSIO/eos#7878]
./cleos --wallet-url http://127.0.0.1:8899 set contract eosio /home/cq/eos/build/unittests/contracts/eosio.bios

error: 
Reading WASM from /home/cq/eos/build/unittests/contracts/eosio.bios/eosio.bios.wasm...
Publishing contract...
Error 3070000: WASM Exception
Error Details:
env.is_feature_activated unresolveable

**Comment by spartucus** [comment]
https://eosio.stackexchange.com/a/4660

**Comment by jgiszczak** [comment]
Or more directly: https://github.com/EOSIO/eos/issues/7180

Before eosio.bios can be installed, a feature must be pre-activated.  The required curl command is in the link.  I'd simply paste it here but it includes a hexadecimal feature code I'm not completely certain won't change and I'd rather update as few places as possible.

Documentation updates to the BIOS boot procedure (among other things) are in progress.

**Comment by johnchenyan** [comment]
> Or more directly: #7180
> 
> Before eosio.bios can be installed, a feature must be pre-activated. The required curl command is in the link. I'd simply paste it here but it includes a hexadecimal feature code I'm not completely certain won't change and I'd rather update as few places as possible.
> 
> Documentation updates to the BIOS boot procedure (among other things) are in progress.

already be solved,  thx
