### ISSUE TITLE
Unable to broadcast a signed tx to the blockchain

### ISSUE THREAD

**Issue by wangsen0518** [EOSIO/eos#7894]
version:v1.8.1
cpu:8 cores
ram:16g
no setting read-mode = read-only
api:push_transaction

when i send a signed tx to the blockchain via the api named push_transaction, it always return the txID, but sometimes i can't find the tx in https://eospark.com. i find it in my local eos node only. and after a valid period what i set in the tx ,i can't find the tx in my local eos node yet.

here the logs:
error 2019-09-10T09:36:43.670 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.push_transaction
error 2019-09-10T09:36:43.670 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.push_transaction
error 2019-09-10T09:36:43.670 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.push_transaction
error 2019-09-10T09:36:43.670 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.push_transaction
error 2019-09-10T09:36:43.670 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.push_transaction

**Comment by wangsen0518** [comment]
> It's possible that your transaction has not reached to the BP nodes, or get subjectively rejected. In these cases it will not be included in the blockchain. You can retry or push another transaction if the original transaction deadline has passed.

i don't want to push another transaction if the original transaction deadline has passed,
is there any way to broadcast successfully?is there a way to broadcast directly to the BP node？

**Comment by taokayan** [comment]
In the nature of blockchain, there's no guarantee of any transaction will always be executed successfully or be included in some of the blocks. Also BP nodes are much likely hiding from the public internet. Therefore, users need to wait until the block containing the transaction becomes irreversible, or the transaction expire time has passed.

**Comment by jgiszczak** [comment]
To see more details about the exception generated when a transaction is submitted, it is better to run your own nodeos synced with the network you wish to use.  That way you have control over and can enable more detailed logging and error reporting.

Even with your own node, what taokayan has stated still applies.  While your local node may accept the transaction and even execute it locally, it may still not be incorporated into the chain by a block producer.  If it isn't, your local node will end up rolling back its own view of the chain, apparently "reversing" the transaction.  Your app must always proactively follow up with the transaction ID to verify a submitted transaction has been accepted and added to the chain and eventually made irreversible.
