### ISSUE TITLE
STAT-203 ⁃ Update start_all.sh script

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#790]
Per Phil:  I need to make the start_all.sh script a little more generic / portable.

Please post to GitHub in ./eos/scripts when completed.

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

in addition to the scripts, I'm going to fix the bug in the launcher that was causing restart headaches last night.

**Comment by heifner** [comment]
Resolved by #791
