### ISSUE TITLE
nodeos does not start syncing after genesis block

### ISSUE THREAD

**Issue by astudnev** [EOSIO/eos#7920]
I installed eos from sources

inited it with genesis:
/home/studnev/eosio/1.8/bin/nodeos --extract-genesis-json genesis.json
and started as
/home/studnev/eosio/1.8/bin/nodeos -e --genesis-json genesis.json --disable-replay-opts

config file, text output is attached.

I do not see ant syncing progress with mainnet. It is showing the latest block as 1.

[logout.txt](https://github.com/EOSIO/eos/files/3613686/logout.txt)

[config.ini.txt](https://github.com/EOSIO/eos/files/3613688/config.ini.txt)

**Comment by astudnev** [comment]
Problem was that i used genesis .json generated by nodeos --print-genesis

which does NOT generate genesis for the Mainnet which is very confusing

**Comment by heifner** [comment]
"Mainnet" is just one of many.

**Comment by astudnev** [comment]
I understand, but this is not said in the help of the method and not very well described in the documentation. Do not use genesis.json generated by the node automatically!

**Comment by heifner** [comment]
Fair enough. I'll see if we can make the doc clearer. 

To be clear can you provide a link to the doc you are following?

**Comment by heifner** [comment]
@dskvr
