### ISSUE TITLE
1.8 version could not run

### ISSUE THREAD

**Issue by IPSE-TEAM** [EOSIO/eos#7922]
error 2019-09-16T07:15:03.848 nodeos    main.cpp:120                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::wrapexcept<boost::program_options::unknown_option>
std::exception::what: unrecognised option 'bnet-endpoint

**Comment by IPSE-TEAM** [comment]
what's the configuration file is right?

**Comment by heipacker** [comment]
delete this bnet-endpoint config item
