### ISSUE TITLE
DAWN-215 ⁃ Remove Block Summary code from P2P

### ISSUE THREAD

**Issue by PaulCalabrese** [EOSIO/eos#796]
Since we are not using block summaries for STAT, this change removes any code related to these messages from the P2P plug-in

**Comment by blockone-syncclient** [comment]
➤ Paul Calabrese commented:

I am cancelling this issue as we don't really want to do this now that the testnet has launched. My previous pull request deleted the block_summary_message and all associated code. Unfortunately, doing this now would break backward-compatibility in the testnet, so we can't apply this change. In addition, the p2p code is being reworked on the noon branch, so there is really no advantage to doing this.
