### ISSUE TITLE
Add Unit test for scenarios related to #7985

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#7987]
Need unit test to restart a chain with an existing state but no block log and no passed in genesis state.

Also need test with a block log (but no genesis state) and no genesis-json.
This could be done by bringing up another tester from a snapshot (made from main tester), syncing a few blocks from the main tester (which is producing new blocks), closing this secondary tester, and then opening it again.

**Comment by arhag** [comment]
Resolved by #7991.
