### ISSUE TITLE
cleos set contract error 3070000: WASM Exception

### ISSUE THREAD

**Issue by wangyilin1987** [EOSIO/eos#7990]
my contract code include :
`
namespace eosio {
   namespace internal_use_do_not_use {
      extern "C" {
         __attribute__((eosio_wasm_import))
         uint64_t get_sender();
      }
   }
}
auto ret = internal_use_do_not_use::get_sender();

and 
cleos set contract racegamelogl ../logs/ -p racegamelogl 

Error 3070000: WASM Exception
Error Details:
env.get_sender unresolveable

`
where is the problem, how to solve it?Thank you!

**Comment by taokayan** [comment]
the API ```get_sender``` is a protocol feature that needs to be activated first. I guess you can refer to https://developers.eos.io/eosio-nodeos/docs/consensus-protocol-upgrade-process

**Comment by wangyilin1987** [comment]
thank you.
