### ISSUE TITLE
Error while linking CXX executable simple_tests.wasm while building EOSIO.cdt

### ISSUE THREAD

**Issue by sugalivijaychari** [EOSIO/eos#7996]
I am using Oracle Vitual Box - Ubuntu OS to install EOSIO software.
When I tried to build eosio.cdt from source. My terminal got stuck during the below point.
"Linking CXX executable simple_tests.wasm".
Someone suggested me to comment "include(modules/TestsExternalProject.txt)" line in the file "CMakeLists.txt".
After this, built successfully and installed successfully. But when I tried to execute hello smart contract, my terminal again got stuck and it doesn't generate .wasm file of the smart contract.
![Screenshot (4)](https://user-images.githubusercontent.com/24669841/65745871-c6125400-e11a-11e9-88dc-69bee87f2921.png)

**Comment by spoonincode** [comment]
eosio.cdt has an issue where it gets stuck if there is only 1 CPU core. Can you make sure there is at least 2 CPU cores assigned to your VM?

**Comment by SethArchambault** [comment]
Running this with `make -j2` allowed me to pass this issue

**Comment by heifner** [comment]
Assuming you were able to get past this issue, reopen if still having problems.
