### ISSUE TITLE
Error while generating eosio.system.wasm file

### ISSUE THREAD

**Issue by bankerneel** [EOSIO/eos#7997]
# Error while generating eosio.system.wasm file

### _**eosio-cpp eosio.system.cpp -o eosio.system.wasm**_

**************************************************************************************************************
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosio::preactivate_feature(eosio::fixed_bytes<32u> const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::native::onerror(eosio::ignore<unsigned __int128>, eosio::ignore<std::__1::vector<char, std::__1::allocator<char> > >)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::onblock(eosio::ignore<eosiosystem::block_header>)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::delegatebw(eosio::name const&, eosio::name const&, eosio::asset const&, eosio::asset const&, bool)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::setrex(eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::deposit(eosio::name const&, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::withdraw(eosio::name const&, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::buyrex(eosio::name const&, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::unstaketorex(eosio::name const&, eosio::name const&, eosio::asset const&, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::sellrex(eosio::name const&, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::cnclrexorder(eosio::name const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::rentcpu(eosio::name const&, eosio::name const&, eosio::asset const&, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::rentnet(eosio::name const&, eosio::name const&, eosio::asset const&, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::fundcpuloan(eosio::name const&, unsigned long long, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::fundnetloan(eosio::name const&, unsigned long long, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::defcpuloan(eosio::name const&, unsigned long long, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::defnetloan(eosio::name const&, unsigned long long, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::updaterex(eosio::name const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::rexexec(eosio::name const&, unsigned short)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/eosio.system.cpp.o: undefined symbol: eosiosystem::system_contract::consolidate(eosio::name const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
**************************************************************************************************************

**Comment by Shaivpidadi** [comment]
I am facing the same problem. I tried with manipulating the header file but the issue remains same. When I was trying to find the solution online , someone said problem is with eosio.cdt version. I tried upgrading the version but issue remains the same.


# Please Help !!!!!!

**Comment by bankerneel** [comment]
I solved it by passing all the files required, as In older version, eosio.system.cpp has #include "voting.cpp" etc.
