### ISSUE TITLE
too much error log

### ISSUE THREAD

**Issue by heipacker** [EOSIO/eos#7998]
error 2019-09-27T12:35:58.158 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.get_table_rows
error 2019-09-27T12:35:58.467 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.get_table_rows
info  2019-09-27T12:35:58.532 nodeos    producer_plugin.cpp:421       on_incoming_block    ] Received block 736cdf20cb072825... #81566708 @ 2019-09-27T12:35:58.500 signed by eosasia11111 [trxs: 16, lib: 81566374, conf: 0, latency: 32 ms]
error 2019-09-27T12:35:58.953 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.push_transaction
info  2019-09-27T12:35:59.040 nodeos    producer_plugin.cpp:421       on_incoming_block    ] Received block c544740176ce46db... #81566709 @ 2019-09-27T12:35:59.000 signed by eosasia11111 [trxs: 18, lib: 81566374, conf: 0, latency: 40 ms]
error 2019-09-27T12:35:59.131 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.push_transaction
info  2019-09-27T12:35:59.316 nodeos    producer_plugin.cpp:421       on_incoming_block    ] Received block 76c25f81bf391e1c... #81566710 @ 2019-09-27T12:35:59.500 signed by eosasia11111 [trxs: 16, lib: 81566374, conf: 0, latency: -183 ms]
info  2019-09-27T12:36:00.107 nodeos    producer_plugin.cpp:421       on_incoming_block    ] Received block 5436ec8c3a4bed27... #81566711 @ 2019-09-27T12:36:00.000 signed by eoscannonchn [trxs: 30, lib: 81566386, conf: 240, latency: 107 ms]
info  2019-09-27T12:36:00.576 nodeos    producer_plugin.cpp:421       on_incoming_block    ] Received block 813fed20ad59006c... #81566712 @ 2019-09-27T12:36:00.500 signed by eoscannonchn [trxs: 35, lib: 81566386, conf: 0, latency: 76 ms]
info  2019-09-27T12:36:01.061 nodeos    producer_plugin.cpp:421       on_incoming_block    ] Received block 0031b3a6877a9a17... #81566713 @ 2019-09-27T12:36:01.000 signed by eoscannonchn [trxs: 25, lib: 81566386, conf: 0, latency: 61 ms]
error 2019-09-27T12:36:01.285 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.push_transaction
error 2019-09-27T12:36:01.357 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.get_table_rows
error 2019-09-27T12:36:01.556 nodeos    http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing chain.push_transaction
info  2019-09-27T12:36:01.630 nodeos    producer_plugin.cpp:421       on_incoming_block    ] Received block f29e9c101a733811... #81566714 @ 2019-09-27T12:36:0

**Comment by heipacker** [comment]
version 1.8.1

**Comment by heifner** [comment]
In version 2.0 the http_plugin has its own logger, `http_plugin`, that can be configured separately from other loggers.
