### ISSUE TITLE
Keosd is a light-wallet, is there a headvy one?

### ISSUE THREAD

**Issue by f4f5** [EOSIO/eos#8006]
I sorry to take your time to answer me some technical question. I want to store private keys in a separate computer. which means I don't need keosd. but the question is, I can't create new account if there is no keosd on.  is it possible to use
`./cleos create account inita tester private-key  private-key` or some other approach instead?

If no, is there a way to bypass keosd?   or is it a problem if keosd manage so many keys, such as, millions of keys ? 

and again, how to create account by rpc api?

**Comment by jgiszczak** [comment]
`keosd` isn't just the key store.  It also signs your transactions submitted via `cleos`.  If you do not want to use `keosd`, you won't be using `cleos` either.

To create an account via the RPC API, you can follow the sample using `eosjs` [here](https://github.com/EOSIO/eosjs/issues/227).  Note that all accounts on EOSIO-based networks are created from existing accounts, so if you do not already control an account, you will need to use one of the services provided by the various networks to have an account created for you.  Once you have at least one account of your own, you can use it to fund the creation of additional accounts as needed.
