### ISSUE TITLE
When can i use `get_sender` by v1.8.x in contract side?

### ISSUE THREAD

**Issue by yyh1102** [EOSIO/eos#8030]
Does it support any API like `get_sender` using `GET_SENDER` codename in contract side? I did not found any API in eosiolib.

**Comment by heifner** [comment]
https://github.com/EOSIO/eos/issues/7028

API not released yet, it is in CDT `v1.7.0-rc1`.

https://github.com/EOSIO/eosio.cdt/blob/v1.7.0-rc1/libraries/eosiolib/contracts/eosio/system.hpp#L90

Also not activated on mainnet yet: https://bloks.io/protocol-features
