### ISSUE TITLE
Unsynced fully blockchain size is 540GB, why?

### ISSUE THREAD

**Issue by atomlab** [EOSIO/eos#8031]
How can I reduce blockchain size? 

At now I have blockchain size
```
# du -hsc /opt/eos/storage/*
149G	/opt/eos/storage/blocks
4.0K	/opt/eos/storage/snapshots
4.1G	/opt/eos/storage/state
390G	/opt/eos/storage/state-history
543G	total
```

```
# du -hsc /opt/eos/storage/state-history/*
269M	/opt/eos/storage/state-history/chain_state_history.index
119G	/opt/eos/storage/state-history/chain_state_history.log
269M	/opt/eos/storage/state-history/trace_history.index
271G	/opt/eos/storage/state-history/trace_history.log
390G	total
```

Current block  my node is 35136312. It's about  **~42%** of full blockchain (last block 82790176)

```# curl http://localhost:8888/v1/chain/get_info```
> {"server_version":"7116e887","chain_id":"aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906","head_block_num":35136312,"last_irreversible_block_num":35135980,"last_irreversible_block_id":"021821ec9c6d253652807ec58264667ac06a4ebeb7b03bfee72c5885e4f513bf","head_block_id":"02182338db06420034afdb0a91b551959e06fa605f0b13c1fe3e1dd8fbe09137","head_block_time":"2019-01-01T10:47:39.500","head_block_producer":"eoshuobipool","virtual_block_cpu_limit":200000000,"virtual_block_net_limit":1048576000,"block_cpu_limit":200000,"block_net_limit":1048576,"server_version_string":"v1.8.3","fork_db_head_block_num":35136312,"fork_db_head_block_id":"02182338db06420034afdb0a91b551959e06fa605f0b13c1fe3e1dd8fbe09137"}

My config

```
#Chain plugin settings
chain-state-db-size-mb = 32000
reversible-blocks-db-size-mb = 2048
read-mode = read-only
validation-mode = light
wasm-runtime = wabt

#Http plugin settings
access-control-allow-origin = *
http-validate-host = false
verbose-http-errors = true
http-server-address = 0.0.0.0:8888
filter-on = *

# Can be 'any' or 'producers' or 'specified' or 'none'. If 'specified', peer-key must be specified at least once. If only 'producers', peer-key is not required. 'producers' and 'specified' may be combined. (eosio::net_plugin)
allowed-connection = any

#Net plugin settings
agent-name = Agent
p2p-max-nodes-per-host = 40
max-clients = 500
p2p-server-address = 0.0.0.0:9876

# State history plugin settings
state-history-endpoint = 0.0.0.0:8080
trace-history = true
chain-state-history=true

#Plugins
plugin = eosio::producer_plugin
plugin = eosio::chain_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::net_plugin
plugin = eosio::state_history_plugin

#peers
p2p-peer-address = 18.234.6.119:80
p2p-peer-address = 185.253.188.1:19876
p2p-peer-address = api-full1.eoseoul.io:9876
p2p-peer-address = api-full2.eoseoul.io:9876
p2p-peer-address = boot.eostitan.com:9876
p2p-peer-address = bp.antpool.com:443
p2p-peer-address = bp.cryptolions.io:9876
p2p-peer-address = bp.eosbeijing.one:8080
p2p-peer-address = bp.libertyblock.io:9800
p2p-peer-address = br.eosrio.io:9876
p2p-peer-address = eos-seed-de.privex.io:9876
p2p-peer-address = eu1.eosdac.io:49876
p2p-peer-address = fullnode.eoslaomao.com:443
p2p-peer-address = mainnet.eoscalgary.io:5222
p2p-peer-address = mainnet.eospay.host:19876
p2p-peer-address = mars.fnp2p.eosbixin.com:443
p2p-peer-address = node.eosflare.io:1883
p2p-peer-address = node1.eoscannon.io:59876
p2p-peer-address = node1.eosnewyork.io:6987
p2p-peer-address = node2.eosnewyork.io:6987
p2p-peer-address = p.jeda.one:3322
p2p-peer-address = p2p.eosdetroit.io:3018
p2p-peer-address = p2p.genereos.io:9876
p2p-peer-address = p2p.meet.one:9876
p2p-peer-address = p2p.one.eosdublin.io:9876
p2p-peer-address = p2p.two.eosdublin.io:9876
p2p-peer-address = peer.eosn.io:9876
p2p-peer-address = peer.main.alohaeos.com:9876
p2p-peer-address = peer1.mainnet.helloeos.com.cn:80
p2p-peer-address = peer2.mainnet.helloeos.com.cn:80
p2p-peer-address = peering.mainnet.eoscanada.com:9876
p2p-peer-address = pub0.eosys.io:6637
p2p-peer-address = pub1.eosys.io:6637
p2p-peer-address = publicnode.cypherglass.com:9876
p2p-peer-address = seed1.greymass.com:9876
p2p-peer-address = seed2.greymass.com:9876
```

**Comment by jgiszczak** [comment]
EOSIO-based networks generate a block every half second.  Mainnet is currently processing 80 transactions per second, sustained, and has been doing so for quite some time.  Mainnet has generated more than 82 million blocks as of this writing.  This requires a lot of storage.  Indexing this data for fast search and retrieval requires even more storage.  If you wish to run a full history node of Mainnet, be prepared to invest in significant storage space.  You may wish to enable filesystem compression, but there are tradeoffs.

If you wish to discuss running a Mainnet node further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
