### ISSUE TITLE
Invalid state history ABI JSON in v2.0.0-rc1

### ISSUE THREAD

**Issue by n8d** [EOSIO/eos#8054]
I'm trying to connect a state history reader to a 2.0.0-rc1 node and getting an error parsing the ABI JSON. Looking at it in detail I see a couple issues with the JSON:

![image](https://user-images.githubusercontent.com/787401/66513748-010c7400-ea99-11e9-96ce-b2cec5ab2d3f.png)
(missing comma)

![image](https://user-images.githubusercontent.com/787401/66513788-16819e00-ea99-11e9-9ea1-2bb1cfe9aa3c.png)
(extra comma)

**Comment by arhag** [comment]
Resolved by #8106 (or #8060). Still requires adding integration tests for SHiP, but that is tracked by #8066.
