### ISSUE TITLE
Update versioning in nodeos

### ISSUE THREAD

**Issue by heifner** [EOSIO/eos#8059]
#7468 added better version reporting to `cleos`.
- Add similar capability to `nodeos`.
- Add a `--full-version` option to `nodeos` that reports the full version with the hash similar to `cleos version full`
- Add a new `server_full_version_string` to `get info` RPC to report this new full version.
- Modify existing `server_version_string` of `get_info` RPC to report similar as `cleos version client`

**Comment by arhag** [comment]
Resolved by #8062 (or #8072).
