### ISSUE TITLE
nodeos gets stuck and stops syncing when a peer becomes unavailable (2.0.0-rc1)

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8069]
a producing nodeos is connected to several peers.  I turned off one of them and then nodeos stopped syncing.  It would not sync even when that peer was turned on again.

The nodeos in question is 2.0.0.-rc1
The peer that was disconnected is 1.8.4

Logs will be sent to @heifner

**Comment by heifner** [comment]
Resolved by #8119 & #8120
