### ISSUE TITLE
error: no member named 'version_int' in       'appbase::application'

### ISSUE THREAD

**Issue by sparcusa** [EOSIO/eos#810]
I'm trying to compile eos on ubuntu 16.04.   I got this error several times:

[ 79%] Built target eos-walletd
1 error generated.
plugins/chain_plugin/CMakeFiles/chain_plugin.dir/build.make:62: recipe for target 'plugins/chain_plugin/CMakeFiles/chain_plugin.dir/chain_plugin.cpp.o' failed
make[2]: *** [plugins/chain_plugin/CMakeFiles/chain_plugin.dir/chain_plugin.cpp.o] Error 1
CMakeFiles/Makefile2:2875: recipe for target 'plugins/chain_plugin/CMakeFiles/chain_plugin.dir/all' failed
make[1]: *** [plugins/chain_plugin/CMakeFiles/chain_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 79%] Linking CXX executable embed_genesis
[ 79%] Built target embed_genesis
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Any idea what this is?    Very frustrating.....

**Comment by heifner** [comment]
The title error is out in your pasted output. However, the title error can be fixed via: `git submodule update`
