### ISSUE TITLE
How can I download the block backup data?

### ISSUE THREAD

**Issue by weimumu** [EOSIO/eos#8101]
Now, https://eosnode.tools/blocks does not provide the block backup data download anymore. And I can download the block backup data from AWS S3. So how can download the block backup data now?

**Comment by matthewdarwin** [comment]
This issue has nothing to do with the EOSIO software.  I recommend posting the question to relevant telegram or stack exchange groups.

You also do don't indicate which network you want to download blocks for.  There are many blockchains based on EOSIO.
