### ISSUE TITLE
Add comparison operator overloads for extended_symbol type

### ISSUE THREAD

**Issue by JackDiSalvatore** [EOSIO/eos#8117]
comparison operators (==, !=, <, >) are missing for the extended_symbol type in eos/libraries/chain/include/eosio/chain/symbol.hpp

**Comment by JackDiSalvatore** [comment]
The extended_symbol definitions are different in the "eos" and "eos.cdt" codelines.  It would be nice if they matched until a common lib is shared between both codelines.

**Comment by jeffreyssmith2nd** [comment]
Handled by #8540
