### ISSUE TITLE
When block Sync eosio::sync_state: Assertion `_valid' failed.

### ISSUE THREAD

**Issue by xylitol** [EOSIO/eos#8122]
nodeos : eos/libraries/fc/include/fc/optional.hpp:210: T *fc::optional<eosio::sync_state>::operator->()
     [U = eosio::sync_state]: Assertion `_valid' failed

When I connect to another peer, the error appear.

**Comment by heifner** [comment]
What version? Any more output?

**Comment by xylitol** [comment]
> 
> 
> What version? Any more output?


The version is 1.7.4. Yes 'nodeos.log' file doeosn't show me anyother output. But I guess the error occurs when blocks were synchronized. The line is [https://github.com/EOSIO/eos/blob/7d210b387ce5ec9089ab31e9cc0e237bceb25622/plugins/net_plugin/net_plugin.cpp#L2478](url)

**Comment by heifner** [comment]
1.7.4 is no longer supported. Please try 1.8.5.
