### ISSUE TITLE
Build script failing 

### ISSUE THREAD

**Issue by zeinramadan** [EOSIO/eos#8123]
When executing ./build.sh script on ubuntu 18.04 bash on windows i get the following errors:

c++: error: 3/Computer: No such file or directory
c++: error: Science: No such file or directory
c++: error: Project/CONTRACTS_DIR/eosio.cdt/build/eosio_llvm/./lib: No such file or directory
utils/TableGen/CMakeFiles/llvm-tblgen.dir/build.make:164: recipe for target 'bin/llvm-tblgen' failed
make[5]: *** [bin/llvm-tblgen] Error 1
CMakeFiles/Makefile2:872: recipe for target 'utils/TableGen/CMakeFiles/llvm-tblgen.dir/all' failed
make[4]: *** [utils/TableGen/CMakeFiles/llvm-tblgen.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/EosioClang.dir/build.make:111: recipe for target 'EosioClang-prefix/src/EosioClang-stamp/EosioClang-build' failed
make[2]: *** [EosioClang-prefix/src/EosioClang-stamp/EosioClang-build] Error 2
CMakeFiles/Makefile2:291: recipe for target 'CMakeFiles/EosioClang.dir/all' failed
make[1]: *** [CMakeFiles/EosioClang.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Anyone had any similar errors before?

**Comment by jgiszczak** [comment]
Something somewhere is failing to deal with a directory with spaces in the name.  Exactly which repository are you attempting to build?

**Comment by jgiszczak** [comment]
Original poster unresponsive for 95 days.l
