### ISSUE TITLE
Download links incorrectly documented in Readme

### ISSUE THREAD

**Issue by sachushaji** [EOSIO/eos#8137]
## Expected Behavior

The download script for downloading builds should correctly resolve to the latest release and download.

## Current Behavior
This is one of the current download links provided in the repo.
`
wget https://github.com/eosio/eos/releases/download/v1.8.0-rc1/eosio_1.8.0-rc1-ubuntu-18.04_amd64.deb
`
This is resolving into 404 

## Context
Incorrect Documentation

I am willing to do a PR for this :-)

**Comment by heifner** [comment]
The README.md for master, shown here: https://github.com/EOSIO/eos is correct.
