### ISSUE TITLE
Unknown action transfer in contract

### ISSUE THREAD

**Issue by sunnykasera3107** [EOSIO/eos#8150]
> stdClass Object ( [code] => 500 [message] => Internal Service Error [error] => stdClass Object ( [code] => 3050000 [name] => action_validate_exception [what] => Action validate exception [details] => Array ( [0] => stdClass Object ( [message] => Unknown action transfer in contract eosio [file] => chain_plugin.cpp [line_number] => 1831 [method] => abi_json_to_bin ) [1] => stdClass Object ( [message] => code: eosio, action: transfer, args: ["boxbuyer1","boxbuyer2","0.0001 EOS","Testy McTest"] [file] => chain_plugin.cpp [line_number] => 1842 [method] => abi_json_to_bin ) ) ) )

Can we create custom action there?

**Comment by heifner** [comment]
It is not clear what you are asking.

**Comment by learnforpractice** [comment]
eosio contract has no transfer action

Change contract from eosio to eosio.token please.
