### ISSUE TITLE
pushSignedTransaction to local nodeos with no response sometimes 

### ISSUE THREAD

**Issue by sampleblood** [EOSIO/eos#8152]
sometimes I push a transaction to my local nodeos in mainnet use eosjs#pushSignedTransaction, nodeos respond nothing in time, hours later, I received this: {"message":{"code":3040005,"name":"expired_tx_exception","what":"Expired Transaction","details":[{"message":"expired transaction xxxxx","file":"producer_plugin.cpp","line_number":466,"method":"process_incoming_transaction_async"}]},"status":522} , 
please help, thank you
nodeos version : v1.8.3

// config.ini 
chain-state-db-size-mb = 65536
chain-threads = 6
http-server-address = 172.31.19.28:8888
http-threads = 6

p2p-peer-address = 185.253.188.1:19876
p2p-peer-address = api-full1.eoseoul.io:9876
p2p-peer-address = api-full2.eoseoul.io:9876
p2p-peer-address = boot.eostitan.com:9876
p2p-peer-address = bp.antpool.com:443
p2p-peer-address = bp.cryptolions.io:9876
p2p-peer-address = bp.eosbeijing.one:8080
p2p-peer-address = bp.libertyblock.io:9800
p2p-peer-address = br.eosrio.io:9876
p2p-peer-address = eos-seed-de.privex.io:9876
p2p-peer-address = eu1.eosdac.io:49876
p2p-peer-address = fullnode.eoslaomao.com:443
p2p-peer-address = mainnet.eoscalgary.io:5222
p2p-peer-address = node.eosflare.io:1883
p2p-peer-address = node1.eoscannon.io:59876
p2p-peer-address = node1.eosnewyork.io:6987
p2p-peer-address = node2.eosnewyork.io:6987
p2p-peer-address = p.jeda.one:3322
p2p-peer-address = p2p.eosdetroit.io:3018
p2p-peer-address = p2p.genereos.io:9876
p2p-peer-address = p2p.meet.one:9876
p2p-peer-address = peer.eosn.io:9876
p2p-peer-address = peer.main.alohaeos.com:9876
p2p-peer-address = peer1.mainnet.helloeos.com.cn:80
p2p-peer-address = peer2.mainnet.helloeos.com.cn:80
p2p-peer-address = peering.mainnet.eoscanada.com:9876
p2p-peer-address = peering1.mainnet.eosasia.one:80
p2p-peer-address = peering2.mainnet.eosasia.one:80
p2p-peer-address = publicnode.cypherglass.com:9876

sync-fetch-span = 2000

max-transaction-time = 30000

plugin = eosio::chain_plugin
plugin = eosio::chain_api_plugin

**Comment by heifner** [comment]
Enable `transaction_tracing` `debug` level logging on your local nodeos. When this happens again take a look at the log and see if it tells you why your transaction failed. Also it would be good to upgrade to latest `v1.8.5`. There were changes in this area.

If you don't have a logging.json already, here is an example:
https://github.com/EOSIO/eos/blob/develop/programs/nodeos/logging.json

`transaction_tracing` needs to be `debug` not `info`. Also you probably want to change net_plugin_impl from `debug` to `info` or `warn`.

**Comment by sampleblood** [comment]
1. where should I put this logging.json?
2. does state_history_plugin help for this issue ?

> Enable `transaction_tracing` `debug` level logging on your local nodeos. When this happens again take a look at the log and see if it tells you why your transaction failed. Also it would be good to upgrade to latest `v1.8.5`. There were changes in this area.
> 
> If you don't have a logging.json already, here is an example:
> https://github.com/EOSIO/eos/blob/develop/programs/nodeos/logging.json
> 
> `transaction_tracing` needs to be `debug` not `info`. Also you probably want to change net_plugin_impl from `debug` to `info` or `warn`.

1. where should I put this logging.json ?
2. is state_history_plugin help for this issue ?

**Comment by heifner** [comment]
The logging should tell you what you need to know. I suspect your transaction is too big or takes too long to execute. What do you have `max-transaction-time` set to?

**Comment by sampleblood** [comment]
> The logging should tell you what you need to know. I suspect your transaction is too big or takes too long to execute. What do you have `max-transaction-time` set to?

max-transaction-time = 30000

**Comment by heifner** [comment]
That is as I expected. 30 seconds is WAY too big. Your block time is 500 ms. So your transaction is not fitting in a block, but since you have max-transaction-time so high it just keeps trying until it times out. Set mas-transaction-time to something more reasonable and then you will get immediate feedback that your transaction is too big.

**Comment by heifner** [comment]
Are you specifying a `-p` or `producer-name` argument or config.ini setting?

**Comment by sampleblood** [comment]
> Are you specifying a `-p` or `producer-name` argument or config.ini setting?
not yet

**Comment by heifner** [comment]
No, the producer-name is another way you might have gotten into this situation.

**Comment by sampleblood** [comment]
I found my local nodeos chainInfo#head_block_num was far behind (about 10 minutes block_num ) the latest block_num when this issue happen,  my local nodeos can not catch up.

**Comment by wangsen0518** [comment]
I also have the same problem.
Is it solved?

**Comment by matthewdarwin** [comment]
How fast is your CPU?  If nodeos is taking >100% CPU, then get a faster CPU.  3.0GHz or better is needed for EOS Mainnet.

**Comment by sampleblood** [comment]
> How fast is your CPU? If nodeos is taking >100% CPU, then get a faster CPU. 3.0GHz or better is needed for EOS Mainnet.

cpu always below 100%，I use aws c5.large with 3000 IOPS ebs , monitoring everything is ok

**Comment by sampleblood** [comment]
> I also have the same problem.
> Is it solved?
not yet by now

**Comment by sampleblood** [comment]
is there official minimum requirement for a non-producing node with these two plugins:
plugin = eosio::chain_plugin
plugin = eosio::chain_api_plugin

**Comment by jgiszczak** [comment]
There is no official minimum hardware requirement.  Networks instantiated using EOS.IO software may have official or de facto limits imposed by the hardware used by their producers and by their transaction rates, but that varies among networks.

**Comment by ndcgundlach** [comment]
Appears to be a hardware provisioning issue.
