### ISSUE TITLE
how about 'cleos wallet create --password xxxx'?

### ISSUE THREAD

**Issue by yanyiwu** [EOSIO/eos#8153]
wanna set the wallet password by myself.

**Comment by heifner** [comment]
We generate a password to avoid users specifying a weak one.

**Comment by yanyiwu** [comment]
@heifner  but sometimes i only use my private key with little money in it, so it is convenient when the password is simple

**Comment by yanyiwu** [comment]
@heifner what do you think of that?

**Comment by heifner** [comment]
I doubt this will be added anytime soon.

**Comment by ndcgundlach** [comment]
Asked and answered.
