### ISSUE TITLE
CPU problem

### ISSUE THREAD

**Issue by IPSE-TEAM** [EOSIO/eos#8157]
My contract address: ipsecontract

Using 4300 eos for CPU pledge,but not enough, over 3651%,that's shit. How to solve the problem?

**Comment by IPSE-TEAM** [comment]
https://bloks.io/account/eidosonecoin
this contract is shit,what's the f**king author?

**Comment by matthewdarwin** [comment]
This github is to discuss problems with EOSIO software, not with someones smart contract.   Best to take this to one of the telegram discussion groups.
