### ISSUE TITLE
How to set the expiretime of refund transaction for manual refund

### ISSUE THREAD

**Issue by chenzhijun45** [EOSIO/eos#8160]
Three days after I undelegatebw.
But I have not received the Resource of undelegatebw.
so, I push_transaction for refund. But, the response is transaction expiretime

push_transaction:
{"actions":[{"account":"eosio","authorization":[{"actor":"chenzhijun12","permission":"active"}],"data":"20c2d4cfb53f5543","name":"refund"}],"context_free_actions":[],"delay_sec":0,"expiration":"2019-11-03T15:29:58","max_cpu_usage_ms":0,"net_usage_words":0,"ref_block_num":87918394,"ref_block_prefix":4279692135,"transaction_extensions":[]}

response
{"code":"3040006","details":[{"file":"controller.cpp","lineNumber":2955,"message":"Transaction expiration is too far in the future relative to the reference time of 2019-11-03T07:29:03.500, expiration is 2019-11-03T15:29:58 and the maximum transaction lifetime is 3600 seconds","method":"validate_expiration"},{"file":"controller.cpp","lineNumber":2956,"message":"","method":"validate_expiration"}],"name":"tx_exp_too_far_exception","what":"Transaction Expiration Too Far"}

I have changed the transaction expiretime several times.
But, without effect.
So , I don not know the reason. Who can tell me , thanks very much~

**Comment by jgiszczak** [comment]
Be sure to submit your expiration time in UTC rather than your local timezone.  EOS.IO runs in UTC and I'm not aware of any network that has forked the code to change that.

**Comment by taokayan** [comment]
are you using ```cleos```? from the error message you've set an expire time to be around 8 hours of the current time, which is too big. However, this might be a problem or software bug which is related to your timezone setting.
