### ISSUE TITLE
what's the relationship between the blocks.log and the data in mongodb?

### ISSUE THREAD

**Issue by ling2yt** [EOSIO/eos#8162]
What's the relationship between the blocks.log and the data in mongodb?
Can I replay all the blocks and transactions and actsions and the trace collections in mongodb from the blocks.log?
My blocks.log is more than 6G, but the mongodb has almost more then 50G.
So if I want to clean the mongodb data. Which collections can I delete and have no effect to processing the new blocks?
EOS node version: 16.02rc

Thx for help

**Comment by heifner** [comment]
There are separate. You can replay and regenerate your mongodb from your block.log. You can drop whatever you like from mongodb. You can choose to store whatever you like in mongodb.
