### ISSUE TITLE
Incorrect namespace in RPC documentation for get_activated_protocol_features

### ISSUE THREAD

**Issue by conr2d** [EOSIO/eos#8188]
The namespace of get_activated_protocol_features RPC is `chain`, but its documentation on Developer Portal is introduced under `producer` namespace.

https://developers.eos.io/eosio-nodeos/reference#get_activated_protocol_features

**Comment by heifner** [comment]
@dskvr

**Comment by iamveritas** [comment]
in the latest documentation the `get_activated_protocol_features` is under `chain` namespace:

see here:
https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_api_plugin/api-reference/index#operation/get_activated_protocol_features

![image](https://user-images.githubusercontent.com/11767353/75066455-88f89500-54f3-11ea-9a12-656174e11609.png)

if it that is alright with you we shall close this one. @conr2d
