### ISSUE TITLE
push_transaction 

### ISSUE THREAD

**Issue by chenlichang** [EOSIO/eos#8189]
push_transaction is no corresponding, the program waits until the end

**Comment by heifner** [comment]
Sorry no idea what you are trying to say.

**Comment by tokyliu** [comment]
@chenlichang , did your question solved? I encountered the same question

**Comment by chenlichang** [comment]
No solution, I now use public network nodes for push_transaction


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"piececoder"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月29日(星期五) 中午11:20
收件人:&nbsp;"EOSIO/eos"<eos@noreply.github.com&gt;;
抄送:&nbsp;"/ylclc"<381267409@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [EOSIO/eos] push_transaction  (#8189)




@chenlichang , did your question solved? I encountered the same question

**Comment by libangzhu** [comment]
我也遇到了相同的问题

**Comment by libangzhu** [comment]
please fix it as soon as possible

**Comment by heifner** [comment]
@libangzhu there is nothing here to indicate what issue you are having. Please open a new issue with details about your problem.
