### ISSUE TITLE
Your Linux Files are not Installing Properly

### ISSUE THREAD

**Issue by nloladze92** [EOSIO/eos#8200]
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`Note, selecting 'eosio' instead of './eosio_1.8.5-1-ubuntu-16.04_amd64.deb'`
`Some packages could not be installed. This may mean that you have`
`requested an impossible situation or if you are using the unstable`
`distribution that some required packages have not yet been created`
`or been moved out of Incoming.`
`The following information may help to resolve the situation:`

`The following packages have unmet dependencies:`
 `eosio : Depends: libicu55 but it is not installable`
`E: Unable to correct problems, you have held broken packages.`

When using the native Ubuntu version 18 installer, it installs then does not display a launch button.

**Comment by spoonincode** [comment]
The 16.04 deb won't work on 18.04 and vice versa. That's expected.

All of eosio's applications are command line applications. I realize that some command line applications in Ubuntu do get a launch button. Say, for example, `fortune`. But launching nodeos is significantly more complex: the first time you launch it you must provide a `genesis-json` or a `snapshot` on the command line to connect to an existing chain. There isn't a way to even specify those options in the config file. And once you've used `genesis-json` or `snapshot` once you need to _not_ specify it subsequent times.

So, I don't believe a launch button will be useful currently. If someday we have a GUI front end to nodeos, cleos, and keosd it may make more sense.
