### ISSUE TITLE
lack of available active peers

### ISSUE THREAD

**Issue by wuyudian1** [EOSIO/eos#8212]
Hi,
Due to lack of available active peers, my full-node open gets stucked at some block.
I must update the peer list from `https://eosnodes.privex.io/?config=1` and restart my nodeos frequently. 

Where can I get stable peers?

My node version is 1.8.4
OS: ubuntu 16.04
disk: 500GB SSD
RAM: 16GB

**Comment by heifner** [comment]
The `net_api_plugin`  when enabled provides connect/disconnect capability without a restart. https://developers.eos.io/eosio-nodeos/docs/net_api_plugin

As for available peers take that up with whatever network you are interacting with.
