### ISSUE TITLE
How do I get transaction details without providing block number information?

### ISSUE THREAD

**Issue by mahsumurebe** [EOSIO/eos#8213]
Hello there.
How do I get the details of a transaction without sending "block_num_hint" ?

**Comment by maoueh** [comment]
You will need to rely on a history provider solution. Here's a great article by @cc32d9 that gives current state of affair regarding history solution: https://medium.com/@cc32d9/history-and-notifications-in-eosio-blockchain-8255194af93.

**Comment by jgiszczak** [comment]
The article by @cc32d9 is informative, accurate, and comprehensive.  While it was written in late August, it continues to be a useful assessment of EOS.IO history solutions as of this posting.
