### ISSUE TITLE
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations

### ISSUE THREAD

**Issue by sunnykasera3107** [EOSIO/eos#8215]
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"eosio","permission":"owner"}', but does not have signatures for it.

I just want to create a new account with eosio creator account. Default wallet is open and unlocked.
Wallet has key "something1" and I want to create account with same key "something1" but eosio has key "something2"
So I am not sure that eosio account will work with this "something1".
I want to set same key for the eosio account.

**Comment by jgiszczak** [comment]
The only key that needs to be in an open and unlocked wallet is the key that will authorize and sign the transaction.  In this case, the key for the `eosio` account.  The key for the new account does not need to be in a wallet at all when the account is created.  The new account's key only needs to be in a wallet when the new account is used for transactions.

In your case only the `something2` key needs to be in a wallet to create a new account using the `eosio` account.  If you want to change the key for the `eosio` account from `something2` to `something1` you may do so, but the `something2` key must be in the wallet to authorize the change.
