### ISSUE TITLE
v2.0.0-rc2 linker command failed: undefined reference to `fc::optional<double>::~optional()'

### ISSUE THREAD

**Issue by bcyangguang** [EOSIO/eos#8216]
On ubuntu 18.04,
 use `./scripts/eosio_build.sh -o Debug -s "EOS"` compile EOSIO v2.0.0-rc2, 
at the end of the compilation get the following error message:
```
[100%] Linking CXX executable nodeos
cd build/programs/nodeos && /usr/bin/cmake -E cmake_link_script CMakeFiles/nodeos.dir/link.txt --verbose=false
make[2]: Leaving directory 'build'
[100%] Built target plugin_test
../../plugins/producer_plugin/libproducer_plugin.a(producer_plugin.cpp.o): In function `eosio::producer_plugin::get_runtime_options() const':
/home/eos/eosio/plugins/producer_plugin/producer_plugin.cpp:1008: undefined reference to `fc::optional<double>::~optional()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
programs/nodeos/CMakeFiles/nodeos.dir/build.make:187: recipe for target 'programs/nodeos/nodeos' failed
```

**Comment by matthewdarwin** [comment]
If you previously compiled v2.0.0-rc1 on the same computer, you need to delete the previously compiled libraries in $HOME.

**Comment by bcyangguang** [comment]
> If you previously compiled v2.0.0-rc1 on the same computer, you need to delete the previously compiled libraries in $HOME.

I deleted the `/home/eosio/2.0` directory and also deleted the `build` directory. The problem is still the same after recompiling.

**Comment by jgiszczak** [comment]
The `fc::optional` class hasn't changed in 2 years, and in particular the destructor hasn't changed in 3 years.

Look for an earlier failure in building or rebuilding the `fc` library.

**Comment by bcyangguang** [comment]
> The `fc::optional` class hasn't changed in 2 years, and in particular the destructor hasn't changed in 3 years.
> 
> Look for an earlier failure in building or rebuilding the `fc` library.

The problem is in `producer_plugin.cpp`
[producer_plugin::runtime_options producer_plugin::get_runtime_options() const](https://github.com/EOSIO/eos/blob/v2.0.0-rc2/plugins/producer_plugin/producer_plugin.cpp#L952)

Where `greylist_limit` was added to `runtime_options`  from v2.0.0-rc1 to v.2.0.0-rc2
[struct runtime_options](https://github.com/EOSIO/eos/blame/v2.0.0-rc2/plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp#L21)

**Comment by jeffreyssmith2nd** [comment]
I'm seeing this as well, but only on `Debug` builds. `Release` or `RelWithDebugInfo` build successfully. And I'm only seeing it on Ubuntu 18.04, have not seen it on MacOS Catalina.

**Comment by ndcgundlach** [comment]
I have encountered this problem also (Ubuntu 18.04).

**Comment by swatanabe-b1** [comment]
It's a bug in clang 7.  There have been a number of bugs in clang and gcc related to destructors and aggregate initialization.

This particular case can be reduced to:

```c++
template<typename T>
struct S {
  ~S() {}
};

struct may_throw {
   may_throw() noexcept(false) {}
};

struct S2 {
  S<double> s;
  may_throw i;
};

S2 f() {
  return {}; // invokes the destructor of S<double> in the cleanup, but does not instantiate it
}

int main() {
}
```

It appears to be fixed in clang 8.

**Comment by theblockstalk** [comment]
Hi
I am getting this issue using the autobuild script on Ubuntu 18.0.4 with the eosio v1.8.7 on master branch

`git clone https://github.com/EOSIO/eos --recursive
cd eos
./scripts/eosio_build.sh -o Debug -m`
