### ISSUE TITLE
eosio.system not applyed any actions

### ISSUE THREAD

**Issue by rommzestz** [EOSIO/eos#8219]
eosio 1.8.6 with EOSIO.CDT buils success eosio.system smartcontract
all actions and tables is exist and all is empty.

when i try execute any actions - i see success result with getting trx id.

but, dont any changes in tables.

first command

system regproducer xxxx

second 

system listproducers

dont have any changes. also, when i try change smartcontract - sample, add
     check( false, "!!"); 
in regproducer dont have any effects when i execute regproducer action.

Why it happende and how fix it?

Thanks

**Comment by jgiszczak** [comment]
Be sure your test node is producing blocks.  If it's a standalone node that was run for a while and then shut down, you may need to add the `-e` or `--enable-stale-production` command line option to get it to resume production.

**Comment by rommzestz** [comment]
node work fine. produce blocks. enable-stale-production is "true" in config.ini
maybe need few exactly steps for success compile system contract and deployand init it?

**Comment by jgiszczak** [comment]
Instructions for building and deploying the system contract are [here](https://github.com/EOSIO/eosio.contracts/blob/master/docs/02_build-and-deploy.md).  Note that specific releases of eosio.contracts do requires specific versions of eosio.cdt, so be sure you have the matching version of the eosio.cdt package for the contracts release you're trying to compile.

**Comment by rommzestz** [comment]
always i get

./build.sh
        =========== Building eosio.contracts ===========

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/lib/cmake/eosio.cdt/eosio.cdt-config.cmake:8 (include):
  include could not find load file:

    EosioWasmToolchain
Call Stack (most recent call first):
  CMakeLists.txt:18 (find_package)


CMake Error at /usr/local/lib/cmake/eosio.cdt/eosio.cdt-config.cmake:11 (include):
  include could not find load file:

    EosioCDTMacros
Call Stack (most recent call first):
  CMakeLists.txt:18 (find_package)


-- Building eosio.contracts v1.6.0
CMake Error at CMakeLists.txt:38 (message):
  Found eosio.cdt version but it does not satisfy version requirements:
  version '' is invalid

  Please use eosio.cdt version 1.5.x


-- Configuring incomplete, errors occurred!
See also "/var/cff_server/contr/contracts/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.

**Comment by rommzestz** [comment]
seems i skip one of part or steps on build

**Comment by rommzestz** [comment]
maybe try on ubuntu 18.04 ?

**Comment by jgiszczak** [comment]
Your best bet is definitely Ubuntu 18.04, but you also need to be sure to use compatible versions.  You don't have eosio.cdt 1.5.x installed, so your contract build is failing.  Replace the eosio.cdt installed on your system to match the version required by the version of eosio.contracts you are using.

**Comment by rommzestz** [comment]
All fine now! I am build contracts in one step. ./build.sh
Thx!

**Comment by rommzestz** [comment]
you can close this issue.
it solved on Ubuntu 18.04
