### ISSUE TITLE
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func': (.text+0x16): undefined reference to `pthread_atfork'

### ISSUE THREAD

**Issue by heng5120** [EOSIO/eos#8225]
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':
(.text+0x16): undefined reference to `pthread_atfork'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/build.make:113: recipe for target 'libraries/fc/test/crypto/test_cypher_suites' failed
make[2]: *** [libraries/fc/test/crypto/test_cypher_suites] Error 1
CMakeFiles/Makefile2:789: recipe for target 'libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all' failed
make[1]: *** [libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 91%] Built target eosio_chain
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by heng5120** [comment]
please help me how to solve this error,thanks!!

**Comment by spoonincode** [comment]
what OS are you running on?

**Comment by heng5120** [comment]
> what OS & eosio version are you running on?

thank you for answer my question,but I have resolved it with running on a .deb package.
