### ISSUE TITLE
nodeos gets into 'coma' state in 2.0.0-rc2

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8227]
There are multiple reports on jungle test network where nodeos gets into a 'coma' state and stops syncing blocks from the rest of the network.  I also ran into such a situation on EOS Mainnet running 2.0.0-rc2. My logs were sent to @heifner

**Comment by matthewdarwin** [comment]
Work is progressing under https://github.com/EOSIO/eos/pull/8229

**Comment by matthewdarwin** [comment]
The PR referenced above definitely helps.

**Comment by heifner** [comment]
Resolved by #8229
