### ISSUE TITLE
Unable to run Cleos after eosio install via brew on Catalina

### ISSUE THREAD

**Issue by ismyhc** [EOSIO/eos#8235]
Trying to install eosio and use Cleos on Catalina is giving the following error:

OS: Catalina
Fresh install of brew

brew tap eosio/eosio
brew install eosio

then when running Cleos

```
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/cleos
  Reason: image not found
```

There is a dylib at that location, but the version is different.
what I see is /usr/local/opt/openssl/lib/libssl.1.1.1.dylib

Tried 
brew update && brew upgrade
brew install openssl

brew remove openssl
brew install openssl

Any ideas?

**Comment by chesterliliang** [comment]
same issue

**Comment by bigonenice** [comment]
same isuue

**Comment by hkabesa** [comment]
+1

**Comment by orbachar** [comment]
+1

**Comment by spoonincode** [comment]
This is ultimately due to homebrew removing openssl 1.0. We'll have a quick fix to rebuild our binaries with openssl 1.1; long term we need to investigate static linking openssl again.

**Comment by duongph223** [comment]
@spoonincode Please help me to fix this.

**Comment by parcool** [comment]
```
$ dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/bin/keosd
  Reason: image not found
```
macOS Majave.

**Comment by hoang-dao** [comment]
Homebrew changed its version of Openssl to 1.1 days ago (https://github.com/Homebrew/homebrew-core/commit/0349a7ca76f483483c6d5c1d4cfe6b458dee2665 and https://github.com/Homebrew/homebrew-core/commit/b4b9c1cd84772e99432b5d2679fb0068da1e1e64).
We can downgrade Openssl to the older version to temporarily fix this issue while waiting for the new rebuild to come (or do it manually):

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/30fd2b68feb458656c2da2b91e577960b11c42f4/Formula/openssl.rb
```

**Comment by arezfuzin** [comment]
@hoang-dao your solution is working for mongodb but it will put issue for another package like postgres or telepresence.

**Comment by spoonincode** [comment]
This is fixed in 1.8.7's build scripts as it explicitly seeks out version 1.1

**Comment by aiavci** [comment]
> Homebrew changed its version of Openssl to 1.1 days ago ([Homebrew/homebrew-core@0349a7c](https://github.com/Homebrew/homebrew-core/commit/0349a7ca76f483483c6d5c1d4cfe6b458dee2665) and [Homebrew/homebrew-core@b4b9c1c](https://github.com/Homebrew/homebrew-core/commit/b4b9c1cd84772e99432b5d2679fb0068da1e1e64)).
> We can downgrade Openssl to the older version to temporarily fix this issue while waiting for the new rebuild to come (or do it manually):
> 
> ```
> brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/30fd2b68feb458656c2da2b91e577960b11c42f4/Formula/openssl.rb
> ```

When I try this, I get:

Invalid usage: Installation of openssl from a GitHub commit URL is unsupported! `brew extract openssl` to a stable tap on GitHub instead.

**Comment by mmislam101** [comment]
> brew install

I followed https://stackoverflow.com/a/59340180/3166719 successfully
