### ISSUE TITLE
The Ram(storage and memory type) Charge Of EOS?

### ISSUE THREAD

**Issue by weimumu** [EOSIO/eos#8236]
There are two types of storage charges for Ethereum: memory and storage types.

The storage charge on EOS is based on RAM. I understand that this corresponds to the storage type of Ethereum. So how does EOS charge for memory type, or does it limit the usage of memory type for a contract.

**Comment by weimumu** [comment]
Memory type data is similar to the red box in the figure.
![image](https://user-images.githubusercontent.com/20694989/69424385-6b385a00-0d63-11ea-83d9-9045b22220f8.png)

Storage type data is the table in a EOS smart contract, like:
![image](https://user-images.githubusercontent.com/20694989/69424479-adfa3200-0d63-11ea-9253-72a207ef69d8.png)

**Comment by swatanabe-b1** [comment]
Contract memory usage has a hard limit of 33 MiB.

**Comment by taokayan** [comment]
EOS will not charge contract runtime memory usage. As @swatanabe-b1 stated, the limit of runtime memory usage is 33MB, and the time spending on allocating the memory will be accumulated into cpu_usage of a transaction which will be billed later. 

However, If you use multi_index table to store something on-chain (which uses in-memory database), it will charge RAM from the corresponding payer.
