### ISSUE TITLE
cleos net peers documentation unclear as to how to forcibly disconnect peers

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8238]
It is not clear from the documentation at https://developers.eos.io/eosio-cleos/reference#cleos-net-disconnect how to disconnect a peer from nodeos.

1) the documentation says to use http:// which given p2p protocol is not HTTP, this seems strange
2) It is not clear how to format the peer address

```
$ cleos net peers
...
    "peer": "192.168.146.46:9876",
...

$ cleos net peer disconnect 192.168.146.46:9876
ERROR: ExtrasError: [peer]
close an existing connection
Usage: cleos net disconnect host
```

Presumably where it says "host" in the error message, it means "peer" (as in "host:port").

3) it is not clear how to disconnect a peer that has an inbound connection to us.  They have a blank "peer" address.  Also the "p2p_address" is filled with garbage of whatever someone typed in which has duplicates and really no meaning.

**Comment by dixia** [comment]
@matthewdarwin this page is no longer accessible. I think the current page is:

https://developers.eos.io/manuals/eos/latest/cleos/command-reference/net/disconnect

it does not say https.

other issues looks reside in the `cleos` code

**Comment by matthewdarwin** [comment]
Indeed, documentation looks correct now.

**Comment by matthewdarwin** [comment]
Did a new issue get opened for the rest?  Or I need to do that?

**Comment by matthewdarwin** [comment]
Specifically I am asking about how to disconnect an incoming connection.  I suspect the answer is that you cannot do this, but the documentation doesn't say that.
