### ISSUE TITLE
Cannot install home-brew onto my MacBook running Mojave 10.14.6

### ISSUE THREAD

**Issue by susans427** [EOSIO/eos#8244]
I get the following message:
Installing Homebrew ...

==> This script will install:

/usr/local/bin/brew

/usr/local/share/doc/homebrew

/usr/local/share/man/man1/brew.1

/usr/local/share/zsh/site-functions/_brew

/usr/local/etc/bash_completion.d/brew

/usr/local/Homebrew

==> Downloading and installing Homebrew...

error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

fatal: the remote end hung up unexpectedly

fatal: early EOF

fatal: index-pack failed

Failed during: git fetch origin master:refs/remotes/origin/master --tags --force

failed

**Comment by susans427** [comment]
also tried again and got this error:
Last login: Sat Nov 23 14:09:35 on ttys000
Valueds-MacBook% bash
bash-3.2$ cd /usr/local
bash-3.2$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
fatal: unable to access 'https://github.com/Homebrew/brew/': LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
bash-3.2$

**Comment by jgiszczak** [comment]
Check to see if you can load https://github.com/Homebrew/brew/ in a browser.  If you can't, you have a local networking problem and will need to fix that.  If you can, try again installing Homebrew.  You're suffering a transient network error.

If you still have the problem and wish to discuss further, please post it in https://apple.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by susans427** [comment]
I want to thank you for your help it’s been a while since I was able to get back into trying to install everything I live in the country and I have slow Internet right now I’m at my parents house and I tried to install homebrew and it installed quickly with no problems I just wanted to let you know that in case someone else has the same problem I had
This was due to a slow Internet thank you very much for your help

Sent from my iPhone

On Nov 25, 2019, at 1:04 PM, jgiszczak <notifications@github.com> wrote:

﻿

Check to see if you can load https://github.com/Homebrew/brew/ in a browser. If you can't, you have a local networking problem and will need to fix that. If you can, try again installing Homebrew. You're suffering a transient network error.

If you still have the problem and wish to discuss further, please post it in https://apple.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
