### ISSUE TITLE
why an eosio.token transfer need billed 18978us cpu time?

### ISSUE THREAD

**Issue by sampleblood** [EOSIO/eos#8249]
two relate logs:
{"code":3080004,"name":"tx_cpu_usage_exceeded","what":"Transaction exceeded the current CPU usage limit imposed on the transaction","details":[{"message":"billed CPU time (18978 us) is greater than the maximum billable CPU time for the transaction (18248 us)","file":"transaction_context.cpp","line_number":553,"method":"validate_cpu_usage_to_bill"}]}

and another :
{"code":3081001,"name":"leeway_deadline_exception","what":"Transaction reached the deadline set due to leeway on account CPU limits","details":[{"message":"the transaction was unable to complete by deadline, but it is possible it could have succeeded if it were allowed to run to completion","file":"transaction_context.cpp","line_number":494,"method":"checktime"}]}

**Comment by jgiszczak** [comment]
It seems very unlikely that an unmodified eosio.token transfer is requiring almost 19 ms to complete.  It is regularly tested in automated tests.  Typically the billed CPU time is under 20 microseconds.  More than likely some other part of the transaction you are attempting is requiring too much time and your contract needs to be optimized or the transactions redesigned into a series of simpler actions which can be executed in the available time.

**Comment by sampleblood** [comment]
> It seems very unlikely that an unmodified eosio.token transfer is requiring almost 19 ms to complete. It is regularly tested in automated tests. Typically the billed CPU time is under 20 microseconds. More than likely some other part of the transaction you are attempting is requiring too much time and your contract needs to be optimized or the transactions redesigned into a series of simpler actions which can be executed in the available time.

this service has been running for a long time and succeed many transaction, there is no contract, only single eosio.token transfer action. after this fail,  I used another account with different nodeos to send the same transaction, succeed with  197us cpu used.
