### ISSUE TITLE
bios-boot-tutorial.py incompatible with current system contracts

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#8261]
When running bios-boot-tutorial.py with current system contracts, I get the error

```
Reading WASM from /opt/src/eosio.contracts/build/contracts/eosio.system/eosio.system.wasm...
Publishing contract...
Error 3070000: WASM Exception
Error Details:
env.is_feature_activated unresolveable
```

The script needs to activate `PREACTIVATE_FEATURE` before setting the contract.

**Comment by cc32d9** [comment]
as a workaround, it worked with `eosio.cdt_1.5.0` and eosio.contracts release 1.6.1

**Comment by danazkari** [comment]
I'm still having issues with the process described in the boot tutorial, I've been trying to spin up a new 2.0 blockchain following both the documentation on the BIOS sequence, and the boot tutorial you have in the repo, neither are working for me, I created a small repo to illustrate the issues with a `makefile` to `make things-easier` (pun intended ;) )

https://github.com/eoscostarica/eos-test

Steps to reproduce the bug in the boot tutorial are there, but also with my attempt to reproduce the python script in bash for my own project.

Can you please help me figure out if this is a bug or just PEBKAC?

**Comment by b1bart** [comment]
This is a shot from the hip but, it seems like your script (and our python code) is falling for the same issues we had in our tropical stay demo which was addressed with some higher tolerance for transaction times and retry logic: https://github.com/EOSIO/tropical-example-web-app/commit/0f5b3be4c75cfea243b419a48ba79092124a7904

more specifically, can you try adding a larger-than-default `--max-transaction-time` parameter do your `nodeos` invocation.  If that works we can work on fixing most of errant tutorials

**Comment by iamveritas** [comment]
both the script and the tutorial have been updated in EOSIO version 2.1.
the EOSIO 2.1-RC1 has just been released.
