### ISSUE TITLE
question for v1/history/get_transaction & get_action

### ISSUE THREAD

**Issue by puffanddmx** [EOSIO/eos#8266]
history / get_transaction When you inquire through the rpc command, you can see the contents of the link information. Can you explain what the information means? The output is separate from the trx information. transaction information needs only trx information for get_transaction command, but explain why you put those traces with putting duplicate tx information?
https://github.com/EOSIO/eos/blob/eb88d033c0abbc481b8a481485ef4218cdaa033a/libraries/chain/include/eosio/chain/trace.hpp#L35L37

In the example below, when get_acion is used when using the eos send command, the same action is always displayed three times. Explain why three things look the same. In the eos receive command, when get_acion is performed, the same action is always shown one.
------------------------------------------------------------------------------------------------------
curl history/get_actions -d '{"account_name":"bithumbsend2","pos":-1, "offset":-3}'
{
    "actions": [
        {
            "account_action_seq": 139,
            "action_trace": {
                "account_ram_deltas": [],
                "act": {
                    "account": "eosio.token",
                    "authorization": [
                        {
                            "actor": "bithumbsend2",
                            "permission": "active"
                        }
                    ],
                    "data": {
                        "from": "bithumbsend2",
                        "memo": "",
                        "quantity": "2000.0000 EOS",
                        "to": "allaglobalio"
                    },
                    "hex_data": "20d254f848ddb23b405d348746666234002d31010000000004454f530000000000",
                    "name": "transfer"
                },
                "action_ordinal": 1,
                "block_num": 92866896,
                "block_time": "2019-12-02T07:27:12.000",
                "closest_unnotified_ancestor_action_ordinal": 0,
                "console": "",
                "context_free": false,
                "creator_action_ordinal": 0,
                "elapsed": 3962,
                "error_code": null,
                "except": null,
                "producer_block_id": "05890950a22a10954ec55f70c1428f7f871ea6975126af17a415ce89d86062e4",
                "receipt": {
                    "abi_sequence": 4,
                    "act_digest": "cdb2edb9da385caae1d1ecebe862fbc95f1175d4d6a8c4c33304380cd7285b4d",
                    "auth_sequence": [
                        [
                            "bithumbsend2",
                            24625
                        ]
                    ],
                    "code_sequence": 4,
                    "global_sequence": "18682810304",
                    "receiver": "eosio.token",
                    "recv_sequence": 3497911839
                },
                "receiver": "eosio.token",
                "trx_id": "dd4e4a8277492adde63513b25ab8502ff63a07567f59a5cc5492aaf3aff3ef4b"
            },
            "block_num": 92866896,
            "block_time": "2019-12-02T07:27:12.000",
            "global_action_seq": "18682810304"
        },
        {
            "account_action_seq": 140,
            "action_trace": {
                "account_ram_deltas": [],
                "act": {
                    "account": "eosio.token",
                    "authorization": [
                        {
                            "actor": "bithumbsend2",
                            "permission": "active"
                        }
                    ],
                    "data": {
                        "from": "bithumbsend2",
                        "memo": "",
                        "quantity": "2000.0000 EOS",
                        "to": "allaglobalio"
                    },
                    "hex_data": "20d254f848ddb23b405d348746666234002d31010000000004454f530000000000",
                    "name": "transfer"
                },
                "action_ordinal": 2,
                "block_num": 92866896,
                "block_time": "2019-12-02T07:27:12.000",
                "closest_unnotified_ancestor_action_ordinal": 1,
                "console": "",
                "context_free": false,
                "creator_action_ordinal": 1,
                "elapsed": 4,
                "error_code": null,
                "except": null,
                "producer_block_id": "05890950a22a10954ec55f70c1428f7f871ea6975126af17a415ce89d86062e4",
                "receipt": {
                    "abi_sequence": 4,
                    "act_digest": "cdb2edb9da385caae1d1ecebe862fbc95f1175d4d6a8c4c33304380cd7285b4d",
                    "auth_sequence": [
                        [
                            "bithumbsend2",
                            24626
                        ]
                    ],
                    "code_sequence": 4,
                    "global_sequence": "18682810305",
                    "receiver": "bithumbsend2",
                    "recv_sequence": 9060
                },
                "receiver": "bithumbsend2",
                "trx_id": "dd4e4a8277492adde63513b25ab8502ff63a07567f59a5cc5492aaf3aff3ef4b"
            },
            "block_num": 92866896,
            "block_time": "2019-12-02T07:27:12.000",
            "global_action_seq": "18682810305"
        },
        {
            "account_action_seq": 141,
            "action_trace": {
                "account_ram_deltas": [],
                "act": {
                    "account": "eosio.token",
                    "authorization": [
                        {
                            "actor": "bithumbsend2",
                            "permission": "active"
                        }
                    ],
                    "data": {
                        "from": "bithumbsend2",
                        "memo": "",
                        "quantity": "2000.0000 EOS",
                        "to": "allaglobalio"
                    },
                    "hex_data": "20d254f848ddb23b405d348746666234002d31010000000004454f530000000000",
                    "name": "transfer"
                },
                "action_ordinal": 3,
                "block_num": 92866896,
                "block_time": "2019-12-02T07:27:12.000",
                "closest_unnotified_ancestor_action_ordinal": 1,
                "console": "",
                "context_free": false,
                "creator_action_ordinal": 1,
                "elapsed": 18187,
                "error_code": null,
                "except": null,
                "producer_block_id": "05890950a22a10954ec55f70c1428f7f871ea6975126af17a415ce89d86062e4",
                "receipt": {
                    "abi_sequence": 4,
                    "act_digest": "cdb2edb9da385caae1d1ecebe862fbc95f1175d4d6a8c4c33304380cd7285b4d",
                    "auth_sequence": [
                        [
                            "bithumbsend2",
                            24627
                        ]
                    ],
                    "code_sequence": 4,
                    "global_sequence": "18682810306",
                    "receiver": "allaglobalio",
                    "recv_sequence": 636
                },
                "receiver": "allaglobalio",
                "trx_id": "dd4e4a8277492adde63513b25ab8502ff63a07567f59a5cc5492aaf3aff3ef4b"
            },
            "block_num": 92866896,
            "block_time": "2019-12-02T07:27:12.000",
            "global_action_seq": "18682810306"
        }
    ],
    "last_irreversible_block": 92867413
}

**Comment by taokayan** [comment]
A normal EOS transfer action will results in 3 different action traces with consecutive action_ordinal numbers: 1st action trace has action_ordinal 1 and receiver equals to eosio.token. 2nd action trace has action_ordinal 2 and receiver equals to token sender (bithumbsend2). 3rd action trace has action_ordinal 3 and receiver equals to token receiver (allaglobalio). This means for a transfer action, it can be up to 3 different contracts involved: transfer action in contract eosio.token, notification handler in contract bithumbsend2(if exists), and notification handler in contract allaglobalio(if exists).

**Comment by puffanddmx** [comment]
I know there are three recipients, but I wonder why I use three to create a single transaction. In case of other coins, you need only one information when you send it.

**Comment by jgiszczak** [comment]
Three are generated because the EOS.IO platform isn't just a coin.  It supports contracts.  All accounts involved may be running contracts that can generate additional automated transactions in response to a transfer.  Three traces are required because the receiver is different in each case, which allows routing to the correct accounts and triggering any contracts present correctly.

Cryptocurrency systems that are only a distributed ledger, without contracts, are likely to be simpler.
