### ISSUE TITLE
cleos system newaccount fails

### ISSUE THREAD

**Issue by eosneedhelp** [EOSIO/eos#8267]
I have reviewed issue #4565 and tried various URLs, but cannot create a new account. I believe I have enough EOS in the creator account.

`$ cleos --url http://api.eosnewyork.io system newaccount --stake-cpu "3.0000 EOS" --stake-net "1.0000 EOS" --buy-ram-kbytes 8 zzzklfsdkass zzzzzosdifja EOS54sixnw9Cuj3xHNhXhu3w7UyN7CBaf76majcb1s5UrNFihsMuF`
`Error 3081001: Transaction reached the deadline set due to leeway on account CPU limits`
`Error Details:`
`the transaction was unable to complete by deadline, but it is possible it could have succeeded if it were allowed to run to completion`
`pending console output: `
`$ cleos --url https://eu1.eosdac.io:443 system newaccount --stake-cpu "3.0000 EOS" --stake-net "1.0000 EOS" --buy-ram-kbytes 8 zzzklfsdkass zzzzzosdifja EOS54sixnw9Cuj3xHNhXhu3w7UyN7CBaf76majcb1s5UrNFihsMuF`
`Error 3080004: Transaction exceeded the current CPU usage limit imposed on the transaction`
`Error Details:`
`billed CPU time (649 us) is greater than the maximum billable CPU time for the transaction (14 us)`

Here is the creator account which has 9 EOS:

```
$ cleos -u https://api.eosnewyork.io:443 get account zzzklfsdkass
created: 2019-12-01T21:56:52.500
[...]
memory: 
     quota:     5.346 KiB    used:     3.365 KiB  

net bandwidth: 
     staked:          0.0512 EOS
     delegated:       0.0000 EOS
     used:                 0 bytes
     available:        46.59 KiB  
     limit:            46.59 KiB  

cpu bandwidth:
     staked:          0.1536 EOS
     delegated:       0.0000 EOS
     used:                 0 us   
     available:           14 us   
     limit:               14 us   

EOS balances: 
     liquid:            9.4810 EOS
     staked:            0.2048 EOS
     unstaking:         0.0000 EOS
     total:             9.6858 EOS
```

If I understand correctly, I don't have enough staked to create an account; however, I created that account through Scatter which doesn't have an option of apportioning how much should be staked and it keeps creating accounts with just 0.15 staked. So it seems I'm in a catch 22 because new accounts created with Scatter don't have enough staked to stake more or create new accounts?

Background question: https://eosio.stackexchange.com/questions/5092/error-3080004-transaction-exceeded-the-current-cpu-usage-limit-imposed-on-the-t

**Comment by jgiszczak** [comment]
Mainnet is substantially busy.  The amount of CPU stake required for a 650 microsecond transaction is at least 7 EOS and it could be higher.  There are various websites that can provide stake estimates for EOS.IO-based networks.  Search for "eos mainnet transaction required stake" and similar queries.
