### ISSUE TITLE
Filter-out in state history

### ISSUE THREAD

**Issue by elnoxvie** [EOSIO/eos#8268]
Since **eidos** contract were introduced, our demuxjs application has become considerably slow. The size of data per block also increased quite significantly. The bottleneck seems to be the parsing and retrieving of block data. Hence, i am asking for experts help here if it's possible to filter out certain transactions such as those from Eidos Contract. 

Thanks.

**Comment by jgiszczak** [comment]
The state history plugin does not currently support filters in nodeos.  Consider composing more specific queries to your postgresql or rocksdb instance to avoid retrieving entire blocks.  Your `SELECT` statement can filter on the `account` or `receipt_receiver` columns, for instance.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

**Comment by elnoxvie** [comment]
Thanks. @jgiszczak . will do so.
