### ISSUE TITLE
Transaction declares authority but does not have signatures for it

### ISSUE THREAD

**Issue by samhatem** [EOSIO/eos#8284]
Running into a lot of errors trying to deploy a contract to the jungle test net.
<img width="655" alt="Screen Shot 2019-12-06 at 3 20 14 AM" src="https://user-images.githubusercontent.com/39573198/70307527-5f26b080-17d7-11ea-8c06-94736934851e.png">

And yes I have already imported my private key (I've tried importing multiple private keys) and tried everything from #4432.

**Comment by samhatem** [comment]
I'm following the set up from https://developers.eos.io/eosio-home/docs and keosd is getting an error: FC Exception encountered while processing wallet.get_public_keys
<img width="572" alt="Screen Shot 2019-12-06 at 6 19 04 AM" src="https://user-images.githubusercontent.com/39573198/70319460-555d7700-17f0-11ea-9525-e7d11103f248.png">

**Comment by jgiszczak** [comment]
Try running keosd with `--verbose-http-errors` to get more detail about the error.  Most likely you've either restarted keosd or it has timed out and locked the default wallet.  `get_public_keys` will not succeed if the wallet is locked.

**Comment by samhatem** [comment]
Still getting the same error trying to deploy the contract, but not getting any error with keosd now.

I'm running:

keosd --verbose-http-errors &

nodeos -e -p eosio \
--plugin eosio::producer_plugin \
--plugin eosio::chain_api_plugin \
--plugin eosio::http_plugin \
--plugin eosio::history_plugin \
--plugin eosio::history_api_plugin \
--filter-on="*" \
--access-control-allow-origin='*' \
--contracts-console \
--http-validate-host=false \
--verbose-http-errors >> nodeos.log 2>&1 &

cleos wallet unlock
cleos -u https://api.jungle.alohaeos.com set contract mnenomneno22 mneno/ "/mneno.wasm" "/mneno.abi" -p mnenomneno22@owner

cleos get account mnenomneno22 returns the expected output by the way.

**Comment by jgiszczak** [comment]
And what is keosd now reporting?

**Comment by ndcgundlach** [comment]
No response for a month.
