### ISSUE TITLE
EOS Code build issue 

### ISSUE THREAD

**Issue by danirabbani90** [EOSIO/eos#8308]
Hi i have changed the address prefix in both public_key.hpp and CmakeLists.txt file but the address is still coming up with prefix of EOS ? after that i have ran build.sh it builds the code but it does not change ?? the EOS prefix didnt change can someone help me out in this case ?

**Comment by jgiszczak** [comment]
If you mean the core symbol, use the `-s NAME` command line argument to `eosio_build.sh`.  `NAME` must be at least 1 and no more than 7 characters.

Note that in EOS.IO, keys are not synonymous with addresses.  In EOS.IO, an account is an address.  Token balances are owned by an account.  Keys may be changed while the account name remains the same.

**Comment by danirabbani90** [comment]
I mean,  i am trying to create the private blockchain through Eos. But the problem is the address prefix it always starts with EOSrjsbshdbfbd....... (example)  . I want this address prefix to be starting with ABC.... because i am trying to create private block chain while making changes in cmakelists. Txt i also do cmake.  It says its. Using the core symbol asy own customised one but whrn i create the wallet the EOS PUBKEY STARTS WITH. EOS rather than my own symbol

**Comment by jgiszczak** [comment]
Your persistent use of the word "address" is demonstrating a fundamental misunderstanding of the software.  In EOS.IO, keys are not addresses.  Accounts are addresses.  This is not a bitcoin-based chain.

The legacy prefix in `public_key.hpp` is the one and only place required to change the human-readable key prefix.  The `string()` operator uses that prefix when rendering a public key for printing on the console.  `cleos` uses that operator when showing and handling key strings.  Internally in `keosd` and `nodeos`, the key material is kept in binary form and has no prefix at all.

If you are using third party software to display keys, either in a wallet or in a transaction, there is no guarantee that software uses the `public_key` conversion routines.  Check your wallet using `cleos`.  Be sure you are using the version of `cleos` built after changing the public key header, either by explicitly typing the path to the new binary in the build directory or by running the `eosio_install.sh` script from the scripts directory.  To avoid conflicts with your custom build, be sure you have removed any packaged version you may have installed.

**Comment by danirabbani90** [comment]
Thank you so much for the much needed help.

**Comment by danirabbani90** [comment]
Hi thanks for the help , but still the issue presist . the steps that i follow after making the change in Public_key.hpp file is ./eosio_build.sh , then ./eosio_install.sh and then i ran cleos wallet create_key but the key prefix remained the same although its successfully built ??? can you please offer some adivce on how to know about the cleos version

**Comment by jgiszczak** [comment]
Run `cleos version client` to see which cleos you are invoking.  Older versions will say something like `Build version: 14185431`.  Newer versions will say something like `v2.0.0-rc2`.  You should have the newer version.  You must then run `cleos version full` to see the details of the build.  The result should look something like `v2.0.0-develop-ba73eeda0f823832a458c784b55f69d986bdbf1c-dirty`.  If you don't see `-dirty` at the end, you're not running the version you built.  Run the uninstall script or the package removal program for your platform to remove old versions.

**Comment by danirabbani90** [comment]
Thank you for your kind advice. But actually the cleos version full is not the command in the input . its not working. Anyways i have build my separate code removed cleos nodeos and keosd d , because in the cleos client version says something like Build Version : 1418764423
