### ISSUE TITLE
Modify table fields with data in it

### ISSUE THREAD

**Issue by raphaelgodro** [EOSIO/eos#8320]
Is there a plan to be able to change the structure of a table on an eosio smart contract with existing data in it? This is a huge issue for systems in production.

 - Writing migration scripts every time is not a solution. It creates a bottleneck and is manual every time. It also creates a downtime.
 - Creating other joint table is not a solution, slows down the queries for clients
 - JSON fields are not a solution, its slowing down and takes more memory. makes it hard to filter too.
- Adding extra fields just in case is also not a solution, its circumventing the source problem and you eventually run out of these fields.

Software always change with time. Business requirements are evolving.

**Comment by taokayan** [comment]
This maybe a possible design that supports extension in the future:

```
// vesion 1:
struct futuredata { char _unused; };
struct [[eosio::table]] userdata {
  uint64_t userid; // primary key
  string string_data; 
  std::optional<futuredata> data_for_future;
};
```
keep in mind that data_for_future must be empty in version 1.

```
// vesion 2 (add new field "float_data" in the future):
struct futuredata { 
  double float_data;
};
struct [[eosio::table]] userdata {
  uint64_t userid; // primary key
  string string_data; 
  std::optional<futuredata> data_for_future;
};
```
in this case old data will still be serialized correctly, but you can put new data in data_for_future for new userid.

**Comment by jafri** [comment]
@taokayan can you safely upgrade version 2 to a struct with new field for version 3?

what if in version 3, you have:

struct futuredata { 
  double float_data;
  double float_data2;
  double float_data3;
};

**Comment by jafri** [comment]
@raphaelgodro why is JSON field not a solution? what is wrong with 

```
struct [[eosio::table]] userdata {
  uint64_t userid; // primary key
  std::map<std::string, std::string> data; 
};
```

**Comment by jafri** [comment]
Found this good resource: https://eosio.github.io/eosio.cdt/latest/best-practices/data-design-and-migration

**Comment by taokayan** [comment]
> @taokayan can you safely upgrade version 2 to a struct with new field for version 3?
> 
> what if in version 3, you have:
> 
> ```
> struct futuredata { 
>   double float_data;
>   double float_data2;
>   double float_data3;
> };
> ```

No, you probably need to have another optional for future's future.
```
struct futuredata { 
  double float_data;
  std::optional<int>  reserved_for_another_future;
};
```
