### ISSUE TITLE
llvm@9 is not accepted

### ISSUE THREAD

**Issue by pplns** [EOSIO/eos#8324]
Mac OS version 10.15.1 (19B88)

Error: No available formula with the name "llvm@4"
==> Searching for a previously deleted formula (in the last month)...
llvm@4 was deleted from homebrew/core in commit 5b9c4d0742:
  llvm@4: delete (https://github.com/Homebrew/homebrew-core/issues/46801)

**Comment by pplns** [comment]
Mac OS version 10.15.1 (19B88)
Change the "llvm@4" to "llvm@9" in the files of eos/tests/bash-bats/eosio_build_darwin.sh and eos/scripts/eosio_build_darwin_deps,then the  build will success!

**Comment by hextzd** [comment]
I get the same error? is there any guy can do something?

**Comment by hextzd** [comment]
Updating Home Brew.
Already up-to-date.
	Installing Dependencies.
Error: No available formula with the name "llvm@4" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
	Homebrew exited with the above errors.
	Exiting now.

macos1:ultrain-core vi$ git -C "$(brew --repo homebrew/core)" fetch --unshallow
fatal: dumb http transport does not support shallow capabilities

**Comment by spoonincode** [comment]
EOSIO 1.8 requires llvm version 4. The latest build script in 1.8.7 will download and build llvm 4 because as you've seen, the llvm@4 package is no longer available from homebrew.

EOSIO 2.0-rc3 works with llvm versions 7, 8, or 9. The build script will install llvm@7 from homebrew.

Please check if you're using 1.8.7 and if you're still having problems with it.

**Comment by jgiszczak** [comment]
See #8246.
