### ISSUE TITLE
2.0-rc2 get_table API broken for i128 keys

### ISSUE THREAD

**Issue by jnordberg** [EOSIO/eos#8330]
Posting the following payload to a 2.0 `/v1/chain/get_table_rows` gets completely different results than on 1.8, looks like both lower and upper bound is being ignored.

```json
{
    "json": true,
    "code": "decentiumorg",
    "scope": "decentiumorg",
    "table": "trending",
    "limit": 21,
    "key_type": "i128",
    "index_position": "3",
    "encode_type": "hex",
    "reverse": true,
    "lower_bound": "0x000000000000000000000000b0e9a461",
    "upper_bound": "0xffffffffffffffff00000000b0e9a461"
}
```

**Comment by swatanabe-b1** [comment]
The input format for uint128 was changed.

https://github.com/EOSIO/fc/pull/111
https://github.com/EOSIO/eos/pull/7530

**Comment by jnordberg** [comment]
Thanks for those references, I have some questions that weren't addressed there:

 - Shouldn't an API-breaking change be a version bump, i.e. `/v2/chain/get_table_rows`?
 - Shouldn't the new input format respect the `encode_type` setting?
 - Is there some example of how to construct a query using this new format? E.g. for the case when you have a two 64-bit indexes combined to a 128-bit index.

**Comment by shwuhk** [comment]
> Thanks for those references, I have some questions that weren't addressed there:
> 
> * Shouldn't an API-breaking change be a version bump, i.e. `/v2/chain/get_table_rows`?
> * Shouldn't the new input format respect the `encode_type` setting?
> * Is there some example of how to construct a query using this new format? E.g. for the case when you have a two 64-bit indexes combined to a 128-bit index.

I agree that it is an API-breaking change. We upgrade our nodes but then all our service can't get running. Any ways to backward compatiable? The performance of v2.0.0 is much better and we would like to use it very much.

**Comment by matthewdarwin** [comment]
Since 2.0.0 was already released, I assume the decision is to do nothing about this incompatibility (now it's too late, dAPPs have to adjust)

**Comment by jgiszczak** [comment]
The previous behavior is considered defective.  Code that was making it work in spite of the defect is a workaround.  The new version works as the `/v1/` API was intended to work.

**Comment by jnordberg** [comment]
That's disappointing, I hope this is not how other API-breaking changes will be handled in the future.

To anyone finding this thread looking for a solution here is what you need to do:

First query the node using a `get_info` call and check `server_version_string` to know which "version" of `get_table_rows` to use. If the version string starts with `v2` use some bignum library (e.g. [BigInteger.js](https://github.com/peterolson/BigInteger.js)) to encode your `lower_bound` and `upper_bound` params to a decimal string and it should work like before.
