### ISSUE TITLE
Custom Built Cleos

### ISSUE THREAD

**Issue by danirabbani90** [EOSIO/eos#8331]
Hi , I am trying to generate the ubuntu_18.04.deb for the custom built cleos. But unfortunately the generate_package.sh builts the cleos fine but when i do sudo apt install xxxx_amd64.deb  it does install as well but it doesnt installs my  custom built cleos globally ?can someone help thanks

**Comment by jgiszczak** [comment]
New packages of EOS.IO install the software to `/usr/opt/eosio/<version>/bin`.  Softlinks to the version installed last are created in `/usr/bin`.  This is a traditional "global" install location that should already be in your `PATH`.  Some shells may require you to execute the `rehash` command to see changes to executables in common path locations.

If you still have questions and wish to discuss it further, please post in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
