### ISSUE TITLE
allow config.ini to be split in multiple files, eg /etc/nodeos/config.d/

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8334]
In debian based systems it is very common to have configuration files split up into multiple chunks so they can be more easily managed by having different packages deploy part of the configuration.

This is a feature request to add an option to config.ini like "include = dir", and then have nodoes read all the config files within the "dir" directory.

Use case here: 
- block producers run many types of nodes (API, P2P, SHIP, BP, etc...)  
- Many parts of the configuration are common between those, and some are different.
- Would make it easier to have common stuff use a common configuration file.

**Comment by spoonincode** [comment]
For the most part this is already tracked over at EOSIO/appbase#66, so I'm going to close this one. The ability to include directories is a good idea.
