### ISSUE TITLE
when contracts-console = true, nodoes prints too many "misaligned reference" messages

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8350]
On EOS Mainnet, 5 million "misaligned reference"  messages per hour are sent to the log. This is really not helpful.

```
grep "misaligned reference" /var/log/syslog | cut -d\:  -f1 | uniq -c
5656679 Dec 18 00
6015364 Dec 18 01
6043497 Dec 18 02
5445104 Dec 18 03
```

(v1.8.7)

**Comment by matthewdarwin** [comment]
There is no logging.json

**Comment by spoonincode** [comment]
Maybe this should be a flag in the action trace; but eos-vm doesn't currently track this at all.

**Comment by matthewdarwin** [comment]
I am using wabt here.

**Comment by zhaoyilun** [comment]
I got the same problem in nodeos.log.Messages like "warn  2020-01-28T04:26:42.605 nodeos    wabt.hpp:632                  translate_one        ] misaligned reference
" are repeated in nodeos.log, the size of nodeos.log has become to 8G within 8 hours.
I am in the yas main-net, the only thing I do different from before is changes plugin history_plugin to state_history_plugin.

**Comment by sanaraufx** [comment]
Address in 2.1, should no longer be an issue.
