### ISSUE TITLE
v2.0.0-rc3 - tests FAILED: 	149 - nodeos_multiple_version_protocol_feature_mv_test (Failed)

### ISSUE THREAD

**Issue by verbus** [EOSIO/eos#8353]
All,
The build for v2.0.0-rc3 worked but getting this error on running the test.

        Start 3250: unwind_0_pass_unit_test_eos-vm-jit
3250/3250 Test #3250: unwind_0_pass_unit_test_eos-vm-jit .................   Passed    1.06 sec

99% tests passed, 2 tests failed out of 3250

Label Time Summary:
long_running_tests         = 3837.07 sec*proc (11 tests)
mixed_version_tests        =  60.65 sec*proc (1 test)
nonparallelizable_tests    = 790.16 sec*proc (12 tests)
wasm_spec_tests            = 9932.93 sec*proc (3100 tests)

Total Test time (real) = 16175.45 sec

The following tests FAILED:
	149 - nodeos_multiple_version_protocol_feature_mv_test (Failed)

**Comment by jgiszczak** [comment]
This test is expected to fail outside of the CI/CD environment.  It will be omitted from the default test list after the referenced PR is merged.

**Comment by jgiszczak** [comment]
Also backported to 1.8 and 2.0 release tracks.  See #8399 and #8400.
