### ISSUE TITLE
v2.0.0-rc3  tests FAILED: 	1163 - const_217_pass_unit_test_eos-vm-oc (Failed)

### ISSUE THREAD

**Issue by verbus** [EOSIO/eos#8354]
All,
The build worked but.....

Start 3250: unwind_0_pass_unit_test_eos-vm-jit
3250/3250 Test #3250: unwind_0_pass_unit_test_eos-vm-jit .................   Passed    1.06 sec

99% tests passed, 2 tests failed out of 3250

Label Time Summary:
long_running_tests         = 3837.07 sec*proc (11 tests)
mixed_version_tests        =  60.65 sec*proc (1 test)
nonparallelizable_tests    = 790.16 sec*proc (12 tests)
wasm_spec_tests            = 9932.93 sec*proc (3100 tests)

Total Test time (real) = 16175.45 sec

The following tests FAILED:
	1163 - const_217_pass_unit_test_eos-vm-oc (Failed)
Errors while running CTest

**Comment by jgiszczak** [comment]
That test ordinarily passes.  Try running `ctest -R const_217_pass_unit_test_eos-vm-oc` from the `build` directory.

**Comment by verbus** [comment]
$ ctest -R const_217_pass_unit_test_eos-vm-oc

Test project /home/eosio/WDforEOSIOChains/eosio/src/eos/build
    Start 1163: const_217_pass_unit_test_eos-vm-oc
1/1 Test #1163: const_217_pass_unit_test_eos-vm-oc ...   Passed    2.30 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
wasm_spec_tests    =   2.30 sec*proc (1 test)

Total Test time (real) =   2.40 sec

This issue can be closed.

**Comment by jgiszczak** [comment]
I'm not aware of any timing sensitivity in the spec tests so there should be no instability here.  We'll chalk it up to cosmic rays for the time being.
