### ISSUE TITLE
Some execption for state history plugin

### ISSUE THREAD

**Issue by weimumu** [EOSIO/eos#8356]
I user nodeos 1.8.1 and run with state history plugin, but i face the problem shown in follows:
How can i solve it.
![image](https://user-images.githubusercontent.com/20694989/71150326-29b8a300-226c-11ea-85e3-0f5c5cae5bfc.png)
![image](https://user-images.githubusercontent.com/20694989/71150386-4bb22580-226c-11ea-88b5-727202aa2ce9.png)

**Comment by jgiszczak** [comment]
Remove your `trace_history.log` file and restart nodeos with `--replay-blockchain`.  Your log file is corrupt and must be replaced.
