### ISSUE TITLE
Issue with staking when CPU/NET is overused

### ISSUE THREAD

**Issue by hashimg74** [EOSIO/eos#8370]
Lately I've been experiencing an over use of CPU which now renders me unable to stake more, since this transaction requires a small amount of CPU/NET. 
I read in another thread with the same title as this one, that his work around was to use another account and delegate CPU to it from there. My problem is i don't know how to use the CPU that is delegated to the account. Can anyone point me in the right direction? 

![EB8A65AA-5884-4399-9C12-68871F7C086D_4_5005_c](https://user-images.githubusercontent.com/59128670/71316639-74871600-2438-11ea-867e-6b50e751993b.jpeg)

**Comment by taokayan** [comment]
As the network is congested, you may need to stake more CPU (maybe more than 10 EOS) for your account in order to pass the transaction itself.

**Comment by hashimg74** [comment]
Yes, it took me a while but I've figured it out... kinda sucks i'll just stick to Eth
