### ISSUE TITLE
Some error when using mongodb plugin

### ISSUE THREAD

**Issue by weimumu** [EOSIO/eos#8377]
I use the mongodb plugin and start nodeos --replay-blockchain, but something went wrong in the middle of replaying the transaction. At the same time, I found that during the replay transaction, mongod's memory footprint has been rising.
![image](https://user-images.githubusercontent.com/20694989/71553621-b540e980-2a4d-11ea-94b2-f88ac0015e78.png)

**Comment by weimumu** [comment]
I find the error in the source code, anyone know it? How can I solve it.
![image](https://user-images.githubusercontent.com/20694989/71553833-09010200-2a51-11ea-888c-6562b32165a9.png)
****

**Comment by weimumu** [comment]
@@matthewdarwin Do you know how to solve it?

**Comment by weimumu** [comment]
@matthewdarwin Do you know how to solve it?

**Comment by weimumu** [comment]
Anyone know how to solve this issue?

**Comment by heifner** [comment]
That looks like an indication that mongo server had some kind of error. I think you need to look at the mongo logs and/or seek mongo help.

**Comment by gleehokie** [comment]
Note that the Mongo DB plugin has been deprecated, consider using the State History Plugin instead.  See https://github.com/EOSIO/eos/issues/7597.
