### ISSUE TITLE
Node can not keep up with Mainnet

### ISSUE THREAD

**Issue by YordanPavlov** [EOSIO/eos#8397]
I am running a EOS Node in the following modes:

`--validation-mode=light --read-mode=irreversible`

The peer list I am providing the node is taken from https://eosnodes.privex.io/. For some reason my node is averaging 130K blocks per 24h which means it fails to keep up with the Mainnet, leave alone catching up. What would the be the way to investigate the cause of this? I am thinking two directions:

1. Hardware limitation. The Node is being run in AWS, which I know is not ideal, still it is far from reaching the limits assigned to it in terms of CPU and disk usage.
2. Peer connectivity problems. What I am observing on executing 'cleos net peers' is very few peers with "last_irreversible_block_num" > 0. As a metter of fact upon restar, using recent peers list I got only one such peer. Am I having connectivity problems? What would be the way to maintain a healty peer connectivity?

**Comment by jgiszczak** [comment]
The usual culprit is disk I/O.  Catching up to Mainnet requires an SSD or equivalent write throughput.  Check that nodeos isn't blocking waiting for I/O.

If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bug reporting and feature tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!
