### ISSUE TITLE
v2.0.0 max_client_count exceeded logging is too verbose (fill up disks with useless logs)

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8455]
When you have exceeded max_client_count and clients keep trying to connect, there is too much noise in the logs. It would be better to say X number of connections were rejected in the last 1 minute or something.

This is with default logging.

Could presumably cause a DOS by simply connecting to the P2P port over and over and then filling up the logs.

1. setup p2p node on public internet
1. set max connections to a low number
1. connect valid p2p clients to fill up all those connections, then watch what happens when you connect more clients over the limit

Jan 15 23:44:46 mar140 nodeos[6581]: info 2020-01-15T23:44:46.041 net-1 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:46 mar140 nodeos[6581]: error 2020-01-15T23:44:46.124 net-0 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:46 mar140 nodeos[6581]: info 2020-01-15T23:44:46.124 net-0 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:46 mar140 nodeos[6581]: error 2020-01-15T23:44:46.147 net-9 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:46 mar140 nodeos[6581]: info 2020-01-15T23:44:46.147 net-9 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:46 mar140 nodeos[6581]: error 2020-01-15T23:44:46.229 net-8 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:46 mar140 nodeos[6581]: info 2020-01-15T23:44:46.229 net-8 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:46 mar140 nodeos[6581]: error 2020-01-15T23:44:46.299 net-1 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:46 mar140 nodeos[6581]: info 2020-01-15T23:44:46.299 net-1 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:46 mar140 nodeos[6581]: error 2020-01-15T23:44:46.404 net-0 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:46 mar140 nodeos[6581]: info 2020-01-15T23:44:46.404 net-0 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:46 mar140 nodeos[6581]: error 2020-01-15T23:44:46.467 net-5 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:46 mar140 nodeos[6581]: info 2020-01-15T23:44:46.467 net-5 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:46 mar140 nodeos[6581]: error 2020-01-15T23:44:46.641 net-4 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:46 mar140 nodeos[6581]: info 2020-01-15T23:44:46.641 net-4 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:46 mar140 nodeos[6581]: error 2020-01-15T23:44:46.722 net-1 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:46 mar140 nodeos[6581]: info 2020-01-15T23:44:46.722 net-1 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:46 mar140 nodeos[6581]: error 2020-01-15T23:44:46.892 net-6 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:46 mar140 nodeos[6581]: info 2020-01-15T23:44:46.892 net-6 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:46 mar140 nodeos[6581]: error 2020-01-15T23:44:46.927 net-4 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:46 mar140 nodeos[6581]: info 2020-01-15T23:44:46.927 net-4 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:47 mar140 nodeos[6581]: error 2020-01-15T23:44:47.043 net-5 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:47 mar140 nodeos[6581]: info 2020-01-15T23:44:47.043 net-5 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:47 mar140 nodeos[6581]: error 2020-01-15T23:44:47.259 net-0 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:47 mar140 nodeos[6581]: info 2020-01-15T23:44:47.259 net-0 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:47 mar140 nodeos[6581]: error 2020-01-15T23:44:47.361 net-8 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:47 mar140 nodeos[6581]: info 2020-01-15T23:44:47.361 net-8 net_plugin.cpp:831 connection ] accepted network connection
Jan 15 23:44:47 mar140 nodeos[6581]: error 2020-01-15T23:44:47.390 net-5 net_plugin.cpp:2267 operator() ] Error max_client_count 20 exceeded
Jan 15 23:44:47 mar140 nodeos[6581]: info 2020-01-15T23:44:47.390 net-5 net_plugin.cpp:831 connection ] accepted network connection

**Comment by matthewdarwin** [comment]
I take it this is fixed in 2.0.1?

**Comment by heifner** [comment]
Yes, fix in 2.0.1.
