### ISSUE TITLE
lost transaction

### ISSUE THREAD

**Issue by lockp111** [EOSIO/eos#8463]
I push my transaction success and also find the trx_id in mongo, but it lost.
This is the link:
[https://bloks.io/transaction/aee9d1c0f97f8d84b54fa1464e35f2426de02cca800d407d17dab2e0fe229d77?tab=raw](https://bloks.io/transaction/aee9d1c0f97f8d84b54fa1464e35f2426de02cca800d407d17dab2e0fe229d77?tab=raw)

**Comment by heifner** [comment]
What do you mean by lost? The link you provided shows it was executed.

**Comment by lockp111** [comment]
> What do you mean by lost? The link you provided shows it was executed.

no no no, you  check the block num.
that block could not found this trx_id.

**Comment by taokayan** [comment]
Looks like this the issue of https://bloks.io/ not the blockchain itself. Transaction aee9d1c0f97f8d84b54fa1464e35f2426de02cca800d407d17dab2e0fe229d77 was is a block in the micro-fork (block time 2020-01-17T09:01:22.500), but later on this block is taken over by a longer fork (block time 2020-01-17T09:01:24.500). Therefore, this transaction is not confirmed in the blockchain and it is already expired.

**Comment by lockp111** [comment]
> Looks like this the issue of https://bloks.io/ not the blockchain itself. Transaction aee9d1c0f97f8d84b54fa1464e35f2426de02cca800d407d17dab2e0fe229d77 was in a block in the micro-fork (block time 2020-01-17T09:01:22.500), but later on this block is taken over by a longer fork (block time 2020-01-17T09:01:24.500). Therefore, this transaction is not confirmed in the blockchain and it is already expired.

Yes, but it also happend in my node. I had using mongo to save history. It can be found in transaction_traces and action_traces.It is happend too often after v1.8.6. Some times,I transfer the token,it will returns me success, but actually not.

**Comment by taokayan** [comment]
By the design of EOS blockchain, a transaction will not be considered fully confirmed until the relevant block became irreversible. Since EOS mainnet has an irreversible time of around 3 minutes, it is recommended to wait for 3 minutes from the expiration time of a transaction, and then start to verify whether the transaction is contained in the blockchain.

**Comment by lockp111** [comment]
> By the design of EOS blockchain, a transaction will not be considered fully confirmed until the relevant block became irreversible. Since EOS mainnet has an irreversible time of around 3 minutes, it is recommended to wait for 3 minutes from the expiration time of a transaction, and then start to verify whether the transaction is contained in the blockchain.

But why it won't happen in past few month? Now it happens too often, more than 10 times in a day

**Comment by jgiszczak** [comment]
> But why it won't happen in past few month? Now it happens too often, more than 10 times in a day

EOS Mainnet traffic has gone up dramatically in the past few months.  The additional load is causing many more microforks than the network previously experienced.  Efforts to better tune settings and to improve code are ongoing.

**Comment by matthewdarwin** [comment]
https://www.alohaeos.com/tools/reliability
