### ISSUE TITLE
V2.0.0  Compiled, source code prompts changes

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#8474]
Version: release v2.0.0
After executing ./scripts/eosio_build.sh, the source directory is changed.

![image](https://user-images.githubusercontent.com/7980920/72708622-1caa0f00-3b9e-11ea-99fe-9555168ff3ec.png)

Found that this llvmWARshim.llvmwar is linked to llvmWARshim.cpp

https://github.com/EOSIO/eos/blob/master/libraries/chain/webassembly/eos-vm-oc/llvmWARshim.llvmwar
![image](https://user-images.githubusercontent.com/7980920/72711529-2d5d8380-3ba4-11ea-8ecb-9496d52a7db0.png)

It feels that the 2.0.0 file management is worse than the previous version.

**Comment by spoonincode** [comment]
I can't reproduce this on Ubuntu 18.04 with 2.0.0. `git status` is clean after a `eosio_build.sh`. Can you describe your environment further?

**Comment by spoonincode** [comment]
Due to no response from submitter, going to close this. It appears submitter is on some sort of windows environment so it's possible git on windows doesn't handle symlinks or other unix-like features correctly.
