### ISSUE TITLE
EOS CPU Usage is always 100% which only use one cpu core.

### ISSUE THREAD

**Issue by lcgogo** [EOSIO/eos#8476]
Hi Support,

![image](https://user-images.githubusercontent.com/8175573/72740955-a9c28780-3be1-11ea-9a37-8dd7a0ec34aa.png)
My EOS 1.8.4 node has heavy traffic, however, the CPU usage is always 100% and does not use all my 4 cores  server.

Is there any config let eos process to use multi cpu?

**Comment by matthewdarwin** [comment]
Suggest you:
- upgrade to eosio 1.8.9
- remove p2p connections (maximum 4)
- upgrade hardware to get faster CPU

**Comment by lcgogo** [comment]
Many thanks, can you help to clarify the step 2 detail config?

Followed config is used in my node which I think may related.

# Maximum number of client0nodes from any single IP address (eosio::net_plugin)
p2p-max-nodes-per-host = 1

# Maximum number of clients from which connections are accepted, use 0 for no limit (eosio::net_plugin)
max-clients = 0

**Comment by matthewdarwin** [comment]
`max-clients = 4` (if you are accepting incoming connections)

Also check `p2p-peer-address = ` and make sure you have no more than 4 + the number of `max-clients`

**Comment by matthewdarwin** [comment]
Basically keep making it smaller until CPU is not 100%.   EOS Mainnet is very busy right now.

**Comment by lcgogo** [comment]
Many thanks, will follow your suggestion.

**Comment by jgiszczak** [comment]
Beyond that, `nodeos` is multithreaded but the threads are not balanced.  At present, additional cores can not be evenly loaded.  `nodeos` takes real advantage of only 2 cores, for now.

**Comment by heifner** [comment]
Yesterday I was running with a non-optimized build and cpu was sitting at 100%. If building yourself it is important to build an optimized non-debug build.

For example, I usually build: ` cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo`
