### ISSUE TITLE
[docs] Suggestion / Change Request

### ISSUE THREAD

**Issue by kingdavid6336** [EOSIO/eos#8479]
File: [docs/00_install/index.md](https://github.com/EOSIO/eos/blob/develop/docs/00_install/index.md)

**Comment by swatanabe-b1** [comment]
I'm don't know what you're asking for.

**Comment by jeffreyssmith2nd** [comment]
It also should be noted those files are used to generate the documentation at https://eosio.github.io/eos/latest/install/index and are not necessarily Markdown compliant, so that is the best place to view them.

**Comment by dskvr** [comment]
@jeffreyssmith2nd This person clicked "request changes" from the documentation site.

**Comment by dskvr** [comment]
Closing for now, @kingdavid6336  Please provide details and we will reopen the issue.
