### ISSUE TITLE
Please kill smart contract eidosonecoin

### ISSUE THREAD

**Issue by stone89son** [EOSIO/eos#8480]
I want to use Eos blockchain, But I cannot use it. I staked for 30 EOS, and can't play the game on dice.one and trade on Newdex. 
Please kill eidosonecoin it is a spammer. No one can handle spammer, just like email.

**Comment by matthewdarwin** [comment]
This github is about EOSIO core software ( nodeos), not about contracts that might be deployed on some EOSIO based network.  Block.one does not run EOS Mainnet so they cannot make any changes there.  Suggest closing this issue.
