### ISSUE TITLE
Proper instructions for upgrade from 1.8.9 to 2.0.0 with state-history

### ISSUE THREAD

**Issue by ksemaev** [EOSIO/eos#8508]
There is very few information in https://github.com/EOSIO/eos/releases/tag/v2.0.0 on upgrade process. It says though "The following instructions should be followed to upgrade nodeos from v1.8.x to v2.0.x without a full replay (after making appropriate backup copies)" without mentioning what are "appropriate backup copies"

So I started my 1.8.9 node with `--read-mode=irreversible --plugin=eosio::producer_api_plugin`, created a snapshot, stopped node, deleted` blocks/reversible` and `state` dirs. Now I have this layout:
```
745G	./blocks
2.5G	./snapshots
20K	./state
1.9T	./state-history
```

Next step I start my 2.0.0 node with `/usr/bin/nodeos --config-dir /home/eos/data/config --data-dir /home/eos/data/mainnet --disable-replay-opts --snapshot /home/eos/data/mainnet/snapshots/snapshot-060f398e418202f5c66fbd80b26b9ae0e484b10f7e565c6870f5a01d05711f54.bin` and get

> warn  2020-01-27T08:24:06.330 nodeos    chain_plugin.cpp:1074         plugin_initialize    ] 3110006 plugin_config_exception: Incorrect plugin configuration
Snapshot can only be used to initialize an empty database.
    {}
    nodeos  chain_plugin.cpp:858 plugin_initialize

What is an empty database? What should I remove? Maybe I need another settings in config.ini?

This is my current config ini, please advice:
```
    #Chain plugin settings
    chain-state-db-size-mb = 12288
    reversible-blocks-db-size-mb = 2048
    read-mode = read-only
    validation-mode = light
    wasm-runtime = wabt

    #Http plugin settings
    access-control-allow-origin = *
    http-validate-host = false
    verbose-http-errors = true

    #Net plugin settings
    agent-name = Agent
    sync-fetch-span = 200
    p2p-max-nodes-per-host = 4
    max-clients = 100
    p2p-server-address = 0.0.0.0:9876

    # State history plugin settings
    trace-history = true
    chain-state-history = true

    #Plugins
    plugin = eosio::chain_plugin
    plugin = eosio::state_history_plugin
    plugin = eosio::chain_api_plugin
    plugin = eosio::history_api_plugin
    plugin = eosio::http_plugin
    plugin = eosio::net_api_plugin

    #peers
```

**Comment by jgiszczak** [comment]
The 'database' in question is the contents of your `state` directory.  Yours is nearly empty, but not quite empty.  Remove the `shared_memory.bin` and `fork_db.dat` files in that directory to load a snapshot.  The contents of the snapshot will replace the `shared_memory.bin` file.
