### ISSUE TITLE
push_transaction timeout

### ISSUE THREAD

**Issue by clown-wang** [EOSIO/eos#8523]
Sending push_transaction request to nodeos is timeout
and only this api is not useful.
I can get blockdata from my endpoint,but i cant transaction with it.(the version is 1.8.1)
![image](https://user-images.githubusercontent.com/27940300/73256699-5f529380-41fd-11ea-8065-9431ab901251.png)
thanx

**Comment by taokayan** [comment]
I guess the endpoint is unavailable. You can try another nodeos RPC endpoint
