### ISSUE TITLE
Bug: nodeos logging strange behavior

### ISSUE THREAD

**Issue by ank-everstake** [EOSIO/eos#8533]
There is very strange behavior  when using extended logging (using logging.json).

What is observed:
"**enabled** - bool value to enable/disable the appender" - does not seem to work at all, nor in appenders, nor in loggers section. 
For example:

- if additional loggers are specified, nodeos - pushes messages, even if they are _**enabled:false**_
- stdout stream seems not to work at all, if you configure it as an appender and specify in logger, messages are pushed only to stderr stream
- If you configure a gelf-type appender and do not enable it - nodeos pushes a message in stderr like `opened GELF socket to endpoint host:port` and  indeed makes connection and pushes messages to the receiver specified
- if you specify **level:off** and **enabled:true** - nodeos pushes some log lines in stderr....it is a bit confusing, maybe it would be better to drop **level: off** and keep **enabled** value as in (refer syslog rfc5424), though making it work

Tested on v2.0.1 tag, built from sources, Ubuntu 18.04.2 LTS.

**Comment by johndebord** [comment]
Despite being in the `logging.json` file, those knobs have not been implemented yet. And we are currently reviewing the different avenues to approach modifying the logging facility.

**Comment by mharrisb1** [comment]
We are closing this issue. We are aware of this and other issues in `fc::logger` and will create a mega-issue linking this and the other logging-related issues soon to address all problems in one effort.
