### ISSUE TITLE
Unable to update producer schedule on eosio 2 chain running bios contract

### ISSUE THREAD

**Issue by scottoau** [EOSIO/eos#8541]
Hi,

I'm setting up a private eosio 2.0 testnet and would like to set the producer schedule using the "setprods" action in the bios contract. 

I'm running the following:

`cleos -u http://localnet:8888 push action eosio setprods 'testnetprods.json' -p eosio@active
`
Where the testnetprods.json is:

```
{
    "schedule": [
        {
            "producer_name": "eosio",
            "authority": [
                {
                    "threshold": 1,
                    "keys": [
                        {
                            "key": "EOS8FLEDoQfhRFnnvUjDBF8wmjYfgkqZVJd1nJeAATtDfG6cp9wsn",
                            "weight": 1
                        }
                    ]
                }
            ]
        }
    ]
}

```
I've tried using the cli direct, not file, it makes no difference. 

Error:

```
Error 3015014: Pack data exception
Error Details:
Expected input to be an array of two items while processing variant 'setprods.schedule[0].authority'
```

I've followed the ABI definition, but am at a loss as to what I'm missing. Assistance would be greatly appreciated. 

Thanks.

**Comment by jgiszczak** [comment]
The format `setprods` accepts has changed in 2.0.  System and BIOS contract [v1.9.0](https://github.com/EOSIO/eosio.contracts/releases) is now required.  The schedule is now a vector of `producer_authority` objects, introduced in EOSIO/eosio.contracts#349.  You'll need to use the new ABI and the new BIOS contract to successfully `setprods` in 2.0.

**Comment by scottoau** [comment]
@jgiszczak Thanks for replying, I understand the change and have followed the ABI but I'm still unable to update the schedule. Can you please provide a working example? It would help me solve the problem. Thanks in advance.

**Comment by scottoau** [comment]
Here is the example that worked for me:

{
    "schedule": [
        {
            "producer_name": "eosio",
            "authority": [
                "block_signing_authority_v0",
                {
                    "threshold": 1,
                    "keys": [
                        {
                            "key": "EOS8xxxx",
                            "weight": 1
                        }
                    ]
                }
            ]
        },{
            "producer_name": "bp2",
            "authority": [
                "block_signing_authority_v0",
                {
                    "threshold": 1,
                    "keys": [
                        {
                            "key": "EOSxxxxx",
                            "weight": 1
                        }
                    ]
                }
            ]
        }
    ]
}
