### ISSUE TITLE
nodeos 2.0.1 head stuck

### ISSUE THREAD

**Issue by n8d** [EOSIO/eos#8542]
I just had a 2.0.1 EOS mainnet node get stuck (or "coma" as is the term on Telegram 🙂) not receiving any new blocks. There wasn't anything revealing in the log; it just stopped receiving blocks and then some usual messages about can't connect to certain remote peers. The net_plugin_impl logging level is currently set to warn so some things may have been missed. We monitor the network pretty closely and I don't believe there was any sort of network outage that triggered it. CPU usage was at 0% where it normally sits around 50%. After a restart it immediately recovered and had no problem keeping up with head.

Backtrace while it was stuck:

[nodeosbt.log](https://github.com/EOSIO/eos/files/4132827/nodeosbt.2.log)

Some peer info while it was stuck:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/787401/73431731-54cbf300-42fe-11ea-9f62-e8528d51b537.png">

**Comment by heifner** [comment]
Can you provide your nodeos log output please.

**Comment by matthewdarwin** [comment]
I believe I may have run into the same issue.  Or at least similar issue with same symptoms.  Sent logs to @heifner on Feb 8.

**Comment by matthewdarwin** [comment]
In my situation the nodeos had just restored from snapshot and was catching up.  It was only connected to 2 other peers.

**Comment by heifner** [comment]
@matthewdarwin Your sync issue on Feb 8th was not this issue. I'm not exactly sure what your Feb 8th issue was. This issue there is no output at all from nodeos when it locks up.

**Comment by matthewdarwin** [comment]
Apparently setting `net-threads` back to the default of `2` reduces (eliminates?) comas.  Original issue was filed with `net-threads = 8`.
