### ISSUE TITLE
Corrections in the example for Transferring funds with the sample "currency" contract

### ISSUE THREAD

**Issue by gluneau** [EOSIO/eos#855]
Hello dear fellow EOS enthousiasts, if you build eosd and you try to run the sample contract: [Transfering funds with the sample "currency" contract](https://github.com/EOSIO/eos#transfering-funds-with-the-sample-currency-contract)

You will get this error:
![](https://image.ibb.co/gFydxw/helo_eos_smart_contract_error.png)

**Change #1 proposed**
The suggested message is erroneous:
```
./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":50}' --scope currency,inita --permission currency@active
```

The error in red does hint at what is wrong.  So kudos to @dan 's team for making the errors meaningful.

The "missing field in variant object: Missing 'amount' in variant object" gave me the inspiration to change the contract a little to this:

```
./eosc push message currency transfer '{"from":"currency","to":"inita","amount":50}' --scope currency,inita --permission currency@active
```

So for this contract, it not quantity anymore, it is amount.  And it worked from there.

**Change #2 proposed:**
Transfering takes two "r" so the subheader of this section should read like this:
Transferring funds with the sample "currency" contract

Have a great day and let's keep making @eosio better everyday!

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@helo/corrections-in-the-example-for-transferring-funds-with-the-sample-currency-contract">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by heifner** [comment]
Improved error messages were addd to cleos.
