### ISSUE TITLE
STAT-226 ⁃ Invalid Merkle calculation corner case

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#856]
If all the pending transactions have are rejected during block production, then the merkle calculation for the block will be wrong.

So if _pending_transactions has one transaction and it is rejected (like for ABI Table verification which is only performed for block generation, not pushed transactions)
in chain_controller::_generate_block:

```
   if( _pending_transactions.size() ) {
      pending_block.cycles.resize(1);
      pending_block.cycles[0].resize(1); // single thread

      for( const auto& pending_trx : _pending_transactions ) {
         if( (fc::time_point::now() - start) > _gen_block_time_limit ||
             pending_block_size > gprops.configuration.max_blk_size)
         {
            pending.push_back(pending_trx);
            continue;
         }
         try {
            ...
         } catch ( const fc::exception& e ) {
            edump((e.to_detail_string()));
         }
      }
   }

...
   pending_block.transaction_merkle_root = pending_block.calculate_merkle_root();

```

which eventually calls the following on pending_block.cycles[0][0]

```
   digest_type merkle(vector<digest_type> ids) {
      while (ids.size() > 1) {
         if (ids.size() % 2)
            ids.push_back(ids.back());
         for (int i = 0; i < ids.size() / 2; ++i)
            ids[i/2] = digest_type::hash(std::make_pair(ids[i], ids[i+1]));
         ids.resize(ids.size() / 2);
      }

      return ids.front();
   }
```

which assumes ids has at least 1 entry, which it will not.

This problem can be exposed by api_tests/test_table_store_fail_str_with_i64, which will likely be commented out, since the test is now problematic based on changes to not perform checks for pushed transactions.

Acceptance Test Criteria:
Specific problem is verified in unit tests and is a corner case scenario
Verifying block production during sanity checks and stress tests will validate that block production is not degraded.

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

[~dan.larimer]

**Comment by heifner** [comment]
Verified, closing.
