### ISSUE TITLE
Feature request: net_plugin needs to monitor peers activity

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#8562]
As experienced by EOSUSA, there are sometimes network conditions that keep the outgoing TCP connections open, but all incoming traffic is blocked in those sessions. So, nodeos considers the peer as connected and waits forever. Then the Linux kernel closes the socket after standard 15 minutes  timeout.

net_plugin needs to monitor the messages it receives from each peer, and if nothing has arrived within X seconds, it should close the connection. If it's an outgoing connection, it should start reconnecting. The period X should be configurable. As the blocks should arrive 2 times a second, default X=3 looks reasonable.

**Comment by sanaraufx** [comment]
This was fixed in 2.1.
