### ISSUE TITLE
Can't find ERC-20 standard token sample contract!

### ISSUE THREAD

**Issue by Gagan0436** [EOSIO/eos#858]
Is there any list of token standards which EOS platform supports? For e.g. ERC20 Standard Token

**Comment by kesar** [comment]
https://github.com/EOSIO/eos/tree/master/contracts/currency

**Comment by wanderingbort** [comment]
ERC-20's design is tightly coupled to the programming model available on Ethereum.  EOS.IO is pretty different but, the need for standardized currencies is evident.   You can track our development of such a standard in issue #1071

**Comment by gaboesquivel** [comment]
this is the new file location https://github.com/EOSIO/eos/blob/master/contracts/eosiolib/currency.hpp
