### ISSUE TITLE
[Feature request]Need a new mode for private peering network - 2.0.1 release read-only node not listen on p2p port(9876)

### ISSUE THREAD

**Issue by jjzhangg** [EOSIO/eos#8580]
eos-vm-jit, read-only

`netstat -a`, only see HTTP port, no P2P port

@heifner

**Comment by UMU618** [comment]
We can reproduce the problem.

**Comment by jjzhangg** [comment]
This is 2.0.1
`
if( my->db_read_mode == chain::db_read_mode::READ_ONLY && my->p2p_address.size() ) {
         my->p2p_address.clear();
         fc_wlog( logger, "node in read-only mode disabling incoming p2p connections" );
      }
`

This is 1.8.x
`
if( cc.get_read_mode() == chain::db_read_mode::READ_ONLY ) {
         my->max_nodes_per_host = 0;
         fc_ilog( logger, "node in read-only mode setting max_nodes_per_host to 0 to prevent connections" );
      }
`

**Comment by jjzhangg** [comment]
As top 21 BP, we need a new mode to create a peer network efficiently
1. sync block and allow p2p connection - BP can keep smooth connection with each other
2. do not sync trx -  the trxs feed to producer can be controlled by other barrier nodes
@heifner

**Comment by heifner** [comment]
Ref: #7886

**Comment by heifner** [comment]
@jjzhangg are you asking to allow both incoming and outgoing connections?

**Comment by jjzhangg** [comment]
> @jjzhangg are you asking to allow both incoming and outgoing connections?

Yes, we need a mode allowing both incoming and outgoing connections, and in these connections, only blocks are transmitted

**Comment by jjzhangg** [comment]
This new mode will perfectly match peering network requirement, and it can broadcasting blocks very efficiently @heifner

**Comment by heifner** [comment]
Thanks @jjzhangg for the report.
