### ISSUE TITLE
[docs] blocks.log callout

### ISSUE THREAD

**Issue by dixia** [EOSIO/eos#8582]
File: [docs/01_nodeos/04_replays/how-to-generate-a-snapshot.md](https://github.com/EOSIO/eos/blob/develop/docs/01_nodeos/04_replays/how-to-generate-a-snapshot.md)

The callout caption looks incomplete or grammatically incorrect

Other blocks.log files
You can also download a blocks.log file from third party providers.

Why are both plural files and a singular file used?

**Comment by lparisc** [comment]
I don't see a singular vs. plural conflict here. The name `blocks.log` describes a singular log file that contains blocks - a local copy of the blockchain. The title is plural because you can get various instances (plural) of such `blocks.log` files from different vendors.

**Comment by dixia** [comment]
Sorry for the tone was a bit too direct. It was late last night.

With your description, I understand it now. Maybe it is easier to follow for a new user as this:

Getting blocks.log files from other sources

What do you think?

**Comment by lparisc** [comment]
When designing callouts, I like to choose titles that are descriptive enough yet not too long. If the title is too long it will take more vertical space than needed. In this case, we could compromise by adding a verb to the title as you suggest but removing the last complement "from other sources". How about "Getting other `blocks.log` files" ?

**Comment by dixia** [comment]
Sounds good. will create a PL

**Comment by dixia** [comment]
fixed
