### ISSUE TITLE
 同步区块太消耗性能了！！

### ISSUE THREAD

**Issue by xyuer** [EOSIO/eos#8588]
peer跟peer之间同步数据太耗cpu，并且只能用到单核 ，这个问题不解决 eos主网会越来越拥堵！！！💊

> Google Translate:
> Synchronizing data between peers and peers takes too much CPU, and only single cores can be used. This problem does not solve the main network of eos, which will become more and more congested! !! !!

**Comment by sampleblood** [comment]
yes，always 100% cpu taken，api response timeout.

**Comment by matthewdarwin** [comment]
Suggest to do all of the following:
1) upgrade to 2.0.2 and use EOS-VM
2) reduce the number of p2p connections
3) increase CPU speed to 4Ghz or higher

**Comment by sampleblood** [comment]
> Suggest to do all of the following:
> 
> 1. upgrade to 2.0.2 and use EOS-VM
> 2. reduce the number of p2p connections
> 3. increase CPU speed to 4Ghz or higher

latest version is 2.0.1 ？
reduce connection to 2 seems not work.
using aws c5.large with cpu speed 3.9Ghz， z1d should be better?

thank you for your advice

**Comment by xyuer** [comment]
1、升级到2.0.2  是用eos-vm 并没有明显效果
2、事实上就算只有几个p2p connections 也会大量使用cpu。假如你是公共peer限制了连接数只会造成主网越来越拥堵
3、基于nodeos的工作效率就算你用10ghz的cpu也没用

请b1的开发人员去主网开启公共peer ，真实体验后在做代码改进。主网大量丢快主要原因就是这里。请改进同步机制 、序列化、反序列化。

**Comment by sampleblood** [comment]
> 1、升级到2.0.2 是用eos-vm 并没有明显效果
> 2、事实上就算只有几个p2p connections 也会大量使用cpu。假如你是公共peer限制了连接数只会造成主网越来越拥堵
> 3、基于nodeos的工作效率就算你用10ghz的cpu也没用
> 
> 请b1的开发人员去主网开启公共peer ，真实体验后在做代码改进。主网大量丢快主要原因就是这里。请改进同步机制 、序列化、反序列化。

是的，多核用不好，瓶颈太明显

**Comment by DenisCarriere** [comment]
@sampleblood yes, the z1d instance would perform a lot better compared to c5.large

**Comment by sampleblood** [comment]
> @sampleblood yes, the z1d instance would perform a lot better compared to c5.large

thank you @DenisCarriere 
but the single cpu speed of these two instance are almost the same, will they perform so different?

**Comment by past2017** [comment]
I got the same issue, it so trouble me,it take over 10 seconds to run v1/chain/get_info rpc command

**Comment by past2017** [comment]
@xyuer why you close this issue?

**Comment by xyuer** [comment]
@past2017 fullnode  can  use eos-vm-jit  sync block，
wasm-runtime = eos-vm-jit
eos-vm-oc-enable = true
do not use this , if you are bp

**Comment by sampleblood** [comment]
use 2.0.2 and config:
wasm-runtime = eos-vm-jit
eos-vm-oc-enable = true
performance improved a lot !

**Comment by UMU618** [comment]
> use 2.0.2 and config:
> wasm-runtime = eos-vm-jit
> eos-vm-oc-enable = true
> performance improved a lot !

But still can't gain the performance given by multi-core.

**Comment by sampleblood** [comment]
> > use 2.0.2 and config:
> > wasm-runtime = eos-vm-jit
> > eos-vm-oc-enable = true
> > performance improved a lot !
> 
> But still can't gain the performance given by multi-core.

cpu load reduced and api response improved, good enough for me by now.
