### ISSUE TITLE
./eosc create account inita currency PUBLIC_KEY_1 PUBLIC_KEY_2 execution error

### ISSUE THREAD

**Issue by JamesKnippel** [EOSIO/eos#860]
Running into this issue at the below step in the setup:
OSX Darwin.

./eosc create account inita currency PUBLIC_KEY_1 PUBLIC_KEY_2 

Error:
```
2571028ms            main.cpp:1165                 main                 ] Failed with error: Assert Exception (10)
base58str.substr(0, prefix_len) == prefix: 

```

anybody seen this before?

**Comment by JamesKnippel** [comment]
Oh, instructions were poorly read/worded. Should mention the previously generated keys in the step above. 

I'll make a medium setup guide with some of the known issues I've encountered with OSX for dummies. 

... like myself.

**Comment by rommzestz** [comment]
you heed use EOS51jM1b5cAFiJASy9BmfrGi64X2FyUopoGZhozeuk28NdQDC1eN instead 5K3rFUvNxXgN6K4rTJaw5BdmM8bPH5GMFDpVexZoSdDNVv8M2Vs
