### ISSUE TITLE
[docs] Dry up Nodeos options page

### ISSUE THREAD

**Issue by dskvr** [EOSIO/eos#8600]
File: [docs/01_nodeos/02_usage/00_nodeos-options.md](https://github.com/EOSIO/eos/blob/develop/docs/01_nodeos/02_usage/00_nodeos-options.md)

This page should instead provide anchored links to each plugin's option reference. At present, these details exist in two locations creating unnecessary maintenance overhead and drift potential.

**Comment by lparisc** [comment]
[docs/01_nodeos/02_usage/00_nodeos-options.md](https://github.com/EOSIO/eos/blob/develop/docs/01_nodeos/02_usage/00_nodeos-options.md)
