### ISSUE TITLE
error OPENSSL_ALGORITHM_DEFINES no longer supported

### ISSUE THREAD

**Issue by heipacker** [EOSIO/eos#8602]
1 -o CMakeFiles/cmcurl.dir/curl_sasl.c.o   -c /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/curl_sasl.c
In file included from /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/http_ntlm.c:40:
In file included from /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/curl_ntlm_core.h:41:
In file included from /usr/include/openssl/ssl.h:156:
In file included from /usr/include/openssl/x509.h:73:
In file included from /usr/include/openssl/evp.h:66:
/usr/include/x86_64-linux-gnu/openssl/opensslconf.h:20:3: error: OPENSSL_ALGORITHM_DEFINES no longer supported
# error OPENSSL_ALGORITHM_DEFINES no longer supported
  ^
[ 38%] Building C object Utilities/cmcurl/lib/CMakeFiles/cmcurl.dir/rand.c.o
cd /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib && /usr/bin/clang -DBUILDING_LIBCURL -DHAVE_CONFIG_H -I/root/eosio/2.0/src/cmake-3.13.2/Utilities -I/root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/include/curl -I/root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/include -I/root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/../include -I/root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/.. -I/root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib  -w   -std=gnu11 -o CMakeFiles/cmcurl.dir/rand.c.o   -c /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/rand.c
In file included from /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/http_ntlm.c:40:
In file included from /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/curl_ntlm_core.h:41:
In file included from /usr/include/openssl/ssl.h:165:
/usr/include/openssl/kssl.h:73:12: fatal error: 'krb5.h' file not found
#  include <krb5.h>
           ^~~~~~~~
In file included from /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/curl_ntlm_core.c:58:
/usr/include/openssl/des.h:91:9: error: unknown type name 'DES_LONG'
        DES_LONG deslong[2];
        ^
2 errors generated.
Utilities/cmcurl/lib/CMakeFiles/cmcurl.dir/build.make:1180: recipe for target 'Utilities/cmcurl/lib/CMakeFiles/cmcurl.dir/http_ntlm.c.o' failed
make[2]: *** [Utilities/cmcurl/lib/CMakeFiles/cmcurl.dir/http_ntlm.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/curl_ntlm_core.c:58:
In file included from /usr/include/openssl/des.h:102:
/usr/include/openssl/des_old.h:132:9: error: unknown type name 'DES_LONG'
        DES_LONG pad[2];
        ^
/usr/include/openssl/des_old.h:343:1: error: unknown type name 'DES_LONG'
DES_LONG _ossl_old_des_cbc_cksum(_ossl_old_des_cblock *input,
^
/usr/include/openssl/des_old.h:368:28: error: unknown type name 'DES_LONG'
void _ossl_old_des_encrypt(DES_LONG *data, _ossl_old_des_key_schedule ks,
                           ^
/usr/include/openssl/des_old.h:370:29: error: unknown type name 'DES_LONG'
void _ossl_old_des_encrypt2(DES_LONG *data, _ossl_old_des_key_schedule ks,
                            ^
/usr/include/openssl/des_old.h:372:29: error: unknown type name 'DES_LONG'
void _ossl_old_des_encrypt3(DES_LONG *data, _ossl_old_des_key_schedule ks1,
                            ^
/usr/include/openssl/des_old.h:375:29: error: unknown type name 'DES_LONG'
void _ossl_old_des_decrypt3(DES_LONG *data, _ossl_old_des_key_schedule ks1,
                            ^
/usr/include/openssl/des_old.h:422:1: error: unknown type name 'DES_LONG'
DES_LONG _ossl_old_des_quad_cksum(_ossl_old_des_cblock *input,
^
In file included from /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/curl_ntlm_core.c:58:
/usr/include/openssl/des.h:135:1: error: unknown type name 'DES_LONG'
DES_LONG DES_cbc_cksum(const unsigned char *input, DES_cblock *output,
^
/usr/include/openssl/des.h:165:19: error: unknown type name 'DES_LONG'
void DES_encrypt1(DES_LONG *data, DES_key_schedule *ks, int enc);
                  ^
/usr/include/openssl/des.h:175:19: error: unknown type name 'DES_LONG'
void DES_encrypt2(DES_LONG *data, DES_key_schedule *ks, int enc);
                  ^
/usr/include/openssl/des.h:177:19: error: unknown type name 'DES_LONG'
void DES_encrypt3(DES_LONG *data, DES_key_schedule *ks1,
                  ^
/usr/include/openssl/des.h:179:19: error: unknown type name 'DES_LONG'
void DES_decrypt3(DES_LONG *data, DES_key_schedule *ks1,
                  ^
/usr/include/openssl/des.h:219:1: error: unknown type name 'DES_LONG'
DES_LONG DES_quad_cksum(const unsigned char *input, DES_cblock output[],
^
In file included from /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/curl_ntlm_core.c:63:
In file included from /usr/include/openssl/ssl.h:156:
In file included from /usr/include/openssl/x509.h:73:
In file included from /usr/include/openssl/evp.h:66:
/usr/include/x86_64-linux-gnu/openssl/opensslconf.h:20:3: error: OPENSSL_ALGORITHM_DEFINES no longer supported
# error OPENSSL_ALGORITHM_DEFINES no longer supported
  ^
In file included from /root/eosio/2.0/src/cmake-3.13.2/Utilities/cmcurl/lib/curl_ntlm_core.c:63:
In file included from /usr/include/openssl/ssl.h:165:
/usr/include/openssl/kssl.h:73:12: fatal error: 'krb5.h' file not found
#  include <krb5.h>
           ^~~~~~~~
16 errors generated.
Utilities/cmcurl/lib/CMakeFiles/cmcurl.dir/build.make:1206: recipe for target 'Utilities/cmcurl/lib/CMakeFiles/cmcurl.dir/curl_ntlm_core.c.o' failed
make[2]: *** [Utilities/cmcurl/lib/CMakeFiles/cmcurl.dir/curl_ntlm_core.c.o] Error 1
make[2]: Leaving directory '/root/eosio/2.0/src/cmake-3.13.2'
CMakeFiles/Makefile2:1587: recipe for target 'Utilities/cmcurl/lib/CMakeFiles/cmcurl.dir/all' failed
make[1]: *** [Utilities/cmcurl/lib/CMakeFiles/cmcurl.dir/all] Error 2
make[1]: Leaving directory '/root/eosio/2.0/src/cmake-3.13.2'
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by spoonincode** [comment]
Please provide:
* Version of EOSIO you're trying to build
* Linux distribution & version you're using
* The command line arguments you passed to the build script

**Comment by heipacker** [comment]
Version of EOSIO you're trying to build
v2.0.1
Linux distribution & version you're using
ubuntu 18.0.4
The command line arguments you passed to the build script
./script/eosio_build.sh -s "EOS"

**Comment by spoonincode** [comment]
The errors appear like you may have an environment with mixed up openssl headers.

Try removing the openssl development packages
```
$ sudo apt-get remove libssl1.0-dev libssl-dev
```
and reinstalling
```
$ sudo apt-get install libssl-dev
```

After that I would recommend verifying the installation
```
$ dpkg -V libssl-dev
```
you should get no output from this verify command.

Then try building eosio again.

**Comment by spoonincode** [comment]
Closing due to no response. I couldn't reproduce.
