### ISSUE TITLE
Additional steps to Manual installation of the dependencies of EOS

### ISSUE THREAD

**Issue by gluneau** [EOSIO/eos#862]
Hello to all EOS enthusiast, if you try to manually install the dependencies of @eosio with a clean install Ubuntu 16.10, while following the instructions of the [Manual installation of the dependencies](https://github.com/EOSIO/eos#manualdep) you will get these errors:

![](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512149753/xc2bbvdvriwoa9wz1khf.png)

Thanks to @deaddy and his article: [First Install & Run of EOS on a Blank Ubuntu 16](https://steemit.com/eos/@deaddy/first-install-and-run-of-eos-on-a-blank-ubuntu-16) we just need to a a few steps before the `sudo apt-get update` such as:

>
>```
>sudo nano /etc/apt/sources.list
>```
>
>Taken from this address: http://releases.llvm.org/download.html add these lines:
>
>```
>deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main
>deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main
>```
>
>Save and Exit
> 

Then after the addition, success!

![](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512150722/l1klpnnn0oz7oxqddqhv.png)

And that's my suggestion for improvement.  Let's make EOS the best it can be.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@helo/additional-steps-to-manual-installation-of-the-dependencies-of-eos">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by nsgaga** [comment]
yes that seems like the issue I was experiencing, I wish I knew at the time.
Though I just used the 17.10 and all worked fine there (as clang/cmake defaults are just right), lot less issues on that side (and all built, running, working fine).
