### ISSUE TITLE
Make nodeos fail to start if eos-vm-oc-enable = true and producer-name = something

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8620]
Since Block.one specifically recommends not running `eos-vm-oc-enable = true` when signing, then nodeos should fail to start if it is going to be signing.  Could detect possibility of signing if ` producer-name =` is set.

That would catch non-recommended behavior.

**Comment by spoonincode** [comment]
The primary reason EOS VM Optimized Compiler isn't recommended for BPs on public networks is because it can be _much_ faster than even EOS VM JIT. So if BPs are running OC it can effectively force all other nodes on that chain to be running OC or they will be left in the dust. For public chains it is difficult to ensure this wide acceptance; particularly when, for example, there are still many nodes running pre 2.0, or we have supported platforms where OC doesn't even run yet (macos).

However, private blockchains don't suffer from those deployment woes: it's possible to ensure all nodes are running with OC enabled. Private blockchains are certainly a use case of EOSIO that even Block.one makes use of, so IMO I don't believe this is something that should be outright forbidden.

**Comment by matthewdarwin** [comment]
The main reason I was suggesting the change is that @arhag wrote in telegram back in January:

As a strategy to mitigate the risk posed by likely differences in behavior between the EOS VM variants while it is still young, we are suggesting that it would be wise to not use eos-vm-oc-enable=true on producing nodes and to just use eos-vm-jit by itself.

**Comment by cppfuns** [comment]
Is it still a problem if all BPs enable eos-vm-oc-enable at the same time?

**Comment by heifner** [comment]
It is not recommended for public network BPs to use eos-vm-oc-enable at this time.

**Comment by cppfuns** [comment]
> It is not recommended for public network BPs to use eos-vm-oc-enable at this time.

If I build my own private chain, all BPs have eos-vm-oc-enable enabled, is there any problem? That is to say, for BP nodes, there is not enough testing yet, is it uncertain whether it will be stable after opening?

**Comment by heifner** [comment]
Private chain where you control trxs you can run eos-vm-oc-enable on your BP signing node. You will also need to run it on all nodeos in the entire network for them to keep up. Also history may be difficult to maintain if running at full speed.

**Comment by cppfuns** [comment]
`Also history may be difficult to maintain if running at full speed.`
Sorry, don't understand why history is affected due to fast running

**Comment by heifner** [comment]
The bigger the blocks that nodeos produces (in terms of cpu billed size) the more data in terms of action data and state deltas and action traces are created that are stored in history solutions.

**Comment by cppfuns** [comment]
That is to say, after eos-vm-oc-enable is enabled, the node processing speed is faster, and TPS will grow a lot, resulting in more data stored in each block, but does not each block have a volume upper limit? Looks like 1MB or 2MB. The maximum amount of data for the chain processing, that is, each block is full, will only affect the query based on the chain layer, and will not affect the block generation?

**Comment by heifner** [comment]
The block size on EOS Mainnet is currently set at 1MB. However, that controls incoming transaction size. A very small transaction can have a loop that generates a huge number of inline actions. These inline actions are stored in many history solutions. So a 1MB block of incoming transactions could potentially generate many MBs of action trace data. Depending on speed that might even be measured in GBs.

**Comment by cppfuns** [comment]
That is, at present, eos-vm-oc-enable is still waiting for the chain to make some adaptations to the VM before it can be used on the BP node. If this is the case, would you like to ask, is there any expected time for completion?

Thank you for your dedication and warm answer

**Comment by heifner** [comment]
Sorry we do not discuss release dates or timelines outside normal announcements.

**Comment by cppfuns** [comment]
Thank you, expect eos-vm-oc-enable to be used in BP production environment earlier
