### ISSUE TITLE
Add more documentation for incoming-defer-ratio in config.ini

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8621]
The configuration options in config.ini are often poorly documented.  Add more comments about what `incoming-defer-ratio` does.

current:
```
# ratio between incoming transations and deferred transactions when both are exhausted (eosio::producer_plugin)
```

Suggestion to add to that:
* Processing always starts with 1 deferred transaction if any exists.
* Default of 1 means: 1 incoming trx per 1 deferred. 
* Setting of 20 would mean, 20 incoming per 1 deferred.
* If incoming is exhausted, then deferred will be taken regardless of the setting.

Also fix spelling of "transations" in existing documentation.

**Comment by dixia** [comment]
@matthewdarwin is issue referring directly on this page https://developers.eos.io/manuals/eos/latest/nodeos/usage/nodeos-configuration/ ? or we are talking about config.inin in a general sense

**Comment by matthewdarwin** [comment]
This is generally about config.ini  

Most of the information is on the plugin page for each option, that is  https://developers.eos.io/manuals/eos/latest/nodeos/plugins/producer_plugin/index for this case.

However, I don't think all the detailed information needs to be in the code (and printed in the default config.ini), but that's up to you how to manage.

What I am looking for is for each option: how that option works in detail and what are the use cases for changing it.   Currently the documentation only gives very limited information about "what?" and nothing about "why?". 

See also https://github.com/EOSIO/eos/issues/8650 for related kind of issue as this one.

**Comment by dixia** [comment]
@lparisc @heifner any additional information besides the what @matthewdarwin already specified?

**Comment by dixia** [comment]
Feel free to comment on this PL as well @matthewdarwin
