### ISSUE TITLE
Documentation says wavm is supported for wasm-runtime (it is not), doesn't mention eos-vm

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8624]
re: https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_plugin/index

The formatting of this page leaves much to be desired as the wrapping makes things unreadable.
However, the point of this issue is to say that the documentation is out of date.

It says:
```
--wasm-runtime wavm/wabt              Override default WASM runtime
```

* `wavm` was removed in 2.0.
* `wasm-runtime` = eos-vm-jit is not mentioned.
* `eos-vm-oc-enable` is not mentioned.

See also https://github.com/EOSIO/eos/issues/8620, where there are significant detail missing about when to use (and not use) these options.

Block.one spends quite a bit of time talking to people in telegram explaining things, but that knowledge is not always captured in the documentation.  Then people not familiar with discussion make mistakes because they can't find how to use stuff properly.

**Comment by lparisc** [comment]
We try to keep the plugin options current in the docs. This one slipped through the cracks unfortunately. It will be updated soon to reflect the 2.0 changes.

Re: the formatting, we will be replacing the CLI style output with tables for better browsing experience. In the meantime, try increasing the width of your browser window.

**Comment by lparisc** [comment]
[docs/01_nodeos/03_plugins/chain_plugin/index.md](https://github.com/EOSIO/eos/tree/develop/docs/01_nodeos/03_plugins/chain_plugin/index.md)
