### ISSUE TITLE
Broken link on producer plugin documentation page

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8625]
https://developers.eos.io/manuals/eos/latest/nodeos/plugins/producer_plugin/index

Get 404 when clicking on this:

> Additional configuration is required to produce blocks. Please read Configuring Block Producing Node.

**Comment by lparisc** [comment]
[docs/01_nodeos/03_plugins/producer_plugin/index.md](https://github.com/EOSIO/eos/tree/develop/docs/01_nodeos/03_plugins/producer_plugin/index.md)
