### ISSUE TITLE
My nodeos could not push transaction with "FC Exception encountered while processing chain.push_transaction"

### ISSUE THREAD

**Issue by devilrayzl** [EOSIO/eos#8628]
1.Run nodeos on my VM ubuntu16
2.Try to push my signed transaction to blockchain
3.Fail and the log from nodeos
`error 2020-02-11T09:10:36.860 nodeos    http_plugin.cpp:696           handle_exception     ] FC Exception encountered while processing chain.push_transaction`

There is no more useful infomation but FC Exception?So how can I fix this problem?

**Comment by matthewdarwin** [comment]
From @heifner 

The "FC Exception encountered while processing chain.push_transaction" is nothing to worry about. 2.0 has diff default logging than 1.8 so you now get this for every failed push_transaction which could be for any reason. For example, the contract had an assert that was tripped, or user ran out of cpu, etc.

**Comment by heifner** [comment]
You can see the reason for the failure by enabling debug level logging on your api node. Here is an example logging.json https://github.com/EOSIO/eos/blob/master/programs/nodeos/logging.json 

If you don't want gelf logging here is one without gelf logging. Rename to `logging.json` and place along side your config.ini file. Or via https://developers.eos.io/manuals/eos/latest/nodeos/logging/setup-logging.json

[logging.json.txt](https://github.com/EOSIO/eos/files/4185957/logging.json.txt)

**Comment by devilrayzl** [comment]
Sorry for late response.Thank you very much.
