### ISSUE TITLE
Redefinition of token error

### ISSUE THREAD

**Issue by AllenBroady** [EOSIO/eos#8629]
I am building a private blockchain for a local net. When I try to deploy the system contract run into the 
following error: 

In file included from /home/allenbroady/eosio.contracts-1.8.x/contracts/eosio.system/src/eosio.system.cpp:12:
In file included from /home/allenbroady/eosio.contracts-1.8.x/contracts/eosio.system/src/voting.cpp:10:
include/eosio.token/eosio.token.hpp:20:45: error: redefinition
      of 'token'
   class [[eosio::contract("eosio.token")]] token : pub...
                                            ^
/home/allenbroady/eosio.contracts-1.8.x/contracts/eosio.system/src/eosio.token.hpp:20:45: note: 
      previous definition is here
   class [[eosio::contract("eosio.token")]] token : pub...

I am having a hard time in determining what the source of this error comes from. Could someone please advise what the problem may be.

**Comment by swang-b1** [comment]
Hi @AllenBroady , 

I can compile eosio.contract release/1.8.x version with cdt version 1.6 without any problem. 

Can you add more information about which version of contract you are trying to compile and which cdt version you are using?

Thanks
