### ISSUE TITLE
Error: Transaction exceeded the current CPU usage limit imposed on the transaction

### ISSUE THREAD

**Issue by cjrada** [EOSIO/eos#8631]
I'm trying to resolve this error: Transaction exceeded the current CPU usage limit imposed on the transaction.
"message":"billed CPU time (291 us) is greater than the maximum billable CPU time for the transaction (13 us)"
"file":"transaction_context.cpp"

I have little CPU and NET in one account, and 0 in the other (a new account).  The issue I'm facing, which I haven't yet found resolved, is that the CPU is too small, yet I can't add CPU, because it's too small.

**Comment by cjrada** [comment]
JSON:
{
"code":400
"message":"Bad Request"
"error":{
"code":3080004
"name":"tx_cpu_usage_exceeded"
"what":"Transaction exceeded the current CPU usage limit imposed on the transaction"
"details":[
0:{
"message":"billed CPU time (291 us) is greater than the maximum billable CPU time for the transaction (13 us)"
"file":"transaction_context.cpp"
"line_number":553
"method":"validate_cpu_usage_to_bill"
}
]
}
}

**Comment by cjrada** [comment]
https://bloks.io/ is raising ERR_CONNECTION_TIMED_OUT errors
https://eoslaomao.com/ is not allowing "replacing deferred transactions"
Another site asked me to pay it before it would lend the CPU for me to pay it ;)
:-)

**Comment by taokayan** [comment]
> I'm trying to resolve this error: Transaction exceeded the current CPU usage limit imposed on the transaction.
> "message":"billed CPU time (291 us) is greater than the maximum billable CPU time for the transaction (13 us)"
> "file":"transaction_context.cpp"
> 
> I have little CPU and NET in one account, and 0 in the other (a new account). The issue I'm facing, which I haven't yet found resolved, is that the CPU is too small, yet I can't add CPU, because it's too small.

you can still delegate CPU resource to your account. Your CPU resource balance will be updated first before cpu billing.

**Comment by cjrada** [comment]
Hi Taokayan,  
Thanks for your response.
So, to confirm that I understand please, I need to move the rest of my eos (on an exchange) to the new wallet (we'll call wallet 2), then delegate from wallet 2 back to wallet 1 (the wallet in question).
Thanks for your help :-)

**Comment by gituser** [comment]
Related issue https://github.com/EOSIO/eos/issues/8502
