### ISSUE TITLE
How can i set field as auto increment in EOS smart contract? 

### ISSUE THREAD

**Issue by rahul1083** [EOSIO/eos#8632]
struct [[eosio::table]] envelope {
    std::string EId;
    std::string ETId;
    std::string TS;
    std::string DV;
    std::string DH;
    uint64_t id;//Auto increment
    uint64_t primary_key() const { return id; }

  };

**Comment by swang-b1** [comment]
Hi,

you can look at this 

https://developers.eos.io/manuals/eosio.cdt/latest/group__multiindex/#function-available_primary_key

there is no auto-increment type in eosio multi_index_table.
