### ISSUE TITLE
Error response from daemon: pull access denied for eosio/eos, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by rahul1083** [EOSIO/eos#8639]
Getting error on  running 'docker pull eosio/eos'
Error response from daemon: pull access denied for eosio/eos, repository does not exist or may require 'docker login'
As mentioned in below web sit
https://www.eosdocs.io/dappdevelopment/software/docker/

**Comment by heifner** [comment]
eosio documentation is here: https://developers.eos.io/
That site appears to be out of date.

**Comment by rahul1083** [comment]
But i am not able see any documentation for EOS node setup using docker

**Comment by heifner** [comment]
Docker containers are no longer provided. We switched to providing binaries instead attached to the release notes:
https://github.com/EOSIO/eos/releases/tag/v2.0.3
