### ISSUE TITLE
On mac running scripts/eosio_build.sh freezes

### ISSUE THREAD

**Issue by shikhars371** [EOSIO/eos#8644]
I am using mac to run 1.8 release , after i cloned 1.8 releaase i tried sudo ./scripts/eosio_build.sh 
this command its throwing me this

Thu Feb 13 15:16:13 UTC 2020
User: root
Current branch: release/1.8.x
No installation location was specified. Please provide the location where EOSIO is installed.
Do you wish to use the default location? /Users/shikhar/eosio/.? (y/n) y

EOSIO will be installed to: /Users/shikhar/eosio/.

and nothing happening. can anyone tell me the reason?

**Comment by spoonincode** [comment]
Can you try running without `sudo`?

**Comment by spoonincode** [comment]
Closing due to no response
