### ISSUE TITLE
Block production documentation

### ISSUE THREAD

**Issue by heifner** [EOSIO/eos#8650]
Behavior as of 1.8.11 & 2.0.2. Earlier versions work differently.

m = max_block_cpu_usage, t = block-time; e = last-block-cpu-effort-percent;
w = block_time_interval = 500ms;
a = produce-block-early-amount = (w - w*e/100)ms;
p = produce-block-time; p = t - a;
c = billed_cpu_in_block = minimum( m, w - a );
n = network tcp/ip latency;
peer validation for similar hardware/eosio-version/config will be <= m;
BP-A <-> BP-A-Peer <-> BP-B-Peer <-> BP-B;
BP-A will send block at p;
BP-B needs block t at time t or it will drop it.

Example: BP-A has 50% e, m = 200ms, c = 200ms, n = 0ms, a = 250ms:
BP-A sends at (t-250ms) <-> BP-A-Peer processes for 200ms and sends at (t - 50ms) <-> BP-B-Peer processes for 200ms and sends at (t + 150ms) = arrive at BP-B 150ms too late.

Example: BP-A has 40% e and m = 200ms, c = 200ms, n = 0ms, a = 300ms:
(t-300ms) <-> (+200ms) <-> (+200ms) = arrive at BP-B 100ms too late.

Example: BP-A has 30% e and m = 200ms, c = 150ms, n = 0ms, a = 350ms:
(t-350ms) <-> (+150ms) <-> (+150ms) = arrive at BP-B with 50ms to spare.

Example: BP-A has 25% e and m = 200ms, c = 125ms, n = 0ms, a = 375ms:
(t-375ms) <-> (+125ms) <-> (+125ms) = arrive at BP-B with 125ms to spare.

Example: BP-A has 10% e and m = 200ms, c = 50ms, n = 0ms, a = 450ms:
(t-450ms) <-> (+50ms) <-> (+50ms) = arrive at BP-B with 350ms to spare.

Example: BP-A has 10% e and m = 200ms, c = 50ms, n = 15ms, a = 450ms:
(t-450ms) <- +15ms -> (+50ms) <- +15ms -> (+50ms) <- +15ms -> BP-B = arrive with 305ms to spare.

Example world-wide network: BP-A has 10% e and m = 200ms, c = 50ms, n = 15ms/250ms, a = 450ms:
(t-450ms) <- +15ms -> (+50ms) <- +250ms -> (+50ms) <- +15ms -> BP-B = arrive with 70ms to spare.

Running wasm-runtime=eos-vm-jit eos-vm-oc-enable on relay node will reduce the validation time.

**Comment by lparisc** [comment]
[docs/01_nodeos/03_plugins/producer_plugin/index.md](https://github.com/EOSIO/eos/tree/release/2.0.x/docs/01_nodeos/03_plugins/producer_plugin/index.md)
[docs/01_nodeos/03_plugins/producer_plugin/10_block-producing-explained.md](https://github.com/EOSIO/eos/tree/release/2.0.x/docs/01_nodeos/03_plugins/producer_plugin/10_block-producing-explained.md)
