### ISSUE TITLE
nodeos does not respond depending on peers

### ISSUE THREAD

**Issue by bsilva122** [EOSIO/eos#8656]
There's an issue with the latest nodeos versions, I can reproduce but I couldn't narrow it down yet. On any machine (from 30gb ram to 64gb to 256gb ram) the same problem happens.

If you put this list of peers https://validate.eosnation.io/eos/reports/config.txt

nodeos goes nuts at 100% cpu only one core and doesn't answer to any http response, takes like 30 seconds to 60 seconds when it works, times out most of the times

However, if you pick just one peer out of that list it works ok. But running with just one peer is not ideal since you can easily get out of sync. If you put 2 peers and those are block producers, nodeos goes bad again. Similar issues happening since 1.8.x, possibly 1.8.2

Please look into this, it's not hardware or bare metal needed, something is wrong with the code. I have tried changing several configs to no use (increasing *threads, reducing max-clients, more memory on chain, etc). Only plugin enabled was chain_plugin and http_plugin, disabled everything else (no history or state-history at all so the problem is not there).

And yes, nodes were in sync. No, it's not a disk io issue. Yes I tried lots of nodeos versions 1.8.6, 1.8.11, 1.8.12. Please try running a nodeos with a recent snapshot from eosnation  https://snapshots.eosnation.io/ and put these peers on your config before replying to this thread with "you need bare metal"

List of peers that can reproduce the issue:

```
# Endpoints config.ini
# Network: EOS
# Validator last update: %last_update% 2020-02-16 21:11 UTC
# For details on how this is generated see https://validate.eosnation.io/about/

# ==== p2p ====

# alohaeosprod: GB, London
p2p-peer-address = peer.main.alohaeos.com:9876

# atticlabeosb: UA, Kyiv
p2p-peer-address = eosbp-0.atticlab.net:9876

# atticlabeosb: UA, Kyiv
p2p-peer-address = eosbp-1.atticlab.net:9876

# eosamsterdam: FI, bnode
p2p-peer-address = mainnet.eosamsterdam.net:9876

# eosdotwikibp: SG, Singapore
p2p-peer-address = p2p.eos.wiki:39876

# eosflareiobp: US, GlobalDAC
p2p-peer-address = p2p.eosflare.io:9876

# eoslaomaocom: US, NewYork
p2p-peer-address = fullnode.eoslaomao.com:443

# eoslaomaocom: US, NewYork
p2p-peer-address = mainnet.eoslaomao.com:443

# eosphereiobp: AU, Sydney
p2p-peer-address = peer1.eosphere.io:9876

# eosswedenorg: SE, Sweden
p2p-peer-address = p2p.eossweden.org:9876

# helloeoscnbp: JP, Tokyo
p2p-peer-address = peer1.mainnet.helloeos.com.cn:80

# okcapitalbp1: JP, Tokyo
p2p-peer-address = eos.okpool.top:9876

# tokenika4eos: PL, Poland
p2p-peer-address = api3.tokenika.io:9876

# tokenika4eos: PL, Poland
p2p-peer-address = eth2.tokenika.io:9876

# whaleex.com: KR, Seoul
p2p-peer-address = p2p-eos.whaleex.com:9876
```

**Comment by matthewdarwin** [comment]
Reduce the number of peers.

If you want to process all incoming transactions on EOS-Mainnet, please use EOSIO 2.0 with EOS-VM or a faster CPU (4.5GHz is probably needed for 1.8 WABT). The volume of transactions is quite high on EOS Mainnet and will only grow.

Additionally change read-mode option if you don't need speculative.

**Comment by bsilva122** [comment]
I can reproduce the same issue with nodeos 2

**Comment by matthewdarwin** [comment]
I am running more than 125 p2p connections on a single nodeos 2.0.3 with EOS-VM enabled (CPU speed 5Ghz).  So it is not a software problem. 

Need more details about your 2.0 configuration.

```
wasm-runtime = eos-vm-jit
eos-vm-oc-enable = true
database-map-mode = locked
read-mode = head
net-threads = 10
```

**Comment by bsilva122** [comment]
Thanks for your help Matthew. That should still be fixed it since this is causing so many problems and it's very hard to figure that out. It should have some decent peer discovery and only use whoever is online and decent latency instead of crapping out when there are too many peers.
