### ISSUE TITLE
public_key_legacy_prefix in version 2.0

### ISSUE THREAD

**Issue by core-chain-io** [EOSIO/eos#8659]
Just installed version 2.0 from master branch.
i changed the CORE_SYMBOL_NAME in CMakeFile then i build with option -s "coresymbolname"

After build and install I change the public_key_legacy_prefix for the public key in file
(eosio/2.0/include/fc/crypto/public_key.hpp)

now a cleos crate key still outputs EOSxxxxxxx
Is there some other location to change this, it worked this way in Version 1.8

**Comment by heifner** [comment]
"EOS" is hardcoded in `libraries/fc/include/fc/crypto/public_key.hpp` and in cleos `main.cpp`.

**Comment by cppfuns** [comment]
It's even better if you can specify it with parameters, otherwise you have to change it yourself every time.

**Comment by core-chain-io** [comment]
right you can specify it during build with option -s name.
But seems for cleos it has to be changed separately.
I found on line 696 in /programms/cleos/main.pp
now building again and test:

authority parse_json_authority_or_key(const std::string& authorityJsonOrFile) {
   if (boost::istarts_with(authorityJsonOrFile, **"EOS"**) || boost::istarts_with(authorityJsonOrFile, "PUB_R1")) {
      try {
         return authority(public_key_type(authorityJsonOrFile));
      } EOS_RETHROW_EXCEPTIONS(public_key_type_exception, "Invalid public key: ${public_key}", ("public_key", authorityJsonOrFile))
   } else {
      auto result = parse_json_authority(authorityJsonOrFile);
      EOS_ASSERT( eosio::chain::validate(result), authority_type_exception, "Authority failed validation! ensure that keys, accounts, and waits are sorted and that the threshold is valid and satisfiable!");
      return result;
   }
}

**Comment by core-chain-io** [comment]
i still get EOSxxxx key pairs.
Any other suggestions where to adjust this?

**Comment by cppfuns** [comment]
> i still get EOSxxxx key pairs.
> Any other suggestions where to adjust this?

https://www.bcskill.com/index.php/archives/717.html

**Comment by spoonincode** [comment]
EOSIO has never supported changing the key prefix via a build option. The `-s` option to the build script never affected this. Hacking the changes in to the mentioned fc & cleos locations will probably work but will likely break unit tests, many downstream projects (eosjs, etc), and maybe other things. This is not a change we can provide assistance with.
