### ISSUE TITLE
DAWN-240 ⁃ Microservice to support the retrieval of a Testnet account name via submission of EOS public key

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#866]
Given an EOS public key, present the user with the matching account name(s).

**Comment by blockone-syncclient** [comment]
➤ Sean Mitchell commented:

This was started earlier today.

**Comment by blockone-syncclient** [comment]
➤ Sean Mitchell commented:

If an account name is hex it's EOS account name is a base32 encoded version of the row number. 

base32.encode( row_num.toString() ).replace(/=/g, "").toLowerCase()

**Comment by jgiszczak** [comment]
`get accounts` now available in `cleos`, or RPC endpoint `get_key_accounts`.  Service provided by `history_api_plugin` and `history_plugin` in `nodeos`.
