### ISSUE TITLE
unable to find "context.control.pending_block_state ()-> block-> block_extensions"

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#8660]
I want to move the random number method of BOS to the EOS 2.0 branch

https://github.com/boscore/ibc_plugin_bos/blob/c89feae30c1de8b8d299ea58368575ef3fa7645a/libraries/chain/wasm_interface.cpp#L1728

But I found that `block_state_ptr pending_block_state () const;` was submitted and deleted by 3299adae9e95b53357cafda852588eb9d87c35ed. How do I get the original `context.control.pending_block_state ()-> block-> block_extensions`?

**Comment by cppfuns** [comment]
And found that `block_header_state` has no `block`

**Comment by cppfuns** [comment]
@arhag I need your help, friend

**Comment by cppfuns** [comment]
If possible, can you fix the `bpsig_action_time_seed` method for me? And will EOS 2.0 add this method, and is this method feasible?

**Comment by cppfuns** [comment]
@heifner  @matthewdarwin  I need your help, friend

**Comment by taokayan** [comment]
I guess you need to put your extra block information into ```block_header_state_common``` and inject those into ```block_extensions``` at the time you finalize the block
