### ISSUE TITLE
Switch cleos from using get_abi to using get_raw_abi

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#8661]
It currently uses `/v1/chain/get_abi`. `/v1/chain/get_raw_abi` uses less resources within nodeos.

**Comment by allenhan2** [comment]
fixes are on branch get_raw_abi. 
Tests (check printed msg):
1. run cleos get abi account
2. run token transfer

**Comment by allenhan2** [comment]
fix by PR #8670
