### ISSUE TITLE
New rpc: /v1/chain/get_block_info

### ISSUE THREAD

**Issue by tbfleming** [EOSIO/eos#8662]
This should behave like `get_block`, but return a smaller subset of data.

e.g. output:

```
{
  "block_num": 12345,
  "id": "00003039C04C45767B191E47A1C77F326AA8FE41AB26B7897036D725CA6D4DFD",
  "timestamp": "2020-02-18T17:46:37.000",
  "producer": "eosio",
  "confirmed": 0,
  "previous": "000030389B1290E805D57D94527C077A94ED0DAE33C91AA62F8FDD488C70A2FD",
  "transaction_mroot": "0000000000000000000000000000000000000000000000000000000000000000",
  "action_mroot": "2B5A5AB9FC4FD220D8928B673A889981144FA88C09AF2E2946737861D1905A91",
  "schedule_version": 0,
  "producer_signature": "SIG_K1_K2CneKYGj6YrYusp9ickseeRF5YGYLincE678zddLteGRd8rpqSWNZijcTws8MkjmXeePSWkA96cBGekWUML2CpgwssaUF",
  "ref_block_prefix": 1383860090
}
```

Also add to cleos.

**Comment by matthewdarwin** [comment]
Nice.

I do hope that going forward when APIs change a new version number is assigned,

And ideally this is /v1/chain/get_block_header/123344 or similar. There is no need to POST for API calls that don't make changes.

**Comment by Velua** [comment]
Any thoughts on implementing GraphQL?

**Comment by tbfleming** [comment]
JSON handling in nodeos is problematic; we hope to eventually get rid of it. GraphQL inside nodeos is even worse. We have considered GraphQL inside history-tools, but that's a long way off if we ever go with it.

**Comment by tbfleming** [comment]
New changes:
* Rename to `get_block_info`
* Add `ref_block_num`; this is a `uint16_t` containing the 16 LSBs of `block_num`

**Comment by tbfleming** [comment]
More new changes:
* instead of `block_num_or_id`, accept a `uint32_t block_num`
