### ISSUE TITLE
Introduce new read-mode to nodeos: api-read-only

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8685]
Enhancement request, as discussed in Mainnet BPs telegram:

Kevin Heifner, [22.02.20 22:11]
Would an option for an api-read-only be useful. read-only in that it would not speculatively execute p2p transactions but would allow for push_transaction? It would only speculatively execute transactions sent to it via api call.

Eric - sw/eden, [22.02.20 22:21]
[In reply to Kevin Heifner]
Ooh, good suggestion.
This would be useful for sure!

Aaron Cox (jesta) — Greymass, [23.02.20 02:54]
[In reply to Kevin Heifner]
Yeah, It'd second that this could be very useful.

**Comment by heifner** [comment]
Note `blk` `p2p-peer-address` option is available in 2.0.

```
  --p2p-peer-address arg                The public endpoint of a peer node to 
                                        connect to. Use multiple 
                                        p2p-peer-address options as needed to 
                                        compose a network.
                                          Syntax: host:port[:<trx>|<blk>]
                                          The optional 'trx' and 'blk' 
                                        indicates to node that only 
                                        transactions 'trx' or blocks 'blk' 
                                        should be sent.  Examples:
                                            p2p.eos.io:9876
                                            p2p.trx.eos.io:9876:trx
                                            p2p.blk.eos.io:9876:blk
```
