### ISSUE TITLE
Add additional CPU/NET usage data to get_account results

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#8708]
## Background and Motivation

The usage of ephemeral EOSIO resources (like CPU and NET) for any given account continuously decreases linearly over time while the resources are not in use. It continues decreasing linearly until either: the resources are used in which case there is a discontinuous jump in usage; or at least one day has passed since the last time the resource was used (in which case it stays flat at zero usage). 

While I said continuously, the lowest granularity of time resolution on the blockchain is determined by the timestamp of the block (the time seen from the perspective of all transactions in a block are the same: the block timestamp). On EOSIO, this means there is a tick at no finer resolution than 500 ms. Nevertheless, it would be infeasible to update the CPU/NET resource usage of every account in the state every 500 ms (i.e. every block). Because only a few accounts' resources will be mutated in any given block, nodeos takes the approach of lazily updating the CPU/NET resources of an account. It tracks the time the resource usage of an account was last updated and what its usage value was at that time of last update. Then whenever the resource usage needs to be accessed in the context of executing transactions, the usage is first updated based on the time of the current block before then doing whatever further mutations are intended (for example add the additional usage of the transaction that is executing).

However, this update of the resource usage of the account to get it to reflect what it should be at the current time is not done when simply querying the resource usage of an account outside of the context of a transaction (e.g. when processing a `/v1/chain/get_account` RPC call). Certainly it would not be acceptable to update the state database as a result of a RPC query call. It could be possible to calculate what the updated usage value would be at the current time (or more appropriately at the timestamp of the current head block), but that is not what nodeos currently does when generating the `net_limit` and `cpu_limit` fields in the results of the `/v1/chain/get_account` RPC call. 

Therefore, any wallets / block explorers / clients that directly use and display the values in the results of the `/v1/chain/get_account` RPC call will present the user with outdated information. This often leads to user confusion where they still think their CPU usage is really high even though they have not used their accounts for days. In reality, if someone hasn't used their account for more than a day, their CPU and NET usage should be exactly 0.

## Change to `/v1/chain/get_account`

The results of `/v1/chain/get_account` (represented by struct `get_account_results` in `chain_plugin`) includes two fields: `net_limit` and `cpu_limit`. In the struct definition, these are currently represented by the `resource_limits::account_resource_limit` type. In the result of the RPC call, the fields `net_limit` and `cpu_limit` will be JSON objects that currently contain three fields: `used`, `available`, and `max`. It is important that we do not make any changes to the result of `/v1/chain/get_account` that changes the presence or even semantics of these three fields in both `net_limit` and `cpu_limit`. However, it is acceptable to add new fields to the JSON objects in the response.

The JSON object values of both `net_limit` and `cpu_limit` fields within the result of `/v1/chain/get_account` should have two new fields added: `last_usage_update_time` and `current_used`. `last_usage_update_time` is the time (represented in same string format as a block timestamp) of the block in which this particular resource of the specified account was last updated. It is possible to determine this by grabbing the `last_ordinal` field of the `usage_accumulator` type for the two resources stored in the `resource_usage_object` for the account and converting that into a `block_timestamp_type` (the `last_ordinal` is simply the `slot` of a `block_timestamp_type`). `current_used` is what the resource usage value should be if it were to be updated as of the current head block time. To determine how the updated usage value is calculated see `resource_limits::resource_limits_manager::update_account_usage` and `resource_limits::usage_accumulator::add` (note that it is not acceptable to call database modifying functions when calculating the updated value in the context of processing a query request).

By providing the `last_usage_update_time` along with the existing `used` in the response, it becomes possible for clients to calculate the instantaneous value of what the real resource usage should be at any moment of time. This could, for example, allow block explorers and wallets to show a live update of an account's decreasing CPU/NET usage in the UI without needing to make frequent `get_account` requests (assuming they were willing to do the math on the client side). For convenience, however, the results will also include the computed updated usage (`current_used`) which is calculated as of the head block time (which is also already included in the results of `/v1/chain/get_account` as the `head_block_time` field). Clients can choose to use the new fields to show more accurate and up-to-date results to users. Or they can use the existing fields to continue showing the old results. Clients that do not update their code shouldn't break and will by default continue to process and display the old results. If updated clients make a request to an old nodeos, they will be able to tell by the absence of the new fields and could resort to using the existing `used` field perhaps with a warning to the user that the information is likely to be out-of-date.

## Changes to cleos

The `cleos get account` sub-command will also need to be updated to reflect the new information that may be included in the results of `/v1/chain/get_account`. Cleos currently prints out the `used` value for both "net bandwidth" and "cpu bandwidth" for a `cleos get account` sub-command. The updated cleos would use the `current_used` value instead, if possible, when printing these `used` values to console; if the RPC response does not include `current_used` (because it is talking to an old nodeos), then cleos should fallback to using the existing `used` field but it should also print in parentheses next to the `used` lines something like `(out-of-date)`.

**Comment by heifner** [comment]
Merged to develop.
