### ISSUE TITLE
rethrow boost::filesystem::resize_file: File too large:

### ISSUE THREAD

**Issue by crow123** [EOSIO/eos#8723]
info  2020-02-29T05:55:27.893 nodeos    chain_plugin.cpp:930          plugin_initialize    ] Using genesis state provided in '/data/eos/genesis.json'
info  2020-02-29T05:55:27.893 nodeos    chain_plugin.cpp:961          plugin_initialize    ] Starting fresh blockchain state using provided genesis state.
warn  2020-02-29T05:55:27.893 nodeos    chain_plugin.cpp:1074         plugin_initialize    ] 13 N5boost10filesystem16filesystem_errorE: boost::filesystem::resize_file: File too large: "/data/eos/eosData/state/shared_memory.bin"
rethrow boost::filesystem::resize_file: File too large: "/data/eos/eosData/state/shared_memory.bin": 
    {"what":"boost::filesystem::resize_file: File too large: \"/data/eos/eosData/state/shared_memory.bin\""}
    nodeos  chain_plugin.cpp:1074 plugin_initialize
error 2020-02-29T05:55:27.893 nodeos    main.cpp:125                  main                 ] 13 N5boost10filesystem16filesystem_errorE: boost::filesystem::resize_file: File too large: "/data/eos/eosData/state/shared_memory.bin"
rethrow boost::filesystem::resize_file: File too large: "/data/eos/eosData/state/shared_memory.bin": 
    {"what":"boost::filesystem::resize_file: File too large: \"/data/eos/eosData/state/shared_memory.bin\""}
    nodeos  chain_plugin.cpp:1074 plugin_initialize

**Comment by heifner** [comment]
Please provide nodeos version, config.ini, and command line args.

**Comment by jgiszczak** [comment]
Also what OS and what filesystem `/data` is.

**Comment by heifner** [comment]
No response from user.
