### ISSUE TITLE
[CI/CD Failure Triage: dbModesTest] Unit Tests : db_modes_test : Terminated

### ISSUE THREAD

**Issue by NorseGaud** [EOSIO/eos#8732]
Results from the EOSIO CI/CD failure bucketing indicate the following test is having problems:

Platforms this is shown on:
macOS 10.15 
macOS 10.14

Details:
---
https://buildkite.com/EOSIO/eosio/builds/20759#bcc9661c-97ee-4aa5-af9e-32a04755df7f
https://buildkite.com/EOSIO/eosio/builds/20819#a4c1efa8-8854-475e-9afb-6f8aad21d279
https://buildkite.com/EOSIO/eosio/builds/20873#ac2eaa23-528b-43c9-91fd-5b3d79aa3adc

52/82 Test #97: db_modes_test ......................................***Failed   40.71 sec

  | /Users/anka/eos/build/tests/db_modes_test.sh: line 45:  2914 Terminated: 15          ( sleep 20; kill -ALRM $MYPID )
  | /Users/anka/eos/build/tests/db_modes_test.sh: line 50:  2968 Terminated: 15          $NODEOS_LAUNCH_PARAMS --http-server-address '' --p2p-listen-endpoint '' "$@" 2> /dev/null

---

**Comment by allenhan2** [comment]
Tried on0both develop and release/2.0.x on MacOS10.15 (on my local desktop) , see test passed on both branch. testing on MacOS10.14 now.

**Comment by allenhan2** [comment]
it could be fixed by this issue. 
https://github.com/EOSIO/eos/pull/7728
