### ISSUE TITLE
error message can't print out correct information 

### ISSUE THREAD

**Issue by swang-b1** [EOSIO/eos#8741]
in the following error message, provided_permissions, auth and provided_keys didn't print out......

Error Details:
transaction declares authority '${auth}', but does not have signatures for it under a provided delay of 0 ms, provided permissions ${provided_permissions}, provided keys ${provided_keys}, and a delay max limit of 3888000000 ms

**Comment by heifner** [comment]
Those are not being expanded in the error message because they are objects which `format_string` is not expanded because minimize was passed to `format_string`. Use `verbose-http-errors` to see them.
