### ISSUE TITLE
{"code":400,"message":"Bad Request","error":{"code":3040005,"name":"expired_tx_exception","what":"Expired Transaction","details":[{"message":"expired transaction c2580aaf5d165e3d6673476d8ca2607f6362212648129ac42bae7367183ab718","file":"producer_plugin.cpp","line_number":471,"method":"process_incoming_transaction_async"}]}}

### ISSUE THREAD

**Issue by crow123** [EOSIO/eos#8764]
headblocktime 2020-03-06T11:17:18
requestbody   {"expiration":"2020-03-06T11:19:18","ref_block_num":108670779,"ref_block_prefix":2949495236,"net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio.token","name":"transfer","authorization":[{"actor":"winbitexeos1","permission":"active"}],"data":"1030555d6577a6e340860898aaaef6de0b0000000000000003454f53000000000474657374"}],"transaction_extensions":[]}

requestParam {"packed_trx":"1030555d6577a6e340860898aaaef6de0b0000000000000003454f53000000000474657374","packed_context_free_data":"","compression":false,"signatures":["SIG_K1_K6BGKeNQPrbvBk3xYxhMDdeBDr8h1SXE78yrxNvr54KPfdWiwUa1t2optX4PcHs3Nu3Msv5oJYsdE1XZnXKBQp9cuhW3gz"]}

why???????

**Comment by cppfuns** [comment]
The transaction has expired. Please note that there is an expiration parameter when initiating a transaction, such as expireSeconds in https://www.bcskill.com/index.php/archives/873.html

**Comment by crow123** [comment]
> The transaction has expired. Please note that there is an expiration parameter when initiating a transaction, such as expireSeconds.
> 
> Removed extraneous references.

I set expireTime add 120 seconds, also as this;

**Comment by heifner** [comment]
It is not clear, are you still having an issue?
