### ISSUE TITLE
History Plugin - Onerror actions are not always recorded with the correct id

### ISSUE THREAD

**Issue by victorj8** [EOSIO/eos#8769]
onerror actions are recorded in the history_plugin with an id that does not allow them to be found via the transaction recorded in a block. Specifically on_action_trace uses at.trx_id which is not the correct id always. So instead of that pass in the transaction id from the trace. This would normally be trace->id  but can be trace->failed_dtrx_trace->id if trace->failed_dtrx_trace exists. See state_history_plugin on_applied_transaction.

**Comment by heifner** [comment]
Related #8772
