### ISSUE TITLE
History plugin problems

### ISSUE THREAD

**Issue by victorj8** [EOSIO/eos#8772]
- History plugin may cause a large amount of memory to be consumed, to mitigate the problem a new API call was proposed with the intent to free some of this memory as needed, a PR was made:

https://github.com/EOSIO/eos/pull/8740 

- Some overflow problems present, originally found by @greymass, a commit with a fix is in:

https://github.com/greymass/eos/commit/e58a0af9199d0474c33987e9622bac218d0fe77c

**Comment by heifner** [comment]
See #8703

**Comment by heifner** [comment]
See #8769

**Comment by matthewdarwin** [comment]
Also see: https://github.com/EOSIO/eos/issues/6377 where history and state-history don't play nice with each other.
