### ISSUE TITLE
Unable to find key assertion error 

### ISSUE THREAD

**Issue by alexy97** [EOSIO/eos#8773]
I am creating a shell script to initialize a local eos chain. I managed to set bios and tokena accounts, as well as issue the token but when I try to transfer it I get "Unable to find key error" even though I am using the default key for all accounts ( as I will just be running test locally). Here is my code https://pastebin.com/eSFMBDRm

**Comment by cppfuns** [comment]
The token symbol you issued is "ET", but the token symbol of the transfer is "EOS" and must be consistent.

www.bcskill.com EOS Chinese blockchain community
