### ISSUE TITLE
How to execute get-account command from browser?

### ISSUE THREAD

**Issue by Gagan0436** [EOSIO/eos#878]
I'm unable to get the expected result when trying to execute the following command.
curl http://myHost:myPort/v1/chain/get_account -X POST -d '{"name":"inita"}' [Refer](https://eosio.github.io/eos/group__eosiorpc.html#v1chaingetaccount)

I am using [Postman](https://www.getpostman.com/) to execute post requests.

Expected Output:
![image](https://user-images.githubusercontent.com/29055755/33659471-5247b1c2-daa6-11e7-8b04-e2c22f517dde.png)

Actual Output:
![image](https://user-images.githubusercontent.com/29055755/33662098-a0f1f9cc-dab0-11e7-8709-ef8324ae48d2.png)

Need Help!

**Comment by nanonano7** [comment]
use "account_name"

**Comment by Gagan0436** [comment]
@nanonano7 I got this in response :/
![image](https://user-images.githubusercontent.com/29055755/33662717-eb03a4aa-dab2-11e7-9741-ca21785ec437.png)

**Comment by nanonano7** [comment]
try http://testnet1.eos.io:80/v1/chain/get_account 
if that works then your local eosd node is probably not set up correctly

**Comment by Gagan0436** [comment]
@nanonano7  I ran this in my browser and got same error.
![image](https://user-images.githubusercontent.com/29055755/33663130-bad9fa70-dab4-11e7-9403-5a1863717cec.png)

**Comment by nanonano7** [comment]
you have post JSON to it

**Comment by Gagan0436** [comment]
@nanonano7 For http://testnet1.eos.io:80/v1/chain/get_account i have tried both ways - with and without params. In both cases i got same error. I am attaching the screen shot where I added params.

![image](https://user-images.githubusercontent.com/29055755/33665998-a264a418-dabe-11e7-99fd-6d8a07819e8a.png)
Response:
![image](https://user-images.githubusercontent.com/29055755/33666028-b9a54506-dabe-11e7-9481-debdbeb2c3b8.png)

**Comment by nanonano7** [comment]
use {"account_name":"inita"} not name

**Comment by Gagan0436** [comment]
Omg! Thanks a lot! It Worked! 💃

**Comment by heifner** [comment]
Thanks @nanonano7.

**Comment by heifner** [comment]
@Gagan0436 Please use telegram `EOS Single Threaded` or `EOS Developers` for questions/support. We want to keep GitHub issues as clean as possible.

**Comment by Gagan0436** [comment]
@heifner Sure. Thank you for sharing. :)

**Comment by Gagan0436** [comment]
@nanonano7 Hi can you please have a look into this [issue](https://github.com/nathanhourt/eosio-sdk/issues/1)
Any help will be appreciated!
Thanks!

**Comment by gittempo** [comment]
how did you get account_name inita?

what api is used to create account_name? Account_Name or wallet names are different?

i tried get_account API with wallet name but it gives me this error



> {
    "code": 500,
    "message": "Internal Service Error",
    "error": {
        "code": 3010001,
        "name": "name_type_exception",
        "what": "Invalid name",
        "details": [
            {
                "message": "Name not properly normalized (name: test-wallet99, normalized: test.wallet) ",
                "file": "name.cpp",
                "line_number": 15,
                "method": "set"
            }
        ]
    }
}

**Comment by nanonano7** [comment]
hyphens are not allowed in account names.
Also just to clarify.
Wallets are just software to manage your account/keys.

**Comment by razliveyatan** [comment]
gittempo,
EOS has "regulations" regarding naming account names:
 "Name should be less than 13 characters and only contains the following symbol .12345abcdefghijklmnopqrstuvwxyz."

Hope this helps
