### ISSUE TITLE
DAWN-266 ⁃ implement remaining "to do" sync-reassignment function

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#879]
this has a performance impact.

The function is called when a sync-block provider times out or disconnects while providing a chunk of blocks. now that syncing no longer retrieves multiple chunks in parallel, this is a simpler problem to solve, but it has to be done.
now all the sync_manager object has to do is nominate another peer to continue the fetch from.

**Comment by blockone-syncclient** [comment]
➤ Phil Mesnier commented:

This issue is obsolete. the synchronization functionality of the p2p infrastructure is quite a bit simpler now, connections no longer try to cache chunks of blocks for later assembly.

**Comment by pmesnier** [comment]
Overtaken By Events
