### ISSUE TITLE
STAT-263 ⁃ Create a configurable "Fetch" parameter

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#881]
Create a configurable "Fetch" parameter so that a user can change the fetch size (increase it / decrease it) so that starting up eosd can be tuned

ATC -
add "sync-fetch-span = 10" to the config.ini file.
start the local eosd instance with --resync. Note in the console output that a certain amount of time is taken to load spans of 10000 blocks. For example on my laptop at work it takes about 90 seconds to load 10000 blocks.
Next change the sync-fetch-span = 100" terminate and restart your eosd instance ands Observe that it takes less time to retrieve 10000 blocks.

**Comment by heifner** [comment]
Resolved by #882

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

ATC Pass

With sync-fetch-span 10, it takes around 4 mins to reach 10000 blocks

While with sync-fetch-span 100, it takes around 45 secs to reach 10000
