### ISSUE TITLE
unapplied_transactions has been deleted

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#8810]
I was referring to the IBC solution of BOS and found that the unapplied_transactions needed by the IBC plugin was deleted. I wanted to ask why it was deleted and whether the IBC plugin is necessary to use this data.

https://github.com/boscore/ibc_plugin_eos/blob/48530532f79585c5632de7a4113fdc6bdbf154a3/libraries/chain/controller.cpp#L2218
```
void controller::drop_all_unapplied_transactions() {
   my->unapplied_transactions.clear();
}
```
https://github.com/boscore/ibc_plugin_eos/blob/48530532f79585c5632de7a4113fdc6bdbf154a3/plugins/ibc_plugin/ibc_plugin.cpp#L3801

```
chain_plug->chain().drop_all_unapplied_transactions();
```

https://github.com/EOSIO/eos/commit/ca534067c85285c3ffe9c9159cc8e464ce5ece97

@heifner

**Comment by heifner** [comment]
You would need to ask BOS about their IBC plugin. unapplied  transactions are still a concept in eosio. See https://github.com/EOSIO/eos/blob/develop/libraries/chain/include/eosio/chain/unapplied_transaction_queue.hpp and its use.
