### ISSUE TITLE
cant get_block return 500.

### ISSUE THREAD

**Issue by atoken-ops** [EOSIO/eos#8839]
nodeos version 2.0.4.
the ec2 config:
4C Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz
32GB
SSD

use 
r = requests.post("http://ip:8888/v1/chain/get_block", timeout=30, headers={},
                                                   json={"block_num_or_id": 110730505})

http api return 500.

the node log:
error 2020-03-18T06:07:14.665 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:14.746 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:14.762 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:14.778 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:14.807 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:14.828 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:14.916 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:14.932 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:15.013 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:15.028 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:15.044 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:15.060 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:15.082 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:15.167 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:15.185 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:15.270 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:15.286 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:15.301 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block
error 2020-03-18T06:07:15.317 nodeos    http_plugin.cpp:727           handle_exception     ] FC Exception encountered while processing chain.get_block

how config the config.ini

**Comment by heifner** [comment]
Likely you need to increase `http-max-reponse-time-ms`

**Comment by atoken-ops** [comment]
# Maximum time for processing a request. (eosio::http_plugin)
http-max-response-time-ms = 60000

thie config already configed

**Comment by heifner** [comment]
Enable `debug` level logging to get more info.
https://github.com/EOSIO/eos/blob/master/programs/nodeos/logging.json

**Comment by heifner** [comment]
Might also need to increase `abi-serializer-max-time-ms`

**Comment by atoken-ops** [comment]
> Might also need to increase `abi-serializer-max-time-ms`

change this is ok.tks
