### ISSUE TITLE
how open the history api about nodeos v2.0.4 

### ISSUE THREAD

**Issue by atoken-ops** [EOSIO/eos#8849]
how open the history api about nodeos v2.0.4

**Comment by heifner** [comment]
I'm sorry it is not clear what this means.

**Comment by atoken-ops** [comment]
/v1/history/get_key_accounts
Which api replaces the above interface。
What nodes need to do。
nodeos v 2.0.4

**Comment by heifner** [comment]
There is no provided replacement for that api currently.
