### ISSUE TITLE
cleos get info still not speedy on 2.0.4 while catching up blocks from a snapshot

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8850]
There were improvements in 2.0.4 to make "get info" return faster in more cases.  There are still times where it takes a long time.

I have two different test cases where starting from a 1 day old snapshot and then trying to run "get info":

Common:

EOS Mainnet
CPU speed = 5Ghz
version 2.0.4
nodeos CPU 100%
sync-fetch-span = 2500
~20 p2p connections

test 1) eos-trxrly

wasm-runtime = wabt
read-mode = speculative

test 2) eos-blkrly

wasm-runtime = eos-vm-jit
eos-vm-oc-enable = true
read-mode = read-only

Test script:

while [ 1 ]
do
date
cleos get info > /dev/null
done

Results:

[results-blkrly.txt](https://github.com/EOSIO/eos/files/4360082/results-blkrly.txt)
[results-trxrly.txt](https://github.com/EOSIO/eos/files/4360083/results-trxrly.txt)

Summary:

It can take more than 4 minutes to get a response.  Read-only mode works better then speculative.

**Comment by heifner** [comment]
Resolved by #8894
