### ISSUE TITLE
When I want to use the snapshot to synchronize to the latest block, the data is always at the initial height of the snapshot and cannot be synchronized

### ISSUE THREAD

**Issue by sbihgud** [EOSIO/eos#8863]
Node version: v1.8.7

P2P address is updated

The following is a screenshot of the synchronization log:

![image](https://user-images.githubusercontent.com/20178448/77494355-808fd300-6e80-11ea-9625-bf84416e6580.png)

why？

**Comment by heifner** [comment]
It is hard to tell without seeing more of the log and possibly enabling debug level logging. Do you only have the two eoshubipool.com peers? If so it looks like those two peers are not accepting any more connections.
