### ISSUE TITLE
rpc get block info error

### ISSUE THREAD

**Issue by 1036225283** [EOSIO/eos#8866]
{"code":500,"message":"Internal Service Error","error":{"code":2,"name":"timeout_exception","what":"deadline 2020-02-20T04:02:21.564 exceeded by 21us ","details":[{"message":"deadline 2020-02-20T04:02:21.564 exceeded by 21us ","file":"json.cpp","line_number":499,"method":"escape_string"}]}}

**Comment by heifner** [comment]
The `timeout_exception`  with that error message is an indication that you exceeded the configured `http-max-response-time-ms` of nodeos during the conversion to json of your rpc call.
