### ISSUE TITLE
Update the copyright years in the repo license file

### ISSUE THREAD

**Issue by bobgt** [EOSIO/eos#8867]
The copyright years in the repo license file is current showing **Copyright (c) `2017-2019 `block.one and its contributors.**

This needs to be updated to reflected the current 2020 year. 

Suggested action:
Bump the year to reflect the current year. 
**Copyright (c) `2017-2020` block.one and its contributors.**

**Comment by lparisc** [comment]
The license file was already updated in commit 9822532374de27dc135c54426f9a27c9f2f2e2c2
