### ISSUE TITLE
Nodeos rejects sync request from the other nodeos being started with the same snapshot

### ISSUE THREAD

**Issue by allenhan2** [EOSIO/eos#8887]
Both nodeoses are started with the same snapshot, the primary was started about 12hours earlier and synced with mainnet, then secondary started with the same snapshot and tried to sync with the primary (w/o syncing with mainnet). The secondary receives the error messages like below:
info  2020-03-26T15:09:09.386 thread-10 net_plugin.cpp:1474           operator()           ] requesting range 111866391 to 111868890, from 127.0.0.1:10076
info  2020-03-26T15:09:09.387 thread-10 net_plugin.cpp:1588           recv_handshake       ] handshake from 127.0.0.1:10066 - ab3770b, lib 112197911, head 112198241, head id 377e2341a4acb9b8.. sync 1
warn  2020-03-26T15:09:09.387 thread-10 net_plugin.cpp:2663           handle_message       ] ["127.0.0.1:10066 - ab3770b" 127.0.0.1:10076]received go_away_message, reason = some other non-fatal condition, possibly unknown block
error 2020-03-26T15:09:09.387 thread-10 net_plugin.cpp:1455           request_next_chunk   ] Unable to continue syncing at this time

Branch is "release/2.0.x", (pulled the latest commit, ffa8190b5391985d7f9fc00dfd5a1803db74f069)
The primary nodoes is a release build,  the same error msg for both release and debug version of secondary nodeos.
snapshot :
snapshot-06aaf216455bd0b4090c7e8211f4de09e0a2cd9238ef3ad2b0d66bfc1d930d38.bin on https://snapshots-main.eossweden.org/

The syncing is fine after the secondary uses a newer version of snapshot.

**Comment by heifner** [comment]
Lets add an integration test that tests this.

**Comment by heifner** [comment]
Fixed in #8889

**Comment by kobrien** [comment]
Currently deploying from 2.0.6 and I think I might be seeing this error?

`info  2020-07-10T12:52:58.379 net-1     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 16/16
info  2020-07-10T12:52:58.379 net-0     net_plugin.cpp:2141           operator()           ] host: mars.peer.eosbixin.com port: 643
info  2020-07-10T12:52:58.592 net-1     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to mars.peer.eosbixin.com:643, lib 128732200, head 128732530, id 2301b7baaad3d567
info  2020-07-10T12:52:58.784 net-1     net_plugin.cpp:1545           start_sync           ] Catching up with chain, our last req is 128732576, theirs is 130485987 peer mars.peer.eosbixin.com:643
info  2020-07-10T12:52:58.784 net-1     net_plugin.cpp:1412           request_next_chunk   ] ignoring request, head is 128732531 last req = 128732576 source is 54.254.162.219:9878 - 696b3cb
info  2020-07-10T12:52:58.784 net-1     net_plugin.cpp:1605           recv_handshake       ] handshake from eosmainnode:443 - 158352a, lib 130485987, head 130486321, head id 2aa24e382ab383d1.. sync 1
warn  2020-07-10T12:52:58.785 net-1     net_plugin.cpp:2673           handle_message       ] ["eosmainnode:443 - 158352a" 18.141.14.217:643]**received go_away_message, reason = some other non-fatal condition, possibly unknown block**
info  2020-07-10T12:52:58.785 net-1     net_plugin.cpp:943            _close               ] closing 'mars.peer.eosbixin.com:643', mars.peer.eosbixin.com:643`


**startup logs**

info  2020-07-09T19:24:38.089 nodeos    main.cpp:106                  main                 ] nodeos version v2.0.6 v2.0.6-c6a7ec0dd816f98a6840f59dca9fed04efd9f7a5
info  2020-07-09T19:24:38.089 nodeos    main.cpp:107                  main                 ] nodeos using configuration file /root/config/config.ini
info  2020-07-09T19:24:38.089 nodeos    main.cpp:108                  main                 ] nodeos data directory is /root/data
info  2020-07-09T19:24:38.089 nodeos    controller.cpp:541            startup              ] Starting initialization from snapshot, this may take a significant amount of time
info  2020-07-09T19:28:18.864 nodeos    controller.cpp:555            startup              ] database initialized with hash: 44463e63f8f8b3ad22fb9334de93ca28364f70f4e77c85dd8548102d7adb5140
info  2020-07-09T19:28:18.864 nodeos    controller.cpp:483            replay               ] existing block log, attempting to replay from 128608416 to 128710075 blocks
info  2020-07-09T19:28:19.200 nodeos    state_history_plugin.c:489    store_chain_state    ] Placing initial state in block 128608416
info  2020-07-09T19:31:56.232 nodeos    controller.cpp:488            replay               ] 128608500 of 128710075

**Current configuration:** 

plugin = eosio::chain_api_plugin
plugin = eosio::http_plugin
http-server-address = 0.0.0.0:8888
http-validate-host = false
plugin = eosio::chain_plugin
plugin = eosio::net_api_plugin
plugin = eosio::history_api_plugin
plugin = eosio::trace_api_plugin
trace-no-abis=true
trace-history=true
# # snapshot=/root/data/snapshots/snapshot-2020-07-07-04-eos@0129904079.bin
# replay-blockchain
#
plugin = eosio::db_size_api_plugin
plugin = eosio::state_history_plugin
chain-state-db-size-mb = 65536
chain-state-db-guard-size-mb = 200

chain-state-history=true
state-history-endpoint = 0.0.0.0:8080

# Peers list
p2p-peer-address=peer.main.alohaeos.com:9876
p2p-peer-address=eosbp-0.atticlab.net:9876
p2p-peer-address=api.binance-eos.com:9875
p2p-peer-address=p2p.eosio.cr:9876
p2p-peer-address=p2p.eos.cryptolions.io:9876
p2p-peer-address=mainnet.eosamsterdam.net:9876
p2p-peer-address=mainnet.eosarabia.net:3571
p2p-peer-address=mars.peer.eosbixin.com:643
p2p-peer-address=p2p.eosflare.io:9876
p2p-peer-address=p2p.bitmars.one:8080
p2p-peer-address=peer.eosn.io:9876
p2p-peer-address=peer1.eosphere.io:9876
p2p-peer-address=p2p.eossweden.org:9876
p2p-peer-address=eos.okpool.top:9876
p2p-peer-address=eos-p2p.slowmist.io:9878
p2p-peer-address=publicnode.cypherglass.com:9876

**Comment by matthewdarwin** [comment]
Probably this is not the same issue. Suggest opening a new issue after verifying the peer you are trying to connect to actually has the block you are requesting and are not otherwise rejecting yoru connection.  Not all public p2p endpoints have full history and/or capacity.

Known to be working p2p endpoints for EOS Mainnet are listed here: https://validate.eosnation.io/eos/reports/config.html (updated every 30 minutes)

BTW, you don't need so many peers.  Reduce the list to just a few that are working.

**Comment by kobrien** [comment]
thanks @matthewdarwin , I upgraded to v2.0.7 and also added the following 2 lines, not seeing any error messages now
p2p-max-nodes-per-host = 100
p2p-server-address = <my ip>:9877
