### ISSUE TITLE
99% tests passed, 17 tests failed out of 2612

### ISSUE THREAD

**Issue by gzliudan** [EOSIO/eos#8902]
I build a single EOS node according to: https://developers.eos.io/manuals/eos/latest/install/build-from-source/manual-build/platforms/ubuntu-18.04-unpinned .  My test enviroment is ubuntu 18.04.4, clang 8.0, cmake 3.17.0, boost 1.72.0, mongodb 4.2.5, mongo c driver 1.16.2, mongo cxx driver (git clone from https://github.com/mongodb/mongo-cxx-driver.git) in virtual machine with 16G memory. After I tested EOSIO, some tests failed, below is the summary, and log files under ~/eosio/eos/build/Testing/Temporary.

99% tests passed, 17 tests failed out of 2612

Label Time Summary:
long_running_tests         = 1267.51 sec*proc (11 tests)
nonparallelizable_tests    = 265.00 sec*proc (13 tests)
wasm_spec_tests            = 13389.44 sec*proc (2480 tests)

Total Test time (real) = 15866.77 sec

The following tests FAILED:
        107 - nodeos_run_test (Failed)
        108 - block_log_util_test (Failed)
        110 - nodeos_run_test-mongodb (Failed)
        111 - producer-preactivate-feature-test (Failed)
        112 - nodeos_protocol_feature_test (Failed)
        113 - distributed-transactions-test (Failed)
        114 - restart-scenarios-test-resync (Failed)
        115 - restart-scenarios-test-hard_replay (Failed)
        116 - restart-scenarios-test-none (Failed)
        118 - launcher_test (Failed)
        123 - nodeos_run_check_lr_test (Failed)
        124 - nodeos_remote_lr_test (Failed)
        125 - nodeos_forked_chain_lr_test (Failed)
        126 - nodeos_voting_lr_test (Failed)
        127 - nodeos_under_min_avail_ram_lr_test (Failed)
        128 - nodeos_irreversible_mode_lr_test (Failed)
        129 - nodeos_chainbase_allocation_lr_test (Failed)
Errors while running CTest
Makefile:135: recipe for target 'test' failed
make: *** [test] Error 8

[LastTestsFailed.log](https://github.com/EOSIO/eos/files/4418345/LastTestsFailed.log)
[CTestCostData.txt](https://github.com/EOSIO/eos/files/4418348/CTestCostData.txt)
[LastTest.log.tar.gz](https://github.com/EOSIO/eos/files/4418349/LastTest.log.tar.gz)

**Comment by heifner** [comment]
Make sure you did a Release build and not a Debug build.
A quick glance in your log I see many errors like:

`Failed with error: deadline 2020-04-01T11:55:19.868 exceeded by 76us  (2)
deadline 2020-04-01T11:55:19.868 exceeded by 76us `

So either you have a debug build OR your machine is just too slow.

**Comment by gzliudan** [comment]
I encounter similar error when publish eosio.system:

cleos set contract eosio ~/eosio/eosio.contracts/build/contracts/eosio.system -p eosio
Reading WASM from /home/liudan/eosio/eosio.contracts/build/contracts/eosio.system/eosio.system.wasm...
Publishing contract...
error 2020-04-03T12:44:48.012 cleos     main.cpp:4013                 main                 ] Failed with error: deadline 2020-04-03T12:44:47.999 exceeded by 92us  (2)
deadline 2020-04-03T12:44:47.999 exceeded by 92us

**Comment by heifner** [comment]
Which is also an indication that you have a debug build or your machine is just too slow.

**Comment by heifner** [comment]
See if you have:
`CMAKE_BUILD_TYPE:STRING=Debug`
in your `CMakeCache.txt` file.

**Comment by gzliudan** [comment]
for FILE in `locate CMakeCache.txt`; do grep -i -H -n "CMAKE_BUILD_TYPE" $FILE ; done

Below is result, not found STRING=Debug

/home/liudan/eosio/eos/build/CMakeCache.txt:82:CMAKE_BUILD_TYPE:STRING=Release
/home/liudan/eosio/eosio.contracts/build/CMakeCache.txt:28:CMAKE_BUILD_TYPE:STRING=
/home/liudan/eosio/eosio.contracts/build/contracts/CMakeCache.txt:25:CMAKE_BUILD_TYPE:STRING=
/home/liudan/eosio/eosio.contracts/build/tests/CMakeCache.txt:91:CMAKE_BUILD_TYPE:STRING=
/home/liudan/eosio/install/cmake-3.17.0/CMakeCache.txt:42:CMAKE_BUILD_TYPE:STRING=Release
/home/liudan/eosio/install/cmake-3.17.0/Source/Checks/Curses-build/CMakeCache.txt:19:CMAKE_BUILD_TYPE:STRING=
/home/liudan/eosio/install/cmake-3.17.0/Tests/CMakeFiles/CheckFortran/CMakeCache.txt:29:CMAKE_BUILD_TYPE:STRING=
/home/liudan/eosio/install/mongo-c-driver-1.16.2/build/CMakeCache.txt:31:CMAKE_BUILD_TYPE:STRING=Release
/home/liudan/eosio/install/mongo-cxx-driver/build/CMakeCache.txt:62:CMAKE_BUILD_TYPE:STRING=Release
/home/liudan/eosio/install/mongo-cxx-driver/build/src/bsoncxx/third_party/EP_mnmlstc_core-prefix/src/EP_mnmlstc_core-build/CMakeCache.txt:37:CMAKE_BUILD_TYPE:STRING=Release
/home/liudan/eosio/install/mongo-cxx-driver-r3.4.0/build/CMakeCache.txt:52:CMAKE_BUILD_TYPE:STRING=Release
/home/liudan/eosio/install/mongo-cxx-driver-r3.4.0/build/src/bsoncxx/third_party/EP_mnmlstc_core-prefix/src/EP_mnmlstc_core-build/CMakeCache.txt:37:CMAKE_BUILD_TYPE:STRING=Release
/home/liudan/eosio.contracts/build/CMakeCache.txt:28:CMAKE_BUILD_TYPE:STRING=
/home/liudan/eosio.contracts/build/contracts/CMakeCache.txt:25:CMAKE_BUILD_TYPE:STRING=
/home/liudan/eosio.contracts/build/tests/CMakeCache.txt:91:CMAKE_BUILD_TYPE:STRING=

**Comment by heifner** [comment]
What are the cpu specs for this machine? Is it a VM?

**Comment by gzliudan** [comment]
My computer is i7-8750H (6 cores, 12 threads), 32G memory, 512G SSD(KXG50ZNV512G TOSHIBA),  Windows 10 and virtualbox 6.1,4. I created a VM with 6 vCPU 16G memory in virtualbox.

**Comment by gzliudan** [comment]
I use pre-build binary package to publish esio.system contract according to the guide of https://developers.eos.io/welcome/latest/tutorials/bios-boot-sequence , when I run:
cleos set contract eosio EOSIO_OLD_CONTRACTS_DIRECTORY/eosio.system/
this command also report same error：
Reading WASM from /home/liudan/eosio.contracts-1.8.x/build/contracts/eosio.system/eosio.system.wasm...
Publishing contract...
error 2020-04-04T09:22:49.373 cleos     main.cpp:4013                 main                 ] Failed with error: deadline 2020-04-04T09:22:49.369 exceeded by 74us  (2)
deadline 2020-04-04T09:22:49.369 exceeded by 74us

![61b36b0a-722f-4d25-b9d2-a474097e3372](https://user-images.githubusercontent.com/7695325/78423615-0b02de80-769a-11ea-96da-adcf37771bd5.png)

**Comment by gzliudan** [comment]
Maybe this is my computer's VM performance problem. I open a new VM with 8 vCPU 16G memory on cloud, installed pre-build packate as today, then run command, the result becomes OK. I will test this problem again build packate from source code.

cleos set contract eosio $EOSIO_CONTRACTS_DIRECTORY/eosio.system
Reading WASM from /home/ubuntu/eosio.contracts/build/contracts/eosio.system/eosio.system.wasm...
Publishing contract...
executed transaction: 30612278981016e4f9c453f89538da6176218df1633d7586b990b7f2c5004f92  87792 bytes  24970 us
#         eosio <= eosio::setcode               {"account":"eosio","vmtype":0,"vmversion":0,"code":"0061736d0100000001cf034160000060047f7f7f7f006003...
#         eosio <= eosio::setabi                {"account":"eosio","abi":"0e656f73696f3a3a6162692f312e310117626c6f636b5f7369676e696e675f617574686f72...
warning: transaction executed locally, but may not be confirmed by the network yet         ]

**Comment by heifner** [comment]
Does seem like an issue with your VM. Your specs look like they should be fine. I use VMWare all the time without issue.

**Comment by gzliudan** [comment]
Is there a hardware specifications required by EOS?

**Comment by heifner** [comment]
There are no specific hardware requirements because it varies via use.

**Comment by gzliudan** [comment]
I use my computer for software development and test based on EOS.

**Comment by heifner** [comment]
Right, but do you need to interact with EOS Mainnet, or Jungle Testnet, or Telos, or private chain. If private chain then what are all the configuration values, etc. etc.

**Comment by heifner** [comment]
All that being said it seems like your specs should be adequate. So I think you are correct that it is likely an issue with your VM.

**Comment by gzliudan** [comment]
According to https://stackoverflow.com/questions/58687159/poor-performance-of-virtualbox-under-win10 , I changed my virtualbox's VM setting. Now the eosio.system contract can be published OK, no matter the program is binary packate or is build from srouce codes. And some unitests disappeared which failed before, but some still fails. I will post new test result and log files to you later.

**Comment by gzliudan** [comment]
The result is out, only 3 failed:
99% tests passed, 3 tests failed out of 2612

Label Time Summary:
long_running_tests         = 3917.37 sec*proc (11 tests)
nonparallelizable_tests    = 795.73 sec*proc (13 tests)
wasm_spec_tests            = 13017.53 sec*proc (2480 tests)

Total Test time (real) = 18585.50 sec

The following tests FAILED:
	110 - nodeos_run_test-mongodb (Failed)
	112 - nodeos_protocol_feature_test (Failed)
	129 - nodeos_chainbase_allocation_lr_test (Failed)
Errors while running CTest
Makefile:135: recipe for target 'test' failed

[LastTestsFailed.log](https://github.com/EOSIO/eos/files/4432737/LastTestsFailed.log)
[CTestCostData.txt](https://github.com/EOSIO/eos/files/4432739/CTestCostData.txt)
[LastTest.log.tar.gz](https://github.com/EOSIO/eos/files/4432740/LastTest.log.tar.gz)
