### ISSUE TITLE
Split the block.log file in chunks

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8909]
The new (2.0.4) trace API generates multiple files splitting into chunks as it goes.  This way old history can be removed easily if no longer needed.

blocks.log should work the same.

When this feature is available, there should be a way to split up the existing block log into chunks without replaying the entire chain from scratch.  (downtime is acceptable during the splitting process).

**Comment by matthewdarwin** [comment]
A good starting point would be to make `eosio-blocklog` tool be able to chunk a blocks log into smaller pieces.  And also let you reassemble them.

Makes for easier backups.

**Comment by sanaraufx** [comment]
Did the log management changes in 2.1 meet the need you expressed here?

**Comment by matthewdarwin** [comment]
I think the remaining features required are covered in the following issues, so can close this one:

https://github.com/EOSIO/eos/issues/9243
https://github.com/EOSIO/eos/issues/9823
