### ISSUE TITLE
RPC stopped responding after catching the latest head block

### ISSUE THREAD

**Issue by vjoke** [EOSIO/eos#8910]
Below are the command line arguments.
nodeos version is 1.8.12
`
nodeos --data-dir /data/eosio-8888 --http-validate-host false --chain-state-db-size-mb 10240 --plugin eosio::net_api_plugin --plugin eosio::history_api_plugin --plugin eosio::net_plugin --plugin eosio::producer_plugin --plugin eosio::db_size_api_plugin --plugin eosio::chain_api_plugin --abi-serializer-max-time-ms=30000 --plugin eosio::http_plugin --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --validation-mode light --wasm-runtime wabt --p2p-peer-address --p2p-peer-address publicnode.cypherglass.com:9876 --p2p-peer-address peering.mainnet.eoscanada.com:9876 --p2p-peer-address p2p.eosargentina.io:5222 --p2p-peer-address bp.eos.vote:9876 --p2p-peer-address p2p.genereos.io:9876 >/www/eos-api/logs/nodeos.log 2>&1 &
`

**Comment by heifner** [comment]
Can you provide your `nodeos.log`
