### ISSUE TITLE
system list producer showing only one producer

### ISSUE THREAD

**Issue by shikhars371** [EOSIO/eos#8914]
Hello,

I have started the genesis node , and then started several producer node,

when i am doing system list producers on genesis node its showing only one genesis node producer account, why its not showing other producer node account which are running on different servers?

Secondly i tried to run 
cleos -u http://127.0.0.1:8888 system regproducer seltos EOS6eDiAXXXXXXXX
above command on one of my producer node and it gave me the error

Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '${auth}', but does not have signatures for it.

Although i can see all three keys owners,active,producer when i do close wallet keys on producer node

What can be the error? please help me in producer node please

**Comment by jgiszczak** [comment]
`system listproducers` will show only the genesis producer account until `system regproducer` works.  Was the account `seltos` successfully created?  If so, what command are you using to verify its keys and what is the output?

**Comment by heifner** [comment]
Closing no response in 7 days.
