### ISSUE TITLE
Boost v1.71.0 required for eos release v1.8.13

### ISSUE THREAD

**Issue by fiocasey** [EOSIO/eos#8915]
Due to recent updates to `xcode-select`, llvm and boost and failing to build during `eosio_build.sh` after `eosio_uninstall.sh`. This forces the hotfix of 1.8.13 required to support current Darwin setups. 

Change required:
https://github.com/EOSIO/eos/blob/v1.8.13/scripts/.build_vars  

Line 33: `export BOOST_VERSION_MINOR=71`

**Comment by revl** [comment]
@dapixcasey, to eliminate the chance of breaking binary compatibility with existing chainbases, we'll stick with boost 1.70 for 1.8 series.

**Comment by dapixcasey** [comment]
Looks like another change is needed to run 1.8.x on current mac builds:

`export LLVM_VERSION=release_80`
