### ISSUE TITLE
[Build] pkg-config cannot see libcurl

### ISSUE THREAD

**Issue by b1aafulei** [EOSIO/eos#8919]
I would like to report a problem that I met and solved (but not quite sure about why) when running the build script.

Environment
------------
This problem is reproducible both on the master branch (commit `b39b6bd3c74ff47fc53fa80aafa2c1941ba82879`) and the develop branch (commit `2ca063812e26273a8b1cb613dc20708d16ffdf3e`).

My OS is macOS Catalina `10.15.4 (19E266)`.

Problem
--------
The `scripts/eosio_build.sh` would stop with error

```
-- Checking for one of the modules 'libcurl'
CMake Error at /usr/local/Cellar/cmake/3.17.0_1/share/cmake/Modules/FindPkgConfig.cmake:711 (message):
  None of the required 'libcurl' found
Call Stack (most recent call first):
  libraries/yubihsm/CMakeLists.txt:167 (pkg_search_module)
```

How to Fix it Manually
----------------------
This problem can be overcome by manually setting

```
export PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
```

Note that in `/usr/local/opt/curl/lib/pkgconfig` there is a file `libcurl.pc`.

Analysis
--------
The strange thing is that I already have `curl` installed (always), and never met this problem before when running the build script, and I believe pkg-config should be able to see `libcurl` even before my manual export.

Running

```
pkg-config --variable pc_path pkg-config
```

will return 

```
/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14
```

Note that in `/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14` there is already a file `libcurl.pc`. I don't know why pkg-config fails to see it.

Request
--------
Please investigate this issue. If that's not a specific problem on my machine, and if the build script could guide the pkg-config to see the `libcurl`, that would be great.

**Comment by jgiszczak** [comment]
This was a transitory problem with Homebrew which has been fixed by that team.  See Homebrew/brew#5068 for details.  You should be able to simply execute the build script again and allow brew to update packages and the build will proceed.
