### ISSUE TITLE
Snapshot can only be used to initialize an empty database.

### ISSUE THREAD

**Issue by phewitt** [EOSIO/eos#8926]
I'm currently trying to replay from snapshot inside a docker container with an attached volume. On fresh run everything seems to work and I sync up after 1-2 days. However, if the container rolls over at any point for any reason I get this message.

```
warn  2020-04-08T21:09:18.280 nodeos    chain_plugin.cpp:1093         plugin_initialize    ] 3110006 plugin_config_exception: Incorrect plugin configuration
Snapshot can only be used to initialize an empty database.
    {}
    nodeos  chain_plugin.cpp:862 plugin_initialize
error 2020-04-08T21:09:18.280 nodeos    main.cpp:125                  main                 ] 3110006 plugin_config_exception: Incorrect plugin configuration
Snapshot can only be used to initialize an empty database.
    {}
    nodeos  chain_plugin.cpp:862 plugin_initialize
rethrow
    {}
    nodeos  chain_plugin.cpp:1093 plugin_initialize
```

 I am 100% the node is shutting down gracefully, I handle all signals. Here is my config. Which I basically copied and pasted from the other history issue a few days ago [here](https://github.com/EOSIO/eos/issues/8893)

```
nodeos \
    --snapshot=/$SNAPSHOT \
    --data-dir $DATA_DIR \
    --config-dir $DATA_DIR/config \
    --plugin eosio::chain_api_plugin \
    --plugin eosio::http_plugin \
    --plugin eosio::state_history_plugin \
    --access-control-allow-origin='*' \
    --trace-history \
    --chain-state-history \
    --chain-state-db-size-mb=3000000 \
    --disable-replay-opts \
    --sync-fetch-span='100' \
    --state-history-endpoint='0.0.0.0:8080' \
    --http-server-address='0.0.0.0:8888' \
    --http-validate-host=false \
    --wasm-runtime='eos-vm-jit' \
    --eos-vm-oc-enable \
    --p2p-peer-address='peer.main.alohaeos.com:9876' \
    --p2p-peer-address='bp.cryptolions.io:9876' \
    --p2p-peer-address='publicnode.cypherglass.com:9876' \
    --p2p-peer-address='bp.eosbeijing.one:8080' \
    --p2p-peer-address='mainnet.eoscalgary.io:5222' \
    --p2p-peer-address='peering.mainnet.eoscanada.com:9876' \
    --p2p-peer-address='p2p.eosdetroit.io:3018' \
    --p2p-peer-address='peer1.mainnet.helloeos.com.cn:80' \
    --p2p-peer-address='eos-seed-de.privex.io:9876' \
    &
```
this does work as long as the node never stops. If I remove `--snapshot` all together, after first roll over, it seems to start at 0 like it never synced before from a snapshot. 

I can't find complete documentation on how to simply get a node up and running quickly and maintain all history information going forward. I want my node to be able to be shutdown/restart without having to manually manipulate files / etc on reboot.

**Comment by matthewdarwin** [comment]
--snapshot can only be used if there is no state directory.  You should have a startup script for your nodeos that checks if there is state and if yes, don't use the snapshot.

My startup script looks like this:

```
#!/bin/sh

ulimit -a
DATADIR="/var/lib/nodeos"
CONFIGDIR="/etc/nodeos"
COMMAND="/usr/bin/nodeos --config-dir $CONFIGDIR -d $DATADIR"

if [ -e /var/lib/nodeos/snapshots ]
then
        SNAPSHOT=`ls /var/lib/nodeos/snapshots/ | head -1`
else
        SNAPSHOT=""
fi

if [ ! -e /usr/bin/nodeos ]
then
        echo "No nodeos binary; aborting"
        sleep 10
        exit 1;
fi

if [ -e "$DATADIR/state/shared_memory.bin" ]
then
        echo "nodeos-wrapper: we've previously run"
        echo "if error then rm -fr $DATADIR/state/*"

elif [ ! -z "$SNAPSHOT" ] && [ -e "$DATADIR/snapshots/$SNAPSHOT" ] && [ -e "$DATADIR/blocks/blocks.log" ]
then
        echo "nodeos-wrapper: we've previously run, but state is missing; using snapshot"
        echo "if error then rm -fr $DATADIR/snapshots/*"
        COMMAND=`echo $COMMAND --snapshot $DATADIR/snapshots/$SNAPSHOT`

elif [ -e "$DATADIR/blocks/blocks.log" ]
then
        echo "nodeos-wrapper: we've previously run, but state is missing; replaying blocks"
        echo "if error then rm -fr $DATADIR/blocks/*"
        COMMAND=`echo $COMMAND --replay-blockchain --genesis-json=$CONFIGDIR/genesis.json`

elif [ ! -z "$SNAPSHOT" ] && [ -e "$DATADIR/snapshots/$SNAPSHOT" ]
then
        echo "nodeos-wrapper: we've previously run, but state and blocks are missing; using snapshot"
        echo "if error then rm -fr $DATADIR/snapshots/*"
        COMMAND=`echo $COMMAND --snapshot $DATADIR/snapshots/$SNAPSHOT`

else
        echo "nodeosd-wrapper: first time start"
        COMMAND=`echo $COMMAND --genesis-json=$CONFIGDIR/genesis.json`
fi

exec $COMMAND
```

**Comment by allenhan2** [comment]
@phewitt 
Are you using 2.0.x release?
Tried with a nodeos version similar to 2.0.5 release (same day as it is released). See the sync will be resumed from previous graceful exit when using w/o --snapshot. However the log print is confusing, (Catching up with chain, our last req is 0, ...), may need to fix this.

1. Started Nodeos with --snapshot, (handshake from 145.239.204.185:9876 - 64abcce, lib 116708620, head 116708952, head id db4b5fda5d9013ff.. sync 1)
info  2020-04-21T18:06:40.164 thread-0  net_plugin.cpp:816            connection           ] creating connection to peer.main.alohaeos.com:9876
info  2020-04-21T18:06:40.164 thread-1  net_plugin.cpp:2141           operator()           ] host: peer.main.alohaeos.com port: 9876
info  2020-04-21T18:06:40.315 thread-2  net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to peer.main.alohaeos.com:9876, lib 116693816, head 116693816, id 9cecee94ff9ac52c
info  2020-04-21T18:06:40.432 thread-1  net_plugin.cpp:1379           set_state            ] old state in sync becoming lib catchup
info  2020-04-21T18:06:40.432 thread-1  net_plugin.cpp:1545           start_sync           ] Catching up with chain, our last req is 0, theirs is 116708620 peer peer.main.alohaeos.com:9876
info  2020-04-21T18:06:40.432 thread-1  net_plugin.cpp:1491           operator()           ] requesting range 116693817 to 116693916, from peer.main.alohaeos.com:9876
info  2020-04-21T18:06:40.432 thread-1  net_plugin.cpp:1605           recv_handshake       ] handshake from 145.239.204.185:9876 - 64abcce, lib 116708620, head 116708952, head id db4b5fda5d9013ff.. sync 1
info  2020-04-21T18:06:52.427 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116693917 to 116694016, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:07:02.086 thread-0  producer_plugin.cpp:401       on_incoming_block    ] Received block b6aad929e1e9420f... #116694000 @ 2020-04-21T16:01:34.000 signed by atticlabeosb [trxs: 17, lib: 116693816, conf: 0, latency: 7528086 ms]
info  2020-04-21T18:07:03.792 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116694017 to 116694116, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:07:10.167 thread-2  net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
info  2020-04-21T18:07:15.304 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116694117 to 116694216, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:07:27.945 thread-1  net_plugin.cpp:1491           operator()           ] requesting range 116694217 to 116694316, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:07:38.686 thread-1  net_plugin.cpp:1491           operator()           ] requesting range 116694317 to 116694416, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:07:40.167 thread-1  net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
info  2020-04-21T18:07:50.638 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116694417 to 116694516, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:08:02.094 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116694517 to 116694616, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:08:10.170 thread-2  net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
info  2020-04-21T18:08:13.440 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116694617 to 116694716, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:08:25.744 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116694717 to 116694816, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:08:37.129 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116694817 to 116694916, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:08:39.855 thread-2  net_plugin.cpp:943            _close               ] closing 'peer.main.alohaeos.com:9876', peer.main.alohaeos.com:9876
info  2020-04-21T18:08:39.995 thread-1  net_plugin.cpp:943            _close               ] closing 'peer.main.alohaeos.com:9876', peer.main.alohaeos.com:9876
info  2020-04-21T18:08:40.001 thread-0  net_plugin.cpp:3515           plugin_shutdown      ] shutdown..
info  2020-04-21T18:08:40.001 thread-0  net_plugin.cpp:3532           plugin_shutdown      ] close 1 connections
info  2020-04-21T18:08:40.001 thread-0  net_plugin.cpp:3552           plugin_shutdown      ] exit shutdown
info  2020-04-21T18:09:25.655 thread-0  main.cpp:149                  main                 ] nodeos successfully exiting

2. restart nodeos w/o --snapshot (handshake from 145.239.204.185:9876 - 64abcce, lib 116709265, head 116709593, head id 4b3ef5e5de2c5b6a.. sync 1)

info  2020-04-21T18:12:02.137 thread-1  net_plugin.cpp:1545           start_sync           ] Catching up with chain, our last req is 0, theirs is 116709265 peer peer.main.alohaeos.com:9876
info  2020-04-21T18:12:02.137 thread-1  net_plugin.cpp:1491           operator()           ] requesting range 116694506 to 116694605, from peer.main.alohaeos.com:9876
info  2020-04-21T18:12:02.137 thread-1  net_plugin.cpp:1605           recv_handshake       ] handshake from 145.239.204.185:9876 - 64abcce, lib 116709265, head 116709593, head id 4b3ef5e5de2c5b6a.. sync 1
info  2020-04-21T18:12:03.726 thread-1  net_plugin.cpp:1491           operator()           ] requesting range 116694606 to 116694705, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:12:04.738 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116694706 to 116694805, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:12:05.746 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116694806 to 116694905, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:12:14.638 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116694906 to 116695005, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:12:26.204 thread-0  producer_plugin.cpp:401       on_incoming_block    ] Received block b60d5e38950d72ba... #116695000 @ 2020-04-21T16:09:56.000 signed by atticlabeosb [trxs: 19, lib: 116694672, conf: 0, latency: 7350204 ms]
info  2020-04-21T18:12:26.840 thread-2  net_plugin.cpp:1491           operator()           ] requesting range 116695006 to 116695105, from 145.239.204.185:9876 - 64abcce
info  2020-04-21T18:12:30.947 thread-1  net_plugin.cpp:943            _close               ] closing 'peer.main.alohaeos.com:9876', peer.main.alohaeos.com:9876
info  2020-04-21T18:12:30.947 thread-1  net_plugin.cpp:943            _close               ] closing 'peer.main.alohaeos.com:9876', peer.main.alohaeos.com:9876
info  2020-04-21T18:12:30.952 thread-0  net_plugin.cpp:3515           plugin_shutdown      ] shutdown..
info  2020-04-21T18:12:30.952 thread-0  net_plugin.cpp:3532           plugin_shutdown      ] close 1 connections
info  2020-04-21T18:12:30.952 thread-2  net_plugin.cpp:943            _close               ] closing 'peer.main.alohaeos.com:9876', peer.main.alohaeos.com:9876
info  2020-04-21T18:12:30.952 thread-0  net_plugin.cpp:3552           plugin_shutdown      ] exit shutdown
