### ISSUE TITLE
Deserialize contract_row table values

### ISSUE THREAD

**Issue by regisBafutwabo** [EOSIO/eos#8935]
Is there a way to deserialize the table_rows returned data that are serialized since they are not actions? (preferably through eosjs)

here below is the screenshot of what I was trying to accomplish: 
- on the left is the request 
- and on the right is the returned data

<img width="1198" alt="Screen Shot 2020-04-13 at 3 00 24 PM" src="https://user-images.githubusercontent.com/10329294/79096318-bf39ee80-7d97-11ea-9627-a1d8c142d2d9.png">

**Comment by emperorhan** [comment]
```javascript
function deserializeTypeData(contract: Contract, account: string, structName: string, data: string | Uint8Array, textEncoder: TextEncoder, textDecoder: TextDecoder): any {
    const type = contract.types.get(structName);
    if (typeof data === "string") {
        data = hexToUint8Array(data);
    }
    if(!type) {
        throw new Error(`Unknown type ${structName} in contract ${account}`);
    }
    const buffer = new SerialBuffer({textDecoder, textEncoder});
    buffer.pushArray(data);
    return type.deserialize(buffer);
}
```
This works but you should know the struct name from contract code
(ex. for eosio `rammarket` in `eosio.system/exchange_state.hpp` the struct name is `exchange_state`)
