### ISSUE TITLE
[ CI/CD Failure Triage: ship_test] macOS 10.15:  block_num: 98 took 0.841 seconds to be received. 

### ISSUE THREAD

**Issue by ndcgundlach** [EOSIO/eos#8936]
See [build 21415](https://buildkite.com/EOSIO/eosio/builds/21415), macOS `ship_test` [line 673](https://buildkite.com/EOSIO/eosio/builds/21415#2259fffe-be96-42c3-b7c9-ef476cb9a23f/264-673).

**Comment by sanaraufx** [comment]
Closing issue after consult with Chris
