### ISSUE TITLE
build issue related to mongodb

### ISSUE THREAD

**Issue by crazybits** [EOSIO/eos#894]
still hit the following issue even i install mongodb
 

>  Make Warning at plugins/db_plugin/CMakeLists.txt:6 (find_package):
>   By not providing "Findlibmongoc-1.0.cmake" in CMAKE_MODULE_PATH this
>   project has asked CMake to find a package configuration file provided by
>   "libmongoc-1.0", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "libmongoc-1.0"
>   (requested version 1.8) with any of the following names:
> 
>     libmongoc-1.0Config.cmake
>     libmongoc-1.0-config.cmake
> 
>   Add the installation prefix of "libmongoc-1.0" to CMAKE_PREFIX_PATH or set
>   "libmongoc-1.0_DIR" to a directory containing one of the above files.  If
>   "libmongoc-1.0" provides a separate development package or SDK, be sure it
>   has been installed.
> 
> 
> Could NOT find MongoDB. db_plugin with MongoDB support will not be included.
> -- Doxygen found.  Contract documentation will be generated.
> -- Configuring incomplete, errors occurred!
> See also "/Users/crazybit/eosio/eos/build/CMakeFiles/CMakeOutput.log".
> make: *** [cmake_check_build_system] Error 1

**Comment by heifner** [comment]
Please use Telegram `EOS Developers` for support.

This is only a warning and you can build without mongodb.
If you want to build db_plugin with mongo then you need to install the required libraries, not just install mongodb. I recommend you take a look at the .travis.yml file.
