### ISSUE TITLE
Help text for `--wasm-runtime` does not show available options

### ISSUE THREAD

**Issue by arhag** [EOSIO/eos#8945]
The available options for `--wasm-runtime` should be available in the help text along with a brief description of each. See help text of `--read-mode` as an example what this could look like. Also it should show the default option in the help text as well, just like `--read-mode`.

**Comment by spoonincode** [comment]
> Also it should show the default option in the help text as well, just like `--read-mode`.

This option today works a little differently: like the help text says it overrides the default wasm runtime. The default value for this option is _empty_ which means `eosio::chain::wasm_interface::vm_type default_wasm_runtime` becomes the default value.  It's probably fine to refactor this option to make it more like the other options with default values.

**Comment by kimjh2005** [comment]
Old help text
--wasm-runtime runtime Override default WASM runtime

New help text for release/2.0.x
--wasm-runtime runtime (=wabt) Override default WASM runtime ( "wabt",
"eos-vm-jit", "eos-vm"[, "eos-vm-oc"])
"wabt" : The WebAssembly Binary
Toolkit.
"eos-vm-jit" : A WebAssembly runtime
that compiles WebAssembly code to
native x86 code prior to execution.
"eos-vm" : A WebAssembly interpreter."eos-vm-oc" : Unsupported. Instead, use one of the other runtimes along with the option enable-eos-vm-oc

New help text for develop
--wasm-runtime runtime (=eos-vm-jit) Override default WASM runtime (
"eos-vm-jit", "eos-vm", ["eos-vm-oc"]) "eos-vm-jit" : A WebAssembly runtime
that compiles WebAssembly code to native x86 code prior to execution.
"eos-vm" : A WebAssembly interpreter.
"eos-vm-oc" : Unsupported. Instead, use one of the other runtimes along with the option enable-eos-vm-oc

*Note: The option and the text for "eos-vm-oc" only appears in help text when EOSIO_EOS_VM_DEVELOPER is defined.
