### ISSUE TITLE
ubuntu16.04+8G+eosio2.0.4+Build EOSIO Binaries something wrong 

### ISSUE THREAD

**Issue by adaipan** [EOSIO/eos#8946]
[ 73%] Building CXX object libraries/chain/CMakeFiles/eosio_chain.dir/webassembly/eos-vm-oc/LLVMJIT.cpp.o
cd /root/eosio/eos/build/libraries/chain && /root/eosio/2.0/opt/clang8/bin/clang++  -DBOOST_ALL_NO_LIB -DEOSIO_EOS_VM_JIT_RUNTIME_ENABLED -DEOSIO_EOS_VM_OC_RUNTIME_ENABLED -DEOSIO_EOS_VM_RUNTIME_ENABLED -DEOSIO_WABT_RUNTIME_ENABLED -DEOS_VM_SOFTFLOAT -DEOS_VM_USE_EXTERNAL_OUTCOME -I/root/eosio/2.0/opt/llvm/include -I/root/eosio/eos/libraries/chain/include -I/root/eosio/eos/build/libraries/chain/include -I/root/eosio/eos/libraries/chain/../wasm-jit/Include -I/root/eosio/eos/libraries/chain/libraries/eos-vm/include -I/root/eosio/eos/libraries/wabt -I/root/eosio/eos/build/libraries/wabt -I/root/eosio/eos/libraries/fc/include -I/root/eosio/eos/libraries/fc/vendor/websocketpp -I/root/eosio/eos/libraries/fc/secp256k1/upstream -I/root/eosio/eos/libraries/fc/secp256k1/upstream/include -I/root/eosio/eos/libraries/chainbase/include -I/root/eosio/eos/libraries/wasm-jit/Source/Runtime/../../../chain/include -I/root/eosio/eos/libraries/softfloat/source/include -I/root/eosio/eos/libraries/softfloat/source/8086-SSE -I/root/eosio/eos/libraries/softfloat/build/Linux-x86_64-GCC -I/root/eosio/eos/libraries/builtins -I/root/eosio/eos/libraries/builtins../softfloat/source/include -I/root/eosio/eos/libraries/eos-vm/include -I/root/eosio/eos/libraries/eos-vm/external/softfloat/source/include -I/root/eosio/eos/libraries/eos-vm/external/outcome/single-header -isystem /root/eosio/2.0/src/boost_1_71_0/include -isystem /root/eosio/2.0/opt/clang8/include/c++/v1 -isystem /usr/local/include -isystem /usr/include  -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fpie -nostdinc++ -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fpie -Wall -Wno-invalid-partial-specialization -O3 -DNDEBUG   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -pthread -std=gnu++17 -o CMakeFiles/eosio_chain.dir/webassembly/eos-vm-oc/LLVMJIT.cpp.o -c /root/eosio/eos/libraries/chain/webassembly/eos-vm-oc/LLVMJIT.cpp

clang-8: error: unable to execute command: Killed
clang-8: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 8.0.1 (https://git.llvm.org/git/clang.git a03da8be08a208122e292016cb6cea1f30229677) (https://git.llvm.org/git/llvm.git 18e41dc964f916504ec90dba523826ac74d235c4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/eosio/2.0/opt/clang8/bin
clang-8: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-8: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-8: note: diagnostic msg: /tmp/wasm_interface-7d9af9.cpp
clang-8: note: diagnostic msg: /tmp/wasm_interface-7d9af9.sh
clang-8: note: diagnostic msg: 

********************
libraries/chain/CMakeFiles/eosio_chain.dir/build.make:335: recipe for target 'libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o' failed
make[2]: *** [libraries/chain/CMakeFiles/eosio_chain.dir/wasm_interface.cpp.o] Error 254
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/root/eosio/eos/build'
CMakeFiles/Makefile2:2408: recipe for target 'libraries/chain/CMakeFiles/eosio_chain.dir/all' failed
make[1]: *** [libraries/chain/CMakeFiles/eosio_chain.dir/all] Error 2
make[1]: Leaving directory '/root/eosio/eos/build'
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by heifner** [comment]
Are you using the build script or building by hand? Can you provide your command line. 8GB ram is not much, I suspect you are running out of memory.

**Comment by spoonincode** [comment]
Almost certainly exhausting memory. You can reduce the number of parallel compiles by setting  `export JOBS=2` in your terminal before running the build script.

**Comment by adaipan** [comment]
maybe   i change version(v1.8)  run success
