### ISSUE TITLE
make  Error 127***

### ISSUE THREAD

**Issue by boyue** [EOSIO/eos#895]
Hey ,My name is CrashHunter, I come from Youzan company in China.
I occur an error when run :
./build.sh darwin

the error is :
-- Build files have been written to: /Users/rancho/eos/build
[  1%] Generating WAST infinite.wast
[  1%] Generating WAST proxy.wast
[  1%] Generating WAST currency.wast
[  1%] Generating WAST test_api.wast
/bin/sh: /usr/local/binaryen/bin/s2wasm: No such file or directory
/bin/sh: /usr/local/binaryen/bin/s2wasm: No such file or directory
/bin/sh: /usr/local/binaryen/bin/s2wasm: No such file or directory
/bin/sh: /usr/local/binaryen/bin/s2wasm: No such file or directory
make[2]: make[2]: *** [contracts/test_api/test_api.wast] Error 127*** [contracts/proxy/proxy.wast] Error 127

make[2]: *** [contracts/currency/currency.wast] Error 127
make[2]: *** [contracts/infinite/infinite.wast] Error 127
make[1]: *** [contracts/proxy/CMakeFiles/proxy.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [contracts/test_api/CMakeFiles/test_api.dir/all] Error 2
make[1]: *** [contracts/currency/CMakeFiles/currency.dir/all] Error 2
make[1]: *** [contracts/infinite/CMakeFiles/infinite.dir/all] Error 2
make: *** [all] Error 2

can you help me?

**Comment by heifner** [comment]
@boyue Please use Telegram `EOS Developers` for support.

You might take a look at: https://github.com/EOSIO/eos/pull/871/files and see if those changes fixes your issue. Either way, let us know on telegram.

**Comment by Haley-Wong** [comment]
@boyue 你的问题解决了么？我也遇到跟你一样的问题

**Comment by a-thomas** [comment]
Hi there, it seems that I've got the same problem with the last version of the `master` branch.

```
[ 58%] Generating WAST multi_index_test.wast
cd /Users/aleks/Dev/eos/eos/build/contracts/multi_index_test && /usr/local/binaryen/bin/s2wasm -o /Users/aleks/Dev/eos/eos/build/contracts/multi_index_test/multi_index_test.wast -s 4096 multi_index_test.s
/bin/sh: /usr/local/binaryen/bin/s2wasm: No such file or directory
make[2]: *** [contracts/multi_index_test/multi_index_test.wast] Error 127
make[1]: *** [contracts/multi_index_test/CMakeFiles/multi_index_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f libraries/fc/CMakeFiles/fc.dir/build.make libraries/fc/CMakeFiles/fc.dir/build
make[2]: Nothing to be done for `libraries/fc/CMakeFiles/fc.dir/build'.
[ 67%] Built target fc
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.
```
I'm on OSX 10.13.3 (High Sierra). Thanks in advance !

**Comment by jackrex** [comment]
same issue!
