### ISSUE TITLE
push_transaction无法发送交易

### ISSUE THREAD

**Issue by libangzhu** [EOSIO/eos#8965]
我构造了签名了正确的EOS交易，但是调用push_transaction接口后一直超时，无法发送成功，但是我用了第三方节点https://mainnet.eoscannon.io/v1/chain/push_transaction，用相同的构造数据调用相同的push_transaction接口，却能发送成功。想问一下，发送一笔交易，需要在节点上配置什么特殊配置项吗？

**Comment by allenhan2** [comment]
Could you please send us the config.ini (after removing sensitive data, such as private keys, etc), and version number, command-line options, also, any modification to the software? 
What transaction was pushed (specially set_code)?

**Comment by allenhan2** [comment]
no further info from requester, so close for now
