### ISSUE TITLE
Improve the build system

### ISSUE THREAD

**Issue by wilmerpaulino** [EOSIO/eos#897]
I would like to get feedback on some changes to improve the build system. I realize this might not be a priority for the core team at the moment, which is why I would like to take the initiative on getting this done.

I've noticed there are some small discrepancies on how to do a manual build of EOS (without the build script), between [Travis](https://github.com/EOSIO/eos/blob/master/.travis.yml), the notes on the [wiki](https://github.com/EOSIO/eos/wiki/Local-Environment#22-manual-build-script), and the notes on the [README](https://github.com/EOSIO/eos/blob/master/README.md#build). I've also noticed people experiencing issues when building the project while hanging out in the EOS Developers chat.

Therefore, I would like to propose the following changes:
- Provide a friendlier build script with flags to build with Doxygen, MongoDB, etc.
- Improve the way dependencies are handled in CMake
- Clean up the CMake files and make them easier to add/remove changes in the future
- Maintain coherent instructions on how to build EOS throughout the repository

I'm sure there are other things that I missed that can be improved, which is why I would like to discuss the possible options. Feel free to add your own suggestions.

**Comment by JamesKnippel** [comment]
Seconded! I will do my best to create some PR's in the near future with the sole purpose of clarifying areas of misleading grammar and/or instructions with vague implications that are easy to miss.

**Comment by kirkins** [comment]
+1 made a commit only changing the README and travis failed, a bit strange.

https://github.com/EOSIO/eos/pull/1430
