### ISSUE TITLE
Create new branch from cc32d9/wax2.0/tree/snapshot_tests-snapshot-generator

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#8981]
Please create a new branch `snapshot_tests-snapshot-generator` from 
https://github.com/cc32d9/wax2.0/tree/snapshot_tests-snapshot-generator

Motivation:

the snapshot archives in `unittests/snapshots` were created by manually modifying `unittests/snapshot_tests.cpp`, and the modifications were not saved. So, fork projects which introduce new intrinsics (such as WAX) would either have failing snapshot tests, or would have to program the snapshot generation again. This is an implementation that creates such snapshots, so that this work doesn't need to be re-done again.

The branch is based on `v2.0.4`

**Comment by cc32d9** [comment]
Also another branch for 1.8 in order to generate v2 snapshots: 

https://github.com/cc32d9/wax2.0/tree/snapshot_tests-snapshot-generator-1.8

**Comment by spoonincode** [comment]
It may be easier to review and provide feedback if you open a PR. I would recommend opening one against `develop` first and after review opening up PRs for older releases.

**Comment by cc32d9** [comment]
@spoonincode Github does not allow creating new branches in PR. And these should be separate stub branches, not merged into `develop` or `master`. Their purpose is one-off work if you need to generate new test snapshots, and they need to stay with the old versions. There's no need in them in current branches.

**Comment by heifner** [comment]
Can't these be methods in `release/2.0.x`, `release/1.8.x`, and `develop` that are not called. They can include a comment with how to use them. Otherwise, I don't see them being kept up to date or anyone remembering to use them.

**Comment by cc32d9** [comment]
they were needed very rarely (only two times in eosio, one time in wax), and probably some other projects will need them eventually to make one-off snapshots. The code at B1 was discarded after the snapshots were made, so I had to re-create it. This is just to archive the code so that next time it's not needed to write it again.

I don't see much value in making it a maintained code within production branches.

**Comment by spoonincode** [comment]
Without it being in the main code I don't think anyone is ever going to find it dangling off in some branch somewhere; or find it useful as that branch will be progressively out of date. Really seems like finding a way to include this more permanently would be desirable.

**Comment by cc32d9** [comment]
but eosio 2.0 is unable to produce V2 snapshots, and the test suite needs v2 snapshots for compatibility checks. So this code has to stay in an old branch.

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
