### ISSUE TITLE
/v1/net/connections should run at higher priority

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#8986]
In https://github.com/EOSIO/eos/issues/8655, the priority of /v1/chain/get_info was increased such that while nodeos is busy (eg catching up blocks after being down for a while), that get_info works.  This feature was implemented in nodeos v2.0.5 and works well.

I would like to request the same change to be made for /v1/net/connections. This API is used to understand which peers are connected at the current time. This API should never be exposed to the  public, so increasing priority should not be subject to abuse.

**Comment by heifner** [comment]
`net_api_plugin` and `producer_api_plugin` neither are exposed publicly, so higher priority for them seems appropriate.

**Comment by ag-blockone** [comment]
I just checked the swagger.yaml for producer_api_plugin and it doesn't seem to have net/connections endpoint. Only exists for net_api_plugin.   Just want to confirm if my understanding is correct

**Comment by heifner** [comment]
@lparisc ^^ see swagger comment.

**Comment by lparisc** [comment]
@ag-blockone That's correct, the `net/connections` endpoint is provided by the `net_api_plugin` not the `producer_api_plugin` - note the prefix `net` in the endpoint.

**Comment by matthewdarwin** [comment]
This appears to be completed now?

develop: https://github.com/EOSIO/eos/pull/9039
2.0: https://github.com/EOSIO/eos/pull/9035

**Comment by ag-blockone** [comment]
@matthewdarwin Yes matthew, changes have been pushed to develop and release/2.0.x.
I will close it now.
