### ISSUE TITLE
developers.eos.io search issues

### ISSUE THREAD

**Issue by heifner** [EOSIO/eos#8990]
- Start at https://developers.eos.io/
- Search for "install"
- Switch "welcome" left of search input box to "eos"
- Search for "install"
- Nothing is reported.

In general switching the Doc Search Dropdown seems to not work most of the time. It doesn't seem to allow you to actually switch to difference document types.

Also "eos" should be "eosio".

**Comment by iamveritas** [comment]
this was fixed by https://github.com/EOSIO/eosio-docs-gatsby/commit/06a5d593783070c6e279b3584a5e1f0fe278c4a8
