### ISSUE TITLE
fatal error: 'fc/smart_ref_fwd.hpp' file not found

### ISSUE THREAD

**Issue by gzliudan** [EOSIO/eos#9004]
When I compile eos v2.0.5, the make command stops and report below error:
libraries/chain/include/eosio/chain/types.hpp:17:10: fatal error: 'fc/smart_ref_fwd.hpp' file not found

There's no file named smart_ref_fwd.hpp in libraries/fc/include/fc directory. Which branch of fc should I checkout for compile eos v2.0.5?

**Comment by heifner** [comment]
Update all your submodules when you switch branches.
`git submodule update --init --recursive`

**Comment by gzliudan** [comment]
thanks.
