### ISSUE TITLE
Prepare packages for Ubuntu 20.04

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#9006]
A new LTS release is about to be available, so it will be great to have deb packages for it.

So far, I tried to install eosio_2.0.5-1-ubuntu-18.04_amd64.deb on Ubuntu 20.04 LTS, alas, not working:

```
The following packages have unmet dependencies:
 eosio : Depends: libicu60 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by zengchengshan** [comment]
Install dependency before installation,use this command  apt-get install libicu60 libusb-1.0-0 libcurl3-gnutls

**Comment by rise-worlds** [comment]
ubuntu 20.04 use libicu66

**Comment by cibil** [comment]
I have the same problem on ubuntu 20.04.
please provide it to work with ubuntu 2020

**Comment by elboletaire** [comment]
In the meantime, you can manually install libicu60 downloading the package:

~~~bash
wget http://mirrors.edge.kernel.org/ubuntu/pool/main/i/icu/libicu60_60.2-3ubuntu3.1_amd64.deb 
sudo dpkg -i ./libicu60_60.2-3ubuntu3.1_amd64.deb 
~~~

After that you'll be able to properly install eosio under ubuntu 20.04.

**Comment by sanaraufx** [comment]
Support for Ubuntu 20.04 was added to 2.1 release

**Comment by jomoljaison** [comment]
mine is ubuntu 20.10 I have the same problem.please provide guidelines to work in ubuntu 20.10

**Comment by rise-worlds** [comment]
> 
ubuntu 20.10 is short term support version, wait next Long Term Support Version 22.04.
