### ISSUE TITLE
./eosc push message currency transfer'{"from":"currency","to":"inita","amount":50}'--scope currency,inita --permission currency@active

### ISSUE THREAD

**Issue by lucas7788** [EOSIO/eos#901]
![default](https://user-images.githubusercontent.com/13885466/33755437-b4880004-dc2b-11e7-80f0-6cff2c7ad53e.png)

could someone help me??

**Comment by nanonano7** [comment]
its probably bc you have no spaces between transfer and data and also between scope and data
for similar question pls use the telegram dev chat
https://t.me/joinchat/EgOVjkPktgfUS3kt14FStw

**Comment by lucas7788** [comment]
![default](https://user-images.githubusercontent.com/13885466/33756325-e86e3286-dc2f-11e7-8f67-b707dff4696d.png)
thank u for your answer,I modified the command as u said,but I come across a new error,do u have an idea?

**Comment by nanonano7** [comment]
change amount to quantity

**Comment by lucas7788** [comment]
thank u, I just got it.
