### ISSUE TITLE
EOS v2.0.5 can't sync block,pls help!

### ISSUE THREAD

**Issue by zengchengshan** [EOSIO/eos#9027]
all-new Ubuntu18.04 system,install the lastest EOS version(v2.0.5),it can't sync block,how to solve the problem?

**Comment by zengchengshan** [comment]
the error message as follow:error 2020-04-30T06:49:56.356 net-1     net_plugin.cpp:2369           operator()           ] Closing connection to:mainnet.eosamsterdam.net:9876

**Comment by heifner** [comment]
Need more of the log and your config.ini and command line arguments.

**Comment by zengchengshan** [comment]
it seems that the node can't be connected.
info  2020-04-30T15:57:12.892 nodeos    platform_timer_accurac:62     compute_and_print_ti ] Checktime timer accuracy: min:3us max:89us mean:6us stddev:2us
info  2020-04-30T15:57:12.893 nodeos    http_plugin.cpp:715           plugin_initialize    ] configured http to listen on 0.0.0.0:8888
info  2020-04-30T15:57:12.893 nodeos    main.cpp:106                  main                 ] nodeos version v2.0.5 v2.0.5-de78b49b5765c88f4e005046d1489c3905985b94
info  2020-04-30T15:57:12.893 nodeos    main.cpp:107                  main                 ] nodeos using configuration file /data/data/config.ini
info  2020-04-30T15:57:12.893 nodeos    main.cpp:108                  main                 ] nodeos data directory is /data/data
info  2020-04-30T15:57:12.893 nodeos    chain_plugin.cpp:1121         plugin_startup       ] starting chain in read/write mode
info  2020-04-30T15:57:12.893 nodeos    chain_plugin.cpp:1129         plugin_startup       ] Blockchain started; head block is #1
info  2020-04-30T15:57:12.893 nodeos    http_plugin.cpp:793           plugin_startup       ] start listening for http requests
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/node/get_supported_apis
info  2020-04-30T15:57:12.894 nodeos    chain_api_plugin.cpp:73       plugin_startup       ] starting chain_api_plugin
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_info
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/abi_bin_to_json
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/abi_json_to_bin
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_abi
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_account
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_activated_protocol_features
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_block
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_block_header_state
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_code
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_code_hash
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_currency_balance
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_currency_stats
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_producer_schedule
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_producers
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_raw_abi
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_raw_code_and_abi
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_required_keys
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_scheduled_transactions
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_table_by_scope
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_table_rows
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/get_transaction_id
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/push_block
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/push_transaction
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/push_transactions
info  2020-04-30T15:57:12.894 nodeos    http_plugin.cpp:890           add_handler          ] add api url: /v1/chain/send_transaction
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:3413           plugin_startup       ] my node_id is 3478d939e706895d8d89cb27ea208518cdcf46e2a3ef69628b96c7c4bc4d12ad
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:3469           plugin_startup       ] starting listener, max clients is 4
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:816            connection           ] creating connection to peer.main.alohaeos.com:9876
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:816            connection           ] creating connection to mainnet.eosamsterdam.net:9876
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:816            connection           ] creating connection to seed.eoscleaner.com:9876
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:816            connection           ] creating connection to p2p.eosflare.io:9876
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:816            connection           ] creating connection to fullnode.eoslaomao.com:443
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:816            connection           ] creating connection to mainnet.eoslaomao.com:443
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:816            connection           ] creating connection to peer1.eosphere.io:9876
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:816            connection           ] creating connection to p2p.eossweden.org:9876
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:816            connection           ] creating connection to eos.okpool.top:9876
info  2020-04-30T15:57:12.894 nodeos    net_plugin.cpp:816            connection           ] creating connection to api3.tokenika.io:9876
info  2020-04-30T15:57:12.894 net-0     net_plugin.cpp:2141           operator()           ] host: mainnet.eosamsterdam.net port: 9876 
info  2020-04-30T15:57:12.895 nodeos    producer_plugin.cpp:947       plugin_startup       ] producer plugin:  plugin_startup() begin
info  2020-04-30T15:57:12.895 net-1     net_plugin.cpp:2141           operator()           ] host: peer.main.alohaeos.com port: 9876 
info  2020-04-30T15:57:12.895 net-1     net_plugin.cpp:2141           operator()           ] host: p2p.eosflare.io port: 9876 
info  2020-04-30T15:57:12.895 net-1     net_plugin.cpp:2141           operator()           ] host: fullnode.eoslaomao.com port: 443 
info  2020-04-30T15:57:12.895 net-1     net_plugin.cpp:2141           operator()           ] host: mainnet.eoslaomao.com port: 443 
info  2020-04-30T15:57:12.895 net-1     net_plugin.cpp:2141           operator()           ] host: peer1.eosphere.io port: 9876 
info  2020-04-30T15:57:12.895 net-1     net_plugin.cpp:2141           operator()           ] host: p2p.eossweden.org port: 9876 
info  2020-04-30T15:57:12.895 net-1     net_plugin.cpp:2141           operator()           ] host: eos.okpool.top port: 9876 
info  2020-04-30T15:57:12.895 net-1     net_plugin.cpp:2141           operator()           ] host: api3.tokenika.io port: 9876 
info  2020-04-30T15:57:12.895 nodeos    producer_plugin.cpp:983       plugin_startup       ] producer plugin:  plugin_startup() end
info  2020-04-30T15:57:12.895 net-0     net_plugin.cpp:2141           operator()           ] host: seed.eoscleaner.com port: 9876 
info  2020-04-30T15:57:13.132 net-1     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to peer.main.alohaeos.com:9876, lib 1, head 1, id bcf2f448225d0996
info  2020-04-30T15:57:13.146 net-0     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to mainnet.eosamsterdam.net:9876, lib 1, head 1, id bcf2f448225d0996
warn  2020-04-30T15:57:13.688 net-1     net_plugin.cpp:2673           handle_message       ] ["peer.main.alohaeos.com:9876" 51.38.86.48:9876]received go_away_message, reason = wrong chain
info  2020-04-30T15:57:13.688 net-1     net_plugin.cpp:943            _close               ] closing 'peer.main.alohaeos.com:9876', peer.main.alohaeos.com:9876
info  2020-04-30T15:57:13.959 net-0     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to mainnet.eoslaomao.com:443, lib 1, head 1, id bcf2f448225d0996
info  2020-04-30T15:57:13.970 net-1     net_plugin.cpp:2350           operator()           ] Peer closed connection
error 2020-04-30T15:57:13.970 net-1     net_plugin.cpp:2369           operator()           ] Closing connection to: mainnet.eoslaomao.com:443
info  2020-04-30T15:57:13.970 net-1     net_plugin.cpp:943            _close               ] closing 'mainnet.eoslaomao.com:443', mainnet.eoslaomao.com:443
info  2020-04-30T15:57:14.022 net-0     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to fullnode.eoslaomao.com:443, lib 1, head 1, id bcf2f448225d0996
info  2020-04-30T15:57:14.070 net-1     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/4, peer connections: 9/10
info  2020-04-30T15:57:14.070 net-0     net_plugin.cpp:2141           operator()           ] host: mainnet.eoslaomao.com port: 443 
info  2020-04-30T15:57:14.095 net-1     net_plugin.cpp:2350           operator()           ] Peer closed connection
error 2020-04-30T15:57:14.095 net-1     net_plugin.cpp:2369           operator()           ] Closing connection to: fullnode.eoslaomao.com:443
info  2020-04-30T15:57:14.095 net-1     net_plugin.cpp:943            _close               ] closing 'fullnode.eoslaomao.com:443', fullnode.eoslaomao.com:443
info  2020-04-30T15:57:14.128 net-0     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to p2p.eosflare.io:9876, lib 1, head 1, id bcf2f448225d0996
info  2020-04-30T15:57:14.195 net-1     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/4, peer connections: 9/10
info  2020-04-30T15:57:14.195 net-0     net_plugin.cpp:2141           operator()           ] host: fullnode.eoslaomao.com port: 443 
info  2020-04-30T15:57:14.195 net-1     net_plugin.cpp:2141           operator()           ] host: mainnet.eoslaomao.com port: 443 
info  2020-04-30T15:57:14.209 net-0     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to peer1.eosphere.io:9876, lib 1, head 1, id bcf2f448225d0996
warn  2020-04-30T15:57:14.309 net-1     net_plugin.cpp:2673           handle_message       ] ["p2p.eosflare.io:9876" 108.171.210.180:9876]received go_away_message, reason = wrong chain
info  2020-04-30T15:57:14.309 net-1     net_plugin.cpp:943            _close               ] closing 'p2p.eosflare.io:9876', p2p.eosflare.io:9876
warn  2020-04-30T15:57:14.471 net-0     net_plugin.cpp:2673           handle_message       ] ["peer1.eosphere.io:9876" 139.99.234.125:9876]received go_away_message, reason = wrong chain
info  2020-04-30T15:57:14.471 net-0     net_plugin.cpp:943            _close               ] closing 'peer1.eosphere.io:9876', peer1.eosphere.io:9876
info  2020-04-30T15:57:15.883 net-1     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to eos.okpool.top:9876, lib 1, head 1, id bcf2f448225d0996
info  2020-04-30T15:57:16.870 net-0     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to p2p.eossweden.org:9876, lib 1, head 1, id bcf2f448225d0996
warn  2020-04-30T15:57:17.138 net-1     net_plugin.cpp:2673           handle_message       ] ["p2p.eossweden.org:9876" 81.26.240.211:9876]received go_away_message, reason = wrong chain
info  2020-04-30T15:57:17.138 net-1     net_plugin.cpp:943            _close               ] closing 'p2p.eossweden.org:9876', p2p.eossweden.org:9876
info  2020-04-30T15:57:18.058 net-0     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to api3.tokenika.io:9876, lib 1, head 1, id bcf2f448225d0996
warn  2020-04-30T15:57:18.292 net-1     net_plugin.cpp:2673           handle_message       ] ["api3.tokenika.io:9876" 51.83.140.117:9876]received go_away_message, reason = wrong chain
info  2020-04-30T15:57:18.292 net-1     net_plugin.cpp:943            _close               ] closing 'api3.tokenika.io:9876', api3.tokenika.io:9876
info  2020-04-30T15:57:19.127 net-1     net_plugin.cpp:2350           operator()           ] Peer closed connection
error 2020-04-30T15:57:19.128 net-1     net_plugin.cpp:2369           operator()           ] Closing connection to: mainnet.eosamsterdam.net:9876
info  2020-04-30T15:57:19.128 net-1     net_plugin.cpp:943            _close               ] closing 'mainnet.eosamsterdam.net:9876', mainnet.eosamsterdam.net:9876
info  2020-04-30T15:57:19.228 net-1     net_plugin.cpp:2141           operator()           ] host: mainnet.eosamsterdam.net port: 9876 
info  2020-04-30T15:57:19.228 net-0     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/4, peer connections: 5/10
info  2020-04-30T15:57:19.228 net-0     net_plugin.cpp:2141           operator()           ] host: mainnet.eoslaomao.com port: 443 
info  2020-04-30T15:57:19.228 net-1     net_plugin.cpp:2141           operator()           ] host: fullnode.eoslaomao.com port: 443 
error 2020-04-30T15:57:19.275 net-1     net_plugin.cpp:2348           operator()           ] Error reading message: Connection reset by peer
error 2020-04-30T15:57:19.275 net-1     net_plugin.cpp:2369           operator()           ] Closing connection to: eos.okpool.top:9876
info  2020-04-30T15:57:19.275 net-1     net_plugin.cpp:943            _close               ] closing 'eos.okpool.top:9876', eos.okpool.top:9876
info  2020-04-30T15:57:19.375 net-0     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/4, peer connections: 5/10
info  2020-04-30T15:57:19.375 net-0     net_plugin.cpp:2141           operator()           ] host: fullnode.eoslaomao.com port: 443 
info  2020-04-30T15:57:19.375 net-0     net_plugin.cpp:2141           operator()           ] host: mainnet.eoslaomao.com port: 443 
info  2020-04-30T15:57:19.375 net-0     net_plugin.cpp:2141           operator()           ] host: eos.okpool.top port: 9876 
info  2020-04-30T15:57:19.375 net-1     net_plugin.cpp:2141           operator()           ] host: mainnet.eosamsterdam.net port: 9876 
error 2020-04-30T15:57:20.787 net-0     net_plugin.cpp:2185           operator()           ] connection failed to mainnet.eoslaomao.com:443: Operation canceled
info  2020-04-30T15:57:20.787 net-0     net_plugin.cpp:943            _close               ] closing 'mainnet.eoslaomao.com:443', mainnet.eoslaomao.com:443
error 2020-04-30T15:57:20.787 net-0     net_plugin.cpp:2185           operator()           ] connection failed to mainnet.eoslaomao.com:443: Operation canceled
info  2020-04-30T15:57:20.787 net-0     net_plugin.cpp:943            _close               ] closing 'mainnet.eoslaomao.com:443', mainnet.eoslaomao.com:443

**Comment by zengchengshan** [comment]
root@bc607b692a77:/data# cat start.sh 
#!/bin/bash
################################################################################
#
# Scrip Created by http://CryptoLions.io
# For EOS mainnet
#
# https://github.com/CryptoLions/EOS-MainNet
#
###############################################################################

DATADIR="/data/data"
#NODEOSBINDIR="/data/eos/build/programs"


/data/stop.sh
echo -e "Starting Nodeos \n";

ulimit -c unlimited
ulimit -n 65535
ulimit -s 64000
/usr/bin/nodeos --data-dir $DATADIR --config-dir $DATADIR "$@" > $DATADIR/stdout.txt 2> $DATADIR/stderr.txt &  echo $! > $DATADIR/nodeos.pid

**Comment by zengchengshan** [comment]
root@bc607b692a77:/data# cat data/config.ini 

    #producer-name = !!!!YOUR_BP_NAME!!!!!!!!
    #signature-provider = YOUR_BLOCK_SIGN_PUB_KEY=KEY:YOUR_BLOCK_SIGN_PRIV_KEY

    agent-name = AgentName

    #blocks-dir = "blocks"
    chain-state-db-size-mb = 10240
    reversible-blocks-db-size-mb = 1024
    contracts-console = false


    http-server-address = 0.0.0.0:8888
    p2p-listen-endpoint = 0.0.0.0:9876
    p2p-server-address = 0.0.0.0:9876
    #bnet-endpoint = !!YOUR_ENDPOINT_IP_ADDRESS!!:9875
    #bnet_threads = 4

    http-validate-host = false
    verbose-http-errors = true
    abi-serializer-max-time-ms = 2000
    chain-threads = 8
    http-threads = 6
    access-control-allow-origin = *
    # access-control-allow-headers =
    # access-control-max-age =
    #access-control-allow-credentials = false



    p2p-max-nodes-per-host = 4

    # actor-whitelist =
    # actor-blacklist =
    # contract-whitelist =
    # contract-blacklist =
    # filter-on =




    # SSL
    # Filename with https private key in PEM format. Required for https (eosio::http_plugin)
    # https-server-address =
    # Filename with the certificate chain to present on https connections. PEM format. Required for https. (eosio::http_plugin)
    # https-certificate-chain-file =
    # Filename with https private key in PEM format. Required for https (eosio::http_plugin)
    # https-private-key-file =


    allowed-connection = any

    #log-level-net-plugin = info
    max-clients = 4
    connection-cleanup-period = 30
    #network-version-match = 1
    sync-fetch-span = 2000
    enable-stale-production = false

    #max-implicit-request = 1500
    pause-on-startup = false
    max-transaction-time = 30
    max-irreversible-block-age = -1
    txn-reference-block-lag = 0
    #unlock-timeout = 90000
    wasm-runtime=wabt
    

    plugin = eosio::chain_api_plugin
    #plugin = eosio::history_plugin
    #plugin = eosio::history_api_plugin
    plugin = eosio::chain_plugin
    #plugin = eosio::bnet_plugin

    #plugin = net_plugin
    #plugin = net_api_plugin


    #bnet-connect =
    #bnet-connect =
    #bnet-connect =

    #p2p-peer-address =
    #p2p-peer-address =
    #p2p-peer-address =

    #p2p-peer-address = 172.2.0.100:9876
    #p2p-peer-address = 172.2.0.200:9876

    #Other Pub BP nodes
    #p2p-peer-address =
    #p2p-peer-address =


#2020


# alohaeosprod: GB, London
 p2p-peer-address = peer.main.alohaeos.com:9876

# atticlabeosb: UA, Kyiv
# p2p-peer-address = eosbp-0.atticlab.net:9876

# atticlabeosb: UA, Kyiv
# p2p-peer-address = eosbp-1.atticlab.net:9876

# eosamsterdam: FI, bnode
p2p-peer-address = mainnet.eosamsterdam.net:9876

# eoscannonchn: HK, Hong Kong
# p2p-peer-address = node1.eoscannon.io:59876

# eoscleanerbp: US, SV Node A-seed
 p2p-peer-address = seed.eoscleaner.com:9876

# eosdotwikibp: SG, Singapore
# p2p-peer-address = p2p.eos.wiki:39876

# eosflareiobp: US, GlobalDAC
p2p-peer-address = p2p.eosflare.io:9876

# eoslaomaocom: US, NewYork
 p2p-peer-address = fullnode.eoslaomao.com:443

# eoslaomaocom: US, NewYork
p2p-peer-address = mainnet.eoslaomao.com:443

# eosphereiobp: AU, Sydney
p2p-peer-address = peer1.eosphere.io:9876

# eosswedenorg: SE, Sweden
 p2p-peer-address = p2p.eossweden.org:9876

# okcapitalbp1: JP, Tokyo
 p2p-peer-address = eos.okpool.top:9876

# tokenika4eos: PL, Poland
 p2p-peer-address = api3.tokenika.io:9876

actor-blacklist = blacklistmee

#https://eoscorearbitration.io/wp-content/uploads/2018/07/ECAF_Arbitrator_Order_2018-06-19-AO-001.pdf
actor-blacklist = ge2dmmrqgene
actor-blacklist = gu2timbsguge
actor-blacklist = ge4tsmzvgege
actor-blacklist = gezdonzygage
actor-blacklist = ha4tkobrgqge
actor-blacklist = ha4tamjtguge
actor-blacklist = gq4dkmzzhege

#https://eoscorearbitration.io/wp-content/uploads/2018/07/ECAF_Arbitrator_Order_2018-06-22-AO-002.pdf
actor-blacklist = gu2teobyg4ge
actor-blacklist = gq4demryhage
actor-blacklist = q4dfv32fxfkx
actor-blacklist = ktl2qk5h4bor
actor-blacklist = haydqnbtgene
actor-blacklist = g44dsojygyge
actor-blacklist = guzdonzugmge
actor-blacklist = ha4doojzgyge
actor-blacklist = gu4damztgyge
actor-blacklist = haytanjtgige
actor-blacklist = exchangegdax
actor-blacklist = cmod44jlp14k
actor-blacklist = 2fxfvlvkil4e
actor-blacklist = yxbdknr3hcxt
actor-blacklist = yqjltendhyjp
actor-blacklist = pm241porzybu
actor-blacklist = xkc2gnxfiswe
actor-blacklist = ic433gs42nky
actor-blacklist = fueaji11lhzg
actor-blacklist = w1ewnn4xufob
actor-blacklist = ugunxsrux2a3
actor-blacklist = gz3q24tq3r21
actor-blacklist = u5rlltjtjoeo
actor-blacklist = k5thoceysinj
actor-blacklist = ebhck31fnxbi
actor-blacklist = pvxbvdkces1x
actor-blacklist = oucjrjjvkrom

#https://eoscorearbitration.io/wp-content/uploads/2018/07/ECAF-Temporary-Freeze-Order-2018-07-13-AO-003.pdf
actor-blacklist = neverlandwal
actor-blacklist = tseol5n52kmo
actor-blacklist = potus1111111

#https://eoscorearbitration.io/wp-content/uploads/2018/07/ECAF-Order-of-Emergency-Protection-2018-07-19-AO-004.pdf
actor-blacklist = craigspys211

#https://eoscorearbitration.io/wp-content/uploads/2018/08/ECAF-Order-of-Emergency-Protection-2018-08-07-AO-005.pdf
actor-blacklist = eosfomoplay1

#https://eoscorearbitration.io/wp-content/uploads/2018/08/ECAF-Order-of-Emergency-Protection-2018-08-28-AO-006.pdf
actor-blacklist = wangfuhuahua

#https://eoscorearbitration.io/wp-content/uploads/2018/09/ECAF-Order-of-Emergency-Protection-2018-09-07-AO-008.pdf
#https://eoscorearbitration.io/wp-content/uploads/2018/09/ECAF-Order-of-Emergency-Protection-2018-09-24-AO-010.pdf
#actor-blacklist = ha4timrzguge
actor-blacklist = guytqmbuhege

#https://eoscorearbitration.io/wp-content/uploads/2018/09/ECAF-Order-of-Emergency-Protection-2018-09-09-AO-009.pdf
actor-blacklist = huobldeposit

#https://eoscorearbitration.io/wp-content/uploads/2018/09/ECAF-Order-of-Emergency-Protection-2018-09-25-AO-011.pdf
actor-blacklist = gm3dcnqgenes
actor-blacklist = gm34qnqrepqt
actor-blacklist = gt3ftnqrrpqp
actor-blacklist = gtwvtqptrpqp
actor-blacklist = gm31qndrspqr
actor-blacklist = lxl2atucpyos

#https://eoscorearbitration.io/wp-content/uploads/2018/10/ECAF-Order-of-Emergency-Protection-2018-10-05-AO-012.pdf
actor-blacklist = g4ytenbxgqge
actor-blacklist = jinwen121212
actor-blacklist = ha4tomztgage
actor-blacklist = my1steosobag
actor-blacklist = iloveyouplay
actor-blacklist = eoschinaeos2
actor-blacklist = eosholderkev
actor-blacklist = dreams12true
actor-blacklist = imarichman55

#https://eoscorearbitration.io/wp-content/uploads/2018/10/ECAF-Order-of-Emergency-Protection-2018-10-05-AO-013.pdf
actor-blacklist = gizdcnjyg4ge

#https://eoscorearbitration.io/wp-content/uploads/2018/10/ECAF-Order-of-Emergency-Protection-2018-10-12-AO-014.pdf
actor-blacklist = gyzdmmjsgige

#https://eoscorearbitration.io/wp-content/uploads/2018/10/ECAF-Order-of-Emergency-Protection-2018-10-13-AO-015.pdf
actor-blacklist = guzdanrugene
actor-blacklist = earthsop1sys

#https://eoscorearbitration.io/wp-content/uploads/2018/10/ECAF-Order-of-Emergency-Protection-2018-10-31-AO-017.pdf
actor-blacklist = refundwallet
actor-blacklist = jhonnywalker
actor-blacklist = alibabaioeos
actor-blacklist = whitegroupes
actor-blacklist = 24cryptoshop
actor-blacklist = minedtradeos

#Manual at 2019.02.22 (MainNet gropup)
actor-blacklist = newdexmobapp
actor-blacklist = ftsqfgjoscma
actor-blacklist = hpbcc4k42nxy
actor-blacklist = 3qyty1khhkhv
actor-blacklist = xzr2fbvxwtgt
actor-blacklist = myqdqdj4qbge
actor-blacklist = shprzailrazt
actor-blacklist = qkwrmqowelyu
actor-blacklist = lhjuy3gdkpq4
actor-blacklist = lmfsopxpr324
actor-blacklist = lcxunh51a1gt
actor-blacklist = geydddsfkk5e
actor-blacklist = pnsdiia1pcuy
actor-blacklist = kwmvzswquqpb
actor-blacklist = guagddoefdqu
http-max-response-time-ms = 500

**Comment by heifner** [comment]
`received go_away_message, reason = wrong chain`
You need to provide a EOS mainnet `genesis.json` file?

**Comment by zengchengshan** [comment]
root@bc607b692a77:/data# cat data/genesis.json 
{
  "initial_timestamp": "2018-06-08T08:08:08.888",
  "initial_key": "EOS7EarnUhcyYqmdnPon8rm7mBCTnBoot6o7fE2WzjvEX2TdggbL3",
  "initial_configuration": {
    "max_block_net_usage": 1048576,
    "target_block_net_usage_pct": 1000,
    "max_transaction_net_usage": 524288,
    "base_per_transaction_net_usage": 12,
    "net_usage_leeway": 500,
    "context_free_discount_net_usage_num": 20,
    "context_free_discount_net_usage_den": 100,
    "max_block_cpu_usage": 200000,
    "target_block_cpu_usage_pct": 1000,
    "max_transaction_cpu_usage": 150000,
    "min_transaction_cpu_usage": 100,
    "max_transaction_lifetime": 3600,
    "deferred_trx_expiration_window": 600,
    "max_transaction_delay": 3888000,
    "max_inline_action_size": 4096,
    "max_inline_action_depth": 4,
    "max_authority_depth": 6
  }
}

**Comment by heifner** [comment]
First run should be with --delete-all-blocks and --genesis-json

./start.sh --delete-all-blocks --genesis-json genesis.json

**Comment by zengchengshan** [comment]
you're great,the problem has solved,thank you very much.
