### ISSUE TITLE
Testnet failed:  Error 3050003: eosio_assert_message assertion failure

### ISSUE THREAD

**Issue by yanyiwu** [EOSIO/eos#9037]
```
cleos -u https://api.testnet.eos.io push action eosio.token transfer '{"from":"zbldzychiboa", "to":"lxhaduruvcio", "quantity":"0.001 TNT", "memo": "testnet blog in yanyiwu dot com"}' -p zbldzychiboa@owner
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: symbol precision mismatch
pending console output:
```

**Comment by yanyiwu** [comment]
what can i do ?

**Comment by dixia** [comment]
@yanyiwu Could you try if this work?

cleos -u https://api.testnet.eos.io push action eosio.token transfer '{"from":"zbldzychiboa", "to":"lxhaduruvcio", "quantity":"0.0001 TNT", "memo": "testnet blog in yanyiwu dot com"}' -p zbldzychiboa@owner

**Comment by jgiszczak** [comment]
Or for transferring the intended amount: `cleos -u https://api.testnet.eos.io push action eosio.token transfer '{"from":"zbldzychiboa", "to":"lxhaduruvcio", "quantity":"0.0010 TNT", "memo": "testnet blog in yanyiwu dot com"}' -p zbldzychiboa@owner`

The number of decimals specified in transfers must match the number of decimals with which the symbol was created.  If it was 4 decimals, as the examples demonstrate, the transfer must also be 4 decimals.

**Comment by yanyiwu** [comment]
@dixia @jgiszczak it works, but it is so weird, isn't it?

**Comment by dixia** [comment]
Personally I agree. It is counterintuitive from the usability aspect
