### ISSUE TITLE
database function error

### ISSUE THREAD

**Issue by gaoqiaizhanglan** [EOSIO/eos#905]
In hello.cpp  

struct model {
       uint64_t number;
       uint64_t name;
    };
typedef eosio::table<N(myscope), N(mycode), N(mytable), model, uint128_t> mytable;
model a { 1, N(one) };

void apply( uint64_t code, uint64_t action ) {
  mytable::store(a);
   }

When ./eoscpp -o hello.wast hello.cpp

There is an error : no member named 'store' in
      'eosio::table_impl<16, 0>'
      return impl::store( s, table_n, &r, sizeof(r) ) != 0;
             ~~~~~~^

**Comment by jgiszczak** [comment]
`eosio::table` has been completely rewritten as `eosio::multi_index`.
