### ISSUE TITLE
Launcher spawns child eosd process but ./eosc -p 8889 get info Fails

### ISSUE THREAD

**Issue by comtechnet** [EOSIO/eos#906]
![image](https://user-images.githubusercontent.com/5374172/33799067-38321a7c-dcf2-11e7-96a9-e89d5ed8b5b1.png)

I do NOT get the

adding hostname ip-XXX-XXX-XXX
found interface 127.0.0.1
found interface XXX.XX.XX.XX

but i do get the spawning child messages

**Comment by heifner** [comment]
Documentation updated.
