### ISSUE TITLE
long running transactions - eos testNet Build version: 6ec8cffc

### ISSUE THREAD

**Issue by Algibbs** [EOSIO/eos#908]
I ran:
./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":2560}' --scope currency,inita --permission currency@active
./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":2576}' --scope currency,inita --permission currency@active
./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":201}' --scope currency,inita --permission currency@active
./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":2456}' --scope currency,inita --permission currency@active
./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":2563}' --scope currency,inita --permission currency@active
./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":2504}' --scope currency,inita --permission currency@active
./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":345}' --scope currency,inita --permission currency@active
./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":2145}' --scope currency,inita --permission currency@active
./eosc push message currency transfer '{"from":"currency","to":"inita","quantity":2562}' --scope currency,inita --permission currency@active

Some of the transactions gave the following:
3537082ms            chain_controller.cpp:1035     validate_block_heade ] head_block_time 2017-12-10T05:58:54, next_block 2017-12-10T05:58:57, block_interval 1
3537102ms            chain_controller.cpp:1037     validate_block_heade ] Did not produce block within block_interval 1, took 3000ms)
3537103ms            chain_controller.cpp:208      _push_block          ] inith #21849 @2017-12-10T05:58:57  | 0 trx, 0 pending, exectime_ms=21
3537103ms            producer_plugin.cpp:246       block_production_loo ] inith generated block #21849 @ 2017-12-10T05:58:57 with 0 trxs  0 pending
3537981ms            wasm_interface.cpp:125        checktime            ] checktime called 247181
3538628ms            chain_controller.cpp:1035     validate_block_heade ] head_block_time 2017-12-10T05:58:57, next_block 2017-12-10T05:58:59, block_interval 1
3538628ms            chain_controller.cpp:1037     validate_block_heade ] Did not produce block within block_interval 1, took 2000ms)

**Comment by Justin-ye** [comment]
how to change the block_interval mare then 500ms?

**Comment by heifner** [comment]
No longer relevant.
