### ISSUE TITLE
Unable to install legacy MongoDB PHP driver on macOS Catalina

### ISSUE THREAD

**Issue by ukandun** [EOSIO/eos#9083]
I am following `https://www.php.net/manual/en/mongo.installation.php ` to install legacy MongoDB PHP driver on macOS Catalina. I need PHP5.6 to support my project.

I could able to run following
$ tar zxvf mongo-php-driver-legacy-<commit_id>.tar.gz
$ cd mongo-php-driver-legacy-<commit_id>
$ phpize
$ ./configure
but getting error at $ make all

Any help if much appreciated
Terminal text:
sudo make install                                                                                       
/bin/sh /usr/local/src/mongo-php-driver-legacy-master/libtool --mode=link cc -DPHP_ATOM_INC -I/usr/local/src/mongo-php-driver-legacy-master/include -I/usr/local/src/mongo-php-driver-legacy-master/main -I/usr/local/src/mongo-php-driver-legacy-master -I/usr/local/Cellar/php@5.6/5.6.40/include/php -I/usr/local/Cellar/php@5.6/5.6.40/include/php/main -I/usr/local/Cellar/php@5.6/5.6.40/include/php/TSRM -I/usr/local/Cellar/php@5.6/5.6.40/include/php/Zend -I/usr/local/Cellar/php@5.6/5.6.40/include/php/ext -I/usr/local/Cellar/php@5.6/5.6.40/include/php/ext/date/lib -I/usr/local/src/mongo-php-driver-legacy-master/api -I/usr/local/src/mongo-php-driver-legacy-master/util -I/usr/local/src/mongo-php-driver-legacy-master/exceptions -I/usr/local/src/mongo-php-driver-legacy-master/gridfs -I/usr/local/src/mongo-php-driver-legacy-master/types -I/usr/local/src/mongo-php-driver-legacy-master/batch -I/usr/local/src/mongo-php-driver-legacy-master/contrib -I/usr/local/src/mongo-php-driver-legacy-master/mcon -I/usr/local/src/mongo-php-driver-legacy-master/mcon/contrib -I/usr/local/Cellar/openssl/1.0.2t/include  -DHAVE_CONFIG_H  -g -O2 -arch i386 -arch x86_64 -mmacosx-version-min=10.5   -o mongo.la -export-dynamic -avoid-version -prefer-pic -module -rpath /usr/local/src/mongo-php-driver-legacy-master/modules  php_mongo.lo mongo.lo mongoclient.lo bson.lo cursor.lo command_cursor.lo cursor_shared.lo collection.lo db.lo io_stream.lo log_stream.lo contrib/crypto.lo contrib/php-json.lo contrib/php-ssl.lo gridfs/gridfs.lo gridfs/gridfs_cursor.lo gridfs/gridfs_file.lo gridfs/gridfs_stream.lo exceptions/exception.lo exceptions/connection_exception.lo exceptions/duplicate_key_exception.lo exceptions/cursor_exception.lo exceptions/protocol_exception.lo exceptions/cursor_timeout_exception.lo exceptions/execution_timeout_exception.lo exceptions/gridfs_exception.lo exceptions/result_exception.lo exceptions/write_concern_exception.lo types/bin_data.lo types/code.lo types/date.lo types/db_ref.lo types/id.lo types/int32.lo types/int64.lo types/regex.lo types/timestamp.lo util/log.lo util/pool.lo mcon/bson_helpers.lo mcon/collection.lo mcon/connections.lo mcon/manager.lo mcon/mini_bson.lo mcon/parse.lo mcon/read_preference.lo mcon/str.lo mcon/utils.lo mcon/contrib/md5.lo mcon/contrib/strndup.lo api/wire_version.lo api/write.lo api/batch.lo batch/write.lo batch/insert.lo batch/update.lo batch/delete.lo -Wl,-rpath,/usr/local/Cellar/openssl/1.0.2t/lib -L/usr/local/Cellar/openssl/1.0.2t/lib -lssl -lcrypto
cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/mongo.so -bundle  .libs/php_mongo.o .libs/mongo.o .libs/mongoclient.o .libs/bson.o .libs/cursor.o .libs/command_cursor.o .libs/cursor_shared.o .libs/collection.o .libs/db.o .libs/io_stream.o .libs/log_stream.o contrib/.libs/crypto.o contrib/.libs/php-json.o contrib/.libs/php-ssl.o gridfs/.libs/gridfs.o gridfs/.libs/gridfs_cursor.o gridfs/.libs/gridfs_file.o gridfs/.libs/gridfs_stream.o exceptions/.libs/exception.o exceptions/.libs/connection_exception.o exceptions/.libs/duplicate_key_exception.o exceptions/.libs/cursor_exception.o exceptions/.libs/protocol_exception.o exceptions/.libs/cursor_timeout_exception.o exceptions/.libs/execution_timeout_exception.o exceptions/.libs/gridfs_exception.o exceptions/.libs/result_exception.o exceptions/.libs/write_concern_exception.o types/.libs/bin_data.o types/.libs/code.o types/.libs/date.o types/.libs/db_ref.o types/.libs/id.o types/.libs/int32.o types/.libs/int64.o types/.libs/regex.o types/.libs/timestamp.o util/.libs/log.o util/.libs/pool.o mcon/.libs/bson_helpers.o mcon/.libs/collection.o mcon/.libs/connections.o mcon/.libs/manager.o mcon/.libs/mini_bson.o mcon/.libs/parse.o mcon/.libs/read_preference.o mcon/.libs/str.o mcon/.libs/utils.o mcon/contrib/.libs/md5.o mcon/contrib/.libs/strndup.o api/.libs/wire_version.o api/.libs/write.o api/.libs/batch.o batch/.libs/write.o batch/.libs/insert.o batch/.libs/update.o batch/.libs/delete.o  -L/usr/local/Cellar/openssl/1.0.2t/lib -lssl -lcrypto  -arch i386 -arch x86_64 -mmacosx-version-min=10.5 -Wl,-rpath -Wl,/usr/local/Cellar/openssl/1.0.2t/lib
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/bundle1.o, building for macOS-i386 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/openssl/1.0.2t/lib/libssl.dylib, building for macOS-i386 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/Cellar/openssl/1.0.2t/lib/libcrypto.dylib, building for macOS-i386 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd
ld: symbol dyld_stub_binding_helper not found, normally in crt1.o/dylib1.o/bundle1.o for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mongo.la] Error 1

**Comment by matthewdarwin** [comment]
I'm not sure what building MongoDB PHP has anything todo with EOSIO.  Seems off topic to me.
