### ISSUE TITLE
Nodeos occurs a problem, please help! 

### ISSUE THREAD

**Issue by tianwangchn** [EOSIO/eos#9093]
Hi guys,
I met a problem when I was running Nodeos. At the beginning, everything is ok and the blocks syn is fine. But, after about 3 hours I found I can't get block info from my node, so I went to check the Nodeos, I found this info and every info is all the same.

Dropping trx a84e9b759851540b65d75fd770040c48a7ae7547efd32c1a242b1ab49d98bb60, too many trx in progress 104878912 bytes

And my config.ini is like this,

    chain-state-db-size-mb = 65536
    reversible-blocks-db-size-mb = 2048
    contracts-console = false

    http-server-address = 192.168.1.2:8888
    p2p-listen-endpoint = 0.0.0.0:9876
    #p2p-server-address = !!YOUR_ENDPOINT_IP_ADDRESS!!:9876
    
    http-alias = 10000    
    http-validate-host = false
    verbose-http-errors = true  
    abi-serializer-max-time-ms = 2000  

    #may take a look
    chain-threads = 12
    http-threads = 24
    
    access-control-allow-origin = *
    access-control-allow-headers = Origin, X-Requested-With, Content-Type, Accept
    # access-control-max-age =
    # access-control-allow-credentials = false

    #wasm-runtime = wabt
    wasm-runtime = eos-vm-jit
    eos-vm-oc-enable = true

    #produce-time-offset-us = 250000
    last-block-time-offset-us = -300000

    chain-state-db-guard-size-mb = 128 
    reversible-blocks-db-guard-size-mb = 2
    
    p2p-max-nodes-per-host = 150

    # actor-whitelist =
    # actor-blacklist =
    # contract-whitelist =
    # contract-blacklist =
    # filter-on =

    allowed-connection = any

    max-clients = 150
    connection-cleanup-period = 30
    #network-version-match = 0
    sync-fetch-span = 500
    enable-stale-production = false

    pause-on-startup = false
    max-transaction-time = 30
    max-irreversible-block-age = -1
    txn-reference-block-lag = 0
    
    plugin = eosio::chain_api_plugin
    #plugin = eosio::history_plugin
    #plugin = eosio::history_api_plugin
    plugin = eosio::chain_plugin
    #plugin = eosio::net_plugin
    #plugin = eosio::net_api_plugin
    plugin = eosio::http_plugin

    p2p-peer-address = peer.main.alohaeos.com:9876 #
    p2p-peer-address = p2p.eosargentina.io:5222 #

    p2p-peer-address = eosbp-0.atticlab.net:9876 #
    p2p-peer-address = p2p.eosflare.io:9876
    p2p-peer-address = p2p-emlg.eosnairobi.io:9076
    p2p-peer-address = p2p.eossweden.org:9876
    p2p-peer-address = publicnode.cypherglass.com:9876 #
    p2p-peer-address = eos-bp.inbex.pro:9876

Please help me, thanks a lot!

**Comment by heifner** [comment]
This is an indication that your node is not keeping up with all the incoming transactions into it.

**Comment by tianwangchn** [comment]
> This is an indication that your node is not keeping up with all the incoming transactions into it.

Hi heifner, 
Thanks for your response. Is that a hardware defect? My server's CPU is 8c16t up to 4.2GHz.

**Comment by heifner** [comment]
Do you know how many peers are connected to you? Are you servicing a lot of http requests? What version of eosio are you running? Are you running on a SSD? How much physical RAM do you have?

**Comment by tianwangchn** [comment]
> Do you know how many peers are connected to you? Are you servicing a lot of http requests? What version of eosio are you running? Are you running on a SSD? How much physical RAM do you have?

Hi heifner,
Thank u very much. 
There is no peer connected to me;
Yes, I'm servicing a lot of http requests for stress testing, it is about 1000 requests per second;
The version of eosio is v2.0.5-de78b49b5765c88f4e005046d1489c3905985b94;
Yes, I use a M.2 SSD;
The RAM size is 8GB.

What's more, I set "net-threads = 8" and it works well now.

**Comment by tianwangchn** [comment]
Set "net-threads = 8" does not solve this issue. Reducing http requests to 200 times per second seems works.
