### ISSUE TITLE
ERROR 3050003 when erasing a table

### ISSUE THREAD

**Issue by LuminousXLB** [EOSIO/eos#9105]
I've got a Smart Contract Named `izsjtpjbqtxy` on [testnet](https://testnet.eos.io/)

It has an action as below, which is used to clear the whole table.
[Here](https://pastebin.com/QbR3T044) is the full code.
```cpp
    [[eosio::action]] void erase(uint64_t nonce)
    {
        auto it = session_table.begin();

        while (it != session_table.end()) {
            session_table.erase(it);
            it = session_table.begin();
        }
        
        print(nonce);
    }

```

I was trying to invoke this action with payload

``` json
{
    "nonce": 1927
}
```
Here's the request body
```json
{
    "signatures": [
        "SIG_K1_KX1UKQbo6bA3TtbRgXfrDVRZPGCyudMgTaJCKr8xoJYKw2stLJ6ntdHxwsJ1HNTaaRrqBR5UYENx9nJ6R7c4XERAssxzaJ"
    ],
    "compression": 0,
    "packed_context_free_data": "",
    "packed_trx": "dd3dc25ef41d04fc201e0000000001e07bb6e7d5fcf077000000000085cd5501e07bb6e7d5fcf07700000000a8ed323208870700000000000000"
}
```

But it returned
```json
{
    "code": 500,
    "message": "Internal Service Error",
    "error": {
        "code": 3050003,
        "name": "eosio_assert_message_exception",
        "what": "eosio_assert_message assertion failure",
        "details": [
            {
                "message": "assertion failure with message: get",
                "file": "wasm_interface.cpp",
                "line_number": 1075,
                "method": "eosio_assert"
            },
            {
                "message": "pending console output: ",
                "file": "apply_context.cpp",
                "line_number": 113,
                "method": "exec_one"
            }
        ]
    }
}
```

I've tried many different modifications, but all failed.

**Comment by swang-b1** [comment]
I did a simple test with your code. transaction id is : 562F97AB8E70B2EF2F177BAE0DA46FC09E7224577E87CC03D4808841B03054B1 

it works well

**Comment by LuminousXLB** [comment]
> I did a simple test with your code. transaction id is : 562F97AB8E70B2EF2F177BAE0DA46FC09E7224577E87CC03D4808841B03054B1
> 
> it works well

Thanks for your work!

I tried to push some data to your contract, and it works indeed.
But I still can't get it run on my own contract.
Maybe there's something wrong on the history of this contract?

**Comment by jawadhaxan007** [comment]
hi @LuminousXLB 
Did you modify your table structure? because you cannot erase data after modifying the structure.

If you modified then revert it to the previous structure, then erase data, then modify the structure.

**Comment by LuminousXLB** [comment]
Yes I modified the structure sometime.
That should be the reason...

Thanks a lot
