### ISSUE TITLE
Transactions overlap

### ISSUE THREAD

**Issue by jawadhaxan007** [EOSIO/eos#9106]
I made two transactions with a time gap of almost 94 seconds. First transaction made a change in table, then while in second transaction that change was not in that table.

First transaction hash: 6094dacd4e7ba052de8cc35a529a7c6cedc575d9f58c16c7493bd7271d46cd20

Second transaction hash: eb488e34c31596826904f4fdff597efb131eed2e70ecb9ea55ae1d4ce97a6431

Table name: dealers

For reference 
Here in first transaction the value of “lastcall” has been changed.
![FF9B0A8E-B280-4BAE-ACEB-A66287BAD081](https://user-images.githubusercontent.com/37640184/82192346-4d604200-990d-11ea-94af-ecc2a5ecd65e.jpeg)

Here in second transaction, there is no change!!
![7984677D-946E-4630-920E-D4C626B746B6](https://user-images.githubusercontent.com/37640184/82192357-5224f600-990d-11ea-9459-166d8a42d971.jpeg)

Please address if this is a problem with eosio blockchain or something else?

Thanks

**Comment by dixia** [comment]
hi jawadhaxan007,

on which chain did you sent these two transactions? Are you sure the first transaction was successful?

**Comment by jawadhaxan007** [comment]
hi @dixia  
I sent on MainNet chain and yes, the first transaction was successful. I have shared the trx hash of both transactions as well, you can check. 

Thanks

**Comment by heifner** [comment]
The first transaction has one action `updatedealer`. The second transaction has one action `transfer`. Would require reviewing the contract code to determine why one action modifies the table and the other does not.

**Comment by jawadhaxan007** [comment]
yes, I got the problem.
The smart was modifying the same table two times within the same transaction.
