### ISSUE TITLE
Issue with eoscpp No such file under /usr/local/share/skeleton/.

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eos#911]
Error message after `eoscpp -n hello`
`cp: /usr/local/share/skeleton/.: No such file or directory`

**Comment by zhangchiqing** [comment]
I also have this problem. How to resolve?

**Comment by zhangchiqing** [comment]
Figured out:

```
cd ~/eos/build/
sudo make install
```

**Comment by EcutDavid** [comment]
@zhangchiqing thanks! Works for me too, although it doesn't need `sudo`...

**Comment by Babaloncryptolog** [comment]
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Doxygen not found.  Contract documentation will not be generated.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EOS_LIBBSONCXX
    linked by target "db_plugin" in directory /root/eos/plugins/db_plugin
EOS_LIBMONGOCXX
    linked by target "db_plugin" in directory /root/eos/plugins/db_plugin

-- Configuring incomplete, errors occurred!
See also "/root/eos/build/CMakeFiles/CMakeOutput.log".

**Comment by flyer88** [comment]
I also have  `cp: /usr/local/share/eosio/skeleton/.: No such file or directory`  error message

`sudo make install`  not work

**Comment by mahanlin** [comment]
> I also have `cp: /usr/local/share/eosio/skeleton/.: No such file or directory` error message
> 
> `sudo make install` not work

try this:
cd eos/build/tools
./eosiocpp -n yourappname
