### ISSUE TITLE
Are these expired deferred trxs abusing system resources? 

### ISSUE THREAD

**Issue by moneyoriented** [EOSIO/eos#9130]
It seems there are quite a lot of expired deferred trxs that won't consume any net or cpu resources. Are they abuse the chain resource?

https://bloks.io/transaction/4f455bd68a11fef1b34c69e1f8b407e9171ed17ec2e61b9abd1555200015af7b

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/57709244/82855295-8320ae80-9f3d-11ea-87df-527e58f08cd5.png">

**Comment by aclark-b1** [comment]
Yes, but the resources consumed by deferred transactions are extremely negligible.  Our PBE group is actively researching options for the future of this feature.
