### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by grantrepository** [EOSIO/eos#9138]
- get this source from release file.

- when to build eos, this is no documents about how to build from this. 
this is a issue to get _submodule_ .

**Comment by spoonincode** [comment]
You can't build from the .tar.gz file. You must do a `git clone`. (sadly Github does not offer a way for us to disable the .tar.gz file)

See https://developers.eos.io/manuals/eos/latest/install/build-from-source/index for documentation

**Comment by grantrepository** [comment]
thanks .
