### ISSUE TITLE
Feature request: automatic data retention

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#9139]
In many cases an application server needs a nodeos with or without state history, but it does not need the historical data. And some networks like EOS are growing quite fast. 

So, there is a need to keep the storage footprint limited and not growing limitlessly.

There are two growing components: blocks log and state history. 

POSIX filesystem operations don't offer a possibility to trim a file from the start, leaving some data at the end, without having to copy the remaining data. So, the only way for data retention is to start writing a new log file, and then later delete the old ones.

The new feature should define the size limit of blocks log and state history log files, and the number of files to keep, so that new files get automatically opened when the size exceeds the threshold, and deleted when there's more files than required. 

This feature will need a new kind of metadata file that refers to those partial log files, so that nodeos can access them when needed.

**Comment by matthewdarwin** [comment]
see also https://github.com/EOSIO/eos/issues/6703

**Comment by cc32d9** [comment]
@matthewdarwin that one is too unstructured and not proposing an approach. I'm trying to be more focused on one problem and its solution.

**Comment by kryton** [comment]
as for purging files, I don't think this should be part of the feature, and left for scripts/sysadmin to implement.
eg. for when they are moved to cold-storage

I would also suggest you have a time-based logic.
ie.. new file ever 24 hours or when size exceeds 1G.

**Comment by cc32d9** [comment]
@kryton nodeos needs to know which files are available, because it still needs to answer historical requests, such as `get_block` or state history requests. So it should also control the deletion.

I would actually be able to implement the feature myself, if there were a feature bounty at B1

**Comment by cc32d9** [comment]
or it can indicate files as unused and let an external process take care of purging

**Comment by gituser** [comment]
> @matthewdarwin that one is too unstructured and not proposing an approach. I'm trying to be more focused on one problem and its solution.

Instead of creating a new issue you could add more info into the initial issue I've submitted, making duplicate issues on the same subject doesn't help.

The issue has been stale since 2019, finally there is some attention to the subject because of the massive EOS blockchain overgrowth.

I'd propose limiting number of recent blocks instead of limiting by size, most PoS based blockchains, e.g. Stellar or XRP doing it this way (number of ledgers).

**Comment by cc32d9** [comment]
splitting the files by number of blocks, like every million blocks is also possible. Probably also cheaper in terms of nodeos CPU effort.

**Comment by sanaraufx** [comment]
Has this enhancement request been addressed with the strides functionality introduced in blocks log and state history in combination with the ability to use snapshots?

**Comment by matthewdarwin** [comment]
The features in nodeos 2.1 seem to address this issue from my perspective.

**Comment by sanaraufx** [comment]
Great! In that case, I'll close this issue for now. Feel free to reopen if there are any additional considerations or related issues.
