### ISSUE TITLE
Missing  eosio_build.sh

### ISSUE THREAD

**Issue by zodiacoder** [EOSIO/eos#9188]
Hi guys. Any help is appreciated. I'm trying to set up an EOS node using Ubuntu VirtualBox on my Windows machine. 
I have installed everything needed so far but after running git clone https://github.com/eosio/eos --recursive, I enter ls into the terminal and see eos, great then cd eos, then ls, then the screenshot shows what I'm seeing...no eosio_build.sh. 
Anyone know whats going wrong? This is driving me mad!!!
Thanks all. 
![eosioscreenshot](https://user-images.githubusercontent.com/66304691/83949790-9c6b0a00-a81d-11ea-8680-f319b336098f.PNG)

**Comment by kryton** [comment]
This is not the correct place to ask for help.
have a look here for community support - https://developers.eos.io/welcome/latest/resources/index/#eosio-developers-community

here is the documentation on how to build EOSIO from source code.

https://developers.eos.io/manuals/eos/latest/install/build-from-source/shell-scripts/build-eosio-binaries (it's in the scripts directory, but you should follow the instructions)

although you may want to try docker or the EOSIO testnet - https://testnet.eos.io/

**Comment by zodiacoder** [comment]
No worries. Thanks for helping.
