### ISSUE TITLE
ubuntu build script seems not work. 

### ISSUE THREAD

**Issue by swang-b1** [EOSIO/eos#9191]
[Ensuring CMAKE installation]
 - CMAKE found @ /usr/bin/cmake.

[Ensuring Boost 1.71.0 library installation]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    10  100    10    0     0     13      0 --:--:-- --:--:-- --:--:--    13
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by swang-b1** [comment]
wget  https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2
--2020-06-08 07:19:20--  https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2
Resolving dl.bintray.com (dl.bintray.com)... 54.148.239.199, 35.161.162.245
Connecting to dl.bintray.com (dl.bintray.com)|54.148.239.199|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-06-08 07:19:21 ERROR 403: Forbidden.

**Comment by zma** [comment]
You may try to apply this patch here https://github.com/EOSIO/eos/issues/9189

**Comment by nksanthosh** [comment]
This is not reproducible right now.
