### ISSUE TITLE
本地测试链启动后，再启动一个节点无法同步

### ISSUE THREAD

**Issue by Tinide** [EOSIO/eos#9197]
operator()           ] Peer closed connection
error 2020-06-11T09:38:02.279 net-1     net_plugin.cpp:2369           operator()           ] Closing connection to: 192.168.246.131:9010
info  2020-06-11T09:38:02.279 net-1     net_plugin.cpp:943            _close               ] closing '192.168.246.131:9010', 192.168.246.131:9010
info  2020-06-11T09:38:02.380 net-0     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
info  2020-06-11T09:38:32.382 net-1     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
info  2020-06-11T09:38:32.382 net-0     net_plugin.cpp:2141           operator()           ] host: 192.168.246.131 port: 9010 
info  2020-06-11T09:38:32.383 net-1     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to 192.168.246.131:9010, lib 1, head 1, id 06d828618f622d4c
info  2020-06-11T09:38:32.383 net-1     net_plugin.cpp:2350           operator()           ] Peer closed connection
error 2020-06-11T09:38:32.383 net-1     net_plugin.cpp:2369           operator()           ] Closing connection to: 192.168.246.131:9010
info  2020-06-11T09:38:32.383 net-1     net_plugin.cpp:943            _close               ] closing '192.168.246.131:9010', 192.168.246.131:9010
info  2020-06-11T09:38:32.383 net-1     net_plugin.cpp:1121           operator()           ] async write socket closed before callback: 192.168.246.131:9010
info  2020-06-11T09:38:32.383 net-1     net_plugin.cpp:943            _close               ] closing '192.168.246.131:9010', 192.168.246.131:9010
info  2020-06-11T09:38:32.484 net-0     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
info  2020-06-11T09:39:02.484 net-1     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
info  2020-06-11T09:39:02.484 net-0     net_plugin.cpp:2141           operator()           ] host: 192.168.246.131 port: 9010 
info  2020-06-11T09:39:02.484 net-1     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to 192.168.246.131:9010, lib 1, head 1, id 06d828618f622d4c
info  2020-06-11T09:39:02.484 net-1     net_plugin.cpp:2350           operator()           ] Peer closed connection
error 2020-06-11T09:39:02.484 net-1     net_plugin.cpp:2369           operator()           ] Closing connection to: 192.168.246.131:9010
info  2020-06-11T09:39:02.484 net-1     net_plugin.cpp:943            _close               ] closing '192.168.246.131:9010', 192.168.246.131:9010
info  2020-06-11T09:39:02.586 net-0     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
info  2020-06-11T09:39:32.586 net-1     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
info  2020-06-11T09:39:32.587 net-0     net_plugin.cpp:2141           operator()           ] host: 192.168.246.131 port: 9010 
info  2020-06-11T09:39:32.588 net-1     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to 192.168.246.131:9010, lib 1, head 1, id 06d828618f622d4c
info  2020-06-11T09:39:32.588 net-1     net_plugin.cpp:2350           operator()           ] Peer closed connection
error 2020-06-11T09:39:32.588 net-1     net_plugin.cpp:2369           operator()           ] Closing connection to: 192.168.246.131:9010
info  2020-06-11T09:39:32.588 net-1     net_plugin.cpp:943            _close               ] closing '192.168.246.131:9010', 192.168.246.131:9010
info  2020-06-11T09:39:32.589 net-1     net_plugin.cpp:1121           operator()           ] async write socket closed before callback: 192.168.246.131:9010
info  2020-06-11T09:39:32.589 net-1     net_plugin.cpp:943            _close               ] closing '192.168.246.131:9010', 192.168.246.131:9010
info  2020-06-11T09:39:32.689 net-0     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
info  2020-06-11T09:40:02.690 net-1     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
info  2020-06-11T09:40:02.690 net-0     net_plugin.cpp:2141           operator()           ] host: 192.168.246.131 port: 9010 
info  2020-06-11T09:40:02.691 net-1     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to 192.168.246.131:9010, lib 1, head 1, id 06d828618f622d4c
info  2020-06-11T09:40:02.691 net-1     net_plugin.cpp:2350           operator()           ] Peer closed connection
error 2020-06-11T09:40:02.691 net-1     net_plugin.cpp:2369           operator()           ] Closing connection to: 192.168.246.131:9010
info  2020-06-11T09:40:02.692 net-1     net_plugin.cpp:943            _close               ] closing '192.168.246.131:9010', 192.168.246.131:9010
info  2020-06-11T09:40:02.692 net-1     net_plugin.cpp:1121           operator()           ] async write socket closed before callback: 192.168.246.131:9010
info  2020-06-11T09:40:02.692 net-1     net_plugin.cpp:943            _close               ] closing '192.168.246.131:9010', 192.168.246.131:9010
info  2020-06-11T09:40:02.793 net-0     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1

**Comment by mharrisb1** [comment]
For context, title roughly translates to

> After the local test chain is started, another node cannot be synchronized

**Comment by Tinide** [comment]
> 对于某些，标题大致翻译为
> 
> > 启动本地测试链后，无法同步另一个第三方

yes ,why?

**Comment by rise-worlds** [comment]
change your config.ini `p2p-max-nodes-per-host` count.

**Comment by Tinide** [comment]
> 更改您的config.ini `p2p-max-nodes-per-host`计数。

yes,ok
