### ISSUE TITLE
MacOS 10.12.6 doc error and eoscpp hello does not work

### ISSUE THREAD

**Issue by comtechnet** [EOSIO/eos#921]
I've now run both the single test node and have started the 2 local production nodes per the MacOS 10.12.6 installation doc.

There is a typo in the doc that reads ...

To confirm the nodes are running, run following eosc commands:

~/eos/build/programs/eosc
./eosc -p 8888 get info
./eosc -p 8889 get info

I believe the first line should be ...

cd ~/eos/build/programs/eosc

-------------------------------------------------------

The docs says I should get ...

adding hostname ip-XXX-XXX-XXX
found interface 127.0.0.1
found interface XXX.XX.XX.XX
spawning child, programs/eosd/eosd --skip-transaction-signatures --data-dir tn_data_0
spawning child, programs/eosd/eosd --skip-transaction-signatures --data-dir tn_data_1

but instead I do NOT get the first three lines at all and the spawning child lines read ...

spawning child, programs/eosd/eosd --skip-transaction-signatures --enable-stale-production true --data-dir tn_data_00
spawning child, programs/eosd/eosd --skip-transaction-signatures --data-dir tn_data_01

-------------------------------------------------------

So I've moved on to testing creating sample contracts.  But, right away the first step fails ...

For this to work we assume you have installed the eosio/eos code installed and that ${CMAKE_INSTALL_PREFIX}/bin is in your path.

$ eoscpp -n hello
$ cd hello
$ ls

I assume that my CMAKE_INSTALL_PREFIX is empty due to the suggestion of ...

cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=.. -DLLVM_TARGETS_TO_BUILD= -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=WebAssembly -DCMAKE_BUILD_TYPE=Release ../
make -j4 install

even tho I went back and did the MacOS 10.12.6 standard install of ...

cd eos
./build.sh darwin

If I"m wrong - what should I put in the path that is different that what ./build.sh darwin creates or that I've got in my path.  Even tho I'm not sure what ./build.sh darwin makes, since the clean installs implies that -DCMAKE_INSTALL_PREFIX=..  does that mean it is empty/ null or that nothing preceeds the /user/local/bin (which is already in my path).

Pls advise

**Comment by JamesKnippel** [comment]
Hey! 

Try running 
`sudo cmake install `
in your` eos/build/programs` folder
and in each of these below:
```
/eosc
/eosd
/eos-walletd
```

**Comment by comtechnet** [comment]
James

Thks for the email / but ur response invites another question ...

What does going to a directory
cd ~/eos/build/programs

and then doing sudo cmake install
actually do?

Does it add to my path?  If so how and what?

Seems confusing / something should b documented 

Dave

**Comment by yao23** [comment]
Not this one:
```
cd ~/eos/build/programs
sudo cmake install
```

Actually the following code works for me:
```
cd ~/eos/build
sudo make install
```

**Comment by gleehokie** [comment]
We have totally rewritten the build system and updated the documentation.  I'm closing this issue as I think we've covered these issues.  Reopen if you have more questions.
