### ISSUE TITLE
Node Peer Stuck In head_catchup after LIB Fails To Update

### ISSUE THREAD

**Issue by baxterjfinch** [EOSIO/eos#9214]
Private network has 1 producer (EOSIO) and a state-history node (EOSIO-HISTORY) connected to the producer. The state-history node fails to update LIB for some reason and then falls behind the producer node. It then goes into a head_catchup state and blocks no longer are received from the producer. Steps and logs are below:

1.)  EOSIO-HISTORY doesn’t return verification back to EOSIO that it received block 18535515 Log from EOSIO-HISTORY node:
`"debug 2020-06-05T14:10:51.892 net-0     net_plugin.cpp:1969           operator()           ] not bcast block 18535515 to eosio-595d8f4544-hmh2x:9876 - a08f187`

 2.) EOSIO sends handshake message to EOSIO-HISTORY with lib at 18535515 

Log from EOSIO node:
` textPayload: "info  2020-06-05T14:10:51.892 net-1     net_plugin.cpp:1070           operator()           ] Sending handshake generation 98 to eosio-history-578f9677fd-zpqlp:9876 - 36c194e, lib 18535515, head 18535517, id 4eee70afb9e66e36`

3.) EOSIO closes connection because handshake response from EOSIO-HISTORY shows that the received block from EOSIO-HISTORY is less than the lib sent in the handshake.  

`textPayload: "info  2020-06-05T14:10:51.893 net-1     net_plugin.cpp:943            _close               ] closing '', 10.215.25.193:47774`

4.) .) EOSIO-HISTORY handles handshake and sees that EOSIO lib is greater than it’s current lib and so calls verify_catchup in net_plugin.cpp

https://github.com/EOSIO/eos/blob/c6a7ec0dd816f98a6840f59dca9fed04efd9f7a5/plugins/net_plugin/net_plugin.cpp#L1629

And from EOSIO-HISTORY node:
`textPayload: "info  2020-06-05T14:10:51.894 net-0     net_plugin.cpp:1632           recv_handshake       ] handshake from eosio-595d8f4544-hmh2x:9876 - a08f187, lib 18535515, head 18535517, head id 4eee70afb9e66e36.. sync 3`

5.) `verify_catchup` sees that sync state is set to in sync

6.) in net_plugin.cpp `sync_manager::set_state` is called and changes old_state (in sync) to new state (head catchup). 

`textPayload: "info  2020-06-05T14:10:51.894 net-0     net_plugin.cpp:1379           set_state            ] old state in sync becoming head catchup`

7.) EOSIO-HISTORY closes connection to EOSIO:

` textPayload: "error 2020-06-05T14:10:51.895 net-0     net_plugin.cpp:2369           operator()           ] Closing connection to: eosio-595d8f4544-hmh2x:9876 - a08f187`

8.) EOSIO attempts to re-establish connection with EOSIO-HISTORY this time over port 9877 and fails 

`textPayload: "debug 2020-06-05T14:10:51.901 net-1     net_plugin.cpp:1947           operator()           ] ["eosio-history.testnet:9877" :]socket_is_open false, connecting false, syncing false`

9.) Logs from EOSIO-HISTORY now only show the following:

```
debug 2020-06-17T01:01:58.064 net-1     net_plugin.cpp:2690           handle_message       ] ["eosio-595d8f4544-hmh2x:9876 - a08f187" 10.216.21.216:9876]received time_message
debug 2020-06-17T01:01:59.712 net-0     net_plugin.cpp:1929           expire_txns          ] expire_local_txns size 0 removed 0
debug 2020-06-17T01:01:59.712 net-0     net_plugin.cpp:3047           expire               ] expire_txns 82us
info  2020-06-17T01:02:00.261 net-1     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
debug 2020-06-17T01:02:00.262 net-1     net_plugin.cpp:3091           connection_monitor   ] connection monitor, removed 0 connections
debug 2020-06-17T01:02:02.712 net-0     net_plugin.cpp:1929           expire_txns          ] expire_local_txns size 0 removed 0
debug 2020-06-17T01:02:02.712 net-0     net_plugin.cpp:3047           expire               ] expire_txns 96us
debug 2020-06-17T01:02:05.713 net-1     net_plugin.cpp:1929           expire_txns          ] expire_local_txns size 0 removed 0
debug 2020-06-17T01:02:05.713 net-1     net_plugin.cpp:3047           expire               ] expire_txns 83us
debug 2020-06-17T01:02:08.713 net-0     net_plugin.cpp:1929           expire_txns          ] expire_local_txns size 0 removed 0
debug 2020-06-17T01:02:08.713 net-0     net_plugin.cpp:3047           expire               ] expire_txns 85us
debug 2020-06-17T01:02:11.713 net-1     net_plugin.cpp:1929           expire_txns          ] expire_local_txns size 0 removed 0
debug 2020-06-17T01:02:11.713 net-1     net_plugin.cpp:3047           expire               ] expire_txns 83us
debug 2020-06-17T01:02:14.713 net-0     net_plugin.cpp:1929           expire_txns          ] expire_local_txns size 0 removed 0
debug 2020-06-17T01:02:14.713 net-0     net_plugin.cpp:3047           expire               ] expire_txns 84us
debug 2020-06-17T01:02:17.713 net-1     net_plugin.cpp:1929           expire_txns          ] expire_local_txns size 0 removed 0
debug 2020-06-17T01:02:17.714 net-1     net_plugin.cpp:3047           expire               ] expire_txns 352us
debug 2020-06-17T01:02:20.714 net-0     net_plugin.cpp:1929           expire_txns          ] expire_local_txns size 0 removed 0
debug 2020-06-17T01:02:20.714 net-0     net_plugin.cpp:3047           expire               ] expire_txns 100us
debug 2020-06-17T01:02:23.714 net-1     net_plugin.cpp:1929           expire_txns          ] expire_local_txns size 0 removed 0
debug 2020-06-17T01:02:23.714 net-1     net_plugin.cpp:3047           expire               ] expire_txns 85us
debug 2020-06-17T01:02:24.206 net-1     net_plugin.cpp:765            operator()           ] handle time_message
debug 2020-06-17T01:02:24.206 net-1     net_plugin.cpp:2690           handle_message       ] ["eosio-595d8f4544-hmh2x:9876 - a08f187" 10.216.21.216:9876]received time_message
debug 2020-06-17T01:02:26.715 net-0     net_plugin.cpp:1929           expire_txns          ] expire_local_txns size 0 removed 0
debug 2020-06-17T01:02:26.715 net-0     net_plugin.cpp:3047           expire               ] expire_txns 84us
debug 2020-06-17T01:02:29.715 net-1     net_plugin.cpp:1929           expire_txns          ] expire_local_txns size 0 removed 0
debug 2020-06-17T01:02:29.715 net-1     net_plugin.cpp:3047           expire               ] expire_txns 96us
debug 2020-06-17T01:02:30.064 net-1     net_plugin.cpp:765            operator()           ] handle time_message
debug 2020-06-17T01:02:30.064 net-1     net_plugin.cpp:2690           handle_message       ] ["eosio-595d8f4544-hmh2x:9876 - a08f187" 10.216.21.216:9876]received time_message
info  2020-06-17T01:02:30.262 net-0     net_plugin.cpp:3090           connection_monitor   ] p2p client connections: 0/25, peer connections: 1/1
debug 2020-06-17T01:02:30.262 net-0     net_plugin.cpp:3091           connection_monitor   ] connection monitor, removed 0 connections
```

**Comment by aclark-b1** [comment]
Do you know if this is reproducible?  Were you able to get it unstuck, or did you have to wipe it out and start over?  Were you using binaries or did you build from source?  Also, what is your host OS?
