### ISSUE TITLE
question about augmented_transaction_trace in state_history_serialization.hpp

### ISSUE THREAD

**Issue by gzliudan** [EOSIO/eos#9237]
Here I find a problem, I'm not sure it's a bug:

In function:
datastream<ST>& operator<<(datastream<ST>& ds,
                           const history_context_wrapper<std::pair<uint8_t, bool>,
                                                         eosio::augmented_transaction_trace>& obj) 

https://github.com/EOSIO/eos/blob/master/plugins/state_history_plugin/include/eosio/state_history_plugin/state_history_serialization.hpp#L646

When if (trace.failed_dtrx_trace) is true, then call:
fc::raw::pack( ds, make_history_context_wrapper(
     obj.db, context, eosio::augmented_transaction_trace{trace.failed_dtrx_trace, obj.obj.partial})
);

It seems calling the function itself (https://github.com/EOSIO/eos/blob/master/plugins/state_history_plugin/include/eosio/state_history_plugin/state_history_serialization.hpp#L602), then falling into an infinite loop.

**Comment by b1bart** [comment]
The input for the parameter `obj` changes from `trace` to `trace.failed_dtrx_trace` on each recursive call.  This will descend into the nested structures until there is no longer a value for `trace.failed_dtrx_trace`.

Knowledge of the operations suggest this should not recurse more than once but even if it was not bounded by that, it would not be an infinite loop unless there was a cycle in the data structure.  

At this time, we do not suspect there is a bug here, just a recursive implementation
