### ISSUE TITLE
Split the state history file in chunks

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#9240]
There is a new feature committed to develop branch just now to split blocks.log in chunks. (https://github.com/EOSIO/eos/issues/8909, https://github.com/EOSIO/eos/pull/9184)  Thank you!

It would be good to allow state history to also be split in chunks similarly.

Probably can just split state history at the same frequency as blocks.

**Comment by sanaraufx** [comment]
Added into 2.1 release

**Comment by 13rac1** [comment]
[Change was listed in `v2.1.0-rc1` release notes](https://github.com/EOSIO/eos/blob/aec7f1ad7077b05e35808468db87134c00729ca9/docs/30_release-notes/99_v2.1.0-rc1.md#health-logging-for-nodeos-running-the-state-history-plugin-9208-9239-9277) and resolved in https://github.com/EOSIO/eos/pull/9277
