### ISSUE TITLE
Fatal: Repository "https://github.com/eosio/eos--recursive/"

### ISSUE THREAD

**Issue by winstonlou1** [EOSIO/eos#9260]
Hi, I'm trying to install EOSIO according to this article: 
https://medium.com/coinmonks/installing-eos-part-2-installing-eosio-883599e497ac 

and am having difficulties. I encountered the following error:
![image](https://user-images.githubusercontent.com/51255718/85947980-a39ab900-b980-11ea-8183-60df12e66038.png)

Will you be able to assist?

Thank you.

**Comment by matthewdarwin** [comment]
You are missing a space before "--recursive". 

```
git clone https://github.com/eosio/eos --recursive
```

**Comment by winstonlou1** [comment]
Thank you so much matthewdarwin

I encountered a new issue though:
![image](https://user-images.githubusercontent.com/51255718/86017333-81736a80-ba56-11ea-9a26-620520caca23.png)

What should I do?

**Comment by matthewdarwin** [comment]
Add more RAM to your server.

There are pre-built binaries available if you don't want to compile yourself. https://github.com/EOSIO/eos/releases/tag/v2.0.6 (scroll to bottom of page)

**Comment by winstonlou1** [comment]
The issue is that when I increase the ram, this error occurs:
![image](https://user-images.githubusercontent.com/51255718/86022071-73284d00-ba5c-11ea-883d-290b6651f688.png)

How do I install the pre-built binary?

**Comment by matthewdarwin** [comment]
Seems this is not an EOSIO code issue. Probably want to discuss in https://eosio.stackexchange.com/
