### ISSUE TITLE
Transaction Net Usage Is Too High: 136 > 0

### ISSUE THREAD

**Issue by Cosmo120** [EOSIO/eos#9266]
Hi, 

It's been a while since I've used this wallet. Can someone please explain to me how to change my usage limit step by step? I need to send my EOS to an exchange. 

Thanks!
<img width="827" alt="Screen Shot 2020-06-29 at 10 02 42 PM" src="https://user-images.githubusercontent.com/67622230/86085718-ae268280-ba54-11ea-8e6e-d69c171d1fc5.png">

**Comment by Cosmo120** [comment]
Why is my net like this?
<img width="285" alt="Screen Shot 2020-06-29 at 10 10 28 PM" src="https://user-images.githubusercontent.com/67622230/86086053-94d20600-ba55-11ea-823c-0d32850b7751.png">

**Comment by matthewdarwin** [comment]
Seems this is not an EOSIO code issue. Probably want to discuss in https://eosio.stackexchange.com/

**Comment by Cosmo120** [comment]
gotcha, appreciate the direction!
