### ISSUE TITLE
New accounts fail lookups via get_accounts_by_authorizers

### ISSUE THREAD

**Issue by aaroncox** [EOSIO/eos#9278]
It's recently come to our attention that the new `v1/chain/get_accounts_by_authorizers` API endpoint will stop updating and adding new key/auth -> account associations to its dataset. All previous lookups will remain functional, but any account created after an unknown period in time (or event) will not be returned unless nodeos is restarted.

We have seen his both on our EOS API infrastructure as well as on Jungle 3. Here are some example calls against our API infrastructure that illustrate the account not returning in `v1/chain/get_accounts_by_authorizers`, but returning results through `v1/history/get_key_accounts`. 

```bash
curl https://jungle3.greymass.com/v1/chain/get_accounts_by_authorizers -d '{"keys": ["EOS7LQUHUHPNLY4T8gbZjtWhxqTNw8ukzqTvrk12uchnHM1gAaR71"]}'

curl https://jungle3.greymass.com/v1/history/get_key_accounts -d '{"public_key":"EOS7LQUHUHPNLY4T8gbZjtWhxqTNw8ukzqTvrk12uchnHM1gAaR71"}'
```

We will leave our Jungle 3 API running in this state if it helps further troubleshoot this issue - and feel free to create new Jungle 3 accounts and observe how they are returned by the v1/history plugin and not the new v1/chain plugin.

**Comment by aaroncox** [comment]
To add additional context, it looks like it's any new accounts after the new API endpoint initializes. 

I performed the following steps over the weekend while experimenting more:

- Restarted nodeos w/ `--enable-account-queries=true`
- Immediately created a new account.
- Performed key lookup using `get_accounts_by_authorizers`, the account is not found. 
- Performed key lookup using `get_key_accounts`, the account name was returned.
- Awaited irreversibility, still not found via `get_accounts_by_authorizers`.
- Restarted nodeos again w/ `--enable-account-queries=true`
- Account can now be found.

**Comment by apolloaotc** [comment]
{
  "account_names": []
}

**Comment by nsjames** [comment]
bump, is there an ETA on this?

**Comment by nickjjzhao** [comment]
Hello nsjames,

Sorry for the late response. I am actively working on this issue, and trying to fix it by next Wednesday. Please feel free to let me know if you have any other concerns. Thanks! – Jingjun

**Comment by matthewdarwin** [comment]
Is suppose this issue is resolved now?

https://github.com/EOSIO/eos/pull/9382 (2.0.x)
https://github.com/EOSIO/eos/pull/9384 (develop)

**Comment by ashuralyk** [comment]
I've found this bug as well, it's totally the same with aaroncox's. And I'm also concerned about wether this bug resolved now?

**Comment by b1bart** [comment]
> Is suppose this issue is resolved now?

We consider this issue resolved in the PRs you have listed, we will keep the issue open until the next `2.0.x` point release when it is officially available in a stable release.  

If you are able, please build a version with that patch integrated and see if the issue(s) persist.   We have not been able to reproduce after the patch.

**Comment by aaroncox** [comment]
I've merged the patch into both our EOS and Jungle 3 APIs and done some initial tests - new accounts seem to be detected while it's running. I'll continue to monitor on our end, but hopefully this will be the end of all these restarts! 👍
