### ISSUE TITLE
STAT-282 ⁃ Add genesis, config, and script for testnet connection

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#928]
Many of the tests are setup to use a hardcoded private key that is no longer appropriate for the testnet genesis.json that is in github master. We need to add a test_genesis.json for exclusive use by tests.

Rather than revise all tests and documentation, genesis.json has been reverted to the local private testnet version.
The strategy to enable easy eosd connection to the testnet is to add a second genesis file and accompanying config.ini, along with a script that's available to launch eosd after a successful build.

### ATC:
* Use script according to the instructions in README.md to connect via P2P to public testnet.

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

Rather than revise all tests and documentation, genesis.json has been reverted to the local private testnet version.

The strategy to enable easy eosd connection to the testnet is to add a second genesis file and accompanying config.ini, along with a script that's available to launch eosd after a successful build.

**Comment by heifner** [comment]
Complete and closed in JIRA.
