### ISSUE TITLE
./eosc 404 Unknown Endpoint after launcher starts 2 nodes and kill child processes

### ISSUE THREAD

**Issue by comtechnet** [EOSIO/eos#929]
Things were grooving along, then after I started 2 nodes via launcher, it seems like I got disconnected from my blockchain.

./eosc get account currency
748771ms            main.cpp:1166                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"unknown key"}

./eosc wallet create
1743919ms            main.cpp:1166                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 404
: {"code":404,"message":"Not Found","details":"Unknown Endpoint"}

the genesis.json files are still there.

I had NOT read about launcher's ability to kill the nodes.

I just used kill PID

but afterwards, using regular ./eosd
3373575ms            main.cpp:48                   main                 ] eosd version a24ebc6d
3373781ms            chain_plugin.cpp:126          plugin_initialize    ] initializing chain plugin
3373781ms            wasm_interface.cpp:757        get                  ] Runtime::init
3373807ms            http_plugin.cpp:138           plugin_initialize    ] host: 127.0.0.1 port: 8888 
3373808ms            http_plugin.cpp:141           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
3373808ms            net_plugin.cpp:2274           plugin_initialize    ] Initialize net plugin
3373809ms            net_plugin.cpp:2294           plugin_initialize    ] Setting net_plugin logging level to info
3373809ms            net_plugin.cpp:2319           plugin_initialize    ] host: 0.0.0.0 port: 9876 
3373809ms            net_plugin.cpp:2398           plugin_initialize    ] my node_id is ac38aa23ba21feccd5acdd160d2fcc4c54a829e425e16baeb6f51c4abac2c434
3373851ms            main.cpp:61                   main                 ] 10 assert_exception: Assert Exception
fc::exists( my->genesis_file ): unable to find genesis file '', check --genesis-json argument
    {"f":""}
      chain_plugin.cpp:228 plugin_startup

    {"my->genesis_file.generic_string()":""}
      chain_plugin.cpp:257 plugin_startup

Is this a BUG?

**Comment by heifner** [comment]
If you are not careful when starting via the launcher it can kill/overwrite existing/running eosds. I suspect that is what happened to you. We have added a -force option to launcher to help prevent this.

**Comment by wangnan31415926** [comment]
i have the same problem.how can i solve the problem?

765508ms            chain_plugin.cpp:126          plugin_initialize    ] initializing chain plugin
765509ms            wasm_interface.cpp:757        get                  ] Runtime::init
765509ms            producer_plugin.cpp:170       plugin_initialize    ] Public Key: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
765509ms            wallet_plugin.cpp:34          plugin_initialize    ] initializing wallet plugin
765509ms            http_plugin.cpp:138           plugin_initialize    ] host: 127.0.0.1 port: 8888 
765510ms            http_plugin.cpp:141           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
765510ms            net_plugin.cpp:2442           plugin_initialize    ] Initialize net plugin
765510ms            net_plugin.cpp:2462           plugin_initialize    ] Setting net_plugin logging level to info
765510ms            net_plugin.cpp:2487           plugin_initialize    ] host: 0.0.0.0 port: 9876 
765511ms            net_plugin.cpp:2566           plugin_initialize    ] my node_id is e5d219a827e1b701b5f47fd2d23374484e56c5174ab6687e5a47e71be89cddf8
765511ms            main.cpp:59                   main                 ] eosd version 79752710
765511ms            main.cpp:63                   main                 ] 10 assert_exception: Assert Exception
fc::exists( my->genesis_file ): unable to find genesis file '/path/to/eos/source/genesis.json', check --genesis-json argument
    {"f":"/path/to/eos/source/genesis.json"}
      chain_plugin.cpp:228 plugin_startup

    {"my->genesis_file.generic_string()":"/path/to/eos/source/genesis.json"}
      chain_plugin.cpp:257 plugin_startup

**Comment by wangnan31415926** [comment]
config.ini Add genesis-json = ../../genesis.json

**Comment by ShellRedia** [comment]
wangnan31415926 's answer is quite good, you need write "genesis-json = ../../genesis.json" to replace "genesis-json = /path/to/eos/source/genesis.json" in config.ini.

**Comment by eliquinox** [comment]
I have the same error, the first run after build was good, but when I wanted to run eosd again I got the message:
```
1129879ms            chain_plugin.cpp:126          plugin_initialize    ] initializing chain plugin
1129879ms            wasm_interface.cpp:757        get                  ] Runtime::init
1129879ms            producer_plugin.cpp:170       plugin_initialize    ] Public Key: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
1129880ms            wallet_plugin.cpp:34          plugin_initialize    ] initializing wallet plugin
1129880ms            http_plugin.cpp:138           plugin_initialize    ] host: 127.0.0.1 port: 8888 
1129880ms            http_plugin.cpp:141           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
1129880ms            net_plugin.cpp:2379           plugin_initialize    ] Initialize net plugin
1129880ms            net_plugin.cpp:2399           plugin_initialize    ] Setting net_plugin logging level to info
1129880ms            net_plugin.cpp:2424           plugin_initialize    ] host: 0.0.0.0 port: 9876 
1129880ms            net_plugin.cpp:2503           plugin_initialize    ] my node_id is a422e382f3c2524d2cf57af2cd09d2b8945dfebc6f3ac25a6ce573557c732c31
1129881ms            main.cpp:59                   main                 ] eosd version 22acff0c
1129882ms            block_log.cpp:92              open                 ] Opening block log at /home/ubuntu/eos/build/programs/eosd/data-dir/blocks/blocks.log
1129882ms            block_log.cpp:120             open                 ] Log is nonempty
1129883ms            main.cpp:63                   main                 ] 13 St9exception: basic_ios::clear: iostream error
basic_ios::clear: iostream error: 
    {"my->genesis_file.generic_string()":"/home/ubuntu/eos/genesis.json","what":"basic_ios::clear: iostream error"}
      chain_plugin.cpp:257 plugin_startup
```
I have checked genesis path in config.ini file but still getting this error
