### ISSUE TITLE
Can it support Clang 4+?

### ISSUE THREAD

**Issue by linsumang** [EOSIO/eos#930]
I am using Arch with Clang 5.0 and got errors below.

CMake Error at libraries/abi_generator/CMakeLists.txt:2 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "4.0".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/llvm/LLVMConfig.cmake, version: 5.0.0
    /usr/lib/cmake/llvm/LLVMConfig.cmake, version: 5.0.0
    /lib64/cmake/llvm/LLVMConfig.cmake, version: 5.0.0
    /lib/cmake/llvm/LLVMConfig.cmake, version: 5.0.0

**Comment by heifner** [comment]
We have not tried Clang 5.0. Please use telegram `EOS Developers` for questions and support.
