### ISSUE TITLE
Feature request: use TCP keepalives in p2p connections

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#9306]
while brainstorming the "comas" with Michael from EOSUSA, it appeared that the firewall stopped forwarding TCP packets within existing sessions, but the nodeos servers still considered them as active, and did not reestablish the connections. The standard TCP timeout in Linux kernel is 15 minutes, so the connection is first dropped 15 minutes after the packets stopped flowing.

TCP Keepalives is a standard feature that can be enabled by an application on the TCP socket. It doesn't require any compatibility on the other side of connection because it's using standard TCP ACK messages. 

http://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/

Keepalives with rather aggressive timers need to be enabled by default on p2p connections, and the timers need to be adjustable. This will prevent the nodeos from stopping because of malfunctioning firewall or aggressive NAT policy.

**Comment by heifner** [comment]
EOSUSA knows this happens with versions 1.8.4 thru 2.0.7

**Comment by heifner** [comment]
Adding TCP keepalive: https://github.com/EOSIO/eos/tree/net-plugin-keepalive-2.0 did not help EOSUSA.

EOSUSA reported they can reproduce this issue by disabling/enabling the wan connection that node is going out:

> i can now preproduce it on demand simply by disabling/enabling the wan connection that node is going out on.  even while in coma, node can ping the external p2p node its no longer syncing with but refuses to sync and then magically after 15 mins syncs again.  i tried with default —p2p-timeout-time as well as 30000 but always waits 15 mins.  if i keep the node peered with another internally thats in sync, node never skips a beat.

**Comment by heifner** [comment]
Closing this as keepalives did not help. I think #8562 is the way to go.
