### ISSUE TITLE
How to debug eos

### ISSUE THREAD

**Issue by Tinide** [EOSIO/eos#9313]

**Comment by taokayan** [comment]
a possible way maybe to start nodeos with ```--contracts-console``` so that you will see console messages printed from your smart contract.

**Comment by johndebord** [comment]
@Tinide Is your question how to debug a smart contract or how to debug `EOSIO/eos` as a whole?

**Comment by gzliudan** [comment]
You can compile a debug version, then use IDE such as clion to debug EOS.

**Comment by Tinide** [comment]
> @Tinide您的问题是如何调试智能合约或`EOSIO/eos`整体调试吗？

yes! Can I debug with IDE？

**Comment by Tinide** [comment]
> EOS
thank you

**Comment by Tinide** [comment]
> 您可以编译调试版本，然后使用诸如clion之类的IDE调试EOS。

tank you

**Comment by Tinide** [comment]
> a possible way maybe to start nodeos with `--contracts-console` so that you will see console messages printed from your smart contract.

This is too much trouble

**Comment by gzliudan** [comment]
for smart contract, maybe you can use print function
