### ISSUE TITLE
Node headblock timestamp difference from GMT 

### ISSUE THREAD

**Issue by HassanAmed** [EOSIO/eos#9318]
I have setup a private node but the time for head block timestamp is 5 min ahead of GMT time. What is causing this time difference ? 
![image](https://user-images.githubusercontent.com/38535048/87763580-7417f780-c82e-11ea-9b70-3e91004c6af6.png)
see head block  time 8:10:32
![image](https://user-images.githubusercontent.com/38535048/87763531-5d71a080-c82e-11ea-91af-96fc247765ea.png)
see GMT

**Comment by aclark-b1** [comment]
Nodeos relies on system time, so you may want to try using NTP or a similar solution to ensure that you don't have time drift on your host.

**Comment by HassanAmed** [comment]
Syncing my server time with GMT resolved the issue Thanks @aclark-b1
