### ISSUE TITLE
I was downloading Homebrew on macOS but following error occurred. Also the downloading speed gets very low around 3.0 KiB/s. 

### ISSUE THREAD

**Issue by Mishrakishan** [EOSIO/eos#9324]
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Failed during: git fetch origin --force

**Comment by spoonincode** [comment]
Did you ever have any success? Not much we can really control with homebrew.
