### ISSUE TITLE
Build script needs check for Secp256k1 (macOS)

### ISSUE THREAD

**Issue by agmontpetit** [EOSIO/eos#933]
I'm trying to build EOS on my MacBook running macOS High Sierra. I'm getting an error related to `Secp256k1`. It seems that library is missing (see attached image).
Probably the build script should handle this.

![eos-build-error-high-sierra](https://user-images.githubusercontent.com/1630814/33889444-652bd8be-df50-11e7-9f55-aef262a2980b.png)

**Comment by heifner** [comment]
Please use telegram `EOS Developers` for support.
