### ISSUE TITLE
std_out does not work in Nodeos logging

### ISSUE THREAD

**Issue by mharrisb1** [EOSIO/eos#9355]
Tried to enable new failed transaction logging introduced in 2.0.7 with the `logging.json` file below:

```json
{
  "includes": [],
  "appenders": [{
      "name": "consoleout",
      "type": "console",
      "args": {
        "stream": "std_out",
        "level_colors": [{
            "level": "debug",
            "color": "green"
          },{
            "level": "warn",
            "color": "brown"
          },{
            "level": "error",
            "color": "red"
          }
        ]
      },
      "enabled": true
    }
  ],
  "loggers": [{
      "name": "default",
      "level": "info",
      "enabled": true,
      "additivity": false,
      "appenders": [
        "consoleout"
      ]
    },
    {
      "name": "transaction_failure_tracing",
      "level": "debug",
      "enabled": true,
      "additivity": false,
      "appenders": [
        "consoleout"
      ]
    }
  ]
```

That did not work and the additional logging could not be seen. The proposed work around is to use `std_err` instead of `std_out` since `std_out` does not work. 

I am unable to identify if the use of `std_err` will resolve the issue, however it stands that we should fix `std_out` since it does not work. We use `std_out` in the default `logging.json` file in the master branch so this should be resolved by either fully removing `std_out` including the removal of it in the default config or by fixing the cause of it being "broken".

**Comment by sanaraufx** [comment]
This has been completed
