### ISSUE TITLE
STAT-286 ⁃ Version Release Table: As a developer I can see which versions and tags were released when, with what features

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#936]
Create AND MAINTAIN a table in our documentation listing release name and version number, and other useful info. It should match up with the GitHub release and tag information. Reported by [~jonathan.giszczak] from chatter in the public dev channel.

Needs to be augmented by a process step in our release process, to update it.

┆Attachments: <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10104&#x2F;releases.md">releases.md</a> | <a href="https:&#x2F;&#x2F;blockone.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10102&#x2F;versions.md">versions.md</a>

**Comment by blockone-syncclient** [comment]
➤ Thomas B. Cox commented:

I'll add to this. [~jonathan.giszczak] where would you suggest publishing this -- as a standalone doc that's part of what directory, and/or as an embedded table inside of what existing document?

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

Unfortunately Markdown doesn't support include directives, even in its Github dialect, so that table would have to be directly incorporated in our README.md.  Or in the wiki.  Or both.

A wiki page, either standalone and referenced from the main page or incorporated in the main page is a must.  Incorporating it into our README.md is a little strange, since the act of incorporating it changes master, immediately pushing it past the latest tag.  This is only a little bit weird, since users attempting to match a particular tag should be using git's checkout by tag feature anyway.  The weird part is tags can never provide a README.md that includes themselves.^1^

^1^ For those playing along at home, git does include a substitution feature for files tagged with gitattribute ident.  This gets you the full 40 character hash.  There is no corresponding short form available.

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

To address the title of this ticket, the version table is all of it except the "with what features" part.  The full release notes serve that purpose.  The table is meant to be an abbreviated quick reference of tags, dates, and versions.

**Comment by blockone-syncclient** [comment]
➤ Thomas B. Cox commented:

[~jonathan.giszczak] your feedback gratefully received on revised "[^releases.md]" file attached.

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

I gather the intent is to incorporate the contents of releases.md into README.md.  If the table will be in the wiki, the final note can be omitted.  If it's going into README.md, then the final note is retained and I suggest editing it to remove the informal language and remove the equivocation.

  * Tags can never provide a document that includes themselves. Therefore the above list will always omit the latest tag.

**Comment by blockone-syncclient** [comment]
➤ Thomas B. Cox commented:

Implemented here:
https://github.com/EOSIO/eos/wiki/Releases

**Comment by heifner** [comment]
Complete and closed in JIRA.
