### ISSUE TITLE
Unclear error message: the options configuration file contains an invalid line '​'

### ISSUE THREAD

**Issue by ejformby** [EOSIO/eos#9363]
I'm trying to run a local test node using a config.ini file. I've previously run it using options set from the command line. Using the config.ini file I get the error:

error 2020-08-05T19:51:32.221 nodeos    main.cpp:131                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::wrapexcept<boost::program_options::invalid_config_file_syntax>
std::exception::what: the options configuration file contains an invalid line '​'

The config.ini file I'm trying to use is:

```
# Enable production on a stale chain, since a single-node test chain is pretty much always stale
enable-stale-production = true
​
# Enable block production with the testnet producers
producer-name = eosio
trusted-producer = eosio
​
# Load the block producer plugin, so you can produce blocks
plugin = eosio::producer_plugin
​plugin = eosio::producer_api_plugin

# Wallet plugin
plugin = eosio::wallet_api_plugin
​
# As well as API and HTTP plugins
plugin = eosio::chain_api_plugin
plugin = eosio::http_plugin
​
# history plugins
plugin = eosio::account_history_api_plugin
plugin = eosio::history_api_plugin

# chain plugin settings
chain-state-db-size-mb = 65536
reversible-blocks-db-size-mb = 65536
contracts-console = true

# producer_plugin settings
max-transaction-time = 150000
subjective-cpu-leeway-us = 150000
signature-provider = <public-key>=KEY:<private-key>

# http_plugin
http-max-response-time-ms = 1000
access-control-allow-origin = *
http-validate-host = false
http-server-address = 127.0.0.0:8888
verbose-http-errors = true

# history_plugin
filter-on = *
```

If I start with the default.init file and add this to the top:

enable-stale-production = true
​
I get the same error message. If I add  the following before that

plugin = eosio::producer_plugin
​plugin = eosio::producer_api_plugin

I get the error messaege:

error 2020-08-05T20:33:44.887 nodeos    main.cpp:131                  main                 ] /workdir/libraries/appbase/application.cpp(298): Throw in function bool appbase::application::initialize_impl(int, char **, vector<appbase::abstract_plugin *>)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: Unknown option '​plugin' inside the config file

The nodeos version I'm using is 2.0.6.

**Comment by spoonincode** [comment]
That code block has some weird unicode characters in it. Can you double check locally and see if your config.ini has any thing out of the ordinary? Not sure best way of doing that

```
hexdump -C config.ini
00000000  23 20 45 6e 61 62 6c 65  20 70 72 6f 64 75 63 74  |# Enable product|
00000010  69 6f 6e 20 6f 6e 20 61  20 73 74 61 6c 65 20 63  |ion on a stale c|
00000020  68 61 69 6e 2c 20 73 69  6e 63 65 20 61 20 73 69  |hain, since a si|
00000030  6e 67 6c 65 2d 6e 6f 64  65 20 74 65 73 74 20 63  |ngle-node test c|
00000040  68 61 69 6e 20 69 73 20  70 72 65 74 74 79 20 6d  |hain is pretty m|
00000050  75 63 68 20 61 6c 77 61  79 73 20 73 74 61 6c 65  |uch always stale|
00000060  0a 65 6e 61 62 6c 65 2d  73 74 61 6c 65 2d 70 72  |.enable-stale-pr|
00000070  6f 64 75 63 74 69 6f 6e  20 3d 20 74 72 75 65 0a  |oduction = true.|
00000080  e2 80 8b 0a 23 20 45 6e  61 62 6c 65 20 62 6c 6f  |....# Enable blo|   <<< the  e2 80 8b here is bad
00000090  63 6b 20 70 72 6f 64 75  63 74 69 6f 6e 20 77 69  |ck production wi|
```

```
signature-provider = <public-key>=KEY:<private-key>
```
that's no good either but probably not what is responsible for the error message you're getting.

**Comment by ejformby** [comment]
Thanks @spoonincode. Those unicode characters were the source of the problem. I removed those and it runs now. They didn't show in my editor. They must have copied over from a website. Sorry about that.

**Comment by spoonincode** [comment]
Good to hear :+1:
