### ISSUE TITLE
error messaging Exchange contract

### ISSUE THREAD

**Issue by jordanrancie** [EOSIO/eos#941]
After installing exchange (and currency) contracts and pushing a message I get a conversion error:

   `./eosc push message currency transfer '{"from":"user1","to":"exchange","quantity":1000}' --scope exchange,user1 -p user1@active`

   `./eosc push message exchange bid '{"buyer":{"name":"user1","number":123},"at_price":100,"quantity":10,"expiration":"2017-12-12","fill_or_kill" : 0}' --scope exchange,user1 -p user1@active`

### Error message from `eosc`
`383246ms            main.cpp:1099                 operator()           ] Converting argument to binary...
383270ms            main.cpp:1166                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"7 bad_cast_exception: Bad Cast\nInvalid cast from object_type to string\n    {\"type\":\"object_type\"}\n      variant.cpp:476 as_string\n\n    {\"code\":\"exchange\",\"type\":\"bid\",\"obj\":{\"buyer\":{\"name\":\"user1\",\"number\":123},\"at_price\":100,\"quantity\":10,\"expiration\":\"19-12-2017\",\"fill_or_kill\":0}}\n      chain_controller.cpp:1555 message_to_binary"}`

### Error message rom `eosd`
`383249ms            chain_api_plugin.cpp:71       operator()           ] Exception encountered while processing chain.abi_json_to_bin: {"code":7,"name":"bad_cast_exception","message":"Bad Cast","stack":[{"context":{"level":"error","file":"variant.cpp","line":476,"method":"as_string","hostname":"","thread_name":"","timestamp":"2017-12-13T04:06:23"},"format":"Invalid cast from ${type} to string","data":{"type":"object_type"}},{"context":{"level":"warn","file":"chain_controller.cpp","line":1555,"method":"message_to_binary","hostname":"","thread_name":"","timestamp":"2017-12-13T04:06:23"},"format":"","data":{"code":"exchange","type":"bid","obj":{"buyer":{"name":"user1","number":123},"at_price":100,"quantity":10,"expiration":"19-12-2017","fill_or_kill":0}}}]}`

At first, I thought is the time(`expiration`) field format, so I tried 2018-01-01, 2018/01/01, 01/01/2018, 01-01-2018, 1513157461 (epoch) - with no luck.

Now I believe its the nested json object `buyer` of type`order_id`

**Comment by nanonano7** [comment]
bid is not an action https://github.com/EOSIO/eos/blob/master/contracts/exchange/exchange.abi#L51

**Comment by heifner** [comment]
Please use telegram `EOS Developers` for support.
