### ISSUE TITLE
unlinkable_block_exception

### ISSUE THREAD

**Issue by Tinide** [EOSIO/eos#9418]
节点运行20多天了，突然出现]unlinkable_block_exception，节点不再同步，但仍在运行

info  2020-08-20T01:24:03.509 net-0     net_plugin.cpp:1070           operator()           ] Sending handshake generation 14 to 192.168.11.253:9878 - 7e9324d, lib 3416134, head 3416466, id 73107293ca4da9bf
warn  2020-08-20T01:24:03.509 net-0     net_plugin.cpp:1747           rejected_block       ] block 3416580 not accepted from 192.168.11.253:9878 - 7e9324d, closing connection
error 2020-08-20T01:24:03.509 nodeos    net_plugin.cpp:2937           process_signed_block ] ["192.168.11.253:9878 - 7e9324d" 192.168.11.253:36616]unlinkable_block_exception #3416581 4b38a914f5535a64...: Unlinkable block (3030001)
unlinkable block 003422054b38a914f5535a64b8d00c927d8d618ecd646d513da3776c153ba059

info  2020-08-20T01:24:03.509 net-0     net_plugin.cpp:1545           start_sync           ] Catching up with chain, our last req is 0, theirs is 3889659 peer 192.168.11.253:9878 - 7e9324d
error 2020-08-20T01:24:03.510 nodeos    net_plugin.cpp:2937           process_signed_block ] ["192.168.11.253:9878 - 7e9324d" 192.168.11.253:36616]unlinkable_block_exception #3416582 ec6a912357856249...: Unlinkable block (3030001)
unlinkable block 00342206ec6a9123578562493603c1fee6311b2a547921b24fcfd022bf6a32c2

error 2020-08-20T01:24:03.510 nodeos    net_plugin.cpp:2937           process_signed_block ] ["192.168.11.253:9878 - 7e9324d" 192.168.11.253:36616]unlinkable_block_exception #3416583 abc6b985adf65073...: Unlinkable block (3030001)
unlinkable block 00342207abc6b985adf6507385a67148a9787681bcb97db0b80db2c7fbd1b7a3

info  2020-08-20T01:24:03.510 net-0     net_plugin.cpp:943            _close               ] closing '', 192.168.11.253:36616
info  2020-08-20T01:24:03.510 net-1     net_plugin.cpp:1491           operator()           ] requesting range 3416567 to 3416666, from 192.168.11.254:9879 - fb28b68
info  2020-08-20T01:24:03.510 net-0     net_plugin.cpp:1491           operator()           ] requesting range 3416567 to 3416666, from 192.168.11.253:36616
info  2020-08-20T01:24:03.510 net-0     net_plugin.cpp:1121           operator()           ] async write socket closed before callback: 192.168.11.253:36616
info  2020-08-20T01:24:03.510 net-0     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to 192.168.11.253:36616, lib 3416134, head 3416466, id 73107293ca4da9bf
info  2020-08-20T01:24:03.511 net-0     net_plugin.cpp:1070           operator()           ] Sending handshake generation 2 to 192.168.11.253:36616, lib 3416134, head 3416466, id 73107293ca4da9bf
error 2020-08-20T01:24:03.511 nodeos    net_plugin.cpp:2937           process_signed_block ] ["192.168.11.254:9879 - fb28b68" 192.168.11.254:44618]unlinkable_block_exception #3416567 48fa7eb0b699cede...: Unlinkable block (3030001)
unlinkable block 003421f748fa7eb0b699cede0a8bfc4de5726dcb647bc1ac8ce96a35f9ef9e3d

info  2020-08-20T01:24:03.511 net-0     net_plugin.cpp:943            _close               ] closing '', 192.168.11.253:36616
error 2020-08-20T01:24:03.511 nodeos    net_plugin.cpp:2937           process_signed_block ] ["192.168.11.254:9879 - fb28b68" 192.168.11.254:44618]unlinkable_block_exception #3416568 9c97c2b5af8aaff9...: Unlinkable block (3030001)
unlinkable block 003421f89c97c2b5af8aaff9fe2b0e0a2f3e32693b0bd286f37bf03e594eea97

info  2020-08-20T01:24:03.511 net-1     net_plugin.cpp:1070           operator()           ] Sending handshake generation 2 to 192.168.11.254:9879 - fb28b68, lib 3416134, head 3416466, id 73107293ca4da9bf
info  2020-08-20T01:24:03.511 net-0     net_plugin.cpp:1070           operator()           ] Sending handshake generation 1 to 192.168.11.253:36616, lib 3416134, head 3416466, id 73107293ca4da9bf
info  2020-08-20T01:24:03.511 net-1     net_plugin.cpp:1070           operator()           ] Sending handshake generation 3 to 192.168.11.254:9879 - fb28b68, lib 3416134, head 3416466, id 73107293ca4da9bf
info  2020-08-20T01:24:03.511 net-0     net_plugin.cpp:1121           operator()           ] async write socket closed before callback: 192.168.11.253:36616
info  2020-08-20T01:24:03.511 net-0     net_plugin.cpp:943            _close               ] closing '', 192.168.11.253:36616
info  2020-08-20T01:24:03.512 net-1     net_plugin.cpp:1545           start_sync           ] Catching up with chain, our last req is 3416666, theirs is 3889659 peer 192.168.11.254:9879 - fb28b68
info  2020-08-20T01:24:03.512 net-1     net_plugin.cpp:1412           request_next_chunk   ] ignoring request, head is 3416466 last req = 3416666 source is 192.168.11.254:9879 - fb28b68

**Comment by aclark-b1** [comment]
Hello @Tinide 

Can you please share a bit more information to help us debug this?  

- What version of EOSIO are you running?
- Are you using our binaries or did you build from source?  If you built it, were there any changes made?
- Which operating system are you using?
- Could you please share your config.ini file?

Thanks!
