### ISSUE TITLE
I feel that the EOSIO code version is not as clear as before

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#9437]
I hope the release branch can continue to follow the previous version rules
![image](https://user-images.githubusercontent.com/7980920/91115872-c36b0680-e6bd-11ea-9872-9eb80da7c1c6.png)
![image](https://user-images.githubusercontent.com/7980920/91116051-13e26400-e6be-11ea-8b6b-82c71f6681ef.png)

Similar to v1.8.4, it is more in line with the previous specification

**Comment by cppfuns** [comment]
@larryk85

**Comment by larryk85** [comment]
@cppfuns, this issue should be against `eosio.contracts` really. 

None-the-less, it was an unfortunate (and hopefully very rare) thing that occurred.  The reasoning behind this, was that we needed to do a bug fix and v1.8.4 was still a release candidate, so we couldn't simply shift to v1.8.4 as that was already a version and we couldn't wait on v1.8.4 to be stable for the fix.  This ultimately leads us to the oddity in terms of versioning.
