### ISSUE TITLE
error launching local node connected to the public testnet

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/eos#945]
Following along instructions I had these problems.
```
~/dev/eos$ cd build/scripts
bash: cd: build/scripts: No such file or directory
```
```
~/dev/eos$ cd scripts/
~/dev/eos/scripts$ ./start_npnode.sh 
Launched eosd.
See testnet_np/stderr.txt for eosd output.
Synching requires at least 8 minutes, depending on network conditions.
*** Error in `../programs/eosd/eosd': corrupted size vs. prev_size: 0x0000557d80fa33c0 ***

```

`~/dev/eos/scripts$ tail -F testnet_np/stderr.txt
3327725ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/lock
3327725ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/lock_all
3327725ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/open
3327725ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/set_timeout
3327725ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/sign_transaction
3327725ms            http_plugin.cpp:239           add_handler          ] add api url: /v1/wallet/unlock
3327725ms            main.cpp:65                   main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
std::exception::what: bind: Address already in use
`

After reboot public testnet node started but with this error message.

> ~/dev/eos/scripts$ tail -F testnet_np/stderr.txt
> 353628ms            fork_database.cpp:47          push_block           ] Head: 16399, 0000400fee01e1c8ee02ad05db44be0b1e8c48b438478552021d4e84a3248afe
> 353628ms            net_plugin.cpp:2010           handle_message       ] unlinkable_block_exception accept block #16446 syncing from p2p-testnet1.eos.io:9876
> 353628ms            fork_database.cpp:46          push_block           ] Pushing block to fork database that failed to link: 0000403f736b51113110e9883430108f02cfcb6f4428b49793e264b264cd37dd, 16447
> 353629ms            fork_database.cpp:47          push_block           ] Head: 16399, 0000400fee01e1c8ee02ad05db44be0b1e8c48b438478552021d4e84a3248afe
> 353629ms            net_plugin.cpp:2010           handle_message       ] unlinkable_block_exception accept block #16447 syncing from p2p-testnet1.eos.io:9876
> 353630ms            fork_database.cpp:46          push_block           ] Pushing block to fork database that failed to link: 0000404080c52612551839a5f510b71745e22b4cd7472a5648544f19748f082a, 16448
> 353631ms            fork_database.cpp:47          push_block           ] Head: 16399, 0000400fee01e1c8ee02ad05db44be0b1e8c48b438478552021d4e84a3248afe
> 353632ms            net_plugin.cpp:2010           handle_message       ] unlinkable_block_exception accept block #16448 syncing from p2p-testnet1.eos.io:9876
> 353632ms            net_plugin.cpp:1406           operator()           ] Error reading message from connection: Bad file descriptor
> 353632ms            net_plugin.cpp:665            close                ] calling reset
>

**Comment by jgiszczak** [comment]
Assuming you had an existing build and only just updated, you should rerun cmake and rebuild (rerun make).

**Comment by bitcoiners** [comment]
Thanks after fresh build managed to start the node on public testnet, but it keeps showing messages like 

> 230131ms            fork_database.cpp:47          push_block           ] Head: 414812, 0006545c63fa9dce6bd078d4cc981513468588380ca6cb4f31307e7aeea6f8fe
230131ms            net_plugin.cpp:2010           handle_message       ] unlinkable_block_exception accept block #414956 syncing from 10.160.13.213:9876
230131ms            fork_database.cpp:46          push_block           ] Pushing block to fork database that failed to link: 000655660c1354f8b14604eaa026e028b46796a50fc922cce061f50312581132, 415078
230132ms            fork_database.cpp:47          push_block           ] Head: 414812, 0006545c63fa9dce6bd078d4cc981513468588380ca6cb4f31307e7aeea6f8fe
230132ms            net_plugin.cpp:2010           handle_message       ] unlinkable_block_exception accept block #415078 syncing from 10.160.13.213:9876
234127ms            fork_database.cpp:46          push_block           ] Pushing block to fork database that failed to link: 00065d37950d29c6a307e88c7af8e8b64d0f5f0cf64bfa53dd3

**Comment by nanonano7** [comment]
change the spawn script to not delete the data folder and restart the node with replay-blockchain. also i think the testnet might be broken atm

**Comment by bitcoiners** [comment]
"change the spawn script to not delete the data folder" - how?
"restart the node with replay-blockchain" - how?

**Comment by nanonano7** [comment]
remove the first three lines from start_npnode.sh
close eosd
and run start_npnode.sh again

**Comment by bitcoiners** [comment]
Thanks. followed your instructions.
getting this message repeatedly:

> 3230017ms            fork_database.cpp:47          push_block           ] Head: 416904, 00065c8835c46f7da13391c2c169b30aef50deda6a471009c381bb9a68bc70ff
3230017ms            net_plugin.cpp:2010           handle_message       ] unlinkable_block_exception accept block #421091 syncing from 10.160.12.212:9876
3232021ms            fork_database.cpp:46          push_block           ] Pushing block to fork database that failed to link: 00066ce4ff49776b84de4daefa21096907b6b948ef865528b171b48bb27322d7, 421092

**Comment by clayop** [comment]
Same as here. Stuck in block 416904
