### ISSUE TITLE
[Question] Documentation is correct?

### ISSUE THREAD

**Issue by scheung38** [EOSIO/eos#9458]
Mac OSX/Linux
For waxdev
docker run -it --name waxdev -v /c/wax:/wax waxteam/dev bash?

should it not be:

docker run -it --name waxdev -v wax:/wax waxteam/dev bash?

Also waxcdt

docker run -it --name waxcdt -v /var/share/wax:/wax waxteam/cdt bash

says namespace already taken up ?

**Comment by heifner** [comment]
I think you have the wrong repo

**Comment by scheung38** [comment]
@heifner I was working in Wax https://developer.wax.io/dapps/wax-contract-development-toolkit-wax-cdt/ and it is eos related?

**Comment by heifner** [comment]
Wax is a fork of eosio: https://github.com/worldwide-asset-exchange/wax-blockchain

**Comment by scheung38** [comment]
So can both Wax and EOSIO able to generate Ricardian Contract? I don't see much resources on it.

**Comment by matthewdarwin** [comment]
WAX is based on EOSIO.  EOSIO has Ricardian Contracts.  If you have further questions about WAX, please join a WAX-specific group. The EOS github is for EOS software issues only.

Thanks.
