### ISSUE TITLE
eosio-cpp: command not found

### ISSUE THREAD

**Issue by SrenH** [EOSIO/eos#9467]
Hi, I am trying to learn EOS smart contract from EOS developer website https://developers.eos.io/welcome/latest/getting-started/smart-contract-development/hello-world. 
When I tried to compile the hello contract with the command eosio-cpp hello.cpp -o hello.wasm, it appers in the terminal: eosio-cpp: command not found
I tried to google the solution, many suggest using the command $ sudo chmod 755 /usr/local/eosio.cdt/bin/eosio-cpp
I have installed v2.0.0, there is no such eosio-cpp file in my bin folder, my folder looks like usr/opt/eosio/2.0.0/bin
there are 4 files in bin: cleos, eosio-blocklog, keosd, nodeos
Can someone please help? How can I compile EOS smart contract in my Terminal?
Thank you in advance!

**Comment by swang-b1** [comment]
eosio-cpp comes with eosio cdt. you need to install with 

`
brew tap eosio/eosio.cdt
brew install eosio.cdt
`
