### ISSUE TITLE
Eosd not running

### ISSUE THREAD

**Issue by over9001** [EOSIO/eos#947]
I'm following the instructions at https://github.com/EOSIO/eos#singlenode up to where it says "Now it should be possible to run eosd and see it begin producing blocks" but instead I get this:

```

science@science-ThinkPad-T420 ~/projects/eos $ ./build/programs/eosd/eosd 
1521943ms            chain_plugin.cpp:126          plugin_initialize    ] initializing chain plugin
1521943ms            wasm_interface.cpp:757        get                  ] Runtime::init
1521943ms            producer_plugin.cpp:170       plugin_initialize    ] Public Key: EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
1521943ms            wallet_plugin.cpp:34          plugin_initialize    ] initializing wallet plugin
1521943ms            http_plugin.cpp:138           plugin_initialize    ] host: 127.0.0.1 port: 8888 
1521943ms            http_plugin.cpp:141           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
1521944ms            net_plugin.cpp:2442           plugin_initialize    ] Initialize net plugin
1521944ms            net_plugin.cpp:2462           plugin_initialize    ] Setting net_plugin logging level to all
1521944ms            net_plugin.cpp:2487           plugin_initialize    ] host: 0.0.0.0 port: 9876 
1521944ms            net_plugin.cpp:2566           plugin_initialize    ] my node_id is 1621e310bca32205890025d03602eedfc9dc087182696250e509eb086b87aad9
1521944ms            main.cpp:57                   main                 ] eosd version 00db493c

```
and when I try to run the next step I get this
```

science@science-ThinkPad-T420 ~/projects/eos $ ./build/programs/eosc/eosc wallet create
Failed to connect to eosd at localhost:8888; is eosd running?
```

I would bring this to a discussion with the devs or community, but since that chat is on Telegram and I don't have a phone, I can't participate. I have not found a way of using Telegram without a phone, so I'm locked out of EOS? Total showstopper. Please help.

**Comment by minimizeTrustLess** [comment]
@over9001@jgiszczak @bytemaster +1 for above...what is telegram? Normal developers don't use telegram...we use linux and git hub and standard lib at max. Please be open in github for all issues so we can collaborate and solve.

#################
My understanding of telegram is that it used mostly by speculative traders. Please avoid favoring one over other. I love this community, **but source code communication needs to happen only in Git hub.**
###########

**Comment by heifner** [comment]
What OS are you running? Please try `./build/programs/eosd/eosd --resync`

**Comment by jgiszczak** [comment]
@minimizeTrustLess Telegram is the equivalent of IRC, but with encrypted communications.  It's a real time chat client, nothing more.  It's used by whoever needs real time chat, which is the best medium for ephemeral tech support questions.  You don't have to join any channel full of traders, speculative or otherwise, if you don't want to.  The EOS Developers channel is kept on topic by moderation.

**Comment by SamFessler** [comment]
If you don't have a phone....or want to stay anonymous, easiest thing to do is buy a cheap Sim card from a store and use that number to activate Telegram. Sucks but they do it to control spam

**Comment by stone89son** [comment]
Yes Please. Only and only on github.

**Comment by remcoros** [comment]
A bit off/on-topic, but there are more feasible ways for slow-chat communications: Gitter (nice github integration), Slack, mattermost, rocketchat. Just an idea.

If the maintainers choose deliberately to actually have a bit of a barrier to get on a slow-chat channel with developers, that's also understandable.

**Comment by nsjames** [comment]
Telegram is available for desktop.

**Comment by kirkins** [comment]
@remcoros +1, last time I tried to sign up for telegram it wouldn't accept my voip number for sign up
