### ISSUE TITLE
Does the DMD Defi project released by TokenPocket team?

### ISSUE THREAD

**Issue by blockchain-hack** [EOSIO/eos#9473]
[DApp Link] https://dmd.finance/
[JS Resource Link] https://dmd.finance/js/chunk-vendors.5ff2ca4e.js

![image](https://user-images.githubusercontent.com/70789818/92297732-d363cf80-ef74-11ea-9755-404d821db144.png)

![image](https://user-images.githubusercontent.com/70789818/92297629-f2159680-ef73-11ea-8831-1d29f81de568.png)

**Comment by matthewdarwin** [comment]
Not sure what this question has to do with EOSIO software.  Seems off-topic to me.

**Comment by aclark-b1** [comment]
This doesn't seem related to the EOSIO software, please feel free to reopen and clarify if that's not the case.
