### ISSUE TITLE
Telegram dependency locks out devs without smartphones

### ISSUE THREAD

**Issue by over9001** [EOSIO/eos#948]
I don't have a smartphone and I want to interact with the dev community.

I'm alone in the dark and nothing works. If Telegram is the only option for interacting with the EOS community, I will have to find another project to base my work on. This is extremely sad.

I guess goodbye forever?

**Comment by nanonano7** [comment]
telegram desktop client?

**Comment by minimizeTrustLess** [comment]
@jgiszczak @bytemaster. Can we remove dependencies such as above if it exists. Could you please make it open source. I like this project....No Secrecy in weird other sites. Git hub is what I trust. ~MinimizeTruslessNess
