### ISSUE TITLE
make test  or unittest  take too long.  any tricky? 

### ISSUE THREAD

**Issue by smartbitcoin** [EOSIO/eos#9497]
One challenge to contribute into eos code base is not cod reading, modification or compiling time, ( with Ryzen 12 core,  it's 5mins), but the testing.

After modify and build,  next step is confirm it correct by  running  either make test or direct run unittest.

"make test" seems taking for ever.   after one hour, only done 133/2615 test case.
unittest is ok as only 1:30mins.

as known the boost unit test framework is not paralleled. but are there any tricky to at least accomplish " make test " in reasonable time eg 2 hours ?

**Comment by heifner** [comment]
ctest -j 10

**Comment by smartbitcoin** [comment]
![image](https://user-images.githubusercontent.com/5984485/93142863-d10c1e80-f6b4-11ea-897a-83f1c37b03b2.png)

that maybe works for folder build/unittest,  but how about those CLI based test?  those are most time consuming one. and multi instance of those CLI may also fail each other ?

**Comment by heifner** [comment]
I thought we had those set up to not run currently. We probably need to restrict many of those from running currently. I guess we must only have those restricts in buildkite.

**Comment by smartbitcoin** [comment]
thanks for your insight. I'll also skip those. lol
