### ISSUE TITLE
Bugs with eosc create account `--permission inita@active`

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eos#950]
Bugs from: https://github.com/EOSIO/eos/wiki/Tutorials#contract-account

![image](https://user-images.githubusercontent.com/16319106/33976530-6c662928-e0d0-11e7-80cb-4aa697577d68.png)

I've experiment two scenarios, 
- by put inita's public key as owner_key and another random public key as active_key
- by put random public key public key as owner_key and inita's public key as active_key
Both shows error below
![image](https://user-images.githubusercontent.com/16319106/33976511-5942531c-e0d0-11e7-8f53-7c1241797de1.png)

**Comment by heifner** [comment]
Please use telegram `EOS Developers` for support. You have to create with an account with another account you own and have the private keys for loaded into your wallet.
