### ISSUE TITLE
Lack of retrieve Account from owner_key in eosc

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eos#951]
[main.cpp](https://github.com/EOSIO/eos/blob/master/programs/eosc/main.cpp)
![image](https://user-images.githubusercontent.com/16319106/33977525-3c3d633c-e0d6-11e7-9117-52c78d84a613.png)
![image](https://user-images.githubusercontent.com/16319106/33977550-54b8daa4-e0d6-11e7-8623-90fc33d11522.png)
we can utilize the functions above create getter function of Account

**Comment by heifner** [comment]
Please use telegram `EOS Developers` for questions.
