### ISSUE TITLE
Failed to start nodeos 

### ISSUE THREAD

**Issue by wzt-tao** [EOSIO/eos#9522]
![image](https://user-images.githubusercontent.com/53932327/94229737-f14ca080-ff32-11ea-9684-2a7590296294.png)
formatting is incorrect, indicates position later location in file

**Comment by venu-block1** [comment]
@wzt-tao can you please give me the steps to replicate this issue? I'll take a look into it.

**Comment by venu-block1** [comment]
@wzt-tao Just a reminder about the steps to replicate this issue. Can you please add them? If we don't get them by next Friday, I'll close this ticket, and you can enter another ticket later if the issue persists.

**Comment by venu-block1** [comment]
@wzt-tao I'm closing this issue. If the problem persists, please enter a new ticket with steps to replicate.
