### ISSUE TITLE
STAT-297 ⁃ Update GitHub Wiki with port numbers on links to p2p-testnet1.eos.io:9876

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#954]
Please update:  https://github.com/EOSIO/eos/wiki/Testnet%3A%20Public

with:  p2p-testnet1.eos.io:9876

**Comment by blockone-syncclient** [comment]
➤ Jonathan Giszczak commented:

Done.

**Comment by heifner** [comment]
Complete and closed in JIRA.
