### ISSUE TITLE
EOS节点同步慢

### ISSUE THREAD

**Issue by yzn5555** [EOSIO/eos#9570]
节点搭建已经有两三个月了，区块同步才打到110535406，当前最新高度：147000696  相差三千六百万个块，请问有什么方法加快同步速度吗，服务器用的是亚马逊云服务器，服务器配置：4核16G 磁盘：1T    服务器cpu使用率：49%   内存使用率：10%

**Comment by heipacker** [comment]
下载别人备份的数据

**Comment by luckybean** [comment]
用快照启动，最新快照可从这2个地方下载：
http://snapshots.eossweden.org/
https://snapshots.eosnation.io/

**Comment by yzn5555** [comment]
快照之前也有考虑，可以快速同步，但是数据不完整，只能查询快照区块之后的数据信息，快照起始块之前的数据查询不到

**Comment by luckybean** [comment]
那没办法，完全从头开始同步，确实很慢。影响同步的，主要是CPU的性能。越高主频的CPU，节点同步越快。

**Comment by qimiaoguo** [comment]
说实话，同步是个大问题，两三年后，基本不可能完全同步了，除非你做浏览器的，否则不要从头开始搞

**Comment by Krados** [comment]
请问下, 自架本地节点同步的唯一方式是透过其他 P2P 的节点嘛?

**Comment by yzn5555** [comment]
会自动连接到其它节点的



---原始邮件---
发件人: "Krados"<notifications@github.com&gt;
发送时间: 2020年11月24日(周二) 下午4:40
收件人: "EOSIO/eos"<eos@noreply.github.com&gt;;
抄送: "yzn5555"<1076813060@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [EOSIO/eos] EOS节点同步慢 (#9570)




 
请问下, 自架本地节点同步的唯一方式是透过其他 P2P 的节点嘛?

**Comment by Krados** [comment]
这是我目前的配置
`nodeos -e --http-server-address=0.0.0.0:8888 --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::http_plugin --access-control-allow-origin='*' --contracts-console --http-validate-host=false --verbose-http-errors --p2p-peer-address=jungle3.eossweden.org:59073 >> nodeos.log 2>&1 &`
如果我把 p2p-peer-address 我的 nodeos 完全不会有同步动作, 请问该如何设置呢??

**Comment by yzn5555** [comment]
同步了两个月，还差好多，都想放弃了



---原始邮件---
发件人: "qimiao guo"<notifications@github.com&gt;
发送时间: 2020年11月21日(周六) 中午11:58
收件人: "EOSIO/eos"<eos@noreply.github.com&gt;;
抄送: "yzn5555"<1076813060@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [EOSIO/eos] EOS节点同步慢 (#9570)




 
说实话，同步是个大问题，两三年后，基本不可能完全同步了，除非你做浏览器的，否则不要从头开始搞
