### ISSUE TITLE
Synchronize data that's been three minutes away

### ISSUE THREAD

**Issue by wzt-tao** [EOSIO/eos#9572]
My profile is below:
blocks-dir = "blocks"
abi-serializer-max-time-ms = 300000
chain-state-db-size-mb = 81920
reversible-blocks-db-size-mb = 340
read-mode = irreversible
http-server-address = 0.0.0.0:8888
access-control-allow-origin = "*"
verbose-http-errors = true
http-validate-host = false
http-threads = 4
max-clients = 2000
connection-cleanup-period = 30
net-threads = 8
sync-fetch-span = 1000
max-transaction-time = 30
http-max-response-time-ms = 60
trace-history = false
chain-state-history = false
plugin = eosio::chain_plugin
plugin = eosio::chain_api_plugin
p2p-listen-endpoint = 0.0.0.0:9876
p2p-server-address = 0.0.0.0:9876
p2p-peer-address = peer.main.alohaeos.com:9876
p2p-peer-address = eosbp-0.atticlab.net:9876
p2p-peer-address = api.binance-eos.com:9875
p2p-peer-address = mainnet.eosamsterdam.net:9876
p2p-max-nodes-per-host = 30

**Comment by heifner** [comment]
It is unclear your issue. Please provide more information.

**Comment by aclark-b1** [comment]
Hi @wzt-tao, Is there any additional context you can provide here?  We're not sure what you're asking for.
