### ISSUE TITLE
How to choose a good history query solution for EOS?

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#9580]
From the history plugin, to the mongo plugin, and to the hyperion-history-api, there is no easy-to-use solution. The dfuse solution is too cumbersome, and there are a lot of problems with building it yourself. Think that the problem of historical query should be solved first.

history plugin: Consume too much machine memory
mongo plugin: Hard to catch up with the latest block
For history-tools, compared to the mongo plug-in, it feels only partially implemented
https://github.com/EOSIO/history-tools
Most of my friends are still using mongo plug-in, although EOSIO has clearly been abandoned

Looking forward to an easy-to-use solution

**Comment by cppfuns** [comment]
@larryk85 @jeremi

**Comment by maoueh** [comment]
@cppfuns This is not a question for this issue tracker, this is to report bugs.

All history solution for EOS Mainnet are hard, managing this amount of data is not easy, assuming you do not filter anything. It's a hard problem, it's not like there was a few transactions per hour and the amount of data would fit in an SQLite database. From a developer perspective, a hosted solution managed by professionals will always be the easiest way to go. 

Deploy, maintain and monitor history solution on EOSIO, where there is a lot of data to deal with (TeraByte scale) will always be hard IMO. Some are easier than other that's for sure. Take a look at this article https://medium.com/@cc32d9/history-and-notifications-in-eosio-blockchain-8255194af93 to get an overview of the current state of history solution on EOSIO platform (seems who already did you research).

Regarding dfuse in particular, EOS Nation is now hosting a free rate-limited solution, check it out https://eos.dfuse.eosnation.io.

This is my personal opinions by the way. Please close this issue an move the conversation to another channel, this issue tracker is not meant for this.

**Comment by cppfuns** [comment]
I am using a sidechain，EOS Nation's plan does not try me

**Comment by cppfuns** [comment]
When the node block is much behind, it is difficult for the node where the mongo plug-in is located to catch up with the latest block. Is it difficult to catch up when a lot of checks are done when the node is behind?
```
 is 2286668, next expected is 2286569 peer 0.0.0.0:11003 - 22db170
info  2020-10-22T01:12:20.351 net-0     net_plugin.cpp:1554           sync_reassign_fetch  ] reassign_fetch, our last req is 2286668, next expected is 2286569 peer 0.0.0.0:11004 - 0d6c078
info  2020-10-22T01:12:20.583 net-1     net_plugin.cpp:1554           sync_reassign_fetch  ] reassign_fetch, our last req is 2286668, next expected is 2286569 peer 0.0.0.0:11005 - b313f5b
info  2020-10-22T01:12:25.341 net-0     net_plugin.cpp:1554           sync_reassign_fetch  ] reassign_fetch, our last req is 2286668, next expected is 2286569 peer 0.0.0.0:11001 - 238c2ba
info  2020-10-22T01:12:25.341 net-0     net_plugin.cpp:1164           cancel_sync          ] sending empty request but not calling sync wait on 172.16.0.45:11001
info  2020-10-22T01:12:25.341 net-0     net_plugin.cpp:1491           operator()           ] requesting range 2286569 to 2286668, from 0.0.0.0:11002 - 8eaf6af
info  2020-10-22T01:12:30.341 net-1     net_plugin.cpp:1554           sync_reassign_fetch  ] reassign_fetch, our last req is 2286668, next expected is 2286569 peer 0.0.0.0:11002 - 8eaf6af
info  2020-10-22T01:12:30.341 net-1     net_plugin.cpp:1164           cancel_sync          ] sending empty request but not calling sync wait on 172.16.0.45:11002
info  2020-10-22T01:12:30.341 net-1     net_plugin.cpp:1491           operator()           ] requesting range 2286569 to 2286668, from 0.0.0.0:11003 - 22db170
info  2020-10-22T01:12:31.199 mongodb   mongo_db_plugin.cpp:499       consume_blocks       ] process_applied_transaction,  time per: 7931, size: 2083, time: 16520664
info  2020-10-22T01:12:34.206 mongodb   mongo_db_plugin.cpp:511       consume_blocks       ] process_accepted_transaction, time per: 1444, size: 2082, time: 3007089
info  2020-10-22T01:12:35.341 net-1     net_plugin.cpp:1554           sync_reassign_fetch  ] reassign_fetch, our last req is 2286668, next expected is 2286569 peer 0.0.0.0:11003 - 22db170
info  2020-10-22T01:12:35.341 net-1     net_plugin.cpp:1164           cancel_sync          ] sending empty request but not calling sync wait on 172.16.0.46:11003
info  2020-10-22T01:12:35.341 net-1     net_plugin.cpp:1491           operator()           ] requesting range 2286569 to 2286668, from 0.0.0.0:11004 - 0d6c078
info  2020-10-22T01:12:36.709 mongodb   mongo_db_plugin.cpp:537       consume_blocks       ] process_irreversible_block,   time per: 28604, size: 72, time: 2059534
info  2020-10-22T01:12:40.342 net-1     net_plugin.cpp:1554           sync_reassign_fetch  ] reassign_fetch, our last req is 2286668, next expected is 2286629 peer 0.0.0.0:11004 - 0d6c078
info  2020-10-22T01:12:40.342 net-1     net_plugin.cpp:1164           cancel_sync          ] sending empty request but not calling sync wait on 172.16.0.46:11004
info  2020-10-22T01:12:40.342 net-1     net_plugin.cpp:1491           operator()           ] requesting range 2286629 to 2286728, from 0.0.0.0:11005 - b313f5b
info  2020-10-22T01:12:40.806 net-0     net_plugin.cpp:3091           connection_monitor   ] p2p client connections: 0/25, peer connections: 7/7
info  2020-10-22T01:12:42.186 net-1     net_plugin.cpp:1554           sync_reassign_fetch  ] reassign_fetch, our last req is 2286728, next expected is 2286629 peer 0.0.0.0:11006 - 547755c
info  2020-10-22T01:12:42.186 net-0     net_plugin.cpp:1554           sync_reassign_fetch  ] reassign_fetch, our last req is 2286728, next expected is 2286629 peer 0.0.0.0:11007 - c8d5da9

```

**Comment by matthewdarwin** [comment]
for faster, replay from a local blocks.log instead of syncing from the network.   That is start nodeos with the full blocks.log already existing.

**Comment by cppfuns** [comment]
> for faster, replay from a local blocks.log instead of syncing from the network. That is start nodeos with the full blocks.log already existing.

I have tested it, the reply speed is the same, all my nodes are in a local area network, and the speed of network synchronization can be ignored
