### ISSUE TITLE
How do nodes synchronize smart contracts?

### ISSUE THREAD

**Issue by BruceChen1995** [EOSIO/eos#9621]

**Comment by aclark-b1** [comment]
Can you please clarify what you're asking?  We can give you a better answer if we understand what you're trying to accomplish.

**Comment by BruceChen1995** [comment]
When a node deployed a smart contract, how do other nodes synchronize or access to the smart contract?

**Comment by heifner** [comment]
https://developers.eos.io/welcome/latest/protocol/network_peer_protocol

The set contract transaction is placed in a block by a block producer. That block is validated and the set contract action is run during validation on the validation node.
