### ISSUE TITLE
Error 308006: Transaction took too long

### ISSUE THREAD

**Issue by Joyia012** [EOSIO/eos#9677]
cleos set contract eosio /home/eosio.contracts-1.8.x/build/contracts/eosio.system
Reading WASM from /home/eosio.contracts-1.8.x/build/contracts/eosio.system/eosio.system.wasm...
Publishing contract...
Error 3080006: Transaction took too long
Error Details:
deadline exceeded 35232us
pending console output:

**Comment by b1bart** [comment]
@Joyia012 it appears you are exceeding the `max-transaction-time` setting detailed [here in the docs](https://developers.eos.io/manuals/eos/v2.0/nodeos/plugins/producer_plugin/index/?query=max-transaction-time&page=1#options)

I would recommend running `nodeos` with this set to a *much larger* value than its default of `30`.  The system contract is a large and complex wasm so, it may just be that it is large however, this is based on the system clock so running an an underprovisioned system (like a lightweight VM) or with a debug build can cause issues.
