### ISSUE TITLE
last block ID does not match current chain state

### ISSUE THREAD

**Issue by wangnan31415926** [EOSIO/eos#968]
2401934ms            main.cpp:63                   main                 ] 10 assert_exception: Assert Exception
head_block_num() == 0: last block ID does not match current chain state
    {"last_block->id":"0000157384d97ad302433e2c2dad00e6c9357033ce957d167976e8c1e5897791","head_block_num":5492}
      chain_controller.cpp:1306 spinup_fork_db

    {"my->genesis_file.generic_string()":"../../genesis.json"}
      chain_plugin.cpp:257 plugin_startup

someone can help me??

**Comment by wangnan31415926** [comment]
someone can help me ?

**Comment by wangnan31415926** [comment]
i solved
./eosd --resync

**Comment by rdevkota** [comment]
Thank you. You saved my life.

**Comment by nsjames** [comment]
eosd is now nodeos

**Comment by WildDylan** [comment]
where is `eosd` under master branch?

**Comment by yefimets** [comment]
@WildDylan nodeos --resync
