### ISSUE TITLE
question

### ISSUE THREAD

**Issue by puffanddmx** [EOSIO/eos#9720]
1. The following error appears when calling rpc api while synchronizing eos blocks (light mode). What did i do wrong with the settings? (maybe block sync not working)

-centos daemon command
 nodeos --data-dir ./ --config-dir ./ --plugin eosio::chain_plugin --plugin eosio::http_plugin --plugin eosio::state_history_plugin --plugin eosio::net_plugin --validation-mode=light --access-control-allow-origin='*' --disable-replay-opts --genesis-json=./genesis.json

-daemon log
info  2020-12-01T09:12:28.738 net-0     net_plugin.cpp:1164           cancel_sync          ] sending empty request but not calling sync wait on eosbp-0.atticlab.net:9876
info  2020-12-01T09:12:28.738 net-0     net_plugin.cpp:1491           operator()           ] requesting range 6001 to 6100, from p2p.eosflare.io:9876 - 3dab7b3
info  2020-12-01T09:12:30.294 net-0     net_plugin.cpp:1491           operator()           ] requesting range 6101 to 6200, from 94.130.161.135:9876 - c79f4d3
info  2020-12-01T09:12:30.586 net-1     net_plugin.cpp:1605           recv_handshake       ] handshake from 94.130.161.135:9876 - c79f4d3, lib 155332756, head 155333082, head id 3e05b0ab7a046a3f.. sync 1

- rpc error
curl -X POST http://localhost:8888/v1/chain/get_info
{"code":404,"message":"Not Found","error":{"code":0,"name":"exception","what":"unspecified","details":[{"message":"Unknown Endpoint","file":"http_plugin.cpp","line_number":570,"method":"handle_http_request"}]}}

2. Is there a way to check reversible block information faster than other slow blockchain explorer? 

3. are there any way that i can do the fast sync? (only lightmode supported?)

**Comment by heifner** [comment]
1. You need `--plugin eosio::chain_api_plugin` for `/get_info` 
2. Not clear what you mean.
3. Syncing from genesis will be very slow. I would recommend downloading a blocks log or starting from a snapshot.
