### ISSUE TITLE
DAWN-516 ⁃ Operator new

### ISSUE THREAD

**Issue by sim31** [EOSIO/eos#973]
Operator new is currently not implemented for contracts, as far as I know. I tried to use operator and I've got this error when trying to publish a contract:
```
144300ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"10 assert_exception: Assert Exception\n!\"unresolvable\": env._Znwj\n 
```
The reason why it is needed is because, as far as I know, it's the only way to initialize dynamically allocated object in C++. I'm not aware of any other way to call a constructor on dynamically allocated memory. I thought about doing something like:
```
some_class* a = (some_class*)malloc(sizeof(some_class));
a = some_class(...);
```
But it is not safe, since assignment operator is called on `a` which usually assumes that the object is already constructed.

Placement new would be useful as well. Actually, I think placement new should be implemented first, because once you can call a constructor on some memory location, implementing simple new should be straightforward, I imagine.

**Comment by wanderingbort** [comment]
we have the appropriate compiler stubs for placement new now in the eos-noon branch.   That is the standard way to initialize dynamically allocated memory.  However, I agree that we could provide a standard new operator that safely issues the malloc and calls placement new for you.

**Comment by wanderingbort** [comment]
For reference:
> If placement_params are provided, they are passed to the allocation function as additional arguments. Such allocation functions are known as "placement new", after the standard allocation function void* operator new(std::size_t, void*), which simply returns its second argument unchanged. This is used to construct objects in allocated storage:

From http://en.cppreference.com/w/cpp/language/new

**Comment by jgiszczak** [comment]
`operator new` now provided by llvm libc++.
