### ISSUE TITLE
Build failed in ubuntu 18.04

### ISSUE THREAD

**Issue by shikhars371** [EOSIO/eos#9730]
Hi guys can any one help me with the build failing when im building from source code?

make[2]: Entering directory '/root/esoio2/eos/build'
cd /root/eosio2/eos/build/libraries/appbase && ../../../1.0/bin/cmake -P /root/eosio2/eos/build/libraries/appbase/version.cmake
fatal: No names found, cannot describe anything.
CMake Error at version.cmake:11 (message):
  git describe failed

libraries/appbase/CMakeFiles/appbase_version.dir/build.make:57: recipe for target 'libraries/appbase/CMakeFiles/appbase_version' failed
make[2]: *** [libraries/appbase/CMakeFiles/appbase_version] Error 1
make[2]: Leaving directory '/root/eosio2/eos/build'
CMakeFiles/Makefile2:2255: recipe for target 'libraries/appbase/CMakeFiles/appbase_version.dir/all' failed
make[1]: *** [libraries/appbase/CMakeFiles/appbase_version.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by nksanthosh** [comment]
can you please describe which version of eos you are trying to build? You can also use the provided scripts to build eos https://developers.eos.io/manuals/eos/latest/install/build-from-source/shell-scripts/index

**Comment by shikhars371** [comment]
2.0

**Comment by shikhars371** [comment]
can someone please help me? my code was working fine but from today when i cloned , its throwing error in building, also when on the server where the build was successfully made , i cloned that folder on the server itself and tried to do ./eosio_build.sh after deleting build bolder and uninstalling eosio, it was building fine when i copied the old folder and made build

**Comment by spoonincode** [comment]
From our telegram discussion it sounds like your problem was resolved.
