### ISSUE TITLE
Suggestion for README.md Ubuntu instructions

### ISSUE THREAD

**Issue by FortisFortuna** [EOSIO/eos#974]
For https://github.com/EOSIO/eos/blob/master/README.md
Can we add the following 
`echo "export WASM_LLVM_CONFIG=~/wasm-compiler/llvm/bin/llvm-config" >> ~/.bash_profile`

right above "Your environment is set up. Now you can build EOS and run a node."

It is there for the Mac OSX instructions, but not for Ubuntu.

**Comment by heifner** [comment]
Building script is much better now.
