### ISSUE TITLE
DAWN-309 ⁃ Standardize naming of binaries & scripts with "eosio"

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#976]
Institute naming standard for executables and scripts.  

All should begin begin with “eosio”
Ex:  eosio-launcher, eosiowd, eosio-build.sh, eosioc, eosiod 

Rename eosc to eos-walletd to eosiowd for consistency with other applications

**Comment by bytemaster** [comment]
Actually, they should be eosio-...

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Guys - in a conversation this morning, we decided to simplify this approach and call the programs:

eosiod
eosioc
eosiowd

**Comment by jgiszczak** [comment]
Completed.
