### ISSUE TITLE
--wasm-runtime Whether parameters can be switched

### ISSUE THREAD

**Issue by Black52** [EOSIO/eos#9773]
Nodeos has been syncing for three months and is now 30 million short
Current configuration：wasm-runtime = wabt 
Can I switch to  "eos-vm-jit"   use  eos-vm-oc-enable = 1,Make synchronization faster?

**Comment by heifner** [comment]
Yes, much faster.

**Comment by Black52** [comment]
> Yes, much faster.

Please Recommend a server configuration
