### ISSUE TITLE
2.1.0-rc1 doesn't compile on Ubuntu 18.04: cmake error in function ensure-libpq-and-libpqxx

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#9784]
scripts/helpers/eosio.sh function ensure-libpq-and-libpqxx doesn't work on Ubuntu 18.04

Simplified test case:

#!/bin/sh

curl -L https://github.com/jtv/libpqxx/archive/7.2.1.tar.gz | tar zxf  -
cd libpqxx-7.2.1
/usr/bin/cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql -DCMAKE_INSTALL_PREFIX=/local/lib/eosio-2.1/opt/pqxx -DSKIP_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Release -S . -B build
cmake --version

Results:

18.04 - Fail
![image](https://user-images.githubusercontent.com/26171839/102169104-7921b700-3e5f-11eb-9007-62768743e7cf.png)

20.10 - OK
![image](https://user-images.githubusercontent.com/26171839/102169116-7cb53e00-3e5f-11eb-8668-eafa5e0efae0.png)

**Comment by matthewdarwin** [comment]
Note, I left out -DCMAKE_TOOLCHAIN_FILE to simplify the test.

**Comment by huangminghuang** [comment]
It's the cmake version problem. Our build script install cmake version 3.16.x , however, you are using cmake version 3.10.2.

**Comment by matthewdarwin** [comment]
The build scripts calls specifically /usr/bin/cmake which comes from the system.  If you need a specific cmake, then build system needs to specify the location of that binary.

**Comment by matthewdarwin** [comment]
Or more correctly it uses ${CMAKE} which on my build server is set to /usr/bin/cmake.  I didn't investigate where that gets set.

**Comment by matthewdarwin** [comment]
I print out the variables in ./scripts/eosio_build.sh and it says:

CMAKE_CURRENT_VERSION=3.10.2
CMAKE_REQUIRED_VERSION=3.8

So if the system requires cmake 3.16.x, then better change the CMAKE_REQUIRED_VERSION variable.

**Comment by matthewdarwin** [comment]
CMakeLists.txt has:
cmake_minimum_required( VERSION 3.8 )

**Comment by matthewdarwin** [comment]
I change this line to 3.16 and will see if the build is successful or not.

**Comment by spoonincode** [comment]
I'm pretty sure the failure is due to the script erroneously using a cmake command line option only present in 3.13+. The actual build can be performed via 3.8 AFAIK, so the `cmake_minimum_required( VERSION 3.8 )` is accurate.

**Comment by matthewdarwin** [comment]
Ok well I leave you to sort it out.

Changing the minimum required version does cause the build script to compile cmake and when it arrives at this line of code, it is using /local/lib/eosio-2.1/bin/cmake.  Then something else fails.

**Comment by nksanthosh** [comment]
Can you try doing a `$unset CMAKE` before starting the script and seeing if that works?

**Comment by matthewdarwin** [comment]
John said the build works fine if you run on fresh ubuntu, the following commands:

~ $ mkdir -p ~/eosio && cd ~/eosio
~ $ git clone --recursive https://github.com/EOSIO/eos
~ $ cd ~/eosio/eos
~/eosio/eos $ git submodule update --init --recursive
~/eosio/eos $ git checkout v2.1.0-rc1
~/eosio/eos $ git submodule update --init --recursive
~/eosio/eos $ ls -la
~/eosio/eos $ ./scripts/eosio_build.sh -y -P 
~/eosio/eos $ cd build/bin
~/eosio/eos/build/bin $ ./nodeos --version
v2.1.0-rc1

However, if the O/S "cmake" package is installed, it still fails.  However, running `dpkg --remove cmake` first then allows the release to complete.

So it is clear the build depends on a newer version of cmake (possibly unnecessarily) and doesn't work when there is an old version available.

**Comment by sanaraufx** [comment]
Fixed in rc2.
