### ISSUE TITLE
2.1.0-rc1 build script fails to make changes to apt repo when not running as root in function ensure-libpq-and-libpqxx

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#9785]
The installer seems to assume you're root and fails when you are not

./scripts/helpers/eosio.sh: line 335: /etc/apt/sources.list.d/pgdg.list: Permission denied

Even if you are root, it should not arbitrarily modify packages on the system. The `-y` option is **not** specified to ./scripts/eosio_build.sh for this test.

**Comment by matthewdarwin** [comment]
Also given the failure the build should probably stop at this point and exit rather than failing later.

**Comment by sanaraufx** [comment]
Fixed in rc3.
