### ISSUE TITLE
Node restart is out of sync

### ISSUE THREAD

**Issue by yzn5555** [EOSIO/eos#9793]
After restarting the node recently, the node data will not be synchronized immediately, and it will take half an hour to synchronize the data，There is also a connection through the netstat command。
The server configuration of the node is relatively low. This situation occurs when the server is migrated to a high-frequency server. The original server's clock speed is lower, so replace it to a high clock server
I want to know why there is a situation of restarting the node and it takes half an hour to synchronize. Is there a way to solve this problem

**Comment by aclark-b1** [comment]
If you're working with a public network this is expected behavior as Nodeos is pulling this data from peers across the network which can be time consuming.  If this isn't the case, please reopen this issue.
