### ISSUE TITLE
Full node snapshot

### ISSUE THREAD

**Issue by Black52** [EOSIO/eos#9799]
Is there an official snapshot of the full node？？

**Comment by matthewdarwin** [comment]
This question seems more about EOS chain than EOSIO software.  Better to ask questions elsewhere.  This github is for issues on EOSIO software.

But you can download chain snapshots here provided by EOS Amsterdam.  
https://snapshots.eosamsterdam.net/

Not sure what you consider "official".

Suggest to close this issue.
