### ISSUE TITLE
EOS Block ID encryption calculation formula...

### ISSUE THREAD

**Issue by sog04004** [EOSIO/eos#9809]
Mainnet EOS

Block_Number 123 -> Block_ID 0000007b5dd0cd9fb87cf16213c8ffa4e8b903377b4d833a50a6236d

I know the block ID is SHA256.

How do I get the block ID by block number ??

I want to get it through calculation.

I'd appreciate it if you could give me an example in C++.

Thanks you !!!

**Comment by heifner** [comment]
You can calculate block number from block id, but not block id from block number.

`uint32_t block_num = fc::endian_reverse_u32(id._hash[0]);`

**Comment by heifner** [comment]
Unless you are looking for this: `controller::get_block_id_for_num`

**Comment by sog04004** [comment]
> Unless you are looking for this: `controller::get_block_id_for_num`

Is it impossible to get mainnet's get_block_id_for_num?

**Comment by heifner** [comment]
It is not clear what you are asking. Maybe try to clarify your question. 
https://t.me/joinchat/DQRZHEPktgcLlyfbl-bDuQ is a good resource for developer questions.

If you have a nodeos that is synced up then you can use `controller::get_block_id_for_num` to access the block id for a given block number.

Or you can use an api node and call `get_block_info`.

https://developers.eos.io/manuals/eosjs/latest/how-to-guides/how-to-get-block-information/?query=get_block_info&page=1#gatsby-focus-wrapper
