### ISSUE TITLE
where is the file genesis.json locate in 

### ISSUE THREAD

**Issue by ranjin** [EOSIO/eos#981]
genesis-json = /path/to/eos/source/genesis.json

i see the directory in config.ini file.  but i can't find the specific location about genesis-json
is the /Users/yourName/eos/build/scripts/testnet_np/genesis.json right?
and when i use this location and modified the file. it occurred the warning: 
`block_production_loo ] Not producing block because I don't have the private key for`
anybody can help me? thx a lot.

**Comment by heifner** [comment]
`/Users/yourName/eos` if you are trying to run a local eosd.
Please use `EOS Developers` telegram for support.
