### ISSUE TITLE
Eos Block Hash Calculation

### ISSUE THREAD

**Issue by sog04004** [EOSIO/eos#9819]
MainNet
BlockNumber 123 -> BlockHash 0000007b5dd0cd9fb87cf16213c8ffa4e8b903377b4d833a50a6236d

 BlockNumber(HEX)                     ↓↓↓↓ What?????
   0000007b               5dd0cd9fb87cf16213c8ffa4e8b903377b4d833a50a6236d

Is there a way to calculate the block hash? Or can I get the last few seats of the block hash?

Thanks you !!

**Comment by heifner** [comment]
Duplicate of #9809
