### ISSUE TITLE
NOON-366 ⁃ build error - conflict with boost

### ISSUE THREAD

**Issue by bezalel** [EOSIO/eos#984]
there is conflict with recent version of "boost" (1.66.0) installed by "brew"

-------------------------------------------------------------------------------
In file included from /Users/bwlim/Documents/__Blockchain__/eos-git/libraries/fc/src/log/gelf_appender.cpp:5:
In file included from /Users/bwlim/Documents/__Blockchain__/eos-git/libraries/fc/include/fc/log/gelf_appender.hpp:3:
/Users/bwlim/Documents/__Blockchain__/eos-git/libraries/fc/include/fc/log/appender.hpp:6:42: error: definition of type 'io_service' conflicts
      with typedef of the same name
namespace boost { namespace asio { class io_service; } }
                                         ^
/usr/local/include/boost/asio/io_service.hpp:27:20: note: 'io_service' declared here
typedef io_context io_service;
                   ^
In file included from /Users/bwlim/Documents/__Blockchain__/eos-git/libraries/fc/src/log/gelf_appender.cpp:5:
/Users/bwlim/Documents/__Blockchain__/eos-git/libraries/fc/include/fc/log/gelf_appender.hpp:7:42: error: definition of type 'io_service'
      conflicts with typedef of the same name
namespace boost { namespace asio { class io_service; } }
                                         ^
/usr/local/include/boost/asio/io_service.hpp:27:20: note: 'io_service' declared here
typedef io_context io_service;
                   ^

**Comment by kenneth** [comment]
meet same error

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

The latest tag hasn't included the fix this yet, so as today, the test is done on the master branch and ATC Pass on the master branch with head commit [https://github.com/EOSIO/eos/commit/ea09b974c89cd0072a32aa6a44264fbf48739c55](https://github.com/EOSIO/eos/commit/ea09b974c89cd0072a32aa6a44264fbf48739c55)

Revisit this again when the latest tag is released

**Comment by blockone-syncclient** [comment]
➤ Andrianto Lie commented:

Tested on the latest tag again. ATC Pass
