### ISSUE TITLE
eosio v2.1.0-rc2 showing version v2.1.0-rc1

### ISSUE THREAD

**Issue by bublik77** [EOSIO/eos#9847]
after building eosio version 2.1.0-rc2, nodeos shown as  v2.1.0-rc1
```
user@SRC_18:/opt/eos/build/programs/nodeos# ./nodeos -v
v2.1.0-rc1
user@SRC_18:/opt/eos/build/programs/nodeos# git status 
HEAD detached at v2.1.0-rc2

```

**Comment by nksanthosh** [comment]
Thank you. We will fix this unexpected behavior and retag v2.1.0-rc2. In the meanwhile please note that in your current build you can use `./nodeos --full-version` which will report the commit hash that is expected f5d73ba67475eb15c412988cdf594330c192370d

**Comment by matthewdarwin** [comment]
This one is fixed already?

**Comment by nksanthosh** [comment]
yes this is fixed and retagged at the commit hash https://github.com/EOSIO/eos/commit/4ffe96358c7a8a6dbc08733d803dd24e66638664 Thank you
