### ISSUE TITLE
I suggest canceling this submission  “Add easter egg ”

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#9848]
Why not make a separate funny contract?
I can’t understand a formal enterprise project, so I put in such a long code just to make things funny🙈

https://github.com/EOSIO/eos/commit/f5d73ba67475eb15c412988cdf594330c192370d

**Comment by 633kh4ck** [comment]
Don't be Evil (toxic) 👿

A lot of "formal enterprises" use easter eggs for a long time to add joy to a challenging work. Even a funny Easter egg can bring positive mood and additional motivation to someone, especially in the context of the upcoming holidays. It's a kind of way to express gratitude to the community.

P.S. We wish you a Merry Christmas and a happy New Year 🎄

**Comment by aclark-b1** [comment]
Well said, @633kh4ck! It was only intended to be a bit of fun, and a shout out to the community :grin:

**Comment by cppfuns** [comment]
The enterprise-level project I understand is rigorous, and I won't put such a long temporary code just because it is interesting. I don't want to revert this submission in my fork warehouse!
