### ISSUE TITLE
cnetos build rh-python36 NOT found!

### ISSUE THREAD

**Issue by TaylorChen** [EOSIO/eos#9866]
I tried to compile eos package on centos system, but the compilation prompted "rh-python36 NOT found!", but actually rh-python36 is already installed, how to fix this?
`rpm -qa | grep rh-python36`
`rh-python36-python-pip-9.0.1-5.el7.noarch`
`rh-python36-python-setuptools-36.5.0-1.el7.noarch`
`rh-python36-runtime-2.0-1.bs1.el7.aarch64`
`rh-python36-python-libs-3.6.12-1.el7.aarch64`
`rh-python36-python-3.6.12-1.el7.aarch64`

**Comment by aclark-b1** [comment]
Hello @TaylorChen,

What version of CentOS are you using, and which version of EOSIO are you trying to build?  Were you using our build scripts to compile the packages?

**Comment by TaylorChen** [comment]
> Hello @TaylorChen,
> 
> What version of CentOS are you using, and which version of EOSIO are you trying to build? Were you using our build scripts to compile the packages?

we used EOSIO  latest version package build on CentOs 7.6.64bit with ARM  system.  
`eosio_build.sh`
`eosio_build_centos.sh`
I've tried all the above compilation scripts, but I still get the same prompt.

**Comment by spoonincode** [comment]
Since EOSIO doesn't officially support ARM, the build scripts make no proper attempt at building on that architecture.

That said, the 2.0.x series will work on ARM8 last I checked, though be aware 2.1.x will not. I would recommend using a modern distro (like Debian 10 or Ubuntu 20.04) though, as it's easier to get the proper dependencies to build manually. (if you're interested in trying Debian 10 or Ubuntu 20.04 be sure to reply back here, and maybe I can help, as it's only a few commands on a distro like that)

However, be advised that EOSIO has no fast WASM runtime for ARM8 at the moment. You won't be able to run a node connected to mainnet, for example.

**Comment by TaylorChen** [comment]
> Since EOSIO doesn't officially support ARM, the build scripts make no proper attempt at building on that architecture.
> 
> That said, the 2.0.x series will work on ARM8 last I checked, though be aware 2.1.x will not. I would recommend using a modern distro (like Debian 10 or Ubuntu 20.04) though, as it's easier to get the proper dependencies to build manually. (if you're interested in trying Debian 10 or Ubuntu 20.04 be sure to reply back here, and maybe I can help, as it's only a few commands on a distro like that)
> 
> However, be advised that EOSIO has no fast WASM runtime for ARM8 at the moment. You won't be able to run a node connected to mainnet, for example.

Got it,thank you for your advice.

**Comment by TaylorChen** [comment]
build on Ubuntu or Debian platform

**Comment by Kwaskoff** [comment]
> Since EOSIO doesn't officially support ARM, the build scripts make no proper attempt at building on that architecture.
> 
> That said, the 2.0.x series will work on ARM8 last I checked, though be aware 2.1.x will not. I would recommend using a modern distro (like Debian 10 or Ubuntu 20.04) though, as it's easier to get the proper dependencies to build manually. (if you're interested in trying Debian 10 or Ubuntu 20.04 be sure to reply back here, and maybe I can help, as it's only a few commands on a distro like that)
> 
> However, be advised that EOSIO has no fast WASM runtime for ARM8 at the moment. You won't be able to run a node connected to mainnet, for example.

Can I rebuild WASM for ARM8 by myself?
