### ISSUE TITLE
Enhancement: Path-aware error for block log version error

### ISSUE THREAD

**Issue by sergmetelin** [EOSIO/eos#9871]
It would be great if errors such as this: 
<img width="1193" alt="Screenshot 2021-01-04 at 1 20 02 PM" src="https://user-images.githubusercontent.com/2141500/103566195-8f83c700-4e8f-11eb-88af-c180c0fdb1c9.png">
would also show a location of the block log.
This instance of nodeos is installed via brew, so finding where the block log is located is a bit of a research whereas it would be much easier if it's printed out.

**Comment by sanaraufx** [comment]
Fixed in 2.1 rc3.
