### ISSUE TITLE
Question: maximum block size of EOS ?

### ISSUE THREAD

**Issue by gzliudan** [EOSIO/eos#9875]
Is there block size limit in EOS ?

**Comment by heifner** [comment]
https://bloks.io/contract?tab=Tables&account=eosio&scope=eosio&table=global&limit=100
max_block_net_usage = 1048576

This can be increased. The max is currently limited by net_plugin which hardcodes a 40MB value for a max. See `def_max_write_queue_size` in net_plugin. This could easily be increased if that is still too small for your private chain.
