### ISSUE TITLE
Who can provide a way to install EOS on ubuntu 14.04?

### ISSUE THREAD

**Issue by lihailei2016** [EOSIO/eos#990]
I execute the following script, but the following error is reported, where can you provide the solution?thanks 
my ubuntu version is  14.04 ,Does anyone have such a problem?

![image](https://user-images.githubusercontent.com/18208851/34283619-bff4704e-e707-11e7-8dc6-5385d34d80ed.png)

![image](https://user-images.githubusercontent.com/18208851/34283598-9dd8a048-e707-11e7-88da-3b3abe5e4550.png)

**Comment by gaolitao** [comment]
the issue of 14.10 is that the git version is low, so i suggest you use docker run from ubuntu 16.10 from your current ubuntu 14.10 machine.

and the issue you met about clang-4.0 is related the network issue, you need to find a VPN tunnel for you machine.

**Comment by remcoros** [comment]
even with clang-4.0 for ubuntu 14 working I got hard compile errors. probably because of older gcc or other dependencies. I suggest moving to ubuntu 16, docker or a virtual machine or something.

**Comment by lihailei2016** [comment]
@remcoros @gaolitao   thanks，I've used your recommendation to run eosd and wallet services in the docker

**Comment by asiniscalchi** [comment]
Look at the travis CI log: it builds EOS on 14.04
