### ISSUE TITLE
improve release notes by highlighting minor features

### ISSUE THREAD

**Issue by matthewdarwin** [EOSIO/eos#9903]
nodeos 2.1.0-rc1 has a lot of great minor features, but they are buried in the "Other Changes" section of the release notes and difficult to find. (https://github.com/EOSIO/eos/releases/tag/v2.1.0-rc1)  This is a huge understatement of all the engineering effort put into this release.

There should be another section in the release notes that highlights these features for all feature releases going forward.  Eg for 2.1.0, it might look like this:

Other Enhancements:
- Allow blocks.log to be split into chunks
- Allow ship to be split into chunks
- New resource monitor
- Allow restrict the max number of concurrent HTTP requests
- etc..

**Comment by aclark-b1** [comment]
Thank you for the suggestion @matthewdarwin!  We'll be more diligent with this next time.
