### ISSUE TITLE
build broken for Mac OS 10.12

### ISSUE THREAD

**Issue by kmanikumar** [EOSIO/eos#992]
failing to build EOS on this step. anyone know how to fix this issue? 

> /Users/kmanikumar/eos/libraries/fc/include/fc/log/appender.hpp:6:42: error: definition of type 'io_service' conflicts with typedef of the same name
namespace boost { namespace asio { class io_service; } }
                                         ^
/usr/local/include/boost/asio/io_service.hpp:27:20: note: 'io_service' declared here
typedef io_context io_service;
                   ^
In file included from /Users/kmanikumar/eos/libraries/fc/src/log/gelf_appender.cpp:5:
/Users/kmanikumar/eos/libraries/fc/include/fc/log/gelf_appender.hpp:7:42: error: definition of type 'io_service' conflicts with typedef of the same name
namespace boost { namespace asio { class io_service; } }
                                         ^
/usr/local/include/boost/asio/io_service.hpp:27:20: note: 'io_service' declared here
typedef io_context io_service;
                   ^
In file included from /Users/kmanikumar/eos/libraries/fc/src/log/gelf_appender.cpp:5:
/Users/kmanikumar/eos/libraries/fc/include/fc/log/gelf_appender.hpp:31:10: warning: 'initialize' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    void initialize(boost::asio::io_service& io_service);
         ^
/Users/kmanikumar/eos/libraries/fc/include/fc/log/appender.hpp:44:23: note: overridden virtual function is here
         virtual void initialize( boost::asio::io_service& io_service ) = 0;
                      ^
In file included from /Users/kmanikumar/eos/libraries/fc/src/log/logger_config.cpp:8:
/Users/kmanikumar/eos/libraries/fc/include/fc/log/gelf_appender.hpp:31:10: warning: 'initialize' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    void initialize(boost::asio::io_service& io_service);
         ^
/Users/kmanikumar/eos/libraries/fc/include/fc/log/appender.hpp:44:23: note: overridden virtual function is here
         virtual void initialize( boost::asio::io_service& io_service ) = 0;
                      ^
[ 37%] Building CXX object libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/Linker.cpp.o
Scanning dependencies of target WASM
[ 38%] Building CXX object libraries/wasm-jit/Source/WASM/CMakeFiles/WASM.dir/WASMSerialization.cpp.o
1 warning and 2 errors generated.
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/src/log/gelf_appender.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 38%] Building CXX object libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/LLVMEmitIR.cpp.o
[ 39%] Building CXX object libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/LLVMJIT.cpp.o
1 warning generated.
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 39%] Building CXX object libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/Memory.cpp.o
[ 39%] Building CXX object libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/ModuleInstance.cpp.o
[ 40%] Building CXX object libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/ObjectGC.cpp.o
[ 40%] Linking CXX static library libWASM.a
[ 40%] Built target WASM
[ 40%] Building CXX object libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/Runtime.cpp.o
[ 41%] Building CXX object libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/Table.cpp.o
[ 41%] Building CXX object libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/Threads.cpp.o
[ 41%] Building CXX object libraries/wasm-jit/Source/Runtime/CMakeFiles/Runtime.dir/WAVMIntrinsics.cpp.o
[ 42%] Linking CXX static library libRuntime.a
[ 42%] Built target Runtime
make: *** [all] Error 2

**Comment by ixxxxxx** [comment]
same error, likes the issue #984 is related.

**Comment by kmanikumar** [comment]
@ixxxxxx thanks, didn't recognize that it was a collision with boost. Can I fix by downgrading boost?

**Comment by kmanikumar** [comment]
closing as redundant, track #984 as @ixxxxxx mentioned above
