### ISSUE TITLE
rotate log file

### ISSUE THREAD

**Issue by gzliudan** [EOSIO/eos#9920]
Can log file be ratated in nodeos? Such as rotate per day or 10MB ?

**Comment by matthewdarwin** [comment]
If you send the nodeos log files to sylog, then the normal processes work `nodeos  | logger`.  Or use systemd.

**Comment by gaboesquivel** [comment]
you can use [logrotate](https://linux.die.net/man/8/logrotate)

This is what I use. 
```
/paht/to/eos-node/logs/*.log {
    daily
    missingok
    rotate 2
    compress
    notifempty
    create 0640 ubuntu ubuntu
}
```

https://www.digitalocean.com/community/tutorials/how-to-manage-logfiles-with-logrotate-on-ubuntu-16-04

**Comment by aclark-b1** [comment]
There's new functionality in 2.1 that might help with this as well.  Please take a look at https://github.com/EOSIO/eos/pull/9184.
