### ISSUE TITLE
Exchange Add Memo Verification？

### ISSUE THREAD

**Issue by machine-creek** [EOSIO/eos#9924]
Exchange recharge address, need to add memo mandatory verification.
How to do it.

Binancecleos This is the address where the memo has been added. How to check the address where the memo has been added?

**Comment by heifner** [comment]
It is not clear what you are asking. You can see transfers here: https://bloks.io/account/binancecleos

**Comment by machine-creek** [comment]
> 目前尚不清楚您在问什么。您可以在此处查看转帐：[https](https://bloks.io/account/binancecleos)：[//bloks.io/account/binancecleos](https://bloks.io/account/binancecleos)


Send the EOS to the Binancecleos account, and the broadcast node returns an error message.
{
    "code":500,
    "message":"500 - {"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: Memo has to be exactly 8 symbols long and contain only digits","file":"wasm_interface.cpp","line_number":1075,"method":"eosio_assert"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":113,"method":"exec_one"}]}}",
    "data":null
}

**Comment by machine-creek** [comment]
> It is not clear what you are asking. You can see transfers here: https://bloks.io/account/binancecleos

Send the EOS to the Binancecleos account, and the broadcast node returns an error message.
{
"code":500,
"message":"500 - {"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: Memo has to be exactly 8 symbols long and contain only digits","file":"wasm_interface.cpp","line_number":1075,"method":"eosio_assert"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":113,"method":"exec_one"}]}}",
"data":null
}

**Comment by heifner** [comment]
You need to contact Binance to determine what they require in their transfer memo.
Their contract is reporting error: "Memo has to be exactly 8 symbols long and contain only digits"

**Comment by machine-creek** [comment]
> You need to contact Binance to determine what they require in their transfer memo.
> Their contract is reporting error: "Memo has to be exactly 8 symbols long and contain only digits"

I want to add this MEMO verification to the account I created.

**Comment by heifner** [comment]
You might find this helpful:
https://developers.eos.io/welcome/v2.0/getting-started/smart-contract-development/payable_actions
Google search for "eosio example memo verification" found a lot of useful info including:
https://github.com/eosauthority/incoming-transfer-rules/blob/master/transferfilter.cpp

**Comment by machine-creek** [comment]
> You might find this helpful:
> https://developers.eos.io/welcome/v2.0/getting-started/smart-contract-development/payable_actions
> Google search for "eosio example memo verification" found a lot of useful info including:
> https://github.com/eosauthority/incoming-transfer-rules/blob/master/transferfilter.cpp

Thank you very much. I'll have a try。
