### ISSUE TITLE
国内节点同步速度非常慢

### ISSUE THREAD

**Issue by garden2weini** [EOSIO/eos#9999]
无论是通过全量同步还是基于快照同步，同步速度都非常慢，甚至慢于出块速度
尝试方式：
1、将https://eosnodes.privex.io/?config=1的p2p-peer-address加入到eos启动参数
2、遍历获取https://bloks.io/bpjson各节点/bp.json，并收集p2p_endpoint信息，然后通过手动方式添加同步节点
cleos net disconnect $p2p_endpoint
cleos net connect $p2p_endpoint
3、调整启动参数
--chain-state-db-size-mb=655360
--wasm-runtime=eos-vm-jit
--eos-vm-oc-enable
--plugin=eosio::history_api_plugin
--plugin=eosio::state_history_plugin
--state-history-endpoint=0.0.0.0:8080
--trace-history
--chain-state-history
--disable-replay-opts
--filter-on=* （需要获取所有账户及交易信息）
备注：
1、eosio version is 2.0.7
2、节点通过docker容器启动，数据盘非SSD，宿主机内存48G
3、服务器为中国大陆阿里云服务器
调整后同步速度依旧非常慢

**Comment by spoonincode** [comment]
如果数据磁盘 _不是_ SSD，则使用48G时，我建议设置chain-state-db-size-mb = 32768和database-map-mode = heap

您将需要删除节点数据目录并使用快照重新启动，以便将chain-state-db-size-mb从655360更改为32768并生效

**Comment by garden2weini** [comment]
> 如果数据磁盘 _不是_ SSD，则使用48G时，我建议设置chain-state-db-size-mb = 32768和database-map-mode = heap
> 
> 您将需要删除节点数据目录并使用快照重新启动，以便将chain-state-db-size-mb从655360更改为32768并生效
1、目前基于snapshot-2021-01-30导入做的，同步一天后/data/state/shared_memory.bin 实际大小就近90G，可以先试试chain-state-db-size-mb=102400
2、database-map-mode = heap，在快照模式下提示配置错误
BTW：请问，EOS磁盘改成SSD同步和访问速度会有很大改善吗？

**Comment by aclark-b1** [comment]
看来您正在运行已过时的history_api_plugin，它可能会增加负载并降低速度。 您可能想尝试禁用插件，看看是否有帮助。
